### ISSUE TITLE
Homepage missing focus styles

### ISSUE THREAD

**Issue by missmatsuko** [chakra-ui/chakra-ui#10]
On [chakra-ui.com](https://chakra-ui.com/), the logo link in the header and the social media links in the footer don't have a prominent style when focused (e.g. an outline).

**Comment by claeusdev** [comment]
Hey @missmatsuko this is something i also noticed, care to open a PR or i'd open one and you can verify if that's what you mean.

**Comment by segunadebayo** [comment]
I've resolved this. Thanks lot guys.

I'll update the docs shortly.
