### ISSUE TITLE
Add documentation around controlled vs uncontrolled components and `useControllableState`

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1008]
Most Chakra components that handle input follow the standard React patterns of [controlled](https://reactjs.org/docs/forms.html#controlled-components) vs. [uncontrolled](https://reactjs.org/docs/uncontrolled-components.html) components. This distinction should be noted in our documentation.

It's also important to note that most Chakra components utilize an internal utility ([`useControllableState`](https://github.com/chakra-ui/chakra-ui/blob/605407eaf5c0a678ef44357c55568658f4fbb02d/packages/hooks/src/use-controllable.ts#L56-L117)) for seamlessly managing regardless of whether it's controlled or uncontrolled. We should document implications of this utility, like that fact that we throw warnings when a component attempts to switch between controlled or controlled props, and how to handle that warning if you run into it.

**Comment by segunadebayo** [comment]
Working on this now!

**Comment by segunadebayo** [comment]
Done!
