### ISSUE TITLE
NumberInput border-color is using default browser black

### ISSUE THREAD

**Issue by aaronmcadam** [chakra-ui/chakra-ui#101]
Firstly, thanks for a great design system!

I can see it is setting `border-color` to `inherit`, but when I do set `borderColor`, only the outer border changes, not the stepper buttons.

I'm using the `CSSReset` component, so I should be getting the `gray.200` colour instead, right?

See the following screen capture:

![CleanShot 2019-09-19 at 16 15 52](https://user-images.githubusercontent.com/37928/65257349-fe9da680-daf8-11e9-8574-e0824209094b.gif)

**Comment by segunadebayo** [comment]
Hi @aaronmcadam,

Yes you should be getting the `gray.200` color instead. Can you send a codesandbox link so I can look into this and fix it?

I'll also improve the `NumberInput` so that passing the `borderColor` should propagate to the stepper buttons, or find better ways to pull out those buttons so you can have complete control over how they look.

Thanks for this feedback. Kindly send me a link.

**Comment by aaronmcadam** [comment]
Hi @segunadebayo, thanks!

Here's the sandbox link: https://codesandbox.io/embed/vigorous-platform-5lppf

**Comment by aaronmcadam** [comment]
There's another thing I noticed about the `NumberInput`. I'm setting the min to `1`, but when I select all (cmd + a) and delete, the value is set to 0. This is invalid for my business rule.

Here's a screen capture (it's from the codesandbox above (https://codesandbox.io/embed/vigorous-platform-5lppf)):
![CleanShot 2019-09-19 at 17 11 44](https://user-images.githubusercontent.com/37928/65261729-ca2de880-db00-11e9-8fcd-134e6ac0955b.gif)

**Comment by segunadebayo** [comment]
@aaronmcadam ,

I've confirmed the issue. For now, you might need to specify the config for both the light and dark mode. I saw you that you've figured it out. In the next version, I'll provide the `defaultConfig` as a second parameter so you can just override some parts of it.

**Comment by aaronmcadam** [comment]
@segunadebayo thanks for taking a look! Should I file the other issue about deleting the selection separately?

**Comment by segunadebayo** [comment]
@aaronmcadam Let's talk about that deleting. What's the expected outcome in this case? It should fallback to the `min`, right?

**Comment by aaronmcadam** [comment]
@segunadebayo Yes, I think that's what users would expect. Do you have a way to organise and prioritise these small fixes?

**Comment by segunadebayo** [comment]
@aaronmcadam ,

At the moment, I don't. I typically just pick which fixes I think are critical and fix them. I'll appreciate your contribution.

As for the NumberInput, I'll look into it soon.

**Comment by aaronmcadam** [comment]
Thanks @segunadebayo! I'll be happy to help with stuff going forward!

**Comment by Ronva** [comment]
Sounds like we should set up a `useEffect` hook that watches the value and sets it to the minimum or 0 if it's ever invalid, right? This would be something good to add to the unit/integration tests once that stuff gets merged in.

**Comment by segunadebayo** [comment]
I believe the recent release addressed this issue by providing a more declarative API so you can style the number input's field and steppers.

I'll close this now. Thanks
