### ISSUE TITLE
[Collapse] Duration prop is not applying

### ISSUE THREAD

**Issue by cereallarceny** [chakra-ui/chakra-ui#1017]
**Describe the bug** No matter what I do, changing the `duration` value on a `<Collapse />` component doesn't seem to have any effect

**Expected Behavior** ... it should have an effect

**Link to minimal reproduction** https://codesandbox.io/s/eloquent-lumiere-0glyc?fontsize=14&hidenavigation=1&theme=dark

**Steps to Reproduce**:
1. Create a `<Collapse>` and fill it with a lot of content
2. Add a `duration` prop and set to some high value, say 10 seconds (`10000`)

**Suggested solution(s)** N/A

**Desktop (please complete the following information):**

- OS: Mac OS 10.15.5
- Browser: Chrome 83

**Additional context** N/A

**Comment by jmiazga** [comment]
It looks like the docs need to be updated. Instead of the `duration` prop you can use the `timeout` prop.

Tomorrow I will try and make a PR to fix the docs to reflect the changes to the `Collapse` component.

**Comment by segunadebayo** [comment]
I've reverted `Collpase` to use `react-animate-height` just like `v0.8`. I noticed some lag/sluggishness in the transitions when using `react-transition-group`.

This prop should now work as expected.

Thanks guys.

**Comment by oncet** [comment]
This is what I was looking for:

`transition={{ enter: { duration: 5 } }}`

Thanks for such great tool!

**Comment by avalanche1** [comment]
@oncet doesnt work for me :(

**Comment by avalanche1** [comment]
@segunadebayo there is still now visible way in the docs to modify transition duration

**Comment by JvSe** [comment]
@oncet it's work for me !! thankss

**Comment by mahdimirmohamadi** [comment]
> This is what I was looking for:
> 
> `transition={{ enter: { duration: 5 } }}`
> 
> Thanks for such great tool!



thanks for this but how can I make an exit animation? 

i'm using the <Collapse /> component and its entering animation works perfectly fine but for exiting it's like there's no animating and transition at all. 

this is how i use it:
`<Collapse
      startingHeight={150}
      in={isOpen}
      transition={{
        enter: { duration: 0.75},
        exit: {
          duration: 0.75,
        },
      }}
    >`
