### ISSUE TITLE
CodeSandbox starters for submitting issues

### ISSUE THREAD

**Issue by aaronmcadam** [chakra-ui/chakra-ui#102]
I've noticed that a lot of times, codesandbox reproductions are really useful.

Having starters may reduce the barrier for people reporting bugs and ideas: 

- [ ] JavaScript: https://codesandbox.io/s/epic-zhukovsky-27i2n
- [ ] TypeScript: 
- [ ] TypeScript Next.js:

**Comment by aaronmcadam** [comment]
@segunadebayo I was going to raise a PR, but it looks like the CONTRIBUTING.md file is a bit of a work in progress.

**Comment by segunadebayo** [comment]
Hi @aaronmcadam ,

What changes would you recommend to the CONTRIBUTING.md? Kindly raise a PR and I'll review it.

**Comment by segunadebayo** [comment]
I think it'll make sense to add a starter for CRA Typescript and Next Typescript as well. So we can jump right in to confirm any bug.

**Comment by aaronmcadam** [comment]
@segunadebayo do we need to create these through an official chakra-ui Code Sandbox account?

**Comment by segunadebayo** [comment]
@aaronmcadam Sure, I'll create the starters using a `chakra-ui` or my personal CodeSandbox account and update the links.

**Comment by astahmer** [comment]
Well, if you're still interested in a CodeSandbox for Next JS + Typescript + Chakra-UI, I just made this : https://codesandbox.io/s/github/astahmer/sandbox-next-ts-chakra

**Comment by segunadebayo** [comment]
Thanks for adding this @astahmer
