### ISSUE TITLE
[Stack] Cannot reverse direction of a Stack

### ISSUE THREAD

**Issue by cereallarceny** [chakra-ui/chakra-ui#1021]
**Describe the bug** When using the `<Stack>` component, I cannot make use of `row-reverse` and `column-reverse` on the `direction` prop. This seems somewhat at odds with the documentation which states it can receive a flex direction value, when the source code and Typescript types indicate it can only receive a `row` and `column`.

**Expected Behavior** I should be able to use `row-reverse` and `row-column`

**Link to minimal reproduction** https://codesandbox.io/s/wonderful-grass-0rzvo?fontsize=14&hidenavigation=1&theme=dark

**Steps to Reproduce**:
1. Create a `<Stack>` and fill it with lots of boxes
2. Change the direction prop to `row-reverse` or `column-reverse`

**Suggested solution(s)** Just allow those types in Typescript :)

**Desktop (please complete the following information):**

- OS: Mac OS 10.15.5
- Browser: Chrome 83

**Additional context** N/A

**Comment by santialbo** [comment]
The margin calculation would also need to account for these new options
https://github.com/chakra-ui/chakra-ui/blob/2782e4d280c10fd7298a738895d71bf84c247038/packages/layout/src/stack.tsx#L97-L103
