### ISSUE TITLE
[Toast] Toast does not appear to have any styles

### ISSUE THREAD

**Issue by cereallarceny** [chakra-ui/chakra-ui#1022]
**Describe the bug** When using `useToast`, none of the default styles are applied. In fact, there is no toast.ts file in the @chakra-ui/theme package at all.

**Expected Behavior** I should have the toast look like a toast on the website

**Link to minimal reproduction** https://codesandbox.io/s/funny-snyder-bm1r9?fontsize=14&hidenavigation=1&theme=dark

**Steps to Reproduce**:
See reproduction above.

**Suggested solution(s)** Add some default styles

**Desktop (please complete the following information):**

- OS: Mac OS 10.15.5
- Browser: Chrome 83

**Additional context**
![Screen Shot 2020-06-29 at 12 09 31 PM](https://user-images.githubusercontent.com/1297930/85997436-675b6d00-ba01-11ea-8ad4-bcd06831be25.png)

**Comment by segunadebayo** [comment]
Hi @cereallarceny,

The `useToast` hook needs access to the theme in `ChakraProvider`. The way you set this up, `useToast` is above the provider that's why you can't see any styles.

To fix this, move the `ChakraProvider` and `CSSReset` to the `index.js` file.

PS: The reason there's no toast.ts is that `Toast` re-uses the styles from the alert theme.

**Comment by segunadebayo** [comment]
Here's an adjusted version: https://codesandbox.io/s/heuristic-brown-b51fb?file=/src/App.tsx

**Comment by cereallarceny** [comment]
That's weird @segunadebayo because I'm doing that in Storybook and it also isn't working:

- [Toast storybook](https://github.com/OpenMined/omui/blob/master/omui/src/components/toast/toast.stories.js)
- [Wrapping whole storybook in a theme](https://github.com/OpenMined/omui/blob/master/omui/.storybook/preview.tsx#L7)
- [Theme component](https://github.com/OpenMined/omui/blob/master/omui/src/components/theme/theme.tsx)

This seems to work perfectly for every other component in my Storybook, except for toast.

**Comment by with-heart** [comment]
@cereallarceny I'll reopen to make sure we don't miss checking that out.

**Comment by segunadebayo** [comment]
That's weird, it should work.

@cereallarceny can you update this line: https://github.com/OpenMined/omui/blob/4211a32df75c3541428d2ed32ec323a3466e5cb4/omui/.storybook/preview.tsx#L8 to this:

```jsx
addDecorator((StoryFn) => (
  <Theme>
    <Box p={6}>
      <StoryFn />
    </Box>
  </Theme>
));
```

Let me know if it works. I've faced this issue once with Storybook.

**Comment by segunadebayo** [comment]
@with-heart It's not exactly a tooling issue, it's mostly with Storybook. Once @cereallarceny confirms it works, we'll close it.

Thanks

**Comment by with-heart** [comment]
Ah well, I've been considering storybook stuff to be tooling!

**Comment by cereallarceny** [comment]
It does throw a Typescript error:

```
ERROR in /Users/cereallarceny/Development/openmined/code/omui/omui/.storybook/preview.tsx
./.storybook/preview.tsx
[tsl] ERROR in /Users/cereallarceny/Development/openmined/code/omui/omui/.storybook/preview.tsx(9,8)
      TS2739: Type '{}' is missing the following properties from type 'StoryContext': id, name, kind, parameters
```

But throwing a @ts-ignore on it solves that problem. Any idea what this could be? I'm able to get styles now, but I am still curious about the TS error.

**Comment by segunadebayo** [comment]
@cereallarceny, Glad you can see the styles now.

For the TS error, you might have to change the type of `StoryFn`, I wasn't able to figure out the correct type so I just put `Function` for now.

Cheers buddy.
