### ISSUE TITLE
[Button] Negative margin given to leftIcon and rightIcon element

### ISSUE THREAD

**Issue by mr-wildcard** [chakra-ui/chakra-ui#1024]
**Describe the bug**

Any element provided to `Button`'s `leftIcon` or `rightIcon` props appears slightly shifted.
I'm currently using Chakra's Icon as button's icons.

**Expected Behavior**

Margin shouldn't be hardcoded inside component.

**Link to minimal reproduction**

https://codesandbox.io/s/sweet-star-vltyj

Value is hardcoded in `Button.tsx` source code : https://github.com/chakra-ui/chakra-ui/blob/master/packages/button/src/button.tsx#L132

**Suggested solution(s)**

Remove hardcoded negative margin values. It should be developer responsibility to define element boxes.
Or am I missing some Chakra UI context ? ;)

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: 83.0.4103.116

**Additional context** 

Currently migrating from `@chakra-ui/core@0.8.0` to `1.0.0-next.3`.

**Comment by with-heart** [comment]
Interesting! I've modified your CodeSandbox to show a few more examples: https://codesandbox.io/s/charming-sky-cjr4n?file=/src/index.tsx

We can set `ml={1}` inside `leftIcon` to negate the negative margin, and I think you're right. The negated versions look better than the versions with the negative margins. Not sure what the purpose of the negative margin is, but we can take a look.

**Comment by mr-wildcard** [comment]
thanks for your reply @with-heart 

Also, this can be fixed by moving the icon as a `Button`'s child but require a bit more JSX to add spacing between its children.

**Comment by segunadebayo** [comment]
Thanks for reporting this @mr-wildcard.

After reviewing this from a design perspective, I think it looks better without the negative margins.

**Comment by nassimbenkirane** [comment]
Hi everyone !

I'm currently _adding_ a bunch of mr={-1} or ml={-1} to the leftIcons and rightIcons, and I'm thinking maybe this could be even better if it was defined as a theme "part" on the button theme definition. This would allow us to define the behaviour of those icons on the theme level rather than when using the component.

I don't know if this is the right place to comment on that, but I would be interested in your thoughts 😄
