### ISSUE TITLE
Incorrect "spacing" prop-types in ButtonGroup

### ISSUE THREAD

**Issue by majorhayes** [chakra-ui/chakra-ui#103]
https://github.com/chakra-ui/chakra-ui/blob/9f319cd0ce38d155960cd6f778447b39ab40b898/packages/chakra-ui/src/ButtonGroup/index.js#L50

This prop-type definition is wrong because StyledSystem supports passing in objects and arrays for MarginProps for responsive formatting.  This invalid prop-type causes a console error to show up when using the responsive object or array syntax.

Example:
```js
<ButtonGroup spacing={[2, 4]}>
// ...
</ButtonGroup>
```

**Comment by segunadebayo** [comment]
Hi @majorhayes,

I agree. `styled-system` allows passing Objects or Arrays.

I'll remove the propTypes from all components. I guess I skipped the `ButtonGroup` component.

Thanks for catching this.

**Comment by segunadebayo** [comment]
Kindly upgrade to the v0.3.2. I've resolved this issue there.
