### ISSUE TITLE
Can I Import the styles props 

### ISSUE THREAD

**Issue by abdallahalaa21** [chakra-ui/chakra-ui#1035]
I was doing a reusable component with chakra , but I need to export the CSS props to the component 
that I can reuse it again at my reusable component and pass it to chakra component
as I may use the button sometimes with a lot of changes and I don`t want to add the shared  props 

so Is there a way to edit the component and make it global to all the app or export the style props types

**Comment by segunadebayo** [comment]
Hi @abdallahalaa21,

I don't understand what you mean, can you show a code snippet so I can help you better?

**Comment by abdallahalaa21** [comment]
`const Btn = ({ rounded, bg, title }) => (
  <Box
    as="button"
    rounded={rounded ?? 'md'}
    bg={bg ?? 'bg.900'}
    color="white"
    px={4}
    h={8}
  >
    {title}
  </Box>
);`

this is a reusable component for example, 
is there a way to export all the props add to Box to my Component to get the intellisense at my btn ?
or is there a way to modify the chakra button like adding colors

**Comment by with-heart** [comment]
```jsx
import {BoxProps} from '@chakra-ui/core'

const Btn = ({rounded = 'md', bg = 'bg.900', title}: BoxProps) => (
  <Box as="button" rounded={rounded} bg={bg} color="white" px={4} h={8}>
    {title}
  </Box>
)
```

You can also add colors or modify the existing theme as you please. See the docs for the component theming api for more information: https://next.chakra-ui.com/docs/theming/overview

**Comment by abdallahalaa21** [comment]
@with-heart  I tried it at Version : "0.8.0"

I`ll upgrade to the latest beta, thank you
