### ISSUE TITLE
[Stack] Default CSS property `align-items` value

### ISSUE THREAD

**Issue by mr-wildcard** [chakra-ui/chakra-ui#1046]
**Describe the bug**

`Stack` default flex layout uses `align-items: flex-start`, constraining inherent display of children.
In my case, I have a vertical `Stack` and all elements appears crushed to the left.

<img width="551" alt="Capture d’écran 2020-06-30 à 15 06 33" src="https://user-images.githubusercontent.com/6979207/86129673-613dbd00-bae3-11ea-9892-9125995c7c86.png">

**Expected Behavior**

HTML _block_ element inside a `Stack`  component should take 100% width.

**Link to minimal reproduction** 
https://codesandbox.io/s/chakra-v1-stack-vertical-fffsf

**Suggested solution(s)**
Don't specify `align-items` property at all and let developer handle it.

**Desktop**

- OS: macOS
- Browser: Chrome
- Version: 83.0.4103.116

**Additional context**
Currently migrating from `@chakra-ui/core@0.8.0` to `1.0.0-next.3`.

**Comment by with-heart** [comment]
@mr-wildcard Those buttons are so freaking cute! I love them!

**Comment by mr-wildcard** [comment]
thanks ! those are actually gifs ;)
![Jun-30-2020 17-12-32](https://user-images.githubusercontent.com/6979207/86143605-ef6e6f00-baf4-11ea-91d0-37768582a591.gif)
