### ISSUE TITLE
[Text] Type Definition 'isTruncated'

### ISSUE THREAD

**Issue by xtalx** [chakra-ui/chakra-ui#105]
Hi. You've done really nice work on the library. I'm giving it a spin on a project and it looks like the types for the Text component might need some tweaking. 

The component renders/functions properly but if you're using TypeScript the `isTruncated` prop causes a compiler error (with create react app typescript). It looks like the other styled-system props work though. My TypeScript skills are super basic but I'll see if I can find a fix and submit a PR.

Thanks!

Here is a [CodeSandbox](https://codesandbox.io/s/naughty-dream-jmm1d) showing the issue, although the CodeSandbox setup still compiles.

```Type '{ children: string; isTruncated: true; }' is not assignable to type 'IntrinsicAttributes & RefAttributes<HTMLElement> & HTMLAttributes<HTMLElement> & LayoutProps & ColorProps & SpaceProps<string | number> & BordersProps & BackgroundProps<string | number> & ... 12 )```

**Comment by segunadebayo** [comment]
Thanks for your PR and suggestion, Tal.

I've resolved this as discussed and will release a patch soon.

**Comment by segunadebayo** [comment]
I have released the patch v0.3.1 that resolves this.

Kindly upgrade accordingly.
