### ISSUE TITLE
Button focus state box-shadow based on the variant

### ISSUE THREAD

**Issue by jyash97** [chakra-ui/chakra-ui#1055]
**What problem does this feature solve?** 

I am working on an application where I am using green color in the `Button` variant. And when I focus the button the box-shadow is of blue color which doesn't blend well with the theme (green). For eg: 

![image](https://user-images.githubusercontent.com/22376783/86158645-b5b65c00-bb26-11ea-9a15-c33e1ea7e9bf.png)

 

**What does the proposed API look like?** 

How about having the same variant color box-shadow as bootstrap does it.

**Additional context** 

Great work on the library 💯  Really loving the API and the composability feature ✨ 

I can help with this issue if it make sense. :)

**Comment by segunadebayo** [comment]
Hi @jyash97,

I'm glad to hear that you're loving Chakra so far.

For this issue, we've solved this problem in the v1 pre-release (1.0.0-next.3) and you read about it [here](next.chakra-ui.com).

Basically, we've moved the styles for all components to the theme so you can be in 100% control of them. We also created a simple API for theming components.

Here's an example: https://github.com/chakra-ui/chakra-ui/blob/master/packages/theme/src/components/button.ts

Hope this helps?

PS: In the meantime, you can pass the `_focus` prop to the button component and change it's `boxShadow`

```jsx
<Button _focus={{ boxShadow: "..." }}>New Customer</Button>
```

**Comment by jyash97** [comment]
> and you read about it here.

Not able to access the `here` link. Looks like the link doesn't redirect anywhere. I am happy to use the next version if it is ready or at least the API is final. 

How it will work in the next version? 

> PS: In the meantime, you can pass the _focus prop to the button component and change it's boxShadow

This will help me for now. Thanks, I kind of missed this from the docs.

**Comment by with-heart** [comment]
@jyash97 I think the link should have been to https://next.chakra-ui.com/.

Specifically you can see https://next.chakra-ui.com/docs/getting-started for docs on using the cli to generate the theme locally.
