### ISSUE TITLE
npx chakra-cli init --theme to prettify the files after adding

### ISSUE THREAD

**Issue by capaj** [chakra-ui/chakra-ui#1062]
So I was thinking-when doing ` npx chakra-cli init --theme` I get back all the files, but they do not match my project's prettier config. Would be super nice if they get added and formatted right away with the correct prettier config.

**What problem does this feature solve?** 
just a convenience for the user of the cli

**What does the proposed API look like?** 
no new API

**Describe alternatives you've considered** 
Everyone could prettify it on their own, but this is a hassle

**Additional context**

**Comment by segunadebayo** [comment]
Hi @capaj,

I like this idea. Please move this issue to https://github.com/chakra-ui/chakra-cli

It'll help us stay organized. Thank you
