### ISSUE TITLE
Request to add a way to disable/configure Accordion/Collapse transition

### ISSUE THREAD

**Issue by tafelito** [chakra-ui/chakra-ui#1075]
It would be great to have a way to either disable Collapse default height transition or at least pass a custom config. Right now I haven't found a way to do this in version 0.8 nor in v1.

**Comment by segunadebayo** [comment]
Thanks for this issue @tafelito.

I've added an option to disable the collapse transition for the accordion component. For now, we can't provide an option to configure the transition for now.

Thanks. We'll publish an update shortly
