### ISSUE TITLE
[Textarea] Erroneous warning when `readOnly` is present

### ISSUE THREAD

**Issue by feross** [chakra-ui/chakra-ui#1077]
**Describe the bug** A clear and concise description of what the bug is.

This prints:

```
Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
```

with this code:

```
          <Textarea
            value={JSON.stringify(stats.db, null, 2)}
            size='sm'
            height='sm'
            readOnly
          />
```

**Expected Behavior** A clear and concise description of what you expected to
happen.

No warning should print since I actually set `readOnly`.

**Link to minimal reproduction** Please provide a codesandbox link or GitHub
repo with a minimal reproduction of the issue.

https://codesandbox.io/s/strange-hypatia-85p8x?file=/src/index.tsx

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 83

**Additional context** Add any other context about the problem here, or some
background information of how you ran into this bug.

**Comment by segunadebayo** [comment]
Hi @feross,

I've resolved this and the fix will be included in the next pre-release. For now, kindly change `readOnly` to `isReadOnly`.
