### ISSUE TITLE
[Avatar] Avatar component not updated on src change

### ISSUE THREAD

**Issue by ima-s** [chakra-ui/chakra-ui#1079]
**Describe the bug** 
`Avatar` with `src={undefined}` not updated on `src` change.

**Expected Behavior**
On `src` change, `Avatar` should render image from updated `src`.

**Link to minimal reproduction** 

https://codesandbox.io/embed/stupefied-hertz-6hkw9?fontsize=14&hidenavigation=1&theme=dark

**Suggested solution(s)**

This happens due to wrong `status` in `useImage`.

```
export function useImage(props: UseImageProps) {
  const {
    src,
    srcSet,
    onLoad,
    onError,
    crossOrigin,
    sizes,
    ignoreFallback,
  } = props

  // this status should be "loading" on src change
  const [status, setStatus] = React.useState<Status>(() => {
    return src ? "loading" : "pending"
  })
...
```

A simple solution is to update `status` on `src` change.

```
export function useImage(props: UseImageProps) {
  const {
    src,
    srcSet,
    onLoad,
    onError,
    crossOrigin,
    sizes,
    ignoreFallback,
  } = props

  const [status, setStatus] = React.useState<Status>(() => {
    return src ? "loading" : "pending"
  })

  // Add this
  useEffect(() => {
    setStatus(src ? "loading" : "pending")
  }, [src])
```

**Desktop (please complete the following information):**

- OS: macOS 10.14.6
- Browser Chrome 83
- Version `1.0.0-next.3`

**Additional context** Add any other context about the problem here, or some
background information of how you ran into this bug.

**Comment by segunadebayo** [comment]
Good catch @ima-s.

Thanks for the suggestion as well. I've added it and it worked!

**Comment by segunadebayo** [comment]
A new pre-release will be published soon.
