### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by lishine** [chakra-ui/chakra-ui#1081]
How do  I tell ```<Icon name='...' />``` to display icon from theme with a preset width and height ?
I receive this svg from figma:
```
<svg width="31" height="34" viewBox="0 0 31 34" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="..." fill="black"/>
</svg>

```
And I want it to be displayed in same size.
But in order to put it in theme I strip svg and add viewBox.

```
    icons: {
        ...defaultTheme.icons,
        head: {
            path: (
                <path
                     ....
                />
            ),
            viewBox: '0 0 31 34',
        },
    },
```

Doing this for example ```<Icon size='32px' />``` will make it square, but I want it to be exactly like in figma...

**Comment by segunadebayo** [comment]
@lishine, you can set only the width of the `svg` to `31px`.

The aspect ratio will be preserved and the height would be `34px` due to the viewBox property.

**Comment by lishine** [comment]
Following your suggestion, I have tried to set  for the above theme ```<Icon name='head' width='32px' />```
It sets the icon too small...
And anyway what I would like is just show the icon as is, but I cannot svg width parameter in the theme.

So I currently I work as usual: use ```<Box as={Head} />```
and a create component
```
export const Head = () => {
    return (
        <svg width='31' height='34' viewBox='0 0 31 34' fill='none' xmlns='http://www.w3.org/2000/svg'>
            <path
                d='...'
                fill='black'
            />
        </svg>
    )
}
```

But then what is the point of theme icons...

**Comment by jiri-matejka** [comment]
@segunadebayo Unfortunately the aspect ratio is not preserved for the svg <Icon> when I specify either `width` or `height`. The other dimension keeps at 16px.
(We use probably version 1.10: `@chakra-ui/system": "1.10.3"`)
