### ISSUE TITLE
[chakra-cli] `npx chakra-cli init --theme` should place the chakra folder inside src folder 

### ISSUE THREAD

**Issue by ilyes-kechidi** [chakra-ui/chakra-ui#1094]
### Current Behavior:
running `npx chakra-cli init --theme` places the chakra folder in the project's root folder  
### Expected Behavior:
it should look for the src folder ( which is the most common) and place the chakra folder there

**Comment by segunadebayo** [comment]
Hi @ilyes-kechidi,

Please move this issue to https://github.com/chakra-ui/chakra-cli

It'll help us stay organized. Also, the CLI has the `--out` option to specify the directory it should clone the theme to.
