### ISSUE TITLE
[Alert] Alert requires __css prop in v1.0.0-next.4

### ISSUE THREAD

**Issue by ima-s** [chakra-ui/chakra-ui#1095]
**Describe the bug** 
Alert throws following type error if `__css` prop is not passed. Is this intentional? I guess something wrong with `Alert` type definition.
```
Property '__css' is missing in type '{ children: (string | Element)[]; status: "error"; }' but required in type 'Pick<AlertProps, "children" | "p" | "slot" | "style" | "title" | "transition" | "_hover" | "_active" | "_focus" | "_highlighted" | "_focusWithin" | "_focusVisible" | ... 487 more ... | "status">'.
```

**Expected Behavior**

**Link to minimal reproduction** 

https://codesandbox.io/s/cool-fire-t3yet?fontsize=14&hidenavigation=1&theme=dark

**Steps to Reproduce** 
Simple `Alert` component as follow throws type error.

`<Alert status="error">`

**Suggested solution(s)**

**Desktop (please complete the following information):**

OS: macOS 10.14.6
Browser Chrome 83
Version 1.0.0-next.4

**Additional context** Add any other context about the problem here, or some
background information of how you ran into this bug.

**Comment by segunadebayo** [comment]
Thanks for reporting this @ima-s.

We've fixed it and we'll publish an update soon.
