### ISSUE TITLE
[ChakraProvider] Better theme prop required error message

### ISSUE THREAD

**Issue by navin-moorthy** [chakra-ui/chakra-ui#1096]
**What problem does this feature solve?** 

A better error message to show on the CLI when Chakra Provider doesn't have the `theme` prop passed.

Current errom message,
![image](https://user-images.githubusercontent.com/39694575/86313160-125a6980-bc42-11ea-94a1-24ddffe68b95.png)

**What does the proposed API look like?** 

Error message on how Styled-Components handle it,
![image](https://user-images.githubusercontent.com/39694575/86313193-2aca8400-bc42-11ea-8a68-8e7f993359c9.png)

**Additional context** 

[CodeSandBox - Example](https://codesandbox.io/s/chakra-ui-issue-1096-oistw)

**Comment by segunadebayo** [comment]
Thanks for this @navin-moorthy. I've added a better error message.
