### ISSUE TITLE
[Slider] Cannot reach minimum with step

### ISSUE THREAD

**Issue by cereallarceny** [chakra-ui/chakra-ui#1099]
**Describe the bug** When I set the `min` value to `0` and the `step` to `5` or `10` I cannot ever reach `0`.

**Expected Behavior** I should be able to hit the minimum amount. The slider does not go all the way to the left

**Link to minimal reproduction** https://codesandbox.io/s/xenodochial-mclean-3ldu9?fontsize=14&hidenavigation=1&theme=dark

**Steps to Reproduce**

1. Add a `<Slider />` component with the proper children
2. Set a minimum and a step
3. Try to reach the minimum

**Suggested solution(s)** No idea

**Desktop (please complete the following information):**

- OS: Mac OSX 10.15.5
- Browser: Chrome 83

**Comment by segunadebayo** [comment]
Thanks for catching this. I've fixed it
