### ISSUE TITLE
Accessibility of 'editable' component

### ISSUE THREAD

**Issue by missmatsuko** [chakra-ui/chakra-ui#11]
[Editable](https://chakra-ui.netlify.com/?path=/story/editable--default)

- Using with keyboard navigation, the text becomes editable when tabbing to it and saved when tabbing away from it. This is very different experience from a mouse user who would have to explicitly make the text editable and has a chance to cancel or save after changing the text.
- Using keyboard to navigate, it seems like focus gets trapped in the text field. When I try to tab past other components in Storybook, I'm able to get past the component and into the bottom area (e.g. knobs, actions). However on this page, tabbing keeps switching the text between editable and not editable.
- Design-wise, I'm not sure if it's clear enough that the text has become editable since it looks like non-editable text rather than text in a form field, for example.

**Comment by segunadebayo** [comment]
Thanks for this detailed feedback and observation @missmatsuko. I've resolved this and will release a patch soon.
