### ISSUE TITLE
useToast() function terminated

### ISSUE THREAD

**Issue by Aneureka** [chakra-ui/chakra-ui#110]
The function terminated when I add the line `const toast = useToast();`, as showed in this image:

![8FAA166C-F342-4CE6-B92E-EE9061A13F08.png](https://i.loli.net/2019/09/21/N1fzxE4UHvqe39P.jpg)

When using `useToast()`, it exits and the next line is not run.

**Comment by Aneureka** [comment]
It seems to happen because I break the rules of react hooks. How can I use `useToast` in non-hook environments? I'm not ready to use react hooks right now...

**Comment by segunadebayo** [comment]
Yes, it seems you can't use hooks in Class components: https://reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both

I found this article that shows how to use hooks in Class components via render prop: https://infinum.co/the-capsized-eight/how-to-use-react-hooks-in-class-components.

**Comment by Aneureka** [comment]
> Yes, it seems you can't use hooks in Class components: https://reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both
> 
> I found this article that shows how to use hooks in Class components via render prop: https://infinum.co/the-capsized-eight/how-to-use-react-hooks-in-class-components.

Thanks a lot. That's the key point. I will also try to learn React Hooks.
