### ISSUE TITLE
[Icon] Size prop is totally unused against theme

### ISSUE THREAD

**Issue by cereallarceny** [chakra-ui/chakra-ui#1101]
**Describe the bug** The `size` prop on the `<Icon />` component is totally ignored.

**Expected Behavior** I'd expect it to work. I looked at `boxSize` as a prop, which works fine for pixel values, but does not work for the pre-defined theme sizes: `xs`, `sm`, `md`, `lg`, or `xl`.

**Link to minimal reproduction** Phttps://codesandbox.io/s/loving-wilson-xm39s?fontsize=14&hidenavigation=1&theme=dark

**Steps to Reproduce**

1. Create an `<Icon />` and give it an `as` prop of some external icon
2. Add a `size` with a value of `xs`, `sm`, `md`, `lg`, or `xl`

**Suggested solution(s)** No clue, I've got my theme set up from the @chakra-ui/theme repo, sizes are totally ignored.

**Desktop (please complete the following information):**

- OS: Mac OSX 10.15.5
- Browser: Chrome 83

**Comment by segunadebayo** [comment]
Hi @cereallarceny,

This is because the `Icon` component theme was omitted in "next.3", remember you added it recently to the theme?

I'll create a new pre-release and you can test it again.

Now that the icon theming API is in the theme, it should work.

**Comment by cereallarceny** [comment]
Ahh understood. I'll wait for the next pre-release. Is this going to be in `next-5`?

**Comment by segunadebayo** [comment]
Yes. It'll be `next.5`
