### ISSUE TITLE
[Select -> option] Styling on option under select is not working

### ISSUE THREAD

**Issue by nikhilpatil-git** [chakra-ui/chakra-ui#1104]
Hello @segunadebayo 

When we create a <Select/> component the <option> under select has a default blue background, is there any way to change this background from blue to something else, i can see similar issues raised before but didn't found any documentation to fix this issue.

<img width="740" alt="Screenshot 2020-07-02 at 17 15 12" src="https://user-images.githubusercontent.com/1549630/86385109-a864b300-bc87-11ea-801a-b4bd807153d3.png">

**Comment by segunadebayo** [comment]
Hi @nikhilpatil-git,

If you're referring to the Select component, you can use the `focusBorderColor` to change the outline or focus ring around the select.

```jsx
<Select focusBorderColor="gray.500" />
```

For the option, sadly there's no way to style the options in the native select element. This is a known issue in HTML.

In the future, we might have a custom select component that allows you to do this.

Cheers.
