### ISSUE TITLE
[MenuButton] MenuButton doesn't identify rightIcon property when set as={Button}

### ISSUE THREAD

**Issue by nikhilpatil-git** [chakra-ui/chakra-ui#1107]
Hello @segunadebayo 

Using Typescript when we define MenuButton as={Button} compiler complains that it didn't identify rightIcon property, reason is because If you check source code, MenuButtonProps doesn't have ButtonProps 

**** Source Code *****
export type MenuButtonProps = PseudoBoxProps & IMenuButton;
export const MenuButton: React.FC<MenuButtonProps>;
*************************

i'm working around this by adding ButtonProps to MenuButtonProps but it need to be added in the code to avoid warning.

This is my code :-
<MenuButton
        as={Button}
        rightIcon="chevron-down"
        w="200px"
        justifyContent="space-between"
   />

**Comment by with-heart** [comment]
Hi @nikhilpatil-git, could you create a reproduction in CodeSandbox? That'll make it easier for us to investigate!

**Comment by dmitru** [comment]
Here's a Sandbox, hope you'll find it useful:
https://codesandbox.io/s/confident-kirch-mkte5?file=/src/App.js:0-1498>

- MenuButton on its own, without `as={Button}` does not render the icon
- MenuButton with `as={Button}` renders the icon correctly (but won't support variant prop, see #1120

**Comment by segunadebayo** [comment]
I've just fixed this.

It'll be published shortly. Thanks guys
