### ISSUE TITLE
[Menu] V1 Rendering Performance Regression

### ISSUE THREAD

**Issue by dmitru** [chakra-ui/chakra-ui#1118]
**Describe the bug**

Rendering performance of Menu component (and possibly some others) got a lot worse (~8-10 times) after migrating a codebase to V1.0.

Description of a JSX layout rendered:
- 20 Boxes each having a Menu with 6 MenuItems

**Expected Behavior** 

Rendering of such a layout should be reasonably fast.

**Link to minimal reproduction** 

### V1.0 (huge lag when rendering):
~~https://codesandbox.io/s/staging-tree-fywty?file=/src/App.js~~
Updated Sandbox: https://codesandbox.io/s/inspiring-nightingale-wmmjs?file=/src/App.js

### Pre-V1.0, rendering is instant:
https://codesandbox.io/s/condescending-hugle-40nim?file=/src/App.js

**Steps to Reproduce** 

Open Sandbox, click on "Toggle" button to hide and then un-hide the thumbnails. Notice a significant lag while rendering the layout.

**Desktop (please complete the following information):**

- OS: OS X most recent
- Browser: Chrome
- Version: most recent

**Additional info**

React profiler screenshots - before V1.0:

![image](https://user-images.githubusercontent.com/948486/86486971-b9f29d00-bd11-11ea-98fb-ad54a856e3ed.png)

React profiler screenshots - after V1.0 migration:

![image](https://user-images.githubusercontent.com/948486/86486979-bc54f700-bd11-11ea-8f9a-51c5dae17260.png)

**Comment by carlreid** [comment]
I am not sure if it is related or not, but I also saw pretty bad frame rate drops too while I scroll. But for me, I think I traced it back to Popper which I believe is used for `Menu`.  
  
You can actually just see the frame rate drops if you use https://next.chakra-ui.com/docs/components/menu and compare it to say for example https://next.chakra-ui.com/docs/components/modal. Simply scrolling causes the frame rate drops, no other interactions at all.

Menu example:
![image](https://user-images.githubusercontent.com/33623601/86489141-aa03a900-bd63-11ea-9e6c-9af9ffdf61ce.png)  
  
Modal example:
![image](https://user-images.githubusercontent.com/33623601/86489154-bab41f00-bd63-11ea-9ba2-bf07b17fb56e.png)

In my own project, I have the following. Which, if I comment out the use of `Menu` then I get a constant FPS.
![image](https://user-images.githubusercontent.com/33623601/86489322-4f1e8180-bd64-11ea-951f-1d97942af7d4.png)

**Comment by remorses** [comment]
We could add some tests for render times using a combination of [react-testing-library](https://github.com/testing-library/react-testing-library) and react [profiler api](https://reactjs.org/docs/profiler.html)

**Comment by ljosberinn** [comment]
The `<Popover />` component seems to have the same behaviour: rendering although not visible through the [hidden](https://github.com/chakra-ui/chakra-ui/blob/master/packages/popover/src/use-popover.ts#L176) attribute (just like `<Menu />` does [here](https://github.com/chakra-ui/chakra-ui/blob/master/packages/menu/src/use-menu.ts#L395)).

**Comment by segunadebayo** [comment]
Thanks for reporting this @dmitru. I spotted a couple of performance issues related to the styling API which is related to this and I've fixed this.

We can set up the Profiler API to measure the performance metrics and further improve the code. If it's related to popper, we need to confirm for sure.

As regards the rendering, we updated the "popover" components to render and stay hidden in the DOM to better collect the `refs` and `index` of each item in the tree, to improve keyboard navigation and handle nested menu scenarios.

In v0, we use `querySelector` to get these `refs` but we ran into some issues with nested menus and popovers hence the change.

We need to look into this some more but I believe the changes I've made will help a bit.

**Comment by dmitru** [comment]
@segunadebayo Tried it by running a local repo clone (but not sure if I set it up correctly, there were some theming issues). I did not notice performance improvements – rendering a dozen of Menus still blocked the main thread for ~600ms. I'll give it another try as soon as the fixes are published (btw, I'd appreciate docs on how to install a Chakra clone locally in an existing project that used chakra from npm registry!)

In my experience, the current approach to always rendering content for popovers and menus won't work performance-wise in some cases (I encounter them very often for the types of apps I'm building - think interactive graphical editors with sliders, color pickers and such). 

For example, in the app I'm building, there are some rendering-heavy components rendered inside Popovers, which are connected to a store (I'm using Mobx), and are re-rendered every time values change there... But I really only expect one Popover to be visible at any time (and then the performance is fine). Rendering all of their content just won't fly for me.

**As a suggestion**, perhaps we could have a `isLazy` prop or similar, for both Menus and Popovers, to defer rendering of content until these components open?

**Comment by dmitru** [comment]
@segunadebayo **Update** The profiler shows a shallower render tree, and also confirms that performance did improve slightly (but below the perception threshold).
 
So far the improvemens for my case are (22ms to ~19ms) for one rendered Menu. 

Imagine how much better it'd be if Menu skipped rendering its children - it'd be down to 3ms! And the gains would be much more evident for longer / more complex content.

![image](https://user-images.githubusercontent.com/948486/86930969-6e166e00-c0ec-11ea-8227-8fe2fa2d2b91.png)

**Comment by dmitru** [comment]
Comparison with a few other a11y-first libraries:

**Performance is ranked from best to worst.**
1. Chakra with skipped rendering of MenuItem's: https://codesandbox.io/s/blissful-mayer-g8vmu?file=/src/App.js
2. Reach: https://codesandbox.io/s/stoic-diffie-8zi65-reach-84b95?file=/src/App.js
3. Chakra without skipped rendering (default behavior): https://codesandbox.io/s/inspiring-nightingale-wmmjs?file=/src/App.js
4. Reakit is the slowest: https://codesandbox.io/s/stoic-diffie-8zi65-reakit-8zi65

It confirms that skipping rendering of MenuItems is the biggest possible performance gain.

**Comment by with-heart** [comment]
@dmitru This is such thorough investigation! Thanks so much for the time and effort you're putting into this.

**Comment by segunadebayo** [comment]
Thanks to @dmitru, we've implemented a solution for this.

Cheers guys

**Comment by jackhkmatthews** [comment]
Hi @segunadebayo, 

I'm seem to be experiencing similar Menu performance issues with chakra-ui/core v1.0.0-rc.3. 

Could you confirm which which version has the solution implemented? And where in the code base the fix exists?

Thanks 👍

**Comment by ljosberinn** [comment]
@jackhkmatthews could you please provide a codesandbox? You may simply add the `isLazy` prop to the `Menu` component to not render the `MenuList` contents until opened. Also you may upgrade to `rc.5`. For this kind of question, I'd recommend joining [our Discord](https://discord.gg/8nzYM2) as they can be easily resolved there.

[code](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/menu/src/use-menu.ts#L291)

**Comment by jackhkmatthews** [comment]
@ljosberinn thanks for the quick response and code link!

I'll be sure to join the discord and post there or here with any further questions
