### ISSUE TITLE
[MenuButton] Doesn't properly support "variant" prop when used with as={Button}

### ISSUE THREAD

**Issue by dmitru** [chakra-ui/chakra-ui#1120]
**Describe the bug** 

MenuButton when used with `as={Button}` prop is not rendered properly when passed different `variant` prop.

https://codesandbox.io/s/confident-kirch-mkte5?file=/src/App.js:0-1498>

**Comment by segunadebayo** [comment]
Hi @dmitru.

I've just fixed this and it'll be published soon.

Thanks for catching it
