### ISSUE TITLE
[Input] A better x-padding

### ISSUE THREAD

**Issue by Grafikart** [chakra-ui/chakra-ui#1123]
I think the default padding for inputs is a bit incoherent since we don't have the same space vertically and horizontally

![input4](https://user-images.githubusercontent.com/395137/86495293-15a44100-bd79-11ea-90c9-6f37e654328a.PNG)

Defaulting the value to "2" should provide a better spacing.

![Capture](https://user-images.githubusercontent.com/395137/86495375-687df880-bd79-11ea-979b-90077c71946b.PNG)

I could do a PR but I wanted a feedback before doing so. Feel free to close this issue if you don't agree with this change.

**Comment by segunadebayo** [comment]
Hi @Grafikart.

I see what you mean. From my design background, I think it looks balanced when the x-padding is slightly more than the visual y-padding.

We also don't want to introduce any extra breaking changes, so I'll close this for now.

Thank you for taking the time to share your thoughts on this.
