### ISSUE TITLE
[Popover][V1] Popover reopen on click

### ISSUE THREAD

**Issue by hosmelq** [chakra-ui/chakra-ui#1124]
**Describe the bug** 

Popover reopen on click.

**Expected Behavior** 

Close popover on click.

**Link to minimal reproduction** 

[codesandbox](https://codesandbox.io/s/dry-star-q0dx1?file=/src/App.js)

**Steps to Reproduce**

1. Click on icon.
2. Click on icon again.

**Additional context** 

If you click the edges of the button works well.

**Comment by segunadebayo** [comment]
Hi @hosmelq,

Thanks for reporting this. I've fixed it and we'll release an update shortly.

Cheers
