### ISSUE TITLE
[Menu] Extra padding when included as child of <Stack>

### ISSUE THREAD

**Issue by feross** [chakra-ui/chakra-ui#1130]
**Describe the bug** A clear and concise description of what the bug is.

The `<Menu>` component renders two children, one for the menu button, and another for the menu itself. This means that when `<Menu>` is a child of `<Stack>`, the menu will be offset incorrectly.

<img width="301" alt="Screen Shot 2020-07-04 at 5 21 55 PM" src="https://user-images.githubusercontent.com/121766/86523008-f5c55980-be1a-11ea-8c54-b86b7d7d6b4e.png">

Should `<Menu>` render a `<Box>` around the children? Like this:

<img width="294" alt="Screen Shot 2020-07-04 at 5 22 28 PM" src="https://user-images.githubusercontent.com/121766/86523009-feb62b00-be1a-11ea-9e44-1b0acc838d84.png">

This is the fixed code (notice how I manually wrap the `<Menu>` in a `<Box>`):

```
    <Stack
      direction='row'
      align='center'
      width='full'
      {...rest}
    >
      <Box>
        <Menu>
          <MenuButton size='sm'><MdMoreHorizIcon boxSize={5} /></MenuButton>
          <MenuList>
            <ReportButton as={MenuItem} game={game}>
              <MdReportProblemIcon mr={2} />
              Report
            </ReportButton>
          </MenuList>
        </Menu>
      </Box>
  </Stack>
```

**Expected Behavior** A clear and concise description of what you expected to
happen.

The following code, without a `<Box>` manually added around the `<Menu>` should render without extra padding on the menu.

```
    <Stack
      direction='row'
      align='center'
      width='full'
      {...rest}
    >
        <Menu>
          <MenuButton size='sm'><MdMoreHorizIcon boxSize={5} /></MenuButton>
          <MenuList>
            <ReportButton as={MenuItem} game={game}>
              <MdReportProblemIcon mr={2} />
              Report
            </ReportButton>
          </MenuList>
        </Menu>
  </Stack>
```

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] Latest

**Additional context** Add any other context about the problem here, or some
background information of how you ran into this bug.

1.0.0-next.4

**Comment by segunadebayo** [comment]
Hey @feross.

Thanks for reporting this. I'm curious, what's your intention of using `Stack` to wrap the `Menu` component?

I'm assuming that you want to give some space between the `MenuButton` and `MenuList`, right? If that's the case you can pass `gutter` prop to `Menu` and set it's value to the space you want between them (30, 24, etc). 

Let me know your thoughts before adding more comments.

**Comment by riverfr0zen** [comment]
I found this issue while trying to figure out how to reduce/eliminate the space between the button and the list. However, applying the gutter prop to `Menu` (also tried to apply to `MenuButton`, `MenuList`, &  `MenuItem`) does not seem to do anything. 

If you try it on the editable example in the `Menu` documentation, it doesn't do anything either. The `Menu` documentation does not mention gutter, whereas I do see it mentioned for the `Popover` component.

I'm using version 0.8.0 of @chakra-ui/core.

**Comment by segunadebayo** [comment]
@riverfr0zen This issue is referring to `v1` pre-release.

For v0.x, I'd suggest you pass popper.js `modifier` prop directly to `MenuList` component to control the `gutter`.

Cheers.

**Comment by feross** [comment]
> @segunadebayo I'm assuming that you want to give some space between the MenuButton and MenuList, right? If that's the case you can pass gutter prop to Menu and set it's value to the space you want between them (30, 24, etc).

The intention of using a `<Stack>` was to have other buttons horizontally alongside the button that triggers the menu, not to get spacing between `MenuButton` and `MenuList`. For example:

<img width="318" alt="Screen Shot 2020-07-16 at 8 41 02 PM" src="https://user-images.githubusercontent.com/121766/87746624-df69b700-c7a5-11ea-86fc-3015c5efa198.png">

So the '...' button and the 'Extend by 2 minutes' button are in the `<Stack>`. Does that make sense?

**Comment by with-heart** [comment]
Here's a reproduction: https://codesandbox.io/s/boring-shape-mhgib?file=/src/App.tsx
