### ISSUE TITLE
[Icon] Fallback icon has the same color for bg and fg

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1131]
@segunadebayo @with-heart Yesterday, I forgot to mention this, current fallback icon is full black without color: "white" for the icon circle.
![image](https://user-images.githubusercontent.com/39694575/86504379-3ac69d00-bdd5-11ea-90db-ad8a1a196a02.png)

![image](https://user-images.githubusercontent.com/39694575/86504399-5fbb1000-bdd5-11ea-8a10-a5aabc68e6de.png)

Can we change below line,
`<circle fill="currentColor" cx="12" cy="12" r="10" />`
to this?
`<circle fill="white" cx="12" cy="12" r="10" />`

Works well in both `light` and `dark` mode.

_Originally posted by @navin-moorthy in https://github.com/chakra-ui/chakra-ui/pull/1115#issuecomment-653715848_

**Comment by segunadebayo** [comment]
Thanks for catching this @with-heart and @navin-moorthy.

I've fixed this.
