### ISSUE TITLE
Embedding a Gatsby Link in MenuItem produces useMenuContext error

### ISSUE THREAD

**Issue by Dave-Lindberg** [chakra-ui/chakra-ui#1133]
**Describe the bug**  Given the component MenuItemContent which contains a [Gatsby Link](https://www.gatsbyjs.org/docs/gatsby-link/):

`const MenuItemContent = ({ menuItem, wordPressUrl }) => {`
` return (`
`  <Link to={CreateLocalLink(menuItem, wordPressUrl)}>`
`    {menuItem.label}`
`  </Link>`
`)}`
`...`

and mapping over it within a MenuItem component like so:

`...`
`  return (`
`    <div style={{ marginBottom: "20px" }}>`
`      {`
`        menuItems &&`
`        menuItems.map((menuItem) => (`
`          <MenuItem >`
`            <MenuItemContent key={menuItem.id} menuItem={menuItem} wordPressUrl={wordPressUrl}/>`
`          </MenuItem>`
`        ))`
`      }`
`    </div>`
`  )`
` ...`

**Expected Behavior**  Should produce something like: 

`<Menu >`
`  <MenuItem>`
`    <Link>Some Text</Link>`
`  </MenuItem>`
`  <MenuItem>`
`    <Link>Some Text</Link>`
`  </MenuItem>`
`...`
`</Menu>`

**Instead, the result is** "Error: useMenuContext must be used within a MenuContext Provider"

Source: 
`Error: useMenuContext must be used within a MenuContext Provider
18 stack frames were collapsed.
(anonymous function)
/Users/dlindberg/Code/dl-gatsby-wpgql/.cache/app.js:67
  64 | const preferDefault = m => (m && m.default) || m
  65 | let Root = preferDefault(require('./root'))
  66 | domReady(() => {
 67 |   renderer(<Root />, rootElement, () => {
  68 |     apiRunner('onInitialClientRender')
  69 |   })
  70 | })`

Compiled: 
`(anonymous function)
http://localhost:8000/commons.js:1125:7
  1122 | 
  1123 | var Root = preferDefault(__webpack_require__(/*! ./root */ "./.cache/root.js"));
  1124 | _mikaelkristiansson_domready__WEBPACK_IMPORTED_MODULE_7___default()(function () {
  1125 |   renderer( /*#__PURE__*/react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement(Root, {
       |   ^  1126 |     __self: _this,
  1127 |     __source: {
  1128 |       fileName: _jsxFileName,`

Tested in Chrome Version 83.0.4103.116 and Firefox Developer 79.0b3 on Mac OS v10.15.5

**Comment by with-heart** [comment]
Are you actually wrapping everything with `Menu`? I don't see that in your code sample.

Is there any way you could reproduce this in a CodeSandbox? It's hard to tell what the actual issue is without being able to see the code.

**Comment by segunadebayo** [comment]
Hi @Dave-Lindberg. I think this is happening because you forgot to wrap this code within the `Menu` component.

```jsx
// wrap in menu component
<Menu>
{
       menuItems &&
        menuItems.map((menuItem) => (
         <MenuItem >
           <MenuItemContent key={menuItem.id} menuItem={menuItem} wordPressUrl={wordPressUrl}/>
          </MenuItem>
        ))
      }
<Menu/>
```

Let me know if this helped. Otherwise, please create a Codesandbox issue for this and we'll re-open it.

**Comment by Dave-Lindberg** [comment]
Yes, that does it. Thanks for the help! :-)
