### ISSUE TITLE
[Toast] Component sits under Modal overlay

### ISSUE THREAD

**Issue by struct78** [chakra-ui/chakra-ui#1134]
When I try to show a toast error when a modal is open, the toast sits underneath the overlay, and I can't figure out how to change the stacking context so it's on top. I am using 1.0.0-next.4

Code sandbox:
https://codesandbox.io/s/festive-wright-tvs80?file=/src/ToastModal.js

**Comment by segunadebayo** [comment]
Thanks for reporting this @struct78.

We've fixed this by reverting to use `z-index`. Ideally, we'll like to eliminate the use of `zIndex` and manage the stacking context properly.

We'll look into that post v1.
