### ISSUE TITLE
Multi select

### ISSUE THREAD

**Issue by dipto0321** [chakra-ui/chakra-ui#1138]
Hi,
I am trying to build multi-select things with chakra-ui but I didn't get any way to do it with chakra-ui. I am trying to wrap react-select with chakra-ui but also not getting any guidelines to do that. Can someone have any idea how can I do that? or any tips? 
Thanks :pray:

**Comment by segunadebayo** [comment]
Hi @dipto0321,

I'd recommend using a combination of `downshift` and Chakra UI to achieve this result. Downshift handles the `select` logic and `chakra` handles the styling part.

I haven't checked but I'm sure a package exists out there to handle multi-select in `downshift`. The downshift community is great so I believe they'll be able to help as well.

Hope this helps.

Cheers.

**Comment by csandman** [comment]
I made a chakra wrapper for react-select if anyone is looking for something like this!  https://github.com/csandman/chakra-react-select
