### ISSUE TITLE
Request to add transition animation to Popover

### ISSUE THREAD

**Issue by dmitru** [chakra-ui/chakra-ui#1144]
**What problem does this feature solve?** 
Menu transition animation is a really nice addition in V1.0! 
It'd be very useful to have the same capability for Popovers too – it'd create a more consistent experience when using animated Menus and Popovers together in the same UI.

**What does the proposed API look like?** 
Same as MenuTransition, but PopoverTransition?

**Comment by segunadebayo** [comment]
This was released in the `next.6` and we also provided a way to customize these transitions as well.

We'll make sure to document them so it's easy for you.

Thanks

**Comment by sebqq** [comment]
Hello @segunadebayo, Is there any change that we could get some quick example here before it is documented? Thanks!

**Comment by la55u** [comment]
Hey @segunadebayo  could you please point me in the right direction on how to add a transition to Popover? I couldn't find it in the docs. thanks

**Comment by red-name** [comment]
Any progress on this?
