### ISSUE TITLE
Store color mode value in theme

### ISSUE THREAD

**Issue by remorses** [chakra-ui/chakra-ui#1147]
Currently we store the color mode value in a react context

This approach has a few problems that limit the extensibility with other packages
- when other packages use another color mode context the state is duplicated in multiple places
- if other UI packages want to know the current color mode they must have a peer dependency on `@chakra-ui/color-mode`
- if there are multiple installs of `chakra-ui` the color mode context is duplicated and color mode will stop working

We could instead use the emotion `ThemeContext` to store the color mode value, this way `chakra-ui` color mode can easily be used by other UI packages without having to depend on `chakra-ui`

Obviously there would be no change on the current API as we can just change the `useColorMode` and `useColorModeValue` functions to get the value from theme instead of context

**Comment by remorses** [comment]
I can open a pull request if @with-heart and @segunadebayo agree

**Comment by with-heart** [comment]
I'm all for reducing friction in integrating with third parties, and this would definitely be a sensible change in that direction! I'm wondering if there was a concern that drove us to use a separate context to begin with though, I'm not sure what led to that.

**Comment by arnaudjnn** [comment]
Is it possible to use color mode like in ```theme-ui```:

```
colors: {
    ...chakraTheme.colors,
    accent1: '#FAFAFA',
    accent2: '#EAEAEA',
    accent3: '#999',
    accent4: '#888',
    modes: {
      dark: {
        accent1: '#111',
        accent2: '#333',
        accent3: '#999',
        accent4: '#FAFAFA',
      },
    },
  },

**Comment by with-heart** [comment]
Hey @arnaudjnn, I made #1162 to track that request since it's not directly related to this.

**Comment by with-heart** [comment]
@remorses Go for it!

**Comment by segunadebayo** [comment]
I see where this is going @remorses. I think it makes sense to store the value in the theme and allow the user to provide their mechanism to control the color mode, we can use localStorage by default.

**Comment by segunadebayo** [comment]
In v1, we managed to create a `colorModeManager` prop which allows the user to gain control over the color mode, rather than adding it to the theme. However, we do allow the user to provide an `initialColorMode` config in the theme as a fallback.

I think this solution would suffice for now.

We'll re-consider this in the future.
