### ISSUE TITLE
Add [ExpandingTextarea] component

### ISSUE THREAD

**Issue by jestrux** [chakra-ui/chakra-ui#115]
Hi @jestrux ,

I agree. Please feel free to add the `resize` prop to the Textarea docs.

I'd appreciate if you add the ExpandingTextarea component as well. Here's what you need to do:

- Create a new folder named `ExpandingTextarea`
- Add `index.js`, `index.d.ts`, and `examples.js`
- Add the component code in `index.js`
- Add type definitions in `index.d.ts`
- Add some storybook examples in `examples.js`
- Update the `src/index.js` and `src/index.d.ts` to include the `ExpandingTextarea`.
- Update the docs for Textarea

I'll include this in the contribution guidelines shortly.

Thanks.

_Originally posted by @segunadebayo in https://github.com/chakra-ui/chakra-ui/issues/93#issuecomment-532595125_

**Comment by jestrux** [comment]
Hi @segunadebayo,

Based on that guideline you provided, I'm comfirming that you meant the information about ExpandingTextArea should be included in the Textarea page and not a standalone page for ExpandingTextarea.

**Comment by segunadebayo** [comment]
I was thinking it should be a standalone page.

**Comment by jestrux** [comment]
Okay, nice.

**Comment by segunadebayo** [comment]
Thanks for this issue. I'll add it in the next release.

**Comment by jestrux** [comment]
Can I instead create a PR for this that you can then review?
