### ISSUE TITLE
[Textarea] Not respecting the rows prop

### ISSUE THREAD

**Issue by hardvain** [chakra-ui/chakra-ui#1157]
Textarea not respecting the rows prop

``` javascript
<Textarea placeholder="Here is a sample placeholder"  rows={20}/>
```
Expect the text area to have the height of 20 rows

**Desktop (please complete the following information):**

- OS: Mac OS Catalina
- Browser: Chrome
- Version: 83.0.4

**Comment by with-heart** [comment]
Reproduction: https://codesandbox.io/s/determined-hopper-bmxwm?file=/src/App.tsx

A workaround to make one with many rows is to set `height` to `null` (not valid, but `undefined` doesn't unset) and to make with few rows is to do the same and set `minH` to `0`.

**Comment by hardvain** [comment]
@with-heart Thanks. The workaround is working fine.

**Comment by with-heart** [comment]
Not sure if we want to consider this a problem or not. I'll leave it open for now and let @segunadebayo have a say :)

**Comment by segunadebayo** [comment]
Thanks for reporting this @hardvain. I've fixed it in the code as well.
