### ISSUE TITLE
Document new styling functionality

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1161]
This was added recently to enable styling of composite components.

- [x] `register` usage and its benefits
- [x] `useStyleConfig`
- [x] `StylesProvider`
- [x] `useStyles`
- [x] styling a composite component using the above tooling

**Comment by tony** [comment]
@with-heart Where in the codebase / api can `useStyleConfig` be found? (re: https://github.com/chakra-ui/chakra-ui/issues/1139#issuecomment-655337839) My GitHub search isn't showing anything

Is it on NPM yet?

**Comment by with-heart** [comment]
It's not out quite yet. It'll be in `1.0.0-next.5`.

https://github.com/chakra-ui/chakra-ui/blob/develop/packages/alert/src/alert.tsx + https://github.com/chakra-ui/chakra-ui/blob/develop/packages/theme/src/components/alert.ts are a pretty good example of it.

**Comment by with-heart** [comment]
https://github.com/chakra-ui/chakra-ui/blob/develop/packages/accordion/src/accordion.tsx shows how it works with composite components.

**Comment by tony** [comment]
Thank you @with-heart !

**Comment by segunadebayo** [comment]
Working on this!

**Comment by segunadebayo** [comment]
Done!

**Comment by tony** [comment]
@segunadebayo Do the themes generated by https://github.com/chakra-ui/chakra-cli still work?

e.g. The `menu.ts` file generated I have tries to import `copy` from `@chakra-ui/theme-tools` but its not there

**Comment by segunadebayo** [comment]
@tony. Right now, the CLI is out of sync with the `@chakra-ui/theme` package.

I'm thinking of moving the CLI to the main repo to establish sync, for now, I'd advise using the `@chakra-ui/theme` directly.
