### ISSUE TITLE
Set color mode colors via `theme.colors.modes`

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1162]
Is it possible to use color mode like in ```theme-ui```:

```
colors: {
    ...chakraTheme.colors,
    accent1: '#FAFAFA',
    accent2: '#EAEAEA',
    accent3: '#999',
    accent4: '#888',
    modes: {
      dark: {
        accent1: '#111',
        accent2: '#333',
        accent3: '#999',
        accent4: '#FAFAFA',
      },
    },
  },

_Originally posted by @arnaudjnn in https://github.com/chakra-ui/chakra-ui/issues/1147#issuecomment-656531188_

**Comment by segunadebayo** [comment]
I see where this is going but Chakra might not go this route. I don't have a clear idea yet but I'm convinced there's a better approach to solve this problem.

Please send this message to @arnaudjnn.

Thank you.

**Comment by arnaudjnn** [comment]
So we have to use a condition each time we use color?

```<Text bg="accent2"/>``` is better than ```<Text bg={colorMode === "dark" ? "green.300" : "green.500"} />```

**Comment by with-heart** [comment]
@arnaudjnn The intention is that you'd handle color mode at the component theming level rather than at the use-site: https://next.chakra-ui.com/docs/theming/advanced#using-color-mode

**Comment by arnaudjnn** [comment]
@with-heart Ok so what would be the best practice for globals colors like body bg, fonts?

**Comment by zzh8829** [comment]
There are rarely any components that work out of box without special color modification since the font and background color literally switch to the opposite color.

Component level color also makes custom styling very difficult.
Take the default button for example https://github.com/chakra-ui/chakra-ui/blob/master/packages/theme/src/components/button.ts
Right now the options are either drop default button completely or find out exactly how to replace `{color}.50,100,200,300,500,600,700,800` in dark and light mode, it's pretty much an impossible task for users.

**Comment by with-heart** [comment]
Going to re-open to make sure we address your concerns/questions

**Comment by segunadebayo** [comment]
Hey guys,

I'm going to resolve this one more time @with-heart.

@arnaudjnn The best practice is to define global styles in `theme.styles.global`. Here's a simple guide for that.
https://github.com/chakra-ui/chakra-ui/blob/develop/website/docs/global-styles.mdx

@zzh8829 The goal is not to create 50-900 colors. The goal is to encourage users to customize the theme and even change component level styles directly from the theme.

If you think you don't that many values, change the button theme all together to match your needs.

```jsx
import theme from "@chakra-ui/theme"

theme.components.Button = {
    // custom button theme goes here.
}

<ChakraProvider theme={theme}>
   // App
</ChakraProvider>
```

I understand this might seem inconvenient for now and we're doing our best to make this as seamless as possible. In the meantime, this is the API we're looking to support.

Hope this helps.

Thanks guys.

**Comment by jesstelford** [comment]
As a workaround for this kind of thing, I've created a Provider which sets the right colours directly onto the theme object by making a new `.mode` property available based on your theme config having a `.modes.<light|dark>` key:

```
// dynamic-color-mode.js
import React from 'react';
import { useTheme, useColorMode, ThemeProvider } from '@chakra-ui/core';

export const DynamicColorMode = (props) => {
  const { colorMode } = useColorMode();
  const theme = useTheme();

  return (
    <ThemeProvider
      {...props}
      theme={{
        // Chakra does a deep-merge of the theme objects
        colors: {
          mode: {
            // Retain access to all the default colours specified
            ...theme.colors,
            // Overwrite with mode-specific colors
            ...theme.colors.modes?.[colorMode],
          },
        },
      }}
    />
  );
};
```

Then use it like so:

```
import defaultTheme from '@chakra-ui/theme';
import { ChakraProvider, InitializeColorMode, Box } from '@chakra-ui/core';
import { DynamicColorMode } from './dynamic-color-mode';

const theme = {
  ...defaultTheme,
  colors: {
    ...defaultTheme.colors,
    border: '#888',
    modes: {
      dark: {
        bg: '#333'
      },
      light: {
        bg: '#ddd'
      }
    }
  },
}

export default function App() {
  return (
    <ChakraProvider theme={theme}>
      <InitializeColorMode />
      <DynamicColorMode>
        <Box bg="mode.bg" border="1px solid" borderColor="mode.border" />
      </DynamicColorMode>
    </ChakraProvider>
  );
}
```

**Comment by vanniewelt** [comment]
I solved this problem by simply creating multiple themes and switching them in the `ChakraProvider`. The benefit of this approach is that you are not limited only to colors – for example, I adjusted font weights a little bit, since they seem to look a little bit thinner on a light background.

```tsx
type Mode = "light" | "dark"

function createTheme(mode: Mode) {
  return extendTheme({
    colors: colorModes[mode],
    fonts,
    fontWeights: fontWeightModes[mode],
    components,
  })
}

const themes = {
  light: createTheme("light"),
  dark: createTheme("dark"),
}

export default function App({ Component, pageProps }: AppProps) {
  const [mode, setMode] = useState<ColorMode>("dark")

  const toggleMode = () => setMode(mode === "light" ? "dark" : "light")

  return (
    <ChakraProvider theme={themes[mode]}>
      <Button onClick={toggleMode}>Toggle mode</Button>
      <Component {...pageProps} />
    </ChakraProvider>
  )
}
```

**Comment by keeeeith** [comment]
You can add a color as a root variable and use the `mode` function.
```
const colors = {
  brand: "var(--brand)",
  green: baseTheme.colors.green,
}
const overrides = {
  config,
  styles: {
    global: props => ({
      ":root": {
        "--brand": mode(colors.green["300"], colors.green["800"])(props),
      },
      html: {
        minHeight: "100%",
      },
      body: {
        overflow: "auto",
      },
      "html, body, #root": {
        display: "flex",
        flex: 1,
      },
    }),
  },
  colors,
}

export const theme = extendTheme(overrides)
```

The example above can be used as `<Flex backgroundColor="brand">` or `theme.colors.brand`
```
