### ISSUE TITLE
[Guides] Add spacing between title+description and guide body

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1164]
Guides pages render their title and description at the top, with no clear division between them and the body of the post. It feels like there should be a better indicator that the heading is a reflection of metadata.

Here's an example from a guide I was working on:

![image](https://user-images.githubusercontent.com/1954752/87214768-94f7be80-c2fd-11ea-9b74-237ddade5fad.png)

![image](https://user-images.githubusercontent.com/1954752/87214776-a4770780-c2fd-11ea-8d42-f388b2c830e5.png)

**Comment by segunadebayo** [comment]
Done!
