### ISSUE TITLE
[Switch] `sm` and `md` labels are the same height

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1166]
An example comes from the `Switch` docs page:

![image](https://user-images.githubusercontent.com/1954752/87216657-bd88b400-c30f-11ea-9393-8b37a7f850a0.png)

These are center-aligned, but visually it doesn't look like it because the surrounding `label` elements for `sm` and `md` are the same height.

**Comment by segunadebayo** [comment]
Fixed!
