### ISSUE TITLE
404 on Chakra-UI About Page

### ISSUE THREAD

**Issue by MikePreston17** [chakra-ui/chakra-ui#1169]
I found a 404 on Chakra-UI About Page.  Might be an issue of a bad NextJS Link (I see you're on Vercel) in the components I show below:

![About-page-not-found](https://user-images.githubusercontent.com/9275026/87218578-d5653580-c319-11ea-936c-1bf8850909c1.gif)

Expected:  Clicking on the _About_ breadcrumb would take me to Chakra-Ui About page, if it has one.

(You may ignore the flashes; it's likely my GIF recorder)

Reproduction:
1. Navigate to chakra-ui.com/breadcrumb
2. Search for 'About' using ctrl+F in your browser
3. Click on the first sample breadcrump with the 'About' text.
4. Observe a custom 404 page.

- OS: Manjaro KDE Plasma
- Browser: chrome
- Version: latest

**Comment by segunadebayo** [comment]
Hi @MikePreston17,

Thanks for reporting this. It was just an example in the docs, @with-heart can you help update this?
