### ISSUE TITLE
Label curation and issue triage

### ISSUE THREAD

**Issue by Ronva** [chakra-ui/chakra-ui#117]
@segunadebayo It might be good to let someone (or a couple people) handle managing issue labels and triaging them to make it easier to scan through. It could even be a one-time job where we backfill the labels and require people to label as they go. Thoughts?

**Comment by segunadebayo** [comment]
Hi @Ronva,

It's a good idea to add some labeling so it's easier to scan through and resolve issues. 

Please feel free to jump on this. I'll appreciate it.

**Comment by Ronva** [comment]
@segunadebayo I would love to but I currently don't have permission to add/edit labels.

**Comment by Ronva** [comment]
Closing this as it's getting stale and is not too relevant to the library itself. @segunadebayo let me know if/when you'd like to proceed with this at your earliest convenience 😁

**Comment by segunadebayo** [comment]
@Ronva, sure I'll proceed with this soon. My apologies for the late response
