### ISSUE TITLE
Figure out how to "link" monorepo output for local development

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1178]
`yarn` and `npm` both come with a `link` command that allows you to easily symlink another local package into your current project in order to test that package. 

With a monorepo, neither of these commands work because there isn't a single build artifact for them to target. In Chakra's case, `yarn build` produces a `dist` folder inside every folder in `packages`. Even if you want to link a single Chakra package, it won't work, because each Chakra package depends on other Chakra packages. 

[`yalc`](https://github.com/whitecolor/yalc) is a tool that can reportedly help with this, but so far we haven't found any success with it.

**Comment by segunadebayo** [comment]
I did some research on this today and it's really challenging to set this up. It involves using `yalc` with custom nodejs script.

I don't think it's worth the work for now. We can use the `examples/` folder in the meantime.
