### ISSUE TITLE
`as={Flex}` not forwarding `align`/`justify` shorthands

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1181]
When using `as={Flex}`, the `align` and `justify` props are swallowed so you have to use `justifyContent` and `alignItems` instead. Most likely related to the `shouldForwardProp` function in `@emotion/styled`.

See #1167 for more information.

**Comment by segunadebayo** [comment]
Having merged your PR for removing `isPropValid` and resolved DOM warnings, this should work now.

Cheers.
