### ISSUE TITLE
[Toast] Toast placed in top right has no margin

### ISSUE THREAD

**Issue by bradenrayhorn** [chakra-ui/chakra-ui#1183]
**Describe the bug**

Running Chakra v1.0.0-next.4, toasts placed in the top right have no right margin and are touching the right edge of the window.

**Expected Behavior**

There should be space between the toast and the right edge of the window.

**Link to minimal reproduction**

CodeSandbox (Chakra 1.0.0-next.4): https://codesandbox.io/s/great-worker-rpzvh?file=/src/button.js
CodeSandbox (Chakra 0.7.0): https://codesandbox.io/s/admiring-night-y2ih4?file=/src/button.js

**Steps to Reproduce**

1. Open CodeSandbox
2. Click "Show Toast" button
3. Observe the toast lost its right margin in the upgrade to Chakra v1

**Suggested solution(s)**

I'd like to check to make sure this is not intentional before looking at a solution.

**Desktop (please complete the following information):**

- OS: macOS
- Browser Any browser

**Comment by with-heart** [comment]
Not entirely sure what the right fix is here. The only way I'm able to get the margin to display correctly is to remove the `100%` width from the `Alert` inside `Toast`, but that affects the display of all toasts, so it doesn't seem like the right approach.

**Comment by bradenrayhorn** [comment]
Would it work to add some spacing inside of the `ToastManager`? Right now the `top`, `left`, `right`, `bottom` properties are all 0. I think adding some space there might work. I'm not super familiar with the codebase so this might cause some issue I'm not aware of.
