### ISSUE TITLE
[Tabs] Improve `orientation` prop support

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1187]
The `Tabs` component technically supports the `orientation` prop (values of `vertical` or `horizontal`), but the effect it has is to switch between `keyDown` handlers for `ArrowUp`+`ArrowDown` or `ArrowLeft`+`ArrowRight` and to alter the `aria-orientation` prop. The default `theme` provides no visual support for the `vertical` orientation, and the `orientation` prop is entirely undocumented.

- [ ] Add `theme` support for `vertical` tabs
- [ ] Document the `orientation` prop

**Comment by dodas** [comment]
Example:
```ts
// Before:
tablist: {
  borderBottom: "2px solid",
  borderColor: "inherit",
},

// After:
tablist: {
  [props.orientation === "vertical" ? "borderRight" : "borderBottom"]: "2px solid",
  borderColor: "inherit",
},
```
This, and similar orientation-aware definitions would repeat few times across the file, so my question is whether
it is readable enough or you guys want to do some type of abstraction/refactoring here?

**Comment by with-heart** [comment]
imo some abstraction would good, perhaps similar to how `Button` defines its variants. That way it's very clear what the styles are for horizontal vs. vertical.

**Comment by neighborhood999** [comment]
Interesting, I think if can receive `props` might be let component flexible, e.g:

```jsx
<Button circle>Button</Button>
```

```js
{
  // ...some props
  borderRadius: props.circle ? '50%' : 'md'
}
```

**Comment by rockchalkwushock** [comment]
@dodas @with-heart 

Spoke with @segunadebayo this morning and am starting work on this tonight

**Comment by segunadebayo** [comment]
@dodas can you create a fresh PR for this based on your solution?

If you can help update the docs as well, that would be great.

**Comment by beforan** [comment]
Some related comments from my usage today in `1.0.0-rc.8`:

With `orientation="vertical", the `TabList` is made vertical, but the `TabList` and the `TabPanels` are still vertically stacked.

I would expect them to be horizontal, with a vertical `TabList` to one side or the other of the `TabPanels`.

I'm currently achieving this as follows:

```
<Tabs orientation="vertical"
  display="grid" gridTemplateColumns="auto 1fr">
```

I don't know if it's desirable for `orientation="vertical"` to cause this layout change, or otherwise for the docs to cover how to get whichever layout effect you want.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by HGCollier** [comment]
It would seem that the `orientation` prop is also not responsive. Is there any planned support for this?

**Comment by ABNERMATHEUS** [comment]
<Tabs orientation={"vertical"} isLazy align='start' variant='enclosed'>

**Comment by HGCollier** [comment]
For anyone wondering, I was able to get the orientation to be responsive, using the `useBreakpointValue` hook.

```const orientation = useBreakpointValue(
  { 
    base: 'horizontal', 
    md: 'vertical', 
  }, 
  { 
    fallback: 'md', 
  }, 
)```
