### ISSUE TITLE
Allow customizing sizes via theme for all the elements.

### ISSUE THREAD

**Issue by nisarhassan12** [chakra-ui/chakra-ui#1190]
Hi!

I use rems to size most of the things in my projects via using the following technique described [here](https://snook.ca/archives/html_and_css/font-size-with-rem) which makes sizing things with rems super easy.

![image](https://user-images.githubusercontent.com/46004116/87245975-6d226b00-c463-11ea-8788-24f6a014a66d.png)

This is how the fontSize objects looks in the theme:

```js
fontSizes: {
    xs: '1.4rem',
    sm: '1.6rem',
    md: '1.8rem',
    lg: '2.5rem',
    xl: '3rem',
    '2xl': '3.5rem',
    '3xl': '4.5rem',
    '4xl': '5.5rem',
    '5xl': '6.5rem',
    '6xl': '8rem',
},
```
Now the buttons and a few other elements(like form elements) have started to look weird that's because of the padding values have became too small:

![image](https://user-images.githubusercontent.com/46004116/87246050-02256400-c464-11ea-83db-bee18af48dcf.png)
![image](https://user-images.githubusercontent.com/46004116/87246104-6e07cc80-c464-11ea-91fe-0efeac148106.png)

using the above technique for sizing things Chakra should not break how buttons and other elements look. 

A solution would be to have all of the values-driven from the default built-in theme and then allowing customizing them in the theme if required as in my case. Thanks

**Comment by with-heart** [comment]
Hi @nisarhassan12, the padding values of `Button` are driven by the theme and you're able to customize them!

https://github.com/chakra-ui/chakra-ui/blob/df27471456e107eec082afb439f36d570413e749/packages/chakra-ui/src/Button/styles.js#L157-L182

As you can see above, the `size` prop determines the `px` value to use. 

https://github.com/chakra-ui/chakra-ui/blob/v0/packages/chakra-ui/src/theme/sizes.js#L1-L5

**Comment by with-heart** [comment]
Hi @nisarhassan12, the padding values of `Button` are driven by the theme and you're able to customize them!

https://github.com/chakra-ui/chakra-ui/blob/df27471456e107eec082afb439f36d570413e749/packages/chakra-ui/src/Button/styles.js#L157-L182

As you can see above, the `size` prop determines the `px` value to use. This prop corresponds with the `size` scale from the theme:

https://github.com/chakra-ui/chakra-ui/blob/df27471456e107eec082afb439f36d570413e749/packages/chakra-ui/src/theme/sizes.js#L1-L21

If you want to use `62.5%` as the base `font-size`, you'd have to scale `theme.sizes` as well.

**Comment by with-heart** [comment]
Personally, I'd highly recommend against sizing based on `62.5%`. That was an old trick to allow developers and designers used to thinking in pixels to continue thinking in pixels, but we live in a new world now :) You'll get little benefit from it, especially in the context of Chakra UI.

**Comment by with-heart** [comment]
Going to close this, but feel free to follow up if you still have questions/concerns!
