### ISSUE TITLE
Equalize `nextjs` js and ts examples

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1191]
The `nextjs-typescript` example is a more complex example than its js counterpart but doesn't use any Chakra components, and the two also have much different content. The examples should be equalized so that you get the same basic example regardless of whether you're using js or ts.

**Comment by Geeman201** [comment]
I'm happy to work on this one 👍 What kind of content do you want on both of them?

**Comment by with-heart** [comment]
I have this PR open for creating basic `create-react-app` templates, and they have basic content inspired by the default `create-react-app` content, along with a color mode switcher: https://github.com/chakra-ui/chakra-ui/pull/936

imo it should be something similar to that, especially with the color mode switcher. Simple enough for users to understand how the package is set up and configured and how to use color mode in their components, without becoming too complex.

I'm open to ideas though!

Also feel free to join us on Discord if you'd like :) https://discord.gg/hUGpfa8

**Comment by Geeman201** [comment]
Cool - I think keeping them aligned is a "good enough" thing for v1 of this 👍 ?

**Comment by with-heart** [comment]
Agreed!
