### ISSUE TITLE
Document `GlobalStyle` + `theme.styles.global`

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1193]
`GlobalStyle` is a new component in v1 that injects styles from `theme.styles.global` into the global styles of the page. This allows users to define styles that affect elements outside of the Chakra system while still using values from their Chakra theme.

The `GlobalStyle` component and `theme.styles.global` are mentioned in only two places in the documentation: the migration guide and the `gatsby-plugin-chakra-ui` `README`. This is not sufficient documentation.

- [x] Document `GlobalStyle` and `theme.styles.global`
- [x] Add note that `ChakraProvider` automatically renders `GlobalStyle`, so you don't need to render it separately if you're using `ChakraProvider`
- [x] Create an example of `GlobalStyle` and `theme.styles.global` being used together to style non-Chakra elements

**Comment by balibebas** [comment]
Example theme to help with the docs: https://git.habd.as/comfusion/gatsby-starter-i18n-react-i18next/src/branch/master/src/utils/theme.tsx

**Comment by segunadebayo** [comment]
Done!

**Comment by with-heart** [comment]
Nice!
