### ISSUE TITLE
No _hover for <Box />  

### ISSUE THREAD

**Issue by nisarhassan12** [chakra-ui/chakra-ui#1196]
Hi!

I'm trying to add hover effect to the `<Box />` component which is used as a `<Link/>` component but it does not seem to be working.

```jsx

<Box
       as={Link}
       cursor="pointer"
       margin="0 10px"
       to={link.route}
       transition="all .2s"
       _hover={{
              bg: colors.orangeDark,
        }}
>
        {link.label}
</Box>
```
`_hover` seems to work perfectly for `<Button/>` component.

```jsx
<Button
  bg={colors.orange}
  _hover={{
    bg: colors.orangeDark,
  }}
>
  {buttonText}
</Button>
```

Thanks.

**Comment by with-heart** [comment]
Minimal reproduction: https://codesandbox.io/s/nice-hooks-ghktz?file=/src/index.js

**Comment by santialbo** [comment]
Before 1.0 you had to use `PseudoBox` instead of `Box`. @with-heart's reproduction works when using `PseudoBox`

**Comment by nisarhassan12** [comment]
Thanks @santialbo

**Comment by with-heart** [comment]
@santialbo Good catch! Wasn't even paying attention 🙃

**Comment by nisarhassan12** [comment]
@with-heart Many Thanks  now `_hover` does seem to be working but I'm unable to style `&::after` in `_hover` this is how my code looks: 

```jsx
<PseudoBox
  as={Link}
  cursor="pointer"
  margin="0 10px"
  to={link.route}
  position="relative"
  transition="all .2s"
  _after={{
    content: '',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: '100%',
    display: 'block',
    height: '1px',
    background: 'white',
    transition: 'all 0.4s cubic-bezier(0, 0.5, 0, 1)',
  }}
  _hover={{
    color: colors.orangeDark,
    '&:after': {
      right: 0,
      background: colors.orangeDark,
    },
  }}
>
  {link.label}
</PseudoBox>
```

Sorry. I'm using Chakra UI for the first time i.e it's my first project with it. Thanks.

**Comment by santialbo** [comment]
try with `content: '""'`

**Comment by nisarhassan12** [comment]
Many Thanks @santialbo It worked perfectly.
