### ISSUE TITLE
Create Gatsby Recipe

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1198]
> Gatsby Recipes is a framework for automating common Gatsby tasks. Recipes are MDX
files which, when run by our interpretor, perform common actions like installing
NPM packages, installing plugins, creating pages, etc.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-recipes/README.md

**Comment by jmiazga** [comment]
The PR above was merged. @with-heart up to you if you want to axe this while on your cleaning spree.

**Comment by with-heart** [comment]
@jmiazga Thank you!
