### ISSUE TITLE
Integrate with Capsize

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1199]
[`capsize`](https://seek-oss.github.io/capsize/) is a library from [seek-oss](https://github.com/seek-oss) built for flipping the way we define typography in CSS to be more like how designers think about typography. Here's a great talk from @michaeltaranto about the differences: https://www.youtube.com/watch?v=TGHbkTGVqoU

We'd like to integrate Chakra with Capsize so that we can provide this functionality out of the box.

Spawned from a Twitter discussion: https://twitter.com/markdalgleish/status/1282575411885404160

**Comment by jesstelford** [comment]
Love this!

I just integrated Capsize's output into a new Chakra V1 site.

I ran Capsize 40 times; 10 font sizes (`xs` to `6xl`) x 4 leading sizes (`none`, `tight`, `base`, `loose`), which gave me a very large object that I popped into the theme.

I then created a new `<Text />` component which accepts a `size` & `leading` prop.

Here's the result:

![87109262-88487b80-c2a7-11ea-9a79-7390222637c7](https://user-images.githubusercontent.com/612020/87306628-a1795280-c55b-11ea-812f-62a36caa6a18.gif)

**Comment by joernroeder** [comment]
@jesstelford i'd love to play around with this as well. can you give me a hint how you started? from my experience sometimes line-heights differ between sizes to always match the baseline grid, so i wonder how size dependent line heights can be implemented in a seamless way

**Comment by michaeltaranto** [comment]
@joernroeder the npm package should be published this week. That should hopefully make it easier to experiment with.

**Comment by with-heart** [comment]
@jesstelford That's beautiful! Is the code for that new site publicly available by any chance?

@michaeltaranto Looking forward to playing around with that :)

**Comment by michaeltaranto** [comment]
Launched `capsize@v1` this week to npm. Might make it easier to play around with.

**Comment by Vynlar** [comment]
I worked on a custom implementation of the "text crop" feature a few months ago (see #512). I was developing against the typescript rewrite branch which was changing a lot at the time. I decided to pause and wait for things to calm down a bit (which it seems they have). Additionally the wonderful @michaeltaranto gave us `capsize` which should help a ton!

I do have some API-related questions for folks to give their two-cents about:

- Should we integrate this into it's own component (`CroppedText`, or the like); or directly into the `Text`/`Header` components?
- Could we get away with a hook that you then spread props into the base `Text`/`Header` components?
- How should we store the `fontMetrics`? (In the theme? In userland? In a separate context?)

**Comment by segunadebayo** [comment]
From the look of this, I think it should be a recipe rather than a default feature in Chakra. There are some edge cases that make this difficult to implement especially the responsive aspects.

I took the first pass at it here: https://codesandbox.io/s/nervous-curran-prmit?file=/src/index.tsx. I'm sure there are some things I'm not doing right in that example but I'm happy to get ideas/feedback @michaeltaranto.

There's quite some complexity involved to get this right and I don't think we're at the point where we can support this.

If you can publish your own implementation @Vynlar under your npm namespace so other users of Chakra can test, that would be awesome. I'd like some more extensive testing on this idea before considering adding it to Chakra.

Thanks for understanding.

**Comment by segunadebayo** [comment]
@jesstelford could you share a recipe for this? I'd love to share it with the Chakra community.

That'll close this issue and get us to a reasonable point with the Capsize integration

**Comment by michaeltaranto** [comment]
Overhauling capsize repo at the moment to make better use of its monorepo setup. That should allow for recomposition in a few different ways and support some different use cases.

There was a proposal for responsive array support in issues, and @jesstelford had a capsized chakra example somewhere too.

**Comment by jesstelford** [comment]
@segunadebayo Here's the script (https://gist.github.com/jesstelford/2850962727b94c4e093e18dd68204321), but it's using an old version of `capsize`.

It would be better to use `capsize`'s new `createStyleObject()` method to generate the objects.

**Comment by jesstelford** [comment]
Even better, now that [`@capsizecss/metrics` & `@capsizecss/unpack` are released](https://github.com/seek-oss/capsize/pull/48), it will make integrating much easier 👍

**Comment by anubra266** [comment]
cc @segunadebayo

**Comment by jesstelford** [comment]
@anubra266 Other than the couple of (now stale) workarounds above, I don't believe this has been implemented yet? Can we keep this ticket open until it's something that's possible?

Or is this officially "Not a feature Chakra will support"?

**Comment by anubra266** [comment]
@jesstelford according to [this](https://github.com/chakra-ui/chakra-ui/issues/1199#issuecomment-895100868) it's not on chakra's roadmap. 
@segunadebayo do we still have any plans for this?

**Comment by segunadebayo** [comment]
We don't be integrating this anymore. It feels like something our users should opt-in for by adding the generated styles to the global styles via `<Global/>` component.

If anyone is willing to write a proper guide for this. I'd love to add it to the docs.

Thanks for understanding.

**Comment by jesstelford** [comment]
Ok, I've created a component to integrate chakra + capsize.

**Introducing: [`chakra-capsize`](https://github.com/ceteio/chakra-capsize)**

It handles all the complexities around responsive props, the interplay of fontMetrics and theme scales, and even supports Chakra's default lines heights for headers 🎉

```
yarn add @ceteio/chakra-capsize
```

```javascript
import { withCappedText } from '@ceteio/chakra-capsize/theme'
import { CappedText, CappedHeading } from '@ceteio/chakra-capsize'
import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import robotoFontMetrics from '@capsizecss/metrics/roboto';

const theme = extendTheme(
  {
    fonts: {
      heading: 'Roboto',
      body: 'Roboto',
    },
  },
  withCappedText({
    fontMetrics: { Roboto: robotoFontMetrics }
  })
);

const App = () => {
  return (
    <ChakraProvider theme={theme}>
      <div>
        <CappedHeading as="h1" size="2xl">Hi!</CappedHeading>
        <CappedText>
          This paragraph will have surrounding whitespace
          trimmed. It will also have space between the lines
          of text reduced to 0.
        </CappedText>
        <CappedText capHeight="lg" lineGap={4}>
          Setting a capHeight overrides any fontSize prop for
          more exact sizing.  Meanwhile, a lineGap uses the
          Chakra 'spacings' scale to insert space between
          lines of text just like any other Chakra element.
        </CappedText>
      </div>
    </ChakraProvider>
  );
}
```

**Comment by jesstelford** [comment]
@segunadebayo is this something you'd be willing to add to the docs? If so, where would be the best place for it to live? In the `Text` component docs? Or maybe as a "Guide", under the "Integrations" heading?

**Comment by with-heart** [comment]
> @segunadebayo is this something you'd be willing to add to the docs? If so, where would be the best place for it to live? In the `Text` component docs? Or maybe as a "Guide", under the "Integrations" heading?

cc @lazarnikolov94

**Comment by lazarnikolov94** [comment]
> > @segunadebayo is this something you'd be willing to add to the docs? If so, where would be the best place for it to live? In the `Text` component docs? Or maybe as a "Guide", under the "Integrations" heading?
> 
> cc @lazarnikolov94

@with-heart definitely as a guide. I'll create an Issue to track this. Thanks for the mention!
