### ISSUE TITLE
Form fields shouldn't have placeholders

### ISSUE THREAD

**Issue by missmatsuko** [chakra-ui/chakra-ui#12]
[form control](https://chakra-ui.netlify.com/?path=/story/formcontrol--default)
[input](https://chakra-ui.netlify.com/?path=/story/input--default)

There's a lot of reasons why we shouldn't use placeholder text in form fields:
https://www.smashingmagazine.com/2018/06/placeholder-attribute/

**Comment by segunadebayo** [comment]
Thank you for this feedback @missmatsuko . The `placeholder` prop is optional and you can use a visible label as well. The goal is Chakra is to be as flexible and extensible as possible to support most use cases.

Thanks again.

**Comment by makkarMeenu** [comment]
How will we add style to placeholders in textarea and other input types in chakra ui?
I cannot see any option.
Please help

**Comment by cyberwombat** [comment]
@makkarMeenu you can use the [pseudo](https://chakra-ui.com/docs/features/style-props#pseudo) notation:
```
<Input
 _placeholder={{
   ...
}}
/>
```
