### ISSUE TITLE
[Guides] Add author avatar + GitHub profile link

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1205]
We store the `author` of each guide in its `frontmatter`, but we don't do anything with that information. Each guide should provide clear attribution by displaying the user's avatar and a link to their GitHub profile.

**Comment by segunadebayo** [comment]
I removed this for now so we can focus on the guide's content itself.

We have support for it already in the `next.config.js` already though. we only need to evaluate if it's really needed.
