### ISSUE TITLE
[Tooltip]: children are required to be wrapped in span tags. shouldWrapChildren does not work.

### ISSUE THREAD

**Issue by aaronmcadam** [chakra-ui/chakra-ui#121]
As of **v0.3.1**:

Here's the codesandbox: https://codesandbox.io/s/blissful-greider-eywse

It shows the bug with a `Tooltip` on its own and used inline with other content (my use case).

It also shows that `shouldWrapChildren` doesn't work.

It's also broken on the docs site: https://chakra-ui.com/tooltip#usage

**Comment by aaronmcadam** [comment]
It looks like the docs use the wrong prop to show an arrow: https://chakra-ui.com/tooltip#tooltip-with-focusable-content. The example uses `showArrow` instead of `hasArrow`.

**Comment by segunadebayo** [comment]
Hi @aaronmcadam ,

I just looked into it and resolved the issue. Thanks for catching this.

I'll release a patch soon.

**Comment by aaronmcadam** [comment]
Thanks!

**Comment by segunadebayo** [comment]
Kindly upgrade to the v0.3.2. I've resolved this issue there.

**Comment by aaronmcadam** [comment]
Thanks for this!
