### ISSUE TITLE
[Modal] Property 'initialFocusRef' does not exist on type 'IntrinsicAttributes & { children?: ReactNode; }

### ISSUE THREAD

**Issue by koolamusic** [chakra-ui/chakra-ui#1215]
**Describe the bug** Following the examples from https://chakra-ui.com/modal the Code generates a type error in a React/Typescript project.

Error
```js
Type '{ children: Element[]; initialFocusRef: MutableRefObject<undefined>; finalFocusRef: MutableRefObject<undefined>; isOpen: boolean; onClose: () => void; }' is not assignable to type 'IntrinsicAttributes & { children?: ReactNode; }'.
  Property 'initialFocusRef' does not exist on type 'IntrinsicAttributes & { children?: ReactNode; }'
```

Even after adding a type, this is the error I get
```ts
Type 'MutableRefObject<undefined>' is not assignable to type 'RefObject<HTMLElement>'.
  Types of property 'current' are incompatible.
    Type 'undefined' is not assignable to type 'HTMLElement | null'.ts(2322)
```

**Link to minimal reproduction** 
I copied the code, following the instructions on *Focus on specific Element* in the documentation https://chakra-ui.com/modal

**Steps to Reproduce** Follow the instructions on *Focus on specific Element* in the documentation https://chakra-ui.com/modal

1. Go to 'https://chakra-ui.com/modal'
2. Copy the Modal Example on 'https://chakra-ui.com/modal#focus-on-specific-element'
3. The `initialFocusRef` generates a type error

**Comment by with-heart** [comment]
I need to explore a bit more but this is likely still a valid issue in 1.0. `useRef()` uses `undefined` as its initial value if one isn't provided while we're expecting `T | null`. 

imo we should probably accept `undefined`, but for now this can be resolved using `useRef(null)`.

**Comment by koolamusic** [comment]
Yeah @with-heart I was able to resolve this with `useRef<HTMLElement>(null)` Thanks

**Comment by segunadebayo** [comment]
Glad you found a walkaround @koolamusic.

Thank you @with-heart. We use `RefObject` as the type of `initialFocusRef` so v1 also supports this use-case. Ideally, it should be `null | HTMLElement`.
