### ISSUE TITLE
Drawer types not updated

### ISSUE THREAD

**Issue by pcvonz** [chakra-ui/chakra-ui#122]
I'm having trouble importing all the new Drawer components in TypeScript. [Looks like the index.d.ts](https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/Drawer/index.d.ts) file in the Draw component's folder wasn't updated.

**Comment by segunadebayo** [comment]
Yes, it was updated. I've added the types and will release a patch soon

**Comment by segunadebayo** [comment]
Kindly upgrade to the v0.3.2. I've resolved this issue there.
