### ISSUE TITLE
[Text] Option to respect line breaks?

### ISSUE THREAD

**Issue by paambaati** [chakra-ui/chakra-ui#1220]
**What problem does this feature solve?**
I want to use `<Text>` to display long-form text like addresses, which often times require line breaks. So for example, when my incoming string is `LINE 1\nLINE 2\nLINE 3`, I'd like an option or a flag (say, `breakOnNewLines`) on the `<Text>` component that would either `<br/>` tags or via [the `\a` CSS trick](https://css-tricks.com/injecting-line-break/#you-can-insert-line-breaks-via-pseudo-element).

**What does the proposed API look like?**
```jsx
const address = `Door number 420,
High street,
Redeye County`;

<Text breakOnNewLines>{address}</Text>
```
This will output —

```html
<p>Door number 420,
<br/>High street,
<br/>Redeye County
</p>
```

**Describe alternatives you've considered**
1. Construct multiple `<Text>` elements for each new line by splitting the variable by new lines into arrays and joining them with `<Text>` via interpolation in JSX. But this is cumbersome to do in every place I expect to do this, and doing it in the component as a prop is much more elegant. 
2. Perhaps use the [`dangerouslySetInnerHTML`](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) API? But as the name suggests, it is a) dangerous and b) I'm not even sure if it works with Chakra components.

**Comment by segunadebayo** [comment]
Hi @paambaati,

Thanks for sharing your thoughts. This is not an API we're looking to support at the moment. You could perhaps use `dangerouslySetInnerHTML`, Chakra components are also regular React elements so it would work just fine.

You can also consider creating your own custom component to handle this use-case so you don't keep repeating yourself.

Cheers.
