### ISSUE TITLE
[V1: Drawer] Not working with suspense for the first time

### ISSUE THREAD

**Issue by theterra** [chakra-ui/chakra-ui#1221]
The Drawer component is not animating for the first time toggle when wrapped in suspense.

```
  <Drawer open={open} onClose={() => setOpen(false)} size="lg">
        <React.Suspense fallback={null}>
          <SidePanelForm />
        </React.Suspense>
      </Drawer>
```

Issue reproduce - https://codesandbox.io/s/serene-darwin-wstw6?file=/src/App.js

**Comment by segunadebayo** [comment]
Hi @theterra,

What's the aim of wrapping Drawer in Suspense? I believe the content within the drawer should be the suspended part not the drawer itself but I'm curious to know your thoughts.

**Comment by theterra** [comment]
I was trying multiple ways. Suspense is in the within the drawer only.
Now I observed that If I keep suspense in Drawercontent, then sliding transition is working

```
<DrawerContent>
            <React.Suspense fallback={null}>
              <SidePanelForm />
            </React.Suspense>
          </DrawerContent>
```

**Comment by segunadebayo** [comment]
Glad you found a working solution.
