### ISSUE TITLE
[Documentation] Broken link to default theme

### ISSUE THREAD

**Issue by Dave-Lindberg** [chakra-ui/chakra-ui#1222]
In the documentation [Theme page](https://chakra-ui.com/theme) in the section #Colors, the link to [default theme](https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/theme) produces a 404 page.

Thanks! :-)

**Comment by with-heart** [comment]
Sorry for not getting back to you sooner @Dave-Lindberg! Focused pretty heavily on shipping v1 with the time we have available to us.

You can find the existing theme for v0 here: https://github.com/chakra-ui/chakra-ui/blob/v0/packages/chakra-ui/src/theme/theme.js
