### ISSUE TITLE
[Theme] Sync theme.config types with ColorMode

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#1223]
**Describe the bug**
Right now, the theme.config property [is not typed](https://github.com/chakra-ui/chakra-ui/blob/master/packages/theme/src/index.ts#L8) which leads to `theme.config.initialColorMode` being `string`, which is incompatible when used against the `ColorMode` type.

![image](https://user-images.githubusercontent.com/29307652/87477091-d4891800-c627-11ea-8b1e-2b1ed49fe9b0.png)

**Suggested solution(s)**

Simply adding and exporting a ThemeConfig definition should solve this:

```ts
import { ColorMode } from '@chakra-ui/core';

export interface ChakraConfig {
  initialColorMode: ColorMode;
  useSystemColorMode: boolean;
}

const config: ChakraConfig = {
  initialColorMode: 'dark',
  useSystemColorMode: false,
};
```

**Comment by jmiazga** [comment]
In `use-color-mode-state.ts` there is:

```
interface Options {
  initialColorMode?: ColorMode
  useSystemColorMode?: boolean
}
```

Should this just be exported and/or renamed so it's more explicit?

**Comment by segunadebayo** [comment]
@jmiazga, want to file in a PR for that? That would be great!

**Comment by jmiazga** [comment]
@segunadebayo Yep I can do that. Options is kind of generic, do you have a preference on a new name?

**Comment by jmiazga** [comment]
@segunadebayo We have 2 options for this:

1: Export it from `color-mode` then add it as a dependency in `theme`
2. Duplicate the interface directly in `theme`

**Comment by segunadebayo** [comment]
@jmiazga. How about this:

- Export it from `color-mode`
- Import it from `system` in the theme package. Color mode is already bundled in the system package.

**Comment by with-heart** [comment]
💢 why isn't linked issue closing working 💢
