### ISSUE TITLE
[Toast] Toast styles not being applied with latest beta

### ISSUE THREAD

**Issue by JClackett** [chakra-ui/chakra-ui#1229]
Using the latest betas

https://codesandbox.io/s/serverless-water-c8szr?file=/src/App.tsx

**Comment by segunadebayo** [comment]
This is due to lerna publishing a weird version of some packages. We'll look into this.

**Comment by dmitru** [comment]
I can confirm the bug; happens to Alert and Toast components.

**Comment by glenmcrae** [comment]
I can confirm this one too for both Alerts and Toast components.

**Comment by maxjustus** [comment]
Same is happening to me

**Comment by JClackett** [comment]
@segunadebayo will this be fixed soon in one of the beta patch releases?

**Comment by segunadebayo** [comment]
This has been fixed in `v1.0.0-rc.0`. Please check again.

Otherwise, I'll re-open this issue.

Cheers

**Comment by JClackett** [comment]
Its working except for when position is "bottom-right" there's now not any padding on the right side?

demo: https://codesandbox.io/s/elated-forest-ul53e?file=/src/App.tsx

**Comment by with-heart** [comment]
@JClackett Probably the same issue as #1183

**Comment by JClackett** [comment]
@with-heart yep that looks like it
