### ISSUE TITLE
Right to Left language support (Internationalization)

### ISSUE THREAD

**Issue by sumitngupta** [chakra-ui/chakra-ui#123]
Hello! 

Absolutely love the Design System.  I have one question I've struggled to get the answer for out of the docs, really sorry if I just missed it.. does Chakra support Right to Left languages out of the box?

 ❤️ ,
Sumit

**Comment by segunadebayo** [comment]
Hi @sumitngupta,

Thanks for your remark on Chakra UI. At the moment, Chakra components don't support Right to Left languages but we're getting there soon 😉.
