### ISSUE TITLE
[Menu] Missing "isOpen" property

### ISSUE THREAD

**Issue by dodas** [chakra-ui/chakra-ui#1233]
The docs for `<Menu>` component mention there is a `isOpen` property that can be passed to it, so it can be controlled from outside.

This property, however does not exist at all.

Docs: https://next.chakra-ui.com/docs/components/menu
Source: https://github.com/chakra-ui/chakra-ui/blob/master/packages/menu/src/use-menu.ts#L39

Version: @chakra-ui/core: 1.0.0-next.5

**Comment by segunadebayo** [comment]
I've just added support for this.

We'll publish an update shortly.
