### ISSUE TITLE
[v1 conversion] Spinner, useStyleConfig null exception 

### ISSUE THREAD

**Issue by vonwao** [chakra-ui/chakra-ui#1234]
**Describe the bug** 

app loads on my first screen, but on another screen crashes
app crashes on this line (after upgrade to V1.  0.x is working)
![image](https://user-images.githubusercontent.com/377000/87565126-3b8de780-c68f-11ea-8b99-b691ed16217d.png)

I believe `baseStyles` in code snippet has null value. 

Looks like it's coming from this other line of code in Spinner.tsx:
  const styles = useStyleConfig("Spinner", props)

Stack trace:
use-style-config.ts:33 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at use-style-config.ts:33
    at mountMemo (react-dom.development.js:15464)
    at Object.useMemo (react-dom.development.js:15760)
    at Object.useMemo (react.development.js:1521)
    at useStyleConfig (use-style-config.ts:30)
    at Spinner (spinner.tsx:71)
    at renderWithHooks (react-dom.development.js:14825)
    at updateForwardRef (react-dom.development.js:16840)
    at beginWork (react-dom.development.js:18678)

**Expected Behavior** 
should not crash.  Better fallback behavior for `baseStyles`
OR
better error message that tells me what went wrong

**Comment by vonwao** [comment]
Sorry for incomplete info above.  I finally discovered this error is ultimately coming from the Button component (removing isLoading prop fixes it)

react_devtools_backend.js:6 The above error occurred in the <Spinner> component:
    in Spinner (created by ButtonSpinner)
    in div (created by Context.Consumer)
    in Box (created by ButtonSpinner)
    in ButtonSpinner (created by Button)
    in button (created by Context.Consumer)
    in Styled(button) (created by Button)
    in Button (created by LoginBox)
    in form (created by LoginBox)
    in div (created by Context.Consumer)
    in Box (created by LoginBox)
    in LoginBox (created by App)

**Comment by segunadebayo** [comment]
I think your diagnosis of the problem was correct @vonwao. It's truly a null exception and I've just fixed it.

We'll publish a new release shortly.

**Comment by cezarneaga** [comment]
this happens also when using Spinner as a fallback for Suspense. i am using 1.0.0-next.6
