### ISSUE TITLE
[Popover] Performance: add isLazy prop similar to Menu to skip rendering of the content

### ISSUE THREAD

**Issue by dmitru** [chakra-ui/chakra-ui#1235]
**What problem does this feature solve?** 
Now that the Menu has the isLazy prop which greatly improves rendering performance, let's have the same prop for Popovers – in my experience, not rendering their content before user actually opens them may improve performance significantly in some cases.

**What does the proposed API look like?** 
```<Popover isLazy>```

**Describe alternatives you've considered** 
Support for a render prop, similar to Menu would also be appreciated (and very consistent with the Menu component API).

**Additional context** 
See #1118 for context

**Comment by segunadebayo** [comment]
Thanks for the reminder @dmitru.

I've just updated the popover to support this.

We'll publish an update shortly.

**Comment by tumdav** [comment]
any updates here?

**Comment by ljosberinn** [comment]
https://github.com/chakra-ui/chakra-ui/blob/develop/packages/popover/src/use-popover.ts#L106 it's supported @tumdav

**Comment by tumdav** [comment]
I have installed the version `^1.0.0-rc.5`, and my code looks like the following `   <Popover isLazy={true}>...`, but it still adds content in the document initially

![image](https://user-images.githubusercontent.com/10452309/96442592-6d799180-121c-11eb-8d10-6986963cbc1d.png)

what I am doing wrong ?

**Comment by tumdav** [comment]
As I understand by passing isLazy it generates containers only? isn't it ?

**Comment by ljosberinn** [comment]
yes, the containers are there but empty, that's intended

**Comment by tumdav** [comment]
great, thx for your quick reply
