### ISSUE TITLE
[v0.x Modal] Can't set max-width of ModalOverlay

### ISSUE THREAD

**Issue by vonwao** [chakra-ui/chakra-ui#1238]
**Describe the bug** 

![image](https://user-images.githubusercontent.com/377000/87589829-da2c3f80-c6b3-11ea-84ec-b3be51b5f999.png)

Since I can't set maxWidth the content overflows outside the Overlay

The max-width seems to be hardcoded to 28rem:

![image](https://user-images.githubusercontent.com/377000/87590156-5e7ec280-c6b4-11ea-8e46-ec522e07c9e8.png)

**Expected Behavior** 
There should be some way to set the maxWidth (or absolute width) of the ModalOverlay

**Comment by segunadebayo** [comment]
Hi @vonwao,

I'm confused here. are you referring to the ModalOverlay or ModalContent?

**Comment by segunadebayo** [comment]
FYI, you can pass `maxWidth` prop directly to the `ModalContent` to set a custom max-width. Same for the overlay as well.

Hope this helps.

**Comment by vonwao** [comment]
Thanks @segunadebayo 

I had to play with it for a few hours more until I figured out how to get the desired results.  I finally found that this is what I needed to get it working with a large width that I wanted:

```
<ModalOverlay maxWidth={950} width={950} />
        <ModalContent maxWidth={950} width={950}> 
        ...
```

Sharing this here in case it's helpful to anyone else who has a similar problem.
(Maybe this answer is clear for those who fully understand the CSS, but it's a mystery to me, like most CSS issues!)

**Comment by with-heart** [comment]
@vonwao `max-width` define the maximum width of the container. The container will grow to fit the width of its content, _up to_ the `max-width`. Since your content was less wide than the max, it wasn't stretching to match the max.

An easy trick that I use fairly often is to define a `max-width` and then set `width` to `100%`, so that the container is always the max.
