### ISSUE TITLE
Add example to Custom Icon with React Icons

### ISSUE THREAD

**Issue by emersonlaurentino** [chakra-ui/chakra-ui#124]
Add some examples of how customize icon with react-icons.

**Comment by Ronva** [comment]
Is this the kind of example you are referring to?
https://chakra-ui.com/getting-started#adding-icons

Sorry if I misunderstood the question.

**Comment by emersonlaurentino** [comment]
@Ronva No, I wanted an example section on how to use icons with the lib React Icons

**Comment by segunadebayo** [comment]
Hi @emersonlaurentino,

Here's how I do it currently:

```jsx
import {MdSettings} from "react-icons/md"

// Use the `as` prop to render the icons
<Box as={MdSettings} />

// Use the `as` prop to render the icons
<Box as={MdSettings} size="32px" color="green.400" />
```

Hope this helps.

**Comment by emersonlaurentino** [comment]
@segunadebayo Thanks for the example, I think it would be nice if you put it in the documentation.

**Comment by segunadebayo** [comment]
Yes, I'll add it to the docs.

**Comment by emersonlaurentino** [comment]
Thanks!
