### ISSUE TITLE
[Modal] scrollBehavior="inside" causes modal's box-shadow to be clipped

### ISSUE THREAD

**Issue by adamck** [chakra-ui/chakra-ui#1240]
When the Modal's `scrollBehavior` prop is set to "inside" the Modal does not display correctly.

Straight from the Modal Getting Started page (with enhanced red drop-shadow for better visibility):

![image](https://user-images.githubusercontent.com/986553/87592745-39cc2000-c69f-11ea-9966-58251a6f0263.png)

**Expected Behavior** 
Expect modal's drop-shadow to be fully visible.

**Steps to Reproduce** 

1. Open any instance of `<Modal scrollBehavior="inside" />`

**Suggested solution(s)**

`<Modal>` or `<ModalContent>` needs its overflow or margin settings adjusted for this case.

**Desktop:**
- OS: OS X
- Browser: Chrome, Firefox
- Version: Chrome 83, Firefox 78

**Comment by segunadebayo** [comment]
Good catch @adamck.

We've fixed this in the v1.0 release coming up soon. We'll publish an update shortly.

Thanks.

**Comment by segunadebayo** [comment]
This was an `overflow:hidden` issue specifically and simply getting rid of that property fixed it.

As a temporary walk around, you can consider passing `overflow: visible` directly to `ModalContent` to override this behavior.

Cheers
