### ISSUE TITLE
[Heading] Heading fontSize prop not working correctly

### ISSUE THREAD

**Issue by trevorblades** [chakra-ui/chakra-ui#1242]
When trying to override the default `fontSize` on the `Heading` component, the default responsive styles are taking precedent over my preference. I did not notice this effect in v1.0.0-next.4, but only after I upgraded to v1.0.0-next.6.

The default `fontSize` defined in the `Heading` part of the default theme looks like this:

```js
{ fontSize: ["3xl", null, "4xl"] }
```

See: https://github.com/chakra-ui/chakra-ui/blob/master/packages/theme/src/components/heading.ts#L21

Knowing this, when I create a component like `<Heading fontSize="3xl" />`, I'm expecting the default array of responsive styles to be replaced with my hard-coded single value (the behaviour in v0.8.0 and v1.0.0-next.4). Instead, my styles appear to only be applied to the `base` part of the responsive style array, leaving the larger breakpoints intact.

Given the following code:

```js
return (
  <>
    <Heading fontSize="5xl"> I ❤️ Chakra UI</Heading>
    <Heading fontSize="4xl"> I ❤️ Chakra UI</Heading>
    <Heading fontSize="3xl"> I ❤️ Chakra UI</Heading>
  </>
)
```

I get the following results on a wide screen:

![Screen Shot 2020-07-15 at 1 38 40 PM](https://user-images.githubusercontent.com/1216917/87593595-89f7b200-c6a0-11ea-8fee-b3dc8b1c4d1a.png)

An example of the resulting styles on the largest `Heading` in my code on this window width:

![Screen Shot 2020-07-15 at 1 39 53 PM](https://user-images.githubusercontent.com/1216917/87593772-d80cb580-c6a0-11ea-887f-5d3d5a39d126.png)

And the following on a mobile device:

![Screen Shot 2020-07-15 at 1 38 18 PM](https://user-images.githubusercontent.com/1216917/87593600-8bc17580-c6a0-11ea-96e8-989866dff155.png)

I made a CodeSandbox to replicate this error: https://codesandbox.io/s/hopeful-payne-07n9r?file=/src/App.js:125-286

You can see this effect in action yourself by resizing this window: https://07n9r.csb.app

**Comment by trevorblades** [comment]
Update: In the mean time, you can avoid this issue by disabling `sizes` under the `Heading` component key in your theme file.

```js
import theme from '@chakra-ui/theme';

export default {
  ...theme,
  components: {
    ...theme.components,
    Heading: {
      ...theme.components.Heading,
      sizes: null
    }
  }
}
```

**Comment by segunadebayo** [comment]
Thanks for catching this @trevorblades.

I've just fixed this issue. We'll release an update shortly.
