### ISSUE TITLE
How to add href to Icon or Icon button component?

### ISSUE THREAD

**Issue by gauravprachchhak** [chakra-ui/chakra-ui#1252]
Hi all,

I am new to Chakra and currently I am creating my blog with it. So, my requirement is to create `Icon` which will act like button and have all features like `Button` with `href` prop. So, when clicked I can redirect to some page else.

I have tried creating function on `Iconbutton` component with `onclick` `window.location` hack.

This works with normal url like Google, twitter but this does does not work with icon having `mailto`

What to do?

**Comment by with-heart** [comment]
Hi @gauravprachchhak, could you create a CodeSandbox reproduction for us? A reproduction would make it much easier for us to help you. You can use this template which comes with Chakra pre-installed: https://codesandbox.io/s/chakra100-next-9ob26?file=/src/App.tsx

**Comment by segunadebayo** [comment]
Hi @gauravprachchhak,

Here's what you need to do:

```jsx
// Use the `as` prop to change the underlying element so it works correctly
<IconButton as="a" href="ww.gaurav.com" target="_blank" />
```

Hope this helps. Kindly re-open if you still run into any issues.

Cheers.

**Comment by gauravprachchhak** [comment]
Worked like a charm! Didn't knew we can also pass `a` into `as` prop. Thank you!
