### ISSUE TITLE
[Link] "as" prop not inferring correct types 

### ISSUE THREAD

**Issue by JClackett** [chakra-ui/chakra-ui#1255]
I know this issue has been brought up before, but this is to address the latest beta versions, which I thought it had been fixed in. 

Im sure I had it working using a previous beta version? Is this to do with the learn publishing issue as well? #1229 

The demo is using v1.0.0-next.6

The as prop isn't inferring the correct types still 

Demo:
https://codesandbox.io/s/cranky-mayer-2b7dt?file=/src/App.tsx

**Comment by segunadebayo** [comment]
Thanks for catching this @JClackett.

I've just resolved it, we'll release an update shortly.
