### ISSUE TITLE
[Menu] Improve submenu mouse-over behavior

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1257]
This issue is best explained by this tweet: https://twitter.com/diegohaz/status/1283557473027346439

**Comment by segunadebayo** [comment]
@with-heart, I'd like us to be a bit more conscious of what we build. I feel it shouldn't be in response to other component libraries otherwise, we'll end up with a pile of issues even though our intentions are great.

I love Reakit and still considering using its primitives instead of re-inventing the wheel.

That said, I'd like us to discuss things like this before opening an issue.

**Comment by with-heart** [comment]
Of course! I'm not looking to build our library in reaction to things other libraries build, but I do think it's important to be inspired by some of their more solid features, and this seemed like one of them. 

I should have done a better job explaining the issue rather than simply linking to a tweet, but I think it does add a nice polish that would be good for us to have too!

I'm fine with discussing ideas wherever, but I feel like putting them in issues allows us to keep feature discussions open to the community and also serves as historical documentation, so that someone that comes along later could find the issue and understand which direction we're planning on moving, or why we decided to implement it/not implement it/hold on it until later, and other contextual things like that! Sort of like #LearnInPublic, but at the organization level instead of the individual level.

I definitely didn't mean for opening this to come off as suggesting that it's something we should definitely implement, just something we should discuss and maybe implement later :)

**Comment by segunadebayo** [comment]
Let's see how far we can go without supporting sub-menus, I feel most users don't really use them but we'll re-open this once we have some user request for sub-menus.

I have a better idea from a UX perspective that might be better than using sub-menus.

**Comment by with-heart** [comment]
@segunadebayo Excited to hear about that idea :)

**Comment by 55Cancri** [comment]
@segunadebayo Why does chakra-ui not support submenus? It looked like it was going so well in your twitter thread - https://twitter.com/thesegunadebayo/status/1257280339963269121?lang=en. I'm currently working on a project that requires the use of submenus. What is your alternative UX and can it be implemented in chakra-ui's current version?

**Comment by hazem3500** [comment]
Hey @segunadebayo, are there any updates on this?
is there a branch with the code in https://twitter.com/thesegunadebayo/status/1257280339963269121?lang=en that we could fork 😁?

**Comment by jgiunta1** [comment]
+1 would like submenus

**Comment by dailycommit** [comment]
It's been a long time since it was said that the submenu feature will come soon, but it has not been added yet, is there a problem? Looking forward to using this feature.

**Comment by JClackett** [comment]
Submenus would be great!!

**Comment by belaarany** [comment]
Still missing submenus 😢

**Comment by rotimidokun** [comment]
I have heard about Chakra and thought to use it for the first time. I need the submenu feature.

**Comment by selvinkuik** [comment]
+1 for submenu support

**Comment by avdkishore** [comment]
Please add support for submenu.

**Comment by paulcarroll** [comment]
+1 for submenu support!

**Comment by lazycoder1** [comment]
+1 lets get the submenu feature pushed !

**Comment by grvsharma1810** [comment]
+ 1 for submenu

**Comment by sorensenjg** [comment]
+1 for submenus

**Comment by dailycommit** [comment]
This has become a tedious wait 😡, I think it's time to talk about the implementation of third-party modules. I am open to any suggestions to solve this problem.

**Comment by frle10** [comment]
Another +1 for submenus!

**Comment by JonathanGafar** [comment]
Just echoing the support for submenus!

**Comment by XkoderFX** [comment]
+1 for submenus

**Comment by timkindberg** [comment]
I'm over here implementing them on my own using v1.2.1. 😓

**Comment by with-heart** [comment]
> I'm over here implementing them on my own using v1.2.1. 😓

Is your implementation public by any chance?

Also hi! I miss you and hope you're doing well ❤️

**Comment by timkindberg** [comment]
oh hai @with-heart! I spent a little time to dump it into a code sandbox. The thing it we are on an older version so I'm not sure if it'll still work in newer versions. Anyway, here it is:

https://codesandbox.io/s/chakra-nested-sub-menu-8xngmq?file=/src/App.tsx

We are doing well over here! Miss you too dude!

**Comment by timkindberg** [comment]
Just wanna say that if you guys didn't export the hooks separately from teh components I wouldn't have been able to pull this off in a decently non-hacky way like I did. I was awesome being able to reimplement and extend things that I needed using your hooks!

**Comment by rctheriot** [comment]
+1 for submenus

**Comment by rctheriot** [comment]
For anyone still needing a submenu here is an example using Chakra without any outside libs.

https://user-images.githubusercontent.com/19752298/234689130-46373f4b-2800-45a5-b8c1-8a67cb35983c.mov


```typescript
function SubmenuExample() {
  const [submenuOpen, setSubmenuOpen] = useState<boolean>(false);

  const openSubmenu = () => {
    if (!submenuOpen) {
      setSubmenuOpen(true);
    }
  };

  const closeSubmenu = () => {
    if (submenuOpen) {
      setSubmenuOpen(false);
    }
  };

  const toggleSubmenu = () => {
    setSubmenuOpen(!submenuOpen);
  };

  return (
    <Menu>
      <MenuButton as={Button} size="md" variant={'solid'} colorScheme="red">
        Open Menu
      </MenuButton>
      <MenuList>
        <MenuItem>Menu Item 1</MenuItem>
        <MenuItem>Menu Item 2</MenuItem>
        {/* Submenu */}
        <Menu isOpen={submenuOpen} placement="right-end" onClose={closeSubmenu}>
          <MenuButton as={MenuItem} onClick={toggleSubmenu}>
            Open Submenu
          </MenuButton>
          <MenuList>
            <MenuItem>Submenu Item 1</MenuItem>
            <MenuItem>Submenu Item 2</MenuItem>
            <MenuItem>Submenu Item 3</MenuItem>
          </MenuList>
        </Menu>
      </MenuList>
    </Menu>
  );
}
```

**Comment by leonardomgt** [comment]
Good solution @rctheriot. Thanks! 
I noticed the "Open Submenu" MenuItem option does not show the hover background. Any fix for that?

**Comment by rctheriot** [comment]
> Good solution @rctheriot. Thanks! I noticed the "Open Submenu" MenuItem option does not show the hover background. Any fix for that?

I know this is late, but maybe other people will find it helpful. 

You can use the `_hover` prop on the `MenuButton`

```
const hoverColorMode = useColorModeValue('gray.100', 'whiteAlpha.100');
const hoverColor = useToken('colors', hoverColorMode);
...
...
{/* Submenu */}
     <Menu isOpen={submenuOpen} placement="right-end" onClose={closeSubmenu}>
        <MenuButton 
           as={MenuItem} 
           onClick={toggleSubmenu}   
           _hover={{ backgroundColor: hoverColor }}
         >
            Open Submenu
        </MenuButton>
...
...
```

**Comment by baptisteArno** [comment]
Surprisingly easy to implement that on mouse hover with debounce:

https://github.com/chakra-ui/chakra-ui/assets/16015833/47ea3782-df66-4494-97c8-13e7c8f87d5a

```ts
import {
  MenuList,
  MenuItem,
  useDisclosure,
  Menu,
  MenuButton,
  HStack,
  Text,
} from '@chakra-ui/react'
import {
  CopyIcon,
  TrashIcon,
  RepeatIcon,
  ChevronRightIcon,
} from '@/components/icons'
import { useTypebot } from '@/features/editor/providers/TypebotProvider'
import { BlockIndices } from '@typebot.io/schemas'
import { useTranslate } from '@tolgee/react'
import { useDebouncedCallback } from 'use-debounce'

type Props = { indices: BlockIndices }
export const BlockNodeContextMenu = ({ indices }: Props) => {
  const { onClose, onOpen, isOpen } = useDisclosure()
  const debounceSubMenuClose = useDebouncedCallback(onClose, 200)
  const { t } = useTranslate()
  const { deleteBlock, duplicateBlock } = useTypebot()

  const handleDuplicateClick = () => duplicateBlock(indices)

  const handleDeleteClick = () => deleteBlock(indices)

  const handleMouseEnter = () => {
    debounceSubMenuClose.cancel()
    onOpen()
  }

  return (
    <MenuList>
      <Menu isOpen={isOpen} placement="right" offset={[0, 0]} onClose={onClose}>
        <MenuButton
          as={MenuItem}
          onClick={onOpen}
          onMouseEnter={handleMouseEnter}
          onMouseLeave={debounceSubMenuClose}
          icon={<RepeatIcon />}
        >
          <HStack justifyContent="space-between">
            <Text>Turn into</Text>
            <ChevronRightIcon />
          </HStack>
        </MenuButton>
        <MenuList
          onMouseEnter={handleMouseEnter}
          onMouseLeave={debounceSubMenuClose}
        >
          <MenuItem>Submenu Item 1</MenuItem>
          <MenuItem>Submenu Item 2</MenuItem>
          <MenuItem>Submenu Item 3</MenuItem>
        </MenuList>
      </Menu>
      <MenuItem icon={<CopyIcon />} onClick={handleDuplicateClick}>
        {t('duplicate')}
      </MenuItem>
      <MenuItem icon={<TrashIcon />} onClick={handleDeleteClick}>
        {t('delete')}
      </MenuItem>
    </MenuList>
  )
}
```
