### ISSUE TITLE
Request to add onOpen/onClose props to Menu component

### ISSUE THREAD

**Issue by chrysb** [chakra-ui/chakra-ui#1258]
**What problem does this feature solve?**
Currently, there's no reliable way to know if a `Menu` has opened or closed. 

**What does the proposed API look like?**
I would just add an `onOpen` and `onClose` prop to the `Menu` component

**Describe alternatives you've considered**
I'm currently trying to simulate this by capturing clicks myself. Not sure if it's going to work out yet.

**Additional context**
It's nice to have access to the internal state from within the `Menu` hierarchy, but in my use case, I need to know when the state changes outside of the context of the `Menu` hierarchy

**Comment by segunadebayo** [comment]
This is in line with #1233. Permit me to close this to avoid duplication.

Also, I'm looking into it now.
