### ISSUE TITLE
[question]: <Box /> is there a way to write an adjacent sibling combimnator on a Box?

### ISSUE THREAD

**Issue by nisarhassan12** [chakra-ui/chakra-ui#1259]
Hi!

I have a scenario where I want every `<Box />` which is followed by another `<Box />` to have had a border-top whose colour changes via `useColorMode` hook. 

I tried to do this with emotion the border does shows up but the change in colour mode does not change the colour of the border. 

I suspect that's because the <GloabalStyles /> component does not re-render on change in the color mode(not too sure though).

This is what the emotion version of the component looks like:

```jsx
import { colors, gutters } from '../themes/neonLaw';

import { Box } from '@chakra-ui/core';
import { Container } from './container';
import React from 'react';
import styled from '@emotion/styled';

const StyledSection = styled(Box)`
  padding: ${gutters.largeOne} 0;

  & + & {
   border-top: var(--border-light);
 }

  h2 {
    &::after {
      content: '';
      display: block;
      height: 2px;
      width: 8rem;
      height: 2px;
      background: ${colors.cyanLight};
      margin: 1rem 0;
    }
  }
`;

export const Section = ({
  children,
}: {
  children: JSX.Element | JSX.Element[];
}) => (
  <StyledSection as="section">
    <Container>{children}</Container>
  </StyledSection>
);

```

The border is defined as a variable where the colour value changes in accordance with the colour mode.

```jsx
import { Global, css } from '@emotion/core';
import { colors, gutters } from '../themes/neonLaw';
import { theme, useColorMode } from '@chakra-ui/core';

import React from 'react';

const BaseStyles = () => {
  const { colorMode } = useColorMode();

  return (
    <Global
      styles={css`
        /* ---------------------------------- */
        /* ----- Basic Setup ----- */
        /* ---------------------------------- */

        :root {
          --lightBlue: #63b3ed;
          --outline: 2px solid var(--lightBlue);
          --grid-max-width: 1240px;

          --border-light: 1px solid ${colors.borderLight[colorMode]};
        }
```

**Comment by nisarhassan12** [comment]
Thanks, @segunadebayo here is the sandbox link https://codesandbox.io/s/falling-wind-pbp2n?file=/src/app.js.
Sorry for my poor comunication skills.

**Comment by with-heart** [comment]
Hi @nisarhassan12!

Check out the "Styling Color Modes" docs: https://chakra-ui.com/color-mode#styling-color-modes. It has what you need for styling based on `colorMode`.

See this section on how to style borders using props: https://chakra-ui.com/style-props#borders
