### ISSUE TITLE
[Modal] are not at the top of the layer

### ISSUE THREAD

**Issue by lamualfa** [chakra-ui/chakra-ui#1266]
### Before the Modal open:

![image](https://user-images.githubusercontent.com/39755201/87734001-89bff980-c7fb-11ea-9f92-a5cc0c9ae423.png)

<hr />

### After the Modal open:

![image](https://user-images.githubusercontent.com/39755201/87734143-fe933380-c7fb-11ea-9e19-58c5d1a8cbb3.png)

<hr />

### After I set the `z-index` property on `chakra-select__icon-wrapper` to `0`: (Default `2`)

![image](https://user-images.githubusercontent.com/39755201/87734290-68abd880-c7fc-11ea-97eb-c8bcc2b89471.png)

<hr />

### My Environment:

- `@chakra-ui/core`: `^1.0.0-beta`
- `@chakra-ui/theme`: `^1.0.0-next.3`

**Comment by segunadebayo** [comment]
Good catch @lamualfa.

I've just resolved this and we'll publish an update shortly.
