### ISSUE TITLE
Storybook link does not work

### ISSUE THREAD

**Issue by woodworker** [chakra-ui/chakra-ui#127]
When i follow the Storybook link on the main website i see the Storybook UI and the message "Page Not Found
Looks like you've followed a broken link or entered a URL that doesn't exist on this site."
and the menu never loads so i can not select anything

**Comment by Ronva** [comment]
I wanted to see if I could figure out what the right link was with no luck. On the bright side I found a hilarious interaction where you can just recursively open the storybook within itself every time you click "back to our site" 😂

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/24194291/65824564-40d19100-e239-11e9-8cc1-087d1e7ed772.png">

**Comment by segunadebayo** [comment]
I'm looking into this now.
