### ISSUE TITLE
How to parse markdown files as chakra-ui components?

### ISSUE THREAD

**Issue by gauravprachchhak** [chakra-ui/chakra-ui#1270]
I am trying to implement a blog using `Gatsby` and `Chakra-UI` and for blog post's data I am using `Markdown` files. Now I am able to parse the markdown to normal `HTML` using `Markdown Remark` but I am confused as to how to convert that `HTML` to `Chakra-UI` components.

Or do I have to use pure `CSS`?

**EDIT**: I found one way to achieve this using `mdx` and `gatsby-plugin-mdx` and inside `mdx` importing `Chakra-UI` components. Is this the correct pattern?

Thanks in advance

**Comment by navin-moorthy** [comment]
> **EDIT**: I found one way to achieve this using `mdx` and `gatsby-plugin-mdx` and inside `mdx` importing `Chakra-UI` components. Is this the correct pattern?

@gauravprachchhak Yes, thats the correct way to do it.

Chakra UI Docs is powered in the same manner.

You can find the source code on how it's done here - https://github.com/chakra-ui/chakra-ui/blob/master/website/src/components/mdx-components.js

Complete Gatsby Docs path - https://github.com/chakra-ui/chakra-ui/tree/master/website - Hope this helps you

**Comment by segunadebayo** [comment]
Thanks for chiming in @navin-moorthy.

That reply solves your challenge @gauravprachchhak.

Cheers

**Comment by gauravprachchhak** [comment]
Yeah, this is what I was working with. Just wanted to confirm the pattern. Thank you clearing this out for me. @navin-moorthy

**Comment by NicolaGenesin** [comment]
I know it's an old post, but I've used https://www.npmjs.com/package/chakra-ui-markdown-renderer to achieve this
