### ISSUE TITLE
Is there a way to make Stack's direction responsive?

### ISSUE THREAD

**Issue by BrandoIsNotASword** [chakra-ui/chakra-ui#1271]
I'm trying to use Stack for a responsive component, so the direction can be changed depending on the width of the screen.

I'm doing like this, but it gives an error:

```
      <Stack direction={{ base: 'column', lg: 'row' }} spacing={5} width="100%" shouldWrapChildren>
        <Link to="/rooms">Rooms</Link>
        <Link to="/luxury-retreats">Luxury retreats</Link>
        <Link to="/experiences">Experiences</Link>
        <Link to="/experiences">Contact us</Link>
      </Stack>
```

**Comment by lamualfa** [comment]
What is the error?

**Comment by JClackett** [comment]
Make sure you include what version of chakra you are using when posting an issue otherwise it makes it hard to know what might be wrong...

What version are you using? Are you using the latest betas? I believe this was added in them: https://next.chakra-ui.com/docs/layout/stack#responsive-direction

**Comment by segunadebayo** [comment]
Hi @BrandoIsNotASword,

We've added support for responsive stack direction in the upcoming v1 version.

We hope to publish it soon. Thanks
