### ISSUE TITLE
[Link] Props of "as" component are not inferred

### ISSUE THREAD

**Issue by asterikx** [chakra-ui/chakra-ui#1280]
**Describe the bug** A clear and concise description of what the bug is.

The `Link` component does not infer props from the `as` component. This appears to be a regression between `next.4` (working) and `next.6` (not working).

Example using `react-router`:

```tsx
import { Link } from "@chakra-ui/core";
import { Link as RouterLink } from "react-router-dom";

function InternalLink() {
  return (
    <Link as={RouterLink} to="/foo">
      hi
    </Link>
  );
}
``` 

Typescript error:

```
Type '{ children: TFunctionResult; as: ForwardRefExoticComponent<LinkProps & RefAttributes<HTMLAnchorElement>>; to: string; onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & Pick<LinkProps, "children" | "p" | "slot" | "style" | "title" | "size" | "className" | "color" | "height" | "id" | "lang" | ... 497 more ... | "isExternal"> & RefAttributes<...>'.
  Property 'to' does not exist on type 'IntrinsicAttributes & Pick<LinkProps, "children" | "p" | "slot" | "style" | "title" | "size" | "className" | "color" | "height" | "id" | "lang" | ... 497 more ... | "isExternal"> & RefAttributes<...>'.  TS2322
```

**Expected Behavior**

The `Link` component should infer props from the `as` component (as in `next.5`)

**Link to minimal reproduction**

https://codesandbox.io/s/jolly-moon-1oy5x?file=/src/App.tsx

**Comment by segunadebayo** [comment]
Thanks for catching this @asterikx.

Someone else reported this and we've fixed it. We'll publish an update shortly.

**Comment by asterikx** [comment]
Ah, nice! Sorry, came straight from Discord to report here, didn't check if anyone else had already reported ;)

**Comment by wilgnne** [comment]
I'm having the same problem with version 1.6.1 of the Chakra UI, and the Next JS Link

**Comment by deven-gqc** [comment]
> Someone else reported this and we've fixed it. We'll publish an update shortly.
Can you add a link to where the issue was fixed?
