### ISSUE TITLE
[Collapse] Add isLazy prop

### ISSUE THREAD

**Issue by dodas** [chakra-ui/chakra-ui#1282]
It would be nice to have `isLazy` property for `<Collapse>` component as well.
I am rendering tree-like structure with `Collapse` component and need to defer rendering inner components until parent is expanded.

I am currently work-arounding it like this:
```tsx
<Collapse isOpen={isExpanded}>
  <Box>
    {isExpanded &&
      <Box padding={2}>
        content...
      </Box>
    }
  </Box>
</Collapse>
```

Related: https://github.com/chakra-ui/chakra-ui/issues/1235

**Comment by segunadebayo** [comment]
Hi @dodas,

Considering that the Collapse is powered by `react-animate-height`, we might not be able to support this use-case. I'd recommend you handle this yourself, just like you described.

Cheers.
