### ISSUE TITLE
Scrollbar Flicker during Modal

### ISSUE THREAD

**Issue by pkrogel-kws** [chakra-ui/chakra-ui#129]
If your page has a scrollbar, using Modal (and possibly Drawer--haven't checked) causes a layout flicker.  It looks like this can be fixed by passing `{reserveScrollBarGap : true}` to 'body-scroll-lock'.

**Comment by segunadebayo** [comment]
Thanks for this issue and for providing a suggestion to fix it @pkrogel-kws. It saved me some time. I'll release a patch soon.

**Comment by segunadebayo** [comment]
I've released a patch
