### ISSUE TITLE
Do we need a Multiselect component?

### ISSUE THREAD

**Issue by Samic8** [chakra-ui/chakra-ui#1293]
A Multiselect is a common input, and it seems like Chakra is missing it.

The API would use a [compound component API](https://www.samdawson.dev/article/compound-components-what-why-when). Example:
```jsx
<Multiselect
  selectedValues={[1, 2]}
  onSelectedValuesChange={newValues => /* ... */}/>
  <Option optionValue={1}>One</Option>
  <Option optionValue={2}>Two</Option>
  <Option optionValue={3}>Three</Option>
</Multiselect>
```

The API could be simpler and use strict props, but it would be less flexible. The compound component pattern would allow people to switch out the `<Option />` component.

I would like to contribute to Chakra by writing this component, does this sound like a good addition?

**Comment by Samic8** [comment]
The [Select](https://chakra-ui.com/select) uses the browsers **<select>** for the options UI. Should the Multiselect do the same?

**Comment by with-heart** [comment]
The most important consideration in building a new component for Chakra is to follow accessibility/aria guidelines to ensure that our components work well for all users, regardless of device or interface.

Multiselect falls under the `listbox` role. Here are some resources for how to build a aria-compliant `listbox` elements:

- MDN overview of the `listbox` role: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role
- w3c `listbox` examples: https://www.w3.org/TR/2017/WD-wai-aria-practices-1.1-20170628/examples/listbox/listbox.html

**Comment by with-heart** [comment]
From the MDN overview:

> It is highly recommended to use the HTML select element, or a group of radio buttons if only one item can be selected, or a group of checkboxes if multiple items can be selected, because there is a lot of keyboard interactivity to manage focus for all the descendants, and native HTML elements provide this functionality for you for free.

**Comment by Samic8** [comment]
Thanks, @with-heart. I might come up with a quick prototype (in codepen or similar) I can share for feedback and if that is well received I can make a Chakra UI version that better follows Chakra code standards. How does that sound?

**Comment by with-heart** [comment]
@Samic8 That sounds most excellent! 🤘

**Comment by Samic8** [comment]
It seems the functionality I was thinking this Multiselect would provide already exists in the Menu component as [MenuItemOption](https://chakra-ui.com/menu#menu-option-groups). 

Maybe we could create a `Multiselect` that internally uses `Menu` and `MenuItemOption` to provide an API like I first mentioned in this issue. It might be called something like `MenuMultiselect` which would leave room for a `Listbox` style component in this library in the future.

Let me know what you think @with-heart. Thanks!

**Comment by Samic8** [comment]
I now think my suggestion about using MenuItemOption internally would create too tight of coupling with the Mutliselect and it would be hard to provide anything extra of value that users can't already do with the Menu and MenuItemOption.

In my last comment, I was confused about the difference `<listbox>` element and `listbox` role. I think this Multiselect component would still be a `listbox` role like you suggested. I will continue with my prototype 🔨

**Comment by with-heart** [comment]
@Samic8 Sorry for not getting back to you! Please do!

**Comment by with-heart** [comment]
@allcontributors please add @Samic8 for idea

**Comment by aaronmcadam** [comment]
I just found a reference implementation based on Tailwind UI: https://github.com/mitchbne/react-listbox

**Comment by with-heart** [comment]
Closing this issue as part of our backlog cleanup. Adding a multi-select/combobox component is work the team plans to accomplish in the near future.

**Comment by Samic8** [comment]
Hi @with-heart. I had some time scheduled to work on this over 14-15th of December as part of volunteer days the company I work offers. Is there any other tasks you could point me towards where I could make use of that time?

Thanks

**Comment by aaronmcadam** [comment]
@Samic8 it looks like the component I mentioned has stopped development. They recommend https://github.com/tailwindlabs/headlessui/tree/develop/packages/%40headlessui-react. Might be worth a look :)

**Comment by with-heart** [comment]
Hi @Samic8! We currently have a [bug triage board](https://github.com/chakra-ui/chakra-ui/projects/5) with issues that need some attention. I haven't organized prioritized any of them yet but plan to do so in the next day or three.

Beyond that, I recommend asking what's available closer to that date [on our Discord](https://discord.gg/dQHfcWF) and we can help figure out what's prioritized and available for you and possibly even make sure one or two of us is available to assist you on your journey through the codebase if needed!

**Comment by Samic8** [comment]
That sounds good. Thanks @with-heart!

**Comment by with-heart** [comment]
@Samic8 Thanks for choosing Chakra as the target for your volunteer time! That's very kind!

**Comment by hus-o** [comment]
Any update on this? I'm loving Chakra but I want to use a multi-select dropdown, currently not possible so I'm having to find and mix different libraries, would be lovely to have it natively.

**Comment by m4tta** [comment]
Chakra already pulls in external libraries for a few components. Why not bring in react-select for this? 
[https://react-select.com/](https://react-select.com/)

**Comment by la55u** [comment]
@m4tta unfortunately it's abandonware https://github.com/JedWatson/react-select/issues/4293, not accessible and does not support react 17.

**Comment by m4tta** [comment]
The thread clearly shows it is **not** abandonware. That they are clearly working on it and the community support is strong.

Not sure what the react 17 relevancy is here.

**Comment by lmi-dk** [comment]
This looks interesting.. https://github.com/koolamusic/chakra-ui-autocomplete

**Comment by csandman** [comment]
I'm not sure what the progress on this is but I wanted to share my wrapper for react-select's multi component.  I needed something like this to use with Chakra and wanted it to look the same so I spent a decent amount of time making it match visually.  If you want to use it, here's the source.  Feel free to modify it as needed until an official Chakra version comes out.

- Gist: https://gist.github.com/csandman/c687a9fb4275112f281ab9a5701457e4
- CodeSandbox: https://codesandbox.io/s/chakra-ui-react-select-648uv?file=/multi-select.js

**Comment by csandman** [comment]
> @m4tta unfortunately it's abandonware [JedWatson/react-select#4293](https://github.com/JedWatson/react-select/issues/4293), not accessible and does not support react 17.

In addition to what @m4tta said, `react-select` is quite accessible, with many of the necessary aria props.  I tested it with a screen reader and it worked quite well.

**Comment by JavaJamie** [comment]
When will this be available?

**Comment by JavaJamie** [comment]
Something like a select with check boxes against each item which could be selected? That would be really useful. I hate littering the view with an array of check boxes...

**Comment by mpiorowski** [comment]
very good looking component, sad it's not working with typescript

**Comment by csandman** [comment]
> very good looking component, sad it's not working with typescript

If you're talking about my component, I added typescript support in 1.2.0.  Let me know if its still not working!

**Comment by Mustycodes** [comment]
Nice component. Although, I am currently trying to use this with typescript but I can't

**Comment by csandman** [comment]
@Mustycodes what specifically isn't working?

**Comment by csandman** [comment]
@Mustycodes could you give me an example of the errors?  I'm currently using it in a typescript project and its working so I'd be curious to hear whats not working for you so I can fix it.  I'm still pretty new to Typescript so i'm not surprised there are some kinks

**Comment by csandman** [comment]
@Mustycodes ah well, I appreciate the heads up anyway.  I have to redo a decent chunk of the Typescript in order to update to react-select v5 so it may work more consistently with typescript then.

**Comment by nelsieborja** [comment]
> Closing this issue as part of our backlog cleanup. Adding a multi-select/combobox component is work the team plans to accomplish in the near future.



> Closing this issue as part of our backlog cleanup. Adding a multi-select/combobox component is work the team plans to accomplish in the near future.

It's been a year... any update on this?

**Comment by albertbronsky** [comment]
> @nelsieborja the core team is refactoring the codebase to use state machines, complex components like this will be available after that and soon.

@anubra266 

So... Any ETA for that? :)

**Comment by csandman** [comment]
@mpiorowski @Mustycodes I just wanted to let you guys know, if you're still looking for a component to do this, I have greatly improved my [`chakra-react-select`](https://github.com/csandman/chakra-react-select) component, specifically the TypeScript support.  It should now work with TypeScript just as well as the original `react-select` package does, as they added native TS support in v5 and I finally got my package updated to work on that version.

**Comment by Mustycodes** [comment]
> @mpiorowski @Mustycodes I just wanted to let you guys know, if you're still looking for a component to do this, I have greatly improved my [`chakra-react-select`](https://github.com/csandman/chakra-react-select) component, specifically the TypeScript support. It should now work with TypeScript just as well as the original `react-select` package does, as they added native TS support in v5 and I finally got my package updated to work on that version.

Alright, I will check it out. Thanks a lot.

**Comment by LiteSoul** [comment]
@csandman Chris I wanted to thank you so much for your component, it's been very useful and you managed to fuse 2 of the best libraries, thanks!
PS: Unfortunately it doesn't work for the new zero installs method used by Yarn since v2, which is now the default approach.

**Comment by csandman** [comment]
@LiteSoul can you elaborate on what isn't working specifically and what broke it?  I'm not sure what you mean by the "new zero installs method", as I don't generally use yarn, but I'd like to help make it work if I can.

Better yet, if you can leave a detailed issue (yarn version, CRS version, specific error, etc.) on the project, that would be the easiest way for me to help! https://github.com/csandman/chakra-react-select/issues. Better there than to spam this thread haha.

**Comment by ErlanBelekov** [comment]
any progress on this?

**Comment by charlie0077** [comment]
Cannot believe the team still does not provide the multi-select UI after almost 3 years.

**Comment by ujjwal-kr** [comment]
certified chakra ui moment

**Comment by PhantomKnight287** [comment]
skill issue

**Comment by alinabarenboim123** [comment]
And update on this?

**Comment by rodrigoea** [comment]
are there any updates or plans for the multi-select?

**Comment by rodrigoea** [comment]
Here's a version I started building for my app using Chakra UI components, if anyone also wants it.

https://github.com/chakra-ui/chakra-ui/assets/1905961/ead47f59-b5a6-4a64-bfbc-4d7559b9fa4d

Here's the CodeSandbox for reference – it's just a simple component, and it might not be 100% optimized for your application yet 🤓 

https://codesandbox.io/s/chakra-ui-multiselect-kn2gvz?file=/src/multi-select.js
