### ISSUE TITLE
[Skeleton]: Can't read property 'gray' of undefined.

### ISSUE THREAD

**Issue by clngkusnd** [chakra-ui/chakra-ui#1295]
**Descriptions**
1. Importing Skeleton component cause problem that throw error "`Can't read property 'gray' of undefined.`"
2. Using AspectRatioBox, children `width` and `height` style properties value treated as `full`.

**Codesanbox** 
- https://codesandbox.io/s/chakra-ui-with-storybook-tks8u?file=/src/components/Bug.js

**Notes**
I use the latest version of *@storybook/react*.

**Comment by Geeman201** [comment]
Hey,

Looks like you've got a couple of problems. I forked your sandbox and I think fixed them all:
https://codesandbox.io/s/chakra-ui-with-storybook-r31id

1. The components are not wrapped in the `chakra-ui` `ThemeProvider` which means it's unable to look up "theme values" from context. On my sandbox I added a `decorator` via the `.storybook/preview.js` file as per the [Storybook docs](https://storybook.js.org/docs/addons/introduction/#storybook-decorators)

```jsx
import { ThemeProvider, CSSReset, theme } from '@chakra-ui/core'

function App({ children }) {
  return (
    <ThemeProvider theme={theme}>
      <CSSReset />
      {children}
    </ThemeProvider>
  );
}
```

2. `AspectRatioBox` requires a `ratio` and `maxWidth` prop to limit the size
https://chakra-ui.com/aspectratiobox#embed-image

3. The `Icon` is not exported as a "story" via a function
```jsx
// Use this 
export const Icon = () => <IconBug name="copy" />;

// Instead of this
export const Icon = <IconBug name="copy"/> 
```

4. Likewise the `Skeleton` isn't exported as a "stroy" and is missing the `height` `prop`
```jsx
// Use this
export const SkeletonExample = () => (<Skeleton height="40px" />)

// Instead of this
export { Skeleton } from '@chakra-ui/core`
```

**Comment by with-heart** [comment]
A minor nit here: I recommend using `ChakraProvider` over `ThemeProvider` where possible! It automatically enables color mode stuff, and hooks up `theme.styles.global`. Other than that, excellent assistance @Geeman201!

**Comment by clngkusnd** [comment]
I imported `ChakraProvider` at `@chakra-ui/core` but it was not found. There is something wrong? @with-heart

**Comment by with-heart** [comment]
My bad! I didn't realize this was for version `0.8.0`. Please ignore everything I said.

**Comment by clngkusnd** [comment]
Just updated to version `1.0.0-next.6`. `Skeleton` component still has problems. The props doesn't work at all. Can you check the updated codesandbox? @with-heart 

https://codesandbox.io/s/chakra-ui-with-storybook-tks8u?file=/src/stories/Issues.stories.js

**Comment by with-heart** [comment]
@clngkusnd Looks like it was fixed in the most recent version: https://codesandbox.io/s/chakra-ui-with-storybook-mn7t0?file=/src/stories/Issues.stories.js

Install `1.0.0-rc.0` please!
