### ISSUE TITLE
[Menu] Unwanted scroll behavior when blurring

### ISSUE THREAD

**Issue by mrmntte** [chakra-ui/chakra-ui#1299]
**Example 1**
1. Go to https://chakra-ui.com/menu
1. Open any menu and scroll up with the mouse inside the popover

![1](https://user-images.githubusercontent.com/49642108/87855478-37a3d480-c8de-11ea-8a27-da01487afa1a.gif)

**Example 2**
1. Go to https://chakra-ui.com/menu
2. Click on any select
3. Scroll down until the trigger disappear from the viewport
4. Click on another menu button or on some text

![2](https://user-images.githubusercontent.com/49642108/87855815-63c05500-c8e0-11ea-920f-797d6016648e.gif)

- OS: macOS 10.14.6
- Browser Chrome 83

**Comment by with-heart** [comment]
Hi @mrmntte, this issue has been fixed in our 1.0 pre-release. You can find more information here: https://next.chakra-ui.com/
