### ISSUE TITLE
Tabs not displayed as intended

### ISSUE THREAD

**Issue by cheapernepalstudio** [chakra-ui/chakra-ui#130]
1. The border color is not right on the tab as shown on the documentation 
2. The padding and spacing is not right as shown in the docs. 

Attached the image below. [link to the component](https://imgur.com/a/nFq9qiJ)

**Comment by segunadebayo** [comment]
Hi @cheapernepalstudio, are you using the `CSSReset` component in your app?

**Comment by cheapernepalstudio** [comment]
> Hi @cheapernepalstudio, are you using the `CSSReset` component in your app?

@segunadebayo  CSSRest component displays blank on the screen , when i inspect on the inspector (in chrome) inside the root className of my html element there is nothing. Meaning nothing is displayed on the screen. 

Here is my code.

```javascript
const Root = () => {
  return (
    <ApolloProvider client={client}>
      <ThemeProvider theme={theme}>
        <CSSReset>
          <Routing />
        </CSSReset>
      </ThemeProvider>
    </ApolloProvider>
  );
};

export default Root ;
```

**Comment by segunadebayo** [comment]
Here's how you should use the `CSSReset` component.

```jsx
const Root = () => {
  return (
    <ApolloProvider client={client}>
      <ThemeProvider theme={theme}>
          <CSSReset /> // <= it's doesn't have a children prop so make it self-closing.
          <Routing />
      </ThemeProvider>
    </ApolloProvider>
  );
};
```

Please try this and let's see if it works now.

**Comment by cheapernepalstudio** [comment]
Thanks, Works as intended :) my bad.
