### ISSUE TITLE
Add note about optional `GITHUB_TOKEN` environment variable for local docs development

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1309]
By default, the GitHub REST API has an anonymous user rate limit. This can be hit during heavy local docs development if the server is frequently restarted. Creating a GitHub token and storing it as the `GITHUB_TOKEN` environment variable allows the user to avoid the limit.

Probably belongs in `CONTRIBUTING.md`.

**Comment by segunadebayo** [comment]
Done!
