### ISSUE TITLE
Request to add `_focus` to `Box`

### ISSUE THREAD

**Issue by nahtnam** [chakra-ui/chakra-ui#1313]
**What problem does this feature solve?**

I was converting my tailwind site to Chakra and noticed that the `Box` component doesnt allow you to customize `focus` properties.

**What does the proposed API look like?**

```jsx
<Box _focus={{ outline: 'none' }} />
```

**Describe alternatives you've considered** 

Currently it looks like I'll have to use css to do this

**Comment by with-heart** [comment]
Hi @nahtnam!

As part of our move to 1.0, `Box` now has a `_hover` prop. 

If you're still using `@chakra-ui/core@<0.8`, you'll want to use the `PseudoBox` component instead, which has all of the pseudo props for CSS selectors. https://chakra-ui.com/pseudobox

**Comment by nahtnam** [comment]
Thank you! That's exactly what I'm looking for. Will `1.0`'s `Box` also have `_focus` and stuff like that?

**Comment by with-heart** [comment]
@nahtnam, yeap. `PseudoBox` no longer exists in 1.0 and all of the pseudo props have been added to `Box`.

**Comment by nahtnam** [comment]
Awesome, great to hear! Are there beta docs for 1.0 that I can look at? I don't see anything on the website

**Comment by aaronmcadam** [comment]
> Awesome, great to hear! Are there beta docs for 1.0 that I can look at? I don't see anything on the website

The beta docs are here: https://next.chakra-ui.com/
