### ISSUE TITLE
[Select] White on white option text

### ISSUE THREAD

**Issue by hissalht** [chakra-ui/chakra-ui#1315]
When using dark mode, the options in a Select element appear white on white which is illegible.

![image](https://user-images.githubusercontent.com/7683740/87886916-fb2cc180-ca20-11ea-8ba0-7565aab109a3.png)

**Expected Behavior** 
The text is legible.

**Link to minimal reproduction** 
https://codesandbox.io/s/pensive-rhodes-pntec?file=/src/Component.js

**Steps to Reproduce**
Render a `Select` element when dark mode is on.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefow Developer Edition, New Microsoft Edge

**Comment by with-heart** [comment]
Still occurring as of `next.6`. Reproduction: https://codesandbox.io/s/rough-meadow-3vyr2?file=/src/App.js

**Comment by segunadebayo** [comment]
This has been fixed in `v1.0.0-rc.0`
