### ISSUE TITLE
Screen flashes when changing urls

### ISSUE THREAD

**Issue by gauravprachchhak** [chakra-ui/chakra-ui#1316]
I have a website and I use color mode component to change between light and dark mode. Now, when I change pages(url) when in dark mode, a white screen quickly flashes before changing back to default dark mode color. Is this behaviour normal?

If not, how to resolve it?

Thanks in advance!

**Comment by with-heart** [comment]
Do you see this flash when you click on a link, or when you manually change the url in the address bar?

**Comment by gauravprachchhak** [comment]
When I click a link @with-heart

**Comment by with-heart** [comment]
Okay, just wanted to check! In that case, could you create a small CodeSandbox reproduction for us? Here's a minimal `1.0.0-next.6` template you can use: https://codesandbox.io/s/chakra100-next-9ob26

**Comment by gauravprachchhak** [comment]
I just figured out the problem. I was missing the `gatsby-plugin-catch-links` plugin. AFter installation, the page change started to feel like a SPA. Thank you.
