### ISSUE TITLE
Conflict with NextJS Link Component as Prop

### ISSUE THREAD

**Issue by harshzalavadiya** [chakra-ui/chakra-ui#132]
As of `next@9` nextjs Link also accepts `as` prop for dynamic routing so it breaks dynamic routed links, I am happy to submit PR fix for `chakra-ui` but will it be possible for chakra-ui's `Link` component `as` prop to be renamed to something else?

### Reference
https://github.com/zeit/next.js#dynamic-routing

**Comment by segunadebayo** [comment]
Hi @harshzalavadiya,

How about you try this

```jsx
import NextLink from "@next/link"
import { Link } from "@chakra-ui/core"

 <NextLink href="/post/[pid]" as={`/post/${pid}`}>
      <Link>Post {pid}</Link>
 </NextLink>
```

Since nextjs link is a default export, you can rename it to `NextLink` so there's no conflict. Changing Chakra's Link component name will cause some breaking change.

**Comment by harshzalavadiya** [comment]
Oh, I totally forgot next Link can take child component, should work fine

**Comment by cj** [comment]
@segunadebayo doing this with TS causes a type error as `href` is required for `import { Link } from "@chakra-ui/core"`

**Comment by Geeman201** [comment]
Hey - Heres a TS example 👍 

Definition:
https://github.com/chakra-ui/chakra-ui/blob/develop/examples/nextjs-typescript/components/NextChakraLink.tsx

Usage: 
https://github.com/chakra-ui/chakra-ui/blob/develop/examples/nextjs-typescript/pages/properties/index.tsx#L12

**Comment by binajmen** [comment]
> Hey - Heres a TS example 👍
> 
> Definition:
> https://github.com/chakra-ui/chakra-ui/blob/develop/examples/nextjs-typescript/components/NextChakraLink.tsx
> 
> Usage:
> https://github.com/chakra-ui/chakra-ui/blob/develop/examples/nextjs-typescript/pages/properties/index.tsx#L12

404. Could you please share the code ?

**Comment by geemanjs** [comment]
@binajmen - Updated links:

Definition:
https://github.com/chakra-ui/chakra-ui/blob/main/examples/nextjs-typescript/components/NextChakraLink.tsx

Usage:
https://github.com/chakra-ui/chakra-ui/blob/main/examples/nextjs-typescript/pages/properties/index.tsx#L19

**Comment by yarapolana** [comment]
@geemanjs I was having issues with this, thank you.

**Comment by fendorio** [comment]
For TS users, I knocked out something like this after stumbling on this post. 

```ts
// Because the website uses both NextJS & Chackra UI, and both export
// a Link component, this component wraps Chackra's link within NextJS's link
import React, { FC } from "react";
import NextLink, { LinkProps as NextLinkProps } from "next/link";
import {
  Link as ChackraLink,
  LinkProps as ChackraLinkProps,
} from "@chakra-ui/react";

interface IProps extends NextLinkProps {
  chackraLink?: ChackraLinkProps;
}

const Link: FC<IProps> = (props) => {
  const { chackraLink, children } = props;
  const nextLinkProps = {
    ...props,
    chackraLink: undefined,
    children: undefined,
  };
  return (
    <NextLink {...nextLinkProps} passHref>
      <ChackraLink {...chackraLink}>{children}</ChackraLink>
    </NextLink>
  );
};

Link.defaultProps = {
  chackraLink: {},
};

export default Link;
```

So the component takes NextJS's props at the top level, i.e. it's treated just as a NextJS link, with you being able to provide the props for the ChackraUI link via the chackraLink prop.

Usage

```ts
import Link from "./my-custom-link"
import {Text} from "@chakra-ui/react";

<Link href="/my-page-in-pages">
   <Text>Click me baby one more time</Text>
</Link>
```

**Comment by wackyjoker** [comment]
The way it worked for me is to integrate NextLinkProps and LinkProps of Chakra Ui
`import { FC } from 'react'
import NextLink, { LinkProps as NextLinkProps } from 'next/link'
import {
  Link, useColorModeValue, LinkProps,
} from '@chakra-ui/react'
import { ILinkItem } from './types'

type ChakraAndNextProps = NextLinkProps & LinkProps & ILinkItem

const LinkItem:FC<ChakraAndNextProps> = ({
  href, path, _target, children, ...props
}) => {
  const active = path === href
  const inactiveColor = useColorModeValue('gray200', 'whiteAlpha.900')
  return (
    <NextLink href={href} passHref>
      <Link
        p={2}
        bg={active ? 'grassTeal' : undefined}
        color={active ? '#202023' : inactiveColor}
        _target={_target}
        {...props}
      >
        {children}
      </Link>
    </NextLink>
  )
}

export default LinkItem`

**Comment by Motherships** [comment]
I modified example from chakraui example to use `ForwardRef` as `PopoverTrigger` needed to pass ref to its child to work properly

```js
import * as React from 'react'
import NextLink from 'next/link'
import { LinkProps as NextLinkProps } from 'next/dist/client/link'
import {
  Link as ChakraLink,
  LinkProps as ChakraLinkProps,
} from '@chakra-ui/react'

export type NextChakraLinkProps = React.PropsWithChildren<
  NextLinkProps & Omit<ChakraLinkProps, 'as'>
>

//  Has to be a new component because both chakra and next share the `as` keyword
const Link = React.forwardRef(function Link(
  {
    href,
    as,
    replace,
    scroll,
    shallow,
    prefetch,
    children,
    ...chakraProps
  }: NextChakraLinkProps,
  ref: React.ForwardedRef<HTMLAnchorElement>
) {
  return (
    <NextLink
      passHref={true}
      href={href}
      as={as}
      replace={replace}
      scroll={scroll}
      shallow={shallow}
      prefetch={prefetch}
    >
      <ChakraLink {...chakraProps} ref={ref}>
        {children}
      </ChakraLink>
    </NextLink>
  )
})

export default Link

```

**Comment by MichaelOren** [comment]
Updated Links and the code in case they get "lost" again:

[NextChakraLink Component](https://github.com/chakra-ui/chakra-ui/blob/main/examples/next-app/components/NextChakraLink.tsx)
```typescript
import { PropsWithChildren } from "react"
import NextLink from "next/link"
import { LinkProps as NextLinkProps } from "next/dist/client/link"
import {
  Link as ChakraLink,
  LinkProps as ChakraLinkProps,
} from "@chakra-ui/react"

export type NextChakraLinkProps = PropsWithChildren<
  NextLinkProps & Omit<ChakraLinkProps, "as">
>

//  Has to be a new component because both chakra and next share the `as` keyword
export const NextChakraLink = ({
  href,
  as,
  replace,
  scroll,
  shallow,
  prefetch,
  children,
  ...chakraProps
}: NextChakraLinkProps) => {
  return (
    <NextLink
      passHref={true}
      href={href}
      replace={replace}
      scroll={scroll}
      shallow={shallow}
      prefetch={prefetch}
    >
      <ChakraLink as="span" {...chakraProps}>
        {children}
      </ChakraLink>
    </NextLink>
  )
}
```


[Usage on a page](https://github.com/chakra-ui/chakra-ui/blob/main/examples/next-app/pages/properties/index.tsx)
```typescript
import { Heading, Wrap, WrapItem } from "@chakra-ui/react"
import { Layout } from "../../components/Layout"
import { properties } from "../../utils/sample-data"
import { PropertySummary } from "../../components/PropertySummary"
import { NextChakraLink } from "../../components/NextChakraLink"
import { Chakra } from "../../Chakra"

interface PropertiesProps {
  cookies?: string
}

const PropertiesPage = ({ cookies }: PropertiesProps) => (
  <Chakra cookies={cookies}>
    <Layout title="Next.js + TypeScript example | View properties">
      <Heading mb={4}>Available this weekend</Heading>
      <Wrap>
        {properties.map((property) => (
          <WrapItem key={property.id}>
            <NextChakraLink
              href="/properties/[id]"
              as={`/properties/${property.id}`}
            >
              <PropertySummary property={property} />
            </NextChakraLink>
          </WrapItem>
        ))}
      </Wrap>
    </Layout>
  </Chakra>
)

export default PropertiesPage
export { getServerSideProps } from "../../Chakra"
```

**Comment by Amazon-simple-email-serv** [comment]
@Motherships https://lnkr.fun/87084b9
