### ISSUE TITLE
Document `theme.layerStyles` and `theme.textStyles`

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1330]
This issue is for adding docs to the theming section for defining `theme.layerStyles` & `theme.textStyles` and how to consume those styles using the `textStyle` and `layerStyle` props available on all Chakra-created components.

# Code Notes

All components created by the Chakra system have the `textStyle` and `layerStyle` props built in:

https://github.com/chakra-ui/chakra-ui/blob/bd26cffb9da3ec4569a101b12abd6d28f3f37223/packages/system/src/system.types.ts#L36-L43

These props are used to read the corresponding values from `theme` as part of `extraProps`:

https://github.com/chakra-ui/chakra-ui/blob/bd26cffb9da3ec4569a101b12abd6d28f3f37223/packages/system/src/system.utils.ts#L118-L127

`extraProps` is used as part of `styled` to define component props and behavior:

https://github.com/chakra-ui/chakra-ui/blob/f2fe9553373da4734712a90fec284eea7a951dfb/packages/system/src/system.ts#L48-L48

**Comment by segunadebayo** [comment]
Done!
