### ISSUE TITLE
[<Button/>] Button

### ISSUE THREAD

**Issue by aoamusat** [chakra-ui/chakra-ui#1334]
**Describe the bug** 
Unable to render the `<Button></Button>` component. Giving `TypeError: right-hand side of 'in' should be an object, got undefined`

![image](https://user-images.githubusercontent.com/19868515/88055348-c02caa00-cb56-11ea-9ae1-a0f0aa48cba7.png)

![image](https://user-images.githubusercontent.com/19868515/88053314-8017f800-cb53-11ea-9591-ccee351b4d31.png)

**Expected Behavior** 
A nice simple button should be rendered in the browser.

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome, Firefox
- Version 78, 77

**Comment by damnjan** [comment]
Since there is no link to the code sandbox, I can only guess that you didn't wrap your app with `<ThemeProvider>`.

**Comment by segunadebayo** [comment]
Hey @aoamusat,

This is a common issue and it's because you didn't wrap your `App.js` in `ThemeProvider` from Chakra. Just like @damnjan mentioned.

Kindly do so and let us know if you still run into this issue, I'll re-open it back.

Cheers.

**Comment by aoamusat** [comment]
My bad, I forgot to wrap App.js in `<ThemeProvider></ThemeProvider>`. Thanks
