### ISSUE TITLE
[styled-system] - the @types/styled-system__core dependency is causing failure when checking licenses.

### ISSUE THREAD

**Issue by nicolad** [chakra-ui/chakra-ui#1335]
We are using `js-green-licenses` to check licenses of packages that are being imported and it is triggering an error related to `@types/styled-system__core dependency` from [here](https://github.com/chakra-ui/chakra-ui/blob/master/packages/styled-system/package.json#L53)

Here is an actual screenshot of the error:

![image](https://user-images.githubusercontent.com/1477453/88058898-c75eb280-cb6c-11ea-8e8d-79a0737d4c24.png)

and here is the failing [build](https://travis-ci.com/github/eventespresso/event-espresso-core/jobs/363020907)

***
will [that alias](https://github.com/chakra-ui/chakra-ui/blob/master/packages/styled-system/package.json#L53) be removed or updated on `@chakra-ui/styled-system` ?

**Comment by segunadebayo** [comment]
Hey @nicolad,

Thanks for reporting this. I've just resolved this by moving the types directly into our codebase.

We'll publish an update shortly.
