### ISSUE TITLE
[Typescript] Many TS errors when trying to build

### ISSUE THREAD

**Issue by nahtnam** [chakra-ui/chakra-ui#1342]
**Describe the bug** A clear and concise description of what the bug is.

I am using `preact-cli@3` with `@chakra-ui/core@next.6`. I am getting the following errors when I run the server

```
Could not find a declaration file for module '@styled-system/core'. xxxxxxx/node_modules/@styled-system/core/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/styled-system__core` if it exists or add a new declaration (.d.ts) file containing `declare module '@styled-system/core';`
```

```
TS7016: Could not find a declaration file for module 'lodash.merge'. xxxxxxx/node_modules/lodash.merge/index.js' implicitly has an 'any' type.
  Try `npm install @types/lodash.merge` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash.merge';`
```

and also many similar to these

```
ERROR in ./node_modules/@chakra-ui/alert/dist/types/alert.d.ts(5,65):
TS2344: Type '"string" | "ideographic" | "alphabetic" | "hanging" | "mathematical" | "target" | "type" | "x" | "y" | "key" | "height" | "width" | "path" | "children" | "end" | "local" | "color" | ... 454 more ... | "sx"' does not satisfy the constraint '"string" | "ideographic" | "alphabetic" | "hanging" | "mathematical" | "target" | "type" | "x" | "y" | "key" | "height" | "width" | "path" | "children" | "ref" | "end" | "local" | ... 454 more ... | "sx"'.
  Type '"__css"' is not assignable to type '"string" | "ideographic" | "alphabetic" | "hanging" | "mathematical" | "target" | "type" | "x" | "y" | "key" | "height" | "width" | "path" | "children" | "ref" | "end" | "local" | ... 454 more ... | "sx"'.
```

**Expected Behavior** A clear and concise description of what you expected to
happen.

No errors

**Link to minimal reproduction** Please provide a codesandbox link or GitHub
repo with a minimal reproduction of the issue.

https://github.com/nahtnam/chakra-ts-bug

**Steps to Reproduce** Clear and concise reproduction instructions are important
for us to be able to triage your issue in a timely manner.

1. Clone
2. `npm install`
3. `npm run dev` or `npm run build` (you may need to scroll up if you are doing `npm run dev` to see the errors)

**Suggested solution(s)**

I'm not sure to be honest. I don't think it's a Preact issue but I'm not entirely sure. I was not having an errors in 0.8.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS 11 beta
- Browser [e.g. chrome, safari] terminal
- Version [e.g. 22] n/a

**Additional context** Add any other context about the problem here, or some
background information of how you ran into this bug.

N/A

**Comment by nahtnam** [comment]
If you get an error about `.LICENSE.txt` duplicate when building, you can ignore that. There is a workaround for that and its not Chakra related. If you get to that error then that means the build was successful

**Comment by ljosberinn** [comment]
Looked into this; the missing types seem to stem from `npm install` not installing the dependencies of `chakra/styled-system` [here](https://github.com/chakra-ui/chakra-ui/blob/master/packages/styled-system/package.json#L53) which is odd. We can probably use the [ `@types/styled-system__core` repo](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/styled-system__core) instead anyways (see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36716 for context).

Apparently the types are removed entirely in the develop branch currently, so it might be resolved with the next release next week, v8. :)

The Alert errors seems to persist however (its unrelated to styled-system anyways):
![image](https://user-images.githubusercontent.com/29307652/88332257-8a421e00-cd2e-11ea-8c43-c0f5085b9da3.png)

**Comment by segunadebayo** [comment]
I looked into this as well, I've resolved the type issues with styled-system core and lodash.merge.

Will release an update shortly.

**Comment by segunadebayo** [comment]
I've released an update. Please try and let us know if this issue is gone.

Otherwise, we'll re-open it.

Cheers
