### ISSUE TITLE
Any plans to include table component ? 

### ISSUE THREAD

**Issue by ngprnk** [chakra-ui/chakra-ui#135]
if any,  Is it going to be implemented from scratch or wrapper around something like `react-table`
[react-table](https://github.com/tannerlinsley/react-table/blob/master/docs/examples.md)

**Comment by ngprnk** [comment]
I can PR  on the first option.

**Comment by segunadebayo** [comment]
Go for it @ngprnk. Can't wait to see it.

**Comment by Vynlar** [comment]
One problem I often have with tables is responsiveness. How do you folks think that problem is best solved?

It's often difficult to squeeze in a lot of columns on a mobile screen, so it would be nice if there were tools to help manage that issue. We could consider:

- Specify hiding certain columns on mobile
- Toggle to allow horizontal scrolling
- Custom renderer for mobile table rows

**Comment by segunadebayo** [comment]
That's a good point, @Vynlar. I'll give it some thought and see how best we can make the tables responsive.

I think providing a prop to hide certain columns on mobile makes sense. We can also support horizontal scrolling. For custom renderer, we might want to leave that to the user to figure it out.

@ngprnk, what are your thoughts?

**Comment by ngprnk** [comment]
Toggle to allow horizontal scrolling and prop to hide certain columns for sounds good to me.

**Comment by aaronmcadam** [comment]
Here are some nice ideas for table designs (from https://twitter.com/steveschoger/status/1167479729282310145):

![EDO4nm_XkAAPe-a](https://user-images.githubusercontent.com/37928/66142384-39293800-e5fd-11e9-8dc4-f92ee7fcf73a.jpeg)

**Comment by SanvirSovTech** [comment]
It would be cool if it made use of the new, headless react-table v7 as well.

**Comment by jeanverster** [comment]
Hi everyone, I have recently implemented a basic table using `react-table` v7 new headless API with chakra. Would be happy to make a PR if anyone would be interested in checking it out? 

It's pretty simple, usage would be as follows:

`<Table columns={columns} data={data} />`

And it looks like this:

<img width="1921" alt="Screenshot 2019-10-08 at 10 06 27" src="https://user-images.githubusercontent.com/17738943/66407551-aec24900-e9ed-11e9-910c-a98c86a6fd9d.png">

Out the box it has client side sorting by column headers, single page navigation, updating number of rows visible, page count & navigating to the first / last page. In terms of responsiveness it adops the `overflow-x` approach so the user can scroll the table content.

Lemme know what you think!

**Comment by felippepuhle** [comment]
IMO creating a wrapper for `react-table` isn't a good idea. I think it should handle styling/UI only.

Personally, I'd prefer to keep my project as clean as possible, and I wouldn't like to add `react-table` as a dependency if I wanted to use a simple table.

If someone want to use with `react-table` they'll be able to use it anyway, using `useTable`. It'll be better for composing purpose.

**Comment by felippepuhle** [comment]
BTW, in terms of responsiveness hiding some columns is a good idea.

I used to turn columns into rows too.

Thanks!

**Comment by franky47** [comment]
I agree with @felippepuhle https://github.com/chakra-ui/chakra-ui/issues/135#issuecomment-550288765.

Chakra is great at providing base UI components: in a table context, this could be pre-styled (overridable as usual) Header and Row components, but should probably not include behaviour, as it's where use-cases will vary immensely from simple data presentation to full interactivity.

As the author of `react-table` states:
> By removing the massive (and seemingly endless) API surface area required to support every UI use-case, React Table can remain small, easy-to-use and simple to update/maintain.

Are there any recommandations for accessibility when working with tables ?

**Comment by felippepuhle** [comment]
@franky47 I've made this a few weeks ago: https://github.com/felippepuhle/chakra-admin/blob/master/src/routes/Users/UsersList/UsersList.tsx#L39

Not perfect but it's working for now (I couldn't take the time to improve it yet), feel free to use/improve and send some PRs if you want.

Probably soon I'll work a bit more on this project (chakra-ui dashboard admin)

Thanks!

**Comment by timkindberg** [comment]
Agree, Chakra could make base styles and show examples of how it works with no library and how it works with a library like react-table v7.

**Comment by dusty** [comment]
Here is another basic one that I used as the base for a data table.  Feel free to do whatever with it.

https://codesandbox.io/s/relaxed-shape-ybulz

**Comment by nejcr** [comment]
@jeanverster do you have an example maybe?

**Comment by jeanverster** [comment]
Hi @nejcr, see code sandbox below with a basic example 👍 

https://codesandbox.io/s/chakra-ui-react-table-o6psn

**Comment by lishine** [comment]
What is going on folks? 🌞

**Comment by elisherer** [comment]
I made a lighter version with row click (using react-table)
https://codesandbox.io/s/chakra-ui-react-table-light-6ikg9

**Comment by aaronmcadam** [comment]
Great work @elisherer! This is a really useful reference implementation

**Comment by lishine** [comment]
Do you find react-table typescript support good enough currently?

**Comment by ms-mousa** [comment]
Hi Guys,
Is there any update on this? is it coming soon? I someone working on it? Can I help? 
Using Chakra for a project at work and I need a table! 😄

**Comment by aaronmcadam** [comment]
@ms-mousa The main focus of the team is on the v1 release. Feel free to raise a PR with an example implementation. It won't go to waste! 😄

**Comment by aaronmcadam** [comment]
Hi all, here's my table implementation: https://codesandbox.io/s/upbeat-christian-3hbgp?file=/src/index.tsx. 

Note that it doesn't try to do anything fancy with data, it is mainly about the table styles.

**Comment by skolhustick** [comment]
Can't wait for the Table component! 🙏

**Comment by esteban-url** [comment]
Hey folks, I stumbled into this issue yesterday while looking for something that would help me, the links provided by others are great, but i was looking for the simplest cases in simple js, so I made three very basic examples forked from the `react-query` codesandbox, they are using `@chakra-ui/core@1.0.0-next.6` but the API should be very similar.

Hope this helps someone. 🙂

Simple: https://codesandbox.io/s/simple--react-table--chakra-ui-3sem5
Footers: https://codesandbox.io/s/footers--react-table--chakra-ui-5x58q
Sorting: https://codesandbox.io/s/sorting--react-table--chakra-ui-h1qx9

**Comment by with-heart** [comment]
Thank you all for the feedback and ideas! 

Having a set of components for building tables would definitely be cool to have, but tables are also complex and come with a lot of edge cases to deal with (especially when it comes to dealing with responsiveness). 

with this. There's clearly a desire in the community to have this feature. Hopefully as we get through v1 and have more time to consider new ideas, we can figure out a direction to proceed.

**Comment by cr101** [comment]
Has anyone implemented a data table  component similar to the [Material Table](https://github.com/mbrn/material-table)?

**Comment by with-heart** [comment]
Happy to announce that basic table support is now part of our current focus!

**Comment by aaronmcadam** [comment]
@with-heart That's great news! I'd be happy to explain my implementation (codesandbox.io/s/upbeat-christian-3hbgp?file=/src/index.tsx )and some thoughts I had.

**Comment by tafelito** [comment]
Finally after some time I was able to put an example of the Table component I'm implemented while ago using @jeanverster as an inspiration. It uses `react-table` **v7**. And even though it uses `chakra-ui` **v0.8** it shouldn't take long to upgrade to **v1**, I'll probably do it soon. 
These are some of the futures it has and is very customizable

- Pagination
- Add/Remove/Edit/Clone
- Inline Add/Edit
- Search
- Select Rows
- Multiple loading states (full loading, partial loading)
- Filters
- Multiple data types
- Columns alignment 
- Mostly Typed
- Sorting (soon)
- Dark theme (soon)

Since chakra is divided in packages now, maybe it'd be a good idea to have 2 table components, 1 basic that includes only styling and a 2 one more complete using react-table since RT it's one of the best libraries to manage tables out there IMO specially with the new v8 coming soon (hopefully)fully typed  
I'd be more than happy to help if there is any interest in using this

https://codesandbox.io/s/chakra-ui-react-table-nextjs-forked-lxvru?file=/src/pages/index.tsx

It took some effort to do it but since chakra gives us so much I' happy to share it!

**Comment by with-heart** [comment]
@tafelito Very cool! That's a serious amount of effort to make something like that work and function well. Looks really nice!

> 2 one more complete using react-table since RT it's one of the best libraries to manage tables out there IMO specially with the new v8 coming soon (hopefully)fully typed

Really love this idea. I have something in mind that I'm going to try to start soon for managing official community-supported third-party integrations like this. I'll hopefully have more details soon!

**Comment by tafelito** [comment]
@with-heart thank you! can't wait to hear what you have planned. Happy to help if needed

**Comment by with-heart** [comment]
@tafelito Would love to have you involved! `react-table` is quite a beast so it'd be great to rely on your expertise. I'll let you know once we get something started with the third-party integrations idea.

Also are you on [our Discord server](https://discord.gg/dQHfcWF)? Lots of discussion happens on there, if you aren't and want in.

**Comment by tafelito** [comment]
Absolutely! And yes I'm there so feel free to ping me whenever you need
