### ISSUE TITLE
[Progressbar] Doesn't show when used

### ISSUE THREAD

**Issue by jaeyholic** [chakra-ui/chakra-ui#1353]
I have imported and used the Progressbar but it doesn't show on the page. version 0.8.0

**Comment by with-heart** [comment]
Hi @jaeyholic, could you please create a CodeSandbox reproduction for us? That will help us better serve you.

**Comment by segunadebayo** [comment]
@with-heart Kindly re-open once @jaeyholic sends a Codesandbox reproduction.

Thanks
