### ISSUE TITLE
[Input components] Make "onChange" consistent and add "onValue" callback

### ISSUE THREAD

**Issue by dodas** [chakra-ui/chakra-ui#1354]
Currently, Chakra's input components, such as `<Input />`, `<Select>` have a `onChange` callback that passes original `event` to the callback function. This is fine and consistent with native html inputs and React's input components.

Some other Chakra components, such as `<NumberInput />` and `<Slider />` have the equally named prop `onChange`, that, however, passes just the `value` to the callback.

To bring some consistency, it would be nice to have all Chakra input components pass the original `event` object to `onChange` callbacks, if possible. (I noticed that `<Slider />` is not implemented as native html `<input type="range" />`).

Then, to bring some convenience too, perhaps we could add an `onValue` for most input components, that would pass just the `value` to callbacks:
```ts
const [name, setName] = useState("");
return (
  <Input value={name} onValue={setName} />
);
```

instead of:
```ts
const [name, setName] = useState("");
return (
  <Input value={name} onChange={(ev) => setName(ev.target.value)} />
);
```
 
[> Related talk on Discord channel](https://discord.com/channels/660863154703695893/724006907634778132/735418752040173600)

I can help with implementation once we agree on the details.
Cheers.

**Comment by with-heart** [comment]
I think this change makes sense. The closer we can get to a consistent return value, the easier it is to document and for new users to become familiar with how our components work.

Anyone want to take the time to make a table of all the components with `value`/`onValue` and whether they're returning a value or an event?

**Comment by dodas** [comment]
I did a recap, hopefully it is clear enough.
Values marked with `value of interest` (sometimes it's not `target.value`) would be passed to `onValue` callbacks.

```tsx
// Parameter passed: event (GOOD)
// value of interest: ev.target.checked
<Checkbox onChange={(ev) => console.log(ev)} />
```
```tsx
// Parameter passed: event (GOOD) 
// value of interest: ev.target.value
<Input onChange={(ev) => console.log(ev)} />
```
```tsx
// Parameter passed: value (BAD) - should be event
// value of interest: ev.target.value
<NumberInput onChange={(ev) => console.log(ev)}>
  {/*
     Parameter passed: event (GOOD) 
     value of interest: ev.target.value

     Should we remove onChange on either NumberInput or NumberInputField?
  */}
  <NumberInputField onChange={(ev) => console.log(ev)} />
</NumberInput>
```
```tsx
// Parameter passed: value (GOOD)
// No native event equivalent - value of composed from children PinInputField's
<PinInput onChange={(ev) => console.log(ev)}>
  <HStack>
    {/*
      Parameter passed: event (GOOD) 
      value of interest: ev.target.value
    */}
    <PinInputField onChange={(ev) => console.log(ev)} />
    <PinInputField />
    <PinInputField />
  </HStack>
</PinInput>
```
```tsx
// Parameter passed: value (GOOD)
// No native event equivalent
<RadioGroup value={value} onChange={handle}>
  <Stack direction="row">
    {/*
      Radio is lacking onChange callback (BAD)
      Should pass event
    */}
    <Radio value="1">First</Radio>
    <Radio value="2">Second</Radio>
    <Radio value="3">Third</Radio>
  </Stack>
</RadioGroup>
```
```tsx
// Parameter passed: event (GOOD)
// value of interest: event.target.value
<Select onChange={(ev) => console.log(ev)}>
  <option value="option1">Option 1</option>
  <option value="option2">Option 2</option>
  <option value="option3">Option 3</option>
</Select>
```
```tsx
// Parameter passed: value (???)
// Slider is not implemented as native input, so probably OK
<Slider onChange={(ev) => console.log(ev)}>
  <SliderTrack>
    <SliderFilledTrack />
  </SliderTrack>
  <SliderThumb />
</Slider>
```
```tsx
// Parameter passed: event (GOOD)
// value of interest: event.target.checked
<Switch onChange={(ev) => console.log(ev)} />
```
```tsx
// Parameter passed: event (GOOD)
// value of interest: event.target.value
<Textarea onChange={(ev) => console.log(ev)} />
```

**Comment by segunadebayo** [comment]
I see where this is going but I consider it a serious breaking change.

The thing to note when input components are that most users integrate them with form libraries such as Formik, React Final Form, or Hook Form. Formik for example manages the form element's onChange and expects it to be the `event`.

For custom-built components like NumberInput, it's a bit tricky because the onChange can be fired by both changing the input's value and clicking the spinner buttons.

We can look into this in the future, for now, let's keep this as an idea worth thinking about.

**Comment by segunadebayo** [comment]
Permit me to close this for now. I don't think we'll move forward with this idea.
