### ISSUE TITLE
[MenuButton] Clicks on button icons are ignored when used with as={Button}

### ISSUE THREAD

**Issue by dmitru** [chakra-ui/chakra-ui#1355]
**Describe the bug**

Menu does not open when user clicks on icons inside the MenuButton rendered with `as={Button}` prop (to support icons).

**Expected Behavior**

Menu should open when user clicks on icons inside the MenuButton.

**Link to minimal reproduction** 

Sandbox: https://codesandbox.io/s/blissful-mayer-g8vmu-vfcvx?file=/src/App.js

**Steps to Reproduce** 

In the sandbox, click on the chevron left icon or the right 'custom icon'. One would expect the menu to open, but it won't

**Desktop (please complete the following information):**

Chrome, OSX

**Comment by segunadebayo** [comment]
Thanks for reporting this @dmitru.

I've just resolved this and will publish an update tomorrow.
