### ISSUE TITLE
Box component overflow property not recognised

### ISSUE THREAD

**Issue by hendrikniemann** [chakra-ui/chakra-ui#136]
The Box component takes the `overflow` property in [one of the examples](https://chakra-ui.com/box#usage-1) but using it gives me an error when attempting to use it in TypeScript. `overflowX` and `overflowY` are recognised. A workaround is to use both of the properties to achieve the behaviour of the `overflow` property.

I could create a simple PR that adds the property to the `index.d.ts` file:

```diff
  textTransform?: StyledSystem.ResponsiveValue<CSS["textTransform"]>;
+ overflow?: StyledSystem.ResponsiveValue<CSS["overflow"]>;
  overflowX?: StyledSystem.ResponsiveValue<CSS["overflowX"]>;
  overflowY?: StyledSystem.ResponsiveValue<CSS["overflowY"]>;
  appearance?: StyledSystem.ResponsiveValue<CSS["appearance"]>;
```

Let me know what you think. Thanks for the awesome UI library I am really in love with it 😍

**Comment by segunadebayo** [comment]
Hi @hendrikniemann,

I'm glad you love Chakra UI. The `overflow` type def is already included in the `@types/styled-system` but I didn't include it. If it wasn't included, then your suggestion would be perfect!

I've now added it to the Box types and will release a patch soon.

**Comment by segunadebayo** [comment]
I've released a patch that resolves this.
