### ISSUE TITLE
Some components reporting "missing the following properties" error

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1369]
This has been reported on Discord for both `Alert` and `NumberInput`. 

Reproduction: https://codesandbox.io/s/naughty-tdd-lnmd9?file=/src/App.tsx

This may have been resolved already but we haven't published `next.7` yet so unable to test. Opening this as a tracking issue so we can verify this has been fixed.

**Comment by ljosberinn** [comment]
On `next.7`, the sandbox still errors using `Alert` in runtime, but also prior because of `(0 , $csb__system.useThemeDefaultProps) is not a function`.
On `rc.0`, it doesn't crash anymore but it can't find the typings: https://codesandbox.io/s/mystifying-galileo-nori5?file=/src/App.tsx

**Comment by nahtnam** [comment]
Still seeing errors like these on 1.0.0rc0

```
ERROR in xxx/chakra-ts-bug/node_modules/@chakra-ui/styled-system/dist/types/config/background.d.ts(1,22):
TS6053: File 'xxx/chakra-ts-bug/node_modules/@chakra-ui/styled-system/src/types.d.ts' not found.
ERROR in xxx/chakra-ts-bug/node_modules/@chakra-ui/styled-system/dist/types/config/background.d.ts(78,41):
TS7016: Could not find a declaration file for module '@styled-system/core'. 'xxx/chakra-ts-bug/node_modules/@styled-system/core/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/styled-system__core` if it exists or add a new declaration (.d.ts) file containing `declare module '@styled-system/core';`
```

Repo https://github.com/nahtnam/chakra-ts-bug

**Comment by ljosberinn** [comment]
Installing https://www.npmjs.com/package/@types/styled-system__core would solve this, we talked about this on Discord. Curious though why it only errors for you, I just checked and don't have the types through some other package in my repo.

**Comment by nahtnam** [comment]
Hmm running that command on my repo still gives the following error:
```
ERROR in xxx/chakra-ts-bug/node_modules/@chakra-ui/styled-system/dist/types/config/background.d.ts(1,22):
TS6053: File 'xxx/chakra-ts-bug/node_modules/@chakra-ui/styled-system/src/types.d.ts' not found.
```

Curious as to why `@types/styled-system__core` isn't installed by default

**Comment by segunadebayo** [comment]
I looked into this issue and it was related to the fact that the custom type definitions for `styled-system/core` didn't make it to the build.

I've resolved this issue and it'll be out in the next pre-release.

Thank you.
