### ISSUE TITLE
Question: Why don't use 'required' attribute for Input component?

### ISSUE THREAD

**Issue by scon-io** [chakra-ui/chakra-ui#1375]
`aria-required` is still useful for user agents that do not yet support HTML5, but `required` is handled natively on most of browsers.

**Comment by with-heart** [comment]
Hi @scon-io! Which version of Chakra are you using?

**Comment by scon-io** [comment]
@with-heart I'm using 1.0.0-next.4 :)

**Comment by trevorblades** [comment]
I was also wondering this. In v0, when you pass `isRequired` to an `Input`, you get the native browser `required` attribute as well: https://github.com/chakra-ui/chakra-ui/blob/v0/packages/chakra-ui/src/Input/index.js#L37

I would expect the same to be true in v1. The [`isDisabled` prop directly translates to the `disabled` attribute](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/form-control/src/use-form-control.ts#L43), so I'm surprised the same convention isn't used for `required`. Right now, we have to write required inputs like this:

```jsx
<Input
  isRequired
  required
  {...otherProps}
/>
```

The solution for this seems pretty simple, and I've put together a PR that addresses this here: https://github.com/chakra-ui/chakra-ui/pull/1400

**Comment by segunadebayo** [comment]
Thank you for catching this @scon-io.

I've pushed a fix for this.
