### ISSUE TITLE
Incompatible with Yarn 2 (easy fix)

### ISSUE THREAD

**Issue by mariusmarais** [chakra-ui/chakra-ui#1378]
We've just completed a migration to Yarn 2, and now want to integrate Chakra-UI into our project.

However, `@chakra-ui/core@1.0.0-next.6` is incompatible with Yarn 2.

A separate bug has been logged with Yarn at https://github.com/yarnpkg/berry/issues/1621, but Chakra-UI is definitely doing something weird, so I think it's appropriate to remedy here as well.

This is due to `@chakra-ui/styled-system` dependency on `@types/styled-system__core`, which is defined as:
```json
  "dependencies": {
    "@types/styled-system__core": "npm:@peduarte/styled-system__core",
  },
```

**Reproduction**
In a minimal Yarn 2 project, add `@chakra-ui/core@1.0.0-next.6`

<details>
  <summary>Step by step (click to expand)</summary>

```sh
/tmp ❯❯❯ mkdir y2
/tmp ❯❯❯ cd y2
/t/y2 ❯❯❯ yarn init -2
yarn init v1.22.4
Resolving berry to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
Saving it into /private/tmp/y2/.yarn/releases/yarn-berry.js...
Updating /private/tmp/y2/.yarnrc.yml...
Done!
{
  name: 'y2'
}
✨  Done in 4.54s.
/t/y2 ❯❯❯ yarn --version; node --version
2.1.1
v12.18.2

/t/y2 ❯❯❯ yarn add @chakra-ui/core@1.0.0-next.6
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @types/styled-system__core@npm:@peduarte/styled-system__core isn't supported by any available resolver
    at i.getResolverByDescriptor (/private/tmp/y2/.yarn/releases/yarn-berry.js:2:266590)
    at i.bindDescriptor (/private/tmp/y2/.yarn/releases/yarn-berry.js:2:266044)
    at /private/tmp/y2/.yarn/releases/yarn-berry.js:2:288133
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 18)
    at async ne.resolveEverything (/private/tmp/y2/.yarn/releases/yarn-berry.js:2:287456)
    at async /private/tmp/y2/.yarn/releases/yarn-berry.js:2:304371
    at async f.startTimerPromise (/private/tmp/y2/.yarn/releases/yarn-berry.js:2:313773)
    at async ne.install (/private/tmp/y2/.yarn/releases/yarn-berry.js:2:304005)
➤ YN0000: └ Completed in 11.41s
➤ YN0000: Failed with errors in 11.42s
```
</details>

**Resolution**

***Option 1 (easiest)***
Add a range to the package, such as `@*`:

```json
  "dependencies": {
    "@types/styled-system__core": "npm:@peduarte/styled-system__core@*",
  },
```

***Option 2***
Complete a pull request to `@types/styled-system__core` with the required changes instead of hijacking the package name.

***Option 3***
Depend directly on `@peduarte/styled-system__core` instead of on `@types/styled-system__core` if that is the intention.

**Desktop (please complete the following information):**

- OS: macOS 10.15.5
- Node: 12.18.2
- Yarn: 2.1.1

**Comment by with-heart** [comment]
This dependency was removed in fc8b8d8. Should have the next version published this weekend!
