### ISSUE TITLE
Need Menu open on hover 

### ISSUE THREAD

**Issue by gagandeep7** [chakra-ui/chakra-ui#1380]
I am using menu item and it is expandable using click but I want it to expand on hover .I am not able found any way to it . 
I have tried updating isOpen render prop to true onMouseEnter event but still nothing happens

**Comment by dodas** [comment]
Yes, `Popover` has configurable `trigger` property (hover, click), but `Menu` does not.
It would be certainly useful to have it for `Menu` as well.

**Comment by segunadebayo** [comment]
Hi @gagandeep7, what's the use case for a menu to open on hover?

I think it's not a common pattern and even the WAI-ARIA guideline for menus doesn't recommend open a menu on hover so I'm curious. When any element opens on hover, it's considered a tooltip or just a regular "nav" without much a11y involved.

This is why I'm curious to know why?

**Comment by gagandeep7** [comment]
Hi @segunadebayo , It was client request that it should open on hover but thanks for the response . I have conveyed the same to client that it is not recommended to open menu on hover . So I am closing this issue .

**Comment by stellarhoof** [comment]
@segunadebayo My usecase is an app menu navbar. I could not find any wai-aria recommendation to not use hover on menus (do you have a link?). I did find this https://www.w3.org/WAI/tutorials/menus/flyout/, which looks exactly like what I need and it also looks like a list of menu buttons.

**Comment by leosolid** [comment]
It is a common pattern for submenu items at least
![image](https://user-images.githubusercontent.com/13348080/123155332-d43ef280-d41c-11eb-91c9-85cf50d06d17.png)
