### ISSUE TITLE
Thoughts on "Container" semantics

### ISSUE THREAD

**Issue by timkindberg** [chakra-ui/chakra-ui#1386]
A couple of way-too-late thoughts on V1...

The Container I am worried about it's name and intention. Can we rename to indicate it is used for Typography? It is not, IMO, a layout concern but a typographical concern. Some name ideas Measure, Paragraph.

Conversely, a Container has typically been used as a way to limit the maxWidth at each breakpoint so that you have a responsive "container" that is NOT fluid. Here is our local implementation, it's full width on "mobile" breakpoints and then fits nicely into any breakpoints above those:

```
export const Container = ({ children, ...props }) => {
  const theme = useTheme()

  return (
    <Box {...props} mx="auto" w={['full', 'full', ...theme.breakpoints.slice(1)]}>
      {children}
    </Box>
  )
}
```

Lastly, I don't think it would be bad to move all typographical components into their own documentation group: Text, Heading, Link, Code, List.

**Comment by segunadebayo** [comment]
Thanks for sharing your thoughts @timkindberg. It's not way too late 😃.

We'll think on these and effect some changes shortly

**Comment by segunadebayo** [comment]
We've updated the grouping for the typography components just like you suggested.

Thank you

**Comment by brianivander** [comment]
Hi @timkindberg @segunadebayo I am using `"@chakra-ui/react": "^1.7.3",` and I am using Container mainly because this will be a web app instead of a desktop app. When on desktop, I love that it limits the left and right margin/padding. But on mobile, I wish it to be full screen. I think that's the purpose of Container no?  


![image](https://user-images.githubusercontent.com/19526473/147864867-dfcd4dfc-18cb-4a01-80e7-f3b52cadf359.png)

**Comment by primos63** [comment]
> ...because this will be a web app instead of a desktop app.
I think you mean you are targeting this only for mobile? A web app runs in a browser which can run on a mobile, tablet and desktop.

If you wish to have the container be the full width for mobile then you could use responsive styles for it
```jsx
<Container maxWidth={{ base: 'full', lg: 'container.sm' }}>
</Container>
```
So for mobile and tablet it's full width and desktop (62em and up) it would have a max width of 640px.
If you're only target is mobile, then you can just set the `maxWidth` to 'full'. By default it has `padding-inline` of 1rem. So if you don't want any padding, then supply the `Container` with `px={0}`.

Mobile only: `<Container maxWidth='full' px={0}>...</Container>`

See the docs about [Responsive Styles](https://chakra-ui.com/docs/features/responsive-styles)
