### ISSUE TITLE
Request to add [ColorModeToogle] to the stories

### ISSUE THREAD

**Issue by leoalves** [chakra-ui/chakra-ui#1389]
I was fixing an issue with the Select component in Dark mode.  To better understand and fix the issue I added the color mode switcher (same as the website) to the Select component Storybook story.

I think it will be useful to have this in all  stories.  I can create the PR, but I am not sure if you guys want this and also where to put the component.

It will have to be imported into each story.  I tried to add into the `addDecorator` function in the `preview.tsx`, inside the `.storybook` folder, but I couldn't make it work.  Not sure why, I don't have a lot of experience with Storybook, but the hook was added before the provider and the story would never get updated with the values from the ColorModeProvider.

My question is.  Where should I put the component.  Just create a new one like any other component?  Or add as an additional export to an existing component?

The code for the component would be something like this:

```javascript
<React.Fragment>
  <Flex justify="flex-end">
    <IconButton
      size="md"
      fontSize="lg"
      aria-label={`Switch to ${text} mode`}
      variant="ghost"
      color="current"
      marginLeft="2"
      onClick={toggleColorMode}
      icon={<SwitchIcon />}
    />
  </Flex>
  {children}
</React.Fragment>
```

And in each Story

```javascript
<ColorModeToggleBar>
  <Container maxWidth="400px" mt="40px">
    {story()}
  </Container>
</ColorModeToggleBar>;
```

Here is a gif of what I am talking about:

![featReq](https://user-images.githubusercontent.com/3867140/88435836-1278ff80-cdd1-11ea-8953-71dbe03a472d.gif)

**Comment by with-heart** [comment]
Hi @leoalves, in the process of playing around with your idea and figuring out how to make it work with Storybook, I ended up implementing it and opened #1396 for it. Wanna take a look and let me know if that addresses the issue?

**Comment by leoalves** [comment]
Cool. Thanks.  That's exactly what I was looking for.
I tried doing it how you did it but I couldn't make it work, not sure why. 
I don't think that changes but I was also working on the wrong branch.
Thanks
