### ISSUE TITLE
TypeScript: Property 'borderTopWidth' does not exist on type for Box

### ISSUE THREAD

**Issue by aaronmcadam** [chakra-ui/chakra-ui#139]
CodeSandbox: https://codesandbox.io/s/chakra-ts-starter-20ydv

I've just hit this working on a new project using TypeScript.

I like to use this property in order to depend on the border rules added by `<CSSReset>`.

**Comment by segunadebayo** [comment]
I'll add the border-width props for all sides (left, right, bottom, left) to the Box component. 

In the meantime, you can do `borderTop="1px solid"` and `borderColor="inherit"`

**Comment by aaronmcadam** [comment]
Ah, nice, thanks for the workaround @segunadebayo!

**Comment by segunadebayo** [comment]
I've released a patch for this.

**Comment by aaronmcadam** [comment]
Thanks!
