### ISSUE TITLE
Request to add a type for common style props

### ISSUE THREAD

**Issue by malerba118** [chakra-ui/chakra-ui#1390]
**What problem does this feature solve?** A clear and concise description of the
feature, the problem it solves and solution you propose.

I'm brainstorming on ways to compose style fragments and would like to create groups of styles for common style props that i can compose and spread onto components.

Something like this is what i'm going for:
```ts
const overlay: Partial<CommonStyleProps> = {
  position: "absolute",
  top: 0,
  right: 0,
  bottom: 0,
  left: 0
};
```

However, I'm having trouble figuring out what to use for the CommonStyleProps type.

**What does the proposed API look like?** Describe how you propose to solve the
problem and provide code samples of how the API would work once implemented.

It'd be nice if chakra-ui exported a CommonStyleProps type that contained all styles that can be applied to any component.

**Describe alternatives you've considered** List any alternative solutions
you've considered.

I've tried doing 
```tsx
type CommonStyleProps = BoxProps
```
and 
```tsx
type CommonStyleProps = BoxProps & FlexProps & StackProps & GridProps & HeadingProps & ...
```
but neither is exactly correct or what i'm looking for.

**Additional context** Add any other context or screenshots about the feature
request here.

Here's a codesandbox i'm playing around in https://codesandbox.io/s/admiring-leftpad-599yx?file=/src/index.tsx

**Comment by with-heart** [comment]
Unfortunately for `0.8.0`, we don't have a good option for you. We use `styled-system` to assemble our components and if you check out `@types/styled-system@5.1.9`, you can see all of the type definitions for the various props, but it's in the same boat as Chakra, where there is no type that represents all of the types as a whole.

In `1.0.0`, `@chakra-ui/styled-system` exports the `SystemProps` interface that extends all base props as well as all of the pseudo props. Hope that helps!

PS: In `1.0.0`, we have an as-of-yet-undocumented feature for `theme.layerStyles` which allows you to do something very similar to what you're doing here.

Define the object in your `theme`:
```tsx
const theme = {
  ...defaultTheme,
  layerStyles: {
    overlay: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
  },
}
```

Use it as a prop from any component:
```tsx
const Example = () => (
  <Box layerStyle="overlay">Welcome to Chakra + TS</Box>
)
```

It also has a sibling called `theme.textStyles` that works the same way but has a different name so you can differentiate between generic layers and what you intend to be text-specific.

**Comment by malerba118** [comment]
@with-heart thanks for the info! layoutStyles look about right, but will there be a way to compose multiple layout styles? I’ll keep digging around on styled-system as well. Thanks again!

**Comment by with-heart** [comment]
@malerba118 If you mean usage similar to your `useStyleGroups` fn that takes an array, there isn't a way to do that currently. `layerStyles` and `textStyles` only allow you to pass a single target. 

I think that idea could be too abstract for what we're trying to do with Chakra, but it's also possible I'm not seeing the big picture with this. If you keep playing with this concept and come up with solid use cases for composable styling that can't be solved using `layerStyles`/`textStyles` or the other pieces in our [new Component Theming system](https://next.chakra-ui.com/docs/theming/overview), please open an issue a new issue and share what you've come up with so we can explore further :)

**Comment by malerba118** [comment]
Oh cool, hadn’t even seen the v1 docs, but the theming api looks like it should do what I’m going for😁
