### ISSUE TITLE
[Wrap] 'Wrap' is not exported from '@chakra-ui/core'

### ISSUE THREAD

**Issue by rahadkc** [chakra-ui/chakra-ui#1391]
**Describe the bug** 

Trying to 'import' 'Wrap'  component from '@chakra-ui/core'. But getting this error - 
Attempted import error: 'Wrap' is not exported from '@chakra-ui/core'

![chakra-ui-wrap-import-error](https://user-images.githubusercontent.com/8745638/88438444-97443780-ce2a-11ea-864f-f093ea73f9b7.png)

**Expected Behavior** 

'Wrap' component should have exported from '@chakra-ui/core' and user should be able to 'import' form '@chakra-ui/core' as describe in 'Wrap' documentation. 

**Link to minimal reproduction** N/A.

**Steps to Reproduce** 

1. Import 'Wrap' in any React component. I'm using 'create-react-app'. 
`import { Wrap } from "@chakra-ui/core"`
2. Now try to use  `<Wrap>....</Wrap>`
3. Save changes

**Suggested solution(s)**

Same as expected behavior

**Desktop (please complete the following information):**

- OS: [Ubuntu 18.04]
- Browser [chrome]
- Version [81.0.4044.138 (Official Build)]

**Additional context** Add any other context about the problem here, or some
background information of how you ran into this bug.

**Comment by leoalves** [comment]
It's working for me.

Are you using the latest Chakra v1.0.0-next.6?
Also what version of Typescript are you using?  I had to update mine to 3.9.7.  The one that comes by default in the create-react-app does not work.

**Comment by rahadkc** [comment]
@leoalves I'm using @chakra-ui/core: ^0.8.0. I'm not using Typescript. By the way, this is my first ever try with Chakra UI. Am I missing something?

**Comment by with-heart** [comment]
Hi @rahadkc, you are missing something :)

We currently have two versions of Chakra. `0.8.0` will soon be deprecated in favor of `1.0.0`, which is currently in pre-release status. 

`Wrap` is from `1.0.0`.

You can find the docs for `0.8.0` at https://chakra-ui.com/ and the docs for `1.0.0` at https://next.chakra-ui.com/. Hope that helps!

**Comment by rahadkc** [comment]
@with-heart  thanks. I was confused. Thanks for your reply.
