### ISSUE TITLE
Attempted import error: 'copy' is not exported from '@chakra-ui/theme-tools'.

### ISSUE THREAD

**Issue by ganeshkrishnasharma** [chakra-ui/chakra-ui#1399]
```
./node_modules/@chakra-ui/theme/dist/esm/components/menu.js
Attempted import error: 'copy' is not exported from '@chakra-ui/theme-tools'.
```

I tried upgrading my chakra ui version to latest from version 0.8 using the upgrade documentation provided. But i am
getting this error when i start my project after upgrading to version "@chakra-ui/core": "^1.0.0-next.7",  "@chakra-ui/theme": "^1.0.0-next.3".

am i doing something wrong? or is there any version mismatch happening? or any other issue ? Any help is appreciated.

**Comment by segunadebayo** [comment]
Hi @ganeshkrishnasharma, Please update all packages to `v1.0.0-rc.0` and try again.

I'll re-open if the issue still persists.

Thanks

**Comment by akiarostami** [comment]
I just installed v1.0.0-rc.0 and I'm having the same issue

**Comment by with-heart** [comment]
`copy` was removed in f68623b
