### ISSUE TITLE
docs:dev not hot-reloading

### ISSUE THREAD

**Issue by cyan33** [chakra-ui/chakra-ui#14]
Running `yarn run docs:dev` correctly set up my localhost but seems like it's not hot reloaded? (According to the CONTRIBUTING guide it should.)
```
"docs:dev": "lerna run --scope=@chakra-ui/docs dev --stream",
```
It might be because of this and I feels like I've missed something that isn't mentioned in the docs.

![image](https://user-images.githubusercontent.com/13282699/64317633-2a535500-cf6d-11e9-9dfe-8414894c8b10.png)

Any pointer would be appreciated! :)

**Comment by segunadebayo** [comment]
I'll look into this. Not sure what the issue is but you can try the following
- Install all dependencies from the root using `yarn bootstrap`
- cd into `packages/chakra-ui-docs` and install dependencies as well
- Then run `yarn docs:dev` from the root

**Comment by segunadebayo** [comment]
You might want to upgrade your node version and try to install the dependencies again.
