### ISSUE TITLE
[API] Single Select Component

### ISSUE THREAD

**Issue by segunadebayo** [chakra-ui/chakra-ui#140]
Following our discussion in Issue #38. I thought to put down my thoughts about
the Single Select component and the API I have in mind.

NB: I know there are other use cases, like Multiple Selects and ComboBox, but
we're keeping it simple for now. We'll start with a Single Select Component

## The Goal:

Create a select component that works just like the native select and accessible,
composable and super easy to style.

The single select will follow WAI-ARIA specs for the list box pattern. These are the
key resources we need to create this Select

- https://ebay.gitbook.io/mindpatterns/input/listbox
- https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-scrollable.html
- https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html
- https://www.w3.org/TR/wai-aria-practices/#kbd_focus_vs_selection

## Key Features:

- Typeahead support: When the select is open and focus is on the select list box
  - Typing the first letter of an option sends focus to that option.
  - Type multiple characters in rapid succession: focus moves to the next item
    with a name that starts with the string of characters typed.
- Keyboard navigation:
  - Using the up and down arrow should navigate the options. Any option that's
    disabled should be skipped in the navigation.
  - The Home and End key should select the first and last option respectively.
- Scrolling into view: In the event, the options are quite many and we navigate
  via keyboard or typeahead, any option is focused that isn't (fully) visible
  should be scrolled into view. Perhaps `scroll-into-view-if-needed` might help.
- Auto select:
  - If `autoSelect` is true, highlighting an option must also select that option
  - If `autoSelect` is false, a highlighted option must be manually selected
    using the SPACEBAR or ENTER key.
- Virtualize Menu: If there's a large number of options, we might need to
  improve render performance by using `react-virtualized`

## Import

Component Parts:

- Select: The wrapper that provides the context and functionalities
- SelectControl: The element that triggers the list box. By default, it renders a
  `button` but can also use a render prop in case user needs full control of the rendering.
- SelectMenu: The wrapper for the popover. It composes the `Popper` component.
  It can also use a render prop incase user needs access to the interal state.
- SelectMenuList: The listbox that wraps the options. It provides the keyboard
  navigation and typeahead functions.
- SelectIndicator: The wrapper for the dropdown icon.
- SelectOption: Each option in the select.
- SelectOptionGroup: A wrapper for a set of options that can be labeled. Similar
  to the `<optgroup>` in the native browser select.

## Usage

```jsx
<Select>
  <SelectControl>
    <SelectLabel>Option 1</SelectLabel>
    <SelectIndicator>
      <Icon name="down-up-arrow" />
    </SelectIndicator>
  </SelectControl>
  <SelectMenu>
    <SelectMenuList>
      <SelectOption value="opt1">SelectOption 1</SelectOption>
      <SelectOption value="opt2">SelectOption 2</SelectOption>
      <SelectOption value="opt3">SelectOption 3</SelectOption>
    </SelectMenuList>
  </SelectMenu>
</Select>
```

The Select should also be able to render an option group. If passed
`isDisabled`, the options should also be disabled.

```jsx
<Select defaultIsOpen={true} defaultValue="css">
  <SelectControl>Select Option</SelectControl>
  <SelectMenu>
    <SelectMenuList>
      <SelectOption value="html">HTML</SelectOption>
      <SelectOption value="css">CSS</SelectOption>
      <SelectOptionGroup label="Frameworks" isDisabled>
        <SelectOption value="react">React</SelectOption>
        <SelectOption value="vue">Vue</SelectOption>
        <SelectOption value="angular">Angular</SelectOption>
      </SelectOptionGroup>
    </SelectMenuList>
  </SelectMenu>
</Select>
```

### Select Props (Provides Context)

- defaultIsOpen: If `true`, the select should be open initially.
- isOpen: If `true`, the select should be open in controlled mode.
- defaultHighlightedIndex: the index of the item that should be highlighted
  initially.
- autoSelect: If `true`, the option will be selected as you navigate through
  them.
- closeOnBlur: If `true`, the select menu will close on blur or outside click
- closeOnEsc: If `true`, the select menu will close when you press `escape`
- closeOnSelect: If `true`, the select menu will close when you select an
  option.
- defaultValue: The initial selected value
- value: The selected value
- onChange: Callback fired when an option is selected
- isDisabled: If `true` the select control will be disabled
- isInvalid: If `true`, the select control will have `aria-invalid` set to true
- isReadOnly: If `true`, the select will be in read-only mode
- children: the content of the select. It can also take a render prop that
  provides:
  - selectedItem
  - highlightedIndex
  - isOpen
  - onClose

### SelectOptionGroup Props (composes Box)

- isDisabled: If `true`, all the SelectOption that it wraps will be disabled
- label: The label for the option group

### SelectOption Props (composes PseudoBox)

- isSelected
- isHighlighted
- value
- children

**Comment by aaronmcadam** [comment]
My biggest concern with the Select component is whether it will be easy to test in unit tests with Jest and End to End tests with Cypress. `react-select`, as least in version 2, makes it very hard to choose items.

Here's an example:

```ts
/**
 * Create a Project
 */
cy.getByTestId("button-add-project").click();
cy.getByTestId("input-project-title").type("E2E Test Project");
cy.getByTestId("button-wizard-next").click();
cy.getByTestId("input-project-description").type(
  "E2E Test Project description"
);
cy.getByTestId("button-wizard-next").click();
cy.getByTestId("select-agency").click();
// Choose 'Testing Agency'
cy.get("#react-select-2-option-4").click();

/**
 * Clicking multiple times makes this test more resilient
 * @see https://github.com/cypress-io/cypress/issues/1486#issuecomment-450151465
 * @see https://github.com/cypress-io/cypress/pull/2982
 */
cy.getByTestId("select-client")
  .click()
  .click()
  .click();
// Choose 'Testing Client'
cy.get("#react-select-3-option-0").click();

cy.getByTestId("button-wizard-next").click();
cy.getByTestId("select-template")
  .eq(0)
  .click();
cy.getByTestId("button-wizard-complete").click();

```

**Comment by aaronmcadam** [comment]
Did we get anywhere with this component @segunadebayo. Did you find any components that might fit in with Chakra? I need to implement a single select in my current project so I'm just about to start researching. If I find anything good, I could post it here if that would help?

**Comment by segunadebayo** [comment]
Hi @aaronmcadam,

I've built a custom select already, it's in the `dev-ts` branch, but it needs some cleanup and type definition. It'll be in the next release.

However, if you find an implementation other than `react-select` or `downshift` please let me know.

**Comment by aaronmcadam** [comment]
Hi @segunadebayo, thanks for getting back to me. I ended up using an old component we had that uses `react-select`. It is an older 1.x version with the testing problems mentioned above. I don't know if `react-select` v2 produces more semantic markup or is less flaky in tests.

That's great news that you've got something working in the TypeScript branch. I'd like to give you a hand with some of the work when I get a chance.

**Comment by aaronmcadam** [comment]
I did have a look at [Reach UI's Combobox](https://reacttraining.com/reach-ui/combobox), and while it's a great example of how to build an accessible and testable component, it didn't fit my simple needs and the needs of this RFC.

**Comment by segunadebayo** [comment]
I'm curious @aaronmcadam. What do you mean by "simple needs"? Just to be sure what I've worked on covers this 😄

**Comment by aaronmcadam** [comment]
> I'm curious @aaronmcadam. What do you mean by "simple needs"? Just to be sure what I've worked on covers this

The same needs as mentioned above: just a select component that allows you choose from a list of options. The combobox is more of an extended text input, in that you can choose an option or type your own value. Does that make sense?

**Comment by aaronmcadam** [comment]
@segunadebayo I do need to be able to have a more complex option than just text though. In my case I need to have an icon beside some text. I'm AFK at the moment but I'll attach a screenshot tomorrow

**Comment by segunadebayo** [comment]
@aaronmcadam. I've got you covered then.

**Comment by aaronmcadam** [comment]
@segunadebayo For clarity, here's my use case:

![CleanShot 2019-11-29 at 12 17 08](https://user-images.githubusercontent.com/37928/69868661-46cc0880-12a2-11ea-8c2b-feef8c85c526.gif)

**Comment by segunadebayo** [comment]
@aaronmcadam There won't be an input to search options in the `SimpleSelect` I've worked on. What I have mimics native HTML select and supports typeahead/rapid typeahead.

**Comment by Martinnord** [comment]
Hello! 

Are there any updates on this? It would be really cool to have this in this awesome lib! 

Cheers!

**Comment by segunadebayo** [comment]
Hi @Martinnord, The select component is in progress, you can track it in the `dev-ts` branch. I believe the first version will be out in our next release.

**Comment by Martinnord** [comment]
@segunadebayo Cool! Will keep an eye on that branch!

**Comment by Enigma10** [comment]
@segunadebayo I want to help you this component. Can you guide me?. I am beginner in open source.

**Comment by segunadebayo** [comment]
@Enigma10, Thanks for offering to help. For now, we've de-scoped the Select component to help us focus on the next major release.

Once we get back to it, I'll drop a comment here so I can guide you.

Cheers.

**Comment by adrianoresende** [comment]
We decided to use your Chakra as the initial DS, congratulations on your project, it's great. 👏 

So, we missed the searchable select and I read the issue here and we want to know if it has ETA to launch?

We can access the component to see if we can help?

**Comment by tomdohnal** [comment]
@segunadebayo 
Hi, now that the v1 is released (congrats!), is this component something you would consider adding to the library? 
I'd be happy to help you out with that if that's something you'd consider.

**Comment by TaylorFacen** [comment]
Hi! I'm checking in to see if there's a plan to implement a searchable select? styling with react-select is 👎🏾

**Comment by csandman** [comment]
@TaylorFacen You should check out my wrapper for react-select.  I spent a decent amount of time replacing the react-select styles with the chakra ones, in some cases just replacing the components entirely.

- Gist: https://gist.github.com/csandman/c687a9fb4275112f281ab9a5701457e4
- CodeSandbox: https://codesandbox.io/s/chakra-ui-react-select-648uv?file=/multi-select.js

**Comment by onurbamaro** [comment]
> @TaylorFacen You should check out my wrapper for react-select. I spent a decent amount of time replacing the react-select styles with the chakra ones, in some cases just replacing the components entirely.
> 
> * Gist: https://gist.github.com/csandman/c687a9fb4275112f281ab9a5701457e4
> * CodeSandbox: https://codesandbox.io/s/chakra-ui-react-select-648uv?file=/multi-select.js

Nice job! I'm kinda new to software development and a documentation on this would be nice. Do you have any? If not, could help me with something? 

Thanks in advance

**Comment by csandman** [comment]
@onurbamaro I don't have any documentation but it should take the same props as the original package.  As long as you have `react-select` and chakra installed, just copy the multi-select component into your app somewhere and import it instead of `react-select`.  The rest of the docs can be found at the `react-select` website: https://react-select.com/home.

If you have a specific question, feel free to ask!

**Comment by onurbamaro** [comment]
> @onurbamaro I don't have any documentation but it should take the same props as the original package. As long as you have `react-select` and chakra installed, just copy the multi-select component into your app somewhere and import it instead of `react-select`. The rest of the docs can be found at the `react-select` website: https://react-select.com/home.
> 
> If you have a specific question, feel free to ask!

Oh, now I get it. That's what I was looking for! Thank you and nice job once again, this is going to help a lot!

**Comment by csandman** [comment]
@onurbamaro You're welcome!

**Comment by tannerbaum** [comment]
@segunadebayo Has there been any consideration into expanding the select component to include search of extending it in a new component? 

@csandman did great work on his own solution, but having something directly from Chakra without relying on React-Select that is also in the Chakra TS ecosystem would be nice.

**Comment by csandman** [comment]
@tannerbaum I definitely agree that it would be great to have a combobox type component native to the Chakra lib, the component I made was only ever supposed to be a holdover until something like that exists

**Comment by aaronmcadam** [comment]
@tannerbaum There's been some experiments using Downshift on Chakra UI Pro. I've not had a chance to play with the component yet, though. But if the component is stable enough, it may make its way into the library.

**Comment by alexkreidler** [comment]
There's also a project that's focused on autocomplete features that uses the Downshift library's ComboBox:

https://github.com/koolamusic/chakra-ui-autocomplete

**Comment by csandman** [comment]
For anyone that has had any interest in my wrapper for react-select, I made it into an NPM package. You can find it here: https://www.npmjs.com/package/chakra-react-select

**Comment by csandman** [comment]
There have been some major improvements in version 2 and version 3 of my [`chakra-react-select`](https://www.npmjs.com/package/chakra-react-select) package, allowing for a fully customizable style system, and the native typescript support added in `react-select@5`.  So if my component didn't feel customizable enough at first, or you had issues implementing it in a TypeScript project, I highly recommend giving it a second chance.
