### ISSUE TITLE
[_hover Attribute] does not allow @media styles

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#1404]
```jsx
<Box
  as={FcSettings}
  size={iconSize}
  css={{
    '@media (prefers-reduced-motion: no-preference)': {
    animation: `${spin} infinite 3s ease-in-out`,
  },
  }}
/>
```

This is fine, but I don't want the animation to be applied unconditionally.

The same code but with `_hover` instead of `_css` will error:
![image](https://user-images.githubusercontent.com/29307652/88488010-9c1ffd00-cf8a-11ea-8ad6-3ab36e314de5.png)

https://codesandbox.io/s/exciting-brook-vtv3m?file=/src/App.tsx

**Comment by with-heart** [comment]
Interestingly enough, this also exposes the fact that nesting a pseudo prop inside itself (or inside other pseudo props) is valid. I don't think that should be the case.

**Comment by ljosberinn** [comment]
Well, at least emotion can handle it properly, so that might be why. 
![image](https://user-images.githubusercontent.com/29307652/88774999-6fcfd080-d184-11ea-9310-dd099e3eeb6a.png)

In fact, that might solve my issue.

```jsx
css={{
  animation: `${spin} infinite 3s ease-in-out`,
  ":hover": {
    "@media (prefers-reduced-motion: no-preference)": {
      animation: 'unset'
    }
  }
}}
```

But that obviously cirumvents the `_hover` prop.

**Comment by segunadebayo** [comment]
You're right. I'd naturally delegate this kind of work to emotion's css prop instead of adding it to the `_hover` prop.

**Comment by segunadebayo** [comment]
@with-heart, there are valid use-cases for nesting pseudo selectors.
