### ISSUE TITLE
[AlertDialog] Merge with Modal

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#1406]
Considering the[ `AlertDialog` _basically_ is a `Modal`](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/alert-dialog/src/alert-dialog.tsx) anyways, I propose merging them:

- remove all references to `AlertDialog`
- add `isAlert` or `isAlertDialog` to `ModalContentProps` which sets the `role` attribute accordingly

**Comment by with-heart** [comment]
I can see what you mean, but I feel like the semantic differences make it pretty clear that `AlertDialog` usage is separate and equal to a `Modal`, indicating to users that there's an important difference between the two. I'm not sure `isAlertDialog` signifies that same thing.

**Comment by ljosberinn** [comment]
I suspect you meant `...and _not_ equal to a Modal`? Anyways I went ahead (and should've read this earlier) and filed a PR 😅 if we drop this one, I'll file another one for the typings in there.

**Comment by with-heart** [comment]
Equal in status/importance, not equal as in being the same thing 😅

**Comment by ljosberinn** [comment]
We talked on Discord about it and we will merge `AlertDialog` into `Modal`, but not remove it entirely for now.
