### ISSUE TITLE
[v 1.0 - Modal] - Unable to give custom size for Modal

### ISSUE THREAD

**Issue by ganeshkrishnasharma** [chakra-ui/chakra-ui#1409]
in v 0 , i could give `<Modal size="90%">` to create a modal with 90% width and height of the screen size. This doesn't seem to work in v 1.0. How do i create a Modal with custom width and height as mentioned above in v 1.0 and above? This is a very frequent use case for many projects.

**Comment by with-heart** [comment]
This should help! 😄 

https://next.chakra-ui.com/docs/migration#5-update-layout-size-prop
