### ISSUE TITLE
TypeScript:  CSSReset: config prop is missing from type

### ISSUE THREAD

**Issue by aaronmcadam** [chakra-ui/chakra-ui#141]
CodeSandbox: https://codesandbox.io/s/chakra-ts-starter-tmw03

The type for `CSSReset` is just `React.FC` without the generic for props.

My use case for wanting to configure `CSSReset` is to set a custom background color on `body`. Should there be a better way to configure this instead?

This came up a while ago here: https://github.com/chakra-ui/chakra-ui/issues/101#issuecomment-533213660

**Comment by segunadebayo** [comment]
Yes, I'll update the types for the CSSReset.

For now, a walkaround would be to use Emotion's `<Global />` component.

**Comment by aaronmcadam** [comment]
Ah, that's what I was thinking @segunadebayo. Thanks again!

**Comment by segunadebayo** [comment]
Here's the type def updates for CSSReset. What do you think?

```ts
interface Config {
  color: string;
  bg: string;
  borderColor: string;
  placeholderColor: string;
}

type ConfigReturnType = { light: Config; dark: Config };

type CSSResetProps = {
  config?: (
    theme: ITheme,
    defaultConfig?: ConfigReturnType,
  ) => ConfigReturnType;
};
```

**Comment by aaronmcadam** [comment]
That looks great @segunadebayo!

**Comment by segunadebayo** [comment]
I've released a patch for this.

**Comment by aaronmcadam** [comment]
Thanks!
