### ISSUE TITLE
Can MenuItem be extended to take an icon prop?

### ISSUE THREAD

**Issue by aaronmcadam** [chakra-ui/chakra-ui#142]
I'm currently having to compose the UI myself. It works, but it's a little bit clunky.

Here's a sandbox: https://codesandbox.io/s/chakra-js-starter-z0400

I'm thinking it'd be nice to reuse `Button`'s `leftIcon` and `rightIcon` prop names for this.

I think this idea could be used for the new Select component too (#38)

**Comment by segunadebayo** [comment]
I see what you mean. 

Allowing users to compose the content of `MenuItem` was intentional and I understand that having the `icon` prop will save some time.

I'll consider adding that to the `MenuItem` component.

**Comment by aaronmcadam** [comment]
Don't get me wrong, I love the flexibility having users compose the content allows, it just seems like a common pattern people might want to implement is all. It's not a huge issue 😄

**Comment by segunadebayo** [comment]
For sure, I understand your point 😄. Thinking about it again, it makes sense. I'll add it to the `MenuItem` component.

**Comment by aaronmcadam** [comment]
Did this get into the `dev-ts` branch @segunadebayo?

**Comment by segunadebayo** [comment]
@aaronmcadam. I intend to add a `MenuItemIcon` component in the `dev-ts` branch

**Comment by aaronmcadam** [comment]
> @aaronmcadam. I intend to add a `MenuItemIcon` component in the `dev-ts` branch

Thanks @segunadebayo.
