### ISSUE TITLE
[Image] Broken with JS disabled (SSR)

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#1422]
Simply renders `[object Object]` with JS disabled using SSR.

![image](https://user-images.githubusercontent.com/29307652/88553537-acd18100-d025-11ea-8796-3203f1a200f7.png)

Apparently adding the `ignoreFallback` prop is a workaround, and was so in the past (v0.8, see #462)

**Comment by ljosberinn** [comment]
...and apparently also when exporting to a static site with next.

**Comment by tonilaukka** [comment]
This is related https://github.com/chakra-ui/chakra-ui/issues/462

**Comment by segunadebayo** [comment]
Thanks for reporting this issue @ljosberinn. I think a good fix would be to ignore the fallback logic when in an SSR environment so the `src` attributes get added properly.

**Comment by segunadebayo** [comment]
I've just pushed a fix for this. 

Thanks, guys.
