### ISSUE TITLE
Pass props defined in the theme .defaultProps to the components

### ISSUE THREAD

**Issue by santialbo** [chakra-ui/chakra-ui#1424]
*(Opening this ticket so the conversation doesn't get lost on discord)*

Right now only stylistic props in the `defaultProps` section of the component theme are used. Any other properties are ignored. (See [codesanbox](https://codesandbox.io/s/objective-feistel-gd0xt?file=/src/index.tsx))

There is a bunch of non-stylistic properties that would benefit from being passed to the underlying component. Some examples:
- Being able to set a default openDelay on all tooltips.
- Being able to set all tooltips with `hasArrow`.
- Being able to set a default `as` on the different variants/sizes of `Heading`.
- Overriding the default aria-label on components like the `CloseButton` (e.g. translating it to other languages).

Right now the only alternative would be to create a custom wrapper component that sets those defaults props.

**Comment by with-heart** [comment]
I think this is a great idea. These are valid, common sense use cases. Wrapper components are also the worst.

**Comment by cloudratha** [comment]
Just ran into this use case. Defining `ReachLink` on the `as` prop by default would be amazing.

**Comment by segunadebayo** [comment]
This idea is a two-edged sword if you ask me. We want the theme to be used only for theme-related stuff not for component props, that's why `defaultProps` exists.

I can see this getting abused a lot if we add this. I understand it might be a bit painful and it's more convenient to go this route but we'll hold off on this.

We want to limit the component theme's defaultProps to be for styles only. We'll revisit this in the future.

**Comment by santialbo** [comment]
I think this is a mistake. It's not that it's painful to do it the other way it's practically impossible and very prone to errors.
Having support for customizing behavioral props is key for a design system.

If people want to abuse this feature, so be it, it's going to be their problem in the long run. I don't think you should worry about this.

**Comment by segunadebayo** [comment]
I'm going to discuss with the team @santialbo, and re-open it if we agree to add this.

Interestingly, I have some implementation around this idea already but I'd prefer to think this through with the team properly before adding it.

I don't think it's impossible to create a wrapper component or define component props in a separate file and use them across all components.

**Comment by segunadebayo** [comment]
I've re-opened it even though it's not a priority for us at the moment. Let's leave it around.

**Comment by santialbo** [comment]
Thanks a lot @segunadebayo 
> I don't think it's impossible to create a wrapper component or define component props in a separate file and use them across all components.

One problem with the wrapper approach is that people forget which components have been customized and which have not. And importing thre wrong one by mistake becomes very easy, which is also easy to overlook during reviews 😔

**Comment by cloud-walker** [comment]
Hi all, I know it may be a bit hacky, but I thought it was good to share: you can actually override the `defaultProps` as follows

```javascript
// my-theme.js

import {extendTheme, Tooltip} from '@chakra-ui/react'

// ...

Tooltip.defaultProps = {...Tooltip.defaultProps, hasArrow: true}
```

Have a good weekend!

**Comment by segunadebayo** [comment]
Thanks for the request! Considering this isn't a bug, I'll add this to our project board so you can track the progress.

Check it here: https://github.com/chakra-ui/chakra-ui/projects/6

Cheers.
