### ISSUE TITLE
[Select] Dark colour mode issue in Firefox

### ISSUE THREAD

**Issue by antonjb** [chakra-ui/chakra-ui#1429]
The Select component, when combined with the dark colour mode means that the select options become 'invisible' (white text on a white background). They are visible when you hover each option but the experience is not ideal. Other browsers don't appear affected by this issue.

**Firefox 78.0.2**
<img width="753" alt="image" src="https://user-images.githubusercontent.com/1066856/88606295-df738c00-d0ae-11ea-9985-d4133f3b9f9b.png">

**Expected Behavior**
Expected behaviour is to change the background colour of the select to the dark colour mode colour. Similar to what happens in Chrome

**Chrome 84**
<img width="738" alt="image" src="https://user-images.githubusercontent.com/1066856/88606369-10ec5780-d0af-11ea-8e42-050e12d3457f.png">

**Link to minimal reproduction** Please provide a codesandbox link or GitHub
repo with a minimal reproduction of the issue.

https://chakra-ui.com/select

**Steps to Reproduce** Clear and concise reproduction instructions are important
for us to be able to triage your issue in a timely manner.

1. Go to https://chakra-ui.com/select in Firefox
2. Click on the select drop
3. See error

**Suggested solution(s)**

Would need to have the same background colour as it does in other browsers if possible.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Firefox 
- Version 78.0.2

**Comment by with-heart** [comment]
Hi @antonjb, this has been fixed as of `1.0.0-rc.0` (see #1315). We're no longer doing work on earlier versions in preparation for the upcoming `1.0.0` release. Thanks for reporting!
