### ISSUE TITLE
TypeScript: MenuItem does not allow the props needed by a component override

### ISSUE THREAD

**Issue by aaronmcadam** [chakra-ui/chakra-ui#143]
CodeSandbox: https://codesandbox.io/s/chakra-ts-starter-s8bur

I came across this when trying to make a TypeScript sandbox for #142.

I think the type should allow the props allowed by the component used in the `as` prop. I appreciate this might be a little bit hard to do with TypeScript. I imagine some fun with generics is needed.

**Comment by segunadebayo** [comment]
This is a very common problem with typescript and the "as" prop. Not sure how to fix it.

A temp walkaround will be to create a new component like this:

```tsx
type NewMenuButtonProps = MenuButtonProps | IconButtonProps

const NewMenuButton: React.FC<NewMenuButtonProps> =  React.forwardRef((props, ref: React.Ref<HTMLButtonElement>)=> {
  return <MenuButton ref={ref} as={IconButton} {...props} />
})
```

I'm not that good with TS but I think it's a good walk around for now.

**Comment by aaronmcadam** [comment]
I don't think that workaround is too bad.

I think we'd have to use generics, so it'd look something like this:

```ts
// when TypeScript 3.7 is out, we'll have recursive types.
// Some other wrapper type might work though
type MenuButtonProps<ComponentOverrideProps> = MenuButtonProps & ComponentOverrideProps;

// then, using it in TSX would look like this:
<MenuButton<IconButtonProps> as={IconButton}>...</MenuButton>
```

**Comment by segunadebayo** [comment]
This looks interesting. I'd appreciate your PR on this on when TypeScript 3.7 is out.

Read through the blog post and the issue in Formik. Thanks for sharing, I'll look into generics.

**Comment by aaronmcadam** [comment]
I've just hit a similar problem with `<Link as={ReactRouterLink{} />` I can't get the custom type to work. The ref is a problem. I'll follow up with a sandbox in a minute

**Comment by aaronmcadam** [comment]
Here's the sandbox: https://codesandbox.io/s/chakra-ts-starter-1thkj

**Comment by segunadebayo** [comment]
I guess we'll need to look into this `as` prop ASAP. Any ideas on how to fix this using generic types?

I'll look into this later.

**Comment by aaronmcadam** [comment]
Yeah I don't know how to extend the types on my local project. This is blocking me, so I need to figure that out before I can override the types.

I'm trying this:

```ts
interface As {
  as?: React.ElementType | ReactRouterLink;
}
```

**Comment by aaronmcadam** [comment]
I found this workflow on how to override the types cleanly: https://stackoverflow.com/a/54840439/104625
