### ISSUE TITLE
[Button] V1.0 Large Button Loading Not V-Centered

### ISSUE THREAD

**Issue by nahtnam** [chakra-ui/chakra-ui#1432]
**Describe the bug**
When you add `isLoading` to a button, it is not v-centered
![image](https://user-images.githubusercontent.com/20051852/88612942-4195a800-d041-11ea-95f3-91690d584c7a.png)

**Expected Behavior**

Should be v-centered
**Link to minimal reproduction**

See screenshot, can do on the demo

**Steps to Reproduce** 

Add `isLoading` to a large button

**Suggested solution(s)**

Unsure

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Edge
- Version: 84.0.522.44

**Comment by segunadebayo** [comment]
Thanks for reporting this. I've just fixed it.
