### ISSUE TITLE
[gatsby-plugin-chakra-ui@0.1.4] has incorrect peer dependency "@chakra-ui/core@0.3.2".

### ISSUE THREAD

**Issue by bnbabu55** [chakra-ui/chakra-ui#1433]
warning " > gatsby-plugin-chakra-ui@0.1.4" has incorrect peer dependency "@chakra-ui/core@0.3.2".

1. Install gatsby-plugin-chakra-ui in a gatsby project
2. installation throws this warning

- OS: Windows 10
- Browser chrome
- Version 84

**Comment by with-heart** [comment]
Hi @bnbabu55! I can verify that the peer dependency is correct. I think you can safely ignore the warning. 

We're currently at `1.0.0-rc.0` with `1.0.0` coming soon, and work on earlier versions of Chakra UI and `gatsby-plugin-chakra-ui` is currently frozen. This will no longer be an issue once `1.0.0` is published. See https://next.chakra-ui.com/ for more information!
