### ISSUE TITLE
[MenuButton] Can't specify Button specific props with TypeScript

### ISSUE THREAD

**Issue by selbekk** [chakra-ui/chakra-ui#1434]
**Describe the bug**

When using TypeScript, I can't specify props of the component I pass in to the `as` prop of the `MenuButton` component.

Here's a reproduction: https://codesandbox.io/s/busy-tereshkova-je9f7?file=/src/App.tsx

TL;DR: Whenever I do this:

```tsx
<MenuButton as={Button} rightIcon="chevron-right" />
```

, the TypeScript compiler complains that `rightIcon` is not a valid property. The same goes for any `Button` specific property.

I can work around it by creating a custom component with all my `Button` props beforehand, like so:

```tsx
const ButtonWithProps = (props: any) => <Button {...props} rightIcon="chevron-right" />
// ...
<MenuButton as={ButtonWithProps} />
```

or even inline, if I'm feeling lazy:

```tsx
<MenuButton as={(props: any) => <Button {...props} rightIcon="chevron-right" />} />
```

but both of these options seem hacky, and I'd rather have the `MenuButton` allow all the props of the component passed in to `as`. I know that particular feature is basically impossible, but at least let me pass in whatever props I want then.

I'd be open to create a PR for adding the latter.

**Comment by santialbo** [comment]
The codesandbox you created is for v0.8. It should work fine on v1 https://codesandbox.io/s/modest-sinoussi-ptz7u?file=/src/App.tsx

**Comment by santialbo** [comment]
Also if you dont want ts to complain on v0 the only work-around i found was to do this 
```
<MenuButton
  as={Button}
  {...{ rightIcon: "chevron-down" }}
  >
  ...
</MenuButton>
```

**Comment by selbekk** [comment]
Great to hear. unfortunately, V1 isn't released yet. If you plan on supporting the v0 branch, this should still be addressed. If you're freezing v0 until v1 is released - then that's fine.

**Comment by with-heart** [comment]
Correctly typing the `as` prop was one of many reasons for the v1 TypeScript rewrite. Unfortunately it's not feasible for us to get that working for 0.8.0.

**Comment by selbekk** [comment]
Fair enough :) I'm glad it'll be fixed in v1 though!
