### ISSUE TITLE
[Installation] Chakra v1 + Vite don't work together

### ISSUE THREAD

**Issue by brennj** [chakra-ui/chakra-ui#1435]
**Describe the bug**

When you try to use Vite (an amazing tool!) https://github.com/vitejs/vite with the latest Chakra, you run into issues.

You'll get the following error trying to run Vite with Chakra v1 installed:

```
[vite] Dep optimization failed with error:
'ResponsiveValue' is not exported by node_modules/@chakra-ui/styled-system/dist/esm/utils/index.js, imported by node_modules/@chakra-ui/styled-system/dist/esm/index.js
Error: 'ResponsiveValue' is not exported by node_modules/@chakra-ui/styled-system/dist/esm/utils/index.js, imported by node_modules/@chakra-ui/styled-system/dist/esm/index.js
```

I haven't looked in depth, I believe ResponsiveValue is a typescript type in this case?

**Expected Behavior**

If you remove that export from the node_modules it runs buttery smooth and is an amazing developer experience from both the Vite and Chakra side. It would be nice to be able to use v1 in this manner.

**Steps to Reproduce**

1. `npx create-vite-app vite-test  --template react`
2. `cd vite-test`
3. `yarn`
4. `yarn add @chakra-ui/core@next` (installs as of writing `@chakra-ui/core 1.0.0-rc.0`)
5. `yarn dev`

**Suggested solution(s)**

Is there a way to exclude this export from the esm build? I'm not 100% knowledgeable on the finer parts of TypeScript. 

**Desktop (please complete the following information):**

- OS: Tested on both Windows 10 and MacOS 

**Additional context** 

The work for the run up to v1 is amazing, well done to the people involved.

**Comment by with-heart** [comment]
Thank you for the kind words @brennj! This issue has also been reported on Discord so I can verify that you're not the only one facing this issue. We'll try to get this resolved shortly!

**Comment by segunadebayo** [comment]
Thanks for catching this @brennj.

I've just fixed it and we'll publish an update shortly
