### ISSUE TITLE
[IconButton] whilst isDisabled={true} onClick function is still fired on click

### ISSUE THREAD

**Issue by DanLeCornu** [chakra-ui/chakra-ui#1436]
**Describe the bug**
When IconButton has isDisabled set to true, it looks disabled, but still actually runs the onClick function when clicked

screen capture:
https://giphy.com/gifs/PkcYSp2C6HJ4UG2lbP

**Expected Behavior**
When isDisabled prop is true, onClick function should not fire

**Link to minimal reproduction**
```
import React from "react"
import { Button, IconButton } from "@chakra-ui/core"
import { FiAlertCircle } from "react-icons/fi"

export const TestIconButton: React.FC = () => {
  const [isDisabled, setIsDisabled] = React.useState<boolean>(false)

  return (
    <>
      <IconButton
        aria-label="delete"
        as={FiAlertCircle}
        isDisabled={isDisabled}
        onClick={() => alert("click!")}
      />
      <Button ml={4} onClick={() => setIsDisabled(!isDisabled)}>
        Toggle isDisabled
      </Button>
    </>
  )
}
```

**Steps to Reproduce**
1. Add isDisabled prop to IconButton
2. Click button
3. Cry

**Desktop (please complete the following information):**
- OS: Mac OS
- Browser: Safari
- Version: 1.0.0-rc.0

**Additional context**
I have not tested out other buttons or links

**Comment by dodas** [comment]
I think it has to do with the fact that you are using `as` property. 
Have you tried using `<IconButton icon={<FiAlertCircle />} .... />`?
That is the documented way and works fine, respecting `isDisabled`.

Is it really a bug? I am not sure.

**Comment by with-heart** [comment]
Reproduction of what @dodas means: https://codesandbox.io/s/broken-cookies-ehkti?file=/src/App.tsx

I think that's the correct answer. It works as expected when using `icon`, which is the documented method for adding icons.

**Comment by DanLeCornu** [comment]
thank you @with-heart for pointing that out and explaining!
