### ISSUE TITLE
Prevent Menu from overlapping navbar

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1452]
![image](https://user-images.githubusercontent.com/1954752/88845357-05ce2000-d1b2-11ea-80a6-26b099d7db75.png)

To reproduce:

- visit https://next.chakra-ui.com/docs/components/menu
- open one of the menus
- scroll down the page

**Comment by segunadebayo** [comment]
This is related to the z-index of the navbar's header. Generally, we need to set it to a higher z-index just like the v0 docs.

If anyone wants to open a PR that would be great.

**Comment by Easybuoy** [comment]
I can work on this @with-heart

**Comment by with-heart** [comment]
Yes please @Easybuoy! That would be awesome.
