### ISSUE TITLE
[Menu] Detect if menu is still within viewport before returning focus to previous ref on close

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1453]
To reproduce:

- Visit https://next.chakra-ui.com/docs/components/menu
- Open one of the menus
- Scroll down the page
- Click or press <kbd>ESC</kbd>

I'm not sure what's appropriate behavior here, but wanted to start discussion. I would not expect the page to jump all the way back to the menu if I've scrolled before closing it.

**Comment by segunadebayo** [comment]
I see where you're going. I think we only need to prevent scroll even if we restore the focus back to the menu button.

**Comment by segunadebayo** [comment]
I just pushed a fix for this!
