### ISSUE TITLE
Inconsistent margin/padding 

### ISSUE THREAD

**Issue by cyberwombat** [chakra-ui/chakra-ui#1457]
I am thoroughly confused by the use of margin/padding in the format of `p={4}` because the spacing is completely inconsistent. Ive upgraded to latest chakra with no difference. 

Here's a shot of me attempting to add margin to a Box:. I use code such as `<Box pl={X}....  `. The number shown is the padding size - as you can see a padding of 14 is completely off and no idea why. I have seen this over and over. Am I misunderstanding how to use these numbers?
<img width="508" alt="Screen Shot 2020-07-29 at 6 15 54 PM" src="https://user-images.githubusercontent.com/777498/88869529-e93ce280-d1c7-11ea-8541-62156accfca8.png">

I can try to make a demo but I can't believe I am the only one with this weird issue.

If I look at my inspector when I use `pl={14}` I see `padding-left:14px` but if I use `pl={16}` I see `4rem`. Somehow there is a mix of px/rem going on.

**Comment by with-heart** [comment]
Hi @cyberwombat! Just a slight misunderstanding there! 

Check out https://chakra-ui.com/theme#spacing. The reason you're seeing `14px` at `14` is that if you don't provide a number that isn't in the spacing scale, we assume you're trying to use a specific pixel value.

The mental model note from that section provides an easy way to remember the scale:

![Screenshot_20200729-214756.png](https://user-images.githubusercontent.com/1954752/88871186-3d09f480-d1e5-11ea-86e0-7fcf3542bbc0.png)

**Comment by cyberwombat** [comment]
Thanks that explains it but itsn't that a little confusing? I have to print the chart and paste it on the wall to know. Why not just divide by 4?   14/4 = 3.5 rem....
