### ISSUE TITLE
Request to add support for custom Input placeholder styling

### ISSUE THREAD

**Issue by epleaner** [chakra-ui/chakra-ui#1460]
**What problem does this feature solve?**
Right now, there isn't a way to style the placeholder of an Input component, especially when using Color Mode. The pseudoelement styling is being injected inline as input::placeholder, textarea::placeholder. 

**What does the proposed API look like?** 
Something either akin to a pseudobox that supports the ::placeholder pseudoselector, or an attribute on the Input tag (e.g placeholderStyles).

**Describe alternatives you've considered**
Tried adding the color attribute to the Input component the inline pseudoelement styles are higher priority.

**Comment by santialbo** [comment]
You can do this on v1 https://codesandbox.io/s/upbeat-booth-sjwfo?file=/src/index.tsx:202-219

**Comment by santialbo** [comment]
Also on v0 https://codesandbox.io/s/empty-hill-o48yx?file=/src/index.tsx
(notice the pragma on the first line)

**Comment by segunadebayo** [comment]
Thanks for chiming in @santialbo 💖
