### ISSUE TITLE
Display logos of companies using Chakra

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1466]
We've had quite a few responses to #405. We should display some of these logos on the website to increase our social credibility.

**Comment by Easybuoy** [comment]
I can work on this @with-heart. Do you have an idea of what it would look like yet?

**Comment by with-heart** [comment]
@segunadebayo is the heart and soul of Chakra design. Let's see if he has anything in mind!

**Comment by segunadebayo** [comment]
Done!
