### ISSUE TITLE
NumberInput: background color can not be overridden

### ISSUE THREAD

**Issue by aaronmcadam** [chakra-ui/chakra-ui#147]
CodeSandbox: https://codesandbox.io/s/chakra-js-starter-iwy4d

I like to style my inputs with grey backgrounds when they are on white backgrounds.

It seems to work for `Input`, but it doesn't work for `NumberInput`

**Comment by segunadebayo** [comment]
I'm currently looking to make the NumberInput API a bit more declarative so it's easy to change the styling. As a walkaround, you can pass `variant="filled"` to `Input` or `NumberInput` to give it a grey background interaction out of the box.

I'd release the patch as soon as I finish this.

**Comment by aaronmcadam** [comment]
Ah, I didn't know that variant existed! Thanks!

**Comment by segunadebayo** [comment]
Yeah, I'll add it to the docs soon 😄.

**Comment by aaronmcadam** [comment]
I've tried `variant="filled"` in the sandbox, but when I click on the input, it goes white. Is that by design @segunadebayo?

**Comment by segunadebayo** [comment]
Yes, it's by design @aaronmcadam. I thought it was a common pattern, taking clues from AtlasKit by Atlassian.

Once I improve the API for the NumberInput, you'll have full control over the styling.

**Comment by aaronmcadam** [comment]
No worries, I don't dislike it, I just expected `backgroundColor` to override it. Is it worth writing up a spec for the `NumberInput`?

**Comment by segunadebayo** [comment]
I see what you mean. Since NumberInput composes `PseudoBox`, you would be able to do this once the new API is released.

```jsx
<NumberInput _focus={{ backgroundColor : "gray.100" }}/>
```

I'd suggest the spec should come after the new API release.

**Comment by segunadebayo** [comment]
@aaronmcadam Here's a preview of the new API

```jsx
<NumberInput max={35} min={0} step={4} defaultValue={23}>
      <NumberInputField />
      <NumberInputSpinner>
        <NumberIncrementSpinner />
        <NumberDecrementSpinner />
      </NumberInputSpinner>
</NumberInput>
```

This is a bit more declarative and gives you the room to override the styling of different parts. 

The bug you showed the other day about clearing the value and it resetting to `0` has been resolved as well.

**Comment by aaronmcadam** [comment]
@segunadebayo That looks great! I think `NumberInputStepper` might be a better name than `NumberInputSpinner` though.

**Comment by segunadebayo** [comment]
Thanks for that feedback. `NumberInputStepper` sounds like a better name. I'll rename it.
