### ISSUE TITLE
[SlideIn] Type definition for children is not correct

### ISSUE THREAD

**Issue by selbekk** [chakra-ui/chakra-ui#1473]
**Describe the bug**

This is a 0.8 bug.

The type definition for the `SlideIn` component's `children` prop is not correct. It's being overridden by `TransitionProps`. `SlideInProps` need to come last.

Here's a reproduction: https://codesandbox.io/s/relaxed-architecture-slmh0?file=/src/App.tsx

**Comment by with-heart** [comment]
See comment in #1474. Thanks for taking the time to open a PR though :)
