### ISSUE TITLE
Error: Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by Rohitkhaitan** [chakra-ui/chakra-ui#1481]
I've built some components that wrap chakra components. I'm trying to strip them out into their own library that I can include in other projects. I'm receiving an error on loading my apps that I include this library into when I try to use toasts.
Facing issue with in my webpack based library.
![image](https://user-images.githubusercontent.com/35948172/89089001-c32a6480-d3b8-11ea-945c-1a7e8346732b.png)

**Comment by ljosberinn** [comment]
Hi @Rohitkhaitan thanks for filing an issue!

However we need more info: which component caused this in which constellation?
Would be great if you could share some code, ideally the entire component in which you used chakra which led to the crash.

**Comment by struct78** [comment]
@Rohitkhaitan The error message is pretty self explanatory. You can't use `useToast()` outside of a React component, it sounds like you're trying to use it in a module.

**Comment by segunadebayo** [comment]
@ljosberinn Please re-open once we get a response that seems like a legit issue.

Thanks for chiming in @struct78
