### ISSUE TITLE
[MenuButton] Lost its Button-like appearance

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#1482]
`Button` still looks as intended, `MenuButton` however doesnt.

Compare https://next.chakra-ui.com/docs/form/button with https://next.chakra-ui.com/docs/components/menu

I assume something unintended happened here:
https://github.com/chakra-ui/chakra-ui/commit/944fa4832d52f9cfe5cda141a3016eb719f087f0#diff-70ae624a9f188d0075cd0d22c6743311
or here 
https://github.com/chakra-ui/chakra-ui/commit/cc58fa2030e38e30f860284891fead2a1cdcbf83#diff-70ae624a9f188d0075cd0d22c6743311

Edit:
- works in dev storybook
- does not work in dev docs, interestingly
- `Letter Navigation` example looks broken in storybook but isnt in the docs:
![image](https://user-images.githubusercontent.com/29307652/89102868-6f963600-d40d-11ea-8135-ca9acb6c0319.png)
![image](https://user-images.githubusercontent.com/29307652/89102869-71f89000-d40d-11ea-8de0-546fa8a33871.png)

This is probably because in the stories, `FaChevronDown` is imported from `react-icons`.

- I think the type of `MenuButtonProps` still has a leftover `subMenuIcon` from the submenu deprecation. it's not mentioned in the docs on the button, but still present on the interface

**Comment by with-heart** [comment]
The issue is here: https://github.com/chakra-ui/chakra-ui/blob/cdad5595e17160d7b2118b8ec78197d10127955b/packages/menu/src/menu.tsx#L103-L106

`StyledMenuButton` doesn't have any real styles on its own. Storybook examples work because they all have styles attached and use `as={Button}`. @segunadebayo do you have some base styles in mind to attach to `StyledMenuButton`?

**Comment by segunadebayo** [comment]
I wanted us to revert to v0.8, `<Menu as={Button} />` to reduce breaking changes. That's why it looks that way. We'll update the docs to reflect this.

**Comment by segunadebayo** [comment]
Letter navigation seems to work correctly on my end.

I've updated the docs to reflect <Menu as={Button} /> behavior. @with-heart I don't plan to add base styles for now, but the user can definitely do that if they want.
