### ISSUE TITLE
[CheckboxGroup] Missing name attribute

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#1486]
According to the docs, [CheckboxGroup accepts a `name` property](https://next.chakra-ui.com/docs/form/checkbox#checkboxgroup-props).
However, that's not the case. Neither the implementation, nor the test or the story ever reference `name`. 

**Expected Behavior**
The prop should either exist or the documentation should reflect the nonexistance.

**Suggested solution(s)**
- remove `name` attribute from documentation
- add `name` attribute to the implementation since `defaultValue` is supported as array already and having only one supported feels odd

**Comment by saptaksengupta** [comment]
Hi @ljosberinn. I would love to contribute.

**Comment by ljosberinn** [comment]
@saptaksengupta thank you :) let's wait what @segunadebayo thinks of this

**Comment by segunadebayo** [comment]
I see what you mean, I've removed the name from the checkbox group's prop table.

We don't really need to have that prop in the implementation as it's usually connected to a form library like Hook form or Formik where the name will be explicitly supplied.

Thanks for catching this.
