### ISSUE TITLE
Problems with <Image /> component

### ISSUE THREAD

**Issue by paynecodes** [chakra-ui/chakra-ui#149]
First off, thank you for an awesome library. I hope this is one the community can support 🚀. I'm running into several problems with the `<Image />` component which I'll outline below.

## Problem 1 - `<img />` `width / height` props

HTML `<img />` accepts `width / height` attributes which helps the browser paint the screen without "jank". Currently, `<Box>` / styled-system / ?, takes these props as css width/height. I understand that this is intentional and desirable for most situations. Perhaps we could add `htmlWidth` and `htmlHeight` (similar to `htmlFor` from react-dom) and pass those props as to the underlying `<img />` element.

Proposed prop names:

1) `htmlWidth` / `htmlHeight`
2) `widthAttribute` / `heightAttribute`
3) `domWidth` / `domHeight`

Whatever you decide here, keep in mind that there will likely be other prop names that should pass through to the underlying element in the future.

## Problem 2 - `useImageHasLoaded` hook causing multiple network requests

The [`useHasImageLoaded `](https://github.com/chakra-ui/chakra-ui/blob/2540204a41121a59c0d7f1228c4cf27c14a0d1e3/packages/chakra-ui/src/Image/index.js#L6-L42) causes (I think) multiple network requests for the same image. I have not tested with the optional `fallbackSrc`, but this should not be required for proper image loading.

## Problem 3 - `<Box />` and `BoxProps` TypeScript

I attempted to workaround Problem 1 & 2 in my user code by reimplementing `<Image>`. I, too, would like to do so using `<Box as="img" ... />` similarly to how this lib handles it. The problem I encountered immediately is `BoxProps`. The TypeScript types are defined as such that `<Box as="img" />` doesn't accept a `src` prop. This is likely going to be a problem for many TypeScript users that would like use the `<Box as="something" />` paradigm. I'm not sure if this can be solved generically by the lib. Also, I'm not sure how to solve this in my own code yet. It may be unfortunate to have to resort to allowing every possible prop such as `src` on `<Box />` just because it may be used as an `<img />`, `<video />`, or `<SomeRandomComponent />`.

**Comment by segunadebayo** [comment]
Hi @paynecodes,

Thanks for this detailed feedback. It makes a lot of sense.

Problem 1 - Sounds interesting and I'll look into this much later. It seems like an adjustment that needs to be made from `styled-system`. If you have some time to look into this as well, I'd appreciate a PR.

Problem 2 - I'll test this hook again to ensure it doesn't have multiple requests. The goal was to support the use of a fallback src in the event the image didn't load. I'll look into alternative ways of getting this without the hook.

Problem 3 - I'm currently attempting to solve this `as` issue in the library. In the meantime, I can export a `css` function that'll help you style any element by passing the `css` prop and using the same theme-aware style props.

Looking to migrate to TS after the next release, hopefully this problem can be solved afterward..

Thanks again.

**Comment by aaronmcadam** [comment]
> I can export a css function 

That's something I was wanting to be added too as an escape hatch for these edge cases 👍 

Maybe we could add a "Recipes" page to the docs showing these workaround techniques.

**Comment by paynecodes** [comment]
I see the work for the image width/height happening here: https://github.com/chakra-ui/chakra-ui/commit/e4b61652c87e4d76963115d2808c8937edc6224e

👍

**Comment by segunadebayo** [comment]
@paynecodes, yep. It's live already, check here: https://chakra-ui.com/image#props

Currently working on the Typescript issue.

**Comment by menberg** [comment]
@segunadebayo Thanks for your amazing work!

Regarding Problem 2 – the images are flashing when using the useImageHasLoaded hook, even when the images had been loaded before. Best seen on the Avatar page https://chakra-ui.com/avatar while switching the theme from light to dark.

I think the useHasImageLoaded hook should return true if the the image can be found in the cache. Would this be possible?

**Comment by segunadebayo** [comment]
@menberg, sounds like a good idea. I'll try it out.

**Comment by mshwery** [comment]
Avatars and Image components still flash even with images from the cache. 

Ideally we would allow users to preload images too, to prime the cache, a `preload` boolean prop would suffice with:
```
React.useLayoutEffect(() => {
  if (props.preload && props.src) {
    const image = new Image()
    image.src = props.src
  }
}, [props.preload, props.src])
```

**Comment by aaronmcadam** [comment]
@mshwery I've been trying to preload Avatar images recently too, but nothing seems to work that well. Have you managed to get a solution that works for you?

**Comment by mshwery** [comment]
> @mshwery I've been trying to preload Avatar images recently too, but nothing seems to work that well. Have you managed to get a solution that works for you?

Not with Chakra. I had to write a custom Avatar component, and same for Image. 

I had a situation where the components had to remount and the flickering was unacceptable. Swapped out with my own Avatar and Image components they work flawlessly with preloading (using the code shown above)

**Comment by aaronmcadam** [comment]
> > @mshwery I've been trying to preload Avatar images recently too, but nothing seems to work that well. Have you managed to get a solution that works for you?
> 
> Not with Chakra. I had to write a custom Avatar component, and same for Image.
> 
> I had a situation where the components had to remount and the flickering was unacceptable. Swapped out with my own Avatar and Image components they work flawlessly with preloading (using the code shown above)

My use case is loading images from S3, which when using the Avatar from Chakra, will first show the initials because the image is `undefined` until the S3 image loads. 

I'm also trying to deal with ugly performance problems with `Image`, loading files from S3 there too, I see a broken image until the file loads in. Preloading doesn't really help much.

I might end up doing the same as you. Thanks for the idea!

**Comment by mshwery** [comment]
Yeah unfortunately preloading didn't work with Chakra components because of the loading hooks they use internally. It means even for cached/preloaded images you will get an immediate flicker.

That's why I had to write my own components instead of using Chakra's which is a shame.

**Comment by aaronmcadam** [comment]
@mshwery Are you able to share a gist of your custom Avatar and Image components? I think I know what I need to do, but just I'm wondering if you're taking account of any other issues that I'm not thinking about!

**Comment by keepersmith** [comment]
I'm experiencing the same issues with chakra Image and Avatar (flashing on initial page load / reload).
I kind of solved the issue with Image by adding an empty span fallback element, but there seems to be no way to avoid the flashing with Avatar.
Has anybody else solved this, and can maybe share the code?
Thanks.

**Comment by aaronmcadam** [comment]
@keepersmith This one is worth discussing on Discord, I think: https://discord.com/invite/chakra-ui

**Comment by mshwery** [comment]
here's a sample of the code (missing a couple functions but you can fill in the blanks). Like I mentioned, we basically rewrote the Avatar so it wouldn't have the flashing behavior at all, because there is no way around it.

```ts
export default React.forwardRef((props: AvatarProps, ref: React.ForwardedRef<HTMLDivElement>) => {
  const { name, size = 'md', src, ...boxProps } = props

  const [imageUnavailable, setImageUnavailable] = React.useState(!src)

  usePreloadedImage(src)

  const initials = React.useMemo(() => getInitials(name), [name])
  const hash = React.useMemo(() => hashCode(name), [name])
  const theme = useTheme()

  const bgColorKeys = Object.keys(theme.colors).filter((key) => {
    return !['black', 'transparent', 'current', 'white', 'whiteAlpha', 'blackAlpha'].includes(key)
  })

  const backgroundColor = name ? theme.colors[bgColorKeys[hash % bgColorKeys.length]]['100'] : theme.colors.gray['300']

  const color = readableColor(backgroundColor) === '#000' ? 'gray.900' : 'white'

  const resolvedSize = getSize(size)

  return (
    <Flex
      ref={ref}
      flex="none"
      position="relative"
      display="flex"
      justifyContent="center"
      alignItems="center"
      boxSize={resolvedSize}
      borderRadius="100%"
      color={color}
      backgroundColor={backgroundColor}
      {...boxProps}
    >
      {imageUnavailable && (
        <Text
          color="inherit"
          opacity={0.9}
          fontSize={Math.floor(parseInt(resolvedSize as string, 10) / 2)}
          fontWeight="500"
        >
          {initials}
        </Text>
      )}
      {!imageUnavailable && (
        <Img
          objectFit="cover"
          width="100%"
          height="100%"
          borderRadius="100%"
          overflow="hidden"
          src={src}
          onError={() => setImageUnavailable(true)}
        />
      )}
    </Flex>
  )
})
```

**Comment by aaronmcadam** [comment]
Thanks, @mshwery!
