### ISSUE TITLE
[Radio/RadioGroup] Inconsistent behaviour with attribute name

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#1491]
Both `RadioGroup` and `Radio` accept the `name` attribute.
`RadioGroup` currently [lacks props documentation](https://next.chakra-ui.com/docs/form/radio#props) in the docs.

- 🎉 with the same `name` on `RadioGroup` and `Radio`: works as expected 
- ⚠️ with different: `RadioGroup` takes precedence, needs docs

- 🐛 _omitting_ `name` on `RadioGroup`, having `name` on `Radio`: adds `radio-undefined` through the `RadioGroup` I assume and `radio-1` for the `Radio`, ignoring `name` attribute (bug)  

- 🎉 _omitting_ `name` on `Radio`, having it on `RadioGroup: works as expected  

❓ _however_ everything is always prefixed with `radio-` 

https://codesandbox.io/s/strange-williams-zidz4?file=/src/App.tsx

**Expected Behavior**
1. no prefixing with `radio-` as the consumer would have to sanitize
2. no `radio-undefined` coming up
3. when using `RadioGroup` without `name` and `Radio` with `name`, `name` of the `Radio` should be just the value of `name`. Right now, it's `radio-1`.

**Solution**
1. probably done by removing `radio` as parameter [here](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/radio/src/use-radio-group.ts#L80)
2. ^ that would also fix the `radio-undefined` issue, as [`radio` checks for `group?.name || props?.name`](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/radio/src/radio.tsx#L61)
3. couldn't trace down where the number comes from...

**Comment by erlendfh** [comment]
I second this, this prefix is causing a lot of headaches when integrating with other form libraries like `react-hook-form` and `yup`.

**Comment by segunadebayo** [comment]
I agree @ljosberinn, and thanks for catching this. I just pushed a fix for this.
