### ISSUE TITLE
Request to add guildlines for building custom component

### ISSUE THREAD

**Issue by Rafi993** [chakra-ui/chakra-ui#1495]
**What problem does this feature solve?** 
Chakra UI might not be able to build out all the components that is needed by the user. So it would be nice if the Chakra UI provides some guidelines to build custom component so that plays out well with the Chakra UI components. 

**What does the proposed API look like?** 
The documents can specify props that the custom component should have (like props relating to theme, margins etc..). and also basic guidelines to make sure that component is accessible.

**Describe alternatives you've considered** 
Provide typescript interface that custom components should follow

**Additional context** 
Since Chakra UI cannot have all the components everyone needs it is better if we provide documentation to build custom components that works well with Chakra UI

**Comment by ljosberinn** [comment]
Hi,

I think this would already be covered by the `Guides` section of the docs: https://next.chakra-ui.com/guides which will surely be expanded.

**Comment by Rafi993** [comment]
Awesome. But I couldn't find any information there relating to creation of custom components. It should probably be added there.

**Comment by ljosberinn** [comment]
Right now, there's none, yes. But I personally plan on adding some in the future. Would that solve the issue?

**Comment by Rafi993** [comment]
Awesome. Thanks @ljosberinn

**Comment by with-heart** [comment]
Hi Rafi, I added this to the guides ideas thread (#811). Going to close this for now as this is definitely something we want to add in the future :)
