### ISSUE TITLE
[InputElement] Shows up on top of modals (v1)

### ISSUE THREAD

**Issue by selbekk** [chakra-ui/chakra-ui#1497]
**Describe the bug** 

`InputLeftElement` and `InputRightElement` shows up through modals.

Reproduction: https://codesandbox.io/s/amazing-chatterjee-zoqww?file=/src/App.js

This is due to the `InputElement` components receiving a [z-index of 2](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/input/src/input-element.tsx#L16). 

This could be solved in one of two ways. 

1. Remove the z-index if it's not needed
2. Add a higher z-index to the modal overlay component

I'd be willing to create a pull request of either - please let me know what you think is the appropriate approach.

**Comment by ljosberinn** [comment]
Thank you for filing this issue.

An alternative approach would be using the `<PortalManager />` and setting a default `z-index` of some value. There's a PR (#1398) and an issue (#1394) for this topic to open up the API surface of `ChakraProvider` for this purpose.

Which approach would you prefer?

**Comment by selbekk** [comment]
My current workaround is just applying a `zIndex="0"` to the `InputElement` component. 🤷  This sort of stuff should just work out of the box though imo.

**Comment by ljosberinn** [comment]
Absolutely! Fix would be very easy too, but there probably was a reason why [this ](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/input/src/input-element.tsx#L16)line was added in the first. place. We'll investigate 👍

**Comment by selbekk** [comment]
Thanks! Sorry, didn't intend to sound so direct. :) Thanks for a great product!

**Comment by with-heart** [comment]
That `z-index` has been in place for a very long time. I'm not sure why it was originally added but it doesn't seem like it's needed. I'll open a PR and have Segun take a look.
