### ISSUE TITLE
node_modules/@chakra-ui/core/dist"' has no exported member 'AccordionIcon

### ISSUE THREAD

**Issue by revskill10** [chakra-ui/chakra-ui#15]
I followed the docs, and trying Accordion example. But i got the error

```js
node_modules/@chakra-ui/core/dist"' has no exported member 'AccordionIcon
```

The code is
```js
import {
  Box,
  Accordion,
  AccordionItem,
  AccordionHeader,
  AccordionPanel,
  AccordionIcon
} from "@chakra-ui/core";
```
Am i missing anything here ?

Thanks you for great library.

**Comment by segunadebayo** [comment]
Thank you for this issue. I didn't include the type definition for AccordionIcon hence the reason for the error. It still works if you use it though: https://pomi8.csb.app/

I've added the type definition for AccordionIcon and will release a patch soon.

Thank you @revskill10

**Comment by arnaudjnn** [comment]
I have the same error with ```AccordionHeader```. What do I need to do?

**Comment by abbaxee** [comment]
I also have the same issue `AccordionHeader`.

**Comment by with-heart** [comment]
There is no `AccordionHeader` component in v1, which would explain the error. https://next.chakra-ui.com/docs/components/accordion
