### ISSUE TITLE
Question: how to consistently theme elements while using color mode?

### ISSUE THREAD

**Issue by vbosch** [chakra-ui/chakra-ui#150]
Hi,

First of all I would like to apologize if this is not the correct way to ask questions of how to use the library but I have been unable to think of an answer from reading the web documentation. Please let me know if there is another way/channel to perform this question. 

I am in the middle of setting up the foundations for a new web and have moved from Material-UI to Chakra-UI because I love the simplicity of how things can be composed and feel less boilerplaty. I have an issue with the theme and color mode options.

How should I go about to for example apply a unique color to all UI elements (lets say teal) without having to define it as the color or variant for each component ? I could do this with my own context provider but I am left out thinking if there is a better way by modifying the theme object. 

Is this the only way (taken from the chakra ui web)  to go forward also to apply color mode themes to components: 
`function StyleColorMode() {
  const { colorMode, toggleColorMode } = useColorMode();
  const bgColor = { light: "red.500", dark: "red.200" };
  const color = { light: "white", dark: "gray.800" };

  return (
    <>
      <Box flex="1" mb={4} bg={bgColor[colorMode]} color={color[colorMode]}>
        This box's style will change based on the color mode.
      </Box>
      <Button size="sm" onClick={toggleColorMode}>
        Toggle Mode
      </Button>
    </>
  );
}`

In Material UI you can specify a primary and secondary color for light and dark mode and they are applied consistently to everything. I am somehow not able to understand from the docs if there is a way to do so in Chakra-UI (except rolling my own but I don't want to reinvent the wheel if I don't have to).

Thank you for your time. 
V.

**Comment by segunadebayo** [comment]
Hi Vicente,

At the moment, that's the only way to change the color for light and dark mode. As you'll see in the docs, this part is still a work in progress. Going forward we might use `theme-ui` to help manage the color modes.

Kindly find a walkaround for now, and if you think it makes sense to use your walk around in the library, please post it here so we can take a look.

Thank you using Chakra UI.

**Comment by vbosch** [comment]
Hi Segun, 

I wanted to be able to change later from a profile menu the fonts and color config so I created a theme object extending the default one and a color object for dark and light color config and allow users to consume and modify it with a hook: (I know I might be duplicating the actual Chakra-UI useTheme hook functionality but I wanted to have it all in one context) 

`const themeObject = {
  ...InitialTheme,
  colors: {
    ...InitialTheme.colors,
  },
  fonts: {
    body: 'Cardo',
    heading: 'Oswald',
    mono: 'Cardo',
  },
};

const colorModeObject = {
  bgColor: { light: 'teal.500', dark: 'teal.300' },
  color: { light: 'white', dark: 'white' },
  variantColor: 'teal',
};

//const themeObject = InitialTheme;

const ThemeProvider = (props) => {
  const [theme, setTheme] = useState(themeObject);
  const [color, setColor] = useState(colorModeObject);

  return (
    <ThemeContext.Provider
      value={{ theme, setTheme, color, setColor }}
      {...props}
    />
  );
};`

An example of using the context in my toggle button: 

`const DarkModeToggle = () => {
  const { colorMode, toggleColorMode } = useColorMode();
  const { color } = useTheme();
  return (
    <Tooltip
      hasArrow
      label="Toggle dark mode"
      placement="bottom"
      bg={color.bgColor[colorMode]}
      color={color.color[colorMode]}
    >
      <IconButton
        ml="10px"
        mr="10px"
        variant="outline"
        onClick={toggleColorMode}
        variantColor={color.variantColor}
        aria-label="Toggle dark mode"
        icon={colorMode === 'light' ? 'moon' : 'sun'}
      />
    </Tooltip>
  );
};`

This way, I can just set all components to the color and variant as per the object (vs coding color values on each component use) and later I will allow users to change the "accent color" via the useColor hook (kinda like on twitter).  Maybe I am being idiotic about the solution so if you have a better idea of how to do this with the actual theme object please let me know I would greatly appreciate it. 

Regards,
V.

**Comment by Martinnord** [comment]
Hey @segunadebayo. 

I've decided to go with your package for my next project. I've only used it for a couple of hours and I must say that this is one of my favorite React components libs.

I'm also interested if there's any update on this question. Since I'm feeling that I keep repeating myself for keeping the color scheme based on the mode.

Regards, Martin.

**Comment by segunadebayo** [comment]
Hi @Martinnord. I'm glad to hear that you like Chakra UI.

To be honest, I haven't given this much thought. I'll look into it once I complete the TypeScript migration. I understand it's a pain to keep repeating that.

I'm thinking we'll need a convenient way to consume a color mode specification. For example, I assume you'd do this most of the time.

```js
const bgColor = { light: 'teal.500', dark: 'teal.300' }
const color =  { light: 'white', dark: 'white' }
```

So we just need a way to consume this, in a more convenient way. We could do:

```jsx
const [bgColor, color] = useMode({light: `teal.500`, dark: `teal.300`},  { light: 'white', dark: 'white' })
```

Let me know what you think.

Happy holidays 😄

**Comment by tuttieee** [comment]
Hello @segunadebayo,
first of all, I appreciate your great work. I recently started using Chakra and love its simple and clean design.

Then I faced the color mode problem exactly stated in this thread.
I want to define consistent color palettes per color mode to be consumed by Chakra's all components and a way to access the palettes in user-defined components.

I think the strategy you mentioned in https://github.com/chakra-ui/chakra-ui/issues/150#issuecomment-538931742 using `theme-ui` is preferable IMO. Styled System also provides a similar way: https://styled-system.com/guides/color-modes/
and [Sancho UI](https://sancho-ui.com/), which is not so famous but I like and am using, takes a similar strategy and I like it.

While I think you already thought on this topic repeatedly, I hope this post is somewhat useful.

In addition, could you reopen this issue so that we can track it?

Thank you.
