### ISSUE TITLE
[Button] [v1] Does not correctly apply colorScheme WITH shade

### ISSUE THREAD

**Issue by mikereinmiller** [chakra-ui/chakra-ui#1501]
**Describe the bug** A clear and concise description of what the bug is.

When using the Button component and applying a colorScheme it works as intended.

For example `<Button colorScheme='teal'>`. 

The problem is when trying to apply a shade to the button, like `<Button colorScheme='teal.500'>`.  This will not render the appropriate color.

Currently using 
    "@chakra-ui/core": "^1.0.0-rc.0",
    "@chakra-ui/theme": "^1.0.0-rc.0",

**Expected Behavior** A clear and concise description of what you expected to
happen.

According to the colorScheme, props in the documentation.  The shade should be applied.  
https://next.chakra-ui.com/docs/form/button#props

**Steps to Reproduce** Clear and concise reproduction instructions are important
for us to be able to triage your issue in a timely manner.

1. Use Button component
2. Apply colorScheme with shade: `<Button colorScheme='teal.500'>Teal Button</Button>`
3. The color will not be applied

**Comment by ljosberinn** [comment]
https://codesandbox.io/s/heuristic-driscoll-fjpjk?file=/src/App.tsx sandbox

**Comment by dodas** [comment]
Is this really supposed to work?

Currently, Chakra is using different shades of selected color scheme for different purposes.
For example, shade `200` is used as Button's background color, `300` for hover state and `400` for active state.
I'm not sure how this would work if specifying shades was supported.

**Comment by mikereinmiller** [comment]
@dodas If this is not intended for version 1.0+, the docs should at least be adjusted to not reference shades in the prop descriptions.  https://next.chakra-ui.com/docs/form/button#props

**Comment by with-heart** [comment]
> @dodas If this is not intended for version 1.0+, the docs should at least be adjusted to not reference shades in the prop descriptions. https://next.chakra-ui.com/docs/form/button#props

Agreed. That's more ambiguous than it needs to be. Will fix
