### ISSUE TITLE
[MenuItem] No event when clicking with keyboard

### ISSUE THREAD

**Issue by liamross** [chakra-ui/chakra-ui#1502]
**Describe the bug**

When you use keyboard (<kbd>space</kbd> or <kbd>return</kbd>) to click a focused menu item, the event `onClick` is called with is `undefined` rather than a `MouseEvent`.

**Expected Behavior**

Like a native component, I would expect it to emit a `MouseEvent` (even though it's a keyboard event obviously, it seems like native components emit MouseEvents regardless of what causes the `onClick` to fire).

**Link to minimal reproduction**

https://codesandbox.io/s/chakra-menu-item-bug-24wy2

**Steps to Reproduce**

1. Open code sandbox link
1. Open the console
1. Open the menu in the codesandbox
1. Use keyboard to navigate between items
1. "Click" them using space or return keys
1. See that "undefined" is logged

**Suggested solution(s)**

Properly emit the event rather than undefined. Since the event is emitted by default from native elements, simply emit it rather than emitting undefined when using keyboard navigation.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: all browsers
- Version: all versions

**Additional context**

This breaks functionality with Next.js `Link` component, since `Link` relies on correct events being emitted from `onClick` in order to override the behaviour. As a result, if you wrap a `MenuItem` in a Next.js `Link`:

```ts
<Link href="/account" passHref>
  <MenuItem as="a">Menu item</MenuItem>
</Link>
```

and then use the keyboard to click and event is undefined, it breaks on this line inside of Next.js `Link`:

```ts
// Breaks here, since `e` is undefined.
if (!e.defaultPrevented) {
  linkClicked(e, router, href, as, replace, shallow, scroll)
}
```

**Comment by segunadebayo** [comment]
Hi @liamross, thanks for catching this.

We've fixed this in the v1 pre-release which we hope to get out over the next 1-2 weeks. It'll emit the correct events as described.

Cheers
