### ISSUE TITLE
[Icons] Missing peer dependency of @types/react

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#1503]
Without the dependency `@types/react` of `^=16.9.21`, using any exported icon of `@chakra-ui/icons` will throw a TS error about missing property `path`.
It may be circumvented with `path={undefined}`, however it's entirely resolved by installying any version above the mentioned.

This should be added to the peer dependencies of `icons`.

**Comment by segunadebayo** [comment]
Done!
