### ISSUE TITLE
[Menu] the new doc site does not reflect submemu status

### ISSUE THREAD

**Issue by wuweiweiwu** [chakra-ui/chakra-ui#1506]
**Describe the bug** 

- https://github.com/chakra-ui/chakra-ui/commit/5a573c6ecc0a331897d93104d9abdaacdc50525c#diff-70ae624a9f188d0075cd0d22c6743311 removes submenu functionality
- https://next.chakra-ui.com/docs/components/menu#nested-menus still shows it as a working example which I believe is not the case

**Expected Behavior** 

- docs should reflect that submenus are not currently working

**Comment by ljosberinn** [comment]
Thank you for the issue! We are aware, the docs are currently being reworked with next in a separate branch.

**Comment by with-heart** [comment]
It'll be fixed whenever the docs are deployed again

**Comment by with-heart** [comment]
Deploying now, so it should this will be resolved shortly!
