### ISSUE TITLE
[Idea] Gatsby integration for Chakra UI

### ISSUE THREAD

**Issue by alexluong** [chakra-ui/chakra-ui#151]
Hey there,

I'm building a Gatsby theme/plugin integration for Chakra UI so that people can just install that package and have Chakra set up right away.

Would you like that package to be hosted under this repo? If not, I can create a repo for it instead.

**Comment by segunadebayo** [comment]
This sounds like a good idea, Alex. Let's have in the repo.

What do I need to do for you be able to add it? Add you as an outside collaborator, correct?

**Comment by segunadebayo** [comment]
@alexluong, I curious if you'd be able available to resolve any issues or PR related to this going forward.

**Comment by alexluong** [comment]
You don’t have to do anything. I’ll make a PR once it’s ready!

And yeah I’d be happy to help going forward.

With that said, should I publish the package to npm or you?

**Comment by segunadebayo** [comment]
Sounds good.

I'll publish the package to npm once it's ready and tested.

Thanks for this Alex.

**Comment by alexluong** [comment]
As I'm building the Gatsby theme in `packages/gatsby-theme-chakra-ui`, would you mind if I create an `examples/gatsby-starter-chakra-ui` directory that make use of that new package?

An alternative is that I create an outside Gatsby project and symlink it with this package. The idea is that when you test out the package, hopefully having the example can make it a bit easier for you.

**Comment by segunadebayo** [comment]
That sounds good. Let's have it in `examples/gatsby-starter-chakra-ui`. I'm currently using a similar structure to test the core library in Typescript.

**Comment by kripod** [comment]
Great initiative!

@segunadebayo May I ask you to publish `gatsby-plugin-chakra-ui` on npm? I am very curious about this new approach.

**Comment by alexluong** [comment]
@kripod the [package](https://npmjs.com/package/gatsby-plugin-chakra-ui) is published 🎉 Thank you @segunadebayo

**Comment by segunadebayo** [comment]
@alexluong, you're welcome. I'll post about it soon and mention you.

Thanks for your work on this.

**Comment by kripod** [comment]
@alexluong Awesome work! However, shadowing the theme with a TypeScript file (`theme.ts` or `theme.tsx`) doesn't seem to work.
