### ISSUE TITLE
[V1] Can't start V1 create-react-app template

### ISSUE THREAD

**Issue by leadream** [chakra-ui/chakra-ui#1522]
**Describe the bug** A clear and concise description of what the bug is.

I just run `yarn create react-app my-app --template @chakra-ui` to create a project but it can't be started when executing `yarn start`. It throws an error below:

![image](https://user-images.githubusercontent.com/12868055/89367435-96a18000-d70b-11ea-8c7b-6c122d5e62aa.png)

Is there some steps I missed?

**Comment by leadream** [comment]
downgrade to 1.0.0-next.3 can fix it.
![image](https://user-images.githubusercontent.com/12868055/89371351-b3db4c00-d715-11ea-8344-e163080635c8.png)

**Comment by with-heart** [comment]
Going to close this in favor of #1534. Unfortunately the Chakra package versions aren't being updated automatically in the templates, so this isn't working well. You should also be able to upgrade them to `1.0.0-rc.0` to get the latest.
