### ISSUE TITLE
[Help] How to have a button as an anchor + use external routing lib?

### ISSUE THREAD

**Issue by yuyao17** [chakra-ui/chakra-ui#1532]
**Describe the bug** A clear and concise description of what the bug is.

Using the Link component, we can use a routing lib like React Router like so:

```js
<Link as={ReachLink} to="/home">
  Home
</Link>
```

But is there a way to have a button acting as an Link with external routing lib? We can't do this:

```js
<Button as="a" as={ReactLink} to="/home">
 Home
</Button>
```

Any help appreciated!

**Comment by with-heart** [comment]
Hi @yuyao17! You can use two layers of components using `as` to create this effect: https://codesandbox.io/s/loving-dew-221k0?file=/src/App.tsx
