### ISSUE TITLE
Update CRA `template.json` package versions

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1534]
The CRA templates are correctly version-incremented when we publish, but unfortunately due to the way templates work, dependencies are not listed in `package.json` but `template.json`. We should instead use `^1.0.0@next` to make sure these versions track with the latest changes.

**Comment by with-heart** [comment]
Once this is merged, need to make sure to add a note to #1329 to change the versions to `^1.0.0@latest` so 1.0 release works correctly.

**Comment by segunadebayo** [comment]
Done!
