### ISSUE TITLE
yarn add @chakra-ui/core failed with 404 response

### ISSUE THREAD

**Issue by ima-s** [chakra-ui/chakra-ui#1535]
**Describe the bug**

`yarn add @chakra/ui-core` failed with following error.

```
error An unexpected error occurred: "https://registry.npmjs.org/@chakra-ui%2ftheme-tools: Not found".
```

**Expected Behavior** A clear and concise description of what you expected to
happen.

**Link to minimal reproduction** 

`yarn add @chakra-ui/core` throws error.

**Steps to Reproduce** Clear and concise reproduction instructions are important
for us to be able to triage your issue in a timely manner.

**Suggested solution(s)**

**Desktop (please complete the following information):**

**Additional context** Add any other context about the problem here, or some
background information of how you ran into this bug.

**Comment by ljosberinn** [comment]
Most likely a network failure, please try again. You can open https://registry.npmjs.org/@chakra-ui%2ftheme-tools yourself and see it's available.

**Comment by neighborhood999** [comment]
Check [npm status](https://status.npmjs.org/):

> Issues accessing npmjs.com and installing scoped packages

**Comment by ima-s** [comment]
@ljosberinn 

Oh, sorry.
This error was caused by npm, not by chakra.

Thank you for quick response!
