### ISSUE TITLE
[Popover] Popover dialog box is broken in IE 11

### ISSUE THREAD

**Issue by mohammed-adil** [chakra-ui/chakra-ui#1536]
**Describe the bug** 

- The `PopoverContent` gets squished/height does not get updated in IE 11
- Elements within the PopoverContent are not accessible

<table>
<tr>
<td>Chrome 84.0.4147.105</td>
<td><img src="https://user-images.githubusercontent.com/31363829/89538084-c2119100-d817-11ea-9ace-852dc298b094.png" /></td>
</tr>
<tr>
<td>Firefox 77.0.1</td>
<td><img src="https://user-images.githubusercontent.com/31363829/89537891-8d9dd500-d817-11ea-8d74-7b09b033fe07.png" /></td>
</tr>
<tr>
<td>Safari 13.0.5</td>
<td><img src="https://user-images.githubusercontent.com/31363829/89538130-cf2e8000-d817-11ea-964b-e079d36f38c2.png" /></td>
</tr>
<tr>
<td>IE 11</td>
<td><img src="https://user-images.githubusercontent.com/31363829/89538162-d9507e80-d817-11ea-929d-bdfc053ded02.png" /></td>
</tr>
</table>

**Expected Behavior** 

Expected `PopoverContent` container to have similar height/width value as of any other browser and also to be able to access the child elements

**Steps to Reproduce** 

1. Use `Popover` component
2. Add a popover trigger element (a button or link) with `trigger='click'`
3. If possible try to load the the page in IE 11
4. Click on the trigger element
5. See popover dialog opening but squished and elements are overflowing
6. Also observe elements within popover dialog are not accessible

**Additional context** 

Although I was able to fix height issue by adding a minHeight like `<PopoverContent minHeight="50px">`. I still can't access the elements within the Popover.

I do know chakra team has tons of other feature/fixes to be done than supporting IE 11 😞 . Any suggestion or workaround to fix this issue would be good enough for me

**Comment by with-heart** [comment]
Hi @mohammed-adil, what Chakra version are you using?

**Comment by mohammed-adil** [comment]
> Hi @mohammed-adil, what Chakra version are you using?

`"@chakra-ui/core": "^0.8.0"`

We haven't moved to chakra-ui v1 yet.

**Comment by segunadebayo** [comment]
I understand the need to support @mohammed-adil and I really wish we could but given the manpower and resource, it's really difficult to invest our efforts to support IE11.

Please try to see how you can help Mohammed via Discord or here @with-heart. For now, I'll close this.

**Comment by mohammed-adil** [comment]
@segunadebayo I understand you point of view, @with-heart do you think we can do some sort of workaround over this? cause I can see popper.js works fine in IE 11 and Popover component uses its API.

On a side note: None of the popover example from https://chakra-ui.com/popover gets triggered in IE 11
