### ISSUE TITLE
[Documentation] Error when access Tab component by search

### ISSUE THREAD

**Issue by adrianoresende** [chakra-ui/chakra-ui#1537]
# Describe the bug

When you use search to access the page `Tab`, I get a 404 error
https://next.chakra-ui.com/tabs#tabs

![image](https://user-images.githubusercontent.com/798755/89561449-e1e08f00-d7ee-11ea-8542-a5c03fc6faf8.png)

The link is incorrect, I think the correct is `https://next.chakra-ui.com/docs/components/tabs`

# Steps to Reproduce** 

1. Search "tab"
1. Page 404 error

**Comment by jmiazga** [comment]
Thanks @adrianoresende for reporting this. I believe this is caused because the search is still indexing https://chakra-ui.com and not https://next.chakra-ui.com

**Comment by with-heart** [comment]
@jmiazga That's correct. Searching is currently broken for that reason.

We'll probably disable it until we move the 1.0 docs to chakra-ui.com to avoid confusion! Thanks for reporting @adrianoresende!
