### ISSUE TITLE
Tabs: is there a way to opt out of triggering tab switching for elements within the  TabList?

### ISSUE THREAD

**Issue by aaronmcadam** [chakra-ui/chakra-ui#154]
CodeSandbox: https://codesandbox.io/s/chakra-js-starter-w4vym

In my UI, I need an edit button that edits the tabs themselves.

When clicking on this button, my behaviour triggers, but it also tries to switch the tab to an empty state (because there isn't a 3rd tab, I'm guessing). Even with controlled state, the tab still switches. So in my `onClick` handler, I'm setting the `tabIndex` to the current one that I'm tracking in local state.

I appreciate this use case might be a little bit advanced, but I didn't want to resort to rendering the edit button outside of `TabList` and then absolutely positioning it so that it looks like it is within the tab list element.

**Comment by segunadebayo** [comment]
I'm not sure I understand this use case very well. Perhaps, you could add the modal that edits the task so I can get the full context. Then list out the expected behavior

**Comment by segunadebayo** [comment]
@aaronmcadam, did you manage to figure this out?

**Comment by aaronmcadam** [comment]
@segunadebayo no, I just didn't have a need to implement this anymore in my project. Thanks for following up.

**Comment by abubakar471** [comment]
> https://chakra-ui.com/docs/disclosure/tabs#controlled-tabs will help?

great, brother. it worked
