### ISSUE TITLE
Emotion Source mapping support

### ISSUE THREAD

**Issue by webegguk** [chakra-ui/chakra-ui#1541]
Are there any plans to support emotion source mapping as per docs here: https://emotion.sh/docs/source-maps?

Chakra UI looks perfect for getting a design system underway. It's so flexible and simple & I can see it supports adding emotion css labels which is great. Source mapping is the only thing missing for me.

**Comment by with-heart** [comment]
@segunadebayo What do you think?

**Comment by probablyup** [comment]
It looks like the "instances" feature of `babel-plugin-emotion` needs to be configured for this to work

**Comment by with-heart** [comment]
Going to close this as part of our backlog cleanup as the team has no plans to implement this anytime soon.

**Comment by wasinsandiego** [comment]
Is this really not supported? On by default in emotion. Is there a way we can make this work with Chakra?

**Comment by arielalvarez882** [comment]
I need this :(
