### ISSUE TITLE
[Progress] documentation seems broken in 1.0

### ISSUE THREAD

**Issue by ivan-dalmet** [chakra-ui/chakra-ui#1542]
Just a quick feedback, the display of the Progress component seems broken on the 1.0 documentation ;) 
https://next.chakra-ui.com/docs/components/progress

[update] I've tested in my app with `1.0.0-rc.1` and it seems to be ok. So it's just a documentation problem I think ^^

![image](https://user-images.githubusercontent.com/9749061/89634618-faf84700-d8a5-11ea-8416-9c762b9fc43d.png)

(Chrome 84.0.4147.105 on Mac OS)

**Comment by ljosberinn** [comment]
Thank you, the docs are currently outdated anyways so I presume this to be fixed with the docs rewrite in nextjs. Leaving this open until it's definitely resolved.

**Comment by segunadebayo** [comment]
I just looked into this and fixed the issues I found.

Thanks for catching this @ivan-dalmet
