### ISSUE TITLE
[Input] type="date" does not display date when defaultValue is set to a Date type

### ISSUE THREAD

**Issue by HadiSDev** [chakra-ui/chakra-ui#1549]
The vanilla input component in ReactJs accepts defaultValue to be of type Date when input type Is set to "date". However <Input/> component does not do anything if a Date object is provided in the defaultValue field. So it just renders "dd/mm/yyyy" instead of the actual date.

    <Input type="date" defaultValue={new Date()}/>
![image](https://user-images.githubusercontent.com/10367624/89662246-15491980-d8d4-11ea-8917-e0eb8b2a9dfb.png)

**Expected Behavior** A clear and concise description of what you expected to
happen.

Should be like:
![image](https://user-images.githubusercontent.com/10367624/89662276-209c4500-d8d4-11ea-8f49-5b1c4559af02.png)

**Desktop (please complete the following information):**

- OS: Win 10
- Browser Edge (chromium)
- Version 84.0.522.52 (Official build) (64-bit)

Chakra Version is rc.1

**Comment by ljosberinn** [comment]
Hi - thanks for filing the issue!

This is not a bug, as its default behaviour:

![image](https://user-images.githubusercontent.com/29307652/90185785-76cb2580-ddb7-11ea-87ed-8897addda974.png)

React will call `.toString()` when you pass `new Date()` which leads to an invalid value.
