### ISSUE TITLE
[Tooltip] crashes Chrome on OS X

### ISSUE THREAD

**Issue by marianorodriguez** [chakra-ui/chakra-ui#1550]
**Tooltip component is making the browser page to hang when setting property `label`**

You can check it on this sandbox:
https://codesandbox.io/s/dreamy-proskuriakova-9cykp

When you move the cursor over the buttons, the page freezes and you are forced to reload/close the tab.
When you remove the property `label` from each Tooltip it works as expected 

**Desktop:**
- OS: macOS 10.15.6
- Browser: Chrome v84.0.4147.105

**Additional context** This seems to work on latest versions of Safari and Firefox. We started noticing this on the upgrade from `^1.0.0-rc.0` to `^1.0.0-rc.1`

**Comment by segunadebayo** [comment]
Thanks for reporting this regression @marianorodriguez.

I've just resolved it and we'll release a new `rc` shortly.

**Comment by with-heart** [comment]
@segunadebayo What ended up being the issue there?

**Comment by santialbo** [comment]
I'm also very curious about what the issue was.

**Comment by ljosberinn** [comment]
looks like enter/exitTimeouts being fired way too often and never getting cleared: https://github.com/chakra-ui/chakra-ui/commit/bac082373de41243b84f19385d45427afcb4f2db#diff-781809a0aa0c77f50bdb483e87664baf
