### ISSUE TITLE
[Modal] Transition is disabled by default, yet docs mention default fade transition

### ISSUE THREAD

**Issue by dmitru** [chakra-ui/chakra-ui#1551]
**Describe the bug** 

Modal component doesn't have transitions enabled by default.
Docs don't explain how to enable them.

**Expected Behavior** 

Modal should probably have transition by default, and the docs should mention how to opt-out or tweak it.

**Link to minimal reproduction** 

https://next.chakra-ui.com/docs/components/modal

**Steps to Reproduce** 

Open Modal docs (https://next.chakra-ui.com/docs/components/modal), click on any button to make the modal appear. Observe no transition.

**Comment by segunadebayo** [comment]
Good catch @dmitru.

We'll update the docs shortly

**Comment by jmiazga** [comment]
@segunadebayo Do we want to add a default transition to the `Modal`? (i don't think the `AlertDialog` has a transition out of the box)

Either way I'll make sure the docs are correct for `Modal` and `AlertDialog`
