### ISSUE TITLE
Request to allow Modal and AlertDialog to be triggered programmatically

### ISSUE THREAD

**Issue by timkindberg** [chakra-ui/chakra-ui#1554]
**What problem does this feature solve?**
Modals (and AlertDialogs, but I'll just say modals from here on out) that require user confirmation before a form saves would be easier if they were triggered programmatically. This way they can be easily added/removed without having to wire up the form submission in a completely different way. Often form libraries assume you will hook the submit button up directly to the library's `onSubmit` handler. So if you want to insert a confirmation beforehand you have to do something like the following (I'm using Formik here):

Current Approach:
```js
const Form = () => {
  // Control show and hide of confirmation
  const [showConfirmation, setShowConfirmation] = useState(false)

  // Store submit args here... hacky
  const formSubmitRef = useRef({})

  const onSaveAttempt = (values, { setSubmitting, resetForm }) => {
    formSubmitRef.current = { values, setSubmitting, resetForm }
    setShowConfirmation(true)
  }

  // The `isConfirmed` is passed as true or false to indicate if the user clicked OK or Cancel
  const onSaveConfirmation = async isConfirmed => {
    // Retrieve submit args
    const { values, resetForm, setSubmitting } = formSubmitRef.current
    // ... continue with submission
  }

  return (
    <>
      <AlertDialog isOpen={showConfirmation} onClose={onSaveConfirmation} />
      <Formik onSubmit={onSaveAttempt}> ... </Formik>
    </>
  )
}
```

**What does the proposed API look like?** 
So instead I'd like to just hook up my form normally and use async/await programmatic logic to trigger the modal and await the user's choice. Something like this:

New Approach:
```js
const Form = () => {
  const showModal = useModal()

  // Notice how we just have our normal Formik submit handler now with normal args
  const onSave = async (values, { resetForm, setSubmitting }) => {
    const modal = await showModal()
    // modal.response would be the user's choice, not sure how it would be achieved
    // modal.close would close the modal
    // perhaps other convenient properties or methods?
    // ... continue with submission
  }

  return (
      <Formik onSubmit={onSave}> ... </Formik>
  )
}
```

**Describe alternatives you've considered**
We used to use Sweet Alert 2.0 which functioned like this and it was quite convenient.

**Additional context**
I'm not quite sure:
1. where to provide the JSX for the modal. The only places that make sense are during `useModal(...here...)` or `await showModal(...here...)`
2. how to wire up the user's response to `modal.response`

**Comment by segunadebayo** [comment]
Hi @timkindberg,

I think your current approach works pretty well if you ask me.  I don't see us implementing something like this for now. 

Controlling the modal's `isOpen` state yourself and managing your custom use-case is probably the best way for us to stick with.

Permit us to leave this as is, we might consider this in the future.

Thank you.
