### ISSUE TITLE
[v1] getting started instructions not working with Typescript

### ISSUE THREAD

**Issue by vonwao** [chakra-ui/chakra-ui#1556]
**Describe the bug** 

followed the getting started instructions
https://next.chakra-ui.com/docs/getting-started

**Expected Behavior** 

The app should work, or at least give a more helpful/meaningful error

**Link to minimal reproduction** Please provide a codesandbox link or GitHub
repo with a minimal reproduction of the issue.

```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import { ChakraProvider, CSSReset } from "@chakra-ui/core"
import theme from "@chakra-ui/theme"
import { Flex, Box, Text, Button, Heading } from '@chakra-ui/core';

ReactDOM.render(
  <React.StrictMode>
      <ChakraProvider theme={theme}>
          <CSSReset />
          <Text>Hello Chakra</Text>
      </ChakraProvider>
  </React.StrictMode>,
  document.getElementById('root')

```

**Steps to Reproduce** 

1. create new app with cra:
npx create-react-app my-app --template typescript

2. follow instructions in https://next.chakra-ui.com/docs/getting-started

**Additional context** 

![image](https://user-images.githubusercontent.com/377000/89674980-2172ae00-d8b7-11ea-9054-40d1a4900e6f.png)

**Comment by ljosberinn** [comment]
Hi thanks for filing an issue!

However, I'm confused, what error are you seeing? I followed the steps you provided and also altered the typescript version as you did in your package.json and don't see any errors.

_That said_, we're currently refactoring the docs, so it definitely is a little outdated in general.

**Comment by segunadebayo** [comment]
Seems to work for me as well. Please re-open once we can get a reproduction.
