### ISSUE TITLE
[Drawer] Overflow not scrollable

### ISSUE THREAD

**Issue by panbanda** [chakra-ui/chakra-ui#1557]
When content extends beyond the Y axis on a drawer it is not scrollable.  I would expect a scrollbar within the div itself.

I am using the `1.0.0-next.7` branch for core, themes and theme-tools.

```

      <Button colorScheme="green" onClick={onOpen}>
        <FaPlus /> Create Project
      </Button>
      <Drawer isOpen={isOpen} placement="right" onClose={onClose} size="lg">
        <DrawerOverlay />
        <DrawerContent>
          <DrawerCloseButton />
          <DrawerHeader>{t('projects.create-project')}</DrawerHeader>

          <DrawerBody>
            ... long content here
          </DrawerBody>
        </DrawerContent>
      </Drawer>
```

![Screenshot 2020-08-07 at 9 17 44 PM](https://user-images.githubusercontent.com/150944/89676155-d32fd000-d8f3-11ea-9581-4ea90366515b.jpg)

I have tried overflow: scroll/visible/etc. and none of those are working for the containers etc.

**Comment by segunadebayo** [comment]
Hi @panbanda,

Thanks for this issue.

First of all the structure of components have changed in `v1`, here's what it looks like:

```jsx
<Drawer size="lg">
 // overlay now wraps the entire content
  <DrawerOverlay>
    <DrawerContent>
      <DrawerCloseButton />
      <DrawerHeader>{t("projects.create-project")}</DrawerHeader>
      <DrawerBody>... long content here</DrawerBody>
    </DrawerContent>
  </DrawerOverlay>
</Drawer>
```

Next, please upgrade to `1.0.0-rc.2` instead. We've made lots of improvements to the components.

I believe that should fix this issue you have, otherwise, I'll re-open.

Cheers

**Comment by kartset** [comment]
Use overflow='scroll' on DrawerContent and it will work. Like -

<Drawer size="lg">
 // overlay now wraps the entire content
  <DrawerOverlay>
    <DrawerContent overflow='scroll'>
      <DrawerCloseButton />
      <DrawerHeader>{t("projects.create-project")}</DrawerHeader>
      <DrawerBody>... long content here</DrawerBody>
    </DrawerContent>
  </DrawerOverlay>
</Drawer>

Cheers.

**Comment by imenelhakim** [comment]
change <DrawerContent> to <DrawerContent **overflow='scroll'**>

**Comment by nhydv** [comment]
scroll height =?
