### ISSUE TITLE
[Input] Always focuses the first input even with autoFocus={false} 

### ISSUE THREAD

**Issue by JClackett** [chakra-ui/chakra-ui#1559]
I noticed that when going to a new screen/modal/component etc if there is a group of inputs, it always autofocuses on the first input. I guess this is fine default behaviour, however if I pass autoFocus={false} it still autoFocuses and I can't figure out a way to disable it

happens on both safari and chrome 

**Suggested solution(s)**
Accept autoFocus={false} as a way to stop autofucusing inputs

- OS: MacOS
- Browser Safari
- Version rc.0

**Comment by with-heart** [comment]
Hi @JClackett! 

I tried to reproduce your issue and am seeing the correct behavior: https://codesandbox.io/s/pensive-roentgen-silbi?file=/src/App.tsx

Any way you could provide a reproduction where this is happening?

**Comment by JClackett** [comment]
I will get a repro!

**Comment by yujuiting** [comment]
> Hi @JClackett!
> 
> I tried to reproduce your issue and am seeing the correct behavior: https://codesandbox.io/s/pensive-roentgen-silbi?file=/src/App.tsx
> 
> Any way you could provide a reproduction where this is happening?

I found it's not work in Safari. Input still be focused when poped.

**Comment by JClackett** [comment]
Yeah @with-heart, can you repro it if you are on safari?

**Comment by Kruutus** [comment]
@JClackett Found the solution, it must be occuring when you are using a Modal component, in which case you should set autoFocus={false} on the Modal component itself.
`<Modal {...props} autoFocus={false}>
...
</Modal>`

**Comment by nico-k3** [comment]
@JClackett This same Fix works for Drawer's too

`<Drawer {...props} autoFocus={false}><DrawerContent> ... </DrawerContent></Drawer>`

**Comment by vuongtran** [comment]
It's work as well, big thank

**Comment by duncanmcdowell** [comment]
Just in case anyone ran into this on the popover component:

You can add `onOpenAutoFocus={(e) => e.preventDefault()}` to the `<PopoverContent>' element.

**Comment by tommywalkie** [comment]
For anyone running on issues with the `Drawer` component (on version `2.8.2`), note that there is a `trapFocus` prop with a default value of `true`, doesn't matter if `autoFocus` is set to `false`.

**Comment by nirajpdn** [comment]
The autoFocus issue in drawer is solved by setting:
`trapFocus: false`

**Comment by Hamza-HM** [comment]
I had this issue with the Dialog, and non of the above fixed it for me, i figured out another solution.
on the DialogContent component i did this   onFocusCapture={(e) => e.target.blur()} and it solved it.
