### ISSUE TITLE
[Documentation] Incorrect links to individual component examples

### ISSUE THREAD

**Issue by jaredjgebel** [chakra-ui/chakra-ui#1569]
The links to Github, npm, and Storybook for each individual component are directing me to the same page I was on in the docs, in a different tab. The behavior appears to be the same across Chrome, Firefox, and Edge.

To use the [Editable Text component](https://next.chakra-ui.com/docs/components/editable) as an example, each of the buttons for Github, npm, and Storybook link to "https://next.chakra-ui.com/docs/components/editable." I assume that each link should be pointing to the code for the component, the repo for the component, and the Storybook link for the component, respectively. I'd be happy to try and correct this myself.

**Comment by ljosberinn** [comment]
Thank you @jaredjgebel - we are aware and soon releasing a new version of the docs :) the docs suffered a bit during the iterations over the last few weeks but we're working on bringing them up to date again!
