### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by pnfcre** [chakra-ui/chakra-ui#157]
Hi there,

I found a small typo in the docs: https://chakra-ui.com/style-props#background
![image](https://user-images.githubusercontent.com/24176136/66338501-88df6a80-e941-11e9-9c02-62875cfe4c39.png)

`bgImage` translates to the invalid CSS property `bg-img` when rendered.

However, `bgImg` works just fine, as stated in the table below:
![image](https://user-images.githubusercontent.com/24176136/66338589-b5938200-e941-11e9-8278-7427c295197d.png)

Kind regards,
Casper.

**Comment by segunadebayo** [comment]
Thanks for catching this. I've fixed it and will release a patch soon.
