### ISSUE TITLE
Document Create new component requirements/process overview

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1570]
In order to enable the community to better contribute to the Chakra library, we need to document our expectations for the creation of new components/features.

Important items:

- accessibility/aria
- following Chakra component construction patterns (`useX` for behavior/props, context for sharing data inside composite components, etc.)
- usage of shared internal tools (`@chakra-ui/utils`)
- testing patterns
- documentation patterns

This issue is an umbrella issue for the purpose of discussing this topic and figuring out additional issues required to achieve this goal.

**Comment by vickywane** [comment]
Hi @with-heart , 

Inorder to improve my contribution to Open Sourced Projects, i would like to work you on this.

**Comment by with-heart** [comment]
@vickywane I would love to include you in this! As we figure out a plan for tackling this, I'll make sure you're involved in implementing it :)

**Comment by vickywane** [comment]
Thank you. 

I'd watch out for your plan!

**Comment by segunadebayo** [comment]
Working on this!

**Comment by vickywane** [comment]
Alright

**Comment by segunadebayo** [comment]
I've put a first draft there for now. We can improve as we go.
