### ISSUE TITLE
[Box] Property 'outline' should accept theme colors

### ISSUE THREAD

**Issue by FredyC** [chakra-ui/chakra-ui#1574]
**Describe the bug** A clear and concise description of what the bug is.

Using eg. `outline="red.500"` it's left as-is instead of transforming it to correct color.

**Expected Behavior** A clear and concise description of what you expected to
happen.

Color should be transformed.

@chakra-ui/core: 0.8.0

**Comment by with-heart** [comment]
Discovered an interesting issue. In `1.0.0-rc.2`, setting `outline` to a theme color displays the existing outline while also displaying a new outline but in a deep blue color and only when focused: https://codesandbox.io/s/loving-greider-fgveh?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/1954752/89736636-b7821200-da38-11ea-92c0-76b62af15d52.png)

Setting it to something like "3px dotted red" works as expected: https://codesandbox.io/s/romantic-architecture-kjtib?file=/src/App.tsx

Not entirely sure if this is a bug.

**Comment by FredyC** [comment]
I am not sure what you mean. Clearly the bug here is that `red.500` is not translated to correct color and the browser considers that invalid value and as such it will show default outline for the button.

**Comment by with-heart** [comment]
Ahh, what I meant was that this may be less of a bug and more of a new feature similar to `border`/`borderColor`/`borderStyle`. Setting `outline` to a color doesn't do anything by default, you'd need to have the other two:

https://codesandbox.io/s/jolly-banzai-j3utb?file=/src/App.js

**Comment by FredyC** [comment]
Maybe I am wrong, but isn't outline used by some accessibility devices which are able to focus paragraphs and other blocks?

**Comment by segunadebayo** [comment]
Hi @FredyC,

I agree with @with-heart. `outline` is a shorthand property for `outline-width`, `outline-color`, and `outline-style`. It depends on what you want to achieve.

- If you really need to set the outline color, I'd recommend you pass `outline: 2px solid`, and then `outlineColor: red.500`,
- If you wanted to change the outline around most Chakra components, I'd recommend you do so from `theme.shadows.outline`
- Finally, you can also try `borderColor`

As regards accessibility, the goal of an outline is to indicate where the user's focus is at any point in time. You can achieve that with any of the 3 options above.

Hope this helps.

Cheers.

**Comment by FredyC** [comment]
Well, so `outlineColor` and others are part of the upcoming 1.x only as it seems. I don't feel like upgrading just because of that and deal with other changes.

The `theme.shadows.outline` would be lovely as a unified way, but it only sets `box-shadow` property, not the `outline`.

And the border is not that great option either because sometimes I used it for a different thing.

I will cope somehow, just stating how it is.
