### ISSUE TITLE
Typescript error: Declaration or statement expected. TS1120

### ISSUE THREAD

**Issue by vickywane** [chakra-ui/chakra-ui#1575]
Hi , 

**Describe the bug**
I am starting off a new **typescript** react project bootstrapped using the Create-React-App. I am using the getting started guide found  [here](https://next.chakra-ui.com/docs/getting-started)

**Expected Behavior**
My project should compile successfully after **typechecking**. 
![chak-bug](https://user-images.githubusercontent.com/29664439/89733268-4cdad180-da4c-11ea-8359-b33c9f8439b8.png)

**Steps to Reproduce** 
Create a new react typescript project using the Create-React-App and add `@chakra-ui/core` following this guide  [here](https://next.chakra-ui.com/docs/getting-started) 

**A copy of my `App.js`**
![app js](https://user-images.githubusercontent.com/29664439/89733336-b0fd9580-da4c-11ea-950b-c2e1ecadfd5e.png)

**A cpoy of `tsconfig.json`**
`{
  "compilerOptions": {
    "module": "esnext",
    "target": "esnext",
    "jsx": "preserve",
    "lib": ["dom", "es2015", "es2015"],
    "strict": false,
    "noEmit": true,
    "experimentalDecorators": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "removeComments": true,
    "preserveConstEnums": true,
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "resolveJsonModule": true
  },
  "include": ["./src/**/*"]
}`

**Comment by ljosberinn** [comment]
This is create-react-app coming with an old version of typescript. Please update to `^3.8.0`.

**Comment by with-heart** [comment]
@vickywane See https://next.chakra-ui.com/docs/getting-started#typescript :)

**Comment by with-heart** [comment]
Also for an easier `create-react-app` setup, check out https://next.chakra-ui.com/guides/cra-templates. We have an official template you can use to generate your app!
