### ISSUE TITLE
Use TypeScript workaround to offer intellisense completion for complex types with string literals

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1580]
This idea comes from a suggestion by @sondh0127 in #1572. Similar to how `csstypes@^3.0.0` is using the workaround detailed in https://github.com/microsoft/TypeScript/issues/29729, we should update our complex types that include string literals with `| (string & {})` so that the strings are offered as intellisense completions.

**Comment by segunadebayo** [comment]
Given our agreed approach, let's close this out.
