### ISSUE TITLE
[ColorMode] localStorageManager hydration issues

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#1581]
When not explicitly using the `cookieStorageManager`, `localStorageManager` is used by default. Maybe this is not the right approach.

Given a Next app, in all cases (Server, Static, SSG), as soon as changing the color mode once (= not the initial value defined in the theme) and then refreshing the page, you'll always see a hydration warning or even visual discrepancies (e.g. a button still being in light mode when you're in dark). Any conditional logic based on color mode is thus affected.

Why is this? During export/SSR/SSG, knowledge about a users localStorage is obviously impossible. Thus the resulting HTML and CSS will be based on initial values.
Once the user accesses the site, React will hydrate and expect the same markup. However, `localStorageManager` will now no longer return `undefined` as during generation, and thus, a lot of the CSS will mismatch and any HTML that renders differently based on color mode.

HTML mismatches may _probably_ be disregarded because most apps will only have a theme toggle component render differently based on the color mode).
The React [docs ](https://reactjs.org/docs/react-dom.html#hydrate) mention for this case:
> If a single element’s attribute or text content is unavoidably different between the server and the client (for example, a timestamp), you may silence the warning by adding `suppressHydrationWarning={true}` to the element. It only works one level deep, and is intended to be an escape hatch. Don’t overuse it. Unless it’s text content, React still won’t attempt to patch it up, so it may remain inconsistent until future updates.

The CSS mismatch is an issue though as it leads to e.g. `<Button />` staying in light mode when we're in dark.

Reproduction:
https://codesandbox.io/s/broken-wind-l994s?file=/pages/index.js

- copy the url of the sandbox and open it in another tab
- open the devtools
- change to dark mode
- reload, check the console

- `<Button />` and `<IconButton />` staying light
![image](https://user-images.githubusercontent.com/29307652/89736820-93d8bf00-da6c-11ea-8d8a-4d2a225af697.png)
- `<IconButton />` icon value changing
![image](https://user-images.githubusercontent.com/29307652/89736813-8cb1b100-da6c-11ea-8374-89f63446d246.png)

thanks for @fr3fou for making me dig deeper.

**Comment by jmiazga** [comment]
@ljosberinn Are you suggesting changing to cookie based storage as default?

**Comment by with-heart** [comment]
Is there a way to detect if we're in a next app or not?

**Comment by ljosberinn** [comment]
@with-heart I think so, but I'm not too sure if you want to hear it: `<script id="__NEXT_DATA__">` presence :D also `window.__NEXT_P`, `window.__NEXT__DATA__` (which is the contents of said script), `window.__BUILD_MANIFEST` and `window.__BUILD_MANIFEST_CB`.

@jmiazga I havent tried tried honestly but that would force to always evaluate to `false` outside of Next so I doubt it's a solution.

**Comment by jmiazga** [comment]
@ljosberinn I'm not sure I follow what you mean, what would always evaluate to false?

**Comment by ljosberinn** [comment]
oh, you're right, passing `document.cookie` might solve it 🤔 I'll try

**Comment by jmiazga** [comment]
We could always pass nothing and try and fallback to document.cookie. It just depends on what we want the API to look like.

**Comment by ljosberinn** [comment]
hm I think I'm a bit stuck here thinking about possible solutions. Tried this but it changes absolutely nothing:
```ts
export const cookieStorageManager = (
  maybeCookies?: string,
): StorageManager => ({
  get(init?) {
    const cookies = maybeCookies
      ? maybeCookies
      : typeof document !== "undefined"
      ? document.cookie
      : ""
```

+ exchanging `localStorageManager` with `cookieStorageManager()` in `useColorModeState`

**Comment by jmiazga** [comment]
How are you testing it? This wouldnt work for SSR apps, but I would expect a client side app wouldnt see a flash during loading, and would behave similar to using local storage to manage the current color mode.

**Comment by ljosberinn** [comment]
Modifying node_modules locally in a small Next app, both in dev and static export. The issue is still that the hydration leads to different markup. We'd need to toggle colorModeState after the render necessarily either way to avoid the warnings.

**Comment by jmiazga** [comment]
Do you have a link to the small next app? I wouldn't mind running it locally.

**Comment by ljosberinn** [comment]
It's pretty much this: 
https://codesandbox.io/s/broken-wind-l994s?file=/pages/index.js
just with another page that uses `getStaticProps`

**Comment by with-heart** [comment]
This issue is not what I was thinking it is, so I'll leave it for someone else 😅

**Comment by ljosberinn** [comment]
stumbling over `getStaticProps` + cookies, I implemented a working, but imo "meh" solution here: https://github.com/ljosberinn/nextjs-mdx/blob/refactor%2Fdrop-getinitialprops/src/components/Chakra.jsx#L36

**Comment by nonissue** [comment]
Amazing, thank you!

**Comment by ljosberinn** [comment]
Closing this since it will be hopefully resolved for good with the next release! 🎉

**Comment by nonissue** [comment]
@ljosberinn Thanks again for the update!

**Comment by fr3fou** [comment]
Was the fix released?

**Comment by 4ortytwo** [comment]
Would like to know as well. Updated to rc3 and cookieStorageManager doesn't work anymore. 
What is the right way to handle dark mode support in Next.js now? @ljosberinn

**Comment by ljosberinn** [comment]
https://next.chakra-ui.com/docs/features/color-mode#change-color-mode-behavior

- however, ironically only in production an issue arose: #1878
