### ISSUE TITLE
Remove the As type infer to make intellisense faster

### ISSUE THREAD

**Issue by remorses** [chakra-ui/chakra-ui#1582]
With latest release typescript intellisense is still very slow

I did some investigation and the problem is the `ComponentWithAs` type, i tried tweaking that types removing the `As` generic argument and everything becomes super smooth, making intellisense instantaneous

The `as` generic argument delays intellisense even if you son't use it, the delay is about `1000ms` average for me

I think we should remove the as generic and instead encourage people to use the new `chakra.tag` approach

The `as` type infer approach could be added maybe in the future, we shouldn't add it in the `1.0` release or it will be impossible to remove (because of breaking changes) and it will make everyone experience worse

**Comment by remorses** [comment]
I can open a pull request if you agree

**Comment by with-heart** [comment]
I feel fairly conflicted here. I like the type safety of strongly typing `as`, but there's a definite concern with the performance around intellisense as it's quite noticeable, and as you said, it affects all users whether they use `as` or not. 

I've been digging around trying to find more information related to this, and I found two things of note:

- `emotion` merged a PR for v11 adding the `as` prop, but also ran into issues and are considering removing it: https://github.com/emotion-js/emotion/pull/1874
- `react-polymorphic-box` was one of the original inspirations for using the `as` prop, and their implementation differs from ours: https://github.com/kripod/react-polymorphic-box/blob/main/src/Box.tsx

The Chakra types are fairly dense, so if you have time @segunadebayo, I'd like to walk through our implementation with you to see if there are adjustments we could make to improve the situation we're in. If not, I unfortunately think @remorses is right about the need to consider performance over typing.

**Comment by remorses** [comment]
Unfortunately there is no way to optimize the as inference, the following is the simplest implementation you could do and it still takes half a second to show intellisense, EVERY TIME

```tsx
import { ComponentPropsWithoutRef, ElementType, ReactElement } from 'react'

export type ASProps<AS extends never | ElementType> = {
    as?: AS
} & (AS extends never ? {} : ComponentPropsWithoutRef<AS>)

export function Box<AS extends never | ElementType>(
    props: { someProp?: string } & ASProps<AS>,
): ReactElement<any, any> {
    return <div />
}
```

**Comment by with-heart** [comment]
That does appear to be the case. MUI has been investigating similar issues for quite some time: https://github.com/microsoft/TypeScript/issues/34801

**Comment by santialbo** [comment]
As much as I love having the type safety, I wouldn't mind going back to the chakra v0 way if that meant a more responsive dev experience.

**Comment by with-heart** [comment]
imo this is something we need to revisit once TypeScript provides us with a mechanism for keeping this performant. Right now, complex union types cause an explosion of type resolution that `tsc` has to do, and `tsserver` (I think) has no way to cache, prioritize, or make those resolutions lazy, so it does them all at once and each time you request a completion.

**Comment by segunadebayo** [comment]
Thanks for reporting this @remorses. I would rather try to improve the IntelliSense a bit more instead of removing `as` prop support completely.

I also agree with @santialbo, we need to keep the DX very close to v0.8 as much as we can.

As a first attempt, @with-heart and I worked on improvements here #1627. @remorses can you check it out to see if you notice any boost in IntelliSense speed?

**Comment by franky47** [comment]
FIY, Microsoft has published a wiki of tips and tricks for improving TypeScript performance:
https://github.com/microsoft/TypeScript/wiki/Performance
