### ISSUE TITLE
Custom variants

### ISSUE THREAD

**Issue by tereartur** [chakra-ui/chakra-ui#159]
Hello!

1) It would be nice to use textStyles and buttonStyles that styled system exports from its variant package (https://github.com/styled-system/styled-system/blob/master/packages/variant/src/index.js).

But Box component don't add these to its systemProps.

2) But even better would be if there is a way to add your own custom variants. Like custom button style, text styles, heading styles etc. I think that maybe it would be good if there would be optional key in theme file like "customVariants".
That would be loaded in with extraConfig (https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/Box/config.js). Then everyone could add their own custom variants to theme file if they wish and because all components use Box as base these would be available in every component. It would make chakra more flexible for custom theming.

At the moment when I have a lot of default styles overriding I need to add lot of props to every Text/Button/Label etc component I use. Another way I thought was to make adapter components that would add these props and render to base Chakra components.

For example in theme file:

`customVariants: {
  textStyles: {
    L14: {
            fontSize: '14px',
            lineHeight: '24px',
            fontWeight: 'medium',
    },
    L16: { ... }
  },
  buttonStyles: ...
}`

And then in code I could just use:

`<Text textStyle="L14">Text here</Text>`

What do you think is the best way to overcome this problem?

**Comment by segunadebayo** [comment]
Hi @tereartur,

I think the best way would be to add variants directly to the theme object and have it accessible via a `variant` prop. As you said, this already exists in Styled System and I'll look into adding this soon.

**Comment by tereartur** [comment]
Thanks for answer @segunadebayo,

Ok, adding variants directly to theme object sounds nice.

Access through one prop like `variant` don't allow you to use multiple variants on one component.

For example I would like to have `<Button buttonType="secondary" textStyles="L14" />`. Secondary button type has custom bg, hover, border, border radius etc. TextStyles variant adds custom fontSize, lineHeight and fontWeight.

I struggling with this because I have totally custom design from designer which I'm trying to implement with Chakra (which is very well done btw 👍 )

But at the moment there is now way to hack into Box component and add custom variants which would be available to other components besides adapter components?

**Comment by squ1sh** [comment]
Hello, another developer and I worked this example out for multiple variants.  This works with Chakra components as well as other styled ones!  Nothing fancy but it allows for either a string or an array of variants that is composed from left to right.

[Hopefully this is useful to someone!](https://codesandbox.io/s/determined-lederberg-2r3dz)

**Comment by ptim** [comment]
For future readers, I think layerStyles help here:

> Layer Styles allow you to save a combination of styling attributes to re-use in other components. Once created, pass the layerStyle prop to any component and chakra will resolve the styles accordingly.
> https://chakra-ui.com/docs/styled-system/text-and-layer-styles
