### ISSUE TITLE
[Tooltip] Warnings about props being passed to DOM elements in rc.2

### ISSUE THREAD

**Issue by santialbo** [chakra-ui/chakra-ui#1595]
Tooltip props are being passed to the DOM element causing some warnings
```
Warning: React does not recognize the `isOpen` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isdisabled` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
Looking at the source it looks like all the `getXXXProps` from `useTooltip` spread the props from `Tooltip` which will ultimately make it into a `<chakra.div {...props}`, causing the warning above.

https://codesandbox.io/s/gallant-haze-35veh?file=/src/index.tsx

**Steps to Reproduce**
Just add any camelCase prop to a tooltip, eg. `isDisabled`, `arrowSize`, `isOpen` (these cause the warning) other non camelCase props like placement don't cause the warning but are applied to the dom, which I'm not sure is intended.

**Suggested solution(s)**
Omit all non-DOM props from TooltipProps in the `getXXXProps` from `useTooltip`

**Comment by segunadebayo** [comment]
Thanks for reporting this @santialbo.

I've just pushed a fix for it.
