### ISSUE TITLE
TypeScript support + Custom items on the Theme

### ISSUE THREAD

**Issue by jmaicaaan** [chakra-ui/chakra-ui#16]
How can I extend the component to get the values from the Theme?

![image](https://user-images.githubusercontent.com/13105222/64323159-84e4c380-cff6-11e9-9e0e-52ddbc5888d1.png)

**Comment by segunadebayo** [comment]
Hi @jmaicaaan, 

Can you put this on Codesandbox so I can take a look? It's most likely a type def issue.

**Comment by segunadebayo** [comment]
I've found the resolved the issue. Thanks for spotting it.

I'll release a patch soon.

**Comment by jmaicaaan** [comment]
I saw the fix regarding the `6xl`. Adding a static type def is fine for the base type def. But I am wondering if it's possible to get values from the Theme with types?

For example, I added a semantic font size name like "header".

```
{
     ...otherFontSizes,
    "header": "28px"
}

<Box fontSize="header">Hello<Box />
```

What do you think?

**Comment by segunadebayo** [comment]
Yes, this should work as well @jmaicaaan .

In the type def, we made it flexible to support any custom value in the theme. 

If it doesn't work, send me a codesandbox link so I can take a look.

**Comment by jmaicaaan** [comment]
@segunadebayo  - Here is the codesandbox https://codesandbox.io/embed/react-typescript-4w0sv

Not sure if my expectation is possible ATM. Let me know what you think again. Thanks!
