### ISSUE TITLE
[RadioButtonGroup] onChange types do not line up, unusable.

### ISSUE THREAD

**Issue by KyleWiteck** [chakra-ui/chakra-ui#1602]
Should be:
onChange?: (
    event: React.ChangeEvent<HTMLInputElement>,
    value: IRadio["value"],
  ) => void;

but is:
onChange?: (value: IRadio["value"]) => void;

conflict:

> 
> Type '((value: string | number | undefined) => void) | ((event: ChangeEvent<HTMLInputElement>, value: string | number | undefined) => void)' is not assignable to type '((value: string | number | undefined) => void) | undefined'.
>   Type '(event: ChangeEvent<HTMLInputElement>, value: string | number | undefined) => void' is not assignable to type '(value: string | number | undefined) => void'.ts(2322)
> index.d.ts(11, 3): The expected type comes from property 'onChange' which is declared here on type 'IntrinsicAttributes & IRadioButtonGroup & Pick<BoxProps, "color" | "hidden" | "ref" | "p" | "slot" | "style" | "title" | ... 418 more ... | "isTruncated"> & { ...; }'
>

**Comment by jmiazga** [comment]
Thanks @KyleWiteck for reporting this. We are dropping `RadioButtonGroup` in v1 in favor of using the `useRadio` and `useRadioGroup` hooks.

**Comment by with-heart** [comment]
You can see an example of how that works here: https://next.chakra-ui.com/docs/form/radio#custom-radio-buttons
