### ISSUE TITLE
[Button] "as" prop has incorrect type in rc2

### ISSUE THREAD

**Issue by dmitru** [chakra-ui/chakra-ui#1615]
**Describe the bug** 

This code:
```
                       <Button
                              as="a"
                              target="_blank"
                            >...</Button>
```

Gives the following TypeScript error:
![image](https://user-images.githubusercontent.com/948486/89917817-1c12ad80-dbae-11ea-8e34-d0879238104c.png)

**Additional context** 
Chakra: 1.0.0-rc2
TypeScript: 3.9.7

**Comment by with-heart** [comment]
I think this may be resolved by #1627 but I need to investigate.

**Comment by with-heart** [comment]
Verified that it's fixed. Will be out whenever `1.0.0-rc.3` is released!

**Comment by ralphilius** [comment]
@with-heart Do you have timeline when `1.0.0-rc.3` is out? It wouldn't harm for me but I hate it when the IDE indicated that I got something wrong in my code :sweat_smile:

**Comment by with-heart** [comment]
@ralphilius I'll check with Segun and try to release it today if we're in a good place. 

You could always annotate issues like this with `@ts-expect-error` so that when they're fixed, ts will let you know that it's no longer throwing an error.

**Comment by ralphilius** [comment]
Thanks @with-heart for your prompt response and tip
