### ISSUE TITLE
[Alert] Icon and text styling conflict with wrapping content

### ISSUE THREAD

**Issue by dustinlarimer** [chakra-ui/chakra-ui#1619]
**Description**

Default styling for the `Alert` component doesn't handle wrapping text well. A few of the [stories](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/alert/stories/alert.stories.tsx) for this component use additional markup with varying results.

<img width="798" alt="Screen Shot 2020-08-11 at 9 32 36 AM" src="https://user-images.githubusercontent.com/180438/89929121-a57dac00-dbbd-11ea-8f09-163cbc9519b0.png">

<img width="621" alt="Screen Shot 2020-08-11 at 9 40 41 AM" src="https://user-images.githubusercontent.com/180438/89929512-2472e480-dbbe-11ea-91a1-57bf07475b0a.png">

**Expected Behavior:**
- By default, the component should accommodate variable text lengths without losing element sizing or alignment.
- When desired, elements should still be easily customizable with additional style attributes or markup.

**Reproduction:**
- https://codesandbox.io/s/vibrant-wind-gylw6?file=/src/App.js

**Suggested solution(s):**

Two possible approaches:

1. **Quick:** Change the `Alert` component container's default `alignItems` from "center" to "start", make all contents and composable child components share a common 1.5rem line-height (similar to the proposed updates in #1611), and set a fixed default boxSize for `AlertIcon`. This will let basic one-line alerts appear vertically centered, while allowing text to gracefully wrap without losing alignment or vertical rhythm.

2. **A bit more complex:** Update the `Alert` component to include an `icon` prop, and manage icon composition in a similar manner to `Button` and `IconButton`. Then wrap the contents of the Alert in a nested div w/ `flex="1"`, as many of the examples and stories do today.

Example with style and layout updates: https://codesandbox.io/s/flamboyant-resonance-b79l8?file=/src/App.js

**System:**

- OS: macOS 10.15.5 (Catalina)
- Chrome
- 84.0.4147.105

**Comment by dustinlarimer** [comment]
I would happily open a PR for this, with input on the possible solutions I outlined above.

**Comment by segunadebayo** [comment]
Thanks for reporting this @dustinlarimer.

I think your first suggestion makes sense. I'm not sure if setting the alignment from `center` to `flex-start` will produce the same vertical rhythm for a one-line text.

The other suggestion sounds like something the user should handle within their applications/website.

Feel free to test this and check if it looks good, then send in a PR.
