### ISSUE TITLE
[Docs] Add extra step in getting started section for babel-plugin-emotion installation

### ISSUE THREAD

**Issue by caiorios** [chakra-ui/chakra-ui#162]
Hello, first of all, congratulations for this awesome library!

I have been using it for a while. I installed the 0.2.8 version and everything went well following the current documentation. However, after updating the package to the latest version (0.3.2), it began to fire the following error:

`
Uncaught Error: Component selectors can only be used in conjunction with babel-plugin-emotion.
`

I made it work after follow the babel-plugin-emotion documentation.

The obvious solution I found is to add the same steps documentate in babel-plugin-emotion in Chakra UI documentation.

**Comment by segunadebayo** [comment]
Hi @caiorios,

Are you using Component selectors within your app? I asked because Chakra doesn't use Component Selectors and I'm not sure we need to add `babel-plugin-emotion`.

Please confirm this.

**Comment by caiorios** [comment]
Hi @segunadebayo, I reviewed all my code to answer your question. Yes, it is using in just one component. After I removed it, everything backed to work without babel-plugin-emotion.

In this case I agree that is not really necessary specify the need of installation of additional plugin to make the library to work.

Can I close the issue?

**Comment by segunadebayo** [comment]
Great. I'm glad it's working now. I'll close this issue and PR.

If you still need to use Component Selectors then you'll need to install the `babel-plugin-emotion` in your project.

Thanks for using Chakra @caiorios.

**Comment by probablyup** [comment]
This is not quite right. Because you re-export `styled` in https://github.com/chakra-ui/chakra-ui/blob/1220fe49f943139a6704b2f8f4e7978008ceca9d/packages/system/src/system.ts, you actually do need to use the newer version of the emotion babel plugin that supports the "importMaps" feature.
