### ISSUE TITLE
Request to add EditableTextArea to [Editable] component

### ISSUE THREAD

**Issue by akiarostami** [chakra-ui/chakra-ui#1622]
**What problem does this feature solve?** A clear and concise description of the
To make multiline texts Editable, we need to have a EditableTextArea, the same way we have EditableInput. I think it would be make Editable even more useful.

**What does the proposed API look like?** Describe how you propose to solve the
Same as EditableInput!

**Comment by with-heart** [comment]
Thanks for the idea @akiarostami! We're open to a PR adding this functionality, but for the time being the team has prioritized other work, so I'm going to close this to help clean up our issues backlog.

**Comment by with-heart** [comment]
Reopening since this seems to have a decent amount of community support.

**Comment by delucca** [comment]
I would like to keep this issue open please, I really need it!

**Comment by delucca** [comment]
no updates on this?

**Comment by segunadebayo** [comment]
Thanks for the request! Considering this isn't a bug, I'll add this to our project board so you can track the progress.

Check it here: https://github.com/chakra-ui/chakra-ui/projects/6

Cheers.

**Comment by TaylorFacen** [comment]
I would greatly appreciate this as well!

**Comment by 0-void** [comment]
Guys, I too wanted this component but couldn't find it anywhere. So pocked around in the editable component and copy-pasted and made some adjustment. And it is working. If you guys need it here is the GitHub gist for it. Hope this will help :) 
Link to the gist - https://gist.github.com/0-void/57ebc389b10f8ecab4f1cad0bf5d92b8

This is the first time I'm doing this so, please if something seems inappropriate sorry :)

**Comment by heozeop** [comment]
Hi!
May I contribute to this feature in the near future (mayby in a week, includes the weekend)?

**Comment by yasimoha** [comment]
Hi, has this feature been added ?

**Comment by heozeop** [comment]
> 
Well, I gonna request review after resolve confict! sorry!

**Comment by semasad** [comment]
Hi! If you pass the as prop with textarea, the EditableInput will be a textarea.

Try to add use the EditableInput like this:

`
<EditableInput as="textarea" />
`

Hope this works for everyone!

**Comment by delucca** [comment]
Can't we reopen this issue? I think this is a pretty simple and common component and we should implement it.

**Comment by semasad** [comment]
> @semasad that does not support mulriple lines like in a normal texarea

Thanks @anubra266. In fact, this do not solve the multiline, would be great if this PR could consider not only textarea, also handle the enter key event to avoid stop editing the input.

Where I need the textarea, was mainly to have line-break in the input.

Hope see this feature soon!

**Comment by heozeop** [comment]
@semasad
I worked on multi line input on [linked pr](https://github.com/chakra-ui/chakra-ui/pull/4443).
I hope you checkout and leave any comment to improve quality!

**Comment by moklick** [comment]
This is fixed! The latest version 1.8.6 has an `EditableTextarea` export 🎉

**Comment by semasad** [comment]
> 

Sorry! For some reason I didn't see this :-(
