### ISSUE TITLE
Request to add useMode hook for dark/light styling

### ISSUE THREAD

**Issue by Coffeegerm** [chakra-ui/chakra-ui#1647]
**What problem does this feature solve?**
The ability to create dynamic styling in a component without a lot of boiler plate

**What does the proposed API look like?**

```tsx
export type Colors = {
  dark: string
  light: string
}

export const useMode = (colors: Colors[]): string[] => {
  const {colorMode} = useColorMode()
  const [items, setItems] = React.useState<string[]>([])
  React.useEffect(() => {
    colors.forEach((color: Colors, index: number) => {
      items[index] = color[colorMode]
      setItems(items)
    })
  }, [colorMode])
  return items
}
```

Open to suggestions for changes obviously. Looking through the source useColorMode returns a context and I assume we can reuse some of these values within the package locally.

**Additional context**
I was looking to fix this headache and found a comment from @segunadebayo suggested this type of fix

**Comment by with-heart** [comment]
I'm not sure I understand the issue. Can you give an example of how you'd use `useMode`?
