### ISSUE TITLE
[Docs] Update migration docs around RadioButtonGroup

### ISSUE THREAD

**Issue by jmiazga** [chakra-ui/chakra-ui#1650]
`RadioButtonGroup` has been dropped in v1 in favor of `useRadio` and `useRadioGroup`. We need to update the docs to show how to migrate from `RadioButtonGroup` to the new hooks.

**Comment by ljosberinn** [comment]
https://next.chakra-ui.com/docs/form/radio#custom-radio-buttons what about this?

**Comment by jmiazga** [comment]
That might work, but it should probably be called out and referenced in the migration guide.
