### ISSUE TITLE
Dark theme bug on website

### ISSUE THREAD

**Issue by pnfcre** [chakra-ui/chakra-ui#166]
Hi there,

I noticed that the GitHub button looks weird if you're using the dark theme on chakra-ui.com.

![image](https://user-images.githubusercontent.com/24176136/66458304-af50f300-ea72-11e9-9a82-db8e7c4800ee.png)

Kind regards,
Casper.

**Comment by pnfcre** [comment]
Also I might note that all imports in https://chakra-ui.com/getting-started appears to be invalid, shouldn't they be `import {} from "@chakra-ui/core"`, not `import {} from "chakra-ui"`? :)

**Comment by segunadebayo** [comment]
Hi Casper,

This is the docs site, I don't know how you got to this but it seems there was an issue with Zeit Now. I've updated the site.
