### ISSUE TITLE
 basic interface icons not working or docs is not clear

### ISSUE THREAD

**Issue by Koli14** [chakra-ui/chakra-ui#1670]
**Describe the bug**
I try to use some icons from the chackra-ui, with chakra-ui/core 1.0.0-rc.2, but I get the following error message:
```
Error
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
```

**Link to minimal reproduction**
Here is a JavaScript CodeSandbox about it:
 https://codesandbox.io/s/sharp-chandrasekhar-bzbji?file=/src/index.js

**Steps to Reproduce** 

Import an icon (e.g.: PhoneIcon) from `"@chakra-ui/core"`, and add it inside `<ChakraProvider>`

**Comment by jmiazga** [comment]
Hey @Koli14 

Can you try and import the `PhoneIcon` from `"@chakra-ui/icons"`

**Comment by Koli14** [comment]
> Can you try and import the `PhoneIcon` from `"@chakra-ui/icons"`

I definitely did, and the same happens:
https://codesandbox.io/s/competent-haslett-whu8b?file=/src/index.js

**Comment by jmiazga** [comment]
Its a named export, not the default export. You need `{ PhoneIcon }`

**Comment by Koli14** [comment]
> Its a named export, not the default export. You need `{ PhoneIcon }`

You are right, now it's working. It would be great, to write in the docs, that one need to import the icons from @chakra-ui/icons.

**Comment by jmiazga** [comment]
I agree. I am going to leave this ticket open, and update the docs to clarify all of this.
