### ISSUE TITLE
Recent Doc Update

### ISSUE THREAD

**Issue by chuckstock** [chakra-ui/chakra-ui#169]
It looks like an older version of the docs got published. Seeing a search bar that does nothing. All the hooks are removed from the SideNav, and the Icon grid layout is not showing up.

**Comment by segunadebayo** [comment]
Yes, I'm currently looking into it. Not sure what triggered it.

**Comment by segunadebayo** [comment]
Updated the docs.

**Comment by chuckstock** [comment]
Always impressed with your responsiveness @segunadebayo! Our whole company is moving over to Chakra and couldn't be happier, keep up the good work!

**Comment by segunadebayo** [comment]
Awesome! Thank you @chuckstock. I'm excited to hear that your company is moving over to Chakra.

**Comment by aaronmcadam** [comment]
> Always impressed with your responsiveness...

I second that, I've been using Chakra as my team's new basis for all new applications and our design system and have been bugging @segunadebayo for days now! 😆 He's been brilliant!

**Comment by aaronmcadam** [comment]
I'm still seeing the old version though. I'm in the UK, is it possible that an cache edge hasn't been updated yet?

**Comment by segunadebayo** [comment]
I'm not sure what's causing this problem. I've tried to update it again. Seriously considering moving to Netlify for the docs.

**Comment by aaronmcadam** [comment]
Yeah it's back to the latest version now, thanks @segunadebayo
