### ISSUE TITLE
[Toast] - How to use toast outside of component?

### ISSUE THREAD

**Issue by ganeshkrishnasharma** [chakra-ui/chakra-ui#1693]
The chakra toasts are really beautiful, but unfortunately it seems like there is no way to use them outside of functional components!! 

I want to invoke the toast on the success or failure of Rest API, which obviously is in .ts file and outside of component. 

Any solution/workaround for this would be highly appreciated. Thanks!

Fo eg: 

In my user component:

```
export const Users = () => {
   .......

    useEffect(() => {
      dispatch(getUsers());
    }, [dispatch]);

   ........
 }

```

and then in my user action file : 

```
export const getUsers = () => {
    return (dispatch: Dispatch) => {
       getUsersService()
       .then((response: any) => {
         dispatch(setUserList(response));
         // i want to invoke success toast here
       })
      .catch((error: Error) => {
        // i want to invoke error toast here
      });
  };
};
```

**Comment by jmiazga** [comment]
Hey @ganeshkrishnasharma. 

Are you able to pass `toast` to `getUsers()`?

```
export const Users = () => {
    const toast = useToast()
   .......

    useEffect(() => {
      dispatch(getUsers(toast));
    }, [dispatch]);

   ........
 }
```

I haven't used `useReducer` or Redux in a while, so I'm not sure if this would be another option:

```
export const Users = () => {
    const toast = useToast()
   .......

    useEffect(() => {
      dispatch(getUsers()).then(() => success toast).catch(() => error toast);
    }, [dispatch]);

   ........
 }
```

**Comment by ljosberinn** [comment]
alternatively, create a custom hook:
```ts
export function useUsers() {
  const dispatch = useDispatch();
  const toast = useToast();

  return () => {
    dispatch(getUsers())
      .then(() => {
        // do something here
      })
      .catch(console.error);
  }
}
```

**Comment by ganeshkrishnasharma** [comment]
@jmiazga 
I tried passing toast as a param, and it works fine!

code:

```
export const Users = () => {
   const toast = useToast();
   .......

    useEffect(() => {
      dispatch(getUsers(toast));
    }, [dispatch]);

   ........
 }
```

user action file (.ts file)

```
export const getUsers = (toast: any) => {
    return (dispatch: Dispatch) => {
       getUsersService()
       .then((response: any) => {
         dispatch(setUserList(response));
         toast({
          title: 'Users fetched successfully!',
          status: 'success',
        });
       })
      .catch((error: Error) => {
        toast({
          title: 'Failed to fetch users!',
          status: 'error',
        });
      });
  };
};
```

@ljosberinn , yeah your solution also looks great, but for my use case i would try to make it generic just by passing toast as shown above , as i have 30+ api integrations required with different success/error/warning toasts to be displayed - hence would be difficult to make it generic with custom hooks!

Thanks guys for your solutions. Much appreciated!

**Comment by with-heart** [comment]
I'm going to leave this open as a feature request. Our codebase at work calls toasts liberally inside API methods, so it'd be nice to see if there's a way we can make that work for Chakra.

**Comment by khanzzirfan** [comment]
copied the code from the above PR merged! Hope it works for others!

import { createStandaloneToast } from "@chakra/core"

const toast = createStandaloneToast()
// const customToast = createStandaloneToast({ theme: customTheme })

const fetchUsers = async () => {
  await fetch() // ...
  toast({
    title: "Yay",
    status: "success"
  })
}

**Comment by huanlirui** [comment]
i want use toast in  uitl.js , but useToast can't use in  outside of component , how to solve it ?

**Comment by huanlirui** [comment]
> 

 import { createStandaloneToast } from "@chakra/core"  module-not-found  ？

**Comment by fakfa19** [comment]
```ts
import { createStandaloneToast } from "@chakra-ui/react";

const toast = createStandaloneToast();

toast({ title: "Toast", status: "success" });
```

**Comment by tochman** [comment]
Oldie but goodie, as they say. Let me throw in my 5 cents... The correct way (at least in my case) is:

```js
import { createStandaloneToast } from "@chakra-ui/react";
const { toast } = createStandaloneToast();
```
...and then toast away:

```js
toast({ title: 'Foo', status: 'error' })
```
Hope it helps.
