### ISSUE TITLE
[Popover] Triggering a Modal Open from Popover doesn't close popover

### ISSUE THREAD

**Issue by ganeshkrishnasharma** [chakra-ui/chakra-ui#1697]
On blur , the popover should be closed & it works in case of outside click, etc. But when we trigger a modal open from the popover component, even-though opening of modal is blur event for popover, the popover doesn't seems to get closed automatically.

codesandbox link:

https://codesandbox.io/s/popover-and-modal-oscml

**Comment by santialbo** [comment]
I don't think it should be closed automatically by default.

You can achieve the desired effect by using a child function. See this codesanbox https://codesandbox.io/s/popover-and-modal-forked-9kf9k?file=/src/App.js

**Comment by ganeshkrishnasharma** [comment]
@santialbo - your solution looks interesting! will try out and update. 

but as far as this issue is concerned, I still think the popover should automatically close as we are explicitly giving `closeOnBlur={true}` for the Popover.

**Comment by mathdroid** [comment]
Hi @ganeshkrishnasharma I think the problem is that you clicked somewhere outside the document. The HTML (minimum) height is not set to 100% of browser height. See attachment

![ezgif-6-afdf9c7e8a2b](https://user-images.githubusercontent.com/3748658/91438498-a38e3b00-e895-11ea-9457-bfe18f75f245.gif)

**Comment by ganeshkrishnasharma** [comment]
Hi @mathdroid , The concern is that the popover is not closing when you click on the delete button to open a modal. Clicking outside of popover itself does work.

**Comment by with-heart** [comment]
On investigating this a little further, I think this is working as intended. The comment on `closeOnBlur` and in the docs notes that this only applies to clicking outside. We use `useInteractOutside` from `react-aria`, which only allows us to detect when a user clicks outside of the component, so this would likely be quite a bit of work which we can't afford right now.

@ganeshkrishnasharma If this is important to you, feel free to open a feature request and we can try to get that implemented sometime in the future.
