### ISSUE TITLE
Snapshot tests aren't processing theme props

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1698]
I was working on our GitHub Actions workflows and noticed that snapshot tests aren't processing theme props correctly.

You can see an example in this commit: https://github.com/chakra-ui/chakra-ui/commit/e9dbd57dfcab8f21339c90790baa043f8e683390

I opened an issue because I'm not sure what's going on here. They receive the correct props when running storybook locally, so I'm not sure what's so special about the snapshot tests.

**Comment by segunadebayo** [comment]
Pushed a fix for this. It was due to mismatching versions of emotion and it's `ThemeContext`

**Comment by with-heart** [comment]
Thank you @segunadebayo! You're the best 💜
