### ISSUE TITLE
PseudoBox _hover prop

### ISSUE THREAD

**Issue by thevenine** [chakra-ui/chakra-ui#17]
I observed that the <code>color</code> style is only applied if a space comes before the value

![hover](https://user-images.githubusercontent.com/22549360/64326846-93b18300-cfc2-11e9-88af-d2d4ad27fb9d.gif)

**Comment by segunadebayo** [comment]
Color `red` is an object in the default theme. So you should do `red.50`, `red.100`, `red.200`, ...all the way to `red.900` for it to work. Kindly refer to the "Theme" in the docs.
