### ISSUE TITLE
Is a toggle button group being considered?

### ISSUE THREAD

**Issue by coodoo** [chakra-ui/chakra-ui#171]
[Something like this](https://material-ui.com/components/toggle-button/) from `material-ui` would come in real handy, mind giving it a thought and provide it out of the box?

<img width="944" alt="Screen Shot 2019-10-10 at 9 49 20 AM" src="https://user-images.githubusercontent.com/325936/66532786-42f1f480-eb43-11e9-9eef-6b5a1c9841c7.png">

**Comment by segunadebayo** [comment]
Hi @coodoo,

Thanks for your request. I'll add it to the backlog. I'd like to move Chakra to TS before adding any new component. I'll definitely consider this.

**Comment by ericclemmons** [comment]
I wouldn't consider this stale, but "blocked" or "on-hold".

**Comment by coodoo** [comment]
bump? 😬

**Comment by ualtinok** [comment]
bumpy

**Comment by emileond** [comment]
bump 👀

**Comment by iamminci** [comment]
bump plz

**Comment by cameronelliott** [comment]
Thank you for making Chakra, this would be a helpful feature.

**Comment by rtman** [comment]
@segunadebayo any chance this is in the works?

**Comment by thegreatsantini** [comment]
Bump

**Comment by ksanmugam** [comment]
Still looking forward to this request

**Comment by emileond** [comment]
Seems like this is coming in the next major release, but if you need it now. It's very straightforward to build your own using ChakraUI's native components, here's one I built - hope it helps:

https://codesandbox.io/s/chakra-ui-toggle-btn-3n3gkn

**Comment by maximilianotaverna** [comment]
bump
