### ISSUE TITLE
[V1] CSS properties not replaced with theme values

### ISSUE THREAD

**Issue by baumandm** [chakra-ui/chakra-ui#1719]
I tried upgrading my application to V1 today, following the migration guide.  I'm now facing a lot of visual issues due to CSS props not being replaced with their respective theme values, e.g. rendering `font-size: sm;` instead of `font-size: 0.875rem;`.  This appears to be happening across the board as seen in this screenshot containing `font-size`, `border-radius`, and `background`:

<img width="340" alt="Screen Shot 2020-08-18 at 10 54 10 AM" src="https://user-images.githubusercontent.com/3084806/90528940-2a7a3f80-e141-11ea-9c5d-a82bf9417a48.png">

That's from 

```
<Input size="sm" value={value} variant="filled" placeholder="Search..."></Input>
```

This is happening on pretty much every component: inputs, buttons, avatars, tooltips, etc.

Some details:

- Using `@chakra-ui/core` and `@chakra-ui/core`, version `1.0.0-rc.2`
- Removed explicit dependency on Emotion
- Switched to `<ChakraProvider theme={theme} />`
- Tried with the default theme: `import theme from '@chakra-ui/theme';`
- Wiped and reinstalled node_modules, deleted the build files and rebuilt from scratch.

I must have missed a step in the migration but I can't figure out what went wrong.  What am I missing?

**Comment by ljosberinn** [comment]
Hi - the `size` prop changed as mentioned [here](https://next.chakra-ui.com/docs/migration#5-update-layout-size-prop). That said, [it's still valid](https://next.chakra-ui.com/docs/form/input#changing-the-size-of-the-input) on `Input`. Can you share your package.json, your provider setup and/or a sandbox?

**Comment by with-heart** [comment]
Hi @baumandm!

We ran into a similar issue recently and it was caused by conflicting `emotion` versions. Can you try deleting `yarn.lock` and reinstalling your modules and see if that fixes the issue?

**Comment by baumandm** [comment]
That fixed it!  Thanks for the assistance.

**Comment by spykr** [comment]
This started occurring for me after I updated Storybook to v6 and added `@storybook/theming`  as a dependency to fix a Storybook error. Changing my `emotion-theming` dependency from `10.0.27` to `10.0.19` fixed this issue for me.
