### ISSUE TITLE
Request to add CSS multi column support to [Box]

### ISSUE THREAD

**Issue by pinutz23** [chakra-ui/chakra-ui#1725]
**What problem does this feature solve?**
Missing support for css columns ([css columns on css-tricks](https://css-tricks.com/almanac/properties/c/columns/))( 
 ([columns on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/columns)).

**What does the proposed API look like?**
columnCount
columnFill
columnGap
columnRuleStyle
columnRuleWidth
columnRuleColor
columnRule
columnSpan
columnWidth
breakInside

**Describe alternatives you've considered**
Building columns with `Flex` or `Grid`, but CSS multi columns behave slightly different.

**Comment by with-heart** [comment]
It's amazing how often I learn about new things hidden in the CSS spec.

I'm not sure we need to add these as direct props. You can apply almost any CSS rule using the `css` prop: https://codesandbox.io/s/interesting-hermann-w77rm?file=/src/App.tsx

Would that satisfy your use case?

**Comment by bogdansoare** [comment]
@with-heart @segunadebayo the downside of using the `css` prop is that you lose the responsive styles

**Comment by trevorblades** [comment]
I'm encountering the same issue right now @bogdansoare. Would love to be able to apply `columnCount` in a responsive way.

**Comment by with-heart** [comment]
I think we have enough demand here to justify adding it :)

**Comment by bogdansoare** [comment]
@with-heart thank you for considering adding this, I understand @segunadebayo's point of view of keeping the API as minimal as possible and I know it's a hard tradeoff

**Comment by trevorblades** [comment]
FWIW, I was able to achieve this effect using a `className` and the `Global` component:

```js
export function MarketingColumns(props) {
  const query = useQuery({above: 'md'});
  return (
    <>
      <Global
        styles={{
          [`@media ${query}`]: {
            '.mktg-cols': {
              columnCount: 2
            }
          }
        }}
      />
      <Text
        className="mktg-cols"
        mb={[5, 6, 8]}
        fontSize="lg"
        css={({theme}) => ({columnGap: theme.space[12]})}
        {...props}
      />
    </>
  );
}
```

Of course it would be much handier to be able to do this:

```js
<Text
  mb={[5,6,8]}
  fontSize="lg"
  columnGap="12"
  columnCount={{md: 2}}
  {...props}
/>
```

**Comment by segunadebayo** [comment]
Thanks for sharing your approach @trevorblades.

You also achieve this by using the `sx` prop in v1, which allows you to define regular css styles in a theme-aware, responsive manner.

```jsx
<Box sx={{ columnCount: [1, 3] }}></Box>
```

@with-heart, the thing is, we created the `sx` prop as a fallback for style props we don't allow by default. Perhaps, we can improve the docs a bit to make this clearer.

Cheers

**Comment by trevorblades** [comment]
@segunadebayo this is amazing, thanks for sharing! I had no idea the `sx` prop worked like this 🤯

**Comment by Ploppy3** [comment]
You can also use a responsive object

`sx={{ base: 1, sm: 2, md: 3 }}`

**Comment by mtailor127** [comment]
> You can also use a responsive object
> 
> ```
> <Box sx={{ base: 1, sm: 2, md: 3 }}></Box>
> ```

<Box sx={{ columnCount: { base: 1, sm: 2, md: 3 } }}></Box>
