### ISSUE TITLE
[TypeScript] Incorrect merging of the onChange prop types

### ISSUE THREAD

**Issue by franky47** [chakra-ui/chakra-ui#173]
I noticed that some components with the `onChange` prop have issues with TypeScript, namely:

- [ ] `NumberInput`
- [ ] `Editable`

Potentially affected, untested:
- [ ] `Accordion`
- [ ] `CheckboxGroup`
- [ ] `Menu`
- [ ] `Radio`
- [ ] `RadioButtonsGroup`
- [ ] `RadioGroup`
- [ ] `Select`
- [ ] `Tabs`

In those cases, the type for the `onChange` prop is not just the one defined in the interface for the component (which is the expected type), but a merge of that and other definitions coming from the underlying components (HTMLInputElement, Flex, Box, PseudoBox etc).

Example of a resolved type for `NumberInput.onChange` with this issue:
```ts
(property) onChange?: (((value: number) => void) & ((event: React.FormEvent<HTMLElement>) => void)) | undefined
```

Which should instead be:
```ts
(property) onChange?: (value: number) => void
```

There might be more cases where this happens, I will edit the list of affected components to reflect that as I go along.

A solution can be to omit the `onChange` prop from the underlying (inherited) types, as done in PR #89.

**Comment by segunadebayo** [comment]
I see what you mean. Thanks for this observation. Please feel free to make the changes as described and submit a PR.

**Comment by segunadebayo** [comment]
I've omitted the types from most of the affected components @franky47.

I'll release a new version shortly
