### ISSUE TITLE
Create pull request template

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1739]
A pull request template allows us to explicitly define our expectations for contributors when creating a pull request.

Our template should provide contributors with prompts for information to fill out relating to the pull request. The prompts should encourage users to share information about their PR like what problem(s) it is attempting to address, what steps they took to address the problem(s), to link to any related issues. This information will make it easier for maintainers to quickly understand what the PR is trying to achieve in order to provide a thorough code review.

We could also consider having a basic checklist for the contributor to check off, like if they added tests and documentation (if applicable), to help set expectations around what should be included in a PR.

See https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository for documentation on how to create the template.

See https://github.com/devspace/awesome-github-templates for examples and inspiration.

**Comment by vickywane** [comment]
@with-heart I think this template has some inclusive and explanatory fields. https://github.com/ionic-team/ionic-framework/blob/master/.github/PULL_REQUEST_TEMPLATE.md

What do you think ?

**Comment by with-heart** [comment]
@vickywane I love it! I think we can leave out the "Build (npm run build) was run locally and any changes were pushed" and "Lint (npm run lint) has passed locally and any fixes were made for failures" checkboxes because those are run via GitHub Actions, but the rest is exactly the content I was hoping to see.
