### ISSUE TITLE
[Input] Floating label

### ISSUE THREAD

**Issue by newerton** [chakra-ui/chakra-ui#1744]
**What does the proposed API look like?** 
To operate the floating label, the placeholder attribute is required.

```html
<FormControl>
  <Input type="email" id="email" aria-describedby="email-helper-text" placeholder="E-mail" floatingLabel />
</FormControl>
```

**Additional context** 
![](https://raw.githubusercontent.com/cymen/react-floating-label-input/HEAD/floating-label-input.gif)

Ref.: https://github.com/Cnilton/react-native-floating-label-input

**Comment by PierreAndreis** [comment]
I think this makes `Input` component a bit more complex. Maybe another component?

I got this working by creating a wrapper that includes `FormControl` and `FormLabel` together with the `Input` and applying css to the form label.

**Comment by newerton** [comment]
@PierreAndreis Applying css work. I didn't think it was very complex. I will try with css.

I will follow that example: https://codepen.io/AdrianBece/pen/KKKZQOY
