### ISSUE TITLE
Overriding default styles

### ISSUE THREAD

**Issue by dusanstojanovic** [chakra-ui/chakra-ui#1746]
Example: Instead of typing `<FormLabel mb='1' htmlFor='email'>
                                <Text as='span' fontSize='14px' fontWeight='500' letterSpacing='0.1em' color='brand.700' textTransform='uppercase'>
                                    Email
                                </Text>
                            </FormLabel>`
...how can I change default style for, in this case, FormLabel?

**Comment by jmiazga** [comment]
Hi @dusanstojanovic. Chakra v1 enables you to easily customize the theme, and set default props for components. Check out the docs and let me know if you have any questions: https://next.chakra-ui.com/docs/theming/basic

**Comment by with-heart** [comment]
Going to close this for now. Feel free to reply if the theming isn't working for you.
