### ISSUE TITLE
[Responsive] Responsive using object not taking effect 

### ISSUE THREAD

**Issue by ralphilius** [chakra-ui/chakra-ui#1752]
**Describe the bug** A clear and concise description of what the bug is.

This is a weird bug that has come to my project a few days ago. After uprading to `1.0.0-rc2`. Previously, I can use something like `{{base: -9999, md: 0}}` to assign responsiveness to an `order` prop. However, when using array style like `{[-9999, null, null, 0]}`, it worked.

**Expected Behavior** A clear and concise description of what you expected to
happen.

**Link to minimal reproduction** Please provide a codesandbox link or GitHub
repo with a minimal reproduction of the issue.

https://codesandbox.io/s/agitated-dream-h7iku
Sadly I can't reproduce this issue using codesandbox template. My stack is:

 - NextJS
 - Yarn Workspace
 - next-transpile-modules

**Steps to Reproduce** Clear and concise reproduction instructions are important
for us to be able to triage your issue in a timely manner.

**Suggested solution(s)**

**Desktop (please complete the following information):**

**Additional context** Add any other context about the problem here, or some
background information of how you ran into this bug.

**Comment by segunadebayo** [comment]
Hi @ralphilius,

I've confirmed that object responsive prop works currently. The issue you're running into has to do with using the `as` prop. I see you do `<Link as={Flex}/>` and `<BaseContainer as={Flex} />`.

Fortunately, we've resolved the issue and we'll release an update shortly.
