### ISSUE TITLE
[Select] It's not possible to change select height

### ISSUE THREAD

**Issue by PierreAndreis** [chakra-ui/chakra-ui#1757]
**Describe the bug** 
When using props `height` on a Select, it doesn't change the height

**Expected Behavior** 
Select component should have correct height

**Link to minimal reproduction** 
https://codesandbox.io/s/flamboyant-engelbart-rqslf?file=/src/index.tsx

**Steps to Reproduce** 
- Use height on a select
- Observe how the height doesn't change

**Suggested solution(s)**
Height should apply to container and Select

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Web
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] v1.0.0-rc.2

**Comment by segunadebayo** [comment]
Thank you for catching this, I just pushed a fix for this.

I've just pushed a fix for this.

**Comment by ryanerringtonatom** [comment]
I'm currently unable to set the select height within the theme, is this possible?

My theme config is as follows:

```
export const Select = {
  parts: ['field', 'icon'],
  variants: {
    outline: {
      field: {
        height: '3rem',
      },
    },
  },
};
```

**Comment by ryanerringtonatom** [comment]
solved using the following syntax - with shorthand "h" property - "height" does not work:

```
export const Select = {
  parts: ['field', 'icon'],
  sizes: {
    md: {
      field: {
        h: '5rem',
      },
    },
  },
};

```
