### ISSUE TITLE
Add table of contents for current docs/guides article

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1758]
I know we've gone around a bit on the design for docs pages and I think this feature existed at some point before going away again, but I think we should consider adding an auto-generated table of contents to each page. 

Whether it's only at the top of the article or floating alongside, I think it's an important addition to help provide context to users. It allows them to understand what content exists within the article, to easily navigate around inside it to the particular part they may be looking for, and—in the case of a floating table of contents—to know how far long within the article they are.

@segunadebayo thoughts on this?

**Comment by Mhmdabed11** [comment]
I would love to work on this once everything is ready!

**Comment by with-heart** [comment]
@Mhmdabed11 That would be awesome. Once we decide how we want to handle this and figure out a design, I'll let you know :)

**Comment by with-heart** [comment]
We're planning on potentially re-working our documentation once we get more analytics from Algolia. In the meantime, I'm going to close this issue.
