### ISSUE TITLE
[Popover] Would like to get more information regarding the help needed with the Popover component

### ISSUE THREAD

**Issue by Billmike** [chakra-ui/chakra-ui#177]
First off, I just want to express how immensely proud this project makes me feel. As a fellow Nigerian, I stand gidigba (excuse my French 😄) with this project. It is well documented, its APIs are easy to use and understand, and the components are highly accessible! Great work here @segunadebayo .

Now my question: I was going through the roadmap, and I saw you listed the Popover component as one that you need help with. I ran the project locally and after testing with Storybook, it's not really clear what you need help with as regards that component. Perhaps, if you could shed some more light on what you think needs fixing, I might be able to help with that?

Again, super work man!

**Comment by segunadebayo** [comment]
Hi @Billmike,

Thank you brother, I'm glad you're excited about Chakra. The Popover is pretty complete already, I just forgot to update the roadmap. Where I'd say I need help is Single Select Component, I have it's API documented here #140. Feel free to jump on this if it interests you.

Thanks again.

**Comment by Billmike** [comment]
Alright. Taking a look now
