### ISSUE TITLE
Request to add Grid Item component

### ISSUE THREAD

**Issue by harveyhalwin** [chakra-ui/chakra-ui#1775]
**What problem does this feature solve?** 
The Grid Item Component would be used to place items in the Grid component. The user should be able to specify the start and end values along the row. This would help in placing items and customising it more precisely.

**Describe alternatives you've considered** 
The current alternate solution is to style it in a seperate css file. This could be avoided if a dedicated component was there.

**Comment by segunadebayo** [comment]
Thanks for this request. I agree that this component will be useful.

I've just pushed a fix for it and it'll go into the next release for v1. Here's what it looks like:
https://github.com/chakra-ui/chakra-ui/blob/bb9f81872a77499f838d44f469efdcd4518e7d3e/packages/layout/src/grid.tsx#L115

Cheers.
