### ISSUE TITLE
[Documentation] State explicitly how a PR should be raised when contributing

### ISSUE THREAD

**Issue by Billmike** [chakra-ui/chakra-ui#178]
I was going through the contributing guidelines hoping to see if it stated how to proceed with raising a PR. There's currently no outlined structure, but going through the PRs raised so far, I could observe that we are raising a PR from a fork against the master branch. This method works great, and I think it should be included in the documentation as well so it's easy to onboard future contributors. If this is okay with you, I would love to modify the existing contributing guidelines to explicitly state this. @segunadebayo

**Comment by segunadebayo** [comment]
Yes please, feel free to modify the contribution guide to include this. 

Thank you.

**Comment by Billmike** [comment]
Awesome! On it
