### ISSUE TITLE
Using chakra icons?

### ISSUE THREAD

**Issue by dusanstojanovic** [chakra-ui/chakra-ui#1792]
Hi, I'm having problems using build-in icons. It works only for one icon, question mark

```JS
import React from "react";
import { Icon } from "@chakra-ui/core";

const Homepage = () => {
    return (
        <div>
            <Icon />
        </div>
    );
};

export default Homepage;
```

... but when I try any other icon it gives me error

```JS
import React from "react";
import { AddIcon } from "@chakra-ui/core";

const Homepage = () => {
    return (
        <div>
            <AddIcon />
        </div>
    );
};

export default Homepage;
```

`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

**Comment by dusanstojanovic** [comment]
@ljosberinn 1.0.0-rc.2. How to install those new icons? Also, someone needs to update docs

**Comment by ljosberinn** [comment]
just `npm i @chakra-ui/icons@next` or `yarn add @chakra-ui/icons@next` - docs are already updated but not yet deployed :)
