### ISSUE TITLE
Docs code examples not accessible

### ISSUE THREAD

**Issue by jescowuester** [chakra-ui/chakra-ui#180]
When you try tabbing through the docs you'll get stuck in the code examples. esc brings you back to the page root and tab just modifies the text.

**Comment by segunadebayo** [comment]
Hi @jescowuester,

I'm not sure what you mean. At the moment, when focus is inside the text editor and you hit `esc`, it blurs out of the editor to allow you "tab" to other elements.

This is handled by `react-live`, the code editor we use for the docs. Feel free to suggest walkarounds as well.

**Comment by jescowuester** [comment]
Seems it only happens when you modify the field. I really like the way reakit handles these fields, let me see if I can find out how they do it :eyes:

**Comment by segunadebayo** [comment]
That would be great. I'll appreciate a PR once you figure it out.
