### ISSUE TITLE
Request to add Badge notification like

### ISSUE THREAD

**Issue by leognmotta** [chakra-ui/chakra-ui#1802]
Would be good to have badge count for notifications bells, so we would be able to show the amount of unread notifications.

[`https://ibb.co/VWSwscT`](url)

![dashboard](https://i.ibb.co/tMsL9TD/Screenshot-from-2020-08-24-18-14-16.png "Logo Title Text 1")

**Comment by jmiazga** [comment]
Hey @leomotta121. It seems like you can set a value for `AvatarBadge`. Is the example below what you are looking for?

```
<Avatar>
    <AvatarBadge boxSize="1.25em" bg="green.500">5</AvatarBadge>
</Avatar>
```

https://codesandbox.io/s/blissful-firefly-igrmn?file=/src/App.js

**Comment by leomotta121** [comment]
> Hey @leomotta121. It seems like you can set a value for `AvatarBadge`. Is the example below what you are looking for?
> 
> ```
> <Avatar>
>     <AvatarBadge boxSize="1.25em" bg="green.500">5</AvatarBadge>
> </Avatar>
> ```
> 
> https://codesandbox.io/s/blissful-firefly-igrmn?file=/src/App.js

Well based on your feedback I would raise another discussion, it would be nice to add a small arrow connecting the menu to the button that raised the menu.

The result I want to achive is exactly that but on the bell, the profile icon will have it own menu, like this:

![dashboard](https://i.ibb.co/fHxPXWH/Screenshot-from-2020-08-25-22-15-13.png "Logo Title Text 1")

I know it would be possible to make some work around the avatar to show badges on the bell, but it would be nice to have a wrapper component where I could add badges to anything, something like this:

```javascript
<Badge size="md" count={5}>
    <MenuButton p='0.6rem' mr='16px'>
          <Icon size='24px' name='bell' />
    </MenuButton>
</Badge>
```

**Comment by laurensnl** [comment]
I personally really like Ant Design's approach on the badge: https://ant.design/components/badge/

**Comment by KevinLu** [comment]
Is this still being considered for Chakra UI?

**Comment by KevinLu** [comment]
> 
> 
> Hi!
> This issue hasn't seen any activity recently. We close inactive issues after 35 days to manage the volume of issues we receive.
> If we missed this issue or you want to keep it open, please reply here. That will reset the timer and allow more time for this issue to be addressed before it is closed.

Is this still being considered for Chakra UI?

**Comment by m-ret** [comment]
This is a great idea.

> I personally really like Ant Design's approach on the badge: https://ant.design/components/badge/

**Comment by natbatwat** [comment]
+1

**Comment by DiegoAlessandro** [comment]
+1

**Comment by bryantobing12** [comment]
any update on how we should do this?

**Comment by tannguyencse19** [comment]
Still not implemented in v1.7.3. 

https://ant.design/components/badge/

https://vuetifyjs.com/en/components/badges/

**Comment by Nithur-M** [comment]
> Hi folks, just found myself needing this today; it's fairly trivial to accomplish using an `IconButton` and absolute positioning:
> 
> ```ts
> import { Box, IconButton } from '@chakra-ui/react';
> import { css } from '@emotion/react';
> import { FaBell } from '@react-icons/all-files/fa/FaBell';
> 
> function Badge ({ count }: { count: number }) {
>     return (
>         <IconButton
>             css={css`
>               position: relative !important;
>             `}
>             py={'2'}
>             colorScheme={'gray'}
>             aria-label={'Notifications'}
>             size={'lg'}
>             icon={<>
>                 <FaBell color={'gray.750'} />
>                 <Box as={'span'} color={'white'} position={'absolute'} top={'6px'} right={'4px'} fontSize={'0.8rem'}
>                      bgColor={'red'} borderRadius={'llg'} zIndex={9999} p={'1px'}>
>                     {count}
>                 </Box>
>             </>}
>         />
>     );
> }
> ```
> 
> That's the one I needed, feel free to tune at your heart's contents. It should work with `Avatar` as well applying the same principle.

Thanks for this solution. It's super helpful.
Also, note that the Circle component works better than the Box component in this case.

**Comment by laurensnl** [comment]
There seems to be some demand for an (animated) component like this. Could this issue be reopened @segunadebayo?

https://ant.design/components/badge/

**Comment by ABNERMATHEUS** [comment]
```javascript
 <IconButton
                                size="lg"
                                variant="ghost"
                                aria-label="open menu"
                                icon={
                                    <>
                                        <Avatar icon={ <FaBell />}>
                                         
                                            <AvatarBadge boxSize='1.25em' bg='green.500' ></AvatarBadge>
                                        </Avatar>
                                    </>


                                }
                            />
```

**Comment by dclstn** [comment]
I'd personally do this:

```js
    <Box pos="relative">
      <Button colorScheme="primary">
        My Cart
      </Button>
      {totalItems > 0 ? (
        <Badge
          colorScheme="red"
          pos="absolute"
          variant="solid"
          bgColor="red.500"
          right={-1}
          top={-1}
        >
          {totalItems}
        </Badge>
      ) : null}
    </Box>
```

**Comment by pga5e** [comment]
@segunadebayo we really need this:

my implementation too was this hack using css: 

```
{/* TODO: Red Notification Bedge over Bell Icon */}
              <Box position={"relative"} display={"inline-flex"}>
                <IconButton
                  aria-label="group"
                  variant={"ghost"}
                  icon={<FaRegBell />}
                />
                <Box
                  position="absolute"
                  top="2px"
                  right="4px"
                  bg="#cf3830"
                  color="white"
                  borderRadius="full"
                  w="15px"
                  h="15px"
                  display="flex"
                  alignItems="center"
                  justifyContent="center"
                  fontSize="xx-small"
                >
                  1
                </Box>
              </Box>
```
