### ISSUE TITLE
[Menu] MenuTransition breaks autoselect with multiple menus in the page

### ISSUE THREAD

**Issue by Sebastiansc** [chakra-ui/chakra-ui#1806]
**Describe the bug** A clear and concise description of what the bug is.
* When using `MenuTransition` and rendering multiple menus in the page `autoSelect` fails to select the first item when switching from one open menu to another. It seems `focus` fails to focus the element because it's not painted on the screen by the time it's called.

https://www.loom.com/share/53ea5b34cd0148c8b5ad798ada716bd2

**Expected Behavior** A clear and concise description of what you expected to
happen.
* auto select should work with or without transitions

**Link to minimal reproduction** Please provide a codesandbox link or GitHub
repo with a minimal reproduction of the issue.

- JavaScript CodeSandbox template:
  https://codesandbox.io/s/github/chakra-ui/codesandbox-react-js-template/tree/master
- TypeScript CodeSandbox template:
  https://codesandbox.io/s/github/chakra-ui/codesandbox-react-ts-template/tree/master

**Steps to Reproduce** Clear and concise reproduction instructions are important
for us to be able to triage your issue in a timely manner.

1. Add multiple menus on a page
2. Wrap `MenuList` with `MenuTransition`
3. Open a menu
4. With one menu open, open another menu
5. Notice the first item in the new menu isn't selected

**Suggested solution(s)**

**Desktop (please complete the following information):**

- Browser [e.g. chrome, safari] Chrome

**Additional context** Add any other context about the problem here, or some
background information of how you ran into this bug.

**Comment by with-heart** [comment]
Any way you could prove a CodeSandbox reproduction of this issue? It'd make it easier for us to start investigating.

**Comment by segunadebayo** [comment]
We recently moved to use `framer-motion` for component transitions. We've handled this use-case in the process.

New version to be released soon.
