### ISSUE TITLE
[NumberInput] incrementing twice

### ISSUE THREAD

**Issue by zaguiini** [chakra-ui/chakra-ui#181]
Every time I do some action on the `NumberInput` example on the [docs](https://chakra-ui.com/numberinput) (e.g. increase or decrease), it repeats the action. Example:

- Value is `2`, then I press the increase button once and it becomes `4` instead of `3`.

This happens on Google Chrome on Android, running MIUI 10.3.

**Comment by segunadebayo** [comment]
Oops. I just confirmed this bug. I'll look into it shortly.

I'd appreciate your PR as well

**Comment by zaguiini** [comment]
I'll work on it!
