### ISSUE TITLE
[Docs] Broken link in chakra ui website

### ISSUE THREAD

**Issue by harveyhalwin** [chakra-ui/chakra-ui#1810]
**Description** 

On looking through the [theme page](https://chakra-ui.com/theme), in the colors section. There is a hyperlink after the example for a [default theme](https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/theme) which appears broken. 

It is currently showing a 404 page not found error.

**Comment by santialbo** [comment]
The docs you are seeing are for the v0 version of the library. What you see on master is v1, which hasn't been released yet.
If you want to access the v0 link, just replace `master` with `v0` on the link.
