### ISSUE TITLE
[NumberInput] not showing numeric keyboard

### ISSUE THREAD

**Issue by zaguiini** [chakra-ui/chakra-ui#182]
The `NumberInput` example on the [docs](https://chakra-ui.com/numberinput) doesn't open for edition with the numeric keyboard.

This happens on Google Chrome on Android, running MIUI 10.3. Not tested with other browsers but I suspect the behavior would be the same since the input itself is marked as of type `text`.

**Comment by segunadebayo** [comment]
Hi @zaguiini,

To make the `NumberInput` show the numeric keyboard, simply pass `type="number"` to the `NumberInputField`.

We didn't add it by default because we think `NumberInput` might get it's own "mobile" implementation soon.

**Comment by zaguiini** [comment]
Ok, if this is expected behavior we can close that issue.

If you want me to fill a PR to change the default type to number, I'll do it!
