### ISSUE TITLE
[Menu] Using display: none to hide Menu breaks custom exit animations

### ISSUE THREAD

**Issue by Sebastiansc** [chakra-ui/chakra-ui#1820]
**Describe the bug** A clear and concise description of what the bug is.
* In https://github.com/chakra-ui/chakra-ui/blob/develop/packages/menu/src/use-menu.ts#L275 we are using `display: none` to hide the `MenuList` when it's closed. This doesn't allow for custom exit animations (animations can't run on a display none element) and is also not a performant option for toggling an element's visibility.

**Expected Behavior** A clear and concise description of what you expected to
happen.
* Menu uses properties for hiding that allow the use of custom exit animations

**Link to minimal reproduction** Please provide a codesandbox link or GitHub
repo with a minimal reproduction of the issue.

- JavaScript CodeSandbox template:
  https://codesandbox.io/s/github/chakra-ui/codesandbox-react-js-template/tree/master
- TypeScript CodeSandbox template:
  https://codesandbox.io/s/github/chakra-ui/codesandbox-react-ts-template/tree/master

**Steps to Reproduce** Clear and concise reproduction instructions are important
for us to be able to triage your issue in a timely manner.

**Suggested solution(s)**
* Use opacity and pointer events to hide menu. 

**Desktop (please complete the following information):**

**Additional context** Add any other context about the problem here, or some
background information of how you ran into this bug.

**Comment by segunadebayo** [comment]
We fixed this when migrated most components to use `framer-motion` for their transitions.
