### ISSUE TITLE
Button: Fatal error when rendering with Testing Library

### ISSUE THREAD

**Issue by disposableraft** [chakra-ui/chakra-ui#1822]
(_Preamble: This is my first time submitting an issue for Chakra. I just wanted to say thank you for this great library, and please let me know if I'm missing something here._)

When unit testing the `Button` component with `testing-library/react`, rendering the component causes a fatal error:

> Cannot use 'in' operator to search for 'gray' in undefined

Please see `button.test.tsx` in the codesandbox below. Running the test will reproduce the error message above.

https://codesandbox.io/s/affectionate-hermann-btzin?file=/src/button.test.tsx

One possible fix for this would be to check that `theme.colors` is defined:

```javascript
  if (process.env.NODE_ENV !== "production") {
    var variantColorIsDefined = variantColor != null;
    // Check if theme.colors is defined
    var themeColorsIsDefined = theme.colors != undefined;

    if (variantColorIsDefined && themeColorsIsDefined) {
        ...
```

I would be happy to contribute this, if you think it's a good way forward.

**Comment by ljosberinn** [comment]
Hi @disposableraft - thank you for using Chakra and filing the ticket 👍 

You appear to be on version 0.7 there. The latest pre v1 version is 0.8. This won't fix the issue, but just as a heads up.

You're missing the Chakra providers in your test. For that you may just inline them in your `render` within the test, which becomes messy to manage, so I'd recommend using a [custom render](https://testing-library.com/docs/react-testing-library/setup#custom-render).

The test will pass then:

![image](https://user-images.githubusercontent.com/29307652/91367612-3af87d00-e807-11ea-8bb5-a80ecc546e4c.png)

**Comment by disposableraft** [comment]
@ljosberinn Thanks for this!
