### ISSUE TITLE
[Avatar] Unmounting & mounting an avatar doesn't display the src

### ISSUE THREAD

**Issue by bogdansoare** [chakra-ui/chakra-ui#1827]
**Describe the bug** 
Unmounting & mounting an avatar doesn't display the src 

This mostly happens on safari, but also sometimes in chrome 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2750170/91441822-8a779100-e879-11ea-950d-5218ac78d5b7.gif)

**Expected Behavior** 
The src should be displayed after unmounting & mounting again

**Link to minimal reproduction** 
For example in a Wizard like scenario, after the second step the avatar is missing the src
- https://codesandbox.io/s/gracious-merkle-fzpke?file=/src/App.js

**Steps to Reproduce** 

1. Open the codesanbox
2. Click on next step
3. Observe the missing avatar src

**Suggested solution(s)**

I believe this has something to do with image loading in [useImage](https://github.com/chakra-ui/chakra-ui/blob/master/packages/image/src/use-image.ts#L88)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Safari, Chrome
- Version 13.1.2, 85

**Comment by jmiazga** [comment]
Hi @bogdansoare. When I pull up your codesanbox, I don't see the issue that is shown in the gif. Can you try and refresh your codesandbox page and let me know if the issue is still happening.

**Comment by bogdansoare** [comment]
Hi @jmiazga. Did you try in Safari? This issues mostly happens in Safari for me, in Chrome/Firefox it doesn't always happen. Thanks

**Comment by santialbo** [comment]
It happens on Safari to me **but only if the console is closed** 😂 The moment I open it, everything works fine.

**Comment by bogdansoare** [comment]
@santialbo that's really weird 😅

**Comment by Harrisonl** [comment]
I'm getting the same issue in my app - avatars will randomly display sometimes and not others. Even though checking the console shows the image has been loaded. I know this comment doesn't really help in terms of debugging the issue but just an FYI that it's something that might be happening. I'm using the new `rc` versions if that helps!

**Comment by gifaeriyanto** [comment]
Please check my PR https://github.com/chakra-ui/chakra-ui/pull/2209. The problem is on `useImage` hooks that `avatar` used. The `status` state has a logical default value. I just change it to a static default value and let `useEffect` change it.
