### ISSUE TITLE
[NumberInput] Copy/Paste doesn't work

### ISSUE THREAD

**Issue by Freak613** [chakra-ui/chakra-ui#1838]
**Describe the bug** NumberInput doesn't support Ctrl+A, Ctrl+C, Ctrl-V combinations
Though selecting with cursor is possible, also copy/paste is working through context menu.
I can't find anything specific about this behavior on WAI-ARIA standards, so I assume this behavior is not intentional.
Also, I can't find anything specific in the source code of the component, that could implicitly block such interaction, so it's not clear for me why it doesn't work.

**Expected Behavior** Ctrl+A, Ctrl+C, Ctrl-V combinations should behave like in normal input.
I'm not sure what should be done when pasting non-numeric values. Currently if I paste invalid data through context menu, value is converted to NaN, and that can be a valid option. However, once the value converted to NaN I can't modify input anymore.

**Link to minimal reproduction** Behavior can be tested on documentation site:
https://chakra-ui.com/numberinput

**Desktop (please complete the following information):**

- OS: MacOS 10.14.1
- Browser: Safari 12, Chrome 84
- Version: `@chakra-ui/number-input` of version `1.0.0-rc.2`

**Comment by Freak613** [comment]
I've played with my own implementation of this component and it looks like the problem is at [isValidNumericKeyboardEvent](https://github.com/chakra-ui/chakra-ui/blob/588b3f24e60f2825baaf062025f2b1f4f17608c2/packages/number-input/src/utils.ts#L15) detection.
What happens with shortcuts, is that component receiving `Meta` first and then corresponding letter a/c/v, and these letters are blocked with event detection.
There are two ways I see to solve this problem:
- Allow entering non-numeric letters (the option that I proceed in my implementation). This is dirty and may be not appropriate for following ARIA standards.
- Implement code that will trigger special mode after `Meta` pressed, to execute hotkeys. I'm sure there are libraries implementing this mode on npm, but I can't provide any at the moment.

**Comment by Freak613** [comment]
Actually, I was wrong, `isValidNumericKeyboardEvent` handles meta keys properly.
So implementation seems correct, still not clear why it's not working on the docs site.

**Comment by segunadebayo** [comment]
Hi @Freak613,

What you see in the `develop` branch is the code for v1 which will be officially released soon. The docs site you're pointing to is for v0.8 which definitely has the bug you're talking about.

v1's docs can be found here: https://next.chakra-ui.com/docs/form/number-input

Hope this helps.

Cheers.
