### ISSUE TITLE
[Button] as="a" how to override <a> tag styles?

### ISSUE THREAD

**Issue by richardrobberse** [chakra-ui/chakra-ui#1839]
How do I override the styles of an <a> tag when a button is rendered as an <a> tag?
I have extensively checked the docs but I couldn't find such an example.

Thanks in advance!

**Comment by with-heart** [comment]
Hi @richardrobberse. Could you create a quick CodeSandbox example that we can work from?

**Comment by richardrobberse** [comment]
For some reason, my issue doesn't reproduce on the sandbox so I'll investigate further myself.
Thanks for the swift reply though.

**Comment by with-heart** [comment]
Feel free to re-open if you run into further issues!
