### ISSUE TITLE
[initialColorMode] initialColorMode does not change the default color mode of the app after being saved in local storage. (V1)

### ISSUE THREAD

**Issue by JeremieLeblanc** [chakra-ui/chakra-ui#1843]
The value of initialColorMode does not change the default color mode after it has been set in local storage the first time.

![Screenshot_1](https://user-images.githubusercontent.com/9596165/91575758-e09e1000-e91d-11ea-989c-a6b385c0783a.png)

When changing the initialColorMode value, I would expect the apps default color mode to change to the corresponding value and override the value saved in the localstorage.

Here is a codesandbox showcasing the issue:
https://codesandbox.io/s/chakra-ui-initialcolormode-3o307?file=/src/index.js

To reproduce, change the value of initialColorMode inside the index.js file from light to dark and refresh the page.
Do this a few time going back from one mode to the next and the app will not change default color modes.

- OS: Windows 10 Home
- Browser: Chrome
- Version: 84.0.4147.135

I have also tested with Edge and Firefox.

**Comment by JeremieLeblanc** [comment]
Looking deeper into this, it seems that this may be intentional as there is currently no ways of knowing if the user changed it manually or if it was set by the default. Furthermore, the only time this is really an issue is while testing the app, so I believe the current implementation is fine.
I am closing this issue for now.

**Comment by ljosberinn** [comment]
On a sidenote, @JeremieLeblanc, color mode usage has been refined in the `develop` branch so this shouldn't be an issue with the next release :)

**Comment by JeremieLeblanc** [comment]
> On a sidenote, @JeremieLeblanc, color mode usage has been refined in the `develop` branch so this shouldn't be an issue with the next release :)

Does this mean that color mode will change from rc.2 to rc.3?

**Comment by ljosberinn** [comment]
yes, it will fix outstanding issues with SSG pages:
- colormode config from theme [was removed](https://github.com/chakra-ui/chakra-ui/commit/47ea2ee70d939fa6cae06d0faa63553b55170c81)
- `ColorModeScript` [was added](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/color-mode/src/color-mode-script.tsx#L46) - it receives the `defaultColorMode` via props; defaults to `light`
- use `ColorModeScript` [in `_document`](https://github.com/chakra-ui/chakra-ui/blob/develop/website/pages/_document.tsx#L17)

**Comment by JeremieLeblanc** [comment]
Awesome, thanks!
