### ISSUE TITLE
[NumberInput] Bad UX on mobile

### ISSUE THREAD

**Issue by zaguiini** [chakra-ui/chakra-ui#185]
It's not easy to increase or decrease the number on mobile phones. The action buttons are too small.

![image](https://user-images.githubusercontent.com/26530524/66938797-3b858c00-f018-11e9-919d-d149a0f63913.png)

We could put them side by side with square buttons instead of two small buttons on top of each other.

**Comment by segunadebayo** [comment]
Hi @zaguiini, 

This NumberInput pattern isn't appropriate for mobile like I mentioned earlier. Here's an example of what a mobile implement might look like: 

![image](https://user-images.githubusercontent.com/6916170/66939323-c5465100-f03a-11e9-971e-afe45e9778f4.png)

We'll add this type of component soon so improve the mobile UX.

**Comment by zaguiini** [comment]
Ok! Closing this issue then. Thanks!

**Comment by segunadebayo** [comment]
Since we have the `useNumberInput` hook, we can easily create this mobile version.
