### ISSUE TITLE
[Documentation] "float" is missing

### ISSUE THREAD

**Issue by akiarostami** [chakra-ui/chakra-ui#1851]
In the documentation, in [Style Props > Other Props](https://next.chakra-ui.com/docs/style-props#other-props), *float* is missing.

**Expected Behavior** 
Expect to see *float* as one of the accepted [props](https://next.chakra-ui.com/docs/style-props#other-props).

**Comment by segunadebayo** [comment]
Thank you for catching this.

I've just pushed an update and will go live in the next Vercel deployment.

Cheers
