### ISSUE TITLE
help with scrollable tabs

### ISSUE THREAD

**Issue by waptik** [chakra-ui/chakra-ui#1852]
Hi! New to chakra and trying out some few components.
I'd like to ask if there's a way to achieve scrollable tabs like in [MUI](https://material-ui.com/components/tabs/#scrollable-tabs).
This is my base setup for it: https://gist.github.com/waptik/64088f0bc6358fc719bcea02cbea8f08
I asked the same question on [discord](https://discord.com/channels/660863154703695893/695564068895064094/746752116676362280) but got no reply.

**Comment by neighborhood999** [comment]
Try to can add `overflowX="scroll"` prop to your `TabList` component.

**Comment by waptik** [comment]
> Try to can add `overflowX="scroll"` prop to your `TabList` component.

Thanks for the feedback. I did so but only shows the scrolling design and nothing elseas you can in the pics below
PC ==> ![tablist overflow-x pc](https://user-images.githubusercontent.com/1687551/91627829-cc075980-e9a9-11ea-92d8-74ed9b921680.jpg)
Mobile ==> ![tablist overflow-x mobile](https://user-images.githubusercontent.com/1687551/91627849-fbb66180-e9a9-11ea-9779-f3ddc5f0d204.jpg)

**Comment by binajmen** [comment]
Hi @waptik, can you share your solution (if you solved it) ?

**Comment by Tooluloope** [comment]
Yeah, Also need the solution

**Comment by qlereboursBS** [comment]
Same here @waptik

**Comment by waptik** [comment]
I don't remember ever solving it as my current codebase no longer contain the code i posted in my gist.
Currently, i have reduced the number of tabs as some of them are not being used.

Sorry guys!

**Comment by binajmen** [comment]
I'm using this on my project. Certainly not a perfect solution, but works for me ;)

```js
  return (
    <Flex
      position="sticky"
      top="0"
      bgColor="primary.100"
      zIndex="sticky"
      height="60px"
      alignItems="center"
      flexWrap="nowrap"
      overflowX="auto"
      px="2"
      css={{
        WebkitOverflowScrolling: "touch",
        msOverflowStyle: "-ms-autohiding-scrollbar"
      }}
    >
      {items.map(item =>
          <Flex key={id} flex="0 0 auto" as="nav">
            <Button
              as="a"
              href={`#${id}`}
              id={`bar-${id}`}
              variant="ghost"
              color="black"
              colorScheme="none"
            >{item.name}</Button>
          </Flex>
        )}
    </Flex>
  )
```

**Comment by Howard86** [comment]
I managed to find a working version for my project

```tsx
        <TabList
          overflowY="hidden"
          sx={{
            scrollbarWidth: 'none',
            '::-webkit-scrollbar': {
              display: 'none',
            },
          }}
        >
          {items.map((item) => (
            <Tab key={item.id} flexShrink={0}>
              {item.name}
            </Tab>
          ))}
        </TabList>
```

**Comment by masafumimori** [comment]
Hey! @Howard86 
This worked for me and helped me lots! Thanks :)

**Comment by vytautas-pilk** [comment]
What works for me is simply setting `display='flex'` and `flexDirection='column'` to `<Tabs>` component and then `overflowY='scroll'` to `<TabPanels>` component.

**Comment by GustavoMelloGit** [comment]
For some reason i cannot scroll to my firsts tabs when using any of the solutions above. it just clips them

**Comment by GustavoMelloGit** [comment]
Got it guys. that is the solution that i manage to make it work
```
<Box overflow='auto'>
   <TabList w='max-content'>
        {insert tab here}
  </TabList>
</Box>
```

**Comment by kicks321** [comment]
> w='max-content'

You are a god send, IDK why i didn't think to just wrap tablist lol, it still perfectly plays well with the internal tabs context and everything.

**Comment by ayodeji334** [comment]
@GustavoMelloGit. The solution worked for me.

**Comment by therealbluepandabear** [comment]
This should work, and you can also drag to scroll:

```TSX
function EzTab(props: EzTabProps): JSX.Element {
    const [isDragging, setIsDragging] = useState(false)
    const [startX, setStartX] = useState<number | null>(null)
    const [scrollLeft, setScrollLeft] = useState(0)

    const [tabIndex, setTabIndex] = useState(0)

    const tabListRef = useRef<HTMLDivElement>(null)

    useEffect(() => {
        if (isDragging) {
            document.addEventListener('mousemove', mouseMoveHandler)
            document.addEventListener('mouseup', mouseUpHandler)
        }
    }, [isDragging])

    function tabChangeHandler(index: number) {
        const scrollOffset = scrollLeft - tabListRef.current!.scrollLeft

        if (Math.abs(scrollOffset) <= 15 && Math.abs(scrollOffset) >= 0) {
            setTabIndex(index)
        }
    }

    function mouseDownHandler(e: React.MouseEvent<HTMLDivElement>) {
        setIsDragging(true)
        setStartX(e.pageX)
        setScrollLeft(tabListRef.current!.scrollLeft)
    }

    function mouseMoveHandler(e: MouseEvent) {
        if (!isDragging) {
            return
        }

        const delta = e.pageX - (startX ?? 0)
        tabListRef.current!.scrollLeft = scrollLeft - delta
    }

    function mouseUpHandler() {
        setIsDragging(false)

        document.removeEventListener('mousemove', mouseMoveHandler)
        document.removeEventListener('mouseup', mouseUpHandler)
    }

    return (
        <Tabs isManual={true} isLazy={true} variant="unstyled" onChange={tabChangeHandler} index={tabIndex}>
            <TabList
                ref={tabListRef}
                onMouseDown={mouseDownHandler}
                overflowY="scroll"
                sx={{
                    "::-webkit-scrollbar": {
                        display: "none"
                    }
                }}
            >
                {props.headers.map((header, index) => (
                    <Flex flexDirection="column">
                        <Tab 
                            key={index} 
                            height="40px" 
                            width="55px" 
                            alignItems="center"
                            justifyContent="center"
                            textColor={tabIndex === index ? "blue.500" : ""}
                        >
                            {header}
                        </Tab>
                        {tabIndex === index && (
                            <Box width="100%" height="3px" background={tabIndex === index ? "blue.500" : ""} />
                        )}
                    </Flex>
                ))}
            </TabList>
            
            <TabPanels>
                {props.content.map((jsx) => (
                    jsx
                ))}
            </TabPanels>
        </Tabs>
    )
}
```

**Comment by EzequiasCalvo** [comment]
Another solution: 
Add maxWidth to Tabs and then overflow: scroll works.
` <Tabs maxWidth="100%">
            <TabList overflow="scroll">
              <Tab>1</Tab>
              <Tab>1</Tab>
              <Tab>1</Tab>
            </TabList>`

**Comment by arhaanb** [comment]
Has anyone tried this with a TabIndicator? It doesn't seem to be working properly when the Tabs are scrolled

**Comment by gostraa** [comment]
for tag Tabs width={'100%'}
for tag TabList
          overflowY="hidden"
          sx={{
            scrollbarWidth: 'none',
            '::-webkit-scrollbar': {
              display: 'none',
            },
          }}

**Comment by medkhalilbk** [comment]
` <Tabs maxWidth="100%"> <TabList overflow="scroll"> <Tab>1</Tab> <Tab>2</Tab> <Tab>3</Tab> </TabList>`

This works for me !

**Comment by Junaid994** [comment]
I have recently implemented the solution. Of course further improvements can be made i.e. U.I part or scroll points etc.

Working Example: https://codesandbox.io/s/vigilant-shape-9mh7q9

[Scrollable.Tabs.-.Horizontally.txt](https://github.com/user-attachments/files/16238068/Scrollable.Tabs.-.Horizontally.txt)
![347765675-3af91364-ab30-4b64-8dd3-2079aa523ec3](https://github.com/user-attachments/assets/4d6baab2-0fea-4468-92c8-09c7e3eb9527)

**Comment by ats1999** [comment]
```jsx
//  flexShrink={0} fixed the issue, source ChatGPT

 <Tabs.Trigger flexShrink={0} key={t} value={t} asChild>
              <Link className="no-link-color" href={`#${t}`}>
                {capitalizeText(t)}
              </Link>
            </Tabs.Trigger>
```
