### ISSUE TITLE
Request to add `update` to Popover's internalState

### ISSUE THREAD

**Issue by matchu** [chakra-ui/chakra-ui#1853]
**What problem does this feature solve?** I have a `Popover` with a loading state, so its content size changes significantly after loading, which causes the popover to be misaligned. I'd like to let `Popover` know to recompute the size and positioning when loading is done.

**What does the proposed API look like?** `Popover` already provides some state-y values to consumers: `<Popover>{({isOpen, onClose}) => …}</Popover>`. We could add another function `update` (or some more Chakra-y name), which consumers can call to let `Popover` know that the content has significantly changed.

**Describe alternatives you've considered** I've tried hacking the element to use a fixed size no matter the state, but it's visually clunky for my use case. I also considered automatically dismissing and re-opening the popover when the content changes, but decided it would be too disruptive to keyboard focus and screen readers.

**Additional context** [I think Popper already provides this functionality!](https://popper.js.org/docs/v2/lifecycle/#manual-update) If we call `popper.update()` on the internal `popper` instance, I think it will do exactly what I'm proposing. If we're lucky, this change could be as simple as `{update: () => popper.update()}`?

**Comment by segunadebayo** [comment]
Hi @matchu,

What version of Chakra UI are you using? Can you provide a low-res reproduction of this issue so it's easier for us to resolve?

Thank you

**Comment by matchu** [comment]
Hi yes! [Here's a code sample](https://github.com/matchu/chakra-popover-demo/blob/master/src/App.js), and [here it is running](https://chakra-popover-demo.vercel.app/)!

I think I've found a workaround that I can use for now though: if I simulate a window resize event as follows, then the Popper library will resize and reposition the popper like I want. I've included that behavior in the demo, too.

```
window.dispatchEvent(new Event("resize"));
```

So at this point my issue isn't getting things working, but rather just a proposal to simplify the API for Chakra users! Lower priority for me now.

Thanks for taking a look!

**Comment by kltdwrds** [comment]
@segunadebayo Any update on this?  I'm running into the same issue with the Menu component.  In my case `MenuItems` are filtered via user input, and when the number of items differs from the initial count, the menu's position is off.

@matchu resize event does the trick, but it's certainly a hack.  I'm happy to consider opening a PR if a maintainer can outline the preferred approach.

**Comment by segunadebayo** [comment]
I just pushed an update that provides the internal `forceUpdate` function from `popper.js` so you can force repositioning.
