### ISSUE TITLE
[Select] outline variant of Select in dark mode  looks similar to filled variant

### ISSUE THREAD

**Issue by hoodwink73** [chakra-ui/chakra-ui#1855]
The `variant="outline"` visually looks similar to `variant="filled"` for `<Select />` only in dark mode. 
The distinction is quite prominent though in light mode.

![Kapture 2020-08-29 at 13 42 47](https://user-images.githubusercontent.com/1285699/91632304-8ffde400-e9fd-11ea-9b12-9e4488403dae.gif)

**Expected Behavior** 
`<Select variant="outline" />` should show a border around the Select. The `border-color` should have a decent contrast with the dark background. And the background of the component should appear as transparent

**Comment by segunadebayo** [comment]
Thanks for this feedback @hoodwink73.

I've finetuned the UI and theme for the input a bit more following your suggestion.

We'll release an update soon.
