### ISSUE TITLE
Help with Grid.

### ISSUE THREAD

**Issue by Zono4ever** [chakra-ui/chakra-ui#1856]
I think you should add more example for grid, I've search for 4h but can't find any document or example to do with grid column!

** Example **
```
<Grid templateColumns="repeat(12, 1fr)" gap={6}>
 <Box w="100%" gridTemplateColumns="**span 3**" h="10" bg="blue.500" />
   <Box w="100%" gridTemplateColumns="**span 9**" h="10" bg="blue.500" />
</Grid>
```
this is what I want, I want to have 2 column 
first one is 3/12
second one is 9/12 
**************************
Help me please !! 
Thank you!!

**Comment by ljosberinn** [comment]
fwiw, the grid component is just the regular CSS Grid: https://developer.mozilla.org/en-US/docs/Web/CSS/grid

**Comment by Zono4ever** [comment]
> fwiw, the grid component is just the regular CSS Grid: https://developer.mozilla.org/en-US/docs/Web/CSS/grid

This is what I need for chakra ui **gridColumn="span 3"**

Thanks for your help!
