### ISSUE TITLE
[Drawer] DrawerBody overflow:auto is unscrollable

### ISSUE THREAD

**Issue by Wisedemic** [chakra-ui/chakra-ui#1862]
Visit: https://chakra-ui.com/ or https://next.chakra-ui.com/docs/components/drawer, and open a drawer. 
- Duplicate the DrawerBody's content until it has enough content for the default "overflow: auto" to enable an overflow-y: scroll; 

Try scrolling. Are you able to? 

I could not figure out a solution myself! Let me know how I can better assist.

Occurrences on both Windows 10 and MacOS devices.

![Untitled](https://user-images.githubusercontent.com/11144553/91648398-1aae0580-ea35-11ea-941d-ad070b0ed2d9.png)

**Comment by with-heart** [comment]
Interesting. I'm not able to scroll on the 0.8 docs, but I can scroll fine for the 1.0 docs at https://next.chakra-ui.com using Chrome, Safari, and Firefox.

**Comment by with-heart** [comment]
@Wisedemic Can you verify that it's not working on the `next` docs still?

**Comment by kandhan-kuhan-t** [comment]
I had this problem in my project. I had to pass a prop "blockScrollOnMount" set to false.
` <Drawer
         scrollBehavior={'inside'}
         blockScrollOnMount={false}
/>`
"blockScrollOnMount" is a modal prop and is true by default.

**Comment by segunadebayo** [comment]
@with-heart, kindly re-open this if it's still an issue in v1.

**Comment by ImSolitude** [comment]
This is still an issue and it's really annoying, and @kandhan-kuhan-t solution doesn't fix it, Check this video out https://drive.google.com/file/d/1k1YzoBZ40MkX9qKIRLviIzbuPJlqACMo/view, Try to fill your drawer content with anything that exceeds the viewport put `overflow-y: auto` to `DrawerContent` and observe.

**Comment by with-heart** [comment]
@ImSolitude Any way you could provide a CodeSandbox reproduction? I still haven't been able to reproduce this. https://codesandbox.io/s/vigilant-benz-iyz8u?file=/src/App.tsx

**Comment by gaurangrshah** [comment]
Just an FYI this is still an issue in V1. Although the "blockScrollOnMount={false}" fix is a partial fix for my needs -- since I'm only currently using this drawer in development, it's not a huge concern. Just to be clear I say this is a partial fix because I think the right fix would be to lock the actual body scroll but leaving the drawer to scroll as needed. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1086269/94630744-9d282000-0294-11eb-8e89-342eef25d210.gif)

**Comment by kandhan-kuhan-t** [comment]
> I had this problem in my project. I had to pass a prop "blockScrollOnMount" set to false.
> ` <Drawer scrollBehavior={'inside'} blockScrollOnMount={false} />`
> "blockScrollOnMount" is a modal prop and is true by default.

This happened because of my mistake!
I was using v1 of chakra-ui and referred to chakra-ui.com instead of next.chakra-ui.com (the difference being how DrawerOverlay is used).
This was never an issue @gaurangrshah
