### ISSUE TITLE
Export problems with @chakra-ui/core 1.0.0-rc.2

### ISSUE THREAD

**Issue by hahahatey** [chakra-ui/chakra-ui#1868]
Hello everyone. 
I am trying to start a project with @chakra-ui/core 1.0.0-rc.2.
I have problems there are not such exports as theme, extendTheme, ColorModeScript that accordingly to the documentation must be there. 
Where am i wrong?
https://codesandbox.io/s/wizardly-minsky-d9ukv

**Comment by ljosberinn** [comment]
You got unlucky there, `rc.3` was supposed to be released earlier but wasn't yet - but the docs were.

I updated your sandbox with the `rc.2` setup - `ColorModeScript` e.g. doesn't exist here yet: https://codesandbox.io/s/peaceful-grass-kp4di?file=/src/App.tsx

I'll let you know once `rc.3` is out and keep this opened until then.

**Comment by ljosberinn** [comment]
`rc.3` is out now! 🎉 🚀
