### ISSUE TITLE
[Stack] Fix spacing of items when flex-direction is reverse

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#187]
Currently, `spacingProps` [does not take](https://github.com/chakra-ui/chakra-ui/blob/3c56d1fb1f9f269c7e3ce036a02f6f374e43d003/packages/chakra-ui/src/Stack/index.js#L32-L35) reversed `direction` into account. For reversed direction, `ml` and `mt` should be used instead of `mr` and `mb`.

**Comment by omarkhatibco** [comment]
@kripod I was ging to report about this problem.
