### ISSUE TITLE
[Toast & Alert] Alert doesn't use correct backgroundColor when inside a Toast with Dark Mode. 

### ISSUE THREAD

**Issue by fr3fou** [chakra-ui/chakra-ui#1875]
**Describe the bug**
If a Toast has a custom render function which contains an Alert and Dark Mode is enabled, the backgroundColor of the Alert seems to be incorrect.

![image](https://user-images.githubusercontent.com/1344906/91666221-befe7d80-eb03-11ea-938a-7b29d08684a5.png)

**Expected Behavior** 

The Alert should change its backgroundColor, based on whether Dark Mode or Light Mode is being used, as shown on the "regular" Alert.

**Link to minimal reproduction** 

https://codesandbox.io/s/zen-morse-4njei?file=/src/App.tsx

**Steps to Reproduce** 

1. Open the CodeSandbox
2. Make sure you're in Dark Mode
2. Click on the `Click me!` button

**Suggested solution(s)**

I have not come up with a solution yet.

**Desktop**

- OS: Windows
- Browser: Chrome
- Version: 84.0.4147.135

Thanks to @impzero for helping me find this bug.

**Comment by segunadebayo** [comment]
Thanks for catching this. I've just pushed a fix for it.

We'll release shortly
