### ISSUE TITLE
Local run of `docs:build` causing incorrect output

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1877]
When non-org users run `docs:build` locally, the `.all-membersrc` produces incorrect output because they don't have access to members who don't publicly list their membership in the org.

**Comment by with-heart** [comment]
#1876 is an example of this

**Comment by segunadebayo** [comment]
`docs:build` is preserved for the CI and for maintainers to run locally.

I've modified the scripts so that `docs:build `works for non-org members and `docs:build-ci` works as the former `docs:build`.

Make sense?
