### ISSUE TITLE
[Color Mode] The colour mode is incorrect on load

### ISSUE THREAD

**Issue by rshackleton** [chakra-ui/chakra-ui#1880]
**Describe the bug** A clear and concise description of what the bug is.

On load, the colour mode is incorrect, doesn't respect `prefers-color-scheme` and doesn't use the value from local storage.

![image](https://user-images.githubusercontent.com/13448395/91669961-00495a00-eb11-11ea-9913-e52e372f6d3e.png)

**Expected Behavior** A clear and concise description of what you expected to
happen.

The colour mode from local storage should be used, or the media query result should be respected on load.

**Link to minimal reproduction** Please provide a codesandbox link or GitHub
repo with a minimal reproduction of the issue.

This application is experiencing the issue, it is an electron app.

https://github.com/rshackleton/twitch-control-centre/tree/19a3dbb24e48d43ba0376d79efefaf42034f8473

**Steps to Reproduce** Clear and concise reproduction instructions are important
for us to be able to triage your issue in a timely manner.

1. Run the application.
2. When the main window has loaded the colour scheme doesn't respect the OS theme or use the local storage value.

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome (in Electron)
- Version: 83

**Additional context** Add any other context about the problem here, or some
background information of how you ran into this bug.

**Comment by ljosberinn** [comment]
We are aware of a bug that reintroduced flashing the default color mode (light) which gets overriden near-instantly to the stored one, just as it was pre-`rc.2`.

But it looks like in your case, not even that is occuring? That must be some interaction issue with electron I fear. I'll investigate in the upcoming days, thanks.

**Comment by praneetrohida** [comment]
I'm getting the same issue in rc.3. Worked fine in rc.2. It does not even respect the `initialValue` prop passed to `ColorModeScript`. I'm running the app inside electron

**Comment by bakate** [comment]
I've passed a default value to my container and it seems working for now: 
****
`const Container = ({ children }) => {
  const { colorMode } = useColorMode()
  const bgColor = { light: 'gray.200', dark: 'gray.900' }
  const color = { light: 'gray.500', dark: 'white' }
  return (
    <Stack
      direction='column'
      **color={color[colorMode] || color.light}
      bg={bgColor[colorMode] || bgColor.light}**
      p='0 2rem'
      h='100vh'
      mx='auto'
      ### spacing={1}>
      {children}
    </Stack>
  )
}`
