### ISSUE TITLE
Replicate space-x-n and space-y-n from tailwindcss

### ISSUE THREAD

**Issue by ralphilius** [chakra-ui/chakra-ui#1884]
**What problem does this feature solve?** 
The `space-x-n` and `space-y-n` features of tailwindcss is really cool. Do we have anything to replicate such behavior? 

Documentation here: https://tailwindcss.com/docs/space#class-reference

**Comment by marekzelinka** [comment]
Yes, we do have the `<Stack />` component! Take a look [here for ChakraUI version 0.8 (current)](https://chakra-ui.com/stack#usag) or [here for ChakraUI V1 (next)](https://next.chakra-ui.com/docs/layout/stack#usage)

**Comment by with-heart** [comment]
`Stack` is one of my favorite components! Definitely gives us the same behavior :)
