### ISSUE TITLE
Expose the Popper options for overlay components

### ISSUE THREAD

**Issue by praneetrohida** [chakra-ui/chakra-ui#1885]
**What problem does this feature solve?** 
I am rewriting my app to use chakra-ui for everything instead of other 3rd party components. There are some advanced cases where I need more control over the positioning of the Menus and Popups. For example, I have a use case where a menu appears on clicking a 'more' icon on a tab. The menu can also be opened by right-clicking anywhere on the tab. In that case, the menu should be positioned near the cursor, instead of the MenuTrigger. `reactjs-popup` allowed me to do this with offsetX and offsetY props. It would be helpful to have similar control in Chakra.

**What does the proposed API look like?** 
All the overlay components should have props that allow a better control over the component's positioning. An alternate solution would be to expose a prop called `popperOptions` that can allow the user to directly control the underlying popper.js instance.

**Comment by with-heart** [comment]
Closing this as part of our backlog cleanup.
