### ISSUE TITLE
Add an alternate way to detect click outside (using overlay)

### ISSUE THREAD

**Issue by praneetrohida** [chakra-ui/chakra-ui#1886]
**What problem does this feature solve?**
 I am using chakra-ui inside an electron app with webviews. The app uses webviews. For popups and menus, I suppose chakra-ui uses a click listener on the document to detect if the user clicks outside the component. This solution does not work if the user clicks on a webview, since the event gets fired on the webview and not the document. `reactjs-popup` solves this problem by rendering an overlay and detecting clicks on the overlay.

**What does the proposed API look like?** 
I think an optional `MenuOverlay` and `PopupOverlay` component should be exposed, just like the `ModalOverlay`.

**Comment by with-heart** [comment]
Closing this as part of our backlog cleanup. I believe 1.0 may solve this issue for you @praneetrohida as it uses a different method to detect when items are clicked outside of a menu.
