### ISSUE TITLE
[Callout] no longer seems to exists while Upgrading from v0.x to v1.x

### ISSUE THREAD

**Issue by nisarhassan12** [chakra-ui/chakra-ui#1890]
Hi!

We are upgrading our codebase to `v1.x` In a file, we are using the `Callout` component but I'm getting the following TypeScript error: 

```
Module '"../../../../node_modules/@chakra-ui/core/dist/types"' has no exported member 'Callout'.ts
```

also, the Docs here does not seem to mention https://next.chakra-ui.com/docs/migration what it is renamed to.

**Comment by with-heart** [comment]
I wasn't aware this was even a thing. It's not documented in `v0`, and the commit message for adding it was "Add Callout component for docs", so I'm not sure it was ever intended to be a public component.

It appears to work the same as or similar to `Alert` with a `variant` of `subtle`. Is there a use case that `Alert` doesn't cover for you?

**Comment by nisarhassan12** [comment]
Many Thanks, @with-heart switching to an `Alert` did the job from me.

**Comment by with-heart** [comment]
@nisarhassan12 Glad to hear it!
