### ISSUE TITLE
[Icon] Type errors on `@chakra-ui/icons` components

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1903]
**Describe the bug** A clear and concise description of what the bug is.

The icons from `@chakra-ui/icons@1.0.0-rc.3` are throwing the following error:

> Type '{}' is missing the following properties from type ...

**Expected Behavior** A clear and concise description of what you expected to
happen.

Icons should not require any props.

**Link to minimal reproduction** Please provide a codesandbox link or GitHub
repo with a minimal reproduction of the issue.

https://codesandbox.io/s/snowy-cache-3cmli?file=/src/App.tsx

**Suggested solution(s)**

Adjust the types of `Icon` and/or `createIcon` so that all props are optional.

**Additional context** Add any other context about the problem here, or some
background information of how you ran into this bug.

**Comment by KarenEfereyan** [comment]
@with-heart id love to help with this. Though I am a new contributor. Can you guide me through?
