### ISSUE TITLE
Document using `pointerEvents="none"` for `InputLeftAddon`/`InputRightAddon` click-through

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1907]
This resolves the issue #1905 was created for without needing any additional API work. Users can pass `pointerEvents="none"` to these elements to allow clicking on them to focus the `input`.

Here's an example: https://codesandbox.io/s/winter-fog-b3kyw?file=/src/App.tsx

Clicking the `AddIcon` focuses the `input`. The icon will currently disappear on focus due to #1900, which has already been fixed but not yet released.

**Comment by segunadebayo** [comment]
Done!
