### ISSUE TITLE
Docs: add copy to clipboard to install/import snippets

### ISSUE THREAD

**Issue by jescowuester** [chakra-ui/chakra-ui#191]
Right now examples of import like
```
import { Button } from "@chakra-ui/core";
```
Don't have that little copy button in the top right corner, would be nice to add it there as well. 

Happy To submit a PR for this if this is desired.

**Comment by segunadebayo** [comment]
Yes please, submit a PR for this and I'll merge it.

**Comment by mjsarfatti** [comment]
At the moment many snippets are still not copy-pastable, eg. all of the snippets in https://chakra-ui.com/getting-started

Is it possible to switch off the readonly mode?
