### ISSUE TITLE
body has some weird margin-right when the Drawer is open while upgrading to 1.x

### ISSUE THREAD

**Issue by nisarhassan12** [chakra-ui/chakra-ui#1915]
Hi.

We are upgrading to v 1.x

After the update when the Drawer is opened body element has now some margin-right applied to it. As a quick fix I have added the following:

```tsx
onClick={() => { 
  onToggle();
  document.body.setAttribute('style', 'margin-right: 0 !important');
}}
```
Reference: https://github.com/NeonLaw/codebase/pull/744/#discussion_r481433174

It can be reproduced on this PR https://github.com/NeonLaw/codebase/pull/744/

![image](https://user-images.githubusercontent.com/46004116/91906870-527dad00-ecc2-11ea-9ef6-7be9a41a5b3c.png)

**Comment by segunadebayo** [comment]
Thanks for reporting this @nisarhassan12. I've pushed a fix for this.

It'll be release shortly.

**Comment by Zoot01** [comment]
This is still not fixed in version  "@chakra-ui/react": "^2.3.4". Please reopen.

**Comment by umershaikh97** [comment]
I am facing the same issue while using the drawer component.  `"@chakra-ui/react": "^2.4.2"`

**Comment by bigen1925** [comment]
I also found weird margin of body with using `Modal`, but it was my mistake.

I used `ModalFooter` outside `ModalContainer`.

```tsx
<Modal ...>
  <ModalOverlay />
    <ModalContent />
      // <ModalFooter />  // ModalFooter should be inside ModalContent
    </ModalContent>

    <ModalFooter /> // but was outside
</Modal>
```

I moved ModalFooter to inside ModalContent, then the margin was removed.

**Comment by caiofeuser** [comment]
stiil having the same weird behavior on Drawer component. When its open i have a margin-right beeing added to the body
