### ISSUE TITLE
[AspectRatio]Display some weird text before load image when used in production

### ISSUE THREAD

**Issue by Masaokb** [chakra-ui/chakra-ui#1919]
# Bug report

## Describe the bug
Using `AspectRatio` and `Image`, before the image has been loaded, some weird text (maybe related to css classes or properties chakra generated) appears.
**This can be seen in [the example in documentation](https://next.chakra-ui.com/docs/layout/aspect-ratio).**

I cannot find this bug in development env.

## To reproduce
Just use `Image` in `AspectRatio` in production env.

## Screenshots
![image](https://user-images.githubusercontent.com/18113551/91928894-268d1680-ed18-11ea-99c9-a52222312a97.png)
![image](https://user-images.githubusercontent.com/18113551/91928921-33aa0580-ed18-11ea-9fdc-8b7f0359be20.png)

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of @chakra-ui/core: 1.0.0-rc.3
- Version of Node.js: v10.16.3

**Comment by segunadebayo** [comment]
Hi @Masaokb 

I can't seem to reproduce this on my end.

@with-heart Kindly re-open this once we have a correct reproduction.
