### ISSUE TITLE
Property 'type' does not exist on VisuallyHidden compoenent types

### ISSUE THREAD

**Issue by ChrisLusted** [chakra-ui/chakra-ui#192]
Hello, 

i'm using an example from the docs [here](https://chakra-ui.com/controlbox#usage) in my project I get a Typescript error on the `VisuallyHidden` component. I think there maybe an issue with the type definition.

```
Type '{ type: string; as: "input"; }' is not assignable to type 'IntrinsicAttributes & RefAttributes<any> & HTMLAttributes<any> & LayoutProps & ColorProps & SpaceProps<ReactText> & BordersProps & BackgroundProps<ReactText> & ... 14 more ... & { ...; }'.
  Property 'type' does not exist on type 'IntrinsicAttributes & RefAttributes<any> & HTMLAttributes<any> & LayoutProps & ColorProps & SpaceProps<ReactText> & BordersProps & BackgroundProps<ReactText> & ... 14 more ... & { ...; }'.ts(232
```

created a codepen example here - https://codesandbox.io/s/chakra-ts-starter-ii7wc

**Comment by segunadebayo** [comment]
Hi @ChrisLusted,

Yes, it's an issue with the type definition. We're currently migrating the codebase to TS. Once we release it, this issue will be resolved.

**Comment by tafelito** [comment]
is there a solution in the meantime, before the code is migrated to TS?
