### ISSUE TITLE
[Drawer] Drawer Overlay Issue

### ISSUE THREAD

**Issue by harveyhalwin** [chakra-ui/chakra-ui#1920]
# Bug report

## Describe the bug

I had used the drawer component in the project and underlying it is a couple of Box components with sliders in it. The thumb of the slider component is visible when the drawer is opened. I caught this issue, when i was using the dark mode. The issue maybe on the slider thumb zIndex or on the drawer itself. 

## To reproduce

1. Add Slider component 
2. Add Drawer component
3. Open the Drawer component
4. Make sure drawer is not the same color as the slider thumb.
5. See Error

## Expected behavior

The slider thumb should not be visible through the drawer.

## Screenshots

![2020-09-02_09-40](https://user-images.githubusercontent.com/41739034/91931464-22a1ca00-ed01-11ea-9f2d-32511cba06a3.png)

## System information

- OS: Linux (Pop Os)
- Version of @chakra-ui/core: 1.0.0-rc.3

**Comment by segunadebayo** [comment]
Thanks for reporting this @harveyhalwin. I've just pushed a fix for this.

We'll cut a new release soon.
