### ISSUE TITLE
Tooltip not showing when within modal

### ISSUE THREAD

**Issue by DanLeCornu** [chakra-ui/chakra-ui#1927]
# Bug report

## Describe the bug

When the Tooltip component is used within the Modal component, the tooltip message isn't showing on hover of the Tooltip's children

## To reproduce

Add a Tooltip component within a Modal component

## Minimal reproduction

```
import React from "react"
import {
  useDisclosure,
  Button,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalCloseButton,
  ModalBody,
  Tooltip,
  ModalFooter,
  Text,
} from "@chakra-ui/core"

export const Example: React.FC = () => {
  const { isOpen, onOpen, onClose } = useDisclosure()
  return (
    <>
      <Button onClick={onOpen}>Open Modal</Button>
      <Modal isOpen={isOpen} onClose={onClose}>
        <ModalOverlay />
        <ModalContent>
          <ModalHeader>Tooltip modal issue</ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            <Tooltip label="hello!" aria-label="hello!">
              <Text>Hovering over this should show a tooltip :(</Text>
            </Tooltip>
          </ModalBody>
          <ModalFooter>
            <Button variantColor="red" onClick={onClose}>
              Close
            </Button>
          </ModalFooter>
        </ModalContent>
      </Modal>
    </>
  )
}

```

## Expected behaviour

Tooltip should show message when hovering over Tooltip children

## System information

- OS: macOS
- Browser: Safari, Firefox, Chrome
- Version: "@chakra-ui/core": "^0.8.0",
- Version of Node.js: v14.4.0

**Comment by santialbo** [comment]
This was already reported on https://github.com/chakra-ui/chakra-ui/issues/1604
You need to set the zIndex of the tooltip
On v1 this won't be necessary

**Comment by with-heart** [comment]
Thanks @santialbo!

**Comment by with-heart** [comment]
Going to close this @DanLeCornu. If you run into issues, feel free to respond again.
