### ISSUE TITLE
[Accordion] Scroll position changes when toggling between panels

### ISSUE THREAD

**Issue by JeremieLeblanc** [chakra-ui/chakra-ui#1932]
# Bug report

## Describe the bug

When you have an accordion with the default allowMultiple set to false and you toggle between the multiple panels, the page scrolls up and eventually would push the entire accordion off the screen.

## To reproduce

If you go to the v1 docs: https://next.chakra-ui.com/docs/components/accordion#usage
and toggle the first and second panels back and forth, you will see the page scroll up on every iteration.

## Expected behavior

I would expect the scroll position to stay the same when toggling between multiple accordion panels.

## System information

- OS: Windows 10
- Browser (if applies): Chrome
- Version of @chakra-ui/core: 1.0.0-rc.3

**Comment by segunadebayo** [comment]
Pushed a fix for this.
