### ISSUE TITLE
checkbox not responding to iconColor prop

### ISSUE THREAD

**Issue by reginaldwhite** [chakra-ui/chakra-ui#1933]
# Bug report
iconColor prop doesn't work

## Describe the bug
Setting the iconColor prop causes a console error and has no effect

## To reproduce

1. Add a checkbox component
2. set the iconColor prop
3. check the console

Warning: React does not recognize the `iconColor` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `iconcolor` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

## Minimal reproduction
Add a checkbox, set the iconColor prop.  See console error.

https://codesandbox.io/s/fervent-khayyam-xew4q?file=/src/App.js

## Expected behavior

iconColor prop changes the Icon's color

## System information

- OS: macOS
- Browser: Chrome
- Version of @chakra-ui/core:  1.0.0-rc.3
- Version of Node.js: [e.g. 12.11.1]

**Comment by segunadebayo** [comment]
Thanks for reporting this @reginaldwhite.

I've just pushed a fix for this. We'll cut a new release shortly.

Cheers
