### ISSUE TITLE
[IconButton] Size attribute doesn't seem to accept an array

### ISSUE THREAD

**Issue by feross** [chakra-ui/chakra-ui#1937]
# Bug report

## Describe the bug

The `size` attribute on the `IconButton` doesn't seem to accept an array.

```js
<IconButton size={["md", "lg"]} icon={<FaMoonIcon />} colorScheme="red" />
```

## To reproduce

1. Go to https://codesandbox.io/s/cranky-rain-3udcn?file=/src/index.tsx
2. Observe that the button looks wrong, has no padding

## Minimal reproduction

Button should have padding. It seems like the issue is the use of the array syntax.

## Screenshots

Incorrect: 

<img width="22" alt="Screen Shot 2020-09-02 at 9 43 04 PM" src="https://user-images.githubusercontent.com/121766/92072225-9b3a7200-ed65-11ea-8e17-f04a04bc904e.png">

Correct: 

<img width="54" alt="Screen Shot 2020-09-02 at 9 43 16 PM" src="https://user-images.githubusercontent.com/121766/92072230-9e356280-ed65-11ea-9a04-3e001aeff8c9.png">

## System information

- OS: [e.g. macOS, Windows] macOS
- Browser (if applies): [e.g. Chrome, Safari] Chrome latest
- Version of @chakra-ui/core: [e.g. 1.0.0-rc.3] 1.0.0-rc.3
- Version of Node.js: [e.g. 12.11.1] v14.8.0

**Comment by with-heart** [comment]
Hi @feross! That's the correct behavior. `size` and `variant` are among the few props that don't currently support a responsive array.

In its place, you can use the `useBreakpointValue` hook to simulate this: `useBreakpointValue(["md", "lg"])`.

https://codesandbox.io/s/strange-payne-md947?file=/src/index.tsx

(The type error on `IconButton` relating to `translate`, `onAuxClick`, and `onAuxClickCapture` was an issue with `@types/react` that was resolved awhile back. For some reason CodeSandbox isn't handling these types correctly, or `react-scripts` is interfering. Not sure which.)

**Comment by feross** [comment]
Thanks @with-heart - `useBreakpointValue` is the approach I went with.

I'm curious what is the rationale for not supporting arrays in `size`. Is there just a whitelist of props which support arrays, and this just hasn't been added yet?

**Comment by with-heart** [comment]
@feross sorry for not getting back to you sooner! `size` and `variant` are specific implementations, and we just haven't built that functionality yet. I think we're planning on adding it at some point though.

**Comment by feross** [comment]
@with-heart thanks for letting me know. makes sense!
