### ISSUE TITLE
[TypeScript] Can't use <Link /> with Gatsby <Link />

### ISSUE THREAD

**Issue by screendriver** [chakra-ui/chakra-ui#194]
I want to use the `Gatsby` [Link](https://www.gatsbyjs.org/docs/linking-between-pages/) component together with Chakras [Link](https://chakra-ui.com/link) component. Unfortunately it seems not to work as expected because I'm getting compile errors:

```ts
import React from 'react';
import { Link as GatsbyLink } from 'gatsby';
import { Link } from '@chakra-ui/core';

export function Test() {
  return (
    <Link as={GatsbyLink} to="/me/">
      Me
    </Link>
  );
}
```

produces a

```
Type 'typeof GatsbyLink' is not assignable to type '"symbol" | "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | "br" | "button" | "canvas" | ... 157 more ... | undefined'.
  Type 'typeof GatsbyLink' is not assignable to type 'ComponentClass<any, any> & string'.
    Type 'typeof GatsbyLink' is not assignable to type 'string'.ts(2322)
index.d.ts(154, 3): The expected type comes from property 'as' which is declared here on type 'IntrinsicAttributes & ILink & IPseudoBoxProps & RefAttributes<HTMLElement> & HTMLAttributes<HTMLElement> & LayoutProps & ColorProps & SpaceProps<ReactText> & ... 16 more ... & { ...; }'
```

**Comment by segunadebayo** [comment]
Hi @screendriver, We're currently working to fix most Type issues by migrating to Typescript.

In the next release, this issue will be resolved.

**Comment by screendriver** [comment]
Awesome :+1: Great library by the way :wink:

**Comment by kripod** [comment]
@segunadebayo Awesome news! I would highly appreciate if you could push just another non-TS release to npm with all the recent fixes.

**Comment by segunadebayo** [comment]
@kripod, I'll do that shortly.

**Comment by alexluong** [comment]
Hey @screendriver, do you have a quick fix for this issue while waiting for the TS migration? Thanks.

**Comment by kripod** [comment]
@alexluong You may opt out of type checking for an entire file with // @ts-ignore, but I wouldn’t recommend that.

An other choice is to create an alias for Link like below:

```tsx
import { Link as ChakraLink } from ‘@chakra-ui/core’;

const Link = ChakraLink as any;
```

Personally, I'm using Chakra with the router of Gatsby and it made sense to create a custom `Link` component, using the first approach:

```tsx
import { Link as ChakraLink, LinkProps } from '@chakra-ui/core';
import { Link as GatsbyLink } from 'gatsby';
import React from 'react';

export default function Link({ href, isExternal, ...restProps }: LinkProps) {
  return (
    // TODO: Don't opt out from type checking once `ChakraLink` gets fixed
    // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
    // @ts-ignore
    <ChakraLink
      {...(isExternal ? { href } : { as: GatsbyLink, to: href })}
      {...restProps}
    />
  );
}
```

**Comment by screendriver** [comment]
> Hey @screendriver, do you have a quick fix for this issue while waiting for the TS migration? Thanks.

My quick fix is to not use the link component from Chakra :see_no_evil:

**Comment by HugoLiconV** [comment]
I'm getting a similar error using reach router
```javascript
import { Link } from "@reach/router"
// ...
    <Breadcrumb separator=">">
      <BreadcrumbItem>
        <BreadcrumbLink as={Link} to="/">
          Home
        </BreadcrumbLink>
      </BreadcrumbItem>
      <BreadcrumbItem>
        <BreadcrumbLink as={Link} to="/about">
          About
        </BreadcrumbLink>
      </BreadcrumbItem>
    </Breadcrumb>
```

Error: 
```
Type 'typeof Link' is not assignable to type '"symbol" | "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | "br" | "button" | "canvas" | ... 157 more ... | undefined'.
 Type 'typeof Link' is not assignable to type 'ComponentClass<any, any> & string'.
  Type 'typeof Link' is not assignable to type 'string'.  TS2322

```

**Comment by tony** [comment]
Thank you @kripod !

As of [typescript-eslint 3.0.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0), I believe the command will now be [`ban-ts-comment` instead of `ban-ts-ignore`](https://github.com/typescript-eslint/typescript-eslint/blob/v3.0.1/packages/eslint-plugin/docs/rules/ban-ts-comment.md)

```tsx
import { Link as ChakraLink, LinkProps } from '@chakra-ui/core';
import { Link as GatsbyLink } from 'gatsby';
import React from 'react';

export default function Link({ href, isExternal, ...restProps }: LinkProps) {
  return (
    // TODO: Don't opt out from type checking once `ChakraLink` gets fixed
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    <ChakraLink
      {...(isExternal ? { href } : { as: GatsbyLink, to: href })}
      {...restProps}
    />
  );
}
```

**Comment by RyanPinPB** [comment]
I copy/pasted the above code from @tony but I get this error:
8:5  error  Definition for rule '@typescript-eslint/ban-ts-comment' was not found  @typescript-eslint/ban-ts-comment

I should mention I do not know typescript (and I'm not using that file, just a normal .js file - ts is on my list to learn) 

Any recommendations to be able to use both Chakra and Gatsby's Link? Maybe i'll just use Gatsby's for now

**Comment by tony** [comment]
You may have to upgrade typescript, typescript eslint, or your eslint config itself. @RyanPinPB 

That error means the package for the rule isn't installed.

But if you have an old ts or eslint version, it could be that too. You are close enough you can lookup the package itself for issues more specific to your eslint / typescript setup

**Comment by RyanPinPB** [comment]
@tony Ya at some point I want to learn how to setup typescript for this project and add the config file, but for now, I have other priorities.

Any suggestions on how to write that code w/o typescript? In a regular .js file?

Or do you highly suggest I spend time learning typescript right now to use that code above, and add it to a .tsx file I assume?

**Comment by tony** [comment]
@RyanPinPB Do you have babel? Can you at least write in es2015? Can you do `import` statements?

Just like the earlier question with the error, not easy to remote diagnose. Depends on your environment

```js
import { Link as ChakraLink, LinkProps } from '@chakra-ui/core';
import { Link as GatsbyLink } from 'gatsby';
import React from 'react';

export default function Link({ href, isExternal, ...restProps }) {
  return (
    <ChakraLink
      {...(isExternal ? { href } : { as: GatsbyLink, to: href })}
      {...restProps}
    />
  );
}
```

That may work assuming you have babel.  I haven't done normal javascript in some time.

You can try playing with this: https://www.typescriptlang.org/play?target=2&module=0#code/KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnADLF4DWAFAN5wAWUKANHMQM4CiIMYFDypMnAHSS23GAAUoEMNzgBfAJRwGAKDhw2MdMLh0duuAHpzcACoB5ACK2AXHHtkA5PEVf0OBQFs4GABPMGA4AmZgAhpqAHM4MgJwgAMAYWZUGihUKloUuDjgGGVkYhBgBFNdSzhgbkxqGABaBB5UACNMYGa8UBbGvrgAARCw7gIoYjAW+sGYcw7UPGaS5oIIf39gPBhqiytR7mbiOLxoYH2AHgysnLyafd0GSXE6Hn5BYVE4AH5NFhsZCqOAuJiobguADiqBKHWCD04MAgLlYKFUahUT00r2kcgUSixZgsAD5TGoANxaFRAA and going into the config options to see what the JS output looks like.

**Comment by RyanPinPB** [comment]
@tony Thank you for spending time on this. I can use the above code to create a functioning site. I do however get an error that I need to look into (not a breaking error - that I know of). I may just need to do something differently w/in the Link components now. . . it might not be an error w/ your above code:

Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ForwardRef(MotionComponent)`.
    in Link (created by ForwardRef(MotionComponent))
    in ForwardRef(MotionComponent) (at pages/index.js:285)
    in div (created by Context.Consumer)
    in Box (created by Flex)
    in Flex (at pages/index.js:276)
    in section (created by Context.Consumer)
etc. . . Goes on to list all of the Chakra components


So LinkProps seems to be the only typescript component (that I didn't know how to replace - this was my original issue)?

From the above it looks like I can just remove it and the code will be fine? Do you think removing it is causing the above error?

**Comment by tony** [comment]
Eek. I don't remember what happened since I made the [post in May](https://github.com/chakra-ui/chakra-ui/issues/194#issuecomment-633659976).  But since then, I've tweaked the link to be a `React.forwardRef` (fancy that)

Here's what the current link I have looks like (TypeScript + JSX):

```tsx
export const SiteLink = React.forwardRef<HTMLAnchorElement, ISiteLinkProps>(
  ({ ...props }, ref) => {
    props.color = props.color ?? "gray.500";
    props._hover = props._hover ?? {};
    // @ts-expect-error
    props._hover.color = props._hover.color ?? "gray.800"; // eslint-disable-line

    const internal = /^\.?\/(?!\/)/.test(props.href || "");
    const asProps: Pick<ChakraLinkProps, "ref"> & {
      as: typeof GatsbyLink | typeof OutboundLink;
      to?: string;
    } = { as: internal ? GatsbyLink : OutboundLink };
    if (internal) {
      asProps.to = props.href;
    }
    asProps.ref = ref;
    return <ChakraLink {...asProps} {...props} />;
  }
);
```

Haven't tested it, but with modern JS / JSX, something like:

```js
export const SiteLink = React.forwardRef(
  ({ ...props }, ref) => {
    props.color = props.color ?? "gray.500";
    props._hover = props._hover ?? {};
    props._hover.color = props._hover.color ?? "gray.800";

    const internal = /^\.?\/(?!\/)/.test(props.href || "");
    const asProps = { as: internal ? GatsbyLink : OutboundLink };
    if (internal) {
      asProps.to = props.href;
    }
    asProps.ref = ref;
    return <ChakraLink {...asProps} {...props} />;
  }
);
```

**Comment by RyanPinPB** [comment]
Thanks so much @tony for spending your precious time thinking about this.

I just assigned OutboundLink to be a ChakraLink.

No more errors!
