### ISSUE TITLE
FormHelperText should not render when inside a FormControl that has isInvalid set

### ISSUE THREAD

**Issue by ChasinHues** [chakra-ui/chakra-ui#1946]
# Bug report

## Describe the bug

The docs suggest that `FormHelperText` should be hidden when inside an invalid `FormControl` ([reference](https://github.com/chakra-ui/chakra-ui/tree/develop/packages/form-control#with-input)), but this doesn't actually happen; `FormHelperText` remains visible.

## To reproduce

1. Render a `FormControl` with a `FormHelperText` and `FormErrorMessage` inside. Set `isInvalid` on the `FormControl`.

```
<FormControl isInvalid>
  <FormLabel>FormLabel</FormLabel>
  <Input />
  <FormHelperText>FormHelperText</FormHelperText>
  <FormErrorMessage>FormErrorMessage</FormErrorMessage>
</FormControl>
```

2. Observe: the `FormErrorMessage` displays (as it should), but the `FormHelperText` remains visible, which it should not.

## Minimal reproduction

Sandbox: https://codesandbox.io/s/lingering-cherry-ub5fd?file=/src/index.tsx

## Expected behavior

When a `FormControl` is set to `isInvalid`, the `FormHelperText` should not be rendered.

## Screenshots

![image](https://user-images.githubusercontent.com/13565648/92182541-47c44300-ee8f-11ea-9cc6-861369219ea3.png)

**Comment by KarenEfereyan** [comment]
@ChasinHues does that mean the  'Formhelpertext' just above the formhelpererror should not be showing

**Comment by KarenEfereyan** [comment]
I would love to tackle this while counting on your help of course

**Comment by with-heart** [comment]
The docs there are incorrect on this one. `FormHelperText` should always be visible.

**Comment by with-heart** [comment]
@segunadebayo Can you verify?

**Comment by segunadebayo** [comment]
@with-heart, from my initial design, `FormHelperText` should not be visible when `FormErrorMessage` is shown. I think it's a sensible default assumption.

I'll check the docs and keep them in sync.

I merged @ChasinHues's PR already.

@KarenEfereyan Thank you so much for wanting to help with this. @ChasinHues already created a PR hence the reason why I didn't chime in on time to help you.

**Comment by segunadebayo** [comment]
Done!

**Comment by KarenEfereyan** [comment]
Okay
