### ISSUE TITLE
Typo in the docs for Chakra UI Form Control

### ISSUE THREAD

**Issue by KarenEfereyan** [chakra-ui/chakra-ui#1951]
# Bug report

## Describe the bug
In the documentation for the chakra UI form fields, there is a little typo. Form is spelt as from

## To reproduce

1. Go to ''

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies): [e.g. Chrome, Safari]
- Version of @chakra-ui/core: [e.g. 1.0.0-rc.3]
- Version of Node.js: [e.g. 12.11.1]

**Comment by KarenEfereyan** [comment]
@segunadebayo can this be assigned to me? Its a really small error

**Comment by ljosberinn** [comment]
@KarenEfereyan feel free to go ahead and file a PR :)

**Comment by KarenEfereyan** [comment]
@ljosberinn I can't seem to find the md file.

**Comment by KarenEfereyan** [comment]
![chakra](https://user-images.githubusercontent.com/56835876/92293806-4c840800-ef1e-11ea-8105-9e23020a5f95.PNG)
Here is the little change I want to make. But in my editor, I cannot seem to find the readme file I need

**Comment by ljosberinn** [comment]
the github URL maps 1:1 to the file tree after `/develop/`, tus the file can be found in [`/packages/form-control/README.md`](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/form-control/README.md#chakra-uiform-control)

**Comment by KarenEfereyan** [comment]
@ljosberinn thank you.

**Comment by segunadebayo** [comment]
Thanks for catching this issue @KarenEfereyan. I managed to fix this before checking this issue.

In the future, I think you can click the edit button on the top-right for most READMEs, make the changes, commit and open a PR directly fro Github without having to clone the repo.

<img width="1308" alt="Screen Shot 2020-09-06 at 1 47 09 PM" src="https://user-images.githubusercontent.com/6916170/92323166-8866bc80-f047-11ea-9e93-5a76779e99c7.png">

Hope this helps.

PS: I'm happy to guide you through any steps you need to contribute. We can even open a discussion for First-time contributors so our chat can help them as well.

**Comment by KarenEfereyan** [comment]
@segunadebayo that's actually true. I totally forgot. Ill be looking out for new issues. Im really loving open soirce

**Comment by KarenEfereyan** [comment]
Yes doing something for first time contributors? I love me the sound of that
