### ISSUE TITLE
[Theme] Provide a function to create the breakpoints property via DI

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#1954]
# Bug report

Right now, to use custom breakpoints, you can just pass `extendTheme({ breakpoints: myBreakpointArray })` [matching the spec](https://next.chakra-ui.com/docs/features/responsive-styles#what-it-does).

However, if you manually pass, [you'd be missing the properties defined on the default theme array](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/theme/src/foundations/breakpoints.ts#L10).

We could provide a function or merge functionality for that into `extendTheme`, something like:

```ts
interface BreakpointConfig {
  [key: string]: string;
  sm: string;
  md: string;
  lg: string;
  xl: string;
}

const createBreakpoints = (config: BreakpointConfig) => {
 const breakpoints = Object.values(config);

 Object.entries(config).forEach(([key, value]) => {
  Object.defineProperty(breakpoints, key, { value });
 });

  return breakpoints;
}
```

**Comment by skasyn** [comment]
Would it used like this ? :
```ts
extendTheme({ breakpoints: createBreakpoints(["30em", "56.25em", "91.50em", "120em"]) })
```

Would'nt it be better if the missing properties were added implicitly ?

**Comment by ljosberinn** [comment]
possibly, that would lock in to forcing those object keys though; I'm not sure what's planned in regards of allowing more/less/entirely custom breakpoint names

**Comment by ljosberinn** [comment]
```ts
interface BaseBreakpointConfig extends Record<string, string>{
  sm: string;
  md: string;
  lg: string;
  xl: string;
}

function createBreakpoints<T extends BaseBreakpointConfig>(config: T):Breakpoints<T> {
  return Object.assign(Object.values(config), config);
}

type Breakpoints<T = BaseBreakpointConfig> = string[] & T;

const breakpoints = createBreakpoints({
  sm: "30em",
  md: "56em",
  lg: "91em",
  xl: "120",
});

```

this would probably work. right now we have breakpoints typed as `any` anyways

**Comment by ljosberinn** [comment]
A more complex, yet definitely more precise implementation would be [this](https://gist.github.com/0kku/a31bf98465fb9d433c7bb547634fa70c), credits to @0kku, but it requires TS 4.1, so we have to wait for next month for that.

It would support those goodies:

![image](https://user-images.githubusercontent.com/29307652/92288030-d2e31e80-ef0b-11ea-9626-27f1e85fc297.png)
![image](https://user-images.githubusercontent.com/29307652/92288037-d676a580-ef0b-11ea-9999-71b29c58371a.png)

**Comment by segunadebayo** [comment]
@ljosberinn We might want to enforce the breakpoint object to be an object. We can be a bit flexible with the breakpoint keys for now.
