### ISSUE TITLE
[Drawer] Drawer height changes when placement is "bottom/top"

### ISSUE THREAD

**Issue by imdongchen** [chakra-ui/chakra-ui#1955]
# Bug report

## Describe the bug

With `<Drawer placement="bottom" size="md" />`, the drawer height keeps growing as you add more content to `DrawerBody`, even though you have specified a `md` size.

## To reproduce

1. Go to https://next.chakra-ui.com/docs/overlay/drawer#drawer-placement
2. Choose placement `bottom`
3. Add lots of content within `DrawerBody` 
4. See the oversized panel

## Expected behavior

The Drawer should honor `size` and have a `max-height` when placement is `bottom` or `top`, just like it has `max-width` when placement is `left ` or `right`

## Screenshots

![image](https://user-images.githubusercontent.com/578035/92239260-8a762300-ee6f-11ea-9d6c-beb7312c7d03.png)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies): [e.g. Chrome, Safari]
- Version of @chakra-ui/core: [e.g. 1.0.0-rc.3]
- Version of Node.js: [e.g. 12.11.1]

**Comment by Samic8** [comment]
This sounds reasonable. I think the default should be the current behavior without a size, and if size is specified it should respect it.

**Comment by ctpaulson** [comment]
@binajmen @imdongchen Here's a workaround I figured out.

You can add a `maxH` attribute to the `<DrawerContent>` component, like so:

```
<Drawer
        isOpen={isOpen}
        placement="bottom"
        onClose={onClose}
        finalFocusRef={btnRef}
      >
        <DrawerOverlay>
          <DrawerContent maxH="75vh">
            <DrawerCloseButton />
            <DrawerHeader>Create your account</DrawerHeader>

            <DrawerBody>
              <Input placeholder="Type here..." />
            </DrawerBody>

            <DrawerFooter>
              <Button variant="outline" mr={3} onClick={onClose}>
                Cancel
              </Button>
              <Button colorScheme="blue">Save</Button>
            </DrawerFooter>
          </DrawerContent>
        </DrawerOverlay>
      </Drawer>
```

You can use either `vh` units if you want the drawer to take up a certain portion of the viewport height, or hardcode a `px` value.

**Comment by binajmen** [comment]
Hi @ctpaulson,

I solved this using a hook largely inspired from https://usehooks.com/useWindowSize/:
```js
import * as React from 'react'

type WindowSize = {
  width: number
  height: number
}

export default function useWindowSize() {
  // https://joshwcomeau.com/react/the-perils-of-rehydration/
  const [windowSize, setWindowSize] = React.useState<WindowSize>({
    width: 0,
    height: 0,
  })

  React.useEffect(() => {
    function handleResize() {
      setWindowSize({
        width: window.innerWidth,
        height: window.innerHeight,
      })
    }

    window.addEventListener("resize", handleResize)
    handleResize()

    return () => window.removeEventListener("resize", handleResize)
  }, [])

  return windowSize
}
```
```js
const { height } = useWindowSite()
...
      <Drawer placement="bottom" isOpen={isOpen} onClose={onClose}>
        <DrawerOverlay>
          <DrawerContent maxH={height}>
```
It works pretty well 😉

**Comment by averyfreeman** [comment]
This issue is pretty old, but it's not closed, so I thought I'd weigh in - 

Tried = creating, `<Drawer />` with about ~30% screen coverage, placement = left

Expected result = `"xs"`, `"sm"`, etc. sizes to be smaller width than screen

Actual result = Drawer was always full width of screen

Workaround = used the `!important` tag inside manual width, ala `width="20rem !important"`

Thanks

**Comment by Developer-Wu** [comment]
I think I've found a good solution. `zIndex` was used because the close button could not be clicked for some reason after the fix. Content `height =100%` stops footer from being hidden and `pos="sticky"` on header stops header from being hidden. 

```javascript
<Drawer {...drawerProps} isOpen={isOpen} onClose={onClose}>
        <DrawerOverlay />
        <DrawerContent height="100% !important">
          <DrawerCloseButton zIndex={999} />
          <DrawerHeader pos="sticky">{renderHeader()}</DrawerHeader>
          <DrawerBody>{children({ close: onClose })}</DrawerBody>
          <DrawerFooter>{renderFooter({ close: onClose })}</DrawerFooter>
        </DrawerContent>
      </Drawer>
```
