### ISSUE TITLE
[Menu] Using MenuDivider inside MenuOptionGroup causes warnings

### ISSUE THREAD

**Issue by santialbo** [chakra-ui/chakra-ui#1959]
# Bug report
Using a `MenuDivider` inside `MenuOptionGroup` causes the following warning
```
Warning: React does not recognize the `isChecked` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ischecked` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in hr (created by Context.Consumer)
    in Styled(hr) (created by MenuDivider)
    in MenuDivider (at PetitionListFilter.tsx:85)
    in div (created by Context.Consumer)
    in Styled(div) (created by MenuGroup)
    in MenuGroup (created by MenuOptionGroup)
```
It looks like `useMenuOptionGroup` clones all children with that property without checking if they are `MenuItemOption`

https://github.com/chakra-ui/chakra-ui/blob/919cf2bb9f0adaa8be50c81ae12d46b8b6469282/packages/menu/src/use-menu.ts#L545-L561

## Minimal reproduction
https://codesandbox.io/s/goofy-fermi-qg2tp?file=/src/App.js

**Comment by segunadebayo** [comment]
Thanks for catching this. I've just pushed a fix.

**Comment by minardimedia** [comment]
There are more elements with this issue <RadioGroup/> cause the same issue.
`Warning: React does not recognize the `isChecked` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ischecked` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

 Warning: React does not recognize the `isFocusable` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isfocusable` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

Warning: React does not recognize the `isDisabled` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isdisabled` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
`

**Comment by nfabacus** [comment]
Hello, this bug is labeled as "Closed" but I am still observing this issue.

**Comment by hhimanshu** [comment]
I see them as well

**Comment by igorschechtel** [comment]
> There are more elements with this issue **RadioGroup** cause the same issue.
> 
> ```
> Warning: React does not recognize the isChecked prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase ischecked  instead. If you accidentally passed it from a parent component, remove it from the DOM element.
> 
> Warning: React does not recognize the isFocusable prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase isfocusable instead. If you accidentally passed it from a parent component, remove it from the DOM element.
> 
> Warning: React does not recognize the isDisabled prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase isdisabled instead. If you accidentally passed it from a parent component, remove it from the DOM element.
> ```

I'm facing the same issue with the **Radio** component. Not passing any of those as props to it.
