### ISSUE TITLE
[CheckboxGroup] Numeric values don't work in uncontrolled mode

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#196]
When a `CheckboxGroup` is not [controlled](https://github.com/chakra-ui/chakra-ui/blob/ad066ae851afc671d8f0de93e82767469b1b7fdd/packages/chakra-ui/src/CheckboxGroup/index.js#L27), giving numeric `value` props to children breaks the [`isChecked` mechanism](https://github.com/chakra-ui/chakra-ui/blob/ad066ae851afc671d8f0de93e82767469b1b7fdd/packages/chakra-ui/src/CheckboxGroup/index.js#L63), as `_values`, matching the value of the `values` state variable, can only be an array of **strings**, set through [`_onChange`](https://github.com/chakra-ui/chakra-ui/blob/ad066ae851afc671d8f0de93e82767469b1b7fdd/packages/chakra-ui/src/CheckboxGroup/index.js#L30-L41).

I suggest deprecating support for numeric form `Checkbox` and `Radio` values, as they do more [harm](https://github.com/chakra-ui/chakra-ui/issues/50) than the convenience they provide.

**Comment by segunadebayo** [comment]
I see what you mean @kripod. Can you provide a quick codesandbox link so I can verify this?

I believe this can be resolved so the values can take both string and numeric values.

**Comment by kripod** [comment]
@segunadebayo Thanks for the quick review! Unfortunately, I don't have the time to construct a CodeSandbox right now, but here is an example snippet:

```tsx
import { Checkbox, CheckboxGroup } from '@chakra-ui/core';
import React, { useState } from 'react';

export default function Component() {
  // Enable controlled mode by uncommenting the line below:
  // const [response, setResponse] = useState<number[]>([]);

  return (
    <CheckboxGroup
      // Enable controlled mode by uncommenting the lines below:
      // value={response}
      // onChange={(values: any) => {
      //   const optionIDs: number[] = values.map(Number);
      //   setResponse(optionIDs);
      // }}
    >
      {[1, 2, 3].map(option => (
        <Checkbox
          key={option}
          value={option} // `${choice.id}` would work fine
        >
          {option}
        </Checkbox>
      ))}
    </CheckboxGroup>
  );
}
```

**Comment by kripod** [comment]
Actually, I just came across #102 and created a CodeSandbox based on the template: https://codesandbox.io/embed/chakra-ui-issue-196-vvq22

**Comment by segunadebayo** [comment]
Okay, I'll look into it. We're currently looking to migrate Chakra to TS to resolve most of the type issues. I'll ensure we resolve this when we work on the `CheckboxGroup`.

**Comment by segunadebayo** [comment]
This has been resolved in the `dev-ts` branch and will be released soon. I'll close it out for now
