### ISSUE TITLE
[ESLint] Create config for auto-sorting style props

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#197]
Similar to how [stylelint-config-rational-order](https://github.com/constverum/stylelint-config-rational-order) works, an ESLint config (e.g. `eslint-config-chakra-ui`) could be created to handle ordering of style props, placing them after non-stylistic props in an [idiomatic order](https://github.com/necolas/idiomatic-css).

The rule [jsx-sort-props in](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-sort-props.md) eslint-plugin-react already [provides](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-sort-props.js) a reference implementation to start with.

**Comment by segunadebayo** [comment]
Thanks for this suggestion @kripod. We don't plan to do this anytime soon.

I'm going to close it for now and add a tag to help me find it down the line.

**Comment by borisghidaglia** [comment]
Hello @segunadebayo,

Is this something you would consider now?

Thanks in avance, and thanks for you work 🙌
