### ISSUE TITLE
[ Typescript ]Transition components missing types and reverse default

### ISSUE THREAD

**Issue by TheThirdRace** [chakra-ui/chakra-ui#1974]
# Bug report

## Describe the bug

Actually 2 bugs on the same property...

**Bug #1**
Missing type for property `appear` in Typescript when using <Slide> transition (@chakra-ui/transition)
http://reactcommunity.org/react-transition-group/transition#Transition-prop-appear

Probably the same bug for the other transition types: Fade, ScaleFade and SlideFade.

**Bug #2**
Property `appear` on <Slide> seem to have the reverse default than on `react-transition-group`.
http://reactcommunity.org/react-transition-group/transition#Transition-prop-appear

By default, **meaning without passing `appear`**, the animation shouldn't play on first mount according to `react-transition-group`. But with <Slide> it plays when not passing `appear`.

If `appear` is set to `false` on <Slide>, it won't play the animation on first mount.

## To reproduce

Load codesandbox provided below (uses @chakra-ui/core package to version 1.0.0-**rc.3**)

In App.tsx, at line 18 you'll see the <Slide> component.

**Bug #1**
The `appear` property is having a Typescript error: 
> Property 'appear' does not exist on type 'IntrinsicAttributes & Pick<TransitionProps, "children" | "in" | "onEnter" | "onEntering" | "onEntered" | "onExit" | "onExiting" | "onExited" | "unmountOnExit" | "transition"> & { ...; } & { ...; }'.ts(2322)

**Bug #2**
Refresh the page without the property `appear` and the Slide animation will play

Pass the `appear` property with `false` and the Slide animation will NOT play (which is the expected behavior)

## Minimal reproduction

https://codesandbox.io/s/lucid-architecture-0ne6g?file=/src/App.tsx

## Expected behavior

**Bug #1**
Expected boolean type for property

**Bug #2**
Animation shouldn't play on first mount if `appear` is not passed

## System information

- OS: Windows 10 (2004)
- Browser (if applies): Chrome
- Version of @chakra-ui/core: 1.0.0-rc.3
- Version of Node.js: 12.18.1

## Additional context

While I can execute the project when passing `false` to `appear` property, I can't compile for production because of the Typescript error...

**Comment by KarenEfereyan** [comment]
I have no idea of Typescript. I'm sad. I really want to contribute to Chakra

**Comment by TheThirdRace** [comment]
Just in case I need to bump it since someone made an unrelated comment.

Sorry if it's not the procedure

**Comment by segunadebayo** [comment]
We recently move all transitions to use `framer-motion`, making this issue stale.

We'll publish a new release shortly. Please confirm it works smoothly for you once you do, otherwise, open a new issue.

Thank you

**Comment by TheThirdRace** [comment]
@segunadebayo 
Thanks for the follow up, I'll check it out.

There have been a couple problems with transitions 1.0.0-rc1 to 1.0.0-rc5. Components like Drawer leave a ton of warning messages in the console because it tries to update the component while it's been unmounted.

Will that disappear in the RC with framer-motion?
