### ISSUE TITLE
Overriding responsive `textStyle` value with non-responsive prop value does not work as expected

### ISSUE THREAD

**Issue by spykr** [chakra-ui/chakra-ui#1975]
# Bug report

## Describe the bug

I love the [new textStyles feature](https://next.chakra-ui.com/docs/features/text-and-layer-styles), however I had an issue applying a text style and then overriding the font-size with a `fontSize` prop value. With further testing I realised it's because overriding a responsive value with a non-responsive value does not currently work how I would expect.

## To reproduce

1. Create a `textStyle` with a responsive `fontSize` value (e.g. `{ base: "32px", sm: "32px", md: "32px", lg: "32px", xl: "32px" }`) and apply the text style to a `Text` or `Heading` component.

2. Add a non-responsive `fontSize` prop value to the component (e.g. `fontSize="16px"`) and see that the text size is only affected at the "base" breakpoint.

3. Change it to a responsive value (e.g. `{ base: "16px", sm: "16px", md: "16px", lg: "16px", xl: "16px" }`) and see that the font-size is now correctly overriden at all breakpoints.

## Minimal reproduction

https://codesandbox.io/s/text-style-font-override-ccl4s

## Expected behavior

I would expect that a non-responsive value would automatically apply to all breakpoints.

## System information

Version of @chakra-ui/core: 1.0.0-rc.3

**Comment by spykr** [comment]
Another issue that seems to be a related to this (if not let me know and I will create a separate issue):

1. Create a `textStyle` with a non-responsive font-size value (e.g. `fontSize: "64px"`)
2. Apply the text style to a `Heading` component
3. Observe that at the large breakpoint (768px) the size will start being overridden by the font sizes from the default value of the Heading component `size` prop (i.e. "xl")

I was able to fix this issue by passing `size=""` to the Heading component, but this is not intuitive.

CodeSandbox: https://codesandbox.io/s/heading-size-default-p715e

**Comment by segunadebayo** [comment]
Hi @spykr,

Thanks for catching this. I've fixed this issue in this PR #2024 

We'll create a new release shortly.

Cheers.

**Comment by dlindenkreuz** [comment]
@segunadebayo I think there has been a regression. Can you reopen this issue?

Here is a fork of the sandbox above with the latest versions of Chakra and Emotion: https://codesandbox.io/s/heading-size-default-forked-246fl?file=/src/App.tsx

Make sure to enlarge the preview to see the default `4xl` font size come into effect for larger widths.

**Comment by dlindenkreuz** [comment]
**Update**: It seems that `textStyle` now ignores the `fontFamily` setting as well in @chakra-ui/react@1.4.2 https://codesandbox.io/s/heading-size-default-forked-zgpbl?file=/src/App.tsx

(Compare this to the sandbox above that uses @chakra-ui/react@1.3.4: https://codesandbox.io/s/heading-size-default-forked-246fl?file=/src/App.tsx)
