### ISSUE TITLE
Unable to use system "prefers-color-scheme" for colorMode Chakra latest

### ISSUE THREAD

**Issue by bamzi** [chakra-ui/chakra-ui#1976]
# Bug report

Unable to use default system `prefers-color-scheme` when setting up colorMode with latest version of Chakra

## Describe the bug

Related to Chakra@next: "1.0.0-rc.3"

For NextJS to enable ColorModeScript, the code below which can also be found in the docs is wrong in 2 ways:
`<ColorModeScript defaultMode="light" />`

First: the prop should be "defaultColorMode" as defaultMode doesn't exists
Second: to use system's `prefers-color-scheme` it's stated to use "system" as `defaultColorMode` value but defaultColorMode allows only 2 values defined in `colorMode` which are locked to `"light" | "dark"` 

## To reproduce

refer to: https://next.chakra-ui.com/docs/features/color-mode

**Comment by ljosberinn** [comment]
known issue, see #1878, will be fixed in the next release
