### ISSUE TITLE
Tree shaking with Next.js

### ISSUE THREAD

**Issue by steida** [chakra-ui/chakra-ui#198]
It seems the whole lib is imported when the only Button is used.

But https://bundlephobia.com/result?p=chakra-ui@0.3.9 says the lib is tree shakeable.

Is there any working example? Thank you.

**Comment by segunadebayo** [comment]
Hi @steida, can you try this:
`import  Button from "@chakra-ui/core/dist/Button"`

**Comment by jaredpalmer** [comment]
@segunadebayo something to consider is creating a babel plugin for Chakra like React Native Web's which rewrites all named imports into "pre-shaken" imports like you just described.

**Comment by segunadebayo** [comment]
Thanks for that idea @jaredpalmer. I'll look into it.

**Comment by koolamusic** [comment]
@jaredpalmer thanks for the suggestion, could you please share any ideas, as to how one can implement that. writing a babel plugin to pre-shaken imports

**Comment by jaredpalmer** [comment]
Source code is here. https://github.com/necolas/react-native-web/tree/master/packages/babel-plugin-react-native-web/src

**Comment by leerob** [comment]
You also might be able to use this: https://github.com/ant-design/babel-plugin-import

**Comment by kahlil** [comment]
Thanks @leerob that seems to work really well!

**Comment by danieljodeci** [comment]
@kahlil Do you mind sharing an example of how you were able to get babel-plugin-import to work with chakra-ui?

**Comment by kahlil** [comment]
Sure. 

1. install the import plugin
2. add `.babelrc`

```js
{
  "presets": ["next/babel"],
  "plugins": [
    ["emotion"],
    [
      "import",
      {
        "libraryName": "@chakra-ui/core",
        "libraryDirectory": "dist",
        "camel2DashComponentName": false
      }
    ]
  ]
}
```

**Comment by danieljodeci** [comment]
Works wonders @kahlil 

Thanks

**Comment by kahlil** [comment]
Happy to. Maybe we should add this to the docs @segunadebayo?

**Comment by segunadebayo** [comment]
@kahlil. This looks good!

We should definitely add it to the docs. If you don't mind adding it and sending a PR, that would be great. Otherwise, I'll add it as soon as I can.

Thank you

**Comment by stevewillard** [comment]
I think this configuration works for most components, but not all of them. For example `Popover` doesn't seem to work:
```
Attempted import error: '@chakra-ui/core/dist/Popover' does not contain a default export (imported as '_Popover').
```

**Comment by kahlil** [comment]
Yeah Popover works differently. It has a bunch of named exports and no default export. Hm, not sure how to use the plugin to keep the named imports in those cases...

**Comment by kahlil** [comment]
@stevewillard for now try to do the named imports from the tree-shaken file directly like: 

```js
import { Popover } from "@chakra-is/core/dist/Popover"
```

I don’t see a way how the plugin could be used to distinguish the two cases. Maybe something that needs to be added somehow.

**Comment by kahlil** [comment]
> @kahlil. This looks good!
> 
> We should definitely add it to the docs. If you don't mind adding it and sending a PR, that would be great. 

I‘ll send a PR but first want to investigate a little further if the `Popover` Case can be handled a little better.

**Comment by stevewillard** [comment]
I think there are several other components that have the same problem. For example `List` and `Tab`:

```
Attempted import error: 'List' is not exported from '@chakra-ui/core/dist/List'.
```

You have to do:
```
import List, { ListItem, ListIcon } from '@chakra-ui/core/dist/List';
```

**Comment by leerob** [comment]
To use properly, that plugin expects all components to be exported at the same level. It would take a bit of refactoring and some breaking changes to get it working perfectly with all components. 

Example: https://github.com/ant-design/ant-design/tree/master/components

**Comment by dimitrisnl** [comment]
This is still relevant.

**Comment by fr3fou** [comment]
Still relevant?

**Comment by fr3fou** [comment]
yep, it's still relevant, it doesn't work with `useColorMode` 

`Module not found: Can't resolve '@chakra-ui/core/dist/useColorMode'`

**Comment by kahlil** [comment]
Yes you still have to import from the tree-shaken module for some modules and hooks. 
But that can't be the long term solution. I bet there is some sort of custom WebPack config that can be added to Next.js in order to deal with it out of the box.
I don't have time to research that at the moment, though.

**Comment by segunadebayo** [comment]
Thank you @kahlil and @lee-reinhardt for helping out with this! 💖

**Comment by solarsoft0** [comment]
❤️

**Comment by feross** [comment]
I'm confused why bundlers aren't able to tree-shake when using `import { Button } from '@chakra-ui/core'`... Wasn't this the whole reason for ESM's existence? My hunch is that there may be some underlying issue with the way that Chakra is exporting stuff that is preventing the bundler from tree-shaking. But, I am far from an expert on this topic.

**Comment by talentlessguy** [comment]
Still happening:

```
TypeError: can't access property "variant", _useContext2 is undefined
```

when doing this:

```js
import Tabs, { Tab, TabList, TabPanel, TabPanels } from '@chakra-ui/core/dist/Tabs/index'
```

**Comment by segunadebayo** [comment]
@feross. This is an issue Babel recently solved. [Check here](https://www.infoq.com/news/2020/05/babel-7-10-react-treeshaking/)

The thing is, whenever we use `React.forwardRef`, it was previously impossible to tree-shake those components if you use babel.

I'm glad this has been solved now, so it shouldn't be a problem in the future.

**Comment by arnaudjnn** [comment]
Do you have an example using Next.js with @chakra-ui/core and theme-ui?

**Comment by dimitrisnl** [comment]
@arnaudjnn this thread pings, a lot of people and your question is not about the bundle size (which seems to be resolved?).

The examples can be found here https://github.com/chakra-ui/chakra-ui/tree/master/examples/ - and there isn't any about `theme-ui`

**Comment by segunadebayo** [comment]
Hey guys,

This is no longer an issue as we now use the latest version of babel which comes with tree-shaking support.

Cheers.

**Comment by kahlil** [comment]
Woohoo!
GitHub <notifications@github.com> wrote:
“Hey guys,

This is no longer an issue as we now use the latest version of babel which comes with tree-shaking support.

Cheers.”

**Comment by s-kris** [comment]
> Sure.
> 
>     1. install the import plugin
> 
>     2. add `.babelrc`
> 
> 
> ```js
> {
>   "presets": ["next/babel"],
>   "plugins": [
>     ["emotion"],
>     [
>       "import",
>       {
>         "libraryName": "@chakra-ui/core",
>         "libraryDirectory": "dist",
>         "camel2DashComponentName": false
>       }
>     ]
>   ]
> }
> ```

I'm getting this error with latest version of chakra and babel-import-plugin:
`Error: Can't resolve '@chakra-ui/core/dist/AlertDescription' from in '/Users/<path-to-next-app>/pages/auth'`

Can anyone help me resolve this?

**Comment by hutber** [comment]
Certainly isn't working for me @segunadebayo Interesting, I'm going to have to look into it!

**Comment by patrickclover** [comment]
bump

**Comment by darrylmorley** [comment]
Tree shaking with next v12.1.0 isn't working with @chakra-ui/react v1.8.8. Is there any update on this?

**Comment by AlexKvazos** [comment]
> 

Is there a way to do tree shaking for people using Next.js with SWC instead of Babel?

**Comment by woodjs** [comment]
For NextJS using SWC one can use:
```
// next.config.js
module.exports = {
      modularizeImports: {
      '@chakra-ui/react': {
        transform: '@chakra-ui/core/dist/{{member}}',
      },
    },
}
```
But the problem is that not all components are placed in this directory. So this won't work, but I'd like to share what I found in the NextJS docs, maybe someone can come up with a solution.

**Comment by jepek** [comment]
I've got this problem too, I am using Chakra with Gatsby.js. Same for me as above - not imports do work replaced to `'@chakra-ui/core/dist/{{member}}'`

**Comment by jinsley8** [comment]
> I've got this problem too, I am using Chakra with Gatsby.js. Same for me as above - not imports do work replaced to `'@chakra-ui/core/dist/{{member}}'`


That wouldn't work because `/core/dist/` is not the path in `node_modules` for `@chakra-ui`. That's just an example from the Next.js docs.

I still haven't figured it out but it should be more along the lines of this below. Although this doesn't work either and there are cases like ChakraProvider that would likely need a regex:

```
// next.config.js
module.exports = {
      modularizeImports: {
         '@chakra-ui/react': {
            transform: '@chakra-ui/{{ kebabCase member }}',
        },
    },
}
```

https://nextjs.org/docs/advanced-features/compiler#modularize-imports

**Comment by woodjs** [comment]
@segunadebayo chakra-ui.com uses NextJS, is tree shaking implemented there?
If so, could you please tell me which version needs to be installed and what add-ons are required for babel?
I really want to understand this topic. Thanks.

**Comment by ctrichereau** [comment]
Hey guys ! 

We have the same issue with our project.
We're using this versions :
- NextJs : 12.3.1,
- Chakra : 2.4.2

I created a [sandBox on gitHub](https://github.com/ctrichereau/sandbox-chakra-tree-shaking-issue.git) for reproducing the issue.
We tried differents way for resolving the missing tree shaking on build, but we run out of solutions...

Feel free to use it.

**Comment by woohyun-park** [comment]
I had same issue so I tried to solve the problem manually. I basically created an webpack loader that replaces all the chakra imports statements to specific imports like below

From
```
import {
  Box,
  Button,
} from '@chakra-ui/react';
```

To
```
import { Box } from '@chakra-ui/layout';
import { Button } from '@chakra-ui/button';
```

but it only reduced about 3kb (parsed size) which is almost nothing. Is my approach incorrect? You can check my loader code [here](https://github.com/woohyun-park/chakra-imports-loader). Does anybody have custom approaches to this problem?
