### ISSUE TITLE
[Progress] Can't use color hues

### ISSUE THREAD

**Issue by pedro-lb** [chakra-ui/chakra-ui#1982]
# Bug report

Hey there! Thanks for this amazing lib.

I've found a bug in `Progress` component, using `"@chakra-ui/core": "^0.8.0"`.

## Describe the bug

We can't access color hue values (e.g. `green.50`, `blue.100`) within `Progress` component, using the `color` prop. It only accepts color names (such as `green`, `blue` and injects `500` as the default hue.

When I try to set `color="green.50"`, for example:

![image](https://user-images.githubusercontent.com/22061051/92407314-946a8100-f110-11ea-815d-aabef03856ea.png)

Looking into the HTML code, it actually injected `.500` (default hue) after the `color` prop value:

![image](https://user-images.githubusercontent.com/22061051/92407338-af3cf580-f110-11ea-8996-ca451a1b7056.png)

If I don't use any hue values, setting `color="green"`, it works. But then I can't access hue values 🤔 .

![image](https://user-images.githubusercontent.com/22061051/92407398-e1e6ee00-f110-11ea-8df7-fb08a19a5f20.png)

Also, strangely enough, other props such as `backgroundColor` actually work fine with hue values. Here's an example using `backgroundColor="green.100"`:

![image](https://user-images.githubusercontent.com/22061051/92407482-1195f600-f111-11ea-8bc4-7a864ab2c033.png)

## To reproduce

Use any hue value in `color` prop in `Progress` component

## Minimal reproduction

Reproducible demo here: https://codesandbox.io/s/chakra-ui-08-progress-color-bug-6dwcq

## Expected behavior

The `color` prop should identify the hue and avoid injecting `.500` as a default one if provided.

## Screenshots

![image](https://user-images.githubusercontent.com/22061051/92408289-6c305180-f113-11ea-9f25-d9ce958ed9cf.png)

## System information

- OS: macOS
- Version of @chakra-ui/core: 0.8
- Version of Node.js: 12

## Additional context

-

**Comment by with-heart** [comment]
Hi @pedro-lb! 

This is working as intended. https://chakra-ui.com/progress#progress-color 

`Progress` is one of the components that builds a set of colors for itself using a color scale. By providing `color`, you're telling it to use the provided color scale, which in this case defaults to `<color>.500`.

This is something you could override in 1.0 using [the new component theming api](https://next.chakra-ui.com/docs/theming/customize-theme) but unfortunately there is nothing for 0.8 that allows you to do the same.

**Comment by marcelchastain** [comment]
Ran into this same issue using `CircularProgressIndicator`.
Thanks for answering this @with-heart.
One thought I had in reading your reply: would it help to use a more explicit prop name to differentiate between components which accept `color` vs `colorScheme`?

**Comment by with-heart** [comment]
For sure @marcelchastain! We made that change as part of v1 :)
