### ISSUE TITLE
Some odds while upgrading to Chakra UI V 1.x

### ISSUE THREAD

**Issue by nisarhassan12** [chakra-ui/chakra-ui#1985]
Hi :) 

We have recently upgraded to chakra ui `v1.x` and while doing so I noticed 2 odd behaviours there are not bugs maybe

With the upgrade, the background colour with value keyword `cyan` was not showing up here. So I have added the following which works: 
```
background: theme.colors.cyan['500'],
```
Ref: https://github.com/NeonLaw/codebase/pull/744#discussion_r481439168

Opposite to what the migration docs https://next.chakra-ui.com/docs/migration#radio say the `Radio` component after the update is not taking up the 100% of the parent's width rather it's only taking up the content width:

![image](https://user-images.githubusercontent.com/46004116/91907826-fae04100-ecc3-11ea-9532-588d47dc91fb.png)

This is how it looks now after the update to v 1.x:

![image](https://user-images.githubusercontent.com/46004116/91907944-33801a80-ecc4-11ea-8407-79ac4967c676.png)

This is how it looked before:

![image](https://user-images.githubusercontent.com/46004116/91907997-4a267180-ecc4-11ea-9180-17300129a5a2.png)

Note: there was no `isFullWidth` prop used before.

I have added the above `width="100%"` so that it takes up the full width.

Ref: https://github.com/NeonLaw/codebase/pull/744#discussion_r481444198

**Comment by ljosberinn** [comment]
Hi, what do you mean by `the background color cyan was not showing up`? Could you provide a sandbox? :)

![image](https://user-images.githubusercontent.com/29307652/92414467-9ce4ab00-f154-11ea-86fc-b7274e6a0538.png)

Works both locally for me as well as in a sandbox, both with `bg` and `background` prop.

We will confirm the issue with `Radio` and update the docs accordingly, thanks!

**Comment by nisarhassan12** [comment]
Sorry for not being specific enough I meant that `background: 'cyan'` was not showing up on this line https://github.com/NeonLaw/codebase/blob/9c605100df0beb1864c406aaa93be6694d402eb7/packages/interface/src/components/homepage/help-with.tsx#L30 in the `&::after` block i.e It was not rendered at all.

![image](https://user-images.githubusercontent.com/46004116/92414541-205ec600-f16e-11ea-989d-c9e647327b27.png)

**Comment by ljosberinn** [comment]
Most colors on the theme are schemes - `cyan` is one of them, so `cyan.500` would work (or any of the other schemes declared [here](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/theme/src/foundations/colors.ts#L145)).
I suspect this is a mistake since you're actively referencing `['500']` in the theme as your fix, which is more or less the same? :)

![image](https://user-images.githubusercontent.com/29307652/92414979-21382d80-f157-11ea-9bc0-ec68aace0662.png)

**Comment by nisarhassan12** [comment]
Thanks. Sorry for my not too good communication skills. I was expecting the keyword `cyan` in isolation without having to reference any of the schemes i.e the word `cyan` is a valid CSS colour keyword value which works in Vanilla CSS. `cyan[500]` indeed works as expected. 

I feel like the keywords in isolation should also work :) .

**Comment by ljosberinn** [comment]
All good! :) I'm not sure from an implementation perspective whether that's possible, we'll talk about it. Which color would be picked, then? Considering `500` is a shade, if it's possible, I'd expect using `cyan` would default to `cyan.900` if anything. So I'd personally consider that misleading then.

**Comment by nisarhassan12** [comment]
Yeah. I'm also not sure either. Maybe it would be ok if cyan would default to just `cyan` i.e the browser built-in I think that won't be misleading.

**Comment by with-heart** [comment]
imo it'd be even more confusing for users if `cyan` by itself defaulted to a color that isn't even in the Chakra system. I think it's fine the way it is. We definitely need to take a closer look at documenting how colors work with the scales though, as a number of users are confused by it.

**Comment by segunadebayo** [comment]
Looking through this conversation, and I think it's fine the way it is, to be honest.

We can plan to document it some more in the future to clear any doubt or confusion.

Thanks for chiming in @with-heart and @ljosberinn. You guys are amazing!
