### ISSUE TITLE
[Modal] Android Chrome input focus causes scroll

### ISSUE THREAD

**Issue by joserocha3** [chakra-ui/chakra-ui#1986]
# Bug report

## Describe the bug

Weird issue on Android Chrome. I have a long page and scroll down quite a bit, then open a `Modal` and it has some `Input` components. If I click on an input the browser scrolls down and I can no longer see the focused input.

## To reproduce

1. Using Android Chrome go to https://3zf6r.csb.app
2. Scroll all the way to the bottom
3. Click the _Open Modal_ button
4. In the modal select the first input
5. You will see that the browser scrolls down the page and the input is no longer visible

## Minimal reproduction

https://codesandbox.io/s/xenodochial-boyd-3zf6r (https://3zf6r.csb.app)

## Expected behavior

When focusing on an input the browser should not scroll way down - the input should still be visible.

## Screenshots

![ezgif com-resize](https://user-images.githubusercontent.com/11415340/92419825-677c9500-f135-11ea-8cd9-424ce3aa5e78.gif)

## System information

- OS: Android (any version)
- Browser (if applies): Chrome
- Version of @chakra-ui/core: 1.0.0-rc.3

## Additional context
I noticed passing `blockScrollOnMount={false}` to the `Modal` stops the issue from occurring, but that leads to some other issues on various browsers. Either way sounds like `react-remove-scoll` has the issue or its not being configured correctly by Chakra.

**Comment by with-heart** [comment]
I can verify that this is happening on my device as well.

**Comment by joserocha3** [comment]
@with-heart thanks, man. You are super on top of everything. Thank you for confirming!

**Comment by segunadebayo** [comment]
@with-heart, can you confirm this is still an issue?

**Comment by with-heart** [comment]
I can confirm that this is still an issue on latest: https://codesandbox.io/s/beautiful-boyd-ukpcl?file=/src/App.js:322-323 (https://ukpcl.csb.app)

It appears to jump about 75% of the way down the page when selecting the input.

**Comment by klh** [comment]
do one of the following for your application

the meta viewport needs to be:
<meta name="viewport" content="width=device-width,height=device-height,initial-scale=1,shrink-to-fit=no">

and you need to add this to the manifest file:
"android:windowSoftInputMode="adjustResize" or "adjustPan"



or use JS to fix this via:

be sure to pop this inside any modal you create in your new system

```
  private handleAndroidResizeEvents = () => {
    if (document.activeElement.tagName == "INPUT") {
      window.setTimeout(function () {
        try {
          //@ts-ignore
          document?.activeElement?.scrollIntoViewIfNeeded(true)
        } catch (e) {
          //dev-null any errors here
        }
      }, 100)
    }
  }
```

trigger it from the resize event that is fired when a SoftKeyboard appears:

```
// fix for android devices where scrolling and softKeyboards MAY be
// acting weird when the modal contains an input field
if (this.isAndroidDevice) {
  window.addEventListener("resize", this.handleAndroidResizeEvents)
}
```

**Comment by klh** [comment]
also related make sure you only use aria-modal=true on NON IOS / WEBKIT devices due to this bug:https://bugs.webkit.org/show_bug.cgi?id=174667

**Comment by op2rules** [comment]
I'm having this issue, and I've tried many fixes but none seem to be working with NextJS
