### ISSUE TITLE
Incorrect definition of functions in EditableProps

### ISSUE THREAD

**Issue by FocalChord** [chakra-ui/chakra-ui#1987]
# Bug report

## Describe the bug

When you go to: https://chakra-ui.com/editable and in particular the EditableProps section, you will notice that `onCancel`, `onEdit` and `onSubmit` have a type string but it should be type func (similar to `onChange)

![Screen Shot 2020-09-08 at 12 50 13 PM](https://user-images.githubusercontent.com/31643423/92422531-d90a2100-f1d1-11ea-8089-642e10dba506.png)

From the Typescript definitions, they clearly should be functions:

![Screen Shot 2020-09-08 at 12 51 56 PM](https://user-images.githubusercontent.com/31643423/92422605-15d61800-f1d2-11ea-9fa8-a0298b2054e0.png)

**Comment by with-heart** [comment]
Yeap, this is definitely incorrect in the docs. Unfortunately since we're putting all of our effort into releasing 1.0, we're not doing any work on the existing `v0` docs. This issue is good documentation for anyone that discovers this in the future though!
