### ISSUE TITLE
Popover warning: Margin styles cannot be used for padding

### ISSUE THREAD

**Issue by zigzactly** [chakra-ui/chakra-ui#1988]
Hi there, i am getting a warning in Popover .

## Describe the bug
A warning displayed when wrapping HStack over a Popover component.
Popper: CSS "margin" styles cannot be used to apply padding between the popper and its reference element or boundary. To replicate margin, use the `offset` modifier, as well as the `padding` option in the `preventOverflow` and `flip` modifiers.
![image](https://user-images.githubusercontent.com/6165450/92454788-7d508f80-f1f3-11ea-8003-f8b2aa79f771.png)

## To reproduce
In essence, i am doing the following.
```
<Hstack>
   <Popover>
      <PopoverContent>
      </PopoverContent>
   </Popover>
</Hstack>
```
It seems like Hstack is injecting the margins into PopoverContent, which seems to be creating the warning.
```
.css-xxxxxx > *:not(style) ~ *:not(style) {
    margin-left: 0.5rem;
    margin-top: 0;
}
```
Using a Flex in place of Hstack does not have this same issue.

## Expected behavior
Should not get a warning.

I am using "@chakra-ui/core": "^1.0.0-rc.3"

**Comment by segunadebayo** [comment]
Hi @zigzactly,

This usage isn't correct because the placement and spacing is managed by popper.js, not Chakra.

I'd recommend not using Stack with Popover, Popper, or Menu. Kindly pass `placement` or `offset` prop to the `Popover` component to place it correctly.

Cheers

**Comment by nghieptiki** [comment]
@segunadebayo 
I have tried pass `offset` prop to the `Popover` and
>Property 'offset' does not exist on type 'IntrinsicAttributes & PopoverProps & { children?: ReactNode; }'.

![image](https://user-images.githubusercontent.com/54924428/94101786-ce4ebd80-fe5a-11ea-8b7f-d1a27b204628.png)

**Comment by lauritzsh** [comment]
@nghieptiki I wrapped it in a [Portal](https://next.chakra-ui.com/docs/overlay/popover#rendering-the-popover-in-a-portal) and it stopped complaining for me.

**Comment by laurensnl** [comment]
> @nghieptiki I wrapped it in a [Portal](https://next.chakra-ui.com/docs/overlay/popover#rendering-the-popover-in-a-portal) and it stopped complaining for me.

That worked for me too. Thanks!
