### ISSUE TITLE
[0.8] [Docs] [Tab] Disabled prop is not documented correctly

### ISSUE THREAD

**Issue by pedro-lb** [chakra-ui/chakra-ui#1991]
# Bug report

[The docs](https://chakra-ui.com/tabs#tab-props) say that the `disabled` prop is called `isDisabled`, but it's actually called `disabled`

![image](https://user-images.githubusercontent.com/22061051/92479848-76595b00-f1ba-11ea-9a7f-85a19c74804f.png)

![image](https://user-images.githubusercontent.com/22061051/92479982-a7399000-f1ba-11ea-88b4-d6b177ba1405.png)

![image](https://user-images.githubusercontent.com/22061051/92480013-b4567f00-f1ba-11ea-94a2-3e5570a78418.png)

## Describe the bug

The documentation should say it's called `disabled` instead of `isDisabled`.

## System information

- OS: macOS
- Version of @chakra-ui/core: 0.8
- Version of Node.js: 12

**Comment by with-heart** [comment]
Hi @pedro-lb, thanks for reporting this but we're very close to releasing 1.0 and are no longer doing work on `v0.8`. Hope you understand!
