### ISSUE TITLE
Using objects for Input theme breaks Textarea

### ISSUE THREAD

**Issue by tomdohnal** [chakra-ui/chakra-ui#1992]
# Bug report

## Describe the bug

Using the `Textarea` throws an error as it expects the `outline` property on the `Input` theme object to be a function. 
This seems to be the line causing it https://github.com/chakra-ui/chakra-ui/blob/develop/packages/theme/src/components/textarea.ts#L13.

I'm happy to send a PR if this gets confirmed as a bug.

## To reproduce

View the attached Codesanbox and uncomment line 30 in the `App.js` file.

## Minimal reproduction

https://codesandbox.io/s/awesome-goldwasser-o6sxj?file=/src/App.js

## Expected behavior

Using the `Textarea` throws an error as it expects the `outline` property on the `Input` theme object to be a function.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies): [e.g. Chrome, Safari]
- Version of @chakra-ui/core: 1.0.0-rc.c
- Version of Node.js: [e.g. 12.11.1]

**Comment by with-heart** [comment]
Hi @tomdohnal! The next release will include #1967 which correctly merges objects and functions. We hope to have it out shortly.
