### ISSUE TITLE
Editing global styles in theme.styles.global makes me lose the default style

### ISSUE THREAD

**Issue by rogor** [chakra-ui/chakra-ui#1994]
# Bug report

## Describe the bug

Nest.js app.

Editing global styles in theme.styles.global makes me lose the default style, even if I give it itself back.

## To reproduce
In **_app.js**:

This code makes me lose the default style (I notice it because the colors don't change in dark mode according to the default style):
```
import { ChakraProvider } from '@chakra-ui/core';
import { AppLayout } from 'components/AppLayout';
import { theme } from '@chakra-ui/core';
import { merge } from '@chakra-ui/utils';

const customTheme = merge(theme, {
  styles: {
    ...theme.styles,
    global: { ...theme.styles.global }, // Here is the problem
  },
});

export default function App({ Component, pageProps }) {
  return (
    <ChakraProvider resetCSS theme={customTheme}>
      <AppLayout>
        <Component {...pageProps} />
      </AppLayout>
    </ChakraProvider>
  );
}

```
But this code works perfectly and keeps the default style: 
```
import { ChakraProvider } from '@chakra-ui/core';
import { AppLayout } from 'components/AppLayout';
import { theme } from '@chakra-ui/core';
import { merge } from '@chakra-ui/utils';

const customTheme = merge(theme, {
  styles: {
    ...theme.styles,
    global: theme.styles.global, // No problem here
  },
});

export default function App({ Component, pageProps }) {
  return (
    <ChakraProvider resetCSS theme={customTheme}>
      <AppLayout>
        <Component {...pageProps} />
      </AppLayout>
    </ChakraProvider>
  );
}
```

I'm pretty sure both codes should do the same thing.
I can't figure out why they don't, and how to add something to theme.styles.global correctly without losing the default global style.

## System information

- OS: Windows
- Browser (if applies): Any
- Version of @chakra-ui/core: 1.0.0-rc.3
- Version of Node.js: v14.8.0

**Comment by zhenyuluo** [comment]
I think below page can help:

https://next.chakra-ui.com/docs/theming/customize-theme#customizing-global-styles

**Comment by segunadebayo** [comment]
Hi @rogor,

This is happening because the global styles in the theme is a function NOT an object. We've created a better way of extending the theme using `extendTheme`, thanks to @TimKolberger.

Here's the PR for that: https://github.com/chakra-ui/chakra-ui/pull/1967

We'll release an update shortly.

Cheers.
