### ISSUE TITLE
React does not recognize the `isFitted` prop on a DOM element.

### ISSUE THREAD

**Issue by victorwpbastos** [chakra-ui/chakra-ui#1995]
# Bug report

React complains about the `isFitted` prop when using Tabs. Maybe it is no exported correctly?

## Screenshots

![image](https://user-images.githubusercontent.com/1017515/92526175-66ae3680-f1fb-11ea-9456-6965a532f60b.png)

## System information

- OS: Windows
- Browser Chrome
- Version of @chakra-ui/core: 1.0.0-rc.3
- Version of Node.js: 12.18.1

**Comment by with-heart** [comment]
For anyone looking further into this, it looks like `isFitted` is left as part of `htmlProps` because it's not pulled out in `useTabs`.

**Comment by segunadebayo** [comment]
Hi @victorwpbastos,

I've just pushed a fix for this and it'll be released shortly.

Cheers.

PS: Thanks for the tip @with-heart, it helped me fix it quickly
