### ISSUE TITLE
Property 'name' does not exist on type 'IntrinsicAttributes & Pick<LinkProps...

### ISSUE THREAD

**Issue by jivinivan** [chakra-ui/chakra-ui#1996]
# Bug report

`name` is not allowed on `Link`. 

## To reproduce

1. Install `@chakra-ui/core@1.0.0-rc.3`
2. Add something like `<Link name="test"></Link>`
3. Typescript compilation fails

## Expected behavior

`name` should be allowed on `Link` because it's a valid prop of `a`.

## System information

- OS: macOS
- Browser: Chrome
- Version of @chakra-ui/core: 1.0.0-rc.3
- Version of Node.js: 10.21.0

**Comment by santialbo** [comment]
`name` is obsolete in HTML5
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Obsolete_attributes

**Comment by jivinivan** [comment]
I should have known to check. I thought it might be something like that. Thank you!
