### ISSUE TITLE
Style prop aliases (like `w` and `d`) don't work in Typescript

### ISSUE THREAD

**Issue by Vynlar** [chakra-ui/chakra-ui#20]
`styled-system` props work correctly, but the custom aliases added by chakra do not have the correct types.

Example:
```
<Box rounded="full" />
```
Results in a type error on rounded.

I've traced down what I believe to be the problem.
See `chakra-ui/src/Box/index.d.ts`:
```
...
interface ICustomConfig {
  // Custom borderRadius alias
  rounded?: StyledSystem.BorderRadiusProps;
...
```
The types are exporting the StyledSystem.BorderRadiusProps directly, but `BorderRadiusProps` is an interface with a single key `borderRadius`. In order to make the types match, we need to export the type of the key:
```
...
interface ICustomConfig {
  // Custom borderRadius alias
  rounded?: StyledSystem.BorderRadiusProps["borderRadius"];
...
```
This results in a valid code for the example above. A similar process could be used to fix many of the other aliased props like `shadow`, `w`, and `d`.

**Comment by segunadebayo** [comment]
Thanks for spotting that @Vynlar . This is good feedback.

I've resolved the types and will release a patch soon.

**Comment by Vynlar** [comment]
I believe this issue extends beyond just the `BoxProps`. For example the `Stack` component's `spacing` property expects `MarginProps` which is an interface as well. Not sure what the solution is here.
