### ISSUE TITLE
Add accessible Carousel component

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#200]
WAI-ARIA Authoring Practices has a [section](https://www.w3.org/TR/wai-aria-practices-1.1/#carousel) about building accessible carousel components:

> A carousel presents a set of items, referred to as slides, by sequentially displaying a subset of one or more slides. Typically, one slide is displayed at a time, and users can activate a next or previous slide control that hides the current slide and "rotates" the next or previous slide into view. In some implementations, rotation automatically starts when the page loads, and it may also automatically stop once all the slides have been displayed. While a slide may contain any type of content, image carousels where each slide contains nothing more than a single image are common.

I think there is a great opportunity to build a composable component by following [Reach UI's Philosophy](https://gist.github.com/ryanflorence/e5c794e6093d16a69fa88d2112a292f7). As I've observed, there are several layers of abstraction:

- Carousel – Similar to Reach UI's Dialog, it would just wrap the 2 children below
  - CarouselControls – [Contains](https://www.w3.org/TR/wai-aria-practices-1.1/#terms) Rotation Control, Next Slide Control, Previous Slide Control and Slide Picker Controls
  - CarouselRotator – Touch-controllable scroll container with a hidden scrollbar
    - CarouselSlide – Holds content to be presented

I've already started building the foundation of some components above, mostly by following [a CSS-Tricks article](https://css-tricks.com/can-get-pretty-far-making-slider-just-html-css/) about [Scroll Snap](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap):

#### CarouselRotator

```tsx
import { Flex, FlexProps } from '@chakra-ui/core';
import React from 'react';
import { MarginProps, ResponsiveValue } from 'styled-system';
import CarouselSlide from './CarouselSlide';

// TODO: https://www.w3.org/TR/wai-aria-practices-1.1/#grouped-carousel-elements

function negateResponsiveValue<T>(value: ResponsiveValue<T>) {
  if (value == null) return value;
  if (typeof value === 'number') return -value;
  if (typeof value === 'string') return `-${value}`;
  if (Array.isArray(value)) return value.map(v => (v != null ? `${-v}` : v));
  return Object.fromEntries(
    Object.entries(value).map(([k, v]) => [k, v != null ? `${-v}` : v]),
  );
}

export interface CarouselProps extends FlexProps {
  children: React.ReactComponentElement<typeof CarouselSlide>[];
  slideIndex?: number;
  spacing?: MarginProps['margin'];
  spacingX?: MarginProps['mx'];
  spacingY?: MarginProps['my'];
}

export default function Carousel({
  children,
  slideIndex = 0,
  spacing,
  spacingX,
  spacingY,
  ...restProps
}: CarouselProps) {
  return (
    <Flex
      as="section"
      aria-roledescription="carousel"
      aria-live="polite" // The carousel is NOT automatically rotating
      my={negateResponsiveValue(spacingY != null ? spacingY : spacing)}
      overflow="auto"
      css={{
        scrollSnapType: 'x mandatory',
        // TODO: Leave vendor prefixing to the underlying library
        '::-webkit-scrollbar': { width: 0 },
        '-msOverflowStyle': 'none',
        scrollbarWidth: 'none',
      }}
      {...restProps}
    >
      {React.Children.map(children, (child, i) =>
        React.cloneElement(child, {
          inert: i !== slideIndex ? '' : undefined,
          px: spacingX != null ? spacingX : spacing,
          py: spacingY != null ? spacingY : spacing,
        }),
      )}
    </Flex>
  );
}
```

There is still a lot of work to do, e.g. adding support for automatic rotating by setting `aria-live` to `off`.

#### CarouselSlide

```tsx
import { Box, BoxProps } from '@chakra-ui/core';
import React from 'react';

// TODO: Follow the status of https://github.com/WICG/inert and remove polyfill
import 'wicg-inert';

export default function CarouselSlide({
  children,
  inert,
  ...restProps
}: BoxProps) {
  return (
    <Box
      role="group"
      aria-roledescription="slide"
      flex="0 0 100%"
      css={{ scrollSnapAlign: 'center' }}
      {...restProps}
    >
      {/* TODO: Remove extra `div` once `shouldForwardProp` of `Box` supports `inert` */}
      <div inert={inert}>{children}</div>
    </Box>
  );
}
```

The `inert` attribute is required to disable tab navigation to undisplayed slides.

#### declarations.d.ts

Unfortunately, TypeScript and React don't support the `inert` attribute yet, thus, it cannot be specified as a boolean, [but an empty string: `''`](https://github.com/WICG/inert#2-toggle-inert-on-an-element).

```ts
declare module 'react' {
  interface DOMAttributes<T> {
    inert?: '' | undefined;
  }
}

declare global {
  namespace JSX {
    interface IntrinsicAttributes {
      inert?: '' | undefined;
    }
  }
}

export {};
```

**Comment by kripod** [comment]
An improved structure which just came to mind:

- [ ] **Carousel** – Wraps `CarouselContainer` along with initialized `CarouselControls` and `CarouselRotator`, passing children directly to the latter
- [ ] **CarouselContainer** – Responsible for setting ARIA props, e.g. `aria-roledescription` to `carousel`
- [ ] **CarouselControls** – Contains children to navigate between slides and toggle auto-rotation
- [ ] **CarouselRotator** – Wraps its children into (non-public) `CarouselSlide` components, controlling their padding and `inert` attribute

I’ll refactor the components above to match my new proposal, stay tuned for updates!

**Comment by segunadebayo** [comment]
Good work @kripod. To help us comprehend this better, it'll be nice to share a codesandbox link as well. It might also help if you show an example of how the components will be used. Something like:

```jsx
<Carousel>
  <CarouselContainer>
      <CarouselSlide />
  </CarouselContainer>
  <CarouselControls>
      <CarouselForwardArrow />
      <CarouselBackArrow />
  </CarouselControls>
</Carousel>
```

Not sure if this is the right structure but it's looking exciting already. For the `inert`, We already use a library called `aria-hidden` to help make dom nodes behind a modal `inert`. You can check the `Modal` component's code to see how it works.

I look forward to more updates on this.

**Comment by kripod** [comment]
@segunadebayo The structure is exactly as you’ve outlined, and `Carousel` could be used as follows:

```tsx
<Carousel slideIndex={n}>
  <img src=“…” alt=“…” />
  <img … />
  …
</Carousel>
```

As for the tip about the `inert` attribute, thanks for the heads-up, I’ll look into the source of `Modal`.

**Comment by kripod** [comment]
While [`aria-hidden`](https://github.com/theKashey/aria-hidden) (both as a library and an attribute) conceals given elements from the accessibility tree, it doesn't disable tabbing through them, [in contrast to the `inert` attribute](https://github.com/WICG/inert/blob/3d77d5ef431780ac72919d8ada151260631befdd/src/inert.js#L72-L81). If slides contain focusable or searchable elements, then the `inert` attribute seems to be mandatory.

**Comment by segunadebayo** [comment]
I agree. If you check the code, you'll see that we used a combination of `aria-hidden` and `react-focus-lock`. However, I'm excited to see how the `inert` attribute solves this issue.

**Comment by kripod** [comment]
I've made some progress by separating concerns and adding props like `infinite`, `autoPlay` and `playInterval`.

#### Carousel.tsx

```tsx
import React from 'react';
import CarouselContainer from './CarouselContainer';
import CarouselControls from './CarouselControls';
import CarouselRotator, { CarouselRotatorProps } from './CarouselRotator';

export default function Carousel(props: CarouselRotatorProps) {
  return (
    <CarouselContainer>
      <CarouselControls />
      <CarouselRotator {...props} />
    </CarouselContainer>
  );
}
```

#### CarouselContainer.tsx

```tsx
import { Box, BoxProps } from '@chakra-ui/core';
import React from 'react';

export default function CarouselContainer(props: BoxProps) {
  return <Box as="section" aria-roledescription="carousel" {...props} />;
}
```

#### CarouselControls.tsx

```tsx
import React from 'react';

// TODO: Consider renaming to `CarouselControlPanel`
export default function CarouselControls() {
  return <>{/* TODO: Add control components */}</>;
}
```

#### CarouselRotator.tsx

```tsx
import { Flex, FlexProps } from '@chakra-ui/core';
import React from 'react';
import { MarginProps, ResponsiveValue } from 'styled-system';
import { fromEntries } from '../utils/object';
import CarouselSlide from './CarouselSlide';

// TODO: https://www.w3.org/TR/wai-aria-practices-1.1/#grouped-carousel-elements

function negateResponsiveValue<T>(value: ResponsiveValue<T>) {
  if (value == null) return value;
  if (typeof value === 'number') return -value;
  if (typeof value === 'string') return `-${value}`;
  if (Array.isArray(value)) return value.map(v => (v != null ? `${-v}` : v));
  return fromEntries(
    Object.entries(value).map(([k, v]) => [k, v != null ? `${-v}` : v]),
  );
}

export interface CarouselRotatorProps extends FlexProps {
  children: React.ReactElement[];
  infinite?: boolean;
  autoPlay?: boolean;
  playInterval?: number;
  activeIndex?: number;
  spacing?: MarginProps['margin'];
  spacingX?: MarginProps['mx'];
  spacingY?: MarginProps['my'];
}

export default function CarouselRotator({
  children,
  infinite,
  autoPlay,
  playInterval = 5000,
  activeIndex = 0,
  spacing,
  spacingX,
  spacingY,
  ...restProps
}: CarouselRotatorProps) {
  return (
    <Flex
      aria-atomic={false}
      aria-live={autoPlay ? 'off' : 'polite'}
      my={negateResponsiveValue(spacingY != null ? spacingY : spacing)}
      overflow="auto"
      css={{
        scrollSnapType: 'x mandatory',
        // TODO: Leave vendor prefixing to the underlying library
        '::-webkit-scrollbar': { width: 0 },
        '-msOverflowStyle': 'none',
        scrollbarWidth: 'none',
      }}
      {...restProps}
    >
      {React.Children.map(children, (child, i) => (
        // Labels are lifted up to comply with WAI-ARIA Authoring Practices
        <CarouselSlide
          inert={i !== activeIndex ? '' : undefined}
          aria-label={child.props['aria-label']}
          aria-labelledby={child.props['aria-labelledby']}
          px={spacingX != null ? spacingX : spacing}
          py={spacingY != null ? spacingY : spacing}
        >
          {React.cloneElement(child, {
            'aria-label': undefined,
            'aria-labelledby': undefined,
          })}
        </CarouselSlide>
      ))}
    </Flex>
  );
}
```

#### CarouselSlide.tsx

```
import { Box, BoxProps } from '@chakra-ui/core';
import React from 'react';

// TODO: Follow the status of https://github.com/WICG/inert and remove polyfill
import 'wicg-inert';

export default function CarouselSlide({
  children,
  inert,
  ...restProps
}: BoxProps) {
  return (
    <Box
      role="group"
      aria-roledescription="slide"
      flex="0 0 100%"
      css={{ scrollSnapAlign: 'center' }}
      {...restProps}
    >
      {/* TODO: Remove extra `div` once `shouldForwardProp` of `Box` supports `inert` */}
      <div inert={inert}>{children}</div>
    </Box>
  );
}
```

**Comment by kripod** [comment]
Finally, I'm ready with the first version of the Carousel, implementing the basic variant outlined [in WAI-ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/#basic-carousel-elements). Unfortunately, I wasn't able to set up a CodeSandbox, but the code is available as a [part of a project](https://github.com/kripod/exigo/blob/415579b51c64e22fe866b63c5968005d4854a6b6/src/pages/carousel-demo.tsx) I'm working on.

### ❗ Live demo

A basic mobile-friendly demo is available from [here](https://5db0f36d1e0d920008bc8aee--exigo.netlify.com/carousel-demo/).

### ✨ Progressive enhancement

The components are made with older browsers in mind, providing graceful fallbacks in legacy environments. The `IntersectionObserver` polyfill is loaded conditionally through a dynamic import, evading network overhead for users of evergreen browsers.

### 🚀Usage examples

#### Basic

```tsx
function Component() {
  return (
        <Carousel isInfinite autoPlay maxWidth="xl" mx="auto">
      <Image
        alt="Aerial photography of lake viewing mountain under orange skies"
        src="https://images.unsplash.com/photo-1569302911021-297d2362e3d3?w=800&q=80"
      />
      <Image
        alt="Empty road near mountain"
        src="https://images.unsplash.com/photo-1569250814530-1e923fd61bc6?w=800&q=80"
      />
      <Image
        alt="Person standing near waterfalls"
        src="https://images.unsplash.com/photo-1569099377939-569bbac3c4df?w=800&q=80"
      />
    </Carousel>
  );
}
```

#### Advanced

Please see the [implementation of `Carousel`](https://github.com/kripod/exigo/blob/415579b51c64e22fe866b63c5968005d4854a6b6/src/components/Carousel.tsx#L17-L22) for further details.

### 📖 Reference

As seen in the advanced usage guide above, the implementation consists of:

- `Carousel`
  - `CarouselContainer`
    - `CarouselOverlay`
      - `CarouselPlayToggleIconButton`
      - `CarouselStepIconButton` x2
    - `CarouselRotator`
      - `CarouselSlide`

Following the [philosophy of Reach UI](https://gist.github.com/ryanflorence/e5c794e6093d16a69fa88d2112a292f7#composable), `Carousel` serves as a convenient wrapper around the `CarouselContainer` component, providing all the children out of the box. Most users will not have to know anything else about the details below.

`CarouselContainer` serves as a provider for establishing `CarouselContext`, and returns a `Box` with `aria-roledescription="carousel"`. The carousel's state can be accessed through a publicly available hook called `useCarouselControls`, offering high-level data and methods:

- `isInfinite`
- `isPlaying`, `togglePlaying()`
- `activeIndex`, `totalCount`, `goTo(index)`, `jump(delta)`

With those, custom components can be built conveniently. For instance, [`CarouselStepIconButton`](https://github.com/kripod/exigo/blob/415579b51c64e22fe866b63c5968005d4854a6b6/src/components/CarouselStepIconButton.tsx) was built relying solely upon the aforementioned utilities.

CarouselOverlay` provides control buttons absolutely positioned on the stacking context of `CarouselContainer`. Its descendants can be overridden naturally by providing `children`.

`CarouselRotator` is the heart of the pack, where all the magic happens. It manages the state of slides and handles user interactions like swiping or focusing with tab. In the future, slides could be virtualized or lazy-loaded for additional performance benefits.

Each slide is wrapped inside a `CarouselSlide`, and shall be labeled through the `aria-label` or `aria-labelledby` prop of carousel children.

Please let me know about any questions or concerns about the implementation, I'm all open for ideas and observations!

**Comment by kripod** [comment]
Legacy browser support is now available, along with several improvements for handling window size changes.

The latest source can be viewed from [here](https://github.com/kripod/exigo), along with a [live demo](https://exigo.netlify.com/carousel-demo).

**Comment by kripod** [comment]
I’ve sent a pull request, but have to mention the following annoyances:

- Carousel IconButtons have `variantColor=“blackAlpha”`, which are too transparent (0.08% visibility) in dark mode, causing a low contrast ratio. Is there a way to overcome this without having to hard-code values and overriding `_hover`? (@segunadebayo)
- Reduced motion setting isn’t respected after server-side rendering. This is [an issue](https://github.com/kripod/react-hooks/issues/114) with the underlying web-api-hooks library of mine.

Also, I’m planning to abstract the `useWindowResizing` logic into a generic [`useChanging` state wrapper hook](https://github.com/kripod/react-hooks/issues/113).

**Comment by segunadebayo** [comment]
@kripod, you might need to override the `_hover`, for now.

I'll look through the code soon.

**Comment by kripod** [comment]
Sorry for the radio silence. I'm working on my thesis at university and using Chakra as a UI lib to execute my project for that. I just realized that a Carousel may be controlled outside of a `CarouselRotator`, but controlled props may be ditched in favor of the `useCarouselControls` hook for improved interoperability with the inner state.

For instance, while controlling the component occasionally, we may still allow users to change slides.

**Comment by jamesarosen** [comment]
[WCAG 2.2.2](https://www.w3.org/WAI/WCAG21/Understanding/pause-stop-hide.html) says

> Auto-updating: For any auto-updating information that (1) starts automatically and (2) is presented in parallel with other content, there is a mechanism for the user to pause, stop, or hide it or to control the frequency of the update unless the auto-updating is part of an activity where it is essential.

Is that what `disableAutoPause` does? Is there a way for the user to trigger that?

**Comment by kripod** [comment]
@jamesarosen Actually, I have a [simpler implementation](https://github.com/kripod/exigo/tree/560f39c0ca30922b9c571cc15275e002b555f145/src/components) in progress, but didn't manage to actualize this PR yet. `disableAutoPause` is for adhering to the [example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/carousel/carousel-1.html) showcased [in WAI-ARIA Authoring Practices](https://www.w3.org/TR/wai-aria-practices-1.1/#carousel), by setting it to `true` when the keyboard or mouse focus is on the pause button:

> If the carousel can automatically rotate, it also:
>
> - […]
> - Stops rotating when keyboard focus enters the carousel. It does not restart unless the user explicitly requests it to do so.
> - Stops rotating whenever the mouse is hovering over the carousel.

**Comment by zasuh** [comment]
Is this component still going to be implemented or has it dropped off?

**Comment by segunadebayo** [comment]
@zasuh , it's definitely going to be implemented. I really appreciate the work of @kripod on this. I just haven't had some time to review the code completely and suggest improvements before merging.

**Comment by kripod** [comment]
@zasuh I also made several improvements over time which are not yet included in this PR. Eagerly waiting for the TypeScript release to update typings and continue work on this. Also, I’ll have final exams at university during the first quarter of January. I had to cope with similar tasks lately, explaining why I wasn’t so active lately.

**Comment by kripod** [comment]
Not stale!

**Comment by talentlessguy** [comment]
Looking forward in using this component because rn I have to use react-slick or my own slider

**Comment by corentinchap** [comment]
Any updates on this ?

**Comment by kripod** [comment]
@corentinchap Lately, I’ve been busy building [a CSS-in-JS library](https://github.com/kripod/glaze). The carousel implementation has to be rewritten for better type checking and performance. Unfortunately, I don’t think I’ll have time to execute this task on my own.

**Comment by segunadebayo** [comment]
We'll look into this after the next release. Thanks for your hard work on this @kripod.

**Comment by chrysb** [comment]
Hi friends! Is this happening?

**Comment by UcheSylvester** [comment]
Hello guys! 
@kripod I really appreciate your work on this. It's really amazing how much time, energy, and considerations you put toward this! Hoping we get this real soon as I now have to resort to using react-slick.

cc @segunadebayo

**Comment by with-heart** [comment]
@segunadebayo created a `Carousel` component for a non-Chakra project but it needs a little work to move it over into Chakra. This will likely be a post-1.0 feature, but it is still in the works.

**Comment by rohanrajpal** [comment]
+1 to this, would love this feature. Also any other recommendations for a library that can help me do this right now? I am building an intro page of a mobile PWA using Nextjs. So swipe support would be essential.

**Comment by UcheSylvester** [comment]
I can't wait for this too! 

But for the meantime, @rohanrajpal I use [Swiper](https://swiperjs.com/react/) which I found to be highly configurable. 
You should give it a try

**Comment by rohanrajpal** [comment]
> I can't wait for this too!
> 
> But for the meantime, @rohanrajpal I use [Swiper](https://swiperjs.com/react/) which I found to be highly configurable.
> You should give it a try

Thanks for sharing! I did try out swiper but just couldn't set it up along chakra UI. I must have been missing something, the `import 'swiper/swiper.scss'` goes in `_app.tsx`, right?

**Comment by UcheSylvester** [comment]
> > I can't wait for this too!
> > 
> > But for the meantime, @rohanrajpal I use [Swiper](https://swiperjs.com/react/) which I found to be highly configurable.
> > You should give it a try
> 
> Thanks for sharing! I did try out swiper but just couldn't set it up along chakra UI. I must have been missing something, the `import 'swiper/swiper.scss'` goes in `_app.tsx`, right?

I can't see the code but I'd probably say yes. You need to import swiper.scss in app.tsx or in the component where you're using swiper

**Comment by rohanrajpal** [comment]
> > > I can't wait for this too!
> > > But for the meantime, @rohanrajpal I use [Swiper](https://swiperjs.com/react/) which I found to be highly configurable.
> > > You should give it a try
> > 
> > 
> > Thanks for sharing! I did try out swiper but just couldn't set it up along chakra UI. I must have been missing something, the `import 'swiper/swiper.scss'` goes in `_app.tsx`, right?
> 
> I can't see the code but I'd probably say yes. You need to import swiper.scss in app.tsx or in the component where you're using swiper

Got it, thanks, man. Will give it a try soon.

**Comment by mrlmaia** [comment]
Any update?

**Comment by rohanrajpal** [comment]
> Any update?

Not sure about when it would come, but for now you can use Swiper slider, I'm using it in a project currently

https://github.com/SevaShop/sevashop/blob/main/pages/welcome.tsx

**Comment by bryantobing12** [comment]
while we are all waiting? any suggestion react library that good for carousel and easy to customize when using chakra?

**Comment by KandarpAjvalia** [comment]
@bryantobing12 @rohanrajpal mentioned the way he used swiper in their app [here](https://github.com/chakra-ui/chakra-ui/issues/200#issuecomment-755294911). Basically, swiper acts as a wrapper for any component that we want to use in a carousel.

**Comment by MA-Ahmad** [comment]
Any update on Carousel component?

**Comment by ETCasual** [comment]
Hi, is there any update on this component? :)

**Comment by philipguedes** [comment]
> I can't wait for this too!
> 
> But for the meantime, @rohanrajpal I use [Swiper](https://swiperjs.com/react/) which I found to be highly configurable.
> You should give it a try

For anyone using this lib with Chakra, the only way I could get it working properly was by setting a `max-width` for its wrapper otherwise it breaks the entire layout

```jsx
<Box maxW={['320px', '480px']}>
  <Swiper
    spaceBetween={0}
    slidesPerView={1}
    pagination={{ clickable: true }}
    onSwiper={(swiper) => console.log(swiper)}
    onSlideChange={() => console.log('on slide change')}
  >
    <SwiperSlide>Slide 1</SwiperSlide>
    <SwiperSlide>Slide 2</SwiperSlide>
    <SwiperSlide>Slide 3</SwiperSlide>
  </Swiper>
</Box>

```

**Comment by RobSchilderr** [comment]
> > I can't wait for this too!
> > But for the meantime, @rohanrajpal I use [Swiper](https://swiperjs.com/react/) which I found to be highly configurable.
> > You should give it a try
> 
> For anyone using this lib with Chakra, the only way I could get it working properly was by setting a `max-width` for its wrapper otherwise it breaks the entire layout
> 
> ```js
> <Box maxW={['320px', '480px']}>
>   <Swiper
>     spaceBetween={0}
>     slidesPerView={1}
>     pagination={{ clickable: true }}
>     onSwiper={(swiper) => console.log(swiper)}
>     onSlideChange={() => console.log('on slide change')}
>   >
>     <SwiperSlide>Slide 1</SwiperSlide>
>     <SwiperSlide>Slide 2</SwiperSlide>
>     <SwiperSlide>Slide 3</SwiperSlide>
>   </Swiper>
> </Box>
> ```

Hey do you have an example of how your components look like? 

And any other suggestion about a library that works with Chakra UI would be nice!

**Comment by muco-rolle** [comment]
> > I can't wait for this too!
> > But for the meantime, @rohanrajpal I use [Swiper](https://swiperjs.com/react/) which I found to be highly configurable.
> > You should give it a try
> 
> For anyone using this lib with Chakra, the only way I could get it working properly was by setting a `max-width` for its wrapper otherwise it breaks the entire layout
> 
> ```js
> <Box maxW={['320px', '480px']}>
>   <Swiper
>     spaceBetween={0}
>     slidesPerView={1}
>     pagination={{ clickable: true }}
>     onSwiper={(swiper) => console.log(swiper)}
>     onSlideChange={() => console.log('on slide change')}
>   >
>     <SwiperSlide>Slide 1</SwiperSlide>
>     <SwiperSlide>Slide 2</SwiperSlide>
>     <SwiperSlide>Slide 3</SwiperSlide>
>   </Swiper>
> </Box>
> ```

Can you please share a working demo I'm struggling to make it work?

**Comment by MA-Ahmad** [comment]
I have created a custom carousel component for my portfolio website with ChakraUI.
[Live link](https://mahmad.me/#/blog/notebook-app)
<img width="812" alt="Screenshot 2021-05-11 at 09 29 31" src="https://user-images.githubusercontent.com/37842853/117851659-61e2cc00-b23b-11eb-843e-a1559fb297d1.png">

**Comment by ostrebler** [comment]
Any update ?

**Comment by luisadriantt** [comment]
I just made a head start for an image carousel using chakra components and react responsive carousel, you can find it [here](https://github.com/luisadriantt/carousel-chakra)
![](https://raw.githubusercontent.com/luisadriantt/carousel-chakra/main/carousel.gif)

**Comment by gold-olar** [comment]
There is still no chakra carousel yet 🥺??

**Comment by gold-olar** [comment]
There is still no chakra carousel yet 🥺??

**Comment by octalpixel** [comment]
> There is still no chakra carousel yet 🥺??

@gold-olar , found this on the ChocUI site : https://choc-ui.tech/docs/elements/carousels

I believe this is maintained by a few from the Chakra UI team as well.

**Comment by gold-olar** [comment]
> > There is still no chakra carousel yet 🥺??
> 
> @gold-olar , found this on the ChocUI site : https://choc-ui.tech/docs/elements/carousels
> 
> I believe this is maintained by a few from the Chakra UI team as well.

Oh amazing thanks ! I actually saw some suggestions on this thread to check out [Swiper](https://swiperjs.com/react) and thats what I used eventually. 
I saw that the ChocUI is built exactly on Chakra and that's amazing. I would most definitely switch to that. Thanks again

**Comment by tornvallalexander** [comment]
Very unfortunate that this went cold 😔

**Comment by festus14** [comment]
@segunadebayo any update on the Carousel component? And whats your suggestion if we are to use another library. Thanks for the hardwork.

**Comment by RobSchilderr** [comment]
> @segunadebayo any update on the Carousel component? And whats your suggestion if we are to use another library. Thanks for the hardwork.

Good question!

**Comment by PreciousNiphemi** [comment]
it is 2021... still now carousel component?

**Comment by symplytheo** [comment]
I currently use this https://choc-ui.tech/docs/elements/carousels#carousels/wcp since it's based on chakra-ui. Did a little customization to show thumbnails and allow the use of props.

**Comment by rishi-raj-jain** [comment]
Any ETA?

**Comment by wazcov** [comment]
Did this ever get implemented?

**Comment by migsblock** [comment]
How is this not implement yet?

**Comment by TamirShklaz** [comment]
+1 can we please get a carousel component

**Comment by wtLau** [comment]
What should I do if I want to attempt finishing this carousel? I am building a carousel component for my work (we're building it with our own design system, but the logic should be transferable). I think it would be beneficial to contribute my recent knowledge to help make this happen.
