### ISSUE TITLE
Property 'as' does not exist on type 'BoxProps & { children?: ReactNode; }'.

### ISSUE THREAD

**Issue by mykhaliuk** [chakra-ui/chakra-ui#2002]
# Bug report

## Describe the bug

Typescript error: `Property 'as' does not exist on type 'ContainerProps & { children?: ReactNode; }'.`

## To reproduce

`"@chakra-ui/core": "^1.0.0-rc.3"`
`"typescript": "^4.0.2"`

```
import { ContainerProps, Container } from '@chakra-ui/core'

const LayoutContainer: React.FC<ContainerProps> = ({ as, children,  ...props}) => {
  return <Container {...{as, ...props}}>{children}</Container>
}
```

## Minimal reproduction

[Sandbox example](https://codesandbox.io/s/peaceful-shadow-umg8h?file=/src/App.tsx)

## Expected behavior

No error on prop `as`

## Screenshots
![Screenshot](https://i.ibb.co/2K2v8zr/Screenshot-2020-09-09-at-11-36-54.png "image")

## System information

- OS: macOS
- Browser: Any
- Version of @chakra-ui/core: 1.0.0-rc.3
- Version of Node.js: 14.8.0

**Comment by with-heart** [comment]
Hi @mykhaliuk! Thanks for reporting this issue. 

@segunadebayo I think we may need to adjust our implementation of `PropsOf` if we want this situation to work correctly. Not sure.

**Comment by segunadebayo** [comment]
@with-heart, I agree. From a type perspective, we can add `as` to the return type of `PropsOf`.

However, to get the `as` prop to infer types correctly @mykhaliuk, you might need to use the approach mentioned here:
https://github.com/chakra-ui/chakra-ui/blob/develop/website/pages/guides/as-prop.mdx

**Update:** I've added the `as` prop to the types so it works from a type perspective at least. We'll create a new release shortly.
