### ISSUE TITLE
Dead Link in Readme to Create React App Templates guide

### ISSUE THREAD

**Issue by FaizShah** [chakra-ui/chakra-ui#2006]
# Bug report

## Describe the bug

In the readme there is a dead link to create react app templates guide: https://next.chakra-ui.com/guides/cra-templates

## To reproduce

1. Go to https://github.com/chakra-ui/chakra-ui#create-react-app-templates
2. Click on "Check out our guide"
3. See: 

"NOT FOUND
You just hit a route that doesn't exist... the sadness."

**Comment by jmiazga** [comment]
Thanks for reporting this @FaizShah! The dead links have been fixed, but not deployed yet. Hopefully we can get it released soon.

**Comment by with-heart** [comment]
Deploying now 😎
