### ISSUE TITLE
Using Chakra components with storybook controls and args

### ISSUE THREAD

**Issue by hazem3500** [chakra-ui/chakra-ui#2009]
# Feature request

## Is your feature request related to a problem? Please describe.

I am trying to extend Chakra components for our design system and show them in storybook, my problem is that the `controls` tab and `prop table` are bloated with the styled props 
I was trying to make a story for the `Checkbox` component and this is how the control tab and props table looked
### control tab
![bloated control tab](https://live.staticflickr.com/65535/50326666562_eaeaeaa50e_o.png)
### props table
![bloated props table](https://live.staticflickr.com/65535/50327151047_22e34b685b_o.png)

I want to show only the main props (`isChecked`, `isDisabled`, `value`, etc.) that are the same as the one in the [docs](https://next.chakra-ui.com/docs/form/checkbox#props)

## Describe the solution you'd like

I am not sure exactly how to approach this issue, in storybook `main.js` file there is a way to filter props as mentioned [here](https://storybook.js.org/docs/react/configure/typescript/#mainjs-configuration) but what props should we filter on? I am aware that chakra exports `propNames` but am still left with **115** controls 😓.
![115 control tab](https://live.staticflickr.com/65535/50327021541_593ff5773e_o.png)
`propNames` doesn't include props such as [`sx`, `style`, `aria-hidden`, `onInput`, ...]
so maybe chakra can export a more comprehensive `propNames`.

## Describe alternatives you've considered

in storybook you could make it not infer the types from the component and you write the args manually as specified [here](https://storybook.js.org/docs/react/api/argtypes)
I guess this would work but that means we'll have to manually write the main props for each component.

## Additional context

Am not sure if this issue is directly related to Chakra, maybe it could be better submitted in the storybook repo

**Comment by segunadebayo** [comment]
@TimKolberger, Any ideas to help @hazem3500 with this?

**Comment by TimKolberger** [comment]
Hi @hazem3500,

There are two sources of numerous props. One is the styled system (`padding`, `color`, etc.) and the default HTML props `onChange`, `aria-*` etc.

The styled system props are, as you mentioned, defined in `import { propNames } from "@chakra-ui/styled-system"`.
The default HTML props can be filtered by checking for `node_modules` in its parent path.

Here is an extracted code snipped from the PR #2351 where I excluded the mentioned props in addition to `"as", "apply", "sx", "__css"`.

```ts
import { propNames } from "@chakra-ui/styled-system"
const excludedPropNames = propNames.concat(["as", "apply", "sx", "__css"])

const { parse } = docgen.withCustomConfig(tsConfigPath, {
    propFilter: (prop) => {
      const isStyledSystemProp = excludedPropNames.includes(prop.name)
      const isHTMLElementProp =
        prop.parent?.fileName.includes("node_modules") ?? false

      return !(isStyledSystemProp || isHTMLElementProp)
    },
  })
```

**Comment by hazem3500** [comment]
@TimKolberger sorry for the late reply 😅, I've tried the fix you've mentioned, the style props are being filtered but the HTMLElementProps arent because `prop.parent` is undefined.

Do you know of another way I can filter the HTMLElementProps?

**Comment by hazem3500** [comment]
Is there an exported list of HTMLELementProps I can filter with?

**Comment by cameronevans** [comment]
@hazem3500 this filter is working for me to just document  component's own props & inherited chakra component props
```js
propFilter: (prop) =>
            prop.parent !== undefined &&
            (!prop.parent.fileName.includes('node_modules') ||
              (prop.parent.fileName.includes('node_modules') &&
                prop.parent.fileName.includes('node_modules/@chakra-ui/') &&
                !prop.parent.fileName.includes(
                  'node_modules/@chakra-ui/styled-system'
                ))),

**Comment by hazem3500** [comment]
@cameronevans I've tried an approach similar to what you're suggesting and the problem is that `prop.parent` turns out to be `undefined` so am not sure if it's something in my configuration that is doing that or is there something else I am missing.

**Comment by hazem3500** [comment]
For anyone who is getting `prop.parent` as `undefined` I've fixed it by adding 
```json
"resolutions": {
   "typescript": "4.1.3"
},
```
in `package.json`, it doesn't have to be `4.1.3` it just needs to be the version you are currently using

**Comment by mkosir** [comment]
If somebody is missing full context where to put filtering props, it's in the Storybook `main.js` file.  
In my case I added it as such
```js
module.exports = {

...

  typescript: {
    check: false,
    checkOptions: {},
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      compilerOptions: {
        allowSyntheticDefaultImports: false,
        esModuleInterop: false,
      },
      shouldExtractLiteralValuesFromEnum: true,
      propFilter: (prop) => {
        const isStyledSystemProp = excludedPropNames.includes(prop.name);
        const isHTMLElementProp = prop.parent?.fileName.includes('node_modules') ?? false;
        return !(isStyledSystemProp || isHTMLElementProp);
      },
    },
  },
};
```

**Comment by jacobgranberry** [comment]
@hazem3500 

Hey there - would you mind sharing your entire main.js file?  I'm having trouble getting this method to work.

**Comment by bujardeari** [comment]
> ```ts
> import { propNames } from "@chakra-ui/styled-system"
> const excludedPropNames = propNames.concat(["as", "apply", "sx", "__css"])
> ```

Where did you define excludedPropNames?

**Comment by ezeikel** [comment]
@bujardeari It's defined in @TimKolberger 's answer above - https://github.com/chakra-ui/chakra-ui/issues/2009#issuecomment-722400651
