### ISSUE TITLE
[1.0][Icon] Can't use icons created by createIcon with TypeScript

### ISSUE THREAD

**Issue by pedro-lb** [chakra-ui/chakra-ui#2013]
# Bug report

## Describe the bug

Any icons that were created using `createIcon` throw errors when rendering them with TypeScript. This includes all Chakra UI default icons.

![image](https://user-images.githubusercontent.com/22061051/92959984-2ccf7100-f443-11ea-8f2a-2965138a1723.png)

![image](https://user-images.githubusercontent.com/22061051/92960011-39ec6000-f443-11ea-9864-7945f9e5e1c7.png)

However, icons that were created using the `Icon` component work fine:

![image](https://user-images.githubusercontent.com/22061051/92959799-d9f5b980-f442-11ea-94a3-e6c437b1aad1.png)

![image](https://user-images.githubusercontent.com/22061051/92959860-f1cd3d80-f442-11ea-9a84-a235b60e8bc9.png)

![image](https://user-images.githubusercontent.com/22061051/92959862-f4c82e00-f442-11ea-94ca-ac8270bd4eba.png)

## To reproduce

Use any icon exported by Chakra UI or create one icon with `createIcon`, then try to render it.

## Expected behavior

Icons created by `createIcon` should inherit `Icon` props.

## Screenshots

In description above

## System information

- OS: macOS
- Version of @chakra-ui/core: e.g. 1.0.0-rc.3
- Version of Node.js: 12
- Version of Typescript: 4.0.2

**Comment by ljosberinn** [comment]
That must be some local misconfiguration or lockfile issues, please try removing your lockfile & node_modules, reinstall and restart the TS server after.

![image](https://user-images.githubusercontent.com/29307652/92991401-d8c89900-f4e3-11ea-9b35-2716723987cb.png)

I'm using plenty of custom icons [here](https://github.com/ljosberinn/personal-react-boilerplate/blob/master/src/client/routes/Index/icons.tsx) and run `tsc --noEmit` as CI step.

**Comment by Harrisonl** [comment]
@ljosberinn I've also got this issue on the newest RC even after complete wipe of yarn.lock + node_modules

I'm using TS v3.9.5

My (hacky) solution is to do:

```ts
const SIcon: any = SettingsIcon

//.....
<SIcon />
```

Full Error


```
[tsserver 2769] [E] No overload matches this call.
  Overload 1 of 2, '(props: Pick<IconProps, "string" | "p" | "style" | "ref" | "key" | "sx" | "className" | "id" | "lang" | "tabIndex" | "role" | "color" | "aria-activedescendant" | "aria-atomic" | ... 674 more ... | "htmlSize"> & Pick<...> & { ...; } & Pick<...>): ReactElement<...> | null', gave the following error.
    Type '{}' is missing the following properties from type 'Pick<IconProps, "string" | "p" | "style" | "ref" | "key" | "sx" | "className" | "id" | "lang" | "tabIndex" | "role" | "color" | "aria-activedescendant" | "aria-atomic" | ... 674 more ... | "htmlSize">': htmlWidth, htmlHeight, htmlSize
  Overload 2 of 2, '(props: Pick<IconProps, "string" | "p" | "style" | "ref" | "key" | "sx" | "className" | "id" | "lang" | "tabIndex" | "role" | "color" | "aria-activedescendant" | "aria-atomic" | ... 674 more ... | "htmlSize"> & Pick<...>): ReactElement<...> | null', gave the following error.
    Type '{}' is missing the following properties from type 'Pick<IconProps, "string" | "p" | "style" | "ref" | "key" | "sx" | "className" | "id" | "lang" | "tabIndex" | "role" | "color" | "aria-activedescendant" | "aria-atomic" | ... 674 more ... | "htmlSize">': htmlWidth, htmlHeight, htmlSize
```

**Comment by segunadebayo** [comment]
This was recently fixed by @TimKolberger.

We'll push a new release shortly.

**Comment by ljosberinn** [comment]
FWIW - there seems to be an easy workaround:
- only have `@chakra-ui/core` and `@chakra-ui/icons` installed (unless you explicitly need others too) - most importantly, have them at `.rc3`. packages should always be in sync!
- remove your lockfile (`package-lock.json` or `yarn.lock`) and your `node_modules` before installing
