### ISSUE TITLE
[1.0] [Input] Variant does not work when using InputGroup

### ISSUE THREAD

**Issue by pedro-lb** [chakra-ui/chakra-ui#2014]
# Bug report

## Describe the bug

Version `1.0.0-rc3`.

When using the `Input` component as children of `InputGroup`, with  the `variant` prop passed to `Input` does not work anymore.

![image](https://user-images.githubusercontent.com/22061051/92964288-3d371a00-f44a-11ea-9298-cacd33ee27fe.png)

![image](https://user-images.githubusercontent.com/22061051/92964323-4922dc00-f44a-11ea-80ca-394d13b5e190.png)

![image](https://user-images.githubusercontent.com/22061051/92964362-58098e80-f44a-11ea-8864-864c3c7c0844.png)

However, if we pass the `variant` prop to `InputGroup` it works:

![image](https://user-images.githubusercontent.com/22061051/92964403-68216e00-f44a-11ea-8ce2-c3b4064dd97b.png)

![image](https://user-images.githubusercontent.com/22061051/92964417-6c4d8b80-f44a-11ea-9c2e-0aa5a08e6323.png)

## To reproduce

Render `Input` inside `InputGroup` and pass `variant` to the input.

## Expected behavior

The `variant` prop should be taken into consideration - it's being ignored.

## Reproducible demo

Link here: https://codesandbox.io/s/input-variant-issue-e5e0t?file=/src/App.tsx

## System information

- OS: macOS
- Version of @chakra-ui/core: e.g. 1.0.0-rc.3
- Version of Node.js: 12
- Version of Typescript: 4.0.2

**Comment by segunadebayo** [comment]
Thanks for catching this @pedro-lb.

I've just pushed a fix for this, and it'll be released shortly.

Cheers

**Comment by theahmadzai** [comment]
The same problem, so it is fixed how can I get the fix, I'm having this issue

**Comment by itsZeebo** [comment]
Has this bug fix been released yet?

**Comment by mrdulin** [comment]
Did you set up `ChakraProvider` correctly? See, https://chakra-ui.com/docs/getting-started#setup-provider
