### ISSUE TITLE
Base styles not overriding button component

### ISSUE THREAD

**Issue by iwatakeshi** [chakra-ui/chakra-ui#2015]
# Bug report

## Describe the bug

Hi, I'm trying to use the new `extendTheme` API for the `Button` component in a Next.js app. However, when I apply a height in the `baseStyle` property, the height stays the same (`2.5rem`). If I add a variant and then add a height, it overrides as expected.

```js
const Button = {
  baseStyle: {
   // not working
    height: 'auto',
   // works
    minHeight: '28px'
  },
  variants: {
    md: {
      // works
      height: 'auto'
    }
  }
}
```

## To reproduce

1. Setup a Next.js app with latest `rc` of Chakra UI
2. Add a `Button` style
3. Use `extendTheme` API
3. View changes in Developers tool

## Minimal reproduction

https://codesandbox.io/s/infallible-jang-p5o7k

## Expected behavior

The height changes based on `baseStyle`

## System information

- OS: MacOS
- Browser (if applies): Chrome, Firefox Developer Edition
- Version of @chakra-ui/core: 1.0.0-rc.3
- Version of Node.js: 14.x

**Comment by segunadebayo** [comment]
Hi @iwatakeshi,

Thanks for reporting this. We've fixed it in a recent PR and it'll be published shortly.

Cheers

**Comment by frysztak** [comment]
Hi @segunadebayo, just letting you know I'm having the same issue in v1.0.1

**Comment by LetMeDream** [comment]
I'm having the exact same problem. Still.  Height on baseStyle not working.
