### ISSUE TITLE
Right-positioned Toasts are too close to the edge!

### ISSUE THREAD

**Issue by akiarostami** [chakra-ui/chakra-ui#2018]
# Bug report

## Describe the bug

Toasts have a small margin on top, left, and bottom, but there's no margin with the right edge of the window when Toasts are positioned on the right side (both **top-right** and **bottom-right**)

## Expected behavior

There should be the same margin on the right as we have on the top, left, and bottom.

## Screenshots

![image](https://user-images.githubusercontent.com/1235113/92981919-d832f280-f450-11ea-89f8-61b5a3f0719d.png)

## System information

- OS: macOS
- Browser: Chrome
- Version of @chakra-ui/core: 1.0.0-rc.3

**Comment by ljosberinn** [comment]
Can't replicate this on the [docs](https://next.chakra-ui.com/docs/feedback/toast#position), do you have any custom styling possibly? Could you provide a sandbox?

`bottom-right` in comparison to `bottom-left`
![image](https://user-images.githubusercontent.com/29307652/92991277-1ed12d00-f4e3-11ea-8518-de4958332cd5.png)
![image](https://user-images.githubusercontent.com/29307652/92991324-66f04f80-f4e3-11ea-9b24-66196d945d5a.png)

`top-right` vs `top-left`
![image](https://user-images.githubusercontent.com/29307652/92991302-4e803500-f4e3-11ea-88ac-ce098dce8616.png)
![image](https://user-images.githubusercontent.com/29307652/92991315-5b9d2400-f4e3-11ea-9152-6acae18891ea.png)

**Comment by pedro-lb** [comment]
Can confirm - this is happening in our project too.

In our case, we have a `Box` in our component tree to set the background color:

```tsx
<Box bg="background" minHeight="100vh">
  <Router history={history}>
    <AppRouter />
  </Router>
</Box>
```

**Comment by ondrejhudek** [comment]
+1

**Comment by ljosberinn** [comment]
This has been fixed in `rc.4` and higher as we just found out on discord: https://canary.discord.com/channels/660863154703695893/758645914868514827/764849558865707018
