### ISSUE TITLE
[Modal] Consider using CSS Overscroll Behavior

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#202]
Scroll management has become [easier](https://developers.google.com/web/updates/2017/11/overscroll-behavior) with the [`overscroll-behavior`](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior) CSS rule. A [polyfill](https://github.com/wessberg/scroll-behavior-polyfill) is also available to maintain compatibility with older browsers.

**Comment by segunadebayo** [comment]
I've noted this and will look into it much later. At the moment, we don't plan to add it.

I'll add comments here once we try it.
