### ISSUE TITLE
Side navigation using the Drawer component

### ISSUE THREAD

**Issue by sorxrob** [chakra-ui/chakra-ui#2021]
# Feature request

## Is your feature request related to a problem? Please describe.

I recently discovered Chakra UI and I love it functionality-wise. I want to use the `Drawer` component as a sidebar nav to make it easier to compose dashboard layouts with Chakra.

## Describe the solution you'd like

Maybe adding a `fixed` prop will make the `Drawer` fixed? 

## Additional context

Here's a sample of what I'm trying to achieve https://vuetifyjs.com/en/examples/layouts/complex/.

**Comment by with-heart** [comment]
Hi @sorxrob! Closing this as a duplicate of #608!
