### ISSUE TITLE
Enable editing text-overflow property on input's placeholder

### ISSUE THREAD

**Issue by oahmaro** [chakra-ui/chakra-ui#2023]
# Feature request
Ability to enable editing text-overflow on input's placeholder
## Is your feature request related to a problem? Please describe.
no

## Describe the solution you'd like
using the _placeholder prop i don't have access to the text-overflow: 'ellipsis' that i can access with native css
[Example on stackoverflow](https://stackoverflow.com/questions/10556365/is-it-possible-to-ellipsize-placeholders-watermarks-in-html5/38248699)

## Describe alternatives you've considered
none

## Additional context
none

**Comment by segunadebayo** [comment]
Hi @oahmaro,

We've added support for this in the upcoming v1 release.

Cheers.
