### ISSUE TITLE
Can't use custom color from theme in Button component 

### ISSUE THREAD

**Issue by ruslan-mystore** [chakra-ui/chakra-ui#203]
trying to use custom color from theme object in button component

That's not working

`
        <Button variantColor="newColor" size="md">
          Button
        </Button>
`

But when using same color in Box component , it's working:

`
        <Box my={2} bg="newColor">
          some box here
        </Box>
`

here is the example:
https://codesandbox.io/s/vibrant-bush-76581

**Comment by segunadebayo** [comment]
Hi @ruslan-mystore,

I should have made it clearer in the docs but to use to `variantColor` with a custom color, you need to create a color object of this shape:

```jsx
const brand = {
  100: "",
  200: "",
  500: "", 
  ...,
  900: ""
}
```

The reason is that `Button` has interactive styles (hover, action, disabled) and we pick color values from the object to make it work out of the box.

Use a tool like https://colorbox.io or  https://smart-swatch.netlify.com to generate this quickly.

In the future, we'll make this more declarative so you'll be in control of this behavior.

**Comment by Prottoy2938** [comment]
@segunadebayo , I've followed what you've said, but still can't seem to fix the warning and can't use the color.

`theme.tsx` looks like this: 

```javascript
import { theme } from "@chakra-ui/core";

const customTheme = {
  ...theme,
  colors: {
    ...theme.colors,
    primary: {
      100: "#CFD1FD",
      200: "#A7ABFB",
      300: "#8388F9",
      400: "#6268F8",
      500: "#444BF7",
      600: "#262EF6",
      700: "#0B14F5",
      800: "#0911DD",
      900: "#080FC7",
    },

    grey: {
      50: "#f0f0fa",
      100: "#d1d3e1",
      200: "#b3b6c9",
      300: "#9499b4",
      400: "#777c9f",
      500: "#5d6385",
      600: "#484d69",
      700: "#34374b",
      800: "#1e212e",
      900: "#080b14",
    },
  },
};

export default customTheme;
```

And I'm trying to use the `grey.900` color in this button

```javascript
 <Button
                isLoading={loginLoading.accountCreating}
                loadingText="Creating Account"
                variantColor="grey.900" //error here. Note that
                variant="outline"
                type="submit"
                height="43px"
                width="300px"
                border="2px"
                className={styles.submitBtn}
              >
                Create Account
              </Button>
```

**Comment by mattszeto** [comment]
I had the same problem, but I just think chakra doesn't allow for selecting which level (100,200,..). 

I fixed this by just changing my `.500` to the color value that I wanted to show.

**Comment by mattszeto** [comment]
@Prottoy2938 , One fix that I just found was to import `theme.tsx` and do `{theme.colors.grey[900]}`

**Comment by sethburtonhall** [comment]
I thought it would be helpful to share [this code sandbox](https://codesandbox.io/s/divine-surf-p19px?file=/src/App.tsx:0-86) for anyone with the same issue.

Thanks @dodas !!

**Comment by nimit95** [comment]
I am facing the same issue!
One thing I noticed is the colors are getting appended with wrong codes like red.500 becomes red.500.600 in html.

**Comment by Ladvace** [comment]
I still have this issue

**Comment by with-heart** [comment]
@nimit95 @Ladvace Really need to CodeSandbox examples to be able to help you.

**Comment by Ladvace** [comment]
I'm not doing something special, I just create a basic app with `create-react-app` and I'm trying to change a button color in the following way

```

const customTheme = extendTheme({
  colors: {
    purple: "#8966ff",
    brand: {
      50: "#ece4ff",
      100: "#c4b2ff",
      200: "#9d80ff",
      300: "#754dff",
      400: "#4f1bfe",
      500: "#3601e5",
      600: "#2900b3",
      700: "#1c0081",
      800: "#10004f",
      900: "#060020",
    },
  },
});

// App.js

   <ChakraProvider theme={customTheme}>
      <Router>
        <App />
      </Router>
    </ChakraProvider>
```



`
       <Button
          variantColor="brand.100"
   
        >
         Click here
        </Button>
`

**Comment by sethburtonhall** [comment]
Rename variantColor to color scheme

https://chakra-ui.com/docs/migration
