### ISSUE TITLE
Feature request: accessible combobox

### ISSUE THREAD

**Issue by AlexFrazer** [chakra-ui/chakra-ui#2031]
# Feature request

## Is your feature request related to a problem? Please describe.

I wouldn't call it a _problem_, but the nearest component I have found is a `Select`, which doesn't quite fit the needs I have. I need to dynamically filter the options and provide a more detailed UI around them.

It looks like the job for a **Combobox**, as per:

https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html

## Describe the solution you'd like

This is really just a composition of existing components with some related contexts/properties to ensure full accessibility. This is actually quite easy to make with the existing components in chakra

[I think it was done very cleanly in reach ui](https://reach.tech/combobox). Basically, break it down the following way:

- **Combobox**: the controller/context provider that renders a containing div. Could compose `@chakra-ui/form-control`
- **ComboboxInput**: The input that allows you to type in it. Could compose `@chakra-ui/input`
- **ComboboxPopover** the component that contains the popover portal. Could compose over `@chakra-ui/popover`
- **ComboboxList** container for the set of results. Could compose `@chakra-ui/list`.
- **ComboboxOption**. Container for a specific option. Could compose `ListItem` from `@chakra-ui/list`.
- **ComboboxOptionText**. Container for the text within the option. Maybe... compose `@chakra-ui/text`? I don't know for this one.

## Describe alternatives you've considered

What I have been doing is basically what is described above: I have taken the `@reach/combobox` and wrapped it in these components. It works reasonably well.

## Additional context

I'm not totally sure if this is appropriate for chakra-ui to handle, but I would be willing to provide a pull request to supply the code, absolutely.

**Comment by silviuaavram** [comment]
You can also do it with Downshift's `useCombobox`. Here is a draft, sorry about the styling.

https://codesandbox.io/s/mystifying-taussig-6c43h?file=/src/Combobox.jsx

There is someone already creating a multiple selection combobox with Chakra UI and useCombobox and looks super dope! We are going to post it in our examples / docsite.

**Comment by with-heart** [comment]
Hi @AlexFrazer, thanks for the suggestion! Closing this as adding a multiselect/combobox component is work we have planned for the near future: https://github.com/chakra-ui/chakra-ui/issues/1293#issuecomment-734437449

**Comment by rodrigoea** [comment]
I built a simple version using Chakra-UI, you don't have to install anything else.

https://github.com/chakra-ui/chakra-ui/issues/1293#issuecomment-1599296636

**Comment by tristan-derez** [comment]
> 

this is a multiselect tho
