### ISSUE TITLE
Upgrading to rc.3 makes "as" work unexpectedly

### ISSUE THREAD

**Issue by panbanda** [chakra-ui/chakra-ui#2032]
# Bug report

## Describe the bug

I am upgrading from rc.2 to rc.3 and I am now getting compile errors for `as=` in `Box`

```
export function Table(props: BoxProps): JSX.Element {
  return <Box as="table" width="full" {...props} />;
}

export function TableHead(props: BoxProps): JSX.Element {
  return <Box as="thead" {...props} />;
}

export function TableRow(props: BoxProps): JSX.Element {
  return <Box as="tr" {...props} />;
}
```

## To reproduce

Add an `HTMLTableElement` tag to Box

## Minimal reproduction

https://codesandbox.io/s/great-glitter-qkm7o?file=/src/App.tsx

## Expected behavior

Allow other HTML elements besides `div` to work with `Box`

## System information

Typescript 4.0.2
@chakra-ui/* ^1.0.0-rc.3

**Comment by segunadebayo** [comment]
Hi @panbanda,

This has been fixed in a recent PR, I believe this error would vanish once we release `rc4`. It's an issue with the `as` prop and here's a walkaround.

```tsx
type As = string | React.ComponentType

const Table = (props: BoxProps & {as?: As})=>{
  return <Box as="table" {...props} />
}
```

Cheers.
