### ISSUE TITLE
Fullscreen modal

### ISSUE THREAD

**Issue by oahmaro** [chakra-ui/chakra-ui#2033]
# Feature request
 I want to be able to make Modal go full screen on mobile
## Is your feature request related to a problem? Please describe.
on chakra documentation if i add `<Modal bottom={0} h='100%' size='full'>` the modal would go full screen but when doing the same on my project it doesn't work, it seams that the docs is using different version of charkra

## Describe the solution you'd like
  I would like to have a prop that would make the modal go full screen

## Describe alternatives you've considered
i am considering creating a component that would go full screen but then i would have to manage focus trap and accessibility that comes out of the box with chakara's modal

**Comment by segunadebayo** [comment]
Hi @oahmaro, quick questions

- What version of Chakra are you using?
- Can you provide a Codesandbox reproduction of this issue?

**Comment by oahmaro** [comment]
I am using version 0.8.0, i have checked the interactive edit on the docs and now i can't make it go full screen too.

So my question is how can i make modals go full screen in Chakra?

**Comment by bamtheboozle** [comment]
@oahmaro did you find a solution?

**Comment by oahmaro** [comment]
@bamtheboozle try passing `size="full"` prop to the `<Modal>` and `m={0} rounded="none"` to the `<ModalContent>`
