### ISSUE TITLE
Multi-line truncate for text components

### ISSUE THREAD

**Issue by hazem3500** [chakra-ui/chakra-ui#2036]
# Feature request

## Is your feature request related to a problem? Please describe.

I have a text that I want to truncate after 3 lines like this ![truncated paragraph](https://i0.wp.com/css-tricks.com/wp-content/uploads/2013/05/clamped.png)

## Describe the solution you'd like

We can add a prop `lineClamp` to text components and use CSS [link clamp](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp) property to make it work

**Comment by segunadebayo** [comment]
Hi @hazem3500,

We recently introduced this in the upcoming v1 release. The prop is called `noOfLines` and here's a quick docs update I made just for you to see:

https://github.com/chakra-ui/chakra-ui/commit/3f1db7603bad7aa9a13787f3a60a0ed1987a06ce

Hope this solves the problem you have in mind.

Cheers.

**Comment by hazem3500** [comment]
That's awesome, thank @segunadebayo 😄

**Comment by adirgil** [comment]
there is a way to detect if the text reach the 3 lines? 
lets say i want to add a button that says "read more" and then set the "noOfLines" to undefined and show the all message.
there is a way that i can decide if to put this button or not? i want to show the button only when i indeed reach the all 3 lines.
