### ISSUE TITLE
Add Menu to AvatarGroup when a max is set

### ISSUE THREAD

**Issue by hazem3500** [chakra-ui/chakra-ui#2038]
# Feature request

## Is your feature request related to a problem? Please describe.

I want to show a menu showing the rest of the users that exceed the max limit set on the `AvatarGroup` component
### Example
![Avatar group with menu](https://live.staticflickr.com/65535/50343931413_d7389e0212_o.png)
 
## Describe the solution you'd like

We could add a way to wrap the remaining avatar label with a `Menu` component, maybe something like this
```jsx
<AvatarGroup size="md" max={2}>
  <Avatar name="Ryan Florence" src="https://bit.ly/ryan-florence" />
  <Avatar name="Segun Adebayo" src="https://bit.ly/sage-adebayo" />
  <Avatar name="Kent Dodds" src="https://bit.ly/kent-c-dodds" />
  <Avatar name="Prosper Otemuyiwa" src="https://bit.ly/prosper-baba" />
  <Avatar name="Christian Nwamba" src="https://bit.ly/code-beast" />
  <Menu>
     <MenuButton>
      <AvatarGroup.Remaining/>
     </MenuButton>
     <MenuList>
        { /* ... */ }
     </MenuList>
  </Menu>
</AvatarGroup>
```
or add `Menu` inside `AvatarGroup` component and we pass a prop `remainingMenuOption` on how to render the remaining avatars in the menu list

```jsx
<AvatarGroup 
size="md" 
max={2} 
remainingMenuOption={({name, src}) => 
<AvatarGroup.MenuOption>
  <Avatar name={name} src={src}/>
  <Text>{name}</Text>
</AvatarGroup.MenuOption>
}>
  <Avatar name="Ryan Florence" src="https://bit.ly/ryan-florence" />
  <Avatar name="Segun Adebayo" src="https://bit.ly/sage-adebayo" />
  <Avatar name="Kent Dodds" src="https://bit.ly/kent-c-dodds" />
  <Avatar name="Prosper Otemuyiwa" src="https://bit.ly/prosper-baba" />
  <Avatar name="Christian Nwamba" src="https://bit.ly/code-beast" />
</AvatarGroup>
```
these are rough ideas, I am not sure if spacing for the `AvatarGroup` would still work for the first example.
I am also aware that `AvatarGroup` doesn't take a list of users so am not sure how it will pass the `name` and `src` to `remainingMenuOption`.

**Comment by ljosberinn** [comment]
Personally havent tried this yet but... what about:
```js
<Menu as={AvatarGroup}>
  <MenuButton as={Avatar}>
    ...
  </MenuButton>
  <MenuList>
    <MenuItem as={Avatar}>...</MenuItem>
  </MenuList>
</Menu>
```

**Comment by with-heart** [comment]
Hi @hazem3500, I'm going to close this as we're trying to clean up our issues backlog. Could you let us know if the solution from @ljosberinn worked for you?

**Comment by hazem3500** [comment]
@with-heart @ljosberinn sorry for the late reply 😅,
I've tried what @ljosberinn suggested but am not sure what is the intended behavior
I've created a [codesandbox](https://codesandbox.io/s/avatar-group-with-menu-hmqrq) with an example

The problem is that I don't have access to the `excessLabel` or no way to wrap the `MenuButton` around it
and I also don't have access to the `excess` users so I can put them inside `MenuList` and wrap them with `MenuItem`.

Although I would've preferred to compose the current `AvatarGroup`, the option that I see viable is that I'll need to recreate my own `AvatarGroup` component, unless we could an add an API that somehow gives us access to the `ExcessLabel` and `ExcessAvatars`.

If that would be possible I would imagine the API to be something similar to

```jsx
<Menu>
	<AvatarGroup max={5} excessLabelWrapper={MenuButton}>
        {({excessAvatars, max}) => (
            <>
                {users.map(user) => <Avatar name={user.name} src={user.avatar} />}
                <MenuList>
                    {excessAvatars.map((ExcessAvatar, i) => (
                        <MenuItem>
                            <ExcessAvatar /> <Text>{users[max + i].name}</Text>
                        </MenuItem>
                    ))}
                </MenuList>
            </>
        )}
    </AvatarGroup>
</Menu>
```

**Comment by with-heart** [comment]
That's an interesting use case. We'd need to add a context behind `AvatarGroup` and some additional components that allow you to use the excess avatars in some way. Not sure if that's effort we'd be interested in spending, but I'll reopen it as a feature so we can consider it.

**Comment by with-heart** [comment]
Since we're a small team with limited time and resources, we're going to close this issue as we have no plans to work on this soon. Hope you understand!

**Comment by hazem3500** [comment]
Oh, no problem, I am willing to make a PR with this feature if you'd like 😄
