### ISSUE TITLE
Ability to change check-mark Icon in checkbox component

### ISSUE THREAD

**Issue by hazem3500** [chakra-ui/chakra-ui#2039]
# Feature request

## Is your feature request related to a problem? Please describe.

In our design, the checkbox Icon is different from the one in Chakra

## Describe the solution you'd like

We could add a `selectedIcon` prop to `Checkbox` and we can use it like this
```jsx
<Checkbox checkedIcon={<CheckMarkIcon/>}/>
```
and it could default to chakra's checkmark Icon

**Comment by ljosberinn** [comment]
Seems reasonable.

[This](https://github.com/chakra-ui/chakra-ui/blob/f95cafaa74536784da09b6c50dc37ece5c005cb9/packages/checkbox/src/checkbox.icon.tsx#L15) is the current `<CheckboxIcon />`. As you can see, such an icon would need to accept `isChecked` at the very least, if not also `isIndeterminate` (that'd depend on your implementation then).

To stay in line with how other components manage it, it should be simply `icon`, accepting `React.ReactElement` which internally gets cloned via `React.cloneElement`, injecting the props.

**Comment by hazem3500** [comment]
@ljosberinn why would the icon need to accept `isChecked` prop, couldn't we just not render the icon when it's not checked?

**Comment by ljosberinn** [comment]
Ah yeah it doesn't, its just omitted from spreading onto `Icon`. That sounds like to me https://github.com/chakra-ui/chakra-ui/blob/f95cafaa74536784da09b6c50dc37ece5c005cb9/packages/checkbox/src/checkbox.tsx#L155 this line can be omitted too.
