### ISSUE TITLE
Deal with custom icons in TS

### ISSUE THREAD

**Issue by cschroeter** [chakra-ui/chakra-ui#204]
Following the guide to add custom icons I get an TypeScript eror that the name is not assignable.

```tsx
<Icon name="custom-icon" size="20px" color="gray.400" />
```

```
Type '"custom-icon"' is not assignable to type '"link" | "time" | ...
```

Is there a ways to override the `export type Icons ..` ?

**Comment by segunadebayo** [comment]
Hi @cschroeter, 

We'll look into this in the next TS release. I hope you can find a walkaround for now.

**Comment by cschroeter** [comment]
yeah somehow ^^ @segunadebayo  if you need any help with the ts release please let me know

**Comment by segunadebayo** [comment]
Yes, I need some help with the ts-release, particularly around theming and supporting custom types for icons, component variants, sizes, etc.

If you have any ideas, I'll love to hear them.

**Comment by cschroeter** [comment]
@segunadebayo regarding the icons:

I think it is not the best approach having the icons within your theme. From a developer point of view its pretty nice to write something like `<Icon name="close" />`. 

The downside on this approach that you have no tree shaking option here, since you always will add all the icons to your bundle. So if I only add one icon in my app, all other icons also gets bundled. 

So instead of this

```tsx
<Button leftIcon="add">Hello World</Button>
```

I would rather go with this API

``` tsx
import AddIcon from './Icons'     

<Button>
  <AddIcon mr={2} />
  Hello World
</Button>

```

**Comment by tony** [comment]
Is there a workaround we have in the meantime? If you have one, feel free to mention it here or link to it :) Thank you!

**Comment by tony** [comment]
@cschroeter 

Hi!  I created a PR that relaxes the typing here to allow custom icons.

This means the area isn't as strongly typed, but sense any icon name can be used, it may also be more accurate in a sense.

Technically, there may not be a benefit to use `Icons` either as a typing if any string is acceptable.

**Comment by tony** [comment]
In my situation, I opted to use font awesome bundles from CDN

There isn't an easy way to do this with `Icon`, but here's what I did:

```typescript
import Box from "@chakra-ui/core/dist/Box";
import Icon from "@chakra-ui/core/dist/Icon";

const FaIcon = ({ name }: { name: string }) => (
  <Box
    as="em"
    className={`fas fa-${name}`}
    lineHeight="1.2rem"
    marginLeft="-.25rem"
    marginRight="0.5rem"
    verticalAlign="middle"
    display="block"
  />
);

const FaBook = () => <FaIcon name="book" />;
const FaBookmark = () => <FaIcon name="bookmark" />;
const FaDownload = () => <FaIcon name="download" />;
const FaHome = () => <FaIcon name="home" />;
const FaInfo = () => <FaIcon name="info" />;
const FaNewspaper = () => <FaIcon name="newspaper" />;

const MyComponent = () => {
  return (
    <Button leftIcon={FaBook} {...dictionaryLink} mr="1rem">
            Dictionary
   </Button>
  )
}
```

**Comment by cpouldev** [comment]
@tony (and future others who'll face this)

this is what I do instead, without the need to load the full CDN (also tree shaking works :) )

A more "chakra-y" way

-- 

Each FontAwesome react icon is an `IconDefinition` which has the following format

```typescript
interface IconDefinition  {
  prefix: string;
  iconName: string;
  icon: [
    number, // width
    number, // height
    string[], // ligatures
    string, // unicode
    IconPathData // svgPathData
  ];
}
```

So based on that data, I created a helper function which in conjunction with **chakra's** `createIcon` helper, it accepts an `IconDefinition` and spits out a supported element to use with chakra's `Icon`

```tsx
import { Icon, createIcon } from '@chakra-ui/react'
import { faImage, IconDefinition } from '@fortawesome/pro-solid-svg-icons'

function faIcon(icon: IconDefinition) {
    let [w, h, lig, unicode, p] = icon.icon

    return createIcon({
        viewBox: `0 0 ${w} ${h}`,
        displayName: icon.iconName,
        path:
            typeof p === 'string' ? (
                <path fill="currentColor" d={p} />
            ) : (
                <g>
                    {p.map((pt, ix) => (
                        <path key={ix} d={pt} />
                    ))}
                </g>
            ),
    })
}
```

**Example**

```jsx
<Icon as={faIcon(faImage)} />
```

pinging @segunadebayo about this. Is it worth adding a better version of this snippet in your docs (or even better, provide an official adapter) for [react-fontawesome](https://www.npmjs.com/package/@fortawesome/react-fontawesome) users? FA is being used by lots and lots of people and I'm pretty sure that many will find it super useful
