### ISSUE TITLE
TabIndicator is not calculated correctly when used wihtin a Drawer

### ISSUE THREAD

**Issue by cschroeter** [chakra-ui/chakra-ui#2040]
# Bug report

## Describe the bug
The `TabIndiciator` does not calculate its position correctly when used in a component like a Drawer but also when for example resizing the window.

## Minimal reproduction

https://codesandbox.io/s/hardcore-dawn-w88t5?file=/src/App.tsx

## Expected behavior

![expected-tab-indicator](https://user-images.githubusercontent.com/1846056/93199356-92c33d80-f74e-11ea-8cb6-157e425a5819.png)

## Actual behavior
![actual](https://user-images.githubusercontent.com/1846056/93199380-9bb40f00-f74e-11ea-9e16-2e0de8612983.png)

**Comment by atk** [comment]
It seems to work if you replace position: absolute with position: fixed in the styles of the indicator.

**Comment by Samic8** [comment]
@with-heart Could you assign this one to me, please? I will be able to work on it next Monday/Tuesday

**Comment by segunadebayo** [comment]
Go for it! @Samic8

**Comment by Samic8** [comment]
I'm working on this now. I don't think position fixed on the tab indicator is going to be a good solution. Because then the developer might end up with the tab indicators positioned on top of other elements like modals.

**Comment by Samic8** [comment]
It seems the core issue is that we are calculating the tab indicator with `getBoundingClientRect` which returns values relative to the window. Then when the tab indicator is used in a relative or fixed element the `left` property is way off.

So far I'm thinking we make the tab element relative and calculate the tab indicator position based on the tab element. Probably by adding up the size of each tab button. I'll give this a go and report back.

**Comment by Samic8** [comment]
I've got a solution that is mostly working in 1afffa0. But I've realise it has a flaw. If the tabs root element has padding then the calculated position is off.

**Comment by Samic8** [comment]
I have a PR up, but I'm not sold on the solution. Please let me know of any feedback.

**Comment by atk** [comment]
While you could use offset[Top|Left|Width|Height] properties to get the exact sizes relative to the next parent node with position:relative, your solution is somewhat more robust in the unlikely but not to be ruled out case that another relative parent comes in between. So I'd be happy with your solution. Just my 2ct.

**Comment by Samic8** [comment]
Thanks for taking a look. I'll put up a PR and see what others think too.

**Comment by Samic8** [comment]
Actually I already had a PR up but it was closed recently. Not sure why.

**Comment by albertkimdev** [comment]
I'm using the Navbar with tabs in chakra ui pro

https://pro.chakra-ui.com/components/marketing/navbars

And when I change my font using the theme the tabindictor is misaligned on initial load

![image](https://user-images.githubusercontent.com/7885328/125661415-0a7056ec-1e84-478d-9469-76d349825b69.png)

My _app.tsx

```ts
import "@fontsource/open-sans";
import "@fontsource/kadwa";
import type { AppProps } from "next/app";
import { ChakraProvider } from "@chakra-ui/react";
import { UserContextProvider } from "@/utils/useUser";
import Layout from "@/components/ui/layout/Layout";
import theme from "@/utils/theme";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ChakraProvider theme={theme}>
      <UserContextProvider {...pageProps}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </UserContextProvider>
    </ChakraProvider>
  );
}

export default MyApp;
```

And the theme

```ts
import { extendTheme } from "@chakra-ui/react";

const theme = extendTheme({
  fonts: {
    heading: "Open Sans",
    body: "Kadwa",
  },
});

export default theme;
```

If I don't change the font, then it's not misaligned. But if I change the font it becomes misaligned.

**Comment by atk** [comment]
Unfortunately, the font change is not detected and thus the position not recalculated. You could fix that by manually changing the key on the TabIndicator.

**Comment by albertkimdev** [comment]
@atk 

Can you provide an example of how to "change the key on tabindicator" so that it fixes? 

Here is what I have

```js
 const [tabIndex, setTabIndex] = React.useState(0);
...
<Tabs
        onChange={(index) => setTabIndex(index)}
        colorScheme="blue"
        variant="unstyled"
        isFitted
      >
        <TabList>
          {children.find((child) => child.type === Links)?.props.children}
        </TabList>
        <TabIndicator
          key={tabIndex}
          mt="6.5px"
          height={1}
          borderTopRadius="md"
          bg={mode("blue.500", "blue.200")}
        />
</Tabs>
```

Which still is misaligned

I added the onchange handler to update the index state which then I set as the key on TabIndicator

![image](https://user-images.githubusercontent.com/7885328/125839210-3ef9639b-ba4d-4b35-b424-af21e2837883.png)

**Comment by atk** [comment]
You could use something like https://github.com/eduardomb/onfontload to detect the font change and force a re-render.

**Comment by stefee** [comment]
I am finding that the TabIndicator position does not update on window resize using latest Chakra.
https://threavetech-ija42tjyd-threavetech.vercel.app/

The source uses the NavbarWithTabs from the Chakra UI Pro components which I have slightly adapted for me needs:

```jsx
    <Flex
      py={6}
      px={{ base: 4, md: 6, lg: 8 }}
      bg={mode("white", "gray.800")}
      boxShadow="none"
      borderBottomWidth={mode("0", "1px")}
      alignItems="center"
    >
      {children.find((child) => child.type === Brand)?.props.children}
      <Spacer />
      <HStack display={{ base: "none", md: "flex" }} marginStart={4}>
        <Tabs
          id="tabs-1"
          defaultIndex={props.defaultTabIndex}
          colorScheme="green"
          variant="unstyled"
          isFitted
        >
          <TabList>
            {children.find((child) => child.type === Links)?.props.children}
          </TabList>
          <TabIndicator
            mt="13px"
            height={1}
            borderTopRadius="md"
            bg={mode("green.600", "green.200")}
          />
        </Tabs>
      </HStack>
```
