### ISSUE TITLE
extending theme doesn't work consistently

### ISSUE THREAD

**Issue by hesxenon** [chakra-ui/chakra-ui#2042]
# Bug report

Extending theme granularly, i.e. by wanting to override only a single leaf property doesn't work for most components

## To reproduce

Try to override _just_ the color of the menu items.

## Minimal reproduction

https://codesandbox.io/s/focused-brook-z0tdo?file=/src/App.js

## Expected behavior

The default theme should be merged with the provided object, leading to a theme that has all the values from the default theme except for the color value of items in a menu, which should be `blue`.

## Additional context

Since `lodash.merge` is used by `extendTheme` and the default menu theme is based on functions, the whole `baseStyle` function simply is overwritten with the passed object, leading to the erasure of all default values from the baseStyle section.

This means that for every component I want to "extend" I have to go to the chakra commit of the package I'm using, copy over all the default styles and put my values instead of the default values. Not really an extension imho.

Imho this is not covered under the warning in the docs regarding function style overrides, as I'm not the one using functions here, and if you decide to not enable this it should be mentioned that (pretty much) any component customization will have to include _all_ styles necessary to render it and not just the granular adaptations.

**Comment by segunadebayo** [comment]
Hi @hesxenon,

This has been resolved in a recent PR. We changed `lodash.merge` to `lodash.mergeWith` to allow more granular control of how the merge happens, especially between functional styles and pure object styles.

We'll improve the docs to clarify this a bit more.

Cheers
