### ISSUE TITLE
function style overrides don't get passed the same args depending on their nesting level

### ISSUE THREAD

**Issue by hesxenon** [chakra-ui/chakra-ui#2043]
# Bug report

## Describe the bug

Function style overrides are described like they'll be passed the props of the corresponding component, however this isn't always the case. This leads to the inability of overriding colors based on the colorMode granularly.

## To reproduce

1. Try overriding a high level property, e.g. baseStyle with a function and log the props
2. Try overriding a leaf property, e.g. color of menu items with a function and log the props
3. Notice that for high level properties the whole props object is passed (including `colorMode`) while for leaf properties (`color`, `bg`...) only the theme is passed from the props.

## Minimal reproduction

https://codesandbox.io/s/determined-cache-t5zsu

## Expected behavior

If you provide the (very nice) option of overriding styles based on a function, I'd expect either explicit documentation what is being passed to this function in which case, or that the very same arguments are passed to the function no matter where in the theme I place it.

## Additional context

This is especially annoying when I would expect this following snippet to work
```typescript
extendTheme({
  componens: {
    button: {
      color: mode('light", 'dark')
    }
  }
})
```
but it doesn't work because the returned function from mode expects the colorMode to be present in the args (which it isn't in this case)

**Comment by segunadebayo** [comment]
Hi @hesxenon,

We recently fixed this by providing an `extendTheme` function which merges both function and non-function style overrides.

Kindly try it in the latest rc release and let us know if you run into any issues.

Cheers.
