### ISSUE TITLE
MenuItemOption docs are messed up

### ISSUE THREAD

**Issue by gregdingle** [chakra-ui/chakra-ui#2045]
# Bug report

## Describe the bug

Some of the props are clearly misdescribed.

## To reproduce

See https://next.chakra-ui.com/docs/overlay/menu#menuoptiongroup-props and `menu.d.ts`. They don't match up.

**Comment by segunadebayo** [comment]
Thanks for catching this @gregdingle.

I've just pushed a fix for it. We'll release an update shortly.
