### ISSUE TITLE
[Input] custom padding alignment issue in IE11

### ISSUE THREAD

**Issue by wKovacs64** [chakra-ui/chakra-ui#206]
Found a strange issue when trying to use Chakra UI in an app that targets IE11. If you put custom padding on an `Input`, it will start with the input text aligned to the bottom of the input. Clicking it will then cause it to jump. I think it has something to do with `line-height` but I haven't been able to narrow it down exactly.

---

Demo:

![chakra-input-padding-ie11](https://user-images.githubusercontent.com/1288694/67417482-1cda4480-f586-11e9-9dda-3a2ffacd031a.gif)

Here's the entire code for that:

```jsx
function App() {
  return (
    <ThemeProvider>
      <CSSReset />
      <Box p={4}>
        <Text mb={4}>Custom padding:</Text>
        <Input autoFocus p={2} />
        <Text my={4}>Default padding:</Text>
        <Input />
      </Box>
    </ThemeProvider>
  );
}
```

And here it is deployed (make sure to use IE11 - it works fine in other browsers):

https://chakra-ui-issue-206.netlify.com/

**Comment by segunadebayo** [comment]
Yes, it has to do with the `height`, `line-height` and `padding` combo in IE11. 

My guess is that you might need to get rid of `line-height` or `height` to use padding.

I haven't tested it yet but I'll look into it soon.

**Comment by wKovacs64** [comment]
Removing `line-height` appears to fix it for IE11, but I assume `line-height` is there for a reason so we can't just remove it. Do you have any thoughts on a how to handle this?

**Comment by segunadebayo** [comment]
I'm signing up for Browser Stack, so I can look into this issue more thoroughly.

**Comment by wKovacs64** [comment]
Oh stalebot, you rascal.

**Comment by wKovacs64** [comment]
Shush, stalebot.

**Comment by wKovacs64** [comment]
🤫

**Comment by with-heart** [comment]
Such dedication to seeing this resolved!

Sorry for the stale spam. I'll open a PR soon to prevent this from being tagged again.

**Comment by segunadebayo** [comment]
@with-heart Please file in a PR for this so we can get it fixed. It's been up for too long

**Comment by with-heart** [comment]
Sorry Justin! We're actually going to close this because we're focusing on the 1.0 future. We haven't touched pre-1.0 in quite some time and don't plan on any further releases unless there are vulnerabilities we need to fix.

See https://next.chakra-ui.com/ for more info on 1.0, which will be out asap!
