### ISSUE TITLE
Bottom drawer doesn't scroll overflow content

### ISSUE THREAD

**Issue by dwainetrain** [chakra-ui/chakra-ui#2060]
# Bug report

## Describe the bug
Content with overflow added to a bottom positioned drawer does not scroll. Instead the content continues to fill up the space on the page beyond the size designation. In Chrome and Firefox on Mac I'm seeing a wall of text that I can't scroll, the only way to close the drawer is to hit esc. 

## To reproduce
Add a copious amount of text to the the Drawer contents then set its position to bottom and then open the drawer.

Take attached file contents and insert into the https://next.chakra-ui.com/docs/overlay/drawer#drawer-placement and then choose bottom and then open the drawer. 

[bottom_drawer_no_scroll.txt](https://github.com/chakra-ui/chakra-ui/files/5240193/bottom_drawer_no_scroll.txt)

- [CodeSandbox Example](https://codesandbox.io/s/vibrant-poitras-7x6j6?file=/src/App.js)

## Expected behavior

To be able to scroll the inner content of the drawer while still keeping the designated size.

## System information

- OS: Mac Catalina
- Browser (if applies): Chrome and Firefox Developer
- Version of @chakra-ui/core@1.0.0-rc.3
- Version of Node.js: v14.3.0

**Comment by with-heart** [comment]
Related issue: #1862

**Comment by mahmoodhosseini** [comment]
I'd like to work on this issue.

**Comment by segunadebayo** [comment]
This can be solved by setting a `maxH=100vh` on the `DrawerContent`.

I've gone ahead to add it by default to this component so it doesn't happen to others as well.

Thanks for catching this @dwainetrain
