### ISSUE TITLE
[Stack] Spacing overrides margin values given directly to children

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#207]
When using a `Stack`, it sets the `mt`, `mr`, `mb` or `ml` props of its children to value determined by `spacing`. Unfortunately, they cannot be overrided manually:

```tsx
function Component() {
  return (
    <Stack spacing={2}>
      <Box>foo</Box>
      <Box mr={100 /* Gets overrided */}>bar</Box>
      <Box>baz</Box>
    </Stack>
  );
}
```

**Comment by segunadebayo** [comment]
I see what you mean. Please feel free to send a PR to fix this.

We'll have to check if `child.props.mr || child.props.marginRight` exists and use that instead of `spacing` value.

**Comment by kripod** [comment]
On the other hand, this behavior might be intentional, and `Flex` with `flexDirection="column"` should be used as an alternative.

**Comment by segunadebayo** [comment]
I agree. Let's leave it as it is in order not to complicate the `Stack` component.

Thanks for this suggestion.

**Comment by segunadebayo** [comment]
Closing this in favor of the suggested alternative.

**Comment by jescowuester** [comment]
To simplify the stack component we could also use sth like this instead of cloneElement:

```
.stack > * + * {
  margin-bottom: 1.5rem;
}
```

That way it can be easily overwritten and it would make the component more intuitive as well IMO.

**Comment by b-novikov-ipersonality** [comment]
*powerful necromancer rushes in this issue and reanimates it*
I think `Flex` with `flexDirection="column"` is not an alternative, at least not a good one. Say I have 10 elements within `Flex`, most of them using the same spacing, but few of them  are using another spacing. It'd be convenient for me to use `VStack` with spacing that is used by most elements, and to set spacing for other elements manually.
With `Flex` on the other hand I have to  manually set desirable margins on all of them.
