### ISSUE TITLE
InputLeftElement crashes when rendered with MDX

### ISSUE THREAD

**Issue by meoyawn** [chakra-ui/chakra-ui#2070]
# Bug report

## Describe the bug

InputLeftElement crashes when rendered with MDX

## To reproduce

Launch this and observe the error https://codesandbox.io/s/sweet-monad-00ed3

## Minimal reproduction

https://codesandbox.io/s/sweet-monad-00ed3

## Expected behavior

InputGroup is rendered without errors

**Comment by meoyawn** [comment]
this probably won't solve it but it points to the code: https://github.com/chakra-ui/chakra-ui/pull/2067

**Comment by segunadebayo** [comment]
Merged the PR that solved this issue.
