### ISSUE TITLE
child of tooltip requires ability to handle refs

### ISSUE THREAD

**Issue by hesxenon** [chakra-ui/chakra-ui#2076]
# Documentation request

Docs don't mention that components you wrap in a `Tooltip` need to be able to have refs. I.e. tooltips don't work on functional components as popperjs isn't invoked.

Not really a problem per sé, but took quite a while to find out, a notice or warning would be nice.

**Comment by with-heart** [comment]
Good idea @hesxenon!

**Comment by segunadebayo** [comment]
Thanks for noting this @hesxenon.

I've updated the docs for tooltip to add this warning.
