### ISSUE TITLE
InputLeftElement Icon disappears on focus, Input variant filled not working

### ISSUE THREAD

**Issue by theahmadzai** [chakra-ui/chakra-ui#2078]
# Bug report

1. Input variant="filled" not working
2. InputLeftElement Icon disappears on focus

## To reproduce

Go to the contact form and interact
pantherspainting1.surge.sh

## Minimal reproduction

https://github.com/theahmadzai/pantherspainting/blob/master/src/components/contact-form.js

## System information

- OS: Windows
- Browser: Chrome
- Version of @chakra-ui/core: 1.0.0-rc.3
- Version of Node.js: 12.11.1

## Additional context

First of all thanks for building such a cool open-source software, any idea when will be the stable version of chakra-ui/core@next released?

**Comment by la55u** [comment]
#1900 I'm waiting for this one to be released as well

**Comment by theahmadzai** [comment]
There was a problem with my theme, the dark theme is working now but other issue remains.

**Comment by with-heart** [comment]
We're releasing `1.0.0-rc.4` very soon (today or tomorrow) and this issue will be resolved then! Sorry for the delay.
