### ISSUE TITLE
Editable Text not showing defaultValue in preview. 

### ISSUE THREAD

**Issue by MsMaddyMac** [chakra-ui/chakra-ui#2082]
# Bug report

## Describe the bug

Preview mode is not working although I have provided a default value. It remains in editable mode. Tried setting startWithEditView to false and it still doesn't work.

## To reproduce

The default value of "currentDisplayName" should be displayed as normal text on the screen but it is not. 

## Minimal reproduction

https://codesandbox.io/s/awesome-kilby-trhe2?file=/src/App.js

## Expected behavior

The default value of currentDisplayName(which is a string "Maddy2") should be displayed as normal text on the screen but it is not. 

## Screenshots
My local project not showing preview mode of default value text.

![Screen Shot 2020-09-23 at 12 50 28 PM](https://user-images.githubusercontent.com/53921783/94045256-38089200-fd9d-11ea-913d-04c01625933e.png)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies): [e.g. Chrome, Safari]
- Version of @chakra-ui/core: [e.g. 1.0.0-rc.3]
- Version of Node.js: [e.g. 12.11.1]

**Comment by segunadebayo** [comment]
<img width="1307" alt="Screen Shot 2020-09-24 at 12 44 46 PM" src="https://user-images.githubusercontent.com/6916170/94122561-c3e4f180-fe63-11ea-85d1-bcdb635dc0c1.png">

Hi @MsMaddyMac,

I opened the codesandbox and found that it's working as expected. Is there something I'm missing?

**Comment by MsMaddyMac** [comment]
That is very interesting because it definitely wasn't working when I sent
it. You see on line 23 I added placeholder text because when it wasn't
there, the screen was blank. Not only was preview mode not working, the
default placeholder wasn't either. Now that it is working in codesandbox, I
am even more curious why it doesn't work in my project with the setup being
the exact same. The only difference now being the default value is user.bio
instead of the shape I had as an example in the sandbox above. This is only
because we were able to make a change in how our user data was coming back.
It is no longer an array but an object.

[image: Screen Shot 2020-09-25 at 8.35.52 AM.png]
[image: Screen Shot 2020-09-25 at 8.38.03 AM.png]

Here you can see the user bio being console logged but still not showing up.

[image: Screen Shot 2020-09-25 at 8.42.07 AM.png]

The only way I can get the bio showing is to pass it in the placeholder
attribute and change the color of the text to match the normal text.

**Comment by segunadebayo** [comment]
We'll look into this some more once we can properly reproduce it.

For now, permit me to close this.
