### ISSUE TITLE
[Popover][V1] Popover always trigger onClose

### ISSUE THREAD

**Issue by hosmelq** [chakra-ui/chakra-ui#2083]
# Bug report

## Describe the bug

The `onClose` function is triggered even when the Popover is closed.

## To reproduce

Click anywhere and you will see an alert.

## Minimal reproduction

[codesandbox](https://codesandbox.io/s/bold-dream-3fvyt)

## Expected behavior

Do not trigger `onClose` when the popover is closed.

## System information

- Version of @chakra-ui/core: [1.0.0-rc.5]

**Comment by nghieptiki** [comment]
Same issue.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. Thanks for catching it.
