### ISSUE TITLE
[Popover][V1] 'returnFocusOnClose' does not exist on type 

### ISSUE THREAD

**Issue by nghieptiki** [chakra-ui/chakra-ui#2084]
# Bug report
```jsx
<Popover returnFocusOnClose={false}>
     <PopoverTrigger>
            <button>
                  Trigger
             </button>
    </PopoverTrigger>
....
</Popover>
```
The problem same with the `offset` prop.

## Screenshots
![image](https://user-images.githubusercontent.com/54924428/94106428-900acb80-fe65-11ea-86e0-06382c14e446.png)

## System information
- Version of @chakra-ui/core: [e.g. 1.0.0-rc.3]

**Comment by segunadebayo** [comment]
Hey @nghieptiki,

I've just pushed an update for this and we'll publish an update shortly.
