### ISSUE TITLE
Pass styleConfig part styles to custom ClassName props

### ISSUE THREAD

**Issue by hazem3500** [chakra-ui/chakra-ui#2085]
# Feature request

## Is your feature request related to a problem? Please describe.

I am trying to style a component from an external library using Chakra multipart component theming, the component has multiple className props for each of it's part I want to pass the part styles from the styleConfig to the part className.

## Describe the solution you'd like

I want to be able to do something similar to this
```tsx
export const CustomComponent= () => {
    const styles = useStyleConfig('CustomComponent', {});
    return (
        <ExternalComponent 
          className={styles.container}
          wrapperClassName={styles.wrapper}
          // or 
          otherClassName={sx(styles.other)}  />
    );
};
```
Is this already possible? if so maybe we could add this to the docs.

If it's not, what is the recommended alternative?

## Describe alternatives you've considered

I can just write CSS classNames but I wanted to use the design tokens from the theme

**Comment by TheThirdRace** [comment]
Not technically classnames, but you can use `useMultiStyleConfig()` for multi-part components.

See [useMultiStyleConfig()](https://next.chakra-ui.com/docs/theming/component-style#styling-multipart-components)

**Comment by hazem3500** [comment]
@TheThirdRace my mistake 😅, I actually use `useMultiStyleConfig`, but how will using it solve my problem?

**Comment by TheThirdRace** [comment]
As I said, not classes per se, but it should allow you to do what you want:

```
import { Box, useMultiStyleConfig } from '@chakra-ui/core'

export const MyComponent = ({ children }: MyComponentProps): ReactElement => {
	const styles = useMultiStyleConfig('PageHeader', {})

	return (
		<Box
			as='header'
			sx={styles.classOne}
		>
			<Box sx={{ ...styles.classTwo, ...styles.classThree }}>
				<Box sx={styles.classFour}>{children}</Box>
			</Box>
		</Box>
	)
}
```

Then define a multi-part theme and it should work.

**Comment by TheThirdRace** [comment]
If my previous answer doesn't work, you can make a global class in your theme:

```
// animation for header
'.animated-header': {
	position: 'sticky',
	top: '0',
	transition: 'top 0.5s'
},
'.animated-header--hide.animated-header--hide': {
	top: '-100px'
}
```

These classes will be injected at the top of every page. You can override pretty much everything with it.

You might be able to restrict it to a component in particular without the need for global styles.

myComponentStyle.ts
```
export const MyComponentStyle= {
	baseStyle: {
		color: 'blue.100',

		'.classOne': {
			color: 'green.200'
		},
		'> *': {
			color: 'pink.300'
		}
	},
	defaultProps: { }
}
```

component.ts
```
import { Box, useStyleConfig } from '@chakra-ui/core'

export const MyComponent = ({ children }: MyComponentProps): ReactElement => {
	const styles = useStyleConfig('MyComponentStyle', {})

	return (
		<Box
			sx={styles}
		>
			<CustomComponent />
		</Box>
	)
}
```

**Comment by with-heart** [comment]
Going to close this as we haven't heard from @hazem3500 in awhile. If you're still having issues, feel free to reply or join us in discord https://discord.com/invite/dQHfcWF

**Comment by hazem3500** [comment]
I've ended up doing what @TheThirdRace suggested above, forgot to close the issue though 😅.

Thanks @TheThirdRace & @with-heart

**Comment by ruddi10** [comment]
@hazem3500 @TheThirdRace can you please help me out how you finally styled the external component

**Comment by hazem3500** [comment]
@ruddi10 you do as mentioned here https://github.com/chakra-ui/chakra-ui/issues/2085#issuecomment-699964454

you add the class styling in the theme object then give those styles to a wrapping component

```js
export const ComponentStyles= {
	baseStyle: {
		// base styles
		'&.CLASS_OF_A_CHILDREN_OF_WRAPPED_COMPONENT': {
			// child styles
		},
	},
}
```

```jsx
import { Box, useStyleConfig } from '@chakra-ui/core'

export const Component= ()=> {
	const styles = useStyleConfig('ComponentStyle', {})

	return (
		<Box
			sx={styles}
		>
			<CustomComponent />
		</Box>
	)
}
```

**Comment by ruddi10** [comment]
@hazem3500 should it be direct child? as in my case its a nested child and it isn't working

**Comment by hazem3500** [comment]
It's the same as CSS rules, you can add any selector you want.

`&.CLASS_OF_A_CHILDREN_OF_WRAPPED_COMPONENT` will select all children whether nested or not inside the component.

if you want direct children you'd write it like `& > .CLASS_NAME`

try logging the `styles` object and see if it includes the styles you want, maybe there is a typo somewhere

**Comment by ruddi10** [comment]
`  const styles = useStyleConfig("DateTime");
<Box sx={styles}>
          <Datetime
            inputProps={{ className: "class" }}
            onChange={handleChange}
          />
        </Box>`

My custom style -
`export const DateTime = {
  // The styles all Cards have in common
  baseStyle: {
    "&.class": {
      fontFamily: "Monaco !important",
      bg: "black !important",
      outline: "lightText",
    },
  },
  // Two variants: rounded and smooth

  // The default variant value
};`

**Comment by ruddi10** [comment]
Can you please have a look and tell if there is some error here

**Comment by hazem3500** [comment]
are you adding `DateTime` to the main theme object?

**Comment by ruddi10** [comment]
`import { DateTime } from "./components/DateTime";
import { extendTheme } from "@chakra-ui/react";
// Global style overrides
import styles from "./global";
//Branding style ovverides
import branding from "./branding";

const overrides = {
  ...branding,
  styles,
  components: {
    DateTime,
  },
};
export default extendTheme(overrides);`

**Comment by ruddi10** [comment]
Yes here it is

**Comment by hazem3500** [comment]
did you log `styles` from `useStyleConfig("DateTime")`? 
does it have the applied styles?

**Comment by ruddi10** [comment]
On consoling I got a object having property "$.class" and inside that object there were fields including the styles

**Comment by hazem3500** [comment]
Can you provide a reproduction repo?

**Comment by ruddi10** [comment]
![Screenshot from 2021-06-15 11-55-21](https://user-images.githubusercontent.com/56596436/122003506-d11a8580-cdd0-11eb-89ec-222b6fdbc5c1.png)

**Comment by ruddi10** [comment]
Sure But you will have to edit some code as its making request to a mock API setup in my local environment will it be fine?

**Comment by ruddi10** [comment]
I can give you the mock api json file if you use mockoon you can simply import that in it

**Comment by hazem3500** [comment]
You can create another repo with the same package versions with only the `DateTime` component

**Comment by ruddi10** [comment]
https://github.com/ruddi10/dashboard.git

**Comment by ruddi10** [comment]
this is the time-querier branch is having the code

**Comment by ruddi10** [comment]
just clone this and run yarn install then you are good to go

**Comment by hazem3500** [comment]
Did you add the `DateTime` component?

**Comment by ruddi10** [comment]
Yes checkout the  TimeQuerier directory, Actually not only on datetime but the styles are not applied even if I am giving the class name to a simple child component

**Comment by hazem3500** [comment]
Couldn't find a directory with the name `TimeQuerier`, can you add it and also try adding the repo to codesandbox?

**Comment by ruddi10** [comment]
Hey inside components directory there is a timequerier directory

**Comment by ruddi10** [comment]
Make sure you have pulled the branch named time-querier

**Comment by ruddi10** [comment]
Hey its working now I replaced $.class with .class

**Comment by hazem3500** [comment]
You mean you've changed `&.class` to `.class`?

**Comment by ruddi10** [comment]
Yes

**Comment by ruddi10** [comment]
Btw @hazem3500 can you also tell me how to customize the default select component I want to change the bg color of it but unable to do so by ovveriding basestyles or even adding variants

**Comment by hazem3500** [comment]
You can checkout Chakra's default theme here https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/select.ts
