### ISSUE TITLE
Pressing `command + P` changes the color mode from light to dark.

### ISSUE THREAD

**Issue by snesjhon** [chakra-ui/chakra-ui#2088]
# Bug report

## Describe the bug

When I press `command + P` the color mode switches from light to dark. I found this while working on a Chakra v1 project and thought it was my code, but I see it happening on the next.docs site as well, thus might be something else.

It looks like it only happens from light to dark. Not vice-versa. 

## To reproduce

1. Go to https://next.chakra-ui.com/
2. Assure you're in color light mode
3. Press (on Mac) `command + P` for the print panel to occur

## Minimal reproduction
See above.

## Expected behavior
The color mode should respect the color mode.

## Screenshots

https://www.loom.com/share/5324cdfe88154db68eef39dbae633bab

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of @chakra-ui/core: 1.0.0-rc.3
- Version of Node.js: v12.14.0

**Comment by with-heart** [comment]
I'm not experiencing this locally. Does it still happen if you're in incognito mode?

**Comment by paulbalogh** [comment]
I also tried it in Safari & Edge (on Mac), could not reproduce it.

**Comment by pedro-lb** [comment]
It's happening on `1.0.0-rc.3`, locally and in production.

**Comment by ljosberinn** [comment]
Can confirm, both on the docs as well as my project (in prod):
- light changes to dark
- dark just flickers shortly

Doesn't happen to me in dev in `1.0.0-rc.4` though, could you test there?

**Comment by with-heart** [comment]
Do yall not get the print dialog?

**Comment by ljosberinn** [comment]
Yes, but it flickers during that, thats the funny part, here's a video: https://drive.google.com/file/d/1GpTfSGL5Bx5V6uAk2BnBrL2T4O6Zz7v0/preview

**Comment by with-heart** [comment]
What happens in incognito? Also what Chrome version? `85.0.4183.102` here and I can't get this to happen anywhere.

**Comment by ljosberinn** [comment]
` 85.0.4183.12` so even a bit newer. Same issue in Incognito as well as Guest mode.

**Comment by snesjhon** [comment]
Same thing happens in incognito. I'm in chrome version: `85.0.4183.121`.

https://www.loom.com/share/b3de0acdfb4644258cf63e12406e3683

**Comment by dodas** [comment]
Does not occur to me .

OS: Mac OS 10.14.6

Tried on:
Chrome 85.0.4183.121
Brave 1.14.84, based on Chromium: 85.0.4183.121

**Comment by ljosberinn** [comment]
Since this, for whatever reason, doesn't happen anymore for me I guess it resolved itself and consider it a bug in Chrome 🤷‍♂️
