### ISSUE TITLE
Efficient use of InputAddons with NumberInput

### ISSUE THREAD

**Issue by waptik** [chakra-ui/chakra-ui#2090]
# Bug report

## Describe the bug
I was looking for the best way to use both InputAddons and NumberInput

1- When using `InputLeftAddon` for example along with `NumberInput` inside `FormGroup`, the width is reduced and in order to get the full width, you'd have to set `w="full"` on `NumberInput` as mentioned in https://discord.com/channels/660863154703695893/660865137137156146/759131141230821416. Also Currently, there's no way to avoid wrapping InputLeftAddon and NumberInput inside FormGroup without the input field being reduced or getting this error:
```js
useStyles: `styles` is undefined. Seems you forgot to wrap the components in `<StylesProvider />` 
```
## To reproduce

1. Go to https://codesandbox.io/s/chakra-testing-number-input-y5ypd?file=/src/InputFields.tsx
2. Comment L71 & 86

## Expected behavior
1- When using InputLeftAddon and NumberInput inside FormGroup, the width of the input field should be full by default without the need of setting `w="full"` again.

## System information

- OS: Windows
- Browser (if applies): Brave
- Version of @chakra-ui/core: 1.0.0-rc.3
- Version of Node.js: 12.5.0

**Comment by Samic8** [comment]
I was wondering why the storybook stories don't have the same width problem. It seems that they are wrapped in a "Stack" component which uses flexbox to stretch them out.
