### ISSUE TITLE
[AlertDialog] not using forwardRef

### ISSUE THREAD

**Issue by UcheSylvester** [chakra-ui/chakra-ui#2092]
# Bug report

## Describe the bug

I don't know whether it is by design or not, but I think the `AlertDialog` component should forward `ref` using `forwardRef`.
On passing ref to the AlertDialog component, I get this error:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `CustomAlertDialog`.
    in AlertDialog (at CustomAlertDialog.js:18)
    in CustomAlertDialog (at App.js:17)
```

## Minimal reproduction

- Minimal reproduction can be found [here on CodeSandbox](https://codesandbox.io/s/chakra-custom-alert-dialog-f1pn8)

## Screenshots

![Screen Shot 2020-09-26 at 1 56 16 PM](https://user-images.githubusercontent.com/38369717/94341324-502c1b80-0000-11eb-993f-3dd104798609.png)

## Expected behavior

The `AlertDialog` component should forward ref using `forwardRef`

## System information

- OS: [macOS]
- Browser: [Chrome, Firefox]
- Version of @chakra-ui/core: [^0.8.0, 1.0.0-rc-3]

**Comment by ljosberinn** [comment]
Hm, I'm curious of the use case. `AlertDialog` is just `Modal`, and `Modal` is actually a `Portal`. I believe it was deliberately chosen not to allow allow a `ref` here.

That said, I'm generally not opposed to it.

**Comment by segunadebayo** [comment]
Hey @UcheSylvester,

The AlertDialog is purely composed of `Modal`, and Modal itself doesn't render any DOM nodes so forwarding ref doesn't add any value.

If you need to forward ref, I'd suggest you forward that ref to the content or overlay depending on your needs.

**Comment by UcheSylvester** [comment]
Hello @segunadebayo, @ljosberinn 

Thanks so much for the prompt responses and suggestions. I was trying to block scroll on the body when modal mounts using [Body Scroll Lock](https://www.npmjs.com/package/body-scroll-lock) as **blockScrollOnMount** wasn't working as expected (at least on the version 0.8.0 that I'm working with). 

I tried your suggestion on codesandbox and it worked, I will implement it on the project shortly

Thanks again
