### ISSUE TITLE
Adding a Picture component

### ISSUE THREAD

**Issue by subhendukundu** [chakra-ui/chakra-ui#2094]
# Feature request

## Is your feature request related to a problem? Please describe.

It will be helpful to add a Picture component that will have the ability to load different images based on screen size.

## Describe the solution you'd like
```
<picture>
    <source srcset="/media/cc0-images/surfer-240-200.jpg"
            media="(min-width: 800px)">
    <source srcset="/media/cc0-images/surfer-240-200.jpg"
            media="(min-width: 1400px)">
    <img src="/media/cc0-images/painted-hand-298-332.jpg" alt="" />
</picture>
```
## Describe alternatives you've considered

The images are great. And to achieve this you can always use `chakra.picture` but I feel making it a part of Chakra which will have the fallbackSrc as well and the rest of the props too.

**Comment by Psvensso** [comment]
It's not a bad idea but do you really need a pre-made component for that? 
Have you looked at [packages/media-query](https://github.com/chakra-ui/chakra-ui/tree/develop/packages/media-query)?

**Comment by subhendukundu** [comment]
So you right, you can make it work. But this is we are making it work. Like we are trying to make a `div` work like `ul`.
When we already have a `Picture` which systematically correct and does the exact same thing without any code, I feel that's a better way to do.
What are your thoughts on that?

**Comment by segunadebayo** [comment]
Hi @subhendukundu,

Sorry, we won't be adding this component to the core library. Please feel free to implement it on your end and share with the community.

Thank you.
