### ISSUE TITLE
rc.4 crash when useSystemColorMode is true on iOS 13

### ISSUE THREAD

**Issue by Sendouc** [chakra-ui/chakra-ui#2097]
# Bug report

## Describe the bug

When `useSystemColorMode` has been set `true` there is a crash on iOS 13. With iOS 14 it works.

## To reproduce

1. Use Chakra UI with config of `useSystemColorMode` is true.
2. Navigate to the site with an iOS 13 device.

## Minimal reproduction

https://codesandbox.io/s/white-river-uqf19?file=/src/index.js

## Screenshots

![image](https://user-images.githubusercontent.com/38327916/94361808-c6dc1e00-00bf-11eb-9940-06f9c2c67e1f.png)

mediaQueryList.addEventListener is not a function. (In 'mediaQueryList.addEventListener("change", listener)', 'mediaQueryList.addEventListener' is undefined)

## System information

- OS: iOS 13.7
- Version of @chakra-ui/core: 1.0.0-rc.4

## Additional context

This seems to be a thing with every device on iOS 13 and not just this one.

**Comment by ljosberinn** [comment]
Thanks, guess I was too fast following TypeScript advice that `.add/.removeListener` are deprecated. I'll push a fix shortly.
