### ISSUE TITLE
Responsive font size with breakpoints aliases generates media queries in incorrect order

### ISSUE THREAD

**Issue by trompx** [chakra-ui/chakra-ui#2099]
# Bug report

## Describe the bug

If I use:
`<Heading fontSize={["30px", "45px", "60px", "90px", "180px"]}>`
The css generated is in the correct order:
```
@media screen and (min-width: 80em)
<style>
.css-1yf13mp {
    font-size: 180px;
}
@media screen and (min-width: 62em)
<style>
.css-1yf13mp {
    font-size: 90px;
}
@media screen and (min-width: 620px)
<style>
.css-1yf13mp {
    font-size: 60px;
}
@media screen and (min-width: 400px)
<style>
.css-1yf13mp {
    font-size: 45px;
}
```

If I use:
`<Heading fontSize={{ base: "30px", sm: "45px", md: "60px", lg: "90px", xl: "180px" }}>`
The css generated is in the wrong order thus the font size applied is not the right one.
```
@media screen and (min-width: 620px)
<style>
.css-yxyd02 {
    font-size: 60px;
}
@media screen and (min-width: 400px)
<style>
.css-yxyd02 {
    font-size: 45px;
}
@media screen and (min-width: 80em)
<style>
.css-yxyd02 {
    font-size: 180px;
}
@media screen and (min-width: 62em)
<style>
.css-yxyd02 {
    font-size: 90px;
}
```
In that case for instance on a desktop (1920px), it's the 620px breakpoint size which is applied.

## Expected behavior

I'd expect the generated media queries to be in the right order.

## System information

- OS: Linux
- Browser (if applies): Chrome (but not tested on other browsers)
- Version of @chakra-ui/core: 1.0.0-rc.3
- Version of Node.js: 12.15.0

**Comment by segunadebayo** [comment]
Hey @trompx,

This is most likely an issue with how you customized the theme breakpoints. Send over a Codesandbox repo of this issue with the exact breakpoints you're using currently, and we'll take a look.

Thanks

**Comment by trompx** [comment]
Hey @segunadebayo,

Thanks for looking at this. I used the setup you mentionned in another issue:
```
const breakpoints = ["400px", "620px", "62em", "80em"];

// aliases
breakpoints.sm = breakpoints[0];
breakpoints.md = breakpoints[1];
breakpoints.lg = breakpoints[2];
breakpoints.xl = breakpoints[3];
```

I'll try to setup a single page to see if this comes from other part of my setup.

**Comment by ljosberinn** [comment]
@trompx we have a new utility for this, although it (currently still) requires Node v10+ installed:
```js
import { createBreakpoints } from 'theme-tools';
```
Sadly we forgot to redeploy the docs with `rc.4` which we will do soon again. In the meantime, you can read up on it here: https://chakra-ui-mmeyu9c67.vercel.app/docs/migration#7-update-theme-breakpoints

**Comment by trompx** [comment]
Thanks @ljosberinn,
I just updated my dependencies to:
```
    "@chakra-ui/core": "^1.0.0-rc.4",
    "@chakra-ui/icons": "^1.0.0-rc.4",
    "@chakra-ui/theme-tools": "^1.0.0-next.3",
```
I tried like you suggested to `import { createBreakpoints } from '@chakra-ui/theme-tools';` but I get the following error: `Module '"../../node_modules/@chakra-ui/theme-tools/dist/types"' has no exported member 'createBreakpoints'.`

**Comment by ljosberinn** [comment]
please update theme tools to the correct version, all packages of chakra should be on the same release, else you run into errors like this (or worse) :)

**Comment by trompx** [comment]
My bad I did a simple `yarn add @chakra-ui/theme-tools`.
All is working perfectly now, thanks!
There is just a small typo in the docs: `import { createBreakpoints } from "chakra-ui/theme-tools"` is missing the **@** in front of `chakra-ui`.

**Comment by ljosberinn** [comment]
Neat, glad its resolved :)
Regarding the typo, thanks, yes, we have a PR for that which I should merge anyways.
