### ISSUE TITLE
Flex component doesn't add `display: 'flex'` to div (in rc.4)

### ISSUE THREAD

**Issue by sebqq** [chakra-ui/chakra-ui#2100]
Hello there.

I've noticed that somehow in chakra-ui v1.0.0 rc.4, `Flex` component doesn't add `display: 'flex'` property to `chakra.div` element. Maybe it could be related to [this commit](https://github.com/chakra-ui/chakra-ui/commit/1bfbe7861332887978096f15303e7dc62cdc7bba).

Enclosing images of same `Flex` component rendered using rc.3 and rc.4:

- RC.3:

<img width="856" alt="Screenshot 2020-09-27 at 14 19 40" src="https://user-images.githubusercontent.com/33039909/94364970-8c797d80-00cd-11eb-8190-aacfa49a51a4.png">

- RC.4

<img width="856" alt="Screenshot 2020-09-27 at 14 25 33" src="https://user-images.githubusercontent.com/33039909/94365010-c9de0b00-00cd-11eb-8a33-f841c983216a.png">

**Comment by segunadebayo** [comment]
Thanks for letting us know @sebqq.

I've pushed a fix for this.

**Comment by sebqq** [comment]
Hello @segunadebayo and thank you for your quick response! I just wanted to ask you whether this fix is included in rc.5 release or not, because it seems to be not working properly in rc5 too. Thanks!

**Comment by ljosberinn** [comment]
Can you please provide a codesandbox? The docs use `Flex` in many places and it's always applied. I see the same in my project too, it wasn't broken in `rc.4` for either neither.

![image](https://user-images.githubusercontent.com/29307652/94442320-1ac03300-01a4-11eb-8917-a7309cc79d8d.png)

**Comment by sebqq** [comment]
@ljosberinn You're right and I'm so sorry. Actually, after revising code more closely I've found that I added `_css` property to my `Flex` component. Somehow, this managed to get rid of `display: 'flex'` attribute.

The problem is fixed after changing `__css` property to `sx`.

**Comment by ljosberinn** [comment]
Glad its resolved :) I believe `___css` is exposed because there can be (rare) use cases, but its technically an internal API. Use `sx` to merge with existing, predefined styles.

**Comment by sebqq** [comment]
Thanks for hint!
