### ISSUE TITLE
Compose issues with Menu, MenuButton, Select and Icon

### ISSUE THREAD

**Issue by ntt2k** [chakra-ui/chakra-ui#2102]
# Bug report

## Describe the bug

Compose issues with Menu, MenuButton, Select and Icon

## To reproduce

Is there a way to create a component like this using Chakra UI?: https://tailwindui.com/components/application-ui/forms/select-menus

![Screen Shot 2020-09-27 at 10 01 23 AM](https://user-images.githubusercontent.com/4227421/94368263-b79da600-00a8-11eb-8dad-a4cdb0af9c61.png)

I try to use composition between components: **Menu, MenuButton, Select and Icon**
But the **MenuButton** text as **Select** not showing up. Plus the **icon (ArrowUpDownIcon)** not get overwrite as expected?!

![Screen Shot 2020-09-27 at 10 07 23 AM](https://user-images.githubusercontent.com/4227421/94368391-5e824200-00a9-11eb-92c6-cef583ce4904.png)

## Minimal reproduction

Code: https://next.chakra-ui.com/docs/overlay/menu

```
<Menu>
  <MenuButton as={Select} rightIcon={<ArrowUpDownIcon />}>
    Your Cats
  </MenuButton>
  <MenuList>
    <MenuItem minH="48px">
      <Image
        boxSize="2rem"
        borderRadius="full"
        src="https://placekitten.com/100/100"
        alt="Fluffybuns the destroyer"
        mr="12px"
      />
      <span>Fluffybuns the Destroyer</span>
    </MenuItem>
    <MenuItem minH="40px">
      <Image
        boxSize="2rem"
        borderRadius="full"
        src="https://placekitten.com/120/120"
        alt="Simon the pensive"
        mr="12px"
      />
      <span>Simon the pensive</span>
    </MenuItem>
  </MenuList>
</Menu>
``` 

## Expected behavior

https://tailwindui.com/components/application-ui/forms/select-menus

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of @chakra-ui/core: v1-next

**Comment by segunadebayo** [comment]
Hey @ntt2k,

At the moment, it's not possible to compose these components to create that custom select.

We're looking to add a custom select component after the launch of v1, but it's not a priority for us at the moment

Permit me to close this for now.
