### ISSUE TITLE
Bug in props of the Accordion component

### ISSUE THREAD

**Issue by ashwinKumar0505** [chakra-ui/chakra-ui#2103]
## Description of the bug:

The Accordion component does not seem to be accepting the defaultIsOpen and isOpen props.

## Screenshots of the error:

![Screenshot 2020-09-27 at 10 52 36 PM](https://user-images.githubusercontent.com/53852911/94371488-8c50a080-0114-11eb-946c-f11c68f25e37.png)

## Codesandbox link:

https://codesandbox.io/s/flamboyant-turing-ebc70?file=/src/AccordionExample.js

**Comment by with-heart** [comment]
Hi @ashwinKumar0505! Thanks for raising this. The indexes are controlled entirely by `Accordion`, using either `index` or `defaultIndex`. The `isOpen` and `defaultIsOpen` props have been removed from `AccordionItem`. Use it like this: https://codesandbox.io/s/confident-platform-57qiw?file=/src/AccordionExample.js

I opened #2104 to remove the reference to `defaultIsOpen` for `AccordionItem` in the docs.
