### ISSUE TITLE
Add Avatar responsive size

### ISSUE THREAD

**Issue by omribenari** [chakra-ui/chakra-ui#2105]
# Feature request

## Is your feature request related to a problem? Please describe.
Avatar component don't support responsive size.
size prop is a string.

## Describe the solution you'd like

something like this:
```
<Avatar name={name} src={photoUrl} size={["sm", "md", "lg", "xl"]} /> 
```
## Describe alternatives you've considered
i also tried 
```
<Avatar name={name} src={photoUrl} size={{ base: "sm", md: "md" }} /> 
```

**Comment by andrei-scripcaru** [comment]
I second that.

**Comment by segunadebayo** [comment]
Thanks for chiming in @andrei-scripcaru. 

This is also a duplicate of #1028.

**Comment by JavaJamie** [comment]
Thanks @andrei-scripcaru!

**Comment by marloscarmo** [comment]
You can use this simple way!

```
import { useBreakpointValue } from '@chakra-ui/media-query'

<Avatar
  size={useBreakpointValue({
    base: 'sm',
    md: 'md',
  })}
  src="/images/avatar.png"
></Avatar>
```

**Comment by edwinvelez** [comment]
If you are using [Next.js](https://nextjs.org/) I came up a solution. Hopefully, it will for you too. See [nextjs-avatar-component-with-chakra-ui](https://github.com/edwinvelez/nextjs-avatar-component-with-chakra-ui) for a working example.
