### ISSUE TITLE
1.0.0 - Safari - useBreakpointValue 'mediaQuery.addEventListener' is undefined

### ISSUE THREAD

**Issue by sebqq** [chakra-ui/chakra-ui#2117]
Hello there,

on latest release there is problem with using `useBreakpointValue` in Safari browser. 

Enclosing error message and reproducible demo.

```
TypeError
mediaQuery.addEventListener is not a function. (In 'mediaQuery.addEventListener("change", handleChange)', 'mediaQuery.addEventListener' is undefined)
```

[codesandbox demo](https://codesandbox.io/s/charming-resonance-cz60j?file=/src/index.js)

Thanks!

**Comment by ljosberinn** [comment]
already fixed in #2097 - this is included in `rc.5`, so this can't be happening anymore, can you please confirm you didn't accidentally use `rc.4`?

Commit: https://github.com/chakra-ui/chakra-ui/commit/fd940a455cc31e4606b51a8ba55ab3d53617f4f0#diff-cc733e88e3d2f0af7534fab28f4bb000

Live in the docs: 
![image](https://user-images.githubusercontent.com/29307652/94568048-59212500-026c-11eb-9431-f27ec5c2fe51.png)

**Comment by ljosberinn** [comment]
On a sidenote, in your sandbox, the `@emotion` dependencies are not needed anymore and you can omit `resetCSS` on `ChakraProvider` as it's true by default :)

**Comment by sebqq** [comment]
@ljosberinn Thanks, I'm aware of `@emotion` dependency thing (I just started codesandbox demo from a template of older version of chakra-ui).

> already fixed in #2097 - this is included in rc.5, so this can't be happening anymore, can you please confirm you didn't accidentally use rc.4?

Thats weird. I'm pretty sure that my project runs rc.5 and sandbox seems to be running rc.5 too.

**Comment by ljosberinn** [comment]
Nevermind, I totally ignored you mentioned `useBreakpointValue` 🤦‍♂️ I forgot reverting it there, sorry. Will change that later today and it will be fixed in the next release.

**Comment by ljosberinn** [comment]
If anyone wants to file a PR for this:

simply change `addEventListener('change', handleChange)` here to `addListener(handleChange)`

https://github.com/chakra-ui/chakra-ui/blob/7c20482da49cafee4f8ead696868b36d1763afd2/packages/media-query/src/use-breakpoint.ts#L72

as well as below with `removeAddEventListener` in the same manner.

**Comment by sebqq** [comment]
I've tried: #2118

**Comment by ljosberinn** [comment]
Thanks, will take care of it later this evening :)

**Comment by PaulPCIO** [comment]
This is still an issue, I tested this from your site next.chakra-ui.com that should be running on .rc5 right?

![image](https://user-images.githubusercontent.com/39598117/96717504-db51c480-13a6-11eb-989b-308b7975e232.png)

**Comment by ljosberinn** [comment]
The docs don't get redeployed on changes to `develop`, so it's still `.rc5` where it's broken. It should work [here](https://chakra-ui-r4i1549me.vercel.app/docs/hooks/use-breakpoint-value), could you kindly confirm that? :)

**Comment by PaulPCIO** [comment]
yea that works 👍 so which version is the fixed one? I thought rc5 was fixed? my client-facing website is currently down because of this :/ I updated to .rc5 last night in the hopes of having this fixed.

**Comment by ljosberinn** [comment]
No, I'm afraid `.rc5` is the latest as the fixes aren't released yet and I don't know by heart whether it worked in `.rc4`, afraid you'll have to try, I don't have an iPhone. fwiw, a sandbox would suffice to test probably

**Comment by sebqq** [comment]
@PaulPCIO Hello, [there](https://github.com/chakra-ui/chakra-ui/pull/2135) is Pull Request, which fixes this problem. You can use [patch-package](https://www.npmjs.com/package/patch-package) for temporary fix. This package will apply changes to your node-modules whenever you re-install your node_modules so until there is a new release of chakra-ui you can use patch-package to overcome this issue.

**Comment by PaulPCIO** [comment]
@sebqq yea thanks I was just about to do that 😉  thanks. I often turn to patch-package ❤️

**Comment by tobiasjeckel** [comment]
Hi, am using @chakra-ui/react `v1.6.7` . Is the `.rc5` included in this version ? If not, how would I go about fixing this issue in my app which uses @chakra-ui/react ? Do I need to replace @chakra-ui/react with @chakra-ui/core ? 
Thanks

**Comment by ljosberinn** [comment]
hi @tobiasjeckel - could you share the actual error? the issue has been resolved nearly a year ago and the current implementation of useBreakpointValue [does not use .addEventListener](https://github.com/chakra-ui/chakra-ui/blob/35d0d94b3a5fb6b1b3bf66ae2222f19bb16d9f9c/packages/media-query/src/use-breakpoint.ts#L77)

**Comment by tobiasjeckel** [comment]
> hi @tobiasjeckel - could you share the actual error? the issue has been resolved nearly a year ago and the current implementation of useBreakpointValue [does not use .addEventListener](https://github.com/chakra-ui/chakra-ui/blob/35d0d94b3a5fb6b1b3bf66ae2222f19bb16d9f9c/packages/media-query/src/use-breakpoint.ts#L77)

Hi, thanks for the quick reply. It seems something else is causing my ChakraUI project to crash on a safari IOS Browser. Because it is a corporate project I can't share more information. I therefore deleted my original comment. You can delete this one as well.
Thanks, 
Tobias
