### ISSUE TITLE
StackDivider is not respecting responsive borderColor in rc.5

### ISSUE THREAD

**Issue by jivinivan** [chakra-ui/chakra-ui#2119]
# Bug report

## Describe the bug

`StackDivider` is not respecting responsive `borderColor` in rc.5.

See here: https://codesandbox.io/s/chakra-ui-rc5-responsive-bordercolor-gfylf?file=/src/App.js

`base` style works as expected however `md` does not get applied properly.

Confirmed in discord https://discord.com/channels/660863154703695893/758645914868514827/760504179084230716

## Minimal reproduction

https://codesandbox.io/s/chakra-ui-rc5-responsive-bordercolor-gfylf?file=/src/App.js

## Expected behavior

Responsive styles should be applied normally.

**Comment by jivinivan** [comment]
In the meantime as a workaround @ljosberinn has pointed out that `useBreakpointValue` can be used https://codesandbox.io/s/chakra-ui-rc5-responsive-bordercolor-forked-7pup9?file=/src/App.js

**Comment by segunadebayo** [comment]
Hi @jivinivan,

I just pushed a fix for this. We'll release an update shortly.
