### ISSUE TITLE
[Checkbox] May cause unwanted horizontal overflow

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#212]
As written in the title, the `Checkbox` component may cause an undesired overflow when wrapped inside a horizontal scroll container, e.g. inside a slide of a [`Carousel`](https://github.com/chakra-ui/chakra-ui/issues/200#issuecomment-545702115).

The fix is as simple as adding a `position="relative"` wrapper for `VisuallyHidden` to compensate for absolute positioning.

**Comment by kripod** [comment]
After further investigation, I came across the realization that negative margin, especially right and bottom ones may cause the undesired behavior.

I would suggest implementing [an alternative approach](https://adrianroselli.com/2019/11/aria-label-does-not-translate.html#Developers) for hiding elements visually.

**Comment by kripod** [comment]
This is not stale, as it still causes trouble.

**Comment by jaredpalmer** [comment]
this bit me hard the other day. i think position relative needs to be added by default

**Comment by segunadebayo** [comment]
@kripod @jaredpalmer  I'm currently finetuning the Checkbox component in the TS branch. 

I'm not sure I understand this issue very well. Do you mind showing me a pseudo-code of this or some code samples? It'll help a lot.

Thanks.

**Comment by kripod** [comment]
@segunadebayo I hope you could successfully trace the issue through the code examples in [kripod/exigo](https://github.com/kripod/exigo), as we have discussed in detail.

**Comment by SimonHoiberg** [comment]
The same applies to Switch and a lot of other components.
We spent hours debugging this. An element `chakra-switch__input` is pushed off the screen, and it's causing some very weird and unintended UI behavior.

The fix was super simple:
```JSX
<Box position="relative"> // <- Add this wrapper
  <Switch />
</Box>
```

But man! You really gotta know what you're looking for.
I would consider this a bug. I suggest reopening this issue.
