### ISSUE TITLE
[Toast] Close all toasts doesn't work

### ISSUE THREAD

**Issue by la55u** [chakra-ui/chakra-ui#2121]
## Describe the bug

Close all toasts button doesn't work on the docs page, it only removes one (the most recent) toast from the bottom.

## To reproduce

Try it here:
https://next.chakra-ui.com/docs/feedback/toast#closing-toasts

## Expected behavior

All toasts shuld be removed immediately.

## System information

- Version of @chakra-ui/core: 1.0.0-rc.x(?)

**Comment by ljosberinn** [comment]
Thanks, can confirm this is a bug and found a fix :)

**Comment by ljosberinn** [comment]
https://chakra-ui-1pr7qefki.vercel.app/docs/feedback/toast#closing-toasts works after fixing it

**Comment by EllaSharakanski** [comment]
Also, `toast.close(id)` doesn't work if performed one-by-one for an array of toasts all in the same position. The fix solves both issues. When is it supposed to be released? Thanks

**Comment by ljosberinn** [comment]
Automatically with the next release. Migrating to framer-motion is the last missing piece for another release as far as I'm aware, so probably next week.

**Comment by EllaSharakanski** [comment]
Thank you! Sorry for asking here, not sure where I can ask, is there a way for me to see this information? Couldn't find the place that specifies the missing pieces for a release

**Comment by ljosberinn** [comment]
Indirectly only I'm afraid. I thought we mentioned it in an issue but I was mistaken; we mentioned it on discord and there is this twitter poll: https://twitter.com/thesegunadebayo/status/1307939057352278016

**Comment by EllaSharakanski** [comment]
@ljosberinn Any update on when this is going to be released? Thank you 🙏

**Comment by ljosberinn** [comment]
maybe @segunadebayo can shed some light :)

**Comment by juanlatorre** [comment]
Any update on this? Toast duration and close buttons aren't working either

**Comment by ljosberinn** [comment]
It's been fixed technically, but I made a silly mistake in the closing logic - which also has been fixed, we're planning to release another rc soon (today or tomorrow depending on progress). See #2328
