### ISSUE TITLE
No overload matches this call for `variantColor` in Button Typescript

### ISSUE THREAD

**Issue by nimit95** [chakra-ui/chakra-ui#2125]
# Bug report

## To reproduce

1. Install chakra-ui using `yarn add @chakra-ui/core @emotion/core @emotion/styled emotion-theming  @chakra-ui/core@next
`
2. Go to node_modules/@chakra-ui/button/dist/types/button.d.ts
3. Scroll down to Button props
4. Buton props don't have `variantColor`

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies): [e.g. Chrome, Safari]
- Version of @chakra-ui/core: @chakra-ui/button@1.0.0-rc.5
- Version of Node.js: 10.15.3

**Comment by ljosberinn** [comment]
Hi @nimit95 - you seem to be installing `@chakra-ui/core` and then `@chakra-ui/core@next` (as well as unnecessary dependencies such as `@emotion/styled`, `/core` and `-theming`. You only need to install `@chakra-ui/core@next`.

Because you install 2 different versions, your node_modules will be in a weird state in between. 

The docs mention this [here](https://next.chakra-ui.com/docs/getting-started#installation) as well as in the [migration steps](https://next.chakra-ui.com/docs/migration#1-update-your-dependencies).

**Comment by nimit95** [comment]
Not sure, I removed node_modules, my dependencies looks as below
`"dependencies": {
    "@chakra-ui/core": "next",
    "formik": "^2.1.5",
    "next": "latest",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  }`

Then did yarn install,
Still getting the same error. Any ideas how to fix if it from my end?

**Comment by ljosberinn** [comment]
Did you remove your lockfile too? If you only remove node_modules you remove only the payload. but what defines it is written in the lockfile.

**Comment by nimit95** [comment]
Nope still facing the issue, does installing `"@chakra-ui/core": "next"` also installs `"@chakra-ui/button"` etc. Because I see them while I do `yarn list`

**Comment by ljosberinn** [comment]
Yes, core imports almost all chakra packages and re-exports them. Now that we've sorted the dependencies - where do you see `variantColor` being a prop on Button?

**Comment by nimit95** [comment]
Here on the button documentation `https://chakra-ui.com/button`

**Comment by ljosberinn** [comment]
I'm afraid thats the v0 documentation. You're installing `next`, which has its documentation over [here](https://next.chakra-ui.com/).

Now I understand why used both installs initially.. [here](https://next.chakra-ui.com/docs/migration#4-rename-variantcolor-to-colorscheme) are the docs on migrating usage of `variantColor` to `colorScheme`.

Sorry for the confusion!

**Comment by nimit95** [comment]
Oh got it. `https://chakra-ui.com/` doesn't have anything to mention that it is v0 or some sort of warning 😅 
Also, Google still indexes `chakra-ui.com` as a top result for `chakra documentation`

**Comment by ljosberinn** [comment]
It's not in the old docs because as you can see we're replacing them entirely. Regardless, the new docs are mentioned right here: https://github.com/chakra-ui/chakra-ui#looking-for-the-documentation- :)
