### ISSUE TITLE
Object breakpoints are not working anymore in 1.0.0-rc.5

### ISSUE THREAD

**Issue by pedro-lb** [chakra-ui/chakra-ui#2129]
# Bug report

## Describe the bug

Responsive breakpoints with objects (e.g. `{ sm: 1, md: 2 }`)  are not working anymore after updating to `1.0.0-rc.5`. Responsive breakpoints with arrays (e.g. `[1, null, 2]`)  are still working fine.

Here's an example:

![image](https://user-images.githubusercontent.com/22061051/94705373-59c2c580-0317-11eb-8a8b-4c91e7143192.png)

## To reproduce

Compare responsive breakpoints with objects and arrays on `1.0.0-rc.5`.

## Minimal reproduction

CodeSandbox link: https://codesandbox.io/s/tender-glitter-s95f4?file=/src/App.tsx

Based on this example: https://next.chakra-ui.com/docs/layout/simple-grid

## Expected behavior

Should work correctly with objects

## Screenshots

Available above

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of @chakra-ui/core: 1.0.0-rc.5
- Version of Node.js: 12

**Comment by ljosberinn** [comment]
Codesandbox has issues so I can't open it right now sadly but there was a change to how breakpoints work to allow custom breakpoints (read more [here](https://next.chakra-ui.com/docs/migration#7-update-theme-breakpoints)).

`base` is now always the first breakpoint, so `[1, 2]` would equal to `{ base: 1, xs: 2 }`.

**Comment by pedro-lb** [comment]
Hey there @ljosberinn !

By updating `{ sm: 1, md: 2 }`  to `{ base: 1, sm: 2 }` it's working correctly.

Thanks!

**Comment by ljosberinn** [comment]
That's odd, yeah, since there were [quite a few commits here](https://github.com/chakra-ui/chakra-ui/pull/2027). Sorry for the inconvenience!

**Comment by callumflack** [comment]
Unsure this issue should be closed? It's not actually fixed?

**Comment by ljosberinn** [comment]
There never was an issue with it @callumflack, it just somehow was omitted from the autogenerated changelog.

**Comment by callumflack** [comment]
Cheers @ljosberinn so don't use `base` anymore, use `sm`?

**Comment by ljosberinn** [comment]
For the object notation: `base` is "between 0 and sm breakpoint", `sm` is "between sm and md breakpoint", etc. 

But for the array notation, its always dependant on the amount of breakpoints added, and as such, the first is always `base`.
