### ISSUE TITLE
Popover focus restoration

### ISSUE THREAD

**Issue by rumkin** [chakra-ui/chakra-ui#213]
## Problem

After popover loose focus, the popover target element became focused even if another element on the page receive focus. If the page was scrolled, it scrolls back to popover target.

## Steps to reproduce

1. Open https://chakra-ui.com/popover
2. Press "Trigger".
3. Scroll one or two screens to the bottom.
4. Select focusable element.

## Current behavior

Popover target receive focus. Page scrolls to it.

## Expected behavior

New element receive focus.

## Solution

If popover is closed using popover controls, popover target should receive focus.
If popover is closed due to another element received focus, that element should remain focused.

**Comment by segunadebayo** [comment]
Hi @rumkin,

To prevent this from happening, you can use the `returnFocusOnClose` prop. If you set it to `false`, you'll get the expected behavior.

Popover can be in controlled mode, this means the element/event that opens/closes the Popover might not be within popover controls. This makes it a bit challenging to implement your solution.

Try using this prop: `<Popover returnFocusOnClose={false}>` and see if you get your desired behavior.

Thanks.

**Comment by rumkin** [comment]
But won't it brake a11y? As I thought current behavior is made for screen readers and other keyboard-only/supportive technologies. I would like to get both behaviors out of the box.

**Comment by segunadebayo** [comment]
For a11y, it's important that focus returns to the element that triggered the Popover (if that element is still visible on the page).

I'm afraid you might not be able to get both behaviors out of the box.

The behavior you explained is mostly for mouse inputs. For keyboard users, you'll have to focus one element at a time using `tab`, and you'll have to close the Popover before moving to other elements. I believe the same should apply for mouse experience as well, you can leverage the `returnFocusOnClose` prop for this custom behavior.

Your solution sounds interesting but it might make the a11y inconsistent across mouse and keyboard. If you have genuine reasons to move focus to another element while the Popover is open, then you'll have to control the accessibility of that behavior.

**Comment by segunadebayo** [comment]
I'll look into this and see if there's a way to return focus without scrolling the page

**Comment by rumkin** [comment]
Maybe my solution isn't the correct or one that should be implemented. But the current one seems confusing for me. I wish it be more like default behavior. I've created a [fiddle](https://jsfiddle.net/rumkin/bw7ty62p/) for select's element popover behavior test. Browsers has different behavior on this issue:

1. Chrome and Safari prevent from scrolling.
2. Firefox hides popover on scroll.

If you'd prefer to preserve the current behavior, I think it would be proper to add smooth scrolling to prevent user confusion from loosing the context.

**Comment by segunadebayo** [comment]
Good suggestions @rumkin.

Supporting default browser behavior sounds good. Here are 3 possible solutions we could implement based on your ideas:

1. Prevent scroll jumping when the popover closes.
2. Prevent scrolling and allow users to disable this via a `blockScrollOnOpen` prop.
3. Hide popover when you scroll within the body.

I think option 1 will be implemented by Chakra. Do you think it's a good idea to include all 3 out of the box? @rumkin

**Comment by rumkin** [comment]
## Part I

I've researched a little bit and found one implementation that almost satisfy my requirements it's [Reakit's popover](https://reakit.io/docs/popover/), it behave exact like what I think it should to. 

I found another case: if you update the [Popup basic usage example](https://chakra-ui.com/popover#basic-usage) with the next code, you will receive incorrect behavior.
Steps to reproduce:
1. Put two focusable elements on the page: "Button A" and "Button B".
2. Make "Button A" a trigger for popup.
2. Click "Button A".
3. Click "Button B".

I expect the "Button B" to be focused, instead of that "Button A" receives focus. In the same time keyboard focus works in the correct way.

### Code

```jsx
<div>
  <Popover>
    <PopoverTrigger>
      <Button>Button A</Button>
    </PopoverTrigger>
    <PopoverContent zIndex={4}>
      <PopoverArrow />
      <PopoverCloseButton />
      <PopoverHeader>Confirmation!</PopoverHeader>
      <PopoverBody>
        Are you sure you want to have that milkshake?
      </PopoverBody>
    </PopoverContent>
  </Popover>
  <Button>Button B</Button>
</div>
```

## Part II

Actually I classified Popup as an overlay element, but it's not. Thus default behavior I referred to could be applied to Popover only partially. In the same time there is no web standard which would describe popups. So I suggest to classify popup what should help to determine its' corner cases. Here is my thoughts on this:

1. Popup should be classified like element in the next way:
  1. Tooltip: non-interactive, doesn't have focus, disappears on mouse out, locks nothing.
  2. Popup: interactive, doesn't isolate focus, disappears on blur or scroll out of screen, locks nothing.
  3. Overlay: interactive, isolate focus, don't disappears, locks the scroll.

This classification could be enhanced and should be used for building design system to make more intuitive UI.

## Part III

According to specified classification popup should be closed when it scrolled out of the screen. And to make it more obvious, it could smoothly loose opacity when it starts covering by the viewport edge, and to disappear when opacity becomes equal 0.

## Part IV

I think, that there is two different cases of focus loss:

1. focus restoration, when element disappears.
2. focus change, when certain element receives focus.

Focus restoration should always return focus to previously selected element, while focus change don't.

## Part V

Due do principle of less surprise, there should be some behavior prioritization.

* Keyboard focus should be indexes-driven and follow `tabindex` values.
* Mouse focus should be position-driven and follow mouse events.

## Conclusion

Due to all of this the most I can prioritize the solutions in this way:

1. Select new element as a new target on focus change/mouse click. And hide on scroll.
2. Prevent scrolling.
3. Smooth scroll back to the element.

What does your community think about it? Could you make a poll?

**Comment by segunadebayo** [comment]
Thanks for this detailed feedback @rumkin. I'm going to wait for more comments on this and then look into its implementation.

**Comment by diegohaz** [comment]
On Reakit we check if there's already a tabbable element with focus before moving focus back to the trigger button:
https://github.com/reakit/reakit/blob/11b7bfa6895818cc7de7bf04d4fca4447965081b/packages/reakit/src/Dialog/__utils/useFocusOnHide.ts#L18-L28

**Comment by segunadebayo** [comment]
That's a good idea. Thank you, @diegohaz.

I'll look through that implementation and see how the Popover can leverage that.
