### ISSUE TITLE
Bug in the step prop in Number Input

### ISSUE THREAD

**Issue by ashwinKumar0505** [chakra-ui/chakra-ui#2134]
Try setting the step prop of the number in string. The entire application gets hanged.

![Screenshot 2020-10-01 at 2 53 36 PM](https://user-images.githubusercontent.com/53852911/94792191-3cb0f400-03f6-11eb-98d4-0717764e8233.png)

**Comment by ljosberinn** [comment]
Only happens in the docs and is sadly out of our control due to the live reload feature used there. The prop should also be a number, not a string.

[Here's](https://codesandbox.io/s/suspicious-snow-fsd7z?file=/src/App.js) an example where its working in codesandbox.
