### ISSUE TITLE
[Docs] Document isLazy on Menu & Popover including example

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#2146]
# Bug report

The `Menu` component may receive `isLazy` to only render `MenuList` children when actually opened. Right now, this is undocumented but may be an important performance optimization.

Same goes for `Popover`.

Documentation should follow the [`Tab example`](https://next.chakra-ui.com/docs/components/tabs#lazily-mounting-tab-panels).

**Comment by Zaynex** [comment]
I'm not good at English, but I'm willing to help. Can I have a try ?

**Comment by ljosberinn** [comment]
sure 👍 it should be fairly copy paste
