### ISSUE TITLE
Editable default value not reactive

### ISSUE THREAD

**Issue by bumbus** [chakra-ui/chakra-ui#2148]
# Editable default value not reactive

## Describe the bug

It seems like after an `Editable` is rendered once with a `defaultValue`, the `value` and the `defaultValue` does not get updated anymore when the (rendered) data changed elsewhere.

## To reproduce

1. [ Go to Code sandbox](https://codesandbox.io/s/black-silence-pl7p1?file=/src/App.js)
2. Click on 'Change text elsewhere'
3. See that text `Initial text` changed to `CHANGED ELSEWHERE`, but not the preview of editable has changed.

## Expected behavior

The default value text should also display `CHANGED ELSEWHERE`.

**Comment by ljosberinn** [comment]
hi @bumbus could you please double check the sandbox link? appearst to be the default template

**Comment by bumbus** [comment]
Sorry, I have updated the link now

**Comment by ljosberinn** [comment]
This is intended, please use the `value` prop instead. It's the difference between `controlled` and `uncontrolled` components. https://reactjs.org/docs/forms.html#controlled-components
