### ISSUE TITLE
How to change color of tabs

### ISSUE THREAD

**Issue by juhaelee** [chakra-ui/chakra-ui#215]
Is there a way to change the color of the tabs that's not the default blue?

**Comment by segunadebayo** [comment]
Hi @juhaelee,

I assume you mean the color of the `Tab` when it's active. There are 2 ways (I'll add it to the docs)

1. Pass a `variantColor` prop to the `Tabs` component and set it to a key in `theme.colors`

```jsx
<Tabs variantColor="red">
    {/*... */}
</Tabs>
```

2. Pass `_selected` prop to any `Tab` component and use the style props.

```jsx
<Tabs>
  <TabList>
    <Tab>One</Tab>
    <Tab _selected={{bg: "red.100"}}>Two</Tab>
  </TabList>
  <TabPanels>
    {/*... */}
  </TabPanels>
</Tabs>
```

**Comment by juhaelee** [comment]
Thanks for the quick response @segunadebayo ! However, I get the following error when I try option 1:

```
Property 'variantColor' does not exist on type 'IntrinsicAttributes & ITabs & RefAttributes<any> & HTMLAttributes<any> & LayoutProps & ColorProps & SpaceProps<TLengthStyledSystem> & BordersProps & BackgroundProps<TLengthStyledSystem> & ... 14 more ... & { ...; }'.
```

**Comment by segunadebayo** [comment]
I must have skipped the type definition for that prop, I'll look into it soon.

If you can, I'll appreciate that as well.

**Comment by segunadebayo** [comment]
I've added the type definition for the `variantColor`. I'll release an update soon.

**Comment by donkey-donkey** [comment]
Thanks. is there a way to add the bg on slected to the Tab in the theme...?

**Comment by samkasman** [comment]
> Thanks. is there a way to change the bg on selected Tab in the theme...?

I'm wondering the same, can't seem to.

**Comment by malashevskyi** [comment]
> > Thanks. is there a way to change the bg on selected Tab in the theme...?
> 
> I'm wondering the same, can't seem to.

```javascript
const theme = extendTheme({
  components: {
    Tabs: {
      baseStyle: {
        tab: {
          _selected: {
            bg: 'red',
          }
        }
      }
    }
  }
})
```

**Comment by andrehadianto** [comment]
<img width="252" alt="image" src="https://user-images.githubusercontent.com/40631483/196873324-9caa19e1-26ac-46ab-8572-52cf362935a2.png">

I can't seem to align my tabs border when I tried to change the width to `1px` 🤔 

```
import { tabsAnatomy as parts } from "@chakra-ui/anatomy";
import { createMultiStyleConfigHelpers } from "@chakra-ui/styled-system";

const { defineMultiStyleConfig } = createMultiStyleConfigHelpers(parts.keys);

export const Tabs = defineMultiStyleConfig({
  variants: {
    line: {
      tab: {
        fontWeight: 500,
        color: "gray.400",
        _selected: {
          color: "gray.100",
          borderBottomWidth: "1px",
          borderBottomColor: "brand-s.500",
        },
      },
      tablist: {
        borderBottomWidth: "1px",
      },
    },
  },
});

```
