### ISSUE TITLE
[Avatar] does not allow loading prop for underlying img

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#2150]
# Bug report

already exists on `Image` and `Img`

![image](https://user-images.githubusercontent.com/29307652/94948318-698d0600-04df-11eb-9594-c3e7939ec73e.png)

## Expected behavior

`Avatar` supports `loading` and passes the prop onto the internally used `AvatarImage`.

Docs should contain a hint about it, too.

**Comment by Zaynex** [comment]
🔧
