### ISSUE TITLE
FormErrorMessage requiring a surrounding StylesProvider

### ISSUE THREAD

**Issue by romseguy** [chakra-ui/chakra-ui#2152]
When using `FormErrorMessage` without wrapping it in a `FormControl`.

Issue description https://github.com/chakra-ui/chakra-ui/issues/906#issuecomment-659972456

Was fixed for `FormLabel` here https://github.com/chakra-ui/chakra-ui/pull/1167

Thank you for doing it for `FormErrorMessage`

**Comment by segunadebayo** [comment]
Thanks for raising this concern, I think it's a valid point and I've gone ahead to breakout `FormErrorMessage` styles from `FormControl`.

We'll release an update shortly
