### ISSUE TITLE
Undefined StarIcon on AirbnbExample

### ISSUE THREAD

**Issue by hems** [chakra-ui/chakra-ui#2159]
# Bug report

I just tried copying the AirbnbExample from the Box documentation: https://chakra-ui.com/box and I got an error saying StarIcon is not defined.

## Expected behavior

The example should be updated to use the <Icon> component, i.e.

````js
              <Icon
                name="star"
                key={i}
                color={i < property.rating ? "teal.500" : "gray.300"}
              />
````

I would love to do a PR on the documentation repo but I did not find it, would anyone kindly point me out to the source code of the `Box` documentation page?

**Comment by ljosberinn** [comment]
Hi @hems - I'm afraid the v0 docs won't receive further updates as we are close to the release of v1: https://next.chakra-ui.com which I would heavily recommend for starting a new project today. Regardless - the v0 docs are in the v0 branch, hence you couldn't find them that easily. Basically archived.

**Comment by ljosberinn** [comment]
Sorry, I wasn't aware - turns out, the icons are all coming from `@chakra-ui/icons`! [Here](https://github.com/chakra-ui/chakra-ui/blob/develop/website/src/components/icons-list.tsx) are they grouped in the docs. It's also used in [the nextjs-typescript example](https://github.com/chakra-ui/chakra-ui/blob/develop/examples/nextjs-typescript/components/PropertySummary.tsx#L9).

**Comment by hems** [comment]
> Sorry, I wasn't aware - turns out, the icons are all coming from `@chakra-ui/icons`! [Here](https://github.com/chakra-ui/chakra-ui/blob/develop/website/src/components/icons-list.tsx) are they grouped in the docs. It's also used in [the nextjs-typescript example](https://github.com/chakra-ui/chakra-ui/blob/develop/examples/nextjs-typescript/components/PropertySummary.tsx#L9).

i see, so it actually exists on v1. good stuff.

I'm curious to know where is the source code for the documentation tough? as in: if I find a "typo" or any mistake on the documentation, where would I find the source code on github to submit a PR ?

**Comment by ljosberinn** [comment]
The entire `website` folder! It's funneled through MDX, so `/website/docs/`.
