### ISSUE TITLE
".500" added to variantColor

### ISSUE THREAD

**Issue by daniel-lovell** [chakra-ui/chakra-ui#216]
My code:
<img width="262" alt="Screen Shot 2019-10-29 at 9 45 54 PM" src="https://user-images.githubusercontent.com/10445825/67830203-0016a300-fa97-11e9-938f-606f25610c66.png">

Chrome:
![Screen Shot 2019-10-29 at 9 45 25 PM](https://user-images.githubusercontent.com/10445825/67830210-0442c080-fa97-11e9-8ae6-6307ed49c30c.png)

**Comment by hendrikniemann** [comment]
The button has not only one color but multiple based on its state (e.g. `:hover`). This is why `variantColor` expects you to supply a [color from the theme](https://chakra-ui.com/theme#colors) that defines different shades. You can also add your own colors in your theme by extending the theme.

**Comment by segunadebayo** [comment]
Hi @daniel-lovell, 

Just like @hendrikniemann has mentioned, the button's `variantColor` should be a color key in the theme object. We use it to determine the interaction colors or the button to save you time.

In the future, we'll consider supporting raw hex codes and find a smart way to generate interaction colors.

For now, you can only pass colors that have the 50-900 hues. Check https://chakra-ui.com/theme#colors. If you want a custom color, here what you can do:

1. Add your custom colors to the theme. Use a tool like https://smart-swatch.netlify.com to generate the different 50-900 hues.

```js
const customTheme = {
  ...theme,
  colors:{
    ...theme.colors,
    myColor: {
      50: "",
      ....,
      900: ""
    }
  }
```

Then you can do `variantColor="myColor"`.

2. Control the interactions yourself
```jsx
<Button bg="[hex]" _hover={{bg: "[hex]"}} _active={{bg: "[hex]"}}/>
```

**Comment by daniel-lovell** [comment]
Thanks! This helps a lot.
