### ISSUE TITLE
fonts theme property should influence components

### ISSUE THREAD

**Issue by hendrikniemann** [chakra-ui/chakra-ui#217]
Currently when I change a property like `fontSizes` it changes the appearance of my `<Heading>` and other components accordingly. That is because they come with a default value for the size. But when I change the `fonts` property there is no change to for example the `<Heading>` even though the name of the subproperty `heading` strongly suggests that.

[This is the relevant section in the docs](https://chakra-ui.com/theme#typography).

Maybe [Heading](https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/Heading/index.js) should have an attribute `fontFamily="heading"`?

I see why it might be difficult to add this to every component but like it is right now I think that it is inconsistent with the other theme properties.

**Comment by hendrikniemann** [comment]
> Please feel free to submit a PR for this

Great, I will do that. I think this would be considered a breaking change. We can then maybe discuss the implications of this in the PR thread.

**Comment by BiggieBrik** [comment]
how can i change the font family in my app while still using the import @chakra-ui/pro-theme , would appreciate the help :)
