### ISSUE TITLE
[Skeleton] Typing adjustment

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#2170]
# Bug report

When re-adding typing support for `noOfLines` in `system`, I unknowingly broke `Skeleton` typings, which I fixed in [this commit](https://github.com/chakra-ui/chakra-ui/commit/5c62c6902e81d0fd943dcaa5ddf534a2875f0304). But I believe this is a rather bad bandaid.

The issue is as follows:

`SkeletonTextProps` extends `SkeletonProps` here
https://github.com/chakra-ui/chakra-ui/blob/5c62c6902e81d0fd943dcaa5ddf534a2875f0304/packages/skeleton/src/skeleton.tsx#L119
and now tries to overwrite `noOfLines` coming from `system` which is no longer just `number`, but `number[]` and thus cannot be overwritten as `number`.

`Skeleton` doesn't care though, but should.
https://github.com/chakra-ui/chakra-ui/blob/5c62c6902e81d0fd943dcaa5ddf534a2875f0304/packages/skeleton/src/skeleton.tsx#L129
https://github.com/chakra-ui/chakra-ui/blob/5c62c6902e81d0fd943dcaa5ddf534a2875f0304/packages/skeleton/src/skeleton.tsx#L140

The solution probably involves using `theme.breakpoints` to dynamically determine the amount of breakpoints used (default 5, but customizeable), `useBreakpointValue` and adjusting the component further down in some way.

## Expected behavior

`Skeleton` should support `noOfLines` just fine.

**Comment by Jaskaran121** [comment]
i can create a pr for this....can you assign this ticket to me thankx
