### ISSUE TITLE
[Stack] Warning: 'Each child in a list should have a unique "key" prop'

### ISSUE THREAD

**Issue by kevinmichaelchen** [chakra-ui/chakra-ui#2171]
# Bug report

## Describe the bug
When I use a `Stack` I get this error:
```
Warning: Each child in a list should have a unique "key" prop.
```

## To reproduce

Occurs when using the Stack component.

## Minimal reproduction

I made a [codesandbox](https://codesandbox.io/s/pensive-wing-qvkz4?file=/src/index.js) reproducing the issue.

The warning should appear in the console.
## System information

- OS: Ubuntu 20.04
- Browser: Firefox
- Version of @chakra-ui/core: 1.0.0-rc.5

## Additional context
Seems similar to https://github.com/chakra-ui/chakra-ui/issues/514.

**Comment by ljosberinn** [comment]
![image](https://user-images.githubusercontent.com/29307652/95135168-5343ac00-0764-11eb-8ae8-0929179dd15c.png)

Not seeing any error here?

**Comment by kevinmichaelchen** [comment]
Err, sorry about that. I just updated the sandbox.

It needed the `shouldWrapChildren`.

```js
const Example = () => <Stack spacing={2} shouldWrapChildren>
  <Box>Box1</Box>
  <Box>Box2</Box>
</Stack>
```

**Comment by ljosberinn** [comment]
Thanks, could reproduce it now, do you want to file a PR or should I just push the fix? 👍 

https://github.com/chakra-ui/chakra-ui/blob/develop/packages/layout/src/stack.tsx#L157

this line should just be `<StackItem key={index}>{child}</StackItem>` instead

**Comment by vakker** [comment]
Using `map` to create the stack still seems to raise the same warning. 
E.g.:
```js
const Example = () => {
  const numbers = [1, 2, 3, 4, 5];
  return (
    <Stack spacing={2}>
      {numbers.map((number) => (
        <Box>{number}</Box>
      ))}
    </Stack>
  );
};
```

Is there a way to assign the keys to the boxes in this scenario?

**Comment by anubra266** [comment]
> Using `map` to create the stack still seems to raise the same warning. E.g.:
> 
> ```js
> const Example = () => {
>   const numbers = [1, 2, 3, 4, 5];
>   return (
>     <Stack spacing={2}>
>       {numbers.map((number) => (
>         <Box>{number}</Box>
>       ))}
>     </Stack>
>   );
> };
> ```
> 
> Is there a way to assign the keys to the boxes in this scenario?

Yeah @vakker 

```js
const Example = () => {
  const numbers = [1, 2, 3, 4, 5];
  return (
    <Stack spacing={2}>
      {numbers.map((number, index) => (
        <Box key={index}>{number}</Box>
      ))}
    </Stack>
  );
};
```
