### ISSUE TITLE
Chakra 1.0.0-rc.5 - toggleColorMode - need to click twice on first page load - on NextJS static pages

### ISSUE THREAD

**Issue by claytonfaria** [chakra-ui/chakra-ui#2174]
# Bug report

## Describe the bug

Chakra 1.0.0-rc.5 
Using NextJS with a simple static page the Button/Switch/IconButton that calls toggleColorMode needs to be clicked twice on first page load.

at first click, it creates a Localstorage entry with theme 'light', but doesnt toggle the colormode until i click the second time

on Chakra 0.8.0 the same code works fine as expected, it works on first click.

Same behavior on Chrome, Safari and Firefox (Both desktop and Mobile)

## To reproduce

Create a simple create-next-app and install Chakra 1.0.0-rc.5  and add a component that calls toggleColorMode, then try to click on first page load

## Minimal reproduction

https://github.com/claytonfaria/chakra-togglecolormode

## Expected behavior

Click once on the Button/Switch/IconButton and get the color mode changed on the first page load

## Screenshots

N/A

## System information

- OS: macOS - Catalina
- Browser :Chrome, Safari, Fireforx
- Version of @chakra-ui/core: 1.0.0-rc.5
- Version of Node.js: 14.3.0

**Comment by claytonfaria** [comment]
Hi,

I just noticed that adding ColorModeScript to my _app.js does the trick and now it works

```
    <ChakraProvider>
      <ColorModeScript initialColorMode="light" />
      <Component {...pageProps} />
    </ChakraProvider>
```

Shouldn't this option be default recommended for non SSR NextJS usage? or Maybe add this highlight to the "Getting Started" section on the docs? 

or even we could improve the ColorModeScript description? because before posting the issue here, I went through the whole docs, and it says to avoid glitches, as i was not having "glitches" it didn't get my attention at first.

As it works out of the box with 0.8.0, upgrading users might have the same issue. in the Upgrade guide it just mentioned that this script should be used for keeping sync between page visits, but no mentioned that without it, the first load, you need to click twice in the icon/switch.

I`d be glad to help somehow, with testing or any. 

Thank you for this awesome project!

**Comment by ljosberinn** [comment]
Hi, this is mentioned in the docs [in the migration guide here](https://next.chakra-ui.com/docs/migration#8-colormodescript-optional) and [in the Color Mode subroute](https://next.chakra-ui.com/docs/features/color-mode#add-colormodescript). Accordingly, I'd recommend moving the `ColorModeScript` into `_document`.

The required double click was a bug that has been fixed since, but is still unreleased.

**Comment by claytonfaria** [comment]
Glad to know the bug will be fixed for future releases and thank you for the support
