### ISSUE TITLE
Make menu enter/exit animatable

### ISSUE THREAD

**Issue by jaredpalmer** [chakra-ui/chakra-ui#218]

**Comment by jaredpalmer** [comment]
It's extremely janky right now. Any thoughts on this?

**Comment by segunadebayo** [comment]
I'm currently fixing this in the `dev-ts` branch 'coz I've found a better popper solution that'll support this use-case.

I understand it's janky right now, the new version will be released soon.

**Comment by segunadebayo** [comment]
@jaredpalmer. I just figured it out and will add it to the current code in the `dev-ts` branch.

![Nov-12-2019 19-41-54](https://user-images.githubusercontent.com/6916170/68700131-b3e25d00-0584-11ea-8e2c-ad142fb01492.gif)

You might need to wait for the next release to get these changes. Thanks for your patience
