### ISSUE TITLE
clipPath attribute not supported 

### ISSUE THREAD

**Issue by m4rcosazevedo** [chakra-ui/chakra-ui#2183]
# Feature request

O Chakra-ui does not support the `clipPath` attribute in typescript

```js
<PseudoBox
    _after={{
        content: '""',
        position: 'absolute',
        bg: 'white',
        right: 0,
        bottom: 0,
        left: 0,
        height: 35,
        clipPath: 'polygon(100% 0, 0% 100%, 100% 100%)'
    }}
/>
```

**Comment by KevinCain90** [comment]
Hi, I'd like to take this on if possible?
I just want to know what is required exactly. 
Does this attribute need replacing with something else or just to be removed as it isn't supported?

**Comment by m4rcosazevedo** [comment]
The attribute works, only the typescript that does not recognize

**Comment by segunadebayo** [comment]
Hi @m4rcosazevedo,

You can use the emotion's css prop to add this property since it doesn't reference the theme.

```jsx
/**@jsx jsx*/
import { jsx } from "@emotion/core"

<PseudoBox
      css={{
        "&:after": {
          content: `""`,
          position: "absolute",
          background: "white",
          right: 0,
          bottom: 0,
          left: 0,
          height: 35,
          clipPath: "polygon(100% 0, 0% 100%, 100% 100%)",
        },
      }}
    />
```

**Comment by segunadebayo** [comment]
We're trying to limit the number of style props we expose to the users to keep the API surface small.
