### ISSUE TITLE
Style the Required Form Control element

### ISSUE THREAD

**Issue by callumflack** [chakra-ui/chakra-ui#2187]
## Is your feature request related to a problem? Please describe.

Required form elements don't always need to be red with too much left margin.

## Describe the solution you'd like

Allow access to the <Required> component in order to set style props.

## Describe alternatives you've considered

Currently, I've added global style overrides for `chakra-form__required-indicator`!

**Comment by segunadebayo** [comment]
I've just pushed a fix for this.

We'll release an update shortly.

**Comment by caseymhunt** [comment]
May I please have a link to the change introduced to solve for this problem? Either the PR or documentation? Thank you!
