### ISSUE TITLE
CheckboxGroup types error

### ISSUE THREAD

**Issue by waptik** [chakra-ui/chakra-ui#2189]
# Bug report

## Describe the bug

I came across CheckboxGroup in the docs when i was looking for the Checkbox components. I found out typescript couldn't find types for `id`, `spacing` props but the docs made mention that accepts these props as well

## To reproduce

1. Go to https://codesandbox.io/s/chakra-next-checkboxgroup-30b6j?file=/src/App.tsx
2. See error

## Expected behavior
No types error for props mentioned in the docs.

## Screenshots

[screenshot](https://share.getcloudapp.com/bLuwmZ6W)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies): [e.g. Chrome, Safari]
- Version of @chakra-ui/core: 1.0.0-rc.3
- Version of Node.js: [e.g. 12.11.1]

**Comment by with-heart** [comment]
Hi @waptik! Thanks for opening this issue. The props table in the docs is outdated, and those props no longer exist. I opened #2193 to update the docs to reflect this.

I created a CodeSandbox showing how to add `spacing` and `id` values instead: https://codesandbox.io/s/chakra-next-checkboxgroup-forked-44sps?file=/src/App.tsx

**Comment by with-heart** [comment]
@allcontributors please add @waptik for bug

**Comment by waptik** [comment]
> Hi @waptik! Thanks for opening this issue. The props table in the docs is outdated, and those props no longer exist. I opened #2193 to update the docs to reflect this.
> 
> I created a CodeSandbox showing how to add `spacing` and `id` values instead: https://codesandbox.io/s/chakra-next-checkboxgroup-forked-44sps?file=/src/App.tsx

Thnaks. That did the trick.
