### ISSUE TITLE
Editable should have validation possibilities 

### ISSUE THREAD

**Issue by Psvensso** [chakra-ui/chakra-ui#2195]
# Feature request
We need our text to be required, right now there is no clear and concise way to validate and stop the user from submitting bad data. If you catch the bad data in onSubmit there is no way to cancel (reset editable state). 

## Is your feature request related to a problem? Please describe.
```
<Editable
   defaultValue={defaultValue}
   onSubmit={(e) => {
       if(someValidation(e)){
        //I need to cancel out and reset to previous state.
        //Im outside of EditableContext so i cant use useEditableState to call onCancel
       }
    }}
>...
```

## Describe the solution you'd like
Provide the onCancel func to onSubmit as second param, similar to how formik provides you with "formikHelpers" to control the form behavior in different callbacks.

## Describe alternatives you've considered
1) preferred, easy to implement - Provide internal editable state or just the onCancel into onSubmit.

2) Wrap controller in a <form> and use form events.

## Additional context
relevant code [onSubmitProp?.(value)](https://github.com/chakra-ui/chakra-ui/blob/3e3ba274d8b7294e79689cffe90433413d7ed199/packages/editable/src/use-editable.ts#L148)

**Comment by Psvensso** [comment]
On second thought, 
current code also resets the internal state before the user could cancel out of the new value as proposed above. So this would not really work. I guess sending in a validate function prop would be easier and call that before [updating the internal state](https://github.com/chakra-ui/chakra-ui/blob/3e3ba274d8b7294e79689cffe90433413d7ed199/packages/editable/src/use-editable.ts#L147) would be the quickest way to allow validation on this.

**Comment by angelbt91** [comment]
Quick message just to pump this issue, as I'm struggling with what @Psvensso detailed.

**Comment by allenchuang** [comment]
Same here! This is actually a necessary feature for us to be able to handle server response such as duplication, and revert the state back.

**Comment by heycassidy** [comment]
I would also love this feature

**Comment by mwhitlaw** [comment]
The feature request is definitely a good idea, but it appears to have been closed/ignored. Is there a way to revive this request?

**Comment by marttiheikkila** [comment]
I have the same problem. I'm having to jump through so many hoops to be able to cancel, if the onSubmit was called with invalid data.
