### ISSUE TITLE
Advanced Theming document incorrect.

### ISSUE THREAD

**Issue by albusphan** [chakra-ui/chakra-ui#2202]
## Describe the bug

It seems like the Advanced theming doc in https://next.chakra-ui.com/docs/theming/advanced is incorrect. I try to follow the doc but it not working on v1.0.0.rc5

https://codesandbox.io/s/focused-hermann-k6xnz?file=/src/button.tsx

## Expected behavior

This what I did to have strong type for component config.

`type StyleOptions = {
  theme: Theme;
  colorMode: "light" | "dark";
};`

`type StyleInterpolation =
  | ((options: StyleOptions) => SystemStyleObject)
  | SystemStyleObject;`

`interface StyleConfig {
  baseStyle?: StyleInterpolation;
  sizes?: { [size: string]: StyleInterpolation };
  variants?: { [variant: string]: StyleInterpolation };
}`

## System information

- Version of @chakra-ui/core: 1.0.0-rc.5

**Comment by segunadebayo** [comment]
Thanks for reporting this @albusphan and leaving a hint in the Codesandbox

I've updated the docs accordingly.
