### ISSUE TITLE
RadioGroups in Menu

### ISSUE THREAD

**Issue by baumandm** [chakra-ui/chakra-ui#2204]
# Feature request

## Is your feature request related to a problem? Please describe.

I needed to create a dropdown menu with radio buttons, and didn't see anything in the documentation about this use case.  So I tried to mashup the `RadioGroup` and `Menu` components and was pretty happy with the result:

<img width="254" alt="Screen Shot 2020-10-09 at 16 45 52" src="https://user-images.githubusercontent.com/3084806/95630020-10792100-0a4f-11eb-8690-942b48835ad8.png">

Here's a codesandbox illustrating this: https://codesandbox.io/s/amazing-poitras-hkuzd?file=/src/index.tsx

Two questions:

1. Is this a supported feature, or more of a happy accident?  In other words, is this likely to break in future releases? 
2. Is this worth writing up an example in the documentation? If so I'd be happy to contribute.

Thanks!

**Comment by ljosberinn** [comment]
Hi @baumandm -

this looks similar to what `MenuOptionGroup` does, just with a different icon, which is almost entirely possible already:

![image](https://user-images.githubusercontent.com/29307652/95652926-e1b58600-0af4-11eb-8fac-070406ecdeb5.png)

```js
<MenuItemOption icon={<StarIcon />} value="asc">Ascending</MenuItemOption>
```

However, it's currently _not_ possible to define an icon for the unchecked state. This might be something we could add support for, would you be up for it if this suits your case?

**Comment by baumandm** [comment]
That's exactly what I wanted, I don't know how I missed it earlier.  I don't think I really need an unchecked icon, so I'm happy to close this.

**Comment by danstans** [comment]
@ljosberinn I hate to comment on something so many years later, but it would be beneficial for my app to have a unchecked icon state. do you have any ideas how I might accomplish this? 

I have a few ideas that involve watching the form state and using a ternary in the icon prop
