### ISSUE TITLE
useBreakpointValue Hook throws an "addEventListener is not a function" error in Safari

### ISSUE THREAD

**Issue by Holunderbeersaft** [chakra-ui/chakra-ui#2206]
# Bug report

## Describe the bug

The useBreakpointValue Hook throws an "addEventListener is not a function" error in Safari (Desktop and mobile iOS). In the Chakra UI docs the error also occurs on the useBreakpointValue Hook page. 

## To reproduce

The error happens immediate without resizing the window. The elements are not showing up.

- [CodeSandbox of Error](https://codesandbox.io/s/dank-morning-2x8id?file=/src/index.js)
- [Same in the Chakra UI docs](https://next.chakra-ui.com/docs/hooks/use-breakpoint-value)

## Expected behavior

No error should be thrown. Elements should change variants when resizing the browser.
As far as I tested it works correctly without throwing an error in Opera, Firefox and Chrome.

## Screenshots

![Bildschirmfoto 2020-10-10 um 15 13 35](https://user-images.githubusercontent.com/27418675/95655978-6ad7b780-0b0b-11eb-8f1e-d07d94cc220e.png)
![Bildschirmfoto 2020-10-10 um 15 07 56](https://user-images.githubusercontent.com/27418675/95655980-6ca17b00-0b0b-11eb-8319-386d09e576eb.png)

## System information

- OS: macOS Catalina 10.15.5 (also iOS 13.7)
- Browser: Safari, mobile Safari
- Version of @chakra-ui/core: 1.0.0-rc.5
- (Version of Node.js: v12.16.3)

**Comment by fekle** [comment]
see #2117

**Comment by ljosberinn** [comment]
yeah that was a bit of a dumb move on my side, sorry for the inconvenience. fixed in the next release :)
