### ISSUE TITLE
Slider component triggers onChange callback despite the value not actually changing

### ISSUE THREAD

**Issue by collinsmuriuki** [chakra-ui/chakra-ui#2210]
# Bug report

## Describe the bug
The slider component will trigger the callback function when holding the slider thumb and slightly moving it, only that the movement is minimal enough to not change the `value` of the slider

## Screenshots
![gif](https://media.giphy.com/media/EF1O2Jiadhf0POQ66B/giphy.gif)

## Minimal reproduction
Here's the [code](https://github.com/collinsmuriuki/wasm_pass/blob/master/app/src/components/Slider.js)

## Expected behavior
The `onChange` callback should change only when the `value` changes. 

## Suggestion
 Add  a `onValue` callback as was previously suggested on #1354

## System information
- OS: macOS
- Browser: Vivaldi, Safari
- Version of @chakra-ui/core: 10.0.35
- Version of Node.js: 12.18.0

**Comment by shubhamzanwar** [comment]
I can take a look at this

**Comment by segunadebayo** [comment]
Hi @collinsmuriuki,

This has been fixed in the upcoming v1 release.

Thanks for reporting it
