### ISSUE TITLE
[Checkbox] Control still has the blue outline on focus, even wih focus-visible package applied

### ISSUE THREAD

**Issue by la55u** [chakra-ui/chakra-ui#2234]
## Describe the bug

The checkbox square has a blue outline color when focused with mouse click, despite the [focus-visible](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/css-reset/README.md) package being used.

## To reproduce

1. `npm i focus-visible`
2. add `import "focus-visible/dist/focus-visible"` to `_app.js`
3. add a `<Checkbox/>` element 

## Expected behavior

The blue outline should only be visible when using keyboard navigation, just like with Button etc.

## System information
"@chakra-ui/core": "^1.0.0-rc.5",
 "next": "9.5.3",

**Comment by cschroeter** [comment]
It is also the case if you use `:focus-visible` which is now natively supported in Chrome

**Comment by rheng001** [comment]
Facing the same issue

**Comment by MichaelGrigoryan25** [comment]
This occurs even when trying to specify `focus` props on the `<Checkbox />` directly. Can confirm

**Comment by kdfriedman** [comment]
Currently facing the same issue

**Comment by kdfriedman** [comment]
I was recently able to make this work as expected:

```
.chakra-checkbox__input[data-focus-visible-added]
  + .chakra-checkbox__control[data-focus] {
  box-shadow: 0 0 0 3px rgb(66 153 225 / 60%) !important;
}
```

I'm using the `data-focus-visible-added` attribute which is appended to the previous sibling `input` element. If you combine the input and span elements, the styling works as expected for tabbed focus vs click focus. As a caveat, I have the `focus-visible` polyfill installed as well.

**Comment by lingyun-z** [comment]
I added these in my global theme and it works as expected.
`
*:focus {
  box-shadow: none !important;
}
*[data-focus] {
  box-shadow: none !important;
}
`

**Comment by mcha-dev** [comment]
Safari (the new IE) is supposed to support `focus-visible` soon 🤞 [can i use](https://caniuse.com/?search=focus-visible) 

_The world's most valuable company is always late to the party `focus-visible`, `<input type="date" />`, `flex gap`, `BroadcastChannel`....😐_ 

I needed to overwrite checkbox boxshadow so I ended up modifying @kdfriedman 's solution to

```css
/* using tailwind */
.chakra-radiobox__control[data-focus],
.chakra-checkbox__control[data-focus] {
  @apply ring-2 ring-red-300 !important;
}
```

**Comment by Blagoj5** [comment]
Another workaround can be:
```tsx
<Checkbox
  size="sm"
  colorScheme="primary"
  defaultIsChecked
  css={`
    span:first-of-type:focus {
      box-shadow: unset;
    }
  `}
  >
  {type}
</Checkbox>
```

**Comment by Brettm12345** [comment]
The focus visible package just adds the polyfill for the focus visible css selector which indicates keyboard focus. In order to remove the box shadow you gotta do this 
```tsx
<Checkbox _focusVisible={{ shadow: 'outline'}} _focus={{ shadow: "none"}} />
```
to apply this globally add the following to your global styles 
```typescript
'.js-focus-visible :focus:not(.focus-visible)': {
  shadow: 'none',
},
```

**Comment by anilanar** [comment]
Perhaps what's not clear is whether if this is intended or just a bug, or under which circumstances this is a bug.

**Comment by slava-lu** [comment]
There is the info regarding the Avada 7.6 at the plugin page:
https://codecanyon.net/item/custom-post-types-and-taxonomies-for-fusion-builder/15572585

```If you are using the latest Avada version 7.6. please contact us via support@amunet.biz with the purchase code with the valid support contract so that we can send you the quick fix. The general release will be available in 3-4 weeks.```

**Comment by segunadebayo** [comment]
For anyone still having this issue. Kindly use the workaround suggested above.

**Comment by ehynds** [comment]
Another option if you want to set this globally in your theme:

```js
const theme = extendTheme({
  components: {
    Checkbox: {
      parts: ['control'],
      baseStyle: {
        control: {
          _focus: {
            boxShadow: 'none',
          },
        },
      },
    }
  }
});
```

**Comment by DavidLabaz** [comment]
> I added these in my global theme and it works as expected.
> 
> ```
> *:focus {
>   box-shadow: none !important;
> }
> 
> *[data-focus] {
>   box-shadow: none !important;
> }
> ```

dude, thank you so much
