### ISSUE TITLE
Breakpoints generate different media-queries

### ISSUE THREAD

**Issue by ahmdtalat** [chakra-ui/chakra-ui#2235]
# Bug report

## Describe the bug

When I override the breakpoints with a custom one, Chakra generates different media queries

## Expected behavior

I expect to see a min-width query with the custom breakpoints that I defined
![image](https://user-images.githubusercontent.com/46477493/95882586-29007880-0d7a-11eb-86c6-46d623bf6399.png)

## Actual behavior
![image](https://user-images.githubusercontent.com/46477493/95882779-649b4280-0d7a-11eb-97ce-1ed4200ed41f.png)

**Comment by ljosberinn** [comment]
hi @ahmdtalat - which version is this on? where do you extend your theme? can you share a sandbox? :)

**Comment by ahmdtalat** [comment]
version: "@chakra-ui/core": "^0.8.0"
I extend my theme in my components and everything works great except this one and the **"content"** attr in ::before and ::after.

**Comment by ljosberinn** [comment]
ah, well - I'm personally not aware of that, but it might have been a limitation of v0.8. I'd heavily recommend to switch to v1 since release is near and we expose `createBreakpoints` for this purpose :)

**Comment by ahmdtalat** [comment]
I've already upgraded to v1 and it solved the breakpoints issue but I got this styling all over my app 
`*:not(style) ~ *:not(style) 
{
    margin-left: 0.5rem;
    margin-top: 0;
}`

**Comment by ljosberinn** [comment]
can you make a sandbox? I've not seen this.

**Comment by ahmdtalat** [comment]
I have another issue, it would be great if there a workaround:
Old version: say I want to render a list of icons, simply passing a list of icons' names as strings and pass it as the name prop
`icons.map(iconName => <Icon name={iconName}/>`

Version 1: have no idea how to do this properly

**Comment by ljosberinn** [comment]
Icons are in a separate package: `@chakra-ui/icons` and you can import them there.

```js
import { AddIcon, ArrowBackIcon } from '@chakra-ui/icons';

const iconMap = {
  add: AddIcon,
  arrowBack: ArrowBackIcon
}

...

['add', 'arrowBack'].map(iconName => <Icon as={iconMap[iconName]} />)
```

**Comment by segunadebayo** [comment]
Thanks for chiming in @ljosberinn.

Considering this is not an issue in v1. Permit me to close this out.
