### ISSUE TITLE
Documentation for useSystemColorMode?

### ISSUE THREAD

**Issue by hems** [chakra-ui/chakra-ui#2238]
# Feature request

I can see `useSystemColorMode` is set to `false` on this [page on the documentation](https://next.chakra-ui.com/docs/features/color-mode#change-color-mode-behavior) but i don't see any explanation about what that actually do?

## Is your feature request related to a problem? Please describe.

It's more of a documentation / explanation request than a feature request?

## Describe the solution you'd like

Some comment/explanation about that flag on the documentation?

**Comment by ljosberinn** [comment]
Hi - it's about this section, we definitely clarify that.

![image](https://user-images.githubusercontent.com/29307652/95960414-fef39880-0e03-11eb-954a-21c48e9e640b.png)

`useSystemColorMode` indicates Chakra to detect the theme via `@media (prefers-color-scheme: dark | light)`.

Note that if you set this to `true`, it takes priority over 
a) the default, `initialColorMode`
b) users choice when the user toggled the theme once.

**Comment by hems** [comment]
> Hi - it's about this section, we definitely clarify that.
> 
> ![image](https://user-images.githubusercontent.com/29307652/95960414-fef39880-0e03-11eb-954a-21c48e9e640b.png)
> 
> `useSystemColorMode` indicates Chakra to detect the theme via `@media (prefers-color-scheme: dark | light)`.

Thank you for pointing that out!

> Note that if you set this to `true`, it takes priority over
> a) the default, `initialColorMode`
> b) users choice when the user toggled the theme once.

I don't think a) and b) were clear, all the examples on the website only show it set to `false` and there is not real explanation of what happens if you turn it to true?

Perhaps a section named "Using System Color Mode" could be added?

Also, i would guess most end-users would only want to use the System Color while the user has not toggled the theme, once the user toggles and it's saved on localStorag / cookies, then system color mode should not take priority over the user preferences? As in: i would guess the system colour would only be used as a "first guess colour before the user decides"?

Perhaps to make this a little bit more customiseable the system color code could be exposed as a hook or function under `theme-tools` ?

**Comment by ljosberinn** [comment]
> Perhaps a section named "Using System Color Mode" could be added?

We can definitely do that! 

> Also, i would guess most end-users would only want to use the System Color while the user has not toggled the theme, once the user toggles and it's saved on localStorag / cookies, then system color mode should not take priority over the user preferences? As in: i would guess the system colour would only be used as a "first guess colour before the user decides"?

Personally that's my opinion too and I've come to terms that this is both a divisive topic and a design decision. We may come back to it after v1 launch as realistically though, it's ultimately a minor issue.

> Perhaps to make this a little bit more customiseable the system color code could be exposed as a hook or function under theme-tools?

What would it expose, exactly? `useColorMode` exposes the current color mode.

**Comment by hems** [comment]
> What would it expose, exactly? `useColorMode` exposes the current color mode.

`useSystemColor` could return the current system color and then the application could take care of deciding what to do?

**Comment by ljosberinn** [comment]
by `take care of deciding what to do` youre thinking of something like this approach?

- render initially with whatever is in `theme.config.initialColorMode` and `theme.config.useSystemColorMode` being false
- app detects `systemColorMode` via `useSystemColorMod` and reacts appropriately

**Comment by hems** [comment]
> by `take care of deciding what to do` youre thinking of something like this approach?
> 
> * render initially with whatever is in `theme.config.initialColorMode` and `theme.config.useSystemColorMode` being false
> * app detects `systemColorMode` via `useSystemColorMod` and reacts appropriately

yes, i guess by default we need to run the initialColorMode on the serverSide because i guess there is no way of detecting the systemColorMode on the ServerSide.

Then once the user has rendered we can check his systemColorMode and use that as default.

Once the user asks to change, then Chakra would save the localStorage / Cookie so from that point on we know what color to render for that user.
