### ISSUE TITLE
bug(docs/utilities): full page reload when navigating between the "utilities" section entries

### ISSUE THREAD

**Issue by thetric** [chakra-ui/chakra-ui#224]
# https://chakra-ui.com bug report

### Description
When navigating to or between the "utilities" section in the docs a full page reload occurs. As a side effect of the reload the theme setting is reset.

### What's the affected URL?
- https://chakra-ui.com/useclipboard
- https://chakra-ui.com/usedisclosure
- https://chakra-ui.com/usetheme

### Reproduction Steps

1. Open https://chakra-ui.com/getting-started
2. Enable the dark theme
3. Go to Utilities/useClipboard
4. The page is displayed with the light theme active

Same when starting in 1. with for example https://chakra-ui.com/usedisclosure.

### Expected vs Actual Behavior
Expected: No full page reload. After enabling the dark theme should always be active - even after navigating between different sections.

Actual: Full page reload. After enabling the dark theme and navigating to a link under "Utilities" the theme is reset to the white theme.

## 🔥 Exception or Error
I've noticed HTTP 404s for the bundles of the "utilities" components.

### Browser info
Firefox 70.0.1 (64 bit), Google Chrome 78.0.3904.87 (64 bit)
Windows 10 Pro, v1903

**Comment by segunadebayo** [comment]
Hi @thetric,

I believe this is because there's a full-page reload on those pages. I'll look into the cause of the reload

**Comment by segunadebayo** [comment]
I've resolved this issue and will update the docs soon.
