### ISSUE TITLE
Chakra 1.0.0-rc.5 - Framer-Motion - Warning: React does not recognize the `whileHover` prop on a DOM element.

### ISSUE THREAD

**Issue by claytonfaria** [chakra-ui/chakra-ui#2240]
# Bug report

## Describe the bug

Using the Documentation Guide in order to use Chakra and Framer Motion gives console warnings (however, the animations works as expected)

> Warning: React does not recognize the `whileHover` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `whilehover` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
>     in div (created by Context.Consumer)
>     in Box (created by ForwardRef(MotionComponent))
>     in ForwardRef(MotionComponent) (at App.js:11)
>     in App (at src/index.js:9)
>     in StrictMode (at src/index.js:8)

> Warning: React does not recognize the `dragConstraints` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `dragconstraints` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Context.Consumer)
    in Box (created by ForwardRef(MotionComponent))
    in ForwardRef(MotionComponent) (at App.js:11)
    in App (at src/index.js:9)
    in StrictMode (at src/index.js:8)

## To reproduce

Use the Chakra documentation Framer-motion guide, that minimal sample already shows the error, below a sandbox

## Minimal reproduction

https://codesandbox.io/s/chakra-framer-motion-error-whq5x?file=/src/App.js

## System information

- Browser (if applies): [e.g. Chrome, Safari]
- Version of @chakra-ui/core: [e.g. 1.0.0-rc.5]

**Comment by ljosberinn** [comment]
Fairly sure this guide will be updated after Sage finished migrating Chakras internals to framer-motion, see [this branch](https://github.com/chakra-ui/chakra-ui/tree/feat/framer-motion) for more context. :)

**Comment by claytonfaria** [comment]
Thanks Gerrit, awesome work you guys are doing!
I will just ignore this warning message for now(as everything is working) and keep up with my project, as soon as the Chakra internals are working with framer-motion, then i update my code

**Comment by segunadebayo** [comment]
Hi @claytonfaria,

Here's how I resolved the warning: https://codesandbox.io/s/chakra-framer-motion-error-fixed-b7fjn?file=/src/App.js

Hope this helps.

**Comment by claytonfaria** [comment]
Hi @segunadebayo ! that works great! no more warnings! thank you for the support and for the amazing work!

**Comment by petrosv91** [comment]
Hello, I still have this problem but the link that @segunadebayo provides doesn't work anymore so I can't see the solution. Can someone share the solution or update the link? Thank you! 

- Version of @chakra-ui/core: 1.0.0-rc.7

**Comment by claytonfaria** [comment]
hello, the solution is create a chakra custom component out of the motion.div, instead of creating a motion.custom out of a chakra component

https://codesandbox.io/s/chakra-framer-motion-error-forked-yfln3

hope it helps

**Comment by oahmaro** [comment]
> hello, the solution is create a chakra custom component out of the motion.div, instead of creating a motion.custom out of a chakra component
> 
> https://codesandbox.io/s/chakra-framer-motion-error-forked-yfln3
> 
> hope it helps

This solution works, but then for some reason the transition attribute from framer motion does not work!, i have looked at the components code built by chakra and i have noticed that they don't use the transition attribute on there code, and just use variants.

**Comment by claytonfaria** [comment]
I dont have much experience with framer motion, but whenever i used it, I have always added the transition either inside variants or directly to the animate

I am not quite sure about the best practices in this case, but instead of :

```
<motion.div
    animate={{ scale: 2 }}
    transition={{ duration: 0.5 }}
  />
```
I've done :

<motion.div
    animate={{ scale: 2, transition:{ duration: 0.5 } }}
  />

if that's your case that you cannot use transition directly as prop in the custom chakra/framer motion component, try this one or inside the variants using this same logic

**Comment by oahmaro** [comment]
I am using AnimateSharedLayout component, This component will automatically make animation for components on mount and unmount if they share same layoutID, so in my case i don't even have animate or variants props, and i only need transition prop to control that animation.

**Comment by bulby97** [comment]
@oahmaro Did you fix the issue ? It looks like there are two solutions with their own drawback:

- `const MotionBox = motion.custom(Box);` with errors in the console
- `const MotionBox = chakra(motion.div);` with `transition` not working.

**Comment by TimKolberger** [comment]
See #2538
