### ISSUE TITLE
When Flex component was used inside loop: same claasName is applied globally for all Flex and divs outside of loop

### ISSUE THREAD

**Issue by humoyun** [chakra-ui/chakra-ui#2241]
# Bug report

## Describe the bug
When I use Flex inside map loop class names of all other Flex's outside of loop are same, also it overrides raw div tag's class name

## To reproduce
Just use Flex inside some component and make multiple instances of component by using map

```
      {loading ?
          <Box>Loading...</Box> :
             data && data.posts.map((post) => (
          <Post key={post.id} data={post}></Post>
        ))
      } 

      <div className='load-more-btn'>
        {/* This div className is also the same as Flex className inside loop */}
        <Button
          variant="outline"
          m="auto"
          isLoading={loading}>
          Load more
        </Button>
      </div>
      <Flex>
        {/* This Flex className is also the same as Flex className inside loop */}
      </Flex>
```

And here is the Post component
```
 <Flex
        bg="#fff"
        p={1}
        minH={100}
        my={5}
        border="1px"
        borderRadius={3}
        borderColor="lightgrey"
        flexDirection="column"
        borderTopRightRadius={2}
        borderBottomRightRadius={2}
      >
        <Heading as="h4" size="sm">
          {data.title}
        </Heading>
        <Box fontSize={14}>{data.textSnippet}</Box>
   </Flex>
```

## Expected behavior

Should be able to use classname for raw div tags and other Flex components without overlapping

## Screenshots

![Screen Shot 2020-10-14 at 6 28 21 PM](https://user-images.githubusercontent.com/9885273/95970693-36396800-0e4b-11eb-8158-03cd88b85557.png)

![Screen Shot 2020-10-14 at 6 28 51 PM](https://user-images.githubusercontent.com/9885273/95970706-3a658580-0e4b-11eb-9d7e-96bd443fb346.png)

## System information
- OS: macOS
- Browser: Chrome
- Version of @chakra-ui/core: "^1.0.0-rc.3"
- Version of Node.js: 12.11.1

**Comment by ljosberinn** [comment]
Hi, could you provide a codesandbox? This is not how emotion behaves - you have different props on those two `Flex` components, one has multiple props, the other has none. Emotion will create separate classNames for both. Also it does not override another elements className. Here's a sandbox: https://codesandbox.io/s/blissful-rgb-ink4l?file=/src/App.js

**Comment by humoyun** [comment]
> https://codesandbox.io/s/blissful-rgb-ink4l?file=/src/App.js

The codesandbox which you provided working as expected, that means there is some other issue in my project. I put it in github repo, could you please check it and help me to find out the issue:

[Here is the repo](https://github.com/humoyun/reddir-web) `pages/index.tsx` and `components/Post.tsx`

**Comment by ljosberinn** [comment]
It's late here so I only took a quick glance, but it might have something to do with your `_app.tsx`, not using `ChakraProvider`. Try that please, see docs [here](https://next.chakra-ui.com/docs/migration#2-update-the-themeprovider). Also please remove your emotion dependencies [here](https://github.com/humoyun/reddir-web/blob/master/package.json#L13), as they are no longer need with Chakra v1.
