### ISSUE TITLE
[NumberInputField] Starting at min value when using arrow key on empty input

### ISSUE THREAD

**Issue by laurensnl** [chakra-ui/chakra-ui#2242]
# Bug report

## Describe the bug

When using the up or down arrow key on your keyboard while focussed on a `NumberInputField` with a `min` and `max` set and without a value (empty box), the value entered in the field is the `min` value, instead of `1` or `-1` (Chakra v0.8 behavior). 

## To reproduce

1. Open the Sandbox below
2. Focus on the input field
3. Press the up or down key on your keyboard

## Minimal reproduction

https://0i6fm.csb.app/

## Expected behavior

I would expect the value to start at 0, like it did in Chakra v0.8. Makes more sense. 

## System information

- OS: MacOS
- Browser: Chrome & Safari
- Version of @chakra-ui/core: 1.0.0-rc.5

**Comment by segunadebayo** [comment]
Thanks for reporting this. I just pushed a fix

**Comment by laurensnl** [comment]
Awesome @segunadebayo! Thanks!
