### ISSUE TITLE
Text noOfLines prop complains about array of numbers type

### ISSUE THREAD

**Issue by redbaron76** [chakra-ui/chakra-ui#2243]
# Bug report

## Describe the bug

As in the title, when I use `<Text noOfLines={[1, 2, 3]}>...</Text>`, following the Pro tip in the Docs, Typescript complains about the type. It seems to accept a single number only.

## Expected behavior

It should accept array of number as well.

## Screenshots

![image](https://user-images.githubusercontent.com/1061849/96006509-db4d4400-0e3d-11eb-8211-24d4dff58614.png)

## System information

- OS: OSX Catalina
- Version of @chakra-ui/core: 1.0.0-rc.5
- Version of Node.js: 10.22.0

**Comment by ljosberinn** [comment]
fixed with #2203 and thus will automatically ship with the next release :)
