### ISSUE TITLE
Eval bundle in Head causes color-mode to store bad ref to document.body 

### ISSUE THREAD

**Issue by Psvensso** [chakra-ui/chakra-ui#2245]
# Bug report
We are using Direflow to create web-components with Chakra, Direflow is a WebComponent wrapper that uses CRA for dev development. Direflow, for some reason, injects the bundle into the Head of the page and this causes some undesired side-effect. 

## Describe the bug
color-mode.utils.ts stores and exports a variable to document.body, document.body can in some circumstances change (when eval:ing bundle prior to page load for example, e.g. in the <Head> portion of the document), so it should not be stored. 

## To reproduce
It's a tricky problem to reproduce with for example codesandbox since all default CRA's are injecting into body. But building a package and injecting it into the head will cause color-mode.utils.ts.body export var to be null. In turn, causing syncBodyClassName to fail. 

## Expected behaviour
syncBodyClassName not to crash with "className of null". // Null check on the body const.

I was supposed to write a PR for this but i have no idea how to actually write a good test for this. 

Either don't export body (no one is importing it atm anyways)
```
/**
 * Function to add/remove class from `body` based on color mode
 */
export function syncBodyClassName(isDark: boolean) {
  const body = isBrowser ? document.body : mockBody;
  body?.classList.add(isDark ? classNames.dark : classNames.light)
  body?.classList.remove(isDark ? classNames.light : classNames.dark)
}
``` 

Or make it a 'getter'
```
export const getBody = ()=> isBrowser ? document.body : mockBody

/**
 * Function to add/remove class from `body` based on color mode
 */
export function syncBodyClassName(isDark: boolean) {
  const body = getBody();
  body?.classList.add(isDark ? classNames.dark : classNames.light)
  body?.classList.remove(isDark ? classNames.light : classNames.dark)
}
``` 

[Source ref](https://github.com/chakra-ui/chakra-ui/blob/234a1e036bf1e5bc365c5a87094d6965e995e8da/packages/color-mode/src/color-mode.utils.ts#L17)

**Comment by segunadebayo** [comment]
Hi @Psvensso,

We've gone ahead to use a 'getter' following your suggestion. I think it's the right approach from a closure perspective.

I've pushed the changes.

Cheers.
