### ISSUE TITLE
[Docs] Menu components miss some props

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#2247]
# Bug report

## Describe the bug

- props [`icon`](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/menu/src/menu.tsx#L190) and `iconSpacing` are missing [in the docs](https://next.chakra-ui.com/docs/overlay/menu#menuitem-props)
- other `MenuItem` components should have their props checked whether they allow those props too (e.g. `MenuItemOptionProps` do and aren't mentioned either in the docs)

## Expected behavior

Props are properly documented.

**Comment by navin-moorthy** [comment]
@ljosberinn You can assign this to me, I will update the docs over the weekend.

**Comment by shuchitpant** [comment]
Has this one been completed?
If no, I'd like to contribute.

**Comment by navin-moorthy** [comment]
I am about to complete this.

**Comment by ljosberinn** [comment]
hey @navin-moorthy we'll release a new rc tomorrow, any update on this? If not, also fine, just letting you know :)

**Comment by navin-moorthy** [comment]
> hey @navin-moorthy we'll release a new rc tomorrow, any update on this? If not, also fine, just letting you know :)

Hey @ljosberinn, sorry for the later,  I was taking some time to understand the Menu component to properly update the docs.
PR #2313  has been submitted.
