### ISSUE TITLE
[Recipe] Next.js components & Chakra

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#2248]
We should provide a proper recipe of how to integrate Chakras `Link` with `next/link`, including the edge case of using a `Link` within a `MenuItem`.

Resources:
- https://github.com/ljosberinn/personal-react-boilerplate/blob/master/src/client/components/LanguageSwitch.tsx#L79
- https://github.com/ljosberinn/personal-react-boilerplate/blob/master/src/client/components/ExternalLink.tsx (`forwardRef`)
- https://github.com/ljosberinn/personal-react-boilerplate/blob/master/src/client/components/InternalLink.tsx (previous version without i18n integration, also currently misses `forwardRef`)

Since Next.js v10, next/image is a thing and this should be documented as well.

**Comment by Talor-A** [comment]
https://github.com/chakra-ui/chakra-ui/issues/132#issuecomment-673021422

this component worked great in typescript for me, hope this helps!

**Comment by ljosberinn** [comment]
It's not feature complete I'm afraid, but it's close so that's something :)

**Comment by cdedreuille** [comment]
I would love to get a proper guide for this one yes. 🙌

**Comment by TheThirdRace** [comment]
I'm currently building a new version of my website and had to deal with <Link> in menu too. 

Here's what I use for now:

```
import { forwardRef, Link as ChakraLink, LinkProps as ChakraLinkProps } from '@chakra-ui/core'
import NextLink, { LinkProps as NextLinkProps } from 'next/link'
import { ReactElement } from 'react'
import { Rename } from '../../type/Typescript'

type LinkProps = Partial<Rename<NextLinkProps, 'as', 'asRoute'>> &
	Pick<NextLinkProps, 'href' | 'passHref' | 'prefetch' | 'replace' | 'scroll' | 'shallow'> &
	Pick<ChakraLinkProps, 'children' | 'isExternal' | 'variant'>

export const Link = forwardRef<LinkProps, 'a'>(
	(
		{
			asRoute,
			children,
			href,
			isExternal,
			passHref = true,
			prefetch,
			replace,
			scroll,
			shallow,
			variant,
			...chakraInternals
		}: LinkProps,
		ref
	): ReactElement => {
		return (
			<NextLink
				as={asRoute}
				href={href}
				passHref={passHref}
				prefetch={prefetch}
				replace={replace}
				scroll={scroll}
				shallow={shallow}
			>
				<ChakraLink
					isExternal={isExternal}
					ref={ref}
					variant={variant}
					// eslint-disable-next-line react/jsx-props-no-spreading
					{...chakraInternals}
				>
					{children}
				</ChakraLink>
			</NextLink>
		)
	}
)

```

**Comment by franky47** [comment]
I have written my own interface library between Next.js and Chakra-UI, [`@47ng/chakra-next`](https://github.com/47ng/chakra-next), it includes Link components (text link, button, icon button) and other shorthands.

I'm planning on adding support for the Next.js v10 Image component (let it do the image processing & fetching) and bridge it with Chakra's style props. The fallbackSrc and onError & onLoad callbacks might be trickier to implement without having to dig into the inner workings of either base components though..

**Comment by oahmaro** [comment]
It is documented that the chakra link component integrates well with other routing libraries like React Router, Reach Router and Next.js Link.

But when i try to use Chakra Link & Nextjs as follow.
`<Link as={NextLink} href='/test'>About</Link>`

i get the following error in typescript
`Type '{ children: string; as: (props: PropsWithChildren<LinkProps>) => DetailedReactHTMLElement<{ onMouseEnter?: (event: MouseEvent<Element, MouseEvent>) => void; onClick: (event: MouseEvent<...>) => void; href?: string; ref?: any; }, HTMLElement>; href: string; }' is not assignable to type 'Pick<PropsWithChildren<LinkProps>, "as" | "replace" | "scroll" | "shallow" | "passHref" | "prefetch" | "locale">'.
  Types of property 'as' are incompatible.
    Type '(props: PropsWithChildren<LinkProps>) => DetailedReactHTMLElement<{ onMouseEnter?: (event: MouseEvent<Element, MouseEvent>) => void; onClick: (event: MouseEvent<...>) => void; href?: string; ref?: any; }, HTMLElement>' is not assignable to type 'Url'.
      Type '(props: PropsWithChildren<LinkProps>) => DetailedReactHTMLElement<{ onMouseEnter?: (event: MouseEvent<Element, MouseEvent>) => void; onClick: (event: MouseEvent<...>) => void; href?: string; ref?: any; }, HTMLElement>' has no properties in common with type 'UrlObject'.`

any idea how i can fix this?

**Comment by omarkhatibco** [comment]
> It is documented that the chakra link component integrates well with other routing libraries like React Router, Reach Router and Next.js Link.
> 
> But when i try to use Chakra Link & Nextjs as follow.
> `<Link as={NextLink} href='/test'>About</Link>`
> 
> i get the following error in typescript
> `Type '{ children: string; as: (props: PropsWithChildren<LinkProps>) => DetailedReactHTMLElement<{ onMouseEnter?: (event: MouseEvent<Element, MouseEvent>) => void; onClick: (event: MouseEvent<...>) => void; href?: string; ref?: any; }, HTMLElement>; href: string; }' is not assignable to type 'Pick<PropsWithChildren<LinkProps>, "as" | "replace" | "scroll" | "shallow" | "passHref" | "prefetch" | "locale">'. Types of property 'as' are incompatible. Type '(props: PropsWithChildren<LinkProps>) => DetailedReactHTMLElement<{ onMouseEnter?: (event: MouseEvent<Element, MouseEvent>) => void; onClick: (event: MouseEvent<...>) => void; href?: string; ref?: any; }, HTMLElement>' is not assignable to type 'Url'. Type '(props: PropsWithChildren<LinkProps>) => DetailedReactHTMLElement<{ onMouseEnter?: (event: MouseEvent<Element, MouseEvent>) => void; onClick: (event: MouseEvent<...>) => void; href?: string; ref?: any; }, HTMLElement>' has no properties in common with type 'UrlObject'.`
> 
> any idea how i can fix this?

Do it this way 

```js
<NextLink href='/about' passHref>
	<Link>About</Link> 
</NextLink>
```

**Comment by ljosberinn** [comment]
@oahmaro nextjs link is a special case and in the original post is a link to an ExternalLink which integrates Chakras Link with next/link including all customization cases

**Comment by oahmaro** [comment]
Yes i saw the link in the original post, but i was confused i thought that chakra had implemented that in v1, in a way that i only have to pass the as prop and everything would work. shouldn't it be that way?

**Comment by ljosberinn** [comment]
No, that would make the `Link` component bound to next.js usage and it would be unusable with e.g. react-router-dom link then

**Comment by oahmaro** [comment]
This make's sense 👍🏻, regarding NextJS `Image` component, i am having difficulties integrating it with chakra, and i agree that it should be documented as well, but in the meantime do you happen to have any code example or post that would help me integrate it?

**Comment by franky47** [comment]
I have a preview integration of Next.js' Image with ChakraUI here:
- [Source code](https://github.com/47ng/chakra-next/blob/v3/src/components/image.tsx)
- [Tracking issue](https://github.com/47ng/chakra-next/issues/187)


However at the moment it has some issues:
- The markup rendered by Next.js is not a drop-in replacement for an `<img>` tag, which can lead to layout issues when using external CSS.
- The outermost div overrides its margin with inline styles, which makes it incompatible with Stack layouts, unless using a Chakra Box wrapper.

Example:
https://www.freecodecamp.org/news/how-to-build-a-recipe-app-with-nextjs/

**Comment by ljosberinn** [comment]
@oahmaro good news - we have plans to support this in the future :)

**Comment by chr-ge** [comment]
So is there currently a way to integrate Chakras Link with next/link using a `Link` within a `MenuItem`?
```js
<MenuItem as={NextLink} href={`/profile`} passHref>
    <Link>Edit</Link>
 </MenuItem>
```
This code throws an error: `React.Children.only expected to receive a single React element child.`

**Comment by asmockler** [comment]
For anyone like me winding up here trying to figure out how to get next links to work with chakra menus, this worked for me:

```jsx
<MenuList>
  <NextLink href="/settings" passHref>
    <MenuItem as={Link}>Settings</MenuItem>
  </NextLink>
</MenuList>
```

**Comment by adnene-guessoum** [comment]
thanks, @asmockler . I also faced a hydration issue that get solved with 'IsLazy' prop, if anyone is in trouble.

https://chakra-ui.com/docs/components/menu#lazily-mounting-menuitem
