### ISSUE TITLE
usePopper return type has wrong typings

### ISSUE THREAD

**Issue by asterikx** [chakra-ui/chakra-ui#2249]
# Bug report

## Describe the bug

Return type of `usePopper` hook has wrong (outdated?) typings, see the SandBox below.

## To reproduce

```
const { getReferenceProps, getPopperProps } = usePopper()
```

```
Property 'getReferenceProps' does not exist on type '{ popperInstance: Instance | null; reference: { ref: RefObject<HTMLButtonElement>; }; popper: { ref: RefObject<HTMLDivElement>; style: { ...; }; }; arrow: { ...; }; update: () => boolean; placement: Placement; place: Dispatch<...>; }'.
```

```
Property 'getPopperProps' does not exist on type '{ popperInstance: Instance | null; reference: { ref: RefObject<HTMLButtonElement>; }; popper: { ref: RefObject<HTMLDivElement>; style: { ...; }; }; arrow: { ...; }; update: () => boolean; placement: Placement; place: Dispatch<...>; }'.
```

## Minimal reproduction

- https://codesandbox.io/s/ecstatic-wilson-icfxr?file=/src/App.tsx

## Expected behavior

`getReferenceProps` and `getPopperProps` should exist.

## System information

- OS: macOS
- Browser (if applies): all
- Version of @chakra-ui/core: 1.0.0-rc.5
- Version of Node.js: 12.16.1

**Comment by ljosberinn** [comment]
The Popper integration has been reworked recently, but this isn't yet released. I'm confident typings align now too.

**Comment by asterikx** [comment]
You're right! I was looking at the `develop` branch (which includes the reworks)
