### ISSUE TITLE
[Image] Warning: Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by astahmer** [chakra-ui/chakra-ui#225]
**Steps to reproduce:**
Unmount Image component before the source image has loaded

The stack trace indicates that the error is on the line 14: 
```
image.onload = event => {
      setHasLoaded(true); // HERE
      onLoad && onLoad(event);
};
```
https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/Image/index.js

This should be fixed with a simple unmount check such as 
```
useEffect(() => {
  let didCancel = false;

  // ...
  return () => {
    didCancel = true;
  };
}, []);
```

**Comment by segunadebayo** [comment]
@astahmer, thanks for suggesting a fix. We'll try your suggestion.

You opt-out of this, for now, you can pass the `ignoreFallback` prop and set it to `false` so the image acts a pure `img` element.

**Comment by segunadebayo** [comment]
I believe the comment above solved your problem. If not, let me know so I can reopen this.

**Comment by gmathieu** [comment]
@segunadebayo the problem still persists. `useHasImageLoaded` is always called in compliance with React hook's rule ["Only Call Hooks at the Top Level"](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level). `ignoreFallback` simply changes the props passed to the image.

https://github.com/chakra-ui/chakra-ui/blob/1e842de357f115f154fc45c4d670747100417ad4/packages/chakra-ui/src/Image/index.js#L46-L52

@astahmer's solution seems like the easiest to implement. Alternatively, you can avoid side effects altogether with something like this:

```js
// warning: untested code
const ImageWithFallback = forwardRef(
  ({ src, fallbackSrc, onError, onLoad, ...props }, ref) => {
    const hasLoaded = useHasImageLoaded({ src, onLoad, onError });
    return <Box as={NativeImage} ref={ref} src={hasLoaded ? src : fallbackSrc} {...props} />;
  },
)

const Image = forwardRef(
  ({ fallbackSrc, ignoreFallback, ...props }, ref) => {
    if (ignoreFallback) {
      return <ImageWithFallback ref={ref} fallbackSrc={fallbackSrc} {...props} />;
    }
    return <Box as={NativeImage} ref={ref} {...props} />;
  },
);
```

Thanks for all your work
