### ISSUE TITLE
[Link] disabled prop & interaction behaviour

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#2255]
# Bug report

## Describe the bug

The `Link` component has default visuals for [`_disabled`](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/theme/src/components/link.ts#L13). However, the typings do not reflect that and interactions are not actually prevented.

## Expected behavior

I'd expect passing `disabled` to `Link` to prevent interactions and TypeScript not having issues with that.

- add `disabled?: boolean` to `LinkProps`
- add documentation for it via JSDoc
- adjust the props in the docs
- consider adding an example to the Link docs too
- all interactions (click, touch) have `event.preventDefault()` if `disabled`, otherwise execute `props.onClick` if present.

**Comment by jsefiani** [comment]
@ljosberinn You can assign it to me.

**Comment by jsefiani** [comment]
@ljosberinn In your bug report you mention all interactions, but what interactions exactly (as there are many)? 
This is a list that I found: https://stackoverflow.com/a/53356984/9764315?

**Comment by ljosberinn** [comment]
Touching a link on mobile should also not work when disabled; as well as middle-mouse-clicking & right-clicking because you could still "Open in new Tab`, outside of the common click itself.

**Comment by jsefiani** [comment]
@ljosberinn Why do you want me to cancel the event using `event.preventDefault()`? While I could use something like this:
`onClick={isDisabled ? () => false : onClick}`?

**Comment by ljosberinn** [comment]
I'm fairly confident that's the more canonical way of canceling an event alltogether

**Comment by jsefiani** [comment]
@ljosberinn Ow okay I see, thanks for mentioning!

**Comment by jsefiani** [comment]
Created a PR: https://github.com/chakra-ui/chakra-ui/pull/2260

**Comment by segunadebayo** [comment]
Hey guys,

Removing the `isDisabled` from the link component was intentional. Links are not buttons and shouldn't have `disabled` in them. We want to be careful not to invent anti-patterns.

The way to make a link non-interactive is to omit the `href` attribute.

Permit me to close this as well as the PR.

Thanks guys 💖

**Comment by ljosberinn** [comment]
Then we should probably remove the default styling for `_disabled`, shouldn't we?

**Comment by jsefiani** [comment]
@segunadebayo Thank you for your feedback. I would like to add the following:
- The `Link` component becomes indeed non-interactive under the hood if you omit the `href` attribute, but what about the styling? The `Link` component still gives me (wrong) feedback (hover state) when no `href` is provided.

**Comment by blentz100** [comment]
@jsefiani I'm having the same issue. Do you have any workarounds for modifying the hover state when there is no href?

**Comment by mizrab** [comment]
I am using Button as Nextjs Link and despite the button being disabled, it functions as it would normally. Are there any suitable workarounds for this?

**Comment by reminjp** [comment]
https://github.com/chakra-ui/chakra-ui/issues/2255#issuecomment-1648343990
> I am using Button as Nextjs Link and despite the button being disabled, it functions as it would normally. Are there any suitable workarounds for this?

I came here because I was facing the same problem.

According to this comment https://github.com/chakra-ui/chakra-ui/issues/2255#issuecomment-712927834, the workaround is to remove the `href` from props. By creating a component that wraps `Button` and using it, you can prevent forgetting to remove the `href`:

```ts
export const LinkButton = ({ href, ...props }) => {
  // or `as={NextLink}`
  return <Button as="a" href={props.isDisabled ? undefined : href} {...props} />
}
```
