### ISSUE TITLE
Named Colors don't work directly with "bg" prop

### ISSUE THREAD

**Issue by deadcoder0904** [chakra-ui/chakra-ui#226]
I am making **Habits** app with the following contents (generated through CRA) ⸺

## App.js

```js
import { Icon, Text, ThemeProvider } from '@chakra-ui/core'
import React from 'react'
import { Habit } from './components/Habit'

const App = () => (
  <ThemeProvider>
    <>
      <Text fontSize='4xl' textAlign='center'>
        Streaks App
      </Text>
      {/* <Habit
        name='Call Fam'
        streak='90'
        icon={<Icon name='phone' size='128px' />}
      /> */}
      {[...Array(9)].map((_, i) => (
        <Habit
          key={i}
          bg={i}
          name='Call Fam'
          streak='90'
          icon={<Icon name='phone' size='128px' />}
        />
      ))}
    </>
  </ThemeProvider>
)

export default App
```

## components/Habit.js

```js
import { Badge, Box, Flex, Text } from '@chakra-ui/core'
import React from 'react'

const colors = [
  'tomato',
  'lightpink',
  'yellowgreen',
  'yellow',
  'navajowhite',
  'antiquewhite',
  'aquamarine',
  'cornflowerblue',
  'red',
]

const randomNo = () => Math.floor(Math.random() * colors.length)

export const Habit = ({ bg, icon, name, streak }) => {
  const bgColor = colors[+bg] //colors[randomNo()]
  console.log({ bgColor, bg })
  return (
    <Flex
      key={bg}
      align='center'
      justify='center'
      direction='column'
      bg={bgColor}
      width='200px'
      height='200px'
      borderRadius='40px'
      margin='16px'
      padding='16px'
    >
      <Box>{icon}</Box>
      <Text fontWeight='bold' fontSize='2xl' textAlign='center'>
        {name}
        <Badge as='span' rounded='full' px='4'>
          {streak}
        </Badge>
      </Text>
    </Flex>
  )
}
```

And colors like `red`, `yellow` do not display directly but if I put `red.100`, `yellow.200` it does. Maybe you forgot to point out if nothing is specified then map `red` to `red.500`. I think this is what Tailwind does.

This is how it currently looks with the above code ⸺

![chakra-bug](https://user-images.githubusercontent.com/16436270/68085397-a16e7200-fe66-11e9-9f42-f560242f5a50.png)

Notice how the `yellow` & `red` does not have background color.

Thank you for this amazing UI framework. This is by far the fastest I've been productive with any UI kit :)

**Comment by segunadebayo** [comment]
Hi @deadcoder0904,

I'm aware of this issue and will look into it soon. The solution you proposed is definitely the route to go. For now, I'll add it to the docs as a "note" so others don't skip that.

Thank you for your comment on Chakra UI. I'm glad it has improved your productivity.
