### ISSUE TITLE
Chakra UI unwillingly being added to storybook?

### ISSUE THREAD

**Issue by hems** [chakra-ui/chakra-ui#2263]
# Bug report

## Describe the bug

Chakra UI is being added to storybook automatically and is generating errors on the console

![image](https://user-images.githubusercontent.com/27327/96362764-86ece180-1127-11eb-9c41-bdfd39dccb72.png)

Also an error on the left bar:

![image](https://user-images.githubusercontent.com/27327/96362771-8ce2c280-1127-11eb-9322-9254cbfbb47b.png)

## To reproduce

Created a storybook for my app, here is the file structure:

```bash
├── .babelrc
├── .eslintrc.json
├── .git
├── .gitignore
├── jest.config.js
├── jest.tsconfig.json
├── .next
├── next.config.js
├── next-env.d.ts
├── node_modules
├── package.json
├── .prettierignore
├── .prettierrc.js
├── public
├── README.md
├── src
├── .storybook
├── tsconfig.json
└── yarn.lock
````

## Minimal reproduction

Just created a standard storybook

#.storybook/main.js
````js
module.exports = {
  stories: ['../src/**/*.stories.@(js|ts|jsx|tsx|mdx)'],
  addons: [
    '@storybook/addon-essentials',
    'storybook-addon-styled-component-theme/dist/register'
  ]
}
````

#.storybook/webpack.config.js
````js
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

module.exports = ({ config }) => {
  config.module.rules.push({
    test: /\.(ts|tsx)$/,
    loader: require.resolve('babel-loader'),
    options: {
      presets: [require.resolve('babel-preset-react-app')],
    },
  });

  config.resolve.extensions.push('.ts', '.tsx', 'js', 'jsx');

  config.resolve.plugins.push(
    new TsconfigPathsPlugin({
      extensions: ['.ts', '.tsx', '.js', '.jsx']
    })
  )
  
  return config;
};
````

## Expected behavior

Chakra-ui to not load on Storybook or to load without any errors.

## System information

- OS: Linux
- Browser (if applies): Chrome
- Version of 1.0.0-rc.5
- Version of Node.js: 14.12

**Comment by with-heart** [comment]
This is a storybook feature called Storybook Composition. You can disable it by following this part of their docs: https://storybook.js.org/docs/react/workflows/package-composition#configuring

The errors occur because our published storybook url is still for v0. The issues should automatically resolve once we fully publish 1.0!

**Comment by hems** [comment]
> This is a storybook feature called Storybook Composition. You can disable it by following this part of their docs: https://storybook.js.org/docs/react/workflows/package-composition#configuring

Thanks for pointing it out, unfortunately that turned out to break my storybook.

Maybe they changed the way of disabling it, i'll keep grinding here until i managed to fix it.

this is my main.js file:

```js
module.exports = {
  stories: ['../src/**/*.stories.@(js|ts|jsx|tsx|mdx)'],
  addons: [
    '@storybook/addon-essentials',
    'storybook-addon-styled-component-theme/dist/register'
  ],
  refs: {
    '@chakra-ui/core': {
      disable: true
    } 
  }
}
````

This is the error i get, using `"@storybook/react": "^6.0.26"` 

````bash
ERR! TypeError: Cannot read property 'replace' of undefined
ERR!     at stripTrailingSlash (.../node_modules/@storybook/core/dist/server/manager/manager-config.js:93:14)
ERR!     at .../node_modules/@storybook/core/dist/server/manager/manager-config.js:147:14
ERR!     at Array.forEach (<anonymous>)
ERR!     at getManagerWebpackConfig (.../node_modules/@storybook/core/dist/server/manager/manager-config.js:132:33)
ERR!  TypeError: Cannot read property 'replace' of undefined
ERR!     at stripTrailingSlash (.../node_modules/@storybook/core/dist/server/manager/manager-config.js:93:14)
ERR!     at .../node_modules/@storybook/core/dist/server/manager/manager-config.js:147:14
ERR!     at Array.forEach (<anonymous>)
ERR!     at getManagerWebpackConfig (/home/hz/Documents/git/aluna/aluna-next/node_modules/@storybook/core/dist/server/manager/manager-config.js:132:33)
````


> The errors occur because our published storybook url is still for v0. The issues should automatically resolve once we fully publish 1.0!

OK, nice!

It would be fun to see Chakra UI storybook side by side with my own Storybook, looking forward to that ( :

**Comment by with-heart** [comment]
I'm actually gonna leave this open just to make sure we follow up and verify that it's working post-v1 😊 Not sure about the errors coming from storybook itself though. Might be worth opening an issue on their repo and linking it with this one.

**Comment by hems** [comment]
> I'm actually gonna leave this open just to make sure we follow up and verify that it's working post-v1  Not sure about the errors coming from storybook itself though. Might be worth opening an issue on their repo and linking it with this one.

actually this worked now, turns out i had written "disable" instead of "disabled" !

**Comment by futhr** [comment]
`@storybook/react v6.1.15`
 `@chakra-ui/react v1.1.6`

```js
module.exports = {
  ...
  refs: {
    '@chakra-ui/react': {
      disable: true,
    },
  },
}

**Comment by bhardy** [comment]
For posterity, ours needed:

```
module.exports = {
  ...
  refs: {
    '@chakra-ui': {
      disable: true,
    },
  },
}
```

**Comment by jonparkdev** [comment]
@with-heart Out of curiosity, is it possible to somehow apply my custom Chakra-UI theme to the Chakra storybook the is being composed in my own storybook

**Comment by Ahavaz** [comment]
> @with-heart Out of curiosity, is it possible to somehow apply my custom Chakra-UI theme to the Chakra storybook the is being composed in my own storybook 

You can find the documentation for that [here](https://chakra-ui.com/getting-started/with-storybook)
