### ISSUE TITLE
Add a search to documentation

### ISSUE THREAD

**Issue by kellvembarbosa** [chakra-ui/chakra-ui#2264]
# Feature request
Add a search to documentation

## Is your feature request related to a problem? Please describe.

Sometimes I know the component I want, but I want to see attributes or examples and it would be easier with the search...

## Describe the solution you'd like

Add search to documentation

## Additional context

A search is missing to facilitate and find information.
Yesterday I was showing the chakra to a friend, but I was lost in the doc and a search would have saved several minutes already ... Outside it would be +1 chakra user ...

**Comment by ljosberinn** [comment]
Agreed! However v1 docs aren't finished yet, the search bar will definitely return, but iirc we cannot enable it while having v0.8 docs still active.

**Comment by with-heart** [comment]
@segunadebayo I think we need to investigate Algolia a little more. If we had more than just the api key that we've been using, we should be able to configure multiple sites at one time. We can also apply as an open source project here: https://www.algolia.com/for-open-source/

**Comment by chrisehlee** [comment]
@with-heart ... what about this https://docsearch.algolia.com/apply/

**Comment by kellvembarbosa** [comment]
@ljosberinn Search for version 1.0 documentation still to be added
