### ISSUE TITLE
[Modal] react-beautiful-dnd doesn't work on modal component

### ISSUE THREAD

**Issue by plumsirawit** [chakra-ui/chakra-ui#2266]
# Bug report

## Describe the bug

The situation is from placing react-beautiful-dnd `DragDropContext` inside a chakra-ui `Modal`.
The bug is that after drag and drop, the modal close itself unexpectedly.

## To reproduce

1. Go to [my personal site showing this bug](https://chakra-modal-react-beautiful-dnd.plummmm.com/)
2. Click on 'Open Modal'
3. Drag n drop any item in the list. (It might seem like plain text due to bad & quick UI, but you can drag and drop them, actually.)
4. See the problem: the modal closes itself after dropping.

## Minimal reproduction

The GitHub repo I use to host the site is [here](https://github.com/plumsirawit/chakra-modal-react-beautiful-dnd).

## Expected behavior

When dragging & dropping objects, the modal should persist itself opened.

## Screenshots

(Hard to provide screenshots, need to interact with drag and drop)

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of @chakra-ui/core: 0.8.0
- Version of Node.js: 12.15.0

## Additional context

none

**Comment by dodas** [comment]
It is advised that you place`<DragDropContext>` at the root of your application, see [`<DragDropContext>` docs](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/drag-drop-context.md).

In your case, [right here](https://github.com/plumsirawit/chakra-modal-react-beautiful-dnd/blob/master/src/index.tsx#L10) (doesn't matter if it is outside, or inside Chakra's provider.

**Comment by kodgurkini** [comment]
Had the same problem and I solved it by setting closeOnOverlayClick on the modal to false. This prevents the modal from closing when you drop the item.

If you still want to have the behaviour of closing the modal by clicking on the overlay you can set a flag in onDragStart or BeforeDragStart method and change it back in onDragEnd. Then use the flag to change closeOnOverlayClick dynamically  depending on if the items is in "the air" or not.

**Comment by with-heart** [comment]
Hi @plumsirawit! This issue has been fixed in Chakra v1: https://codesandbox.io/s/cool-snyder-pp19m?file=/src/index.tsx

Check out our [Getting Started doc](https://chakra-ui.com/docs/getting-started) for installing v1 or our [Migration doc](https://chakra-ui.com/docs/migration) for migrating from a v0 project.
