### ISSUE TITLE
[AccordionButton] needs type="button"

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#2267]
# Bug report

## Describe the bug

Technically #98 but that one's fairly outdated. Having an `Accordion` within a form submits the form as the default type for `button` within a `form` implicitly is `submit`.

## Expected behavior

Clicking `AccordionButton` within a form should not submit the form.

## Proposed changes

Adding `type="button"` before the spreading of `buttonProps` [here](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/accordion/src/accordion.tsx#L157) should solve it. If `buttonProps` overrides it, move it below and make it prop-agnostic so users can override `type` should they want to.

**Comment by segunadebayo** [comment]
Fixed!
