### ISSUE TITLE
InputGroup has styling issues with custom chakra Input components

### ISSUE THREAD

**Issue by recursiveElk** [chakra-ui/chakra-ui#2269]
# Bug report

## Describe the bug

When trying to extend Input, InputGroup and InputLeftElement according to the strategy specified in: https://next.chakra-ui.com/guides/as-prop InputGroup causes styling issues within Input.

## To reproduce

1. Extend Input/ InputGroup with forwardRef.
Sandbox below shows a comparison between native components and a stripped back extension of those components.

## Minimal reproduction

https://codesandbox.io/s/cool-water-jh4dg?file=/src/index.js

## Expected behavior

No padding overlap/issue when using InputLeftElement in conjunction with Input and InputGroup for extended components.

## Screenshots

n/a

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of @chakra-ui/core: [1.0.0-rc.5]
- Version of Node.js: [e.g. 12.11.1]

**Comment by segunadebayo** [comment]
Hi @recursiveElk,

Based on our internal implementation, you need to add an `id` static property to the **Input**, **InputLeftElmeent**, and **InputRightElement**, components for `InputGroup` to work correctly.

Here's an example: https://codesandbox.io/s/boring-jang-0um95?file=/src/custom.tsx.

Code:

```jsx
export const CustomInput = forwardRef<InputProps, "input">(
  (props: InputProps, ref) => {
    return <ChakraInput ref={ref} {...props} />;
  }
);

CustomInput.id = "Input";

// tslint:disable-next-line: no-empty-interface
export interface InputElementProps extends ChakraInputElementProps {}

export const CustomInputLeftElement = forwardRef<InputElementProps, "div">(
  (props: InputElementProps, ref) => {
    return <ChakraInputLeftElement ref={ref} {...props} />;
  }
);

CustomInputLeftElement.id = "InputLeftElement";

export const CustomInputRightElement = forwardRef<InputElementProps, "div">(
  (props: InputElementProps, ref) => {
    return <ChakraInputRightElement ref={ref} {...props} />;
  }
);

CustomInputRightElement.id = "InputRightElement";
```

Hope this helps.

Cheers.

**Comment by recursiveElk** [comment]
Ah i see, thanks for pointing that out!

**Comment by focux** [comment]
I just ran into this issue, would be good if this information could be added to the docs, I tried to find it and didn't see it. Thank you anyways.

**Comment by dromback** [comment]
> 

How did you fix this? I can't seem to fix this problem. I use InputGroup for my search bar and it's on top of everything when I scroll.

**Comment by Coding-Maniac** [comment]
@segunadebayo Can you kindly update the code sandbox link. It doesn't seem to be working anymore

**Comment by effectivetom** [comment]
Just dropping a note here to clarify something for people who have only wrapped `Input` in their codebase, and not the other components.

If you're still using `InputGroup`, `InputLeftElement` and `InputRightElement` directly from `@chakra-ui/react`, you can fix this issue with one line in your wrapped `Input` component.

Here's my wrapped input as an example

```typescript
import type { InputProps as ChakraInputProps } from '@chakra-ui/react'
import { forwardRef, Input as ChakraInput } from '@chakra-ui/react'

export const Input = forwardRef(({ ...props }: ChakraInputProps, ref) => {
  return <ChakraInput ref={ref} autoComplete="off" {...props} />
})

// This line is all you need to add in order to fix the positioning issue
Input.id = 'Input'
```
