### ISSUE TITLE
Hide Button while using IconButton

### ISSUE THREAD

**Issue by deadcoder0904** [chakra-ui/chakra-ui#227]
I want to display Icon & allow it to be clickable which is why I need the `IconButton` component.

The problem comes when I need to show only icon but hide the button and I'm unable to do that.

Here's the contents of my `IconButton` ⸺

```js
import { Flex, IconButton } from '@chakra-ui/core'
import React from 'react'

export const CreateHabit = () => (
  <Flex
    width='220px'
    height='220px'
    borderRadius='40px'
    margin='0 16px'
    padding='0 16px'
    justify='center'
    flexWrap='wrap'
  >
    <IconButton
      onClick={() => alert('click')}
      icon='add'
      variant='unstyled'
      fontSize='300px'
    />
  </Flex>
)
```

And right now you can see how it looks ⸺

![chakra-ui-bug](https://user-images.githubusercontent.com/16436270/68087263-fff11b80-fe79-11e9-9f78-b5315d4b4717.png)

Notice the button's outline above the add icon. I want to hide the button completely so that my icon will move up a bit in alignment :)

**Comment by deadcoder0904** [comment]
I found a workaround by adding `display="contents"` to `IconButton` like

```js
<IconButton
      display='contents'
      onClick={() => alert('click')}
      icon='add'
      variant='unstyled'
      fontSize='300px'
    />
```

Not sure if I should keep this open?

**Comment by segunadebayo** [comment]
Thanks and I'm glad you found a walkaround. We'll add an `unstyled` variant for the Button and IconButton so this use case can be permanently resolved.

I'll close it for now.

**Comment by deadcoder0904** [comment]
Hey, @segunadebayo there is one issue I found with this approach. I can't tab around the + icon.

Might wanna re-open this one as I think it's required for a11y although I'm not sure since Idk much about a11y.

**Comment by deadcoder0904** [comment]
I changed the `IconButton` to `Icon` & it works ⸺

```js
<Icon
        name='small-add'
        onClick={onOpen}
        fontSize='300px'
        cursor='pointer'
      />
```

But still, it cannot be tabbed as I guess because it's an icon. But I do think it is required for a11y projects. 

This is just a demo project so it doesn't matter that much but I do think it's a valid problem.

**Comment by segunadebayo** [comment]
@deadcoder0904, why not try this:

```jsx
 <IconButton
      height="auto"
      onClick={() => alert('click')}
      icon='add'
      variant='unstyled'
      fontSize='300px'
  />
```

**Comment by deadcoder0904** [comment]
It works but it pushes the icon below

![streaks app](https://user-images.githubusercontent.com/16436270/68205163-95fa8280-ffef-11e9-91a1-036e666d05e5.png)

I uploaded the code → https://github.com/deadcoder0904/streaks-app

**Comment by segunadebayo** [comment]
I'd suggest you use the `PseudoBox` component to create that button.

```jsx
<PseudoBox as="button" onClick={...}><Icon name="add"/></PseudoBox>
```

Let me know if this helps. If not, I'll re-open the issue

**Comment by bawahakim** [comment]
For those still looking for a way to work with ally/tab 
```
                 <IconButton
                        aria-label="Share Program"
                        icon={<LinkIcon boxSize={6} color="gray.400" />}
                        onClick={invitePeopleDisclosure.onOpen}
                        w="fit-content"
                        variant="ghost"
                      />
```

The secret is the variant and the `fit-content`
