### ISSUE TITLE
1.0.0-rc.5 -  property translate is required on button ?

### ISSUE THREAD

**Issue by hems** [chakra-ui/chakra-ui#2274]
# Bug report

## Describe the bug

Property translate is being marked as required on typescript?

## To reproduce

Implement this simple Button:

![image](https://user-images.githubusercontent.com/27327/96580935-f5b96e80-12d0-11eb-8631-d72178741e9f.png)

## Expected behavior

Property translate should not be required?

**Comment by ljosberinn** [comment]
Which version are you on? This doesn't happen on the latest RC.

**Comment by hems** [comment]
> Which version are you on? This doesn't happen on the latest RC: https://codesandbox.io/s/clever-leavitt-vvm8j?file=/src/App.tsx

Indeed, it doesn't happen on the sandbox.

I deleted my `node_modules`, updated my package.json to use exactly same package versions ( i was already using 1.0.0-rc.5, just updated react and react-dom), as it still happens in this project.

```json
    "@chakra-ui/core": "^1.0.0-rc.5",
    "react": "17.0.0-rc.2",
    "react-dom": "17.0.0-rc.2",
    "typescript": "^4.0.3"
```

I'll investigate furthre

**Comment by ljosberinn** [comment]
Did you also reload whichever editor you're using? After reinstalling, VSCode e.g. needs to `Restart TS Server`. Alternatively, an editor reboot in general should work. In WebStorm, you may have to invalidate the cache.

**Comment by hems** [comment]
> Did you also reload whichever editor you're using? After reinstalling, VSCode e.g. needs to `Restart TS Server`. Alternatively, an editor reboot in general should work. In WebStorm, you may have to invalidate the cache.

restarted and still got the same issue. pretty weird

![image](https://user-images.githubusercontent.com/27327/96587603-72047f80-12da-11eb-8b4e-ab7c9e328b39.png)

**Comment by hems** [comment]
fixed by updating version of `@types/react` and `@types/react-dom`

**Comment by ljosberinn** [comment]
Ahhh sorry we had that issue some time ago, yes. iirc `@types/react` published a faulty version at some point.
