### ISSUE TITLE
useColorMode returns wrong value

### ISSUE THREAD

**Issue by hesxenon** [chakra-ui/chakra-ui#2275]
# Bug report

## Describe the bug

useColorMode returns the value for `'dark'` even though light is set in the `initialColorMode` property in the theme object

## To reproduce

I am not sure how to reproduce this without sharing the entiry private codebase for now. Going through the usage of chakra it seems pretty standard, just the `ChakraProvider` with the theme object that contains a config property and so on. From chakras side it seems to be okay as well, but when I debug the code `useColorMode()` in `useColorModeValue` returns an object with `colorMode: ''`. Not sure how this would be possible in theory as I'm not that familiar with chakras code.

## Additional context

It seems to me that the check `colorMode === "light" ? light : dark` should rather be flipped, i.e. `dark` is the special case? Of course, this is opinionated.

**Comment by ljosberinn** [comment]
is this maybe related to #2106? could you check what value `colorMode` is after the initial render?

**Comment by hesxenon** [comment]
the colormode is set to `''` after the second render. Not sure why the app renders 6 times (might be a mistake on my side, still investigating) but for the first two renders it's correctly set to `'light'` and then it becomes `''`. I wanted to look at the storage manager soon, did you find something noteworthy there?

**Comment by ljosberinn** [comment]
ah yeah then its the issue described in #2106 and fixed, but unreleased yet. you can fix it if you do this until the next release:

```js
function ColorModeFix() {
  const { colorMode, toggleColorMode } = useColorMode();

  useEffect(() => {
    if(colorMode === '') {
       toggleColorMode();
    }
  }, [colorMode])

  return null;
}
```
and rendering that component once below `ChakraProvider`.
