### ISSUE TITLE
Using Link in gatsby doesn't work properly, page flashes

### ISSUE THREAD

**Issue by theskillwithin** [chakra-ui/chakra-ui#2278]
expect client side routing to work

result is that page reloads causing a flash

https://codesandbox.io/s/github/DropInBlog/gatsby-starter

reproduction: 
go to codesandbox

switch back and forth between authors and home page

you will notice that the image in the header reloads when it should not

**Comment by segunadebayo** [comment]
Hi @theskillwithin,

This is due to the internal `setState` logic in the `Image` component. It's not compatible with the SSR in Next.js and Gatsby. I'd recommend you do `<Box as="img" />` as a temp. walkaround.

We've exported an `Img` component in the upcoming V1 release to handle this walkaround.
