### ISSUE TITLE
[Stack] No spacing when using fragments

### ISSUE THREAD

**Issue by astahmer** [chakra-ui/chakra-ui#228]
This is more a question than a bug actually but it would be nice to see it solved somehow :

**Steps to reproduce :**
Use a Fragment inside a Stack (same logic applies to ButtonGroup as well)

Like: 
```
<Stack ...">
    <Fragment>
        <Box ... />
        <Box ... />
        <Box ... />
    </Fragment>
    <Box ... />
    <Box ... />
    <Box ... />
</Stack>
```

The elements inside the Fragment will not receive appropriate spacing props while others will.
It seems to me this is a known behavior, since React doc clearly specify that [here](https://reactjs.org/docs/react-api.html#reactchildrenmap)

> If children is a Fragment it will be treated as a single child and not traversed.

My use case was having a conditional rendering around 2 buttons that should be in a group.
I'm still kinda new to React so right now I don't have any solution to suggest.
Do you think that would be somehow solvable ?

Right now my solution was to use another Stack instead of using a Fragment, but it does not feel 100% clean to me.

**Comment by segunadebayo** [comment]
Hi @astahmer,

You can use the `shouldWrapChildren` prop to solve this use-case. If passed, the Stack component will wrap its children with a `Box`.

**Comment by segunadebayo** [comment]
@astahmer We've now resolved this by using `css` to manage the stack spacing rather than react `cloneElement`.  It lands in the next release.

**Comment by tbathat** [comment]
I got through something similiar.

I created a ButtonGroup to manage 3 buttons, and it is a component which is being rendered in a another component wrapped by a Flex father component.

Unfortunately I'm not succesfull in applying spacing between those 3 buttons directly on ButtonGroup. 

I actually tried few things and dont know how to solve it using chakra-ui lib.
