### ISSUE TITLE
[Checkbox] Checkbox onChange not called from within CheckboxGroup

### ISSUE THREAD

**Issue by konahart** [chakra-ui/chakra-ui#2280]
# Bug report

## Describe the bug

If a Checkbox is the child of a CheckboxGroup, the Checkbox's onChange prop does not get called when the state of the checkbox changes. This is true whether or not the containing CheckboxGroup has its own onChange prop.

## To reproduce

1. Create a `<CheckboxGroup>` component
1. Create a child `<Checkbox />` with an `onChange` prop
e.g., `<Checkbox onChange={() => console.log('hello world')} />`
2. Click on the checkbox
3. See error: `onChange` does not get called 
e.g., no "hello world" in console

## Expected behavior

Checkbox's onChange function should be called when Checkbox's state changes.

## Minimal reproduction

Chakra 1.0.0-rc.2: [https://codesandbox.io/s/tender-microservice-d6n5b](https://codesandbox.io/s/tender-microservice-d6n5b)

[Works as expected] Chakra 0.8.0: [https://codesandbox.io/s/sharp-fog-nesbv](https://codesandbox.io/s/sharp-fog-nesbv)

## Additional context

This is a change in behavior from previous versions of Chakra. In 0.8.0, both Checkbox and CheckboxGroup onChange functions would be called then the Checkbox's state changed. This could be useful for tracking which checkbox changed most recently without having to compare CheckboxGroup's current value array with previous value array, and more generally allowing Checkboxes to have different behaviors.

If this change in behavior is an intentional change from previous versions, it should be added to the "Upgrade to Chakra v1" documentation. It would also be good for the Checkbox component documentation to explain the difference in behavior when Checkbox belongs to a CheckboxGroup. Currently the override of Checkbox's onChange is unmentioned.

If this change is not intentional, I am happy to take a shot at a PR for restoring the previous functionality.

**Comment by segunadebayo** [comment]
Thanks for reporting this @konahart.

I've just pushed a fix for it in v1.
