### ISSUE TITLE
Upgrade to v1

### ISSUE THREAD

**Issue by ahmdtalat** [chakra-ui/chakra-ui#2283]
# Bug report

## Describe the bug

Hello, I have an issue with my custom breakpoints, When I try to override the default breakpoints, nothing changes and it's solved in V1 but a lot of breaking changes, so I think it's a better idea to stick with v0.8. Is there a chance to fix this in V 0.8?

## Expected behavior

I expect to see a min-width query with the custom breakpoints that I defined
![image](https://user-images.githubusercontent.com/46477493/96720777-7d73ab80-13ab-11eb-8c48-5b29f304dc9e.png)

Actual behavior
![image](https://user-images.githubusercontent.com/46477493/96720828-8fede500-13ab-11eb-8ce8-9785105bcd38.png)

**Comment by ljosberinn** [comment]
What are you referring to in regards of "lots of breaking changes"? Most, except for the singular usage of the providers, can be resolved via find-replace functionality of your editor:
- `PseudoBox` -> `Box`
- `size=` to `boxSize=`
- `variantColor=` to `colorScheme=`

I don't have the last word to say on it but I highly doubt v0 will receive an update.

**Comment by ahmdtalat** [comment]
Fixing ModalOverlay and the Drawer overflow is not that easy.

**Comment by ljosberinn** [comment]
Are you referring to this? https://github.com/chakra-ui/chakra-ui/issues/2060#issuecomment-713554196

**Comment by ahmdtalat** [comment]
I'm not sure, but with ModalContent I get height=100vh although I'm not using full modal size.

**Comment by ljosberinn** [comment]
I'm afraid I'm not following. Could you create a sandbox to show what you mean, precisely? Generally I'd heavily recommend upgrading to v1 whenever time is available. it's very close to release and better than v0 in every way.

**Comment by segunadebayo** [comment]
I'm sorry but I don't understand the problem you are reporting with the v1 upgrade. Kindly go through the migration guide: https://next.chakra-ui.com/docs/migration

Please provide a repository or CodeSandbox reproducing any problems, and describe the difference between the expected and current behavior.
