### ISSUE TITLE
Link to the default theme in the documentation gives 404

### ISSUE THREAD

**Issue by iamsaumya** [chakra-ui/chakra-ui#2285]
# Bug report

## Describe the bug

Link to the default theme in the documentation gives 404. 

## To reproduce

1. Go to [this](https://chakra-ui.com/theme).
2. Scroll down to Colors section.
4. Click on 'default theme' link that is below the sample code for colors palette. 

## Expected behaviour

I am not sure about the expected behaviour. A link to 404 page in the official documentation appears to be good enough reason to create an issue!

## System information

Independent of system. 

Thanks!

**Comment by ljosberinn** [comment]
This is a sideeffect of v1; master by now holds v1 and thus, v0.8 is in a separate branch. [Here](https://github.com/chakra-ui/chakra-ui/blob/v0/packages/chakra-ui/src/theme/theme.js) is the correct folder.
