### ISSUE TITLE
[useBreakpoint]: mediaQuery.addEventListener is not a function.

### ISSUE THREAD

**Issue by omarkhatibco** [chakra-ui/chakra-ui#2286]
# Bug report

## Describe the bug

on IOS 13, it seems there is no `addEventListener` on matchMedia function just the old one `addListener`,

## To reproduce

just use this hook on IOS 13

## Expected behavior

should be polyfilled or provide a use the  old function `addListener` as it has wider support for now.

## Screenshots

![Screenshot 2020-10-22 at 11 26 30](https://user-images.githubusercontent.com/9054278/96852837-ee719c80-1459-11eb-978c-fb483ff49e04.png)

## System information

- OS: [e.g. macOS, Windows] IOS 13.7
- Browser (if applies): Safari 13.7
- Version of @chakra-ui/core: 1.0.0-rc.5
- Version of Node.js: v12

**Comment by ljosberinn** [comment]
see #2117, fixed but unreleased
