### ISSUE TITLE
Toast Example

### ISSUE THREAD

**Issue by ColbyWTaylor** [chakra-ui/chakra-ui#229]
Hi! First- Chakra is very cool - thank you for all your work :)

I'm trying to use toast but receiving no actual popup when I click. I've been able to use many of the other feature but not this- is there a trick to getting it to function? At the very least the app isn't crashing.. Thank you for you help!

**Comment by segunadebayo** [comment]
Hi @ColbyWTaylor,

Can you send a CodeSandbox link so I can look at your code and figure out what's wrong? There are tricks to use the Toast hook 😄.

**Comment by segunadebayo** [comment]
I'm going to close this for now. Let me know if there are still issues, and I can re-open this.
