### ISSUE TITLE
[Docs] AlertDialog - Adding Transitions example broken

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#2292]
linking to the deploy of my PR since the snapshots aren't fixed on develop yet
the error is:

![image](https://user-images.githubusercontent.com/29307652/96917339-16d4b780-14a9-11eb-9764-591b7fa0fff4.png)

which is probably due to the migration to framer

https://chakra-ui-j487j8uza.vercel.app/docs/overlay/alert-dialog#adding-transitions

**Comment by ljosberinn** [comment]
Collapse docs link to 404, probably because it got moved into the transition package

**Comment by ljosberinn** [comment]
<Link breakout in the Airbnb example is not working, unsure if its broken or just not properly forwarded

![image](https://user-images.githubusercontent.com/29307652/96917881-b98d3600-14a9-11eb-833c-137fcc170cc1.png)

**Comment by segunadebayo** [comment]
Thanks for catching this @ljosberinn. Just pushed a fix.
