### ISSUE TITLE
useBreakpointValue crashes app on mobile Safari ?

### ISSUE THREAD

**Issue by hems** [chakra-ui/chakra-ui#2293]
# Bug report

## Describe the bug

I need to have breakpoint based values for the `size` propety on a Drawer and since responsive properties aren't available for the `size` on `Drawer` ( [featured requested here in this issue ](https://github.com/chakra-ui/chakra-ui/issues/1028) ) i decided to use `useBreakPointValue`, but turns out it's breaking my application on mobile with this error:

`TypeError: mediaQuery.addEventListener is not a function. ( in 'mediaQuery.addEventlistener("change", handleChange), 'mediaQuery.addEventListener' is undefined)`

It does work well on the desktop browser tough.

## To reproduce

 - install `chakra-ui` 1.0.0-rc.5.
 - add `useBreakPointValue` inside of a component
 - open website on safari mobile, i'm using iOS 13.4.1

```tsx
const size = useBreakpointValue({ base: 'full', sm: 'xs' })
```

## Screenshots

![image](https://user-images.githubusercontent.com/27327/96921538-9745e900-14a6-11eb-84b4-4a01e1750ae6.png)

## System information

- OS: iOS 13.3.1

**Comment by ljosberinn** [comment]
see #2117, fixed but unreleased

**Comment by hems** [comment]
> see #2117, fixed but unreleased

Do you know a workaround in order to point to an specific git commit instead of a release version?

is there a way of using a @chakra/core `nightly version` ?

I think it's only possible if you would commit the built files for each commit ?

**Comment by ljosberinn** [comment]
Someone patched Chakra with the `patch-package` tool over [here](https://github.com/chakra-ui/chakra-ui/issues/712#issuecomment-712332346) but it's a different issue - you might be able to work around that. Else I'm afraid you can only use the fix locally.

**Comment by hems** [comment]
> Someone patched Chakra with the `patch-package` tool over [here](https://github.com/chakra-ui/chakra-ui/issues/712#issuecomment-712332346) but it's a different issue - you might be able to work around that. Else I'm afraid you can only use the fix locally.

thank you once agian for such quick answer.

I'm wondering what i would need to do in case i would like to push the latest compile version of chakra-ui to my own github so then i could reference it on package.json insetad of using the latest version published on npm?

Have you guys considered having some script to publish the nightly version on a github repository?

thank you once again for such good support.

**Comment by ljosberinn** [comment]
We released `rc.7` yesterday (ignore `rc.6`, there were dependency issues) which should have fixed this.

This release looks quite solid so it might very well be the last rc before release. :) However, should we see some functionality crashing we'll push out a release as soon as we have a fix for that!

**Comment by hems** [comment]
> We released `rc.7` yesterday (ignore `rc.6`, there were dependency issues) which should have fixed this.
> 
> This release looks quite solid so it might very well be the last rc before release. :) However, should we see some functionality crashing we'll push out a release as soon as we have a fix for that!

Yes, i found it out this morning, i'm using rc.7 for a few hours already, and it feels great!

Also, currently i downloaded `packages/theme` entirely into my project and i'm customising those files instead of using `extendTheme`, i feel this way i can learn / navigate them earier.

Because of that i had to update my `modal` and `drawer` file to match the main repo otherwise it was not opening on correct size.

I probably have to do that to entire `theme` or stop copying the files and exclusively use `extendTheme` to create my own variations of components.

**Comment by ljosberinn** [comment]
Did you happen to [see this](https://next.chakra-ui.com/docs/theming/customize-theme#scaling-out-your-project)? MIght help organizing your theme more, the docs just illustrate using inline `extendTheme({...huge object here })` for the sake of brevity.

**Comment by hems** [comment]
> Did you happen to [see this](https://next.chakra-ui.com/docs/theming/customize-theme#scaling-out-your-project)? MIght help organizing your theme more, the docs just illustrate using inline `extendTheme({...huge object here })` for the sake of brevity.

Yes, i did see that! Thanks for linking. 

Since it's my first project using chakra i decided to download the `theme` pack to understand a bit more how the theme is implemented and hopefully keep the same standards.

then later i believe i should move into using `extendTheme` and only do what's needed, but at this stage i believe i'm still figuring out how it works and it's very interesting to read the default implementation.
