### ISSUE TITLE
TypeScript build error in rc.{3-5}

### ISSUE THREAD

**Issue by joelgallant** [chakra-ui/chakra-ui#2294]
# Bug report

## Describe the bug
Using TypeScript with strict mode on, this internal error comes up.

```
node_modules/@chakra-ui/system/dist/types/forward-ref.d.ts:10:186 - error TS2344: Type 'T' does not satisfy the constraint '"symbol" | "object" | "button" | "meter" | "textarea" | "style" | "progress" | "text" | "ruby" | "table" | "small" | "sub" | "circle" | "embed" | "pre" | "caption" | "menu" | "menuitem" | ... 158 more ... | (new (props: any) => Component<...>)'.
  Type 'As' is not assignable to type '"symbol" | "object" | "button" | "meter" | "textarea" | "style" | "progress" | "text" | "ruby" | "table" | "small" | "sub" | "circle" | "embed" | "pre" | "caption" | "menu" | "menuitem" | ... 158 more ... | (new (props: any) => Component<...>)'.
    Type 'string' is not assignable to type '"symbol" | "object" | "button" | "meter" | "textarea" | "style" | "progress" | "text" | "ruby" | "table" | "small" | "sub" | "circle" | "embed" | "pre" | "caption" | "menu" | "menuitem" | ... 158 more ... | (new (props: any) => Component<...>)'.
      Type 'T' is not assignable to type '"view"'.
        Type 'As' is not assignable to type '"view"'.
          Type 'string' is not assignable to type '"view"'.

10 declare type PropsOf<T extends As> = T extends React.ComponentClass<infer P> ? React.PropsWithoutRef<P> & React.RefAttributes<InstanceType<T>> : React.PropsWithRef<React.ComponentProps<T>>;
```

**Comment by ljosberinn** [comment]
iirc this is because of an outdated `@types/react` package, would you mind upgrading to the latest, removing node_modules and lockfile and reinstall? I'm building my site with strict mode and chakra too, no issues there.

**Comment by joelgallant** [comment]
Thanks for the quick response. I am using react types `16.9.53`, which it looks like is the latest. Tried reinstalling but no luck. Is that the same as https://github.com/chakra-ui/chakra-ui/issues/2274? They look on surface level to be different problems.

**Comment by ljosberinn** [comment]
It should be, hence the initial comment. Just to be sure, did you remove the lockfile and reinstall then? Because without that, you'll just reinstall what you previously had. 

Regardless, do you see this error just randomly coming up or on a specific componetn? Might be that, alternatively. Would love to see a sandbox then.

I'm using ["strict": true](https://github.com/ljosberinn/personal-react-boilerplate/blob/master/tsconfig.json#L18) here since months and haven't had issues after updating deps as you can see in the Github Actions log.

**Comment by joelgallant** [comment]
Yup, full reinstall without a lockfile. I noticed in the sandbox that "skipLibCheck" is on - that'll hide this problem. It happens before any of my TS is compiled (skipLibCheck "fixes" this problem in my repo). I'll take a quick shot at reproducing it, though I'll probably just make a PR with a fix here since it looks simple.

**Comment by ljosberinn** [comment]
ah interesting, that might indeed change something

**Comment by joelgallant** [comment]
Actually, even better. It looks like chakra-ui actually ships this code:

```
// @ts-expect-error
type PropsOf<T extends As> = React.PropsWithRef<React.ComponentProps<T>>
```

That's in `forward-ref.tsx` of the system package. It shouldn't end up in production builds, presumably, but it is.

**Comment by ljosberinn** [comment]
yeah that explains it - you mentioned a PR :] already know the solution by any chance?

**Comment by joelgallant** [comment]
I think so, working on it now.
