### ISSUE TITLE
Create react app using typescript fails

### ISSUE THREAD

**Issue by snissn** [chakra-ui/chakra-ui#2303]
# Bug report

## Describe the bug

following the tutorial i used the create react app. command, the resulting app has typescript errors

## To reproduce
1. `yarn create react-app my-app --template @chakra-ui/typescript`
2. `yarn run start`

## Screenshots

<img width="682" alt="Screen Shot 2020-10-23 at 12 21 03 PM" src="https://user-images.githubusercontent.com/1981537/97028504-3b24a880-152a-11eb-9dd6-437a5d55b65c.png">

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies): [e.g. Chrome, Safari]
- Version of @chakra-ui/core: [e.g. 1.0.0-rc.3]
- Version of Node.js: [e.g. 12.11.1]
mac os
> node --version
v12.18.3
## Additional context

should be an easy on boarding experience for new users

**Comment by snissn** [comment]
do i have the wrong version of node?

**Comment by ljosberinn** [comment]
probably a TS version issue, CRA is running an old one, did you check the steps [here](https://next.chakra-ui.com/guides/integrations/with-cra)?

**Comment by snissn** [comment]
yeah i just ran `yarn create react-app my-app --template @chakra-ui/typescript` and then tried to use the resulting app :)

**Comment by ljosberinn** [comment]
ah I'm afraid that's using the version `.next` and not `.rc5`, what's in your package json right now? (this will be fixed automatically when v1 lands)

**Comment by snissn** [comment]
`{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@chakra-ui/core": "^1.0.0-next.6",
    "@chakra-ui/theme": "^1.0.0-next.6",
    "@chakra-ui/theme-tools": "^1.0.0-next.6",
    "@testing-library/jest-dom": "^5.9.0",
    "@testing-library/react": "^10.2.1",
    "@testing-library/user-event": "^12.0.2",
    "@types/jest": "^25.0.0",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-icons": "^3.0.0",
    "react-scripts": "4.0.0",
    "typescript": "^3.9.5",
    "web-vitals": "^0.2.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`

**Comment by ljosberinn** [comment]
right so please try those:

```diff
-    "@chakra-ui/core": "^1.0.0-next.6",
-    "@chakra-ui/theme": "^1.0.0-next.6",
-    "@chakra-ui/theme-tools": "^1.0.0-next.6",
-    "typescript": "^3.9.5",

+    "@chakra-ui/core": "1.0.0-rc.5",
+    "@chakra-ui/theme": "1.0.0-rc.5",
+    "@chakra-ui/theme-tools": "1.0.0-rc.5",
+    "typescript": "4.0.3",
```

- [ ] remove `node_modules`
- [ ] remove lockfile
- [ ] reinstall

**Comment by snissn** [comment]
still same error! :)

**Comment by snissn** [comment]
the non type script version of the create app works great :)

**Comment by ljosberinn** [comment]
seeing now that create-react-app just released v4 so I'm checking locally real quick, that might've changed something

**Comment by ljosberinn** [comment]
Nevermind, its because of the old template. create-react-app is limiting in which git source we pull iirc, so the template you have there right now is from back then, `-next.6`.

You're probably seeing this error:
![image](https://user-images.githubusercontent.com/29307652/97032650-7511a100-1562-11eb-9f21-54f6f6ddeff5.png)

simply change `Grid` instead to `<Grid minH="100vh" p={3}>`, removing the other props. It's already fixed in the repo here for a while...

There's currently an issue with the color mode in create-react-app or rather generally client side rendering which will be fixed in the upcoming rc.6 which will be released later today.
