### ISSUE TITLE
MenuButton missing prop type defs

### ISSUE THREAD

**Issue by antegulin** [chakra-ui/chakra-ui#231]
MenuButton seems to be missing `isActive` and `rightIcon` typescript prop types.

**Comment by segunadebayo** [comment]
Okay. We'll look into it soon. If you have some time to look into it and add the types, I'll gladly merge your PR.

Thanks

**Comment by Drakota** [comment]
Hey guys!
I've taken a look to submit a PR and I've realized that the `MenuButton` isn't actually a Button per say. `isActive` and `rightIcon` are props specific to the `Button` component we have access to them, because we "cast" the `MenuButton`  to a `Button` via the `as` prop. 

We could also reproduce the same issue with the `Box` component. 
Example:
```
<Box as={Button} rightIcon="chevron-down"></Box>
```
There won't be any prop definition for the rightIcon in this case.
So I don't think we can just add the missing props on the `MenuButton` interface, because it can be anything. Unless there's a magic trick with Typescript that allows extracting a component's interface (ie. `IButton`) from the `as` attribute.

**Comment by antegulin** [comment]
Yes, there's a magic trick 

To extract props from a component you can use `React.ComponentProps`
```ts
type FooProps = React.ComponentProps<typeof Foo>
type InputProps = React.ComponentProps<'input'> 
```

**Comment by segunadebayo** [comment]
Thanks for the walkaround @antegulin and @Drakota

**Comment by iRoachie** [comment]
What's actually the fix for this? What does usage look like?

**Comment by wouterds** [comment]
Doesn't look like it's been fixed, I still need to do this on the latest version (using an out of the box example).

![Screenshot 2020-04-03 at 16 12 56](https://user-images.githubusercontent.com/1210628/78369958-47fda100-75c6-11ea-8945-dedac702002b.jpg)
![Screenshot 2020-04-03 at 16 13 03](https://user-images.githubusercontent.com/1210628/78369969-4a5ffb00-75c6-11ea-814d-1fb41e53b374.jpg)

**Comment by iRoachie** [comment]
Using this as my workaround:

```jsx
<MenuButton
  as={Button}
  {...{
    rightIcon: 'chevron-down',
  }}
>
  Hey
</MenuButton>
```

**Comment by shashankGS10** [comment]
I had the same issue while using this but I figured out that we need to import components from chakra which we are passing as a prop for the type of the `MenuButton`.

For example:
`import {
  **IconButton,
  Button,**
  Menu,
  MenuButton,
  MenuList,
  MenuItem} from '@chakra-ui/react';
  
  import {  ChevronDownIcon } from '@chakra-ui/icons';
  
  const MenuDemo =(props)=>{
      return{
           <Menu>
                {({ isOpen }) => (
                    <>
                         <MenuButton isActive={isOpen} as={Button} rightIcon={<ChevronDownIcon />}>
                             {isOpen ? "Close" : "Open"}
                         </MenuButton>
                         <MenuList>
                              <MenuItem>Download</MenuItem>
                              <MenuItem onClick={() => alert("Kagebunshin")}>Create a Copy</MenuItem>
                         </MenuList>
                    </>
                 )}
           </Menu>
      }
  }
  
  export default MenuDemo`
  
  In the above example, you'll notice that I also imported the `Button` component and passed it as a prop in `MenuButton`.
  https://codesandbox.io/s/menudemochakraui-fx1hy

**Comment by shashankGS10** [comment]
I had the same issue while using this but I figured out that we need to import components from chakra which we are passing as a prop for the type of the MenuButton.
For example:
`import {
IconButton,
Button,
Menu,
MenuButton,
MenuList,
MenuItem} from '@chakra-ui/react';
import { ChevronDownIcon } from '@chakra-ui/icons';
const MenuDemo =(props)=>{
return{

{({ isOpen }) => (
<>
<MenuButton isActive={isOpen} as={Button} rightIcon={}>
{isOpen ? "Close" : "Open"}


Download
<MenuItem onClick={() => alert("Kagebunshin")}>Create a Copy

</>
)}

}
}export default MenuDemo`
In the above example, you’ll notice that I also imported the `Button` component and passed it as a prop in `MenuButton`
https://codesandbox.io/s/menudemochakraui-fx1hy
