### ISSUE TITLE
Broken vertical font alignment on certain Linux distributions

### ISSUE THREAD

**Issue by nikwen** [chakra-ui/chakra-ui#2314]
# Bug report

## Describe the bug

Text which is supposed to be centered vertically is off by a few pixels in Firefox on Fedora 33.
This happens on both v1 and v0 and for every UI element where text is used.

## To reproduce

1. Get a working installation of [Fedora 33](https://getfedora.org) (VM, live USB stick, etc.)
2. In Firefox, open one of the urls mentioned below
3. See how the font is not aligned properly

## Minimal reproduction

The official Chakra UI docs are by nature a minimal reproduction. See below for links. :)

**Update:** This is no longer the case as the docs now use the non-default `Inter` font.

## Expected behavior

I would expect the vertical alignment of text to be pixel perfect.

### v1 screenshots

https://next.chakra-ui.com/docs/form/button

![buttons](https://user-images.githubusercontent.com/3309657/97105553-fa5c9900-16bb-11eb-8075-d6b02333d318.png)
![image buttons](https://user-images.githubusercontent.com/3309657/97105560-0ba5a580-16bc-11eb-99d2-7d089bda41d6.png)
![loading indicator](https://user-images.githubusercontent.com/3309657/97105572-195b2b00-16bc-11eb-8ac3-6ca685e433d3.png)

https://next.chakra-ui.com/docs/data-display/badge

![badges](https://user-images.githubusercontent.com/3309657/97105761-c2eeec00-16bd-11eb-9c32-25e929a85955.png)

https://next.chakra-ui.com/docs/form/input

![inputs](https://user-images.githubusercontent.com/3309657/97105814-20833880-16be-11eb-8466-aee113618d77.png)

### v0 screenshot

https://chakra-ui.com/button:

![grafik](https://user-images.githubusercontent.com/3309657/97105589-4f001400-16bc-11eb-93f6-b9a9556d2cf4.png)

## System information

- OS: Fedora 33 (Linux)
- Browser: Firefox 84.0 (64 bit)
- Version of @chakra-ui/core: 1.0.0-rc.5 / 0.8.0
- Version of Node.js: N/A

**Comment by la55u** [comment]
Possibly related: https://github.com/chakra-ui/chakra-ui/issues/983
I experienced the same issue.

**Comment by nikwen** [comment]
Thank you for the link, @la55u! I'll try the suggested fix in the coming week and will try to think about how to prevent this from happening to other people in the future (docs, code, etc.).

**Comment by with-heart** [comment]
It appears that Firefox calculates `align-items: baseline` differently from other browsers, and expects `inline-flex` rather than `flex` on the containing element. https://stackoverflow.com/questions/26385334/css-displayflex-align-itemsbaseline-not-working-in-firefox

We can investigate this to see if there's an easy fix, as that's a pretty big difference in display.

**Comment by tsnieman** [comment]
FWIW I have similar vertical-alignment issues across a **large** set of v1 components using Chromium (on Linux). I don't think this is contained to _just_ Firefox.

**Comment by with-heart** [comment]
Any way you can provide an example?  Haven't seen this.

**Comment by tsnieman** [comment]
@with-heart 

As I started to put together an example, it strikes me that:

- perhaps this at least PARTIALLY is an issue with the default font size + icons.

- Vertical alignment also doesn't seem to love my use of a monospace font: ![Screenshot from 2020-11-05 13-43-11](https://user-images.githubusercontent.com/595711/98299630-e131d300-1f6c-11eb-9d54-aa7b2acd961b.png)

Anyway, here's the sandbox from the screenshot above:

https://codesandbox.io/s/stoic-ptolemy-glf6d?file=/src/App.tsx

![Screenshot from 2020-11-05 13-38-57](https://user-images.githubusercontent.com/595711/98299282-4df89d80-1f6c-11eb-9884-fc43638593d3.png)

**Comment by nikwen** [comment]
Thank you guys for the great replies! :tada: 

**Using another font** can fix this issue. However, I feel like a UI framework like Chakra should work fine on all platforms out of the box.

Linux distributions like Fedora do not ship the `Helvetica` and `Arial` fonts referenced by Chakra. Hence, browsers fall back to look-alike fonts.

---

**Firefox** on Fedora uses `Nimbus Sans` as a replacement for `Helvetica`:

![Firefox screenshot](https://user-images.githubusercontent.com/3309657/98481305-9d073280-21f9-11eb-9ade-02b43d0fbc03.png)

`Nimbus Sans` seems to be a special fallback for `Helvetica`. If we set `font-family: sans-serif`, Firefox uses `Bitstream Vera Sans`.

---

**Chrome** falls back to its default `sans-serif` font on Fedora – `Liberation Sans`:

![Chrome screenshot](https://user-images.githubusercontent.com/3309657/98481317-bd36f180-21f9-11eb-858a-de6db0a35cc7.png)

However, even `Liberation Sans` has its issues. Badge texts are not properly centered in Chrome on Fedora:

![Chrome screenshot](https://user-images.githubusercontent.com/3309657/98481328-c758f000-21f9-11eb-921f-da6cf1e7547d.png)

---

A couple **more observations**:

* To me it was not clear that Chakra relies on system default fonts. I thought that it shipped it own and I wouldn't have to think about it.
* Chakra *could* ship its own default fonts. A change of that magnitude should be considered very carefully, though, especially since it would be breaking.
* The docs could also advise each user to choose their own custom fonts as part of the installation process. However, that goes against the design principle of simplicity. Chakra should in my opinion work fine for all users out of the box.

I'm not sure what the best fix would be. Do you have **any ideas?**

**Comment by nikwen** [comment]
This has not been fixed yet. Please keep the issue open. :)

**Comment by with-heart** [comment]
By default, we use the same font stack as GitHub: https://markdotto.com/2018/02/07/github-system-fonts/#the-stack

It's not entirely clear to me what change we can make here to fix what is a system and/or browser issue.

**Comment by nikwen** [comment]
> By default, we use the same font stack as GitHub: https://markdotto.com/2018/02/07/github-system-fonts/#the-stack

This explains why I am seeing the exact same issue on GitHub:

![Screenshot](https://user-images.githubusercontent.com/3309657/103156198-92532d80-47a6-11eb-875c-4feeed88a218.png)

**Comment by with-heart** [comment]
I haven't used Linux in a few years, but part of me wants to chalk this up to generally poor font rendering that has plagued distros forever. 😔

**Comment by nikwen** [comment]
Given that Chakra uses GitHub's font selection, I created an issue in the repository of their design system: https://github.com/primer/css/issues/1209. Let's see what they say.

**Comment by with-heart** [comment]
Found a few additional resources:

- https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1874842
- https://bugzilla.mozilla.org/show_bug.cgi?id=553580

Looks like Firefox relies too heavily on `fontconfig` to detect fallback fonts rather than following the fallbacks specified in the font stack, with `fontconfig` believing Nimbus Sans to be closest in weight and style to Helvetica, but Nimbus Sans includes spacing that Helvetica doesn't have which causes this issue.

**Comment by nikwen** [comment]
Thank you for the very interesting links, @with-heart! I commented on the Bugzilla ticket.

**Comment by wutangpaul** [comment]
Experiencing same issue on Firefox. Definitely from the github font stack. Seeing the same issue on buttons here.

**Comment by jdamon96** [comment]
Experiencing the same issue on Chrome & Safari

**Comment by nikwen** [comment]
Please keep the issue open. :)

**Comment by jdamon96** [comment]
I am still experiencing this issue - please keep it open

**Comment by with-heart** [comment]
I think I'm going to go ahead and close this because it's not serving any purpose for Chakra to have a tracking issue for it. There's no solution on our part because it's a Firefox font rendering issue, and we don't have anyone on the team that uses Linux so finding an alternative font to use in the stack isn't something we can investigate appropriately. If GitHub updates their font stack, I'd be happy to have an issue requesting that we update ours to mirror theirs, but this issue in particular isn't doing anything for anyone.

**Comment by nikwen** [comment]
That's fair. I'll create a new issue when there's an update from GitHub.

Their engineers have already done some work in this regard.

**Comment by with-heart** [comment]
I've also got it subscribed, just to make sure it doesn't slip through the cracks! Just trying to slowly reduce the number of issues, we're already behind enough as it is 😅 though it's open source, so really everything is right on time!

**Comment by DeveloperMatheus** [comment]
I also got this problem and could solve it by changing the font manually (i got one from google fonts, and then injected with my theme object inside the theme prop to ChakraProvider.

**Comment by ardasevinc** [comment]
Apparently this is still a thing in 2022. Just had this alignment issue. My fix is to change the fontconfig so that when applications want Helvetica they get Inter :)

References: this great [blog post](https://eev.ee/blog/2015/05/20/i-stared-into-the-fontconfig-and-the-fontconfig-stared-back-at-me/) by eevee and arch wiki [fontconfig page](https://wiki.archlinux.org/title/Font_configuration#Fontconfig_configuration)

Here are the steps if anyone finds this:

-  Install or choose a font you like to replace Helvetica. I chose [Inter](https://rsms.me/inter/)
- Open or create `~/.config/fontconfig/fonts.conf`
- Insert these lines after `<fontconfig>`
```
 <match>
  <test name="family">
   <string>Helvetica</string>
  </test>
  <edit binding="same" mode="assign" name="family">
   <string>Inter</string>
  </edit>
 </match>
```
- Change Inter to some other font if don't want to use Inter.
- Run `fc-cache -fv` (this step might not be necessary)
- Close your browser and open it again
- Your app should load Inter instead of Nimbus Sans

**Comment by nikwen** [comment]
GitHub just updated its font stack in an attempt to fix the issue. Maybe a good time to reopen this one?

See: https://github.com/primer/css/issues/1209#issuecomment-1319410949

**Comment by ardasevinc** [comment]
> GitHub just updated its font stack in an attempt to fix the issue. Maybe a good time to reopen this one?
> 
> See: https://github.com/primer/css/issues/1209#issuecomment-1319410949

I don't think Firefox is going to fix relying on fontconfig... This issue is going to pop up every time an application requests helvetica. It's best if people set up their fontconfig as I've shown.

**Comment by nikwen** [comment]
> I don't think Firefox is going to fix relying on fontconfig... This issue is going to pop up every time an application requests helvetica. It's best if people set up their fontconfig as I've shown. 

This issue is about fixing the default look of Chakra UI, a UI framework, not about fixing Linux-wide font issues.

**Comment by ardasevinc** [comment]
> > I don't think Firefox is going to fix relying on fontconfig... This issue is going to pop up every time an application requests helvetica. It's best if people set up their fontconfig as I've shown.
> 
> This issue is about fixing the default look of Chakra UI, a UI framework, not about fixing Linux-wide font issues.

That's right, sorry. It seems to me that the only viable solution is to ship a font like Inter by default...
