### ISSUE TITLE
Possibility to override default toast options as `useToast({ ... })`

### ISSUE THREAD

**Issue by tomdohnal** [chakra-ui/chakra-ui#2316]
# Feature request

## Is your feature request related to a problem? Please describe.

I am using the `useToast` hook to create different messages based upon what has gone wrong. 

Now, I have to pass the options (such as `status`, `duration`, and `isClosable`) to each individual `toast(...)` call.

## Describe the solution you'd like

I'd like to have the possibility to specify these options as an argument to the `useToast(...)` hook itself so that I could then use the `toast(...)` call like this:

```javascript
const errorToast = useToast({ status: 'error', duration: 10000, isClosable: true, position: 'top' })

// ...

if (error1) { errorToast({ title: 'Error 1!' }) }
if (error2) { errorToast({ title: 'Error 2!' }) }
if (error3) { errorToast({ title: 'Error 3!' }) }
```

Also, it would make creating custom hooks like `useErrorToast` or `useSuccessToast` a bit *easier*
```javascript
function useSuccessToast(options) {
  const successToast = useToast({ status: 'success', duration: 10000, isClosable: false, position: 'top', ...options })

  return successToast
}
```

instead of 
```javascript
function useSuccessToast() {
  const toast = useToast()

  return (options) => {
    toast({ status: 'success', duration: 10000, isClosable: false, position: 'top', ...options })
  }
}
```

## Describe alternatives you've considered

An alternative is to keep things as they are as creating a custom hook is not a major pain. Or you could just document a suggested approach for creating those custom hooks

**Comment by tomdohnal** [comment]
I'd actually love to try to implement this if you'd consider it a useful addition :)

**Comment by ljosberinn** [comment]
Oh sure, please go ahead :) should be somewhat trivial actually, I considered twice adding it today already but we're in the process of releasing another rc first.

**Comment by tomdohnal** [comment]
Okay, I'll try to send a PR tomorrow :)
