### ISSUE TITLE
Would there have a Cascader component?

### ISSUE THREAD

**Issue by kxxoling** [chakra-ui/chakra-ui#2322]
# Feature request

## Is your feature request related to a problem? Please describe.

Cascader is a common component in ent component suites, such as [rsuite](https://rsuitejs.com/components/cascader) and ant-design.

## Describe the solution you'd like

A component supports multi levels of options rendered in a horizontal dropdown menu.

## Describe alternatives you've considered

A select like component which renders an next-level select if there's children in selected option.

## Additional context

![image](https://user-images.githubusercontent.com/1227139/97129987-2d199680-177b-11eb-8bea-723bc6585f2a.png)

**Comment by segunadebayo** [comment]
HI @kxxoling,

This isn't a priority for the team and I won't be adding this to Chakra UI soon.

We'll add it to the backlog though, perhaps we might consider it in the future.

Thank you
