### ISSUE TITLE
RC-7 VStack spacing is ignored when using any non- <StackDivider /> component as a divider

### ISSUE THREAD

**Issue by Harrisonl** [chakra-ui/chakra-ui#2326]
# Bug report

## Describe the bug

Upgraded to the new version and saw that my spacing was being ignored on VStacks when using a <Divider />. I did notice however that there is a new StackDivider that does work as normal. This solves the problem for me as I was just using a normal divider, however this may be an issue for others using custom component dividers which according to the docs should be supported?

>  Pass the divider prop and set it's value to the StackDivider or any custom React element.

## To reproduce

Create a VStack and use any divider that's not a `StackDivider`

## Minimal reproduction

https://codesandbox.io/s/inspiring-brahmagupta-vhvt4?file=/src/App.tsx

## Screenshots

<img width="687" alt="Screenshot 2020-10-26 at 08 45 07" src="https://user-images.githubusercontent.com/10399120/97151554-8f689c00-1767-11eb-9296-9eba6f8243d3.png">

**Comment by sebqq** [comment]
Here is sandbox reproducible repo: https://codesandbox.io/s/falling-microservice-oypkl?file=/src/index.js

**Comment by omarkhatibco** [comment]
I can confirm the same problem

**Comment by segunadebayo** [comment]
I just pushed a fix for this. Thanks for reporting.
