### ISSUE TITLE
Module not found: Can't resolve 'framer-motion' in chakra-ui 1.0.0-rc6 and rc-7

### ISSUE THREAD

**Issue by sebqq** [chakra-ui/chakra-ui#2327]
# Bug report

## Describe the bug

Using latest chakra-ui with next.js I keep getting following error message

```node
error - ./node_modules/@chakra-ui/checkbox/dist/esm/checkbox-icon.js:6:0
Module not found: Can't resolve 'framer-motion'
null
```

## To reproduce

1. use rc.6 or rc.7

## System information

- OS: macos
- Version of @chakra-ui/core: 1.0.0-rc.6 and rc.7

**Comment by sebqq** [comment]
Sorry. I can see now `framer-motion` added to upgrade guide.

**Comment by ljosberinn** [comment]
`framer-motion` is a peer dependency since `rc.7`, the [docs](https://next.chakra-ui.com/docs/getting-started#installation) reflect that. Sorry for the inconvenience :)
