### ISSUE TITLE
RC-7 Toasts no-longer close automatically

### ISSUE THREAD

**Issue by Harrisonl** [chakra-ui/chakra-ui#2328]
# Bug report

## Describe the bug

I can't seem to get toasts to close in the new version, either automatically or by button press

## To reproduce

1. https://next.chakra-ui.com/docs/feedback/toast
2. Open any toast with a duration (observe it won't close)
3. Try the 'close last toast' or 'close all toasts' button and observe none close

**Comment by ljosberinn** [comment]
Fixed last night in cd3530e941f46b5b4fdaf120f6414798ee29df9d - will be in the next release :)

**Comment by Harrisonl** [comment]
Oh perfect thanks for the speedy reply! @ljosberinn

**Comment by archywillhe** [comment]
nice! looking forwards to the new release 🥳

**Comment by feross** [comment]
@ljosberinn Any ETA on a new release? I hastily updated to rc7, made changes to support `<WrapItem>`, etc. but just ran into this toast bug.

**Comment by bogdansoare** [comment]
Also having this issue, a quick release for this fix would be highly appreciated

**Comment by ljosberinn** [comment]
We're aiming for another release tomororw or the day after!
