### ISSUE TITLE
[Icon] display property has typing issues

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#2333]
Using object notation with display:

![image](https://user-images.githubusercontent.com/29307652/97205337-9fa86780-17b7-11eb-8f17-de6d180e66cb.png)

Using array notation:

![image](https://user-images.githubusercontent.com/29307652/97205372-b18a0a80-17b7-11eb-9884-135ff9eb426d.png)

Same with `d` - so far only happens on `Icon`. It occurs regardless of using `as` on the component.

**Comment by segunadebayo** [comment]
Just pushed a fix for this!
