### ISSUE TITLE
[SLIDER] Initial value is skipped while dragging slider

### ISSUE THREAD

**Issue by laurensnl** [chakra-ui/chakra-ui#2336]
# Bug report

## Describe the bug

While dragging the slider back and forth, the value that was selected before starting to drag is skipped when passing it. I'm unable to select the initial value while dragging the thumb.

## To reproduce

1. Open the sandbox below
2. The slider defaults to 10
3. Slide left, to 5 (`step=5`), keep the mouse down
4. Slide back to the right
5. You'll see that 10 can't be selected while dragging. 

## Minimal reproduction

https://codesandbox.io/s/new-hill-3eeky?file=/src/App.tsx

## Expected behavior

I'd expect to be able to select the value that I've started at before dragging.

## Screenshots

![ezgif com-gif-maker](https://user-images.githubusercontent.com/4354382/97230342-0fc7e500-17da-11eb-8d6e-34ed7328e4b9.gif)

## System information

- OS: Mac OS
- Browser Chrome 86.0.4240.111 
- Version of @chakra-ui/core: 1.0.0-rc.7

**Comment by segunadebayo** [comment]
Thanks for catching this @laurensnl.

I just pushed a fix for it.
