### ISSUE TITLE
[Wrap] <Wrap> has extra margin between lines when used with <Badge>

### ISSUE THREAD

**Issue by feross** [chakra-ui/chakra-ui#2337]
# Bug report

## Describe the bug

`<Wrap>` has extra margin between lines when used with `<Badge>`.

## To reproduce

https://codesandbox.io/s/stupefied-meninsky-mxiob?file=/src/index.tsx:251-416

## Expected behavior

No extra spacing between lines.

## Screenshots

Note the extra spacing between lines:

<img width="945" alt="Screen Shot 2020-10-26 at 2 57 11 PM" src="https://user-images.githubusercontent.com/121766/97244040-d5981c80-17b4-11eb-9ed8-2096ec444618.png">

## System information

- OS: [e.g. macOS, Windows] macOS
- Browser (if applies): [e.g. Chrome, Safari] Chrome
- Version of @chakra-ui/core: [e.g. 1.0.0-rc.3] rc7
- Version of Node.js: [e.g. 12.11.1] 14 LTS

**Comment by segunadebayo** [comment]
Thanks for catching this @feross.

I've just pushed a fix for this. The walkaround is to apply `display=flex` to the `WrapItem`

**Comment by feross** [comment]
Awesome, thanks!
