### ISSUE TITLE
1.0.0-rc.7 Checkbox shows 'not-allowed' cursor when isDisabled set to false

### ISSUE THREAD

**Issue by avaragado** [chakra-ui/chakra-ui#2339]
# Bug report

## Describe the bug

According to the [Checkbox documentation](https://next.chakra-ui.com/docs/form/checkbox#checkbox-props), `Checkbox` takes a boolean prop `isDisabled`. Setting this prop to `true` should show the checkbox as disabled, and `false` should not show the checkbox as disabled.

However, setting `isDisabled={false}` shows the `not-allowed` cursor. The checkbox itself still works: it's just the cursor that's wrong.

(I can't just remove the prop: the value is being passed as a variable, ie `isDisabled={isDisabled}`)

## To reproduce

1. Go to https://next.chakra-ui.com/docs/form/checkbox#disabled-checkbox
2. Change `<Checkbox isDisabled>` to `<Checkbox isDisabled={false}>`
3. Note that the checkbox still functions, but the `not-allowed` cursor shows

## Expected behavior

The `not-allowed` cursor should not show when `isDisabled` is set to `false`.

## System information

- macOS Catalina 10.15.6
- Chrome 86
- @chakra-ui/core 1.0.0-rc.7
- node v12.16.1

**Comment by avaragado** [comment]
Workaround: `isDisabled={isDisabled ? true : undefined}`

**Comment by Zaynex** [comment]
> Workaround: `isDisabled={isDisabled ? true : undefined}`

I send a pull request, you can try it.
https://chakra-ui-git-fix-checkbox.chakra-ui.now.sh/docs/form/checkbox
