### ISSUE TITLE
[Flex] responsive array disallowed for prop color

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#2341]
`<Flex color={["blue.500", "red.500"]}>` is no longer valid in rc.7 - it _works_ as intended, but TS complains.

rc.5: https://codesandbox.io/s/xenodochial-mirzakhani-zhtxv?file=/src/App.tsx
rc.7: https://codesandbox.io/s/snowy-shape-misk4?file=/src/App.tsx

**Comment by segunadebayo** [comment]
I just pushed a fix for this!
