### ISSUE TITLE
Toast is not closable anymore

### ISSUE THREAD

**Issue by paulbalogh** [chakra-ui/chakra-ui#2345]
# Bug report

## Describe the bug

After upgrading to RC7, using `toast` with `isClosable: true` results in a component which is not closable anymore (stuck on screen). 

## To reproduce

Just use the toast as described in Chakra's or Chakr's own toast examples: https://next.chakra-ui.com/docs/feedback/toast

## Screenshots

![CleanShot 2020-10-27 at 18 49 33](https://user-images.githubusercontent.com/1029610/97348044-853cbf80-1885-11eb-817f-32b7c79aa453.gif)

## System information

- OS: macOS
- Browser (if applies): checked in latest Chrome and Edge
- Version of @chakra-ui/core: 1.0.0-rc.7
- Version of Node.js: v12.18.2

**Comment by ljosberinn** [comment]
fixed in #2328 will be in the next released
