### ISSUE TITLE
Gatsby Link activeStyle prop

### ISSUE THREAD

**Issue by theskillwithin** [chakra-ui/chakra-ui#2346]
gatsby activeStyle doesn't seem to work,  maybe this is not getting passed to gatsbys Link?

https://www.gatsbyjs.com/docs/gatsby-link

```
import React from 'react'
import { Link as UILink, PseudoBox } from '@chakra-ui/core'
import { Link as GatsbyLink } from 'gatsby'

const Link = (props) => {
  if (props.to) {
    return <PseudoBox as={GatsbyLink} {...props} />
  }

  return <UILink {...props} />
}

export default Link
```

```
 <Link
    to="/"
    textDecoration="none"
    color="gray.700"
    _hover={{ textDecoration: 'none', borderBottomColor: 'teal.500' }}
    px="4"
    py="2"
    activeStyle={{ color: 'red', background: 'red' }}
  />
```

**Comment by segunadebayo** [comment]
Hi @theskillwithin,

This has been fixed in the upcoming v1 release. It is due to the `shouldForwardProp` condition v0.8 uses and that has been improved in the upcoming v1.

Permit me to close this in favor of upgrading to v1 (next.chakra-ui.com).
