### ISSUE TITLE
Input style props not being overwritten with customized theme

### ISSUE THREAD

**Issue by bwillem** [chakra-ui/chakra-ui#2347]
# Custom theme API for `components.Input` not working

## Describe the bug

Input styles are not being overwritten when using the customize theme API: https://next.chakra-ui.com/docs/theming/customize-theme

## To reproduce

customize your theme:
```
const Input = {
  baseStyle: {
    borderColor: 'primary.accent2',
    _hover: {
      borderColor: 'primary.foreground',
    },
  },
  sizes: {
    sm: {
      fontSize: 'md',
      height: '40px',
    }
  },
  defaultProps: {
    size: 'sm',
  },
}

const theme = extendTheme({
  components: {
    Input,
  }
})
```

use this input:
```
import { Input } from '@chakraui/core'

const Component = props => <Input />
```

## Expected behavior

The default exported input should adopt custom theme styles

## Additional context

This API and method works with the Button component (`theme.components.Button`). With `Input`, however, no styles seem to render. They don't seem to exist in the DOM at all.

**Comment by ljosberinn** [comment]
`Input` has multiple parts - [`field` and `addon`](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/theme/src/components/input.ts#L3). Which means you need to scope all your props for `Input` within `baseStyle.field`, `sizes.lg.field`, etc. - the default version is a good starting point here to compare.

**Comment by linghaolin** [comment]
```js
const Input = {
  baseStyle: {
    field: {
      borderColor: 'primary.accent2',
      _hover: {
        borderColor: 'primary.foreground',
      },
    }
  },
  sizes: {},
  defaultProps: {},
}
```

Works for me

**Comment by ImSolitude** [comment]
Weird, I think this issue still exists. 
```
Input: {
  baseStyle: {
    field: {
      borderWidth: '4px',
      borderStyle: 'solid',
      borderColor: '#f0f',
      _hover: {
        borderColor: '#f0f',
        },
      },
    },
    sizes: {},
    defaultProps: {},
    },
```
this code doesn't change the border! It's stuck on default.

**Comment by JuSenpai** [comment]
Try setting a variant other than the ones provided in the docs. I found this out by accident, but seemed to fix it for me.
```js
  <ChakraInput
      variant={'something'} // this variant does not exist, but it clears the default variant styles
      {...props}
  />
```

**Comment by agentlewis** [comment]
Same issue and solution discovered here.

Seems like a bug worth tracking?

**Comment by SakibAbrar** [comment]
Facing the same issue. Anyone came up with an way around or something?

**Comment by tomimarkus991** [comment]
this works for me (changing input text color to red)
![image](https://user-images.githubusercontent.com/48998818/128526138-91761b32-1fb5-48e5-9730-da63c4ae4963.png)

**Comment by SakibAbrar** [comment]
### This one worked for me

```javascript
export default {
  baseStyle: {
    field: {
      fontWeight: 400,
    },
  },

  sizes: {
    sm: {
      field: {
        height: 8,
        borderRadius: '4px',
        boxShadow: '4px 4px 0px #B1B1B1',
      },
    },

    md: {
      field: {
        borderRadius: '4px',
        height: 12,
        fontSize: 'md',
        boxShadow: '4px 4px 0px #B1B1B1',
      },
    },

    lg: {
      field: {
        height: 16,
        borderRadius: '6px',
        fontSize: 'lg',
        boxShadow: '4px 4px 0px #B1B1B1',
      },
    },

    xl: {
      field: {
        height: { base: 16, lg: 20 },
        borderRadius: '6px',
        fontSize: { base: 'lg', lg: 'xl' },
        px: { base: 3, lg: 5 },
        boxShadow: '4px 4px 0px #B1B1B1',
      },
    },

    '2xl': {
      field: {
        height: 24,
        borderRadius: 'none',
        fontSize: '2xl',
        px: 5,
        boxShadow: '4px 4px 0px #B1B1B1',
      },
    },
  },

  variants: {
    outline: {
      field: {
        border: '2px solid',
        _focus: {
          borderColor: '#9280FF',
          boxShadow: 'none',
        },
      },
    },

    yourVariant: {
      field: {
        border: '3px solid',
        borderColor: '#130080',
        _focus: {
          borderColor: '#9280FF',
          boxShadow: 'none',
        },
      },
    },
  },
};
```

**Comment by minhla** [comment]
My code works, however I am using v.1.3.3 though. YMMV
`const Input = {
  variants: {
    auth: {
      field: {
        border: "1px solid",
        borderColor: "gray.400",
        color: "black",
        _focus: {
          boxShadow: "0 0 2px 2px #38B2AC"
        }
      },
    },
  },
}

`

**Comment by muco-rolle** [comment]
How to change the border color that appears on focus? ![Screenshot from ](https://user-images.githubusercontent.com/43722815/131475069-526069bd-af5a-4ae7-b132-e0d11b7b7b4f.png)

**Comment by Subalee** [comment]
I think it'd be very beneficial to include some kind of note for multi part chakra components in the docs, what do you guys think?

**Comment by Subalee** [comment]
> > Try setting a variant other than the ones provided in the docs. I found this out by accident, but seemed to fix it for me.
> > ```js
> >   <ChakraInput
> >       variant={'something'} // this variant does not exist, but it clears the default variant styles
> >       {...props}
> >   />
> > ```
> 
> Setting `variant` to null in `defaultProps` works too!
> 
> ```js
> {
>   ...
>   Input: {
>     baseStyle: {
>       field: {
>         bg: '#4b4b4f',
>         borderColor: '#4b4b4f',
>         borderWidth: 3,
>         ':focus': {
>           borderColor: '#a970ff',
>           bg: '#000'
>         }
>       }
>     },
>     sizes: {},
>     variants: {},
>     defaultProps: {
>       variant: null // null here
>     }
>   }
> }
> ```

This feels like the best solution for now

**Comment by takethefake** [comment]
If you don't want to use variants, this can be a way to solve this, but the more sustainable way would be to overwrite an existing variant or define a variant for your special use case. `baseStyle` is as the name states, the base for the components. variants overwrite the `baseStyle`.

**Comment by Subalee** [comment]
@takethefake Respectfully I have to disagree, I should be able to override the base styles without resorting to creating a new variant and passing that to `defaultProps`.  This way I'm creating variants based on my own baseStyle and not based on my variant that overrides the chakra baseStyle

**Comment by takethefake** [comment]
You're always creating variants based on your own `baseStyle` but the variant-style overwrites the `baseStyle`. That's why there are some properties that can't be overwritten by `baseStyle` because the used variant always overwrites them.

**Comment by nappalm** [comment]
```
baseStyle: {
      field: {
        borderColor: '#D3E8E6',
        borderWidth: 1,
        borderRadius: '12px' // here
      },
    },
```

Not working border radius

**Comment by malashevskyi** [comment]
> ```
> baseStyle: {
>       field: {
>         borderColor: '#D3E8E6',
>         borderWidth: 1,
>         borderRadius: '12px' // here
>       },
>     },
> ```
> 
> Not working border radius
 
Built-in sizes have ```border-radius```.
So if you change ```border-radius```, you probably don't want to use a default built-in size at all:
```javascript
defaultProps: {
    size: null
},
```

**Comment by keithburgie** [comment]
Okay I did a deep dive. Hope this is helpful to anyone else who comes along.

- For Input, styles need to be added to `baseStyle.field` and not just `baseStyle`
- `baseStyle` styles are overridden by `sizes` styles (borderRadius, fontSize, height & padding) as well as `variant` styles (background, border, borderColor, _focus, _hover and sometimes others.)
- `variant` styles will override all `sizes` styles.
- Setting `defaultProps.size` and/or `defaultProps.variant` to `null` will remove those styles. I don't love this solution because it remove _all_ styles, and I don't want to have to re-set everything because I wanted a different background color.

The simplest way to make a basic change, like to a background or border, would be to set it on the variant that you're using:
```javascript
Input: {
  variants: {
    outline: {
      field: {
        background: "white",
        borderRadius: 0
      } 
    }
  }
}
```
Here's a component (err, component style object) that shows all defaults.

```javascript
const Input = {
  baseStyle: {
    /**
     * Styles set within { variants } will override base styles
     * Styles set within { sizes } will override base styles
     * The Input component uses "md" size and "outline" variant by default.
     *
     * You can unset those defaults by using null in defaultProps:
     *    defaultProps: {
     *      size: null,
     *      variant: null
     *    },
     *
     * You will lose all default styles this way, including things like focus.
     */
    field: {
      // Add custom base styles here
    },
  },
  sizes: {
    /**
     * Input component will receive "md" styles by default
     * Styles set within { variants } will override styles at all sizes
     *
     * The styles below are what Chakra will use unless replaced.
     */
    xs: {
      field: {
        borderRadius: "sm",
        fontSize: "xs",
        height: 6,
        paddingX: 2,
      },
    },
    sm: {
      field: {
        borderRadius: "sm",
        fontSize: "sm",
        height: 8,
        paddingX: 3,
      },
    },
    md: {
      field: {
        borderRadius: "md",
        fontSize: "md",
        height: 10,
        paddingX: 4,
      },
    },
    lg: {
      field: {
        borderRadius: "md",
        fontSize: "lg",
        height: 12,
        paddingX: 4,
      },
    },
  },
  variants: {
    /**
     * Input component will use "outline" styles by default.
     * Styles set here will override anything in { baseStyle } and { sizes }
     *
     * The styles below are what Chakra will use unless replaced.
     */
    outline: {
      field: {
        background: "inherit",
        border: "1px solid",
        borderColor: "inherit",
        _focus: {
          zIndex: 1,
          borderColor: "#3182ce",
          boxShadow: "0 0 0 1px #3182ce",
        },
        _hover: { borderColor: "gray.300" },
      },
    },
    filled: {
      field: {
        background: "gray.100",
        border: "2px solid",
        borderColor: "transparent",
        _focus: {
          background: "transparent",
          borderColor: "#3182ce",
        },
        _hover: {
          background: "gray.300",
        },
      },
    },
    flushed: {
      field: {
        background: "transparent",
        borderBottom: "1px solid",
        borderColor: "inherit",
        borderRadius: 0,
        paddingX: 0,
        _focus: {
          borderColor: "#3182ce",
          boxShadow: "0 0 0 1px #3182ce",
        },
      },
    },
    unstyled: {
      field: {
        background: "transparent",
        borderRadius: "md",
        height: "auto",
        paddingX: 0,
      },
    },
  },
  defaultProps: {
    /**
     * Set either or both of these to null to use only what's in { baseStyle }
     */
    size: "md",
    variant: "outline",
  },
}
```

**Comment by FaustoHM** [comment]
it works to me adding "field:", sorry, i'm a true newbie, but why u must add field to the variant name? For Button customize u only need variant name.

**Comment by Subalee** [comment]
@FaustoHM `Input` component is what chakra calls multipart components, in this case its made out of 2 subcomponents `field` and `addon` which you need to style separately. this is a case for some but not all chakra components.

you can find the parts by viewing theme source, it's a button under the component title and scroll down to see the invidiual parts in the source.

That said as a fan of Chakra I think the documentation does terrible job when it comes to restyling premade multipart components

**Comment by abhagsain** [comment]
> arts in the source.

@Subalee It'd be great if you could provide a link? 😅

**Comment by marksto-workshub** [comment]
> You're always creating variants based on your own `baseStyle` but the variant-style overwrites the `baseStyle`. That's why there are some properties that can't be overwritten by `baseStyle` because the used variant always overwrites them.
> 
> That's why I mentioned that you should make use of variants yourself to achieve your styling by overwriting variants or defining your own instead of trying to overwrite `baseStyles`

It feels to me that this behavior should either be changed or **be configurable** (via the global Chakra configuration).

How it works at the moment (here, the `<<` means "overrides"):
```
default `baseStyle` << default `variants`
        ^                       ^
        ^                       ^
project `baseStyle` << project `variants`
```

How some Chakra users (me included) would like it to work for our project:
```
default `baseStyle` << default `variants` << project `baseStyle` << project `variants`
```

When a thing that one pursues is merely tuning up a single property (e.g. setting a thicker `borderWidth` for all `Input`s), there must be a better way than setting up a default `variant` and overriding all Chakra's existing variants just in case.

**Comment by mattrigg9** [comment]
Adding to this thread in case anyone runs into the same trouble I did.

In addition to ensuring the appropriate variants and sizes are overridden (as mentioned above), you must override the styles with the same attributes that Chakra defines in it's default theme. **Some of these are shorthand attributes**.

For example, when overriding the `Input` `field` height, you must use the `h` attribute instead of `height`, since this is the attribute that Chakra [defines in the theme](https://github.com/chakra-ui/chakra-ui/blob/95aa4499c72de28e91dd9274177c529db55e7964/packages/components/theme/src/components/input.ts#L37).

As of Chakra 2.3.2, the following config will successfully override the default height for the Input filled:

```ts
{
  Input: {
    baseStyle: {
      field: {
        h: "2rem",
      },
    },
    variants: {
      outline: {
        field: {
          h: "2rem",
        },
      },
    },
  },
};
```

**Comment by schulzf** [comment]
I've just lost half an hour to understand that to change the border you actually have to set `outlined` instead of `border` ... go figure...

**Comment by villesau** [comment]
@segunadebayo could this be reopened? Just spent forever to figure out what is wrong before found out this hacky but functional workaround: https://github.com/chakra-ui/chakra-ui/issues/2347#issuecomment-917375118

This is one of those things that makes the entry barrier to the library pretty steep and overriding default variants with nulls does not sound like a expected behaviour.

**Comment by Pulverizer2020** [comment]
Changing the default style in the field for the borderColor attribute doesn't work for me. Has anyone else experienced this?

**Comment by isabellasantiago** [comment]
I couldn't get a way to style properly the input, I tried and read every single comment in this issue. Some of them work, but when we talk about `__hover`, `_active` etc, none of them work. Another thing is: when you use `outline` instead of `border` it seems to change the color, but ACTUALLY it get 2 borders!!

![image](https://github.com/chakra-ui/chakra-ui/assets/78266129/7466caf2-486e-4df9-8563-a610c9a10fb8)

**Comment by joaofranciscoguarda** [comment]
> I couldn't get a way to style properly the input, I tried and read every single comment in this issue. Some of them work, but when we talk about `__hover`, `_active` etc, none of them work. Another thing is: when you use `outline` instead of `border` it seems to change the color, but ACTUALLY it get 2 borders!!
> 
> ![image](https://user-images.githubusercontent.com/78266129/264797096-7466caf2-486e-4df9-8563-a610c9a10fb8.png)

Have you tried `_focus` property?
