### ISSUE TITLE
TypeScript error when using @chakra-ui/icons within Buttons

### ISSUE THREAD

**Issue by Catchpowle** [chakra-ui/chakra-ui#2348]
# Bug report

## Describe the bug

I get a type error when using an Icon from chakra-ui/icons within a Button.

## To reproduce

Doing this:
```
import { Button } from "@chakra-ui/core"
import { PhoneIcon } from '@chakra-ui/icons'


<Button leftIcon={PhoneIcon}>PhoneIcon</Button>
```

Results in:
```
Type 'ComponentWithAs<"svg", IconProps>' is missing the following properties from type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>': type, props, key
```

## Minimal reproduction

I've added a repo to demonstrate the issue here:
https://github.com/Catchpowle/ChakraBug

Go to `src/stories/ChakraButton.tsx` within VSCode or another editor with TypeScript language support to see the error.

## Expected behavior

There should be no type errors when doing this.

## Screenshots

<img width="1053" alt="Screenshot 2020-10-27 at 21 49 21" src="https://user-images.githubusercontent.com/2227892/97365918-60087b00-189e-11eb-9944-50e1c684d5d5.png">

## System information

- OS: macOS
- Version of @chakra-ui/core: 1.0.0-rc.7
- Version of Node.js: v12.16.1

**Comment by ljosberinn** [comment]
[Per the docs](https://next.chakra-ui.com/docs/form/button#button-with-icon), you need to use `<PhoneIcon />`.

**Comment by sanandnarayan** [comment]
`<Button leftIcon={React.createElement(PhoneIcon)}>PhoneIcon</Button>`
could work
