### ISSUE TITLE
Wrong typings when using <Box as="form" />

### ISSUE THREAD

**Issue by kgnugur** [chakra-ui/chakra-ui#2352]
# Bug report

## Describe the bug

onSubmit typing is wrong when using `<Box as="form" />`

![image](https://user-images.githubusercontent.com/28161197/97390959-1c8a2d00-18ef-11eb-9d2c-9bf018c5fba3.png)

## To reproduce

- Open the [official template](https://codesandbox.io/s/github/chakra-ui/codesandbox-react-ts-template/tree/master)
- Type `<Box as="form" onSubmit></Box>`
  - It will work as expected. Now go to package json and update to     "@chakra-ui/core": "^1.0.0-rc.7", "@chakra-ui/theme": "^1.0.0-rc.7"
- Go back and take a look at onSubmit typing.

## Minimal reproduction

https://codesandbox.io/s/sleepy-keldysh-x35lr?file=/src/App.tsx

## Expected behavior

![image](https://user-images.githubusercontent.com/28161197/97390998-3592de00-18ef-11eb-95a0-adcab5a7405b.png)

## System information

- Version of @chakra-ui/core: "^1.0.0-rc.7"

**Comment by segunadebayo** [comment]
Hi @kgnugur.

This is a trade-off we're willing to make for the `as` prop.

We've had a lot of back and forth to get 100% type correctness and TS Intellisense speed of the `as` prop. Sadly, you can't get both at the same time.

@ljosberinn, let's take note to add this to the docs.

**Comment by selrond** [comment]
For people who will face this:
It's solvable by using `<chakra.form />` JSX element, where you still have all of the styling props, but with proper typings for events

**Comment by jvnlwn** [comment]
Might be misunderstanding the above solution with using `<chakra.form />` but, while the following will make TypeScript happy, your users won't be:

```tsx
interface FormPropsType {
  onSubmit: React.FormEventHandler<HTMLFormElement>
}

const Form = ({ onSubmit }: FormPropsType)=> {
  return (
    <chakra.form as={Box} onSubmit={onSubmit}>
      {/* form stuff */}
    </chakra.form>
  )
}
```

The element rendered will be a `<div />` rather than a `<form />` and will thus not handle the `onSubmit` event.

You could simply wrap with the literal `<form />` element:
```tsx
return (
  <form onSubmit={onSubmit}>
    <Box>
      {/* form stuff */}
    </Box>
  </form>
)
```

**Comment by selrond** [comment]
@jvnlwn why would you want to do that? 
OP presumably wanted to use Chakra styling props but have a `form` element rendered in the end.
These two are practically equivalent: `<Box as="form">` == `<chakra.form />`

**Comment by jvnlwn** [comment]
@selrond thanks for the response. I think I see how I misunderstood your suggestion.

> These two are practically equivalent: `<Box as="form">` == `<chakra.form />`

Yes, that makes sense. They both will accept Chakra styling props and will both render a `<form />` element. The issue though with `<Box as="form">` as the OP noted was that the typing of `onSubmit` will be wrong.

If I alter my example as follows, using `<Box as="form">`:

```tsx
interface FormPropsType {
  onSubmit: React.FormEventHandler<HTMLFormElement>
}

const Form = ({ onSubmit }: FormPropsType)=> {
  return (
    <Box as="form" onSubmit={onSubmit}>
      {/* form stuff */}
    </Box>
  )
}
```

TypeScript will produce the following error for the Box's `onSubmit` prop:

> Type 'FormEventHandler\<HTMLFormElement\>' is not assignable to type 'FormEventHandler\<HTMLDivElement\>'.

Here's a fuller example if it helps: https://codesandbox.io/s/thirsty-galois-18kxqo?file=/src/index.tsx

Not sure how to work around this other than by breaking the components out into their separate concerns.
