### ISSUE TITLE
TypeError on the Image width and height responsive style props - Version 1.0.0-rc.7

### ISSUE THREAD

**Issue by nicolastoulemont** [chakra-ui/chakra-ui#2356]
# Bug report

## TypeError on the Image width and height props

Version 1.0.0-rc.7 brings a new TypeError on the width and height props of the Image component when using responsive style props (`width={["100px", "200px"]}` for example.)

## To reproduce

1. Go to [this codesandbox](https://codesandbox.io/s/goofy-hoover-3ppiv?file=/src/App.tsx:451-477)

## Minimal reproduction

- [TypeScript CodeSandbox template](https://codesandbox.io/s/goofy-hoover-3ppiv?file=/src/App.tsx:451-477)

## Expected behavior

No TypeError

**Comment by segunadebayo** [comment]
I just pushed a fix for this. Thanks for catching it!
