### ISSUE TITLE
isFullWidth broken on Input in @chakra-ui/core": "^1.0.0-rc.7

### ISSUE THREAD

**Issue by hyliancoder** [chakra-ui/chakra-ui#2357]
# Bug report

## Describe the bug

When using `@chakra-ui/core@next` to utilize needed new code for [colorModeManager](https://next.chakra-ui.com/docs/features/color-mode#add-colormodemanager-optional) to use with Next.js it is breaking InputOptions for isFullWidth

## To reproduce

1. install @chakra-ui/core@next installed ("@chakra-ui/core": "^1.0.0-rc.7")
2. create `<Input isFullWidth={false}/>`
3.open console log and see error `Warning: React does not recognize the `isFullWidth` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isfullwidth` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

## Minimal reproduction

https://codesandbox.io/s/mystifying-framework-3e1ur?file=/src/App.js

## Expected behavior

Input is not displayed fullscreen, as it is in the stable branch

## System information

- OS: macOS
- Browser (if applies): Firefox, Chrome
- Version of @chakra-ui/core: 1.0.0-rc.7
- Version of Node.js: 14.2.0

**Comment by segunadebayo** [comment]
Hi @hyliancoder,

If you check the migration guide, you might see that `isFullWidth` has been deprecated for the Input. You can pass w="auto" to the Input to prevent that.

Cheers

**Comment by hyliancoder** [comment]
Ah I checked the migration guide under inputs and didn't see anything before I opened the pr, I'll double check the whole thing. I'm sure I just scanned over it elsewhere.

Thanks!

**Comment by hyliancoder** [comment]
Looks like it was under Checkbox but not mentioned elsewhere. Might want to add something under inputs as well or a overall listing of what things are depreciated from which Components

**Comment by blascsi** [comment]
I just ran into this issue as well, and it seems like `isFullWidth` is still present on the Input component documentation, and this information is also missing under the migration guide. 
I'm happy to open a PR to fix them if you want some help!

Also thank you for your work on this library!

**Comment by pianomansam** [comment]
> If you check the migration guide, you might see that isFullWidth has been deprecated for the Input. You can pass w="auto" to the Input to prevent that.


Passing `w="auto"` does not seem to work for me while `w="100%"` does.
