### ISSUE TITLE
FormHelperText disappears when isInvalid is set to true on the FormControl

### ISSUE THREAD

**Issue by Catchpowle** [chakra-ui/chakra-ui#2365]
# Bug report

## Describe the bug

When isInvalid is set to true on the FormControl the FormHelperText disappears

## To reproduce

```
<FormControl id="email" isInvalid={true}>
  <FormLabel>Email address</FormLabel>
  <Input type="email" />
  <FormHelperText>We'll never share your email.</FormHelperText>
</FormControl>
```

## Minimal reproduction

https://codesandbox.io/s/elegant-mendeleev-izs3w?file=/src/App.js

## Expected behavior

The helper text should still be there if the form is invalid

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of @chakra-ui/core: 1.0.0-rc.7
- Version of Node.js: v12.16.1

**Comment by avaragado** [comment]
I suspect the intent, not fully documented, is that isInvalid governs the visibility of both FormHelperText and FormErrorMessage. When IsInvalid is false, FormHelperText appears and FormErrorMessage doesn’t; and vice versa.

As a default this is probably fine, although I think the styles don’t quite align (the line heights for FormHelperText and FormErrorMessage are different, at least in my app) and it would look nicer if there were transitions on show/hide.

I agree there should be a way to opt out of this behaviour - there are cases where you might want both FormHelperText and FormErrorMessage to be visible at the same time.

**Comment by ivan-dalmet** [comment]
I agree, I understand why this can be a good idea. 
But a way to opt-out to this behaviour is needed.
Because if you put the `FormHelperText ` above the input and the `FormErrorMessage` below the behaviour expected is not to have the `FormHelperText` to disappear 😉

**Comment by dodas** [comment]
I think it is easy to hide the `FormHelperText` in userland, in case you want. On the other hand, it's currently impossible to show it if you want to.

I have sent a PR that makes it always render.
The `aria-describedby` stays the same - error text first (if any), then helper text (if any).
