### ISSUE TITLE
Setting Tabs's Default / Current Index

### ISSUE THREAD

**Issue by cm-hvg** [chakra-ui/chakra-ui#237]
I'm sure I'm missing something, I just need some guidance, or geussing this might be an easy fix.

What is the current way the set / control index of `Tabs` component. 

`defaultIndex` or `index` is not valid props for `@chakra-ui/core": "0.4.0`

**Comment by cm-hvg** [comment]
Update:

`index` props does work, however you need to use `//@ts-ignore`as the Props interface is correct

**Comment by segunadebayo** [comment]
The type definition of the Tabs component needs some updates. I'll update it in the next release

**Comment by segunadebayo** [comment]
I've updated the definitions for the Tabs component and will release a new version soon
