### ISSUE TITLE
Active selector not works for Tab component

### ISSUE THREAD

**Issue by kkatsuba** [chakra-ui/chakra-ui#2370]
# Bug report

## Describe the bug

If add `_hover` & `_active`  fields into Tab theme `_active` selector not works as expected

## To reproduce

1. Go to 'https://codesandbox.io/s/vigilant-hugle-40k06?file=/src/themee.ts'
2. Click on any tab button and hold left mouse button 
3. Expect to see red background for active state, but see green 

## Minimal reproduction
https://codesandbox.io/s/vigilant-hugle-40k06?file=/src/themee.ts'
![ezgif-7-bf1647fda8ab](https://user-images.githubusercontent.com/17414540/97600861-910dba80-1a1a-11eb-9cbf-4a743ece948a.gif)

## Expected behavior
When hold mouse button active selector should be applied

## System information

- OS: Windows
- Browser (if applies): Chrome
- Version of @chakra-ui/core: 1.0.0-rc.5

**Comment by segunadebayo** [comment]
@kkatsuba I believe this is related to the previous issue. I've pushed a fix for this.
