### ISSUE TITLE
[theme] zIndices type err

### ISSUE THREAD

**Issue by FengShangWuQi** [chakra-ui/chakra-ui#238]
**Describe the bug**
zIndices use StringOrNumber now, it can't work any, it should not be number?

![image](https://user-images.githubusercontent.com/17982705/68638380-57f3e600-053c-11ea-8bf2-ffc0de7dd569.png)

and I'm curious about why zIndices named zIndices instead of zIndex, why radii named radii instead of borderRadius or radius?

**Comment by segunadebayo** [comment]
The names `zIndices` and `radii` are directly from styled-system, that's why we're using it that way. Indeed, `zIndex` should be a `number` not `StringOrNumber`.

Thanks for that suggestion. I'll release a new version shortly
