### ISSUE TITLE
Select isReadOnly option not working as intended 

### ISSUE THREAD

**Issue by recursiveElk** [chakra-ui/chakra-ui#2381]
# Bug report

## Describe the bug

Using IsReadOnly flag on `<Select/>` doesn't appear to stop option editing.

## To reproduce
Add isReadOnly to Select component
```
<Select isReadOnly placeholder="Select option">
  <option value="option1">Option 1</option>
  <option value="option2">Option 2</option>
  <option value="option3">Option 3</option>
</Select>
```
## Minimal reproduction

https://codesandbox.io/s/blazing-architecture-zujfc?file=/src/App.tsx

## Expected behavior

> If true, prevents the value of the select from being edited.

## System information

- OS: [ macOS]
- Browser (if applies): [ Chrome]
- Version of @chakra-ui/core: [1.0.0-rc.7]

**Comment by segunadebayo** [comment]
Hi @recursiveElk,

The thing is, `readonly` cannot be applied to the native HTML select element. That's the reason it doesn't work. When you pass `isReadonly`, we pass `readonly` to the underlying select element.

As a walkaround, you can pass `pointerEvents:none` to disable select from being edited.

**Comment by recursiveElk** [comment]
Hi @segunadebayo, Would it be appropriate to remove the prop "isReadOnly" from the Select documentation in this case? Despite being a Box prop from what i understand, I think it's relatively confusing if it in fact can't be used on Select. 

I've submitted a PR, feel free to close if this is incorrect 👍 

Thanks for your time.
