### ISSUE TITLE
MenuList cannot be positioned correctly

### ISSUE THREAD

**Issue by ChiaJune** [chakra-ui/chakra-ui#2383]
# Bug report

## Describe the bug

If the width of the MenuButton changes dynamically and the placement is bottom-end, the MenuList is not positioned correctly

## Minimal reproduction

[https://codesandbox.io/s/menu-bug-fgll2?file=/src/MenuTest.tsx](https://codesandbox.io/s/menu-bug-fgll2?file=/src/MenuTest.tsx)

**Comment by segunadebayo** [comment]
Hi @ChiaJune,

We pushed a fix for this earlier today, it'll be released soon.

Cheers
