### ISSUE TITLE
Attempted import error: 'ChakraProvider' is not exported from '@chakra-ui/core'.

### ISSUE THREAD

**Issue by geoboom** [chakra-ui/chakra-ui#2387]
![image](https://user-images.githubusercontent.com/13282914/97783034-0373cb80-1bd0-11eb-9f06-1746d22892be.png)

```json
  "dependencies": {
    "@chakra-ui/core": "^0.8.0",
    "@emotion/core": "^10.0.35",
    "@emotion/styled": "^10.0.27",
    "emotion-theming": "^10.0.27",
    "formik": "^2.2.1",
    "framer-motion": "^2.9.4",
    "next": "9.5.5",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-icons": "^3.11.0"
  },
```
Using `"typescript": "^4.0.5"`. Happened as soon as I re-installed chakra-ui.

**Comment by ljosberinn** [comment]
ChakraProvider is only exported in v1. Please upgrade to v1 you want to use it, the latest `rc` is `1.0.0-rc.8`.

**Comment by geoboom** [comment]
> ChakraProvider is only exported in v1. Please upgrade to v1 you want to use it, the latest `rc` is `1.0.0-rc.8`.

Oh thanks I got lost. Didn't realize that there was `next` chakra subdomain.
