### ISSUE TITLE
Add a "code block" component?

### ISSUE THREAD

**Issue by ianstormtaylor** [chakra-ui/chakra-ui#2394]
# Feature request

## Is your feature request related to a problem? Please describe.

It would be nice to have a component for longer blocks of code. It seems like right now there is only `<Code>` which is for code mixed inline with text.

## Describe the solution you'd like

Having something very similar to how the code blocks in the docs are formatted would be amazing.

**Comment by dodas** [comment]
What are the requirements for such component? 

You can achieve the following result by adding 2 style props, although we could make a `variant` out of it:
<img width="751" alt="Screenshot 2020-12-10 at 01 30 29" src="https://user-images.githubusercontent.com/14360171/101705575-83bb0580-3a87-11eb-979b-d39c31624a64.png">

cc @ianstormtaylor @HarishJangra @gamegee @rohmanhm @yatish27

**Comment by remjx** [comment]
I've been able to style the `<Code>` element to suit my needs by adding a wrapping `<Box>` with border and adding `overflowX="scroll"`. Perhaps a variant as @dodas suggests would be a good addition that incorporates a border & background color based on colorMode.

**Comment by rohmanhm** [comment]
> What are the requirements for such component?
> 
> You can achieve the following result by adding 2 style props, although we could make a `variant` out of it:
> <img alt="Screenshot 2020-12-10 at 01 30 29" width="751" src="https://user-images.githubusercontent.com/14360171/101705575-83bb0580-3a87-11eb-979b-d39c31624a64.png">
> 
> cc @ianstormtaylor @HarishJangra @gamegee @rohmanhm @yatish27

Brilliant, thanks it suit my use cases.

**Comment by ianstormtaylor** [comment]
I was most curious about it having styling that matched the code blocks from Chakra's docs. Ideally even be able to figure out syntax highlighting as something Chakra can simplify if possible.

**Comment by remjx** [comment]
@ianstormtaylor here is the component for the Chakra docs' code blocks: https://github.com/chakra-ui/chakra-ui/blob/develop/website/src/components/codeblock/codeblock.tsx

**Comment by jswent** [comment]
If anyone is looking for the new link to the Chakra docs' code blocks: https://github.com/chakra-ui/chakra-ui-docs/blob/main/src/components/mdx-components/codeblock/codeblock.tsx

**Comment by danielsteman** [comment]
Unfortunately that link doesn't work either.

**Comment by jswent** [comment]
Are you sure? I just clicked on it and it seems to be working. Here's a permalink: https://github.com/chakra-ui/chakra-ui-docs/blob/9f1b555eb87b82437f2754342b1d7cab5d8bf5e3/src/components/mdx-components/codeblock/codeblock.tsx

**Comment by forrest-keller** [comment]
Here is my solution utilizing `Code` and [prism-react-renderer's](https://www.npmjs.com/package/prism-react-renderer) `Highlight` component.

```ts
<Highlight
  language={node.language || ""}
  code={node.code}
  theme={themes.okaidia}
>
  {({ style, tokens, getLineProps, getTokenProps }) => (
    <Code
      padding={2}
      rounded="md"
      key={key}
      display="block"
      whiteSpace="pre"
      backgroundColor={style.backgroundColor}
      overflow="auto"
    >
      {tokens.map((line, i) => (
        <div key={i} {...getLineProps({ line })}>
          {line.map((token, key) => (
            <span key={key} {...getTokenProps({ token })} />
          ))}
        </div>
      ))}
    </Code>
  )}
</Highlight>;
```
<img width="756" alt="Screenshot 2024-01-14 at 2 47 29 PM" src="https://github.com/chakra-ui/chakra-ui/assets/31026224/a04658b7-c0e8-4e8e-99b6-88825b32d0b6">
