### ISSUE TITLE
MenuItem doesn't respect the as prop

### ISSUE THREAD

**Issue by bogdansoare** [chakra-ui/chakra-ui#2397]
# Bug report

## Describe the bug

`MenuItem` doesn't respect the `as` prop. 
Version `1.0.0-rc.8` broke this behaviour.

## Minimal reproduction

https://codesandbox.io/s/awesome-goldstine-od3lu?file=/src/App.js

## Expected behavior

`MenuItem` should respect the `as` prop, this is important when using external links or router links

**Comment by ljosberinn** [comment]
fixed in b7d71c1011243de34d899d6bb7f7d51d00532e2a, will be in the next release :)

**Comment by bogdansoare** [comment]
Thanks @ljosberinn, looking forward to that release :)
