### ISSUE TITLE
AlertDialog isn't opened when using MenuItem as trigger element

### ISSUE THREAD

**Issue by s-kris** [chakra-ui/chakra-ui#2398]
# Bug report

## Describe the bug
Invoking an AlertDialog with MenuItem isn't opening the modal but verified that click is registered in the onClick handler.

## To reproduce

1. Declare MenuButton (with `const MenuButtonAsButton = MenuButton as React.FC<MenuButtonProps & ButtonProps>;` for ts)
2. Declare `MenuItems`
3. Write AlertDialog with a MenuItem as shown here: https://chakra-ui.com/alertdialog
4. When you click on that MenuItem, modal won't open.

## Minimal reproduction
https://codesandbox.io/s/upbeat-sanderson-ox4vr

## Expected behavior
AlertDialog opens when clicked on the trigger element as shown here: as shown here: https://chakra-ui.com/alertdialog

## System information

- OS: macOS 10.15.4
- Browser (if applies): FireFox 81.0.2
- Version of @chakra-ui/core: 0.8.0
- Version of Node.js: 14.4.0

**Comment by masiamj** [comment]
@s-kris I'm seeing very similar issues with both AlertDialog and Modal on RC 8

**Comment by s-kris** [comment]
@masiamj I found that this bug isn't there on RC 2. Can you confirm this?

**Comment by s-kris** [comment]
It is fixed in 1.0.0

**Comment by prenaissance** [comment]
If anyone is having a similar issue, make sure that your Menu does not have the `isLazy` flag enabled, as that removes the dialog from the dom on focus lost.
