### ISSUE TITLE
TypeScript error when assigning a responsive style to "color" attribute

### ISSUE THREAD

**Issue by aabuhijleh** [chakra-ui/chakra-ui#2399]
# Bug report

## Describe the bug

I'm getting this typescript error

```
Type 'string[]' is not assignable to type 'string | (string & (string | number | symbol | null)[]) | (string & { [x: string]: string | number | symbol | undefined; [x: number]: string | number | symbol | undefined; }) | undefined'.
```

when assigning an array to "color" attribute

```tsx
<Flex color={["white", "white", "primary.700", "primary.700"]}></Flex>
```

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of @chakra-ui/core: 0.8.0
- Version of Node.js: 12.5.0

**Comment by ljosberinn** [comment]
![image](https://user-images.githubusercontent.com/29307652/97899608-cfb4b500-1d39-11eb-8d4b-2d5cdcdad88d.png)
![image](https://user-images.githubusercontent.com/29307652/97899620-d4796900-1d39-11eb-8f85-e6ccb3f3bc90.png)

works fine here, please provide a minimum reproduction

**Comment by aabuhijleh** [comment]
@ljosberinn ok thanks. Sorry typed Enter by mistake before completing entering the issue description. 

<img width="845" alt="Screen Shot 2020-11-02 at 7 36 50 PM" src="https://user-images.githubusercontent.com/42934634/97900025-c845d980-1d42-11eb-8646-87d12f209218.png">

I'm getting this with vscode. Will try to provide a minimal repo.

**Comment by ljosberinn** [comment]
Which version are you on? Which `@types/react` version do you have installed? :)

**Comment by aabuhijleh** [comment]
It seems I didn't have it installed and everything was running fine. I just installed it (16.9.55) and restarted vscode. Same issue.

**Comment by ljosberinn** [comment]
And of chakra?

**Comment by aabuhijleh** [comment]
These are my deps <img width="866" alt="Screen Shot 2020-11-02 at 7 43 51 PM" src="https://user-images.githubusercontent.com/42934634/97900723-c2042d00-1d43-11eb-804f-8732d967bb96.png">

**Comment by ljosberinn** [comment]
Ah, still `v0`. Types have been docked onto JS back then, I recommend upgrading to `v1` if your project is still in an early stage, it's release is in the near future.

We have new docs [here](https://next.chakra-ui.com/docs/getting-started).
I recommend jumping right to the latest release candidate: `1.0.0-rc.8` and before installing again, removing `node_modules`, `yarn.lock` | `package-lock.json` and the no longer needed dependencies:
```diff
- "@chakra-ui/core": "^0.8.0",
+ "@chakra-ui/core": "1.0.0-rc.8",
+ "framer-motion": "latest",
- "@emotion/core": "^10.0.27",
- "@emotion/styled": "^10.0.27",
- "emotion-theming": "^10.0.27",
```

and then reinstall.

**Comment by aabuhijleh** [comment]
Thanks for the fast reply :)

**Comment by aabuhijleh** [comment]
I followed the migration steps from v0 to v1 as described in the docs [here](https://next.chakra-ui.com/docs/migration)

I deleted `node_modules` and installed "@chakra-ui/core": "^1.0.0-rc.8" and "framer-motion": "^2.9.4"

No matter what I do I keep getting this "Module not found: Can't resolve '@emotion/core'"

<img width="990" alt="test" src="https://user-images.githubusercontent.com/42934634/97907886-9c305580-1d4e-11eb-8ad3-7428371b4943.png">

I tried to provide a minimal example with https://github.com/vercel/next.js/tree/canary/examples/with-chakra-ui-typescript but it is working for them

I can't understand why I'm having this error. @ljosberinn any idea of why I'm getting this? Should I open a separate issue?

**Comment by ljosberinn** [comment]
could you go into `node_modules/@chakra-ui/css-reset/package.json` and check the version? I presume the order got mixed up.

**Comment by aabuhijleh** [comment]
node_modules/@chakra-ui/css-reset/package.json => "version": "1.0.0-rc.8"

It looks correct :(

**Comment by ljosberinn** [comment]
alright, what do you currently have in your _app.js?

**Comment by aabuhijleh** [comment]
It worked after deleting package-lock.json.

It looks like node_modules was getting cached somehow even though I did rm -rf node_modules several times

Thanks a lot!

**Comment by ljosberinn** [comment]
`package-lock` is actually the cache for node_modules, so that explains it :)

**Comment by aabuhijleh** [comment]
And you it looks like you told me to remove the lock file in an earlier comment but I didn't pay enough attention and just removed node_modules. Sorry for the trouble :)

**Comment by ljosberinn** [comment]
Haha no worries, let's say I've been preaching `remove node_modules and lockfile` a while now both in issues and on discord 😆
