### ISSUE TITLE
NumberInput native spinners are visible [Firefox 69.0.0] [Firefox 67.0.2]

### ISSUE THREAD

**Issue by valstu** [chakra-ui/chakra-ui#24]
Native input type=number spinners (up/down buttons) are visible and overlapping with chakra-ui implementation on `<NumberInput />` component.

![image](https://user-images.githubusercontent.com/647861/64406736-40573780-d08b-11e9-9212-c5333b61596f.png)

Tested with following browsers:
Firefox 67.0.2 (Mac)
Firefox 69.0.0 (Mac)

**Comment by segunadebayo** [comment]
Thanks for this issue @valstu .

I guess we missed the CSS to hide the spinners on Firefox. We'll fix this and release a patch soon.

**Comment by segunadebayo** [comment]
I've resolved this and will release a patch soon
