### ISSUE TITLE
Ability to style Container and Divider components with the theme API (extendTheme) (v1)

### ISSUE THREAD

**Issue by ryanerras** [chakra-ui/chakra-ui#2405]
# Feature request

## Is your feature request related to a problem? Please describe.

I'm currently unable to customise certain components in the theme configuration. With both Container and Divider I can see valid use cases where baseStyles/defaults would be useful (max-width for container + padding for divider).

## Describe the solution you'd like

I'd like to see the above components added to the theme spec to make them themeable.

## Describe alternatives you've considered

The current alternate solution is to create a wrapper component around these Chakra components in order to set the defaults.

## Additional context

The suggested components are specific to v1 of Chakra.

**Comment by cereallarceny** [comment]
I'd love this as well. Just adding my support!

I had to do this the other day:

```js
styles: {
  global: {
    '.chakra-divider': {
      borderColor: '#BCBCBC !important',
      opacity: 1,
    },
  }
}
```

Gross! 🤮
