### ISSUE TITLE
Tooltip is not working on custom/nested components even when using forwardRef

### ISSUE THREAD

**Issue by gamegee** [chakra-ui/chakra-ui#2406]
# Bug report

## Describe the bug
Tooltip is not working on custom/nested components even when using `forwardRef`

## To reproduce
It looks like when you have custom tooltip, the ref is not passed correctly 🤔 :
```tsx
const CustomTooltip = forwardRef(({ children }, ref) => {
  return (
    <Tooltip ref={ref} bg="red" label="hello">
      {children}
    </Tooltip>
  );
});

const CustomBox = forwardRef(({ children }, ref) => {
  return (
    <Box ref={ref} w={200} bg="blue" color="white" padding={10}>
      {children}
    </Box>
  );
});

function App() {
  return (
    <ThemeProvider theme={theme}>
      <Box mt={20}>
        <CustomTooltip>
          <CustomBox>Not working</CustomBox>
        </CustomTooltip>
      </Box>
      <Box mt={20}>
        <CustomTooltip>
          <Box bg="blue" color="white" w={200}>
            Working
          </Box>
        </CustomTooltip>
      </Box>
    </ThemeProvider>
  );
}
```

## Minimal reproduction
You can reproduce the error on this code sandbox:
https://codesandbox.io/s/dank-smoke-9p6e2?file=/src/index.js

- Try to hover 1st box => won't work
- Try to hover 2nd box => will work

## Expected behavior
- The tooltip should work even if I pass custom component as children
- Tooltip abstraction should be able to work

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of @chakra-ui/core:  1.0.0-rc.8
- Version of Node.js: -

## Additional context
Not sure but it may be related to this popperJS issue: #2382

**Comment by kkatsuba** [comment]
It works. need manually "forward" props. It's ugly solution, but works. In you example make changes

```jsx
const CustomBox = forwardRef(({ children, ...props}, ref) => {
  return (
    <Box ref={ref} w={200} bg="blue" color="white" padding={10} {...props}>
      {children}
    </Box>
  );
});
```

**Comment by ljosberinn** [comment]
Yup, that should be the solution, you're assigning the ref but not forwarding the props `Tooltip` passes down.

**Comment by gamegee** [comment]
Yes it works 🙏 🙂 
The only drawback is I have to forwardRef in every custom component.
