### ISSUE TITLE
Theme is not passed to @emotion/styled components

### ISSUE THREAD

**Issue by klekowskim** [chakra-ui/chakra-ui#2407]
# Bug report

## Describe the bug

When using new v1 together with ChakraProvider, my components defined with @emotion/styled, do not receive theme object on props.

## To reproduce

styled component
```
const Container = styled.div(
  {
    display: "flex",
    height: "100%",
    overflow: "hidden"
  },
  (props) => {
    console.log(">>>props", props.theme); // <--- theme is an empty object
    return {};
  }
);

const rootElement = document.getElementById("root");
render(
  <ChakraProvider theme={theme}>
    <Container>Welcome to Chakra + TS</Container>
  </ChakraProvider>,
  rootElement
);
```

## Minimal reproduction

https://codesandbox.io/s/interesting-kapitsa-yhkfh?file=/src/index.tsx

## Expected behavior

theme is available in styled components props

## Screenshots

N/A

## System information

- OS: macOS
- Browser (if applies): -
- Version of @chakra-ui/core: 1.0.0-rc.8
- Version of Node.js: -

## Additional context

N/A

**Comment by ljosberinn** [comment]
I don't think this is a usecase chakra wants to support, instead, leverage built-in layout primitives such as `Flex` or `Box` for this or alternatively use the style-free `chakra` API which is more or less `styled`:

```js
import { chakra } from '@chakra-ui/core';

const Container = (props) => <chakra.div display="flex" height="100%" overflow="hidden" {...props} />;
```

**Comment by klekowskim** [comment]
But is it a problem to support it? It was working before and as far as I know, underneath, chakra is using emotion context.

**Comment by ljosberinn** [comment]
Fwiw I'm not too familiar with emotion, but from what I understand, it's most likely a version conflict as in youre importing a different version of emotion than chakra is, so you end up trying to use a different context provider than the one chakra is using.

You can simply remove your emotion dependencies and you see the theme getting logged.

Already for the sake of consistency I wouldn't recommend doing this, regardless of what chakra wants you to do or any other UI Lib. Unless you - and whoever might be working on the project too - are careful, it's very easy to end up with an inconsistent UI.

**Comment by klekowskim** [comment]
Is there a reason why chakra defines emotion strict version?

**Comment by ljosberinn** [comment]
emotion doesn't follow semver and has frequent breaking changes, iirc chakra e.g. doesnt run properly with emotion 10.1 right now
