### ISSUE TITLE
[Select] doesn't pass props to the actual select element

### ISSUE THREAD

**Issue by jaredpalmer** [chakra-ui/chakra-ui#241]
`<Select>` doesn't pass props to the actual `select` element, but to a wrapper `div`.

**Comment by jaredpalmer** [comment]
It's also unclear why we need a wrapper div in the first place. It seems like it is just used for the placement of the chevron. A better way to do this is to use a background image in css of a inlined svg.

**Comment by segunadebayo** [comment]
@jaredpalmer, that's a good point.

I was planning to make the API a bit more declarative so the user can decide to get rid of the icon and use a background image.

Here's what I have in mind:

```jsx
<SelectWrapper>
  <Select />
  <SelectIcon />
</SelectWrapper>
```

`SelectWrapper` and `SelectIcon` can then be ignored completely if you don't need them.

**Comment by zaguiini** [comment]
Title of this issue is wrong.
