### ISSUE TITLE
StackDivider not respecting responsive styles

### ISSUE THREAD

**Issue by jivinivan** [chakra-ui/chakra-ui#2411]
# Bug report

## Describe the bug

Responsive styles are not being applied to StackDivider.

## To reproduce / minimal reproduction

![image](https://user-images.githubusercontent.com/1165669/98108489-0984d900-1e6a-11eb-80e9-37adb34dae38.png)

## Expected behavior

Responsive styles should be applied to StackDivider (was working in rc.3)

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of @chakra-ui/core: 1.0.0-rc.8
- Version of Node.js: 12.19.0

**Comment by segunadebayo** [comment]
Thanks for catching this @jivinivan.

I just pushed a fix for this. We'll release an update shortly
