### ISSUE TITLE
NumberInput isDisabled sets only input field disabled 1.0.0-rc.8

### ISSUE THREAD

**Issue by Schnueggel** [chakra-ui/chakra-ui#2412]
# Bug report

## Describe the bug

Setting NumberInput isDisabled to true only disables the input itself but the steppers are still working. I can see that they react to aria-disabled but nothing i do is setting this attribute.

## To reproduce

https://codesandbox.io/s/vigilant-dewdney-uo2ye?file=/src/index.js

I put isDisabled on the Stepper Components itself too. Nothing helped.

## Expected behavior

disable the whole component.

## System information

- Windows 10
- Browser: Chrome
- Version of @chakra-ui/core: 1.0.0-rc.8
- Version of Node.js: 14.4.0

**Comment by segunadebayo** [comment]
Thanks for catching this @Schnueggel.

We just pushed a fix for it. We'll release it shortly
