### ISSUE TITLE
Checkbox and Switch default value broken with React Hook Form

### ISSUE THREAD

**Issue by alessandropisu** [chakra-ui/chakra-ui#2413]
# Bug report

## Describe the bug

Boolean inputs (like Checkbox and Switch) used with React Hook Form don't read default value passed in UseForm method. 0.8 version works instead.

## Minimal reproduction

Example: https://codesandbox.io/s/sparkling-wind-z6zmv?file=/src/App.js

## System information

- OS: macOs
- Browser (if applies): Chrome
- Version of @chakra-ui/core: 1.0.0-rc.8
- Version of react-hook-form: 6.10.1 (also with oldest version the problem persists)
- Version of Node.js: 14.9.0

**Comment by segunadebayo** [comment]
Thanks for reporting this @alessandropisu.

I've just pushed a fix for this and tested that it works correctly.
