### ISSUE TITLE
[RC.8/Menu] Performance issues using the <Menu/> component

### ISSUE THREAD

**Issue by tonyjmartinez** [chakra-ui/chakra-ui#2415]
# Bug report

## Describe the bug

I am still seeing performance issues using the `<Menu/>` component after upgrading to `RC.8`.

## To reproduce

Reproduction: https://github.com/tonyjmartinez/card-menu-performance-repro

1. npm i && npm start
2. Click the button to toggle rendering of `<Card/>`'s
3. Performance lags rendering the cards.
4. Check for TODO's that mark areas to comment out to make sure that other components aren't causing the lag.
5. If everything gets commented out besides the `<Menu/>`, the performance lag remains.

## Minimal reproduction

https://github.com/tonyjmartinez/card-menu-performance-repro

## Expected behavior

I expect to be able to render 30-50 menus at a time without significant performance issues.

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of @chakra-ui/core: 1.0.0-rc.8
- Version of Node.js: 10.15.3

**Comment by TheThirdRace** [comment]
I can confirm a similar problem on my side.

I just updated from 1.0.0-rc.5 to 1.0.0-rc8 and now my pages are completely freezing in Chrome and Firefix (haven't tried others).

As soon as I don't render the <Menu>, the freezing is gone.

On another note, I'm having a lot of troubles migrating 1.0.0-rc5 to rc8, there seems to have a lot of breaking changes in many components. Everything that use an animation seems wonky, themes aren't applied the same anymore, etc. I understand we're working on an rc version, but it's very discouraging... Furthermore, my js bundle jumped 20 KB after migrating, which is a jump of 18% in my case.

**Comment by with-heart** [comment]
@TheThirdRace Please open separate issues for your other problems so we can accurately investigate each!

**Comment by segunadebayo** [comment]
@tonyjmartinez  We created an `isLazy` prop for the Menu which helps improve performance when rendering multiple menus at the same time.

**Comment by tonyjmartinez** [comment]
> @tonyjmartinez We created an `isLazy` prop for the Menu which helps improve performance when rendering multiple menus at the same time.

@segunadebayo my reproduction is using `isLazy`. Inside `MenuContainer.tsx`.

**Comment by segunadebayo** [comment]
@tonyjmartinez Yes, I can see that. Taking a look at the `package.json`, I see you have various versions of Chakra installed.

```json
  "@chakra-ui/core": "next",
  "@chakra-ui/theme": "^1.0.0-next.8",
  "@chakra-ui/theme-tools": "^1.0.0-next.7"
```

Can you try to pin them to `1.0.0-rc.8`?

```json
  "@chakra-ui/core": "1.0.0-rc.8",
  "@chakra-ui/theme": "1.0.0-rc.8",
  "@chakra-ui/theme-tools": "1.0.0-rc.8",
```

**Comment by segunadebayo** [comment]
Update: I tested it with the version update and it seems to work well. Kindly try and let me know.

**Comment by tonyjmartinez** [comment]
@segunadebayo thanks for the suggestion, I tried updating the packages and I'm still seeing performance issues - takes about a second for the cards to show up. If I comment out `<MenuList/>` in `MenuContainer.tsx`, the performance improves considerably.

We're trying to use this in a virtualized list, and the performance is much worse when we include the menu than when we leave it out.

**Comment by brennanfife** [comment]
Experiencing a bit of weird behavior that seems to be related. When clicking outside the menu, it only closes when the click is right above the menu. Otherwise, clicks to the right, left, and bottom won't close the menu.

![chakra-ui-menu](https://user-images.githubusercontent.com/31396350/99151163-dfe46280-265e-11eb-9194-80fbb95d6f9e.gif)

[CodeSandbox demo](https://codesandbox.io/s/chakra-ui-menu-bqzyl)

**Comment by ljosberinn** [comment]
@brennanfife this only happens if you're clicking outside of the viewport. #root has only the height of your button:
![image](https://user-images.githubusercontent.com/29307652/99151693-44bead80-269d-11eb-95c0-da0291ca7c48.png)

adding `height: 100vh;` to the App container resolves it

**Comment by brennanfife** [comment]
@ljosberinn False alarm, you're correct
