### ISSUE TITLE
Typescript Auto complete does not work for component props

### ISSUE THREAD

**Issue by sidoshi** [chakra-ui/chakra-ui#242]
**Describe the bug**
The auto complete for component props value does not seem to work. I am not sure if this is a bug or something new that needs to be implemented altogether. But ideally I think it would be a great DX if we get the auto complete values when for example we are entering a color prop on the box and I can select from all the available colors from the theme? I am not sure if this is possible or not. Would love to spend some time on this if required.

**Expected Behavior**
I want to get suggestions when I type a style prop on a component based on the custom theme. For example If I type `<Box bg="|"></Box>`, (`|` is the position of the cursor), I want to get autocompelete values for all the possible options based on my theme or default theme.

**Comment by segunadebayo** [comment]
Hi @sidoshi,

I believe this will need some TypeScript gymnastics. Your suggestion will definitely lead to a better DX.

If you have some time to look into it, I'll appreciate that. Otherwise, I'll look into it later.

**Comment by sidoshi** [comment]
Hey @segunadebayo, so I already tried to take a look into it. Basically this is right now impossible to implement on `chakara-ui` code because styled-system itself does not support it and seems like it has no plan to as well. So unless we decide to fork styled-system, I am not sure how we can proceed further.

Related comment on styled-system: https://github.com/styled-system/styled-system/issues/480#issuecomment-516492291

**Comment by segunadebayo** [comment]
Yes, that's the main problem.

We could try forking `styled-system` and see if we can get this to work.

I saw this library: https://github.com/jaridmargolin/properly-styled/tree/master/packages, and I believe it has somethings we might find useful.

I'm open to collaborating with you on this one.

**Comment by sidoshi** [comment]
Yes, I can try and fork styled-system and see if I can get it to work with our use case. I will also check properly-styled and see how it fits. BTW thanks for being open to changes 👍

**Comment by segunadebayo** [comment]
@sidoshi, let me know when you have something to show and I can re-open this issue.

Can't wait to see what you come up with.
