### ISSUE TITLE
Output Variant Name on component

### ISSUE THREAD

**Issue by hutber** [chakra-ui/chakra-ui#2420]
Related: https://github.com/chakra-ui/chakra-ui/issues/682 

Hey guys, I would also love to have something similar working to this:
![image](https://user-images.githubusercontent.com/1344898/98367100-f5d5a000-202c-11eb-9acd-f198472f3267.png)

The selected H2 is actually a variant book4...

              <Heading as="h2" variant="book4">

It would be fantastic to be able to get this outputting too, something like this:

             <h2 class="chakra-heading book4">"

**Comment by segunadebayo** [comment]
Hi @hutber,

Can you explain the reason behind this request as it relates to your project?

**Comment by hutber** [comment]
Thanks @segunadebayo for coming back to me. It may be that in the past I have used material-ui and they base their styles on named classes, but I am having great difficulty seeing which of my own variants are being used and where when trying to debug other people's code.

For example, we have extensive variants throughout ourcode base, I would imagine around 50 of such things. It is currently impossible to know which style is being used when doing a string search for the component:
```
    blogTitle: {
      fontSize: 5,
      letterSpacing: "0.16em",
      textTransform: "uppercase",
      lineHeight: 5,
      marginTop: "1rem",
      marginBottom: "0.5rem",
    },
    blogSubTitle: {
      fontSize: 3,
      fontWeight: "normal",
      letterSpacing: "0.04em",
      lineHeight: 5,
    },
```

**Comment by segunadebayo** [comment]
Hi, Thanks for opening this issue.

We won't be working on this as we're not convinced it's worth adding to the core of Chakra UI. Feel free to add on your end by passing `data-variant` on your components, or other solutions.

Cheers
