### ISSUE TITLE
Global Styles Variant in Themes

### ISSUE THREAD

**Issue by hutber** [chakra-ui/chakra-ui#2421]
Currently I have a large list of variants outlined by our design team. Something alone the lines of this, but 250 lines long:
```javascript
  light0: {
    fontFamily: "light",
    fontWeight: "light",
    fontSize: 0,
    lineHeight: 0,
  },
  light1: {
    fontFamily: "light",
    fontWeight: "light",
    fontSize: 1,
    lineHeight: 1,
  },
  light2: {
    fontFamily: "light",
    fontWeight: "light",
    fontSize: 2,
    lineHeight: 2,
  },
  etc
```

To add these variants for all components that will use it I need to do:
```
const appTheme = {
  components: {
     Button: {
         ...typographyStyles,
         ...etc
     }
     Text: {
         ...typographyStyles,
         ...etc
     }
     Headings: {
         ...typographyStyles,
         ...etc
     }
  }
}
```

This is creating a rather large bloat on the codebase, is it possible to have a global variant set, to share the variants between all the components without duplicating this large text based object?

**Comment by segunadebayo** [comment]
Hi @hutber,

You will need a combination of the `textStyle` documented here:
https://next.chakra-ui.com/docs/features/text-and-layer-styles

and the `apply` prop not yet documented but can be seen here:
https://github.com/chakra-ui/chakra-ui/blob/develop/packages/styled-system/tests/css.test.ts#L193
