### ISSUE TITLE
[Menu] Initial placement of MenuList is incorrect

### ISSUE THREAD

**Issue by la55u** [chakra-ui/chakra-ui#2424]
# Bug report
When opening the Menu via MenuButton the placement of MenuList is incorrect. 

## Describe the bug
In the example the placement is set to `bottom-start` but as you can see on the screenshot below, it is not being applied. When modifing the placement to let's say `bottom` it works properly, and then rewiting it back to `bottom-start` it works this time perfectly. If you refresh the CodeSandbox browser it won't be correct any more... Somehow the bug only affects the first page load.

## Minimal reproduction
https://codesandbox.io/s/holy-snow-hovg5?fontsize=14&hidenavigation=1&theme=dark

## Expected behavior

MenuList should be positioned correcty on the first page load.

## Screenshots

![image](https://user-images.githubusercontent.com/30611343/98384181-bf5c4d00-204d-11eb-9403-2ab8da12569c.png)

## System information

- OS: Fedora 33 
- Browser: Firefox Developer Edition 83.0b8 
- Version of @chakra-ui/core: 1.0.0-rc.8

**Comment by afestbaum** [comment]
I'm experiencing the same issue with @chakra-ui/core: 1.0.0-rc.8 and Firefox 82.0.2. The strange thing... if you load the page and open the Firefox Devtools before clicking the Menu, it works...

**Comment by segunadebayo** [comment]
Hi @la55u,

I fixed this in a recent PR and will release v1 shortly so you can try again.

If the issue still persists, I will re-open this.

Thank you
