### ISSUE TITLE
Add documentation for the `chakra` factory function

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#2425]
Currently the only mention of the `chakra` function is a _very_ small section in the "The as prop" guide: https://next.chakra-ui.com/guides/as-prop#option-3-use-the-chakra-factory-function

**Comment by segunadebayo** [comment]
Working on this!

**Comment by with-heart** [comment]
@segunadebayo You're a machine!

**Comment by segunadebayo** [comment]
Done!
