### ISSUE TITLE
Accordion within a Drawer starts opened even if asked to be closed

### ISSUE THREAD

**Issue by TheThirdRace** [chakra-ui/chakra-ui#2427]
# Bug report

## Describe the bug

An `<Accordion>` within a `Drawer` starts opened when you open the `Drawer`

## To reproduce

1. Open the Code Sandbox provided
2. Click on the green `Accordion` and it behaves as expected, meaning it starts closed, opens on the first click and close on the second click
3. Click on the blue **Open Drawer** button
4. The red `Accordion` within the Drawer starts opened while it shouldn't (you can also see the chevron is pointing down, which means it's supposed to be closed)
5. Click on the red `Accordion` and it doesn't close either, but now you can see the chevron pointing up like it should once the `Accordion` is opened
6. Click again on the red `Accordion` and it will close correctly now, the state is now synched with the right values.
7. Close the `Drawer` and open it again, the red `Accordion` is behaving badly again.

## Minimal reproduction
https://codesandbox.io/s/cool-lumiere-k15y0?file=/src/App.js

## Expected behavior

The `Accordion` within the `Drawer` should start closed when opening the Drawer. If no props is passed to the Accordion to tell it to be opened (index or defaultIndex), it should be closed.

## System information

- OS: Windows 10 (2004)
- Browser (if applies): Chrome, Firefox, Edge
- Version of @chakra-ui/core: 1.0.0-rc.8
- Version of Node.js: 12.18.2

## Additional context

It worked perfectly fine with **@chakra-ui/core: 1.0.0-rc.5**.

Between then (rc.5) and now (rc.8), Framer-Motion was introduced.

My first guess would be the Accordion is now looking for a Context Provider up the chain and is finding the `Drawer` provider instead of his own. Since the `Drawer` has a `isOpen` prop, it might clash with the `Accordion`'s.

You can find an **rc.5** working example at [beta.thethirdrace.com](https://beta.thethirdrace.com). Simply resize your browser under 768px and you'll have the mobile menu kicking in.

**Comment by TheThirdRace** [comment]
I would also add that there have been 6 commits since 1.0.0-rc.5 (last 30 days) and this one has the description: "fix: isopen logic for accordion item"

https://github.com/chakra-ui/chakra-ui/commit/6549fca6eedb01010bc98599d4bbae6f39287545#diff-4aa900a477fc890333426a71693128c02a947b3656e0d3185dd88daaef0d9469

If I had to bet, something in there could be the culprit.

For easier reference, here is the link for all the commits on Accordion.tsx in the last 30 days (October 6 is the first commit after 1.0.0-rc.5 which was working)
https://github.com/chakra-ui/chakra-ui/commits/develop/packages/accordion/src/accordion.tsx

**Comment by segunadebayo** [comment]
We fixed this in a recent commit. I just confirmed that this works as expected.

Cheers

**Comment by hems** [comment]
I just updated the sandbox to latest version and i can confirm the bug was fixed.

https://codesandbox.io/s/patient-https-cgzj4?file=/src/App.js

Unfortunately on my app updating to latest version broke other things, which I'm trying to figure out now.

**Comment by TheThirdRace** [comment]
@hems Might not be this, but at some point Chakra changed the drawer "parts" to use the Modal parts (see theme). Actually, a drawer is a modal but stuck at the edge instead of being centered.
