### ISSUE TITLE
Checkbox does not update when isChecked props changed

### ISSUE THREAD

**Issue by hmtri1011** [chakra-ui/chakra-ui#2428]
# Bug report

## Describe the bug
Checkbox component does not update when isChecked props changed from undefined to true.
It did work when changing from false to true but not from undefined to true.

## To reproduce

1. Init render with isChecked = undefined
2. Fetch data from server and update isChecked = true
3. Component is re-rendered but Checkbox does not check

## Minimum Reproduce
https://codesandbox.io/s/floral-waterfall-7i4ip?file=/src/App.tsx:0-549

## System information

- OS: macOS
- Version of @chakra-ui/core: 1.0.0-rc.8

**Comment by segunadebayo** [comment]
Hey @hmtri1011,

Passing an `undefined` value to `isChecked` implies it is an uncontrolled component. To ensure it works as expected (controlled), kindly set the initial `selected` state of your component to `false`.

```jsx
// change from this
const [selected, setSelected] = React.useState<boolean>();

// to this
const [selected, setSelected] = React.useState<boolean>(false);
```

PS: By the way, you should also wrap the entire application with `ChakraProvider` for the styles to get applied correctly.

Cheers.
