### ISSUE TITLE
[Stack] Element inside stack overrides marginLeft so I can't add a custom marginLeft

### ISSUE THREAD

**Issue by BrandoIsNotASword** [chakra-ui/chakra-ui#2431]
# Bug report

Stack component adds a margin override to the elements inside of it. So, for example, can add margin left to he last element inside a Stack component.

## Screenshots

With Stack

![image](https://user-images.githubusercontent.com/3867650/98447867-3baa6b00-20f6-11eb-8779-01968bc0ac82.png)

![image](https://user-images.githubusercontent.com/3867650/98447873-482ec380-20f6-11eb-9712-cb9793f95804.png)

Without Stack

![image](https://user-images.githubusercontent.com/3867650/98447883-5bda2a00-20f6-11eb-9bfa-234a37438c7f.png)

**Comment by segunadebayo** [comment]
Yes, this is by design. If you intend to add a custom margin-left:

- Increase the `spacing`
- Wrap the stack item in a <Box/>
- Try multiple `<Stack/>`s for each group.
- Change the layout to use a `<Flex/>` or `<Grid/>`. `<Stack/>` is most likely not the right pattern
