### ISSUE TITLE
Elements within Accordion are focusable while Accordion closed

### ISSUE THREAD

**Issue by TheThirdRace** [chakra-ui/chakra-ui#2432]
# Bug report

## Describe the bug

Using the `Tab` key, you can focus elements within a closed `Accordion`.

This is a new behavior, it was working fine in **1.0.0-rc.5**.

## To reproduce

1. Open the codesandbox provided
2. Click on a blank space on the page
3. Press `Tab` key until it puts focus on the green `Accordion` (which is with a `closed` status)
4. Press `Tab` key again and it will focus on the `Link` inside the closed `Accordion`

You can see the `Link` is focused because the browser will show the url in a tooltip at the bottom like they usually do when focusing on a link.

## Minimal reproduction
https://codesandbox.io/s/cool-lumiere-k15y0?file=/src/App.js
-->

## Expected behavior

As with 1.0.0-rc.5, I would expect to not be able to focus on the `Link` within the closed `Accordion`

## System information

- OS: Windows 10 (2004)
- Browser: Chrome for sure, haven't tested anything else
- Version of @chakra-ui/core: 1.0.0-rc.8
- Version of Node.js: 12.18.2

## Additional context

There are many components that aren't behaving as before since the move to Framer Motion. I don't know if it's directly related to how Framer Motion is doing the animation or if it's how the components were changed to support it.

In any case, I've had trouble migrating from 1.0.0-rc.5 to 1.0.0-rc.8 because of Menu, Accordion and Drawer, all 3 components are now using Framer Motion.

I already raised the issues for Accordion and Drawer, but I had to move away from Preact for the Menu as it wouldn't work anymore (the move added 60KB to my js bundle, which is not trivial on a 115KB bundle...). So there's something that changed important compatibility stuff from 1.0.0-rc.5 to 1.0.0-rc.8.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. Thanks for reporting.
