### ISSUE TITLE
Error: 'Transition' is not exported from '@chakra-ui/transition'

### ISSUE THREAD

**Issue by jhenriquevissotto** [chakra-ui/chakra-ui#2433]
```
error - ./node_modules/@chakra-ui/toast/dist/esm/toast.js
Attempted import error: 'Transition' is not exported from '@chakra-ui/transition'.
Could not find files for /toasts in .next/build-manifest.json
Could not find files for /toasts in .next/build-manifest.json
```

Not running in Next.js 10

```javascript
  "dependencies": {
    "@chakra-ui/core": "^0.8.0",
    "@chakra-ui/icons": "^1.0.0-next.3",
    "@chakra-ui/system": "^1.0.0-next.3",
    "@chakra-ui/toast": "^1.0.0-next.6",
    "@chakra-ui/transition": "^1.0.0-next.3",
    "@emotion/core": "^10.1.1",
    "@emotion/styled": "^10.0.27",
    "emotion-theming": "^10.0.27",
    "framer-motion": "^2.9.4",
    "next": "10.0.0",
    "react": "17.0.1",
    "react-dom": "17.0.1"
  },
```

**Comment by ljosberinn** [comment]
You're using conflicting versions. All packages of `chakra` must have the same version. To use the latest version of v1, please remove:
- all emotion dependencies
- all chakra dependencies EXCEPT for `@chakra-ui/core`
- use `"@chakra-ui/core": "next"`

**Comment by jhenriquevissotto** [comment]
Hummm, thanks!!! (y)  =)

**Comment by jhenriquevissotto** [comment]
Solved.

But I got another problem:

![image](https://user-images.githubusercontent.com/19745638/98688676-dea6f300-2349-11eb-80af-acd9c1707273.png)

**Comment by ljosberinn** [comment]
I'm not sure what I'm looking at. Could you please create a sandbox? Looks like youre missing the ChakraProvider.
