### ISSUE TITLE
Add a way to specify a custom "body" element for styling purposes

### ISSUE THREAD

**Issue by AndrewPrifer** [chakra-ui/chakra-ui#2439]
# Feature request
Add a way to specify a custom body element for styling purposes. When a custom body element is specified, all the styles that would normally be applied to the body element (e.g. body font settings), will now be applied to this element instead.

## Is your feature request related to a problem? Please describe.

With the advent of web components and the shadow dom, it is now possible that the root element under which chakra operates is not the document root, but the shadow dom root, thus any styling applied to the body element will have no effect.

## Describe the solution you'd like

Maybe we could add a prop to chakra provider for a custom selector that specifies the "body" element.

## Describe alternatives you've considered

--

## Additional context

I'm building a web component with chakra. Currently the only workaround I found is wrapping the contents of my web component in an extra body tag. This is [illegal](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body):

> The HTML `<body>` Element represents the content of an HTML document. **There can be only one `<body>` element in a document.**

However it seems to be tolerated by browsers.

**Comment by AndrewPrifer** [comment]
5 minutes later and I found the solution. My issue actually stemmed from a lack of knowledge about the theme specification. 😅 The actual solution for anyone having the same issue:

```ts
import { extendTheme } from '@chakra-ui/core';
import { mode } from '@chakra-ui/theme-tools';

const theme = extendTheme({
  styles: {
    global: (props) => ({
      '#my-web-component-root': {
        fontFamily: 'body',
        color: mode('gray.800', 'whiteAlpha.900')(props),
        bg: mode('white', 'gray.800')(props),
        transition: 'background-color 0.2s',
        lineHeight: 'base',
      },
    }),
  },
});

export default theme;
```

**Comment by aayushsaini** [comment]
Could you please elaborate on how to do this.
I want to change the body color from default to black.
