### ISSUE TITLE
[NumberInput] onChange returns a string instead of a number

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#244]
**Describe the bug**
While the example in the docs shows `NumberInput` being used with a numeric state variable, it returns a `string` in its `onChange` callback.

**Suggested solution(s)**
Return `number | null`, the latter [denoting the intentional absence](https://github.com/chakra-ui/chakra-ui/pull/243) of a value.

**Comment by segunadebayo** [comment]
Thanks for this suggestion @kripod. I'll look into it.

**Comment by segunadebayo** [comment]
I've looked into this and will publish a new version shortly.
