### ISSUE TITLE
the `borderImage` prop isn't supported

### ISSUE THREAD

**Issue by ianstormtaylor** [chakra-ui/chakra-ui#2440]
Chakra doesn't seem to recognize the `borderImage` prop for CSS.

```jsx
<Box
  width="100px"
  height="100px"
  border="1px"
  borderImage="linear-gradient(to bottom, red, blue) 1 100%"
/>
```

But if you use `style={{ borderImage: ... }}` it works fine.

**Comment by segunadebayo** [comment]
Yes, we try to limit the style props to common css styles. Border image can be added via the `style` prop as mentioned, css prop using `@emotion/core`, or the `sx` prop in v1.

Permit me to close this out.

**Comment by ianstormtaylor** [comment]
@segunadebayo are there any docs on the `sx` prop?
