### ISSUE TITLE
[NumberInputField] inputMode prop is ignored -> unable to enter negative values on iPhone

### ISSUE THREAD

**Issue by laurensnl** [chakra-ui/chakra-ui#2445]
# Bug report

## Describe the bug

The `inputMode` property is accepted but ignored on the NumberInputField component. This property is needed to render a keyboard that includes the minus key on iPhone (inputMode = numeric). 

![Keyboards](https://i2.wp.com/css-tricks.com/wp-content/uploads/2020/04/input-numeric-ios.png?w=1615&ssl=1)

## To reproduce

```
<NumberInput>
  <NumberInputField inputMode="numeric" />
</NumberInput>
```

The NumberInputField always renders the right keyboard on iPhone (iOS 14.2). The `inputMode="numeric"` on a standard HTML input renders the left keyboard. 

## Minimal reproduction

https://codesandbox.io/s/blissful-williamson-jiu5s?file=/src/App.js

## Expected behavior

I would expect that adding the `inputMode="numeric"` property renders the left keyboard.

## System information

- OS: iOS 14.2
- Browser (if applies): Safari
- Version of @chakra-ui/core: 1.0.0-rc8

## Additional context

This makes it impossible to enter negative values on iPhone, without using the steppers.

For more info on the `inputMode` prop, see https://css-tricks.com/better-form-inputs-for-better-mobile-user-experiences/.

**Comment by segunadebayo** [comment]
Hi @laurensnl,

`inputMode` should be applied to the top-level NumberInput component, not the `NumberInputField` component. Kindly try this and it should work as expected.

However, I've gone ahead to make it possible to pass props as you've shown above.

PS: Kindly change your version to `1.0.0-rc.8` as well.

**Comment by laurensnl** [comment]
Thank you for your quick reply, as always @segunadebayo! You're right: adding `inputMode` to the `NumberInput` component does add the attribute to the HTML element correctly indeed. However, the `type` seems to be set to `text`, also when trying to overwrite it. 

I did some more experiments. It seems like the desired keyboard (the left one) is only rendered when `type` is `number` and `inputMode` is not set. In my tests, Chakra always sets the `type` to `text` and the `inputMode` to `decimal` if not explicitly set. Setting it to a empty value is invalid by Typescript and sets the `inputMode` to `decimal` anyway.

Whatever I tried, I didn't get the desired keyboard. I've updated the Sandbox to show the difference between a HTML `input` element and the Chakra `NumberInput` component.

I'm on `1.0.0-rc.8`

Thanks again for your help.

**Comment by laurensnl** [comment]
Hi @segunadebayo. Any chance this issue can be revisited? 

Adding `type="number"` and `pattern="-?[0-9]*"` to an input field should render the regular keyboard defaulting to the numbers pane, allowing for negative numbers. The `type` property seems to be overwritten by Chakra though (the useNumberInput hook?), making it impossible to enter negative values on iOS using the NumberInputField component.

**Comment by with-heart** [comment]
@laurensnl So the need here is to have `type="number"` applied to `input` in order to show the correct keyboard for iOS?

**Comment by segunadebayo** [comment]
I just pushed an update for this. It'll be part of the next release.

**Comment by laurensnl** [comment]
@with-heart It would be most useful to be able to override the `type` and `pattern` props so you can get the keyboard that you need. 

Awesome @segunadebayo! Thank you very much. That's exactly what we needed.

Happy holidays!
