### ISSUE TITLE
In v1, ModalOverlay usage is wrong in docs

### ISSUE THREAD

**Issue by travellingprog** [chakra-ui/chakra-ui#2446]
# Bug report

## Describe the bug

In the docs of Chakra v1, on the usage of Modals,  https://next.chakra-ui.com/docs/overlay/modal#usage, it shows ModalOverlay as a sibling element of ModalContent.

Howver, in my use of this component, I found that ModalOverlay actually needs to wrap around ModalContent. In fact, if I remember well (came across this bug last week), the modal did not show up at all for me until I made this change.

## To reproduce

Try to create a modal as described in the current v1 docs

**Comment by segunadebayo** [comment]
Hi @travellingprog, kindly upgrade to the most recent `rc` release. `1.0.0-rc.8` and it should work as expected.
