### ISSUE TITLE
Modal content variant style is not applied

### ISSUE THREAD

**Issue by RyanPayso13** [chakra-ui/chakra-ui#2447]
# Bug report

## Describe the bug

When I add a variant style to the Modal component in my theme file it is not applied.

```
    <Modal
      onClose={() => onDialogClose(false)}
      isOpen={showDialog}
      closeOnOverlayClick={false}
      isCentered
      variant="wide"
    >...</Modal>
```

```
components: {
    Modal: {
      parts: ['content'],
      variants: {
        wide: {
          content: {
            maxWidth: ['55%', '55%', '55%'],
          },
        },
      },
    }
}
```

## Expected behavior

The variant should apply the new style of `55%`

**Comment by segunadebayo** [comment]
Hi @RyanPayso13,

Kindly create a codesandbox reproduction of this so we can look into it.

I will re-open once you do.

Thank you

**Comment by malalecherocks** [comment]
Hi, I think he did here, I have the same problem with Modals...

https://codesandbox.io/s/vigilant-germain-u3mkx?file=/src/App.js

**Comment by selvinkuik** [comment]
+1 I am also having the same issue. It is replicable on all modal components. In my case, I am unable to theme ModalContent, but in the same fashion as the codesandbox that has already been provided

**Comment by selvinkuik** [comment]
I was also experiencing this issue, after inspecting how the modal variant styling is defined (see@chakra-ui/theme/dist/types/components/index.d.ts) I noticed the definition should be dialog not content.

@segunadebayo It might be helpful for others to include this in the example docs as it's not obvious the naming of the theme is different to the naming of the component.

```
components: {
    Modal: {
      parts: ['content'],
      variants: {
        wide: {
          dialog: {
            maxWidth: ['55%', '55%', '55%'],
          },
        },
      },
    }
}
```

**Comment by aprakash123** [comment]
Hi @selvinkuik How can I modify the `containerProps` using variant ?

**Comment by aprakash123** [comment]
Solved using `dialogContainer`
