### ISSUE TITLE
Tooltip supports any node as content, but the type says strings only

### ISSUE THREAD

**Issue by avaragado** [chakra-ui/chakra-ui#2448]
# Bug report

## Describe the bug

https://next.chakra-ui.com/docs/overlay/tooltip#props and the Typescript types say that the `label` prop takes a string. However, in practice, any node seems to work. For example, text nodes with embedded inline elements (so you can make an important word **bold** in a tooltip), and Chakra components.

If there's no good reason to limit the type to string, the type should be loosened, possibly to React.ReactNode.

## To reproduce

Paste this into any editable box on the Tooltip documentation page:

```<Tooltip label={<span>hello <b>world</b></span>}>some content</Tooltip>```

## Expected behavior

Types should reflect reality.

## System information

- macOS 10.15.6
- Chrome 86.0.4240.183
- @chakra-ui/core: 1.0.0-rc.8
- node.js: 12.16.1

**Comment by segunadebayo** [comment]
Thanks for reporting this @avaragado. I've updated the types
