### ISSUE TITLE
Typscript typings for theme object need to cover all cases (I included what I'm using right now)

### ISSUE THREAD

**Issue by TheThirdRace** [chakra-ui/chakra-ui#2449]
# Bug report

## Describe the bug

When developing my app with Chakra and Typescript, I realize pretty fast that the typings for the theme weren't covering all cases.

Documentation: https://next.chakra-ui.com/docs/theming/advanced#multipart-or-composite-component

The typings suggested in the documentation are:

```
type StyleInterpolation =
  | { [part: string]: SystemStyleObject }
  | ((options: StyleOptions) => { [part: string]: SystemStyleObject });

interface StyleOptions {
  theme: Theme
  colorMode: "light" | "dark"
  colorScheme: string
}

interface StyleConfig {
  baseStyle: StyleInterpolation
  sizes: { [size: string]: StyleInterpolation }
  variants: { [variant: string]: StyleInterpolation }
  defaultProps?: {
    variant: string
    size: string
  }
}
```

## Expected behavior

These are the typings I'm using right now after having problems with the ones from documentation:

```
export type StyleConfig = {
	parts?: string[]
	baseStyle: StyleInterpolation
	sizes?: { [size: string]: StyleInterpolation }
	variants?: { [variant: string]: StyleInterpolation }
	defaultProps?: {
		size?: string
		variant?: string
	}
}

export type StyleConfigProps = {
	theme: Theme
	colorMode: 'light' | 'dark'
	colorScheme: string
}

type StyleInterpolation =
	| SystemStyleObject
	| ((style: StyleConfigProps) => SystemStyleObject)
	| { [part: string]: SystemStyleObject }
	| ((style: StyleConfigProps) => { [part: string]: SystemStyleObject })
```

The biggest difference is from `StyleInterpolation` where I can have:

- An object
- A function that returns an object
- A multi-part object with each part having their styling object
- A multi-part function with each part having their styling object

I also added the Optional type on every properties that weren't mandatory for the styling to work. This saves some boilerplate code and makes it easier to read the real changes.

**Comment by TheThirdRace** [comment]
Given the new documentation has been updated with the same types beside some optionals that are lost there, there's no point in keeping this issue open.

**Comment by amosbastian** [comment]
Is this actually fixed? I am encountering a problem with the typings not being correct when creating custom components (see https://chakra-ui.com/docs/theming/advanced#single-part-component).

**Comment by TheThirdRace** [comment]
@amosbastian Yes it's fixed.

But it seems the documentation hasn't been updated much... 

Here's an example of what I use:

```
import { ComponentSingleStyleConfig, SystemStyleObject, ThemeComponentProps } from '@chakra-ui/react'
import { text } from '../variables/brand'

export const Text: ComponentSingleStyleConfig = {
	baseStyle: {},
	variants: {
		del: (props: ThemeComponentProps): SystemStyleObject => ({
			color: text.del(props),
			textDecoration: 'line-through'
		}),
		em: (props: ThemeComponentProps): SystemStyleObject => ({
			// visual
			color: text.emphasis(props),
			// typography
			fontStyle: 'italic'
		}),	},
	defaultProps: {}
}
```
