### ISSUE TITLE
Initial value of undefined stops radio group from being controlled even if an actual value is passed later

### ISSUE THREAD

**Issue by AndrewPrifer** [chakra-ui/chakra-ui#2451]
# Bug report

## Describe the bug

For my use case it is necessary to be able to uncheck all radio buttons. I found this works by passing undefined as value. However if the _initial_ value is undefined, it stops me from being able to control the radio group altogether. Otherwise if the initial value is anything else, everything works as expected.

## To reproduce

Set up a controlled RadioGroup and pass undefined as initial value. Set up a few buttons to test if you can control the group from the outside.

## Minimal reproduction

https://codesandbox.io/s/great-kare-l00gu?file=/src/App.tsx

## Expected behavior

Passing undefined as initial value doesn't stop me from controlling the RadioGroup, it simply unchecks all buttons for a default state.

## System information

- OS: MacOS 10.15.7
- Browser (if applies): Chrome 86.0.4240.183
- Version of @chakra-ui/core: [e.g. 1.0.0-rc.8]
- Version of Node.js: v14.2.0

## Additional context

This issue might be relevant, as it names the same initial conditions: https://github.com/chakra-ui/chakra-ui/issues/1507

**Comment by AndrewPrifer** [comment]
Update: it seems that passing any non-existent string or numeric value, or an empty string, which is illegal anyway, as initial value results in the same effect, without the above mentioned issue. It would still be nice if this behavior were documented at least.

**Comment by ljosberinn** [comment]
Isn't this in line with how form elements work in react in general? no value given => uncontrolled?

**Comment by AndrewPrifer** [comment]
@ljosberinn the issue here is more no value given _initially_ => uncontrolled.

**Comment by ljosberinn** [comment]
yea, thats what I'm saying: https://reactjs.org/docs/uncontrolled-components.html#:~:text=In%20a%20controlled%20component%2C%20form,form%20values%20from%20the%20DOM.
Passing in an impossible state for the form works fine: https://codesandbox.io/s/vigorous-newton-4t1ye?file=/src/App.tsx

**Comment by AndrewPrifer** [comment]
@ljosberinn again, this is a slight difference. Please see this [codesandbox](https://codesandbox.io/s/suspicious-jepsen-n4wei?file=/src/App.tsx). Even though the control is initialized with an undefined value, as soon as we pass it one, it becomes controlled. In chakra's case, if we initialize the radio group with an undefined value, it refuses to become controlled even if we later do pass it a value.

**Comment by ljosberinn** [comment]
Right, I forgot about that bit but:

> Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components

so this should be avoided either way.

**Comment by AndrewPrifer** [comment]
Alright, I think the issue can be closed, a mention about this deviation in behavior in the documentation would be nice though.
