### ISSUE TITLE
Following the doc for custom themed components means props can't override theme

### ISSUE THREAD

**Issue by avaragado** [chakra-ui/chakra-ui#2453]
# Bug report

I've run into an issue with custom themed components. Whether it's a bug in code or documentation or my head is hard to say. I'm reporting it as requested on Discord.

Going from the example at https://next.chakra-ui.com/docs/theming/component-style#return-value, the recommended approach is for your custom component to gather styles from the theme via `useStyleConfig`, then render some lower-level component like `Box` (or `chakra.span` I guess), passing `sx` with the gathered styles, and spreading all your remaining props. For example, copied from that page:

```js
return <Box as="button" sx={styles} {...rest} />
```

The issue concerns what happens when `styles` and `rest` clash. For example, if your custom style sets `fontSize: 'xl'`, and then your custom component props set `fontSize="sm"`, it appears that the styles take precedence over the props.

This feels wrong to me. I would always expect that the `props` would override the base style (it's called 'base' for a reason, right?).

In the core Chakra components that I've looked at, the code uses `__css` instead of `sx` - and guess what: with `__css`, the `props` override the base style as you'd expect.

So we have a discrepancy: _What Chakra recommends_ vs _What Chakra does_.

Should I make my components using `sx` or `__css`? If `sx`, then how best to ensure that props override base style?

Or should Chakra recommend `__css` instead for custom components?

## To reproduce

https://codesandbox.io/s/keen-proskuriakova-zyc31?file=/src/App.tsx

I've made two components: one using `sx` and one using `__css`, to show the difference.

**Comment by segunadebayo** [comment]
We'll update the docs to explain when to use `__css` and `sx` prop for component theming.

**Comment by davebrewer** [comment]
Encountered same issue today. Pls post a link here once the docs are updated as would like to read about this nuanced behaviour. Switched over to __css and continued 👍

**Comment by ParallelUniv3rse** [comment]
I'd like to bump this issue, the docs still don't explain when to use `sx` compared to `__css` and I'm having the same problems understanding the difference.
