### ISSUE TITLE
Type of _groupHover is missing property "filter"

### ISSUE THREAD

**Issue by gbrlsnchs** [chakra-ui/chakra-ui#2454]
# Bug report

## Describe the bug

When passing `_groupHover={{ filter: "grayscale(100%)" }}` to `Image`, I get the following message:
```
 Type '{ filter: string; }' is not assignable to type 'ChakraStyleProps | PseudoProps<ChakraStyleProps> | undefined'.
Object literal may only specify known properties, and 'filter' does not exist in type 'ChakraStyleProps | PseudoProps<ChakraStyleProps>'.
```

## To reproduce

1. Import `Image`
2. Add prop `_groupHover={{ filter: "grayscale(100%)" }}` to it
3. See error described above

## Minimal reproduction

TS template is currently broken, but the issue is easily reproduced by following the steps above.

## Expected behavior

`filter` field not missing from type of `_groupHover`.

## Screenshots

N/A

## System information

- OS: Linux
- Version of @chakra-ui/core: [e.g. 1.0.0-rc.8]
- Version of Node.js: 14.13.1

## Additional context

N/A

**Comment by with-heart** [comment]
Here's a reproduction: https://codesandbox.io/s/eager-snow-c2tfe?file=/src/App.tsx

Related: #1504

**Comment by Zaynex** [comment]
hey, any guys review the pull request ? 👀
