### ISSUE TITLE
Styles are not working after deploy.

### ISSUE THREAD

**Issue by SebaP94** [chakra-ui/chakra-ui#2460]
# Bug report

## Describe the bug

After deploy to hosting platform, font styles and sizing are not changed (in sources are "2xl" instead of expected "2.25rem" It breaks all layout and I cannot find why it is happening. On local env works properly. 

for example You can run locally project from here:
https://github.com/SebaP94/gastroSaver
and compare view with this:
https://nextjs-bl39u4onj.vercel.app/

Please help :(

**Comment by SebaP94** [comment]
This probably caused @ emotion / core, even though all code was commented out.

**Comment by allpwrfulroot** [comment]
I get the following locally after attempting to upgrade:
```hot-dev-client.js?647e:162 ../../node_modules/@chakra-ui/system/dist/esm/providers.js:4:0
Module not found: Can't resolve '@emotion/react'
null
```
I've tried adding the module, removing node_modules and yarn.lock, etc. No luck

**Comment by with-heart** [comment]
@allpwrfulroot Is there any way you can create a CodeSandbox with your setup or share a git repo? It's hard to tell without being able to see your project setup.

**Comment by allpwrfulroot** [comment]
I went ahead and re-added both of @emotion/react and @emotion/styled, somehow that restored things?
