### ISSUE TITLE
add support for locales to format numbers in NumberInput

### ISSUE THREAD

**Issue by tafelito** [chakra-ui/chakra-ui#2461]
# Feature request

## Is your feature request related to a problem? Please describe.

I'm using NumberInput and I was trying to find a way how to format the number depending on the user's locale. I did find the pattern option but that's only for validation on submit. It would be great to add a way to tell the NumberInput what format to use, similar to the  `Intl.NumberFormat` class

## Describe the solution you'd like

When you work with multiple locales, number format can differ. Some locales has `,` as the decimal separator. 

I don't know if this is planned for the future or maybe not but I think it would be a great addition to the library

**Comment by with-heart** [comment]
I don't have time to explore this more atm, but I'd think you could hook that up in a similar fashion to how you'd format with a "$" prefix, but using `Intl.NumberFormat` instead: https://next.chakra-ui.com/docs/form/number-input#formatting-and-parsing-the-value

**Comment by tafelito** [comment]
the problem is not formatting the value or parsing in before submitting, the problem is that NI will treat the value as invalid afaik

in that same example, if you use `1,53` instead of `1.53` you'll see that then the NI is in fact invalid and if you go up or down then you lose the value

**Comment by tafelito** [comment]
I'm not sure why is the $ sign would be valid tho? Is that because of the pattern?

**Comment by with-heart** [comment]
Yeah, the default `pattern` is only checking for numbers with a possible decimal in between them:

https://github.com/chakra-ui/chakra-ui/blob/ca8e17f48fcc0fba3d22ccfce60e3d770d4b28c8/packages/number-input/src/use-number-input.ts#L107-L107

**Comment by tafelito** [comment]
but even changing the pattern to accept other formats, it will still be invalid, based on what it says on the prop comments the pattern is only used to validate on submit, right?

**Comment by with-heart** [comment]
Yeap. Supporting something more flexible would probably take a lot of additional effort to make sure we can also handle changing validation.

**Comment by tafelito** [comment]
make sense, dealing with intl is never an easy thing to do. I hope you find any time soon, I think it will be a great addition, but I understand the priorities. I wish I could be of more help but I don't have much time my self either and I don't know all the internals of v1 to try to tackle this

**Comment by Radmehr-aghdam** [comment]
fixed in https://github.com/chakra-ui/chakra-ui/issues/4474#issuecomment-1407011322

**Comment by robinsadeghpour-teclead** [comment]
This is still an issue and not fixed.

**Comment by LFCavalcanti** [comment]
The US and UK are two of the few countries in the planet that use point to delimit decimal places, so at least supporting commas should also be a default option.
I find fascinating that the default implementation is how the US does it and every other use case you must use additional libraries to compound code on top to support the use case, that it by the way, the standard currency notation of a country.

**Comment by nelsieborja** [comment]
Also need internalization support in NumberInput but I don't think Chakra will ever gonna implement this. Been looking for an alternative decent NumberInput library but it doesn't seem to exist. Until I came across with `react-spectrum` which has the exact component I'm looking for, problem is not sure consuming 2 libraries is a good idea for the bundle. But they also provide [react-aria](https://react-spectrum.adobe.com/react-aria/useNumberField.html) hooks such as `useNumberField` to implement the same functionalities on your custom component, but then again it's library that contains other things so

**Comment by nelsieborja** [comment]
> Also need internalization support in NumberInput but I don't think Chakra will ever gonna implement this. Been looking for an alternative decent NumberInput library but it doesn't seem to exist. Until I came across with `react-spectrum` which has the exact component I'm looking for, problem is not sure consuming 2 libraries is a good idea for the bundle. It also provides [react-aria](https://react-spectrum.adobe.com/react-aria/useNumberField.html) hooks such as `useNumberField` to implement the same functionalities on your custom component, but then again it's a library that contains other things so

Actually you can use the specific library [@react-aria/numberfield](https://www.npmjs.com/package/@react-aria/numberfield)
