### ISSUE TITLE
No default export when use with Nextjs Custom _App

### ISSUE THREAD

**Issue by Ndifreke** [chakra-ui/chakra-ui#2462]
# Bug report

## Describe the bug
Chakra UI "1.0.0-rc.8" when used with Nextjs Custom App throws an exception `Error: The default export is not a React Component in page: "/_app"`

1. Go to sendbox Link [https://codesandbox.io/s/admiring-gates-zuj7b?file=/pages/_app.js](https://codesandbox.io/s/admiring-gates-zuj7b?file=/pages/_app.js)

## System information

- OS:  macOS 11.0.1
- Browser: [Chrome, Safari]
- Version of @chakra-ui/core: 1.0.0-rc.8
- Version of Node.js:v14.15.0

**Comment by ljosberinn** [comment]
That's not a chakra error, thats a nextjs error telling you you need to use `export default function App() { .... }`
