### ISSUE TITLE
Images are slow to appear

### ISSUE THREAD

**Issue by Hargoze** [chakra-ui/chakra-ui#2463]
Hello Chakra team

I am currently building my website with next js and chakra, but i find that my images are a bit slow, they take a few moment to appear, even when refreshing.

[here](https://blog.acert.io/) is my site (dummy text and picture), this also seems to be the case on your [documentation](https://next.chakra-ui.com/docs/data-display/image#usage) (the picture takes a bit of time to appears too)

 do you know why this happen ? if yes is there a way to fix that?
Also what do you think of [next/Image](https://nextjs.org/docs/api-reference/next/image) in nextjs ?

**Comment by ljosberinn** [comment]
Seguns image on the website isnt directly linked, the request gets redirected twice before the actual image can be retrieved. Dan Abramovs image loads instantly. Chakra has zero influence over the time it takes to load an image. On your site, images load instantly for me too.

We track the integration of Chakra with Next.js specific components over in #2248 :)
