### ISSUE TITLE
Text them variants ignores textTransform

### ISSUE THREAD

**Issue by hutber** [chakra-ui/chakra-ui#2464]
# Theme 
```
variants: {
  caps3: {
    fontFamily: "demi",
    fontWeight: "normal",
    fontSize: 3,
    lineHeight: 3,
    textTransform: "uppercase",
    letterSpacing: "0.16rem",
  },
}
```

# Component
<Text variant="caps3">Caps 3</Text>

# Output Styles:
```
.css-1a23dbw {
    font-family: Futura PT Pro Demi;
    font-weight: 400;
    font-size: 1.625rem;
    line-height: 2.5rem;
    -webkit-letter-spacing: 0.16rem;
    -moz-letter-spacing: 0.16rem;
    -ms-letter-spacing: 0.16rem;
    letter-spacing: 0.16rem;
}
```

![image](https://user-images.githubusercontent.com/1344898/98934554-307e8300-24da-11eb-9942-f2a7ad23d991.png)

Manually adding:
![image](https://user-images.githubusercontent.com/1344898/98934780-7dfaf000-24da-11eb-86fc-37a7f511437c.png)

**Comment by with-heart** [comment]
Quick and dirty reproduction: https://codesandbox.io/s/silent-breeze-8d3x1?file=/src/App.tsx

**Comment by with-heart** [comment]
Interestingly enough, `textStyles` doesn't apply it either: https://codesandbox.io/s/elated-drake-n16ms?file=/src/App.tsx

**Comment by hutber** [comment]
Thanks very much for creating this @with-heart !!!
