### ISSUE TITLE
Vertical Slider

### ISSUE THREAD

**Issue by JohannesKlauss** [chakra-ui/chakra-ui#2465]
# Feature request

## Is your feature request related to a problem? Please describe.

The docs state that the orientation of the Slider component can be vertical or horizontal, but only horizontal is supported at the moment. This also seems to be the case for 1.0.

For a project I would really like to switch from Mui to ChakraUI, but I need vertical Sliders for this.
Is there any chance we can get vertical sliders for 1.0?

## Describe the solution you'd like

Given the prop `orientation={'vertical'}` to the Slider component should render it vertical.

## Additional context

I don't know how complex that is, I could sure be of help if you need someone to do it.

**Comment by JohannesKlauss** [comment]
I just realized that despite what the docs for 1.0 state, vertical Sliders are included. Nice one 👍 .
You should update the docs for the Slider section :)

**Comment by with-heart** [comment]
@JohannesKlauss We definitely should 😁
