### ISSUE TITLE
Style Props won't work with the Media Query Object.

### ISSUE THREAD

**Issue by brvnonascimento** [chakra-ui/chakra-ui#2467]
# Bug report

## Describe the bug

Style Props won't accept the Media Query Object as a parameter after version 1.0.0-rc.4. I've experienced the bug with at least the "background", "textAlign" and Grid's props.

I haven't experienced any problems with passing the Media Query Array though.

## To reproduce

1. Go to https://codesandbox.io/s/async-tdd-sr5yl?file=/src/App.js
2. The Box component won't have the black background as described in the props.
3. Change @chakra-ui/core version to 1.0.0-rc.3
4. It should display the black background just fine.

## System information

- OS: MacOS Big Sur
- Version of @chakra-ui/core: next
- Version of Node.js: 14.
- NextJS 10 (with the Provider and Custom Document as described in the docs).

**Comment by with-heart** [comment]
Oh. This isn't actually a bug. Installing `@emotion/core`, `@emotion/styled`, or `emotion-theming` cause versioning conflicts that cause styles to be incorrectly applied or not applied at all. Working fine here after removing those dependencies: https://codesandbox.io/s/upbeat-wiles-vbqzb?file=/src/App.js

**Comment by brvnonascimento** [comment]
Thank you! The Problem is solved on my Codesandbox, but not on my local environment. I'm using Yarn 1.22.4 and none of those dependencies are declared in my package.json.

Here's my yarn.lock:

```yaml```
"@chakra-ui/core@next":
  version "1.0.0-rc.8"
  resolved "https://registry.yarnpkg.com/@chakra-ui/core/-/core-1.0.0-rc.8.tgz#2a2e7105b18488762edf479cc7cd77185503c760"
  integrity sha512-ZPGjTwy5QrYG/sYuGhrYeBNfWNIfQMSI4spHkNusd+qmNwPJMXR/WO0M8FwTdSnLc0ZVubUpvqdY4e9fp+xT+g==
  dependencies:
    "@chakra-ui/accordion" "1.0.0-rc.8"
    "@chakra-ui/alert" "1.0.0-rc.8"
    "@chakra-ui/avatar" "1.0.0-rc.8"
    "@chakra-ui/breadcrumb" "1.0.0-rc.8"
    "@chakra-ui/button" "1.0.0-rc.8"
    "@chakra-ui/checkbox" "1.0.0-rc.8"
    "@chakra-ui/close-button" "1.0.0-rc.8"
    "@chakra-ui/control-box" "1.0.0-rc.8"
    "@chakra-ui/counter" "1.0.0-rc.8"
    "@chakra-ui/css-reset" "1.0.0-rc.8"
    "@chakra-ui/editable" "1.0.0-rc.8"
    "@chakra-ui/form-control" "1.0.0-rc.8"
    "@chakra-ui/hooks" "1.0.0-rc.8"
    "@chakra-ui/icon" "1.0.0-rc.8"
    "@chakra-ui/image" "1.0.0-rc.8"
    "@chakra-ui/input" "1.0.0-rc.8"
    "@chakra-ui/layout" "1.0.0-rc.8"
    "@chakra-ui/live-region" "1.0.0-rc.8"
    "@chakra-ui/media-query" "1.0.0-rc.8"
    "@chakra-ui/menu" "1.0.0-rc.8"
    "@chakra-ui/modal" "1.0.0-rc.8"
    "@chakra-ui/number-input" "1.0.0-rc.8"
    "@chakra-ui/pin-input" "1.0.0-rc.8"
    "@chakra-ui/popover" "1.0.0-rc.8"
    "@chakra-ui/popper" "1.0.0-rc.8"
    "@chakra-ui/portal" "1.0.0-rc.8"
    "@chakra-ui/progress" "1.0.0-rc.8"
    "@chakra-ui/radio" "1.0.0-rc.8"
    "@chakra-ui/select" "1.0.0-rc.8"
    "@chakra-ui/skeleton" "1.0.0-rc.8"
    "@chakra-ui/slider" "1.0.0-rc.8"
    "@chakra-ui/spinner" "1.0.0-rc.8"
    "@chakra-ui/stat" "1.0.0-rc.8"
    "@chakra-ui/switch" "1.0.0-rc.8"
    "@chakra-ui/system" "1.0.0-rc.8"
    "@chakra-ui/tabs" "1.0.0-rc.8"
    "@chakra-ui/tag" "1.0.0-rc.8"
    "@chakra-ui/textarea" "1.0.0-rc.8"
    "@chakra-ui/theme" "1.0.0-rc.8"
    "@chakra-ui/toast" "1.0.0-rc.8"
    "@chakra-ui/tooltip" "1.0.0-rc.8"
    "@chakra-ui/transition" "1.0.0-rc.8"
    "@chakra-ui/utils" "1.0.0-rc.8"
    "@chakra-ui/visually-hidden" "1.0.0-rc.8"
```

**Comment by TimKolberger** [comment]
Please delete your `yarn.lock` file and run `yarn` again.

**Comment by brvnonascimento** [comment]
> Please delete your `yarn.lock` file and run `yarn` again.

That's exactly what I've tried to do with no success.

**Comment by TimKolberger** [comment]
Delete your `yarn.lock`, delete `node_modules` and run `yarn` again.
This should reset _everything_.

**Comment by brvnonascimento** [comment]
> Delete your `yarn.lock`, delete `node_modules` and run `yarn` again.
> This should reset _everything_.

Same with no success. Also tried ```shell```yarn cache clean``` and still getting broken styles.

I'm running a monorepo with Yarn v1 Workspaces could something else using Emotion to be causing some conflict? Although, that's the only frontend/ui package for now.

```json
{
  "name": "@monorepo/main-web",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "dev": "env-cmd next -p 4000",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@apollo/client": "^3.2.2",
    "@chakra-ui/core": "1.0.0-rc.8",
    "@chakra-ui/icons": "1.0.0-rc.8",
    "@chakra-ui/theme-tools": "1.0.0-rc.8",
    "@workmize/graphql-codegen": "*",
    "@workmize/validator": "*",
    "env-cmd": "^10.1.0",
    "env-var": "^6.3.0",
    "fork-ts-checker-webpack-plugin": "^5.0.14",
    "framer-motion": "latest",
    "graphql": "^15.0.0",
    "msw": "^0.21.2",
    "next": "^10.0.0",
    "next-compose-plugins": "^2.2.0",
    "next-transpile-modules": "^4.0.2",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-hook-form": "^6.9.6"
  },
  "devDependencies": {
    "@babel/core": "^7.11.0",
    "@babel/preset-env": "^7.12.1",
    "@babel/preset-react": "^7.12.1",
    "@babel/preset-typescript": "^7.12.1",
    "@babel/runtime": "^7.10.3",
    "@svgr/webpack": "^5.4.0",
    "@testing-library/jest-dom": "^5.11.5",
    "@testing-library/react": "^11.1.0",
    "@types/jest": "^26.0.13",
    "@types/node": "^14.11.6",
    "@types/react": "^16.9.51",
    "@types/react-dom": "^16.9.8",
    "@typescript-eslint/parser": "^4.1.0",
    "babel-jest": "^26.6.1",
    "cypress": "^5.4.0",
    "eslint-import-resolver-typescript": "^2.3.0",
    "eslint-plugin-import": "^2.22.0",
    "jest": "^26.4.2",
    "react-test-renderer": "^17.0.1",
    "tsc-watch": "^4.2.9",
    "typescript": "^4.0.3"
  }
}
```

**Comment by ljosberinn** [comment]
try `yarn why @emotion/core`, mono repo shouldnt matter as chakra itself is a monorepo, but we use lerna

**Comment by brvnonascimento** [comment]
That's the outcome:

```
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "@emotion/core"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@emotion/core@10.0.35"
info Reasons this module exists
   - "_project_#@workmize#main-web#@chakra-ui#core#@chakra-ui#system" depends on it
   - Hoisted from "_project_#@workmize#main-web#@chakra-ui#core#@chakra-ui#system#@emotion#core"
info Disk size without dependencies: "268KB"
info Disk size with unique dependencies: "3.23MB"
info Disk size with transitive dependencies: "15.19MB"
info Number of shared dependencies: 41
✨  Done in 1.90s.
```

**Comment by ljosberinn** [comment]
That looks alright. Noticing only now that you're using `next-transpile-modules` - is it possible a module of another folder is leading to this behaviour by pulling in another dependency?

**Comment by brvnonascimento** [comment]
I've tried disabling all my webpack plugins in next.config.js and purged everything from my "pages" folder leaving just an "index.tsx" with just a simple component wrapped in Chakra Provider (also deleted the .next cache). All styles work but the Media Query Object, which makes sense cause the transpiled modules are all just shared utils in the monorepo.

**Comment by ljosberinn** [comment]
Afraid we'll need a repro repo then 🤔 something is going on here that we're missing but it's impossible to tell by now

**Comment by brvnonascimento** [comment]
I just upgraded to the newest official version 1.0.0 and it's working flawlessly! Just noticed that we don't have the "xs" breakpoint property anymore, so I upgraded everything to "sm" and it started working again. One nice addition would be to have typings for the breakpoint object. I'll try digging into the source code and make a pull request!

You guys are the best! I could not thank you enough!

**Comment by ljosberinn** [comment]
> Just noticed that we don't have the "xs" breakpoint property anymore

The breakpoints are unchanged, so.. [its definitely still there](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/theme/src/foundations/breakpoints.ts#L7) :)

its impossible to type it beyond the defaults because users can extend them as they like.

**Comment by brvnonascimento** [comment]
That's weird. I have an entire project in production with v0 and the "xs" property works just fine somehow (????).

**Comment by brvnonascimento** [comment]
What says in the [docs](url) is that any undefined alias will define the default value, maybe that's why my "xs" property worked as the "base" value.
