### ISSUE TITLE
DrawerFooter doesn't appear in mobile browsers

### ISSUE THREAD

**Issue by acolytec3** [chakra-ui/chakra-ui#2468]
# Bug report

## Describe the bug

The `DrawerFooter` component is not appearing when a  `Drawer` is open in mobile browsers.  Tested on Chrome/Brave/Firefox/Safari on both Android and iOS

## To reproduce

1. Click on "Open Drawer"
2. Drawer will open
3. Should see "Cancel" and "Upload File" buttons in lower right in `DrawerFooter` but do not appear on mobile browsers

## Minimal reproduction

https://5neo3.csb.app/

## Expected behavior

DrawerFooter component should appear when drawer is open

## System information

- OS: Android/iOS
- Browser (if applies): Chrome/Brave/Firefox on Android - Safari on iOS
- Version of @chakra-ui/core:  1.0.0-rc.8

**Comment by with-heart** [comment]
Couple of things before getting to the footer issue:

First issue is that you had `@emotion/core`, `@emotion/styled`, and `emotion-theming` installed which causes conflicts and none of Chakra's styles were being applied. That's fixed here: https://codesandbox.io/s/dark-waterfall-lx9k7?file=/src/index.tsx

Fixing that caused the `Drawer` to show with a transparent. That's because `bg`, `color`, etc. props require a specific color. Changing that to `green.500` causes it to render correctly: https://codesandbox.io/s/dark-waterfall-lx9k7?file=/src/Drawer.tsx:532-546

With those things out of the way, I can confirm that the footer is not visible on mobile. It looks like that's due to the mobile browser toolbar being visible, which is pushing the footer down past the bottom of the page but it's not scrollable. If I add a bottom margin to the footer, I'm able to partially see the buttons. 
![image](https://user-images.githubusercontent.com/1954752/98960175-1b9df180-24d2-11eb-9e14-9a6ba2dc6172.png)

**Comment by acolytec3** [comment]
@with-heart Thanks!  I've corrected the code-sandbox example per your recommendation and see the correct styling now.  I'll code around it for now as I need buttons to be fully rendered in mobile for the PWA I'm working on but good to know I wasn't imagining things.

**Comment by with-heart** [comment]
Some additional context:

- https://css-tricks.com/the-trick-to-viewport-units-on-mobile/
- https://stackoverflow.com/questions/43575363/css-100vh-is-too-tall-on-mobile-due-to-browser-ui
- https://stackoverflow.com/a/61934714 

The last link specifically suggests adding `height: 100%` to `html, body` to resolve this issue across browsers, but not sure what the implications are there.

**Comment by acolytec3** [comment]
Thanks, I'll take a look.  A naive setting of those values in a theme object and then using `extendTheme` doesn't seem to make any difference but I'll experiment a little further.

**Comment by acolytec3** [comment]
@with-heart One last follow-up here for how I solved this in my use case.  I used your trick of extra bottom-padding with a media-query of this sort - `<DrawerFooter mb={{base:"25%",sm:"25%",md:"25%",lg:0,xl:0}}>`

This seems to work well enough for now.

**Comment by crubier** [comment]
Not sure if this is related, but the drawer example on the docs are broken on mobile safari 

![2620FD90-E83F-458B-A4FB-47F47D08D66B](https://user-images.githubusercontent.com/2954572/99088583-26d14a00-25c4-11eb-9a3a-1f99c38d2ab8.png)

**Comment by nicolascavallin** [comment]
Well, I'm newbie, and maybe is not the best practice, but I solved the problem in the next way:

```
<DrawerOverlay heigth='100% !important>
     <DrawerContent heigth='100% !important>
          [...]
```

My problem now is when the keyboard goes up, footer too.

**Comment by AO19** [comment]
**React example**
You can get the real height of a device by doing this in your App.js:
```js
useEffect(() => {
    window.addEventListener('resize', windowResizeHandler);
    document.documentElement.style.setProperty(
      '--vh',
      window.innerHeight / 100 + 'px'
    );
    return function cleanup() {
      window.removeEventListener('resize', windowResizeHandler);
    };
  }, []);


// --vh is a String here with px at the end, so I remove it and could parseFloat it, to use in JS
  const realHeight = getComputedStyle(document.body)
    .getPropertyValue('--vh')
    .slice(0, -2);
```

This way you set a css variable `--vh` with the real height of a device and can get that value in your JS files or in your css files.


```js
<Flex direction='column' height={`${100 * parseFloat(realHeight)}px`}>
...
</Flex>
```

**Comment by rserafim** [comment]
it was not clear to me. Will it be fixed in any version? Tks

**Comment by maxbeier** [comment]
Had the same problem and created a PR: https://github.com/chakra-ui/chakra-ui/pull/3048

I tested on Desktop and iOS Safari. Could someone also test on Android with Chrome?

**Comment by acolytec3** [comment]
> Had the same problem and created a PR: #3048
> 
> I tested on Desktop and iOS Safari. Could someone also test on Android with Chrome?

I'll take a look on Android. I need to remove my hack from my code first.

**Comment by maxbeier** [comment]
> > Had the same problem and created a PR: #3048
> > I tested on Desktop and iOS Safari. Could someone also test on Android with Chrome?
> 
> I'll take a look on Android. I need to remove my hack from my code first.

Oh you can use the preview deploy from the PR: https://chakra-ui-git-fork-maxbeier-develop.chakra-ui.now.sh/docs/overlay/drawer

**Comment by acolytec3** [comment]
![Screenshot_20210113-162214](https://user-images.githubusercontent.com/17355484/104512009-8eebde80-55bb-11eb-8895-4abd4f7c1ad6.png)
 Works!

**Comment by Fedeorlandau** [comment]
Hi @maxbeier I left a comment in your pr. In iPhone 11 pro max (safari and chrome) it's looking weird.

Cheers,

**Comment by camilo86** [comment]
Hey yall. 

Just following up on this bug. I found the same issue while testing a drawer on ios safari. Is there a fix on the way? or a nice way to patch this in the mean time? 

Thanks!

**Comment by Fedeorlandau** [comment]
> Hi @maxbeier I left a comment in your pr. iPhone 11 pro max (safari and chrome) it's looking weird.
> 
> Cheers,

Now it works fine! thanks

**Comment by binajmen** [comment]
> **React example**
> You can get the real height of a device by doing this in your App.js:
> 
> ```js
> useEffect(() => {
>     window.addEventListener('resize', windowResizeHandler);
>     document.documentElement.style.setProperty(
>       '--vh',
>       window.innerHeight / 100 + 'px'
>     );
>     return function cleanup() {
>       window.removeEventListener('resize', windowResizeHandler);
>     };
>   }, []);
> 
> 
> // --vh is a String here with px at the end, so I remove it and could parseFloat it, to use in JS
>   const realHeight = getComputedStyle(document.body)
>     .getPropertyValue('--vh')
>     .slice(0, -2);
> ```
> 
> This way you set a css variable `--vh` with the real height of a device and can get that value in your JS files or in your css files.
> 
> ```js
> <Flex direction='column' height={`${100 * parseFloat(realHeight)}px`}>
> ...
> </Flex>
> ```
> 
> In this example, the height would be `100vh`, just exchange the 100 in the calculation with the value you want.
> 
> When the whole app has the real height, you can just set the Drawer ([see here](https://github.com/chakra-ui/chakra-ui/issues/2468#issuecomment-729554826)) height and it will be 100% = 100vh

Thank you for this solution.

Is there any reason why I couln't use `<DrawerContent maxH={window.innerHeight}>` instead?

Tested it on Chrome/Safari in iOS. Seems to do the job (with placement `bottom`).

**Comment by binajmen** [comment]
> ```js
> const realHeight = getComputedStyle(document.body)
>     .getPropertyValue('--vh')
>     .slice(0, -2);
> ```

Thanks for this solution.

I'm using this one if anyone is interested (using NextJS, you have to ensure `window` is defined):

```js
  const [innerHeight, setH] = React.useState<number>(typeof window !== "undefined" ? window.innerHeight : 100)

  function windowResizeHandler() {
    if (window !== undefined) {
      setH(window.innerHeight)
    }
  }

  React.useEffect(() => {
    if (window !== undefined) {
      window.addEventListener('resize', windowResizeHandler)
      return () => {
        window.removeEventListener('resize', windowResizeHandler)
      }
    }
  }, [])
```
I believe setting the state to `100` (or any number) is not an issue as the `useEffect` will directly run on mount and set the state with the correct `innerHeight`.
