### ISSUE TITLE
[Typescript] Breadcrumbs `as` parameter does not work with Reach Router as documented

### ISSUE THREAD

**Issue by DavidJFelix** [chakra-ui/chakra-ui#247]
**Describe the bug**
Typescript claims a type error when attempting to use `Link` from `@reach/router` in the `BreadcrumbLink` `as` parameter as documented [here](https://chakra-ui.com/breadcrumb#usage-with-routing-library)

This may also affect other components which use `Link`

Error:
```
Type 'typeof Link' is not assignable to type '"symbol" | "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | "br" | "button" | "canvas" | ... 157 more ... | undefined'.
  Type 'typeof Link' is not assignable to type 'ComponentClass<any, any> & string'.
    Type 'typeof Link' is not assignable to type 'string'.
```

**Expected Behavior**
The types should match to allow use as documented and as allowed in JS.

**To Reproduce**
- Use this template:

`yarn create react-app bug-demo --typescript`

Install chakra-ui as documented
Use this component:

```typescript
import React from 'react'
import {Breadcrumb, BreadcrumbItem, BreadcrumbLink} from '@chakra-ui/core'
import {Link} from '@reach/router'

export const Bug = () => (
  <Breadcrumb>
    <BreadcrumbItem>
      <BreadcrumbLink as={Link} to="/">Test</BreadcrumbLink>
    </BreadcrumbItem>
  <Breadcrumb>
)
```

- List the steps to reproduce the behavior:
`yarn start`

**Suggested solution(s)**

Change the typing on `as` to be more inclusive. Perhaps `ReactNode` instead of `ElementType`

**Comment by DavidJFelix** [comment]
Current workaround:

```typescript
import React from 'react'
import {Breadcrumb, BreadcrumbItem, BreadcrumbLink} from '@chakra-ui/core`
import {Link} from '@reach/router'

export const Bug = () => (
  <Breadcrumb>
    <BreadcrumbItem>{/*
      // @ts-ignore */}
      <BreadcrumbLink as={Link} to="/">Test</BreadcrumbLink>
    </BreadcrumbItem>
  <Breadcrumb>
)
```
please note that the `//` must be the first non-space character on the line above the offending line to make this work.

**Comment by aaronmcadam** [comment]
Here's a workaround I wrote where I wanted to use a `Button` as a react-router `Link`. This should work for Reach too:

```ts
import { Button } from '@chakra-ui/core';
import { ButtonProps } from '@chakra-ui/core/dist/Button';
import * as React from 'react';
import {
  Link as ReactRouterLink,
  LinkProps as RouterLinkProps
} from 'react-router-dom';

type ButtonLinkProps = ButtonProps & RouterLinkProps;

/**
 * This is to work around the `as` prop needing generics.
 * @see https://github.com/chakra-ui/chakra-ui/issues/148#issuecomment-540457308
 */
export const ButtonLink: React.FC<ButtonLinkProps> = React.forwardRef(
  (props: ButtonLinkProps, ref: React.Ref<any>) => {
    return <Button ref={ref} as={ReactRouterLink} {...props} />;
  }
);
```

**Comment by DavidJFelix** [comment]
unstale. this still exists with a number of link-based components when using reach

**Comment by segunadebayo** [comment]
Hi @DavidJFelix,

I'm going to close this considering it's a duplicate in the #205 issue. We've resolved this permanently in the TypeScript branch. It should be released by next month.

Thanks
