### ISSUE TITLE
docs(gatsby-plugin): update package name

### ISSUE THREAD

**Issue by TimKolberger** [chakra-ui/chakra-ui#2480]
# Bug report

## Describe the bug

https://github.com/chakra-ui/chakra-ui/blob/develop/website/pages/guides/integrations/with-gatsby.mdx
shows the old package name. 

Maybe in other locations as well.

## Expected behavior

Should be `@chakra-ui/gatsby-plugin`

## Additional context

The package got renamed after v1 release

**Comment by jmiazga** [comment]
I didnt realize we had a ticket for this. I fixed it earlier in https://github.com/chakra-ui/chakra-ui/pull/2435
