### ISSUE TITLE
Popover with width property set has positioning problem

### ISSUE THREAD

**Issue by sebqq** [chakra-ui/chakra-ui#2481]
# Bug report

## Describe the bug

Before rc.6 version I was able to set Popover's width (or minWidth) property to make it bigger. Using version rc.6 (or newer) there is a problem with popover positioning while width attribute is set.

## To reproduce

1. Open popover.
2. Popover has wrong position (is not aligned with its triggering element).

## Minimal reproduction

https://codesandbox.io/s/falling-microservice-oypkl?file=/src/index.js

## Expected behavior

Popover position should be recalculated correctly

## System information

- OS: macOS
- Version of @chakra-ui/react: 1.0.0

**Comment by nicklas-delphai** [comment]
I can confirm I'm facing the same issue. With `placement="bottom-start"` it positions correctly with enough space to the right, but if there's not enough space it will position as if it had the default width of `318px`
![2020-11-14_20-02](https://user-images.githubusercontent.com/67684610/99154953-100a2080-26b4-11eb-876c-fbeef4063bd3.png)

**Comment by dannyvaughton** [comment]
I have fixed this issue by doing:

```
const baseStylePopper = {
  w: "100%",
  maxW: "xs",
  zIndex: 10,
};

const theme = {
  components: {
    Popover: {
      parts: ["popper"],
      baseStyle: {
        popper: ({width}) => ({
          ...baseStylePopper,
          maxW: (width) ? width : baseStylePopper.maxW
        })
      }
    } 
  }
};
```

By updating the baseStyle to be function which uses the `width` prop instead of the default `maxW`.

If this is a suitable approach, I could apply this to Charka's main theme config and submit a pull request?

(FYI, I'd probably need to apply either `w` & `width` as props for consistency)

**Comment by Neilann** [comment]
> I have fixed this issue by doing:
> 
> ```
> const baseStylePopper = {
>   w: "100%",
>   maxW: "xs",
>   zIndex: 10,
> };
> 
> const theme = {
>   components: {
>     Popover: {
>       parts: ["popper"],
>       baseStyle: {
>         popper: ({width}) => ({
>           ...baseStylePopper,
>           maxW: (width) ? width : baseStylePopper.maxW
>         })
>       }
>     } 
>   }
> };
> ```
> 
> By updating the baseStyle to be function which uses the `width` prop instead of the default `maxW`.
> 
> If this is a suitable approach, I could apply this to Charka's main theme config and submit a pull request?
> 
> (FYI, I'd probably need to apply either `w` or `width` as props for consistency)

![image](https://user-images.githubusercontent.com/37895035/100993677-4981cd80-3588-11eb-9106-33978902fd05.png)
The `width` works, but the arrow now is under the content. I have tried to modify z-index, but id doesn't work.

**Comment by maxweng** [comment]
Thanks for the tips! But for some reason, the way you wrote doesn't work for me. Maybe that's because I'm using v1.0.1? 
So, I ended up have to get the `props` from baseStyle object, like something as follows:

``` javascript
  components: {
    Popover: {
      parts: ['popper'],
      baseStyle: props => ({
        popper: {
          zIndex: 10,
          maxW: props.width ? props.width : 'xs',
          w: '100%',
        },
      }),
    },
  },
```

**Comment by with-heart** [comment]
This is an interesting case, where a default style actually breaks custom usage and requires knowledge of the system (you have to understand that it sets `maxW` to `xs` by default to know to override it). imo we should either resolve this by changing the behavior of `w`/`width` as proposed by @dannyvaughton or we add this use case to our documentation. Setting the css value of a different prop than the one passed feels off to me, and could lead to potentially more confusing situations as you now need to know that for this specific use case, `w` doesn't actually set `width` but `max-width`.

cc: @chakra-ui/react-team Thoughts on this? Maybe a different way to solve?

**Comment by santialbo** [comment]
I don't think this is stale. A way to set the width of the popover is necessary. @dannyvaughton solution did not work for me very well.

**Comment by iamcristos** [comment]
Did anyone fix this issue yet?

**Comment by jordanlesich** [comment]
I'm having the same problem.

**Comment by jordanlesich** [comment]
I was able to do a rough patch by using the fix mentioned above, setting the width of a parent component, and using: 

```
.css-n0uled[style] {
  max-width: 100%;
}
```
My fix mostly sucks, and it will result in me having to scope the css to components and hope this doesn't break anything else. That being said, it doesn't look like I'm being given many options here.  Styles added to <PopoverContent/> are applied to the <section > and not the parent <div> where .css-n0uled[style] is. 

Hardcoding a popover's width to 20rem is...an odd choice. If this isn't going to be fixed any time soon, then I think there should be a warning in the docs.

**Comment by heikomat** [comment]
I had luck with the following adjustment to the theme:
```JS
components: {
  Popover: {
    baseStyle: {
      popper: {
        width: 'fit-content',
        maxWidth: 'fit-content',
      },
    },
  },
},
```

**Comment by mandyGitH** [comment]
In my case, thread #4104 helped.
