### ISSUE TITLE
[Tooltip] Doesn't show inside modals

### ISSUE THREAD

**Issue by fernandobandeira** [chakra-ui/chakra-ui#249]
Tooltips aren't working when used inside a modal body, currently tooltips are portals themselves and they don't have any z-index on them so they are hidden behind the modal body.

I think it's alright to not set any z-index on the tooltips but we shouldn't be using portals since it'll break if the tooltip should be rendered inside any element that has a  z-index attribute.

**Comment by segunadebayo** [comment]
Hi @fernandobandeira,

Thanks for your suggestions. I'll look into this. In the meantime, you can update the z-index of the tooltip.
