### ISSUE TITLE
Module not found: Can't resolve '@emotion/react' in '/Users/andrew/Projects/chakra/node_modules/@chakra-ui/css-reset/dist/esm' when running 1.0.0 CRA template

### ISSUE THREAD

**Issue by AndrewPrifer** [chakra-ui/chakra-ui#2493]
# Bug report

## Describe the bug
I get the following error when I try to run the newest 1.0.0 CRA (typescript) template:

```
/node_modules/@chakra-ui/css-reset/dist/esm/css-reset.js
Module not found: Can't resolve '@emotion/react' in '/Users/andrew/Projects/my-project/node_modules/@chakra-ui/css-reset/dist/esm'
```

## To reproduce

Install and start the official chakra CRA template.

## Minimal reproduction

--

## Expected behavior

The template starts without issues.

## System information

- OS: MacOS
- Version of @chakra-ui/react: 1.0.0
- Version of Node.js: v14.2.0
- Version of NPM: 6.14.4
- Version of Yarn: 1.22.4

(tried installing both with yarn and npm)

**Comment by dennismorello** [comment]
I'm submitting a PR to fix this.
