### ISSUE TITLE
IE11 Support on 1.0

### ISSUE THREAD

**Issue by dedo1911** [chakra-ui/chakra-ui#2498]
Trying to run anything on IE11 results in unhappy life, we know that.

But, the main issue to have Chakra running on IE looks to be related to framer-motion not supporting IE11.

I was able to have  most stuff working, apart from few components, following this suggestion: https://github.com/framer/motion/issues/364#issuecomment-723137822

My polyfills at begin of my entrypoint (note that proxyDefined has to be included BEFORE proxy-polyfill - as explained in the above link):
```node
import 'core-js/stable'
import { proxyDefined } from './clientState'
import 'proxy-polyfill'
import 'whatwg-fetch'
```

clientState.js
```javascript
const hasProxy = (scope) => !!scope.Proxy
export const proxyDefined = hasProxy(window)
```

framer-motion-wrapper.js
```javascript
import { motion as origMotion, createDomMotionComponent } from '../node_modules/framer-motion';
import { proxyDefined } from './clientState';

// fragile copied from internal framer-motion supported-elements.ts
import { htmlElements, svgElements } from './framer-motion-supported-elements';

// Adapted from https://github.com/framer/motion/commit/b4319c78fb4bde28ce0d2a8008df48d7e3fd1c8b
const createNonProxyMotion = () => {
  let motionProxy = {
    custom: (component) => {
      createDomMotionComponent(component);
    },
  };
  motionProxy = htmlElements.reduce((acc, key) => {
    acc[key] = createDomMotionComponent(key);
    return acc;
  }, motionProxy);
  motionProxy = svgElements.reduce((acc, key) => {
    acc[key] = createDomMotionComponent(key);
    return acc;
  }, motionProxy);
  return motionProxy;
};

export const motion = proxyDefined ? origMotion : createNonProxyMotion();
export * from '../node_modules/framer-motion';
```

I'm still having issues with the icon loaded from `AlertIcon` in `Alert` component:
![immagine](https://user-images.githubusercontent.com/1364496/99152643-468b6f80-26a3-11eb-9a56-4f201af1889c.png)

I know it's sub optimal to still support IE, but if that's anything easy might be worth a try.

Thanks everyone!

**Comment by with-heart** [comment]
Gonna investigate this when I have some time!

**Comment by rr-justin-hanselman** [comment]
@dedo1911  - Hey Dedo,

Note sure if you've gotten any further with the error here.  If you drill down into the source for CheckIcon, it loads Icon from icon.tsx and that uses chakra.svg.

If this is indeed still IE11 polyfill related, it may have something to do with 
```javascript
import { htmlElements, svgElements } from './framer-motion-supported-elements';
```

I haven't run into this issue yet, but I'm sure I will, so any input on where your implementation is blowing up would be a great lifesaver for me later!

**Comment by cezarneaga** [comment]
hi there everyone,

i am having issues with IE11 too. :(
in my case : `unable to get property '__emotion_real' of undefined or null reference.`

i have 
```
import 'react-app-polyfill/ie11'
import 'react-app-polyfill/stable'
import 'proxy-polyfill'
```
any ideas?

**Comment by haapti** [comment]
hello

i have next.js / chakra project which im trying to get work on IE11. my current configuration is follow:

**_app.tsx**
```
import 'core-js/stable';
import 'proxy-polyfill';
```

**next.config.js**
```
const { readdirSync } = require('fs');
const { join } = require('path');
const withPlugins = require('next-compose-plugins');

const modules = ['proxy-polyfill'];

const withTM = require('next-transpile-modules')([
	...readdirSync(join(__dirname, 'node_modules/@chakra-ui')).map((m) => '@chakra-ui/' + m),
	...modules,
]);

module.exports = withPlugins([withTM], {
	trailingSlash: true,
	webpack: (config) => {
		config.resolve.alias = {
			...(config.resolve.alias || {}),
			dequal: 'dequal/lite',
		};
		return config;
	},
});
```

**no wins here yet. IE11 is givin this error, which im not still figured out how to solve. any ideas?**

![IE11 error](https://user-images.githubusercontent.com/9010889/101392220-24fe5c00-38ce-11eb-892b-26f9a8d06d3c.png)

**Comment by mirai-will** [comment]
Finally, I got working on IE11
Following this issue: https://github.com/framer/motion/issues/364

Replace all occurrences `motion.XXX` to  `createDomMotionComponent(XXX)`

Example:
`node_modules/@chakra-ui/modal/dist/esm/modal.js`

line:11
```js
- import { AnimatePresence, motion, usePresence } from "framer-motion";
+ import { AnimatePresence, motion, usePresence, createDomMotionComponent } from "framer-motion";
```
line:80
```js
- var Motion = chakra(motion.div);
+ var Motion = chakra(createDomMotionComponent("div"));
```
Patch all occurrences under the `node_modules/@chakra-ui`

My `index.js` imports are like this.

```
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';
import 'proxy-polyfill';
```

**Comment by trickydisco78** [comment]
I've got the exact same issue as above

in my case : unable to get property '__emotion_real' of undefined or null reference.
=
![image](https://user-images.githubusercontent.com/3627429/106479904-bc34f980-64a2-11eb-89c7-5d3768010cc0.png)

did anyone manage to fix it?

**Comment by trickydisco78** [comment]
@dedo1911 for the framer motion wrapper did you eject CRA to get this to work or is there another way to reference the wrapper component?

**Comment by trickydisco78** [comment]
@mirai-will  Did you use patch package at all to do this? Would be great if you could share that

**Comment by takutoaoi** [comment]
@trickydisco78 
Here is minimum example that running Chakra UI on IE11.
After `npm ci`, run `bash patch.sh`. 
https://github.com/takutoaoi/chakra-ui-ie11

**Comment by trickydisco78** [comment]
Thanks so much @takutoaoi  I tried doing it with the wrapper example but it didn't work

I suppose the only issue is we'd have to pin the chakra version number to stop any future updates breaking it

**Comment by trickydisco78** [comment]
Wondering if there is a way to create a separate js build in webpack for IE11?

**Comment by rr-justin-hanselman** [comment]
I'm gonna go ahead and use this bug to document some further IE11 issues.

Chakra v1 made the change to using CSS variables for anything theming related.  This means that, if you use theme variables, your styles will not work on IE11 since they will be set with a variable reference.  I have solved this internally in my own project, but am a ways away from making a public project.  Here's the cliff notes though:

You can create a stylis v4 plugin that:
1. passes through is CSS variables are supported
2. If not, then it does the reverse of what Chakra has already done - stores a map of all css variable declarations AND then replaces those variable declarations with the values when it finds them used in another style declaration.

Additionally, I've found some chakra styles use RGBA Hex codes, which aren't IE11 supported (at least in my testing).  You would want another stylis plugin that detects the presence of these hex codes and replaces them with "rgba(R, G, B, A)" instead.

With those two plugins in your pipeline and a custom cache created by "@emotion/cache", I've found that the mystery of the missing styles seems to be solved!

**Comment by spykr** [comment]
Apologies @rr-justin-hanselman but IE11 is no longer supported by Chakra v1, hence the move to CSS variables.

See this comment from @segunadebayo: https://github.com/chakra-ui/chakra-ui/pull/2762#issuecomment-753606667

You can however continue to use Chakra v0.8 for IE11 support as I have done.

**Comment by trickydisco78** [comment]
Would love to see examples of this @rr-justin-hanselman . I don't quite understand this part

```
    passes through if CSS variables are supported
    If not, then it does the reverse of what Chakra has already done - stores a map of all css variable declarations AND then replaces those variable declarations with the values when it finds them used in another style declaration.
```

**Comment by rr-justin-hanselman** [comment]
Hey @trickydisco78 ,

Since it was a company project, my code is currently private, but the general gist is:

`
const varMap = {};

  const ie11RevertCssVars = (element) => {
    if (isServer() || browserCanUseCssVariables()) return;
    if (element.type === 'decl') {
       // Process chakra's global variable declaration
       if (element.props.match(cssVarRegex)) {
          // Add variable to map
          varMap[element.props.trim()] = element.children;
       } else if (element.value && cssVarSubRegex(element.value)) {
         // Sub any variables that were already stored for and are now showing up as references
         element.value = varMap[element.value.trim()];
       }
    }
  }
`

If I have the time and go-ahead, my may be able to break out my stylis plugins into public repos.  But this should get you started (note, a more verbose solution would consider multiple scopes, etc.). I recommend browsing the stylis-v4 types to get an idea of how their new plugin system works.  Hope it helps!

**Comment by hanseltime** [comment]
@trickydisco78 -

I know this is late, but I've created a repo of stylis plugins that can be used to revert certain chakra-ui css properties to match IE11.  (They're published as packages as well).

The repo also has an example NextJS + chakra-ui app with minimum polyfills (does not include the original fix on this thread, which may still be necessary).  For anyone trying to tackle this, or wanting to add other style fixes to the stylis system, feel free to give it a look!

**Comment by goethel** [comment]
Anyone else having problems with the patched Chakra (from @mirai-will , thanks!) and certain elements like Toast & Checkbox re-rendering constantly if the mouse is hovered over them, causing a flickering effect? I'm thinking its something to do with AnimatePresence, but I cant figure it out exactly...

It doesnt happen before running the patch to replace the function calls to createDomMotionComponent, but it does as soon as I apply the patch. 

Did anyone else experience this and find a solution?

**Comment by hanseltime** [comment]
@goethel

I've gone ahead and added a checkbox to the example NextJs project here: 
https://github.com/hanseltime/stylis-ie11-plugins/tree/master/examples/chakra-app

It looks like framer-motion changed it's motion signature, so you'll have to update your wrapper component.  

I've added a checkbox, but didn't add a toast (also, no formatting beyond proving the problems I wanted to handle).

If you want to play with the app and test it with a Toast, feel free to contribute back feedback if it's still not working.  I wouldn't mind keeping a running example.  (At some point, I should break it into a github template).

Let me know if that helps!

**Comment by goethel** [comment]
Hey @hanseltime ,

Thank you so much! I was able to get my project running successfully on IE11 without the patch above with your plugins. Checkboxes&Toasts no longer flicker, but Toasts still dont work in IE (they are added to the chakra toast portal div in the DOM successfully, but the end user's screen doesn't see them). 

However, this is now a styling problem and not a "IE11 wont work at all" problem, so it's one I can likely solve. 

Thanks again!

**Comment by hanseltime** [comment]
@goethel Glad it works!  If you wouldn't mind commenting the style problem with toast here, I may try incorporating it into the stylis plugins repo later.

**Comment by muradsofi** [comment]
@haapti Did U find any solution for this error?

**Comment by muradsofi** [comment]
So when I try to run my application in IE 11 I get an error 

You are trying to create a styled element with a undefined component

Does anyone know how we can solve this issue?

**Comment by with-heart** [comment]
Have you followed any of the suggestions or ideas in the thread?
