### ISSUE TITLE
Global Search on documentation site

### ISSUE THREAD

**Issue by drixie** [chakra-ui/chakra-ui#2500]
# Feature request

## Is your feature request related to a problem? Please describe.

People who are new to chakra will refer to the documentation site very frequently, and it takes a while to find what you are looking for

## Describe the solution you'd like

Global search for features/elements, similar to the implementation on the tailwind docs

## Describe alternatives you've considered

CTRL+F on every page :'(

**Comment by ljosberinn** [comment]
The search will return soon, algolia needs to index it first and we're rewriting the search component :) hold out!
