### ISSUE TITLE
[Transition]

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#2501]
[SlideFadeProps](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/transition/src/slide-fade.tsx#L59) and probably others too only allow `number` for `offsetX` and `Y`. When using units, e.g. `20%`, a string would be required, which is currently not allowed by the types, although it works. Ironically the docs themselves use it too.

**Comment by segunadebayo** [comment]
This has been resolved a while back:
https://github.com/chakra-ui/chakra-ui/commit/c4b14644ae80af1a3f77b3fa960172dee5c8183f
