### ISSUE TITLE
Tooltip delay + Drawer = bug

### ISSUE THREAD

**Issue by crubier** [chakra-ui/chakra-ui#2503]
# Bug report

## Describe the bug

Tooltips with a delay applied to buttons that open drawer causes the following problem:

- If the user clicks on the button **before** the tooltip appears, 
    - The drawer appear, so far so good.
- Then if the user moves the cursor out of where the button was, still **before** the tooltip appears
    - Then the tooltip **still** appears after the drawer, on top of it, creating a weird graphical bug. The tooltip is then impossible to dismiss without leaving the drawer.

This might sound like a rare case, but it happens all the time if you put a normal delay of 500-1000ms to the tooltip, and use the tooltip on a button that opens a drawer. 

Some variants of the bug happen depending on the exact configuration. 

## To reproduce

https://codesandbox.io/s/youthful-rgb-iit3e?file=/src/App.tsx

## Minimal reproduction

https://codesandbox.io/s/youthful-rgb-iit3e?file=/src/App.tsx

## Expected behavior

Tooltip should only appear if its target is visible on screen for example. Here it happens even though there is a drawer in front of it.

## Screenshots

![Screen Recording 2020-11-15 at 01 38 14 mov](https://user-images.githubusercontent.com/2954572/99160822-6b073c00-26e3-11eb-9608-1d1c8e82b639.gif)

## System information

- OS: macOS but I suspect all
- Browser: Chrome but I suspect all
- Version of @chakra-ui/react: 1.0.0

**Comment by Jamesgilje** [comment]
I'm having a similar issue with tooltips on MenuButtons. If the tooltip has an openDelay, when you click the button and hover to the MenuList the tooltip still pops up on top of the MenuList. 

![tooltipTest](https://user-images.githubusercontent.com/12547640/100892920-6fbc4600-3480-11eb-9d6a-4ad2d553fbf7.gif)

**Comment by prayogoa** [comment]
Still an issue in 1.1.4 https://codesandbox.io/s/broken-microservice-cz6ks?file=/src/App.js
![untitled](https://user-images.githubusercontent.com/1696217/104320799-bee4a480-551d-11eb-8bbf-b0b53d95e12a.gif)

**Comment by crubier** [comment]
Still an issue

**Comment by yotam707** [comment]
Still an issue, please open!

**Comment by yotam707** [comment]
@dodas

**Comment by crubier** [comment]
To be honest, I think this is more generally a problem with ToolTips in Chakra, which are not ideal. A lot of annoying behaviours

**Comment by delucca** [comment]
No updates on this? This is messing up with my app =/

**Comment by anubra266** [comment]
@dodas, does this issue still exist?

**Comment by with-heart** [comment]
Appears to be resolved at least in latest: https://codesandbox.io/s/admiring-taussig-kd5lv?file=/src/App.tsx (the original CSB updated to latest)

Can someone having this issue please confirm/deny that?

**Comment by vcastroi** [comment]
Still happening @with-heart 
![image](https://user-images.githubusercontent.com/17008138/120583753-abaa7680-c3e3-11eb-83e3-539579a48771.png)

**Comment by whyroland** [comment]
*sigh*

![image](https://user-images.githubusercontent.com/42717361/127741119-e203b0d0-1821-4e69-9a0c-bc58b11474ab.png)

**Comment by NathZ1** [comment]
I'm having the same problems with these tooltips... are there any workarounds?

**Comment by matt-dale** [comment]
I implemented this tooltip package to get around the issue:
https://github.com/mohsinulhaq/react-popper-tooltip

It works well enough.

**Comment by delucca** [comment]
Thanks @matt-dale

Since no one is considering this issue a priority, sadly I would need to move to a different library. This component in Chakra is simply useless.

**Comment by nicmeriano** [comment]
I got bit by this bug as well. At first I assumed it had to do with the focus event emitting after the click, which would cause the tooltip to display after the provided delay. However looking at the [onClick](https://github.com/chakra-ui/chakra-ui/blob/bb99f3c0855455f0ad1343536ace2defcfbf492c/packages/tooltip/src/use-tooltip.ts#L132) handler it looks like it does actually clear (or at least tries to) the enter timeout that calls the `onOpen` handler. I'm going to go ahead and guess something's interfering with the clearing of that timeout. 

For the time being a workaround that worked for me is triggering a close on mouse down:
```tsx
<Tooltip label="My tooltip" openDelay={1000} closeOnMouseDown={true}>
   <Button>Click me</Button>
</Tooltip>
```

This fixes a tooltip popping up after a button has been clicked. The examples above include popups that auto-focus on buttons with tooltips which triggers their display. That behavior is expected and not a bug.

**Comment by wyatt** [comment]
Any updates on this? - It's quite frustrating! This occurs on _quickly_ hovering over multiple elements
![image](https://user-images.githubusercontent.com/40368472/158070647-df3114b3-45dd-41c9-abf9-06674f654878.png)

**Comment by colinmorelli** [comment]
After some digging internally on one of our apps, I believe this might actually be caused by a "bug" in React: https://github.com/facebook/react/issues/23165

I was able to confirm, as far as I can tell, that onFocus and onBlur events are being triggered out of order. The button with a tooltip believes it is focused (which is why the timer is not canceled correctly), even though `document.activeElement` is another element. Working on a repro.

**Comment by itkrt2y** [comment]
not stale
