### ISSUE TITLE
Radio standalone don't have a color

### ISSUE THREAD

**Issue by mjcarnaje** [chakra-ui/chakra-ui#2505]
# Bug report

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies): [e.g. Chrome, Safari]
- Version of @chakra-ui/react: [e.g. 1.0.0-rc.3]
- Version of Node.js: [e.g. 12.11.1]

**Comment by TimKolberger** [comment]
Please update chakra to version 1.0.0, it is fixed there: https://codesandbox.io/s/chakra-ui-issue-2505-stff1?file=/src/App.tsx
