### ISSUE TITLE
[1.0] Wrong box-shadow of invalid Input with flushed variant

### ISSUE THREAD

**Issue by nghiepit** [chakra-ui/chakra-ui#2508]
Hi,

When I focus the Input with `variant="flushed"` and `isInvalid ` props the `box-shadow` is wrong.

```jsx
 <Input variant="flushed" isInvalid placeholder="Focus me" />
```

## Minimal reproduction

Reproduction: https://codesandbox.io/s/tender-star-wqddl?file=/src/App.js

## Expected behavior

Should works properly

## Screenshots
![image](https://user-images.githubusercontent.com/4768095/99182261-86fff180-2766-11eb-91a7-6c38fe29bc28.png)

## System information

- OS: [e.g. macOS, Windows]
- Version of @chakra-ui/react: [e.g. 1.0.0]

**Comment by segunadebayo** [comment]
Hi @nghiepit ,

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by nghiepit** [comment]
Hey @segunadebayo 

Your fix has been created a new issue with the border style.

![image](https://user-images.githubusercontent.com/4768095/103151007-823e4c80-47ac-11eb-86f0-ba4f6b7d44e4.png)
