### ISSUE TITLE
DrawerContent as form breaks the placement of Drawer

### ISSUE THREAD

**Issue by mrcnk** [chakra-ui/chakra-ui#2510]
# Bug report

First of all, congrats on releasing 1.0 🎉 

## Describe the bug

`Drawer` component gets misplaced when I add `as="form"` to `DrawerContent`.
I use Chakra together with React Hook Form and my current workaround is to add `as="form" onSubmit={handleSubmit(onSubmit)}` to the `DrawerOverlay` component.

## To reproduce

1. Add a Drawer component with DrawerContent to your app
2. Add `as="form"` to DrawerContent
3. Drawer gets misplaced

## Minimal reproduction

[Here we go](https://codesandbox.io/s/happy-vaughan-2blgo?file=/src/App.tsx)

## Expected behavior

DrawerContent should accept `as="form"` and Drawer should stay on its correct place

## Screenshots

![image](https://user-images.githubusercontent.com/16132011/99186090-2b296e80-274e-11eb-9242-6d1a79e8c6bc.png)

## System information

- OS: macOS Big Sur
- Browser (if applies): New school Edge
- Version of @chakra-ui/react: 1.0.0
- Version of Node.js: 12.18.3

**Comment by segunadebayo** [comment]
I just updated the docs to show the recommended way to do this.

If you need to put a form within the Drawer, you might need to use to form validation library like `react-hook-form` or `formik`. Here's the recommended way to do it:

> Because the button is located outside the form, you can leverage its native HTML `form` attrbute and refer to the `id` of the `form`.

```jsx live=false
export const App = () => {
  const { isOpen, onOpen, onClose } = useDisclosure()
  return (
    <>
      <Button onClick={onOpen}>Open</Button>
      <Drawer isOpen={isOpen} onClose={onClose}>
        <DrawerOverlay />
        <DrawerContent>
          <DrawerCloseButton />
          <DrawerHeader>Create your account</DrawerHeader>

          <DrawerBody>
            <form
              id="my-form"
              onSubmit={(e) => {
                e.preventDefault()
                console.log("submitted")
              }}
            >
              <Input name="nickname" placeholder="Type here..." />
            </form>
          </DrawerBody>

          <DrawerFooter>
            <Button type="submit" form="my-form">
              Save
            </Button>
          </DrawerFooter>
        </DrawerContent>
      </Drawer>
    </>
  )
}
```
