### ISSUE TITLE
Menu Regression: Prop gutter is not applied to popper element

### ISSUE THREAD

**Issue by gauthierrodaro** [chakra-ui/chakra-ui#2511]
# Bug report

## Describe the bug

The Menu component doesn't apply the gutter props to popper.

```(jsx)
<Menu gutter={100}>
        <MenuButton as={Button}>Actions</MenuButton>
        <MenuList>
            <MenuItem>Download</MenuItem>
            <MenuItem>Create a Copy</MenuItem>
            <MenuItem>Mark as Draft</MenuItem>
            <MenuItem>Delete</MenuItem>
            <MenuItem>Attend a Workshop</MenuItem>
        </MenuList>
</Menu>
```

## To reproduce

1. Go to the following codesandbox https://codesandbox.io/s/chakra-menu-gutter-regression-2r3ob
2. Click on the menu you should see the default gutter of 8px instead of 100 from props
3. Click on the popover you should see the correct gutter of 100px

## Minimal reproduction

https://codesandbox.io/s/chakra-menu-gutter-regression-2r3ob

## Expected behavior

Menu should apply the gutter value when it is set in the props.

## System information

- Version of @chakra-ui/react: 1.0.0

## Additional context

This was not a problem with the release candidate 1.0.0-rc7

**Comment by segunadebayo** [comment]
Hi @gauthierrodaro ,

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
