### ISSUE TITLE
Modal Width Does Not Respect Responsive Props

### ISSUE THREAD

**Issue by TransmissionsDev** [chakra-ui/chakra-ui#2512]
# Bug report

## Describe the bug

When using responsive props to set the `ModalContent` width or height, it will simply ignore them and use the default value.

## To reproduce

```
function BasicUsage() {
  const { isOpen, onOpen, onClose } = useDisclosure()
  return (
    <>
      <Button onClick={onOpen}>Open Modal</Button>

      <Modal isOpen={isOpen} onClose={onClose}>
        <ModalOverlay />
        <ModalContent width={{md: "100px", xs: "100px"}} height={{md: "100px", xs: "100px"}}>
          <ModalHeader>Modal Test!</ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            <Lorem count={2} />
          </ModalBody>

          <ModalFooter>
            <Button colorScheme="blue" mr={3} onClick={onClose}>
              Close
            </Button>
            <Button variant="ghost">Secondary Action</Button>
          </ModalFooter>
        </ModalContent>
      </Modal>
    </>
  )
}
```
## Minimal reproduction

The codesandbox templates are using v0.8 (#2506) but you can reproduce on the editable example: https://chakra-ui.com/docs/overlay/modal

## Expected behavior

It should respect the responsive props like it did in v0.8

## Screenshots

![ScreenShot-](https://user-images.githubusercontent.com/26209401/99178932-44d6a180-26cd-11eb-8314-b0166f96f869.png)

## System information

- OS: [e.g. macOS, Windows]: MacOS
- Browser (if applies): Chrome Latest
- Version of @chakra-ui/react: 1.0.0
- Version of Node.js: [e.g. 12.11.1]: 12.13.1

**Comment by jmiazga** [comment]
Hey @TransmissionsDev. Can you try and replace `xs` with `base`?

`<ModalContent width={{md: "100px", base: "100px"}} height={{md: "100px", base: "100px"}}>`

**Comment by TransmissionsDev** [comment]
> Hey @TransmissionsDev. Can you try and replace `xs` with `base`?
> 
> `<ModalContent width={{md: "100px", base: "100px"}} height={{md: "100px", base: "100px"}}>`

That does fix! So the issue seems to be with the `xs` responsive prop. Was I just using it incorrectly all along and should have been using base? Why is `xs` not longer working?

**Comment by jmiazga** [comment]
I saw @ljosberinn call out  earlier in discord that `xs` didnt actually exist in v0, and that someone mentioned in an issue that it was implicitly working because as an unknown breakpoint it would just be treated as the default one.

**Comment by TransmissionsDev** [comment]
> I saw @ljosberinn call out earlier in discord that `xs` didnt actually exist in v0, and that someone mentioned in an issue that it was implicitly working because as an unknown breakpoint it would just be treated as the default one.

Haha that's crazy! Well I'll know to use `base` from now on 👍
