### ISSUE TITLE
LinkBox: update Docs for #link-around-containers

### ISSUE THREAD

**Issue by dodas** [chakra-ui/chakra-ui#2515]
Currently, the [ Docs mention the `outbreak` prop for the `<Link>` component](https://chakra-ui.com/docs/components/link#link-around-containers).
However, this prop has been replaced by the `LinkBox` component, which is undocumented at all.

Probably current `outbreak` prop docs is a good place for the `LinkBox` as well.

**Comment by TheThirdRace** [comment]
After using the current LinkBox component, I would say it's missing flexibility.

One of the biggest flaw is that it uses Chakra's Link component without the possibility to replace it with something else.

Given a lot of people use Gatsby or NextJs, that makes the LinkBox unusable.

**Comment by TheThirdRace** [comment]
This is my LinkBox implementation for reference:

```
import { Box, ThemingProps, useMultiStyleConfig } from '@chakra-ui/react'
import { cloneElement, PropsWithChildren, ReactElement } from 'react'
import { Link, LinkProps } from './Link'

type LinkBoxProps = Pick<ThemingProps, 'variant'> &
	Partial<Pick<LinkProps, 'href'>> &
	PropsWithChildren<{
		link?: ReactElement
	}>

export const LinkBox = ({ children, href, link, variant, ...linkBoxInternals }: LinkBoxProps): ReactElement => {
	const styles = useMultiStyleConfig('LinkBox', { variant })
	const linkOverlay = link || <Link href={href || '/'} />
	return (
		<Box
			sx={styles.layLinkBox}
			// eslint-disable-next-line react/jsx-props-no-spreading
			{...linkBoxInternals}
		>
			{children}
			{cloneElement(linkOverlay, { sx: styles.linkBoxOverlay)}
		</Box>
	)
}
```

It allows to use the LinkBox directly if you only want the href & variant:

```
<LinkBox href='/' variant='pageNavHome'>
			<Image
				src='/icon/64/ttr-glow.png'
				alt='TheThirdRace.com logo'
				dimensions={[48, 48]}
				layout='fixed'
				loading='eager'
				priority
				quality='100'
			/>
			{isDisplayText ? 'TheThirdRace.com' : undefined}
		</LinkBox>
```

or by passing the Link component you need with all its parameters:

```
<LinkBox link=<NextJsChakraLink href='https://google.ca' isExternalNoFollow isExternal variant='navExternal'>>
			<Image
				src='/icon/64/ttr-glow.png'
				alt='TheThirdRace.com logo'
				dimensions={[48, 48]}
				layout='fixed'
				loading='eager'
				priority
				quality='100'
			/>
			{isDisplayText ? 'TheThirdRace.com' : undefined}
		</LinkBox>
```

Note that I use a custom Link component in my implementation because I'm using NextJs and it's easier to simply wrap LinkBox to use my own Link than passing the Link component every time as parameters. But the principle remains the same, you can put there Chakra's Link component instead. And people that need a different default can always wrap LinkBox to automatically pass their Link component as default.

**Comment by ugcgt** [comment]
[](https://163.com)

**Comment by ugcgt** [comment]
**__**

**Comment by ugcgt** [comment]
ث__

**Comment by ugcgt** [comment]
- [ ]

**Comment by segunadebayo** [comment]
I updated the docs to include this already.
