### ISSUE TITLE
Can't display Skeleton animation

### ISSUE THREAD

**Issue by delucca** [chakra-ui/chakra-ui#2516]
Hi!

I'm trying to move my application from Material-UI to Chakra-UI, but I'm failling to make `Skeleton` component to work.

I'm using NextJS as my framework, and I have already create the required `ChakraProvider`. Any Chakra component is working as expected, but as soon as I add a Skeleton it simply wont show. It creates the div, adds the required classes to it, but the animation won't work.

Any idea how to fix it?

**Comment by Xunpok** [comment]
Need a anchor 

Von meinem iPhone gesendet

**Comment by delucca** [comment]
> Need a anchor Von meinem iPhone gesendet
> […](#)
> Am 15.11.2020 um 22:04 schrieb Daniel De Lucca ***@***.***>: ﻿ Hi! I'm trying to move my application from Material-UI to Chakra-UI, but I'm failling to make Skeleton component to work. I'm using NextJS as my framework, and I have already create the required ChakraProvider. Any Chakra component is working as expected, but as soon as I add a Skeleton it simply wont show. It creates the div, adds the required classes to it, but the animation won't work. Any idea how to fix it? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Sorry, I did not understand your comment. What do you mean by `a anchor`? 

I've just followed the Skeleton page at Chakra website.

**Comment by TimKolberger** [comment]
The [Skeleton](https://chakra-ui-drd9dxh6o.vercel.app/docs/feedback/skeleton#usage) needs either an explicit height or some children. But I think you are looking for the additional Components `SkeletonText` or `SkeletonCircle`:

```tsx
<Box padding="6" boxShadow="lg" bg="white">
  <SkeletonCircle size="10" />
  <SkeletonText mt="4" noOfLines={4} spacing="4" />
</Box>
```

[Example in Codesandbox](https://codesandbox.io/s/chakra-ui-skeleton-bbeoc?file=/src/App.tsx)

Feel free to join our [discord](https://discord.gg/yxpPm4q) for additional questions!

**Comment by delucca** [comment]
@timkindberg does NextJS has any special requirement? Because I'm using exactly your provided example and it is not working...

**Comment by ljosberinn** [comment]
No, here's a nextjs sandbox where it behaves exactly the same 🤔 https://codesandbox.io/s/compassionate-mclean-c0s9j?file=/pages/index.js

**Comment by delucca** [comment]
Strange.

I'm going to take a more detailed look in my code. It seems that the animations are not being applied.

**Comment by yotam707** [comment]
@delucca were you able to solve this?
