### ISSUE TITLE
fontSize prop on Heading sets lineHeight too high

### ISSUE THREAD

**Issue by TransmissionsDev** [chakra-ui/chakra-ui#2518]
# Bug report

## Describe the bug

When using `fontSize` on a `Heading` component, it increases the lineHeight to `2.25em` which is different behavior from v0.8 and makes the text have far too much spacing around it.

## To reproduce

Create a `<Heading>` component with a `fontSize` prop set to a small amount like `20px`. It will have a massive line height of `2.5em`

![](https://media.discordapp.net/attachments/776516215337386054/777704697364086804/ScreenShot-.png?width=1080&height=388)

## Minimal reproduction

`<Heading fontSize="20px">Hello</Heading>`

You can reproduce this on the editable example on the docs: https://chakra-ui.com/docs/typography/heading

## Expected behavior

The lineHeight should be a more reasonable amount like 1.25em for smaller fontSizes.

## Screenshots

![](https://media.discordapp.net/attachments/776516215337386054/777704697364086804/ScreenShot-.png?width=1080&height=388)

![image](https://user-images.githubusercontent.com/26209401/99208624-def22480-2775-11eb-9201-c4cd25ec4b78.png)

## System information

- OS: MacOS
- Browser (if applies): Chrome Latest
- Version of @chakra-ui/react: ^1.0.0
- Version of Node.js: v12.13.1

## Additional context

This was not an issue in v0.8. 
![ScreenShot-](https://user-images.githubusercontent.com/26209401/99208680-08ab4b80-2776-11eb-9ca8-9b7b5ba1edff.png)

**Comment by segunadebayo** [comment]
We've updated the Heading component to use `em` values that are relative to font-size, instead of absolute values.

We'll release an update shortly
