### ISSUE TITLE
Feature Request/Missing: Disable Modal Animations/Transitions

### ISSUE THREAD

**Issue by TransmissionsDev** [chakra-ui/chakra-ui#2519]
# Feature request

## Is your feature request related to a problem? Please describe.

In v0.8, it was optional to add a transition like scale or fade-in to the modal. With v1, you can still choose which animation you like, but there is no way to choose not to have an animation show when the modal first renders.

## Describe the solution you'd like

I'd like to be able to set `motionPreset` to `none` to disable the initial animation. 

## Describe alternatives you've considered

I've tried not setting `motionPreset` or setting it to `undefined` but this just used the default `scale` animation.

**Comment by mashabow** [comment]
> ## 1.4.0
> 
> ### Minor Changes
> 
> - [`6a82a3d4`](https://github.com/chakra-ui/chakra-ui/commit/6a82a3d4f061191171a12e6d38719ba05414a86e) [#2888](https://github.com/chakra-ui/chakra-ui/pull/2888) Thanks [@ytakayanagi](https://github.com/ytakayanagi)! - Added "none" option in motionPreset prop to disable animation in modal component

In [@chakra-ui/modal@1.4.0](https://github.com/chakra-ui/chakra-ui/blob/%40chakra-ui/modal%401.4.0/packages/modal/CHANGELOG.md), now we can disable the `ModalContent` transition with `motionPreset="none"`. However, I found that it doesn't disable the `ModalOverlay` transition.

https://user-images.githubusercontent.com/6268183/103655222-496f5600-4faa-11eb-9f65-034c42bebbac.mp4

I think it would better to disable both `ModalContent` and `ModalOverlay` transitions for consistency.

**Comment by nappalm** [comment]
How can you change that animation globally? I have seen the [code](https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/theme/src/components/modal.ts) of the theme, but I can not find anything about it
