### ISSUE TITLE
Request to add [Label] component

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#252]
**Is your feature request related to a problem? Please describe.**
As [mentioned in the docs](https://chakra-ui.com/input#props), input fields may be labeled visually, e.g. with a text above the component:

> `aria-label`: Accessibility label to use, in scenarios where the input has no **visible label.** A11Y: It's useful for screen readers.

**Describe the solution you'd like**
Similar to the native `label` element, a `Label` component should be added.

**Describe alternatives you've considered**
An other solution is to improve the docs about labeling form elements.

**Comment by aaronmcadam** [comment]
I tend to use `FormControl` for this, should the docs suggest using that component to get a label?

**Comment by segunadebayo** [comment]
@kripod, you can use the `FormLabel` component. I don't see a need for a separate `Label` component.

**Comment by kripod** [comment]
@segunadebayo I apologize, but I haven't heard about it previously. I'd like to suggest adding an example with a `FormLabel` to the documentation page of Inputs.
