### ISSUE TITLE
[1.0.0] isLazy prop on Popover error when close

### ISSUE THREAD

**Issue by nghiepit** [chakra-ui/chakra-ui#2521]
# Bug report

Using `isLazy` prop on `Popover` component, when close 
>Popper: "arrow" modifier's `element` must be a child of the popper element. 

## To reproduce

1. Click Trigger button
2. Click outside
3. Check console.log

## Minimal reproduction
Reproduction https://codesandbox.io/s/snowy-silence-xftso?file=/src/App.js

## Screenshots
![image](https://user-images.githubusercontent.com/4768095/99210918-aa27b100-27f9-11eb-881d-7ee516e25d34.png)

## System information
- Browser (if applies): [e.g. Chrome, Safari]
- Version of @chakra-ui/react: [e.g. 1.0.0]

**Comment by anthowm** [comment]
I just add a sandbox with 1.0.0 rc7 working  so I think this is a regression https://codesandbox.io/s/billowing-https-1j366?file=/src/App.js:551-1140

**Comment by rodbs** [comment]
I'm experiencing the same issue in 1.0.3

**Comment by nghiepit** [comment]
Maybe the issue has been resolved in the recent `@chakra-ui/react@1.0.4` version.

**Comment by nghiepit** [comment]
The issue out again in `1.1.5`

**Comment by rodbs** [comment]
Still in `1.1.6`

**Comment by MarcLongJoyride** [comment]
Here to report same issue. I think it is also affecting the performance of the Popover when this error occurs.

**Comment by segunadebayo** [comment]
This error doesn't occur in the most recent version. Kindly upgrade
