### ISSUE TITLE
Textarea with autoExpand functionality.

### ISSUE THREAD

**Issue by SimonHoiberg** [chakra-ui/chakra-ui#2524]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, the `Textarea` component supports a `resize` prop that allow you to resize the area.
But there is no way to have the textarea automatically expand.

## Describe the solution you'd like
It would be great if the `Textarea` component also supported an `autoExpand: boolean` prop, that allows the textarea to automatically expand (vertically) as text is filled.
Ideally in combination with an `maxHeight` prop that defines the threshold for when the scrollbar should start appearing instead of the textarea expanding.

## Visual example
![](https://s3.amazonaws.com/impressivewebs/2012-01/textarea-auto-resize.jpg)

## Describe alternatives you've considered
I currently use a homemade solution for this in extension to the component, but I think it would be awesome if this was natively supported.

## Additional context
If and when this issue gets approved/refined, I'd be happy to pick it up and work on it 🙌

**Comment by santialbo** [comment]
This has been discussed before in #670

**Comment by Silind** [comment]
Ah, I see.
My apologies, I didn't see that.

Is there a reason why this feature didn't find its way into chakra?
I still think it would be amazing not having to implement this myself or add extra external dependencies to achieve it.
