### ISSUE TITLE
Upgrading to v1 has broken fonts in Storybook

### ISSUE THREAD

**Issue by hutber** [chakra-ui/chakra-ui#2527]
After upgrading to `v1.0.0` it appears that my storybook has stopped working. I have updated my preview.js file with the updated ChakraProvider:

```
addDecorator((storyFn) => (
  <ChakraProvider resetCSS theme={theme}>
    {storyFn()}
  </ChakraProvider>
));
```

The issue is that the theme variables are being output directly on the component:
```
    <Heading variant="caps6" as="h1">
       Heading Caps6
    </Heading>
```
![image](https://user-images.githubusercontent.com/1344898/99255399-c7657b00-280b-11eb-945b-b33a012b85c5.png)

Here is the same code working within the react app:
![image](https://user-images.githubusercontent.com/1344898/99255451-db10e180-280b-11eb-8632-4e9a9a1f7eaa.png)
What I find that is interesting is that the `font-family` is not `demi` it is just `cap`

Just confirmation that all the fonts and styles have loaded, but are just not being applied:
![image](https://user-images.githubusercontent.com/1344898/99255204-7d7c9500-280b-11eb-8a14-dc7f8fce006d.png)

**Comment by Zyclotrop-j** [comment]
Seems to me to be a general issue: All theme-properties aren't getting resolved anymore.

<img width="176" alt="Screen Shot 2020-11-17 at 12 36 48 am" src="https://user-images.githubusercontent.com/4939546/99258703-11cb1400-286d-11eb-827c-52e4947adc88.png">

Or differently said, using storybook and v1 the theme doesn't work anymore. (I didn't try without storybook.)

See also https://github.com/chakra-ui/chakra-ui/issues/2488#issuecomment-727179727, seems to be the same problem.

**Comment by kelvinmaues** [comment]
Facing the same issue.

**Comment by kelvinmaues** [comment]
Maybe this [PR](https://github.com/chakra-ui/chakra-ui/pull/2514) could fix this issue

**Comment by TimKolberger** [comment]
The PR updates just some links in our documentation. This won't fix anything regarding this issue.

I think the root of this issue with storybook is, that there are multiple versions of emotion present, which breaks the functionality of chakra.

I have not looked into the issue, it's just my best guess.

**Comment by lee-reinhardt** [comment]
I was able to work around this in my project by:
- using Storybook v6.1.0-rc.2
- implementing the `webpackFinal` config that Chakra uses in my own (see: https://github.com/chakra-ui/chakra-ui/blob/develop/.storybook/main.js#L11)
- remove `node_moduels` and `yarn.lock`

Making the above three changes got my Storybook styles working again. I'm not sure if the Storybook rc version actually makes a difference; I didn't test downgrading to 6.0.x.

**Comment by ljosberinn** [comment]
maybe the [chakra storybook setup](https://github.com/chakra-ui/chakra-ui/tree/develop/.storybook) can help

**Comment by kelvinmaues** [comment]
The tips worked guys. Thanks a lot!

**Comment by hutber** [comment]
@kelvinmaues would u share the working package.json and maybe even the main/preview.js please pal?

**Comment by kelvinmaues** [comment]
Sure @hutber.

 **package.json**
```json
{
  "name": "samui",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@chakra-ui/react": "^1.0.0",
    "@emotion/react": "^11.0.0",
    "@emotion/styled": "^11.0.0",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@types/jest": "^24.0.0",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "framer-motion": "^2.9.4",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "react-scripts": "3.4.4",
    "typescript": "^3.8.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "contributors:add": "all-contributors add",
    "contributors:generate": "all-contributors generate",
    "storybook": "start-storybook -p 6006 -s public --no-dll",
    "build-storybook": "build-storybook -s public --no-dll"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/core": "^7.12.3",
    "@storybook/addon-actions": "^6.1.0-rc.3",
    "@storybook/addon-essentials": "^6.1.0-rc.3",
    "@storybook/addon-links": "^6.1.0-rc.3",
    "@storybook/node-logger": "^6.1.0-rc.3",
    "@storybook/preset-create-react-app": "^3.1.5",
    "@storybook/react": "^6.1.0-rc.3",
    "all-contributors-cli": "^6.19.0",
    "babel-loader": "^8.1.0",
    "react-is": "^17.0.1"
  }
}
```

`.storybook/main.js`

```javascript
const path = require("path");
const toPath = (_path) => path.join(process.cwd(), _path);

module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/preset-create-react-app",
  ],
  webpackFinal: async (config) => {
    return {
      ...config,
      resolve: {
        ...config.resolve,
        alias: {
          ...config.resolve.alias,
          "@emotion/core": toPath("node_modules/@emotion/react"),
          "emotion-theming": toPath("node_modules/@emotion/react"),
        },
      },
    };
  },
};

```

The `preview.js` file it is the same wrapping the `ChakraProvider` in the **decorator**.

**Comment by hutber** [comment]
Thanks very much, I got there in the end, for me it was that I wasn't patient enough to let the yarn finish properly :P
Glad we got a temporary fix

**Comment by beforan** [comment]
Just a quick note for anyone using yarn2 in pnp mode; you can't alias the emotion packages to `node_modules` because pnp doesn't use `node_modules`.

Instead just the package name worked for me:

```js
// main.js ...
alias: {
          ...config.resolve.alias,
          "@emotion/core": "@emotion/react",
          "emotion-theming": "@emotion/react",
        },
// ...
```

**Comment by mattpetters** [comment]
> Sure @hutber.
> 
> **package.json**
> 
> ```json
> {
>   "name": "samui",
>   "version": "0.1.0",
>   "private": true,
>   "dependencies": {
>     "@chakra-ui/react": "^1.0.0",
>     "@emotion/react": "^11.0.0",
>     "@emotion/styled": "^11.0.0",
>     "@testing-library/jest-dom": "^4.2.4",
>     "@testing-library/react": "^9.3.2",
>     "@testing-library/user-event": "^7.1.2",
>     "@types/jest": "^24.0.0",
>     "@types/node": "^12.0.0",
>     "@types/react": "^16.9.0",
>     "@types/react-dom": "^16.9.0",
>     "framer-motion": "^2.9.4",
>     "react": "^17.0.0",
>     "react-dom": "^17.0.0",
>     "react-scripts": "3.4.4",
>     "typescript": "^3.8.3"
>   },
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test",
>     "eject": "react-scripts eject",
>     "contributors:add": "all-contributors add",
>     "contributors:generate": "all-contributors generate",
>     "storybook": "start-storybook -p 6006 -s public --no-dll",
>     "build-storybook": "build-storybook -s public --no-dll"
>   },
>   "eslintConfig": {
>     "extends": "react-app"
>   },
>   "browserslist": {
>     "production": [
>       ">0.2%",
>       "not dead",
>       "not op_mini all"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   },
>   "devDependencies": {
>     "@babel/core": "^7.12.3",
>     "@storybook/addon-actions": "^6.1.0-rc.3",
>     "@storybook/addon-essentials": "^6.1.0-rc.3",
>     "@storybook/addon-links": "^6.1.0-rc.3",
>     "@storybook/node-logger": "^6.1.0-rc.3",
>     "@storybook/preset-create-react-app": "^3.1.5",
>     "@storybook/react": "^6.1.0-rc.3",
>     "all-contributors-cli": "^6.19.0",
>     "babel-loader": "^8.1.0",
>     "react-is": "^17.0.1"
>   }
> }
> ```
> 
> `.storybook/main.js`
> 
> ```js
> const path = require("path");
> const toPath = (_path) => path.join(process.cwd(), _path);
> 
> module.exports = {
>   stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
>   addons: [
>     "@storybook/addon-links",
>     "@storybook/addon-essentials",
>     "@storybook/preset-create-react-app",
>   ],
>   webpackFinal: async (config) => {
>     return {
>       ...config,
>       resolve: {
>         ...config.resolve,
>         alias: {
>           ...config.resolve.alias,
>           "@emotion/core": toPath("node_modules/@emotion/react"),
>           "emotion-theming": toPath("node_modules/@emotion/react"),
>         },
>       },
>     };
>   },
> };
> ```
> 
> The `preview.js` file it is the same wrapping the `ChakraProvider` in the **decorator**.

Kudos to you sir! This saved my project after hours of troubleshooting

**Comment by shilman** [comment]
Is anybody from the Chakra team interested in building an addon for Storybook? It would mean that users could use Chakra in storybook with one line of configuration, rather than copying over the Chakra configuration.

We're doing a big push on addons in 2021 and we'd be happy to promote the addon (and Chakra) as part of that. Kick-off post: https://storybook.js.org/blog/addon-catalog-sneak-peak/

**Comment by with-heart** [comment]
@shilman Very cool! I'd absolutely be interested in that. What's the best way to connect with you or the Storybook team to figure out first steps?

**Comment by shilman** [comment]
@with-heart Storybook has a discord where we do most of our chats and there's an `#addons` channel where we could discuss this in realtime. https://discord.gg/UUt2PJb

There's also documentation about writing a preset (the part of the addon that handles configuration) here: https://storybook.js.org/docs/react/api/writing-presets (tho we're in the process of updating it cc @winkervsbecks @jonniebigodes)

**Comment by with-heart** [comment]
@shilman Thanks for the info! I'll reach out on Discord at some point because I think this would be great to offer.

PS: Thanks for the sustained effort you've put into Storybook. You've turned an awesome tool into an even better platform!

**Comment by segunadebayo** [comment]
Given that we have a walkaround for this, I'd close this and leave #2694 open

**Comment by Zyclotrop-j** [comment]
This is still an issue.
While the workaround might work for some cases, I couldn't find a way to make it work with our internal mono-repo. (I suspect it's either because we're on the latest stable storybook and/or because the package-resolution with hoisting is much more involved and doesn't quite work. Anyways, after many hours of debugging we've decided to wait for this issue being fixed instead of pouring more time into it trying to work around it - and thus staying on the chakra rc-version for the time being.)
Therefore I'd pledge to re-open and only close once it's fixed for good.

**Comment by with-heart** [comment]
I'd agree that we should re-open if there was some action for Chakra to take, but unfortunately it's an upstream conflict between `@emotion` and the version Storybook uses internally which is tracked on their GH. Looks like @shilman picked up https://github.com/storybookjs/storybook/issues/13114 yesterday, so I'd follow along in that issue.

**Comment by cloud-walker** [comment]
Yeah, IMHO the #2694 is not the real solution to this, they just need to upgrade their emotion version (the storybook addon would be cool anyway!)

**Comment by riceboyler** [comment]
Just as a note, the link for the Chakra Storybook main.js is broken above. This one should work: https://github.com/chakra-ui/chakra-ui/blob/main/.storybook/main.js

**Comment by kidtango** [comment]
Been fighting with this issue all day! 

I'm using this config and it works beautifully with Chakra V1.3 + next.js 10:
const path = require('path');

const toPath = (_path) => path.join(process.cwd(), _path);

module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    'storybook-addon-performance/register',
    '@storybook/addon-a11y',
    '@storybook/addon-toolbars',
  ],
  typescript: {
    reactDocgen: false,
  },
  webpackFinal: async (config) => {
    return {
      ...config,
      resolve: {
        ...config.resolve,
        alias: {
          ...config.resolve.alias,
          '@emotion/core': toPath('node_modules/@emotion/react'),
          'emotion-theming': toPath('node_modules/@emotion/react'),
        },
      },
    };
  },
};

**Comment by ilumin** [comment]
> Been fighting with this issue all day!
> 
> I'm using this config and it works beautifully with Chakra V1.3 + next.js 10:
> const path = require('path');
> 
> const toPath = (_path) => path.join(process.cwd(), _path);
> 
> module.exports = {
> stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
> addons: [
> '@storybook/addon-links',
> '@storybook/addon-essentials',
> 'storybook-addon-performance/register',
> '@storybook/addon-a11y',
> '@storybook/addon-toolbars',
> ],
> typescript: {
> reactDocgen: false,
> },
> webpackFinal: async (config) => {
> return {
> ...config,
> resolve: {
> ...config.resolve,
> alias: {
> ...config.resolve.alias,
> '@emotion/core': toPath('node_modules/@emotion/react'),
> 'emotion-theming': toPath('node_modules/@emotion/react'),
> },
> },
> };
> },
> };

@kidtango, thanks for your solution

**Comment by nilscam** [comment]
Hi

I'm experiencing the same issue. I tried all the solutions listed in this thread but none of them worked.
Could this possibly be due to yesterday's release?

thx.

**Comment by luskafaria** [comment]
> Sure @hutber.
> 
> **package.json**
> 
> ```json
> {
>   "name": "samui",
>   "version": "0.1.0",
>   "private": true,
>   "dependencies": {
>     "@chakra-ui/react": "^1.0.0",
>     "@emotion/react": "^11.0.0",
>     "@emotion/styled": "^11.0.0",
>     "@testing-library/jest-dom": "^4.2.4",
>     "@testing-library/react": "^9.3.2",
>     "@testing-library/user-event": "^7.1.2",
>     "@types/jest": "^24.0.0",
>     "@types/node": "^12.0.0",
>     "@types/react": "^16.9.0",
>     "@types/react-dom": "^16.9.0",
>     "framer-motion": "^2.9.4",
>     "react": "^17.0.0",
>     "react-dom": "^17.0.0",
>     "react-scripts": "3.4.4",
>     "typescript": "^3.8.3"
>   },
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test",
>     "eject": "react-scripts eject",
>     "contributors:add": "all-contributors add",
>     "contributors:generate": "all-contributors generate",
>     "storybook": "start-storybook -p 6006 -s public --no-dll",
>     "build-storybook": "build-storybook -s public --no-dll"
>   },
>   "eslintConfig": {
>     "extends": "react-app"
>   },
>   "browserslist": {
>     "production": [
>       ">0.2%",
>       "not dead",
>       "not op_mini all"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   },
>   "devDependencies": {
>     "@babel/core": "^7.12.3",
>     "@storybook/addon-actions": "^6.1.0-rc.3",
>     "@storybook/addon-essentials": "^6.1.0-rc.3",
>     "@storybook/addon-links": "^6.1.0-rc.3",
>     "@storybook/node-logger": "^6.1.0-rc.3",
>     "@storybook/preset-create-react-app": "^3.1.5",
>     "@storybook/react": "^6.1.0-rc.3",
>     "all-contributors-cli": "^6.19.0",
>     "babel-loader": "^8.1.0",
>     "react-is": "^17.0.1"
>   }
> }
> ```
> 
> `.storybook/main.js`
> 
> ```js
> const path = require("path");
> const toPath = (_path) => path.join(process.cwd(), _path);
> 
> module.exports = {
>   stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
>   addons: [
>     "@storybook/addon-links",
>     "@storybook/addon-essentials",
>     "@storybook/preset-create-react-app",
>   ],
>   webpackFinal: async (config) => {
>     return {
>       ...config,
>       resolve: {
>         ...config.resolve,
>         alias: {
>           ...config.resolve.alias,
>           "@emotion/core": toPath("node_modules/@emotion/react"),
>           "emotion-theming": toPath("node_modules/@emotion/react"),
>         },
>       },
>     };
>   },
> };
> ```
> 
> The `preview.js` file it is the same wrapping the `ChakraProvider` in the **decorator**.

Holy mother of Jesus, thank you so much!
Rly man, THANK YOU!

**Comment by ryanerringtonatom** [comment]
Would anyone know how to get this working in the context of a monorepo where `node_modules` is 3 directories below the `.storybook` config?

The following doesn't work...

```
"@emotion/core": toPath("../../../node_modules/@emotion/react"),
"emotion-theming": toPath("../../../node_modules/@emotion/react"),
```

**Comment by brvnonascimento** [comment]
> Would anyone know how to get this working in the context of a monorepo where `node_modules` is 3 directories below the `.storybook` config?
> 
> The following doesn't work...
> 
> ```
> "@emotion/core": toPath("../../../node_modules/@emotion/react"),
> "emotion-theming": toPath("../../../node_modules/@emotion/react"),
> ```

Same here, ryanerringtonatom, I tried:

```javascript
 require.resolve('@emotion/react') 
```

Although the build passes, the styles are still not applied.

**Comment by ryanerringtonatom** [comment]
@brvnonascimento the solution we chose was moving the `.storybook` config folder to the root of the monorepo (in the same directory as the root `node_modules`) and then pointed the stories config to the relevant package as below. Hope this helps. 

```
stories: [
  "../packages/shared/src/**/*.stories.mdx",
  "../packages/shared/src/**/*.stories.@(js|jsx|ts|tsx)"
],
```

**Comment by brvnonascimento** [comment]
Managed to solve the problem!


```typescript
// .storybook/main.js

const path = require('path');

const emotionAlias = require.resolve('@emotion/react');

module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials'],
  webpackFinal: async (config) => {
    return {
      ...config,
      resolve: {
        ...config.resolve,
        alias: {
          ...config.resolve.alias,
          '@emotion/core': emotionAlias,
          'emotion-theming': emotionAlias
        }
      }
    };
  }
};
```

I'm using Yarn so I added the following Resolutions to my root "package.json" :

```json
{
  "resolutions": {
    "**/@emotion/core": "^11.0.0",
    "**/@emotion/react": "^11.4.0",
    "**/@emotion/styled": "^11.3.0"
  }
}
```

**Comment by Cretezy** [comment]
Here is the solution that worked for me:

```js
module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: ["@storybook/addon-links", "@storybook/addon-essentials"],
  webpackFinal: async (config) => {
    return {
      ...config,
      resolve: {
        ...config.resolve,
        alias: {
          ...config.resolve.alias,
          "@emotion/core": "@emotion/react",
          "emotion-theming": "@emotion/react",
        },
      },
    };
  },
};
```

**Comment by adamklepacz** [comment]
I'm having the same issue. Our storybook can not load the font's properly:

Here is my 
main.js
```
const path = require("path");
const toPath = (_path) => path.join(process.cwd(), _path);

module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-actions',
    'storybook-css-modules-preset',
    '@storybook/preset-scss',
    'storybook-css-modules-preset',
  ],
  webpackFinal: async (config) => {
    return {
      ...config,
      resolve: {
        ...config.resolve,
        alias: {
          ...config.resolve.alias,
          "@emotion/core": toPath("node_modules/@emotion/react"),
          "emotion-theming": toPath("node_modules/@emotion/react"),
          "assets": path.resolve(__dirname, '../src/assets'),
          'assets': path.resolve(__dirname, '../src/assets'),
          'locales': path.resolve(__dirname, '../src/locales'),
          'pages': path.resolve(__dirname, '../src/pages'),
          'utils': path.resolve(__dirname, '../src/utils'),
          'styles': path.resolve(__dirname, '../src/styles'),
          'theme': path.resolve(__dirname, '../src/theme'),
          'stores': path.resolve(__dirname, '../src/stores'),
        },
      },
    };
  },
};
```
But as you can see on the screenshot down below, the font is not included...
![Zrzut ekranu 2021-34-07 o 14 34 40](https://user-images.githubusercontent.com/27632432/121017417-8af46f00-c79d-11eb-9ab9-3035a738d256.jpg)

And the preview file is properly wrapped with ChakraProvider like so:

```
import React from 'react';
import { ChakraProvider } from '@chakra-ui/react';

import chakraTheme from '../src/theme/theme';

export const decorators = [
  (Story) => (
    <ChakraProvider resetCSS theme={chakraTheme()}>
      <Story />
    </ChakraProvider>
  ),
];

export const parameters = {
  actions: {
    argTypesRegex: '^on[A-Z].*',
  },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
};
```

Any ideas how to fix it?

**Comment by with-heart** [comment]
@adamklepacz What does `chakraTheme` look like?

**Comment by rrsai** [comment]
After much debugging of the clash between versions of emotion used in storybook and in app, and for those who come after me, I found that storybook has now provided a feature flag to avoid clashing with later versions of emotion: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#emotion11-quasi-compatibility

**Comment by nappalm** [comment]
Fix font issue by adding .storybook/preview-head.html file.
and inside it, add the sources

```
.storybook/preview-head.html

<link
  href="https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,100;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
  rel="stylesheet"
/>

```
