### ISSUE TITLE
Styled Component Not Working with Chakra UI v1.0 Components

### ISSUE THREAD

**Issue by zakasalaheddine** [chakra-ui/chakra-ui#2528]
# Bug report

## Describe the bug

I've tried using Styled with Box or any other chakra UI components and it always producing an eslint Error

(I'm using Typescript with NextJS)

## To reproduce

Just set up a new NextJS application with Chakra UI and Typescript and try to use Styled with any Component from Chakra

**Comment by with-heart** [comment]
What's the error?

**Comment by ljosberinn** [comment]
ESLint has nothing to do with Chakra and I'm not aware of any rule that makes sense that could prevent using it.

**Comment by zakasalaheddine** [comment]
Yes, sorry I restart my editor and all the errors produced was gone, Thank you guys for your comments !!
