### ISSUE TITLE
create-react-app template: Invalid tag name "^1.0.0@next"

### ISSUE THREAD

**Issue by merganon** [chakra-ui/chakra-ui#2533]
![Screenshot 2020-11-17 00_15_05](https://user-images.githubusercontent.com/74573436/99321477-2eb41700-286e-11eb-8fde-5218e4607314.jpg)

When creating a react app with the `npx create-react-app my-app --template @chakra-ui` command, this error is thrown.
Seems like "@next" needs to be removed.

## System information
- OS: Windows 10
- Version of Node.js: v12.16.2

**Comment by segunadebayo** [comment]
Pushed a fix for this! Thanks for catching it.
