### ISSUE TITLE
Collapse component: in property is not working when setting it initially to true

### ISSUE THREAD

**Issue by javierriveros** [chakra-ui/chakra-ui#2534]
# Bug report

## Describe the bug

The Collapse component isn't open when specifying it.

## To reproduce

Create a way of opening and closing the collapse with the initial state set as open. I'm using the `useDisclosure` hook.
```javascript
const { isOpen, onToggle } = useDisclosure({ defaultIsOpen: true });
```
Create a button for opening and closing the collapse:
```javascript
<Button onClick={onToggle} size={"sm"}>
    {isOpen ? "Hide" : "Show"} collapse
</Button>
```
Create a `Collapse` component and use the previous state you created.
```javascript
<Collapse in={isOpen} animateOpacity>
...
</Collapse>
```
Go to the browser, there you can see that the collapse isn't open by default. Once you click the button, the collapse will open and close very fast, then when you click the button for the 2nd time the collapse will work as expected.

## Minimal reproduction

I created a repository with a minimal reproduction of the issue: https://github.com/javierriveros/chakra-collapse-issue

## Expected behavior

Collapse should be open by default when I specify it using the state variable.

## System information

- Version of @chakra-ui/react: 1.0.0

- Version of React: 17.0.1

## Additional context

This was not a problem with the release candidate 1.0.0-rc8

**Comment by tn12787** [comment]
Can confirm - I'm having this issue too.

**Comment by tn12787** [comment]
[Minimal CodeSandbox repro](https://codesandbox.io/s/stoic-goldstine-odmwz?file=/src/index.tsx)

**Comment by harshzalavadiya** [comment]
Temporary using `unmountOnExit={true}` will make it work as expected

**Comment by harshzalavadiya** [comment]
After looking at code looks like error is coming from `getInitialHidden()` since it returns `false` if it's open
also there's no `aria-hidden` in entire component file so looks like comment above that line like is ambiguous

```diff
diff --git a/packages/transition/src/collapse.tsx b/packages/transition/src/collapse.tsx
index 93db3859..c2cb44f7 100644
--- a/packages/transition/src/collapse.tsx
+++ b/packages/transition/src/collapse.tsx
@@ -89,7 +89,7 @@ export const Collapse = React.forwardRef<HTMLDivElement, CollapseProps>(
 
     const getInitialHidden = () => {
       // If it is open by default, no need to apply `aria-hidden`
-      if (isOpen) return false
+      if (!isOpen) return false
       // If startingHeight > 0, then content is partially visible
       if (hasHeightValue(startingHeight)) return false
       // Else, the content is hidden
```

**Comment by javierriveros** [comment]
Thank you @harshzalavadiya, it works when adding that prop.

**Comment by lunaticcoding** [comment]
@segunadebayo Took me quite a while to find this here :) the documentation on the website right [here](https://v0.chakra-ui.com/collapse) still calls the `in` argument `isOpen`. :) Maybe you could update it.

**Comment by fabidi** [comment]
> @segunadebayo Took me quite a while to find this here :) the documentation on the website right [here](https://v0.chakra-ui.com/collapse) still calls the `in` argument `isOpen`. :) Maybe you could update it.

I don't understand why my code does not have the isOpen property. I only have "in", but it does not animate like in the examples using isOpen. Did you find any answer?
