### ISSUE TITLE
Add ability to customise Icon styles in theme

### ISSUE THREAD

**Issue by ChasinHues** [chakra-ui/chakra-ui#2535]
# Feature request

## Is your feature request related to a problem? Please describe.

At the moment you can not customise the styles of the Icon component in the theme, as documented here: https://chakra-ui.com/docs/theming/advanced#single-part-component

## Describe the solution you'd like

The ability to customise the Icon component, as documented here: https://chakra-ui.com/docs/theming/advanced#single-part-component

## Describe alternatives you've considered

We're currently creating our own custom Icon component that returns the Chakra Icon component with the style overrides we want applied. This is fine, but a more ideal solution would be simply customising the components styles in the theme, reducing the need for our own custom component.

**Comment by segunadebayo** [comment]
This is a bit tricky, to be honest as lots of other components rely on the Icon component.

Create a theme and setting default values for the icon should be moved user-land for now, till we're able to unify icon sizes across components.

This isn't a priority for now, though. Feel free to share your approach as well so others can learn from it.

Thanks buddy.
