### ISSUE TITLE
Wrapping motion component with chakra is removing transition prop

### ISSUE THREAD

**Issue by oahmaro** [chakra-ui/chakra-ui#2538]
# Bug report

## Describe the bug
When wrapping motion component inside chakra factory component, i lose access to transition prop.

## To reproduce
`const MotionBox = chakra(motion.div)`
this will create a div that holds chakra props and framer motion props, except that the transition prop coming from framer-motion is not available

## Expected behavior
I expect to have access to transition attribute, specially in cased where framer-motion is providing animation, such as using AnimateSharedLayout where i am only required to provide layoutId and framer-motion will handle mount and unmount animation on my component.

## System information
- Version of @chakra-ui/react: v1.0.0

**Comment by segunadebayo** [comment]
Hi @oahmaro,

Thanks for catching this. We'll look into it. Can you try this instead:

```jsx
const MotionBox = motion.custom(chakra.div)
```

**Comment by oahmaro** [comment]
> Hi @oahmaro,
> 
> Thanks for catching this. We'll look into it. Can you try this instead:
> 
> ```js-jsx
> const MotionBox = motion.custom(chakra.div)
> ```

Yes this works, but then type script complains about props related to motion component, and i am getting errors like this: Warning: Received `false` for a non-boolean attribute `initial`.

**Comment by Espoirr** [comment]
Hi @oahmaro 

I was also facing a similar issue, but after having a discussion with one of the chakra team members we were able to come to the following workaround.

```
import { motion } from 'framer-motion'
import { forwardRef } from '@chakra-ui/core

const MotionBox = motion.custom(forwardRef(({ layoutId, ...rest }, ref) => <chakra.div ref={ref} {...rest} />))
``` 
This solved it for me. You can separate the props you are using in order to avoid the prop warning, here I was using it for AnimateSharedLayout so I took out layoutId.

Pls, let me know if u have found any other alternatives.

Thanks, Hope I helped.

**Comment by oahmaro** [comment]
Hi @Espoirr 
Actually this did remove the errors i am getting on my console, but presented me with new type errors on my code editor,

<img width="540" alt="Screen Shot 2020-11-20 at 7 51 09" src="https://user-images.githubusercontent.com/15835932/99764186-2de8e280-2b05-11eb-930f-a8bfeecd5e8a.png">

<img width="540" alt="Screen Shot 2020-11-20 at 7 50 05" src="https://user-images.githubusercontent.com/15835932/99764126-0f82e700-2b05-11eb-932d-33d5c384f6f7.png">

**Comment by TimKolberger** [comment]
You have to provide types for the forwardRef component. Please see: https://codesandbox.io/s/chakra-ui-motion-box-sbk9e?file=/src/App.tsx

**Comment by oahmaro** [comment]
Thank you @TimKolberger , i am new to Typescript and getting the syntax right is sometimes challenging for me

**Comment by wobsoriano** [comment]
> Hi @oahmaro,
> 
> Thanks for catching this. We'll look into it. Can you try this instead:
> 
> ```js-jsx
> const MotionBox = motion.custom(chakra.div)
> ```

I am using the `Img` component in Next and still getting the warning

```javascript
import { motion } from "framer-motion";

const MotionImg = motion.custom(chakra.img);
```

**Comment by with-heart** [comment]
@wobsoriano Here's a codesandbox for `motion` + `chakra.img`: https://codesandbox.io/s/elastic-morning-q5e4e?file=/src/App.tsx

**Comment by wobsoriano** [comment]
> @wobsoriano Here's a codesandbox for `motion` + `chakra.img`: https://codesandbox.io/s/elastic-morning-q5e4e?file=/src/App.tsx

Thanks!

**Comment by karesztrk** [comment]
@with-heart Should it be better now? I still see the framer props on the DOM element.

**Comment by FerasAloudah** [comment]
> @with-heart Should it be better now? I still see the framer props on the DOM element.

Same here.

**Comment by TimKolberger** [comment]
There are two ways to compose a component which accepts motion and chakra props.

## use `chakra()` factory

```tsx
const MotionBox = chakra(motion.div)
```

The drawback is, that the prop `transition` is consumed by the chakra styled system and not passed to the motion component. If you don't  need to use this prop, you are good to go with this solution.

### props flow 

1. Use the MotionBox 
   ```tsx
   <MotionBox 
     px="8"
     mt="4"
     animate={{
       scale: [1, 2, 2, 1, 1],
     }}
     transition={{
       duration: 2,
       ease: "easeInOut",
     }} 
   />
    ```
2. chakra extracts all style props (`px`,`mt` and `transition`...), creates a className and passes className on in addition to any non chakra style props
    ```tsx
    <motion.div className="xyz" animate={{ scale: [1, 2, 2, 1, 1] }}/>
    ```
    `animate` **is not a chakra style prop** so it will be passed on.
    `transition` **is a chakra style prop** so it won't be passed to the motion component -> bad if you need it

## use `motion.custom`

```tsx
const MotionBox = motion.custom(chakra.div)
```

This implementation passes every internal motion prop to the passed component. In our case `chakra.div`.
This API is provided by _framer-motion_, not _chakra-ui_. We cannot fix anything there, because the [implementation lives in the framer-motion source code](https://github.com/framer/motion/blob/3c4a25fe6220540a60e42e648208670a670dc81b/src/render/dom/index.ts#L72).
And I think this behaviour is intended to be able to reuse the motion props in the custom component - most of the times you won't need it, but someone somewhere will.

We are on our own and need to filter every motion prop to prevent passing it to the DOM element. _framer-motion_ exposes a function called `isValidMotionProp` which we can use to filter the mix of motion and chakra props.

```tsx
import {
  forwardRef,
  ChakraProps,
  chakra,
} from "@chakra-ui/react";
import {
  motion,
  MotionProps,
  isValidMotionProp
} from "framer-motion";

const MotionBox = motion.custom(
  forwardRef<MotionProps & ChakraProps, "div">(
    (props, ref) => {
      const chakraProps = Object.fromEntries(
        Object.entries(props).filter(
          ([key]) => !isValidMotionProp(key)
        )
      );

      return <chakra.div ref={ref} {...chakraProps} />;
    }
  )
);
```

**Comment by karesztrk** [comment]
Hi @TimKolberger. So do i get it right that `chakra()` factory method is the preferred way if i want to omit the props from the DOM?

**Comment by TimKolberger** [comment]
If you do not need the transition prop of framer-motion use the chakra factory.

If you need the transition prop, use motion.custom.

**Comment by wvieed** [comment]
I'm can't long

**Comment by ssijak** [comment]
@TimKolberger With option 2 if I use `MotionBox`, my TypeScript compiler is complaining at use sites that `MotionBox` does not have `children` property.

**Comment by TimKolberger** [comment]
Please see this updated example from the [linked codesanbox](https://codesandbox.io/s/chakra-ui-motion-box-sbk9e?file=/src/App.tsx) in the [chakra ui docs](https://chakra-ui.com/guides/integrations/with-framer): 

```tsx
import * as React from "react";
import {
  forwardRef,
  ChakraProps,
  chakra,
  ComponentWithAs
} from "@chakra-ui/react";
import {
  motion,
  MotionProps,
  isValidMotionProp
} from "framer-motion";

export type MotionBoxProps = Omit<
  ChakraProps,
  keyof MotionProps
> &
  MotionProps & {
    as?: React.ElementType;
  };

export const MotionBox = motion.custom(
  forwardRef<MotionBoxProps, "div">((props, ref) => {
    const chakraProps = Object.fromEntries(
      // do not pass framer props to DOM element
      Object.entries(props).filter(
        ([key]) => !isValidMotionProp(key)
      )
    );
    return <chakra.div ref={ref} {...chakraProps} />;
  })
) as ComponentWithAs<"div", MotionBoxProps>;
```

**Comment by RIP21** [comment]
@TimKolberger any ideas on how to properly make a factory function that will build MotionWhatever out of other Chakra components?

```typescript
export type GenericMotionProps<Props> = Omit<Props, keyof MotionProps> &
  MotionProps & {
    as?: React.ElementType
  }

function generateMotion<Props extends object, T extends React.ElementType<Props>>(
  Component: string | React.ComponentClass<Props, any> | React.FunctionComponent<Props>
) {
  const Wrapped = motion.custom(
    forwardRef<Props, T>((props, ref) => {
      const chakraProps = Object.fromEntries(
        // do not pass framer props to DOM element
        Object.entries(props).filter(([key]) => !isValidMotionProp(key)),
      )
      // @ts-ignore
      return <Component ref={ref} {...chakraProps} />
    }),
  ) as ComponentWithAs<T, GenericMotionProps<Props>>
  Wrapped.displayName = `Motion${Component.displayName}`
  return Wrapped
}

const MotionFlex = generateMotion<FlexProps, 'div'>(Flex)
```

The goal is to build Chakra primitives that will be possible to reuse like `<MotionFlex as='header' />` or `<MotionStack spacing={4} />` etc. So, to have Chakra UI components but also powered by a framer-motion.

Or maybe I'm missing something?
Had to ignore on Component as it argues about `ref`, but unsure how to fix that.

**Comment by TimKolberger** [comment]
@RIP21 This looks interesting, but I could not make it work in a reasonable timebox.

On one hand a "super component to rule them all" would be awesome, but on the other hand you are left with a component definition which is so complicated I would not understand half an hour later.

As a workaround I would suggest the latest implementation of `MotionBox` in https://github.com/chakra-ui/chakra-ui/issues/2538#issuecomment-774283111 where it is possible to pass the `as` prop:

 ```jsx
<MotionBox as={Stack} />
 ```

I am sure that there are valid use-cases where a DOM element needs to be a `Stack` and a `header` and is animated with framer-motion, but I would just fallback to 

```jsx
<MotionBox as="header">
  <Stack>...</Stack>
</MotionBox>
```

to keep is simple.

If you find a solution, feel free to tag me 🙂

**Comment by RIP21** [comment]
@TimKolberger implementation above is actually working :) See Sandbox link above (at the very end of the https://github.com/chakra-ui/chakra-ui/issues/2538#issuecomment-776066074)
The only issue is with // @ts-ignore which is not that important as externally, when you use the generated component, it auto-suggests everything nicely, meaning typings are correctly passing down. 

In the Codesandbox above I have generated MotionStack that has `as="header"` and it indeed got populated correctly, while Stack functionality is still preserved :) 

So I guess it works? :)

**Comment by TimKolberger** [comment]
Yes, thats great! I referred to a solution without `@ts-ignore`. But if it works, it works. :tada:

**Comment by raphtlw** [comment]
What can be implemented to fix this issue is to provide an optional prop that accepts an object which are the props passed directly to the component passed to the `as` prop. For instance, in this case, we have a `<Stack as={motion.div} />`. We can't use `transition=` directly, but with this fix we should be able to pass something like `forwardProps=` to the element and it should automatically forward them to the inner div.

Ideal API:
```tsx
<Stack as={motion.div} forwardProps={{ transition: ... }} />
```
