### ISSUE TITLE
[NumberInput] Cannot use numeric keypad

### ISSUE THREAD

**Issue by pan-tom** [chakra-ui/chakra-ui#254]
NumberInput accepts only key codes from standard keyboards, which are from 48 to 57. Numeric keypads have different keycodes. They are from 96 to 105.

**Comment by pan-tom** [comment]
To fix this, isNumberKey function from [https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/useNumberInput/utils.js](url) should be changed:

```javascript
export function isNumberKey(event) {
  const charCode = event.which ? event.which : event.keyCode;
  if (event.key === ".") return true;
  if (charCode > 31 && (charCode < 48 || charCode > 57) &&
    (charCode < 96 || charCode > 105) && charCode !== 110) return false;
  return true;
}
```

**Comment by segunadebayo** [comment]
Hi @pan-tom, thanks for catching this issue.

I'll look into it soon. If you have some time to look into it and update the keyCodes to cover numeric keypads, I'll gladly merge your PR.

Thanks

**Comment by pan-tom** [comment]
Hi @segunadebayo,
thank you, I created PR.

**Comment by segunadebayo** [comment]
Thanks for the PR @pan-tom
