### ISSUE TITLE
Heading component does not work properly

### ISSUE THREAD

**Issue by tumdav** [chakra-ui/chakra-ui#2542]
# Bug report

## Describe the bug
Please see the attached screenshots, chakra rendered heading component actual height is not setting properly, and the part of heading text is cut.

## Minimal reproduction

unfortunately,  I can't create a `codesandbox` example, as I could not find the chakra's new package there.

#### Chakra implementation
```js
import React from 'react';
import { Heading } from '@chakra-ui/react';

const TestPage = () => (
    <>
        <Heading fontSize="9xl">
            Hello world
        </Heading>
    </>
);

export default TestPage;
```
![image](https://user-images.githubusercontent.com/10452309/99396715-85b3fd80-28fb-11eb-8b71-7444bddbf882.png)

#### Html implementation
```js
import React from 'react';
import { Heading } from '@chakra-ui/react';

const TestPage = () => (
    <>
        <h2 style={{fontSize:"8rem"}}>
            Hello world
        </h2>
    </>
);

export default TestPage;
```

![image](https://user-images.githubusercontent.com/10452309/99396747-8f3d6580-28fb-11eb-8eb3-da627645f8d7.png)
## System information

- OS: macOS
- BrowseLr Safari
- Version of @chakra-ui/react: 1.0.0
- Version of Node.js: 10.22.0

**Comment by segunadebayo** [comment]
Hi @tumdav,

Applying a line-height of `1` or any theme aware value fixes this. The Heading component was designed to be themed with the font-size and line-height.

I've gone ahead to update the heading component theme to use units that are relative to font-size instead. Thanks for catching that.

We'll release an update shortly.
