### ISSUE TITLE
InputRightAddon does not accept variants

### ISSUE THREAD

**Issue by hutber** [chakra-ui/chakra-ui#2543]
I am trying to use a variant with InputRightAddon but it outputs as a html attribute. 

The output theme:
![image](https://user-images.githubusercontent.com/1344898/99409356-2f3dc380-28e9-11eb-9e19-67d42cc8620c.png)

The rendered comp:
![image](https://user-images.githubusercontent.com/1344898/99409389-382e9500-28e9-11eb-8352-1a474f049d8f.png)

Is it possible to use variants on the `InputRightAddon` component?

**Comment by Zyclotrop-j** [comment]
From what I see in the source-code, the `InputRightAddon` is themed (aka has variants) together with the `Input` (or `InputGroup` really) as the "addon"-part like so:
```
<InputGroup variant="squareButton">.....<InputLeftAddon .... />.....
```
+
```
// in your theme
const variants = {
  // make a own varient of the input
  squareButton: {
   // theme the addon in general (targets both InputRIghtAddon and InputLeftAddon)
    addon: {
      bg: background: "#f6ced6",
      fontFamily: "light",
      ...
    },
  // this variant overwrites the input-field (aka input-element) styles as well, 
  // so to get the default outline-variant in your custom varient, you could do:
   field: theme.components.input.variants.outline
  },
}

export default {
  variants,
}

```

If the chakra-ui team is happy with above proposed additional syntax though (own theme-component "InputLeftAddon" and "InputRightAddon" respectivly), which would aggregate and overwrite whatever is defined in input->addon, I'm happy to provide a PR for that 😄
