### ISSUE TITLE
[Avatar] Support "htmlHeight", "htmlWidth" props

### ISSUE THREAD

**Issue by cloud-walker** [chakra-ui/chakra-ui#2544]
# Feature request

## Is your feature request related to a problem? Please describe.

Lighthouse reports fails due to the lack of explicit dimensions sets on Avatar images:

![image](https://user-images.githubusercontent.com/1144075/99408177-3ae0b880-28f0-11eb-9f0a-276d46a6c2ef.png)

**Comment by dominictwlee** [comment]
Happy to look into this.

I think we could infer the width and height img attributes using the dimensions of the span container. Thoughts on this?

**Comment by with-heart** [comment]
> I'm not entirely sure this is as relevant in this context, given the use case of avatars. the span already occupies a certain amount of space on layout (acting as a sort of aspect ratio box), and we always expect to have only 1 image that fills the span's dimensions. I don't believe this will cause any layout shift as the image is downloaded, though correct me if I'm wrong.

I agree with this. I believe Lighthouse is either not looking for or is not correctly detecting that the `span` container of each avatar has a set `width` and `height`, as seen here in the default theme:

https://github.com/chakra-ui/chakra-ui/blob/9a831e0a8d5efc5b94a49544f86eb31d09cfeb9f/packages/theme/src/components/avatar.ts#L45-L77

I'm happy to revisit if this is determined to be a problem
 on our end, but I don't believe that's the case.
