### ISSUE TITLE
docs: how to create your own `MenuItemOption`

### ISSUE THREAD

**Issue by TimKolberger** [chakra-ui/chakra-ui#2545]
# Missing docs report

## Describe the missing docs

Document how to receive the props `onChange`, `isChecked` and `type` in custom Component inside of a `MenuOptionGroup`

https://github.com/chakra-ui/chakra-ui/blob/1fedbc8d788f193e8be3206296a70a8ca7a9362a/packages/menu/src/use-menu.ts#L621-L634

## To reproduce

* select an item -> it is not selected

## Minimal reproduction

https://codesandbox.io/s/chakra-ui-menu-option-group-y4xoi?file=/src/App.tsx

## Expected behavior

* add the line `SomeItem.id = "MenuItemOption";`
* select an item -> it is selected 🎉

**Comment by auto200** [comment]
Bump
