### ISSUE TITLE
The 'add-path' command is disabled

### ISSUE THREAD

**Issue by Jivvon** [chakra-ui/chakra-ui#2547]
# Bug report

## Describe the bug

New error with the github actions pipeline

```shell
Error: Unable to process command '::add-path::/opt/hostedtoolcache/node/12.19.0/x64/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

## To reproduce

1. Try PR
2. Click on the build error detail
3. See error

## Minimal reproduction

example: https://github.com/chakra-ui/chakra-ui/pull/2546/checks?check_run_id=1413300215

## Expected behavior

Build success without error

## Additional context

This may be able to solved by updating [pr.yml](https://github.com/chakra-ui/chakra-ui/blob/develop/.github/workflows/pr.yml)

**Comment by flavio0567** [comment]
Same issue:
Error: Unable to process command '::add-path::/opt/hostedtoolcache/node/12.19.0/x64/bin' successfully.
Error: The `add-path` command is disabled. ...
