### ISSUE TITLE
Add theme styling capability to root Tabs element

### ISSUE THREAD

**Issue by cereallarceny** [chakra-ui/chakra-ui#2548]
# Feature request

## Is your feature request related to a problem? Please describe.

I'm trying to create a variant called "sticky" for my tabs which positions the tabslist to the left and the tabspanel to the right, instead of the default "stacked" layout. In order to do this, I need to add the `display="flex"` prop to all my tabs with this variant. I'd like to be able to define it in the theme variants itself.

By extension of this logic: it would be quite nice to be able to also access the styling of the `<TabPanels>` component, which is also unexposed by the current API.

## Describe the solution you'd like

Here's what I have to do:

```jsx
<Tabs variant="sticky" display="flex">
  <TabList>
    <Tab>Basic Information</Tab>
    <Tab>Change Password</Tab>
    <Tab>Linked Accounts</Tab>
  </TabList>
  <TabPanels>
    <TabPanel>
      <BasicInformation />
    </TabPanel>
    <TabPanel>
      <ChangePassword />
    </TabPanel>
    <TabPanel>
      <LinkedAccounts />
    </TabPanel>
   </TabPanels>
</Tabs>
```

Here's what I'd like to do:

```js
// Somewhere in the theme overrides file...
Tabs: {
  variants: {
    sticky: {
      root: {
        display: 'flex', // Right here instead of as a prop on the component
      },
      tablist: {
        flexDirection: 'column',
      },
    },
  },
},
```

```jsx
<Tabs variant="sticky">
  <TabList>
    <Tab>Basic Information</Tab>
    <Tab>Change Password</Tab>
    <Tab>Linked Accounts</Tab>
  </TabList>
  <TabPanels>
    <TabPanel>
      <BasicInformation />
    </TabPanel>
    <TabPanel>
      <ChangePassword />
    </TabPanel>
    <TabPanel>
      <LinkedAccounts />
    </TabPanel>
   </TabPanels>
</Tabs>
```

## Describe alternatives you've considered

None, I just have to include all the parent props on the actual `<Tabs>` element itself.

## Additional context

None!

**Comment by dodas** [comment]
related: #1187

**Comment by segunadebayo** [comment]
Hi @cereallarceny ,

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
