### ISSUE TITLE
There should be types for components styling in extendTheme

### ISSUE THREAD

**Issue by smitbarmase** [chakra-ui/chakra-ui#2555]
# Feature request

## Is your feature request related to a problem? Please describe.

There should be typescript autocomplete when changing stying in extendTheme.  I was changing the styling of "FormErrorMessage", and it didn't work. Maybe there must be some component inside it like "label" and "addon" don't know.

## Describe the solution you'd like

Maybe a typescript suggestion OR proper documentation of each and every component and their inside abstraction to change their style.

## Describe alternatives you've considered

Nothing yet.

## Additional context

![Screenshot 2020-11-18 033059](https://user-images.githubusercontent.com/37347831/99455913-8629b400-294e-11eb-8bd0-e7ffe8926b8d.png)

**Comment by smitbarmase** [comment]
Found it. You can go here to find **base-style** and other configuration of all the components
https://github.com/chakra-ui/chakra-ui/tree/develop/packages/theme/src/components

**Comment by kfalkiewicz** [comment]
Still, there is an error with no TS help when extending styles. This problem should be addressed.

**Comment by with-heart** [comment]
@kfalkiewicz Definitely agree with you there. We merged #2632 recently which should improve things quite a bit. That should be published in a new version in the next few days.
