### ISSUE TITLE
Add border radius to progress component

### ISSUE THREAD

**Issue by brennanfife** [chakra-ui/chakra-ui#2556]
# Bug report

## Describe the bug
Setting a border radius inside the progress bar only alters the fill. There is no effect on the track component.
 
## To reproduce
Set a border radius on the progress component 

`<Progress borderRadius="1rem" />
`
## Expected behavior
Setting a border radius on the progress component alters both the outer and inner div

## Screenshots
![](https://cdn.discordapp.com/attachments/758645914868514827/778443306274914304/Screen_Shot_2020-11-17_at_8.14.50_PM.png)

## System information
- OS: macOS
- Browser: Chrome
- Version of @chakra-ui/react@1.0.0

**Comment by segunadebayo** [comment]
I just pushed a fix for this. Thanks for catching it.
