### ISSUE TITLE
can't make full screen long menus

### ISSUE THREAD

**Issue by Hargoze** [chakra-ui/chakra-ui#2559]
# Bug report

## Describe the bug

since i migrated to v1, i can no longer make full screen long menus.
my current version of chakra is :"@chakra-ui/core": "^1.0.0-rc.8"

## To reproduce

```  <MenuList w="100%"> ``` worked on 0.8, but not anymore on v1

## Screenshots

V1:
![image](https://user-images.githubusercontent.com/60386882/99504817-57c4cc80-2980-11eb-8d66-bf1e291f3ce1.png)
V0.8:
![image](https://user-images.githubusercontent.com/60386882/99504992-8d69b580-2980-11eb-9cf1-33bd2d0c4d3c.png)

(those screenshots come from your website : https://chakra-ui.com/docs/overlay/menu)

**Comment by ChasinHues** [comment]
@Hargoze I had this issue too. To get around it, I used `w="100vw"` on the `MenuList` instead. 

Example: https://codesandbox.io/s/full-screen-menu-5xi1z

**Comment by Hargoze** [comment]
that seems to work on the sandbox, i will close when that will work on my site, thanks

**Comment by Hargoze** [comment]
that work, thanks !
