### ISSUE TITLE
[StatNumber] vertical align does not apply to block level elements

### ISSUE THREAD

**Issue by xtalx** [chakra-ui/chakra-ui#256]
**Describe the bug**
StatNumber renders a P tag (a block level element) and has css with vertical-align: baseline.

**Additional context**
Not a big deal. I'd submit a PR if I knew which route you wanted to take.

Thanks!

**Comment by segunadebayo** [comment]
Hi @xtalx, do you suggest we remove the `vertical-align: baseline`?

**Comment by xtalx** [comment]
Without other changes, yes, currently it doesn’t do anything. If you wanted it to line up on the baseline you could make the p tag inline or inline-block(I think it’s a flex item though, can’t remember). Probably best/easiest to remove it and leave it to the user to style further if needed.
