### ISSUE TITLE
Image component not always fires `onLoad` callback

### ISSUE THREAD

**Issue by sebqq** [chakra-ui/chakra-ui#2563]
# Bug report

## Describe the bug

So I have this bug when Image component not always fires `onLoad` callback. It becomes pain in situations where I use `Skeleton` as outer container and `isLoaded` depends on image's `onLoad` method. I was wondering if someone else also noticed this kind of bug. Could it be somehow related to  browser's image cache-ing capabilities?

Actually, it is really hard to reproduce and I'm still working on reproducible example. 

Also I was not able to set <Skeleton /> as `fallback` for Image. 

## To reproduce

1. Add image with onLoad
2. Shift + alt + R until it fails to log :D

## Minimal reproduction

Trying to simulate environment right now....

Official Chakra CodeSandbox templates:
- [JavaScript CodeSandbox template](https://codesandbox.io/s/github/chakra-ui/codesandbox-react-js-template/tree/master)
- [TypeScript CodeSandbox template](https://codesandbox.io/s/github/chakra-ui/codesandbox-react-ts-template/tree/master)
-->

## Expected behavior

`onLoad` callback should be called everytime

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of @chakra-ui/react: 1.0.0

**Comment by sebqq** [comment]
This problem is probably relate to Next.js so I will close it.

If anyone encounters same issue there is one hacky solution that can be used:

```ts
const imageRef = useRef<HTMLImageElement>(null);
const [loaded, setLoaded] = useState(false);

useEffect(() => {
  if (!loaded && imageRef.current?.complete) {
    setLoaded(true);
  }
}, []);

return (
  <Image
        ref={imageRef}
        src={src}
        onError={onError}
        onLoad={onLoad}
        {...otherImageProps}
      />
)
```

**Comment by jackiewung** [comment]
was also running into this with nextjs. that workaround works great, thank you @sebqq

**Comment by coreymunn3** [comment]
So happy to have come across this - I have no idea why the onLoad doesn't fire sometimes but this worked perfectly for me. FWIW, the skeleton-over-image approach is too nice to pass up and one of my favorite parts of Chakra.

**Comment by lucksp** [comment]
> So happy to have come across this - I have no idea why the onLoad doesn't fire sometimes but this worked perfectly for me. FWIW, the skeleton-over-image approach is too nice to pass up and one of my favorite parts of Chakra.

same - love the Skeleton `loading` prop wrapper...however, this is STILL an issue!  The `ref` + `useEffect` seems to be an OK solution, but darn it doesn't work without this.
