### ISSUE TITLE
Current state not being used by Chakra Slider with Next-js

### ISSUE THREAD

**Issue by amazingphilippe** [chakra-ui/chakra-ui#2564]
# Bug report

## Describe the bug

Lets say we have two sliders that both control two distinct values in a state object. Whenever a slider is used, values in the state object get reset to their initial values. This issue only applies when using Next-js. 

## To reproduce

1. Go to the broken example below
2. Get to the sliders page by clicking the link
3. Play around with **both** chakra-ui Sliders.
4. Notice that when you change a value, the other value gets reset to its initial state value. 
5. Further down the page is another example with simple html range inputs. 
6. Notice that the issue is not happening there.

## Minimal reproduction

1. [See the working example using CRA ](https://codesandbox.io/s/react-chakra-multi-slider-bqmzd?file=/src/App.js)
2. [See the the broken example using Next-js](https://codesandbox.io/s/react-next-chakra-multi-slider-3bxhp?file=/pages/slider.js)

## Expected behavior

In both examples, when setting state value, I pass the current state object as a mean to override only the value that I want. Otherwise I would completely override the state object with a single value.

When using `onChange`, I would expect to have access to the current state object, and not its initial value. You can check this by logging out the state object when calling `onChange`

Just to illustrate what I mean:
```
onChange={(e) => console.log(e, state)} // state should output the current state object
```

My intuition is that the current state is not being used or passed to the Chakra-ui Slider, but this goes beyond my comprehension of Chakra-ui. It might be something else completely.

## System information

- OS: macOS
- Browser (if applies): Chrome and Firefox
- Version of @chakra-ui/react: 1.0.0-rc.8
- Version of Node.js: 14.15.0

## Additional context

I suspect this same issue might be happening with different components, but I haven't dug into it yet.

Please let me know if this isn't precise enough. Also check out the discussion I started [here](https://github.com/chakra-ui/chakra-ui/discussions/2550) If this is a legitimate issue, I'll mark it answered and reference the issue. 

Thank you!

**Comment by with-heart** [comment]
The problem here was that the examples weren't identical. NextJS was using `@chakra-ui/core@1.0.0-rc.8` while the CRA example was using `@chakra-ui/react@^1.0.0`. The fix for this issue was #2389 which was first included in `@chakra-ui/react@1.0.0`. You can see it working correctly here: https://codesandbox.io/s/busy-sound-hh9ov?file=/pages/index.js
