### ISSUE TITLE
Popover within Modal - flashes and dissapears

### ISSUE THREAD

**Issue by DanLeCornu** [chakra-ui/chakra-ui#2569]
# Bug report

## Describe the bug
Chakra v0.8.0 - When using a popover within a modal, triggering the popover will result in the popover showing and then immediately disappearing, resulting in a flashing of the popover, with no chance for the user to interact with the popover content. This problem is only occurring in production environments, in development env it's fine (for us at least)

## To reproduce

1. Be in a production env using the safari browser
2. Add a popover component within a modal component
3. Trigger the popover
4. Watch with dismay as the sad popover flashes again and again

## Minimal reproduction

Couldn't get a pre v1.0 version of Chakra to work within code sandbox unfortunately

## Expected behaviour

Popover to show and stay shown

## Screenshots

https://imgur.com/a/orgDLGu

## System information

- OS: macOS
- Browser: Safari only
- Version of @chakra-ui/react: ^0.8.0
- Version of Node.js: v14.4.0

**Comment by yoongti** [comment]
@DanLeCornu Can you try using chakra-ui v1.0.0? It seems to work properly with v1.0.0.

![image](https://user-images.githubusercontent.com/15006252/101282678-6b41b580-3811-11eb-88c8-c336468c6f54.png)

**Comment by TimKolberger** [comment]
As v0.8 won't receive any bugfixes please follow our [upgrade guide to v1](https://chakra-ui.com/docs/migration) and try our [codemod](https://github.com/chakra-ui/chakra-codemod).
