### ISSUE TITLE
[Menu] rendering problems with multiple menus

### ISSUE THREAD

**Issue by aaronmcadam** [chakra-ui/chakra-ui#257]
**Describe the bug**

My use case is a column of cards with actions that can be taken (e.g. duplicate, delete). At the top of the list, the menus seem to work fine. But when you start scrolling down the list and open the menus, we start to see some strange behaviour:

* Sometimes the menu will flicker. 
* Sometimes you'll scroll up and try to open the menu and it won't appear. 
* Sometimes the options are very hard to select because the menu jumps around.

See this screen capture from the [codesandbox](https://codesandbox.io/s/chakra-js-starter-xxqzk):

![CleanShot 2019-11-19 at 11 59 40](https://user-images.githubusercontent.com/37928/69145067-b41eb300-0ac4-11ea-937c-8a101e6ed9f1.gif)

Here's another example from my app:

![CleanShot 2019-11-19 at 12 06 41](https://user-images.githubusercontent.com/37928/69145274-33ac8200-0ac5-11ea-8fd3-26810dd09b3b.gif)

**Expected Behavior**

I expect the menus to work as normal when they're in a list.

**To Reproduce**
Use this codesandbox: https://codesandbox.io/s/chakra-js-starter-xxqzk

**Suggested solution(s)**

I think using portals might be a better fit for my use case because of how the positioning needs to work. I think maybe allowing `Menu` to accept the `usePortal` prop might help. I had a look at the implementation and `usePortal` is hard coded to `false`: https://github.com/chakra-ui/chakra-ui/blob/91966cef0a5b424b44b1850393e9f66de4f469d0/packages/chakra-ui/src/Menu/index.js#L316.  

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.1
 - Browser: Chrome
 - Version: 78.0.3904.97

**Comment by aaronmcadam** [comment]
Do you have any suggestions @segunadebayo? I was going to see if reimplementing the menu with the `Popover` and setting the `isPortal` to `true` would help.

**Comment by segunadebayo** [comment]
@aaronmcadam, that might work. I'm thinking it has to do with some modifiers in `popper.js`, maybe `enableEventListeners` needs to be set to false.

Not sure but I'll look into it. The walkaround is to use Popover directly. I'll test this within the `dev-ts` and ensure this bug is fixed

**Comment by aaronmcadam** [comment]
> The walkaround is to use Popover directly

Do you mean I'd have to build my own menu instead with my own components? I was thinking I'd have to try that.

**Comment by segunadebayo** [comment]
Yes, you might have to try that. Let me know how it goes.

**Comment by aaronmcadam** [comment]
Thanks @segunadebayo. For now, I've had to deploy a different component, but I might get around to trying to rebuild the menu later.

**Comment by segunadebayo** [comment]
@aaronmcadam , I've resolved this problem in the `dev-ts` branch so you should be good in the next release 😄

**Comment by aaronmcadam** [comment]
Thanks so much @segunadebayo!

**Comment by Aeolun** [comment]
Note that this issue has not been fixed yet. My menu is still janking around like crazy when I move my mouse on top of it.

**Comment by ljosberinn** [comment]
@Aeolun could you please provide a codesandbox? I have not seen any performance issues solely because of moving the mouse.

**Comment by aaronmcadam** [comment]
@Aeolun you're welcome to fork my original codesandbox and update the code for v1: https://codesandbox.io/s/chakra-js-starter-xxqzk

**Comment by Segun98** [comment]
Still have the same issue with Menu. It lags on mobile

**Comment by ljosberinn** [comment]
@Segun98 could you please provide a codesandbox?
