### ISSUE TITLE
Bug: useColorMode returned undefined colorMode if you use an 3thparty chakra component library

### ISSUE THREAD

**Issue by oschade** [chakra-ui/chakra-ui#2572]
# Bug report

## Describe the bug

I'm not sure, this is a bug or just the default behaviour of react hooks, but let me explain:
I have two projects in a Monorepo:
**Project A**: the Main App, using Chakra
**Project B**: contains custom Chakra-UI-Components using chakra components

I use the ChakraProvider in **A** with a **custom theme**. When I import one Component from **B**, this Component uses the custom theme of **A**, as you excpected.
If you toggle the colorMode in **A**, then the colors in the components of **B** all so changed. This is fine, too

**BUT**: If you switch the colorMode in **A**, the useColorMode hooks in **B** get not triggered.
_Correction: Hooks actually get triggered, but the "colorMode"-value is "undefined"._

And this is unexpected, because everything else works: the theme-context get recognised in **B** and also the colorModeChange triggers the chakra-ui-component internals.

Is this a bug?

## To reproduce

create a repo and export a button component with custom background-color using the useColorModeValue-hook, for example.

**Comment by ljosberinn** [comment]
sounds like useColorMode/-Value consume a different color mode context, are there version discrepancies between the repos regarding emotion/chakra? it sounds like there arent but..

just to be sure:
components in **B** use the _theme values_ from **A**, _except_ for the color mode?

**Comment by oschade** [comment]
> sounds like useColorMode/-Value consume a different color mode context, are there version discrepancies between the repos regarding emotion/chakra?

The versions of chakra and react are the same in **A** and **B**.

> just to be sure:
> components in **B** use the _theme values_ from **A**, _except_ for the color mode?

I set in my theme a "brand"-color and be able to use it in **B**.
But I was wrong: the useColorMode/ useColorModeValue hooks actually get triggered, but the "colorMode"-value is "undefined". I correct my explanation above.

**Comment by ljosberinn** [comment]
- which chakra version are you on?
- can you show where youre using, presumably, ChakraProvider and how, exactly?

**Comment by oschade** [comment]
I use:
    "@chakra-ui/react": "^1.0.0",
    "@emotion/react": "^11.1.1",
    "@emotion/styled": "^11.0.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",

I setup the ChakraProvider in my App.tsx.

index.tsx
```
import * as React from 'react'
import { render } from 'react-dom'
import { ColorModeScript } from '@chakra-ui/react'
import theme from './theme'
import App from './App'

const rootEl = document.getElementById('root')

render(
  <>
    <ColorModeScript initialColorMode={theme.config.initialColorMode} />
    <App />
  </>,
  rootEl
)
```


App.tsx
```
import React from 'react'
import { ChakraProvider, Box, Flex} from '@chakra-ui/react'
import theme from './theme'

const App = () => {
  return (
    <ChakraProvider theme={theme}>
      <Flex w="100vw" h="100vh" flexDir="row">
          ...
      </Flex>
    </ChakraProvider>
  )
}

export default App

```


In Project B I use currently no ChakraProvider, but I tried to: It makes no difference.

**Comment by ljosberinn** [comment]
That looks alright... do you happen to have a repo to look at? And if you check the React devtools -> ColorModeProvider, what prop `value` does it have before and after changing the color mode?

**Comment by oschade** [comment]
While I creating an example-repo, I can't reproduce my problem. It works fine with Create-React-App!

This is maybe related to webpack-5: 
https://github.com/vercel/next.js/issues/18090

I'm using webpack 5 in my setup, CRA uses still webpack 4.

If I'm correct: is this then an issue of webpack or an issue of chakra?

I will test my project with webpack 4 later this day.

**Comment by ljosberinn** [comment]
I'm using WP5 (latest, 5.6) in prod and don't encounter that issue; but I don't have components imported from a separate project.

If I'm not mistaken, e.g. on my page here: https://personal-react-boilerplate.now.sh/ you should have a fine initial render, then toggle the theme, switch route (by clicking on `Get Started`), then try to retoggle theme and nothing happens? However, I'm using layouts, so that might accidentally fix it 🤔

**Comment by oschade** [comment]
I created a repo using webpack5, please check:

https://github.com/oschade/chakra-example

You can run the server with `yarn dev`

In the console it should log the current colorMode. In a CRA-App it works, with webpack5 it is always: undefined.
(This example shows just the webpack-5 version, not the CRA).

**Comment by ljosberinn** [comment]
Thanks, I think I know why:

![image](https://user-images.githubusercontent.com/29307652/99844036-cbc6c680-2b72-11eb-880f-82c5cab8fa1a.png)

The source of useColorMode in your components package is the cjs bundle.

![image](https://user-images.githubusercontent.com/29307652/99844112-e8fb9500-2b72-11eb-8ad8-298ce470e6ec.png)

The source of useColorMode in App is the esm bundle!

You can additionally verify both are used by setting breakpoints within useColorMode in both bundles:

![image](https://user-images.githubusercontent.com/29307652/99844215-0cbedb00-2b73-11eb-8f14-45890bb789ca.png)
![image](https://user-images.githubusercontent.com/29307652/99844259-219b6e80-2b73-11eb-84cc-4acdbe3c1aca.png)

Sounds like a webpack config issue to be, but I havent dabbled with it in a few years.

**Comment by oschade** [comment]
Thank you very much for your advice! The issues was a misconfigured tsconfig file. Took me some time, but now it works!

**Comment by alveshelio** [comment]
Hi,

I'm having the same issues with Nextjs. You said it was a misconfiguration of tsconfig. Can you please tell me what you did?

**Comment by oschade** [comment]
I didn't know it anymore, but here is my current tsconfig:

tsconfig.json
```
{
  "compilerOptions": {
    "module": "CommonJS",
    "lib": [
      "esnext"
    ],
    "target": "es2019",
    "declaration": true,
    "declarationMap": true,
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": false,
    "removeComments": true,
    "moduleResolution": "node",
    "noLib": false,
    "strict": true,
    "incremental": true,
    "strictPropertyInitialization": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "noEmitOnError": false,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "extendedDiagnostics": false,
    "listFiles": false,
    "typeRoots": [
      "../../node_modules/@types"
    ]
  },
  "exclude": [
    "dist",
    "node_modules",
    "**/node_modules",
    "**/.*/",
    "**/*.spec.ts"
  ]
 }
```
 
tsconfig.web.json
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "module": "esnext",
    "lib": ["dom", "esnext"],
    "jsx": "react",
    "allowJs": true,
    "isolatedModules": true,
    "resolveJsonModule": true
  }
}
```

packages/components/tsconfig.json
```
{
  "extends": "../../tsconfig.web.json",
  "compilerOptions": {
    "composite": true,
    "rootDir": "src",
    "outDir": "dist"
  },
  "include": [
    "./src/**/*"
  ],
  "exclude": [
    "dist",
    "node_modules"
  ]
}
```

**Comment by alveshelio** [comment]
Hi @oschade,

Thank you very much for getting back so fast. I was actually able to solve my problem and maybe for anyone ending up in this issue maybe this can help.

So since I'm using NextJS, I was using `useColorMode()` directly in the page. I don't why but for some reason when you use `useColorMode()` directly in the page you'll not be able to access `colorMode` but strange enough, you can still call `toggleColorMode()`.

So I ended up moving the content of the page to a component and imported the component and not it works like a charm.

Again, Thank you for your help and I hope this can help someone else in the future :)

**Comment by ljosberinn** [comment]
> So since I'm using NextJS, I was using useColorMode() directly in the page. I don't why but for some reason when you use useColorMode() directly in the page you'll not be able to access colorMode but strange enough, you can still call toggleColorMode().

That's possible. And you cannot call `toggleColorMode` outside of the provider because then its undefined, [as per source](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/color-mode/src/color-mode-provider.tsx#L25). So I'm afraid it was something else.

**Comment by nejcm** [comment]
I see this closed but I am getting the same issue with next.js 13+ and latest chakra.ui. When using the useColorMode hook both the value and toggle method are undefined. I am using the hook inside the provider.

**Comment by elboletaire** [comment]
I'm also having this same issue using a CRA app, but I can only reproduce it when using workspaces (no need to actually link anything, as soon as I have the repo inside my monorepo it starts failing).

**Comment by elboletaire** [comment]
> UPDATE: So for me upgrading `@chakra-ui/react` or `@chakra-ui/system` from 2.3.1 to 2.3.5 or higher breaks things. I went to look into the yarn.lock and saw that some packages get duplicated versions probably because of the version mismatch (dependent on different versions) between `@chakra-ui/system` and `@chakra-ui/react`. Hard to say what could be the cause. For now will not be upgrading.

Thanks dude. Yes there seems to be something odd here, downgraded `@chakra-ui/react` to 2.3.7 and then it started working as expected again. Maybe we should open a new issue for this, since looks like some problem from chakra side (??)
