### ISSUE TITLE
[StackDivider] Console error when adding divider in stack (should have a unique "key" prop)

### ISSUE THREAD

**Issue by JeremieLeblanc** [chakra-ui/chakra-ui#2573]
# Bug report

## Describe the bug
When adding a StackDivider to the Stack component, you get a console error for a missing key.

## To reproduce
Add a divider prop to the Stack component.

## Minimal reproduction

https://codesandbox.io/s/quizzical-hodgkin-5qz4e

## Expected behavior
Children of the Stack component should be given a unique key.

## Screenshots
![image](https://user-images.githubusercontent.com/9596165/99704545-eadc3000-2a6e-11eb-9ee0-30c252d7d771.png)

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of @chakra-ui/react: 1.0.0
- Version of Node.js: v14.15.0

**Comment by segunadebayo** [comment]
Hi @JeremieLeblanc, we merged a PR that fixed this.

A new release would be out shortly.

**Comment by JeremieLeblanc** [comment]
> Hi @JeremieLeblanc, we merged a PR that fixed this.
> 
> A new release would be out shortly.

Thank you!
