### ISSUE TITLE
Popover/Menu is cropped if it is wrapped by FormControl in AccordionPanel.

### ISSUE THREAD

**Issue by kueychuj** [chakra-ui/chakra-ui#2576]
# Bug report

## Describe the bug

Popover and Menu are cropped and bounded by AccordionPanel if it is wrapped by FormControl in Accordion.

## To reproduce

Please check the example below

## Minimal reproduction

https://codesandbox.io/s/quirky-mirzakhani-oqbjt?file=/src/App.js

## System information

- macOS
- Chrome
- @chakra-ui/react v1.0.0

**Comment by santialbo** [comment]
You should wrap the `PopoverContent` inside a `Portal` element.
Check https://codesandbox.io/s/pensive-rhodes-ud69g?file=/src/App.js

**Comment by with-heart** [comment]
@kueychuj give the solution from @santialbo a try! If that doesn't work, feel free to reply and we can take another look.

**Comment by kueychuj** [comment]
> You should wrap the `PopoverContent` inside a `Portal` element.
> Check https://codesandbox.io/s/pensive-rhodes-ud69g?file=/src/App.js

Thanks for help. I think your solution is ok with popover but not menu.

but the way, may i know where the Portal API documentation is?

**Comment by santialbo** [comment]
> > You should wrap the `PopoverContent` inside a `Portal` element.
> > Check https://codesandbox.io/s/pensive-rhodes-ud69g?file=/src/App.js
> 
> Thanks for help. I think your solution is ok with popover but not menu.
> 
> but the way, may i know where the Portal API documentation is?

It's the same for the menu, wrap the `MenuContent` inside a `Portal`.
