### ISSUE TITLE
@chakra-ui/gatsby-plugin interfere with netlify-cms admin

### ISSUE THREAD

**Issue by EdinSkeja** [chakra-ui/chakra-ui#2584]
# Bug report

## Describe the bug
I just added @chakra-ui/gatsby-plugin@1.0.0 to my project and currently i'm using gatsby with netlify-cms. The plugin works perfectly for the site but it's interfering with the netlify-cms? Does anyone else have this issue and how could i be able to fix this?

## To reproduce

1. clone [https://github.com/netlify-templates/gatsby-starter-netlify-cms](https://github.com/netlify-templates/gatsby-starter-netlify-cms) and follow install instructions
2. `yarn add  @chakra-ui/gatsby-plugin @chakra-ui/react @emotion/react @emotion/styled`
3. add `@chakra-ui/gatsby-plugin` to `gatsby-config.js`
4. `yarn develop`
5. Go to `http://localhost:8000/admin`

## Expected behavior

Not to interfere with the admin interface.

## Screenshots
Expected default 
<img width="1424" alt="Skärmavbild 2020-11-21 kl  15 52 47" src="https://user-images.githubusercontent.com/2357726/99880108-a2a94300-2c11-11eb-9a76-986b8c439030.png">

With gatsby-plugin
<img width="1494" alt="Skärmavbild 2020-11-21 kl  15 44 35" src="https://user-images.githubusercontent.com/2357726/99879987-ddf74200-2c10-11eb-9866-799f2aee321a.png">

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of @chakra-ui/gatsby-plugin: 1.0.0i
- Version of Node.js: 12.18.4

**Comment by ljosberinn** [comment]
netlify-cms seems to be styling with bulma, so you already have a css framework in there and then add Chakra, that makes no sense conceptually as you should pick one

**Comment by with-heart** [comment]
Going to go ahead and close this. Conflicting styles happen when using multiple frameworks. There's not anything we can do to avoid this problem.

**Comment by benatkin** [comment]
Sometimes it's worth pushing through conflicting styles.

The key to it is adding extra scopes with [stylisPlugins](https://emotion.sh/docs/@emotion/cache).

```ts
// based on https://github.com/drenckpohl/stylis-plugin-extra-scope/blob/stylis-v4/src/index.js
// MIT License
function createExtraScopePlugin(...extra: string[]) {
  const scopes = extra.map((scope) => `${scope.trim()} `)

  const plugin: StylisPlugin = (element) => {
    if (element.type !== 'rule') {
      return
    }

    if (element.root?.type === '@keyframes') {
      return
    }

    const propsArray = Array.isArray(element.props) ? element.props : [element.props]
    if (propsArray.includes(':root')) {
      return
    }
    element.props = propsArray
      .map((prop) => scopes.map((scope) => scope + prop))
      .reduce((scopesArray, scope) => scopesArray.concat(scope), [])
  }
  return plugin
}

const customCache = createCache({
  key: 'cc',  // custom chakra - in case the other library uses c for the prefix
  stylisPlugins: [
    prefixer,
    createExtraScopePlugin('._cs._cw'),  // cs for chakra scope, cw for chakra wrap
  ]
})
```
