### ISSUE TITLE
PortalManager rendering things "outside of view"

### ISSUE THREAD

**Issue by santialbo** [chakra-ui/chakra-ui#2586]
# Bug report
This is a bit hard to explain but I'll try.

When you have any portal elements (e.g. a menu) deep down inside an overflowed container, the portal manager is rendering something with visibility hidden at that same position but on the root, causing the app to have a larger than expected height and making the browser show a scrollbar.

## Minimal reproduction
Here's a codesandbox reproducing the issue https://codesandbox.io/s/great-liskov-4t5g9?file=/src/App.ts

The regression was introduced after 1.0.0-rc.5
This is a working codesandbox from that version https://codesandbox.io/s/falling-tree-nci26?file=/src/App.tsx

**Comment by santialbo** [comment]
If anyone finds a workaround I would love to hear it 🙏. This is the only thing preventing me to upgrade to 1.0.1.

**Comment by Samic8** [comment]
This sounds like a tricky one. Maybe we could remove the portal element from the DOM if it is about to overflow the viewport.

That wouldn't allow for intentional overflow, but unsure if anyone would want that anyway.

**Comment by santialbo** [comment]
The regression was introduced after 1.0.0-rc.5
This is a working codesandbox from that version https://codesandbox.io/s/falling-tree-nci26?file=/src/App.tsx

**Comment by Samic8** [comment]
Oh right, thanks @santialbo. I will have some time next Monday/Tuesday to work on Chakra and I can look into this issue then if you don't beat me to it.

**Comment by santialbo** [comment]
I think there was a major refactor of the Portal Manager before 1.0.0 to use `visibility: hidden` instead of `display: none`. I assume this was done to allow animations. Maybe @segunadebayo could explain this better.

**Comment by Samic8** [comment]
It does seem like that is the issue and introduced here: hhttps://github.com/Samic8/chakra-ui/commit/123baa4fa4a568c6b3f37422e9e663a4cc37d498#diff-6c4aefbd3ea81ddacf70475aa13274ae14fbcc6609044c74a25c45f12bd9ff4eR343

We could add these styles when the menu is hidden
```css
height: 0; 
width: 0;
overflow: hidden;
```

I'm not sure how that would affect animations applied to the menu though. 

Do we have an example of how animations might be used with the menu component?

**Comment by Samic8** [comment]
I just tried that out and it did remove the menu transition when going from open to closed.

**Comment by segunadebayo** [comment]
Looking into this

**Comment by segunadebayo** [comment]
@santialbo can you clarify this some more, do you mean the menu is being portaled to the wrong location? or is this specific to the Menu using `visibility: hidden`?

**Comment by santialbo** [comment]
Thanks for looking into this @segunadebayo. It's not that it's portaled in the wrong position. It's that an empty div is rendering (even when the menu is closed) which causes the body to overflow.
If you look at the scrollbars in the codesandbox you will see that the body is a lot larger than what would be expected. You can check both codesandbox to see the difference.

If you are on a mac, make sure to set this setting to get the experience one would get in other OS
<img width="672" alt="Screenshot 2021-01-08 at 18 05 47" src="https://user-images.githubusercontent.com/1557563/104043516-3b088080-51dc-11eb-9e74-c81ed9630224.png">

**Comment by martinpengellyphillips** [comment]
Just encountered this too after using a portal in a similar setup. 

![portal-overflow-page-issue](https://user-images.githubusercontent.com/214338/106206672-61f11b80-61b8-11eb-8ca1-760871dd4572.jpg)

**Comment by santialbo** [comment]
This issue seems to be fixed on the latest version of chakra, I'm not able to reproduce it anymore on the codesandbox. However there's still a small issue if `portalZIndex` is used (which I suspect is also @martinpengellyphillips issue). I will open a separate ticket for that.

**Comment by landermedia** [comment]
I'm not sure but I think I'm seeing this issue starting in 1.8.7 if I remember correctly. The good thing is this isn't reproducible in production with Next.js. I'm really not sure what's happening but it's really cumbersome to keep refreshing the browser after you close the Modal or Popover.

<img width="870" alt="image" src="https://user-images.githubusercontent.com/83575285/168072102-87b49a88-6ab9-4a76-ab30-eeddf455aff3.png">

**Comment by Chukwuamaka** [comment]
This issue persists in Chakra v2.3.6. [This solution](https://github.com/chakra-ui/chakra-ui/issues/2760#issuecomment-1372294655) in a duplicate issue worked for me.
