### ISSUE TITLE
Add Search to docs for easier navigation & lookup

### ISSUE THREAD

**Issue by xtrial** [chakra-ui/chakra-ui#2588]
# Feature request

## Is your feature request related to a problem? Please describe.

Like the title said 👍

**Comment by lukas321396** [comment]
Buenas noches solo puedo desir q e estado trabajando estudiando bien duro en unos días más mandar correo establecere mi escrito asía GitHub nuevo software la aplicasion que tengas buena noche .. El 23 nov 2020 1:14 a. m., xtrial <notifications@github.com> escribió:

Feature request

Is your feature request related to a problem? Please describe.

Like title said 👍

**Comment by with-heart** [comment]
Duplicate of #2264
