### ISSUE TITLE
Chakra doesn't seem to work well with react-player

### ISSUE THREAD

**Issue by Hargoze** [chakra-ui/chakra-ui#2590]
# Bug report

i have an error when using ```@chakra-ui/react``` and ```react-player``` with next-js

![image](https://user-images.githubusercontent.com/60386882/99941578-8cfd6000-2d6e-11eb-87af-9df58aca1ce3.png)

when i used chakra v0.8 i didn't have this issue but i do now with the released version

my code:

``` 
<Box rounded="20px" overflow="hidden" my="6">
          <ReactPlayer
            url='video-home-last.mp4'
            controls = {true}
            playing={true}
            muted={true}
            loop={true}
            width="100%"
            height="100%"
          />
</Box>
```

Is there a way tomake react-player work with chakra or should i use ```<AspectRatio/>``` ?

**Comment by ljosberinn** [comment]
That doesn't seem to be related to Chakra but your usage of `react-player` with next.js; what is hte origin of the function mentioned there, `init`? Could you provide a sandbox?

**Comment by Hargoze** [comment]
i have no idea where the init comes from to be honest

**Comment by ljosberinn** [comment]
the call stack is expandable, should be mentioned there; my assumption is that react-player isn't compatible to SSR

**Comment by ljosberinn** [comment]
looks like it _is_ compatible with SSR, then I'm even more curious where `init` comes from, since [Chakra does not have a function with that name](https://github.com/chakra-ui/chakra-ui/search?q=init)

**Comment by Hargoze** [comment]
i am laking a sandbox but it seems to work in the sandbox, the problem certainly comes from me

**Comment by ljosberinn** [comment]
ping me on discord should you need some rubber ducking :)

**Comment by lukas321396** [comment]
Usen la versión la última se puede? claro que se puede desd en el país en el que se encuentr cada quien se puede somos nosotros Kien asé esto no un alienígena inténtelo igual yo puedo ayudar explicando paso x paso checkra1n no es lo nuevo los nuevos somos nosotros así que la misión es no rendirse animoEl 23 nov 2020 2:39 a. m., Hargoze <notifications@github.com> escribió:
Bug report
i have an error when using @chakra-ui/react and react-player with next-js

when i used chakra v0.8 i didn't have this issue but i do now with the released version
my code:
<Box rounded="20px" overflow="hidden" my="6">
          <ReactPlayer
            url='video-home-last.mp4'
            controls = {true}
            playing={true}
            muted={true}
            loop={true}
            width="100%"
            height="100%"
          />
</Box>

Is there a way tomake react-player work with chakra or should i use <AspectRatio/> ?

**Comment by lukas321396** [comment]
Recomiendo que trabajen el idioma Ruby agan cuentas i empiesen con su aplicasion programa cmo gusten acabando seguro q en el tiempo en el que ases thu thu app ai t darás cuenta El 23 nov 2020 2:47 a. m., Gerrit Alex <notifications@github.com> escribió:
ping me on discord should you need some rubber ducking :)
