### ISSUE TITLE
Container does not accept variants in theme

### ISSUE THREAD

**Issue by hutber** [chakra-ui/chakra-ui#2593]
Currently it seems I am unable to use a `variant` on the Container component. I believe this is not meant to be the case?

```   
 <Container
      variant="share"
    >
```

Output:

```
<div 
    class="chakra-container css-3z6a7s"
    variant="readMore"
>
```

Versions:
```
    "@chakra-ui/core": "^1.0.0",
    "@chakra-ui/media-query": "^1.0.0",
```
Theme:
![image](https://user-images.githubusercontent.com/1344898/99968651-508f2b80-2d91-11eb-9d8b-a760e54cc2b9.png)

Output:
![image](https://user-images.githubusercontent.com/1344898/99968670-58e76680-2d91-11eb-87bc-1c31a224132c.png)

**Comment by la55u** [comment]
Container component is not themeable. See https://github.com/chakra-ui/chakra-ui/issues/2405

**Comment by hutber** [comment]
Thank you @la55u. I only created this ticket as I was told only the Box isn't themeable. My mistake.
https://github.com/chakra-ui/chakra-ui/issues/2456
