### ISSUE TITLE
The Breakpoint system fails with custom "em" breakpoint values.

### ISSUE THREAD

**Issue by gitmonster** [chakra-ui/chakra-ui#2595]
# Bug report

## Describe the bug
The Breakpoint system fails with custom breakpoints provided with custom "em" values.

## To reproduce
See this sandbox. A valid breakpoint is not recognized. On smaller screens the value is flipping fast.

## Minimal reproduction
[Codesandbox](https://codesandbox.io/s/chakra-ui-breakpoint-test-x2dkv)

## Expected behavior
useBreakpoint() and useBreakpointValues() should work with custom "em" values

## System information

- OS: linux
- Browser : Chrome, Firefox...
- Version of @chakra-ui/react: 1.0.1
- Version of Node.js: 14.15.1

**Comment by OFranke** [comment]
@gitmonster The way you are trying to customize breakpoints is not intended. You can only configure breakpoints base, sm, md, lg, xl. See https://codesandbox.io/s/chakra-ui-breakpoint-test-forked-1sh9l?file=/src/index.js

Please also note this issue: https://github.com/chakra-ui/chakra-ui/issues/2539

**Comment by gitmonster** [comment]
OK, that works!. I was assuming that, regardless of the systems breakpoints, I also can define free ones.
