### ISSUE TITLE
Allow responsive font sizes in theme.

### ISSUE THREAD

**Issue by neil-morgan** [chakra-ui/chakra-ui#2599]
Without predefining a component which feeds an object of font sizes into the `fontSize` prop there doesn't seem to be a way to quickly and consistently apply responsive font sizes.

### It would be very handy to be able to do this:

```
//theme.js
const fontSizes = {
  ...
  ...
  ...
  ...
  "6xl": { base: "42px", md: "54px", lg: "64px" },
}
```

### Or perhaps add a new theme object entirely

```
//theme.js
const fontSizes = {
  ...
  ...
  ...
  ...
  "6xl": "64px" ,
}

const fluidFontSizes = {
  ...
  ...
  ...
  ...
  "6xl": { base: "42px", md: "54px", lg: "64px" },
}
```

**Comment by OFranke** [comment]
I was dealing with the same thing. You could define it on component level. See also this: https://chakra-ui.com/docs/theming/customize-theme

```
  const extendedTheme = {
    components: {
      Heading: {
        sizes: {
          "6xl": {
            fontSize: { base: "10px", lg: "50px" },
          },
        },
      },
    },
  };
```

**Comment by TimKolberger** [comment]
The theme is like a grocery store. It provides e.g. water in 3 different variants: `no-sparkles`, `medium-sparkles`, `maximum-sparkles`.

If you are hosting a dinner for _two_ people, you would buy _two bottles_ of the variant you would like to offer your guests.
If you are having _six_ guests you would need to _responsively_ alter the amount of water bottles.

But the store won't need to change its products. It would not be efficient that the store would offer many different packages like "Non sparkling water for 6 persons", "Medium sparkling water for 2 persons" etc.

You would have to do the abstraction and provide the responsive value (amount of bottles and variant) for your dinner.

There are the different levels of style abstractions present. 

1. The grocery store is our theme foundation (font sizes, colors), 
2. the dinner preparation is our components part of the theme, 
3. and when dinner is served you arrange the components with its styles on your dish as you like (your application code)

I hope this metaphor helps 😅

**Comment by agentlewis** [comment]
@timkindberg while I get the point your making, but I don't see how this answers the question (I have the same one).

Currently I can add a `Heading` into my code and specify the fontSize it is, I then want it to get larger at later breakpoints.

I would therefor naively expect to be able to pass it an array of values defining what size I want it to be at different break points.

Currently it looks like I have to create a component per `Heading` size and then import them into my codebase eg. `2xl, xl... xs`. This feels like a huge amount of code duplication when I am already specifying these in the when I declare the `Heading`.

eg: 

```
<Heading
   align={alignText}
   fontSize={heading.size}
   key={uuidv4()}
 >
  {heading.text}
</Heading>
```

ps this is the code snippet I am using for rendering an array of headings underneath each as defined in client side config view.

**Comment by TimKolberger** [comment]
This is perfectly possible with the current tools. Please have a look at the "dinner preparation", the component part of the theme: 

The default theme has responsive font sizes for the Heading, see
https://github.com/chakra-ui/chakra-ui/blob/develop/packages/theme/src/components/heading.ts

And this comment https://github.com/chakra-ui/chakra-ui/issues/2599#issuecomment-732936173

Please note that you apply those styles with the size prop, not fontSize.

**Comment by agentlewis** [comment]
@timkindberg wow thanks for the speedy response.

So I had given that a try by defining an object and adding it to my theme under components. But it didn't work. Can you please look at this snippet and tell me if I have missed something obvious?

```
// responsive rules - not necessarily what I want, just values from figma.
export default {
  Heading: {
      sizes: {
        xs: {
          fontSize: ['10px', '12px']
        },
        sm: {
          fontSize: ['12px', '14px']
        },
        md: {
          fontSize: ['14px', '16px']
        },
        lg: {
          fontSize: ['16px', '18px']
        },
        xl: {
          fontSize: ['18px', '20px']
        },
        '2xl': {
          fontSize: ['20px', '24px']
        },
        '3xl': {
          fontSize: ['20px', '24px', '28px']
        },
        '4xl': {
          fontSize: ['24px', '28px', '36px']
        },
        '5xl': {
          fontSize: { base: '28px', md: '36px', lg: '48px'}
        },
        "6xl": {
          fontSize: { base: '36px', md: '48px', lg: '64px'}
        }
    }
  }
}

// theme file

import { extendTheme } from '@chakra-ui/react'
import { createBreakpoints } from '@chakra-ui/theme-tools'

import styles from './styles'
import Heading from './components/heading'

const columnWidth = 4.7619047619

const breakpoints = createBreakpoints({
  sm: '40em',
  md: '52em',
  lg: '64em',
  xl: '86em'
})

const overrides = {
  styles,
  colors: {
    black: '#16161D',
    orange: '#F76626',
    pink: {
      200: '#FBC9BC',
      100: '#F8E2D6'
    },
    yellow: '#F5E6C4',
    grey: '#C4C4C4'
  },
  fonts: {
    body: "system-ui, sans-serif",
    heading: "Georgia, serif",
    mono: "Menlo, monospace",
  },
  fontSizes: {
    xs: "12px",
    sm: "14px",
    md: "16px",
    lg: "18px",
    xl: "20px",
    "2xl": "24px",
    "3xl": "28px",
    "4xl": "36px",
    "5xl": "48px",
    "6xl": "64px",
  },
  breakpoints,
  maxWidth: '82em',
  columnWidth: columnWidth,
  pageXMargin: [
    `${columnWidth * 0.5}%`,
    `${columnWidth * 0.75}%`,
    `${columnWidth}%`,
    `${columnWidth}%`,
    0
  ],
  pageYMargin: ['3em', '4em', '6em'],
  components: {
    Heading
  }
}

export default extendTheme(overrides)

```

**Comment by TimKolberger** [comment]
See this codesandbox for reference: https://codesandbox.io/s/chakra-ui-responsive-heading-4bh4p?file=/src/App.tsx

`<Heading size="xl"` is not the same as `<Heading fontSize="xl"`. The `fontSize` prop only applies the fontSize, the `size` prop applies the defined styles from the theme.

**Comment by agentlewis** [comment]
Oh thanks so much - thats exactly what I needed! inner-critic attack alleviated.
