### ISSUE TITLE
Convert Tabs component to TS

### ISSUE THREAD

**Issue by thefrontendwizard** [chakra-ui/chakra-ui#260]
https://github.com/chakra-ui/chakra-ui/projects/1#card-29009903
I'd like to contribute on the migration so if nobody took this one, I'd like to take it.

**Comment by aaronmcadam** [comment]
The latest commit on `dev-ts` already tackles this: https://github.com/chakra-ui/chakra-ui/commit/0be477bf0638022251bd5abb676026cdca283f11

**Comment by thefrontendwizard** [comment]
yeah, saw it. there are lots of `any` types in there though, so perhaps improving the types would be good.

**Comment by aaronmcadam** [comment]
Ah I see @thefrontendwizard. Maybe we should find out why the `any` types were used. Maybe there were some awkward issues when doing a first pass.

**Comment by aaronmcadam** [comment]
It appears everything except the component itself is pretty well covered. I wonder whether the use of `any` inside the component defs is just a pattern to get us onto TypeScript, with the view to improve thing later.

**Comment by segunadebayo** [comment]
Hi @thefrontendwizard,

I'm working on the Tabs component already. Feel free to pick any other components. I really appreciate your willingness to help and would love to help you get started.

As regards `any` types, it's just a first pass so I don't have to worry about the types just yet till everything is working, then I gradually tighten the types and remove `any`.
