### ISSUE TITLE
[Slider] Document that `aria-label` prop is required for accessibility

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#2604]
Since we have no way to determine the label for `Slider` components, we rely on the user to provide an `aria-label` prop. The documents don't mention that this is required for accessibility, and we need to make that clear.

**Comment by TimKolberger** [comment]
It is mentioned in the [Slider props table](https://chakra-ui.com/docs/form/slider#slider-props). We can't make it required, due `aria-labelledby` being a valid alternative to label this element.

**Comment by segunadebayo** [comment]
I agree, it's documented in the slider prop table already.

I've also added a note to the slider docs as well.
