### ISSUE TITLE
[Menu] Add example with animation in docs

### ISSUE THREAD

**Issue by jaredpalmer** [chakra-ui/chakra-ui#261]
Just like AlertDialog, using `<SlideIn>` etc.

**Comment by jaredpalmer** [comment]
I have tried this and it doesn't work, but I think it should for consistency and completeness.

**Comment by segunadebayo** [comment]
Hi @jaredpalmer. I'll look into this

**Comment by hugotox** [comment]
Hello! Any examples on how to modify the transition used by `Menu`?
