### ISSUE TITLE
isLoading is not implemented on Input, as the documentation suggests

### ISSUE THREAD

**Issue by pianomansam** [chakra-ui/chakra-ui#2610]
# Bug report

## Describe the bug

The [current documentation](https://chakra-ui.com/docs/form/input#props) suggests that `isLoading` is implemented on `<Input>` but I get the following error:

> Warning: React does not recognize the `isLoading` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isloading` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

## To reproduce

Add the `isLoading` property to an `<Input>` component.

## Minimal reproduction

https://codesandbox.io/s/epic-easley-6s1q7?file=/src/App.tsx

## Expected behavior

Minimally, no error. But additionally, some sort of visual indicator of loading status.

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of @chakra-ui/react: 1.0.1
- Version of Node.js: 12.19.1

**Comment by with-heart** [comment]
The `isLoading` prop could be used for theming purposes. We don't have a visual use case for displaying a loading input (truth be told, I'm not even sure what that would look like), but if you had a use case for it, you could access it as part of your `Input` component theme to define specific styles for when the `isLoading` prop is present.

Something like this:

```
extendTheme({
  components: {
    Input: {
      baseStyle: ({ isLoading }) => ({
        field: {
          borderColor: isLoading ? 'green.500' : 'black'
        }
      })
    }
  }
})
```

It's possible we should instead remove this prop from `Input` entirely though, as I'm not sure it will provide much value to anyone.

**Comment by segunadebayo** [comment]
I agree we should remove that `prop` @with-heart. I had it in mind to think of this use-case for future implementations but it doesn't provide any useful value at the moment.

Working on this!

**Comment by segunadebayo** [comment]
Done! It'll be removed in the next release.
