### ISSUE TITLE
Date & time picker components

### ISSUE THREAD

**Issue by ceopaludetto** [chakra-ui/chakra-ui#2612]
# Feature request

## Is your feature request related to a problem? Please describe.

Chakra is awesome and growing every day, bring these components to ecosystem will stimulate new users to come, recently I've searched some implementations of custom designed date pickers that tries to keep consise with chakra ui, they use vanilla css and drop the mutability of css-in-js. https://github.com/chakra-ui/chakra-ui/issues/580.

## Describe the solution you'd like

I imagined a few components such as date picker, time picker, date & time picker and date range picker, they can have agnostic "backend" implementations working with all common date libraries such as moment, dayjs, date-fns and luxon, similar to material-ui pickers. 

## Describe alternatives you've considered

As mentioned above, https://github.com/chakra-ui/chakra-ui/issues/580 the react-datepicker is a solution, but it doesn't bring the common features of chakra and your design-system. Another option is every solution which uses chakra build your own implementation of a date picker or simply use default type"date" input (last one have some visual glitches that cannot be covered https://github.com/chakra-ui/chakra-ui/issues/1786).

**Comment by with-heart** [comment]
Hi @ceopaludetto! I appreciate that you shared the idea and as much as I'd love to say that Chakra can offer its own datepicker (I would LOVE to stop using `react-datepicker`), we're going to pass on this feature request. Building a datepicker that meets our accessibility standards while covering the very long list of use cases is a massive undertaking that we simply don't have the time or energy to implement or support. Hope you understand!

**Comment by iamclaytonray** [comment]
@with-heart - it seems that this is on the roadmap now? https://github.com/chakra-ui/chakra-ui/projects/6#card-70245953
