### ISSUE TITLE
Nextjs build error: `Package subpath './' is not defined by "exports"`

### ISSUE THREAD

**Issue by bwillem** [chakra-ui/chakra-ui#2622]
# Bug report

## Describe the bug

Nextjs build error: `Package subpath './' is not defined by "exports"`

deleting `exports` from `@chakra-ui/react/package.json` fixes the issue.

## To reproduce

use chakra-ui/react components in a nextjs project
run `next build`

## System information

- Version of @chakra-ui/react: 1.0.3
- Version of next: 10.0.3

## Screenshot
<img width="924" alt="Screen Shot 2020-11-25 at 9 27 48 AM" src="https://user-images.githubusercontent.com/5076181/100262585-a22fe580-2f4c-11eb-95c9-4a3c22624ba0.png">

**Comment by with-heart** [comment]
Hi @bwillem! We have multiple NextJS projects run by the Chakra maintainers and none of them have this issue, so we'll need more details about your setup or a reproduction in order to investigate.

**Comment by bwillem** [comment]
Thanks for the reply. It's a typescript project, anyone of said maintainers have a nextjs typescript project working with chakra v1? It started happening after updating to chakra v1.

There's no custom build config, just default nextjs with typescript. Tsconfig can't be changed much, next requires a specific config.

I'll keep puzzling through.

**Comment by bwillem** [comment]
My mistake. It was a very sneaky import in one of my files:

`import { Box } from '@chakra-ui/react/';`

notice the trailing `/`
