### ISSUE TITLE
Issue when ussing Switch inside Modal

### ISSUE THREAD

**Issue by albusphan** [chakra-ui/chakra-ui#2628]
## Describe the bug

When I add Switch component into a Modal which has scrollBehavior="inside", 
If the Modal body is scrollable, toggle the switch make the modal content float to the top.
## Minimal reproduction
https://codesandbox.io/s/pensive-moser-qxyre?file=/src/App.tsx

## Expected behavior

Modal Content not float to the top.

## System information

- OS: macOS Big Sur
- Browser (if applies): Chrome
- Version of @chakra-ui/react: 1.0.1

**Comment by santialbo** [comment]
I'm not sure I'm experiencing what you are describing. I click the switch and nothing happens. I tried both on Chrome and Firefox.

**Comment by albusphan** [comment]
I just take a screen shot for the issue, you can take a look @santialbo 
First initial
<img width="553" alt="Screen Shot 2020-11-27 at 16 00 27" src="https://user-images.githubusercontent.com/58453812/100430755-c6fd9780-30c9-11eb-9f76-aa5567c13774.png">
After click
<img width="552" alt="Screen Shot 2020-11-27 at 16 00 36" src="https://user-images.githubusercontent.com/58453812/100430823-e09edf00-30c9-11eb-893e-02cc28cd45c0.png">

**Comment by santialbo** [comment]
:S that doesn't happen to me on chrome or ff (on a mac). Does it happen to you in other browsers?

**Comment by albusphan** [comment]
hi @santialbo , so sorry, just know what happens, it's because some of my chrome extensions

**Comment by theunexpected1** [comment]
I'm facing the same issue in Chrome, despite disabling all extensions.
Not facing this in Safari.

https://user-images.githubusercontent.com/734385/136674381-f941aaa8-0f44-4fa3-8732-475c36db8703.mov
