### ISSUE TITLE
Motion props are passed to DOM

### ISSUE THREAD

**Issue by kajchang** [chakra-ui/chakra-ui#2629]
# Bug report

## Describe the bug

In `1.0.0-rc.8`, passing motion props to a Chakra component wrapped using `motion.custom` results in the props appearing in the DOM, whereas they don't in `0.8.0`

## To reproduce

Render a Chakra component wrapped using `motion.custom` with motion props.

## Minimal reproduction

[1.0.0-rc.8, motion props are passed to DOM](https://codesandbox.io/s/chakra-framer-props-are-passed-wmf7p)
[0.8.0, motion props aren't passed to DOM](https://codesandbox.io/s/chakra-framer-props-arent-passed-g8ib7?file=/src/App.tsx)

## Expected behavior

The props shouldn't appear in the DOM, like in `0.8.0`.

## Screenshots

**Example:**

This
<img width="362" alt="Screen Shot 2020-11-25 at 10 36 25 PM" src="https://user-images.githubusercontent.com/39450215/100316083-a836be00-2f6e-11eb-950c-d84b84b9406c.png">
Results In
<img width="352" alt="Screen Shot 2020-11-25 at 10 36 40 PM" src="https://user-images.githubusercontent.com/39450215/100316099-b1278f80-2f6e-11eb-9202-592584dbc13b.png">

## System information

- OS: N/A
- Browser (if applies): N/A
- Version of @chakra-ui/react: 1.0.0-rc.8
- Version of Node.js: N/A

## Additional context

I assume this sort of new behavior is intended to some extent, but I don't think these extraneous props should be passed to the DOM when `framer-motion` is being used as intended.

**Comment by TimKolberger** [comment]
Please see #2538
