### ISSUE TITLE
Range Slider

### ISSUE THREAD

**Issue by dannyvaughton** [chakra-ui/chakra-ui#2642]
# Feature request

## Is your feature request related to a problem? Please describe.

There is no way to select an upper and lower value (range) using the slider, which is useful for a lot of applications like a price filter.

## Describe the solution you'd like

Add a new component called Range Slider (or an additional prop which transforms the existing slider) which has two SliderThumbs. One controls the upper limit and the other the lower limit. The Thumbs can't cross over.

The value & defaultValue will accept an array of values `[0, 100]` & the onChange events will also return an array of values.

## Describe alternatives you've considered

Antd have a nice Range Slider.

**Comment by with-heart** [comment]
Definitely think this is a common sense feature to add! I've been working a bit on #2649 and feel like we need to clean that area of the code up a bit to make it easier to add features like this. I'll try to expand the scope a bit to include cleanup.

**Comment by oahmaro** [comment]
I think this feature is really necessary, most apps require a range slider not just a slider.

**Comment by segunadebayo** [comment]
Thanks for the request! Considering this isn't a bug, I'll add this to our project board so you can track the progress.

Check it here: https://github.com/chakra-ui/chakra-ui/projects/6

Cheers.

**Comment by vincentbriglia** [comment]
I'd upvote it but can't see it in the project board?

**Comment by mattssll** [comment]
can't either, i'll have to develop it myself I guess, wondering if I should try to extend the actual slider or just build it with plain js?

**Comment by kotoyama** [comment]
any updates?

**Comment by laurensnl** [comment]
We'd love to have this as well!

**Comment by federicobadini** [comment]
@segunadebayo I can't either find this issue on the project roadmap. 
Is it something that has been removed from it or it simply got untracked?

**Comment by luigiminardim** [comment]
Any updates in this topic?

**Comment by kotoyama** [comment]
I recently found someone's solution and I think it might be a good base if it is developed further:
https://github.com/okupara/daily-components-chakra-ui/tree/master/src/range-slider

**Comment by Vvaradinov** [comment]
Would love to see this be a standard component!

**Comment by 4ortytwo** [comment]
Would love this one as well

**Comment by segunadebayo** [comment]
Thanks for the upvote. We've added this to the list of upcoming features in the roadmap

**Comment by luigiminardim** [comment]
In a personal project that extends Chakra-UI, I've started creating a multi thumb slider that can satisfy the needs for this issue.

The API is looking like this:
```jsx
    <MutltiThumbSlider values={[40, 60, 80, 90]} {...args}>
        <MultiThumbSliderTrack>
                <MultiThumbSliderInnerTrack start={0} end={1} />
                <MultiThumbSliderInnerTrack start={2} end={3} />
        </MultiThumbSliderTrack>
        <MultiThumbSliderThumb index={0} aria-label="start 0" />
        <MultiThumbSliderThumb index={1} aria-label="end 0" />
        <MultiThumbSliderThumb index={2} aria-label="start 1" />
        <MultiThumbSliderThumb index={3} aria-label="end 1" />
    </MutltiThumbSlider>
);
```

I would like to know if this is in the interest of the community so I can share and ask for help.

**Comment by oliviermtl** [comment]
> In a personal project that extends Chakra-UI, I've started creating a multi thumb slider that can satisfy the needs for this issue.
> 
> The API is looking like this:
> 
> ```js
>     <MutltiThumbSlider numThumbs={4} values={[40, 60, 80, 90]} {...args}>
>         <MultiThumbSliderTrack>
>                 <MultiThumbSliderInnerTrack start={0} end={1} />
>                 <MultiThumbSliderInnerTrack start={2} end={3} />
>         </MultiThumbSliderTrack>
>         <MultiThumbSliderThumb index={0} aria-label="start 0" />
>         <MultiThumbSliderThumb index={1} aria-label="end 0" />
>         <MultiThumbSliderThumb index={2} aria-label="start 1" />
>         <MultiThumbSliderThumb index={3} aria-label="end 1" />
>     </MutltiThumbSlider>
> );
> ```
> 
> I would like to know if this is in the interest of the community so I can share and ask for help.

That would be great, please share.

**Comment by luigiminardim** [comment]
I've finished implementing a Multi-Thumb Slider, but I haven't tested it exhaustively yet. I would like to have some help to do more test cases in the Storybook.

The usage API is something like:
```jsx
    <MultiSlider min={0} max={100} step={1}>
      <MultiSliderTrack>
        <MultiSliderFilledTrack startThumbKey={0} endThumbKey={1} />
        <MultiSliderFilledTrack startThumbKey={2} endThumbKey={3} />
      </MultiSliderTrack>
      <MultiSliderThumb thumbKey={0} aria-label="slider 0" defaultValue={0} />
      <MultiSliderThumb thumbKey={1} aria-label="slider 1" defaultValue={25} max={50}/>
      <MultiSliderThumb thumbKey={2} aria-label="slider-2" defaultValue={50} min={50} />
      <MultiSliderThumb thumbKey={3} aria-label="slider-3" defaultValue={75} />
    </MultiSlider>
```

The component is very flexible and allows configurations like the ones shown in the image attachment.
![Screenshot from 2021-09-04 23-26-30 1](https://user-images.githubusercontent.com/37146539/132112911-7bb5b3ba-108f-49e4-b7e9-bc36b4ec7409.png)
