### ISSUE TITLE
AspectBox: doesn't work with Button

### ISSUE THREAD

**Issue by dodas** [chakra-ui/chakra-ui#2643]
# Bug report

## Describe the bug

When using `<Button>` inside `<AspectRatio>`, it works depending on whether there are any style props passed to `<AspectRatio>`.

The problem seems to be the order in which the `<style>` elements are inserted in.
`<AspectRatio>`'s `>*` selector's styling is overriden by `<Button>`'s styling.
## Minimal reproduction

https://codesandbox.io/s/tender-taussig-fbezd?file=/src/App.tsx

```tsx
<ChakraProvider>
  {/* Just to make the example fit into browser window */}
  <Box maxWidth="300px" borderWidth={1} borderColor="red.500">
    {/* Default AspectRatio - doesn't work */}
    <AspectRatio ratio={1 / 1}>
      <Button>Test</Button>
    </AspectRatio>

    {/* AspectRatio with any style prop set - works */}
    <AspectRatio color="red.500" ratio={1 / 1}>
      <Button>Test</Button>
    </AspectRatio>
  </Box>
</ChakraProvider>
```

Edit: v1.1 behaves slightly differently than v1.0, but still buggy. I updated the sandbox and example to reflect v1.1

**Comment by segunadebayo** [comment]
I see that this might be a bug but it feels like the wrong usage of the components though. Any reason you're wrapping Button within AspectRatio?

**Comment by dodas** [comment]
Well, I just want a `Button` that is square.
I have dynamic width and I want each `Button` to be 1/3 of the width and same height.

If this is not intended usage, we should clarify that better in the Docs.

**Comment by segunadebayo** [comment]
Yes, this is not an intended use-case.

Aspect ratio is meant to be used with "media-related" elements like images, videos, and iframes NOT interactive components.

We can definitely update the docs to reflect this but I think it's mentioned in the docs already.

> AspectRatio component is used to embed responsive videos and maps
