### ISSUE TITLE
Skeleton fading on mounting

### ISSUE THREAD

**Issue by delucca** [chakra-ui/chakra-ui#2644]
# Bug report

## Describe the bug

The Skeleton component is always fading upon mounting/remounting even if the `isLoaded` prop is statically set to `true`. In my use case, I have a list that the user can reorder using `react-beautiful-dnd`. That list shows remote data that is fetched from my backend (from a parent component, the component that wraps Skeleton receives only the data directly).

After fetching the data, Skeleton fades and shows it to me (as expected, since I check if there is data in my component to show). But, if I reorder the list it "blinks", because `react-beautiful-dnd` unmount and remounts the lines after reordering.

It seems that Skeleton **always** fadeIn upon mounting. Even if it has an `isLoaded` prop set to true upon mounting.

You can see the behavior I've described above [in this video](https://imgur.com/Vrf5R6y)

## To reproduce

1. Open the [provided Codesandbox](https://codesandbox.io/s/skeleton-fade-on-remounting-ye29d)
2. Clicks on the `Toggle Skeleton` button
3. It should fade
4. Click again
5. Click again
6. It should fade again

## Minimal reproduction

https://codesandbox.io/s/skeleton-fade-on-remounting-ye29d

## Expected behavior

I would like to have a prop that could prevent that. In my opinion, we should be able to define if the `Skeleton` component should fade upon mounting even if the `isLoaded` prop was set to true.

**Comment by ChasinHues** [comment]
I'll try and get a PR in for this this weekend.

**Comment by delucca** [comment]
> @delucca sorry I had another look at this this morning, you can actually achieve no-fade-in effect if you set `fadeDuration={0}`.
> 
> > _Note:_ You have to use `{0}` instead of `"0"` for the value of `fadeDuration` because it accepts a number, not a string.

Hi!

Thanks for replying :)

Yeah, I'm actually using that, but I would like to have the fade effect, without the issue that I've opened (only fading after loading, and not after every mount)

**Comment by Samic8** [comment]
@with-heart Could you assign this one to me, please? I will be able to work on it next Monday/Tuesday

**Comment by Samic8** [comment]
I've got a PR #2775 up to fix this. Let me know what you think. Thanks!
