### ISSUE TITLE
Slider onChangeEnd being called multiple times

### ISSUE THREAD

**Issue by delucca** [chakra-ui/chakra-ui#2649]
# Bug report

## Describe the bug

I need to control my Slider and open a Popover as soon as the user finishes sliding it. To do so, I've created a state in my component that evaluates if the popover should be opened or not.

To make it work, I've added a function to `onChangeEnd` prop that updates my state, enabling the Popover to be displayed.

Since my Slider is controlled (I need to display it's value elsewhere) I have an `onChange` function too, that updates another state (a Recoil state).

I've noticed that in this scenario, the Slider `onChangeEnd` is called multiple times.

## To reproduce

You can check [this sandbox](https://codesandbox.io/s/chakra-slider-onchangeend-multiple-executions-g7v0c) and drag the slider. Open the console and see that for each time you finish dragging, we got a console log twice (instead of once)

## Minimal reproduction

https://codesandbox.io/s/chakra-slider-onchangeend-multiple-executions-g7v0c

## Expected behavior

The Slider component should be able to understand if the `onChangeEnd` was already called, and prevent from doing that twice.

**Comment by with-heart** [comment]
Spent ~1 hour looking at this. Needed to familiarize myself with the `useSlider` code again and working on figuring out how to test mouse and touch events. Will post further updates as I have more time.

**Comment by TimKolberger** [comment]
useCallback for the onChangeEnd handler on the using side should help with this.

**Comment by delucca** [comment]
I've tried to change how my component is structured, but I always stumble upon the same issues:

1. The `onChangeEnd` is triggered every time the component rerenders (even if the original `value` props are the same as the previous one)
2. Since I'm opening a Popover when I hot-reload my app (change any file) it instantly opens ALL popovers and enters in an infinite loop that freezes my machine.
3. Every time the `onChangeEnd` is executed, it is executed twice (if I change my component state)

**Comment by delucca** [comment]
Just to give more info regarding my setup, I basically have three components now:

`container.tsx` (I don't like using containers too much, but since this is a pretty complex component, it helped me make the structure smoother)
```tsx
import { remove } from 'lodash'
import React from 'react'
import { useRecoilState, useRecoilValue } from 'recoil'

import { Slider } from 'components/Base'
import { KeyResult, ProgressReport } from 'components/KeyResult/types'
import { buildPartialSelector } from 'state/recoil/key-result'

import ProgressSliderComponent from './component'

export interface ProgressSliderContainerProperties {
  id?: KeyResult['id']
  isPopoverGuarded?: boolean
}

const initialValueSelector = buildPartialSelector<KeyResult['initialValue']>('initialValue')
const goalSelector = buildPartialSelector<KeyResult['goal']>('goal')
const formatSelector = buildPartialSelector<KeyResult['format']>('format')
const progressReportsSelector = buildPartialSelector<KeyResult['progressReports']>(
  'progressReports',
)
const confidenceReportsSelector = buildPartialSelector<KeyResult['confidenceReports']>(
  'confidenceReports',
)

const ProgressSliderContainer = ({ id, isPopoverGuarded }: ProgressSliderContainerProperties) => {
  const [progressReports, setProgressReports] = useRecoilState(progressReportsSelector(id))
  const confidenceReports = useRecoilValue(confidenceReportsSelector(id))
  const initialValue = useRecoilValue(initialValueSelector(id))
  const goal = useRecoilValue(goalSelector(id))
  const format = useRecoilValue(formatSelector(id))

  const isLoaded = Boolean(goal)

  const handleSliderUpdate = (valueNew?: number): void => {
    if (valueNew) {
      const previousReport = progressReports?.[0]
      const newLocalReport = {
        valueNew,
        valuePrevious: previousReport?.valueNew,
      }

      setProgressReports(remove([newLocalReport as ProgressReport, ...(progressReports ?? [])]))
    }
  }

  const handleSliderUpdateEnd = (newValue: number | number[]) => {
    console.log('ok')
    const newKeyResultPartial = { progress: newValue as number, id }
    // Await updateRemoteKeyResult(id, newKeyResultPartial)
  }

  return isLoaded ? (
    <ProgressSliderComponent
      isPopoverGuarded={isPopoverGuarded}
      latestProgressReport={progressReports?.[0]}
      latestConfidenceReport={confidenceReports?.[0]}
      initialValue={initialValue as KeyResult['initialValue']}
      goal={goal as KeyResult['goal']}
      format={format}
      handleSliderUpdate={handleSliderUpdate}
      handleSliderUpdateEnd={handleSliderUpdateEnd}
    />
  ) : (
    <Slider isDisabled />
  )
}

export default ProgressSliderContainer
```

`component.tsx`
```tsx
import React from 'react'

import Slider from 'components/Base/Slider'
import { SliderProperties } from 'components/Base/Slider/slider'
import { selectConfidenceTag } from 'components/KeyResult/ConfidenceTag/selectors'
import { KeyResult, ProgressReport } from 'components/KeyResult/types'

import { ConfidenceReport } from '..'

import PopoverGuard from './popover-guard'
import { selectProgressStep } from './selectors'

export interface ProgressSliderComponentProperties {
  initialValue: KeyResult['initialValue']
  goal: KeyResult['goal']
  handleSliderUpdate: SliderProperties['onChange']
  handleSliderUpdateEnd: SliderProperties['onChangeEnd']
  isPopoverGuarded?: boolean
  latestProgressReport?: ProgressReport
  latestConfidenceReport?: ConfidenceReport
  format?: KeyResult['format']
}

const ProgressSlider = ({
  latestProgressReport,
  latestConfidenceReport,
  initialValue,
  goal,
  format,
  handleSliderUpdate,
  handleSliderUpdateEnd,
  isPopoverGuarded,
}: ProgressSliderComponentProperties) => {
  const currentProgress = latestProgressReport?.valueNew ?? 0
  const currentConfidence = latestConfidenceReport?.valueNew ?? 50

  const { color } = selectConfidenceTag(currentConfidence)
  const step = selectProgressStep(format)

  return isPopoverGuarded ? (
    <PopoverGuard
      Slider={Slider}
      value={currentProgress}
      trackColor={color}
      min={initialValue}
      max={goal}
      step={step}
      onChange={handleSliderUpdate}
      onChangeEnd={handleSliderUpdateEnd}
    />
  ) : (
    <Slider
      value={currentProgress}
      trackColor={color}
      min={initialValue}
      max={goal}
      step={step}
      onChange={handleSliderUpdate}
      onChangeEnd={handleSliderUpdateEnd}
    />
  )
}

export default ProgressSlider
```

and `popover-guard.tsx`
```tsx
import {
  Popover,
  PopoverCloseButton,
  PopoverContent,
  PopoverHeader,
  PopoverTrigger,
} from '@chakra-ui/react'
import React, { ComponentType, useState } from 'react'

import { SliderProperties } from 'components/Base/Slider/slider'

export interface PopoverGuardProperties extends SliderProperties {
  Slider: ComponentType<SliderProperties>
}

const PopoverGuard = ({ Slider, onChangeEnd, value, ...rest }: PopoverGuardProperties) => {
  const [isOpen, setIsOpen] = useState(false)

  const handleSliderUpdateEnd = (newValue: number) => {
    console.log(value, newValue)
    if (!isOpen) setIsOpen(true)
    if (onChangeEnd) onChangeEnd(newValue)
  }

  const handleClose = () => setIsOpen(false)

  return (
    <Popover isOpen={isOpen} onClose={handleClose}>
      <PopoverTrigger>
        <Slider onChangeEnd={handleSliderUpdateEnd} value={value} {...rest} />
      </PopoverTrigger>
      <PopoverContent>
        <PopoverHeader>Atualize seu progresso</PopoverHeader>
        <PopoverCloseButton />
        Teste
      </PopoverContent>
    </Popover>
  )
}

export default PopoverGuard
```

The `import { Slider } from 'components/Base'` is basically a component that creates a Slider with Thumb and custom track. In any case, here is the code:
```tsx
import {
  Slider as ChakraSlider,
  SliderFilledTrack,
  SliderProps,
  SliderThumb,
  SliderTrack,
  Tooltip,
} from '@chakra-ui/react'
import React, { forwardRef } from 'react'
import { useIntl } from 'react-intl'

import messages from './messages'

export interface SliderProperties extends SliderProps {
  trackColor?: string
}

const Slider = forwardRef<HTMLDivElement, SliderProperties>(
  ({ trackColor, ...rest }: SliderProperties, forwardedReference) => {
    const intl = useIntl()

    return (
      <ChakraSlider role="group" focusThumbOnChange={false} {...rest}>
        <SliderTrack ref={forwardedReference} h="8px" bg="gray.100" borderRadius="full">
          <SliderFilledTrack bg={trackColor} borderRadius="full" />
        </SliderTrack>

        <Tooltip label={intl.formatMessage(messages.updateLabel)} placement="top">
          <SliderThumb
            bg={trackColor}
            borderColor="white"
            borderWidth={2}
            w="22px"
            h="22px"
            transition="0.2s opacity ease-in-out"
            opacity={0}
            _groupHover={{ opacity: 1 }}
          />
        </Tooltip>
      </ChakraSlider>
    )
  },
)

export default Slider
```

**Comment by delucca** [comment]
Also, if you guys think it can help, my project is open sourced, so you can check how it works entirely [here](https://github.com/delucca/execution-mode/tree/39f949f353a4187b9363189b0309ad26874a05cb/src/components/KeyResult/ProgressSlider)

**Comment by TimKolberger** [comment]
I added some useCallbacks in your [codesandbox](https://codesandbox.io/s/chakra-slider-onchangeend-multiple-executions-forked-jdlrg?file=/src/App.tsx)

**Comment by delucca** [comment]
@timkindberg hm 🤔  nice idea.

I'm going to try that

**Comment by delucca** [comment]
But, in any case, I think `chakra` should be able to handle it without the need to `useCallback`

**Comment by TimKolberger** [comment]
The inline functions `handleSliderUpdateEnd` and `handleClose ` are recreated on every render, so they are always "fresh". Because of that `Slider` is not able to tell if the value or the handler function just changed, and calls it with the new value.

useCallback updates the handlerFunction only when a value in its dependency array changes.

**Comment by delucca** [comment]
Oh, I see. But, in any case, `useCallback` made `handleSliderUpdateEnd` to trigger just one, but now it is preventing it from mutating the state itself, therefore the Popover don't open Oo:

```tsx
  const handleSliderUpdateEnd = useCallback(
    (newValue: number) => {
      if (!isOpen) setIsOpen(true)
      if (onChangeEnd) onChangeEnd(newValue)
    },
    [value],
  )
```

And, if I add `isOpen` to the second arg of `userCallback`, the loop begins again

**Comment by TimKolberger** [comment]
You need to let useCallback know, when it should update the function. You do this by passing the dependency array.
Currently there is only `value` in there. But now it depends on `onChangeEnd` as well. See the React docs for further reference: https://reactjs.org/docs/hooks-reference.html#usecallback
The `setIsOpen` is a special case, because this function reference will never update, because it is the setter function from `React.setState`

```jsx
 const handleSliderUpdateEnd = useCallback(
    (newValue: number) => {
      if (!isOpen) setIsOpen(true)
      if (onChangeEnd) onChangeEnd(newValue)
    },
  [value, onChangeEnd],
)
```

**Comment by delucca** [comment]
@timkindberg yeah, but as soon as I let `useCallback` know about `isOpen` the issue returns. I don't know why. I'm trying to investigate your fix in my codesandbox to understand the difference

**Comment by delucca** [comment]
I think it is related to the Popover itself. I'm changing my codesandbox. After the issue happens, everytime I click (anywhere in the page) the console log appears too.

**Comment by TimKolberger** [comment]
You need to lift the state `isOpen` up to get rid of this. And the modal component could move up as well. 
Please see https://reactjs.org/docs/lifting-state-up.html

Because this is not an issue with the Slider component I am closing this.

**Comment by delucca** [comment]
@timkindberg here is the problem: https://codesandbox.io/s/chakra-slider-onchangeend-multiple-executions-g7v0c?file=/src/App.tsx

**Comment by delucca** [comment]
I'm going to try to lift the state up. But, I think I've already tried that and it did not work.

In any case, I'm going to check again. If you could please check the code sandbox I've just sent and see if you can identify the problem.

**Comment by delucca** [comment]
Just lifted the state up to the parent component, the issue remains :/

**Comment by delucca** [comment]
Also, in the example I've send at codesandbox, the entire state is at the same level and I'm using `useCallback`, but the issue remains. I don't think the issue is related to the state position in the tree.

**Comment by TimKolberger** [comment]
The slider thumb and the popover both wants to do focus management. So the Popover opens, and closes in the next render.  

I removed the component `PopoverTrigger`, as you are managing your own isOpen state, and do not need another component interfering with that. See this [codesandbox](https://codesandbox.io/s/chakra-slider-onchangeend-multiple-executions-forked-zbzju?file=/src/App.tsx)

Now we have the state management and the focus management under control :tada:

**Comment by delucca** [comment]
Thanks :)

In any case, I've followed your suggestion and moved the `isOpen` to the Recoil layer. I rewrote the entire component but now it is working as expected.

**Comment by delucca** [comment]
For future reference my mistake was the following:

I was trying to set the popover state at the same level, or below, at the `value` of my progress slider state. So, that locked me into an infinite loop.

After lifting the popover state above (to the Recoil layer) all problems were fixed :)

Thanks for your help guys!
