### ISSUE TITLE
ColorScheme "whatsapp" does not represent the correct brand color

### ISSUE THREAD

**Issue by AO19** [chakra-ui/chakra-ui#2652]
# Bug report

## Describe the bug

ColorScheme WhatsApp should represent the correct brand color (https://whatsappbrand.com/#color)

## To reproduce

```ts
<IconButton
  colorScheme="whatsapp"
  aria-label="WhatsApp"
  icon={<FaWhatsapp />}
/>
```

## Minimal reproduction

https://codesandbox.io/s/wrong-whatsapp-brand-color-sfyvt?file=/src/App.tsx

## Expected behavior

The color should be #25D366 light green (https://whatsappbrand.com, navigate to `color`), not teal.

https://smart-swatch.netlify.app/#25D366

## Screenshots

![image](https://user-images.githubusercontent.com/33397118/100516178-67af8e00-3182-11eb-8438-9b37d21a3475.png)

![image](https://user-images.githubusercontent.com/33397118/100516188-75651380-3182-11eb-9fbc-6926ed041a1b.png)

## System information

- OS: Windows 10
- Browser: all
- Version of @chakra-ui/react: 1.0.0
- Version of Node.js: all

**Comment by dodas** [comment]
Currently all these brand colors are undocumented in Chakra UI docs.
In my opinion they all should be removed from default Chakra UI theme instead of trying to keeping them up to date with official brand guidelines.

**Comment by AO19** [comment]
They are partially documented here: https://chakra-ui.com/docs/form/button#social-buttons. But I understand your concern, it is still nice to have.

**Comment by dodas** [comment]
Removing those colors would be a breaking change, so maybe it would be better to leave it for a major release?
Until then, we can just fix the incorrect color...

**Comment by with-heart** [comment]
@dodas Agreed. I'm not really sure why we have the social media color schemes in there. Seems like they'd be better as optional theme extensions somehow. It'd be interesting to know how many people are actually using them.

**Comment by segunadebayo** [comment]
@with-heart, the social media color scheme was leftover from Careerlyft, the project that initiated Chakra UI.

I agree it shouldn't really be a part of the core Chakra UI colors and we'll make a note to remove it in our next major release. For now, we leave it there.

Good points @dodas

**Comment by rahrang** [comment]
Is there a way to remove these color schemes via the `extendTheme` function? I've tried setting them to - `null`, which causes a TypeScript error
- `undefined`, and `{}`, which get overwritten by the color schemes from Chakra
