### ISSUE TITLE
[Slider] Add tests for mouse+touch events

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#2655]
This component can be interacted with in a number of ways but only keyboard events are tested. I think we could do a decent bit of cleanup and refactoring on the code for this component, but we need the safety of a test suite before performing that work.

**Comment by with-heart** [comment]
Going to reopen this as it would have caught #3040. We should have tests though it sounds like a real pain to implement.

**Comment by segunadebayo** [comment]
Given that no action has been taken on this issue, I'm closing it for now.
