### ISSUE TITLE
[Switch]: feedback could be improved by using similar cursor styles from Button

### ISSUE THREAD

**Issue by aaronmcadam** [chakra-ui/chakra-ui#266]
## Is your feature request related to a problem? Please describe.

I think we should add cursor styles similar to buttons. Hovering over a switch does not change the cursor. Also, a disabled switch does not change its cursor either.

Here's a codesandbox demo: https://codesandbox.io/s/chakra-js-starter-owv1h

## Describe the solution you'd like

I think having cursor styles similar to `Button` would help.

## Describe alternatives you've considered

I've had to add the styles myself.

## Additional context

Codesandbox: https://codesandbox.io/s/chakra-js-starter-owv1h

**Comment by segunadebayo** [comment]
Thanks for this feedback @aaronmcadam. I'll look into it.

**Comment by aaronmcadam** [comment]
Thanks @segunadebayo!
