### ISSUE TITLE
SlideFade Props offsetX and offsetY has different types from the documentation

### ISSUE THREAD

**Issue by carldegs** [chakra-ui/chakra-ui#2662]
# Bug report

## Describe the bug
Based on the [documentation](https://chakra-ui.com/docs/components/transitions#slidefade-props), `offsetX` and `offsetY` should be a string but the actual type is a number.

## To reproduce

1. Import and use `SlideFade`
2. add `offsetX` or `offsetY` props and set the value to the default value based on the documentation "20px".
3. Typescript would show error
```
Type 'string' is not assignable to type 'number | undefined'.ts(2322)
slide-fade.d.ts(12, 5): The expected type comes from property 'offsetY' which is declared here on type 'IntrinsicAttributes & SlideFadeProps & RefAttributes<HTMLDivElement>'
```
## Minimal reproduction

https://codesandbox.io/s/blazing-waterfall-e0qp5

## Expected behavior

`offsetX` and `offsetY` should be a string or the documentation should be updated to change their types into a number.

## System information

- OS: Windows 10
- Version of @chakra-ui/react: 1.0.1
- Version of Node.js: 12.19.0

**Comment by with-heart** [comment]
Hi @carldegs, thanks for the bug report! This changed when we moved to `framer-motion` for animations. That library can handle a large number of types, so we need to revisit how we're implementing the types for our components to support all possible `framer-motion` values.

**Comment by jvmazagao** [comment]
@with-heart this is very strange, in the documentation, the offsetX and offsetY are strings, and in code is numbers, I will fix in my pr, change only to strings.
