### ISSUE TITLE
Can't override `shouldForwardProp`

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#2670]
# Bug report

## Describe the bug

When using the `chakra` factory function, users should be able to pass a custom `shouldForwardProp` function to replace that functionality for their custom component.

## Minimal reproduction

https://codesandbox.io/s/distracted-cloud-ncioj?file=/src/App.tsx

## Expected behavior

Base `div` element should not have `hello="true"` attribute attached.

## Additional context

Users can specify the `shouldForwardProp` option, but it is always overridden inside `styled`.

https://github.com/chakra-ui/chakra-ui/blob/b5f1211d2093727e9733d2c6f2728adce3338676/packages/system/src/system.ts#L128-L139

**Comment by jvmazagao** [comment]
I will try to fix it, assign to me

**Comment by with-heart** [comment]
Should be an easy one! 😄

**Comment by jvmazagao** [comment]
@with-heart Based on your issue when the shouldForwardProp are passed to the CustomComponent if the props.hello are passed, they will show an error in the component right?

**Comment by with-heart** [comment]
@jvmazagao Nope! `shouldForwardProp` just determines whether a prop is also forwarded to the underlying html element or not. So in this case, `<div hello="true" class="css-0">` is rendered, but it should just be `<div class="css-0">` since `shouldForwardProp` returns `false` for `hello`.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly
