### ISSUE TITLE
Merge built-in `shouldForwardProp` results with custom `shouldForwardProp`

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#2671]
# Feature request

## Is your feature request related to a problem? Please describe.

The `shouldForwardProp` option for the `chakra` function (when it's working as intended—see #2670) replaces the built-in `shouldForwardProp` call, which means all props will be forwarded by default.

## Describe the solution you'd like

Similar to how `extendTheme` uses `mergeWith` to enable functions defined in the default `theme` to be merged with functions defined in a custom `theme`, user-provided `shouldForwardProp` option to `chakra` function should be merged with the default `shouldForwardProp` call. This allows a user to _extend_ the `shouldForwardProp` definition rather than replacing it, which is fairly useless functionality imo.

**Comment by segunadebayo** [comment]
Too many duplicates of this issue. Closing this even though I'm working on it at the moment.
