### ISSUE TITLE
Alert Icon shrinks with long text

### ISSUE THREAD

**Issue by scisteffan** [chakra-ui/chakra-ui#2672]
# Bug report

## Describe the bug

When I add a lot of text to the alert component, the alert icon shrinks in size.

## To reproduce

1. Create an alert component with an icon
2. Add lots of text to the alert
3. See alert icon size shrinks with large amount of text

## Minimal reproduction

https://codesandbox.io/s/objective-morse-j2qni?file=/src/App.js

## Expected behavior

Alert icon to remain the same size

## Screenshots

<img width="756" alt="Screenshot 2020-11-30 at 14 22 12" src="https://user-images.githubusercontent.com/2676185/100621424-9317b180-3317-11eb-866c-ed855d756989.png">

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of @chakra-ui/react: 1.0.0
- Version of Node.js: 12.16.3

## Additional context

None

**Comment by Jivvon** [comment]
You can use <chakra.div> tag separate from the content(AlertDescription) for it.

```javascript
import { chakra } from '@chakra-ui/system';
...
<Alert>
  <chakra.div flex="1">
    <AlertIcon />
    <AlertTitle>404</AlertTitle>
  </chakra.div>
  <AlertDescription>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut hendrerit
    accumsan ipsum sit amet mollis. Nam eu erat eu lorem tristique
    maximus. Nullam eu est ex. Nullam aliquet fringilla tellus a commodo.{' '}
  </AlertDescription>
</Alert>
```

**Comment by scisteffan** [comment]
Cool, that seems to work! So it's not a bug, then?

**Comment by dodas** [comment]
I think the correct default behaviour should be to prevent icon shrinking.
I have sent a PR that fixes it.

**Comment by Jivvon** [comment]
@dodas Come to think about it, it might be the better behavior that you did.
Thank you 👍
