### ISSUE TITLE
[PinInput] Support alphanumeric pins

### ISSUE THREAD

**Issue by garrettjoecox** [chakra-ui/chakra-ui#2679]
I'd like to propose supporting alphanumeric pins in the PinInput component. Limiting to digits seems to be an arbitrary restriction pulled from the referenced `pin-code` from Uber[[1]](https://github.com/uber/baseweb/blob/master/src/pin-code/pin-code.js#L115). I think this could either come as a prop configuration or simply changing the existing regex[[2]](https://github.com/chakra-ui/chakra-ui/blob/453db5e2bf788f51fc88387d2c9d185b911d4e44/packages/pin-input/src/use-pin-input.ts#L249) to alphanumeric.

[1] https://github.com/uber/baseweb/blob/master/src/pin-code/pin-code.js#L115
[2] https://github.com/chakra-ui/chakra-ui/blob/453db5e2bf788f51fc88387d2c9d185b911d4e44/packages/pin-input/src/use-pin-input.ts#L249

**Comment by abelHodasz** [comment]
Could you maybe add support to other languages as well? Right now the alphanumeric values can only be English letters, and there's no way to change that.
