### ISSUE TITLE
[Divider] responsive styles not working

### ISSUE THREAD

**Issue by shoxton** [chakra-ui/chakra-ui#2686]
# Bug report

`<Divider />` its not working correctly when using responsive styles on the `orientation` property

This works:

`<Divider />`
`<Divider orientation="horizontal" />`
`<Divider orientation="vertical" />`

This **does not** work:

`<Divider orientation={{base: "horizontal", md: "vertical"}} />`

## To reproduce

Use [reponsive styles ](https://chakra-ui.com/docs/features/responsive-styles) on `orientation` property on the divider component

## Minimal reproduction

https://codesandbox.io/s/charming-silence-j4kup?file=/src/App.js

## Expected behavior

Vertical divider on large screens 
Horizontal divider on small screens

using responsive styles

## System information

- OS: Ubuntu 20.04.1 LTS
- Browser: Version 87.0.4280.66 (Official Build) (64-bit)
- Version of @chakra-ui/react: ^1.0.1
- Version of Node.js: v15.0.1

**Comment by with-heart** [comment]
Hi @shoxton! Thanks for reporting. Chakra currently doesn't support responsive props for the "theming" props, which includes `orientation`. I've added `orientation` to #1028 for future support for this. In the meantime, you can use `useBreakpointValue`. There's an example of that for `size` in the linked issue, and it would work similarly for `orientation`.

Going to close this as the other issue now covers this functionality.

**Comment by shoxton** [comment]
Thanks!
