### ISSUE TITLE
[Box] TS error when assiging a typed ref to Box

### ISSUE THREAD

**Issue by diedu89** [chakra-ui/chakra-ui#2687]
# Typed ref on Box component

## Describe the bug

When using the box component and trying to pass a typed react ref according to `as` prop, it complains about type mismatch since `Box` component is not generic

## To reproduce

pass a typed ref to `Box` component

```
  const boxRef = React.useRef<HTMLSpanElement>(null);
...
  <Box as="span" ref={boxRef}>
```

TS error: `Type 'RefObject<HTMLSpanElement>' is not assignable to type 'string | ((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined'.
  Type 'RefObject<HTMLSpanElement>' is not assignable to type 'RefObject<HTMLDivElement>'.
    Property 'align' is missing in type 'HTMLSpanElement' but required in type 'HTMLDivElement'.`

## Minimal reproduction

https://codesandbox.io/s/box-typed-ref-27mkm

## Expected behavior

Maybe make `Box` generic so we can type it, something like this: `<Box<HTMLSpanElement> />`, not sure if it can take the type from `as` prop :thinking:

**Comment by ChasinHues** [comment]
Hi @diedu89, I think TS is complaining because `Box` renders a `div` element in the DOM, whereas your ref is expecting to be on a `span`. 

I think the [chakra factory](https://chakra-ui.com/docs/features/chakra-factory) might be what you're after.

If the aim is to add a ref onto a component that is a span but to have access to chakra props, you can replace `Box` with `chakra.span` instead. 

Does this help?

**Comment by diedu89** [comment]
Yes, it does help, thank you. However, I still think that the `ref` typing for `Box` is a little inconsistent since `as` prop allows to render a component other than `div`

**Comment by ChasinHues** [comment]
Ah yeah I see what you mean. The `Box` renders a `span` so all works as expected, but TS complains because, for whatever reason, it can't infer that `<Box as="span" />` is actually going to render a `span` as opposed to a `div`.

**Comment by tomhicks** [comment]
Having the same thing here with `<Stack as="form">`. It looks as though there is an attempt in the types to make them pick up the types from the `as` prop, but it's not working.

**Comment by diedu89** [comment]
keep it open

**Comment by chinanderm** [comment]
Keep this open please.
