### ISSUE TITLE
Hover backgroundColor dosen't apply on ListItem

### ISSUE THREAD

**Issue by ProsperDevelopment** [chakra-ui/chakra-ui#269]
**Describe the bug**
The hover backgroundColor on ListItem with a set backgroundColor doesn't apply.

**Expected Behavior**
Hover should change background

**To Reproduce**

Import PseudoBox and add this story to the List example file and try it in storybook
```
stories.add("Styled with background hover and icons", () => (
  <Box mb={6}>
    <List spacing={3}>
    <PseudoBox _hover={{ backgroundColor: 'blue.700' }}>
      <ListItem backgroundColor='green.500'>
        <ListIcon icon={SampleIcon} color="green.500" />
        Lorem ipsum dolor sit amet, consectetur adipisicing elit
      </ListItem>
      </PseudoBox>
      <ListItem>
        <ListIcon icon="phone" color="green.500" />
        Assumenda, quia temporibus eveniet a libero incidunt suscipit
      </ListItem>
    </List>
  </Box>
));
```

**Comment by segunadebayo** [comment]
Hi @ProsperDevelopment. Can you try the `bg` prop instead?

**Comment by ProsperDevelopment** [comment]
No difference with `bg`.

The problem seems to be when using the theme color strings in the ListItem. Works if we use an variable or hard coded color. 

As workaround we import the theme and use ` theme.colors.mashieblue[400];` in our code.

**Comment by segunadebayo** [comment]
I just looked into this. The `ListItem` itself uses `PseudoBox` internally. So you can just do this, and it'll work:

```jsx
stories.add("Styled with background hover and icons", () => (
  <Box mb={6}>
    <List spacing={3}>
      <ListItem
        backgroundColor="green.500"
        _hover={{ backgroundColor: "blue.700" }}
      >
        <ListIcon icon={SampleIcon} color="green.500" />
        Lorem ipsum dolor sit amet, consectetur adipisicing elit
      </ListItem>
      <ListItem>
        <ListIcon icon="phone" color="green.500" />
        Assumenda, quia temporibus eveniet a libero incidunt suscipit
      </ListItem>
    </List>
  </Box>
));
```

I've tested this in Storybook and it works. Kindly confirm

**Comment by ProsperDevelopment** [comment]
Yes thanks, we totally missed the fact that the <li> element was composed by a PseudoBox. Great!
