### ISSUE TITLE
Tooltips open inconsistently on mobile

### ISSUE THREAD

**Issue by ianwalter** [chakra-ui/chakra-ui#2691]
# Bug report

## Describe the bug

On iOS Safari, tooltips sometimes don't get triggered on touch. I can reproduce this in the documentation examples where some of the examples don't seem to work at all.

## To reproduce

1. Go to 'https://chakra-ui.com/docs/overlay/tooltip' on iOS Safari
2. Tap around on 'tooltip examples'
3. Notice that some are sometimes not triggered and that some are not triggered at all

## Expected behavior

That tooltips get triggered and displayed every time they are touched.

## System information

- OS: latest iOS
- Browser (if applies): Safari
- Version of @chakra-ui/react: 1.0.1
- Version of Node.js: 14.15.1

**Comment by abagshaw** [comment]
Are there any updates on this? Experiencing the same problem.

**Comment by alevosia** [comment]
Tooltips are click/mouse-based. You can make it work with touch devices by manually setting the `isOpen` prop of Tooltip and set the value `onMouseEnter`, `onMouseLeave`, and `onClick` (handles touch event as well) on the element the Tooltip is wrapping.

Something like this:
```ts
const Pin: FC<PinProps> = ({ label }) => {
    const [isLabelOpen, setIsLabelOpen] = useState(false)

    return (
        <Tooltip label={label} isOpen={isLabelOpen}>
            <Image
                src="/images/map_pin.svg"
                alt={label}
                onMouseEnter={() => setIsLabelOpen(true)}
                onMouseLeave={() => setIsLabelOpen(false)}
                onClick={() => setIsLabelOpen(true)}
            />
        </Tooltip>
    )
}
```

**Comment by abagshaw** [comment]
Why would tooltips not have this functionality built in by default? Bit of a pain to have to do this on every tooltip I create. Don't see any reason why this shouldn't be default behaviour.

**Comment by alevosia** [comment]
> Are there any updates on this? Experiencing the same problem.

Tooltips, in the field UI, are meant to be a brief, informative message that shows up to guide the user what a UI element is or what it does when interacted with. A touch event means you already interacted with the UI and a toltip is not meant to be used as a feedback to an action.

In the world of touch, it is usually advised to provide a different form of providing information other than Tooltips. More here: [Tooltips in the Era of Touch](https://medium.com/smarter-workforce-design/tooltips-in-the-era-of-touch-5268615bf321). Fortunately, the Chakra team allows us to extend this functionality by setting the `isOpen` props of the component.

**Comment by alevosia** [comment]
> Why would tooltips not have this functionality built in by default? Bit of a pain to have to do this on every tooltip I create. Don't see any reason why this shouldn't be default behaviour.

Tooltips, in the field UI, are meant to be a brief, informative message that shows up when the cursor hovers it to guide the user what a UI element is or what it does when interacted with. A touch event means you already interacted with the UI and a toltip is not meant to be used as a feedback to an action.

In the world of touch, it is usually advised to provide a different form of providing information other than Tooltips. More here: [Tooltips in the Era of Touch](https://medium.com/smarter-workforce-design/tooltips-in-the-era-of-touch-5268615bf321). Fortunately, the Chakra team allows us to extend this functionality by setting the `isOpen` props of the component.

**Comment by alevosia** [comment]
> Why would tooltips not have this functionality built in by default? Bit of a pain to have to do this on every tooltip I create. Don't see any reason why this shouldn't be default behaviour.

Tooltips, in the world of UI, are meant to be a brief, informative message that shows up when the cursor hovers it to guide the user what a UI element is or what it does when interacted with. A touch event means you already interacted with the UI and a tooltip is not meant to be used as a feedback to an action.

In the world of touch, it is usually advised to provide a different form of presenting information other than Tooltips. More here: [Tooltips in the Era of Touch](https://medium.com/smarter-workforce-design/tooltips-in-the-era-of-touch-5268615bf321) / [Tooltip Definition by techterms.com](https://techterms.com/definition/tooltip). 

Fortunately, the Chakra team allows us to extend this functionality by setting the `isOpen` props of the component. Also, you don't have to do it for every Tooltip. You can always make it your own `<TouchFriendlyTooltip />` that wraps the Chakra Tooltip. :)

**Comment by alevosia** [comment]
> Why would tooltips not have this functionality built in by default? Bit of a pain to have to do this on every tooltip I create. Don't see any reason why this shouldn't be default behaviour.

Tooltips, in general, are meant to be a brief, informative message that shows up when the cursor hovers it to guide the user what a UI element is or what it does when interacted with. A touch event means you already interacted with the UI and a tooltip is not meant to be used as a feedback to an action.

In the world of touch, it is usually advised to provide a different form of presenting information other than Tooltips. More here: [Tooltips in the Era of Touch](https://medium.com/smarter-workforce-design/tooltips-in-the-era-of-touch-5268615bf321) / [Tooltip Definition by techterms.com](https://techterms.com/definition/tooltip). 

Fortunately, the Chakra team allows us to extend this functionality by setting the `isOpen` props of the component. Also, you don't have to do it for every Tooltip. You can always make it your own `<TouchFriendlyTooltip />` that wraps the Chakra Tooltip. :)

**Comment by matchu** [comment]
I was surprised by this too! One thing I notice is that the examples and API seem to _encourage_ the pattern of using a tooltip to share extra information on a non-interactive icon, through `shouldWrapChildren`. So I was a bit confused when I discovered later that this pattern doesn't work on mobile, since tooltips for non-interactive elements seemed to be part of the intended the design.

I also notice that tooltips with delays before opening _do_ seem to open correctly, and sometimes even in the standard failure case, I notice a flicker of the tooltip opening and re-closing.

These two facts together make me wonder if, despite the limitations of tooltips in touch design, this could be an implementation oversight rather than an intentional design decision. If so, it'd be useful to me to fix it! 😁😅

Or, if touch events are intentionally not supported, I wonder if it could be useful to clarify this in the docs, and make the touch behavior more consistent.

**Comment by segunadebayo** [comment]
At the moment, we don't recommend using tooltips on mobile because we think it's a bad UX. Don't hide relevant information in a tooltip, especially on mobile. Tooltips should be used to provide "supplementary" information.

We'll update the docs to explain this better.

Read more:
https://ux.stackexchange.com/questions/98628/how-can-i-display-tool-tips-on-a-touchscreen-or-is-there-a-better-way

**Comment by matchu** [comment]
Thanks, makes sense! Appreciate the work and the clarity! 💛

On March 14, 2021, GitHub ***@***.***> wrote:
> At the moment, we don't recommend using tooltips on mobile because we
> think it's a bad UX. Don't hide relevant information in a tooltip,
> especially on mobile. Tooltips should be used to provide
> "supplementary" information.
>
> We'll update the docs to explain this better.
>
> Read more:
>  <https://ux.stackexchange.com/questions/98628/how-can-i-display-tool-
> tips-on-a-touchscreen-or-is-there-a-better-way>
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/chakra-ui/chakra-ui/issues/2691#issuecomment-
799353335>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAOOUSSZFA2Y4QDNH6HXALTDXXH7ANCNFSM4UKS75LQ>.

**Comment by AndreyPatseiko** [comment]
I created my own tooltip wrapper for this. Thanks for your advice @ianwalter.

     export const TooltipWithTouch = ({ children, ...restToolTipProps }: { children: ReactNode; [key: string]: any })  =>  {
        const [isLabelOpen, setIsLabelOpen] = useState(false);

        return (
           <Tooltip isOpen={isLabelOpen} {...restToolTipProps}>
              <Box
                  onMouseEnter={() => setIsLabelOpen(true)}
                  onMouseLeave={() => setIsLabelOpen(false)}
                  onClick={() => setIsLabelOpen(true)}
              >
               {children}
             </Box>
          </Tooltip>
        );
    };`

**Comment by aerinsol** [comment]
Hey, is there any chance we can include this "not recommended for mobile" in the main docs for both v1 and current version? 

https://v1.chakra-ui.com/docs/components/overlay/tooltip
https://chakra-ui.com/docs/components/tooltip

We used this in an important mobile design, but we would have avoided this had we known this issue existed.
