### ISSUE TITLE
Investigate reducing `framer-motion` bundle size

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#2693]
`framer-motion` provides an API for reducing the bundle size by importing the `m` component and adding functionality to it as needed. This could possibly reduce the bundle size for Chakra consumers, as we'd only be including the specific pieces of functionality we're using in our library rather than the entirety of `framer-motion`.

https://www.framer.com/api/motion/guide-reduce-bundle-size/

**Comment by anki247** [comment]
Currently there is a bug report... at least bundle size stays pretty much the same. 
[https://github.com/framer/motion/issues/861](https://github.com/framer/motion/issues/861)

**Comment by with-heart** [comment]
That's good to know! Subscribed to that topic to keep an eye on it.

**Comment by aboveyunhai** [comment]
@with-heart  Any new updates for this issues?
I had noticed that if I want to use Chakra with next.js + Apollo, which I believed it's quite general for a simple crud web app with some scalability, 
The bundle size (first load js) from `next.js build` can be roughly 110 - 150k (react + chakra + next.js + apollo). The bundle size from `framer-motion` is 20k by itself. Note that `Chakra + emotion` only takes 19k from my analyze. You guys did the pretty good job on reducing the bundle size :) 
I think it's quite crucial here comparing to other packages.

**Comment by aboveyunhai** [comment]
> Hi!
> This issue hasn't seen any activity recently. We close inactive issues after 35 days to manage the volume of issues we receive.
> If we missed this issue or you want to keep it open, please reply here. That will reset the timer and allow more time for this issue to be addressed before it is closed.

No stale
