### ISSUE TITLE
cannot customize Alert colors

### ISSUE THREAD

**Issue by AJFunk** [chakra-ui/chakra-ui#2696]
# Bug report

## Describe the bug

The Alert component's colors cannot be customized. The docs claim you can pass a `colorScheme`, but this prop is overridden by the hard-coded `STATUSES` here https://github.com/chakra-ui/chakra-ui/blob/develop/packages/alert/src/alert.tsx#L55

Additionally, there is not way to add a custom `status`. Since the statuses are hard-coded into this file, they are inaccessible from the theme.

## To reproduce

Pass any `colorScheme` to an Alert and observe that it does not work:
`<Alert colorScheme="purple">....<Alert>`

## Minimal reproduction

https://ckudz.csb.app/

## Expected behavior

You should be able to override the `colorScheme` of an Alert, and/or be able to add a new `status` via the theme

## System information

- Version of @chakra-ui/react: 1.0.0-rc.4
- Version of Node.js: 12.19.0

**Comment by tomdohnal** [comment]
I suppose that making the `Alert` work with colour schemes is something to fix. 

How about adding custom statuses? Should it be possible or is it restricted by design? 

I'm happy to work on the fix once this is clarified.

**Comment by dodas** [comment]
I have sent a PR that allows you to pass the `colorScheme` prop and it will take precedence over whatever color scheme is set by status.

You can also customize the icon by using `<AlertIcon as={SomeIcon} />`.

Do we need anything more?

<img width="761" alt="Screenshot 2020-12-07 at 02 03 18" src="https://user-images.githubusercontent.com/14360171/101298903-6809f200-3830-11eb-9f24-d16a812d474a.png">
