### ISSUE TITLE
[MenuItem] Menu closes when clicking on a MenuItemOption 

### ISSUE THREAD

**Issue by marianorodriguez** [chakra-ui/chakra-ui#2698]
When you have a `MenuOptionGroup` of type="radio" inside a Menu, clicking on any of this options will make the menu to close. I'd like to give my users some kind of "change" feedback, when selecting this options. Same as `closeOnSelect` property of `Menu` component, I'd like to have a closeOnSelect for `MenuItem` and `MenuItemOption` components, so I can choose which Items should close the menu on selection, and which items should keep the menu open.

Here's a small sandbox showing this behavior with a "language selection" example: I'd like to keep the menu open when clicking on 'Spanish' or 'English', so the users have instant feedback on this change.

https://codesandbox.io/s/small-paper-exgwi?file=/src/App.tsx

I am aware of some workarounds to make this work, but it will be great if this was supported by Chakra with a property on the MenuItem components.

Thanks in advance! 😄

**Comment by santialbo** [comment]
Please don't close this.

**Comment by franky47** [comment]
I have a similar use-case: for some actions in the menu, I want to display a loading indicator as feedback, eg:

<img src="https://user-images.githubusercontent.com/1174092/112765877-93972f00-900f-11eb-8be3-3b60969bfa50.gif" width="400px">

One thing that could work is to cancel propagation of the event on the `onClick` handler of the `MenuItem`.

This could then be detected in ChakraUI by `useMenuItem`, and prevent calling `onClose` to close the menu:
https://github.com/chakra-ui/chakra-ui/blob/d6129a526d20d05319eb9acfd35a079f13a32cf8/packages/menu/src/use-menu.ts#L461-L472

**Comment by franky47** [comment]
@with-heart if the solution proposed in my previous comment is acceptable, I can open a PR.

**Comment by segunadebayo** [comment]
That's a great idea @franky47, thanks for sharing your thoughts.

I think it makes sense to be able to control `closeOnSelect` per `MenuItem`. Feel free to create a PR for this.

**Comment by purevolcano106** [comment]
Menu doesn't close when I click MenuItem.
![image](https://user-images.githubusercontent.com/95304105/151067638-88541bbf-afcd-45c0-af55-039fb0377cc3.png)

`
<Menu>
      <MenuButton as={Button} w='100%'>
            <NetworkItem network={fromNetwork}></NetworkItem>
       </MenuButton>
        <MenuList>
         {
                        Networks.testNets.map((network, idx)=>{
                          if(network.chainId !== fromNetwork.chainId)
                            return (
                              <MenuItem minH='48px' key={idx} onClick={() => handleFromNetwork(network)}>
                                <NetworkItem network={network}></NetworkItem>
                              </MenuItem>
                            )
                        })
          }
        </MenuList>
</Menu>
`
