### ISSUE TITLE
Make chakra run in IE 11

### ISSUE THREAD

**Issue by ProsperDevelopment** [chakra-ui/chakra-ui#270]
We will need IE 11 support when we deploy to production. So the first step would be to make it render in IE 11. At the moment it crashes resulting in an white screen.

**Describe the solution you'd like**
First need to get some dependencies working in IE 11 to get it up rendering. I think it might be doable with how to configure webpack transpiling. I found issues with the transpile of react-spring and pretty-num - i tested to exclude the libraries and the components that depended and got it to render.

**Describe alternatives you've considered**
Maybe pretty-num might be a bit bloated to use as its used today.

**Comment by segunadebayo** [comment]
Thanks for this feedback.

I'll check to see how we can make react-spring and pretty-num work in IE 11. Although, I'm guessing it might be related to adding some polyfills.

**Comment by zaguiini** [comment]
To be honest, I don't think it's worth supporting IE 11 anymore. It's big 2019 and IE corresponds to roughly 1% of total browser usage in the world...

**Comment by ProsperDevelopment** [comment]
Well that depends on what users you are targeting, and how picky you are about supporting all platforms. 

Our customers are in the public care area and often in not-so-up-to-date Windows environments and they can't always choose what browser to use. So we have a fair amount of IE 11 users.

Unfortunately we can't say that IE 11 is dead since Microsoft still support it and will do so until its end of life 2025.

**Comment by JeremieLeblanc** [comment]
I would have used Chakra if it had IE11 support.
Seeing that 5% of the traffic to my client's site was still using IE last year, I can't ignore it...
IE11 still comes pre-loaded on any new Windows machine you buy today...

**Comment by jamesg1** [comment]
I think some pollyfills for react-spring should get there. https://github.com/react-spring/react-spring/issues/877
I agree this is a nice library but IE11 is still a browser most large enterprise customer apps support.

**Comment by leetmachine** [comment]
is this related to the reason for https://www.npmjs.com/package/react-app-polyfill

**Comment by segunadebayo** [comment]
I'll open to looking into this after the migration to TS. For now, I'd appreciate if anyone can chime in on this.

I think adding the right polyfills will get us pretty close.

**Comment by ProsperDevelopment** [comment]
I've been looking into this and found two issues with getting it running:

The third party module from-exponential isn't transpiled to es5.
the react-spring library isn't transpiled correct

I got stuck at the first issue getting the polyfills for third party packages in the root node_modules folder.

I tried with working with exclude and include in the babel config, with no results

Maybe https://github.com/babel/babel/issues/8309 is related?

**Comment by VladLegkowski** [comment]
I wanted to have a look into this issue as well but can't even start a storybook... Anybody managed to do it?

![Screenshot 2020-01-24 at 11 47 05](https://user-images.githubusercontent.com/17318500/73063614-7b71d000-3e9f-11ea-8339-077b4885c5ea.png)

**Comment by ProsperDevelopment** [comment]
Yes I mangade to get it working before in 0.4.1 by removing all components having dependencies to react-spring and then I removed the dependency to pretty-num from useNumberInput/utils.js

**Comment by hamfz** [comment]
Any updates?

**Comment by hamfz** [comment]
Just an FYI I got things running in IE11 just by configuring the babel-loader on my webpack configuration not to ignore the node_modules directory.

For the most part, the main problems I noticed were:
- Dropdown menus were not stable, would not stay "open". Possibly something fighting for focus ?
- Simple Grid was a bit sketchy, although not terrible.

I didn't do extensive testing however.

**Comment by ProsperDevelopment** [comment]
> Just an FYI I got things running in IE11 just by configuring the babel-loader on my webpack configuration not to ignore the node_modules directory.
> 

"my webpack"? Did you fix it in the webpack of the project where you are using Chakra?

**Comment by hamfz** [comment]
> > Just an FYI I got things running in IE11 just by configuring the babel-loader on my webpack configuration not to ignore the node_modules directory.
> 
> "my webpack"? Did you fix it in the webpack of the project where you are using Chakra?

Yes.

**Comment by timkindberg** [comment]
Looks like Array.prototype.includes is not being transpiled in the `dist` files. That is causing IE11 issues for me. Box has `if (nativeHTMLPropAlias.includes(prop)) {` and I'm trying to load a polyfill for it but it doesn't seem to help.

**Comment by with-heart** [comment]
We're still marginally supporting customers on IE11 at VNDLY, so I'll take the time to at least investigate and see where we are for 1.0.

**Comment by arthyn** [comment]
> Looks like Array.prototype.includes is not being transpiled in the `dist` files. That is causing IE11 issues for me. Box has `if (nativeHTMLPropAlias.includes(prop)) {` and I'm trying to load a polyfill for it but it doesn't seem to help.

```
import 'react-app-polyfill/ie11'
import 'core-js/features/array/includes'
```

This seemed to fix it for me @timkindberg

**Comment by Edjevw12** [comment]
For the next.js users out there, I use these polyfills and everything seems to work fine.

```
import 'core-js/fn/object/assign'
import 'core-js/fn/array/fill'
import 'core-js/fn/string/starts-with'
import 'core-js/fn/object/entries'
import 'core-js/fn/array/includes'
import 'core-js/fn/string/ends-with'
import 'core-js/fn/string/repeat'
```

**Comment by with-heart** [comment]
We can re-open if new issues are discovered relating to IE11, but I think the polyfills should cover it.

**Comment by ob6160** [comment]
Hi! I'm attempting to run Chakra in IE11, but I'm running into some problems (app isn't loading due to a syntax error).

I've attempted the suggested polyfills above but with no success (still getting a syntax error and white screen). I would appreciate any help/advice that you might have 🙂 I'm happy to spend some time debugging this if I could get some pointers.

**Comment by ljosberinn** [comment]
Could you please provide the errors youre seeing?

**Comment by ob6160** [comment]
Similar error to: https://github.com/chakra-ui/chakra-ui/issues/270#issuecomment-578081024, just throwing a general `syntax error` on the `eval`-ed JS that's added to our bundle from the `dist` directory.

I'd like to be able to provide you with better info than that though. What's the best way I can get a more specific error message?

**Comment by ljosberinn** [comment]
A codesandbox with a minimum reproduction would be great, then I'll run it in IE11 locally :)

**Comment by ob6160** [comment]
success! I tried in codesandbox and it worked which set me trying to fix it in our application.
We weren't transpiling the js files provided in /dist. I added babel to our project and included the followng in our webpack dev config:
```
            {
                test: /\.js$/,
                use: 'babel-loader',
                include: [
                    path.resolve(process.cwd(), 'node_modules/@chakra-ui'),
                    path.resolve(process.cwd(), 'node_modules/@react-aria')
                ]
            }
```
It seems to do the trick. Thanks!
