### ISSUE TITLE
Style prop configured as boolean in styled-system is not working

### ISSUE THREAD

**Issue by terryyu** [chakra-ui/chakra-ui#2700]
# Bug report

## Describe the bug

Style prop configured as boolean in styled-system is not working.

## To reproduce

Let's take `textTransform` as an example, it's configured as true in styled-system.
https://github.com/chakra-ui/chakra-ui/blob/develop/packages/styled-system/src/config/typography.ts#L31

If we extend the theme, and provide a textTransform token.

```javascript
const theme = extendTheme({
  textTransform: {
    header: "uppercase"
  }
}
```

Then use that token in the code

```html
<Box textTransform="header">header</Box>
```

The token is not honored

## Minimal reproduction

https://codesandbox.io/s/jolly-lalande-1ew6j?file=/src/index.js

## Expected behavior

textTransform token should be honored and the text displays in uppercase.

## System information

- Version of @chakra-ui/react: 1.0.1

## Additional context

The config value retrieved should be converted to object if it's boolean
https://github.com/chakra-ui/chakra-ui/blob/develop/packages/styled-system/src/css.ts#L150

**Comment by with-heart** [comment]
I think we need input from @segunadebayo on this to make sure, but I believe this is intentional. All of the properties listed as `true` (or as an object with a `property` key) aren't meant to be themed, they're just extensions of underlying css properties. We provide `theme.textStyles` and `theme.layerStyles` for customizing something like this:

```jsx
const theme = extendTheme({ 
  textStyles: { 
    header: { 
      textTransform: 'uppercase'
    } 
  }
})

// ...

<Box textStyle="header">Hello World</Box>
```

**Comment by terryyu** [comment]
@with-heart `textTransform` might be a bad example. I totally agree it can be substituted by textStyles, but there are quite a few other properties defined as `true`
https://github.com/chakra-ui/chakra-ui/blob/develop/packages/styled-system/src/config/color.ts#L17
https://github.com/chakra-ui/chakra-ui/blob/develop/packages/styled-system/src/config/others.ts#L5

I assume they are following the purpose of styled-system shortcut definition.
https://styled-system.com/custom-props/#shortcut-definition
https://github.com/styled-system/styled-system/blob/master/packages/core/src/index.js#L165
