### ISSUE TITLE
Color mode: can't force light mode.

### ISSUE THREAD

**Issue by luanfelipecosta** [chakra-ui/chakra-ui#2713]
# Bug report

## Describe the bug
Configuration for forcing the color mode to light won't work. 
- it's a react + nextJS (Typescript) project
- Followed example in Docs.
- My OS and my browser uses dark mode. 

## To reproduce
created a next-js-typescript project and did the setup:
```
// pages/_app.tsx

const config = {
  useSystemColorMode: false,
  initialColorMode: 'light',
};

const customTheme = extendTheme({ config });

function MyApp({ Component, pageProps }) {
  return (
    <Provider store={store}>
      <ChakraProvider resetCSS theme={customTheme}>
        <Component {...pageProps} />
        <Alert />
      </ChakraProvider>
    </Provider>
  );
}

export default MyApp;
```

```
pages/_doocument.tsx

export default class CustomDocument extends Document<DocumentProps> {
  static getInitialProps(ctx) {
    return Document.getInitialProps(ctx);
  }
  render(): JSX.Element {
    return (
      <Html>
        <Head>
          <link
            href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap"
            rel="stylesheet"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <body>
          <ColorModeScript initialColorMode="light" />
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
```
## Expected behavior
Theme to be light.

## Result: 
![screenshot](https://i.imgur.com/iGDPuNL.png)

## System information

- OS: MacOS Catalina 
- Browser Chrome
- Version of @chakra-ui/react: 1.0.2
- Version of Node.js: [e.g. 12.11.1]

**Comment by with-heart** [comment]
Hi @luanfelipecosta! Any way you could wrap this example up in a CodeSandbox to make it easier to triage?

**Comment by luanfelipecosta** [comment]
I checked out my localstorage and there was default keys setted up already 
erased them, the bug has gone.
