### ISSUE TITLE
active / hover on nav elements on docs with darkmode

### ISSUE THREAD

**Issue by brennanfife** [chakra-ui/chakra-ui#2714]
# Bug report

## Describe the bug
With darkmode turn on, hover over the navigation elements. You'll find the text is hard to read (black text on black background)

## Screenshots
<img width="198" alt="Screen Shot 2020-12-05 at 1 05 15 PM" src="https://user-images.githubusercontent.com/31396350/101261252-65f24700-36fb-11eb-92af-d7f6008dfad0.png">

## System information
- Browser: Chrome (also applies to Firefox)

**Comment by snesjhon** [comment]
I have a PR for this #2715
