### ISSUE TITLE
Use input type tel instead of phone

### ISSUE THREAD

**Issue by steida** [chakra-ui/chakra-ui#272]
It seems, there is no such thing as phone value.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel

**Comment by segunadebayo** [comment]
Hi @steida. I'm not sure I understand what you mean. What component has `type=phone`? I'm aware that there's no `phone` value.

Kindly point me to it. Thanks

**Comment by steida** [comment]
Sorry for not being descriptive enough.  In example, there is `type` phone.
![Screenshot 2019-12-02 at 20 10 01](https://user-images.githubusercontent.com/66249/69987410-be6a9380-153f-11ea-9a1c-21e6027d55e5.png)

**Comment by segunadebayo** [comment]
Oh, I see. I've changed that to `tel`.

I'll update the docs shortly.
