### ISSUE TITLE
Add support for flex gap

### ISSUE THREAD

**Issue by colemars** [chakra-ui/chakra-ui#2720]
https://caniuse.com/flexbox-gap

Supported in Chrome and FF and will be supported in Safari next major release (currently in TP).

If approved I'm happy to make the changes.

**Comment by segunadebayo** [comment]
Hello @colemars,

You can use `flexGap` currently with the `sx` prop. We're not looking to add this directly to the style props at the moment but we'll do so once it is more widely supported.

Thanks

**Comment by terrierscript** [comment]
Safari supported flex gap on 14.1.
https://webkit.org/blog/11648/new-webkit-features-in-safari-14-1/
and many modern browsers are supported this.

---

Workaround: You can use `gridGap`.

```tsx
<Flex direction="column" gridGap={2}>
```

**Comment by ssijak** [comment]
Please add this. It is a life saver for Flex. And supported in all major browsers now.

**Comment by with-heart** [comment]
Going to re-open this since we now have support in all major browsers. 
![image](https://user-images.githubusercontent.com/1954752/120895765-7c1a8a80-c5ec-11eb-8123-f83562d90a53.png)

**Comment by davidkpiano** [comment]
I'd also appreciate support for this! Currently just doing this:

```jsx
<Box display="flex" css={{ gap: '.5rem' }}>
```

**Comment by nenadfilipovic** [comment]
Yea you can use `sx`, `css`, or `style` to pass gap prop but it would be nice to put it inside api.

**Comment by stellarhoof** [comment]
How will this affect the API for `Stack` and `Wrap`? Will `spacing` be deprecated in favor of `gap`?

**Comment by nicopoore** [comment]
Isn't it easier to just use `Stack` instead? It's basically `flex-gap` without `flex-gap`, and (from what I understand) with broader support

**Comment by ssijak** [comment]
@nicopoore Stack is fine until it wraps items to another row, then you lose that gap between the rows and have a strange gap at the first item in the next row.
`gap` property is natively supported in all browsers now, works really well, it is easy to understand, and should be supported.

**Comment by nenadfilipovic** [comment]
Yup it is needed for wrap.

**Comment by nicopoore** [comment]
@ssijak @nenadfilipovic and what about the `Wrap` chakra component if the items are going to wrap?

**Comment by ssijak** [comment]
@nicopoore It wraps everything in `ul` and each item in `li` tag and adds unnecessary margins. Unnecessary if you use flex gap.

**Comment by MichaelKilbane** [comment]
Happy to use the workarounds for now, but it feels like this should be added. Currently at [87.3% support](https://caniuse.com/flexbox-gap). Not sure if that meets the standard for 'widely supported' enough. Nonetheless, here is a use cases I've run into:

Applying consistent spacing to children of a Stack, while allowing more to be applied to particular children. Right now, the Stack component overwrites the margin properties of the children, so any extra margin is ignored.

**Comment by k-utsumi** [comment]
I think it would be convenient to have props `row-gap` (rowGap) and `column-gap` (columnGap) as well.

- https://developer.mozilla.org/en-US/docs/Web/CSS/row-gap
- https://developer.mozilla.org/en-US/docs/Web/CSS/column-gap

**Comment by ssijak** [comment]
Those are not flex attributes

**Comment by MichaelKilbane** [comment]
@k-utsumi Thanks for the suggestion. I'll wait for some feedback from the maintainers before amending my PR.

@ssijak I believe `gap` is just the shorthand version of these two properties, so it makes sense to add them.

**Comment by stellarhoof** [comment]
@ssijak They started as grid attributes but they were extended to include flex as well: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Alignment#gaps_between_boxes

**Comment by selrond** [comment]
What's the state of this? The `gap` property (along with `row-gap` & `column-gap`) has great support nowadays, there seems to be no reason for not having it inside chakra

**Comment by stellarhoof** [comment]
@selrond There's a PR linked to this issue and the maintainers are aware of it.

**Comment by selrond** [comment]
not stale

**Comment by rshea0** [comment]
Is there any real use for Wrap now that Flex supports gap?

**Comment by marcosmarp** [comment]
> Is there any real use for Wrap now that Flex supports gap?

I'm not sure how one excludes the other

**Comment by dayoolacodes** [comment]
is there support for the gap property now?
