### ISSUE TITLE
Add new Tailwind v2 extended color palette

### ISSUE THREAD

**Issue by hugobqd** [chakra-ui/chakra-ui#2721]
### Feature request

Is it planed to add the new Tailwind v2 extended palette into Chakra-UI v1? 
https://tailwindcss.com/docs/customizing-colors#color-palette-reference

<img width="837" alt="Capture d’écran 2020-12-06 à 21 27 15" src="https://user-images.githubusercontent.com/35178/101291566-1ea6ac00-380a-11eb-936d-94208fb12339.png">

Thanks ⚡

**Comment by Xetera** [comment]
The old tailwind palette is really lacking in the grays. It would be pretty cool if this came as an helper object that can be spread into `extendTheme`
