### ISSUE TITLE
[ModalCloseButton] Modal close button missing styles

### ISSUE THREAD

**Issue by nejcm** [chakra-ui/chakra-ui#2722]
# Bug report

## Describe the bug

The modal close button does not respect the close-button styles.

## To reproduce

Open the modal with the close button inside.

## Minimal reproduction

https://chakra-ui.com/docs/overlay/modal

## Expected behavior

The modal close button should have the same styling as the CloseButton.

**Comment by dodas** [comment]
Hi @nejcm, thanks for reporting.

This issue has been already [fixed here](https://github.com/chakra-ui/chakra-ui/pull/2708), we just need to wait for the next release.

**Comment by nejcm** [comment]
Sorry missed the issue. Thanks.
