### ISSUE TITLE
Resolve forwarded props issues

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#2728]
# Feature request

## Is your feature request related to a problem? Please describe.

When using the `chakra` function, users can provide the `shouldForwardProps` option as a function which (once #2670 is fixed; see #2717) takes a `prop` and returns a `boolean` representing whether `prop` should be forwarded to the underlying HTML element or not. 

If this option is not provided, `chakra` defaults to our internal `shouldForwardProp` implementation, which returns `true` for any prop that is a valid HTML prop OR is not a prop in the Chakra system. 

In my view, allowing users to provide their own `shouldForwardProps` implementation that _replaces_ the internal function is nearly useless. If you're using `chakra` you're producing a component built by the Chakra system, and replacing the `shouldForwardProps` function means that users would have to re-implement the default functionality of forwarding any valid html props and blocking Chakra props wherever the option is defined. I can't think of a case where a user would expect or want this.

I think the vast majority of use cases that exist are to allow integration of Chakra with other third-party libraries. An example of this that has been reported multiple times is combining Chakra components with `framer-motion`, where the framer props are all forwarded on to the underlying HTML element, causing console errors (see https://github.com/chakra-ui/chakra-ui/discussions/2704#discussioncomment-148445 for a recent report of this). To resolve these errors, functionality should exist that allows a user to _extend_ `shouldForwardProps`, so they can prevent these additional props from being forwarded while still receiving the default props forwarding behavior.

## Describe the solution you'd like

I was originally thinking we could modify the `shouldForwardProp` option to behave similar to `extendTheme`, where the result of the options function is merged with the internal `shouldForwardProp` function, but this would leave us back where we started:

```ts
const partialMotionProps = ['animate', 'whileHover', 'whileTap']

const MotionBox = motion.custom(
  chakra('div', {
    // would prevent forwarding of props in `partialMotionProps`, but then
    // blocks forwarding of all other props
    shouldForwardProp: (prop) => !partialMotionsProps.includes(prop)
  })
)
```

Some other alternatives I've thought about:

1. Allow the result to be `boolean | undefined`, where `undefined` would signal that we should defer to the result of the internal function:

```ts
const partialMotionProps = ['animate', 'whileHover', 'whileTap']

const MotionBox = motion.custom(
  chakra("div", {
    // `true` or `false` overrides value returned from internal function.
    // `undefined` defers to the internal value.
    shouldForwardProp: (prop) => partialMotionProps.includes(prop) ? false : undefined,
  }),
)
```

This feels dirty though, and relies on the user to have a lot of knowledge about how the internal `shouldForwardProp` function works.

2. Forward **only** valid HTML props by default and provide `forwardedProps` option that allows the user to specify individual props to forward. I'm not sure what the use case for this would be, but it would automatically resolve all third-party integration issues we're currently facing as those props would not be forwarded.

```ts
const arbitraryPropsToForwardForSomeReason = ['prop1', 'prop2', 'prop3']

const NewBox = chakra('div', { forwardedProps: arbitraryPropsToForwardForSomeReason })
```

The more I think about it, the more I think that maybe this is actually the better way forward. We might not even need to define the additional option at all.

@segunadebayo Is there a reason we need to explicitly return `true` for all props that aren't in the Chakra system by default? What would happen if we change our internal implementation to this:

```ts
export const shouldForwardProp = (prop: string): boolean => validHTMLProps.has(prop)
```

## Additional context

This issue stems from conversation in https://github.com/chakra-ui/chakra-ui/pull/2717/files#r536979296.

**Comment by segunadebayo** [comment]
@with-heart, yes there's a reason. When you wrap custom components that use custom prop names, emotion might flag them as invalid when they're valid. The best bet at the time was to check for only Chakra's style props and allow the others to pass through.

Given the conversation we had about allowing custom shouldForwardProps, we can invert control to the user to handle these scenarios. We'll export our internal `shouldForwardProps`, and the user can also install emotion's `is-prop-valid` package for more fine-grained validation.

We could do this "Forward only valid HTML props by default" by I think we might keep the shouldForwardProp as a function instead of providing an array of props to forward to keep similar API as emotion and styled-components.

Your first approach might work but I need to test it out.

**Comment by segunadebayo** [comment]
I just pushed a fix for this and added docs as well.

That should suffice for now.

**Comment by with-heart** [comment]
@segunadebayo How did you end up changing this?

The more I think about it, the more I I feel like "Forward only valid HTML props by default" is probably the correct solution. For the vast majority of cases, users aren't going to need this feature. It makes sense for `@emotion` to provide `shouldForwardProps` and `is-prop-valid` since it's a framework intended to be used in lots of cases, but I don't think the same makes sense for us, since we're providing a concrete system where we know the output.

Does that change make sense? Mostly I'm concerned with the use case of `framer-motion` + Chakra components throwing `React does not recognize the 'X' prop on a DOM element` errors by default. Doesn't feel like good DX for users to have to manually fix that every time.
