### ISSUE TITLE
Container no longer uses sizes.container values

### ISSUE THREAD

**Issue by prayogoa** [chakra-ui/chakra-ui#2730]
# 🐛 Bug report

Since https://github.com/chakra-ui/chakra-ui/pull/2602 the `Container` component no longer uses size values defined in `sizes.container`, but instead uses `sizes.largeSizes`. This is not mentioned in the PR, and I couldn't find any other uses of `sizes.container` in the codebase so either `sizes.container` is deprecated without documentation or this change is unintended.

## 💥 Steps to reproduce
As can be seen from the codesandbox, specifying `maxW="lg"` results in a max width value of `512px = (sizes.largeSizes.ls)` instead of `1024px (sizes.containers.lg)`

## 💻 Link to reproduction
https://codesandbox.io/s/white-moon-7sxnh?file=/src/App.tsx

## 🧐 Expected behavior

Container should use size values defined in `sizes.container`

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.0.2      |
| Browser          |      N/A      |
| Operating System |     N/A       |

## 📝 Additional information

![Screen Shot 2020-12-07 at 11 34 45 PM](https://user-images.githubusercontent.com/1696217/101370860-0061ae80-38e5-11eb-9c36-40180f4481f1.png)
Offending PR https://github.com/chakra-ui/chakra-ui/pull/2602
[sizes.container](https://github.com/chakra-ui/chakra-ui/blob/3fbe55c5a55d8c4697759a06ad4d492df41003e4/packages/theme/src/foundations/sizes.ts#L23)

**Comment by prayogoa** [comment]
This might be an intended change, since you can still do `<Container maxW="container.lg" />` to achieve the same effect. This does make the behaviour less surprising, so imo I don't mind this change as long as it's reflected in the docs / changelog.

**Comment by with-heart** [comment]
Whoops! Looks like that PR removed some functionality that was built in to `Container` previously.

cc @chakra-ui/react-team: How do we want to handle this? I'm leaning towards reverting it and coming up with a better plan for adding theming to `Container`, as this ended up being an unintentional breaking change.

**Comment by jmiazga** [comment]
Do you think we can follow up quickly with a fix? If not reverting might be the better way to go.

**Comment by TimKolberger** [comment]
Reverting would introduce another breaking change due the removal of the possibility to style the container. 
IMO a bugfix is the best way to go.

To resolve this, we have to map the width props with this removed function:

https://github.com/chakra-ui/chakra-ui/pull/2602/files#diff-60a86369843a19e5529447248281f54561cf8c3898b59f94f7514d4ab606dabfL87-L99

**Comment by hems** [comment]
i reckon using “container.width” is much more intuitive than overwriting “largeSizes”.l or having a “container” object using that size while all other objects such as Flex would use largeSizes...?

One thing i wonder though is if “container” sizes are even needed on sizes.ts..

perhaps we can survive with the “largeSizes” hash only?

**Comment by segunadebayo** [comment]
I'd recommend this:

- Revert the change first
- Add support for theming containers
- Figure out how both functionalities can co-exists without breaking.

@chakra-ui/react-team This means we need to review PRs a bit more before merging. #LessonLearned

**Comment by dodas** [comment]
What's current state of this issue?

**Comment by trevorblades** [comment]
@segunadebayo I put together [a PR](https://github.com/chakra-ui/chakra-ui/pull/2997) that attempts to support both functionalities. The catch with the approach I used is that using the shorthand size prop (`xl` rather than `container.xl`) only works as a prop on the `Container`, and not when overwriting styles in the theme. Does this seem like an acceptable solution?

Works as expected:
```js
<Container maxW="xl" /> {/* container.xl */}
```

Does not use the size from `sizes.container`:
```js
components: {
  Container: {
    maxW: 'xl' // largeSizes.xl
  }
}
```

**Comment by with-heart** [comment]
@trevorblades Sorry for not getting back to you. I'll try to take a look at your PR tomorrow.

**Comment by segunadebayo** [comment]
So sorry for keeping this up for some time. We reviewed the PR and thought it was best to leave the container as is due to the TypeScript complexity involved.

Hope you can find a way to walk around this by using `maxW=container.lg`

Cheers
