### ISSUE TITLE
Drawer close button alignment

### ISSUE THREAD

**Issue by ganeshkrishnasharma** [chakra-ui/chakra-ui#2732]
The alignment of close button inside Drawer seems to be wrong. Can be seen in docs as well. 

```
 <Drawer
        isOpen={isOpen}
        placement="right"
        onClose={onClose}
        finalFocusRef={btnRef}
      >
        <DrawerOverlay>
          <DrawerContent>
            <DrawerCloseButton />
            <DrawerHeader>Create your account</DrawerHeader>

            <DrawerBody>
              <Input placeholder="Type here..." />
            </DrawerBody>

            <DrawerFooter>
              <Button variant="outline" mr={3} onClick={onClose}>
                Cancel
              </Button>
              <Button color="blue">Save</Button>
            </DrawerFooter>
          </DrawerContent>
        </DrawerOverlay>
      </Drawer>
```
<img width="322" alt="Screenshot 2020-12-07 at 10 45 54 PM" src="https://user-images.githubusercontent.com/39894982/101382795-60a12200-38de-11eb-9830-6c65d1381872.png">

**Comment by dodas** [comment]
Hi @ganeshkrishnasharma!

This issue has been already [fixed here](https://github.com/chakra-ui/chakra-ui/pull/2708), we just need to wait for the next release.

**Comment by ganeshkrishnasharma** [comment]
> Hi @ganeshkrishnasharma!
> 
> This issue has been already [fixed here](https://github.com/chakra-ui/chakra-ui/pull/2708), we just need to wait for the next release.

Thank you @dodas :) I am sorry for missing out on checking this!
