### ISSUE TITLE
Unable to change Input text color.

### ISSUE THREAD

**Issue by ellisio** [chakra-ui/chakra-ui#2734]
# 🐛 Bug report

Unable to change the text color on `<Input />`.

## 💥 Steps to reproduce

1. Visit the documentation site: https://chakra-ui.com/docs/form/input#usage
2. Apply `color="red"` to `<Input />`
3. Enter some test text.
4. Observe that the color remains black.

## 💻 Link to reproduction

See above.

## 🧐 Expected behavior

I expect the input's text color to be red, not black.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | v1           |
| Browser          | Chrome           |
| Operating System |            |

## 📝 Additional information

This was discovered because I am styling an input in a header that needs to be white by default, and gray.700 on focus. My code I was using was:

```
<Input bg="blue.200" color="white" _focus={{ bg: 'white', color: 'gray.700' }} /
```

**Comment by dodas** [comment]
Hi @ellisio.

I am not sure what you are doing wrong, but your code **does** work.
Following screenshot is from the Docs.
<img width="770" alt="Screenshot 2020-12-08 at 13 44 47" src="https://user-images.githubusercontent.com/14360171/101485529-920c0300-395b-11eb-87b0-ad48821b57ee.png">

**Comment by with-heart** [comment]
> 2. Apply `color="red"` to `<Input />`

`color` expects an individual color scale value, not a color scale. `red.#` works fine:

![image](https://user-images.githubusercontent.com/1954752/101486403-9835bb80-392a-11eb-9f6c-600b4df15058.png)
