### ISSUE TITLE
Chakra Slide (transition) component ignores directions: top || bottom

### ISSUE THREAD

**Issue by gaurangrshah** [chakra-ui/chakra-ui#2735]
# 🐛 Bug report

> Provide a brief description of the bug here

Currently having trouble implementing the slide component to slide my header in and out when the props for direction are set to either "top" or "bottom". 

**NOTE:** "left" || "right" work just fine.

## 💥 Steps to reproduce

> Clear and concise reproduction steps are important for us to be able to triage
> your issue in a timely manner

1. Go to https://codesandbox.io/s/jolly-wu-f28um?file=/chakra/components/header.js
2. Navigate to `./chakra/components/header.js`
3. see the default implementation, and then try to comment in the others  (one for each direction is available.)

## 💻 Link to reproduction

> Please create a minimal reproduction in CodeSandbox
>
>   [CodeSandbox template](https://codesandbox.io/s/jolly-wu-f28um?file=/chakra/components/header.js)
>

## 🧐 Expected behavior

> All directions should transition in and out as expected. 

## 🌍 System information

| Software         | Version(s)                |
| ---------------- | ------------------------- |
| Chakra UI        | 1.01                      |
| Framer Motion    | 2.9.4                     |
|                  |                           |
| Browser          | Edge, Firefox, safari     |
| Operating System | osx 10.13.6 (High Sierra) |

## 📝 Additional information

![chakra-header-slide](https://user-images.githubusercontent.com/1086269/101419456-0d1edc00-38be-11eb-9a80-282bbe0d0151.gif)

**Comment by TimKolberger** [comment]
I just forked your codesandbox and it appears to be working. 
The header is sliding in from the top.

Can you please check again if @chakra-ui/react v1.0.4 fixes your issue?

**Comment by gaurangrshah** [comment]
@TimKolberger would you mind sharing your fork of the repo, i just upgraded all my chakra related packages https://codesandbox.io/s/jolly-wu-f28um and still I am not seeing the working slide transition for my header, thanks.

**Comment by TimKolberger** [comment]
This link is in there: 

> I just [forked your codesandbox](https://codesandbox.io/s/magical-einstein-u6ik6?file=/chakra/components/header.js) and it appears to be working.

This is odd - I tried a few things and after reverting all changes it still worked 😅  Sorry for the confusion.
Adding this style to the Slide component fixes it:

```tsx
<Slide
  direction="top"
  in={headerShow}
  zIndex={2000}
  style={{ width: "100%", height: "100vh" }}
>
```

**Comment by gaurangrshah** [comment]
This works perfectly, btw thank you!
