### ISSUE TITLE
Generate global changelog/GitHub release for `@chakra-ui/react`

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#2739]
Since `@chakra-ui/react` acts as a combined gateway to (nearly) all Chakra UI functionality, its changelog and release should reflect that by listing all changes to all dependent packages, so that users can view all changes/fixes in a single place rather than having to view the changelog/release for each individual package.

We use https://github.com/atlassian/changesets for release management and changelog generation, so we'll need to work with their community to implement/utilize this functionality. Relevant `changesets` issues:

- https://github.com/atlassian/changesets/issues/387
- https://github.com/atlassian/changesets/issues/264

**Comment by segunadebayo** [comment]
I think we should put all release management issues under one umbrella, given that it's an internal problem to solve with the @chakra-ui/triage team.

**Comment by jonstuebe** [comment]
out of curiosity did you all manually end up creating the github releases and global changelog? Or did you end up finding a tooling solution for this?

@segunadebayo
