### ISSUE TITLE
[AlertIcon] Alert icons are not vertically aligned with the text

### ISSUE THREAD

**Issue by franky47** [chakra-ui/chakra-ui#274]
**Describe the bug**

It is subtle, but alert icons are not vertically aligned with the alert text:
<img width="518" alt="before" src="https://user-images.githubusercontent.com/1174092/69897276-18a20380-134a-11ea-8127-8e1ecaf0b1f4.png">

**Expected Behavior**
The icons should be vertically aligned with the text:
<img width="518" alt="after" src="https://user-images.githubusercontent.com/1174092/69897281-33747800-134a-11ea-953f-3e31912f1f15.png">

**To Reproduce**
See the documentation: https://chakra-ui.com/alert

**Suggested solution**
Removing the top margin on the `AlertIcon` component seems to do the trick.

The line in question:
https://github.com/chakra-ui/chakra-ui/blob/edb945b8423beb8b9d5cfb5162d75f8ca3c82f7b/packages/chakra-ui/src/Alert/index.js#L55

Note: as the AlertIcon is used in the Toast as well, it seems it solves the same issue there, effectively aligning the toast icon with the toast title:
<img width="360" alt="before" src="https://user-images.githubusercontent.com/1174092/69897406-fa3d0780-134b-11ea-92eb-60ac05801104.png">
<img width="360" alt="after" src="https://user-images.githubusercontent.com/1174092/69897407-fc06cb00-134b-11ea-9d83-7e82be7c002d.png">

**Platform**
 - OS: macOS 10.14.6
 - Browser: Firefox 70.0.1
 - Version: 0.4.1

**Comment by segunadebayo** [comment]
Thanks for this suggestion @franky47. It's subtle but I like that attention to detail.

I've done that and will release a new version soon.
