### ISSUE TITLE
Improve Chakra versioning strategy

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#2740]
Since `@chakra-ui/react` acts as a combined gateway to (nearly) all Chakra UI functionality, its version should reflect that by having all `minor` version bumps to its internal dependencies applied to itself as well. This allows the `@chakra-ui/react` package to reflect all backwards-compatible functionality changes for the _system as a whole_.

We've currently configured https://github.com/atlassian/changesets to bump internal dependency changes using `patch` which is _probably_ the more correct thing to do in that situation since the _technically correct_ thing would result in constant `major` version bumps, but in the case of `@chakra-ui/react`, we want to instead receive any `minor` version bumps.

# Examples

In my mind, here's how versioning should look (assume all packages starting at `1.0.0`):

1. Internal dependency adds backwards-compatible functionality

- `@chakra-ui/hooks` adds a new `useCoolThing` export
	- `@chakra-ui/hooks@1.0.0` -> `@chakra-ui/hooks@1.1.0` (`minor`)
- `@chakra-ui/react@1.0.0` -> `@chakra-ui/react@1.1.0` (`minor`) to reflect the added _system-level_ functionality

2. Multiple internal dependencies add backwards-compatible functionality

- `@chakra-ui/hooks` adds a new `useCoolThing` export
	- `@chakra-ui/hooks@1.0.0` -> `@chakra-ui/hooks@1.1.0` (`minor`)
- `@chakra-ui/accordion` adds a new `AccordionCoolestItem` export
	- `@chakra-ui/accordion@1.0.0` -> `@chakra-ui/accordion@1.1.0` (`minor`)
- `@chakra-ui/react@1.0.0` -> `@chakra-ui/react@1.1.0` (`minor`) to reflect the added _system-level_ functionality

3. Internal dependency adds bug fix

- `@chakra-ui/hooks` fixes a bug with `useCoolThing`
	- `@chakra-ui/hooks@1.0.0` -> `@chakra-ui/hooks@1.0.1` (`patch`)
- `@chakra-ui/react@1.0.0` -> `@chakra-ui/react@1.0.1` (`patch`) to reflect the _system-level_ bug fix

4. Multiple internal dependencies add bug fixes

- `@chakra-ui/hooks` fixes a bug with `useCoolThing`
	- `@chakra-ui/hooks@1.0.0` -> `@chakra-ui/hooks@1.0.1` (`patch`)
- `@chakra-ui/accordion` fixes a bug with `useAccordionItem`
	- `@chakra-ui/accordion@1.0.0` -> `@chakra-ui/accordion@1.0.1` (`patch`)
- `@chakra-ui/react@1.0.0` -> `@chakra-ui/react@1.0.1` (`patch`) to reflect the _system-level_ bug fixes

5. Internal dependencies add backwards-compatible functionality **and** bug fixes

- `@chakra-ui/hooks` fixes a bug with `useCoolThing`
	- `@chakra-ui/hooks@1.0.0` -> `@chakra-ui/hooks@1.0.1` (`patch`)
- `@chakra-ui/accordion` adds a new `AccordionCoolestItem` export
	- `@chakra-ui/accordion@1.0.0` -> `@chakra-ui/accordion@1.1.0` (`minor`)
- `@chakra-ui/react@1.0.0` -> `@chakra-ui/react@1.1.1` (`minor` and `patch`) to reflect **maximum** version bump of all _system-level_ changes (I believe this is the automatic `changesets` behavior, but I need to test that; see https://github.com/atlassian/changesets/blob/master/docs/decisions.md#how-changesets-are-combined for more info)

6. New package is published

- `@chakra-ui/new-component` is created
	- `@chakra-ui/new-component@1.0.0` to reflect start of new package
- `@chakra-ui/react@1.0.0` -> `@chakra-ui/react@1.1.0` (`minor`) to reflect the added _system-level_ functionality

# How?

I think we have two possible solutions:

- Include `@chakra-ui/react` in all changeset files matching the version bump of the dependent package. This requires manual effort, but allows us to fully control the process.
- Build our own customized release plan. I'm not sure `changesets` supports this yet and need to investigate, but it would allow us to automate this so we don't have to always include `@chakra-ui/react` bumps in our changeset files.

**Comment by segunadebayo** [comment]
This is a valid thought, I'd go with the first approach 'coz it requires less work.

I'd suggest we find an automated way to add `@chakra-ui/react` to the changesets just before we publish new releases. Perhaps we can write a simple script to read the `frontmatter` of all changeset markdown and add to it.

**Comment by with-heart** [comment]
Wanted to add some further discussion/resources for more context: 

- https://github.com/semver/semver/issues/502 

`semver` maintainers consider peer dependency changes to be part of the public API of the package and thus breaking changes require `major` bump
 
- https://github.com/Thinkmill/monorepo#versioning

> If a peer dependency(a dependency which is in peerDependencies) is being released as a major or minor(though not patch), the dependent should receive a major bump. This is done because. We do not do this on patch bumps to peer dependencies because they shouldn’t introduce new features or behaviour that the dependent could rely on.

Unfortunately the reason WHY was cut off, but Thinkmill also views `major` as a requirement for bumping peer dependencies

**Comment by timkindberg** [comment]
I'm not sure you'd need to go to 1.1.1 if there was a minor and patch, I think going to 1.1.0 is sufficient.

**Comment by segunadebayo** [comment]
What's the fate of this issue @with-heart? Can we close if you don't have the time to improve this?

**Comment by with-heart** [comment]
It's slowly coming along. I'll give an update late this week if that's okay

**Comment by segunadebayo** [comment]
I'm going to close this for now since we don't have a better solution.

I'd suggest adding this issue description as a guideline for the @chakra-ui/react-team instead. We can do this manually in the meantime till there's some solution out there that can help.

Thanks.

**Comment by segunadebayo** [comment]
I just pushed this under `VERSIONING.md` for now.
