### ISSUE TITLE
Modal does not fill 100% of the screen

### ISSUE THREAD

**Issue by PauloSpiguel** [chakra-ui/chakra-ui#2748]
I am trying to use the modal but this does not fill 100% of the screen, when this is in a responsive mode or on some mobile phone. I have tried several properties of the modal but nothing worked. To correct I need to change the width: 100vw to 100% and height: 100vh to 100%. How can I accomplish this. Changing the width and height property in the modal doesn't work. Any ideas?

![Captura de ecrã 2020-12-09, às 15 41 10](https://user-images.githubusercontent.com/41386612/101652705-79bce680-3a36-11eb-822f-f353f4c4f0c9.png)

**Comment by ginyatov** [comment]
Good evening. You have the wrong adaptive. Judging by the screenshot, chacka correctly set the dimensions of the modal window, 375x812, as you have specified in the response google chrome.To make sure of this, delete all content through the code inspector and leave only the modal window and everything will be fine. Therefore, redo the responsiveness of your site.

**Comment by segunadebayo** [comment]
Thanks for chiming in @ginyatov. I agree, @PauloSpiguel, the issue is that the content behind the modal isn't responsive.

Your view is 375x812
Chakra's modal is 375 x 812

This shows that the Modal is working correctly though. Kindly improve the responsiveness of the content behind.

**Comment by PauloSpiguel** [comment]
Thanks for the tips, I will do that.
