### ISSUE TITLE
Pasting into PinInput does not work anymore

### ISSUE THREAD

**Issue by nejcm** [chakra-ui/chakra-ui#2749]
# 🐛 Bug report

Pasting into a group of PinInputFields does not work anymore in v1.0.3. This did work in previous versions but currently the pasted number gets inserted in the first PinInputField.

## 💥 Steps to reproduce

Create a PintInput group of multiple PinInputFields and try pasting into it a multiple digit number.

## 💻 Link to reproduction

https://chakra-ui.com/docs/form/pin-input

## 🧐 Expected behavior

The pasted number digits should be each in it's own field.

## 🌍 System information

Chakra UI v1.0.3

**Comment by with-heart** [comment]
Looks like something we broke something in #2729

**Comment by segunadebayo** [comment]
I just pushed a fix for this! My bad.
