### ISSUE TITLE
[Select] backgroundColor not forwarded to element

### ISSUE THREAD

**Issue by leerob** [chakra-ui/chakra-ui#275]
**Describe the bug**
When trying to forward `backgroundColor` to `Select`, it does not work as expected.

**Expected Behavior**
I would expect the color to change.

**To Reproduce**
```js
<Select backgroundColor="blue">
  <option>Test</option>
</Select>
```

** Suggested solution(s)**
Workaround
```js
const StyledSelect = styled(Select)`
    background-color: blue;
`;
```

I was able to get it to work by overriding the component, but I'm guessing the prop is just not getting passed to correctly. It looks like it was trying to put `backgroundColor` on the DOM.

**Comment by segunadebayo** [comment]
Hi @leerob,

The color `blue` is an object in the theme, that's the cause of this issue. It should work if you use `blue.100`, or `blue.200`, etc. See it here: https://chakra-ui.com/theme#blue

Not sure how to prevent this common error in the future. Kindly verify that it works.

**Comment by segunadebayo** [comment]
Let me know if this works. If it doesn't I'll re-open this issue

**Comment by leerob** [comment]
I believe that's not the issue 😢 Here's a sandbox with a reproducible example.

https://codesandbox.io/s/chakra-js-starter-6t9xl?fontsize=14&hidenavigation=1&theme=dark

**Comment by segunadebayo** [comment]
I see what you mean, I plan to simplify the API for the select component to this:

```jsx
<SelectWrapper>
 <Select />
 <SelectIcon />
</SelectWrapper>
```
This will keep it declarative and make it easy to style any part of the `Select`

**Comment by segunadebayo** [comment]
I'll release an update soon.

**Comment by aaronmcadam** [comment]
@segunadebayo are there updated docs for `Select` too? I'd like to try it out. The docs site didn't get updated when `0.5.0` was released.

**Comment by segunadebayo** [comment]
@aaronmcadam. The Select is still the native select component, not the `SingleSelect` we discussed in #140.

I intend to release a patch for this issue so users can style any part of the Select.

I noticed I didn't add it to the docs. I will do so shortly.

**Comment by aaronmcadam** [comment]
@segunadebayo yeah, I see that, it's a great start though! Thanks!

**Comment by leerob** [comment]
Awesome @segunadebayo - thank you so much!

**Comment by segunadebayo** [comment]
I've fixed this issue and I'll release a patch later today after I add it to the docs.

`Select` will now forward props as expected.

**Comment by segunadebayo** [comment]
I've added the Select to the docs and it'll be updated shortly.

Thanks for this issue, it helped me improve the Select component a bit.

**Comment by leerob** [comment]
Thanks so much @segunadebayo 🎉
