### ISSUE TITLE
Padding not loading with JS turned off

### ISSUE THREAD

**Issue by hutber** [chakra-ui/chakra-ui#2758]
It seems that there is miss-match with the SSR and when js renders the app, so all padding is missing. At least this is my guess as I cannot think why else the padding would be missing when you turn JS off.

```
    "@chakra-ui/react": "^1.0.3",
    "@chakra-ui/theme-tools": "^1.0.1",
```

Theme
```
export const Link = {
    mainNav: {
    fontFamily: "demi",
    fontWeight: "normal",
    fontSize: -1,
    lineHeight: -1,
    textTransform: "uppercase",
    letterSpacing: "0.16em",
      py: 1,
      px: 2,
      m: "0 !important",
      "&:hover": {
        boxShadow: `0 4px ${colors.pink.dark}`,
      },
    },
  },
}
```

Component 
```
          <Link
            variant="mainNav"
          >
            {item.text}
          </Link>
```

With JS enabled:
![image](https://user-images.githubusercontent.com/1344898/101932073-30090300-3bd2-11eb-81a4-7c5e35ed56f9.png)
WIth JS disabled:
![image](https://user-images.githubusercontent.com/1344898/101932094-36977a80-3bd2-11eb-9bfc-71b396bbd9b1.png)

**Comment by with-heart** [comment]
Can you select the same element for both pics? 😁 Little hard to compare the two here
