### ISSUE TITLE
useDisclosure: TS Types are possibly undefined

### ISSUE THREAD

**Issue by JClackett** [chakra-ui/chakra-ui#276]
**Describe the bug**
The values returned from the useDisclosure hook are possible undefined, meaning i have to accommodate for this all over the place

**Expected Behavior**

```ts
isOpen: boolean
onClose: () => void
onOpen: () => void
```

**To Reproduce**
Inspect the useDisclosure types

**Suggested solution(s)**
Make not undefined :)

**Comment by segunadebayo** [comment]
Hi @JClackett,

I just checked this again. Doesn't seem to have an issue and it's not "possibly undefined"
Check here: https://codesandbox.io/s/chakra-ts-starter-e5rgt

I'm not sure why it says that for you, perhaps you could share a codesandbox TS link for this, or a quick screen recording, inspecting the types.

**Comment by JClackett** [comment]
Hmmm, in the example you gave you're using v0.3.1 if you use the latest (v0.4.1) the typescript definitions change to:

```ts
interface IDisclosure {
  /**
   *
   */
  isOpen?: boolean;
  onOpen?: () => void;
  onClose?: () => void;
  onToggle?: () => void;
}
```

**Comment by segunadebayo** [comment]
Ah. I see. Thanks for that observation

I merged a PR that fixed this. I've just released an update that fixes this. Kindly upgrade.

If this issue persists, I'll re-open this issue.

Cheers.

**Comment by segunadebayo** [comment]
You can check it by reviewing this update: https://codesandbox.io/s/chakra-ts-starter-v5g1y

**Comment by JClackett** [comment]
I also have the same for the useColorMode types

**Comment by segunadebayo** [comment]
I've just fixed that as well
