### ISSUE TITLE
Popover sticks out of Box with overflow = 'scroll'

### ISSUE THREAD

**Issue by YoungeonLee** [chakra-ui/chakra-ui#2760]
# 🐛 Bug report

Popover sticks out of Box with overflow = 'scroll'

## 💥 Steps to reproduce

1. Make a Box with overflowY='scroll' with fixed height
2. Put Popovers inside of the box that total height is greater than the parent box
3. There are two scroll bars (one for the box and one for the body)
4. As you scroll down from the box, the scroll bar of the body decreases, eventually goes away

## 💻 Link to reproduction

https://codesandbox.io/s/dank-smoke-m6q8l?file=/src/App.js

## 🧐 Expected behavior

All popovers should be contained in the parent div (the body shouldn't be scrollable for the linked reproduction)

## 🧭 Possible Solution

I can set document.body.overflow = 'hidden' for my use case, but this may not fit all cases

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       1.0.3     |
| Browser          |   Google Chrome 87.0.4280.88         |
| Operating System |    MacOs        |

## 📝 Additional information

scroll bar appears for the body
![Screen Shot 2020-12-12 at 11 00 13 AM](https://user-images.githubusercontent.com/58812396/101969719-4c0bb380-3c69-11eb-937d-4040983a8027.png)

scroll bar disappears for the body when you scroll to the bottom of the box
![Screen Shot 2020-12-12 at 11 00 29 AM](https://user-images.githubusercontent.com/58812396/101969724-55951b80-3c69-11eb-890d-15250459f167.png)

I think the problem is related to the Popovertrigger component since the problem goes away if I delete it

**Comment by santialbo** [comment]
There's an existing issue around this problem #2586

**Comment by sushanyadav** [comment]
To me setting position='relative' to parent help me resolve this issue.

**Comment by Chukwuamaka** [comment]
> 

This solution worked for me, but I also had to stop rendering the popover in a portal because rendering the popover in a portal persisted the issue on my end.

**Comment by Chukwuamaka** [comment]
> To me setting `position='relative'` to parent scrolling container help me resolve this issue.

This solution worked for me, but I also had to stop rendering the popover in a portal because rendering the popover in a portal persisted the issue on my end.
