### ISSUE TITLE
npx create-react-app myappname --template @chakra-ui FAILS

### ISSUE THREAD

**Issue by zmagickap** [chakra-ui/chakra-ui#2765]
# 🐛 Bug report

> Provide a brief description of the bug here

Running npx create-react-app myappname --template @chakra-ui fails.

Message: npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template-@chakra-ui has failed.

The only notable info in the debug log is:
27 error 404 Not Found - GET http://registry.npmjs.org/cra-template- - Not found

I didn't see any instructions of steps I'm supposed to take prior ro running the CRA line, so I'm GUESSING this is a bug?

## 💥 Steps to reproduce

At my root folder (above any React projects), in Terminal, run:
npx create-react-app base --template @chakra-ui

## 🧐 Expected behavior

The React project creation completes wiht the chacra-ui template

## 🌍 System information

vscode  1.51.1
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js 12.14.1

Win 10

**Comment by with-heart** [comment]
Howdy @zmagickap! I've tried installing with a few different versions of `node` and `npx` and haven't run into any issues. Looks like there's a related issue open under the `create-react-app` repo: https://github.com/facebook/create-react-app/issues/10132 

Going to close this as it appears to be an issue with `npm`/`create-react-app` and not Chakra!
