### ISSUE TITLE
Wrong Accordion focus while in Drawer

### ISSUE THREAD

**Issue by TheThirdRace** [chakra-ui/chakra-ui#2771]
# 🐛 Bug report

When using an Accordion within a Drawer and the Accordion has focusable element within it's panel, pressing Tab key puts focus  on those elements even though the Accordion is closed.

## 💥 Steps to reproduce

1. Open codesandbox
2. Open Drawer
3. Press Tab key a couple times and you'll see the focus going on links even though the Accordion panel is closed

You can also reproduce it in the documentation.

## 💻 Link to reproduction

https://codesandbox.io/s/competent-goldstine-uyxs5?file=/src/App.tsx

## 🧐 Expected behavior

When pressing Tab key, focus should NOT be possible on elements within a closed Accordion panel.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.0.3 |
| Browser          |    Chrome 87.0.4280.88 |
| Operating System |   Windows 10 2004         |

## 📝 Additional information

This is a recurring bug, it keeps being fixed and someone else keep breaking it again :(

**Comment by Samic8** [comment]
Interesting. The `.chakra-collapse` element when collapsed in the drawer has `display: block`. 

When used outside of the drawer the accordion in the same state has `display: block`

**Comment by Samic8** [comment]
This is strange.

When I console log out the display value within the Collapse component that has display "block" (when it should have "none"). On each render the display value is "none", but the value in the DOM is "block". It's like something is mutating the DOM after the render.

https://github.com/chakra-ui/chakra-ui/blob/d9696af79a3d9b51af175a90a45579bf78abfeff/packages/transition/src/collapse.tsx#L160

**Comment by Samic8** [comment]
It seems to be something to do with the variants. When I remove it from "ownProps" it fixes the focus in drawer issue and the collapse element is display none as expected.

https://github.com/chakra-ui/chakra-ui/blob/d9696af79a3d9b51af175a90a45579bf78abfeff/packages/transition/src/collapse.tsx#L137

**Comment by TheThirdRace** [comment]
If it can helps, I can confirm the bug wasn't there with Chakra 1.0.0.

There's been a lot of small "optimizations" in the last few releases (1.0.1, 1.0.2, 1.0.3) that were done with the best of intentions, but broke something else. Trying to over optimize the components reduce their flexibility.

Given the multiple repos, it's a bit harder to simply check the files that changed between 2 releases, which makes debugging a big pain... I feel sorry for you :(  If you can figure out in which revision the bug occurs for the first time (1.0.1, 1.0.2 or 1.0.3), at least you'd be able to narrow it down a little.

**Comment by with-heart** [comment]
> Trying to over optimize the components reduce their flexibility.

Let's not get ahead of ourselves here! Bugs are a part of life, especially in a large project with only a few maintainers. It's to be expected. We just need to get it fixed and make sure we write a test this time to guarantee it doesn't happen again.

**Comment by with-heart** [comment]
Looks like this works fine in 1.0.0 and 1.0.1 and doesn't work in 1.0.2 and 1.0.3.

**Comment by Samic8** [comment]
Might commit at d6f23b8 fixes the issue but breaks the exit animation... 
That was more me just trying to learn how framer-motion works.

**Comment by TheThirdRace** [comment]
> Let's not get ahead of ourselves here! Bugs are a part of life, especially in a large project with only a few maintainers. It's to be expected. We just need to get it fixed and make sure we write a test this time to guarantee it doesn't happen again.

I know I know, I'm with you there.

I must admit there's a bit of frustration on my end. I've been using Chakra since 0.8.4, like a month or two before the RC, and everything was working pretty nicely. But when `1.0.0-rc.6` hit with the changes from Framer-Motion, I had to throw away Preact and move to React, increasing my bundle by 60KB (40KB for React, 20KB for Framer-motion), which was a 50% increase at the time. Since then, every revision I integrate has broke something that worked flawlessly before...

Some of the regression are easy to spot, e.g. the whole site freeze on load (100% CPU, that's when I had to throw Preact away). Some are a bit more puzzling, e.g. the layout of my site completely changed (useMediaQuery stopped working in SSG). Some requires manual testing, e.g. the focus on elements that aren't visible (Accordions within Drawer).

The result is a good amount of time spent on migrating for hotfix revisions. The kind of time that should only be required for major revisions :( 

Because of this, I feel Chakra has been "unstable" in the last 2 months, which is a shame because I know how dedicated you guys are. I'm suspecting a lot of people tries to help Chakra without understanding the full extent of what it can do and they break stuff without meaning to. Such is the nature of every programmer, we test in the conditions we know and sometimes we miss things.

I follow Chakra's Discord pretty much every day and try to help whenever I can. It's clear how much work is going into Chakra and I'm absolutely in awe to see how patient Chakra's team is with the community. Every day I see people asking simple questions without even reading the documentation and every day I see you guys go above and beyond to help them. It would drive me completely crazy to be completely honest :)

I'm sorry if my previous comment felt like pointing fingers, it wasn't ill intentioned. I just want to thank you guys for all your hard work.

**Comment by TheThirdRace** [comment]
> My commit at [d6f23b8](https://github.com/chakra-ui/chakra-ui/commit/d6f23b8f8d79a7d46e63900cf39fa020c4fa31bb) fixes the issue but breaks the exit animation...
> That was more me just trying to learn how framer-motion works.

Maybe a hint for the solution...

I'm not really privy to how Framer-Motion works, but every animation library I've tested in React seems to need their own separate element. Trying to combine everything on the same element seems to break the animation itself.

I personally went around this by using css classes instead of properties, which allows me to have my cake and eat it too, but it ain't the "React" way... on the plus side, it's a lot less code in the bundle than importing an animation library. (I understand it's a moot point given Chakra now requires Framer-Motion anyway...)

Thus, maybe making sure the animation is on it's own element would help separating the animation from the content you're trying to show/hide.

I might be completely wrong, take this with a grain of salt.

**Comment by segunadebayo** [comment]
Hey @TheThirdRace,

This wasn't an issue caused by Chakra UI. It was a breaking change in `framer-motion` and upgrading to v3.0 fixes the focus problem.

I understand that it can be frustrating sometimes, just like Mark mentioned, you need to be a bit more kind and considerate when raising issues like this. Bugs are a part of every software and we'll do our best to fix them as soon as we can.

Cheers.
