### ISSUE TITLE
[NumberInput] Asymmetric value and onChange parameter

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#278]
**Describe the bug**

The value of `NumberInput.value` has a type of `number | undefined`, while `NumberInput.onChange` receives `number | null` as a parameter.

**Suggested solution(s)**
`NumberInput.value` should also be intentionally nullable, as described by #243.

**Comment by segunadebayo** [comment]
I've looked into this and it's quite tricky.

Here are the scenarios that play out:

- If we return just `number  | null` in the onChange callback, then decimal values won't be allowed. When you type "3.", you would get back "3"

- It sounds like a good idea to allow `null` and internally set the input's value to `""` but I don't see the benefits if my first point can't be achieved.

**Possible Options:**
- onChange will have to pass `number | string` sadly, to allow for decimal inputs
- onChange will pass `value: string` and `valueAsNumber: number` so you (the user) can handle any use case in-between.

**Comment by kripod** [comment]
I’d personally use a string, or encapsulate the inner state of the component to disallow emitting `onChange` when only a decimal point is appended to the end. The latter case would allow using a `number` as the `value` prop and the parameter of `onChange`.

**Comment by segunadebayo** [comment]
I thought about that and tried it. Here are my thoughts:

1. We'd be switching between controlled and uncontrolled mode. As far as I know, that's not good practice. If it's controlled, I'd like it to be "fully" controlled, and vice-versa.

2. If the `defaultValue` is `3.45`, pressing `Backspace` up until `3.`. If we disallow emitting onChange when there's a decimal point appended, the value will always be `3.` except if the user deletes all (in annoyance 😅).

3. Consider the scenario where the user passes the `precision` prop which rounds the value to specific decimal points. So if the `value` is `3.4` and precision is `2`, the expected output is `3.40` which isn't possible if we return a `number`.

For now, the onChange callback will pass `string | number`, sadly.

I hope you understand what I mean. If you can hack it without any issues, I'd be happy to take a look.

**Comment by segunadebayo** [comment]
I've fixed this type problem. value and onChange will now return `string | number` following our conversation.

I'll release a patch in a couple of hours

**Comment by kripod** [comment]
I had some time to experiment with the inner state concept I've [outlined above](https://github.com/chakra-ui/chakra-ui/issues/278#issuecomment-561712561). While working on an implementation, I realized that it's not even remotely as straightforward to make as I would've thought.

My `NumberInput` is available as [a gist](https://gist.github.com/kripod/a0fde82708df64c35fbf1521f951374f), along with [a live demo](https://codesandbox.io/s/react-numberinput-1fc8h).

**Comment by kripod** [comment]
In the meantime, I came up with a more elegant solution, shown in [this CodeSandbox](https://codesandbox.io/s/react-numberinput-v2-v9sgk). The gist has also been [updated](https://gist.github.com/kripod/a0fde82708df64c35fbf1521f951374f) to reflect the changes.

**Comment by kripod** [comment]
I've just released [react-typed-inputs](https://github.com/kripod/react-typed-inputs), which aims to provide a solution by utilizing inner state. As a bonus, `clampAfterBlur` and `roundAfterBlur` options are available.

When overriding `type="number"` with `type="text"`, the following input sequence can be input without a `null` result, as seen in this [live demo](https://codesandbox.io/s/zealous-blackwell-4z86f):

```
12 -> 12. -> 12.3 -> 12.
```

Unfortunately, React has [a bug](https://github.com/facebook/react/issues/17609) which results in the decimal point being clamped at the end, resulting in `12` instead of `12.` inside the field. On the bright side, Preact works fine and React [will also be fixed](https://github.com/facebook/react/issues/17609#issuecomment-566345149).
