### ISSUE TITLE
Tables are not getting rendered

### ISSUE THREAD

**Issue by krankj** [chakra-ui/chakra-ui#2782]
# 🐛 Bug report

> Provide a brief description of the bug here

On using the Chakra **table** component after referring [here](https://chakra-ui.com/docs/data-display/table), I am getting the following error while using it:

_Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined._

However changing the import from `import { ... } from "@chakra/react"` to  `import { ... } from "@chakra/table"` , does render the table and its content, but without any CSS styling.

## 💥 Steps to reproduce

> Clear and concise reproduction steps are important for us to be able to triage
> your issue in a timely manner

1. Go to '[Table](https://chakra-ui.com/docs/data-display/table)' and follow the documentation.
2. Use the Table component in your react app.
3. See error: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

## 💻 Link to reproduction

> Please create a minimal reproduction in CodeSandbox
>
> 
>   [Codesandbox link](https://codesandbox.io/s/github/chakra-ui/codesandbox-react-js-template/tree/master?file=/src/App.js:384-998)
Please note, that the example is functioning in the sandbox link provided above but is not in my local env.
>
> - TypeScript Template:
>   [TypeScript CodeSandbox template](https://codesandbox.io/s/github/chakra-ui/codesandbox-react-ts-template/tree/master)

## 🧐 Expected behavior

> Tell us what you expect to happen.

Table should be rendered on my local app.

## 🧭 Possible Solution

> Not compulsory, but suggesting a fix would be great!

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |    1.0.0        |
| Browser          |     Chrome        |
| Operating System |     Windows 10       |

## 📝 Additional information

- Screenshots or code
- Notes or link to ideas

**Comment by TimKolberger** [comment]
Please update @chakraui/react to version 1.0.3.

**Comment by krankj** [comment]
Ah! This works! 
Thank you.
