### ISSUE TITLE
Using chakra on a forwardRef component removes the inner structure

### ISSUE THREAD

**Issue by fredshevek** [chakra-ui/chakra-ui#2785]
# 🐛 Bug report

If `chakra` is used on a product that has already been 'forwardRefed' then the inner components are removed and only `children` is kept
## 💥 Steps to reproduce

Check the CodeSandbox link

## 💻 Link to reproduction

https://codesandbox.io/s/musing-lichterman-f0odu?file=/src/App.js

## 🧐 Expected behavior

The inner structure to be maintained

## 🧭 Possible Solution

> Not compulsory, but suggesting a fix would be great!

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.0.3      |
| Browser          |     Chrome Version 87.0.4280.88 (Official Build) (x86_64)       |
| Operating System |   macOS Catalina         |

## 📝 Additional information

- Screenshots or code
- Notes or link to ideas

**Comment by TimKolberger** [comment]
In your codesandbox the `Container` component accepts the `as` prop. The chakra factory function creates a new component (`CContainer`) which accepts the `as` prop as well. And it won't  pass it through - this is intended.

The as prop replaces the hole rendered component - not just its children. With this behaviour it is not possible to maintain the structure.

```tsx
const CContainer = chakra(Container);
<CContainer as="c">Hello World!</CContainer> // as="c" replaces the component `Container`
```

You can apply the as prop inside a new component in the chakra factory:

```tsx
const NextContainer = chakra(props => <Container as="c" {...props} />);
<NextContainer>Hello World!</NextContainer> 
```

**Comment by fredshevek** [comment]
Thank you @TimKolberger
