### ISSUE TITLE
Double submit on Editable.

### ISSUE THREAD

**Issue by sergeikabuldzhanov** [chakra-ui/chakra-ui#2788]
# 🐛 Bug report

> Provide a brief description of the bug here

Editable currently doesn't check whether it is in edit mode before submitting, which can lead to double submit of the same data in some cases, can be especially nasty if you have some kind of API call attached to it.

## 💥 Steps to reproduce

> Clear and concise reproduction steps are important for us to be able to triage
> your issue in a timely manner

1. Go to [codesandbox example](https://codesandbox.io/s/reverent-cookies-y9t01?file=/src/index.tsx)
2. Click on the editable and enter edit mode
3. Press enter to commit changes and exit edit mode
4. Click anywhere else on the page to lose the focus from the editable
5. Watch the editable value being submitted for a second time

## 💻 Link to reproduction

[Here](https://codesandbox.io/s/reverent-cookies-y9t01?file=/src/index.tsx)

## 🧐 Expected behavior

Editable doesn't submit the changes if it is not in edit mode.

## 🧭 Possible Solution

Add a simple check to the onBlur prop in the use-editable file.
```typescript
  var onBlur = (0, _react.useCallback)(function () {
    if (submitOnBlur && isEditing) {
      onSubmit();
    }
  }, [submitOnBlur, isEditing, onSubmit]);
```

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       1.0     |
| Browser          |       Firefox Developer edition 84.0b8     |
| Operating System |     Windows 10       |

## 📝 Additional information

- Screenshots or code
- Notes or link to ideas

**Comment by with-heart** [comment]
Looks like this only works the way we expect it to on Chrome. Tested with Safari and it's having the same issue.

**Comment by sergeikabuldzhanov** [comment]
Seems like in Chrome focus shifts to the chakra root once you hit enter and in firefox it stays on the input tag of the editable and that's what causes it to submit the second time once you shift focus somewhere else. Actually not sure what is the intended behavior here but logically I'd say it would make sense if data only gets submitted at the same time you change away from edit mode, regardless of focus management.

**Comment by bkiac** [comment]
We still see this issue with `chakra@1.8.1`

**Comment by VitiaCatDragon** [comment]
I have this issue in Firefox 103.0.1 with chakra@2.2.4

**Comment by helgardferreira** [comment]
This is still an issue with @chakra-ui/react@2.8.2. Can we please get some visibility on this?
