### ISSUE TITLE
Add Collapse from Right or Left side

### ISSUE THREAD

**Issue by nicolascavallin** [chakra-ui/chakra-ui#2791]
# 🚀 Feature request

It would be useful if the Collapse component could also be used horizontally. Instead of Drawer component, it would be to use as an additional panel, for example to the right of a chat window.

**Comment by vkmita** [comment]
I would like this feature as well!

**Comment by jfobrien29** [comment]
Hey! Would appreciate this as a feature also. In the meantime looking into other solutions, will report back here.

**Comment by anubra266** [comment]
cc @lazarnikolov94

**Comment by segunadebayo** [comment]
We think this is a feature that can be implemented in user-land using `framer-motion`.

Here's a quick recipe to help achieve this:
https://codesandbox.io/s/horizontal-collapse-fmq66?file=/src/App.tsx

```jsx
import { useDisclosure } from "@chakra-ui/react";
import { motion } from "framer-motion";
import { useState } from "react";

export default function App() {
  const { getButtonProps, getDisclosureProps, isOpen } = useDisclosure();
  const [hidden, setHidden] = useState(!isOpen);

  return (
    <div>
      <button {...getButtonProps()}>Toggle</button>
      <motion.div
        {...getDisclosureProps()}
        hidden={hidden}
        initial={false}
        onAnimationStart={() => setHidden(false)}
        onAnimationComplete={() => setHidden(!isOpen)}
        animate={{ width: isOpen ? 500 : 0 }}
        style={{
          background: "red",
          overflow: "hidden",
          whiteSpace: "nowrap",
          position: "absolute",
          right: "0",
          height: "100vh",
          top: "0"
        }}
      >
        welcome home
      </motion.div>
    </div>
  );
}
```

We won't be adding this to the core of Chakra UI for now. Thanks for understanding

> Please take this as a temp decision, if we see the need for it in the future, we'll definitely add it.
