### ISSUE TITLE
PWA docs

### ISSUE THREAD

**Issue by fandy** [chakra-ui/chakra-ui#2793]
# 🚀 Feature request

Make the docs a PWA

## 🧱 Problem Statement / Justification

Chrome allows you to install PWAs so they can be opened and browsed like a native app. Coming from Material UI, it really makes documentation digging faster.

## ↩️ Alternatives
* Add to Dash docs
* Add to Chrome omnisearch?

**Comment by with-heart** [comment]
Great request!

**Comment by fandy** [comment]
This should be pretty easy to do. Would you like me to do a PR for it @with-heart?
