### ISSUE TITLE
Auto grow input fields, or specify # of lines for textarea

### ISSUE THREAD

**Issue by fandy** [chakra-ui/chakra-ui#2799]
# 🚀 Feature request

Create an input component that starts with a single line (or X lines), and grows as you add more lines, up to a certain height.

## 🧱 Problem Statement / Justification

Auto grow is a good UX for cases like creating a chatbox, where you may type a multi-line message and see what you've written, but also don't want to be presented with a large input field right away (esp if you plan on typing a single line).

## ✅ Proposed solution or API

```
<Textarea h="auto" autoGrow={2} />
```

By default `autoGrow` is false, which maintains the current behavior. Passing a number allows it to grow the height of the input to that many lines.

## 📝 Additional Information

Current behaviour:
![Kapture 2020-12-15 at 20 31 16](https://user-images.githubusercontent.com/19108762/102293172-85b41700-3f14-11eb-820a-d5376b40de3c.gif)

**Comment by santialbo** [comment]
This has been discussed before on
https://github.com/chakra-ui/chakra-ui/issues/670
https://github.com/chakra-ui/chakra-ui/issues/2524

**Comment by fandy** [comment]
> This has been discussed before on
> 
> https://github.com/chakra-ui/chakra-ui/issues/670
> 
> https://github.com/chakra-ui/chakra-ui/issues/2524

Ah sorry, I didn't see that. Even better that this isn't built in Chakra and we can use a robust library.
