### ISSUE TITLE
Permanent drawer (feature-request)

### ISSUE THREAD

**Issue by checkmatez** [chakra-ui/chakra-ui#28]
Would be nice to have a drawer that is always on screen, without overlay on the rest of the window. Something like https://material-ui.com/components/drawers/#permanent-drawer

Common use case - application wide menu.
Thanks for amazing library!

**Comment by segunadebayo** [comment]
Thanks for your suggestion @checkmatez ,

This is currently work in progress and will be released soon.

**Comment by openarun** [comment]
Any update on this please ?

**Comment by MAfzalKhan1997** [comment]
Any update on this ?

**Comment by hb12DevTn** [comment]
Any update on this feature?

**Comment by slackermorris** [comment]
any update on this feature? thanking you!

**Comment by Otoru** [comment]
Any update on this please ?

**Comment by AlvaroLuken** [comment]
Any update on this? Thanks!
