### ISSUE TITLE
[CheckBox] variantColor not accepting custom color object any more 

### ISSUE THREAD

**Issue by omarkhatibco** [chakra-ui/chakra-ui#280]
**To Reproduce**
1. just update to v.5.0
2. in `theme.js` in Color object make a new color `colorTest`
3. in `CheckBox`  component make `variantColor="colorTest"`
4. you will see the error.

**Suggested solution(s)**
we need a way to transfer custom theme value to types also.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 0.5.0

**Comment by JClackett** [comment]
I have this for the Button component also, i added a "primary" color to the default theme like so:
```js
const customTheme = {
  ...theme,
  colors: {
    ...theme.colors,
    primary: "#f48d82",
  },
```

but then when using variantColor="primary" on a button the button becomes fully transparent, have i missed something here?

demo here: https://codesandbox.io/s/chakra-ts-starter-ny9bw

Thanks

**Comment by DouglasGabr** [comment]
@JClackett I think you must provide the shades of your primary color (50, 100, 200, 300...), being 500 the actual color. https://codesandbox.io/s/chakra-ts-starter-u5cty

**Comment by DouglasGabr** [comment]
The other shades are used in `:hover` and `:focus`

**Comment by segunadebayo** [comment]
This for answering this @DouglasGabr! I'm going to close this out for now.

I'll improve the docs to reflect this, as it's a common mistake.

**Comment by omarkhatibco** [comment]
Hi @segunadebayo  
it's still a bug here and the problem is not solved

**Comment by segunadebayo** [comment]
@omarkhatibco Send me a codesandbox for this and I'll look into it.

As for the type definition, I'll update it to support custom values. Will release an update today.

**Comment by omarkhatibco** [comment]
@segunadebayo I just updated my comment 

I think with typeScript we need a dynamic types for things in `theme.js`

here is my codesandbox 
https://codesandbox.io/s/chakra-ts-starter-siunw

**Comment by omarkhatibco** [comment]
@segunadebayo  
I found some bugs in Typescript definition so do you prefer to open an issue or a PR ?

**Comment by segunadebayo** [comment]
I see. This is related to the types for the `variantColor` not that `variantColor` does not work with custom color objects.

For now, I thought it changing the `variantColor` type to `string` so users can freely pass any value and emit some warning if they pass the wrong values not in the theme.

What do you think?

**Comment by segunadebayo** [comment]
> @segunadebayo
> I found some bugs in Typescript definition so do you prefer to open an issue or a PR ?

Is this related to the `variantColor?: VariantColor` part of the code?

**Comment by omarkhatibco** [comment]
> I see. This is related to the types for the `variantColor` not that `variantColor` does not work with custom color objects.
> 
> For now, I thought it changing the `variantColor` type to `string` so users can freely pass any value and emit some warning if they pass the wrong values not in the theme.
> 
> What do you think?

I think it's ok for now

**Comment by omarkhatibco** [comment]
> > @segunadebayo
> > I found some bugs in Typescript definition so do you prefer to open an issue or a PR ?
> 
> Is this related to the `variantColor?: VariantColor` part of the code?

no it's too many other things 

for example if you use `Box` as  `iframe` the prop `src` is not acceptable 

check the same codesandbox again 

https://codesandbox.io/s/chakra-ts-starter-siunw

**Comment by segunadebayo** [comment]
I'm aware of the issue with the `as` prop and we're currently tackling that in the `dev-ts` branch.

**Comment by omarkhatibco** [comment]
@segunadebayo  some missing css props like `filter` or `backdropFilter` ?

**Comment by segunadebayo** [comment]
Please add type issue you notice as a comment here #205. When we work on that aspect, we'll resolve it.

As a walk around, you can definitely use the `css` prop from emotion to that those css properties.

**Comment by segunadebayo** [comment]
For emotion `css` to work you need to add the jsx pragma at the top of the file.
`/**jsx @jsx */`

**Comment by omarkhatibco** [comment]
> For emotion `css` to work you need to add the jsx pragma at the top of the file.
> `/**jsx @jsx */`

@segunadebayo  it worked , thanks for you.

**Comment by segunadebayo** [comment]
Great! I'll release an update to the checkbox `variantColor` based on our conversation.

Thanks for using Chakra.
