### ISSUE TITLE
Typescript: has no exported member 'Table'

### ISSUE THREAD

**Issue by vecdoor** [chakra-ui/chakra-ui#2805]
# 🐛 Bug report

import {
  Box,
  Flex,
  Heading,
  IconButton,
  SimpleGrid,
  **Table,
  Tbody,
  Td,**
  Text,
  **Th,
  Thead,
  Tr,**
} from '@chakra-ui/react';

the bold imports cannot be found...

**TS2305: Module '"../../../node_modules/@chakra-ui/react/dist/types"' has no exported member 'Table'.**

## 🧭 Possible Solution

please deliver types

**Comment by segunadebayo** [comment]
Hi @vecdoor, kindly upgrade to the most recent version of Chakra UI to get access to the Table component.

PS: If the issue still persists, let us know the version of Chakra UI you are on and we'll take a look.
