### ISSUE TITLE
Add required version tag for new packages/functionality

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#2807]
# 🚀 Feature request

New features/components/functionality should have a version number badge attached so that users know which specific version of `@chakra-ui/react` they need to have installed in order to access the feature/component/functionality.

## 🧱 Problem Statement / Justification

An example of this issue is #2805, where `Table` was added in `1.0.3` but a user on `1.0.2` reported that it was not exported.

## ✅ Proposed solution or API

[XState](https://xstate.js.org) does this really well with their docs. 

For entirely new areas of functionality, the page title receives a version badge:

![image](https://user-images.githubusercontent.com/1954752/102420677-ad68b500-3fd0-11eb-8c4c-1a49399714d4.png)

New features added within areas also receive a version badge:

![image](https://user-images.githubusercontent.com/1954752/102420712-bd809480-3fd0-11eb-96a6-0089ca03a422.png)

Screenshots are from https://xstate.js.org/docs/guides/actors.html.

**Comment by segunadebayo** [comment]
This makes sense @with-heart. I'll take a look at how to do that.

**Comment by segunadebayo** [comment]
I added this recently to the docs
