### ISSUE TITLE
Tooltip with delay doesn't handle blur

### ISSUE THREAD

**Issue by Jamesgilje** [chakra-ui/chakra-ui#2814]
# 🐛 Bug report

It seems Tooltips with OpenDelay on clickable elements don't correctly cancel themselves when focus moves to another element via click (this same situation seems to work fine when navigating with the keyboard). 

## 💥 Steps to reproduce

In [this CodeSandbox](https://codesandbox.io/s/practical-margulis-te27r?file=/src/index.tsx)
1. click each button in quick succession
2. all three tooltips will appear

![Kapture 2020-12-17 at 09 23 28](https://user-images.githubusercontent.com/12547640/102507277-aaf67180-4049-11eb-979f-f7842ec3dbc2.gif)

## 🧐 Expected behavior

Tooltip should appear after it's delay only if focus or hover is still on it's trigger element

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.0.3      |

## 📝 Additional information

Similar/Related issues
-#319
-#2503

**Comment by avaragado** [comment]
The best tooltip implementation I’ve seen so far is from [Reach UI](https://reach.tech/tooltip/), which aims to match native UI tooltip behaviour. In particular it has global timeouts: when a tooltip is visible, moving the mouse to an adjacent element with a tooltip shows the new tooltip immediately.
