### ISSUE TITLE
Unified architecture for defining custom styles

### ISSUE THREAD

**Issue by ianstormtaylor** [chakra-ui/chakra-ui#2821]
Hey, thanks for Chakra, I've been using it to prototype a few different projects and it makes getting started quickly very easy. I've noticed though that customizing Chakra does not feel so easy, and I think it's partly because there's a lack of overall API design, so I wanted to open an issue to write up the inconsistencies/problems I saw...

I think the big issue I see is that there are too many ways of solving the same problem in Chakra, which generally leads to confusion as to when to use each. But before getting into that, even just looking at the naming system it feels inconsistent:

- There are "text styles" in `theme.textStyle` and "layer styles" in `theme.layerStyle`, but for some reason "global styles" live in `theme.styles.global`.

- There are "size variants" that are given special treatment in `Component.sizes` but "visual variants" are all grouped into `Component.variants` and only one can be active at a time.

- This all gets even more complex when trying to use `parts` to update the styles of groups of components all at once.

I feel like there are too many different features at odds here. And it makes me wonder if things could be simplified to using the "variants" concept more across the entire system. For example, I really like how [Stitches handles variants](https://stitches.dev/docs/variants) where it is just a mapping that you have full control over. Which would allow for things like...

```tsx
<Button size="sm" scheme="red" fill="solid">...</Button>
```

…and it could all be customized in the same consistent way.

Similarly, the "text styles" and "layer styles" feel weird as these separate concepts that are special-cased for global styles. It feels like something that could be implemented as simple components instead. Or, if they really need to exist as global groups of styles, why not allow for "global variants" which could solve the exact same use case:

```ts
const theme = {
  ...
  variants: {
    textStyle: {
      caption: { ... },
      heading: { ... }
    }
  }
}
```

```tsx
<Box textStyle="caption">...</Box>
```

I think the existing APIs could benefit from some consolidation so that there are fewer concepts to learn and ways of customizing the same thing.

**Comment by ianstormtaylor** [comment]
Still an issue I think.

**Comment by segunadebayo** [comment]
Thanks for the ideas mentioned here!

Converting this to a discussion as I don't think it's an issue per se.
