### ISSUE TITLE
Editable form overlows on multiple paste 

### ISSUE THREAD

**Issue by peersky** [chakra-ui/chakra-ui#2826]
# 🐛 Bug report
 If copy pasting large text block in to <Editable> window - content will overflow parent container

## 💥 Steps to reproduce

0. copy these numbers in the buffer -> `123`
1. Go to https://chakra-ui.com/docs/form/editable
2. Activate input 
3. hold cntrl+v for a while
![Screenshot 2020-12-18 at 17 03 10](https://user-images.githubusercontent.com/61459744/102628854-07918380-4153-11eb-8ab1-258b01626afe.png)

**Comment by TimKolberger** [comment]
Please apply the CSS prop `wordBreak="break-all"`. See [MDN word-break](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) for further reference.

I am closing this, because it is not an issue with chakra-ui.
