### ISSUE TITLE
useMediaQuery does not work with SSR styles

### ISSUE THREAD

**Issue by hutber** [chakra-ui/chakra-ui#2827]
I have tried to create a codepen for it, but was unable to: https://codesandbox.io/s/no-margin-chakra-forked-zcygd?file=/src/App.tsx

The issue seems to be that everything is reported correctly, the only issue being the styles are out of alignment with what is being rendered and reported:

```
  const [baseLg] = useMediaQuery((max-width: 35em))
  const marginX = `${space[baseLg ? 1 : 0]} !important`
  console.info(marginX)

  return (
      <GridItem
        data-marginX={marginX}
        mx={marginX}
      >
)
```

Output:
![image](https://user-images.githubusercontent.com/1344898/102617177-a9ec3f80-4130-11eb-948e-a88a3255bcbd.png)

So on initial load, the text rendered is correct, but the styles are incorrect. Then when i change from portrait to landscape back to portrait, the styles are correct. As seen here:

![image](https://user-images.githubusercontent.com/1344898/102631700-f68e4580-4145-11eb-9957-d9f916d3c68a.png)

I am unsure, but I assumed that useMediaQuery would generate css media queries, rather than imitate media queries with JS.

It may not be an issue, but it feels like one to me :)

**Comment by callumflack** [comment]
Might be due to server-side rendering? [There's a note in the docs about this.](https://chakra-ui.com/docs/hooks/use-media-query)

To get a custom media query on first page, I use the `sx` prop:

```js
sx={{
  "@media screen and (min-width: 375px) and (max-width: 440px) and (max-height: 900px) and (orientation: portrait)": {
    height: "85vh",
  },
}}
```

**Comment by ljosberinn** [comment]
> I assumed that useMediaQuery would generate css media queries, rather than imitate media queries with JS.

No, it's adding `window.matchMedia()` listeners, returning booleans depending on current screen size. It's merely a convenient abstraction of doing that yourself.

**Comment by segunadebayo** [comment]
Yes, useMediaQuery is a client-side only hook since it uses `window.matchMedia`. For this, I'd recommend using a media query style object in `sx` or `css` prop, like @callumflack suggested.

You can also consider tweaking the breakpoint in the theme as well and passing responsive values (as object or array).

Cheers.

**Comment by ArenoRobert** [comment]
What would be the prefered way in rendering different components based on width?
Different mobile or desktop menu component based on device with?

**Comment by Romej** [comment]
I believe you would need to create a custom hook to detect the viewport's dimensions.

Here is some code that does the job pretty well :

`export default function useWindowSize() {
  const isSSR = typeof window !== "undefined";
  const [windowSize, setWindowSize] = React.useState({
    width: isSSR ? 1200 : window.innerWidth,
    height: isSSR ? 800 : window.innerHeight,
  });

  function changeWindowSize() {
    setWindowSize({ width: window.innerWidth, height: window.innerHeight });
  }

  React.useEffect(() => {
    window.addEventListener("resize", changeWindowSize);

    return () => {
      window.removeEventListener("resize", changeWindowSize);
    };
  }, []);

  return windowSize;
}`

Full explanations can be found here : [](https://dev.to/reedbarger/how-to-create-a-usewindowsize-react-hook-2bcm)

**Comment by k-utsumi** [comment]
I found this solution.
https://github.com/chakra-ui/chakra-ui/issues/3124#issuecomment-773972513

Also, I heard that `useBreakpointValue ` supports SSR, so I tried it and it worked.
Maybe like this.
```
  const isMinWidthLg = useBreakpointValue({ lg: true })

  return <GridItem mx={isMinWidthLg ? 1 : 0}>
  // or
  return <GridItem {...(isMinWidthLg && { mx: 1 })}>
```

**Comment by natBizitza** [comment]
> Refactor/minor issues clean up NTUCourse-Neo/ncn-frontend#78

I use `useMediaQuery` with min-height value and this type of conditions `<Flex fontSize={isHeightSmallerThan1000 ? '2xs: 'xs'}>`. It causes an awful CLS. What alternatives do we have? `useBreakpointValue`?
