### ISSUE TITLE
Ability to set default colorscheme for all components

### ISSUE THREAD

**Issue by BojanStipic** [chakra-ui/chakra-ui#2828]
# 🚀 Feature request

> Please describe your request in one or two sentences.

I would find it very convenient if it would be possible to set the default colorscheme for all components at once. 

## 🧱 Problem Statement / Justification

> Please provide valid reason(s) why this should added to Chakra UI.
>
> If this feaure is related to a problem you've noticed. Mention it as well

Currently, if you want to change the default colorscheme from blue to red, for example, you have to do it for all of the existing components individually:

```javascript
const theme = extendTheme({
  components: {
    Button: {
      defaultProps: {
        colorScheme: "red",
      },
    },
    Tabs: {
      defaultProps: {
        colorScheme: "red",
      },
    },
    // ... etc
  },
});
```

## ✅ Proposed solution or API

> Please provide code snippets, gists, or links to the ideal design or API

It would be more convenient if we could do something like this:

```javascript
const theme = extendTheme({
  config: {
    initialColorMode: "dark",
    initialColorScheme: "red",
  },
});
```

## ↩️ Alternatives

> What alternative solutions have you considered before making this request?

As already mentioned, alternative is to set the default colorscheme for every existing component separately. It is not the end of the world to do it individually for all components, but implementing this feature request would be a great quality of life improvement.

## 📝 Additional Information

> What resources (links, screenshots, etc.) do you have to assist this effort?

N/A

Thank you for this great library and all the hard work put into it! Cheers!

**Comment by BojanStipic** [comment]
Per Stalebot instructions, I am leaving this comment, as I am still interested in this improvement.

**Comment by yuritoledo** [comment]
Per Stalebot instructions, I am leaving this comment, as I am still interested in this improvement. ²

**Comment by segunadebayo** [comment]
Thanks for the request! Considering this isn't a bug, I'll add this to our project board so you can track the progress.

Check it here: https://github.com/chakra-ui/chakra-ui/projects/6

Cheers.

**Comment by jarodburchill** [comment]
This would be awesome!

**Comment by nielsuit227** [comment]
This looks done, awesome work! Cannot find any instructions however?

**Comment by anubra266** [comment]
> This looks done, awesome work! Cannot find any instructions however?

https://github.com/chakra-ui/chakra-ui/commit/07612ce47a7a35dba56f1a7836ceac622b497dfb @nielsuit227

**Comment by SerhatG35** [comment]
This is a great feature but I can't change `colorScheme` depending on the current color mode. There is a function in which we can retrieve the current color mode located in _@chakra-ui/theme-tools_ named `mode` but I couldn't figure out how to implement it with `withDefaultColorScheme`.

**Comment by anubra266** [comment]
@SerhatG35 `withDefaultColorScheme` is not for handling colorModes. The colorMode will ba handled in the component itself.
