### ISSUE TITLE
No data from form with NumberInput and CheckboxGroup with react-hook-form

### ISSUE THREAD

**Issue by mszyma** [chakra-ui/chakra-ui#2832]
# 🐛 Bug report
Hey, I'm not getting data from my form when using NumberInput and CheckboxGroup. It works with the normal input field. I'm using Chakra-UI v1.0.4 with react-hook-form. I've had this issue on v0.8 so I've decided to upgrade but it still happens. 

Please see the attached CodeSandbox. It doesn't work there was well:
https://codesandbox.io/s/recursing-sinoussi-1f1m7?file=/src/addExercise.jsx

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      v1.0.4      |
| Browser          |     Version 1.17.75 Chromium: 87.0.4280.88 (Official Build) (x86_64)
       |
| Operating System |     MacOS 10.15.6 (19G2021)       |

package.json:
"dependencies": {
    "@chakra-ui/react": "^1.0.4",
    "@emotion/react": "^11.0.0",
    "@emotion/styled": "^11.0.0",
    "@hookform/resolvers": "^1.2.0",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "axios": "^0.21.0",
    "bootstrap": "^4.5.3",
    "framer-motion": "^2.9.5",
    "joi-browser": "^13.4.0",
    "jwt-decode": "^3.1.2",
    "moment": "^2.29.1",
    "moment-duration-format": "^2.3.2",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "react-hook-form": "^6.13.1",
    "react-icons": "^4.1.0",
    "react-idle-timer": "^4.5.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^3.4.4",
    "tenorjs": "^1.0.7",
    "validator": "^13.5.2"

**Comment by TimKolberger** [comment]
The chakra component `NumberInput` manages its own state. This is needed to be able to update the value with the stepper buttons.

You need to use the [Controller component from react-hook-form](https://react-hook-form.com/api/#Controller) to make it work. See this [codesandbox](https://codesandbox.io/s/chakra-ui-react-hook-form-hmgl1?file=/src/App.tsx) for a working example.

I am closing this, because it is not an issue with chakra-ui.

**Comment by approached** [comment]
You use a wrong element for ref. Use NumberInputField and not a NumberInput.

Try this:
```js
return (
        <InputWrapper
            id={id}
            name={name}
            label={label}
            required={required}
            register={register}
            errors={errors}
        >
            <NumberInput defaultValue={defaultValue} min={min} max={max}>
                <NumberInputField
                    name={name}
                    placeHolder={placeHolder}
                    ref={register({ required: true })}
                />
                <NumberInputStepper>
                    <NumberIncrementStepper />
                    <NumberDecrementStepper />
                </NumberInputStepper>
            </NumberInput>
        </InputWrapper>
    )
```

**Comment by wazcov** [comment]
Hi. @TimKolberger I just followed the guide in the sandbox you linked (https://codesandbox.io/s/chakra-ui-react-hook-form-hmgl1?file=/src/App.tsx) however, when I use this now with more recent versions of libraries, I get`TypeError: path.split is not a function. (In 'path.split(/[,[\].]+?/)', 'path.split' is undefined)`.

This is the case both in my own application and in the sandbox, when upgrading dependencies to more recent versions.

You can try with the following versions:

`    "@chakra-ui/react": "^1.6.5",
    "@emotion/react": "^11.4.0",
    "@emotion/styled": "^11.3.0",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "axios": "^0.21.1",
    "framer-motion": "^4.1.17",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-hook-form": "^7.12.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",`

Is this a bug in React-Hook-Form or ChakraUI?

**Comment by TimKolberger** [comment]
Thanks for letting me know about the outdated sandbox! 💖 
I updated the sandbox to reflect the breaking changes of react-hook-form.

Unfortunately the solution without the `Controller` component in this comment (https://github.com/chakra-ui/chakra-ui/issues/2832#issuecomment-782593177) introduces a bug if the user uses the IncrementSteppers. Please use the Controller component for all Chakra UI components, except the plain `Input`.

**Comment by wazcov** [comment]
@TimKolberger Thank you for the reply! Fastest reply to a question I've had from any open source page!

I tried the changes you made and it also fixes my app, so that's much appreciated!!

Just a recommendation, is that the sandbox you change the defaults from:

 ```
   defaultValues: {
      name: "Harry Potter",
      amount: 1337,
      pin: "12"
    }
```
    
    to 
    
```
        defaultValues: {
      name: "Harry Potter",
      amount: "1337",
      pin: "12"
    }
```

this is because when you update the number field, and submit, it prints a quoted number (string), so if you are handling the type (such as typescript), the default should be the same type.

Cheers!
