### ISSUE TITLE
Add Steps component

### ISSUE THREAD

**Issue by potty** [chakra-ui/chakra-ui#2836]
# 🚀 Feature request

> Please describe your request in one or two sentences.

It would be useful to have some form of Steps (Stepper) component to show navigation with a certain amount of steps.

## 🧱 Problem Statement / Justification

> Please provide valid reason(s) why this should added to Chakra UI.
>
> If this feaure is related to a problem you've noticed. Mention it as well

I think this is quite common use case and should be part of the library.

## ✅ Proposed solution or API

> Please provide code snippets, gists, or links to the ideal design or API

I really like the Ant Design version of [Steps component](https://ant.design/components/steps/). It would be really nice to have at least some light version of it.

**Comment by potty** [comment]
I can prepare PR for this as I already have something similar.

**Comment by mlonn** [comment]
I would very much like a steps components included in Chakra!

**Comment by potty** [comment]
I'm working on this, depends on how many options it should have. This can be a quite complex component with many parts if everything should be configurable. Currently, I have a working horizontal version in my project. Do we need also a vertical one?

**Comment by mlonn** [comment]
For me a horizontal one is what I need, the vertical one could be added at a later state. Not needed for an MVP

**Comment by segunadebayo** [comment]
Thanks for the request! Considering this isn't a bug, I'll add this to our project board so you can track the progress.

Check it here: https://github.com/chakra-ui/chakra-ui/projects/6

Cheers.

**Comment by bencooper96** [comment]
If anyone needs a temporary work around, I have used the Circle & Progress components together wrapped in a Flex Component. While it is far from perfect, it works for my purposes (+ you get the satisfying animation of the Progress bar increasing).

E.g.)
```
<Flex justify="center" align="center">
   //Step 1
   <Circle layerStyle="selected"> Step 1 </Circle>

   //Step 2
   //The marginX is to allow overlapping  w/ the circles
   //If you do this make sure to include a zIndex value in your Circle layerStyle to put it in front of the progress bar
   <Progress value={props.step > 0 ? 100 : 0} width="full" mx={-4} />
   <Circle layerStyle={props.step > 0 ? "selected" : "base"}> Step 2 </Circle>

   //Step 3
   <Progress value={props.step > 1 ? 100 : 0} width="full" mx={-4} />
   <Circle layerStyle={props.step > 1 ? "selected" : "base"}> Step 3 </Circle>
</Flex>
```

Then you can:

1. create layer styles for your selected/unselected Circles 
2. style progress bars as you please
3. keep a state variable for the step to pass as a prop to the stepper
4. display step-associated content conditionally.

I will say, I fully support a Stepper as a core component but for anyone who needs something quick and dirty, theres this.

Best

**Comment by shreyansh-zazz** [comment]
Come on guys we needs this.

**Comment by potty** [comment]
It's already in Chakra Pro

**Comment by jeanverster** [comment]
Hey guys, I have recently published a steps component for chakra if anyone's interested :) https://github.com/jeanverster/chakra-ui-steps

**Comment by arunvenkates** [comment]
@jeanverster its not flexible I cant Able to change step color particularly

**Comment by theskinnycoder** [comment]
> Hey guys, I have recently published a steps component for chakra if anyone's interested :) [jeanverster/chakra-ui-steps](https://github.com/jeanverster/chakra-ui-steps)

man, this is good
