### ISSUE TITLE
Radio/RadioGroup inconsistency

### ISSUE THREAD

**Issue by diceroll123** [chakra-ui/chakra-ui#2842]
# 🐛 Bug report

Radio components ***only*** seem to work if they're in a RadioGroup.

## 💥 Steps to reproduce

This bug exists even in the live docs under one example, https://chakra-ui.com/docs/form/radio#radio-sizes

## 🧐 Expected behavior

I expect behavior like this: (this is non-chakra)
![ZmjKzfBzZK](https://user-images.githubusercontent.com/1243957/102698272-02831180-41f1-11eb-9790-45838d157f00.gif)

This is what happens:
![z3ekgkqJYj](https://user-images.githubusercontent.com/1243957/102698304-3cecae80-41f1-11eb-90a9-88dd300f455c.gif)

Changing `Radio` out with `input type="radio"` does what I expect:
![4whK5d4W44](https://user-images.githubusercontent.com/1243957/102698321-55f55f80-41f1-11eb-9d37-2ceaa3cc06ec.gif)

But Chakra's Radio buttons are obviously nicer looking.

## Notes

* My radio buttons in each column are tied to the same name. They're in different Tr's and Td's, so putting them in a `RadioGroup` isn't possible for my use case.
* That said, if this were to be fixed, it *might* remove the need for the `Note about name prop` at the bottom of the Radio docs page. I have not dived into the source of the radios, but it's just a theory.

**Comment by cereallarceny** [comment]
@segunadebayo @with-heart I'm also having this problem on 1.0.3. I see that someone in the Blitz community is also having this issue: https://github.com/blitz-js/blitz/issues/1600

**Comment by cereallarceny** [comment]
@diceroll123 I noticed that if you surround your radio sizes example with a `<RadioGroup>` then it should work. However, on my local application, even this doesn't correctly solve the problem.

**Comment by with-heart** [comment]
Seems like there are quite a few things going on with `Radio`/`RadioGroup`/`useRadio`/`useRadioGroup` where things aren't quite syncing up in the expected way.

So far I've investigated the built-in components and their behavior. Individual, uncontrolled `Radio` elements are not working the same way as their raw html element counterparts: https://codesandbox.io/s/radio-radiogroup-dgd37?file=/src/App.tsx

**Comment by with-heart** [comment]
I've identified the cause of the uncontrolled issue.

This line sets a default value for `isChecked` https://github.com/chakra-ui/chakra-ui/blob/83099cb6f50417de38571eb3264d1edf4246d570/packages/radio/src/radio.tsx#L55-L55

which is then passed to `useRadio` https://github.com/chakra-ui/chakra-ui/blob/83099cb6f50417de38571eb3264d1edf4246d570/packages/radio/src/radio.tsx#L72-L77

means that `isControlled` will always be `true` https://github.com/chakra-ui/chakra-ui/blob/f41a231aa7241419aa8bb4a31cca508e19a3a464/packages/radio/src/use-radio.ts#L99-L102

Removing the `|| false` for `isChecked` and passing that through as `undefined` value allows `isControlled` to be `false`.

**Comment by cereallarceny** [comment]
@with-heart  Is this also, by proxy, fixed for Checkboxes? I was having an identical problem there.
