### ISSUE TITLE
Cannot add a Tooltip on a Popover Trigger

### ISSUE THREAD

**Issue by SimonHoiberg** [chakra-ui/chakra-ui#2843]
# 🐛 Bug report

When I try to use a `Tooltip` in combination with a `PopoverTrigger`, the Tooltip prevents the trigger from firing.

## 💥 Steps to reproduce
Consider these example:

### Case A
```jsx
<Popover>
   <PopoverTrigger>
     <Tooltip aria-label='tooltip' label='Click here to open a popover'>
       <IconButton aria-label='open popover' icon={<SomeIcon />} />
     </Tooltip>
   </PopoverTrigger>
   <PopoverContent>....</PopoverContent>
 </Popover>
```
In this case, the tooltip shows, but the popover doesn't get shown when clicking the button.

### Case B
```jsx
<Popover>
   <Tooltip aria-label='tooltip' label='Click here to open a popover'>
      <PopoverTrigger>
         <IconButton aria-label='open popover' icon={<SomeIcon />} />   
      </PopoverTrigger>
   </Tooltip>
   <PopoverContent>....</PopoverContent>
 </Popover>
```

## Example
https://codesandbox.io/s/empty-tdd-c6e57?file=/src/App.js

## 🧐 Expected behavior

I expect both tooltip to show *and* popover content to appear when clicking.

## 🧭 Possible Solution
I haven't got one ready right now, but I'll gladly help out with a PR if you confirm that this is a bug.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | ^1.0.0 |
| Browser          |  Chrome |
| Operating System | Ubuntu |

**Comment by TimKolberger** [comment]
Tooltip and Popover cannot share the same DOM element as trigger element. I think this is a limitation of popperjs.

A possible workaround is to add another element for both cases, but see how the focus state is handled differently.

1. Case A does not return the focus to the origin element after closing the Popover. 
2. Case B returns the focus to the button and triggers the Tooltip

See this [codesandbox](https://codesandbox.io/s/modest-pare-8kn5t?file=/src/App.js)

```tsx
<Popover>
  <Tooltip
    aria-label="tooltip"
    placement="bottom"
    label="Click here to open a popover"
  >
    {/* additional element */}
    <Box display="inline-block">
      <PopoverTrigger>
        <IconButton
          aria-label="open popover"
          icon={<div>Tooltip does show :)</div>}
        />
      </PopoverTrigger>
    </Box>
  </Tooltip>
  <PopoverContent>....</PopoverContent>
</Popover>
```

**Comment by SimonHoiberg** [comment]
Wow, that actually worked.

Not the cleanest, but I can definitely live with it.
Thank you!! 🙌

If this is a well-known and accepted limitation, then I guess this issue can be closed again.
Cheers.

**Comment by Thebigbignooby** [comment]
sandbox links don't work anymore, not sure how to fix them :/

has this bug been fixed or are we still to use a workaround?

**Comment by allister-grange** [comment]
I am still experiencing the issue

**Comment by Enfield-Li** [comment]
> Tooltip and Popover cannot share the same DOM element as trigger element. I think this is a limitation of popperjs.
> 
> A possible workaround is to add another element for both cases, but see how the focus state is handled differently.
> 
> 1. Case A does not return the focus to the origin element after closing the Popover.
> 2. Case B returns the focus to the button and triggers the Tooltip
> 
> See this [codesandbox](https://codesandbox.io/s/modest-pare-8kn5t?file=/src/App.js)
> 
> ```tsx
> <Popover>
>   <Tooltip
>     aria-label="tooltip"
>     placement="bottom"
>     label="Click here to open a popover"
>   >
>     {/* additional element */}
>     <Box display="inline-block">
>       <PopoverTrigger>
>         <IconButton
>           aria-label="open popover"
>           icon={<div>Tooltip does show :)</div>}
>         />
>       </PopoverTrigger>
>     </Box>
>   </Tooltip>
>   <PopoverContent>....</PopoverContent>
> </Popover>
> ```

It worded for me!

**Comment by udidol** [comment]
Ha, the `<Box>` hack actually worked.

In my case, I didn't have the bug described in this issue exactly:
The trigger was still firing when it was supposed to, but the popover got pushed down (in the default "bottom" position) to be positioned **under** where the tooltip was. So when you clicked the trigger, the tooltip disappeared, and the popover appeared, but it appeared all the way below the trigger _below_ where the now-removed tooltip's bottom was.
