### ISSUE TITLE
Tooltip assumes disabled state of its child

### ISSUE THREAD

**Issue by raulrpearson** [chakra-ui/chakra-ui#2849]
# 🐛 Bug report

I wrapped a Button/IconButton with a Tooltip component and disabling the Button/IconButton also disables de tooltip.

## 💻 Link to reproduction

I created a [minimal reproduction on Codesandbox](https://codesandbox.io/s/tooltip-assumes-disabled-state-of-child-uy1t9?file=/src/index.tsx)

## 🧐 Expected behavior

I expected the disabled state of Tooltip to be independent of its children's.

## 🧭 Possible Solution

The workaround I found is to wrap the Button/IconButton in a Box.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI | 1.0.4 |
| Browser | Firefox |
| Operating System | macOS |

## 📝 Additional information

![tooltip](https://user-images.githubusercontent.com/23662058/102772238-d3ef6d00-438f-11eb-8871-2759b62094d5.png)

**Comment by dodas** [comment]
Hey @raulrpearson.

The mouse events are not triggered for disabled elements. This behaviour applies for both native DOM and React events implementation.

Judging from [Tooltip stories source](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/tooltip/stories/tooltip.stories.tsx#L220), the Tooltip not being shown on disabled elements is expected behaviour.

You can workaround it the way you did - wrapping it in another element.

If you [google "tooltip on disabled button"](https://www.google.com/search?q=tooltip+on+disabled+button&oq=tooltip+on+disabled+button&aqs=chrome..69i57j69i60l2.4207j0j1&sourceid=chrome&ie=UTF-8) you will find out this issue applies for all UI libraries.

Hope that helps!

**Comment by raulrpearson** [comment]
Thanks for the explanation and tips, @dodas. I had no idea this was a thing. I'm not convinced that this is a good idea, though. Do we know what the reasoning behind this common API feature is?

**Does it encourage a better UX in the final product?** I don't think it does. Having a tooltip on a disabled control can [explain the reason why this control is disabled](https://ux.stackexchange.com/a/12761). Right now I have to fight the API a bit to make this happen.

Using the `shouldWrapChildren` wraps the button in `<span tabindex="0"></span>`, which makes the disabled button focusable. I'm in two minds about this: on one hand, it might be an annoying waste of time to focus something that's not actionable (and maybe also create problems for screen readers?); on the other, you do get the tooltip on focus, which you might appreciate if you're tabbing your way around the UI. I'm also [not sure a `span` should wrap a `button`](https://stackoverflow.com/a/11314736). This choice might be [coming from Tippy.js docs](https://atomiks.github.io/tippyjs/v6/constructor/#disabled-elements), which is also based on Popper.js.

**Does it provide a better DX?** If the expectation that the tooltip will assume the disabled state of its child is commonplace, maybe that's a good enough reason to have it this way.

But I have a suggestion; it might make sense to keep this behavior but enable an override if the `isDisabled` property is _explicitly_ set in the `Tooltip` component:

```jsx
<Tooltip label="A tooltip">
  <Button isDisabled={true}>This one behaves as currently expected</Button>
</Tooltip>
<Tooltip label="A tooltip" isDisabled={false}>
  <Button isDisabled={true}>This one overrides the currently expected behavior</Button>
</Tooltip>
```

On the other hand, this might still trip some people off, if they're expecting the button's `isDisabled` property to rule when `true`.

Just a thought. I'm definitely not a UX expert and it seems many people have already devoted some time to think about this. My take is that the component's API should afford and easy way to independently control the disabled state of the tooltip and that probably a disabled control shouldn't be focuseable.
