### ISSUE TITLE
[Button | Input] certain components are not compatible with react-beautiful-dnd

### ISSUE THREAD

**Issue by deebov** [chakra-ui/chakra-ui#285]
**Describe the bug**
I am drying to make the components draggable. But components such Button and Input are not working well with dnd. I think there's some problem with the ref prop. Because react-beautiful-dnd requires its ref to be passed to HTMLElement.

**Expected Behavior**
Components such Button and Input should be draggable

**To Reproduce**
- Use this sandbox: https://codesandbox.io/s/delicate-framework-jh0vb?fontsize=14&hidenavigation=1&theme=dark
- List the steps to reproduce the behavior:
1. Try to drag and drop the components from the right panel to the left panel
2. As you will see the button and input components are not draggable

**Comment by JClackett** [comment]
can just wrap the chakra stuff in a normal div?

```
<Draggable draggableId={image.id} key={image.id} index={order}>
      {draggable => (
        <div
          {...draggable.dragHandleProps}
          {...draggable.draggableProps}
          ref={draggable.innerRef}
        >
          <Box pb={4}>
			stuff
		  </Box>
        </div>
	  )}
</Draggable>

```

**Comment by segunadebayo** [comment]
I think @JClackett's idea would work. Kindly try that.

If the issue still persists, I'll re-open this.
