### ISSUE TITLE
Bug: styled not working

### ISSUE THREAD

**Issue by chineduogada** [chakra-ui/chakra-ui#2850]
I tried to add some additional styles, using the `styled` but Instead got this `Server Error
Error: Invalid hook call. Hooks can only be called inside of the body of a function component...` from `Next.js`

import { Flex, styled } from "@chakra-ui/react";

const StyledComponents = styled.div\`
	color: red;
\`;

export default App;

**Comment by dodas** [comment]
`styled` is not a part of the public API.
You can use [chakra factory](https://chakra-ui.com/docs/features/chakra-factory).
