### ISSUE TITLE
Checkbox bubbles onClick event twice

### ISSUE THREAD

**Issue by AJFunk** [chakra-ui/chakra-ui#2854]
# 🐛 Bug report

When a `Checkbox` is the child of an element that has an `onClick` handler, clicking the Checkbox causes the handler to be fired twice.

## 💥 Steps to reproduce

1. wrap a `Checkbox` with a parent that has an `onClick` handler
```
<Box onClick={() => console.log('CLICK!')}>
  <Checkbox>Click Me!</Checkbox>
<Box>
```
2. Click the checkbox and observe that the parent's `onClick` is fired twice

## 💻 Link to reproduction

https://codesandbox.io/s/strange-thunder-v1ccm

## 🧐 Expected behavior

Click handler should only fire once.

This is also a relatively common use case - I am wrapping the checkbox with a parent to create a larger "click area" around the checkbox, and a `isChecked` value is being passed down to the Checkbox to control it.

Adding a `onChange` handler to the Checkbox has no effect.

My current workaround is to detect checkbox clicks and avoid firing the handler:
```
<Box
  onClick={event => {
    if (event.target.nodeName !== 'INPUT') onClick();
  }}
>
  <Checkbox>Click Me!</Checkbox>
<Box>
```

This is obviously a hacky, non-ideal fix

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.0.3       |
| Browser          |       Chrome 87.0.4280.88     |
| Operating System |      macOS Catalina 10.15.3      |

**Comment by santialbo** [comment]
This is how browsers work when you click on a label. When you click on a label a click event is also created on the input. Here's a non-chakra version https://codesandbox.io/s/modest-hoover-43nkk?file=/src/index.js as proof.

The only workaround I can think of is use `as="div"` or something other than `label` in the `Checkbox` element. So that chakra doesn't render a label and clicking on it doesn't create another click event.
https://codesandbox.io/s/sleepy-borg-h936b?file=/src/index.js

**Comment by AJFunk** [comment]
Ahh ok - thanks @santialbo I totally missed that a `label` is always rendered. In my actual implementation, I made the incorrect assumption that no `label` was being rendered because the `Checkbox` did not have any children. I was just doing something like:
```
<Box onClick={...}>
  <Checkbox />
<Box>
```

I think it would be helpful to add something about this in the documentation!

**Comment by hariria** [comment]
I had a similar issue with the `Checkbox` component, however, I had to double click the Checkbox in order for it to select. Does anyone know how to avoid this?

**Comment by AJFunk** [comment]
@hariria if you provide a codesandbox link or something to reproduce the problem I can probably help!

**Comment by vania22** [comment]
@AJFunk 
`
import { ChakraProvider, Box, theme } from "@chakra-ui/react";
import { Checkbox } from "@chakra-ui/react";

export default function App() {
  return (
    <ChakraProvider theme={theme}>
      <div className="App">
        <h1>Hello CodeSandbox</h1>
        <h2>Start editing to see some magic happen!</h2>
        **<div onClick={() => console.log("hello")}>
          <Checkbox />
        </div>**
      </div>
    </ChakraProvider>
  );
}
`

In this example onClick will be fired twice!

**Comment by AJFunk** [comment]
> In this example onClick will be fired twice!
 @vania22 this is expected behavior as @santialbo pointed out. The `Checkbox` renders a `label`, when registers the click handler. This is equivalent to something like:

```
<div onClick={onClick}>
  <label onClick={onClick}>...</label>
</div>
```

To prevent this, you need to either:
1) do not add an `onClick` to the div wrapper and just let the `label` handle it or
2) `<Checkbox as="div">` will render a div instead of a label, so this duplicate click handling will not occur

**Comment by AJFunk** [comment]
The solution of using `as="div"` no longer works as of v1.4.0 https://github.com/chakra-ui/chakra-ui/blob/main/packages/checkbox/CHANGELOG.md#140

@segunadebayo since this is an intended change, is there a known workaround to this problem?

**Comment by AJFunk** [comment]
The only solution I have found post-update is to create an invisible overlay that covers the entire clickable area (including the checkbox) and handle `onClick` events there

**Comment by AJFunk** [comment]
I've found another workaround - style a disabled checkbox to appear like a non-disabled checkbox:
```
// Behaves just like a normal Checkbox but prevents click events from propagating
const CheckboxReadOnly = (props: ElementConfig<typeof Checkbox>) => {
  const variant =
    props.isChecked || props.isIndeterminate ? 'readOnlyChecked' : 'readOnly';
  return (
    <Checkbox
      variant={props.isDisabled ? undefined : variant}
      {...props}
      isDisabled
    />
  );
};
```

in the theme:
```
const theme = extendTheme({
  components: {
    Checkbox: {
      variants: {
        readOnly: {
          control: {
            cursor: 'pointer',
            backgroundColor: 'var(--chakra-colors-white) !important',
            borderColor: 'var(--chakra-colors-gray-300) !important'
          }
        },
        readOnlyChecked: {
          control: {
            cursor: 'pointer',
            backgroundColor: 'var(--chakra-colors-blue-500) !important',
            borderColor: 'var(--chakra-colors-blue-500) !important',
            color: 'var(--chakra-colors-white) !important'
          }
        }
      }
    }
  }
})
```

**Comment by anubra266** [comment]
I'm not seeing any issue here. All that's happening is event bubbling. 
Clicking the `div` does not fire the event twice, clicking the `checkbox` does that, as the event is fired for the `checkbox` then the `div`.

**Comment by jameshoward** [comment]
It's not even bubbling if the `onClick` event fires twice for the same element (the `div`) from a single click. The explanation above makes sense though; the browser fires a click for the `label` and a click for the related `input`. Both then bubble, as you say, and end up on the wrapping `div`.

**Comment by digitaltoad** [comment]
Although this is indeed how bubbling works, unless I'm missing something, I've noticed that I cannot stop propagation from the checkbox. For instance, if a checkbox is in a table row, I want to interact with the checkbox without the click bubbling to the table row. This seems to be related to the fact that a click handler never makes it to the Label on the checkbox. This can be seen in the `getRootProps` returned by `useCheckbox`.

#### getRootProps
https://github.com/chakra-ui/chakra-ui/blob/main/packages/checkbox/src/use-checkbox.ts#L276-L303

#### getRootProps usage in Checkbox
https://github.com/chakra-ui/chakra-ui/blob/main/packages/checkbox/src/checkbox.tsx#L151

If I'm misunderstanding this, please let me know or at least point me in the right direction.

**Comment by vincentbriglia** [comment]
I'm having the same problem @digitaltoad. if you look at this discussion how to add a checkbox using react-table: https://github.com/tannerlinsley/react-table/discussions/2243 - i would love to be able to add an `onClick` prop to the checkbox component, but it doesn't seem to register an onClick when you have no label.

**Comment by ccoltos** [comment]
You can also try:

`<Box onClick={() => handleClickEvent()}>
	<Box pointerEvents={"none"}>
		<Checkbox  />
	</Box>
</Box>`

This will disable clicking on the actual Checkbox component and will handle the event by the parent.

**Comment by thefalked** [comment]
> You can also try:
> 
> ```
> <Box onClick={() => handleClickEvent()}>
> 	<Box pointerEvents={"none"}>
> 		<Checkbox  />
> 	</Box>
> </Box>
> ```
> 
> This will disable clicking on the actual Checkbox component and will handle the click event by the parent.

Thank you, my checkbox wasn't working, i added `pointerEvents="none"` on the checkbox and then on the `Box` element i use the `onClick` setting the state of the checkbox by the `isChecked` prop. In my case i also added a `stopPropagation` so the click doesn't go up.

If helps anyone, here is the commit:  https://github.com/thefalked/Drink-Count/commit/c3993bea209acd670fa733da258488951f6296f2

**Comment by segunadebayo** [comment]
Closing based on inactivity

**Comment by approached** [comment]
Thx, this works:
```js
<Checkbox pointerEvents="none"></Checkbox>
```
