### ISSUE TITLE
Unable to set default color mode

### ISSUE THREAD

**Issue by Scoder12** [chakra-ui/chakra-ui#2861]
# 🐛 Bug report

Unable to force color mode to dark using theme. 

## 💥 Steps to reproduce

1. Open [this codesandbox](https://codesandbox.io/s/chakra-ui-bug-niglu?file=/src/index.tsx)
2. See that the components are in light mode. Expected them to be in dark mode due to configuration of `ColorModeScript` and `extendTheme`

## 💻 Link to reproduction

[Codesandbox reproduction](https://codesandbox.io/s/chakra-ui-bug-niglu?file=/src/index.tsx)

## 🧐 Expected behavior

Expect components to be in dark mode

## 🧭 Possible Solution

Not sure.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.0.3       |
| Browser          |      Chrome Latest (Chromium: 87.0.4280.101)      |
| Operating System |      Linux x64      |

## 📝 Additional information

None

**Comment by Scoder12** [comment]
Can also reach me on Chakra UI discord. [Message link](https://discord.com/channels/660863154703695893/758645914868514827/790751167582961695)

**Comment by Scoder12** [comment]
Upon further inspection, I have found that `theme.config.initialColorMode` is set to `"light"`. It can be fixed by putting the two properties under `extendTheme` under the key `config`. 

So I guess now the problem is, why doesn't the old method work, why is it allowed by TS, and why is it in the examples? Or is there something I'm missing?

Thanks for your time in advance.

**Comment by TimKolberger** [comment]
Can you share a link to the incorrect example? At https://chakra-ui.com/docs/features/color-mode is a valid example listed:

```tsx
// 1. import `ChakraProvider` component and `extendTheme`
import { extendTheme, ChakraProvider } from "@chakra-ui/react"

// 2. declare your configuration, these are the defaults
const config = {
  useSystemColorMode: false,
  initialColorMode: "light",
}

// 3. extend the theme
const customTheme = extendTheme({ config })

function App() {
  return (
    // 4. pass to `ChakraProvider` as usual
    <ChakraProvider theme={customTheme}>
      <h1>Example</h1>
    </ChakraProvider>
  )
}
```

The `extendTheme` function allows adding properties to the theme. 
It **extends** the theme - so every property in the default theme should be present plus any additional values you want.

**Comment by ljosberinn** [comment]
In your sandbox youre not nesting the `config` property, but just adding `useSystemColorMode` etc to the top level, which doesn't work.

![image](https://user-images.githubusercontent.com/29307652/102895460-04eda180-4465-11eb-9280-7e3043f7a0fc.png)

Nesting it within `config` works as expected.

**Comment by wvieed** [comment]
ا

**Comment by Scoder12** [comment]
Ah thanks - it seems I misinterpreted the example. Sorry!
