### ISSUE TITLE
Tooltip bugs when used with icon

### ISSUE THREAD

**Issue by mrlmaia** [chakra-ui/chakra-ui#2869]
# 🐛 Bug report

If you use a tooltip with an icon provided by chakra-ui/icons the tooltip works well. But if you use the tooltip with an icon provided by another package, for example react-icons, the tooltip goes to the top of the page.

## 💥 Steps to reproduce

Create two tooltips. One using a icon provided by chakra and other provided by another package. 

## 💻 Link to reproduction

 View the bug [here](https://codesandbox.io/s/intelligent-chatterjee-13zt5?fontsize=14&hidenavigation=1&theme=dark)

## 🧐 Expected behavior

when you hover the second ant third icons the tooltip will open on the top left 

## 🧭 Possible Solution

I have no idea but in the discord someone said 
"comparing the react devtools, it looks like the hover effect is always active when using Icon as...
while with InfoOutlineIcon Tooltip is actually working as intended, hiding until shown"

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI    |   1.0      |
| Browser       |   Opera, Firefox and maybe the others too |
| Operating System |     Ubuntu 20.04       |

**Comment by with-heart** [comment]
The console has an error that explains what's happening here:

![image](https://user-images.githubusercontent.com/1954752/103106750-21750f80-4606-11eb-8e0e-f65aaa80f661.png)

`Tooltip` relies on passing a `ref` to its child, but `react-icons` don't use `forwardRef` so there's no way for that to happen. This is a problem on the `react-icons` end which I have an open issue for: https://github.com/react-icons/react-icons/issues/336

You can fix it in the meantime by wrapping `react-icons` with `span` elements: https://codesandbox.io/s/peaceful-sanne-9gcks?file=/src/App.tsx

**Comment by with-heart** [comment]
Will add a note in the docs for this

**Comment by imabp** [comment]
Update:
This also happens when you export a icon from Figma, and create an icon like this.

```ts
import { Icon, IconProps, useColorModeValue } from '@chakra-ui/react'
import React from 'react'

const TooltipIcon = ({
    isInverted = false,
    fill,
    ...rest
}: {
    fill?: string
    isInverted?: boolean
} & IconProps): JSX.Element => {
    const lightMode = isInverted ? 'white' : 'gray.800'
    const darkMode = isInverted ? 'gray.800' : 'white'

    const iconFill = fill || useColorModeValue(lightMode, darkMode)

    return (
        <Icon viewBox="0 0 16 16" ms={1} mr={1} {...rest}>
            <path d="M12.9744 2.2256C11.5392 0.7904 9.6304 0 7.6 0C5.5696 0 3.6616 0.7904 2.2256 2.2256C0.7896 3.6608 0 5.5696 0 7.5992C0 9.6288 0.7904 11.5376 2.2256 12.9736C3.6608 14.4096 5.5696 15.1992 7.6 15.1992C9.6304 15.1992 11.5384 14.4088 12.9744 12.9736C14.4104 11.5384 15.2 9.6296 15.2 7.5992C15.2 5.5688 14.4096 3.6608 12.9744 2.2256V2.2256ZM7.6 14.4C3.8504 14.4 0.8 11.3496 0.8 7.6C0.8 3.8504 3.8504 0.8 7.6 0.8C11.3496 0.8 14.4 3.8504 14.4 7.6C14.4 11.3496 11.3496 14.4 7.6 14.4Z"
                fill={iconFill} />
            <path d="M7.6 11.2004C7.3792 11.2004 7.2 11.0212 7.2 10.8004V9.20039C7.2 8.97959 7.3792 8.80039 7.6 8.80039C9.144 8.80039 10.4 7.54439 10.4 6.00039C10.4 4.45639 9.144 3.20039 7.6 3.20039C6.056 3.20039 4.8 4.45639 4.8 6.00039C4.8 6.22119 4.6208 6.40039 4.4 6.40039C4.1792 6.40039 4 6.22119 4 6.00039C4 4.01559 5.6152 2.40039 7.6 2.40039C9.5848 2.40039 11.2 4.01559 11.2 6.00039C11.2 7.84999 9.7976 9.37879 8 9.57799V10.8004C8 11.0212 7.8208 11.2004 7.6 11.2004V11.2004Z"
                fill={iconFill} />
            <path d="M7.60001 13.6C7.37921 13.6 7.20001 13.4208 7.20001 13.2V12.4C7.20001 12.1792 7.37921 12 7.60001 12C7.82081 12 8.00001 12.1792 8.00001 12.4V13.2C8.00001 13.4208 7.82081 13.6 7.60001 13.6Z"
                fill={iconFill} />

        </Icon>
    )
}

export default TooltipIcon
```

Also you use it here:

```ts
   
                        <Tooltip label={helper} placement='bottom'>
                            <span>  <TooltipIcon /></span>
                        </Tooltip>
```

If Icon is not wrapped in span, the same error is reproduced.

**Comment by IamSanjayGupta** [comment]
<Tooltip label="Home"  hasArrow>
      <span>
        <Icon as={TooltipIcon} />
      </span>
</Tooltip>

**Comment by IamSanjayGupta** [comment]
Wrap the icon in ```<span>``` tag it will work.

```
<Tooltip label="Home"  hasArrow>
      <span>
        <Icon as={TooltipIcon} />
      </span>
</Tooltip>

```

**Comment by kheuch2018** [comment]
> Wrap the icon in `<span>` tag it will work.
> 
> ```
> <Tooltip label="Home"  hasArrow>
>       <span>
>         <Icon as={TooltipIcon} />
>       </span>
> </Tooltip>
> ```

This worked for me with react-icons

**Comment by tbathat** [comment]
Hey guys! I discovered another way to render tooltip that is using a <Box> element around the icon.

So instead of using <span> tag you can use <Box> tag from Chrakra-UI. It works very well for the purpose and is more easy to do stylization, for example, including a gap between Tooltip popper and the icon:

```
<Tooltip label="Edit" placement="left" shouldWrapChildren={true} hasArrow>
                <Box ml="10px">
                  <EditIcon />
                </c.Box>
              </c.Tooltip>
```

Also, it is important to use the `shouldWrapChildren` prop.
