### ISSUE TITLE
How to do nested selectors?

### ISSUE THREAD

**Issue by singingwolfboy** [chakra-ui/chakra-ui#287]
## Problem
[Emotion supports nested selectors](https://emotion.sh/docs/nested), and they can sometimes be very useful. However, it does not appear that Chakra supports this feature, even though Chakra is built on Emotion.

Is it possible to use nested selectors with Chakra, as well? I don't see a way to do so in the documentation. I tried using the `css` prop to build on Emotion, but the Typescript annotations do not allow use of this prop in a Typescript project (which is what I'm using).

## Proposed Solution
Maybe the `Box` component could add a prop called `nested`, which accepts a JS object of nested selectors and styles? For example:

```jsx
<Box
  nested={{
    "a": { color: "#0000EE" },
    "a:visited": { color: "#551A8B;" },
  }}
>
  These <Link>links</Link> are <Link>colored</Link>!
</Box>
```

Note that the above example is handy for restoring [standard HTML link colors](https://stackoverflow.com/a/4774037/141395) after the `CSSReset` component removes them.

**Comment by lee-reinhardt** [comment]
> I tried using the css prop to build on Emotion, but the Typescript annotations do not allow use of this prop in a Typescript project (which is what I'm using).

You have to do a little bit of extra work to make emotion's `css` prop work in general. You need to do one of these things:
- Use emotion's `jsx` pragma in files where the `css` prop is used, see: https://emotion.sh/docs/typescript
- Use  the`@emotion/babel-preset-css-prop` Babel preset, see: https://emotion.sh/docs/@emotion/babel-preset-css-prop

TS will be fine with the `css` prop as long as you've imported _something_ from `@emotion/core` somewhere in your app.

[Here's a CodeSandbox example of the first solution.](https://codesandbox.io/s/youthful-shtern-eerw9)

**Comment by singingwolfboy** [comment]
Ah, perfect! I was able to get the `css` prop to work with the `jsx` pragma. Perhaps we should add this to the Chakra documentation, or at least link to the relevant section of the Emotion documentation?

**Comment by segunadebayo** [comment]
That's a good point @lee-reinhardt!

I was thinking you could create your own Link component based on Chakra's link and add the styles there, to keep it clean.

Here's what I mean

```jsx
import { Link as ChakraLink } from "@chakra-ui/core"

const Link = props => <ChakraLink color="#0000EE" _visited={{ color: "#551A8B" }}  {...props} />

export default Link
```

You can either use this or the `css` prop.

**Comment by DouglasGabr** [comment]
Other solution is to use emotion `styled` to use the nested selectors:

```javascript
import styled from '@emotion/styled'
import { Box } from '@chakra-ui/core'

const MyCustomBox = styled(Box)`
  a {
    color: #0000EE;
    &:visited {
      color: #551A8B;
    }
  }
`

<MyCustomBox>
  These <Link>links</Link> are <Link>colored</Link>!
</MyCustomBox>
```

If you need to target the `Link` component in the selector, I think you will need to wrap it in a styled:

```javascript
import styled from '@emotion/styled'
import { Box, Link } from '@chakra-ui/core'

const StyledLink = styled(Link)``

const MyCustomBox = styled(Box)`
  ${StyledLink} {
    color: #0000EE;
    &:visited {
      color: #551A8B;
    }
  }
`

<MyCustomBox>
  These <StyledLink>links</StyledLink> are <StyledLink>colored</StyledLink>!
</MyCustomBox>
```

This is a more advanced usage, and I think it's required to use the emotion babel plugin for it to work

**Comment by segunadebayo** [comment]
Seems we have a couple of solutions for this issue. I'll close this out for now.

If you ever run into any issues related to this, feel free to comment here and I'll re-open it.

Thanks for using Chakra UI

**Comment by kellyrmilligan** [comment]
I ended up using the `styled` method to do this as well, however I was a bit sad and it felt like an escape hatch. I really like the single part and multipart theme stuff with defineStyle functions, etc. I was hoping initially that I could do it there somehow, so I settled on a split between the theme and `styled` to do the things I could not do 😭

**Comment by Irrelon** [comment]
If you have parent ComponentA, then you want ComponentB to respond to ComponentA's hover state e.g. in pure CSS:

```html
<div class="ComponentA">
   <div class="ComponentB">Foo</div>
</div>
```

```css
.ComponentA:hover .ComponentB {
    color: #fff;
}
```

How would you achieve this based on the proposed solutons above?

**Comment by SanderVanHullebusch** [comment]
> If you have parent ComponentA, then you want ComponentB to respond to ComponentA's hover state e.g. in pure CSS:
> 
> ```
> <div class="ComponentA">
>    <div class="ComponentB">Foo</div>
> </div>
> ```
> 
> ```css
> .ComponentA:hover .ComponentB {
>     color: #fff;
> }
> ```
> 
> How would you achieve this based on the proposed solutons above?

I believe you can use the _groupHover prop: https://chakra-ui.com/docs/styled-system/style-props#pseudo
Just make sure your data attributes are correctly set OR use a className (like in the documentation example)
