### ISSUE TITLE
The colorScheme props doesn't apply to Link component

### ISSUE THREAD

**Issue by cereallarceny** [chakra-ui/chakra-ui#2870]
# 🐛 Bug report

When supplying a `colorScheme` to a `<Link>` component, as described in the documentation, the color does not seem to change. This can only be done by setting the color prop to a specific color key value.

## 💥 Steps to reproduce

1. Go to your documentation: https://chakra-ui.com/docs/components/link
2. Try to change the color scheme of the first example, like such: `<Link colorScheme="red">Hello world</Link>`
3. Nothing happens

## 💻 Link to reproduction

See previous

## 🧐 Expected behavior

I'd expect the color to change, as well as have a hover color set that's different from the main color

## 🧭 Possible Solution

I'm not quite sure where this should be added - I'm guessing the layout package?

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.0.3           |
| Browser          | Brave 1.18.75           |
| Operating System | MacOS 11.0.1           |

## 📝 Additional information

- None

**Comment by dodas** [comment]
Hey  @cereallarceny.

This probably won't be implemented in Chakra's default theme.
We can improve the docs to clarify that - either some note, or completely omit those props from Link's prop table.

If you want to simply change the color, use the `color` prop.

However, if you want to implement `colorScheme` support, with `_hover` styles, you can extend the theme like this:
```ts
export const theme = extendTheme({
  components: {
    Link: {
      variants: {
        // you can name it whatever you want
        primary: ({ colorScheme = "blue" }) => ({
          color: `${colorScheme}.500`,
          _hover: {
            color: `${colorScheme}.400`,
          },
        }),
      },
      defaultProps: {
        // you can name it whatever you want
        variant: "primary",
      },
    },
  },
})
``` 

and use it like this:
```ts
<Link colorScheme="purple" href="https://google.com">
  This is a purple link
</Link>
```

**Comment by cereallarceny** [comment]
Why? Tons of other components have full support for `colorScheme`, and you have documentation for it's support on the `<Link>` component - why wouldn't it be something defaultly supported by Chakra's theme? Seems strange that this is already done for a variety of components, including `<Button>`, but not for `<Link>`...

CC: @with-heart

**Comment by dodas** [comment]
Because Chakra's Link's default styling does not change color on hover/active states like `Button` does. That's a deliberate choice. That means you can just use `color` prop to change link's color. If you want to have hover styles, I told you how that can be done.

The fact that `colorVariant` is mentioned in `Link`'s prop table is a "bug" - you can see that all chakra's components list `colorScheme` as well as `size` and `variant`, although it doesn't do anything in many of them. The docs will be improved soon.

**Comment by cereallarceny** [comment]
THAT makes more sense. I expected that prop to exist due to incorrect docs. I'll close this issue now.

**Comment by with-heart** [comment]
Yeah after looking at the source, I think there only around 10 components that ACTUALLY utilize `colorScheme`. Need to take a look at the types there to limit that.

**Comment by robobeau** [comment]
It is the year 2023, and the docs still show that Link supports the `colorScheme` property.

![image](https://user-images.githubusercontent.com/1454939/217534067-dc36967d-35dd-48b8-acfa-c51b3602b3da.png)

**Comment by sanjaydefidev** [comment]
I have same issue with `Drawer` component. `colorScheme` doesn't work
