### ISSUE TITLE
[Modal] Vertically centered modal cutoff on mobile

### ISSUE THREAD

**Issue by nejcm** [chakra-ui/chakra-ui#2871]
# 🐛 Bug report

On mobile devices vertically centered modals get cutoff at the top. This happens for modals that are bigger than the screen.

## 💥 Steps to reproduce

Open a modal on mobile that is vertically centered and higher than the screen.

## 💻 Link to reproduction

https://chakra-ui.com/docs/overlay/modal

## 🧭 Possible Solution

I believe this is not solvable with the current structure. I could fix it with making the modal container `display: block;` and adding one div element between the container and the modal content with `min-height: 100%; display: flex; align-items: center; justify-content: center;`.
This needs to be tested for other modal types.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |    v1.0.3        |

**Comment by nejcm** [comment]
Let me know if more info is needed or if I can help somehow. I would make a PR myself but am currently a bit short on time.

**Comment by nejcm** [comment]
The issue is still present.

**Comment by segunadebayo** [comment]
Following my explanation in the PR.

**Comment by krishnaacc123** [comment]
I think this issue still exist. I'm currently using margin="auto" on modal content block as a fix. @segunadebayo
