### ISSUE TITLE
Using responsive size values on Drawer is not working

### ISSUE THREAD

**Issue by pfortes** [chakra-ui/chakra-ui#2877]
# 🐛 Bug report

> Drawer component size is not reacting to responsive styles 

## 💥 Steps to reproduce

1. Go to the[ live Drawer component example](https://chakra-ui.com/docs/overlay/drawer) 
2. Add the prop:
`  size={["xs", "sm", "sm", "sm"]}       `

3. Open the drawer and see that its width its full size and should be "xs" or "sm"

## 💻 Link to reproduction

https://codesandbox.io/s/github/chakra-ui/codesandbox-react-js-template/tree/master with size={["xs", "sm", "sm", "sm"]}

## 🧐 Expected behavior

Get xs size in phones and sm in bigger screens

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.0      |

**Comment by with-heart** [comment]
Hi @pfortes, Chakra doesn't currently support responsive `size` values. See #1028 for more information and a workaround.

**Comment by pfortes** [comment]
> Hi @pfortes, Chakra doesn't currently support responsive `size` values. See #1028 for more information and a workaround.

Thank you for clarifying that, maybe i missed it in the "update to 1.0" docs

i think it would be usefull to have something along the lines of what you wrote... "The new modifier versions of the variant and size props don't accept responsive values"  in the update docs.

tnx
