### ISSUE TITLE
autoComplete prop on PinInputField is not working

### ISSUE THREAD

**Issue by oahmaro** [chakra-ui/chakra-ui#2879]
# 🐛 Bug report
Using autoComplete prop on PinInputField will always result in not-allowed value.

<img width="268" alt="Screen Shot 2020-12-24 at 19 27 02" src="https://user-images.githubusercontent.com/15835932/103104938-2bf9ce00-4633-11eb-8ecb-f2fe5a3c1ab6.png">
<img width="841" alt="Screen Shot 2020-12-24 at 22 00 49" src="https://user-images.githubusercontent.com/15835932/103105003-82670c80-4633-11eb-878d-8b9a99a7acb8.png">

<img width="214" alt="Screen Shot 2020-12-24 at 19 25 56" src="https://user-images.githubusercontent.com/15835932/103104935-200e0c00-4633-11eb-8442-fbdc353d8a1c.png">

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.0.4       |
| Browser          |      chrome      |
| Operating System |     mac       |

**Comment by with-heart** [comment]
Thanks for reporting @oahmaro!

@allcontributors please add @oahmaro for bug
