### ISSUE TITLE
Checkbox inside CheckboxGroup does not accept initial value

### ISSUE THREAD

**Issue by samuelmburu** [chakra-ui/chakra-ui#2885]
# 🐛 Bug report
Checkboxes inside of CheckboxGroups do not "take" the initial `isChecked` value.

## 💥 Steps to reproduce

1. Create 2 checkboxes with the `isChecked` set to true
2. See that they render as they should in browser
3. Wrap one checkbox with a `CheckboxGroup`
4. See that the newly wrapped Checkbox is now unchecked

## 💻 Link to reproduction
https://codesandbox.io/s/goofy-bash-iusc4?file=/src/App.js

## 🧐 Expected behavior
The Checkboxes should work the same way whether inside a CheckboxGroup or not

## 🧭 Possible Solution
I wonder if the `isChecked` is somehow getting overridden via a very greedy spread operation.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     "@chakra-ui/react": "^1.0.4"        |
| Browser          |    Chrome        |
| Operating System |     OSX 11.1       |

## 📝 Additional information

<img width="750" alt="Screen Shot 2020-12-25 at 6 12 39 PM" src="https://user-images.githubusercontent.com/588790/103144391-80598800-46dd-11eb-9716-95e9f35ab42e.png">

- Notes or link to ideas

-- Just started using Chakra today and am enjoying it thus far

**Comment by Zaynex** [comment]
If using CheckboxGroups wrap checkbox,  checkboxs status should be controlled by Checkboxgroups.

**Comment by with-heart** [comment]
@Zaynex is correct. From https://chakra-ui.com/docs/form/checkbox#checkboxgroup: 

> Chakra exports a `CheckboxGroup` component to help manage the checked state of its children `Checkbox` components and conveniently pass a few shared style props to each.

If you only want the styling and not state management, `CheckboxGroup` is not the right component to use. `VStack` would work better for stacking and spacing the checkboxes, and you'd need to set `colorScheme` on each individual `Checkbox`.

**Comment by samuelmburu** [comment]
Oh geez, I didn't read the manual well enough.  I'll be reading the docs more closely.

Thanks, @Zaynex, and @with-heart for explaining.
