### ISSUE TITLE
Feature Request: Fixed Nav Bar Position When Navigation Docs

### ISSUE THREAD

**Issue by sampoder** [chakra-ui/chakra-ui#2886]
# 🚀 Feature request

When I navigate the docs, I think it'd be helpful to have the nav bar not jump to the top when I open a new page.

## 🧱 Problem Statement / Justification

1. It makes it quicker to navigate the docs.
2. It makes feels more smooth, not jumping around.

## ✅ Proposed solution or API

I'm not exactly sure how you could do this. But maybe when you changes pages send a URL param to keep it in the same position if that makes sense.

Thanks and happy holidays

\- Sam!

**Comment by brahim-kellou** [comment]
I think this issue is fixed now if I understood you correctly.
I tried to open a new page when navigating the docs, and it's not jumping to the top

**Comment by sampoder** [comment]
Seems like you're correct! Thank you to the person who fixed that!
