### ISSUE TITLE
BUILD FAILING CAUSE CODE FROM CHAKRA LIBRARY CAN'T BE MINIFIED

### ISSUE THREAD

**Issue by ajibadedapo** [chakra-ui/chakra-ui#2890]
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/@chakra-ui/styled-system/dist/esm/utils/index.js:6 

Read more here: http://bit.ly/2tRViJ9

**Comment by with-heart** [comment]
Hi @ajibadedapo! It's hard to know exactly what the issue is without more information, but it appears that you might be on a very old version of `react-scripts`. See https://create-react-app.dev/docs/troubleshooting/#npm-run-build-fails-to-minify

**Comment by ajibadedapo** [comment]
Thank you @with-heart, upgrading the react-script version solved the issue.
