### ISSUE TITLE
@emotion/react

### ISSUE THREAD

**Issue by manziEric** [chakra-ui/chakra-ui#2892]
after installing the package i get that @emotion/core is been updated to @emotion/react so i have to manually update the package maybe this can be updated so that in the future developers don't have to do this

Cheers,
One Love

**Comment by with-heart** [comment]
It already has been on Chakra 1.0.0+ 😄 `@emotion/core` is no longer a dependency. See https://chakra-ui.com/docs/getting-started#installation
