### ISSUE TITLE
Non modal drawer

### ISSUE THREAD

**Issue by ramiel** [chakra-ui/chakra-ui#2893]
# 🚀 Feature request

Would it possible to have the drawer not taking the entire screen? At the moment even if I disable trap focus and the overlay, the focus is trapped because the drawer has an invisible element taking all the screen width

## 🧱 Problem Statement / Justification

The idea is to still be able to interact with the page content while having the drawer opened

## ✅ Proposed solution or API

No new API to add, the focusTrap={false} should work

**Comment by ramiel** [comment]
Also, "useInert" is not working

**Comment by jmiazga** [comment]
I was chatting with @with-heart about this recently, and I think he had some ideas around it.

**Comment by segunadebayo** [comment]
This was added a few releases ago. You can now add `trapFocus={false}`

**Comment by ramiel** [comment]
trapFocus is not working, this is what this issue is about. You can check by modifying any of your existing demo in the docs. If I remove the overlay, remove the close on click outside and remove trapFocus, I'm expecting to be able to interact with external elements but this is actually not possible. In the initial but report it's explained why

**Comment by with-heart** [comment]
This issue is a little deceptive because this is a bug report, not a feature request 🙃 

The original report is correct. I'm able to get very close to the intended behavior by rendering `<Drawer isOpen trapFocus={false} closeOnOverlayClick={false} blockScrollOnMount={false} />`, but the fullscreen `.chakra-modal__content-container` element is blocking interaction with any visible elements on the page that aren't inside the `Drawer`. If I add `pointer-events: none` to that container, I'm able to interact fully with the page with the drawer remaining open.

I'm wondering if we can safely add that style to the container without it affecting anything else. https://github.com/chakra-ui/chakra-ui/blob/f41a231aa7241419aa8bb4a31cca508e19a3a464/packages/modal/src/drawer.tsx#L94-L102

If users want to block interactivity, they would have rendered `DrawerOverlay` which already detects clicks outside the drawer, so I _think_ this should be fine to change, but I'd love to get some reassurance around that.

cc: @chakra-ui/react-team

**Comment by with-heart** [comment]
I'm also wondering if there's an easier way to allow this functionality than requiring that users pass 3 separate `false` props and don't render `DrawerOverlay`.

**Comment by ramiel** [comment]
> This issue is a little deceptive because this is a bug report, not a feature request

Indeed :man_facepalming:

**Comment by jasonwarta** [comment]
My solution to this issue was to copy the necessary contents of drawer.tsx, and add pointerEvent fields to the props... `pointerEvents: 'auto'` on `dialogStyles` and `pointerEvents: 'none'` on `dialogContainerStyles`. I use this customized drawer rather than the one that comes with chakra-ui at the breakpoints where I want the drawer always open.

I feel like there should be a way to pass down the customization via a drawer variant in the theme, but I couldn't figure it out.

**Comment by jasonwarta** [comment]
The "correct" way to deal with this in the current version of chakra-ui is with a variant.

Extend the theme with this variant:
```
const components = {
	Drawer: {
		variants: {
			alwaysOpen: {
				parts: ['dialog, dialogContainer'],
				dialog: {
					pointerEvents: 'auto',
				},
				dialogContainer: {
					pointerEvents: 'none',
				},
			},
		},
	},
};
```

Consume it like this:
```
const OpenDrawer = ({ children, ...rest }) => {
	return (
		<Drawer variant='alwaysOpen' {...rest}>
			<DrawerContent>
				<DrawerHeader borderBottomWidth='1px'>Basic Drawer</DrawerHeader>
				<DrawerBody>{children}</DrawerBody>
			</DrawerContent>
		</Drawer>
	);
};
```

**Comment by ramiel** [comment]
It's working perfectly. Thank you, also for let me understand better how chakra works. It's not the easiest approach probably, but it gets the job done!

**Comment by dodas** [comment]
Just a heads up. When extending the theme, you don't have to pass the `parts` array.
Parts are defined in the base theme and you have no way/need to override them.

**Comment by mazury** [comment]
The same thing happens in Modal component. `trapFocus` is still not working.

**Comment by samantha-wong** [comment]
@jasonwarta this solution is working great except I can't open any modals or type anything in an input while it's open. Any ideas on how we can extend this? Thanks for your help

**Comment by elibosley** [comment]
@mazury I just ran into this same thing. You can use the same solution as above with the modal:

`variants: {
 clickThrough: {
      dialogContainer: {
        pointerEvents: 'none',
      },
      dialog: {
        pointerEvents: 'auto',
      },
    },
}`

**Comment by jvnlwn** [comment]
Based on the discussion, this is what I'm trying, which seems to support all interactions with the overlaid content (clicking, focusing, typing, scrolling, .etc.). Though, I am on an older version (1.8.8) of Chakra, in case that matters.

```javascript
theme.components = {
  Drawer: {
    variants: {
      aside: {
        dialog: {
          pointerEvents: "auto"
        },
        dialogContainer: {
          pointerEvents: "none"
        }
      }
    }
  }
}
```

```jsx
<Drawer
  variant="aside"
  trapFocus={false}
  blockScrollOnMount={false}
>
  {/* ... */}
</Drawer>
```

**Comment by Gwened** [comment]
> ```js
> trapFocus={false}
>   blockScrollOnMount={false}
> ```

Thanks to those, it works brillantly, thanks!

**Comment by rctheriot** [comment]
This ended up working for me in `@chakra-ui/react": "^2.5.5"`
 

```typescript
// Custom component variants
const components = {
  // Drawer variant to allow pointer events to the underlying content
  Drawer: {
    variants: {
      clickThrough: {
        overlay: {
          pointerEvents: 'none',
          background: 'transparent',
        },
        dialogContainer: {
          pointerEvents: 'none',
          background: 'transparent',
        },
        dialog: {
          pointerEvents: 'auto',
        },
      },
    },
  },
};

// Extend the theme
export const theme = extendTheme({ config, components, colors, styles });

// Within your component just use variant={"clickThrough"}
<Drawer isOpen={isOpen}  onClose={onClose} closeOnOverlayClick={false}  variant="clickThrough">
...
</Drawer>

```

**Comment by bruno-henr** [comment]
> A maneira "correta" de lidar com isso na versão atual do chakra-ui é com uma variante.
> 
> Estenda o tema com esta variante:
> 
> ```
> const components = {
> 	Drawer: {
> 		variants: {
> 			alwaysOpen: {
> 				parts: ['dialog, dialogContainer'],
> 				dialog: {
> 					pointerEvents: 'auto',
> 				},
> 				dialogContainer: {
> 					pointerEvents: 'none',
> 				},
> 			},
> 		},
> 	},
> };
> ```
> 
> Consuma assim:
> 
> ```
> const OpenDrawer = ({ children, ...rest }) => {
> 	return (
> 		<Drawer variant='alwaysOpen' {...rest}>
> 			<DrawerContent>
> 				<DrawerHeader borderBottomWidth='1px'>Basic Drawer</DrawerHeader>
> 				<DrawerBody>{children}</DrawerBody>
> 			</DrawerContent>
> 		</Drawer>
> 	);
> };
> ```

In case someone doesn't understand where to configure this:
just create a theme.ts file:
```
import { extendTheme } from "@chakra-ui/react";

export const theme = extendTheme({
  colors: {
    gray: {
      "900": "#181B23",
      "800": "#1F2029",
      "700": "#353646",
      "600": "#4B4D63",
      "500": "#616480",
      "400": "#797D9A",
      "300": "#9699B0",
      "200": "#B3B5C6",
      "100": "#D1D2DC",
      "50": "#EEEEF2",
    },
  },
  
  styles: { ... },

// Here you must add the friend code
  components: {
    Drawer: {
      variants: {
        alwaysOpen: {
          parts: ['dialog, dialogContainer'],
          dialog: {
            pointerEvents: 'auto',
          },
          dialogContainer: {
            pointerEvents: 'none',
          },
        },
      },
    },
  }
});
```
