### ISSUE TITLE
The number input displays the built-in stepper in Firefox

### ISSUE THREAD

**Issue by Wolfr** [chakra-ui/chakra-ui#29]
The number input displays the built-in stepper in Firefox.

<img width="945" alt="Screenshot 2019-09-06 at 22 33 29" src="https://user-images.githubusercontent.com/12690/64458731-6665f180-d0f6-11e9-950f-bec85dd8ac97.png">

Can be fixed with `-moz-appearance: textfield;`.

**Comment by segunadebayo** [comment]
Hi @Wolfr , 

This has been resolved. I'll release a patch shortly
