### ISSUE TITLE
CircularProgress linter error

### ISSUE THREAD

**Issue by diceroll123** [chakra-ui/chakra-ui#2907]
# 🐛 Bug report

WebStorm/IntelliJ seems to have a conniption when using CircularProgress, suggesting that every possible underscore-prefixed attribute is required.

![unknown (1)](https://user-images.githubusercontent.com/1243957/103249216-074b7200-4923-11eb-95a9-09febe322926.png)

## 💥 Steps to reproduce

1. Open a project with Chakra installed and imported using WebStorm
2. Try using a CircularProgress element

## 🧐 Expected behavior

The yellow squiggle under each CircularProgress element shouldn't be there. This isn't a large problem, though.

**Comment by TimKolberger** [comment]
Leaving this here for reference: https://github.com/chakra-ui/chakra-ui/pull/2753#issuecomment-752004528

**Comment by TimKolberger** [comment]
This is a bug of the Jetbrains IDEs. Please see the ticket in YouTrack https://youtrack.jetbrains.com/issue/WEB-48161.
I am closing this, because it is not an issue of chakra UI.
