### ISSUE TITLE
Allow setting the skeleton width and height only while it is being loaded

### ISSUE THREAD

**Issue by delucca** [chakra-ui/chakra-ui#2916]
# 🚀 Feature request

Since Chakra provides an incredible Skeleton wrapper that works as a Box, it is common to face scenarios where your Skeleton is wrapping an empty content until you fetch the remote data. For those cases, it would be great to have a way to customize the Skeleton width/height while is being loaded without affecting the content box afterwards.

## 🧱 Problem Statement / Justification

Here is a sample snippet:
```tsx
      <Skeleton isLoaded={!isLoading}>
        <Heading as="h3" fontSize="18px">
          {company?.name}
        </Heading>
      </Skeleton>
```

In that snippet (which is pretty common in my project) before fetching `company` data, the `Skeleton` component is empty, since it is rendering an `undefined` child. When it renders in my DOM I simply cannot see the `Skeleton` at all.

To fix that, I have two options, I can either:

**Use a static text fallback (bad):**
```tsx
      <Skeleton isLoaded={!isLoading}>
        <Heading as="h3" fontSize="18px">
          {company?.name ?? 'Sample text'}
        </Heading>
      </Skeleton>
```
This works, but it is hacky and suboptimal (I can have some issues like running into an error in my request, and them rendering the `Sample text` instead.

**Set the minimum width and height:**
```tsx
      <Skeleton isLoaded={!isLoading} minW="150px" minH="21px">
        <Heading as="h3" fontSize="18px">
          {company?.name}
        </Heading>
      </Skeleton>
```
This works, but after rending the final component the `minW` and `minH` props are passed to the Skeleton box, affecting the behavior of the final rendered component (which is bad). To fix that, I ended up with something like this:
```tsx
      <Skeleton isLoaded={!isLoading} minW={ isLoading ? '150px' : 'auto' } minH={ isLoading ? '21px' : 'auto' }>
        <Heading as="h3" fontSize="18px">
          {company?.name}
        </Heading>
      </Skeleton>
```
Which, in my opinion, is hacky.

We should have a prop to set the width and height of the Skeleton only when it is being loaded.

## ✅ Proposed solution or API

I suggest the following API:

```tsx
      <Skeleton isLoaded={!isLoading} skeletonW="150px" skeletonH="21px">
        <Heading as="h3" fontSize="18px">
          {company?.name}
        </Heading>
      </Skeleton>
```

## ↩️ Alternatives

I've already describe some alternatives, but for now that is the best one (IMHO):
```tsx
      <Skeleton isLoaded={!isLoading} minW={ isLoading ? '150px' : 'auto' } minH={ isLoading ? '21px' : 'auto' }>
        <Heading as="h3" fontSize="18px">
          {company?.name}
        </Heading>
      </Skeleton>
```

**Comment by delucca** [comment]
I would like this feature :)

**Comment by ptrhck** [comment]
I was facing this issue as well and would love to see this feature! :)

**Comment by nenadfilipovic** [comment]
Same

**Comment by scottrblock** [comment]
I would also love to see this!

**Comment by sxppro** [comment]
I would also like to see this, had some layout issues when wrapping text in Skeletons as well 😄

**Comment by omattman** [comment]
+1 would want this

**Comment by derherbst** [comment]
+1 August 2023 and still would be great to have.

I'm loading users email but if there is no data after loading then there is empty space...

**Comment by derherbst** [comment]
<SkeletonText skeletonHeight={value} /> makes things easier!

**Comment by pedram6195** [comment]
I would also love to see this!
