### ISSUE TITLE
Variant to Select and Checkbox doesn't work

### ISSUE THREAD

**Issue by beavanzi** [chakra-ui/chakra-ui#2917]
# 🐛 Bug report

I just can't use custom variants to Select and Checkbox because the styles I set up don't be apply.

## 💥 Steps to reproduce

1. Use Select
2. Create an styled sheet with variants style config
3. Export this style sheet in 'components' through extendTheme() object
4. Try to use your custom variant into Select

##  📝 Additional information

style/theme/components/Select.ts

> `const Select = {
>   sizes: {
>     sm: {
>       w: '10px',
>     },
>   },
>   variants: {
>     primary: {
>       bg: '#010101',
>       borderColor: 'inherit',
>       borderWidth: '1px',
>       iconColor: '#110000',
>     },
>     'primary-form': {
>       color: 'gray.400',
>       borderColor: '#110000',
>       border: '1px solid',
>       iconColor: '#001100',
>     },
>   },
> }
> 
> export default Select`

style/theme/index

> `import { extendTheme } from '@chakra-ui/react'
> import { breakpoints, colors, sizes, fonts, textStyles } from './custom'
> 
> import Button from './components/Button'
> import Checkbox from './components/Checkbox'
> import Select from './components/Select'
> 
> const globalStyles = {}
> 
> export const theme = extendTheme({
>   colors: colors as any,
>   breakpoints,
>   fonts,
>   sizes,
>   textStyles,
>   components: {
>     Button,
>     Select,
>     Checkbox,
>   },
>   styles: { global: globalStyles },
> })
> `

The same occurs when I try to use custom variants to Checkbox.

**Comment by TimKolberger** [comment]
The Select component has a MultipartStyle theme configuration. Please [see the docs](https://chakra-ui.com/docs/theming/advanced#multipart-or-composite-component) for more context.

https://github.com/chakra-ui/chakra-ui/blob/c773820ed23e0e114ca160d8bf6eeb3684f2ea23/packages/theme/src/components/select.ts#L26-L29

In your case it could look like this:

```ts
const Select = {
  variants: {
    primary: {
      field: {
        bg: '#010101',
        borderColor: 'inherit',
        borderWidth: '1px',
      },
      icon: {
        color: '#110000',
      }
    }
  }
}
```
