### ISSUE TITLE
Chakra Toast breaks when using why-did-you-render

### ISSUE THREAD

**Issue by mikecx** [chakra-ui/chakra-ui#2924]
# 🐛 Bug report

When using `@welldone-software/why-did-you-render` and the Chakra Toast the hooks get run out of order, the Toast does not display, and the console shows the hook error.

## 💥 Steps to reproduce

1. Install [@welldone-software/why-did-you-render](https://github.com/welldone-software/why-did-you-render)
2. Add a Standalone Toast anywhere in your code.
3. Run the code and watch the error log, the Toast should not display and the errors should show up.

## 💻 Link to reproduction

https://codesandbox.io/s/nice-kirch-n6r6c

## 🧐 Expected behavior

The Toast should display and no error should be thrown.

## 🧭 Possible Solution

Currently, if you configure why-did-you-render to not track hooks, the error does not happen.

```
  whyDidYouRender(React, {
    trackAllPureComponents: true,
    trackHooks: false
  })
```

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.0           |
| Browser          |  Chrome          |
| Operating System | OSX           |

## 📝 Additional information

Going to cross post this to why-did-you-render as well. This is the first issue i've seen with the library when it comes to hooks so it's unclear if this is an error in how Toast is written or in why-did-you-render.

**Comment by ljosberinn** [comment]
Seems to be fixed upstream by importing why-did-you-render-first.
