### ISSUE TITLE
Menu component not accepting zIndex property

### ISSUE THREAD

**Issue by diceroll123** [chakra-ui/chakra-ui#2928]
# 🐛 Bug report

Giving a Menu a `zIndex` does nothing. I don't know if it ignores other Chakra CSS props, haven't tried.

## 💻 Link to reproduction

https://codesandbox.io/s/elastic-jones-monv9

(Click the `Show` button to demonstrate)

*Note that I gave the Logo a zIndex of 2, and the Menu (and MenuList) a zIndex of 3*

## 🧐 Expected behavior

I expected `zIndex` to be added to the Menu components.

**Comment by diceroll123** [comment]
Ah, right. Portals exist.

**Comment by martinpengellyphillips** [comment]
I'm hitting this as an issue now and Portals don't solve it for me currently due to #3201.

Could we get support added for setting zIndex on the menulist explicitly?
