### ISSUE TITLE
getRadioProps can't handle number as value

### ISSUE THREAD

**Issue by abagshaw** [chakra-ui/chakra-ui#2931]
# 🐛 Bug report

When creating a [custom radio button](https://chakra-ui.com/docs/form/radio#custom-radio-buttons) I wanted to use integers as values instead of strings (and have the onChange callback take in an integer too).

## 💥 Steps to reproduce

When I set the value to an integer in `getRadioProps({value: 1})` the button never registers as being clicked. I have to do `getRadioProps({value: "1"})` as it seems it can only handle strings. Also TypeScript didn't catch this for some reason.

**Comment by cschroeter** [comment]
I'm not sure how to deal with that. For example when using an `<input type="number" value="42 />` the value is always a string [StackOverflow](https://stackoverflow.com/questions/35791767/html-input-type-number-still-returning-a-string-when-accessed-from-javascript) 

My suggestion would be to adjust the typings in ChakraUI.  
You can then cast the onChange from string to number.

**Comment by segunadebayo** [comment]
I agree with @cschroeter because we use the native `input` element under the hood, all values are cast to a DOM String (aka string).

I'd recommend casting to number on your end at `onChange`.

Thanks
