### ISSUE TITLE
Hover For Menu

### ISSUE THREAD

**Issue by Lumbarque-Oficial** [chakra-ui/chakra-ui#2945]
# 🚀 Feature request

> Add event property onHover for MenuButton 

## 🧱 Problem Statement / Justification

> Feature do not exists 

## ✅ Proposed solution or API

> <MenuButton onHover={}>

## ↩️ Alternatives

> Create a react component by myself for that

**Comment by dodas** [comment]
Closing as duplicate of #1380.
Please feel free to continue discussion there.
