### ISSUE TITLE
[Breadcrumb] Can't use theme to style items and nav elements

### ISSUE THREAD

**Issue by kfalkiewicz** [chakra-ui/chakra-ui#2953]
# 🐛 Bug report

> I want to have all of my component styling inside theme. I can use parts to style link and separator components, but can't use it to style `Nav` element and `Item` itself (needed for custom styles of the `isActivePage` item).

## 🧐 Expected behavior

> All visible elements of the `Breadcrumb` component should be accessible from theme.

## 🧭 Possible Solution

> Add additional theme parts for nav and item elements.

## 📝 Additional information
- Just check [here](https://github.com/chakra-ui/chakra-ui/blob/9035bc182136a2ffca3e6e5fb73bffcd537fd378/packages/breadcrumb/src/breadcrumb.tsx) to see that styles from theme are only passed to `link` (anchor) and to `separator`. Of course you can style it by passing custom props, but this collide with an idea of theme where you store your base component styles.

**Comment by la55u** [comment]
I agree it's a bit annoying that you can't style the current page from theme.
