### ISSUE TITLE
Allow to merge pseudo props

### ISSUE THREAD

**Issue by egoist** [chakra-ui/chakra-ui#296]
**Is your feature request related to a problem? Please describe.**

```jsx
<Button _hover={{ fontWeight: 'bold' }}>Button</Button>
```

Something like this will disable the default `hover` styles.

**Describe the solution you'd like**

Maybe we should merge custom pseudo props with the default one?

**Describe alternatives you've considered**

No.

**Additional context**

**Comment by mpash** [comment]
Perhaps making this either an object or a function will enable us to consume the base props and spread them into the consuming object.

**Comment by segunadebayo** [comment]
I agree. We're currently looking into this for the next release. Thanks for pointing this out.

**Comment by jvgreenaway** [comment]
I like this idea. Any news on this? 

I anticipated that the `_hover` prop would be merged with the default styles by default.
