### ISSUE TITLE
Collapse animation hides overflow

### ISSUE THREAD

**Issue by frysztak** [chakra-ui/chakra-ui#2966]
# 🐛 Bug report

Elements wrapped in `Collapse` animation can't overflow it. It causes problems for dropdowns.

## 💥 Steps to reproduce

1. Go to https://codesandbox.io/s/eager-tereshkova-fr0mr
2. Click on 'Click Me'
3. Open Dropdown
4. Options should be clipped
5. Click on 'Toggle Theme'
6. Options should not be clipped

## 💻 Link to reproduction

https://codesandbox.io/s/eager-tereshkova-fr0mr

## 🧐 Expected behavior

`Collapse` should allow overflow.

## 🧭 Possible Solution

Workaround is provided in Codesandbox. For a actual solution, I think that removing `overflow: hidden` from [here](https://github.com/chakra-ui/chakra-ui/blob/f41a231aa7241419aa8bb4a31cca508e19a3a464/packages/transition/src/collapse.tsx#L138) would do. I can provide PR if that's okay.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.0.0          |
| Browser          |    Chrome 87        |
| Operating System |   Win 10  |

**Comment by TheAsda** [comment]
I got the same issue. Looks like `overflow: hidden` was added to prevent animation artifacts on collapse.

**Comment by frysztak** [comment]
Upon further testing I encountered issues with `startingHeight` after removing `overflow: hidden`. Some other solution is needed, but I haven't had the time to experiment.

**Comment by simontaisne** [comment]
You can't really use `Input` either with the `Collapse` component due to the `overflow: hidden` property. Once selected you can notice the cut borders.

<img src="https://user-images.githubusercontent.com/233639/110159598-ed159080-7db8-11eb-82ae-b9fb119a661b.png">

**Comment by dusty** [comment]
Did you ever find a workaround on this, aside from just not using collapse?

**Comment by frysztak** [comment]
@dusty best I came up with is this hack:

```ts
// theme.ts
const styles = {
  global: {
    ':not(.chakra-dont-set-collapse) > .chakra-collapse': {
      overflow: 'initial !important',
    },
  },
};

export const theme = extendTheme({
  styles,
  ...
});
```

by default, it sets `overflow: initial !important` so that overflow is visible. sometimes that's not what you want. you can then set `className="chakra-dont-set-collapse"`

**Comment by Inviz** [comment]
```
.chakra-collapse[style*="height: auto"] { overflow: initial !important }
```

**Comment by lucasruy** [comment]
I had problems with collapsing using a `Select` component and found a workaround using `@emotion/styled` creating a Wrapper component like this below, I reusing the Collapse `in` prop to disable `overflow: hidden`::
```js
export const CollapseTransition = styled(Collapse)`
  overflow: ${({ in: isEnabled }) => (isEnabled ? 'initial !important' : 'hidden')};
`
```

I hope this helps anyone with the same problem.

**Comment by lucasruy** [comment]
I had problems with collapsing using a Select component and found a workaround using @emotion/styled creating a Wrapper component like this below, I reusing the Collapse in prop to disable overflow: hidden::

export const CollapseTransition = styled(Collapse)`
  overflow: ${({ in: isEnabled }) => (isEnabled ? 'initial !important' : 'hidden')};
`
This way the overflow is disabled only when the Collapse has the prop in with value true. So when the value is false the animation is preserved without problems.

I hope this helps anyone with the same problem.

**Comment by KROT47** [comment]
I came up with this hack:

```ts
import { Accordion as AccordionBase, ExpandedIndex } from '@chakra-ui/react';
import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useRef,
} from 'react';

type AccordionProps = Parameters<typeof AccordionBase>[0];

const chakraCollapseSelector = '.chakra-collapse';

export default forwardRef(function Accordion(
  { onChange, ...restProps }: AccordionProps,
  ref
) {
  const accordionRef = useRef<HTMLDivElement>(null);

  useImperativeHandle(ref, function () {
    return accordionRef.current;
  });

  const handleAccordionItemToggle = useCallback(
    (expandedIndex: ExpandedIndex): void => {
      if (accordionRef.current === null) return;

      const indexArr = Array.isArray(expandedIndex)
        ? expandedIndex
        : [expandedIndex];
      const collapseItems = accordionRef.current.querySelectorAll(
        chakraCollapseSelector
      );

      collapseItems.forEach((el, i) => {
        if (!(el instanceof HTMLElement)) return;

        if (indexArr.includes(i)) {
          setTimeout(() => {
            el.style.overflow = 'visible';
          }, 100);
        } else {
          el.style.overflow = 'hidden';
        }
      });
    },
    []
  );

  const handleOnchange = useCallback(
    (expandedIndex: ExpandedIndex): void => {
      handleAccordionItemToggle(expandedIndex);
      onChange?.(expandedIndex);
    },
    [handleAccordionItemToggle, onChange]
  );

  useEffect(() => {
    if (restProps.defaultIndex === undefined) return;
    // make all opened by default accordion panels
    // to be `visibility: visible` from the beginning
    handleAccordionItemToggle(restProps.defaultIndex);
  }, [restProps.defaultIndex, handleAccordionItemToggle]);

  return (
    <AccordionBase
      ref={accordionRef}
      onChange={handleOnchange}
      {...restProps}
    />
  );
});
```

Hope somebody will make nice PR for that...

**Comment by kicks321** [comment]
@segunadebayo, is there a particular reason why Chakra-ui enforces this styling by default on that "chakra-collpase" div component?
