### ISSUE TITLE
Toasts trolling me in tests

### ISSUE THREAD

**Issue by timkindberg** [chakra-ui/chakra-ui#2969]
# 🐛 Bug report

Toasts cause headaches during testing.

1. There is no easy way to clear all toasts without any exit animation. They always linger around, messing with dom element selection. You have to wait 401ms for all toasts to be gone. Is there a way to disable the animation in tests?

2. Toast renders two alerts, one visible one in the toast manager, another hidden one meant for accessibility rendered into a `role=status` element. This makes selection difficult because it's hard to select by role of 'alert', or by the text contents, because there is always two elements found.

3. Toast Manager renders persistent dom elements into every test and adds to cognitive overload while reviewing snapshots or screen.debug output. 

```
<div id="chakra-toast-portal"><ul id="chakra-toast-manager-top" style="position: fixed; z-index: 5500; pointer-events: none; display: flex; flex-direction: column; margin: 0px auto; top: 0px; right: 0px; left: 0px;"></ul><ul id="chakra-toast-manager-top-left" style="position: fixed; z-index: 5500; pointer-events: none; display: flex; flex-direction: column; top: 0px; left: 0px;"></ul><ul id="chakra-toast-manager-top-right" style="position: fixed; z-index: 5500; pointer-events: none; display: flex; flex-direction: column; top: 0px; right: 0px;"></ul><ul id="chakra-toast-manager-bottom-left" style="position: fixed; z-index: 5500; pointer-events: none; display: flex; flex-direction: column; bottom: 0px; left: 0px;"></ul><ul id="chakra-toast-manager-bottom" style="position: fixed; z-index: 5500; pointer-events: none; display: flex; flex-direction: column; margin: 0px auto; bottom: 0px; right: 0px; left: 0px;"></ul><ul id="chakra-toast-manager-bottom-right" style="position: fixed; z-index: 5500; pointer-events: none; display: flex; flex-direction: column; bottom: 0px; right: 0px;"></ul></div>
```

## 💥 Steps to reproduce

Install Chakra and react-testing-library. 

1. Show a toast.
2. Now try to select alert via RTL

## 💻 Link to reproduction

This shows the double alert causing selection issues.
https://codesandbox.io/s/chakra-toast-renders-two-alerts-mlhyr

## 🧭 Possible Solution

1. Add an option to remove all toasts outside of a component (for example in an afterEach) and disable animations while doing so. I know there is `removeAll`, is this callable outside of the useToast hook?
2. Somehow hide one of the alerts from the accessibility tree? Maybe we can hide the visible alert, since the "hidden" one is really the one meant to be seen by screenreaders.
3. Do not render the Toast Manager divs unless a toast is present.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.0.3         |
| Browser          |      Chrome      |
| Operating System |    Mac        |

**Comment by cloud-walker** [comment]
I can confirm all of that, its really annoying T_T

**Comment by avaragado** [comment]
Please keep this open. It’s still an issue.

It would be great to have some testing guidance in the documentation if nothing else.

**Comment by dca123** [comment]
Anytime I render any component using the jest + react testing library, the toast manager is also included in that render. Is there any workaround for this problem?  
For example, when I render a ChakraButton, I receive - 
```
<body>
      <div
        id="chakra-toast-portal"
      >
        <ul
          id="chakra-toast-manager-top"
          style="position: fixed; z-index: 5500; pointer-events: none; display: flex; flex-direction: column; margin: 0px auto; top: 0px; right: 0px; left: 0px;"
        />
        <ul
          id="chakra-toast-manager-top-left"
          style="position: fixed; z-index: 5500; pointer-events: none; display: flex; flex-direction: column; top: 0px; left: 0px;"
        />
        <ul
          id="chakra-toast-manager-top-right"
          style="position: fixed; z-index: 5500; pointer-events: none; display: flex; flex-direction: column; top: 0px; right: 0px;"
        />
        <ul
          id="chakra-toast-manager-bottom-left"
          style="position: fixed; z-index: 5500; pointer-events: none; display: flex; flex-direction: column; bottom: 0px; left: 0px;"
        />
        <ul
          id="chakra-toast-manager-bottom"
          style="position: fixed; z-index: 5500; pointer-events: none; display: flex; flex-direction: column; margin: 0px auto; bottom: 0px; right: 0px; left: 0px;"
        />
        <ul
          id="chakra-toast-manager-bottom-right"
          style="position: fixed; z-index: 5500; pointer-events: none; display: flex; flex-direction: column; bottom: 0px; right: 0px;"
        />
      </div>
      <div>
        <button
          class="chakra-button css-113xcha"
          type="button"
        />
      </div>
    </body>
```

**Comment by sbaileys** [comment]
I am having this same issue. Have been trying to render literally anything to test using getByText, getByID - everything fails because screen.debug() only shows me toasts and margins instead of the HTML code for the whole page and its actual components.

**Comment by lee-reinhardt** [comment]
> I am having this same issue. Have been trying to render literally anything to test using getByText, getByID - everything fails because screen.debug() only shows me toasts and margins instead of the HTML code for the whole page and its actual components.

You can increase the output size of `screen.debug()` by passing `DEBUG_PRINT_LIMIT`, eg, (`DEBUG_PRINT_LIMIT=100000 jest --watch`).

**Comment by kodell** [comment]
> Anytime I render any component using the jest + react testing library, the toast manager is also included in that render. Is there any workaround for this problem?

This is the problem I'm having as well. I'm not rendering a `<Toast>` anywhere in my app so I'm confused about what's adding these elements. They are visible in the snapshot from react-testing-library, in `baseElement`, just like what you posted in your snippet.

All I can think of is I'm rendering a `<ChakraProvider>`, but even that is only in one component, yet I'm seeing this artifact across all of my snapshot tests.

**Comment by avaragado** [comment]
*keepalive packet*

**Comment by matheusmb** [comment]
Facing same issues here

**Comment by tamaskani** [comment]
I've had this problem too
you should remove height:100vh from all tags
this fixed it for me

**Comment by timkindberg** [comment]
@tamaskani I don't understand how adding some css would fix any of the three issues listed in the original post? Which issue are you saying the `height: 100vh` would fix?

**Comment by dlindenkreuz** [comment]
I got pretty far using @kodell's suggestion, but tests involving toasts were randomly failing in some rare cases.

Closing all toasts programmatically, [as seen in the Chakra tests](https://github.com/chakra-ui/chakra-ui/blob/3f0b369e34e7336df2d51d9978d6334cc073e541/packages/toast/test/use-toast.test.tsx#L9-L16), seems to work more reliably in the end:
https://github.com/chakra-ui/chakra-ui/blob/3f0b369e34e7336df2d51d9978d6334cc073e541/packages/toast/test/use-toast.test.tsx#L9-L16

**Comment by dlindenkreuz** [comment]
*keepalive packet*

**Comment by wildeyes** [comment]
_keepalive packet_

**Comment by valenciaHQ** [comment]
up

**Comment by alexonaci20robots** [comment]
up

**Comment by hevans90** [comment]
This is still annoying as hell, and after updating to chakra 2.x, the above workarounds no longer work.

**Comment by hevans90** [comment]
After 2.x, the globally added HTML changes significantly:

<img width="938" alt="image" src="https://user-images.githubusercontent.com/12142999/173192487-494c924c-4d0f-479d-9815-d924c07f791b.png">

And my attempts to interrogate the DOM in a setup preset (as before), just return empty collections...

<img width="684" alt="image" src="https://user-images.githubusercontent.com/12142999/173192478-a203f3b6-8b8b-4bbf-bae6-23593be42614.png">

<img width="574" alt="image" src="https://user-images.githubusercontent.com/12142999/173192501-f3587075-0cec-473b-a9cf-a09cef1ae4db.png">

**Comment by lluia** [comment]
Having the same issues pretty annoying 🥲

**Comment by rafaelaprado** [comment]
Same issues

**Comment by Ninfa-Jeon** [comment]
Facing this issue. No idea how to clear the toasts.

**Comment by bojackhorseman0309** [comment]
Subscribing to here, current beforeEach that Chakra UI uses internally does work for me on Chakra UI 1.6

` beforeEach(async () => {
    await waitFor(
      () => {
        expect(
          screen.queryAllByText("successToastHeading").length
        ).toBe(0);
      },
      { timeout: 50000 }
    );`

Though they run extremely slow, I assume that's because I have a duration of 4000 on them, though would like to see a solution that can close them all up immediately before each test.

**Comment by 1NF053C** [comment]
I'm using Chakra UI for the first time and integrated it with my vite + react + ts scaffold. The only chakra import I've done so far is the ChakraProvider in my main.tsx file.

Without importing any other chakra component, my existing application's styles are become wonky and upon inspecting the HTML I see a ton of "portal" & "toast" elements injected in my HTML.

Why is this happening?

**Comment by with-heart** [comment]
@1NF053C that's unrelated to this issue. `ChakraProvider` uses a global css reset that can be disabled by setting `resetCSS={false}` (but doing so will mess with how your Chakra components look).

**Comment by luisspassos** [comment]
> Subscribing to here, current beforeEach that Chakra UI uses internally does work for me on Chakra UI 1.6
> 
> ` beforeEach(async () => { await waitFor( () => { expect( screen.queryAllByText("successToastHeading").length ).toBe(0); }, { timeout: 50000 } );`
> 
> Though they run extremely slow, I assume that's because I have a duration of 4000 on them, though would like to see a solution that can close them all up immediately before each test.

@bojackhorseman0309 Try this:
```javascript
import {
  waitForElementToBeRemoved,
} from '@testing-library/react';
import { act } from 'react-dom/test-utils';

it('test', async () => {
  await act(async () => {
    jest.runAllTimers();
  });

  await waitForElementToBeRemoved(() =>
    screen.queryAllByText('successToastHeading')
  );

  expect(screen.queryAllByText('successToastHeading').length).toBe(0);
});
```

**Comment by lluia** [comment]
Any idea why toasts (I find it happens the same with modals) take so long to render in **Jest** with **JSDOM**? Is it because of fade-in animations or something?

**Comment by luisspassos** [comment]
Solution for Cypress component testing:

```ts
beforeEach(() => {
  function closeToasts() {
    // the toasts persist between the tests, because of that we need to close them.
    toast.closeAll();

    cy.get('[class="chakra-toast"]').should('not.exist');
  }

  closeToasts();
});
```
You could put this inside your support file as well, so it can run before every test.

**Comment by segunadebayo** [comment]
This is a design constraint/flaw in v2. We've improved this in Chakra v3.
