### ISSUE TITLE
[Modal with Input] Input focus resets on every keystroke

### ISSUE THREAD

**Issue by wleroux** [chakra-ui/chakra-ui#297]
**Describe the bug**
When a modal contains multiple inputs, the first input selected is re-selected on every change when using useState.

See: https://codesandbox.io/s/old-cdn-xizlo

**Expected Behavior**
After the initial mounting, the focus should not change.

**To Reproduce**
1. Go to https://codesandbox.io/s/old-cdn-xizlo
2. Click "Open Modal"
3. Type "Hello" in First Name
4. Type "World" in Last Name
5. Ensure focus is not reset to First Name

**Suggested solution(s)**
I suspect the issue is that the Modal resets focus whenever a change occurs. The initial focus ref should only be used during mounting, not all component changes.

**Desktop:**
- Windows 10 Pro
- Firefox (70.0.1) and Chrome (78.0.3904.108)
- @chakra-ui/core: 0.5.1

**Additional context**
It seems like the first input that was focused is 'locked' in. Any changes afterwards refocuses on the initial focus. If I set initialFocusRef to null or undefined, the issue still occurs.

P.S.: I left another issue in there RE: the input extending beyond the modal. I was able to fix that locally using boxSizing="border-box". Perhaps the default should be change?

**Comment by segunadebayo** [comment]
Thanks for this issue.

I just looked into it and resolved it. Will release a patch soon.

As regards the `box-sizing`, you might need to add the `CSSReset` component. It applies that style by default.
