### ISSUE TITLE
Type 'IconType' is not assignable to type 'string & IconType'

### ISSUE THREAD

**Issue by neilnahid** [chakra-ui/chakra-ui#2970]
# 🐛 Bug report

Type error when using <Icon> component's "as" property

## 💥 Steps to reproduce
1. use <Icon> component with "as" prop
2. use third party icon library(react-icons/fi in my case)
3. error occurs 

## 🧐 Expected behavior
Should not produce Type error

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.1.2           |
| Browser          |   Version 87.0.4280.88 (Official Build) (64-bit)         |
| Operating System |     Ubuntu 20.10       |

## 📝 Additional information
![image](https://user-images.githubusercontent.com/25801890/103849027-b2f08100-50de-11eb-8304-409b93fcc168.png)

**Comment by TimKolberger** [comment]
Hi @neilnahid,

I could not reproduce the TS error on [codesandbox with TypeScript 4.1.2](https://codesandbox.io/s/chakra-ui-icon-as-issue-2970-9hz27), nor on my machine with TypeScript 3.9.7, 4.1.2 or 4.1.3 together with different versions of `@types/react` (16.9.35, 16.9.49, 17.0.0). 

Could you please provide a reproduction of this error?

**Comment by neilnahid** [comment]
Turns out, it has something to do with my custom type declaration file. My bad.
```ts
// The 'as' prop on styled components
declare global {
  namespace JSX {
    interface IntrinsicAttributes<T> extends DOMAttributes<T> {
      as?: string;
    }
  }
}
```
