### ISSUE TITLE
[BUG] ChakraUI cant working on mobile browser

### ISSUE THREAD

**Issue by ghost** [chakra-ui/chakra-ui#2972]
# 🐛 Bug report

> Nothing appears on mobile browser

## 💥 Steps to reproduce

> I got a simple starter application for React and chakraui to the product environment. But there is a problem with the mobile browser

> I followed the instruction there

1. Go to 'https://chakra-ui.com/guides/integrations/with-cra'
2. `  npx create-react-app my-app --template @chakra-ui `
3. yarn build
4. deploy to prod

## 💻 Link to reproduction

> [demo here](https://chakrauitesting.surge.sh/)

This chakra is made as in the ui documentation. There is a problem with mobile browsers.

**Comment by TimKolberger** [comment]
Could elaborate which on which mobile browser and OS? Seems to work fine on iOS 14.3.

**Comment by segunadebayo** [comment]
Seems to be working fine on my end as well.

I'm sorry but we don't understand the problem you are reporting.

Kindly provide more information about this and we'll re-open.

Thanks
