### ISSUE TITLE
NumberInput with precision has pattern that excludes negative values

### ISSUE THREAD

**Issue by EdNutting** [chakra-ui/chakra-ui#2976]
# 🐛 Bug report

The NumberInput `pattern` created when using `precision` rejects negative values.

## 💥 Steps to reproduce

1. Create a number input

```
<NumberInput
      min={-12}
      max={12}
      precision={1}
  >
      <NumberInputField />
      <NumberInputStepper>
          <NumberIncrementStepper />
          <NumberDecrementStepper />
      </NumberInputStepper>
  </NumberInput>
```

2. Enter a value such as `-1.2`. Note: This issue doesn't seem to occur for values like `-10` - where precision is not needed.

## 🧐 Expected behavior

The value should be accepted by the pattern.

## 🧭 Possible Solution

Change the pattern from `[0-9]*(.[0-9]+)?` to `-?[0-9]*(.[0-9]+)?` when the `min` property is less than zero.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      "@chakra-ui/react": "^1.0.3"      |
| Browser          |      Any (Firefox / Chrome tested)      |
| Operating System |     N/A       |

## 📝 Additional information

![Number field is highlighted red even though the input is valid](https://user-images.githubusercontent.com/1746336/103929201-dc2c0400-5114-11eb-9be9-b6505e4bdb66.png)

Number field is highlighted red even though the input is valid

**Comment by EdNutting** [comment]
Keeping this open.

**Comment by EdNutting** [comment]
Bump.

**Comment by segunadebayo** [comment]
Hi @EdNutting,

I can't seem to reproduce this with the latest version of Chakra UI. Kindly upgrade to the latest version and if this issue persists, I'll re-open and investigate.

**Comment by stuisme** [comment]
@segunadebayo  This is not fixed in `1.7.2`

```
<NumberInput value={value} onChange={handleOnChange} precision={2} min={-9999.99} max={9999.99}>
  <NumberInputField />
 </NumberInput>
 ```
 
 then type in -123.45 in the input and try to submit via a form (i.e. with formik)
 
 on submit, you receive an html error because the <input /> codes with a `pattern="[0-9]*(.[0-9]+)?"`

**Comment by stuisme** [comment]
If anyone else runs into this, here is a workaround

```
<NumberInput value={value} onChange={handleOnChange} precision={2} min={-9999.99} max={9999.99}>
  <NumberInputField pattern="(-)?[0-9]*(.[0-9]+)?" />
 </NumberInput>
 ```

**Comment by hooch** [comment]
Why is this closed?

**Comment by EdNutting** [comment]
It's probably still broken because despite providing a valid reproduction, the lib maintainers thought it wasn't reproducible. Furthermore, the library's tests (both legacy and current) only test positive input values (which is a fairly obvious hole that any fuzzer-based or property-based validation would have picked up on, e.g. Quickcheck-style testing.)

The bug is that the pattern is hard-coded to a default of `[0-9]*(.[0-9]+)?`, which is just wrong. There's no excuses here, the minus sign is needed if min is less than zero (even without precision set.) 

The correct regex might be:
* With precision > 0:  
    * `min < 0`  ->  `-?[0-9]*(.[0-9]+)?`
    * `min >= 0`  ->  `[0-9]*(.[0-9]+)?`
* With precision <= 0:
    * `min < 0`  ->  `-?[0-9]*`
    * `min >= 0`  ->  `[0-9]*`

There is an argument that the pattern needn't validate the semantics of the input (since min/max/precision will do that) and that the pattern should be a syntax-only validation. Although this is a confusing to a user, this is the "wisdom of web developers" in various places. In which case, the pattern would just be `-?[0-9]*(.[0-9]+)?`.

Note this change log entry: https://github.com/chakra-ui/chakra-ui/blob/38acfe89c5d1f1edc67bbc44e2edd38980ca3e08/packages/components/number-input/CHANGELOG.md?plain=1#L1073C1-L1083
It would appear the author of that change log entry knew that the minus sign might be an optional part of the pattern.
