### ISSUE TITLE
Tab panels reveals box shadow

### ISSUE THREAD

**Issue by brennanfife** [chakra-ui/chakra-ui#2979]
# 🐛 Bug report
When clicking on a tab panel, you'll notice a box shadow around the panel appears

## 💥 Steps to reproduce
1. Vist the [Tabs document page](https://chakra-ui.com/docs/components/tabs)
2. Click the tab panel
3. Notice the box shadow outline around the tab panel

## 🧐 Expected behavior

- Don't remember this existing before. I see in the latest update, the tabs components were modified so this likely has something to do with it.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.12           |
| Browser          |  chrome         |
| Operating System |  mac          |

## 📝 Additional information

<img width="763" alt="Screen Shot 2021-01-07 at 11 15 02 AM" src="https://user-images.githubusercontent.com/31396350/103922670-b1708a00-50d9-11eb-95ce-c2b3b77f1ef6.png">

**Comment by brahim-kellou** [comment]
This is an issue with CSS

it appears also in the tab title: 
![image](https://user-images.githubusercontent.com/32751978/104028142-ab0d0b80-51c8-11eb-817e-cd972488b797.png)

**Comment by brennanfife** [comment]
@brahim-kellou The box-shadow is definitely related to the css. The issue is if there is suppose to be a box shadow around the tab content, it should then be consistent with what you see in other chakra box shadows (i.e. like with the tab title)
Additionally, the tab title's box-shadow is suppose to be there.

**Comment by brahim-kellou** [comment]
@brennanfife I'm not sure that the `box-shadow` should exist for both the tab title and the tab panel.
I've checked some examples in Tailwind, and they are not setting a `box-shadow` for the tab title. 
Also, for the tab panel, I think the `box-shadow` should exist only if the content is a `textarea` or an `input`, but in [Tabs document page](https://chakra-ui.com/docs/components/tabs) examples, the content of the tab panel is a `div`.

**Comment by segunadebayo** [comment]
Thanks for catching this. Just pushed a fix for it.
