### ISSUE TITLE
Navbar component

### ISSUE THREAD

**Issue by Vectormike** [chakra-ui/chakra-ui#298]
Any future implementation of a Navbar component?

**Comment by jeanbauer** [comment]
Hey @Vectormike, **no**. You can check here why: https://github.com/chakra-ui/chakra-ui/issues/291

And here is the recipe so you can build your own: https://codesandbox.io/s/chakra-ui-header-sbsh5?fontsize=14&hidenavigation=1&theme=dark

Hope it helps.

**Comment by robertoandres24** [comment]
> Hey @Vectormike, **no**. You can check here why: #291
> 
> And here is the recipe so you can build your own: https://codesandbox.io/s/chakra-ui-header-sbsh5?fontsize=14&hidenavigation=1&theme=dark
> 
> Hope it helps.

thanks man.
Btw, I had some responsive fixes.
https://codesandbox.io/s/chakra-ui-header-forked-n8l02

**Comment by pythonidae-lupus** [comment]
> > Hey @Vectormike, **no**. You can check here why: #291
> > And here is the recipe so you can build your own: https://codesandbox.io/s/chakra-ui-header-sbsh5?fontsize=14&hidenavigation=1&theme=dark
> > Hope it helps.
> 
> thanks man.
> Btw, I had some responsive fixes.
> https://codesandbox.io/s/chakra-ui-header-forked-n8l02

Here are some further updates needed after Chakra-ui updated
[https://codesandbox.io/s/chakra-ui-header-forked-vwcwp?file=/src/header.js](https://codesandbox.io/s/chakra-ui-header-forked-vwcwp?file=/src/header.js)
