### ISSUE TITLE
[InputGroup, InputRightAddon] Right addon disappears under background color on focus

### ISSUE THREAD

**Issue by DavidJFelix** [chakra-ui/chakra-ui#300]
**Describe the bug**
When a background color is set on any parent tag, a child `InputGroup` with `InputRightAddon` will have the `InputRightAddon` disappear "under" the background when the `Input` that is part of the `InputGroup` is focused

Here's a really ugly screenshot of it happening in the chakra docs with "teal" forced as a background color (via dev tools).

<img width="793" alt="image" src="https://user-images.githubusercontent.com/263432/71069693-38596a00-2147-11ea-98f9-701fd7fc62cd.png">

And a video of performing the change:

https://streamable.com/pfgsd

**Expected Behavior**

If there is no background color, the group performs as expected. Highlights go over the right addon on-focus and the addon does not disappear. I expect this with background colors.

**To Reproduce**
- Go to the chakra docs for input https://chakra-ui.com/input
- Open developer tools and set the background color to anything
- Click an input that has a right addon and watch it disappear.

**Suggested solution(s)**

I believe this is related to the way flex box handles z-index. ~~For some reason it doesn't put the left addon under the background, but it does for the right addon.~~ The left addon is left alone because the selector is `input:flex +` so it applies to the next item.

**Additional context**

**Comment by DavidJFelix** [comment]
New suggestion: don't apply `input:focus + .inputGroup { z-index: -1 }` instead apply `.input: focus { z-index:2 }`

**Comment by DavidJFelix** [comment]
Here's my workaround code that performs the suggestion above:

```javascript
import {get} from 'styled-system'
import {useTheme} from '@chakra-ui/core'
...
const theme = useTheme()
const _focusBorderColor = get(theme.colors, 'blue.500', 'blue.500')
...
<InputGroup>
  <InputLeftAddon children="before" />
  <Input
    name="name"
    type="text"
    placeholder="input"
    _focus={{
      zIndex: 2,
      boxShadow: `0 0 0 1px ${_focusBorderColor}`,
    }} 
  />
  <InputRightAddon
    children="right"
    css={{
      'input:focus + &': {zIndex: 0},
    }}
  />
</InputGroup>
```

**Comment by segunadebayo** [comment]
Thanks for your suggestion @DavidJFelix . I'll try it out and update the code once it works as expected.
