### ISSUE TITLE
'useCallbackRef' is not exported from '@chakra-ui/hooks'

### ISSUE THREAD

**Issue by brennanfife** [chakra-ui/chakra-ui#3006]
[Discord Link](https://discord.com/channels/660863154703695893/758645914868514827/797919545394331658)
 On a fresh install with CRA, the following compiler error appears 
 
 ```
 ./node_modules/@chakra-ui/portal/dist/esm/portal.js
Attempted import error: 'useCallbackRef' is not exported from '@chakra-ui/hooks'.
```

**Comment by massqeen** [comment]
having the same issue

**Comment by danecando** [comment]
This issue is also present in v1.1.2

I had to roll back to 1.1.1

**Comment by KoenBrouwer** [comment]
I can also confirm that I have this issue.

```
$ npm ls | grep chakra-ui
├── @chakra-ui/icons@1.0.2
├── @chakra-ui/react@1.1.3

```

**Comment by rodbs** [comment]
same thing!

**Comment by WolffDev** [comment]
Same issue here. Had to revert back to `@chakra-ui/react@1.1.2`

**Comment by kafiln** [comment]
If you are facing the same issue you can fix this temporary by changing your package.json to: 
 `"@chakra-ui/react": "1.1.2",`
NOT  `"@chakra-ui/react": "^1.1.2",`

**Comment by JohannesKlauss** [comment]
Also have problem running it with Storybook:

```
logical-prop.js:29 Uncaught TypeError: Object(...) is not a function
    at logicalTransform (logical-prop.js:29)
    at Object.logical (logical-prop.js:41)
    at Module.../../node_modules/@chakra-ui/styled-system/dist/esm/config/position.js (position.js:20)
    at __webpack_require__ (bootstrap:851)
    at fn (bootstrap:150)
    at Module.../../node_modules/@chakra-ui/styled-system/dist/esm/config/index.js (index.js:1)
    at __webpack_require__ (bootstrap:851)
    at fn (bootstrap:150)
    at Module.../../node_modules/@chakra-ui/styled-system/dist/esm/index.js (index.js:1)
    at __webpack_require__ (bootstrap:851)
```

**Comment by lednhatkhanh** [comment]
Having the exact same issue with @JohannesKlauss, created an issue here: https://github.com/chakra-ui/chakra-ui/issues/3009

**Comment by amitojsingh366** [comment]
Same issue....

**Comment by anubra266** [comment]
Has anything been done about this please?

**Comment by wvieed** [comment]
No can you halp me please

احصل على Outlook لـ iOS<https://aka.ms/o0ukef>
________________________________
من: Abraham <notifications@github.com>
‏‏تم الإرسال: Monday, January 11, 2021 12:27:50 PM
إلى: chakra-ui/chakra-ui <chakra-ui@noreply.github.com>
نسخة: Subscribed <subscribed@noreply.github.com>
‏‏الموضوع: Re: [chakra-ui/chakra-ui] Issues installing Chakra V1.13 (#3006)


Has anything been done about this please?

**Comment by cschroeter** [comment]
@segunadebayo 

`@chakra-ui/hooks@1.0.2` does not export `export * from "./use-callback-ref"`. Which is not quite understandable though, since if you build `@chakra-ui/hooks` locally, everything is exported correctly.

In https://github.com/chakra-ui/chakra-ui/blob/develop/packages/hooks/src/index.ts#L18 the export is declared and the file has not been touched since 3 days 😕

**Comment by jtparrett** [comment]
Same here

**Comment by cschroeter** [comment]
I'm tempted to just build a new release, but I'm not sure if that won't just create another broken package.

**Comment by with-heart** [comment]
![image](https://user-images.githubusercontent.com/1954752/104182604-b20d6700-53de-11eb-8231-1efa706d2461.png)

`@chakra-ui/hooks@1.0.2` was previously published 25 days ago. Investigating how we ended up with a version mismatch.

**Comment by with-heart** [comment]
Our release process is automated using `changesets` and there wasn't a changeset file involving `@chakra-ui/hooks` for this release, which means it wouldn't know to bump the version before attempting to publish. Will open a PR with a fix shortly.

**Comment by cschroeter** [comment]
@with-heart great work. but I'm afaraid there is more to the story.

**Comment by pengliheng** [comment]
emmm.

**Comment by wvieed** [comment]
لم افهم

احصل على Outlook لـ iOS<https://aka.ms/o0ukef>
________________________________
من: Peng, LiHeng <notifications@github.com>
‏‏تم الإرسال: Monday, January 11, 2021 8:00:30 PM
إلى: chakra-ui/chakra-ui <chakra-ui@noreply.github.com>
نسخة: wvieed <waleed_saleeh@outlook.sa>; Comment <comment@noreply.github.com>
‏‏الموضوع: Re: [chakra-ui/chakra-ui] 'useCallbackRef' is not exported from '@chakra-ui/hooks' (#3006)


same issue i have to face.

Failed to compile
./node_modules/@chakra-ui/portal/dist/esm/portal.js
Attempted import error: 'useCallbackRef' is not exported from '@chakra-ui/hooks'.
This error occurred during the build time and cannot be dismissed.
