### ISSUE TITLE
Attempted import error: 'useCallbackRef' is not exported from '@chakra-ui/hooks'

### ISSUE THREAD

**Issue by BruceJi7** [chakra-ui/chakra-ui#3008]
I installed Chakra using the recommended commands on the getting started page, and ran into this issue immediately after adding the ChakraProvider component :S

```
Failed to compile.

./node_modules/@chakra-ui/portal/dist/esm/portal.js
Attempted import error: 'useCallbackRef' is not exported from '@chakra-ui/hooks'.
```

I looked in the folder and it is indeed not there :(

More detail: This issue happened when I tried to use 1.1.3, but I uninstalled hooks and 1.1.3, and installed 1.1.1, and there is no issue.

**Comment by gantoreno** [comment]
Same issue here, using the `@chakra-ui/typescript` template.

<img width="751" alt="Screen Shot 2021-01-10 at 10 48 56 PM" src="https://user-images.githubusercontent.com/43397475/104143482-0809ec80-5396-11eb-8b14-fc0e0a28e7f6.png">

**Comment by rafaelsorto** [comment]
I'm having the same issue with next js with chakra typescript template. I solved it by installing chakra-react 1.1.2

`npm install @chakra-ui/react@1.1.2`

It seems there was an update 8 hours ago to version 1.1.3 which is broken.

**Comment by neg4n** [comment]
Can confirm that this issue also occurs with pure `create-next-app` and adding `@chakra-ui/react@1.1.3` manually.
`1.1.2` version works fine.

**Comment by amitojsingh366** [comment]
Getting this same issue with they typescript template `@chakra-ui/typescript`

**Comment by cschroeter** [comment]
Closing in favour of #3006
