### ISSUE TITLE
New App Fails to compile

### ISSUE THREAD

**Issue by anubra266** [chakra-ui/chakra-ui#3011]
# 🐛 Bug report

> Trying to run a new CHakra App. It fails with
```bash
./node_modules/@chakra-ui/portal/dist/esm/portal.js
Attempted import error: 'useCallbackRef' is not exported from '@chakra-ui/hooks'.
```

## 💥 Steps to reproduce

- Create react app with chakra template
- run `yarn start`
- See error

## 🧐 Expected behavior

> to successfully start my app

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |1.0.0|
| Browser          |Firefox
| Operating System |Zorin OS|

## 📝 Additional information

![image](https://user-images.githubusercontent.com/30869823/104162912-c577fc80-53f5-11eb-99cd-2f64f4af0926.png)

**Comment by cschroeter** [comment]
Closing in favour of #3006
