### ISSUE TITLE
Right-clickable, i.e. Context Menu, for Chakra

### ISSUE THREAD

**Issue by mike-fam** [chakra-ui/chakra-ui#3013]
Hi Chakra team. First of all, I just want to say thank you for an amazing library and all of your great work.

# 🚀 Feature request

It would be great if chakra provides a right-clickable (i.e. context menu) component out of the box. I'm not sure if I'm capable enough to contribute directly to this repository so I want to provide a snippet of my own implementation of ContextMenu instead, and hopefully, a Chakra expert can convert my idea/code to integrate it to the library.

## 🧱 Problem Statement / Justification
I recently encountered a situation where I had to implement a context menu component. I found nothing on the internet. The components I found are either not satisfactory or not maintained anymore.

## ✅ Proposed solution or API
I have implemented a ContextMenu component using Chakra components.
[CodeSandbox](https://codesandbox.io/s/chakra-contextmenu-jlz10)

## 📝 Additional Information
Demo

https://user-images.githubusercontent.com/31090859/104186206-d3636700-5461-11eb-905e-2d5f76361576.mov

**Comment by segunadebayo** [comment]
Thanks for the request! Considering this isn't a bug, I'll add this to our project board so you can track the progress.

Check it here: https://github.com/chakra-ui/chakra-ui/projects/6

Cheers.

**Comment by sarimabbas** [comment]
Thanks Mike for sharing your code! For anyone who is interested, I expanded on it by adding support for multiple menus, message passing etc. https://codesandbox.io/s/chakra-ui-recoil-context-menu-dfy7j?file=/src/demo.tsx. It uses Recoil but can be reconfigured to work with Context API

Just wanted to share with someone who might be looking and doesn't want to go through the hassle 😊

**Comment by lukasbach** [comment]
If it helps anyone, I've written a small utility component for using context menus with Chakra Ui :) 

https://github.com/lukasbach/chakra-ui-contextmenu

**Comment by nelsieborja** [comment]
I think this feature can be simply implemented as a custom hook.
Straightforward example: https://blog.logrocket.com/how-to-create-a-context-menu-in-react/
