### ISSUE TITLE
Request: add star icon variants 

### ISSUE THREAD

**Issue by codetheweb** [chakra-ui/chakra-ui#3021]
# 🚀 Feature request

> Please describe your request in one or two sentences.

A half star icon would be a really nice addition:

![external-content duckduckgo com](https://user-images.githubusercontent.com/7410405/104254993-a8ffb280-543d-11eb-88fc-8fe32a0cabce.jpg)

As would be an outlined star icon.

## 🧱 Problem Statement / Justification

> Please provide valid reason(s) why this should added to Chakra UI.

This would allow for the implementation of star-rating systems without having to pull in another icon dependency.

**Comment by segunadebayo** [comment]
Thanks for the request! Considering this isn't a bug, I'll add this to our project board so you can track the progress.

Check it here: https://github.com/chakra-ui/chakra-ui/projects/6

Cheers.

**Comment by HassanShanJava** [comment]
Hi @segunadebayo, I actually need a rating component with 5 stars like this, you tell me how i can build it with chakra ui

**Comment by farshidinanloo** [comment]
there is work around to do this:

**index.jsx**
```jsx 
import { StarIcon } from '@chakra-ui/icons';
import { HalfStarContainer } from './styles';

const HalfStar = () => {
  return (
    <HalfStarContainer>
      <StarIcon color="gold" />
      <StarIcon color="white" stroke="gold" />
    </HalfStarContainer>
  );
};

export default HalfStar;

```


**styles.js**

```jsx
import { Box } from '@chakra-ui/react';
import styled from '@emotion/styled';

export const HalfStarContainer = styled(Box)`
  svg {
    position: absolute;
  }

  svg:nth-child(1) {
    clip-path: polygon(0 0, 50% 0, 50% 100%, 0 100%);
    z-index: 1;
  }
`;

```

**output**
![Capture](https://github.com/chakra-ui/chakra-ui/assets/46605967/9ece219f-9e8f-4344-a14d-45fb73505b9d)
