### ISSUE TITLE
Using `portalZIndex` on the ChakraProvider makes the app unusable (1.1.4 regresion)

### ISSUE THREAD

**Issue by santialbo** [chakra-ui/chakra-ui#3026]
# 🐛 Bug report
Since updating to 1.1.4 (from 1.1.2) using `portalZIndex` on the ChakraProvider makes one of the portal elements to bee full-screen and "capture" all mouse interaction, making the app underneath unusable.

This is working as expected on versions <= 1.1.2

## 💥 Steps to reproduce
- Use `zIndex` to position some elements of your app
- Use `portalZIndex` on the `ChakraProvider` to make sure portals render on top of your `z-index`-positioned element.

## 💻 Link to reproduction
https://codesandbox.io/s/quiet-pond-i94rd?file=/src/App.tsx

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.1.4       |

**Comment by with-heart** [comment]
Looks like this is part of 6844dd68265a735ce85950b8c0997dfc3ce3dd77 in `portal.tsx`: https://github.com/chakra-ui/chakra-ui/blob/6844dd68265a735ce85950b8c0997dfc3ce3dd77/packages/portal/src/portal.tsx#L24-L29

We didn't have that styling previously. My first thought was to add `pointer-events: none` which works to allow the button to be clicked, but then leaves the content of the portal (the menu buttons) unclickable. Not entirely sure what the rationale was here, so I'm going to assign this to @segunadebayo so he can give us some more context!

**Comment by segunadebayo** [comment]
Looking into this now.
