### ISSUE TITLE
Unable to use nested CSS rules with TS

### ISSUE THREAD

**Issue by hutber** [chakra-ui/chakra-ui#3027]
I am trying to spread some inline css rules which work without issues in terms of functionally. 
However as you can see from one of the TS errors `css` is also being flagged but I cannot think of a good reason for this sadly. To me I should be able to use nested styles like this.

      "@chakra-ui/react": "^1.0.4",
      "@chakra-ui/theme-tools": "^1.0.2",

# Avatar/index.tsx

    <Image
      styles={{
        "& > div": {
          position: "relative",
        },
      }}
    />

# <Image>

    type Props = ImageProps & {
      styles?: {
        "& > div"?: {
          position?: string
        }
      }
    }
    
    export const Image: React.FC<Props> = ({
      styles,
    }) => {    
      const css =
        objectFit === "cover"
          ? {
              ...styles,
              "& > div": {
                position: "initial !important",
                ...(styles && styles["& > div"] && { ...styles["& > div"] }),
                width: "100%",
                height: "100%",
              },
            }
          : styles

      return (
        <Box
          css={css}
        >
        //.... stuff....
        </Box>
      )
    }
    
    Image.defaultProps = {
      type: "standard",
      objectFit: "cover",
      fillColor: "white",
    }

# TS Errors
```

components/Image/index.tsx:120:7 - error TS2322: Type '{ "& > div"?: { overflow?: string; borderRadius?: number; position?: CSSInterpolation; }; } | { transition: string; height: string; "& > div": { width: string; height: string; marginBottom: string; overflow?: string; borderRadius?: number; position: CSSInterpolation; }; "& > div > div": { ...; }; }' is not assignable to type 'Interpolation<{}>'.
  Type '{ "& > div"?: { overflow?: string; borderRadius?: number; position?: CSSInterpolation; }; }' is not assignable to type 'Interpolation<{}>'.
    Type '{ "& > div"?: { overflow?: string; borderRadius?: number; position?: CSSInterpolation; }; }' is not assignable to type 'CSSObject'.
      Property '"& > div"' is incompatible with index signature.
        Type '{ overflow?: string; borderRadius?: number; position?: CSSInterpolation; }' is not assignable to type 'CSSInterpolation'.
          Type '{ overflow?: string; borderRadius?: number; position?: CSSInterpolation; }' is not assignable to type 'CSSObject'.
            Types of property 'position' are incompatible.
              Type 'CSSInterpolation' is not assignable to type '"-moz-initial" | "inherit" | "initial" | "revert" | "unset" | "fixed" | "-webkit-sticky" | "absolute" | "relative" | "static" | "sticky" | Position[]'.
                Type 'string' is not assignable to type '"-moz-initial" | "inherit" | "initial" | "revert" | "unset" | "fixed" | "-webkit-sticky" | "absolute" | "relative" | "static" | "sticky" | Position[]'.

120       css={css}
          ~~~

  node_modules/@chakra-ui/system/dist/types/system.types.d.ts:54:5
    54     css?: Interpolation<{}>;
           ~~~
    The expected type comes from property 'css' which is declared here on type 'IntrinsicAttributes & { as?: ElementType<any>; } & ChakraProps & Pick<any, string | number | symbol> & Pick<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | ... 253 more ... | "is">, "key" | ... 253 more ... | "is">'


Found 1 error.

```

  [1]: https://chakra-ui.com/

**Comment by bibekg** [comment]
@hutber Did you find a fix for this? Running it the same issue.

**Comment by hugotox** [comment]
Same issue, please @hutber why this was closed?

**Comment by hutber** [comment]
Urgh sorry guys, I cannot remember at all.

However checking the code here was my final solution:
```

      <Flex
        width="full"
        css={{
          "& > div": {
            width: "100%",
          },
          opacity,
        }}
        {...attrs}
        data-size={size}
        data-testid="image"
        ref={backgroundRef}
        visibility={imageWidth ? "visible" : "hidden"}
      >
```

So it appears that I the issue here is that the types are defined in a way that you cannot use `width` with `position: relative` and looking through this, the code and the way its written backs this up :)... Good luck!
