### ISSUE TITLE
Drop pretty-num for pure javascript

### ISSUE THREAD

**Issue by JeremieLeblanc** [chakra-ui/chakra-ui#303]
From what I can tell, the only place using pretty-num is in the useNumberInput/utils.js roundToPrecision function.

The setting used in the prettyNum function is PRECISION_SETTING.FIXED (set precision to specified number of decimal digits, pad with ending zeros if needed)

I believe we can achieve this functionality with simple javascript like this:
`return parseFloat(value).toFixed(precision);`

If there's another reason for using pretty-num in future versions, that's fine, but I think we should remove the dependency if not.

I can make a PR if needed.

**Comment by segunadebayo** [comment]
I agree. I've removed `pretty-num` in the dev-ts branch in favor of pure javascript.

Feel free to make a PR.
