### ISSUE TITLE
Feature request: column-count

### ISSUE THREAD

**Issue by pfcodes** [chakra-ui/chakra-ui#3039]
# 🚀 Feature request

Requesting the `column-count` property be added.

## 🧱 Problem Statement / Justification

`column-count` has [95.9%](https://caniuse.com/?search=column-width) browser support and works on IE10+.

## ✅ Proposed solution or API

```
<List columnCount={[1, 2]}>
  {[1,2,3,4,5,6,7,8].map((listItem, index) => (
    <ListItem key={index}>
      {listItem}
    </ListItem>
  ))}
</List>
```

## ↩️ Alternatives

Right now I'm using it with the `css` prop. But it's not easily made responsive this way.
```
<List css={'column-count: 2'}>
  {[1,2,3,4,5,6,7,8].map((listItem, index) => (
    <ListItem key={index}>
      {listItem}
    </ListItem>
  ))}
</List>
```

## 📝 Additional Information

https://developer.mozilla.org/en-US/docs/Web/CSS/column-count
https://caniuse.com/?search=column-count

**Comment by segunadebayo** [comment]
Thanks for the request! Considering this isn't a bug, I'll add this to our project board so you can track the progress.

Check it here: https://github.com/chakra-ui/chakra-ui/projects/6

Cheers.

**Comment by bertho-zero** [comment]
Still no `columnCount` :'(

**Comment by Young-Einstein10** [comment]
For now, using the `sx` property works fine. Also for responsivity too.
```
<List sx={{ columnCount: [1, 2] }}>
  {[1,2,3,4,5,6,7,8].map((listItem, index) => (
    <ListItem key={index}>
      {listItem}
    </ListItem>
  ))}
</List>
```
