### ISSUE TITLE
[POPOVER] Z-index to main div popovoer

### ISSUE THREAD

**Issue by max10rogerio** [chakra-ui/chakra-ui#3043]
# 🐛 Bug report

Popover component have a problem when any component use a different z-index

Search component ("O que vc procura?") use z-index 1 and select component ("UF") use popover with portal 
![image](https://user-images.githubusercontent.com/21085292/104466483-0d348a80-5594-11eb-9506-27b5dce1c89b.png)

![image](https://user-images.githubusercontent.com/21085292/104465675-0eb18300-5593-11eb-84e9-512e62311af7.png)

## 🧐 Expected behavior

Popover box on top of search component 

## 🧭 Possible Solution

Possibility pass css style to main div of popover

See `z-index: 2;`, I add manually in dom chrome
![image](https://user-images.githubusercontent.com/21085292/104467978-add77a00-5595-11eb-98bb-84c1a7d80fe3.png)

![image](https://user-images.githubusercontent.com/21085292/104468085-d19ac000-5595-11eb-8034-3dae27eb37dd.png)

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       ^1.0.1     |
| Browser          |    Chrome        |
| Operating System |       Ubuntu 20.04     |

## 📝 Additional information

- Screenshots or code
- Notes or link to ideas

**Comment by jsbroks** [comment]
@max10rogerio How did you fix this?

**Comment by max10rogerio** [comment]
I think this problem is solved by adding more zindex before PopoverContent

![image](https://user-images.githubusercontent.com/21085292/108056703-5f077f00-7030-11eb-9688-8a2ed45673ca.png)

**Comment by zevictordantas** [comment]
> I think this problem is solved by adding more zindex before PopoverContent
> 
> ![image](https://user-images.githubusercontent.com/21085292/108056703-5f077f00-7030-11eb-9688-8a2ed45673ca.png)

Thanks! This also worked for me.

**Comment by aysommer** [comment]
My solution works for me with for MenuList, thanks:
![image](https://user-images.githubusercontent.com/23564468/115256631-122b4c00-a138-11eb-869b-49c19131be86.png)

**Comment by munj1** [comment]
Thank you so much!
It works for me too

**Comment by Abcold** [comment]
> My solution works for me with for MenuList, thanks: ![image](https://user-images.githubusercontent.com/23564468/115256631-122b4c00-a138-11eb-869b-49c19131be86.png)

its work for me thanks!!!

**Comment by daviFrag** [comment]
> I think this problem is solved by adding more zindex before PopoverContent
> 
> ![image](https://user-images.githubusercontent.com/21085292/108056703-5f077f00-7030-11eb-9688-8a2ed45673ca.png)

The solution currently doesn't work because the Box component is set to a static position ad so the browser doesn't set the z-index

if i change it to relative it works fine 

`<Box zIndex="popover" w="full" h="full" position={'relative'}>`

I hope i can help someone :)

**Comment by keithburgie** [comment]
@daviFrag you helped me! That's so much! In my use case all I needed was position="relative" along with the zIndex.

**Comment by talksik** [comment]
Thank you! @aysommer ! The portal did it for me!

**Comment by Rafael-Ramblas** [comment]
@daviFrag Thank you so much for this

**Comment by coderbahrom** [comment]
### I have zIndex issue i read above did What the said But not luck plz help me


``<Box>
      <Popover
        placement="bottom-start"
        isOpen={open}
        onOpen={() => setOpen(true)}
        onClose={() => setOpen(false)}
        zIndex="popover"
      >
        <PopoverTrigger>
          <Button
            border="1px solid"
            borderColor="colors.sidebarBorder"
            p="6"
            colorScheme="gray"
            variant="ghost"
            fontSize="13px"
            color="colors.icon"
            position="relative"
            // minW="250px"
            rightIcon={<img src={CalendarIcon} alt="calendar" />}
          >
            {` ${
              startDate
                ? lightFormat(startDate, "dd.MM.yyyy")
                : t("not_selected")
            }
          - ${
            endDate ? lightFormat(endDate, "dd.MM.yyyy") : t("not_selected")
          }`}
            {(startDate || endDate) && deletable && (
              <Image
                src={DeleteIcon}
                alt="delete"
                width="15px"
                position="absolute"
                top="2px"
                right="2px"
                borderRadius="50%"
                onClick={deleteHandler}
              />
            )}
          </Button>
        </PopoverTrigger>
        <PopoverContent width="550px">
          <DatePicker
            ranges={ranges}
            onChange={onChange}
            locale={getTranslatedLocale(t)}
            theme={{
              // Custom styles for dark mode
              backgroundColor: "#222",
              calendarTextColor: "#fff",
              textColor: "#fff",
              selectionColor: "#444",
              headerColor: "#111",
              borderColor: "#333",
            }}
          />
        </PopoverContent>
      </Popover>
    </Box>

**Comment by daviFrag** [comment]
> 

Try position relative as my comment

**Comment by coderbahrom** [comment]
@daviFrag I did it but it effects other things  should I add relative here ;"<Popover
placement="bottom-start"
isOpen={open}
onOpen={() => setOpen(true)}
onClose={() => setOpen(false)}
zIndex="popover"
>"
