### ISSUE TITLE
[Popover] Custom style in main div

### ISSUE THREAD

**Issue by max10rogerio** [chakra-ui/chakra-ui#3044]
# 🐛 Bug report

Popover component has a problem when any component uses a different z-index

e. g.: this SearchBar component ("O que vc procura?") uses z-index 1 and select component ("UF") uses popover with portal tag

![image](https://user-images.githubusercontent.com/21085292/104466483-0d348a80-5594-11eb-9506-27b5dce1c89b.png)

![image](https://user-images.githubusercontent.com/21085292/104465675-0eb18300-5593-11eb-84e9-512e62311af7.png)

## 🧐 Expected behavior

Popover box on top of search component 

## 🧭 Possible Solution

Possibility pass css style to main div of popover

See `z-index: 2;`, I add manually in dom chrome
![image](https://user-images.githubusercontent.com/21085292/104467978-add77a00-5595-11eb-98bb-84c1a7d80fe3.png)

![image](https://user-images.githubusercontent.com/21085292/104468085-d19ac000-5595-11eb-8034-3dae27eb37dd.png)

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       ^1.0.1     |
| Browser          |    Chrome        |
| Operating System |       Ubuntu 20.04     |

## 📝 Additional information

- Screenshots or code
- Notes or link to ideas

**Comment by PabloSzx** [comment]
any workaround to make this possible with the current version?

**Comment by with-heart** [comment]
If one of you could reproduce this issue in a CodeSandbox, that would be awesome.

**Comment by PabloSzx** [comment]
codesandbox: https://codesandbox.io/s/popover-content-props-kd4eu

[In the code you can see](https://github.com/chakra-ui/chakra-ui/blob/main/packages/popover/src/popover.tsx#L133) that the popover content has a parent chakra.div that is not possible to specify props / style to, I had to manually patch locally chakra-ui to fix this issue in one of my projects

**Comment by PabloSzx** [comment]
> Hi!
> This issue hasn't seen any activity recently. We close inactive issues after 35 days to manage the volume of issues we receive.
> If we missed this issue or you want to keep it open, please reply here. That will reset the timer and allow more time for this issue to be addressed before it is closed.

bump

**Comment by PabloSzx** [comment]
bump

**Comment by PabloSzx** [comment]
> Hi!
> This issue hasn't seen any activity recently. We close inactive issues after 35 days to manage the volume of issues we receive.
> If we missed this issue or you want to keep it open, please reply here. That will reset the timer and allow more time for this issue to be addressed before it is closed.

bump

**Comment by Apiyo4** [comment]
I'm experiencing the same issue in 1.0.3

**Comment by PabloSzx** [comment]
@with-heart I updated the codesandbox https://codesandbox.io/s/popover-content-props-kd4eu dependencies to the latest and the error the issue is still there, shouldn't at least the label "needs reproduction" be removed?

**Comment by segunadebayo** [comment]
Hi @max10rogerio, you can use the `rootProps` to pass props to the popover content's container.
