### ISSUE TITLE
Allow wrapping `TabPanel` components

### ISSUE THREAD

**Issue by tomdohnal** [chakra-ui/chakra-ui#3045]
# 🚀 Feature request

## 🧱 Problem Statement / Justification

I'm using the `Tabs` components. If I want to wrap the `TabPanel` components in another component, the `Tabs` components break.

```javascript
// Does not work
<Tabs>
  <TabList>
      <Tab>FIrst Tab</Tab>
      <Tab>Second Tab</Tab>
      <Tab>Third Tab</Tab>
  </TabList>
  <TabPanels>
      <div>
          <TabPanel>Tab panel 1</TabPanel>
      </div>
      <div>
          <TabPanel>Tab panel 2</TabPanel>
      </div>
      <div>
          <TabPanel>Tab panel 3</TabPanel>
      </div>
  </TabPanels>
</Tabs>
```

Interestingly, wrapping `Tab` components in custom components works just fine:

```javascript
// Works just fine
<Tabs>
  <TabList>
    <div>
      <Tab>FIrst Tab</Tab>
    </div>
    <div>
      <Tab>Second Tab</Tab>
    </div>
    <div>
      <Tab>Third Tab</Tab>
    </div>
  </TabList>
  <TabPanels>
    <TabPanel>Tab panel 1</TabPanel>
    <TabPanel>Tab panel 2</TabPanel>
    <TabPanel>Tab panel 3</TabPanel>
  </TabPanels>
</Tabs>
```

## ✅ Proposed solution or API

The proposed solution is to remove the coupling between `TabPanels` and `TabPanel` components and don't require the `TabPanel` component to be a direct child of the `TabPanels` components.

I've looked at the source code and figured out that while the `TabList` and `Tab` components use the "descendant context" to get the index in the `Tab` component, the `TabPanels` and `TabPanel` components use `React.Children.map` and `React.cloneElement` to pass the index onto the `TabPanel` component. 

I believe that the issue could be solved by using the "descendant context" for the `TabPanels` and `TabPanel` components as well....

## ↩️ Alternatives

An alternative is to leave the necessity of `TabPanel` being a direct child of `TabPanels` as it is now.

## 📝 Additional Information

I could send a PR with the proposed changes if you're interested in implementing this feature request.

**Comment by dodas** [comment]
Can you post your use case?

**Comment by tomdohnal** [comment]
Generally creating custom `TabPanel` components does not work with this approach:

```javascript

function FancyTabPanel({ children }) {
  return (
    <TabPanel>
      <Heading>This is a fancy tab panel</Heading>
      {children}
    </TabPanel>
  );
}

function App() {
  return (
    <Tabs>
      <TabList>
        <Tab>FIrst Tab</Tab>
        <Tab>Second Tab</Tab>
        <Tab>Third Tab</Tab>
      </TabList>
      <TabPanels>
        <FancyTabPanel>Tab panel 1</FancyTabPanel>
        <FancyTabPanel>Tab panel 2</FancyTabPanel>
        <FancyTabPanel>Tab panel 3</FancyTabPanel>
      </TabPanels>
    </Tabs>
  );
}
```

(full code on https://codesandbox.io/s/bold-resonance-7s2bx?file=/src/index.tsx)

You could actually solve this by passing on the props in the `FancyTabPanel` onto the `TabPanel` component like this:
```javascript
function FancyTabPanel({ children, ...props }) {
  return (
    <TabPanel {...props}>
      <Heading>This is a fancy tab panel</Heading>
      {children}
    </TabPanel>
  );
}
```

But IMHO that's too much coupling to how the things are wired up in Chakra UI under the hood...

**Comment by simontaisne** [comment]
Same thing with the `Breadcrumb` & `BreadcrumbItem` components.

**Comment by tomdohnal** [comment]
I still believe this could be both useful and quite straightforward to implement (happy to help with it myself) 🙂

**Comment by NileDaley** [comment]
This issue also makes the code a bit more verbose to conditionally render `TabPanel` components

```jsx
function App({ showExtraTabs }) {
  return (
    <Tabs>
      <TabList>
        <Tab>First Tab</Tab>        
        {showExtraTabs && (
          {/* This works */}
          <>
            <Tab>Second Tab</Tab>
            <Tab>Third Tab</Tab>
          </>
        )}
      </TabList>
      <TabPanels>
        <TabPanel>Tab panel 1</TabPanel>
        {/* You can't use fragments here, so have to conditionally render each panel individually */}
        {showExtraTabs && <TabPanel>Tab panel 2</TabPanel>}
        {showExtraTabs && <TabPanel>Tab panel 3</TabPanel>}
      </TabPanels>
    </Tabs>
  );
}
```

**Comment by tomdohnal** [comment]
@segunadebayo Would you accept a PR with a solution outlined in the issue?

> The proposed solution is to remove the coupling between TabPanels and TabPanel components and don't require the TabPanel component to be a direct child of the TabPanels components.
> I've looked at the source code and figured out that while the TabList and Tab components use the "descendant context" to get the index in the Tab component, the TabPanels and TabPanel components use React.Children.map and React.cloneElement to pass the index onto the TabPanel component.
> 
> I believe that the issue could be solved by using the "descendant context" for the TabPanels and TabPanel components as well....

**Comment by with-heart** [comment]
We discussed this issue in our team meeting yesterday and we came up with some changes we'd like to make for `2.0`. Check out #4062 for more info.

In the meantime, I think we'd accept a PR to implement descendant context to break the `props`-based coupling. Context has become our preferred pattern but we haven't had a chance to refactor everything to use it, so this would be a great step forward.

**Comment by Creator674** [comment]
We still need that feature. 🥺

**Comment by ivan-kleshnin** [comment]
The issue implies both `TabPanel` and `Tab` component are kinda useless as you can replace them with custom tags.
Tabs API indeed feels bloated – in MUI you can have just `Tabs` and `Tab` and I'd personally prefer namespacing like `Tabs.Xxx`.
