### ISSUE TITLE
Request: allow using components other than div for transitions

### ISSUE THREAD

**Issue by codetheweb** [chakra-ui/chakra-ui#3051]
# 🚀 Feature request

I want to animate the addition of a row to a table. However, the Collapse animation doesn't really work properly because it (and all other animations) have a hard-coded `<motion.div/>` component: https://github.com/chakra-ui/chakra-ui/blob/9ca61eca9a8be06cef650341b33603d429a9b66b/packages/transition/src/collapse.tsx#L146

## ✅ Proposed solution or API

Ideally, there would be a prop that allows a custom component to be passed in (I want to use `<motion.tr/>`).

**Comment by codetheweb** [comment]
Still relevant.

**Comment by lucasmaffazioli** [comment]
I have the same issue as the OP, enabling to set a <Collapse as={TR}> would really help!

**Comment by MatthewCushing** [comment]
I'm with the OP on this one as well.  Spent way too long trying to figure out how to get Accordion working with table rows, finally giving up, and moving on to the Collapse component only to find out that the Collapse component is the problem and is the reason Accordion won't work as well as it renders a div as a sibling to the AccordionItem.

**Comment by amysak** [comment]
bump. would appreciate this feature as well for the same reasons described in the comments above. this would solve an issue with table row expanded state toggles.

**Comment by ahmadxgani** [comment]
Hi @codetheweb! have you find any workaround solution for this issue?

**Comment by victoria-martin** [comment]
same need here
