### ISSUE TITLE
Deprecate `gatsby-plugin-chakra-ui`

### ISSUE THREAD

**Issue by LekoArts** [chakra-ui/chakra-ui#3052]
# 🚀 Request

Please deprecate the `gatsby-plugin-chakra-ui` package on npm and add a notice at the beginning of the README that `@chakra-ui/gatsby-plugin` should be used instead.

## 🧱 Problem Statement / Justification

https://github.com/gatsbyjs/gatsby/issues/29017 made me aware of the fact that the old plugin isn't deprecated with a note in the README yet. This confuses our users as we currently simply list out all plugins that have `gatsby-plugin` tag in their package.json file and thus the old package is also shown.

Thanks!

**Comment by LekoArts** [comment]
@with-heart ^

**Comment by LekoArts** [comment]
.

**Comment by with-heart** [comment]
Sorry about that @LekoArts. Always way too many things and not enough focus to deal with them 🙃 

I've deprecated this on `npm` and added a note at the top of the `README.md` file to upgrade Chakra to v1, to use `@chakra-ui/gatsby-plugin`, and to visit our site for more information.

I don't see the official Chakra version of `gatsby-plugin-chakra-ui` showing up in the plugins list anymore, so I think this was successful. Let me know if there's anything else I need to do though!
