### ISSUE TITLE
`gridTemplate` is not supported?

### ISSUE THREAD

**Issue by ianstormtaylor** [chakra-ui/chakra-ui#3058]
### 🐛 Bug report

The [`grid-template`](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template) CSS property is not supported as a `gridTemplate` prop.

**Comment by dodas** [comment]
Hi @ianstormtaylor.

There are a few css properties that can't be used directly as a prop.
I don't think we will try to implement all css properties.

In those cases, you can use the `sx` property:
```ts
<Box sx={{ gridTemplate: "100px 1fr / 50px 1fr" }}
```

The `sx` property will be documented soon.

Hope that helps. Cheers!

**Comment by ianstormtaylor** [comment]
@dodas @segunadebayo @with-heart I've seen this response to a handful of different "where is the X prop?" questions. I'd encourage you to re-think this policy, it's extremely confusing and frustrating as an end user.

The existing API encourages thinking of props mapping directly to CSS properties, but then it omits props seemingly at random, so you can never know which ones are supported at which aren't...

```ts
// supported
gripColumnGap
gridTemplateRows
flexDirection
borderColor
borderStyle

// unsupported
columnGap
gridTemplate
flexFlow
borderImage
clipPath
```

There doesn't seem to be any reasoning behind which props get supported and which don't…

So whenever you try to set one of these props you run into weird errors and have to realize that Chakra doesn't recognize it. Then you have to use both the existing props that do work _and_ the `cx` prop to achieve what you were doing, which just complicates the library's usage even further.

**Comment by segunadebayo** [comment]
@ianstormtaylor, thanks for sharing your thoughts.

- I wouldn't say that some props are "omitted at random" which could imply we intentionally omit them. We do our best to ensure only commonly used props are available as style props to reduce the API surface. We could possibly skip some in error and it's okay to request for a style prop to be added (in the event we missed it)

-  If you check how we manage the style props, you'll see that supporting all CSS properties will lead to a bundle size bloat we can avoid. That's not to say we can't consider adding a specific style prop.

- Using only the `sx` prop to manage styles is definitely the best way to go if you want all CSS properties exposed to you. For style props, we won't be supporting all CSS properties.

That said, I'll review all the style props one more time and add any missing props based on this feedback.

 Thank you.

**Comment by segunadebayo** [comment]
I've added support for the missing grid props and flex-flow.

**Comment by ianstormtaylor** [comment]
@segunadebayo thanks for adding the missing props! Is the `sx` prop documented anywhere? I could only find a few places in the docs that use it, but never an explanation of what the prop does exactly.

---

I understand about limiting the bundle size, that is a good goal. But from experience I don't think the tradeoffs Chakra is making are the right ones—using the library right now feels very haphazard and like there isn't an overarching thought process to how API decisions are made. I wrote up some thoughts along this line in https://github.com/chakra-ui/chakra-ui/issues/2821 as well.
