### ISSUE TITLE
StatNumber missing StyleProvider

### ISSUE THREAD

**Issue by marcebdev** [chakra-ui/chakra-ui#3073]
# 🐛 Bug report

> StatNumber seems to be missing an import and/or the `<StyleProvider />` wrapper causing it to not be properly usable.

## 💥 Steps to reproduce

Seems that just trying to render a `<StatNumber />` causes this I don't see anything else this can be attributed to.

## 💻 Link to reproduction

I can add one if needed but seems just like a minor mistake that's reproducible anywhere so I will omit further sections and show the error

## 📝 Additional information

```
Error: useStyles: `styles` is undefined. Seems you forgot to wrap the components in `<StylesProvider />` 
This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

**Comment by segunadebayo** [comment]
Hi @marcebdev, to use the `StatNumber` component, kindly wrap it within the `Stat` component. This is because `Stat` provides the theming context for the `StatNumber` component

```
<Stat>
  <StatNumber>£0.00</StatNumber>
</Stat>
```
