### ISSUE TITLE
[Feature] Add writingMode style prop to typography

### ISSUE THREAD

**Issue by DecliningLotus** [chakra-ui/chakra-ui#3083]
# 🚀 Feature request

Add writingMode styling props for typography.

## 🧱 Problem Statement / Justification

It allows for text-orientations to be changed in a vertical context. This can be particularly nice for certain niche design choices, but also very useful for languages like Mandarin or Japanese which can present their language in vertical script.

## ✅ Proposed solution or API

Simple mirror from the actual CSS syntax?

e.g. `<Text writingMode="vertical-rl">Example text.</Text>` or `<Heading writingMode="vertical-lr">Example header.</Heading>`

## ↩️ Alternatives

I currently just add a custom CSS class for my particular usecase, but I see no issue for this to be integrated into Chakra UI. It's an added little bonus.

## 📝 Additional Information

More on the CSS prop here: https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode

**Comment by dodas** [comment]
Hey @DecliningLotus 
Please read the issue #3058 to find better solution as well as some details about what style props are implemented.
I think `writing-mode` is not common enough to be added as a style prop, but please express yourself if you feel otherwise.

**Comment by DecliningLotus** [comment]
I think it depends on how large the bundle size changes are. It's a fairly important i18n feature for Asian languages mainly, which might be in the interest of Chakra's roadmap.

It has been gaining use for reference: https://2020.stateofcss.com/en-US/features/layout/writing_modes

**Comment by segunadebayo** [comment]
Hi @DecliningLotus, just like @dodas mentioned, you can either use the `sx`, or native `style` prop for this use-case, or create a global style for this writing mode using the `<Global/>` component from emotion.

Hope this helps.
