### ISSUE TITLE
Menu component - type radio (boolean)

### ISSUE THREAD

**Issue by zaferkadi** [chakra-ui/chakra-ui#3086]
# 🐛 Bug report

Currently I'm trying to maintain and feed the Menu component with MenuOptionGroup of type Radio, but it seems there is a bug concerning having an array of objects with values of boolean

## 💥 Steps to reproduce

Clicking on the Menu of type radio, select a menu item, selected item is persisted and changeable.

## 💻 Link to reproduction

> Please create a minimal reproduction in CodeSandbox
>
> - JavaScript Template:
>   [JavaScript CodeSandbox template](https://codesandbox.io/s/adoring-grass-qgx3c?file=/src/app.js)
>

## 🧐 Expected behavior

Menu component to function as the docs state.
OnChange to be called once a menuitem is changed.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.1.5           |
| Browser          | Chrome Version 87.0.4280.141           |
| Operating System |     mac os Catalina       |

**Comment by tomdohnal** [comment]
I don't think this is a bug. The docs (https://chakra-ui.com/docs/overlay/menu#menuitemoption-props) state that the `value` prop you pass to the `MenuItemOption` component must be of type `string`.

**Comment by zaferkadi** [comment]
@tomdohnal You are correct, I think I tried to do more than what Menu component was made for, my guess that it only accepts strings because of accessibility purposes but I could be wrong.
Any suggestions on how to handle such case by still utilizing the Menu component with booleans without?

**Comment by tomdohnal** [comment]
You can use `"true"` and `"false"` as strings I guess. Not the most beautiful thing in the world but it does the job.
(see https://codesandbox.io/s/still-glitter-nibk9?file=/src/app.js)

**Comment by zaferkadi** [comment]
@tomdohnal I tried that, but I was aiming to have a reusable Menu component, and yes it's not pretty.
But thank you, I'll close this now.
