### ISSUE TITLE
Tooltip missplacement with smooth container animation

### ISSUE THREAD

**Issue by Dmytro-Epam** [chakra-ui/chakra-ui#3089]
When Tooltip is in container which has smooth animation with changing container's size and affects Tooltip trigger position and in the same moment Tooltip is shown, Tooltip doesn't recalculate it's position and stays at an old place, when trigger moves away.

In sandbox set focus on red figure then press Tab 2 times 
https://codesandbox.io/s/chakra-tooltip-missplacement-bx9wi

**Comment by segunadebayo** [comment]
Hi @Dmytro-Epam, I think this is quite difficult to manage and technically not feasible in `popper.js`.

`popper.js` recalculates the position when the reference changes size, gets close to the viewport and you scroll the page. It doesn't consider when the reference moves.

I have 2 recommendations:
- You can consider writing your own modifier that checks when the reference moves and recomputes the styles based on the position of the reference: https://popper.js.org/docs/v2/modifiers/community-modifiers/. Then pass that modifier to the `Tooltip` component.

- You can co-ordinate the timing of showing the tooltip, wait till the width transition is done, then show the tooltip. Here's a quick example

```jsx
export const RecalculatesPosition = () => {
  const [isFocused, setIsFocused] = React.useState(false)
  const [isOpen, setIsOpen] = React.useState(isFocused)

  const handleFocus = () => {
    setIsFocused(true)
  }
  const handleBlur = () => {
    setIsOpen(false)
    setIsFocused(false)
  }
  return (
    <div
      onTransitionEnd={() => {
        if (isFocused) {
          setIsOpen(true)
        }
      }}
      style={{
        width: isFocused ? 400 : 500,
        height: 200,
        transition: "width 0.3s ease",
        background: "red",
        position: "relative",
      }}
    >
      <p>{isFocused ? "pressed" : "not pressed"}</p>
      <div style={{ position: "absolute", top: "50%", right: "100px" }}>
        <Tooltip
          isOpen={isOpen}
          p="5px"
          background="white"
          shouldWrapChildren
          label="Bottom"
          placement="bottom"
        >
          <button onFocus={handleFocus} onBlur={handleBlur}>
            Bottom
          </button>
        </Tooltip>
      </div>
    </div>
  )
}
```

Hope you find this helpful.
