### ISSUE TITLE
[Menu] Entire App crashes if no MenuItems exist

### ISSUE THREAD

**Issue by iRoachie** [chakra-ui/chakra-ui#310]
**Describe the bug**
When selecting the Menu and no items are rendered, the entire app crashes

![Screenshot 2019-12-26 at 2 52 26 PM](https://user-images.githubusercontent.com/5962998/71487050-8c231d80-27ef-11ea-88d4-edf9e7cc4620.png)
![Screenshot 2019-12-26 at 2 53 03 PM](https://user-images.githubusercontent.com/5962998/71487051-8dece100-27ef-11ea-92b9-7e6ce51d7812.png)

**Expected Behavior**
Dropdown should not open (since no items) and **definitely not crash the app**

**To Reproduce**
https://codesandbox.io/s/great-volhard-ozr5l

**Suggested solution(s)**
- Don't open the menu when no menu items are present
- Check before focusing to see if the element exist (this is where the error throws) https://github.com/chakra-ui/chakra-ui/blob/14b0ad5fb5c821032168793406d5a0c2c3cfc849/packages/chakra-ui/src/Menu/index.js#L91

I can make the PR, let me know which way is best

**Desktop (please complete the following information):**
 - OS - MacOS Catalina
 - Browser - Chrome
 - Version ("@chakra-ui/core": "^0.5.2")

**Additional context**
Usually the MenuList component would have children (MenuItem), in the event where the list is populated by data from an api and the server is down, the app should still work, with data that is stored locally. In the example below, the menu is usually populated with a list of schools to choose from, however since the server is down, the list would be empty.

```jsx
<MenuList placement="bottom-start">
  {schools.map(a => (
    <MenuItem
      fontSize="sm"
      key={a.id}
      onClick={() => selectSchool(a.id)}
    >
      {a.name}
    </MenuItem>
  ))}
</MenuList>
```

![Kapture 2019-12-26 at 14 57 02](https://user-images.githubusercontent.com/5962998/71487119-005dc100-27f0-11ea-98b5-29c22ef40d81.gif)

**Comment by segunadebayo** [comment]
Hi @iRoachie. Feel free to submit a PR for this issue.

Thanks for using Chakra UI

**Comment by iRoachie** [comment]
The first one I can do easily. For the second one, do you have any idea how we might check if there's any MenuItem's?

**Comment by segunadebayo** [comment]
Hi @iRoachie, I've just fixed this bug. Ideally, you might want to render the MenuList if `schools` array is empty. 

I'll release a patch shortly for this.

**Comment by iRoachie** [comment]
Thanks, that’s what I ended up doing
