### ISSUE TITLE
TypeError: (0 , _system.useMultiStyleConfig) is not a function

### ISSUE THREAD

**Issue by Fractured2K** [chakra-ui/chakra-ui#3100]
Just finished a migration to v1, ran `next dev` and received the following error.

![d599606568f0873b25220f19a774aced](https://user-images.githubusercontent.com/32372095/105092330-ef649b00-5a55-11eb-9244-7050c7effd3f.png)

Tried researching and couldn't find anything elsewhere. Anyone have any ideas?

```
"@chakra-ui/icons": "^1.0.3",
"@chakra-ui/layout": "^1.0.0-next.3",
"@chakra-ui/react": "^1.1.5",
"@chakra-ui/skeleton": "^1.0.0-next.3",
"@emotion/react": "^11.1.4",
"@emotion/styled": "^11.0.0",
"framer-motion": "^3.2.1",
"react": "^17.0.1",
```

**Comment by with-heart** [comment]
How are you using `ChakraProvider`? 

Also I don't think this is the cause exactly but versions of Chakra packages should always match, and you shouldn't need `@chakra-ui/layout` or `@chakra-ui/skeleton` as their contents are exported from `@chakra-ui/react`.

**Comment by Fractured2K** [comment]
Ah! That was it. Removing `@chakra-ui/layout`,`@chakra-ui/skeleton` and deleting `node_modules` finally threw a new error letting us know we were missing `@chakra-ui/system`. Thanks for the help! 🙇
