### ISSUE TITLE
extendTheme's return type is any

### ISSUE THREAD

**Issue by nvsd** [chakra-ui/chakra-ui#3101]
# 🐛 Bug report

> Provide a brief description of the bug here

It seems that at some point `extendTheme`'s return type became `any`.

## 💥 Steps to reproduce

> Clear and concise reproduction steps are important for us to be able to triage
> your issue in a timely manner

1. Attempt to extend theme
  ```ts
  const colors = {
  brand: {
    100: "#ffffff",
    200: "#ededed"
  }
};

const extendedTheme = extendTheme({ colors });
```
2. observe type of extendedTheme variable in editor is `any`

## 💻 Link to reproduction
[Minimial repro](https://codesandbox.io/s/charming-browser-oyrpz?file=/src/App.tsx:104-225)

## 🧐 Expected behavior

> Tell us what you expect to happen.

A return type that reflects the extended theme.

This is the code that was working at some point.
```ts
import { extendTheme, useTheme } from '@chakra-ui/react';

export const theme = extendTheme(overrides, baseTheme);
export type AppTheme = typeof theme;

const theme = useTheme<AppTheme>();
```

## 🌍 System information

| Software         | Version(s) |
| ------------------ | ------------ |
| Chakra UI              | >1.0.4             |

## 📝 Additional information

<img width="493" alt="image" src="https://user-images.githubusercontent.com/7391612/105094035-445ddc80-5a69-11eb-837a-7fd075494499.png">

I'm not sure if something changed with the api and I just missed it.
Let me know if I can help in any other way.

Thanks for all of the hard work and the great library!

**Comment by Slmii** [comment]
same issue here. is there an older version where it works?

**Comment by nvsd** [comment]
My TS isn't the best but I'm wondering if the return type is being inferred as `any` due to [this change](https://github.com/chakra-ui/chakra-ui/pull/2783/files).

**Comment by nvsd** [comment]
> same issue here. is there an older version where it works?

Looks like 1.0.4 is working fine

**Comment by Slmii** [comment]
>Looks like 1.0.4 is working fine

Yes, can confirm. Hope it will return to the latest version as well

**Comment by TimKolberger** [comment]
[The introduction of an arbitrary base theme](https://github.com/chakra-ui/chakra-ui/pull/2834/files) lead to the return type any. 

Next step would be to define a generic `ChakraTheme` type and not to derive the Theme type from the default theme.
I am thinking of something like 

```ts
type ChakraTheme = ToBeDefined

function extendTheme(override: DeepPartial<ChakraTheme>, baseTheme: ChakraTheme): ChakraTheme
```
