### ISSUE TITLE
Sticky Position Element

### ISSUE THREAD

**Issue by tobiasjayas** [chakra-ui/chakra-ui#3117]
Can i use position style props like this?
`<Tabs align="start" variant="line">
            <TabList position="sticky>
              <Tab>One</Tab>
              <Tab>Two</Tab>
              <Tab>Three</Tab>
            </TabList>`

**Comment by segunadebayo** [comment]
Yes, you can.

**Comment by tobiasjayas** [comment]
why the sticky didn't work? @segunadebayo

**Comment by with-heart** [comment]
@tobiasjayas Please fill out the issue template provided when opening an issue. Deleting it is not appropriate.
