### ISSUE TITLE
Ability to create variants that extend other variants

### ISSUE THREAD

**Issue by ChasinHues** [chakra-ui/chakra-ui#3118]
# 🚀 Feature request

It would be handy in some situations to be able to create variants that extend existing variants.

## 🧱 Problem Statement / Justification

See https://github.com/chakra-ui/chakra-ui/discussions/2974 - dev needs to create a `Button` variant that is very similar to the existing `outline` variant, but still needs the outline variant. In this case, they'll have to basically build the variant from scratch. Being able to extend the `outline` variant and override the styles desired would be a handy feature.

Example of an attempt at trying to do this: https://codesandbox.io/s/extend-variants-demo-0nhtc?file=/src/App.tsx
Note that the `thickOutline` variant does not bring across all of the styles that the `outline` variant has.

## ✅ Proposed solution or API

Maybe a function that gets styles associated with a given variant?
```jsx
const customTheme = extendTheme({
  components: {
    Button: {
      variants: {
        thickOutline: (props) => ({
          ...extendVariant('outline', props),
          borderWidth: "4px",
          borderColor: `${props.colorScheme}.800`
        })
      }
    }
  }
});
```

## ↩️ Alternatives

https://codesandbox.io/s/extend-variants-demo-0nhtc?file=/src/App.tsx
```jsx
import { extendTheme, theme } from "@chakra-ui/react";

const customTheme = extendTheme({
  components: {
    Button: {
      variants: {
        thickOutline: (props) => ({
          ...theme.components.Button.variants.outline,
          borderWidth: "4px",
          borderColor: `${props.colorScheme}.800`
        })
      }
    }
  }
});

export default customTheme;
```

**Comment by segunadebayo** [comment]
Thanks for the request! Considering this isn't a bug, I'll add this to our project board so you can track the progress.

Check it here: https://github.com/chakra-ui/chakra-ui/projects/6

Cheers.

**Comment by dodas** [comment]
Possible solution: https://github.com/chakra-ui/chakra-ui/discussions/2974#discussioncomment-379564

**Comment by giovdk21** [comment]
thanks @segunadebayo ; I can't find this in the roadmap anymore,  could you please confirm the current status / solution?

**Comment by elboletaire** [comment]
> thanks @segunadebayo ; I can't find this in the roadmap anymore, could you please confirm the current status / solution?

Looks like they moved it to "No commitment" just a few months after the issue was added to the Roadmap, based on what the log says here in github.

I'm currently trying to make custom components using the theming system from chakra, and not being able to easily extend chakra's styles is a bit annoying.

Any update on this @segunadebayo?
