### ISSUE TITLE
Add ability to customise InputLeftElement and InputRightElement in the theme

### ISSUE THREAD

**Issue by ChasinHues** [chakra-ui/chakra-ui#3119]
# 🚀 Feature request

## 🧱 Problem Statement / Justification

Currently you can't customise `InputLeftElement` and `InputRightElement` in the theme. 

The `baseStyles` for these components are [defined in their component sub repo package](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/input/src/input-element.tsx) and aren't available for customisation through the theme.

## ✅ Proposed solution or API

Expose another part (or parts) to the `Input` component in the theme.

```jsx
const parts = ["field", "addon"]
```
becomes
```jsx
const parts = ["field", "addon", "element"] // or "leftElement" and "rightElement"
```

**Comment by segunadebayo** [comment]
I see where this is going but we need to avoid theming every component. I think the input left and the right element is a very dynamic element that should be styled based on use-case.

I'd suggest we hold this off for now. I'll add it to the project board though

Check it here: https://github.com/chakra-ui/chakra-ui/projects/6

Cheers.

**Comment by topaxi** [comment]
Our design team would also like to have the input elements be styled based on focus within the input element. I haven't yet figured out a nice way to do that though :thinking:

**Comment by GunB** [comment]
Hello. My team is also interested in this feature, exactly what @topaxi suggests. I had a lot of hope as I saw Element in the anatomy of input to just run in circles for hours and finally arrive here and know is not possible. I would really appreciate this feature.

**Comment by bkiac** [comment]
It seems like the `element` is in the `parts` array now but I can't add any styles to it.

![image](https://user-images.githubusercontent.com/24522620/155325118-399fa8d3-0d6e-4395-965c-ec793b327597.png)

**Comment by edtech1985** [comment]
Hey Guys, 
I'm trying to set a custom color ofr InputLeftElement on Chakra-UI theme file but I think I'm doing something wrong. Can you help me?

![image](https://github.com/chakra-ui/chakra-ui/assets/98822745/1d3c95ce-4061-4592-b528-194cee84761b)

**Comment by edtech1985** [comment]
I found it!

need to use "element" inside the input like this:
![image](https://github.com/chakra-ui/chakra-ui/assets/98822745/5009a274-71e8-4238-92b2-dff771036ed1)

![image](https://github.com/chakra-ui/chakra-ui/assets/98822745/5009a274-71e8-4238-92b2-dff771036ed1)

**Comment by ashatat** [comment]
I needed to edit same element but inside a variants, it didn't work, it seems to only work in the baseStyle

```js
Input: {
		defaultProps: {
			size: "lg",
		},
		baseStyle: {
			field: {
				_placeholder: {
					color: "text.label",
					opacity: 0.4,
				},
			},
			element: {
				h: "calc(36px - 1.25rem)", // it works here
			},
		},
		sizes: {
			lg: {
				field: {
					fontSize: "md",
					borderRadius: "xl",
				},
			},
		},
		variants: {
			main: {
				field: {
					h: "36px",
					bg: "gray.400",
					color: "blackText",
					px: "1rem",
					py: "0.625rem",
					rounded: "8px",
					fontSize: "12px",
					fontWeight: "400",
				},
				element: {
					h: "calc(36px - 1.25rem)", // but it doesn't work here, not sure why
				},
			},
		},
	},
	```
	I only needed the change in the `main` variant i created 🤷
