### ISSUE TITLE
Potential responsive style bug

### ISSUE THREAD

**Issue by coodoo** [chakra-ui/chakra-ui#312]
I was expecting the following two statements should have the same effect (when in small screen it's `1fr`, any other screen sizes will be `1fr 1fr 1fr`), but strangely, the one on top is making `md` to be `1fr` too, while the one on the bottom worked correctly. Not sure if this is expected or indeed a bug?

```js
templateColumns={{
	sm: '1fr',
	md: '1fr 1fr 1fr',
}}

templateColumns={['1fr', '1fr 1fr 1fr']}
```

**Comment by segunadebayo** [comment]
@coodoo, this might need some more clarification due to how style props work in styled-system.

To make them the same, try this:
```jsx
// base applies to all screens
// sm applies to `sm` upwards
templateColumns={{
	base: '1fr',
	sm: '1fr 1fr 1fr',
}}

// first index, applies to all screens
// second index applies to `sm` upwards
templateColumns={['1fr', '1fr 1fr 1fr']}
```
