### ISSUE TITLE
Enhancements about how to add font files to Chakra and Next.js

### ISSUE THREAD

**Issue by LauraBeatris** [chakra-ui/chakra-ui#3120]
# 🚀 Feature request

After watching this [video](https://www.youtube.com/watch?v=G0cOQ79WKZE) about web fonts, I have some suggestions to apply in the [docs](https://chakra-ui.com/guides/with-nextjs-font-files#import-fonts-from-public-folder) about Next.js + font files.

## 🧱 Problem Statement / Justification

According to this note:

![image](https://user-images.githubusercontent.com/48022589/105521388-95b0da80-5cba-11eb-9d06-cb627d24a446.png)

I decided to send this enhancement suggestion since the preloading and caching fonts resources can help to improve the initial loading time of custom fonts.

## ✅ Proposed solution or API

The [docs](https://chakra-ui.com/guides/with-nextjs-font-files#import-fonts-from-public-folder) can mention preloading the fonts resource and also caching it. There is a lot of useful information in this [blog post](https://leerob.io/blog/fonts).

## ↩️ Alternatives

I don't know if would be too specific to mention how to cache resources using [Vercel](https://vercel.com/docs/configuration#project/headers) but we should at least mention that it's possible to do so.

**Comment by LauraBeatris** [comment]
I don't if it's exactly a feature request but I decided to follow the issue template 🥲

**Comment by LauraBeatris** [comment]
From [docs](https://chakra-ui.com/guides/with-nextjs-font-files#import-fonts-from-public-folder): 
> As to what is going on in unicode-range, I do not entirely know. It came from this GitHub issue. It does not appear to cause any harm. If you experience bad mojo, submit a PR and we can revise this guide.

`unicode-range` is used to apply subsettings. Refer to the following quote from https://leerob.io/blog/fonts:

`Font files contain multiple languages and glyphs, which increase the file size. Subsetting is the removal of characters you don’t need.`

**Comment by DecliningLotus** [comment]
I feel that guide may not be necessary. Thoughts on [Fontsource](https://github.com/fontsource/fontsource) which essentially simplifies the whole self-hosting process removing the need to create the custom CSS? Furthermore, it helps you keep the fonts updated just like a regular NPM package.

Same way, you just import it into your `_app.js` or `_app.tsx`.

**Comment by DecliningLotus** [comment]
Personally, I'm open to making a PR that offers an alternate installation guide for Fontsource. It would be great to get approval for it here though, so not stale.

**Comment by segunadebayo** [comment]
Hi @DecliningLotus. Go for it! I'd be happy to review it.

**Comment by LauraBeatris** [comment]
@DecliningLotus Thanks for the suggestion!
