### ISSUE TITLE
PopoverTrigger doesn't support functional components as children

### ISSUE THREAD

**Issue by marcebdev** [chakra-ui/chakra-ui#3121]
# 🐛 Bug report

Due to how references are being used React FC's aren't able able to use the reference and correctly act as triggers.

## 💥 Steps to reproduce

1. Create a functional component wrapper, it can just return something like `<div>test</div>`
2. Place said component inside a **PopoverTrigger** element

#### Docs:
This is never mentioned in the docs as far as I can find, though it's relatively straight forward from the console error that this is due to a Functional Component being used.

It would be nice to have such an example in the docs, the one example that uses Box doesn't really take advantage of the face it can show you might use a Box to otherwise wrap functional components.

#### Type safety:
It's perhaps a bit tricky since the return value for a FC isn't always React.FC, I'm relatively new to TypeScript so I'm not sure, but disallowing Functional children in some way if the current method is kept would be nice.

#### Behavior:
I believe this scenario is better avoided as mentioned in solutions but for completeness, either clarifying the use of **PopoverTrigger** or handling exceptions for this use of references so that **PopoverTrigger** works reliably.

## 🧭 Possible Solution

The two solutions I can think of are
- Make **PopoverTrigger** an actual element, as it appears to be a React fragment)
- Somehow injecting useRef if a child is a functional component

I know that Chakra has a habit of not wrapping elements with actual elements (i.e. using fragments) and in many cases this provides flexibility; However, in this case the behavior of having to wrap FC's so that references work correctly is a little opaque and if it comes down to it seems wrapping everything by default is a more sustainable and less ambiguous approach.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.1.4      |

**Comment by segunadebayo** [comment]
Hi @marcebdev, I'd recommend wrapping this functional component in a `Box` instead if you want the `ref` to be forwarded correctly.

We won't be adding this feature as it is considered a breaking change.

Cheers.

**Comment by nvmnghia** [comment]
@segunadebayo  This is still true in Chakra v2. The doc hasn't been updated with this workaround. Will this be implemented in v3?
