### ISSUE TITLE
Bootstrap-like button outline/border behaviour

### ISSUE THREAD

**Issue by ildan-gh** [chakra-ui/chakra-ui#3122]
Hi there! Would it possible to have this button behaviour like Bootstrap as default? I think it looks pretty neat if the outline matches the button color.

![untitled](https://user-images.githubusercontent.com/75571904/105568907-8626a580-5d3d-11eb-9bf6-c590973f3ed9.gif)

**Comment by ildan-gh** [comment]
Just saw it has already been mentioned here: https://github.com/chakra-ui/chakra-ui/issues/1055#issuecomment-652335379

However @segunadebayo 's link he posted does not work.

**Comment by gejimayu** [comment]
so... is this a valid issue ? if so i'll be happy to help

**Comment by segunadebayo** [comment]
Hi @ildan-gh, this isn't a valid issue. Kindly permit me to close it.

In future APIs, we'll provide an easy way to update the focus-ring colors for interactive elements.

Cheers.
