### ISSUE TITLE
useMediaQuery - doesn't select the corect state on initial load

### ISSUE THREAD

**Issue by robalaban** [chakra-ui/chakra-ui#3124]
# 🐛 Bug report

When using the hook `useMediaQuery(["(min-width: 980px)"])` for example - the state only updates after I manually come near the threashold set, but if I load my component under that width it will not trigger and update the component.

## 💥 Steps to reproduce

1. Go to you component with `useMediaQuery([])` hook
2. Load the component under the threadshold set in the hook
3. Notice that even though the state is correct the component doesn't re-render
4. Now - resize your screen
5. Notice that the component triggers its re-render

## 🧐 Expected behavior

When using the useMediaQuery hook - when the component is initially loaded - trigger a re-render if under / above the threshold. 

## 🧭 Possible Solution

Checking on load - if 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       Latest     |
| Browser          |      Chrome Latest      |
| Operating System |    OXS        |

## 📝 Additional information

```js
const CardSection: React.FC = () => {
  const [isLargerThanMd, isDisplayingInBrowser] = useMediaQuery([
    "(min-width: 980px)",
    "(display-mode: browser)",
  ])

  const CardComponents = [
    <Card key={0} title="Cryptocurrencies" link="/dashboard" />,
    <Card key={1} title="Stocks" link="/dashboard" />
  ]

  function determinDevice() {
    let component;
    switch (isLargerThanMd) {
      case false:
        component = <VStack> {CardComponents} </VStack>
        break
      default:
        component = <HStack> {CardComponents} </HStack>
        break
    }
    return component
  }

  return (determinDevice())
}
```

**Comment by dominictwlee** [comment]
@robalaban Tried your example with the latest version and seems fine to me. Loads initially with a VStack, then adjusts accordingly to HStack/VStack when viewport is resized.

The only thing I changed were your card components (replaced them with plain Boxes)

Initial load:
![image](https://user-images.githubusercontent.com/34794189/106359734-69c1d480-630c-11eb-80f9-697fad1b6deb.png)

readjusted to larger than 980px:
![image](https://user-images.githubusercontent.com/34794189/106359769-983faf80-630c-11eb-849a-785d72f435c3.png)

Maybe setup a minimal example on codesandbox and I can help you look further into this?

**Comment by Ionito** [comment]
hi @dominictwlee 
I am having similar issue
look at this codesandbox I made [](https://codesandbox.io/s/hopeful-jennings-p8uxm)
If yo stand in the "mobile state" and reload the page, the showing comp isn't the correct one
Tell me please if you can see what I am trying to explain.
thanks

**Comment by Ionito** [comment]
Actually you can see the component showed changes (text inside change), but not the bg color...
Also I am see this warning `"Warning: Text content did not match. Server: "web component" Client: "Mobile Component"`

**Comment by dennemark** [comment]
Hi,
I seem to have the same issue, also getting the warning Ionito mentioned. My useMediaQuery is returning true, but the Box component is still taking a false value. I am using NextJS in development mode, not sure if it is related to this?

```
const MyComponent = () => {
  const [isMinWidthMedium] = useMediaQuery("(min-width: 768px)");
  console.log("orientation", isMinWidthMedium) //logs true
  return (
        <Box display="flex" 
        orientation={isMinWidthMedium ? "vertical" : "horizontal" /*has value horiztonal, so if statement is false*/} 
        >
       </Box>
)
}
```

**Comment by dennemark** [comment]
Current workaround with useEffect seems to fix useMediaQuery, but not the warning. I guess the issue is related to SSR in my case, since I have read about the warning in nextjs and SSR related posts elsewhere.

```
const MyComponent = () => {
  const [isMinWidthMedium, setIsMinWidthMedium] = useState(false);
  const mediaQuery = useMediaQuery("(min-width: 768px)");

  useEffect(() => {
    if(mediaQuery !== isMinWidthMedium){
      setIsMinWidthMedium(mediaQuery);
    }
  }, [mediaQuery])
  return (
        <Box display="flex" 
        orientation={isMinWidthMedium ? "vertical" : "horizontal" /*has value horiztonal, so if statement is false*/} 
        >
       </Box>
)
}
```

**Comment by dominictwlee** [comment]
@Ionito Ah yeah I see it now. The wrong background color is showing.
@dennemark I think you're onto something, could be strictly SSR/nextjs related, since I couldn't repro this in plain React without nextjs

**Comment by ooaeoaey** [comment]
I faced the same problem with
```
"@chakra-ui/react": "^1.2.1",
"next": "10.0.6",
```

**Comment by payapula** [comment]
I can confirm this happens on SSR ([14810](https://github.com/vercel/next.js/discussions/14810)). I am using nextjs and the issue is that the server is sending the rendered page for desktop, but the client is not getting re-rendered when this useMediaQuery() hook executed.

This happens only on the initial load. I solved it using [this hook](https://github.com/vercel/next.js/discussions/14810#discussioncomment-61177) as suggested in nextjs repo.

```
import { useState, useCallback, useEffect } from 'react';

const useMediaQuery = (width) => {
  const [targetReached, setTargetReached] = useState(false);

  const updateTarget = useCallback((e) => {
    if (e.matches) {
      setTargetReached(true);
    } else {
      setTargetReached(false);
    }
  }, []);

  useEffect(() => {
    const media = window.matchMedia(`(max-width: ${width}px)`);
    media.addListener(updateTarget);

    // Check on mount (callback is not called until a change occurs)
    if (media.matches) {
      setTargetReached(true);
    }

    return () => media.removeListener(updateTarget);
  }, []);

  return targetReached;
};
```

Also, for responsive styles you need to add meta tag --> [meta tag for viewport](https://github.com/vercel/next.js/issues/5122)

For my case it worked without even adding the above meta tag.

**Comment by wereHamster** [comment]
The bug is actually in the implementation of the useMediaQuery hook (#3580), however the issue I raised was closed as working-as-intended. You're not supposed to use useMediaQuery in server-rendered components!

I suggest to not use the useMediaQuery hook from the chakra-ui project and instead use another one that does work reliably with SSR (such as the one from @payapula).

**Comment by geisterfurz007** [comment]
For what it's worth, `useBreakpoint` as well as `useBreakpointValue` fall under the same category as they also rely on `window.watchMedia`. Maybe this helps Googlers find this issue when searching for the same thing with a different hook.

**Comment by Darek79** [comment]
@payapula 

the addListener() method is deprecated.

https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener

**Comment by wereHamster** [comment]
@Darek79 `addEventListener()` on `MediaQueryList` is only supported in Safari 14 and later. So if you need to support Safari <=13 you need to stick with `addListener()`.

**Comment by voyagebagage** [comment]
none of the solutions worked for me on next13 & chakra ui

**Comment by payapula** [comment]
Can you reproduce the issue on a codesandbox or any other way so that I can take a look? 

I am not quite sure, but if you are using next 13 with server components (app directory), then you expect these things to happen as they are still experimental. If it's not experimental next 13, then please try to create a sandbox to take a look.
