### ISSUE TITLE
colorModeManager cookies is not setting the cookie

### ISSUE THREAD

**Issue by chrisbull** [chakra-ui/chakra-ui#3135]
# 🐛 Bug report

If you watch the cookies using the `examples/nextjs-typescript` examples, the cookies aren't getting set for `chakra-ui-color-mode` even though the example product is set to use the cookies

## 💥 Steps to reproduce

1. run the examples/nextjs-typescript project
2. clear your cookies
3. watch as no cookie is getting set

## 💻 Link to reproduction

It works on codesandbox fine. But locally it does not. Any idea why? I've tried both node 14 and 12

## 🧐 Expected behavior

a cookie value should be set as `chakra-ui-code-mode`

## 🧭 Possible Solution

I found that if you manually set `cookies: ctx.req.headers.cookie ?? "chakra-ui-color-mode=light",` instead of `cookies: ctx.req.headers.cookie ?? "",` it will trigger the cookie and start actually using properly. So I belive the issue is in the `colorCodeManager` script. Where the cookie is supposed to be getting set. A recommendation would be to use an npm package like `cookie` or `nookies` (next js support) to set the cookie properly. 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |            |
| Browser          |            |
| Operating System |            |

## 📝 Additional information

- Screenshots or code
- Notes or link to ideas

**Comment by sleeyax** [comment]
Same issue, the suggested work around doesn't work in my project though.

**Comment by yatxone** [comment]
Can confirm, issue is still relevant.

Setting the cookie the proposed way `cookies: ctx.req.headers.cookie ?? "chakra-ui-color-mode=light"` works.

**Comment by darasus** [comment]
Downgrading to 1.6.7 resolved the issue for me.
