### ISSUE TITLE
<Spinner /> - Expected server HTML to contain a matching <span> in <div>.

### ISSUE THREAD

**Issue by RadovanPelka** [chakra-ui/chakra-ui#3136]
# 🐛 Bug report

> Hi guys, pls fix

## 💥 Steps to reproduce

> NextJS app, import Spinner

![image](https://user-images.githubusercontent.com/29738200/105631032-9aa59380-5e4c-11eb-9c39-8f351458d2f0.png)

![image](https://user-images.githubusercontent.com/29738200/105631147-3a632180-5e4d-11eb-8858-1a9be0eb1d85.png)

> Not compulsory, but suggesting a fix would be great!

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  latest  |
| Browser          |  all ( chrome ) |
| Operating System |    all  ( macos )    |

**Comment by tomdohnal** [comment]
Do you have a CodeSandbox with a reproduction?
I've put together what I believe would be the minimal reproduction based on what you've written at it seems to be working just fine for me: https://codesandbox.io/s/polished-cookies-k7qxe?file=/pages/_app.js

**Comment by RadovanPelka** [comment]
Fake alert, my bad. Sry
