### ISSUE TITLE
Accessiblity: Navigation issues using keyboard on <Menu/>

### ISSUE THREAD

**Issue by harshzalavadiya** [chakra-ui/chakra-ui#314]
**Describe the bug**
In `<Menu/>` component while navigating with keyboard if `<MenuItem/>` is or has Link inside it's not navigating but `onClick` event gets triggered perfectly and clicking using mouse also works fine.

below is the example taken from https://chakra-ui.com/menu#usage

```jsx
<Menu>
  <MenuButton as={Button} rightIcon="chevron-down">
    Actions
  </MenuButton>
  <MenuList>
    <MenuItem onClick={() => alert("Hello World!")}>Works</MenuItem>
    <MenuItem as="a" href="https://www.foobars.in">Does Nothing</MenuItem>
  </MenuList>
</Menu>
```

**Expected Behavior**
Should navigate to href on pressing enter on <MenuItem/> component

**To Reproduce**
1. Navigate to Second menu item
2. Press enter on selected component
4. Nothing happens instead of navigating

**Suggested solution(s)**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Linux
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: 79.0.3945.79

**Additional context**
NA

**Comment by harshzalavadiya** [comment]
not stale

**Comment by segunadebayo** [comment]
Hi @harshzalavadiya,

We'll look into this for the next release.

**Comment by harshzalavadiya** [comment]
not stale

**Comment by segunadebayo** [comment]
Hi @harshzalavadiya,

We've just resolved this issue in preparation for the next release.

Thanks for reporting it.

**Comment by thure** [comment]
In case anyone else is coming here from a search engine and their `as` component is more than just `'a'`, bear in mind the component you provide should forward the necessary refs (using `forwardRef`) in order for accessibility to work.

**Comment by jansengunderson** [comment]
> In case anyone else is coming here from a search engine and your `as` component is more than just `'a'`, bear in mind the component you provide should forward the necessary refs (using `forwardRef`) in order for accessibility to work.

Has anyone been able to get this to work with Gatsby Link? We've been able to make it work by passing navigate to onClick in the <MenuItem /> component, but have been unsuccessful following thure's advice.

```
<MenuItem
  key={index_}
  className="sub-menu-item"
  whiteSpace="nowrap"
  padding="0"
  target={item.link.target}
  onClick={() => {navigate(item.link.url)}}
>
  {item.link_label.text}
</MenuItem>
```

**Comment by mikemajara** [comment]
FTR: here how I solved it in NextJS

```
<NextLink href={navItem.href} passHref>
            <MenuItem
              as={ChakraLink}
              icon={<Icon as={navItem.icon} />}
              href={navItem.href}
              _hover={{ textDecor: "none" }}
            >
              {navItem.label}
            </MenuItem>
          </NextLink>
```
