### ISSUE TITLE
Td BG color change only applies on even rows if Table variant is striped

### ISSUE THREAD

**Issue by ronnyhaase** [chakra-ui/chakra-ui#3144]
# 🐛 Bug report

Hi, I noticed that on a `<Table/>` with `variant` `"striped"` changing the BG color via props only applies on even rows.
A quick look into the inspector reveals that it is related to CSS cascadence - the default background-color has higher precedence than the one from the prop (see screenshot).

## 💥 Steps to reproduce

Create a striped table with at least 3 rows and change the background color via bg prop of tds.

## 💻 Link to reproduction

https://codesandbox.io/s/agitated-tdd-su5eq

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.0.3           |
| Browser          | All           |
| Operating System | All           |

## 📝 Additional information

<img width="1680" alt="screenshot" src="https://user-images.githubusercontent.com/714368/105646582-fac62500-5ea0-11eb-8b36-5d0a859aafcf.png">

**Comment by ronnyhaase** [comment]
On a side note, wouldn't it be better to add the colors to the tr not the td?

I'm building a diff view were colors vary either on a whole row or a single cell and need to add unecessary logic (if diff on row set cell color to X, otherwise Y when cell value is also different)

Happy to create a separate ticket if you find it worth a discussion. Thanks!

**Comment by TimKolberger** [comment]
Hi @ronnyhaase,

You are correct, the CSS selector `&:nth-of-type(odd)` has a higher precendence than a single classname. I think there is no way around it, besides `!important`. 

```tsx
import { useToken } from '@chakra-ui/react'
//...

const bg = useToken('colors', 'red.500')

<Td bg={bg + '!important'} />
```

If this is not satisfactory, and you are managing the background colors on your own you can use the default `variant="simple"` and set the colors as you need in JS. e.g. `bg = index % 2 ? 'red.500' : 'green.500'`. 

Regarding styling the `td` with a background: The HTML table can have additional headers in a row. e.g.

```tsx
<Table variant="striped">
  <Tbody>
    <Tr>
       <Th>Left Title</Th>
       <Td>1</Td>
     </Tr> 
     <Tr>
       <Th>Left Title</Th>
       <Td>1</Td>
     </Tr>
   </Tbody>
</Table>
```

If the `tr` had the background, this would not look that great. We try to provide default styles to be sufficient most use cases, but there isn't a perfect one-fits-all solution.

If in your case styling the `tr` works for you, you can create a custom variant:

```ts
const customTheme = extendTheme({
  components: {
    Table: {
      variants: {
        mytable: {
          tr: {
            _odd: {
              background: "green.500"
            }
          }
        }
      }
    }
  }
});

<ChakraProvider theme={customTheme}>
      <Table variant="mytable">
//...
```

**Comment by ronnyhaase** [comment]
Thanks so much for the detailed explanation - makes sense - and solutions, @TimKolberger !

This helps me, I leave it to you and the team if you consider the issue done. But I might not be the only one surprised by the behavior, might be worth documenting - esp. the `+ !important'` for CSS precedence "issues"?
