### ISSUE TITLE
[Tooltip] Using the "auto" `placement` causes arrow to change directions when `isOpen` is toggled

### ISSUE THREAD

**Issue by rr-matthew-benjamin** [chakra-ui/chakra-ui#3160]
# 🐛 Bug report

Hi! I'm trying to use the `placement="auto"` prop on the `Tooltip`. This is causing behavior that can be seen in this video:

https://user-images.githubusercontent.com/69278191/105784186-27278300-5f2d-11eb-97b5-78d2e5de4e31.mp4

What I found out is that in the `use-popper.ts` file there is a `finalPlacement` variable that gets set by the `use-popper` hook. In that `use-popper` there's a discrepancy between the `popperState` and the `popperOptions`.

## 💥 Steps to reproduce

1. Use the tooltip with `placement="auto"`
```
  <Tooltip
    aria-label="Button Clicked"
    label="Button Clicked"
    placement="auto"
    bg="bgColor"
    color="textColor"
  >
    <Button>
      Open Modal
    </Button>
  </Tooltip>
```

## 💻 Link to reproduction

[CodeSandbox](https://codesandbox.io/s/blissful-hodgkin-l4vpl?file=/src/App.js)

## 🧐 Expected behavior

When you "re-hover" or "re-click" I'd expect the arrow to be in the same location

## 🧭 Possible Solution

Not entirely sure...but I think it might have to do with the `useSafeLayoutEffect` not being called again in `react-popper.ts`

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |    ^1.0.3        |
| Browser          |  Chrome 88.0.4324.96          |
| Operating System |         MacOS Catalina 10.15.6    |

**Comment by tomdohnal** [comment]
Can I try to look into that? @with-heart

**Comment by deebov** [comment]
I am also seeing this issue

**Comment by with-heart** [comment]
> Can I try to look into that? @with-heart 

Yes please! Always open to others jumping in and helping ♥
