### ISSUE TITLE
MenuOptionGroup onChange does not work on new menu items added dynamically

### ISSUE THREAD

**Issue by gregdingle** [chakra-ui/chakra-ui#3171]
# 🐛 Bug report

Re-renders won't update `onChange` because of memoization here: https://github.com/chakra-ui/chakra-ui/blob/a505441cafa1f1a5593eeae395feadd8083aae14/packages/menu/src/use-menu.ts#L572 . 

## 💥 Steps to reproduce
1.
```
          <MenuOptionGroup
            type="radio"
            onChange={(ids) => {
              const selected = items.filter((deck) => ids.includes(deck.id))>
              {items.map((item) => (
                <MenuItemOption key={item.id} value={item.id}>
                  {item.name}
                </MenuItemOption>
              ))}
```

2. add a new item to `items` array dynamically by setting state in parent
3. click on item in menu
4. `selected` is `undefined`

## 🧐 Expected behavior

New item should be selectable.

## 🧭 Possible Solution

Don't `useCallback` in https://github.com/chakra-ui/chakra-ui/blob/a505441cafa1f1a5593eeae395feadd8083aae14/packages/menu/src/use-menu.ts#L572 .

**Comment by mcbroh** [comment]
You can solve this by using the MenuItemOption, use the  `onClick` props together with the `isChecked`props and this should give you the same behavior you are looking for. I hope this helps

**Comment by u-yas** [comment]
The bug that onChange of MenuOptionGroup does not work with the new MenuItemOption may be solved by referring to this issue.
#5011 
do not wrap using React.FC (or React.VFC). let wrap with forwardRef (@chakra-ui/system)

**Comment by selvinkuik** [comment]
@u-yas Unfortunately that suggestion did not work. I'm still able to reproduce this issue. My code structure is the same as OP's, we are not wrapping `MenuItemOption` – this is to do with the dynamic creation of components

**Comment by nip10** [comment]
I can still repro this bug, and I believe this is related to option group items being generated dynamically.

This works:
```ts
<Menu closeOnSelect={false}>
  <MenuButton
    as={Button}
    colorScheme="teal"
    variant="link"
    fontSize="sm"
  >
    Edit category
  </MenuButton>
  <MenuList maxHeight="400px" overflowY="scroll">
    <MenuOptionGroup
      type="checkbox"
      onChange={onCategoryChange}
    >
      <MenuItemOption value="foo">Foo</MenuItemOption>
      <MenuItemOption value="bar">Bar</MenuItemOption>
    </MenuOptionGroup>
    <MenuDivider />
    <MenuItem onClick={onEditTagsClick}>Edit my tags </MenuItem>
  </MenuList>
</Menu>
```

This doesn't work:
```ts
<Menu closeOnSelect={false}>
  <MenuButton
    as={Button}
    colorScheme="teal"
    variant="link"
    fontSize="sm"
  >
    Edit category
  </MenuButton>
  <MenuList maxHeight="400px" overflowY="scroll">
    <MenuOptionGroup
      type="checkbox"
      onChange={onCategoryChange}
    >
      {categories.map((category) => (
        <Fragment key={category.categoryKey}>
          <MenuItemOption value={category.name}>
            <Flex alignItems="center" gap={2}>
              <Icon name={category.icon} /> {category.name}
            </Flex>
          </MenuItemOption>
          {category.childCategory.map((childCategory) => (
            <MenuItemOption
              key={childCategory.categoryKey}
              value={childCategory.name}
              pl={8}
            >
              <Flex alignItems="center" gap={2}>
                <Icon name={childCategory.icon} />{" "}
                {childCategory.name}
              </Flex>
            </MenuItemOption>
          ))}
        </Fragment>
      ))}
    </MenuOptionGroup>
    <MenuDivider />
    <MenuItem onClick={onEditTagsClick}>Edit my tags </MenuItem>
  </MenuList>
</Menu>
```

**Comment by natBizitza** [comment]
Any news on this one?

**Comment by yasircodingcrafts** [comment]
@HenrikBechmann what is `workspaceMenuIteration` ?
