### ISSUE TITLE
colorScheme="black" bug

### ISSUE THREAD

**Issue by MikeMajara** [chakra-ui/chakra-ui#3172]
When setting `colorScheme="black"` or `colorScheme="white"` or any other custom color, the color does not get applied, since these two have no levels in default theme.

<img width="483" alt="image" src="https://user-images.githubusercontent.com/15649320/105892125-b27a4480-6011-11eb-8c19-d638871cb27e.png">

https://github.com/chakra-ui/chakra-ui/blob/7415eb6394bb0014e699c9c6006f4fa284f66f53/packages/theme/src/components/switch.ts#L21

In the same way, if I define my own theme with different tones of let's say `white` components will not work b/c they are assuming white exists with no shades according to defaultTheme.

**Comment by with-heart** [comment]
Yeap, they're just constants. We should probably note that in the docs somewhere but it's not a bug, that's just how those two in particular work.

**Comment by MikeMajara** [comment]
thanks @with-heart, so, given this is expected behavior, it seems cumbersome to have to define my own color to give the component a different scheme than the ones defined in the default theme.

I tend to see as a simpler approach to have theme take any color you want, including those in the default theme, that would then be converted to the corresponding html color. something along the lines of `colorScheme="blue.200"` would be more flexible and intuitive IMHO.

Would that be a major change? I'd be willing to do a PR

**Comment by with-heart** [comment]
Yeah that would not only be a massive change in both behavior, docs, and all user themes, I'm not even sure that would make sense. The whole point of `colorScheme` is to pass a scale so that we can pick multiple colors from it to handle multiples states like hover, active, etc. states for `Button`. What would `colorScheme="red.300"` mean?

**Comment by MikeMajara** [comment]
I see what you mean, makes sense. I see the big picture now. Thanks a mill!

**Comment by with-heart** [comment]
@MikeMajara Do you think there's a good place in particular that we should explain that in the docs? Wondering if you happened to look in a specific area for more info about this or something.

**Comment by MikeMajara** [comment]
@with-heart Yeah! I did search for `colorScheme` first, but found no specific sections (expected). But I would've expected this to be in either or both [Colors](https://chakra-ui.com/docs/theming/theme#colors), or [Customize Theme](https://chakra-ui.com/docs/theming/customize-theme) with a preference for the first option, as I find it more intuitive.
