### ISSUE TITLE
Warning when using Menu inside HStack

### ISSUE THREAD

**Issue by dbousamra** [chakra-ui/chakra-ui#3173]
# 🐛 Bug report

A warning is issued when a Menu is used inside an HStack
## 💥 Steps to reproduce

> Clear and concise reproduction steps are important for us to be able to triage
> your issue in a timely manner

## 💻 Link to reproduction

https://codesandbox.io/s/proud-hill-82dg5?file=/src/index.tsx

## 🧐 Expected behavior

No warning

## 🧭 Possible Solution

> Not compulsory, but suggesting a fix would be great!

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |            |
| Browser          |            |
| Operating System |            |

## 📝 Additional information

- Screenshots or code
- Notes or link to ideas

**Comment by segunadebayo** [comment]
Hi @dbousamra,

I think this is the wrong usage of the Menu component. Here are some ideas:

- To render the menu-list to the left of the menu button, pass the `placement` prop to the `Menu` component and set it to `right-start`.
- To add some spacing between the menu button and the menu list, pass the `gutter` prop to the `Menu` component.

This warning is coming from `popper.js` and it basically hints that you're using it incorrectly. Hope this helps.

Cheers.

**Comment by dbousamra** [comment]
Hi @segunadebayo thanks for getting back to me.

I disagree this is a mis-usage of the Menu component. Or at least I disagree it's obvious that theres a misuse. I don't care about the placement of the menu-list at all. 

My example was designed to be as minimal as possible to demonstrate the issue. All I am doing is nesting a Menu inside an HStack, which seems valid to me. The real-world use case behind doing this is I have a navbar with items like so:

```
<Flex px={4} py={3} w="full" bg="extraDarkPurple">
  <HStack spacing={4}>
    <FileUploadButton />
    <UserMenu />
  </HStack>
</Flex>
```

where `UserMenu` is similarly structured to above.

**Comment by muhammetsait** [comment]
I was also using the Menu components inside an HStack to create a nav bar and was getting this warning:

```
Popper: CSS "margin" styles cannot be used to apply padding between the popper and its reference element or boundary. To replicate margin, use the `offset` modifier, as well as the `padding` option in the `preventOverflow` and `flip` modifiers.
```

The solution was replacing `HStack` with `Flex` just like @dbousamra did in his case.

**Comment by mustaphaturhan** [comment]
I am also using the `Menu` component inside `Stack` element and the same thing happened to me.

As a workaround, I wrapped `<Menu>` component with a `<Box>` so I can still use `spacing` props of `Stack` element. In this case, solution is:

```jsx
    <Flex px={4} py={3} w="full" bg="purple.800">
      <HStack>
        <Button>Item 1</Button>
        <Button>Item 2</Button>
        <Button>Item 3</Button>
        <Box>
          <Menu>
            <MenuButton as={Button}>Actions</MenuButton>
            <MenuList>
              <MenuItem>Download</MenuItem>
              <MenuItem>Create a Copy</MenuItem>
              <MenuItem>Mark as Draft</MenuItem>
              <MenuItem>Delete</MenuItem>
              <MenuItem>Attend a Workshop</MenuItem>
            </MenuList>
          </Menu>
        </Box>
      </HStack>
    </Flex>
```

**Comment by goritm** [comment]
@mustaphaturhan that worked for me, thanks!

**Comment by hjaber** [comment]
I was having a similar issue, was receiving an error: 

`Popper: CSS "margin" styles cannot be used to apply padding warning when using OverlayTrigger with Popover` 

Using @mustaphaturhan's solution of wrapping Menu with a Box solved my issue

```
<Box>
  <Menu>
    <MenuButton as={Button} rightIcon={<ChevronDownIcon />}>
      Actions
    </MenuButton>
    <MenuList>
      <MenuItem>Download</MenuItem>
    </MenuList>
  </Menu>
<Box>
```

Much appreciated.

**Comment by rohithandique** [comment]
@mustaphaturhan this worked for me too, thanks a lot!

**Comment by alexnguyennz** [comment]
I also get this warning using the default Menu example with no modifications, with 1.8.5. Wrapping in a <Box /> has hidden it, thanks.

**Comment by mallen13** [comment]
> I am also using the `Menu` component inside `Stack` element and the same thing happened to me.
> 
> As a workaround, I wrapped `<Menu>` component with a `<Box>` so I can still use `spacing` props of `Stack` element. In this case, solution is:
> 
> ```js
>     <Flex px={4} py={3} w="full" bg="purple.800">
>       <HStack>
>         <Button>Item 1</Button>
>         <Button>Item 2</Button>
>         <Button>Item 3</Button>
>         <Box>
>           <Menu>
>             <MenuButton as={Button}>Actions</MenuButton>
>             <MenuList>
>               <MenuItem>Download</MenuItem>
>               <MenuItem>Create a Copy</MenuItem>
>               <MenuItem>Mark as Draft</MenuItem>
>               <MenuItem>Delete</MenuItem>
>               <MenuItem>Attend a Workshop</MenuItem>
>             </MenuList>
>           </Menu>
>         </Box>
>       </HStack>
>     </Flex>
> ```

The box solution worked for me as well. March 2022

**Comment by oncet** [comment]
@segunadebayo how is using `Menu` inside an `HStack` a misuse? Looks like a valid use case as already pointed by some of the comments.

**Comment by mawais786** [comment]
> I am also using the `Menu` component inside `Stack` element and the same thing happened to me.
> 
> As a workaround, I wrapped `<Menu>` component with a `<Box>` so I can still use `spacing` props of `Stack` element. In this case, solution is:
> 
> ```js
>     <Flex px={4} py={3} w="full" bg="purple.800">
>       <HStack>
>         <Button>Item 1</Button>
>         <Button>Item 2</Button>
>         <Button>Item 3</Button>
>         <Box>
>           <Menu>
>             <MenuButton as={Button}>Actions</MenuButton>
>             <MenuList>
>               <MenuItem>Download</MenuItem>
>               <MenuItem>Create a Copy</MenuItem>
>               <MenuItem>Mark as Draft</MenuItem>
>               <MenuItem>Delete</MenuItem>
>               <MenuItem>Attend a Workshop</MenuItem>
>             </MenuList>
>           </Menu>
>         </Box>
>       </HStack>
>     </Flex>
> ```

It'll not work if using `MenuButton` as a `Link`. For that wrap `<MenuList>` component with a `<Portal>`

**Comment by cassiewallace** [comment]
I am having a similar issue with the Popover component, and wrapping the entire component in a Box worked to clear the error as well.

**Comment by Inviz** [comment]
Easy solution to the issue is to add `global` style into theme like this: 

```
  styles: {
    global: {
      '.chakra-popover__popper.chakra-popover__popper': {
        margin: '0'
      },
```
two classes to ensure higher specificity than normal. I find this much better solution rather than wrapping each case of popper/menu in a box.
