### ISSUE TITLE
Discrete Sliders

### ISSUE THREAD

**Issue by DecliningLotus** [chakra-ui/chakra-ui#3183]
# 🚀 Feature request

It would be nice if we could add discrete sliders to the library. This is where the slider moves up or down in fixed intervals (30, 60, 90, ...) rather than continuously.

## 🧱 Problem Statement / Justification

It would allow the sliders library to be more versatile and flexible. Should fit many user use cases.

## ✅ Proposed solution or API

This is the Material UI counterpart that illustrates the proposal -
https://material-ui.com/components/slider/#discrete-sliders

**Comment by segunadebayo** [comment]
I believe it has been covered by the `step` prop in the Slider implementation we have, or am I missing something?

```jsx
<Slider defaultValue={60} min={0} max={300} step={30}>
      <SliderTrack bg="red.100">
        <SliderFilledTrack bg="tomato" />
      </SliderTrack>
      <SliderThumb boxSize={6} />
    </Slider>
```

**Comment by DecliningLotus** [comment]
Ah, step is mentioned in the Props section of the slider component, however, I would imagine there should be a visual example somewhere in the documentation to distinguish it? I don't believe step is mentioned anywhere else in that section at least.

I think that would be really helpful for a lot of users.

**Comment by dominictwlee** [comment]
I've made a PR for the documentation #3239.

Though perhaps what's been brought up is whether we want to expand the API of the Slider, giving the user the ability to easily add markers/indicators at the stepped positions of the slider track? I reckon it's a common enough use case to warrant this feature. What are your thoughts @segunadebayo ?
