### ISSUE TITLE
Passing "{ isReadOnly: true }" to "getInputProps()" gives Typescript error

### ISSUE THREAD

**Issue by ViaxCo** [chakra-ui/chakra-ui#3189]
# 🐛 Bug report

After getting `getInputProps` from `useNumberInput` and passing `{ isReadOnly: true }` as shown in the docs: `const input = getInputProps({ isReadOnly: true })`, it gives a Typescript error.
## 💻 Link to reproduction

https://codesandbox.io/s/affectionate-microservice-kl9ob?file=/src/App.tsx

## 🧐 Expected behaviour

Code should work without the Typescript error

## 🧭 Possible Solution

> Not compulsory, but suggesting a fix would be great!

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.1.6     |
| Browser          |            |
| Operating System |            |

## 📝 Additional information

- Screenshots or code
![Screenshot 2021-01-28 at 06 56 14](https://user-images.githubusercontent.com/43748536/106096469-ec446b80-6135-11eb-82d0-4bf40414621d.png)

**Comment by segunadebayo** [comment]
Hi @ViaxCo,

You should pass `isReadOnly` to the `useNumberInput` hook not `getInputProps`. Those prop getters only accept native react element props.

```jsx
import React from "react";
import "./styles.css";
import { useNumberInput } from "@chakra-ui/react";

export default function App() {
  const {
    getInputProps,
    getIncrementButtonProps,
    getDecrementButtonProps
  } = useNumberInput({ defaultValue: 0, isReadOnly: true });
  const inc = getIncrementButtonProps();
  const dec = getDecrementButtonProps();
  const input = getInputProps();
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
    </div>
  );
}
```

**Comment by ViaxCo** [comment]
Hello @segunadebayo,

Thank you for your response. I got the idea to pass `isReadOnly` to `getInputProps` from this part of the docs: [Create a mobile spinner](https://chakra-ui.com/docs/form/number-input#create-a-mobile-spinner).

**Comment by SC4RECOIN** [comment]
Does this mean the documentation is incorrect?
https://chakra-ui.com/docs/form/number-input#create-a-mobile-spinner

**Comment by Xayer** [comment]
Absolutely. 

> Does this mean the documentation is incorrect? https://chakra-ui.com/docs/form/number-input#create-a-mobile-spinner

Absolutely. Like shown in @segunadebayo's example code - move `isReadOnly: true` inside the `useNumberInput`'s prop object.

```typescript
function HookUsage() {
  const { getInputProps, getIncrementButtonProps, getDecrementButtonProps } =
    useNumberInput({
      step: 0.01,
      defaultValue: 1.53,
      min: 1,
      max: 6,
      precision: 2,
      isReadOnly: true // <- here
    })

  const inc = getIncrementButtonProps()
  const dec = getDecrementButtonProps()
  const input = getInputProps()

  return (
    <HStack maxW='320px'>
      <Button {...inc}>+</Button>
      <Input {...input} />
      <Button {...dec}>-</Button>
    </HStack>
  )
}
```
