### ISSUE TITLE
Editable submitOnBlur submits on button click

### ISSUE THREAD

**Issue by vogler** [chakra-ui/chakra-ui#3198]
# 🐛 Bug report

Following the example from https://chakra-ui.com/docs/form/editable#with-custom-controls
I would expect it to behave the same with `submitOnBlur`, i.e., <kbd>esc</kbd> should undo any change instead of calling `onSubmit`. Also, the cancel button should call `onCancel` instead of `onSubmit`.

## 💥 Steps to reproduce

The example linked below first calls `onCancel` and afterwards `onSubmit` but does not revert changes.
If you click the cancel button, it only calls `onSubmit`. I understand that clicking the button does blur `EditableInput`, but maybe the blur should be scoped to `Editable` instead. How can I get the button to call `onCancel` otherwise?

## 💻 Link to reproduction

 [TypeScript CodeSandbox template](https://codesandbox.io/s/happy-hypatia-okuw3?file=/src/App.tsx)

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.1.5      |
| Browser          |     Chrome 87.0.4280.88       |
| Operating System |      macOS 11.1 (20C69)      |

**Comment by with-heart** [comment]
Please fill out the whole report template when filing an issue. We ask for that information for a reason 😞  What browser and OS are you on?

**Comment by vogler** [comment]
Sorry, added above. Your setup behaves differently?

**Comment by with-heart** [comment]
Interesting! We have very similar setups but I'm only experiencing the problem with clicking the cancel button. `esc` is canceling as expected.

**Comment by vogler** [comment]
Huh, didn't expect a browser issue. Just tried it in Safari 14.0.2, there `esc` works.

**Comment by vogler** [comment]
Ok, if I disable the [Surfingkeys](https://github.com/brookhong/Surfingkeys) extension, `esc` works as expected.
The extension removes focus from the current input on `esc`. I assume it only passes through `esc` afterwards.
I'll open an issue there.

So, just the button issue remains.

**Comment by segunadebayo** [comment]
Looking into this!

**Comment by segunadebayo** [comment]
Pushed a fix for this! Should be available in the next release

**Comment by vogler** [comment]
Thanks! Just had to change from `useEditableState` to `useEditableControls` in my `EditableControls`.

I noticed that `getCancelButtonProps` sets `aria-label` but it's not reflected in the type (`string | undefined` instead of `string`).
For `Button` this is ok, but when using `IconButton` it can't be `undefined` which requires setting `aria-label` again.

**Comment by Robert-Rendell-THE** [comment]
hello! I'm seeing this issue again on the chakra demo for editable with the edit/submit/cancel buttons on Chrome and Safari:
https://v0.chakra-ui.com/editable 
Screenshot 2022-03-30 at 14.57.03
