### ISSUE TITLE
PortalManager still rendering closed menu elements when portalZIndex is used

### ISSUE THREAD

**Issue by santialbo** [chakra-ui/chakra-ui#3201]
# 🐛 Bug report
**Important**
<details>
<summary>
If you are on a mac, make sure to set the OSX setting to see scrollbars. This will give you the same experience as non-mac users. Click here to see how to do it.
</summary>
<img width="672" alt="104043516-3b088080-51dc-11eb-9e74-c81ed9630224" src="https://user-images.githubusercontent.com/1557563/106257172-7961f000-621c-11eb-8031-95a351a47252.png">
</details>

This is a bit hard to explain. When you use the following:
- `portalZIndex` on the `ChakraProvider`
- `Menu` elements within a `Portal`
A remnant of the menu is rendering at the end of the body (even if the menu being closed), extending the page innecessarily.
In [this codesandbox](https://codesandbox.io/s/damp-cookies-zdber?file=/src/App.tsx) I painted the body in red to see this overextension. You can see how it disappears if you don't use the `portalZIndex` option.
<img width="766" alt="Screenshot 2021-01-29 at 10 24 09" src="https://user-images.githubusercontent.com/1557563/106257689-2ccae480-621d-11eb-8493-2fb0a38114c1.png">

## 💻 Link to reproduction

https://codesandbox.io/s/damp-cookies-zdber?file=/src/App.tsx

## 🧐 Expected behavior

It should work the same way as when not using portalZIndex

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.1.6       |
| Browser          |            |
| Operating System |            |

## 📝 Additional information

- This might be related to @martinpengellyphillips issue in #2586

**Comment by segunadebayo** [comment]
I'm looking into this. The thing to note though is that the menu list and menu items are always rendered in the DOM but hidden when the menu is closed. This is the semantic way to handle the menu-button pattern.

Looking into the issue where the portal z-index container is incorrectly positioned.

**Comment by segunadebayo** [comment]
Resolved in the last release.

**Comment by santialbo** [comment]
Is it possible that the recent usePopper refactor broke this @segunadebayo? I'm seeing this again on 1.4.1
and I'm unable to get a codesandbox to work :(
