### ISSUE TITLE
Form label flickers when used next to a switch

### ISSUE THREAD

**Issue by Gohsato** [chakra-ui/chakra-ui#3206]
# 🐛 Bug report
I came across this issue when I was working on a form with this template: https://chakra-ui.com/docs/form/form-control#sample-usage-for-a-radio-or-checkbox-group

If a switch is rendered next to the Form Control and the switch is pressed, the label flickers.

## 💥 Steps to reproduce

1. Write a component like so:
```
    <Box>
      <Switch />
      <FormControl as="fieldset">
        <FormLabel as="legend">hi</FormLabel>
      </FormControl>
    </Box>
```
2. Click the switch
3. The label flickers

## 💻 Link to reproduction
https://codesandbox.io/s/sharp-framework-un034?file=/src/index.tsx:218-356

**Comment by segunadebayo** [comment]
Hi @Gohsato,

I can't seem to reproduce this issue. What browser, OS, or device did you notice this?

**Comment by Gohsato** [comment]
Hi,
Thanks for the reply!
I'm on Windows 10 + Chrome (Version 88).
I have a colleague who can also reproduce the issue on Ubuntu + Chrome

**Comment by bl-ue** [comment]
I can reproduce as well (macOS 11.2.1 + Chrome 88.0.4324.182)

**Comment by bl-ue** [comment]
No no @stale you're wrong.

/open

**Comment by bl-ue** [comment]
@stale /reopen

**Comment by Gohsato** [comment]
In case anyone else has this bug - I found a hack to stop it from happening.  

Just add this css:
```
fieldset {
  border-width: 1px;
  border-color: transparent;
}
```
