### ISSUE TITLE
Using webkit precommands for Components

### ISSUE THREAD

**Issue by hasanaydins** [chakra-ui/chakra-ui#3211]
Hello I searched but couldnt find.

How can I apply -webkit- commands for components. For example ;

`style={{backdropFilter:"saturate(180%) blur(38px)"}}` is worked just for chrome not working in safari  or ios browsers.

How can I fix it ?

### CodeSandbox
[Test this link in Safari](https://codesandbox.io/s/upbeat-napier-y88iy)

Thanks a lot..

Versions

"@chakra-ui/react": "^1.1.0",
"@emotion/react": "^11.1.4",
"@emotion/styled": "^11.0.0",

**Comment by segunadebayo** [comment]
Hi @hasanaydins,

This is a CSS-related issue but I can help. Kindly use `WebkitBackdropFilter` instead.

Reference: https://caniuse.com/?search=backdrop-filter

**Comment by hasanaydins** [comment]
@segunadebayo Thanks a lot it works !
