### ISSUE TITLE
CheckBox using number as value doesn't check

### ISSUE THREAD

**Issue by HOYOUNG98** [chakra-ui/chakra-ui#3212]
# 🐛 Bug report

When using a number for value  for CheckBox with CheckBoxGroup, the checkbox doesn't check and selected values in onChange seems to repeat. 

## 💥 Steps to reproduce

1. Try clicking on the checkbox. 
2. The box doesn't get checked. Also, the (selected) values seems to overlap.

## 💻 Link to reproduction

Link to CodeSandBox example:

https://codesandbox.io/s/quiet-lake-ef5lz

## 🧐 Expected behavior

I believe using number as value should work the same as working with a string

## 🧭 Possible Solution

Not really sure.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       1.1.6     |
| Browser          |      Safari      |
| Operating System |      MacOS      |

## 📝 Additional information

At first, I thought ReactText type does not include numbers and that was the reason for it. However, ReactText = string | number. I am now running out of approaches. Also, you can see how when number is used, it is changed to string.

**Comment by segunadebayo** [comment]
Yes, this is because we pass the value to the native  `<input type=checkbox />` and this changes the value to a DOMString or string.

We can cast the type to just `string`. For now, kindly use `string` and convert to number at the `onChange` site.

Related: #2931
