### ISSUE TITLE
Cannot explicitly set zIndex for MenuList

### ISSUE THREAD

**Issue by martinpengellyphillips** [chakra-ui/chakra-ui#3213]
# 🐛 Bug report

I need to explicitly set `zIndex` on `MenuList` to overcome an ordering issue in my application. Currently it seems that any passed `zIndex` has no effect as it is not passed to the wrapping popper element. This is similar to #2928  - however, in my case using `Portal` is not an option at present due to #3201.

In the below image, `zIndex={4}` was passed to `MenuList`. 

![chakra-zindex-menulist-bug](https://user-images.githubusercontent.com/214338/106357196-82c28980-62fc-11eb-8268-7d476304608e.jpg)

# 💻 Link to reproduction

See prior https://codesandbox.io/s/elastic-jones-monv9

## 🧐 Expected behavior

`zIndex` is set on the corresponding popper element when passed as a prop to `MenuList`.

**Comment by segunadebayo** [comment]
Resolved in #3210, now available in the latest version

**Comment by kennycrosby** [comment]
@segunadebayo this is fixed if a user explicitly adds the `zIndex` as a prop to `MenuList` but adding the zIndex to `baseStyle` or to a variant does not work. Pointing out that this is also the case with the Tooltip bg, works as an explicitly set prop but NOT as a baseStyle or variant.
