### ISSUE TITLE
[Modal] Top most modal overlay should appear above all other modals

### ISSUE THREAD

**Issue by robertcoopercode** [chakra-ui/chakra-ui#322]
**Describe the bug**
When opening multiple modals, the top most modal's overlay does not appear over other modals found underneath the current modal.
![image](https://user-images.githubusercontent.com/16786990/71657983-1f88b100-2d10-11ea-852a-abeb3cfd0ba5.png)

**Expected Behavior**
The modal overlay of the top most modal should appear above all modals except for the top most modal.
![image](https://user-images.githubusercontent.com/16786990/71657967-0a138700-2d10-11ea-8b06-ef8161d9d977.png)

**To Reproduce**
- Use this template:
- List the steps to reproduce the behavior:
1. Open one modal
2. Open another modal from within the current modal
3. Notice how the top most modal's overlay is still beneath other modals.

**Suggested solution(s)**
We could solve this problem by setting the z-index for both the modal contents and the modal overlay to the same value (e.g. 1300) and then the overlays would stack up according to their order in the DOM. I'm assuming that the order of the added portals will line up with the desired modal overlay order (not sure if it's a safe assumption).

**Desktop (please complete the following information):**
 - MacOS
 - Chrome v79

**Comment by robertcoopercode** [comment]
Bump

**Comment by segunadebayo** [comment]
Hi @robertcoopercode,

Thanks for this idea and the PR as well. We've solved this problem permanently in preparation for the next release.

All modals would naturally stack on top of themselves without needed `zIndex`

**Comment by Frontend-io** [comment]
Just came across this issue. Is this still awaiting publishing?

**Comment by ljosberinn** [comment]
Considering its over 5 months old, and going by the PR linked, this should be included in the current `rc.4` (or any other `rc` too). @Frontend-io - you might need to add `portalZIndex` to `ChakraProvider`.

**Comment by Frontend-io** [comment]
> Considering its over 5 months old, and going by the PR linked, this should be included in the current `rc.4` (or any other `rc` too). @Frontend-io - you might need to add `portalZIndex` to `ChakraProvider`.

Great! I'd try it out. 🙏
