### ISSUE TITLE
Flags for conditional render based on window size

### ISSUE THREAD

**Issue by angelhodar** [chakra-ui/chakra-ui#3220]
# 🚀 Feature request

Flags for component display based on window size (sorry if the funcionality is already implemented, I haven't found a clear solution in the documentation).

## 🧱 Problem Statement / Justification

When setting if a component should be rendered on mobile or not, the display attribute with the breakpoints object syntax seems to be repetitive and a bit weird to get used to.

## ✅ Proposed solution or API

A clean solution would be to add flags for components that has to be rendered in a specific size or group of sizes. I used the Quasar framework for Vue and they have this thing I propose, as seen [here](https://quasar.dev/style/visibility#Window-Width-Related).

For example, if you have a Box component that has a few components inside:

```js
<Box>
   <Components...>
</Box>
```

And you want to show that only on sm screens, people would only have to do this:

```js
<Box sm>
   <Components...>
</Box>

// or

<Box mobileOnly>
   <Components...>
</Box>
```

Or only on certain screens:

```js
<Box display={["sm", "md"]}>
   <Components...>
</Box>
```

## ↩️ Alternatives

I suppose this can be achieved adding this functionality to the custom theme or something like that to create a mapping, but I think the flas is cleaner.

**Comment by segunadebayo** [comment]
Hi @angelhodar, I'd recommend making a `Breakpoint` component that handles this on your end.

Here's a little gist that can help:
https://gist.github.com/waptik/e740355a5cc372c3665f0af92600ccf3

Cheers.
