### ISSUE TITLE
Popover crashes on Maximum update depth exceeded

### ISSUE THREAD

**Issue by cyberduck1** [chakra-ui/chakra-ui#3238]
Package V1.16

Tried to implement Popover by following the exact example from the website
But as soon as I change the content of the PopoverContent I get the next error

```
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

My popover looks like this
```
<Popover isOpen={state.isOpen} onClose={() => setState({ isOpen: false })}>
      <PopoverTrigger>
        <Input
          value={itemToString(state.originalValue)}
          onClick={() => setState({ isOpen: true })}
          readOnly
        />
      </PopoverTrigger>
      <PopoverContent>
        <ul css={styles.popover}>
          {timeSlots.map((item, index) => (
            <li
              css={styles.listItem}
              key={index}
              onClick={() => setState({ originalValue: item, isOpen: false })}
            >
              {item.format(TIME_FORMAT)}
            </li>
          ))}
        </ul>
      </PopoverContent>
    </Popover>
```

I tried without the `isOpen` and `onClose` attr and use the default functionality.

I have noticed that the error I get is happening as soon as I change the `PopoverContent` with any element which has children.
So even this will make the app crash.

```
<PopoverContent>
        <ul css={styles.popover}>
          <li>lala</li>
        </ul>
      </PopoverContent>
```

**Comment by ChasinHues** [comment]
Thanks for reporting the issue @cyberduck1. Could you please provide the missing details from the issue template?

## 💻 Link to reproduction

> Please create a minimal reproduction in CodeSandbox
>
> - JavaScript Template:
>   [JavaScript CodeSandbox template](https://codesandbox.io/s/github/chakra-ui/codesandbox-react-js-template/tree/master)
>
> - TypeScript Template:
>   [TypeScript CodeSandbox template](https://codesandbox.io/s/github/chakra-ui/codesandbox-react-ts-template/tree/master)

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |            |
| Browser          |            |
| Operating System |            |

**Comment by segunadebayo** [comment]
We'll re-open once there's a reproduction.

**Comment by scrawfor** [comment]
I believe I'm encountering this as well. I'm receiving logs of errors being caught by my error boundaries.  It's occurring in every component I have a Chakra Menu and the stack-trace points to popper.js

**Error Boundary**
```
in Menu\n in TimeframeSelector\n in div\n in Styled(div)\n in ForwardRef\n in div\n in Styled(div)\n in Module\n in ErrorBoundary\n
```

**Console Stack Trace**
```
react-dom.profiling.min.js:210 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Gg (react-dom.profiling.min.js:231)
    at yh (react-dom.profiling.min.js:163)
    at fn (react-popper.ts:73)
    at Object.forceUpdate (index.js:184)
    at use-popper.ts:139
```

**Comment by shuent** [comment]
I have same issue when I call dynamic components inside popover content.
