### ISSUE TITLE
[FIrefox] Input Addon overflows container with defined width

### ISSUE THREAD

**Issue by adam4813** [chakra-ui/chakra-ui#3243]
# 🐛 Bug report

When using an InputGroup with addons (right and/or left) on Firefox AND defining a width on its container, the whole input  overflows the container's width by the size of the addons.

It appears the input takes the width of the constraint.

## 💥 Steps to reproduce

Place an InputGroup with an Addon (right or left) and an Input within a container, such as a Stack or a Box, and set a width or max width on that container. The Input will overflow the container's width on Firefox, but will be contained on Chrome. See the `maxWidth` prop on the Stack component in the following code:

```
<Stack spacing={4} maxWidth="200px">
  <InputGroup>
    <InputLeftAddon children="+234" />
    <Input type="tel" placeholder="phone number" />
  </InputGroup>

  {/* If you add the size prop to `InputGroup`, it'll pass it to all its children. */}
  <InputGroup size="sm">
    <InputLeftAddon children="https://" />
    <Input placeholder="mysite" />
    <InputRightAddon children=".com" />
  </InputGroup>
</Stack>
```

## 💻 Link to reproduction

This is reproducible by visiting the docs https://chakra-ui.com/docs/form/input#left-and-right-addons and adding the `maxWidth="200px"` property to the Stack container.

## 🧐 Expected behavior
 
Both Chrome and Firefox should behave the same; either the input should get the containers width, or the whole InputGroup should fit within that width.

## 🧭 Possible Solution

A workaround is to add the `overflow="hidden"` property to the Input component which causes consistent behavior on both Chrome and Firefox.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |    1.2        |
| Browser          |       Firefox (85.0), Chrome (88.0.4324.96)   |
| Operating System |     MacOS X 10.14.6       |

### Firefox
<img src="https://user-images.githubusercontent.com/3011917/106518825-0cf72300-64a0-11eb-8268-841300584757.png">

### Chrome
<img src="https://user-images.githubusercontent.com/3011917/106518890-20a28980-64a0-11eb-9b3d-827f6eec0bcc.png">

**Comment by adam4813** [comment]
Quick follow up Safari and Edge (both on the same MacOS) appears to match Chrome's behavior making Firefox the outlier

**Comment by dodas** [comment]
Thanks for the report! I fixed the bug and it will be hopefully out with the next release.
Cheers!
