### ISSUE TITLE
Enhance layerStyles with paddings and margins

### ISSUE THREAD

**Issue by oschade** [chakra-ui/chakra-ui#3247]
# 🚀 Feature request

Is there a reason why layerStyles does not accept paddings and margins? I think, this would result in more consistent spacing.

## 🧱 Problem Statement / Justification

I would lke to add margins, paddings and maybe heights and widths (not sure, if heights and widths that usefull) to layerstyles in my theme.

**Comment by dodas** [comment]
Hey @oschade.
You can put really any css property inside the `layerStyles` as well as `textStyles`.
I guess you got confused because of the docs that list specific props, right?
> Properties defined in a layer style
> - Color or text color
> - Background color
> - Border width and border color
> - Box shadow
> - Opacity

This is more of a suggestion than a limit. We will improve the docs!

**Comment by oschade** [comment]
Oh, sorry, my fault!
I thought I had tested it...

Thank you!
