### ISSUE TITLE
Make Drawer component swipable

### ISSUE THREAD

**Issue by nephix** [chakra-ui/chakra-ui#325]
**Is your feature request related to a problem? Please describe.**
On mobile devices, users have to click outside of the drawer or a toggle button in order to close a drawer

**Describe the solution you'd like**
On mobile devices, a user should be able to close a drawer by swiping left or right

**Additional context**
Material UI's [Drawer](https://material-ui.com/components/drawers/#swipeable-temporary-drawer) component supports swiping

**Comment by mpash** [comment]
@nephix This would be great to mixin your own swiping package to get this functionality. I don't see a need for the core to support this behavior.


```ts
import { useSwipeable } from 'react-swipeable'

const handlers = useSwipeable({
    onSwipedLeft: () => {
      dispatch(closeSidebar())
    },
  })
```

**Comment by nephix** [comment]
I'm very aware that I can implement it on my own. From a users perspective I have never seen a drawer on mobile that isn't swipeable though. 

That's why I think it makes a lot of sense to have this as a core feature and therefore my suggestion in this ticket.

**Comment by segunadebayo** [comment]
I agree with @nephix. This is a behavior you should compose in your application.

I don't think we're going to integrate this in the near future.

Thanks for bringing this up though.

**Comment by Beetix** [comment]
> @nephix This would be great to mixin your own swiping package to get this functionality. I don't see a need for the core to support this behavior.
> 
> ```ts
> import { useSwipeable } from 'react-swipeable'
> 
> const handlers = useSwipeable({
>     onSwipedLeft: () => {
>       dispatch(closeSidebar())
>     },
>   })
> 
> 
> ....
> 
> <DrawerContent {...handlers} />
> ```

Did you test it? I don't get any event when passing the handlers in `DrawerContent`.

**Comment by aabishkaryal** [comment]
> > @nephix This would be great to mixin your own swiping package to get this functionality. I don't see a need for the core to support this behavior.
> > ```ts
> > import { useSwipeable } from 'react-swipeable'
> > 
> > const handlers = useSwipeable({
> >     onSwipedLeft: () => {
> >       dispatch(closeSidebar())
> >     },
> >   })
> > 
> > 
> > ....
> > 
> > <DrawerContent {...handlers} />
> > ```
> 
> Did you test it? I don't get any event when passing the handlers in `DrawerContent`.

Spread the handlers on DrawerOverlay and it should work. :)

**Comment by amosbastian** [comment]
> > > @nephix This would be great to mixin your own swiping package to get this functionality. I don't see a need for the core to support this behavior.
> > > ```ts
> > > import { useSwipeable } from 'react-swipeable'
> > > 
> > > const handlers = useSwipeable({
> > >     onSwipedLeft: () => {
> > >       dispatch(closeSidebar())
> > >     },
> > >   })
> > > 
> > > 
> > > ....
> > > 
> > > <DrawerContent {...handlers} />
> > > ```
> > 
> > 
> > Did you test it? I don't get any event when passing the handlers in `DrawerContent`.
> 
> Spread the handlers on DrawerOverlay and it should work. :)

It does not work for me.
