### ISSUE TITLE
Codesandbox examples are broken

### ISSUE THREAD

**Issue by dominictwlee** [chakra-ui/chakra-ui#3252]
# 🐛 Bug report
The codesandbox examples are broken due to an old bug involving localStorage on version 1.0.3.

## 💥 Steps to reproduce
Open sandbox examples.

![image](https://user-images.githubusercontent.com/34794189/106619045-1481ff00-6568-11eb-99a1-73679162aeef.png)

## 💻 Link to reproduction
Click on codesandbox example in README

## 🧐 Expected behavior
It shouldn't crash.

## 🧭 Possible Solution
Update default chakra-ui version for codesandbox examples to anything above 1.0.3

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.0.3         |
| Browser          |            |
| Operating System |     Brave Browser 1.19.88      |

## 📝 Additional information

- Screenshots or code
- Notes or link to ideas

**Comment by segunadebayo** [comment]
Hi @dominictwlee, pushed a fix for this. Should work as expected after it's released.
