### ISSUE TITLE
Tooltip `pointer-events: none` seems applied to the wrong container

### ISSUE THREAD

**Issue by matchu** [chakra-ui/chakra-ui#3257]
# 🐛 Bug report

I'm using negative `gutter` to have my tooltip overlap the target element, which looks very nice in my use case!

But this causes a flicker effect when the mouse hovers the overlapping space shared by the tooltip and its target: the mouse exits the target element to enter the tooltip container instead; which dismisses the tooltip, and causes the mouse to re-enter the target; which opens the tooltip, etc.

Examining the HTML, it looks like a fix might already be intended: the Chakra element with `role="tooltip"` already has `pointer-events: none` applied in the CSS, which seems to be in the spirit of resolving this issue.

But this doesn't do a lot when its parent, which in code seems to be named the "positioner" element, doesn't have the same rule applied! The positioner still receives the pointer events, which breaks my use case, and seems to contradict the intent of `pointer-events: none` on its child 😅

## 💥 Steps to reproduce

1. Render a tooltip that overlaps its target, using `gutter={-10}` or similar.
2. Hover over the area where the tooltip and the target overlap.
3. Observe that the tooltip rapidly flickers in and out of its open state.

## 💻 Link to reproduction

https://codesandbox.io/s/kind-paper-625q0

## 🧐 Expected behavior

I expect the tooltip to ignore pointer events—which, in this case, would keep the tooltip target in its hovered state.

## 🧭 Possible Solution

We could apply `pointer-events: none` to the tooltip positioner element, as well. I tried this in the browser devtools and it seemed to work!

This is effectively the workaround I'm using in my app now: I've created a global CSS rule to do this, with `@emotion/react` 😅

```jsx
<Global
  styles={css`
    .chakra-portal [data-popper-placement] {
      pointer-events: none;
    }
  `}
/>
```

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.2.1 |
| Browser          | 85.0 (64-bit) |
| Operating System | Windows 10 |

**Comment by dodas** [comment]
Hey @matchu, thanks for a nice detailed report!
Personally I can't reproduce the flickering issue, but I can definitely see how it could be a problem.

I made a PR that should fix it.
Can you please try if you can reproduce it in [this version of the docs](https://chakra-ui-git-fork-dodas-fix-tooltip-pointer-events.chakra-ui.now.sh/docs/overlay/tooltip)? (examples are editable)

**Comment by matchu** [comment]
Ah yes works as expected when I add `gutter={-12}` to the first example on the page, thank you!!

Regarding the repro, it looks like the browser affects the behavior for me: I just pulled up my repro sandbox in Edge, and I just see the tooltip being _dismissed_ when I hover over the overlapping space, instead of the flicker I see in Firefox. That's definitely a less aggressive failure case, and might explain why the repro didn't work the same for you!

**Comment by matchu** [comment]
Thank you! 💖
