### ISSUE TITLE
Docs: add search

### ISSUE THREAD

**Issue by divyanshu013** [chakra-ui/chakra-ui#326]
Not a critical issue since <kbd>Cmd</kbd> + <kbd>F</kbd> works for most cases but would be great to have a search functionality for the docs. (I've seen some other docs use Algolia for this.)

**Comment by segunadebayo** [comment]
Hi @divyanshu013,

Thanks for raising this issue. At the moment, we're hyper-focused on getting the Typescript release out as soon as possible.

If you don't mind owning this, I'll send you the Algolia script and add it here to you can take a stab at this.

Let me know. Thanks again.

**Comment by divyanshu013** [comment]
Sounds good. I can give it a try.

**Comment by Martian2Lee** [comment]
@divyanshu013 @segunadebayo Thanks for highlighting this issue. Any luck with the search?

**Comment by segunadebayo** [comment]
@Martian2Lee  no progress yet 😅.

I just got the Algolia script for the website, if you'd like to work on it, I'd be happy to send you the script.

Thanks.

**Comment by Martian2Lee** [comment]
@segunadebayo Sure, I would love to have a try.

**Comment by normancapule** [comment]
> @Martian2Lee no progress yet 😅.
> 
> I just got the Algolia script for the website, if you'd like to work on it, I'd be happy to send you the script.
> 
> Thanks.

Hello! Can I also have the Algolia script? Would like to have a try :) No worries if someone already beat me to it.

**Comment by with-heart** [comment]
@segunadebayo! Both @normancapule and @margalit have expressed interest in helping us out with search functionality. Any way you could share your thoughts around search, and the above-mentioned Algolia script as well?

Let's get some discussion going in here so we can finally have first-class search for Chakra! 🎉

**Comment by with-heart** [comment]
Closing this as we have implemented Algolia for the 1.0 website revamp.
