### ISSUE TITLE
Select support multiple and disable some options

### ISSUE THREAD

**Issue by gzponline** [chakra-ui/chakra-ui#3263]
# 🚀 Feature request

if we need support multiple select, so if chakra will support these?
now we use primitive select ,so if we will support build a component support more props such as disabled, remote search same as antd https://ant.design/components/select/ or elementui. https://element.eleme.io/#/en-US/component/select

## ✅ Proposed solution or API

> Please provide code snippets, gists, or links to the ideal design or API

## ↩️ Alternatives

> What alternative solutions have you considered before making this request?
such as https://element.eleme.io/#/en-US/component/select

## 📝 Additional Information

> What resources (links, screenshots, etc.) do you have to assist this effort?
![image](https://user-images.githubusercontent.com/12186221/106708091-46a96480-662d-11eb-8209-b5247e94b787.png)

**Comment by dodas** [comment]
hey @gzponline,

this has been requested several times now.
Please see #1293.

**Comment by shreyansh-zazz** [comment]
Any update on this?
