### ISSUE TITLE
On modal close - scroll to the top of the page behavior is happening

### ISSUE THREAD

**Issue by nicolad** [chakra-ui/chakra-ui#3266]
# 🐛 Bug report

If the scroll position on the page is not the topmost and a modal is opened and then closed, the page is being scrolled to the top.

https://user-images.githubusercontent.com/1477453/106740768-82d7c780-6623-11eb-91dc-4d8352a6203a.mp4

## 💻 Link to reproduction

I tried to reproduce in codesandbox, but it's not reproducible there, only in the real app scenario.

https://codesandbox.io/s/chakra-modal-6h5h8

## 🧐 Expected behavior

To preserve the current position on the page, without jumping to the top.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       1.2.1     |
| Browser          |        Chrome v. 88.0.4324.96    |
| Operating System |   Ubuntu 20.04         |

**Comment by dodas** [comment]
Hey @nicolad,

I couldn't reproduce that behaviour neither, in my project nor in the codesandbox nor in the docs.
You will have to provide a reproduction, otherwise we can't really act upon this.

**Comment by nicolad** [comment]
I am investigating this further and will provide more details or will close the issue.

**Comment by segunadebayo** [comment]
We'll re-open when you provide more details.

**Comment by dbousamra** [comment]
I have this same bug. Any more details?

**Comment by piotr-musialek-skyrise** [comment]
I also had this problem when closing modal, but it scrolled to the button itself, not top of the page and only on Safari (macOS). My guess is the button was receiving focus back which could trigger my div (or page) to scroll. I was searching the web for topics around focus on button and I found https://stackoverflow.com/questions/36167366/remove-focus-from-button-once-clicked. After I changed `onClick` to `onMouseDown` the problem disappeared 🙂  It's a workaround, but I'll take it.

**Comment by sandippakhanna** [comment]
Use this
```
<Drawer
  isOpen={isOpen}
  placement="right"
  onClose={onClose}
  autoFocus={false} <-- add this
  returnFocusOnClose={false} <-- add this also
>
```

**Comment by Yagasaki7K** [comment]
This works! Thanks!

https://github.com/chakra-ui/chakra-ui/issues/3266#issuecomment-1292097053

**Comment by Yagasaki7K** [comment]
> Use this
> 
> ```
> <Drawer
>   isOpen={isOpen}
>   placement="right"
>   onClose={onClose}
>   autoFocus={false} <-- add this
>   returnFocusOnClose={false} <-- add this also
> >
> ```

This works! Thanks!

**Comment by nachoperassidev** [comment]
> Use this
> 
> ```
> <Drawer
>   isOpen={isOpen}
>   placement="right"
>   onClose={onClose}
>   autoFocus={false} <-- add this
>   returnFocusOnClose={false} <-- add this also
> >
> ```

Thank you, hero

**Comment by dorklord23** [comment]
> Use this
> 
> ```
> <Drawer
>   isOpen={isOpen}
>   placement="right"
>   onClose={onClose}
>   autoFocus={false} <-- add this
>   returnFocusOnClose={false} <-- add this also
> >
> ```

Weird, it doesn't work in my case. The page still scrolls to the top after drawer is closed.

**Comment by adedaniel** [comment]
> Use this
> 
> ```
> <Drawer
>   isOpen={isOpen}
>   placement="right"
>   onClose={onClose}
>   autoFocus={false} <-- add this
>   returnFocusOnClose={false} <-- add this also
> >
> ```

This works! Thank you 💯
