### ISSUE TITLE
Td and Th cannot appear as a child of Tbody or Thead

### ISSUE THREAD

**Issue by jack5341** [chakra-ui/chakra-ui#3268]
# 🐛 Bug report

> Provide a brief description of the bug here
When i use Table components of Chakra UI in my console i see:
`<th> cannot appear as a child of <thead>`

## 🧐 Expected behavior

> Tell us what you expect to happen.
Error-free work

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI       |  ^1.1.2   |
| Browser          |    Firefox - 85.0    |
| Operating System |    Linux-Mint    |

## 📝 Additional information

- Screenshots or code
https://imgyukle.com/i/H9oPbP
https://imgyukle.com/i/H9ooQq
https://imgyukle.com/i/H9kdDN

**Comment by with-heart** [comment]
This isn't a Chakra error, it's an html error. Tables are made of rows (`tr`) which contain cells (`th`/`td`). You need to wrap your cells in a row.
