### ISSUE TITLE
Portal elements is hidden behind Modal and Drawer

### ISSUE THREAD

**Issue by vemundeldegard** [chakra-ui/chakra-ui#3269]
# 🐛 Bug report

When you want to have Popover in a Portal, and also have it inside Modal or Drawer, the PopoverContent is not shown. It is hidden behind the Modal or Drawer, since the Portal div is the last element added to document.body. 

Also, there is no info in Upgrading to v1 about usePortal being discontinued..

## 💻 Link to reproduction

I Created a CodeSandbox :dancing_men: 
https://codesandbox.io/s/boring-vaughan-2rbbb?fontsize=14&hidenavigation=1&theme=dark

## 🧐 Expected behavior

Portal should be the first div in document.body? Or it should be possible to specify zIndex? 

## 📝 Additional information

![Skjermbilde 2021-02-03 kl  14 49 18](https://user-images.githubusercontent.com/36489034/106755944-01863200-662f-11eb-9ca4-97d3ffa1b448.png)

**Comment by ljosberinn** [comment]
please pass `portalZIndex={40}` (or a different number that works for your app) to `ChakraProvider` :)

![image](https://user-images.githubusercontent.com/29307652/107120478-25937e80-688e-11eb-9349-54d5f55c0fa0.png)

![image](https://user-images.githubusercontent.com/29307652/107120482-2af0c900-688e-11eb-822d-851f2eb38252.png)

![image](https://user-images.githubusercontent.com/29307652/107120488-2d532300-688e-11eb-94d6-12e1ccfb8c66.png)
