### ISSUE TITLE
Custom variants not working on Input component

### ISSUE THREAD

**Issue by Luisetelo** [chakra-ui/chakra-ui#3272]
# 🐛 Bug report

Custom variants are not working on Input components. Overwriting already existing variants is not working either.

## 💥 Steps to reproduce

**This bug is visual**

1. Open the reproduction link
2. You'll see a red input on the right
3. That input has a border declared in the theme.js inside the variant "border-black" key but it's not working

## 💻 Link to reproduction

https://codesandbox.io/s/sweet-rosalind-u76f2?file=/src/App.js

![image](https://user-images.githubusercontent.com/8354589/106780711-8df11e80-6648-11eb-9325-c6c65bcaa637.png)

## 🧐 Expected behavior

To see a black border on the input:

![image](https://user-images.githubusercontent.com/8354589/106779775-9dbc3300-6647-11eb-836b-7ff040b939af.png)

## 🧭 Possible Solution

Not a clue, sorry 😞 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |          1.0.0  |
| Browser          |         Chrome 88.0.4324.96   |
| Operating System |          macOS Catalina 10.15.7  |

**Comment by segunadebayo** [comment]
Hey @Luisetelo. This is happening because the Input component is a "composite component", meaning, it is composed of other parts "field" and "addon" (for LeftAddon, and RightAddon).

Here's the modified version that works:
```jsx
const theme = extendTheme({
  components: {
    Input: {
      variants: {
        'border-black': {
          field: {
            background: '000',
            border: '3px solid',
          }
        },
      },
    },
  },
});
```

**Comment by Luisetelo** [comment]
Thank you very much for the quick response @segunadebayo! Will keep an eye on composite componentes for similar issues ;)
