### ISSUE TITLE
PinInput not support ref property

### ISSUE THREAD

**Issue by Otoru** [chakra-ui/chakra-ui#3279]
# 🐛 Bug report

PinInput not support ref property.

## 💥 Steps to reproduce

Create project with react, typescript and chakra-ui and try pass a Ref for a PinInput.

## 🧐 Expected behavior

PinInput accept a Ref.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.1.6       |
| Browser          | Google Chorme  |
| Operating System | Mac OS |

## 📝 Additional information

```ts
<PinInput ref={forwardedRef} colorScheme="pink" otp onChange={setValue}>
  <PinInputField />
  <PinInputField />
  <PinInputField />
  <PinInputField />
  <PinInputField />
</PinInput>
```

```
(JSX attribute) ref: React.ForwardedRef<HTMLInputElement>
Type '{ children: Element[]; ref: ForwardedRef<HTMLInputElement>; colorScheme: string; otp: true' is not assignable to type 'IntrinsicAttributes & PinInputProps & { children?: ReactNode; }'.
  Property 'ref' does not exist on type 'IntrinsicAttributes & PinInputProps & { children?: ReactNode; }'.
```

**Comment by with-heart** [comment]
There's nothing to forward the ref to. `PinInput` renders a context and it's children, but no element of its own.

**Comment by Otoru** [comment]
So for any validation and/or rule that depends on the use of Refs do I need to create a secondary component just to store the value read in the PinInput?

**Comment by with-heart** [comment]
Not familiar with ref-based form libs so I'm not too sure. How would you normally manage four  separate inputs via refs?

**Comment by with-heart** [comment]
I guess maybe a better question to help me understand is "what would passing a ref to `PinInput` allow you to do?" I'm not sure I understand how that would work.

**Comment by Otoru** [comment]
One example is [react-hook-form](https://react-hook-form.com/get-started).
My pain arose when trying to use it in conjunction with [yup](https://www.npmjs.com/package/yup) to validate forms.

This [tutorial](https://dev.to/dialaeke/using-chakra-ui-react-hook-forms-and-yup-for-react-form-validation-3i4k) is a good example of what I try to do.

**Comment by with-heart** [comment]
You could pass `register` via `ref` and an array-keyed `name` to each `PinInputField`, which would return the array of values like this: https://codesandbox.io/s/elastic-jang-xyp9p?file=/src/App.tsx

**Comment by Otoru** [comment]
It's not like I would have thought, but it will work!

Thanks @with-heart , Your way of thinking will help me a lot :D

**Comment by with-heart** [comment]
@TimKolberger might know of a better way to handle that. I think he's used `react-hook-form`. Let's see if he has any ideas :D

**Comment by TimKolberger** [comment]
You can use the [Controller component of react-hook-form](https://react-hook-form.com/api#Controller) to add components your form, which manage their state in react, and not in the DOM.
Please have a look at this [codesandbox](https://codesandbox.io/s/chakra-ui-react-hook-form-hmgl1?file=/src/App.tsx) for an example implementation of NumberInput and PinInput.

**Comment by Otoru** [comment]
I had gone straight through the use of controllers. This will help me, thanks!

**Comment by MikeMajara** [comment]
@TimKolberger this bit here works fine in v6, but not in v7. Would you happen to know which would be the equivalent in react-hook-form v7, and why this one does not work?

`<Input name="name" ref={register} />`

**Comment by with-heart** [comment]
@MikeMajara Reproduce in CodeSandbox please
