### ISSUE TITLE
Cannot override global default style (Heading component)

### ISSUE THREAD

**Issue by binhxn** [chakra-ui/chakra-ui#3287]
# 🐛 Bug report

Hello, I want to override global default styles to HTML elements when extending the theme object, so that when I use the `as` prop, the overridden default styles would be referenced correctly. For example:

```jsx
// theme
const theme = extendTheme({
  styles: {
    global: {
      h3: {
        fontSize: "50px",
        fontWeight: "300"
      }
    }
  }
});

// usage
<Heading as="h3">Hello world</Heading>
```

The `fontSize` and `fontWeight` styles above are not applied, but when I add `color` it works fine. I wasn't sure if this is a bug or intentional implementation detail.

## 💻 Link to reproduction

[JavaScript CodeSandbox repro](https://codesandbox.io/s/solitary-cdn-7owv0?file=/src/App.js)

## 🧐 Expected behavior

New `fontSize` and `fontWeight` styles to be correctly applied on `h3` element when:
1. Extending theme global styles
2. Setting `as="h3"` on a Heading component

**Comment by santialbo** [comment]
If you want to use the `Heading` component you need to customize the `Heading` component on the theme.
```
const theme = extendTheme({
  components: {
    Heading: {
      baseStyle: {
        fontWeight: "300"
      },
      sizes: {
        xl: {
          h: "56px",
          fontSize: "lg",
          px: "32px",
        },
      },
    },
  },
});
```
If you don't want to do that, then use the `Text` component instead
```
<Text as="h3">Hello world</Text>
```
See updated codesandbox https://codesandbox.io/s/old-river-uwpql?file=/src/App.js

**Comment by segunadebayo** [comment]
Thanks for chiming in @santialbo.

**Comment by afroguy16** [comment]
> If you want to use the `Heading` component you need to customize the `Heading` component on the theme.
> 
> ```js
> const theme = extendTheme({
>   components: {
>     Heading: {
>       baseStyle: {
>         fontWeight: "300"
>       },
>       sizes: {
>         // default size is md
>         xl: {
>           fontSize: "50px",
>         },
>       },
>     },
>   },
> });
> ```
> 
> If you don't want to do that, then use the `Text` component instead
> 
> ```js
> <Text as="h3">Hello world</Text>
> ```
> 
> See updated codesandbox https://codesandbox.io/s/old-river-uwpql?file=/src/App.js

Hello santialbo,

Yes this is possible, but it doesn't solve the above issue raised, which IMO is a valid issue, because I just faced the same problem. I want to set a default style for h1 globally, so any time I want to use h1, there is a default font size, and I don't have to set the size every-time.

**Comment by afroguy16** [comment]
The last resort would be to use a variant

**Comment by israelperez** [comment]
I tried adding global style to no avail, not sure why this wouldn't work. seem variants are the only way to get this done. 
> styles: {
>         global: {
>                 h5: {
>                        fontSize: '28px',
>                        fontWeight: 600,
>                        marginBottom: '12px'
>                }
>         }      
> }

**Comment by maxskewes** [comment]
If there is a font with only one weight setting, I'm finding what you set the weight to has no bearing; if used as Heading, it will be bold; if used as Text, it will not.

**Comment by keithburgie** [comment]
I've struggled with the `Heading` component as well and landed here today because I couldn't get it to use a responsive font size. Here are a bunch of "H" components for anyone who would prefer to use headings this way...

```typescript
/**
 * Headings.tsx
 * 
 * Example usage:
 * --------------------
   import { H1 } from "./components/Headings"
   return ( <H1>Your Heading</H1> )
   
 * Example styling:
   --------------------
   const theme = extendTheme({
     components: {
       H1: {
         baseStyle: {
           fontSize: {
             base: "lg",
             md: "3xl",
           },
         },
       }
     }
     styles: {
       global: {
         h2: {
           fontSize: "md"
           fontWeight: "normal"
         }
       }
     }
   })
 */

import {
  chakra,
  forwardRef,
  omitThemingProps,
  ThemingProps,
  useStyleConfig,
  HTMLChakraProps,
} from "@chakra-ui/system"
import { cx, __DEV__ } from "@chakra-ui/utils"

interface HeadingProps extends ThemingProps<"Heading"> {}
export interface H1Props extends HTMLChakraProps<"h1">, HeadingProps {}
export interface H2Props extends HTMLChakraProps<"h2">, HeadingProps {}
export interface H3Props extends HTMLChakraProps<"h3">, HeadingProps {}
export interface H4Props extends HTMLChakraProps<"h4">, HeadingProps {}
export interface H5Props extends HTMLChakraProps<"h5">, HeadingProps {}
export interface H6Props extends HTMLChakraProps<"h6">, HeadingProps {}

const headingBaseStyles = {
  fontFamily: "heading",
  fontWeight: "bold",
}

export const H1 = forwardRef<H1Props, "h1">((props, ref) => {
  const styles = useStyleConfig("H1", props)
  const { className, ...rest } = omitThemingProps(props)

  return (
    <chakra.h1
      ref={ref}
      className={cx("chakra-heading", props.className)}
      {...headingBaseStyles}
      {...rest}
      __css={styles}
    />
  )
})

export const H2 = forwardRef<H2Props, "h2">((props, ref) => {
  const styles = useStyleConfig("H2", props)
  const { className, ...rest } = omitThemingProps(props)

  return (
    <chakra.h2
      ref={ref}
      className={cx("chakra-heading", props.className)}
      {...headingBaseStyles}
      {...rest}
      __css={styles}
    />
  )
})

export const H3 = forwardRef<H3Props, "h3">((props, ref) => {
  const styles = useStyleConfig("H3", props)
  const { className, ...rest } = omitThemingProps(props)

  return (
    <chakra.h3
      ref={ref}
      className={cx("chakra-heading", props.className)}
      {...headingBaseStyles}
      {...rest}
      __css={styles}
    />
  )
})

export const H4 = forwardRef<H4Props, "h4">((props, ref) => {
  const styles = useStyleConfig("H4", props)
  const { className, ...rest } = omitThemingProps(props)

  return (
    <chakra.h4
      ref={ref}
      className={cx("chakra-heading", props.className)}
      {...headingBaseStyles}
      {...rest}
      __css={styles}
    />
  )
})

export const H5 = forwardRef<H5Props, "h5">((props, ref) => {
  const styles = useStyleConfig("H5", props)
  const { className, ...rest } = omitThemingProps(props)

  return (
    <chakra.h5
      ref={ref}
      className={cx("chakra-heading", props.className)}
      {...headingBaseStyles}
      {...rest}
      __css={styles}
    />
  )
})

export const H6 = forwardRef<H6Props, "h6">((props, ref) => {
  const styles = useStyleConfig("H6", props)
  const { className, ...rest } = omitThemingProps(props)

  return (
    <chakra.h6
      ref={ref}
      className={cx("chakra-heading", props.className)}
      {...headingBaseStyles}
      {...rest}
      __css={styles}
    />
  )
})

if (__DEV__) H1.displayName = "H1"
if (__DEV__) H2.displayName = "H2"
if (__DEV__) H3.displayName = "H3"
if (__DEV__) H4.displayName = "H4"
if (__DEV__) H5.displayName = "H5"
if (__DEV__) H6.displayName = "H6"

```

**Comment by advename** [comment]
This is a valid reason and issue. Using `<Heading as="h1">Lorem</Heading>` should yield a h1 element without any default `size` prop. Headings should remain consistent throughout a UI and only have different sizes, when explicitly defined, not the other way around... .

**Comment by dlibis** [comment]
> This is a valid reason and issue. Using `<Heading as="h1">Lorem</Heading>` should yield a h1 element without any default `size` prop. Headings should remain consistent throughout a UI and only have different sizes, when explicitly defined, not the other way around... .
> 
> I had even to go that far and disable in our project with the following Eslint rule:
> 
> ```js
> rules:{
>     'no-restricted-syntax': [
>       'error',
>       {
>         message : "Don't use Chakra's <Heading/> component. It creates an inconsistent UI with different heading sizes. Use <Text as='h1'/> instead.",
>         selector: 'ImportDeclaration[source.value="@chakra-ui/react"] > ImportSpecifier[imported.name="Heading"]',
>       },
>     ],
> }
> ```
> 
> The other alternative would be creating a custom `size` named `h1`, but then you'd have to double specify props `<Heading as="h1" size="h1>`.
> 
> Please reconsider this issue.

it possible to do what you suggested when using chakra Text component, like so
`                        <Text as="h3" textStyle="h4">
                           text
                        </Text>`

**Comment by wnharper** [comment]
This is still an issue in V3. The example they give in their docs does not work:

```
import { createSystem, defineRecipe } from "@chakra-ui/react"
import { defaultConfig } from "@chakra-ui/react"

const headingRecipe = defineRecipe({
  base: {
    fontWeight: "normal",
    textStyle: "4xl", // <---- this does not work
  },
})

const system = createSystem(defaultConfig, {
  theme: {
    recipes: { heading: headingRecipe },
  },
})
```

For now, the only solution I found was to change the XL size variant (which is the default size) like so:

```
export const headingRecipe = defineRecipe({
  variants: {
    size: {
      xl: { textStyle: "5xl" },
    },
  },
});
```
