### ISSUE TITLE
[Tooltip] Tooltip does not show on a disabled button

### ISSUE THREAD

**Issue by SofienM** [chakra-ui/chakra-ui#3289]
# 🐛 Bug report

> Provide a brief description of the bug here

Tooltip does not show on a disabled button
## 💻 Link to reproduction
https://codesandbox.io/s/infallible-58e4e-58e4e

## 🧐 Expected behavior

The tooltip shows off

## 🧭 Possible Solution

Workaround is to add a `<div>` wrapper around the button.

```
       <Tooltip
          label="Not enough shares"
          hasArrow
          aria-label="Not enough shares"
          placement="top"
        >
          <div>
             <Button alignSelf="start" isDisabled onClick={() => {}}>
               Submit
             </Button>
          </div>
        </Tooltip>
```

**Comment by santialbo** [comment]
Related #2849

**Comment by TimKolberger** [comment]
Closing this as duplicate of #2849 

Please see this especially this comment https://github.com/chakra-ui/chakra-ui/issues/2849#issuecomment-749043599

> There is a `shouldWrapChildren` prop on Tooltip, thanks to which you don't have to wrap it manually.
