### ISSUE TITLE
Request to add global tooltip subscriptions

### ISSUE THREAD

**Issue by lkleuver** [chakra-ui/chakra-ui#329]
**Is your feature request related to a problem? Please describe.**
Tooltips don't hide when triggering another tooltip

**Describe the solution you'd like**
Hide tooltip when a new one is active

**Additional context**
https://github.com/reach/reach-ui/blob/master/packages/tooltip/src/index.js#L179

I'd be happy to send a PR for this

**Comment by segunadebayo** [comment]
Hi @lkleuver, thanks for this request.

We've currently solved this in the `dev-ts` branch and will be out in the next release.

Thanks again for your suggestion.
