### ISSUE TITLE
Button BaseStyle not overriding for paddings

### ISSUE THREAD

**Issue by iwatakeshi** [chakra-ui/chakra-ui#3293]
# 🐛 Bug report

> Provide a brief description of the bug here

Hi, this is similar to #2015. However, this time `paddingX` and `px` do not override the button styles.

## 💥 Steps to reproduce

> Clear and concise reproduction steps are important for us to be able to triage
> your issue in a timely manner

See the `_app.js` file in the repro

## 💻 Link to reproduction

> Please create a minimal reproduction in CodeSandbox
>
> - JavaScript Template:
>   [JavaScript CodeSandbox template](https://codesandbox.io/s/github/chakra-ui/codesandbox-react-js-template/tree/master)
>
> - TypeScript Template:
>   [TypeScript CodeSandbox template](https://codesandbox.io/s/github/chakra-ui/codesandbox-react-ts-template/tree/master)

https://codesandbox.io/s/chakra-button-basestyle-repro-spjid?file=/pages/_app.js

## 🧐 Expected behavior

> Tell us what you expect to happen.

## 🧭 Possible Solution

> Not compulsory, but suggesting a fix would be great!

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.2.1          |
| Browser          |  Brave        |
| Operating System |  MacOS          |

## 📝 Additional information

- Screenshots or code
- Notes or link to ideas

It might be good to check what other props are not being applied, but so far in the repro, the padding in the `x` direction do not work.

**Comment by with-heart** [comment]
Hi @iwatakeshi! I'm seeing the correct `padding-left` and `padding-right` values in all browsers.

**Comment by iwatakeshi** [comment]
@with-heart !! Wow, it does work... it didn't work when I first created the repro. Hmm, I wonder why I'm still having issues on my local machine then. I've tried different browsers and I don't see fast-refresh showing the changes either. My `Button` setup looks like the following:
```ts
Button: {
      baseStyle: {
        fontSize: ['14px', null, null, '16px'],
        letterSpacing: '0.03em',
        borderRadius: '0',
        px: '100px',
        py: 4,
        // paddingY: '1rem',
        // paddingX: '2rem',
        transition:
          'background-color 400ms ease, border-color 400ms ease, transform 400ms ease',
      },
      variants: {
        primary: (props) => ({
          fontSize: 'md',
          color: 'white',
          borderWidth: '3px',
          borderColor: mode('blue.500', 'red.500')(props),
          borderStyle: 'solid',
          backgroundColor: mode('blue.500', 'red.500')(props),
          shadow: 'md',
          _hover: {
            shadow: 'xl',
            transform: `scale(1.02)`,
            color: mode('blue.500', 'red.500')(props),
            backgroundColor: 'white',
            borderColor: mode('blue.500', 'red.500')(props),
          },
        }),
      },
    },
```

It works when I add the padding to the `variants` but not to the `baseStyle`

**Comment by with-heart** [comment]
Huh, that's really strange. It seems to only work if you have both `px` and `paddingX` defined. If I only define one of them, it stops working.

**Comment by iwatakeshi** [comment]
@with-heart You're right! That would for in the meantime. Thank you!

**Comment by mtt87** [comment]
I think this is a more extended issue, for example also `bg` and `backgroundColor` only work if both of them are specified.
https://codesandbox.io/s/chakra-button-basestyle-repro-forked-80gxg?file=/pages/_app.js

On a separate note, it seems to be impossible to also set `minWidth`

```jsx
const theme = extendTheme({
  components: {
    Button: {
      baseStyle: {
        // bg: "#ff2200", // enable this and it will work
        backgroundColor: "#ff2200",
        minWidth: "200 px"
      }
    }
  }
});
```

**Comment by mtt87** [comment]
Trying to see if I can find the issue, so far I can exclude this
https://github.com/chakra-ui/chakra-ui/blob/b77049f161256b67fbf5afec99d90636a814f053/packages/react/tests/extend-theme.test.tsx#L45
I tried locally
```jsx
  it("should merge component baseStyle object with a function result", () => {
    const testColor = "papayawhip"
    const minWidth = '200px'
    const override = {
      components: {
        Button: {
          baseStyle: () => ({
            bg: testColor,
            minWidth,
          }),
        },
      },
    }

    const customTheme = extendTheme(override)

    const { baseStyle, defaultProps } = customTheme.components.Button
    const baseStyles = baseStyle()

    expect(baseStyles.bg).toBe(testColor)
    expect(baseStyles.minWidth).toBe(minWidth)

    // should have more properties from the default theme
    expect(Object.keys(baseStyles).length).toBeGreaterThan(1)
  })
```

And it works fine, the `baseStyle` contains `minWidth`
```js
    {
      lineHeight: '1.2',
      borderRadius: 'md',
      fontWeight: 'semibold',
      _focus: { boxShadow: 'outline' },
      _disabled: { opacity: 0.4, cursor: 'not-allowed', boxShadow: 'none' },
      _hover: { _disabled: { bg: 'initial' } },
      bg: 'papayawhip',
      minWidth: '200px'
    }
```

So I suspect it's something at the `Button` level that is not taking `baseStyle`  into consideration.

**Comment by dodas** [comment]
The `Button` component has its paddings defined in the `sizes` object (as it's different for each size), not in the `baseStyle`.
You should override styles in `sizes.<x>` (`sizes.md` for the default size) and you can use either `px` or `paddingX`, both work.

For example:
```ts
const theme = extendTheme({
  components: {
    Button: {
      sizes: {
        md: {
          px: "100px"
        }
      }
    }
  }
});
```
https://codesandbox.io/s/chakra-button-basestyle-repro-forked-b22n6?file=/pages/_app.js:65-206

The fact that you can override it when you use both `px` and `paddingX` at once in `baseStyle` is interesting, but that's probably a different discussion :D

**Comment by tawnyzhao** [comment]
@mtt87 
I just had your issue, I realized it is also due to similar reasons as the padding issue here. For buttons, the background color is defined in the `variants` object, which is by default uses `solid`. If you override the bg through the variant, this issue no longer occurs. I think this could be more clear in the docs.

**Comment by oyatek** [comment]
@dodas thanks for the hint about "sizes" I've been trying to style Button without any success for quite a long time

**Comment by giedrius-timinskis** [comment]
Facing the same issue with the Button. 
Looks like whatever property was used to define the style will need to be used to override it, i.e. per the Button example:
https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/button.ts#L168

Example:
⛔️  Doesn't work
```
extendTheme({
  components: {
    Button: {
      baseStyles: {
        height: 'auto'
      }
    }
  }
});
```
✅  Works
```
extendTheme({
  components: {
    Button: {
      baseStyles: {
        h: 'auto'
      }
    }
  }
});
```

**Comment by Kevinrp22** [comment]
> El `Button`componente tiene sus rellenos definidos en el `sizes`objeto (ya que es diferente para cada tamaño), no en el `baseStyle`. Debe anular los estilos en `sizes.<x>`( `sizes.md`para el tamaño predeterminado) y puede usar `px`o `paddingX`, ambos funcionan.
> 
> Por ejemplo:
> 
> ```ts
> const theme = extendTheme({
>   components: {
>     Button: {
>       sizes: {
>         md: {
>           px: "100px"
>         }
>       }
>     }
>   }
> });
> ```
> 
> https://codesandbox.io/s/chakra-button-basestyle-repro-forked-b22n6?file=/pages/_app.js:65-206
> 
> El hecho de que pueda anularlo cuando usa ambos `px`y `paddingX`al mismo tiempo `baseStyle`es interesante, pero probablemente sea una discusión diferente: D

Hello, I am trying to apply the code but including different rules in different measures.

❌ Why this doesn't work? note: only the 'md' works

```ts
extendTheme({
  components: {
    Button: {
      sizes: {
        base: { height: "100px" },
        sm: { height: "200px" },
        md: { height: "300px" },
      },
    },
  },
});
```

✅ I was trying another way, this one works

```ts
extendTheme({
  components: {
    Button: {
      sizes: {
        md: {
          height: {
            base: "100px",
            sm: "200px",
            md: "300px",
          },
        },
      },
    },
  },
});
```

The last one works but is not semantically correct? You are defining the measure 'md' and within the object another measure is defined again
