### ISSUE TITLE
Content-Security-Policy cannot be used with secure instructions

### ISSUE THREAD

**Issue by TheThirdRace** [chakra-ui/chakra-ui#3294]
# 🐛 Bug report

The `Content-Security-Policy` header allows you to give browsers directives on how to handle stuff securely for your site.

> For example, you can restrict all scripts to be only executed if they're directly hosted on your site.
>
> With this, a script on cdnjs.com wouldn't be executed by the browser. No other host than your own site host would be allowed.
>
> All this severely restricts the attack surface of your site.

**More info on this:**
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
- https://content-security-policy.com/

**Bug**
It's actually impossible to set secure policies using Chakra because of the use of inline scripts and inline styles.

The only inline script I found is the `<ColorModeScript>`. A workaround is easy to implement in this case, all you need to do is add a props to the component on which we can pass the secure `nonce` token. I provide the modified code below.

The bigger problem is about EmotionJs. It litters the DOM with inline styles. While the severity of inline styles attacks are less than inline scripts, it's still a vulnerability. Unfortunately, we don't have access to the underlying structure of EmotionJs, so we personally can't add a `nonce` ourselves.

## 💥 Steps to reproduce

Add the `Content-Security-Policy` header on a website with this value:

```text
"base-uri; child-src; connect-src 'self' *; default-src; font-src; form-action; frame-ancestors 'self' *; frame-src 'self'; img-src 'self' * data:; manifest-src 'self'; media-src 'self'; object-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline';"
```

Make sure your site use the `<ColorModeScript>` component to test the result in Dev Tools.

## 💻 Link to reproduction

Not really possible to show this in CodeSandbox

## 🧐 Expected behavior

A `nonce` we provided being added to inline **script**, which will allow the script to be executed and not be blocked by the browser.

A `nonce` we provided being added to inline **style**, which will allow the styles to be applied and not be blocked by the browser.

## 🧭 Possible Solution

For EmotionJs, it's supposedly a matter of passing the `nonce` to a cache. See https://emotion.sh/docs/@emotion/cache#nonce

For `ColorModeScript`, here is the code **as-is** from Chakra (1.2.1) that add the `nonce`. It's literally 2 small changes.

```typescript
import * as React from "react"
import { ColorMode } from "./color-mode-provider"

type Mode = ColorMode | "system" | undefined

function setScript(initialValue: Mode) {
  const mql = window.matchMedia("(prefers-color-scheme: dark)")
  const systemPreference = mql.matches ? "dark" : "light"

  let persistedPreference: Mode

  try {
    persistedPreference = localStorage.getItem("chakra-ui-color-mode") as Mode
  } catch (error) {
    console.log(
      "Chakra UI: localStorage is not available. Color mode persistence might not work as expected",
    )
  }

  const isInStorage = typeof persistedPreference === "string"

  let colorMode: Mode

  if (isInStorage) {
    colorMode = persistedPreference
  } else {
    colorMode = initialValue === "system" ? systemPreference : initialValue
  }

  if (colorMode) {
    const root = document.documentElement
    root.style.setProperty("--chakra-ui-color-mode", colorMode)
  }
}

interface ColorModeScriptProps {
  initialColorMode?: Mode
  nonce?: string
}

/**
 * Script to add to the root of your application when using localStorage,
 * to help prevent flash of color mode that can happen during page load.
 */
export const ColorModeScript = (props: ColorModeScriptProps) => {
  const { initialColorMode = "light" } = props
  const html = `(${String(setScript)})('${initialColorMode}')`
  return <script nonce={props.nonce} dangerouslySetInnerHTML={{ __html: html }} />
}
```

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.2.1         |
| Browser          |    Chrome        |
| Operating System |  Windows          |

**Comment by TimKolberger** [comment]
Thank you for bringing this up @TheThirdRace.

The emotion part can be solved in the userland implementation, because chakra does not use a emotion cache provider.
Please see this example implementation:

```jsx
import createCache from '@emotion/cache'

function MyEmotionProvider({ nonce, children }) {
  const cache = createCache({ nonce })
  return <CacheProvider value={cache} children={children} />
}


// ... 

<ChakraProvider>
  <MyEmotionProvider nonce="your-nonce">
    <MyApp />
  </MyEmotionProvider>
</ChakraProvider>
```

The `ColorModeScript` needs the an update in our codebase to support this, as you already showed 👍 
Would you care to contribute this by opening a PR?

**Comment by TheThirdRace** [comment]
@TimKolberger 
I wouldn't mind dabbling in making my first PR for Chakra, teams members have been very helpful on discord and all, but I need a few pointers.

The whole github flow is a bit new to me, so I'd appreciate if you point me in the right direction.

This is what I think I need to do:

1. Clone the whole repo on my computer (not sure which branch I should start from though)
2. Create a new branch (I guess there's a naming convention?)
3. Make the change
4. Push the change on my branch
5. Go to github and create a PR from my branch to the appropriate branch (develop?)
6. ???
7. Profit

Something like that?

**Comment by TheThirdRace** [comment]
@TimKolberger 
I had a bit of trouble making it work, the console errors aren't very explicit as to which styles are problematic exactly...

Once I fixed the NextJs noise (Next/Image & 2 inline style tags), I was able to make Emotion work with the cache.

Although, I had to reverse the Emotion provider with the Chakra provider because `<ChakraProvider>` include a css reset functionality and another style tag I don't remember for what.

Thus the exact solution was this:

```typescript
// EmotionCacheProvider.tsx

import createCache from '@emotion/cache'
import { CacheProvider } from '@emotion/react'
import React, { PropsWithChildren, ReactElement } from 'react'

type EmotionCacheProviderProps = PropsWithChildren<unknown> & {
	nonce: string
}

export const EmotionCacheProvider = ({ nonce, children }: EmotionCacheProviderProps): ReactElement => {
	const cache = createCache({ key: 'contentsecuritypolicy', nonce })
	return <CacheProvider value={cache}>{children}</CacheProvider>
}
```

```typescript
// _app.tsx

import { ChakraProvider } from '@chakra-ui/react'
import { AppProps } from 'next/app'
import { ReactElement } from 'react'
import { Page } from '../component/container/Page'
import { EmotionCacheProvider } from '../component/presentational/EmotionCacheProvider'
import theme from '../theme'

function MyApp({ Component, pageProps }: AppProps): ReactElement {
	return (
		<EmotionCacheProvider nonce='12345'>
			<ChakraProvider theme={theme}>
				<Page>
					{/* eslint-disable-next-line react/jsx-props-no-spreading */}
					<Component {...pageProps} />
				</Page>
			</ChakraProvider>
		</EmotionCacheProvider>
	)
}
```

For those using js, it's practically the same, just use `.js` as extension instead

**Comment by TimKolberger** [comment]
That's awesome @TheThirdRace 
Thanks for sharing the example implementation. 

You can follow our [contribution guide](https://github.com/chakra-ui/chakra-ui/blob/main/CONTRIBUTING.md).

**Comment by TheThirdRace** [comment]
I've reopened this issue until I either create that PR for the `<ColorModeScript>` or someone else does.

**Comment by mattiasw** [comment]
I'm not sure a nonce is going to solve this issue. Please tell me if I'm wrong in my thinking here. If you're statically building your site (as I assume many are when using Next.js, I know we are) you can't have a nonce since it has to be a new one for each page load. Instead you have to use the `<hash-algorithm>-<base64-value>` method of allowing inline scripts/styles in the CSP which unfortunately is not as easy as the nonce.

**Comment by TheThirdRace** [comment]
@mattiasw 
You're right, using SSG with NextJs will not create a new `nonce` on every request. It's correct to say I would need to use a hash at this point and it's a pain...

Ideally, the script shouldn't be inline to begin with. I extracted it into a new file in my `public/` folder at the moment. No `nonce` or `hash` required. But this ain't the easiest thing to maintain...

Reading different threads over at NextJs Github, it looks like they're working on something that would allow to generate a `nonce` for SSG pages. So at some point the `nonce` should work on every request and be the way to go.

While waiting for a more permanent solution, I would much prefer to reduce as much as possible the attack surface of my site. While far from being ideal and wouldn't be 100% secure, a fixed  `nonce`  would certainly be a thousand times more secure than a blanket `unsafe-inline`. At least you'd have to be specifically targeted to be breached, unlike with `unsafe-inline`... 

And without `unsafe-inline`, I can't get my site running with Chakra, mostly because of styling, but also because of the ColorModeScript. Still haven't figured out how to pass a `nonce` to Emotion's  `CacheProvider` ... Fun times !!! ;)
