### ISSUE TITLE
Request to support library in VueJS

### ISSUE THREAD

**Issue by ShahAnuj2610** [chakra-ui/chakra-ui#330]
Since this library has achieved great popularity, extending it to VueJS would be a cherry on the cream. I would be more than happy to start a project and contribute to the same.

**Comment by segunadebayo** [comment]
Hi @ShahAnuj2610. Thanks for your suggestion about VueJS.

I know a friend who's already working on this and will soon make it public. I'd advise you to collaborate with him once he does so we can create a more solid Vue.js system.

Here's a link to the repo: https://github.com/codebender828/kiwi-ui/tree/master/packages/kiwi-core/src

**Comment by atilkan** [comment]
@segunadebayo The link is broken. Do you have knowledge about it? 
We would like to work on Vue port, and it would be better if you involve in a way.
