### ISSUE TITLE
Can we have MenuArrow component similar to PopoverArrow

### ISSUE THREAD

**Issue by oahmaro** [chakra-ui/chakra-ui#3304]
# 🚀 Feature request
Can we have an arrow pointing the the trigger of the menu similar to what we have with Popover component.

## 🧱 Problem Statement / Justification
This would allow to have an arrow pointing to a trigger such as Avatar component. a common case used for avatar on Nav for authenticated users.

**Comment by joaoGabriel55** [comment]
I got it @oahmaro. I can try to solve your demand.

**Comment by joaoGabriel55** [comment]
Hello @oahmaro almost done...
