### ISSUE TITLE
No typings for custom breakpoints

### ISSUE THREAD

**Issue by ViaxCo** [chakra-ui/chakra-ui#3305]
# 🐛 Bug report

> Provide a brief description of the bug here
Custom breakpoints added to the theme work as expected when used in a project with the object syntax, but Typescript gives error.

## 💥 Steps to reproduce

> Clear and concise reproduction steps are important for us to be able to triage
> your issue in a timely manner

1. Create custom breakpoint(s): 
```
const breakpoints = createBreakpoints({
  sm: "54.0625em",
  md: "63.5625em",
  lg: "80em",
  xl: "90em",
  mobileM: "23.4375em",
  tablet: "35.4375em",
});
```
2. Use it in a component: 
```
mt={{ base: "130px", tablet: "152px" }}
```

## 💻 Link to reproduction

> Please create a minimal reproduction in CodeSandbox
>
> - JavaScript Template:
>   [JavaScript CodeSandbox template](https://codesandbox.io/s/github/chakra-ui/codesandbox-react-js-template/tree/master)
>
> - TypeScript Template:
>   [TypeScript CodeSandbox template](https://codesandbox.io/s/github/chakra-ui/codesandbox-react-ts-template/tree/master)

## 🧐 Expected behavior

> Tell us what you expect to happen.

## 🧭 Possible Solution

> Not compulsory, but suggesting a fix would be great!

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |            |
| Browser          |            |
| Operating System |            |

## 📝 Additional information

- Screenshots or code
- Notes or link to ideas

This is the Typescript error I get: 
```
Type '{ base: "130px"; tablet: string; }' is not assignable to type 'number | (string & {}) | "px" | "-moz-initial" | "inherit" | "initial" | "revert" | "unset" | "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10" | "12" | "14" | "16" | "20" | ... 17 more ... | undefined'.
  Object literal may only specify known properties, and 'tablet' does not exist in type 'ResponsiveArray<number | (string & {}) | "px" | "-moz-initial" | "inherit" | "initial" | "revert" | "unset" | "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10" | "12" | "14" | "16" | ... 15 more ... | "auto"> | Partial<...>'.ts(2322)
```
![Screenshot 2021-02-06 at 21 46 54](https://user-images.githubusercontent.com/43748536/107129314-d6b50b80-68c4-11eb-8da0-096d905fc8fe.png)

**Comment by cloudratha** [comment]
@TimKolberger I see your fix got merged, however I'm still experiencing issues with custom breakpoint keys. I've confirmed `@chakra-ui/styled-system` is on `v1.7.0`

```jsx
const breakpoints = createBreakpoints({
  xs: "23em",
  sm: "30em",
  md: "48em",
  lg: "62em",
  xl: "80em",
  "2xl": "96em",
});

export default extendTheme({ breakpoints });

...

<HStack spacing={{ base: "6", xs: "10" }}>
```

```
Object literal may only specify known properties, and 'xs' does not exist in type 'ResponsiveArray<number | (string & {}) | "px" | ...
```

Is there something additional I need to do to satisfy the above?

**Comment by TimKolberger** [comment]
The changes are not released yet. When [this PR is merged](https://github.com/chakra-ui/chakra-ui/pull/3312) a new version will be published with all mentioned changes. We aim to release every friday 🚀

**Comment by cloudratha** [comment]
Ah, I misread the release PR! thanks!
