### ISSUE TITLE
[Button] Skip not-allowed cursor when button is in loading state

### ISSUE THREAD

**Issue by ProsperDevelopment** [chakra-ui/chakra-ui#331]
**Is your feature request related to a problem? Please describe.**
When button is in loading state the mouse cursor changes to a forbidden sign.

**Describe the solution you'd like**
I would like the cursor not to change - I think its enough indication with the greying out, the spinner and no pointer cursor. In my opinion the not-allowed cursor makes to much noise and is a too strong symbol for a loading state.

**Comment by tioluwani94** [comment]
@ProsperDevelopment, if you don't want to have the `not-allowed` cursor on your button you can override it using the emotion's `css`. 

Example

`
<Button
    variantColor="green"
    disabled
    css={css`
      &:disabled {
        cursor: pointer!important;
      }
    `}
  >
    Hello
  </Button>
`

**Comment by ProsperDevelopment** [comment]
Well of course you could hard code whatever with !important :) But can i make it global in the theme? 

This was more of a change request of the default behaviour.

For example in windows I get a red forbidden sign which becomes quite eye catching for such a trivial state.

**Comment by ProsperDevelopment** [comment]
Okey I have seen this behaviour on other sites as well now so I guess it's not random over design.

But this raise the need of more theming options for the components, now you need to wrap/override default design instead of using the theme.
