### ISSUE TITLE
Type of default theme is not accurate because of typecast

### ISSUE THREAD

**Issue by heikomat** [chakra-ui/chakra-ui#3314]
# 🚀 Feature request

Use `DefaultChakraTheme` as type for `theme`

## 🧱 Problem Statement / Justification

- The `theme` variable is defined as `= defaultTheme` [here](https://github.com/chakra-ui/chakra-ui/blob/b77049f161256b67fbf5afec99d90636a814f053/packages/theme/src/index.ts#L21)
- `DefaultChakraTheme` is by definition the exact type of `defaultTheme`, and therefore also the exact type of `theme`
- Instead of using that exact type, `theme` is typecasted to the way less precise `ChakraTheme` [here](https://github.com/chakra-ui/chakra-ui/blob/b77049f161256b67fbf5afec99d90636a814f053/packages/theme/src/index.ts#L21)

This makes using values from the default theme within definitions for `extendTheme` harder, because the types are more broad. For example: currently `theme.space[4]` has the type `string | number | RecursiveObject<string | number>`, instead of `string`. So i can't use `theme.space[4]` as value for anything that only accepts strings.

## ✅ Proposed solution or API

The typecast in the following line should either be removed or corrected to `DefaultChakraTheme`:
https://github.com/chakra-ui/chakra-ui/blob/b77049f161256b67fbf5afec99d90636a814f053/packages/theme/src/index.ts#L21

## ↩️ Alternatives

none

**Comment by TimKolberger** [comment]
Thank you @heikomat for this issue. 

The typecasting was added to ensure that the default theme of Chakra UI is of type `ChakraTheme`. But this type check could be done on a variable which is not exported, to keep the explicit type definitions of `theme`.

There is always room for improvement for the theme types.
