### ISSUE TITLE
Tooltip arrow misalignes when there's not enough space

### ISSUE THREAD

**Issue by deebov** [chakra-ui/chakra-ui#3315]
# 🐛 Bug report

When there's not enough space to show the tooltip, the arrow displays in the wrong place. 

![image](https://user-images.githubusercontent.com/28673719/107216276-5dd1c300-6a2e-11eb-8088-407d9d55c407.png)

## 💥 Steps to reproduce

1. Go to the [With Arrow](https://chakra-ui.com/docs/overlay/tooltip#with-arrow) section
2. Scroll down so the Search icon is at the very bottom but is visible.
3. Hover the Search icons _couple of times_ and you should see the issue

**Comment by joaoGabriel55** [comment]
I got this bug too. I can work on this...

**Comment by deebov** [comment]
> I got this bug too. I can work on this...

would be really great, man!

**Comment by joaoGabriel55** [comment]
Hello @deebov. I tried to simulate this bug at chakra-ui's storybook, and I didn't have this bug. Are you already tried to use `placement="bottom"` or `placement="top"` to fix/set the Tooltip position?

**Comment by deebov** [comment]
yes, as you can see in our storybook

<img width="1195" alt="Screen Shot 2021-02-08 at 22 19 59" src="https://user-images.githubusercontent.com/28673719/107256873-de5ae880-6a5b-11eb-85fe-1588e2dc7269.png">

**Comment by joaoGabriel55** [comment]
Hello @deebov, I tested the Tooltip component at local StoryBook on my machine. Where you got these "Controls"?

**Comment by deebov** [comment]
it's a private SB that we use internally. I tried to run the chakra's SB but having some issues with `node gyp`. Have you tried to decreare the height viewport? e.g. by moving up the console or making the browser window height smaller? here's an example:
<img width="755" alt="Screen Shot 2021-02-09 at 10 23 45" src="https://user-images.githubusercontent.com/28673719/107319690-22cc9f80-6ac1-11eb-8f55-47be7f3831a1.png">

**Comment by joaoGabriel55** [comment]
I did something similar on Chakra's website (I think same thing that you did) at "With arrow" topic

**Comment by deebov** [comment]
> Now I got your reported bug on Chakra's storybook, doing the same thing that you showed above.

glad that it worked on your end!

**Comment by groenborg** [comment]
Popperjs will continue to generate unplanned work, I suggest moving to react laag, that is a nice lib 😄 

https://github.com/everweij/react-laag @

**Comment by steven-wilson-crl** [comment]
Just piling on here.  We are getting this issue as well, and it makes a rather embarrassing user experience.   Appreciate any work going into this!!

**Comment by steven-wilson-crl** [comment]
Hey folks, I think maybe this PR (https://github.com/chakra-ui/chakra-ui/pull/3477) fixed the issue??  Its just not been released yet.

**Comment by steven-wilson-crl** [comment]
> 
> 
> Hey folks, I think maybe this PR (#3477) fixed the issue?? Its just not been released yet. I was going to look into fixing this, forked the repo, ran storybook and wasn't able to duplicated it. Then found that PR.

Negative on the above PR being the fix.  It just got released, and it still puts the arrow on the wrong side of the box as described in the original post.  It must be Monday :(

**Comment by segunadebayo** [comment]
Yes, #3477 fixed the issue.

There's an upcoming PR #3583 that seeks to eliminate the issue permanently. In the meantime, this is already fixed.
