### ISSUE TITLE
RadioButtonGroup swallows Tab key event

### ISSUE THREAD

**Issue by gumbadumba** [chakra-ui/chakra-ui#332]
Tabbing out of the chakra RadioButtonGroup does not work. This can be verified with the example at https://chakra-ui.com/radio.

Looking at https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/RadioButtonGroup/index.js, it appears as if the `handleKeyDown` method only handles arrow presses and always calls `event.preventDefault()`:

```
const handleKeyDown = event => {
    // Disable page scrolling while navigating with keys
    event.preventDefault();

    const count = focusableValues.length;
    let enabledCheckedIndex = focusableValues.indexOf(_value);

    if (enabledCheckedIndex === -1) {
      enabledCheckedIndex = 0;
    }

    switch (event.key) {
      case "ArrowRight":
      case "ArrowDown": {
        const nextIndex = (enabledCheckedIndex + 1) % count;
        updateIndex(nextIndex);
        break;
      }
      case "ArrowLeft":
      case "ArrowUp": {
        const nextIndex = (enabledCheckedIndex - 1 + count) % count;
        updateIndex(nextIndex);
        break;
      }
      default:
        break;
    }
  };
```

As a consequence, once inside the radio group, you can not tab out of it.

**Comment by Hagendorn** [comment]
I can provide a fix for this bug

**Comment by Hagendorn** [comment]
Here is a PR to fix this bug: https://github.com/chakra-ui/chakra-ui/pull/333
