### ISSUE TITLE
No tab is selected when using autoFocus, therefore the user sees no content

### ISSUE THREAD

**Issue by EllaSharakanski** [chakra-ui/chakra-ui#3323]
# 🐛 Bug report

When using tabs, and a `Tab` component has the `autoFocus` property, it causes a situation where no tab is selected, so the user doesn't see any content at all.

## 💥 Steps to reproduce

1. Use the reproduction link (it's just two simple tabs. The only unusual thing is `autoFocus` on the first tab).
2. Refresh the browser inside of codesandbox.

Alternatively, you can just go to https://chakra-ui.com/docs/disclosure/tabs and add `autoFocus` to the first `Tab` component in the first example.

## 💻 Link to reproduction

https://codesandbox.io/s/frosty-flower-qqzr3?file=/src/index.tsx

## 🧐 Expected behavior

The content of the first tab (which is "Tab Content 1") should be visible because the first tab is selected.

## 🧭 Possible Solution

I don't have a solution at the moment, but after a lot of debugging, I do have a good understanding of where this bug comes from:

Take a look at https://github.com/chakra-ui/chakra-ui/blob/main/packages/tabs/src/use-tabs.ts
Seems like the `autoFocus` property is triggering a focus on the tab before everything is ready, which causes no tab to be selected, so the page becomes empty (In the dev tools I see that `selectedIndex = -1` in the tab's context).

This is how it goes:
1. When the UI is still loading, the `ref` on line 280 is still `null`.
2. For this reason, the `index` on line 298 is `-1`.
3. At first, `selectedIndex` is 0 (the default).

Happy flow:
4. At some point, `ref` is populated with the actual element.
5. Then, `index` becomes the correct index of the current tab (so 0, 1, etc.)
6. Then, for the tab with index 0, we get `isSelected = true` on line 303, and this tab becomes selected 👍 .

Bug:
4. While `index` is still `-1`, something triggers `focus()` on tab 0 (in this case, it is the `autoFocus` prop).
5. Therefore, according to line 315, `setSelectedIndex(index)` is executed, so `selectedIndex` becomes `-1`.
6. Next, line 303 is executed again, but this time both `index = -1` and `selectedIndex = -1` so we get `isSelected = true` for all of the tabs.
7. When `ref` is finally populated with the element, `index` becomes the correct index of the tab (so it's not `-1` anymore).
8. Then, since `selectedIndex` is still `-1`, we get `isSelected = false` for all tabs on line 303, so no tab is selected = bug 👎 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.3      |
| Browser          |       Chrome     |
| Operating System |     Mac       |

But this doesn't seem related.

## 📝 Additional information

When the bug happens, there is no visible content:
<img width="462" alt="Screen Shot 2021-02-09 at 2 32 49" src="https://user-images.githubusercontent.com/61652966/107299011-32c38f80-6a7f-11eb-9edc-e0ca5bde6c74.png">

The expected behavior - to see the content of the first tab:
<img width="466" alt="Screen Shot 2021-02-09 at 2 32 56" src="https://user-images.githubusercontent.com/61652966/107299064-4bcc4080-6a7f-11eb-928e-79e352148eae.png">

Additionally, if you are wondering why I need `autoFocus` on the first tab: It's actually because of this bug - https://github.com/chakra-ui/chakra-ui/issues/3324. I wanted to avoid having the modal scroll down, so I wanted to force the first `Tab` to be focused instead of the `TabPanel`.

**Comment by segunadebayo** [comment]
Hi @EllaSharakanski, this isn't the intended design/API for the Tabs component even though I understand what you mean. 

To make a tab active, please use the `index` or `defaultIndex` instead.  Having multiple ways to control the active/selected index might lead to unexpected bugs in the future.

**Comment by EllaSharakanski** [comment]
@segunadebayo I wasn't trying to control the active tab, I just wanted it to be focused initially when the page loads. Why should it cause such a weird behavior that takes hours to debug?
You can maybe just avoid setting the selected index to `-1` in `onFocus`, because it should never be `-1`.

**Comment by EllaSharakanski** [comment]
@segunadebayo Also note that this bug can happen for many reasons. You cannot assume that nothing will set the focus of tabs before they are "ready". For example if tabs are used in a modal, then the `focus-lock` of the modal will set the focus.
