### ISSUE TITLE
Installation error with NextJs: unable to resolve dependency tree

### ISSUE THREAD

**Issue by DiegoMcDipster** [chakra-ui/chakra-ui#3327]
# 🐛 Bug report
Chakra-ui fails to install with fresh install of NextJs.  Error message: ERESOLVE unable to resolve dependency tree
**Note, this worked fine last week.  I vaguely recall getting a new version of npm installed between then and now.

> Provide a brief description of the bug here
1. npx create-next-app app-name
2. cd app-name
3. npm i @chakra-ui/react @emotion/react @emotion/styled framer-motion

## 🧐 Expected behavior

It should install without errors

## 🧭 Possible Solution
The workaround i'm using is: 
npm i @chakra-ui/react @emotion/react @emotion/styled framer-motion --legacy-peer-deps

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       1.3.2     |
| NextJs          |      10.0.6      |
| React |      17.0.1      |
| npm  |      7.5.2      |
| node  |     14.15.4      |

## 📝 Additional information

293 verbose node v14.15.4
294 verbose npm  v7.5.2
295 error code ERESOLVE
296 error ERESOLVE unable to resolve dependency tree
297 error
298 error Found: [1mreact[22m@[1m17.0.1[22m[2m[22m
298 error [2mnode_modules/react[22m
298 error   [35mpeer[39m [1mreact[22m@"[1m^16.9.0 || ^17[22m" from [1m@next/react-dev-overlay[22m@[1m10.0.6[22m[2m[22m
298 error   [2mnode_modules/@next/react-dev-overlay[22m
298 error     [1m@next/react-dev-overlay[22m@"[1m10.0.6[22m" from [1mnext[22m@[1m10.0.6[22m[2m[22m
298 error     [2mnode_modules/next[22m
298 error       [1mnext[22m@"[1m10.0.6[22m" from the root project
298 error   [35mpeer[39m [1mreact[22m@"[1m^16.6.0 || ^17[22m" from [1mnext[22m@[1m10.0.6[22m[2m[22m
298 error   [2mnode_modules/next[22m
298 error     [1mnext[22m@"[1m10.0.6[22m" from the root project
298 error   55 more (react-dom, styled-jsx, use-subscription, ...)
298 error
298 error Could not resolve dependency:
298 error [35mpeer[39m [1mreact[22m@"[1m^16.8.0[22m" from [1mreact-remove-scroll[22m@[1m2.4.0[22m[2m[22m
298 error [2mnode_modules/@chakra-ui/modal/node_modules/react-remove-scroll[22m
298 error   [1mreact-remove-scroll[22m@"[1m2.4.0[22m" from [1m@chakra-ui/modal[22m@[1m1.5.1[22m[2m[22m
298 error   [2mnode_modules/@chakra-ui/modal[22m
298 error     [1m@chakra-ui/modal[22m@"[1m1.5.1[22m" from [1m@chakra-ui/react[22m@[1m1.3.2[22m[2m[22m
298 error     [2mnode_modules/@chakra-ui/react[22m
298 error       [1m@chakra-ui/react[22m@"[1m*[22m" from the root project
298 error
298 error Fix the upstream dependency conflict, or retry
298 error this command with --force, or --legacy-peer-deps
298 error to accept an incorrect (and potentially broken) dependency resolution.

**Comment by afermon** [comment]
Same as in chakra-ui/chakra-ui#2820
