### ISSUE TITLE
Support Tooltip Within AvatarGroup

### ISSUE THREAD

**Issue by igoldny** [chakra-ui/chakra-ui#3329]
# 🚀 Feature request
Support Tooltip Within AvatarGroup
```
<AvatarGroup size="md" max={2}>
  <Tooltip label="Christian Nwamba">
    <Avatar name="Christian Nwamba" />
  </Tooltip>
  <Tooltip label="Ryan Florence">
    <Avatar name="Ryan Florence" />
  </Tooltip>
  <Tooltip label="Segun Adebayo">
    <Avatar name="Segun Adebayo" />
  </Tooltip>
  <Tooltip label="Kent Dodds">
    <Avatar name="Kent Dodds" />
  </Tooltip>
  <Tooltip label="Prosper Otemuyiwa">
    <Avatar name="Prosper Otemuyiwa" />
  </Tooltip>
</AvatarGroup>
```

## 🧱 Problem Statement / Justification
when using Avatar with initials only you would want to display the user full name.
one way to do it is using Tooltip but it's currently broken.
![image](https://user-images.githubusercontent.com/480868/107360200-46eaa980-6ade-11eb-8c75-b372c7b2a8af.png)

you won't get avatars overlapping.
before:
![image](https://user-images.githubusercontent.com/480868/107360442-9cbf5180-6ade-11eb-9a0a-fdc36531ab33.png)
after: 
![image](https://user-images.githubusercontent.com/480868/107360397-8ca77200-6ade-11eb-8e35-4cd53ebc75c1.png)

## ✅ Proposed solution or API
one way to fix the problem is using deep mapping in [avatar group children mapping](https://github.com/chakra-ui/chakra-ui/blob/main/packages/avatar/src/avatar-group.tsx#L86)
using [react-children-utilities](https://github.com/fernandopasik/react-children-utilities/blob/master/docs/deep-map.md)

## ↩️ Alternatives
another option is passing styles from avatar group to avatar using context

WDYT? any other suggestions?

**Comment by santialbo** [comment]
I had a similar problem, my workaround was to create my own TooltipAvatar component and pass the properties to the inner Avatar element.

See codesandbox https://codesandbox.io/s/quiet-hooks-gefoy?file=/src/App.tsx

**Comment by igoldny** [comment]
sweet! @santialbo thnx for the example, looks like a great workaround.
but for a long-term solution would you keep it as it is or find a way to make it work?

**Comment by Akifcan** [comment]
```
 <AvatarGroup size='md' max={5} position='relative' paddingBlock={3}>
            {employees.length > 0 &&
              employees?.map((employee: IEmployee, i: number) => (
                <Tooltip key={employee.id} label={employee.name} textTransform='capitalize'>
                  <Avatar position='absolute' left={i * 7} bg='white' name={employee.name} src={employee.path}></Avatar>
                </Tooltip>
              ))}
          </AvatarGroup>
```

**Comment by juac08** [comment]
Put in a Box Avatar component, it will stack
