### ISSUE TITLE
Would it be possible to add the isLazy prop to Tooltip?

### ISSUE THREAD

**Issue by joaomlap** [chakra-ui/chakra-ui#3333]
First of all I would like to say thank you, incredible work.

# 🚀 Feature request

I would like Tooltip to have the prop isLazy.

## 🧱 Problem Statement / Justification

I am using Tooltip in a situation where it's heavily called (an array of arrays). The problem is that the tooltip is taking valuable rendering time when actually I just need to show it later after the page is rendered.

I am not sure of the possibility of this but since Popover already has it I was thinking that maybe there's a way to replicate the same behaviour.

## ✅ Proposed solution or API

Provided above.

Thank you very much.

**Comment by segunadebayo** [comment]
Hi @joaomlap,

Thanks for sharing your ideas. At the moment, the tooltip doesn't show up in the DOM until it's open and that's very similar to the `isLazy` behavior in the `Popover` component. Adding `isLazy` to the Tooltip component would have no effect on its rendering (I just tested this).

I'd recommend optimizing your code a bit more, or simplifying the UX of your product so you don't show too much information in the tooltip. Tooltips should be used to provide "supplementary" information.
