### ISSUE TITLE
Request to add shadows API

### ISSUE THREAD

**Issue by divyanshu013** [chakra-ui/chakra-ui#334]
**Is your feature request related to a problem? Please describe.**
I find the colors API pretty usefule. For example referring to colors simply like `gray.50`, etc. I was wondering if we can leverage something similar for shadows? For example, say you are creating a card and want to add some elevation, it would be great if we can utilize something similar.

**Describe the solution you'd like**
I don't have the exact API in mind but tailwind has something similar https://tailwindcss.com/docs/box-shadow/#app.

**Describe alternatives you've considered**
Currently writing this manually as CSS.

**Additional context**

Attaching screenshot from tailwind

![image](https://user-images.githubusercontent.com/6682655/71977633-4cbcee00-323f-11ea-9414-e3f777c2368a.png)

**Comment by aaronmcadam** [comment]
@divyanshu013 This already exists here: https://github.com/chakra-ui/chakra-ui/blob/52230c5ac62301993ae6ac47ad658987e5822581/packages/chakra-ui/src/theme/theme.js#L8

Example:

```js
<Box background="white" boxShadow="sm" margin={4}>
  <Text>content</Text>
</Box>
```

**Comment by divyanshu013** [comment]
Thanks, I missed that in the docs. Closing this issue.
