### ISSUE TITLE
The Select component can't hide the overflow text in iOS/Safari

### ISSUE THREAD

**Issue by syauqy** [chakra-ui/chakra-ui#3342]
# 🐛 Bug report

> Provide a brief description of the bug here

Currently, I'm using Chakra Select component for my project. I've found a problem when I tested my app on the Safari browser. As you can see in the pictures below, The Select component on the Safari works differently since it makes a new line for the overflow text. I did several methods to work around this like ellipsis but it didn't work.

![Safari](https://user-images.githubusercontent.com/3627108/107523951-d92aa480-6be7-11eb-8f8f-794c3425c269.png)
![Chrome](https://user-images.githubusercontent.com/3627108/107524154-11ca7e00-6be8-11eb-9dc7-688e6865b03f.png)

## 💥 Steps to reproduce

> Clear and concise reproduction steps are important for us to be able to triage
> your issue in a timely manner

I found this issue only happened in Safari so far. The Chrome result is good as I expected.
1. Open a project with a Select component from Chakra, or just go to the Chakra-UI docs in Select component section using Safari browser. https://chakra-ui.com/docs/form/select
2. Do some edit on the editable example. Edit the options list with some long text, in my case I wrote a full name of addresses.
3. Click on the Select component, and choose an option with long text.
4. See the result.

## 🧐 Expected behavior

> Tell us what you expect to happen.

I think it should hiding the overflow text in Safari as it is also working on Chrome.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.0      |
| Browser          |      Safari      |
| Operating System |    macOS Catalina 10.15.7     |

**Comment by dustinlarimer** [comment]
@syauqy seems this is still an issue. I was able to get around it by adding the following:

```jsx
<Select
  display="flex"
  maxHeight={10}
  lineHeight={10}
>
  {/* */}
</Select>
```
