### ISSUE TITLE
Badge elements for icons and icon buttons

### ISSUE THREAD

**Issue by brennanfife** [chakra-ui/chakra-ui#3346]
# 🚀 Feature request

> Please describe your request in one or two sentences.
- Attaching badge elements to icons and / or icon buttons

## 🧱 Problem Statement / Justification

> Please provide valid reason(s) why this should added to Chakra UI.

- Currently, users of Chakra can attach badges to avatar elements. It would also be convenient to have this feature for other elements such as icon buttons and / or icons. For example, this would come in handy for a notification component, that when clicked, opens a popup of all the unread notifications a user has.

- As it stands now, a potential workaround may look something like the following
Avatar as="button" aria-label="notifications" icon={FiBell} children={hasUnreadNotifications ? AvatarBadge boxSize="1rem" bg="red.500" : null} 

## ✅ Proposed solution or API

> Please provide code snippets, gists, or links to the ideal design or API

- If considered, I don't see why this couldn't be similar to the way Material UI implements this feature

Badge colorScheme="red"
  Icon 
Badge

Additional properties may include badgeContent, badgeSize, and badgePosition

## 📝 Additional Information

> What resources (links, screenshots, etc.) do you have to assist this effort?

- Reference from Material UI https://material-ui.com/components/badges/

**Comment by segunadebayo** [comment]
Hi @brennanfife,

After much thought, we won't be adding support for this. Adding these props `badgeContent, badgeSize, and badgePosition` feels like there's a "badge" component longing to be created from those.

I'd recommend creating a component that wraps the IconButton and provide this behavior.

Thanks

**Comment by oncet** [comment]
> Hi @brennanfife,
> 
> After much thought, we won't be adding support for this. Adding these props `badgeContent, badgeSize, and badgePosition` feels like there's a "badge" component longing to be created from those.
> 
> I'd recommend creating a component that wraps the IconButton and provide this behavior.
> 
> Thanks

Why not have a child `ButtonBadge` component for `Button` and `IconButton`? Similar as `Avatar` and `AvatarBadge`.
