### ISSUE TITLE
feat: Add support for overriding defaultProps for Tooltip (and possibly more?)

### ISSUE THREAD

**Issue by KoenBrouwer** [chakra-ui/chakra-ui#3347]
## 🧱 Problem Statement / Justification

We're using the (very nice) [Customizing Single Components](https://chakra-ui.com/docs/theming/customize-theme#customizing-single-components) approach to customize our theme for various components. 
I would like to configure the Tooltip component to use some props by default: `placement = top` and `hasArrow = true`.

From what I see in https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/tooltip.ts overriding these props is currently not supported.

# 🚀 Feature request

Add support for overriding defaultProps for the Tooltip component.

## ✅ Proposed solution or API

Basically I would like to end up doing this:

```typescript
extendTheme({
  components: {
    Tooltip: {
      defaultProps: {
        placement: "top",
        hasArrow: true
      }
    }
  },
});
```

## ↩️ Alternatives

We now have created our own `CustomTooltip` component as a wrapper around the Tooltip component that does nothing else than returning a tooltip with these options:

```typescript
import { Tooltip } from "@chakra-ui/react";

export const CustomTooltip = (props) => <Tooltip placement={"top"} hasArrow {...props} />
```

## 📝 Additional Information

None, so far. Except that I'm now wondering if there's a solution for "theming" defaults (placement, duration, isClosable) for the Toast. 🤔

**Comment by santialbo** [comment]
This has been discusse before in #1424

Another alternative you have (the one I'm using in the meantime) is doing the following:

```tsx
import { Tooltip } from "@chakra-ui/react";

Tooltip.defaultProps = {
  hasArrow: true;
} as any;
```

**Comment by KoenBrouwer** [comment]
Right, not the cleanest workaround but it does its job for now. Thanks a lot @santialbo! 👍🏻

**Comment by KoenBrouwer** [comment]
Just to answer my own question: no there doesn't seem to be a way to set the defaults through Chakra UI, but creating a custom hook as a wrapper around useToast that sets the defaults seems to be a solution. 
Inspired by this tweet: https://twitter.com/Frontend_io/status/1366178544284561410

**Comment by segunadebayo** [comment]
As discussed here: #1424. This is a feature we're careful to add because it can easily get abused.

I can't guarantee when this will happen but we're looking into it. In the meantime, please consider wrapping components or hooks as suggested.
