### ISSUE TITLE
Can't resolve react

### ISSUE THREAD

**Issue by Thatseasy** [chakra-ui/chakra-ui#3348]
I installed Chakra multiple times in React aswell as Next.js using the Chakra docs, it throws this Internal Error when I want to run dev:

wait  - compiling...
error - ../../../../node_modules/@emotion/react/dist/emotion-react.browser.esm.js:1:0
Module not found: Can't resolve 'react'
null
error

**Comment by with-heart** [comment]
Create a reproduction in CodeSandbox like the issue template you deleted asked you to do. This isn't enough information for us to help you.

**Comment by Thatseasy** [comment]
aight

Mark Chandler <notifications@github.com> schrieb am Mi., 10. Feb. 2021,
19:31:

**Comment by emelens** [comment]
I have similar issue. It looks like chakra does not like react 17

````JSON
  "dependencies": {
    "@chakra-ui/core": "^0.8.0",
    "@emotion/core": "^11.0.0",
    "@emotion/styled": "^11.1.5",
    "emotion-theming": "^11.0.0",
    "next": "^10.0.6",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
  "devDependencies": {
    "@types/node": "^14.14.25",
    "@types/react": "^17.0.1",
    "@types/react-dom": "^17.0.0",
    "typescript": "^4.1.5"
  }
````

Error
````
warning "@chakra-ui/core > toasted-notes@3.2.0" has incorrect peer dependency "react@^16.8.4".
warning "@chakra-ui/core > toasted-notes@3.2.0" has incorrect peer dependency "react-dom@^16.8.4".
warning "@chakra-ui/core > use-dark-mode@2.3.1" has incorrect peer dependency "react@^16.8.0".
warning "@chakra-ui/core > @reach/auto-id@0.10.2" has incorrect peer dependency "react@^16.8.0".
warning "@chakra-ui/core > @reach/auto-id@0.10.2" has incorrect peer dependency "react-dom@^16.8.0".
warning "@chakra-ui/core > toasted-notes > @reach/alert@0.1.5" has incorrect peer dependency "react@^16.8.0".
warning "@chakra-ui/core > toasted-notes > @reach/alert@0.1.5" has incorrect peer dependency "react-dom@^16.8.0".
warning "@chakra-ui/core > use-dark-mode > @use-it/event-listener@0.1.6" has incorrect peer dependency "react@^16.8.0".
warning "@chakra-ui/core > @reach/auto-id > @reach/utils@0.10.5" has incorrect peer dependency "react@^16.8.0".
warning "@chakra-ui/core > @reach/auto-id > @reach/utils@0.10.5" has incorrect peer dependency "react-dom@^16.8.0".
warning "@chakra-ui/core > toasted-notes > @reach/alert > @reach/visually-hidden@0.1.4" has incorrect peer dependency "react@^16.8.0".
warning "@chakra-ui/core > toasted-notes > @reach/alert > @reach/visually-hidden@0.1.4" has incorrect peer dependency "react-dom@^16.8.0".
warning "@chakra-ui/core > toasted-notes > @reach/alert > @reach/component-component@0.1.3" has unmet peer dependency "prop-types@^15.6.2".
warning "@chakra-ui/core > toasted-notes > @reach/alert > @reach/component-component@0.1.3" has incorrect peer dependency "react@^16.4.0".
warning "@chakra-ui/core > toasted-notes > @reach/alert > @reach/component-component@0.1.3" has incorrect peer dependency "react-dom@^16.4.0".
warning "@emotion/styled > @emotion/babel-plugin@11.2.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "@emotion/styled > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.12.13" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @chakra-ui/core@0.8.0" has incorrect peer dependency "@emotion/core@10.x".
warning " > @chakra-ui/core@0.8.0" has incorrect peer dependency "@emotion/styled@10.x".
warning " > @chakra-ui/core@0.8.0" has incorrect peer dependency "emotion-theming@10.x".
warning " > @emotion/styled@11.1.5" has unmet peer dependency "@emotion/react@^11.0.0-rc.0".

````

**Comment by heikomat** [comment]
@emelens `@chakra-ui/core: ^0.8.0` is outdated, and is afaik supported up to react 16 and emotion 10.
`@chakra-ui/react: ^1.0.0` (or the current one, 1.6.1) works fine with react 17 and emotion 11

**Comment by emelens** [comment]
@heikomat Noted. Thank you.
Not sure why yarn downloaded outdated version when I typed `yarn add @chakra-ui/core @emotion/styled @emotion/core emotion-theming` . Any idea?

**Comment by heikomat** [comment]
@emelens when transitioning to 1.0, the package was renamed:
`@chakra-ui/core` -> `@chakra-ui/react`

**Comment by KoenBrouwer** [comment]
@emelens You might want to take a look at the Chakra migration guide: https://chakra-ui.com/docs/migration. I've followed it myself soon after v1.0 came out and I had absolutely no issues with upgrading everything.

**Comment by justinphilpott** [comment]
I'm getting a similar error to the above:

`$ next build
info  - Checking validity of types  
info  - Creating an optimized production build  
Failed to compile.

./node_modules/@chakra-ui/accordion/dist/chakra-ui-accordion.esm.js
Module not found: Can't resolve 'react' in '[...]/node_modules/@chakra-ui/accordion/dist'

Import trace for requested module:
./node_modules/@chakra-ui/react/dist/chakra-ui-react.esm.js
./src/pages/_app.tsx

./node_modules/@chakra-ui/alert/dist/chakra-ui-alert.esm.js
Module not found: Can't resolve 'react' in '[...]/node_modules/@chakra-ui/alert/dist'

Import trace for requested module:
./node_modules/@chakra-ui/react/dist/chakra-ui-react.esm.js
./src/pages/_app.tsx

./node_modules/@chakra-ui/avatar/dist/chakra-ui-avatar.esm.js
Module not found: Can't resolve 'react' in '[...]/node_modules/@chakra-ui/avatar/dist'

Import trace for requested module:
./node_modules/@chakra-ui/react/dist/chakra-ui-react.esm.js
./src/pages/_app.tsx

./node_modules/@chakra-ui/breadcrumb/dist/chakra-ui-breadcrumb.esm.js
Module not found: Can't resolve 'react' in '[...]/node_modules/@chakra-ui/breadcrumb/dist'

Import trace for requested module:
./node_modules/@chakra-ui/react/dist/chakra-ui-react.esm.js
./src/pages/_app.tsx

./node_modules/@chakra-ui/button/dist/chakra-ui-button.esm.js
Module not found: Can't resolve 'react' in '[...]/node_modules/@chakra-ui/button/dist'

Import trace for requested module:
./node_modules/@chakra-ui/react/dist/chakra-ui-react.esm.js
./src/pages/_app.tsx`

package.json is:

`  "dependencies": {
    "@aws-amplify/ui-react": "^2.1.2",
    "@chakra-ui/icons": "^1.1.5",
    "@chakra-ui/react": "^1.8.3",
    "@emotion/cache": "^11.7.1",
    "@emotion/react": "^11.7.1",
    "@emotion/styled": "^11.6.0",
    "@fontsource/roboto": "^4.5.1",
    "@hookform/error-message": "^2.0.0",
    "@hookform/resolvers": "^2.8.4",
    "@xstate/immer": "^0.3.1",
    "@xstate/react": "^2.0.0",
    "aws-amplify": "^4.3.8",
    "axios": "^0.24.0",
    "framer-motion": "^4",
    "immer": "^9.0.7",
    "next": "latest",
    "next-s3-upload": "^0.1.7",
    "react": "^17.0.2",
    "react-aws-s3": "^1.5.0",
    "react-dom": "17.0.2",
    "react-hook-form": "^7.21.0",
    "react-icons": "^4.3.1",
    "react-query": "^3.33.5",
    "react-router-dom": "^6.0.2",
    "swr": "^1.1.2-beta.0",
    "xstate": "^4.30.1",
    "xstate-helpers": "^1.2.0"
  },
  "devDependencies": {
    "@next/bundle-analyzer": "^12.0.3",
    "@types/node": "^17.0.18",
    "@types/react": "^17.0.34",
    "@types/react-dom": "^17.0.11",
    "eslint": "8.1.0",
    "eslint-config-next": "12.0.3",
    "husky": "^7.0.4",
    "typescript": "^4.4.4"
  },
`

**Comment by with-heart** [comment]
Hey @justinphilpott! Are you using `yarn` or `npm`?

**Comment by justinphilpott** [comment]
I'm using Yarn...

**Comment by with-heart** [comment]
Could you run `yarn why react` and paste the result? Want to see if something is causing a version mismatch.

**Comment by justinphilpott** [comment]
```
yarn why v1.22.17
[1/4] Why do we have the module "react"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "react@17.0.2"
info Has been hoisted to "react"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "356KB"
info Disk size with unique dependencies: "404KB"
info Disk size with transitive dependencies: "432KB"
info Number of shared dependencies: 3
Done in 0.54s.
```
