### ISSUE TITLE
Enhancement: replace popper js with react laag

### ISSUE THREAD

**Issue by groenborg** [chakra-ui/chakra-ui#3356]
# 🚀 Feature request
> Please describe your request in one or two sentences.

Replace popper js with react laag

## 🧱 Problem Statement / Justification

> Please provide valid reason(s) why this should added to Chakra UI.
>
> If this feature is related to a problem you've noticed. Mention it as well

There have been a lot of issues in the backlog related to tooltips and other components relying on popperjs placement. 
Refactoring to React Laag, a much more stable and well functioning library should decrease the errors and time spent
on fixing popper js related issues. 

The value proposition is mostly removing the issues that popperjs created. I have been using it on various projects until I started using react laag. 

## ✅ Proposed solution or API

> Please provide code snippets, gists, or links to the ideal design or API

https://www.react-laag.com/

## ↩️ Alternatives

> What alternative solutions have you considered before making this request?

I have looked at various alternatives, including Tippy.js, which is the other most prominent one. That however also suffers from popper.js issues. 

## 📝 Additional Information

> What resources (links, screenshots, etc.) do you have to assist this effort?

https://www.react-laag.com/

**Comment by FezVrasta** [comment]
It'd be really useful if you could share what kind of issues are you experiencing with Popper.

react-laag is a way more limited positioning library, with very specific constraints. If one decided to follow the same constraints while using Popper you would most likely observe the same behavior.

The problem with Popper is that it aims to solve positioning in a very broad sense, not just a few specific cases. So it can happen that sometimes a specific edge case is not completely supported.

Reporting these issues to the Popper repository can help improve the library though.

**Comment by cschroeter** [comment]
Thank you for taking the time to create this issue. 

I have looked at the proposed alternative and have come to the conclusion that it is not an adequate replacement for Popper.js. However, in the coming days I will look at implementation on our site and make appropriate changes.

Thank you and Happy hacking ✌️
