### ISSUE TITLE
flushSync React warning occurs on render() for Modal that contains a Checkbox

### ISSUE THREAD

**Issue by nfm** [chakra-ui/chakra-ui#3357]
# 🐛 Bug report

Since upgrading Chakra from 1.1.6 to 1.2.1 (and beyond), some of our existing code now emits a React warning on render. From what I can tell, this is a regression in Chakra relating to `@chakra-ui/focus-lock`, or potentially how it interacts with the underlying `react-focus-lock` or `react-clientside-effects` dependencies.

It looks like when we bumped our Chakra version, the underlying `react-focus-lock` and `react-clientside-effects` dependency versions have remained the same in our lockfile.

## 💥 Steps to reproduce

Render a Modal with a Checkbox element inside of it. You'll hit the following React warning:

```
Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.
```

## 💻 Link to reproduction

Here's a minimal reproduction, the `flushSync` warning exhibits on initial render:

https://codesandbox.io/s/exciting-keller-j95hk

## 🧐 Expected behavior

No React warning emitted.

## 🧭 Possible Solution

Not sure sorry, I haven't yet dug into these internals. My next step would be looking into what changed in the `@chakra-ui/focus-lock` package version that comes with `chakra-ui/react` >= 1.2.0.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  >= 1.2.0           |
| Browser          |   any         |
| Operating System |  any          |

## 📝 Additional information

nil

**Comment by segunadebayo** [comment]
Hi @nfm, kindly upgrade to the latest version of React and this warning should go away!

**Comment by nfm** [comment]
Thanks for taking a look @segunadebayo :heart: 

I can confirm we are hitting this on the latest version of react (17.0.1) and chakra-ui/react (1.3.4), so I think something else might be going on.

Would you be able to reopen this issue? Thanks!

**Comment by celador** [comment]
Can Confirm.  I have a <Switch> component inside a <Drawer> and I get this error every time the drawer opens up, before it finishes opening.  I commented out the <Switch> and I do not get the error

**Comment by nfm** [comment]
It looks like we're experiencing this on the newly released chakra-ui/react 1.4.1 too, from more contexts than we did on 1.3.4 :thinking: I haven't dug into the new cases we're seeing this in yet.

**Comment by coodoo** [comment]
Can confirm this still exists in `v1.4.2`, might need further investigation!

cc @segunadebayo

**Comment by manzoorwanijk** [comment]
Can confirm this with the latest version of React and Chakra. In my case it happens when conditionally rendering the inputs.
https://codesandbox.io/s/romantic-river-3nntj

**Comment by melvinalmonte** [comment]
I'm experiencing the same behavior as @manzoorwanijk but with radio buttons instead of a checkbox.

**Comment by iamjoshua** [comment]
As with @celador I'm seeing an error on v1.4.2 when a Drawer contains a switch.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by prizalmarinez** [comment]
I'm experiencing the same problem as @melvinalmonte.  I'm using a Custom Radio Buttons inside the modal and this error pops up whenever I open the modal.

**Comment by Tomer-Shavit** [comment]
I'm still having this problem, I have a Modal with a radio box in it and I get this warning:
Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.

**Comment by mbret** [comment]
I am getting this error when calling toaster.create within a useEffect

**Comment by Deepak-Sangle** [comment]
> I am getting this error when calling toaster.create within a useEffect

I am also getting this when calling `toaster.create()`, any workarounds?
