### ISSUE TITLE
Unable to change the color of the pin input to white in dark mode

### ISSUE THREAD

**Issue by devhims** [chakra-ui/chakra-ui#3379]
I'm trying to change the outline color of the pin input fields to white in dark mode. However, I couldn't find a prop for that. Could it be done? 

<img width="470" alt="Screenshot 2021-02-14 at 2 17 02 PM" src="https://user-images.githubusercontent.com/17825870/107872340-b510e100-6ecf-11eb-8772-61ca21c5953c.png">

**Comment by devhims** [comment]
I managed to get a somewhat better outcome with the `borderColor` prop on the `PinInputField` children. But the inner circle remains unaffected. 

<img width="475" alt="Screenshot 2021-02-14 at 2 59 26 PM" src="https://user-images.githubusercontent.com/17825870/107873054-61a19180-6ed5-11eb-9aa3-64f262d2da7d.png">

**Comment by with-heart** [comment]
Converting this to a discussion
