### ISSUE TITLE
Tooltip render loop with Preact

### ISSUE THREAD

**Issue by karesztrk** [chakra-ui/chakra-ui#3384]
The Tooltip causes render loop.

# 🐛 Bug report

The Tooltip causes render loop when used with **Preact**.

## 💥 Steps to reproduce

1. Open any page containing a \<Tooltip\>

## 🧐 Expected behavior

Page should be rendered even tough the tooltip is not yet displayed.

## 🧭 Possible Solution

> https://popper.js.org/react-popper/v2/faq/

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.2.1       |
| Preact        |     10.5.12       |
| Browser          |        Firefox Dev v86    |
| Operating System |  Window 10          |

**Comment by segunadebayo** [comment]
Fixed in the PR above. If the issue re-occurs, we'll consider re-opening.

**Comment by tumdav** [comment]
@segunadebayo same happens for the popover component

I am using gatsby, without `gatsby-plugin-preact` it works perfectly but when I am adding the plugin it stops working
