### ISSUE TITLE
Td/Tr rendered outside of a Table throw an unclear error

### ISSUE THREAD

**Issue by npirotte** [chakra-ui/chakra-ui#3388]
# 🐛 Bug report

When rendering a Tr component outside of a table (I know I shouldn't, but I accidentally did that in a snapshot test), rendering throw an ambiguous error:

useStyles: `styles` is undefined. Seems you forgot to wrap the components in `<StylesProvider />`

While I admit this is a corner case, this make one of my team mates loose a couple of hours to figure out why his very simple test was not working.

A clear error message, or at least a mention of that limitation in the documentation would be welcome :)

## 💥 Steps to reproduce

> Clear and concise reproduction steps are important for us to be able to triage
> your issue in a timely manner

## 💻 Link to reproduction

Render a Tr component outside of a Table scope:

```
describe('TablePlaceholder', () => {
  it('should render successfully', () => {
    const { asFragment } = render(
      <ChakraProvider theme={theme}>
        <Tr></Tr>
      </ChakraProvider>
    );
    expect(asFragment()).toMatchSnapshot();
  });
});
```

## 🧐 Expected behavior

An clear error message explaining that a Tr can only be rendered within a Table, or at least some documentation on the Table documentation.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        1.1.6

**Comment by segunadebayo** [comment]
Hi @npirotte,

The `Tr` and `Td` can't be used outside the context of `Table` by design. They share a common theming context that's provided by the `Table` component. You can use a regular `tr` and `td` or a chakra derivative of those (`chakra.tr`, `chakra.td`)
