### ISSUE TITLE
CircularProgress

### ISSUE THREAD

**Issue by sinitsa** [chakra-ui/chakra-ui#34]
Hello,

I tried using the CircularProgress component but got an error when importing from @chakra-ui/core. It only worked now with import like this:
import CircularProgress, {
  CircularProgressLabel
} from "@chakra-ui/core/dist/CircularProgress";

PS: Thanks for perfect ui lib ;)

**Comment by segunadebayo** [comment]
Thanks for spotting this @sinitsa . It was missing in the type def export, I've added it now.
