### ISSUE TITLE
[Homepage] Error displayed in the homepage

### ISSUE THREAD

**Issue by thangab** [chakra-ui/chakra-ui#340]
**Describe the bug**
We can see an error message _ReferenceError: mdx is not defined_ on the homepage [https://chakra-ui.com/](url) and the Box component is not display.

<img width="1251" alt="error-chakra-ui" src="https://user-images.githubusercontent.com/15085404/72168967-7f492100-33ce-11ea-8f4a-3ef332fb636c.png">

**Expected Behavior**
Display the Box Component in the homepage

**To Reproduce**
- List the steps to reproduce the behavior:
1. Go to the homepage [https://chakra-ui.com/](url)
2. Click on **Get Started**
3. Come back to the homepage
4. See the error message

**Suggested solution(s)**
I didn't check yet, sorry.

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by cxcorp** [comment]
I'm also seeing this now.
