### ISSUE TITLE
Tabs onChange handler is triggered twice

### ISSUE THREAD

**Issue by vicke4** [chakra-ui/chakra-ui#3406]
## 💻 Steps to reproduce & Link to reproduction

We can easily reproduce this on the [tabs documentation page](https://chakra-ui.com/docs/disclosure/tabs#controlled-tabs). Just add a `console.log` in the `onChange` handler. Please check the screenshot attached.

## 🧐 Expected behavior

The handler has to be called only once.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |    1.1.6  & The version being used on Chakra docs page      |
| Browser          |        Chrome    |
| Operating System |      Mac      |

## 📝 Additional information
![abc](https://i.ibb.co/kc8gHXk/chakra-tabs-onchange-handler-min.gif)

**Comment by dodas** [comment]
Hey @vicke4, thanks for the report!

I made a PR that fixes it alongside some other possible double-calls.
Should be released in the next version.

**Comment by sbdchd** [comment]
I can still reproduce this in the docs:

```ts
  const handleTabsChange = (index) => {
    setTabIndex(index)
    console.log("on change", index)
  }
```

<img width="147" alt="image" src="https://user-images.githubusercontent.com/7340772/215241896-fb8f0f59-7ea1-4ddb-a81f-79ab79578304.png">
