### ISSUE TITLE
losing styles in the middle of development

### ISSUE THREAD

**Issue by devhims** [chakra-ui/chakra-ui#3407]
Everything is working fine. I'm testing a few props for the Text and Link components and then suddenly I realize the props are not taking effect. As you can see in the screenshot `as` and `textDecor` are not working. Any clues? 

<img width="1106" alt="Screenshot 2021-02-18 at 12 51 53 AM" src="https://user-images.githubusercontent.com/17825870/108256899-0fd26300-7184-11eb-8bc1-546c3b4605f6.png">

**Comment by devhims** [comment]
"@chakra-ui/react": "^1.3.3",
 "react": "^17.0.1",

confirmed on:

- [x] Chrome
- [x] Safaru

**Comment by devhims** [comment]
I think it's just my sleepy mind and newness to Chakra UI. When I pass the `fontSize` and `fontWeight` props, everything works fine.  As for the `textDecor` prop on the Link, I didn't find it on the documentation page, so maybe it's deprecated. However, I can still use the `underline` value.

**Comment by dodas** [comment]
`as` only changes the html element the component renders. as you can see, it works and an `h1` is rendered. However, Chakra UI uses CSS reset, so html tags don't have any styling by default.

`textDecor` is shorthand for `textDecoration`. when you use `textDecor="violet"`, you are setting underline's color to purple, but you don't have the `text-decoration-line` css property set to begin with. Using `textDecor="underline violet"` works.

Style props are listed [here](https://chakra-ui.com/docs/features/style-props) and you can use them on all Chakra UI components.
