### ISSUE TITLE
Request to add CDN

### ISSUE THREAD

**Issue by wale-bant** [chakra-ui/chakra-ui#341]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when i can't use beautiful UI library like this on code sharing platforms such as CodePen or CodeSandbox

**Describe the solution you'd like**
Chakra UI hosted on a CDN

**Comment by mpash** [comment]
You can get this out of the box. Include a `package.json` in any new CodeSandbox, and import there.

https://codesandbox.io/s/new
