### ISSUE TITLE
Adding option in Menu item to be selectable when open

### ISSUE THREAD

**Issue by yotam707** [chakra-ui/chakra-ui#3411]
# 🚀 Feature request

> Please describe your request in one or two sentences.

When I open a Menu I want an option to choose the selected item (similar to the way you do it in the popper component with initial ref). I couldn't find a way to achieve this.

## 🧱 Problem Statement / Justification

> Please provide valid reason(s) why this should added to Chakra UI.
Seems like a logical thing to do 😄 
> If this feaure is related to a problem you've noticed. Mention it as well
My problem was that I have a menu and I want the current value to be also highlighted, meaning selected. Currently, it only focuses on the first element in the list. 

## ✅ Proposed solution or API

> Please provide code snippets, gists, or links to the ideal design or API

## ↩️ Alternatives

> What alternative solutions have you considered before making this request?

## 📝 Additional Information

> What resources (links, screenshots, etc.) do you have to assist this effort?

**Comment by cschroeter** [comment]
Thank you for taking the time to create this issue. Unfortunately, it does not contain all the necessary information we need to work on this issue.

Therefore we have to close this issue. You can create a new issue at any time - please use the corresponding issue template.

Happy hacking ✌️
