### ISSUE TITLE
Elements for Number Inputs

### ISSUE THREAD

**Issue by brennanfife** [chakra-ui/chakra-ui#3420]
# 🚀 Feature request

> Please describe your request in one or two sentences.

Currently, developers can add left or right elements to Input components. It would be nice to extend this functionality to Number Inputs as well.

## 🧱 Problem Statement / Justification

> Please provide valid reason(s) why this should added to Chakra UI.

A couple use cases that come to mind include left elements for currency symbols or right elements that contain tag or badge labels.

One component library I know that has used elements on number inputs is [Blueprint.js](https://blueprintjs.com/docs/#core/components/numeric-input). While this library is dated, this minor feature may prove useful in certain scenarios.

**Comment by segunadebayo** [comment]
Hi @brennanfife,

After much thought, we won't be adding support for this to reduce the API surface. Feel free to compose this behavior in your app.

**Comment by Jhappy77** [comment]
@segunadebayo Respectfully, I think you should implement this feature. 

https://chakra-ui.com/docs/form/number-input#formatting-and-parsing-the-value 

The alternative example here from the documentation seems like poor practice for an ecommerce application. Deformatting and reformating the number upon every change is prone to errors, plus it would not be easily extensible (what if you add currencies besides $? Now you need to update the formatting logic to include every single possible symbol)

Needing a prefix or suffix for a number input is probably an extremely common use case - usually a number is describing a cost or quantity of something. I ran into wanting to do this within my first 30 minutes of using Chakra UI

**Comment by iampueroo** [comment]
I have had the same experience as the commenter above me. I have found it surprising that the [docs](https://chakra-ui.com/docs/form/input#left-and-right-addons) use a currency as the example, but the input is an Input, not an `NumberInput`.

If there is some guidance on how to start, or suggested fixes, I'd be happy to attempt a PR.

**Comment by mabdu11ah** [comment]
The best solution I could come up with was using the `InputGroup` and the `InputLeftAddon` with the `NumberInput`.

However, this causes the `NumberInput` to decrease in width and border radius' to mismatch which is fixed by setting the `NumberInput`'s width to `100%` and setting the border radius to 0 on the left side of the `NumberInputField`.

A bit hacky, but it gets the job done.

```
<InputGroup>
   <InputLeftAddon>$</InputLeftAddon>
   <NumberInput w="100%">
      <NumberInputField
         borderTopLeftRadius={0}
         borderBottomLeftRadius={0}
       />
      <NumberInputStepper>
         <NumberIncrementStepper />
         <NumberDecrementStepper />
      </NumberInputStepper>
   </NumberInput>
</InputGroup>
```

The end result looks like this:

<img src="https://i.imgur.com/TNe5RyA.png" />
