### ISSUE TITLE
Website: Drawer links are broken

### ISSUE THREAD

**Issue by nwatx** [chakra-ui/chakra-ui#3425]
https://chakra-ui.com/docs/overlay/drawer

source links here: 
![image](https://user-images.githubusercontent.com/43394822/108616695-6e425000-73d5-11eb-8dd3-786a1136b2b7.png)

**Comment by TheAsda** [comment]
[This commit](https://github.com/chakra-ui/chakra-ui/commit/d1a6fe409a8aa67867b5cbb14006dfe0dd7e4e9b#diff-1680f27e83d7c1f66ea53e931e86801ea8e297b95f8ce0716461dd10c1c953d9) moved drawer code to modal. So i guess that modal readme should be updated and the link in the docs should lead to [modal](https://github.com/chakra-ui/chakra-ui/tree/main/packages/modal).
