### ISSUE TITLE
[Modal] Dialog closes on drag release

### ISSUE THREAD

**Issue by jonathanwilke** [chakra-ui/chakra-ui#343]
**Describe the bug**
When you try to select the text in an input that is inside a modal and you release the drag outside of the modal it closes.

**Expected Behavior**
Since it is not an actual click besides the modal to close it, the modal should not be closed.

**Comment by segunadebayo** [comment]
Hi @jonathanwilke,

I just looked into this and fixed it in the `dev-ts` branch. Kindly wait till the next release to get this fix. Thanks for reporting this!

**Comment by peter-thach** [comment]
I am still experiencing this issue. I assume it has been "fixed" by now, has it not?
