### ISSUE TITLE
[Refactor] separate core from React dependencies

### ISSUE THREAD

**Issue by iamyuu** [chakra-ui/chakra-ui#3431]
# Refactor

Chakra UI has 3 main core package: `utils`, `system`, and `styled-system`.

`styled-system` is a framework independent package that can be used with React, Vue, Svelte, or another framework.

## 🧱 Problem Statement

`styled-system`  has peer dependencies to `utils` package and the `utils` have peer dependencies to React.

## ✅ Proposed solution

Move `react-helpers` into a single package, so packages `utils` can be used with another framework without need to install React as dependencies.

**Comment by segunadebayo** [comment]
I totally see the usefulness of this. After some consideration, we won't be doing this for now.
