### ISSUE TITLE
Incorrect `MenuList` positioning before first open

### ISSUE THREAD

**Issue by jgarrow** [chakra-ui/chakra-ui#3433]
# 🐛 Bug report

On the initial render before opening the `Menu` for the first time, the `MenuList` is incorrectly positioned, causing an undesired horizontal scroll on the page. After opening and closing the menu, the `MenuList` is correctly positioned and no longer causes a horizontal scroll.

## 💥 Steps to reproduce

1. Create a `Menu` with a `MenuButton`, `MenuList` and a couple of `MenuItems`
2. Place the `Menu` inside of an absolutely positioned div in the top right corner
3. Refresh the page to trigger an initial mount
4. Try scrolling horizontally
5. Open the `Menu`
6. Close the `Menu`
7. Try scrolling horizontally

## 💻 Link to reproduction

https://codesandbox.io/s/amazing-leftpad-jd0sh?file=/src/App.js

## 🧐 Expected behavior

The hidden `MenuList` does not create a horizontal scroll 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | v1.1.6 (also tried w/ v1.3.3)           |
| Browser          | Chrome v88.0.4324.182, Safari v14.0.1 |
| Operating System | macOS Catalina            |

## 📝 Additional information

Screenshot of horizontal scroll:
<img width="470" alt="Screen Shot 2021-02-22 at 11 03 19 AM" src="https://user-images.githubusercontent.com/32886852/108753430-f6be0f00-7501-11eb-97b1-35e8ce791bc1.png">

After opening and closing the `Menu`, the `MenuList` has some `transform` styling being applied. This styling is not present on the initial render before the `Menu` has been opened.

`MenuList` styling before opening for first time:

```
position: absolute;
left: 0px;
top: 0px;
visibility: hidden;
```

`MenuList` styling after opening and closing:

```
position: absolute;
inset: 0px auto auto 0px;
visibility: hidden;
transform: translate3d(-160px, 36.5px, 0px);
```

**Comment by jgarrow** [comment]
If I change the first `Box` child of the `App` div to a `Flex` component and remove the absolute positioning, that seems to fix the issue. Perhaps absolute positioning messes up the way Chakra calculates the placement of the menu.

**Comment by JanSysala** [comment]
Setting the `display` property of `MenuList` to `block` solved my issue with the hidden div that Chakra creates before the first render of the MenuList.

**Comment by hugomn** [comment]
I'm seeing this issue right now:
<img width="263" alt="Screenshot 2023-11-27 at 17 55 04" src="https://github.com/chakra-ui/chakra-ui/assets/497957/ad2f7db3-ec89-4e35-a712-e758f9ce9b4a">

Why was this issue closed? What is the solution to use the Menu inside a container with absolute positioning?

**Comment by eliseubrito7z** [comment]
I had this problem now, in my case the problem is using a customized Button in "as={Button}", it is necessary to use the chakra-ui's own Button

Code with error:

```js
import { MyCustomButton } from "../DefaultComponents/Button";

    <ChakraMenu>
      <MenuButton as={MyCustomButton} rightIcon={<ArrowDown />}>
        Actions
      </MenuButton>
      <MenuList>
        <MenuItem>Download</MenuItem>
        <MenuItem>Create a Copy</MenuItem>
        <MenuItem>Mark as Draft</MenuItem>
        <MenuItem>Delete</MenuItem>
        <MenuItem>Attend a Workshop</MenuItem>
      </MenuList>
    </ChakraMenu>
```` 

No error:

```js
import { Button as ChakraButton } from "@chakra-ui/react";

    <ChakraMenu>
      <MenuButton as={ChakraButton} rightIcon={<ArrowDown />}>
        Actions
      </MenuButton>
      <MenuList>
        <MenuItem>Download</MenuItem>
        <MenuItem>Create a Copy</MenuItem>
        <MenuItem>Mark as Draft</MenuItem>
        <MenuItem>Delete</MenuItem>
        <MenuItem>Attend a Workshop</MenuItem>
      </MenuList>
    </ChakraMenu>
```
