### ISSUE TITLE
Menu on far right of screen causes unexpected mobile resize behavior

### ISSUE THREAD

**Issue by ryanhatfield** [chakra-ui/chakra-ui#3436]
# 🐛 Bug report

When using a Menu or Popover, the popper js container is being resized even when not visible, and is being placed outside the normal bounds, causing unexpected behavior when resizing (rotating the screen on mobile).

## 💥 Steps to reproduce

1. Go to https://j59xr.csb.app/
2. Open Chrome Dev Tools
3. Set the device to something smaller than a tablet
4. Click on the "Menu" button at least once
5. Click the "Rotate" button in Chrome Dev tools
6. See the extra padding on the right and bottom

## 💻 Link to reproduction

Reproduction on [CodeSandbox](https://codesandbox.io/s/recursing-kirch-j59xr)

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.3.3  |
| Browser          | Google Chrome  |
| Operating System |   OSX   |

## 📝 Additional information

* This doesn't happen on all resolutions
* I was able to reproduce this bug on my OnePlus 7Pro Android smartphone

![image](https://user-images.githubusercontent.com/12716395/108806102-6239c800-7566-11eb-9ffe-bfa52a0f4ed4.png)
 
![chakra-menu-resize-bug](https://user-images.githubusercontent.com/12716395/108806542-9661b880-7567-11eb-98b3-59739d9d5402.gif)

**Comment by segunadebayo** [comment]
Hi @ryanhatfield,

I just checked this and it seems to be a bug in popper.js itself. Kindly open an issue there.

Feel free to double-check against popper.js to confirm this.

**Comment by jaaneh** [comment]
@ryanhatfield Curious if you managed to solve this somehow? Been facing a similar issue where the menu appears outside of view when resizing the window. 
 
![](https://jaany.xyz/i/e1qwy.png)
