### ISSUE TITLE
[Menu] MenuItems have missing icons when two Menus are on the page

### ISSUE THREAD

**Issue by feross** [chakra-ui/chakra-ui#3442]
# 🐛 Bug report

When two Menus are on the page, the second Menu has icons missing from its MenuItems. See example.

## 💥 Steps to reproduce

```js
<Stack>
      <Box>
        <Menu>
          <MenuButton as={Button} size="lg">
            Add files
          </MenuButton>
          <MenuList>
            <MenuItem icon={<Icon as={VscFiles} height="full" width={4} />}>
              Select files
            </MenuItem>
            <MenuItem
              icon={<Icon as={VscFolderOpened} height="full" width={4} />}
            >
              Select a folder
            </MenuItem>
          </MenuList>
        </Menu>
      </Box>
      <Box>
        <Menu>
          <MenuButton as={Button} size="lg">
            Add files
          </MenuButton>
          <MenuList>
            <MenuItem icon={<Icon as={VscFiles} height="full" width={4} />}>
              Select files
            </MenuItem>
            <MenuItem
              icon={<Icon as={VscFolderOpened} height="full" width={4} />}
            >
              Select a folder
            </MenuItem>
          </MenuList>
        </Menu>
      </Box>
    </Stack>
```

</details>

## 💻 Link to reproduction

https://codesandbox.io/s/adoring-pond-kinz3?file=/src/index.tsx

## 🧐 Expected behavior

Icons should always show up in `MenuItem`s.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.3.3         |
| Browser          |  Chrome          |
| Operating System |  macOS 11.2.1          |

**Comment by dodas** [comment]
This is a pretty weird bug. I can't reproduce it with any other icon than `VscFolderOpened`.

**Comment by feross** [comment]
Perhaps this is a bug in the way that the icon is defined? I dug a little bit further and figured out that the SVG icon uses an `id` attribute which shouldn't be used in the page more than once? Perhaps the second icon is using the first's `clip-path`?

I opened an issue about it here: https://github.com/microsoft/vscode-codicons/issues/48

**Comment by dodas** [comment]
Can this be closed on our side?

**Comment by maplemap** [comment]
Faced with the same problem of using the same icon several times

@chakra-ui/react@2.6.1

Reproduced in:
- Chrome 114.0.5735.133 (Official Build) (arm64)
- Firefox 114.0.2 (64-bit)
- Opera 95.0.4635.37 (arm64)

**Comment by dodas** [comment]
@maplemap check the source code of the icon and check whether it uses the `id` attribute somewhere.

**Comment by maplemap** [comment]
Please take a look this video below
https://github.com/chakra-ui/chakra-ui/assets/5664270/973ab8ce-84d1-4547-8a66-1a317918dcb9

So, there are two icons with the same id `search_svg__a`. One of the icons is not showing up in the search field. After I changed the id attribute name of the invisible icon in the tags `mask` and `g`, it appeared

**Comment by dodas** [comment]
That's unfortunately how ids in svgs work (not related to chakra) – you can't have multiple same ones on a single page.
The easiest solution would be probably to find a _Search_ icon that doesn't use ids, for example this one:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50">
  <path d="M 21 3 C 11.601563 3 4 10.601563 4 20 C 4 29.398438 11.601563 37 21 37 C 24.355469 37 27.460938 36.015625 30.09375 34.34375 L 42.375 46.625 L 46.625 42.375 L 34.5 30.28125 C 36.679688 27.421875 38 23.878906 38 20 C 38 10.601563 30.398438 3 21 3 Z M 21 7 C 28.199219 7 34 12.800781 34 20 C 34 27.199219 28.199219 33 21 33 C 13.800781 33 8 27.199219 8 20 C 8 12.800781 13.800781 7 21 7 Z"/>
</svg>
```

![download](https://github.com/chakra-ui/chakra-ui/assets/14360171/72c57b89-5e52-4570-bf68-63a3d5780927)
