### ISSUE TITLE
useToken with theme function notation, with usecase in fallbackShadowColor for Popover

### ISSUE THREAD

**Issue by vincentbriglia** [chakra-ui/chakra-ui#3444]
# 🚀 Feature request

I don't consider this a bug, more an enhancement, but example here is Popover to take its `arrowShadowColor` value from the popover theme. We have tried `useToken` to get the value but since the token for the Popover border is calculated, we can't do 
```
  const [popoverBackground] = useToken<string>(
    // the key within the theme, in this case `theme.components`
    'components',
    // the subkey(s), resolving to `theme.components.<subkeywithdotnotation>`
    ['Popover.baseStyle.borderColor']
  );
```

## 🧱 Problem Statement / Justification

We love that we can add a theme, f.ex a popper with a yellow border, but we do not love that we have to then hardcode the same theme value in our Popover or a Popover wrapper on the `arrowShadowColor` prop

## ✅ Proposed solution or API

possible solutions: 
- by default, attempt to take the values of `fallbackShadowColor` from the calculated values in `popover.tsx` using useProps? https://github.com/chakra-ui/chakra-ui/blob/main/packages/popover/src/use-popover.ts#L157-L159 
- allow for `useTheme` hook to compute object lookups that contain the function notation 

## ↩️ Alternatives

documenting an exception in our project that if you want to customize the popover or the tooltip

**Comment by segunadebayo** [comment]
Hi @vincentbriglia,

A simpler solution could be to use a CSS variable to store the border color and pass that to the value of `arrowShadowColor`

```jsx
const theme = extendTheme({
  components: {
    Popover: {
      baseStyle: {
        content: {
          "--popover-border-color": "#444",
        },
      },
    },
  },
});

<Popover arrowShadowColor="var(--popover-border-color)" />
```

Hope this is helpful.

**Comment by segunadebayo** [comment]
Happy to re-open if it's not.
