### ISSUE TITLE
motion.custom() is deprecated. Use motion() instead

### ISSUE THREAD

**Issue by ViaxCo** [chakra-ui/chakra-ui#3459]
# 🐛 Bug report

> Provide a brief description of the bug here

This warning: `motion.custom() is deprecated. Use motion() instead` gets logged to the console whenever a new `chakra-ui` project is created with `framer-motion@3.7.0`.
Framer motion [changelog.](https://github.com/framer/motion/blob/main/CHANGELOG.md)

## 💥 Steps to reproduce

> Clear and concise reproduction steps are important for us to be able to triage
> your issue in a timely manner

## 💻 Link to reproduction

> Please create a minimal reproduction in CodeSandbox

https://codesandbox.io/s/delicate-glitter-hroux

## 🧐 Expected behavior

> Tell us what you expect to happen.

## 🧭 Possible Solution

> Not compulsory, but suggesting a fix would be great!

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |            |
| Browser          |            |
| Operating System |            |

## 📝 Additional information

- Screenshots or code
- Notes or link to ideas

**Comment by Mzaien** [comment]
i've had a look on chakra repo the motion.custom is used only in checkbox component and one storyblock /storybook (sorry if mis spilled )

**Comment by smblee** [comment]
This breaks the `chakra-cli tokens` command for me.

`chakra-cli tokens src/styles/theme/theme.ts`

![image](https://user-images.githubusercontent.com/9781750/109548427-7b200d00-7a81-11eb-922d-881dc92fd5c0.png)

**Comment by bartconsedine** [comment]
having the same issues and it is not loading my NextJS app as a result

**Comment by Mzaien** [comment]
@segunadebayo i think it is solvable if it was only used in checkbox as mentioned here https://github.com/chakra-ui/chakra-ui/issues/3459#issuecomment-786892967 right?

**Comment by dodas** [comment]
To solve this, we can either:

- bump required `framer-motion` to `^3.7.0` which introduced `motion()`, so we can use it.
Can we do it? Could it introduce some problems for users?
- do some heuristics to determine whether `motion()` is supported and conditionally use that, or `motion.custom()`.
I'm not yet sure how doable this option is.

**Comment by codetective** [comment]
@dodas there's currently a PR for this implemementing your idea, hopefully the chakra team will review it soon. #3492

**Comment by violabg** [comment]
chakra-cli  command yarn gen:theme-typings, is not working anymore due to **This warning: motion.custom() is deprecated. Use motion() instead**.
So it's not just a warning we can ignore.

**Comment by callum-mellorreed-privitar** [comment]
If you're affected by this and use Yarn, for now you can add a resolution for the relevant dependency to your `package.json`.

```json
"resolutions": {
  "framer-motion": "3.6.7"
}
```

This will tell Yarn to use framer-motion@3.6.7 even if a newer version matches the range specified by the depending package. This is the latest version before `motion.custom()` deprecation.

**Comment by Mzaien** [comment]
But will all users need to do that ? it is kinda weird we should updated framer motion + doing tests to make sure noting is broken

**Comment by kavehsaket** [comment]
+1

**Comment by callum-mellorreed-privitar** [comment]
> But will all users need to do that ? it is kinda weird we should updated framer motion + doing tests to make sure noting is broken

Sure, I'm just providing an immediate workaround for people blocked by the issue.

**Comment by hamzahasbi** [comment]
@callum-mellorreed-privitar +1 on the workaround mate !

**Comment by segunadebayo** [comment]
This has been fixed in #3623
