### ISSUE TITLE
*FEATURE* mediaQueries prop

### ISSUE THREAD

**Issue by ivanjeremic** [chakra-ui/chakra-ui#3466]
Instead of using the hook `useMediaQuery` I sugguest solving the use of media queries with a new prop API would be better, instead of importing a hook and then initialize the hook we could have just one prop called `mediaQueries`

I'm unsure how the best solution for the API would be but something where we can put multiple media queries inside if needed I think.

`takes array if you need multiple`
```
<Box
 mediaQueries={[{ maxWidth: 992px, style: { backgroundColor: blue } }...]}
 >
Demo
</Box>
```

Also, an option would be to have a `mediaQuery` prop if you only need one
```
<Box
 mediaQuery={{ minWidth: 992px, style: { backgroundColor: blue } }}
 >
Demo
</Box>
```

**Comment by segunadebayo** [comment]
Thanks for sharing this idea.

I took some time to think about this and I don't think we'll be adding this feature for now.
