### ISSUE TITLE
make transitions "lazy" by default

### ISSUE THREAD

**Issue by ianstormtaylor** [chakra-ui/chakra-ui#3468]
# 🚀 Feature request

Make transitions like `<Collapse>` lazy by default, so that their content isn't rendered in the DOM when they are hidden.

This is a sensible default because otherwise it becomes very easy to accidentally render large lists with a `Collapse` (or other transitions) and then you have a massive DOM that slows everything down. The default should be flipped so that leaving it mounted is what you opt-in to instead of the other way around.

(I believe this should apply to all components that render a hidden element, like `<Modal>`, `<Popover>`, etc. But I'll keep this issue scoped.)

**Comment by santialbo** [comment]
I would like to see this happen too, or at least have a better way of setting the default on the theme. This is how I'm overcoming this until there's a better way. 
```
Menu.defaultProps = {
  isLazy: true,
} as any;

Popover.defaultProps = {
  isLazy: true,
} as any;
...
```

**Comment by spykr** [comment]
@santialbo with the addition of the new ["theme extensions"](https://chakra-ui.com/docs/theming/customize-theme#using-theme-extensions) there seems to be an easier way to do this now, e.g.

```
import { extendTheme, withDefaultProps } from '@chakra-ui/react';

const theme = extendTheme(
  withDefaultProps({
    defaultProps: {
      isLazy: true,
    },
    components: ['Menu', 'Popover'],
  })
);

export default theme;
```
