### ISSUE TITLE
Icon button weird behavior in dark mode

### ISSUE THREAD

**Issue by Mzaien** [chakra-ui/chakra-ui#3469]
# 🐛 Bug report

> Provide a brief description of the bug here
Iconbuttons or buttons containing an icon inside has a weird behavior in production it mixies between light and dark mode
## 💥 Steps to reproduce
visit https://media-club-mzaien.netlify.app/ and see any post 
then copy its url and paste it in another tap like visit https://media-club-mzaien.netlify.app/p/ydp3phuaammv-cwn/
> Clear and concise reproduction steps are important for us to be able to triage
> your issue in a timely manner

## 💻 Link to reproduction
visit https://media-club-mzaien.netlify.app/p/ydp3phuaammv-cwn/
> Please create a minimal reproduction in CodeSandbox
>
> - JavaScript Template:
>   [JavaScript CodeSandbox template](https://codesandbox.io/s/github/chakra-ui/codesandbox-react-js-template/tree/master)
>
> - TypeScript Template:
>   [TypeScript CodeSandbox template](https://codesandbox.io/s/github/chakra-ui/codesandbox-react-ts-template/tree/master)

## 🧐 Expected behavior
all buttons should all be in dark or light mode 
![image](https://user-images.githubusercontent.com/43112535/109383338-fc976400-78f6-11eb-8826-3a1e73f71715.png)

> Tell us what you expect to happen.

## 🧭 Possible Solution

> Not compulsory, but suggesting a fix would be great!

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |            |
| Browser          |            |
| Operating System |            |

## 📝 Additional information

- Screenshots or code
- Notes or link to ideas

**Comment by Mzaien** [comment]
Missed to say i'm using gatsby

**Comment by dodas** [comment]
The link you posted is 404.
Please make a minimal reproduction in the code sandbox.

**Comment by Mzaien** [comment]
Sorry for that,
here is the working links 
main site: 
https://media-club.netlify.app/

The problematic: url (it works for any post link but this is an example):
https://media-club.netlify.app/p/ydp3phuaammv-cwn/

@dodas if you can see it

**Comment by dodas** [comment]
I am asking for a sandbox for a reason.
I can't see your code from looking at your site.
All I can see is that you are ending up in a `<button>` nested in `<button>`, so your code structure is probably wrong.
Maybe you are putting `IconButton` inside `Button` or something like that.

**Comment by Mzaien** [comment]
You are right i checked the code and figured out the containing icon-button inside react-share button was the problem with styling now it is as react-share button and inside it i put a normal icon Thanks a lot
