### ISSUE TITLE
EditableInput isInvalid prop

### ISSUE THREAD

**Issue by frustak** [chakra-ui/chakra-ui#3476]
# 🚀 Feature request

> `EditableInput` should have `isInvalid` prop

## 🧱 Problem Statement / Justification

> Since `Input` does have `isInvalid` prop, `EditableInput` should have one too.
> It's also quite a useful feature for validation

## ✅ Proposed solution or API

> Suggested API: `<EditableInput isInvalid />` 
> `Input` `isInvalid` API link: https://chakra-ui.com/docs/form/input#changing-the-focus-and-error-border-colors

## ↩️ Alternatives

> Custom `Editable` component.

## 📝 Additional Information

> --

**Comment by segunadebayo** [comment]
Hi @frustak,

After much thought, we won't be adding this but here's how you can do that.

```jsx
 <Editable defaultValue="chakra-ui-demo">
        <EditableInput aria-invalid={isInvalid}  _invalid={{ borderColor: "red.300" }} />
        <EditablePreview />
  </Editable>
```
