### ISSUE TITLE
[ColorModeProvider] ColorMode and SSR (next.js) not working very well together

### ISSUE THREAD

**Issue by santialbo** [chakra-ui/chakra-ui#349]
**Describe the bug**
When using colorMode with SSR (in this case with next.js) the pages are rendered from the server with light mode.
However on the client the pages are rendered with whatever setting is stored on localstorage by `use-dark-mode`. If the value store is `darkMode = true` this leads to hydration missmatches.
This causes some of the components to be rendered with light mode even if the colorMode is dark.

Check the issue by yourself on https://next-colormode-test.santialbo.now.sh (repo on [santialbo/next-colormode-test](https://github.com/santialbo/next-colormode-test/)).
- Set dark mode on
- Refresh the page

**Expected Behavior**
I would expect that by default the client renders twice, a first time with light mode so that there are no missmatches and the turns into dark mode.

**To Reproduce**
Check [santialbo/next-colormode-test](https://github.com/santialbo/next-colormode-test/) for a minimal reproduction of the issue.

**Desktop (please complete the following information):**
Tried with both Firefox and Chrome.

**Comment by davae1an** [comment]
experiencing the same issue

**Comment by Penspinner** [comment]
Also experiencing the same issue.

**Comment by VladLegkowski** [comment]
Would it be better not to set the theme in the local storage? 

Funny, but if you change the theme on https://chakra-ui.com/, it is not setting the cookie to true.

**Comment by kolyasapphire** [comment]
Also can't get it to work both on my project (Next.js) and https://chakra-ui.com/

In the file [NoFlashSript.js](https://github.com/chakra-ui/chakra-ui/blob/28f19337a29bc6d2196708a1c76ac0d823821cc6/packages/chakra-ui-docs/components/NoFlashSript.js) on [chakra-ui-docs ](https://github.com/chakra-ui/chakra-ui/tree/28f19337a29bc6d2196708a1c76ac0d823821cc6/packages/chakra-ui-docs) I see localStorage 'darkMode' being referenced.

Returns true for me every time:
`localStorage.getItem('darkMode')`

However, in issue #214 it's 'isDarkMode'

Returns null for me every time:
`localStorage.getItem('isDarkMode')`

**Comment by mdreizin** [comment]
The same issue for Gatsby as well.

**Comment by franky47** [comment]
I have the same issue, and from what I understand, the NoFlashSript (which comes from a [recommendation](https://github.com/donavon/use-dark-mode#that-flash) on `use-dark-mode`, the dependency used by Chakra) works as expected: before hydration time, it will find the correct theme to apply, first by looking in local storage (for remembering explicit user preferences), then in the system theme (if applicable), and only then in the body by looking for a class name, to follow the default applied by SSR.

Once the theme has been identified, it syncs it at the two locations it has control over: the localStorage key, and the body classname, which toggles the dark styles and no FOUC, yay.

The issue (for my case at least) arises when there are components that use dynamic styles based on the `useColorMode` hook, which are not calculated in CSS depending on which class is applied on `body`, but rather interpolated dynamically, causing the hydration mismatches. 

One (ugly) solution I found, which solves the FOUC and the incorrect style, is:
1. adding the [NoFlashScript](https://github.com/donavon/use-dark-mode/blob/develop/noflash.js.txt) from `use-dark-mode` to make sure the class name is set correctly at hydration time
2. changing components with dynamic styles:

```ts
import React from 'react'
import { Box, useColorMode } from '@chakra-ui/core'

const DynamicComponent = ({}) => {
  const { colorMode } = useColorMode()
  return (
    <Box
      bg={colorMode === 'dark' ? 'gray.800' : 'gray.200'}
      color={colorMode === 'dark' ? 'gray.200' : 'gray.800'}
    >
      Test
    </Box>
  )
}

export default DynamicComponent
```

into styled components detecting the theme on `body`:

```ts
import React from 'react'
import { Box, ITheme, useTheme } from '@chakra-ui/core'
import styled from '@emotion/styled'

const StyledBox = styled(Box)<{ theme: ITheme }>`
  body.dark-mode & {
    background-color: ${p => p.theme.colors['gray'][800]};
    color: ${p => p.theme.colors['gray'][200]};
  }

  body.light-mode & {
    background-color: ${p => p.theme.colors['gray'][200]};
    color: ${p => p.theme.colors['gray'][800]};
  }
`

const StyledComponent = ({}) => {
  const theme = useTheme()
  return <StyledBox theme={theme}>Test</StyledBox>
}

export default StyledComponent
```

It's quite ugly though, as it drops all the awesomeness of working with style props.

**Comment by bwillem** [comment]
Just commenting so I get updates on this. Also experiencing the issue.

Thanks to segunadebayo and all the contributors for this super awesome library. 👍

**Comment by b-b0t** [comment]
+1

**Comment by skingston91** [comment]
If you don't need it inside of gatsby and are using it with the chakraUI plugin you can turn it off in the gatsby-config.js, if that helps anyone.
```
  plugins: [
    {
      resolve: "gatsby-plugin-chakra-ui",
      options: {
        /**
         * @property {boolean} [isUsingColorMode=true]
         * if false, this plugin will not use <ColorModeProvider />
         */
        isUsingColorMode: false,
      },
    },
```

**Comment by jana-uoft** [comment]
A possible solution I found that does the trick.

Since NextJS's initial render is server-side, the value read from local storage is always set to 'light'.
We can make use of this by also storing the dark mode preference value in cookies (non-http).

This way, we can grab the initial value from `App.getInitialProps` and pass it to the `ColorModeProvider` context when initializing it. 

_app.js
```
import {
  ThemeProvider,
  CSSReset,
  ColorModeProvider
} from '@chakra-ui/core'
import cookies from 'next-cookies'

import theme from '../utils/theme'

const App = ({ Component, pageProps, initialColorMode }) => {
  return (
    <ThemeProvider theme={theme}>
      <ColorModeProvider value={initialColorMode}>
        <CSSReset />
        <Component {...pageProps} />
      </ColorModeProvider>
    </ThemeProvider>
  )
}

App.getInitialProps = async ({ Component, ctx }) => {
  let pageProps = {}
  if (Component.getInitialProps) {
    pageProps = await Component.getInitialProps(ctx)
  }
  const { isDarkMode = 'false' } = cookies(ctx)
  return {
    pageProps,
    initialColorMode: isDarkMode === 'true' ? 'dark' : 'light'
  }
}

export default App

```

We also have to wrap the `toggleColorMode` function to set the cookie value on change. 

Snippet from my `DarkModeToggle` button
```
const DarkModeToggle = ( ) => {
  const { colorMode, toggleColorMode } = useColorMode()

  const handleToggleDarkMode = ( ) => {
    toggleColorMode()
    document.cookie = `isDarkMode=${colorMode === 'light'}`
  }

  ....
```

And I am not sure if we still need the `noflash.js` script, but I included it anyway. 
```
// Insert this script in your index.html right after the <body> tag.
// This will help to prevent a flash if dark mode is the default.

(function () {
  // Change these if you use something different in your hook.
  var storageKey = 'darkMode'
  var classNameDark = 'dark-mode'
  var classNameLight = 'light-mode'

  function setClassOnDocumentBody (darkMode) {
    document.body.classList.add(darkMode ? classNameDark : classNameLight)
    document.body.classList.remove(darkMode ? classNameLight : classNameDark)
  }

  // Determine the source of truth from cookie
  const isDarkMode = window.document.cookie.match(/isDarkMode=([^;]*)/)[1] === 'true'
  setClassOnDocumentBody(isDarkMode)
  window.localStorage.setItem(storageKey, JSON.stringify(isDarkMode))
})()
```

**Comment by iammarkps** [comment]
@jana-uoft Does your solution break nextjs static optimization?

**Comment by jana-uoft** [comment]
> @jana-uoft Does your solution break nextjs static optimization?

Unfortunately, Yes 🔨

**Comment by franky47** [comment]
FYI, there has been a very interesting article written by Josh Comeau about solving Dark Mode with SSR, originally aimed at Gatsby, but which raises similar issues as Next.js:
https://joshwcomeau.com/gatsby/dark-mode/

**Comment by fastengineer** [comment]
in next js you can disable ssr for a dynamic component.

**Comment by b-b0t** [comment]
Firstly this is an issue with `use-dark-mode` package itself that Chakra uses.
Having gone through every possible solution to this problem it seems that the best way to accomplish this without breaking static optimisation is using css variables.

This article was inspired by Josh's article but applied to Next.js (using styled components but I use the built in style jsx): https://brianlovin.com/overthought/adding-dark-mode-with-next-js

I also implemented variables allowing showing and hiding of divs using a class.

```
          body.light-mode {
            --lightmode: block;
            --darkmode: none;
          }

       .light {
         display: var(--lightmode);
       }
```

**Comment by Kozie1337** [comment]
Try modifying the _app.js file to wait with  the app hydration until the user mounts the site:

```
function App({ Component, pageProps }) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <ThemeProvider theme={theme}>
      <ColorModeProvider>
        <CSSReset />
        {mounted && <Component {...pageProps} />}
      </ColorModeProvider>
    </ThemeProvider>
  );
}
```
