### ISSUE TITLE
Editable defaultValue is not updating

### ISSUE THREAD

**Issue by delucca** [chakra-ui/chakra-ui#3497]
# 🐛 Bug report

The `Editable` component is not updating the `defaultValue` property. Explaining my scenario: in the first render, the provided default value for my component is `null`. After fetching data from my remote server it should update the `defaultValue` with the new provided value.

But, Editable completely ignores the new prop I'm passing to it.

## 💥 Steps to reproduce

1. Go to [my reproduction](https://codesandbox.io/s/chakra-editable-default-value-bug-nk5xq?file=/src/App.tsx)
2. You should see the `NOK` message rendered
3. Check the code. As you can see, in the first render it is passing `value` as `null`, so in my coalesce logic it is rendering the fallback option.
4. Check the code again. As you can see, in the second render it is passing `value` as `OK`, so, it should render `OK` in the `defaultValue` instead.

## 💻 Link to reproduction

https://codesandbox.io/s/chakra-editable-default-value-bug-nk5xq?file=/src/App.tsx

## 🧐 Expected behavior

The `defaultValue` should be updatable.

**Comment by segunadebayo** [comment]
Hi @delucca,

Because most components in Chakra are designed following the concept of controlled vs uncontrolled components, you shouldn't be updating the defaultValue of an uncontrolled component.

What you want to reach for is the controlled version of the component, kindly use the `value` and `onChange` props to handle this behavior.

```jsx
const EditableTest = ({ value, onChange }) => {
  const defaultValue = value ?? 'NOK'

  return (
    <Editable value={defaultValue} onChange={onChange}>
      <EditablePreview />
      <EditableInput />
    </Editable>
  )
}
```

**Comment by delucca** [comment]
Hi @segunadebayo 

Thanks for the explanation!
