### ISSUE TITLE
stylesheets wont load after build

### ISSUE THREAD

**Issue by electather** [chakra-ui/chakra-ui#3498]
# 🐛 Bug report

I recently developed a landing page for our system everything works fine  in development environment but things start to break after building my package. at first some of the styles won't load. change a few pages or load a dynamically gererated page and no stylesheet loads completely breaking the page. 

## 💥 Steps to reproduce

developing complex pages

## 💻 Link to reproduction

https://irdt-web-client-neon.vercel.app/

## 🧐 Expected behavior

for everything to work as expected. everything works fine in dev. it all goes wrong in prod

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |        1.2.1    |
| browser|        chrome    |

**Comment by with-heart** [comment]
Hi @electather! Sorry to hear that you're having issues. Unfortunately your steps to reproduce and link to reproduction don't help us reproduce your specific problem, so there's not really any way for us to help you right now. Please share the repo for your site or create a minimal reproduction in CodeSandbox that has the same problem so we can take a look!

**Comment by segunadebayo** [comment]
I can't reproduce this as well.

**Comment by segunadebayo** [comment]
Kindly re-open when there's a reproduction.

**Comment by electather** [comment]
@segunadebayo  I was able to fix this issue by downgrading few of my dependencies. including chakra ui to v1.2.1. we're in active development RN and i don't have the time to find what caused the problem now. I'll look into this issue in few days when things calm a bit.
