### ISSUE TITLE
Plugin @chakra-ui/gatsby-plugin is not compatible with your gatsby version 3.0.0 - It requires gatsby@^2.24.85

### ISSUE THREAD

**Issue by figgew** [chakra-ui/chakra-ui#3499]
# 🐛 Bug report

@chakra-ui/gatsby-plugin gives a dependency warning on upgrade to Gatsby 3.0.0

## 💥 Steps to reproduce

Upgrade to Gatby 3.0.0

## 🧐 Expected behavior

No warning

## 🧭 Possible Solution

Check if breaking changes, change dependency

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |            |
| Browser          |            |
| Operating System |            |

## 📝 Additional information

- Screenshots or code
- Notes or link to ideas

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. I pushed a fix for it and will be available in the next release
