### ISSUE TITLE
Add a way to set up line height on SkeletonText

### ISSUE THREAD

**Issue by naiaramartin** [chakra-ui/chakra-ui#3500]
In our app we have many places where we use Skeletons. Most of them are single line Skeletons and some SkeletonCircles, but we have only one usage for SkeletonText, which we use to emulate several paragraphs of text loading.
In the regular Skeleton component setting up the "height" or "h" attributes will affect the height of the "rectangle" that represents the text placeholder. However in SkeletonText, setting up the height affects to the entire paragraph, and not to each one of the lines in the paragraph. I'd like to have some attribute to change the line height on SkeletonText, as in other places the rectangles we render are taller and the size used by SkeletonText falls short in comparison.
<img width="385" alt="App : Document : Viewer - Skeleton ⋅ Storybook 2021-03-03 10-17-24" src="https://user-images.githubusercontent.com/2079601/109783262-15ab5800-7c0a-11eb-938c-55a736b24571.png">
<img width="210" alt="Theme - Nav ⋅ Storybook 2021-03-03 10-19-27" src="https://user-images.githubusercontent.com/2079601/109783266-1643ee80-7c0a-11eb-92fb-75e6777b74fa.png">

**Comment by dodas** [comment]
Hi @naiaramartin !

You can use the `skeletonHeight` prop on the `<SkeletonText>` component to set the line height.
I will take care of adding that to the docs.

<img width="749" alt="Screenshot 2021-03-04 at 13 56 45" src="https://user-images.githubusercontent.com/14360171/109967305-88433300-7cf1-11eb-87e7-9513a727ddc9.png">

**Comment by naiaramartin** [comment]
Thank you  @dodas ! `skeletonHeight` worked like a charm :-)

**Comment by codetheweb** [comment]
I just ran into this as well, I don't think it's been added to the docs yet.
