### ISSUE TITLE
Cannot override Heading fontSize if there is a textStyles value

### ISSUE THREAD

**Issue by PSalaun** [chakra-ui/chakra-ui#3501]
# 🐛 Bug report

It a fontSize value is defined in the `textStyles` object of the Theme for a Heading component, it seems like we cannot override it by passing a fontSize prop to the Heading.

## 💥 Steps to reproduce

- add a textStyles object to the Theme, with at least a fontSize property. It can be a string or a responsive value.
- add a Heading component and pass it the corresponding textStyle key
- try to override this font size by adding a fontSize props (or using sx props)

## 💻 Link to reproduction

https://codesandbox.io/s/chakra-heading-font-size-pr14s

## 🧐 Expected behavior

- it should be possible to override the textStyles font size value

## 🧭 Possible Solution

- it seems like the breaking version is 1.3.1, according to the codesandbox

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.3.3          |
| Browser          |    Chrome 88        |
| Operating System |      MacOS      |

## 📝 Additional information

- on the reproduction repo, overriding with `size` works, but not on my actual app (excepted when I pass both size and fontSize props); I don't understand why yet.

**Comment by kristian240** [comment]
I have a similar issue that might be connected. In my `theme.textStyles` I have this
```json
body1: {
    fontSize: [8, null, null, null, null, 9],
    lineHeight: [9, null, null, null, null, 10],
  },
```

And then, once I use this in code:

```jsx
<Text textStyle="body1">Lorem ipsum</Text>
```

And this works fine until I add additional property

```jsx
<Text textStyle="body1" mb={[0, 1, 2, 3]}>Lorem ipsum</Text>
```

I'm a bit busy, but I will try to create a sandbox for this issue as well.

**Comment by kristian240** [comment]
Here is a sandbox for my issue: https://codesandbox.io/s/elegant-banach-ds6c9?file=/src/App.tsx

**Comment by tonyjmartinez** [comment]
I'm running into the same issue, but with `fontWeight`. I'd expect to be able to override any of these `textStyle` values.

**Comment by segunadebayo** [comment]
We looked into this and I thought to some recommendations here:

- Don't combine the `<Heading />` with the text styles in the theme. Use `extendTheme` to change the `Heading` styles in `theme.components.Heading`.

- Override the Heading component theme completely by using `theme.components.Heading = { ... }`, and then you can leverage textStyles there.

```jsx
theme.components.Heading = {
  baseStyle: { 
    fontFamily: "heading",
    fontWeight: "bold",
 },
 sizes: {
   lg: {
      textStyle: "large-text",
   }
}
}
```

- If you want to use text styles for headings, consider creating yours with `<Box as="h2" textStyle="..." />`

We've seen that it's quite challenging to get this one right without affecting other style prop features.
