### ISSUE TITLE
FormControl doesn't have control over placeholder

### ISSUE THREAD

**Issue by kgnugur** [chakra-ui/chakra-ui#3502]
Hi,

You can easily check out the problem from the [sandbox](https://codesandbox.io/s/determined-field-n8yiz?file=/src/App.tsx). `FormControl` accepts `placeholder` props yet it does not work. Is it because typings are a bit loose on `FormControl`? 

Thanks.

**Comment by segunadebayo** [comment]
Hi @kgnugur,

This is happening because `placeholder` is a valid HTML attribute for a `<div/>` element. I know It can be confusing since you're rendering a `FormControl` element and you'd expect it to work.

Technically, this isn't a bug. Kindly pass the `placeholder` prop to the `Input` element.
