### ISSUE TITLE
Cannot set height of Button through Gatsby plugin theme

### ISSUE THREAD

**Issue by migueldlr** [chakra-ui/chakra-ui#3506]
# 🐛 Bug report

Setting styles like `textTransform`, `borderRadius`, `py`, etc. on `components.Button.baseStyle` in `@chakra-ui/gatsby-plugin/theme.js` works fine, but setting `height`/`h` to any value does not work.

## 💥 Steps to reproduce

1. Create minimal Gatsby project with `npm init gatsby` (https://www.gatsbyjs.com/docs/quick-start/)
2. Add Chakra UI with steps from: https://chakra-ui.com/guides/integrations/with-gatsby
3. Add `src\@chakra-ui\gatsby-plugin\theme.js`
4. Use `extendTheme` to add styling through `components.Button.baseStyle`
5. Create a `<Button>`
6. Observe that other styles are modified, but not height

Here's an example of a theme I used in the demo repo:
```
const theme = extendTheme({
    components: {
        Button: {
            baseStyle: {
                // These styles all get applied correctly
                textTransform: 'uppercase',
                borderRadius: 0,
                py: '4px',

                // None of the following lines sets the Button height to 'min-content'
                // height: 'min',
                // height: 'min-content',
                // h: 'min-content',
                h: 'min',
            },
            defaultProps: {
                colorScheme: 'purple',
                // This also doesn't work
                h: 'min',
            },
        },
    },
});
```

## 💻 Link to reproduction

Here's a minimal demo repo that shows this: https://github.com/migueldlr/chakra-gatsby-button-height-demo
And a Vercel deployment: https://chakra-gatsby-button-height-git-main-migueldlr.vercel.app/

## 🧐 Expected behavior

Setting `height` in `theme.js` should alter the height of the `Button`.

## 🧭 Possible Solution

I wish I knew 😭

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.3.3 |
| Gatsby | 3.0.1 |
| `@chakra-ui/gatsby-plugin` | 1.0.1 |
| Browser          | Chrome |
| Operating System |  Windows  |

## 📝 Additional information

![image](https://user-images.githubusercontent.com/8410924/110060221-93b74e00-7d33-11eb-8bea-fdc06ee6c5ff.png)
The bottom button has `h="min"` set inline to show the desired effect.

**Comment by PSalaun** [comment]
Have you tried using the `sizes` property to set the height? Here is a simplified example of my theme, with Gatsby plugin:
```
const themedButton = {
  baseStyle: {
    borderRadius: 0,
    cursor: 'pointer',
    textTransform: 'uppercase',
  },
  defaultProps: {
    colorScheme: 'primary',
  },
  sizes: {
    md: {
      height: 'auto',
      minHeight: 8,
    },
  },
  variants: {
    solid: {
      bg: 'primary.500',
      color: 'black',
    },
  },
};
```

**Comment by migueldlr** [comment]
@PSalaun this works perfectly! Thank you!
