### ISSUE TITLE
deps "lodash.mergewith" not found

### ISSUE THREAD

**Issue by binajmen** [chakra-ui/chakra-ui#3507]
# 🐛 Bug report

I'm trying to add new package with `yarn add ..` but I receive the following error:
```
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@/types/lodash.mergewith/-/lodash.mergewith-4.6.6.tgz: Request failed \"404 Not Found\"".
```

I have the same issue whith the package `object-assign`. Both packages are listed as dependencies in `yarn.lock`:
```
  "@chakra-ui/utils@1.2.0":
    version "1.2.0"
    resolved "https://registry.yarnpkg.com/@chakra-ui/utils/-/utils-1.2.0.tgz#9385950e91455ecf480eb52bca268d3a5f8c9d6d"
    integrity sha512-oMTX8BX1+MUf+iYUafFm9tNfwa3m1cqzMcE/5iQFmNcqKlZmuADnVL28Yw7jhoeouIjANaGY+f51qj9zHgDn9Q==
    dependencies:
      "@/types/lodash.mergewith" "4.6.6"
      "@/types/object-assign" "4.0.30"
      css-box-model "1.2.1"
      lodash.mergewith "4.6.2"
```

## 💥 Steps to reproduce

Install a new package using `yarn add`

## 🧐 Expected behavior

Not having this error

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.3.3       |
| Browser          |      Chrome      |
| Operating System |        macOS    |

## 📝 Additional information

Anybody using Chakra UI should have the same error I guess ? Any steps to correct that ? It is kind of blocking since I don't want to remove dependencies or Chakra, but on the other side I need to be able to install new packages..

**Comment by with-heart** [comment]
Considering that this dependency was added 6 months ago and we haven't had any other reported issues, I don't think it's a problem on our end. `@types/lodash.mergewith@4.6.6` is a valid package and I'm able to install it locally with no issues, but for some reason, your `yarn` is pointing you to a url that doesn't exist. 

Can you try running `yarn cache clean` and then `yarn install`?

**Comment by binajmen** [comment]
No sorry it was on my end !

**Comment by with-heart** [comment]
Mind posting how you fixed it, just in case someone else runs into a similar issue in the future? :)

**Comment by binajmen** [comment]
Sure. But I doubt someone else will run in the same issue as it was a really (really) dumb mistake 😅

I applied the `paths` solution from `tsconfig.json` after I learned about this trick while I was bored to use `../../../`.

I did some search/replace in vscode. I forgot to exclude yarn.lock.. @types definition packages changed to @/types. Therefore some dependencies were just not valid.. Oops 🤭

**Comment by with-heart** [comment]
> Sure. But I doubt someone else will run in the same issue as it was a really (really) dumb mistake 😅

You never know! What seems like a dumb mistake to you is just a natural part of the development process imo. We all make mistakes and run into situations that make us feel dumb, we're only human after all 😁 

> I forgot to exclude yarn.lock.. @types definition packages changed to @/types

Ahhhhhhhhhhh that makes sense! I was wondering what would cause that to end up as `@/types`.

Glad you got were able to resolve your issue!
