### ISSUE TITLE
Using shorthand with responsive value breaks pseudo class breakpoints order

### ISSUE THREAD

**Issue by PSalaun** [chakra-ui/chakra-ui#3508]
# 🐛 Bug report

When using responsive values in shorthands props, it breaks the breakpoints order in the before pseudo class. For instance, this code is gonna display "hello" on XL breakpoint:
```
<Box
        color={{ base: "red", xl: "blue" }}
        _before={{
          base: { content: '"hello "' },
          xl: { content: '"hello XL"' }
        }}
/>
```
but this one will display "hello XL" like it should:
```
<Box
        color="red"
        _before={{
          base: { content: '"hello "' },
          xl: { content: '"hello XL"' }
        }}
/>
```

When using SX for the prop, it doesn't break:
```
<Box
        sx={{ color: { base: "red", xl: "blue" } }}
        _before={{
          base: { content: '"hello "' },
          xl: { content: '"hello XL"' }
        }}
/>
```

## 💥 Steps to reproduce

1. Create a Box or Text (didn't tried others) component, and pass a responsive value to any shorthand prop + a responsive _before (or any pseudo class like _hover) value.
2. Resize your screen and notice that on larger breakpoints, the smallest breakpoint's values are not superseded

## 💻 Link to reproduction

https://codesandbox.io/s/chakra-responsive-pseudo-class-jhwku

## 🧐 Expected behavior

Pseudo classes responsive values should work when using responsive values in shorthand props.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.3.3       |
| Browser          |     Chrome, Firefox       |
| Operating System |      MacOS      |

## 📝 Additional information

**Comment by segunadebayo** [comment]
This seems to be a wrong usage of the responsive prop. Here's what the correct usage would be:

```jsx
<Box
        color={{ base: "red", xl: "blue" }}
        _before={{
           content: { base: '"hello "', xl: "hello XL" },
        }}
/>
```

I'm not sure why it worked for the `sx` prop 😃   . Kindly use the recommended approach as mentioned above.

Thanks

**Comment by PSalaun** [comment]
Wow, I don't know how I did such a basic mistake indeed 🤔
