### ISSUE TITLE
Colors not replaced in a styled component

### ISSUE THREAD

**Issue by lukemcgregor** [chakra-ui/chakra-ui#3517]
# 🐛 Bug report

When I create a new component and specify a style in the extended theme for that component colors like 'red.500' are not replaced with their hex value when injected into the component, instead they retain their variable key (eg 'red.500') which doesn't work in css

## 💥 Steps to reproduce

1. Create a new react app and install chakra as per docs
2. add a new component
3. Theme that component with a color
4. import the theme from chakra using useStyleConfig
5. apply that theme to a regular react Dom element (eg div).

expected: the color is correctly set
actual: no color is set

## 💻 Link to reproduction

https://codesandbox.io/s/zen-mahavira-5dq4b?file=/src/App.js

This should draw a red box (100 x 100), however the background color isn't set from the theme as its color value isn't a valid color.

## 🧐 Expected behavior

When getting a theme back from useStyleConfig, variables should be replaced with their actual values.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  "@chakra-ui/react": "^1.3.4"          |
| Browser          |   brave        |
| Operating System |   osx         |

## 📝 Additional information

I console logged the results of `useStyleConfig('TestComponent')` from my code example, it contains `backgroundColor: 'red.500',` not `backgroundColor: '#E53E3E'` which doesn't work when put into the style on a react element (like div). It does seem to work if I change div to Box, however this won't work for a bunch of use cases (like styling a component from npm).

**Comment by PSalaun** [comment]
I don't think you're supposed to use the value of `useStyleConfig` as normal CSS styles in a div. I believe you must use it with a Chakra component, like `<Box sx={styles} />` or `<Box {...styles} />`

**Comment by lukemcgregor** [comment]
Is there another way to style an existing component I should be looking into? I can’t change the component I want to style as it’s from a library.

**Comment by PSalaun** [comment]
You may want to check `useToken` https://chakra-ui.com/docs/hooks/use-token

**Comment by lukemcgregor** [comment]
thanks ill give that a go
