### ISSUE TITLE
Switch should be able to have an Icon on its slider

### ISSUE THREAD

**Issue by Jackbaude** [chakra-ui/chakra-ui#3518]
# 🚀 Feature request
Switch to have an Icon/ Element in it

## 🧱 Problem Statement / Justification
I want my darkmode switch to have an icon showing whether its in dark mode or light mode. This could be done with a normal button but I like the satisfaction of the switch, however, the switch does not allow to have an icon in it.

## ✅ Proposed solution or API
Have a prop for `<Switch/>` to add a element, such as an Icon.

## ↩️ Alternatives
Like I said I could use a button but I want to be able to use this with a swtich.

## 📝 Additional Information
![image](https://user-images.githubusercontent.com/25142905/110259327-b41e1d00-7f6c-11eb-9fd6-51e526ea1115.png)
![image](https://user-images.githubusercontent.com/25142905/110259340-c1d3a280-7f6c-11eb-96bd-e325116083aa.png)

**Comment by adamint** [comment]
This is a great idea

**Comment by jatin33** [comment]
@segunadebayo I am interested in picking this up, please assign me

**Comment by Jackbaude** [comment]
> @segunadebayo I am interested in picking this up, please assign me

if not assigned feel free to make pr

**Comment by segunadebayo** [comment]
After much thought, I really think this should be a "recipe" or Codesandbox "example". We don't have plans to add this component.

@jatin33, if you want, please create an example that uses the internal implementation of Switch, we can add it as a recipe and post it in our discord as well.

Thank you.

**Comment by Jackbaude** [comment]
@jatin33 update me when/ if you finish this

**Comment by Jackbaude** [comment]
Has there been any update on this?

**Comment by probability-is-logic** [comment]
@segunadebayo Any updates on this?

**Comment by downdrown** [comment]
I came across this post because I wanted to achieve the same thing, unfortunately I didn't find any "recipe" or example for this.

I played around a little bit and managed to add an icon to the `Switch` component. [This](https://imgur.com/a/Ib9Y7OF) is how it looks and you can find a code sandbox [here](https://codesandbox.io/s/chakra-ui-switch-icon-u164jg?file=/src/theme.tsx).

**BUT**

I'm actually not quite sure that this is the *best* solution, I'm not too experienced with web development so this is the best thing I could do. If there's anything I could enhance I'd love to get some feedback. 😃

**Comment by kyar1s** [comment]
I had the same problem. I am a front-end developer, im working on next and im not really happy with chakra ui. I saw the code that the merge and looks like that: 

`import { FormLabel, Icon, IconButton, Switch } from "@chakra-ui/react";
import React, { useState } from "react";
import { BiDollarCircle } from "react-icons/bi";
import { IoLogoEuro } from "react-icons/io";

const Switcher: React.FC = () => {
  const [themeMode, setThemeMode] = useState<"light" | "dark">("dark");
  return (
    <FormLabel
      htmlFor="theme-switcher"
      as={"label"}
      display="flex"
      alignItems="center"
      justifyContent="center"
      gap={2}
      position="relative"
    >
      <IconButton
        aria-label="Toggle light dark mode"
        onClick={() => setCurrency(currency.includes("euro") ? "dollar" : "euro")}
        icon={currency === "euro" ? <IoLogoEuro /> : <BiDollarCircle />}
      />
    </FormLabel>
  );
};

export default Switcher;
`

It looks like a button and it switch between those icons... 
![image](https://user-images.githubusercontent.com/45215699/209120801-0d42a8d0-9132-46b2-bd1c-5e0836ebb364.png)
![image](https://user-images.githubusercontent.com/45215699/209120852-83baaf1f-fb4e-4c9b-ba8f-9b61b07c87b0.png)

I didnt want a result like that so i didnt by myself with a little animation... 
px are orientative. I suggest to use rem instead. 
bg and colors are able to be custom. 

`import { Box, FormLabel, Icon, Input } from "@chakra-ui/react";
import React, { useState } from "react";
import { BsSunFill, BsFillMoonFill } from "react-icons/bs";

const Switcher: React.FC = () => {
  const [themeMode, setThemeMode] = useState<"light" | "dark">("dark");
  return (
    <FormLabel
      htmlFor="theme-switcher"
      as={"label"}
      display="flex"
      alignItems="center"
      justifyContent="center"
      gap={2}
      position="relative"
    >
      <Input
        id="theme-switcher"
        type="checkbox"
        checked={themeMode.includes("light") ? true : false}
        onChange={() => setThemeMode(themeMode.includes("light") ? "dark" : "light")}
        display="inline-block"
        appearance="none"
        cursor="pointer"
        height="24px"
        width="48px"
        backgroundColor="blue.50"
        border="1px solid"
        borderColor="blue.200"
        borderRadius="full"
      />
      <Box
        className={`iconMove `}
        transition="all 0.2s ease-in"
        transform={`${themeMode.includes("light") ? "translateX(0)" : "translateX(24px)"}`}
        position="absolute"
        cursor="pointer"
        top={"1px"}
        left={"1px"}
        w={"22px"}
        h={"22px"}
        bg="blue.900"
        borderRadius="full"
      >
        <Icon
          as={themeMode.includes("light") ? BsSunFill : BsFillMoonFill}
          padding="2px"
          w={"22px"}
          h={"22px"}
        />
      </Box>
    </FormLabel>
  );
};

export default Switcher;
`

Result as: 
![image](https://user-images.githubusercontent.com/45215699/209129987-9c08fe63-8673-48c5-a39d-71050395bde9.png)

![image](https://user-images.githubusercontent.com/45215699/209129940-371a3f43-7cc2-46c8-a07c-299875e461d8.png)


It is my first time using chackra ui. Maybe there is some ways to improve it, but for me thats the best one. Also... I know there should be one way to change the icon with framer-motion to do a cool transformation, but i didnt spend time to investigate that. 

Kind regards!
kyar1s ;)

**Comment by barrymichaeldoyle** [comment]
I'm quite disappointed that this isn't something that is planned to be added 😞
