### ISSUE TITLE
styling props for child margins (or "gutters")

### ISSUE THREAD

**Issue by ianstormtaylor** [chakra-ui/chakra-ui#352]
**Is your feature request related to a problem? Please describe.**

Right now the `<Stack>` component is a little confusing to use. It's [been suggested](https://github.com/chakra-ui/chakra-ui/pull/277) to change it to use margin-based styling using the `* + *` selector instead. I agree with this approach.

**Describe the solution you'd like**

But I think there's room to improve it further, and make it a more general purpose styling attribute instead of needing to have a dedicated `<Stack>` component. I've done this locally for a while and come to really like it.

Similar to how we have `mx` and `my`, I've used "gutter" styling props:

```jsx
<Box gy="1">
  ...
</Box>
```

This equates to:

```css
* + * {
  margin-top: ...;
}
```

Or using horizontal gutters:

```jsx
<Box gx="1">
  ...
</Box>
```

Equates to:

```css
* + * {
  margin-left: ...;
}
```

**Additional context**

I've used this myself for while and it has made adding gutter styles in one-off places a lot easier than having to mess with the component hierarchy. Just an idea for this library!

(Obviously there are cases where it's better to use flexbox, grid or columnar layout, and these wouldn't involve the `gx/gy` props. But for cases where a regular layout is what you want, but you want to add spacing between children, these props can be very helpful.)

**Comment by segunadebayo** [comment]
I agree, for the next release, we've updated the Stack component to use `* + *` CSS selector.

I kinda like the idea of `gx/gy`, I'll think about it a bit more. Thanks for bringing it up

**Comment by segunadebayo** [comment]
We've decided not to use this approach for now, as it introduces a new set of prop users need to get used to.

To cover for this, we've created a number of layout components to make this a lot easier.

Thank you once again, for this suggestion.

**Comment by ianstormtaylor** [comment]
For future folks, I found a very simple solution for this use case which is better than my previous suggestion or the `Stack` component at all:

```ts
<Box display="grid" gridRowGap={1}>
  ...
</Box>
```

**Comment by with-heart** [comment]
> For future folks, I found a very simple solution for this use case which is better than my previous suggestion or the `Stack` component at all:
> 
> ```tsx
> <Box display="grid" gridRowGap={1}>
>   ...
> </Box>
> ```

You can shorthand that to `<Grid rowGap={1}>` :)
