### ISSUE TITLE
Add documentation for built-in `keyframe` method.

### ISSUE THREAD

**Issue by dmahajan980** [chakra-ui/chakra-ui#3523]
The current Chakra UI documentation does not contain any information regarding the built-in `keyframe` method. Given this and the fact that Chakra UI comes with Framer Motion (and Emotion), it portrays a wrong impression that Chakra itself doesn't provide any methods to write custom animations. We should add some information for this method with relevant examples. Having information about such methods would help users seeking non-third party solutions without trawling through the Chakra codebase.

**Comment by segunadebayo** [comment]
Hi @dmahajan980,

We don't have a built-in `keyframe` function. It's only a re-export from `@emotion/react`:

```jsx
export { keyframes } from "@emotion/react"
```

We only do this internally to avoid added `@emotion/react` to dependencies for consuming components.

We recommend using emotion's keyframe as a way to add custom animations to your project.
Reference: https://emotion.sh/docs/keyframes

**Comment by dmahajan980** [comment]
Hi @segunadebayo,

I'm not sure what you mean exactly by "re-export". However, the `keyframe` method imported from Chakra is quite different (at least syntactically) from the one provided by `@emotion/react`:

``` javascript
import { Button as ChakraButton, keyframes } from '@chakra-ui/react'

const pulse = keyframes({
    '0%': {
        transform: 'translate3d(0, 0, 0) scale(1)',
    },
    '50%': {
        transform: 'translate3d(0, 0, 0) scale(1.1)',
    },
    '100%': {
        transform: 'translate3d(0, 0, 0) scale(1)',
    },
})

const Button = ({ children, ...props }, ref) => {
    return (
        <ChakraButton
            animation={`${pulse} 1s infinite linear`}
            {...props}
        >
            {children}
        </ChakraButton>
    )
}

export default Button
```

I don't have a Codepen example at the moment, but this did work in my project. If I understood correctly then is the above `keyframe` method a derived version of the one provided by `@emotion/react`?
