### ISSUE TITLE
[Tooltip] Placement `auto-end` works just like `auto-start`

### ISSUE THREAD

**Issue by DarthVitalus** [chakra-ui/chakra-ui#3528]
# 🐛 Bug report

Placement `auto-end` works just like `auto-start`

## 💥 Steps to reproduce

1. Go to https://chakra-ui.com/docs/overlay/tooltip#placement
2. Scroll page to see button with `auto-end` tooltip at the very bottom of the page (thus tooltip should appear above button)
3. Hover over button
4. Tooltip appears at the `auto-start` position

## 🧐 Expected behavior

Tooltip appears at the `auto-end` position (top right) (see screenshot)

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.3.4 |
| Browser          |   Chrome   |
| Operating System | MacOS  |

## 📝 Additional information

![Снимок экрана 2021-03-09 в 18 29 35](https://user-images.githubusercontent.com/20593651/110495401-85877a00-8105-11eb-949f-650ea0a69c18.png)

**Comment by segunadebayo** [comment]
This has been fixed in #3583. We'll release an update shortly.
