### ISSUE TITLE
Missing styling for toasts (and only toasts)

### ISSUE THREAD

**Issue by screw123** [chakra-ui/chakra-ui#3535]
# 🐛 Bug report

v1.3.4 of the chakra-ui seems to have missing styling for toast.

## 💥 Steps to reproduce

1. Create a brand new project with `yarn create react-app my-app --template @chakra-ui`
2. Copy and paste the code from https://chakra-ui.com/docs/feedback/toast#usage and start the project
3. Run the project

## 🧐 Expected behavior

Expect to see the toast as in doc website

But instead saw the toast styling is not applied, but the button is looking all fine.
I suppose there's some dependency issues like https://github.com/chakra-ui/chakra-ui/issues/2414, but it's not, because the button styling is working fine.

![1](https://user-images.githubusercontent.com/18388411/110602468-0192c800-81c1-11eb-90ab-358230176e76.gif)

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.3.4   |
| Browser          |  Firefox v87, Chrome v89  |
| Operating System |            |

**Comment by BillyPurvis** [comment]
I had a similar issue like this, but I found it was because I was calling the `useToast` hook inside the App component which was rendering the Chakra Provider, children of the App component worked, but the `useToast` would render exactly the same as you. 

I would believe this is because `useToast` cannot read the theme at this point. 

```
export const App = (): ReactElement => {
  const toast = useToast();

  return (
    <ChakraProvider brand={brand}>
      <Button
        onClick={() =>
          toast({
            title: 'Hello!',
            status: 'success',
            position: 'top-right',
          })
        }
      >
        Show Toast
      </Button>
    </ChakraProvider>
  );
};
```

Not sure if this helps your issue!

**Comment by screw123** [comment]
Thanks above, confirm the following would work:

```
export const App = () => {

    return (
        <ChakraProvider>
            <ToastButton />
        </ChakraProvider>
    )
}

const ToastButton = () => {
    const toast = useToast()
    return (
        <button onClick={() => toast({
            title: "Account created.",
            description: "We've created your account for you.",
            status: "success",
            duration: 1000,
            isClosable: true,
        })}>Test</button>)


}
```

`useToast()` need to be called at least 1 level down from ChakraProvider.  I guess at some point of time this should be either documented, or update code, not sure what is the correct approach.

**Comment by ajendrex** [comment]
Hi!

I'm having this issue and I'm calling `useToast` several components below `ChakraProvider`; what can it be? do I need to add something special to the theme? I tried adding `Toast` but it keeps not working properly
