### ISSUE TITLE
Icon issues

### ISSUE THREAD

**Issue by theentirety** [chakra-ui/chakra-ui#3542]
# 🐛 Bug report

Two icons have rendering issues when trying to utilize them outside of the browser and properly converting them to outlines (needed for design systems like Figma):

**UpDownIcon**: 
It has viewBox="-1 -1 9 11" and it shouldn't have a negative origin (The other icons have viewBox="0 0 24 24" but this one is odd.)

**QuestionOutlineIcon**: 
The dot in the question mark is using a 1px stroke, but the size is less than 1px (0.88) so when it converts to outlines it fails as the inside of the outline creates an infinite overlap. The simple solution would be to make the dot greater than 1px in diameter.

**Comment by segunadebayo** [comment]
Hi @theentirety,

We recommend using `react-icons` for your project since we're looking to deprecate the icons package in the future.

We think using a library of consistent icons would help make your product more cohesive. `react-icons` give you that!
