### ISSUE TITLE
Be able to use textStyle prop with breakpoints ( textStyle={['do', 're', 'mi']} )

### ISSUE THREAD

**Issue by kousenlsn** [chakra-ui/chakra-ui#3544]
# 🚀 TextStyles prop with breakpoints

Be able to define multiple **textStyles** depending on breakpoint values at the component tag level.

## 🧱 Problem Statement / Justification

We have different font styles for different breakpoint sizes in your app following the UX design, but to have better code readability, it is best to have the breakpoint definition inside the components instead of at the **textStyle** definition.

## ✅ Proposed solution or API

```
<Heading as="h2" textStyle={["bold40", "bold40", "bold48"]} color="secondary.mid-dark" pt="44px">
    My variable title
</Heading>
```

## ↩️ Alternatives

1) Make a generic textStyle definition and have the breakpoints inside of it. 

This suffices, but it's harder to follow the UX design pages as we try to keep the same variants as the UXs ones.

```
// custom theme override text prop
hero2: {
    fontSize: [40, 40, 48, 48],
    lineHeight: ['40px', '40px', '48px', '48px'],
    fontWeight: '900',
    ...baseStyle,
},
[...]
```

2) Use useBreakpointValue hook.

This also suffices, and is what I want, but without the verbosity of having to call the hook here.

```
  const textStyle = useBreakpointValue({
    base: 'h1',
    sm: 'h1',
    lg: 'h2',
    xl: 'h2',
  });

  return (
    <Heading
      as="h2"
      textStyle={textStyle}
      color="grey.100"
      mt={[5, 5, 2]}
      mr={['75px', '75px', 0]}
      mb={['35px', '35px', 0]}
    >
      {children}
    </Heading>
  );
````

**Comment by segunadebayo** [comment]
Kindly provide a codesandbox reproduction of this issue. We'll re-open once you do.

PS: Please this against the most recent version of Chakra, I believe this was fixed.
