### ISSUE TITLE
Button that has `isDisabled=true` in SSR but not in browser, stay disabled after hydration

### ISSUE THREAD

**Issue by jokester** [chakra-ui/chakra-ui#3545]
# 🐛 Bug report

Hello, I think I encountered a possibly bug as described in title.

## 💥 Steps to reproduce

1. Define a component like:

```tsx
import { Button } from '@chakra-ui/react';
import React, { useState } from 'react';

export const DemoChakraInconsistentSsr = () => {
  const [disabled, setDisabled] = useState(typeof window === 'undefined');

  return (
    <Button disabled={disabled} onClick={() => setDisabled(!disabled)}>
      strange button
    </Button>
  );
};

```

2. When this component is used in SSR-enabled environment (I used next.js v10), the button stay in disabled state even after hydration.

## 🧐 Expected behavior

- After dehydration, the button is not disabled (browser rendering should had `isDisabled={false}`)

## 🧭 Possible Solution

A easier workaround is to disable such component in SSR. Couldn't find a perfect one by myself 😅 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | `@chakra-ui/react` v1.1 and v1.3 |
| Browser          | Chrome / Firefox latest |
| Operating System | osx / linux |

## 📝 Additional information

- Screenshots or code
- Notes or link to ideas

**Comment by rushi444** [comment]
One way to work around this is to use the useEffect hook: 
```javascript
  useEffect(() => {
    if (typeof window !== "undefined") {
      const handleDisabled = () => {
        setDisabled(false);
      };
      handleDisabled();
    }
  }, []);
```

**Comment by segunadebayo** [comment]
Thanks for chiming in @rushi444 and @spykr. Indeed it's a bug in your code @jokester.

**Comment by jokester** [comment]
Sorry I had wrong expectation with React's SSR and hydration. Thanks :heart:
