### ISSUE TITLE
Shadow disappears on hover/focus

### ISSUE THREAD

**Issue by ildan-gh** [chakra-ui/chakra-ui#3553]
# 🐛 Bug report

Components like Dropdown Menu or Alert Dialog lose shadow as soon as you hover or click on them.
(I'm not sure if this intentional?)

![gif1](https://user-images.githubusercontent.com/75571904/110843166-4b0a1280-82a8-11eb-8ac1-2f6a685683b6.gif)
![gif2](https://user-images.githubusercontent.com/75571904/110843175-4c3b3f80-82a8-11eb-90c2-8273eb902eca.gif)

## 💥 Steps to reproduce

Dropdown Menu: loses shadow if you hover 1) over MenuDivider, 2) over MenuGroup or 3) outside the dropdown
Alert dialog: loses shadow if you click on the dialog.

## 💻 Link to reproduction

Sorry I was trying to create a project on Codesandbox but it throws some weird error.

![unknown](https://user-images.githubusercontent.com/75571904/110845299-c1a80f80-82aa-11eb-9e19-b159c69f31c4.png)

## 🧐 Expected behavior

Components like Alert Dialog / Modal Dialog / Dropdown should not lose shadow if you hover/click on them.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.0.3           |
| Browser          |Chromium: 89.0.4389.72            |
| Operating System |Windows 10            |

**Comment by ansonkao** [comment]
Temporary workaround to avoid the flicker is to hardcode the boxShadow on `<MenuList />`

**Comment by leadream** [comment]
I found it's caused by `focus-visible`, it's normal after removing this library.

**Comment by leadream** [comment]
Current workaround:

```jsx
<MenuList sx={{'&:focus:not([data-focus-visible-added])': {shadow: 'base'}}}></MenuList>
```

**Comment by dlindenkreuz** [comment]
Workaround using the theme (based on @leadream's suggestion above):

```js
export const theme = extendTheme({
  components: {
    Menu: {
      baseStyle: {
        list: {
          "&:focus:not([data-focus-visible-added])": {
            shadow: "dark-lg" // default shadow
          },
        },
      },
    },
  }
})

**Comment by treece** [comment]
Hi,

I'm running @chakra-ui/react v1.7.4 and having this issue. The suggested work around apparently doesn't work anymore.

**Comment by travel-left** [comment]
new workaround for "@chakra-ui/react": "1.8.8"

in global css file
`.chakra-menu__menu-list {
    box-shadow: 0 8px 16px 0 rgba(56, 96, 165, 0.15) !important;
}`

**Comment by bouncingbumble** [comment]
new workaround for "@chakra-ui/react": "1.8.8"

in global css file
`.chakra-menu__menu-list {
    box-shadow: 0 8px 16px 0 rgba(56, 96, 165, 0.15) !important;
}`

**Comment by taitems** [comment]
Updating the no longer working example with the selector that worked for me in 2023, using v2.4.9 -- 
`:focus:not([data-focus-visible-added]):not([data-focus-visible-disabled])`

```js
export const theme = extendTheme({
  components: {
    Menu: {
      baseStyle: {
        list: {
          "&:focus:not([data-focus-visible-added]):not([data-focus-visible-disabled])": {
            shadow: "dark-lg" // default shadow
          },
        },
      },
    },
  }
})
```
