### ISSUE TITLE
RadioGroup TypeScript error when used with useState

### ISSUE THREAD

**Issue by lazarnikolov94** [chakra-ui/chakra-ui#3560]
# 🐛 Bug report

TypeScript throws an error on the `onChange` method of the `RadioButton` when we pass the setter method from `useState`. The underlying type of `onChange` is of type `StringOrNumber`, so that might be the issue.

## 💥 Steps to reproduce

1. Create a `RadioGroup` with some `Radio` buttons inside.
2. Create a state using `useState`.
3. Set the `onChange` method of the `RadioGroup` to the setter method obtained from `useState`.
4. TypeScript issue occurs on the `onChange`.

## 💻 Link to reproduction

[https://codesandbox.io/s/muddy-bush-f00jz?file=/src/index.tsx](https://codesandbox.io/s/muddy-bush-f00jz?file=/src/index.tsx)

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.3.4       |
| Browser          |            |
| Operating System |            |

**Comment by segunadebayo** [comment]
Thanks for this @lazarnikolov94. Pushed a fix for this.
