### ISSUE TITLE
rerendering theme provider re-renders components that use useColorMode

### ISSUE THREAD

**Issue by hesxenon** [chakra-ui/chakra-ui#3564]
https://github.com/chakra-ui/chakra-ui/blob/fa8273bb41ad667a113b99ed97d1ab39e5790e63/packages/color-mode/src/color-mode-provider.tsx#L127

means the value of `ColorModeContext` will change every time the `ColorModeProvider` rerenders which causes every 
component that uses `useColorMode` will rerender as well. 

I'd suggest wrapping this object in a `useMemo`, since the actual values probably change less often than the provider re-renders.

Use-Case: nested `ChakraProvider`s where the parent component rerenders (auth context, router context, micro-frontends). In this case it's undesirable for every compoent that consumes `useColorMode` to rerender.

**Comment by segunadebayo** [comment]
Thanks for this @hesxenon. I just pushed a fix for it.
