### ISSUE TITLE
[Drawer] Link with onClick do not close the drawer

### ISSUE THREAD

**Issue by SebastianChaca** [chakra-ui/chakra-ui#3571]
# 🐛 Bug report

I have a drawer with a Link from React-router-dom. When i click the link, the link works, im redirected to the given link. But the drawer remains  open. I tried using the onClose function from the useDisclosure hook but do not work.
It works when i use Link from Chakra, but the page refresh and that's no a expected behavior
I have  used onClicks functions on the Link tags with pure css  and always worked. 

Edit: My temporary solution is removing the Link for a button, and inside the onClick im using a history.push from react-router-dom
## 💥 Steps to reproduce

```
<Drawer>
     {....other components}
      <DrawerContent>
               <Link to="/" onClick={onClose}>>
                    Home 
               </Link>
     </DrawerContent>
</Drawer>
```

## 🧐 Expected behavior

Open the Drawer and when you click on the Links from React-Router-Dom i should get redirected and the drawer should close

**Comment by with-heart** [comment]
Bug Report asks for a reproduction. Will reopen when that is provided.
