### ISSUE TITLE
Focus on modal with Formik

### ISSUE THREAD

**Issue by prrrcl** [chakra-ui/chakra-ui#3579]
# 🐛 Bug report

> When We create an form on modal with formik auto manage values, we can't write on inputs. We think the focus is the problem.

## 💥 Steps to reproduce

> Clear and concise reproduction steps are important for us to be able to triage
> your issue in a timely manner

1. Go to https://codesandbox.io/s/nice-cookies-ixc35?file=/pages/index.js:184-363
2. Click on Actions
3. Open Modal
4. Try to write on fields.
5. When I try tab for change the input focus, it doesn't work.

## 🧐 Expected behavior

> Write without problems

## 🧭 Possible Solution

> Auto focus disable prop?

**Comment by segunadebayo** [comment]
Hi @prrrcl,

This isn't a bug. It is happening because the Menu component prevents the default keydown behavior. to get keyboard navigation working.

To fix get this working, I recommend wrapping your form around a container and adding `e.stopPropagation` to the wrapper.

```jsx
<form
      onKeyDown={(e) => {
        // we stop the keydown from input to propagate upward to the menu (which prevents default)
        e.stopPropagation();
      }}
      onSubmit={formik.handleSubmit}
    >
      <input
        value={formik.values.test}
        onChange={formik.handleChange}
        name="test"
      />
      <input
        value={formik.values.testTwo}
        onChange={formik.handleChange}
        name="testTwo"
      />
      <button type="submit">Save</button>
    </form>
```
