### ISSUE TITLE
Type '"enterKeyHint"' is not assignable to type 'keyof ClassAttributes<HTMLInputElement> | keyof InputHTMLAttributes<HTMLInputElement>'.

### ISSUE THREAD

**Issue by CaydenD** [chakra-ui/chakra-ui#3582]
# 🐛 Bug report

> Provide a brief description of the bug here

when attempting to build my app I get a type error from a file that comes from chakra-ui/react. the file is as follows ./node_modules/@chakra-ui/pin-input/dist/types/use-pin-input.d.ts:77:126. This only happens when i am building my app as when i am in development( im using next to build and dev) everything works just fine.

Error message: 
Type error: Type '"max" | "required" | "disabled" | "hidden" | "dir" | "form" | "slot" | "style" | "title" | "pattern" | "color" | "size" | "multiple" | "height" | "translate" | "width" | "prefix" | ... 269 more ... | "enterKeyHint"' does not satisfy the constraint 'keyof ClassAttributes<HTMLInputElement> | keyof InputHTMLAttributes<HTMLInputElement>'.
2021-03-15T00:15:42.574Z    Type '"enterKeyHint"' is not assignable to type 'keyof ClassAttributes<HTMLInputElement> | keyof InputHTMLAttributes<HTMLInputElement>'.

## 💥 Steps to reproduce

after running next build i get my error.

## 🧐 Expected behavior

The issue is that the problem is in files that are dependencies in my project so when i try to build the project elsewhere( in my case vercel) i get this issue and cannot mutate the files. 

## 🌍 System information

{
  "name": "with-chakra-ui",
  "version": "0.1.0",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "gen": "graphql-codegen --config codegen.yml"
  },
  "dependencies": {
    "@babel/core": "^7.0.0",
    "@chakra-ui/core": "^0.8.0",
    "@chakra-ui/icons": "^1.0.0",
    "@chakra-ui/react": "^1.3.4",
    "@chakra-ui/system": "^1.3.1",
    "@emotion/core": "10.x",
    "@emotion/react": "^11.1.5",
    "@emotion/styled": "10.x",
    "@urql/exchange-graphcache": "^4.0.0",
    "emotion-theming": "10.x",
    "formik": "^2.2.6",
    "framer-motion": "^3.7.0",
    "graphql": "^15.5.0",
    "graphql-tag": "^2.11.0",
    "isomorphic-unfetch": "^3.1.0",
    "next": "^10.0.7",
    "next-urql": "^3.0.0",
    "prop-types": "^15.6.2",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-is": "^17.0.1",
    "urql": "^2.0.1"
  },
  "license": "MIT",
  "devDependencies": {
    "@graphql-codegen/cli": "1.21.2",
    "@graphql-codegen/typescript": "1.21.1",
    "@graphql-codegen/typescript-operations": "1.17.15",
    "@graphql-codegen/typescript-urql": "^2.0.3",
    "@types/node": "^14.14.28",
    "@types/uuid": "^8.3.0",
    "typescript": "^4.1.5"
  }
}

## 📝 Additional information
![image](https://user-images.githubusercontent.com/69131993/111090013-7b4ded00-8504-11eb-938e-ba2125b5260e.png)
![image](https://user-images.githubusercontent.com/69131993/111090034-8e60bd00-8504-11eb-8210-9f5a64f7be45.png)

overall i am guessing this is an issue with the dependancies i have installed but im not sure if its a problem with the package itself.

**Comment by with-heart** [comment]
We have no way of diagnosing without the reproduction the template asked for!

**Comment by segunadebayo** [comment]
Hi @CaydenD,

Kindly provide a reproduction for this issue and we'll consider re-opening it.

Looking through the dependencies though, I think you'll run into issues. You're combining incompatible versions of Chakra UI and Emotion in your app. Considering cleaning it up a bit:

```diff
"@babel/core": "^7.0.0",
- "@chakra-ui/core": "^0.8.0",
"@chakra-ui/icons": "^1.0.0",
"@chakra-ui/react": "^1.3.4",
- "@chakra-ui/system": "^1.3.1",
- "@emotion/core": "10.x",
"@emotion/react": "^11.1.5",
- "@emotion/styled": "10.x",
- "@emotion/styled": "11.x",
"@urql/exchange-graphcache": "^4.0.0",
-"emotion-theming": "10.x",
```
