### ISSUE TITLE
Default z-index for MenuList is lower than a Slider's thumb

### ISSUE THREAD

**Issue by hugolgst** [chakra-ui/chakra-ui#3592]
By default, the Menu has a lower z-index than the Slider's thumb which should not be the case.
![image](https://user-images.githubusercontent.com/15371828/111296038-52d10a80-864c-11eb-89c9-5337912e9e54.png)

**Comment by hugolgst** [comment]
Missed issue.

**Comment by ThomasFKJorna** [comment]
I am experiencing the same issue.
![image](https://user-images.githubusercontent.com/21983833/127670288-5bd14e63-f3eb-45df-84f2-4c5bd5610ce3.png)
![image](https://user-images.githubusercontent.com/21983833/127670315-e58956d6-eb2a-42ae-8e4f-1879de72e6a6.png)

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. Please provide a Codesandbox reproduction of this so we can resolve it quickly.

PS: I think this can be resolved by bumping up the zIndex of the `MenuList` or using the `isolation` CSS attribute.

**Comment by hugolgst** [comment]
Please do not close the issue because it is not solved. I know how to solve the issue but the fact is that it must be updated by default in Chakra's code since it is an unexpected behaviour.

**Comment by papo1011** [comment]
Hi
I solved the issue by adding zIndex="0" as attribute of SliderThumb.

<SliderThumb zIndex="0"/>

**Comment by hugolgst** [comment]
I think how to solve the issue is not the question here, it is more of a unexpected behaviour that should not happen.
We should fix that directly in Chakra's code
