### ISSUE TITLE
Toggle AccordionItem Programmatically

### ISSUE THREAD

**Issue by vinnymicale** [chakra-ui/chakra-ui#3599]
# 🚀 Feature request

> Please describe your request in one or two sentences.

AccordionItems should have the ability to be toggled programmatically. For example, I have several accordion items that I would want to all be expanded/collapsed when a button is pressed instead of clicking each one individually.

## 🧱 Problem Statement / Justification

> Please provide valid reason(s) why this should added to Chakra UI.
>
> If this feaure is related to a problem you've noticed. Mention it as well

There currently isn't a way to toggle AccordionItems other than clicking on them individually. If there are lots of accordion items, this could get annoying as opposed to being able to expand them all at once.

## ✅ Proposed solution or API

> Please provide code snippets, gists, or links to the ideal design or API

`<AccordionItem allowToggle allowMultiple **newPropertyThatsProbablyABoolean={true/false} />`**

## ↩️ Alternatives

> What alternative solutions have you considered before making this request?

I've tried to conditionally assign defaultIndex based on the boolean I have that is assigned a value when the toggle button is clicked, but this only works on the initial render.

## 📝 Additional Information

> What resources (links, screenshots, etc.) do you have to assist this effort?

**Comment by segunadebayo** [comment]
Hi @vinnymicale,

For this scenario, you want to control the accordion by passing the `index` and `onChange` props to `Accordion`. `defaultIndex` is used for the uncontrolled mode of the component and it only works on initial render.

```jsx
function Example() {
  const [index, setIndex] = React.useState([]);

  return (
    <>
      <Accordion allowMultiple index={index} onChange={setIndex}>
        {"..."}
      </Accordion>
      <button onClick={() => setIndex([])}>Close all</button>
    </>
  );
}
```

**Comment by jinnkhan88** [comment]
@segunadebayo can you share an example for this to work? I am trying to open the Accordion Item on click of a button but i m having a hard time with this. any help would be greatly appreciated.

**Comment by tae100k** [comment]
@segunadebayo 

Your code is giving me Type error below.

Type 'Dispatch<SetStateAction<never[]>>' is not assignable to type '(expandedIndex: ExpandedIndex) => void'.
  Types of parameters 'value' and 'expandedIndex' are incompatible.
    Type 'ExpandedIndex' is not assignable to type 'SetStateAction<never[]>'.
      Type 'number' is not assignable to type 'SetStateAction<never[]>'.
