### ISSUE TITLE
Add disable attribute to TagCloseButton

### ISSUE THREAD

**Issue by Martinnord** [chakra-ui/chakra-ui#360]
**Describe the bug**
`TagCloseButton` component doesn't allow passing in `isDisabled`.

**Expected Behavior**
I'd like to have the option to make a tag not removable. I think I could go around this by using the Button component, but this feels like something it should support right out the box.

**To Reproduce**
Try disabling the component.

**Suggested solution(s)**
Add `isDisabled` type field to its props.

Great library by the way, I love it

**Comment by segunadebayo** [comment]
Thanks for this issue, @Martinnord.

The team is heavily working on the TypeScript migration and would appreciate it if you can submit a PR for this. Thanks

I'm glad you love Chakra UI.

**Comment by Martinnord** [comment]
Sure @segunadebayo. Do you have a guide for PRs? It will be my first PR to OS 😅

**Comment by segunadebayo** [comment]
Sure @Martinnord, I'm happy to help in any way I can.

Here's a quick PR guide:
- Create a Fork of the project's `master` branch
- Run `yarn bootstrap` at the root to install dependencies
- Try `yarn storybook` to see if storybook opens correctly. If it does, then you're good to go.
- Go to `packages/Tag` 
- Complete the fix, and add the types for TagCloseButton in `index.d.ts`
- Submit your first PR 🥳

Here' s the line of code that needs to be updated: 
https://github.com/chakra-ui/chakra-ui/blob/49f2cda58dece076e3fa0b3b97f55dcd9b85f0bc/packages/chakra-ui/src/Tag/index.js#L29

As you'll see that the TagCloseButton passes all it's props to the `PseudoBox`, which means a walkaround, for now, is to pass the `disabled` prop to it. To fix it, you'll need to assign `isDisabled` prop to the `disabled` attribute.

That's all, I think.

It'll be good to have your first PR in Chakra UI 😄. Thanks again.
