### ISSUE TITLE
Can't change direction of Stack using Variants

### ISSUE THREAD

**Issue by vinicius507** [chakra-ui/chakra-ui#3602]
# 🐛 Bug report

## 💥 Steps to reproduce

1. Create `Stack` component
```js
export default function Component(props) {
  const  { variant } = props
  const styles = useStyleConfig('Component', { variant })
  return (
    <Stack sx={styles}>
        <Text as="span">text1</Text>
        <Text as="span">text2</Text>
        <Text as="span">text3</Text>
    </Stack>
  )
}
```
2. Create a component configuration with theme options
```js
export const Component = {
  baseStyle: {
    // [...]
  },
  variants: {
    variant1: {
      direction: 'column',
      color: 'red',
    }
  },
  // [...]
}
```
4. If `variant1` is set, `color` turns red but `direction` won't change.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/chakra-stack-bug-8uetx

## 🧐 Expected behavior

Change direction based on variant.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.3.4      |
| Browser          |      Firefox  86.0.1 (64-bit)    |
| Operating System |      Manjaro Linux      |

**Comment by segunadebayo** [comment]
Hi @vinicius507, this isn't a bug.

The `direction` prop doesn't work in the `sx` prop for `Stack`.

`Stack` wasn't designed to work with the component theming approach you're referring to. Consider passing props directly to it if you need to change the direction.

**Comment by vinicius507** [comment]
Thanks for the clarification!
