### ISSUE TITLE
How to change the text color for every shade of a color scheme?

### ISSUE THREAD

**Issue by jahirfiquitiva** [chakra-ui/chakra-ui#3603]
Hello

I would like to be able to set a specific text color for every shade of a color scheme (like when using the color as background) so it will always have enough contrast.

Right now, the colors used by default in Chakra aren't having enough contrast, so that's why.

Is it possible right now? would you mind adding such feature?

<img width="379" alt="Shot 2021-03-17 at 10-37-14@2x" src="https://user-images.githubusercontent.com/10360816/111517160-c47b8800-8722-11eb-8881-e5d66a68104e.png">

**Comment by segunadebayo** [comment]
Hi @jahirfiquitiva, I replied in the Discord channel.

At the moment, there's no way to change the color of every shade.

**Comment by jahirfiquitiva** [comment]
alright, thanks
