### ISSUE TITLE
Sticky Component 

### ISSUE THREAD

**Issue by yotam707** [chakra-ui/chakra-ui#3605]
# 🚀 Feature request

> Please describe your request in one or two sentences.

I would like to ask to create a sticky component since styling sticky components can be tricky. In my previous job, I worked with Semantic React where they had a sticky component that worked really well and I could position a few elements to sticky with no hassle [Refrence](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Sticky/Sticky.js)

## 🧱 Problem Statement / Justification

> Please provide valid reason(s) why this should added to Chakra UI.
> It's hard making components sticky (position sticky is nice but it's doesn't work well with when you have multiple sticky elements)
> If this feaure is related to a problem you've noticed. Mention it as well

## ✅ Proposed solution or API

> Please provide code snippets, gists, or links to the ideal design or API

## ↩️ Alternatives

> What alternative solutions have you considered before making this request?

## 📝 Additional Information

> What resources (links, screenshots, etc.) do you have to assist this effort?

**Comment by b-lawlor** [comment]
My solution was to use the sx prop like this:

`<Box
      sx={{
        position: '-webkit-sticky', /* Safari */
        position: 'sticky',
        top: '0',
      }}>`

This sticks the box to the top of the screen when you scroll past it

**Comment by segunadebayo** [comment]
Hi @yotam707,

After much thought, we won't be adding this component to Chakra for now. Feel free to make this component yourself and share the code publicly and here as well. We're happy to add it as a "recipe" on the website and discord as well.

Thanks for understanding.

**Comment by livevsonline** [comment]
> Hi @yotam707,
> 
> After much thought, we won't be adding this component to Chakra for now. Feel free to make this component yourself and share the code publicly and here as well. We're happy to add it as a "recipe" on the website and discord as well.
> 
> Thanks for understanding.

What is the reasoning for this? Could you elaborate why the decision was made not to include this?

**Comment by onurhan1337** [comment]
> My solution was to use the sx prop like this:
> 
> `<Box sx={{ position: '-webkit-sticky', /* Safari */ position: 'sticky', top: '0', }}>`
> 
> This sticks the box to the top of the screen when you scroll past it

Thanks, this example really worked for me. But I am getting an error message because `position` is used twice. Is there a better method for this? I want to create a seamless sticky table header for Safari and Mozilla.

**Comment by charlscooper** [comment]
In this example I was able to use the following props to achieve the sticky header. Hope this helps!

```js
<Thead
  css={{
    position: "-webkit-sticky",
  }}
  position="sticky"
  top="0"
  zIndex="1"
  bg="#0A1129"
></Thead>
```
> Note: Dependency `@emotion/react` being utilised to achieve the 'webkit-sticky' css property for safari compatibility.
