### ISSUE TITLE
<Image /> is fetching the resource twice

### ISSUE THREAD

**Issue by OmarZeidan** [chakra-ui/chakra-ui#3606]
# 🐛 Bug report

This did drive me crazy. I was wondering why my images are being fetched **twice** initiated once from `index.js` file and the second is from `react-dom.development` and nop, I am not using the "Strict mode" from React.

I removed the `<Image />` component and used the normal `<img />` tag and it worked perfectly fine.

## 💥 Steps to reproduce

1. Create a simple App
2. Use the AWESOME Chakra UI
3. Use the `<Image />` component
4. Run and check the browser network tab for your image(s)

## 💻 Link to reproduction

CodeSandbox reproduction: https://your-codesandbox-link-goes-here.io

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     ^0.8.0       |
| Browser          |            |
| Operating System |            |

**Comment by with-heart** [comment]
Hi Omar! Appreciate the kind words about Chakra being awesome. I'm going to close this though, as it's not an issue with Chakra. Not sure why `react-dom.development.js` is causing the second render if you're sure you're not using `StrictMode`, but it's not something Chakra could cause to happen. See #2899 for more info.
