### ISSUE TITLE
Toast doesn't perform dedup as stated in the docs

### ISSUE THREAD

**Issue by codetheweb** [chakra-ui/chakra-ui#3609]
# 🐛 Bug report

On the [docs page for the Toast component](https://chakra-ui.com/docs/feedback/toast), it says that the `id` prop is 

> Mostly used when you need to prevent duplicate.

However, duplicate toasts can be created when passing the ID.

## 💥 Steps to reproduce

1. Click "Click me!" multiple times.

## 💻 Link to reproduction

For some reason, it's not rendering correctly [in the sandbox](https://codesandbox.io/s/duplicate-toasts-t628o?file=/src/App.tsx); so I [deployed it to Vercel](https://csb-t628o-ho6puln0f-codetheweb.vercel.app/).

## 🧐 Expected behavior

Duplicate IDs are ignored.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.3.4         |
| Browser          |   Firefox 86         |
| Operating System |      macOS 11.2.3      |

**Comment by d4ncer** [comment]
Having the same issue.

**Comment by segunadebayo** [comment]
Here's how to solve this issue:

```jsx
function Foo() {
  const toast = useToast();
  const { toggleColorMode } = useColorMode();
  const id = "test-toast";
  return (
    <>
      <Button
        onClick={() => {
          if (!toast.isActive(id)) {
            toast({
              id,
              title: "Test Toast"
            });
          }
        }}
      >
        Click me!
      </Button>
      <Button onClick={() => toggleColorMode()}>Toggle Mode</Button>
    </>
  );
}
```

https://codesandbox.io/s/duplicate-toasts-forked-t41gq?file=/src/App.tsx:156-604

**Comment by codetheweb** [comment]
Thanks. I was going to update the docs but I see you [already did](https://github.com/codetheweb/chakra-ui/commit/65fbc414463ea729c0a63d337d300b0fb9395153). 😛
