### ISSUE TITLE
[TabPanel] No way to overflow using scroll

### ISSUE THREAD

**Issue by TransmissionsDev** [chakra-ui/chakra-ui#361]
**Describe the bug**
For a TabPanel, I want it to (on overflow) allow scrolling, however, even after adding `overflow="scroll"` as prop, I cannot seem to find a way to do so.

**Expected Behavior**
Able to scroll on the X or Y axis in the event of an overflow.

Am I missing something or is this a feature that is not in Chakra?

**Comment by segunadebayo** [comment]
Hi @TransmissionsDev,

Can you drop a codesandbox reproduction for this? I'll look into it and provide a solution right away. I believe you should be able to do so without any issues.

**Comment by TransmissionsDev** [comment]
@segunadebayo Here you go! Hope this helps: https://codesandbox.io/s/affectionate-yonath-bzdjg?fontsize=14&hidenavigation=1&theme=dark

**Comment by TransmissionsDev** [comment]
@segunadebayo Have you been able to find a solution? My client is bugging me to finish this up 😅

**Comment by TransmissionsDev** [comment]
> Hi @TransmissionsDev,
> 
> Can you drop a codesandbox reproduction for this? I'll look into it and provide a solution right away. I believe you should be able to do so without any issues.

@segunadebayo Have you been able to find a solution for this? Sorry to bug you, but my client is pushing me to meet this deadline 😅

**Comment by segunadebayo** [comment]
I just checked it. There's no problem with the `TabPanel`, it's mostly a styling issue.

You need to add `maxHeight` and `overflowY` to get it to work correctly.

Here's a working example: https://codesandbox.io/s/wonderful-gauss-6rc6b

**Comment by TransmissionsDev** [comment]
@segunadebayo Thank you for the response! However, the implementation you provided cuts off the last card (when you scroll down) when viewed as a full page. Can you help me with this? Thanks 😄 https://imgur.com/v05PbgL

**Comment by TransmissionsDev** [comment]
> I just checked it. There's no problem with the `TabPanel`, it's mostly a styling issue.
> 
> You need to add `maxHeight` and `overflowY` to get it to work correctly.
> 
> Here's a working example: https://codesandbox.io/s/wonderful-gauss-6rc6b

@segunadebayo Thank you for the response! However, the implementation you provided cuts off the last card (when you scroll down) when viewed as a full page. Can you help me with this? Thanks 😄 

https://imgur.com/v05PbgL

**Comment by EzeScigo** [comment]
> I just checked it. There's no problem with the `TabPanel`, it's mostly a styling issue.
> 
> You need to add `maxHeight` and `overflowY` to get it to work correctly.
> 
> Here's a working example: https://codesandbox.io/s/wonderful-gauss-6rc6b

maxHeight = 90vh won't work in most cases when you have the tabPanel in a panel with height < 100vh. Any chance height=100% would be admissible??? I dont want to use fixed px for this.
Thanks.

**Comment by Udit-takkar** [comment]
> @segunadebayo Thank you for the response! However, the implementation you provided cuts off the last card (when you scroll down) when viewed as a full page. Can you help me with this? Thanks 😄
> 
> https://imgur.com/v05PbgL

Did you get any solution for this? What height to set to display all items ?

**Comment by vytautas-pilk** [comment]
What works for me is setting `display='flex'` and `flexDirection='column'` for `<Tabs>` component and then `overflowY='scroll'` for `<TabPanels>` component.
