### ISSUE TITLE
Add `_target` to base box element as pseudoselector

### ISSUE THREAD

**Issue by ez-alexfrazer** [chakra-ui/chakra-ui#3617]
# 🚀 Feature request

> Please describe your request in one or two sentences.

I would like to be able to use `_target` as a pseudoclass on all elements

## 🧱 Problem Statement / Justification

> Please provide valid reason(s) why this should added to Chakra UI.
>
> If this feaure is related to a problem you've noticed. Mention it as well

Imagine a page like wikipedia, at a url like this: https://en.wikipedia.org/wiki/Naruto
You click on a section, and it updates the hash like so: https://en.wikipedia.org/wiki/Naruto#Production

It would be useful to have a `_target` pseudoselector that will allow you to style this. Here's some resources on it:
https://developer.mozilla.org/en-US/docs/Web/CSS/:target
https://css-tricks.com/on-target/

## ✅ Proposed solution or API

> Please provide code snippets, gists, or links to the ideal design or API

Effectively, should be pretty straightforward and easily fit in with the other APIs for `Box`:

```jsx
<Box
  _hover={{
    textDecoration: 'underline',
  }}
  _target={{
    color: 'cyan.500',
  }}
/>
```

## ↩️ Alternatives

> What alternative solutions have you considered before making this request?

- Global styles
- wrapping desired elements in `styled`

## 📝 Additional Information

> What resources (links, screenshots, etc.) do you have to assist this effort?

The spec from w3 here

https://drafts.csswg.org/selectors-4/#target-pseudo

**Comment by segunadebayo** [comment]
Hi @ez-alexfrazer,

We don't have plans to extend the pseudo-selectors just yet. Kindly use the `sx` or `css` prop in this case.

```jsx
<Box sx={{ "&:target": { color: "red.500" } }} />
```

Thanks
