### ISSUE TITLE
No transparency for subtle or accented toasts when using createStandaloneToast

### ISSUE THREAD

**Issue by JackWinterburn** [chakra-ui/chakra-ui#3628]
# 🐛 Bug report

When using createStandaloneToast to show a toast message on a page with either the subtle, left-accent or top-accent variants, there is no transparency and **on dark mode** the contrast between the text and the bright background is very difficult to read.

## 💥 Steps to reproduce

```javascript

import { Wrap, WrapItem, Button, createStandaloneToast } from "@chakraUI/react"

function ToastVariantsExample() {
  const toast = createStandaloneToast()
  const variants = ["subtle", "left-accent", "top-accent"]

  return (
    <Wrap>
      {variants.map((variant, i) => (
        <WrapItem key={i}>
          <Button
            onClick={() =>
              toast({
                title: `${variant} toast`,
                variant: variant,
                isClosable: true,
              })
            }
          >
            Show {variant} toast
          </Button>
        </WrapItem>
      ))}
    </Wrap>
  )
}
```

## 💻 Link to reproduction

CodeSandbox does not seem to be working for me, but this issue can be easily recreated on the chakra UI website by **enabling dark** mode, scrolling down to the "variants" section and changing "useToast" to "createStandaloneToast" and then clicking on the subtle or accented options for the toast messages

[link to chakraUI website](https://chakra-ui.com/docs/feedback/toast#variants)

## 🧐 Expected behavior

I expected that createStandaloneToast would work the same, however it seems that a styling issue has caused it to lack any transparency, which makes the text difficult to read since the background is so bright against the white text

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |1.3.4            |
| Browser          |Edge: version 89.0.774.57 and Chrome: version 89.0.4389.90            |
| Operating System |Windows 10 (64 bit)            |

## 📝 Additional information

image of createStandalone toast
![image](https://user-images.githubusercontent.com/52929068/111879922-783d7b80-89a0-11eb-9d64-a8c93332432c.png)

image of useToast
![image](https://user-images.githubusercontent.com/52929068/111879951-9acf9480-89a0-11eb-9379-e26e824a15f4.png)

**Comment by Qocotzxin** [comment]
This is still happening:


`
import theme from '@/utilities/theme';
import {createStandaloneToast} from '@chakra-ui/react';

...     
private toast = createStandaloneToast({theme});
private toastId = 'http-error-toast';

axios.interceptors.response.use(
      (response) => response,
      (error) => {
        if (this.toast.isActive(this.toastId)) return error;
        this.toast({
          variant: 'subtle',
          description: error.message,
          status: 'error',
          duration: 10000,
          isClosable: true,
          position: 'top',
          id: this.toastId,
        });
        return error;
      }
    );`

Not only with subtle, but with every other variant it won't add the transparency that is supposed to add, as @JackWinterburn  mentioned, it makes the text almost impossible to read in dark mode.

Btw, amazing library!

**Comment by Qocotzxin** [comment]
> Hi!
> This issue hasn't seen any activity recently. We close inactive issues after 35 days to manage the volume of issues we receive.
> If we missed this issue or you want to keep it open, please reply here. That will reset the timer and allow more time for this issue to be addressed before it is closed.

Can we reopen this?
