### ISSUE TITLE
How to set a hover color on Icons?

### ISSUE THREAD

**Issue by secretlifeof** [chakra-ui/chakra-ui#363]
**Describe the bug**
Thank you very much for this library. Trying it out for the first time for a project, and I like the simplicity. Just wondering what is the best way to set a hover color? I tried _hover but that did not work? A workaround is using the css-prop. But then the themes colours are not used.

```
import { css } from "@emotion/core"
<Icon
  name="read"
  color="red"
  css={css`
     &:hover {
        color: white;
      }
  `}
/>
```

**Comment by franklinjavier** [comment]
@secretlifeof you can find in codebase. Try _hover props

```jsx
  <PseudoBox
    as="button"
    bg="teal.500"
    py={2}
    px={4}
    ml={3}
    rounded="md"
    fontWeight="semibold"
    color="white"
    _hover={{ bg: "teal.600" }}
    _focus={{ boxShadow: "outline" }}
  >
    Sign Up
  </PseudoBox>
```

**Comment by secretlifeof** [comment]
@franklinjavier thank you. But I cannot get this working with <Icon />. For <IconButton /> there is a _hover but that only partly works. As an example for the Icons included in Chakra UI, I only managed to change the stroke color on hover.

This does not work:
```
<PseudoBox _hover={{ color: "blue", stroke: "blue" }}>
  <Icon name="menu" color="red" w={["2vw", "2vw", "5.5vw"]} h="auto" />
</PseudoBox>
```

Can you please provide an example with <Icon />?

**Comment by segunadebayo** [comment]
Hi @secretlifeof,

Thanks for this issue. Can you try this?

```jsx
<PseudoBox _hover={{ color: "blue", stroke: "blue" }}>
  <Icon name="menu" color="currentColor" w={["2vw", "2vw", "5.5vw"]} h="auto" />
</PseudoBox>
```

The trick is to get the icon to use colors from the `PseudoBox` component by setting it's color to `currentColor`

Let me know if this works.

**Comment by segunadebayo** [comment]
Try the above method, and if it doesn't work I'll re-open this issue.

Thanks again.

**Comment by secretlifeof** [comment]
@segunadebayo thank you, this works!

**Comment by fr3fou** [comment]
How can I do the same but with `transform: scale`?

**Comment by moneebalalfi** [comment]
@fr3fou Did u figure out it ?

**Comment by Charlesdoiron** [comment]
Hi, i figure it by making :

```javascript

import { ReactComponent as Edit } from "./assets/edit.svg";

 <Box
  sx={{ "svg:hover": {fill: "red"} }}>
   <Edit />
</Box>
```

**Comment by arubua** [comment]
> How can I do the same but with `transform: scale`?

**_hover = { {  transform: "scale(1.2)"  } }**

**Comment by shubhsk88** [comment]
Does anyone figure this out ? I am trying to have the same thing on `active` as well

**Comment by labyh123456** [comment]
<Icon
  name="read"
  color="red"
 _hover={{ backgroundColor: "blue" }}
/>

**Comment by NickyZewe** [comment]
I got mine to work with this:

const example = ( ) => {
  return (
    <Box
      _hover={{
        transform: "scale(1.03)",
        transition: "transform .15s ease-in",
      }}
  >
      example
    </Box>
  );
};
