### ISSUE TITLE
[Menu] Menu component throws a "Element type is invalid" error when using Chakra 1.3.4 or 4.0.0

### ISSUE THREAD

**Issue by JeremieLeblanc** [chakra-ui/chakra-ui#3634]
# 🐛 Bug report

If using version 1.3.4 or 4.0.0 of chakra-ui/react, the Menu component will crash your site and give the following error
```
Error
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of Menu.
```

## 💥 Steps to reproduce

1. Create a new project using the latest Chakra-ui version
2. Add a Menu component

## 💻 Link to reproduction

 [CodeSandbox reproduction](https://codesandbox.io/s/zen-star-ct50v?fontsize=14&hidenavigation=1&theme=dark)

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |           4.0.0 |
| Browser          |           Google Chrome (89.0.4389.90) |
| Operating System |           Windows 10 (20H2) |

**Comment by TimKolberger** [comment]
I could reproduce this issue only in CodeSandbox starting with `@chakra-ui/react@v1.3.4`. 
It works on my machine ©️ 

Is this the case for you as well?

**Comment by JeremieLeblanc** [comment]
You seem to be correct.
I stumbled upon this bug while trying to make a bug report for something else and noticed it in CodeSandbox.
I just made a new project and it does indeed work.
I was hesitant to update my code after seeing the error in CodeSandbox, but it seems that the issue may not be that urgent.

Thanks

**Comment by TimKolberger** [comment]
Closing this with https://github.com/chakra-ui/chakra-ui/pull/3636#issuecomment-804178019
