### ISSUE TITLE
Switch and NumberInput don't look any good in RTL

### ISSUE THREAD

**Issue by manzoorwanijk** [chakra-ui/chakra-ui#3638]
## Picture worth a thousand words
![image](https://user-images.githubusercontent.com/18226415/111950943-fe74d180-8b08-11eb-8b66-2571d9d8cd35.png)

![image](https://user-images.githubusercontent.com/18226415/111951595-e3ef2800-8b09-11eb-8be6-892dfec08ce7.png)

## 💥 Steps to reproduce

1. Go to the sandbox
2. Turn the switches ON/OFF

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/chakra-ui-switch-rtl-bug-nw97f

## 🧐 Expected behavior

The switch should not be the way it is.

## 🧭 Possible Solution

RTL aware styling

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.4.1       |
| Browser          |     Chrome       |
| Operating System |     Windows 10       |

**Comment by segunadebayo** [comment]
Hi @manzoorwanijk,

I'm working on the fix for `Switch` but NumberInput works in RTL. I think the issue is with your setup for RTL. In addition to setting `dir=rtl`, you need to also change `theme.direction` to `rtl`.

```jsx
<ChakraProvider  theme={extendTheme({ direction: "rtl" })}>
   <App />
<ChakraProvider/>
```

**Comment by manzoorwanijk** [comment]
Thank you

**Comment by ilkou** [comment]
Hello @segunadebayo, I'm facing the same problem, no `rtl` support for `NumberInput` component even after using the right configuration in `ChakraProvider`.
I'm using the latest version `@chakra-ui/react 1.8.6`
