### ISSUE TITLE
[NumberInput] NaN value after multiple dots

### ISSUE THREAD

**Issue by AlbertLucianto** [chakra-ui/chakra-ui#364]
**Describe the bug**
Typing number like "1.......2", will set the value to NaN. To recover, you can select with mouse and replace the value. However, as a keyboard user there's nothing I can do to recover from this NaN value (arrow left/right can't move the cursor, and up/down does not go back to valid number neither).

Another related issue is by writing "1........" and press arrow up - it will also set to NaN.

**Expected Behavior**
After writing "1......", event like blur and increase/decrease action with arrow up/down should fix the value into "1".

**Comment by segunadebayo** [comment]
Hi @AlbertLucianto, I agree.

We'll ensure we fix this in the next release.

Thanks for bringing it up.

**Comment by simontaisne** [comment]
This issue seems to be still valid on `1.1.5` version.

Quick try on the combined `Slider` [example](1.1.5) from the doc.

![chrome-capture](https://user-images.githubusercontent.com/233639/105638419-82c81280-5e40-11eb-8c92-4873caff9b52.gif)
