### ISSUE TITLE
Divider <hr /> – do not set role="separator"

### ISSUE THREAD

**Issue by rastersysteme** [chakra-ui/chakra-ui#3642]
# 🐛 Bug report

## 💥 Steps to reproduce

1. Go to the CodeSandbox.
2. Inspect the hr element.
3. There’s an explicit `role="separator"` set on the [hr element](https://github.com/chakra-ui/chakra-ui/blob/main/packages/layout/src/divider.tsx#L52) which mustn’t be present [according to the standard](https://www.w3.org/TR/html52/grouping-content.html#the-hr-element).

## 💻 Link to reproduction

[CodeSandbox](https://codesandbox.io/s/recursing-rain-826s6?file=/src/App.js)

## 🧐 Expected behavior

No explicit `role="separator"` on `hr`.

## 🧭 Possible Solution

Remove [this line](https://github.com/chakra-ui/chakra-ui/blob/main/packages/layout/src/divider.tsx#L52).

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.4      |
| Browser          |      all (Chrome, Fireforx, …)      |
| Operating System |    MacOS, Windows       |

## 📝 Additional information

–

**Comment by ProPratik1405** [comment]
Can i work on this

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
