### ISSUE TITLE
[NumberInput] Controlled component fails when trying to check `.indexOf` on a Number

### ISSUE THREAD

**Issue by trevorgerhardt** [chakra-ui/chakra-ui#365]
**Describe the bug**
When the `useNumberInput` hook is handling a change with `updateValue` it checks to see if the value can convert to a `number`. It does so by using a method that the native `number` type does not have: `indexOf` and so throws a `Uncaught TypeError: value.indexOf is not a function`. Here: https://github.com/chakra-ui/chakra-ui/blob/e3e3453e495fae9f9d5f38a8b8bca0e4f33e6f9e/packages/chakra-ui/src/useNumberInput/index.js#L89

**To Reproduce**
I created a CodeSandbox: https://codesandbox.io/s/chakra-js-starter-z0yqw
Essentially:
```js
function NumberExample() {
  const [v, setV] = React.useState(0);

  return (
    <NumberInput keepWithinRange={false} max={10} onChange={setV} value={v}>
      <NumberInputField />
    </NumberInput>
  );
}
```
Change the max value to > 10 and click away.

**Suggested solution(s)**
Check to see if the value is a number before converting it.

**Desktop (please complete the following information):**
 - OS: Max OSX
 - Browser: Brave
 - Version: 0.5.2

It appears the code in `dev` has changed drastically. So this may have been fixed already. If that is the case, please let me know and let me know when the release is planned if possible!

Thanks!

**Comment by trevorgerhardt** [comment]
Ah. I converted the max to a string and it fixed the error. 

The component should probably allow setting max to a Number without an error.

**Comment by segunadebayo** [comment]
Hi @trevorgerhardt,

Sorry for my late reply. Yes, the code in for NumberInput has changed significantly to handle most of the use-cases, allow for more control, and make testing the logic easier.

I'm glad you found a walkaround for it.

Thanks
