### ISSUE TITLE
[Stack] setting `direction` property to `column-reverse` adds extra padding

### ISSUE THREAD

**Issue by feross** [chakra-ui/chakra-ui#3657]
# 🐛 Bug report

When we set the first breakpoint (the base) of the `direction` property to `column-reverse`, there is extra padding. When setting to `column` there is no such issue.

The weird part is that it affects padding *specifically for breakpoints that are not set to `column-reverse`*. So even though `column-reverse` is the first breakpoint value, it messes up the padding at larger screen sizes.

The red and green box should be exactly the same size at this screen resolution because the direction property is the same, but it's not. Instead there is extra padding at the bottom of the first component:

<img width="886" alt="Screen Shot 2021-03-24 at 12 52 31 AM" src="https://user-images.githubusercontent.com/121766/112274059-485dd480-8c3b-11eb-8800-bc90c813ce71.png">

## 💥 Steps to reproduce

```js
<>
      {/* COMPONENT 1 */}

      <Stack
        // NOTE: column-reverse is used for base breakpoint
        direction={["column-reverse", null, "row"]}
        spacing={12}
        border="1px solid red"
      >
        <Stack w={["full", null, "50%"]}>
          <p>CONTENT</p>
        </Stack>
        <Stack w={["full", null, "50%"]}>
          <p>CONTENT</p>
        </Stack>
      </Stack>

      {/* COMPONENT 2 */}

      <Stack
        // NOTE: column is used for base breakpoint
        // THIS IS THE ONLY DIFFERENCE.
        direction={["column", null, "row"]}
        spacing={12}
        border="1px solid red"
      >
        <Stack w={["full", null, "50%"]}>
          <p>CONTENT</p>
        </Stack>
        <Stack w={["full", null, "50%"]}>
          <p>CONTENT</p>
        </Stack>
      </Stack>
    </>
```

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/cool-ives-ucsuw?file=/src/index.tsx:197-1022

## 🧐 Expected behavior

There should not be extra padding on the last component in the stack. This is where the extra padding is:

<img width="756" alt="Screen Shot 2021-03-24 at 12 55 24 AM" src="https://user-images.githubusercontent.com/121766/112274413-b3a7a680-8c3b-11eb-98c6-0fdd0d4e6995.png">

<img width="314" alt="Screen Shot 2021-03-24 at 12 56 05 AM" src="https://user-images.githubusercontent.com/121766/112274446-ba361e00-8c3b-11eb-806f-b50d32d2c81e.png">

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       1.4.1     |
| Browser          |       Chrome     |
| Operating System |    macOS latest        |

**Comment by burhanuday** [comment]
Seems to be an issue with the styles in [stack.utils.tsx](https://github.com/chakra-ui/chakra-ui/blob/main/packages/layout/src/stack.utils.tsx)

https://github.com/chakra-ui/chakra-ui/blob/e5d9bb84fbcefe572ce273807d213c47f8145fcb/packages/layout/src/stack.utils.tsx#L22-L27

This issue gets fixed on changing it to
```javascript
row: { marginStart: spacing, marginTop: 0, marginBottom: 0 },
```

I can send a PR for this fix if it's the correct way to fix this problem
