### ISSUE TITLE
components that have textStyle, no longer receive styles from it, in version 1.4

### ISSUE THREAD

**Issue by violabg** [chakra-ui/chakra-ui#3658]
# 🐛 Bug report

after updating to version 1.4 components that have textStyle, no longer receive styles from it.
up to to version 1.3 was working fine.

Heading and Text components never receive textStyle props, while Box is getting them the first render, but if you rerender the component (useEffect) it will loose them.

## 💻 Link to reproduction

https://codesandbox.io/s/textstyle-demo-vzxyr?file=/src/App.tsx:240-245

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.4      |
| Browser          |      all      |
| Operating System |      all      |

**Comment by segunadebayo** [comment]
Kindly upgrade to `1.4.1`. Thanks

**Comment by violabg** [comment]
> Kindly upgrade to `1.4.1`. Thanks

If you look at my codesandbox, you can see that the Heading still doesn't get the styles.
Is this a bug or Headings don't support textStyle?

**Comment by with-heart** [comment]
Yeap, can see that in your CSB even on `1.4.1`. Looks like there are still some conflicts around `textStyle` resolution. Reopening so we can investigate!

**Comment by segunadebayo** [comment]
Please check #3501. I provided some recommendations there.

Basically, the idea is to stick to one source of truth, the Heading component uses `theme.components.Heading` to handle its styles.

You can either:
- Use `extendTheme` to update the styles of the Heading, or
- Change `Heading` to `<Box as="h1" />` so it correctly applies text styles.

It's quite challenging to resolve styles from the theme, text style, and style props override (e.g fontSize, lineHeight, etc). Consider this a walkaround for the current issue, we'll figure out a better solution over time.

**Comment by violabg** [comment]
Thanks, I already switched to Box for now, it works fine.

**Comment by segunadebayo** [comment]
After further investigation, it seems we might have to leave it this to avoid further breaking scenarios.

Thanks for understanding. Please use the suggested methods above if you run into this issue.

**Comment by violabg** [comment]
> After further investigation, it seems we might have to leave it this to avoid further breaking scenarios.
> 
> Thanks for understanding. Please use the suggested methods above if you run into this issue.

That’s cool, maybe you should update the docs with this info.

**Comment by martinmunillas** [comment]
i'm having the same problem but i'm already indeed extending the chakra theme and using `<Box as="h1" textStyle="foobar"  />` and i don't think this issue should be closed just because there is a work around

**Comment by martinmunillas** [comment]
also i'd be glad to contribute to chakra if you could give me some indications where i can start to solve this bug it would be awesome :D

**Comment by nicolls1** [comment]
I just upgraded from 1.3.4 to 1.5.2 and have this as a breaking issue for my headings. It seems that the default value for the heading component is now used for fontWeight and size as now my headings are all the same size and bold. 

The Component:
```
<Heading textStyle="h2" mb={12}>
  Text
</Heading>
```

The Theme:
```
  textStyle: {
    ...
    h2: {
      fontSize: { base: '28px', md: '4xl' },
      lineHeight: { base: '34px', md: '48px' },
      fontWeight: 'medium',
      color: 'blue.500',
    },
    ...
  }
```

This used to work in 1.3.4 but now the Heading component overwrites fontSize and fontWeight. Very sad as the text style overwriting the heading default is what I would have expected and how it used to work :/

**Comment by HasanMothaffar** [comment]
I can reproduce this bug locally using these versions:

```js
"@chakra-ui/react": "^2.2.4",
"@emotion/react": "^11",
"@emotion/styled": "^11"
```
In my case, the `<Text>` component is receiving styles from the `textStyles` entry in the theme correctly, but `<Heading>` elements do not.

Using a `<Box>` element instead resolves the issue.
