### ISSUE TITLE
Overwriting variant renders error on 1.4.1

### ISSUE THREAD

**Issue by danielolaviobr** [chakra-ui/chakra-ui#3662]
# 🐛 Bug report

When trying to update the Input outline variant in NextJs and typescript project, it renders an error as such:

```
Value of type '({ colorScheme: c }: { colorScheme: any; }) => { field: { _focus: { borderColor: string; }; }; }' has no properties in common with type 'DeepThemeExtension<Partial<{ field: { border: string; borderColor: string; bg: string; _hover: { borderColor: any; }; _readOnly: { boxShadow: string; userSelect: string; }; _disabled: { opacity: number; cursor: string; }; _invalid: { ...; }; _focus: { ...; }; }; addon: { ...; }; }>, CSSWithMultiValues | ... 2 more ....'. 
Did you mean to call it? ts(2560)
theme.chakra.ts(47, 18): Did you mean to call this expression?
```

![image](https://i.ibb.co/crTSZSG/code.png)

<img width="498" alt="Screen Shot 2021-03-24 at 21 58 51" src="https://user-images.githubusercontent.com/64712584/112402899-21aba680-8cec-11eb-9798-9416d7e4ede1.png">

## 💥 Steps to reproduce

1. Create a NextJs project using typescript
2. Create theming file and add a overwrite a variant with a function

## 💻 Link to reproduction

No CodeSandBox preset provided

## 🧐 Expected behavior

Not to render the error

## 🧭 Possible Solution

Downgrade the version

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.4.1      |
| Browser          |        Chrome    |
| Operating System |    Macbook Pro 2015        |

**Comment by luigiminardim** [comment]
I have this same issue and described how to reproduce this in #3308. [See the comment.](https://github.com/chakra-ui/chakra-ui/issues/3308#issuecomment-813700322)

**Comment by TimKolberger** [comment]
Thank you for the repro @luigiminardim! I could only reproduce it locally with nextJS. The PR should fix this issue.
