### ISSUE TITLE
[Menu] Content shifts once JavaScript loads and runs

### ISSUE THREAD

**Issue by feross** [chakra-ui/chakra-ui#3668]
# 🐛 Bug report

The `<Menu>` component seems to not properly hide the underlying menu item (it's using `visibility: none`) so the hidden dropdown menu takes up space until the JS loads and then `position: absolute` is added to the `style` attribute, so it doesn't displace the other nearby content.

The lack of `position: absolute` in the SSR output looks wrong and the content shifts during load.

## 💥 Steps to reproduce

```js
    <Menu>
      {fileInput}
      <MenuButton as={Button} size='lg'>
        Select files to send
      </MenuButton>
      <MenuList>
        <MenuItem
          icon={<Icon as={VscFiles} height='full' width={4} />}
          onClick={showFilePicker}
        >
          Select files
        </MenuItem>
        <MenuItem
          icon={<Icon as={VscFolderOpened} height='full' width={4} />}
          onClick={showDirectoryPicker}
        >
          Select a folder
        </MenuItem>
      </MenuList>
    </Menu>
```

Before JS is loaded: 

<img width="537" alt="Screen Shot 2021-03-25 at 1 21 51 PM" src="https://user-images.githubusercontent.com/121766/112539005-b4405a00-8d6d-11eb-959f-dabebca78f00.png">

After JS loads on the client:

<img width="538" alt="Screen Shot 2021-03-25 at 1 22 05 PM" src="https://user-images.githubusercontent.com/121766/112539039-bdc9c200-8d6d-11eb-83f5-7b4d504685dc.png">

Here's the element that's displacing the other content:

<img width="554" alt="Screen Shot 2021-03-25 at 1 21 35 PM" src="https://user-images.githubusercontent.com/121766/112539091-c91ced80-8d6d-11eb-9702-24e786cec589.png">

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/elated-water-mubin?file=/src/App.js

Although it doesn't seem possible to Disable JS in the Chrome web inspector and have CodeSandbox load, so you might need to put this into an SSR'd app to see it.

## 🧐 Expected behavior

No content shifting.

## 🧭 Possible Solution

Add the style tag with `position: absolute`, etc. during SSR.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.4.1           |
| Browser          |     Chrome   latest    |
| Operating System |    macOS latest        |

**Comment by segunadebayo** [comment]
Fixed in a recent PR I merged. #3583

**Comment by feross** [comment]
@segunadebayo Amazing!
