### ISSUE TITLE
Tables are not really responsive

### ISSUE THREAD

**Issue by jahirfiquitiva** [chakra-ui/chakra-ui#3669]
# 🐛 Bug report

The table component in Chakra is not quite responsive. Even the docs has some issues.

## 💥 Steps to reproduce

1. Go to 'https://chakra-ui.com/docs/data-display/table'
2. Scroll down
3. See error

## 💻 Link to reproduction

[https://chakra-ui.com/docs/data-display/table](https://chakra-ui.com/docs/data-display/table)

## 🧐 Expected behavior

The content should not overflow any parent `div`s

## 🧭 Possible Solution

I suggest adding a wrapper like Bulma has.
https://bulma.io/documentation/elements/table/#table-container

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.4.1 |
| Browser          | Brave |
| Operating System | iOS |

## 📝 Additional information

![IMG_1139](https://user-images.githubusercontent.com/10360816/112552687-368e4580-8d91-11eb-8fc6-579e862aa402.jpg)
![IMG_1138](https://user-images.githubusercontent.com/10360816/112552699-39893600-8d91-11eb-8bab-79c9c74953aa.jpg)

**Comment by segunadebayo** [comment]
Thanks for providing a solution. I think this makes sense.

I've added a `TableContainer` component to help manage this. Will be live in the next release.

**Comment by jahirfiquitiva** [comment]
Thank you!
