### ISSUE TITLE
Request to add [Optimized Image/Picture] component

### ISSUE THREAD

**Issue by jescowuester** [chakra-ui/chakra-ui#367]
**Is your feature request related to a problem? Please describe.**

Images are the heaviest part of a website. Lazyloading is rather hard to implement and the picture/srcset syntax is all over the place and confusing for new devs. Webp is an amazing solution for this but its barely used because it's not yet stable in every browser.

Taking care of this issue would greatly improve web accessibility for people on slow networks.

**Describe the solution you'd like**

An improvement to the Image component that would address all of these issues, similar to gatsby-images.
Users would still need to convert and provide the images themselves but 
 - lazyloading
 - webp fallbacks 
 - responsive sizes
are made easy.

A nice and flexible api could look like this:

```
<Image
	loading='lazy' // default behavior
    placeholder='img-xxs.jpg' // blured version of this is gonna be shown while the image loads
	src='img-md.jpg' // the default source and fallback
    sizes={['/img-sm.jpg', '/img-md.jpg','/img-lg.jpg']} // responsive array like styled-system that can take multiple sources
	webp={['/img-sm.webp', '/img-md.webp','/img-lg.webp']}
/>
```
Most keys are optional so sth like this is possible
```
<Image src='img-md.jpg' webp='img-md.webp' />
```

This integrates well with pretty much every common image optimization service like Cloudinary that provide flexible links for every size.

**Describe alternatives you've considered**

I thought about porting gatsby-image out of gatsby but the api is very specific to their image sharp configuration.

**Comment by segunadebayo** [comment]
This sounds like a great idea @jescowuester. I'm not sure how you'd go about this but if you can create a quick draft or prototype, I'll look into it.

Otherwise, we'll consider this after the TypeScript migration.

This is definitely a good component to add to Chakra, thanks for your suggestion.

**Comment by jescowuester** [comment]
Yeah, I'll agree that it should wait until the typescript rewrite, ping me here when you think the library is ready and I'll get a demo out

**Comment by jescowuester** [comment]
alright heres a demo: https://codesandbox.io/s/github/jescowuester/optimized-image_v1/tree/master/?fontsize=14&hidenavigation=1&theme=dark

A lot of this stuff is inspired by https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js but gatsby's image component is a big mess so I think its best to write it from scratch. 

This still needs a lot of features, especially
[] accessibility
[] support for browsers that don't have intersectionObserver
[] turn off lazy loading when loading='lazy' is supported

but the demo should get the idea across.

**Comment by felipesousa** [comment]
@jescowuester good idea! I think that it would be super usefully!

@segunadebayo do you have some components list that can be good implement inside the library? If yes, can you send me the link please?

🔥

**Comment by segunadebayo** [comment]
@jescowuester, I think you have a pretty good prototype already. Once we're done with the TS migration, I'll take a look at this even more.

Thanks man.

**Comment by asterikx** [comment]
Would also love to see this. Also on the Avatar component to account for different DPRs. I'm using TypeScript and cannot use `srcSet` since it's not included in the typings.

I suppose this will be fixed with the TypeScript release :)

**Comment by subhendukundu** [comment]
I see two problems with the Image component too.
1. If the image is too big, its shows a broken image until the whole image is loaded. So I guess the proposed `isLazy` or adding a loading icon would be great.
2. `fallbackSrc` take a `string` which is great but I think we should provide an ability to add a passing custom component too. So that it's possible to pass SVG to make it more personalized.

Is anyone working on this? Otherwise, I would like to pick it up.

**Comment by grsoares21** [comment]
Sad to see this has gone stale, :/. It was exactly what I was looking for.

Anyone with plans of doing a PR for this?

**Comment by MSSPL-KamalenduGarai** [comment]
Any update on this will be appreciated.
