### ISSUE TITLE
[Number Input]: onChange executing on mount

### ISSUE THREAD

**Issue by vmlopezr** [chakra-ui/chakra-ui#3676]
# 🐛 Bug report

When using the number input and passing `onChange`, the change method executes when the number input first mounts.
## 💥 Steps to reproduce

```jsx
      const [value, setValue] = React.useState(0);
      const onChange = (valueAsString: string, valueAsNumber: number) => { 
        // This is executed when the component first mounts
        setValue(valueAsNumber);
      } 
      return (
        <NumberInput min={0} max={10} value={value} onChange={onChange}>
          <NumberInputField />
        </NumberInput>
      )
```

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/eager-clarke-xxh6e?file=/src/index.tsx:338-382

Click on the button to toggle the number input. It will run the onChange method and print to console on every mount of the input.

## 🧐 Expected behavior

No execution of `onChange` on component mount.
## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |    Latest        |
| Browser          |     Firefox, Safari, Chrome Latest       |
| Operating System |    MacOS Latest        |

**Comment by simontaisne** [comment]
On a side not, the `onBlur` event is called twice.
