### ISSUE TITLE
Mobile touch/scrolling not working in drawer (nextjs => preact)

### ISSUE THREAD

**Issue by approached** [chakra-ui/chakra-ui#3677]
# 🐛 Bug report
Mobile touch/scrolling not working in drawer (nextjs => preact).

Example:
![image](https://user-images.githubusercontent.com/3439330/112668029-41fb7280-8e5e-11eb-96d7-0dcbddf3d002.png)

Without preact it works fine. So it just a bug in preact.

## 💥 Steps to reproduce
I just copied the first example https://chakra-ui.com/docs/overlay/drawer#basic-drawer and put some Text in DrawerBody.

## 💻 Link to reproduction
Nextjs / Preact Template: https://github.com/vercel/next.js/tree/canary/examples/using-preact

**Comment by segunadebayo** [comment]
Thanks for the investigation @approached, I don't think this is within the scope of what we can fix as it works fine in React.

Permit me to close this.

**Comment by tornvallalexander** [comment]
Seems like there is a problem when using Preact together with Chakra UI as scrolling doesn't work in modals.
