### ISSUE TITLE
Question: breakpoints to change button variant / variantColor

### ISSUE THREAD

**Issue by JClackett** [chakra-ui/chakra-ui#368]
Hello!

Wondering if its possible to change the variant or variantColor on Chakra components using the breakpoint api.

Example implementation..

```
<Button variant={{base: "solid", md: "ghost"}} variantColor={{base: "green", md: "blue"}} />
```

Above doesnt work for me but just checking if im doing something wrong?

Thanks!!

**Comment by segunadebayo** [comment]
Hi @JClackett,

At the moment, there's no way to make variant and variantColor responsive using the breakpoint api. We might look into it much later.

A walkaround is to use this package: https://github.com/system-ui/theme-ui/tree/master/packages/match-media and then change the prop based on the matched media. I hope this helps?

Thanks for bringing this up.
