### ISSUE TITLE
Menu is throwing errors on render

### ISSUE THREAD

**Issue by simontaisne** [chakra-ui/chakra-ui#3680]
# 🐛 Bug report

`Menu` is throwing the following errors on render.

```
Warning: Unknown event handler property `onUpdate`. It will be ignored.
```

```
Warning: Received `false` for a non-boolean attribute `initial`.
```

## 💻 Link to reproduction

https://codesandbox.io/s/menu-chakra-ui-rx0lm

## 🧐 Expected behavior

No error.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       1.4.1     |
| Browser          |   Chrome         |
| Operating System |    macOS 11.1   |

**Comment by segunadebayo** [comment]
Hi @simontaisne,

The error goes away when you update framer-motion to the latest. This is happening because of the way `framer-motion` forwards prop passed to any `motion.custom` component (before v4).

If you upgrade it should work as expected.

Thanks
