### ISSUE TITLE
Request to add [Component] Input Masks

### ISSUE THREAD

**Issue by mavalon** [chakra-ui/chakra-ui#369]
I need my text inputs to have an input mask to describe and enforce a certain format: e.g. "(999) 999-9999".  I was hoping `react-input-mask` would work with chakra, but it doesn't seem possible.  This seems like a common requirement, so it would be nice to support that.

**Comment by segunadebayo** [comment]
Hi @mavalon, 

Thanks for this issue. Do you a CodeSandbox replica that shows the `react-input-mask` doesn't work with Chakra?

If so, please share it so I can take a look.

**Comment by segunadebayo** [comment]
Hi, I'm going to close this now as it's not a priority for the team at the moment.

I've noted your request in our backlog and will look into it later. In the meantime, we might consider adding a sample of how to use Chakra UI with react-input-mask.

Thanks.

**Comment by breytex** [comment]
Hey!
Sorry for re-opening, but I just want to quickly confirm that `react-input-mask` does indeed NOT work together with Chakra.
I can't even tell why, but as soon as I put the MaskInput inside the Chakra context, is does no longer work.

I would be very glad for an example on how to get it to work :)
Thanks for the greater work so far on Chakra UI.

**Comment by esakkik** [comment]
Any updates on `sample of how to use Chakra UI with react-input-mask.`

**Comment by zgid123** [comment]
I don't know what problem did you guys face when using the `react-input-mask` with `chakra-ui`. I just added `react-input-mask` for my project and it works well. [Here a quick CodeSandbox](https://codesandbox.io/s/distracted-morse-51p5y?file=/src/App.tsx)

**Comment by nbarthel** [comment]
> I don't know what problem did you guys face when using the `react-input-mask` with `chakra-ui`. I just added `react-input-mask` for my project and it works well. [Here a quick CodeSandbox](https://codesandbox.io/s/distracted-morse-51p5y?file=/src/App.tsx)

The code sandbox isn't masking...  Am I missing something?

**Comment by nbarthel** [comment]
> > I don't know what problem did you guys face when using the `react-input-mask` with `chakra-ui`. I just added `react-input-mask` for my project and it works well. [Here a quick CodeSandbox](https://codesandbox.io/s/distracted-morse-51p5y?file=/src/App.tsx)
> 
> The code sandbox isn't masking... Am I missing something?

Nevermind, not enough coffee.  It is working.

**Comment by lucivaldo** [comment]
`react-input-mask` appears to be dead. Any suggestion? [Issue 268](https://github.com/sanniassin/react-input-mask/issues/268)

**Comment by dapeduu** [comment]
@lucivaldo Maybe a little late, but Ive just got input masks working with [React Imask](https://www.npmjs.com/package/react-imask). Here's a [Codesandbox](https://codesandbox.io/s/chakra-ui-react-imask-react-hook-form-4drkf?file=/src/App.tsx) with the example.
