### ISSUE TITLE
Next.js links don't work inside toasts

### ISSUE THREAD

**Issue by raulrpearson** [chakra-ui/chakra-ui#3690]
# 🐛 Bug report

In my project I've created a `Link` component that wraps Chakra's link component with Next.js' [as recommended](https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag). This component works fine when I use it in regular places inside my app, but breaks when used inside toasts. On click I get thrown the error "TypeError: can't access property "push", router is null". I think it might have to do with the fact that toasts are placed inside a portal?

<img width="922" alt="toast-portal" src="https://user-images.githubusercontent.com/23662058/112755928-89fbd000-8feb-11eb-97ed-332424a35d64.png">

## 💥 Steps to reproduce

1. Go to the sandbox provided below
2. Explore implementation of `Link` component
3. Test the instances of `Link` within pages and confirm that they work
4. Trigger the toast and test that instance of `Link`
5. Observe error thrown by Next.js

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/purple-wood-q6ug6

## 🧐 Expected behavior

I expect this link component pattern to work inside toasts too.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.4.1       |
| Browser          |      N/A      |
| Operating System |    N/A       |

**Comment by raulrpearson** [comment]
My current workaround is this:

```javascript
import Router from "next/router";
import { Link as ChakraLink, LinkProps } from "@chakra-ui/react";

// TODO
// https://github.com/chakra-ui/chakra-ui/issues/3690
// const Link = ({ href, ...rest }: LinkProps) => {
//   return (
//     <NextLink href={href} passHref>
//       <ChakraLink textDecoration="underline" {...rest} />
//     </NextLink>
//   );
// };

const Link = ({ href, ...rest }: LinkProps) => {
  const onClick = (e) => {
    e.preventDefault();
    Router.push(href);
  };
  return (
    <ChakraLink
      textDecoration="underline"
      href={href}
      onClick={onClick}
      {...rest}
    />
  );
};

export default Link;
```

**Comment by mcha-dev** [comment]
There is a todo comment in `toast.class` I think once it's todo-ed, it might solve this issue
```jsx
* @todo
*
* Update toast constructor to use `PortalManager`'s node or document.body.
* Once done, we can remove the `zIndex` in `toast.manager.tsx`
```

**Comment by mcha-dev** [comment]
If chakra can accept some `portalParent` prop like `portalParent: "#__next"` and then render portal there, it will solve this issue.

**Comment by dgreene1** [comment]
> mcha-dev commented on Jun 9, 2021
> If chakra can accept some portalParent prop like portalParent: "#__next" and then render portal there, it will solve this issue.

@segunadebayo would you be willing to accept a PR that included `portalProps` similar to what [Modal's props](https://chakra-ui.com/docs/overlay/modal#modal-props) allow?

**Comment by nilsdet** [comment]
This is my current workaround: 

```typescript
import { RouterContext } from "next/dist/shared/lib/router-context"; // next 12
// import { RouterContext } from "next/dist/shared/lib/router-context"; // next 11.1
// import { RouterContext } from "next/dist/next-server/lib/router-context"; // next < 11.1

const MyComponent = () => {
  const router = useRouter();
  const toast = useToast();

  useEffect(() => {
    toast({
      description: (
        <RouterContext.Provider value={router}>
          <Link href="/home" passHref>
            <chakra.a>Home</chakra.a>
          </Link>
        </RouterContext.Provider>
      ),
    });
  }, []);

  return null;
};

```

**Comment by bbovenzi** [comment]
> @segunadebayo would you be willing to accept a PR that included `portalProps` similar to what [Modal's props](https://chakra-ui.com/docs/overlay/modal#modal-props) allow?

+1 on `portalProps` for toasts. There are instances where I want to pass a custom `containerRef` for anything using a portal, this works for tooltips, dialogs and modals but not for toasts.

**Comment by kfranqueiro** [comment]
This issue still exists in the latest version of Chakra.

**Comment by kfranqueiro** [comment]
The issue in the sandbox is still reproducible in the latest version of Chakra.

**Comment by kfranqueiro** [comment]
This still seems to be an issue in the provided sandbox, which is running against latest.

**Comment by yukukotani** [comment]
@kfranqueiro You can simply avoid this issue using `toastOptions.portalProps.containerRef`.

sandbox: https://codesandbox.io/s/next-js-links-dont-work-inside-toasts-forked-k0m1o2

```tsx
function App({ Component, pageProps }: AppProps) {
  const portalContainerRef = useRef();
  return (
    <>
      <div>
        <ChakraProvider
          toastOptions={{ portalProps: { containerRef: portalContainerRef } }}
        >
          <Component {...pageProps} />
        </ChakraProvider>
      </div>
      <div ref={portalContainerRef} />
    </>
  );
}
```
