### ISSUE TITLE
Wrong spacing between Stack items when using responsive direction

### ISSUE THREAD

**Issue by martinezleoml** [chakra-ui/chakra-ui#3695]
# 🐛 Bug report

When using responsive direction on `<Stack />` component, depending on the direction values, spacing between items may behave strangely (unwanted margins are applied).

## 💥 Steps to reproduce

When using this code:

```typescript
<Stack
  direction={{ base: "column", md: "row-reverse" }}
  spacing="16"
>
  <Box flex="1" height="100px" bg="blue.400">
    First container
  </Box>
  <Box flex="1" height="100px" bg="green.400">
    Second container
  </Box>
</Stack>
```

A `margin-top` is applied to the second box, which is unwanted.

![image](https://user-images.githubusercontent.com/759215/112903241-877ea080-90e7-11eb-971f-dfa417429d89.png)

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/peaceful-noether-z8yks?file=/src/App.tsx

(Open preview in full screen).

## 🧐 Expected behavior

We expect the behaviours to be the same as when using this code :

```typescript
<Stack
  direction="row-reverse"
  spacing="16"
>
  <Box flex="1" height="100px" bg="blue.400">
    First container
  </Box>
  <Box flex="1" height="100px" bg="green.400">
    Second container
  </Box>
</Stack>
```

![image](https://user-images.githubusercontent.com/759215/112903626-11c70480-90e8-11eb-9fc5-bb8ba094de7c.png)

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.4.1 (@chakra-ui/react)           |
| Browser          |  Chrome  89.0.4389.90        |
| Operating System |      macOS 11.2.3      |

**Comment by martinezleoml** [comment]
My current workaround is : 

```typescript
const MyComponent = () => {
  const hasMediumScreen = useBreakpointValue({ base: false, md: true });

  return (
    <Stack
      direction={hasMediumScreen ? 'row-reverse' : 'column' :}
      spacing="16"
    >
      <Box flex="1" height="100px" bg="blue.400">
        First container
      </Box>
      <Box flex="1" height="100px" bg="green.400">
        Second container
      </Box>
    </Stack>
  );
}
```

**Comment by segunadebayo** [comment]
Hi @martinezleoml,

This is fixed in the latest release. If you upgrade that Codesandbox to `1.4.2`, you'll see that it works.
