### ISSUE TITLE
Drawer: scrollBehavior="outside" not working as documented?

### ISSUE THREAD

**Issue by binajmen** [chakra-ui/chakra-ui#3701]
# 🐛 Bug report

> If set to `outside`, the entire `ModalContent` will scroll within the viewport.

It does not seem to be the case. Unless I misunderstood the expected effect.

## 💥 Steps to reproduce

1. Go to https://chakra-ui.com/docs/overlay/drawer#drawer-placement
2. Add a lot of content (`<p>Some contents...</p>`) in the `DrawerBody`
3. Open the drawer
4. Scroll down: the DrawerHeader is still visible

## 🧐 Expected behavior

> If set to `outside`, the entire `ModalContent` will scroll within the viewport.

As a default value (or with `outside` specified), the entire content of the Drawer (`DrawerContent`) should scroll, which is not the case.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.3.3      |
| Browser          |       Chrome     |
| Operating System |       MacOS     |

Thank you for your help!

**Comment by segunadebayo** [comment]
Hi @binajmen,

This is by design. We don't plan for Drawer's content to work with `scrollBehavior=outside`. This API is only intended for the modal component.

What's your use-case? I'm not sure I see a reason for the entire drawer to scroll as opposed to just the `DrawerContent` scrolling.

Let me know your thoughts.

**Comment by binajmen** [comment]
Hi @segunadebayo,

I was confused by the presence of `scrollBehavior` in the API documentation at https://chakra-ui.com/docs/overlay/drawer#drawer-props. If this is by design, there must be a good reason for that.

I have a drawer opening from the bottom with a top picture followed by the header then the content. I was looking for an option similar to `scrollBehavior` as on small screens the drawer content is rather small because of the square picture.

I suppose I can group the picture, the header and the content in the `DrawerContent` to solve my issue.

Thank you for the quick answer (and this wonderful UI library!).

**Comment by segunadebayo** [comment]
Ah yes, this must be an error from how we auto-generate the prop-tables in the docs.

We definitely meant to omit `scroll behavior from the drawer's prop table. I'll update that.

I'm glad you found a walkaround for it.

Cheers.
