### ISSUE TITLE
Investigate simplifying types around polymorphic `as` prop

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#3706]
# 🚀 Feature request

Investigate simplifying the types for the polymorphic `as` prop, so that the types become less dense, easier to understand, and more testable.

## 🧱 Problem Statement / Justification

I noticed that `@reach/ui` [recently replaced their polymorphic `as` types](https://github.com/reach/reach-ui/commit/fb6ad2077c8b9d5fd6c476ad2efbec60f518443f#diff-9c510737e1186b97aff9dee1c7846bd214978bbe0f31e2d0b45ccf4d756e95d8R35) with the code from [the private `polymorphic` package from `@radix-ui/primitives`](https://github.com/radix-ui/primitives/tree/main/packages/react/polymorphic/src). `@reach/ui` was previously using types much closer to ours. 

The types from the `radix-ui` `polymorphic` module are less complex than ours, to the point that it's easy to read through them and understand what it's doing and why. Their types module is also tested, which provides a much higher level of reliability than we get from ours currently.

## ✅ Proposed solution or API

I'd like us to investigate whether we can reuse (in whole or in part) the `polymorphic` module code from `radix-ui`. At the very least, I would like for us to walk away with an idea of how to test the types in our `system.types` module.

## 📝 Additional Information

This is one area where I wish all of the different React component libraries would work together on a single best-in-class solution, so if that means using the code from their private package to start in order to align with other large projects and iterate on the same concept, I'm all in favor.

I'm also hoping to get a chance to chat with Chance at `@reach/ui` or one of the `radix-ui` team members to start a conversation around this!

**Comment by segunadebayo** [comment]
This is an approach I investigated in the past and I don't quite like the fact that it required the use of `as` for any component that needs to properly typed.

Here's an example from the `radix-ui` test code and you'll see that it requires `as Polymorphic.ForwardRefComponent<"a", AnchorProps>` at the tail of the component to get it working. Doing that for every component and telling our consumers to do that might if they need the `as` prop to work might be quite tedious.

```jsx
const Anchor = React.forwardRef((props, forwardedRef) => {
  const { as: Comp = "a", requiredProp, ...anchorProps } = props;
  /* Does not expect requiredProp */
  return <Comp {...anchorProps} ref={forwardedRef} />;
}) as Polymorphic.ForwardRefComponent<"a", AnchorProps>;
```

I also don't think this is an **issue** per se. It might be a "refactoring" opportunity but labeling it as "performance" might not be correct. I could be wrong though 😅

**Comment by segunadebayo** [comment]
Regarding the tests, I think @TimKolberger put some tests in `as-props.test.tsx`, perhaps that might help gain some understanding.

**Comment by segunadebayo** [comment]
I did some research around this and it might be more challenging than we think.

Permit me to close for now. We won't be looking into this
