### ISSUE TITLE
Drawer + initialFocusRef on an input wrapped with FormControl throws a warning

### ISSUE THREAD

**Issue by brennanfife** [chakra-ui/chakra-ui#3708]
# 🐛 Bug report

Drawers with an initialFocusRef on an input (and are wrapped with a form control) throw an error. I've noticed this does not occur on Chakra V1.4.0

## 💥 Steps to reproduce

1. Open up a drawer with an initialFocusRef on an input component, wrapped within a formcontrol
2. See error
<img width="544" alt="Screen Shot 2021-03-31 at 10 19 30 AM" src="https://user-images.githubusercontent.com/31396350/113168896-b477a400-920a-11eb-8c4c-6d7b47cd2758.png">

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/heuristic-swartz-bl8hx?file=/src/Drawer.tsx

## 🧐 Expected behavior

An error should not be thrown

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.4.2       |
| Browser          |      Chromium      |
| Operating System |     mac       |

**Comment by segunadebayo** [comment]
Hi @brennanfife,

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
