### ISSUE TITLE
Website Performance Review

### ISSUE THREAD

**Issue by DecliningLotus** [chakra-ui/chakra-ui#3721]
# 🚀 Feature request

This is for the https://chakra-ui.com/ homepage itself. On the initial load of the homepage, we are fetching over 11-13MB of data, compared to https://chakra-ui.com/docs/getting-started which fetches around a more acceptable 1.3MB (but possibly improvable!) download.

I feel the website itself needs a performance review as I'm a tad worried to check the website when I'm on limited data outdoors (pretty expensive where I live). Throttling to Fast 3G on Chrome Devtools took a whopping 46.39 seconds to complete on the homepage.

## ✅ Proposed solution or API

There's way too much going on the front homepage. I don't really have time to go through everything, but there's a lot getting loaded like the CodeSandbox and Chakra Team Avatars (could be optimised into a single image) that adds a lot to the waterfall. The biggest offender I can see is the Chakra Pro image which accounts for 4.4MB by itself.

**Comment by jatin33** [comment]
@with-heart We can address this by lazy loading components below the fold using Intersection Observer api. What do you think? If possible i can work on this and create a PR

**Comment by segunadebayo** [comment]
Thanks for the detailed investigation @DecliningLotus.

I moved the Chakra Pro images to use next/image which gives us automatic image optimization. Things left to review on the site:

- Consider lazy loading the Codesandbox or using a static image that links to codesandbox
- Consider lazy loading the team/sponsors area or using [Adaptive hooks](https://github.com/GoogleChromeLabs/react-adaptive-hooks) to reduce the resolution of the images for slower networks

If anyone wants to take this up, that'll be awesome

**Comment by segunadebayo** [comment]
Closing this as most of the perf issues have been resolved. See my comment above.

In the future, we'll consider removing the codesandbox frame on the site to further improve perf.

If you feel inclined to further improve it, feel free to send in a PR.

Cheers

**Comment by MustaphaAlioglou** [comment]
> Thanks for the detailed investigation @DecliningLotus.
> 
> I moved the Chakra Pro images to use next/image which gives us automatic image optimization. Things left to review on the site:
> 
> * Consider lazy loading the Codesandbox or using a static image that links to codesandbox
> * Consider lazy loading the team/sponsors area or using [Adaptive hooks](https://github.com/GoogleChromeLabs/react-adaptive-hooks#network) to reduce the resolution of the images for slower networks
> 
> If anyone wants to take this up, that'll be awesome

i didnt understand. can we use the next/image optimization on the chakra ui or only in the pro version?
