### ISSUE TITLE
Modal: useEffect order when using the modal component

### ISSUE THREAD

**Issue by vmlopezr** [chakra-ui/chakra-ui#3723]
# 🐛 Bug report

There seems to be an issue in the effect orders (initial render/mounting) when using the modal component. 
When the Modal renders, any effects execute before the child components.

 
## 💥 Steps to reproduce

1. Create a component with a modal (called `ParentModal`).
2. Define an effect in `ParentModal` with empty dependency. The effect should have a console log.
3. Create a child component for `ParentModal` , (called `ChildA`).
4. Define an effect in `ChildA` with empty dependency. The effect should have a console log.
5. On initial render, see that the `ParentModal` effect executes before `ChildA` effect.

```js
const ChildA = () => {
  console.log("Child component A render");
  React.useEffect(() => {
    console.log("Child component A effect");
  }, []);
  return <Text> Child component A </Text>;
};

const ParentModal = ({ onClose }: { onClose: () => void }) => {
  console.log("Parent Modal component render");
  React.useEffect(() => {
    console.log("Parent component modal effect");
  }, []);
  return (
    <Modal
      onClose={onClose}
      isOpen={true}
      size={"md"}
      scrollBehavior={"inside"}
    >
      <ModalOverlay>
        <ModalContent>
          <ModalBody>
            <Flex>Content</Flex>
            <ChildA />
          </ModalBody>
        </ModalContent>
      </ModalOverlay>
    </Modal>
  );
};
function App() {
  const [showModal, setShowModal] = React.useState(false);
  return (
    <Flex w={"100%"} h={"100%"}>
      <Heading>Welcome to Chakra + TS</Heading>
      <Button onClick={() => setShowModal(true)}>Show Modal</Button>
      {showModal && <ParentModal onClose={() => setShowModal(false)} />}
    </Flex>
  );
}
```

See the reproduction below. 

## 💻 Link to reproduction

See this sandbox for a live example:
https://codesandbox.io/s/happy-brook-brg53?file=/src/index.tsx:251-1305

To view the effect order, click on the button. The console will then show the messages printed.

## 🧐 Expected behavior

Normally in react, with the following components:
- Parent A
- Child B

(**Expected**) The following are the render/effect orders:
1. Parent A renders initially
2. Child B renders initially
3. Child B effects execute
4. Parent A effects execute

(**Current Behavior**) On the other hand, with the modal component as the parent:
1. Parent A renders initially
2. Parent A effects execute
3. Child B renders initially
4. Child B effects execute 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      latest      |
| Browser          |        Firefox, Chrome, Safari latest    |
| Operating System |          MacOS  |

**Comment by segunadebayo** [comment]
Hi @vmlopezr,

We looked into this and we think it is related to how FocusLock, AnimatePresense, and BodyScrollLock work together within the Modal.

This isn't something we're looking to fix at the moment as it relates to 3 external libraries.

Thanks for understanding.
