### ISSUE TITLE
Modal crashes with Next.js when using chakra-ui/react v1.4.2 - Error: Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by Vadorequest** [chakra-ui/chakra-ui#3728]
# 🐛 Bug report

Using "@chakra-ui/react": "1.4.2", I've experience an issue when using the Modal component.

Using the [basic example](https://chakra-ui.com/docs/overlay/modal) would yield `Error: Invalid hook call. Hooks can only be called inside of the body of a function component.`.

After much troubles, I figured out downgrading to v1.2.1 fixes the issue. (I also had to downgrade framer-motion to v3.10.6 because v4 breaks Chakra)

This happened on a private repo and I don't have time to make a repro. (sorry)

## 💻 Link to reproduction

CodeSandbox reproduction: https://your-codesandbox-link-goes-here.io

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |            |
| Browser          |            |
| Operating System |            |

**Comment by segunadebayo** [comment]
Thanks for reporting this issue.

However, you didn't provide sufficient information for us to understand and reproduce the problem.

I'll re-open when we can reproduce this.
