### ISSUE TITLE
'as' prop breaks menu transition

### ISSUE THREAD

**Issue by malashevskyi** [chakra-ui/chakra-ui#3739]
# 🐛 Bug report

'as' prop breaks menu list transition.
I want to use `ul` tag for `MenuList` and `li` for `MenuItem`. `as` prop works well for `MenuButton`, `MenuItem` and I suppose it should work for `MenuList` as well. The same problem(transition) with a popover, but in that case, I don't need to change anything.

I tried to search in issues and in discussions and didn't find anything.

## 💥 Steps to reproduce
I added a transition in 2s to show the problem;
Without `as` work well:
```javascript
<MenuList transition="all 2s ease">
  <MenuItem>Download</MenuItem>
  <MenuItem>Create a Copy</MenuItem>
</MenuList>
```
But if I add `as={List}` or `as="ul"` or anything else, it breaks: when I click 'open menu' - the menu shows immediately and when I close the menu it waits for 2s and then hides.
```javascript
<MenuList transition="all 2s ease" as="ul">
  <MenuItem>Download</MenuItem>
  <MenuItem>Create a Copy</MenuItem>
</MenuList>
```

1. Go to  [codesandbox example](https://codesandbox.io/s/issue-transition-problem-i3t3t)
2. Click on 'Open menu'

## 💻 Link to reproduction
 [codesandbox example](https://codesandbox.io/s/issue-transition-problem-i3t3t)

## 🧐 Expected behavior
Want to change tag with `as` prop;

## 🧭 Possible Solution
I can wrap all inner `MenuItem` with `List` inside `MenuList`, but in that case, keyboard navigation stop working

**Comment by segunadebayo** [comment]
Hi @malashevskyi,

The `MenuList` will add `role=menu` to the underlying element so adding `as=ul` would have no effect.

Consider wrapping the menu items inside a `ul`

```jsx
        <MenuList>
          <ul>
            <MenuItem>Download</MenuItem>
            <MenuItem>Create a Copy</MenuItem>
            <MenuItem>Mark as Draft</MenuItem>
            <MenuItem>Delete</MenuItem>
            <MenuItem>Attend a Workshop</MenuItem>
          </ul>
        </MenuList>
```

PS: Just a nit-pick. Avoid passing CSS `transition` values to the MenuList as the transition/animation is handled by framer-motion.
