### ISSUE TITLE
[Theme] Overriding breakpoints not working as expected

### ISSUE THREAD

**Issue by Rixcy** [chakra-ui/chakra-ui#374]
If I override the breakpoints by extending the default config file, they seem to break some existing functionality.

Example overrides: `breakpoints: ['576px', '768px', '992px', '1200px']`

Before overriding, the following works as expected:

`<Box rounded="lg" bg={{ base: 'blue.200', lg: 'blue.700' }}>Stuff</Box>`

After overriding, the above no longer works - the large colour (blue.700) is applied regardless of viewport size.

The theme object breakpoints look like this before overriding:
![image](https://user-images.githubusercontent.com/11819124/73614634-dd95a800-45f8-11ea-905c-56926c3983c2.png)

And after overriding:
![image](https://user-images.githubusercontent.com/11819124/73614642-f8681c80-45f8-11ea-973f-16440d520d03.png)

In the [responsive styles]() example, the following is provided which makes me think it should still work with the overrides:

`<Box mt={{ base: 4, md: 0 }} ml={{ md: 6 }}>`

I'm not sure how to replicate the theme breakpoints array, since originally it's an array of 4 but shows 8 entries and after overriding I only get the 4. Is there some additional configuration needed inside the custom theme object?

**Comment by christofferberg** [comment]
I am having the same issue. 

As soon as I switch to the Object syntax for responsive styles on a components prop, the ordering of the generated css rules are not correct. 

Using the array syntax for the responsive padding values:
![image](https://user-images.githubusercontent.com/10507071/75240748-26d6b300-57c5-11ea-8027-f01409a94ead.png)

and the generated css: 
![image](https://user-images.githubusercontent.com/10507071/75240798-3c4bdd00-57c5-11ea-92ac-e0985464aa46.png)

This works like a charm. 


Switching to an object syntax for the responsive padding values: 
![image](https://user-images.githubusercontent.com/10507071/75240916-6dc4a880-57c5-11ea-97bc-f48580367d83.png)

The generated css changes:
![image](https://user-images.githubusercontent.com/10507071/75240947-7c12c480-57c5-11ea-8617-b447f6026dd6.png)

**Comment by segunadebayo** [comment]
@Rixcy, here's what you need to do to override breakpoints:

```jsx
// define your custom breakpoints
const breakpoints = ['576px', '768px', '992px', '1200px']

// add an alias for object responsive prop
breakpoints.sm = breakpoints[0]
breakpoints.md = breakpoints[1]
breakpoints.md = breakpoints[2]
breakpoints.md = breakpoints[3]

// add this custom breakpoint to your theme.
const theme = {
  breakpoints
}
```

This specification comes from `styled-system`. In future releases, we're looking to make this a lot easier. For now, I'll add this to the FAQs on the website.

Thanks

**Comment by segunadebayo** [comment]
@christofferberg, sorting the styles alphabetically is done from styled-system. We might look into this later on.

I agree that there might be some unintended side effects of sorting alphabetically.

**Comment by Rixcy** [comment]
> @Rixcy, here's what you need to do to override breakpoints:
> 
> ```js-jsx
> // define your custom breakpoints
> const breakpoints = ['576px', '768px', '992px', '1200px']
> 
> // add an alias for object responsive prop
> breakpoints.sm = breakpoints[0]
> breakpoints.md = breakpoints[1]
> breakpoints.md = breakpoints[2]
> breakpoints.md = breakpoints[3]
> 
> // add this custom breakpoint to your theme.
> const theme = {
>   breakpoints
> }
> ```
> 
> This specification comes from `styled-system`. In future releases, we're looking to make this a lot easier. For now, I'll add this to the FAQs on the website.
> 
> Thanks
> 
> PS: I just noticed you posted this 23 days ago, accept my apologies for the late response. 😅

Awesome, thanks for clarifying!
