### ISSUE TITLE
Modal > Input not work when called from Menu

### ISSUE THREAD

**Issue by sammarxz** [chakra-ui/chakra-ui#3743]
# 🐛 Bug report

`Modal > Input` not works when called from a `Menu` Component.

## 💥 Steps to reproduce

1. Create something with Menu Component
2. Create Something with Modal component and put some Input inside
3. Call the Modal Component inside the Menu Component

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/frosty-sanderson-t88bn?file=/src/Main.js

## 🧐 Expected behavior
The Input should works normal, capturing the user input.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.4.2  |
| Browser          |  Brave Browser (Chrome 89) |
| Operating System | Elementary OS 5.1.7 |

## 📝 Additional information

![Preview](https://i.imgur.com/VFZHhBw.gif)

**Comment by payapula** [comment]
@sammarxz  I digged into this to check if this has to do with `react-hook-form`, but its not.  This is happening for simple `<input/>` as well. Need to check on the implementation of Menu to find the root cause for this issue. 

I was able to reproduce this issue in this [Codesandbox repro](https://codesandbox.io/s/modest-paper-xwr8e?file=/src/Main.js)

**Comment by segunadebayo** [comment]
Hi @sammarxz, 

I think you're mixing up v0.8 with v1.4 of Chakra UI, you've also got the older versions of Emotion. Basically **don't mix up different versions of chakra and/or emotion**

I cleaned it up to only include the latest version of Chakra and here's a minimal example
https://codesandbox.io/s/menitem-trigger-modal-c670z

Hope you find that useful.

**Comment by sammarxz** [comment]
Yeah @payapula, even with native input the error persists.

@segunadebayo but the bug is not by the version, is when you try to get an input onChange event fired by Menu Open Modal button. I forked your sandbox to show:

https://codesandbox.io/s/menitem-trigger-modal-forked-zhxr6

**Comment by payapula** [comment]
@sammarxz I have placed <input /> in the forked sandbox that you provided and it seems to be working as expected. Can you please check ?

**Comment by sammarxz** [comment]
@payapula Yeah, the error persist with native `<input />`

**Comment by dbousamra** [comment]
This issue is still occurring. Not sure why it was closed.

**Comment by davidbarman** [comment]
I agree with @dbousamra.  This appears to still be an issue.

**Comment by dbousamra** [comment]
Interestingly.... all I did was copy this MenuList from the menu code, and it appears to work now: https://codesandbox.io/s/affectionate-bose-1kopi?file=/src/index.tsx

**Comment by dbousamra** [comment]
Alright, seems unrelated to my new component. Turns out just upgrading Chakra fixes it. It was broken in 1.5.2 and works in 1.6.0
