### ISSUE TITLE
Extending IconButton in extendTheme doesn't pass colorScheme or other styles

### ISSUE THREAD

**Issue by ekkusi** [chakra-ui/chakra-ui#3746]
# 🐛 Bug report

When extending IconButton in theme, new baseStyle and defaultProps are not being passed to IconButtons by default.

## 💥 Steps to reproduce

1. Extend Chakra theme with new props for IconButton and provide new theme to ChakraProvider 
2. Render a IconButton

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/heuristic-architecture-m4ljx?file=/src/App.tsx

## 🧐 Expected behavior

Colorscheme to change in IconButton after changing it in extendTheme override.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.4.2       |
| Browser          |      Chrome      |
| Operating System |      Ubuntu  20.04.1     |

**Comment by segunadebayo** [comment]
HI @ekkusi,

Sorry for the lack of document around this but the `IconButton` component uses the same style config as the `Button`. the key you want to use is `Button`.

In the future, we'll consider isolating the two of them

const theme = extendTheme({
  components: {
    Button: {
      defaultProps: {
        colorScheme: "red"
      }
    }
  }
});

**Comment by mayteio** [comment]
+1 for splitting the two!

**Comment by raffaeu** [comment]
I have accomplished in this way:

```typescript
        Button: {
            variants: {
                'drawer': (props) => ({
                    bg: props.isActive ? 'gray.600' : 'gray.700',
                    svg: {
                        color: props.isActive ? 'white' : 'white'
                    }
                })
            }
        }
```

**Comment by ODanyor** [comment]
> HI @ekkusi,
> 
> Sorry for the lack of document around this but the `IconButton` component uses the same style config as the `Button`. the key you want to use is `Button`.
> 
> In the future, we'll consider isolating the two of them
> 
> ```js
> const theme = extendTheme({
>   components: {
>     Button: {
>       defaultProps: {
>         colorScheme: "red"
>       }
>     }
>   }
> });
> ```

Please, update the doc🙏

**Comment by roitalpaz** [comment]
Hey did you by any chance split the two styles?

**Comment by yougotashovel** [comment]
Is splitting still being considered?

**Comment by effectivetom** [comment]
Splitting these up seems like it would be a good idea. It would be nice to be able to (for example) define a minimum width for buttons without that also being applied to icon buttons.

**Comment by ClarenceL** [comment]
Ok at least document this?!?

**Comment by boan-anbo** [comment]
OMG, I tried to theme IconButton for so long because it's in its own npm package. Please do split the two in theming...
