### ISSUE TITLE
[Menu] closeOnSelect not working on navigation w/ next.js links

### ISSUE THREAD

**Issue by harshzalavadiya** [chakra-ui/chakra-ui#375]
**Describe the bug**
![on-menu](https://user-images.githubusercontent.com/5774849/73649244-60743c80-46a5-11ea-9ee0-b57619e0934c.gif)
As shown above while selecting link which is wrapped in `next/link` in `MenuItem`, `MenuList` isn't closing automatically as it does for normal links or any items in menu list

Is there any workaround/way to close menu on dynamic links selection?

**Minimal Example**
[![Edit sleepy-cori-811en](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sleepy-cori-811en?fontsize=14&hidenavigation=1&theme=dark)

**Expected Behavior**
It should automatically close on selection

**To Reproduce**
- Create menu links wrapped under `next/link`
- Select any option

**Suggested solution(s)**

**Desktop (please complete the following information):**

**Additional context**
I think it's happning due to next.js overtaking link component and preventing it on click so parent isn't able to detact event

**Comment by jhoch** [comment]
I had this issue, too, but solved it using the `onClose` property that `Menu` can pass to its children.  For example:

```jsx
<Menu>
  {({ onClose }) => (
    <MenuList>
      <NextLink>
        <MenuItem as="a" onClick={onClose}>
          Hello World
        </MenuItem>
      </NextLink>
    </MenuList>
  )}
</Menu>
```

**Comment by export-mike** [comment]
Seems related, I'm finding the menu isn't closing when I click anything other than the menu itself?


![ezgif-4-6139f0850e20](https://user-images.githubusercontent.com/2983327/83504301-b0ee9000-a507-11ea-93c4-a5efdcb818a5.gif)

**Comment by export-mike** [comment]
ah ok got it, pass down ref!

**Comment by MohammedAK1991** [comment]
none of these things work for me..
Is there a workaround??

**Comment by heythisispaul** [comment]
@MohammedAK1991 in case this is still an issue for you, check out #3994

There was an issue with the peer dependency `framer-motion`.
