### ISSUE TITLE
<Text> component cannot be forced to specific color mode 

### ISSUE THREAD

**Issue by x-EricH-x** [chakra-ui/chakra-ui#3753]
# 🐛 Bug report

Wrapping `Text` component inside `LightMode` or `DarkMode` does not force it to the specified mode.

## 💥 Steps to reproduce

1. Wrap a `<Text>` inside `<LightMode>` or `<DarkMode>`
2. Run the app and switches color mode.
3. `<Text>` changes color mode even if it is wrapped.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/jolly-pasteur-1wp21

## 🧐 Expected behavior

`<Text>` stays in the specified color mode.

## 🌍 System information

| Software         | Version(s) |
| --------------- | ---------- |
| Chakra UI              | 1.4.2 |
| Browser                 | Google Chrome Version 89.0.4389.114 (Official Build) (64-bit) |
| Operating System |  MS Win 10 Home (10.0.19042 Build 19042) |

## 📝 Additional information

Maybe related:
[No colormode in text and layer styles #3451](https://github.com/chakra-ui/chakra-ui/issues/3451)

**Comment by gCardinal** [comment]
I also see this problem. Same Chakra UI version.

**Comment by segunadebayo** [comment]
The `Text` component doesn't have any color property specified so it inherits it from `body`. It is effectively just a `p` tag with the ability to pass chakra's style props.

Here's how you can get that working:

```jsx
// create a custom text component that changes its color based on color-mode
const CustomText = (props: TextProps) => {
  return <Text color={useColorModeValue("black", "white")} {...props} />;
};
```

Hope you find this useful

**Comment by gCardinal** [comment]
While I understand it's by design, wouldn't it make more sense for all components to respond to the color mode automatically? As it is, every component in the library will change based on the color mode, except `Text` and `Heading`.

**Comment by x-EricH-x** [comment]
Thank you @segunadebayo , your suggestion and clarification definitely helped.
