### ISSUE TITLE
Circular Progress has a tiny part of the progress ring that appears even when the value is 0.

### ISSUE THREAD

**Issue by thefatstack** [chakra-ui/chakra-ui#3754]
# 🐛 Bug report

I currently have a particular issue with Circular Progress in Safari 14.0.3 (MacOS 10.15.7) (Chrome, Edge, Firefox,... are fine), where there is a tiny part of the progress ring that appears even when the value is 0.

## 💥 Steps to reproduce

1. Using a Circular Progress component (or using the example on the docs) on Safari 14 (iOS and ipadOS as well)
2. Pass 0 to the `value` props
3. Look at the start of the ring and see the tiny part.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/autumn-frost-djsf8?file=/src/App.tsx

## 🧐 Expected behaviour

Expected there is no tiny part that appears not only on Safari but all browsers.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.4.2        |
| Browser          | Safari 14.0.3          |
| Operating System | MacOS Catalina 10.15.7, iOS 14           |

## 📝 Additional information

![Screen Shot 2021-04-05 at 3 57 34 PM](https://user-images.githubusercontent.com/52730845/113824331-dd1f1100-97a9-11eb-8962-3d4c93ba2f62.png)

**Comment by segunadebayo** [comment]
Good catch @thefatstack!

I just pushed an update for this. Will be out in the next release.

Cheers

**Comment by thefatstack** [comment]
Thanks, @segunadebayo! Really productive!
