### ISSUE TITLE
Select icon should be at the inline-end for RTL

### ISSUE THREAD

**Issue by manzoorwanijk** [chakra-ui/chakra-ui#3755]
# 🐛 Bug report

The icon for `Select` is always on the right, regardless of LTR or RTL.

## 💥 Steps to reproduce

1. Go to the sandbox
2. Check the icon position

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/chakra-ui-select-rtl-icon-1kwbx

## 🧐 Expected behavior

The icon should be at the end (on the left for RTL, right for LTR)

![image](https://user-images.githubusercontent.com/18226415/113838729-aeef0080-97ac-11eb-9edd-18d9e88c3260.png)

## 🧭 Possible Solution

It should be placed at the inline-end, instead of right. 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.4.2      |
| Browser          |      Chrome      |
| Operating System |      Windows 10      |

**Comment by HcroakerDev** [comment]
Hi there, not sure if this is a related issue but thought I should bring it up as we have been having issues with it. The select dropdown arrow seems to not work correctly when the width is changed. You can see this issue on the chakra-ui home page:
<img width="1440" alt="Screen Shot 2021-04-08 at 2 07 29 pm" src="https://user-images.githubusercontent.com/39733666/113967360-29cf1e80-9874-11eb-8718-bd166afee160.png">
