### ISSUE TITLE
Responsive breakpoints not working for heading

### ISSUE THREAD

**Issue by antonyleme** [chakra-ui/chakra-ui#3764]
# 🐛 Bug report

I can't use responsive breakpoints with Heading element. 

![image](https://user-images.githubusercontent.com/36122235/113932003-84f80700-97c9-11eb-912f-b4b0de80a900.png)
![image](https://user-images.githubusercontent.com/36122235/113932101-9e00b800-97c9-11eb-87e5-d87b2178c3e0.png)

## 💥 Steps to reproduce

Just import a Heading element and try to use the breakpoints in an array or even in a object structure.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/chakra-heading-breakpoints-forked-e09mk?file=/src/index.js

## 🧐 Expected behavior

Should have different sizes for each breakpoint.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      Latest      |
| Browser          |      Opera/Chrome      |
| Operating System |     Windows       |

**Comment by karland** [comment]
In your codesandbox, you have not wrapped a `Provider` around the app. Have a look here:

https://codesandbox.io/s/chakra-heading-breakpoints-forked-e09mk?file=/src/index.js

See the documentation here: https://chakra-ui.com/docs/getting-started#set-up-provider

Maybe that helps.

**Comment by antonyleme** [comment]
Yeah, my mistake while doing the preview. I just forgot. But not working yet. The same issue happens with the Avatar component for me.

**Comment by segunadebayo** [comment]
Hi @antonyleme,

Responsive values for `variant` and `size` props are still a work in progress #3258.

We never mentioned that this was possible in the docs. If we did, kindly point me to it so I can edit accordingly.

Thanks
