### ISSUE TITLE
Toast are extremly big when showing

### ISSUE THREAD

**Issue by kentng201** [chakra-ui/chakra-ui#3766]
# 🐛 Bug report

The toast UI show is incorrect, below attached UI shown
![Screenshot 2021-04-08 at 12 07 30 PM](https://user-images.githubusercontent.com/4708656/113967282-3d25be00-9863-11eb-9788-c282dd70ff6e.png)

## 💥 Steps to reproduce
npx create-react-app my-app --template typescript
yarn add @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^4

replace App.tsx content
```tsx
import './App.css';
import { Box, Button, ChakraProvider, Skeleton, Text, theme, useToast } from "@chakra-ui/react";
import React from 'react';

function App() {
  const toast = useToast();

  React.useEffect(() => {
    
  }, []);
  return (
    <ChakraProvider theme={theme}>
      <Box>
        <Text>hi</Text>
        <Skeleton h="40px"></Skeleton>
        <Button 
          colorScheme="red"
          onClick={() =>
            toast({
              title: `success toast`,
              status: 'success',
              isClosable: true,
            })
          }
        >Click</Button>
      </Box>
    </ChakraProvider>
  )
}

export default App;
```

## 💻 Link to reproduction
https://codesandbox.io/s/relaxed-banzai-s5304

## 🧐 Expected behavior
Toast shown as correct UI

## 🧭 Possible Solution
Is that any css needs to import before use?

## 🌍 System information
| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     ^1.5.0       |
| Browser          |    Google Chrome Version 89.0.4389.114        |
| Operating System |      macOS Big Sur 11.1      |

**Comment by malashevskyi** [comment]
I had the same problem.

**Comment by malashevskyi** [comment]
I had the same problem.
1. Your example (Link to reproduction) doesn't work for me because you export `App` component incorrectly.
2. About toast. `useToast` must be inside the ChakraProvider, otherwise it doesn't get styles.

One way to solve:
You can add ChakraProvider to index.tsx instead of App.tsx
```javascript
ReactDOM.render(
  <React.StrictMode>
    <ChakraProvider>
       <App />
    </ChakraProvider>
  </React.StrictMode>,
  document.getElementById("root")
)
```

**Comment by NaungYeHtet** [comment]
Not working in version 2.5.1

**Comment by ryanhefner** [comment]
@NaungYeHtet Not sure if this will help you or not, but I was running into the same issue, until I added the `Alert` base styles to the `components` entry within my custom `theme`.

```js
import { Alert } from '@chakra-ui/theme/components'

const theme = {
  components: {
    Alert
    ...
  }
}

**Comment by elbezz** [comment]
strangely is working perfectly - thanks a lot!

**Comment by elbezz** [comment]
> @NaungYeHtet Not sure if this will help you or not, but I was running into the same issue, until I added the `Alert` base styles to the `components` entry within my custom `theme`.
> 
> ```js
> import { Alert } from '@chakra-ui/theme/components'
> 
> const theme = {
>   components: {
>     Alert
>     ...
>   }
> }
> ```

strangely is working perfectly - thanks a lot!
