### ISSUE TITLE
Request to add size-aware collapsible Breadcrumb component

### ISSUE THREAD

**Issue by jaredpalmer** [chakra-ui/chakra-ui#377]
**Is your feature request related to a problem? Please describe.**
Breadcrumbs aren't awesome on smaller screens. It's rather annoying to have to hide them or truncate them by hand.

**Describe the solution you'd like**
Make a new combo of menu, breadcrumb, and a new size-aware container (for truncation) to allow for a more useful breadcrumb component that worked like VSCode's or Blueprint.js breadcrumbs. 

**Additional context**

![Kapture 2020-02-03 at 11 09 17](https://user-images.githubusercontent.com/4060187/73669576-add8b580-4675-11ea-99eb-e251e7dcae5b.gif)

Blueprint's Breadcrumb: https://blueprintjs.com/docs/#core/components/breadcrumbs

**Comment by with-heart** [comment]
This is an interesting idea. Commenting to remove stale status.

**Comment by segunadebayo** [comment]
We won't be supporting this for now @with-heart. I'll close it out.
