### ISSUE TITLE
Styles unsyncing (?) with NextJS

### ISSUE THREAD

**Issue by binajmen** [chakra-ui/chakra-ui#3776]
Hi everyone,

I'm struggling for more than 48h with this issue, so I decided to overpass the feeling this is a specific issue from my side and to leverage your experience and brains as mine is 🤯 

FYI, my setup is NextJS + TypeScript + Chakra UI.

I have some kind of "styling unsyncing" that appeared recently, and I'm unable to find the cause.

What I noticed though is the weird amount of styles piling up. My first question would be: **is this normal?** The 
subsidiary question would be: **what would be the cause?**

![Screenshot 2021-04-09 at 09 55 52](https://user-images.githubusercontent.com/15611419/114149149-e11e7080-991a-11eb-85f1-124cc072d70b.png)
![Screenshot 2021-04-09 at 09 56 18](https://user-images.githubusercontent.com/15611419/114149157-e380ca80-991a-11eb-9c8a-64af23ca7fc9.png)
![Screenshot 2021-04-09 at 09 56 35](https://user-images.githubusercontent.com/15611419/114149166-e5e32480-991a-11eb-8190-21f9169099f0.png)
![Screenshot 2021-04-09 at 09 56 49](https://user-images.githubusercontent.com/15611419/114149172-e8457e80-991a-11eb-89f9-04689d9865cc.png)

Another strange thing is when I'm hovering a button, the styling of the drawer breaks:

![ezgif-7-346d530153f5](https://user-images.githubusercontent.com/15611419/114150785-b7fedf80-991c-11eb-9b99-626bcb481f70.gif)

And finally, from one page transition to another (using `next/link`), scroll is (sometimes..) disabled/not working.

Unfortunately, I can't share the repo as it is private and not mine. I tried to reproduce the issue in a sandbox without success..

I know animated gif is not the greatest to help debugging, but I'm willing to share any code snippet you would suspect being the problem ! 🙏 🙏 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       1.3.3     |
| Browser          |     Chrome       |
| Operating System |      MacOS      |

**Comment by payapula** [comment]
@binajmen Based on my experience with Chakra and NextJs

> is this normal?

Yes this is normal.

> what would be the cause? 

The Styles that we see in the dev tools are from Chakra's [default theme](https://chakra-ui.com/docs/theming/theme)

> one page transition to another (using next/link)

If you have custome functional component that wraps the link `<a></a>` then you need to pass the ref from `next/link` via the props `passHref` - Read about this [on ref forwarding in the next docs](https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag)

To reproduce your problem have you tried this template ?   [NextJS TypeScript CodeSandbox template](https://codesandbox.io/s/chakra-ui-next-js-typescript-kxvyr)

**Comment by binajmen** [comment]
I was able to put in place a repo to reproduce the styling issue:
https://github.com/binajmen/chakra-nextjs

You can reproduce the issue by following these steps:
1. Go to https://orderbru-crqewikkia-ew.a.run.app/
2. Open/close the menu: everything looks fine
3. Click on "Se connecter"
4. Use the email/password "demo@demo.com" and "demodemo"
5. Reopen the menu: styles are broken

I suspect something is breaking the style in the `Menu` component. But I tried a lot of things, I don't understand what's the issue..

https://github.com/binajmen/chakra-nextjs/blob/develop/components/layout/Menu.tsx

**Comment by payapula** [comment]
Hi @binajmen 

Thank you for the details. I looked into the demo that you shared. However I am not able to run the app from the repo (due to some firebase error).

As you said it is related to the styles that are being loaded. The next/link is prefetching when you open the drawer which is causing the present styles applied on the drawer to collapse.

As you can see in the GIF below the styles getting collapsed after the next prefetches the account/ related route. 

![Styles](https://user-images.githubusercontent.com/7134153/114276323-bd0a7e80-9a43-11eb-989d-e02ad69b5276.gif)

Next prefetches the links with static generation by default. 

Can you try disabling the `prefetch={false}` option of next/link inside the drawer ?

**Comment by binajmen** [comment]
Hi @payapula,

Thank you for taking the time to look at my issue. I've followed your advice and add `prefetch={false}` in the component `NextButton`. Unfortunately, this is not solving the issue. However, the behaviour is different now: the drawer is fine, but when I'm hovering (not even clicking) the "Mon compte" button, the design breaks again..

![ezgif-7-cbdf28bfdf6a](https://user-images.githubusercontent.com/15611419/114278304-7c086f00-9a2f-11eb-9199-3c7d5565ef08.gif)

The change: https://github.com/binajmen/chakra-nextjs/blob/with-firebase/components/atoms/NextButton.tsx

You can test on live: https://orderbru-crqewikkia-ew.a.run.app/

**Comment by binajmen** [comment]
Is prefetch also performed on hovering?

![ezgif-2-d901a1a2a851](https://user-images.githubusercontent.com/15611419/114279395-be807a80-9a34-11eb-8a5c-9e392f69d231.gif)

Prefetch is a good strategy. It would be a pitty to deactivate that. But I cannot understand why the prefetched code is added in the body **AND** get executed

**Comment by payapula** [comment]
Thanks @binajmen  

When we hover on that link, we are loading the same js code again, this is by [default on nextjs](https://github.com/vercel/next.js/pull/18859) . 

![Styles_hover](https://user-images.githubusercontent.com/7134153/114279331-aec35f00-9a51-11eb-8e71-b6e1f2270ec0.gif)


Now that we understand the problem that the /account related code is breaking our current styles, you may be need to debug on the routes and check what content is loaded for /account. You can try analysing that account bundle to check what code is loaded. 

Also I advice you to not set `prefetch={false}` for all the routes, Instead you can pass-in as prop to NextButton and default it to `true`

```jsx
export default function NextButton(props: NextButtonProps) {
  const { children, pathname, query = {}, prefetch = true, ...buttonProps } = props

  return (
    <Link href={{ pathname, query }} prefetch={prefetch}>
      <Button {...buttonProps}>
        {children}
      </Button>
    </Link>
  )
}
```

> how did you manage to delay the design breaking itself? 3G mode?

I didn't do anything, it loaded like that for me, (I might be having slow connection oops!)

**Comment by payapula** [comment]
@binajmen  Also since this involves authentication, make sure you read the docs about the [authentication patters on next js](https://nextjs.org/docs/authentication) and [an example with  firebase](https://github.com/vercel/next.js/tree/canary/examples/with-firebase-authentication) might help.

> The first step to identifying which authentication pattern you need is understanding the **data-fetching strategy** you want. We can then determine which authentication providers support this strategy. There are two main patterns:

**Comment by payapula** [comment]
@binajmen  one more idea, Instead of Link you can try navigation with `useRouter()` from [next router](https://nextjs.org/docs/api-reference/next/router) to avoid this prefetching in the first place.

**Comment by binajmen** [comment]
Hi @payapula,

> Now that we understand the problem that the /account related code is breaking our current styles, you may be need to debug on the routes and check what content is loaded for /account. You can try analysing that account bundle to check what code is loaded.

It's hard to read the bundle in its minified version. But looking at the source, it seems to me nothing special is done. Well, the `Drawer` is also used in the `/account` page (in fact, the `Menu` is used in all pages as part of the Header). I have the feeling the styles from the `Drawer` from the `/account` page are applied in the `/index` page, therefore unsyncing the styles. But I have trouble to prove that (+ it wouldn't solve my issue).

> Also I advice you to not set `prefetch={false}` for all the routes, Instead you can pass-in as prop to NextButton and default it to `true`

I think the prefetching is a good strategy and that's what makes Next smooth when transitioning from page to page. It would be a pity to deactivate that in the first place..

> @binajmen Also since this involves authentication, make sure you read the docs about the [authentication patters on next js](https://nextjs.org/docs/authentication) and [an example with firebase](https://github.com/vercel/next.js/tree/canary/examples/with-firebase-authentication) might help.

Yes, I'm already using their suggestion (`next-firebase-auth`).

> > why the prefetched code is added in the body AND get executed
> 
> This is how the code would be executed with the bundlers like webpack, rollup etc.

But from https://web.dev/route-prefetching-in-nextjs/, I understand that: "Next.js only fetches the JavaScript; it doesn't execute it. That way, it's not downloading any additional content that the prefetched page might request until you visit the link."

So it should not execute that code. I can't figure out why it gets executed in my case..

> @binajmen one more idea, Instead of Link you can try navigation with `useRouter()` from [next router](https://nextjs.org/docs/api-reference/next/router) to avoid this prefetching in the first place.

Yes I could (and I will try). However, this doesn't feel right: something is not working the way it should. Trying to bypass the problem instead of fixing it is a big risk: it's the kind of thing that will explode in my face in the future.

I can't thank you enough for your help, I have the feeling we're narrowing down the problem, just need additional steps to fix it !

**Comment by binajmen** [comment]
I think I found out what is causing this mess: I'm using RGPA that somehow uses `@emotion/react` in a way that it causes a "double-load" (not sure how I'm supposed to call that), probably messing with the whole thing.. If I remove this component, everything seems to work properly..

I've opened an issue there to see how I can solve that (https://github.com/Tintef/react-google-places-autocomplete/issues/176). Otherwise, I'll have to find an alternative for this `AddressField`.

**Comment by payapula** [comment]
Glad that you found the root cause! 

I looked into the `react-google-places-autocomplete` they are using `react-select` package which in turn uses `emotion` for styling. Hope it helps.

**Comment by binajmen** [comment]
Yes, perhaps I'll open an issue on their side, as it could impact others in the future (if not already).

Thank you for your support in this debugging process @payapula, really appreciate it ;)

**Comment by violabg** [comment]
I have a project that uses react-select and Have a similar problem, it is definitely related to react-select and there emotion package been in conflict with chakra-ui.
Basically the pages that use react-select are working fine, if you go to a page that doesn't use it, still works, but if you reload that page, the style breaks.
I didn't find a solution yet to use react-select with chakra-ui and next-js.

**Comment by violabg** [comment]
found a related issue on react-select

https://github.com/JedWatson/react-select/issues/4541

**Comment by jonidelv** [comment]
Should be fixed https://github.com/JedWatson/react-select/issues/4541#issuecomment-855090442
