### ISSUE TITLE
Different layouts between Safari and any other browser

### ISSUE THREAD

**Issue by jahirfiquitiva** [chakra-ui/chakra-ui#3781]
# 🐛 Bug report

My website is looking different in Safari compared to any other browser

## 💥 Steps to reproduce

1. Go to [https://synaptiko.io](https://synaptiko.io) in Safari browser
2. Go to [https://synaptiko.io](https://synaptiko.io) in any other browser
3. See the differences

## 🧐 Expected behavior

The website should look exactly the same in any browser

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.5.0 |
| Browser          | Safari |
| Operating System | MacOS 11.2.3 |

**Comment by segunadebayo** [comment]
Hi @jahirfiquitiva,

This isn't an issue with Chakra UI. Please take the time to check the differences in the layout and fix them on your site.

Btw, I checked on my end and it seems to be the same.

**Comment by jahirfiquitiva** [comment]
I would say it is related to Chakra UI... I don't have any other custom styles of any sort ... yet here's what it looks like in the same device... using Brave and Safari

![Shot 2021-04-13 at 10-41-02@2x](https://user-images.githubusercontent.com/10360816/114581865-afbce200-9c45-11eb-85e9-c733179f4c2d.png)


![Shot 2021-04-13 at 10-41-48@2x](https://user-images.githubusercontent.com/10360816/114581826-a764a700-9c45-11eb-885f-b06b4b8c09bc.png)

See how the content is messed up in Safari

<img width="1495" alt="Shot 2021-04-13 at 10-48-51@2x" src="https://user-images.githubusercontent.com/10360816/114582177-f8749b00-9c45-11eb-9798-68b95d9902d4.png">

<img width="1549" alt="Shot 2021-04-13 at 10-48-05@2x" src="https://user-images.githubusercontent.com/10360816/114582207-ff031280-9c45-11eb-92cc-cf4a1d342f30.png">
