### ISSUE TITLE
Circular progress isIndeterminate broken

### ISSUE THREAD

**Issue by brennanfife** [chakra-ui/chakra-ui#3789]
https://codesandbox.io/s/pensive-star-wd3zp?file=/src/App.tsx:389-404

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.5.0         |
| Browser          |     chrome       |
| Operating System |     mac       |

## Additional Notes
Moving back to version 1.4.2 solves this issue

**Comment by segunadebayo** [comment]
This has been fixed in a recent PR. We'll release an update shortly
