### ISSUE TITLE
[Popover] Content shifts once JavaScript loads and runs

### ISSUE THREAD

**Issue by feross** [chakra-ui/chakra-ui#3792]
# 🐛 Bug report

I found a similar issue to https://github.com/chakra-ui/chakra-ui/issues/3668 but for the `Popover` component.

## 💥 Steps to reproduce

1. Go to https://wormhole.app
2. Open DevTools > Network tab
3. Set Throttling to "Slow 3G"
4. Reload the page.
5. Click the browser's "Stop" button when you see the header shifted down. It'll look like this:

<img width="1124" alt="Screen Shot 2021-04-12 at 8 54 28 PM" src="https://user-images.githubusercontent.com/121766/114494766-c164a200-9bd1-11eb-89f3-12b782bd396e.png">

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/confident-aryabhata-d4tjv?file=/src/App.js

Although it doesn't seem possible to Disable JS in the Chrome web inspector and have CodeSandbox load, so you might need to put this into an SSR'd app to see it.

## 🧐 Expected behavior

The `Popover` is taking up space even before it has been opened. It seems that it's actually hidden (and stops taking up space) only once the JavaScript has been downloaded and runs.

<img width="1122" alt="Screen Shot 2021-04-12 at 8 55 23 PM" src="https://user-images.githubusercontent.com/121766/114494784-cc1f3700-9bd1-11eb-9173-012c48724c40.png">

This means that the SSR'd page looks different from the final page once JS arrives and runs.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.5.0      |
| Browser          |       Chrome     |
| Operating System |     macOS latest       |

**Comment by segunadebayo** [comment]
Hi @feross,

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by feross** [comment]
Thanks, @segunadebayo. Confirmed it works.
