### ISSUE TITLE
all button focus have outline or border，how to remove this

### ISSUE THREAD

**Issue by jianly** [chakra-ui/chakra-ui#3794]
![image](https://user-images.githubusercontent.com/30860965/114518451-f58f9f80-9c71-11eb-90df-0ba5b1615b77.png)
![image](https://user-images.githubusercontent.com/30860965/114518472-f9232680-9c71-11eb-808e-95b395481e57.png)
![image](https://user-images.githubusercontent.com/30860965/114518520-0809d900-9c72-11eb-8ca2-045dadcf2312.png)

**Comment by segunadebayo** [comment]
Hi @jianly,

Kindly install the `focus-visible` package, and import it at the root level of your app. It'll remove the focus outlines for mouse interactions.
