### ISSUE TITLE
Confusing example on Global Styles within the documentation

### ISSUE THREAD

**Issue by simontaisne** [chakra-ui/chakra-ui#3796]
On the [Global Styles](https://chakra-ui.com/docs/features/global-styles) documentation, the following example is used to illustrate the `theme.styles.global` style object and could imo lead to errors.

```js
const theme = {
  styles: {
    global: {
      "html, body": {
        fontSize: "sm", // <-- that part
        color: "gray.600",
        lineHeight: "tall",
      },
      a: {
        color: "teal.500",
      },
    },
  },
}
```

With the `"html, body"` selector, the font size for all text elements will now compute to `12.25px` (16 x 0.875 x 0.875 = 12.25) instead of the expected `14px`.

**Comment by segunadebayo** [comment]
That was just an example but I do see your points. I've updated the docs.
