### ISSUE TITLE
Invalid markup inside <Stat /> component

### ISSUE THREAD

**Issue by rastersysteme** [chakra-ui/chakra-ui#3799]
# 🐛 Bug report

When using `StatHelpText` inside the `Stat` component a `p` element is rendered inside the wrapping `dl` which is **not** allowed according to the [HTML specs](https://www.w3.org/TR/html52/grouping-content.html#the-dl-element).

## 💥 Steps to reproduce

1. Visit [Chakra UI Stat docs](https://chakra-ui.com/docs/data-display/stat)
2. Scroll to [first example](https://chakra-ui.com/docs/data-display/stat#basic-usage)
3. Inspect third element
4. You'll see a `p` element inside the `dl`

![image](https://user-images.githubusercontent.com/1895414/114570937-89fc0100-9c76-11eb-81f8-a382c5d21885.png)

## 💻 Link to reproduction

https://github.com/chakra-ui/chakra-ui/blob/main/packages/stat/src/stat.tsx#L34

## 🧐 Expected behavior

The HTML validator shouldn’t report this error:
![image](https://user-images.githubusercontent.com/1895414/114571451-f8d95a00-9c76-11eb-93f6-23606fd93038.png)

## 🧭 Possible Solution

Instead of using a `p` element, `StatHelpText` should be rendered as another `dd` element.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.5.0      |
| Browser          |      doesn't matter      |
| Operating System |     doesn’t matter       |

## 📝 Additional information

– none –

**Comment by davidsonsns** [comment]
just ran lighthouse and got a similar message related to it

[`<dl>s do not contain only properly ordered <dt> and <dd> groups, <script>, or <template> elements`](https://web.dev/definition-list/?utm_source=lighthouse&utm_medium=devtools)

I'll be happy to make my first contribution fixing it. If so, let me know if sounds good assigning it to me
