### ISSUE TITLE
Add Chakra theme support or documentation for the [Collapse] component

### ISSUE THREAD

**Issue by davidhousedev** [chakra-ui/chakra-ui#380]
**Is your feature request related to a problem? Please describe.**
While implementing the Collapse component, I spent some time believing that the `startingHeight` was broken because, like all other Chakra components, I was passing a string "20", and anticipating that it would reference a size value from my theme.

I then realized that this value was being passed directly to `react-animate-height` and it was not going through my theme.

**Describe the solution you'd like**
I would like for `react-animate-height` in the [Collapse] component to be wrapped by the Chakra theme under the hood, so that I can use the same API for `startingHeight` as I do for, e.g. `height`. 

**Describe alternatives you've considered**
One alternative would be to add documentation for [Collapse] that warns users not to Chakra theme values for `startingHeight`.

**Additional context**
Keep up the great work!

**Comment by tioluwani94** [comment]
Hi @davidhousedev, this has been documented in preparation for the TypeScript release of Chakra UI.
