### ISSUE TITLE
Misalignment of icon inside <Button /> component

### ISSUE THREAD

**Issue by rastersysteme** [chakra-ui/chakra-ui#3800]
# 🐛 Bug report

The icon inside a `<Button />` is not centered correctly.

## 💥 Steps to reproduce

1. Visit [Chakra UI Button docs](https://chakra-ui.com/docs/form/button)
2. Scroll to [Button with icon example](https://chakra-ui.com/docs/form/button#button-with-icon)
3. Have a look at the second button with the right arrow.

![image](https://user-images.githubusercontent.com/1895414/114574278-68504900-9c79-11eb-9247-525c6d29474e.png)

The icon top space is larger than the bottom space.

## 💻 Link to reproduction

https://github.com/chakra-ui/chakra-ui/blob/main/packages/button/src/button.tsx#L152

## 🧐 Expected behavior

The icon should be centered correctly, the amount of space above and below of it should be the same.

## 🧭 Possible Solution

The problem is, that the SVG-icon is put inside a `span` and doesn’t benefit from being a flex-item anymore, which means the `align-items: center` from the `button` doesn’t affect the SVG element. Instead `display: inline-block` and `vertical-align: middle` is set on the SVG which causes the misalignment because the icon itself has a height of 16px but the wrapping `span` is 19px high.

![image](https://user-images.githubusercontent.com/1895414/114577894-b61a8080-9c7c-11eb-891b-e96ce321f96f.png)
![image](https://user-images.githubusercontent.com/1895414/114577991-ca5e7d80-9c7c-11eb-9582-cc8fa3bb711c.png)

Solution: If the SVG inside the `span` would be set to `display: block` here (so `vertical-align` has no effect and therefore isn’t needed anymore), the wrapping span gets the height of the icon which would be perfectly centered then.

![image](https://user-images.githubusercontent.com/1895414/114578697-6c7e6580-9c7d-11eb-924b-3c4906f6f7db.png)

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.5.0      |
| Browser          |      Chrome 89 and Firefox  87    |
| Operating System |     Mac OS       |

## 📝 Additional information

– none –

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
