### ISSUE TITLE
Spinner baseStyle color can't be overridden

### ISSUE THREAD

**Issue by tmikeschu** [chakra-ui/chakra-ui#3803]
# 🐛 Bug report

If `components.Spinner.baseStyles.color` is set, any `color` prop passed to `Spinner` will not override the `baseStyle` value.

## 💥 Steps to reproduce

1. Set `components.Spinner.baseStyles.color` to any color (e.g., `blue.400`).
2. Render `<Spinner color="red.400" />`
3. See that the color is `blue.400`.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/chakra-spinner-color-bug-nt62x?file=/src/App.tsx

## 🧐 Expected behavior

I expect the baseStyle color to be overridable.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       1.4.2 and 1.5.0     |
| Browser          |      Brave      |
| Operating System |        macos    |

## 📝 Additional information

Current workarounds: use `emptyColor` or the `sx.color` prop.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by tmikeschu** [comment]
@segunadebayo thanks for the quick response!
