### ISSUE TITLE
[CSSReset] Custom Config Documentation

### ISSUE THREAD

**Issue by kolyasapphire** [chakra-ui/chakra-ui#381]
**Describe the bug**
By default, `<html>` background color is set to theme.colors.gray[800], it took me a while to find where it was coming from and how to correct it to an appropriate colour.

**Suggested solution(s)**
In docs this could be mentioned on the [Color Mode page](https://chakra-ui.com/color-mode), or as a separate page for CSSReset in Components or Utilities (where it makes better sense), documenting how to configure a custom config for CSSReset. Personally, I think [Color Mode page](https://chakra-ui.com/color-mode) is most appropriate, I would be happy to submit a pull request if needed.

**Comment by segunadebayo** [comment]
Hi @kolyasapphire, thanks for bringing this up.

I'll appreciate a PR that adds a CSS Reset page and mentions all the things you listed above.

Thanks again.

**Comment by kolyasapphire** [comment]
Hi @segunadebayo , done!

Please check if everything is alright.
