### ISSUE TITLE
Upgrading to 1.5.1 breaks SSR

### ISSUE THREAD

**Issue by feross** [chakra-ui/chakra-ui#3817]
# 🐛 Bug report

This is a really strange issue and I haven't been able to make a minimal reproduction for it. Opening this to see if anyone has any pointers or ideas to what might be causing the issue.

For some reason, since updating to 1.5.1 we're seeing that SSR doesn't work anymore.

## 💥 Steps to reproduce

Example with chakra 1.5.1: https://wormhole-pr-379.onrender.com/
Example with chakra 1.5.0: https://wormhole-pr-380.onrender.com/

If you inspect the HTML sent by the server, you'll see the difference:

1.5.1:

<img width="1472" alt="Screen Shot 2021-04-14 at 4 07 37 PM" src="https://user-images.githubusercontent.com/121766/114791524-8aaa9b00-9d3b-11eb-855f-cbc1e1c6ca5a.png">

1.5.0:

<img width="1460" alt="Screen Shot 2021-04-14 at 4 11 57 PM" src="https://user-images.githubusercontent.com/121766/114791918-29cf9280-9d3c-11eb-9c13-e4c3a67e35e6.png">

The only difference between these URLs is the version of chakra used.

## 💻 Link to reproduction

I wasn't able to make a minimal reproduction.

## 🧐 Expected behavior

Chakra should not (seemingly) cause SSR to be disabled.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.5.1         |
| Browser          |   Chrome        |
| Operating System |   macOS         |

**Comment by segunadebayo** [comment]
I'm looking into this!

**Comment by segunadebayo** [comment]
Found where the bug is and I've pushed a fix for it. We'll release an update shortly.

**Comment by feross** [comment]
@segunadebayo Thanks for the quick fix!

**Comment by JClackett** [comment]
@segunadebayo Thanks for the fix, any ideas when the fix will be released?
