### ISSUE TITLE
Slider bug 

### ISSUE THREAD

**Issue by aboveyunhai** [chakra-ui/chakra-ui#3818]
> # 🐛 Bug report
> slider can only be moved once
> 
> ## 💥 Steps to reproduce
> Slider is broken/fixed after first slide
> 
> ## 💻 Link to reproduction
> It seems like all sliders on official Chakra doc has the exact problem.
> https://chakra-ui.com/docs/form/slider
> 
> ## 🧐 Expected behavior
> Slider can be freely moved without customization.
> 

The same issue re-appears in latest Chakra UI  version (1.5.1). Official website suffers from the same issue.
https://github.com/chakra-ui/chakra-ui/issues/3040

I believe we need to do some investigation about the current implementation.

**Comment by with-heart** [comment]
Can definitely confirm through just through the docs site alone.
