### ISSUE TITLE
"Navbar with right cta" - portal zIndex issue

### ISSUE THREAD

**Issue by aravind-tc** [chakra-ui/chakra-ui#3819]
# 🐛 Bug report

I am using this premium component navbar mentioned in the subject line. In mobile mode , i am not able to click the close button. The reason is zIndex of portal is 40. It is blocking the menu. is this a known issue? Can you please fix it?

## 💻 Link to reproduction

CodeSandbox reproduction: https://your-codesandbox-link-goes-here.io

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |            |
| Browser          |            |
| Operating System |            |

**Comment by segunadebayo** [comment]
Hi, this issue is related to Chakra UI Pro. Please open the issue there instead.

Cheers.
