### ISSUE TITLE
Chakra as an open-source needs to be a bit more responsible with changes.

### ISSUE THREAD

**Issue by manzoorwanijk** [chakra-ui/chakra-ui#3825]
We have been using Chakra since it was born and really love it. Thank you for this amazing library.

There is something I want to mention/rant about.

I think being an open source project with high usage, you ought to be a bit responsible with changes. If there is something that breaks an existing code, it SHOULD be released as a breaking change.
A recent (supposedly non-breaking) [change](https://github.com/chakra-ui/chakra-ui/releases/tag/%40chakra-ui%2Freact%401.5.1) to `ChakraProvider`, led to the loss of two days of debugging the test failures for two devs! It was nowhere in our minds that Chakra would result in that failure.
All of us test our components and provide a context to the test renderers. Now that recent change conditionally renders the children if and only if it's a certain environment. Now in test renderers, we do not have that expected environment and thus it rendered nothing, resulting in weird test failures. The least that could have been done was to make the change backward compatible or list it as a breaking change.

Same goes with `Switch` component. Recent a11y fixes to the component should have been marked as breaking change, as it changed the markup completely, leading to E2E test failures.

**Comment by with-heart** [comment]
For anyone else that stumbles on this, we had a brief discussion about this on Discord: https://discord.com/channels/660863154703695893/660863154703695896/832230885415845899
