### ISSUE TITLE
Module not found: Can't resolve './dom'

### ISSUE THREAD

**Issue by DiegoMcDipster** [chakra-ui/chakra-ui#3826]
# 🐛 Bug report

when i : npm run dev 
I get the error message 
error - ./node_modules/@chakra-ui/react-utils/dist/esm/index.js:3:0
Module not found: Can't resolve './dom'

## 💥 Steps to reproduce

I was running chakra version : "@chakra-ui/react": "^1.4.2",

The application launched and i was able to do my stuff.  However, when i used a modal I was getting the flushsync issue as reported in #3357 . 

So, i followed the instructions on that issue and updated my version of Chakra to "@chakra-ui/react": "^1.5.1"

## 💻 Link to reproduction
Not sure how to recreate it for you to see.

## 🧐 Expected behavior
I expect no error to occur and the ./dom file to be found

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.5.1       |
| Browser          |       firefox     |
| Operating System |     WSL2       |
| Nodejs | 14.15.4
| Webpack | 5 |
| Nextjs | 10.1.3 |
| React | 17.0.2 |

**Comment by with-heart** [comment]
Hi @DiegoMcDipster! Could you paste your `package.json` file?

**Comment by DiegoMcDipster** [comment]
Hi @with-heart,

Thanks for taking the time to look at this.  As requested :
{
  "name": "firebase-try",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@chakra-ui/react": "^1.5.1",
    "@emotion/react": "^11.1.5",
    "@emotion/styled": "^11.3.0",
    "firebase": "^8.3.2",
    "firebase-admin": "^9.6.0",
    "formik": "^2.2.6",
    "framer-motion": "^4.1.4",
    "moment": "^2.29.1",
    "next": "10.1.3",
    "nookies": "^2.5.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-icons": "^4.2.0",
    "yup": "^0.32.9"
  }
}

**Comment by segunadebayo** [comment]
@DiegoMcDipster, please consider reinstalling your `node_modules`.

**Comment by DiegoMcDipster** [comment]
@segunadebayo  I already tried that. It didn't work. At the moment i rolled it back to version 1.4.2 and i'm living with the flush sync warning.  

I noticed that the directory structure has changed in /node_modules/@chakra-ui/react-utils/dist/esm
and the ./dom.js file has been removed between version 1.4.2 and 1.5.1.  So, are there maybe any upgrade instructions?
or any other advise you can give me?

**Comment by with-heart** [comment]
CodeSandbox with the same versions works fine: https://codesandbox.io/s/competent-wave-jd215?file=/pages/index.js

You'll have to try to recreate your error from there based on what you're doing in your project. It's a guessing game at this point.

**Comment by DiegoMcDipster** [comment]
I managed to get it working!

The solution was to remove the ".next" folder and all of it's contents.
