### ISSUE TITLE
LinkOverlay covering entire body on chrome in a Tr LinkBox on Chrome

### ISSUE THREAD

**Issue by MisterSquishy** [chakra-ui/chakra-ui#3832]
🐛 Bug report
i want a table with rows that link on click. the following code snippet produces a link that covers the entire document body in Chrome, but not in Firefox:
```
import React from "react";
import { Table, Thead, Tr, Th, Td, Tbody, LinkBox, LinkOverlay } from "@chakra-ui/react";

export default function App() {
  return (
    <Table>
      <Thead>
        <Tr>
          <Th>Col</Th>
        </Tr>
      </Thead>
      <Tbody>
        <LinkBox as={Tr}>
          <Td>
            <LinkOverlay href="https://www.google.com">test</LinkOverlay>
          </Td>
        </LinkBox>
      </Tbody>
    </Table>
  );
}
```

![CleanShot 2021-04-15 at 22 11 36](https://user-images.githubusercontent.com/5599894/114961989-e9553f00-9e37-11eb-8f24-f71fd185ba02.gif)

💥 Steps to reproduce
add a `<LinkBox as={Tr}>` as your table rows and add a `LinkOverlay`

💻 Link to reproduction
https://codesandbox.io/s/billowing-sky-myimc?file=/src/app.js

🧐 Expected behavior
only the table row is clickable, not the entire page. note that this works fine on firefox

**Comment by TimKolberger** [comment]
The LinkBox components uses `position: relative` to contain the absolute positioned `LinkOverlay`.
Unfortunately `<Tr />` does not allow `position: relative` -> see https://github.com/w3c/csswg-drafts/issues/1899

There is a hacky workaround by applying `transform: scale(1)` to the tr element:

```jsx
<LinkBox as={Tr} transform="scale(1)">

```

> Please verify if this works in all browsers you need to support!

I am closing this issue, because there is nothing chakra ui can do to fix the web standard.

**Comment by zebapy** [comment]
I can't get the `transform` hack to work in Safari. Is it supposed to, as mentioned above? Otherwise newer chrome and FF support position on `tr` okay.

**Comment by rusakovic** [comment]
> 

Confirm. Not working on Safari

**Comment by KeisukeNagakawa** [comment]
not working on safari, me too

**Comment by olecrivain** [comment]
Same problem for me on IOS, with safari & firefox.
The workaround does not work :s

**Comment by NullSoldier** [comment]
Thanks this was very helpful. I tested it on Safari and it seems to work on current Safari now.
