### ISSUE TITLE
 CSS Property `hyphens` is not supported

### ISSUE THREAD

**Issue by devlargs** [chakra-ui/chakra-ui#3842]
# 🚀 Feature request

> CSS Property `hyphens` is not supported

## 🧱 Problem Statement / Justification

> I stumbled upon a task wherein if a text overflows the parent container width, you need to use hyphens instead of using word break. Then i noticed that hyphens isn't currently supported. 

## ✅ Proposed solution or API

> Add hyphens support (just a suggestion) 😉 not big deal though

## ↩️ Alternatives

> right now the best solution is 
> `style={{ hyphens: "auto" }}`

**Comment by with-heart** [comment]
`hyphens` [barely has browser support outside of English](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens#browser_compatibility) and is still a "Candidate Recommendation" from w3c, so I think at least for now we'll pass!
