### ISSUE TITLE
Create

### ISSUE THREAD

**Issue by jitenderchand1** [chakra-ui/chakra-ui#3845]
# 🐛 Bug report

After upgrading chakra to `1.5.0`. The `createBreakpoints` not creating a array of breakpoints as mentioned in the doc. (https://chakra-ui.com/docs/features/responsive-styles). Which is causing issue. The styled system expected breakpoints to be an array but since it received object it is throwing error.

**Here is the screenshot of error.**
<img width="1096" alt="Screen Shot 2021-04-15 at 9 36 27 AM" src="https://user-images.githubusercontent.com/19687185/115017552-53232680-9ed4-11eb-8e90-a77aaf474e67.png">

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/ancient-tdd-5xwex?file=/src/App.js:69-80

## 🧐 Expected behavior

`createBreakpoints` should create an array of breakpoints

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.50       |
| styled-system/css |  5.1.5   |
| styled-system|  5.1.5   |
| framer-motion|  4.1.4   |
| Browser          |    chrome  89    |
| Operating System |  macos  HS   |

**Comment by segunadebayo** [comment]
Hi @jitenderchand1,

This is an internal implementation, yes `createBreakpoint` no longer returns an array but responsive styles still work as expected.

Please remove `@styled-system/css` and `styled-system` from your dependencies as well. Chakra UI doesn't rely on those anymore.
