### ISSUE TITLE
PopoverTrigger child Button type is undefined

### ISSUE THREAD

**Issue by huijiewei** [chakra-ui/chakra-ui#3859]
# 🐛 Bug report

I use PopoverTrigger in form, but PopoverTrigger's child Button type is undefined
when click Trigger, form submit always trigger

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/hopeful-shamir-fcd4q?file=/src/App.tsx

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.5.2          |
| Browser          |    Chrome 90        |
| Operating System |    macOS 11.2.3        |

**Comment by sampi** [comment]
I experienced something similar and found that if I set the `as` prop as anything but `undefined` then inside `button.tsx` `isButton` will be `false` on the first render and it won't re-render.

_I was using the buttons as is, not wrapped in any special components (like `PopoverTrigger`)_

**Comment by j-dominguezp** [comment]
![image](https://user-images.githubusercontent.com/53125581/115582251-c3e08f00-a296-11eb-8f30-9076f38a3bad.png)

I can confirm this is happening in any Button. I've been having this weird problem where a custom InputPassword component triggers form submit when clicking the hide/reveal button, and it's because of what's described in this issue.

As a workaround I added e.preventDefault() to the onClick event, but in my case is not working well as now I can't submit the form when pressing Enter button.

**Comment by huijiewei** [comment]
I have a temporary workaround， <Button as="span">Bad idea</Button>

:(

**Comment by sampi** [comment]
downgrading to v1.5.1 fixes the issue and `type="button"` gets applied correctly.

```diff
1,5c1,5
< "@chakra-ui/react": "^1.5.2",
< "@chakra-ui/react-utils": "^1.1.1",
< "@chakra-ui/system": "^1.6.3",
< "@chakra-ui/theme": "^1.8.3",
< "@chakra-ui/theme-tools": "^1.1.5",
---
> "@chakra-ui/react": "1.5.1",
> "@chakra-ui/react-utils": "1.1.1",
> "@chakra-ui/system": "1.6.2",
> "@chakra-ui/theme": "1.8.2",
> "@chakra-ui/theme-tools": "1.1.3",
```

**Comment by j-dominguezp** [comment]
> downgrading to v1.5.1 fixes the issue and `type="button"` gets applied correctly.
> 
> ```diff
> 1,5c1,5
> < "@chakra-ui/react": "^1.5.2",
> < "@chakra-ui/react-utils": "^1.1.1",
> < "@chakra-ui/system": "^1.6.3",
> < "@chakra-ui/theme": "^1.8.3",
> < "@chakra-ui/theme-tools": "^1.1.5",
> ---
> > "@chakra-ui/react": "1.5.1",
> > "@chakra-ui/react-utils": "1.1.1",
> > "@chakra-ui/system": "1.6.2",
> > "@chakra-ui/theme": "1.8.2",
> > "@chakra-ui/theme-tools": "1.1.3",
> ```

Yup, did the same, this bug was added here #3732

**Comment by antoniel** [comment]
If anyone isn't working on this, i can if fix it
