### ISSUE TITLE
[AvatarGroup] Request to add event props to AvatarGroup and Avatar component

### ISSUE THREAD

**Issue by apnerve** [chakra-ui/chakra-ui#386]
**Is your feature request related to a problem? Please describe.**
I have currently a requirement where in hovering/clicking on avatars need to either show the name of the person in a tooltip or clicking on the `+3` to show more avatars in a dropdown. This isn't possible using the components in the current state.

**Describe the solution you'd like**
This might be possible if the `AvatarGroup` component starts accepting props like `onAvatarHover`, `onAvatarClick`, and `onMoreClick`

**Describe alternatives you've considered**
[AvatarGroup](https://atlaskit.atlassian.com/packages/core/avatar-group) by atlaskit has these options

**Additional context**
I need a way to show more user avatars on clicking/hovering over more (`+3`). It is not possible at the moment

**Comment by trompx** [comment]
Could this be reopened?
Also, let's say I have a list of 500 users and I want to show max 3. I don't necessarily have requested the 500 users so I cannot render AvatarGroup with the 500 Avatars. But I'd like to force the **+500**, how could I do that?
Being able to set the size in px would be another great feature!
