### ISSUE TITLE
Toast dark theme transparent background

### ISSUE THREAD

**Issue by rossmoody** [chakra-ui/chakra-ui#3861]
# 🐛 Bug report

I think this is a bug as it hurts legibility. I noticed the subtle and accent variants of toasts in dark mode have transparent backgrounds. Should probably have them be a solid color by default?

![image](https://user-images.githubusercontent.com/29072694/115343899-68f94b80-a161-11eb-87dd-286450f4784f.png)

## 💥 Steps to reproduce

1. Go to https://chakra-ui.com/docs/feedback/toast
2. Ensure dark mode is turned on
3. Click on `show subtle-toast`
4. See transparent background

**Comment by antoniel** [comment]
Doesn't look like a bug, but expected behavior, toast component uses Alert component as composed component, Alert theme uses `transparentize` helper on dark mode [here](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/alert.ts#L31).

**Comment by rossmoody** [comment]
Ah, my apologies. Might consider a revision if it's intentional behavior. The transparent background on an Alert makes more sense when you can ensure nothing is behind it but for a floating toast that will very likely appear on top of content, it doesn't seem ideal. Any idea an easy way for me to adjust the background color of the toast inline?

**Comment by antoniel** [comment]
You could try `variant="solid"`, this variant provides a full filled background with opacity:1

**Comment by segunadebayo** [comment]
Thanks for chiming in @antoniel.

You can also opt for rendering your own component @rossmoody in `useToast`. Use the `Alert` component and change the background as needed.

**Comment by dgrcode** [comment]
Hey 👋 

For other people landing here, what I found to be a nice alternative for the default dark theme to avoid the transparency is the following:

```js
import { useColorModeValue } from "@chakra-ui/react";
const toastVariant = useColorModeValue("subtle", "solid");

toast({
  description: "The description shown on the toast",
  status: "error",
  variant: toastVariant,
});
```
