### ISSUE TITLE
Add imports to Formik/Chakra code example in docs

### ISSUE THREAD

**Issue by Nutlope** [chakra-ui/chakra-ui#3866]
# 🚀 Feature request

I'd like to propose adding imports to the [Formik/Chakra example](https://chakra-ui.com/docs/form/form-control#usage-with-form-libraries) code example in the Chakra docs.

## 🧱 Problem Statement / Justification

I spent hours trying to figure out why the [Formik/Chakra example](https://chakra-ui.com/docs/form/form-control#usage-with-form-libraries) in the docs wasn't working and it turns out I needed to import 'Form' and 'Field' from Formik instead of from Chakra UI. I would have never figured this out if Mark from the core team didn't help me out.

Resolving this would make it a lot easier for users to copy/paste the code example from the docs instead of having to worry about imports. This would make for a smoother user experience. 

Smoother user experience => happier users => more word of mouth => more people using Chakra => more people paying for Chakra UI pro :)

## ✅ Proposed solution or API

My proposed solution is to simply add imports to the Formik/Chakra code example.

## 📝 Additional Information

Below is a screenshot of a conversation with someone else who faced the same issue. **By the way, I'd love to implement this myself and make my first contribution to Chakra if the team thinks this is a good idea.**

![image](https://user-images.githubusercontent.com/63742054/115432845-da261680-a1d4-11eb-898b-73222d39398b.png)

**Comment by Nutlope** [comment]
Talking with @with-heart made me realize I ran into this issue because I'm very new to both Formik and Chakra, and that someone who knows either of them decently would have been able to fill in the blanks for this. Feel free to do with this as you wish, if you don't think it's necessary feel tree to close it.

**Comment by segunadebayo** [comment]
This sounds good. Feel free to create a guide in the docs for this @Nutlope

**Comment by Nutlope** [comment]
Sounds good @segunadebayo, I'll write up a guide and send a PR later this week. To confirm, would you also like me to add the import statements in the code example currently in the docs or do you think just linking to the guide I'll write in that section is enough?
