### ISSUE TITLE
`bg=` should map to `background` not `background-color`?

### ISSUE THREAD

**Issue by ianstormtaylor** [chakra-ui/chakra-ui#387]
**Is your feature request related to a problem? Please describe.**

Right now the `bg=` shorthand property seems to map to `background-color`. But this makes it confusing when you want to change a background from a color to a gradient. You might think you can just change:

```
bg="gray.500"
```

To:

```
bg="linear-gradient(...)"
```

But that would result in CSS of:

```css
background-color: linear-gradient(...);
```

Which fails, because it maps to `background-color` instead of `background`.

**Describe the solution you'd like**

Instead of mapping `bg=` to `background-color`, it should map to `background`. I think there's no downside here, since colors can always be passed directly to `background` and work as intended?

**Comment by segunadebayo** [comment]
This also makes sense @ianstormtaylor. We'll look into it.

**Comment by akiarostami** [comment]
Is there any solution in the current format for setting background to something like linear-gradient?

**Comment by segunadebayo** [comment]
Hi @akiarostami, I believe you can use the `bgImage` or `backgroundImage` prop for linear gradients.

**Comment by akiarostami** [comment]
Thank you, it worked!

**Comment by ianstormtaylor** [comment]
Not stale.

**Comment by segunadebayo** [comment]
@ianstormtaylor This has been fixed in the `v1` pre-release. We'll publish `v1` officially soon.

**Comment by segunadebayo** [comment]
@ianstormtaylor This has been fixed in the `v1` pre-release. We'll publish `v1` officially soon.

**Comment by realshegz-github** [comment]
Hi, I've been having issues fixing a linear gradient to my bgImage, any help pls?
