### ISSUE TITLE
MenuButton as Button does not recieve type="button"

### ISSUE THREAD

**Issue by margalit** [chakra-ui/chakra-ui#3871]
# 🐛 Bug report

MenuButton as Button does not recieve type="button", even when passed in as a prop.

## 💥 Steps to reproduce

1. Create Menu with nested MenuButton
2. Add as={Button} to MenuButton
3. Inspect button

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/crazy-microservice-oizpx?file=/src/App.tsx

## 🧐 Expected behavior

MenuButtons rendered with Button receive type="button" or at least access can be set via  prop.

## 🧭 Possible Solution

Haven’t dug into it but we may be able to set the alternative case to true here: https://github.com/chakra-ui/chakra-ui/blob/117f2db20fbc7c261cdf9daa528a708eb191f6d6/packages/button/src/button.tsx#L124

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.5.2      |
| Browser          |     Firefox/Chrome       |
| Operating System |     OSX       |

## 📝 Additional information

This is breaking some of our forms as we render some Menus inside of them. These buttons trigger the submit function on the form when clicked.

**Comment by huijiewei** [comment]
#3859
