### ISSUE TITLE
templateAreas on Grid component not working without additional quotes

### ISSUE THREAD

**Issue by dastasoft** [chakra-ui/chakra-ui#3878]
# 🐛 Bug report

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/ecstatic-butterfly-84g76?file=/pages/index.tsx

## 🧐 Expected behavior

With the component `Grid` I define a `templateAreas` prop: templateAreas="shodai nidaime sandaime yondaime" but if you examine the CSS I get: grid-template-areas: shodai nidaime sandaime yondaime without quotes which is invalid.

If I put templateAreas="'shodai nidaime sandaime yondaime'" is solved but I don't think that's the idea.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.5.2         |
| Browser          |    Firefox and Chrome        |
| Operating System |   Linux Mint 20.1         |

**Comment by segunadebayo** [comment]
Hi @dastasoft,

This is by design in emotion (the css-in-js library we use).

It's the same issue as `content:` in the `:before` and `:after`. Kindly wrap in an extra quote 🙂

**Comment by dastasoft** [comment]
Oh I see, thank you and sorry for the misunderstanding :(
