### ISSUE TITLE
consolidate `rounded` vs `borderRadius` duplication?

### ISSUE THREAD

**Issue by ianstormtaylor** [chakra-ui/chakra-ui#388]
**Is your feature request related to a problem? Please describe.**

Right now there's a confusing duplication in how to set a border radius. It seems like you can make use of:

```
rounded="md"
roundedLeft="md"
roundedTop="md"
roundedTopLeft="md"
```

Or:

```
borderRadius="md"
```

If you have an existing `borderRadius=` prop you might except (given that you know CSS) that you could change it to `borderTopRadius`, but you can't.

The `rounded*` variants aren't intuitive because they don't map to existing CSS properties like most props do. Why not change them to use the exact CSS mappings instead to reduce complexity?

**Describe the solution you'd like**

```
borderRadius="md"
borderTopRadius="md"
borderTopLeftRadius="md"
...
```

There's only an ever-so-slight increase in typing, but at the benefit of mapping directly to CSS like everything else.

**Comment by segunadebayo** [comment]
Hi @ianstormtaylor,

I agree! We spotted this yesterday when reviewing all the style props. I think it will be updated to `topLeftRadius` instead of `borderTopLeftRadius`. I believe it's a bit more intuitive and closer to CSS.

Thanks for this suggestion.

PS: We're adding this fix now to the dev-ts branch and will come with the next release. So I'm going to close it out.

**Comment by ianstormtaylor** [comment]
Thanks @segunadebayo that's great to hear!

Just in case the above was clear, the `borderTopLeftRadius` name I mentioned was because the CSS property for it is actually [`border-top-left-radius`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-top-left-radius).

(The shorter/double `borderTopRadius` variants don't exist in CSS it seems, but so often just changing the two corners on one full side is what's needed so it seems like it would be useful to have them in addition as `borderTopRadius`.)

**Comment by segunadebayo** [comment]
@ianstormtaylor. I agree!

I've implemented your suggestions because I thought it was more intuitive. Now we'll have these props:

```jsx
borderRadius="md"
borderTopRadius="md"
borderTopLeftRadius="md"
```

I might get rid of the `rounded-*` props to keep the overall style API concise.
