### ISSUE TITLE
Modal in @chakra-ui/react v1.5.2 not working

### ISSUE THREAD

**Issue by shashankGS10** [chakra-ui/chakra-ui#3880]
# 🐛 Bug report

I tried to replicate the example of Modal which has been provided in the documentation(https://chakra-ui.com/docs/overlay/modal) but failed.

## 💥 Steps to reproduce

1. Import all the components required to create a modal
2. Copy the example code and paste it inside the base component(<App />)
3. Link: https://chakra-ui.com/docs/overlay/modal
4. You'd be able to see the error in the console

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/modaldemochakraui-fx1hy?file=/src/ModalDemo.js

## 🌍 System information

| Software         | Version(s) |
| ---------------- | -------- |
| Chakra UI        |      1.5.2      |
| Browser           |    Chrome  |
| OS                   |  MacOS      |
| Code Editor    |  VS Code   |

**Comment by with-heart** [comment]
Hi @shashankGS10! `Lorem` isn't a Chakra component, it's an external library that generates fake text that we use in the documentation. Removing that resolves the issue: <https://codesandbox.io/s/modaldemochakraui-forked-tm6tr?file=/src/ModalDemo.js>
