### ISSUE TITLE
LayerStyles not rendered on Container + TextStyle not rendered on Textarea

### ISSUE THREAD

**Issue by callumflack** [chakra-ui/chakra-ui#3883]
# 🐛 Bug report

## 💥 Steps to reproduce

1. View the [codesandbox reproduction](https://codesandbox.io/s/competent-colden-j6ucp?file=/pages/_app.tsx)
2. Note that the layerStyles applied to the Container are not rendered
3. Note that the textStyles applied to the Textarea are not rendered

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/competent-colden-j6ucp?file=/pages/_app.tsx

## 🧐 Expected behavior

Both styles should be rendered and previously (1.0) they have.

**Comment by 88ta** [comment]
Hello! I'd like to tackle it.

**Comment by 88ta** [comment]
Hi!, I'd like to tackle it.

**Comment by spidertwin2** [comment]
Also, layerStyle does not work with `<Button>`.

Link to [Sandbox](https://codesandbox.io/s/clever-pine-4c57b?file=/src/index.tsx).

:seedling:
