### ISSUE TITLE
textStyles defined inside extendTheme aren’t applied correctly

### ISSUE THREAD

**Issue by rastersysteme** [chakra-ui/chakra-ui#3884]
# 🐛 Bug report

Styles defined via `textStyles` are not applied correctly although they’re set within `extendTheme`.

## 💥 Steps to reproduce

1. Go to my [CodeSandbox](https://codesandbox.io/s/textstyle-problems-ibu9h?file=/src/App.tsx:176-186)
2. Inspect Heading, Button, Text and the body element with the developer tools inside the browser
3. Have a look at the styles set by Chakra UI and compare them

### textStyles which should be applied
![image](https://user-images.githubusercontent.com/1895414/115682943-3b292800-a356-11eb-8a21-63842980e65e.png)

### body styles
![image](https://user-images.githubusercontent.com/1895414/115683692-ff429280-a356-11eb-9fb9-596cca3d8549.png)
✅ `font-size` from `textStyles` is used.
💥 `font-family` and `line-height` aren’t applied by `textStyles`.

### Heading styles
![image](https://user-images.githubusercontent.com/1895414/115683106-6875d600-a356-11eb-9cd6-61d71033df97.png)
💥 Neither `font-family` nor `font-size` and `line-height` are applied by `textStyles`.

### Button styles
![image](https://user-images.githubusercontent.com/1895414/115684300-898af680-a357-11eb-8203-7cb3f72c1268.png)
✅ `font-family` from `textStyles` is used.
💥 `font-size` and `line-height` aren’t applied by `textStyles`.

### Text styles
![image](https://user-images.githubusercontent.com/1895414/115684530-b9d29500-a357-11eb-8a37-349061aded17.png)
✅ All styles set by `textStyles` are used.  

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/textstyle-problems-ibu9h?file=/src/App.tsx:176-186

## 🧐 Expected behavior

Styles like `font-family`, `font-size` and `line-height` defined in `textStyles` should be applied when passed through `extendTheme` according to [this comment](https://github.com/chakra-ui/chakra-ui/issues/3658#issuecomment-807299129). This behaviour should be consistent and reliable when used on all elements (even `<body />`).

## 🧭 Possible Solution

–

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.5.2       |
| Browser          |      Chrome, Firefox      |
| Operating System |      macOS      |

## 📝 Additional information

–

**Comment by tbaschim** [comment]
Bump

**Comment by bangngo1508** [comment]
I am facing the same issue with the defaultProps

![image](https://user-images.githubusercontent.com/85552164/121157545-dc6f2d80-c873-11eb-90cc-ac55ea77c58c.png)

![image](https://user-images.githubusercontent.com/85552164/121157497-d0836b80-c873-11eb-8a6e-81199dd80e70.png)

**Comment by rastersysteme** [comment]
Tested it with the latest version 1.6.3, still the same problem. Sadly, at the moment `textStyles` aren’t usable.

**Comment by crimson-med** [comment]
Any updates on this? 
I'm trying to customize StatHelperText and it is working on old version 1.1.2 of chakra but the recent 1.6.3 not working.

```
<StatHelpText textStyle="h1" >
    <StatArrow type="increase" /> 10%
</StatHelpText>
```

Variant with StatHelpText are also not working

**Comment by rastersysteme** [comment]
Bump – I really would love to see a solution for this.

**Comment by stephane-ruhlmann** [comment]
Same, can't manage to have `fontSize` defined in `textStyle` work with `<Heading/>` since I updated to 1.6.5. Worked fine with version 1.1.6.

[Here's a narrowed down example in CodeSandbox
](https://codesandbox.io/s/condescending-frost-zw8l4?file=/src/App.tsx:114-719)

`textStyles` are defined as:
```javascript
const customTheme = extendTheme({
  textStyles: {
    h1: {
      fontSize: "32px",
      color: "blue",
    },
    h2: {
      fontSize: "24px",
      color: "red",
    },
    h3: {
      fontSize: "16px",
      color: "orange",
    }
  }
});
```

And used this way:

```javascript
<VStack spacing="8px">
      <Heading as="h1" textStyle="h1">
        Heading 1
      </Heading>
      <Heading as="h2" textStyle="h2">
        Heading 2
      </Heading>
      <Heading as="h3" textStyle="h3">
        Heading 3
      </Heading>
</VStack>
```

**Comment by stephane-ruhlmann** [comment]
After some further investigation it looks like we should be using theme `variants` for components such as `<Heading/>` as suggested there https://github.com/chakra-ui/chakra-ui/issues/3501#issuecomment-803610656

**Comment by rastersysteme** [comment]
> After some further investigation it looks like we should be using theme `variants` for components such as `<Heading/>` as suggested there [#3501 (comment)](https://github.com/chakra-ui/chakra-ui/issues/3501#issuecomment-803610656)

Sadly this doesn’t tackle the base problem – just have a look for example at my initial sandbox where I applied `textStyle` on `body`. And even inside the variants it won’t work.

To cite the [documentation](https://chakra-ui.com/docs/features/text-and-layer-styles#text-styles):
> The text styles functionality in Chakra makes it easy to repeatably apply a collection of text properties (like line height and size) to any component.

So as described I just want to be able to apply my pre-definied `textStyle` definitions (which are all saved in one single file) to any component as I did prior to V1.4. This isn’t possible at the moment.

**Comment by stephane-ruhlmann** [comment]
> > After some further investigation it looks like we should be using theme `variants` for components such as `<Heading/>` as suggested there [#3501 (comment)](https://github.com/chakra-ui/chakra-ui/issues/3501#issuecomment-803610656)
> 
> Sadly this doesn’t tackle the base problem – just have a look for example at my initial sandbox where I applied `textStyle` on `body`. And even inside the variants it won’t work.
> 
> To cite the [documentation](https://chakra-ui.com/docs/features/text-and-layer-styles#text-styles):
> 
> > The text styles functionality in Chakra makes it easy to repeatably apply a collection of text properties (like line height and size) to any component.
> 
> So as described I just want to be able to apply my pre-definied `textStyle` definitions (which are all saved in one single file) to any component as I did prior to V1.4. This isn’t possible at the moment.

Yes, this is definitely a bug as it should work as stated in the documentation.
The suggestion is a workaround that might not work for everywhere but as it appears to be a complex issue on chakra's side that's all we can do for now.
