### ISSUE TITLE
Add srcSet attribute to the chakra image component

### ISSUE THREAD

**Issue by MWFIAE** [chakra-ui/chakra-ui#3886]
# 🚀 Feature request

Add the srcSet attribute to the chakra image component.

## 🧱 Problem Statement / Justification

I'm currently trying to reduce loading times for my website and therefore I tried to use the srcSet attribute of images to only load the version corresponding to the screen resolution of the user.
While it works for normal images the srcSet attribute isn't available using the chakra image component.

## ✅ Proposed solution or API

Add the srcSet attribute to the chakra image component and treat it the same way src is currently treated.

## 📝 Additional Information

https://web.dev/serve-responsive-images/#serve-multiple-image-versions

**Comment by segunadebayo** [comment]
Hi @MWFIAE,

As far as I can tell, the Image component currently supports the `srcSet` prop. You can also use the `Img` component which has the same interface as `<img/>`

If you can provide a reproduction, we'll look into and re-open once we confirm.

Cheers

**Comment by MWFIAE** [comment]
Ah just realized I was in the wrong repo anyways. Will reopen in the vue repo and supply more information.
