### ISSUE TITLE
docs: copy icons to clipboard 

### ISSUE THREAD

**Issue by antoniel** [chakra-ui/chakra-ui#3889]
# 🚀 Feature request

Implement copy to clipboard behavior on [/docs/media-and-icons/icon#all-icons](https://chakra-ui.com/docs/media-and-icons/icon#all-icons) docs section 

## 🧱 Problem Statement / Justification

It's an improvement in user experience. The component that displays each icon looks like a button, so an interaction to copy to the clipboard would be nice.
As a user, when I'm searching by a chakra icon on [/docs/media-and-icons/icon#all-icons](https://chakra-ui.com/docs/media-and-icons/icon#all-icons) I should be able to:
- Copy to clipboard the icon's import code
- Copy to clipboard the icon name

I'm not sure about what is the best approach.

## 📝 Additional Information

A reference for this feature is [systemuicons](https://systemuicons.com/) where user is able to copy all SVG code by one click.

**Comment by joaorodrs** [comment]
> - Copy to clipboard the icon's import code

I'm trying to work on this issue and I'm not sure if the feature above would be essential based on my understanding. When the user is getting an Icon from the docs, they usually already have an import that contains all of his icons.
```
import { FooIcon, BarIcon, ... } from "@chakra-ui/icons"
```
And if the user copied the icon's import, it would be something like `import { CopiedIcon } from "@chakra-ui/icons"`

My suggestion (and what I'm working on) is allow the user to copy the entire icon tag `<CopiedIcon />`, but please let me know if I'm getting it wrong

**Comment by antoniel** [comment]
@joaorodrs thanks for your comment, Looking to use a case where a user needs to import many icons, is more efficient just to copy icon name, so that way it's enough paste on jsx `<Copied Icon/>` and at import list. So just copy Icon name is nice
