### ISSUE TITLE
1.5.2 Form in drawer calls onSubmit when a button attached to a disclosure is clicked

### ISSUE THREAD

**Issue by dusty** [chakra-ui/chakra-ui#3890]
# 🐛 Bug report

We have a drawer with a form that has a submit button and another button that calls a disclosure.  In chakra 1.5.1, this worked properly, only the submit button was able to trigger form submission.

In chakra 1.5.2, that other button triggers form submission.  I tried to narrow this down to the smallest repro.  See the codesandbox for examples.  They are running the same code in both versions.

Interestingly the form submission does not seem to happen if the button onClick is attached to a regular function.  It seems the disclosure (from useDisclosure) has to do with this.

### 1.5.2
1. Go to https://codesandbox.io/s/twilight-hill-g7pni?file=/src/index.tsx
2. Open the console
3. Click on the Open button
4. Click on the Disclosure button
5. Notice that the form submits, which also closes the drawer

![2021-04-22 11 52 34](https://user-images.githubusercontent.com/792/115770516-aa584980-a361-11eb-902c-d7a817f61ec7.gif)

### 1.5.1
1. Go to https://codesandbox.io/s/fragrant-wave-vf9xz?file=/src/index.tsx:570-620
2. Open the console
3. Click the Open button
4. Click on the Disclosure button
5. Notice the form does not submit

![2021-04-22 11 52 50](https://user-images.githubusercontent.com/792/115770561-b93efc00-a361-11eb-8c37-5a0cbb3558b4.gif)

## 🧐 Expected behavior

I would not expect that the button would submit the form

**Comment by with-heart** [comment]
A fix for this was merged earlier today in #3859. Will be published soon.

See other related issues: #3885, #3871, #3859
