### ISSUE TITLE
Transparent logo not legible in <Avatar>

### ISSUE THREAD

**Issue by delanebob** [chakra-ui/chakra-ui#3891]
# 🐛 Bug report

We use the `<Avatar>` component for customers to add their logo. If we use the name field and have a transparent logo, the background colour from the name is behind and in some cases the logo isn't legible.

## 💥 Steps to reproduce

1. Create a `<Avatar>` with a transparent image.
2. Add name field

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/eager-dust-i83y7

## 🧐 Expected behavior

Should be transparent to inherit the background behind, or we should be able to pass in some sort of background.

## 🧭 Possible Solution

One of the below could be a solution:
- Default to white/black depending on colour mode. (might not be as flexible).
- Have the background colour transparent when you have a successful image.
- Be able to set the background for a successful image.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.5.2  |
| Browser          | Safari/Chrome |
| Operating System | Mac OS |

## 📝 Additional information

<img width="782" alt="Screenshot 2021-04-22 at 21 21 24" src="https://user-images.githubusercontent.com/5358403/115785992-21203180-a3b8-11eb-9dfc-60dd0ad8cf11.png">

**Comment by segunadebayo** [comment]
Hi @delanebob,

The generated background color is our system's default based on the name passed. You can override it by passing the `bg` prop

```jsx
 <Avatar
        bg="white"
        name="Ryan Florence"
        src="https://cdn.logo.com/hotlink-ok/logo-social-sq.png"
      />
```

**Comment by delanebob** [comment]
Hi @segunadebayo,

If I pass in a background though, it will make the background always be that colour. So I need to be able to pass a background when the image is successful.

Otherwise use the one generated by chakra. If it's not setup in the Avatar component, it means I've todo a check manually outside of the avatar component to see if the image is successful before setting the background.
