### ISSUE TITLE
Checkbox size prop doesn't work

### ISSUE THREAD

**Issue by AlexanderMelox** [chakra-ui/chakra-ui#3894]
# 🐛 Bug report

When using the `Checkbox` component with a size prop of `lg` I noticed I wasn't getting the right sizes and Medium is the largest of all of them. 

![Screen Shot 2021-04-23 at 9 15 03 AM](https://user-images.githubusercontent.com/12755042/115876501-65d9b600-a414-11eb-8c44-2289a85c0754.png)

![Screen Shot 2021-04-23 at 9 15 21 AM](https://user-images.githubusercontent.com/12755042/115876534-6f631e00-a414-11eb-9507-12862f249733.png)

## 💥 Steps to reproduce

1. Go to `pages/home.tsx`
2. View the checkbox code
3. View in the window and notice that the sizes are off.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/practical-austin-l52bv?file=/src/pages/Home.tsx

## 🧐 Expected behavior

I expected the checkbox sizes to work as usual

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.5.2       |
| Browser          |    Google chrome        |
| Operating System |      Mac OS      |

**Comment by segunadebayo** [comment]
Hi @AlexanderMelox,

If you inspect the code for the checkbox, you'll see that `<Checkbox size=lg />`  applies `fontSizes.lg` for the label. I see you have a custom fontSizes object, and you defined it as:

```js
 fontSizes: {
    sm: '0.875rem',
    md: '1.6rem',
    lg: '1.25rem',
  },
```

`md=1.6rem` is larger `lg=1.25rem` hence the reason it looks like the medium is larger than large.

Kindly update your theme definition for `lg`

**Comment by AlexanderMelox** [comment]
Ohh thanks so much! I didn't realize it will use the font size!
