### ISSUE TITLE
Multiple dark/light theme

### ISSUE THREAD

**Issue by alirezavlz** [chakra-ui/chakra-ui#3896]
Hello Everyone, 

I'm trying to build an application, It supports darks/lights themes (like Slacks theme), the base is dark or light but some backgrounds or colours are different.
I migrate to chakra v1  recentlyI found it's kind of hard to do since it has different API for managing the theme. So my first issue is when you define baseStyle for a component you can only access to colorMode which is good but not enough, I'm looking for a way to pass a "sub theme name", Imagine we have these themes, 

![image](https://user-images.githubusercontent.com/53314423/115520689-b58c7600-a28a-11eb-9a0c-1de812639121.png)

I need to define a heading for each,
```js
import { extendTheme } from '@chakra-ui/react';

const config = {
  initialColorMode: 'dark',
  useSystemColorMode: false,
};

const getBgBasedOnTheme = ({subThemeNameFromArgs}) => {
   switch (subThemeNameFromArgs) {
     case 'subDarkTheme1':
     case: 'subDarkTheme2'
     case: 'subDarkTheme3'
   }
};

const components = {
  HeaderApp: {
    baseStyle: ({ colorMode, ...rest }) => {
      console.log(colorMode, rest); // returns dark or light
      // rest has also useless properties
      return {
         bg: getBgBasedOnTheme(rest)
      };
    }
  }
};

export const theme = extendTheme({
  config,
  components
});
```

I can handle this with store management tricks and take these logic to a context or something but I'm sure there should be a cleaner and performant way.

In the past I solved the issue with having different theme objects like this:
```js
export const theme = {
  dark,
  light
};


const GlobalProviders = ({ children }) => {
 // some states to change the theme
  return (
    <ChakraProvider theme={theme.dark}>
      {children}
    </ChakraProvider>
  );
};
```
But the issue was you needed to write css for each component. I like the new approach that chakra has now.
Thanks in advance

_Originally posted by @alirezavlz in https://github.com/chakra-ui/chakra-ui/discussions/3873_

**Comment by TimKolberger** [comment]
See discussion https://github.com/chakra-ui/chakra-ui/discussions/3873
