### ISSUE TITLE
usePopoverContext is no longer exported

### ISSUE THREAD

**Issue by AJFunk** [chakra-ui/chakra-ui#3899]
# 🐛 Bug report

I am attempting to upgrade from v1.2.1 to v1.5.2 and noticed that `usePopoverContext` is no longer exported, so I cannot use it to render a custom PopoverTriggerArrow.

My implementation looks something like:
```
export const PopoverTriggerArrow = forwardRef(function PopoverTriggerArrow(
  props: StyledComponentProps<>,
  ref
) {
  const { isOpen } = usePopoverContext();
  return (
    <Box as="span" ref={ref} {...props}>
      <Icon
        name={`faAngle${isOpen ? 'Up' : 'Down'}`}
        size="medium"
        color="inherit"
      />
    </Box>
  );
});
```

and this component is always a child of `PopoverTrigger` so it has access to the popover context.

I have attempted to solve this by instead using the `aria-expanded` prop that is passed down from `PopoverTrigger`, but the implementation quickly becomes ugly and prone to bugs.

Looks like this was caused by https://github.com/chakra-ui/chakra-ui/pull/3733/files#diff-90c4d042a18f8ae178e87611b561c7b86ddd6029b77d35b98b30f153dbe2a1f6L48

## 💥 Steps to reproduce

`import { usePopoverContext } from '@chakra-ui/react';` returns `undefined`

## 🧐 Expected behavior

`usePopoverContext` should be exported

## 🧭 Possible Solution

Revert this change so it is exported

**Comment by joaorodrs** [comment]
> I am attempting to upgrade from v1.2.1 to v1.5.2 and noticed that `usePopoverContext` is no longer exported, so I cannot use it to render a custom PopoverTriggerArrow.

https://github.com/chakra-ui/chakra-ui/pull/3906#pullrequestreview-644036349
This may be relevant
