### ISSUE TITLE
allow to pass addEventListener options into NumberInput stepper

### ISSUE THREAD

**Issue by aboveyunhai** [chakra-ui/chakra-ui#3900]
# 🚀 Feature request

It seems like all `NumberInput` has the passive warning because `{ passive: false/true }` is not set.
https://chakra-ui.com/docs/form/number-input#setting-a-minimum-and-maximum-value

## 🧱 Problem Statement / Justification

when I click the `NumberInput`  `step button`, I will see the following warning.
![image](https://user-images.githubusercontent.com/35160613/115925291-e74e3a00-a44e-11eb-83db-e8da8f210f1f.png)

## ✅ Proposed solution or API

Provide a way to allow user to pass explicit options into the `addEventListener`

## ↩️ Alternatives

> N/A

## 📝 Additional Information

> N/A

**Comment by segunadebayo** [comment]
Hi @aboveyunhai,

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
