### ISSUE TITLE
[Docs]: Add section navigation on the right side for docs

### ISSUE THREAD

**Issue by saisandeepvaddi** [chakra-ui/chakra-ui#3901]
First of all, Amazing library. Probably best React component library I've seen these days. Great work 👏🏽 

# 🚀 Feature request

Please add a right side navigation in docs for sub-sections of a page.

## 🧱 Problem Statement / Justification

If I have to find a section in a page, I have to keep scrolling up/down searching for a section. For example, In [https://chakra-ui.com/docs/form/button](https://chakra-ui.com/docs/form/button) page, navigation will be easier if it shows links on the right side for Usage, Button Sizes, .... and other sections. It'll help quickly go back to what I'm looking for. Something like [https://ant.design/components/button](https://ant.design/components/button/) has

## ✅ Proposed solution or API

I believe all sections on each doc page already have `#section-name` which we can use in a `href` and build a nav list with links. Extra features may include a scrollspy.

Thank you

**Comment by jamesaucode** [comment]
This seems like an interesting task, I am willing to give it a try :smile:

**Comment by ahmed-28** [comment]
seems like a good suggestion. It really saves time.@jamesaucode what component are you working on? I'll take one component and try to do for that.

**Comment by saisandeepvaddi** [comment]
Awesome work @jamesaucode  and Chakra team. 👏🏽 👏🏽 👏🏽  . Didn't expect this to be finished and deployed this fast. 💯
