### ISSUE TITLE
[Editable] onEdit not working

### ISSUE THREAD

**Issue by emersonlaurentino** [chakra-ui/chakra-ui#391]
**Describe the bug**
The prop `onEdit` is not passed to `Editable`.

**Expected Behavior**
Callback invoked once the user enters edit mode.

**Comment by segunadebayo** [comment]
Hi @emersonlaurentino, 

Yes, I just caught this bug and fixed it. Fixes will be shipped in the next release. Thanks

**Comment by segunadebayo** [comment]
I just fixed this and will release a patch in a bit.
