### ISSUE TITLE
The Slider's OnChangeStart prop does not get called

### ISSUE THREAD

**Issue by nollidnosnhoj** [chakra-ui/chakra-ui#3919]
# 🐛 Bug report

I do not know if this is intentional, but when I add a function to the onChangeStart prop of the slider component, it does not get called when the user starts dragging the slider handle (according to the docs). 

## 💥 Steps to reproduce

1. Add a slider component that contains a value and onChangeStart property (and any other required props). 
2. To see the issue, you could add a console.log() into the onChangeStart function. 
3. When you start dragging, you should not see any logging in the console when you start dragging the slider handle.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/confident-jackson-zlg17?file=/src/App.tsx

Just start dragging the slider, and you'll see that the handle change start counter will not change.

## 🧐 Expected behavior

The expected behavior is that the onChangeStart function should get called when the user starts dragging the slider handle.

## 🧭 Possible Solution

I tried looking at the source code, but unfortunately I could not understand the usePanGesture hook.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.6.0       |
| Browser          |     Edge (Chromium)       |
| Operating System |      Windows 10      |

## 📝 Additional information

I do not know if the onChangeStart function is intended to work this way.

**Comment by j-dominguezp** [comment]
Seems like what's happening in #3860

**Comment by segunadebayo** [comment]
Yes, it's related. I just pushed a fix for this!

I'll check the other issue @j-dominguezp

**Comment by j-dominguezp** [comment]
Thanks @segunadebayo !
