### ISSUE TITLE
Typescript isn't allowing values that should be provided by the default theme.

### ISSUE THREAD

**Issue by AlexanderProd** [chakra-ui/chakra-ui#392]
**Describe the bug**
Typescript doesn't allow any other zIndex values than shown. 

<img width="567" alt="image" src="https://user-images.githubusercontent.com/3080903/74180598-20cac900-4c40-11ea-9b27-a683904476a4.png">

I've added all those values for zIndex in my theme manually, even though they should be default but it's still not being picked up by typescript. I'm using VSCode as editor.

```
export const theme = {
  ...chakraTheme,
  zIndices: {
    ...chakraTheme.zIndices,
    hide: -1,
    auto: 'auto',
    base: 0,
    docked: 10,
    dropdown: 1000,
    sticky: 1100,
    banner: 1200,
    overlay: 1300,
    modal: 1400,
    popover: 1500,
    skipLink: 1600,
    toast: 1700,
    tooltip: 1800,
  },
};
```

The size prop for a heading also doesn't allow all the values available in the default theme.

I've already found error report #16 but I can't figure out why the error still persists. I'm using chakra-ui with NextJS.

**Desktop (please complete the following information):**
 - OS: macOS
 - Chakra-UI Version 0.5.2

**VSCode version** 
Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:33.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

**Comment by segunadebayo** [comment]
Hi, @AlexanderProd,

We're aware of this scenario and we're looking into it. This issue will be closed as all TypeScript related issues are logged here: #205.

You don't need to add it there, I'll go over it before the next release.

Thanks
