### ISSUE TITLE
The return type of `extendTheme` is `any`

### ISSUE THREAD

**Issue by DrGor** [chakra-ui/chakra-ui#3920]
# 🐛 Bug report
The return type of `extendTheme` is now `any`. Possible regression of https://github.com/chakra-ui/chakra-ui/issues/3101

## 💥 Steps to reproduce

1. Go to `node_modules/@chakra-ui/react/dist/types/extend-theme.d.ts`
2. Check return type of `extendTheme`

## 💻 Link to reproduction
https://codesandbox.io/s/crazy-mcclintock-s7pji?file=/src/App.tsx

## 🧐 Expected behavior
A return type that reflects the extended theme.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.6.0          |
| Browser          |       any     |
| Operating System |      any      |

**Comment by with-heart** [comment]
Seems to be typed here: https://codesandbox.io/s/distracted-sea-yuqhn?file=/src/App.tsx:102-132

Any way you could share your `theme`? I'm wondering if there's something in it that is confusing the compiler.

**Comment by segunadebayo** [comment]
This seems to be typed for me as well.

Consider reinstalling node_modules or restart TS server (if using VSCode).

We'll re-open if we can reproduce this.

**Comment by DrGor** [comment]
@with-heart 
You're not using the latest version of `chakra-ui/react` in CodeSandbox.

Try this link:
https://codesandbox.io/s/crazy-mcclintock-s7pji?file=/src/App.tsx

Very easy to replicate.

**Comment by hwhmeikle** [comment]
I'm also having this issue in 1.6.0

**Comment by dalhaan** [comment]
I am having the same issue.

**Comment by Joaoviana** [comment]
Having the same issue in 1.6.0

**Comment by with-heart** [comment]
Upon further investigation, the problem is that `extendTheme` relies on `pipe`, which is not generic and returns `any`. Need to determine how to properly type the `pipe` function in order to construct the correct types, but for the time being, we should guarantee that `extendTheme` at least returns the default theme type.
