### ISSUE TITLE
[useClipboard] Copies rich text with dark background color instead of plaintext

### ISSUE THREAD

**Issue by feross** [chakra-ui/chakra-ui#3921]
# 🐛 Bug report

`useClipboard` copies rich text with dark background color instead of plaintext

## 💥 Steps to reproduce

1. Go to https://chakra-ui.com/docs/hooks/use-clipboard
2. Click on 'Copy' in the first usage example
3. Go to a rich text window, e.g. Gmail, and paste.
4. Notice the dark background behind the text.
 
![Screen Shot 2021-04-26 at 10 02 12 PM](https://user-images.githubusercontent.com/121766/116187789-11b42780-a6db-11eb-883d-426db4197c54.png)

## 💻 Link to reproduction

See the code for the docs website. Specifically, the code for this page: https://chakra-ui.com/docs/hooks/use-clipboard

## 🧐 Expected behavior

Copied text should be plain text with no formatting.

## 🧭 Possible Solution

Consider using [`clipboard-copy`](https://github.com/feross/clipboard-copy). Unlike other implementations, text copied with clipboard-copy is clean and unstyled. Copied text will not inherit HTML/CSS styling like the page's background color.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.6.0           |
| Browser          |     Chrome latest      |
| Operating System |    macOS latest        |

**Comment by santialbo** [comment]
Note: You also need to have dark mode activated for this to happen (this where the background color is coming from).
Note: It works fine on Firefox
This is the clipboardData from Chrome:
```
text/html
<meta charset='utf-8'><span style="color: rgb(45, 55, 72); font-family: Inter, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Hello world</span> debugger eval code:1:84

text/plain
Hello world
```

**Comment by segunadebayo** [comment]
Hi @feross,

You can pass `options` to the `useClipboard` hook.

```jsx
  const { hasCopied, onCopy } = useClipboard(value,  { format: "text/plain" } )
```

We'll consider making this the default value in the future.

**Comment by feross** [comment]
@segunadebayo Amazing, thanks!

**Comment by cristobalcl** [comment]
> const { hasCopied, onCopy } = useClipboard(value, { format: "text/plain" } )

This should be in the documentation. I've been wasting hours with this issue.

Thanks @segunadebayo !
