### ISSUE TITLE
[Menu] MenuOptionGroups with closeOnSelect={true} do not close on select

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#3923]
# 🐛 Bug report

Passing `closeOnSelect` or `closeOnSelect={true}` explicitly does not work on Menu option groups. It works fine in other scenarios (without option groups).

## 💥 Steps to reproduce

- Go to https://chakra-ui.com/docs/overlay/menu#menu-option-groups
- replace `<Menu closeOnSelect={false}>` with `<Menu closeOnSelect={true}>` or its shorthand `<Menu closeOnSelect>`
- clicking any MenuItemOption should now close on select, but doesnt

**Comment by segunadebayo** [comment]
Good catch @ljosberinn!

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
