### ISSUE TITLE
Receive a function in defaultProps when extending components on theme

### ISSUE THREAD

**Issue by goncy** [chakra-ui/chakra-ui#3926]
# 🚀 Feature request

It would be nice to optionally receive a function that has access to colorMode and other properties when setting defaultProps on theme

## 🧱 Problem Statement / Justification

I tried to set a custom trackColor to CircularProgress based on the current colorMode and realized its not possible from the theme

## ✅ Proposed solution or API

```js
extendTheme({
  components: {
    CircularProgress: {
      defaultProps: (props) => ({
        trackColor: mode("gray.100", "alpha.300")(props),
      })
    },
  },
})
```

## ↩️ Alternatives

I'm currently using the useColorMode hook, still a good solution

Thanks!

**Comment by segunadebayo** [comment]
Hi @goncy,

This sounds interesting and I gave this some thought. We won't be adding support for this considering some ideas we have in mind for next major of Chakra.

**Comment by goncy** [comment]
> Hi @goncy,
> 
> This sounds interesting and I gave this some thought. We won't be adding support for this considering some ideas we have in mind for the next major of Chakra.
> 
> Thanks for understanding

Thanks @segunadebayo ! Is there any link around to see this roadmap or proposals? I would really like to help on what is needed 🙌
