### ISSUE TITLE
Checkbox default background colour

### ISSUE THREAD

**Issue by charliemday** [chakra-ui/chakra-ui#3928]
# 🚀 Feature request

Add background colour to unchecked Checkbox 

## 🧱 Problem Statement / Justification

From the docs there doesn't seem to be any functionality to alter the background colour of an unchecked Checkbox which means if you've got a Checkbox against specific background colours they don't show up

Sandbox Example: https://codesandbox.io/s/zealous-pine-jgv7n?file=/src/index.js 

## ✅ Proposed solution or API

```
<Checkbox defaultBgColor="white" />
```

**Comment by la55u** [comment]
you can set the background color through theme:
https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/checkbox.ts

**Comment by charliemday** [comment]
> you can set the background color through theme:
> https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/checkbox.ts

As far as I can tell you can only target the background of the whole Checkbox component (children included), not the specific unchecked box - this seems to remain transparent unless I'm missing something

**Comment by la55u** [comment]
> 
> As far as I can tell you can only target the background of the whole Checkbox component (children included), not the specific unchecked box - this seems to remain transparent unless I'm missing something

https://codesandbox.io/s/zen-mcclintock-trpzu?file=/src/index.js:205-380

**Comment by barrymichaeldoyle** [comment]
There should be a way to update this without using the theme 😞 

Because I have a component where a color will be passed to it and those colors aren't always in my theme file.

**Comment by BlockJayn** [comment]
> There should be a way to update this without using the theme 😞
> 
> Because I have a component where a color will be passed to it and those colors aren't always in my theme file.

I just encountered exactly the same problem. Not being able to simply change the color of the inactive checkbox without adding a theme is more than disturbing....

**Comment by joduplessis** [comment]
A hacky way to accomplish this would be to override the CSS variables directly.

```
<Checkbox style={{ '--chakra-colors-blue-500': '#F7FAFC' }}>Please check this box</Checkbox>
```

Very non-ideal.
