### ISSUE TITLE
Add ability to remove default sizes/variants/colorSchemes

### ISSUE THREAD

**Issue by kculmback** [chakra-ui/chakra-ui#3931]
# 🚀  Feature request

Add the ability to remove the a default size, variant, and/or color scheme for a given component. For example, removing the ability to specify `xs` as a `size` for the `Button` component.

If there is a method to do this already, I can close this issue. However, I could find nothing in the docs that looked to provide this functionality.

## 🧱  Problem Statement / Justification

Our design system has very specific size, color, and variants for buttons (and other components). We would like the ability to update Chakra to adhere to that design system and limit the available options for certain components. This would reduce the risk of developers implementing a component that does not adhere to the design system.

## ✅   Proposed solution or API

One solution would be to provide methods for overriding certain parts of the theme instead of extending it. This is similar to how Tailwind has implemented their theme configuration (https://tailwindcss.com/docs/theme#overriding-the-default-theme).

Another option would be to have a function that just removes a variant/size/color option from a component, since the `extendTheme` option already provides a method for changing the default variant/size/colors that you want to keep but modify.

Finally one other option would be to update `extendTheme` to allow you to pass `undefined` for the option you want to remove.

Then being able to use the Chakra CLI to update the typings so that whatever you have overridden/removed is no longer autocompleted when writing a component.

## ↩️   Alternatives

Currently we have to create wrapper components for components like `Button` in order to limit the available options, which isn't as ideal.

**Comment by kculmback** [comment]
I was able to figure out a sort of work around that does not involve creating a wrapper component. I noticed that the `extendTheme` function can accept a base theme object as the last argument, so you can do something like this:

```typescript
import { extendTheme, theme as baseTheme } from '@chakra-ui/react';

type Dict = Record<string, any>;

const theme = {
  ...baseTheme,
  components: {
    ...baseTheme.components,
    Button: {
      baseStyle: baseTheme.components.Button.baseStyle,
      defaultProps: baseTheme.components.Button.defaultProps,
      sizes: {
        md: baseTheme.components.Button.sizes.md,
      },
      variants: {
        primary: (props: Dict) => {
          const defaultStyle = baseTheme.components.Button.variants.solid(props);

          return {
            ...defaultStyle,
            bg: 'blue.500',
          };
        },
      },
    },
  },
};

export default extendTheme({ /* ... */ }, theme);
```

Pairing this with chakra-cli to produce the typings mostly provides the desired effect. However, it still does not limit the color schemes available to the Button component. The above code would ignore any `colorScheme` but it could cause confusion to developers who are not super familiar with the UI. That being said there are some ways around that via documentation on the design system/implementation of Chakra or still using wrapper components.

**Comment by gpaluk** [comment]
I want to +1 this. Having the ability to mask internal assumptions does seem relevant to a library that supports bespoke design systems. This would be a very welcome addition.

**Comment by kculmback** [comment]
> Hi!
> This issue hasn't seen any activity recently. We close inactive issues after 35 days to manage the volume of issues we receive.
> If we missed this issue or you want to keep it open, please reply here. That will reset the timer and allow more time for this issue to be addressed before it is closed.

Would still love to see this get implemented.

**Comment by adamdiestelkamp** [comment]
This is relevant for our system too. We don't want the consumers of our design system to be able to use `colorScheme` on buttons but to have those all preset. We also want to limit the design token options. We don't want all the spacing variables to be available for use but be able to control what tokens are included.

**Comment by lbittner-pdftron** [comment]
+1 we would also love to see this feature - we have a tight knit design system and do not want to see the default Chakra values when autocompleting values with Typescript.

**Comment by bennyszantar** [comment]
This would be super usefull.

**Comment by gpaluk** [comment]
Sure, perhaps have an optional theme configuration. By default you could provide a default theme config but allow it to be null / undefined then simply allow the user to provide another custom theme config and / or override style properties individually.

**Comment by gpaluk** [comment]
> @kculmback @bennyszantar @lbittner-pdftron @gpaluk , the `extendTheme` method means extend the default theme. If you don't want the default theme values, you could pass your them object, without wrapping it in `extendTheme`
> 
> If you have a suggestion for another way this should wor, feel free to reopen the issue.

Sure, perhaps have an optional theme configuration. By default you could provide a default theme config but allow it to be null / undefined then simply allow the user to provide another custom theme config and / or override style properties individually

**Comment by Sh1d0w** [comment]
Just a quick look into chakra typescript's interface I can find this:

```

/**
 * This is a placeholder meant to be implemented via TypeScript's Module
 * Augmentation feature and is an alternative to running `npx @chakra-ui/cli
 * tokens`
 *
 * @example
 * ```ts
 * import { BaseThemeTypings } from "@chakra-ui/styled-system";
 * 
 * type DefaultSizes = 'small' | 'medium' | 'large';
 * 
 * declare module "@chakra-ui/styled-system" {
 *   export interface CustomThemeTypings extends BaseThemeTypings {
 *     // Example custom `borders` tokens
 *     borders: 'none' | 'thin' | 'thick';
 *     // ...
 *     // Other custom tokens
 *     // ...
 *     components: {
 *       Button: {
 *         // Example custom component sizes and variants
 *         sizes: DefaultSizes;
 *         variants: 'solid' | 'outline' | 'wacky' | 'chill';
 *       };
 *       // ...
 *      }
 *   }
 * ```
 *
 * @see https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation
 */
 ```
 
 So it seems it is already possible.

**Comment by jrolfs** [comment]
@Sh1d0w yeah, I contributed that portion of the theme types. I owe y'all some proper documentation on how to leverage this feature. In the meantime, you can check out the discussion from my PR to get an idea of how it works: https://github.com/chakra-ui/chakra-ui/pull/5579. I think I should be able to put together some documentation next week (in addition to functionality in **@chakra-ui/cli** for outputting definitions that leverage this feature).

**Comment by vlbin** [comment]
@jrolfs I'm having some issues with this feature, although it feels like a perfect solution if I get it to work :sweat_smile:. I get it to work in my own component library but when I install my component library in another React application it falls back on the default Chakra types. My declaration file containing the extended `CustomThemeTypings` is provided in my package but I'm not sure Chakra finds it.

To clarify, this works

```
node_modules
  @chakra-ui/react
  ...
lib
  types
    chakra.d.ts
  components
    Card.tsx // I can use my own button variants here
```
This does not work
```
node_modules
  @chakra-ui/react
  @my-org/my-design-system // My package including my own types
  ...
src
  App.tsx // It falls back on the existing Chakra variants

**Comment by jrolfs** [comment]
After we sort this maybe you can help me with the documentation 😁
