### ISSUE TITLE
No matching version found for @babel/helper-module-transforms@^7.14.0 (Using NextJS 10.2)

### ISSUE THREAD

**Issue by johnfrades** [chakra-ui/chakra-ui#3933]
# 🐛 Bug report

Cant install Chakra UI on NextJS 10.2, having an error about babel

## 💥 Steps to reproduce

1. Create new NextJS app using 10.2
2. install chakra using `npm i @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^4`
3. Error found `No matching version found for @babel/helper-module-transforms@^7.14.0`

**Comment by johnfrades** [comment]
Update: it works using `yarn`

**Comment by segunadebayo** [comment]
Great! Please use `yarn` then 😃

This is technically not an issue
