### ISSUE TITLE
[Modal] Dialogue closes if it contains Input components and Enter key is pressed

### ISSUE THREAD

**Issue by efossvold** [chakra-ui/chakra-ui#394]
**Describe the bug**
If a Modal contains Input field(s) and the Enter key is pressed the Modal closes. This happens regardless of whether the any of the Input fields are focused.

**Expected Behavior**
The Modal should only close if the onClose prop is set to false or if the Esc key is pressed and the closeOnEsc prop is true.

**Comment by Jake21x** [comment]
issue still occur

**Comment by Jake21x** [comment]
How i handle this is to attach an id or ref to submit button
- then add preventDefault on keypress enter  in every input.
then to create the expected result
- add after the preventDefault the click simulatation on submit button by id or ref

hope this will address in the future update

**Comment by TaylorFacen** [comment]
Bumping this issue. It happens on the Drawer component as well.

**Comment by anubra266** [comment]
@TaylorFacen  Could you provide a codesandbox reproduction please?

**Comment by TaylorFacen** [comment]
> @TaylorFacen Could you provide a codesandbox reproduction please?

I figured out that this was happening because the drawer autofocuses to the close button. No worries.

**Comment by mirror-ru** [comment]
For fix use:
`<ModalCloseButton tabIndex={-1} />`
