### ISSUE TITLE
Error: `emotion-theming` has been removed and all its exports were moved to `@emotion/react` package. Please import them like this  `import { useTheme, ThemeProvider, withTheme } from '@emotion/react'`.

### ISSUE THREAD

**Issue by NANI1734** [chakra-ui/chakra-ui#3945]
# 🐛 Bug report

always when I use chakra-UI, emotion-theming gives error

## 🌍 System information

| Software          | Version(s) |
| ----------------  | ---------- |
| Chakra UI/core |         0.8.0    |
| Browser            |  Chrome  |
| Operating System |  Windows  |

## 📝 Additional information
I have another error 

The @emotion/core package has been renamed to @emotion/react. Please import it like this import { jsx } from '@emotion/react'
 
But i fix it using yarn add @emotion/core@10.1.1

**Comment by NANI1734** [comment]
Pls fix this cuz i can't work with out it

**Comment by NANI1734** [comment]
ugh i close it by mistake

**Comment by segunadebayo** [comment]
Hey @NANI1734, 

Please upgrade to Chakra UI V1, or keep using `@emotion/core` and `emotion-theming` without upgrading.

https://chakra-ui.com/docs/migration

**Comment by NANI1734** [comment]
thx
