### ISSUE TITLE
Can't dynamically mark a MenuItemOption as checked

### ISSUE THREAD

**Issue by brunodesde1987** [chakra-ui/chakra-ui#3949]
# 🐛 Bug report

**First of all, Chakra UI is awesome! Thank you guys so much for this amazing set of tools.**

I'm trying to dynamically mark the `MenuItemOption` as checked and can't make it work.
I've tried using the `isChecked` prop in the `MenuItemOption` or the `defaultValue` in `MenuOptionGroup`.

After a few minutes trying to figure it out, I just realize that the `isChecked` prop doesn't work in the static code either.

## 💥 Steps to reproduce

1. Go to to the documentation page: https://chakra-ui.com/docs/overlay/menu#menu-option-groups
2. Choose any of the `MenuItemOption` of the second `MenuOptionGroup` and add the `isChecked` prop on it
4. See that when you click at the MenuButton the option you've choosed are not checked.

https://user-images.githubusercontent.com/28319535/116871622-eeadda00-abea-11eb-8a71-4f98f097c76b.mp4

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/chakraui-dynamic-checked-menuitemoption-zuqs0

## 🧐 Expected behavior

When use the `isChecked` prop in `MenuItemOption` the option has to be checked and the `defaultValue` should work when use it with dynamic `MenuItemOption`.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.6.0       |
| Browser          |   Firefox Developer Edition 89.0b6 (64-bits)        |
| Operating System |     Windows 10 Pro       |

**Comment by segunadebayo** [comment]
Hi @brunodesde1987,

This seems to be an error on your part. You're setting the `defaultValue` of `MenuOptionGroup` to the `id` of the menu option and then you're passing the `value` to the `name` of the menu option.

```jsx
// defaultValue = ["abc"]
// menu option 1 value = "Option 1"
// menu option 2 value = "Option 2"

// this leads to unexpected behavior
```

If you change the `value` passed to each menu item option to the `id` of the item, you'll get the result you expect.

```jsx
const items = [
  {
    id: "abc",
    name: "Option 1"
  },
  {
    id: "def",
    name: "Option 2"
  },
  {
    id: "ghi",
    name: "Option 3"
  }
];

function App() {
  return (
    <ChakraProvider>
      <Box height="100vh" padding={4}>
        <Menu isLazy lazyBehavior="unmount" closeOnSelect={false}>
          <MenuButton as={Button} colorScheme="blue">
            MenuItem
          </MenuButton>
          <MenuList minWidth="240px">
            <MenuOptionGroup type="checkbox" defaultValue={["abc"]}>
              {items.map((item) => (
                <MenuItemOption key={item.id} value={item.id}>
                  {item.name}
                </MenuItemOption>
              ))}
            </MenuOptionGroup>
          </MenuList>
        </Menu>
      </Box>
    </ChakraProvider>
  );
}
```

**Comment by segunadebayo** [comment]
Also the way to dynamically select an option:

```jsx
// uncontrolled scenario
<MenuOptionGroup defaultValue={...} />

// controlled scenario
<MenuOptionGroup value={...} onChange={...} />
```

You shouldn't pass `isChecked`  or `defaultChecked` the option. It's all managed from the option group.
