### ISSUE TITLE
[Docs] Link to theming page 404s

### ISSUE THREAD

**Issue by walela** [chakra-ui/chakra-ui#395]
**Describe the bug**
The link to https://chakra-ui.com/theming on the https://chakra-ui.com/badge page is broken.

**Expected Behavior**
Should link to a live page, perhaps https://chakra-ui.com/theme?

**To Reproduce**
Visit https://chakra-ui.com/badge and click on the `Learn more about theming` link.

**Suggested solution(s)**
Not sure if the link is supposed to point to https://chakra-ui.com/theme

**Comment by segunadebayo** [comment]
Hi @walela. Yes, it's meant to point to https://chakra-ui.com/theme.

Feel free to submit a quick PR to fix that. Thank you
