### ISSUE TITLE
Codesandbox templates are not working

### ISSUE THREAD

**Issue by EllaSharakanski** [chakra-ui/chakra-ui#3954]
# 🐛 Bug report

When opening a bug, the following two links to codesandbox are included, and they don't work any more:
- JavaScript Template:
  [JavaScript CodeSandbox template](https://codesandbox.io/s/github/chakra-ui/codesandbox-react-js-template/tree/master)

- TypeScript Template:
  [TypeScript CodeSandbox template](https://codesandbox.io/s/github/chakra-ui/codesandbox-react-ts-template/tree/master)

On codesandbox, they show: "TypeError (0 , $csb__framermotion.motion) is not a function".

## 💥 Steps to reproduce

1. Open a link from above
2. Wait for codesandbox to load and see the error

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/github/chakra-ui/codesandbox-react-js-template/tree/master and https://codesandbox.io/s/github/chakra-ui/codesandbox-react-ts-template/tree/master

**Comment by segunadebayo** [comment]
Thanks, I just updated it.
