### ISSUE TITLE
Disable keyboard focusing on menu items

### ISSUE THREAD

**Issue by bbovenzi** [chakra-ui/chakra-ui#3957]
# 🚀 Feature request

Add a prop to `MenuList` to disable keyboard interactions that change the focus of menu items. There can be scenarios where the focus change would get in the way (ie: An advanced menu that includes an input)

## 🧱 Problem Statement / Justification

There are use cases of a Menu dropdown where one does not want the keyboard to change focus. For example, if you want to include an input as the last option to serve as a custom "other" catchall.

## ✅ Proposed solution or API

A minimum would be to add a `disableTypeahead` boolean that defaults to `false` that would toggle `onTypeahead()`. A larger scope could be an array of enums where you can pick what types of keyboard interaction you want disabled.

## ↩️ Alternatives

Users could rethink how they are using a menu or build a custom one.

## 📝 Additional Information

Previously brought up here: https://discord.com/channels/660863154703695893/695564068895064094/834303404033441804

I'd be happy to submit a pull request if this feature is approved.

**Comment by segunadebayo** [comment]
Hi @bbovenzi,

I just pushed an update that prevents this issue from happening. Here's how we recommend using an input or advance elements:

```jsx
const MenuItemWithInput = (props) => {
 // a11y: omit the role because `menuitems` should not include interactive descendants
  const { role: _, ...rest } = useMenuItem(props)
  return (
    <div>
      <input {...rest} />
    </div>
  )
}

export const MenuWithInput = () => {
  return (
    <Menu>
      <MenuButton>Welcome</MenuButton>
      <MenuList>
        <MenuItemWithInput />
        <MenuItem>Menu 1</MenuItem>
        <MenuItem>Menu 2</MenuItem>
        <MenuItem>Menu 3</MenuItem>
        <MenuItem>Menu 4</MenuItem>
      </MenuList>
    </Menu>
  )
}
```

**Comment by segunadebayo** [comment]
We'll release an update shortly for this

**Comment by SantiagoBobrik** [comment]
Hello, I wanted to know what was the status of this update because I am having the same problem.
Thanks
