### ISSUE TITLE
Figma design resources

### ISSUE THREAD

**Issue by alexofthewu** [chakra-ui/chakra-ui#396]
Hey @segunadebayo ,

I'm a designer and my development team is looking to use Chakra UI for our current project. I saw on your twitter that you use Figma, so I was wondering if you had a design library available to help build wires and prototypes. I'm also happy to contribute in making it happen. 

Best,
Alex

**Comment by tsaiDavid** [comment]
@segunadebayo - This would be amazing!

**Comment by segunadebayo** [comment]
Hi @alexofthewu,

This is an amazing idea. At the moment we don't have a Figma or Sketch Component library for Chakra UI. Want to make it happen? I'm all in, let me know how I can help.

Thanks.

**Comment by aaronmcadam** [comment]
Did we get anywhere with this @alexofthewu?

**Comment by aaronmcadam** [comment]
@segunadebayo I think we can piggy back off of Steve Shoger's work on setting up Tailwind's design system in Figma. I'm planning on doing something similar when I get a chance. I'm thinking if we can at least start with the colours and typography, that'd be something.

**Comment by segunadebayo** [comment]
Sounds good to me. We'll look into design tooling and UI kits after the TS release.

**Comment by aaronmcadam** [comment]
> ...after the TS release.

Is there a list of issues that are blocking the TypeScript release?

**Comment by segunadebayo** [comment]
@aaronmcadam We're closing out work on the TypeScript release already. Once we're done, we need to upgrade the docs.

That's the part that might take some time, and I'm open to some help.

**Comment by aaronmcadam** [comment]
> Once we're done, we need to upgrade the docs.
> 
> That's the part that might take some time, and I'm open to some help.

That's cool, because I want to know what's changed and if there are any new best practices you've come up with, especially for use with TypeScript. I could at least help with proof reading and making sure things are explained well. Is there a way to get involved in that?

**Comment by segunadebayo** [comment]
Closing this out, for now, considering there have been no updates from @alexofthewu.

**Comment by guzmaniglesias** [comment]
https://www.figma.com/community/file/840198843830316310
At moove-it.com we've been working with Chakra UI in some of our projects.
We find an opportunity to build this Figma library that allow us to speak the same component language between designers and frontenders.

**Comment by rohmanhm** [comment]
Looks great @guzmaniglesias .
Thanks for amazing work @imNicoSuarez!
I have posted in HN https://news.ycombinator.com/item?id=23109559

**Comment by missmatsuko** [comment]
Looks great! Could there be a link to it from the docs so it's easier to find?

**Comment by plainspace** [comment]
Is there a place to submit issues about the Figma project? All of the avatar components are a pixel off (e.g. 25px instead of 24px)

> https://www.figma.com/community/file/840198843830316310
> At moove-it.com we've been working with Chakra UI in some of our projects.
> We find an opportunity to build this Figma library that allow us to speak the same component language between designers and frontenders.
> Great work of @imNicoSuarez.

**Comment by imNicoSuarez** [comment]
Hello, @plainspace 
I'm going to fix this bug you reported 

We are looking to add a space in the Spectrum of Chakra UI so that the community can report bugs and improvements for the Figma library.

In the meantime if you find any bugs in the library you can mention me here. 

Greetings
Nico

**Comment by plainspace** [comment]
Sounds great Nico. Will you update the thread when you get the space spun up?

> Hello, @plainspace
> I'm going to fix this bug you reported
> 
> We are looking to add a space in the Spectrum of Chakra UI so that the community can report bugs and improvements for the Figma library.
> 
> In the meantime if you find any bugs in the library you can mention me here.
> 
> Greetings
> Nico

**Comment by imNicoSuarez** [comment]
@plainspace Yes, 

when we get the space in Spectrum, I will share the link here.

Greetings

**Comment by imNicoSuarez** [comment]
Hello, I leave you a link of the community discord, in that place you can find a design channel which you can report bugs and improvements and chat about the library.

Link: https://discord.gg/xyCv97n

**Comment by villesau** [comment]
I think this should still be open. The linked ui kit is 10 months old. There is also another one but I think it's incomplete too: https://www.figma.com/file/cWuIe1XzqLAKnBcLu9WmDy/Chakra-UI?node-id=8%3A461

**Comment by vamshi9666** [comment]
Support for adobe xd ?

**Comment by cayleyh** [comment]
In case anyone finds this, there is now an official one for Figma: https://www.figma.com/community/file/971408767069651759
