### ISSUE TITLE
Allow the developer to set the value of the `Select` component

### ISSUE THREAD

**Issue by vedantroy** [chakra-ui/chakra-ui#3966]
# 🚀 Feature request
Allow the `Select` component to have a default value that is one of the options.

## 🧱 Problem Statement / Justification
 
> Please provide valid reason(s) why this should added to Chakra UI.
> Would allow the `Select` component to be useful when making anything that needs to reflect existing state.
> If this feaure is related to a problem you've noticed. Mention it as well

Currently, there is no way to control what the default value for a `Select` is. This feature is useful, if you are, for example, allowing the user to edit some settings (maybe change the status of a person), and you want them to see what the current status of a person in the system is.

## ✅ Proposed solution or API
A prop like `defaultSelect` which takes in an number (the index of the entry to be selected).
## ↩️ Alternatives
Using the Radio component. But, the radio often takes up too much space.

## 📝 Additional Information

> What resources (links, screenshots, etc.) do you have to assist this effort?

This is used inside Google Docs settings.

![example](https://user-images.githubusercontent.com/8407819/117357288-a05a3e80-ae69-11eb-9c0f-c31139727d97.png)

**Comment by TimKolberger** [comment]
The chakra UI `Select` component composes the native `select` component.
[React provides the prop `defaultValue` for all input elements including `select`](https://reactjs.org/docs/uncontrolled-components.html#default-values).

Example:

```jsx
<Select defaultValue="option1">
  <option value="option1">Option 1</option>
  <option value="option2">Option 2</option>
  <option value="option3">Option 3</option>
</Select>
```

Please close this issue if it solves your feature request :)
