### ISSUE TITLE
Upgrading framer-motion to 4.1.13 causes Modal to only show overlay on open

### ISSUE THREAD

**Issue by j-dominguezp** [chakra-ui/chakra-ui#3967]
# 🐛 Bug report

As the title says upgrading framer motion to 4.1.13 version causes Modal to not show content onOpen, only ModalOverlay.

Inspecting what happened I found that ModalContent is there but in opacity: 0.

Also realized this only happened after updating framer motion to 4.1.13.

**Last working version is 4.1.11.** 

This could be a problem for users doing fresh installations.

## 💥 Steps to reproduce

1. Open a modal in any project with framer-motion 4.1.13 version.
2. You'll only see Modal Overlay

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/proud-violet-3gqny?file=/pages/index.tsx

## 🧐 Expected behavior

Modal content sould be visible when openning a Modal.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |        1.6.1      |
| Browser          |       Edge 92.0.878.0    |
| Operating System |       Windows 10     |

**Comment by anudit** [comment]
Same issue with <Menu> too, Doesn't close after opening.

**Comment by lucasvianav** [comment]
I'm having the same problem. Were you able to figure out any workaround?

**Comment by nikosolihin** [comment]
On the same boat with `<Modal>`.

Workaround was to `yarn remove framer-motion` and `yarn add framer-motion@4.1.11`.

**Comment by BarbarConan** [comment]
Same here. Downgrading framermotion did not work for me either. 

Setting `motionPreset="none"` is a solution for now.

**Comment by j-dominguezp** [comment]
> Yes, I can confirm that downgrading framer-motion solves the issue.
> 
> Consider this a walkaround till framer-motion releases a patch.
> 
> Thanks

Thanks.

Maybe this should be stated in Getting Started docs, as all new users doing fresh installations will have this issue.

**Comment by la55u** [comment]
Is there an issue on framer's git that tracks this?

**Comment by segunadebayo** [comment]
Closing in favor of https://github.com/chakra-ui/chakra-ui/issues/3994
