### ISSUE TITLE
[Menu/Text] Text with 'noOfLines' doesn't style correctly within a Menu set to 'matchWidth'

### ISSUE THREAD

**Issue by tonyjmartinez** [chakra-ui/chakra-ui#3968]
# 🐛 Bug report

## 💥 Steps to reproduce

1. I have two reproductions with the same code, but different Chakra versions. [Repro 1.1.4](https://codesandbox.io/s/recursing-sun-wvhzk?file=/src/index.tsx) and [Repro 1.6.1](https://codesandbox.io/s/elated-torvalds-3vrqk?file=/src/index.tsx)
2. They both have `<Menu />` set to `matchWidth`. And `<Text />` with `noOfLines` specified within a `<MenuList />`
3. In the 1.1.4 reproduction, the text correctly wraps to two lines. In the 1.6.1, the text never wraps and this makes the `<MenuList />` fail to match the width of the button.

## 💻 Link to reproduction

CodeSandbox reproduction:[Repro 1.1.4](https://codesandbox.io/s/recursing-sun-wvhzk?file=/src/index.tsx) and [Repro 1.6.1](https://codesandbox.io/s/elated-torvalds-3vrqk?file=/src/index.tsx)

## 🧐 Expected behavior

I expect the text to wrap/truncate the way it does in the previous version.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.6.1          |
| Browser          |   Chrome         |
| Operating System |  MacOS          |

**Comment by anubra266** [comment]
You have to set a `maxWidth` on the Text

```html
<Text maxW="200px" noOfLines={2}>Lorem ipsum something something something</Text>
```

**Comment by tonyjmartinez** [comment]
For posterity, @anubra266 checked this for me on Discord and found that the text does overflow in the docs when `matchWidth` is set. So I still think this is a bug.

**Comment by anubra266** [comment]
For more posterity, I can confirm this is a bug.
