### ISSUE TITLE
Can't customize theme colors using function

### ISSUE THREAD

**Issue by glyxs** [chakra-ui/chakra-ui#3971]
# 🐛 Bug report

I was trying to customize colors of my theme and came upon an issue that colors won't change based on the props passed to the theme. 

Just like we can pass a function to global styles:
```
import { mode } from "@chakra-ui/theme-tools";
const styles = {
    global: (props) => ({
        'body, html': {
            color: mode("red.800", "white")(props),
            bg: mode("white", "red.800")(props),
        },
    }),
};
export default styles;
```

Same does not work with colors for some reason:

```
import { mode } from "@chakra-ui/theme-tools";
const colors = {
    custom: (props) => ({
        bg: mode("red.800", "white")(props),
        primary: mode("white", "red.800")(props),
        secondary: mode("gray.200", "red.600")(props),
    }),
};
export default colors;
```

All of the styles overrides in my example are joined together in theme.js
```
import { extendTheme } from "@chakra-ui/react";
import styles from "./styles";
import colors from './colors';
const overrides = {
    colors,
    styles
};
export default extendTheme(overrides);
```

## 💥 Steps to reproduce

1. Create custom theme with global styles and colors and attach it to ChakraProvider
2. Customize global styles and colors based on the colorMode value
3. Click on the 'log theme' in App.js to see that changes took place
4. Text will not change color no matter what (issue).
5. Global styles will change based on the colorMode

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/brave-worker-ytdkj

## 🧐 Expected behavior

Changing the colorMode using toggle in App.js should change color of the text based on the current colorMode, but only global styles are changing when doing so.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.6,1       |
| Browser          |     Google Chrome v. 88.0.4324.146    |
| Operating System |      Windows 10 20H2   |

**Comment by glyxs** [comment]
Fount similar issue in [#1162](https://github.com/chakra-ui/chakra-ui/issues/1162#issue-655009925). Something must have changed since 2020...? 

This [workaround](https://github.com/chakra-ui/chakra-ui/issues/1162#issuecomment-682270232) is kind of working, allowing me to use custom colors, but it is limited to component prop styles only (meaning I can't use those colors in global styles), but most importantly it breaks the default Chakra theme completely, leaving components unstyled.

The goal is to have a set of predefined colors that change based on the color mode. The use of `mode` function inside theme colors could save so much time not designing component color logic via `useColorModeValue` each time I need a custom color.

**Comment by segunadebayo** [comment]
We won't be supporting this API @glyxs. We'll consider a better API for this in the next major but not a priority for now. Please use `useColorMode` for now as described above.
