### ISSUE TITLE
Remove Lighthouse "Avoid non-composited animations" issue

### ISSUE THREAD

**Issue by paulbuechner** [chakra-ui/chakra-ui#3974]
# 🚀 Feature request

Evaluating the Web App performance with Lighthouse, the following report for chakras `<Skeleton />` animations is given:

- Avoid non-composited animations – x animated elements found!

![grafik](https://user-images.githubusercontent.com/45827409/117541384-ee12aa80-b013-11eb-8e74-653e81513f8d.png)

## 🧱 Problem Statement / Justification

As Google states on their **web.dev** [forum](https://web.dev/non-composited-animations/?utm_source=lighthouse&utm_medium=devtools): 

> Non-composited animations can appear janky (i.e. not smooth) on low-end phones or when performance-heavy tasks are running on the main thread. Janky animations can increase the Cumulative Layout Shift (CLS) of your page. Reducing CLS will improve your Lighthouse Performance score.

## ✅ Proposed solution or API

Give the `<Skeleton />` component a optional prop `transform="auto | auto-gpu"`, like in chakra version 1.6.2, to render the Animation with GPU support, or support it natively, so the warning gets resolved.

## 📝 Additional Information

As stated in this [CHANGELOG](https://github.com/willmendesneto/ngx-skeleton-loader/blob/master/CHANGELOG.md) under this [point](https://github.com/willmendesneto/ngx-skeleton-loader/blob/master/CHANGELOG.md#fixed-3) the warning can be fixed by using `translate3d` instead of the `background-position` css prop:

> Fixed
> Removing Lighthouse "Avoid non-composited animations" issue. Lighthouse shows warnings from ngx-skeleton-loader.scss -file (progress).
> 
> "Avoid non-composited animations":
> 
> "Animations which are not composited can be janky and contribute to CLS"
> 
> To solve that, instead of using CSS background-position the module is now using CSS translate3d, which improves the animation by using GPU instead of CPU. Issue fixed and performance boost added 🎉
>

**Comment by tailic** [comment]
We are facing the same issue with CLS warnings on the `<Skeleton />` animation. Is there a workaround for this or maybe it is addressed somewhere else?

**Comment by anubra266** [comment]
> We are facing the same issue with CLS warnings on the `<Skeleton />` animation. Is there a workaround for this or maybe it is addressed somewhere else?

@tailic [here](https://github.com/willmendesneto/ngx-skeleton-loader/blob/master/CHANGELOG.md#fixed-3)
