### ISSUE TITLE
[1.6.1] Popover isLazy/isOpen seems not working

### ISSUE THREAD

**Issue by nghiepit** [chakra-ui/chakra-ui#3975]
# 🐛 Bug report

In `1.6.1` when to pass `isLazy` prop on the `Popover` component, the popover no longer works.
The bug second, the popover can't off when to set `isOpen` is `false`.
## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/chakra-bug-popover-m3c5t?file=/src/index.tsx:336-342

## 🧐 Expected behavior

Works again

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.6.1      |
| Browser          |        Chrome    |
| Operating System |    macOS        |

**Comment by giacomorebonato** [comment]
I'd like to add to this issue that if you manage to open the popover... There is no way to close it anymore.
I tested this on your Sandbox above by adding `<PopoverCloseButton />`.

**Comment by RageItalic** [comment]
I think popover seems to be broken in general.

**Comment by j-dominguezp** [comment]
Hi guys, seems related to #3967 

Try downgrading framer motion
