### ISSUE TITLE
Editable deafultValue issue Chakra UI

### ISSUE THREAD

**Issue by abhim-089** [chakra-ui/chakra-ui#3981]
# 🐛 Bug report

I am currently passing  name as prop in editable default value property but it's not showing on the screen.

## 💥 Steps to reproduce

1. Click on edit icon
2. Label become editable.
3. Edit the name.
4. Click on check button to change the value by invoking callback function which is passed as prop.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/proud-dawn-wcfbo

## 🧐 Expected behavior

The label should be editable on edit click and invoke callback function after submit.

## 🧭 Possible Solution

I put the name in value property so its visible but not editable after edit click. 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       @chakra-ui/core: 0.8.0  |
| Browser          |     Chrome Version 90.0.4430.93 (Official Build) (64-bit), Firefox       |
| Operating System |  Windows 10          |

**Comment by segunadebayo** [comment]
Hey @abhim-089,

This works in the latest version of Chakra UI. Please upgrade accordingly.
https://codesandbox.io/s/cool-voice-wymr7?file=/src/App.js

Thanks
