### ISSUE TITLE
Modal: opacity: 0

### ISSUE THREAD

**Issue by RadovanPelka** [chakra-ui/chakra-ui#3982]
# 🐛 Bug report

Modal: opacity: 0

## 💥 Steps to reproduce

1. yarn create next-app --example with-chakra-ui-typescript with-chakra-ui-typescript-app
2. yarn add @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^4

## 💻 Link to reproduction

![image](https://user-images.githubusercontent.com/29738200/117646726-64d2b380-b18c-11eb-9895-21066e90461e.png)

![image](https://user-images.githubusercontent.com/29738200/117646743-6ac89480-b18c-11eb-80be-339adc931e27.png)

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     latest       |
| Browser          |    chrome        |
| Operating System |     macos       |

**Comment by RadovanPelka** [comment]
@segunadebayo

**Comment by markodvornik** [comment]
+1

I'm using `size="full"` Modal and the modal-section has opacity 0 when `Open`.

```html
<section class="chakra-modal__content css-ffrka9" role="dialog" id="chakra-modal-140" tabindex="-1" aria-modal="true" style="opacity: 0; transform: scale(0.95) translateZ(0px);" aria-labelledby="chakra-modal--header-140" aria-describedby="chakra-modal--body-140">
```

**Comment by RadovanPelka** [comment]
Exactly

**Comment by marciocuelho** [comment]
any good solution?

**Comment by segunadebayo** [comment]
This is an issue with the most recent version of framer-motion (`4.1.13`). Kindly downgrade to `4.1.11`.

Feel free to open an issue in framer-motion
