### ISSUE TITLE
Can't close popover

### ISSUE THREAD

**Issue by violabg** [chakra-ui/chakra-ui#3990]
# 🐛 Bug report

I followed the doc example for the pop over:
https://chakra-ui.com/docs/overlay/popover

but I'm not albe to close id after is open, I even try to use useDiscloser hook to control it, but it doesn't close.
Am I missing something or is a bug?

## 💻 Link to reproduction

https://codesandbox.io/s/chakra-bug-popover-forked-fivvw?file=/src/index.tsx

## 🧐 Expected behavior

To be able to close.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.6.1      |
| Browser          |     all       |
| Operating System |      macOS 11.3.1      |

**Comment by j-dominguezp** [comment]
Hi @violabg, this bug is related to this issue #3967 

Workaround is to downgrade framer-motion. You'll find more info in the issue itself. Hope that helps.

**Comment by segunadebayo** [comment]
Closing in favor of https://github.com/chakra-ui/chakra-ui/issues/3994
