### ISSUE TITLE
FAQ: Menu, Popover not closing? Check here

### ISSUE THREAD

**Issue by segunadebayo** [chakra-ui/chakra-ui#3994]
It seems some components got affected by the most recent patch release of `framer-motion` (4.1.13).

If you experience an issue where the menu, popover, or tooltip components don't show/close correctly, kindly downgrade to framer-motion `4.1.11` for now.

Thank you!

**Comment by j-dominguezp** [comment]
@segunadebayo please add Modal to the component's list too

**Comment by with-heart** [comment]
I took some time to investigate and opened a bug report on the `framer-motion` repo: https://github.com/framer/motion/issues/1148

**Comment by with-heart** [comment]
> I feel like the docs should be hotfixed to use framer-motion@4.1.12

imo that would be an overreaction. Upstream bugs happen from time to time, and I can't think of a single time I've seen an open source project update their installation instructions due to a temporary bug in another lib.

Unfortunately there's always the small risk that something like this might happen. That's just the cost of doing (open source) business.

**Comment by j-dominguezp** [comment]
> Because those users would be pinned to that specific version and would lose out on any benefit to future versions of `framer-motion` if they don't unpin after it's resolved. If it becomes a more long-term issue I would be open to changing it, but right now it's just a momentary blip in time.

I agree with this. 

`chakra-ui` itself could depend (in the future) on a newer version of `framer-motion`, so that would be a problem for users pinned in 4.1.11 or 4.1.12.

**Comment by ka2n** [comment]
A new version(`4.1.16`) released and fixed this.
https://codesandbox.io/s/optimistic-hawking-ofjsy

**Comment by nikosolihin** [comment]
`4.1.16` fixes the issues with `<Modal>` for me.

**Comment by with-heart** [comment]
Issues should now be resolved because @mattgperry is awesome! Please let us know if you notice any issues.

**Comment by toilahungvn98** [comment]
Thanks, "Popover close" working
