### ISSUE TITLE
[RadioButtonGroup] Add TypeScript guide for child props

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#40]
Currently, there is no definitive guide about specifying prop types of a `RadioButtonGroup`'s children. I tried my best to come up with a solution browsing through [React+TypeScript Cheatsheets](https://github.com/typescript-cheatsheets/react-typescript-cheatsheet#forwardrefcreateref), but could only make up the code snippet below, which is full of boilerplate:

```tsx
import { Button } from '@chakra-ui/core';
import React from 'react';

type RadioButtonProps = React.ComponentPropsWithoutRef<typeof Button> & {
  isChecked?: boolean;
  value?: React.InputHTMLAttributes<HTMLInputElement>['value'];
};

const RadioButton = React.forwardRef(
  (
    { isChecked, isDisabled, ...restProps }: RadioButtonProps,
    ref: React.Ref<HTMLButtonElement>,
  ) => {
    return (
      <Button
        ref={ref}
        aria-checked={isChecked}
        role="radio"
        isDisabled={isDisabled}
        {...restProps}
      />
    );
  },
);

export default RadioButton;
```

Please consider providing better docs about types or creating an official `RadioButton` component with correctly specified props, as using [`React.forwardRef`](https://reactjs.org/docs/forwarding-refs.html) is not a convenient approach.

**Comment by tioluwani94** [comment]
Hi @kripod,

We are looking into this and working on a solution, for now, you can follow the example below to create types the `RadioButton` component.

```jsx
import { Button } from '@chakra-ui/core';
import React from 'react';
import { ButtonProps } from '@chakra-ui/core/dist/Button';

type RadioButtonProps = ButtonProps & {
  isChecked?: boolean;
  value?: React.InputHTMLAttributes<HTMLInputElement>['value'];
};

const RadioButton = React.forwardRef(
  (
    { isChecked, isDisabled, ...restProps }: RadioButtonProps,
    ref: React.Ref<HTMLButtonElement>,
  ) => {
    return (
      <Button
        ref={ref}
        aria-checked={isChecked}
        role="radio"
        isDisabled={isDisabled}
        {...restProps}
      />
    );
  },
);

export default RadioButton;
```

**Comment by kripod** [comment]
@tioluwani94 Thank you for the insights! I think a link may be added to the docs about it for better discoverability.
