### ISSUE TITLE
Static CSS Extraction

### ISSUE THREAD

**Issue by samuelcastro** [chakra-ui/chakra-ui#4003]
# 🚀 Feature request

It'd be amazing to enhance Chakra UI with a zero-runtime CSS in JS library or even Tailwind CSS to improve performance in general.

## 🧱 Problem Statement / Justification

The problem is very obvious: https://chakra-ui.com/docs/comparison#the-runtime-trade-off-%EF%B8%8F

> Since Chakra UI uses CSS-in-JS under the hood (emotion + styled-system), this flexibility comes with a small price to pay when it comes to runtime. This runtime footprint is caused by style computations by styled-system, and className generation by emotion.
> 
> If your app deals with high, frequently changing data that is performance sensitive, you might notice this footprint as your app grows.

## ✅ Proposed solution or API

There was a discussion around it and I want to re-open it because I think this is very important: https://github.com/chakra-ui/chakra-ui/issues/859

## ↩️ Alternatives

I'm considering to use [Linaria](https://linaria.dev/) or [TailwindCSS](https://tailwindcss.com/), but that would require me to create my own UI library on top of it, it'd be just amazing to have Chakra UI replacing Emotion + Styled-System in favor of Linaria/TailwindCSS, but keeping the [ThemeUI specification](https://theme-ui.com/theme-spec/).

## 📝 Additional Information

- https://calendar.perfplanet.com/2019/the-unseen-performance-costs-of-css-in-js-in-react-apps
- https://daily.dev/blog/why-i-moved-from-styled-components-to-tailwind-css-and-whats-the-future-of-css-in-js
- https://leerob.io/blog/tailwind

**Comment by paambaati** [comment]
This might be a big undertaking (given how much Chakra-UI depends on Emotion), but if the team would consider, now is the perfect time to start exploring other zero-runtime style libraries like [`vanilla-extract`](https://vanilla-extract.style/) and [`sprinkles`](https://github.com/seek-oss/vanilla-extract/tree/master/packages/sprinkles).

Sprinkles is a small abstraction over vanilla-extract, and together they offer — 

1. Fantastic type-safe primitives for building design systems with no runtime
2. Fully statically built plain CSS and an optional runtime for dev mode
3. Build plugins for Webpack, Babel, esbuild and Gatsby.

They're both built by the same folks that also built [`treat`](https://seek-oss.github.io/treat/) and [`capsize`](https://seek-oss.github.io/capsize/)!

**Comment by with-heart** [comment]
@paambaati I don't know that we have any solid plans yet, but I can say that this is a direction we'd like to explore, and `vanilla-extract` seems to be generating some excitement. That's infinitely more likely than Tailwind.

**Comment by samuelcastro** [comment]
**vanilla-extract** and **sprinkles** look like a perfect fit for this. :)

**Comment by marek-sed** [comment]
wouldnt switching to something like [stiches](https://stitches.dev/) be more straight forward for perf gain?

**Comment by samuelcastro** [comment]
@segunadebayo Would you have any feedback on this? Is it on your roadmap? Do you guys have a timeline?

Thank you.

**Comment by with-heart** [comment]
We're looking into various options for how to achieve this, and it's definitely something we plan to accomplish in v2.

**Comment by segunadebayo** [comment]
Update: After several days of research and discussion with the creators of Vanilla Extract and Sprinkles, it might be quite difficult to support static extraction for Chakra UI's component given the numerous amount of use-cases we have.

**We don't want to make promises we can't keep.**

In the next major version, we might not opt for static extraction just yet and if we do, it might be a completely separate package from **chakra-ui** to avoid excessive breaking changes when people migrate.

The road to V2 already includes a lot of structural changes that might be too much for us to manage if we choose to add static extraction to it.

We're looking to improve the speed of style computations in V2 by re-evaluating our stack.

Thanks for understanding.

**Comment by dlindenkreuz** [comment]
PSA: Stitches recently had their first stable release v1.0: https://github.com/modulz/stitches/releases/tag/v1.0.0

**Comment by samuelcastro** [comment]
Six months passed by, do you have more information on this @segunadebayo ?

Thanks!

**Comment by samuelcastro** [comment]
@with-heart Would you have insights on this well? We'd love to hear from you guys.

**Comment by fandy** [comment]
Will this be adopted for V3?

**Comment by wub** [comment]
Definitely interested in this - we're considering switching frameworks as this is killing our SSR performance (using Chakra UI with Remix).

**Comment by sudazzle** [comment]
Any update on this feature?

**Comment by thesyntaxninja** [comment]
Love the DX of Chakra but have been looking at Tailwind CSS due to performance issues. 

Would love to see Chakra UI with a zero-runtime CSS in JS solution. Any updates?

**Comment by bfeister** [comment]
Just dropping my +1 / "Hey, is this still being considered?" on here. We use Chakra in a demanding high perf runtime where static extraction would be a huge help!

**Comment by wub** [comment]
For those interested, it looks like @segunadebayo has posted an update here: https://github.com/chakra-ui/chakra-ui/issues/7180
> Regarding CSS-in-JS, we've been in a 10-months long research phase to design our first static solution for Chakra UI. We've made a lot of progress with this, and we're excited to show it in the coming months.

**Comment by galliotl** [comment]
Hey, is there a way to help contributing to this roadmap?
Completely new to Open Source Development so don't know if there's a better way to ask it

**Comment by yarinsa** [comment]
@segunadebayo Any news on this issue? Anyway I can contribute to make this happen?

**Comment by coopbri** [comment]
@yarinsa one of the pillars of Chakra expanded into Panda CSS: https://panda-css.com/

Check this out for concrete plans regarding Chakra itself: https://www.adebayosegun.com/blog/chakra-panda-ark-whats-the-plan
