### ISSUE TITLE
Add Option component for easy styling inside Select

### ISSUE THREAD

**Issue by vedantroy** [chakra-ui/chakra-ui#4004]
# 🚀 Feature request

## 🧱 Problem Statement / Justification
Sometimes, I want to style the `option`s inside of a `Select` component. This is currently possible using React's `style` prop, but it's a bit unwieldy. I much prefer to use Chakra UI's style props.

> Please provide valid reason(s) why this should added to Chakra UI.

It would make the `Select` component more powerful?

## ✅ Proposed solution or API

> Please provide code snippets, gists, or links to the ideal design or API
```react
<Select>
    <Option backgroundColor="#00000" disabled>&nbsp;</Option>
    <Option backgroundColor="#someOtherColor" value="Foo">Foo</Option>
 </Select>
```

## ↩️ Alternatives

> What alternative solutions have you considered before making this request?

Styling the `option` using React's default API.

## 📝 Additional Information

**Comment by hathal100** [comment]
Open

**Comment by segunadebayo** [comment]
Hi @vedantroy, there's not much you can do to change the styles of the native select's option.

You can consider using the `sx` prop to achieve this.

```jsx
<Select sx={{ "option": { bg: "red.300" }}} />
```
