### ISSUE TITLE
[Menu] The isLazy prop prevents keyboard accessibility from working in the <Menu /> component

### ISSUE THREAD

**Issue by tonyjmartinez** [chakra-ui/chakra-ui#4009]
# 🐛 Bug report

The `isLazy` prop prevents keyboard accessibility from working in the `<Menu />` component

## 💥 Steps to reproduce

1. Visit the sandbox [reproduction](https://codesandbox.io/s/elastic-austin-tqp9s?file=/src/index.tsx)
2. Try tabbing to the menu and opening with [enter]. None of the items in the menu will be highlighted, so you can't access it with a keyboard
3. Remove the `isLazy` prop on the menu
4. Try using the keyboard again, and it will work.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/elastic-austin-tqp9s?file=/src/index.tsx

## 🧐 Expected behavior

I'd expect the keyboard accessibility to work the same whether or not `isLazy` is provided.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.6.1          |
| Browser          |   Chrome         |
| Operating System |  MacOS          |

**Comment by segunadebayo** [comment]
Good catch @tonyjmartinez,

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
