### ISSUE TITLE
[Toast] TypeError on rendering toast

### ISSUE THREAD

**Issue by PTaylour** [chakra-ui/chakra-ui#401]
**Describe the bug**

I'm trying to use `useToast` with the default `render` field

```js
<Button
      onClick={() => {
            toast({
              title: "An error occurred.",
              description: "message",
              status: "error",
              duration: 9000,
              isClosable: true
            });
          }}
    >
     Example in docs fails
</Button>
```

but I'm getting this error:

```
react-dom.development.js:20312 Uncaught TypeError: Cannot read property 'question-outline' of undefined
    at eval (index.js:49)
```

I see similar TypeErrors when using the `render` field to provide my own toast component, unless that component doesn't use an icon or a "complex" component such as `Alert`.

Replicated from `0.3.3` onwards. (before `0.3.3` I see this now fixed error https://github.com/chakra-ui/chakra-ui/issues/164)

See codesandbox for some examples https://codesandbox.io/s/chakra-js-toast-not-working-pxs2q

**Expected Behavior**

That toast works as expected or the docs are update to show if I'm using it wrong :)
 

**To Reproduce** 

See codesandbox
https://codesandbox.io/s/chakra-js-toast-not-working-pxs2q

**Suggested solution(s)**
Is the toast being rendered outside of the provider?

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome + safari
 - Tested Version 0.3.0 - 0.5.2

**Comment by jeremyadavis** [comment]
Just make sure your ThemeProvide is outside of the component that needs to use the theme context.
https://codesandbox.io/s/chakra-js-toast-not-working-o2pi1

**Comment by PTaylour** [comment]
Ah yes this makes a lot of sense. In the real life example I had the `ThemeProvider` inside of a gatsby `Layout` component but we were using `useToast` in a component higher in the tree.

Have since seen the chakra gatsby plugin where the `ThemeProvider` is in `wrapRootElement`

Thanks for taking a look!
