### ISSUE TITLE
RenderProps['id'] is `string | number` but id should only be a string.

### ISSUE THREAD

**Issue by rchinerman** [chakra-ui/chakra-ui#4011]
# 🐛 Bug report

RenderProps['id'] is `string | number` but id should only be a string.

## 💥 Steps to reproduce

N/A

## 💻 Link to reproduction

N/A

## 🧐 Expected behavior

The ids  would be expected as string types.

## 🧭 Possible Solution

Keep the id types as strings.

## 🌍 System information

N/A

**Comment by segunadebayo** [comment]
Hi @rchinerman, please consider calling `id.toString()` in your project to resolve this.

We use numbers for the internal id management for the toast component, hence the reason for `string | number`.

Thanks
