### ISSUE TITLE
Data Attributes not working for Checkbox component

### ISSUE THREAD

**Issue by joshiain** [chakra-ui/chakra-ui#4018]
# 🐛 Bug report

Data attributes appear not to be working for the Checkbox component as they are not present inside the dataset property when declared.

## 💥 Steps to reproduce

1. Create a Checkbox component
2. Add a data attribute to the component (e.g. data-test="test")
3. Log event.target.dataset when checkbox is changed
4. See the console doesn't contain the data attribute in event.target.dataset

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/cold-cache-0cze8?file=/src/index.js

## 🧐 Expected behavior
Expect to see the data attribute inside event.target.dataset. In the codesanbox I included a regular html checkbox to show that this should work

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.6.1      |
| Browser          |      Chrome and Safari      |
| Operating System |     MacOS Big Sur 11.3.1       |

**Comment by segunadebayo** [comment]
Hi @joshiain,

This is by design, the data attribute is passed to the `label` container, and only form-related attributes are forwarded to the input.

If you need to select the input, consider using `.chakra-checkbox__input`.

I'm sure you're aware that the checkbox is different from a native checkbox due to its custom design.

Thanks for understanding.

**Comment by joshiain** [comment]
Hi @segunadebayo , thanks for the information. 

The reason I wanted to use data attributes with the Checkbox component is because I am developing a dynamic form where it's up to the user how many times the checkbox would appear in the form. To keep track of the state of the controlled component, I pass through the index of other dynamic components through a `data-idx` attribute, which allows me to set the state of the correct index in the state array of objects on input change. This works for the other chakra input components I use in the dynamic section of the form.

Would you have any suggestions on how I could implement this for the Checkbox component?

Thanks!

**Comment by handletastic** [comment]
what should we do for all other cases that we want to use selectors that are data driven.

for example, my use case, I am using Chakra and our QA team is using Cypress, if we want to use the data-cy attribute allowed by react and recommended by Cypress in their best practices, but then Chakra strips them off, its rather frustrating.

Maybe I am misusing this, would be great if you could provide some guidelines. I tried searching on Chakra documentation about testing and couldnt find any meaningful information about this behaviour of stripping data attributes.

Thanks in advance!

**Comment by DiegoMcDipster** [comment]
I just came across this in my cypress tests.  The way I got around it was using @segunadebayo suggestion of using the chakra class on the input, which is a child of the label:

```
      cy.get("[data-cy=choice-2]") // the label has this attribute
        .children(".chakra-checkbox__input")  // the <input> is a child of the label with classname=chakra-checkbox__input
        .uncheck({ force: true });  // BINGO!
```

I hope this helps.

**Comment by csleary** [comment]
I was pleasantly surprised to learn you can access the checkbox data value as follows. e.g. for a `data-my-data-value` prop on the checkbox, you'd access it as: `e.currentTarget.labels.[0].dataset.myDataValue` in the onChange handler.
