### ISSUE TITLE
Could not find module in path: '@emotion/memoize' in CodeSandbox

### ISSUE THREAD

**Issue by talentlessguy** [chakra-ui/chakra-ui#4019]
# 🐛 Bug report

When using Chakra UI in codesandbox.io it breaks with this error:

```
Could not find module in path: '@emotion/memoize' relative to '/node_modules/@emotion/cache/dist/emotion-cache.browser.esm.js'
```

screenshot:

![image](https://user-images.githubusercontent.com/35937217/118408943-a5509680-b690-11eb-9c1a-b3cdfca288b1.png)

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/vigorous-dirac-cto67

## 🧐 Expected behavior

It shouldn't throw any module-related errors.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.6.1           |
| Browser          |  Firefox 89          |
| Operating System | Manjaro Linux x64            |

**Comment by segunadebayo** [comment]
Hey @talentlessguy, I tried this and it works.

Here's the link: https://codesandbox.io/s/zen-curran-z21o1

**Comment by talentlessguy** [comment]
interesting 

not sure why my sandbox broke, yours seems to be working

thanks for taking time to help :)
