### ISSUE TITLE
Avatar overrides icon attribute with name when the src is missing or lazy loading.

### ISSUE THREAD

**Issue by srameshr** [chakra-ui/chakra-ui#4028]
# 🐛 Bug report
Avatar component images should have an alt tag for SEO at the same time if the image is downloading the src, the fallback src should be the icon (if any) provide and, not the name attribute. 

## 💥 Steps to reproduce

```<Avatar loading="lazy" name="MY NAME" src="http//:xyz" icon={<MyIcon />} /> ```

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/competent-mirzakhani-i1hq8

## 🧐 Expected behavior

Let the image src be the icon (may be base 64 of icon) instead of case letters of the name tag.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.5.2      |
| Browser          |        Chrome    |
| Operating System |      MacOS      |

**Comment by srameshr** [comment]
If the image src is either loading or throws an error, then display the icon that has been provided as a prop to the image instead of the name (alt) attribute.

**Comment by cschroeter** [comment]
Ok but isn't that more of a feature request than a bug?

**Comment by srameshr** [comment]
Looks like a bug to me as there is conflict between alt (name) attribute and icon attribute and which to render.

**Comment by basantech89** [comment]
@cschroeter can I work on this?

**Comment by brandonarbini** [comment]
> It also seems that the `alt` attribute is being added to the `span` wrapping the `img`.

I now see the note about `name` being used as the `alt`. I still think we should be able to specify `alt` directly.
