### ISSUE TITLE
Drawer examples

### ISSUE THREAD

**Issue by Beetix** [chakra-ui/chakra-ui#4033]
# 🐛 Bug report
In the [doc's examples](https://chakra-ui.com/docs/overlay/drawer) the `DrawerOverlay` is in a self-closing tag but in [the example on npm](https://www.npmjs.com/package/@chakra-ui/modal#usage-2) the `DrawerOverlay` wraps the `DrawerContent`. Which is correct?

## 🧭 Possible Solution

My guess is that the `DrawerOverlay` should wrap the `DrawerContent`

**Comment by with-heart** [comment]
The docs are correct. We haven't updated the individual package READMEs in quite some time lol

**Comment by Beetix** [comment]
> The docs are correct. We haven't updated the individual package READMEs in quite some time lol

Ah ok. I've been trying out [react-swipeable](https://github.com/FormidableLabs/react-swipeable) and swipes on the Drawer weren't detected if I didn't wrap the content in the `DrawerOverlay` like so:
```js
const handlers = useSwipeable({
  onSwipedLeft: () => onClose()
);

return (
  <Drawer placement={placement} onClose={onClose} isOpen={isOpen}>
    <DrawerOverlay {...handlers}>
      <DrawerContent >
        <DrawerHeader borderBottomWidth="1px">Header</DrawerHeader>
        <DrawerBody>
          <p>Some contents...</p>
        </DrawerBody>
      </DrawerContent>
    </DrawerOverlay>
  </Drawer>
);
```
