### ISSUE TITLE
Drawer sizes larger than XL do not work properly

### ISSUE THREAD

**Issue by damianricobelli** [chakra-ui/chakra-ui#4034]
# 🐛 Bug report

According to the Chakra documentation, the Drawer section specifies that the size property has values ​​of "sm" | "md" | "lg" | "xl" | "2xl" | "full" | "xs" | "3xl" | "4xl" | "5xl" | "6xl". [https://chakra-ui.com/docs/overlay/drawer](url)
When I resize the Drawer between 2xl and 6xl, the size always ends up being full screen.

## 💥 Steps to reproduce

1. Go to the link to reproduce the bug in Codesandbox.
2. Modify the size of the Drawer with values ​​from 2xl to 6xl.
3. You can see the size is equal to full

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/fervent-neumann-rxrsc?file=/src/index.tsx

## 🧐 Expected behavior

The expected behavior when changing the prop size of the Drawer to 2xl, 3xl, ..., 6xl, is that the size varies but does not reach the full size

## 🧭 Possible Solution

Add custom sizes to the Drawer

## 🌍 System information

Chakra UI --> 1.6.2
Browser --> Chrome Versión 90.0.4430.212 
Operating System --> Windows 10

**Comment by dusty** [comment]
I was just reviewing this behavior today as well.  We also have custom sizes in our theme that we'd like to pass through.  It looks like they are hardcoded to the following

```
function getSize(value: string) {
  if (value === "full") {
    return { dialog: { maxW: "100vw", h: "100vh" } }
  }
  return { dialog: { maxW: value } }
}

const sizes = {
  xs: getSize("xs"),
  sm: getSize("md"),
  md: getSize("lg"),
  lg: getSize("2xl"),
  xl: getSize("4xl"),
  full: getSize("full"),
}
```

**Comment by dusty** [comment]
Custom sizes can be added to the theme.
```
components: {
    Drawer: {
      sizes: {
        ...defaultTheme.components.Drawer.sizes,
        '2xl': { dialog: { maxW: '8xl' } }
      }
    }
  }
```
