### ISSUE TITLE
Event Handler type is wrong when using `as` prop

### ISSUE THREAD

**Issue by dlindenkreuz** [chakra-ui/chakra-ui#4037]
# 🐛 Bug report

When using the `as` prop, the event handler TypeScript types are wrong:

```typescript
const btn = <Button as="a" href="//chakra-ui.com" onClick={(e) => e.currentTarget.href} />

// Property 'href' does not exist on type 'EventTarget & HTMLButtonElement'.ts(2339)
```

## 💥 Steps to reproduce

1. Use any Chakra UI component, turn it into a `HTMLAnchorElement` using the `as` prop
2. Observe that event handlers have a wrong type: for example, `React.MouseEventHandler<HTMLButtonElement>`

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/sharp-driscoll-b4ic6?file=/src/index.tsx

## 🧐 Expected behavior

Event handlers should use the correct HTML element type as event target type that is defined by the `as` prop.

## Workaround

```typescript
const handleClick: React.MouseEventHandler<HTMLAnchorElement> = (e) => {
  console.log(e.currentTarget.href);
};
const btn = (
  <Button
    as="a"
    href="//chakra-ui.com"
    onClick={
      handleClick as unknown as React.MouseEventHandler<HTMLButtonElement>
    }
  />
);
```

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |    v1.6.2        |
| TypeScript        |    v4.2.x        |
| Browser          |    Safari 14.1    |
| Operating System |   macOS 10.15  |

**Comment by with-heart** [comment]
We discussed this in our team meeting and we'd like to try to resolve this in `2.0`. The truth though is that typing `as` correctly is **hard**, so we can't make any guarantees.
