### ISSUE TITLE
Collapse Transition not working with `unMountOnExit`

### ISSUE THREAD

**Issue by tpck** [chakra-ui/chakra-ui#4039]
# 🐛 Bug report

The collapse transition isn't working correctly on version 1.6.2

## 💥 Steps to reproduce

1. Go to the below sandbox
2. Collapse animation that displays a chart is working (version 1.6.0)
3. Switch to 1.6.2
4. Collapse animation that displays a chart is not displaying the chart animation anymore

## 💻 Link to reproduction

https://codesandbox.io/s/chakra-collapse-wxi75?file=/src/App.js

## 🧐 Expected behavior

The collapse functionality should work the same as version 1.6.0

**Comment by with-heart** [comment]
@lazarnikolov94 is going to investigate if this is the result of a change in `framer-motion`.

**Comment by lazarnikolov94** [comment]
Upon further investigation I found out that [this line](https://github.com/chakra-ui/chakra-ui/blob/main/packages/transition/src/collapse.tsx#L128) might be causing the issue. If we don't override the `display` property the animation executes smoothly. I've opened a fix proposition PR at #4069.
