### ISSUE TITLE
Accordion renders invalid IDs on SSR (Next.js)

### ISSUE THREAD

**Issue by robinzachmann** [chakra-ui/chakra-ui#4044]
# 🐛 Bug report

The Accordion component renders invalid IDs on SSR. Instead of counting the IDs for the accordion button and panel, the SSR-output shows `id="accordion-button-undefined"` and `id="accordion-panel-undefined"`.   
After the first render the IDs change to their correct value, like `id="accordion-button-1"`.

## 💥 Steps to reproduce

1. Open Sandbox in an new window
2. Disable JavaScript to see SSR output
3. Open the element inspector
4. Inspect the DOM elements of `<AcordionButton>` and `<AccordionPanel>` 

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/accordion-nextjs-issue-wrqym?file=/pages/index.tsx
Open Next.js page in new window: https://wrqym.sse.codesandbox.io/

## 🧐 Expected behavior

The IDs should be incremented correctly on client __and__ server. 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.6.2         |
| Browser          |   Chrome 90.0.4430.212 (arm64)  |
| Operating System |    macOS (Catalina)        |

## 📝 Additional information

Example SSR output of one accordion item

```html
<div className="chakra-accordion__item css-17mg6aq">
  <h2>
    <button
      type="button"
      id="accordion-button-undefined"
      aria-expanded="false"
      aria-controls="accordion-panel-undefined"
      className="chakra-accordion__button css-1rboc9n"
    >
      <div className="css-1eziwv">Section 1</div>
      <svg
        viewBox="0 0 24 24"
        focusable="false"
        className="chakra-icon chakra-accordion__icon css-186l2rg"
        aria-hidden="true"
      >
        <path
          fill="currentColor"
          d="M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z"
        ></path>
      </svg>
    </button>
  </h2>
  <div
    className="chakra-collapse"
    style="overflow:hidden;display:none;opacity:0;height:0px"
  >
    <div
      role="region"
      id="accordion-panel-undefined"
      aria-labelledby="accordion-button-undefined"
      className="chakra-accordion__panel css-1hb5ode"
    >
      ...
    </div>
  </div>
</div>
```

**Comment by with-heart** [comment]
This is likely a result of replacing `@reach/use-id` with an internal copy that fixed an issue. We'll investigate using `@reach` again and letting them handle the maintenance 😆
