### ISSUE TITLE
Who is using Chakra UI? ⚡️

### ISSUE THREAD

**Issue by segunadebayo** [chakra-ui/chakra-ui#405]
Hey Chakra people 😄,

If you or your company is using Chakra UI in production, please leave a comment below so we can mention you in the new README and documentation website.

Here's what your comment should look like:

**Company:** [Put company name] 
**Permission to use our logo in our readme/website:** [Yes or No]
**Project type and size:** [Just a little description of the project & how Chakra helped]
**Project link:** [If public, attach a link]

Thank you

**Comment by franky47** [comment]
**Company**: [@47ng](https://github.com/47ng)
**Permission to use our logo in our readme/website**: Yes
**Project type and size**: Personal website/blog, some prototype webapps with Next.js
**Project link**: https://francoisbest.com

❤️

**Comment by KenzoBenzo** [comment]
**Company**: BeFreakingKind apparel
**Permission to use our logo in our readme/website**: [Yes](https://media.graphcms.com/ck7oney0ndq660b209ym6baaa)
**Project type and size**: BFK is an eCommerce site built with Chakra, Stripe, Sendgrid, Printful, GraphCMS, and Netlify. It's a small-sized application that's just getting started. Using Chakra allowed the project to focus on the goal rather than the important nuances of aesthetics and accessibility.
**Project link**: [BeFreakingKind.com](https://BeFreakingKind.com)

---

**Company**: Makenna Smutz Freelancing
**Permission to use our logo in our readme/website:** Yes
**Project type and size**: This is my personal portfolio that I really wanted to play with dark mode.
**Project link**: [Kenna.xyz](https://kenna.xyz)

**Comment by JClackett** [comment]
Company: Common Grounds
Permission to use our logo in our readme/website: Yes
Medium-sized platform for booking co-working spaces worldwide. Chakra allowed us to launch our product super fast! 😃 Next.js, TypeScript, GraphQl, Stripe, Apollo Server, React-native + Expo
Project link: https://www.commongrounds.co/spaces

Chakra has helped so much, now just waiting for React native support so our entire frontend can use Chakra ❤️

**Comment by junaid33** [comment]
Company: Openship
Permission to use our logo in our readme/website: Yes
Project type and size: Opensource.builders allows you to find open-source alternatives to commercial apps. It's used building Chakra-UI and TinaCMS. The code is also open-sourced here: https://github.com/junaid33/opensource.builders.
Project link: https://opensource.builders

Thanks for creating an amazing project!

**Comment by tylerjbainbridge** [comment]
Company: [Cataloged](https://cataloged.co/)
Permission to use our logo in our readme/website: Yes
Project type and size: A knowledge base tool for Links, Files, Notes, Contacts, etc. The company is just me at the moment, but hoping to launch/fundraise soon!
Project link: https://cataloged.co/

![image](https://user-images.githubusercontent.com/13852400/77257978-0972f880-6c4e-11ea-95cd-e5d8867aaaf5.png)

**Comment by bs32g1038** [comment]
**Company: @bs32g1038**
**Permission to use our logo in our readme/website:** Yes
**Project type and size:** Personal website/blog. You can build a similar website by this template quickly. Chakra-UI make our coding more comfortable and fast! 👍 Other libraries such as Next.js, TypeScript, Nestjs, ... also used on Project.

**Project link:** https://www.lizc.net - https://github.com/bs32g1038/node-blog
```js
 I like ChakraUI very much. It’s so excellent! Thank you for your hard work.
```
![](https://github.com/bs32g1038/node-blog/blob/master/docs/images/home.png?raw=true)

**Comment by Haja-andri** [comment]
Company: Codelify
Permission to use our logo in our readme/website: Yes
Project type and size: Codelify.dev is a code snippets library for developers to Store, Manage, Retrieve and Share code snippets. Chakra UI helped us focusing on the app logic, while style having beautiful/accessible UI to ship Codelify during a 2 days Hackathons.
Project link: https://codelify.dev

**Comment by breytex** [comment]
**Company:** Need-Mask.com non-profit
**Permission to use our logo in our readme/website:** yes
**Project type and size:** 
We are a team of 6 ppl and created this listing app to connect buyers and suppliers of protective masks and other medical, covid19 relevant gear to fight cutthroat prices. Chakra helped us create this fully-fledged platform in under 10 days. IE11 support is one thing that is missing for us and some breakpoints were glitching on SSR, but everything else was a blast to use. Will use chakra again for my next project!
**Project link:** https://www.need-mask.com/

**Comment by dev-cj** [comment]
Company: (Personal Project by www.devcj.in )
Permission to use our logo in our readme/website: yes
Project type and size: A visualization web app where I used the amazing Chakra UI,
Project description: Visualize corona stats from around the world with downloadable charts to use in projects/research. I will use chakra again for my next project. Thank you so much for your hard work!❤
Project link: https://dev-cj.github.io/visualize-corona/

**Comment by martinpengellyphillips** [comment]
**Company:** Hashbrown
**Permission to use our logo in our readme/website:** Yes
**Project type and size:** A fast capacity planner for team goals. This is a small side hustle to solve a problem we encounter in our jobs, and for which most existing tools seem too light or too heavy 😄. Evaluated a bunch of UI toolkits and Chakra UI was the one that just felt _fun_ to use - the right balance of getting things done, guidance on best practices and the flexibility to adapt as needed. Great community also 🙌 
**Project link:** https://gethashbrown.com/

**Comment by remorses** [comment]
Company: Dokz
Permission to use our logo in our readme/website: Yes
Project type and size: Documentation generator built with chakra components!
Project link: https://github.com/remorses/dokz

**Comment by davidli3100** [comment]
**Company**: Donations Revealed
**Permission to use our logo in our readme/website**: yes
**Project type and size**: Corporations have made large anti-racism donations recently - making many people feel as if their donations are insignificant. We made this web app to scale it down to the perspective of an average household to encourage them to make the same relative impact as any given corporation. We currently have over 70 corporations in our database, and will be adding more soon!
**Project link**: [donations.exposed](https://donations.exposed)

**Comment by nfm** [comment]
Company: UsabilityHub
Permission to use our logo in our readme/website: Yes
Project type and size: UsabilityHub is a remote user research platform that takes the guesswork out of design decisions by validating them with real users. We're actively rolling out Chakra in our web app and are very excited for the TS rewrite :tada: 
Project link: https://usabilityhub.com

**Comment by feross** [comment]
**Company:** Virus Cafe
**Permission to use our logo in our readme/website:** Yes
**Project type and size:** I built Virus Cafe to help you make a friend in 2 minutes. You're matching over video or voice for a 1-on-1 chat with a random stranger. The conversation lasts 2 minutes (with an "extend" button if the convo is good). My goal is to help people make meaningful connections with strangers. So far we've had 50,000 users try the app.
**Project link:** https://virus.cafe

Chakra UI has been a joy to use throughout this project!

**Comment by DavidJFelix** [comment]
**Company**: NullServe
**Permission to use our logo in our readme/website**: Yes
**Project type and size**: I've been building NullServe for awhile now and originally it consisted of a Gasby marketing site and CRA site, each using Tailwind CSS for portions of it in different ways. I found Chakra really easy to use within the React ecosystem and I was able to eliminate a large amount of Tailwind-react integration that was present in each app. Chakra also helped ease the pain of creating my own component library so that the look and feel of both the marketing site and application site match.
**Project link**: https://nullserve.com

**Comment by mwood23** [comment]
**Company:** Wave Snippets
**Permission to use our logo in our readme/website:** Yes
**Project type and size:** Wave snippets gives you the ability to create gorgeous animated snippets to share with the world. This is a small product I built to help people learn code through motion.
**Project link:** https://www.wavesnippets.com/

If you'd be open to converting some of the readme to Wave Snippets just say the work and I'll do it!

**Comment by godwinbenson** [comment]
**Company:** Tuteria
**Permission to use our logo in our readme/website:** Yes
**Project type and size:** We re-designed our landing page and onboarding flow for students looking to join our group classes online and offline. Chakra-UI was incredibly helpful in implementing these designs with React very fast, and easily. It was easy to incorporate responsiveness and ensure a consistent layout across all components without having to create my own base component library. We couldn't have pulled this off fast without Chakra-UI. All thanks to the Chakra-UI team, and especially to Segun Adebayo for this amazing work.
Project link: https://www.tuteria.com/classes/IELTS/IELTSProgram

**Comment by markjackson02** [comment]
![image](https://user-images.githubusercontent.com/35121685/91660831-1bcb4b00-eaa6-11ea-87cc-249c41399507.png)

**Company:** Slow TV Map
**Permission to use our logo in our readme/website:** Yes
**Project type and size:** A map of Slow TV videos from YouTube. Components used from Chakra include Modal, Buttons, ColorMode, Radio Buttons, Input, and Toast
**Project link:** https://slowtvmap.com

**Comment by MirzayevFarid** [comment]
![logo-midnight@3x](https://user-images.githubusercontent.com/29518613/91822325-ab106400-ec48-11ea-8bdb-a56ed1ce3ca9.png)

Company: [Radity](https://radity.com/)
Permission to use our logo in our readme/website: Yes
Project type and size:  We develop digital products and build web and mobile applications (20 Team members)

**Comment by gparuthi** [comment]
Company: Arboreum
Permission to use our logo in our readme/website: Yes
Project type and size: A small MVP for a fintech app.
Project link: https://arboreum.dev

**Comment by timshingyu** [comment]
Company: TGAV
Permission to use our logo in our readme/website: Yes
Project type and size: Kickstart is next.js the boilerplate for building apps fast. We using Chakra UI for building up our UI components.
Project link: https://kickstart.app

**Comment by dsumer** [comment]
![logo-mail-template](https://user-images.githubusercontent.com/4418879/93633489-59f5c380-f9ef-11ea-9fc5-81c7474c67d3.png)
**Company:** Project by @anki247 and @dsumer
**Permission to use our logo in our readme/website:** Yes!
**Project type and size:** We've just launched TrueQ, our new developer platform, so we're at the very beginning. We're using Chakra UI to build our UI and we love it as it allows us to develop a high quality product very fast
**Project link:** https://trueq.io

**Comment by paambaati** [comment]
![Logo Full purple](https://user-images.githubusercontent.com/5381764/93910066-321f9c00-fd1e-11ea-87ec-dd332455e0fc.png)

[Media Kit (with SVG logos with our 2 primary brand colours)](https://github.com/chakra-ui/chakra-ui/files/5262795/wiz-logos-2020.zip)

**Company**: Wiz
**Permission to use our logo in our readme/website**: Yes
**Project type and size**: Wiz is a digital freight forwarder based out of Chennai, India. Wiz is a months-old startup aiming to disrupt the freight forwarding space by offering first-class technology-based solutions for freight & logistics. I had a lot of fun building our platform with Chakra-UI, and I was able to get quickly productive and launch the initial version of our platform (it had a full booking experience, an admin-only portal for managing customer accounts & their bookings, live-tracking and document management) in only ~3 months!
**Project link**: https://wizfreight.com/

**Comment by MA-Ahmad** [comment]
Company: Codenya Studio
Permission to use our logo in our readme/website: Yes
Project type and size: Personal website to show my work and experience.
Project link: https://mahmad.me

Big fan of ChakraUI ❤️

**Comment by sumitngupta** [comment]
Company: DoubleLoop
Permission to use our logo in our readme/website: [Yes](https://uploads-ssl.webflow.com/5e548d3db0467d0ba8d90988/5e56148f24830b710a09c324_logo-white.png)
Project type and size: SaaS product to enable companies to track product iterations and assess the results of them. We recently rebuilt the entire product from scratch and Chakra was instrumental in relaunching fast and actually improve the overall design. 
Project link: [doubleloop.app](https://doubleloop.app)

**Comment by maxkostinevich** [comment]
Company: [maxkostinevich](https://maxkostinevich.com/)
Permission to use our logo in our readme/website: Yes
Project type and size: Collection of pre-made UI components to use in admin dashboard.
Project link: [Github Repo](https://github.com/maxkostinevich/Chakra-UI-Admin-Dashboard-Template)

**Comment by locona** [comment]
Company: https://3-shake.com/
Permission to use our logo in our readme/website: Yes
Project type and size: Reckoner is a cloud-based ETL / data pipeline service.
By integrating and linking all kinds of data such as databases, storage applications, etc., we contribute to business transformation utilizing data.
Project link: https://reckoner.io/

**Comment by Prottoy2938** [comment]
Project: Cipher Delta
Permission to use our logo in our readme/website: Yes
Project type: A web application that helps encode and decode plain content. Most of the front-end component used on the application were from Chakra-UI. It also helped integrate a dark mode feature seamlessly.
Project link: http://cipher-delta.edrini.xyz/

**Comment by Prottoy2938** [comment]
Project: A Converter Tool
Permission to use our logo in our readme/website: Yes
Project description: An online tool that helps change the color of an SVG using CSS filter 
Project link: https://change-svg-color.edrini.xyz/

**Comment by cereallarceny** [comment]
Company: OpenMined
Permission to use our logo in our readme/website: Yes
Project type and size: Chakra powers our component system OMUI (OpenMined UI), which in turn is used in all of our various web applications. OMUI sits [within a monorepo](https://github.com/OpenMined/openmined) of other websites managed by NX.
Project link: https://openmined.org
About Project: OpenMined is an open-source community whose goal is to make the world more privacy-preserving by lowering the barrier-to-entry to private AI technologies.

![horizontal-primary-light](https://user-images.githubusercontent.com/1297930/99423145-2d2f3100-28f8-11eb-9f43-d4b810267164.png)
