### ISSUE TITLE
[Feature Request] Export non-hook utilities

### ISSUE THREAD

**Issue by jesstelford** [chakra-ui/chakra-ui#4055]
# 🚀 Feature request

As well as exported hooks `useToken`, `useBreakpoint`, etc, also export utilities that are regular functions (ie; non-hooks); `getToken`, `getBreakpoint`, etc.

## 🧱 Problem Statement / Justification

The hooks ChakraUI exports are fantastic (`useBreakpoint`, `useToken`, etc), however they can only be used within a rendering context, and worse can never be used in a conditional branch within that rendering context (see: [Rules Of Hooks](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level)).

I've recently found myself in need of calling `useToken` and `useBreakpoint` within a loop (not a react component rendering loop), but can't because it violates the hooks rule _"Don’t call Hooks inside loops"_.

## ✅ Proposed solution or API

Refactor the existing hooks to look like so (example taken [from here](https://github.com/chakra-ui/chakra-ui/blob/75edcf41e7ff4acc2569f2169949063c164d8f6e/packages/system/src/hooks.ts)):

```diff
 export function useToken<T extends StringOrNumber>(
   scale: string,
   token: T | T[],
   fallback?: T | T[],
 ) {
   const theme = useTheme()
 
+  return getToken(theme, scale, token, fallback)
+}
+
+export function getToken<T extends StringOrNumber, U extends object = Dict>(
+  theme: WithCSSVar<U>
+  scale: string,
+  token: T | T[],
+  fallback?: T | T[],
+) {
   if (Array.isArray(token)) {
     let fallbackArr: T[] = []
     if (fallback) {
       fallbackArr = Array.isArray(fallback) ? fallback : [fallback]
     }
 
     return token.map((token, index) => {
       const path = `${scale}.${token}`
       return get(theme, path, fallbackArr[index] ?? token)
     })
   }
 
   const path = `${scale}.${token}`
   return get(theme, path, fallback ?? token)
 }
```

This maintains existing functionality while avoiding duplication.

Usage could look something like this (contrived example):

```javascript
const Thing = (props) => {
  const theme = useTheme()
  for (i = 0; i < 100; i++) {
    getToken(theme, 'space', 9)
  }
  return <div {...props} />
}
```

## ↩️ Alternatives

For now, I'm copy+pasting ChakraUI internals which isn't so great 

## 📝 Additional Information

Not all hooks make sense to modify. For example, `useTheme()` _must_ be used as a hook because it depends on `useContext`, but I'd hazard that the vast majority of hooks could be refactored to support a non-hook version too.

**Comment by jesstelford** [comment]
Please keep this open @stalebot

**Comment by jatin33** [comment]
@with-heart @segunadebayo let me know if I can pick this up? How would we go about doing this as a lot of hooks might have these utilities?
Do we have an existing list of such hooks?

**Comment by segunadebayo** [comment]
To reduce our API surface and avoid breaking changes, we won't be doing this for now.
