### ISSUE TITLE
Allow to use `usePortal` on the Menu component.

### ISSUE THREAD

**Issue by santialbo** [chakra-ui/chakra-ui#406]
When the menu trigger is within an overflown element it's necessary to render the menu using a portal in the same way it's already possible with the `Popover` component.

**Describe the solution you'd like**
Same interface as the Popover component, just another prop `usePortal: boolean;`

**Describe alternatives you've considered**
I tried implementing myself by passing the prop all the way down to the Popper component but I got an error that I was not sure how to fix with the `focusableItems`

**Comment by segunadebayo** [comment]
Hi @santialbo,

Do you have a codesandbox replica for this issue? I'd like to take a look.

Thanks

**Comment by santialbo** [comment]
This is a feature request, I just tried changing [this line](https://github.com/chakra-ui/chakra-ui/blob/06b65dd4117d8c1207d3ed80f4932d8c2b0d7dee/packages/chakra-ui/src/Menu/index.js#L317) but the stories would not work, they would throw an error because [the effect in L51](https://github.com/chakra-ui/chakra-ui/blob/06b65dd4117d8c1207d3ed80f4932d8c2b0d7dee/packages/chakra-ui/src/Menu/index.js#L51-L61) would be executed before `menuRef` has a value.

**Comment by bjgrosse** [comment]
@segunadebayo here is a sandbox that reproduces this. If you don't set usePortal=true on the MenuList, then the menu gets cut off. If you do usePortal then you get an error about the focusableItems. focusableItems is null at the time of opening the menu.

Turning autoSelect off gets past this error, but then other things don't work such as the closeOnBlur. Seems that a various number of things need to be changed to allow the portal. 

https://codesandbox.io/s/beautiful-cray-dk9eq

**Comment by bjgrosse** [comment]
It should be noted that the Popover component works fine in this same scenario, and it would be lovely if the Menu could as well.

**Comment by Sebastiansc** [comment]
I'm facing this same issue. It seems that when `usePortal` is true this line here isn't called in the order that's expected https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/Popper/index.js#L144. That line should be called before this https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/Menu/index.js#L52 (as it does when `usePortal` is false).

Since `menuRef` is defined in Popper/index.js#L144, Menu's `useEffect` in L52 doesn't set the focusable items causing auto selection to error out

**Comment by Sebastiansc** [comment]
Open a fix for this. You'd have just to set `container` prop to a valid DOM node e.g.
`<MenuList container={document.body}>`

**Comment by segunadebayo** [comment]
@bjgrosse will look into this as we're working on the next release. Thanks for the PR @Sebastiansc , I'll review it shortly

**Comment by santialbo** [comment]
These seems to have been addressed on the `ts-dev` branch so I'll close this.

**Comment by paambaati** [comment]
For someone still stuck on v0.8.x unfortunately, is there a workaround or a patch for this? Our codebase is quite large and I don't have the resources (yet) to start migrating to 1.x, so I'd appreciate any help here.

**Comment by ajmalhassan** [comment]
@santialbo @segunadebayo Can the PR to fix this issue be merged to v0.8.0 as mentioned by @paambaati , there are large codebases still using v0.8.0 pending migration.

**Comment by felixfbecker** [comment]
I'm a bit confused, I am on 2.6.0 and there is no `usePortal` prop for `<Menu>` or `<MenuList>`. How is Menu intended to be used with a Portal?

**Comment by michaelaflores** [comment]
For anyone else coming to this in the future, I believe the right way as of this writing for v2.8.2 is to wrap `<MenuList>` in a `<Portal>` as the `usePortal` prop isn't a thing anymore. [Docs](https://v2.chakra-ui.com/docs/components/menu/usage#rendering-menu-in-a-portal)
