### ISSUE TITLE
WithCSSVar error

### ISSUE THREAD

**Issue by danchitnis** [chakra-ui/chakra-ui#4068]
# 🐛 Bug report

I am using Snowpack (v3.5.1) with Chakra-ui (v.1.6.2), however there is an error when running `yarn start`:

`Module "undefined" has no exported member "WithCSSVar". Did you mean to use "import WithCSSVar from 'undefined'" instead?`

This error occurs when processing `@chakra-ui/styled-system@1.11.0`

Chakra-ui (v.1.6.1) has no problem.

## 💥 Steps to reproduce

`yarn start`

## 💻 Link to reproduction

N/A

## 🧐 Expected behaviour

Should compile as usual 

## 🧭 Possible Solution

change the Chakra-ui version to 1.6.1

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.6.2         |
| Browser          |      Chrome 90      |
| Operating System |    Win10        |

**Comment by cschroeter** [comment]
Thanks for reporting the issue. 

I'm happy to say that this has already been fixed in https://github.com/chakra-ui/chakra-ui/commit/fd231f720965b505faf5a0d8153366f8989ec9ce
