### ISSUE TITLE
Typescript v4.x.x does not support @chakra-ui/react

### ISSUE THREAD

**Issue by David00154** [chakra-ui/chakra-ui#4070]
After upgrading my typescript to v4.x.x typescript start throwing errors for @chakra-ui/react so i had to step down my typescript version to version ^3.x.x

**Comment by cschroeter** [comment]
Thank you for taking the time to create this issue. Unfortunately, it does not contain all the necessary information we need to work on this issue.

Therefore we have to close this issue. You can create a new issue at any time - please use the corresponding issue template.

Happy hacking ✌️
