### ISSUE TITLE
Popover `enabled` prop not valid / working

### ISSUE THREAD

**Issue by CarterMcAlister** [chakra-ui/chakra-ui#4074]
# 🐛 Bug report

The [Chakra docs for Popover](https://chakra-ui.com/docs/overlay/popover#popover-props) show `enabled` to be a supported prop, but it does not work and shows a Typescript error ```Property 'enabled' does not exist on type```

## 💥 Steps to reproduce

1. Build a popover with Chakra
2. Add the enabled prop with a boolean condition

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/great-cray-rw3xw

## 🧐 Expected behavior
* Popover does not open when `enabled` is `false`
* Typescript shows `enabled` to be a supported property 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  latest          |
| Browser          |   Chrome         |
| Operating System |  OSX          |

**Comment by cschroeter** [comment]
Thanks for reporting this issue.

This feature will be available with the next release. Due to a mistake the docs have already been updated. I will bring this issue up in our next core meeting.

Thanks buddy.

**Comment by futhr** [comment]
@cschroeter Hi, what release are you referring to? I'm running `@chakra-ui/react v1.6.4` and face the same issue.

Thanks
