### ISSUE TITLE
Invalid hook call, when chakra ui was inside a react component library

### ISSUE THREAD

**Issue by tashikomaaa** [chakra-ui/chakra-ui#4077]
the problem was, i build a library of component, i want to add chakra ui inside for use it as my ui lib.
but when i put chakra in my component, i get an invalid hook call error.

any ideas ?

**Comment by with-heart** [comment]
Hi @tashikomaaa! We'd love to help but unfortunately this issue doesn't give us any of the things we need to understand your problem. Please open a new issue and fill out the template!
