### ISSUE TITLE
OpenChackra UI Went Down

### ISSUE THREAD

**Issue by JetDeveloping** [chakra-ui/chakra-ui#408]
Open Chackra went down today at approx 2:15 (PST) 3-4 minutes ago today. Or at least the server closes to the West North American side!

Another idea to prevent work being lost, is to have a login system, if possible. 

Thanks

**Comment by segunadebayo** [comment]
Hi @JetDeveloping,

I think the best place to open this issue is OpenChakra's repo. Kindly go here: https://github.com/premieroctet/openchakra

Thanks
