### ISSUE TITLE
Add an option to disable drawer overlays completely

### ISSUE THREAD

**Issue by ostrebler** [chakra-ui/chakra-ui#4081]
# 🚀 Feature request

My current use case requires me to use the `Drawer` as a retractable settings panel for an interactive animation that plays on the main screen. But the animation should remain interactive even with the `Drawer` being open.

I set `closeOnOverlayClick` to `false` and didn't render any `DrawerOverlay` but there is still one, the main screen is unresponsive to pointer events.

## 🧱 Problem Statement / Justification

I think this would be a valuable addition as it's not the first time I run into such a use case (but it's the first time with Chakra).

## ✅ Proposed solution or API

Maybe add an `overlay` boolean prop, that can be set to `false` and is `true` by default.

## ↩️ Alternatives

I tried playing around with the props, but nothing seemed to do the trick.

**Comment by mcha-dev** [comment]
You might be able to achieve what you're after with [Slide-transition](https://chakra-ui.com/docs/components/transitions#slide-transition)

**Comment by segunadebayo** [comment]
Hi @ostrebler,

You can a couple of options here:
- Consider using the Slide transition as suggested by @mcha-dev
- Pass `blockScrollOnMount=false` or/and `trapFocus=false`
- Consider building one using framer-motion's API

We intend to build this component you're describing (SideSheet) in the next major. For now, please consider those options.

Thank you
