### ISSUE TITLE
Allow the styling of Menucomponents to be changed based on the menu position.

### ISSUE THREAD

**Issue by jacobpstorefeeder** [chakra-ui/chakra-ui#4086]
When using a menu and having the `MenuList` component toggled on/off, if the menu is near the edge of the screen, it will of course reposition. So if the menu would overflow the viewport to the right, then the menu will position itself to align to the right instead of to the left. This all works as expected, but there is currently no way to actually target the List if it's positioned to the right.

I have an arrow placed (with a border) above the menu pointing to the target element when it is shown. This is positioned to the left of the box, but when the menu repositions to align to the right, the arrow no longer is in the correct place. Currently i cannot see a way to make this align to the right. There is a wrapper div in the dom which surrounds the MenuList. Any props provided to the MenuList react component, are applied to the MenuList div, not to the wrapper and i can't see a way to target the wrapper. IMO this is a very necessary feature, as any styling based on the position of the menu cannot work without it.

Red is where the trigger button is.
![image](https://user-images.githubusercontent.com/44572986/119532117-7f0bb480-bd7c-11eb-935f-8d3b62a32f71.png)

**Comment by cschroeter** [comment]
Thank you for taking the time to create this issue. Unfortunately, it does not contain all the necessary information we need to work on this issue.

Therefore we have to close this issue. You can create a new issue at any time - please use the corresponding issue template.

Happy hacking ✌️
