### ISSUE TITLE
Bundle size considerations

### ISSUE THREAD

**Issue by mtt87** [chakra-ui/chakra-ui#4088]
I was doing some testing and I noticed that just by adding the `<ChakraProvider>` and using one `<Text>Hello world</Text>` would increase a next.js bundle by `38kb` and I was wondering if there is something wrong, perhaps with the way the library is bundled and published?

In my ignorance it feels like something with tree-shacking is not working properly and more stuff that's not used is being included in the next.js bundler.

These days I'm trying to understand more about how different bundlers work so I don't have a proposed solution yet but I'm curious to understand if you are aware of this and if you already thought about ways to improve this?

Thank you 🙏 

## 📝 Additional Information

Just as a reference this is the comparison of the build outputs, check the `First Load JS shared by all` which increases by `38kb`

Without chakra
```
Page                             Size     First Load JS
┌ ○ /                            268 B          63.2 kB
├   /_app                        0 B            62.9 kB
└ ○ /404                         3.06 kB          66 kB
+ First Load JS shared by all    62.9 kB
  ├ chunks/framework.56721e.js   42 kB
  ├ chunks/main.71948a.js        19.4 kB
  ├ chunks/pages/_app.0da268.js  542 B
  └ chunks/webpack.2a5a41.js     952 B
```
With chakra
```
Page                             Size     First Load JS
┌ ○ /                            5.25 kB         107 kB
├   /_app                        0 B             101 kB
└ ○ /404                         3.08 kB         105 kB
+ First Load JS shared by all    101 kB
  ├ chunks/framework.56721e.js   42 kB
  ├ chunks/main.cdc763.js        19.5 kB
  ├ chunks/pages/_app.9685f2.js  38.9 kB
  └ chunks/webpack.1d8564.js     1.04 kB
```

**Comment by aboveyunhai** [comment]
duplicate of #2693
PR relates #3488
I believe it's still on the way.

**Comment by mtt87** [comment]
@aboveyunhai thanks, so if I understand correctly it's all related to the huge size of `framer-motion`.
I'm gonna close the issue then and hopefully that PR will be merged soon!
