### ISSUE TITLE
Question: How to access media query state?

### ISSUE THREAD

**Issue by sinclairnick** [chakra-ui/chakra-ui#409]
I've tried looking for this answer on the styled system docs to no avail, but is there a way to access the current media query state.

I'm aiming to conditionally render components based on the media state - e.g. render an accordion on mobile and a list on desktop.

Thanks

**Comment by segunadebayo** [comment]
Hi @sinclairnick,

We're looking into this for the next release. At the moment, we don't have a package to help with that but there 2 options:
- Use `display` prop and pass responsive values to it. `display=[none, "block"]`
- Use this package this match-media package from `theme-ui`. It has a hook to help you manage breakpoints.
Link: https://github.com/system-ui/theme-ui/tree/master/packages/match-media

Hope you find this useful.

Thanks.

**Comment by coodoo** [comment]
@segunadebayo Out of curiosity, have you figured out how to do this natively with chakra instead of installing dependencies?

**Comment by coodoo** [comment]
@segunadebayo  Ended up I wrote this minimum pieces based on `theme-ui/match-media`, hope that helps.

```js
const useRWD = ( values ) => {
	const theme = useTheme()

	// SSR - early bailout
	if( typeof window === 'undefined') return [values[0], 0]

	//
	const getIndex = () => {

		if( typeof window === 'undefined') return 0

	  const idx = theme.breakpoints.filter(
	    b => window.matchMedia(`screen and (min-width: ${b})`).matches
	  ).length

	  return idx
	}

	const [index, setIndex] = useState(getIndex())

	useEffect(() => {
	  const onResize = () => setIndex(getIndex())
	  window.addEventListener('resize', onResize)
	  return () => window.removeEventListener('resize', onResize)
	}, [])

  const payload = values[index >= values.length ? values.length - 1 : index]

  return [payload, index]
}
```

**Comment by segunadebayo** [comment]
Hi @coodoo,

We have a `useMediaQuery` hook that can help you achieve it easily. I'll take out some time today to add that `useResponsiveValue` hook since it might be useful.

Your solution looks good as well. We'll take it into consideration.

Thank you!

**Comment by coodoo** [comment]
Sounds good, where to find that `useMediaQuery` in current cocebase?

**Comment by segunadebayo** [comment]
It's here: https://github.com/chakra-ui/chakra-ui/blob/dev-ts/packages/hooks/src/useMediaQuery.ts
