### ISSUE TITLE
TS: Chakar types for foundations - fonts, borders etc.

### ISSUE THREAD

**Issue by nidhi-tandon** [chakra-ui/chakra-ui#4090]
# 🐛 Bug report

Chakra does not export types for foundations like typography, border, radii etc.

## 💥 Steps to reproduce

Use case :
Extend Chakra's default theme and override it

App.tsx
```
import { extendTheme, ChakraProvider, Theme } from '@chakra-ui/react';
import customTheme from './theme';

const theme: Theme = extendTheme(customTheme);
```

theme.ts 
```
const fontSize = {
  xxxs: '.5rem',
  xxs: '.625rem',
  xs: '.75rem',
  sm: '.875rem',
  md: '1rem',
};

export default {
  fontSize,
};

```

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/hardcore-moser-4qw4y?file=/src/App.tsx

## 🧐 Expected behavior

```
import { FontType } from '@chakra-ui/react'

const fontSize: FontType = {
  xxxs: '.5rem',
  xxs: '.625rem',
  xs: '.75rem',
  sm: '.875rem',
  md: '1rem',
};

export default {
  fontSize,
};
```

## 🧭 Possible Solution

Export types for typography tokens.
Could see Typography interface [here](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/theme.types.ts#L88) but its not being exported. Also it wont serve the purpose for individual tokens like fonts, fontWeights etc. 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       1.6.2     |
| Browser          |            |
| Operating System |            |

## 📝 Additional information

Checked[ theme typings](https://chakra-ui.com/docs/theming/advanced#theme-typings) via @chakra-ui/cli. This also doesnt solve the purpose as it gives support for autocomplete but not to define the type of a token.

Lmk if anything is missed. Any help will be appreciated.

**Comment by TimKolberger** [comment]
If you like to reference a theme property type you can use 

```ts
import { ChakraTheme, extendTheme } from '@chakra-ui/react'

type FontSizes = ChakraTheme['fontSizes']

const fontSizes: FontSizes = {
  xxxs: '.5rem',
  xxs: '.625rem',
  xs: '.75rem',
  sm: '.875rem',
  md: '1rem',
};

const customTheme = extendTheme({ fontSizes })
type MyCustomThemeType = typeof customTheme
```

**But** I'd recommend not to narrow the type for `fontSizes` with `const fontSizes: FontSizes = ...`, as this would remove the autocomplete when accessing the customTheme properties.

```ts
// const fontSizes: ChakraTheme['fontSizes'] = 
const fontSizes = {
  xxxs: '.5rem',
  xxs: '.625rem',
  xs: '.75rem',
  sm: '.875rem',
  md: '1rem',
};

const customTheme = extendTheme({ fontSizes })
const mySize = customTheme2.fontSizes.xxxs
                                     ^ - Try autocomplete here with and without `ChakraTheme['fontSizes']` to see the difference
```

Please note that the type `Theme` describes the Chakra UI default theme.
The type `ChakraTheme` describes how a chakra theme looks like.
I think of the type `ChakraTheme` as the interface and the type `Theme` as the "implementation" of a chakra theme.
