### ISSUE TITLE
Export 'import_types' is not defined in module

### ISSUE THREAD

**Issue by blechatellier** [chakra-ui/chakra-ui#4092]
# 🐛 Bug report
I'm running into a `Uncaught SyntaxError: Export 'import_types' is not defined in module` error using vite (2.3.4) boilerplate code with the latest version (1.6.2) of @chakra-ui/react, it works ok with the previous version (1.6.1).

![image](https://user-images.githubusercontent.com/437646/119617872-8d041880-be02-11eb-8b8f-9672a077d377.png)

**Comment by segunadebayo** [comment]
Thanks for reporting the issue.

I'm happy to say that this has already been fixed. I'll publish a patch shortly.
