### ISSUE TITLE
Provide a parameter for the Menu position to the render method of Menu.

### ISSUE THREAD

**Issue by jacobpstorefeeder** [chakra-ui/chakra-ui#4093]
# 🚀 Feature request

Provide a param to the render function inside `Menu` stating the position of the Menu component, whether it has repositioned to the left, right, top or bottom.

## 🧱 Problem Statement / Justification

When using a menu and having the MenuList component toggled on/off, if the menu is near the edge of the screen, it will of course reposition. So if the menu would overflow the viewport to the right, then the menu will position itself to align to the right instead of to the left. This all works as expected, but there is currently no way to actually target the List if it's positioned to the right.

I have an arrow placed (with a border) above the menu pointing to the target element when it is shown. This is positioned to the left of the Menu, but when the Menu repositions to align to the right, the arrow no longer is in the correct place. Currently i cannot see a way to make this align to the right based on the position of the Menu. There is a wrapper div in the dom which surrounds the MenuList. Any props provided to the MenuList react component, are applied to the MenuList div, not to the wrapper and i can't see a way to target the wrapper. IMO this is a very necessary feature, as any styling based on the position of the menu cannot work without it.

![image](https://user-images.githubusercontent.com/44572986/119623110-c424fa80-bdff-11eb-81a8-f121245a2dba.png)

## ✅ Proposed solution or API

```
return (
    <Menu>
      {/** currentPosition : "top right" | "top left" | "bottom left" | "bottom right" */}
      {({ isOpen, currentPosition }) => {
        const menuListStyle = {
          _after: {
            top: currentPosition.indexOf("top") > -1 ? "unset" : "0px",
            bottom: currentPosition.indexOf("bottom") > -1 ? "unset" : "0px",
            left: currentPosition.indexOf("left") > -1 ? "unset" : "0px",
            right: currentPosition.indexOf("right") > -1 ? "unset" : "0px",
          },
        };
        return (
          <>
            {isOpen && (
              <Portal>
                <MenuList sx={menuListStyle}>{/* List items */}</MenuList>
              </Portal>
            )}
          </>
        );
      }}
    </Menu>
  );
```

## ↩️ Alternatives

Some form of nasty hack with either vanilla JS to get the position of the div wrapping the MenuList or something with CSS and positioning on the MenuButton meaning my arrow would always be centred. The downside to this is there is no way to know if it goes above or below the button. It would only fix the horizontal centring issue.

**Comment by segunadebayo** [comment]
Hi @jacobpstorefeeder,

This is a complex use case we're not able to consider at the moment.

Kindly try an alternative solution, or use the `offset` prop to manually position the elements.

**Comment by dionjwa** [comment]
As far as I understand it, this is simply positioning a menu to the right, instead of the left, and having the menuItems naturally positioned (right aligned, if the menu items are long). This might be complex to implement, but the use case does not feel complex, simply right vs left positioning, .
