### ISSUE TITLE
Pin input field not working with iOS SMS autocomplete

### ISSUE THREAD

**Issue by AquiGorka** [chakra-ui/chakra-ui#4095]
# 🐛 Bug report

The `PinInput`s nested within a `PinInputField` are not correctly set when using the iPhone's autofill functionality.
This is only happening in Safari. I've tested with Edge, Chrome, Opera, Brave, Firefox and Firefox Focus and these all work as expected.

## 💥 Steps to reproduce

1. Receive an SMS message with an OTP
2. Navigate to https://chakra-ui.com/docs/form/pin-input#using-fields-as-a-one-time-password-otp
3. Select the first pin input
4. Click on the available OTP from the keyboard
5. Only some inputs will be set

## 🌍 System information

Chakra UI: Latest 1.6.2
Browser: Mobile Safari iOS (tested in iPhone 8 and iPhone 12)
Operating system: Latest 14.2.1

## 📝 Additional information

https://user-images.githubusercontent.com/3072458/119651245-175d7400-be25-11eb-997b-1ec3ed51aa80.MP4

**Comment by cesarzagonel** [comment]
Any workaround?

**Comment by AquiGorka** [comment]
Since I posted this issue I have not received any communication from the Chakra team, a solution for us was to start using [`react-otp-input`](https://github.com/devfolioco/react-otp-input) for iOS only as it does not provide an api to easily style the components to mimic the chakra theme.
I do hope someone from the team eventually says something about this.

**Comment by with-heart** [comment]
If someone could research what Mobile Safari expects that the rest of the browsers don't and suggest a solution, that would be helpful in moving this along.

**Comment by cesarzagonel** [comment]
@AquiGorka did that too for now.

**Comment by cesarzagonel** [comment]
@with-heart I will investigate.

**Comment by with-heart** [comment]
Thank you! That would be very helpful. Sorry that we didn't respond and ask for help sooner.

**Comment by ljosberinn** [comment]
On a sidenote - the Chakra team does to my knowledge not have any iOS device, hence the request for help here. Can't reproduce if it only happens on a specific device :/

**Comment by ruofanwei** [comment]
## 🐛 Bug report

#### here is my code
```javascript
<HStack display="flex" justify="center" m="auto" w="100%" mb="16">
        <PinInput
          size="lg"
          display="flex"
          opt
          onComplete={(value) => dispatch(setCaptchaData(value))}
        >
          <PinInputField
            cursor="pointer"
            fontSize="24px"
            w="48px"
            h="48px"
            color="brand.100"
          />
          <PinInputField
            cursor="pointer"
            fontSize="24px"
            w="48px"
            h="48px"
            color="brand.100"
          />
          <PinInputField
            cursor="pointer"
            fontSize="24px"
            w="48px"
            h="48px"
            color="brand.100"
          />
          <PinInputField
            cursor="pointer"
            fontSize="24px"
            w="48px"
            h="48px"
            color="brand.100"
          />
        </PinInput>
      </HStack>
```


## 💥 Steps to reproduce
- Receive an SMS message with an OTP
- Click on the available OTP from the keyboard
- Wrong OTP will be set in pin input

## 🌍 System information
Chakra UI: Latest 1.6.4
Browser: Mobile Safari iOS (tested in  iPhone 12 mini)
Operating system: Latest 14.6

## 📝   Additional information

https://user-images.githubusercontent.com/32828379/122860628-a4c2b400-d350-11eb-8fe3-32726b640a88.mov

**Comment by ruofanwei** [comment]
We found a regular pattern for the wrong OTP will be set in pin input in iOS device.

```
4748 => 4474
3783 => 3378
7309 => 7730
```

Three numbers In front position will be move back, and first number will be repeat.
`N1  N1  N2  N3`



Hope it will be helpful .

**Comment by lasharela** [comment]
Not working for me. With opt property as well.

**Comment by lasharela** [comment]
https://user-images.githubusercontent.com/2189316/155052645-0750bac1-260e-4e80-9d6f-acd285f920f2.mov

If you will pay attention. The number I've got is `070774` but he is skipping the first digits.  Most of the time It's filling only the first 2 digits and that's it. No idea based on what logic it's doing so.

**Comment by reza-akbari** [comment]
same issue version 2.0.2

**Comment by nomadoda** [comment]
I confirm that it's still a problem as of 2.2.4. Safari OTP triggers the `onChange` handler once for each character. I patched the `onChange` handler to make it compatible with safari OTP:

```tsx
import { PinInput, PinInputProps } from '@chakra-ui/react';
import React, { useMemo } from 'react';

const PinInputWithOtp: React.FC<PinInputProps> = ({ children, onChange, ...props }) => {
  const length = React.Children.count(children);

  const memoizedOnChangeHandler = useMemo(() => {
    let queue: string[] = [];
    let timeout: NodeJS.Timeout;

    return (value: string) => {
      onChange?.(value);
      clearTimeout(timeout);
      queue.push(value);
      timeout = setTimeout(() => {
        const didReceiveOtp = queue.length === length && queue.every((a) => a.length !== length);
        if (didReceiveOtp) onChange?.(queue.map((v) => v.at(-1)).join(''));
        queue = [];
      }, 150);
    };
  }, [onChange, length]);

  return (
    <PinInput onChange={memoizedOnChangeHandler} {...props}>
      {children}
    </PinInput>
  );
};
```

**Comment by mwood23** [comment]
Any update on this and can we reopen pretty please 🙏 ?

**Comment by Will-Mann-16** [comment]
Yeah I'm having the same issue here, with general lags behind on iOS devices for the Pin Input. Is there any update, or do I have to migrate to a regular HTML input?

**Comment by changviv** [comment]
Also running into this issue - any updates here?

**Comment by kyin42** [comment]
I also am having this issue.

**Comment by ifightcrime** [comment]
Same issue. Should probably be reopened.

**Comment by GandhiMateGandhi** [comment]
Same issue

**Comment by jordiup** [comment]
Hi gang. I figured the much easier approach is to just check if the browser is Safari + iOS + mobile. Then conditionally render a normal text element.

```diff
+  const isSafari = useMemo(() => /Safari/.test(navigator.userAgent) && !/Chrome/.test(navigator.userAgent), []);
+  const isMobile = useMemo(() => /iPhone|iPad|iPod|Android/i.test(navigator.userAgent), []);
+  const isIOS = useMemo(() => /iPhone|iPad|iPod/.test(navigator.userAgent), []);
```

then 
```diff
<HStack justifyContent="start" mt="0">
							{isSafari && isMobile && isIOS ? (
								<Input
									size="lg"
									autoFocus={true}
									type="tel"
									fontSize="48px"
									autoComplete="one-time-code"
									letterSpacing={6}
									_placeholder={{
										color: 'gray.300',
									}}
									focusBorderColor="whatsapp.500"
									height="56px"
									variant="flushed"
									placeholder="123456"
									value={pin}
									onChange={(e) => setPin(e.target.value)}
								/>
							) : (
								<PinInput
									autoFocus={true}
									type="number"
									onChange={(val) => setPin(val)}
									onComplete={verifnOtpFn}
									size="lg"
								>
									<PinInputField data-testid="sms-pin-input-first" />
									<PinInputField />
									<PinInputField />
									<PinInputField />
									<PinInputField />
									<PinInputField />
								</PinInput>
							)}
						</HStack>
```

**Comment by allenhartwig** [comment]
I went with @longlostnick's solution above, however, I wanted to share my simpler approach to implementing the placeholder visibility logic:

```jsx
    <OtpInput
      value={otp}
      shouldAutoFocus
      onChange={setOtp}
      numInputs={6}
      placeholder={'○○○○○○'} //set the placeholder on the OtInput component
      renderInput={({ style, ...props }, i) => (
        <Input
          {...props}
          _focus={{ //make the placeholder transparent on focus
            _placeholder: {
              color: 'transparent',
            },
          }}
          size={'lg'}
          textAlign={'center'}
          w={10}
          px={0}
          mx={1}
        />
      )}
    />
```

**Comment by MJSPollard** [comment]
Can confirm this is still an issue with version 2.8.2 and definitely related to https://github.com/chakra-ui/chakra-ui/issues/7142. Doesn't look like it getting fixed anytime soon so better look for an alternative.

**Comment by CoreyAccel** [comment]
Ran into this issue today, it's super dissapointing.

**Comment by bradsobie** [comment]
Running into this issue. Sad that this hasn't been addressed

**Comment by trewous** [comment]
Same issue here, it's sad that an OTP component cant work with autocomplete.

**Comment by FlawaCLV** [comment]
I also configm the issue is still here in `v2.8.2` 😢

**Comment by Darthravager23** [comment]
issue still present. Let say i have 4 digit otp 1234 and 4 pinInputfields, on autofill 14_ _. this output comes.1 and 4 is fiiled in first 2 fields

**Comment by envisean** [comment]
Pretty wild that this still hasn't gotten a fix in so many years, did implement the suggestion above to get things working on our end, but still far from perfect. I'm honestly thinking about switching this back into a single input field and just styling it to look like a pin input field.

**Comment by bpetii** [comment]
Same issue here, any updates on this?
