### ISSUE TITLE
Chakra cli theme typings not generating from custom theme for vs code intellisense

### ISSUE THREAD

**Issue by abhaykeerthy12** [chakra-ui/chakra-ui#4097]
# 🐛 Bug report

Chakra cli to generate theme typings from custom theme for vs code intellisense

custom theme content

`export default extendTheme(
  {
    colors: {
      primary: baseTheme.colors.purple,
      secondary: baseTheme.colors.gray,
    }
);`

npm script ran

`"gen:theme-typings": "chakra-cli tokens src/theme/index.ts"`
`"postinstall": "npm run gen:theme-typings"`

## 💥 Steps to reproduce

Follow exactly like documentation

## 💻 Link to reproduction

Chakra Doc: [Theme Typings](https://chakra-ui.com/docs/theming/advanced#theme-typings)

## 🧐 Expected behavior

Custom theme values should be picked up by chakra cli for vs code intellisense

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      "^1.6.3"     |
| Chakra CLI        |      "^1.3.1"     |
| Browser          |     Brave      |
| Operating System |      Linux mint      |

**Comment by segunadebayo** [comment]
It seems we can't reproduce this issue @abhaykeerthy12. Can you provide a simple GitHub repo for this so we can look at the setup you have?

**Comment by cschroeter** [comment]
Close due to inactivity. Feel free to reopen if needed

**Comment by veloware** [comment]
@vlbin did you ever get typings to work in your application that consumes your component library? I'm facing the same issue

**Comment by vlbin** [comment]
@veloware i ended up writing a partly home-cooked solution -- it's not the prettiest but it gets the job done. 

note: i'm on `@chakra-ui/react: 2.1.0` and `@chakra-ui/cli: 2.26.2`

in my `prepare` script I build the library (with Vite), i then generate the tokens using `chakra-cli` and add them to my build

```
"prepare": "npm run build && npm run gen-tokens",
"gen-tokens": "npm run extract-tokens && npm run append-tokens",
"extract-tokens": "chakra-cli tokens ./lib/theme/index.ts --out ./dist/chakra.typings.d.ts --template augmentation",
"append-tokens": "node scripts/write_chakra_typings.js",
```

`write_chakra_typings.js` takes the content generated by `extract-tokens` and appends it to my `dist/index.d.ts`, then deletes `chakra.typings.d.ts`. this was the only way i managed to get the IntelliSense to work

feel free to ask if you need any clarifications!

**Comment by hyetigran** [comment]
> scripts/write_chakra_typings.js

What does the `scripts/write_chakra_typings.js` fn do?

**Comment by vlbin** [comment]
@hyetigran 

as stated in the comment it just takes the output from `extract-tokens` and appends it to `dist/index.d.ts` (the types declaration for the library) to get the TS autocomplete to work
