### ISSUE TITLE
Support fallback CSS values using theme tokens

### ISSUE THREAD

**Issue by joekrill** [chakra-ui/chakra-ui#4098]
# 🚀 Feature request

Emotion [has ability to supply fallback values](https://emotion.sh/docs/object-styles#fallbacks) for browsers that don't support features. Their example is:

```jsx
<div
    css={{
      background: [
        'red',
        'linear-gradient(#e66465, #9198e5)'
      ],
      height: 100
    }}
  >
    This has a gradient background in browsers that support
    gradients and is red in browsers that don't support
    gradients
  </div>
```

which generates some css like:

```css
.theclassname {
    background: red;
    background: linear-gradient(#e66465, #9198e5);
}
```

This actually works in chakra using the `css` prop as above. But for style props the array syntax is interpreted as responsive styles, so that doesn't work directly. Interestingly, an array of arrays actually _does_ work:

```jsx
<chakra.div height="100" background={[["red", 'linear-gradient(#e66465, #9198e5)']]} />
```

or:

```jsx
<chakra.div 
    height="100"
    sx={{
        background: [["red", "linear-gradient(#e66465, #9198e5)"]],
    }}
/>
```

But there are 2 problems:

1. The typescript typings do not support this, so it causes a typescript error.
2. You can't use theme tokens.

It would be great to be able to do something like this:

```jsx
<chakra.div height="100" background={[["red.400", 'linear-gradient(#e66465, #9198e5)']]} />
```

Taking that even further (and really, the thing that lead me down this path in the first place), it would be really awesome if these fallback values could be specified for the theme tokens themselves. For example, there's an issue using `100vh` in mobile browsers that [can be worked-around](https://css-tricks.com/css-fix-for-100vh-in-mobile-webkit/) by using a fallback height of `-webkit-fill-available`. So something like this would be awesome:

```js
export const theme = extendTheme({
  sizes: {
    "100vh": [["100vh", "-webkit-fill-available"]]
  }
});
```

which would then allow you to do:

```jsx
<chakra.div height="100vh" />
```

but have the underlying style be output as:

```css
.theclassname {
    height: 100vh;
    height: -webkit-fill-available;
}
```

This may actually be 2 features requests... or perhaps a bug and 1 or 2 feature requests. Let me know if you'd like me to resubmit or split them up.

Sorry for the edit! I accidentally submitted this issue before I was finished writing it up.

**Comment by segunadebayo** [comment]
Hi @joekrill,

This is quite tricky to support as we're a bit weary to increase the API surface. Array syntax currently maps to responsive styling, having to support an array of arrays for fallback values might seem quite inconsistent to the common Chakra UI consumer.

All components accept the `css` prop which is basically passed to emotion directly without any processing on our end.

Please use the `css` for these scenarios since they're quite rare in practice.

Thanks
