### ISSUE TITLE
[RadioButtonGroup] TypeScript cannot infer onChange types correctly

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#41]
When using the code below:

```tsx
export default function Component() {
  const [selectedChoice, setSelectedChoice] = useState<string>();

  return (
    <RadioButtonGroup
      value={selectedChoice}
      onChange={value => setSelectedChoice(value)}
    >
      {/* ... */}
    </RadioButtonGroup>
  );
}
```

I get the following TypeScript error in strict mode:

`Parameter 'value' implicitly has an 'any' type. - ts(7006)`

**Comment by segunadebayo** [comment]
Thanks for this feedback @kripod .

I guess we'll need to review and test the type defs more thoroughly, esp. for `RadioButtonGroup`
