### ISSUE TITLE
Popover `matchWidth` prop does not work

### ISSUE THREAD

**Issue by cloud-walker** [chakra-ui/chakra-ui#4104]
# 🐛 Bug report

Hi, I'm trying to implement a combobox like experience, and to do so I use the `Popover` module from chakra, but the documented prop `matchWidth` seems to be ignored.

## 💥 Steps to reproduce

1. Just open the popover, clicking on the codesandbox example below

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/chakra-popover-matchwidth-olbtk?file=/src/modules/App/App.tsx

## 🧐 Expected behavior

It should respect the property and take the same width of the container

## 🧭 Possible Solution

TBD

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     latest       |
| Browser          |      Chrome latest      |
| Operating System |     Windows 10       |

**Comment by segunadebayo** [comment]
Technically, the popover content's container (aka popper.js) sets the width correctly but because the PopoverContent component has width set, it basically overrides it.

You can get it working by setting `width=inherit` on `PopoverContent`:
https://codesandbox.io/s/chakra-popover-matchwidth-forked-l4lu2?file=/src/modules/App/App.tsx

Hope this helps.

**Comment by csandman** [comment]
Is there any chance this could be documented somewhere?  It seems like the `matchWidth` prop is kind of useless without this workaround, and I couldn't figure out how to make it function until I happened across this issue.  Maybe include this in the documentation for the `matchWidth` prop?

**Comment by krzysztofMlczk** [comment]
@segunadebayo the question was to make the PopoverContent as wide as the Container component and not the triggering button. Any hints on achieving this?
