### ISSUE TITLE
LinkBox and LinkOverlay - support for buttons or other elements.

### ISSUE THREAD

**Issue by autumnwoodberry** [chakra-ui/chakra-ui#4105]
# 🚀 Feature request

Allow specifying which elements within a `LinkBox` will be raised above the `LinkOverlay`.

## 🧱 Problem Statement / Justification

As stated in the docs, "the component or card could contain other clickable elements or links (tags, timestamps, buttons)." A component with a `LinkBox` and `LinkOverlay` might contain other elements besides just `<a/>` or `<abbr/>` and it would be nice to be able to mark which components should not be covered. Specifically a button component would be useful.

## ✅ Proposed solution or API

One solution would be to have another sibling component to the `LinkOverlay` which would wrap and raise any element within it.

## ↩️ Alternatives

You could probably just add the correct z-index to any button element you wanted to raise over the `LinkOverlay`.

**Comment by anubra266** [comment]
I think this does what you want
```html
<LinkBox as="article" maxW="sm" p="5" borderWidth="1px" rounded="md">
  <Box as="time" dateTime="2021-01-15 15:30:00 +0000 UTC">
    13 days ago
  </Box>
  <Heading size="md" my="2">
    <LinkOverlay href="#head">
      New Year, New Beginnings: Smashing Workshops & Audits
    </LinkOverlay>
  </Heading>
  <Text mb="3">
    Catch up on what’s been cookin’ at Smashing and explore some of the most
    popular community resources.
  </Text>
  <Button as="a" color="teal.400" href="#inner" fontWeight="bold">
    Some inner link
  </Button>
</LinkBox>
```

**Comment by segunadebayo** [comment]
Hi @autumnwoodberry, the solution suggested by @anubra266 seems to be correct.

Please try this and we're happy to re-open if the issue persists.
