### ISSUE TITLE
Toast transparency is inconsitent between colormodes. Dark mode legibility is low.

### ISSUE THREAD

**Issue by mah51** [chakra-ui/chakra-ui#4108]
# 🚀 Feature request

> Please describe your request in one or two sentences.

Make the darkmode (subtle and accented) toasts opaque.

## 🧱 Problem Statement / Justification

> Please provide valid reason(s) why this should added to Chakra UI.

Text behind the toast makes it difficult to read, and the light mode toast is opaque, so it seems intuitive that they are consistent through color modes.
> If this feaure is related to a problem you've noticed. Mention it as well

## ✅ Proposed solution or API

> Please provide code snippets, gists, or links to the ideal design or API

Just make the bg non-transparent, with a dark variant of the colour. 

## 📝 Additional Information

> What resources (links, screenshots, etc.) do you have to assist this effort?
![lightmode](https://cdn.discordapp.com/attachments/695564068895064094/846824869021876234/unknown.png)
![darkmode](https://cdn.discordapp.com/attachments/695564068895064094/846824924630220870/unknown.png)

**Comment by with-heart** [comment]
`Toast` uses `Alert` under the hood, so here's where that transparency is defined: https://github.com/chakra-ui/chakra-ui/blob/890839d9fe32d5ec90954c8f4c5b6c463ff0b57d/packages/theme/src/components/alert.ts#L28-L33

Not sure why dark mode is slightly transparent.

**Comment by mah51** [comment]
Hi are there any updates on this, I don't have much experience with open source code but I don't mind trying to help out if that's alright?

**Comment by hollowprince-afk** [comment]
My aforesaid knowledge of it's limited agl. Is so good, I required support. Thanks.

**Comment by mah51** [comment]
🙃

**Comment by cpagonis** [comment]
in dark mode toast background is still transparent
