### ISSUE TITLE
Request to add Angular Version

### ISSUE THREAD

**Issue by asajuenitan** [chakra-ui/chakra-ui#411]
**Describe the solution you'd like**
A version of the UI for Angular Framework since you are migrating to Typescript

**Comment by segunadebayo** [comment]
Hi @asajuenitan, 

This is currently out of our scope and I can't guarantee we'll work on it.

Feel free to chime in on this if you're interested.

**Comment by asajuenitan** [comment]
Hello, it's me again :).
I really want to have a shot at developing an angular version

**Comment by deepakrudrapaul** [comment]
> Hello, it's me again :).
> I really want to have a shot at developing an angular version

I would love to help you.

**Comment by en1tan** [comment]
hello, that'd be awesome. when do you want to get started, I have not been able to continue

**Comment by timothyalcaide** [comment]
If someone develops the angular version will they be paid? Or is it just voluntary?

**Comment by aarhusgregersen** [comment]
A discussion has been opened a bit more recently for those wanting to contribute to building an angular version:
https://github.com/chakra-ui/chakra-ui/discussions/6086
