### ISSUE TITLE
Color of Editable placeholder should not be the same as real content

### ISSUE THREAD

**Issue by QzCurious** [chakra-ui/chakra-ui#4116]
# 🐛 Bug report

When value of an `Editable` is falsy, `EditablePreview` show the placeholder in black.
This confuse me that if the text on screen is real content or not.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/chakra-editable-placeholder-bug-wy6pl

## 🧐 Expected behavior

When value of an `Editable` is falsy, `color` of  `EditablePreview` should be the same as `EditableInput`.
That is, falsy value should show a `GrayText` placeholder both in `EditablePreview` and `EditableInput`.

## 🧭 Possible Solution

I had a workaround for it (code in CodeSandbox).
By set the `color` to `GrayText` if value is falsy.
But it introduce a problem that I need to make sure the color is the same for `EditablePreview` and `EditableInput`  if I changed one.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.6.3  |
| Browser          |       Firefox 88.0.1-1    |
| Operating System |      5.12.2-1-MANJARO     |

## 📝 Additional information

![image](https://user-images.githubusercontent.com/38932402/120113720-576a8100-c1ae-11eb-81c1-4d1064f84eb6.png)

**Comment by anubra266** [comment]
The Preview has to blend in with other content on the page, it's only a placeholder, when the input is focused.

**Comment by QzCurious** [comment]
> And don't do <EditablePreview color={value || "GrayText"} />, because if your user enters an actual color, your input color will change to that color.

The workaround I provided was a terrible example. Thanks for correcting me.

But I'm still not convinced that the color of placeholder to be the same as content. I'll adopt the workaround.

**Comment by anubra266** [comment]
cc @with-heart

**Comment by segunadebayo** [comment]
Hi @QzCurious,

Changing this would be considered a visual breaking change for other users. Please change it in your project by passing the `color` prop.

Thanks for understanding.

**Comment by storenth** [comment]
Looks like workaround still actual, I'll use it, thx.
