### ISSUE TITLE
equivalent feature like window.prompt

### ISSUE THREAD

**Issue by aboveyunhai** [chakra-ui/chakra-ui#4118]
# 🚀 Feature request

I wonder does Chakra have similar component to simulate `window.prompt()`;

## 🧱 Problem Statement / Justification

I know I can use `modal` combine with `useState` to simulate the `window.prompt()` behavior;
but it can be very handy I can do something like the following;

```js

const prompt = usePrompt(// customize prompt panel here, pass value into panel);

const result = window.prompt() or promprt.trig() ;
if(result) ...
```

## ✅ Proposed solution or API

Maybe it can be an extra feature from current modal?

## ↩️ Alternatives

> N/A

## 📝 Additional Information

> N/A

**Comment by anubra266** [comment]
https://chakra-ui.com/docs/overlay/alert-dialog

**Comment by aboveyunhai** [comment]
> Have you checked [Alert Dialogs](https://chakra-ui.com/docs/overlay/alert-dialog)?

Please read my question carefully. If you ever read the doc, `Alert Dialogs` is indeed `modal`, unless I missed something from the doc,

**Comment by anubra266** [comment]
> Please read my question carefully. If you ever read the doc, `Alert Dialogs` is indeed `modal`, unless I missed something from the doc,

I read your question, and I know it's a modal, But the dialogs are streamlined to serve this purpose.  If not, you're basically asking for JSX in a hook.
