### ISSUE TITLE
How to reduce the spacing in the menu

### ISSUE THREAD

**Issue by ameerthehacker** [chakra-ui/chakra-ui#412]
If I change the size of the button, the spacing increases. How can I reduce this spacing?
<img width="360" alt="Screenshot 2020-02-17 at 1 43 30 AM" src="https://user-images.githubusercontent.com/15448192/74611999-12404e00-5127-11ea-9ce2-afd309c3687d.png">

**Comment by segunadebayo** [comment]
Hi @ameerthehacker,

Thanks for reporting this issue. Do you have a CodeSandbox replication of this so we can help?
