### ISSUE TITLE
Popover arrowShadowColor is not working

### ISSUE THREAD

**Issue by alexvuong** [chakra-ui/chakra-ui#4127]
# 🐛 Bug report

Hello,
I am trying to change the arrow shadow in Popover, as I follow the [doc](https://chakra-ui.com/docs/overlay/popover) . The Popover takes `arrowShadowColor` as a prop, but it never gets apply to the component arrow. 

## 💥 Steps to reproduce

1. Go to 'https://codesandbox.io/s/chakra-ui-header-forked-l37o6?file=/src/index.js'
2. Click on 'Trigger' to open the Popover
3. I passed the color `red.900` to the prop `arrowShadowColor`, but it does not reflect on the component
![image](https://user-images.githubusercontent.com/52219283/120246663-bf0fe300-c225-11eb-9b12-21d822e39e3b.png)

## 💻 Link to reproduction
https://codesandbox.io/s/chakra-ui-header-forked-l37o6?file=/src/index.js

## 🧐 Expected behavior

The arrow shadow should reflect the value being passed as prop

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.6.1         |
| Browser          |    Chrome        |
| Operating System |  Version 91.0.4472.77 (Official Build) (x86_64)  |

**Comment by anubra266** [comment]
I've confirmed this is a bug.
The arrowShadow in the defaultStyles provided to `PopoverTransition` overrides the one the user provides, cause that is passed to the parentComponent.
