### ISSUE TITLE
Updated toast should retain original options.

### ISSUE THREAD

**Issue by anubra266** [chakra-ui/chakra-ui#4139]
# 🚀 Feature request

I think updating a toast should retain the previous options.

## 🧱 Problem Statement / Justification

When I create a toast, say with `error` status, When updating the toast, I must specify the status again, or it resets to default, which is info. 
When I create a toast, I might just want to update the description. I shouldn't have to specify the status and the title all over again.

## ✅ Proposed solution or API
See how it is done [here](https://fkhadra.github.io/react-toastify/update-toast)

**Comment by EricKulchycki** [comment]
I've started working on this, but it seems like from comments that someone is planning a toast refactor. Is this something that should wait @with-heart?

**Comment by anubra266** [comment]
Hi! @EricKulchycki what comments?

**Comment by EricKulchycki** [comment]
@anubra266 Code comments*. My bad, I should have been a little more clear.

**Comment by anubra266** [comment]
Thanks for working on this BTW.

**Comment by noobinthisgame** [comment]
@TimKolberger According to this PR https://github.com/chakra-ui/chakra-ui/pull/5493 this issue should be closed if im not mistaken. :)

**Comment by TimKolberger** [comment]
@anubra266 is this issue about `toast.update({ ...thisObjectHere })` or `const {...thisObjectHere} = useToast()`?

**Comment by anubra266** [comment]
> @anubra266 is this issue about `toast.update({ ...thisObjectHere })` or `const {...thisObjectHere} = useToast()`?

It was about toast.update

**Comment by EricKulchycki** [comment]
yeah this can probably be closed, i wasn't really monitoring and didn't get any updates about the status of the other changes.
