### ISSUE TITLE
[useClipboard] Clipboard content not changed when used inside a Drawer

### ISSUE THREAD

**Issue by varshard** [chakra-ui/chakra-ui#414]
**Describe the bug**
I used `useClipboard` from a component inside `Drawer`. When I call `onCopy`, then nothing changed to the clipboard. The clipboard content is still as before I called `onCopy`. 
I put a breakpoint on `useCliptboard`'s `copyToClipboard` and discovered that a textarea has the exact value that I pasted to `useClipboard`, but somehow not copied by `document.execCommand("copy");`

**Expected Behavior**
When `onCopy` is called inside a component inside a Drawer, then the clipboard content should be changed to match `useClipboard`'s value.

**To Reproduce**
1. Create a component and put it inside a DrawerBody
2. Use `useClipboard` inside the component
3. Trigger `onCopy` from the component
4. Paste, then the content that's pasted will not be the value that's passed to `useClipboard`

**Suggested solution(s)**

I believe that this is caused by `Drawer`'s attempt to trap focus inside itself. This prevented `useClipboard` from selecting text on the textarea outside.

I suggest that `useClipboard` should create a textarea inside the component that's calling it attaching it to document.body.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.3
 - Browser: Firefox
 - Version: 72.02
 - Browser: Google Chrome
 - Version: 79.0.3945.130

**Additional context**
I've replicated `useClipboard` logic inside a component inside `Drawer` and it works as intended.

**Comment by segunadebayo** [comment]
Hi @varshard,

Thanks for reporting this issue. I've just fixed this and will release a patch shortly.

If after upgrade the problem still exists in your application please open a new issue and follow the instructions in the issue template.

**Comment by dewaleolaoye** [comment]
This still happens, I have to click the *onCopy* functionality twice for the clipboard to update
