### ISSUE TITLE
Button Size not Responsive

### ISSUE THREAD

**Issue by anubra266** [chakra-ui/chakra-ui#4140]
# 🐛 Bug report

The Size prop of the Button Component does not accept Responsive values

## 💥 Steps to reproduce

Import the Button Component, and set responsive, array or object type values. The editor shows errors.

## 💻 Link to reproduction

https://codesandbox.io/s/solitary-grass-18vgr?file=/src/index.tsx

## 🧐 Expected behavior

I should be able to enter Responsive value sizes for a Button

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.6.3 |
| Browser          |Firefox|
| Operating System |Ubuntu|

## 📝 Additional information
![image](https://user-images.githubusercontent.com/30869823/120426193-88da7c80-c367-11eb-99fd-14bc316cc225.png)

**Comment by TimKolberger** [comment]
Responsive variants and sizes are currently not supported in chakra. We are working hard to land this feature in v2 😊

**Comment by anubra266** [comment]
Wow...can't believe this is the first time, I've ever tried it. 
When it didn't work, I was like; I've done this before, what went wrong now.😆

**Comment by segunadebayo** [comment]
Hehehe. @anubra266, it has never worked 🤣 as far I can remember.

Let's close this in favor of adding it to the v2 milestone.

Thanks for bringing this up.
