### ISSUE TITLE
Drawer/Modal exit animation doesn’t work

### ISSUE THREAD

**Issue by joshuabaker** [chakra-ui/chakra-ui#4149]
# 🐛 Bug report

The exit animation for drawers and modals isn’t playing before the component is unmounted.

## 💥 Steps to reproduce

1. Go to reproduction linked below
2. Press “Toggle” to open the drawer
3. Close the drawer

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/boring-noyce-833wl?file=/pages/index.js

## 🧐 Expected behavior

I’d expect the animation (e.g. fade out) to complete before the component is unmounted.

## 🧭 Possible Solution

I’m wondering if this might be caused by having `Portal` as the immediate child of `AnimatePresence`, instead of the modal/drawer content component.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.6.3       |
| Browser          |    Safari 14.1, Chrome 90       |
| Operating System |       macOS 11.3.1      |

**Comment by joshuabaker** [comment]
@segunadebayo [Reproduction](https://codesandbox.io/s/boring-noyce-833wl?file=/pages/index.js) is linked in the issue.

**Comment by joshuabaker** [comment]
### Screen recording

https://user-images.githubusercontent.com/160484/120635548-801ba080-c464-11eb-83f6-ddf7804923c0.mov

**Comment by joshuabaker** [comment]
@segunadebayo Why did you close this? This issue is unresolved.

**Comment by bkiac** [comment]
I still experience this issue with `1.8.1

**Comment by bkiac** [comment]
`DrawerOverlay` is needed for the closing animation, see https://github.com/chakra-ui/chakra-ui/discussions/4327

**Comment by dush-t** [comment]
I could fix this for myself by adding a `<DrawerOverlay disaply='none'/>` component inside the `<Drawer>` component. Maybe that'll work for you as a temp fix.
