### ISSUE TITLE
[Icon] Unable to specify custom icons in the theme

### ISSUE THREAD

**Issue by gopinav** [chakra-ui/chakra-ui#416]
**Describe the bug**
I tried to follow [docs](https://chakra-ui.com/icon#adding-custom-icons) to add custom icons. However, the app breaks and does not run. I see errors in the terminal. Not sure if this is CRA specific but below are screenshots to help.

![image](https://user-images.githubusercontent.com/13146172/74625891-e303fe00-5173-11ea-93e7-9e0ef1c76319.png)
![image](https://user-images.githubusercontent.com/13146172/74625966-1e9ec800-5174-11ea-98b2-5635e071af9f.png)
![image](https://user-images.githubusercontent.com/13146172/74625974-25c5d600-5174-11ea-96da-329674658e81.png)

**Expected Behavior**
App should run without breaking

**Suggested solution(s)**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version: "@chakra-ui/core": "^0.5.2"

**Additional context**

**Comment by santialbo** [comment]
I think you might just need to rename your file to `icons.tsx` since you are using jsx.

**Comment by gopinav** [comment]
That was the fix! Thank you very much
