### ISSUE TITLE
Custom Link variants not working?

### ISSUE THREAD

**Issue by JClackett** [chakra-ui/chakra-ui#4163]
Hey!

I posted a discussion in here: https://github.com/chakra-ui/chakra-ui/discussions/4064, but it seems like it must be a bug, so thought I'd create an issue, maybe im wrong :D 

# 🐛 Bug report

I'm trying to create a link variant but it doesn't seem to do anything, I've followed the docs the best I could but not sure if im doing something incorrect.

```ts
export const theme = extendTheme({
  components: {
    Link: {
      baseStyle: { bg: "red" },
      sizes: {
        md: {
          h: "56px",
          fontSize: "lg",
          px: 10
        }
      },
      defaultProps: { variant: "test" },
      variants: {
        test: {
          p: 4,
          borderRadius: "md",
          bg: "red",
          fontSize: "40px"
        }
      }
    }
  }
});
```

Here's a repo: https://codesandbox.io/s/fragrant-monad-2uzcs?file=/pages/_app.tsx

## 🧐 Expected behavior

I get a custom variant for the Link component

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |          latest  |
| Browser          |       all     |
| Operating System |   macOS         |

**Comment by cschroeter** [comment]
Hey buddy,

you need to pass in the theme like `<ChakraProvider theme={theme} />`
Hope that clarifies your issue.

**Comment by JClackett** [comment]
Dam, well that's embarrassing.. thanks though!
