### ISSUE TITLE
CSSReset Scoped to an element and not the whole html root

### ISSUE THREAD

**Issue by DavidNorena** [chakra-ui/chakra-ui#4164]
# 🚀 Feature request

> CSSReset should work also for scoped styles, only applied from root certain elements

## 🧱 Problem Statement / Justification

> There is not current implementation/approach to accomplish that
>
> If this feaure is related to a problem you've noticed. Mention it as well

## ✅ Proposed solution or API

> The only thing i found its this: https://codesandbox.io/s/hs31q?file=/src/CSSReset.tsx

## ↩️ Alternatives

> What alternative solutions have you considered before making this request?

## 📝 Additional Information

> What resources (links, screenshots, etc.) do you have to assist this effort?

**Comment by with-heart** [comment]
There is a trick you can do using `@emotion/cache` and creating a `stylis` plugin that forces `emotion` to target a specific element but that still leaves the problem of having to set `font-size` on `html` because of how `rem` works, so it only gets you so far.

**Comment by DavidNorena** [comment]
ok, but is there a plan or something committed to make this out of the box ? or is not related to this library ?
