### ISSUE TITLE
[Select] <option> labels are not readable in dark mode

### ISSUE THREAD

**Issue by maggo** [chakra-ui/chakra-ui#417]
**Describe the bug**
`<option>` elements are inheriting the white color of the `<select>` element in dark mode and are not readable.

![image](https://user-images.githubusercontent.com/384953/74699586-5acc3a00-5201-11ea-8f6f-8f527d977c27.png)

**Suggested solution(s)**
A CSS reset for the <option> elements should do the trick (`option { color: initial; }`)

**Desktop**
Windows Chrome 80

**Comment by balibebas** [comment]
Suggested solution works. It would be preferable, however, for the background color of the select element to match the theme:

![Peek 2020-06-05 20-52](https://user-images.githubusercontent.com/65664227/83879103-b4845000-a76f-11ea-82a5-87bde826b8ce.gif)

**Comment by with-heart** [comment]
I've verified that `Select` is now using different styling for light and dark modes in 1.0: https://codesandbox.io/s/rough-meadow-3vyr2?file=/src/App.js

**Comment by nikhilpatil-git** [comment]
> I've verified that `Select` is now using different styling for light and dark modes in 1.0: https://codesandbox.io/s/rough-meadow-3vyr2?file=/src/App.js

This sandbox is not working please check

**Comment by with-heart** [comment]
@nikhilpatil-git Fixed!

**Comment by leomotta121** [comment]
Still not matching dark mode

**Comment by balibebas** [comment]
@leomotta121 which pre-release version are you using? perhaps there was a regression

**Comment by stefan-girlich** [comment]
This phenomenon still exists as of @chakra-ui/react v1.0.1. 
Observations:
- The white background is only applied when a color is passed to `<Select />` via the `bg` or `bgColor` prop.
- Issue reproducible on Firefox 83.0 on MacOS 10.15.7
- Not reproducible on Chrome 86.0.4240.198 on MacOS 10.15.7; unstyled native dropdown overlay is used
- Issue only exists in _light_ mode (if `colorMode` returned by `useColorMode()` equals _"light"_)

**Comment by with-heart** [comment]
> * The white background (behind the white text) is only applied when a color is passed to `<Select />` via the `bg` or `bgColor` prop.
> * Issue reproducible on Firefox 83.0 on MacOS 10.15.7
> * Not reproducible on Chrome 86.0.4240.198 on MacOS 10.15.7; unstyled native dropdown overlay is used
> * Issue only exists in _light_ mode (if `colorMode` returned by `useColorMode()` equals `"light"`)

Can you make a CodeSandbox for this? I'm not sure I'm following what you mean.

> * `colorMode` from `useColorMode()` seems to be `"light"` by default, despite my OS and browsers being set to dark mode

https://chakra-ui.com/docs/features/color-mode#change-color-mode-behavior

**Comment by stefan-girlich** [comment]
@with-heart Sure!

https://codesandbox.io/s/eloquent-cray-u2bxb?file=/src/App.js

**Comment by with-heart** [comment]
@stefan-girlich Thank you! Re-opening as this does appear to still be an issue in Firefox.

**Comment by segunadebayo** [comment]
@with-heart  can you confirm this has been fixed?

**Comment by rafaelderolez** [comment]
@segunadebayo not yet! 
![image](https://user-images.githubusercontent.com/6158959/110549241-11af9680-8132-11eb-9ab4-0546fed906bf.png)

**Comment by with-heart** [comment]
@rafaelderolez That csb is working as it should. `Select` has `color="white` as a prop which is inherited by the options, which is just how CSS works. This issue is about the default styling of `Select` being unreadable in dark mode.

If we render `Select` without any additional props, it works correctly in dark mode: https://codesandbox.io/s/wispy-platform-ipxu7?file=/src/App.js

Light mode: 
![image](https://user-images.githubusercontent.com/1954752/111037575-ad6f2a00-83f2-11eb-9653-9efa57449391.png)

Dark mode: 
![image](https://user-images.githubusercontent.com/1954752/111037587-b829bf00-83f2-11eb-96ff-786372354ddc.png)
