### ISSUE TITLE
Color Mode caching in browser between applications

### ISSUE THREAD

**Issue by prescottbreeden** [chakra-ui/chakra-ui#4175]
# 🐛 Bug report
Screenshot of my browser storage:
![image](https://user-images.githubusercontent.com/35798153/120941831-dc3b2a80-c6d9-11eb-855b-e601057e3de7.png)
Color Mode is being cached in the browser, and so even though I have another application that has no dark mode, only is written for light mode, it is pulling the dark mode from another application I work on which does have light/dark mode enabled.

## 💥 Steps to reproduce
Create 2 applications, set one to toggle light/dark mode, the other to just use default settings. The second one will appear in dark mode until you delete the keys from browser storage.

## 🧐 Expected behavior
To be able to write multiple apps with chakra without color modes bleeding across applications.  I assume there is a good reason for using the browser storage but seems like a sledge hammer of a solution.

## 📝 Additional information
This may be a "not clear in the documentation" issue but I cannot find anything that indicates I am missing something.

**Comment by o-henry** [comment]
Because chakra-ui-color-mode uses localStorage, data does not expire. For this function, shouldn't we add a flag that uses session storage to color-mode?

**Comment by prescottbreeden** [comment]
Not a very elegant solution but you could provide a property on the theme to create a unique identifier.

**Comment by anubra266** [comment]
Hmm...Maybe we could choose our key in config.

**Comment by with-heart** [comment]
This is occurring in production?

**Comment by anubra266** [comment]
> This is occurring in production?

No. It's just different applications, using the same port on localhost.

**Comment by Nish7** [comment]
@with-heart Similar Behavior happening,  local storage should be reset or cleared on each new instance of chakraprovider ig. Because the color mode value is persisting between every application running on same port and host in this case localhost:3000.

**Comment by aboveyunhai** [comment]
@Nish7  @prescottbreeden  I guess we just need a feature request to do the following, 
Although I believe it's is just a niche dev issue. Probably not worth to address.
```js
{
  config: {
    customColorModeStorageName: `your own name`, // this will override the default chakra-ui-color-mode 
  }
}
```

**Comment by prescottbreeden** [comment]
I like the custom option.  An option to disable caching on localhost is the only other thing I can think of that is low hanging fruit. Roughly something like...

```typescript
extendTheme({
  config: {
    disableColorModeCacheInDev: true, // this will prevent chakra from storing color mode settings on localhost
    initialColorMode: "dark",
  }
})
```
```ts
const disableStorage = () =>  disableColorModeCacheInDev && (
    /^http:\/\/localhost:/.test(document.URL) || 
    /^http:\/\/127.0.0.1:/.test(document.URL)
);
```
and then update manager
```ts
export const localStorageManager: StorageManager = {
  get(init?) {
    if (!hasSupport() || disableStorage()) return init
    // ...
  },
  set(value) {
    if (!hasSupport() || disableStorage()) return
    // ...
  },
  type: "localStorage",
}
```

The benefit here is if I have a project that I did not create a name for, then add the name later, my browser will retain the old key that will be pulled in on any projects I spin up.  The quality of life provided by the token is really for production, not dev, so I think allowing people to shut off caching on dev has merit.

**Comment by ssosina** [comment]
Just confirming that I'm also experiencing this issue in local dev. I had to clear my `localStorage` to reset back to default light scheme.

**Comment by jasonkarjadi** [comment]
I thought I'm the only one experiencing this. Would appreciate if there is a fix to this
<img width="736" alt="Screen Shot 2021-08-15 at 23 46 42" src="https://user-images.githubusercontent.com/77325085/129482407-fd4e1121-6ce6-4021-933b-689c7551db26.png">

**Comment by anubra266** [comment]
not stale

**Comment by JClackett** [comment]
Jumping in here to confirm that its quite annoying when developing an app that is meant to be dark mode only, but I've set another application to light mode. Tt forces me to have to open the dev console and delete the localstorage item as I don't have a theme switcher in the dark mode app (and don't want one). Surely it's just a case of passing in some kind of unique key to chakra somewhere?
