### ISSUE TITLE
(Question) How to store the theme object to support multi tenant application? 

### ISSUE THREAD

**Issue by charanpasham** [chakra-ui/chakra-ui#418]
Can chakra-ui handle following things?

- I need to be able to support multiple tenants through single application by storing tenant specific themes into database.

- Those themes should be editable from UI.

**Comment by l3szcz** [comment]
I didn't try it myself but I think it would work.

Theme object can be stored serialized in a database. Download the theme when needed, deserialize it and change the value of `theme` prop passed to `ThemeProvider`.

For editing - load the theme object you want to edit, make changes (changes can be reflected live and later serialized and saved to DB via API call).

**Comment by JClackett** [comment]
We do this with one of our projects, as mentioned above just modify the default theme with the values from your DB

```

function ThemeProvider() {
const dataFromDb = useQuery/fetch/whatever you do
const customTheme = theme // From chakra
customTheme.<whatever color you want>["500"] = dataFromDB.color

 return (
  <ThemeProvider theme={customTheme}>
      <CSSReset />
      {children}
   </ThemeProvider>
  )
}
```

Its best to have values for the entire Hue i.e. 50, 100, 200 300 etc as this means you can use the components to their fullest, for our platform the tenant only provides one color so we use "polished" to create different hues

```
 theme.colors<color you want>["400"] = lighten(0.2, datafromDb.color)
```

**Comment by segunadebayo** [comment]
Hi @charanpasham, I assume you've found a solution based from @JClackett  and @l3szcz 's reply.

Closing this out.
