### ISSUE TITLE
Button is unusually large only when the height or width is 40

### ISSUE THREAD

**Issue by papparapa** [chakra-ui/chakra-ui#4182]
Thanks for the great library!

# 🐛 Bug report

Buttons become unusually large when height is set to 40 or width is set to 40.

## 💥 Steps to reproduce

1. Make a button with a height  of 40 or a width of 40 like this one.
```
function App() {
  return <Button colorScheme={"red"} width={40} height={40}/>;
}
```
2. Render it.
3. Compare it to a button with a size of 39 or 41 if you need to.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/chakra-ui-button-size-bug-report-lbid6

## 🧐 Expected behavior

The size 40 button should be between the size 39 button and the size 41 button.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.6.3    |
| Chrome     | 90.0.4430.212|
| Windows 10  Home  | 21H1 |

## 📝 Additional information

![image](https://user-images.githubusercontent.com/37232476/121023973-bf3c4f80-c7de-11eb-985d-21aba12b13ba.png)
width={40} height={40}

![image](https://user-images.githubusercontent.com/37232476/121025541-38887200-c7e0-11eb-9349-8666a7a687d6.png)
width={39} height={39}

![image](https://user-images.githubusercontent.com/37232476/121025646-58b83100-c7e0-11eb-8129-620a7c84c5db.png)
width={41} height={41}

**Comment by with-heart** [comment]
This is working as intended! `width` and `height` are connected to `theme.sizes` which includes all of the values from `theme.space`. 

What's happening here is that `39` and `41` are not keys of `theme.space`, so they're translated to `39px` and `41px`

![image](https://user-images.githubusercontent.com/1954752/121029936-055dc880-c777-11eb-8ffa-e8d93a3996d5.png)
![image](https://user-images.githubusercontent.com/1954752/121029981-0ee73080-c777-11eb-9e85-15c7af44d678.png)

whereas `40` uses the `--chakra-sizes-40` CSS var

![image](https://user-images.githubusercontent.com/1954752/121030070-26261e00-c777-11eb-981f-43167cbb5e1b.png)

If you'd prefer to use pixels, use `"40px"` to make it specific.

**Comment by papparapa** [comment]
Thank you for the quick response.
I didn't know how it worked.
