### ISSUE TITLE
[MenuItem] Menu not closing when clicking on icon or command

### ISSUE THREAD

**Issue by xotea** [chakra-ui/chakra-ui#4189]
# 🐛 Bug report

When putting elements in a MenuItem (like a cat image and a span shown in the documentation) or using the `icon` or `command` props it won't close on click because `isTargetMenuItem()` [here](https://github.com/chakra-ui/chakra-ui/blob/245a164f6058e96986b2354017d96816b5d336e9/packages/menu/src/use-menu.ts#L337) returns false. In the former case you can solve this problem by providing a role that starts with _menuitem_ like _menuitemimage_ (I don't know whether you should do that) but the latter is definitely a bug.

## 💥 Steps to reproduce

1. Go to sandbox or the [relevant page of the documentation](https://chakra-ui.com/docs/overlay/menu#adding-icons-and-commands).
2. Open either menu
3. Click on the icon/image/command
4. See menu not closing

## 💻 Link to reproduction

CodeSandbox reproduction: [https://codesandbox.io/s/stupefied-water-p7s1l](https://codesandbox.io/s/stupefied-water-p7s1l)

## 🧐 Expected behavior

Menu should close on icon and command click by default and we probably should have a way to tell children of `<MenuItem />` whether we want them to close the menu or not.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI         |   1.6.3       |
| Browser            |  Chromium based Edge |
| Operating System |   Windows 10   |

**Comment by SkrewEverything** [comment]
And if I'm not wrong, even `closeOnBlur` for normal `Menu` is also not working as intended.

**Comment by anubra266** [comment]
It's been reported and fixed in #4165, expect a fix release soon.

**Comment by xotea** [comment]
Oops, my bad. Apparently I can't properly read in the evening. Closing this.
