### ISSUE TITLE
[FormControl/Textarea] FormControl with TextArea child displays as invalid on page load

### ISSUE THREAD

**Issue by bsansone** [chakra-ui/chakra-ui#419]
**Describe the bug**
FormControl with TextArea child displays as invalid on page load. 

**Expected Behavior**
Page should load and FormControl with Textarea should not be in an invalid state.

**To Reproduce**
- Load this code sandbox: https://codesandbox.io/s/wizardly-violet-hdtzr
- Page loads with FormControl & Textarea in invalid state
- Textarea value is an empty string
- FormControl has `isRequired` prop set to `true`

**Suggested solution(s)**
Upgrade react and react-dom from 16.9 to current (16.12)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox Developer Edition
 - Version 74.0b4 (64-bit)

**Additional context**
N/A

**Comment by gopinav** [comment]
Hello - Can you please elaborate how the text area is invalid on page load? Unable to see the issue in the codesandbox link.

**Comment by bsansone** [comment]
@gopinav On page load, the `Textarea` is rendered with a red border as if the form has been submitted and the `Textarea` was left empty causing the `isInvalid` state of the wrapping `FormControl`.

It looks like the issue is specific to Firefox, it works fine in Chrome, do you have access to the Firefox Developer edition browser?

----

It looks like this a react issue https://github.com/facebook/react/issues/16402, and it was addressed in this PR https://github.com/facebook/react/pull/16578

Going to close.
