### ISSUE TITLE
Search bar throws 500 on docs website

### ISSUE THREAD

**Issue by bmstefanski** [chakra-ui/chakra-ui#4195]
# 🐛 Bug report

Chakra-ui's website throws `An unexpected error has occurred.` after typing `mode(` in the search bar

## 💥 Steps to reproduce

1. Go to https://chakra-ui.com/docs
2. Click on Search bar
3. Type in `mode(`
4. See the error

## 💻 Link to reproduction

Not-related

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     Not-related       |
| Browser          |     Chrome       |
| Operating System |    MacOS        |

## 📝 Additional information

![image](https://user-images.githubusercontent.com/28964599/121221580-ff0a4200-c885-11eb-9aef-3b2c6cb24586.png)

**Comment by anubra266** [comment]
Happens as long as you put parentheses, because it's not escaped.
