### ISSUE TITLE
a11y issue with Portal elements creating "clickable" elements

### ISSUE THREAD

**Issue by santialbo** [chakra-ui/chakra-ui#4205]
# 🐛 Bug report

When using Portals, a DOM element is created on the body with a click handler. On apps with many portalled elements a bunch of these "clickable" elements are created at the end of the page.

This causes some VoiceOvers (_Nvda 2020.4 NV Access_ in particular) to announce them and read

>clickable, clickable, clickable, clickable, clickable, clickable, clickable, clickable, clickable...

which is a bit annoying for people using voiceovers

### Image from Firefox a11y report
<img width="664" alt="Screenshot 2021-06-10 at 11 03 22" src="https://user-images.githubusercontent.com/1557563/121497980-4571b500-c9dc-11eb-98c5-11a55d876d10.png">

### Video
The video has no sound, but when navigating it reads "clickable, clickable, clickable, ..." on these non opened menu and popover

https://user-images.githubusercontent.com/1557563/121498760-06902f00-c9dd-11eb-8f26-87b6a8164ce0.mov

## 💥 Steps to reproduce
1. Create an element with a Portal: Menu, Popover
2. See created element with class `chakra-portal` at the end of the page
3. Same happens with the `chakra-toast-portal`.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/thirsty-silence-vqj6d?file=/src/index.tsx

## 🧐 Expected behavior
This clickable elements shouldn't be created unless the elements (menu or popover) are opened.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       1.6.3     |
| Browser          |       Edge 91.0.864.37       |
| Operating System |          Windows 10 64B  |
| VoiceOver| Nvda 2020.4 NV Access|

**Comment by segunadebayo** [comment]
As far as I can remember, `Portal` creates a `div` element that isn't clickable so I'm wondering where this issue around "clickable" might be coming from.

**Comment by santialbo** [comment]
> As far as I can remember, `Portal` creates a `div` element that isn't clickable so I'm wondering where this issue around "clickable" might be coming from.

Some screen readers will consider anything with a click handler as clickable. I'm not sure why those elements have event handlers attached to them.

**Comment by anubra266** [comment]
cc @segunadebayo
