### ISSUE TITLE
Dead links to Discord

### ISSUE THREAD

**Issue by Ningaro** [chakra-ui/chakra-ui#4207]
# 🐛 Bug report

## 💥 Steps to reproduce

There are non-working links to Discord both on the site and in the repository. 
Below is a list of files

* [README.md](https://github.com/chakra-ui/chakra-ui/blob/main/README.md#L17)
* [website/next-redirect.js](https://github.com/chakra-ui/chakra-ui/blob/main/website/next-redirect.js#L5)
* [website/configs/site-config.ts](https://github.com/chakra-ui/chakra-ui/blob/main/website/configs/site-config.ts#L26)
* [website/src/components/discord-strip.tsx](https://github.com/chakra-ui/chakra-ui/blob/main/website/src/components/discord-strip.tsx#L36)

## 🧐 Expected behavior

Would love to get some kind of solution to this problem, as currently the links are only misleading 🤯

## 🧭 Possible Solution

1. Remove links to Discord, since now this is only an option for Chakra UI Pro(?)
    <details>
    <summary>Screenshot from pro.chakra-ui.com</summary>
    <img src="https://user-images.githubusercontent.com/23503775/121567239-06b51c80-ca27-11eb-8190-a3f38ba4431d.png"/>
    </details>
2. Create another server / make new links to Discord

**Comment by with-heart** [comment]
Thanks for catching this @Ningaro! @allcontributors please add @Ningaro for bug

We have a community Discord at https://discorg.gg/chakra-ui. I think the private Discord is for paying Chakra UI Pro members, though @segunadebayo would need to confirm.
