### ISSUE TITLE
Not able to display Icon with InputLeftElement

### ISSUE THREAD

**Issue by quinnliu** [chakra-ui/chakra-ui#4221]
```
<Stack spacing={4}>
  <InputLeftElement
    children={<Search2Icon color="gray.300" />}
  />
  <Input
    id={field.name}
    onChange={field.onChange}
    variant="filled"
    w={inputWidthPixels}
    focusBorderColor="primary.100"
    placeholder={placeholder}
  />
</Stack>
```

I'm expecting the above code to display a Search Icon inside the Input like in https://chakra-ui.com/docs/form/input

But I'm getting the error 

```
Uncaught (in promise) ContextError: useStyles: `styles` is undefined. Seems you forgot to wrap the components in `<StylesProvider />` 
```

I'm not sure how to interpret this error message.

I'm on MacOS 15.17, Chrome Version 91.0.4472.101 (Official Build) (x86_64), node v14.16.1, 

```
    "@chakra-ui/icons": "^1.0.2",
    "@chakra-ui/react": "^1.0.4",
    "@chakra-ui/theme-tools": "^1.0.2",
    "@chakra-ui/utils": "^1.0.2",
    "react": "^17.0.1",
    "typescript": "^4.3.2",
```

**Comment by anubra266** [comment]
The context is undefined because it must be wrapped in an `InputGroup` component. Check [here](https://chakra-ui.com/docs/form/input#add-elements-inside-input)

**Comment by segunadebayo** [comment]
`InputLeftElement` is designed to be used within `InputGroup`. Please wrap with `InputGroup`
