### ISSUE TITLE
useDisclosure does not open modal from another component when supplied with modal id

### ISSUE THREAD

**Issue by mah51** [chakra-ui/chakra-ui#4223]
# 🐛 Bug report

useDisclosure with id passed will not open / close a specific modal

## 💥 Steps to reproduce

1. create modal component
2. try to open mondal from different component with useDisclosure({id: 'id-that-is-specified-on-modal-component-props'})
3. Does not open modal on call of onOpen() function

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/sleepy-glade-wef2y?file=/src/index.js

## 🧐 Expected behavior

Modal opens on button click in external component

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |    latest        |
| Browser          |   firefox         |
| Operating System |      windows10      |

**Comment by anubra266** [comment]
Hi! that's not how it works. Check the implementation[here](https://chakra-ui.com/docs/overlay/modal#usage)

**Comment by mah51** [comment]
Hi, yeah i understand the basic implementation. But don't understand when you want to open the modal from a different component. I assumed the id prop allowed you to open modals with a specified I'd from any component. Thanks

**Comment by anubra266** [comment]
The Id is used internally, for accessibility `aria-controls` prop. Check the usage [here](https://github.com/chakra-ui/chakra-ui/blob/main/packages/hooks/src/use-disclosure.ts#L61)

**Comment by mah51** [comment]
Oh ok. So there's no way to open a model without passing the onOpen function as a prop down components?

**Comment by anubra266** [comment]
Yeah...if you're problem is props drilling, then use the React Context API

**Comment by mah51** [comment]
Ok thanks. Do you think it's worth adding this as a feature to modals? Having it built in would be advantageous I think.

**Comment by anubra266** [comment]
If you could explain your implementation better, I don't really understand it yet.

**Comment by mah51** [comment]
So from my understanding you can only call useDisclosure in the component you are defining the model in unless you prop drill the onOpen and onClose functions through components but what I am suggesting is being able to pass an id into useDisclosure and then you can call it from any component to open the modal with the specified id.

**Comment by anubra266** [comment]
Hmm...I get the concept now. Can't think of any way to implement that yet though.

**Comment by segunadebayo** [comment]
`useDisclosure` isn't designed for this use case. Please consider an alternative solution to achieve this.

**Comment by lzambarda** [comment]
I know this has been closed but I ended up using `useDisclosure` in the parent component and passing it down to the child. Not sure if it is an anti-pattern but surely made things simpler for me @mah51 !
