### ISSUE TITLE
Can't append to MenuItem to MenuList using React Ref

### ISSUE THREAD

**Issue by pszafer** [chakra-ui/chakra-ui#4227]
# 🐛 Bug report

I'm trying to append MenuItem to Menu in other component of my code.
Unfortunately I end up with error `Cannot destructure property 'setFocusedIndex' of 'menu' as it is undefined.`

## 💥 Steps to reproduce

1. Go to https://codesandbox.io/s/menu-kvmte?file=/src/index.js
2. See error

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/menu-kvmte?file=/src/index.js

## 🧐 Expected behavior

Possibility to add menu item anywhere.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |    1.6.3        |
| Browser          |     Chrome 91       |
| Operating System |        Arch Linux    |

**Comment by segunadebayo** [comment]
Hi @pszafer,

You can't use `MenuItem` outside the `MenuList` component. Considering moving the `ChildComponent` into the `MenuList` component.
