### ISSUE TITLE
X axis padding on unstyled buttons

### ISSUE THREAD

**Issue by anubra266** [chakra-ui/chakra-ui#4228]
# 🐛 Bug report

When a `Button` takes the `unstyled` variant any X- axis padding is not applied

**Comment by m0nae** [comment]
Did you ever end up finding a fix to this?

**Comment by anubra266** [comment]
> Did you ever end up finding a fix to this?

Nah.

**Comment by segunadebayo** [comment]
This is happening because `variant=unstyled` doesn't really affect `size`. we'll fix this in the next major.

For now, please set the `size` to `null` to complete remove the size-related styles, or pass `px={0}`
