### ISSUE TITLE
[Modal] Mouse up outside closes the modal

### ISSUE THREAD

**Issue by ProsperDevelopment** [chakra-ui/chakra-ui#423]
**Describe the bug**
Modal closes when mouse button is released (mouse up) outside of modal 

![Peek 2020-02-19 14-30](https://user-images.githubusercontent.com/6404440/74838966-c4913480-5324-11ea-80de-781e9eef10ec.gif)

**Expected Behavior**
Modal should not close on mouse release outside of modal 

**To Reproduce**
1. Open modal
2. Press mouse down inside modal
3. Move cursor out of modal
4. Release mouse button

**Comment by segunadebayo** [comment]
@ProsperDevelopment,

Yes, we're aware of this issue and are working to fix it in the `dev-ts` branch.

Thanks for bringing it up.

**Comment by segunadebayo** [comment]
This has been fixed in the dev-ts branch and will be made available in the next release.
