### ISSUE TITLE
[Toast] useToast() returns a new object each time

### ISSUE THREAD

**Issue by feross** [chakra-ui/chakra-ui#4230]
# 🐛 Bug report

This issue seems to have returned: https://github.com/chakra-ui/chakra-ui/issues/1448

Each time we call `useToast` hook, a new object is returned.

## 💥 Steps to reproduce

Same as previous issue: https://github.com/chakra-ui/chakra-ui/issues/1448

## 💻 Link to reproduction

Same as previous issue: https://github.com/chakra-ui/chakra-ui/issues/1448

## 🧐 Expected behavior

The object returned by `useToast` hook should always be from the same reference.

## 🧭 Possible Solution

 I think perhaps the `useChakra()` hook on this line (https://github.com/chakra-ui/chakra-ui/blob/ebda07095bffd9b3135c5d19803a3a08397b78ef/packages/toast/src/use-toast.tsx#L191) is returning new object references each time which is causing the `useCallback` to have no effect.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.6.3         |
| Browser          |   Chrome         |
| Operating System |    macOS latest        |

**Comment by jamesopti** [comment]
FYI I thought this was happening to me too, but it turned out my top level provider was re-rendering and providing the theme inline:

```ts
<ChakraProvider
  theme={extendTheme(rootTheme, { ...
/>
```

Hoisting the `extendTheme` call out of the render path solved this issue for me.

**Comment by noobinthisgame** [comment]
@TimKolberger According to this PR https://github.com/chakra-ui/chakra-ui/pull/5493 this issue should be closed if im not mistaken.

**Comment by TimKolberger** [comment]
Yes, this PR is merged to main, but not yet released.
We'll have a release ready in a few days 🚀
