### ISSUE TITLE
<Image> onLoad & onError never gets called when using with srcSet

### ISSUE THREAD

**Issue by lemnis** [chakra-ui/chakra-ui#4234]
When using a `Image` with a onLoad or onError, it doesn't get called when used with a srcSet. The `Img` is working as expected.

# 🐛 Bug report

## 💥 Steps to reproduce

Open the sandbox and see for  number one (the `Image`) only the native event is getting logged.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/friendly-butterfly-6byy1?file=/src/index.tsx

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.6.3 |
| Browser          | Chrome 91 |
| Operating System | macOs 11 |

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
