### ISSUE TITLE
[Editable]: Call onCancel when submitOnBlur is false

### ISSUE THREAD

**Issue by Saifadin** [chakra-ui/chakra-ui#424]
**Is your feature request related to a problem? Please describe.**
When the `Editable` Component is used with Custom Handling and the field is blurred, the `isEditing` prop never changes to false. I am currently using it like this:

```
<Editable defaultValue={email} mb="2" fontFamily="heading" position="relative" submitOnBlur={false}>
  {({ isEditing, onSubmit, onCancel }) => {
    return (
      <>
        <EditablePreview />
        <EditableInput />
        {isEditing ? (
          <Box position="absolute" right="0" bottom="-32px">
            <ButtonGroup justifyContent="center" size="xs">
              <IconButton icon="check" aria-label="Check" onClick={onSubmit} />
              <IconButton icon="close" aria-label="cancel" onClick={onCancel} />
            </ButtonGroup>
          </Box>
        ) : null}
      </>
    );
  }}
</Editable>
```

**Describe the solution you'd like**
The solution I would suggest is to return to the initialValue on Blur when `submitOnBlur={false}` is set. Basically call `onCancel` instead of `onSubmit` here: 

https://github.com/chakra-ui/chakra-ui/blob/06b65dd4117d8c1207d3ed80f4932d8c2b0d7dee/packages/chakra-ui/src/Editable/index.js#L218

This could be changed to `submitOnBlur ? onSubmit() : onCancel();`

**Additional context**
I can create an MR if this behavior is desired. I think this would be a better UX in this specific use case.

**Comment by segunadebayo** [comment]
Hi @Saifadin,

Thanks for this suggestion. It sounds like a good idea. I'll look into it for the next release.

**Comment by Saifadin** [comment]
@segunadebayo I will create a MR and you can look into it :)

**Comment by stefanbugge** [comment]
It seems to me that this newly added `onCancel()` call in the `onBlur` handler basically blocks the `onSubmit` renderProp from ever being called when using custom controls. I am guessing the `onBlur` is triggered immediately and the custom "check" button never receives the mouse event before it has been unmounted (due to the `onCancel` call).
As a workaround I can add a custom noop `onBlur` handler to `<EditableInput />` to bypass this.

**Comment by Staz** [comment]
Hey, I'm experiencing this same issue on v1.6.4. Can we please get this "Call onCancel when submitOnBlur is false
" behaviour back again?
