### ISSUE TITLE
Remove `noreferrer` attribute from `<Link isExternal />`

### ISSUE THREAD

**Issue by feross** [chakra-ui/chakra-ui#4243]
# 🚀 Feature request

> Please describe your request in one or two sentences.

The `<Link>` component adds a `noreferrer` attribute when you include the `isExternal` attribute. I think we should remove this since it prevents the `Referer` header from being sent on link clicks to external sites.

## 🧱 Problem Statement / Justification

> Please provide valid reason(s) why this should added to Chakra UI.
>
> If this feaure is related to a problem you've noticed. Mention it as well

I believe the original reason that this was included was for security reasons, to prevent `window.opener` from being set on the new tab, which would allow the tab to navigate the opening page. However, we have a better way to enforce that in modern browser. Specifically, the `noopener` attribute, which is already present.

Docs on each attribute:

- https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noreferrer
- https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noopener

Before `noopener`, the only way to get the protection from the `window.opener` security risk was to use `noreferrer`. But we don't need that anymore as the browser support for `noopener` is great (it works in all browsers that Chakra UI supports).

## ✅ Proposed solution or API

> Please provide code snippets, gists, or links to the ideal design or API

Remove `noreferrer` from this line: https://github.com/chakra-ui/chakra-ui/blob/9747c534327145fb4a7e3e6c88a3ecfb7cf1b4fb/packages/layout/src/link.tsx#L40

## ↩️ Alternatives

> What alternative solutions have you considered before making this request?

We could keep it in place, but I think sending referrer by default is valuable. The browser's default referrer policy these days is `strict-origin-when-cross-origin`:

> Send the origin, path, and querystring when performing a same-origin request. For cross-origin requests send the origin (only) when the protocol security level stays same (HTTPS→HTTPS). Don't send the Referer header to less secure destinations (HTTPS→HTTP).

See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

Which seems like a better default than suppressing the referrer for all external links.

## 📝 Additional Information

> What resources (links, screenshots, etc.) do you have to assist this effort?

As previously mentioned:

- https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noreferrer
- https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noopener

**Comment by prerana1821** [comment]
I would like to take this issue.

**Comment by Howard86** [comment]
Hmmm currently im just create a new Link component with a custom props to handle this kind of external links

I am also curious why it was added initially together with `no opener`...

**Comment by anubra266** [comment]
Feel free to open a PR @Howard86

**Comment by Howard86** [comment]
> Feel free to open a PR @Howard86

Sure, If @prerana1821 is not working on it, I don't mind creating a PR.

The questions is, which of the following do you think is more appropriate?

1. add new props something like `isReferred` to address this new change (same as `isExternal` but without `noopener`
2. remove `noopener` in current `isExternal` condition

Some reference:
https://web.dev/external-anchors-use-rel-noopener/

**Comment by Howard86** [comment]
@anubra266 any suggestion, please?

**Comment by anubra266** [comment]
cc @segunadebayo

**Comment by TimKolberger** [comment]
@Howard86 kindly go ahead and open a PR to remove referrer from the rel attribute. 
Please double check what to remove, because noopener should stay there as default for security reasons.

The developer is still able to override the rel attribute, if they need to.
