### ISSUE TITLE
IconButton does not use themed Button borderRadius

### ISSUE THREAD

**Issue by Mattinton** [chakra-ui/chakra-ui#4244]
# 🐛 Bug report

When using an IconButton component, it does not use the default borderRadius in the Button component theme.

## 💥 Steps to reproduce

Use an IconButton component with changes to the default borderRadius in your custom theme.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/late-leftpad-9gqvc?file=/src/index.tsx

## 🧐 Expected behavior

IconButton should use the same themed borderRadius

## 🧭 Possible Solution

borderRadius set [here](https://github.com/chakra-ui/chakra-ui/blob/main/packages/button/src/icon-button.tsx#L50) should be set to undefined if isRound is not set, not 'md'. This would then default to the themed radius.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.6.3 |
| Browser          | Chrome |
| Operating System | macOS |

**Comment by TheDavidDelta** [comment]
This doesn't solve the problem because it makes the IconButton remove any inhereted value from Button or its own theme. It can be tested in your own CodeSandbox, which can be updated to the last Chakra version that cointains this change.

**Comment by Mattinton** [comment]
> This doesn't solve the problem because it makes the IconButton remove any inhereted value from Button or its own theme. It can be tested in your own CodeSandbox, which can be updated to the last Chakra version that cointains this change.

This was the required fix, however it identified an underlying problem with how styles were applied see [here](https://github.com/chakra-ui/chakra-ui/pull/4265#issuecomment-868174433). I imagine this fix will be in the next release.

**Comment by TheDavidDelta** [comment]
Thanks for the reply. I wish next version rolls out quickly cause I'm also having another problem with previouses.

**Comment by AlexandruCalinica** [comment]
Looking forward for the next release to fix this.
