### ISSUE TITLE
Add tomato colorScheme

### ISSUE THREAD

**Issue by unsphere** [chakra-ui/chakra-ui#4246]
I really like to use tomato. Could you please add a colorScheme for it? 👍

**Comment by anubra266** [comment]
You can extend the theme, and add it yourself. Get the scheme here,

https://smart-swatch.netlify.app/#tomato

**Comment by unsphere** [comment]
> You can extend the theme, and add it yourself. Get the scheme here,
> 
> https://smart-swatch.netlify.app/#tomato

Ah perfect, thank you very much! Didn't know the link.
