### ISSUE TITLE
withDefaultProps not working with Text & Tab components

### ISSUE THREAD

**Issue by amosbastian** [chakra-ui/chakra-ui#4247]
# 🐛 Bug report

I am trying to make the default `fontSize` for `Text` and `Tab` components to be `sm`, so I thought I'd use the `withDefaultProps` function as described [here](https://chakra-ui.com/docs/theming/customize-theme#theme-extension-withdefaultprops). Unfortunately the following is not working:

```
export default extendTheme(
  overrides,
  withDefaultProps({
    defaultProps: {
      fontSize: "sm",
    },
    components: ["Text", "Tab"],
  }),
  withDefaultColorScheme({ colorScheme: "primary" }),
);
```

## 💥 Steps to reproduce

Extend your theme and add

```
withDefaultProps({
  defaultProps: {
    fontSize: "sm",
  },
  components: ["Text", "Tab"],
}),
```

and you will see the default `fontSize` stays `md`.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/jolly-sound-is9cx?file=/src/index.tsx

## 🧐 Expected behavior

It should pass the prop `fontSize="sm"` to all `Text` and `Tab` components.

## 📝 Additional information

I assumed it should work like this, but of course I could be wrong.

**Comment by segunadebayo** [comment]
Hi @amosbastian,

`withDefaultProps` is designed to be used for the theming-related props `colorScheme`, `variant` and `colorScheme`, not for general styling purposes.

Please add these props to components themselves if you need to style them.

Hope this helps.
