### ISSUE TITLE
Video component in Chakra UI

### ISSUE THREAD

**Issue by MichaelGrigoryan25** [chakra-ui/chakra-ui#4248]
# 🚀 Feature request

It'd be good to have a Video component in Chakra UI

## 🧱 Problem Statement / Justification

It's hard when trying to mix a native HTML `video` tag with Chakra UI's Image tag.

## ✅ Proposed solution or API

Well, we could use something like this

```jsx
<Video 
    h={100} 
    w={200} b
    boxShadow={"sm"} 
    sources={["source1", "source2", "source3"]} 
    controls={true} 
    autoplay={true} 
    poster={"link to poster"} 
    sliderColor={"red.500"}
    sliderThumbnail={<AiArrowRight />}
    theme={"orange.500"} // the color that the sliders/buttons will all have
    loop={true} />
```

## ↩️ Alternatives

I have tried making getting the image mime type on file upload request and storing it in separate props. Afterward, I made a component that'd check the type and return an image or a video based on the type.

## 📝 Additional Information

Here's the code of my alternative solution if that'd help in any way:

```jsx
const Media = ({ url, mimetype, ...rest }) => {
  if (mimetype === "image") return <Image {...rest} src={url} />;
  else if (mimetype === "video") {
    return (
      <video>
        <source src={url}></source>
        Your browser does not support HTML5 video
      </video>
    );
  } else return null;
};
```

With the array of  `sources`, the user will be able to have as many sources as he wants and the component will generate some code like this

```jsx
...
{sources.map((source, index) => { return <source src={source}></source> })}
...
```

**Comment by segunadebayo** [comment]
Hi @MichaelGrigoryan25,

I'd love to have a Video component to Chakra UI but it's outside our roadmap or feature list for now.

Please consider creating one yourself, publish it to NPM and we'll be happy to promote it for you.

Cheers.

**Comment by MichaelGrigoryan25** [comment]
No probs!

**Comment by hugobqd** [comment]
> Hi @MichaelGrigoryan25,
> 
> I'd love to have a Video component to Chakra UI but it's outside our roadmap or feature list for now.
> 
> Please consider creating one yourself, publish it to NPM and we'll be happy to promote it for you.
> 
> Cheers.

Hi! @segunadebayo 
Is there a place where we can check out the roadmap or the feature list? Thanks

**Comment by MichaelGrigoryan25** [comment]
Hey @hugobqd . Here's the [roadmap link](https://github.com/chakra-ui/chakra-ui/projects/6) (it is in the projects tab)
