### ISSUE TITLE
align items doesn't work at all

### ISSUE THREAD

**Issue by clementbowe14** [chakra-ui/chakra-ui#4249]
# 🐛 Bug report

## 💥 Steps to reproduce

1. I tried to manipulate a set of boxes using the align property in props and it did not affect the boxes.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/align-bug-h8ggn?file=/src/App.js

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | ^1.6.3           |
| Browser          |   chrome         |
| Operating System |  windows          |

## 📝 Additional information
Steps to produce the bug:

**Comment by segunadebayo** [comment]
Hey @clementbowe14,

It seems to work in the CSB you send: 
<img width="1431" alt="Screen Shot 2021-06-18 at 3 15 08 PM" src="https://user-images.githubusercontent.com/6916170/122553003-18f71200-d048-11eb-9526-f1f9ab867260.png">

Please check your HTML structure and tweak the styles to get it working as expected.

Cheers.
