### ISSUE TITLE
[Theme] gatsby-plugin-chakra-ui

### ISSUE THREAD

**Issue by jhonaikerf** [chakra-ui/chakra-ui#425]
I am using the plugin with gatsby-starter-blog, following the documentation with src / gatsby-plugin-chakra-ui / theme.js
And the file is ignored.

**Comment by trevorblades** [comment]
This is a duplicate of #347. There's some more info in that issue about the cause of this error, and it will be fixed when #362 gets merged/released.

**Comment by uselessdev** [comment]
Hi, @trevorblades I'm getting this same error here and I don't know if I've messed up some config or is the same bug.
