### ISSUE TITLE
`useBreakpointValue` always returns `undefined` on initial render

### ISSUE THREAD

**Issue by stuart-williams** [chakra-ui/chakra-ui#4251]
# 🐛 Bug report

`useBreakpointValue` always returns `undefined` on initial render. 

<img width="231" alt="Screenshot 2021-06-18 at 07 31 43" src="https://user-images.githubusercontent.com/2526507/122516926-47a0c880-d007-11eb-8363-7276715b0b26.png">

## 💥 Steps to reproduce

```
console.log(window.matchMedia);
const value = useBreakpointValue({ base: 1, sm: 2, md: 3, lg: 4 });
console.log(value);
```

## 💻 Link to reproduction

https://codesandbox.io/s/infallible-haze-3mhq0

## 🧐 Expected behavior

As the initial render is client side and `window.matchMedia` is available I would expect the correct breakpoint value to be return immediately.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       1.6.3     |
| Browser          |     Chrome       |
| Operating System |      Mac OS      |

**Comment by anubra266** [comment]
Fixed. Refer to Issue #3018.
