### ISSUE TITLE
Code should be removed?

### ISSUE THREAD

**Issue by bl-ue** [chakra-ui/chakra-ui#4259]
The code at

https://github.com/chakra-ui/chakra-ui/blob/db46840efea41d66c4d7c8f59af7d944dfb0cbd9/packages/radio/src/use-radio.ts#L211-L221

should probably be removed since https://github.com/facebook/react/issues/18591 was closed earlier this year.

cc @with-heart because you appear to be subscribed to that issue.

**Comment by kristojorg** [comment]
This scheduleMicrotask also appears to be causing an issue with focus on custom radio buttons
