### ISSUE TITLE
Understand strategies for shipping/publishing chakra

### ISSUE THREAD

**Issue by kamleshchandnani** [chakra-ui/chakra-ui#4262]
### Discussed in https://github.com/chakra-ui/chakra-ui/discussions/4232

<div type='discussions-op-text'>

<sup>Originally posted by **kamleshchandnani** June 16, 2021</sup>
I wanted to ask, if the strategy of shipping chakra is documented anywhere? Like I would like to understand what was the reason of just transpiling chakra with babel and publishing instead of bundling it using rollup or something else.

For more context you can read the discussions in [this tweet](https://twitter.com/_kamlesh_/status/1404701659180134400)</div>

**Comment by cschroeter** [comment]
We offer Chakra UI in ESM and as CJS variant.

The ES modules are essential to allow tools like Webpack, Snowpack or Vite to reach their full potential (e.g. ThreeShaking).
If we would bundle Chakra UI with Rollup, these tools would not work anymore as intended.

Last but not least CJS modules are for Jest - as this tool can't handle ES modules at the moment.

Hope that helps to understand why we do certain things.
