### ISSUE TITLE
Rollup fails to bundle chakra component lib

### ISSUE THREAD

**Issue by export-mike** [chakra-ui/chakra-ui#427]
I'm using create-react-library and trying to use chakra-ui as the core.

I've found the lib exenv to cause issues with rollup and how its exported. I notice you have a copy of the canUseDOM in another package chakra-ui-docs so I've copied this and place it into utils.

PR to follow.

**Comment by segunadebayo** [comment]
Hi @export-mike.

Since this has been fixed, I'll close it for now.

Thanks for the PR earlier. I will release a patch soon.
