### ISSUE TITLE
Menu shadow disappears when not hovering while using focus-visible

### ISSUE THREAD

**Issue by amosbastian** [chakra-ui/chakra-ui#4276]
# 🐛 Bug report

When using `focus-visible` to remove the default outline it inadvertently makes the box shadow of the menu disappear when you stop hovering over it.

## 💥 Steps to reproduce

1. import `focus-visible/dist/focus-visible` in your app
2. Create a menu
3. Open menu and stop hovering over it
4. See box shadow disappear

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/jolly-sound-is9cx?file=/src/index.tsx

## 🧐 Expected behaviour

The box shadow should not disappear.

## 🧭 Possible Solution

No idea, but could be related to https://github.com/chakra-ui/chakra-ui/issues/4041

**Comment by StringKe** [comment]
Does anyone know how to fix it? Or how to remove the focus effect without affecting `dark mode `

**Comment by gabiduarte** [comment]
I'm facing the same issue, this workaround solved it for me: https://github.com/chakra-ui/chakra-ui/issues/3553#issuecomment-843043883

**Comment by taitems** [comment]
Not an elegant fix, but my workaround was to go into your theme/styles section
```js
export const theme = extendTheme({
    ///
    // other stuff
    //
    styles: {
      global: {
        '.chakra-menu__menu-list:focus:not([data-focus-visible-added])': {
          boxShadow: 'var(--chakra-shadows-dark-lg)'
        }
      }
    }
  });
  
```
