### ISSUE TITLE
Avatar rounded prop does not translate to underlying img tag

### ISSUE THREAD

**Issue by JohannesKlauss** [chakra-ui/chakra-ui#4288]
### Description

When I change the `rounded` prop on the `Avatar` component I expect the embedded image to have the same rounded prop, but instead is keeps the `var(--chakra-radii-full)` as `border-radius`

### Link to Reproduction

https://codesandbox.io/s/serverless-dust-ek03i?file=/src/index.tsx

### Steps to reproduce

1. Go to 'https://codesandbox.io/s/serverless-dust-ek03i?file=/src/index.tsx'
2. Check the resulting rendering
3. The background of the avatar component with a smaller border radius is still visible and the image does not have the same given border radius

### Chakra UI Version

1.6.4

### Browser

Google Chrome 93

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by gifaeriyanto** [comment]
Use `borderRadius` instead of `rounded`. Regarding `rounded-*` they already discussed it in this issue https://github.com/chakra-ui/chakra-ui/issues/388, but yeah it's still a bit confusing because we still able to use `rounded` properties. cc @segunadebayo

**Comment by anubra266** [comment]
@JohannesKlauss Could you close since it has been resolved?

**Comment by JohannesKlauss** [comment]
Sure thing
