### ISSUE TITLE
Document MenuList/Popper overflow-y bug

### ISSUE THREAD

**Issue by jaredpalmer** [chakra-ui/chakra-ui#429]
Popper has difficulty calculating positioning when parent has `overflow-y: hidden` (https://github.com/popperjs/popper-core/issues/535). To fix this, you just have to pass to Popper instance

```
modifiers: {
  preventOverflow: {
    boundariesElement: 'scrollParent'
  }    
}
```

To do this in Chakra, you can just do this:

```jsx
<Menu>
  <MenuButton>{/* .. */}</MenuButton>
  <MenuList
    modifiers={{
      preventOverflow: {
        boundariesElement: "scrollParent"
      }
    }}
  >
    {/* .. */}
  </MenuList>
</Menu>
```

**Comment by segunadebayo** [comment]
@jaredpalmer. Thanks for this.

I'll test this as well for the next release of all popper elements. It seems it has been fixed in popper.js V2.

**Comment by yasirtrimulabs** [comment]
Didn't work for me, any other workaround
<img width="440" alt="Screen Shot 2022-08-04 at 3 38 52 AM" src="https://user-images.githubusercontent.com/62023757/182724609-85b61ba1-856d-4a2d-a0e4-bb11a410666b.png">

**Comment by 0xlarry** [comment]
> Didn't work for me, any other workaround <img alt="Screen Shot 2022-08-04 at 3 38 52 AM" width="440" src="https://user-images.githubusercontent.com/62023757/182724609-85b61ba1-856d-4a2d-a0e4-bb11a410666b.png">

want to do this - is this resolved?

**Comment by yasirtrimulabs** [comment]
@0xlarry  I ended up using shorter strings as options so it won't overflow
