### ISSUE TITLE
bgColor prop not working on MenuItem

### ISSUE THREAD

**Issue by DVGY** [chakra-ui/chakra-ui#4291]
### Description

When I use bgColor props inside MenuItem, the bgColor props works only if I hover onto that MenuItem

### Link to Reproduction

https://chakra-ui.com/docs/overlay/menu#usage

### Steps to reproduce

1. Go to [docs example](https://chakra-ui.com/docs/overlay/menu#usage)
2. Change 
From this 
`<MenuItem >Download</MenuItem>`
To this
`<MenuItem bgColor="teal.300">Download</MenuItem>`
3. Now click on Open button and see, the bgColor of the MenuItem still has not changed. (Bug)
4. Hover on MenuItem and color appears

### Chakra UI Version

1.6.3

### Browser

Chrome 91

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by anubra266** [comment]
Hi, the color actually changes. The reason you don't see the color at first is because, the first option is focused by default, and focused Items will use a different bg. Try setting that background on any Item that's not the first one, you'll see it works because they are not focused or hovered.

**Comment by DVGY** [comment]
> Hi, the color actually changes. The reason you don't see the color at first is because, the first option is focused by default, and focused Items will use a different bg. Try setting that background on any Item that's not the first one, you'll see it works because they are not focused or hovered.

Thanks
