### ISSUE TITLE
Tooling functions such as darken, lighten, etc. don't seem to be working correctly

### ISSUE THREAD

**Issue by northernisle** [chakra-ui/chakra-ui#4293]
### Description

When the `darken` function is called with the `amount` param ranging from 0 to 1 nothing happens, however when the `amount` value exceeds it 1 (e.g. 20) the function seems to be working

### Link to Reproduction

https://codesandbox.io/s/kind-nobel-px1cv

### Steps to reproduce

1. Open the sandbox above.
2. The left button is using the darken function according to the documentation with value specified as 0.5
3. The right button is the exact same except the darken function receives a value of 20.

### Chakra UI Version

1.6.4

### Browser

Firefox 89.0.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

After researching a bit it `darken` uses [TinyColor](https://github.com/bgrins/TinyColor) under the hood. According to Chakra's docs the value should range from 0 to 1, whilst TinyColor [specifies](https://github.com/bgrins/TinyColor#darken) that the value should be from 0 to 100. Either the documentation should be updated to reflect this or the code should be changed to scale the supplied `amount` param to TinyColor's specs.

**Comment by segunadebayo** [comment]
This isn't technically a bug. It's more of an error in the JS Doc comments we added to these functions, the amount can be `0-100` as defined in the TinyColor.

We'll tweak the comments to reflect this shortly and release an update.

Thanks
