### ISSUE TITLE
Custom breakpoints with pixel values break media query related hooks

### ISSUE THREAD

**Issue by JDansercoer** [chakra-ui/chakra-ui#4301]
### Description

After adding custom breakpoints with pixel values via extendTheme, the resulting theme will contain breakpoints consisting of both em and px values. This messes with the createMediaQuery function as this orders them based on the parsed numbers.

### Link to Reproduction

Can't add one, since a sandbox results in endless loops and freezes your browser

### Steps to reproduce

1. Add a theme with custom breakpoints
```
const theme = extendTheme({
  breakpoints: {
    tablet: '768px',
    laptop: '1024px'
  }
});
```
2. Check the content of `theme`. The breakpoints will be a combination of both `em` and `px` values.
3. Try to use `useBreakpointValue`. This will result in endless loops, because there are media queries that match both and `em` value and a `px` value.

### Chakra UI Version

1.6.4

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by aboveyunhai** [comment]
@JDansercoer 
I encounter the similar issues but never realize that `2xl` is also a default options which is in doc. 
The best way I can think of right now is to completely override all the default breakpoints (`sm` - `2xl`) into `px`, you probably need to convert `em` to `px` in breakpoints, which might be somehow annoy.

**Comment by aboveyunhai** [comment]
Hi @with-heart 
this part of codes is somehow missing leading cuz it lacks of `2xl` and causes the infinite `setState` issues.
Also, when we define custom breakpoint with `px` unit, wee need to override all default `em` breakpoints, maybe it need to be clarified in the doc ? I am not exactly sure this is a bug or doc issues. 
https://chakra-ui.com/docs/features/responsive-styles#customizing-breakpoints,
I had heart ` createBreakpoints({})` will be removed in the future.

**Comment by JDansercoer** [comment]
> @JDansercoer
> I encounter the similar issues but never realize that `2xl` is also a default options which is in doc.
> The best way I can think of right now is to completely override all the default breakpoints (`sm` - `2xl`) into `px`, you probably need to convert `em` to `px` in breakpoints, which might be somehow annoy.

We currently solved this by just overriding the breakpoints fully to have complete control over them, might be a solution for you as well
