### ISSUE TITLE
Stack Prop Instead of (or in addition to) the Stack Component

### ISSUE THREAD

**Issue by thecodeclimber** [chakra-ui/chakra-ui#4308]
### Description

I would like to suggest adding some stack props that do the same job as the Stack component (namely give spacing between child elements). I'm thinking of something similar to the tailwindcss space classes:  https://tailwindcss.com/docs/space.

Here's an initial idea of a possible syntax: 

```
<Flex hstack={5}>...</Flex>
<Box vstack="24px">...</Box>
<Flex stack={5}>...</Box> // horizontal and  vertical
<Box stack-direction={["column", "row"]} stack={["5", "3"]}...</Box>  // responsive
```

### Problem Statement/Justification

I personally would prefer not to add unnecessary components to my code when I can achieve the same solution using props.  Or, put otherwise, we don't have `padding` components and `margin` components (or `width` components or `height` components, etc.).  We relegate those to props.  It seems to me that we should do the same with child margins (or padding) if possible.  It's more elegant and allows us to remove an unnecessary component and have leaner and easier to reason about code.

### Proposed Solution or API

https://gist.github.com/thecodeclimber/322367501766f70215f4c4239035c462

**Comment by segunadebayo** [comment]
Hi @thecodeclimber,

This sounds interesting but it is beyond the scope of V1 for now.

I see the benefits of handling all stack-related styles with props but I think the component approach is easier to reason about compared to the "all things as props" approach.

We're not trying to achieve the same API as Tailwind and this is an example of an area where we diverge in ideas.

Given that this isn't a common painpoint or issue for other consumers, I would be careful with your suggested approach.

Thanks for understanding.

**Comment by thecodeclimber** [comment]
Hello and thanks for taking the time to respond to my suggestion.

Perhaps this is an idea you could consider for version 2.  I agree that not everything should be in props.  However, given that this is essentially just a stylistic element, it would be nice if at some point in the future we could at least have the option to adding it to props (just like I can either use a Flex component or use the display prop with a value of flex.

Either way, thanks again for taking the time to get back to me.

Be well.
