### ISSUE TITLE
[InputGroup] rightElement default padding clashing with input 

### ISSUE THREAD

**Issue by dukartbr** [chakra-ui/chakra-ui#431]
**Describe the bug**
When creating an input group with a right element within the group, the text and icon clash over one another, this is due to the `rightElement` default padding being set incorrectly 

<img width="768" alt="Screen Shot 2020-02-21 at 11 49 02 AM" src="https://user-images.githubusercontent.com/24302915/75058331-6f7a2d80-54a0-11ea-9383-04b84af94aba.png">

**Expected Behavior**
`rightElement` should be padded in the same manner as the `leftElement`

**To Reproduce**
Type in a `<FormGroup />` input with a `rightElement` until the text exceeds the width of the input.

**Suggested solution(s)**
https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/InputGroup/index.js#L30
The way the above code is written is dependent on the `leftElement` or `rightElement` coming before the `<Input />` otherwise the padding is applied before the element is encountered. 

- Either change the docs so that it is recommended that the `leftElement` and `rightElement` are defined before the `<Input />` in the `<InputGroup />` component 
- Or rewrite the `<InputGroup />` component to handle right padding correctly 

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version:  80.0.3987.116

**Comment by segunadebayo** [comment]
Hi @dukartbr , thanks for raising this issue.

We're aware of this and have fixed it in the `dev-ts` branch in preparation for the next release. 

We've re-written the InputGroup component altogether to fix this as you suggested.

Thanks
