### ISSUE TITLE
Custom Dropdown/Select

### ISSUE THREAD

**Issue by CaitlinSweeney** [chakra-ui/chakra-ui#4311]
### Description

Create a custom, [keyboard compliant](https://www.w3.org/WAI/perspective-videos/keyboard/) dropdown/select component with search capabilities.

### Problem Statement/Justification

- Most designs and apps need a more dynamic `select` component, such as `react-select`.
- I needed to create a custom `Select` component, while using Chakra-UI's infra and system utils, hooks. Referencing the `Menu` component, I added optional search to filter out the listed options, the `DescendantsContext` for keyboard focus management, along with custom `SelectOptions` for rending labels and optional icons, etc.

### Proposed Solution or API

I found the `react-select` format much more versatile in terms of controlling and rendering data.

`Select` will render and array of `OptionTypes`.
```js
export type OptionType = {
  icon?: string;
  label: string;
  value: string; 
}
```

Example usage:
```js
function SelectUsage() {
  const [state, setState] = React.useState(null)
  const options = [
    { label: 'Green', value: 'green' },
    { label: 'Green-Yellow', value: 'greenyellow' },
    { label: 'Red', value: 'red' },
    { label: 'Violet', value: 'violet' },
    { label: 'Forest', value: 'forest' },
    { label: 'Tangerine', value: 'tangerine' },
    { label: 'Blush', value: 'blush' },
    { label: 'Purple', value: 'purple' },
  ]
  return (
    <>
      <Select
        isSearchable
        defaultValue={options[0].value}
        value={state}
        options={options}
        onChange={(value) => setState(value)}
      />
    </>
  )
}
```
- container `SelectDescendantsProvider`, `SelectProvider` & `StylesProvider`
- `Select` consumes four internal components, each with its relative context.
```
<SelectContainer />
  <SelectInputValue />
<SelectList />
   <SelectOption />
```

### Alternatives

- Structure: maybe moving the components out of the context, leaving the developers more control of the general structure of the elements? I found this be more difficult in terms of controlling data.
```
<Select>
  <SelectContainer>
    <SelectInputValue /> // handles current state, and search state
  </SelectContainer>
  <SelectList>
    <SelectOption label="Green" value="green" />
    <SelectOption label="Red" value="red" />
    <SelectOption label="Yellow" value="yellow" />
    <SelectOption label="Blue" value="blue" />
    <SelectOption label="Black" value="black" />
  </SelectList>
</Select>
```

### Additional Information
- current component development

https://user-images.githubusercontent.com/19299064/124046312-e5fd3880-d9ce-11eb-8938-25b946a9cfd9.mov

**Comment by anubra266** [comment]
You could check out [choc autocomplete](https://github.com/anubra266/choc-autocomplete).

**Comment by csandman** [comment]
I made a chakra wrapper for react-select recently, if anyone else is looking for something like this!  https://github.com/csandman/chakra-react-select

**Comment by edgars-sirokovs** [comment]
Is there a plan to add this to Chakra UI React components, any roadmap? That would be just awesome!

**Comment by csandman** [comment]
There have been some major improvements in version 2 and version 3 of my [`chakra-react-select`](https://www.npmjs.com/package/chakra-react-select) package, featuring a fully customizable style system, and the native typescript support added in `react-select@5`.  So if my component didn't feel customizable enough at first, or you had issues implementing it in a TypeScript project, I highly recommend giving it a second chance.

**Comment by lcswillems** [comment]
@csandman Thanks a lot for this package!! It made me save so much time!

**Comment by CaitlinSweeney** [comment]
@csandman this package is awesome! Thank you so much for creating it and for the great docs. I created a chakra-ui `Select` last year, inspired by `react-select` and the chakra-ui `Menu`, but just not as solid as the `react-select` framework.

**Comment by csandman** [comment]
@CaitlinSweeney Thanks for the feedback, I'm glad you like it!

**Comment by fransiscushermanto** [comment]
@csandman can you please export out SelectType interface in your library

**Comment by csandman** [comment]
Sure I can do that some time tomorrow.  However I'm probably going to rename it SelectComponent

**Comment by fransiscushermanto** [comment]
> Sure I can do that sometime tomorrow. However, I'm probably going to rename it SelectComponent

Thanks! I'm looking forward to it.

**Comment by fransiscushermanto** [comment]
@csandman there is one issue when using your package, It seems your package default theme is overriding my Chakra default theme is there any solution?

**Comment by csandman** [comment]
> @csandman there is one issue when using your package, It seems your package default theme is overriding my Chakra default theme is there any solution and cause ordering issues?

Could you elaborate on that?  Like it's overriding the theme from other unrelated components? Or changes to you theme aren't propegating to the select?

**Comment by lcswillems** [comment]
Doesn't make sense to close it. Problem is still here

**Comment by julia-allyce** [comment]
Hello - I'd be interested in creating a simpler implementation of this request by using the existing Menu components. But this component would implement WAI listbox properties, so it could be used as a form element. Is that something that would be a good addition to the chakra library?

**Comment by lcswillems** [comment]
Don't close

**Comment by anubra266** [comment]
@CaitlinSweeney The Just concluded Chakrathon was based on Custom Select, so it's available already, they're just working on implementing it into the Chakra Codebase.

**Comment by csandman** [comment]
@anubra266 was the whole Chakrathon based on a custom select, or was that just what the winners made?

**Comment by anubra266** [comment]
@csandman the whole chakrathon was based on it.

**Comment by csandman** [comment]
@anubra266 oh I see it now.  so it was based on making a single select component, no multi-select capabilities (unless the team decided to add them).

**Comment by anubra266** [comment]
@csandman  I don't expect that multi select will take too much effort once single select is settled.

**Comment by csandman** [comment]
> @csandman I don't expect that multi select will take too much effort once single select is settled.

I'd tend to disagree, making selected options in a multi-select component composable in a similar way to how the rest of the chakra components are is a pretty big step from making a single-select component.  I'd be happy to be proven wrong, but it's a whole different challenge.

**Comment by anubra266** [comment]
@csandman, chakra ui has a `descendants` package. Like that of React spectrum, so composability won't be an issue.

**Comment by csandman** [comment]
I more meant composability for the end user, as in how you'd store them and display them as their own list of a built in chakra component.  The list of options to select is relatively straightforward (similar to the menu), but I'm finding it very difficult to imagine how you could use the list of selected options to display those components in a way that aligns with any of the patterns other Chakra components use.

**Comment by anubra266** [comment]
I'm not sure I understand what you mean here @csadman, perhaps you could explain in terms of `react-select`

**Comment by csandman** [comment]
@anubra266 sure, `react-select` follows a completely different paradigm for how it renders the sub-components that make up the overall component than most of Chakra UI's components.  Instead of manually composing those sub-components, you pass in essentially an example component and `react-select` handles rendering it, as many times as it needs to be:

```tsx
const MultiValueContainer = (props: MultiValueGenericProps<ColourOption>) => {
  return (
    <Tooltip content={'Customise your multi-value container!'}>
      <components.MultiValueContainer {...props} />
    </Tooltip>
  );
};

export default () => (
  <Select
    isMulti
    components={{ MultiValueContainer }}
  />
);
```

Where as, if we take the Chakra UI `Menu` component for example, each of the `MenuItem` components is manually added by the user:

```jsx
<Menu>
  <MenuButton as={Button} rightIcon={<ChevronDownIcon />}>
    Actions
  </MenuButton>
  <MenuList>
    {/* Or map a list of options */}
    <MenuItem>Download</MenuItem>
    <MenuItem>Create a Copy</MenuItem>
    <MenuItem>Mark as Draft</MenuItem>
    <MenuItem>Delete</MenuItem>
    <MenuItem>Attend a Workshop</MenuItem>
  </MenuList>
</Menu>
```

The big benefit of this pattern is that it allows you to customize each of the sub-components on their own, as you're manually placing them in the DOM.

For the most part, this pattern works fine for a single select, as it essentially follows the same pattern as the `Menu`.  But as soon as you start talking about a multi select, this pattern breaks when you get to the selected options.  Here are the only ways I think you might be able to handle it (using the winning project from Chakrathon as an example):

1. Rely on the user to manage the state of the selected options and map them to their respective components.

```jsx
const [selectedOptions, setSelectedOptions] = useState([]);

return (
  <Select clearable isDisabled={isDisabled || isLoading} onChange={setSelectedOptions}>
    <SelectedOptions>
      {selectedOptions.map((option) => (
        <SelectedOption option={option} />
      ))}
    </SelectedOptions>
    <SelectSelector />
    <SelectMenu>
      <SelectOption isDisabled>Option 1</SelectOption>
      <SelectOption value="option-value-1">Option 2</SelectOption>
      <SelectOption value="option-value-3">Option 3</SelectOption>
    </SelectMenu>
  </Select>
);
```

This goes against Chakra's patterns as none of the other Chakra components require you to manage state outside of the rendered components in order to render them properly.

2. Pass an example component (similar to `react-select`) for Chakra to render multiple times for each option selected.

```jsx
<Select clearable isDisabled={isDisabled || isLoading}>
  <SelectedOptions option={<SelectedOption fontSize="lg" />} />
  <SelectSelector />
  <SelectMenu>
    <SelectOption isDisabled>Option 1</SelectOption>
    <SelectOption value="option-value-1">Option 2</SelectOption>
    <SelectOption value="option-value-3">Option 3</SelectOption>
  </SelectMenu>
</Select>
```

This, like I mention above, does not follow a pattern that any of the other Chakra components use, and makes it a little more complicated to customize each `SelectedOption` for each time it's rendered.  There are definitely cases where they use this `component={<Component />}` prop pattern, but its only ever used in instances where there is a single instance of the component being used, such as an `Icon` for an `IconButton`.

3. Using render props to get the selected options from the components context.

```js
<Select placeholder="Select option" value={value} onChange={onChange}>
  {({ selectedOptions }) => (
    <>
      <SelectedOptions>
        {selectedOptions.map((option) => (
          <SelectedOption option={option}>{option.label}</SelectedOption>
        ))}
      </SelectedOptions>
      <SelectButton>{option?.label ?? "Placeholder"}</SelectButton>
      <SelectMenu>
        <SelectOption value="option-value-1">Option 1</SelectOption>
        <SelectOption value="option-value-2">Option 2</SelectOption>
      </SelectMenu>
    </>
  )}
</Select>
```

This is just something no other Chakra components do, and render props as a pattern have generally fallen out of favor with the introduction of hooks.  I doubt they'll go this route, for either their new single select or multi select components.

---

So these are the reasons I think it'll get complicated to implement a multi select without breaking away from some of the patterns which make up Chakra's design system.  I've put a lot of thought in to how you might accomplish this in a way that strictly follows the component composition pattern that other Chakra components use, but I've had no luck.

But hey, I could always be missing another implementation pattern, and I wouldn't be upset if they come up with a way to make it possible.  This is just my thought process after thinking about it for some time.  Honestly, I'm glad to be able to put it into words haha.

**Comment by anubra266** [comment]
Oh I see @csandman you're talking of tags. The way I was thinking of it, is selected items, have a checkmark or whatever way the developer chooses.
But talking of tags, A tag component is a completely different component on it's own. React Aria is very much composition oriented like chakra, you can check it out. The select, passes the state to a tag component, which then does it's thing with that state. Note that the tag component has it's own levels of composition too, thereby keeping the composition apis intacts.
Chakra UI is going to be using zagjs components. Zagjs actually has a tag components already. So I guess that'll settle that part.

**Comment by csandman** [comment]
@anubra266 Sure, so if they decide not to include any implementation for displaying the list of selected options other than marking them in the list itself, then my point is moot.  But that get's tricky if people want to do anything like react-select where the options are displayed inside the select.

Can you link me to an example of what you're talking about with React Aria?  I've seen the package before but not the multi-select.

**Comment by anubra266** [comment]
@csandman they don't have an official implementation in the docs, but a maintainer kinda showed an implementation, can't find it now.

**Comment by stellarhoof** [comment]
Not stale

**Comment by segunadebayo** [comment]
This has been created in Zag.js and will land in Chakra UI pretty soon:
https://zagjs.com/components/react/select

**Comment by schettn** [comment]
Hey @segunadebayo. Any ETA on this?

**Comment by codler** [comment]
@segunadebayo any ETA?

**Comment by herwaldt** [comment]
@segunadebayo any ETA?
