### ISSUE TITLE
NextJS & SSR Bug: Warning: Prop className did not match on useMediaQuery

### ISSUE THREAD

**Issue by niconiahi** [chakra-ui/chakra-ui#4319]
### Description

On a NextJS application, when using Chakra's useMediaQuery to determine a value for a Text prop, it prints an error about a non matching className on the server and the client

### Link to Reproduction

https://codesandbox.io/s/festive-keller-6jhy5

### Steps to reproduce

IN THE SANDBOX WORKS:
1. Run the code and check the console

IN MY NEXTJS APP WITH CHAKRA DOES NOT. 
Am I missing something?

Code reference (same as codesandbox but in real app)
same happening to me when ussing `useMediaQuery` as so:
```jsx
const useDevice = () => {
  const [isLargeDevice] = useMediaQuery('(min-width: 62em)')

  return {
    isLargeDevice,
  }
}
```

then used: (THIS THROWS AN ERROR)
```jsx
  import { useDevice } from './useDevice'
  
  const { isLargeDevice } = useDevice()
  
   <Text color='white' textStyle={isLargeDevice ? 'body.bold.lg' : 'body.bold.md'}>
       Don't miss out on new proposals
   </Text>
```

used: (THIS DOESN'T)
```jsx
   <Text color='white'>
       Don't miss out on new proposals
   </Text>
```

screenshot here:
![image](https://user-images.githubusercontent.com/8381041/124301037-a1d87800-db35-11eb-990f-ab1cd9d40b1b.png)

### Chakra UI Version

1.6.4

### Browser

Google Chrome 91.0.4472.114

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Relates to this issue:

https://github.com/chakra-ui/chakra-ui/issues/684

**Comment by segunadebayo** [comment]
Hi @niconiahi, 

As mentioned in the [docs](https://chakra-ui.com/docs/hooks/use-media-query#return-value), 

> Keep in mind this API relies on the user's browser support of window.matchMedia and will always return false if it is not supported or does not exist (e.g. during server-side rendering).

To fix this, I recommend waiting for the client to be re-hydrated by using a `useEffect` check, then you can return the value from `useBreakpointValue`

```jsx
const [mounted, setMounted] = useState(false)
const value = useMediaquery(...)

useEffect(()=>{ 
  setMounted(true)
},[])

return mounted ? value : null
```

Be sure to add a spinner or skeleton to that portion of the page so there's no layout shift.

**Comment by aboveyunhai** [comment]
@segunadebayo  maybe we should include your suggestion implementation in doc or inside the `example code block`?

Or you consider it might mislead some people how to use it without specific concern. 
I felt like it should be indicated somewhere, it's pretty ambiguous with the text mentioned about SSR issues only.

**Comment by kimgysen** [comment]
So there is a mismatch in the className between server and client, and the solution is to add a spinner and set the value with useEffect to fix a media query? Maybe it's me, but that doesn't sound right.

**Comment by oiojin831** [comment]
It seems not working when I do it with remix..
any suggestion?

**Comment by cyberwombat** [comment]
Can we address this internally? I mean requiring us to wrap each and every component with this doesn't provide value imo. SSR is very common and perhaps considering a `useBreakpointValue`, etc that handles refresh as I see in the fixes people post online?

**Comment by oleksandr-danylchenko** [comment]
In my project I came up with a hook that can wrap the value that leads to a server-client mismatch:
```ts
export const useMountedValue = <T>(value: T, ssrValue: T): T => {
  // Needed to prevent a mismatch between the first render on the server and the client
  const [mountedValue, setMountedValue] = useState(ssrValue);
  useEffect(() => setMountedValue(value), [value]);

  return mountedValue;
};
```

Usage:
```tsx
const clientValue = useMediaquery(...);
const value = useMountedValue(clientValue, '');
```
