### ISSUE TITLE
Can't use an Input inside an AccordionButton

### ISSUE THREAD

**Issue by delucca** [chakra-ui/chakra-ui#4320]
### Description

While using an Accordion with an Input in the Accordion button, it is not possible to type space without the Accordion to toggle

### Link to Reproduction

https://codesandbox.io/s/chakra-accordion-space-toggle-icyoh

### Steps to reproduce

1. Open the CodeSandbox
2. Click on the input
3. Type anything with more than 2 words (them, you would need to type space)
4. See the accordion opening

### Chakra UI Version

1.6.4

### Browser

Firefox

### Operating System

- [ ] macOS
- [ ] Windows
- [x] Linux

### Additional Information

As I've mentioned, I would like to have a way to disable the `space` and `enter` hotkeys when the focus is within the input. So my users could type `space` without having to open the Accordion

As a workaround, I can add `onKeyUp={(event) => event.preventDefault()}` to the `Input`, and that should prevent the Accordion from toggling. But, that is a pretty ugly workaround. We should have a proper way to handle that.

**Comment by AndreasJacobsen** [comment]
I don't think Chakra should support the behaviour you described. 

The accordion button is rendered as an HTML button. Buttons should never contain other interactive elements such as inputs and other buttons. 

This makes buttons much more difficult to use with assistive tools such as screen reads and more confusing for many users. A form inside a button is not what I would describe as a generall good user experience.

**Comment by ThomasAlvin** [comment]
can you specify where did you put the as="div"?, because i can't get mine working, i also found another solution where i just added onKeyUp with a function that has event.preventDefault()
 const handleKeyUp = (event) => {
    if (event.key === " ") {
      event.preventDefault();
    }
  };
