### ISSUE TITLE
There's no way to change checkbox border-color in the documentation

### ISSUE THREAD

**Issue by demolaemrick** [chakra-ui/chakra-ui#4323]
### Subject

Checkbox

### Description

Add how-to change checkbox border-color to the documentation

**Comment by anubra266** [comment]
<img width="805" alt="CleanShot 2021-07-06 at 13 01 14@2x" src="https://user-images.githubusercontent.com/30869823/124596544-4f12ff00-de5a-11eb-97c7-337c25e5c862.png">
<img width="809" alt="CleanShot 2021-07-06 at 13 01 27@2x" src="https://user-images.githubusercontent.com/30869823/124596558-520def80-de5a-11eb-96bc-a373482876ca.png">

**Comment by demolaemrick** [comment]
Okay, thank you very much.

**Comment by slekass** [comment]
doesn't work

**Comment by anubra266** [comment]
@slekass you create a codesandbox reproduction and open an issue.

**Comment by mecampbellsoup** [comment]
Is it possible to do something similar but for an unchecked state?

**Comment by MohsinAliINPL** [comment]
> It's a style prop, so we can't create a separate checkbox doc for it.
> 
> <img alt="CleanShot 2021-07-06 at 13 01 14@2x" width="805" src="https://user-images.githubusercontent.com/30869823/124596544-4f12ff00-de5a-11eb-97c7-337c25e5c862.png">
> 
> <img alt="CleanShot 2021-07-06 at 13 01 27@2x" width="809" src="https://user-images.githubusercontent.com/30869823/124596558-520def80-de5a-11eb-96bc-a373482876ca.png">

can we add custom background color to checkbox?

**Comment by MobeenKhan221** [comment]
i need a borderradius change property
