### ISSUE TITLE
Warning: Prop `id` did not match. Server: "accordion-button-3" Client: "accordion-button-6"

### ISSUE THREAD

**Issue by TheThirdRace** [chakra-ui/chakra-ui#4328]
### Description

Whenever I use an accordion with NextJs, I get mismatches for ids.

### Link to Reproduction

https://codesandbox.io/s/snowy-thunder-gxsfl?file=/pages/index.tsx:0-1603

### Steps to reproduce

First thing first, I can't reproduce it with the codesandbox. I think it's running `next start` while you only see the errors with `next dev`...

I still linked a codesandbox with something that will reproduce the problem when ran in local.

To reproduce, I simply create a new page, let's say "accordion.tsx" with this code taken directly from the documentation:

```typescript
import {
  Accordion,
  AccordionButton,
  AccordionIcon,
  AccordionItem,
  AccordionPanel,
  Box,
  Heading
} from "@chakra-ui/react";
import React from "react";

export default function IndexPage() {
  return (
    <article>
      <Heading>Welcome to Chakra UI example</Heading>
      <Accordion allowToggle>
        <AccordionItem>
          <h2>
            <AccordionButton as="button" id="ttr">
              <Box flex="1" textAlign="left">
                Section 1 title
              </Box>
              <AccordionIcon />
            </AccordionButton>
          </h2>
          <AccordionPanel pb={4}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat.
          </AccordionPanel>
        </AccordionItem>

        <AccordionItem>
          <h2>
            <AccordionButton>
              <Box flex="1" textAlign="left">
                Section 2 title
              </Box>
              <AccordionIcon />
            </AccordionButton>
          </h2>
          <AccordionPanel pb={4}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat.
          </AccordionPanel>
        </AccordionItem>
      </Accordion>
    </article>
  );
}
```

Load the page, look at the console and I get:

```
Warning: Prop `id` did not match. Server: "accordion-button-3" Client: "accordion-button-6"
```

This is new from Chakra `1.6.4`.

Everything was working fine in my project with `1.6.3`.

When I migrated to `1.6.4`, I saw there had been a big modification for generating `id`s so they could better match between server and client. (supposedly, I never had the problem before so I have no idea why it was "fixed")

I looked at the modified file and it was a huge change. I tried it as is, but I couldn't make it work at all in my project because **with `1.6.4` pretty much all ids were a mismatch now...**

Since I was using Chakra's `useId` hook for my own custom components, I created a new `useId` with the old code and removed the import from Chakra. Everything went back to normal.

I didn't use any accordion at the time, so I never saw any other problem. But obviously, anything that would use Chakra `1.6.4` `useId` will behave incorrectly with NextJs, as we can see with `Accordion`.

I figured someone would eventually create an issue because the console is completely red when used with NextJs in SSG... Turns out I'm the first to report it after all :( 

### Chakra UI Version

1.6.4

### Browser

MS Edge 91.0.864.64 (latest at the moment)

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I tried passing my own `id` to the accordion button, but it's simply ignored by Chakra implementation, it overrides it with it's own automatic `id`. This should be looked at, if I could somehow pass my own `id`, I could easily patch in the old version to generate `id`s, the one that worked 100% with NextJs.

Screenshot of a simple page with only the accordion on it
![image](https://user-images.githubusercontent.com/22915526/124411204-15d37580-dd1a-11eb-8b2b-70ff360add6d.png)

Screenshot of the console for that same page
![image](https://user-images.githubusercontent.com/22915526/124412107-c726db00-dd1b-11eb-824e-6fb4dbb410c7.png)

Screenshot of React Dev Tools on the Accordion Button (id = "ttr")
![image](https://user-images.githubusercontent.com/22915526/124412203-fa696a00-dd1b-11eb-9d98-201f3cc87c11.png)

Screenshot of React Dev Tools on the Accordion Button sub component "button" (id = "accordion-button-6")
![image](https://user-images.githubusercontent.com/22915526/124412230-0bb27680-dd1c-11eb-8a04-1e17da8c9f36.png)

I have no idea why on the server the id is `accordion-button-3` while on the client it's `accordion-button-6`.

My repository is private, but I could invite someone from the staff to debug it if necessary.

If you require anything else, don't hesitate to ask.

Regards,

TheThirdRace

**Comment by MobliMic** [comment]
Just to add to this it appears this change has broken all of our tests using snapshots. Nothing mentioning a change to the ID system in the changelog though?

`1.6.3` was perfectly fine but now it looks like everything is being being randomly generated on render each time in `1.6.4` causing the snapshots to always fail. 

![image](https://user-images.githubusercontent.com/4713282/124488491-d2bfe380-dda7-11eb-96e1-fccccf6495b9.png)

for note we are also using `"@emotion/jest": "^11.3.0"` to serialize the css for the snapshots.

I don't know if this is related to the same issue or needs a new issue creating for it?

**Comment by chasinhues** [comment]
Same issue here as MobliMic mentioned.

Issue was introduced in 1.6.4. Might have been from this commit? https://github.com/chakra-ui/chakra-ui/commit/51428cdd1606d4ce2c9432a6fdac05cfc96f4373

**Comment by TheThirdRace** [comment]
@chasinhues I can confirm it's the commit I was referring to, but were too lazy to look for while creating the issue 😅

**Comment by raisiqueira** [comment]
Just following this issue, I'm with the same error here, the id of the Menu changes and broke's my snapshot.

```
@Chakra-ui/react: 1.6.4
@emotion/jest: 11.3.0
```

![image](https://user-images.githubusercontent.com/2914170/124824982-70064d80-df49-11eb-81c6-bb2d7604723f.png)

**Comment by with-heart** [comment]
@TheThirdRace Can you try deleting your `.next` folder and see if you're still receiving issues with `dev`?

**Comment by TheThirdRace** [comment]
@with-heart I removed the `.next` folder, built and tested, but got the same result.

I still get unmatched `id`, same exact result as before: the server the id is `accordion-button-3` while on the client it's `accordion-button-6`

**Comment by MobliMic** [comment]
@with-heart should I create a seperate issue regarding the ID gen issue with jest snapshot testing? I'm using CRA and it seems like while related to the same change it is probably not the same issue

**Comment by with-heart** [comment]
@TheThirdRace Thanks for trying that. That's good to know. @segunadebayo had noticed issues with ids being cached in `.next` and he suggested that we try that.

@MobliMic I think we can keep that within this issue. It's all related and I think whatever solution would need to handle both problems.

**Comment by TheThirdRace** [comment]
@with-heart 
No problem, if you need further testing I can make myself available. I'd like this to be solved sooner rather than later 😉

I don't know what was the problem with the `id` that prompted the modification in `1.6.4`, but I can confirm I never had a problem with the previous solution from Chakra `0.8` to `1.6.3`.

Thanks for the feedback

**Comment by aboveyunhai** [comment]
Tabs and Menu also have similar issues.
![image](https://user-images.githubusercontent.com/35160613/125534771-0c624a92-e4d8-4b1a-9649-9977596098ed.png)
![image](https://user-images.githubusercontent.com/35160613/125534797-a81d285c-7ff3-4896-badf-1bf7630e9248.png)

**Comment by pravastacaraka** [comment]
> Tabs and Menu also have similar issues.
> ![image](https://user-images.githubusercontent.com/35160613/125534771-0c624a92-e4d8-4b1a-9649-9977596098ed.png)
> ![image](https://user-images.githubusercontent.com/35160613/125534797-a81d285c-7ff3-4896-badf-1bf7630e9248.png)

I have the same problem.

**Comment by atelog** [comment]
As a temporary solution, you can provide your id.

Example for `<Accordion>` component:

```
<Accordion>
  {items.map((e, i) => <AccordionItem key={i}  id={`my-id-${i}`}> ... </AccordionItem>)}
</Accordion>
```

**Comment by TheThirdRace** [comment]
@atelog 
Good to know!

It's just very unfortunate that setting the `id` on the `AccordionButton` doesn't work as it's much more intuitive than passing an `id` on the `AccordionItem`...

I think it's a very bad idea to distribute props meant for a child component to its parent if you can easily put it on the child you need to target. Not only do you lose control of what does what, but you're introducing so much uncertainty 😅

**Comment by givionte** [comment]
The issue just started with my accordion buttons as well, also using Nextjs.  I've been using 1.65 since it became available, but it took until last night for the mismatched ids to crop up.  I temporarily switched to 1.63 until the issue is resolved.

**Comment by yuyaamano23** [comment]
I got the following error when using the tabs component.
<img width="889" alt="スクリーンショット 2021-08-01 22 46 58" src="https://user-images.githubusercontent.com/58542696/127773234-f171f730-94eb-4ce9-9dfb-87d38cede198.png">
code:
```js
<Tabs variant="enclosed">
  <TabList>
    <Tab>One</Tab>
    <Tab>Two</Tab>
  </TabList>
  <TabPanels>
    <TabPanel>
      <p>one!</p>
    </TabPanel>
    <TabPanel>
      <p>two!</p>
    </TabPanel>
  </TabPanels>
</Tabs>
```

So I added an id to the first `<Tabs>` and the error is resolved!!!!

code:
```js
<Tabs variant="enclosed" id="1">
  <TabList>
    <Tab>One</Tab>
    <Tab>Two</Tab>
  </TabList>
  <TabPanels>
    <TabPanel>
      <p>one!</p>
    </TabPanel>
    <TabPanel>
      <p>two!</p>
    </TabPanel>
  </TabPanels>
</Tabs>
```

**Comment by pcs980** [comment]
Same issue with menu here. Solved by using id. Thanks, @yuyaamano23.

```jsx
<Menu isLazy id={`${p._id}-menu-id`}>
  <MenuButton
    as={IconButton}
    icon={<Icon as={RiMore2Line} fontSize='20' />}
    aria-label='actions'
    variant='outline'
    borderRadius={8}
  />
  <MenuList color={`${primaryColor}.900`}>
    <MenuItem color='red.500'>
      Close
    </MenuItem>
  </MenuList>
</Menu>
```

**Comment by y471n** [comment]
I'm having the same issue with `<PinInput />`

**Comment by kdubb1337** [comment]
> Same issue with menu here. Solved by using id. Thanks, @yuyaamano23.
> 
> ```js
> <Menu isLazy id={`${p._id}-menu-id`}>
>   <MenuButton
>     as={IconButton}
>     icon={<Icon as={RiMore2Line} fontSize='20' />}
>     aria-label='actions'
>     variant='outline'
>     borderRadius={8}
>   />
>   <MenuList color={`${primaryColor}.900`}>
>     <MenuItem color='red.500'>
>       Close
>     </MenuItem>
>   </MenuList>
> </Menu>
> ```

To resolve my issue this worked, but I needed a `<menu>` with both `isLazy` and the `id` set.

**Comment by aboveyunhai** [comment]
> > Same issue with menu here. Solved by using id. Thanks, @yuyaamano23.
> > ```js
> > <Menu isLazy id={`${p._id}-menu-id`}>
> >   <MenuButton
> >     as={IconButton}
> >     icon={<Icon as={RiMore2Line} fontSize='20' />}
> >     aria-label='actions'
> >     variant='outline'
> >     borderRadius={8}
> >   />
> >   <MenuList color={`${primaryColor}.900`}>
> >     <MenuItem color='red.500'>
> >       Close
> >     </MenuItem>
> >   </MenuList>
> > </Menu>
> > ```
> 
> To resolve my issue this worked, but I needed a `<menu>` with both `isLazy` and the `id` set.

Then it's a sever side rendering issue, by using isLazy we are forcing it into client side rendering, which it's probably not a good idea for people who wants SEO, etc..  We probably want to leave what it is until it's fixed.

**Comment by tomdohnal** [comment]
I did some investigation and came to the following conclusions:
- This bug only occurs when using SSR (Next.js or any other framework) in conjunction with **React Strict Mode**
- There is an open issue in the `react-spectrum` which uses the same approach for generating IDs as ChakraUI (https://github.com/adobe/react-spectrum/issues/2231)
- Essentially, the problem boils down to the fact that in strict mode, React invokes some hooks *twice* (https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects). This is because it tries to detect invoking side-effects during the render phase as it leads to problems when using concurrent mode.
- I'm not really sure that there is a good solution to this problem apart from either **manually entering the `id` attributes or turning the strict mode off** (which just hide the problem without solving it).
- The current implementation relies on updating the context during the render phase as we need to update the context value synchronously (when the component renders). This means that it *relies* on performing side-effects during the render phase – the very thing which problematic for future React releases

**Comment by chasinhues** [comment]
> This bug only occurs when using SSR (Next.js or any other framework) in conjunction with React Strict Mode

I don't think it _only_ occurs when using SSR. As mentioned [in another comment](https://github.com/chakra-ui/chakra-ui/issues/4328#issuecomment-874167812), it also occurs in snapshot testing.

**Comment by aboveyunhai** [comment]
> > This bug only occurs when using SSR (Next.js or any other framework) in conjunction with React Strict Mode
> 
> I don't think it _only_ occurs when using SSR. As mentioned [in another comment](https://github.com/chakra-ui/chakra-ui/issues/4328#issuecomment-874167812), it also occurs in snapshot testing.

Are you using Next.js? If so, SSG might be the case. He probably means the hydration or rendering phase. Not need to limit our thought into the exact definition of SSR by framework.

**Comment by chasinhues** [comment]
Nah I'm not using SSR or SSG, just normal CSR. 

My point was that this issue isn't specific to SSR/SSG, as it's also happening in snapshot tests.

**Comment by aboveyunhai** [comment]
> Nah I'm not using SSR or SSG, just normal CSR.
> 
> My point was that this issue isn't specific to SSR/SSG, as it's also happening in snapshot tests.

My bad. Then it's impossible to tell with my limit knowledge. I'm a little bit surprise it also failed in CSR.
It seems like react-aria team is also not able to solve it currently.

**Comment by fhefh2015** [comment]
Same problem with the Next.js SSR.

<img width="834" alt="CleanShot 2021-09-25 at 19 41 45@2x" src="https://user-images.githubusercontent.com/14891797/134770196-374c78e5-de15-4f37-9db5-a6a0f91bc782.png">

**Comment by parsher** [comment]
![image](https://user-images.githubusercontent.com/26663229/135212042-fb064616-e6af-4d9f-a8f7-faa1c00c859f.png)
FormLabel has the same problem.

**Comment by cyberwombat** [comment]
Some thoughts i had on this is that while hardcoding an ID appears to fix the issue I don't think it does anything more than suppressing the error which is an option. It is rendering twice - probably as its supposed to be and hardcoding the id I do not think stops this - simply another way to hide the underlying issue if any. Just a guess though.

**Comment by igorwessel** [comment]
> Some thoughts i had on this is that while hardcoding an ID appears to fix the issue I don't think it does anything more than suppressing the error which is an option. It is rendering twice - probably as its supposed to be and hardcoding the id I do not think stops this - simply another way to hide the underlying issue if any. Just a guess though.

@cyberwombat Just some doubts by chance was with strict mode active? In case you are, I've already fixed about this, the big problem is that some side effects regarding id generation were in some wrong places considered wrong for example the body of a function, side effects inside a useMemo function. 
If you disable strict mode, this will resolve itself, I already opened a pull request solving this problem. #4835

**Comment by igorwessel** [comment]
@raisiqueira This usually happens when you haven't encapsulated the component in a ChakraProvider, as there is no default context to access, it creates a new context, because of this you have a random prefix every time you run the test. 

In the pull request I created I'm questioning whether to keep this, because I haven't found at any time that this prefix is ​​useful.

**Comment by kimgysen** [comment]
I get the same problem for the popover-content. The fix of giving an id to the PopOver parent element did not work for me. 
Just manually overriding the id of the PopOverContent itself could be a solution for me, but this doesn't seem to work. 
Temporarily I could render the popover from the client; but indeed temporarily, because this impacts on SEO when it concerns main navigation. 

<img width="714" alt="Screenshot 2021-12-08 at 07 37 41" src="https://user-images.githubusercontent.com/4547364/145160616-99a3662e-34da-47fc-89fb-7deac1292034.png">

**Comment by MMiller-Hairston** [comment]
I think this may be of use here. I don't think this is a chakra issue, but rather a next issue.

https://nextjs.org/docs/messages/react-hydration-error

**Comment by TheThirdRace** [comment]
> I think this may be of use here.
> 
> https://nextjs.org/docs/messages/react-hydration-error

Unfortunately, it does show it's a Chakra issue. The error you link is 100% dependent on how you render your component and these components are from Chakra.

This type of error is not only related to NextJs. Any SSR (server-side rendering) or SSG (static site generated) framework would suffer from the same exact limitations.

It's up to the component library to make sure their component can be used in SSR and SSG, not just in CSR (client side rendering). 

Case in point, before Chakra modified their own `useId()` hook in version 1.6.3, everything was working just fine. Because Chakra used a new method that only support CSR, it causes problems with SSR and SSG. I can't be NextJs fault at this point as the code didn't change, only Chakra code changed.

But there might be light at the end of the tunnel, I've seen a PR in the works that refactor the whole id generation process to avoid CSR side effects. I'm not sure it's been merged yet and I've been busy in my personal project for the last 2 months so I haven't updated to the latest to test if it works now. Maybe we're gonna be lucky soon, fingers crossed!

**Comment by MrWangJustToDo** [comment]
i found it is because of React StrictMode, so it is will only happen in the develop mode, could we use getter resolve it?

**Comment by maapteh** [comment]
@segunadebayo with React 18 it ships with useId hook which creates same id on server and client. Maybe it helps.
