### ISSUE TITLE
Popovers in imported / sub components positioning fails

### ISSUE THREAD

**Issue by karimcambridge** [chakra-ui/chakra-ui#4329]
### Description

When I include a component in a page (for example a header component) the popover is always shown at the top left

### Link to Reproduction

https://codesandbox.io/s/reverent-hopper-18vnm?file=/pages/index.tsx

### Steps to reproduce

1. Just hover over the 'account' menu item and you will see

### Chakra UI Version

1.6.4

### Browser

Google Chrome 91

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

- Next JS

See an example below (The popover is supposed to be at "account")

![image](https://user-images.githubusercontent.com/4283893/124415333-a44bf500-dd22-11eb-882b-b4e502192245.png)

**Comment by mrcnk** [comment]
I have pretty much the same issue with Tooltip. It's also being placed in the top left corner of the screen instead of over the wrapped element.

- [x]  macOS
- [x]  Edge
- [x] Safari

**Comment by segunadebayo** [comment]
Hi @karimcambridge  and @mrcnk,

This issue is typically caused by not forwarding `ref` to this underlying component within `PopoverTrigger`.

In this case, using `forwardRef` in the `MenuItem` component fixed the issue:

```jsx
const MenuItem = forwardRef(({ children, isLast, to = "/", ...rest }, ref) => {
  return (
    <Link href={to}>
      <Text ref={ref} display="block" {...rest}>
        {children}
      </Text>
    </Link>
  );
});
```

https://codesandbox.io/s/sleepy-violet-hfo96?file=/components/header.js

**Comment by segunadebayo** [comment]
@mrcnk, if your use-case is different, feel free to file an issue with a reproduction

**Comment by karimcambridge** [comment]
> ```js
> ref={ref} 
> ```

Thank you, maybe the docs can reflect this?

Also @segunadebayo what is your take on the solution @anubra266 made in choc-ui autocomplete? https://github.com/anubra266/choc-autocomplete/commit/10c67e84a204839b6a35a374109d917719c948df#diff-cf399d638dbb98790d084d4c75a4fc5bb53771a417b504126eb088929a8fe759L56

**Comment by anubra266** [comment]
Hi @karimcambridge, I followed that approach because, my Popover doesn't use a trigger. And thanks for the [appreciation](https://github.com/anubra266/choc-autocomplete/commit/10c67e84a204839b6a35a374109d917719c948df#commitcomment-53335046).

**Comment by karimcambridge** [comment]
> Hi @karimcambridge, I followed that approach because, my Popover doesn't use a trigger. And thanks for the [appreciation](https://github.com/anubra266/choc-autocomplete/commit/10c67e84a204839b6a35a374109d917719c948df#commitcomment-53335046).

Ah.

Thank you both for this hard work, helping my work come true!
