### ISSUE TITLE
Custom radio does not update input checked value

### ISSUE THREAD

**Issue by mateeyow** [chakra-ui/chakra-ui#4339]
### Description

When using a custom radio component with `useRadioGroup`, and selecting the "unchecked" radio button. I expect that the hidden input text's "checked" attribute will match with the selected radio element.

### Link to Reproduction

https://chakra-ui.com/docs/form/radio#custom-radio-buttons

### Steps to reproduce

1. Go to the custom radio component's [documentation](https://chakra-ui.com/docs/form/radio#custom-radio-buttons)
2. Select `svelte` 
3. Inspect element of svelte
4. Notice that the `input` for svelte does not have "checked" attribute

### Chakra UI Version

1.6.4

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by MasterGordon** [comment]
Looks like you got fooled by the chrome Inspector
![image](https://user-images.githubusercontent.com/18127395/124893911-75ac7380-dfdb-11eb-9d85-099c60cf4dfe.png)

**Comment by mateeyow** [comment]
This is very weird, was also using firefox. 🤔 I'll close it then.
