### ISSUE TITLE
[ColorMode] How to get dark mode by default?

### ISSUE THREAD

**Issue by RizeXor** [chakra-ui/chakra-ui#434]
I want dark mode by default. I don't want to call toggleColorMode().

In material design we could add dark boolean to theme object is there something similar?

Also in dark mode the background doesn't change, how could I fix thanks :)

**Comment by segunadebayo** [comment]
Hi @RizeXor,

You can wrap your entire application in the <DarkMode> component. Import it from Chakra and apply it at the root of your application, just below the <ThemeProvider>

Thanks. 

PS: If this doesn't fix it, I'll re-open this issue.

**Comment by RizeXor** [comment]
> Hi @RizeXor,
> 
> You can wrap your entire application in the component. Import it from Chakra and apply it at the root of your application, just below the
> 
> Thanks.
> 
> PS: If this doesn't fix it, I'll re-open this issue.

Ok i see there is a DarkMode component but my background-color still doesn't change. I see in the official website the html element itself changes the background. How would I achieve that?

**Comment by segunadebayo** [comment]
Did you render the <CSSReset/> component at the root of your application? Its CSSReset that's responsible for updating the `body` color and background.

So what you want is:

```jsx
<ThemeProvider>
<DarkMode>
    <CSSReset/>
      // render your app here.
</DarkMode>
</ThemeProvider>
```

**Comment by RizeXor** [comment]
@segunadebayo,

Yes now it works. I had CSSReset outside DarkMode. Is it possible to change the backgroundcolor?

**Comment by segunadebayo** [comment]
Hi @RizeXor,

Sorry for the late reply. The CSSReset component takes a config prop you can use to change the bg of the body element.

Unfortunately, we don't have docs for it yet. Kindly check how it works here:  https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/CSSReset/index.js
