### ISSUE TITLE
null as a valid theme property

### ISSUE THREAD

**Issue by luigiminardim** [chakra-ui/chakra-ui#4344]
### Description

Would be great to override the default Chakra UI theme if `null` is a valid style PropertyValue.

### Problem Statement/Justification

 I would like to use null to override `fontSize`,` lineHeight` values in the default theme by using `textStyle` instead. Currently I have to do this:
 
```ts
// theme/components/tag.ts

export const Tag: ComponentMultiStyleConfig = {
	sizes: {
	        md: {
		       container: {
			       minH: (null as unknown) as undefined,
				minW: (null as unknown) as undefined,
				fontSize: (null as unknown) as undefined,
				textStyle: 'button.md',
				borderRadius: 'md',
				px: '8px',
				py: '2px',
		      },
               },
	},
};
```

### Proposed Solution or API

I would like to do just this:

```ts
// theme/components/tag.ts

export const Tag: ComponentMultiStyleConfig = {
	sizes: {
	        md: {
		       container: {
			       minH: null,
				minW: null,
				fontSize: null,
				textStyle: 'button.md',
				borderRadius: 'md',
				px: '8px',
				py: '2px',
		      },
               },
	},
};
```

**Comment by segunadebayo** [comment]
Hi @luigiminardim,

This looks interesting, thanks for sharing your thoughts.

After much thought, we won't be going in this direction. We're exploring ideas to help users override the theme values but it'll be a breaking change for v2 instead.

Please figure out a solution on your end and share it here once you do.

Thanks for understanding.
