### ISSUE TITLE
Latency in Checkbox while changing checked state (in Storybook only)

### ISSUE THREAD

**Issue by danielbollom** [chakra-ui/chakra-ui#4346]
### Description

When I click a checkbox it takes anywhere from 1-3 seconds to re-render as checked.

### Link to Reproduction

https://github.com/danielbollom/chakra-checkbox-latency

### Steps to reproduce

1. Clone repo provided, install dependancies & start storybook
2. Go to Checkbox story
3. Click on checkbox 

### Chakra UI Version

1.6.4

### Browser

Google Chrome 91

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The issue does not occur when using @chakra-ui/react@1.5.0 or lower, so the bug may have been introduced in v1.5.1.

I do also see this behaviour in some other components (menu, radio come to mind).

It's also worth noting that this only seems to happen in Storybook - so far in my actual application I have no come acros the issue.

P.s. Apologies for the Github repo rather than Codesandbox - I couldn't get Storybook running nicely in Codesandbox!

**Comment by danielbollom** [comment]
Just to add a little more context after investigation, it seems like this only occurs while running Storybook locally (`start-storybook`) - after building the storybook and serving the static files everything works fine.

It's looking like this might be something more on the Storybook end, but would be great if someone with a little more knowledge of the repo & some of the versions in question could confirm/give their 2 cents before closing this from the Chakra side :)

**Comment by danielbollom** [comment]
Happy to close this one now, after further investigation the issue actually seemed to be chrome extension that was interfering with rendering on some Chakra components only in Storybook running locally 🤷

Apologies for the hassle!

**Comment by with-heart** [comment]
@danielbollom Glad you were able to track that down!
