### ISSUE TITLE
AspectRatio is forcing its img, video children to behave objectFit="cover"

### ISSUE THREAD

**Issue by tomchentw** [chakra-ui/chakra-ui#4347]
### Description

When I set `<Image objectFit="contain" />`, I expect it to happen. But if I render it inside an `<AspectRatio />`, it will always be `objectFit="cover"`.

```
<AspectRatio ratio={3 / 1}>
  <Image
    src="https://bit.ly/naruto-sage"
    alt="naruto"
    objectFit="contain" // Does NOT work
  />
</AspectRatio>
```

### Link to Reproduction

https://codesandbox.io/s/awesome-ritchie-ec8n9?file=/src/index.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/awesome-ritchie-ec8n9?file=/src/index.js
2. You should see the "Actual" and the "Expected" section

![CS](https://user-images.githubusercontent.com/922234/124885553-f7b19200-e005-11eb-9ed9-71959f5cc739.jpg)

### Chakra UI Version

1.6.4

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Source: 
https://github.com/chakra-ui/chakra-ui/blob/%40chakra-ui/react%401.6.4/packages/layout/src/aspect-ratio.tsx#L62-L64

Tracing it back, these lines were first introduced in this commit: https://github.com/chakra-ui/chakra-ui/commit/c91fdf397f5b75a315d9dff6918684b9f1e5e988#diff-ce7500ee881128fd4e892b90abbccad46958754956da612389d3d5e4f75ebec8

---

In my opinion, the `objectFit` of its img, video children should be configurable directly on its children, not on the `<AspectRatio />` itself.

**Comment by tomchentw** [comment]
Since @segunadebayo authored the commit https://github.com/chakra-ui/chakra-ui/commit/c91fdf397f5b75a315d9dff6918684b9f1e5e988#diff-ce7500ee881128fd4e892b90abbccad46958754956da612389d3d5e4f75ebec8
I'm wondering what's the rational behind this? Are we okay to have a breaking change that removes this behavior? Thank you.

**Comment by segunadebayo** [comment]
This might have been an assumption around the possible use-cases of the aspect-ratio component. This was added to ensure that images stretch to fill the aspect ratio container's space.

At the moment, we're not able to change this as it'll be considered a breaking change. Removing it is not technically the solution here, but exposing a prop that determines whether to stretch the child is the solution.

As a workaround, feel free to use the workaround or pass `objectFit: contain !important` to the `Image` component.

Thanks for understanding.
