### ISSUE TITLE
[Popover, Menu] Strange page scale when enabling mobile mode in Chrome DevTools

### ISSUE THREAD

**Issue by pavchip** [chakra-ui/chakra-ui#4349]
### Description

When I adding Popover or Menu components into page and swtiching to mobile mode in DevTools, page doesn't scale to the size of the screen

### Link to Reproduction

https://codesandbox.io/s/nameless-grass-lx0ep?file=/src/index.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/nameless-grass-lx0ep?file=/src/index.js
2. Click on 'Open on New Window' in the CodeSandbox browser.

![Screenshot 1](https://user-images.githubusercontent.com/12133071/124983530-bc808480-e040-11eb-87b7-79d879a704fb.png)

3. Switch to the mobile mode in DevTools.

![Screenshot 2](https://user-images.githubusercontent.com/12133071/124983554-c6a28300-e040-11eb-9e8c-feec981e47b3.png)

4. You should see that the page doesn't scale to the viewport.
5. You can also click on the button "Go to popover bug", switch to mobile mode in DevTools and see the same bug.

### Chakra UI Version

@chakra-ui/react@1.6.5

### Browser

Google Chrome 91

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Ploppy3** [comment]
I have what seems to be the same issue when using a `MenuList`.

**Comment by Ploppy3** [comment]
I think I understand what the problem is: it scales down because the modal is bigger or outside of the viewport.
