### ISSUE TITLE
TextArea add an interface

### ISSUE THREAD

**Issue by Can-Chen** [chakra-ui/chakra-ui#4351]
### Description

![image](https://user-images.githubusercontent.com/50009783/125021885-1703fa00-e0ae-11eb-96f1-9d5205b93015.png)

As shown in the figure, I hope textarea can add a new interface. You can customize the number of visible lines of text in the textarea component

### Problem Statement/Justification

I need to dynamically change the number of visible lines of textarea text

### Proposed Solution or API

`<TextArea  minRows={1} maxRows={3} />`

### Alternatives

Now my alternative is this

`
export default () => {
  const [rows, setRows] = useState(1);
  
  const onScroll = () => {
    if (rows < 3){
       setRows(rows => rows + 1);
    }
  }

 return <TextArea  rows={rows} onScroll={onScroll}  />
}
`

**Comment by Can-Chen** [comment]
Reference link: [https://ant.design/components/input/](url)

**Comment by segunadebayo** [comment]
Hi @Can-Chen, you can consider using https://github.com/Andarist/react-textarea-autosize to manage this behavior smoothly. I think it handles most of the use-cases pretty well.

As far as I can tell, we won't be adding this to Chakra

**Comment by Can-Chen** [comment]
thanks
