### ISSUE TITLE
Opacity for properties ( textOpacity, borderOpacity, backgroundOpacity, ...) for chakra factory 

### ISSUE THREAD

**Issue by pham-nhat-khanh** [chakra-ui/chakra-ui#4352]
### Description

I want to be able to set opacity separately for chakra factory JSX elements.

### Problem Statement/Justification

Most of the times I don't want to set opacity for the whole element but rather for specific properties: border, background, text, ... It's more convenient to be able to just set textOpacity={0.5} instead of having to use function + js like below.
before:
![opacity-before-2](https://user-images.githubusercontent.com/24745349/125026657-45360980-e0af-11eb-83d2-e46f4fea0bfa.png)
![opacity-before-1](https://user-images.githubusercontent.com/24745349/125026659-46673680-e0af-11eb-8261-c41850defbfa.png)

after:
![opacity-after](https://user-images.githubusercontent.com/24745349/125027155-02c0fc80-e0b0-11eb-8811-9702b69559bd.png)

### Proposed Solution or API

I took the idea from [tailwind's opacity](https://tailwindcss.com/docs/background-opacity) :
![opacity-tailwind](https://user-images.githubusercontent.com/24745349/125027038-cbeae680-e0af-11eb-85e8-26535ff99ddf.png)

**Comment by anubra266** [comment]
check out the [tinyColor2](https://www.npmjs.com/package/tinycolor2) package, as chakra uses it internally. You can use it to set the alpha of your colors.

**Comment by segunadebayo** [comment]
Hi @pham-nhat-khanh,

This looks like a good idea @pham-nhat-khanh. After much thought, we won't be taking on this idea.

We're currently exploring the idea of introducing alpha colors instead, so you can specify "green.500A" instead of setting both background color and opacity.
