### ISSUE TITLE
Disable autofocus on form submit error

### ISSUE THREAD

**Issue by redhaazmei** [chakra-ui/chakra-ui#4354]
### Description

<img width="522" alt="Screenshot 2021-07-09 at 4 06 42 PM" src="https://user-images.githubusercontent.com/54533260/125045610-c1d8e000-e0cf-11eb-9bab-cd387201dae5.png">

As from above image, I hope there is an option to disable autofocus on the input element on submit form error. I've tried
include the autoFocus prop `<Input autoFocus={false} />` but this did not work.

### Problem Statement/Justification

Input element automatically focus after on submit form error.

### Proposed Solution or API

To have 

`<FormControl disableAutoFocus={false}>`

### Alternatives

N/A

### Additional Information

N/A

**Comment by anubra266** [comment]
Could you add a reproduction link.

**Comment by redhaazmei** [comment]
Here's the reproduction [https://codesandbox.io/s/gracious-bouman-yru91](url). Notice that after submitting, the form is autofocus to the first input field.

**Comment by segunadebayo** [comment]
Hey @redhaazmei,

Based on my knowledge, I think this is the default behavior in react hook form when there's a validation error.

Please refer to the docs: https://react-hook-form.com/api/useform/#useFormRef
