### ISSUE TITLE
First tooltip inside an alert dialog is focused when the dialog is opened 

### ISSUE THREAD

**Issue by bl-ue** [chakra-ui/chakra-ui#4365]
### Description

When I open an alert dialog containing tooltips, the first tooltip is automatically showing.  No tooltips should be visible.

### Link to Reproduction

https://codesandbox.io/s/silly-thunder-fjjj8

### Steps to reproduce

1. Go to https://codesandbox.io/s/silly-thunder-fjjj8
2. Click on **Open Alert Dialog**

If you mouse over the tooltip, then off, then back over again, you'll see the tooltip reappear _in a different place_.

### Chakra UI Version

1.6.5

### Browser

Google Chrome 91

### Operating System

- [X] macOS
- [X] Windows

**Comment by anubra266** [comment]
It's not a bug set `autoFocus={false}`  on `AlertDialog` component.
<img width="791" alt="CleanShot 2021-07-18 at 23 52 21@2x" src="https://user-images.githubusercontent.com/30869823/126084541-e1401c78-ee24-4449-9400-735ad7e0d98e.png">
