### ISSUE TITLE
InputLeftElement misalignment when <Input/> size different from "md"

### ISSUE THREAD

**Issue by binajmen** [chakra-ui/chakra-ui#4366]
### Description

`InputLeftElement` misalignment when `<Input/>` size different from `"md"`

### Link to Reproduction

https://chakra-ui.com/docs/form/input#add-elements-inside-input

### Steps to reproduce

1. Go to https://chakra-ui.com/docs/form/input#add-elements-inside-input
2. Add `size="sm"` to the `<Input/>`component
4. See the misalignment

### Chakra UI Version

Latest

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Thank you for your support (and awesome UI library ❤️ ❤️ )

**Comment by segunadebayo** [comment]
Hi @binajmen,

Thanks for filing this issue. To fix the misalignment, please pass the `size` prop to the `InputGroup` component instead of the `Input` component.

```jsx
 <InputGroup size="lg">
    <InputLeftElement
      pointerEvents="none"
      children={<PhoneIcon color="gray.300" />}
    />
    <Input type="tel" placeholder="Phone number" />
  </InputGroup>
```

**Comment by binajmen** [comment]
Oops, I should have thought about this possibility, sorry ;D
