### ISSUE TITLE
Slide's thumb active state doesn't work property on Firefox.

### ISSUE THREAD

**Issue by fvalmeida** [chakra-ui/chakra-ui#4367]
### Description

When you just (not drag) click in the thumb part of the Slider component it doesn't set the active state

### Link to Reproduction

https://codesandbox.io/s/competent-shaw-9qzof?file=/src/index.js

### Steps to reproduce

1. Go to the shared CodeSandbox link using the Firefox browser
2. Click on the Slider's thumb, don't drag it
4. Expected behaviour: The thumb displays the active state, setting the background to red.

**_If you repeat the steps above using the Chrome browser, you will see the expected behaviour happening._**

### Chakra UI Version

1.6.4

### Browser

Firefox 89.0.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Thanks for this detailed bug report @fvalmeida!

I just pushed a fix for this. We'll release an update shortly once merged.

If the issue persists after upgrading, I'll re-open it.
