### ISSUE TITLE
[Toast] Extend toast behavior with theme

### ISSUE THREAD

**Issue by alexluong** [chakra-ui/chakra-ui#4374]
### Description

I'd like to have a default behavior for toast (position, duration, isClosable, etc). Currently, the way to go about it is to create a custom hook.

I'd like to extend it within the theme if possible.

### Problem Statement/Justification

I think the DX for this is cleaner than maintaining my own custom `useToast` hook.

### Proposed Solution or API

```js
export const theme = extendTheme(
  {
    components: {
      useToast: {
        defaultProps: {
          position: "bottom-right",
        },
      },
    },
  },
);
```

**Comment by pierroo** [comment]
I'm sorry I am unable to provide any more information, but were you able to find a solution for this?
The same way, I would like to force the aesthetic of day mode to toast even when dark mode is on. (transparency makes it unreadable considering my background...)

**Comment by samantha-wong** [comment]
+ 1 on this issue. I'm trying to keep my toast position consistent via the theme but it's not working.

**Comment by cpv123** [comment]
+1 for this. I'm about to write my own custom useToast hook to set some default configuration like position, duration etc. but it would be much cleaner to configure this globally in the Chakra theme provider.

**Comment by segunadebayo** [comment]
I totally understand that this is a feature that sounds nice. I believe this can be resolved on your end by creating a wrapper around `useToast`.

From an API design perspective, I don't think it's a good idea to add this. I know you might disagree, but that's okay.

In the upcoming changes to the toast component, we intend to add a global toast provider to configure this from the ChakraProvider directly instead of adding that to the theme.

**Comment by cpv123** [comment]
Thanks, @segunadebayo, sounds like a fair decision 👍

For anyone that comes across this, I ended up writing a wrapper that looks like this:

```
import { useToast as useChakraToast, UseToastOptions } from '@chakra-ui/react';

export default function useToast() {
  const toast = useChakraToast();
  const notify = (toastOptions: ToastOptions) => {
    toast({
      duration: 4000,
      position: 'top',
      isClosable: true,
      ...toastOptions,
    });
  };

  const notifyWithStatus = (status: ToastOptions['status']) => {
    return (toastOptions: ToastOptions) => notify({ ...toastOptions, status });
  };

  return {
	notify,
    notifyError: notifyWithStatus('error'),
    notifySuccess: notifyWithStatus('success'),
    notifyInfo: notifyWithStatus('info'),
  };
}

```
