### ISSUE TITLE
Make the loadingText prop "smarter" in the <Button /> component

### ISSUE THREAD

**Issue by KovJonas** [chakra-ui/chakra-ui#4376]
### Description

It's great that we can add the `loadingText` prop to the `<Button />` component, but the problem is that it isn't customizable, it is only a simple text.

### Problem Statement/Justification

It would be nice if we could customize the `loadingText` properly, for example pass an element (or Chakra UI component) in the `loadingText` prop of the `<Button />` component, so we could use e.g. a `<Text />` as the loading text, with its properties, like `isTruncated`.
It would be useful in cases when you use a small button with a longer text, for example inside modals. I'm currently using chakra UI in a project right now, and I had this problem with a longer text a couple of days ago. Sure I could just use a shorter text, but in some cases (smaller screens), it isn't really possible. 

### Proposed Solution or API

I have two ideas in my mind:

1. The first one is probably the more logical (and simpler) one: since people usually use text in their buttons, maybe you shouldn't even allow to pass a component in the `loadingText` prop, but just add another prop (like `isTruncated`), and render a `<Text />` component around `loadingText`.
2. Extend the type of the `loadingText` property, so that it accepts `React.ReactElement` too. This way, you would give some freedom to the developers using Chakra UI components, but maybe it would be just too much?

### Alternatives

Making a custom button component would be and "okay" solution for this issue, but I thought it would be better if the component would support this functionality out of the box.

### Additional Information

Maybe this issue is a little bit strange, since the text shouldn't be truncated on a button (in terms of UX), but I decided to submit this issue, so I can see other people's thoughts on this topic too.

**Comment by segunadebayo** [comment]
Hi @KovJonas,

I see where this is going and I think the button component is growing in complexity very fast. I'm quite weary to add this feature to it. Maybe a walkaround is to pass a react element instead of a string (I think this might give a type error but it'll work)

I'd recommend working out a solution in your app and post it here if you can.

Thanks for understanding.
