### ISSUE TITLE
Request to add Format Option to NumberInput, Input

### ISSUE THREAD

**Issue by lolcookie** [chakra-ui/chakra-ui#438]
Feature identical or similar to the "formatter" prop here https://ant.design/components/input-number/

Makes it easier to read long numbers that are being inputed if there are commas on them.

Unless there is a way to handle this already?

**Comment by Rodrico** [comment]
Would be great to have this as built-in support. Could have similar signature as `getAriaValueText(...)` on NumberInput.

For us, this would allow removal of another component like `react-numeric-input` - I like chakra variant of numeric input much more and adding this could enable it's usage in more scenarios than now.

**Comment by with-heart** [comment]
Hi @Rodrico! You can achieve that us controlled state: https://next.chakra-ui.com/docs/form/number-input#formatting-and-parsing-the-value
