### ISSUE TITLE
The onClick of Swtich is invalid, I need stopPropagation

### ISSUE THREAD

**Issue by linxianxi** [chakra-ui/chakra-ui#4382]
### Description

 The onClick of Swtich is invalid, I need stopPropagation

### Link to Reproduction

https://chakra-ui.com/docs/form/switch

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

lastest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by with-heart** [comment]
You'll have to explain what you're asking for and why.

**Comment by linxianxi** [comment]
> Please provide a reproduction to demonstrate what you're looking for.

Use switch in Table. Table has onClick event to history.push a new page.If click the switch,table events are also triggered
