### ISSUE TITLE
[Tabs] Overflow navigation

### ISSUE THREAD

**Issue by nelsieborja** [chakra-ui/chakra-ui#4384]
### Description

In case of a long list of tabs, auto-add left/right buttons or tab dropdown to navigate through the hidden tabs.

### Problem Statement/Justification

Would be nice to have this as a native feature of the tab component, instead of resorting to a hacky solution.

### Proposed Solution or API

A quick solution can be found at #1852 - but this will just add a scrollbar instead of buttons/dropdown.

**Comment by Nazeeh21** [comment]
Can I work on this issue?

**Comment by anubra266** [comment]
Yes you can @Nazeeh21

**Comment by segunadebayo** [comment]
Hi @nelsieborja,

We currently won't take on this feature as it can be implemented in a number of ways. Please consider creating a solution for this and sharing it here when you do.

This is a perfect use-case for a  "recipe". If anyone creates a solution around this, feel free to share it here and we'll include it on the website.

Thanks for understanding.

**Comment by Junaid994** [comment]
I have recently implemented the solution. Of course further improvements can be made i.e. U.I part or scroll points etc.

Working Example: https://codesandbox.io/s/vigilant-shape-9mh7q9

import React, { useRef } from "react";
import { ChevronLeftIcon, ChevronRightIcon } from "@chakra-ui/icons";
import {
  ChakraProvider,
  Box,
  SimpleGrid,
  GridItem,
  Tabs,
  TabList,
  TabPanels,
  Tab,
  TabPanel,
  Button,
  Flex
} from "@chakra-ui/react";
import theme from "./theme";

export default function App() {
  const scrollableTabs = useRef(null);

  const items = [
    { id: 1, name: "Item 1" },
    { id: 2, name: "Item 2" },
    { id: 3, name: "Item 3" },
    { id: 4, name: "Item 4" },
    { id: 5, name: "Item 5" },
    { id: 6, name: "Item 6" },
    { id: 7, name: "Item 7" },
    { id: 8, name: "Item 8" },
    { id: 9, name: "Item 9" },
    { id: 10, name: "Item 10" }
  ];

  const scroll = (scrollOffset) => {
    scrollableTabs.current.scrollBy(scrollOffset, 0);
  };

  return (
    <ChakraProvider theme={theme}>
      <Box position="relative" h="100vh" p={12} overflow="auto">
        <SimpleGrid>
          <GridItem width={700}>
            <Tabs>
              <Flex color="white" id="tabsFlex">
                <Button
                  colorScheme="green"
                  variant="ghost"
                  height="inherit"
                  onClick={() => scroll(-80)}
                >
                  <ChevronLeftIcon />
                </Button>
                <TabList
                  ref={scrollableTabs}
                  overflowX="scroll"
                  sx={{
                    "::-webkit-scrollbar": {
                      display: "none"
                    }
                  }}
                >
                  {items.map((item) => (
                    <Tab key={item.id} flexShrink={0}>
                      {item.name}
                    </Tab>
                  ))}
                </TabList>
                <Button
                  colorScheme="green"
                  variant="ghost"
                  height="inherit"
                  onClick={() => scroll(80)}
                >
                  <ChevronRightIcon size />
                </Button>
              </Flex>

              <TabPanels>
                <TabPanel>
                  <p>Tab panel 1</p>
                </TabPanel>
                <TabPanel>
                  <p>Tab panel 2</p>
                </TabPanel>
                <TabPanel>
                  <p>Tab panel 3</p>
                </TabPanel>
                <TabPanel>
                  <p>Tab panel 4</p>
                </TabPanel>
                <TabPanel>
                  <p>Tab panel 5</p>
                </TabPanel>
                <TabPanel>
                  <p>Tab panel 6</p>
                </TabPanel>
                <TabPanel>
                  <p>Tab panel 7</p>
                </TabPanel>
                <TabPanel>
                  <p>Tab panel 8</p>
                </TabPanel>
                <TabPanel>
                  <p>Tab panel 9</p>
                </TabPanel>
                <TabPanel>
                  <p>Tab panel 10</p>
                </TabPanel>
              </TabPanels>
            </Tabs>
          </GridItem>
        </SimpleGrid>
      </Box>
    </ChakraProvider>
  );
}
