### ISSUE TITLE
Popover: Tabbing out of a popover using a Portal doesn't return focus

### ISSUE THREAD

**Issue by kfranqueiro** [chakra-ui/chakra-ui#4386]
### Description

When I tab out of a popover that uses a portal, I expect focus to return to its trigger element, but it doesn't (it's moved into to the browser chrome)

### Link to Reproduction

https://codesandbox.io/s/chakra-popover-portal-focus-0qmrl

### Steps to reproduce

1. Go to https://codesandbox.io/s/chakra-popover-portal-focus-0qmrl and click "open in new window" near the top right
2. Click on "Open popover"
3. Press tab twice
  * The popover closes, but focus is not returned to the trigger element

### Chakra UI Version

Reproduced on latest and also on 1.3.3 (popover 1.2.0)

### Browser

Google Chrome 93

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I suspect this is happening because of the way the blur event handling is set up. By the time it's able to process this event and instruct it to return focus to the trigger, it's already too late, because focus has moved outside of the viewport entirely, into the browser chrome (because the last tabbable element in the popover content was also the last tabbable element in the entire document, due to the portal).

One alternative approach I've seen work for this is to use sentinel elements (invisible but tabbable elements at either end of the content) to handle when focus passes beyond either end of the tabbable elements in the container, which would give you an opportunity to move focus while it's still within the document. However, I realize that a leading sentinel element would be tricky to work with given that the container initially receives focus, which would mean that the leading sentinel (inside the container) would be the first thing in the tab order after that. For this particular issue, given the current logic in place, only a trailing sentinel is strictly necessary (it's how I'm working around this in my own code for now).

**Comment by kfranqueiro** [comment]
This is still an issue with latest chakra using the reproduction steps + codesandbox.

**Comment by kfranqueiro** [comment]
This is still reproducible with the latest version as stated above.

**Comment by kfranqueiro** [comment]
This is still reproducible with the latest version as stated above.

**Comment by kfranqueiro** [comment]
Tangentially, #4385 is also still reproducible and I commented as such, but for some reason the bot closed it anyway, so it'd be great if someone could reopen that...

**Comment by kfranqueiro** [comment]
This is still reproducible in the codepen with the latest version of Chakra as stated above.

#4385 is also still reproducible and was incorrectly closed even though I commented on it, so I would really appreciate that being reopened, if anybody ever sees this ticket.

**Comment by kfranqueiro** [comment]
Apologies for the re-ping, but once again, stale-bot has not removed the stale tag despite me commenting...

**Comment by segunadebayo** [comment]
This is by design. Focus should move to the next focusable element on the page.

You can programmatically control this and return focus as needed. Alternatively, you can implement a focus trap so that the escape key is needed to close the popover.

**Comment by kfranqueiro** [comment]
> This is by design. Focus should move to the next focusable element on the page.

If moving to the next focusable element on the page is what's happening in current Chakra, then that means this bug was fixed, which is good. My test page had originally exhibited focus not returning to anywhere within the page.
