### ISSUE TITLE
[useColorMode] I'm using chakra-ui with Gatsby and it's applying dark mode by default

### ISSUE THREAD

**Issue by junaid33** [chakra-ui/chakra-ui#439]
**Describe the bug**
For some reason, dark mode is being applied by default. When I check LocalStorage, I see darkMode : true. I'm not applying the dark mode at all.

**Expected Behavior**
darkMode should not be applied by default

**To Reproduce**
1. Repo: https://github.com/junaid33/opensource.builders
2. See the bug here: https://opensource-builders.junaidkabani3.now.sh
3. You can check LocalStorage and see the darkMode is true
4. You can click the toggle light button and this fixes it. This should be the default. 

**Suggested solution(s)**

I tried passing "light" into the useColorMode:

  const { colorMode, toggleColorMode } = useColorMode("light")

But this did not work.
**Desktop (please complete the following information):**

**Additional context**

**Comment by ivan-dalmet** [comment]
Hey, @junaid33 any chance that your system is in Dark mode?
Because Chakra UI default color mode is based on the user system preference ;) 
If you don't want the color mode at all, you should remove the `<ColorModeProvider>` in your app ;)

**Comment by junaid33** [comment]
I haven't used <ColorModeProvider> at all. It just defaults to dark mode: true in local storage.

Please check this link: https://opensource-builders-hq7rifoee.now.sh. The text appears at first and then fades away. If you check the element, you will see it says <body class="dark-mode">.

As a temporary fix, I manually added color to the text and change local storage to darkMode: false.

Is this a Gatsby issue?

**Comment by junaid33** [comment]
Oh are you asking if my operating system settings has dark mode on? It does, but how can I make Chakra-ui not use that when loading the website?

**Comment by junaid33** [comment]
Oh wow you were right! I turned my system from dark mode to light mode and the website is all fixed now.

**Comment by ivan-dalmet** [comment]
Yes! Look at this article for how to use JS to know system preference -> https://medium.com/@jonas_duri/enable-dark-mode-with-css-variables-and-javascript-today-66cedd3d7845 ;)
If you don't want to use the dark theme at all, remove the `<ColorModeProvider>` component that wrapping your app.

**Comment by junaid33** [comment]
But I'm not using <ColorModeProvider> at all. I don't import it into the app.

**Comment by ivan-dalmet** [comment]
Oh sorry, I didn't see that you are using the Gatsby plugin.
You can configure the plugin to don't use the Color Mode -> https://www.gatsbyjs.org/packages/gatsby-plugin-chakra-ui/#gatsby-plugin-options
```
// gatsby-config.js
module.exports = {
  plugins: [
    {
      resolve: "gatsby-plugin-chakra-ui",
      options: {
        /**
         * @property {boolean} [isResettingCSS=true]
         * if false, this plugin will not use `<CSSReset />
         */
        isResettingCSS: true,
        /**
         * @property {boolean} [isUsingColorMode=true]
         * if false, this plugin will not use <ColorModeProvider />
         */
        isUsingColorMode: true,
      },
    },
  ],
};
```

**Comment by ivan-dalmet** [comment]
So just add this code `isUsingColorMode: false,`
on line 30 of this file https://github.com/junaid33/opensource.builders/blob/master/gatsby-config.js
It should work pretty well :)

**Comment by junaid33** [comment]
Thank you so much! Should've read the readme for the plugin.

**Comment by ivan-dalmet** [comment]
No problem 😄
