### ISSUE TITLE
`useToast` and `createStandaloneToast` which do not work

### ISSUE THREAD

**Issue by stla** [chakra-ui/chakra-ui#4390]
### Description

Hello,

  I wrapped `Chakra UI` in a R package [shinyChakraUI](https://github.com/stla/shinyChakraUI). The `useToast` and `createStandaloneToast` hooks did not work, and they did work after I modified the file `toast.class.js`.

### Problem Statement/Justification

So I want to propose a modification. The reason is that the current implementation does not work with my package. I'm not a star in JavaScript, so I don't know whether this modification could cause a problem in other situations. But maybe it would solve some issues other than mine.

### Proposed Solution or API

The problem is that `document.body` in `toast.class.js` is `null` with the current implementation, in my situation. So I modified the code as follows, in `constructor`:

```
    if (!isBrowser) return;

    var portal;
    var existingPortal = document.getElementById(portalId);

    var elem = React.createElement(ToastManager, {
      notify: this.bindFunctions
    });

    if (existingPortal) {
      portal = existingPortal;
      render(elem, portal);
    } else {
      document.addEventListener("DOMContentLoaded", function () {
        var _document$body;
        var div = document.createElement("div");
        div.id = portalId;
        (_document$body = document.body) == null
          ? void 0
          : _document$body.appendChild(div);
        portal = div;
        render(elem, portal);
      });
    }
```

The point which solved my issue is the inclusion of the `document.addEventListener("DOMContentLoaded", ...`. 

Would it cost something to add this `document.addEventListener("DOMContentLoaded", ...` in the source code?

**Comment by segunadebayo** [comment]
Hey @stla,

This sounds like a great idea but I'd recommend using `patch-package` on NPM to apply a temporary fix for your use-case. We plan to rewrite the toast component pretty soon but I can't guarantee a timeline.
