### ISSUE TITLE
Popover freezing page in Preact

### ISSUE THREAD

**Issue by oguzhane** [chakra-ui/chakra-ui#4397]
### Description

The Popover freezing page when used with Preact.

### Link to Reproduction

https://github.com/OguzhanE/chakraui-popover-preact-issue/blob/master/src/routes/home/index.js

### Steps to reproduce

1. Use basic example of `<Popover />` in [the docs.](https://chakra-ui.com/docs/overlay/popover#basic-usage)
2. Page is freezing instead rendered successfully 

### Chakra UI Version

1.6.5

### Browser

Google Chrome 91

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Any `<Popover/>` does not render and causing crash in page. Apparently, it gets into infinite render. Link to reproduction can be found in the home page in [this repo](https://github.com/OguzhanE/chakraui-popover-preact-issue/blob/master/src/routes/home/index.js)

**Comment by codetheweb** [comment]
Still happening in 1.6.7. Would love to use Preact and this is the only thing blocking the transition at the moment. :)

**Comment by TheThirdRace** [comment]
Maybe related to this https://github.com/chakra-ui/chakra-ui/issues/4821

**Comment by mjgerace** [comment]
Encountered this issue as well.

**Comment by mjgerace** [comment]
Any update on this issue?

**Comment by mjgerace** [comment]
@segunadebayo I have pinpointed the exact issue, here: https://github.com/mjgerace/chakra-ui/blob/main/packages/popover/src/use-popover.ts#L418:L420

I don't know what this `setHasBody(!!node)` does, but it causes an infinite render cycle with `preact`. Changing line 418 to ref: ref fixes the infinite loop - as an added bonus, popover seems to work fine. Could you PR a fix for this? I lack context on why setHasBody is needed.

**Comment by TheThirdRace** [comment]
Infinite loops should definitely be fixed by Chakra.

Chakra definitely needs efforts to reduce their JS bundle-size because at the moment it's pretty much atrocious.

The gains in bundle-size by using Preact vs React are substantial, no reason to not fix Preact and pass that benefits to users.

**Comment by TheThirdRace** [comment]
Just preventing the stale bot...

**Comment by TheThirdRace** [comment]
Just preventing the stale bot...

**Comment by segunadebayo** [comment]
This is no longer an issue with the latest version of Preact:
https://codesandbox.io/s/interesting-artem-j05syq?file=/src/index.js
