### ISSUE TITLE
[Button] Text alignment does not work

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#44]
When creating a button wider than its contents (e.g. with its uncodumented `isFullWidth` prop or `width="100%"`), the `textAlign="left"` does nothing. I tried playing around with left and right paddings, but with no luck.

#### Example

```tsx
<Button isFullWidth textAlign="left">
  I'm a full width button with text aligned to the left
</Button>
```

#### Current appearance

![image](https://user-images.githubusercontent.com/14854048/64485443-441cc280-d221-11e9-8161-57d88c73b018.png)

#### Expected appearance

![image](https://user-images.githubusercontent.com/14854048/64485427-1d5e8c00-d221-11e9-830e-43e999f5b446.png)

#### Use-case

When a group of buttons contain check boxes or radios, one may want to align them together.

**Comment by lee-reinhardt** [comment]
If you look at the button's css, it's `display: inline-flex`. If a container is flex'd, `text-align` is not respected -- you should use `justify-content` for child alignment.

This works as expected:
```
<Button width="100%" justifyContent="flex-start">
  Button Text
</Button>
```

**Comment by kripod** [comment]
@lee-reinhardt Thanks for your quick response! Could you please add a note about it inside the docs? I'd happily close the issue afterwards.

**Comment by segunadebayo** [comment]
I'll add this to the docs. Thanks for the quick response @lee-reinhardt

**Comment by Chokerino** [comment]
@lee-reinhardt Could you please tell how to align 2 different texts on either end? Justifying button content aligns both to the same side.
