### ISSUE TITLE
Editable component can't be clicked when empty

### ISSUE THREAD

**Issue by EChristian48** [chakra-ui/chakra-ui#4403]
### Description

When an Editable is empty, I can't click on it to change the value

### Link to Reproduction

https://codesandbox.io/s/jovial-shadow-1ctmc

### Steps to reproduce

1. Click the Editable
2. Delete the text
3. Get out of focus (Press enter, click somewhere else, etc)

### Chakra UI Version

1.6.5

### Browser

Google Chrome 91

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

You can also recreate it in the [documentation page](https://chakra-ui.com/docs/form/editable)

![me doing that](https://i.imgur.com/rSTlFZm.gif)

**Comment by EChristian48** [comment]
One solution that I found was using `placeholder` to make sure it's still clickable.

**Comment by segunadebayo** [comment]
After taking a look at this, I think this can be fixed on your end.

Ideally, the user wants to specify a `placeholder` when the input is empty to prevent this. Just like @EChristian48 suggested (thank you!)

Another alternative is to add `width:100%` to `EditablePreview` component.
