### ISSUE TITLE
Icon not centering itself inside Input

### ISSUE THREAD

**Issue by somguyth** [chakra-ui/chakra-ui#4404]
### Description

I'm trying to position an icon correctly in the middle of an input, where that input has size="xs". However, all my attempts have failed, and the icon keeps being positioned too low/down. I've also tried using IconButton instead of a regular icon but that didn't work either. See a further discussion here: https://github.com/chakra-ui/chakra-ui/discussions/4402

### Link to Reproduction

https://codesandbox.io/s/optimistic-bartik-5ifsd?file=/src/App.tsx

### Steps to reproduce

Just visit the code sandbox.

### Chakra UI Version

Latest

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by anubra266** [comment]
Just Add `h="full"` to the `InputLeftElement` Component.

**Comment by anubra266** [comment]
@somguyth Could you close this issue, if you've found an answer.
