### ISSUE TITLE
Menu stays stays focused while trying to set focus on another element 

### ISSUE THREAD

**Issue by jsefiani** [chakra-ui/chakra-ui#4415]
### Description

When I click on a menu item, I expect the menu button to become unfocused when another element on the page is programmatically focused.

### Link to Reproduction

https://codesandbox.io/s/magical-hermann-xhkcv?file=/src/App.tsx

### Steps to reproduce

1. Click on "Open Menu"
2. Select menu item "Do something"

**Actual result**: input is not programmatically focused, because the menu button stays focused.

**Expected result**: input is programmatically focused.

### Chakra UI Version

1.6.5

### Browser

Brave

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by nelsieborja** [comment]
@jsefiani, I am facing the same issue. How did you fix it?

**Comment by jsefiani** [comment]
@nelsieborja by using Chakra UI's custom `focus` method. The first argument is the element and the second argument is an object where you need to set the `nextTick` property to `true`. I hope this helps!

**Comment by anubra266** [comment]
Hi @jsefiani could you paste a code sample, don't know where the custom focus method comes from.

**Comment by nelsieborja** [comment]
Thank you for sharing your solution, @jsefiani. I will give it try.
