### ISSUE TITLE
theme for AccordionButton 

### ISSUE THREAD

**Issue by katwingki** [chakra-ui/chakra-ui#4426]
### Description

I was trying to create a theme for AccordionButton component

It was imported in the main theme using the same component name, somehow the theme did not apply like all the other themes that is within the same app. 
Things have tried, create variant and pass it in through defaultProps. 

### Problem Statement/Justification

It will help the development stay consistent to use theme instead of inline styling or separate css files. 

### Proposed Solution or API

https://chakra-ui.com/docs/disclosure/accordion#accordionbutton-props

```
const AccordionButton = {
    baseStyle: {
        bg: '#000',
        display: 'flex',
        justifyContent: 'center',
        ml: '-16',
        _focus: {
            boxShadow: 'none'
        }
    }
};

```

**Comment by TimKolberger** [comment]
The Accordion component is a multipart style component. At the top of each component documentation is a link the the "theme source". There you can copy and alter the default styles for your application.

[Theme source Accordion](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/accordion.ts)

Hope this helps 😊 feel free to close this issue if your question is resolved.

**Comment by katwingki** [comment]
Go it, thank you, that's helpful.
