### ISSUE TITLE
CSS side effects with global chakra styles

### ISSUE THREAD

**Issue by aman-fit** [chakra-ui/chakra-ui#4427]
### Description

CSS global styles from ChakraProvider should not effect elements outside the chakra provider block

### Link to Reproduction

https://codesandbox.io/s/affectionate-lamport-8sc86?file=/src/App.js

### Steps to reproduce

https://codesandbox.io/s/affectionate-lamport-8sc86?file=/src/App.js

In the above link one can inspect elements outside ChakraProvider block, it will have css styles injected by Chakra

I understand, emotion injects styles to head but what are the workarounds? 

### Chakra UI Version

1.3.3

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by TimKolberger** [comment]
Maybe `<ChakraProvider resetCss={false} />` solves your issue.

Chakra applies a global css reset to ease the cross browser support. 

[See in the docs](https://chakra-ui.com/docs/getting-started#chakraprovider-props)

Please close this issue, if it is solved 😊

**Comment by TimKolberger** [comment]
The CSS reset has an effect on a global level - you can disable the [built-in CSS reset](https://github.com/chakra-ui/chakra-ui/blob/main/packages/css-reset/src/css-reset.tsx) and provide your own or implement a emotion stylis plugin as Mark mentioned in https://github.com/chakra-ui/chakra-ui/issues/4164#issuecomment-854129457. These are currently the only options I can think of.

Possible next steps:

I think we could export the pure CSS reset in a CSS object notation, to reuse the default styles in a userland project.

Something like 

```ts
// packages/css-reset/src/css-reset.tsx

export const defaultCssReset = {
  html: { /* ... */ },
  body: { /* ... */ },
  "*, *::before, *::after": { /* ... */ }, 
  // ...
}

export const CSSReset = () => (
  <Global styles={defaultCssReset} />
)
```

Would that solve your issue?

**Comment by anilanar** [comment]
Q: Is there a definitive answer on whether if css-reset is optional or not?

**Comment by anubra266** [comment]
Hi @TimKolberger what's the update on this?

**Comment by anubra266** [comment]
@aman-fit if @TimKolberger's answer does not satisfy your requirements, feel free to reopen this issue

**Comment by 202212055Arkan** [comment]
I am facing the same issue I use chakra in one body component but it effects my nav component.
