### ISSUE TITLE
Storybook viewport add-on not working with responsive styles

### ISSUE THREAD

**Issue by tuler** [chakra-ui/chakra-ui#4429]
### Description

When I create a component using responsive styles, then test it using storybook the viewport selection in storybook does not work as expected

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-typescript-pomi8?file=/src/index.tsx

### Steps to reproduce

1. Develop a component using responsive styles
2. Load it up at storybooks
3. Change the viewport size to "Large mobile"
4. media-query not properly triggered

### Chakra UI Version

6.3.4

### Browser

Google Chrome 92.0.4515.107

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by tuler** [comment]
Adding `resetCSS` to `ChakraProvider` in the preview seems to fix the problem.

**Comment by segunadebayo** [comment]
Glad you found a solution 👌
