### ISSUE TITLE
[Icon] TypeScript throws error if we use a custom component name

### ISSUE THREAD

**Issue by gopinav** [chakra-ui/chakra-ui#443]
**Describe the bug**
If you add custom icons to your theme and try use it for an Icon component, TypeScript throws an error

**Expected Behavior**
TypeScript should not flag error for custom icons used.

**Comment by segunadebayo** [comment]
Hi @gopinav, This is a duplicate of #204.

I've just merged a PR that fixed this. Will release a patch shortly.
