### ISSUE TITLE
Custom breakpoints on specific page tutorial

### ISSUE THREAD

**Issue by jessielam415** [chakra-ui/chakra-ui#4430]
### Description

Request to add a tutorial on how to add custom breakpoints for responsive styles on a specific page in an app. 

### Problem Statement/Justification

I have been reading through the chakra docs (https://chakra-ui.com/docs/features/responsive-styles). I understand that I can create custom breakpoints for the entire app through modifying _app.tsx, however, I cannot find a guide on how I can set custom breakpoints for just one page of an app.

### Proposed Solution or API

Please add a tutorial in the chakra docs on how to do this

**Comment by segunadebayo** [comment]
Hi @jessielam415,

This depends on the framework you're building with. With Next.js you need to wrap each page within `ChakraProvider` to allow for page-specific changes to the `theme` object. I think you can do the same with Gatsby.

It's not a common use-case at the moment so I don't think we should include it in the docs.

The key solution to this is that the framework you use needs to allow you to wrap each page within `ChakraProvider`.

Hope you find this helpful.

PS: To get more specific help, please send over a CodeSandbox reproduction.
