### ISSUE TITLE
Various issues when rendering into a different window

### ISSUE THREAD

**Issue by agundermann** [chakra-ui/chakra-ui#4457]
### Description

When rendering chakra components into a different window object (e.g. popup via window.open), I expect the components to behave correctly as if I rendered them into the current window. For example, `<Menu>` should close when clicking outside or selecting an item.

### Link to Reproduction

https://codesandbox.io/s/gifted-cartwright-km537?file=/src/index.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/gifted-cartwright-km537?file=/src/index.js
2. Click on "Render in Popup"
3. In the popup, click the "Actions" menu. Make sure the original window is visible on your screen otherwise it won't open.
4. Try to close the menu by selecting an item or clicking outside

Note that the menu in the original window works as expected.

### Chakra UI Version

1.6.5

### Browser

Chrome 92

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

We're using chakra-ui in a multi-window electron app, which renders into different windows using React portals. Chakra portals, styling etc. worked out of the box 👏 but some components like Menu misbehave.

I already tracked it down to `instanceof Element` checks (and similar), which fail if the element belongs to a different window. Will open a PR soon.

By the way, in this use case, there's also an issue around `window.requestAnimationFrame` usage, which is why the Menu doesn't open when the original window is covered/minimized. Ideally, the timers would also be called on the `window` object that belongs to the respective component, but these calls may be deeper inside framer dependencies.

**Comment by segunadebayo** [comment]
Really interesting breakdown of the issue. Thanks for being so detailed @agundermann.

I'll take a look at your PR to get a better understanding of the solution you have in mind.

**Comment by agundermann** [comment]
@segunadebayo thanks! 🎉
