### ISSUE TITLE
Accordion: defaultIndex does not work in SSR

### ISSUE THREAD

**Issue by mjnaderi** [chakra-ui/chakra-ui#4483]
### Description

I have an accordion and some items need to be expanded initially (using `defaultIndex`). When accordion is rendered at server side, all accordion items are collapsed initially, and they expand after JavaScript loads on client side.

### Link to Reproduction

https://codesandbox.io/s/rough-wind-ktbb8?file=/pages/index.tsx

### Steps to reproduce

1. Go to https://ktbb8.sse.codesandbox.io/
2. Open Chrome DevTools, Open Settings. In "Debugger" section click on "Disable JavaScript".
3. Reload the page.
4. The first accordion item is closed, but it should be expanded according to `defaultIndex`.

### Chakra UI Version

1.6.5

### Browser

Any Browser

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

I'm using Next.js + ChakraUI. The page needs to be SEO-friendly, but I have this problem with Accordion component. This has increased the page's [CLS](https://web.dev/cls/) (Cumulative Layout Shift) metric in Google PageSpeed Insights.

**Comment by bendvc** [comment]
I'm seeing the same behaviour in `1.6.6` as well. Looking at the code, the context for `isExpanded` is coming from the `useAccordion` hook, is that hook running server-side?

**Comment by segunadebayo** [comment]
Please see my comment here: https://github.com/chakra-ui/chakra-ui/issues/4506#issuecomment-904488909
