### ISSUE TITLE
Remove the blog section

### ISSUE THREAD

**Issue by MasterGordon** [chakra-ui/chakra-ui#4488]
### Subject

Blog

### Description

I think the blog section should be removed from the chakra-ui webpage since there is no content since November 13, 2020.
This seems like the project is stale if you are just looking at the blog.

**Comment by TimKolberger** [comment]
I think this is a good idea. If we do not use the blog, we don't need a blog 😅 

I'd be happy to merge a PR which includes the following changes:

- [ ] Remove the blog link from all navs
- [ ] Delete all blog related files in `pages/blog` and helpers like`utils/get-blog-posts`

@segunadebayo What do you think?

**Comment by segunadebayo** [comment]
@TimKolberger, let's make it happen.

I'd like to blog more often but I think when we can either move blogging to a different platform or use a different repo for it.

Thanks for bringing this up @MasterGordon. Less is more 👌
