### ISSUE TITLE
ThemeOverride['components'] types are not reusable 

### ISSUE THREAD

**Issue by samijaber** [chakra-ui/chakra-ui#4497]
### Description

When I try to annotate my theme overrides, I get a lot of type errors.

### Link to Reproduction

https://codesandbox.io/s/morning-bird-ql323?file=/src/theme.ts

### Steps to reproduce

The codesandbox has these steps implemented in the `Button` override object:

1. Try to override a component's theme (in my case, `Button`)
2. Annotate the config with `ThemeOverride["components"]["Button"]`
3. provide overrides for styles not implemented in default theme for that component
4. See type errors

### Chakra UI Version

1.6.5

### Browser

not browser-specific

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

You will see in the codesandbox 3 variations:
- `ButtonUntyped` which has no type annotation. This works fine
- `Button` which has type `ThemeOverride['components']['Button']`. This has type errors in it
- `ButtonAsConfig` which has type `ComponentSingleStyleConfig`. This has no type errors in it, but adding it to a `ThemeOverride` object causes tons of confusing type errors to other theme objects in the tree.

I tried having a separate `Button` object because that is the approach that Chakra UI docs recommend on scaling out a project's themes: see https://chakra-ui.com/docs/theming/customize-theme#scaling-out-your-project

**Comment by 5ebastianMeier** [comment]
Curiously this works:
```
const works: ThemeOverride["components"] = {
  Button: {
    baseStyle: {
      borderRadius: "0px",
      h: "auto",
      position: "relative"
    },
    sizes: {
      sm: (props) =>
        props.variant !== "unstyled"
          ? {
              px: "2",
              py: "2",
              fontSize: "xs"
            }
          : {}
    },
    variants: {
      solid: ({ colorScheme }) => ({
        bg: colorScheme === "grey" ? "grey.4" : "white",
        color: "dark"
      }),
      unstyled: {
        fontWeight: "inherit",
        fontFamily: "inherit"
      }
    }
  }
}
```
It might be caused by the way the [ `DeepPartial` is used in the ThemeExtension](https://github.com/chakra-ui/chakra-ui/blob/main/packages/react/src/extend-theme.ts#L25), but the internals are not easy to grasp for me right now.

**Comment by segunadebayo** [comment]
I'm going to admit that the theme extension types got pretty complex to manage (a lesson we learned).

Please consider the alternative solution suggested by @5ebastianMeier or use any of the other theme extension functions.

We plan to rewrite the types in the next major release.
