### ISSUE TITLE
Request to add children styling prop

### ISSUE THREAD

**Issue by sidneyramos** [chakra-ui/chakra-ui#450]
**Is your feature request related to a problem? Please describe.**
There currently isn't a way to provide css selectors for the children of a selected component. 

**Describe the solution you'd like**
A children prop, or anything similar that accepts an object would be nice
e.g.
children={{
  "div": <style object applying to all children div>,
  ".className": <style object applying to all children with class className>,
  "& > .className": <style object applying to all direct children with class className>,
...so on and so forth
}}

**Describe alternatives you've considered**
One solution was to use emotion/styled-components to inject custom css on a component

**Comment by segunadebayo** [comment]
Hi @sidneyramos, I don't think this something Chakra is looking to provide.

This is what the PseudoBox component was made to solve. If you can provide a Codesandbox example, I'll work it out and send to you, so you see what I mean.
