### ISSUE TITLE
Typescript: assigning false to ResponsiveValue which expects `undefined`

### ISSUE THREAD

**Issue by scottrepreneur** [chakra-ui/chakra-ui#4503]
### Description

When I'm assigning a unary within a Chakra prop it is giving me an error when for most ResponsiveValue types

### Link to Reproduction

https://codesandbox.io/s/chakra-false-responsive-prop-h5d3o

### Steps to reproduce

1. initiate Box with `color` or other prop
2. use a unary expression within the prop `prop={boolean expression && 'colorValue'}`
3. type error for `Type 'false' is not assignable to type 'ResponsiveValue`

### Chakra UI Version

1.6.5

### Browser

n/a

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

@types/react@17.0.5

can't tell if this is the expected behavior. been using these for a while and recently broke when we switched to `strict: true` for implementing nextjs. is this expected?

is a ternary preferred here? `prop={booleanExpression ? 'color' : undefined}`

**Comment by ljosberinn** [comment]
this is expected behaviour of `&&`. `false && 1` will return `false`, and if the prop does not allow booleans, then you end up with a type incompatibility
