### ISSUE TITLE
[Website] Table of Content shows wrong `activeId`

### ISSUE THREAD

**Issue by takethefake** [chakra-ui/chakra-ui#4507]
### Description

When navigating the website I noticed that the active Element in the Table of Contents does not match my expect active Element.

### Link to Reproduction

https://chakra-ui.com

### Steps to reproduce

1. Go to any Site with headings on the website
2. Scroll the Website
3. Check the active Section in the Table of Contents on the right
4. Often the Section below the current section is highlighted since we are only checking if the heading is in the viewport and not the length of the content corresponding to the heading.

### Chakra UI Version

1.6.5

### Browser

Google Chrome 93

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

Not sure if there is an easy fix here because we need to group content by heading somehow and check if the group is still in the viewport otherwise show the next heading as `activeId`

`activeId` is received here in `table-of-content` with this we only check for headings not for any content below the heading
https://github.com/chakra-ui/chakra-ui/blob/ca4998d7de437731eddbfb2496b72a07fd41c04f/website/src/components/table-of-content.tsx#L20:L25

to give an example:
![Screen Shot 2021-08-03 at 14 12 58](https://user-images.githubusercontent.com/3123354/128013421-f9b4bd02-0a59-469d-ae5a-0e72ecada4c5.png)

I expected that `Installation` is still the active element since there is still content from it in the viewport

Also sometimes it could happen that you click on an item in the Table of Contents, you get scrolled to the desired view and once you arrive the Table of Contents moves its active state to the section below.

Example https://chakra-ui.com/docs/form/number-input -> Click on `Setting a minimum and maximum value`

### Solutions

recently saw that vuepress solves the problem quite well! https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/plugin-active-header-links/clientRootMixin.js

**Comment by segunadebayo** [comment]
Thanks for noticing this @takethefake. I don't think this is a pressing issue for now.

Feel free to open a PR if you have ideas to fix this.  Due to the limited manpower we have, I think we can de-prioritize fixing this. Just to clean up the issue board.

Thanks for understanding.
