### ISSUE TITLE
Chakra factory baseStyles types broken

### ISSUE THREAD

**Issue by LonJonn** [chakra-ui/chakra-ui#4509]
### Description

When I write my base styles in the chakra factory function, I expect the object to be correctly typed, however, 

### Link to Reproduction

can't reproduce in codesandbox

### Steps to reproduce

Use the factory function
```tsx
const Wrapper = chakra(Box, {
  baseStyles: {
    display: "flex", // This should be typed correctly (e.g. intellisense, etc) but isn't
    // But if you use responsive shortcut, it works
    display: ["flex", "block"], // This DOES get typed correctly
    _hover: {
      display: "flex" // Same deal for selector styles, only arrays of values are typed
    }
  }
});
```

### Chakra UI Version

1.6.5 (latest)

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

After digging through the @chakra/styled-system types, I found that changing the following from:
```ts
export declare type CSSWithMultiValues = {
    [K in keyof SystemCSSProperties]?: K extends keyof StyleProps ? StyleProps[K] | PropertyValue<K> : PropertyValue<K>;
};
```
to
```ts
export declare type CSSWithMultiValues = {
    [K in keyof SystemCSSProperties]?: K extends keyof StyleProps ? StyleProps[K] : PropertyValue<K>;
};
```
_seems_ to resolve the issue, however, I'm quite inexperienced in working with types so I'm not sure this is a proper fix.

**Comment by anubra266** [comment]
@TimKolberger any updates on this?

**Comment by TimKolberger** [comment]
Thanks for the ping - I'll give this a shot in the next days.

**Comment by TimKolberger** [comment]
There is a small typo in the example, the key is `baseStyle` - without the trailing s.
Autocomplete works for me with @chakra-ui/react@1.8.1.

```ts
const Wrapper = chakra(Box, {
  baseStyle: {
    display: "flex",
    // display: ["flex", "block"],
    _hover: {
      display: "flex"
    }
  }
});
```
