### ISSUE TITLE
Keyboard navigation does not scroll down the view when MenuList is long

### ISSUE THREAD

**Issue by icy-meteor** [chakra-ui/chakra-ui#4510]
### Description

When the list of menu items is long, the keyboard navigation on <MenuList/> component doesn't automatically scroll the list down after hitting the end of the list in current view.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-menu-bug-vwqtm?file=/src/App.tsx

### Steps to reproduce

1. Open the dropdown
2. Try to move down with your down arrow.
3. Notice that after hitting the end of list of the current view, the entire view stays in same place without scrolling down.

### Chakra UI Version

1.6.4

### Browser

Google Chrome 93

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I found an old codesandbox with a similar situation but with Chakra UI Version 1.0.0. 
It seemed to work fine in that.

**Comment by takethefake** [comment]
Checked the example and found out that the problem somehow is linked to the duplicate occurrence of the `title`  inside the values object. Will investigate further.

**Comment by icy-meteor** [comment]
Oops, looks like my sandbox link got overwritten by some other stuff, that's related to a third party package.
This is the right link - https://codesandbox.io/s/chakra-ui-menu-bug-vwqtm?file=/src/App.tsx

**Comment by Jzmang** [comment]
Hi! It seems like for chakra v2.8.2, the scroll function does not work. I tried adding height="150px" and overflow="auto" to the MenuList and keyboard navigation via arrow keys does not scroll the view (did this in Chakra UI's website). Are there any workaround for this?
