### ISSUE TITLE
Chakra UI Slider does not handle re-renders as expected (focus grabbing and browser locking loop)

### ISSUE THREAD

**Issue by offe** [chakra-ui/chakra-ui#4512]
### Description

When I use <Slider> I expect it to behave like <input type="range"> when it comes to re-renders and handling of focus. Instead the last <Slider> on the page takes focus. When using the keyboard it goes into an infinite loop of jumping focus between the Sliders on the page. 

### Link to Reproduction

https://codesandbox.io/s/l3dks?file=/src/index.js

### Steps to reproduce

The codesandbox can be run in two modes, by setting USE_CHAKRA_SLIDER to true or false. 

1. Set USE_CHAKRA_SLIDER to false, and it works like expected: 

2. You can drag the two sliders left and right. You can control them with keyboard, tab and shift-tab between them. Change value with left-right. If you select a value of 6 or higher on the first slider, the second one gets hidden (it's like that, because the point of the bug is that the page needs to get re-rendered). 

3. Set USE_CHAKRA_SLIDER to true and reload. 

4. The slider looks better, because it is Chakra! 
5. It basically works if you are using the mouse, but you will notice that the second slider will always grab focus, even if you moved the first slider. 
6. Now for the worst part: Change the value of the first slider with keyboard (by getting it to focus with tab, and then pressing left/right). Now you will have an infinite loop where focus is jumping between the first and second slider. 

### Chakra UI Version

1.6.5

### Browser

Google Chrome and Safari

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by takethefake** [comment]
I've checked the behavior and it happens because both sliders share the same state. 

On keyboard navigation we call the `onChangeEnd` function. which triggers `setAnswer`  in your example which triggers another `onChange` call which leads into an infinity loop and your described behavior. 

To solve your problem I would separate the states.

**Comment by offe** [comment]
Thank you for looking at it, I really appreciate you taking the time. I still don't completely understand the problem, but at least I have an acceptable workaround, I'll simply won't use onChangeEnd. I don't see how I would separate the states, since the second slider depends on the value of the first slider (should be hidden for some values). 

onChangeEnd is still doing something strange. If I change the lines from 29 to this: 

```
          onChange={(v) => {
            setValue(v);
            setAnswer(v);
          }}
          onChangeEnd={() => {}}
```
I don't get the infinite loop, but the second slider will steal the focus if I change the value of the first slider. BUT if you remove the onChangeEnd={()=>{}}, it no longer does that! I would expect using a NOP-function as onChangeEnd would give me the same behaviour as not using onChangeEnd at all.

**Comment by takethefake** [comment]
I spend some time investigating your example a little further and the main problem was that the `setAnswer` function changed on every render which called an internal Effect.

A possible solution for your problem could look like this https://codesandbox.io/s/chakra-slider-problem-forked-c2oou?file=/src/index.js

**Comment by offe** [comment]
Thank you again! I could not get your useCallback suggestion to work for me in my real project. Right now I'm fine with avoiding onChangeEnd. If I miss it I will look into this again. Thank you for your help!
