### ISSUE TITLE
Tabs: changing default TAB behavior?

### ISSUE THREAD

**Issue by romseguy** [chakra-ui/chakra-ui#4515]
### Description

When trying out this example : https://chakra-ui.com/docs/disclosure/tabs#creating-custom-tab-components I noticed using keyboard TAB that only first tab gets selected, so I wanted to allow selecting other tabs (only switching to the corresponding panels after hitting SPACE/ENTER)

### Problem Statement/Justification

Default <Tabs> keyboard behavior should be same as other components default behaviors

### Proposed Solution or API

```javascript
      const tabProps = useTab(props);
      tabProps.tabIndex = 0;
      tabProps.onClick = useCallback(tabProps.onFocus);
      tabProps.onFocus = () => {};
```

**Comment by takethefake** [comment]
Currently the tabs component uses [Automatic Activation](https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-1/tabs.html). As far as i understood your request you want to have a possibility to enable [Manual Activation](https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-2/tabs.html) ?

**Comment by romseguy** [comment]
Yes.

**Comment by takethefake** [comment]
This should be possible with the `isManual`-prop see https://chakra-ui.com/docs/disclosure/tabs#tabs-with-manual-activation

**Comment by romseguy** [comment]
Indeed, with `isManual` and `tabProps.tabIndex = 0` it works fine, thanks!
