### ISSUE TITLE
aspect-ratio not supported

### ISSUE THREAD

**Issue by ngregrichardson** [chakra-ui/chakra-ui#4516]
### Description

Passing `aspectRatio` into layout components isn't recognized, it only works when passing it into the `sx` prop.

### Link to Reproduction

https://codesandbox.io/s/happy-brattain-s7uku?file=/src/App.js

### Steps to reproduce

1. The red box has `aspectRatio={'1'}` passed directly into it, but it does not show up as `aspect-ratio: 1;` in the rendered page.
2. The blue box has `aspectRatio={'1'}` passed through the `sx` prop and it renders as expected.

### Chakra UI Version

1.6.5

### Browser

Brave Version 1.27.108

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by takethefake** [comment]
To my knowledge `Box` and other layout-components don't support `aspectRatio`. 

If you want to use ratio direct on the component without providing the ratio with the `sx` prop you could use the `AspectRatio` component and since the use case can still be achieved with the `sx` prop I don't see any need to add an `aspectRatio`-prop to all layout components.

@with-heart @segunadebayo @TimKolberger  - correct me if I'm wrong here.

**Comment by ngregrichardson** [comment]
That makes sense, I've used the `AspectRatio` component a few times and I personally don't mind using `sx` for it. Just wasn't sure if that was intended behavior or not and figured I might as well report it in case it wasn't intended as I know `aspect-ratio` is still technically pretty new.

**Comment by TimKolberger** [comment]
Thanks for bringing this up @ngregrichardson!

We support the most common CSS properties as component props.
A CSS property which refers to a token in the theme makes sense to provide them as a component prop, but the `aspect-ratio` is a rarely used (imo) one and can be achieved with our `<AspectRatio />` component.

Let's see if this issue gets a few upvotes or the stale does it's job and closes this feature request.

**Comment by volkyeth** [comment]
Another reason for adding it: The `AspectRatio` component scales its content to fill it, while with `aspect-ratio` the content dimensions is not affected. They have different use cases
