### ISSUE TITLE
Certain CSS Vars not applying custom prefix

### ISSUE THREAD

**Issue by fandy** [chakra-ui/chakra-ui#4519]
### Description

When I set a custom prefix in the theme config, I expected all CSS vars to be prefixed, but a few aren't.

### Link to Reproduction

N/A

### Steps to reproduce

These CSS Vars are unaffected by the custom prefix:

![image](https://user-images.githubusercontent.com/19108762/128271516-35cd8db7-72d9-49fa-add9-9e8d49f338aa.png)

### Chakra UI Version

1.6.4

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by takethefake** [comment]
Hej @fandy thanks for pointing this out! 

`--chakra-ring-inset` and the following props in `:root` are `defaultCssVars` which are defined in `packages/styled-system/src/create-theme-vars` and later used in:

- `packages/styled-system/src/config/ring.ts`
- `packages/styled-system/src/utils/templates.ts`
- `packages/styled-system/src/config/flexbox.ts`

I initially thought that we need to get access to the defined `cssVarPrefix` of the theme in those files to adjust it accordingly, but didn't found a way to achieve this.

`--chakra-ui-color-mode` is mainly used in `packages/color-mode` and I can probably see a way to migrate this to match `cssVarPrefix` with the result that the code would probably look a bit confusing with all the reads of the theme to get `cssVarPrefix` - which compared to the goal that the var has another name is hard to justify. 

What do others think? @segunadebayo @with-heart @TimKolberger

**Comment by TimKolberger** [comment]
All mentioned css vars are hardcoded and are part of the private API. 

https://github.com/chakra-ui/chakra-ui/blob/37aeec0091c0eec940cb2dc44495cd5ade5d227f/packages/styled-system/src/create-theme-vars/to-css-var.ts#L31-L40

E.g. the `*-ring-*` vars are altered when using the [`ring` prop](https://chakra-ui.com/changelog#17-05-2021).

Is there a specific use case you are trying to solve by renaming those vars @fandy?

**Comment by fandy** [comment]
> All mentioned css vars are hardcoded and are part of the private API. 
> 
> 
> 
> https://github.com/chakra-ui/chakra-ui/blob/37aeec0091c0eec940cb2dc44495cd5ade5d227f/packages/styled-system/src/create-theme-vars/to-css-var.ts#L31-L40
> 
> 
> 
> E.g. the `*-ring-*` vars are altered when using the [`ring` prop](https://chakra-ui.com/changelog#17-05-2021).
> 
> 
> 
> Is there a specific use case you are trying to solve by renaming those vars @fandy?
> 
> 

The inconsistency bothers me more than anything. If there's no special reason for the chakra prefix to be present, would it be better to make it customizable as well?

**Comment by TimKolberger** [comment]
The special reason is, that this change would introduce additional complexity to the code base, which is not necessary by my current understanding.

I am closing this issue as there are no known bugs or implications by this implementation detail.
