### ISSUE TITLE
[VisuallyHidden] TypeScript error for type prop

### ISSUE THREAD

**Issue by gopinav** [chakra-ui/chakra-ui#452]
**Describe the bug**
VisuallyHidden component throws type error for the prop 'type'

![image](https://user-images.githubusercontent.com/13146172/75456346-6c9ba300-59a0-11ea-9eb6-bfbb9f3048e9.png)

**Expected Behavior**
There should not be any typescript errors

**Comment by segunadebayo** [comment]
Hi @gopinav,

Thanks for this issue.

I'm going to close this issue because it's a duplicate comment from this issue #205. We're already working on this.
