### ISSUE TITLE
useOutsideClick not working as expected

### ISSUE THREAD

**Issue by oncet** [chakra-ui/chakra-ui#4523]
### Description

When I click outside an element using useOutsideClick, I expected the handler handler to be called but nothing happened instead.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-useoutsideclick-hook-j66d2

### Steps to reproduce

1. Create a blank page with a single element
2. Attach the useOutsideClick hook to that element
2. Click outside that element
3. If you clicked "below" the `<body>`, the event doesn't fire

### Chakra UI Version

1.6.5

### Browser

Google Chrome 92

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Seems like the `useOutsideClick` hook is checking that the click is "inside" the `<body>` instead of the `<html>`.

**Comment by gaspardip** [comment]
It works as expected in my opinion, `body` has `#root`'s `height`.

Clicking on the white area within the green borders has the expected behavior, clicking on the box on the bottom does too.

**Comment by oncet** [comment]
> It works as expected in my opinion, `body` has `#root`'s `height`.
> 
> Clicking on the white area within the green borders has the expected behavior, clicking on the box on the bottom does too.

But if you click below the green-bordered box it doesn't fire. Is this the expected behaviour?

**Comment by gaspardip** [comment]
It is. To get the behavior you want you need to change `html` and `body`'s `height`, see https://codesandbox.io/s/chakra-ui-useoutsideclick-hook-forked-ktx5z?file=/src/app.js
