### ISSUE TITLE
Support component prop generics with `forwardRef`

### ISSUE THREAD

**Issue by mayteio** [chakra-ui/chakra-ui#4528]
### Description

I'd like to be able to pass generic probs to components wrapped in `forwardRef`:

```ts
type GenericAcceptingProps<P = object> = {
 ...
}

function ForwardRefComponent<P = object>(
  props:GenericAcceptingProps<P>, 
  ref: React.ForwardedRef<HTMLDivElement>
){
  return ...
}

export const MyComponent = forwardRef(ForwardRefMyComponent)

// usage
<MyComponent<{otherProp?: string}> />
```

### Problem Statement/Justification

My use case is a `ItemsList` dropdown component that takes `items` and `onSelect` as a prop. The `items` prop could hold arbitrary data that I want to access in `onSelect`, though without allowing `ItemsList` to be generic, the `onChange={(item.genericProp) => setState(genericProp)}` throws a typescript error.

In general though, Component generic types can be very handy and are possible without the use of forwardRef.

### Proposed Solution or API

This is possible by taking advantage of [`higher order function type inference`](https://github.com/microsoft/TypeScript/pull/30215) (what a mouthful of a name). There's an example of this [for regular react `forwardRef`](https://fettblog.eu/typescript-react-generic-forward-refs/) where types are augmented to return a plain function type, which enables `forwardRef` to infer the return type to take props of the component it forwards to:

```ts
function forwardRef<T, P = {}>(
    render: (props: P, ref: React.Ref<T>) => React.ReactElement | null
  ): (props: P & React.RefAttributes<T>) => React.ReactElement | null
```

I've tried to have a crack at this myself but can't seem to get it to work:

```ts
declare module "@chakra-ui/react" {
  function forwardRef<Props extends object, Component extends As>(
    component: React.ForwardRefRenderFunction<
      any,
      RightJoinProps<PropsOf<Component>, Props> & {
        as?: As
      }
    >
  // return a generic function
  ): (
    props: Props &
      MergeWithAs<
        React.ComponentProps<Component>,
        React.ComponentProps<As>,
        Props,
        As
      > &
      React.RefAttributes<Component>
  ) => JSX.Element
}
```

When passing generics with this new augmented type like so;

```ts
<MyComponent<{otherProp?: string}> />
```

I get the following error;

```
Type '{ otherProp?: string; }' provides no match for the signature '(props: any, context?: any): ReactElement<any, any>'
```

While I was here, I also noticed that chakra `forwardRef` has it's generic arguments in a different order to react's forward ref, i.e. `Props, Component` vs, `T, P` - is that intentional?

```ts
function forwardRef<T, P = {}>(
    render: React.ForwardRefRenderFunction<T, P>
  ): React.ForwardRefExoticComponent<
    React.PropsWithoutRef<P> & React.RefAttributes<T>
  >
```

### Alternatives

Type the exported component with `as`

```ts
const ClickableList = React.forwardRef(ClickableListInner) as <T>(
  props: ClickableListProps<T> & { ref?: React.ForwardedRef<HTMLUListElement> }
) => ReturnType<typeof ClickableListInner>;
```

### Additional Information

https://fettblog.eu/typescript-react-generic-forward-refs/
https://github.com/microsoft/TypeScript/pull/30215

**Comment by segunadebayo** [comment]
Hi @mayteio,

To be honest, the `forwardRef` type is quite complex at the moment due to the support for the `as` prop and it sometimes makes the TypeScript compiler unhappy when you want to smartly compose it with a generic.

I'd recommend that you cast the type on your end instead to avoid breaking changes to other consumers of Chakra.

Thanks for understanding.

PS: We delved into this idea of JSX generics in the past but we think it's not an ergonomic approach and it was quite more complex than it's worth.

**Comment by segunadebayo** [comment]
Btw, I'm happy to reconsider this if you can come up with a solution that works and cover that with extensive tests in the `system` package.

**Comment by mayteio** [comment]
Thanks - I just typecast it. Much simpler than wrestling a complex
typescript type 👍
