### ISSUE TITLE
Make @chakra-ui/theme framework agnostic

### ISSUE THREAD

**Issue by simpletrontdip** [chakra-ui/chakra-ui#4530]
### Description

The **@chakra-ui/theme** provides the default theme for theming API. 
Most of the codes are not related to the UI framework. They can be used anywhere like Vue, Angular... 

### Problem Statement/Justification

For now, it requires `@chakra-ui/system` which is tightened to React, for:
- Types definition in `theme.type.ts` 
- A re-exported utils `keyframes` in `skeleton.ts`

### Proposed Solution or API

- For Type definitions, we can introduce new packages for types only, such as `@chakra-ui/system.types` to support the Typescript version, and this package can be framework agnostic as well (which may benefit downstream typescript packages).
- The `keyframes`:
   -  Can be fixed by import it from `@emotion/css`, this may not be ideal for  **React** version, which is recommended to use `@emotion/react`
   -  Or we **try to import it from both packages** `@emotion/css` or `@emotion/react` and raise a meaningful error on the missing case (most of the time, one of these packages has already been required by the component library).
   - Then we can safely re-export it in `@chakra/theme-tools` packages

### Additional Information

Although, this will require efforts to export a shared `system.types` packages and somehow, quite unintuitive for try to import `keyframes` from both emotion packages, but make `theme` package framework-agnostic will speed up the development of the downstream package (Vue, Angular version), unify the theming API and enlarge the Chakra ecosystem, which is really worth doing.

**Comment by TheThirdRace** [comment]
I think it's a great idea to make the theme agnostic. 

It would also be nice to get a modular theme. Right now, the theme is a big monolith and is not tree-shakeable.

To import a button, you get a huge amount of unnecessary JS from all the unused components, not to mention the huge amount of custom properties you're not even using. The color definitions amount to 10KB non-gzip...
