### ISSUE TITLE
Cannot create Input variants in custom theme

### ISSUE THREAD

**Issue by pixel-mattp** [chakra-ui/chakra-ui#4535]
### Description

Custom Input component styling and variants not being passed to the theme.  Cannot change the appearance of input fields.

### Link to Reproduction

https://codesandbox.io/s/condescending-flower-634fr

### Steps to reproduce

See Sandbox link.

Note that Button styling / custom variant works - but Input does not.

### Chakra UI Version

1.6.4

### Browser

Google Chrome 93

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by pixel-mattp** [comment]
Just figured out that Input has multiple parts ("field" and "addon").

**Comment by ricardo-passos** [comment]
@pixel-mattp how did you find out about these multiple parts? Is there documented somewhere? If not, do you have any advices on how to find out what components are "multi-part"?

**Comment by pixel-mattp** [comment]
@ricardo-passos - yes - I found the documentation here.  It's not 100% clear but hope it helps!

[Documentation HERE](https://chakra-ui.com/docs/theming/component-style#styling-multipart-components)

There is a helpful note too: 

"If you're looking for a list of parts of a multipart component you can check it by clicking on the "View theme source" button at the top of the documentation page for that certain component."

**Comment by ricardo-passos** [comment]
Thank you @pixel-mattp
