### ISSUE TITLE
Allow overriding default styles for Stat root element

### ISSUE THREAD

**Issue by oncet** [chakra-ui/chakra-ui#4537]
### Description

I'm trying to add a default style to the `Stat` component but it's not working. Seems you can only apply styles to the inner elements, as seen on the [source code](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/stat.ts#L24):

```javascript
const baseStyle = {
  label: baseStyleLabel,
  helpText: baseStyleHelpText,
  number: baseStyleNumber,
  icon: baseStyleIcon,
}
```

### Problem Statement/Justification

Seems reasonable to be able to add default styles to the `Stat` root element.

### Proposed Solution or API

Add a `baseStyle.root` option to alow styling the root element of the `Stat` component:

```javascript
const theme = extendTheme({
  components: {
    Stat: {
      baseStyle: {
        root: {
          border: "1px solid green"
        }
      }
    }
  }
});
```

### Alternatives

Creating a custom component that exports a `Stat` components with style props:

```javascript
export const MyStat = ({ children }) => (
  <Stat
    border="1px solid green"
  >
    {children}
  </Stat>
);
```

### Additional Information

View this [CodeSandbox ](https://codesandbox.io/s/chakra-ui-extendtheme-0fbic?file=/src/index.js) that illustrates the problem.

View [Stat component source code](https://github.com/chakra-ui/chakra-ui/blob/main/packages/stat/src/stat.tsx#L131).

**Comment by takethefake** [comment]
Hej @oncet thanks for pointing this out!

I've added a new `container`-part to the `Stat`-style config. This should give you the possibility to do what you want to do :)

**Comment by oncet** [comment]
> Hej @oncet thanks for pointing this out!
> 
> I've added a new `container`-part to the `Stat`-style config. This should give you the possibility to do what you want to do :)

That's awesome! Where can I find this latest changes?

**Comment by takethefake** [comment]
They need to be approved by one of the core maintainer and then we are good to go :)
