### ISSUE TITLE
[PseudoBox] TypeScript error for props

### ISSUE THREAD

**Issue by gopinav** [chakra-ui/chakra-ui#454]
**Describe the bug**
PseudoBox component flags typescript errors when passing props that are appropriate for the component passed into 'as' prop. For example, PseudoBox as button right now throws error for type and disabled prop. These props are valid for a button element.
![image](https://user-images.githubusercontent.com/13146172/75505804-43abfa00-5a02-11ea-891c-3dff7011b10b.png)

**Expected Behavior**
There should not be any TypeScript errors

**Comment by segunadebayo** [comment]
@gopinav, Thanks for this issue. We're aware of this and we created a central #205 issue to log all TypeScript related issues.

I'm going to close this and as it's a duplicate in #205. We'll definitely add support for this in the next release.
