### ISSUE TITLE
Timeline component

### ISSUE THREAD

**Issue by ameetmadan** [chakra-ui/chakra-ui#4543]
### Description

It would be great to get a Timeline component like in Material UI (https://material-ui.com/components/timeline)

### Problem Statement/Justification

It would be a nice addition to the components. I tried creating a new component myself but am struggling.

### Proposed Solution or API

https://material-ui.com/components/timeline/ as inspiration

**Comment by ashiskumar-1999** [comment]
Hey @segunadebayo, Is this component carrying a high priority to be built?

**Comment by segunadebayo** [comment]
@ashiskumar-1999 This component isn't currently on our priority list.

@ameetmadan Feel free to create this component in your project and even publish it on your end. Post it on the Discord channel to see if anyone can help you out. We're a kind and helpful community.

**Comment by ashiskumar-1999** [comment]
@segunadebayo , is there any issue having a good priority to contribute?

**Comment by zzezequiel** [comment]
There was a progress with the timeline component?
