### ISSUE TITLE
Chakra Netlify Storybook Version Should Be Updated

### ISSUE THREAD

**Issue by mtsmachado8** [chakra-ui/chakra-ui#4545]
### Description

Please take a look at #3925. It's closed but not fixed

### Link to Reproduction

Please take a look at #3925. It's closed but not fixed

### Steps to reproduce

Please take a look at #3925. It's closed but not fixed

### Chakra UI Version

latest

### Browser

GC

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

Relates to #3925, please reopen it. (Still an issue for me)

**Comment by TimKolberger** [comment]
The chakra ui storybook on Netlify is outdated. 
I just configured a CI deployment of our latest stories on the main branch to https://storybook.chakra-ui.com/

Feel free to close this issue if this works for you.

**Comment by mtsmachado8** [comment]
Nice work!!! it looks much better now @TimKolberger! Chackra-ui stories are updated right?
![image](https://user-images.githubusercontent.com/11022437/129460026-190f43bf-cd3f-49ed-8528-cdac3d5924b4.png)
I noticed it doesn't have controls enabled for your stories... iam making a Design System based on Material-Ui and Storybook for my company. I would really enjoy helping you with some storybook stuff.
I can help changing the storybook colors and logo so it can look more like Chackra-Ui Branding on this deploy: https://storybook.chakra-ui.com/
I did something similar to my company's storybook:
![image](https://user-images.githubusercontent.com/11022437/129460188-b1fcdf9a-112c-43e7-af3c-6b443d22b3dd.png)
I've also linked our Design System to Material-Ui storybook.

It looks like you're missing some good stuff from storybook 6.3.6, Automatic Generated Docs, measure tools, and some other things.
Would you like me to help you with that?
![image](https://user-images.githubusercontent.com/11022437/129460256-a882ee5a-9ad9-474a-97a8-24fae4b7d9a0.png)
Please let me know.
Thanks a lot for now

**Comment by mtsmachado8** [comment]
Iam closing this one for now. PR's comming as soon as i have time to help you guys! meanwhile please keep the nice job going! you're on fire with Chackra!!
