### ISSUE TITLE
Chakra CLI generate theme tokens cannot find modules declared in yarn workspaces

### ISSUE THREAD

**Issue by jasiene** [chakra-ui/chakra-ui#4550]
### Description

When I run chakra-cli tokens on a web app's theme file within a monorepo, chakra cli fails to find a referenced workspaces package within the same monorepo when generating typings. I don't know if this is an actual bug, or due to my monorepo setup. Please advise

### Link to Reproduction

https://codesandbox.io/s/chakra-cli-yarn-workspace-package-module-not-found-tkx2q

### Steps to reproduce

Setup a mono repo with two top level folders:

- apps
- packages

Within the packages folder, create a project which contains some new Chakra UI components and an extended theme. Within the apps folder create a Chakra UI project, and extend the theme in that project, including the extended theme from the packages folder. When you run chakra-cli tokens on the theme in your web app folder within the monorepo, chakra cli complains that it cannot find the packages theme (@monorepo/package)

Please check out the sandbox for a clearer example.

### Chakra UI Version

1.6.6

### Browser

Chrome 92

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by tony** [comment]
I think I may have bumped into the same issue.  Downgrading chakra/react + theme + theme-tools to the version before chakra-ui/react was 1.6.6 fixed it for me

**Comment by jasiene** [comment]
thanks tony, I'll have to give that a try

**Comment by tony** [comment]
@jasiene have you found a way to get this to work?

btw, can you actually compile? if so do your theme's styling not show? My situation is my theme properties aren't applying after this update

**Comment by jasiene** [comment]
Hey tony, it compiles just fine and I can generate typings within the app folder itself as long as I'm not referencing anything else in the with @monorepo/*

**Comment by jasiene** [comment]
hi @segunadebayo, it still is an issue with 1.6.10. What seems to work for now is referencing the relevant folder by going back to the root of the repo.

So from:
`import { theme as webComponentsTheme } from '@slrc-monorepo/package-web-components'`

To this:
`import { theme as webComponentsTheme } from '../../../../packages/web-components/src/theme'`

**Comment by igorwessel** [comment]
Hi guys!

I managed to debug to find out what was going on, basically tsconfig web-app was setting the baseUrl to the web-app src.
The output of the code that is responsible for generating the path was exactly like this
```js
 "rootFolder/apps/web-app/src/packages/web-components/src/"
```

When we create the path alias we use the absolute path that is generated from tsconfig, you can verify this by looking at this piece of code 
https://github.com/chakra-ui/chakra-ui/blob/05bf4288f2b138b9f75c070a92406d9d69f315db/tooling/cli/src/scripts/read-theme-file.worker.ts#L64

I believe it's not an error, it's just a small problem when configuring tsconfig.

**Comment by TimKolberger** [comment]
I think you are on the right track! 
Kindly open a PR if you find the time 😊

**Comment by igorwessel** [comment]
> I think you are on the right track! Kindly open a PR if you find the time 😊

I don't think I need to change anything currently the problem is in the configuration that the user made, basically the root tsconfig it's something like this:
```json
{
 "compilerOptions": {
  "baseUrl": ".",
  "paths": {
    "@monorepo/web-components/*": "packages/web-components/src/*"
  }
}
```

And web-app repo (apps/web-app) have tsconfig configured like this:
```json
{
 "extends": "../../tsconfig.json", // root tsconfig with path alias for package of monorepo
 "compilerOptions": {
  "baseUrl": "./src",
}
```

Currently we always get the settings referring to tsconfig.json from the working directory (in this case: apps/web-app/tsconfig.json) and because in the tsconfig of the working directory it replaced the baseUrl of the tsconfig root, we are unable to correctly register the path-alias.

The solution for him in specific would be to remove the paths of the tsconfig root:
```json
{
 "compilerOptions": {
  "baseUrl": ".",
  //"paths": {
   // "@monorepo/web-components/*": "packages/web-components/src/*"
 // }
}
```

And move to tsconfig from web-app repo 
```json
{
 "extends": "../../tsconfig.json", // root tsconfig with path alias for package of monorepo
 "compilerOptions": {
  "baseUrl": "./src",
  "paths": {
     "@monorepo/web-components/*": "../../../packages/web-components/src/*"
  }
}
```

Because of that I think it's not a problem, and trying to put things automatically like trying to check if the directory exists and if it doesn't exist try to load another configuration from root or from the extended tsconfig can lead to some strange behaviors.

**Comment by jasiene** [comment]
Hey Igor, thanks for this. When I get a chance I'll try it this way

**Comment by tony** [comment]
I ended up moving on from chakra-ui - not that the library wasn't great (it is!) - but on a monorepo w/ gatsby and a huge website, it was untenably difficult to diagnose why things would break between versions. you'd have to build your UX from the ground up to have a basic reproduction.

too many packages, libraries, and systems to trace why something breaks.

for smaller, non-monorepo projects i'd pick chakra-ui in a heartbeat.

**Comment by jasiene** [comment]
I ended up using https://nrwl.io/ as my monorepo tool instead and things seem to work really well and, generally, straight out the box
