### ISSUE TITLE
isDisabled for RadioGroup

### ISSUE THREAD

**Issue by andreidragu** [chakra-ui/chakra-ui#4551]
### Description

Just like isDisabled exists for CheckboxGroup, it would be nice to have this functionality also for RadioGroup 
I see that a similar request was made for CheckboxGroup  #3718 and I was wondering if we can have it also for RadioGroup

### Problem Statement/Justification

consistency reasons: if the feature exists on CheckboxGroup is should also exist on RadioGroup

### Proposed Solution or API

I suppose.. the same approach that was made on CheckboxGroup
[feat(checkbox-group): add isDisabled prop to checkbox group](https://github.com/chakra-ui/chakra-ui/pull/3778/commits/8e24bfff938478311027f091d47d105489ccb8e3)

**Comment by takethefake** [comment]
Hej @andreidragu thanks for pointing this out!

I've created a MR to recreate a similar behavior.
