### ISSUE TITLE
Application of the Tooltip to work with a functional component

### ISSUE THREAD

**Issue by shubhsk88** [chakra-ui/chakra-ui#4555]
### Subject

Tooltip

### Description

Currently, there is a note in the Tooltip documentation to work with functional components using `forwardRef` It would be easier for the audience to see an example as a workaround.

**Comment by shubhsk88** [comment]
I would be working on this PR and will be opening the PR soon, can you please assign this to me @TimKolberger?

**Comment by segunadebayo** [comment]
Hey @shubhsk88,

Here's a quick guide on how to do this:

```jsx
const Comp = forwardRef((props, ref) => <button ref={ref} {...props} />)

function Example(){
   return (
      <Tooltip>
            <Comp />
      </Tooltip>
   )
}
```

Feel free to add this to the docs in a PR.
