### ISSUE TITLE
wordWrap does not work

### ISSUE THREAD

**Issue by approached** [chakra-ui/chakra-ui#4556]
### Description

wordWrap => normal does not work

### Link to Reproduction

https://codesandbox.io/s/young-sun-vv0w7?file=/src/index.js

### Steps to reproduce

```js
        <Box w="212px" bg="tomato" d="block">
          {/* with chakra */}
          <Text fontSize="xl" wordWrap="normal">
            Akkreditierungsrichtlinien
          </Text>

          {/* hardcoded via style */}
          <Text
            fontSize="xl"
            style={{
              wordWrap: "normal"
            }}
          >
            Akkreditierungsrichtlinien
          </Text>
        </Box>
```

### Chakra UI Version

1.6.5

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by primos63** [comment]
I think there's some confusion on the props. There is no prop for `wordWrap` and sending it as a prop will only result in it being set as an attribute on the element. To do this in the example given, one would use the `sx` prop `sx={{ wordWrap: 'normal' }}`.

There is a property in `packages/styled-system/src/config/typography.ts` called `wordBreak` which is for the CSS word-break property.  It's default is true which is what is visible in the inspector developer tool on the page 
```css
*, *::before, ::after {
    border-color: var(--chakra-colors-gray-200);
    word-wrap: break-word;
}
```

There are two ways to achieve the desired effect. 
 - Use the `sx` on the element needing `word-wrap` set to `normal` 
 - In a custom theme define `"*, *::before, ::after"` or the appropriate tags such as `"div, p"` and set `word-wrap` to `normal`
 
I modified the [example](https://codesandbox.io/s/elegant-edison-mmpe6) to show each of the methods.
