### ISSUE TITLE
Menu won't close when click outside down

### ISSUE THREAD

**Issue by surielmx** [chakra-ui/chakra-ui#4557]
### Description

Menu won't close when click outside down

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-menu-wont-close-nn48m

### Steps to reproduce

***The codesandbox belongs to the user from issue [3969](https://github.com/chakra-ui/chakra-ui/issues/3969), but the bug I found works with that example**

### First bug
1. Go to https://codesandbox.io/s/chakra-ui-menu-wont-close-nn48m
2. Click on outside down of the menu list, then ESC key doesn't work
3. The menu isn't closed, either using ESC key

Only the examples of documentation works well.

### Chakra UI Version

1.6.5

### Browser

Google Chrome, Edge, last version

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

<h2 style="box-sizing: border-box; margin-bottom: 16px; margin-top: 24px; font-weight: 600; font-size: 1.5em; line-height: 1.25; border-bottom: 1px solid var(--color-border-secondary); padding-bottom: 0.3em; color: rgb(201, 209, 217); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><g-emoji class="g-emoji" alias="earth_africa" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f30d.png" style="box-sizing: border-box; font-family: &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 1em; font-weight: 400; line-height: 1; vertical-align: -0.075em; font-style: normal !important;">🌍</g-emoji><span> </span>System information</h2>

Software | Version(s)
-- | --
Chakra UI | 1.6.5
framer-motion | 4.1.17
Browser | Chrome Edge
Operating System | macOS

**Comment by primos63** [comment]
The height of the `Container` element only fits the action button as it's the only element in it. It does fill the width of the viewport, so clicking anywhere within the container triggers the menu to close. Clicking outside the viewport won't trigger the action. You get this result in the CodeSandbox example by triggering the menu then clicking inside the code editor. The menu does not close.

Setting the `Container` to have `height="100vh"` will give the desired result.

**Comment by surielmx** [comment]
Good point, thanks. I 'll close this issue
