### ISSUE TITLE
TagLabel gets clipped when the wrapping Tag has size "lg".

### ISSUE THREAD

**Issue by bncpr** [chakra-ui/chakra-ui#4565]
### Description

TagLabel gets clipped when the wrapping Tag has size "lg".

### Link to Reproduction

https://codesandbox.io/s/restless-butterfly-i85m9?file=/src/index.tsx

### Chakra UI Version

1.6.6

### Browser

Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

In my projects, I fix this by setting overflow='visible' on the TagLabel element.

**Comment by takethefake** [comment]
Hej @bncpr thanks for your report,

I couldn't verify your described behavior in the codesandbox.

![Screenshot 2021-08-15 214648](https://user-images.githubusercontent.com/3123354/129490669-65cd5a91-6963-4777-9b72-5aae9cca98ec.png)

Both `Tag`s look the same - independent from the `overflow` property. 

Could you share an Image to clarify the difference?

**Comment by bncpr** [comment]
In the image you added, at the bottom of the middle tag, the bottoms of the y, g, and j are clipped.

**Comment by takethefake** [comment]
fyi: This is reproducible with font-family: Segoe UI Semibold
