### ISSUE TITLE
File Upload Components

### ISSUE THREAD

**Issue by sumanthyedoti** [chakra-ui/chakra-ui#457]
File Upload Components like [Ant Design's](https://ant.design/components/upload)

**Comment by Martinnord** [comment]
This seems like a fun challenge. I'd like to try to get this working.

Are there any preferred libs to be used with this? The two I know are [rc-upload](https://www.npmjs.com/package/rc-upload) and [react-dropzone](https://www.npmjs.com/package/react-dropzone).

Cheers!

**Comment by Sm03leBr00t** [comment]
Hey did you tackle this one? @Martinnord

**Comment by with-heart** [comment]
This is a tough one to consider because a file upload component necessarily includes far more behavior than we have in our existing Chakra components. 

Chakra's focus is on providing base UI components that follow aria requirements that users can then theme to their liking and wrap with their own custom behavior. File upload components are often complex and require a lot of fine-tuning to meet the needs of the user. The underlying implementation and the design of these components varies widely between different sites.

For this reason, I don't think this would be a good component to include in the Chakra library. 

However, I would love to have a tutorial showing users how to create their own file upload component using existing Chakra components. If anyone would like to write that, I would happily accept a PR adding that to the guides section of our site. See [How to Create a Guide](https://next.chakra-ui.com/guides/how-to-create-a-guide) for information on how to go about that.

**Comment by Sm03leBr00t** [comment]
@with-heart I tried but I am so new I would need more assistance to pull that one off

**Comment by with-heart** [comment]
@Sm03leBr00t Join us on Discord! https://discord.com/invite/BEZ8VDy

**Comment by Martinnord** [comment]
To answer @Sm03leBr00t. A lot of things have come up in my personal life so I haven't had the time nor energy to jump on this. Sorry!

**Comment by Sm03leBr00t** [comment]
@Martinnord hey no worries, its not like I am your boss. I will try to finish my version and publish a tutorial in the docs.

**Comment by Martinnord** [comment]
Cool. Looking forward to see it :D

**Comment by karltaylor** [comment]
Hey @ArcticSpaceFox, @Martinnord, did you ever get round to finishing one of these? Would love to see it

**Comment by mike-fam** [comment]
Is there any update on this?

**Comment by Yhozen** [comment]
@mike-fam seems like they won't add it

**Comment by ArcticSpaceFox** [comment]
@karltaylor @mike-fam @Martinnord 
I have done it, it is a lil workaround and poropably not the best way, but let your inspiration flow!

```js
import { Input, FormControl, FormLabel, InputGroup, InputLeftElement, FormErrorMessage, Code, Icon } from "@chakra-ui/react";
import { FiFile } from "react-icons/fi";
import { useController } from "react-hook-form";
import { useRef } from "react";

const FileUpload = ({ name, placeholder, acceptedFileTypes, control, children, isRequired=false }) => {
  const inputRef = useRef();
  const {
    field: { ref, value, ...inputProps },
    meta: { invalid, isTouched, isDirty },
  } = useController({
    name,
    control,
    rules: { required: isRequired },
  });

  return (
    <FormControl isInvalid={invalid} isRequired>
      <FormLabel htmlFor="writeUpFile">{children}</FormLabel>
      <InputGroup>
        <InputLeftElement
          pointerEvents="none"
          children={<Icon as={FiFile} />}
        />
        <input type='file' accept={acceptedFileTypes} name={name} ref={inputRef} {...inputProps} inputRef={ref} style={{ display: 'none' }}></input>
        <Input
          placeholder={placeholder || "Your file ..."}
          onClick={() => inputRef.current.click()}
          value={value}
        />
      </InputGroup>
      <FormErrorMessage>
        {invalid}
      </FormErrorMessage>
    </FormControl>
  );
}

export default FileUpload;
```

**Comment by ArcticSpaceFox** [comment]
@raisoturu thanks mate, finally this issue has been solved. Thanks for the tip

**Comment by AlfieDarko** [comment]
> ```js
> ```js
> import { Input, FormControl, FormLabel, InputGroup, InputLeftElement, FormErrorMessage, Code, Icon } from "@chakra-ui/react";
> import { FiFile } from "react-icons/fi";
> import { useController } from "react-hook-form";
> import { useRef } from "react";
> 
> const FileUpload = ({ name, placeholder, acceptedFileTypes, control, children, isRequired=false }) => {
>   const inputRef = useRef();
>   const {
>     field: { ref, value, ...inputProps },
>     meta: { invalid, isTouched, isDirty },
>   } = useController({
>     name,
>     control,
>     rules: { required: isRequired },
>   });
> 
>   return (
>     <FormControl isInvalid={invalid} isRequired>
>       <FormLabel htmlFor="writeUpFile">{children}</FormLabel>
>       <InputGroup>
>         <InputLeftElement
>           pointerEvents="none"
>           children={<Icon as={FiFile} />}
>         />
>         <input type='file' accept={acceptedFileTypes} name={name} ref={inputRef} {...inputProps} inputRef={ref} style={{ display: 'none' }}></input>
>         <Input
>           placeholder={placeholder || "Your file ..."}
>           onClick={() => inputRef.current.click()}
>           value={value}
>         />
>       </InputGroup>
>       <FormErrorMessage>
>         {invalid}
>       </FormErrorMessage>
>     </FormControl>
>   );
> }
> 
> export default FileUpload;
> ```
> ```

Hey @raisturu do you mind re-adding that gist if you ever get a moment? Can imagine it would be super useful for everyone that ran into this issue!

Thanks!

**Comment by Sqvall** [comment]
I'm new to Chakra UI and first try react-hook-form, but created the simplest implementation.
it works for me.
Perhaps this will also be useful to someone.
https://gist.github.com/Sqvall/23043a12a7fabf0f055198cb6ec39531

**Comment by I-am-abdulazeez** [comment]
Any luck using formula?

**Comment by Markodimitrakis-Giannis** [comment]
> 
> 
> > ```js
> > ```js
> > import { Input, FormControl, FormLabel, InputGroup, InputLeftElement, FormErrorMessage, Code, Icon } from "@chakra-ui/react";
> > import { FiFile } from "react-icons/fi";
> > import { useController } from "react-hook-form";
> > import { useRef } from "react";
> > 
> > const FileUpload = ({ name, placeholder, acceptedFileTypes, control, children, isRequired=false }) => {
> >   const inputRef = useRef();
> >   const {
> >     field: { ref, value, ...inputProps },
> >     meta: { invalid, isTouched, isDirty },
> >   } = useController({
> >     name,
> >     control,
> >     rules: { required: isRequired },
> >   });
> > 
> >   return (
> >     <FormControl isInvalid={invalid} isRequired>
> >       <FormLabel htmlFor="writeUpFile">{children}</FormLabel>
> >       <InputGroup>
> >         <InputLeftElement
> >           pointerEvents="none"
> >           children={<Icon as={FiFile} />}
> >         />
> >         <input type='file' accept={acceptedFileTypes} name={name} ref={inputRef} {...inputProps} inputRef={ref} style={{ display: 'none' }}></input>
> >         <Input
> >           placeholder={placeholder || "Your file ..."}
> >           onClick={() => inputRef.current.click()}
> >           value={value}
> >         />
> >       </InputGroup>
> >       <FormErrorMessage>
> >         {invalid}
> >       </FormErrorMessage>
> >     </FormControl>
> >   );
> > }
> > 
> > export default FileUpload;
> > ```
> 
> Hey @svspicious turu do you mind re-adding that gist if you ever get a moment? Can imagine it would be super useful for everyone that ran into this issue!
> 
> Thanks!

Can you provide an example of how to use that ? I  am getting an error about control being Null

**Comment by 4ndv** [comment]
For anyone looking for a dropzone example, you can try mine: https://github.com/4ndv/magnets/blob/main/components/dropzone/index.js

**Comment by filliph** [comment]
> Can you provide an example of how to use that ? I am getting an error about control being Null

```js
import { Input, FormControl, FormLabel, InputGroup, InputLeftElement, FormErrorMessage, Icon } from "@chakra-ui/react";
import { FiFile } from "react-icons/fi";
import { useController } from "react-hook-form";
import { useRef } from "react";

export const FileUpload = ({ name, placeholder, acceptedFileTypes, control, children, isRequired = false }) => {
	const inputRef = useRef();
	const {
		field: { ref, onChange, value, ...inputProps },
		fieldState: { invalid, isTouched, isDirty },
	} = useController({
		name,
		control,
		rules: { required: isRequired },
	});

	return (
		<FormControl isInvalid={invalid} isRequired>
			<FormLabel htmlFor="writeUpFile">{children}</FormLabel>
			<InputGroup>
				<InputLeftElement
					pointerEvents="none">
					<Icon as={FiFile} />
				</InputLeftElement>
				<input type='file'
					   onChange={(e) => onChange(e.target.files[0])}
					   accept={acceptedFileTypes}
					   name={name}
					   ref={inputRef}
					   {...inputProps}
					   style={{display: 'none'}} />
				<Input
					placeholder={placeholder || "Your file ..."}
					onClick={() => inputRef.current.click()}
					// onChange={(e) => {}}
					readOnly={true}
					value={value && value.name || ''}
				/>
			</InputGroup>
			<FormErrorMessage>
				{invalid}
			</FormErrorMessage>
		</FormControl>
	);
}

FileUpload.defaultProps = {
	acceptedFileTypes: '',
	allowMultipleFiles: false,
};

export default FileUpload;
```

**Comment by yaacov-commenda** [comment]
The 'double input trick' stopped working for me in the latest chrome release, apparently they patched an issue related to "Insufficient policy enforcement in File System API".

Guess it's back to the drawing board.

https://chromereleases.googleblog.com/2022/06/stable-channel-update-for-desktop_21.html

**Comment by Byevenes** [comment]
> Any luck using formik

```typescript
import React, { ChangeEvent, ForwardedRef, useRef } from 'react'
import { EditIcon } from '@chakra-ui/icons'
import { Button, ButtonProps, InputGroup } from '@chakra-ui/react'
import { useField } from 'formik'

import { SUPPORTED_FORMATS } from 'utils/yup'

import FormControl, { BaseProps } from '../FormControl'

type FileUploadProps = {
  accept?: string
  multiple?: boolean
}

export type FileControlProps = BaseProps & FileUploadProps & { buttonProps?: ButtonProps };

export const FileControl: React.FC<FileControlProps> = React.forwardRef(
  (props: FileControlProps, ref: ForwardedRef<HTMLInputElement>) => {
    const { name, label, buttonProps, multiple = false, accept = SUPPORTED_FORMATS.join(' ,'), ...rest } = props
    const [{ onChange, ...field }, , { setValue }] = useField(name)
    const inputRef = useRef<HTMLInputElement | null>(null)

    const handleClick = () => {
      inputRef.current?.click()
    }

    const handleChange = (value: ChangeEvent<HTMLInputElement>) => {
      value.target.files && setValue(value.target.files?.[0])
    }

    return (
      <FormControl name={name} label={label} {...rest} {...ref}>
        <InputGroup onClick={handleClick}>
          <input
            onChange={handleChange}
            type='file'
            accept={accept}
            multiple={multiple}
            id={name}
            ref={inputRef}
            hidden />
          <Button w={'full'} variant={'secondary'} {...buttonProps} {...field} leftIcon={<EditIcon />} isLoading={false} paddingX={24}>
            {'Adjuntar'}
          </Button>
        </InputGroup>
      </FormControl>
    )
  }
)

export default FileControl
```

**Comment by oncet** [comment]
I managed to get a nice looking file uploader without hidding the actual input by using CSS's [`::file-selector-button`](https://developer.mozilla.org/en-US/docs/Web/CSS/::file-selector-button) to style the button of the file input.

For example:

```
<FormControl>
  <FormLabel>Files</FormLabel>
  <Input
    type="file"
    multiple
    sx={{
      "::file-selector-button": {
        height: 10,
        padding: 0,
        mr: 4,
        background: "none",
        border: "none",
        fontWeight: "bold",
      },
    }}
  />
  <FormHelperText>Attach any related documents.</FormHelperText>
</FormControl>
```

I used `height: 10` wich equals to `40px`, which seems to be the default height for Chakra's `FormControl`.

**Comment by blechatellier** [comment]
If someone is interested, this is another way to solve this one,

```tsx
export const DefaultTypes = () => {
  const styles = useMultiStyleConfig('Button', { variant: 'outline' });

  return (
        <Input
          type="file"
          sx={{
            '::file-selector-button': {
              border: 'none',
              outline: 'none',
              mr: 2,
              ...styles
            }
          }}
        />
  );
};
```

**Comment by ticketauth** [comment]
I made a  component by modifying @blechatellier 

`import { Image, Input, InputProps, useMultiStyleConfig } from "@chakra-ui/react";
import { ChangeEvent, useState } from "react";

export const ImageInput = (props: InputProps) => {
  const styles = useMultiStyleConfig("Button", { variant: "outline" });
  const [imgarray,setImgArray] = useState<string[]>();
  const handleChange = (e: ChangeEvent<HTMLInputElement>)=>{
    const filearray:string[] = [];
    if (e.target.files){
      Array.from(e.target.files).forEach(file => 
        filearray.push(URL.createObjectURL(file)))
    }
    setImgArray(filearray)
  }
  console.log(imgarray)
  return (
    <>
    <Input
      w='100%'
      border=''
      accept=".jpg, .jpeg, .png"
      type="file"
      sx={{
        "::file-selector-button": {
          ...styles,
        },
      }}
      
      onChange={handleChange}
    />
      {imgarray&&
      imgarray.map((img,key)=><Image key={key} src={img}/>)}
    </>
  );
};`

**Comment by Michael-indochat** [comment]
Is there no input file component in the current official latest file?

**Comment by mihir254** [comment]
```
const FileUploader = () => {
    const fileInputRef = useRef<HTMLInputElement | null>(null);
    const [selectedFile, setSelectedFile] = useState<File | null>(null);
    const [dataLength, setDataLength] = useState<number>(0);

    const handleButtonClick = () => {
        setSelectedFile(null);
        setDataLength(0);
        if (fileInputRef.current) {
            fileInputRef.current.value = '';
            fileInputRef.current.click();
        }
    };

    const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        const uploadedFile = event.target.files?.[0];
        if (uploadedFile) {
          // I am reading an excel sheet and storing the length
        }
    };
    return (
        <Flex direction="column" width="400px" height="300px" border="2px dashed gray" borderRadius={20} alignItems="center" justifyContent="center">
            <Flex flex={1} justifyContent={"center"} alignItems={"center"}>
                <Button shadow={"xl"} backgroundColor="gray.700" _hover={{ backgroundColor: 'gray.800' }} _active={{ backgroundColor: "gray.900" }} onClick={handleButtonClick}>
                    <Text color="white">UPLOAD FILE</Text>
                </Button>
            </Flex>
            {selectedFile ? <Flex height={"75px"} p={5} borderTop={"1px dashed silver"} w={"100%"} justifyContent={"space-between"} alignItems={"center"}>
                <Flex direction={"column"}>
                    <Heading fontSize={"24px"}>{selectedFile.name}</Heading>
                    <Heading size="sm" fontFamily={"mono"} color={"gray.500"}>THIS FILE WILL ADD {dataLength} DEVICE{dataLength === 1 ? '' : 'S'}</Heading>
                </Flex>
            </Flex> : <Flex height={"75px"} alignItems={"center"} p={5} borderTop={"1px dashed silver"} w={"100%"}>
                <Heading size={"sm"} fontFamily={"mono"} color={"gray.400"} textAlign={"center"}>THIS FEATURE CAN BE USED TO ADD MULTIPLE DEVICES AT ONCE</Heading>
                </Flex>
            }
            <input type="file" accept=".xlsx, .xls, .csv" onChange={handleFileChange} ref={fileInputRef} style={{ display: 'none' }} />
        </Flex>
    )
}

export default FileUploader;
```

**Comment by YuzeTT** [comment]
In fact, this can realize the upload function
```tsx
<label>
  <input type="file" onChange={handleImageChange} style={{ display: 'none' }}>
  </input>
  <Button as="span">Upload File</Button>
</label>
```

**Comment by suyashl13** [comment]
I tried to make it look better this way

Make sure you, `import { chakra } from '@chakra-ui/react'` at top
```

<FormControl isRequired>
            <FormLabel>Some File</FormLabel>
            <chakra.input
              type="file"
              w="100%"
              p="2"
              borderColor="grey.100"
              borderRadius="md"
              textColor="gray.500"
              borderWidth="1px"
              as={"input"}
              css={{
                "&::file-selector-button": {
                  alignItems: "center",
                  textAlign: "center",
                  display: "none",
                  backgroundColor: "blue.400",
                  _hover: {
                    backgroundColor: "blue.500",
                  },
                  _active: {
                    backgroundColor: "blue.600",
                  },
                },
              }}
              placeholder="Suyash"
            />
</FormControl>
```

**Comment by HardiB-Salih** [comment]
```js
import { AddIcon } from '@chakra-ui/icons';
import {
  Center,
  Image,
  ScaleFade,
  Text,
  VStack,
  chakra,
} from '@chakra-ui/react';
import React, { useState } from 'react';

/**
 * SingleUploadImage Component
 *
 * This component provides a user-friendly interface for uploading a single image.
 * It includes an option to preview the selected image and supports customization for size and rounding.
 *
 * @component
 *
 * @props {string} [size='100px'] - Specifies the dimensions of the upload area.
 * @props {string} [rounded='full'] - Defines the border-radius for the upload area, creating rounded corners.
 * @props {function} onUpdateFile (Required) - A callback function invoked when a new image is selected.
 *                                              It receives the selected image file as a parameter.
 *
 * @example
 * // Usage Example
 * <SingleUploadImage
 *   size="150px"
 *   rounded="md"
 *   onUpdateFile={handleFileUpdate}
 * />
 *
 * @example
 * // Import Example
 * import { SingleUploadImage } from './path-to-components';
 *
 * const YourComponent = () => {
 *   const handleFileUpdate = (file) => {
 *     // Handle the selected file (e.g., upload to server, update state)
 *     console.log('Selected File:', file);
 *   };
 *
 *   return (
 *     <SingleUploadImage
 *       size="150px"
 *       rounded="md"
 *       onUpdateFile={handleFileUpdate}
 *     />
 *   );
 * };
 */


const SingleUploadImage = ({
  size = '100px',
  rounded = 'full',
  onUpdateFile,
}) => {
  const [uploadedFile, setUploadedFile] = useState(null);

  const handleFileChange = event => {
    const file = event.target.files[0];
    setUploadedFile(file);
    onUpdateFile(file);
  };

  return (
    <Center
      w={size}
      h={size}
      as={chakra.label}
      htmlFor="file"
      bg="whiteAlpha.500"
      border="1px dashed gray"
      rounded={rounded}
      cursor="pointer"
      overflow="hidden"
      position="relative"
    >
      <Center
        position="absolute"
        w="100%"
        h="100%"
        _hover={{ bg: 'blackAlpha.600' }}
      >
        <VStack>
          <AddIcon />
          <Text>Upload</Text>
        </VStack>
      </Center>

      {uploadedFile && (
        <ScaleFade initialScale={0.9} in={uploadedFile !== null}>
          <Image
            w="100%"
            h={'100%'}
            src={URL.createObjectURL(uploadedFile)}
            alt="Uploaded"
            rounded={rounded}
          />
        </ScaleFade>
      )}

      <chakra.input
        required
        style={{ display: 'none' }}
        type="file"
        id="file"
        name="file"
        onChange={handleFileChange}
      />
    </Center>
  );
};

export default SingleUploadImage;
```
