### ISSUE TITLE
Typescript autocomplete does not work with extendTheme function

### ISSUE THREAD

**Issue by ishowta** [chakra-ui/chakra-ui#4573]
### Description

When I use extendTheme with Typescript, I expected to autocomplete theme, but it doesn't.

### Link to Reproduction

https://codesandbox.io/s/quizzical-mclean-zewes?file=/src/index.tsx

### Steps to reproduce

1. use extendTheme function with override exist theme object

### Chakra UI Version

1.6.6 (it works fine with 1.5.2)

### Browser

Chrome

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I think it's probably related to this commit https://github.com/chakra-ui/chakra-ui/commit/1d5e55272fe1475ce6fa0ed5bdccef4218885f77

This may be a problem in typescript. This is the small code that reproduces this problem in typescript: 
```typescript
type BaseTheme = {
  component?: string
}

declare function extendTheme<
  Extensions extends (BaseTheme & Record<string, unknown>)[]
>(...extensions: [...Extensions]): Extensions


extendTheme({

})
```
https://www.typescriptlang.org/play?ts=4.3.5#code/C4TwDgpgBAQghgZwgFQBYQLbQLxQN4BQUUAxgPYZhkB2E1wA-AFxQLABOAltQOYEC+BAgBMIJADZx20AGYBXaiWCcaUCAA9gdYWkwQAPESgBRTXQQrqCNWerDrACnhJdWKADIoAJTFl2w-TYuXgAaKAUAa2oyAHdqAD4ASgBtAF0CeIcAOhyNLStLBBZknKzTfIsaBFTElnLzQqECPO1XCAdCAUSCIA

**Comment by segunadebayo** [comment]
Please see my comment here: https://github.com/chakra-ui/chakra-ui/issues/4226#issuecomment-904630320

**Comment by jacobtkoch** [comment]
Hello! Curious if anyone knows if/when this might be addressed. Still not able to have autocomplete build for my custom theme.

**Comment by ishowta** [comment]
@jacobtkoch

> Chakra CLI finishes tokens just fine, but autocomplete does not activate for the custom themes.

Maybe the `tokens` command and the type of the `extendTheme` function exist independently. The reason why custom themes are not enabled is probably due to recent incompatible changes in chakra-ui. Updating all packages starting with `@chakra-ui` should work good.

**Comment by Dovalization** [comment]
Still waiting on a fix for this...
Chakra UI v 1.8.3 (latest) and the autocomplete for extendedTheme does not work.

**Comment by Inayat-C** [comment]
Still not working in 1.8.8.

**Comment by lishine** [comment]
```
"@chakra-ui/cli": "^1.9.0",
```
seems to work

**Comment by Inayat-C** [comment]
According to the [changelog](https://github.com/chakra-ui/chakra-ui/blob/next/tooling/cli/CHANGELOG.md), Chakra CLI 1.9.0 was a minor update addressing https://github.com/chakra-ui/chakra-ui/issues/5585.

It doesn't address the autocomplete issue being discussed in this thread.

**Comment by lishine** [comment]
@Inayat-C it would be great if your issue would be described as one line example, without going to codesandbox...

I am talking about autocomplete for extended theme for like zIndex='newname'

But autocomplete does not satisfy me anyway, because I need validation.
Maybe I will have to wrap chakra components with a fixing wrapper...

**Comment by cwylycode** [comment]
In case anyone needs autocomplete in typescript for their extendTheme object, without using chakra cli, there's a little 'hack' that mostly works.

```
import { extendTheme, theme, } from "@chakra-ui/react"

const base: typeof theme = {
  fonts: {
    body: `Poppins, sans-serif`,
    heading: 'Poppins, sans-serif',
    mono: 'mono, monospace'
  },
  components: {
    Button: {
      baseStyle: {
        color: 'green',
        background: 'yellow'
      },
    },
  },
  ...etc
}

export const themeBase = extendTheme(base)
```

There are two peculiarities with this approach: autocomplete isn't available for the values of the tokens (i.e. 'color and 'background' will autocomplete, but 'green' and 'yellow' won't - even though they are still valid) and there's a syntax error for the components object - however, it seems to not matter, as the app will still compile and run just fine (if anyone knows why this components error exists, I'd be grateful).

It works well enough for me inside vscode, since all I needed was the type auto-completion.

**Comment by ishowta** [comment]
I made a patch that tweaks the original type definition to allow autocompletion. (Extensions are not autocomplete).

```diff
diff --git a/node_modules/@chakra-ui/react/dist/declarations/src/extend-theme.d.ts b/node_modules/@chakra-ui/react/dist/declarations/src/extend-theme.d.ts
index 17a8c8e..a92afed 100644
--- a/node_modules/@chakra-ui/react/dist/declarations/src/extend-theme.d.ts
+++ b/node_modules/@chakra-ui/react/dist/declarations/src/extend-theme.d.ts
@@ -37,7 +37,14 @@ export declare type BaseThemeWithExtensions<BaseTheme extends ChakraTheme, Exten
  *   baseTheme // optional
  * )
  */
-export declare function extendTheme(...extensions: Array<Dict | ((theme: Dict) => Dict)>): Dict;
+export declare function extendTheme<
+BaseTheme extends ChakraTheme = Theme,
+ThemeOrThemeOverride extends (
+  | BaseTheme
+  | ThemeOverride<BaseTheme>
+) = ThemeOverride<BaseTheme>,
+ThemeExtensions extends ThemeExtension<ThemeOverride<BaseTheme>>[] = ThemeExtension<ThemeOverride<BaseTheme>>[]
+>(themeOrThemeOverride: ThemeOrThemeOverride, ...themeExtensions: ThemeExtensions): BaseThemeWithExtensions<BaseTheme, [ThemeOrThemeOverride, ...ThemeExtensions]>;
 export declare function mergeThemeOverride(...overrides: any[]): any;
 export {};
 //# sourceMappingURL=extend-theme.d.ts.map

```

**Comment by dalindev** [comment]
I got this problem too, I used the `npx chakra-cli tokens`, but still, autocomplete on vs code not working? If anyone gets this to work please share...

**Comment by tombohub** [comment]
What is that patch doing?

Version 2.2.3 does not have autocomplete for extendTheme

**Comment by tresorama** [comment]
> What is that patch doing?
> 
> Version 2.2.3 does not have autocomplete for extendTheme.
> 
> Do I have to use like this:
> 
> ```ts
> import {extendTheme, ThemeOverride} from '@chakra-ui/react'
> 
> const base: ThemeOverride = {
>   semanticTokens: { ... }
> }
> 
> const theme = extendTheme(base)
> ```
> 
> ?

This solution is clean IMO, and i'd like to use it, but it shows me this "ts error", and i dont know how to handle it.
<img width="630" alt="Schermata 2022-08-10 alle 18 10 36" src="https://user-images.githubusercontent.com/47954700/183959679-e8b19908-7cd9-4f03-bf6b-395f1949c82b.png">

<img width="672" alt="Schermata 2022-08-10 alle 18 07 46" src="https://user-images.githubusercontent.com/47954700/183958945-03c80f1a-1ed7-4ddc-9f8f-dae08a703e34.png">

<hr />

But if i change to this (ugliest IMO), ts agree.
```ts
const colors = {...};
const globalStyles = {...};

export const chakraCustomTheme = extendTheme({
  colors,
  textStyles,
  styles: {
    global: globalStyles,
  },
} as ThemeOverride);// <- Note Me !!!
```

**Comment by cwylycode** [comment]
@tresorama
Many thanks for the ThemeOverride solution, it works well for autocomplete.

Anyway, it seems that values still won't autocomplete, just the properties.

**Comment by tombohub** [comment]
@tresorama Did you try to use it without single `colors`, but full object like:

```typescript

const base: ThemeOverride = {
  colors: { /* ...  */}
}
```
?

**Comment by tresorama** [comment]
Yes i tried but with no difference.

Anyway i want to clarify what i mean by autocomplete.
IMO there are two "moment" when you need autocomplete.

1. When you are building your custom theme and need to know where to put colors, layerStyles, componentsOverrides, ecc...
2. When you are consuming theme tokens from a <Box> or <Flex> components in your views.

The code i posted works "good enough" for point 1.
For point 2, properties like "justifyContent" show css values in autocomplete, but properties like "color" and "bg" don't.
"color" and "bg" don't suggest any colors tokens at all, neither "red.XXX" or "green.XXX" coming from baseTheme of Chakra UI.
I think this problem will be resolved soon as stated in https://github.com/chakra-ui/chakra-ui/pull/6465

I'm not an expert of Typescript, so please correct me if i'm wrong.

**Comment by tombohub** [comment]
@tresorama isn't that why you need to run @chakra/cli to generate types for number 2?

**Comment by tresorama** [comment]
> @tresorama isn't that why you need to run @chakra/cli to generate types for number 2?

Yes.
I confirm that with
`@chakra-ui/react@2.2.8`
`@chakra-ui/cli@2.1.6`
after generate theme typing using
`npx chakra-cli tokens /path/to/theme.ts`,
Vs Code autocomplete suggests all theme tokens values.

**Comment by IRediTOTO** [comment]
I get this error to, newest version. What recommended ts version use with chakra UI ?

**Comment by kul-sudo** [comment]
Still a relevant issue.

**Comment by xxczaki** [comment]
Using the [`satisfies`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html) operator introduced in TypeScript 4.9 works perfectly for me:

```ts
const theme = extendTheme({
	// ...
} satisfies ThemeOverride);
```
