### ISSUE TITLE
Multiple segments for Progress Bar

### ISSUE THREAD

**Issue by TaylorFacen** [chakra-ui/chakra-ui#4574]
### Description

I would like to be able to create a progress bar similar to this.

![Multi-step progress bar](https://i.stack.imgur.com/3EJJz.jpg)

### Problem Statement/Justification

I'm building a budgeting app and need to show them how much of their budget they've spent and how much of their budget is allocated towards upcoming transactions. Having a multi-segment progress bar will allow me to display this information more easily. There's currently no other way to piece together other components to solve for this use case.

### Proposed Solution or API

Current single-color progress bar

```
<Progress colorScheme="green" value={20} />
```

Proposed multi-color progress bar that would produce the image presented above

```
<Progress colorScheme={["green", "yellow", "red"]} value={[50, 25, 10]} />
```

**Comment by takethefake** [comment]
Hej @TaylorFacen thanks for your feedback.

The `Progress`-Component is used to display the progress status for a task that takes a long time or consists of several steps.

Even though I understand your request and it possibly could make sense to have a view like this I think that this is a special case that should rather be implemented in your code than be moved into chakra.

To do something like this on your own best take a look at the source code of the [Progress](https://github.com/chakra-ui/chakra-ui/blob/main/packages/progress/src/progress.tsx)-component and adapt it to your use case.

**Comment by primos63** [comment]
The request was also posted on Discord. After reading this, I added another variant to my [CodeSandbox app](https://codesandbox.io/s/chakra-ui-theme-extension-w5u2n). 
`multiColor` which takes an object of percentages and colors and as the progress value increased the color changes to the one specified at the percentage breakpoint.
`multiSegment` which takes an object of colors and values, calculates the percentages given the `max` value and displays the entire progress bar (one-time). Closer to what is being requested.

```jsx
   <Progress
     variant="multiSegment"
     height={8}
     min={0}
     max={1000}
     values={{
       "red": 300,
       "blue": 150,
       "green": 50
     }}
   />
```
will produce the following progress bar
![image](https://user-images.githubusercontent.com/2768849/129604441-769631fc-6045-4c73-a09d-83a639a69abf.png)

Numbers on the bar will be problematic for the following reasons
  1.  When the percentage area is too small to fit the number, you'll have an overflow or truncation
  2.  Progress only works with a background image and as-is does not accept children that could hold the color and number. So placing a number at a specific location will be tricky at best.
  
While I see a use case for something like this, it seems more like a case for a charting tool than a progress bar.

**Comment by TaylorFacen** [comment]
@primos63 This worked perfectly for my use case! Thank you so much!
