### ISSUE TITLE
[Flex] Type does not include "visibility" prop

### ISSUE THREAD

**Issue by aaronmcadam** [chakra-ui/chakra-ui#459]
**Describe the bug**

I see the following TypeScript error:

```
Property 'visibility' does not exist on type 'IntrinsicAttributes & IFlex...
```

**Expected Behavior**

I expect to be able to use the `visibility` prop on anything.

**To Reproduce**

See this codesandbox: https://codesandbox.io/s/chakra-ts-starter-90t57

**Suggested solution(s)**

Add `visibility` to the props.

**Desktop (please complete the following information):**

 - OS: MacOS
 - Browser: Chrome
 - Version: 0.6.1

**Comment by tioluwani94** [comment]
Hi @aaronmcadam, thanks for catching this. It has been fixed and will be released with the next patch

**Comment by aaronmcadam** [comment]
Thanks @tioluwani94!
