### ISSUE TITLE
MacOS Safari: "An Unexpected Error Has Occurred" showing Button docs

### ISSUE THREAD

**Issue by garyrob** [chakra-ui/chakra-ui#4592]
### Description

I expect to see the page describing the button component. I see an error message

### Link to Reproduction

not relevant

### Steps to reproduce

1. Go to 'https://chakra-ui.com/docs/form/button'

2. Click on '...' 
No need to click on anything
3. Scroll down to '...'
No need to scroll

On Safari 14.1.2, with no extensions active and having cleared cookies and cache, I see the docs page start to render, but then suddenly it turns into a white screen with the text "An unexpected error has occurred" in the middle of the screen. I open the Javascript console and see the attached results

### Chakra UI Version

1.6.6

### Browser

Safari 14.1.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I opened the javascript console after the error appeared and this is what I see.

![Untitled 2](https://user-images.githubusercontent.com/1130621/129939926-418aabe1-00f9-4403-a032-92ae3fd49c58.jpg)

**Comment by takethefake** [comment]
Hej @garyrob thanks for your report!

Unfortunately, I couldn't reproduce this. Does the issue still persist on your side? Does it work in other Browsers? Do other sites work? Is there any further information about your environment that might be helpful for us?

I've tested it with:

- Safari Version 14.1.2 (16611.3.10.1.6) 
- macOS 11.5.2
- on a Macbook Pro 16" 2019

**Comment by segunadebayo** [comment]
Can't reproduce this as well. This is most likely caused by the `use-scrollspy` hook we use in the docs.

Safari 14.1 supports IntersectionObserver and it works on my end as well.

Let's re-open when we can reproduce.

**Comment by garyrob** [comment]
It looks like IntersectionObserver is settable in Experimental Features in Safari, where it defaults on being on. But I’d turned it off a long time ago in an attempt to debug some other problems. So, people who aren’t messing around with Experimental Features shouldn’t see the problem I saw.

**Comment by takethefake** [comment]
Hej @garyrob thanks for your reproduction notice!
