### ISSUE TITLE
Custom color does not reflect on withDefaultProps and other similar

### ISSUE THREAD

**Issue by renaldodev** [chakra-ui/chakra-ui#4593]
### Description

Changing the theme Button specifically the colorScheme with my custom color I hope the changes reflect on the component but it doesn't happen

### Link to Reproduction

https://codesandbox.io/s/morning-currying-1j7h0

### Steps to reproduce

# theme.ts file
```TypeScript
export const theme = extendTheme(
  {
    colors: {
      primary: base.colors.purple[400],
      secundary: "#EA80FC"
    }
  },
  withDefaultProps({
    defaultProps: {
      colorScheme: "secudary"
    },
    components: ["Button"]
  })
);
```
# exemple.tsx file
 
```TypeScript
   <Button">Click me</Button>
```
Even if you change the colorScheme attribute don't change
```TypeScript
   <Button colorScheme="secundary">Click me</Button>
```

### Chakra UI Version

1.6.6

### Browser

Edge

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### IMPORTANT: With the default colors works perfectly

**Comment by primos63** [comment]
It doesn't work because `colorScheme` expects a color name that is defined like the [Chakra colors](https://chakra-ui.com/docs/theming/theme#colors), with levels. Your theme should be:
```javascript
export const theme = extendTheme(
  {
    colors: {
      primary: base.colors.purple[400],
      secondary:  {
        "50": "#xxxxxx",
        "100": "#xxxxxx",
        "200": "#xxxxxx",
        "300": "#xxxxxx",
        "400": "#xxxxxx",
        "500": "#EA80FC"
        "600": "#xxxxxx",
        "700": "#xxxxxx",
        "800": "#xxxxxx",
        "900": "#xxxxx"
    }
  },
  ...
}
```
If you look at the default theme for a component like Button, you'll find that it uses the color levels to set the color and background of the component depending on the mode, dark or light.
```javascript
  // c is the colorScheme that is passed into the theme props
  const darkHoverBg = transparentize(`${c}.200`, 0.12)(theme)
  const darkActiveBg = transparentize(`${c}.200`, 0.24)(theme)

  return {
    color: mode(`${c}.600`, `${c}.200`)(props),
    bg: "transparent",
    _hover: {
      bg: mode(`${c}.50`, darkHoverBg)(props),
    },
    _active: {
      bg: mode(`${c}.100`, darkActiveBg)(props),
    },
  }
```

**Comment by segunadebayo** [comment]
Thanks for chiming in @primos63. That's correct.

**Comment by renaldodev** [comment]
thank you  @primos63, its helpfull
