### ISSUE TITLE
If Switch is disabled, then remove disabled.The focused style cannot be removed

### ISSUE THREAD

**Issue by linxianxi** [chakra-ui/chakra-ui#4596]
### Description

If Switch is disabled, then remove disabled.The focused style cannot be removed

### Link to Reproduction

https://codesandbox.io/s/eloquent-hellman-yh4lb

### Steps to reproduce

1. click switch and wait 2s
2. click anywhere,the focused style cannot be removed

### Chakra UI Version

lastest

### Browser

chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Nazeeh21** [comment]
Can I work on this issue?

**Comment by takethefake** [comment]
sure! i'll assign you.

**Comment by Nazeeh21** [comment]
I am unable to locate the file where I have to make the changes. May I get some idea like where the hover styling property is, in which I have to make the changes?
