### ISSUE TITLE
[Checkbox] [Radio] Make labels colorable

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#46]
Currently, labels of `Checkbox` and `Radio` components cannot be colored. I tried applying a `color` prop on the parent element, but it had no effect:

```tsx
const choice = 'Answer to a quiz question';

<Box color="red">
  <Radio key={choice} value={choice} color="green">
    {choice}
  </Radio>
</Box>
```

The text remained black, as inherited from the root `html` element's styles (caused by `<CSSReset />`).

I would like to propose that the `color` attribute should not have special behavior on form components, see [Bootstrap Forms](https://getbootstrap.com/docs/4.1/components/forms/#supported-elements). As for styling checkboxes or radio buttons, I think there should be a separate [`iconColor` prop](https://github.com/chakra-ui/chakra-ui/blob/5b6c957a2f2042349a44fddfe9679074821a6c2e/packages/chakra-ui/src/Checkbox/index.js#L72) for altering their appearance, which could be used in combination with `PseudoBox` props to style states other than checked.

**Comment by segunadebayo** [comment]
Hi @kripod,

Thanks for this observation. The children prop of `Radio` or `Checkbox` is optional.  If you need to gain control over the styling of the labels, ignore it and compose the component this way.

```jsx
<Flex as="label">
  <Radio key={choice} value={choice} color="green" />
  <Box ml={2} color="red.500">{choice}</Box>
</Flex>
```

Note that applying the `color` prop for primitives other than `Radio` or `Checkbox` should be accessed with the dot notation. The `Box` you have should have a prop of `red.X`, where `X` is 50-900.

I've noted your feedback on the `color` though. I'll test it out.

Thanks again.

**Comment by kripod** [comment]
I appreciate your detailed feedback. However, the outlined approach comes with a lot of boilerplate and might be hard to remember or reason about, especially for beginners. I would still suggest using a separate `iconColor` prop, which could be modified on its own, especially with #49 taken into consideration:

```tsx
<Radio
  value="foo"
  color="red"
  iconColor="black"
  _checked={{ iconColor: 'green' }}
>
  This piece of text should be red, but the icon should be
  black by default or green when hovered
</Radio>
```

**Comment by segunadebayo** [comment]
I completely understand your perspective @kripod . Thanks for the feedback, I'll try it out.

**Comment by segunadebayo** [comment]
Hi @kripod ,

I'm closing to this issue because there are other ways to solve this.

Option #1 (recommended)

```jsx
const choice = 'Answer to a quiz question';

  <Radio key={choice} value={choice} color="green">
    <Box color="red.500">{choice}</Box>
  </Radio>
```

Option #2

```jsx
<Flex as="label">
  <Radio key={choice} value={choice} color="green" />
  <Box ml={2} color="red.500">{choice}</Box>
</Flex>

```

We've looked into this suggestion:

```jsx
<Radio
  value="foo"
  color="red"
  iconColor="black"
  _checked={{ iconColor: 'green' }}
>
  This piece of text should be red, but the icon should be
  black by default or green when hovered
</Radio>
```

We think might not be possible at the moment because the `iconColor` isn't a style prop and there's more we need to do to support that. 

Kindly use the suggested options above.

Thanks again.
