### ISSUE TITLE
This project has been added to the react-ui-roundup

### ISSUE THREAD

**Issue by dimitropoulos** [chakra-ui/chakra-ui#461]
Hi!

I am making this issue just to let you know that I've included your amazing project in the [react-ui-roundup](https://github.com/dimitropoulos/react-ui-roundup).

For more information see https://github.com/dimitropoulos/react-ui-roundup/issues/2.

Please feel free to close this issue at will - I just wanted to let you know :smile:.

Thanks!

**Comment by segunadebayo** [comment]
Amazing! Thank you @dimitropoulos 💖
