### ISSUE TITLE
isChecked on MenuItemOption does nothing

### ISSUE THREAD

**Issue by metchegarayhw** [chakra-ui/chakra-ui#4612]
### Description

When I use isChecked prop in MenuItemOption component nothing happens

### Link to Reproduction

https://codesandbox.io/s/reverent-taussig-qx90e?file=/src/App.js

### Steps to reproduce

Simply open MenuItem, "Choice" should be checked
Am I missing something here ?

### Chakra UI Version

1.6.6

### Browser

Google Chrome 93

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by pedrorvelloso** [comment]
I don't know if this is a doc problem but `isChecked` will check the item only when you're not using `MenuOptionGroup`.

If you want to be checked by default you should use `defaultValue` prop within `MenuOptionGroup` or `value` prop.

```js
<Menu closeOnSelect={false}>
    <MenuButton as={Button}>MenuItem</MenuButton>
    <MenuList>
        <MenuOptionGroup title="Test" type="checkbox" defaultValue="Choice">
            <MenuItemOption value="Choice">Choice</MenuItemOption>
        </MenuOptionGroup>
    </MenuList>
</Menu>
```

**Comment by metchegarayhw** [comment]
> I don't know if this is a doc problem but `isChecked` will check the item only when you're not using `MenuOptionGroup`.
> 
> If you want to be checked by default you should use `defaultValue` prop within `MenuOptionGroup` or `value` prop.
> 
> ```js
> <Menu closeOnSelect={false}>
>     <MenuButton as={Button}>MenuItem</MenuButton>
>     <MenuList>
>         <MenuOptionGroup title="Test" type="checkbox" defaultValue="Choice">
>             <MenuItemOption value="Choice">Choice</MenuItemOption>
>         </MenuOptionGroup>
>     </MenuList>
> </Menu>
> ```

I don't want a default check, I want to have MenuOptionGroup checked with a variable
I guess I won't use this then

**Comment by segunadebayo** [comment]
Hey @metchegarayhw,

You should pass the checked or default checked values to `MenuOptionGroup`, not the `MenuItemOption`. That way you can use either `value` or `defaultValue` to drive which options get checked or not.

To check all items within the `MenuOptionGroup`, you'll need to set the value or default value to be an array of values.

`<MenuOptionGroup value={["Choice-1", "Choice-2"]} onChange={...}  />`

Happy to update the docs to reflect this.
