### ISSUE TITLE
Bug when trying to opening modal

### ISSUE THREAD

**Issue by Marcioshub** [chakra-ui/chakra-ui#4633]
### Description

When i try open a modal dialog it will clear everything on the screen.

### Link to Reproduction

https://codesandbox.io/s/u7bnx

### Steps to reproduce

1. Create modal button from the docs.
2. Click on modal button
3. Screen goes white (on codesandbox there will be an error).

### Chakra UI Version

1.6.6

### Browser

Chrome, Safari, Firefox

### Operating System

- [X] macOS
- [ ] Windows
- [X] Linux

### Additional Information

On codesandbox to will show the following error message:
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by tydusgg** [comment]
I had the same issue. You should delete the Lorem component from your jsx.

**Comment by Marcioshub** [comment]
> I had the same issue. You should delete the Lorem component from your jsx.

Thanks tydusgg.
