### ISSUE TITLE
Menu in AccordionButton

### ISSUE THREAD

**Issue by tydusgg** [chakra-ui/chakra-ui#4635]
### Description

When I click on MenuButton, click event triggers in AccordionButton with MenuButton

### Link to Reproduction

https://codesandbox.io/s/relaxed-black-up6sl

### Steps to reproduce

1. Go to 'App.js'
2. Click on 'Click me' button
3. See behavior

### Chakra UI Version

1.6.6

### Browser

Google Chrome 92

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Probably I`m doing something wrong because I`m a newbie with Chakra and component libraries, so I'm glad to get any help.

**Comment by takethefake** [comment]
Hej @tydusgg thanks for reaching out!

Could you describe your desired behavior?

**Comment by tydusgg** [comment]
> Hej @tydusgg thanks for reaching out!
> 
> Could you describe your desired behavior?

I want to open Accordion when I click on AccordionButton and open Menu when I click on MenuButton, but not open Accordion when I click on MenuButton. Is there any way to write a custom onClick event or something like that?

**Comment by takethefake** [comment]
Alright, the main problem is that your `MenuButton` is nested inside the `AccordionButton` this way the `onClick` handler propagates from the `MenuButton` to the `AccordionButton` and therefore triggers both actions. 

A possible solution could look like this: https://codesandbox.io/s/goofy-hopper-6j62k?file=/src/index.js

**Comment by tydusgg** [comment]
> Alright, the main problem is that your `MenuButton` is nested inside the `AccordionButton` this way the `onClick` handler propagates from the `MenuButton` to the `AccordionButton` and therefore triggers both actions.
> 
> A possible solution could look like this: https://codesandbox.io/s/goofy-hopper-6j62k?file=/src/index.js

Yes, this is what I need, thank you!
