### ISSUE TITLE
Chakra UI errors due to `ModuleNotFoundError`s with Next.js and Yarn PnP

### ISSUE THREAD

**Issue by misterjoshua** [chakra-ui/chakra-ui#4640]
### Description

When I followed the "Getting Started" instructions to add Chakra UI to a Next.js project with Yarn PnP, I expected the build to succeed, but the build fails with a `ModuleNotFoundError`.

### Link to Reproduction

https://github.com/misterjoshua/nextjs-chakra-ui-bug

### Steps to reproduce

```
yarn create next-app my-chakra-app
cd my-chakra-app
yarn set version berry
yarn config set nodeLinker pnp
yarn add @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^4
yarn install
```

Copy/paste the example from https://chakra-ui.com/docs/getting-started#nextjs into `pages/_app.js`

```
yarn build
```

Get this error:

```
info  - Checking validity of types
info  - Creating an optimized production build
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve '@chakra-ui/react' in 'E:\p\my-chakra-app\pages'


> Build error occurred
Error: > Build failed because of webpack errors
    at E:\p\my-chakra-app\.yarn\__virtual__\next-virtual-884fbe2c0d\0\cache\next-npm-11.1.0-ba26540f3a-b74dfd738b.zip\node_modules\next\dist\build\index.js:390:19
    at async Span.traceAsyncFn (E:\p\my-chakra-app\.yarn\__virtual__\next-virtual-884fbe2c0d\0\cache\next-npm-11.1.0-ba26540f3a-b74dfd738b.zip\node_modules\next\dist\telemetry\trace\trace.js:60:20)
```

### Chakra UI Version

1.6.7

### Browser

N/A

### Operating System

- [ ] macOS
- [X] Windows
- [X] Linux

### Additional Information

The bug reproducer uses next 11.1.0.

I was able to reproduce the problem in these environments:

**Windows Environment**
Windows 10 21H1
Node 14.15.4
Yarn 3.0.1

**Linux Environment 1**
Ubuntu 21.04
Node 14.16.1 (via nvm)
Yarn 3.0.1

**Linux Environment 2**
Ubuntu 21.04
Node 16.8.0 (via nvm)
Yarn 3.0.1

**Comment by markodvornik** [comment]
Possibly related to https://github.com/chakra-ui/chakra-ui/issues/4683

**Comment by markodvornik** [comment]
Downgrade that worked for me:

```sh
yarn add -D typescript@4.3.2 @chakra-ui/portal @chakra-ui/react-env @chakra-ui/provider
yarn add @chakra-ui/theme-tools@1.1.9 @chakra-ui/system@1.7.2 @chakra-ui/react@1.6.6
```

**Comment by segunadebayo** [comment]
I just pushed a fix for this
