### ISSUE TITLE
[Checkbox] can't make checkbox truly unfocusable

### ISSUE THREAD

**Issue by takethefake** [chakra-ui/chakra-ui#4641]
### Description

When providing the `isFocusable`-prop to a checkbox it's still tabbable via keyboard and the `::focus` styles are applied. Only in combination with `isDisabled` the checkbox is not focusable.

### Link to Reproduction

Not needed

### Chakra UI Version

1.6.6

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

Suggested Change:

if the user adds `tabIndex` to the `Checkbox`-component pass the tab index to `getInputProps` to truly make a checkbox not focusable, otherwise, only the label isn't focusable. 

Alternative: A more invasive way would be to set `tabIndex=-1` inside `Checkbox` if `isFocusable===true` but this might be a breaking change for some users.

**Comment by segunadebayo** [comment]
What's the use-case for this?

I'm trying to wrap my head around why this is needed compared to using `isReadonly` or `isDisabled`.
