### ISSUE TITLE
Image should ignore fallback behavior when no fallback is set

### ISSUE THREAD

**Issue by JulioC** [chakra-ui/chakra-ui#4648]
### Description

When using Image component and not setting fallback or fallbackSrc values, it renders a non-existing <img> for a single frame. This causes a flash when you remount a component instance with another, even if the `src` is the same. Image component should ignoreFallback automatically if no fallback is set

### Link to Reproduction

https://codesandbox.io/s/ecstatic-tu-c6ztk?file=/src/index.js

### Steps to reproduce

Create an `<Image />` instance, setting only its `src` prop and cause it to remount.

On reproduction link, click on the "Remount!" buttons a few times to see the behavior in both cases. In my opinion they shouldn't differ at all

### Chakra UI Version

1.6.7

### Browser

Chrome, Firefox

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by takethefake** [comment]
Hej @JulioC thanks for pointing this out!

I've created a PR to introduce the suggested changes.
