### ISSUE TITLE
`ChakraProviderProps` export removed from `@chakra-ui/react` in 1.6.7

### ISSUE THREAD

**Issue by South-Paw** [chakra-ui/chakra-ui#4649]
### Description

When I updated to 1.6.7, `ChakraProviderProps` is not exported from `@chakra-ui/react` anymore

### Steps to reproduce

1. `import { ChakraProviderProps } from '@chakra-ui/react';` in a ts file
2. `Module '"@chakra-ui/react"' has no exported member 'ChakraProviderProps'.`

### Chakra UI Version

1.6.7

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

`ChakraProviderProps ` was exported in 1.6.6, but has been (I assume) accidentally removed in 1.6.7

**Comment by VigneshMurugan** [comment]
I think we can import it using `import { ChakraProviderProps } from '@chakra-ui/provider`

CC: @South-Paw

**Comment by South-Paw** [comment]
Yes, that's what I've done to work around it in the mean time however, `ChakraProvider` is still exported from `@chakra-ui/react` but not `ChakraProviderProps` which doesn't make sense.

The API change was also released as a minor version so a bunch of my components just started throwing errors - not ideal for a minor release which should have no breaking changes 😆

It's also not mentioned in the changelog, so I assume its just a minor oversight with 1.6.7 😄

**Comment by segunadebayo** [comment]
Yes, it's a minor oversight @South-Paw. Thanks for pointing that out.

I'll resolve this shortly.

**Comment by segunadebayo** [comment]
I just pushed a fix for it. We'll release an update shortly
