### ISSUE TITLE
[Alert] Typo in documentation

### ISSUE THREAD

**Issue by wale-bant** [chakra-ui/chakra-ui#465]
**Describe the bug**

There is a typo in the Status alert (warning). It says : "Seems your account is about expire, upgrade now"

**Expected Behavior**

The text should be: "Seems your account is about to expire, upgrade now"
The "to" is omitted.

**To Reproduce**
- Use this template:
- List the steps to reproduce the behavior:
1. Go to 'Alert'
3. Scroll down to 'Status'
4. See the warning message

**Suggested solution(s)**

Accept my incoming PR

**Desktop (please complete the following information):**

**Additional context**

**Comment by nainardev** [comment]
Fixed!
