### ISSUE TITLE
Add lazy loading option in Image component

### ISSUE THREAD

**Issue by jatinhemnani01** [chakra-ui/chakra-ui#4655]
### Description

It will be very useful to have images lazily load with a option in Image component. Like next/image which works great

### Problem Statement/Justification

It will be very useful to have images lazily load with a option in Image component. Like next/image which works great

### Proposed Solution or API

using any lazy loading package?

### Alternatives

next/image component in Next JS

**Comment by king-glitch** [comment]
I belive there's a loading option in Chakra-Ui Image component. `loading="lazy"`

**Comment by RedWilly** [comment]
i think the best option is to use the skeleton https://chakra-ui.com/docs/components/skeleton
