### ISSUE TITLE
Feature Request: OnClick Prop to useToast

### ISSUE THREAD

**Issue by danbunkr** [chakra-ui/chakra-ui#4658]
### Description

- The useToast / toast API is great for displaying information to a user but lacks the ability for the user to act on that information via an onClick action. For example in our application a common use case is to pop a toast when a user moves a file from one folder to another via a dropdown / select folder. The toast alerts them that we moved the file successfully into {folderName}. It would be great if chakra provided a way to click that toast and then in our use case route the user to the folder the file was moved into.

### Problem Statement/Justification

There are current workarounds to this such as adding event listeners at the document level or using the render prop function of the toast. But in my opinion these are not necessary for such a simple task. From the render prop perspective it seems tedious to have to re-implement all the styles and logic toast already provided to you in useToast just to add an onClick function and is something that could be easily done in the root API.

### Proposed Solution or API

My proposed API would be something similar to:

```
const onToastClick = useCallback(() => {
   /// Implement toast click logic here
  }, []);


  toast({
          id: '123'
          description: 'test'
          status: 'success',
          duration: 2000,
          isClosable: true,
          onToastClick
        });
```

### Alternatives

* Document listeners at the level
* custom hook that listens for a click on a 'chakra-alert' class
* Implementing the toast via render prop and <Alert> component

**Comment by danbunkr** [comment]
BTW @takethefake @segunadebayo. I do not mind opening a PR / doing the work required just want to make sure the API / acceptance criteria has been approved before doing the work

**Comment by takethefake** [comment]
@danbunkr thanks for pointing this out!

IMO this sounds like a good idea, if you don't mind you could start working on this even though I can't you give a 100% go since I'm quite new in supporting chakra as well and @segunadebayo might has a different opinion on this.

**Comment by segunadebayo** [comment]
Thanks for chiming in @takethefake.

While this sounds like a good idea, I think it's a perfect use-case for the "render" function in `useToast`.
https://chakra-ui.com/docs/feedback/toast#custom-component

When you define your own component in there, you can pass the `onClick` handler you need to get the component working correctly. To make it easier, you can use the `Alert` component in the toast render function which is what we do as well.

Thanks for understanding
