### ISSUE TITLE
Broken `@emotion` dependencies

### ISSUE THREAD

**Issue by mtrzesniowski** [chakra-ui/chakra-ui#4664]
### Description

`Module not found: Can't resolve '@emotion/styled-base'` error shows up on the compilation

### Link to Reproduction

--

### Steps to reproduce

I've added ChakraUI to my project and the above error shows up while compiling

### Chakra UI Version

1.6.7

### Browser

--

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Full error's output:
```
yarn start
Failed to compile.

./node_modules/@chakra-ui/system/dist/esm/system.js
Module not found: Can't resolve '@emotion/styled-base' in '<project_path>/node_modules/@chakra-ui/system/dist/esm'
```

Chakra's and Emotion's dependencies:
```
    "@chakra-ui/icons": "^1.0.15",
    "@chakra-ui/react": "^1.6.7",
    "@chakra-ui/system": "^1.7.3",
    "@emotion/react": "^11",
    "@emotion/styled": "^11",
```

Additional `yarn why` for `@emotion/styled`:
```
yarn why @emotion/styled
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "@emotion/styled"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@emotion/styled@11.3.0"
info Has been hoisted to "@emotion/styled"
info Reasons this module exists
   - Specified in "dependencies"
   - Hoisted from "@companyName#shared#@emotion#styled"
info Disk size without dependencies: "596KB"
info Disk size with unique dependencies: "5.14MB"
info Disk size with transitive dependencies: "11.93MB"
info Number of shared dependencies: 45
✨  Done in 1.95s.
```

**Comment by takethefake** [comment]
Hej @mtrzesniowski thanks for reaching out!

Could you provide us with a codesandbox/ example repo where this failure occurs? 

The provided deps should work with each other, so there shouldn't be any issue.

**Comment by Andarist** [comment]
Chakra is using Emotion 11 and `@emotion/styled-base` was only available in Emotion 10. Therefore something is broken with the dependency graph - most likely because you have different versions of Emotion as dependencies of your dependencies and somehow they have clashed.

As to `yarn why` - it would be helpful if you would include that info for `@emotion/styled-base`

**Comment by segunadebayo** [comment]
Closing this since there's no response from the author.

Happy to re-open when we can reproduce this.
