### ISSUE TITLE
Adding 'isChecked' to MenuItemOption doesn't work

### ISSUE THREAD

**Issue by chuckstock** [chakra-ui/chakra-ui#4666]
### Description

MenuItemOption does not use the value of the isChecked prop to render the checkbox properly.

### Link to Reproduction

https://chakra-ui.com/docs/overlay/menu#menuitemoption-props

### Steps to reproduce

1. Go to preview example
2. Add isChecked prop to any MenuItemOption
3. See that the check is not shown on the MenuItemOption

### Chakra UI Version

1.6.6

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by takethefake** [comment]
Hej @chuckstock thanks for reporting this!

I've created a PR that should fix this misbehavior.

**Comment by segunadebayo** [comment]
Hi @chuckstock,

You need to use the `MenuOptionGroup` to explicitly check or uncheck `MenuOptionItem`s. For uniform API design, I'd discourage the use-case of adding the `isChecked` explicitly.

Happy to provide an example if need it.

**Comment by takethefake** [comment]
@segunadebayo in this case i would consider removing the `isChecked`-prop from `MenuOptionItem`?
