### ISSUE TITLE
Style inconsistency in a theme created with Extend Theme, some styles are not applied

### ISSUE THREAD

**Issue by b-novikov-ipersonality** [chakra-ui/chakra-ui#4672]
### Description

When I create a `baseStyle` overright for a component and add it to my theme, I expect it to be applied to all component variants. But instead, `baseStyle` is not being applied (or being overriden by default component styles, I'm not sure).

### Link to Reproduction

https://codesandbox.io/s/compassionate-fire-ulrv7?file=/src/theme.js

### Steps to reproduce

1. Open the link, file `theme.ts`
2. In `Button` variable change `px`, `height` and `border` properties
3. See the result - `px` and `height` are not being applied, as well as `border-width` of 2px to `outline`. 

### Chakra UI Version

1.6.7

### Browser

Chromium Version 92.0.4515.159

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

When inspecting an element for which you write `baseStyle`, in the devtools style inspector there isn't even a trace of styles I wrote. If it's how it should be, then probably my styles are being overriden by default variant's styles. 

When apply each individual style separately (for example, `pl` and `pr` instead of `px`), styles are applied.

**Comment by tony** [comment]
@b-novikov-ipersonality do you also have issues where colors like `blue.700` aren't rendered to chakra's css variables?

**Comment by tony** [comment]
Also did this happen after an upgrade?  

If you do these dependencies, does it still happen?

```
    "@chakra-ui/react": "1.6.5",                                                                                                                                                                                                                                                     
    "@chakra-ui/theme": "1.9.2",  
```

**Comment by takethefake** [comment]
Hej @b-novikov-ipersonality thanks for reaching out!

You were right with one of your assumptions. `baseStyle` is being overwritten by variants. To ensure that a certain style is on a specific variant you have to style accordingly.

**Comment by b-novikov-ipersonality** [comment]
@takethefake so even if I don't provide custom variants, baseStyles will be overriden by default variant's style?

**Comment by takethefake** [comment]
yes that's right. `baseStyle` can be understood as a base style for the general component before applying variants
