### ISSUE TITLE
Sizes doesn't seem to get overridden for IconButton and possibly others.

### ISSUE THREAD

**Issue by RIP21** [chakra-ui/chakra-ui#4677]
### Description

When I override certain size properties in the component's sizes theme object, I expect it to work as expected.

### Link to Reproduction

https://codesandbox.io/s/jovial-haslett-cgm2c?file=/src/index.tsx

### Steps to reproduce

The issue is that `sizes` are not getting applied as expected. Applying styles directly to `sx` of the component with the same values as I have in custom `sizes` works as expected changing `h` and `minW` accordingly.

### Chakra UI Version

1.6.7

### Browser

Unrelated to browser

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by RIP21** [comment]
@takethefake  Here we go.

**Comment by RIP21** [comment]
@takethefake sorted...
IconButton uses Button under the hood, so it useStyleConfig of it uses `Button` entry in the theme and not `IconButton`
It's a bit unclear and probably docs or smth can be done to improve this part as I wasted a looooot of time :)

**Comment by takethefake** [comment]
Yes, that's it! The docs mention that "`IconButton` composes the `Button`-component" but I can understand that it's relatively easy to fall for this issue.

also, make sure to nest the `sizes` inside the `sizes`-prop. 

to provide a working example: https://codesandbox.io/s/lingering-wind-8brrm?file=/src/index.tsx
