### ISSUE TITLE
Table not obeying size object syntax

### ISSUE THREAD

**Issue by 1Gokul** [chakra-ui/chakra-ui#4679]
### Description

To display a table responsively, I expected the Table component to obey the object syntax i.e. I expected the size to be **"sm"** on smaller screens and **"lg"** on larger screens. Instead, it is large even on small screens.

### Link to Reproduction

https://codesandbox.io/s/chakra-table-not-obeying-object-syntax-ewqnc?file=/pages/index.js&resolutionWidth=320&resolutionHeight=675

### Steps to reproduce

1. Go to to [this CodeSandbox link](https://codesandbox.io/s/chakra-table-not-obeying-object-syntax-ewqnc?file=/pages/index.js).
2. Click on "Toggle Responsive Preview"
4. Scroll up and down in the preview to see the difference in sizes.

### Chakra UI Version

1.6.7

### Browser

Google Chrome  93.0.4577.63

### Operating System

- [ ] macOS
- [x] Windows
- [X] Linux

### Additional Information

With Object syntax: `<Table size={{ base: "sm", md: "lg" }}  variant="striped" colorScheme="cyan">`

![](https://i.imgur.com/LZMQiye.png)

using one size: `<Table size="sm"  variant="striped" colorScheme="cyan">`

![](https://i.imgur.com/JohtREB.png)

Do tell me if I'm doing something wrong in my implementation of the Table.

Thanks in advance :)

**Comment by segunadebayo** [comment]
Hi @1Gokul,

Responsive size and variants are currently not supported in v1. We're planning this to land in the next major release.

Thanks

**Comment by 1Gokul** [comment]
Alright!
Wonderful work on Chakra, thanks a lot!

**Comment by 1Gokul** [comment]
To someone else stumbling on this thread, I solved it by using Chakra's [useMediaQuery](https://chakra-ui.com/docs/hooks/use-media-query) hook like so:

```javascript
export const ResultTable = ({ items }) => {
  const [largerThanMD] = useMediaQuery("(min-width: 784px)")
  return(
    <Flex overflowX="auto">
      <Table
        size={largerThanMD ? "lg" : "sm"}
        variant="striped"
        colorScheme="cyan"
        border="2px"
        borderColor="cyan.600"
      >
...
```

There's a warning about it not working with SSR, but it won't affect my app as this table would be rendered only after an input by the user.

**Comment by 1Gokul** [comment]
To anyone else stumbling on this thread, I solved it by using Chakra's [useMediaQuery](https://chakra-ui.com/docs/hooks/use-media-query) hook like so:

```javascript
export const ResultTable = ({ items }) => {
  const [largerThanMD] = useMediaQuery("(min-width: 784px)")
  return(
    <Flex overflowX="auto">
      <Table
        size={largerThanMD ? "lg" : "sm"}
        variant="striped"
        colorScheme="cyan"
        border="2px"
        borderColor="cyan.600"
      >
...
```
