### ISSUE TITLE
CRA example - DependencyNotFoundError

### ISSUE THREAD

**Issue by nainardev** [chakra-ui/chakra-ui#468]
**Describe the bug**
DependencyNotFoundError

**Expected Behavior**
Template works

**To Reproduce**
https://codesandbox.io/s/github/chakra-ui/chakra-ui/tree/master/examples/create-react-app

https://immqr.csb.app

**Suggested solution(s)**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tioluwani94** [comment]
Hi @nainardev, 

I noticed that the project on Codesandbox doesn't have the required dependencies (@chakra-ui/core, @emotion/core, @emotion/styled and emotion-theming), hence the error you are getting. If you add these dependencies everything should work fine. 

You can also check out Chakra UI's starter projects for JavaScript and Typescript on Codesandbox.

https://codesandbox.io/s/chakra-js-starter-lzzg9
https://codesandbox.io/s/chakra-ts-starter-pomi8

Cheers.
