### ISSUE TITLE
Full screen modals don't appear full screen (iOS Safari)

### ISSUE THREAD

**Issue by nRocket** [chakra-ui/chakra-ui#4680]
### Description

When I open a full screen modal on iOS safari it does not fill the full screen. There's a gap at the bottom the screen.

### Link to Reproduction

https://chakra-ui-git-fix-modal-height-ios-chakra-ui.vercel.app/docs/overlay/modal#modal-sizes

### Steps to reproduce

On an iPhone 
1. Go to https://chakra-ui-git-fix-modal-height-ios-chakra-ui.vercel.app/docs/overlay/modal#modal-sizes
2. Click on "open full modal'
3. full modal does not cover full screen when the safari navigators aren't there (see attached image)

### Chakra UI Version

1.6.4

### Browser

Safari on iPhone X 14.7.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

possibly caused by css styling below as removing it allows the modal to go full screen.

```
@supports (height: -webkit-fill-available)
modal:1.css-v9b9hc {
  height: -webkit-fill-available;
}
```

However the above code was added to solve this other issue: https://github.com/chakra-ui/chakra-ui/pull/3806

![Image from iOS (2)](https://user-images.githubusercontent.com/69126995/132506363-9598a0fa-e4ea-4a3b-a2ae-fc1a48ef8885.png)

**Comment by jmherzo** [comment]
The issue is still happening, so this thread shouldn't be closed. It is related to the behavior of iOS safari and the browser url section in the bottom of the screen.

**Comment by yamankatby** [comment]
This still an issue and should be reopened again!

**Comment by thiagobutignon** [comment]
This issue still happening any work around?

**Comment by KiranMantha** [comment]
on top of @metanivek solution, i added height as well:
```typescript
Modal: {
      baseStyle: {
        dialogContainer: {
          '@supports(height: -webkit-fill-available)': {},
          height: '100%'
        }
      }
    }
```

this worked for me.
