### ISSUE TITLE
[tooltip] Show at most one tooltip at a time

### ISSUE THREAD

**Issue by Andarist** [chakra-ui/chakra-ui#4685]
### Description

The strategy to display at most one tooltip at a time tends to improve UX in certain scenarios.

### Problem Statement/Justification

When using `closeDelay` (which I find preferable from the UX point of view) it seems highly undesirable to have 2 tooltips rendered at once. This can easily happen when triggering tooltips with keyboard navigation and when "jumping" through elements. The issue gets worse with long longer labels as tooltips might overlap with each other as each one gets positioned without taking the other one into consideration.

Take a look at this sandbox:
https://codesandbox.io/s/trusting-darkness-2yqz6?file=/src/App.js

### Proposed Solution or API

Use module-level (global~) variables to track open tooltip and if there is any tooltip shown when displaying a new one - dismiss the older one (immediately, without taking `closeDelay` into account for this action).

**Comment by Andarist** [comment]
bump for the stale bot

**Comment by Andarist** [comment]
bump for the stale bot

**Comment by Andarist** [comment]
Bump for stale bot

**Comment by kentongray** [comment]
Since there are other bugs with the tooltips not closing that remain open (https://github.com/chakra-ui/chakra-ui/issues/6255) this seems like a good workaround to me

**Comment by Andarist** [comment]
Bump for stale bot
