### ISSUE TITLE
Component losing style in Next.js with persistent layout

### ISSUE THREAD

**Issue by yudyananda** [chakra-ui/chakra-ui#4689]
### Description

When using Next.js with [Layout](https://nextjs.org/docs/basic-features/layouts) all Chakra UI component inside the layout not rendered as it should be

### Link to Reproduction

https://github.com/yudyananda/chakraNextLayout

### Steps to reproduce

1. Go to component inside Layout for example `components/Header/SiteHeader`
2. Check on `Container` and `Flex`
3. See error
   - The `Container` rendered without default style like margin and width
   - The theme token value from all component like padding, maxWidth will be passes to the css, for example `p="6" => 6px` `maxW="container.md" => container.md`
   - Responsive style token failed to render 

### Chakra UI Version

1.6.6

### Browser

N/A

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @yudyananda,

This is due to how the `_app.js` is setup here: https://github.com/yudyananda/chakraNextLayout/blob/main/pages/_app.js#L17

I think `getLayout` should be called below the `ChakraProvider`

```jsx
function MyApp({ Component, pageProps }) {
   // Use the layout defined at the page level, if available
   const getLayout = Component.getLayout || (page => page);

   return (
      <ChakraProvider theme={theme}>
         <CSSReset />
         <GlobalStyle />
         {getLayout(<Component {...pageProps} />)}
      </ChakraProvider>
   );
}
```

Please try this and I'm happy to re-open if the issue still persists.

**Comment by sunncyn** [comment]
in my case, this approach make h-screen bug (adding padding area at bottom)

**Comment by edemagbenyo** [comment]
> in my case, this approach make h-screen bug (adding padding area at bottom)

I am facing the same issue here. Have you been able to find a way to fix that?
