### ISSUE TITLE
Popper V2

### ISSUE THREAD

**Issue by nainardev** [chakra-ui/chakra-ui#469]
**Describe the bug**
this uses v1.16.1

**Expected Behavior**

**Suggested solution(s)**

**Desktop (please complete the following information):**
 - OS: [linux]

**Additional context**

**Comment by aaronmcadam** [comment]
Here's some background on what is improved: [Smarter Tooltips and Popovers with Popper 2](https://dev.to/fezvrasta/smarter-tooltips-and-popovers-with-popper-2-44bh)

**Comment by segunadebayo** [comment]
Hi @nainardev, I've upgraded the popper component to use V2 in the `dev-ts` branch. This will be published soon.

To verify, you can check the popper package in dev-ts.

Thanks

**Comment by nicolad** [comment]
hello @segunadebayo, you wrote previously that update to v2 will be published soon, do you have any updates?
