### ISSUE TITLE
@chakra-ui/icons: Module not found: Can't resolve '@chakra-ui/system' in '[redacted]/packages/app/node_modules/@chakra-ui/icon/dist/esm'

### ISSUE THREAD

**Issue by zkindest** [chakra-ui/chakra-ui#4693]
### Description

compilation errors with chakra icons

### Link to Reproduction

https://github.com/zkindest/messageboard/tree/d1bd07eac13057387e22386ad4799610e64cc824

### Steps to reproduce

1. yarn app install
2. uncomment line [6](https://github.com/zkindest/messageboard/blob/d1bd07eac13057387e22386ad4799610e64cc824/packages/app/src/components/Thread.tsx#L6) & [30](https://github.com/zkindest/messageboard/blob/d1bd07eac13057387e22386ad4799610e64cc824/packages/app/src/components/Thread.tsx#L30)
3. yarn app start
4. you will see compile error regarding chakra icons.

### Chakra UI Version

  @chakra-ui/icons@^1.0.15 (Not using UI for now)

### Browser

Brave

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Hi @zkindest,

Chakra UI Icons required `@chakra-ui/system` to work. If you don't want to have UI, I recommend installing the `@chakra-ui/system` package. Otherwise, please consider using other icon libraries like `react-icons` or `radix-icons`.
