### ISSUE TITLE
Stack ignores defaultProps

### ISSUE THREAD

**Issue by maximkott** [chakra-ui/chakra-ui#4694]
### Description

When I try to extend the theme and configure defaultProps for the Stack component, the defaultProps are being ignored.

### Link to Reproduction

https://codesandbox.io/s/magical-dan-8szht?file=/src/index.tsx

### Steps to reproduce

```ts
extendTheme({
  components: {
    Stack: {
      defaultProps: {
        isInline: true,
        spacing: "3rem",
      },
    },
  },
})
```

### Chakra UI Version

1.6.7

### Browser

Version 93.0.4577.63 (Official Build) (x86_64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @maximkott,

The `defaultProps` keys are constrained to only theming-related props. You can only use `colorScheme`, `variant`, and `size`. Any other keys will be ignored.

Please use React's conventional `Stack.defaultProps = {...}` approach to set the default values for the component.

Thanks.
