### ISSUE TITLE
Tooltip custom variant with prop bg does not color the arrow

### ISSUE THREAD

**Issue by arbejd** [chakra-ui/chakra-ui#4695]
### Description

When i make a custom tooltip Variant i expect the arrow to also be colored with the bg style prop

### Link to Reproduction

https://codesandbox.io/s/long-frost-9m4rm

### Steps to reproduce

make a custom variant
assign to a tooltip
mouseover the tooltip

### Chakra UI Version

latest

### Browser

Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

It works when you set the bg directly

**Comment by anubra266** [comment]
@arbejd, your reproduction is just a fresh chakra UI sandbox

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Please follow the issue template as we're not able to act on issues that are lacking important information.

**Comment by arbejd** [comment]
Dont know why i didnt save it. I remade the repo here:

https://codesandbox.io/s/9m4rm?file=/src/index.js

**Comment by arbejd** [comment]
@segunadebayo  is this sufficient to reopen?

**Comment by randex** [comment]
While these guys play bureaucracy:

If anybody googles their way here when having the same problem (like me): define a css var `popper-arrow-bg` and set it to your color with `colors.` prefix at the start.

```
const $arrowBg = cssVar("popper-arrow-bg");
export default {
  baseStyle: {
    // ... other styles
    [$arrowBg.variable]: "colors.red.500",
  },
};
```

But the better way is to use `cssVar` to set both the background color and arrow color. Use the same approach as in the [default tooltip theme](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/tooltip.ts).

**Comment by fritzschoff** [comment]
Well done! Shame that nothing is written in the docs about that

**Comment by Digital-Human-BK** [comment]
The problem still persists! Thanks to @randex. I hope this issue will be fixed...

**Comment by bj-nostra** [comment]
Broken.

I added `hasArrow` to the docs example and we get this nice black diamond for the `blue` colorScheme.

<img width="921" alt="image" src="https://github.com/chakra-ui/chakra-ui/assets/126716058/0e244f20-eb08-4a7c-ac6c-70350dc982a7">

The issue appears to be that the tooltip itself is checking if there is a `userDefinedBg` user defined background coming in on props, and it ignores the theme extension mechanisms.

**Comment by TiagoJeronimo** [comment]
@segunadebayo would it be possible to reopen this issue?

**Comment by jassibacha** [comment]
Still dealing with this issue in 2025, hoping it gets reopened!
