### ISSUE TITLE
Loading spinner does not work for Button and IconButton.

### ISSUE THREAD

**Issue by manzoorwanijk** [chakra-ui/chakra-ui#47]
In certain cases, `<Spinner />` and `<Button />` or `<IconButton />` with `isLoading` are not visible.
[Here](https://codesandbox.io/s/chakra-ui-spinner-xr43u) is the sandbox.

The issue is the missing `borderStyle` prop in `<Spinner />` which should be `solid` by default. You can see the difference in the sandbox. For `<Spinner />` it's possible to pass the prop explicitly but not in case of `<Button />` and `<IconButton />`.

PR on the way :)

**Comment by segunadebayo** [comment]
I see. Thank you for this @manzoorwanijk 

Ideally, It works when you add the `<CSSReset/>` component to your `<ThemedApp/>` which adds a global style like

```css
*, *:before, *:after{
border-style:solid;
}
```

I now see that users might ignore the `<CSSReset/>` and it still needs to work. Thank you for the PR.
