### ISSUE TITLE
Update Color Mode page

### ISSUE THREAD

**Issue by lazarnikolov94** [chakra-ui/chakra-ui#4700]
### Subject

Color Mode

### Description

Update [Color Mode page](https://chakra-ui.com/docs/features/color-mode) to use `ChakraProvider` instead of `ColorModeScript`.

**Comment by segunadebayo** [comment]
As far as I can remember, the `ColorModeScript` is still needed to get color-mode stuff working correctly. Switching to `ChakraProvider` might have no effect.

I could be wrong though, what did you have in mind @lazarnikolov94?

**Comment by lazarnikolov94** [comment]
Oh, my bad, totally forgot about it. I'm going to close this issue.
