### ISSUE TITLE
RTL broken for InputLeftElement/InputRightElement

### ISSUE THREAD

**Issue by glocore** [chakra-ui/chakra-ui#4701]
### Description

When I switch to RTL, components in InputLeftElement and InputRightElement stay in place.

### Link to Reproduction

https://codesandbox.io/s/chakra-inputrightelement-bug-pd3cl

### Steps to reproduce

1. Create an InputGroup with an InputRightElement in it
2. Open DevTools and add the `dir="rtl"` attribute to the `<html>` tag
3. Observe that InputRightElement stays on the right

### Chakra UI Version

1.6.7

### Browser

Google Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I'm not sure if this is the intended behaviour, but I've observed other instances of "right" and "left" elements switch sides in RTL. For example, `leftIcon` in the `<Button/>` component switches to the right side in RTL mode.

![Screen Recording 2021-09-10 at 7 23 38 PM](https://user-images.githubusercontent.com/24620401/132864410-c03e4adc-c56b-4ee5-8bfa-61edc7f50e48.gif)

**Comment by glocore** [comment]
Yes, but that only partially fixes the problem. The contents of `InputRightElement` now overlap on top of the Input.
<img width="653" alt="Screenshot 2021-09-10 at 8 16 18 PM" src="https://user-images.githubusercontent.com/24620401/132872341-52dbbb7a-7736-4969-8a52-7812fd717499.png">

Besides, I don't seem to require this for the Button example I mentioned above. I'm guessing flexbox handles the direction in those cases.

**Comment by segunadebayo** [comment]
Hi @glocore,

Add `direction: rtl` to the theme and setting `dir=rtl` to the root element (`html`) solves the RTL issue you're facing.

The other issue you might see is that padding doesn't flip properly. For this, we recommend using logical CSS properties instead. Here's how to fix it.

```diff
 <InputGroup size="md" dir="rtl">
      <Input
-       paddingRight="4.5rem"
+       paddingEnd="4.5rem"
        type={show ? "text" : "password"}
        placeholder="Enter password"
      />
      <InputRightElement width="4.5rem">
        <Button h="1.75rem" size="sm" onClick={handleClick}>
          {show ? "Hide" : "Show"}
        </Button>
      </InputRightElement>
    </InputGroup>
```
