### ISSUE TITLE
Popover not working with RC Scrollbars

### ISSUE THREAD

**Issue by delucca** [chakra-ui/chakra-ui#4709]
### Description

A Popover component don't work when inside a custom Scrollable component from RC Scrollbars

### Link to Reproduction

https://codesandbox.io/s/chakra-scrollbars-5t49x?file=/src/index.tsx

### Steps to reproduce

1. Click on the first button. You will see it works without the Scrollbars;
2. Click on the first button. You will see it don't work with Scrollbars

### Chakra UI Version

1.6.7

### Browser

Firefox

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Related to [rc-scrollbars#30](https://github.com/sakhnyuk/rc-scrollbars/issues/30)

**Comment by segunadebayo** [comment]
Hi @delucca,

I think you might have set up the component incorrectly. The "real" popover is the `PopoverContent` and you need to wrap `Scrollbars` around that not the root `Popover` component itself.

Here's a working example: https://codesandbox.io/s/chakra-scrollbars-forked-ib8bt?file=/src/index.tsx

Hope you find it useful.
