### ISSUE TITLE
Weird styles

### ISSUE THREAD

**Issue by nainardev** [chakra-ui/chakra-ui#471]
**Describe the bug**
No styling in a new app

**Expected Behavior**
Correct Button style

**Scrrenshots**
![Screenshot (119)](https://user-images.githubusercontent.com/59839368/75779076-01c2e100-5d7f-11ea-830c-d590f5ab819d.png)

**Comment by segunadebayo** [comment]
I'm sorry but we don't understand the problem you are reporting. This looks like you're not using the CSSReset component in your app.

Please provide a repository or CodeSandbox reproducing this problem, and describe the difference between the expected and current behavior.

**Comment by nainardev** [comment]
How to use CSSReset
