### ISSUE TITLE
Align the presence or absence of spaces

### ISSUE THREAD

**Issue by watagit** [chakra-ui/chakra-ui#4715]
### Subject

FeaturesSection

### Description

Is it intentional that some parts of this page have spaces while others do not?

https://chakra-ui.com/docs/features/gradient

```ts
// bgGradient has spaces
<Box w="100%" h="200px" bgGradient="linear(to-l, #7928CA, #FF0080)" />

// no space
<Box
  w="100%"
  h="200px"
  bgGradient="linear(to-r,gray.300,yellow.400,pink.200)"
/>
```

If this is intentional, please feel free to close this issue. If it is not intentional, I will try to fix it.

**Comment by segunadebayo** [comment]
Thanks for reporting this. It's not intentional and just pushed a fix for it.
