### ISSUE TITLE
[Motion] Unify `motionPreset` across components

### ISSUE THREAD

**Issue by segunadebayo** [chakra-ui/chakra-ui#4722]
At the moment, only the `Modal` component uses the `motionPreset` prop to allow users to change the motion type of the modal, or even disable it.

We want to support this prop in all motion related components, namely `Popover` and `Tooltip`.

**Benefits**
- For those who don't want the animations, they can disable it by passing `motionPreset="none"`
- For those who want to try different motion/transitions, they can use `motionPreset="slideIn" | "scale" | "fade"`

**Comment by tomhicks** [comment]
On a related note, I've noticed that motion animations on modals can be *horribly* slow and janky.

I wonder if there are some less main-thread-dependent presets that can be added, or a documented way of using class-based CSS animations instead.

**Comment by glekner** [comment]
Please implement this

**Comment by georgekrax** [comment]
We should be able to modify the animation altogether, not just change its direction. What would happen if I wanted to have a custom animation on the `<Drawer />` component for example?

**Comment by joernroeder** [comment]
I still like to alter animations more freely

**Comment by georgekrax** [comment]
Me too!!

**Comment by aroman** [comment]
please fix this
