### ISSUE TITLE
[Build] Improve build times by switching to `esbuild`

### ISSUE THREAD

**Issue by segunadebayo** [chakra-ui/chakra-ui#4723]
Building the packages currently takes 5 - 8 minutes on the CI and I think we can massively improve this by using either `preconstruct` or `esbuild`.

**Possible ideas:**
- https://github.com/twilio-labs/paste/blob/012333451cc36383cd4dc6f79fb1e678da676d66/tools/build/esbuild.js
- https://sourcegraph.com/github.com/vladmandic/face-api@ac172b8be50f2b020c22a2dda43a10e0e92d7441/-/blob/server/build.js?L14
- https://sourcegraph.com/github.com/prisma/prisma/-/blob/packages/engine-core/helpers/build.js?L3

If anyone wants to take on this task, that would be amazing!

**Comment by hiroppy** [comment]
Let's take over it. I would like to improve many things of chakra-ui

**Comment by stefee** [comment]
If chakra is currently using Babel then SWC might be a better replacement for it. Esbuild is better positioned as a replacement for Webpack. Both are great though if you can make them work for you.

**Comment by hiroppy** [comment]
I think yes because chakra-ui has its own babel plugin but in my understanding, swc doesn't support babel-plugin now, right?

**Comment by stefee** [comment]
Correct

**Comment by segunadebayo** [comment]
@hiroppy, thanks for chiming in!

Feel free to take on this ticket if you want.

**Comment by segunadebayo** [comment]
Based on #4956, we've decided to use Preconstruct to manage packages in this repo.

Makes this issue obsolete.
