### ISSUE TITLE
How to use the new way to customize component style

### ISSUE THREAD

**Issue by IronTony** [chakra-ui/chakra-ui#4728]
### Subject

Tabs/Input/Menu custom style

### Description

Hi all,

I have some problem understand how to use the new method to  add custom style to components.
I have read the documentation here, and for the Button component is quite easy to follow, but for Input, (I have done but I lost a lot of time to understand),  Tabs, Menu and so on I am really lost.

I think would be great to enrich the documentation with more examples.

All the best

**Comment by segunadebayo** [comment]
@lazarnikolov94 Can you help @IronTony better understand this?

I'll move this to a discussion in the meantime.
