### ISSUE TITLE
Extra organisation sponsors displayed

### ISSUE THREAD

**Issue by DeviousLab** [chakra-ui/chakra-ui#4732]
### Description

When I opened up the main website for Chakra UI and scrolled through it, I noticed that Shogun and Touchless are listed twice in the organisation sponsors section. Just wanted to ask whether this is intentional? 

### Link to Reproduction

https://chakra-ui.com/

### Steps to reproduce

1. Go to [Chakra UI](https://chakra-ui.com/)
2. Scroll down to Organisation Sponsors
3. See error

### Chakra UI Version

Not relevant

### Browser

Google Chrome 93.0.4577

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![image](https://user-images.githubusercontent.com/53790060/133914202-8a0a506f-eec1-40e8-b721-eea29cbe8b24.png)

**Comment by toth2000** [comment]
I would like to work on this issue.
