### ISSUE TITLE
feat(popover): manual trigger mode

### ISSUE THREAD

**Issue by dodas** [chakra-ui/chakra-ui#4733]
Hello Chakra folks!

### Problem Statement/Justification

I have a use case where I need to have a `Popover` where neither clicking nor hovering on the trigger should toggle the visibility of the popover.
Similar to the [Controlled Usage example](https://chakra-ui.com/docs/overlay/popover#controlled-usage), however I want the `Popover Target` button to not close the popover.
In my case the `PopoverTrigger` children is an input and I want to be able to click inside it without closing the popover.

My current workaround:
```tsx
<Popover
    isOpen={isOpen}
    onClose={onClose}
    closeOnBlur={false}
    // Passing anything else than `click` or `hover` works, however TS types do not accept it.
    trigger={"manual" as any}
>
    ...
</Popover>
```

### Proposed Solution or API

Add a `manual` mode for `trigger`. Or should it be called `none` instead?

It seems like just adding this value to the possible `TRIGGER` values makes this work, since Chakra doesn't bind any event listeners in that case.

_____
Thanks!

**Comment by anubra266** [comment]
not stale

**Comment by dodas** [comment]
Please see and comment PR: https://github.com/chakra-ui/chakra-ui/pull/5044
