### ISSUE TITLE
Responsive styles aren't applied when used in `extendTheme` with `Heading` component

### ISSUE THREAD

**Issue by b-novikov-ipersonality** [chakra-ui/chakra-ui#4742]
### Description

When I declare responsive font size styles for `Heading` component in `extendTheme`, I expect `Heading` to have font sizes I set depending on the width of my screen, but instead no styles are applied. 

### Link to Reproduction

https://codesandbox.io/s/inspiring-chandrasekhar-s7x41?file=/pages/index.js

### Steps to reproduce

1. Open `_app.tsx` file
2. Change values of `Heading` font size properties
3. Inspect the `Heading`
4. See no styles are applied.

### Chakra UI Version

1.6.7

### Browser

Chromium Version 92.0.4515.159

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

When apply font size as a primitive value (i.e. `fontSize: 16`), it works, doesn't work with responsive object i.e.
```javascript
fontSize: {
  base: 'xl',
  sm: '2xl'
}
```
Responsive object works with other components like `Text` which is shown in reproduce example.

**Comment by primos63** [comment]
This is a duplicate of #3884

**Comment by anubra266** [comment]
Closing as duplicate of #3884
