### ISSUE TITLE
Add ability to style MenuGroup (and MenuOptionGroup)

### ISSUE THREAD

**Issue by jameshoward** [chakra-ui/chakra-ui#4750]
### Description

Theme props passed to `MenuGroup` and `MenuOptionsGroup` are ignored because `MenuGroup` creates a `div` with no style or generated class name applied.

It would be useful if we could pass props. For example, to add `maxHeight` / `overflow` to scroll a section of the menu instead of the containing page. I'm sure there are plenty of use-cases.

### Problem Statement/Justification

Most components and sub-components can be styled in a consistent manner, but `MenuGroup` doesn't appear to be one of them.

### Proposed Solution or API

The problem is that `...rest` are passed into the `chakra.p` for the title so it could be hard for this not to be a breaking change.

### Alternatives

I tried wrapping the items within `MenuOptionGroup` in a `Box` with styles applied but that means the selected item no longer gets the check icon.

**Comment by segunadebayo** [comment]
Hi @jameshoward,

You can style the `MenuGroup` from the `MenuList` component. I understand it might not be the ideal solution you want but it should work.


```jsx
<MenuList sx={{ ".chakra-menu__group": {...} }} />
```

**Comment by jameshoward** [comment]
I didn't realise you could do that. Thanks, that is a useful workaround (to use sparingly).
