### ISSUE TITLE
@chakra-ui/cli tokens resolves to a wrong tsconfig path resulting in JSON5 error parse

### ISSUE THREAD

**Issue by Nayni** [chakra-ui/chakra-ui#4755]
### Description

When running `@chakra-ui/cli tokens` it resolves to a wrong tsconfig path resulting in a JSON5 error crash

### Link to Reproduction

N/A

### Steps to reproduce

The error:

```
$ chakra-cli tokens ./src/components/ui/styles/theme.ts

 Chakra UI CLI  v1.5.1 by chakra UI
Generate theme typings for autocomplete


✖ An error occurred
SyntaxError: JSON5: invalid character 'i' at 1:1
```

This is what I was able to find during a debug session:

The bug is a result of https://github.com/chakra-ui/chakra-ui/pull/4725 which tries to load the related `tsconfig` using `tsconfig-paths`. However instead of it resolving to a `tsconfig.json` file it uses the exact same file path from the specified theme file.

It all goes wrong on the following line: https://github.com/chakra-ui/chakra-ui/blob/main/tooling/cli/src/scripts/read-theme-file.worker.ts#L34

By calling: `tsConfigPaths.loadConfig` directly with the `absoluteThemePath` it will eventually result in `tsconfig-paths` thinking that the tsconfig is exactly the path that was given (which is a TS file, not a config file).

The argument of `tsConfigPaths.loadConfig` expects a `cwd`. (see: https://github.com/dividab/tsconfig-paths/blob/master/src/config-loader.ts#L41) if this `cwd` is a file that exists it will default to thinking it is the `tsconfig` file (see: https://github.com/dividab/tsconfig-paths/blob/6dc51e43111bea24c847f24d8c13debe305b58bd/src/tsconfig-loader.ts#L74). This results in the CLI crashing.

### Chakra UI Version

@chakra-ui/cli@1.5.1

### Browser

N/A

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Currently keeping our cli version at `1.5.0` as I don't see any way to get around this.

**Comment by ahrbil** [comment]
Hello,
I'm using windows and I have the same error on v 1.5.1

**Comment by karrui** [comment]
It also does not work with a tsconfig that has its paths in a separate tsconfig file (due to overriding CRA)

Also getting a 
```
SyntaxError: JSON5: invalid character 'i' at 1:1
```

my tsconfig:
```
{
  "extends": "./tsconfig.paths.json",
   ...
}
```


my tsconfig.paths.json:
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "~shared/*": ["../shared/*"],
      "~assets/*": ["./src/assets/*"],
      "~contexts/*": ["./src/contexts/*"],
      "~constants/*": ["./src/constants/*"],
      "~components/*": ["./src/components/*"],
      "~templates/*": ["./src/templates/*"],
      "~features/*": ["./src/features/*"],
      "~hooks/*": ["./src/hooks/*"],
      "~utils/*": ["./src/utils/*"],
      "~pages/*": ["./src/pages/*"],
      "~services/*": ["./src/services/*"],
      "~theme/*": ["./src/theme/*"],
      "~typings/*": ["./src/typings/*"],
      "~/*": ["./src/*"]
    }
  }
}

```

**Comment by mheob** [comment]
I can confirm the error while using it in an NX monorepo structure.

```bash
❯ yarn chakra-cli tokens libs/tool/ui/src/theme/theme.ts
yarn run v1.22.11
$ XXX/node_modules/.bin/chakra-cli tokens ./libs/tool/ui/src/theme/theme.ts

Chakra UI CLI  v1.5.1 by chakra UI
Generate theme typings for autocomplete

✖ An error occurred
SyntaxError: JSON5: invalid character 'i' at 1:1
✨  Done in 0.53s.
```

**Comment by TimKolberger** [comment]
@Nayni Thank you for this detailed bug report! 💖  

I opened a PR which resolves the `ts-config.json` from the dirname of the given theme file path.

Cheers

**Comment by kasim444** [comment]
Hi everyone.

I used the latest version of chakra in my new project, but I've been following it for the last few versions. When I run the "chakra-cli tokens" command, I get an error.  A new version was released yesterday that the bug here has been fixed. but still this problem persists. Anyone else encountering this issue with the new version? ( @TimKolberger  @segunadebayo  )

Have a good day.

My chakra-ui versions:

```
"@chakra-ui/cli": "^1.5.2",
"@chakra-ui/react": "^1.6.9",
```

Error detail: 

```js
yarn postinstall
yarn run v1.22.10
$ yarn run gen:theme-typings
$ chakra-cli tokens ./src/styles/theme/index.ts

 Chakra UI CLI  v1.5.2 by chakra UI
Generate theme typings for autocomplete


✖ An error occurred
SyntaxError: Cannot use import statement outside a module
✨  Done in 4.97s.
```

**Comment by TimKolberger** [comment]
Hi everyone,

I am sorry that this issue persists over the last releases after various fixes.

The root of those issue is reading the `ts-config.json` in the userland project to extract the aliases (#4725).
I found no good way to write automated tests for this feature and now I see that this not the way to go.

I tested this feature with a linked version of the chakra-cli "on my machine" with one TypeScript and one JavaScript target codebase. 

Next Steps:
* Revert #4725 and following fixes to get a working chakra cli again
* Get input how to test the CLI automated
* Get help from the community implementing the feature request in #4652

What do you think @segunadebayo?

**Comment by igorwessel** [comment]
Hey guys!

I think I managed to solve the problem, in your fix was reading the project's tsconfig.json but if tsconfig.json didn't have the settings for ts-node it ended up giving this error because it could only use CommonJS. I just override one of the user project settings to be able to use CommonJS.

I will branch now with a fix, but I still haven't been able to write tests for it.

Sorry for bad english!
