### ISSUE TITLE
Drawer's Slide animation cannot be changed in 1.6.8

### ISSUE THREAD

**Issue by glekner** [chakra-ui/chakra-ui#4756]
### Description

When I upgraded to 1.6.8, i can no longer disable the slide animation of the drawer through the `motionPreset` prop

### Link to Reproduction

no need

### Steps to reproduce

Title states the error

### Chakra UI Version

1.6.8

### Browser

Google Chrome 94

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by glekner** [comment]
@segunadebayo

**Comment by glocore** [comment]
Hi @glekner, the Drawer component doesn't use the standard Modal component's transitions, and so the `motionPreset` prop won't work. A temporary workaround would be to emulate `DialogContent` yourself with a z-index of 1400. Check [this sandbox](https://codesandbox.io/s/naughty-roentgen-n9dlx?file=/src/index.js) for inspiration.

**Comment by segunadebayo** [comment]
Hi @glekner,

This isn't a bug, it's the intended behavior of the drawer component. in a separate PR, we're planning to allow users to disable animation for all or some components.

For now, feel free to use the `Modal` component to achieve this (similar to how @glocore showed above)

**Comment by ZiggStardust** [comment]
@segunadebayo when will this be introduced ?

**Comment by lisandropat** [comment]
Is there a possibility to edit Drawer's cubic-bezier?

**Comment by sftsk** [comment]
@segunadebayo any update on disabling animations for some components?
I would like to stick to the drawer component as is but I have an issue when re-rendering the page with an already "open" drawer. It then does the animation and therefore is visually jaggy and disturbing..
