### ISSUE TITLE
Specify w={1} should produce 100% with on Box component

### ISSUE THREAD

**Issue by skube** [chakra-ui/chakra-ui#476]
**Describe the bug**
I'm not exactly sure if this is a bug or intended functionality, but if I understand correctly, Chakra _should_ generally function the same as Styled System. For example, [Styled System shows a Box example](https://styled-system.com/api#layout) where `width` is supplied via props.

The first point states:

> Numbers from 0-1 are converted to percentage widths.

**Expected Behavior**
So, something like :

```jsx
<Box w={1}>This should be 100% width</Box>
```

Should work the same in Chakra

**Actual Behavior**

```jsx
<Box w={1}>Is 1px in Chakra UI</Box>
```

It should be noted fractions _do_ work in Chakra, so:

```jsx
<Box w={1/2}>Is 50% in Chakra UI</Box>
```

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.3
- Browser: chrome
- Version: 80

**Additional context**

**Comment by rickysullivan** [comment]
I think this is because in styled-system v5:

> Uses theme.sizes scale for width, height, minWidth, minHeight, maxWidth, maxHeight, and size props

https://github.com/styled-system/styled-system/pull/513

I think the Styled System API docs needs updating.

**Comment by rickysullivan** [comment]
Actually.

https://styled-system.com/getting-started#layout

> If an array is used to define theme.sizes, width={0} will return theme.sizes[0] and width={1} will return theme.sizes[1]

I tested this by changing my theme:

```
import { theme as chakraTheme } from "@chakra-ui/core";

const theme = {
  ...chakraTheme,
  sizes: undefined
}
```

Now I get 100% width when supplying `w={1}` or 50% when supplying `w={1/2}`

**Comment by segunadebayo** [comment]
@skube, I traced down this issue to this https://chakra-ui.com/theme#spacing.

The theme has a scale for "1" in `theme.sizes`, that's why it behaves like that.

I'll suggest you use "100%" for now,  or remove the "1" scale from the theme object.

Thanks.
