### ISSUE TITLE
How to use component without React Hook

### ISSUE THREAD

**Issue by juzhiyuan** [chakra-ui/chakra-ui#4761]
### Subject

component

### Description

Hi, I'd like to use the Toast[1] component inside `axios`'s interceptors, when a success/error response is received, it will show a Toast.

When I read the documentation, I find that I could only use `useToast` to init the instance, does there have other ways to use it?

[1] https://chakra-ui.com/docs/feedback/toast

**Comment by stefee** [comment]
It sounds like you are looking for `createStandaloneToast`: https://chakra-ui.com/docs/feedback/toast#standalone-toasts

**Comment by juzhiyuan** [comment]
Good
