### ISSUE TITLE
Display errors in Editable and change behaviour of EditablePreview when EditableInput is invalid

### ISSUE THREAD

**Issue by neg4n** [chakra-ui/chakra-ui#4763]
### Description

It would be super cool if [`Editable`][editable-chakra-docs] could be easily used in [`FormControl`][form-control-chakra-docs] context and not only `EditableInput` but `EditablePreview` would respect the `isInvalid` prop from [`FormControl`][form-control-chakra-docs].

Also, It would be good to have `errorBorderColor` prop in the [`Editable`][editable-chakra-docs] that will set the boxShadow both for `EditableInput` and `EditablePreview` when the whole [`Editable`][editable-chakra-docs] is invalid.

[editable-chakra-docs]: https://chakra-ui.com/docs/form/editable
[form-control-chakra-docs]: https://chakra-ui.com/docs/form/form-control<details>

## The observed problem

I'm creating more or less complex form using [react-hook-form][rhf-homepage]. One of my form elements is interactive set of editable instructions created using [`useFieldArray`][rhf-use-field-array] from [react-hook-form][rhf-homepage] along with [`FormControl`][form-control-chakra-docs] and [`Editable`][editable-chakra-docs]s as its children.

The problem is how errors are handled. Even if the `EditableInput` is invalid after form submission - it does not display error border (as in regular [`Input`][input-chakra-docs]) because it is not displayed at all if the [`Editable`][editable-chakra-docs] isn't focused.
 
I think it should be `EditablePreview`'s responsibility to visually display error because current behaviour leads to inconsistence between form parts (comparing regular [`Input`][input-chakra-docs] with error border when invalid to [`Editable`][editable-chakra-docs] when invalid which apart from focusing the element after submission does not display any visual information at all).

## Workaround

First of all, I've created helper component that must be embedded in base instruction list inside [`Editable`][editable-chakra-docs](s). It takes current [`Editable`][editable-chakra-docs] `index`, triggers `EditableInput` when there is an error in the form and returns `FormErrorMessage` with corresponding message.

<summary><b>Helper component code</b></summary>
<details>

```ts
function EditableInstructionInputError({ index }: { index: number }) {
  const {
    formState: { errors }
  } = useFormContext<CreateRecipeFormValues>()

  const { getEditButtonProps } = useEditableControls()

  useEffect(() => {
    if (errors?.instructions?.[index]?.content) {
      const editButton = getEditButtonProps()
      if (editButton.onClick) {
        editButton.onClick(null as any)
      }
    }
  }, [errors?.instructions?.[index]?.content])

  return <FormErrorMessage>{errors?.instructions?.[index]?.content?.message}</FormErrorMessage>
}
```

</details>

The next things I've done:
1. Set `isPreviewFocusable` in [`Editable`][editable-chakra-docs] to be true only when there is an error
2. Modified `EditablePreview` and `EditableInput` styles to emulate `errorBorderColor` behaviour from regular [`Input`][input-chakra-docs] when whole [`FormControl`][form-control-chakra-docs] is invalid.
3. Set `placeholder` in [`Editable`][editable-chakra-docs] to some dummy text.  
**NOTE:** *This is important and I will explain it in the further part of feature request*

<summary><b>Full code of instructions list component</b></summary>
<details>

```ts
type CreateRecipeFormValues = Omit<CreateRecipeDto, 'instructions'> & {
  instructions: Array<{ content: string }>
}

export function InstructionsListInput() {
  const {
    register,
    control,
    formState: { errors }
  } = useFormContext<CreateRecipeFormValues>()
  const { fields, append, remove } = useFieldArray({ control, name: `instructions` })

  return (
    <Stack
      p={4}
      spacing={4}
      borderWidth="1px"
      borderStyle="solid"
      borderColor="gray.200"
      borderRadius={8}
    >
      <OrderedList as={Stack} flexDirection="column">
        {fields.map((instruction, index) => (
          <ListItem key={instruction.id}>
            <FormControl isRequired isInvalid={!!errors?.instructions?.[index]?.content}>
              <Editable
                as={Stack}
                alignItems="center"
                direction="row"
                defaultValue={instruction.content}
                isPreviewFocusable={!!errors?.instructions?.[index]?.content}
                placeholder="Your epic instruction."
                startWithEditView
              >
                <Stack w="100%">
                  <EditablePreview
                    {...(!!errors?.instructions?.[index]?.content && {
                      boxShadow: '0 0 0 2px red',
                      color: 'transparent',
                      px: 3
                    })}
                    w="100%"
                  />
                  <EditableInput
                    {...(!!errors?.instructions?.[index]?.content && {
                      color: '0 0 0 2px red'
                    })}
                    {...register(`instructions.${index}.content`, {
                      required: {
                        value: true,
                        message: 'Please enter an instruction step.'
                      }
                    })}
                  />
                  <EditableInstructionInputError index={index} />
                </Stack>
                <EditableInstructionStepControls index={index} onDelete={() => remove(index)} />
              </Editable>
            </FormControl>
          </ListItem>
        ))}
      </OrderedList>
      <Button
        leftIcon={<Icon as={FiPlus} w={5} h={5} />}
        colorScheme="gray"
        onClick={() => append({ content: "I'm a super cool instruction." })}
      >
        Add new instruction
      </Button>
    </Stack>
  )
}
```

</details>

[rhf-homepage]: https://react-hook-form.com
[rhf-use-field-array]: https://react-hook-form.com/api/usefieldarray
[editable-chakra-docs]: https://chakra-ui.com/docs/form/editable
[input-chakra-docs]: https://chakra-ui.com/docs/form/input
[form-control-chakra-docs]: https://chakra-ui.com/docs/form/form-control

## Preview

The workaround presented in the previous section of this issue looks like that

https://user-images.githubusercontent.com/57688858/134815938-511a63d0-66d0-453d-a5a0-81a5b23bf9ef.mov

## API Suggestions

1. Due to https://github.com/chakra-ui/chakra-ui/pull/4409#issuecomment-895043005 and https://github.com/chakra-ui/chakra-ui/issues/4116 the `placeholder` in [`Editable`][editable-chakra-docs] must be present in order to determine span size and  `color` of the `EditablePreview` should be `transparent` when `EditableInput` has invalid state but is not displayed because of lack of focus on [`Editable`][editable-chakra-docs]
2. `errorBorderColor` prop in [`Editable`][editable-chakra-docs]
3. error border on `EditablePreview` triggered when `EditableInput` is indicated as invalid and is not focused.

Sorry but these are the only API suggestions that I can provide because I'm not familiar with chakra internals on level where I can provide more reliable technical solution :( 

Cheers! Igor

[editable-chakra-docs]: https://chakra-ui.com/docs/form/editable

**Comment by neg4n** [comment]
bump

**Comment by segunadebayo** [comment]
Hi @neg4n,

Thanks for this issue. I think it's more of a custom requirement for your application than it is an issue we should fix for all consumers. I appreciate the level of detail and understand your suggestion.

I just think it'll work better as a recipe than something we should add to the core of Chakra UI.

Thanks for understanding.

> PS: A workaround could be to use the exported `useEditable` hook as well.

**Comment by barrymichaeldoyle** [comment]
Is there a recipe for this yet?
