### ISSUE TITLE
useConfirm hook

### ISSUE THREAD

**Issue by pravosleva** [chakra-ui/chakra-ui#4764]
### Description

Need have confirm alert with buttons YES / NO

### Problem Statement/Justification

Quick solution. Must have for any ui kit.

### Proposed Solution or API

```js
import { useConfirm } from '@chackra-ui'

// USAGE:
const confirm = useConfirm()

confirm({
  title: 'YOUR_TITLE',
  description: 'YOUR_DESCR',
  // size, etc.
})
.then(() => {
  // Do something if YES...
})
.catch((err) => {
  // Do something if NO...
})
```

**Comment by segunadebayo** [comment]
Hi @pravosleva,

This sounds like an interesting idea. Thanks for sharing.

For now, I'd recommend using the `AlertDialog` component to achieve this. We don't intend to include this API

Thanks for understanding.
