### ISSUE TITLE
regression during update from 1.6.6 to 1.6.8 theme became: Dict<any>

### ISSUE THREAD

**Issue by maapteh** [chakra-ui/chakra-ui#4765]
### Description

When we upgraded from 1.6.6 to 1.6.8 the types for extendTheme became `Dict<any>`

### Link to Reproduction

http://nope

### Steps to reproduce
```
import { extendTheme } from '@chakra-ui/react';
```

- First do a yarn with 1.6.6 then look at its typing.
- Then install 1.6.8 and look at its typing.
- Normally the theme was typed

### Chakra UI Version

1.6.8

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Its a TS issue. will show by screenshots

**Comment by maapteh** [comment]
1.6.6 :
<img width="817" alt="Screenshot 2021-09-27 at 15 59 47" src="https://user-images.githubusercontent.com/25961356/134923951-f1a0f7f9-035e-4e00-8d11-91a018a93b8f.png">

**Comment by maapteh** [comment]
1.6.8:
<img width="578" alt="Screenshot 2021-09-27 at 16 04 17" src="https://user-images.githubusercontent.com/25961356/134924219-0f3f79c6-bf77-439a-b386-48817bd863bb.png">

**Comment by maapteh** [comment]
```
❯ yarn why @chakra-ui/react
yarn why v1.22.11
[1/4] 🤔  Why do we have the module "@chakra-ui/react"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@chakra-ui/react@1.6.6"
info Reasons this module exists
   - "_project_#@foo#components" depends on it
   - Hoisted from "_project_#@foo#components#@chakra-ui#react"
info Disk size without dependencies: "320KB"
info Disk size with unique dependencies: "13.86MB"
info Disk size with transitive dependencies: "27.97MB"
info Number of shared dependencies: 62
✨  Done in 0.97s.
```

**Comment by segunadebayo** [comment]
Hi @maapteh, 

If you checked the changelog, you'll see that we added a comment about the TS complexity we experienced working with the types. It got to the point where any additional change we made to it will be a breaking change, hence the reason for this change.

Feel free to stay on `1.6.6` for now or wait till we rewrite the types to be more maintainable. Thanks for understanding.
