### ISSUE TITLE
[Proposal] `GridItem.at`

### ISSUE THREAD

**Issue by Enteleform** [chakra-ui/chakra-ui#4766]
### Description

I am proposing a shorthand positioning attribute for `GridItem`.

&nbsp;  
### Problem Statement/Justification

Positioning `GridItem` can be verbose:

```jsx
<GridItem rowStart={1}, colStart={1}, colSpan={1}, rowSpan={1}/>
```

&nbsp;  
### Proposed Solution or API

This can be expressed more concisely using common coordinate attributes:

```jsx
<GridItem at={{x:1, y:1, w:1, h:1}}/>
```

**Comment by segunadebayo** [comment]
Hi @Enteleform,

This sounds like an interesting idea. After much thought, I don't think we'll go in this direction.
