### ISSUE TITLE
Request to support breakpoints properties to the size property.

### ISSUE THREAD

**Issue by yassinebridi** [chakra-ui/chakra-ui#477]
**Is your feature request related to a problem? Please describe.**
Many components that has the **size** property doesn't work with responsive properties that ChakraUI utilize like the **heading** and **button** components

**Describe the solution you'd like**
for the size property to handle breakpoints properties.

**Describe alternatives you've considered**
I had to use the **fontSize** property for the Heading component instead of **size** for it to be responsive.

**Comment by segunadebayo** [comment]
Hi @yassinebridi, we're not looking to make component "size" prop responsive.

Instead, we'll provide a simple hook to detect breakpoints and change the size prop with that.

As much as we'd like to give lots of flexibility, this is one constraint we plan to introduce. I believe the hook alternative will work pretty well.
