### ISSUE TITLE
CloseButton inside Badge warning

### ISSUE THREAD

**Issue by f-laino** [chakra-ui/chakra-ui#4773]
### Description

If I put a CloseButton component inside Badge component it return me `Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>` or, if I add `as="text", `Warning: The tag <text> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.`

### Link to Reproduction

https://codesandbox.io/s/peaceful-oskar-9edob?file=/src/index.tsx

### Chakra UI Version

CloseButton 1.1.11, Layout 1.4.9

### Browser

Google Chrome 93.0.4577.63

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by aboveyunhai** [comment]
@f-laino  This is not a Chakra `bug`, You are nesting `button` inside `button`, which violate the `html` rule. Of course you will get those warnings. Instead, you could do something like the below.
```js
  <Button rightIcon={<CloseIcon />} variant="outline">
      text
  </Button>
```
