### ISSUE TITLE
Number Input increment / decrement sometimes require 2 clicks at min / max respectively.

### ISSUE THREAD

**Issue by rafaelderolez** [chakra-ui/chakra-ui#4776]
### Description

With the mobile spinner (Number Input) example from the docs, when the spinner is at its minimum it sometimes requires two clicks on the increment button to actually do anything (and vice-versa to decrement at max value)

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-number-input-inc-dec-bug-dfuq2

### Steps to reproduce

0. Visit [Sandbox](https://codesandbox.io/s/chakra-ui-number-input-inc-dec-bug-dfuq2) and open console
1. Click minus button to decrement to minimum value of 1
2. Click on plus button to increment
3. Expect value to increase to 2 but remains at 1
4. Click plus button again to increment
5. Value finally increases to 2

### Chakra UI Version

1.6.8

### Browser

Brave V1.30.86

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

![Kapture 2021-10-01 at 14 03 39](https://user-images.githubusercontent.com/6158959/135616968-e840ce1b-cbcf-4e02-b1c8-706cdbaf702f.gif)

**Comment by piersolenski** [comment]
Solid report. Couldn't be more clear imo.

**Comment by xotea** [comment]
#4646 might be related. If i copy your code and paste it to the [codesandbox](https://codesandbox.io/s/use-number-input-bug-3s371) of my PR (#4703) the issue seems to be gone.

**Comment by anubra266** [comment]
will be fixed in #4982

**Comment by samhecquet-divido** [comment]
Hi @anubra266 , any update on #4982 being merged?
