### ISSUE TITLE
Flex is not working correctly on refresh (shown in the attached video). 

### ISSUE THREAD

**Issue by jakegiri** [chakra-ui/chakra-ui#4778]
### Description
Flex is not working correctly on refresh (shown in the attached video). 
After refresh, the `div` element associated with `Flex` component gets transformed from `<div class="css-1ijbxy6">` to `<div class="chakra-container css-ydhjs">`

### Link to Reproduction

https://github.com/jakegiri/storeKeystone_Frontend/blob/chakraFlexBug/components/Layout/Header/subComponents/HeaderTopSmallDevice.tsx

### Steps to reproduce

1. Open the root folder in terminal
2. hit "npm run dev" on terminal
3. And in browswer do the same as shown in the video. 

### Chakra UI Version

1.6.7

### Browser

Google Chrome 94

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

https://user-images.githubusercontent.com/24270559/135699653-ba68ebcf-6225-4c13-a0ee-721762114dad.mp4

**Comment by TimKolberger** [comment]
Hi @jakegiri, 

your referenced reproduction results in a 404.
Please provide a reproduction, preferably in codesandbox that we can try live.

Cheers

**Comment by primos63** [comment]
@TimKolberger This was also posted on the [Discord](https://discord.com/channels/660863154703695893/660865137137156146/893697485661437964) where I provided triage and a work-around. It's not an issue with Flex, but with the way the `useMediaQuery` hook relays changes. Github issue #4657 already exists for this problem.

**Comment by TimKolberger** [comment]
Thanks for the update @primos63!
Closing this in favor of the linked issue.

**Comment by jakegiri** [comment]
@TimKolberger Yeah @primos63 already answered this in discord that its the issue with `useMediaQuery`. I was about to update it here. Thanks @primos63
