### ISSUE TITLE
Modal initialFocusRef not working as expected when using with React Hook Form

### ISSUE THREAD

**Issue by rajmasha** [chakra-ui/chakra-ui#4792]
### Description

When I opened the modal, I expected email field to be focused but the ModalCloseButton was focused

### Link to Reproduction

https://codesandbox.io/s/agitated-cdn-sth4w?file=/pages/index.js

### Steps to reproduce

1. On the index.js file, click the "Open Modal" button
2. You can see that the ModalCloseButton is in focus instead of the email input field

### Chakra UI Version

1.6.8

### Browser

Google Chrome 94

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I have passed the **initialRef** for the email field but still, the ModalCloseButton is focused when the modal opens.
If I remove the **{...register("email")}** from the email input then it works as expected.

**Comment by segunadebayo** [comment]
Hi @rajmasha,

This isn't a bug. Looking at your code, the reason this happens is because `...register("email")` provides a `ref` under the hood that overrides the `ref={initialRef}` you provided.

Here's how to solve it:

```jsx
// import { useMergeRefs } from "@chakra-ui/react"

// merge the ref from RHF and initial ref
<Input
    id="email"
    type="email"
    placeholder="Enter email address"
    {...register("email")}
     ref={useMergeRefs(initialRef, register("email").ref)}
/>
```

https://codesandbox.io/s/sad-clarke-mv6zm?file=/pages/index.js:1202-1452
