### ISSUE TITLE
Add RTL Support for ButtonGroup

### ISSUE THREAD

**Issue by rajadain** [chakra-ui/chakra-ui#4796]
### Description

Currently, when using `ButtonGroup` with `isAttached`, the inner borders are not curved and the outer ones are. This is reversed if ever the page switches to Right-to-Left text rendering, such as when selecting Arabic or Hebrew as the language. In such case, the curved borders look backwards.

If there was RTL awareness baked in to `ButtonGroup`, or something like a `reverse` prop, that could be used to render the correct curvature in both cases.

### Problem Statement/Justification

Without this, `ButtonGroup` cannot be used with RTL languages, since the curves are backwards.

### Proposed Solution or API

Perhaps something like this:

```jsx
<ButtonGroup reverse={document.dir === 'rtl'}>
  ...
</ButtonGroup>
```

### Additional Information

Correct rendering in Left-to-Right:

![image](https://user-images.githubusercontent.com/1430060/136111277-b79681fc-9db2-4047-b6cd-ad87c0962daf.png)

Incorrect rendering in Right-to-Left:

![image](https://user-images.githubusercontent.com/1430060/136111318-ae7d1c09-b2e0-4558-8d8a-55348ce249f8.png)

**Comment by segunadebayo** [comment]
Hi @rajadain,

You didn't attach a CSB reproduction but here's how to fix this. I assume that you only applied "direction===rtl" to your code but it's insufficient to get RTL working in Chakra. Here's what you need to do in addition.

```jsx
1. Add dir=rtl to the document element (HTML)

2. Add `direction: rtl` to the chakra theme
<ChakraProvider theme={{...theme, direction: "rtl"}}>
    <App />
</ChakraProvider>
```

When you do that, RTL will work as you expect.
