### ISSUE TITLE
spaces/sizes deprecated but what then to use

### ISSUE THREAD

**Issue by maapteh** [chakra-ui/chakra-ui#4802]
### Subject

theme

### Description

From code perspective and docs its not clear what to use. There is a deprecated message on spacing:

https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/foundations/spacing.ts#L38

It tells to use sizes, then looking at sizes:

https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/foundations/sizes.ts#L37

This one also mentioned it's deprecated. But what i?s then left? Maybe a deprecation annotation should always have mentioning what to use? Now it states "You can derive the Sizes type from the DefaultChakraTheme"?

So when using `mt={2}` where is this 2 then defined in our theme (so i can reuse spacing in own components)?

**Comment by segunadebayo** [comment]
Hi @maapteh,

It's just the type that is deprecated not the object itself. `DefaultChakraTheme['sizes']` is the new type we recommend using.
