### ISSUE TITLE
useBreakpointValue is broken with custom breakpoint (idea on how to solve that) (good first issue imo)

### ISSUE THREAD

**Issue by alexisvisco** [chakra-ui/chakra-ui#4813]
### Description

When I use custom breakpoints by extending the them and use the `useBreakpointValue` hook, the behavior should take the closest breakpoint even with a custom breakpoint, but it doesn't. 

### Link to Reproduction

https://codesandbox.io/s/sad-chatterjee-o39ye?file=/src/index.tsx

### Steps to reproduce

Resize the screen, you will constantly be below the `2sm` breakpoint (32em).

### Chakra UI Version

1.6.9

### Browser

Chrome

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

To solve this problem I copy/paste the useBreakpointValue and here at this line https://github.com/chakra-ui/chakra-ui/blob/main/packages/media-query/src/use-breakpoint-value.ts#L32 you are getting the list of breakpoints. 

The problem is that you are calling the [getClosestValue](https://github.com/chakra-ui/chakra-ui/blob/cb49051ff99a3ac992221fd85928be744cee0eb7/packages/media-query/src/media-query.utils.ts#L3) on a list that isn't sorted !! 

To solve this problem I have been doing this kind of thing: 
```ts
  const breakpoints = Object.keys(theme.breakpoints).sort((a, b) => {
    return Number.parseInt(theme.breakpoints[a], 10) > Number.parseInt(theme.breakpoints[b], 10) ? 1 : -1
  })
```

Hope this solution can solve the problem for all users :thinking:  ?

**Comment by Brennvo** [comment]
Possibly clarified with #4815
