### ISSUE TITLE
Ability to add custom motion variants to menu component

### ISSUE THREAD

**Issue by joernroeder** [chakra-ui/chakra-ui#4826]
### Description

Right now menu motion variants are hardcoded into the component https://github.com/chakra-ui/chakra-ui/blob/main/packages/menu/src/menu.tsx#L127 and is impossible to overwrite.

### Problem Statement/Justification

By allowing to override the motion variant the <MenuList> component could serve as the semantic base for flyouts as you build https://pro.chakra-ui.com/components/marketing/flyout-menu for example but would enhance them with all the goodies like keyboard support etc.

### Proposed Solution or API

Allow to pass in a `<MenuList motionVariant={myMotionVariant} />` and fall back to the one currently used as a default.

**Comment by joernroeder** [comment]
Still like to see this being implemented.

**Comment by benjamincharity** [comment]
Not stale

**Comment by Geeknerd1337** [comment]
Running into this issue now as well, want to be able to override the transition animation for a menu list but can't seem to
