### ISSUE TITLE
using the `as` property on `<ModalContent>` breaks the animations of the modal

### ISSUE THREAD

**Issue by Ploppy3** [chakra-ui/chakra-ui#4833]
### Description

using the `as` property on `<ModalContent>` breaks the animations of the modal

### Link to Reproduction

https://codesandbox.io/s/stupefied-cache-o8768?file=/src/index.js

### Steps to reproduce

1. Go to https://chakra-ui.com/docs/overlay/modal
2. Modify `<ModalContent>` to `<ModalContent as="form">`
3. Open and close the modal
4. See error: animations are broken, the modal appear and disappear instantly

### Chakra UI Version

1.6.6

### Browser

Chrome 94

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Weirdly enough, it works on codesandbox but doesn't on chakra website & in my project.

**Comment by anki247** [comment]
@segunadebayo Thank you! 
I had a similar issue, but not reg. the animation...
If you pass `as="form"` to `<ModalContent />` it leaks the motion props `initial`, `animate`, `exit` and `variants` to the DOM.
But your hint reg. the submit button saved me 🙏 ❤️
