### ISSUE TITLE
bug(CheckboxGroup): Array of number doesn't work as value.

### ISSUE THREAD

**Issue by don-hover** [chakra-ui/chakra-ui#4838]
### Description

When providing an array of `number` as the `value` prop to a `CheckboxGroup` component that has `Checkbox` children with matching `value` props, I expect to see those `Checkbox` children checked when the id values match the values in the `CheckboxGroup`.  This does not work when the ids are of `number` type; no matching and setting of `checked` is happening.  When all id values are of `string` type, everything works as expected.  See previous issue https://github.com/chakra-ui/chakra-ui/issues/196.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-issue-checkboxgroup-5ggr6

### Steps to reproduce

1. Go to codesandbox url.
2. Notice the checkboxes initially checked as a result of the value controlled by state.
2. Observe the logging below checkboxes shows three checked values.
3. Click on a checkbox to uncheck.
4. Observe all checkboxes are cleared; logging shows empty array as CheckboxGroup value.
5. Check a checkbox; UI shows one checked box, logging shows array of one value as CheckboxGroup value.
6. Check an additional checkbox; UI shows one checked box, logging shows array of one value as CheckboxGroup value.

Something is obviously wrong here.

### Chakra UI Version

1.6.8

### Browser

Chrome 93

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Yes, I agree @takethefake. This issue has been raised before.

Because we're passing the value to the underlying input element which accepts a `DOMString` and returns a `string` in its `onChange` callback, we might not be able to do anything about this.

Please consider casting the values to `string` in the userland.
