### ISSUE TITLE
Stack, Inline, Columns

### ISSUE THREAD

**Issue by export-mike** [chakra-ui/chakra-ui#484]
Hey Thought I'd share and potentially start a discussion about this layout pattern thats trending.

theres been a growing interest in this pattern for layout. Its really neat!

all components have minimal to no margins. all spacing is determined by the layout. theres this awesome effort in Braid design system

https://github.com/seek-oss/braid-design-system/tree/master/lib/components/Stack

Theres also movement in this area with system-ui. in this PR 
https://github.com/system-ui/theme-ui/pull/719

all pretty much inspired from this setup in playroom. take a look 👀 
https://seek-oss.github.io/braid-design-system/playroom/#?code=N4Igxg9gJgpiBcIA8BBANjATgFwATYgDsYBeAHRAEtCAzCCgPgHUY1IBbGfCXABTQCGAT0wQI7AIRIA9OizYGZQkgDK2AWADWuAWkoBzQuXAxC2LBVwBnAA4bSFQZn0xGS3LiQAhAVBeLCDw8AC0p3IJkfPxgAoM8o-3CQsMCI6QSYpPjfRNTkrMiczOVpNQ1NBhAAXyA

Stack, Inline and Columns to achieve layout control,
https://seek-oss.github.io/braid-design-system/playroom/#?code=N4Igxg9gJgpiBcIA8BlALgQzAawHxIHp0s8ACJASQDsAbASypnwOvsd3IGEIaBXAWyoBnfNz6DmYgVUk9pIkAF8gA

Effectively you stop using flex properties and you build up a more declarative and strict ui. as described here: https://gist.github.com/mxstbr/f24105fe48a5263b2bc42699216f55d4

Thought I'd share what I've found as this was a big discussion at the recent react conference in Sydney Australia 🎉 

Braid is heavily coupled to css modules, so theres a bunch of changes in that library to get mappings to css class names, but i feel theres a bunch of similarities with braid and chakra.

Would be awesome to have this style of layout system. I've been playing around with a stack and inline components so far in a side project. 

Edit: I notice theres already a stack component 🎉 Columns and Inline would be epic

**Comment by segunadebayo** [comment]
This is a great idea @export-mike. We've added the `Inline` component to the next release, and looking to improve the Stack component as well to support responsive values and a `divider`.

In the next release, all the layout components will be bundled as `@chakra-ui/layout`. Some more goodies (components) are coming as well 😄

Thanks for these ideas!

**Comment by export-mike** [comment]
Amazing very excited!

**Comment by stephane2018** [comment]
@segunadebayo great information it will facilitate the build of certaine desing ui feature in react using chakra. Aligatore!
