### ISSUE TITLE
Remove focus on modal close button when opened

### ISSUE THREAD

**Issue by pengchew** [chakra-ui/chakra-ui#4840]
### Description

Remove focus on modal close button when opened

### Link to Reproduction

https://chakra-ui.com/docs/overlay/modal

### Steps to reproduce

<img width="350" alt="1" src="https://user-images.githubusercontent.com/64325702/137366741-c413b82c-4a32-4240-a099-33863c45bec1.png">
https://chakra-ui.com/docs/overlay/modal

### Chakra UI Version

https://chakra-ui.com/docs/overlay/modal

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by purohitdheeraj** [comment]
or simple have `tabIndex={-1}` on close button :D 
esc is already there
