### ISSUE TITLE
Allow usage of Menu/MenuList/MenuItem components that don't trap focus

### ISSUE THREAD

**Issue by jamesopti** [chakra-ui/chakra-ui#4844]
### Description

We'd like to use the Chakra Menu components to build a filterable/searchable list (related to #4311).

Using the current Menu context with it's child components always focuses the menu or menuitem on focus, which prevents typing in the input that might filter it.

### Problem Statement/Justification

This would enable building more consistent UIs using the Menu component which need to be controlled programmatically, like the UI in #4311

### Proposed Solution or API

I think a simple prop like `disableFocus` that prevents focus from being stolen but still supports keyboard, hover, and mouse interactions would be all we need.

### Alternatives

Due to how much context is used in `Menu`, only forking it entirely would suffice.

**Comment by lerichardson** [comment]
I'd be happy to add this if it pleases the maintainers
