### ISSUE TITLE
Group components in docs

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#485]
One of the issues we've found at work when onboarding devs to Chakra is that it's hard for them to get a sense of all the components that are available for them to use in a given situation. I believe this is partially due to the way components are laid out in the docs.

Rather than listing the components alphabetically, it would be more useful to list them in basic groups. Grouping the layout components would allow a dev to see at a glance which components are available for laying out a page, grouping the form components would allow seeing which components are available for building forms, etc.

imo those two groups plus a "display" components group for the remaining components would go a long way in making it more obvious which components are available to use and when to use them.

**Comment by tioluwani94** [comment]
Hi @with-heart, we are looking into this style of documentation of components for the next major release of Chakra.
