### ISSUE TITLE
Button component with `link` variant has focus ring smaller than the text content on mobile

### ISSUE THREAD

**Issue by resurrexi** [chakra-ui/chakra-ui#4861]
### Description

Button component with `link` variant has focus ring smaller than the text content on mobile

### Link to Reproduction

https://chakra-ui.com/docs/form/button

### Steps to reproduce

1. Open the [link](https://chakra-ui.com/docs/form/button) on a mobile screen.
2. Activate the focus state of the button with the `link` variant.
3. The focus ring (box-shadow) appears smaller than the text content.

### Chakra UI Version

1.6.10

### Browser

Chrome 94

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Screenshot of the button showing the behavior:

![screenshot](https://i.imgur.com/QQ7M1AL.png)

**Comment by segunadebayo** [comment]
This is a non-issue in my opinion and can be easily fixed in the user-land. Tweaking the internal styles for this might cause a break in visual layout for others.
