### ISSUE TITLE
Editable variant not working as expected

### ISSUE THREAD

**Issue by hlynurstef** [chakra-ui/chakra-ui#4871]
### Description

When I added a variant to Editable I expected the text in the editable field style to be updated in accordance to the variant style but instead nothing happens.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-editable-variant-k7k5o?file=/src/App.js

### Steps to reproduce

1. Open codesandbox link
2. First `Editable` uses variant and has incorrect styling
3. Second `Editable` sets the style directly and has correct styling
4. They should both have the same styling.

### Chakra UI Version

1.6.10

### Browser

Google Chrome Version 94.0.4606.81 (Official Build) (x86_64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by takethefake** [comment]
Hej @hlynurstef thanks for reaching out!

after checking your example I realized that you didn't define the container you want to style in your variant. Since `Editable` defines `preview` and `input` this has to be adjusted.

Your definition.
```ts
import { extendTheme } from "@chakra-ui/react";

export const theme = extendTheme({
  components: {
    Editable: {
      variants: {
        bold32: {
          fontSize: "32px",
          lineHeight: "36px",
          letterSpacing: "-0.005em",
          fontWeight: "700"
        }
      }
    }
  }
});
```

to get the desired behavior just add an `preview` below `bold32` (see [codesandbox](https://codesandbox.io/s/chakra-ui-editable-variant-forked-zovtc?file=/src/theme.js))

```tsimport { extendTheme } from "@chakra-ui/react";

export const theme = extendTheme({
  components: {
    Editable: {
      variants: {
        bold32: {
          preview: {
            fontSize: "32px",
            lineHeight: "36px",
            letterSpacing: "-0.005em",
            fontWeight: "700"
          }
        }
      }
    }
  }
});

```

**Comment by hlynurstef** [comment]
@takethefake this should be stated in the documentation. Right now there is a very minimal explanation on how the variants work with this component and the link provided does not explain that you need to nest preview and input inside the variant. I'd suggest making the documentation clearer on this.

![image](https://user-images.githubusercontent.com/15615089/139684953-31a6f584-e9bf-4841-9536-ce9cac216cad.png)

**Comment by takethefake** [comment]
@hlynurstef thanks for pointing this out - I've adjusted the docs accordingly :)
