### ISSUE TITLE
_invalid Input State Theming

### ISSUE THREAD

**Issue by ryansle** [chakra-ui/chakra-ui#4887]
### Description

Is there a reason this shouldn't work?

```
export const chakraTheme = extendTheme({
  components: {
    FormLabel: {
      defaultProps: { _invalid: { textColor: 'red.100' } },
    },
  },
});
```

It works fine as a prop on the component but I want to have it be a default.

### Problem Statement/Justification

This is important as to not having to individually set `_invalid` states on all components throughout a codebase. We should be able to theme it directly to apply to all components.

### Proposed Solution or API

(see above snippet)

**Comment by felquis** [comment]
Hey team,

How can I use defaultProps of a prop like _invalid or _autofill in the extendTheme?

```
  components: {
    Input: {
      defaultProps: {
        _autofill: {
          textFillColor: 'green',
          boxShadow: `0 0 0px 1000px pink inset`,
        },
      },
    },
  },
```

Because it says "defaultProps" I think of _invalid or _autofill as props as well. May you give me some light?

**Comment by Thebigbignooby** [comment]
What is the recommended way of changing the error color theme-wide?

ie: the default error color in the base theme is `red.500` in light mode and `red.300` in dark mode.
I want to change it to `red.400` for dark mode: do I have to set this for `color` and `border` for the `Input`s and the `FormError` (duplicating a lot of code).  or is there a more straightforward way of changing this?

**Comment by dlindenkreuz** [comment]
@Thebigbignooby Use `theme.component.Input.defaultProps.errorBorderColor`.
