### ISSUE TITLE
[Menu] Allow links as MenuItems

### ISSUE THREAD

**Issue by Andarist** [chakra-ui/chakra-ui#4892]
### Description

Currently, there is no clear way to render anchors as menu items. Existing `MenuItem` strongly assumes that it's going to render a button element:
https://github.com/chakra-ui/chakra-ui/blob/910a701f9f3b16157f287479a3df64a2ea84090b/packages/menu/src/menu.tsx#L259

### Problem Statement/Justification

This is a valid use case, implemented as an example here: https://www.w3.org/TR/wai-aria-practices-1.2/examples/menu-button/menu-button-links.html

### Proposed Solution or API

Either provide an option on the `MenuItem` (could be indirect) or create a new `MenuItemLink` component. An example in the docs of how to use this would be appreciated as well.

**Comment by santialbo** [comment]
You can render a link with
```tsx
<MenuItem as="a" href="https://github.com/chakra-ui/chakra-ui/issues/4892">
  link
</MenuItem>
```

**Comment by Andarist** [comment]
I know how to achieve this - but it stays a little bit undocumented. Using it like this also doesn't provide the best TS experience:
```jsx
const buttonRef = React.useRef<HTMLButtonElement>(null)
return (
  <MenuItem
    as="a"
    // @ts-expect-error - atm this is valid, but should be an error if using `as` is canonical answer to this question
    ref={buttonRef}
    href="https://github.com/chakra-ui/chakra-ui/issues/4892"
  >
    link
  </MenuItem>
)
```

**Comment by jansengunderson** [comment]
> I'm interested to tackle this issue. I've found this interesting.
> 
> Out of curiosity, is it that bad just replace the button with `<Link/>` component? as following:
> 
> ```js
> <MenuItem as={Link} minH="48px" href="https://chakra-ui.com" isExternal>
>    <span>Fluffybuns the Destroyer</span>
>  </MenuItem>
> ```
> 
> I know this isn't the best solution since we are breaking semantic rules, but at least is a workaround.
> 
> I think we need more traction, before starting a new component or changing an API, although I don't think is the best thing to assume that every MenuItem will be a button

This works as long as you're not using a routing library. We've tried implementing Gatsby Link, but it breaks accessibility. Our current solution is to pass Reach Router's navigate() function to the button's onClick.

**Comment by Zoe7** [comment]
FYI, I was trying to implement something like this with Next but haven't had too much luck getting it working with their link component. Next's links are pretty picky about only having a single child and it looks like using `<MenuItem as={NextLink} ... >` causes multiple children to be passed to Next's link, which breaks the build.

I can kind of work around this by using the button's `onClick` event to programmatically navigate, but that's not great for accessibility.
I can also use a simple `a` tag for the links, but then Next doesn't know that those are internal links and I lose all the benefits Next normally provides for links (prefetching, preserving state across pages, etc.)

I made a small codesandbox to illustrate the issue and different workarounds: https://codesandbox.io/s/bold-sound-wgdoi?file=/pages/_app.js
The MenuItem "solution" is commented out, since it breaks the build. You can comment it back in to see what happens 🙂

**Comment by Andarist** [comment]
I think this works OK:
```jsx
<Menu>
    <MenuButton>Working menu</MenuButton>
    <MenuList>
        <NextLink href="/" passHref>
            <MenuItem as="a">Home</MenuItem>
        </NextLink>
        <NextLink href="/about" passHref>
            <MenuItem as="a">About</MenuItem>
        </NextLink>
        <NextLink href="/profile" passHref>
            <MenuItem as="a">Profile</MenuItem>
        </NextLink>
    </MenuList>
</Menu>
```

Can be tested here: https://codesandbox.io/s/nervous-elbakyan-2mcxs?file=/pages/_app.js

I wouldn't call this intuitive though.

**Comment by Zoe7** [comment]
Oh wow, that indeed works 🤯 I would not have thought of that 😄 
Thanks!

**Comment by Andarist** [comment]
Nobody said that `MenuItem` has to compose the `NextLink` :P it can be the other way around! However, this is still a pity that they just can't be composed in any order - and that a particular composition order might be required when integrating with a specific framework. 

Given how popular Next is I would probably include a "blessed" way of integrating with it in the docs

**Comment by Andarist** [comment]
bump for the stale bot

**Comment by Andarist** [comment]
Bump for stale bot

**Comment by Andarist** [comment]
Bump for stale bot

**Comment by S-STALWART-S** [comment]
> You can render a link with
> 
> ```tsx
> <MenuItem as="a" href="https://github.com/chakra-ui/chakra-ui/issues/4892">
>   link
> </MenuItem>
> ```

"Hydration failed" error in NextJS
