### ISSUE TITLE
[ControlBox] Use PseudoBox for better composability

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#49]
Checkboxes and radio buttons have a lot of states heavily depending on CSS pseudo selectors. As suggested in #46, using `PseudoBox` to style form controls would open up new possibilities like using different icon colors for active and inactive states of a checkbox.

Also, the button-like [behavior](https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/Button/styles.js) described by #45 could be achieved by code similar to below:

```tsx
const choice = 'Answer to a quiz question';

<Radio
  key={choice}
  value={choice}
  isDisabled={selectedChoice != null}
  isFullWidth
  px={3}
  py={2}
  bg={color}
  borderWidth={1}
  _hover={{
    // This is the important part
    // ...
  }}
>
  {choice}
</Radio>
```

**Comment by tioluwani94** [comment]
Hi @kripod,

Thanks for the feedback, it is highly appreciated. We have looked into this and we would release a patch soon.

**Comment by kripod** [comment]
@tioluwani94 Unfortunately, no patch has been released for this. I would like to know whether the issue can be re-opened.
