### ISSUE TITLE
Button in Modal - click event not working

### ISSUE THREAD

**Issue by aaronbentley** [chakra-ui/chakra-ui#4900]
### Description

When I click the button in a modal, the button event is broken

### Link to Reproduction

https://codesandbox.io/s/gatsby-chakra-ui-modal-button-demo-64ldc?file=/src/pages/index.js

### Steps to reproduce

1. Click the pink button, this works (functionality wise, I'm aware there's an issue with the URL provided for this reproduction)
2. Then open the Modal via the purple button
3. Click the pink button in the modal - it's exactly the same as the button outside the modal, but the click event doesn't seem to register

### Chakra UI Version

1.6.6

### Browser

All browsers I've tested (Chrome, Safari, Firefox, Opera & Edge desktop browsers) have the same issue.

### Operating System

- [x] macOS
- [x] Windows
- [x] Linux

### Additional Information

I'm loading an external script via React Helmet, which should capture the click event of a Button and open a new window/tab to allow the user to order a print/poster.

However as the Button is in a Modal component, it doesn't work - while digging through this trying to identify the issue, I found that if I move the Button from within the Modal to the page itself (i.e not in a Portal) it all works as intended.

Can anyone suggest how to go about fixing this?

Thanks in advance,

Aaron.

<img width="1982" alt="Screenshot 2021-10-22 at 10 27 39" src="https://user-images.githubusercontent.com/3936200/138431226-c5ba2eba-8ae5-49c5-ace4-50d5a63fc5c7.png">

**Comment by pm-pp** [comment]
Hey @segunadebayo, 

I'm facing similar issue. I've a global listener for the click event (track analytics event of interest) which work fine when every click **not happening inside** a Chakra modal (AlertDialog in my case). Any click inside a modal does not trigger the listener. I can see the click event listener set on every modal HTML element but it does not triggers at all (notice the that listener set in `document`).

![image](https://user-images.githubusercontent.com/103785246/182677114-663598d1-f885-4649-9933-0868d65da6af.png)

I checked @AaronBentley's reproduction CodeSandbox and I think it exemplifies the issue perfectly.

@AaronBentley were you able to find a workaround?

By the way awesome work with Chakra UI! Top-notch library and a pleasure to work it 💪 🤩

**Comment by AaronBentley** [comment]
Hey @pm-pp 👋
Apologies, I never did find a solution to this issue. 
I stopped work on the side project this was for due to a third party API the app was using became unavailable.

I second your comment above above regarding the awesomeness of Chakra UI 🙌

**Comment by realing29** [comment]
> Hi Aaron,
> 
> Thanks for reporting this issue. I can't seem to reproduce this problem.
> 
> Please send a CodeSandbox reproduction of this issue to re-open this.

The problem is still being observed

**Comment by jfrader** [comment]
I have the same issue

**Comment by rodolfoufscar** [comment]
any updates? i have the same issue
