### ISSUE TITLE
Tooltip does not align to <Icon/> component

### ISSUE THREAD

**Issue by JohannesKlauss** [chakra-ui/chakra-ui#4902]
### Description

When I use the <Tooltip/> component, I expect the tooltip to appear at the wrapped element, but instead it appears somewhere else.

### Link to Reproduction

https://codesandbox.io/s/beautiful-sky-ejbvd?file=/src/index.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/beautiful-sky-ejbvd?file=/src/index.tsx
2. Hover over the icons
3. The first icons show the tooltip at the begin of the text and not at the position of the icon. The second one, using the ref approach doesn't show up anywhere.

### Chakra UI Version

1.6.10

### Browser

Google Chrome 93

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
If you're using `react-icons`, wrap the icon component in a `span`.

**Comment by zhondori** [comment]
> If you're using `react-icons`, wrap the icon component in a `span`.

Tooltip also don't align with SVG imported icons
