### ISSUE TITLE
Modal footer is not visible on iOS browsers

### ISSUE THREAD

**Issue by vangelov** [chakra-ui/chakra-ui#4903]
### Description

Footers of modals with ```size="full"``` and ```scrollBehavior="inside"```  are not visibile on iOS 

### Link to Reproduction

https://codesandbox.io/s/romantic-greider-xwuy6

### Steps to reproduce

1. Open the sandbox link
2. Click on Open modal
3. The footer is not visible

### Chakra UI Version

1.6.10

### Browser

Safari and Chrome 

### Operating System

iOS 14 & 15

### Additional Information

The same issue has been reported before here: https://github.com/chakra-ui/chakra-ui/issues/3684
It's been subsequently fixed but it seems it's now happening again. 

I did some digging and it seems this is caused by `ModalContent`'s `minHeight` being `100vh`:
https://github.com/chakra-ui/chakra-ui/blob/3adda59f95986abfc7b4d97a855900270cde2d3c/packages/theme/src/components/modal.ts#L86

The problem goes away if the codesandbox example is modified like this:
```
<ModalContent minHeight="-webkit-fill-available">
...
</ModalContent>
```

**Comment by ocean90** [comment]
I was able to restore the footer by using this global style:

```js
const styles = {
	global: () => ( {
		// Fix missing modal footer on iOS 15.
		'.chakra-modal__content': {
			'@supports(height: -webkit-fill-available)': {
				minHeight: '-webkit-fill-available !important',
			},
		},
	} ),
};
```

where `styles` is passed to `extendTheme()` and the theme provider.

**Comment by yss14** [comment]
Our workaround so far:

```typescript
// extendTheme
Modal: {
  baseStyle: {
    dialogContainer: {
      '@supports(height: -webkit-fill-available)': {},
    },
  },
}
  
// Modal component
const getViewports = () => ({
  viewport: {
    width: Math.max(document.documentElement.clientWidth || 0, window.innerWidth || 0),
    height: Math.max(document.documentElement.clientHeight || 0, window.innerHeight || 0),
  },
  visualViewport: {
    width: window.visualViewport.width,
    height: window.visualViewport.height,
  },
})

const useVisualViewport = () => {
  const [state, setState] = useState(getViewports)
  useEffect(() => {
    const handleResize = () => setState(getViewports)
    window.visualViewport.addEventListener('resize', handleResize)
    return () => window.visualViewport.removeEventListener('resize', handleResize)
  }, [])
  return state
}

<ModalContent
  height={height.visualViewport.height}
  minH={'auto'}
  maxH={'auto'}
>
...
</ModalContent>
```

**Comment by Hasmaa** [comment]
This is still an issue in 2024.

**Comment by ega130** [comment]
> I was able to restore the footer by using this global style:
> 
> const styles = {
> 	global: () => ( {
> 		// Fix missing modal footer on iOS 15.
> 		'.chakra-modal__content': {
> 			'@supports(height: -webkit-fill-available)': {
> 				minHeight: '-webkit-fill-available !important',
> 			},
> 		},
> 	} ),
> };
> where `styles` is passed to `extendTheme()` and the theme provider.

Works on Chakra v3 as well.
But need to change a bit: `chakra-modal__content` -> `chakra-dialog__content`
