### ISSUE TITLE
Add a Hover Card components to Chakra UI

### ISSUE THREAD

**Issue by iamsahebgiri** [chakra-ui/chakra-ui#4905]
### Description

I want to have a hover card like that of Twitter or Wikipedia as Chakra UI components. When a user hover over the card it should show up information as if it is a popover.

![Screenshot (2)](https://user-images.githubusercontent.com/47132373/138490689-06cbd2b9-1ef4-4b66-8e01-b1ce4ac0fed7.png)

### Problem Statement/Justification

- Improve UX, instead of opening every links in new tab, they can see a short info.
- Reduce time building our own
- Increase chakra components
- One less things to worry about :)

### Proposed Solution or API

https://github.com/radix-ui/primitives/tree/main/packages/react/hover-card/src

**Comment by gitisforme** [comment]
Nice.
