### ISSUE TITLE
The inferred type of 'theme' cannot be named without a reference to '../../../../node_modules/@chakra-ui/utils/dist/types'. (ts: 2742)

### ISSUE THREAD

**Issue by georgekrax** [chakra-ui/chakra-ui#4913]
### Description

I am extending the Chakra UI's theme with my own, but in the `them/index.ts` file, where I export the `const theme = extendTheme({})` variable, VS Code TypeScript highlights this as an error.

### Steps to reproduce

1. Go to your custom **theme** configuration file 
2. Hover over the `const theme = extendTheme({})` variable
3. See error

### Chakra UI Version

1.6.10

### Browser

Google Chrome 94

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Code snapshot:

```ts
import { extendTheme, ThemeComponents, ThemeConfig } from "@chakra-ui/react";
// import * as hey from "@chakra-ui/react";

const theme = extendTheme({
  config,
  components,
  colors: {
    brand: {
      primary: "#ff4600",
      secondary: "#1a202c",
    },
  },
});

export default theme;
```

*Error: The inferred type of 'theme' cannot be named without a reference to '../../../../node_modules/@chakra-ui/utils/dist/types'. This is likely not portable. A type annotation is necessary.ts(2742)*

**However, when I uncomment the 2nd line, and import from the `@chakra-ui/react` or `@chakra-ui/system` package, there is no error**

**Thanks in advance for your help!**

@segunadebayo Any idea why is this happening?

**Comment by MahdiTa97** [comment]
It will be solved if you set theme type to any

```ts
import { extendTheme, ThemeComponents, ThemeConfig } from "@chakra-ui/react";
// import * as hey from "@chakra-ui/react";

const theme: any = extendTheme({
  config,
  components,
  colors: {
    brand: {
      primary: "#ff4600",
      secondary: "#1a202c",
    },
  },
});

export default theme;
```

**Comment by anubra266** [comment]
Please feel free to reopen this issue when you create a codesandbox reproduction @georgekrax 
Happy coding
