### ISSUE TITLE
ColorModeScript should not produce its own script tag

### ISSUE THREAD

**Issue by Manc** [chakra-ui/chakra-ui#4915]
### Description

As far as I understand, the purpose of `<ColorModeScript />` is to have the color mode preference detected and set as soon as possible to avoid a flash.

My two issues:

1. If I integrate `<ColorModeScript />` into my Create React App like [this](https://github.com/chakra-ui/chakra-ui/blob/75edcf41e7ff4acc2569f2169949063c164d8f6e/tooling/cra-template/template/src/index.js), a script tag will be created in the DOM, but it doesn't appear to be executed.
2. It seems unnecessary to me to integrate the script like this: `<script nonce={props.nonce} dangerouslySetInnerHTML={{ __html: html }} />`. Is there a specific purpose for this that I may overlook?

I created a copy of the file [`/src/color-mode-script.tsx`](https://github.com/chakra-ui/chakra-ui/blob/75edcf41e7ff4acc2569f2169949063c164d8f6e/packages/color-mode/src/color-mode-script.tsx) and just added some `console.log("Hello")` to it, but never saw any of it.

**Important:** I only looked at this from a client-rendered perspective in a Create React App-style app, nothing server-rendered. Just keep that in mind, that my thoughts are not fully thought through.

### Problem Statement/Justification

The problem is, since the tag `<ColorModeScript />` is in the `index.tsx` and the `<script>` will only be injected into the DOM when the main app's script has been loaded anyway, I don't really see the point why we don't execute the actual code directly in the `index.tsx`, before `ReactDOM.render()`. The code will definitely be executed there, it is guaranteed to run before the React app is initialised, and the code can be written in TypeScript, optimised and compressed.

### Proposed Solution or API

For my own testing I created the following function:

```tsx
const storageKey = "ColorMode"; // <-- This is just my custom key for local storage.

export function getStoredColorMode(): ColorMode | null {
	const stored = localStorage.getItem(storageKey);
	if (stored === "dark" || stored === "light") {
		return stored;
	}
	return null;
}

export function initColorMode() {
	try {
		console.log("Initializing color mode");
		let colorMode: ColorMode;
		const stored = getStoredColorMode();
		if (stored) {
			colorMode = stored;
		} else {
			colorMode = window.matchMedia("(prefers-color-scheme: dark)").matches
				? "dark"
				: "light"
		}
		document.documentElement.style.setProperty("--chakra-ui-color-mode", colorMode);
	} catch (_) {}
}
```

Note: In this implementation the value `null` means `"system"` color mode.

Then in `index.tsx`:

```tsx
initColorMode();

ReactDOM.render(
	<React.StrictMode>
		<App />
	</React.StrictMode>,
	document.getElementById("root"),
);
```

**Comment by saadel** [comment]
It sounds like the documentation needs to be updated, I couldn't get it to work for CRA with this:
https://chakra-ui.com/docs/features/color-mode#for-create-react-app
