### ISSUE TITLE
Allow to change Popover popper style on a per-basis Popover

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#4919]
### Description

I would like to change the style of only some popovers I have.

Currently, I have to change the style in the theme. But this changes the style of every popover I have. I would like to rather do this:

```
<Popover maxW="unset" w="unset">
    ...
</Popover
```

### Problem Statement/Justification

I would like to change the style of only some popovers I have.

### Proposed Solution or API

Allow something like:

```
<Popover maxW="unset" w="unset">
    ...
</Popover
```

**Comment by Venipa** [comment]
```jsx
<PopoverContent as={React.Fragment}>
// card div with your stylings etc, might need transition handling with isOpen prop
</PopoverContent>
```
