### ISSUE TITLE
Spinner vs Circluar Progress clarification

### ISSUE THREAD

**Issue by OfficerHalf** [chakra-ui/chakra-ui#492]
The circular progress component seems to supersede the spinner, but there's no indication in the docs which is the newer/preferred component. Maybe one should be deprecated, or at least marked as such in the docs?

Or do they serve some different purpose? Is it just the difference in animation?

**Comment by segunadebayo** [comment]
Hi @OfficerHalf,

Semantically the Spinner and CircularProgress serve different purposes. Visually, <CircularProgress/> in it's "indeterminate" state looks more like <Spinner/>.

**CircularProgress**
It's used to denote the progress of a determinate operation. Take for example an image upload operation:
- Before upload begins, the upload progress is indeterminate (at this point, it’s just spinning),
- Once we know the size of the image and begin upload (using axios) then we update the progress value of the CircularProgress (at this point, it shows the progress).

CircularProgress also comes with the aria-* attributes to make its progress value accessible to screenreaders.

**Spinner**
It's more of a “presentational” loading indicator you can use on a page or a component, while it’s loading or before it renders. It doesn’t have any semantic meaning.

To give meaning to a Spinner/loading indicator, ARIA standards require that you mark the area of the component/page that’s loading with `aria-busy=true`.

I hope this helps

**Comment by OfficerHalf** [comment]
It does. I always (regrettably) forget to think about accessibility. Maybe something can be added to the docs to clarify? I can try and cobble a PR together from what you said here.

**Comment by segunadebayo** [comment]
@OfficerHalf. Yes please, you can create a FAQ section in the docs, create a PR and I'll merge it.

Thanks
