### ISSUE TITLE
Issue with Next.js 12.0.0

### ISSUE THREAD

**Issue by alveshelio** [chakra-ui/chakra-ui#4937]
### Description

With the release of Next.js 12.0.0 which now supports ESM modules, it breaks when using with Chakra-ui

### Link to Reproduction

No need for a codesandbox

### Steps to reproduce

Follow this thread: https://github.com/vercel/next.js/issues/30330
This comment: https://github.com/vercel/next.js/issues/30330#issuecomment-952847838 explains the issue and how to fix it. 

### Chakra UI Version

1.6.9

### Browser

Brave Version 1.31.87 Chromium: 95.0.4638.54 (Official Build) (x86_64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by PabloSzx** [comment]
This issue is deeper than just dev mode not working, chakra-ui doesn't ship valid ESM modules to be executed in Node.js, which means that when a third party library that does try to import chakra-ui from an ESM module it just breaks
