### ISSUE TITLE
  <MenuItemOption> component props isChecked={true} not working

### ISSUE THREAD

**Issue by prathameshpbhat** [chakra-ui/chakra-ui#4945]
### Description

I am trying to dynamically  check the checkbox of MenuItemOption

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-menu-wont-close-forked-j0pgd?file=/src/App.js

### Steps to reproduce

1.Create chakra Menu 
2.Menu ->MenuList->MenuOptionGroup->MenuItemOption
3. Set MenuOptionGroup type as checkbox
4.  Make isChecked true for particular option(it fails here)

### Chakra UI Version

1.6.10

### Browser

chrome 93

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I am trying to dynamically  check the checkbox of MenuItemOption,By setting isChecked props as true, having <MenuOptionGroup> component as parent. i have already check https://github.com/chakra-ui/chakra-ui/pull/4676 but the problem has not been resolved.

**Comment by segunadebayo** [comment]
Hi @prathameshpbhat,

The checking/unchecking behavior of a `MenuItemOption` should be handled by `MenuOptionGroup`. 

Here's a working solution:
https://codesandbox.io/s/chakra-ui-menu-wont-close-forked-jjrr0?file=/src/App.js
