### ISSUE TITLE
dynamic focus on Input doesn't enables the focus styles on input

### ISSUE THREAD

**Issue by nilavrusty** [chakra-ui/chakra-ui#4948]
### Description

ref.current.focus() , it scrolls the UI to the component but focus styles are not there, wont understand its focused

### Link to Reproduction

https://codesandbox.io

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

1.6.8

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Please follow the issue template as we're not able to act on issues that are lacking important information.
