### ISSUE TITLE
Investigate bloated bundle size for Checkbox

### ISSUE THREAD

**Issue by cschroeter** [chakra-ui/chakra-ui#4958]
### Description

When I add a Checkbox to my App, I don't expect the bundle size to increase by 100kb

### Link to Reproduction

https://codesandbox.io/s/hungry-water-uhrnv?file=/src/index.tsx

### Steps to reproduce

`yarn create react-app my-app --template typescript`

Delete all the bloatware and than add Chakra UI

`arn add yarn add @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^4`

```tsx
import { Button, ChakraProvider } from "@chakra-ui/react";
import React from "react";

function App() {
  return (
    <ChakraProvider>
      <Button>Hello World</Button>
    </ChakraProvider>
  );
}

export default App;
```
**291K** 2.747da5cd.chunk.js

```tsx
import { Button, ChakraProvider, Checkbox } from "@chakra-ui/react";
import React from "react";

function App() {
  return (
    <ChakraProvider>
      <Button>Hello World</Button>
      <Checkbox>Hi</Checkbox>
    </ChakraProvider>
  );
}

export default App;
```
**391K** 2.eb16164b.chunk.js

### Chakra UI Version

Latest

### Browser

-

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by noyanyan** [comment]
I analyzed the bundle size in Next.js. Here is my [Repo](https://github.com/noyanyan/chakra-checkbox-bundle-issue).
(I couldn't figure out how to do this with CRA.)

without Checkbox
![スクリーンショット (13)](https://user-images.githubusercontent.com/63000297/139605678-5551bc56-ca21-4699-92b2-08e5c2c2fd3a.png)

with Checkbox
![スクリーンショット (12)](https://user-images.githubusercontent.com/63000297/139605687-6815b1d0-dbc6-42f4-812d-1cf1960cf557.png)

**Comment by noyanyan** [comment]
When I displayed the contents of the concatenated modules, I found that framer motion was the cause of the problem.

![スクリーンショット (14)](https://user-images.githubusercontent.com/63000297/139605990-9124956c-5712-467f-8c98-a97effd98b50.png)

**Comment by segunadebayo** [comment]
Based on the investigations we've done so far. Framer motion is the key element of the bloated bundle size.

We'll look into optimizing it in the next major. Thanks for bringing this up!

**Comment by Anakin100100** [comment]
@segunadebayo has this been addressed at this time. I'm still experiencing the issue now.
