### ISSUE TITLE
Request to add an additional example on documentation for PopoverTrigger component

### ISSUE THREAD

**Issue by PSalaun** [chakra-ui/chakra-ui#496]
Here is a suggestion of improving documentation for helping people like me that are not yet that experienced with React, with using Popover.

**Is your feature request related to a problem? Please describe.**
I've been trying to pass my custom component as a child of `PopoverTrigger`, and struggled for 1 hour making it work, because I was focused on the ref forwarding as it was highlighted in the doc (and I'd never used ref), but not passing all the props from the parent.

**Describe the solution you'd like**
Adding a new example, showing how to pass a custom React Component wrapping a simple `a` tag.

**Describe alternatives you've considered**
Adding an additional sentence to the Basic Usage paragraph, reminding that you need to pass all the props down to the target component.

Thank you for creating this library, I love it so far, and adding it to a codebase already using ThemeUI was a breeze.

**Comment by segunadebayo** [comment]
Thank for this @PSalaun.

We'll improve the documentation and ensure we address this to save time for other users.

**Comment by tony** [comment]
@segunadebayo I was initially looking for something else on the tracker, but saw this, and realized, you're so friendly and professional. Thank you for this project. Sponsored you on Patreon 😊 

Thank you for being so courteous on these issues!

**Comment by segunadebayo** [comment]
@tony Amazing! Thank you for sponsoring me on Patreon 💖 

This means a lot and will go a long way.
