### ISSUE TITLE
Multiple transitions at once

### ISSUE THREAD

**Issue by PetrovStefan** [chakra-ui/chakra-ui#4962]
### Subject

Transition

### Description

Is there a way to set different transition speeds for different properties on the same component? For instance, this works:
transition="all 0.5s"

But if I want to set border and box-shadow at separate speeds, I can't. This doesn't work:
transition={{"box-shadow 0.5s", "border 0.2s"}}

I tried most variations, nothing does. The documentation doesn't cover it, it just mentions that transition is possible as a prop.

**Comment by noyanyan** [comment]
Giving properties as a string will solve the problem.
https://codesandbox.io/s/zealous-pare-y4xyz?file=/src/index.tsx

**Comment by noyanyan** [comment]
Sorry, You are taking about document? I agree document will cover it.
So I've looked at a few pages, [style-props](https://chakra-ui.com/docs/features/style-props) is the only page I could find.

Would it be user-friendly to describe how to give transition properties on the transitions page?

**Comment by PetrovStefan** [comment]
Yes, I believe it would be. What I wanted to ask was whether you could group up transition effects for multiple properties in one place. Say I have a Flex, and I want to set a different transitions for border, boxShadow, and background color. How would I do that in a single transition prop for the Flex?

**Comment by PetrovStefan** [comment]
Nevermind, just saw the sandbox. It wouldn't load before. It's exactly what I was looking for. Yes, it would help to have it in the docs though.
