### ISSUE TITLE
Request to make <Stack> props `isInline` & `isReverse` accept an array for responsive style

### ISSUE THREAD

**Issue by Calvein** [chakra-ui/chakra-ui#497]
I would love if those props could be used "responsively", in the meantime, I created an hook to get the current breakpoint and I use it to set the correct value, it works well because they are boolean values but I don't think it's generic enough. Here's how I use it:

```jsx
const MyComponent = () => {
  const currentBreakpoint = useCurrentBreakpoint()

  return (
    <Stack isInline={[false, true, true, true][currentBreakpoint]}>
      <Box>1</Box>
      <Box>2</Box>
    </Stack>
  )
}
```

And here's a working example, with the hook:

https://codesandbox.io/s/chakra-ui-isinline-responsive-scfye

If you reckon that would work, I'd gladly make a PR :)

**Comment by segunadebayo** [comment]
@Calvein , I'm glad you found a walkaround for this.

We've accounted for this in preparation for the next release. We're deprecating `isInline` prop in favour of `direction`, and you will be able to pass responsive `direction` values.

Sounds good?

**Comment by Calvein** [comment]
Sounds even better than good 😄

**Comment by julians300** [comment]
When is this responsive update planned to get released?

**Comment by tjbo** [comment]
This worked for me, not sure if it's new... but works very well.
  
  https://chakra-ui.com/docs/hooks/use-breakpoint-value
  
  const isDesktop = useBreakpointValue({ base: false, md: true })
