### ISSUE TITLE
RangeSlider throw error - Cannot read properties of undefined

### ISSUE THREAD

**Issue by weiliao715** [chakra-ui/chakra-ui#4981]
### Description

When I using RangSlider with 3 thumbs, an TypeError is thrown when two of the thumbs are stacked. 

### Link to Reproduction

https://codesandbox.io/s/charkra-ui-rangeslider-0sjiz?file=/src/index.js

### Steps to reproduce

1. Create RangSlider with 3 thumbs. The index 0 and index 1 are stacked.

![image](https://user-images.githubusercontent.com/54960477/139886149-d275ed31-8099-44a3-8255-c7a9add3a275.png)

2. Move the thumb at index 2

3. See error

![image](https://user-images.githubusercontent.com/54960477/139899260-f5bdfca4-296c-4660-bc01-ae42d9390c9b.png)

### Chakra UI Version

1.6.10

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

I investigated the use-range-slider file and add few console log

![2](https://user-images.githubusercontent.com/54960477/139900088-afc0624f-8fda-4eae-8297-005d609b3804.PNG)

I discovered the error came from index exceeds the range. Suppose I have only index 0, 1, 2, we should not get to index 3.

![1](https://user-images.githubusercontent.com/54960477/139887959-69324c55-3851-4baf-911a-0f9e008c8e04.PNG)

Below function in use-range-slider  causes the index exceeds the range.

![3](https://user-images.githubusercontent.com/54960477/139900292-febe3a98-8699-4dfd-adcd-5a5949d26944.PNG)

**Comment by anubra266** [comment]
Hi @weiliao715 do you still have this issue? Can't see any logged errors in your codesandbox reproduction.

**Comment by weiliao715** [comment]
Hi @anubra266 the issue still persists. You need to move the thumb on the right side to trigger the error. Make sure you click on the left half of the circular thumb.

**Comment by weiliao715** [comment]
@anubra266 sorry, click on the right half of the circular thumb

**Comment by weiliao715** [comment]
@anubra266, @burhanuday thanks for helping me out with this error.

I found another problem related to range slider, and I opened a new error #5041
