### ISSUE TITLE
Chakra 1.6.12 now features color mode issues (now dark by default, even though docs promise light by default. Also, overrides appear not to work)

### ISSUE THREAD

**Issue by Robbie-Cook** [chakra-ui/chakra-ui#4987]
### Description

Docs tell me that Chakra will be light color mode: https://chakra-ui.com/docs/features/color-mode#setup, but the default is your system color mode. Overrides appear to not work

### Link to Reproduction

https://codesandbox.io/s/dank-cloud-rymzh?file=/src/App.tsx

### Steps to reproduce

1. Install latest Chakra (1.6.12)
2. Set your system color mode to 'dark'
3. Wrap something in a `<ChakraProvider/>`
4. Notice that it is all black now, instead of light: 
![image](https://user-images.githubusercontent.com/13477291/140237795-6634bba7-933b-4fc0-955b-5b19a7bc8b1f.png)

Even if you set: 
```
const config = {
  initialColorMode: "light",
  useSystemColorMode: false,
}
```
 this now does not override the color mode. **It always takes your system color mode**

### Chakra UI Version

1.6.12

### Browser

All

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by nemosupremo** [comment]
Not sure if this is related, but 1.6.12, but setting `initialColorMode="dark"` now also produces the light mode theme

**Comment by CarlOmega** [comment]
@nemosupremo It seems to always take system color mode. So you must have light mode on your system and it just ignores the config.

**Comment by Robbie-Cook** [comment]
This looks sus: https://github.com/chakra-ui/chakra-ui/pull/4634/files#r742456342

**Comment by Robbie-Cook** [comment]
@CarlOmega  is right I think. Overrides also not working 4 me: https://codesandbox.io/s/romantic-chatelet-383kf?file=/src/App.tsx:251-256

**Comment by Robbie-Cook** [comment]
We love Chakra, btw. Thanks for all your hard work on this amazing framework

**Comment by jnsdls** [comment]
yep, same issues here, worked around it for now by explicitly wrapping the app with a `<LightMode>` (directly after the provider) - since I only want light mode for right now

**Comment by takethefake** [comment]
Will check that we can get a fix asap

**Comment by zxhycxq** [comment]
very good!, hope more theme.thanks.

**Comment by kasim444** [comment]
I'm having the same problem with the v1.6.12 version.

**Comment by michaelmarziani** [comment]
I'm evaluating Chakra-UI this weekend and have been dealing with this issue while trying to set up the framework per the documentation.

I'm worried that bugs like this are able to find their way into release versions.

Does the Chakra-UI project have any kind of automated testing to prevent this?

**Comment by takethefake** [comment]
Hey @michaelmarziani sorry to hear this - I hope this doesn't affect your relation to chakra-ui

We have a lot of automated tests in chakra UI unfortunately in this case the bug slipped through. We will continue to improve our performance in the review process and will find a way to ensure that code changes are tested accordingly.

Also, we are currently working to establish a `next` tag which is based on the current main. This will give us an extra level of security to avoid that something like this happens.

**Comment by michaelmarziani** [comment]
@takethefake I appreciate your comments and info. I used the workaround provided by @jnsdls (thank you!) and am proceeding with creating pages using Chakra. I think it speaks highly of Chakra that it appears to have an engaged developer community around it. Cheers!

**Comment by anubra266** [comment]
@Robbie-Cook the issue was auto closed because the PR has been merged. Just wait for the next release.

**Comment by stefvw93** [comment]
For people who can't wait for the next release for some reason, I temporarily solved it like this:

```
function ForceLightMode(props: { children: JSX.Element }) {
  const { colorMode, toggleColorMode } = useColorMode();

  useEffect(() => {
    if (colorMode === "light") return;
    toggleColorMode();
  }, [colorMode]);

  return props.children;
}
```

```
export function App() {
  return (
    <ChakraProvider theme={theme}>
      <ForceLightMode>
        ...
      </ForceLightMode>
    </ChakraProvider>
  );
}
```

**Comment by HarryAustin** [comment]
Had similiar problem too. I resolved mine by deleting the color mode key on localstorage. Tho mine's not because of a bug from chakra. 

When i had everything set up and running, i toggled the button to dark mode before re editing my App.js on react. 

I have a well detailed explanation on a Twitter thread.  https://twitter.com/small_techy/status/1610901026747604996?t=IPRAhFtV1BR3ebogpHkGWQ&s=19
