### ISSUE TITLE
Export useFormControl from lib

### ISSUE THREAD

**Issue by liokm** [chakra-ui/chakra-ui#499]
**Is your feature request related to a problem? Please describe.**
When using `FormControl` together with customized input components which also want to accept `isDisabled` etc from `FormControlContext`, we can not `useFormControl` because it is not exported from the lib.

**Describe the solution you'd like**
- Export `useFormControl` for customized input components to take advantage of it.
- Document it

**Describe alternatives you've considered**
Now I am passing `isDisabled` flags manually.

Thanks

**Comment by segunadebayo** [comment]
Hi @liokm ,

Thanks for the issue. We're currently looking into this and will release a patch shortly

**Comment by segunadebayo** [comment]
This has been fixed. Expect a patch release soon
