### ISSUE TITLE
Bundle all the packages

### ISSUE THREAD

**Issue by cschroeter** [chakra-ui/chakra-ui#4990]
### Description

Benefits for bundling libraries:

- less kB transferred via wire
- faster install time
- faster bundling time in apps (webpack/rollup has to process only 1 files instead of N)
- faster tests execution (cold starts can be painfully slow especially if you’re using jest and your app is massive)
- better tree-shaking

Source: https://medium.com/@martin_hotell/typescript-library-tips-rollup-your-types-995153cc81c7

### Problem Statement/Justification

The advantages described in the description

### Proposed Solution or API

ESBuild

**Comment by segunadebayo** [comment]
Hi @cschroeter,

Based on the conversation we had in #4956, we're switching to `preconstruct` and it bundles all exposed APIs in entry points to a single `esm` and `cjs` file.

I actually had an issue open about using `esbuild` but I closed it after the conversation. Thanks for sharing that article.

**Comment by cschroeter** [comment]
Any reason why preconstruct (rollup) over esbuild?
