### ISSUE TITLE
Custom cursors

### ISSUE THREAD

**Issue by anoushk1234** [chakra-ui/chakra-ui#4994]
### Description

It's a new design trend, custom cursors on the website that override the default one like this
![image](https://user-images.githubusercontent.com/32778608/140386171-e0a00338-08ed-42fc-a257-fafa703ae7c7.png)

### Problem Statement/Justification

A lot of new and upcoming web3 websites are adopting it, u might wanna implement it to stay relevant among that crowd

### Proposed Solution or API

https://hyperound.com/ this is one website that has implemented it

**Comment by segunadebayo** [comment]
Hi @anoushk1234,

Thanks for sharing this cool idea. I don't think this is something that should be added to the core of Chakra UI. I think it fits better as a recipe or a CodeSandbox for others to use if they want.

That said if anyone gets around building this cool idea. I'd love to promote or share it.

Cheers.
