### ISSUE TITLE
Code editor leading to keyboard trap

### ISSUE THREAD

**Issue by stephan281094** [chakra-ui/chakra-ui#5]
Hi there! Really impressive work! 🙌 

One thing I noticed when navigating the [chakra-ui.com](chakra-ui.com) website using my keyboard is that once the code editor ("editable example") gets focus, it seems impossible to get out with the cursor. This is because the editor recognises the "tab" key as a way to change the indentation. It would be nice to escape this keyboard trap somehow.

A suggestion would be to allow the "escape" key to move the focus out of the "edit" mode (suggested by slugolicious [here](https://stackoverflow.com/a/53910297/1772418)). The spec might be helpful: https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-trapping.html

**Comment by devanshj** [comment]
@segunadebayo Can you update `react-live` the PR is published now. I would have sent a PR to do that but I'm finding issues upgrading it with yarn.

**Comment by segunadebayo** [comment]
@devanshj, I've updated `react-live` and I see that `Esc` moves focus out of the editor.

Thanks for your work to resolve this issue @devanshj and @stephan281094. I'll update the docs with the next patch release.
