### ISSUE TITLE
[RadioGroup] Usage of numeric values is broken

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#50]
I tried using `number | undefined` type values with `RadioGroup`:

```tsx
const [selectedChoiceID, setSelectedChoiceID] = useState<number>();
return (
  <RadioGroup
    value={selectedChoiceID}
    onChange={event => {
      // Input values are stored as strings under the hood
      // Thus, a conversion back to number is necessary
      const choiceID = Number(event.target.value);
      setSelectedChoiceID(choiceID);
    }}
    spacing={0}
  >
    <Radio value={1}>A</Radio>
    <Radio value={2}>B</Radio>
    <Radio value={3}>C</Radio>
  </RadioGroup>
);
```

Unfortunately, as `value` attributes are stored as strings under the hood, the code above does not work: None of the radio buttons can be checked. However, if I explicitly convert `selectedChoiceID` to `string` with the `value={String(selectedChoiceID)}` syntax, the example above works flawlessly.

I would suggest explicitly asking for `string` values in TypeScript, as input field attributes are stored as strings under the hood (see the conversion necessary in the `onChange` callback).

**Comment by tioluwani94** [comment]
Hi @kripod , thanks for this feedback. We'll look into this.

**Comment by tioluwani94** [comment]
Hi @kripod,

This issue has been fixed and a patch will be released soon.

Also, to use the `RadioGroup` component in a controlled state, an initial value should be passed as shown below for example when using `number` values:

```jsx
const [selectedChoiceID, setSelectedChoiceID] = useState<number>(0);
return (
  <RadioGroup
    value={selectedChoiceID}
    onChange={event => {
      const choiceID = Number(event.target.value);
      setSelectedChoiceID(choiceID);
    }}
    spacing={0}
  >
    <Radio value={1}>A</Radio>
    <Radio value={2}>B</Radio>
    <Radio value={3}>C</Radio>
  </RadioGroup>
);
```

or this when using `string` values

```jsx
const [selectedChoiceID, setSelectedChoiceID] = useState<string>("");
return (
  <RadioGroup
    value={selectedChoiceID}
    onChange={event => {
      const choiceID =event.target.value;
      setSelectedChoiceID(choiceID);
    }}
    spacing={0}
  >
    <Radio value="1">A</Radio>
    <Radio value="2">B</Radio>
    <Radio value="3">C</Radio>
  </RadioGroup>
);
```

**Comment by kaurkaelep** [comment]
I don't know if its valid to reopen this issue, but when I tried to use 0 as a <Radio /> value, it broke.

https://codesandbox.io/s/chakra-ui-radiogroup-error-brbfj?file=/src/index.js

**Comment by with-heart** [comment]
@kaurkaelep This issue is pretty old. See this more recent response: https://github.com/chakra-ui/chakra-ui/issues/2931#issuecomment-761758604
