### ISSUE TITLE
[Docs] GitHub Button in Docs Header not responsive

### ISSUE THREAD

**Issue by jackleslie** [chakra-ui/chakra-ui#501]
**Describe the bug**
When viewing the docs at [chakra-ui.com](https://chakra-ui.com) on mobile, the GitHub button showing the number of stars isn't responsive and forces the other header buttons out of the view.

![Before](https://user-images.githubusercontent.com/22222776/76799674-dfdb4c80-67c9-11ea-885b-68ad69def01d.PNG)

**Expected Behavior**
The header should look nice on mobile, without the badge being too big and forcing other buttons out of the view.

**To Reproduce**
1. Go to [chakra-ui.com](https://chakra-ui.com) on mobile
2. See header in nav bar

**Suggested solution(s)**
The `GitHubButton` has a `Box` parent, so using responsive props we can simply add the following to `Box`:

```
display={["none", "flex"]}
```

This removes any need to do any more mobile detection or CSS. Open to hear other suggestions though as it's a bit annoying to have to declare `flex` explicitly.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Safari
 - Version: iOS 13.3, iPhone XS

**Additional context**
Perhaps this could be put in the footer instead?

**Comment by segunadebayo** [comment]
Thanks for this @jackleslie.

I've reviewed your PR and here's my thought. How about we move the logo to the left? This will allow some room for the Github button?

**Comment by jackleslie** [comment]
@segunadebayo Yes that works, however it looks a bit squeezed even when the GitHub button is set to `small`. We could hide the star count and that would solve it quite quickly - are you wanting the star count to be visible? If so then I'll keep tinkering.

**Comment by segunadebayo** [comment]
Ideally, it'll be good to have the star count show, give Chakra more credibility 😀. However, if there's no room for it, you can simply remove the count.

Thanks for helping with this.

**Comment by jackleslie** [comment]
@segunadebayo How about moving it down the page on mobile?

![star_moved](https://user-images.githubusercontent.com/22222776/77228721-1bd33080-6b81-11ea-8fef-18a9cec534a3.PNG)

That's where [material-ui](https://material-ui.com/) has theirs.

**Comment by segunadebayo** [comment]
@jackleslie, sure that's fine as well. Kindly submit a PR

**Comment by jackleslie** [comment]
@segunadebayo force pushed to the same PR #502
