### ISSUE TITLE
When select Wrapping MenuItemOption component does not trigger onChange of MenuOptionGroup.

### ISSUE THREAD

**Issue by u-yas** [chakra-ui/chakra-ui#5011]
### Description

I wanted to style-design the MenuItemOption component and create a new wrapped component. However, onChange of MenuOptionGroup is not triggered when trying to use wrapped menuItemOption

### Link to Reproduction

https://codesandbox.io/s/charming-kilby-n6x63?file=/src/index.tsx

### Steps to reproduce

I have two components written in codesandox. In both cases, it is expected that alert will be activated when a menu item is selected.
The first is a menu component that reproduces a bug, which does not launch alert no matter which menu you select.
The second uses a component that imports MenuItemOption directly from "@chakra-ui/react". That  works fine

### Chakra UI Version

1.6.12

### Browser

All major browsers

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

May be related to the following issues　#3171

**Comment by u-yas** [comment]
I was able to fix this bug. I found that onChange didn't work properly because of this code. (https://github.com/chakra-ui/chakra-ui/blob/main/packages/menu/src/use-menu.ts#L725-L733 )
If you do not create a component with React.FC, wrap the component with forwardRef in @ chakra-ui / systems, and give the "MenuItemOption" id to the component that has been wrapped, it will work normally.

Leave the component wrapped in the correct way in this sandbox 
https://codesandbox.io/s/charming-kilby-n6x63?file=/src/index.tsx

**Comment by BenjaminLMI** [comment]
> I was able to fix this bug. I found that onChange didn't work properly because of this code. (https://github.com/chakra-ui/chakra-ui/blob/main/packages/menu/src/use-menu.ts#L725-L733 ) If you do not create a component with React.FC, wrap the component with forwardRef in @ chakra-ui / systems, and give the "MenuItemOption" id to the component that has been wrapped, it will work normally.
> 
> Leave the component wrapped in the correct way in this sandbox https://codesandbox.io/s/charming-kilby-n6x63?file=/src/index.tsx

This works only if your wrapped component is a direct child of <MenuOptionGroup>. If you have some HStack, Flex, Box, Tooltip components etc. inside the <MenuOptionGroup> for styling purposes for example and your wrapped components is a child of those, it won't work. The only solution to bypass this limitation is to use the onClick handler for the MenuItemOption instead of the onChange handler of the MenuOptionGroup.
