### ISSUE TITLE
[Switch component] Change thumb style when disabled

### ISSUE THREAD

**Issue by shiranZe** [chakra-ui/chakra-ui#5018]
### Description

In the Switch component, be able to style the thumb (like bg color) by passing the `_disabled` attribute to the baseStyleThumb

### Problem Statement/Justification

disabled mode should effect not only the tracker but also in the switch thumb

### Proposed Solution or API

<img width="1174" alt="Screen Shot 2021-11-07 at 11 03 08" src="https://user-images.githubusercontent.com/40235967/140638897-f43ae309-70ae-4500-8748-2583fc6d71e1.png">

**Comment by anubra266** [comment]
Hi @shiranZe please reopen with a codesandbox reproduction
