### ISSUE TITLE
Toast keeps staying there as long as mouse hovered on it

### ISSUE THREAD

**Issue by Shouduo** [chakra-ui/chakra-ui#5022]
### Description

Hi, 
I found that a toast would clear its delay timer when hovered, and reset when mouse leave. 
I knew it is feature, but if only we could turn if on and off conditionally.

### Problem Statement/Justification

Sometimes user left their mouse on the area where toast comes out, which makes toast staying there until user move mouse away. it's not that elegant in some scenaior.

### Proposed Solution or API

Just add a boolean prop for toast.

**Comment by cschroeter** [comment]
Thank you for reporting this issue.
As you have already correctly recognized, it is a feature. But it should be possible to force close the toast using 

```tsx
const { close } = useToast()
``` 

Thanks for supporting Chakra UI :heart:
Happy Hacking ✌️

**Comment by Shouduo** [comment]
@cschroeter 
Thank you for the quick reply.
It's nice that toast can be closed imperatively via close(), 
but in the scenaior I described above, there's no reason for me to set a timer outside the component since prop 'duration' is set and works well inside.
Now my solution is to add a prop 'isPersistable' for Toast which conditionally controls onHoverStart & onHoverEnd.

![Snipaste_2021-11-08_17-09-29](https://user-images.githubusercontent.com/12470371/140714764-2d4c7bfb-e6e0-4530-8db1-03b126cc2eab.png)

Does it a good idea to implicate in chakra/ui repo?
