### ISSUE TITLE
@chakra-ui/cli@1.5.x breaks with certain module aliases

### ISSUE THREAD

**Issue by anilanar** [chakra-ui/chakra-ui#5023]
### Description

When I use a module alias in tsconfig that points to a typing but not a concrete module, @chakra-ui/cli breaks

### Link to Reproduction

https://github.com/anilanar/chakra-cli-reproduction

### Steps to reproduce

1. `git clone https://github.com/anilanar/chakra-cli-reproduction`
2. `cd chakra-cli-reproduction`
3. `yarn`

### Chakra UI Version

1.6.12 

### Chakra-CLI Version

1.5.3

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by anubra266** [comment]
@anilanar That's an empty repo

**Comment by anilanar** [comment]
@anubra266 My bad, pushed.

**Comment by cschroeter** [comment]
Why not just add a resollution to the corect react version?

**Comment by anilanar** [comment]
@cschroeter We don't necessarily alias them to `node_modules`, sometimes we alias them to local files.
