### ISSUE TITLE
useStyles: `styles` is undefined. Seems you forgot to wrap the components in `<StylesProvider />`

### ISSUE THREAD

**Issue by PeterEckIII** [chakra-ui/chakra-ui#5028]
### Description

Using Next.js, when I run `next dev` and visit a pre-rendered, static page it gives the above error, when I expect it to successfully prerender these pages and allow visits. This also occurs when running `next build`. When the build process gets to these pages it errors out with the message in the issue title.

### Link to Reproduction

https://codesandbox.io/s/tender-heisenberg-rpxif?file=/pages/_app.js

### Steps to reproduce

Unfortunately, I am unable to reproduce my issue in a CodeSandbox for some reason. Please let me know if there's a way I can share access to my repository for a reproduction of the issue.

The issue stems from either running `yarn build` and observing the pages trying to pre-render, or running `yarn dev` and visiting the pages that are showing this issue. The issue seems to be happening on one specific type of page with a dynamic URL (e.g. `/games/[id]`) that is calling `getStaticProps`. On that page, I am calling the following Chakra UI components:
Flex, Box, Heading, Image, Text, Table, Thead, Th, Tbody, Tr, Td.

I have also tried wrapping the entire app in a `<StylesProvider>` component like so, to no avail:
```
const MyApp = ({ Component, pageProps }) => {
    const styles = useStyles();
    return (
        <StylesProvider value={styles}>
            <ChakraProvider theme={theme}>
                 <Component { ...pageProps } />
            </ChakraProvider>
        </StylesProvider>
    )
}
```

`package.json`
```
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "test": "jest --watch --coverage --colors",
    "lint": "next lint",
    "cypress": "cypress open",
    "cypress:h": "cypress run",
    "e2e": "start-server-and-test start http://localhost:3000 cypress",
    "e2e:headless": "start-server-and-test start http://localhost:3000 cypress:headless",
    "sb": "start-storybook -p 4000",
    "sb:build": "build-storybook"
  },
  "dependencies": {
    "@aws-sdk/client-cognito-identity-provider": "^3.39.0",
    "@badrap/bar-of-progress": "^0.1.2",
    "@chakra-ui/icons": "^1.0.15",
    "@chakra-ui/react": "^1.6.8",
    "@emotion/core": "^11.0.0",
    "@emotion/react": "^11.4.1",
    "@emotion/styled": "^11.3.0",
    "@fontsource/roboto": "^4.5.1",
    "aws-amplify": "^4.2.9",
    "date-fns": "^2.23.0",
    "date-fns-tz": "^1.1.6",
    "dotenv": "^10.0.0",
    "emotion-theming": "^11.0.0",
    "formik": "^2.2.9",
    "framer-motion": "^4.1.17",
    "graphql": "^15.5.3",
    "graphql-tag": "^2.12.5",
    "next": "11.1.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-spinners": "^0.11.0",
    "react-table": "^7.7.0",
    "react-toastify": "^8.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.16.0",
    "@cypress/react": "^5.10.1",
    "@cypress/webpack-dev-server": "^1.7.0",
    "@snek-at/storybook-addon-chakra-ui": "^1.0.0-beta.1",
    "@storybook/addon-actions": "^6.3.12",
    "@storybook/addon-controls": "^6.3.12",
    "@storybook/addon-docs": "^6.3.12",
    "@storybook/addon-essentials": "^6.3.12",
    "@storybook/addon-links": "^6.3.12",
    "@storybook/addon-storyshots": "^6.3.12",
    "@storybook/addon-viewport": "^6.3.12",
    "@storybook/react": "^6.3.12",
    "@testing-library/cypress": "^8.0.1",
    "@testing-library/dom": "^8.10.1",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.0.2",
    "@types/testing-library__cypress": "^5.0.9",
    "babel-jest": "^27.3.1",
    "babel-loader": "^8.2.3",
    "cypress": "^8.6.0",
    "cypress-localstorage-commands": "^1.5.0",
    "eslint": "^8.1.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^27.3.1",
    "react-test-renderer": "^17.0.2",
    "start-server-and-test": "^1.14.0"
  }
}

```

The easiest way to reproduce the issue is probably to fork and clone my repo and run `yarn build` to observe the problems. Again, please let me know if someone is able to be granted access. Happy to do so.

### Chakra UI Version

1.6.8 (@chakra-ui/react)

### Browser

Google Chrome 95

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This error seemingly showed up overnight. I've never used `<StylesProvider>` or `useStyles` in my app and was previously able to build without issue. The only changes I have made to the Chakra-UI setup since was setting it up with Storybook. However, the Storybook setup is in a different file than _app.js, so I can't see how this would be relevant. 

I've referenced the following:
* https://chakra-ui.com/docs/theming/component-style
* https://github.com/chakra-ui/chakra-ui/issues/906
* https://github.com/chakra-ui/chakra-ui/issues/2001
which all mention either `useStyles` or `<StyleProvider>` but none seem to be related to my issue. I am not using Component Styling in the way described in these resources.

**Comment by primos63** [comment]
Your CodeSandbox is using the latest Next JS version v12 and @chakra-ui/react v1.6.12. I changed them to v11.1.2 and v1.6.8. The CSB fails with `TypeError: Cannot read property 'gamesByDate' of undefined`.

**Comment by PeterEckIII** [comment]
Please disregard. It turned out I was importing some of the Table components from `@chakra-ui/table` instead of `@chakra-ui/react`. I corrected this and was able to build sucessfully.
