### ISSUE TITLE
colorScheme prop on Switch component appending extra characters

### ISSUE THREAD

**Issue by mnpkoerner** [chakra-ui/chakra-ui#5029]
### Description

When I passed in a value to colorScheme prop on the Switch component, it behaves inconsistently. 

### Link to Reproduction

https://codesandbox.io/s/practical-wiles-9ysdg

### Steps to reproduce

1. Import two of the Switch components to a page
2. On one, with the colorScheme prop pass in the string 'red'
3. On the second, pass it 'red.300'
4. Both should render different reds per the docs/built in colors except the 'red.300' will have either '.200' appended to the end or '.500', the component will try to render 'red.300.200' and default to gray

### Chakra UI Version

1.3.4

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This only happens with the colorScheme prop. The bgColor prop will render any color (both built in and custom colors) without this issue. But, if you attempt to manually pass in a color to the Switch with colorScheme (from a custom color theme or by using a hex code), the Switch will default to grey.

**Comment by primos63** [comment]
The `colorScheme` prop only takes the color name and not the level. It also does not take a hex value as it appends the level to the color to look it up in the theme.colors. `colorScheme` was previous called `variantColor` the reason for it
> Reason: We renamed this prop to make it easier to understand that this prop represents a visual color scheme, not a css color attribute.

**Comment by anubra266** [comment]
You already have colors defined in your theme, green, red, and many more, including your custom defined colors(optional). The switch looks up this colors and takes the level at those appended numbers by default, so if you pass red.300, it assumes red.300 is just a color. If you want a different behavior, you can always extend the theme and change this. Happy coding @mnpkoerner

**Comment by mnpkoerner** [comment]
Thanks for the explanation! @primos63 and @anubra266, makes a ton of sense!
