### ISSUE TITLE
Request to organize components docs into groups

### ISSUE THREAD

**Issue by timkindberg** [chakra-ui/chakra-ui#503]
I think it may be easier to browse the component docs if they were organized into groups in the left hand pane:
- Typography
- Layout (Box, Grid, Simple Grid, etc)
- Input / Form (Form, all the inputs, ControlBox)
- Disclosures ?? (Modal, Drawer, Popover, Tooltip)
- More (not everything needs a well named group)

**Comment by timkindberg** [comment]
BTW We have decided to Chakra here at Vndly! Thank you so much for the amazing library!!

**Comment by segunadebayo** [comment]
It sounds like a good idea @timkindberg. We'll look into this in preparation for the next release docs.

**Comment by with-heart** [comment]
Hoping to release the new docs under `next.chakra-ui.com` soon so we can finally consider this closed! The new docs are organized into "theming", "layout", "form", "components", and "utilities" sections.

**Comment by with-heart** [comment]
[next.chakra-ui.com](https://next.chakra-ui.com/) is out! Considering this closed
