### ISSUE TITLE
[Slider]thumb is incorrect position when the slider max value is "Infinity"

### ISSUE THREAD

**Issue by joos0701** [chakra-ui/chakra-ui#5030]
### Description

My case is this:
`<Slider defaultValue="5" max="Infinity" min="0" > ... </Slider>`

In this case, thumb is located in min position.
How can I change the thumb position?

### Problem Statement/Justification

![image](https://user-images.githubusercontent.com/67673559/140845363-8e3e501b-079c-48e8-b65c-d20657898d58.png)

### Proposed Solution or API

`<Slider defaultValue="5" max="Infinity" min="0" > ... </Slider>`

**Comment by primos63** [comment]
This case does not make sense. How does one represent the halfway point with a max set to Infinity? If anything the issue should be that the value is allowed rather than rejected. A min value of -Infinity should also be rejected.

**Comment by anubra266** [comment]
Hi @joos0701 could you give a use case for your scenario.
