### ISSUE TITLE
Unable to handle esc key on modal for different action than closing a modal

### ISSUE THREAD

**Issue by piotrpawlik** [chakra-ui/chakra-ui#5032]
### Description

I want to handle other action on modal for esc key. I'd expect modal to allow me to do that when closeOnEsc={false} is used. However, only Esc handler is triggered even when closeOnEsc={false} is used.

### Link to Reproduction

(open console to see logs showing the issue)
https://codesandbox.io/s/interesting-nobel-3m2bl?file=/src/modal.js

### Steps to reproduce

1. Use Modal with `closeOnEsc={false}` option
2. Define custom keydown event listener which handles esc too
3. When Modal is opened custom esc handler is not called

### Chakra UI Version

1.6.10

### Browser

Google Chrome 95

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This is needed because I have an action to unfocus `div` element on esc and pressing esc only when this element is not in focus should close the modal.

**Comment by anubra266** [comment]
@piotrpawlik your custom escape event works if the modal is closed. When the modal is open, the modal is focused and then you can handle escape events in the `onEsc` prop. Could you give a use case that this pattern would not work with please?

**Comment by piotrpawlik** [comment]
@anubra266 Good point, I improved codesandbox to show the issue in a better way https://codesandbox.io/s/interesting-nobel-3m2bl?file=/src/modal.js

Steps:
1. Click on "focus on this - outside moda"
2. Press 'esc'
3. There is "custom esc outside of modal" logged in console
4. Open modal
5. Press 'esc'
6. There is "esc from modal" logged in console, I'd expect nothing to be logged into console as `closeOnEsc={false}` is used
7. Press on "focus on this - in modal"
8. There is still "esc from modal" logged in console, I'd expect "custom esc inside modal" to be logged into console

**Comment by anubra266** [comment]
@piotrpawlik `closeOnEsc` has nothing to do with the `onEsc` prop. `closeOnEsc` is for those who don't want the esc event to close their modals. You've seen that when the modal is open, the esc event listener from outside the modal does nothing, because of the `preventDefault` handling in the modal, so If a user wants to perform another action with the escape event, which might even have nothing to do with the modal, then the `onEsc` prop is the way. 
This would be easier, if you can produce a use real life usecase that this pattern works against, we can then navigate it together.

**Comment by anubra266** [comment]
@piotrpawlik please feel free to reopen this whenever you find a use case against the current pattern.

**Comment by coxato** [comment]
in my case I have to use `onEsc={myEscHandlerFn}` and `closeOnEsc={false}`
So I made a counter, like 
```typescript 
const [escPressedCount, setEscPressedCount] = useState(0);
```

then 

```typescript
const myEscHandlerFn = () => {
    setEscPressedCount((prev) => prev + 1);
};
```

and inside my component that it's inside the chakra modal
```typescript
useEffect(() => {
    if (escPressedCount > 0) {
     // my logic here for my custom Esc 
    }
}, [escPressedCount]);
```
