### ISSUE TITLE
Rounded Rectangle Tabs Variant

### ISSUE THREAD

**Issue by AnishDe12020** [chakra-ui/chakra-ui#5034]
### Description

The tabs feature in Chakra UI has got an option to supply in different variants. A rounded rectangle variant would be a nice touch.

### Problem Statement/Justification

This tab variant will look good and provide users with more options as far as customization goes

### Proposed Solution or API

A rounded rectangle tab variant

Example (From Headless UI docs, made with Headless UI and Tailwind CSS) - 
![image](https://user-images.githubusercontent.com/63192115/140906643-cbbade56-c191-40b7-8ab7-ba8955e9be2e.png)

**Comment by anubra266** [comment]
@AnishDe12020 are you aware you could extend the thing and add this to your project?

**Comment by anubra266** [comment]
Adding a new variant to the theme just to give it a different `borderRadius` seems unnecessary.

**Comment by anubra266** [comment]
cc @segunadebayo In case you think otherwise.

**Comment by AnishDe12020** [comment]
> @AnishDe12020 are you aware you could extend the theme and add this to your project?
> Also see this:
> ```html
> <Tabs variant="solid-rounded">
>   <TabList>
>     <Tab rounded="md">One</Tab>
>     <Tab rounded="md">Two</Tab>
>   </TabList>
>   <TabPanels>
>     <TabPanel>
>       <p>one!</p>
>     </TabPanel>
>     <TabPanel>
>       <p>two!</p>
>     </TabPanel>
>   </TabPanels>
> </Tabs>
> ```
> <img width="797" alt="CleanShot 2021-11-09 at 13 25 08@2x" src="https://user-images.githubusercontent.com/30869823/140923880-2cef382b-ce4d-4909-9a13-6ad1b13839bb.png">
> 
> 
> **NB:** You can use `borderRadius` in place of `rounded`.

Oh, I think that should do it for me. Thanks for the help!!!
