### ISSUE TITLE
[Menu] allow positioning without Popper

### ISSUE THREAD

**Issue by kristojorg** [chakra-ui/chakra-ui#5039]
### Description

Allow positioning the `Menu` component manually, without relying on Popper. In my use case, the menu is portaled into another component and positioned there. This does not work when using Popper to position the element.

### Problem Statement/Justification

I want to be able to click a button, and open a menu-like UI elsewhere on the page. Consider a button in the header for "Table of Contents" which, when clicked, opens a full-page table of contents UI in the main content area. This menu-like UI would trap focus, and allow navigation with the up/down keys, as well as allow closing with escape and/or clicking the close button. 

This component falls somewhere between multiple existing component. I will list their drawbacks below:
- `Menu` component: almost works, but is positioned with popper, which introduces problems.
- `Modal` component: also very similar, but takes up the full screen instead of one div or content area.
- `Portal` component: This is the basis for the functionality, and what I initially started using, but it lacks all of the accessibility built in to `Menu`.

Here is a video of the desired UX which I created by copying `Menu` and removing the popper:

https://user-images.githubusercontent.com/4398775/140958867-dc9f3970-ec96-4ed6-b65c-ed65ee0bde87.mov

### Proposed Solution or API

I don't have a specific proposal for how this would work. I suppose ideally the accessibility-focused features of Menu would be extracted into a hook that can be imported and used in a `Portal`-based custom UI.

### Alternatives

- Update the `Menu` to take a `usePopper` prop
- Make a separate `UnpositionedMenu` component

**Comment by ManoMylv-tBC** [comment]
I also had this use case. In the end I hacked it using the `sx` prop, to apply styles to the Popper element to knock out its `transform` styling (had to use `!important` )
I also set `position: relative` on the portal so that the menu would sit relative to it.

**Comment by forrestwilkins** [comment]
@ManoMylv-tBC Do you have an example for this by chance?
