### ISSUE TITLE
Noticeable and unwanted Border between two same color boxes

### ISSUE THREAD

**Issue by miguelmigs24** [chakra-ui/chakra-ui#5043]
### Description

When I zoom into de middle of two boxes with the same color, I see a black border between them, and I expected to see no border

### Link to Reproduction

https://codesandbox.io/s/elastic-surf-q2qhy?file=/src/index.js

### Steps to reproduce

1- Create two boxes with some text inside each
2- Zoom into to border of the two boxes ( where they meet)
Certain amounts of zoom show it, others don't. This issue happens on mobile too

### Chakra UI Version

1.6.12

### Browser

Brave

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by anubra266** [comment]
I dont'e understand this @miguelmigs24 you have a black background, but you don't want to see it.

**Comment by miguelmigs24** [comment]
@anubra266 It's not the black background around the boxes. If you zoom in where two boxes meet, you can see a black line between them, even when they have no border, and are the same color. I tested it on different browsers and even a different computer and I can see it too

**Comment by primos63** [comment]
Using Brave browser on Arch Linux. I zoomed from 100% through 500% without seeing any border between the boxes.
I also tried this on Chrome and Firefox with the same results.

**Comment by miguelmigs24** [comment]
@primos6 here's my point of view
![pov](https://user-images.githubusercontent.com/90193453/140995915-d3915677-283a-4015-bf76-75af2c12d83f.JPG)
3

**Comment by segunadebayo** [comment]
This isn't a Chakra UI issue.

I can't reproduce this as well. Please inspect the CSS and see what it's only applying the CSS background property to the element.

If you're experiencing this issue, then it'll be there even if you use regular CSS or style attributes.

Thanks for understanding.
