### ISSUE TITLE
Improve type definitions

### ISSUE THREAD

**Issue by TomokiMiyauci** [chakra-ui/chakra-ui#5049]
### Description

`Union` types can be made more straightforward.

https://github.com/chakra-ui/chakra-ui/blob/baa6fee280530137548f961db5cb308100bc3920/packages/styled-system/src/utils/types.ts#L14

#5031 

### Problem Statement/Justification

`(string & {})` looks a bit odd.
I understand that this is a hacky way, but it works just as well for `String`.

### Proposed Solution or API

```ts
export type Union<T> = T | String
```

**Comment by anubra266** [comment]
@TomokiMiyauci do you want to open a PR for this change?

**Comment by TomokiMiyauci** [comment]
@anubra266 Yes, I'll do.

**Comment by segunadebayo** [comment]
Closed as a result of #5055
