### ISSUE TITLE
[InputGroup] Jest Snapshots Error with InputGroup Containing InputLeftElement or InputRightElement

### ISSUE THREAD

**Issue by skingston91** [chakra-ui/chakra-ui#505]
**Describe the bug**
When testing a FormField component comprised of the below component elements: 

Component code
```
 <InputGroup size={size}>
          <InputLeftElement>
            {icon && <Box as={icon} color={color} />}
          </InputLeftElement>
            <Input
            variant={variant}
            placeholder={placeholder}
            aria-label={id}
            id={id}
            color={color}
          />
   </InputGroup>
```

I'm getting an error of `TypeError: Cannot read property '10' of undefined` 

Chakra UI code 
https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/InputGroup/index.js

Error
TypeError: Cannot read property '10' of undefined
```
      20 |   it("renders with error message", () => {
      21 |     const tree = renderer
    > 22 |       .create(
         |        ^
      23 |         <FormField
      24 |           field={{}}
      25 |          
      at ../../node_modules/@chakra-ui/core/dist/InputGroup/index.js:46:17
```

I'm using the gatsby-plugin-chakra-ui, so its possible I need to extend my jest config to use the ChakraUi theme provider but I wouldn't have. Removing the InputRightElement does let jest work

**Expected Behavior**
By default there should always be sizes, or the code should be rewritten so that sizes can never be undefined or has a default value if missing

**To Reproduce**
```
import React from "react"
import PropTypes from "prop-types"

import {
  Box,
  Input,
  InputGroup,
  Icon,
  InputLeftElement,
  FormControl,
  FormErrorMessage,
} from "@chakra-ui/core"

export const FormField = ({
  color = "gray.300",
  iconName,
  variant = "outline",
  placeholder,
  size = "md",
  id,
}) => {
  return (
 <InputGroup size={size}>
          <InputLeftElement>
            {iconName && <Icon name={iconName} color={color} />}
          </InputLeftElement>
            <Input
            variant={variant}
            placeholder={placeholder}
            aria-label={id}
            id={id}
            color={color}
          />
   </InputGroup>
}
```

**Suggested solution(s)**
After investigating the InputGroup component the cause is because of `const { sizes } = useTheme();` which (I believe) is referencing an undefined theme so it doesn't have any sizes. Which causes this `pl = sizes[height];` code to fail as sizes is undefined. 

I have a few ideas of what could happen here, there could be a PR which adds a valid default value.

Basic fix but I wouldn't recommend it. I'd suggest perhaps a default theme is always loaded into chakra in all cases including tests

```
 if (child.type === InputLeftElement) {
          pl = sizes[height] || "10px" ;
        }
```

Or Is a common way of injecting sizes/theme into useTheme()?  If its a gatsby chakra plugin specific issue then we can add a section into the docs on how to inject a theme into jest.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser terminal
    "babel-jest": "^25.1.0",
    "babel-preset-gatsby": "^0.2.36",
    "jest": "^25.1.0",

Thanks for your help!

**Comment by corvallo** [comment]
I'm having the same problem.
Downgraded to version 0.7.0

**Comment by segunadebayo** [comment]
Hey @skingston91,

I think this is happening because you didn't wrap the tests in `ThemeProvder`.  You should wrap every test with ThemeProvider for it to work correctly.

```jsx
import { ThemeProvider } from "@chakra-ui/core"

<ThemeProvider>
 <InputGroup size={size}>
          <InputLeftElement>
            {icon && <Box as={icon} color={color} />}
          </InputLeftElement>
            <Input
            variant={variant}
            placeholder={placeholder}
            aria-label={id}
            id={id}
            color={color}
          />
   </InputGroup>
</ThemeProvider>
```

For more context see this: #1085 

Thanks
