### ISSUE TITLE
Make `iconSpacing` control `ButtonSpinner` margin

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#5056]
### Description

Currently `iconSpacing` property of `Button` component only controls the spacing between `leftIcon` / `rightIcon` and button text. It doesn't control the spacing between `ButtonSpinner` and button text when `isLoading={true}`.

From my point of view, it should control it. Otherwise, there is a design shift when `isLoading` goes from `false` to `true`.

### Problem Statement/Justification

Currently `iconSpacing` property of `Button` component only controls the spacing between `leftIcon` / `rightIcon` and button text. It doesn't control the spacing between `ButtonSpinner` and button text when `isLoading={true}`.

### Proposed Solution or API

Controling ButtonSpinner margin via `iconSpacing` property.

**Comment by sohamsshah** [comment]
Hey @lcswillems , Can you create a reproducible codesandbox example describing the `design shift` occurring due to `isLoading` state change?

**Comment by lcswillems** [comment]
@sohamsshah  Here is a codesandbox: https://codesandbox.io/s/homepage-forked-6pmis?file=/src/App.tsx

This is the UI of "Search button" by default:

![image](https://user-images.githubusercontent.com/5437552/141170213-433057b6-1918-430c-989a-e5baf37d7173.png)

When you click, this is the UI:

![image](https://user-images.githubusercontent.com/5437552/141170261-a193d830-b2ba-492d-aecd-e5a385ffa933.png)

You see that the spacing changes.

**Comment by sohamsshah** [comment]
Thank you. Would you like to add a PR for this change?

**Comment by cschroeter** [comment]
I have a couple of concerns with that approach:

1. The prop name `iconSpacing` indicates the spacing between the icon and the label not the spinner.
2. Changing this would create a breaking change for our users 
3. The desired behaviour can easily be achieve in user land

In an ideal world I would say the button api would need to change to something like in Stacks

```tsx
<Button spacing="4" leftIcon={<SaveIcon />}>Save</Button>
<Button spacing="4" isLoading loadingText="Loading">Text</Button>
````

**Comment by lcswillems** [comment]
1. Le loading spinner is also an icon.
2. Yes maybe introducing another property name at least.
3. Your solution doesn't work.

**Comment by cschroeter** [comment]
1. Not necessarily. You can use any kind of React component 
```tsx
spinner?: React.ReactElement;
``` 
3. ? What solution. Was just an proposal for a more flexible button api

**Comment by cschroeter** [comment]
````tsx
export const Workaround = () => {
  const [isLoading, setIsLoading] = React.useState(false)
  const spacing = '8'
  return (
    <Button
      disabled={false}
      leftIcon={<SearchIcon />}
      onClick={() => setIsLoading((b) => !b)}
      isLoading={isLoading}
      spinner={<Spinner color="currentColor" boxSize="1em" marginEnd={spacing} />}
      loadingText="Search"
      iconSpacing={spacing}
    >
      Search
    </Button>
  )
}
````

**Comment by lcswillems** [comment]
@cschroeter For 3., I thought that the code you were providing with `spacing` was a currently working wordaround. But it isn't right?

**Comment by lcswillems** [comment]
@cschroeter Your workaround doesn't work. The spinner now has a margin-end and it's container has also a 0.5rem margin-right.

**Comment by cschroeter** [comment]
@lcswillems I see what you mean. I've updated the exampe. It is not perfect in any way but it shows that a stack would be the better solution for children in a button.
