### ISSUE TITLE
Textarea - can't update padding

### ISSUE THREAD

**Issue by Patrick-Ullrich** [chakra-ui/chakra-ui#5059]
### Description

When I update Input or Textarea padding in a theme file, I expect to see the given padding. However, textarea will continue to have padding of 16px.

### Link to Reproduction

https://codesandbox.io/s/friendly-dawn-fvpbu?file=/src/index.tsx

### Steps to reproduce

In the codesandbox:
1. Click on the input, notice 12px padding
2. click on the textarea below, notice 16px padding

Lot of different approaches displayed in the theme file in the sandbox, but none works as anticipated. 

### Chakra UI Version

1.6.12

### Browser

Google Chrome 94

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

`<Textarea pl={3} />` does work of course, but not through the theme.

**Comment by primos63** [comment]
It's `Textarea` and not `TextArea`. Don't worry it got me too. I'm going to close this as it isn't an issue with Chakra. If you need additional assistance, please feel free to start a `Discussion` or you can connect to the [Chakra Discord Server](https://chakra-ui.com/discord) 

Either of these work:
```javascript
  components: {
    Textarea: {
      variants: {
        outline: {
          paddingInlineStart: 3,
          paddingInlineEnd: 3
        }
      }
      // sizes: {
      //   md: {
      //     px: 3
      //   }
      // }
    },
```
For `Input` you can do the same but you need the `field` object:
```javascript
    Input: {
      variants: {
        outline: {
          field: {
      //    paddingInline: 3, //works
            paddingInlineStart: 3, //works
            paddingInlineEnd: 3, //works
      //    px: 3 // Works
          }
        }
      },
      // sizes: {
      //   md: {
      //     field: {
      //       // paddingInline: 3, //works
      //       paddingInlineStart: 3, // works
      //       paddingInlineEnd: 3,
      //       px: 3 // Works
      //     }
      //   }
      // }
    }
  }
```
If you're not seeing the changes in the inspector, you made need to select Inspect on the field again. Using Firefox this happened to me, but once I selected the element and hit Inspect, the correct padding changed.
