### ISSUE TITLE
Increase MenuItemOption configurability

### ISSUE THREAD

**Issue by Sebastiansc** [chakra-ui/chakra-ui#506]
**Is your feature request related to a problem? Please describe.**
* `MenuItemOption` does not allow skipping it's default event handler behavior.
* It doesn't allow to render a checkbox (or anything else) as the check display (only the default Icon component)

**Describe the solution you'd like**
* Add `wrapEvent` as it's done for `MenuItem`.
* Use a render prop to allow for custom checkbox or allow `Input` to be used (I'm not sure how doable the latter is)

**Describe alternatives you've considered**
* Nothing that can be done with current state

**Additional context**
* I will be opening a pr for this unless someone has a better approach for this

**Comment by aaronmcadam** [comment]
If we're going to add requirements for improvements, I think it'd be really nice to be able to add an icon too.
