### ISSUE TITLE
PinInputField does not have the props specified on documentation

### ISSUE THREAD

**Issue by DiegoMcDipster** [chakra-ui/chakra-ui#5061]
### Description

When I wanted to disable a PinInputField I found that the isDisabled prop didn't exist

### Link to Reproduction

sorry no link required

### Steps to reproduce

1. In VS Code: 

```
    <HStack>
      <PinInput id="pinid">
        <PinInputField isDisabled />
      </PinInput>
    </HStack>
```

2. Here's a screenshot of the available props beginning with 'is':
![image](https://user-images.githubusercontent.com/51478172/141310224-4f89a7fe-f23c-4993-84c0-def434482544.png)

3. This is the error I get in the console
Warning: React does not recognize the `isDisabled` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isdisabled` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
4. I looked a bit further and noticed that none of the props stated in the documentation are available. (https://chakra-ui.com/docs/form/pin-input#pininputfield)

### Chakra UI Version

1.6.10 & .12

### Browser

Firefox (but not a browser issue)

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by primos63** [comment]
Correct. This should be a docs issue. The some of the props apply to `PinInput` and not `PinInputField`. The other props apply to neither.

Props which seem to apply to `PinInput`:
- errorBorderColor
- focusBorderColor
- isDisabled
- isInvalid
- size
- variant

**Comment by DiegoMcDipster** [comment]
I don't think this is just a docs issue.  To me it seems logical to have isDisabled, isValid and isRequired on PinInputField.  

For example:
Funtionaliy what I want to do is to enble the PinInputField when the previous PinInputField is filled.

At the moment if I have a PinInput of four fields, a user can start inputting data in the fourth field and have the PinInput complete.

I would like to disable all PinInputFields except the first one, 
- thereby forcing the user to enter the first, 
- this resets the isDisabled=false on the second.  Which the user then fills in. 
- this resets the isDisabled=false on the third. Which the user then fills in. 
- this resets the isDisabled=false on the last. Which the user then fills in... upon which the PinInput completes.

**Comment by primos63** [comment]
I log into my Chrome tablet using a 6 digit pin code. Inputs 2-6 are not disabled. I do not get to the next field unless the one I'm on is filled. That is a much better way of designing a component. This is a form field that groups individual components to make the whole. There is no usefulness to a single PinInput. Component validation is done at the group. The pin in total is either valid or invalid.

**Comment by DiegoMcDipster** [comment]
"I do not get to the next field unless the one I'm on is filled". Yes, that's exactly what I want! I thought the only way to do it would be use the isDisabled flag on the PinInputField.

Your comment starting "This is a form field..." has confused me a bit. So, to be specific with an example:

The code below is from the website docs (https://chakra-ui.com/docs/form/pin-input#usage). As it stands now you can click on the third PinInputField without having filled in the first two. Which properties on the PinInput component do i need to set to make sure that : 
1. on load the first field is the only one accessible
2. I cannot get to the next field unless the one I'm on is filled in?

```
<HStack>
  <PinInput>
    <PinInputField />
    <PinInputField />
    <PinInputField />
    <PinInputField />
  </PinInput>
</HStack>
```

**Comment by anubra266** [comment]
@primos63 I checked some other libraries, apparently `PinInputField` should have all the props of an `Input`

**Comment by primos63** [comment]
@anubra266 The only other UI framework I found with it is NativeBase and while they support Input props on the individual fields they have no valid examples of using it.  All of their examples are based on the group and the props are on the group. I also checked Ant, Material, Bootstrap, Onsen and Semantic UI and could not find any PinInput component or something like it.

**Comment by anubra266** [comment]
okay then @primos63 we need to remove that prop from the docs.

**Comment by DiegoMcDipster** [comment]
Changing the docs however doesn't get me any closer to implementing the functionality that I want to implement.

The code below is from the website [docs](https://chakra-ui.com/docs/form/pin-input#usage) . You can click on the third PinInputField without having filled in the first two. Which properties on the PinInput component do i need to set to make sure that :

1. on load the first field is the only one accessible
2. I cannot get to the next field unless the one I'm on is filled in?

```
<HStack>
  <PinInput>
    <PinInputField />
    <PinInputField />
    <PinInputField />
    <PinInputField />
  </PinInput>
</HStack>
```

**Comment by primos63** [comment]
As I tried to explain earlier, having `isDisabled` on the `PinInputField` is not going to get you any closer either. It's also not inline with Pin Input designs you see on sites (at least not the ones I've been to).
No other toolkit that I know of has implemented this except for [NativeBase](https://docs.nativebase.io/3.0.6/pinInput). However, after release 3.0.6 it quietly disappeared from the website examples and [docs](https://docs.nativebase.io/).
You should be able to get the functionality you want either by working with the `PinInput` and `PinInputField` components or by cloning the component and changing the `usePinInput` hook to get the desired functionality.

If you are having difficulty figuring out what needs to be done you can have a look at the [CodeSandbox](https://codesandbox.io/s/nostalgic-visvesvaraya-8p8z8) I created. It's not perfect, but it's certainly a good start.

**Comment by DiegoMcDipster** [comment]
@primos63 Thanks so much for code sandbox! 

I can now see how you would get it to work. I will use it as a starting point.

I suppose the problem is that I have been spoiled by chakra and so I expected the implementation of this to be simple... like it is with the majority of Chakra components.  The docs don't give much insight into how to implement it either, so, hopefully your code will help others in the future.

**Comment by primos63** [comment]
You're welcome. PinInput seems simple and as designed is simple, but even if `isDisabled` was applied to `PinInputField` it wouldn't give you what you are looking for. It's very difficult to design a simplistic yet flexible and all encompassing component.
To be honest, I'd create my own `use` hook  and `PinInput` which would have the functionality you are looking for. You can see that what I provided has an issue when you click on an empty `PinInputField`. The placeholder is removed. That's due to the underlying code.

Thanks for using Chakra UI. Wish you well on your Chakra UI adventure.
