### ISSUE TITLE
Tooltip does not show when move from a disabled button

### ISSUE THREAD

**Issue by weiliao715** [chakra-ui/chakra-ui#5062]
### Description

When I move my mouse from a disabled button to a tooltip button , I expect the tooltip shows, but the tooltip does not show instead.

### Link to Reproduction

https://codesandbox.io/s/tooltip-not-shown-xgo1d?file=/src/index.js

### Steps to reproduce

Go to above CodeSandbox 

![chrome-capture](https://user-images.githubusercontent.com/54960477/141329014-e113b643-e862-4aee-9003-e25a5397edea.gif)

### Chakra UI Version

1.6.12

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by cschroeter** [comment]
Have to check code to see whats going on for now you can wrap the disabled button in a box
```tsx
     <Stack spacing="4" direction="row">
        <Tooltip label="One">
          <Button>One</Button>
        </Tooltip>
        <Tooltip label="Two">
          <Button>Two</Button>
        </Tooltip>
        <Tooltip label="Three">
          <Box>
            <Button isDisabled={true}>Three</Button>
          </Box>
        </Tooltip>
        <Tooltip label="Four">
          <Button>Four</Button>
        </Tooltip>
      </Stack>
```

**Comment by amustaque97** [comment]
:wave: another approach is to write something like this. `shouldWrapChildren` will create a span under the hood and wrap your button inside `span`
https://github.com/chakra-ui/chakra-ui/blob/94959ceefc0d8d6c89292fcf986711baeb8ba4f2/packages/tooltip/stories/tooltip.stories.tsx#L216-L220

**Comment by weiliao715** [comment]
@cschroeter @amustaque97 thanks for helping me out with this. Should I close this issue?

**Comment by weiliao715** [comment]
I added shouldWrapChildren to all tooltips, result shown below

![chrome-capture (1)](https://user-images.githubusercontent.com/54960477/141713662-22c15183-399e-4d2a-b0ac-371555327cc8.gif)

https://codesandbox.io/s/tooltip-not-shown-xgo1d?file=/src/index.js

**Comment by amustaque97** [comment]
@weiliao715, can you check the above link again?
> https://codesandbox.io/s/tooltip-not-shown-xgo1d?file=/src/index.js

It is working as expected. Though `shouldWrapChildren` should be used with `disabled` component. It is not required with other components.

Check below screenshot for reference.
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/21127788/141723336-7a8ff4b6-2aae-41ee-83bf-636d0594a189.png">

**Comment by weiliao715** [comment]
@amustaque97  when mouse move from button "Three" to button "Two", the tooltip is not shown on button "Two"

![chrome-capture (2)](https://user-images.githubusercontent.com/54960477/141785706-93eac4b7-59f1-4b6d-b0cd-23d893d49c56.gif)

**Comment by amustaque97** [comment]
@weiliao715, thank you so much. finally I'm able to reproduce the above behavior. Looks like it is happening in google chrome and safari. If you try it in Firefox you won't face above issue. Now I feel like we might have to look into code once. 
@cschroeter, Can you also pitch-in some idea how to go about it?

**Comment by DeeeeLAN** [comment]
I have a related point, not sure if it warrants its own ticket. If I have an enabled tooltip wrapping a disabled button (typical use-case is to describe why the button is disabled), the tooltip won't work either. If I wrap the button in a box or a span it works fine, but I have at least one spot where I am disabling select buttons of a button group and the border radius loses continuity with the rest of the group as a result.

![image](https://user-images.githubusercontent.com/12877032/152488018-31f4e08d-225d-4a05-a8a2-ceb926dc4912.png)

**Comment by with-heart** [comment]
@DeeeeLAN yes, please open that as a separate issue. Worth reporting and tracking separately!
