### ISSUE TITLE
version 1.3.0 of portal causing issues with nullish coallescing operation

### ISSUE THREAD

**Issue by theramirobeltran** [chakra-ui/chakra-ui#5067]
### Description

version 1.3.0 of portal causing issues with nullish coallescing operation

### Link to Reproduction

www.google.com

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

1.7.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Error when running tests: 

/root/project/node_modules/@chakra-ui/portal/dist/chakra-ui-portal.cjs.dev.js:106         const host = appendToParentPortal ? parentPortal ?? doc.body : doc.body;  SyntaxError: Unexpected token '?'        at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)       at Object.<anonymous> (node_modules/@chakra-ui/portal/dist/chakra-ui-portal.cjs.js:6:20)

**Comment by mikemajara** [comment]
Downgrading to `"@chakra-ui/react": "1.6.12",` for now works - suggesting it could be something in this last release.

**Comment by theramirobeltran** [comment]
Yes, did that for now. Thanks

**Comment by anubra266** [comment]
@theramirobeltran please feel free to reopen this issue when you have a codesandbox reproduction

**Comment by nicksrandall** [comment]
Same issue. I'll see if I can create the reproduction.
