### ISSUE TITLE
v1.7.0 update build system TypeErrors / issue loading into storybook

### ISSUE THREAD

**Issue by philcon93** [chakra-ui/chakra-ui#5069]
### Description

Loading chakra 1.7.0 gives TypeErrors and loading storybook breaks the build

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-default-dark-mode-1-7-0-nltxk

### Steps to reproduce

View the console logs

### Chakra UI Version

1.7.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I think the changes to the update build system has messed something up, all the components seem to be having type errors? I didn't know how to attach a Storybook build into Codesandbox, so I wanted to show the same Codesandbox with the only difference being the chakra UI version. There seem to be TypeErrors loading Chakra components, which didn't happen in 1.6.12:

- Chakra v1.6.12 - https://codesandbox.io/s/chakra-ui-default-dark-mode-yoe6v
- Chakra v1.7.0 - https://codesandbox.io/s/chakra-ui-default-dark-mode-1-7-0-nltxk

<img width="1012" alt="Screen Shot 2021-11-12 at 3 59 35 pm" src="https://user-images.githubusercontent.com/13529653/141418081-afbf6650-35ff-49d6-abfc-14ebce7b60ff.png">

Updating Charka UI and trying to load my storybook, I get these errors, I'm guessing Storybook is trying to load the file but its using newer JS syntax it can't read?
 
<img width="2134" alt="Screen Shot 2021-11-12 at 3 51 14 pm" src="https://user-images.githubusercontent.com/13529653/141417727-cc6dfe23-99e2-4218-9272-9f00d6d3f493.png">

Storybook errors are `You may need an appropriate loader to handle this file type, currently, no loaders are configured to process this file.`. This wasn't an issue with 1.6.12. 

Let me know if there is an easy way to show Storybooks, I don't think I can recreate it in Codesandbox, but happy to help however I can :)

**Comment by devtainguyen5762** [comment]
I also got the same error

**Comment by primos63** [comment]
Take a look at my answer [here](https://github.com/chakra-ui/chakra-ui/discussions/5068)

**Comment by r-matsuura** [comment]
I have tried the below, but it does not solve the problem.

- replace browserlist
- delete node_modules/.cache
- npm install

**Comment by tomascabralh** [comment]
I really don't know if it's related but i'm having a type error while running through a pipeline process, never happened before, only since yesterday.

![Screenshot from 2021-11-12 15-45-51](https://user-images.githubusercontent.com/58670290/141519076-0a31b5fd-7019-437f-949b-409b95167646.png)

I'm not sure what it could be. In my local machine, build and tests go well.
