### ISSUE TITLE
Headings in Popover content are rendered as empty when Popover is closed

### ISSUE THREAD

**Issue by emilioschepis** [chakra-ui/chakra-ui#5073]
### Description

When embedding an <Heading> into the body of a <Popover>, the heading is part of the DOM even before the Popover is opened, but it is considered to have 0 content inside. This is a problem for SEO checkers.

### Link to Reproduction

https://codesandbox.io/s/misty-thunder-k9wgr

### Steps to reproduce

1. Create an empty project
2. Add chakra-ui
3. Render a simple popover with a trigger, a content and the body (see attached sandbox)
4. Add an heading as part of the popover body
5. Check the page structure with any SEO checker
6. 🐛 While the popover is still closed, the heading is detected as part of the page structure, but has no text inside
7. Opening the popover and repeating the check works correctly, the text is viewable

### Chakra UI Version

1.7.0

### Browser

Google Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I think this is version-independent and OS-independent.
Let me know if I can provide any further information. 

Thank you.

**Comment by cschroeter** [comment]
Thank you for reporting this isue.

To achieve that you need the `isLazy` prop.

```tsx
    <Popover closeOnBlur={false} isLazy>
      <PopoverTrigger>
        <Button>Open</Button>
      </PopoverTrigger>
      <PopoverContent>
        <PopoverBody>
          <Heading as="h1">This is part of the DOM.</Heading>
        </PopoverBody>
      </PopoverContent>
    </Popover>
```
Thanks for supporting Chakra UI :heart:

Happy Hacking ✌️

**Comment by emilioschepis** [comment]
Hey @cschroeter, I did not think the element would be considered empty but it makes sense. 
I'll add `isLazy` to that component. 

Thank you very much for your help.
