### ISSUE TITLE
Add Chinese documentation 中文文档

### ISSUE THREAD

**Issue by Martian2Lee** [chakra-ui/chakra-ui#508]
**Is your feature request related to a problem? Please describe.**
It's hard for some Chinese developers to read English documentation.

**Describe the solution you'd like**
Add Chinese documentation.

#509

**Comment by segunadebayo** [comment]
Amazing idea, Martian. This has been on my mind as well.

If you don't mind, I'd love to collaborate with you once this. To come up with a plan, let's take the conversation here: https://discord.gg/RgAzRm
