### ISSUE TITLE
Accordion isDisabled should not be spread to the DOM element

### ISSUE THREAD

**Issue by ddkang** [chakra-ui/chakra-ui#5080]
### Description

When setting isDisabled on the Accordion, it is spread to the underlying DOM element

### Link to Reproduction

https://codesandbox.io/s/elegant-bogdan-kwbbq?file=/src/index.tsx

### Steps to reproduce

1. Compile / run
2. See warning in console

### Chakra UI Version

1.6.9

### Browser

Google Chrome 95

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

The Accordion isDisabled prop gets passed to the DOM element when it should not. See the warning below.

Similarly, activeStyle is passed from Flex, Text, etc.

```
Warning: React does not recognize the `isDisabled` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isdisabled` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

**Comment by sohamsshah** [comment]
Hey @ddkang , you can observe in the [documentation](https://chakra-ui.com/docs/disclosure/accordion#accordion-props) that `Accordion` component doesn't possess `isDisabled` prop. 

But If you want to

**Comment by cschroeter** [comment]
As @sohamsshah said, `isDisabled` is only available for the accordion item https://chakra-ui.com/docs/disclosure/accordion#accordionitem-props
