### ISSUE TITLE
emotion/core breaks new repo

### ISSUE THREAD

**Issue by dcsan** [chakra-ui/chakra-ui#5084]
### Description

emotion breaks chakra

### Link to Reproduction

new repo

### Steps to reproduce

when i install and create a new project with chakra-ui/core

somehow core depends on emotion 

```
./node_modules/@chakra-ui/core/dist/es/Accordion/index.js
Module not found: Can't resolve '@emotion/core' in '/Users/dc/dev/esclabs/stan/client/node_modules/@chakra-ui/core/dist/es/Accordion'
```

yarn add @emotion/core

now I get this error:

```
Error: The `@emotion/core` package has been renamed to `@emotion/react`. Please import it like this `import { jsx } from '@emotion/react'`.
```

thing is, I am not doing the import, I'm also not using the accordion component.
there seems to be a complete breaking change upstream in the emotion library...? 🤯 

### Chakra UI Version

0.8.0

### Browser

chrome latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

```json
{
  "name": "dcsan",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@chakra-ui/core": "^0.8.0",
    "@chakra-ui/icons": "^1.0.16",
    "@chakra-ui/react": "^1.0.0",
    "@emotion/core": "^11.0.0",
    "@emotion/react": "^11.5.0",
    "@emotion/styled": "^11.3.0",
    "@testing-library/jest-dom": "^5.9.0",
    "@testing-library/react": "^10.2.1",
    "@testing-library/user-event": "^12.0.2",
    "@types/jest": "^25.0.0",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "@types/react-router-dom": "^5.3.2",
    "@types/react-syntax-highlighter": "^13.5.2",
    "emotion-theming": "^11.0.0",
    "framer-motion": "^4.0.0",
    "gray-matter": "^4.0.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-icons": "^3.0.0",
    "react-markdown": "^7.1.0",
    "react-masonry-css": "^1.0.16",
    "react-particles-js": "^3.2.1",
    "react-router-dom": "^5.3.0",
    "react-scripts": "4.0.3",
    "react-scroll-up": "^1.3.7",
    "react-syntax-highlighter": "^15.4.4",
    "react-text-loop": "^2.3.0",
    "react-tsparticles": "^1.37.3",
    "rehype-raw": "^6.1.0",
    "typescript": "^3.9.5",
    "web-vitals": "^0.2.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by dcsan** [comment]
further issues

```
Error: `emotion-theming` has been removed and all its exports were moved to `@emotion/react` package. Please import them like this `import { useTheme, ThemeProvider, withTheme } from '@emotion/react'`.
```

so do I need to fix the core chakra library to use emotion with their new renamed version?
there's a guide on their site about how to deal with this, but that won't fix apps that use chakra - it's a chakra level fix required.

https://emotion.sh/docs/emotion-11#package-renaming

**Comment by dcsan** [comment]
I guess this is on emotion for changing the names of all their packages, but I would have thought by now chakra-ui would have fixed everything or there would be a way to still use the old pre-renamaggedon version of emotion...

seems like their v11 came out a year ago at least. so maybe there's some _very very specific combination_ of chakra and emotion versions that works?

**Comment by dcsan** [comment]
OK this seems to work - not explicitly including chakra/core 
afraid to touch this now, it seems a certain implicit peer deps combination is working for now.


```
    "@chakra-ui/icons": "^1.0.14",
    "@chakra-ui/react": "^1.7.1",
    "@emotion/core": "^10.1.1",
    "@emotion/eslint-plugin": "^11.5.0",
    "@emotion/react": "^11",
    "@emotion/styled": "^11",
    "framer-motion": "4",
````

note that framer-5 also is broken due to CRA upstream.

**Comment by burhanuday** [comment]
Hi @dcsan, i think the `@chakra-ui/core` was renamed to `@chakra-ui/react`. You can find the installation docs here - https://chakra-ui.com/docs/getting-started. Installing `@chakra-ui/react` itself should be enough. If you are upgrading versions, the migration guide is here - https://chakra-ui.com/docs/migration

**Comment by dcsan** [comment]
yeah found that out in the end. kinda frustrating I was porting some code someone built for me, even tho it was a brand new project I guess they reused some old code :(
