### ISSUE TITLE
Icon documentation page has some broken layout

### ISSUE THREAD

**Issue by martinblostein** [chakra-ui/chakra-ui#5088]
### Subject

Icon

### Description

The "Using a third-party icon library" and "Some examples" navigation links on the right side do not work (but the seconds do exist).

Also there is a layout issue in the options/props section:

![image](https://user-images.githubusercontent.com/21064932/141696084-70d8486b-661d-477e-be4a-fc4c12615d19.png)

I'm on Linux Mint and I see the issue in both Chrome (95.0.4638.69) and Firefox (94.0). I noticed similar issues across the documentation earlier but it looks like most of them were fixed!

**Comment by pablomayobre** [comment]
I'm seeing something similar in the Divider's page

![chakra-ui com_docs_data-display_divider](https://user-images.githubusercontent.com/1095969/142272638-7dee70ac-f96c-42d5-9295-c27f76cc997b.png)

**Comment by thisizkp** [comment]
Happening in almost all the pages that use code examples. Noticed in `Avatar` and `Image` docs too.

**Comment by segunadebayo** [comment]
This has been fixed in a recent update to the documentation
