### ISSUE TITLE
Custom component in `as` prop of `MenuButton` doesn't work

### ISSUE THREAD

**Issue by martinblostein** [chakra-ui/chakra-ui#5089]
### Description

When I supply a component to the as prop of MenuButton I expect the menu to function normally.

The documentation states:
> The default MenuButton can be styled using the usual styled-system props, but it starts off plainly styled.
> 
> Using the as prop of the MenuButton, you can render a custom component instead of the default MenuButton. For instance, you can use Chakra's Button component, or your own custom component.
> 
> Custom components must take a ref prop which is assigned to the React component that triggers the menu opening. This is so that the MenuList popover can be positioned correctly. Without this, the MenuList will render in an undefined position.

This doesn't seem to work with a custom component (even if it is wrapped in forward ref).

### Link to Reproduction

https://codesandbox.io/embed/youthful-darkness-r6ih8

### Steps to reproduce

1. Create a ref-forwarding custom wrapper around `Button`:

```
const CustomButton = forwardRef((props, ref) => {
  return <Button ref={ref}>{props.children}</Button>
})
```
2. Pass it as the `as` prop to `MenuButton` and build a menu like normal. The menu will not appear to open.

### Chakra UI Version

1.6.12

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by anubra266** [comment]
Do this 
```js
const CustomButton = forwardRef((props, ref) => {
  return <Button ref={ref} {...props} />;
});
```

or

```js
const CustomButton = forwardRef((props, ref) => {
  const { children, ...rest } = props
  return <Button ref={ref} {...rest} > {children} </Button>;
});
```

**Comment by martinblostein** [comment]
Perhaps that should be documented? Which props need to make it through?

**Comment by anubra266** [comment]
> Perhaps that should be documented? Which props need to make it through?

@martinblostein clicking the button, opens the list, that's definitely handled by an `onClick` handler internally.

**Comment by anubra266** [comment]
Regarding documentation, that's unnecessary because that's how it works in the whole `styled-components` ecosystem, including many other libraries, when you create a component for a factory, you should pass the props over to the root component, that's why it's a factory in the first place, so it can add capabilities to the component. This capabilities come across as props.

**Comment by anubra266** [comment]
@martinblostein the full return is [here](https://github.com/chakra-ui/chakra-ui/blob/65704470e165948f849cb2fc6de8546187e7f4c8/packages/menu/src/use-menu.ts#L341-L351)

**Comment by martinblostein** [comment]
I see, I wasn't familiar with this pattern but in retrospect it makes total sense. From the existing documentation I assumed the ref would be used to attach a listener to the reference element, but that wouldn't be idiomatic.
