### ISSUE TITLE
Popover showing in top right corner, not as per its proper position.

### ISSUE THREAD

**Issue by prathameshpbhat** [chakra-ui/chakra-ui#5090]
### Description

The  Popover component is not showing in proper position ,it is showing in top left corner

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-menu-wont-close-forked-j0pgd?file=/src/App.js

### Steps to reproduce

1.Import   Popover,PopoverBody,PopoverContent,PopoverTrigger
2.Popover     trigger='hover'  placement='bottom-start'
3.PopoverTrigger position='relative'
4.PopoverContent      position='absolute'           w='auto'   zIndex={401} 
5.PopoverBody     userSelect='none' whiteSpace='nowrap'
6.Map content inside popoverbody with text

### Chakra UI Version

1.6.10

### Browser

95.0.4638.69

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The issue started after i updated the chakra version from 1.6
<img width="1440" alt="popover bug screen shot" src="https://user-images.githubusercontent.com/32131455/141732592-ff641014-4cb6-4af4-94c7-e6f6a3b151fc.png">
.3 to 1.6.10
Earlier it was working perfectly

`
                            <Popover
                                trigger='hover'
                                placement='right-end'
                                isLazy
                            >
                                <PopoverTrigger>
                                    <Box
                                        as={MdInfoOutline}
                                        d='inline-flex'
                                        color='purple.500'
                                        ml={1}
                                        position='relative'
                                    />
                                </PopoverTrigger>
                                <PopoverContent
                                    position='absolute'
                                    w='auto'
                                    zIndex={401} // So it can go above the map.
                                    mt={5}
                                >
                                    <PopoverBody
                                        userSelect='none'
                                        whiteSpace='nowrap'
                                    >
                                        {rowData.info.service_type.map(
                                            (c, index) => {
                                                return (
                                                    <Text
                                                        key={`wiz-container-${index}`}
                                                        fontWeight={500}
                                                    >
                                                        {c}
                                                    </Text>
                                                );
                                            }
                                        )}
                                    </PopoverBody>
                                </PopoverContent>
                            </Popover>
                       `

<img width="1440" alt="popover bug screen shot" src="https://user-images.githubusercontent.com/32131455/141732463-a0eb4a89-85e0-49d6-aa81-1cc48150bb64.png">

Disclaimer:
I am not able to reproduce on sandbox not sure why.But this is happening only after i updated my chakra version.Also for Windows localhost this issue is not comming, only when on server or mac local hosting

**Comment by segunadebayo** [comment]
Hi @prathameshpbhat,

Removing all the clashing styles you had in your code, and it works as expected:

```jsx
export default function App() {
  return (
    <ChakraProvider>
      <Popover trigger="hover" placement="bottom-start" isLazy>
        <PopoverTrigger>
          <Button>
            <Box
              as={MdInfoOutline}
              d="inline-flex"
              color="purple.500"
              position="relative"
            />
          </Button>
        </PopoverTrigger>
        <PopoverContent
          width="auto"
          zIndex={401} // So it can go above the map.
        >
          <PopoverBody userSelect="none" whiteSpace="nowrap">
            <Text>a</Text>
            <Text>b</Text>
            <Text>c</Text>
            <Text>d</Text>
          </PopoverBody>
        </PopoverContent>
      </Popover>
    </ChakraProvider>
  );
}
```

**Comment by mwibutsa** [comment]
I have the same issue.

**Comment by nabeelpkl** [comment]
any update on this issue? I am also facing this in Remix.js

**Comment by jack77121** [comment]
in popover[ basic usage ](https://chakra-ui.com/docs/components/popover#basic-usage)
`Tip: When using this component, ensure the children passed to PopoverTrigger is focusable and has a forwarded ref`

so, in my case, I use my own wrapped button component in popover trigger:
```
...
<PopoverTrigger>
    <MyButton>Trigger</MyButton> // <- my own wrapped component
</PopoverTrigger>
...
```

then, I add forwardRef to MyButton:
```
import {
   ...
  forwardRef,
  Button as _Button
} from '@chakra-ui/react';


interface IButton extends ButtonProps {
  // my interface
}

const MyButton = forwardRef<IButton, 'button'>((props, ref) => {
  ...

  return (
    ...
    <_Button ref={ref}  {...props}>
      {props.children}
    </_Button>
    ...
  );
});

export default MyButton;
```

hope this is helpful
