### ISSUE TITLE
Radio buttons missing pointer cursor on hover

### ISSUE THREAD

**Issue by israelperez** [chakra-ui/chakra-ui#5091]
### Description

when i mouse over a radio button, i expect the mouse cursor to change to "pointer"

### Link to Reproduction

 no link

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

1.6.4

### Browser

chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

It seems it's only happening to radio buttons. checkboxes, buttons, switches are working fine

**Comment by cschroeter** [comment]
Thx for reporting the issue. As a workaround you can set a `cursor: pointer` in your custom theme / component.
