### ISSUE TITLE
notarget No matching version found for @chakra-ui/pin-input@1.7.1.

### ISSUE THREAD

**Issue by lqd1434** [chakra-ui/chakra-ui#5092]
### Description

when I use nom to install dependents as the guide,i got this error

### Link to Reproduction

...

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

1.7.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

when I search this package in npm ,I don't find it
![截屏2021-11-15 15 52 13](https://user-images.githubusercontent.com/66897781/141742829-ec4a6da7-da2d-4b6e-9ef8-41da6a205e6a.png)

**Comment by cschroeter** [comment]
Thank you for taking the time to create this issue. Unfortunately, it does not contain all the necessary information we need to work on this issue.

I've tried this the same command and it just works fine (npm and yarn).
Therefore we have to close this issue. You can create a new issue at any time - please use the corresponding issue template.

Happy hacking ✌️
