### ISSUE TITLE
padding left for a flushed <Select />

### ISSUE THREAD

**Issue by performautodev** [chakra-ui/chakra-ui#5094]
### Description

pl not working on flushed <Select />

### Link to Reproduction

https://codesandbox.io/s/nifty-star-og5uf?file=/src/index.js

### Steps to reproduce

pl not working on flushed <Select />

### Chakra UI Version

1.6.12

### Browser

chrome 93

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by ala-garbaa-pro** [comment]
For <Select /> variant="flushed"
pl not working just you have to add 
style={{ paddingLeft: "16px" }}

**Comment by performautodev** [comment]
Thank you @ala-garbaa-pro
