### ISSUE TITLE
InputGroup overrides Input variant

### ISSUE THREAD

**Issue by AntoineLbrn** [chakra-ui/chakra-ui#5103]
### Description

I created a styled component with Chakra ForwardRef, which had variant="flushed" by default. When i was using this component, it had variant="outline" set. I finally discovered this was because of InputGroup.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-forked-t9q2s

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

1.6.10

### Browser

Google chrome 93

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
You should set the variant on the `InputGroup`

**Comment by AntoineLbrn** [comment]
> You should set the variant on the `InputGroup`

Ikr, but in my opinion, behaviour should be the same doing 
```
<InputGroup>
    <CustomInputWithForwardRef variant="flushed"/>
</InputGroup>
```
or doing 
```
<InputGroup>
    <Input variant="flushed"/>
</InputGroup>
```

but it does not. Am I wrong ?

**Comment by anubra266** [comment]
> > You should set the variant on the `InputGroup`
> 
> Ikr, but in my opinion, behaviour should be the same doing
> 
> ```
> <InputGroup>
>     <CustomInputWithForwardRef variant="flushed"/>
> </InputGroup>
> ```
> 
> or doing
> 
> ```
> <InputGroup>
>     <Input variant="flushed"/>
> </InputGroup>
> ```
> 
> but it does not. Am I wrong ?

@AntoineLbrn `InputGroup` passes its `variant` and `size` props to `Input` so when none Is provided, it passes it as undefined to the `Input` this overrides the variant you already specified in `CustomInput` and when `undefined` is provided as the `variant` prop of the input, it defaults to `outline`.

This is the solution
```js
const CustomInput = forwardRef<InputProps, "input">((props, ref) => {
  const { variant, size, ...rest } = props;
  return (
    <Input
      ref={ref}
      color="gray.600"
      variant={variant ?? "flushed"}
      size={size ?? "flushed"}
      {...rest}
    />
  );
});
```
