### ISSUE TITLE
ChakraComponent/Chakra Factory don't work with props in curly brackets (TypeScript - interface)

### ISSUE THREAD

**Issue by maryamseyedi** [chakra-ui/chakra-ui#5109]
### Description

When I use ChakraComponent or any other method to wrap my component in chakra in order to have its style props available to me, if I use {} and put all the props inside this {} from my interface in typescript, it won't make the style changes I add. However, I also receive no error.

### Link to Reproduction

https://codesandbox.io/s/priceless-wiles-hpjto?file=/src/DataTable.tsx

### Steps to reproduce

1. Go to DataTable
2. Change props on DataTable
3. Try having only one prop vs several (adding curly brackets)

### Chakra UI Version

1.6.4

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
There is no use of the chakra factory in your reproduction @maryamseyedi. Please feel free to reopen this when you do that and encounter any issues

**Comment by maryamseyedi** [comment]
I have tested every other possible scenario. It doesn't work. I have in fact done that already. It won't recognize the styles to begin with, if I don't use chakra factory.......
![image](https://user-images.githubusercontent.com/9810835/142219528-a13e89c4-e6ac-4eb1-96e4-ac3b7ebaec22.png)
https://github.com/chakra-ui/chakra-ui/discussions/5099

**Comment by maryamseyedi** [comment]
> 
> 
> There is no use of the chakra factory in your reproduction @maryamseyedi. Please feel free to reopen this when you do that and encounter any issues
I have tested every other possible scenario. It doesn't work. I have in fact done that already. It won't recognize the styles to begin with, if I don't use chakra factory.......

![image](https://user-images.githubusercontent.com/9810835/142219770-6474a4d9-40f0-439d-ae1a-245fcbb481d5.png)


https://github.com/chakra-ui/chakra-ui/discussions/5099

**Comment by anubra266** [comment]
> > There is no use of the chakra factory in your reproduction @maryamseyedi. Please feel free to reopen this when you do that and encounter any issues
> > I have tested every other possible scenario. It doesn't work. I have in fact done that already. It won't recognize the styles to begin with, if I don't use chakra factory.......
> 
> ![image](https://user-images.githubusercontent.com/9810835/142219770-6474a4d9-40f0-439d-ae1a-245fcbb481d5.png)
> 
> #5099

@maryamseyedi update your codesandbox to show the problem or errors that need to be solved, the `chakra` factory isn't used, and I hardly understand the description at the end.

<img width="668" alt="CleanShot 2021-11-17 at 16 36 13@2x" src="https://user-images.githubusercontent.com/30869823/142231334-d5e79ef4-0d81-48b8-a10d-681e9f63bd12.png">

**Comment by maryamseyedi** [comment]
couldn't get clearer. Refer to the discussion with the link I have included, _**please**_.

**Comment by maryamseyedi** [comment]
> 
> 
> > > There is no use of the chakra factory in your reproduction @maryamseyedi. Please feel free to reopen this when you do that and encounter any issues
> > > I have tested every other possible scenario. It doesn't work. I have in fact done that already. It won't recognize the styles to begin with, if I don't use chakra factory.......
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/9810835/142219770-6474a4d9-40f0-439d-ae1a-245fcbb481d5.png)
> > #5099
> 
> @maryamseyedi update your codesandbox to show the problem or errors that need to be solved, the `chakra` factory isn't used, and I hardly understand the description at the end.
> 
> <img alt="CleanShot 2021-11-17 at 16 36 13@2x" width="668" src="https://user-images.githubusercontent.com/30869823/142231334-d5e79ef4-0d81-48b8-a10d-681e9f63bd12.png">

Refer to the discussion with the link I have included, _please_.
