### ISSUE TITLE
Color mode not setting up properly with the gatsby plugin in production

### ISSUE THREAD

**Issue by Calvein** [chakra-ui/chakra-ui#511]
**I only recreate this bug in production**
When loading a page that should be in dark theme by default, it appears that `colorMode` from the hook `useColorMode` always returns 'light' by default, see https://github.com/Calvein/acnh-surf-n-turf/blob/master/src/components/Header.js#L24-L35

You can see the bug on this page: https://acnh-surf-n-turf.netlify.com/
To reproduce, go into dark mode & reload the page, you'll see that the header is in light mode.
https://www.loom.com/share/bebc18bc629544daa814409bfc3722a6

**Comment by KenzoBenzo** [comment]
Hey @Calvein! I posted my work-around solution, [here](https://github.com/chakra-ui/chakra-ui/issues/305#issuecomment-598702861). Hope it helps

**Comment by Calvein** [comment]
Thanks a lot @KenzoBenzo, it works perfectly in the meantime 👍
