### ISSUE TITLE
Modal doesn't receive focus on input blur

### ISSUE THREAD

**Issue by marcelscruz** [chakra-ui/chakra-ui#5116]
### Description

When an input inside a modal loses its focus (blur), the focus goes to `body` , causing ESC not to close the modal.

### Link to Reproduction

https://codesandbox.io/s/modal-doesnt-receive-focus-on-input-blur-mrn9f?file=/src/index.js

### Steps to reproduce

1. Open a modal that has an input field inside
2. Focus on the input, if not already focus
3. Press ESC to remove the focus from the input
4. Press ESC again to try and close the modal
5. The modal doesn't close

### Chakra UI Version

1.6.12

### Browser

Google Crome 95

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The following link is from Chakra's docs, where the issue can also be seen:
https://chakra-ui.com/docs/overlay/modal#focus-on-specific-element

The video below demonstrates the example above in action.
When pressing ESC while focused on the input, it removes its focus, but then the focus goes to `body`, which doesn't allow ESC to close the modal.

https://user-images.githubusercontent.com/12413903/142462272-5171ccc2-c62f-42bc-b14c-ec811e9da617.mov

**Comment by marcelscruz** [comment]
Never mind.

It seems that the [Vimium extension](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en) was the culprit.

**Comment by marcelscruz** [comment]
It seems that fields with 1Password's autocomplete also suffer from this issue.

**Comment by cschroeter** [comment]
Thanks for reporting the error and explaining what caused the issue.
Unfortunately, we have no way to deal with external addons on a UI level.

Thanks for supporting Chakra UI :heart:
Happy Hacking ✌️
