### ISSUE TITLE
Floating labels for inputs

### ISSUE THREAD

**Issue by singingwolfboy** [chakra-ui/chakra-ui#5120]
### Description

There is a UI design for input labels that I believe was first popularized by [Material Design](https://material.io/components/text-fields). This design involves initially showing the label directly on the input field, and then "floating" the label upwards to appear above the cursor when the user interacts with the input field. It would be nice if this UI design was an option for Chakra UI.

This was previously discussed in #1744, but I would like to take a different approach on how to implement it.

### Problem Statement/Justification

Chakra UI should support common UI designs and interactions, especially to allow developers to migrate away from other component libraries and towards Chakra UI. By including this "floating" version of input labels in Chakra UI, we support a common design for frontend components, which makes the Chakra UI library more widely useful.

### Proposed Solution or API

```html
<FormControl variant="floatingLabel">
  <FormLabel>Username</FormLabel>
  <Input type="text" />
</FormControl>

<FormControl variant="floatingLabel">
  <FormLabel>Password</FormLabel>
  <Input type="password" />
</FormControl>
```

[See this codepen for an example of the expected UI design.](https://codepen.io/AdrianBece/pen/KKKZQOY)

### Alternatives

It should be possible to implement this variant in a custom theme, but I wanted to reach out to the Chakra community to see if I could contribute it as a pull request instead. I'm happy to put together a proposed implementation, but wanted to check if that would be acceptable first.

### Additional Information

It would be nice if this `variant="floatingLabel"` could apply to other, similar form components, such as the `<Select>` component. That is why I believe this variant belongs on the `<FormControl>` component, rather than on the `<Input>` component.

**Comment by segunadebayo** [comment]
Great thoughts in here @singingwolfboy. This sounds more like a recipe than a feature we should add to Chakra since we don't implement any specific design pattern/system e.g Material design.

Feel free to implement this and create a PR to add it to the recipe section of the docs.

**Comment by Binternet** [comment]
These works just fine:
https://v2.chakra-ui.com/community/recipes/floating-labels

But does anyone made a solution to support RTL inputs?
