### ISSUE TITLE
Cannot pass icon prop as variant in checkbox

### ISSUE THREAD

**Issue by semasad** [chakra-ui/chakra-ui#5122]
### Description

When I tried to add prop 'icon' in a variant of a checkbox, the app throws error, do not render.

### Link to Reproduction

https://codesandbox.io/s/frosty-thunder-idvgb

### Steps to reproduce

In a project I'm working, we tried to define a default icon for the checkbox element, instead of the check. After a while, we discuss the best solution is to create a variant, pass the Icon inside the variant as part of the props of the checkbox, and use that variant as default.

After trying a lot of different solutions, we think there is a bug or is a missing feature, in Chakra, you cannot pass custom icon inside the theme.

I created a reproduction of the problem. Also, step by step, we:

1. In a project from scratch, add Chakra, extended the theme and define custom configuration to the checkbox element (sizes, variants, defaultProps, etc).
2. We made all process to make this basic project work. If you try to remove the icon prop inside the variant in the `checkbox.js` file works, the variant add the red border and background to the checkbox.
3. We create a custom icon inside the project.
4. We import the icon in the theme, and try to pass inside the variant.

I think all the information is inside the replica.

### Chakra UI Version

latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by primos63** [comment]
Icon is not a CSS property. It's a prop meant to be placed with the `Checkbox` component as it is JSX, `<Checkbox icon={<Female />} ...>`.
If you do not want to specify the icon each time you use the `Checkbox` component, then you can wrap `Checkbox` in your own React component where you can specify the default icon.

You are welcome to take a look at my [CodeSandbox of theming examples](https://codesandbox.io/s/chakra-ui-theme-extension-w5u2n?file=/src/theme/Checkbox/index.js).

Please feel free to use the [Github Discussions](https://github.com/chakra-ui/chakra-ui/discussions) or the [Chakra Discord Server](https://chakra-ui.com/discord) if you have questions or need help.

I'm closing this as it is not an issue with Chakra.
