### ISSUE TITLE
[useToast] Unusable in a new project due to ref error

### ISSUE THREAD

**Issue by KenzoBenzo** [chakra-ui/chakra-ui#513]
**Describe the bug**
The `useToast` hook applied as an onClick handler to a button errors out with _"Cannot read property 'ref' of null"_.

**Expected Behavior**
Clicking the button should create a toast.

**To Reproduce**
Click the button
[Here is the CodeSandbox.](https://codesandbox.io/s/chakra-ui-toast-oe08i)

**Suggested solution(s)**
Digging through some other bug reports that have similar issues, it could be a dependency version mismatch. Deeper in the error it mentions the `ToastManager` which I would assume is part of `toasted-notes`.

**Comment by segunadebayo** [comment]
Hi @KenzoBenzo,

I just looked at the Codesandbox, updated the dependencies including `@chakra-ui/core`, and moved the `ThemeProvider` close to `ReactDOM.render`.

It seems to be working: https://codesandbox.io/s/chakra-ui-toast-ezkcu

**Comment by KenzoBenzo** [comment]
@segunadebayo that version upgrade worked, thanks mate!
