### ISSUE TITLE
Theme typings broken cannot find default out directory

### ISSUE THREAD

**Issue by benekoehler** [chakra-ui/chakra-ui#5138]
### Description

When running `chakra-cli tokens ...` it yields `Could not find @chakra-ui/styled-system in node_modules. Please provide '--out' parameter.`

### Link to Reproduction

https://codesandbox.io/s/vigorous-galileo-1olmf

### Steps to reproduce

1. run `chakra-cli tokens yourTheme.ts` 
2. wait for error to throw
3. `Could not find @chakra-ui/styled-system in node_modules. Please provide '--out' parameter.`

### Chakra UI Version

chakra-cli@1.5.3

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Hey guys, Thanks for this awesome package. 
i use `chakra-cli@1.5.3`
I think it's due to the change of your build config which now doesn't have a `dist` folder anymore.

**Comment by jrolfs** [comment]
I'm pretty sure you just need to upgrade **@chakra-ui/cli** to **1.6.0** — are you not able to for some reason?

**Comment by segunadebayo** [comment]
Hi @benekoehler,

Please upgrade to 1.6.0 and that should be fixed.

**Comment by benekoehler** [comment]
Thanks for having a look! Seems we got another issue with 1.6 but this needs some more debugging from my side :)
This issue is rightfully closed, thanks!

**Comment by jrolfs** [comment]
Yeah, I'm having an issue with Prettier and 1.6. I'm hoping to be able to get to the bottom of that sometime this week. I'll probably open a separate issue for that.
