### ISSUE TITLE
[RadioGroup/CheckboxGroup] Error: each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by rovervannispen** [chakra-ui/chakra-ui#514]
When I use either a RadioGroup or a CheckboxGroup I get an error that I need to specify keys. When I add keys it'll still throw the same error.

```
<RadioGroup
  isInline
  spacing={4}
  defaultValue="301"
  ref={register}
  name="game"
  onChange={e => setGameType(e.target.value as GameTypes)}
  value={gameType}
>
  {gameTypes.map((type, index) => (
    <Radio value={type} key={index}>
      {type}
    </Radio>
  ))}
</RadioGroup>;
```

```
index.js:1 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `RadioGroup`. See https://fb.me/react-warning-keys for more information.
    in Box (created by RadioGroup)
    in RadioGroup (at CreateGame.tsx:84)
```
**Expected Behavior**
When adding keys the error shoud be gone.

**To Reproduce**
- Install @chakra-ui/core#0.6.1
- Add a RadioGroup
- Map over items in RadioGroup and return Radio Buttons
- Check console

**Desktop**
- Browser: Chrome 80.0.3987.149

**Comment by dusty** [comment]
I ran into this as well.  I made a sandbox here: https://codesandbox.io/s/chakra-ui-bi5nm

<img width="1500" alt="Screen Shot 2020-03-24 at 11 35 14 " src="https://user-images.githubusercontent.com/792/77464288-2cbfb400-6dc4-11ea-9c48-c71905fd20f3.png">

Does a passed in key never make it to the wrapper box.

<img width="941" alt="Screen Shot 2020-03-24 at 11 43 17 " src="https://user-images.githubusercontent.com/792/77464612-ad7eb000-6dc4-11ea-912e-75b11bf92fa6.png">

**Comment by segunadebayo** [comment]
This has been fixed. Kindly upgrade to the latest version

**Comment by rovervannispen** [comment]
That’s awesome, thanks man. Love your your library!
