### ISSUE TITLE
[Icon] - @chakra-ui/icons installation instructions gets truncated(cropped) on reloading the page

### ISSUE THREAD

**Issue by shahpreetk** [chakra-ui/chakra-ui#5143]
### Description

The @chakra-ui/icons installation instructions box on https://chakra-ui.com/docs/media-and-icons/icon is truncated and hence the npm/yarn command is not completely visible on reloading the page.

### Link to Reproduction

https://chakra-ui.com/docs/media-and-icons/icon#installation

### Steps to reproduce

1. Go to 'https://chakra-ui.com/docs/media-and-icons/icon#installation'
2. Check the installation copy code box
3. Reload the page and check again
<img width="1126" alt="Screenshot 2021-11-23 at 9 11 44 PM" src="https://user-images.githubusercontent.com/46485763/143129883-d6e6f15c-cce7-41fc-b754-0121a340d8c1.png">

### Chakra UI Version

1.7.2

### Browser

Google Chrome Version 96.0.4664.55 (arm64) and Mozilla Firefox Version 96.0.4664.55 (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by primos63** [comment]
Thanks for contributing. This issue was already reported in #5088 so I will close this one as a duplicate.
