### ISSUE TITLE
Make it possible to leave out warnings when creating production code?

### ISSUE THREAD

**Issue by maapteh** [chakra-ui/chakra-ui#5148]
### Description

The warnings are really helpful while developing. But in our distribution we would like to not have these. Is/should that be possible?

### Problem Statement/Justification

Here you can see for one Accordion for example https://github.com/chakra-ui/chakra-ui/blob/main/packages/accordion/src/use-accordion.ts#L341-L379 this is really helpful while developing, but also some are about just reading the documentation right

### Proposed Solution or API

First i was thinking about using the NODE_ENV but that also leaves the code.

**Comment by segunadebayo** [comment]
Hi @maapteh,

In the code, we don't log the warnings in production. See the code here:
https://github.com/chakra-ui/chakra-ui/blob/main/packages/utils/src/function.ts#L56

**Comment by maapteh** [comment]
@segunadebayo im not talking about not showing the warning. Im talking about leaving all that code OUT of production code. Now its also compiled with the end result!
