### ISSUE TITLE
[NumberInput] Clicking the label no longer focuses the related input

### ISSUE THREAD

**Issue by aaronmcadam** [chakra-ui/chakra-ui#515]
**Describe the bug**

The `htmlFor` and `id` combination doesn't work anymore using the latest version. It works in `0.3.1` (the default version in the code sandbox linked on the readme).

See here: https://codesandbox.io/s/chakra-ts-starter-olcgy

**Expected Behavior**

I expect to be able to click on an input's label and have the related input focussed.

**To Reproduce**

1. Go to https://codesandbox.io/s/chakra-ts-starter-olcgy
2. Click on any of the labels
3. See that the input isn't focussed

**Suggested solution(s)**

I don't know

**Comment by segunadebayo** [comment]
@aaronmcadam, this is a bug in how we're forwarding the `id` prop. Seems it's going to the containing `div`, not the `input` itself.

As a walk around, I'd suggest you use the declarative version of the NumberInput

See the code here: https://codesandbox.io/s/chakra-ts-starter-f3eqz

**Comment by aaronmcadam** [comment]
Thanks!
