### ISSUE TITLE
Tooltip keydown listener causing performance issues

### ISSUE THREAD

**Issue by danzvara** [chakra-ui/chakra-ui#5156]
### Description

Using a lot of tooltips in a page causes a many keydown handlers to be registered on document via `useEventListener("keydown", onKeyDown)`. Typing then causes CPU spikes and ultimately feels sluggish and freezes due to large amount of listeners being handled.

### Problem Statement/Justification

`useEventListener` takes optional `env` parameter, which defaults to `document` when not provided. This makes it impossible to prevent Tooltip from subscribing keydown event handlers, in case the "Close on Esc" behavior is not desired. 

### Proposed Solution or API

Don't subscribe event listener if `env` is not defined. Add a prop `closeOnEsc` to control the behavior in Tooltip component.  

Proposed `useEventListener` effect implementation. The unfortunate side effect would be to update current usages of the hook to pass `document` in. 
```
  React.useEffect(() => {
    const node = runIfFn(env)

    node?.addEventListener(event, listener, options)
    return () => {
      node?.removeEventListener(event, listener, options)
    }
  }, [event, env, options, listener])

```

**Comment by primos63** [comment]
A few questions I have:
- Where's the demonstration of the issue?

- How many is "a lot"? 

- Your proposal is to make `env` required and remove the fallback value, `document`. What would prevent one from passing in `document` via `env` thereby causing the same issue?  

Silently not subscribing is a bad idea to me. Events handlers would just fall into an abyss.
> The unfortunate side effect would be to update current usages of the hook to pass document in.

That side effect would make such a change a breaking one.

I think the issue can be solved via docs with a mention of best practices in using tooltips.

**Comment by jordangarcia** [comment]
+1 to this.  

After digging deep into performance inside of our large ChakraUI app one of the biggest culprits is around the `Menu` and `Tooltip` component which rely heavily on `useEventListener` under the hood.  The fact that this hook is constantly adding and removing event listeners seems like a non optimal way to handle this from a performance standpoint.

The overhead in constantly add / removing event listeners has quite a bit of overhead (when interacting directly with DOM nodes).  Instead usage of a JS event emitter that manages handler state and only binds a single event listener seems more efficient.

@segunadebayo would love to get your opinion on this as I see you originally authored `useEventListener`

**Comment by mlajtos** [comment]
@jordangarcia Would the proposed solution work for you? #5199

**Comment by mlajtos** [comment]
@jordangarcia Thank you for your input.

@segunadebayo Here is codesandbox for replication – https://42pmxu.csb.app/

With 10240 tooltips, you can see spikes as bad as this:
<img width="518" alt="Snímka obrazovky 2022-02-16 o 11 39 29" src="https://user-images.githubusercontent.com/1047512/154248036-205bc45a-6f77-423d-92d6-1e3abbea1844.png">
