### ISSUE TITLE
"variant" is not working with Button with "at" attribute

### ISSUE THREAD

**Issue by itta611** [chakra-ui/chakra-ui#5158]
### Description

I want to create the outline button using Link with "at" attribute. but "variant" is not working.

### Link to Reproduction

https://codesandbox.io/s/dry-firefly-6vbvl

### Steps to reproduce

1. Create `Link`
2. Set `at` prop to `{Button}`
3. Set `variant` prop to `outline` <- This is not working

### Chakra UI Version

1.7.2

### Browser

Google Chrome 95.0.4638.69

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by ruckonic** [comment]
You're doing it wrong, it should be:
```jsx
<Button
    href="https://chakra-ui.com/docs/theming/component-style"
    variant="outline" // THIS NOT WORKING
    target="_blank"
    referrerPolicy="no-referrer"
    as={Link}
  >
    Button
</Button>

```

**Comment by anubra266** [comment]
@itta611 refer to @ruckonic answer above and don't forget passHref if you use nextjs.
