### ISSUE TITLE
The component doesn't change their color depending on the color mode in Storybook

### ISSUE THREAD

**Issue by ngxCoder** [chakra-ui/chakra-ui#5161]
### Description

The component doesn't change their color depending on the color mode in Storybook

### Link to Reproduction

https://github.com/ngxCoder/storybook-chakra-test

### Steps to reproduce

1. yarn (Install dependencies)
2. yarn link "@chakra-ui/storybook-addon" (You need to link the "@chakra-ui/storybook-addon" from chakra-ui repo as [TimKolberger](https://github.com/chakra-ui/chakra-ui/pull/5126#issuecomment-977077594) said)
3. yarn storybook

### Chakra UI Version

1.7.2

### Browser

Google Chrome 96

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

You can see a GIF of the issue in the repository

**Comment by segunadebayo** [comment]
This isn't an issue since it's not released yet. Please add this as a comment in the attached PR you created.
