### ISSUE TITLE
Page-specific color scheme (light / dark)

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#5165]
### Description

I would like the homepage of my website to be dark mode and the other pages to be light mode. But curently I can't find a way to do it with Chakra-UI. I can only set the initial color mode.

### Problem Statement/Justification

I would like the homepage of my website to be dark mode and the other pages to be light mode. But curently I can't find a way to do it with Chakra-UI. I can only set the initial color mode.

### Proposed Solution or API

Add a `colorMode` parameter to ChakraProvider.

**Comment by segunadebayo** [comment]
Hi @lcswillems, Did you try using the `<LightMode>` and `<DarkMode>` components?

**Comment by lcswillems** [comment]
Hi @segunadebayo,
I tried them! But I didn't succeed to make them working. With `DarkMode` the background of the page was still white.

**Comment by segunadebayo** [comment]
A combination of `LightMode` or `DarkMode` components and the undocumented `GlobalStyle` component can help you achieve this.

> Note that the caveat of this approach is that you won't be able to switch between color modes. You're effectively "locking" the mode.

```jsx
<LightMode>
      <GlobalStyle />
      // rest of your page
 </LightMode>
```

I'll post this as a recipe on the website.

**Comment by lcswillems** [comment]
Thanks it works!!

**Comment by lcswillems** [comment]
@segunadebayo Finally your solution doesn't fully work. It doesn't work for modals. My whole page is in a DarkMode component. But when I open a modal, it has a white background.
