### ISSUE TITLE
Get Chakra UI working with Remix Run

### ISSUE THREAD

**Issue by alanaudi** [chakra-ui/chakra-ui#5166]
### Description

Incompatible with remix-run

### Link to Reproduction

https://codesandbox.io/s/autumn-dream-se227

### Steps to reproduce

1. Click on  'button'
2. Color mode value doesn't change with `useColorMode` and `useDisclosure` doesn't work with `Slide` component.
3. Initial color mode doesn't load correctly too

### Chakra UI Version

1.7.2

### Browser

FireFox Nightly 96.0a1（2021-11-26）

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by primos63** [comment]
Did you follow the Remix docs for styling CSS-in-JS libraries? I don't see that in the CSB example.
https://remix.run/docs/en/v1/guides/styling#css-in-js-libraries

**Comment by primos63** [comment]
Steps to get Chakra to work with Remix.

First install Emotion Server
`npm install @emotion/server to your project or yarn add@emotion/server`

You'll need some context to put your styles on so that your root route can render them.
```javascript
// app/StylesContext.tsx
import { createContext } from "react";
export default createContext<null | string>(null);
```
Your entry.server.tsx will look something like this:
```jsx
import ReactDOMServer from "react-dom/server"
import { renderToString } from "react-dom/server";
import { RemixServer } from "remix";
import type { EntryContext } from "remix";
import createEmotionServer from "@emotion/server/create-instance"
import createCache from '@emotion/cache'
import StylesContext from "./StylesContext"
import { CacheProvider } from "@emotion/react";

export default function handleRequest(
  request: Request,
  responseStatusCode: number,
  responseHeaders: Headers,
  remixContext: EntryContext
) {
  // set up the Emotion Cache
  const key = 'chakra'
  const cache = createCache({ key })
  
  // Get functions to extract Emotion CSS styles from the app
  const { extractCriticalToChunks, constructStyleTagsFromChunks } = createEmotionServer(cache)

  // This render is here to let Emotion extract the styles used
  const html = renderToString(
    <CacheProvider value={cache}>
      <RemixServer
        context={remixContext}
        url={request.url}
      />
    </CacheProvider>
  )

  // Now that we rendered to a string, we can get the styles out of the html
  const chunks = extractCriticalToChunks(html)
  const styles = constructStyleTagsFromChunks(chunks)

  // Finally, we render a second time, but this time we have styles to apply,
  // make sure to pass them to `<StylesContext.Provider value>`
  let markup = ReactDOMServer.renderToString(
    <StylesContext.Provider value={styles}>
      <RemixServer
        context={remixContext}
        url={request.url}
      />
    </StylesContext.Provider>
  )

  responseHeaders.set("Content-Type", "text/html");

  return new Response("<!DOCTYPE html>" + markup, {
    status: responseStatusCode,
    headers: responseHeaders
  });
}
```
You'll now be able to use Chakra UI components in your app.

**Comment by macjabeth** [comment]
Having an official way to integrate Chakra UI w/ Remix would be nice!

I wanted to add that I've been getting issues when navigating to routes that aren't defined. I add the provider in the `Document` component which is shared between the `App` and `CatchBoundary`. Despite it being in both places, all styling is removed when it hits the `CatchBoundary`.

I've tried adding the provider to the `server.entry` file and using the provided solution @primos63 added above. Neither seems to fix the issue.

**Comment by primos63** [comment]
How did you add the provider? I thought the solution was to follow what was done for Styled Components on the server side, but that throws a warning which I'm still looking into. I think if <Scripts> is removed then the server side styles would come into play. I haven't tested this yet as I'm still learning what Remix is doing. 

I also noticed that without any modifications to the server component Chakra works. For any `<Document><Layout>` grouping you need to have `<Document><ChakraProvider theme={theme}><Layout>`. This is necessary because Remix does remove the CSS styling for a new document.

**Comment by South-Paw** [comment]
Have been asked to test out some stuff with Remix and first through was to see how well Chakra integrated - ran into same thing as @macjabeth with. Works fine on initial load, can navigate to valid routes but if you hit a `CatchBoundary` all styles get lost. Navigating to a valid route again has no styles, but reloading the page resolves the missing styles until you hit a `CatchBoundary` again.

**Comment by primos63** [comment]
@South-Paw Did you checkout the [Remix doc](https://chakra-ui.com/guides/getting-started/remix-guide)?

**Comment by South-Paw** [comment]
@primos63 Yes, that is what I followed to set it up Chakra in my Remix project. However the Remix app still looses all styling when you hit a `CatchBoundary`

- Refreshing the CatchBoundary page will fix the styles, but navigating away will break them again
- Navigating to a valid route from the CatchBoundary does not fix the missing styles, but refreshing the page on the valid route will fix them

**Comment by primos63** [comment]
@South-Paw Is this a nested CatchBoundary or the root? Do you have an example I can look at?

**Comment by South-Paw** [comment]
@primos63 This is the root CatchBoundary _and_ ErrorBoundary (same behaviour if you get to it)

I'll see if I can find time to make an example repo, but can't make promises sorry - short on time this time of year

**Comment by primos63** [comment]
I just tested my sample app. If I go to `localhost:3000/junk` I get a Chakra styled page and if I go back the styles are still applied.
These are what I have in `root.tsx` for root Error and Catch boundaries:
```jsx
export function ErrorBoundary({ error }: { error: Error }) {
  console.error(error);
  return (
    <Document title="Error!">
      <ChakraProvider theme={theme}>
        <Layout>
          <Box>
            <Heading as="h1">There was an error</Heading>
            <Text>{error.message}</Text>
            <Divider />
            <Text>
              Hey, developer, you should replace this with what you want your
              users to see.
            </Text>
          </Box>
        </Layout>
      </ChakraProvider>
    </Document>
  );
}

// https://remix.run/docs/en/v1/api/conventions#catchboundary
export function CatchBoundary() {
  let caught = useCatch();

  let message;
  switch (caught.status) {
    case 401:
      message = (
        <p>
          Oops! Looks like you tried to visit a page that you do not have access
          to.
        </p>
      );
      break;
    case 404:
      message = (
        <Text color='red.400'>Oops! Looks like you tried to visit a page that does not exist.</Text>
      );
      break;

    default:
      throw new Error(caught.data || caught.statusText);
  }

  return (
    <Document title={`${caught.status} ${caught.statusText}`}>
      <ChakraProvider theme={theme}>
        <Layout>
          <h1>
            {caught.status}: {caught.statusText}
          </h1>
          {message}
        </Layout>
      </ChakraProvider>
    </Document>
  );
}
```

**Comment by South-Paw** [comment]
@primos63 have created a reproduction repo here: https://github.com/South-Paw/remix-chakra-reproduction

This was just created using `npx create-remix@latest` and then following the [setup guide](https://chakra-ui.com/guides/getting-started/remix-guide) to step 2

### Reproduction steps

(just so we're on the same page)

1. Pull repo
2. `npm i`
3. `npm run dev`
4. Open localhost:3000
  - Styles loaded correctly ✅ 
6. Using the link on the top of the page, navigate to `No Route`
  - CatchBoundary hit
  - Styles lost ❌ 
7. Refresh `No Route` page
  - Styles loaded correctly ✅ 
8. Using the link on the top of the page, navigate to `Home`
  - Styles lost ❌ 
9. Refresh `Home` page
  - Styles loaded correctly ✅ 

(repeat above with `Error` page, same results)

Loading the routes manually (ie; typing into the address bar) loads the styles correctly but upon navigation they're lost again and styles remain loaded between valid routes just fine (see "Real route")

Hopefully you can see the same results as I do!

**Comment by primos63** [comment]
The `<Scripts />` in `root.tsx` is what is causing your problem. If you comment out the tag the nav layout is fine.
Not sure if that is something with SSR or not. I'll look into it.

**Comment by South-Paw** [comment]
> The `<Scripts />` in `root.tsx` is what is causing your problem.

The create-remix put the Scripts tag there, not something I changed

> Not sure if that is something with SSR or not. I'll look into it.

Thank you for taking the time to help 🙏 

I'll also keep playing with things and see if I can help any more

**Comment by JClackett** [comment]
Also having the exact same issue as @South-Paw, any ideas what could be causing this?

**Comment by pjtf93** [comment]
I'm having the same issue as @South-Paw and @JClackett.

**Comment by primos63** [comment]
@South-Paw This issue has been driving me crazy. I began to wonder if the same issue happens with Styled Components and it does! I know they work better with CSS and after going through this process I can understand why, but they did post a working CSS-in-JS example in their docs. However, I don't really think they tested it. Even that example has an error.
Anyway, I solved the issue for Styled Components and hopefully the same will translate to Emotion based projects. I'll post what I know and what I've done once I've had a chance to test it.

**Comment by JClackett** [comment]
> @South-Paw This issue has been driving me crazy. I began to wonder if the same issue happens with Styled Components and it does! I know they work better with CSS and after going through this process I can understand why, but they did post a working CSS-in-JS example in their docs. However, I don't really think they tested it. Even that example has an error.
> 
> Anyway, I solved the issue for Styled Components and hopefully the same will translate to Emotion based projects. I'll post what I know and what I've done once I've had a chance to test it.
> 
> 

Eagerly awaiting this fine work you're doing! I refuse to use remix unless it's possible to use chakra, there's no way back after you've used the chak.

**Comment by primos63** [comment]
Well my thoughts were something along the same lines, but the execution of it I was struggling with.
All credit goes to Luc Vauvillier on the Material UI repo for the [solution](https://github.com/mui-org/material-ui/issues/30436) and Rob Gilber on Remix's Discord for pointing me to it.

In my test app, I do not put the `ChakraProvider` into the `entry.server.tsx` and `entry.client.tsx`. I put it in `root.tsx` as a wrapper around `{children}`. In the server, the markup ended up having a `<span></span>` appended which caused an error.

Now it can be a **Happy New Year!**

**Comment by JClackett** [comment]
@primos63 I also have the ChakraProvider in the root.tsx file, but still having the same issues. Could you maybe share an example of your setup?

**Comment by primos63** [comment]
@JClackett You can get the sample I created from my [Github](https://github.com/primos63/chakra-remix-example)

**Comment by pjtf93** [comment]
Thanks for the solution! @primos63

**Comment by JClackett** [comment]
Thanks @primos63 !!

**Comment by primos63** [comment]
@South-Paw Well I understood what the problem was but thanks to the network I was directed to a solution.
Yes there's an issue with the color mode. There is no matter what you are using. That's because of the way dark mode is implemented. I was looking at other techniques, but then other issues, questions and Discord questions have delayed that.
As for the docs, I have no specific plans on updating them. There was talk on Discord about getting my example into the docs. That was the last I heard. You want to take on that task, be my welcome guest :)

**Comment by lcswillems** [comment]
Are all the issues mentionned here known from the Remix team?

**Comment by andrerpena** [comment]
@primos63 thanks for that. Your repository stops working after upgrading to Remix `1.2.3` though. But thanks again for doing that :D

**Comment by JClackett** [comment]
Our team's boilerplate seems to still be working...
Example source and deployment.

https://github.com/NoQuarterTeam/boilerplate-remix
https://boilerplate-remix.noquarter.co

**Comment by jongbelegen** [comment]
While I'm not using Chakra UI, I am using emotion/styled and had the same problem that all my styles got lost after hitting a 404. 
I tried following the [remix guide](https://chakra-ui.com/guides/getting-started/remix-guide), while this did apply the styles after hitting a 404 it only applied them after hydration it seems. So you would still see an unstyled page for a second.

For me, the easiest 'fix' was to build a 404 page myself so I never run in to this problem to begin with:

in routes/$404.tsx
```
import { json, LoaderFunction } from "remix";

export const loader: LoaderFunction = async () => {
  return json(
    {},
    {
      status: 404,
    }
  );
};

export default function notFound() {
  return (
    <Container>
      <Heading as="h1" mt={6}>
        404: Not found
      </Heading>
    </Container>
  );
}
```
A nice result is that I don't need any of the serverside code. Hope it helps :-)

**Comment by jongbelegen** [comment]
I'm not using any component library but experienced the same problem with just emotion without any SSR configuration.
This example finally solved the catchBoundary problem for me:
https://github.com/mui/material-ui/blob/master/examples/remix-with-typescript

**Comment by barbinbrad** [comment]
For anyone still trying to get Chakra color mode working with Remix without the flashing, one workaround is to follow this [guide](https://www.mattstobbs.com/remix-dark-mode/#1-naive-dark-mode-switch) -- drop in the Chakra specifics, and finally when you go to use the component do something like this:

```ts
// app/components/Navigation.tsx
import { useColorMode } from '@chakra-ui/react'
import { useTheme } from '~/theme'
import type { Theme } from '~/theme'

const [, setTheme] = useTheme();
const { setColorMode } = useColorMode();

  const toggleTheme = () => {
    setTheme((prevTheme) => {
      const newTheme = (prevTheme === Theme.LIGHT ? Theme.DARK : Theme.LIGHT);
      setColorMode(newTheme);
      return newTheme;
    });
  };
```

That should keep your application and Chakra in sync (in the absence of a better solution). 

Here's a repo: [https://github.com/barbinbrad/remix-chakra](https://github.com/barbinbrad/remix-chakra)

**Comment by JClackett** [comment]
> > Our team's boilerplate seems to still be working... Example source and deployment.
> 
> > 
> 
> > https://github.com/NoQuarterTeam/boilerplate-remix https://boilerplate-remix.noquarter.co
> 
> 
> 
> I am using this boilerplate but i am facing some issues, will you be available to help me out with some stuff?

@felixyeboah post and issue/start a discussion in our repo
