### ISSUE TITLE
Add tag video integration with chakra-ui

### ISSUE THREAD

**Issue by pauloreis7** [chakra-ui/chakra-ui#5172]
### Description

The current project does not have an integration with HTML5's video tag, and the documentation does not talk about the lack of such functionality.

### Problem Statement/Justification

It would be a great idea to have the integration of the chakra-ui library with the video tag because of the great use that this tag has in various applications and is used in everyday life.

This would make the tool more complete.

Something important to note is that the official chakra-ui documentation does not say that the video tag has no integration with the tool and the user will have to use it natively, the lack of this information can cause doubt to the user about how to apply the video tag in a project with chakra-ui safely. If the integration is not done, I believe that the documentation should make clear the lack of this feature and guide the user through the best way.

### Proposed Solution or API

Perform a simple abstraction, integrating the video tag into a Video component that brings all the video properties and works best with the rest of the chakra-ui tool, bringing in the most common functionalities in which the video tag is used. A simple solution design to integrate an HTML tag to the tool as it is done with Text tags, Box, etc.

### Alternatives

Since this is a simple integration with a widely used HTML tag, the only alternative is that if the functionality is not done, the documentation should inform the user about the lack of this feature and guide them through the best way to apply the video to a chakra-ui project, thus making the user less confused.

**Comment by primos63** [comment]
Thanks for your input. I don't believe this is necessary as you can achieve this today without a special component using the `as` prop. It supports all of the video specific attributes.

I use this in a CodeSandbox of examples for theming components.
```jsx
  <Box
      as='video'
      controls
      src='https://archive.org/download/BigBuckBunny_124/Content/big_buck_bunny_720p_surround.mp4'
      poster='https://peach.blender.org/wp-content/uploads/title_anouncement.jpg?x11217'
      alt='Big Buck Bunny'
      objectFit='contain'
      sx={{
        aspectRatio: '16/9'
      }}
  />
```
And if you're looking to embed a YouTube video:
```jsx
  <Box
      as='iframe'
      src='https://www.youtube.com/embed/wI2vqXsjsIo'
      width='100%'
      sx={{
        aspectRatio: '16/9'
      }}
  />
```

I will close this issue. If there's something I missed we can revisit.

**Comment by cameronelliott** [comment]
This issue was very helpful for me, but it needed on small tweak:
Change alt to title to pass typescript checking.

**Comment by iamamitkumarsaini** [comment]
how to enable autoplay in iframe?

**Comment by primos63** [comment]
For YouTube embedded videos:
```javascript
  <Box
      as='iframe'
      src='https://www.youtube.com/embed/wI2vqXsjsIo?autoplay=1&mute=1'
      width='100%'
      allow='autoplay'
      sx={{
        aspectRatio: '16/9'
      }}
  />
  ```
  
  For other sourced videos:
  ```javascript
  <Box
      as='video'
      controls
      autoplay
      src='https://archive.org/download/BigBuckBunny_124/Content/big_buck_bunny_720p_surround.mp4'
      poster='https://peach.blender.org/wp-content/uploads/title_anouncement.jpg?x11217'
      alt='Big Buck Bunny'
      objectFit='contain'
      sx={{
        aspectRatio: '16/9'
      }}
  />
  ```

**Comment by iamamitkumarsaini** [comment]
Thanks for the solution.  I was not putting autoplay in url that's why it was not working.  Thanks to you.  Solved my problem.

**Comment by SankhojjalChatterjee** [comment]
How do one add multiple video formats in src.
i have .mp4 and .ogg formats coming and Safari doesn't supports .ogg.

So how to pass both format and let browser decide.

**Comment by Tasin5541** [comment]
> Thanks for your input. I don't believe this is necessary as you can achieve this today without a special component using the `as` prop. It supports all of the video specific attributes.
> 
> I use this in a CodeSandbox of examples for theming components.
> 
> ```js
>   <Box
>       as='video'
>       controls
>       src='https://archive.org/download/BigBuckBunny_124/Content/big_buck_bunny_720p_surround.mp4'
>       poster='https://peach.blender.org/wp-content/uploads/title_anouncement.jpg?x11217'
>       alt='Big Buck Bunny'
>       objectFit='contain'
>       sx={{
>         aspectRatio: '16/9'
>       }}
>   />
> ```
> 
> And if you're looking to embed a YouTube video:
> 
> ```js
>   <Box
>       as='iframe'
>       src='https://www.youtube.com/embed/wI2vqXsjsIo'
>       width='100%'
>       sx={{
>         aspectRatio: '16/9'
>       }}
>   />
> ```
> 
> I will close this issue. If there's something I missed we can revisit.

How can we implement the `onLoad` handler for video with this method?

**Comment by gomesalexandre** [comment]
> How can we implement the `onLoad` handler for video with this method?

@Tasin5541 `onCanPlay`/`onCanPlayThrough` can be used to achieve this https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canplaythrough_event

Seems like `onLoad` being allowed at type-level is just `DOMAttributes` not being narrowed down to "Media Events" when using a `<Box />`, the prop will be passed through the native element as chakra's `shouldForwardProp(prop)` will return true for this prop, but it actually does nothing for videos.
