### ISSUE TITLE
Toast placement: 'ToastPositionWithLogical' can't be used to index type 'LogicalPlace mentMap'.

### ISSUE THREAD

**Issue by mordv** [chakra-ui/chakra-ui#5173]
### Description

During build of my project I get internal chakra typescript error: Element implicitly has an 'any' type because expression of type 'ToastPositionWithLogical' can't be used to index type 'LogicalPlace mentMap'.

### Link to Reproduction

https://github.com/chakra-ui/chakra-ui/blob/main/packages/toast/src/toast.placement.ts#L42

### Steps to reproduce

tsc for file mentioned above

### Chakra UI Version

latest

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
