### ISSUE TITLE
`colSpan` property on tables do not accept responsive values

### ISSUE THREAD

**Issue by chrysb** [chakra-ui/chakra-ui#5179]
### Description

I'd like to be able to:

```
<Td colSpan={{ base: 1, md: 3 }}>
```

### Problem Statement/Justification

Some tables require different behavior on mobile vs desktop

### Proposed Solution or API

Add support for responsive values to `colSpan`

**Comment by segunadebayo** [comment]
Hi @chrysb,

Thanks for opening this issue. `colSpan` is a native HTML property of the `td` element and not a CSS property hence we won't be able to support this.

Thanks for understanding.

**Comment by 1mehdifaraji** [comment]
I did try this and it works without a typescript error 

```typescript
   <GridItem
            colSpan={{
              base: 1,
              md: 2,
            }}>
```
