### ISSUE TITLE
Request to add basic Form component

### ISSUE THREAD

**Issue by Moro-Code** [chakra-ui/chakra-ui#518]
**Is your feature request related to a problem? Please describe.**
Hey, first of all this is very minor, just a little annoying I find. While there are FormControl components there is no actual Form component. This makes it kind of awkward since for example if you wanted to do dynamic sizing based on breakpoints you'd have to do CSS for the form element and use style props for the FormControl. 

**Describe the solution you'd like**
Just need to add a Form component with some basic style props

**Comment by segunadebayo** [comment]
Hi @Moro-Code,

Thanks for this feedback. Could you give an example of the this scenario where you need a Form component? A pseudo-code or a CodeSandbox link will be helpful.

**Comment by JClackett** [comment]
@Moro-Code a form doesnt really do much visually, so what would having this as a component provide?

Can always just use a Box and then use as="form" then make your own Form component that forwards all props, including breakpoints etc

```
function Form(props) {
	return (
		<Box as="form" onSubmit={props.onSubmit} {...props}
			{props.children}
		</Box>
	)
}
```

use it like:

```
<Form my={4} bg="green" width={{base: "100%", md: "50%"}} onSubmit={handleSubmit}>
	<Input name="email" />
</Form>
```

**Comment by tmikeschu** [comment]
If anyone is trying to do this with TypeScript and passing a ref, I'm using the following workaround:

```tsx
const FormBox = Box as ChakraComponent<"form">;
```

Which will allow you to pass a form ref

```tsx
const ref = React.useRef<HTMLFormElement>(null)
return <FormBox as="form" ref={ref} ... />
```

Otherwise you'll get a type error on the ref, as it expects a `div`.

<img width="937" alt="image" src="https://user-images.githubusercontent.com/19894032/99211400-3a340f00-2796-11eb-9637-658a555b0f0d.png">

**Comment by vogler** [comment]
> @Moro-Code a form doesnt really do much visually, so what would having this as a component provide?
> 
> Can always just use a Box and then use as="form" then make your own Form component that forwards all props, including breakpoints etc
> 
> ```js
> function Form(props) {
> 	return (
> 		<Box as="form" onSubmit={props.onSubmit} {...props}>
> 			{props.children}
> 		</Box>
> 	)
> }
> ```
> 
> use it like:
> 
> ```js
> <Form my={4} bg="green" width={{base: "100%", md: "50%"}} onSubmit={handleSubmit}>
> 	<Input name="email" />
> </Form>
> ```

In the example below, this leads to the input losing focus when typing:

![Kapture 2021-03-17 at 18 18 56](https://user-images.githubusercontent.com/493741/111509729-4ed8e180-874d-11eb-8b2b-0a522e9ade42.gif)
~~~ts
  const [value, setValue] = useState('');
  return (<>
    <form style={{width: '100%'}}>
      <Input value={value} onChange={event => setValue(event.target.value)} />
    </form>
    <Form w='100%'>
      <Input value={value} onChange={event => setValue(event.target.value)} />
    </Form>
  </>);
~~~

I wasn't able to reproduce it on codesandbox.io though.
I'm fine with `form` for now, just wondered what the reason for the different render behavior is.
