### ISSUE TITLE
Auto import working inconsistently after updating VSCode to v1.60.1

### ISSUE THREAD

**Issue by IHIutch** [chakra-ui/chakra-ui#5183]
### Description

When I try to use a component, I expected it to auto import when I hit Return, instead nothing happens when I hit Return and I have to add the import manually

### Steps to reproduce

You can clone this repo and try it in VS Code ^1.60.1: https://github.com/IHIutch/auto-import-test

1. Have imported components from '@chakra-ui/react'
2. Attempt to import a new component (eg. GridItem)
3. Component will not be added to existing list of imported components

** If you're not importing from '@chakra-ui/react' and instead importing from say, '@chakra-ui/layout', everything should work fine, you'll just be importing from multiple subdirectories.

### Chakra UI Version

1.6.7

### Additional Information

Maybe this is expected behavior? I don't see it documented anywhere and it seems like it was working before so I figured I'd create an issue for it.

Also documented [here](https://github.com/microsoft/TypeScript/issues/45921) and [here](https://github.com/chakra-ui/chakra-ui/discussions/4608)

[A solution was suggested](https://github.com/microsoft/TypeScript/issues/45921#issuecomment-943767005), but I'm not sure what it means

**Comment by lucasmaffazioli** [comment]
@IHIutch I've upgraded typescript to 4.5.2, eslint to 8.3.0, and Chakra React to 1.7.2 and it seems that solved the issue for me, but only on new files it seems, maybe my old ones has weird imports

**Comment by segunadebayo** [comment]
Hi @IHIutch,

We simplified our build system recently to fix most of these issues. Kindly upgrade to the latest version.

**Comment by IHIutch** [comment]
Awesome, thanks

**Comment by cevr** [comment]
@segunadebayo This did not seem to fix the issues on my end after updating to 1.7.2
