### ISSUE TITLE
<Select/> The placeholder of a select should not be selectable in the select options.

### ISSUE THREAD

**Issue by Charlesdoiron** [chakra-ui/chakra-ui#5184]
### Description

The placeholder of a select should not be selectable in the select options.

### Link to Reproduction

/

### Steps to reproduce

Hello ! Thanks a lot for this amazing lib !
I need to use the select with a non-clickable placeholder.
Is it possible ?

Eg: 

```
<Select placeholder='Select option'>
  <option value='option1'>Option 1</option>
  <option value='option2'>Option 2</option>
  <option value='option3'>Option 3</option>
</Select>
```

![Capture d’écran 2021-12-02 à 12 34 56](https://user-images.githubusercontent.com/4417717/144414711-ac15a4fb-32da-4a69-9248-93986a80c5f5.png)

![Capture d’écran 2021-12-02 à 12 35 05](https://user-images.githubusercontent.com/4417717/144414727-59d5f14d-2293-4c1f-8509-0610bc99f0c7.png)

### Chakra UI Version

1.7.2

### Browser

All

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @Charlesdoiron,

This isn't possible to do while keeping the placeholder visible. The way to achieve that is to pass `disabled` to the placeholder `option` but that'll make the first valid option the default placeholder, which isn't the intended side effect.

Try it here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

I'd recommend that you turn off the placeholder by passing `placeholder=""` and then solving that UI problem on your end. If you can solve it with native select element then you can apply it to the component.

**Comment by Charlesdoiron** [comment]
Hi @segunadebayo , thanks for your quick reply.

It work perfectly with :

`<Select placeholder=''>
<option value="" disabled>{placeholder}</option>
  <option value='option1'>Option 1</option>
  <option value='option2'>Option 2</option>
  <option value='option3'>Option 3</option>
</Select>`

Thanks !!
