### ISSUE TITLE
the Drawer cannot be closed when ...!

### ISSUE THREAD

**Issue by Ali-Hussein-dev** [chakra-ui/chakra-ui#5196]
### Description

When using the Drawer with "bottom" placement and has a long content in a real-mobile device, it cannot be closed!

### Link to Reproduction

https://codesandbox.io/s/naughty-monad-hv7du?file=/src/index.tsx

### Steps to reproduce

1. Go to ['LINK'](https://hv7du.csb.app/) on a real mobile device
2. Click on 'Open'

### Chakra UI Version

1.7.2

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by primos63** [comment]
@Ali-Hussein-dev I opened the link on my mobile, Android, and did not see the issue you are describing. I opened the drawer and could close the content. I tried scrolling and then touched the close button and it worked.

**Comment by Ali-Hussein-dev** [comment]
which browser did you use?

**Comment by Ali-Hussein-dev** [comment]
I used Brave, Firefox Chrome, and Chrome Canary on my android device!

**Comment by malashevskyi** [comment]
Works on my phone in all mentioned browsers. What is your android version?

**Comment by Ali-Hussein-dev** [comment]
android 8.0.0

**Comment by primos63** [comment]
Interesting. I have an Android 7.0 mobile with DuckDuckGo browser v5.102.3 and it works. I tried with Chrome browser v96.0.4664.45 and it does not. It appears that the header of the drawer slides under the address bar.
Thought maybe it was the Android version, but I tried it on an Android 12 with Chrome and Brave and it does not work, but it does work with the DuckDuckGo browser.

**Comment by Ali-Hussein-dev** [comment]
A workaround I made is to change the drawer placement to the side! 
I think if the drawer were swipeable it would have been easier to close it with a swipe to the bottom regarding if the close button is visible or not!
