### ISSUE TITLE
When I use the safari browser, an error is reported, Firefox and Google browsers are normal

### ISSUE THREAD

**Issue by shenhaoguangDayDayUp** [chakra-ui/chakra-ui#5197]
### Description

When I use the safari browser, an error is reported .

### Link to Reproduction

https://test.zhanheyibiao.com/#/cube

### Steps to reproduce

![image](https://user-images.githubusercontent.com/17617821/144769663-b35b22ec-5b28-4bcd-82cc-ab5e56c7059d.png)

### Chakra UI Version

1.7.2

### Browser

safari 13.1.3

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Looking forward to your reply

**Comment by primos63** [comment]
Please provide the version of Safari this occurred on.

**Comment by shenhaoguangDayDayUp** [comment]
> Please provide the version of Safari this occurred on.

Ok.

**Comment by primos63** [comment]
[Safari support](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList) for `MediaQueryList inherits EventTarget` began in version 14. Version 13.1.3 was released on October 15, 2019. Version 14 was released on September 16, 2020 and version 15 was released on September 20, 2021.
 
 The `addListener` and `removeListener` API methods were deprecated.
 > Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.
 
 I would advise updating your browser to version 14 or greater; otherwise, you will need to use an earlier version of Chakra.

**Comment by shenhaoguangDayDayUp** [comment]
> [Safari support](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList) for `MediaQueryList inherits EventTarget` began in version 14. Version 13.1.3 was released on October 15, 2019. Version 14 was released on September 16, 2020 and version 15 was released on September 20, 2021.
> 
> The `addListener` and `removeListener` API methods were deprecated.
> 
> > Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.
> 
> I would advise updating your browser to version 14 or greater; otherwise, you will need to use an earlier version of Chakra.

OK,thanks for your reply.

**Comment by primos63** [comment]
I'm going to close this for now as it's with an older browser which doesn't support the MediaQueryList's add/removeEventListener.
Will revisit this if it becomes a more common occurrence.

**Comment by mwisner** [comment]
Hi @primos63,

Sorry for raising a question in an older thread.

It seems like Safari 13 support was dropped in `1.7.3`, but up until that specific version (including `1.7.2`) Safari 13 was working with Chakra. Given 1.7.2 -> 1.7.3 is a minor patch change, I was wondering if you'd consider 
https://www.designcise.com/web/tutorial/how-to-fix-the-javascript-typeerror-matchmedia-addeventlistener-is-not-a-function for a potential solution to add back Safari 13 support.

I'd be happy to work on a PR, but before I do I just want to make sure this is something that has a reasonable chance of getting accepted into the codebase. 

For us and our projects, we still have enough Safari 13 users that we must continue to support it. It is understandable if Chakra is not interested in supporting Safari 13, but I wanted to double confirm that before starting to look for alternative workaround solutions.

**Comment by primos63** [comment]
@mwisner Sorry, I got caught up in other things and completely forgot about this. I had chatted with Sage several weeks ago about this. I'm going to add a fallback for the deprecated calls to the code. I'll reopen this issue and have a PR for it soon.
Thanks for pinging me about this.

**Comment by primos63** [comment]
@mwisner Could you please open my [CodeSandbox](https://codesandbox.io/s/usemediaquery-backward-compat-fj5yo) on Safari 13 to verify that it does work?
I tried to go back to Firefox version 44, but that is 6 years old and won't handle the JavaScript.

**Comment by shenhaoguangDayDayUp** [comment]
> 

Ok, Is the only way to deal with it now is to downgrade?

**Comment by Edjevw12** [comment]
> > 
> 
> Ok, Is the only way to deal with it now is to downgrade?

Fix: #5474

**Comment by noobinthisgame** [comment]
This has been fixed with @chakra-ui/react@1.8.2 @TimKolberger

**Comment by shenhaoguangDayDayUp** [comment]
> This has been fixed with @chakra-ui/react@1.8.2 @TimKolberger

Hi~,When I upgraded to version 1.8.2 it still reported the same error
https://priceless-cori-be3043.netlify.app/#/home

**Comment by TimKolberger** [comment]
Just did a quick search:

The mentioned PR addressed useBreakpoint, this issue is in the colormode package in addListener: https://github.com/chakra-ui/chakra-ui/blob/main/packages/color-mode/src/color-mode.utils.ts

**Comment by shenhaoguangDayDayUp** [comment]
> Just did a quick search:
> 
> The mentioned PR addressed useBreakpoint, this issue is in the colormode package in addListener: https://github.com/chakra-ui/chakra-ui/blob/main/packages/color-mode/src/color-mode.utils.ts
Yes I see it, I wonder if there is a problem here?

<img width="530" alt="image" src="https://user-images.githubusercontent.com/17617821/157186999-f84bc0f6-f3fb-44b1-9478-aaaa5f846856.png">
<img width="629" alt="image" src="https://user-images.githubusercontent.com/17617821/157187562-a8133f1a-3d88-4ce3-b13a-d1a95f80e4b1.png">
<img width="717" alt="image" src="https://user-images.githubusercontent.com/17617821/157187633-1e321a8a-3a88-495d-ae7c-796acf0b164f.png">

**Comment by TimKolberger** [comment]
You are close 👍 
Safari <14 does not support `mediaQueryList.addEventListener`.

https://github.com/chakra-ui/chakra-ui/blob/577aeb92dbd6b1e309b973c1864601b936ef20bc/packages/color-mode/src/color-mode.utils.ts#L69-L73

We need a fallback to `mediaQueryList.addListener` like in PR #5474

**Comment by shenhaoguangDayDayUp** [comment]
> 



> You are close 👍 Safari <14 does not support `mediaQueryList.addEventListener`.
> 
> https://github.com/chakra-ui/chakra-ui/blob/577aeb92dbd6b1e309b973c1864601b936ef20bc/packages/color-mode/src/color-mode.utils.ts#L69-L73
> 
> We need a fallback to `mediaQueryList.addListener` like in PR #5474

Thank you for your maintenance, you are great👍

**Comment by skrisztianidealap** [comment]
Hey folks, apparently this case is still an issue as of **@chakra-ui/react": "^1.8.7**. - any plans on making this feature backward compatible?
