### ISSUE TITLE
[Checkbox] [Radio] Add 'isReadOnly' attribute

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#52]
While checkboxes and radio buttons may be disabled, they cannot be made read-only through Chakra UI. According to the HTML specification, every input type [has a `readonly` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Attributes_common_to_all_input_types).

I would like to propose adding an `isReadOnly` prop to checkable input fields, as it is suitable for making forms which cannot be modified after submission.

**Comment by kripod** [comment]
@segunadebayo This doesn’t seem to be stale for me. Has it been solved?

**Comment by tioluwani94** [comment]
Hi @kripod, this has been fixed in the dev-ts branch.

**Comment by kripod** [comment]
Awesome, thank you!
