### ISSUE TITLE
[Docs] Space table should refer to font size

### ISSUE THREAD

**Issue by Machinezero** [chakra-ui/chakra-ui#520]
**Describe the bug**
When viewing the table which shows the conversion of the space value from **rem** to **px**, it is not mentioned that a base **font-size** of **16px** is needed for this table to be correct. Although it is says that **0.25rem** converts to **4px** by default in most common browsers, it is not conveyed that it is because most common browsers use **16px** as a default base **font-size**, and that this conversion becomes invalid if this font-size is changed.

![image](https://user-images.githubusercontent.com/4267140/77535361-64952d00-6e92-11ea-8cb6-34a24d523304.png)

**Expected Behavior**
Should mention that this table is correct only if a base **font-size** of **16px** is used.

**To Reproduce**
1. Go to [spacing](https://chakra-ui.com/theme#spacing) section in theme page
2. Read space conversion table description 

**Suggested solution(s)**
Add to the description that rem is based on the **font-size** of the root element, and that most browsers default to **16px**, which the table is based on.

**Comment by segunadebayo** [comment]
@Machinezero, thanks for pointing this out.

It has been fixed and docs will be updated shortly
