### ISSUE TITLE
`startWithEditView` prop on `Editable` is not working?

### ISSUE THREAD

**Issue by baptisteArno** [chakra-ui/chakra-ui#5201]
### Description

When I try to set `startWithEditView` to `true` on an `Editable` component, it doesn't start in edit view as it's supposed to.

### Link to Reproduction

https://codesandbox.io/s/pedantic-mestorf-60cq0?file=/src/App.tsx

### Chakra UI Version

1.6.6

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by primos63** [comment]
It is in edit view, but the focus on the Input field is not initially set. Is this [CodeSandbox example](https://codesandbox.io/s/editable-focus-tw9k2?file=/src/App.tsx) what you are expecting to happen?

**Comment by baptisteArno** [comment]
Yes, that's exactly it! 👌

**Comment by Stephen-Tsen** [comment]
I also expected the input to be focused.
