### ISSUE TITLE
Tooltip arrow does not get a border when a border as a tooltip prop

### ISSUE THREAD

**Issue by chrisfernandes102** [chakra-ui/chakra-ui#5203]
### Description

When I passed in the prop `border` to tooltip I would expect the arrow to also get this border. However, the arrow does get the border.

### Link to Reproduction

https://codesandbox.io/s/dreamy-cori-ydedu?file=/src/App.js

### Steps to reproduce

Hover over the tooltip and notice that the border is not around the tooltip arrow.

### Chakra UI Version

1.6.10

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by bryg217** [comment]
Hello, looking to help out!  Would it be possible to get this issue assigned to me?  All the best.

**Comment by jainpawan21** [comment]
@chrisfernandes102 Are you able to see the arrow icon after removing the border? I am not able to see the arrow icon.

**Comment by chrisfernandes102** [comment]
@jainpawan21 @bryg217 For some reason the code sandbox does not show the arrow. In my personal project, the arrow is showing up perfectly.

**Comment by bryg217** [comment]
@jainpawan21 @chrisfernandes102 , I ran into the same thing, not sure why I am not able to reproduce.

I just went to the documentation site and was able to reproduce it there ([here](https://chakra-ui.com/docs/overlay/tooltip#with-arrow)).

**Comment by josulliv101** [comment]
Seems the "--popper-arrow-shadow-color" css var is not being found. Not a fix but defining that var in the sx property got the border on the tooltip arrow displaying -- as a work-around at least (see example).
https://codesandbox.io/s/stupefied-fire-s36kz?file=/src/App.js

**Comment by chrisfernandes102** [comment]
@josulliv101 That is a great find. Appreciate your reaching out. I will give it a shot today!

**Comment by jainpawan21** [comment]
> Seems the "--popper-arrow-shadow-color" css var is not being found. Not a fix but defining that var in the sx property got the border on the tooltip arrow displaying -- as a work-around at least (see example). https://codesandbox.io/s/stupefied-fire-s36kz?file=/src/App.js

Thanks for sharing this. for border-width > 1px, the arrow shadow is not picking the width. It remains 1px;

**Comment by CalvinChhour** [comment]
Looks like they are hard coded as 1px borders right now.

https://github.com/chakra-ui/chakra-ui/pull/6412
This change will resolve the issue I believe.

**Comment by Tenkir** [comment]
This is the same root cause as https://github.com/chakra-ui/chakra-ui/issues/5934

As @CalvinChhour mentioned, I have had a PR open for sometime [here](https://github.com/chakra-ui/chakra-ui/pull/6412), just needs review from a maintainer.

**Comment by Tenkir** [comment]
Bumping this as it was closed as stale, but a PR fix has been open for 7 months without comment.

**Comment by alex-fung** [comment]
Bump on this ☝️ , seems like a great PR
