### ISSUE TITLE
Select dropdown arrow icon stay in the right with RTL direction

### ISSUE THREAD

**Issue by aliHunter-0** [chakra-ui/chakra-ui#5204]
### Description

The select dropdown arrow stay in the right side with RTL so this causes a ui bug with the text inside

### Link to Reproduction

https://codesandbox.io/s/laughing-fermat-ppesv?file=/src/index.tsx

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

1.7.2

### Browser

Mozilla Firefox 94.0.2

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

![dropdown](https://user-images.githubusercontent.com/80057449/145088359-79ba9685-0751-48b7-a70c-eb639340be11.png)

**Comment by segunadebayo** [comment]
Hi @aliHunter-0,

To set up RTL in Chakra UI, you also need to set the direction property in the theme `theme.direction=rtl`.

Here's how to get it working:

```js
<ChakraProvider theme={extendTheme({ direction: "rtl" })}>
    <App />
  </ChakraProvider>
```
