### ISSUE TITLE
Fine tuning components using emotion

### ISSUE THREAD

**Issue by olup** [chakra-ui/chakra-ui#521]
Hi, thanks for this amazing work.

Using chakra for a production project, one that needs branding, I was wondering what strategies could be used to deeply theme the components, more than what styled system let you do and with emotion dx. Something like applying  styles over a component and reexport it. But what about complex ones ? I don't think chakra publish any static  classnames to get a hold onto ?

Thanks !

**Comment by segunadebayo** [comment]
Hi @olup. 

I understand what you mean. At the moment, Chakra doesn't provide any classname to hold onto, we're looking into this for the next release.

The walkaround would be to pass the styles you need to those components. I believe almost every component styles can be overridden.  This is a slightly painful approach and I understand.

In the next release, we have a solution for this.

Thanks.
