### ISSUE TITLE
Blur filter on `Box` component.

### ISSUE THREAD

**Issue by erickponce** [chakra-ui/chakra-ui#5217]
### Description

Hello there! 👋

The possibility to add `blur` effects on `Box` component.
Something like the utility `filter blur-lg` from tailwindcss, and similar with the `Gradient` feature Chakra UI have.

I'm not quite sure if this request was already made and was decided to not implement it, if so, I apologize. 😅

Thank you for this amazing lib!

### Problem Statement/Justification

It would enable more great customization for Chakra UI. Like transparent overlays with blur effects.

Currently im looking for a UI library that allows me to implement a specific design system on top of it.
Chakra UI is great! And the amount of components and features are impressive, so I think this customization feature would be great to have.

### Proposed Solution or API

```tsx
<Box w='100%' h='200px' bgFilter blur="md" bgOpacity='0.8' />
```

or

```tsx
<Box w='100%' h='200px' filter='blur(md)' bgOpacity='0.8' />
```

### Additional Information

With this feature it will be possible to create elements like these:

![image](https://user-images.githubusercontent.com/449033/145459995-437b42ca-9b5f-48ae-9341-5e8f322c58eb.png)

![image](https://user-images.githubusercontent.com/449033/145460116-a05ec4a9-75ae-4919-9886-810e512a3f6f.png)

**Comment by TimKolberger** [comment]
I think this is what you are looking for:

```tsx
<Box backdropFilter="auto" backdropBlur="2px" />
```

[see CodeSandbox](https://codesandbox.io/s/wizardly-zeh-wh21h?file=/src/index.tsx)

There is a `blur` scale in the theme, so you could add default values to your chakra theme like this:

```tsx
const customTheme = extendTheme({ 
  blur: {
    sm: "1px",
    md: "2px",
    lg: "4px"
  }
})
```

and use them:

```tsx
<Box backdropFilter="auto" backdropBlur="md" />
```

If this solves your issue, close it please ✌️

**Comment by erickponce** [comment]
Thank you for the quick reply!

I was able to apply the opaque blur effect with a color using a little "hack" adding rgba on `bg`: `bg="rgba(0,0,0,0.3)"`

Closing the issue.
