### ISSUE TITLE
[Checkbox] onBlur is triggered onMouseDown

### ISSUE THREAD

**Issue by eugenenelou** [chakra-ui/chakra-ui#522]
**Describe the bug**

onBlur is triggered on mouseDown.

It is a problem for form validation: when the checkbox is required, a form that validate onBlur will show an error when checking the checkbox for a split second, because the onBlur is triggered before the input value changes (This is only if the checkbox had the focus already).

**Expected Behavior**

onBlur should trigger after the input value has changed.

**To Reproduce**
1. click on an input like: `<Checkbox onBlur={() => console.log('blur')} />`
2. see that the log appears on click down

**Suggested solution(s)**

**Desktop (please complete the following information):**
 - Linux
 - Firefox
 - Version 74.0

**Comment by tioluwani94** [comment]
Hi @eugenenelou, thanks for catching this. It has been fixed in the dev-ts branch and will be out in the next major release.
