### ISSUE TITLE
Popover steals focus with closeOnBlur={false}

### ISSUE THREAD

**Issue by Andarist** [chakra-ui/chakra-ui#5224]
### Description

When `closeOnBlur={false}` is used the focus is always stolen by the Popover when we tab out of it

### Link to Reproduction

https://codesandbox.io/s/goofy-antonelli-m5t4z?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/goofy-antonelli-m5t4z?file=/src/App.js
2. Click on Trigger button
3. Press Tab several times but with a delay between each press
4. Notice how focus always returns to the Popover when we tab out of it

### Chakra UI Version

1.7.3

### Browser

Chrome 96

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

Video illustrating the problem:
https://www.loom.com/share/64668e91aeb64b55b5a63cec82f5bcd5

The docs explicitly state that to trap focus in the Popover one should use some additional solution like `react-focus-lock`: https://chakra-ui.com/docs/overlay/popover#trapping-focus-within-popover . This means to me that the focus trapping in this area is not implemented by Chakra and that this is a bug because the focus should not be trapped in this Popover by default. And even if this is the desired effect - the lock should be more aggressive because right now I can see another element to be focused for a moment, before the focus gets stolen by Popover.

The focus is stolen within this `useFocusOnShow` hook:
https://github.com/chakra-ui/chakra-ui/blob/eac427c0a8ad7f945540a1b661c67429ecc2acd0/packages/popover/src/use-popover.ts#L190-L194
and its name also suggests that this shouldn't happen because this scenario doesn't involve the popover showing for the first time.

And more specifically - this happens because the `transitionend` gets fired in this case and it calls `onFocus` here:
https://github.com/chakra-ui/chakra-ui/blob/eac427c0a8ad7f945540a1b661c67429ecc2acd0/packages/hooks/src/use-focus-on-show.ts#L52

**Comment by Andarist** [comment]
bump for the stale bot

**Comment by Andarist** [comment]
Bump for stale bot

**Comment by Andarist** [comment]
Bump for stale bot

**Comment by TheXienator** [comment]
why was this closed I think the focus still is bugged

**Comment by benwiley4000** [comment]
still bugged
