### ISSUE TITLE
Add CHANGELOG / Release info to new releases

### ISSUE THREAD

**Issue by efossvold** [chakra-ui/chakra-ui#523]
First of all change for the amazing work you're doing with chakra-ui, love it.

I'd like to request some info about what's new in each release. @chakra-ui/core@0.7.0 just came out yesterday. However, there's no info in the release tag and no CHANGELOG file so how do I know what's new and if there are any breaking changes? Of course I could browse through the commits, but that takes time and it's not very user friendly. So please, a few lines about what's new/changed would be greatly appreciated.

**Comment by segunadebayo** [comment]
@efossvold, you're right and we would definitely update the changelog going forward.

In the meantime, here's where to find the changelog:
https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/CHANGELOG.md
