### ISSUE TITLE
Using `styled` with Slider or SliderFilledTrack does not work

### ISSUE THREAD

**Issue by vsylvestre** [chakra-ui/chakra-ui#5232]
### Description

When applying styles using `styled` (either from Chakra or Emotion) to the Slider or SliderFilledTrack components, it does not work. However, SliderTrack and SliderThumb do work.

### Link to Reproduction

https://codesandbox.io/s/stupefied-meadow-0hypr

### Steps to reproduce

1. Go to [this sandbox](https://codesandbox.io/s/stupefied-meadow-0hypr).
2. The `background-color: red` should be applied to all four components: Slider, SliderTrack, SliderFilledTrack and SliderThumb. But it seems like Slider and SliderFilledTrack do not receive the styling (whereas SliderTrack and SliderThumb do).

### Chakra UI Version

1.6.6

### Browser

Google Chrome 96.0.4664.93

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by primos63** [comment]
`className` props are not being applied to `Slider` and `SliderFilledTrack`.
