### ISSUE TITLE
TabIndicator does not work in RTL

### ISSUE THREAD

**Issue by oalsarhani01** [chakra-ui/chakra-ui#5235]
### Description

When I switch from LTR to RTL, TabIndicator remain in the same position

### Link to Reproduction

https://pro.chakra-ui.com/components/marketing/navbars

### Steps to reproduce

1. Go to chakra pro
2. Click on Marketing
3. click on Navbar
4. use Navbar with tabs
5. try to switch to RTL
6. see the TabIndicator
[https://www.up-00.com/i/00221/lgem43ijmivj.png
](url)

### Chakra UI Version

1.4.1

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by primos63** [comment]
As far as I know, this repo is not for Chakra Pro issues. You may want to contact Chakra-Pro support, support@chakra-ui.com.

Not sure if
> switch from LTR to RTL 

means setting the `direction` prop to `rtl`. If so, `direction='rtl'` in the open-source version changes the behavior of the arrow keys and not the positioning of the tabs. As Pro is built on top of the open source version, I assume it behaves the same. The support team for Chakra Pro should be able to verify this.

Closing this issue as it's not related to the open-source version of Chakra UI.

**Comment by oalsarhani01** [comment]
ok thank you

**Comment by oalsarhani01** [comment]
ok thank you
