### ISSUE TITLE
Bundling dev-ts packages

### ISSUE THREAD

**Issue by cschroeter** [chakra-ui/chakra-ui#524]
Is there a specific reason why you've decided to use `tsdx` to bundle your components? 
As far as I can see you don't have any additional assets besides your TypeScript files. So you could speed up your bundling by just using plain old `tsc`.

I'm expecting to see a performance increase by 90%. Let me know if I can help you with that

**Comment by segunadebayo** [comment]
@cschroeter, so far I've found `tsdx` quite reliable in releasing React TypeScript packages.

If you have other alternatives, feel free to suggest them.
