### ISSUE TITLE
Add defaultProps to Accordion

### ISSUE THREAD

**Issue by kongebra** [chakra-ui/chakra-ui#5254]
### Description

Allow developers to add `defaultProps` to `Accordion` for themeing.

### Problem Statement/Justification

I tried to add `allowToggle: true` while themeing an `Accordion`, but this does not seem to be implemented.

### Proposed Solution or API

Add `defaultProps` to `Accordion` theme options. `allowMultiple` should also be added to this.

**Comment by primos63** [comment]
Closing this as it isn't a bug. `allowToggle` is a boolean and does not equate to a CSS property. It's used by the `use-accordian` hook to toggle the open state of the accordion item.

If you want something like this in your project, you can easily wrap the AccordionComponent and set the `allowToggle` to true.
