### ISSUE TITLE
srcSet is missing in avatar component

### ISSUE THREAD

**Issue by dailycommit** [chakra-ui/chakra-ui#5256]
### Description

It seems that the srcSet prop is not being passed to the AvatarImage correctly.

### Link to Reproduction

https://codesandbox.io/s/magical-pine-89r3r

### Steps to reproduce

See: https://github.com/chakra-ui/chakra-ui/blob/b983e4ceb7c1e794c2b901ce16f12016836d40d6/packages/avatar/src/avatar.tsx#L294-L305

### Chakra UI Version

1.7.3

### Browser

not relevant

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by sohamsshah** [comment]
The `Avatar` component imports the props from `Image` component.
https://github.com/chakra-ui/chakra-ui/blob/b983e4ceb7c1e794c2b901ce16f12016836d40d6/packages/avatar/src/avatar.tsx#L240-L243

See this:
https://github.com/chakra-ui/chakra-ui/blob/b983e4ceb7c1e794c2b901ce16f12016836d40d6/packages/image/src/image.tsx?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L137-L147

To add `srcSet`, you can pretty much add it to Avatar like it is being added on an img HTML element. You can refer [this](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset)
