### ISSUE TITLE
Adding a background color to <ModalHeader /> component removes border radius

### ISSUE THREAD

**Issue by dukartbr** [chakra-ui/chakra-ui#5258]
### Description

While trying to add a background color to the header of the <Modal /> component I noticed the top two corners lose their border radius

### Link to Reproduction

https://codesandbox.io/s/nostalgic-taussig-b24x4?file=/src/index.tsx

### Steps to reproduce

Add a `bg` prop to `<ModalHeader />` component

### Chakra UI Version

1.7.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by alejandroch1202** [comment]
Same in `<ModalFooter />`

**Comment by alejandroch1202** [comment]
Same in `<ModalFooter />`, I temporary fixed it adding `sx={{ borderRadius: '20px' }}`
