### ISSUE TITLE
Controls not pulling className and style into rootProps

### ISSUE THREAD

**Issue by jamesmfriedman** [chakra-ui/chakra-ui#5269]
### Description

When adding `className` and `style` props to a component, I expected them to be on the root of the rendered HTML, but instead were on a child. This is observed on the Radio button right now, and looks to be inconsistent with Checkbox (which has the expected behavior). 

### Link to Reproduction

https://codesandbox.io/s/flamboyant-fermat-gss7j?file=/src/index.js

### Steps to reproduce

See code sandbox

### Chakra UI Version

1.6.4

### Browser

All

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

Worked on component libraries for a long time, going to share a bit of perspective that may help more than just this case.

- The Radio / Checkbox / and Switch in Chakra are composed controls. This is great because it matches the same expectation as using the HTML primitive of `radio`. Per this bug, prop forwarding becomes an issue.
- className and style are important to maintain as rootProps since other styling libraries (or just css) likely need to layout this component in some way if they aren't using styled-system or Chakras layout tools. This is the case for us.
- There are other props that we would expect to be able to be emitted onto the root DOM node. For instance `data-test-id`.
- For composed inputs, ideally there would be a `ref` to grab the root element, and an additional `inputRef` to target the input. The inverse of using `ref` for the input and `rootRef` works just as well.

Suggestions:
- Always make sure `className` and `style` are spread to the root DOM node. We found this issue because we're writing tests to ensure this behavior.
- Always make sure refs are applied to the root DOM node and references to additional nodes are exposed as needed
- Provide a way to append to the root props. A pattern like passing a prop into the component called `rootProps` would work. Also, the way Chakra's internal api is currently structured seems like support could be added for whitelist of props that end up on the root. This would greatly help the case of things like `data-test-id`.

Thank you, enjoying using Chakra!

**Comment by anubra266** [comment]
What do you think @TimKolberger ?

**Comment by TimKolberger** [comment]
Thank you this valuable insight @jamesmfriedman! I think it is a great pattern to 

> Always make sure className and style are spread to the root DOM node.
> Always make sure refs are applied to the root DOM node and references to additional nodes are exposed as needed

I think we should revisit this issue, when we are allowed to change the component API. Either with v2 or if we come to a conclusion how to manage breaking changes in the API layer of components.
