### ISSUE TITLE
Divider - `size` prop doesn't work

### ISSUE THREAD

**Issue by tannguyencse19** [chakra-ui/chakra-ui#5270]
### Description

I try `size="2px"`, `size="xl"` but doesn't work. Only if I use `borderWidth` then it works.

### Link to Reproduction

https://codesandbox.io/s/divider-size-prop-vitn2?file=/src/index.tsx

### Chakra UI Version

latest

### Browser

latest

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

- In `divider.tsx` of `chakra-ui` source-code also doesn't have `size` prop declaration but only `borderWidth` (`borderBottomWidth`, `borderLeftWidth`...).

![image](https://user-images.githubusercontent.com/62830718/146927076-582d1ac2-9b43-4ec3-9179-3e8b5b6311b5.png)

- Also, in VSCode,  `size` and `variant` props don't show suggestion. Though, `variant` prop still work, so if user want to use, they have to look up other component which used `variant`.

**Comment by primos63** [comment]
This is a documentation issue.

The `size` property listed in the `Divider` documentation should be `borderWidth`.

Depending on the orientation the `borderLeftWidth` or `borderBottomWidth` is set from a corresponding border{X}Width with the default being 1px.
```jsx
 vertical: {
      borderLeftWidth:
        borderLeftWidth || borderRightWidth || borderWidth || "1px",
      height: "100%",
    },
  horizontal: {
      borderBottomWidth:
        borderBottomWidth || borderTopWidth || borderWidth || "1px",
      width: "100%",
    },
```

**Comment by tannguyencse19** [comment]
Yeah, though I like the name `size` than `borderWidth` :smile

**Comment by primos63** [comment]
Lol and I'm the opposite as `size` is too ambiguous. `font-size`, `background-size` and such are different as they convey what they are affecting.

**Comment by segunadebayo** [comment]
Please consider using `borderWidth` or you can extend the divider's theme to include size definitions.

```jsx
const theme = extendTheme({
  components: {
    Divider: {
      defaultProps: { size: "md" },
      sizes: {
        lg: { borderWidth: "4px" },
        md: { borderWidth: "2px" },
        sm: { borderWidth: "1px" },
      },
    },
  },
})
```
