### ISSUE TITLE
Image component loads images twice if fallback prop is used

### ISSUE THREAD

**Issue by mislavmiocevic** [chakra-ui/chakra-ui#5285]
### Description

When I use the fallback prop in the Image component, I get double requests for the images in Chrome.

### Link to Reproduction

https://codesandbox.io/s/2jdpu

### Steps to reproduce

1. Open Chrome, the developer tools and go to the "Network" tab, click the "Disable cache" and filter by "Img"
2. Go to https://chakra-ui.com/ and scroll down to the "Less code. More speed" section
3. In the codesandbox example add `fallback={<div />}` and rerun the example
4. You should see "https://a0.muscache.com/4ea/air/v2/pictures/7ea52b34-8177-45ab-b5ad-d1cb83b6f006.jpg?t=r:w1200-h720-sfit,e:fjpg-c90" image loaded twice with the response 200

![Screenshot 2021-12-24 at 10 11 17](https://user-images.githubusercontent.com/67387665/147338601-af0a8fcd-e31c-4fe0-8e40-a92676b6e718.png)

https://user-images.githubusercontent.com/67387665/147339687-536947c1-a852-491d-aa06-fad87a89be80.mov

### Chakra UI Version

1.7.3

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This does not happen in Safari and Firefox.
Chrome version is Version 96.0.4664.110 (Official Build) (arm64)
macOS version is Big Sur, 11.2.3

**Comment by primos63** [comment]
The proposed fix for #5288 also fixes this one.
You can see in the [example](https://codesandbox.io/s/sandpack-project-forked-dqh98?file=/src/components/image/src/image.tsx) that the image is now only requested once.

**Comment by lcswillems** [comment]
@primos63 I can't find the PR where the fix was proposed. Do you know where it is?

**Comment by noobinthisgame** [comment]
@lcswillems This is the PR handling the image fallback https://github.com/chakra-ui/chakra-ui/pull/5680 :)

**Comment by lcswillems** [comment]
@noobinthisgame Thanks!!

**Comment by lcswillems** [comment]
@noobinthisgame In fact the PR you shared doesn't mention this issue. It doesn't seem related

**Comment by takethefake** [comment]
Hej @lcswillems 

As @noobinthisgame stated - the PR is related to this :) Hopefully, we can get it merged soon.

**Comment by lcswillems** [comment]
This should not be closed

**Comment by lcswillems** [comment]
Don't close

**Comment by TylerAPfledderer** [comment]
Per the example @mislavmiocevic provided (which comes from the home page), this issue looks to now be resolved. When I try to include either the `fallback` or `fallbackSrc` prop in the sandbox, the network does no longer shows the image request twice.

To @noobinthisgame and @takethefake, is this now confirmed?

And is there anyone else that can supply a new reproduction of this issue?

**Comment by lcswillems** [comment]
@TylerAPfledderer Which version do you use?

**Comment by TylerAPfledderer** [comment]
@lcswillems working with Chakra v2.

What I see on the network with the CSB from the home page (and an empty `<div />` in `fallback`:
![image](https://user-images.githubusercontent.com/65234762/173269389-2be8f761-7f27-4fe7-b52a-78a51f0eab8b.png)

And what it looks like when I use a local project (Next) with content supplied to `fallback` including a random image file:
![image](https://user-images.githubusercontent.com/65234762/173269497-a0fcb7f0-02ac-4720-943f-c6c22e455cd9.png)

**Comment by lcswillems** [comment]
@TylerAPfledderer Thanks for the screenshot! I am on 1.8, it should be the reason
