### ISSUE TITLE
Image component loads fallbackSrc even without error

### ISSUE THREAD

**Issue by mythosil** [chakra-ui/chakra-ui#5288]
### Description

When I pass `src` and `fallbackSrc` props to Image component, I expect that `fallbackSrc` get loaded only when the browser fails to load `src` but the browser loads both simultaneously.

### Link to Reproduction

https://codesandbox.io/s/t51j5

### Steps to reproduce

1. Open a new tab in Chrome
2. Open developer tools' network tab
3. Go to https://codesandbox.io/s/t51j5
4. You can see fallbackSrc https://via.placeholder.com/240 is loaded

### Chakra UI Version

1.7.3

### Browser

Chrome 96, Firefox 95

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Image component loads fallbackSrc when status is not "loaded". The initial value of status is "loading", so fallbackSrc get loaded.
https://github.com/chakra-ui/chakra-ui/blob/96c4aabb/packages/image/src/image.tsx#L120-L135

It might be an intended design but I think fallbackSrc should be loaded only when error occurs to suppress network traffic.

**Comment by primos63** [comment]
Changed status check from `status !== "loaded"` to `status === "failed"`. The fallback image is then only loaded when the image fails to load.
The [example](https://codesandbox.io/s/sandpack-project-forked-dqh98?file=/src/components/image/src/image.tsx) is from #5285 which this change will also fix. For this issue please comment out `fallback` and remove the `//` from `fallbackSrc`. If you add a 1 to the end of the `src` value the load will fail and the fallback will load.

**Comment by mythosil** [comment]
I found this in image.stories.tsx:
> Chakra has support for fallback images so in event the image falls to load, or while the image is loading, you can show a fallback.
https://github.com/chakra-ui/chakra-ui/blob/96c4aabb/packages/image/stories/image.stories.tsx#L17-L19

But the docs mention only "error":
> You can provide a fallback image for when there is an error loading the src of the image.
https://chakra-ui.com/docs/media-and-icons/image#fallback-support

Maybe issue #1027 is related to this behavior.

**Comment by segunadebayo** [comment]
Great thought @primos63 and thanks for opening this @mythosil.

For now, we can update the docs to reflect the true implementation.

An approach could be to include a `fallbackStrategy = "onError"  | "beforeLoadOrError"` which will determine how the fallback loading logic would be. Just an idea

**Comment by trybick** [comment]
> For this issue please comment out `fallback` and remove the `//` from `fallbackSrc`. If you add a 1 to the end of the `src` value the load will fail and the fallback will load

@primos63 Just wanted to clarify - is this the fix everyone should do to resolve this issue or do we still need someone to open PR to change status check to `status === "failed"`? (happy to volunteer)

**Comment by pedrowindisch** [comment]
@segunadebayo 

> An approach could be to include a `fallbackStrategy = "onError" | "beforeLoadOrError"` which will determine how the fallback loading logic would be. Just an idea

i'd like to implement the fallbackstrategy approach, should i open an issue to detail and develop the code?

**Comment by BenjaOliva** [comment]
Any improvements on this ? prop fallbackStategy is not available but it appears on the props of the Image component :(

**Comment by trybick** [comment]
> Any improvements on this ? prop fallbackStategy is not available but it appears on the props of the Image component :(

fallbackStrategy was added in 2.0.0
https://github.com/chakra-ui/chakra-ui/pull/5680
