### ISSUE TITLE
Responsive `alignItems` not working (simple `alignItems` works fine)

### ISSUE THREAD

**Issue by jakegiri** [chakra-ui/chakra-ui#5289]
### Description

When i set simple alignItems like `alignItems: "center"` it works correnctly. 
But when i set responsive alignItems like `alignItems: {{sm: "center", md: "left"}}`. 

Neither i can use `useBreakpointValue` hook as an work around. If i do i get this typeerror
![image](https://user-images.githubusercontent.com/24270559/147391735-530f11ec-d573-4d27-9a36-832f30f7f327.png)

### Link to Reproduction

https://codesandbox.io/s/winter-shadow-osg6m

### Chakra UI Version

1.7.2

### Browser

Google Chrome 96

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by TimKolberger** [comment]
Hi @jakegiri, 

The provided example is missing the ChakraProvider in the `_app.js`.
More info in the docs: https://chakra-ui.com/guides/getting-started/nextjs-guide

Working example:
https://codesandbox.io/s/upbeat-currying-o2wnb?file=/pages/index.js

Regarding the TS error:

> Personally I'd prefer the CSS solution over the JS solution with useBreakpoints, but for completeness:

The prop `textAlign` only accepts valid literal string types from `csstypes`.
`useBreakpointValue` accepts a Generic to provide explicit typings:

```ts
import * as CSS from "csstype";

const textAlign = useBreakpointValue<CSS.Property.TextAlign>({ 
  base: "center", 
  md: "left" 
})

//...

return <Text textAlign={textAlign}>Merry Christmas</Text>
```

Feel free to reopen this issue if you found a successfully failing reproduction.
