### ISSUE TITLE
[FormHelperText] FormHelperText should be aware of the disabled, focused and error state of the form input

### ISSUE THREAD

**Issue by shiranZe** [chakra-ui/chakra-ui#5293]
### Description

Hi!

Like form label and input, form control should pass the data attributes of disabled, focused, etc.

### Problem Statement/Justification

For example: I need to style the `FormHelperText` according to the input state, but it's not aware to the input's state.

`<FormControl isDisabled>
    <FormLabel htmlFor="email">Email address</FormLabel>
     <Input id="email" type="email" />
    <FormHelperText>This should get disabeld attribute as well.</FormHelperText>
</FormControl>;`

in form.ts (theme):

```
const baseStyleHelperText = () => ({
  mt: 1,
  color: 'grey.600',
  apply: 'textStyles.body3',
  _disabled: {
    color: 'grey.400'
  }
});
```

The disabled style won't work.

### Proposed Solution or API

Add the `data-disabled` attr to FormHelperText

**Comment by TimKolberger** [comment]
Hi @shiranZe 👋 
Thank your for this suggestion!

We created a new set of pseudo selectors e.g. `_peerDisabled`, `_peerFocus` which match your requirements.
It will be available **with the next release**. You can read more in the [Changeset](https://github.com/chakra-ui/chakra-ui/blob/main/.changeset/chilly-phones-flash.md).

```jsx
<>
  <input type="checkbox" data-peer />
  <Box bg="white" _peerFocus={{ bg: "green.400" }} />
</>
```
