### ISSUE TITLE
Color and Border Color theme overrides on Selected Tabs are ignored.

### ISSUE THREAD

**Issue by EdwinObviousPeople** [chakra-ui/chakra-ui#5295]
### Description

When I extend the theme on the Tabs, I can change all style properties except for the border color and text color.

### Link to Reproduction

https://codesandbox.io/s/festive-lichterman-ede2r?file=/src/index.tsx

### Steps to reproduce

Extend the theme like this:
```
extendTheme({components: {
  Tabs: {
    baseStyle: {
      tab: {
        color: "red.400",
        borderColor: "red.400",
        bg: "green.100",
        _selected: {
          color: "red.500",
          borderColor: "red.500",
          bg: "yellow.100",
        }
      }
    }
  }
}});
```

Toggle the selected Tabs.

Notice how selected Tabs don't get the Color and Background Color changes.

### Chakra UI Version

1.7.3

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by primos63** [comment]
Closing as this is not an issue with Chakra. Please refer to the [theme](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/tabs.ts) for `Tabs`. `Tabs` has variants the default being `line` which is what you are using.

Before opening an issue for something like this, you may want to post a request for help on Chakra's Discord channel `SOS-need-help` or in Github Discussions for the project.

```javascript
const theme = extendTheme({
  components: {
    Tabs: {
      variants: {
        'line': {
          tab: {
            color: "red.400",
            borderColor: "red.400",
            bg: "green.100",
            _selected: {
              borderColor: 'red.500',
              color: "red.500",
              bg: "yellow.100"
              }
          }
        }
      },
    }
  }
});
```

**Comment by ulises-castro** [comment]
If you try by changing baseStyle values for Tabs the custom values you assigned to it doe not work for _selected.

```jsx
components: {
  Tabs: {
    baseStyle: {
      tab: {
        _selected: {
          color: 'blue !important'
        },
        color: 'blackAlpha.700', 

        _hover: {
          color: 'rinseblue.500',
          borderBottom: 'rinseblue.500'
        }
      }
    },
    variants: {
      rinse: {
        tabs: {
          background: 'red'
        }
      }
    }
  }
}
}
```

And the end I use @primos63 solution.
