### ISSUE TITLE
Heading component makes font look messed up in FireFox

### ISSUE THREAD

**Issue by afd998** [chakra-ui/chakra-ui#5299]
### Description

When I look at my heading, i expect it to look good but it doesn't

### Link to Reproduction

I cant reproduce it with a sandbox because it only looks messed up in FF

### Steps to reproduce

run dev on a chakra project preferably using NEXTjs but maybe not necessary to see the bug.
make a heading component and type a fair amount of text so you can see
change the font the way the [docs tell you to option #1](https://chakra-ui.com/guides/recipes/using-fonts#option-1-install-with-npm). I've tried with Rozha One and Comfortaa both looked screwed up.
go to localhost in Firefox and look at it
It looks great in chrome and chrome mobile; looks bad on Firefox and Firefox mobile

### Chakra UI Version

1.7.2

### Browser

Firefox

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Here is bad Comfortaa
![Captureccc](https://user-images.githubusercontent.com/43195508/147615517-e6048064-a544-4edf-b8b4-c28c0eb2098d.PNG)

and bad Rozha One
![Capturecccc](https://user-images.githubusercontent.com/43195508/147615518-92bcc33a-ac63-417e-92bd-a19c54646b5f.PNG)

**Comment by segunadebayo** [comment]
Hi @afd998,

If the fonts look messed up. Feel free to tweak them based on your design, there's very little we can do to ensure the design for typography elements works for everyone.

Feel free to use the typography properties `fontSize`, `lineHeight`, `fontFamily` to customize the component.
