### ISSUE TITLE
The dark mode doesn't persist on page refresh.

### ISSUE THREAD

**Issue by prvnbist** [chakra-ui/chakra-ui#53]
The dark mode doesn't persist on page refresh.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17105682/64490523-4ca1e700-d27b-11e9-923c-f5717805e71a.gif)

**Comment by segunadebayo** [comment]
Hi @prvnbist ,

This is currently a bug I'm looking to fix that's why I forced it to behave this way. It's an issue with the internal library `use-dark-mode`.

Will look into it soon.

**Comment by segunadebayo** [comment]
This seems to be an issue with Next.js and the `use-dark-mode` hook. It seems to work fine in Create React App. See this app made with Chakra UI: https://smart-swatch.netlify.com/
