### ISSUE TITLE
Outline and solid variants of badges don't pass lighthouse audit

### ISSUE THREAD

**Issue by jaisharx** [chakra-ui/chakra-ui#5300]
### Description

Outline and solid variants of badges don't pass lighthouse audit

### Link to Reproduction

https://chakra-badges.vercel.app/

### Steps to reproduce

I love how good most of the components are out of the box in chakra-UI, and tbh that's why I pretty much use it in my every project. But the badge component doesn't pass lighthouse audit with the solid & outline variants.

**Below is the screenshot of the lighthouse audit ran locally**
<img width="820" alt="outline-badges" src="https://user-images.githubusercontent.com/55892116/147629884-ba5c187e-b180-4cc4-9bad-eb2d71e5b552.png">
<img width="825" alt="solid-badges" src="https://user-images.githubusercontent.com/55892116/147629888-0d9a3b6d-0e61-4070-85c6-596f6067ccee.png">

### Chakra UI Version

1.7.3

### Browser

Edge 96 (Chromium)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by noobyogi0010** [comment]
Hi, @sohamsshah 
I would like to work on this issue if no one has picked it up.
Thanks.

**Comment by sohamsshah** [comment]
Sure @noobyogi0010 , go ahead!

**Comment by noobyogi0010** [comment]
Alright, I will start working on it.
Thank you, @sohamsshah

**Comment by segunadebayo** [comment]
Hi @jaisharx,

Making changes to the colors of the badge at this time might be a breaking change to existing consumers who use visual regression tools.

Kindly make the changes in your app. In our next major version, we'll update all components to ensure they have sufficient contrast ratios.

Thanks for understanding.
