### ISSUE TITLE
Tooltip is being shown, when it shouldn't, when using with MenuButton and Modal

### ISSUE THREAD

**Issue by nilsdet** [chakra-ui/chakra-ui#5304]
### Description

When I use a Tooltip on a MenuButton, and a MenuItem of that Menu opens a Modal the Tooltip should not be shown after a click on that MenuItem.

### Link to Reproduction

https://codesandbox.io/s/tooltip-bug-pctvh?file=/src/App.js

### Steps to reproduce

1. Open the codesandbox
2. Click on the IconButton
3. Click on the MenuItem
4. Now you'll see that the Tooltip is shown even though it shouldn't.

### Chakra UI Version

1.7.2

### Browser

Google Chrome 96.0.4664.110

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information
I don't know if this is a bug or the expected behaviour.
If it's not a bug, I'd still like to know how to make sure the Tooltip is not shown, after a MenuItem is clicked.

### Current "workaround"
For now I seem to have some kind of "fix".
Setting the Tooltip's closeDelay hides the Tooltip properly.
By choosing a very small value (such as 5ms) it does not flicker.
But if that value is too small (such as 1ms or 2ms) it does not work.
I guess that's because the MenuButton's onFocus method is called after its onBlur method when clicking the MenuItem.
So for the workaround the closeDelay needs to be greater than the time between the onFocus and the onBlur call.
(You can see the console logs in the codesandbox.)

### Related issues
#2503

**Comment by kltdwrds** [comment]
I experienced this too - it's caused by a combination of 
1. chakra automatically re-focusing the trigger element when the triggered "popper.js" component closes (menu, modals, etc) and 
2. the [default behavior ](https://chakra-ui.com/docs/components/overlay/tooltip#tooltip-with-focusable-content)for tooltips wrapping focusable elements (ie trigger elements like buttons)


the easiest fix is by adding `onFocus={e => e.preventDefault()}` to the trigger element:
```
<Tooltip label='Search places'>
  <Button onFocus={e => e.preventDefault()}>Button</Button>
</Tooltip>
```

Ideally tooltip would have a flag to disable revealing it's label "on focus" of the trigger element.


https://chakra-ui.com/docs/components/overlay/tooltip#tooltip-with-focusable-content

**Comment by itkrt2y** [comment]
I don't know which commit is related, but this issue has been fixed in 2.1.0.
Maybe update of react-focus-lock? #6043

**Comment by jessicalc** [comment]
> I experienced this too - it's caused by a combination of
> 
> 1. chakra automatically re-focusing the trigger element when the triggered "popper.js" component closes (menu, modals, etc) and
> 2. the [default behavior ](https://chakra-ui.com/docs/components/overlay/tooltip#tooltip-with-focusable-content)for tooltips wrapping focusable elements (ie trigger elements like buttons)
> 
> the easiest fix is by adding `onFocus={e => e.preventDefault()}` to the trigger element:
> 
> ```
> <Tooltip label='Search places'>
>   <Button onFocus={e => e.preventDefault()}>Button</Button>
> </Tooltip>
> ```
> 
> Ideally `Tooltip` would have a flag to disable this behavior - something like `focusable=false`
> 
> https://chakra-ui.com/docs/components/overlay/tooltip#tooltip-with-focusable-content

Thank you! Much better than adding `onMouseEnter` and `onMouseLeave` listeners to the buttons to toggle the tooltip display...

**Comment by revengemiroz** [comment]
I was having this issue where when i open the modal a tooltip was shown without hovering. So i disabled the autoFocus behavior of the dialog
```
<DialogContent onOpenAutoFocus={(e) => e.preventDefault()}>
         <ShareModal />
</DialogContent>
```
