### ISSUE TITLE
[Toast]: Prevent toast duplication

### ISSUE THREAD

**Issue by tumdav** [chakra-ui/chakra-ui#531]
**Describe the solution you'd like**
Currently, it is impossible to prevent toast duplication.
For instance, if I show error message after incorrect login then a user again fills incorrect information and clicks a submit it again shows a toast with the same error message. So the user sees the same message twice.

**Describe alternatives you've considered**
You can check the react-toastify implementation [here](https://github.com/fkhadra/react-toastify#prevent-duplicate)

**Comment by GauravRajSharma** [comment]
Yes. If chakra exposed an hook for "Duplicate handling", "Programmatically updating toast that is already on the screen", "Newest on top mode", "Animation Controller", it would be really really awesome.

**Comment by segunadebayo** [comment]
Hey guys,

We've added support for this in the `v1` pre-release. Specifically these features:

- Duplicate handling
- Programmatically updating toast that is already on the screen

We'll publish an update shortly.

Thanks

**Comment by EllaSharakanski** [comment]
@segunadebayo Hi, where can I read the update? Thank you!

**Comment by ljosberinn** [comment]
Documentation for v1 is over [here](https://next.chakra-ui.com/docs/getting-started).
