### ISSUE TITLE
Entering `e` in a `number-input` clamps to min value

### ISSUE THREAD

**Issue by aeons** [chakra-ui/chakra-ui#5318]
### Description

When I enter the character `e` in a `number-input` field and deselect it, the value is clamped to the minimum numeric value.

### Link to Reproduction

https://chakra-ui.com/docs/form/number-input#usage

### Steps to reproduce

1. Go to https://chakra-ui.com/docs/form/number-input#usage
2. Enter `e` in the text field
3. Deselect text field
4. See the value in the text field

### Chakra UI Version

1.7.3

### Browser

Firefox 96

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The floating point regex used to validate input checks each character one at a time, so it allows an `e` without it being used in scientific notation.

**Comment by aeons** [comment]
The validity of the entered character is checked here: https://github.com/chakra-ui/chakra-ui/blob/bad1953306d693dc6bd1b559adf594cf02a3b8e5/packages/number-input/src/use-number-input.ts#L220

And the regex that could use some more context is defined here: https://github.com/chakra-ui/chakra-ui/blob/bad1953306d693dc6bd1b559adf594cf02a3b8e5/packages/number-input/src/utils.ts

**Comment by segunadebayo** [comment]
Hi @aeons,

Thanks for opening this and taking the time to get to the root cause. What did you expect to happen when the number input is blurred?

**Comment by aeons** [comment]
I would expect the `e` to not be allowed to be entered at all, unless there already were numbers in the field. The same way every other letter is handled.
