### ISSUE TITLE
Elements remain after closing a modal in React18

### ISSUE THREAD

**Issue by otofu-square** [chakra-ui/chakra-ui#5321]
### Description

When using the Modal component of `@chakra-ui/react` in an environment with React18 installed, the DOM element seems to remain after the modal is closed. This makes it impossible to click on other elements.
                                                                                            
### Link to Reproduction

https://codesandbox.io/s/chakra-ui-react18-reproduction-il8ux

### Steps to reproduce

1. Click `Open Modal` button
2. Click `Close` button
3. The `Open Modal` button cannot be pressed

### Chakra UI Version

1.7.4

### Browser

Google Chrome 96.0.4664.110(Official Build)(arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @otofu-square. Chakra UI doesn't support React 18 just yet therefore it's not a bug.

We might need a major release to support it due to possible breaking changes/behavior.

Thanks for understanding.

**Comment by jdmitrijev** [comment]
I've found the issue, when I removed <StrictMode/> which was there by default it started working.

**Comment by sitogi** [comment]
I've found the issue. However, I tried a simple configuration to create a new issue, but I could not reproduce.
I will turn off StrictMode for the time being.

> then the overlay stays. Not able to click on any button which is on stage

>  when I removed <StrictMode/> which was there by default it started working.

**Comment by jabza** [comment]
Modals with v2 & React 18 haven't been showing, removing <React.StrictMode/> fixed that

**Comment by abdougenesis** [comment]
i also have the same issue, i thought that chakra UI does support react 18 now.
