### ISSUE TITLE
Wish to control opacity when the button isLoading

### ISSUE THREAD

**Issue by TimonPeng** [chakra-ui/chakra-ui#5327]
### Description

For example, I want to be able to see the content of the button when loading, but here opacity is forced to `0`.

https://github.com/chakra-ui/chakra-ui/blob/main/packages/button/src/button.tsx#L151

### Problem Statement/Justification

Control more details.

### Proposed Solution or API

Allow more `variant` to be passed in?

**Comment by Patrick-Ullrich** [comment]
Would setting `loadingText` to your Button children be a workaround?

```
<Button isLoading loadingText="Hello :)">
        Hello :)
</Button>
```

https://codesandbox.io/s/great-cherry-qe731?file=/src/index.tsx

**Comment by TimonPeng** [comment]
Thanks for your help, I used this code and works:

```
sx={{ span: { opacity: 1 } }}
```
