### ISSUE TITLE
@chakra-ui/storybook-addon webpack problem

### ISSUE THREAD

**Issue by Todilo** [chakra-ui/chakra-ui#5328]
### Description

When I try to install the new storybook-addon I get webpack configuration errors

### Link to Reproduction

none

### Steps to reproduce

After a create-react-app with typescript/storybook setup then adding
npm i -D @chakra-ui/storybook-addon
also 
@chakra-ui/icons
npm start start-storybook -p 6006 -s public
I get errors:
info => Loading presets
info => Serving static files from ./public at /
info => Loading Webpack configuration from `node_modules\react-scripts`
info => Removing existing JavaScript and TypeScript rules.
info => Modifying Create React App rules.
info => Using default Webpack4 setup
ERR! WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
ERR!  - configuration.module.rules[5].oneOf[9].type should be one of these:
ERR!    "javascript/auto" | "javascript/dynamic" | "javascript/esm" | "json" | "webassembly/experimental"
ERR!    -> Module type to use for the module
ERR!     at webpack (C:\Projects\halloween-memory\node_modules\@storybook\builder-webpack4\node_modules\webpack\lib\webpack.js:31:9)
ERR!     at Object.start (C:\Projects\halloween-memory\node_modules\@storybook\builder-webpack4\dist\cjs\index.js:92:18)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (C:\Projects\halloween-memory\node_modules\@storybook\core-server\dist\cjs\dev-server.js:126:28)
ERR!     at async buildDevStandalone (C:\Projects\halloween-memory\node_modules\@storybook\core-server\dist\cjs\build-dev.js:115:31)
ERR!     at async buildDev (C:\Projects\halloween-memory\node_modules\@storybook\core-server\dist\cjs\build-dev.js:161:5)
ERR!  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
ERR!  - configuration.module.rules[5].oneOf[9].type should be one of these:
ERR!    "javascript/auto" | "javascript/dynamic" | "javascript/esm" | "json" | "webassembly/experimental"
ERR!    -> Module type to use for the module
ERR!     at webpack (C:\Projects\halloween-memory\node_modules\@storybook\builder-webpack4\node_modules\webpack\lib\webpack.js:31:9)
ERR!     at Object.start (C:\Projects\halloween-memory\node_modules\@storybook\builder-webpack4\dist\cjs\index.js:92:18)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (C:\Projects\halloween-memory\node_modules\@storybook\core-server\dist\cjs\dev-server.js:126:28)
ERR!     at async buildDevStandalone (C:\Projects\halloween-memory\node_modules\@storybook\core-server\dist\cjs\build-dev.js:115:31)
ERR!     at async buildDev (C:\Projects\halloween-memory\node_modules\@storybook\core-server\dist\cjs\build-dev.js:161:5)

### Chakra UI Version

1.7.4

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Node version:
v16.13.1

**Comment by Todilo** [comment]
After more experimentation this issue is resolved by using webpack5 using instructions found here:
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#webpack-5

**Comment by primos63** [comment]
Closing as there seems to be a solution to the issue.
