### ISSUE TITLE
`Select` component does not pass background colour to `option`  children

### ISSUE THREAD

**Issue by keithradford** [chakra-ui/chakra-ui#5331]
### Description

When using the Select component, I expect the given bg prop to pass it's property to it's children. Instead, the options have a white background which isn't readable when using white text.

### Link to Reproduction

https://chakra-ui.com/docs/form/select#overriding-the-styles-of-the-select

### Steps to reproduce

1. Go to [the Chakra UI docs for the Select component](https://chakra-ui.com/docs/form/select#overriding-the-styles-of-the-select)
2. Click on the example that says `Woohoo! A new background color!`
3. Move your cursor away so the option is not focused
4. See that the option is not legible

### Chakra UI Version

1.7.3

### Browser

Firefox 95.0.2 (64-bit)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Note: this likely a browser specific problem, I originally was developing with Linux and did not have this problem until I switched over to macOS (both using Firefox), and I can confirm Safari is legible.

**Comment by segunadebayo** [comment]
Hi @keithradford,

Yes, this is a browser problem and not a bug in Chakra UI. There's very little we can do about this from a cross-browser perspective.

Thanks for understanding.
