### ISSUE TITLE
No way to customize text colors for Button's colorSchemes

### ISSUE THREAD

**Issue by bymoe** [chakra-ui/chakra-ui#5345]
### Description

I want to globally custom text color based on Button's colorScheme

### Link to Reproduction

https://codesandbox.io/s/quizzical-lalande-sncs3?file=/src/index.js

### Steps to reproduce

1. Go to this [codesandbox](https://codesandbox.io/s/quizzical-lalande-sncs3?file=/src/index.js)
2. See how the default white color does not match with the `colorScheme`.

How can I add a different text color globally for the `pink` colorScheme!

### Chakra UI Version

1.7.4

### Browser

Google 96

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by primos63** [comment]
[This](https://codesandbox.io/s/custom-button-color-theme-xo6gq) is what I was referring to on Discord. You need to modify the theme for `Button`.

**Comment by bymoe** [comment]
> [This](https://codesandbox.io/s/custom-button-color-theme-xo6gq) is what I was referring to on Discord. You need to modify the theme for `Button`.

That solves it. Thank you so much!
