### ISSUE TITLE
<PopoverTrigger> throws error when passing a NextJS <NextLink> component as children

### ISSUE THREAD

**Issue by jamsmd** [chakra-ui/chakra-ui#5347]
### Description

When I use the PopoverTrigger To render a NextLink functionally it seems to work properly but when I open the console it shows an error

### Link to Reproduction

www

### Steps to reproduce

1. Create a NextJS app with the following template: https://github.com/vercel/next.js/tree/canary/examples/with-chakra-ui
2. Copy the Navbar `With Sub-Navigation & CTA` from: https://chakra-templates.dev/navigation/navbar
3. Inside the `<PopoverTrigger>` wrap the Chakra `<Link>` component inside a `<NextLink>` Component.  (As their docs says you should: https://chakra-ui.com/docs/navigation/link#usage-with-nextjs)
5. Open the console and you should see the following error

```
next-dev.js?3515:32 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `PopoverTrigger`.
```

### Chakra UI Version

@chakra-ui/react@^1.7.3

### Browser

Google Chrome Version 96.0.4664.110 (Official Build) (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@jamsmd  The Popovertrigger needs a ref to work and `NextLink` does not take refs.
A popover button should be a trigger, not a link, is there a usecase where you'll open a popover and navigate at the same time?

**Comment by jamsmd** [comment]
@anubra266 Thanks brother

**Comment by ThinkerDreamer** [comment]
@jamsmd I had the exact same error because I used the exact same NavBar template in the exact same way 😂 Thank you for posting here so I could solve my problem too! 

For anyone else reading this who still needs help, I fixed the issue by refactoring the NavBar. Instead of using the JSON format for the link hierarchy from https://chakra-templates.dev/navigation/navbar , I modified my NAV_ITEMS object and the props of the subcomponents to specify whether I wanted a PopoverTrigger (just a label) or a link with Next Link.

I don't think my way is necessarily the best way or the cleanest code, but I'll put it here in case it helps anyone else.

```javascript
 const NAV_ITEMS = {
    menu: {
      label: 'Dropdown Sublinks',
      children: [
        {
          label: 'Sublink 1',
          href: '/sublink1',
        },
        {
          label: 'Sublink 2',
          href: '/sublink2',
        },
      ],
    },
    link: {
      label: 'Contact us',
      href: '/contact',
    },
  };
``` 
```javascript
<DesktopNav
  label={NAV_ITEMS.menu.label}
  subItems={NAV_ITEMS.menu.children}
  link={NAV_ITEMS.link}
/>
```

```javascript
<MobileNav
  label={NAV_ITEMS.menu.label}
  subItems={NAV_ITEMS.menu.children}
  link={NAV_ITEMS.link}
/>
``` 

```javascript
const DesktopNav = ({ label, subItems, link }) => {
  return (
    <Stack direction={'row'}>
      <Box
        display={'flex'}
        alignItems={'center'}
      >
        <Popover trigger={'hover'} placement={'bottom-start'}>
          <PopoverTrigger>
            <Flex>
              <Text>{label}</Text>
            </Flex>
          </PopoverTrigger>
          <PopoverContent>
            <Stack>
              {subItems.map((subItem) => {
                return (
                  <DesktopSubNav key={subItem.label} {...subItem} />
                );
              })}
            </Stack>
          </PopoverContent>
        </Popover>
      </Box>
      <Flex>
        <NextLink href={link.href}>
          {link.label}
        </NextLink>
      </Flex>
    </Stack>
  );
};

const DesktopSubNav = ({ label, href }) => {
  return (
    <NextLink
      href={href}
    >
      <Stack direction={'row'} align={'center'}>
        <Text
          transition={'all .3s ease'}
        >
          {label}
        </Text>
      </Stack>
    </NextLink>
  );
};

const MobileNav = ({ label, subItems, link }) => {
  const { isOpen, onToggle } = useDisclosure();
  return (
    <div style={{ paddingBottom: '1rem', minHeight: '0' }}>
      <Stack>
        <Flex
          onClick={onToggle}
          justify={'space-between'}
          align={'center'}
        >
          <Text>
            {label}
          </Text>
        </Flex>
        <Collapse
          in={isOpen}
          animateOpacity
        >
          <Stack>
            {subItems.map((subItem) => (
              <NextLink
                key={subItem.label}
                href={subItem.href}
              >
                {subItem.label}
              </NextLink>
            ))}
            );
          </Stack>
        </Collapse>
        <NextLink href={link.href}>
          <Text>
            {link.label}
          </Text>
        </NextLink>
      </Stack>
    </div>
  );
};

```
