### ISSUE TITLE
Optimizing Grid virtualized DOMs

### ISSUE THREAD

**Issue by TimonPeng** [chakra-ui/chakra-ui#5348]
### Description

When I load a lot of image elements in SimpleGrid or Grid, scrolling will be flash screen (probably too much DOMs), is there any plan to support virtualized DOMs?

### Problem Statement/Justification

When I load a lot of image elements in SimpleGrid or Grid, scrolling will be flash screen (probably too much DOMs), is there any plan to support virtualized DOMs?

### Proposed Solution or API

Support virtual DOMs parameters for components?

**Comment by fredericoo** [comment]
Chakra works with react-virtualized, you just need to start using it.

**Comment by TimonPeng** [comment]
> Chakra works with react-virtualized, you just need to start using it.

but it need to know each child element's height, but it's hard thing when i using grid and if i have different length elements

**Comment by segunadebayo** [comment]
Hi @TimonPeng,

We don't support this out of the box. Feel free to use libraries like https://www.npmjs.com/package/react-virtual, https://www.npmjs.com/package/react-tiny-virtual-list, etc to solve it.

Cheers.

**Comment by alolis** [comment]
Is there an example by any chance?

**Comment by jakerobb** [comment]
+1 -- an example would be helpful!
