### ISSUE TITLE
Type of omitThemingProps is invalid and does not work if the component has a variant or size

### ISSUE THREAD

**Issue by Bassintag** [chakra-ui/chakra-ui#5350]
### Description

When using omitThemingProps in a custom components with props extending ThemingProps, typescript will not compile because props is not assignable to ThemingProps<string>

### Link to Reproduction

https://codesandbox.io/s/blue-currying-g4f1d?file=/src/index.tsx

### Steps to reproduce

1. Create a component with props extending ThemingProps<'Button'> (or any component name)
2. Try using omitThemingProps with the component props
3. There will be a Typescript error

### Chakra UI Version

1.7.4

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

This bug is caused by a change in the ThemingProps type, the type of variant and size used to be `string` when the ThemeComponent type parameter was string but it is now `never`.

This can be fixed by either reverting to `string` or by allowing omitThemingProps to take a type parameter that would be passed to ThemingProps hence not using the default `string` type parameter.

**Comment by TimKolberger** [comment]
Thank you for reporting this issue!
This was fixed by #5342.
Closing this as duplicate.
