### ISSUE TITLE
Different width depending on how props are passed

### ISSUE THREAD

**Issue by no-yan** [chakra-ui/chakra-ui#5363]
### Description

When passing a number to the width property, it behaves differently for `width={}` and `width=''`. 

### Link to Reproduction

https://codesandbox.io/s/laughing-dirac-57w68?file=/src/index.tsx

### Steps to reproduce

1. Go to [sandbox](https://codesandbox.io/s/laughing-dirac-57w68?file=/src/index.tsx)
2. Ensure all props are same.
3. Check different width between A and B.
4. See height.

### Chakra UI Version

1.7.4(latest)

### Browser

Google Chrome 96

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

For example, if you pass 11, it will behave as follows.

```
width={11} // output:11px 
width='11' // output: 11 
```

CSS does not handle unitless values and ignores them as a result.
Unlike width, height will attach `px` in both cases. Therefore, it seems that there is something to be fixed in the implementation of width.

**Comment by chenc041** [comment]
This is react behavior
Please check [react inline > style](https://reactjs.org/docs/dom-elements.html#style)

**Comment by no-yan** [comment]
Thank you for your response. However, that doesn't explain the difference in behavior between width and height.

**Comment by chenc041** [comment]
The difference in height and width is because the chakra has switched at the bottom,
If you want to know more, you need to read the source code

[styled-system/config/layout](https://github.com/chakra-ui/chakra-ui/blob/main/packages/styled-system/src/config/layout.ts#L38-L40)
[styled-system/utils/index](https://github.com/chakra-ui/chakra-ui/blob/main/packages/styled-system/src/utils/index.ts#L37-L38)

**Comment by anubra266** [comment]
@no-yan the default chakra sizes are in the theme file for [spacing](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/foundations/spacing.ts) and  [sizes](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/foundations/sizes.ts) and neither `33` nor `111` is there by default, so when you use something non existent in the them it's left to the browser to figure it out.
Update your codesandbox to use length specified in the them, if you still find an error, feel free to reopen this issue.

**Comment by no-yan** [comment]
これについてはすでに知っています。問題は、規定されていない値でもChakra UIが動くケースと動かないケースがあることです。
つまり、heightのようにvalidな値に修正する場合と、<w='11'/>のようにそうでない場合があることです。
<Box h={11}/> と<Box h='11'/>の挙動が異なることです。これは修正すべき問題だと思います。


あなたの説明が問題の根幹だと思うなら、なぜheightがfallbackとしてpxをつけられているのか説明できますか。
私の意見では、Chakra UIはこれらの値にheightのように'px'をつけるのか、それかwidthもheightも型エラーを出して値を受け付けないようにするか、一貫した挙動を提供する必要があります。
