### ISSUE TITLE
Page bottom blank space beyond </html> tag

### ISSUE THREAD

**Issue by prathameshpbhat** [chakra-ui/chakra-ui#5365]
### Description

All pages that are created have unwanted extra spacing at bottom of page

### Link to Reproduction

https://github.com/chakra-ui/chakra-ui#codesandbox-templates 

### Steps to reproduce

1.Create page with format
            ```
                  <Fragment>
                      <Stack>
                          <Box>
                          </Box>
                     </stack>
                 <Fragment>
            ```

### Chakra UI Version

1.6.3

### Browser

Version 97.0.4692.71 (Official Build) (arm64)

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

**### All pages that are created have unwanted extra spacing at bottom of page, Checked theme and other details and inspected the page, seems like the extra space is beyond </html> tag.**

### **Below is my general page Layout code**

              `import Head from 'next/head';
              import { LogoJsonLd, SocialProfileJsonLd } from 'next-seo';
              import { Box, ChakraProvider } from '@chakra-ui/react';
              import { PageNoticeProvider } from '../stores/page-notice';
              import globalStyles from '../styles/global';
              import WizTheme, { WIZ_SIZES } from '../theme';
              import WizHeader from './header';
              import type { ReactNode } from 'react';
              import type { NextPage } from 'next';
              import type { BoxProps } from '@chakra-ui/react/dist/types';
         
              export type WizPage<P, IP = Record<string, unknown>> = NextPage<P, IP> & {
                  /**
                   * Persistent outer layout.
                   */
                  getLayout: () => JSX.Element;
              };
              const SiteLayout = ({
                  children,
                  containerProps,
              }: {
                  children: ReactNode;
                  containerProps?: BoxProps;
              }): JSX.Element => {
                  return (
                      <PageNoticeProvider>
                          <ChakraProvider theme={WizTheme}>
                              <Head>
                                  <meta
                                      name='viewport'
                                      content='width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=0'
                                  />
                              </Head>
                              <style jsx global>
                                  {globalStyles}
                              </style>
                              <LogoJsonLd
                                  logo=''
                                  url=''
                              />
                              <SocialProfileJsonLd
                                  type='Organization'
                                  name='Wiz'
                                  url=''
                                  sameAs={['']}
                              />
                              <WizHeader />
                              <Box
                                  w='100%'
                                  p={WIZ_SIZES.containerBox.padding}
                                  {...containerProps}
                              >
                                  {children}
                              </Box>
                          </ChakraProvider>
                      </PageNoticeProvider>
                  );
              };  
              export const getLayout = (page?: JSX.Element): JSX.Element => (
                  <SiteLayout>{page}</SiteLayout>
              );
              export const getLayoutWithZeroPadding = (page?: JSX.Element): JSX.Element => (
                  <SiteLayout containerProps={{ p: 0 }}>{page}</SiteLayout>
              );  
              export const getLayoutWithFullHeight = (page?: JSX.Element): JSX.Element => (
                  <SiteLayout
                      containerProps={{
                          minH: `calc(100vh - ${WIZ_SIZES.homeNavbar.height})`,
                      }}
                  >
                      {page}
                  </SiteLayout>
              );
              
              export default SiteLayout;
              `

**### Below is my general page code for reference**
              ```
                    <Fragment>
                        <Stack>
                          <Box>
                          </Box>
                     </stack>
                   <Fragment>
              ```

### **Attaching Image below for better understanding of issue**

<img width="1440" alt="Screenshot 2022-01-10 at 7 50 22 PM" src="https://user-images.githubusercontent.com/32131455/148781187-8ae38c66-e54e-4e08-8621-0ecf2494ab55.png">

Please let me know, what is causing this issue.
Thank you.

(Note:There is no padding to the page)

**Comment by anubra266** [comment]
Please create a codesandbox reproduction of your issue.

**Comment by truongrayyone** [comment]
I have just solved the same issue in my project. Use this prop:  position='relative':
<Radio ... position='relative'>
