### ISSUE TITLE
[Chakra Storybook Addon] Color mode switch breaks visual testing tools 

### ISSUE THREAD

**Issue by guilleironhack** [chakra-ui/chakra-ui#5380]
### Description

When using visual testing tools that take screenshots of stories, the color mode switch appears in all of them, triggering a false positives.

### Link to Reproduction

N/A

### Chakra UI Version

@chakra-ui/storybook-addon@1.0.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Some example:
![image](https://user-images.githubusercontent.com/44772724/149331083-1ed0e996-f2d8-40a0-9006-ed8601658558.png)

Ideally, the color mode selector should at the toolbar, or at least would be great to have the option to disable the color mode switcher.

**Comment by ngxCoder** [comment]
If nobody else solves this, I will try to add an option to remove the color mode switcher this week.
I thought about this feature when I released it, but I am having some problems with my bills, haha
