### ISSUE TITLE
Custom toasts seem to be rendered twice

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#5395]
### Description

Custom toasts seem to be rendered twice.

### Link to Reproduction

https://codesandbox.io/s/cool-roman-yvt8x?file=/src/index.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/cool-roman-yvt8x?file=/src/index.tsx
2. Click on "Open Toast" multiple times. You should see this:

![image](https://user-images.githubusercontent.com/5437552/149642351-c9d737ff-3d2a-4243-aee2-b4e74f630dc8.png)

The counter increases two by two, instead of one by one. I have looked at Chakra-UI Toast source code but can't figure out why this is happening.

### Chakra UI Version

1.7.4

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by marek-sed** [comment]
I think you example is not using hooks properly.
You want to count each time component mounts probably so I rewrote it to use useEffect with useState. counterRef is still living outside of cycle. So I think it behaves as expected now.

https://codesandbox.io/s/sleepy-dhawan-czexf?file=/src/index.tsx

good article on rerenders, the fact the react function is run does not immediatly mean that the dom will be updated. https://kentcdodds.com/blog/fix-the-slow-render-before-you-fix-the-re-render

**Comment by lcswillems** [comment]
The code I made is only to prove there is a bug. Even if my code is not conventional (it is not the code I use in my codebase), it shows there is an issue. The counter should not increase two by two, but one by one.

**Comment by lcswillems** [comment]
Moreover, have a look at your example and it is obvious there is a bug. When I click multiple times on the toast button, the counter value is not the value that would be expected.

**Comment by marek-sed** [comment]
Well didnt wanted to be disrespectful it is not clear to me. What is clear to me that useMemo runs multiple times.
That doesnt mean that render happens. You are using useMemo to handle side effect of increasing counter. I would assume that first toast is alive and might get rerendered when you click again. 

If you look at the ToastManager.tsx, you can see that it keeps state of all the toasts on the screen and when you create new toasts(notify method) it renders the whole collection. And here is probably the issue that in this steps some of the useMemos gets called, and increases the counter multiple times, while with useEffect it works as expected.

Anyway I am not a maintainer, just love chakra and use it daily on our project.
I do not believe there is anything obvious here, to me it looks like incorrect usage of hooks for the reasons I stated.

So lets agree to disagree and will wait for someone competent to resolve this.
cheers :)

**Comment by lcswillems** [comment]
`useMemo(() => {...}, [])` should not run multiple times on rerenders. 

I have made a new demo of the bug with, this time, conventional code: https://codesandbox.io/s/dazzling-babycat-yf1wo?file=/src/index.tsx

When you click on the toast button, a toast is displayed in the bottom. But if you look at the console, it seems rather two toasts had been added to the dom because all the logs are doubled:

![image](https://user-images.githubusercontent.com/5437552/149735034-c3400aee-91cf-4e15-9969-a54c473c2d98.png)

**Comment by lcswillems** [comment]
So I have tracked down the bug and it seems to be comming from the `ReachAlert` component used by Chakra-UI. I have updated the Codesandbox: https://codesandbox.io/s/dazzling-babycat-yf1wo?file=/src/index.tsx

With this simple code:

```
import * as React from "react";
import { render } from "react-dom";
import ReachAlert from "@reach/alert";

const MyToast = () => {
  React.useEffect(() => {
    let counter = 0;

    const timeout = window.setInterval(() => {
      counter += 1;
      console.log(counter);
    }, 1000);

    return () => {
      window.clearInterval(timeout);
    };
  }, []);

  return <div style={{ background: "green" }}>Toast</div>;
};

render(
  <ReachAlert>
    <MyToast />
  </ReachAlert>,
  document.getElementById("root")
);
```

We see all console logs are doubled as if two components were displayed:

![image](https://user-images.githubusercontent.com/5437552/149738192-55398bc9-6435-4651-b2c5-bd06662f406c.png)

**Comment by marek-sed** [comment]
@lcswillems here is a workaround for you, https://codesandbox.io/s/festive-marco-nnn7c?file=/src/index.tsx

**Comment by lcswillems** [comment]
Thanks! Do you have any idea why one code works (one render) and the other one doesn't (two renders)?

**Comment by marek-sed** [comment]
Sry not really but would love to know. I think in ReachAlert there is useMirrorEffect which duplicates the child or somethin :), and I assume it is because of accesability since thats what reach-ui is about. It runs as an effect when child changes, so by making a child stable it might be fixed. Anyway I am guessing.

have a good one, glad I could somewhat help :)

**Comment by lcswillems** [comment]
Okay! Thansk for all this information! Have a good day too!

**Comment by lcswillems** [comment]
I don't think this issue is solved

**Comment by lcswillems** [comment]
Don't close

**Comment by bursteways** [comment]
This is still happening

**Comment by lcswillems** [comment]
Are you using Chakra-UI 2 ?

**Comment by dmahajan980** [comment]
I am using Chakra UI (v2.2.8) and I am facing the same issue.

**Comment by lcswillems** [comment]
In the codesandbox I posted in the issue, it seems to work now: https://codesandbox.io/s/cool-roman-yvt8x?file=/src/index.tsx

**Comment by mjviana** [comment]
Hi!
 
Just in case someone faces this is the future. I was facing this issue.
The thing is: isn't this due to React.StrictMode?

Just for the sake of testing I disabled it and now I only get one custom toast message.
I will save you a google search :) here is how you disable it: [https://stackoverflow.com/questions/74952506/how-to-disable-strict-mode-in-react-18](url)

So I think it's fine. Once you go to production environment and since in this environment, React.StrictMode is disabled by default, this should work as expected.

**Comment by kaf-lamed-beyt** [comment]
@mjviana, clicking on the link you provided... redirects to this: https://github.com/chakra-ui/chakra-ui/issues/url

For anyone who'd run into this, and wants to remove Strict Mode. Here's the [link](https://stackoverflow.com/questions/74952506/how-to-disable-strict-mode-in-react-18) or you can just copy the blue text

**Comment by mjviana** [comment]
Ups, 😭 my bad!
The link it's fixed. 
Thanks and happy coding! 🥳

**Comment by kaf-lamed-beyt** [comment]
Happy coding! 

Cheers 🍷
