### ISSUE TITLE
Popover content position styles are only rendered after 1st click on popover trigger

### ISSUE THREAD

**Issue by cbdeveloper** [chakra-ui/chakra-ui#5398]
### Description

When I render a popover content placed at the bottom I was expecting the position props to be rendered but they are only rendered after the first click on the popover.

### Link to Reproduction

https://codesandbox.io/s/practical-hooks-t6jiv?file=/src/App.tsx

### Steps to reproduce

1. Render this:

```
<Popover arrowPadding={30} offset={[15, 15]} placement="bottom">
    <PopoverTrigger>
      <Box w="40px" h="40px">
        <svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
          <circle cx="50" cy="50" r="50" />
        </svg>
      </Box>
    </PopoverTrigger>
    <PopoverContent borderRadius={12} border="none" p={2}>
      <PopoverArrow />

      <PopoverHeader fontSize="24" borderBottom="none">
        heading
      </PopoverHeader>

      <PopoverBody>Body</PopoverBody>
    </PopoverContent>
  </Popover>
```

2. Inspect elements (see where the popover is being rendered before and after the 1st click).
3. See Additional Information

Obs: I tried to make a working example on CodeSandbox, but there was some error with the `'@emotion/memoize'` package that wasn't compiling.

### Chakra UI Version

"@chakra-ui/react": "^1.7.1",

### Browser

Same behavior on Chrome and Firefox (only ones I've tested)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Before clicking on the popover for the 1st time:

![image](https://user-images.githubusercontent.com/43407798/149799847-217e348d-ae94-4d58-9964-85affcce6478.png)

![image](https://user-images.githubusercontent.com/43407798/149804479-e88416b0-f647-4f1e-ade4-b210deb9f50b.png)

After 1st click (and subsequent clicks, opening and closing it).

![image](https://user-images.githubusercontent.com/43407798/149799911-00ba7bfd-0de8-48ff-b108-5b6e57670e4e.png)

![image](https://user-images.githubusercontent.com/43407798/149804573-c06a7903-f6b2-4521-85ee-14ac94d90f43.png)

This is the popover that is being rendered:

![image](https://user-images.githubusercontent.com/43407798/149804650-4335e39e-e716-4bc6-849c-3057ef8907e0.png)

I was expecting the position styles to be rendered right from the 1st render, regardless of it being clicked or not.

**Comment by yotam707** [comment]
This is also an issue for us

**Comment by Abdul-Ismail** [comment]
@cbdeveloper @yotam707  did you end up solving this?

**Comment by cbdeveloper** [comment]
@Abdul-Ismail unfortunately, no. This is still a bug for us. Haven't had the time to try and solve it yet.

**Comment by NeoDrew** [comment]
We've found a work around to this if you apply the correct css translate to the  `.chakra-popover__popper` which can be found by inspecting webpage. 

This worked for us:
``.chakra-popover__popper { 
    transform: translate3d(-97.2727px, 48.1818px, 0px); 
}``
