### ISSUE TITLE
Consider joining WICG's Open UI initiative

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#54]
[WICG](https://wicg.io/) has started a project called [Open UI](https://open-ui.org/), which aims to standardize UI components for the web. I think that Chakra UI fits the purpose well and should consider [contributing](https://open-ui.org/contribute/design-system) design system details towards the initiative.

**Comment by segunadebayo** [comment]
Looked at Open UI and it looks interesting. I'll see how Chakra can contribute to it, we definitely need a standardized resource for common UI components.

Thanks @kripod
