### ISSUE TITLE
Nested Popover content rendered in a Portal closes everything

### ISSUE THREAD

**Issue by baptisteArno** [chakra-ui/chakra-ui#5401]
### Description

When I implement a Popover inside another Popover and render the inside PopoverContent in a Portal, when clicking on the trigger, it closes everything.

### Link to Reproduction

https://codesandbox.io/s/nested-popover-with-portal-closes-everything-n7t6w

### Steps to reproduce

1. Click on "Open first popover"
2. Click on "Open second popover"
3. See issue

### Chakra UI Version

1.7.4

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by primos63** [comment]
Closing as this is not an issue with Chakra. 
Popover's `closeOnBlur` defaults to true therefore the first popover closes once the button to open the second is pressed and focus is transferred. Please refer to the documentation for [Popover](https://chakra-ui.com/docs/overlay/popover) and specifically the section on [Accessing Internal State](https://chakra-ui.com/docs/overlay/popover#accessing-internal-state).
