### ISSUE TITLE
Cannot select custom theme token with useToken

### ISSUE THREAD

**Issue by mihai-ro** [chakra-ui/chakra-ui#5407]
### Description

When attempting to extract a custom theme token with useToken, the hook returns invalid results

### Link to Reproduction

https://codesandbox.io/s/homepage-forked-9un9r?file=/src/index.tsx:196-203

### Steps to reproduce

1. Go to '[my sandbox](https://codesandbox.io/s/homepage-forked-9un9r?file=/src/index.tsx:196-203)'
2. Look at index.tsx to see the theme
3. Look at App.tsx to see the implementation
4. Check the output to understand the results

### Chakra UI Version

1.7.5

### Browser

All

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by primos63** [comment]
`useToken` is operating as it should be.

The docs, however, do not accurately reflect the function: 
> The useToken hook retrieves whatever is in the theme at the given path(s).

The function **does not** return **whatever** is put into the theme. It returns values for tokens which are entries that are turned into CSS variables. As your theme stands, `myToken` would not get converted to a CSS variable and therefore is not in the `__cssMap`. `Components` are in the theme, but they cannot be retrieved with `useToken`.

Your theme should be something like:
```jsx
const updatedTheme = extendTheme({
  colors: {
     acmeBrand: {
       background: "#D53F8C",
       primary: "#FFFFFF"
     }
  },
  borders: {
    acmeDashed: "1px dashed"
  }
});
```
Then in App.tsx, you'd be able to use the function like this
```javascript
  const acmeBackground = useToken("colors", "acmeBrand.background");
  const acmeDashed = useToken("borders", "acmeDashed")
```
giving you the returned value or fallback value if the token is not found
```javascript
console.log('background:', acmeBackground)
console.log('border:', acmeDashed)
```
Your `singleToken` is also working correctly, but I think you may misunderstand the use of fallback.
I modified the [CodeSandbox](https://codesandbox.io/s/usetoken-gh-issue-5407-2400q) application you provided to show what should be done.

I will close this issue as there isn't an issue with the Chakra code. I'll open an issue in the docs repo to request a better explanation of `useToken`.

**Comment by primos63** [comment]
**Note**:  I misread the docs and quoted the return value as its definition. 
> useToken is a custom hook used to resolve design tokens from the theme.

Design tokens are defined in `packages/styled-system/src/create-theme-vars/theme-tokens.ts` as
```javascript
const tokens = [
  "colors",
  "borders",
  "borderWidths",
  "borderStyles",
  "fonts",
  "fontSizes",
  "fontWeights",
  "letterSpacings",
  "lineHeights",
  "radii",
  "space",
  "shadows",
  "sizes",
  "zIndices",
  "transition",
  "blur",
] as const
```
`useToken` expects one of these tokens to be passed to it.

The docs are correct and there is no need to file an issue against them. Sorry for any confusion that may have caused.

**Comment by mihai-ro** [comment]
Thank you, @primos63. The sandbox you referenced seems to not exist, but that's fine, I believe I understand now what you mean.
This is, probably, also a breaking change in the hook's usage, as the implementation changed and the scope narrowed down to what you explained. I am currently running`@chakra-ui/react@1.6.10` in my project, and have been using the `useToken` hook just as I described in my initial post - as a convenient way to select specific values from the theme, instead of grabbing the entire theme with `useTheme`. This behaviour changed in the following version, but I missed this being documented anywhere.
Nonetheless, thank you for clarifying this.

**Comment by primos63** [comment]
Well I need to apologize again. My sandboxes start as private. I forgot to make it visible for others. You should be able to access it now @mihai-ro .
