### ISSUE TITLE
`omitThemingProps` shows type errors with template generated with `chakra-cli`

### ISSUE THREAD

**Issue by hpohlmeyer** [chakra-ui/chakra-ui#5409]
### Description

When using `omitThemingProps` from `@chakra-ui/react` with a custom component, it shows a type error.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-vgxthw?devtoolsheight=33&file=src/components/MyComponent.tsx

### Steps to reproduce

1. Go to [the reproduction](https://stackblitz.com/edit/vitejs-vite-vgxthw?devtoolsheight=33&file=src/components/MyComponent.tsx)
2. Run `npm run typecheck` from the terminal
3. See the errors

### Chakra UI Version

1.7.4

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by primos63** [comment]
There was in issue with theme typings in 1.7.4. If you move to 1.7.5 and run the npm command, the error no longer exists.
Closing as the issue was fixed in version 1.7.5.

**Comment by hpohlmeyer** [comment]
Thanks @primos63! Is there any plan when 1.7.5 will be released? Currently 1.7.4 is still the latest version on npm.

**Comment by primos63** [comment]
I'll have to ask about that. CodeSandbox shows 1.7.5 as latest. The docs show the same and I know I installed the package locally.

**Comment by hpohlmeyer** [comment]
Oh, you are right, 1.7.5 exists on npm and fixes the issue. But it looks like it never got the `latest` tag. That’s also why CodeSandbox does show it in their list but uses 1.7.4 by default.
