### ISSUE TITLE
Editable without value isn't clickable

### ISSUE THREAD

**Issue by rhadamez** [chakra-ui/chakra-ui#5423]
### Description

In a "editable" input, when it is empty, is not possible to click on it again, cause the width of the editable seems to be zero.

### Link to Reproduction

https://chakra-ui.com/docs/form/editable

### Steps to reproduce

1. Go to 'https://chakra-ui.com/docs/form/editable'
2. Click on 'editable'
3. Clean the 'editable'
4. Lost the focus
4. Try to click on 'editable' again

### Chakra UI Version

1.7.5

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by rhadamez** [comment]
I think maybe a "width: 2px" when the value.length === 0 could fix it.

**Comment by noobinthisgame** [comment]
I can confirm that putting a minWidth on the `EditablePreview` solves this and works as a workaround. Using a placeholder also helps against this behaviour.

**Comment by matmont** [comment]
Hey guys, I would like to work on that.

**Comment by burhanuday** [comment]
@rhadamez a solution is to set width to full on the preview component
```jsx
  <EditablePreview width="full" />
```

@noobinthisgame should we set the `minWidth` of `EditablePreview` to "2px" by default? Currently it becomes impossible to go into edit mode once it becomes empty. Would like to take this issue up

**Comment by noobinthisgame** [comment]
@burhanuday feel free to submit a PR for this :) If setting it to fixed 2px by default, make sure that it's overriden properly when custom styles are applied so that there is no secondary effects :)

**Comment by segunadebayo** [comment]
> I can confirm that putting a minWidth on the `EditablePreview` solves this and works as a workaround. Using a placeholder also helps against this behaviour.

Thanks for chiming in here @noobinthisgame. This is the recommended solution for this issue
