### ISSUE TITLE
Color name token with symbols

### ISSUE THREAD

**Issue by deshiknaves** [chakra-ui/chakra-ui#5424]
### Description

Color names with $ no longer work (`$red`)

### Link to Reproduction

https://codesandbox.io/s/confident-kalam-27b3m

### Steps to reproduce

Some where between `1.2.1` and `latest` color names can no longer start a symbol. Anyone know what change might have caused it and why? I'm happy to work on a fix.

### Chakra UI Version

latest

### Browser

Firefox, Chrome, Safari

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by deshiknaves** [comment]
Bump

**Comment by TimKolberger** [comment]
I think this bug was introduced when we started using CSS variables. 

The CSS variable names should be escaped. This is happening in the package styled-system.
