### ISSUE TITLE
color label can represent diffrent color by color mode

### ISSUE THREAD

**Issue by rainke** [chakra-ui/chakra-ui#5429]
### Description

I want a special theme config make `color label` will display special color in diffrent color mode;

```jsx
<Box color="color.label">color</Box>
```

### Problem Statement/Justification

In some design systems, many colors have some differences in light and dark modes

### Proposed Solution or API

```js
{
  colorTheme: {
    light: {
      primary: "#31f",
    },
    dark: {
      primary: "#33a",
    },
  },
}
```

or

```js
{
    primary: ["#31f", "#33a"],
  }
```

then we can use it in `Box` component

```jsx
<Box color="primary">primary</Box>
```

It's color is `#31f` in `light` mode, `#33a` in `dark' mode

**Comment by primos63** [comment]
It's not the way Chakra colors and color mode works. There are ways to change the color based on mode. 

This is the global style used in the default theme. You can add your own global in your theme and can modify the component theme 
```jsx
const styles: Styles = {
  global: (props) => ({
    body: {
      fontFamily: "body",
      color: mode("gray.800", "whiteAlpha.900")(props),
      bg: mode("white", "gray.800")(props),
      transition: "background-color 0.2s",
      lineHeight: "base",
    },
    "*::placeholder": {
      color: mode("gray.400", "whiteAlpha.400")(props),
    },
    "*, *::before, &::after": {
      borderColor: mode("gray.200", "whiteAlpha.300")(props),
      wordWrap: "break-word",
    },
  }),
}
```
Closing this as I do not see this type of change being applied to the product.
