### ISSUE TITLE
[Stack] add Divider between children

### ISSUE THREAD

**Issue by luizcieslak** [chakra-ui/chakra-ui#543]
**Is your feature request related to a problem? Please describe.**

No, not a problem. I think that would be a nice feature of Stack component to have an option to add Dividers between components.

**Describe the solution you'd like**

A boolean prop called `divider` to `Stack`:

`<Stack divider {...props}> {children} </Stack>`

**Describe alternatives you've considered**

Currently, to have this, I manually input the `<Divider />` between children components:

```js
<Stack>
  <Component1 />
  <Divider />
  <Component2 />
  <Divider />
  <Component3 />
  <Divider />
</Stack>
```

**Additional context**

I'd love to contribute on this! However, there is some questions I'd like to discuss before:

* Is this a valid feature? If not, is it possible to add an example or paragraph in [Stack docs page](https://chakra-ui.com/stack)?

* if the prop `divider` is `true`, should the spacing number be divided by 2? If so, how to deal with odd numbers? I mean, if the user create this component: `<Stack spacing={8} />`, it surely expects an `8` space between the components:

```
component1 spacing8 component2
```

Thus the divider should be in the middle of the components:

```
component1 spacing4 divider spacing4 component2
```

* Should the divider border color be editable? for example:

`<Stack divider dividerColor="red.100" />`

**Comment by segunadebayo** [comment]
Hi @luizcieslak, thanks for bringing this up.

It's definitely a good idea and we've done some work on it already. It'll land in the next release.

Here's a migration file we've prepared to you can get an idea:
https://github.com/chakra-ui/chakra-ui/blob/dev-ts/packages/layout/migration.md
