### ISSUE TITLE
Storybook Addon does not run with ViteJS/Esbuild

### ISSUE THREAD

**Issue by marjan-pluto** [chakra-ui/chakra-ui#5431]
### Description

When trying to build Storybook with Chakra UI addon in ViteJS, I get uncaught error for `require` in `chakra-ui-storybook-addon-preset-decorators.cjs.js` file.

### Steps to reproduce

1.  Set up storybook builder in vite
```
npx sb@next init --builder storybook-builder-vite
```
2. Install the official Storybook Addon for Chakra UI as mentioned in the doc
```
yarn add -D @chakra-ui/storybook-addon
```
3. Start Storybook
4. See error in browser console
![image](https://user-images.githubusercontent.com/97608659/150551457-9a6151f5-b23d-41e0-ba36-f721ba866679.png)
![image](https://user-images.githubusercontent.com/97608659/150551617-bcd2104c-68bf-4fb0-8045-f95cc2215ff1.png)

### Chakra UI Version

1.7.4

### Operating System

- [ ] macOS
- [x] Windows
- [ ] Linux

### Additional Information

Exposing esm file should fix the issue.

**Comment by enjinerd** [comment]
@marjan-pluto i face the issue too, then i removed the addon, and it's worked, maybe its bug with the addon?
![2-1-2022_goxWp71B98](https://user-images.githubusercontent.com/35429278/150931161-892480eb-5af9-4f15-9c5d-f02a8a98be84.png)

**Comment by ashfaqnisar** [comment]
Umm,  where you able to solve this @marjan-pluto ?
