### ISSUE TITLE
[Button] Support for multi-lines Button, or recommended workaround

### ISSUE THREAD

**Issue by verekia** [chakra-ui/chakra-ui#5435]
### Description

If Button contents are longer than their container or screen constraint, the content breaks out of the button instead of wrapping to a new line

### Link to Reproduction

https://chakra-ui.com/docs/form/button

### Steps to reproduce

1. Make a Button with long text content
2. Resize the window if necessary to make it break

### Chakra UI Version

1.7.5

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

In the docs:

<img width="319" alt="Screenshot 2022-01-22 at 16 11 50" src="https://user-images.githubusercontent.com/522007/150632469-aed6c517-0c12-4e39-a8b9-69dc44a54ed0.png">

Adding `white-space: initial` (or `unset` and such), is not too bad on 2 lines, but since the height is locked, the padding is off :

<img width="324" alt="Screenshot 2022-01-22 at 16 12 58" src="https://user-images.githubusercontent.com/522007/150632724-f053fe60-3e0a-4fcc-b2aa-24884ac0f52d.png">

On 3 lines it completely breaks though:

<img width="232" alt="Screenshot 2022-01-22 at 16 13 09" src="https://user-images.githubusercontent.com/522007/150632734-b9ae244e-8f9c-45f4-891a-8f549c994b0c.png">

Is there any better workaround than changing `white-space` that would preserve the expected padding around the text?

**Comment by segunadebayo** [comment]
Hi @verekia,

That's exactly the workaround you need 👌.

**Comment by testerez** [comment]
Would it be a better solution to trade `height` for `min-height` and remove `nowrap` in the default theme? I believe the behaviour in case of long a text would be preferable since it would break on as many lines as required, preserve padding and avoid overflows.
