### ISSUE TITLE
Request for Svelte Support

### ISSUE THREAD

**Issue by SuPythony** [chakra-ui/chakra-ui#5437]
### Description

Feature request for extending Chakra-UI to Svelte.

### Problem Statement/Justification

Chakra-UI has become one of the top UI libraries for React. Svelte is also gaining attention steadily. I believe that chakra-ui should extend to Svelte and that would be a great help for svelte developers!

I have seen into the previous issue (#819) requesting the same and it was closed as at that time typescript support was being added. Now that it's done, I think that extending to svelte will be possible.

### Proposed Solution or API

The same components and functionality as the React version.

**Comment by segunadebayo** [comment]
Hi @SuPythony,

I can totally relate to this and I'd love for Chakra UI to have a Svelte version. We don't consider this a priority for us and can't dedicate resources to it.

If you can, feel free to take this on and share progress with the community on Discord.

We'd love to see this as well.

Thanks for understanding.

**Comment by elcharitas** [comment]
I published a post about the implementation of Chakra UI in svelte. Do check it out here https://blog.elcharitas.dev/announcing-chakra-ui-svelte

**Comment by SuPythony** [comment]
Looks good! I hope it expands and becomes an official implementation.

**Comment by JTBrinkmann** [comment]
Note: This is a duplicate of #819
