### ISSUE TITLE
useNumberInput firing multiples onChange events.

### ISSUE THREAD

**Issue by luigiminardim** [chakra-ui/chakra-ui#5441]
### Description

When I click a button that uses the useNumberInput, I expect the onChange event to be fired just once, but the input is firing the onChange event infinitely.

### Link to Reproduction

https://codesandbox.io/s/trusting-banzai-o6njl?file=/src/index.js

### Steps to reproduce

1. Click to increment the input 2 times.
2. Check that the number of onChange events doesn't stop growing.

> NOTE: this behavior happens on the upper bound and the lowest bound (min = 0 and max = 2).

### Chakra UI Version

1.7.4

### Browser

Google Chrome Version 97.0.4692.71 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

In this picture, we see the onChange event being fired non-stop:
![Screenshot from 2022-01-24 17-45-03](https://user-images.githubusercontent.com/37146539/150862043-7c785279-1532-480c-ad65-42d1b5e2dd99.png)

I also notice that when I reach the upper bound or the lowest bound of the value in the increment input, I have to click 2 times to change the value. E.g. When I get the value 2, I have to click to times in the decrement button to get a lower value.

**Comment by noobyogi0010** [comment]
Hi, @luigiminardim 
I would like to work on this issue if no one has already taken it up.

**Comment by luigiminardim** [comment]
> Hi, @luigiminardim 
> I would like to work on this issue if no one has already taken it up.

@noobyogi0010, it would be awesome! I haven't started working on this.

**Comment by noobyogi0010** [comment]
Okay, then I will pick it up and start working on it.
Thank you @luigiminardim

**Comment by FoxMandrake** [comment]
Was this ever fixed?

**Comment by PatrickInFrontEnd** [comment]
Nope... still not fixed in 2023... shame
