### ISSUE TITLE
[nextjs] ColorModeScript "Uncaught ReferenceError: root is not defined"

### ISSUE THREAD

**Issue by Haschikeks** [chakra-ui/chakra-ui#5453]
### Description

When adding the ColorModeScript in a nextjs app and starting the server, the ColorModeScript can't access the "root" object which would give access to `document.documentElement`.

### Link to Reproduction

https://codesandbox.io/s/epic-glade-cnxbx?file=/package.json

### Steps to reproduce

1. Open the sandbox
2. Start the server
3. Check the console logs

### Chakra UI Version

1.8.0

### Browser

Chrome 93

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This Problem only occurred  with version 1.8.0
Probably with this commit https://github.com/chakra-ui/chakra-ui/commit/1c02c15ea4c373c06f377f1df13d85e745ba8ea9

I'm not sure if a simple revert + adding the corresponding deprecated message would be the best solution.

**Comment by Distortedlogic** [comment]
bump

**Comment by gavinhenderson** [comment]
Also experiencing this issue

**Comment by JClackett** [comment]
Yep, can confirm this is a bug in chakra. Seems to be a bug in the color mode script

<img width="616" alt="Screenshot 2022-01-26 at 15 48 22" src="https://user-images.githubusercontent.com/12549124/151196991-90ec7823-a94a-4bbf-9d16-08448ec5c7e5.png">
