### ISSUE TITLE
Custom Accordion icon

### ISSUE THREAD

**Issue by vf1** [chakra-ui/chakra-ui#5455]
### Description

It would useful to have ability to change accordion icon svg.

### Problem Statement/Justification

It would useful to have ability to change accordion icon svg.

### Proposed Solution or API

It can be achieved by accepting _children_ in AccordionIcon props, and then icon should render _children_ or default svg.

![image](https://user-images.githubusercontent.com/1785355/151173599-e84024d0-be56-4808-8815-58550184b075.png)

**Comment by noobinthisgame** [comment]
Hey @vf1, [this example](https://chakra-ui.com/docs/disclosure/accordion#accessing-the-internal-state) shows how you can change the displayed Icon. Maybe this works for your use case ?

**Comment by vf1** [comment]
Hi @noobinthisgame, yes, it works, and I use isExpanded for using/changing custom icon. The custom icon is:
![image](https://user-images.githubusercontent.com/1785355/151221082-1e37f684-19d8-463a-9194-7e8b79839c38.png)
and I would like to keep chakra animation for it. Maybe you right, and it is mine specific task. It seemed to me that this is the simplest solution, but maybe I should just add animation to mine icon)
