### ISSUE TITLE
Some components use z-index which produces unwanted behaviors

### ISSUE THREAD

**Issue by Ploppy3** [chakra-ui/chakra-ui#5456]
### Description

Some components (RangeSliderThumb, InputLeftElement, InputRightElement) use z-index which causes unwanted behaviors

### Link to Reproduction

https://codesandbox.io/s/nervous-easley-9uq07?file=/src/index.js

### Steps to reproduce

Put content on top of slider thumbs.

### Chakra UI Version

1.7.5

### Browser

Google Chrome 97

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Somehow I have a similar problem with the RangeSliderTrack but I can't reproduce it.

**Comment by Webbanditten** [comment]
We solved this by overwriting the z-index in our theme config. Hope this will be fixed centrally.

**Comment by Ploppy3** [comment]
@Webbanditten could you please price the code you wrote that fixes the problem?

**Comment by Ploppy3** [comment]
its not

**Comment by Ploppy3** [comment]
not stale

**Comment by segunadebayo** [comment]
Please tweak the z-index in your userland code, or add `isolation` property where needed

**Comment by Ploppy3** [comment]
@segunadebayo You surely know that z-index is an issue in css. I recommend using z-index only when necessary and I don't think it is here. I might be wrong though.
