### ISSUE TITLE
Menu is not closing when we click outside the MenuList

### ISSUE THREAD

**Issue by porwal-ayush** [chakra-ui/chakra-ui#5458]
### Description

When the MenuList is in the open state, and I want to close it, I click outside of the MenuList, it doesn’t close. However, if I click on the horizontal area, it closes. The expected behaviour is that if the user clicks anywhere outside the Menu, the MenuList should close.

This issue is similar to #3994 but that issue does not speak for horizontal click successfully closing the Menulist.

### Link to Reproduction

https://codesandbox.io/s/nostalgic-snowflake-93y20?file=/src/App.js

### Steps to reproduce

1. Go to the code sandbox link
2. Click on the hamburger icon
3. Click outside the MenuList (say like the bottom of the screen)
4. Click outside the MenuList (anywhere in the horizontal red area)

### Chakra UI Version

1.7.4

### Browser

Google Chrome 97

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @porwal-ayush,

Looking at the repro, this is happening because the page isn't tall enough to be considered an outside click.

If you increase the height of the page, say by adding `min-height: 100vh;` it'll work as expected.
