### ISSUE TITLE
[Modal] Request to add option to disable focus trap

### ISSUE THREAD

**Issue by SDrinkwater** [chakra-ui/chakra-ui#546]
**Is your feature request related to a problem? Please describe.**
I am attempting to open a drawer on the right while maintaining an interactable menu down the left. I can position the left menu so that links can be clicked by manually selecting the html elements of the drawer and manipulating their width, but this still leaves my left menu search bar as unfocusable. This "solution" is less than ideal as I don't want to cripple my UX to support this particular drawer, and it's pretty messy selecting and modifying elements manually.

**Describe the solution you'd like**
Two things would be extremely useful, both providing the drawer with more flexibility. 

1. Add an option to disable the focus trap `disableFocusTrap?: boolean`.

1. Add an option to control the height/width of the area occupied by the modal/overlay/etc. This would allow for situations where parts of the UI could still be interacted with without closing the drawer.

**Describe alternatives you've considered**
There is no real way around the focus trap as it currently stands. When the drawer is open, nothing can be done to escape it (that I'm aware of).
The interactable area problem can be partially solved by manually manipulating the elements once they're rendered, but this is pretty ugly and definitely shouldn't be encouraged.

**Additional context**
This is a simplified example, but it contains the basics. The righthand drawer is opened when someone is selected from the panel on the left. I need the panel on the left to still be interactable so that another user can be selected without first closing the drawer
![Screen Shot 2020-03-31 at 9 00 48 AM](https://user-images.githubusercontent.com/13460254/77966381-a1e43980-732e-11ea-98b0-1ce19644adfb.png)

**Comment by segunadebayo** [comment]
This has been resolved in preparation for the next release.

Thanks for bringing it up.

**Comment by aquibbaig** [comment]
@segunadebayo Sorry but I am looking for this feature, has this been implemented yet?

**Comment by afialydia** [comment]
Also curious about this update, thx in advance!

**Comment by joangavelan** [comment]
To everyone looking for this feature, it is now available as `trapFocus?` prop.

However, it is not advisable to disable this option for accessibility reasons as stated in the [docs](https://chakra-ui.com/docs/components/modal/props).
 
In my case, I had a different problem. I'm displaying a welcome modal component as soon as the user visits a particular page and the first tabbable element in the modal (a button) is rendering in a focused state. To prevent this I passed a ref to the `initialFocusRef` modal prop referencing the `<ModalContent />` component.
```
const initialRef = React.useRef(null)

<Modal initialFocusRef={initialRef}>
  <ModalContent ref={initialRef}>
  ...

</Modal>
```

This way the button no longer renders in a focused state and we don't lose the benefits of accessibility. The next time the user presses the tab key, the first tabbable element within the `<ModalContent />` component will be focused.
