### ISSUE TITLE
Not possible to add type="submit" to MenuItem

### ISSUE THREAD

**Issue by JClackett** [chakra-ui/chakra-ui#5462]
### Description

I want to be able to add type="submit" to a MenuItem

### Link to Reproduction

I can see in the chakra codebase that it's definitely not possible.

### Steps to reproduce

I want to add a type of "submit" to the MenuItem component, but it keeps overriding it to be "button", I've added an as prop as button too but it doesn't change it.

Example:

 <c.MenuItem as="button" type="submit">

The MenuItem uses the useMenuItem hook which uses the useClickable hook which sets the type to be "button"

https://github.com/chakra-ui/chakra-ui/blob/00114ad4cb7060459bbdeb6ead250a01f3d335dd/packages/clickable/src/use-clickable.ts#L250

The clickable props are spread after the user's htmlProps as seen here:
https://github.com/chakra-ui/chakra-ui/blob/main/packages/menu/src/use-menu.ts#L646

Which means its impossible to set type="submit"

Not sure if this is a feature or bug though? would having type="submit" break something in chakra?

### Chakra UI Version

latest

### Browser

Safari

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by burhanuday** [comment]
Hey @JClackett 
Does the following work for you?
```jsx
          <MenuItem>
            <button type="submit">Hi</button>
          </MenuItem>
```

Since Chakra UI uses CSSReset, button should not have any default styling

sandbox link - https://codesandbox.io/s/menu-button-type-4kqpb?file=/src/index.js

**Comment by JClackett** [comment]
Unfortunately not, firstly, we need to put an as="div" or something on the MenuItem otherwise its a button in a button and that's incorrect html.

and if you take a look at the updated repro I've made here:
https://codesandbox.io/s/menu-button-type-forked-4ydxh?file=/src/index.js

you can see that the form is only submitted when you actually click the "Hi" text, clicking the MenuItem to the side or pressing enter when its selected doesn't submit the form.

**Comment by JClackett** [comment]
I used patch-package to update the chakra menu package to put the clickable props before the html props, so type="submit" wouldn't be overwritten. It's working now, but would be good to get some context from the contributors as to why it was ordered this way in the first place.


I can see that props like isLoading & isDisabled are now being sent straight to the button and so react is complaining that these aren't valid Dom attributes, so there would need to be some changes there. Feels like there has to be a way for type="submit" to be put on menu items??


Here's the patch:

```patch
diff --git a/node_modules/@chakra-ui/menu/dist/chakra-ui-menu.cjs.dev.js b/node_modules/@chakra-ui/menu/dist/chakra-ui-menu.cjs.dev.js
index ee5ef4e..0c95a86 100644
--- a/node_modules/@chakra-ui/menu/dist/chakra-ui-menu.cjs.dev.js
+++ b/node_modules/@chakra-ui/menu/dist/chakra-ui-menu.cjs.dev.js
@@ -576,7 +576,7 @@ function useMenuItem(props, externalRef) {
     isDisabled: isDisabled,
     isFocusable: isFocusable
   });
-  return _extends({}, htmlProps, clickableProps, {
+  return _extends({}, clickableProps, htmlProps, {
     id: id,
     role: "menuitem",
     tabIndex: isFocused ? 0 : -1
diff --git a/node_modules/@chakra-ui/menu/dist/chakra-ui-menu.cjs.prod.js b/node_modules/@chakra-ui/menu/dist/chakra-ui-menu.cjs.prod.js
index ee5ef4e..0c95a86 100644
--- a/node_modules/@chakra-ui/menu/dist/chakra-ui-menu.cjs.prod.js
+++ b/node_modules/@chakra-ui/menu/dist/chakra-ui-menu.cjs.prod.js
@@ -576,7 +576,7 @@ function useMenuItem(props, externalRef) {
     isDisabled: isDisabled,
     isFocusable: isFocusable
   });
-  return _extends({}, htmlProps, clickableProps, {
+  return _extends({}, clickableProps, htmlProps, {
     id: id,
     role: "menuitem",
     tabIndex: isFocused ? 0 : -1
diff --git a/node_modules/@chakra-ui/menu/dist/chakra-ui-menu.esm.js b/node_modules/@chakra-ui/menu/dist/chakra-ui-menu.esm.js
index 4f163ce..69ee99a 100644
--- a/node_modules/@chakra-ui/menu/dist/chakra-ui-menu.esm.js
+++ b/node_modules/@chakra-ui/menu/dist/chakra-ui-menu.esm.js
@@ -552,7 +552,7 @@ function useMenuItem(props, externalRef) {
     isDisabled: isDisabled,
     isFocusable: isFocusable
   });
-  return _extends({}, htmlProps, clickableProps, {
+  return _extends({}, clickableProps, htmlProps, {
     id: id,
     role: "menuitem",
     tabIndex: isFocused ? 0 : -1

```

**Comment by akbo** [comment]
I am running into this problem while trying to create a logout button in a [Remix](https://remix.run/) project as described [here](https://remix.run/docs/en/v1/tutorials/jokes#build-logout-action) and just wanted to drop my workaround here for people who run into the same thing: You can use [useFetcher](https://remix.run/docs/en/v1/api/remix#usefetcher) instead of using a form and a submit button.

Here is a minimal example:

```TSX
import {
  Button,
  Menu,
  MenuButton,
  MenuList,
  MenuItem
} from "@chakra-ui/react";
import { useFetcher } from "remix";

function SomeComponent() {
  const fetcher = useFetcher();

  return (
    <Menu>
      <MenuButton as={Button}>Actions</MenuButton>
      <MenuList>
        <MenuItem
          onClick={() => {
            fetcher.submit({}, { method: "post", action: "/logout" });
          }}
        >
          Log out
        </MenuItem>
      </MenuList>
    </Menu>
  );
}
```
