### ISSUE TITLE
useMediaQuery not supported on iOS 13<

### ISSUE THREAD

**Issue by Edjevw12** [chakra-ui/chakra-ui#5467]
### Description

useMediaQuery hook not supported on safari browsers v13 <=

### Link to Reproduction

https://codesandbox.io/s/nostalgic-https-mwzhs?file=/pages/index.tsx

### Steps to reproduce

open the sandbox on safari browsers v13 <=

### Chakra UI Version

1.6.3

### Browser

Safari 13 <=

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

useMediaQuery hook not supported on safari browsers v13 <=

`"Support for matchMedia is only partial in Safari (Desktop and iOS) including Safari 13 (Technology Preview), because the MediaQueryList object that is returned only supports the legacy .addListener() method, but not .addEventListener()."` 

Similair issue: https://github.com/mdn/sprints/issues/858

![image](https://user-images.githubusercontent.com/37038043/151396831-02282153-ed86-4a6e-af33-53c91a1be223.png)

**Comment by noobinthisgame** [comment]
See https://github.com/chakra-ui/chakra-ui/issues/5197

**Comment by Edjevw12** [comment]
fix: #5474

pushing the fix with patch-package to prod, and issue solved

**Comment by TimKolberger** [comment]
Closed by #5474 and @chakra-ui/react@1.8.3
