### ISSUE TITLE
[Popover] 'Right' position calculated incorrectly for input of type 'number'

### ISSUE THREAD

**Issue by martinpengellyphillips** [chakra-ui/chakra-ui#547]
**Describe the bug**
When a Popover is used with an Input field of type 'number', the Popover position is calculated incorrectly when position is set to 'right'.

![chakra_popover_offset_for_number_input](https://user-images.githubusercontent.com/214338/78021523-4bd1bf00-734b-11ea-82db-b862c264e6d0.jpg)

**Expected Behavior**
The Popover would be positioned correctly (the same as for a standard 'text' Input)

**Reproduce**

https://codesandbox.io/s/chakra-js-starter-pc3e4

**Comment by shubhamkakkar** [comment]
Yes, your current work around is 
`      <Box>
        <Popover placement="right" hasArrow trigger="hover">
          <PopoverTrigger>
            <Input id="number" type="string" width={200} value="500" />
          </PopoverTrigger>
          <PopoverContent>
            <PopoverArrow />
            <PopoverBody>Hello world</PopoverBody>
          </PopoverContent>
        </Popover>
      </Box>`

**Comment by with-heart** [comment]
Hi @martinpengellyphillips! This has been fixed in 1.0. You can see it working correctly here: https://codesandbox.io/s/chakra-js-popover-number-bug-10qne?file=/src/index.js
