### ISSUE TITLE
Text Component noOfLines prop does not support responsive object 

### ISSUE THREAD

**Issue by jcleefw** [chakra-ui/chakra-ui#5473]
### Description

When I use the Text component with noOfLines props, i want to be able to pass in a responsive object instead of array

Current acceptance of responsive value
`noOfLines={[7, 5, 3]}`

Proposed acceptance of responsive value
`noOfLines={{ lg: 3, md: 5, sm: 7 }}`

### More issue after digging around 
After doing some digging around the code base, I've found the fundamental issue comes from the acceptance of the `noOfLines` acceptance of responsive array is a bit different from the rest

responsive value uses `objectToArrayNotation` to convert object to Array. So the result as below
```
objectToArrayNotation({ lg: 3, md: 5, sm: 7 }) // will produce [null, 7, 5, 3]
```

Text `noOfLines` prop only takes into account array of 3 value. It wants an exact value of [7, 5, 3] for it to render correctly. Since `objectToArrayNotation` first value is `null` hence breaking the responsive rendering 

### Link to Reproduction

https://codesandbox.io/s/peaceful-bassi-ogqpx?file=/src/index.tsx

### Steps to reproduce

See sandbox example.. 

### Chakra UI Version

1.8.1

### Browser

Chrome 97, firefox

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jcleefw** [comment]
Happy to push a fix to this but i think it's best I get some idea of what's the best practice to resolve an issue as this?

Something like this would do the trick, but is this the best way to implement the fix?

```
export const Text = forwardRef<TextProps, "p">((props, ref) => {
  const styles = useStyleConfig("Text", props)
  const { className, align, decoration, casing, noOfLines, ...rest } =
    omitThemingProps(props)
  const [_first, ...others] = objectToArrayNotation(noOfLines)
  console.log(others)

  const aliasedProps = filterUndefined({
    textAlign: props.align,
    textDecoration: props.decoration,
    textTransform: props.casing,
  })

  return (
    <chakra.p
      ref={ref}
      className={cx("chakra-text", props.className)}
      {...aliasedProps}
      {...rest}
      noOfLines={others}
      __css={styles}
    />
  )
})
```

**Comment by segunadebayo** [comment]
Hi @jcleefw,

This isn't a bug but a misunderstanding of how the responsive prop works for the array and object notation.

If you try this: `<Text maxWidth="500px" noOfLines={{ lg: 3, md: 5, base: 7 }}>`, you'll that it works as expected. Responsive props are mobile-first and usually required a "base" value which is tweaked based on the breakpoint.

Here's how to interpret the expression:

`noOfLines=[7, 5, 3]`: By default, the `noOfLines` start at `7` and then switches to `5` from `sm` upwards, then switch to `3` from `md` upwards.

To achieve the same with the object notation (esp the base or default value), you'll need to use the `base` key.

`noOfLines={ md: 3, sm: 5, base: 7 }`: The base or default value is `7`, and then switches to `5` from `md` upwards, the switches to `3` from `md` upwards.

Please refer to the responsive style section of the docs to understand better.

Thanks
