### ISSUE TITLE
IconButton padding overriding

### ISSUE THREAD

**Issue by DSDeadShot** [chakra-ui/chakra-ui#5476]
### Description

When passing px and py props to IconButton, these get overridden by the padding that is set to 0px. Only works when only passing p

### Link to Reproduction

https://codesandbox.io/s/amazing-franklin-n32p5?file=/src/index.tsx

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

latest

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by ShubhamSolanki24** [comment]
i would like to work on this issue.

**Comment by fredericbahr** [comment]
Any updates on this? Problem still occures

**Comment by vladRGaembla** [comment]
@qwertxr any updates on why this issue is closed? I faced the same problem. If the problem still exists I can try to contribute because it blocks our team from updating to the latest chakra version

**Comment by vladRGaembla** [comment]
btw Passing only `p` didn't help me
