### ISSUE TITLE
extending BreadcrumbLink variant doesnt work

### ISSUE THREAD

**Issue by omerman** [chakra-ui/chakra-ui#5488]
### Description

When extending variant of BreadcrumbLink giving it color prop, it does not seem to work

### Link to Reproduction

https://codesandbox.io/s/hopeful-morning-drgz8?file=/src/index.tsx

### Steps to reproduce

![image](https://user-images.githubusercontent.com/6780529/151719270-f37a508e-08e6-4d9e-a727-210f18afae4b.png)

### Chakra UI Version

latest

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Please help :) Thanks for the amazing library!

**Comment by noobinthisgame** [comment]
What you are trying to do is to theme a multipart component. You can find out wether a component has multiple parts by checking the theme source by clicking on "view theme source" at the top of the component docs. 
You then can follow the steps in the [theming docs for multipart components](https://chakra-ui.com/docs/theming/component-style#styling-multipart-components).
I've made some changes to your example using multipart theming in this codesandbox: https://codesandbox.io/s/xenodochial-cookies-mjm91?file=/src/index.tsx

**Comment by omerman** [comment]
Brilliant. Thank you!
