### ISSUE TITLE
Theming prop `size` conflicts with input prop `size`

### ISSUE THREAD

**Issue by davidkpiano** [chakra-ui/chakra-ui#5489]
### Description

When I want to set the DOM attribute `size={3}` of an `<input>` element, I am unable to do it with `<Input>` since `size` is interpreted as a theme prop, and not a native attribute.

### Link to Reproduction

https://codesandbox.io/s/jovial-mendeleev-upylk?file=/src/index.js

### Steps to reproduce

See above CodeSandbox

### Chakra UI Version

1.6.3

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by jcleefw** [comment]
I think you are using size wrongly. Size is not a value of width / padding. It's actually almost sort of a variable.

As you can see in the [Input doc about Size](https://chakra-ui.com/docs/form/input#changing-the-size-of-the-input), there are some predefined values of sizes you can use. However, you can also defined new variable and styling for a different size [using component styling](https://chakra-ui.com/docs/theming/component-style#usemultistyleconfig-api).

If you just simply want to defined the width of the input, this would do the trick
https://codesandbox.io/s/cocky-spence-1zze8?file=/src/index.js

**Comment by davidkpiano** [comment]
Thanks for the response @jcleefw - I'm aware of Chakra's `size` prop. I'm trying to point out that there is a naming conflict with it and the _native_ `size` attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/size

**Comment by noobinthisgame** [comment]
Hey :) 
I was wondering if you had a specific reason why you want to use the Input component?
If there is not, then maybe using the chakra factory for an input could solve your problem. It would let you use the chakra props on the input element but also has the size attribute working as you expect. 
See this example: https://codesandbox.io/s/heuristic-flower-jnmbw

Let me know if that solves your problem :)

**Comment by TimKolberger** [comment]
Hi David,
Thanks for raising this issue.

I think this is prop name clash is comparable to the attributes `width` and `height` for the Image component where we added `htmlWidth` and `htmlHeight` as props.

My suggestion would be to add a new prop to the Input component called `htmlSize` and pass it to the input DOM element.

Would that solve your issue?

**Comment by davidkpiano** [comment]
> Hi David, Thanks for raising this issue.
> 
> I think this prop name clash is comparable to the attributes `width` and `height` for the Image component where we added `htmlWidth` and `htmlHeight` as props.
> 
> My suggestion would be to add a new prop to the Input component called `htmlSize` and pass it to the input DOM element.
> 
> Would that solve your issue?

Yep, sounds like a good solution!
