### ISSUE TITLE
Pass initial breakpoint to our Chakra Theme Provider to have a better first paint!

### ISSUE THREAD

**Issue by maapteh** [chakra-ui/chakra-ui#5491]
### Description

As a continuation for issue #5234, which got solved. Is it possible we can set an initial value for breakpoint to our ThemeProvider which then picks that as default when given for everything?

I have centrally during SSR a best educated guess of the breakpoint by using the user-agent. And i want to simplify passing that value further down the three.

### Problem Statement/Justification

We have some browser reflows when using the useBreakpoint hook since its a client-side only hook with some options to set a default but this default will always make 50% of our users unhappy by lots of layout shifts. So for most mobile/desktop cases we solved it greatly by guessing the breakpoint from the server, which now results in 6% of reflows initially. I know its considered as bad practise to use agent sniffing but its the best possible option we have on the server.

So we have 3 cached versions for breakpoints: 'sm', 'md' and 'lg' on the server. Centrally we created a BreakpointProvider which indeed then listens on window resize and checks matchmedia to update.

When we have this integrated in the theme provider we can even make our tests way simpler by not mocking/stubbing matchMedia at all, but just set the value directly by providing centrally a mocked BreakpointProvider. So technically testing becomes also very easy!

### Proposed Solution or API

I created a single Provider and thought maybe that one can be integrated to the theme and further consumed. Before i go into code ,i want to know what you think about it. Because i lost some time when i wanted to show that a single theme was better then supporting always all themes which were not tree shakable :)

### Alternatives

Having an initial state in the useBreakpoint hook, but then i just had a mobile first for every first cycle, which looked weird for our desktop users

### Additional Information

https://mpth.medium.com/render-server-side-for-specific-viewports-with-option-to-cache-1196fbf936c3

**Comment by anton-johansson** [comment]
Related pull request: #4268

**Comment by itzr** [comment]
I was having similar problems related to useBreakpoint & useBreakpointValue. 

My issue was that I was using useBreakpointValue all over my components to make them responsive but the first paint looked terrible. 

It was only after moving the browser width around did they start to look as intended. 

This issue was only apparent in Production, and not in Dev mode.

I overcame most of the issues by not relying on useBreakpointValue and passing an array instead. For example, instead of:
```
width: useBreakpointValue({base: <base_value>,...,xl: <xl_value>})
```
I did this:
```
width: {[<base_value>,<sm_value>,<md_value>,<lg_value>,<xl_value>]}
```

I'm not sure why this works over useBreakpointValue(), but it did for me...
