### ISSUE TITLE
[ColorModeProvider] Types for the useColorMode are incorrectly named

### ISSUE THREAD

**Issue by vueu** [chakra-ui/chakra-ui#55]
So in the typings for the hook: `useColorMode`, it returns an object with two values: of course, the `mode` and the `toggle`.

However, in the actual code, it is expecting `colorMode` and `toggleColorMode`, so in the type defs the names are off. Easy fix, but TypeScript will give an error without this change so it's currently unusable.

I would be happy to put in a PR :)

**Comment by segunadebayo** [comment]
Thank you @vueu
