### ISSUE TITLE
Value of NumberInput invisible if maxW lower than 55px

### ISSUE THREAD

**Issue by l3szcz** [chakra-ui/chakra-ui#5510]
### Description

The NumberInput component can't be smaller than ~55px, otherwise inner style of input `paddingInline` covers the input value.

### Link to Reproduction

https://codesandbox.io/s/magical-mestorf-dm77i?file=/src/index.js

### Steps to reproduce

_See reproducion link._

### Chakra UI Version

1.8.1

### Browser

Microsoft Edge 97.0.1072.76

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Workaround is setting `paddingInline={0}` on the `NumberInputField`.

**Comment by segunadebayo** [comment]
Hi @l3szcz,

Thanks for reporting this. The padding was added to cater to the stepper buttons.

If you don't want this, feel free to remove the padding on the input by setting `px="0"` or overriding specific padding. This is an app-specific change and not a change we should make in Chakra UI.

Thanks for understanding
