### ISSUE TITLE
useToast portal is in the DOM structure but not visible.

### ISSUE THREAD

**Issue by chrisfernandes102** [chakra-ui/chakra-ui#5512]
### Description

When I use useToast, the dom is updated, but the portal is not visible

### Link to Reproduction

NA

### Chakra UI Version

1.7.3

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by chrisfernandes102** [comment]
![image](https://user-images.githubusercontent.com/21992184/152281974-203b7ad7-5c69-43e3-a965-3f0747511bc1.png)

**Comment by with-heart** [comment]
Can you please create a reproduction using https://codesandbox.io/? It's almost impossible to know what the problem is from just a screenshot.

**Comment by fijijavis** [comment]
@with-heart 👋  Hope you are doing well!  

I stumbled across this issue today trying to track down some super weird behavior I was seeing with approval toast in our app.  Manual testing I was able to see the toast without any problem.  However, automated testing with Playwright the toast was in the DOM but was 💯  not visible leading to regression failures.

Wanted to make sure it wasn't something goofy we are doing so I went [here](https://v0.chakra-ui.com/toast#success) to see if I could reproduce the issue with `Show Success Toast`.  Sure enough I've been able to reproduce the problem.

Here's a self contained playwright script that will reproduce the issue.

```javascript
(async () => {
  const { chromium } = require("playwright");
  const browser = await chromium.launch({
    headless: false,
  });
  const page = await browser.newPage();
  // run with commented out line and you'll get the toast; uncomment line and the toast will not be visible
  //await page.setViewportSize({ width: 1600, height: 1200 });
  await page.goto("https://v0.chakra-ui.com/toast#success");
  await page.click("text=Show Success Toast");
  await new Promise((res) => setTimeout(res, 5000));
  await browser.close();
})();
```

And here's my package.json
```
{
  "name": "sandbox-playwright",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "playwright": "^1.19.1"
  }
```

run `node path/to/script.js` to execute.  

I haven't been able to track down _why_ manipulating the view port causes a problem and I have no clue if this even remotely matches anything the OP was doing but this felt like too much of a coincidence to not post something here.

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Please follow the issue template as we're not able to act on issues that are lacking important information.

**Comment by segunadebayo** [comment]
Hi @fijijavis. It's hard to understand what you mean without a reproduction.

**Comment by fijijavis** [comment]
@segunadebayo The reproduction is Chakra's own site https://v0.chakra-ui.com/toast#success and can be seen when running the Playwright script I provided.
