### ISSUE TITLE
Popover not working in Safari < 14.1 due to inset not being supported

### ISSUE THREAD

**Issue by mislavmiocevic** [chakra-ui/chakra-ui#5514]
### Description

When I use Popover in a longer content in Safari I get the issue due to inset not being supported

### Link to Reproduction

https://codesandbox.io/s/sandpack-project-forked-ruxsi?file=/package.json

### Steps to reproduce

1. In Safari 14.0.3 or below go to [CodeSandbox link](https://codesandbox.io/s/sandpack-project-forked-ruxsi?file=/package.json)
2. Scroll down to the end of the example
3. You can see white space in the HTML body

### Chakra UI Version

1.7.3

### Browser

Safari 14.0.3

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

`inset` CSS property is not supported in Safari < 14.1.

Because of that, Popover makes some space in Portal but it should not.

The fix can be to set top/right/bottom/left explicitly.

In this image we can see property added in Chrome, but in Safari it is not there and you need to add it manually as top/right/bottom/left.

![Screenshot 2022-02-03 at 14 40 30](https://user-images.githubusercontent.com/67387665/152353850-44c206ae-aff3-4aba-b6f6-82a8d1908e0b.png)

Code
```
import * as React from "react";
import {
  Box,
  Flex,
  Popover,
  PopoverArrow,
  PopoverBody,
  PopoverContent,
  PopoverTrigger,
  Portal
} from "@chakra-ui/react";

export default function Example() {
  return (
    <Flex h="100%">
      {/* If you remove h it works */}
      <Box bg="red" flex="1" overflowY="auto">
        {/* If you remove overflowY it also works */}
        <Box bg="green" h="800px">
          Some long content before Popover
        </Box>
        <Popover trigger="hover">
          <PopoverTrigger>
            <Box bg="yellow">IF YOU HOVER ME ONCE THEN THERE IS NO ISSUE</Box>
          </PopoverTrigger>

          <Portal>
            <PopoverContent>
              <PopoverArrow />
              {/* Comment this PopoverBody to see that there is no issue */}
              <PopoverBody>Popover body</PopoverBody>
            </PopoverContent>
          </Portal>
        </Popover>
        <Box bg="green" h="800px">
          Some long content after Popover
        </Box>
      </Box>
    </Flex>
  );
}

```

**Comment by isBatak** [comment]
It seems like [this style](https://github.com/chakra-ui/chakra-ui/blob/e1057b085f47916fb148561e40fe0b4afbdd633f/packages/popper/src/use-popper.ts#L239) is not injected into `styles` on Safari...
