### ISSUE TITLE
useDisclosure causes component to be rendered twice

### ISSUE THREAD

**Issue by kk21** [chakra-ui/chakra-ui#5517]
### Description

When useDisclosure is in the component code, the component is rendered twice.

### Link to Reproduction

https://codesandbox.io/s/compassionate-germain-ixz9x?file=/pages/index.tsx

### Steps to reproduce

1. Go to 'https://codesandbox.io/s/compassionate-germain-ixz9x?file=/pages/index.tsx'
2. Click on the embedded browser's Console tab
3. Click on the embedded browser's Refresh icon
4. The console message is shown twice when useDisclosure is in the component code
5. Do the same for 'https://codesandbox.io/s/sad-yonath-c7mk9?file=/pages/index.tsx'
6. The console message is only shown once when useDisclosure is commented out

### Chakra UI Version

1.8.1

### Browser

Google Chrome 98

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kk21** [comment]
In my local nextjs environment, even if I set reactStrictMode in next.config.js to false, the same problem exists.

**Comment by with-heart** [comment]
Possibly related to #5046

**Comment by segunadebayo** [comment]
Hi @kk21,

I don't see this issue at all both in CodeSandbox and local. Looking at the code of useDisclosure, I don't see how it'll cause a double render.

That said, it's possibly related to the strict mode in react or something you're doing in your code. This is a non-issue but I appreciate you bringing it up.

**Comment by kk21** [comment]
> @kk21 did you manage to resolve this? Also getting this issue...

No... it is a real issue though.

**Comment by piersolenski** [comment]
This seems to be problematic when `useDisclosure` is used twice on the same page to control different components.

**Comment by ValentinGurkov** [comment]
I'm experiencing this as well. By adding the `useDisclosure` hook to my component, it is immediately rendered twice. Without it only once.

**Comment by jay-babu** [comment]
@segunadebayo happening to me as well

**Comment by jay-babu** [comment]
destructuring the result before passing it prevents this for me
