### ISSUE TITLE
In FormLabel, add _filled & _empty or similar to the label be aware of the "state" of the input

### ISSUE THREAD

**Issue by semasad** [chakra-ui/chakra-ui#5542]
### Description

Add as prop to be inline or extend in the theme the capability of the FormLabel to be aware of the "content" of the input in the FormControl with props _filled and _empty (or similar), so we can handle some better styles if the input is filled or not.

### Problem Statement/Justification

When someone try to add more "complex" behaviour to the label of a form based on the state of it. So we can not only alert with the _invalid, also with if its empty or not, and config this by the theme. This make much easy to develop forms, so we do not need to make additional config form by form, we can define it by the theme.

This is not only functional, whit this we can do advance form interactions (like the ones used with Material by Google whit label + form combo).

### Proposed Solution or API

`
<FormControl>
   <FormLabel _empty={{...}} _filled={{...}}}> Label </FormLabel>
   <Input {...} />
</FormControl>
`

### Alternatives

- Use pseudoclasses in the theme.
- Create a new component in the project.

**Comment by Patrick-Ullrich** [comment]
Would _focusWithin help you here? Check out some of the usage here: https://chakra-ui.com/docs/components/recipes/floating-labels

Does _empty / _filled do something you wouldn't be able to achieve with this?

**Comment by semasad** [comment]
> Would `_focusWithin` help you here? Check out some of the usage here: https://chakra-ui.com/docs/components/recipes/floating-labels
> 
> Does _empty / _filled do something you wouldn't be able to achieve with this?

Wow! This is enough, thanks! I don't know why I do not see this.

**Comment by segunadebayo** [comment]
Thanks for chiming in @Patrick-Ullrich. Please use the recipe in the docs.
