### ISSUE TITLE
Storybook Addon: configuration to remove the color mode switcher

### ISSUE THREAD

**Issue by davidhousedev** [chakra-ui/chakra-ui#5544]
### Description

I recently began migrating my CSS to Chakra from CSS modules and already have Storybook stories publishing visual regression tests to Chromatic. I would like to be able to disable the color mode switch button injected to my stories by the Chakra add-on because it causes a visual diff in my existing visual regression tests.

### Problem Statement/Justification

As someone who has existing visual regression tests created with a different CSS framework, it's important to me that my migration to Chakra UI results in no visual diffs to my existing UI. In an ideal world, I could add Chakra, re-run my visual regression tests, and have them all pass because I have refactored my styles without changing my UI.

The automatically-injected color mode switch button causes visual diffs, creating roadblocks as I try to use the Chakra storybook add-on.

### Proposed Solution or API

If the color mode switcher could be disabled via configuration parameters, I could use the storybook add-on as-is without impediment.

_preview.js_
```
export const parameters = {
  chakra: {
    theme,
    enableColorModeControl: false, // default could be true
  },
}
```

### Alternatives

I'm currently working around this by importing the storybook add-on's `webpackFinal` function. This allows me to get the benefit of the add-on's web pack handling without without the color mode button.

_main.js_
```
const {
  webpackFinal,
} = require('@chakra-ui/storybook-addon/preset/dist/chakra-ui-storybook-addon-preset.cjs.dev')

module.exports = {
  // [...]
  webpackFinal: async (config) => {
    return webpackFinal(config)
  },
}

```

**Comment by ngxCoder** [comment]
As I mentioned in another issue: If nobody else solves this, I will try to add an option to remove the color mode switcher this week; let me finish some tasks before

**Comment by sauldeleon** [comment]
hey @ngxCoder , thanks for taking a look into this.

Would it be possible to hide it for certain stories, instead of hiding it for all of them?

I have taken a look into the code but honestly, I dont know where to start!

**Comment by ngxCoder** [comment]
Hi @sauldeleon, I'm working on it right now finally.
If you want to contribute, you need to start for the storybook tutorial: [https://storybook.js.org/docs/react/addons/writing-addons](https://storybook.js.org/docs/react/addons/writing-addons)

I want to find a way to move the Switcher to the toolbar if you're going to contribute.
