### ISSUE TITLE
`as` prop does not change ref type: `Type 'RefObject<Flickity>' is not assignable to type 'RefObject<HTMLDivElement>'`

### ISSUE THREAD

**Issue by b-novikov-ipersonality** [chakra-ui/chakra-ui#5547]
### Description

When I pass `ComponentB` to `ComponentA`'s `as` prop, I expect `ref` prop to be of type of the passed component (`RefObject<ComponentB>`) but instead it expects a ref of type `RefObject<ComponentA>` 

### Link to Reproduction

https://github.com/b-novikov-ipersonality/chakra-ui-ref

### Steps to reproduce

1. `git clone git@github.com:b-novikov-ipersonality/chakra-ui-ref.git issue`
2. `cd issue && yarn install`
3. Open `issue` folder in editor
4. Open `src/App.tsx` file
5. See Typescript error

### Chakra UI Version

1.8.3

### Browser

Chrome Version 100.0.4867.0 (Official Build) dev (64-bit)

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by TimKolberger** [comment]
Hi @b-novikov-ipersonality,

This is a known limitation of the as prop, kindly see the [Chakra UI Docs | Guides | as prop](https://chakra-ui.com/guides/as-prop) for options. 

The as prop typings are quite complex, for the TypeScript compiler performance and our brains as well 🤯
