### ISSUE TITLE
useBreakpointValue() works incorrectly with custom breakpoints

### ISSUE THREAD

**Issue by Molju** [chakra-ui/chakra-ui#5555]
### Description

I define additional breakpoint value preSm: '36em'. It works properly with style properties, but when I use useBreakpointValue({ base: true, lg: false }), it returns true for base to preSm and md to lg, but false for preSm to md

### Link to Reproduction

https://codesandbox.io/s/adoring-sky-khuko?file=/src/index.js

### Steps to reproduce

1. Add custom breakpoint to theme (preSm: '36em')
2. Use useBreakpointValue({ base: true, lg: false })
3. Get true for:
base to preSm
md to lg
4. Get false for:
preSm to md
lg+

It fixes by adding preSm to responsive object - useBreakpointValue({ base: true, preSm: true,  lg: false })

### Chakra UI Version

1.6.7

### Browser

all

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by TimKolberger** [comment]
I am reopening this because my PR did not address this issue. 

The useBreakpoint hook uses CSS media queries with min and max width. The responsive object uses min width queries. This leads to the observed difference in behavior.

**Comment by TimKolberger** [comment]
> The useBreakpoint hook uses CSS media queries with min and max width. The responsive object uses min width queries. This leads to the observed difference in behavior.

Despite this being true, this was not the issue here. The useBreakpointValue hook operated on an unsorted breakpoints object too, which got it confused about the order.

**Comment by ogheneovo12** [comment]
just encountered this issue too, it ignores my custom breakpoint

**Comment by math-marcellino** [comment]
Still getting this issue while implementing custom breakpoints

**Comment by TimKolberger** [comment]
Kindly add a reproduction in codesandbox

**Comment by ogheneovo12** [comment]
later found a fix, use em unit's for custom breakpoints instead of px

**Comment by math-marcellino** [comment]
> later found a fix, use em unit's for custom breakpoints instead of px

Thank you sir, it worked!

**Comment by ankursehdev** [comment]
> later found a fix, use em unit's for custom breakpoints instead of px

This saved my day and frustration, wondering why it doesn't work for PX

**Comment by tylerbecks** [comment]
This solved it for me https://github.com/chakra-ui/chakra-ui/issues/4813#issuecomment-939194128
