### ISSUE TITLE
Automatic RadioGroup or Select component

### ISSUE THREAD

**Issue by cameronelliott** [chakra-ui/chakra-ui#5556]
### Description

It would be great if there was a component which automatically created a RadioGroup or Select depending
upon the number of items to choose between.
for example, if the number of items is <= 4, display a Radiogroup, if >4, Display a Select.

### Problem Statement/Justification

It is mentioned in the Chakra docs that a RadioGroup is often better than a select for a few number of items.
It would be nice if Chakra did this automatically for you.

### Proposed Solution or API

I think the request is hopefully self explanatory.

### Alternatives

Well, as a user I can live without?

### Additional Information

none.

**Comment by takethefake** [comment]
Hej @cameronelliott thanks for reaching out!

This is something that we consider a good style, but this special abstraction you mention can be better implemented in your applications if you wish than writing a general component in chakra. Since there is nothing the user directly benefits from.
