### ISSUE TITLE
[Switch] Square corners instead of rounded corners

### ISSUE THREAD

**Issue by EricKulchycki** [chakra-ui/chakra-ui#556]
**Description**
It looks like the Switch component is displaying as square.

**Expected Behaviour**
Should be rounded, as shown in the documentation.

**To Reproduce**
1. Render Switch component from ChakraUI. 

**Suggested solution**
Instead of using border radius property full use border-radius: 500rem;

**Desktop:**
 - OS: OSx
 - Browser Chrome
 - Version 80.0.3987.149

**Comment by EricKulchycki** [comment]
Sorry I'm not smart.

**Comment by ogheneovo12** [comment]
hey how where you able to fix this
