### ISSUE TITLE
[Box] Position absolute overtakes box styling

### ISSUE THREAD

**Issue by samullman** [chakra-ui/chakra-ui#557]
**Describe the bug**
When assigning position absolute to an image or a box, the styles of the absolutely positioned elements overtake (z-index) a fellow child element. 
<img width="1148" alt="Screen Shot 2020-04-02 at 2 29 31 PM" src="https://user-images.githubusercontent.com/10147333/78303059-d0117700-74f0-11ea-878f-ddd286fa622d.png">

**Expected Behavior**
The middle element from screenshot above should look like this.
<img width="1244" alt="Screen Shot 2020-04-02 at 2 44 15 PM" src="https://user-images.githubusercontent.com/10147333/78303085-dbfd3900-74f0-11ea-9f9e-bb5ed0b1c75b.png">

**To Reproduce**
- Use this template:
- List the steps to reproduce the behavior:
1. Create a parent div.
2. One child is position absolute. 
3. One child has no position assigned. 
4. Absolutely position element will overtake styles of child with no position assigned. 

**Suggested solution(s)**
None.

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.3
 - Browser: Chrome
 - Version: 80.0.3987.149 

**Additional context**

**Comment by samullman** [comment]
I was able to fix this by giving middle element explicitly position="relative"
<img width="1244" alt="Screen Shot 2020-04-02 at 2 44 15 PM" src="https://user-images.githubusercontent.com/10147333/78303332-5037dc80-74f1-11ea-8510-dd91d62c3da6.png">

**Comment by segunadebayo** [comment]
Hi @samullman,

Thanks for this issue.  I don't think this as anything with Chakra's internal details. Chakra doesn't come with any `position` defaults, so it's completely up to you how you handle it.

I'm glad you solved this style problem.
