### ISSUE TITLE
Move range with dragging

### ISSUE THREAD

**Issue by itta611** [chakra-ui/chakra-ui#5572]
### Description

Dragging the track part of the range slider will move the nearest thumb, but it is more convenient to be able to drag the range track.

### Problem Statement/Justification

We'll get a better UX/UI this way.

### Proposed Solution or API

none

### Additional Information

https://chakra-ui.com/docs/form/range-slider

**Comment by segunadebayo** [comment]
Hi @itta611,

This sounds interesting. After thinking about this, it's not a feature we're looking to support for now.

Thanks for understanding.
