### ISSUE TITLE
A set of prose classes to add beautiful typographic defaults (Tailwind Typography functionality)

### ISSUE THREAD

**Issue by PrimozRome** [chakra-ui/chakra-ui#5577]
### Description

Provide something like [Tailwind Typography](https://tailwindcss.com/docs/typography-plugin).

_Beautiful typographic defaults for HTML you don't control. The official Tailwind CSS Typography plugin provides a set of prose classes you can use to add beautiful typographic defaults to any vanilla HTML you don’t control, like HTML rendered from Markdown, or pulled from a CMS._

### Problem Statement/Justification

These days a lot of content is coming from headless CMS where you do not control the HTML. We need a simple way to format this content inside a container with beautiful typography defaults with margins, font sizes etc. For this purpose Tailwind guys created [Tailwind Typography](https://tailwindcss.com/docs/typography-plugin).

### Proposed Solution or API

I think a new component could be created like `<Typography />`. Typography defaults should be easily overridable in the setup / theme.

**Comment by segunadebayo** [comment]
Hi @PrimozRome,

There's a new recipe and guide for this here: https://chakra-ui.com/guides/recipes/prose

Enjoy!
