### ISSUE TITLE
Transition elements such as Collapse do not play nicely with flex

### ISSUE THREAD

**Issue by yourtallness** [chakra-ui/chakra-ui#5586]
### Description

When I render a flex item as={Collapse} it overrides its display from flex to block.

### Link to Reproduction

https://codesandbox.io/s/empty-shape-zfdbi6

### Steps to reproduce

Render any component with a flex display as a `Collapse` to make it collapsible, e.g. an `InputGroup`.

The layout will break because `Collapse` uses `display: block` to control visibility.

See also codesandbox link for reproduction.

### Chakra UI Version

1.7.2

### Browser

Google Chrome 98

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by m4x3d** [comment]
Hi, your codesandbox looks empty. Can you please have a look?
