### ISSUE TITLE
Add option to specify initially focused menu item

### ISSUE THREAD

**Issue by lukasbach** [chakra-ui/chakra-ui#5598]
### Description

Add an option in the menu's props to define which item is focused initially when it is opened.

### Problem Statement/Justification

We use the menu as a custom select component, which works in functionality for most parts, except that a select component requires that the previously selected item is the one that is focused initially when it is opened. Chakra always automatically focuses the first menu item when it is opened. I understand that this might be a stretch for an use case for the menu component, since it is not a select component, but the solution I believe is really easy to impelement and might be helpful to others that use the component in a similar way (e.g. #3411).

### Proposed Solution or API

* Add a `initialFocusIndex?: number;` entry in the `UseMenuProps` here: https://github.com/chakra-ui/chakra-ui/blob/main/packages/menu/src/use-menu.ts#L69
* Extract it with `initialFocusIndex = -1,` from here: https://github.com/chakra-ui/chakra-ui/blob/main/packages/menu/src/use-menu.ts#L144
* Use it as initial focus index value for initialization by using `const [focusedIndex, setFocusedIndex] = React.useState(initialFocusIndex)` here: https://github.com/chakra-ui/chakra-ui/blob/main/packages/menu/src/use-menu.ts#L217

### Alternatives

* Use a regular HTML select input, however that does not yield the customization possibilities as does Chakras menu component

### Additional Information

Of course I'm happy to take a PR on this if this feature is desired.

**Comment by feifei-x** [comment]
I have the same issue, is there a plan to get this merged?

**Comment by Qocotzxin** [comment]
Is this still in progress? I'm trying to use this menu as a navigation one and would love to have this functionality to focus the correct option depending on the route. Happy to help as well if needed :)

**Comment by igorzheludkov** [comment]
> Is this still in progress? I'm trying to use this menu as a navigation one and would love to have this functionality to focus the correct option depending on the route. Happy to help as well if needed :)

I'sm stuck with the same. Temporary fix this by passing custom style with conditional ternary operator to <MenuItem style={categoryData.id === e.id ? { background: 'grey' } : { background: 'transparent' }}>.  If 'id' of item matches 'id' of the page, style is applied.  It's working as desired)

**Comment by kdfriedman** [comment]
Any progress on this? This is my current workaround:

```js
const handlePseudoFocus = (menuItemToFocus) => {
    if (!menuItemToFocus) return;
    menuItemToFocus.focus();
    menuItemToFocus.tabIndex = 0;
};

const menuItems = [
    {
      id: 0,
      hasParentComponent: true,
      parent: Link,
      props: { className: 'header__nav-menu-item', tabIndex: '-1' },
      parentProps: { as: NavLink, to: '/profile', style: { textDecoration: 'none' } },
      item: MenuItem,
      label: 'Profile',
      pathname: '/profile',
    },
    {
      id: 1,
      hasParentComponent: true,
      parent: Link,
      props: { className: 'header__nav-menu-item', tabIndex: '-1' },
      parentProps: { as: NavLink, to: '/integrations', style: { textDecoration: 'none' } },
      item: MenuItem,
      label: 'Integrations',
      pathname: '/integrations',
    },
  ];

  const generateMenuItems = (menuItems) => {
    return menuItems.map((item) => {
      const { hasParentComponent, parent: Parent, item: Item, id, props, parentProps, label, pathname } = item;
      return (
        <React.Fragment key={id}>
          {hasParentComponent ? (
            <Parent {...parentProps}>
              <Item
                {...props}
                style={location.pathname === pathname ? { backgroundColor: '#EDF2F7' } : { backgroundColor: '#FFF' }}
                ref={location.pathname === pathname ? menuItemRef : null}
              >
                {label}
              </Item>
            </Parent>
          ) : (
            <Item {...props}>{label}</Item>
          )}
        </React.Fragment>
      );
    });
  };

//.....further down in the JSX
<Menu onOpen={() => handlePseudoFocus(menuItemRef.current)}>
//children.......
```

**Comment by ricsands2801** [comment]
+1

**Comment by Michael-indochat** [comment]
## How to set initial focused item when using initialFocusIndex in my code?

- Tags: React, Chakra UI, Menu, initialFocusIndex

## Question Description:

I'm using the Chakra UI Menu component and trying to set the initial focused item when opening the menu. According to the official documentation, I found a new prop called initialFocusIndex that can be used to specify the initial focused item. However, I'm confused about how to use it in my code.

Here is the current code snippet:

```jsx
// Relevant imports omitted

const SwitchAccountMenu = ({
  officialAccountListQuery,
  currentAccount,
}: SwitchAccountMenuProps) => {
  // Omitted part of the code

  return (
    <Menu isLazy placement="left">
      <MenuButton
        w="100%"
        px={4}
        py="10px"
        mb="10px"
        _hover={{ bg: "#F5F5F5" }}
      >
        {/* Button content */}
      </MenuButton>
      <MenuList w="260px" maxH="126px" overflowY="auto">
        {/* Menu items */}
      </MenuList>
    </Menu>
  );
};

export default SwitchAccountMenu;
```

I'm trying to understand how to use the initialFocusIndex prop in the Menu component. Can someone provide an example to help me better understand how to use it? I would like to set the focus on the first menu item when opening the menu.

Thank you for your help! @lukasbach

**Comment by xencodes** [comment]
any update on this?

**Comment by nicolas-goudry** [comment]
For anyone stumbling on this issue, here is how to do it the Chakra way with Typescript:

```tsx
type OptionsMenuProps = {
  readonly label: string
  readonly options: Array<{
    id: string
    label: string
  }>
  readonly selectedOption: string
  readonly onChange: (id: string) => void
}

function OptionsMenu({ label, options, selectedOption, onChange }: OptionsMenuProps) {
  const selectedItemRef = useRef<HTMLButtonElement>(null)

  return (
    <Menu initialFocusRef={selectedItemRef}>
      <MenuButton>
        Options <ChevronDownIcon />
      </MenuButton>
      <MenuList>
        {options.map(({ id, label }) => {
          const refProp = id === selectedOption ? { ref: selectedItemRef } : {}

          return (
            <MenuItem {...refProp} key={id} onClick={() => onChange(id)}>
              {label}
            </MenuItem>
          )
        })}
      </MenuList>
    </Menu>
  )
}
```
