### ISSUE TITLE
Congratulations on your wedding, Segun & Esther! 💍❤️

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui#5622]
### Description

Congratulations on your wedding, Mr. & Mrs. @segunadebayo  and @estheragbaje !

As core maintainers and contributors of Chakra UI you have given us a great component library and for some, you've inspired to do great work. I pray you both have a prosperous marriage!

Blessings,
Chakra UI Community

### Problem Statement/Justification

N/A

### Proposed Solution or API

`npm install @chakra-ui/marriage` LOL 🤣

**Comment by segunadebayo** [comment]
Thank you so much, guys! This means a lot 😊
