### ISSUE TITLE
Allow disabling Check Icon in `MenuItemOption`

### ISSUE THREAD

**Issue by anubra266** [chakra-ui/chakra-ui#5629]
### Description

In the `Menu` component, we can use `MenuOptionGroup` to have a `radio` or `checkbox` functionality, The chosen item usually has a check Icon:
<img width="262" alt="CleanShot 2022-02-20 at 19 26 47@2x" src="https://user-images.githubusercontent.com/30869823/154858021-c68bf24d-3003-41fd-99cf-8bd8e4c098cd.png">

The `MenuItemOption` has an `icon` prop, that allows us to dictate what we we might want to use in place of this `Check` Icon. Now I'm using this functionality, but I don't want any icon at all. I tried setting `icon` to `null`. But that doesn't help.

### Proposed Solution or API

By normal React convention, a null component is not displayed, so I feel we should not display the Check Icon when null is passed, If not, we can accept a prop perhaps on the `MenuOptionGroup` or the Item itself to disable this icon.

### Alternatives

My current approach is to pass `<></>` to the `icon` prop

**Comment by anubra266** [comment]
cc. @TimKolberger, @segunadebayo I don't mind working on this if we can decide on something.

**Comment by TimKolberger** [comment]
Explicitly passing null to disable the icon seems like a good idea 👍
🙌
