### ISSUE TITLE
cannot set "px " in createBreakpoints

### ISSUE THREAD

**Issue by itta611** [chakra-ui/chakra-ui#5645]
### Description

I want to set value with `px` in `createBreakpoints`, but the value is ignored.

### Link to Reproduction

https://codesandbox.io/s/blissful-water-ndgd0g?file=/src/index.js:0-347

### Steps to reproduce

1. Set value with `px` in `createBreakpoints`
2. Values with px set don't work.

---

<img width="255" alt="スクリーンショット 2022-02-22 17 30 52" src="https://user-images.githubusercontent.com/86896657/155106765-7f3e2b34-ffa6-4f8c-93a1-1f629614cc77.png">

### Chakra UI Version

1.7.2

### Browser

Google Chrome 95

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by smitgol** [comment]
can i pick up this issue ?

**Comment by smitgol** [comment]
You need to change code to this in your project `https://codesandbox.io/s/blissful-water-ndgd0g?file=/src/index.js:316-461`

```
import { extendTheme } from "@chakra-ui/react";

// your breakpoints variable below

const theme = extendTheme({ breakpoints });

 <ChakraProvider theme={theme}>
      <Box padding={4}>
        <Box height="40px" bg={{ md: "tomato", lg: "slategray" }} />
      </Box>
    </ChakraProvider>
```
Apply above changes breakpoint will work in px as well 
Thanks

**Comment by itta611** [comment]
Fixed. but still not working...

**Comment by m4x3d** [comment]
You need to wrap the breakpoints in an object. See this example:
https://codesandbox.io/s/adoring-engelbart-dspk42?file=/src/index.js

You can pass also other properties like colors, components and fonts on the same way. For more informations have a look on this page: https://chakra-ui.com/docs/theming/customize-theme

**Comment by TimKolberger** [comment]
Mixing px and em values will lead to some unexpected behavior, because we are sorting the breakpoints by their number value to support the style props Array syntax.

But you can provide all values in pixels to make it work:

```js
const breakpoints = createBreakpoints({
  base: "0px",
  sm: "200px",
  md: "300px",
  lg: "400px",
  xl: "500px",
  "2xl": "600px"
});
```
