### ISSUE TITLE
Select inside Popover: Popover closes if selection overflows popover size

### ISSUE THREAD

**Issue by schettn** [chakra-ui/chakra-ui#5658]
### Description

I would like to use `Select` inside of `Popover` where the select is higher than the popover, and this works well if the popover trigger is set to `click`. Although, if using `hover` as trigger the popover closes when the mouse is leaving the popover to select a option. (see the video below))

### Code to Reproduction

```typescript
<Popover trigger="hover">
  <PopoverTrigger>
    <Button>Trigger</Button>
  </PopoverTrigger>
  <PopoverContent>
    <PopoverArrow />
    <PopoverCloseButton />
    <PopoverHeader>Confirmation!</PopoverHeader>
    <PopoverBody>
      <Select>
        <option>1</option>
        <option>1</option>
        <option>1</option>
        <option>1</option>
      </Select>
    </PopoverBody>
  </PopoverContent>
</Popover>;
```

### Chakra UI Version

1.7.4

### Additional Information

https://user-images.githubusercontent.com/52858351/155725545-1e849b67-74f9-4706-a769-b90e51e2c7c5.mp4

**Comment by Brennvo** [comment]
Hey @schettn — could you specify which operating system and browser you captured this with?

**Comment by schettn** [comment]
> Hey @schettn — could you specify which operating system and browser you captured this with?

Firefox & Ubuntu, but same behavior occurs with Chromium & Windows 11

**Comment by webjay** [comment]
It also happens for me on a Mac 12.2.1 using Firefox 97.0.1.
It works using Safari.

**Comment by Brennvo** [comment]
I made two pens to try and isolate the issue. [One example is with vanilla JS](https://codepen.io/brennvo/pen/MWrmeqq) (let's call this pen 1) and [another example with React](https://codepen.io/brennvo/pen/bGaWwpK?editors=1111) (pen 2). The idea is that when you leave the dashed, gray container, you get a browser alert that you are leaving the container. This can quickly be demonstrated by placing your cursor inside the gray container and immediately removing it. Things get interesting, though, when you open the `<select>` element. When clicking the `<select>` element, here are the results I got:


When reading this table, preface each result with: **"When pressing the select element, the ..."**

|| Chrome | Firefox | 
|---|---|---|
| Vanilla JS | Alert does not appear | Alert does appear (unexpected) | 
| React | Alert does not appear | Alert does appear (unexpected) |

The [working solution](https://stackoverflow.com/a/19595383) seems to be adding a check for the `relatedTarget` inside of the `mouseLeave` event of the container.

However, while this working solution seems to work just fine with vanilla JS, React is still not working as expected. Without doing any further research, I suspect it has something to do with the event delegation in their code. I will get back to this...

----
To note, here are my OS and browser versions:
* OS: MacOS 11.6.2
* Chrome: 99.0.4844.84
* Firefox: 98.0.2
