### ISSUE TITLE
Editable: setting controlled value does not propagate into Editable's internal value

### ISSUE THREAD

**Issue by kk21** [chakra-ui/chakra-ui#5670]
### Description

Using React useState to control the value of Editable, calling setState does not seem to change the internal value of Editable.

### Link to Reproduction

https://codesandbox.io/s/naughty-glade-ufqr78?file=/pages/index.tsx

### Steps to reproduce

1. The name state is set to "John" in useEffect once initially
2. Click on the Editable text: "John"
3. You can change, or not to change the Editable text.
4. Press Escape key to abort.
5. Editable shows placeholder text and the name state becomes the default empty string specified in useState("")

### Chakra UI Version

1.8.6

### Browser

Google Chrome 99

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by TimKolberger** [comment]
Thank you for creating a reproduction! ✨ 

I updated the codesandbox with some logs to get more insight: https://codesandbox.io/s/chakra-ui-issue-5670-j0q3p5?file=/src/App.tsx 

Seems like the previous value inside Editable is only updated, if Editable itself initiates the update.
It is not updated if the valueProp is changing.

https://github.com/chakra-ui/chakra-ui/blob/577aeb92dbd6b1e309b973c1864601b936ef20bc/packages/editable/src/use-editable.ts#L107-L117

The linked PR did not introduce the issue, it was already present in 1.7.2.

I think it is missing an Effect similar to this:

```ts
React.useEffect(() => {
  setPreviousValue(valueProp)
}, [valueProp])

**Comment by TimKolberger** [comment]
I think a more straight forward solution would be to set `setPrevValue(valueProp)` in the `onEdit` callback, to use the most recent "previous" value in favor of the proposed effect.

**Comment by takethefake** [comment]
Hej @TimKolberger @kk21 

I also took a look at this and came to another approach which gives the user a little bit more control regarding the `prevValue`

I made `prevValue` a controllable prop that can be updated outside the scope of editable. this way you could update the prevValue in the `useEffect` as well. 

by registering to `onChangePrevValue` you would get updates if the internal state would be updated.

**Comment by takethefake** [comment]
When adjusting my PR I noticed one drawback to call `setPrevValue` in `onEdit` 

when `startWithEditView` is `true` `onEdit` isn't called, since it is only called `onFocus` on the preview component.

which leaves us with the same error

**Comment by takethefake** [comment]
@TimKolberger will now set the `prevValue` on the `onFocus`-Event on the `input` and `preview` component. Adjusted my PR accordingly.

**Comment by takethefake** [comment]
Added a test to verify the strategies are working
