### ISSUE TITLE
LinkOverlay breaks IconButton/Button within LinkBox

### ISSUE THREAD

**Issue by JClackett** [chakra-ui/chakra-ui#5673]
### Description

The latest release (1.8.6) introduced a new bug.

When using a LinkBox + LinkOverlay, any IconButton within the LinkBox becomes unresponsive.

### Link to Reproduction

https://codesandbox.io/s/bold-leaf-rhjbxj?file=/src/index.tsx

### Steps to reproduce

Hover over the + icon, you can see that there is no animation, and clicking it doesn't log anything to the console.

### Chakra UI Version

1.8.6

### Browser

Safari 

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Removing the LinkOverlay component seems to fix it, but obviously that makes the whole link box feature not very useful.

**Comment by m4x3d** [comment]
Hey @JClackett, thanks for reporting that!

I just recognized that this is a direct result of my PR https://github.com/chakra-ui/chakra-ui/pull/5632
Already found the problem. I will create a PR during the day.

A workaround until this is fixed is for example to pass e.g. `zIndex="2"` in the Button like in this example:
https://codesandbox.io/s/eager-sun-8jljqk
