### ISSUE TITLE
Formik Fields overflowing in Modal 

### ISSUE THREAD

**Issue by Bryan03122** [chakra-ui/chakra-ui#5677]
### Description

When I use some Formik Fields as Input or Textarea in a modal dialog with scrollBehaviour="inside", those fields and Modal Footer are overflowing.

### Link to Reproduction

https://codesandbox.io/s/busy-monad-5hyhjw?file=/src/index.js

### Steps to reproduce

Click the "Open" button.

### Chakra UI Version

1.8.6

### Browser

Google Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by TimKolberger** [comment]
If you remove the additional Box in the formik callback it looks good again: https://codesandbox.io/s/cold-moon-8e9zxe?file=/src/index.js

Hope this helps :)
