### ISSUE TITLE
Text inside checkbox label is not selectable

### ISSUE THREAD

**Issue by Pk-T** [chakra-ui/chakra-ui#5681]
### Description

I want users to be able to select text from checkbox label

### Link to Reproduction

https://codesandbox.io/s/youthful-sky-1nt85y

### Chakra UI Version

1.8.5

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by m4x3d** [comment]
Hey @Pk-T, thanks for opening that issue!

In my opinion this is not a bug because normally you want to have the click event on the text too. But here is a way you can achieve what you want to do:
https://codesandbox.io/s/reverent-cerf-47po0y

**Comment by nikolovlazar** [comment]
@Pk-T do you want to be able only to select the text, or also toggle the checkbox when the user clicks on the text? By web standards, the text of the checkbox should be clickable, but not necessarily selectable. You might have an edge-case here.

**Comment by Pk-T** [comment]
@nikolovlazar Is it a non standard to say text is clickable as well as selectable? I tried searching for it before posting here but couldn't find it. It would be great if you can point me to some resource.

**Comment by nikolovlazar** [comment]
@Pk-T here's an interesting article on designing Checkboxes: https://uxplanet.org/checkbox-and-toggle-in-forms-f0de6086ac41

![CleanShot 2022-03-03 at 15 22 57](https://user-images.githubusercontent.com/5396211/156583521-50069894-e5b9-4f87-8a96-ed74d7f258fa.png)

Clicking on the label is definitely a must. Therefore, making the text selectable, as well as clickable, is pretty challenging. If I wanted to just select the text, I'll actually activate the checkbox by mistake.

**Comment by Pk-T** [comment]
Yeah what you say certainly makes sense & I agree that clickable label is a must & trying to have both the features would increase the complexity for not a lot of value. I raised the bug because I saw we can do this on the native checkbox in chrome, it checks the  checkbox on mouse up only if nothing is selected. Anyway I will close this, thanks for the response. :)
