### ISSUE TITLE
Add noscript version for Popover component

### ISSUE THREAD

**Issue by f-laino** [chakra-ui/chakra-ui#5687]
### Description

Allow Popover component to work in no-script context (e.g. google bot) through css properties, so its content (like menu->sub menu) is available.

### Problem Statement/Justification

For accessibility and seo purposes

### Proposed Solution or API

```
<Popover
  style={{
    &:hover > .content: opacity: 1; visibility: visible; and so on...;
  }}
>
  <trigger>
    Hover me!
  </trigger>
  <content>
    Hidden content
  </content>
</Popover>
```

**Comment by segunadebayo** [comment]
Hi @f-laino,

Thanks for the suggestion. After thinking about this, I don't think we'll add this to Chakra UI for now, feel free to implement this in your codebase and post your solution here to help others who may have similar issues.

Thanks again.
