### ISSUE TITLE
gap property missing from flexbox

### ISSUE THREAD

**Issue by saltnpixels** [chakra-ui/chakra-ui#5689]
### Description

How can I add the gap property to a Flex item?

### Problem Statement/Justification

I'm a vanilla CSS guy... However I am on a project that seems to be using your library.
How can I add the gap property to my flexbox items?
I do not see a gap property for the flexbox component.

Is there an escape hatch so I can add real css to a component or something?

### Proposed Solution or API

Add gap property.

**Comment by josulliv101** [comment]
hi,
I was experimenting with this the other day. Not sure of your specifics but what I had tried functioned as expected. Below is a couple examples of what worked for me:
https://codesandbox.io/s/6z18f7?file=/src/index.tsx

**Comment by noobinthisgame** [comment]
Hi @saltnpixels,
the docs page for `Flex` describes the props that are specific to that component. If you want a full list of the style-props check out this [page](https://chakra-ui.com/docs/styled-system/features/style-props#flexbox) :)

**Comment by takethefake** [comment]
Closing this Issue, if there are further questions regarding the `gap`-property feel free to reach out.
