### ISSUE TITLE
[Progress] Bar does not render when theme shade color passed

### ISSUE THREAD

**Issue by martinpengellyphillips** [chakra-ui/chakra-ui#569]
**Describe the bug**
Passing a theme shade such as `blue.300` rather than just `blue`, causes the Progress bar to not render.

**Expected Behavior**
The bar should render when using any theme defined color.

**To Reproduce**
https://codesandbox.io/s/chakra-js-starter-bfngf

**Suggested solution(s)**
The logic is hardcoded to always add `.500` suffix to the passed color. It could instead check whether this is necessary.

(p.s. Really enjoying this library - thank you! 😄 )

**Comment by yuyokk** [comment]
I believe same happens with `Button`

![image](https://user-images.githubusercontent.com/1225343/82076673-7ea6fb00-96de-11ea-864f-6c739ec004eb.png)

I'm trying to define custom colors. Thought I could do `blueDark: '#1d274e'` but it seems that I need to define an object as a workaround instead `blueDark: { 500: '#1d274e' }`

**Comment by mbrookson** [comment]
I wish this was supported for all components. Why does this library only allow for setting the "main" shade? Would be fantastic if it was possible to pass in any shade to control the colour of a component!

**Comment by chrysb** [comment]
I'm going to upvote this, as the documentation says:

```
You can add color prop to any progressbar to apply any color that exists in the theme.
```

This component is not working as described.

**Comment by with-heart** [comment]
You'll be able to configure the colors however you like in 1.0. `Progress` and `Button` both take a `colorScheme` prop which refers to a base color (`blue`), but you can override this behavior with more specific colors in your theme.

See the component theming docs on the 1.0 pre-release site for more information on this topic: https://next.chakra-ui.com/docs/theming/overview
