### ISSUE TITLE
Defaults are bypassed when providing options to useToast

### ISSUE THREAD

**Issue by emilpaw** [chakra-ui/chakra-ui#5692]
### Description

When I provide options to useToast directly I expect that defaults are used for all omitted properties. They are not.

### Link to Reproduction

https://codesandbox.io/s/naughty-fast-pjuycq?file=/src/index.tsx

### Steps to reproduce

1. Press the buttons
2. The shown toast should look the same for all of them
3. The toast where options were directly passed to the useToast hook looks different because it does not use the toast defaults

### Chakra UI Version

1.8.6

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

After this is confirmed as a bug, I could work on it.

**Comment by takethefake** [comment]
Hej @emilpaw thank you very much for filing this issue!

I provided a PR that should fix this issue.
