### ISSUE TITLE
Cannot properly style addon on the input

### ISSUE THREAD

**Issue by standup75** [chakra-ui/chakra-ui#5693]
### Description

Given I specify a custom theme for Input's addon
When I display a component with an addon (InputLeftElement or InputRightElement)
Then I don't see the style being applied to my component's addon.

Given I specify a custom theme for Input's addon _focus property
And I display a component with an addon (InputLeftElement or InputRightElement)
When I focus on the input
Then I don't see the _focus style being applied to my component's addon.

### Link to Reproduction

https://codesandbox.io/s/cool-sky-obj7tb?file=/src/index.js

### Steps to reproduce

1. Go to 'https://codesandbox.io/s/cool-sky-obj7tb?file=/src/index.js'
2. The $ sign should be the same gray as the border but it's darker 
3. Focus on the input, the border changes color to green but not the $ sign

### Chakra UI Version

1.8.6

### Browser

Chrome 98

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by takethefake** [comment]
hej @standup75 thanks for reaching out!

i've checked `InputElement` and your csb and found out that you need `element` instead of `addon` to style the `InputElement`

unfortunately, this works in our storybook but not in csb. will keep you updated.

**Comment by standup75** [comment]
This is true for the color of the `InputLeftElement`, but it doesn't change on focus
