### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by simoncollins** [chakra-ui/chakra-ui#57]
Hi, thanks for a great project. I couldn't see a mention of the browser versions you're targetting. Obviously you need flexbox support but specifically I'm interested in whether you are looking to support IE11.

**Comment by segunadebayo** [comment]
Hi @simoncollins ,

It's not set in stone yet but here's an initial draft of browsers we're targetting with Chakra UI. Yes, we're looking to support IE 11.

```
ie 11
edge >= 14
firefox >= 52
chrome >= 49
safari >= 10
```

**Comment by simoncollins** [comment]
Fantastic, thanks @segunadebayo. I'm looking forward to trying out Chakra in a project
