### ISSUE TITLE
Input Left and RIght Elements are dispositioned when size is not medium

### ISSUE THREAD

**Issue by anubra266** [chakra-ui/chakra-ui#5703]
### Description
As long as the Input is not the default medium size, no matter how we changed the input, be it `size` prop or adding `padding` to the input, it dispositions the `InputGroup` elements.
![CleanShot 2022-03-08 at 22 20 08](https://user-images.githubusercontent.com/30869823/157326971-e5cd552d-a11b-4179-a18e-1564cfa9f15f.png)

I currently solve this with CSS transform, but it would be nice if we have this positioning by default.

![CleanShot 2022-03-08 at 22 22 19](https://user-images.githubusercontent.com/30869823/157327320-ef316035-9099-449b-82c6-8edc476422b7.png)

**Comment by TimKolberger** [comment]
Applying h="full" on the Elements does the job as well, because they have `position: absolute` by default. 

```jsx
<InputGroup>
    <InputLeftElement
      pointerEvents='none'
      color='gray.300'
      fontSize='1.2em'
      children='$'
      h="full"
    />
    <Input placeholder='Enter amount' py={20}/>
    <InputRightElement children={<CheckIcon color='green.500' />} h="full"/>
</InputGroup>
```

I think this would be a minimal invasive solution, but maybe this is a design decision to keep them at the top?
cc @segunadebayo

**Comment by segunadebayo** [comment]
Hi @anubra266,

You'll need to pass the `size` prop to the `InputGroup` component. That's the only way `InputLeftElement` and `InputRightElement` can get access to it.

**Comment by gbrocha** [comment]
Hello guys. The issue is occurring yet. The input padding doesn't adapts following the InputRightElement when the size is different of 'md'.

An example of code that the problem happens: 
``` jsx
<InputGroup
    cursor="pointer"
    size={{ base: 'md', lg: 'lg' }}
>
  <Input
    bg="white"
    readOnly
  />
  <InputRightElement h="full" w={10}>
    <CopyIcon />
  </InputRightElement>
</InputGroup>
```

**Comment by cengizhanhakan** [comment]
This is still broken. If the InputGroup size is lg everything is fine. But, if you use md as a size on InputGroup left and right element will be misaligned.
