### ISSUE TITLE
Setting the "gray" color in the theme object breaks `<Skeleton/>` animation

### ISSUE THREAD

**Issue by nathanhleung** [chakra-ui/chakra-ui#5709]
### Description

When I set the "gray" color in the theme object, I expected the `<Skeleton/>` component to continue working, but it stopped working

### Link to Reproduction

https://codesandbox.io/s/skeleton-animation-bug-with-gray-color-78zbvj?file=/src/App.js

### Steps to reproduce

1. Go to the CodeSandbox: https://codesandbox.io/s/skeleton-animation-bug-with-gray-color-78zbvj?file=/src/App.js
2. Scroll down to Line 14 and uncomment it
3. See that the `<Skeleton/>` animation disappears

### Chakra UI Version

1.8.5

### Browser

Google Chrome 99

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by nathanhleung** [comment]
It looks like this is occurring because the default Skeleton `baseStyle` function relies on the gray from Chakra's default color scheme: https://pastebin.com/G0JWEuQT

Right now my resolution is to avoid overriding default Chakra colors (I changed the name of the color to "mediumgray" and the Skeleton component started working again), but I wonder whether it's appropriate to also do something on the Chakra side to mitigate this, either updating the `<Skeleton/>` code to handle this case or updating the Theming docs to discourage users from overriding the default named colors.

**Comment by segunadebayo** [comment]
Hi @nathanhleung,

You're correct. My recommendation is to update the 50-900 colors for the gray object instead of changing it altogether.

or, like you did already, use a different name.
