### ISSUE TITLE
Skeleton component does not animate with the Theme-able Colors

### ISSUE THREAD

**Issue by davrosull** [chakra-ui/chakra-ui#5712]
### Description

When I set the `startColor` and `endColor` on the baseStyle for the Skeleton Component, the colors are not used on the Animation. Setting the colors via props works though. 

### Link to Reproduction

https://codesandbox.io/s/quirky-mcnulty-6h4x3f

### Steps to reproduce

1. Go to the Sandbox
2. Inspect the 3 Skeleton components and see that only when the `startColor` and `endColor` are set via props that the colors appear.

### Chakra UI Version

1.8.6

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I've logged out the `theme` and the Skeleton StyleConfig and all the props look like they are being set, however I noticed that the animation seems to not be created correctly. This is what it logs:

```
animation: "undefineds linear infinite alternate _EMO_animation-snm94m_@keyframes animation-snm94m{from{border-color:#EDF2F7;background:#EDF2F7;}to{bord…"
```

which I think means the fade or fadeDuration might not be being set correctly.

**Comment by segunadebayo** [comment]
Hi @davrosull,

`startColor` and `endColor` aren't valid CSS properties or style props in Chakra UI. They are custom props that should only be passed directly to the `Skeleton` component NOT in the theme. That's why it doesn't work.

Kindly pass it to the component as you've already done in the reproduction.

Cheers.

**Comment by davrosull** [comment]
Thanks @segunadebayo for the clarification!
