### ISSUE TITLE
csstype ColorAdjust is deprecated and causes error on build

### ISSUE THREAD

**Issue by honungsburk** [chakra-ui/chakra-ui#5714]
### Description

I expect to be able to compile my project using Vite. The project did not compile but instead I received the error message " Namespace '"/home/frank/git/chakra-ui-ColorAdjust-bug/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'."

### Link to Reproduction

https://github.com/honungsburk/chakra-ui-coloradjust-bug

### Steps to reproduce

1. Set up the repository I have linked
2. `npm install`
3. `npm run build`

should produce the errors:
```bash

node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:480:50 - error TS2694: Namespace '"/home/frank/git/chakra-ui-ColorAdjust-bug/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.

480         colorAdjust?: import("csstype").Property.ColorAdjust | undefined;
                                                     ~~~~~~~~~~~

node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:986:61 - error TS2694: Namespace '"/home/frank/git/chakra-ui-ColorAdjust-bug/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.

986         WebkitPrintColorAdjust?: import("csstype").Property.ColorAdjust | undefined;
                                                                ~~~~~~~~~~~
```

### Chakra UI Version

1.8.6

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Seems like if "ColorAdjust" is replaced with "PrintColorAdjust" everything compiles. I can update my node_modules/ manually until there is a real fix.

**Comment by DGVIP** [comment]
I created my project with Vite and after using `yarn build` I faced the same problem, but the error indicated where was the problem.

```bash
Found 2 errors in the same file, starting at: node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:480
```

So a temporary solution is to change the two errors on the file where `ColorAdjust` is referenced and replace it with `PrintColorAdjust`

```ts
colorAdjust?: import("csstype").Property.PrintColorAdjust | undefined;
```
```ts
WebkitPrintColorAdjust?: import("csstype").Property.PrintColorAdjust | undefined;
```

And when I ran the build command again it worked.

Still, I haven't tested how this affects the `menu` component.

**Comment by RichardMoralesLuis** [comment]
I have the same issue on macOs using the latest version and node 14.17.1 with npm and yarn

**Comment by rohidisdev** [comment]
I'm having this same issue. I am able to fix this bug manually in my local machine but what about Vercel?
 
```
node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts(480,50): error TS2694: Namespace '"/vercel/path0/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.
--
21:16:23.083 | node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts(986,61): error TS2694: Namespace '"/vercel/path0/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.
21:16:23.120 | error Command failed with exit code 2.
```

**Comment by RichardMoralesLuis** [comment]
On Vercel it works fine

**Comment by RichardMoralesLuis** [comment]
> I'm having this same issue. I am able to fix this bug manually in my local machine but what about Vercel?
> 
> ```
> node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts(480,50): error TS2694: Namespace '"/vercel/path0/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.
> --
> 21:16:23.083 | node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts(986,61): error TS2694: Namespace '"/vercel/path0/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.
> 21:16:23.120 | error Command failed with exit code 2.
> ```

On Vercel works fine

**Comment by rohidisdev** [comment]
> > I'm having this same issue. I am able to fix this bug manually in my local machine but what about Vercel?
> > ```
> > node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts(480,50): error TS2694: Namespace '"/vercel/path0/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.
> > --
> > 21:16:23.083 | node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts(986,61): error TS2694: Namespace '"/vercel/path0/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.
> > 21:16:23.120 | error Command failed with exit code 2.
> > ```
> 
> On Vercel works fine

But then why I'm having this issue 🤔. Which version are you using?

**Comment by Emmanx** [comment]
I am having

> ### Description
> I expect to be able to compile my project using Vite. The project did not compile but instead I received the error message " Namespace '"/home/frank/git/chakra-ui-ColorAdjust-bug/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'."
> 
> ### Link to Reproduction
> https://github.com/honungsburk/chakra-ui-coloradjust-bug
> 
> ### Steps to reproduce
> 1. Set up the repository I have linked
> 2. `npm install`
> 3. `npm run build`
> 
> should produce the errors:
> 
> ```shell
> node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:480:50 - error TS2694: Namespace '"/home/frank/git/chakra-ui-ColorAdjust-bug/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.
> 
> 480         colorAdjust?: import("csstype").Property.ColorAdjust | undefined;
>                                                      ~~~~~~~~~~~
> 
> node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:986:61 - error TS2694: Namespace '"/home/frank/git/chakra-ui-ColorAdjust-bug/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.
> 
> 986         WebkitPrintColorAdjust?: import("csstype").Property.ColorAdjust | undefined;
>                                                                 ~~~~~~~~~~~
> ```
> 
> ### Chakra UI Version
> 1.8.6
> 
> ### Browser
> _No response_
> 
> ### Operating System
> * [x]  macOS
> * [ ]  Windows
> * [ ]  Linux
> 
> ### Additional Information
> Seems like if "ColorAdjust" is replaced with "PrintColorAdjust" everything compiles. I can update my node_modules/ manually until there is a real fix.

I am having the same issue

**Comment by iffa** [comment]
```json
"resolutions": {
  "csstype": "3.0.10"
}
```

Adding this to package.json should act as a workaround to the issue for now.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by segunadebayo** [comment]
> ```json
> "resolutions": {
>   "csstype": "3.0.10"
> }
> ```

After much investigation, this seems to be the only way to resolve this for now. Kindly use the suggestion above.

**Comment by AaronL1011** [comment]
Hello! Im also facing this issue in a recent Vite project ive created
```
> tsc && vite build

node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:480:50 - error TS2694: Namespace '"/Users/aaron/personal_code/react-sessions/react-state-management-demo/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.

480         colorAdjust?: import("csstype").Property.ColorAdjust | undefined;
                                                     ~~~~~~~~~~~

node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:986:61 - error TS2694: Namespace '"/Users/aaron/personal_code/react-sessions/react-state-management-demo/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.

986         WebkitPrintColorAdjust?: import("csstype").Property.ColorAdjust | undefined;
                                                                ~~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:480
```

Ive attempted adding the resolution for `csstype` as suggested above but it had no affect on the issue for me.
Is there any more info available on this one? Cheers!

**Comment by AaronL1011** [comment]
Hello! Im also facing this issue in a recent Vite project ive created
```
> tsc && vite build

node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:480:50 - error TS2694: Namespace '"/<OMITTED>/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.

480         colorAdjust?: import("csstype").Property.ColorAdjust | undefined;
                                                     ~~~~~~~~~~~

node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:986:61 - error TS2694: Namespace '"/<OMITTED>/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.

986         WebkitPrintColorAdjust?: import("csstype").Property.ColorAdjust | undefined;
                                                                ~~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:480
```

Ive attempted adding the resolution for `csstype` as suggested above but it had no affect on the issue for me.
Is there any more info available on this one? Cheers!

**Comment by shadyaziza** [comment]
@AaronL1011 you need to do `yarn install` / `npm install`

**Comment by seancaleb** [comment]
> Hello! Im also facing this issue in a recent Vite project ive created
> 
> ```
> > tsc && vite build
> 
> node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:480:50 - error TS2694: Namespace '"/<OMITTED>/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.
> 
> 480         colorAdjust?: import("csstype").Property.ColorAdjust | undefined;
>                                                      ~~~~~~~~~~~
> 
> node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:986:61 - error TS2694: Namespace '"/<OMITTED>/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.
> 
> 986         WebkitPrintColorAdjust?: import("csstype").Property.ColorAdjust | undefined;
>                                                                 ~~~~~~~~~~~
> 
> 
> Found 2 errors in the same file, starting at: node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:480
> ```
> 
> Ive attempted adding the resolution for `csstype` as suggested above but it had no affect on the issue for me. Is there any more info available on this one? Cheers!

same issues

**Comment by serinuntius** [comment]
If the directory was configured using yarn's workspace, it was necessary to append to package.json in the root.

>"resolutions": {
  "csstype": "3.0.10"
}

```
└── packages
    ├── contracts
    └── frontend
package.json
```

**Comment by seancaleb** [comment]
> Hello! Im also facing this issue in a recent Vite project ive created
> 
> ```
> > tsc && vite build
> 
> node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:480:50 - error TS2694: Namespace '"/<OMITTED>/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.
> 
> 480         colorAdjust?: import("csstype").Property.ColorAdjust | undefined;
>                                                      ~~~~~~~~~~~
> 
> node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:986:61 - error TS2694: Namespace '"/<OMITTED>/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.
> 
> 986         WebkitPrintColorAdjust?: import("csstype").Property.ColorAdjust | undefined;
>                                                                 ~~~~~~~~~~~
> 
> 
> Found 2 errors in the same file, starting at: node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:480
> ```
> 
> Ive attempted adding the resolution for `csstype` as suggested above but it had no affect on the issue for me. Is there any more info available on this one? Cheers!

I checked the package.json of csstype under node_modules folder, and it's version is listed at 3.0.11. And yet it still shows this error. I'd appreciate if someone can help me about this issue, thanks!

**Comment by serinuntius** [comment]
@seancaleb It should be fixed at 3.0.10, not 3.0.11.

> > Hello! Im also facing this issue in a recent Vite project ive created
> > ```
> > > tsc && vite build
> > 
> > node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:480:50 - error TS2694: Namespace '"/<OMITTED>/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.
> > 
> > 480         colorAdjust?: import("csstype").Property.ColorAdjust | undefined;
> >                                                      ~~~~~~~~~~~
> > 
> > node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:986:61 - error TS2694: Namespace '"/<OMITTED>/node_modules/csstype/index".Property' has no exported member 'ColorAdjust'.
> > 
> > 986         WebkitPrintColorAdjust?: import("csstype").Property.ColorAdjust | undefined;
> >                                                                 ~~~~~~~~~~~
> > 
> > 
> > Found 2 errors in the same file, starting at: node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:480
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Ive attempted adding the resolution for `csstype` as suggested above but it had no affect on the issue for me. Is there any more info available on this one? Cheers!
> 
> I checked the package.json of csstype under node_modules folder, and it's version is listed at 3.0.11. And yet it still shows this error. I'd appreciate if someone can help me about this issue, thanks!

**Comment by jakeboone02** [comment]
@segunadebayo - the workaround with `"resolutions": { "csstype": "3.0.10" }` worked for me, so thanks for that (and thanks @iffa). Will a permanent fix be released in the future? If so, will this ticket be updated? Seems like this shouldn't be closed if the fix is only a temporary workaround.

Sorry if this is pestering, I'm just wondering when I can remove the `"resolutions"` property from my `package.json`.

**Comment by Daim-Nickel-Penny** [comment]
Despite adding 
```
"resolutions": {
  "csstype": "3.0.10"
}
```
to package.json and running `npm install`

The issue **still** persists. 

### My workaround was:-
Manually replacing **ColorAdjust** with **PrintColorAdjust** [at lines 480:50 & 986:61] in `node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts` did the job.

**Comment by jakeboone02** [comment]
Thanks for that suggestion, @Daim-Nickel-Penny. You can use [patch-package](https://www.npmjs.com/package/patch-package) to persist the change for your app/library, like I've done [here](https://github.com/react-querybuilder/react-querybuilder/commit/c23b619cd584baf9785155ad46c8f1b399f1cb35).

**Comment by carlomigueldy** [comment]
> Thanks for that suggestion, @Daim-Nickel-Penny. You can use [patch-package](https://www.npmjs.com/package/patch-package) to persist the change for your app/library, like I've done [here](https://github.com/react-querybuilder/react-querybuilder/commit/c23b619cd584baf9785155ad46c8f1b399f1cb35).

But then it breaks for rollup dynamic imports on my end

```
arn run v1.22.17
$ tsc && vite build
vite v2.8.6 building for production...
✓ 29 modules transformed.
[rollup-plugin-dynamic-import-variables] Unexpected token (25:19)
file: /home/carlomigueldy/dev/atlantis-world-core/admin-dashboard/src/views/whitelists/default.tsx:25:19
error during build:
SyntaxError: Unexpected token (25:19)
    at Parser.pp$4.raise (/home/carlomigueldy/dev/atlantis-world-core/admin-dashboard/node_modules/rollup/dist/shared/rollup.js:19636:13)
    at Parser.pp$9.unexpected (/home/carlomigueldy/dev/atlantis-world-core/admin-dashboard/node_modules/rollup/dist/shared/rollup.js:16932:8)
    at Parser.pp$9.expect (/home/carlomigueldy/dev/atlantis-world-core/admin-dashboard/node_modules/rollup/dist/shared/rollup.js:16926:26)
    at Parser.pp$5.parseExprList (/home/carlomigueldy/dev/atlantis-world-core/admin-dashboard/node_modules/rollup/dist/shared/rollup.js:19503:12)
    at Parser.pp$5.parseSubscript (/home/carlomigueldy/dev/atlantis-world-core/admin-dashboard/node_modules/rollup/dist/shared/rollup.js:18865:25)
    at Parser.pp$5.parseSubscripts (/home/carlomigueldy/dev/atlantis-world-core/admin-dashboard/node_modules/rollup/dist/shared/rollup.js:18822:24)
    at Parser.pp$5.parseExprSubscripts (/home/carlomigueldy/dev/atlantis-world-core/admin-dashboard/node_modules/rollup/dist/shared/rollup.js:18806:21)
    at Parser.pp$5.parseMaybeUnary (/home/carlomigueldy/dev/atlantis-world-core/admin-dashboard/node_modules/rollup/dist/shared/rollup.js:18769:17)
    at Parser.pp$5.parseExprOps (/home/carlomigueldy/dev/atlantis-world-core/admin-dashboard/node_modules/rollup/dist/shared/rollup.js:18696:19)
    at Parser.pp$5.parseMaybeConditional (/home/carlomigueldy/dev/atlantis-world-core/admin-dashboard/node_modules/rollup/dist/shared/rollup.js:18679:19)
error Command failed with exit code 1.
```

**Comment by slbls** [comment]
For those looking for a workaround using npm instead of Yarn, replace `resolutions` with `overrides` in `package.json` and rerun `npm install`.

```json
{
	"overrides": {
		"csstype": "3.0.10"
	}
}
```
