### ISSUE TITLE
Incompatible types when spreading values

### ISSUE THREAD

**Issue by veloware** [chakra-ui/chakra-ui#5717]
### Description

When spreading props into the likes of `Stack` component, it can create typescript errors for incompatible types

### Link to Reproduction

https://codesandbox.io/s/rough-http-41leby?file=/src/index.tsx

### Steps to reproduce

1. Provide props directly to Stack component creates no error - `<Stack {...{ direction: 'column' }}></Stack>` or `<Stack direction="column"></Stack>`
2. However if you create an object first and spread the values to the `Stack` component - 

```
const styles = {
   direction: 'column'
};

<Stack {...styles}></Stack>
```

3. Observe an error - 

```
Error:(39, 12) TS2322: Type '{ children: Element[]; direction: string; }' is not assignable to type 'StackProps'.
  Types of property 'direction' are incompatible.
    Type 'string' is not assignable to type 'StackDirection | undefined'.
```

creating a dummy type gets rid of the error but seems unnecessary  - 

```
type column = 'column';

const styles = {
   direction: 'column' as column
};

<Stack {...styles}></Stack>
```

### Chakra UI Version

1.8.3

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @veloware,

This isn't an issue with Chakra but a general Typescript issue. The `direction` prop has to be either `row | column` and it can't be assigned to a `string` since that's too generic.

The best you can do is to add a type to the `style` object.

```tsx
const styles: StackProps = {
  direction: "column"
}
```

Now you can assign it without issues.
