### ISSUE TITLE
[@chakra-ui/core] Circular dependencies

### ISSUE THREAD

**Issue by mseeley** [chakra-ui/chakra-ui#572]
**Describe the bug**

Rollup reports two circular dependencies while building:

```
(!) Circular dependencies
../../node_modules/@chakra-ui/core/dist/es/Menu/index.js -> ../../node_modules/@chakra-ui/core/dist/es/Menu/MenuOption.js -> ../../node_modules/@chakra-ui/core/dist/es/Menu/index.js
../../node_modules/@chakra-ui/core/dist/es/Tabs/index.js -> ../../node_modules/@chakra-ui/core/dist/es/Tabs/styles.js -> ../../node_modules/@chakra-ui/core/dist/es/Tabs/index.js
```

No user-facing bugs because of the wise bundler.

**Expected Behavior**
No cyclic deps please.

**To Reproduce**

1. Navigate to the directory shown below and run [`madge`](https://www.npmjs.com/package/madge)

```
MacBook-Pro:src (master) matthome$ pwd
/Users/matthome/Development/chakra-ui/packages/chakra-ui/src
MacBook-Pro:src (master) matthome$ madge -c **/*
Processed 236 files (1.7s) (48 warnings)

✖ Found 2 circular dependencies!

1) Menu/MenuOption.js > Menu/index.js
2) Tabs/index.js > Tabs/styles.js
```

**Suggested solution(s)**

Cycles are easy to add when moving fast. I'm certain you know how to deal with them.

**Desktop (please complete the following information):**
 - OS: n/a
 - Browser n/a
 - Version f407acf41efb2585bb8c444c9a5869b171257c12

**Additional context**
Thank you for sharing your work. :) I really enjoy the clean output markup of Chakra components. The accessibility and keyboard support was the winning combination when evaluating against other component libraries. Well... and maybe I have a soft spot for Naruto. ;)

**Comment by segunadebayo** [comment]
Thanks for catching this @mseeley.

We're resolved this in the `dev-ts` branch in preparation for the next release.
