### ISSUE TITLE
Alert colorScheme's defaultProps is not taken into consideration

### ISSUE THREAD

**Issue by galliotl** [chakra-ui/chakra-ui#5721]
### Description

Hello,

I wanted to create an alert that has a grey colorScheme by default. But when I try to override Alert's theme I came across a different behavior than I expected.

### Problem Statement/Justification

My need is that:

```
<Alert>
...
```
Would render a grey alert. So I went ahead and override Alert's theme with:

```
const defaultProps = {
  variant: "solid",
  colorScheme: "gray", // gray is a valid colorScheme
};
```

In this case, the solid defaultProps is taken into consideration, but the colorScheme is not.
Unfortunately, the underlying code seems to set the colorScheme to "blue" (via STATUS.info) when we don't explicitly set a colorScheme props.

### Proposed Solution or API

I expect 

```
const defaultProps = {
  variant: "solid",
  colorScheme: "gray", // gray is a valid colorScheme
};
```

To allow to use Alert without specifying the colorScheme props each time in inline props

### Additional Information

Thanks for the great work with Chakra-ui :D

**Comment by TylerAPfledderer** [comment]
Hey @galliotl!

Would [withDefaultColorScheme](https://chakra-ui.com/docs/styled-system/theming/customize-theme#theme-extension-withdefaultcolorscheme) not serve your purpose?

**Comment by TylerAPfledderer** [comment]
Hey @galliotl!

So I was able to dig into this. 

Firstly, keep in mind that `withDefaultColorScheme`  is [passed as an argument to `extendTheme`](https://chakra-ui.com/docs/styled-system/theming/customize-theme#using-theme-extensions) and not within an array or object.

```js
const theme = extendTheme(
  {
    colors: {
      brand: baseTheme.colors.red,
    },
  },
  withDefaultColorScheme({ colorScheme: 'brand', components: ["Button"] }),
)
```

Testing the above with a button component will work.

However, I noticed that this problem might be specific to `Alert`, maybe in how it tries to [retrieve `bg` colors](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/alert.ts#L30-L35) from the `colorScheme` prop, different from the [`Button` styles](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/button.ts#L89-L127).

Maybe @segunadebayo can provide insight into this? I'm also not able to get `withDefaultColorScheme` to update the `Alert` component color, but it works fine for me with other components that accept the `colorScheme` prop by default.

**Comment by praveenpuglia** [comment]
Encountering the same issue. 
```
withDefaultColorScheme({
    colorScheme: 'red',
    components: ['Alert'],
  }),
  ```
Something like this definitely works for checkbox or buttons etc but for for alert, i still get the default blue.
