### ISSUE TITLE
getInputProps is not returning "checked" property

### ISSUE THREAD

**Issue by matefgo** [chakra-ui/chakra-ui#5722]
### Description

When I use `getInputProps` I expect to have access to the property `checked`, which is only possible via casting.

### Link to Reproduction

https://codesandbox.io/s/lucid-fire-dv2s9y?file=/src/CustomRadioCard.tsx

### Steps to reproduce

1. After setting up the whole custom radio group, destruct the `useRadio` to access the `getInputProps`.
2. Call the `getInputProps` and set the return to a constant, like `input`.
3. If you try to access the `checked` property, you'll get an error.

I used casting as a workaround, but I think this should not bet necessary, as the `PropGetter` should return the `HTMLInput` properties.
![image](https://user-images.githubusercontent.com/57035325/157893959-908bf1a0-4602-453a-b4d4-a7906e7f4ff2.png)

### Chakra UI Version

1.6.7

### Browser

Google CHrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information
This is my very first issue, so sorry if I've made a mistake. My english is not that perfect too, I've tried my best.

_No response_

**Comment by TylerAPfledderer** [comment]
Hey @matefgo!

What purpose are you needing to know if a radio is checked?

**Comment by matefgo** [comment]
> Hey @matefgo!
> 
> What purpose are you needing to know if a radio is checked?

Hey Tyler, what's up? 

This custom radio buttom will activate a collapse when checked. 

I thought about writing other structures to accomplish what I want, but I really want to know why the `checked` property can't be accessed.

**Comment by TylerAPfledderer** [comment]
@matefgo this is due to the typing on `getInputProps`, which looks to be constrained to rely on `getRadioProps` from `useRadioGroup` when making [custom radios](https://chakra-ui.com/docs/components/form/radio#custom-radio-buttons). The `getRadioProps` runs an onChange event for a group of radios to supply the value for `checked` when selecting an unchecked radio in a custom group. 

Based on the docs, these hooks were only intended for a group of custom radios.

In the meantime, probably the simplest workaround is controlled state with `useState`.

Something like:
```jsx
const [ isRadioChecked, setIsRadioChecked ] = useState( false );

return (
  <Box>
    <Box padding={ 2 }>
      <Radio
        isChecked={ isRadioChecked }
        onChange={ () => setIsRadioChecked( !isRadioChecked ) }
      >
        Radio #1
      </Radio>
    </Box>
    <Collapse in={ isRadioOneChecked }>
      <Center padding={ 6 } bg="blue" color="white">
        This is collapsed text for Radio #1
      </Center>
    </Collapse>
  </Box>
)
```

I could not discover another solution that did not complicate the issue unless you need a little more control.

**Comment by TylerAPfledderer** [comment]
@matefgo also, check out this pull request in the Chakra docs that will add [Documentation for `useRadio` and `useRadio` hooks](https://github.com/chakra-ui/chakra-ui-docs/pull/413)!

**Comment by matefgo** [comment]
> @matefgo this is due to the typing on `getInputProps`, which looks to be constrained to rely on `getRadioProps` from `useRadioGroup` when making [custom radios](https://chakra-ui.com/docs/components/form/radio#custom-radio-buttons). The `getRadioProps` runs an onChange event for a group of radios to supply the value for `checked` when selecting an unchecked radio in a custom group.
> 
> Based on the docs, these hooks were only intended for a group of custom radios.
> 
> In the meantime, probably the simplest workaround is controlled state with `useState`.
> 
> Something like:
> 
> ```js
> const [ isRadioChecked, setIsRadioChecked ] = useState( false );
> 
> return (
>   <Box>
>     <Box padding={ 2 }>
>       <Radio
>         isChecked={ isRadioChecked }
>         onChange={ () => setIsRadioChecked( !isRadioChecked ) }
>       >
>         Radio #1
>       </Radio>
>     </Box>
>     <Collapse in={ isRadioOneChecked }>
>       <Center padding={ 6 } bg="blue" color="white">
>         This is collapsed text for Radio #1
>       </Center>
>     </Collapse>
>   </Box>
> )
> ```
> 
> I could not discover another solution that did not complicate the issue unless you need a little more control.

Hey Tyler! First, thanks for all the effort to explain me this.
I think I wasn't clear enough, but I'm using those hooks for a custom radio button. The print from the code, on the very first post, is just a fragment of the custom `RadioCard` that I've written.

I'll be back later with a solution, as I'm refactoring the whole code. For now, the casting is sufficient to solve this issue.

But, for now, I'll leave the issue open. Because the type which is returned by the `getInputProps` it's indeed `Omit<HTMLProps<HTMLInputElement>, never>`.
![image](https://user-images.githubusercontent.com/57035325/158627170-c2288c54-32ad-4540-b318-dca5d53d1126.png).

And the `HTMLInputElement` has the `checked` property available.
![image](https://user-images.githubusercontent.com/57035325/158627445-711066c2-1002-4dc9-9283-35a5d8080310.png)

So I just can't understand why the `getInputProps` doesn't have the `checked` property available yet.

Again, thanks for that!
