### ISSUE TITLE
Checkbox is does does not observe state changes

### ISSUE THREAD

**Issue by HadiSDev** [chakra-ui/chakra-ui#5725]
### Description

When I use React hook form, and assign a default value to the checkbox, the checkbox never registers it. It works fine with vanilla checkbox

### Link to Reproduction

https://codesandbox.io/s/sad-lichterman-pqdno9?file=/pages/index.tsx

### Steps to reproduce

1. Go to index.tsx
2. See that I have set the defaultValues with { can_be_roomate: true }
3. See that the Checkbox is never set 

### Chakra UI Version

1.8.6

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by TylerAPfledderer** [comment]
Hey @HadiSDev! 😁

Based on the sandbox you provided, I noticed a typo.

When passing the `defaultValues` property to `useForm`, you provided the field name as `can_be_roomate`.

But when registering the name in the checkbox, it's `can_be_roommate`.

It works as expected when fixing this discrepancy.

**Comment by HadiSDev** [comment]
@TylerAPfledderer Sorry I about that, that was a spelling mistake from my side :D  However, locally the error still occurs but I was not able to recreate it on a sandbox. Weird thing is if I switch out the component with vanilla checkbox, then everything works fine.

**Comment by TylerAPfledderer** [comment]
Strange! Unless you have a setup that requires the use of `Controller` to render the component. That would only make sense though if you have a group wrapped in the `CheckboxGroup` component. 🤔

In case you haven't seen this before, one of the maintainer of React-Hook-Form supplied a CodeSandbox with all basic use cases with the Chakra components!
https://codesandbox.io/s/chakra-ui-5mp8g?file=/src/App.js

**Comment by HadiSDev** [comment]
No Group. Just a single Checkbox. switching it out with <input type="checkbox" {...}/> works fine

**Comment by vdmgolub** [comment]
In case someone encounters the same issue, here's how I've solved this. The solution was to set `isChecked={value}`:
```js
<FormControl>
  <FormLabel htmlFor="toggle-switch">
    Toggle?
  </FormLabel>
  <Controller
    name="toggle"
    control={control}
    render={({ field: { onChange, value, ...rest } }) => (
      <Switch
        id="toggle-switch"
        isChecked={value}
        onChange={(e) => onChange(e.target.checked)}
        {...rest}
      />
    )}
  />
</FormControl>

```

**Comment by ramiware** [comment]
isChecked={value} works. This should be in the official docs.
Just spent an hour on this. That's 59 minutes more than I should have.

Glad I came across your solution @vdmgolub Thank you
