### ISSUE TITLE
[ColorModeProvider] Does not re-render when value prop changes

### ISSUE THREAD

**Issue by mattjennings** [chakra-ui/chakra-ui#573]
**Describe the bug**
If you choose to manually provide the color mode value to ColorModeProvider, it does not re-render when the `value` prop changes

**Expected Behavior**
It should rerender child components with the new color mode

**To Reproduce**
https://codesandbox.io/s/chakra-ui-color-mode-bug-xfzv9

A temporary workaround is to also add a `key` prop of the color mode value, but this unmounts all children when it changes, so it's not ideal.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 81

**Comment by bear-in-a-box** [comment]
I'd like to add that this bug makes integration with Electron's `nativeTheme.shouldUseDarkColors` impossible.

**Comment by mattjennings** [comment]
I've found a better workaround is to make my own ColorModeProvider with the exported ColorModeContext. You'll have to handle dark mode detection yourself, though. In my case, I used `gatsby-plugin-dark-mode`:

```js
// ColorModeProvider.js

import React from 'react'
import { ThemeToggler } from 'gatsby-plugin-dark-mode'
import { ColorModeContext } from '@chakra-ui/core/dist/ColorModeProvider'

export default function ColorModeProvider({ children }) {
  return (
    <ThemeToggler>
      {({ theme, toggleTheme }) => {
        const colorMode = theme || 'light'
        const toggleColorMode = () =>
          toggleTheme(colorMode === 'dark' ? 'light' : 'dark')

        return (
          <ColorModeContext.Provider
            value={{
              colorMode,
              toggleColorMode,
            }}
          >
            {children}
          </ColorModeContext.Provider>
        )
      }}
    </ThemeToggler>
  )
}
```

**Comment by segunadebayo** [comment]
Hi @mattjennings,

I just had a look at this and I think the setup wasn't correct.

Ideally, you shouldn't have to use your own `useState` to control the toggling between light and dark mode. `ColorModeProvider` and `useColorMode` doesn't that for you.

Consider the `value` prop passed to ColorModeProvider as the "initial state". Then we provide a useColorMode hook to help you toggle those values.

Here's the correct setup: https://codesandbox.io/s/chakra-ui-color-mode-bug-xn4j3?file=/src/App.js

We'll try to make this clearer in docs.

**Comment by segunadebayo** [comment]
Let me know if you need any further help and I'll reopen this.

We'll also consider syncing the `value` prop of ColorModeProvider with `state` so this usage works. Thinking about @bear-in-a-box comment on electron.

**Comment by mattjennings** [comment]
I see, I would still expect the `value` prop to change the state value, though. Syncing that value to the state would be the best solution.

The reason I was providing the value myself was to workaround issues #305, #349, and #511. It worked properly when I did either the `key` prop or custom `ColorModeProvider` workaround. I do wonder if those issues may be symptoms of this issue.
