### ISSUE TITLE
[Popover][V1] Popover trigger render on scroll

### ISSUE THREAD

**Issue by the21st** [chakra-ui/chakra-ui#5734]
_Originally posted by @patresk in https://github.com/chakra-ui/chakra-ui/issues/2091#issuecomment-998787415_ :

Unfortunately, I don't think this was fixed, we are experiencing the same issue in `chakra-ui/react@1.6.6`. We temporarily hotfixed it with

```
eventListeners={{
  scroll: false,
}}
```

to every Popover. This degrades the UX a little bit, but the performance benefit is large.

**Comment by Brennvo** [comment]
Hey @the21st — I tried recreating the issue, similar to the one #2091, by creating [this CodeSandbox](https://codesandbox.io/s/popover-rendering-fifbgr) and opening it in [it's own isolated window](https://fifbgr.csb.app/). When I use the React component profiler and enable the "Highlight updates when components render." checkbox, I don't see any component rerenders.

Could you verify your usage of `Popover`?
