### ISSUE TITLE
Modal is getting hidden on submit of a form in it

### ISSUE THREAD

**Issue by oyatek** [chakra-ui/chakra-ui#5738]
### Description

When I submit a form in Modal,  the form updates currentUser, which in turn triggers cache update of the user data in a parent container and it triggers component redraw. The model gets hidden EVEN THOUGH the `isOpen` state variable is still `true`. 

### Link to Reproduction

https://codesandbox.com

### Steps to reproduce

1. Create a component that has an object loaded with `useQuery`
2. Create a modal as a child component with a form that updates the same object
3. Submit the form
4. The modal is getting hidden (`isOpen` is still true) and the page is not scrollable

### Chakra UI Version

1.7.3

### Browser

Chrome 96

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

I'm using Blitz.js with Chakra UI and I need to update an object in a modal, the same object that is already loaded in a parent container with `useQuery` that caches the data.

I tried to examine the page elements to see what's going on. 

`isOpen` is still true when the model is hidden but the model element gets removed from the DOM tree. The page becomes unresponsive, not clickable, not scrollable. It looks like it's still covered with overlay. But there's no modal DOM element. It gets unmounted and not remounted back.

**Comment by oyatek** [comment]
maybe worth mentioning that I'm using `isOpen` without `useDisclosure`, just as a state:
```
  const [payoutFormIsOpen, setPayoutFormIsOpen] = useState(false)
```

**Comment by allenhartwig** [comment]
I seem to be experiencing a similar issue on Chrome Version 99.0.4844.74 on Mac OS, however, its when a radio value is changed vs a form submit. The issue also seems to be limited to the Modal having `scrollBehavior="inside"` and the contents having been scrolled.

**Comment by segunadebayo** [comment]
Hi @oyatek,

Kindly provide a reproduction and I'll re-open this issue.

**Comment by oyatek** [comment]
I have found the source of the problem.

Inside of the modal I was fetching data from the server via `useQuery(...)` without using `<Suspense ..>`.

After adding it everything started working correctly:
```
      <Modal ...>
        <Suspense ...>
          <PayoutDetails (fetching data in this component) />
        </Suspense>
      </Modal>
```
