### ISSUE TITLE
Request to add option to easily disable Tab boxShadow on focus

### ISSUE THREAD

**Issue by cyberwombat** [chakra-ui/chakra-ui#574]
**Problem description**
I personally dont like the blue shadow/outline on the tabs - for one its blue no matter what color my tabs are and if its an accessibility thing its not being carried over to links and buttons (which I personally would not want). To turn it off involves adding `_focus={{ boxShadow: 'none' }}` to all `Tab` elements which is a bit of a pain - or building a component on top which takes away from default ease of use.
<img width="109" alt="Screen Shot 2020-04-05 at 7 59 09 PM" src="https://user-images.githubusercontent.com/777498/78519356-f1d05f80-7777-11ea-87e5-504568f9f442.png">

**Proposed solution**
Preferred choice is no shadow - but thats just me :).  Else can we explore having an option on the main `Tabs` component to not have shadows - something like `outline={true|false}` type of thing?

**Comment by segunadebayo** [comment]
Hi @cyberwombat,

You might be interested in this post that explains how to achieve that:
https://medium.com/@keeganfamouss/accessibility-on-demand-with-chakra-ui-and-focus-visible-19413b1bc6f9

Let me know if you find it useful.

**Comment by PSalaun** [comment]
It was to me at least, thank you!

**Comment by cyberwombat** [comment]
So this does not work on the Textarea one as that uses the outline property. Is there the intention to shift this to using box-shadow like the rest of the components?

**Comment by cyberwombat** [comment]
While this seems to partially work the `Textarea` component uses a `border-color` property which I have so far not been able to undo without affecting the normal state.
