### ISSUE TITLE
Conflicting zIndex of InputRightElement and MenuList

### ISSUE THREAD

**Issue by m4x3d** [chakra-ui/chakra-ui#5742]
### Description

When I have an Input with an InputRightElement it overlaps with the MenuList of a Menu because of the constellation of zIndex in both components.

### Link to Reproduction

https://codesandbox.io/s/objective-almeida-i2rcvl

### Steps to reproduce

1. Go to the CodeSandbox
2. Click on the buttons to see the bug and possible solutions

### Chakra UI Version

1.8.6

### Browser

Firefox 98.0 and Chromium 99.0.4844.51

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Use case for this is in my case a search bar with a lens icon in the top right corner of the page, directly under the mobile header.

I figured out that the change of the zIndex of InputLeftElement and InputRightElement was increased from 1 to 2 because of [issue 1900](https://github.com/chakra-ui/chakra-ui/issues/1900). I can not reproduce this bug when setting it to 1 again, so I guess something else has changed in the code that it is not required anymore.

In the codesandbox are 3 solutions from me how we can fix this:
1. set a high zIndex for MenuList in the theme, fits probably the best [between banner and overlay](https://chakra-ui.com/docs/styled-system/theming/theme#z-index-values) at ~1250 -> this should be a breaking change but in my opinion the way to go
2. set zIndex of the InputElements to 1 again and set the zIndex of MenuList to 2 OR wrap the MenuList in a Portal (to keep it on top if both have a zIndex of 1)
3. set zIndex of MenuList to 3 -> probably the worst solution

Feel free to assign me when we found out which solution is the best :smiley:

**Comment by ovirta** [comment]
Ugly hack to workaround the zindex issue where in our case Clear X icon was floating over another element.
![image](https://user-images.githubusercontent.com/4389140/173000461-e99456ec-e066-460d-8b5d-8ede31f3a6fa.png)

```
const [zIndex, setZIndex] = useState(0)
:
  <InputGroup>
    <Input
      :
        onFocus={() => setZIndex(2)}
        onBlur={() => setZIndex(0)}
    />
      <InputRightElement zIndex={zIndex}>
```

**Comment by sohrab-** [comment]
I wish someone would reopen this. This isn't happening only with `InputRightElement` and `MenuList`. Here is an example of a `Popover` and an `IconButton` that refused to stay behind it.

![image](https://user-images.githubusercontent.com/4444588/183579193-af2fd2b0-c4aa-4934-8aea-8408e17b6aac.png)

**Comment by dornach-mateusz-szumilo** [comment]
Just encountered this problem, adding `zIndex='5'` to an element I want at the top fixed this

**Comment by bertho-zero** [comment]
This issue should be reopened.
