### ISSUE TITLE
[website]Branch. dev-ts  Unable to build example

### ISSUE THREAD

**Issue by ukris** [chakra-ui/chakra-ui#575]
**Describe the bug**
I am unable to build the example in dev-ts branch

**Expected Behavior**
Error occurred prerendering page "/404". Read more: https://err.sh/next.js/prerender-error:
Error: Minified React error #130

**To Reproduce**
after. building packages
1. Go to example directory
2. yarn && yarn build

**Comment by segunadebayo** [comment]
Hey @ukris,

At the moment, only the `next-js` example is usable. We'll try to ensure all examples are working once we're done.

By the way, you don't run `yarn && yarn build` directly in the `examples` directory, you need to go into the `examples/next-js` first.

**Comment by ukris** [comment]
oh I am sorry - I mean the website directory
