### ISSUE TITLE
Add disable reason for buttons

### ISSUE THREAD

**Issue by villesau** [chakra-ui/chakra-ui#5753]
### Description

Buttons can be disabled, but you cannot attach reason for it which is either confusing from the users perspective or tedious to implement from the developers perspective.

Disable reason should be some sort of popover when hovering over the button or tapping it on mobile.

### Problem Statement/Justification

It is important to inform why the button is disabled. Not only once or twice I've seen buttons that are disabled, but there is no reason for it

### Proposed Solution or API

`<Button disabled disableReason="You have already performed the action" >submit</Button>`

### Alternatives

You can always add some UI for this or implement the popover from scratch, but this is tedious.

**Comment by marcosmarp** [comment]
Why don't you use a `<Tooltip>` and that's it?

```
<Tooltip label={disabledReason}>
  <Button disabled>Submit</Button>
</Tooltip>
```

**Comment by villesau** [comment]
I am, but now you have to understand and manage two components instead of one, and also manage when to show the tooltip etc. All this could be in a button and handled automatically, in similar way like the cursor is handled now.

**Comment by segunadebayo** [comment]
Hi @villesau,

I totally see your point here. I recommend adding a tooltip as @marcosmarp suggested. I'd rather not complicate the button component with more dependencies to solve this specific problem.

Thanks for understanding.

**Comment by blentz100** [comment]
@villesau Thanks for raising this issue and as I'm having the same challenge. 
@segunadebayo Thanks for the library and in the input. I will go the tooltip route.

**Comment by Danztee** [comment]
Hi, disabled prop isn't working for the button

**Comment by ocean90** [comment]
@Danztee Looks like you have to use `isDisabled` now https://github.com/chakra-ui/chakra-ui/commit/0f376650efce9eb2d2cba3484ffe4e3a73364504

**Comment by codingcaffeine** [comment]
just updated chakra and now disabled={boolean-reason} has been replaced with isDisabled; why this is not in the documentation props or variant?

**Comment by MrVa55** [comment]
> Why don't you use a `<Tooltip>` and that's it?
> 
> ```
> <Tooltip label={disabledReason}>
>   <Button disabled>Submit</Button>
> </Tooltip>
> ```

I have similar issue and tried this, but I don't think disabled elements can show tooltips in Chakra UI like suggested. Instead it still shows the prohibition/circle-backslash icon...

**Comment by clinton-mwachia** [comment]
Kindly add the isDisabled to the documentation.
