### ISSUE TITLE
Optional prop for disabling/shutting down a tooltip when scrolling

### ISSUE THREAD

**Issue by marcosmarp** [chakra-ui/chakra-ui#5755]
### Description

If an user has the mouse over a tooltiped element, and then starts scrolling, the tooltip scrolls through the page (see the video)

https://user-images.githubusercontent.com/88422056/159212705-7af7cda0-6fd6-476f-bb49-b5c22e1aa5e2.mp4

### Problem Statement/Justification

It would save some time on the developer side and help us avoid bigger edge cases like when the tooltip scrolling causes an overflow on the screen (see the video)

https://user-images.githubusercontent.com/88422056/159213399-22765349-622b-491d-b692-d851971a8ff5.mp4

### Proposed Solution or API

`<Tooltip label={yourLabel} hideOnScroll={true}>`

### Alternatives

I could manually check scrolling and then using the `isDisabled` prop to hide the tooltip

### Additional Information

I opened this as a feature request instead of a bug cause I'm pretty sure this is on the browser side and how it handles mouseover state changes

**Comment by marcosmarp** [comment]
not stale

**Comment by Sh1d0w** [comment]
I think this is a pretty major issue and definitely is a bug, being either in the library or the browser.

**Comment by Sh1d0w** [comment]
Not stale, big bug actually!

**Comment by damingerdai** [comment]
how to fix the issues...
