### ISSUE TITLE
[Button] Does not handle long text

### ISSUE THREAD

**Issue by soumikcv** [chakra-ui/chakra-ui#576]
The button breaks when the text overflows. Could happen a lot in smaller devices.

![image](https://user-images.githubusercontent.com/18064965/78544446-c8ffa700-7817-11ea-8582-8e3df783da15.png)

The text should fold with the increase in button height to wrap it around. Adding wordBreak styles did not help either in my case.

 - OS: MacOS
 - Browser: Chrome

I apologise if I'm missing an obvious solution to fix this on my side.

**Comment by soumikcv** [comment]
I've reached a solution to this. Adding whiteSpace along with wordBreak seems to do the trick. After that I handle the height by myself.

```
            <Button
              mr={2}
              mb={2}
              height={[`${text.length > 30 ? "60px" : "40px"}`, "40px"]}
              style={{
                whiteSpace: "normal",
                wordWrap: "break-word",
              }}
            >
              {option}
            </Button>
```

**Comment by bogdansoare** [comment]
Having the height hard coded limits the usage of the button, maybe it will be better to use padding instead of a fixed height, what do you think @segunadebayo ?

**Comment by segunadebayo** [comment]
@bogdansoare, that's a good idea actually. I'll consider using padding for the next release.

**Comment by mistsy** [comment]
@bogdansoare Hi! How's it going with button heights? It would be a much more flexible approach to eliminate the hard-coded heights for buttons, so they can be customized via theme component override aswell as inline. Now i actually am not able to even set the height to auto in "baseStyle" nor any other props, it's only possible inline which is not a very scale-friendly apporach :/ Looking forward to this update. Good work, keep it up!

**Comment by VaZark** [comment]
Can this reopened? I'm observing the same error 2 yrs later. 

![image](https://user-images.githubusercontent.com/11616688/194563825-3c956cc6-345d-49b9-90f4-c1f10012d819.png)

It'd make sense that hardcoding the height would be an opt-in option rather than the default.

**Comment by VictorComette** [comment]
Another solution using ellipsis:
```
<Button>
  <Text isTruncated>My very long button text that now is truncated with ellipsis</Text>
</Button>
```

**Comment by Sid-Turner-Ellis** [comment]
I use this as the base style for the button component to get around this:

```
  Button: {
    baseStyle: {
      borderRadius: 'md',
      shadow: 'md',
      whiteSpace: 'normal',
      wordBreak: 'break-word',
      textAlign: 'left',
      fontSize: ['2xl', null, 'xl'],
      height: 'unset',
      py: '3',
      px: '6',
      
    }
}
```

**Comment by ELHart05** [comment]
> ```js
> whiteSpace="normal" height="auto" blockSize="auto"
> ```

yep that worke thanks!!
