### ISSUE TITLE
Theme default props per variant

### ISSUE THREAD

**Issue by omerman** [chakra-ui/chakra-ui#5768]
### Description

At the moment we can only pass styling props as part of the theme object. I think most of Chakra's users would like to be able to tell a component to render with default props per variant, or even by default.. Without the need to compose the component and use the composed custom component we create. 

### Problem Statement/Justification

- Every other big react ui library has it. I know it doesnt mean we should add it, but it does mean it is a feature that is largely in use by the React dev community.

- Less components is a huge win for mid / big projects, 
This kind of addition will accomplish that because a lot of the times you just want to map between a variant and its default props, a sort of a guideline. 

- (non style related) props often do effect the component style behaviors, it is the ui we are talking about after all.. So it's clearly related to the theme. I don't see any cons for adding this sort of support to the theme.

### Proposed Solution or API

A straightforward approach, add the ability to define default component props to the theme as well. 

### Alternatives

Alternatively, add another place for mapping variants to default props, if it feels that the theme is not the right place.

**Comment by segunadebayo** [comment]
Hi @omerman,

Your proposal is unclear to me. Perhaps showing me a sample API would help me understand better.

Thanks

**Comment by omerman** [comment]
```
const theme: Partial<ChakraTheme> = {
   components: {
     Alert: {
       defaultProps: {
           status: "warning" // This is impossible at the moment. we can only use css props. Why? Other UI Libraries support using actual component props as part of the default behavior set on the theme.
       }
     }
   }
}

// Make it possible to have default props per variant
const theme: Partial<ChakraTheme> = {
   components: {
     Alert: {
        defaultProps: {...} // Default props for the component. Just like we have today.
        variants: {
             variant1: {
                 defaultProps: {...} // Default props that will be applied for variant1
             },
             variant2: {
                 defaultProps: {...} // Default props that will be applied for variant2
             }
        }
     }
   }
}
```

**Comment by segunadebayo** [comment]
Hi @omerman,

After giving it some thought, we won't be going in that direction. It increases the API complexity and I think this can be handled in the user-land code.

Thanks for understanding.

**Comment by xeinebiu** [comment]
> Hi @omerman,
> 
> After giving it some thought, we won't be going in that direction. It increases the API complexity and I think this can be handled in the user-land code.
> 
> Thanks for understanding.

Can you elaborate little bit, how does this one increase the complexity? I think if Chakra provides this functionality, the flexibility is increased and customization can completely rely on chakra theming instead of wrapping components.
