### ISSUE TITLE
[TextArea] Can't set rows/cols on a textarea

### ISSUE THREAD

**Issue by Rixcy** [chakra-ui/chakra-ui#577]
Looks like the textarea is using input types so doesn't accept cols, rows, wrap etc. as props

https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/Textarea/index.js

**Comment by segunadebayo** [comment]
Hi @Rixcy,

Thanks for reporting this. We've resolved this in preparation for the next release.
