### ISSUE TITLE
LinkOverlay in LinkBox takes full height after being wrapped in chakra factory

### ISSUE THREAD

**Issue by andrewcohen** [chakra-ui/chakra-ui#5771]
### Description

When I wrap the LinkBox in chakra factory, the LinkOverlay takes up the full height of its container

### Link to Reproduction

https://codesandbox.io/s/interesting-herschel-msrh2m?file=/src/index.tsx

### Chakra UI Version

1.8.6

### Browser

Google Chrome 99

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Possibly related - the LinkBox does not seem to be themeable currently although the documentation suggests it. 

I've opened a separate issue for that https://github.com/chakra-ui/chakra-ui-docs/issues/473

**Comment by jeferson-sb** [comment]
@andrewcohen LinkBox is missing the `position: relative` CSS property in order to keep LinkOverlay background within its boundary, not sure why chakra factory might be overridden that, but you can attach styles to it as workaround:
```jsx
const WrappedLinkBox = chakra(LinkBox, {
  baseStyle: {
    position: "relative"
  }
});
```
