### ISSUE TITLE
Random behavior when using show/hide

### ISSUE THREAD

**Issue by pierrebiver** [chakra-ui/chakra-ui#5773]
### Description

When I use Show or Hide, the css do not get applied properly and generate random behavior. Mainly when using HStack, or SimpleGrid.  I'm using next js and only Chakra UI as UI lib. I'm sorry I couldn’t easily reproduce the bug in codesandbox but I made a screen recording so that you can see for yourself. 

### Link to Reproduction

https://drive.google.com/file/d/1X6Elx4sYA5nC6I_h9tDVswAr1hfqY58l/view?usp=sharing

### Steps to reproduce

1. Go to the link with the video demonstrating the issue

### Chakra UI Version

1.8.6

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I

**Comment by segunadebayo** [comment]
Hi @pierrebiver,

I think you should use `display: { base: none, sm: grid }` to the `SimpleGrid` component instead of the `Show` and `Hide` which relies on JavaScript's media query and might not work in SSR.

**Comment by pierrebiver** [comment]
thanks for your help. I have similar issue with VStack for the mobile version. I tried using the code you shown above but I have the same problem... is there any alternative I can use ?
