### ISSUE TITLE
[Collapse] collapse component isnt rendered open if prop isOpen is false on the server and initially true on the client for SSR

### ISSUE THREAD

**Issue by ylin6** [chakra-ui/chakra-ui#578]
**Describe the bug**
The collapse component isnt opened if the isOpen prop is initially true. It only becomes open after the prop toggles from false to true

**Expected Behavior**
Expected behavior is that the Collapse component is rendered opened if the isOpen prop is true.

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser Chrome
 - Version 80

**Additional context**

**Comment by tioluwani94** [comment]
Hi @ylin6, I'm sorry but we can't reproduce this issue. To help us, kindly create a repository or Codesandbox that reproduces this problem so we can fix it. I tried reproducing the issue here https://codesandbox.io/s/bold-kilby-ydtkf?file=/src/App.js.

**Comment by ylin6** [comment]
@tioluwani94 thanks for the response. After some more investigating, it looks like the issue has to do with nextjs or server side rendering. In my example (see code sandbox below)

I am reading the initial state off of a cookie. On the server, that initial state is `undefined` since the server doesnt have properties of the window. Once it hydrates on the client, it properly reads the cookie value and populates show to `true`. You can see this because the `<Switch>` component is in the `checked` state. From the debugger, you can also see the `Collapse` component is also receiving the props correctly. However, for some reason the height is set to 0 and the children are not visible. 

https://codesandbox.io/s/friendly-bash-f3kjh?file=/pages/index.js

Steps to reproduce in codesandbox
1) Toggle switch on
2) Refresh the page
3) see the toggle being in the `on` state but the collapse component is not `open`
