### ISSUE TITLE
Feature: Use FloatingUI over Popper

### ISSUE THREAD

**Issue by iamclaytonray** [chakra-ui/chakra-ui#5784]
### Description

FloatingUI is super nice and very small. I also like some of it's primitives, particularly around scrolling (ie: arrow changing position, etc)

### Problem Statement/Justification

While it seems to have dropped to the backburner, FloatingUI is cross platform and as such, may motivate more dev efforts into providing official RN support (one day). Here's a list of benefits: https://floating-ui.com/docs/motivation

### Proposed Solution or API

https://floating-ui.com/

**Comment by a-edwaar** [comment]
I'd also love to see Floating UI in Chakra 👍

**Comment by mix3d** [comment]
duplicates #5669
