### ISSUE TITLE
Module augmentation does not update colors

### ISSUE THREAD

**Issue by oscarsanzsanchez-arup** [chakra-ui/chakra-ui#5788]
### Description

When I write a module augmentation, I expect to VSCode suggest new color variables, but it's not doing it.

### Link to Reproduction

no link

### Steps to reproduce

`chakra.d.ts`
![chakra.d.ts](https://user-images.githubusercontent.com/99179684/160590689-82391b5d-b1ad-439d-825d-5c5f71287043.png)

It works for variants
![variantlinkworking](https://user-images.githubusercontent.com/99179684/160590895-99a31be9-7e17-4b8f-9e7f-85e279d2b809.png)

But not for color
![notcolorworking1](https://user-images.githubusercontent.com/99179684/160590971-92aaf364-83bd-4f74-999d-df178393406d.png)

And not working either if colors is an Object
![image](https://user-images.githubusercontent.com/99179684/160591312-25b6cde3-f095-49ac-8ab7-defbc0983d8e.png)

### Chakra UI Version

1.8.7

### Operating System

- [ ] macOS
- [x] Windows
- [x] Linux

### Additional Information

Using Windows Subsystem for Linux (WSL)

**Comment by segunadebayo** [comment]
Hi @oscarsanzsanchez-arup,

Kindly use the Chakra UI CLI to autogenerate types. This is the recommended approach:

- yarn add -D `@chakra-ui/cli`
- `yarn chakra tokens path/to/theme`

Hope this helps.
