### ISSUE TITLE
Emotion css prop

### ISSUE THREAD

**Issue by lishine** [chakra-ui/chakra-ui#579]
I stumble into a problem when specifying emotion css prop or theme-ui sx prop.
In this example the second input has css prop and it's paddingLeft is wrong.
https://codesandbox.io/s/clever-mestorf-qjo6p

**Comment by lishine** [comment]
What I want actually to do is use the theme-ui sx prop instead of spreading the css styles into props like chakra ui natively does.

**Comment by lishine** [comment]
Though I can write of course {...{ css props object }}.

**Comment by lishine** [comment]
I know why this is happening, because the props from InputGroup are blocked by EmotionCssPropInternal.

```
const InputGroup = ({ children, size = "md", ...props }) => {
  const { sizes } = useTheme();
  const height = inputSizes[size] && inputSizes[size]["height"];
  let pl = null;
  let pr = null;
  const validChildren = cleanChildren(children);
  return (
    <Box display="flex" position="relative" {...props}>
      {validChildren.map(child => {
        if (child.type === InputLeftElement) {
          pl = sizes[height];
        }
        if (child.type === InputRightElement) {
          pr = sizes[height];
        }
        if (child.type === Input) {
          return cloneElement(child, {
            size,
            pl: child.props.pl || pl,
            pr: child.props.pr || pr,
          });
        }
        return cloneElement(child, { size });
      })}
    </Box>
  );
};
```

**Comment by segunadebayo** [comment]
Hi @lishine,

Currently, Chakra UI does not support the `sx` prop from `theme-ui`. 

If you really need to do this, chakra exports a `css` function you can use.

```jsx
import {css} from "@chakra-ui/core"

// grab the theme
const theme = useTheme()

// add the styles
const styles = css(stylePropObject)(theme)

// pass it to css prop
<Box css={styles} />
```

Hope this helps.

**Comment by GaspardC** [comment]
Hi @segunadebayo ,

First I'm new to chakra-ui and I really like using it thanks !

I tried to use the `css` function from emotion as you said.

But I still have an Typescript error saying : 

`Property 'css' does not exist on type 'IntrinsicAttributes & IImage & RefAttributes<any> & HTMLAttributes<any> & LayoutProps<Required<Theme<TLengthStyledSystem>>> & ... 18 more ... & { ...; }` 

What can I do ? 

Thks ! 

-----

it's working of course if use this notation : 
`{...{
                    css: css(stylePropObject)
                }}`

**Comment by segunadebayo** [comment]
@GaspardC, kindly add the `jsx` pragma at the top of your file and you should be able to pass the `css` prop.

I mean.
```jsx
/*@jsx jsx*/
import { jsx } from "@emotion/core
```
