### ISSUE TITLE
Add returnFocusOnClose escape hatch to Menu Component

### ISSUE THREAD

**Issue by broose-goose** [chakra-ui/chakra-ui#5792]
### Description

Currently, when a Menu component is closed, the only behavior is to focus the MenuButton element

### Problem Statement/Justification

I have a use case where a Tooltip component wraps a Menu component. Whenever the menu is closed, the Tooltip opens back up, which the user wouldn't expect

### Proposed Solution or API

Add an prop to the Menu component "returnFocusOnClose" like there is in the Modal component. 

### Alternatives

I'm currently doing this, which is pretty dumb...

```
...  
 (  
    <Menu   
        onClose={() => {  
            window.setTimeout(() => {  
                (document.activeElement as HTMLElement).blur()  
            }, 0)  
        }}  
    >  
...  
    </Menu>  
)  
```

### Additional Information

I think this can pretty easily be implemented by adding the prop to the if statement on line 130 of the file [chakra / packages / menu / src / use-menu.ts](https://github.com/chakra-ui/chakra-ui/blob/main/packages/menu/src/use-menu.ts), but when I tried this it didn't work...

**Comment by swapnonil-b** [comment]
+1, if popover and modals can have it, why can't menu?

**Comment by AdhamMoussa** [comment]
That'd be great to have
