### ISSUE TITLE
Marking a FormControl as "required" for a Checkbox Group causes all child checkboxes to be required

### ISSUE THREAD

**Issue by SheaBelsky** [chakra-ui/chakra-ui#5799]
### Description

When I use FormControl on a group of checkboxes, all the checkboxes become required, and I have to select every checkbox (rather than only needing to select one)

### Link to Reproduction

https://codesandbox.io/s/inspiring-leftpad-3mtmu8?file=/src/index.tsx

### Steps to reproduce

1. Create a `FormControl` with the `isRequired` prop
2. Create a `CheckboxGroup` and add some `Checkbox` components to it
3. Wrap everything in a form, and then attempt to submit the form
4. HTML5 validation kicks in because each other checkbox input is treated as being required, even though I only want one of the checkboxes to be selected to satisfy the input requirement

### Chakra UI Version

1.8.7

### Browser

Chrome 99

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by sloyer** [comment]
Ha funny! I just ran into this issue as well.

**Comment by segunadebayo** [comment]
Hi @SheaBelsky,

I won't recommend using `FormControl` and `CheckboxGroup` together. We'll update the code to emit a warning for this usage. FormControl is best used when you have a single form element (single checkbox, radio, input, textarea) **NOT**  a group of form elements.

We'll update the docs to reflect this. Here's how to refactor this:

```jsx
 <Box as="fieldset">
    <Box as="legend">Favorite DC Comics Characters</Box>
    <CheckboxGroup defaultValue={["Nightwing"]}>
      <HStack spacing="24px">
        <Checkbox value="Beast Boy">Beast Boy</Checkbox>
        <Checkbox value="Nightwing">Nightwing</Checkbox>
        <Checkbox value="Starfire">Starfire</Checkbox>
        <Checkbox value="Raven">Raven</Checkbox>
      </HStack>
    </CheckboxGroup>
</Box>
```

**Comment by SheaBelsky** [comment]
@segunadebayo appreciate the clarity and docs improvements! Does that mean there is no native way within Chakra UI to require one checkbox out of many to be selected? I don't mind finding a native way to do it, I just want to confirm if that's the path I need to pursue at this point.

**Comment by segunadebayo** [comment]
That's right @SheaBelsky. There's no native way within Chakra UI, you'll need to handle that within your app code

**Comment by dmwyatt** [comment]
@SheaBelsky  I just stumbled across this while looking for something else and I just wanted to note that "require one checkbox out of many to be selected" is best served by radio buttons, not checkboxes.  That's the whole reason the two different concepts exist.

**Comment by caomicc** [comment]
@segunadebayo The current documentation does not mention this limitation, and includes "sample usage for a checkbox group" as part of a page section: https://chakra-ui.com/docs/components/form-control#sample-usage-for-a-radio-or-checkbox-group

Is it a planned enhancement to be able to use `FormControl` and `CheckboxGroup` concurrently?

---

> I just stumbled across this while looking for something else and I just wanted to note that "require one checkbox out of many to be selected" is best served by radio buttons, not checkboxes. That's the whole reason the two different concepts exist.

@dmwyatt There are use cases that involve requiring _at least_ one option selected while having more than two options for the user to select from. This makes a radio button approach infeasible:

```
 * Option A
 * Option B
 * Option C
 * ...
 * Option A & B
 * Option A & C
 * Option A & ...
 * Option A & B & C
 * Option A & B & ...
```

On the other hand, a checkbox approach is much more intuitive and straightforward for both users and developers.

**Comment by caomicc** [comment]
FWIW, I was able to achieve this via a local state :)

```
const MarketoCheckboxesInput = ({
  values,
  name,
}: {
  values: Value[];
  name: string;
}) => {
  const [atLeastOneChecked, setAtLeastOneChecked] = useState(false);

  return (
    <CheckboxGroup
      onChange={(value) => setAtLeastOneChecked(Boolean(value.length))}
    >
      <Stack
        spacing={[1, 5]}
      >
        {values?.map(({ value, label }) => {
          return (
            <Checkbox
              key={value}            
              isRequired={atLeastOneChecked ? false : undefined}
            >
              {label}
            </Checkbox>
          );
        })}
      </Stack>
    </CheckboxGroup>
  );
};
```

**Comment by dmwyatt** [comment]
> There are use cases that involve requiring at least one option selected

@caomicc Right, but I was replying to the specific request to "require one".
