### ISSUE TITLE
Add disabled state for other 

### ISSUE THREAD

**Issue by alexnguyennz** [chakra-ui/chakra-ui#5800]
### Description

I've noticed that for non-default<Tab> variants that the isDisabled state does not set the same style. Was this intentional?

To get around this, I've just applied the `css-1ltezim` class that I found which seems to apply the same effects; greyed out text and not-allowed cursor.

### Problem Statement/Justification

Add the same class or styles to all variants for consistent behaviour and display - I'm unsure if css-1ltezim is unique to particular components.

### Proposed Solution or API

Add the same class or styles to all variants for consistent behaviour and display - I'm unsure if css-1ltezim is unique to particular components.

**Comment by segunadebayo** [comment]
Hi @alexnguyennz,

This style is generated by `@emotion/styled` at runtime. It's not a static style.

**Comment by alexnguyennz** [comment]
Hi good to know. Any thoughts on the issue at hand or no disabled styles for other variants?
