### ISSUE TITLE
Cra template project can't work

### ISSUE THREAD

**Issue by okesseko** [chakra-ui/chakra-ui#5803]
### Description

Can't run the cra typescript template, 

### Steps to reproduce

1. Create a new cra typescript template (npx create-react-app my-app --template @chakra-ui/typescript)
2. npm run start
3. Get the white screen and error console log
![image](https://user-images.githubusercontent.com/59650459/161305300-e62e1b63-607a-46c6-a314-357a0e177506.png)

### Chakra UI Version

1.8.7

### Browser

Google Chrome 100

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

package.json
```
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@chakra-ui/react": "^1.8.7",
    "@emotion/react": "^11.8.2",
    "@emotion/styled": "^11.8.1",
    "@testing-library/jest-dom": "^5.16.3",
    "@testing-library/react": "^10.4.9",
    "@testing-library/user-event": "^12.8.3",
    "@types/jest": "^25.2.3",
    "@types/node": "^12.20.47",
    "@types/react": "^16.14.24",
    "@types/react-dom": "^16.9.14",
    "framer-motion": "^4.1.17",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-icons": "^3.11.0",
    "react-scripts": "5.0.0",
    "typescript": "^4.6.3",
    "web-vitals": "^0.2.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

````

**Comment by yououhan123** [comment]
Seems like the same issue as mentioned in https://github.com/chakra-ui/chakra-ui/issues/3618. I was able to get it fixed by following the workaround.
```
yarn remove framer-motion
yarn add framer-motion@3.10.6
yarn start
```

**Comment by okesseko** [comment]
> Seems like the same issue as mentioned in #3618. I was able to get it fixed by following the workaround.
> 
> ```
> yarn remove framer-motion
> yarn add framer-motion@3.10.6
> yarn start
> ```
> 
> For npm
> 
> ```
> npm uninstall framer-motion
> npm install framer-motion@3.10.6
> npm start
> ```

It work thx

**Comment by yououhan123** [comment]
@okesseko I would assume the [fix](https://github.com/chakra-ui/chakra-ui/issues/5803#issuecomment-1086319086) I suggested is simply a workaround instead of a fix. Would it make sense to re-open this issue so that it can be addressed properly?
