### ISSUE TITLE
CRA with NPM/TypeScript failing

### ISSUE THREAD

**Issue by sasjonbri** [chakra-ui/chakra-ui#5804]
### Description

When I run the "TypeScript using npm" command found [here](https://chakra-ui.com/guides/getting-started/cra-guide) I am getting errors in my terminal and the command exits before completing.

### Link to Reproduction

This happens in the terminal

### Steps to reproduce

Run this command:

```sh
npx create-react-app ch_npm --template @chakra-ui/typescript
```

Error:
![image](https://user-images.githubusercontent.com/10959274/161324704-f8aae8bd-8c4b-4322-9baf-acbf3675c663.png)

### Chakra UI Version

Latest stable

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I'm using WSL2
Node v14.19.1
NPM 6.14.16

**Comment by yououhan123** [comment]
Seems like the same issue as described in https://github.com/chakra-ui/chakra-ui/issues/3618. The same workaround (`yarn remove framer-motion` and then `yarn add framer-motion@3.10.6`) fixed it for me.

**Comment by ggrantrowberry** [comment]
I'm also having an issue with this.  I don't get the same error however. 

I ran `yarn create react-app my-app --template @chakra-ui/typescript` It installed properly it seems but then when I start it nothing appears in the browser. The following error showed up in the console. 

```
bootstrap:27 Uncaught TypeError: framer_motion__WEBPACK_IMPORTED_MODULE_5__.motion.custom is not a function
    at Module../node_modules/@chakra-ui/checkbox/dist/chakra-ui-checkbox.esm.js (chakra-ui-checkbox.esm.js:146:1)
    at Module.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at Module../node_modules/@chakra-ui/react/dist/chakra-ui-react.esm.js (chakra-ui-react-utils.esm.js:91:1)
    at Module.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at Module../src/App.tsx (logo.svg:47:1)
    at Module.options.factory (react refresh:6:1)
```

I am using MacOS. With Node v16.13.2 and npm v8.1.2

**Comment by ggrantrowberry** [comment]
Same error occurs if Chakra is installed manually. 
Here are my dependencies. 
```
"@chakra-ui/react": "^1.8.7",
"@emotion/react": "^11",
"@emotion/styled": "^11",
"@testing-library/jest-dom": "^5.14.1",
"@testing-library/react": "^12.0.0",
"@testing-library/user-event": "^13.2.1",
"@types/jest": "^27.0.1",
"@types/node": "^16.7.13",
"@types/react": "^17.0.20",
"@types/react-dom": "^17.0.9",
"framer-motion": "^6",
"react": "^18.0.0",
"react-dom": "^18.0.0",
"react-scripts": "5.0.0",
"typescript": "^4.4.2",
"web-vitals": "^2.1.0"
```
It's probably worth noting that react is version 18.

**Comment by okesseko** [comment]
> Same error occurs if Chakra is installed manually. Here are my dependencies.
> 
> ```
> "@chakra-ui/react": "^1.8.7",
> "@emotion/react": "^11",
> "@emotion/styled": "^11",
> "@testing-library/jest-dom": "^5.14.1",
> "@testing-library/react": "^12.0.0",
> "@testing-library/user-event": "^13.2.1",
> "@types/jest": "^27.0.1",
> "@types/node": "^16.7.13",
> "@types/react": "^17.0.20",
> "@types/react-dom": "^17.0.9",
> "framer-motion": "^6",
> "react": "^18.0.0",
> "react-dom": "^18.0.0",
> "react-scripts": "5.0.0",
> "typescript": "^4.4.2",
> "web-vitals": "^2.1.0"
> ```
> 
> It's probably worth noting that react is version 18.

Seems like framer-motion cuasing error
You can follow [this](https://github.com/chakra-ui/chakra-ui/issues/5803#issuecomment-1086319086) to fix it

**Comment by netcoding87** [comment]
I am having the same issue. A repository for reproduction can be found here: https://github.com/netcoding87/chakra-ui-issue

Downgrading `framer-motion` to `3.10.6` works but is not the desired solution. For unknown reasons I cannot reproduce this in an codesandbox...

**Comment by bchilcott** [comment]
For reference, the following (non-typescript) also doesn't work. Probably obvious, but worth mentioning.

`npx create-react-app my-app --template=@chakra-ui`

This issue occurs after following the docs step by step which isn't great, so maybe the template needs updating to downgrade framer-motion?

**Comment by netcoding87** [comment]
Note: When downgrading `react-scripts` to `4.0.3` it works. `react-scripts` version 4 uses webpack version 4, whereas `react-scripts` `5.0.0` uses webpack `^5.0`. I actually do not know if this is an issue with `framer-motion` and webpack 5 or the usage of `framer-motion` in `chakra-ui`...

**Comment by lahlim** [comment]
Resolution to older webpack in `react-scripts` can solve this temporarily! https://github.com/chakra-ui/chakra-ui/issues/5812#issuecomment-1088419675

**Comment by maxcww** [comment]
> Resolution to older webpack in `react-scripts` can solve this temporarily! [#5812 (comment)](https://github.com/chakra-ui/chakra-ui/issues/5812#issuecomment-1088419675)

If you use npm, then use `"devDependencies": {
    "webpack": "5.70.0"
  }`

Resolutions is yarn I believe.

**Comment by jonbri** [comment]
Yes, @netcoding87 it's working for me now as well 👍

**Comment by jonbri** [comment]
I think this issue can be closed

**Comment by JTBrinkmann** [comment]
Right. I just ran a few tests, and upgrading either `webpack` to v5.72.0 (or 5.70.0 and below), or `@chakra-ui/react` to 1.8.8, (or both) fixes the issue. It is apparently not required to manually clear any cache. Note that `@chakra-ui/react` 1.8.8 only has a workaround, but does not fix the core issue, so you should upgrade webpack in any case because the bug also causes issues with other libraries or possibly your own code.
