### ISSUE TITLE
Stack adds unexpected spacing when first child has `display: 'none'`

### ISSUE THREAD

**Issue by a-edwaar** [chakra-ui/chakra-ui#5807]
### Description

When I used a Stack where the first child had `display: 'none'`, I expected the second child of the Stack to not have a margin. However, the margin is added to the element. This happens for both HStack and VStack. 

This is unexpected behaviour according to MDN's definition of `display: 'none'`: 

```
Turns off the display of an element so that it has no effect on layout (the document is rendered as though the element did not exist)
```

### Link to Reproduction

https://codesandbox.io/s/black-bird-6hii0s?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/black-bird-6hii0s?file=/src/App.js
2. Observe that the text `I should be in the top-left corner of the page with no margins!` is not in the top-left corner of the page

### Chakra UI Version

1.8.7

### Browser

Brave 1.36

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @a-edwaar,

This is due to how Stack applies the margin across its child elements. To use a `display: none` child, kindly consider using Flex and the new `gap` property, or Grid.

**Comment by a-edwaar** [comment]
Thanks for the response @segunadebayo! 🙂 

I have been using `Flex` as a workaround but thought its worth digging a bit deeper here so I created the issue. 

Just have a couple of questions.

> This is due to how Stack applies the margin across its child elements

This behaviour seems odd to me, hence why it caught me out in the first place. If the element has `display:'none'`, why should it have an effect on the layout?

Also, how come `Gap` behaves differently?
