### ISSUE TITLE
Menu sometimes gets stuck in a layout loop

### ISSUE THREAD

**Issue by jonbri** [chakra-ui/chakra-ui#5817]
### Description

When the browser height is less than a `Menu`'s height, an infinite layout loop can occur when user hovers over items

### Link to Reproduction

https://codesandbox.io/s/recursing-scott-3s6kih?file=/src/index.tsx

### Steps to reproduce

1. Navigate to https://codesandbox.io/s/recursing-scott-3s6kih?file=/src/index.tsx in Chrome
2. Reduce browser window height to about 1/2 the screen size
3. Click "Open menu" button
4. Slowey hover over menu, from top to bottom
5. At times, when hovering between the menu items the Menu gets stuck in positioning:

![menuNotSettled](https://user-images.githubusercontent.com/1750227/161622195-709a5502-e2fb-44d3-8998-d49eaab01af8.gif)

### Chakra UI Version

1.8.7

### Browser

Google Chrome 99

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by yss14** [comment]
This is still a problem with Chakra UI `2.4.6` and apparently only occurs on Windows for us.

**Comment by BruceHubbard** [comment]
Did either of you figure out how to get around this?  We just upgraded to 1.8.8 and one of our really long MenuList's has this problem now.  I'm trying to find a work around

**Comment by BruceHubbard** [comment]
I ended up throwing `maxHeight` and `overflowY` onto the `<MenuList` and it seems to fix most of the jankiness: `<MenuList maxHeight="50vh" overflowY="auto">`
