### ISSUE TITLE
Radio Color

### ISSUE THREAD

**Issue by export-mike** [chakra-ui/chakra-ui#582]
**Radio Button Color not setting**
seems to default to white?
see: 
https://codesandbox.io/s/cranky-goodall-q9b9z

I've got a work around which is a hack
```js
const AddRadioColor = styled(Radio)`
  div[type="radio"] {
    color: ${({theme}) => theme.colors.gray[300]};
  }
`
```

**Expected**

a non white color as default and allow control via a color prop

**Comment by segunadebayo** [comment]
Hi @export-mike,

You're missing the ` <CSSReset />` component in that Codesandbox. 

We've addressed this properly in the next release but for now, please make sure you add the ` <CSSReset />` component as it contains some global styles that make the visuals consistent.

**Comment by segunadebayo** [comment]
Hang on. Are you referring to the "dot" in the Radio button? Do you want to change the color?

Kindly help me understand 'coz I feel I didn't answer the question correctly

**Comment by Deevoid** [comment]
Hey! If anyone is still looking to customize the color of the dot of radio button , Please do this,
`Radio: {
      variants: {
        primary: ({ colorScheme = "primary" }) => ({
          color: `${colorScheme}.500`,
          control: {
            _checked: {
              color: "secondary.500",
            },
          },
        }),
      },
      defaultProps: {
        variant: "primary",
        colorScheme: "primary",
      },
    },`
