### ISSUE TITLE
Checkbox does not reset on HTMLFormElement.reset()

### ISSUE THREAD

**Issue by Crustan** [chakra-ui/chakra-ui#5820]
### Description

When I reset the form with [HTMLFormElement.reset()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset), I expected that all inputs should be cleared, but the checkbox input was not.

### Link to Reproduction

https://codesandbox.io/s/suspicious-liskov-79x8yu

### Steps to reproduce

1. Go to https://codesandbox.io/s/suspicious-liskov-79x8yu
2. Enter text in the input field
3. Check the checkbox
4. Submit the form
5. Text input is reset, checkbox is not.

### Chakra UI Version

1.8.7

### Browser

Google Chrome 99

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The actual checkbox input gets cleared, but visually, it still looks checked.

**Comment by hardikhere** [comment]
Hello @Crustan I want to contribute please let me know if you are already doing or if you have something for me :)

**Comment by Crustan** [comment]
> Hello @Crustan I want to contribute please let me know if you are already doing or if you have something for me :)

I haven't looked into it more than that. Switched to using a controlled form state instead. But I think this should work regardless.

**Comment by hardikhere** [comment]
> > Hello @Crustan I want to contribute please let me know if you are already doing or if you have something for me :)
> 
> I haven't looked into it more than that. Switched to using a controlled form state instead. But I think this should work regardless.

Got it Thanks @segunadebayo I'm looking at this

**Comment by hardikhere** [comment]
Unable to make any progress yet. I'm not able to find root cause

**Comment by segunadebayo** [comment]
Hi @hardikhere,

The hint to fix this is to check the form connected to the input element (`input.form`) and listen for its `reset` event. We'll use that to sync the state of the checkbox as needed.

**Comment by hardikhere** [comment]
Hi @segunadebayo Thanks for hint.
I know how to do it now, `checkbox.form.onreset = ()=>{  //resetting the checkbox state  }`.

**Comment by hardikhere** [comment]
Hi @segunadebayo PR is raised for the same. Please check #5978

**Comment by segunadebayo** [comment]
This is now fixed in the PR attached
