### ISSUE TITLE
Multipart component theming doesn't work for Popover arrow

### ISSUE THREAD

**Issue by noobinthisgame** [chakra-ui/chakra-ui#5821]
### Description

When I create a custom theme for a Popover component, I expect the arrow part theme to style the arrow of the Popover but it doesn't work.

### Link to Reproduction

https://codesandbox.io/s/cool-newton-xw6kie?file=/src/App.js

### Steps to reproduce

1. Go to Codesanbox
2. See the theme with the arrow part. 
3. It has no effect

### Chakra UI Version

1.8.7

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

There is a workaround that is inspired from the implementation in the base theme. See line 22, 23 in the Codesandbox. Uncomment those and it works. However this is not the way I expect it to work, as multipart component theming should work here.

**Comment by arclogos132** [comment]
Still not fixed.

**Comment by arclogos132** [comment]
Thanks for the workaround @noobinthisgame !!

**Comment by jeliroco** [comment]
Yeah this is still broken. Can't figure out how to get this workaround to work with a proper flexible "defineMultiStyleConfig" implementation. Thanks much for the investigation though @noobinthisgame -- may fiddle around with this and see what I can figure out. For now though, just going to remove the arrows from my popovers -_-

**Comment by mhamid3d** [comment]
With dark mode this does not work because the variable is coming from the dark theme. How can we edit that?
