### ISSUE TITLE
theme isn't applied to `FormControl` component

### ISSUE THREAD

**Issue by b-novikov-ipersonality** [chakra-ui/chakra-ui#5824]
### Description

When I extend theme with `FormControl` component styles I expect styles to be applied but they are not

### Link to Reproduction

https://codesandbox.io/s/angry-carlos-v6sqjm?file=/src/App.tsx

### Steps to reproduce

1. Extend theme with `FormControl` styles, i.e. add `baseStyle` and `variant`
1. Use `FormControl`  component
1. See theme not being applied

### Chakra UI Version

1.8.7

### Browser

Version 100.0.4896.75 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Theme is defined in `index.tsx` file, component is used in `App.tsx` file.
Theme also not being applied to `Input` component and probably there're others. 

Issue might be related to #3884

**Comment by TimKolberger** [comment]
The theme key for "FormControl" is unfortunately "Form".
Kindly [see this CodeSandbox](https://codesandbox.io/s/nice-currying-vjm1ss?file=/src/index.tsx:207-214).

I am using the "View theme source" very often when editing themes, to get to know the parts of a [MultipartComponent](https://chakra-ui.com/docs/styled-system/theming/component-style#styling-multipart-components).

<img width="795" alt="image" src="https://user-images.githubusercontent.com/16899513/162060179-6843deaa-9153-445b-bc37-738e3922481d.png">

Hope this helps, cheers :)

**Comment by b-novikov-ipersonality** [comment]
@TimKolberger thank you for pointing that. Is `Input` component a part of some multipart component too? I can't apply styles to it: https://codesandbox.io/s/angry-carlos-v6sqjm?file=/src/index.tsx
`Input` completely ignores `baseStyle` and custom variants, although it does apply styles from default variant (either by defining `defaultProps.variant` or by setting `variant` prop directly on `Input`)

**Comment by TimKolberger** [comment]
Let's find out:

Open the docs for the Input component:

![image](https://user-images.githubusercontent.com/16899513/162161614-5575c16c-9d3c-4078-9239-5183aff6b530.png)

Click on "View theme source" and look for `baseStyle`:

https://github.com/chakra-ui/chakra-ui/blob/3e0a97185afda28edb47414db190916ea541bf57/packages/theme/src/components/input.ts#L9-L19

Notice the `field` property => the Input component is a MultipartComponent.

**Comment by b-novikov-ipersonality** [comment]
@TimKolberger ahh that's how you find parts. It's clear now. Thank you very much Tim! =)

**Comment by b-novikov-ipersonality** [comment]
@TimKolberger hi Tim. I apologize I'm stupid or something, but I can't figure out why theme does not work for `Heading` component. 
I specify responsive styles inside `extendTheme`: 
```js
const theme = extendTheme({
  ...
  Heading: {
    variants: {
      title: {
        fontSize: { base: 'xl', md: '5xl' }
      }
    }
  }
});
```
but it doesn't work.
sandbox: https://codesandbox.io/s/angry-carlos-v6sqjm?file=/src/index.tsx here responsive styles defined inside `extendTheme` do work for `Text` component  but don't work for `Heading` component

I found similar but not exact issue, #3884. Is it related? Or am I doing something wrong, **again**?

**Comment by ArthurGerbelot** [comment]
Look like Form theme as been refactored October 22 so it's not a multipart anymore (but thank you @TimKolberger for your tips, this should be more explained on chakra UI documentation.. Component theme documentation are often empty.. :/ )

But even using Form or FormControl (now a simple component style) still not working for me.

**Comment by TimKolberger** [comment]
Hi @ArthurGerbelot, kindly open a new issue with a reproduction on codesandbox. This way we and the community can help you faster!
