### ISSUE TITLE
`Button` rendered by `MenuButton` is always focused

### ISSUE THREAD

**Issue by thiengo105** [chakra-ui/chakra-ui#5825]
### Description

When I use `MenuButton` to render `Button` component with `as`, this button is always focused but I don't want this happen.
When I remove `as` prop, it is not focused anymore.

### Link to Reproduction

https://codesandbox.io/s/jovial-bush-15gusr?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/jovial-bush-15gusr?file=/src/App.js
2. Click on the refresh button in the sandbox preview
3. See the button of the menu is focused first.

### Chakra UI Version

1.8.7

### Browser

Google Chrome 100

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @thiengo105,

This was fixed in the recent `next` release. If the issue persists, I'll re-open it.
