### ISSUE TITLE
Custom size not working

### ISSUE THREAD

**Issue by punit2502** [chakra-ui/chakra-ui#583]
I created a custom size by extending the theme but it is not working
Example: https://codesandbox.io/s/lively-glade-lef4p

**Comment by aqrojo** [comment]
Padding props can accept values from the space theme key so try to add your custom value under theme.space instead

**Comment by tioluwani94** [comment]
Thanks for the response @aqrojo. 
@punit2502, to add to @aqrojo's response, the space theme key affects values such as width, height, and maxWidth, minWidth, maxHeight, minHeight. You can learn more from the Chakra UI docs here https://chakra-ui.com/theme.
