### ISSUE TITLE
CSS variables not compiled in tsdx app with Storybook

### ISSUE THREAD

**Issue by mellis481** [chakra-ui/chakra-ui#5830]
### Description

When I add Chakra to a tsdx app with Storybook, I expect the CSS variables to be compiled, but they are not.

### Link to Reproduction

https://github.com/mellis481/chakra-test

### Steps to reproduce

1. Clone repo.
2. Run `npm i`.
3. Run `npm run storybook`.

### Chakra UI Version

1.8.7

### Browser

Google Chrome 100.0.4896.75

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I have a tsdx app with Storybook which I've integrated Chakra into and I'm seeing CSS variables not being compiled. eg.

![image](https://user-images.githubusercontent.com/39313898/162024095-bd1faa48-1eba-4c34-9db9-4f2884409c07.png)

When I compare this to working examples, I see that the CSS variables are successfully compiled and available at run-time. eg.

![image](https://user-images.githubusercontent.com/39313898/162024282-bf7ee1c1-9f17-47a6-97e0-0bb501a77d56.png)

Note that I tried to integrate Chakra into a tsdx `react` project and I did NOT see this issue. It's only when Chakra is integrated into a `react-with-storybook` tsdx project.

**Comment by mellis481** [comment]
For posterity, it looks like the following `webpackFinal` storybook configuration (`.storybook/main.js`) fixed it:

```
const path = require('path');

const toPath = (_path) => path.join(process.cwd(), _path);

module.exports = {
  stories: ['../stories/**/*.stories.@(ts|tsx|js|jsx)'],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials'],
  // https://storybook.js.org/docs/react/configure/typescript#mainjs-configuration
  typescript: {
    check: true, // type-check stories during Storybook build
  },
  webpackFinal: async (config) => {
    return {
      ...config,
      resolve: {
        ...config.resolve,
        alias: {
          ...config.resolve.alias,
          '@emotion/core': toPath('node_modules/@emotion/react'),
        },
      },
    };
  },
};
```

**Comment by CaitlinSweeney** [comment]
> const toPath = (_path) => path.join(process.cwd(), _path);

Thanks for this, my co-worker is trying to inject a chakra app in Webflow (total migraine), saved me from gonig down a rabbit hole of another solution.
