### ISSUE TITLE
MenuItemOption doesn't support `command` prop as docs indicate

### ISSUE THREAD

**Issue by danielbeardsley** [chakra-ui/chakra-ui#5832]
### Description

When I pass the 'command' prop to MenuItemOption, I expect it to render a MenuCommand component

### Link to Reproduction

https://codesandbox.io/s/kind-leaf-t4465p?file=/src/app.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/kind-leaf-t4465p?file=/src/app.js
2. Click on the "Menu" button
3. Expect to see the "command" text on each menu item

### Chakra UI Version

1.8.7

### Browser

Chrome 100

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

The docs claim it's supported, but the code does not support it (though it looks like it works with `MenuItem`).

**Comment by jarstelfox** [comment]
I did some digging:

It does look like `command` is defined on the interface:
https://github.com/chakra-ui/chakra-ui/blob/3e0a97185afda28edb47414db190916ea541bf57/packages/menu/src/menu.tsx#L249-L267

https://github.com/chakra-ui/chakra-ui/blob/3e0a97185afda28edb47414db190916ea541bf57/packages/menu/src/menu.tsx#L282-L284

But the component just does nothing with the prop:

https://github.com/chakra-ui/chakra-ui/blob/3e0a97185afda28edb47414db190916ea541bf57/packages/menu/src/menu.tsx#L355-L361

If you dig into the code it looks like `useMenuOption` and `useMenuItem` will pass back up the props. I suspect the pro is getting lost somewhere in this code path.

https://github.dev/chakra-ui/chakra-ui/blob/3e0a97185afda28edb47414db190916ea541bf57/packages/menu/src/use-menu.ts#L649-L656

**Comment by danielbeardsley** [comment]
> If you dig into the code it looks like `useMenuOption` and `useMenuItem` will pass back up the props. I suspect the prop is getting lost somewhere in this code path.

It's implemented in `MenuItem`, but not `MenuItemOption`

**Comment by segunadebayo** [comment]
Hi @danielbeardsley,

This is by design. Native OS menus don't allow commands for option items, they often only allow that for normal menu options. If you really need this, kindly use the `useMenu` hook instead and override the aspects you need.

Thanks for understanding.

**Comment by andyszy** [comment]
> Native OS menus don't allow commands for option items

The Preview app on Mac is a counterexample:
<img width="447" alt="image" src="https://github.com/chakra-ui/chakra-ui/assets/3219015/0781d0c9-d0ad-430c-bb97-1aad0f0bae69">

I have a similar use case in my Chakra app—fixing support for the `command` prop in `MenuItemOption` would be very helpful to me!
