### ISSUE TITLE
Toast not working anymore

### ISSUE THREAD

**Issue by Poolshark** [chakra-ui/chakra-ui#5839]
After having several issues with `framer-motion`, I have solved this by upgrading `webpack` and `@chakra-ui`. However, now neither `useToast()` nor `createStandaloneToast()` is working anymore.

I'm really not sure what is going on here but I'm getting the well known error message:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
ToastManager
```

I did experiment a bit with different versions of `framer-motion` (I could solve a similar issue before with downgrading to `v5.6.0`) but now no luck.

An help more then appreciated! Thanks! 🙌

### Versions:
- `@chakra-ui/react: 1.8.8`
- `framer-motion: 6.2.9`
- `webpack: 5.72.0`
- `react-dom: 17.0.2`
- `react: 17.0.2`
- `react-scripts: 5.0.0`
- `@craco/craco: 6.4.3`

**Comment by TimKolberger** [comment]
Hi @Poolshark
Could you kindly provide a reproduction for this? A git repo or codesandbox helps a lot debugging those errors.

**Comment by Poolshark** [comment]
Hi @TimKolberger 

Thanks for the very quick response!

I have forgotten to mention, that I have a very complex monorepo in place which makes it impossible to resemble something like this on, eg. CodeSandbox. Additionally, I can't figure out how to config CodeSandbox to run applications with custom eg. `webpack` configs.

I'm very aware that not being able to provide reproduction examples makes solving this nearly impossible but I was hoping that someone else might experience the same issue since it **only occurs with the Chakra Toast component.**

**Comment by kk21** [comment]
I am using the latest nextjs 12 and all the same versions listed above except for webpack which isnt listed in package.json.

I call my own custom toast from createStandaloneToast and everything still works.

**Comment by jamesmeneghello** [comment]
Had the same issue - for us it was because multiple versions of chakra were being included (we'd just swapped to esbuild and hadn't declared it as an external). Possibly a webpack change (or webpack config change) causing it?

**Comment by segunadebayo** [comment]
I can't seem to reproduce this issue. It sounds like something related to Next.js and Webpack.

Kindly provide a reproduction and we'll look into it.

**Comment by srivastavaAbhishek01** [comment]
> I am using the latest nextjs 12 and all the same versions listed above except for webpack which isnt listed in package.json.
> 
> I call my own custom toast from createStandaloneToast and everything still works.

its not working at all...

**Comment by TimKolberger** [comment]
As stated multiple times in this thread: kindly share a reproduction as codesandbox or git repo to give others the opportunity to help.

@elliotbonneville the Toast package was rewritten to work with React 18. AFAIK we do not have any major changes regarding the toast package our roadmap. Personally I understand your message as a demand to do something - please don't do that in Open Source.

**Comment by Great-Odin** [comment]
We upgraded Chraka-react to  1.7.5 and solves the issue

**Comment by ra-kesh** [comment]
we have upgraded chakra-react to 1.7.5 and this issue still persists in local environment . But Surprisingly somehow it is working in production. I know this is not the right way to ask for help but I sincerely don't know how to reproduce this error as we are using nextJs version 12 within turbo repo latest.

**Comment by danyhiol** [comment]
I also stumbled on this problem on NextJS. Somehow I had to add `<ToastContainer />` to `_app.js` for the toast to work. Looks like the provider alone does not provide a toast container.

**Comment by radoslawgrochowski** [comment]
In my case if fixed it by using reexported `ChakraProvider` and `ToastProvider` from our internal ui package instead of importing directly from `@chakra-ui/react`.  Might be some dependency conflict i think?

**Comment by tc9011** [comment]
I'm using umi v3 for my app. If you do not enable msfu (MFSU is a speed-up package solution based on the new WebPack5 feature Module Federation.), the toast use createStandaloneToast  in my app will not show, so I think maybe it's a conflict between Webpack and Toast

**Comment by sorenhusted** [comment]
> I also stumbled on this problem on NextJS. Somehow I had to add `<ToastContainer />` to `_app.js` for the toast to work. Looks like the provider alone does not provide a toast container.

I have the same issue. From where do you import `<ToastContainer />`?

I'm using chakra-ui v2.3.4 and next v12.3.0

**Comment by Destiner** [comment]
Fixed by adding `<ToastProvider>` (from `@chakra-ui/react`) to `_app.tsx`.

**Comment by danyhiol** [comment]
> > I also stumbled on this problem on NextJS. Somehow I had to add `<ToastContainer />` to `_app.js` for the toast to work. Looks like the provider alone does not provide a toast container.
> 
> I have the same issue. From where do you import `<ToastContainer />`?
> 
> I'm using chakra-ui v2.3.4 and next v12.3.0

1. `import { createStandaloneToast } from '@chakra-ui/toast';`
2. `const { ToastContainer } = createStandaloneToast();`
3. 
```
<Fragment>
      <Head>
        ...
      </Head>
      <ToastContainer />
      <ChakraProvider theme={theme}>
            ...
            <Component {...pageProps} />
            ...
      </ChakraProvider>
</Fragment>
```
I hope this helps.

**Comment by ekrokowski** [comment]
This could happen if you use 

```
import { ChakraProvider } from '@chakra-ui/provider';
```

instead of 
```
import { ChakraProvider } from '@chakra-ui/react';
```

Only the ChakraProvider from `@chakra-ui/react` automatically renders the `ToastProvider`.

**Comment by tonton-k37** [comment]
@ekrokowski Thank you. Saved my day.

> This could happen if you use
> 
> ```
> import { ChakraProvider } from '@chakra-ui/provider';
> ```
> 
> instead of
> 
> ```
> import { ChakraProvider } from '@chakra-ui/react';
> ```
> 
> Only the ChakraProvider from `@chakra-ui/react` automatically renders the `ToastProvider`.

**Comment by TheAndrewJackson** [comment]
@ekrokowski Thank you! Your solution also fixed my issue.

**Comment by Ohtico** [comment]
Hola de un momento a otro dejo de salir los toast en mi proyecto alguien podría ayudarme?
