### ISSUE TITLE
[NumberInput] clampValueOnBlur throws an error

### ISSUE THREAD

**Issue by deebov** [chakra-ui/chakra-ui#584]
**Describe the bug**
there's an error if the input value is greater than the `max` prop when focus is blurred 

**Expected Behavior**
there should be no error in the console and value must be equal or less than the `max` prop when focus is blurred

**To Reproduce**
1. go to https://chakra-ui.com/numberinput#allowing-out-of-range-values
2. set `max` prop and `clampValueOnBlur` to true
3. Focus the input out

**Comment by deebov** [comment]
![image](https://user-images.githubusercontent.com/28673719/78673399-857e6900-78fb-11ea-9c32-d17c60eb148b.png)

**Comment by segunadebayo** [comment]
Hi @deebov,

Thanks for this issue. We've resolved this in preparation for the next release.

**Comment by tafelito** [comment]
@segunadebayo is this going to be fixed only in v1 and up? Can a patch be applied to pre v1?
