### ISSUE TITLE
ChakraProvider breaks Suspense in Next.js projects, even without suspended components

### ISSUE THREAD

**Issue by PatrikTheDev** [chakra-ui/chakra-ui#5842]
### Description

When you add ChakraProvider to _app.tsx, any usage of Suspense breaks the app.

### Link to Reproduction

https://codesandbox.io/s/nice-wood-50d2lj?file=/pages/index.tsx

### Steps to reproduce

1) Create a vanilla Next.js app
2) Add a Suspense component with `<p>Hello world</p>` as children into pages/index.tsx
3) Verify it works fine (should)
4) Add @chakra-ui/react and `<ChakraProvider>` into _app.tsx
5) Reload the page - emits the following error:

`Error: This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition.`

### Chakra UI Version

1.8.8 and @next

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by chrisco255** [comment]
I'm still seeing this issue in v2.0.0. Not sure if it's related to the hook library I'm using (wagmi), which is based on react-query.

**Comment by PatrikTheDev** [comment]
I recommend trying a small sample to reproduce, helps narrow down the issue

**Comment by dasdasdasd1232134** [comment]
```
(
    <EnvironmentProvider>
        <Suspense fallback={<Spinner />}>
            <ComponentThatSuspend />
        </Suspense>
    </EnvironmentProvider>
)
```

setNode(el) in EnvironmentProvider will cause it re-render,
and the context value has changed from `defaultEnv` to { document, window }
React recived an update during streaming rendering
react doesn't know if this update will affect the `<ComponentThatSuspend />` component 

So react will have to replace the server HTML with the suspense fallback.
This is because it is stale

More detail: https://github.com/reactwg/react-18/discussions/38


I think we need refactor EnvironmentProvider to avoid the top-level updates during the app startup.

**Comment by Draqode** [comment]
This issue still persists and is still occurring, I tried wrapping my api call with a startTransition but it's still isn't working

**Comment by itseasy21** [comment]
@Draqode this might be fixed in: https://github.com/chakra-ui/chakra-ui/pull/6220

**Comment by SecondThread** [comment]
Can confirm this is still happening, even after updating Chakra.

**Comment by SecondThread** [comment]
@[segunadebayo] Would you be able to reopen this, given that it's still an issue?

**Comment by SecondThread** [comment]
I was finally able to fix this by putting <ColorModeScript /> (initially in _document) inside my RelayEnvironmentProvider in _app.ts. My _app.tsx now looks like:

```
...
		<>
			<Head>
				<link rel='icon' href='/logo.ico' />
				<title>SecondThread</title>
			</Head>
			<RelayEnvironmentProvider environment={RelayEnvironment}>
				<Suspense fallback={'loading...'}>
					<ColorModeScript />
					<ChakraProvider resetCSS theme={theme}>
						{/* eslint-disable */}
						{/* @ts-ignore */}
						<Component {...pageProps} />
					</ChakraProvider>
				</Suspense>
			</RelayEnvironmentProvider>
		</>
```

Hope this helps!

**Comment by nghiepit** [comment]
In `@chakra-ui/react@2.2.3` release, the issue is still happening.

**Comment by rickymarcon** [comment]
Confirmed still an issue in `@chakra-ui/react@2.2.3` as well

**Comment by MasashiSalvador57f** [comment]
still happening @chakra-ui/react@2.2.3 any updates?

**Comment by MincePie** [comment]
Is there an update on a resolution to this issue? It is still happening.

**Comment by jmcoder1** [comment]
Still happening

**Comment by woodjs** [comment]
I am seeing this issue when using Accordion child components
