### ISSUE TITLE
Update Popover to support styling (or removing) animations

### ISSUE THREAD

**Issue by mix3d** [chakra-ui/chakra-ui#5843]
### Description

The current Popover system has a baked in animation / transition for show/hide. This makes is very difficult for a developer to modify it. Having an API with which to provide animations to would be extremely helpful, and having such a system would also allow for turning _off_ the transition as well. 

### Problem Statement/Justification

For a given "copy this existing site" implementation, I need to remove the transition animations from Popover.

I would expect someone who is trying to match a specific transition / animation style would also run into this problem. 

### Proposed Solution or API

unsure, I can't even find in the ChakraUI code where the transition animation is set. 

### Alternatives

Asking on the Discord channel suggested adding hardcoded CSS overrides,  `opacity="1 !important"` and `transform="none !important"` as the only way to override the existing behavior.

**Comment by mix3d** [comment]
I have done more digging through the codebase, and it turns out there's a <PopoverTransition> component that is automatically wrapped around the <PopoverContent>'s children, which seems responsible for the animation. The Documentation does not mention that the PopoverContent component forwards a `variants` prop to this component. 

Playing around, however, it doesn't seem like it takes the content verbatim, and I've had trouble overwriting the default behavior. With the below example, the standard ScaleFade still applies somehow. 

EG:

```JSX
// expect this to have zero animation
const noAnim = {
     exit: {},
    enter: {}
}

...

return (<Popover>
  <PopoverTrigger>
    <Button>Click me</Button>
  </PopoverTrigger>
  <PopoverContent variants={noAnim}>
    <PopoverHeader fontWeight="semibold">Popover placement</PopoverHeader>
    <PopoverArrow />
    <PopoverCloseButton />
    <PopoverBody>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore.
    </PopoverBody>
  </PopoverContent>
</Popover>)

```

**Comment by pedrowindisch** [comment]
You can turn off the popover show/hide animation by sending an empty object as the `variants` prop. You can also override the default animation the same way.

The `variants` prop is actually part of the framer-motion package ([docs here](https://www.framer.com/docs/animation/#variants)).

[CodeSandbox example](https://codesandbox.io/s/relaxed-khayyam-wx17e5?fontsize=14&hidenavigation=1&theme=dark)

**Comment by mix3d** [comment]
Perhaps I should open a ticket with the docs side instead.

**Comment by mix3d** [comment]
@pedrowindisch I think there is a clear lack of documentation about WHAT props go to framer and what don't, and which components USE framer, as well as an issue I've identified already #5883 that still prevents proper framer integration.

**Comment by bosworthco** [comment]
I feel like this is semi related to the issues we're facing in #6189
