### ISSUE TITLE
Children typing for PopoverTrigger which will support @types/react 18.0.0 along with backwards compatibility 

### ISSUE THREAD

**Issue by pomSense** [chakra-ui/chakra-ui#5844]
### Description

The PopoverTrigger does not provide typing to support the upcoming react 18.0.0 types. This issue serves to provide support for @types/react 18.0.0 in addition to backward compatibility. 

If the below solution is suitable, I'll link a PR to it. Please provide me feedback on the proposed solution below, specifically on other props if needed, or let me know if it is too early for this, and I can close it out.

### Problem Statement/Justification

With @types/react 18, implicit children are removed. The current PopoverTrigger has implicit children, and although they are convenient, they can lead to hard-to-detect bugs. Furthermore, this functionality will break in typescript projects with React 18. 

Error with using PopoverTrigger with @types/react 18:
```
Type '{ children: any; }' has no properties in common with type 'IntrinsicAttributes'.
```

### Proposed Solution or API

Provide single react element, string, or number type for PopoverTrigger children:

```ts
interface PopoverTriggerProps {
  /**
   * The React child to use as the
   * trigger for the popover
   */
  children: React.ReactChild
}

export const PopoverTrigger: React.FC<React.PropsWithChildren<PopoverTriggerProps>> = (props) => {
  // enforce a single child
  const child: any = React.Children.only(props.children)
  const { getTriggerProps } = usePopoverContext()
  return React.cloneElement(child, getTriggerProps(child.props, child.ref))
}
```

### Additional Information

- [React 18 removal of implicit children](https://solverfox.dev/writing/no-implicit-children/)
- [React 18 type changes](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210)

**Comment by mdddj** [comment]
+1

**Comment by kogovsekm** [comment]
+ 1

**Comment by gmatthewsfeuer** [comment]
+1

**Comment by MSSPL-KamalenduGarai** [comment]
+1

**Comment by lucasruy** [comment]
Is there any workaround to avoid this issue?
