### ISSUE TITLE
Bug: Component styles overrides in theme for the Text component are not respected

### ISSUE THREAD

**Issue by wuweiweiwu** [chakra-ui/chakra-ui#5848]
### Description

When I set the `defaultProps` in the component styles overrides for the `Text` component, I expected a `Text` component to have those props set to the default value. Instead, any component styles set for `Text` in my theme are not respected.

Other fields such as `baseStyles` are also not respected.

Related to https://github.com/chakra-ui/chakra-ui/issues/3884

### Link to Reproduction

https://codesandbox.io/s/text-default-props-dont-work-prpbqj

### Steps to reproduce

1. The `Default Text` shown in the codesandbox should inherit the default prop `textStyle="title"`

### Chakra UI Version

1.8.8

### Browser

All

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @wuweiweiwu,

The idea behind `defaultProps` for component themes is to set the default variant, size, and colorScheme of the component **NOT** to set the general default props.

You can achieve that with classic React's `Component.defaultProps = {}` pattern

```jsx
Text.defaultProps = {
  textStyle: "title"
}
```
