### ISSUE TITLE
Using InputRightElement with InputRightAddon leads to overlapping icons

### ISSUE THREAD

**Issue by takethefake** [chakra-ui/chakra-ui#5849]
### Description

When I use `InputRightElement` with `InputRightAddon` the elements overlap. 

<img width="441" alt="Screenshot 2022-04-10 at 11 14 38" src="https://user-images.githubusercontent.com/3123354/162611325-c6016633-6d2c-4cf2-a785-e918ec9c57e2.png">

I would expect them to align accordingly.

<img width="430" alt="image" src="https://user-images.githubusercontent.com/3123354/162610787-79f045bc-be24-4bed-81c9-c5e616599a50.png">

This happens because `InputRightElement` positions `absolute` with `right:0` A possible fix for this is to get a reference to `InputRightAddon` and change the `InputRightElement` `right` property to the retrieved value. 

I wonder if we can find a way to integrate this inside `InputGroup` by defining an `InputGroupProvider` that provides four functions:

- getLeftElementProps
- getLeftAddonProps
- getRightElementProps
- getRightAddonProps

Within those, we populate the references for the Addon components and if the respective Element Component exists as well, we then add the `left`/`right` property.

What do you think @segunadebayo @TimKolberger ?

### Link to Reproduction

https://codesandbox.io/s/silent-glitter-yz8o1n?file=/src/index.tsx

### Chakra UI Version

1.8.8

**Comment by segunadebayo** [comment]
Hi @takethefake,

I'd leave this to the user to fix in their app code. I'd like to reduce the "magic" we do within the code to fix a trivial problem like this.

Thanks for understanding.

**Comment by HenrikBechmann** [comment]
Just so you know I've spent hours trying to figure out why the InputLeftElement and Input sit on top of each other. As you can see I'm experimenting.

I still have no clue what's going on.

~~~
<FormControl>
  <FormLabel size = 'sm'>Padding and gaps</FormLabel>

 <InputGroup id = 'padding' size = 'sm' >
      <InputLeftElement as = 'span' width = 'auto' id = 'padding' children = 'Padding' />
       <Input id = 'padding' width = '30%' type = 'number' />
</InputGroup>
</FormControl>
~~~
<img width="314" alt="Screen Shot 2022-10-17 at 5 46 11 PM" src="https://user-images.githubusercontent.com/4584381/196290462-598f1f35-5b4b-4e48-a65c-70287d0accea.png">

**Comment by HenrikBechmann** [comment]
Well, I came up with this:

~~~
<FormControl>
   <FormLabel size = 'sm'>Padding and gaps</FormLabel>
    <HStack>
       <InputGroup size = 'sm' flexGrow = {1}>
          <FormLabel fontSize = 'sm'>Padding:</FormLabel>
          <Input type = 'number' />
       </InputGroup>
       <InputGroup size = 'sm' flexGrow = {1}>
          <FormLabel fontSize = 'sm'>Gaps:</FormLabel>
          <Input type = 'number' />
        </InputGroup>
     </HStack>
     <FormHelperText>
            Integers. Padding applies to the scroller borders; gaps apply to the space between cells.
      </FormHelperText>
</FormControl>
~~~

I take it we're kind of on our own to figure things out.

I still haven't found a list of props for `InputGroup`

**Comment by rtman** [comment]
in the interest of saving other people time, you can set a ref to the rightAddon and use that refs offsetWidth property to then adjust the absolute position of the rightElement.

**Comment by DonaldTaylor** [comment]
I agree that this is a bug.

However, the easiest workaround is to wrap multiple `InputGroups`:

`
  <InputGroup>
    <InputGroup>
      <Input />
      <InputRightElement>
      {/* right element */}
      </InputRightElement>
    </InputGroup>
    <InputRightAddon>
      {/* right add-on element */}
    </InputRightAddon>
  </InputGroup>
`
