### ISSUE TITLE
[IconButton] Seeing warnings in console when using parameterized variantColor

### ISSUE THREAD

**Issue by Premkumar-Shanmugam** [chakra-ui/chakra-ui#585]
**Describe the bug**
Every time the browser renders the IconButton, it throws a warning in the console which expects the component to use hard-coded color value from the the theme object.
![image](https://user-images.githubusercontent.com/28890016/78674940-fc1e6500-7901-11ea-8c71-732c0d6a25f2.png)

**Expected Behavior**
Component is rendered without any warning.

**To Reproduce**
```
const { colorMode, toggleColorMode } = useColorMode();
const bgColor = { light: 'purple.100', dark: 'purple.700' };
const textColor = { light: 'purple.800', dark: 'white' };
.
.
.
<IconButton
  onClick={toggleColorMode}
  icon={colorMode === 'light' ? 'moon' : 'sun'}
  color={textColor[colorMode]}
  variantColor={bgColor[colorMode]}
>
```
**Suggested solution(s)**
No idea

**Desktop (please complete the following information):**
 - Windows10
 - Chrome
 - Version 80

**Additional context**
None.

**Comment by segunadebayo** [comment]
Hi @Premkumar-Shanmugam,

I think you have an error in your code. Did you mean to do this?

```jsx
const { colorMode, toggleColorMode } = useColorMode();
const bgColor = { light: 'purple.100', dark: 'purple.700' };
const textColor = { light: 'purple.800', dark: 'white' };

<IconButton
  onClick={toggleColorMode}
  icon={colorMode === 'light' ? 'moon' : 'sun'}
  color={textColor[colorMode]}
  bg={bgColor[colorMode]}
>
```

I believe you meant to pass the `bg` prop not `variantColor`. `variantColor` only accepts the color keys not the specific color.

Hope this helps

**Comment by Premkumar-Shanmugam** [comment]
You are right. Thank you @segunadebayo 👍
