### ISSUE TITLE
css grid placeItems does not pass to the element

### ISSUE THREAD

**Issue by lishine** [chakra-ui/chakra-ui#586]
https://codesandbox.io/s/determined-butterfly-nse92

**Comment by segunadebayo** [comment]
Hi @lishine,

At the moment, we don't have support for the `placeItems` style prop.

You can some walkarounds:
- Use `alignItems` and `justifyItems` style prop
- Use the regular jsx `style` attribute
- Use the `css` prop from `@emotion/core`.

In the upcoming release, we've added support for `placeItems`.

Thanks
