### ISSUE TITLE
Skeleton Animation fails when rendered as Tr (table row)

### ISSUE THREAD

**Issue by ogheneovo12** [chakra-ui/chakra-ui#5861]
### Description

Skeleton Animation fails when rendered as Tr, it just makes the component blank white

### Link to Reproduction

https://codesandbox.io/s/intelligent-sanderson-ul3hdj?file=/src/index.js

### Steps to reproduce

```
<Skeleton
       cursor={"pointer"}
         // _hover={{ bg: "#FFF" }}
          borderBottom={"1px solid #E8E9EB"}
          as={"tr"}  
          isLoaded={false}></Skeleton>
```

### Chakra UI Version

^1.0.0

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Instead of the animation, a Tr with visibility hidden is rendered, basically white empty tr is rendered

**Comment by segunadebayo** [comment]
Hi @ogheneovo12,

I think this is the wrong usage of the Skeleton component. I'll recommend showing the skeleton within else data cell rather than making the entire row a skeleton element.

Thanks for understanding.
