### ISSUE TITLE
Make `placeholder` of `Select` unselectable

### ISSUE THREAD

**Issue by ahmedelq** [chakra-ui/chakra-ui#5863]
### Description

When I fill the `placeholder` prop of the `Select` I get extra unwanted element.
![image](https://user-images.githubusercontent.com/11134754/163136696-3d734716-398c-485f-b74e-2a590585010d.png)

Better is to have it only as a hint  not option, and when the user clicks it fades:
![image](https://user-images.githubusercontent.com/11134754/163137233-5cb3d671-bbe4-4057-bd26-12900e9950df.png)
![image](https://user-images.githubusercontent.com/11134754/163137617-2ff55100-23ae-4c7c-ba5e-79268fbaf140.png)

### Problem Statement/Justification

According to MDN, a placeholder is a "string that provides a brief hint to the user". However, when used with select it provides an extra unwanted `option` element. It must not be included in the user's options. 

### Proposed Solution or API

Just add `disabled hidden` attribute to the placeholder option tag.

**Comment by segunadebayo** [comment]
Hi @ahmedelq,

This is by design. The issue with this approach is that when the select is an optional field and the user selects an option, they can't undo the action by going back to the placeholder. They're forced to pick a value.

I'd recommend keeping this fix to the user-land code. You can achieve that by not passing the `placeholder` prop and adding an extra option:

```jsx
<Select>
  <option selected hidden disabled value="">Placeholder</option>
  { /* ... */ }
</Select>
```

Thanks for understanding.

**Comment by g1st** [comment]
React throws a warning with the suggested solution:

```
Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
```

**Comment by poengen** [comment]
> React throws a warning with the suggested solution:
> 
> ```
> Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
> ```

I found that removing the `selected` attribute on the `option` tag removes the error.
