### ISSUE TITLE
customizing width of AvatarBadge in theme don't work

### ISSUE THREAD

**Issue by jaemushim** [chakra-ui/chakra-ui#5888]
### Description

when i customizing avatarBadge'styles in theme, 'color', 'padding' is work but 'bg', 'width', 'height" don't.

### Link to Reproduction

https://codesandbox.io/s/fervent-snow-4biwwb?file=/src/index.js

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

1.6.4

### Browser

chrome 93

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @jaemushim,

This isn't working because of how you set it up.

```diff
  <Avatar>
-        <AvatarBadge boxSize="1.25em" bg="green.500">
+        <AvatarBadge>
          5
        </AvatarBadge>
      </Avatar>
```

Here's a working version:
https://codesandbox.io/s/frosty-https-rnnhky?file=/src/index.js

**Comment by jaemushim** [comment]
> Hi @jaemushim,
> 
> This isn't working because of how you set it up.
> 
> ```diff
>   <Avatar>
> -        <AvatarBadge boxSize="1.25em" bg="green.500">
> +        <AvatarBadge>
>           5
>         </AvatarBadge>
>       </Avatar>
> ```
> 
> Here's a working version: https://codesandbox.io/s/frosty-https-rnnhky?file=/src/index.js

Thanks..!!! segunadebayo
I appreciate you and chakra.
