### ISSUE TITLE
Full size Modal glitch on latest Safari versions

### ISSUE THREAD

**Issue by mihaichiciu** [chakra-ui/chakra-ui#5889]
### Description

When I open a full sized modal on the latest version of Safari (Safari 14 & 15) & iOS (iOS 14 & 15) and I scroll down, there is a glitch where it displays the content behind the modal.

### Link to Reproduction

https://chakra-ui-git-fix-modal-height-ios-chakra-ui.vercel.app/docs/overlay/modal#modal-sizes

### Steps to reproduce

On an iPhone

1. Go to [jurata.ch](https://www.jurata.ch/)
2. Click on the burger menu on top right to open the modal, when using an iOS device / Browserstack for mobile devices.
3. Scroll down inside the modal.
4. See the glitch of the page content that is displayed for a split second.

### Chakra UI Version

1.6.12

### Browser

Safari 14 & 15

### Operating System

- [x] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I found a PR that solved height calculation on iOS devices [#3806](https://github.com/chakra-ui/chakra-ui/pull/3806), but I am not sure if it is related to this one.
This issue takes place on our production environment, so you can check it out there. I have also provided a video that showcases the bug.

https://user-images.githubusercontent.com/52376898/163783332-1cdb6e5a-a541-4c43-8ea6-fba0ad43fb6d.MP4

**Comment by tokai-son** [comment]
the same problem for me

**Comment by shyam-whatmore** [comment]
I am also facing this issue in production for Safari browser, this issue is reproduced with the full modal example in chakra's documentation https://chakra-ui.com/docs/components/modal. Try opening the full modal example in Safari Mobile.

**Comment by JordenLCH** [comment]
I face this issue too

**Comment by cichien** [comment]
I also has issue too

**Comment by Ra0R** [comment]
Same issue

**Comment by Ra0R** [comment]
Seems to be fixed in Chakra version ^2.35

**Comment by shyam-whatmore** [comment]
We moved to using [React-Modal](https://www.npmjs.com/package/react-modal), it's working well in IOS. The interface is almost very similar, except the close-button and slide-in animations have to be implemented, which is not hard as they offer easy overriding of css styles.

**Comment by shyam-whatmore** [comment]
@segunadebayo The solution seems to be using  'height: 100vh !important;' CSS property for the modal element. This is a visible viewport related, iOS specific requirement and same works well for Android too.

**Comment by thiagobutignon** [comment]
I still have this issue

**Comment by PhelixTaken** [comment]
I also have the issue. Would really like to know how to fix it.

**Comment by moshekrup** [comment]
I still have the issue in version 2.4.1
