### ISSUE TITLE
[Modal] State change of a parent causes modal to close

### ISSUE THREAD

**Issue by MrLemur** [chakra-ui/chakra-ui#589]
**Describe the bug**
When a modal is a child of a component with state, if the parent's state changes then the modal will close. (chakra-ui/core 0.7.0)

**Expected Behavior**
State should be able to change without changing the modal's `isOpen` prop.

**To Reproduce**
- Use this template:
- List the steps to reproduce the behavior:
1. Go to https://codesandbox.io/embed/nostalgic-euler-b3bj6?fontsize=14&hidenavigation=1&theme=dark - notice state is 0
2. Click on Open Modal
3. Click on Change State
4. State changes to 1 and the modal closes

**Suggested solution(s)**
Modal should keep its open or close state regardless of state change on other components unless directly linked

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 80.0.3987.183

**Additional context**
Would be good to know if this is expected behaviour, and a Modal component just needs to be siblings with a component with state instead of a child.

**Comment by segunadebayo** [comment]
Hi @MrLemur,

This is happening because you have `useDisclosure` inside the `BasicUsage` Component, so when it re-renders everything including `useDisclosure` re-renderers.

Lift the state up and outside `BasicUsage` and it should work as expected.

Hope this helps.

**Comment by MrLemur** [comment]
Many thanks! I wasn't too sure based on examples in the docs, but this is crystal clear :)
