### ISSUE TITLE
Responsive styles

### ISSUE THREAD

**Issue by RadovanPelka** [chakra-ui/chakra-ui#5893]
### Description

Not working responsive styles in theme.variant

### Link to Reproduction

https://codesandbox.io/s/staging-paper-p0h3nz?file=/src/index.js

### Steps to reproduce

Hey guys, please can you help?

Theme.variant needs option null to set 2diff styles (mobile version and mobile up) 
![image](https://user-images.githubusercontent.com/29738200/163846608-261e80ee-3eac-4d9c-a818-dcaa920b97e8.png)

and grid no ?

![image](https://user-images.githubusercontent.com/29738200/163846641-9d56e197-1716-407f-92f5-925588b6a539.png)

Why? isn't that a bug?
@segunadebayo 

### Chakra UI Version

latest

### Browser

all

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Hi @RadovanPelka,

This is happening because of the way the default theme for the heading component was created. The default `sizes` is affecting the styles.

Here are 2 ways to resolve this:

- Use `sizes` instead of `variants` to define the override:

```jsx
const components = {
  Heading: {
    baseStyle: { fontWeight: "600, Semi Bold" },
    sizes: {
      h1: {
        fontSize: ["1rem", "6rem", null] // remove null and try to change page width
      }
    }
  }
};
```

- Keep it as `variants` and set the `defaultProps` for `size` to be `null`

```jsx
const components = {
  Heading: {
    defaultProps: {
      size: null
    },
    baseStyle: { fontWeight: "600, Semi Bold" },
    variants: {
      h1: {
        fontSize: ["1rem", "6rem", null] // remove null and try to change page width
      }
    }
  }
};
```
