### ISSUE TITLE
TypeError: `Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes'` on `PopoverTrigger`

### ISSUE THREAD

**Issue by jonahallibone** [chakra-ui/chakra-ui#5896]
### Description

When I use a `PopoverTrigger`, I get a TypeError for the children

### Link to Reproduction

NA

### Steps to reproduce

1. Create a Popover in a project using TS
2. Insert a `Button` in the trigger
3. See error `Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes'.`

<img width="980" alt="Screen Shot 2022-04-18 at 6 10 58 PM" src="https://user-images.githubusercontent.com/8886318/163885621-d8efbc31-d1c2-4885-a0b0-d304798364c6.png">

### Chakra UI Version

1.8.8

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by nftgeek** [comment]
Hi @jonahallibone  are you using react 18?

**Comment by RobinUndersigned** [comment]
Got the same problem with React 18. I guess we need to wait for an Update on this?

**Comment by Shing-Ho** [comment]
It's because of the types of React 18 issues maybe. Try `yarn why @types/React` and check if there are two versions for it.

**Comment by adrian-amigues** [comment]
Hi, I'm encountering the same issue after upgrading to react 18. I have the latest versions for `@types/react` (18.0.5) and `@types/react-dom` (18.0.1).

It seems there was a PR for this (https://github.com/chakra-ui/chakra-ui/pull/5845) but it got closed in favor of a broader react-18 related updates (https://github.com/chakra-ui/chakra-ui/pull/5856). Maybe the Popover update was forgotten somehow? 

It seems the problem comes from the react-18 update in how `React.FC` is typed, as doesn't include `children` anymore

**Comment by TylerAPfledderer** [comment]
This was discussed on Discord and determined it was React 18 that was installed and causing the error. This issue should be closed, as reverting to the previous version will solve the problem.

**Comment by parth-decodes** [comment]
> <{ children: React.ReactNode }>


> Temp patch:
> 
> ```
> 
> import {
>   PopoverTrigger as OrigPopoverTrigger
> } from '@chakra-ui/react'
> 
> export const PopoverTrigger: React.FC<{ children: React.ReactNode }> =
>   OrigPopoverTrigger
> ```

Thanks a lot

**Comment by PrashantIndurkar** [comment]
> Temp patch:
> 
> ```
> 
> import {
>   PopoverTrigger as OrigPopoverTrigger
> } from '@chakra-ui/react'
> 
> export const PopoverTrigger: React.FC<{ children: React.ReactNode }> =
>   OrigPopoverTrigger
> ```

Thanks it works

**Comment by Royalcrist** [comment]
I fixed this error changing in the `tsconfig.json` the value `esModuleInterop` from `false` to `true` and I set the `moduleResolution` to `bundler`
