### ISSUE TITLE
How to use toast outside of component? 

### ISSUE THREAD

**Issue by huanlirui** [chakra-ui/chakra-ui#5901]
#### Can officials provide similar support ？

```
import { Toast } from '@chakra-ui/react';

 Toast.error({title:'error'});

 Toast.info({title:'info'});

 Toast.success({title:'success'});

```

**Comment by tomhicks** [comment]
https://chakra-ui.com/docs/components/feedback/toast#:~:text=Use%20createStandaloneToast%20to%20create%20toasts%20from%20outside%20of%20your%20React%20Components.

This is specifically dealt with in the docs.

**Comment by huanlirui** [comment]
> https://chakra-ui.com/docs/components/feedback/toast#:~:text=Use%20createStandaloneToast%20to%20create%20toasts%20from%20outside%20of%20your%20React%20Components。
> 
> 这在文档中专门处理。

thanks!!
