### ISSUE TITLE
Ability to add switches and other types of items to a Menu

### ISSUE THREAD

**Issue by chrysb** [chakra-ui/chakra-ui#5904]
### Description

I'd like to be able to add other items to the menu component. Not every item needs to be clickable. This would allow for richer menu interactions, for example:

<img width="217" alt="image" src="https://user-images.githubusercontent.com/120388/164349567-29d9e276-29dd-4022-acc5-8891842225cd.png">

### Problem Statement/Justification

Menus are sometimes more than just a list of clickable items, and this would make Chakra even more powerful.

### Proposed Solution or API

Perhaps add an `isInteractive` flag that disables the normal clicking behavior

```
              <MenuList>
                <MenuItem isInteractive>
                  <Flex justifyContent='space-between'>
                    <Text>Dark mode</Text>
                    <Switch />
                  </Flex>
                </MenuItem>
                <MenuItem onClick={onSignOut}>Sign out</MenuItem>
              </MenuList>
```

**Comment by mnickkk** [comment]
@chrysb wouldn't 
```
<MenuItem as={Switch}>DarkMode</MenuItem>
```
work for you?
