### ISSUE TITLE
Avatar component  show questionmark if "name" props start with emoji.

### ISSUE THREAD

**Issue by mhjariwala** [chakra-ui/chakra-ui#5905]
### Description

If There is no avatar image available then In this case, If there was name property provided then, Avatar component split firstName and lastName and show first letter of both variable. If the name starts with emoji in that case, Avatar component show question mark if the user system has no unicode for that emoji. Example of the string: "🎻 The Wong Family"

### Link to Reproduction

https://codesandbox.io/s/vibrant-bohr-cgek9y?file=/src/app.js

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

1.8.8

### Browser

Google chrome: Version 100.0.4896.127

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

![Screenshot 2022-04-21 122539](https://user-images.githubusercontent.com/24501581/164392656-b608b8ac-89eb-4e67-bbbb-9ed234df26aa.png)

**Comment by mhjariwala** [comment]
@segunadebayo , We can use following code to avoid display of question mark if the name contain emoji as first letter.

`function initials(name: string) {
  const [firstName, lastName] = name.split(" ")
  const firstNameLetterUnicode = firstName?.codePointAt(0);
  const lastNameLetterUnicode = lastName?.codePointAt(0);
  const firstNameLetter = firstNameLetterUnicode ? String.fromCodePoint(firstNameLetterUnicode) : '';
  const lastNameLetter = lastNameLetterUnicode ? String.fromCodePoint(lastNameLetterUnicode) : '';

  return firstNameLetter && lastNameLetter
    ? `${firstNameLetter}${lastNameLetter}`
    : firstNameLetter
}`

github avatar.tsx:
https://github.com/chakra-ui/chakra-ui/blob/next/packages/avatar/src/avatar.tsx#L105

**Comment by segunadebayo** [comment]
Hi @mhjariwala,

The Avatar component exposes a way to customize the initials. `getInitials` is a function that provides the name and allows you to customize what it rendered.

```
<Avatar name="🎻 The Wong Family" getInitials={() => "🎻 T"} />
```

**Comment by mhjariwala** [comment]
Got it. @segunadebayo , Thank you so much for your reply.
