### ISSUE TITLE
Wrap: `spacingX={0}` resulting in no spacing for `spacingY`

### ISSUE THREAD

**Issue by OmarZeidan** [chakra-ui/chakra-ui#5907]
### Description

For the `<Wrap>` component, I expect the `spacingY` to not be affected if I state the `spacingX={0}`

### Link to Reproduction

https://codesandbox.io/s/spacingy-issue-dvnujw

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

latest

### Operating System

- [x] macOS
- [x] Windows
- [x] Linux

**Comment by OmarZeidan** [comment]
The reason for that is the `{0}` will reach as a number 0, resulting an error with the margin `calc()` function

see, https://github.com/chakra-ui/chakra-ui/blob/next/packages/layout/src/wrap.tsx#L82

A proper consumer fix would be: 

```tsx
<Wrapper spacingX={"0px"} spacingY={4}>
...
</Wrapper>
```

instead of 

```tsx
<Wrapper spacingX={0} spacingY={4}>
...
</Wrapper>
```

Another possible fix would be checking if the value is zero from https://github.com/chakra-ui/chakra-ui/blob/next/packages/layout/src/wrap.tsx#L82 and change the `margin` to `marginY` and/or `marginX`

**Comment by Rafael-Ramblas** [comment]
+1
