### ISSUE TITLE
Add  Referrer-Policy prop to Avatar & Image Components

### ISSUE THREAD

**Issue by koester** [chakra-ui/chakra-ui#5909]
### Description

I noticed an issue with `referrer-policy: origin` (default) and images from `googleusercontent.com`. Sometimes, not always, the request will be blocked with a status 403 code, resulting in rendering the fallback instead of the requested image.

In my testing I found that this is resolved by adding `referrer-policy="no-referrer"` to the resulting html `<img>` tag.

Since this problem happens so irregular I'm also not quite sure yet if this is caused by my Nextjs + Chakra setup, or if its a general issue. If its not a general problem but downstream related to Nextjs, please feel free to close this issue.

### Problem Statement/Justification

Google likes to return a 403 status code when you try to use googleusercontent.com as a src for Avatar / Image components., basically blocking your request even if the source is valid and can be opened in a new tab, resulting in the fallback being rendered instead of the actual image.
 
To control this on a component level I propose to add an optional prop for `referrerpolicy` on these two components.

### Proposed Solution or API

Add support for `referrerPolicy` (or maybe just `policy`) as an optional prop for Avatar / Image and pass it down to the rendered `<img>` tag.

```tsx
<Avatar referrerPolicy="no-referrer" src="https://lh3.googleusercontent.com/a-/AOh14GiHdBn5xmhJ8eQHJHMsDtadvtAgls7NpRb7BWq2=s96-c" name="Fall Back"  />
<Image referrerPolicy="no-referrer" src="https://lh3.googleusercontent.com/a-/AOh14GiHdBn5xmhJ8eQHJHMsDtadvtAgls7NpRb7BWq2=s96-c" alt="Fall Back"  />
```
Expected Output:
```html
<img referrerpolicy="no-referrer" src="https://lh3.googleusercontent.com/a-/AOh14GiHdBn5xmhJ8eQHJHMsDtadvtAgls7NpRb7BWq2=s96-c" alt="Fall Back" class="chakra-classes"  />
```

Since this should be an optional prop not passing anything results in the same rendered HTML as it is right now.

For the list of valid values for this prop see: [Referrer Policy Reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy)

### Alternatives

Using `<meta name="referrer" content="no-referrer" />` to set this globally for the whole HTML. This does stop the problem from happening, but might not be viable for all users / use cases.

I think it would be cleaner to allow users to set this at the component level, when and where it is needed.

**Comment by Marchelllo27** [comment]
In 2022 for MUI Avatar Component you should provide it like this: 

`  <Avatar src="..." alt="fallback" imgProps={{ referrerPolicy: "no-referrer" }} />;`

**Comment by innovatorved** [comment]
I am also suffering with this issue anyone please tell me what to do?

**Comment by creme332** [comment]
For mantine v6, you need to use `imageProps` instead of `imgProps`:
```js
  <Avatar src="..." alt="..." imageProps={{ referrerPolicy: "no-referrer" }} />;
```
https://mantine.dev/core/avatar/?t=props

**Comment by biigpongsatorn** [comment]
Update April 2024.

The use of `imgProps` has been deprecated, and we are now required to use `slotProps` instead.

```jsx
<Avatar
  alt={userInfo?.fullName}
  src={userInfo?.profilePicture}
  sx={{ width: "40px", height: "40px" }}
  slotProps={{ img: { referrerPolicy: 'no-referrer' } }}
/>
```
