### ISSUE TITLE
ColorModeScript does not read from LocalStorage (locally ONLY)

### ISSUE THREAD

**Issue by captain-woof** [chakra-ui/chakra-ui#5911]
### Description

When I toggle the color mode to `dark`, it does toggle, both visually and in LocalStorage, but reloading the page shows the `light` theme although local storage still has `dark`.

**This happens only on the local dev server.**

### Link to Reproduction

```
pnpm run dev
```

### Steps to reproduce

*Using Next.js*

1. Create a theme, like:
```ts
const theme = extendTheme(
    {
        colors: {
            green: greenHue,
            blue: blueHue,
            red: redHue,
            orange: orangeHue
        },
        fonts: {
            body: "'Noto Sans', sans-serif",
            heading: "'Josefin Sans', sans-serif",
            mono: "'Oxygen Mono', monospace",
        },
        components: {
            Button: componentStyles.buttonStyle
        },
        config: {
            initialColorMode: "light",
            useSystemColorMode: false
        }
    },
    withDefaultColorScheme({ colorScheme: "green" })
) as Theme;
```

2. Add `ColorModeScript` to `document.tsx` like:
```tsx
   <body>
       <ColorModeScript initialColorMode={theme.config.initialColorMode} />
       <Main />
       <NextScript />
   </body>
```
   
3. Add `ChakraProvider` to `_app.tsx` like:
```tsx
import type { AppProps } from 'next/app';
import { ChakraProvider } from '@chakra-ui/react';
import theme from '../theme';
import AppBar from '../components/organisms/appbar';
import { Provider as ReduxProvider } from "react-redux";
import { store } from "../store";

function OnenessApp({ Component, pageProps }: AppProps) {
  return (
    <ReduxProvider store={store}> // For state management
      <ChakraProvider theme={theme}>
        <AppBar />
        <Component {...pageProps} />
      </ChakraProvider>
    </ReduxProvider>
  )
}

export default OnenessApp;
```

4. Try to toggle the theme now.

### Chakra UI Version

1.8.8

### Browser

Google Chrome 99.0.4844.84 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Here's the repo for the app's source code: [Project Oneness](https://github.com/captain-woof/oneness).

**Comment by mrcnk** [comment]
Can confirm the issue for macOS and [colorCodeManager guide](https://chakra-ui.com/docs/styled-system/features/color-mode#add-colormodemanager-optional-for-ssr).

**Comment by LeonardSSH** [comment]
Same issue here.

**Comment by rmsramos** [comment]
Same issue here.
