### ISSUE TITLE
<LinkBox> prevents me from selecting options in <Menu>

### ISSUE THREAD

**Issue by hornta** [chakra-ui/chakra-ui#5918]
### Description

When I try to click on options in a `<Menu>` whose options sits above a `<LinkBox>` the click registers on the <LinkBox>

I can get around it by providing a z-index above 1 on the `<MenuList>` like this: `<MenuList zIndex={2}>`

### Link to Reproduction

https://codesandbox.io/s/winter-microservice-u0kf1l?file=/src/index.tsx

### Chakra UI Version

1.8.8

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![Animation (2)](https://user-images.githubusercontent.com/4553604/164788299-50c4265c-af90-4853-8ba4-327e6bd3bb29.gif)

**Comment by TimKolberger** [comment]
I think this was introduced with #5632 to fix #5630.
After this change the issues with the LinkBox increased.

I think we should rollback the zIndex magic and fix the edge cases like #5630 in userland. 
What do you think @m4x3d?

**Comment by m4x3d** [comment]
Yes that is fine for me, especially if there are a lot of issues after the change. The edge case with the opacity for changing the text color in the linked issue is also bad practice in my opinion. I will create a PR to rollback my changes.

Btw: the Menu should also have a zIndex greater than `1`. I guess ~1250 would fit the best according to the [other default zIndex](https://chakra-ui.com/docs/styled-system/theming/theme#z-index-values). Then this Issue would not have been created.
