### ISSUE TITLE
Unexpected error when trying to generate typings for custom theme

### ISSUE THREAD

**Issue by hornta** [chakra-ui/chakra-ui#5919]
### Description

When I run `npx chakra-cli tokens ./src/theme.ts` I'm getting an unexpected error.

### Chakra UI Version

1.8.8

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

@chakra-ui/cli version: 1.9.0

I followed the documentation and no where did it say I have to install the @chakra-ui/styled-system package. 
```
npx chakra-cli tokens ./src/theme.ts

 Chakra UI CLI  v1.9.0 by Chakra UI
Generate theme typings for autocomplete


✖ An error occurred
Could not find @chakra-ui/styled-system in node_modules. Please provide `--out` parameter.
```

```ts
// ./src/theme.ts
import { extendTheme } from "@chakra-ui/react";

const breakpoints = {
  xs: "15em",
  sm: "30em",
  md: "48em",
  lg: "62em",
  xl: "80em",
  "2xl": "96em",
};

export const theme = extendTheme({ breakpoints });
```

Also I'm getting a weird typescript error in my theme.ts, don't know if that's because no typings are generated yet.
![image](https://user-images.githubusercontent.com/4553604/164793730-a8b5db28-5859-4bce-9b09-eb38d2575af0.png)

**Comment by TimKolberger** [comment]
Seems like you are using pnpm - the CLI might not find the correct place to put the generated interface file.

Could you kindly try installing the CLI as dev dependency and running it in a package.json script:

```json
"scripts": {
  "gen:theme-typings": "chakra-cli tokens <path/to/your/theme.(js|ts)>",
  "postinstall": "npm run gen:theme-typings"
},
"devDependencies": {
  "@chakra-ui/cli": "latest"
}
```

FYI: The CLI won't affect the ReturnType of `extendTheme`. It provides better autocomplete for colors, sizes etc when typing style props like `<Box color="gra.."`.

**Comment by JDansercoer** [comment]
@TimKolberger that didn't fix the issue, at least not for me.
To give more context, we are indeed also using `pnpm` but also have it set up as a monorepo, with each project residing inside `packages`.

So we have our frontend in `packages/frontend`. However, with the way pnpm works, it only adds simlinks for actual dependencies.   
With `@chakra-ui/styled-system` not being a direct dependency (but a dependency of `@chakra-ui/react`), this means that `@chakra-ui/styled-system` is not included in `packages/frontend/node_modules`, but only in `node_modules/.pnp/@chakra-ui/styled-system@VERSION`.

I currently had to install `@chakra-ui/styled-system` as a devDependency to get it to work again, but I'm not sure if that's the actual approach we want?

WDYT?
