### ISSUE TITLE
[Stack] Margin-spacing fails when stacked components are imported

### ISSUE THREAD

**Issue by ansonkao** [chakra-ui/chakra-ui#592]
## Expected Behaviour
When the following code runs, it should generate 2 boxes with 100px margin spacing in between them:

`ImportedBox.js:`
```jsx
import { Box } from "@chakra-ui/core";
export const ImportedBox = () => (
  <Box size="md" bg="red.500">
    This Box is indirectly imported
  </Box>
);
```

`Main.js`
```jsx
import { Stack } from "@chakra-ui/core";
import { ImportedBox } from './ImportedBox';

export const Main = () => (
  <Stack spacing="100px">
    <ImportedBox />
    <ImportedBox />
  </Stack>
)
```

## Actual Behaviour:
2 boxes appear but spacing is 0px .

## Workaround:
Wrap extra `<Box>`s around the imported component:

`Main.js`
```jsx
import { Stack } from "@chakra-ui/core";
import { ImportedBox } from './ImportedBox';

<Stack spacing="100px">
  <Box><ImportedBox /></Box>
  <Box><ImportedBox /></Box>
</Stack>
```

**Comment by ansonkao** [comment]
Ah, `shouldWrapChildren` is the solution, found in https://github.com/chakra-ui/chakra-ui/issues/228

**Comment by jonolo6** [comment]
FYI This still seems to be an issue w "@chakra-ui/core": "^0.8.0". Solvable by using another stack without using Fragment though...
