### ISSUE TITLE
[Drawer] "size" props isn't used when placement="top|bottom"

### ISSUE THREAD

**Issue by hornta** [chakra-ui/chakra-ui#5921]
### Description

When I pass a size prop to the drawer I expect it to be sized accordingly to the prop regardless of what the placement prop is

### Link to Reproduction

https://codesandbox.io/s/priceless-benz-rviclr?file=/src/index.tsx

### Chakra UI Version

1.8.8

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![image](https://user-images.githubusercontent.com/4553604/164980104-78e47d1f-6fa0-4a61-a965-76021ef20545.png)

**Comment by hardikhere** [comment]
I'm picking up this issue

**Comment by hardikhere** [comment]
Hi @segunadebayo I need small hint from you, 

I used useDrawerContext in Modal to get to know about placement.  it is working fine for Drawer as it has DrawerProvider but showing an attached error for Modal as it is not wrapped in DrawerContextProvider, any other way to pass placement in Modal (props may cause an issue as this prop should be private)

![unknown (1)](https://user-images.githubusercontent.com/51117080/167073875-296c49c9-cbe2-46ec-ad93-ae24bb57c36e.png)
![unknown](https://user-images.githubusercontent.com/51117080/167073889-fe127f77-2c0c-4fbe-8b1f-48b1994cb942.png)

**Comment by hornta** [comment]
reopen
