### ISSUE TITLE
Support AnimatePresenceProps for Transitions

### ISSUE THREAD

**Issue by MrHeer** [chakra-ui/chakra-ui#5924]
### Description

I want to reset my form field data `onExitComplete`.

https://github.com/chakra-ui/chakra-ui/blob/6551cb9010ac23002782b3820178cfc74c8109a0/packages/transition/src/fade.tsx#L59

### Problem Statement/Justification

None

### Proposed Solution or API

None

**Comment by anubra266** [comment]
Could you add more context and maybe a reproduction @MrHeer, feel free to reopen then. Thanks

**Comment by MrHeer** [comment]
@anubra266 The `AnimatePresence` have some extra [props](https://www.framer.com/docs/animate-presence/#props), like [exitBeforeEnter](https://www.framer.com/docs/animate-presence/###exitbeforeenter). I hope I can use them.

**Comment by anubra266** [comment]
@MrHeer 
![CleanShot 2022-06-06 at 10 54 13@2x](https://user-images.githubusercontent.com/30869823/172138916-b0782985-f89f-440e-ab19-880488575325.png)
