### ISSUE TITLE
[Bug] Color mode in local storage not working after navigation or refresh

### ISSUE THREAD

**Issue by mrcaidev** [chakra-ui/chakra-ui#5925]
### Description

I set `initialColorMode = 'dark'`. When I manually selected my preferred color mode to `'light'`, local storage did remembered my selection; but after a page refresh or navigation, the color mode returned to 'dark', although local storage did indicate `chakra-ui-color-mode === 'light'`.

### Link to Reproduction

https://codesandbox.io/s/competent-firefly-obu73s

### Steps to reproduce

1. In the code sandbox, toggle color mode to 'light' with the button on index page.
2. Now local storage should have an item like 'chakra-ui-color-mode: light'.
4. Navigate to another page with the link on index page.
5. The color mode returns to 'dark'.

### Chakra UI Version

1.8.8

### Browser

Microsoft Edge (100.0.1185.50) (64-bit)

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![image](https://user-images.githubusercontent.com/78269445/165083053-e66c556d-9825-4021-b569-f705fba71c68.png)

When I set breakpoint to watch on every attribute change on `html` element, I saw the `style` attr was always `--chakra-ui-color-mode:dark`, but the `data-theme` attr switched from 'light' to 'dark' on the 3rd break.

![image](https://user-images.githubusercontent.com/78269445/165084656-968935ed-6332-4db8-aa23-81751acf491e.png)

**Comment by aboveyunhai** [comment]
@mrcaidev For next.js you need to add the `colorscript` into the `_document.tsx` file, also turn off the `useSystemColorMode`.
Doc Ref: https://chakra-ui.com/docs/styled-system/features/color-mode#for-nextjs
Also, please read the colormode section behavior really carefully: https://chakra-ui.com/docs/styled-system/features/color-mode#difference-between-initialcolormodesystem-and-usesystemcolormode

example for your intention:
https://codesandbox.io/s/kind-engelbart-1ow5ir?file=/pages/_document.tsx

**Comment by mrcaidev** [comment]
> @mrcaidev For next.js you need to add the `colorscript` into the `_document.tsx` file. Doc Ref: https://chakra-ui.com/docs/styled-system/features/color-mode#for-nextjs Also, please read the colormode section behavior really carefully to check what you are looking for: https://chakra-ui.com/docs/styled-system/features/color-mode#difference-between-initialcolormodesystem-and-usesystemcolormode
> 
> example for your intention: https://codesandbox.io/s/kind-engelbart-1ow5ir?file=/pages/_document.tsx

The sandbox works as expected. But when I pasted your code as-is into a new local project, my color preference still cannot persist between navigation...
I uploaded this local project [here](https://github.com/mrcaidev/chakra-colormode-sandbox). Could you help me find the issue? Thank you!

**Comment by mrcaidev** [comment]
Tried again on Manjaro with the same result :(

**Comment by aboveyunhai** [comment]
@mrcaidev  can confirm is a bug related to Chakra with the latest react 18 version.  If you revert back to 17.0.2 (the latest v17). Everything should work as expect.
Since the newest React version does not significantly affect Chakra UI, I would just recommend you stick with react v17, wait few more minor versions until it's stable to upgrade or the bug is fixed.
You are going to use other packages anyway, all of React-related packages are also facing the same issues most likely.

**Comment by mrcaidev** [comment]
@aboveyunhai Solved! Thanks a lot!

**Comment by HugoFortunato** [comment]
Too late but I resolve this problem change my ``useSystemColorMode: true`` to ``useSystemColorMode: false``.

Reading the doc, I found this observation: 
![image](https://user-images.githubusercontent.com/67443788/221231330-33f26fb8-3555-4cf8-a45f-9af8f3db536f.png)

link: https://chakra-ui.com/docs/styled-system/color-mode
