### ISSUE TITLE
Modal position is affected when a radio button is clicked inside a modal

### ISSUE THREAD

**Issue by jaisharx** [chakra-ui/chakra-ui#5926]
### Description

When a radio button or checkbox is clicked inside a modal which has some long content, the modal position is affected.

### Link to Reproduction

https://chakra-modal-click-inside-issue.vercel.app/

### Steps to reproduce

1. Go to https://chakra-modal-click-inside-issue.vercel.app/
3. Click on any of the modal buttons to open the modal
4. Scroll down to the bottom of the opened modal and click on the radio input
5. You'll see that the modal moves up! It seems the degree to which the modal moves up is related to how much of content is before that input 😅

You can go through the code of the deployed version on the public repo: https://github.com/jaisharx/chakra-modal-click-inside-issue. I've also tried adding a very simple radio group to one of the modals in the chakra docs itself (it happens with scrollBehaviour="inside"), and the issue was reproducible!

<img width="523" alt="Screenshot 2022-04-25 at 6 15 12 PM" src="https://user-images.githubusercontent.com/55892116/165091629-a9f64eba-8a54-485e-87a8-010389b420f0.png">

<img width="1053" alt="Screenshot 2022-04-25 at 6 15 33 PM" src="https://user-images.githubusercontent.com/55892116/165091679-bbfeb29f-0f67-4184-8280-1ad4c0d8bab9.png">

<img width="1792" alt="Screenshot 2022-04-25 at 6 17 05 PM" src="https://user-images.githubusercontent.com/55892116/165091970-179ae5ff-a69d-4c03-a554-996b9615b2da.png">

### Chakra UI Version

^1.8.8

### Browser

Edge 100

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by haneenmahd** [comment]
I have tested it out on macOS safari, it has no problems ✅ .

But Chrome (101.0.4951.41) is also affected❗

### Chrome
https://user-images.githubusercontent.com/72091386/166141434-755db61f-412c-4076-9f57-d698a5b1557d.mov

### Safari
https://user-images.githubusercontent.com/72091386/166141472-158d68b0-f7e6-4f8f-ba8f-82157fb5287f.mov

️

**Comment by jaisharx** [comment]
Yeah on safari weirdly it's not an issue, but on chromium based browsers like I tested on Edge 100, the issue was the same as in your screen recording.

**Comment by haneenmahd** [comment]
It feels weird, gotta do more re-search on this and dive into the code for the modal component.

**Comment by imakero** [comment]
Tabbing to the radio button causes the same behavior so it seems it's not the clicking per se that causes the bug but rather the button receiving focus.

Fwiw, the behavior disappears for me when wrapping the `RadioGroup` with a `FormControl`.

**Comment by jaisharx** [comment]
Yeah putting the inputs inside the ```FormControl``` does fix the issue, does that mean we should always use an input with ```FormControl```? If yes, the docs should explicitly say so and we can close the issue, if not and the input should work either way we can leave this issue open and track it here.

**Comment by navnitInsight** [comment]
I have solution you can try. I think Its focus issue. When last element is focused then Modal logic is failing. 
`     const courseModalDocument = document.querySelector('.course-modal-content')
      if (courseModalDocument) {
          courseModalDocument.focus();
       }`

**Comment by viQcinese** [comment]
Any news on that? I'm having a similar problem of `<Radio />` clicking impacting the scroll of the screen and position of other elements. Tried to prevent default on every possible event and it didn't help.
