### ISSUE TITLE
Subtle variant for button

### ISSUE THREAD

**Issue by jacobhq** [chakra-ui/chakra-ui#5927]
### Description

Adds a new variant to the `Button` and `IconButton` components, which is like the `ghost` variant but with no hover color. It would use a lighter color in dark mode when hovered and a darker color in light mode when hovered, and would keep the same focus ring.

Here's a mockup, which uses opacity changes for time saving purposes.
![image](https://user-images.githubusercontent.com/29145479/165111675-9d2634cf-df7a-4d12-a13b-ef451d6f5d56.png)

**I'd be happy to handle this if someone could give me an overview on how variants could be added.**

### Problem Statement/Justification

![image](https://user-images.githubusercontent.com/29145479/165110287-c23132b8-93f4-4d91-9da0-0e69eee4bb7b.png)
![image](https://user-images.githubusercontent.com/29145479/165110501-f0966743-2691-4894-9543-3e911dab8c07.png)

In a button group, things begin to look weird if you are hovering over a button next to the one you have focused. Adding spacing would not look nice

![image](https://user-images.githubusercontent.com/29145479/165111675-9d2634cf-df7a-4d12-a13b-ef451d6f5d56.png)

This could be solved by adding the proposed `subtle` variant.

### Proposed Solution or API

This new variant would be available by passing the `variant="subtle"` prop to a `Button` or `IconButton` component. It would also work with `ButtonGroup`s.

### Alternatives

- Use a custom theme to add this variant

**Comment by anubra266** [comment]
@jacobhq you can find how to add variants to your components here: https://codesandbox.io/s/peaceful-oskar-4m43wt?file=/src/index.tsx
