### ISSUE TITLE
Stack, Box - Allow scrollSnap Properties

### ISSUE THREAD

**Issue by export-mike** [chakra-ui/chakra-ui#593]
**css scroll snap properties are not being passed down**
Is there a particular way to pass these props down with chakra-ui /styled system utils? 

see example
https://codesandbox.io/s/festive-lake-jpq0x?file=/src/App.js

**Comment by segunadebayo** [comment]
Yes, you can options:

1. Use the native `style` attribute to pass this prop.
2. Use @emotion/core `css` by passing the `css` prop to the component and adding the `jsx` pragma at the top of the file

Hope this helps.

**Comment by RMuradli** [comment]
scroll snap still not working, tried both css and style attributes

**Comment by rwitchell** [comment]
read this to understand how to use scroll snap: https://stackoverflow.com/a/53417516/2926320
