### ISSUE TITLE
Editable - unable to set different placeholder for preview and input

### ISSUE THREAD

**Issue by giero** [chakra-ui/chakra-ui#5931]
### Description

Editable component has a 'placeholder' prop for both preview and input. Is there any way to set those placeholders separately? 'Placeholder' prop is available for EditablePreview and EditableInput, but does nothing for them.

### Link to Reproduction

https://codesandbox.io/s/sharp-brattain-28ss7z

### Steps to reproduce

1) Set 'placeholder' prop separately for EditablePreview and EditableInput
2) Observe it has no impact for any of those

### Chakra UI Version

1.8.8

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
https://stackoverflow.com/a/57800404/9470383

**Comment by thvozdovic** [comment]
Hey,
I'm currently experiencing the same issue, is there any way to display a placeholder on the input only? Directly setting the placeholder prop on the input does not work 😕

**Comment by IronTony** [comment]
I agree that this can be a necessary feature.
An temporary patch can be:
`__css={{
                  '& span': {
                    color: 'var(--chakra-colors-text-tertiary)',
                    opacity: 0.5,
                  },
                }}`
