### ISSUE TITLE
Drawer Component - Cannot set custom background color outside of baseStyle

### ISSUE THREAD

**Issue by alexastef** [chakra-ui/chakra-ui#5936]
### Description

When I create variants for Drawer component, I expect that any background color I set will override the background color set by baseStyle. Aside from setting one background color in baseStyle, I'm unable to set a background color by using variants.

### Link to Reproduction

https://codesandbox.io

### Steps to reproduce

 If I don't set a color for background, chakra's default `bg: mode('white', 'grey')(props)` overrides anything I set by creating variants. I need two variants, one with a white background and grey text, and one with a grey background and dark text. Unless I remove `baseStyles.dialog` entirely, I haven't been able to achieve this (this is not a viable solution). Setting background to null also still ignores the variant background colors.

My Drawer theming:
```
const Drawer = {
  parts: ['dialog', 'header', 'body'],
  baseStyle: {
    dialog: {
      height: '100vh',
      zIndex: 'modal',
      maxH: '100vh',
      boxShadow: 'hover'
    },
    header: {
      color: colors.greyScale['900'],
      textStyle: 'displayXxs',
      py: 6
    },
    body: {
      px: 6
    }
  },
  variants: {
    primary: {
      dialog: {
        background: 'white',
        color: colors.greyScale['500']
      }
    },
    secondary: {
      dialog: {
        background: colors.backgroundScale['50'],
        color: colors.greyScale['900']
      }
    }
  },
  sizes: {
    '2xl': { dialog: { maxH: '100%', maxW: '70%' } },
    '3xl': { dialog: { maxH: '100%', maxW: '80%' } },
    '4xl': { dialog: { maxH: '100%', maxW: '90%' } }
  }
};

export default Drawer;
```
 
My Drawer component:
Note that `sx={styles.dialog}` also didn't work when applied to the Drawer component itself or the DrawerContent component.
```
const styles = useMultiStyleConfig('Drawer', { variant });

  return (
    <Drawer
      closeOnOverlayClick={overlayClose}
      isOpen={isOpen}
      motionPreset={motionPreset}
      placement={placement}
      size={size}
      onClose={() => onClose(props)}
    >
      <DrawerOverlay>
        <DrawerContent __css={styles.dialog}>
          {title && (
            <>
              <DrawerCloseButton />
              <DrawerHeader>{title}</DrawerHeader>
            </>
          )}
          {children}
        </DrawerContent>
      </DrawerOverlay>
    </Drawer>
  );
```

### Chakra UI Version

latest

### Browser

Google Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
Hi @alexastef please create a codesandbox reproduction of this issue.
In the mean time, I tried to reproduce this to my best of understanding the issue, and I couldn't find any issue.
See my coddesandbox here: https://codesandbox.io/s/peaceful-oskar-4m43wt?file=/src/index.tsx
