### ISSUE TITLE
[OpenCollective] Sponsor $100USD/Month refers to Bulma website

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#594]
**Describe the bug**
On your [opencollective site](https://opencollective.com/chakra-ui#section-contribute), the Sponsor section refers to the Bulma homepage. Just a minor copy paste error I suspect :)

**Additional context**
![image](https://user-images.githubusercontent.com/29307652/79006483-8f050c80-7b59-11ea-948b-fe771ed8baa8.png)

**Comment by segunadebayo** [comment]
Thank you for catching this! I've updated it
