### ISSUE TITLE
Checkboxes not working on datatables

### ISSUE THREAD

**Issue by wladiston** [chakra-ui/chakra-ui#5943]
### Description

When I went to the tables components in the docs website and clicked in the checkbox, I was expecting the checkboxes to check and uncheck but it doens't unckeck

### Link to Reproduction

https://pro.chakra-ui.com/components/application/tables

### Steps to reproduce

1. Go to 'https://pro.chakra-ui.com/components/application/tables'
2. Click on 'any checkbox'
3. See error

### Chakra UI Version

idk

### Browser

Brave Version 1.37.116 Chromium: 100.0.4896.127 (Official Build) (x86_64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

https://user-images.githubusercontent.com/1843792/165798672-8a39295e-5f27-46af-88c7-c6150c5141b2.mov

**Comment by noobinthisgame** [comment]
@cschroeter @segunadebayo This seems to be a chakra ui pro issue.

**Comment by TimKolberger** [comment]
If you are a Chakra UI Pro user, kindly raise this issue here: https://github.com/chakra-ui/chakra-pro-issues/issues
Github doesn't let me transfer the issue there.

**Comment by TimKolberger** [comment]
Thanks for resubmitting the issue!

**Comment by kodekage** [comment]
I also experienced this bug too (I'm not a pro user btw) while using chakra in nextjs app.

The wired thing when I running my next app in development mode, everything works fine.

But after building my next app for prod. I noticed this exact checkbox behaviour.

So i'm in a dilemma where checkboxes works on dev but breaks on prod.

**Comment by raphaelrochap** [comment]
Hello, everyone!

Hey @kodekage i have the same issue, an application with Nextjs + Chakraui (free) in development mode the ckeckbox works fine, but in production this problem appears.

I dont know what to do but wait a fix.

**Comment by dz3n** [comment]
> Hello, everyone!
> 
> Hey @kodekage i have the same issue, an application with Nextjs + Chakraui (free) in development mode the ckeckbox works fine, but in production this problem appears.
> 
> I dont know what to do but wait a fix.

go in your next.config.js file and remove `swcMinify` or put it to false

**Comment by lucadibello** [comment]
> I also experienced this bug too (I'm not a pro user btw) while using chakra in nextjs app.
> 
> The wired thing when I running my next app in development mode, everything works fine.
> 
> But after building my next app for prod. I noticed this exact checkbox behaviour.
> 
> So i'm in a dilemma where checkboxes works on dev but breaks on prod.

Same problem as you @kodekage. This is my code just for reference:
```tsx
<Checkbox
    w="full"
    h="full"
    isChecked={checked}
    disabled={
      isCheckboxLoading || data.User.LinkedContactsCompany?.length == 0
    }
    onChange={(e) => {
      // Set local state to avoid flickering
      setChecked(e.target.checked)
      // Update copyTo value
      updateCopyTo(data, e.target.checked)
    }}
/>
```

I'll switch to a simple `Input` component.

**Comment by kodekage** [comment]
> > Hello, everyone!
> > Hey @kodekage i have the same issue, an application with Nextjs + Chakraui (free) in development mode the ckeckbox works fine, but in production this problem appears.
> > I dont know what to do but wait a fix.
> 
> @kodekage, @raphaelrochap go in your next.config.js file and remove `swcMinify` or put it to false

I really don't think this is a good solution. This will disable magnification which isn't the best thing for production.

I was able to fix this issue by upgrading to `@chakra-ui/react` to ` v2.2.6`

Checkbox works fine in that version @lucadibello @dz3n

**Comment by lucadibello** [comment]
Little update: I've created a custom checkbox component using `useCheckbox` hook provided by ChakraUI (https://chakra-ui.com/docs/hooks/use-checkbox).
My component is built around the example shown on the official documentation. I've already tried this component in production and works perfectly!


This is my new component `CustomCheckbox`:
```tsx
interface ICustomCheckboxProps {
  label?: string
  isChecked: boolean
  isDisabled: boolean
  onChange: (_e: ChangeEvent<HTMLInputElement>) => void
}

export const CustomCheckbox = ({
  label,
  onChange,
  isChecked,
  isDisabled,
}: ICustomCheckboxProps) => {
  // Load checkbox hook
  const { state, getCheckboxProps, getInputProps, htmlProps } = useCheckbox({
    isChecked: isChecked,
    isIndeterminate: false,
    isDisabled: isDisabled,
    onChange: onChange,
  })

  // Return checkbox
  return (
    <FormLabel
      display="flex"
      flexDirection="row"
      alignItems="center"
      gridColumnGap={2}
      maxW="36"
      rounded="lg"
      cursor="pointer"
      {...htmlProps}
    >
      <input {...getInputProps()} hidden />
      <Flex
        alignItems="center"
        justifyContent="center"
        border="2px solid"
        borderColor="gray.300"
        w={4}
        h={4}
        {...getCheckboxProps()}
      >
        {state.isChecked && (
          <Icon as={FiCheck} color="white" w={4} h={4} bg="blue.500" />
        )}
        {label && <Text>{label}</Text>}
      </Flex>
    </FormLabel>
  )
}
```

And this is a simple usage example:
```tsx
<CustomCheckbox
  isChecked={checked}
  isDisabled={
    isCheckboxLoading || data.User.LinkedContactsCompany?.length == 0
  }
  onChange={(e) => {
    // Set local state to avoid flickering
    setChecked(e.target.checked)
    // Update copyTo value
    updateCopyTo(data, e.target.checked)
  }}
/>
```
