### ISSUE TITLE
Possible bug with <Select /> component in mobile?

### ISSUE THREAD

**Issue by alveshelio** [chakra-ui/chakra-ui#5944]
### Description

In mobile the options list opens in a completely misplace and it is shrink.

### Link to Reproduction

https://codesandbox.io/s/festive-lake-5vu84x?file=/src/index.tsx&resolutionWidth=320&resolutionHeight=675

### Steps to reproduce

Open the codesanbox, 
Open app in New Window
When in the new window, inspect the page and open the page in mobile view.
Click on the select to open the options

Here's a screenshot of what I get
![image](https://user-images.githubusercontent.com/8176422/165803839-c5aa315d-b437-4126-abcd-501e2a75393c.png)

This behaviour only happens in Chromium based browser. I've tested it in Firefox and Safari and no issues in these two browsers.

### Chakra UI Version

1.8.8

### Browser

Version 100.0.4896.127

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by TimKolberger** [comment]
Did this only occur in the mobile view of Chrome or on an actual mobile device running Chrome as well?

The Select component renders a default HTML select. 
I think this seems like an issue with the mobile view of Chrome, not Chakra UI.
