### ISSUE TITLE
Type support for @chakra-ui/react not working in webstorm (IDE)

### ISSUE THREAD

**Issue by highalps** [chakra-ui/chakra-ui#5957]
### Description

When i use webstorm IDE, @chara-ui/react type supporting not working.

### Link to Reproduction

X

### Steps to reproduce

first, using yarn berry with zero-install 

in package.json

```
"dependencies": {
    ...
    "@chakra-ui/react": "^1.8.8",
    "react": "^17",
    "next": "^12.1.5",
    ...
},
"devDependencies": {
     ...
    "@types/react": "^17",
    "@types/react-dom": "^17",
    "typescript": "^4.6.4",
     ...
}
```

and tsconfig.json

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "noImplicitAny": false,
    "isolatedModules": true,
    "baseUrl": "."
    },
    "jsx": "preserve",
    "incremental": true
  },
  "exclude": [
    "node_modules"
  ]
}
```
(react 18 + apollo client is not compatible, so downgrade to react@17)

and 

`${project_name}/.yarn/cache/@chakra-ui-react-npm-1.8.8-7e22e1d39c-7862b88a23.zip!/node_modules/@chakra-ui/react/dist/declarations/src/index.d.ts`

![image](https://user-images.githubusercontent.com/20738369/166207694-aa0fde1d-b30c-4431-b6f9-f5b8322e075d.png)

i cannot find declaration about @chakra-ui/react at all :(
how can i fix it?

### Chakra UI Version

1.8.8

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by MelnCat** [comment]
I have the same issue, I hate you stalebot

**Comment by highalps** [comment]
@MelnCat 

I resolve this issue from install all of packages

```
"@chakra-ui/accordion": "^2.0.6",
 "@chakra-ui/alert": "^2.0.4",
 "@chakra-ui/avatar": "^2.0.5",
 "@chakra-ui/breadcrumb": "^2.0.4",
 "@chakra-ui/button": "^2.0.4",
 "@chakra-ui/checkbox": "^2.1.3",
 "@chakra-ui/clickable": "^2.0.4",
 "@chakra-ui/close-button": "^2.0.4",
 "@chakra-ui/control-box": "^2.0.4",
.....
```
