### ISSUE TITLE
toggleColorMode does not work as expected within a LightMode or DarkMode component

### ISSUE THREAD

**Issue by rodrigofuentes** [chakra-ui/chakra-ui#5958]
### Description

When I have a component wrapped with `DarkMode` that can also toggle the theme using `useColorMode` it should toggle the theme for the rest of the app. Currently it does not toggle the theme if the component is wrapped in an enforcing theme component.

### Link to Reproduction

https://codesandbox.io/s/darkmode-theme-toggle-puvbqg?file=/src/App.tsx

### Steps to reproduce

1. Visit reproduction.
2. Click on the bottom two toggle theme button (view expected behavior).
3. Try the other buttons (doesn't work as expected).

### Chakra UI Version

1.8.8

### Browser

Chrome, Firefox, Safari

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

Only workaround is to set the individual elements within the container to be `DarkMode` and not the container.

**Comment by anubra266** [comment]
@rodrigofuentes That's the intended behaviour: https://github.com/chakra-ui/chakra-ui/blob/53cb16f3e19610c0ca422c7a40338fcaf5547872/packages/color-mode/src/color-mode-provider.tsx#L177
You should wrap the UI you need it for, not your whole stateful component.
