### ISSUE TITLE
[Website] Reference error MDX is not defined

### ISSUE THREAD

**Issue by leerob** [chakra-ui/chakra-ui#596]
Just a heads up – this error is showing on the home page.

![image](https://user-images.githubusercontent.com/9113740/79010187-0f5e4a00-7b27-11ea-8736-1f2e39f999c4.png)

**Comment by leerob** [comment]
I'm not seeing this anymore, strange. Going to close it and can reopen if it happens again.

**Comment by cxcorp** [comment]
Yup, I'm also seeing this. Looks like the same as #340

**Comment by leerob** [comment]
Weird – must be intermittent. Does MDX get lazy-loaded in?
