### ISSUE TITLE
Updated Figma design resources

### ISSUE THREAD

**Issue by ErlanBelekov** [chakra-ui/chakra-ui#5962]
### Description

Hi,

designers in our team have spotted a difference between the design of components on the website and the Figma resource in an old issue
<https://github.com/chakra-ui/chakra-ui/issues/396>
old Figma file: <https://www.figma.com/community/file/971408767069651759>

We need the latest version of Figma for Chakra UI.

### Problem Statement/Justification

Designers should be able to provide designs to development teams

### Proposed Solution or API

share a link to Figma resource

**Comment by segunadebayo** [comment]
Hi @ErlanBelekov,

We're currently in need of a UI designer on the team. We've struggled to get a good one in the past months so we de-prioritized this. If you'd love to volunteer, kindly reach out on Discord, and let's get the update process started.

Thanks
