### ISSUE TITLE
[Recipe] Progress + Countdown component

### ISSUE THREAD

**Issue by cezarneaga** [chakra-ui/chakra-ui#597]
needed a progress with countdown component. couldn't find one so i put something together.
maybe it helps someone so i made a sandbox: https://codesandbox.io/s/chakra-ui-progress-countdown-7fszj

maybe it will help someone else :)
feedback welcome

**Comment by segunadebayo** [comment]
Thanks for this recipe, @cezarneaga.

I'll add it to the website soon. I also renamed the issue title so I can find it better
