### ISSUE TITLE
Storybook Docs shows nothing when using @chakra-ui/storybook-addon

### ISSUE THREAD

**Issue by rajmasha** [chakra-ui/chakra-ui#5977]
### Description

When I installed @chakra-ui/storybook-addon, I expected components using chakra-ui to be shown correctly in storybook with docs but storybook docs tab shows nothing

### Link to Reproduction

https://github.com/rajmasha/chakra-ui-storybook

### Steps to reproduce

1. setup the repository provided above
2. run yarn storybook to open the storybook in the browser
3. click on the **MyButton** component under Example
4. click on the **Docs** tab on the top navbar (displays nothing)

### Chakra UI Version

1.8.8

### Browser

100.0.4896.127

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

If I comment the **@chakra-ui/storybook-addon** from the addon list in the **.storybook/main.js** file then the docs are displayed but then the components no longer use the chakra-ui styles (It becomes like a normal html button with no styles)

**Comment by TimKolberger** [comment]
We just released a prerelease version of our storybook addon. Kindly let me know if it fixes the issue.

### yarn

```sh
yarn add -D @chakra-ui/storybook-addon@2.0.0-next.4
```

### npm

```sh
npm i -D @chakra-ui/storybook-addon@2.0.0-next.4
```

Add the addon to your configuration in `.storybook/main.js` and disable the emotion alias (available with Storybook >6.4).

```js
module.exports = {
  addons: ["@chakra-ui/storybook-addon"],
  features: {
    emotionAlias: false,
  },
}
```

**Comment by rajmasha** [comment]
I installed @chakra-ui/storybook-addon@2.0.0-next.4. Now, I am getting the below error in all the stories:

```
TypeError: Cannot read properties of undefined (reading 'theme')
    at ChakraProviderDecorator (http://localhost:6006/vendors~main.iframe.bundle.js:18559:112)
    at http://localhost:6006/vendors~main.iframe.bundle.js:51675:21
    at http://localhost:6006/vendors~main.iframe.bundle.js:71487:12
    at http://localhost:6006/vendors~main.iframe.bundle.js:71545:12
    at http://localhost:6006/vendors~main.iframe.bundle.js:51705:20
    at unboundStoryFn (http://localhost:6006/vendors~main.iframe.bundle.js:72469:12)
    at renderWithHooks (http://localhost:6006/vendors~main.iframe.bundle.js:183789:18)
    at mountIndeterminateComponent (http://localhost:6006/vendors~main.iframe.bundle.js:188522:13)
    at beginWork (http://localhost:6006/vendors~main.iframe.bundle.js:190025:16)
    at beginWork$1 (http://localhost:6006/vendors~main.iframe.bundle.js:194990:14)
```

**Comment by ntwrkjasen** [comment]
@rajmasha  - were you able to resolve this? I'm getting the same thing.

**Comment by TimKolberger** [comment]
@rajmasha Thanks for the error report! The plugin in version `2.0.0-next.4` requires a Chakra UI theme provided via storybooks parameters. I just pushed a fix to fallback to the default Chakra UI theme.

Meanwhile you can workaround by providing a theme like this:

```ts
// .storybook/main.js
module.exports = {
  addons: ["@chakra-ui/storybook-addon"],
  features: {
    emotionAlias: false,
  },
}
```

```ts 
// .storybook/preview.tsx
import { theme } from "@chakra-ui/react"

export const parameters = {
  chakra: {
    theme
  }
}
```
