### ISSUE TITLE
"align" in Tabs component doesn't support breakpoints

### ISSUE THREAD

**Issue by akiarostami** [chakra-ui/chakra-ui#598]
**Describe the bug**

I'm trying to change the alignment in Tabs for different screen sizes with the simple code, but it doesn't work:

 `
<Tabs align={{xs: "start", sm: "end"}}  w="full">
<TabList>
<Tab key="tab-1">Tab 1</Tab>
<Tab key="tab-2">Tab 2</Tab>
</TabList>
</Tabs>
`

**Expected Behavior**
expect Tabs to support screen size breakpoints like most other components in the library.

**To Reproduce**
Use the simple code above.

**Suggested solution(s)**
Check the breakpoints in Tabs :)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome & safari
 - Version latest

**Additional context**
Tabs' documentation seems to be missing Align all together! I could only see it in the examples provided, but not in the documentation.

**Comment by afrieirham** [comment]
It's also weird that all text inside the `TabPanel` is centered, if `Tabs` is set to `align="center"`. I found a workaround by making the `TabList` as `Flex` and set `justifyContent` and `alignItems` to `center`.

Another issue with `Tabs` is the `isFitted` props also doesn't support breakpoints, which I don't have a workaround yet.

**Comment by karimcambridge** [comment]
> It's also weird that all text inside the `TabPanel` is centered, if `Tabs` is set to `align="center"`. I found a workaround by making the `TabList` as `Flex` and setting `justifyContent` to `center`.
> 
> Another issue with `Tabs` is the `isFitted` props also doesn't support breakpoints, which I don't have a workaround yet.

I'd also like the tablist to be centered with the border lines spanning the width without workarounds.

**Comment by Tranquerah** [comment]
> It's also weird that all text inside the `TabPanel` is centered, if `Tabs` is set to `align="center"`. I found a workaround by making the `TabList` as `Flex` and setting `justifyContent` to `center`.
> 
> Another issue with `Tabs` is the `isFitted` props also doesn't support breakpoints, which I don't have a workaround yet.

Having same issue with trying to make `Tabs` responsive to breakpoints - `Tab` components currently stays on one line always.

**Comment by kjanred** [comment]
Was looking into this issue. <Tabs align= "center">  produces Tabs in the center, so <Tabs align={{ base: "center", md: "start" }} > should produce centered Tabs until the MD breakpoint, at which they become aligned at the start. But it does not, everything is aligned start.
