### ISSUE TITLE
[Bug?]: CircularProgress does not use StyleConfig

### ISSUE THREAD

**Issue by caseybaggz** [chakra-ui/chakra-ui#5982]
### Description

When I used a StyleConfig on the CircularProgress component, I expected it to be used, but it did not apply any of the styles.

### Link to Reproduction

Ihttps://codesandbox.io/s/ps-react-chakra-forked-t5lw4s?file=/src/App.tsx

### Steps to reproduce

1. Go to sandbox link
2. View `App.tsx`
3. See error

### Chakra UI Version

latest

### Browser

Chrome - latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

From the source - I think the component is missing the `useMultiSTyleConfig` that Progress seems to use (Progress works fine). Not sure if this is it though?

**Comment by Patrick-Ullrich** [comment]
Hey @caseybaggz ,

I took a look at your sandbox and I noticed a couple of things:

1. based on the documentation and location of Circular Progress, it should actually be themed through the `Progress` component in the theme:

```
const CircularProgressConfig = {
  parts: ['filledTrack', 'track', 'label'],
  baseStyle: {
    filledTrack: {
      stroke: 'tomato'
    },
    track: {
      stroke: 'tomato',
      opacity: 0.7
    }
  },
  defaultProps: {
  }
}

const theme = extendTheme({
  components: {
    Progress: CircularProgressConfig
  }
})
```

2. When styling the progress, you actually change the `backgroundColor`, not the stroke. e.g.:
```
 baseStyle: {
    filledTrack: {
      backgroundColor: 'red'
    },
    track: {
      backgroundColor: 'yellow',
      opacity: 0.7
    }
  },
```

3. The default props that were added were also not allowing it to be styled correctly. 

Putting it all together, you can see that the `Progress` is being styled, but as you already reported, the Circular Progress isn't being styled:
![Screen Shot 2022-05-16 at 10 05 03 PM](https://user-images.githubusercontent.com/6193042/168726485-d80e9535-a220-4052-9324-5411d18384d9.png)

Digging into the code; just like you stated, it is in fact not wired up to the theme at all. 

Just in case this is a blocking issue and you are looking for a workaround.. You could write your own wrapper around CircularProgress and pass in some of the Progress theme properties in until this gets fixed:

```

const CircularProgressConfig = {
  parts: ['filledTrack', 'track', 'label'],
  baseStyle: {
    filledTrack: {
      backgroundColor: 'red'
    },
    track: {
      backgroundColor: 'yellow',
      opacity: 0.7
    }
  },
  defaultProps: {}
}

const theme = extendTheme({
  components: {
    Progress: CircularProgressConfig
  }
})

const MyCircularProgress = () => {
  const styles = useMultiStyleConfig('Progress', {})
  return (
    <CircularProgress
     // And whatever else you need here
      color={styles.filledTrack.backgroundColor}
      trackColor={styles.track.backgroundColor}
      value={32}
    />
  )
}

export default function App() {
  return (
    <ChakraProvider theme={theme}>
      <MyCircularProgress />
    </ChakraProvider>
  )
}
```

**Comment by Kolby-Udacity** [comment]
Any update on this? I'm unable to style the CircularProgress bar via theme.

**Comment by GKosheev** [comment]
@Kolby-Udacity, this component is still not allowed to be themed, but I'm currently investigating the reason behind it and planning to create an issue.

**Comment by Patrick-Ullrich** [comment]
@GKosheev https://github.com/chakra-ui/chakra-ui/issues/5982#issuecomment-1128385889

**Comment by GKosheev** [comment]
@Patrick-Ullrich, I saw this comment. Even though it solves the problem of styling, it doesn't follow the logic of the library. `Progress` and `CircularProgress` are 2 completely different components, though they share the same following logic: 
```tsx
export function getProgressProps(options: GetProgressPropsOptions) {
  const {
    value = 0,
    min,
    max,
    valueText,
    getValueText,
    isIndeterminate,
    role = "progressbar",
  } = options
```

My issue with that there is no support for theming out of the box for `CircularProgress`, which supposes to be included. I don't have any intention or urgent need to use this theme in my projects. What I want is to contribute to this library by creating an issue with a possible solution.

**Comment by sinolopes** [comment]
Any news ?

**Comment by banch3v** [comment]
The only thing that I found as a solution (more like workaround) is to build custom component and pass props while having some default ones for the styling...
Under the hood it's an SVG, that is why the default styling config method isn't working.
