### ISSUE TITLE
Invalid changelog

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#5984]
The last 4 entries of the changelog are the same: https://github.com/chakra-ui/chakra-ui/blob/next/CHANGELOG.md

**Comment by TimKolberger** [comment]
Good catch - I think this is a side effect of changesets and our changelog script while the repo is in pre-release mode.
We should definitely clean this up right before releasing v2.

FYI @segunadebayo

**Comment by lcswillems** [comment]
Ok I see!
