### ISSUE TITLE
-internal-light-dark overriding input styles

### ISSUE THREAD

**Issue by DaviCaamano** [chakra-ui/chakra-ui#5985]
### Description

I'm creating a Next js project and I noticed the -internal-light-dark class is overriding all Chakra UI input boxes.

### Link to Reproduction

https://github.com/DaviCaamano/illmith

### Steps to reproduce

1. Create a Next Js project.
2. Create an <Input> using ChakraUI.

### Chakra UI Version

2.0.22

### Browser

Google Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I'm creating a Next js project and I noticed the -internal-light-dark class is overriding all Chakra UI input boxes.

This isn't happening for normal input boxes. Is there something I can do to stop this?

**Comment by JClackett** [comment]
Yeah I've just noticed that all "filled" inputs are showing up a bit weird:

un-focused:

<img width="815" alt="Screenshot 2022-05-07 at 18 51 38" src="https://user-images.githubusercontent.com/12549124/167264107-6da1be32-a14a-498f-a3c8-ebc8853dc4d8.png">

focused:
<img width="814" alt="Screenshot 2022-05-07 at 18 51 42" src="https://user-images.githubusercontent.com/12549124/167264104-a41bae5c-3db9-4f16-867a-06a47bca643d.png">


something to do with the background on dark mode for filled inputs on chakra v2

**Comment by anubra266** [comment]
Please create a cidesandbox reproduction. Thanks

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. Kindly provide a reproduction in CodeSandbox and we'll re-open

PS: If it's related to the color mode, then it has been fixed in the recent release. Kindly upgrade and try again
