### ISSUE TITLE
Global with css`` does not work

### ISSUE THREAD

**Issue by lishine** [chakra-ui/chakra-ui#599]
This does not work
```
import { Global, css } from '@emotion/core'

    <Global
      styles={css`
        ::-webkit-search-cancel-button {
          -webkit-appearance: 'none';
        }
        body: {
          background-color: green;
        }
      `}
    />
```
where this works
```
    <Global
      styles={{
        '::-webkit-search-cancel-button': {
          '-webkit-appearance': 'none',
        },
        body: {
          backgroundColor: 'green',
        },
      }}
    />

```
I wanted to write it with css because cannot get rid of this annoying warning:
```
Using kebab-case for css properties in objects is not supported. Did you mean WebkitAppearance
```

**Comment by segunadebayo** [comment]
Hi @lishine,

I'm sorry but this issue is mostly related to @emotion/core. I'm glad you found a walk-around.

If you're writing styles as an object, then you want to change ` '-webkit-appearance'` to  `WebkitAppearance`.

**Comment by lishine** [comment]
Yes, actually I tried and thought this -webkit-search-cancel-button should be converted as well, but no, actually it works as is, only the WebkitAppearance should be camel case.
Thanks
```
    <Global
      styles={{
        '::-webkit-search-cancel-button': {
          WebkitAppearance: 'none',
        },
        body: {
          backgroundColor: 'green',
        },
      }}
    />
```

**Comment by julians300** [comment]
Your style for the body should be 

```
body {
    backgroundColor: 'green',
},
```

That extra `:` was making it invalid.
