### ISSUE TITLE
Toast - Reset duration on update

### ISSUE THREAD

**Issue by devagja** [chakra-ui/chakra-ui#5992]
### Description

Hi all!

I missing a property that reset the duration counter on toast.update()

### Problem Statement/Justification

https://user-images.githubusercontent.com/43604808/167262960-109afdd6-58f3-4996-bccd-c215c8a74f3e.mp4

### Proposed Solution or API

add prop resetDuration

**Comment by devagja** [comment]
based on my code, i think the current behavior is cumulative if you press it too fast

if you press with a certain delay it does not accumulate the time

Anyway, I don't know if this behavior should be correct since if I put a duration of 3 seconds and click 10 times in a row, I will have a toast for 30s

these is my code
```
const id = 'color-scheme-toast'

export default function Home () {

   const toast = useToast({
      duration: 3000,
      position: 'bottom-left'
   })

   const changeThemeDesktop =() => {
      const render = ({ onClose }) => (
         <CustomToast
            onClick={onClose}
         >
            lorem ipsum
         </CustomToast>
      )

      if (toast.isActive(id)) {
         toast.update(id, { render })
      } else {
         toast({ id, render })
      }
   }
...
}
```

thx so much!

**Comment by anubra266** [comment]
@devagja, don't add a duration, then you can close the toast whenever you want, like [this](https://chakra-ui.com/docs/components/feedback/toast#closing-toasts). You can use Javascript `setTimeout` method to set any complex duration you want
