### ISSUE TITLE
Create navbar

### ISSUE THREAD

**Issue by nejos97** [chakra-ui/chakra-ui#6]
Nice job and I'm ready to adopt this in my future project.
I tried to make a navigation bar but it was not easy at all. if you can make a component for that. or do a little tutorial on how we can do this.

**Comment by Vynlar** [comment]
Could you provide an example of the type of navbar you are trying to build?

**Comment by shivashp** [comment]
I am not sure your exact requirements / design. I created a standard Navbar ( pretty basic ) to give you example of how it works. Let me know if it helps

https://codesandbox.io/embed/peaceful-bird-kd74j

**Comment by segunadebayo** [comment]
Hi @nejos97 ,

I hope @shivashp's example resolved your concern. Thank you for the quick prototype @shivashp.

I'll close this issue, let us know if you have any other questions.

Thanks again.

**Comment by Koli14** [comment]
Hey, @segunadebayo ! I also really enjoy Chakra-UI.
I want to achieve a menu similar to this: https://codepen.io/Koli14/pen/jOPWEWB
I can't use the `<Menu>` element, as I need the parent to be a link, and  open on hover.

**Comment by Koli14** [comment]
I solved it with an aproach based on this:
https://codesandbox.io/s/chakra-js-hover-5kxd2
