### ISSUE TITLE
[Button] variantColor can only take some colors 

### ISSUE THREAD

**Issue by TheHelias** [chakra-ui/chakra-ui#600]
variantColor can only accept certain colors. It doesn't work with hex codes and only works with some colors. Also, colors set in the theme don't work for it

It should be able to accept any color and hex code. Also, I should be able to use colors set in the theme

**Comment by segunadebayo** [comment]
Hi @TheHelias,

Yes, that's the current constraint we have but we've solved this in preparation for the next release.

For now, you can simply pass `bg`, `color`, `_hover` props to style the button yourself if you need to gain control. The `variantColor` only takes the name of colors in the `theme` that have `50-900` values.

As I said, this has been resolved in the next release we're working on.

Thank you.

**Comment by TheHelias** [comment]
That's great, how soon can we expect this new release?

Sent from Yahoo Mail on Android 
 
  On Sun, 12 Apr 2020 at 0:40, Segun Adebayo<notifications@github.com> wrote:   


Hi @TheHelias,

Yes, that's the current constraint we have but we've solved this in preparation for the next release.

For now, you can simply pass bg, color, _hover props to style the button yourself if you need to gain control. The variantColor only takes the name of colors in the theme that have 50-900 values.

As I said, this has been resolved in the next release we're working on.

Thank you.
