### ISSUE TITLE
Toast feature not working (including Chakra website)

### ISSUE THREAD

**Issue by floroz** [chakra-ui/chakra-ui#6000]
### Description

When I use `useToast` and execute a toast, nothing is visible on the page

### Link to Reproduction

https://github.com/floroz/chakra-reproduce-example-bug-toast

### Steps to reproduce

1. Go on the [Toast Documentation](https://chakra-ui.com/docs/components/feedback/toast) on Chakra website and try to use one of the Toast example
2. Clone this repository [this](https://github.com/floroz/chakra-reproduce-example-bug-toast)
3. Click on 'Open Toast' button
4. Nothing appears

### Chakra UI Version

1.8.8

### Browser

Google Chrome 100

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Currently Toast is broken both on the Chakra docs site, and I could reproduce the issue in a standalone repo

**Comment by hardikhere** [comment]
Hey @floroz I'm unable to reproduce. it works for me 
![image](https://user-images.githubusercontent.com/51117080/167833722-b21acfe8-a2b9-4666-87d1-831b79511cf8.png)

**Comment by floroz** [comment]
> Hey @floroz I'm unable to reproduce. it works for me ![image](https://user-images.githubusercontent.com/51117080/167833722-b21acfe8-a2b9-4666-87d1-831b79511cf8.png)

Okay, this is super-weird, I had a colleague of mine double-checking and they also could not see the Toast appearing, nor on the Chakra website.
Today both my repo and the website work fine. 

Mysteries of software...

Thanks for replying sorry to waste your time!

**Comment by hardikhere** [comment]
@floroz  So Issues, it happens.
