### ISSUE TITLE
TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_5__.createContext) is not a function when using with NextJS

### ISSUE THREAD

**Issue by praveen7557** [chakra-ui/chakra-ui#6001]
### Description

I am trying to setup chakra UI in my newly created next app, there is nothing in the app yet, just followed https://chakra-ui.com/guides/getting-started/nextjs-guide page, but getting  `TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_5__.createContext) is not a function` error.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-next-js-typescript-kxvyr?file=/pages/_app.tsx

### Steps to reproduce

Issue is not reproducing in codesandbox for some reason.

### Chakra UI Version

1.8.8

### Browser

Google Chrome 101

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

These are the dependencies I have

<img width="315" alt="Screenshot 2022-05-11 at 7 53 51 AM" src="https://user-images.githubusercontent.com/13882201/167756267-28b7f9ab-ee8a-4697-b15a-f0fe6d0a1826.png">

**Comment by segunadebayo** [comment]
Hi @praveen7557,

The issue you're experiencing is related to Next.js, not Chakra UI. Also, to use Chakra UI with React 18, kindly upgrade to v2

Thank you
