### ISSUE TITLE
Select isReadOnly is not preventing value selection and still fires onChange events

### ISSUE THREAD

**Issue by cevaris** [chakra-ui/chakra-ui#6005]
### Description

When I set isReadOnly on Select, I expect clicking the Select do do nothing and onChange event not to fire, but I am seeing both occur. I expect Select isReadOnly to operate similar to Input. isDisabled here is not desirable because that alters the font color.

### Link to Reproduction

https://codesandbox.io/s/fast-wildflower-jo2k4c

### Steps to reproduce

1. Set `<Select isReadOnly />` with some sample options.
2. Click on the Select component.
3. See that the options menu still pops up.
4. See that the onChange handler still fires.

### Chakra UI Version

1.8.8

### Browser

Brave 1.38.111 Chromium: 101.0.4951.54 (Official Build) (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @cevaris,

`readonly` isn't a valid attribute of the select element. See here:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement

Kindly pass the `isDisabled` property instead.

**Comment by starg09** [comment]
> Hi @cevaris,
> 
> `readonly` isn't a valid attribute of the select element. See here: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement
> 
> Kindly pass the `isDisabled` property instead.

Sorry to necrobump this, but why is `ìsReadOnly` a prop for the `<Select/>` component then?
