### ISSUE TITLE
Wrap list extending past the Wrap container when you specify spacing

### ISSUE THREAD

**Issue by dxu** [chakra-ui/chakra-ui#6006]
### Description

The wrap__list is extending past the wrap container, causing overflow to sroll when you specify spacing

### Link to Reproduction

https://chakra-ui.com/docs/components/layout/wrap

### Steps to reproduce

You can even see it in the docs, in the examples themselves. 
<img width="881" alt="image" src="https://user-images.githubusercontent.com/718423/168021048-64b7930b-0023-4924-b0c4-583854a6964b.png">

### Chakra UI Version

1.8.8

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Can't seem to reproduce this. Kindly create a reproduction and I'll re-open

<img width="855" alt="CleanShot 2022-05-17 at 11 59 02@2x" src="https://user-images.githubusercontent.com/6916170/168760248-01b29527-28e4-4900-96c2-1ed7c01acc73.png">
