### ISSUE TITLE
Request to not show tooltips when label is empty

### ISSUE THREAD

**Issue by martinpengellyphillips** [chakra-ui/chakra-ui#601]
**Is your feature request related to a problem? Please describe.**
Currently a Tooltip with an empty label will still display. 

![firefox_9tqNWp27R8](https://user-images.githubusercontent.com/214338/79068396-78c49100-7cbe-11ea-87ef-386a91bd4b77.png)

**Describe the solution you'd like**
An option (or default behaviour) to not show the Tooltip when the label is null. This feels like a helpful part of the component (especially as the rendering of the empty tooltip is not pretty).

**Describe alternatives you've considered**
Conditionally creating the Tooltip when the label is not empty. Works, but feels redundant effort.

**Additional context**
https://codesandbox.io/s/chakra-js-starter-98f93?file=/src/index.js

**Comment by segunadebayo** [comment]
Hi @martinpengellyphillips,

Thanks for this issue and suggestion. We've just implemented it in preparation for the next release.
