### ISSUE TITLE
Allow tabs to be set by unique key, not index

### ISSUE THREAD

**Issue by mellis481** [chakra-ui/chakra-ui#6014]
### Description

Only allowing Tabs to be set by index requires consumers to manage indexes in situations where they need to programmatically set tabs AND one or more tabs are rendered conditionally.

### Problem Statement/Justification

Here is an example of what happens when a tab is conditionally rendered and a tab needs to be selected programmatically if I don't manage the indexes on my own:

```function ControlledExample() {
  const [tabIndex, setTabIndex] = React.useState(0)
  const [isTabTwoHidden, setIsTabTwoHidden] = React.useState(false)

  const handleButton0Click = () => setTabIndex(0);  
  const handleButton1Click = () => setTabIndex(1);  
  const handleButton2Click = () => setTabIndex(2);  
  const handleButton3Click = () => setIsTabTwoHidden(!isTabTwoHidden);
  const handleTabsChange = (index) => setTabIndex(index);

  return (
    <Box>
      <button 
        onClick={handleButton0Click} 
        style={{border:'1px solid black',padding:'5px'}}>Select tab with index 0</button>
      <button 
        onClick={handleButton1Click} 
        style={{border:'1px solid black',padding:'5px'}}>Select tab with index 1</button>
      <button 
        onClick={handleButton2Click}
        style={{border:'1px solid black',padding:'5px'}}>Select tab with index 2</button>
      <button 
        onClick={handleButton3Click} 
        style={{border:'1px solid black',padding:'5px'}}>{isTabTwoHidden ? 'Show' : 'Hide'} tab "Two"</button>
      <Tabs index={tabIndex} onChange={handleTabsChange}>
        <TabList>
          <Tab>One</Tab>
          {!isTabTwoHidden && <Tab>Two</Tab>}
          <Tab>Three</Tab>
        </TabList>
        <TabPanels>
          <TabPanel>
            <p>Click the tabs or pull the slider around</p>
          </TabPanel>
          {!isTabTwoHidden && (
            <TabPanel>
              <p>Yeah yeah. What's up?</p>
            </TabPanel>
          )}
          <TabPanel>
            <p>Oh, hello there.</p>
          </TabPanel>
        </TabPanels>
      </Tabs>
    </Box>
  )
}
```

When tab "Two" is enabled, it's index is 1 and I can programmatically select it using the React hook and index 1.

When tab "Two" is disabled, tab "Three" is the tab with an index of 1 and and when I programmatically set index 1 using the React hook, it selects tab "Three".

It would be great if you could specify the tab you want to select directly by a id/key rather than indirectly by index.

### Proposed Solution or API

Add a `key` property to the `<Tab>` component and have `<Tabs>` use a `selectedKey` prop to determine selection. It seems like this could be used as an alternative to `index` (ie. have both conventions available).

**Comment by segunadebayo** [comment]
Hi @mellis481,

This is in scope for the next major release. We're going to the tabs components in Zag as shown here: https://zagjs.com/components/react/tabs

For now, kindly find alternatives (or use Zag tabs) while we work on this.

Thanks for understanding.

**Comment by mellis481** [comment]
@segunadebayo Thanks for the update. Is there a timeline for the next major release that you can share?

CC: @dgreene1

**Comment by dgreene1** [comment]
@segunadebayo a few questions:

1. are you saying that Chakra will wrap Zag? Or are you saying that the next Chakra major release will no longer have a tabs component?
2. If you're wrapping it, why not just stop offering it (like you've done with date time dropdowns) and clarify that you recommend Zag?
3. If you have the time, can you share why you've chosen this shift?

**Comment by mellis481** [comment]
@segunadebayo The Chakra documentation would seem to indicate Tabs still uses an [index-based control implementation](https://chakra-ui.com/docs/components/tabs/usage#controlled-tabs) even though there has been a major release since this ticket was closed. Am I missing something?

**Comment by dgreene1** [comment]
Hi @segunadebayo can you share an ETA on when we can utilize a key property on tabs like @mellis481 describes in the original issue text above?

If the ETA is too far away, then please reopen this and allow our team to PR the existing version with the enhancement we’ve described.

**Comment by unsphere** [comment]
I came across this need today as well because I just want to utilize the TabList for routes like so e.g.:

```javascript
export const Submenu = () => {
  const router = useRouter();

  return (
      <Tabs value={router.asPath}>
        <TabList>
          <Tab value="/" onClick={() => router.push('/')}>
            Dashboard
          </Tab>
          <Tab value="/settings" onClick={() => router.push('/settings')}>
            Settings
          </Tab>
        </TabList>
      </Tabs>
  );
};
```

It would be nice if we could get a comment on this.
