### ISSUE TITLE
Locally saved 'dark mode' not applied on page load (v2.0.0)

### ISSUE THREAD

**Issue by lucasishuman** [chakra-ui/chakra-ui#6016]
### Description

If the locally saved color mode is 'dark', the 'chakra-ui-dark' class is not applied to body element on page load

### Link to Reproduction

x

### Steps to reproduce

I just upgrade from Chakra v1.8.8 to v2.0.0 and noticed the following behavior:

1. Save the local color mode preference to be 'dark'
2. Verify `chakra-ui-color-mode` in LocalStorage is `dark`
3. Refresh page
4. Note that `chakra-ui-dark` class is not applied to `body` element
5. Therefore any `_dark` component props further down the tree are not being observed

### Chakra UI Version

2.0.0

### Browser

Google Chrome 101.0.4951.64

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

react + react-dom v18.1.0 (_not_ a CRA)

Tried this in my index file but seems to make no difference (didn't use this in v1.8.8 and behavior was as expected)

```jsx
...
root.render(
  <React.StrictMode>
    <ColorModeScript />
    <MyApp />
  </React.StrictMode>
);
...
```

This does _not_ occur when locally saved color mode is `light` - not sure why...

The behavior is the same whether I include the `ColorModeScript` component in the initial render block or not (I did not use it in v1.8.8 and it work correctly)

See attached screen capture ~>

![May-12-2022 14-21-00](https://user-images.githubusercontent.com/1753761/168170313-ec89fa80-2685-4019-8c24-c7f89a0d81c1.gif)

**Comment by lucasishuman** [comment]
I'm also seeing this when there is **no** locally saved color mode preference and the `initialColorMode` is `dark`

**Comment by ogheo** [comment]
Same, on initial render light color mode isn't applied

**Comment by lucasishuman** [comment]
It seems that a lot of people are having miscellaneous color mode issues w/ v2. I noticed that there is some work being done on it **right now** so I assume fixes are coming very soon. Many thanks to the Chakra team for jumping on this!

Related PR:
https://github.com/chakra-ui/chakra-ui/pull/6035
