### ISSUE TITLE
Default Toast style renders `subtle` variant from Alert by default

### ISSUE THREAD

**Issue by TylerAPfledderer** [chakra-ui/chakra-ui#6017]
### Description

When testing a toast with default styling, it renders an opaque background color when the page is in dark mode.

### Link to Reproduction

https://chakra-ui.com/docs/components/feedback/toast

### Steps to reproduce

With the docsite in dark mode, playing with the first code example will render the transparent background. 

Same with the [Closing Toasts](https://chakra-ui.com/docs/components/feedback/toast) example.

### Chakra UI Version

2.0.0

### Browser

Firefox 101.0b5 (Developer Edition

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

In v1, the sourcecode of `useToast` shows an object named [`default`](https://github.com/chakra-ui/chakra-ui/blob/0f591c613af822798918ae141186a4597ab64d39/packages/toast/src/use-toast.tsx#L127-L131) that holds the variant `solid`. This is the object applied to the `Alert` component the toast uses.

In the newest version, there is no sign of a default variant value for the `Alert` component (now in the [`toast.tsx` file](https://github.com/chakra-ui/chakra-ui/blob/790d2417a3f5d59e2d69229a027af671c2dc0cbc/packages/toast/src/toast.tsx#L30))

There is also no changelog stating that this default change occurred.

### Solution??
For accessibility, fundamentally, the toast could retain the `solid` variant by default to limit potential contrast issues until the user declares to make a new variant to alter the background as they see fit.

So at [line 28 of `toast.tsx`](https://github.com/chakra-ui/chakra-ui/blob/790d2417a3f5d59e2d69229a027af671c2dc0cbc/packages/toast/src/toast.tsx#L28), changing to:
```jsx
<Alert
  status={status}
  variant={variant ?? "solid"} <=== // Or `variant || "solid"` ?
  id={id}
  alignItems="start"
  borderRadius="md"
  boxShadow="lg"
  paddingEnd={8}
  textAlign="start"
  width="auto"
  aria-labelledby={alertTitleId}
>
```

## Screenshot
![image](https://user-images.githubusercontent.com/65234762/168174455-e38f0b29-9743-4dcd-b05f-09de1a6dff07.png)

**Comment by segunadebayo** [comment]
Good catch @TylerAPfledderer. Feel free to open a PR to revert to the `solid` variant
