### ISSUE TITLE
Support chrome and safari bug with height 100% in all components

### ISSUE THREAD

**Issue by hadson172** [chakra-ui/chakra-ui#6027]
### Description

When I was developing my website using chakra-ui components I needed in few drawer component with size set to full or some other components like <Box height="full">. On iOS safari 100vh === viewport + bottonNavbar

### Link to Reproduction

https://allthingssmitty.com/2020/05/11/css-fix-for-100vh-in-mobile-webkit/

### Steps to reproduce

1. Build a webiste with chakra's attribute `height={"full"}` or use existing one like drawer full screen option.
2. Deploy webiste
3. Go to iphone safari
4. Height makes part of the page to be hidden under bottom navbar.

Chakra-ui should use properties like 
```
  height: 100vh;
  height: -moz-available;
  height: -webkit-fill-available;
  height: fill-available;
```

instead of just 100vh
It is well known problem and it should be handled by chakra-ui.
Described here https://allthingssmitty.com/2020/05/11/css-fix-for-100vh-in-mobile-webkit/

### Chakra UI Version

1.8.8

### Browser

Safari

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Patrick-Ullrich** [comment]
Personally I haven't had much luck with the suggested work arounds. I usually end up using some js solution like `react-100div`. 

Alternatively, something like this often works pretty well:
```
let vh = window.innerHeight * 0.01;
document.documentElement.style.setProperty('--vh', `${vh}px`);
```

This could be easily baked into the framework and be part of the theme.
