### ISSUE TITLE
TypeError: win.matchMedia is not a function during unit test

### ISSUE THREAD

**Issue by stefee** [chakra-ui/chakra-ui#6036]
### Description

When I render a ChakraProvider inside a unit test (for example, to test a component which uses the useToast hook) an error is thrown by the color mode query function `TypeError: win.matchMedia is not a function`.

### Link to Reproduction

https://github.com/stefee/chakra-repro-6036

### Steps to reproduce

```
git clone git@github.com:stefee/chakra-repro-6036.git
cd chakra-repro-6036
npm install
npm test
```

### Chakra UI Version

2.0.0

### Browser

Jest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by stefee** [comment]
Added reproduction.

**Comment by DeveloperMatheus** [comment]
I'm also getting this error.

But nonetheless, thank you guys for the hardwork and the V2. I can't wait to use this!

**Comment by Patrick-Ullrich** [comment]
Hey @stefee, check out my PR to your sample repo: https://github.com/stefee/chakra-repro-6036/pull/1

1. Added typescript to get the sample project running
2. Added matchMedia to window. Read more here: https://stackoverflow.com/questions/39830580/jest-test-fails-typeerror-window-matchmedia-is-not-a-function

For future reference in case the Repo will be deleted / the PR is gone:
1. Add a `jest.setup.js` (or .ts)
```
// jest.setup.js
beforeEach(() => {
  Object.defineProperty(window, "matchMedia", {
    writable: true,
    value: jest.fn().mockImplementation((query) => ({
      matches: false,
      media: query,
      onchange: null,
      addListener: jest.fn(), // Deprecated
      removeListener: jest.fn(), // Deprecated
      addEventListener: jest.fn(),
      removeEventListener: jest.fn(),
      dispatchEvent: jest.fn(),
    })),
  });
});
```

2. Add a reference to your `jest.setup.js/ts` file in your `jest.config.js/ts`
```
module.exports = {
 ... rest of your config,
 setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
... rest of your config
}
```

Find some more info in the jest official documentation: https://jestjs.io/docs/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom

This has little to do with chakra, but the fact that JSDOM (the DOM implementation used by Jest) has not implemented `matchMedia`, so you have to mock it.

**Comment by stefee** [comment]
Thanks @Patrick-Ullrich! The jest docs example makes sense, good to know it’s not a Chakra issue specifically. I’m happy to close this now. https://jestjs.io/docs/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom

**Comment by stefee** [comment]
This issue was fully resolved in the latest release of Chakra UI (2.0.2) so the manual mock is no longer required.

**Comment by wizardbyron** [comment]
> 

This issue can be reproduced in Chakra UI（2.5.2）by：

```shell
npx create-react-app chakra-ui-app-test --template @chakra-ui/typescript
cd chakra-ui-app-test
npm test 
```

 I have to write the manual mock to fix this.

**Comment by brunnolou** [comment]
It worked for me by adding this code to `/src/setupTests.ts` instead of `jest.setup.js`

> Hey @stefee, check out my PR to your sample repo: [stefee/chakra-repro-6036#1](https://github.com/stefee/chakra-repro-6036/pull/1)
> 
> 1. Added typescript to get the sample project running
> 2. Added matchMedia to window.
> 
> For future reference in case the Repo will be deleted / the PR is gone:
> 
> 1. Add a `jest.setup.js` (or .ts)
> 
> ```
> // jest.setup.js
> beforeEach(() => {
>   Object.defineProperty(window, "matchMedia", {
>     writable: true,
>     value: jest.fn().mockImplementation((query) => ({
>       matches: false,
>       media: query,
>       onchange: null,
>       addListener: jest.fn(), // Deprecated
>       removeListener: jest.fn(), // Deprecated
>       addEventListener: jest.fn(),
>       removeEventListener: jest.fn(),
>       dispatchEvent: jest.fn(),
>     })),
>   });
> });
> ```
> 
> 2. Add a reference to your `jest.setup.js/ts` file in your `jest.config.js/ts`
> 
> ```
> module.exports = {
>  ... rest of your config,
>  setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
> ... rest of your config
> }
> ```
> 
> Find some more info in the jest official documentation: https://jestjs.io/docs/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom
> 
> This has little to do with chakra, but the fact that JSDOM (the DOM implementation used by Jest) has not implemented `matchMedia`, so you have to mock it.

**Comment by BruceHubbard** [comment]
I hit this problem in Chakra 2.0.2 (which is quite old now) but there was an interesting wrinkle.  I had the `beforeEach` like above but I also needed a `beforeAll` because of a random test that had a `beforeAll` in it that was hitting that logic and then throwing an error.  Just putting this here in case someone hits the same problem.
