### ISSUE TITLE
[Modal] If scrollBehavior = 'inside', unable to close modal by clicking above or below it

### ISSUE THREAD

**Issue by psychedelicious** [chakra-ui/chakra-ui#604]
**Describe the bug**
When `scollBehavior` is set to `inside`, the Modal cannot be closed by clicking the overlay anywhere above its top edge or below its bottom edge.

You can see this in action on the [official docs page](https://chakra-ui.com/modal), or in [this codesandbox example](https://codesandbox.io/s/staging-http-zh4hk?file=/src/App.js).

**Expected Behavior**
The Modal should close when clicking anywhere on the overlay element.

**To Reproduce**
- Use this template: [this codesandbox example](https://codesandbox.io/s/staging-http-zh4hk?file=/src/App.js)
- List the steps to reproduce the behavior:
Set `scrollBehavior` to `inside`. 

**Suggested solution(s)**
Unfortunately I am not familiar enough with the Chakra UI to suggest a code fix, but it looks like when `scrollBehavior` is set to `inside`, the Modal's container (which has the `onClick` handler) does not extend to the top or bottom of the screen. 

**Desktop (please complete the following information):**
 - OS: macOS 15.4
 - Browser/Version:
Firefox 75.0
Safari 13.1 (15609.1.20.111.8)
Chrome 80.0.3987.149

**Additional context**

**Comment by segunadebayo** [comment]
Thanks for raising this issue @psychedelicious.

This has been resolved in preparation for the next release.
