### ISSUE TITLE
Multipart component themes for Tag component does not work

### ISSUE THREAD

**Issue by johannespein** [chakra-ui/chakra-ui#6045]
### Description

When I style the `components.Tag.baseStyle.label` theme I expect my component to change on the UI.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-tag-theme-not-working-rczxck?file=/src/index.js

### Steps to reproduce

Apply styles to Tag component 
```
Tag: {
    Tag: {
      // parts: ["container", "label"],
      baseStyle: {
        container: {
          bg: "red"
        },
        label: {
          // this does not work
          color: "white"
        }
      },
      defaultProps: {
        variant: "none"
      }
    }
```

### Chakra UI Version

1.7.4

### Additional Information

https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/tag.ts#L46

**Comment by hugobqd** [comment]
Hello @johannespein ! 
`label` refers to the `TagLabel` subcomponent 
So two possibilities :

1. Use the container to provide the text color :
```
Tag: {
    Tag: {
      // parts: ["container", "label"],
      baseStyle: {
        container: {
          bg: "red",
          color: "lawngreen"
        },
    }
```

2. Use the TagLabel :
```
<Tag>
  <TagLabel>Hi</TagLabel>
</Tag>
```

**Comment by johannespein** [comment]
Thanks for the quick answer @hugobqd ! :)

worked!
