### ISSUE TITLE
chakra-ui/focus-lock React 18 peer dependency error

### ISSUE THREAD

**Issue by TomSmedley** [chakra-ui/chakra-ui#6048]
### Description

When installing Chakra with NextJS I'm getting the following error.

### Link to Reproduction

N/A

### Steps to reproduce

```
npx create-next-app@latest
npm i @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^6
````
Gives error:
```
npm WARN ERESOLVE overriding peer dependency
npm WARN node_modules/react-focus-lock
npm WARN   react-focus-lock@"2.5.2" from @chakra-ui/focus-lock@2.0.0
npm WARN   node_modules/@chakra-ui/focus-lock
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0" from react-focus-lock@2.5.2
npm WARN   node_modules/react-focus-lock
npm WARN     react-focus-lock@"2.5.2" from @chakra-ui/focus-lock@2.0.0
npm WARN     node_modules/@chakra-ui/focus-lock
```

### Chakra UI Version

2.0.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by hugobqd** [comment]
hello @TomSmedley !
Try downgrading to chakra 1.8.8, because v2 is compatible with react 18.
V1 docs -> https://v1.chakra-ui.com

**Comment by TomSmedley** [comment]
Hi @hugobqd, 

Why would I downgrade to Chakra 1.8.8 if I'm using React 18? This error is produced with React 18.

**Comment by hugobqd** [comment]
You are right, so that should be the react-focus-lock dependency that should de upgraded to 2.9.0 to support react18
https://github.com/theKashey/react-focus-lock/releases/tag/v2.9.0

**Comment by segunadebayo** [comment]
This was fixed in a recent PR. We'll publish a release shortly
