### ISSUE TITLE
Box shadow are cut when components are inside Collapse 

### ISSUE THREAD

**Issue by alexpuertasr** [chakra-ui/chakra-ui#6049]
### Description

Components with box shadows are cut when are inside a Collapse, this is due the overflow hidden (maybe removing this style once the c)

### Link to Reproduction

https://codesandbox.io/s/stoic-dream-kkjf6x?file=/src/App.tsx:356-364

### Steps to reproduce

1. Click on the Switch
2. Click on the Input
3. See how the box shadow is cut

<img width="543" alt="image" src="https://user-images.githubusercontent.com/10731590/169082728-3435a489-ec4b-4b2f-ab8c-09c729bc7b60.png">

### Chakra UI Version

2.0.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by domhede** [comment]
I am facing a related issue.  The `overflow:hidden` within the `Accordion` cuts off any element inside:
In my case is the Select component from react-select.

Here is a reproduction:
https://codesandbox.io/s/frosty-forest-mwev80?file=/src/App.js

I suspect it may have been this change:
https://github.com/chakra-ui/chakra-ui/commit/aaadcd0ed9388417b0b647d75055ede0613d3495#diff-292a67f458d02eed2a987014502933bf75dd238edd557986c4994dbcf10d4faaL126

Perhaps it could be reverted?

**Comment by alexpuertasr** [comment]
@domhede in your case a quick fix should be using a portal for the select dropdown, here you have the solution:
https://codesandbox.io/s/sad-hill-60bku2?file=/src/App.js

**Comment by segunadebayo** [comment]
This is by design and intentional to get the Collapse functionality working.

Kindly resolve this issue within your app, by using portals or adding some padding (around 2px) to accommodate the input element's box shadow.

Thanks for understanding

**Comment by domhede** [comment]
Thank you for your responses. @alexpuertasr your example is much appreciated.

**Comment by lswainemoore** [comment]
Hi all, I just want to register that I don't think portals are always a good solution. For instance, when the Collapse will sometimes sit inside a modal, it is more difficult than simply creating a portal to document.body. And adding padding doesn't work for something like a dropdown menu. 

Looking at the change [here](https://github.com/chakra-ui/chakra-ui/pull/5783), it seems like there ought to be a better solution than just making overflow hidden all the time--if changing to initial on enter/hidden on exit doesn't work, that seems to be indicative of a deeper bug, no?
