### ISSUE TITLE
Drawer open/close function becomes progressively slower when adding dom nodes.

### ISSUE THREAD

**Issue by tumdav** [chakra-ui/chakra-ui#605]
Based on document nodes count it becomes slower and slower

**To Reproduce**
1. Create a page
2. Add drawer
3. Add 50 nodes (div with the small text)
4. Dynamically increase nodes count 
5. After each operation check drawer functionality

 - OS: macOs 10.14.6
 - Browser: chrome
 - Version: 80.0.3987.163 (Official Build) (64-bit)

**Comment by tumdav** [comment]
BTW,  it's not the only with drawer. After  each added node in the document, it makes render process slowly

**Comment by tumdav** [comment]
@segunadebayo you really don't care about performance issues? and you can close the ticket without asking at least one question?

**Comment by mplis** [comment]
For what it's worth, I can't reproduce this https://codesandbox.io/s/practical-kowalevski-f7q0c?file=/src/App.js

**Comment by tumdav** [comment]
@mplis https://codesandbox.io/s/wonderful-diffie-ojdmc?fontsize=14&hidenavigation=1&theme=dark please check this one

**Comment by segunadebayo** [comment]
Can't reproduce this as well @tumdav. Looked at your example and it works just fine on my end.

I feel if you notice any slowness, it might most likely come from your code.

Happy to see any example that reproduces this.

**Comment by mplis** [comment]
I don't think that's a problem with Chakra, I think the issue is that that example is re-rendering each node whenever the `isOpen` state changes. One solution would be to render each card with a component wrapped in `React.memo` https://codesandbox.io/s/quizzical-ives-yh85z?file=/src/App.js

**Comment by tumdav** [comment]
@mplis yes, you were right, thanks a lot
