### ISSUE TITLE
Stat components placed after LinkOverlay are not behind overlay

### ISSUE THREAD

**Issue by pianomansam** [chakra-ui/chakra-ui#6052]
### Description

When I place a Stat component in a LinkBox but after a LinkOverlay, I expect to be able to have it clickable. Instead, the text in the Stat is not clickable.

### Link to Reproduction

https://codesandbox.io/s/relaxed-hofstadter-7vgg29

### Steps to reproduce

1. Go to [https://codesandbox.io/s/relaxed-hofstadter-7vgg29](https://codesandbox.io/s/relaxed-hofstadter-7vgg29)
2. Hover over "Stat before LinkOverlay" and see how it's properly placed behind the overlay
3. Hover over "Stat after LinkOverlay" and see how it is not placed behind the overlay and thus not clickable.

### Chakra UI Version

2.0.2

### Browser

Google Chrome 101.0.4951.64

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by hugobqd** [comment]
I don't know if LinkOverlay should be modified, but you can easily fix your problem by adding `zIndex={-1}` to those position='relative' elements (<IconButton> and <Stat>)

**Comment by pianomansam** [comment]
@hugobqd IconButton does not suffer from this problem.

**Comment by hugobqd** [comment]
So just add zIndex={-1} to the Stat. Does it work for you ?

**Comment by pianomansam** [comment]
It works on this example. It doesn't work on my project, though. Is it to be expected that any position='relative' items after the LinkOverlay will not be overlaid?
