### ISSUE TITLE
Toast isActive instance method not working

### ISSUE THREAD

**Issue by VinRoi** [chakra-ui/chakra-ui#6055]
### Description

When using useToast the toast.isActive instance method always returns false even when the toast is active .  When using createStandaloneToast toast.isActive always returns 'undefined'.

### Link to Reproduction

https://codesandbox.io/s/jolly-fermat-wtsi2j?file=/src/StandaloneToast.tsx

### Steps to reproduce

Click on "Show Toast" or "Standalone Toast" to open Toasts. toast.isActive is logged in the console. 

### Chakra UI Version

2.0.2

### Browser

Google Chrome 101, Firefox 100, Edge 101

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by meerns** [comment]
Experiencing the same issue, also the `toast.closeAll()` is stopped working, I think it has to do with the reference issue, the new `ToastContainer` causing it, I'm using Next.js and I render the `ToastContainer` in `_app.tsx` .
