### ISSUE TITLE
Fix `_disabled` state of slider component

### ISSUE THREAD

**Issue by SpencerDuball** [chakra-ui/chakra-ui#6060]
### Description

When I hover the disabled slider component, I expect to see a `not-allowed` cursor type but I don't see any cursor.

### Link to Reproduction

https://codesandbox.io/s/fix-slider-add-disabled-state-cd8q66

### Steps to reproduce

1. Render a `<Slider/>` component, add the `isDisabled` prop.
2. Hover over the slider.
3. Observe that there is no `not-allowed` cursor.
> **Side Note:** Please see the disabled state on other components such as `Button`, `Checkbox`, or `Input` as examples. These components will provide a `not-allowed` cursor when disabled.

### Chakra UI Version

2.0.2

### Browser

Google Chrome 101.0.4951.64

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Here is what it looks like after the fix applied, sorry for the picture of screen. I couldn't get the hover state to say while taking a screenshot, it would appear even with a snapshot delay focus is given to the screenshot program before the actual capture.
![slider_disabled](https://user-images.githubusercontent.com/22606045/169420352-a3a52c9d-14d5-4446-a01b-6b6168eac3d5.jpg)

**Comment by segunadebayo** [comment]
Hi @SpencerDuball, we've been thinking of a way to make the disabled state more inclusive.

For more background see here: https://css-tricks.com/making-disabled-buttons-more-inclusive/

A possible side effect is to avoid using the "not-allowed" cursor property and just simply prevent interaction. This would allow the consumer to show a tooltip explaining why the slider is disabled.

**Comment by SpencerDuball** [comment]
@segunadebayo ahh I see that makes sense, I can edit the slider component to instead use the `aria-disabled` attribute as this would sill give the `cursor: not-allowed`. This would enable the `onClick`, `onMouseDown`, etc handlers to fire, but can add some code to disabled this when the `aria-disabled` is present as part of passing the `isDisabled` prop?

You did mention that this is already being looked into, I can make a commit with the changes described above or if this is already being worked I can close this issue & close #6061?
