### ISSUE TITLE
Modal fullscreen should not have a border radius by default

### ISSUE THREAD

**Issue by RubenSmn** [chakra-ui/chakra-ui#6066]
### Description

The modal component by default has a border radius, when using `size="full"`. When using its fullscreen size this is not necessary.

### Problem Statement/Justification

The fullscreen 'feeling' is less due to the fact that the fullscreen size is not really _full_

See: [https://codesandbox.io/s/chakra-ui-fullscreen-modal-xqgf2f?file=/src/index.js](https://codesandbox.io/s/chakra-ui-fullscreen-modal-xqgf2f?file=/src/index.js)

### Proposed Solution or API

Removing the border radius if the size is `full`

**Comment by anubra266** [comment]
Hi @RubenSmn you could contribute to chakra with this. Just add the `borderRadius: 'none'` here; https://github.com/chakra-ui/chakra-ui/blob/4449b7fdd5de8bab1cb690b7d0f86bd71f6e4650/packages/theme/src/components/modal.ts#L85
