### ISSUE TITLE
Modal: prevent scrolling on body and preserve body width

### ISSUE THREAD

**Issue by timothychandler** [chakra-ui/chakra-ui#6067]
### Description

When I set `blockScrollOnMount` to `true`, I expect scrolling on the body to be blocked and there to be only 15px padding/margin on the right, no matter what other props I set

### Link to Reproduction

https://codesandbox.io/s/unruffled-greider-986rpw?file=/src/index.tsx

### Steps to reproduce

**First scenario (too much extra padding)**
1. Implement a Button that opens a Modal
2. Add the prop `blockScrollOnMount={true}`
3. Click the Button to open the modal
4. Inspect the `<body>` in the dev tools
5. **Observed:** there is 15px margin AND 15px padding on the right side, which results in jumpy UI when opening and closing the modal
6. **Expected:** there is only 15px padding OR 15px margin on the right side and no jumpy UI

**Second scenario (body remains scrollable)**
1. Implement a Button that opens a Modal
2. Add the props `blockScrollOnMount={true}` AND `preserveScrollBarGap={true}` (uncomment it in the sandbox)
3. Click the Button to open the Modal
4. Move the cursor over the scrollbar of the body and attempt to scroll the page
5. **Observed:** the scroll bar is still visible and the page can be scrolled
6. **Expected:** there is 15px padding OR 15px margin in place of the scrollbar and the page cannot be scrolled

### Chakra UI Version

2.0.2

### Browser

Google Chrome 101

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Closing in favor of a duplicate issue #6084 which captures the issue better.
