### ISSUE TITLE
Allow overriding event handlers with javascript strings (Pure HTML style)

### ISSUE THREAD

**Issue by minism** [chakra-ui/chakra-ui#6068]
### Description

Allow overriding event handlers with javascript strings (Pure HTML style), which could be via a separate 'unsafe' or 'raw' API.

### Problem Statement/Justification

For server-side rendering with chakra, it would be very useful to be able to do something like:

      <Input
        onPaste="return false;"
        autoComplete="off"
      />

To produce HTML with some simple behavior (in this case, preventing pasting) in an environment where we're not serving js to the client.

However, chakra only accepts a function here, which is fine, but doesn't seem to allow any other way of setting a string explicitly for event handlers.

### Proposed Solution or API

Some new element API for setting raw attributes directly, or perhaps just for event handlers.

**Comment by segunadebayo** [comment]
Hi @minism,

Chakra UI is purely based on React and JSX, not vanilla JavaScript. Kindly use functions.

Thanks
