### ISSUE TITLE
[Tooltip] hidden behind div that is fixed positioned and has a background color set

### ISSUE THREAD

**Issue by frankhock** [chakra-ui/chakra-ui#607]
**Describe the bug**
Tooltip is hidden behind div that is `position: fixed` and has a background color set.

**Expected Behavior**
Expect to see the tooltip.

**To Reproduce**
- Use this template:

````
<div style={{ position: 'fixed', background: 'red', height: '100px', width: '200px' }}>
  <Tooltip label="Hello" aria-label="hello">
    Hi
  </Tooltip>
</div>
````

**Suggested solution(s)**
add `zIndex` prop to tooltip styling

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.4
 - Browser: chrome
 - Version: 80.0.3987.163

**Additional context**

**Comment by segunadebayo** [comment]
Hi @frankhock,

Thanks for raising this issue, we've resolved this in preparation for the next release.

I'm glad you found a walk around for it. In the next release, you're not going to need that `zIndex` anymore.
