### ISSUE TITLE
Show component causes a hydration failure in NextJS

### ISSUE THREAD

**Issue by romatallinn** [chakra-ui/chakra-ui#6070]
### Description

I am using Show for responsive design; in particular, to show an element only on large screens. But NextJS/React is complaining about changed UI (hydration error), compared to rendered on server. Can it be fixed somehow?

### Link to Reproduction

https://codesandbox.io/s/nextjs-chakra-show-u851f7?file=/components/headi.tsx

### Steps to reproduce

1. Open cidesandbox website
2. Open browser console
3. Observe `Warning: Expected server HTML to contain a matching <h2> in <div>.`
4. Locally, it would also throw a warning visually on the webpage that says hydration failure.

<img width="953" alt="Screenshot 2022-05-21 at 20 01 21" src="https://user-images.githubusercontent.com/14923964/169663828-8eb346d4-ea6e-4b78-9af1-3e2bd3381838.png">

### Chakra UI Version

2.0.2

### Browser

Firefox

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @romatallinn,

This was fixed in a recent PR. We're about to release a new version. If after the upgrade the problem still exists, I'll re-open
