### ISSUE TITLE
Add ability to make Drawer permanent

### ISSUE THREAD

**Issue by mikereinmiller** [chakra-ui/chakra-ui#608]
**Is your feature request related to a problem? Please describe.**
It would be nice if we had the ability to make the Drawer "permanent" so it flows inline with the document instead of just as a "modal".

**Describe the solution you'd like**
It would be nice if I could toggle the drawer state as needed to be permanent or temporary.  Maybe something like the drawer in material-ui https://material-ui.com/components/drawers/

It's possible I'm missing the props to pass into the drawer component to make it permanent.  Any help would be appreciated.

**Comment by aaronmcadam** [comment]
Have you tried working around this by adding your own styles @mikereinmiller? I think it'd be useful to see how it might be done, as a reference for the team.

**Comment by openarun** [comment]
Any update on the permanent sidebar/drawer ?

**Comment by Masaokb** [comment]
I think this would be a very nice function.

**Comment by nvme0** [comment]
Here's a minimal solution to achieve something similar to **Material-UI Mini Variant Drawer** https://material-ui.com/components/drawers/#mini-variant-drawer.

I had to write separate forward and reverse animations to make it to start the animation on state change. I wonder if there is a more elegant way to do this?

```ts
import { useState } from "react";
import {
  ...
  FiChevronRight,
  FiChevronLeft
} from "react-icons/fi";
import {
  Button,
  Stack,
  keyframes,
  InterpolationWithTheme
} from "@chakra-ui/core";

const forwardAnimation = keyframes`
  from {
    width: 68px;
  }
  to {
    width: 200px;
  }
`;

const reverseAnimation = keyframes`
  from {
    width: 200px;
  }
  to {
    width: 68px;
  }
`;

const DesktopMenu = () => {
  const [isOpen, setIsOpen] = useState(false);

  const buttonCss: InterpolationWithTheme<any> = {
    overflowX: "hidden",
    animation: isOpen
      ? `${forwardAnimation} 0.2s linear forwards`
      : `${reverseAnimation} 0.2s linear forwards`
  };

  return (
    <Stack
      {...{
        h: "100vh",
        backgroundColor: "#FFF"
      }}
    >
      <Stack
        {...{
          position: "sticky",
          top: 0
        }}
      >
          <Button
            {...{
              "aria-label": "Item 1",
              size: "lg",
              colorScheme: "blue",
              variant: "ghost",
              borderRadius: 0,
              justifyContent: "left",
              iconSpacing: 8,
              leftIcon: <FiCalendar />,
              css: buttonCss
            }}
          >
            Item 1
          </Button>
          <Button
            {...{
              "aria-label": "Item 2",
              ...
              css: buttonCss
            }}
          >
            Item 2
          </Button>
          <Button
            {...{
              "aria-label": "Item 3",
              ...
              css: buttonCss
            }}
          >
            Item 3
          </Button>
          <Button
            {...{
              "aria-label": "Item 4",
              ...
              css: buttonCss
            }}
          >
            Item 4
          </Button>
          <Button
            {...{
              "aria-label": "Expand",
              ...
              leftIcon: isOpen ? <FiChevronLeft /> : <FiChevronRight />,
              css: buttonCss,
              onClick: () => setIsOpen(!isOpen)
            }}
          />
      </Stack>
    </Stack>
  );
};

export default DesktopMenu;

```

**Comment by 8brandon** [comment]
Should this be closed if the conversation was still in progress? 
@nvme0 was asking for feedback if there was any more elegant way to do that. 

I haven't even played around with this yet but was wondering if there's an way to include this as some kind of a layout component that wraps all your other components.

**Comment by kxshen** [comment]
I made a manual sidebar using the "transitions" from v1.0 (https://chakra-ui.com/docs/components/transitions#slide-transition) to achieve a drawer that allows for interaction outside of it (i.e. not a modal). That way, you can manually customize your own button interactions, set styles, insert layout components, make persistent, etc. But for a "permanent" drawer can't you just have a normal layout component w/ styling, the contents of DrawerContent, essentially?

Can paste code if needed, but the example code there works pretty well. Also not sure about how to make it "push", if that's desired. And apologies I'm very new to React! Would be nice to have this easily toggleable as a prop for the drawer component as well.

**Comment by bawahakim** [comment]
@kxshen Some code would be lovely! Trying to make a toggleable drawer as @nvme0 did. Using slide transition seems like a good option, but haven't had a chance to really make it work.

**Comment by kxshen** [comment]
I found it to work nicely! Pasting code below, can try to clarify anything if needed. 

In the JavaScript section, I used the `useDisclosure()` hook, can probably configure it using the normal `useState()` hooks in some way, but this was easiest:
`const { isOpen, onToggle } = useDisclosure() /* Control panel opening */`

In the `return()`, I essentially put a `<VStack>` within the `<Slide>` to contain all my contents, can probably use other layout components too. Apologies for the messiness/manual positioning practices, shortened from the drawer within https://kevmapper-detroit.herokuapp.com/:
```
{/* Drawer toggle button at top left */}       
<div style={{position: 'absolute', left: '5px', top: '5px', zIndex: '100'}}>
    <Button ref={btnRef} colorScheme="teal" onClick={onToggle}>
         Controls
    </Button>           
</div> 

{/* Imitation drawer below */}
<Slide direction="left" in={isOpen} style={{height:'100vh', width: '300px', zIndex: 100 }}>
        <VStack            
          color="black"
          bg="white"
          rounded="md"
          h="100vh"
          w="300px"
          overflowY="scroll">
          <Box p={5} shadow="md" borderWidth="1px" m="5px" bg="purple.700" color="white">
            <Flex> {/* Put in a flex to get the close button on the right */}
              <Heading fontSize={28}>Title <span role="img" aria-label="bus">🚌</span> </Heading>
              <IconButton aria-label="Close Control Panel" icon={<CloseIcon />} onClick={onToggle} color="black"/>
            </Flex>
            <i> Last updated: January 4, 2021</i></Text>
          </Box>
          <Box p={5} shadow="md" borderWidth="1px" m="5px">
            <Heading fontSize="xl">Insert more contents!!</Heading>
          </Box>
           {/* Insert other contents */}
        </VStack>
</Slide>
```

**Comment by MAfzalKhan1997** [comment]
Any update for permanent solution of this  ?

**Comment by segunadebayo** [comment]
Thanks for the request! Considering this isn't a bug, I'll add this to our project board so you can track the progress.

Cheers.

**Comment by hb12DevTn** [comment]
Any update on this feature?

**Comment by iamclaytonray** [comment]
Here's a code sandbox based on some work I recently did at my job. It's definitely not perfect but Drawer doesn't support this behavior. However, content does push and I made it responsive (mostly). Hope it helps until Chakra releases full support for a permanent drawer

[CodeSandbox](https://codesandbox.io/s/trusting-voice-8jvl0?file=/src/index.tsx)

**Comment by iamclaytonray** [comment]
I'm sorry to be repetitive but is there a possible timeline for this feature?

**Comment by luka-rmar** [comment]
Any news about the release of the feature?

**Comment by dindustack** [comment]
Has the feature being implemented?

**Comment by sultan-aslam** [comment]
@segunadebayo. is this feature is in v1.6.4 or not ???

**Comment by aaronmcadam** [comment]
> @segunadebayo. is this feature is in v1.6.4 or not ???

As Segun already said, this issue is on the roadmap, but the team have not committed to working on it yet: https://github.com/chakra-ui/chakra-ui/projects/6#card-53849082

**Comment by aaronmcadam** [comment]
Seeing as this issue has already shown some known workarounds, it will probably have low priority for a while.

**Comment by sultan-aslam** [comment]
@aaronmcadam is there any estimated deadline for this feature... ???

**Comment by aaronmcadam** [comment]
> @aaronmcadam is there any estimated deadline for this feature... ???

There's no deadline because it's not being worked on. The Parking Lot column in the roadmap means that there's no commitment to work on it.

**Comment by DVGY** [comment]
Please solve this issue, it kind of irritating when Drawer reopen if we click on some element

**Comment by thecodeclimber** [comment]
It would be nice if we could have a simple and elegant solution to this problem.  People should not have to search through Github issues to solve something as simple as making a drawer permanent -- particularly since this is such a common UI pattern in web and app design.

**Comment by transitive-bullshit** [comment]
It appears that Chakra UI Pro includes [Sidebar components](https://pro.chakra-ui.com/components/application/sidebars) for this use case, so I'm guessing the team is prioritizing base components in the free library and compound use cases in the paid version.

imho this is a sensible tradeoff. I just wish it was communicated more clearly and that there was a note on the `Drawer` component itself since this is such a common use case.

**Comment by landermedia** [comment]
@transitive-bullshit If we take a look at [Application Shells](https://pro.chakra-ui.com/components/application/shells) where `Sidebar Components` are applied, it still uses `Drawer` component so I doubt that'll solve things.

**Comment by darokviana** [comment]
I took a look at the roadmap and didn't find any records related to this functionality. It would really be great to be able to have this natively in the library.
