### ISSUE TITLE
react-dom/client error in @chakra-ui/typescript

### ISSUE THREAD

**Issue by jcstein** [chakra-ui/chakra-ui#6080]
### Description

When I ran `yarn create react-app my-app --template @chakra-ui/typescript` I am receiving the following error when running `yarn start` 

### Link to Reproduction

yarn create react-app my-app --template @chakra-ui/typescript

### Steps to reproduce

1. Run `yarn create react-app my-app --template @chakra-ui/typescript`
2. CD into `my-app`
3. `yarn start`
4.  errors

### Chakra UI Version

yarn create react-app my-app --template @chakra-ui/typescript

### Browser

Brave

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Compiled with problems:X

ERROR in src/index.tsx:3:27

TS7016: Could not find a declaration file for module 'react-dom/client'. '/Users/joshstein/BUILDING/my-app/node_modules/react-dom/client.js' implicitly has an 'any' type.
  If the 'react-dom' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom'
    1 | import { ColorModeScript } from "@chakra-ui/react"
    2 | import * as React from "react"
  > 3 | import * as ReactDOM from "react-dom/client"
      |                           ^^^^^^^^^^^^^^^^^^
    4 | import { App } from "./App"
    5 | import reportWebVitals from "./reportWebVitals"
    6 | import * as serviceWorker from "./serviceWorker"

**Comment by mszklanko** [comment]
To fix update `@types/react` `@types/react-dom`
This was helpful: https://blog.logrocket.com/how-to-use-typescript-with-react-18-alpha/

**Comment by segunadebayo** [comment]
Fixed in a recent PR. We'll publish an update soon

**Comment by jcstein** [comment]
thank you @mszklanko and @segunadebayo 🎉
