### ISSUE TITLE
SyntaxError: Undefined label 'e' (@chakra-ui/cli)

### ISSUE THREAD

**Issue by nick-kang** [chakra-ui/chakra-ui#6081]
### Description

When I run `chakra-cli tokens src/styles/theme.ts`, I get the error `SyntaxError: Undefined label 'e'`

### Link to Reproduction

https://github.com/nick-kang/chakra-ui-cli-bug-01

### Steps to reproduce

1. clone [repo](https://github.com/nick-kang/chakra-ui-cli-bug-01)
2. run `yarn` to install packages
3. run `yarn build:chakra` to build tokens
4. see error

### Chakra UI Version

2.0.0

### Browser

Google Chrome 101

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

This is the log output when I run chakra-cli tokens

```
 Chakra UI CLI  v2.0.0 by Chakra UI
Generate theme typings for autocomplete


✖ An error occurred
SyntaxError: Undefined label 'e'
```

pacakges:
```json
{
  "dependencies": {
    "@chakra-ui/pro-theme": "^0.0.49",
    "@chakra-ui/react": "2.0.2",
    "@emotion/react": "^11",
    "@emotion/styled": "^11",
    "framer-motion": "^6",
    "pino": "^7.11.0",
    "react": "18",
    "react-dom": "18"
  },
  "devDependencies": {
    "@chakra-ui/cli": "^2.0.0",
    "@types/react": "18.0.9",
    "@types/react-relay": "^13.0.2",
    "prettier": "^2.4.1",
    "typescript": "4.6.4"
  }
}
```

**Comment by albusphan** [comment]
Confirmed, I facing same issue with the pro theme
cc @segunadebayo

**Comment by TimKolberger** [comment]
I ran into this issue as well in one of my projects. Setting the baseUrl in tsconfig.json solved it for me. 

Nevertheless the CLI error handling needs some love.

**Comment by albusphan** [comment]
hi @TimKolberger , could you sare your baseUrl config 🙇

**Comment by segunadebayo** [comment]
This has been fixed in a recent PR. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
