### ISSUE TITLE
Components that use react-remove-scrollbar shift screen

### ISSUE THREAD

**Issue by 0xIvan** [chakra-ui/chakra-ui#6084]
### Description

Since Chakra v2, any component that uses react-remove-scrollbar (modal, drawer), when open, it shifts the html body

### Link to Reproduction

https://chakra-ui.com/docs/components/overlay/modal

### Steps to reproduce

1. Go to https://chakra-ui.com/docs/components/overlay/modal
2. Click on any 'open modal'
3. See page shift to the left because there is a padding-right and margin-right being applied.

### Chakra UI Version

2.1.0

### Browser

Chrome latest, Safari latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This issue can be reproduced in the docs page. When interacting with V1.8.8 docs, the issue is not there. Not sure if it has to do with the `react-remove-scrollbar` package (since it was updated in Chakra v2), or within Chakra code.

**Comment by segunadebayo** [comment]
I can confirm that this is a bug from `react-remove-scrollbar`.

**Here's a repro:**
https://codesandbox.io/s/react-remove-scroll-l84vvw?file=/src/App.js
