### ISSUE TITLE
Combining _hover & _before

### ISSUE THREAD

**Issue by akiarostami** [chakra-ui/chakra-ui#609]
On **_hover** I need to change some css values in **_before**, but with the current structure that doesn't seem to be possible (or I couldn't find it!)

We should have a way to combine _hover, _active, _focus, _before, _after, _etc.

**Comment by akiarostami** [comment]
I found the solution:

`_hover={{ "&:before": { ... }}}`

**Comment by segunadebayo** [comment]
Glad you found a solution @akiarostami
