### ISSUE TITLE
regression in toast component and Next.js

### ISSUE THREAD

**Issue by JTBrinkmann** [chakra-ui/chakra-ui#6096]
### Description

I cannot use Toasts with Chakra UI v2.1.1 and Next.js

### Link to Reproduction

https://codesandbox.io/s/flamboyant-elbakyan-yrpxmo

### Steps to reproduce

for existing projects:
1. upgrade to Chakra UI v2.1.1
2. start server with `npx next dev`
3. open a page that uses `useToast()`

for a clean template:
1. create a Next.js project `yarn create next-app --typescript my-app`
4. add Chakra UI dependencies `yarn add @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^6`
5. add Chakra UI provider
6. add `useToast()` to index.tsx
7. run `yarn dev`
8. open page

### Chakra UI Version

2.1.1

### Browser

Firefox 99

### Operating System

- [ ] macOS
- [X] Windows
- [X] Linux

### Additional Information

I assume this is because #6091 [introduced](https://github.com/chakra-ui/chakra-ui/pull/6091/files#diff-bf450a9a984fe33c62cfe00d54efdb5623aea6fdbe032da1ea5a54ee09e3059bR95) `React.useSyncExternalStore`, which apparently causes this issue with Next.js? I didn't investigate further, yet.

**Comment by nftgeek** [comment]
I'm also using Toast and I've seen the same error.
```
Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.
```

**Comment by segunadebayo** [comment]
Yes, I can confirm this is a regression in the toast component. Working on a fix for it now.
