### ISSUE TITLE
npm ERR! notarget No matching version found for @chakra-ui/alert@2.0.1

### ISSUE THREAD

**Issue by a-vitug** [chakra-ui/chakra-ui#6107]
### Description

Having trouble installing npm bc it keeps giving me an error

### Link to Reproduction

https://www.npmjs.com/package/@chakra-ui/alert

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.0.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

<img width="765" alt="Screen Shot 2022-05-25 at 2 37 23 AM" src="https://user-images.githubusercontent.com/93061615/170237865-7df37dc2-9544-4ecd-b626-93f699bb8d69.png">

<img width="1422" alt="Screen Shot 2022-05-25 at 3 02 55 AM" src="https://user-images.githubusercontent.com/93061615/170237302-24b5e2f7-1012-40b2-bcc8-ceaebf0036e0.png">

**Comment by amirsinaa** [comment]
yup, same here
https://github.com/chakra-ui/chakra-ui/issues/5855#issuecomment-1137041951

**Comment by bitbeckers** [comment]
Duplicate? https://github.com/chakra-ui/chakra-ui/issues/6104

**Comment by puthrayaharness** [comment]
I am seeing the same issue. I tried - 
```
yarn add @chakra-ui/button@2.0.0
```

I see - 
```
➤ YN0001: │ Error: @chakra-ui/alert@npm:2.0.1: No candidates found
```

Also
```
yarn add @chakra-ui/button

➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @chakra-ui/utils@npm:2.0.1: No candidates found
```

Looks like a bunch of packages are missing.

**Comment by amirsinaa** [comment]
As [Pagebakers mentioned](https://github.com/chakra-ui/chakra-ui/issues/5855#issuecomment-1137068259) it's probably an npm issue 

https://status.npmjs.org/
> May 24, 2022
[Some published packages do not show up in registry](https://status.npmjs.org/incidents/4zkt80fxq1nb)
Resolved - This incident has been resolved.
May 24, 13:39 UTC
Identified - Publishing is working. Some of the packages versions published between 2022-05-23 21:00UTC and 2022-05-24 11:00UTC have not been published correctly. We are currently backprocessing these package versions.
May 24, 11:58 UTC
Investigating - We are currently investigating this issue.
May 24, 10:57 UTC

**Comment by BenBktech** [comment]
Same error there

**Comment by DuckniceWork** [comment]
Same issue here for a build with react 18.1 and nextJs 12.1.6 built with pnpm.
All chakra/react 2.x builds give: 

ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @chakra-ui/alert@2.0.1
The latest release of @chakra-ui/alert is "2.0.0"

**Comment by abdulbasetbasher** [comment]
you can set registry cdn temporary while the main registry get fixed

npm config set registry http://r.cnpmjs.org/

**Comment by rushi7997** [comment]
same here

**Comment by TheRuslan** [comment]
the same problem

**Comment by jkgatt** [comment]
Changing repository wasn't working for me, so what I did was downgrade the chakra-ui version to thew last working one:

```
npm i @chakra-ui/react@2.1.0 @emotion/react@^11 @emotion/styled@^11 framer-motion@^6
```

Hope this helps some of you, until the registry fixes this issue!

**Comment by abdulbasetbasher** [comment]
> Changing repository wasn't working for me, so what I did was downgrade the chakra-ui version to thew last working one:
> 
> ```
> npm i @chakra-ui/react@2.1.0 @emotion/react@^11 @emotion/styled@^11 framer-motion@^6
> ```
> 
> Hope this helps some of you, until the registry fixes this issue!

@chakra-ui/react must be removed from package.json in order to retrieve it from the new repository.

**Comment by jkgatt** [comment]
> > Changing repository wasn't working for me, so what I did was downgrade the chakra-ui version to thew last working one:
> > ```
> > npm i @chakra-ui/react@2.1.0 @emotion/react@^11 @emotion/styled@^11 framer-motion@^6
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope this helps some of you, until the registry fixes this issue!
> 
> 👉 @chakra-ui/react must be removed from package.json first in order to retrieve it from the new repository.

Great this works too, ill stick to version 2.1.0 for now and upgrade later! Thanks @abdulbasetbasher
