### ISSUE TITLE
SSR needs a default width to render the same as the client

### ISSUE THREAD

**Issue by DevAlien** [chakra-ui/chakra-ui#611]
**Describe the bug**
When using SSR the returned html is different than the one generated by the client, That's because of the conditional rendering like `display={{md: "none", sm: "block"}}` Is there a way to define the default width when one is not set? For example material-ui has an initialWidth that you can set on your theme, so the content that comes from the server is the same, in most cases.
```
 initialWidth: isMobile ? "sm" : "lg" // Breakpoint being globally set 🌎!
```
To know if it is mobile or a presumeably bigger monitor you can check the agent that is sent to the server.
Actually it seems it is using mediaqueries for that, which is good, but then why does it generates 2 different classes?
I will investigate more

**Expected Behavior**
Code sent to the client from SSR should be the same as the one generated in the client.

**Comment by DevAlien** [comment]
```
<Box mt={{ base: 4, md: 0 }}>asd</Box>
```

on client generates
```
.css-15wo4ec{margin-top:1rem;}
@media screen and (min-width:48em){.css-15wo4ec{margin-top:0;}}
```

On server generates
```
.css-8kn4zf{margin-top:0;}
```

**Comment by DevAlien** [comment]
Installing emotion and emotion-server and setting it up solved the issue.

https://emotion.sh/docs/ssr

**Comment by segunadebayo** [comment]
Hi @DevAlien,

I'm glad you found a solution. Do you mind sharing a snippet of the setup that worked for you? so it can be useful for others.

Thanks

**Comment by DevAlien** [comment]
Basically the extractCritical was the solution.

```
import { renderToString } from 'react-dom/server'
import { extractCritical } from 'emotion-server'
import App from './App'

const { html, ids, css } = extractCritical(renderToString(<App />))
```

an example on next.js => https://github.com/zeit/next.js/blob/master/examples/with-emotion/pages/_document.js

And the emotion documentation => https://emotion.sh/docs/ssr#extractcritical

**Comment by segunadebayo** [comment]
Amazing. Thanks.
