### ISSUE TITLE
'@chakra-ui/tabs@https://r.cnpmjs.org/@chakra-ui/tabs/-/tabs-2.0.2.tgz' is not in this registry.

### ISSUE THREAD

**Issue by Blazerker** [chakra-ui/chakra-ui#6110]
### Description

When compiling with Vercel a dependency issue pops up with tabs-2.0.2 not in registry

### Link to Reproduction

n/a

### Steps to reproduce

npm ERR! 404  '@chakra-ui/tabs@https://r.cnpmjs.org/@chakra-ui/tabs/-/tabs-2.0.2.tgz' is not in this registry.

The error comes up deploying with vercel.com

### Chakra UI Version

2.1.2

### Browser

n/a

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @Blazerker,

This will be fixed in our next release. Not exactly an issue on our part.
