### ISSUE TITLE
extendTheme will not allow me to override custom base theme as docs describe 

### ISSUE THREAD

**Issue by arnoldsandoval** [chakra-ui/chakra-ui#6111]
### Description

When I override a custom base theme I expect it to be overriden, but nothing happens

### Link to Reproduction

https://codesandbox.io/s/magical-kilby-somvkk?file=/src/App.tsx

### Steps to reproduce

1. Go to [codesandbox example](https://codesandbox.io/s/magical-kilby-somvkk?file=/src/App.tsx) and review the code.
    - Pay special attention to the base theme and theme overrides
    - On line 76 you can see we have our `baseTheme` being called as the last parameter, which is correct per the [documentation](https://chakra-ui.com/docs/styled-system/theming/customize-theme#using-theme-extensions)
2. Notice that the `baseThemeOverrides` are not being respected
3. Uncomment line 77, this line puts the `baseThemeOverrides` as the last parameter. The behavior works as one would expect.

### Chakra UI Version

1.8.6 but can also repro in 2.0.0

### Browser

Tested with Chrome v101.0.4951.64 and Safari v15.5 (17613.2.7.1.8)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Given that I can get this to work by inverting the order of the `baseTheme` and `baseThemeOverride` I'm not sure if this is a bug within the code, or if it's an issue with the documentation.

I suspect it has something to do with the way in which backward compatibility support was implemented here: https://github.com/chakra-ui/chakra-ui/blob/main/packages/react/src/extend-theme.ts#L80-L89

**Comment by JTBrinkmann** [comment]
maybe the term "baseTheme" is misleading. It refers to something else than what you apparently interpret it as. Your example's `const baseTheme` does not qualify as a "base theme" in the sense that the documentation uses that phrasing. To be considered a "base theme", it must have a few required things / pass the `isChakraTheme` test that you can see here https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/utils.ts#L25-L33

In my opinion, you should ignore the "base theme" part of the documentation and just pass your objects from left to right. It is meant for cases, where you already have a theme that's returned by `extendTheme`, e.g. from an external module.

**Comment by arnoldsandoval** [comment]
This was marked as closed, but I don't believe the question was answered. Is my followup an issue with my code, or is there in fact an issue within chakra?

**Comment by anubra266** [comment]
@arnoldsandoval @JTBrinkmann's comment is the answer to your question.
