### ISSUE TITLE
Reopen #3287 as it creates an inconsistent UI

### ISSUE THREAD

**Issue by advename** [chakra-ui/chakra-ui#6114]
### Description

Reopen https://github.com/chakra-ui/chakra-ui/issues/3287

### Link to Reproduction

https://github.com/chakra-ui/chakra-ui/issues/3287

### Chakra UI Version

all

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is a known issue and we're looking into it

**Comment by elauser** [comment]
Leaving a mark here, this is an issue for me too.

**Comment by benchilds** [comment]
When will this get resolved? It seems like a fundamental part of how the Heading component should be used. If I render a Heading using `<Heading as="h2">` then I shouldn't have to also specify a size or variant just to get it to appear as an H2.

**Comment by elauser** [comment]
@benchilds I got a workaround working in my codebase.

In the chakraUI component Config I overwrite the Heading sizes

```
const Heading: ComponentStyleConfig = {
  // hacky fix to remove standard heading sizes from chakra to be able to use custom sizes
  sizes: null as unknown as undefined,
}
```

and in the global styles I can overwrite the h and it works

```
export const styles = {
  global: {
    h1: {
      fontSize: ['4xl', '5xl'],
    },
    h2: {
      fontSize: ['3xl', '4xl'],
    },
    h3: {
      fontSize: ['2xl', '3xl'],
    },
    h4: {
      fontSize: ['xl', '2xl'],
    },
    h5: {
      fontSize: ['lg', 'xl'],
    },
    h6: {
      fontSize: ['md', 'lg'],
    },
...
```
I hope this helps everyone else who had this problem.
So yeah while in theory the heading type shouldn't affect its size, it's nice to have a consistent default sizing going on.

**Comment by morganm58** [comment]
Any update on this?
