### ISSUE TITLE
Internal hooks are exposed to end-users

### ISSUE THREAD

**Issue by yukukotani** [chakra-ui/chakra-ui#6122]
### Description

Some hooks such as `useModal` seem not designed for end-users, but it's exported from `@chakra-ui/react` package.

### Link to Reproduction

https://codesandbox.io/s/vibrant-http-v67ioy?file=/src/index.js

### Steps to reproduce

1. Import `useModal` from `@chakra-ui/react`

### Chakra UI Version

2.1.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @yukukotani, we plan to establish a much better API surface in the next major, but this is intentional for now.

We allow users to compose their own components in the event our components don't meet their design requirements.
