### ISSUE TITLE
"Why Can't I" tooltip preset

### ISSUE THREAD

**Issue by david-morris** [chakra-ui/chakra-ui#6127]
### Description

I'd like a switch for Tooltip that caused the tooltip to display when the child was a disabled control, and to be hidden otherwise.

### Problem Statement/Justification

I find a common pattern is that I want to use a tooltip to explain to the user why a control is disabled when they mouseover.
Therefore, it would be useful to invert whether a tooltip got shown based on the isDisabled of the child.

### Proposed Solution or API

I think that `invertChildDisable` or `explainIsDisabled` would be clear names for switch props.

### Alternatives

For now I have to get the information as to whether the prop should be disabled from outside, which works, but isn't pretty.

**Comment by anubra266** [comment]
@david-morris this issue is not clear.
