### ISSUE TITLE
ChakraProvider breaks Suspense when reloading in Next.js project

### ISSUE THREAD

**Issue by mu-suke** [chakra-ui/chakra-ui#6129]
### Description

When I reloaded the screen I used with react 18 suspense and Next.js, I expected to display correctly happen but instead an error was displayed.

### Link to Reproduction

https://codesandbox.io/s/stoic-violet-b8beh4?file=/pages/index.tsx

### Steps to reproduce

1. Create Next.js App
2. Add a Suspense component into pages/index.tsx
3. Verify it works fine (should)
4. Add @chakra-ui/react and <ChakraProvider> into _app.tsx
5. Reload the page - emits the following error:

```
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.
```

### Chakra UI Version

2.1.2

### Browser

Firefox, Chrome, Safari

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This issue seemed to have solved the problem, but it still seems to be occurring.
Please check.

https://github.com/chakra-ui/chakra-ui/issues/5842

**Comment by m90khan** [comment]
Any idea on when this issue will be fixed?. I am having the same issue as well :)

**Comment by r29taheri** [comment]
I am still having this issue
Repository: https://github.com/r29taheri/livechain
Error: https://reactjs.org/docs/error-decoder.html/?invariant=418

**Comment by jca41** [comment]
Same issue with latest of all packages

**Comment by AlfieDarko** [comment]
Same as above, still getting this issue

**Comment by Mounajidev** [comment]
it seems i could fix same error with the solution 4 of this post. 
[](https://ittutorialpoint.com/solved-react-18-hydration-failed-because-the-initial-ui-does-not-match-what-was-rendered-on-the-server/)
