### ISSUE TITLE
iconButton: Change border color

### ISSUE THREAD

**Issue by erichodges** [chakra-ui/chakra-ui#613]
I want to change the border color.

I tried:
borderColor="#000"
borderColor="none"
border="0px"
borderStyle="none"

I would prefer, in this case, to not have a border.
I'm using the CSSReset component. The borderColor is showing on both the light and dark theme as normal. 

The iconButton is getting the border color on each edge separately, which is interesting.
I tried:
border-top-color="#000"
This had no effect.

I'm using chakra-ui in a gatsby project. I'm very excited about Chakra! :-)

**Comment by erichodges** [comment]
Ok, I fixed it via the method in this article:
https://medium.com/@keeganfamouss/accessibility-on-demand-with-chakra-ui-and-focus-visible-19413b1bc6f9

**Comment by javierfuentesm** [comment]
@erichodges  is there any other way ?? to achieve this ? I have been trying to change the border-color  when  hover, focus and on active , but i couldnt figure it out how to do it

**Comment by erichodges** [comment]
@javierfuentesm Sorry for the late reply. I don't know. I have not looked at this for a long time. With Gatsby, I changed over to theme-ui, which I like more. If Chakra would fix the  dark/light mode, which they may have, it would be really good.
