### ISSUE TITLE
useMediaQuery value is incorrect on first render

### ISSUE THREAD

**Issue by trybick** [chakra-ui/chakra-ui#6130]
### Description

When using useMediaQuery, the value it returns is incorrect on first render.

### Link to Reproduction

https://codesandbox.io/s/usemediaquery-testing-xkv2dh?file=/src/App.tsx

### Steps to reproduce

1. Go to the codesandbox link
2. Open the console
3. Notice the initial value is `false` while subsequent values are `true`

### Chakra UI Version

2.1.2

### Browser

Google Chrome 102

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Why is it important that the initial value be correct? Some components might take a prop like `initialView` which gets passed the first value from useMediaQuery and updating this prop doesn't help because it only looks at the initial value. Ideally, the initial value of useMediaQuery would be accurate.

**Comment by segunadebayo** [comment]
The reason this is happening is we designed the hook to work with SSR apps. Perhaps we can improve the logic to check if we're purely client-side rendering and set the default value on render first.

For SSR apps, the behavior remains like we currently have. Fixing it will lead to a hydration mismatch.
