### ISSUE TITLE
Drawers on iOS safari are wonky

### ISSUE THREAD

**Issue by saltnpixels** [chakra-ui/chakra-ui#6131]
### Description

when opening a Drawer component, the content inside does not scroll nicely. It's jumpy. and the bottom gets chopped off.

### Link to Reproduction

https://chakra-ui.com/docs/components/overlay/drawer#other-components

### Steps to reproduce

1. Go to the site above on mobile safari
2. open the drawer
3. try scrolling up and down.

### Chakra UI Version

2.1.0

### Browser

iOS Safari

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Would recommend not using a position fixed container inside the position fixed container. Use absolute inside the fixed and give it an overflow of auto. I think this might help.

Additionally I noticed you set overflow: hidden on the body, but not the html tag. I think you should add hidden to the html tag too, to override anything set in there. Some sites use overflow-x: hidden on the html tag and this can cause issues when used with the chakra modals.

**Comment by wrux** [comment]
Although it's [not well supported yet](https://caniuse.com/mdn-css_types_length_viewport_percentage_units_dynamic). Once it ships in Chrome, perhaps a better solution could be to use `height: '100dvh'` with the `@supports` directive.

**Comment by RobSchilderr** [comment]
Having the same issue..

**Comment by bhatvikrant** [comment]
facing the same issue

**Comment by saltnpixels** [comment]
I got things working by giving the DrawerContent component an overflow of auto and then directly inside is a Box with minHeight of 100vh.

Everything goes in that Box. Scrolling should work better on safari with that setup.

**Comment by iNetJoJo** [comment]
doing full height and with on DrawerOverlay fixes the issue.
```tsx
<Drawer isOpen={isOpen} placement="left" onClose={onClose} size="full">
			<DrawerOverlay width="full" h="full" />```

**Comment by segunadebayo** [comment]
Closing based on https://github.com/chakra-ui/chakra-ui/issues/6131#issuecomment-1557154432
