### ISSUE TITLE
Replace react-icons with react-feather

### ISSUE THREAD

**Issue by bingalls** [chakra-ui/chakra-ui#6133]
### Description

I can't tell, if it is causing my display issues, but 5 year old deprecation errors overloading logs could easily break in the next React v19, if not already.

### Problem Statement/Justification

react-icons keeps throwing deprecation warnings.
Visiting issues on their github repo shows that this is a problem that's overwhelmed the new maintainer for years.

### Proposed Solution or API

I gave up on trying a few SVG libs for React.
Just dropping in https://github.com/feathericons/react-feather worked fast & easy.
Works with React v18, and MIT license.
Updates could be better, but are better than react-icons, with fewer open issues.
No tree shaking needed! Early performance check looks great.

### Alternatives

- css.gg
- icomoon

**Comment by anubra266** [comment]
@bingalls I don't really understand. Replace them where, `react-icons` is not a dependency for chakra ui.
