### ISSUE TITLE
Custom global toast options

### ISSUE THREAD

**Issue by baptisteArno** [chakra-ui/chakra-ui#6134]
### Description

I'd like to be able to set the default position of all my toasts in one location.

### Problem Statement/Justification

The problem is that currently I need to set the position on each one of my toasts:

```ts
const toast = useToast({
    position: 'bottom-right',
    status: 'error',
  })
```

It's redundant. I'd like to set the `position` attribute somewhere once.

### Proposed Solution or API

Could be great to set defaults in the custom theme

**Comment by Patrick-Ullrich** [comment]
As someone who had the same need before (not just with toast), I think it's a good practice to wrap Chakra components when needed anyways, so you could do something like this:

```
import { useToast as useChakraToast } from '@chakra-ui/toast';
import { IToastProps, Toast } from './Toast';

export const useToast = () => {
  const toast = useChakraToast();

  const showToast = ({
    duration = 6000,
    message,
    variant,
  }: IProps) => {
    toast({
      duration,
      isClosable: true,
      position: 'top-right', // <--- HERE
      render: ({ onClose }) => (
        <Toast // <--- My Custom Toast 
          message={message}
          onClose={onClose}
          variant={variant}
        />
      ),
    });
  };

  return { showToast };
};
```

There will always be some props that you might not be able to default (especially things that are not part of the **theme**), and this will always work. 👍

**Comment by baptisteArno** [comment]
Right, I wonder why I didn't think about that... Thanks man!

**Comment by salman486** [comment]
I am doing this.

import { useToast as useChakraToast, UseToastOptions } from "@chakra-ui/react";

const toastConfig = {
  duration: 3000,
  isClosable: true,
};

export const useToast = () => {
  const toast = useChakraToast();

  const showSuccessToast = (message: string, props: UseToastOptions = {}) => {
    toast({
      title: "Success",
      description: message,
      status: "success",
      ...toastConfig,
      ...props,
    });
  };

  const showErrorToast = (message: string, props: UseToastOptions = {}) => {
    toast({
      title: "Error",
      description: message,
      status: "error",
      ...toastConfig,
      ...props,
    });
  };

  const showToast = (props: UseToastOptions = {}) => {
    toast({
      ...toastConfig,
      ...props,
    });
  };

  return { showSuccessToast, showErrorToast, showToast };
};
