### ISSUE TITLE
Can't update slider value programmatically

### ISSUE THREAD

**Issue by ssadler** [chakra-ui/chakra-ui#6136]
### Description

When I update Slider defaultValue, I expect the slider current value to change. 

### Link to Reproduction

https://codesandbox.io/s/damp-waterfall-8fxte6?file=/src/index.js

### Steps to reproduce

In the sandbox example, the component with the slider has an effect which updates the slider range, this works correctly, but the slider defaultValue is not reflected. The idea is to be able to update the current value.

### Chakra UI Version

2.1.2

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

It is possible to set the slider value using `value={n}`, but then the slider will be locked to that value, and the user will not be able to change it.

**Comment by hugobqd** [comment]
Hello! I'm not sure what behaviour you exactly wan't but that doesn't look like an issue to me.

However here is a modified sandbox where "things kinda works": https://codesandbox.io/s/relaxed-tdd-r9tk1l?file=/src/index.js

- controlling the slider by using _value_ to update the render.
- give an empty dependency `[]` to the useEffect to fire it only on first render.
- give a fixed 'max' to the slider (I can't figure how a slider with changing range can work)

**Comment by anubra266** [comment]
@ssadler when you want to control an element, use `value` and not `defaultValue`. `defaultValue` specifies the initial value for an uncontrolled component.
![CleanShot 2022-06-04 at 01 55 13@2x](https://user-images.githubusercontent.com/30869823/171970266-76d7bba7-ef19-40de-b477-b7aa28f7bc82.png)
![CleanShot 2022-06-04 at 01 55 37@2x](https://user-images.githubusercontent.com/30869823/171970270-6e1b7ea5-f9dc-4829-a639-e52f051840be.png)

**Comment by SampadaVp** [comment]
Thanks this helped!
