### ISSUE TITLE
Typescript error in Editable example - getSubmitButtonProps  types incompatibile with IconButton

### ISSUE THREAD

**Issue by allenchuang** [chakra-ui/chakra-ui#6147]
### Description

When I'm copy and pasting the code in the Editable example, getSubmitButtonProps seems to be imcompatible when spreading the props with IconButton

### Link to Reproduction

https://chakra-ui.com/docs/components/form/editable#with-custom-input-and-controls

### Steps to reproduce

1. Go to 'https://chakra-ui.com/docs/components/form/editable#with-custom-input-and-controls'
2. Copy the example for 
```
function CustomControlsExample() {
  /* Here's a custom control */
  function EditableControls() {
    const {
      isEditing,
      getSubmitButtonProps,
      getCancelButtonProps,
      getEditButtonProps,
    } = useEditableControls()

    return isEditing ? (
      <ButtonGroup justifyContent='center' size='sm'>
        <IconButton icon={<CheckIcon />} {...getSubmitButtonProps()} />
        <IconButton icon={<CloseIcon />} {...getCancelButtonProps()} />
      </ButtonGroup>
    ) : (
      <Flex justifyContent='center'>
        <IconButton size='sm' icon={<EditIcon />} {...getEditButtonProps()} />
      </Flex>
    )
  }

  return (
    <Editable
      textAlign='center'
      defaultValue='Rasengan ⚡️'
      fontSize='2xl'
      isPreviewFocusable={false}
    >
      <EditablePreview />
      {/* Here is the custom input */}
      <Input as={EditableInput} />
      <EditableControls />
    </Editable>
  )
}
```

3. Notice the typescript error
![image](https://user-images.githubusercontent.com/4248780/171988350-f5278145-74bc-4982-8cca-e6973e612987.png)

Additional `.eslintrc.json` info:

```
{
  "parser": "@typescript-eslint/parser",
  "plugins": ["react", "css-modules", "chakra-ui"],
  "extends": [
    "prettier",
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:css-modules/recommended",
    "next/core-web-vitals"
  ],
  "rules": {
    "@typescript-eslint/no-unused-vars": ["error"],
    "@typescript-eslint/ban-ts-comment": "off"
  }
}

```

### Chakra UI Version

1.8.8

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @allenchuang,

This is happening because `aria-label` is required for the IconButton. Provide `aria-label` and the error will go away.

Cheers

**Comment by AbdelMN** [comment]
Hi,

But aria-label is provided by the hooks as you can see : 
![image](https://user-images.githubusercontent.com/57446997/228331453-cc9588cf-dc40-4431-8604-4c7766f5f0c1.png)

And on the [official documentation](https://chakra-ui.com/docs/components/editable#with-custom-input-and-controls), the example is the same but does not work. 

I also have the same problem with the onClick function that I can't call because it is possibly undefined because it is typed as optional like "aria-label" 

Here is an [example code](https://codesandbox.io/p/sandbox/interesting-hellman-csehx1?file=%2FREADME.md) of the problem
