### ISSUE TITLE
Less peer dependencies, less packages to install

### ISSUE THREAD

**Issue by remorses** [chakra-ui/chakra-ui#615]
Currently when installing `@chakra-ui/core` you also have to install its peer deps `@emotion/core`, `@emotion/styled` and `emotion-theming`

This is because you need to have only one instance of emotion inside the node_modules to make sure the  `emotion` `ThemeContext` is not duplicated

However `@emotion/styled` and `emotion-theming` don't implement any custom context so they can added as simple dependencies to chakra-ui, simplifying the installation process

**Comment by segunadebayo** [comment]
Hi @remorses,

I completely agree and understand it's not super convenient to install those at first.

In the next release, we're looking to reduce this. I think you'll only need to install `@chakra-ui/core`. nothing else. So I can say this is kinda solved already and will be released soon.

Thank you for these ideas.
