### ISSUE TITLE
SyntaxError from "@fontsource/roboto" (@chakra-ui/cli)

### ISSUE THREAD

**Issue by VickyKoblinski** [chakra-ui/chakra-ui#6150]
### Description

When I run `npx @chakra-ui/cli tokens ./theme.ts` where `theme.ts` contains `import "@fontsource/roboto"`, the CLI fails with a syntax error. When this line is removed, the cli type gen works perfectly.

### Link to Reproduction

https://codesandbox.io/s/eager-bassi-jx20vu

### Steps to reproduce

1. Open terminal
2. Run `yarn gen:theme-typings`
3. See error
4. Open `theme.ts` and comment out the font import lines (5 & 6)
5. Run `yarn gen:theme-typings`
6. See it work

### Chakra UI Version

CLI: 2.0.0

### Operating System

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Hi @VickyKoblinski,

The `fontsource` code should be added to the root of your application, not the theme file. This will help avoid any errors from the CLI.

In this case, moving it to `index.tsx` should make it work.

**Comment by VickyKoblinski** [comment]
That's not a fix, that's just a work around. We want to import our fonts inside our theme file because that makes the most sense. The "root" of our application isn't in a singular place and changes based on context (the whole app, Storybook, jest, etc.) and we want to re-use the theme across different apps.
