### ISSUE TITLE
Certain numbers are "broken" in responsive styling

### ISSUE THREAD

**Issue by khinshankhan** [chakra-ui/chakra-ui#6154]
### Description

When I use sizes like 25 for padding, I expect chakra ui to convert it internally based on their formula for units (to 100px I think).

### Link to Reproduction

https://codesandbox.io/s/bitter-smoke-1bpdo4

### Steps to reproduce

1. Open the sandbox
2. Try stretching the screen to go across aquamarine -> salmon -> skyblue
3. Note how salmon is shorter than the aquarmine and skyblue ones although 25 > 10 and 20

Additional:
1. Try replacing 25 with 20
2. Run codesandbox
3. Note how salmon and skyblue are now equal

### Chakra UI Version

2.1.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Chakra ui usually converts number => (number * 4)px, not sure where in the docs I saw this but it is consistent with many other numbers).

Based on inspect element, in the example, 25 is being used directly as 25px. 10 and 20 are properly being converted to 40 and 80 px respectfully. This issue happens with other numbers as well.

I included a video in case my phrasing wasn't clear :sweat_smile: 

https://user-images.githubusercontent.com/22206867/172075651-ee83f1c4-7493-41c9-8b37-0181eb1e1a2d.mp4

**Comment by segunadebayo** [comment]
Please see the documentation here:
https://chakra-ui.com/docs/styled-system/theming/theme#spacing

You can extend the theme to include the values you want to use.
