### ISSUE TITLE
add loader for Select component

### ISSUE THREAD

**Issue by villesau** [chakra-ui/chakra-ui#6158]
### Description

Very often, and in our case most often, the select options are loaded dynamically. This means that we need to have an indication in the select component when we are still loading content. However, ChakraUI does not currently seem to support that

### Problem Statement/Justification

Dynamically loaded content needs an indication when the content is loading. This should belong in ChakraUI since it has the component and without the loader the usage for Select is very limited.

### Proposed Solution or API

`<Select isLoading />`

### Alternatives

- use some other library
- build from scratch

### Additional Information

react-select has such functionality: https://react-select.com/home

**Comment by anubra266** [comment]
@villesau
<img width="807" alt="CleanShot 2022-06-07 at 12 37 33@2x" src="https://user-images.githubusercontent.com/30869823/172370315-b3f178cb-c3af-4b00-91a2-e20377f341de.png">
