### ISSUE TITLE
@chakra-ui/cli@2.1.0 breaks on tokens

### ISSUE THREAD

**Issue by James-Mnemosyne** [chakra-ui/chakra-ui#6161]
### Description

`npx @chakra-ui/cli tokens` command fails with Cannot find module 'lodash/throttle'

### Link to Reproduction

Sorry I can't share more. The code base is private.
Simple to repro, though; create any file and run the cli. E.g.

```
# thing.ts
// Any basic theme code
```

Running `npx @chakra-ui/cli@2.0.0 tokens thing.ts` works.
Running `npx @chakra-ui/cli tokens thing.ts` fails.

### Steps to reproduce

Run:
npx @chakra-ui/cli tokens --strict-component-types <path to file>

Returns:
```
npx: installed 180 in 4.913s
Cannot find module 'lodash/throttle'
Require stack:
- /Users/<user>/.npm/_npx/26024/lib/node_modules/@chakra-ui/cli/dist/index.js
- /Users/<user>/.npm/_npx/26024/lib/node_modules/@chakra-ui/cli/bin/index.js
```

### Chakra UI Version

@chakra-ui/cli@2.1.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by TimKolberger** [comment]
Seems like the CLI is missing the dependency to "lodash/throttle"

https://github.com/chakra-ui/chakra-ui/blob/b4498221320bf51a2fcf8a2fdbeb8c43eb216bd3/tooling/cli/package.json#L41-L56
