### ISSUE TITLE
Toast manager adds aXe violations (role and landmarks)

### ISSUE THREAD

**Issue by moritzjacobs** [chakra-ui/chakra-ui#6164]
### Description

While upgrading to v2 I encountered a few aXe violations, that weren't there before

### Link to Reproduction

https://sfh0m5.csb.app/

### Steps to reproduce

1. Go to https://sfh0m5.csb.app/ (which is just the template without any changes)
2. Enable the aXe dev tools (I use [the one for Firefox](https://www.deque.com/axe/devtools/firefox-browser-extension/))
3. Scan for violations and find the ones screenshotted below

### Chakra UI Version

2.2.0

### Browser

any

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

<img width="1497" alt="Bildschirmfoto 2022-06-07 um 13 49 26" src="https://user-images.githubusercontent.com/2290460/172372214-0f5ab59e-2dcb-4643-a88d-87c06a29a8be.png">

<img width="1506" alt="Bildschirmfoto 2022-06-07 um 13 49 15" src="https://user-images.githubusercontent.com/2290460/172372203-9261f92a-5a1e-416d-a825-124b437e88b4.png">

Not sure how to proceed here, thanks for your attention!

**Comment by leomelzer** [comment]
This issue still persists (as of the current release), exactly as described by @moritzjacobs above. I'm happy to work on it, but it'll take a few weeks (vacation time :)). Maybe you have some guidance or ideas in the meanwhile.

**Comment by aleehedl** [comment]
My attempt to fix these was to remove the `role="region"` from the ul element and wrap the ul with a div element with `role="alert"`. Both violations are fixed because _alert_ is an allowed role for a div and also it's not a landmark, so uniqueness is not required.
