### ISSUE TITLE
[NumberInput] onChange should return an event

### ISSUE THREAD

**Issue by hulk51** [chakra-ui/chakra-ui#617]
**Describe the bug**
Currently NumberInput onChange returns the value of the input, but it should return an event object.

**Expected Behavior**
NumberInput onChange should return an event to comply with form conventions, for example to use with formik. 

**To Reproduce**
Test with the code below that we can not change the NumberInput value with the arrows.
```
<Formik
      initialValues={{ number: 0 }}
      onSubmit={console.log}
    >
      {props => (
        <form onSubmit={props.handleSubmit}>
          <Field name="number">
            {({ field, form }) => (
              <FormControl isInvalid={form.errors.number && form.touched.number}>
                <NumberInput {...field} id="number" />
              </FormControl>
            )}
          </Field>
          <Button type="submit">
            Submit
          </Button>
        </form>
      )}
    </Formik>
```

**Suggested solution(s)**
Make NumberInput onChange returning an event.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 80.0.3987.149

**Comment by segunadebayo** [comment]
Hi @hulk51,

If you're using Formik, you can definitely use `form.setFieldValue`. I mean

```jsx
<Formik
      initialValues={{ number: 0 }}
      onSubmit={console.log}
    >
      {props => (
        <form onSubmit={props.handleSubmit}>
          <Field name="number">
            {({ field, form }) => (
              <FormControl isInvalid={form.errors.number && form.touched.number}>
                <NumberInput onChange={val=>form.setFieldValue(field.name, val)}  />
              </FormControl>
            )}
          </Field>
          <Button type="submit">
            Submit
          </Button>
        </form>
      )}
    </Formik>
```

This is the best way to use NumberInput with form libraries like Formik at the moment. We can consider your suggestion later on.
