### ISSUE TITLE
Hover State is not removed on mobile devices

### ISSUE THREAD

**Issue by nekrozon** [chakra-ui/chakra-ui#6173]
### Description

Hover State is not removed on mobile devices unless you tap focus away

### Link to Reproduction

don't have one

### Steps to reproduce

Adding a hover state to an element works fine on desktop...

Hover state persists on button until you click off of the button a second time (iOS).

Cannot add a CSS4 media query in css files.

Extending the theme with custom media queries is very difficult.

### Chakra UI Version

1.6.4

### Browser

Chrome / iOS

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by nekrozon** [comment]
I understand this can be fixed with CSS (JS is not ideal).

The issue is that I was using Chakra UI for the hover implementation ... Chakra UI library is supposed to make the UI implementation easier.

I could also make the entire UI in native CSS/JS (which I ended up doing as the documentation is extremely weak in this area).

With the CSS fix... you can use a CSS media query

@media(hover: hover) and (pointer: fine)

Except that adding these media queries is not trivial with Chakra UI.

By the time you hack around Chakra UI it's just faster to use native CSS/JS

But again... this is a UI library.  Mobile devices are extremely popular.  Chakra UI should have proper hover states on mobile devices ... otherwise what is the point of using a UI library if you're writing native CSS anyways?

**Comment by OCmilo** [comment]
can we reopen this? the media query pointed out by @nekrozon should be the solution for this problem

**Comment by Sirrom84** [comment]
for some reason adding ` sx={{
              _hover: {},
            }}` did the trick but I don't know why

**Comment by kasem-sm** [comment]
I wonder why this isn't consider an important issue by the Chakra Team!?

**Comment by rajeshbabu-oviva** [comment]
I would argue that we only need to apply hover for supported devices.

 Eg:
     _....
      variants: {
        foo: (props: StyleFunctionProps) => ({
         '@media(hover: hover)': {
            _hover: {
            bg: 'whiteAlpha.200',
         },
       },  
     }),
     ...._
     
     Can we wrap the map the _hover to enclose &:hover inside @media(hover: hover) so that we can be sure that we support hover only for supported devices.

**Comment by isaachinman** [comment]
@segunadebayo Pinging this thread because this is indeed something which should be handled by a UI lib.

**Comment by sbeben** [comment]
bump
