### ISSUE TITLE
cookieStorageManager is undefined in chakra-ui 2.2.1 / next.js

### ISSUE THREAD

**Issue by JimboBilbo** [chakra-ui/chakra-ui#6175]
### Description

When i try to use coockieStorageManger to avoid flashing in Next.js during hydration i get a TypeError that cookieStorageManger is not a function

### Link to Reproduction

https://codesandbox.io/s/wonderful-morning-nu2hm2?file=/src/chakra.js

### Steps to reproduce

Just follow the docs for Add colorModeManager (Optional, for SSR) to avoid flashing during hydration in Chakra 2.2.1
_https://chakra-ui.com/docs/styled-system/features/color-mode#add-colormodemanager-optional-for-ssr_

### Chakra UI Version

2.2.1

### Browser

all

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

i worked with the following dependencies and it don't work (see the codesandbox example)
    "@chakra-ui/react": "^2.2.1",
    "@emotion/react": "^11.9.0",
    "@emotion/styled": "^11.8.1",
    "framer-motion": "^6.3.11",
    "next": "^12.1.6",
    "react": "^18.1.0",
    "react-dom": "^18.1.0"

but it works after i switched to the following older dependencies:
    "@chakra-ui/react": "^1.8.8",
    "@emotion/react": "^11.9.0",
    "@emotion/styled": "^11.8.1",
    "framer-motion": "^6.3.0",
    "next": "^12.1.5",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"

**Comment by riecho14** [comment]
is there no other solution besides switching to old dependencies?

**Comment by ArkShocer** [comment]
@JimboBilbo 
`cookieStorageManager` has been changed to `cookieStorageManagerSSR`.
Importing and replacing it with the following should fix your problem.
```js
import {
  cookieStorageManagerSSR,
} from '@chakra-ui/react'

  const colorModeManager =
    typeof cookies === 'string'
      ? cookieStorageManagerSSR(cookies)
      : localStorageManager
```

**Comment by JimboBilbo** [comment]
@ArkShocer 
thanks! i guess should be worth mentioning in the docs.
