### ISSUE TITLE
__css prop does not work on Avatar

### ISSUE THREAD

**Issue by benknab** [chakra-ui/chakra-ui#6188]
### Description

When I use the `__css` prop, I expected to be able to change the style of the component but nothing happens

### Link to Reproduction

https://codesandbox.io/s/avatar-css-vcx7tp?file=/src/app.tsx

### Steps to reproduce

1. Add `__css` prop to an `Avatar` component to change the style
2. See that style is not applied
3. Use the same CSS object in the `sx` prop
4. See that style is applied

### Chakra UI Version

2.1.0

### Browser

any

### Operating System

any

### Additional Information

`sx` prop works fine

**Comment by bkiac** [comment]
@segunadebayo thanks for the explanation! I think it's a type error then, I should not be able to pass in a `__css` prop without error if it doesn't do anything
