### ISSUE TITLE
[Select] Support isMultiple prop

### ISSUE THREAD

**Issue by Sibasish19** [chakra-ui/chakra-ui#619]
**Is your feature request related to a problem? Please describe.**
It would be super useful to transform the existing <Select /> component into a multi-select one having a Boolean prop. Something like the one we have in [https://github.com/JedWatson/react-select](react-select).

**Comment by segunadebayo** [comment]
Hi @Sibasish19,

This sounds interesting. However, this is not in our plan for now and I can't promise we'll look into it.

Let's see.

**Comment by Sibasish19** [comment]
No problem. Looking forward to v1 release :)

**Comment by csandman** [comment]
@sibasishm I made a wrapper for react-select if you still need something like this!  https://github.com/csandman/chakra-react-select
