### ISSUE TITLE
Expose modal scroll lock as a hook

### ISSUE THREAD

**Issue by TomSmedley** [chakra-ui/chakra-ui#6195]
### Description

Currently when you open a modal it locks the scrolling, it would be nice to expose that as a hook such as useScrollLock to it can be applied to custom components such as is available with Mantine (https://mantine.dev/hooks/use-scroll-lock/)

### Problem Statement/Justification

If someone wanted to lock the scrolling with custom components.

### Proposed Solution or API

const [scrollLocked, setScrollLocked] = useScrollLock();

**Comment by segunadebayo** [comment]
Hi @TomSmedley,

We use [React Remove Scroll](https://github.com/theKashey/react-remove-scroll) internally to block scroll. You can install this library in your app as well.

Cheers.
