### ISSUE TITLE
chakra-cli command fails on next's 12

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [chakra-ui/chakra-ui#6197]
### Description

when using `npx @chakra-ui/cli` the command throws an error, also it's not installing the executable script (using pnpm)

### Link to Reproduction

none

### Steps to reproduce

1. `npx @chakra-ui/cli tokens ...`
2. error appears
<img width="784" alt="Screen Shot 2022-06-15 at 15 58 59" src="https://user-images.githubusercontent.com/74371045/173928372-47a0f325-4cec-465c-adef-155989864b25.png">

**Already installed loads/throttle on the current project, yet the error still happens**

### Chakra UI Version

2.2.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

- Using `pnpm`
- Node v18.2

**Comment by TylerAPfledderer** [comment]
Hey, @AlvaroAquijeDiaz! This will be fixed in the next release. See PR #6172.

In the meantime, running `npx @chakra-ui/cli@2.0.0 tokens <path/to/theme>` should work!

**Comment by AlvaroAquijeDiaz** [comment]
Hi now I get the type definitions but when its added to my `tsconfig.json` chakra doesn't recognize it which means I actually cannot use the so wanted autocomplete. (I think this is a TS error but anyhow). 

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "./**/*.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

### Using a custom button variant and not getting autcomplete
<img width="564" alt="Screen Shot 2022-06-16 at 20 56 04" src="https://user-images.githubusercontent.com/74371045/174207026-d49a0f64-099a-4607-9ae8-0b55b74ee05c.png">

### Generated code from `chakra-cli`
<img width="564" alt="Screen Shot 2022-06-16 at 20 57 01" src="https://user-images.githubusercontent.com/74371045/174207121-f41c273e-1143-494d-ab81-684d6596cbef.png">


I'd use some help

**Comment by TylerAPfledderer** [comment]
@AlvaroAquijeDiaz Hmm I'm not experiencing the issue, even with the TSConfig you provided.

Firstly, it might be good to restart the extension host. In VSCode the command is `Developer: Restart Extension Host`. Maybe the intellisense needs a reset.

If that doesn't work, I take it you are allowing the output to go to the default `node_modules` path?

**Comment by AlvaroAquijeDiaz** [comment]
Yea me neither, and well everything is by default when used `yarn create next-app`, only the paths and the include values were changed. I'll keep looking and see why it doesn't work, but thanks anyway. 🚀

**Comment by TylerAPfledderer** [comment]
> @TylerAPfledderer hi Tyler, I experienced similar issue to @AlvaroAquijeDiaz, but the symptom is different in that with certain tsconfig, chakra-cli produces an empty-ish type definition file. From my own experiment, the cause seem to be the "baseUrl" field in `tsconfig.json`. I made a repo to show the problem [here](https://github.com/suimong/chakra-cli-issue-mwp-pnpm). Could you please take a look? Thanks.

Hi @suimong!

This seems like a new issue after the release of `v2.1.0`. If you revert back to `v2.0.0` it works as expected in your "failed" commit (`c47cb977`).

Also, to clarify, adding the following package script also works when reverting to the previous version:
```js
"gen:theme-typings": "chakra-cli tokens ./src/tw-theme/index.ts --out tw-theme2.types.d.ts"
```

Please kindly post a new issue so this can be better seen, triaged, and reviewed by the folks on the team who have been improving the CLI. I unfortunately have never been inside that tool to provide you any further explanation. 🌝

**Comment by suimong** [comment]
> > @TylerAPfledderer hi Tyler, I experienced similar issue to @AlvaroAquijeDiaz, but the symptom is different in that with certain tsconfig, chakra-cli produces an empty-ish type definition file. From my own experiment, the cause seem to be the "baseUrl" field in `tsconfig.json`. I made a repo to show the problem [here](https://github.com/suimong/chakra-cli-issue-mwp-pnpm). Could you please take a look? Thanks.
> 
> Hi @suimong!
> 
> This seems like a new issue after the release of `v2.1.0`. If you revert back to `v2.0.0` it works as expected in your "failed" commit (`c47cb977`).
> 
> Also, to clarify, adding the following package script also works when reverting to the previous version:
> 
> ```js
> "gen:theme-typings": "chakra-cli tokens ./src/tw-theme/index.ts --out tw-theme2.types.d.ts"
> ```
> 
> Please kindly post a new issue so this can be better seen, triaged, and reviewed by the folks on the team who have been improving the CLI. I unfortunately have never been inside that tool to provide you any further explanation. full_moon_with_face

@TylerAPfledderer Thanks for testing! I opened issue #6282
