### ISSUE TITLE
Support typescript autocomplete within extendTheme

### ISSUE THREAD

**Issue by IljaDaderko** [chakra-ui/chakra-ui#6202]
### Description

I created a custom theme, however there was no typescript autocomplete / intenseness provided along the way. It would be really cool if we could get this, as it can make work with themes more pleasant without requiring developers to reference theming docs  as often.

### Problem Statement/Justification

Improve developer experience

### Proposed Solution or API

`extendTheme({ /*data*/ })` data within extendTheme should be typed and validated.

### Alternatives

None

**Comment by TylerAPfledderer** [comment]
Hey @IljaDaderko I would tend to agree here, though there are other typings to consider that are exposed if you isolate and import each theme object if your project scales. (i.e. the `colors` object can be given a type signature `Colors` from the react package, say).

Hey @segunadebayo, I understand that there is a [type called `ThemeOverride`](https://github.com/chakra-ui/chakra-ui/blob/aac6c98321e6487894b45cb459e67e5e02499224/packages/react/src/extend-theme.ts#L34-L35) that I see in some component tests when overriding base themes in a given story, including the `extendTheme` test file itself. Is it possible to apply to the function, or does this negatively impact it?

So from:
```ts
export function extendTheme( ...extensions: Array<Dict | ((theme: Dict) => Dict)> ): Dict
```

to...
```ts 
export function extendTheme( ...extensions: Array<ThemeOverride> ): Dict 
```

**Comment by mym0404** [comment]
here is a rough workaround

```tsx
type ExtendTheme = (...extensions: Array<ThemeOverride>) => Dict;
const theme = (extendTheme as ExtendTheme)({
  config,
  colors: {},
  semanticTokens: {
    colors: {},
  },
});
```

![image](https://github.com/chakra-ui/chakra-ui/assets/33388801/13c60273-a670-49d6-9b12-bd418e4512c0)
