### ISSUE TITLE
Request to add responsive orientation on Divider

### ISSUE THREAD

**Issue by skauffmann** [chakra-ui/chakra-ui#621]
**Is your feature request related to a problem? Please describe.**
I want display an horizontal divider for small devise, and a vertical divider for large devise.
 
**Describe the solution you'd like**
Take into account responsive props like :
<Divider orientation={{ xs: 'horizontal', md: 'vertical' }} />

**Describe alternatives you've considered**
I'm open to other solutions :)

**Additional context**
n/a

**Comment by with-heart** [comment]
Hi @skauffmann, in Chakra 1.0, the default theme now comes with two variants for `Divider`: `horizontal` and `vertical`.

In order to responsively switch between these orientations, you can currently use the `useBreakpointValue` hook:

```jsx
import {Divider, useBreakpointValue} from '@chakra-ui/core'

const Component = () => (
  <Divider variant={useBreakpointValue({xs: 'horizontal', md: 'vertical'})} />
)
```

Eventually `variant` will support responsive values (#1028) so you won't need to use the hook, but we're not quite there yet.

**Comment by taitems** [comment]
Came across this in `v1.8.1` and found this issue.

I thought I would have been able to do the following, which would have been nice and simple.

```js
<Divider orientation={['horizontal', null, 'vertical']}  />
```

**Comment by Tenkir** [comment]
> Hi @skauffmann, in Chakra 1.0, the default theme now comes with two variants for Divider: horizontal and vertical.


This does not seem to work anymore as of v2.8.2.

My expectation is in line with @taitems. I instead had to implement like this:
```jsx
          <Show below="xl">
            <Divider orientation="horizontal" />
          </Show>
          <Hide below="xl">
            <Divider orientation="vertical" h="auto" />
          </Hide>
```
