### ISSUE TITLE
Configs override theme not work for Button BaseStyle likes minWidth, fontSize

### ISSUE THREAD

**Issue by nhattan097** [chakra-ui/chakra-ui#6210]
### Description

When I override baseStyle Button but some case likes fontSize, minWidth not worked

### Link to Reproduction

https://codesandbox.io/s/hopeful-benji-08nl09?file=/pages/_app.tsx

### Steps to reproduce

1. Go to F12
2. Click on Elements
3. Scroll down to the Button
4. See the styles won't change for fontSize, minWidth

### Chakra UI Version

latest

### Browser

Google Chorme v102.0.5005.115

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

My configs theme:
<img width="436" alt="image" src="https://user-images.githubusercontent.com/34256997/174420737-4175a824-5e65-4edc-9671-0333d6f07874.png">

I have already clone the source and debug, why the error happened. Finally, I found the problem come from here:

<img width="864" alt="image" src="https://user-images.githubusercontent.com/34256997/174420636-856bead2-093e-4d56-8313-1b8f85aaa332.png">

`recipe(config, "sizes", size, props)` 
have overrided 
`runIfFn(config.baseStyle ?? {}, props)` 
when code like this: 
` mergeWith(
        runIfFn(config.baseStyle ?? {}, props),
        recipe(config, "sizes", size, props),
      )`
and I fixed the problem like this:
`mergeWith(
        recipe(config, "sizes", size, props),
        runIfFn(config.baseStyle ?? {}, props),
      )`

**Comment by VickyKoblinski** [comment]
This is intentional, the `size` prop is responsible for, well, the size :)

What you want is:

```
Button: {
  sizes: {
    sm: { /* small size props */ },
    md: { /* md size props */ },
    lg: { /* lg size props */ }
  }
}
```

The default size is `md`, so you can put your sizing props there and you should see your changes. Border radius and fontWeight can stay on the baseStyle.

**Comment by TylerAPfledderer** [comment]
That's right!

Here's the [default size styles](https://github.com/chakra-ui/chakra-ui/blob/aac6c98321e6487894b45cb459e67e5e02499224/packages/theme/src/components/button.ts#L176-L181) for reference.
