### ISSUE TITLE
When I implement `ColorModeScript` set to `useSystemColorMode: true` and `initialColorMode: "dark"` it does not seem to be working.

### ISSUE THREAD

**Issue by jcstein** [chakra-ui/chakra-ui#6211]
### Description

When I implement `ColorModeScript` set to `useSystemColorMode: true` and `initialColorMode: "dark"` it does not seem to be working.

### Link to Reproduction

https://github.com/jcstein/buildmarket-lol

### Steps to reproduce

1. Go to [https://github.com/jcstein/buildmarket-lol](https://github.com/jcstein/buildmarket-lol)
2. Clone the repo
3. Run `yarn`
4. Run `yarn start`
5. See error

### Chakra UI Version

2.2.1

### Browser

Brave/Safari/Firefox

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

https://buildmarket.lol

**Comment by VickyKoblinski** [comment]
Check out the last paragraph I wrote on this ticket, I think it's related: https://github.com/chakra-ui/chakra-ui/issues/6192 

I'm guessing your localStorage has "light" in it which is overriding your default "dark" mode. Try clearing localStorage and refreshing. Do you see dark mode after that? Is that the cause of the issue?

**Comment by jcstein** [comment]
Thank you so much for checking this out @VickyKoblinski 😄 

I have tried this out with no luck. The `ColorModeSwitcher` works just fine, though. The real goal for me is to have this auto load. It's worked on Next.js sites for me with Chakra before well too.

Here's what it looks like loading after clearing `chakra-ui-color-mode` and refreshing ⬇️

https://user-images.githubusercontent.com/46639943/174447511-f4decbc6-3a9f-48ab-a5e9-90e04315570d.mov

**Comment by VickyKoblinski** [comment]
Ah! It was worth a try :) Do you have chakra-ui-color-mode cookies that need to be cleared? (You can find them a couple items down from Local Storage in that menu.)

I experienced this same problem too but didn't investigate it too deeply because it was outside the scope of what I was working on.

**Comment by jcstein** [comment]
Absolutely 😄 It does not appear there are any cookies 👀 

Here's what I see on my end

https://ipfs.io/ipfs/bafybeia6iiufw6gfx4k2riwzqnppctohdttnjbodtlq7as6czc6gnk7dl4/clear%20cookies2.mov (too large for embed)

Thanks again!

**Comment by VickyKoblinski** [comment]
Oh well, that's all I've got 😅 we'll just have to wait for an expert to chime in.

**Comment by dufia** [comment]
I just bumped to v2 and `useSystemColorMode` seems to stop working

**Comment by itkrt2y** [comment]
@jcstein 

`@chakra-ui/color-mode` seems to have changed the behavior of the initial color in v2.0.0
https://github.com/chakra-ui/chakra-ui/releases/tag/%40chakra-ui%2Fcolor-mode%402.0.0

>If user specifies `useSystemColorMode: true`, then we'll subscribe to color
mode changes from the operating system. It is no longer used to determine
the initial color mode. To achieve that, please use `initialColorMode: "system"`

Therefore, if you'd to use the system color as the default color, fix theme as follows.

```diff
// src/theme.ts

const config: ThemeConfig = {
-  initialColorMode: "dark",
+  initialColorMode: "system",
  useSystemColorMode: true,
};
```

And there is a bug in https://github.com/jcstein/buildmarket-lol.
You need to pass a custom theme to `ChakraProvider` instead of the default theme.

```diff
// src/App.tsx

import {
  ChakraProvider,
  Box,
  Text,
  Link,
  VStack,
  Code,
  Grid,
-  theme,
  Button,
} from "@chakra-ui/react";
import { ColorModeSwitcher } from "./ColorModeSwitcher";
import { Logo } from "./Logo";
import { FaRobot } from "react-icons/fa";
+ import theme from "./theme";

export const App = () => (
  <ChakraProvider theme={theme}>
```

**Comment by jcstein** [comment]
thank you so much! @itkrt2y
