### ISSUE TITLE
react-remove-scroll-bar error when open more than one modal

### ISSUE THREAD

**Issue by kiq-o** [chakra-ui/chakra-ui#6213]
### Description

A weird error occurs when a modal is opened and there is another one open on background.

### Link to Reproduction

https://2p5inx.csb.app/

### Steps to reproduce

1. Just create a modal with a button that open another one and keep both open.
2. The error should appear on the console like this
![Screenshot_1](https://user-images.githubusercontent.com/46490712/174491393-e137ce0b-0057-4d5f-93b7-5fb01cb31cbb.png)
:

### Chakra UI Version

1.8.8

### Browser

Firefox

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by shigetaichi** [comment]
it seems related to this. → https://github.com/theKashey/react-remove-scroll-bar/blob/3dd80e28c92b8aac025e41f4258ff926cdc88af9/src/utils.ts#L22

**Comment by cc-dev04** [comment]
I have the same problem, any solution to this?

**Comment by ryanahamilton** [comment]
In our applications, I am seeing this error with the opening of any (single) Drawer or Modal (after upgrading to Chakra 2).

**Comment by cc-dev04** [comment]
The only thing I could see here is that I used a custom scroll library in my app, and due to the use of this library I had to place in css body { overflow: hidden } and I realized that when I removed this line of css no longer the warning came out, I hope this helps you in something

**Comment by ryanahamilton** [comment]
> The only thing I could see here is that I used a custom scroll library in my app, and due to the use of this library I had to place in css body { overflow: hidden } and I realized that when I removed this line of css no longer the warning came out, I hope this helps you in something

Ah, your comment made me recall I had `overflow: 'hidden'` defined in the theme. Thank you!

<img width="468" alt="image" src="https://user-images.githubusercontent.com/3267/177614942-b196fa57-3951-4b04-8c13-1add3fb7cdb8.png">

**Comment by thimholanda** [comment]
I have the same problem here. This alert is shown only for development environment. Somebody can help us?

**Comment by tanuj-g** [comment]
I am also facing the issue 
any solution?

**Comment by hixus** [comment]
On my project this happens if there is already Drawer open and the I open AlertDialog asking confirmation. 

This is because react-remove-scroll-bar has already set overflow: hidden when Drawer was opened and errors when AlertDialog tries to do the same.

**Comment by tanuj-g** [comment]
> On my project this happens if there is already Drawer open and the I open AlertDialog asking confirmation.
> 
> This is because react-remove-scroll-bar has already set overflow: hidden when Drawer was opened and errors when AlertDialog tries to do the same.

I am also facing the similar kind of behaviour in my project, what is the solution for this.

**Comment by bitweed** [comment]
I have met the similar problem. It seems if the modal open, `overflow:hidden` will be append into the body. I think this could be an issue although it doesn't affect normal usage.

**Comment by karna41317** [comment]
any update on this ?

**Comment by NahuE3** [comment]
When you keep both modals open, just should have to set `blockScrollOnMount={false}` in the last modal. This works for me.

**Comment by yhoungdev** [comment]
> When you keep both modals open, just should have to set `blockScrollOnMount={false}` in the last modal. This works for me.

this worked for me, Thanks alotm God bless you

**Comment by yhoungdev** [comment]
> ### Description
> A weird error occurs when a modal is opened and there is another one open on background.
> 
> ### Link to Reproduction
> https://2p5inx.csb.app/
> 
> ### Steps to reproduce
> 1. Just create a modal with a button that open another one and keep both open.
> 2. The error should appear on the console like this
>    ![Screenshot_1](https://user-images.githubusercontent.com/46490712/174491393-e137ce0b-0057-4d5f-93b7-5fb01cb31cbb.png)
>    :
> 
> ### Chakra UI Version
> 1.8.8
> 
> ### Browser
> Firefox
> 
> ### Operating System
> * [x]  macOS
> * [x]  Windows
> * [x]  Linux
> 
> ### Additional Information
> _No response_

add this blockScrollOnMount={false} to the last modal

**Comment by itsam** [comment]
Same happens when the second (last) modal is actually a Drawer. In this case, when setting `blockScrollOnMount={false}`, the error is replaced with the following warning

`Warning: React does not recognize the `motionProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `motionprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

So in this case, `blockScrollOnMount={false}` does not work

**Comment by yuhang1995** [comment]
You can solve this problem by removing the version dependency of react-remove-scroll-bar from lock file and reinstalling the new version. See this link for [details](https://github.com/theKashey/react-remove-scroll-bar/issues/35#issuecomment-1276809669)
