### ISSUE TITLE
[TagIcon] 'first-child' console error when using TagIcon

### ISSUE THREAD

**Issue by trybick** [chakra-ui/chakra-ui#622]
**Describe the bug**
When rendering a `TagIcon`, I get the following console error in the browser:

_The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type"._ 

![Screen Shot 2020-04-19 at 5 01 41 PM](https://user-images.githubusercontent.com/39889198/79699778-9ca84980-825f-11ea-95a4-8491594d2574.png)

**Expected Behavior**
Expected behavior is to not get a console error.

**To Reproduce**
1. Add the following to any app:
```jsx
<Tag size="md" variantColor="teal">
  <TagIcon icon="add" size="12px" /> // console error goes away if this is removed
  <TagLabel>Follow</TagLabel>
</Tag>
```
2. Open console in browser and see error

**Suggested solution(s)**
Would updating emotion version for charka help?

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: v80

**Additional context**
There is some discussion about this error on emotion github:
https://github.com/emotion-js/emotion/issues/1178

**Comment by kckusal** [comment]
Any updates on this? I'd like to keep my console clean.)

**Comment by KevinGomezDev** [comment]
Not totally sure if it's the best approach but storybook suffered from the same issue some time ago, @segunadebayo I can create a PR if you agree
https://github.com/storybookjs/storybook/issues/6998
https://github.com/storybookjs/storybook/pull/7861/files

**Comment by with-heart** [comment]
@KevinGomezDev I would love that!

**Comment by segunadebayo** [comment]
Hey guys,

We've fixed this by deprecating the `TagIcon` and adding the `TagLeftIcon` and `TagRightIcon` components.

We'll release an update shortly.

**Comment by KevinGomezDev** [comment]
I saw the changes on the codebase when I was  implementing the change so I decided to wait until the new version, thanks @segunadebayo

**Comment by surajsharma** [comment]
> TagIcon

this isn't released yet?

**Comment by with-heart** [comment]
@surajsharma We've removed `TagIcon` and replaced it with `TagLeftIcon` and `TagRightIcon`. See https://next.chakra-ui.com/docs/components/tag#with-left-icon

**Comment by jdkoeh79** [comment]
> @surajsharma We've removed `TagIcon` and replaced it with `TagLeftIcon` and `TagRightIcon`. See https://next.chakra-ui.com/docs/components/tag#with-left-icon

This link simply returns:

<img width="392" alt="Screen Shot 2020-09-19 at 12 07 14 AM" src="https://user-images.githubusercontent.com/18156271/93658719-19587300-fa0c-11ea-8182-00f3e3a35e04.png">

Try this: https://next.chakra-ui.com/docs/data-display/tag

**Comment by surajsharma** [comment]
> > @surajsharma We've removed `TagIcon` and replaced it with `TagLeftIcon` and `TagRightIcon`. See https://next.chakra-ui.com/docs/components/tag#with-left-icon
> 
> This link simply returns:
> 
> <img alt="Screen Shot 2020-09-19 at 12 07 14 AM" width="392" src="https://user-images.githubusercontent.com/18156271/93658719-19587300-fa0c-11ea-8182-00f3e3a35e04.png">
> 
> Try this: https://next.chakra-ui.com/docs/data-display/tag

thanks but this doesn't help as i am using chakra and don't want to add next.chakra to the project, any workaround would be appreciated.

**Comment by trybick** [comment]
> > > @surajsharma We've removed `TagIcon` and replaced it with `TagLeftIcon` and `TagRightIcon`. See https://next.chakra-ui.com/docs/components/tag#with-left-icon
> > 
> > 
> > This link simply returns:
> > <img alt="Screen Shot 2020-09-19 at 12 07 14 AM" width="392" src="https://user-images.githubusercontent.com/18156271/93658719-19587300-fa0c-11ea-8182-00f3e3a35e04.png">
> > Try this: https://next.chakra-ui.com/docs/data-display/tag
> 
> thanks but this doesn't help as i am using chakra and don't want to add next.chakra to the project, any workaround would be appreciated.

Just wait for version 1 to be released 🙂 - next.chakra is a preview of that
