### ISSUE TITLE
use Input in Collapse, Input style be error

### ISSUE THREAD

**Issue by dyk98** [chakra-ui/chakra-ui#6225]
### Description

use Input in Collapse, Input style be error

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-typescript-pomi8?file=/src/index.tsx:0-839

### Steps to reproduce

<InputGroup mt={"16px"} size='md'>
            <Input type={"password"} placeholder='请输入登录密码' />
</InputGroup>
<Collapse in={true} animateOpacity>
          <InputGroup mt={"16px"} size='md'>
            <Input type={"password"} placeholder='请输入登录密码' />
          </InputGroup>
</Collapse>
<img width="962" alt="image" src="https://user-images.githubusercontent.com/34772565/174966289-38309e05-b093-494f-83c7-2ab1d3051f68.png">
<img width="933" alt="image" src="https://user-images.githubusercontent.com/34772565/174966314-da95e66f-6ede-422e-b368-dbd228c7a998.png">

### Chakra UI Version

2.2.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by shigetaichi** [comment]
@dyk98 
FYI: it seems related to this issue, and this comment⏬
https://github.com/chakra-ui/chakra-ui/issues/6049#issuecomment-1133765447

**Comment by segunadebayo** [comment]
Yes, @dyk98 please refer to the comment in the issue above.
