### ISSUE TITLE
Portals around semanticaly string HTML like `tr` will spit console warnings because of the temp `span` created

### ISSUE THREAD

**Issue by snide** [chakra-ui/chakra-ui#6227]
### Description

When you use a portal around semantic HTML, a temp span is created which may not be a valid child

### Link to Reproduction

https://codesandbox.io/s/hopeful-wildflower-0s3pvw?file=/src/index.js

### Steps to reproduce

1. Place Portal around a child element of semanticly strict HTML like `Tr`
2. Portal creates a temp node span as noticed https://github.com/chakra-ui/chakra-ui/blob/main/packages/portal/src/portal.tsx#L87
3. Console will throw an error that the HTML is not semantic "span can't be child of tr"

### Chakra UI Version

2.2.1

### Browser

Firefox

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Sandbox shows a reproduction. I think I can see where the error is but I'm not clever enough to think how this could be solved.

BTW. Fantastic library. Once I figure it out some more I'd like to start contributing.

**Comment by aboveyunhai** [comment]
@snide  I have a "hacky workaround" that can get rid of the warning. The main idea is to persist the html table structure.

This solution wouldn't work without `<Portal/>`;
Wrap your portal inside `<Tr/><Td/>`, since we used `portal` we can use display={'none'} to hide the table row.
```jsx
     <Tr display={'none'}>
        <Td>
          <Portal>
            <PopoverContent>
              <PopoverBody>
                The temp node span is created here briefly before the portal
                moves it
              </PopoverBody>
            </PopoverContent>
          </Portal>
        </Td>
      </Tr>
```

**Comment by snide** [comment]
Solves the warning, but likely creates a worse problem semantically. Oh well, I'll think on it and look at the codebase a little closer. Again, fantastic lib, TY for the work on it.

**Comment by aboveyunhai** [comment]
@snide  this problem technically will happen on all `popover (wrapper-like)` libraries as long as it involves html elements with strict semantic, like table and link. 
Maybe it's good to see how they solve this kind of problems. I just cannot come out one for now.
