### ISSUE TITLE
useMediaQuery does not update on browser resize

### ISSUE THREAD

**Issue by timhettler** [chakra-ui/chakra-ui#6228]
### Description

When I resize the browser, I expected the `useMediaQuery` values to update. Instead, they are set properly on initial render but do not ever update.

### Link to Reproduction

https://codesandbox.io/s/upbeat-monad-7mo32x?file=/pages/index.tsx

### Steps to reproduce

1. Resize page
2. Observe that string does not re-render
3. Reload page at different breakpoints
4. Observe that initial rendered string is correct

### Chakra UI Version

2.2.1

### Browser

Chrome latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This functionality broke for me after upgrading from `v1.8.8`

**Comment by TylerAPfledderer** [comment]
Hey @timhettler! Can you verify that you have also upgraded to React 18? Chakra v2 is focused on being compatible with React 18, and the CSB you provided does not show that upgrade.

I am seeing inconsistency on my end, as the examples rendered in the Docsite are working as intended, so I wonder if there is an issue with specific implementation.

**Comment by timhettler** [comment]
Thank you all for your help. I updated the CodeSandbox here and it now works correctly: https://codesandbox.io/s/optimistic-butterfly-f34ff9?file=/pages/index.tsx

The query strings as originally written (`(max-width : 767px)`) did work in version 1x, and it's a bit odd that it still works on initial render. Either way, I'm glad the fix is an easy one.
