### ISSUE TITLE
[website] dev-ts how to get the website working

### ISSUE THREAD

**Issue by ukris** [chakra-ui/chakra-ui#623]
**Describe the bug**
I did yarn && yarn build from root and went to website and did yarn
I get the following error:
```Couldn't find package "@chakra-ui/hooks@0.0.1" required by "@chakra-ui/core@file:../packages/core" on the "npm" registry```
what am i doing wrong

**Expected Behavior**
to be able to install, build and run w/oissue

**To Reproduce**
git checkout dev-ts
yarn && yarn boot
cd website
yarn

**Comment by segunadebayo** [comment]
Hi @ukris,

We're not focused on getting the website to work in the dev-ts branch for now.

We've setup storybook, playroom, and examples if you need to test our progress so far.

Try to run `yarn build` again at the root and see if it build correctly. I believe it should.

Let me know.
