### ISSUE TITLE
Documentation route doesn't exist

### ISSUE THREAD

**Issue by luckyaxl** [chakra-ui/chakra-ui#6232]
### Description

when i search for floating action in search bar, the route documentation doesn't exist

### Link to Reproduction

https://chakra-ui.com/recipes/floating-labels

### Steps to reproduce

1. Go to `https://chakra-ui.com/`
2. Click on `Search the docs`
3. Search for `Floating actions`
 
 <img width="1433" alt="image" src="https://user-images.githubusercontent.com/30078653/175187966-3669bc1c-25da-4c9c-85a0-ba89dd0654bc.png">

### Chakra UI Version

v2.2.1

### Browser

Google Chrome Version 102.0.5005.115 (Official Build) (x86_64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/30078653/175187966-3669bc1c-25da-4c9c-85a0-ba89dd0654bc.png">

**Comment by segunadebayo** [comment]
Hi @luckyaxl. This has been fixed.
