### ISSUE TITLE
Items in a breadcrumb aren't aligned centrally

### ISSUE THREAD

**Issue by jonhaddow** [chakra-ui/chakra-ui#6239]
### Description

With multiple breadcrumb items with dynamic heights, the items are not centre aligned.

### Link to Reproduction

https://codesandbox.io/s/jolly-wing-r1lxxl?file=/src/index.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/jolly-wing-r1lxxl?file=/src/index.tsx
2. Notice the misaligned breadcrumb items.

### Chakra UI Version

2.2.1

### Browser

Brave

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This can be fixed by adding `display:flex;` to the `nav > ol` tag. However, I don't believe there is a way for the developer to modify that style without custom CSS.

**Comment by mi-upto** [comment]
me too... 👀  i using "@chakra-ui/react": "^2.2.0",
I would like `display: flex; align-items: center` added to the auto-generated `ol` element.

```tsx
    <Breadcrumb
      spacing={3}
      separator={<IconArrowRight />}
      fontSize='xs'
    >
      <BreadcrumbItem>
        <BreadcrumbLink href='/'>
          <Logo width='24px' height='24px' role='img' aria-label='LogoName' />
        </BreadcrumbLink>
      </BreadcrumbItem>

      <BreadcrumbItem>
        <BreadcrumbLink href={`/projects/${project.id}`} fontWeight='bold'>
          {project.name}
        </BreadcrumbLink>
      </BreadcrumbItem>
    </Breadcrumb>
```

**Comment by shigetaichi** [comment]
> me too... 👀 i using "@chakra-ui/react": "2.2.0", I would like `display: flex; align-items: center` added to the auto-generated `ol` tag.

if you apply ```display:flex;```, then sometimes it also need ```flex-wrap: wrap``` to avoid shrinking and overflow when it used in narrow container💡

**Comment by itkrt2y** [comment]
[workaround] Use `sx` prop

https://chakra-ui.com/docs/styled-system/the-sx-prop

```tsx
<Breadcrumb sx={{ ol: { display: "flex", alignItems: "center" } }}>
  <BreadcrumbItem>
    <BreadcrumbLink>Item A</BreadcrumbLink>
  </BreadcrumbItem>
  <BreadcrumbItem>
    <Image
      width={8}
      height={8}
      borderRadius="full"
      src="https://picsum.photos/20"
    />
    <BreadcrumbLink>Item B</BreadcrumbLink>
  </BreadcrumbItem>
  <BreadcrumbItem>
    <BreadcrumbLink>Item C</BreadcrumbLink>
  </BreadcrumbItem>
</Breadcrumb>
```

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. Luckily it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

After the upgrade, if the problem still exists in your application please open a new issue and follow the instructions in the issue template.
