### ISSUE TITLE
Use minus key in [NumberInput] component

### ISSUE THREAD

**Issue by laurensnl** [chakra-ui/chakra-ui#624]
**Is your feature request related to a problem? Please describe.**
We're dealing with potentially large negative numbers that can be entered in the NumberInput component. It's currently not possible to enter a negative number using the minus key on the keyboard, like users would expect. Right now, the (shift +) down keys must be used to select the required negative number.

**Describe the solution you'd like**
It would be nice if the minus key on the keyboard could be used to toggle between a negative number and a positive number.

**Describe alternatives you've considered**
Adding a onKeyDown handler myself, but it feels kind of hacky.

**Comment by laurensnl** [comment]
No-one else who would like to have this feature?

**Comment by kimroen** [comment]
I would also like it if the user could type a negative number without having to hit the step buttons.

**Comment by with-heart** [comment]
This functionality has been added in 1.0. Here's an example on `1.0.0-next.2`: https://codesandbox.io/s/zen-ellis-9939t?file=/src/App.js

**Comment by laurensnl** [comment]
Awesome! Thanks @with-heart!
