### ISSUE TITLE
Different Background Colors in Different Browsers

### ISSUE THREAD

**Issue by kartset** [chakra-ui/chakra-ui#6247]
### Description

When I installed chakra and wrapped my <App /> inside the chakra provider. I expected the background to be white and font color to be black by default

### Link to Reproduction

https://codesandbox.io/s/late-cdn-qnx8hh?file=/src/index.tsx

### Steps to reproduce

1. Create a new react app using create-react-app with node version 18.4.0 and typescript template
2. Install Chakra-UI, emotion, and framer using the installation terminal command given on the getting started page of the documentation. [[1]](https://chakra-ui.com/getting-started)
3. Wrap the new react app's <App /> component in the index.tsx file with the chakra provider
4.  This will give different background colors in different browsers(for eg. in chrome it gives a background color of rgb(26,32,44) and in firefox, it gives a background color of white)
5. After this I used the theme to see whether that can change the output but no matter what combination of initialColorMode and useSystemColorMode I made and fed the theme attribute the output was still the same.
6. When I used code sandbox to reproduce results to post here it showed an error in interpretation.

### Chakra UI Version

2.2.1

### Browser

Google Chrome and Mozilla Firefox

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

My package.json file is:-

`{
  "name": "warement-store",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@chakra-ui/react": "^2.2.1",
    "@emotion/react": "^11.9.3",
    "@emotion/styled": "^11.9.3",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.11.41",
    "@types/react": "^18.0.14",
    "@types/react-dom": "^18.0.5",
    "framer-motion": "^6.3.15",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.7.4",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`
My index.tsx file is:- 

`import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import { ChakraProvider, extendTheme,  type ThemeConfig } from '@chakra-ui/react'

const config: ThemeConfig = {
  initialColorMode: 'light',
  useSystemColorMode: false,
}
const theme = extendTheme({ config })

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);

console.log({config})

root.render(
  <ChakraProvider theme={theme}>
    <React.StrictMode>
      <App />
    </React.StrictMode>
  </ChakraProvider>
);`

I am attaching the screenshots of the outputs from google chrome and firefox with inspect element with this.
![Screenshot from 2022-06-27 17-51-06](https://user-images.githubusercontent.com/30878021/175940671-b1515d3a-7f84-4023-98ba-27726ad8d217.png)
![Screenshot from 2022-06-27 17-52-23](https://user-images.githubusercontent.com/30878021/175940680-01d4a8cd-bf5f-4a49-9367-ddb4772937de.png)
![Screenshot from 2022-06-27 17-52-39](https://user-images.githubusercontent.com/30878021/175940689-8cef13f1-320f-4cfc-b9a0-6d92cf251712.png)

**Comment by NickVishwamitra** [comment]
I think you are missing the ColorModeScript in your index file
https://chakra-ui.com/docs/styled-system/color-mode#for-create-react-app

Make sure you don't skip over this
<img width="593" alt="image" src="https://user-images.githubusercontent.com/88915328/176058218-4de38249-e66c-45e6-97f1-de412af2490a.png">

**Comment by kartset** [comment]
Thanks, @NickVishwamitra. This resolved my problem.
