### ISSUE TITLE
[PseudoBox] responsive style props within pseudo props

### ISSUE THREAD

**Issue by harlanlewis** [chakra-ui/chakra-ui#625]
**Describe the bug**
Responsive style props for PseudoBox are not compiled. For example:

```
<PseudoBox
  _after={{ 
    content: '"" ', // using "" in `content` may be related to [#561](https://github.com/chakra-ui/chakra-ui/issues/561), doesn't seem relevant here
    width: { base: '10px', md: '20px' }
  }}
>…</>
```

Omits `width` when compiled:
```
.css-1ysci86:after {
  content: "";
}
```

I thought I misunderstood it's usage, but variations result in no compiled CSS rules at all, eg:

```
<PseudoBox
  _after={{ 
    base: {
      content: '"" ',
      width: '10px',
    },
  }}
>…</>
```

**Expected Behavior**
CSS pseudo element rules wrapped in media queries.

**Comment by with-heart** [comment]
Hi @harlanlewis, this has been fixed in 1.0! https://codesandbox.io/s/codesandbox-react-js-template100-next2-44gv7?file=/src/App.js

See https://next.chakra-ui.com for more information on the 1.0 pre-release.
