### ISSUE TITLE
 Css style doesn't load as well in firefox 52 because of :host tag

### ISSUE THREAD

**Issue by carlpassos** [chakra-ui/chakra-ui#6253]
### Description

 When I try to load the app in firefox 52 it loses the main chakra theme

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-next-js-typescript-kxvyr

### Steps to reproduce

1. install the chakra ui using the "get started"
2. extend the "chakra ui" theme and apply the same different styles to any rendered component
3. load app in "firefox 52" browser 
4. the application wont render the chakra ui default styles because of the css :host tag

the way i found to "solve" the problem

```js
if (typeof window !== 'undefined') {
      const isFireFox52 =
        window.navigator.userAgent.indexOf('Firefox/52.0') >= 0;
      console.log(`isFirefox52 ${isFireFox52}`);
      if (isFireFox52) {
        const tagStyle = document.getElementsByTagName('style')[0]
        if (!tagStyle) return

        tagStyle.textContent = tagStyle.textContent.replace(':host,', '')
      }
    }
```

### Chakra UI Version

2.2.1

### Browser

Firefox 52

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Is there any easy way to enable some compatibility mode?

**Comment by segunadebayo** [comment]
Kindly follow the solution above as described by @TimKolberger
