### ISSUE TITLE
Tooltip stays open even after hovering away from the element

### ISSUE THREAD

**Issue by Monte9** [chakra-ui/chakra-ui#6255]
### Description

When I hover away from an element that has a Chakra Tooltip, I expect it to disappear, but instead it stays active and the tooltip is still seen.

### Link to Reproduction

https://codesandbox.io/s/billowing-dream-upj6me

### Steps to reproduce

1. Go to to the sandbox link above
2. Hover over the text 
3. The tooltip will pop up
4. Sometimes the tooltip will persist even when you hover away from the text

### Chakra UI Version

0.3.9

### Browser

Brave (Chromium)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This happens in our application that has a table with multiple UI element rendered at the same time. Each of these stars have a tooltip and sometimes when you hover away from the star, the tooltip still persists.

<img width="633" alt="Screen Shot 2022-06-28 at 10 01 31 AM" src="https://user-images.githubusercontent.com/7840686/176218876-99064442-46e4-495b-b2bd-8b9e4ee86861.png">

**Comment by yemi-js** [comment]
Yeah I noticed same thing

**Comment by AnanaMJ** [comment]
> Chakra UI Version
> 
> 0.3.9

The sandbox is using latest (2.2.6) and doesn't seem to persis the tooltip after you hover away. I've tried it in Brave and Firefox.
Have you tried upgrading the chakra ui version?

**Comment by bouncingbumble** [comment]
The latest version of Chakra hides tooltips the majority of the time but there are still a few cases where they will stay open.

**Comment by segunadebayo** [comment]
@itkrt2y has recently resolved this issue in a recent PR.

We'll publish a new release tomorrow. If, after the upgrade, the problem still exists in your application, please open a new issue and follow the instructions in the issue template.

Thanks
