### ISSUE TITLE
Typescript: Property '_hover' does not exist on type 'CSSObject'.

### ISSUE THREAD

**Issue by moritzjacobs** [chakra-ui/chakra-ui#6261]
### Description

When spreading `_hover` from the return of a `SystemStyleFunction`, I get this type error: `Typescript: Property '_hover' does not exist on type 'CSSObject'.`

### Link to Reproduction

https://codesandbox.io/s/chakra-hover-typing-problem-g72p2p?file=/src/buttons.ts

### Steps to reproduce

```tsx
import {
  StyleFunctionProps,
  SystemStyleFunction
} from "@chakra-ui/theme-tools";

const primary: SystemStyleFunction = (props: StyleFunctionProps) => ({
  background: "red.500",
  _hover: {
    background: "red.100"
  }
});

const secondary = (props: StyleFunctionProps) => {
  const p = primary(props);

  return {
    ...p,
    borderRadius: "none",
    _hover: {
      ...p._hover, // <--- type error
      borderRadius: "xl"
    }
  };
};

export const Button = {
  defaultProps: {
    variant: "primary"
  },
  variants: {
    primary,
    secondary
  }
};

```

```
Property '_hover' does not exist on type 'CSSObject'.
  Property '_hover' does not exist on type 'CSSWithMultiValues'.
```

### Chakra UI Version

2.2.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

We're currently working around it with `...(p as { _hover: CSSObject })._hover` ... 😬

Thanks for your support!

**Comment by ks-pp** [comment]
I'm running into this issue as well. Would be great if SystemStyleObject included these pseudo selector props like `_hover`.

Fixing this for SystemStyleObject would also fix other types based on it, like SystemStyleInterpolation, SystemStyleFunction, PartsStyleInterpolation, PartsStyleObject, and PartsStyleFunction.

I'm currently working around this by using a custom type, which I'm sharing below in case it helps anyone:
```
import type { Pseudos } from '@chakra-ui/system';
import type { SystemStyleObject } from '@chakra-ui/theme-tools';

export type CustomStyleObject = SystemStyleObject &
  {
    [K in keyof Pseudos]?: SystemStyleObject;
  };
```
