### ISSUE TITLE
Make it possible to customize FormErrorMessage in the theme

### ISSUE THREAD

**Issue by Zeilar** [chakra-ui/chakra-ui#6262]
### Description

After doing some digging, it appears you moved out FormErrorMessage from form-control. But the theme component named `FormError` is instead exported, and not to be found in the npm package anywhere. And when I try to style either `FormError` or `FormErrorMessage`in the theme it does not work, I don't think it's implemented at all.

### Problem Statement/Justification

Because I don't see a reason why you shouldn't be able to change this component on a theme level like you can on basically all the other components.

**Comment by zakariasahmane** [comment]
I have the same issue here. 

Trying to customize FormErrorMessage doesn't work. 

Here is a reproduction

https://stackblitz.com/edit/react-ww7z5z?file=package.json,src%2FApp.js,src%2Findex.js

**Comment by Zeilar** [comment]
Thank you for providing reproduction, my bad for forgetting to include that!

**Comment by segunadebayo** [comment]
Hi @Zeilar,

Here's the [structure of the form error message theme](https://github.com/chakra-ui/chakra-ui/blob/35b416761841da30194b8967d72049a27d78d099/packages/theme/src/components/form-error.ts#L3). It's a multipart component that includes the "icon" and "text" parts in it.

To customize it, you'll need to provide styles for any of those parts.

**Comment by segunadebayo** [comment]
https://stackblitz.com/edit/react-5udnqm?file=src/App.js
