### ISSUE TITLE
useBreakpointValue returns unexpected result between breakpoints

### ISSUE THREAD

**Issue by JaredMichel** [chakra-ui/chakra-ui#6269]
### Description

When I have a screen size somewhere between lg and xl, I expect useBreakpointValue to express my current breakpoint as "lg" or "xl"  but instead it returns "base".

### Link to Reproduction

https://codesandbox.io/s/laughing-phoebe-i3wybo?file=/src/index.tsx

### Steps to reproduce

1. Open the CodeSandbox example in a new full window
2. Open developer tools and set your screen width to 1279px.
3. Instead of "large" being printed to the screen, "base" is printed instead. If you reduce/increase the screen size by even just one pixel the correct value is printed to the screen.

### Chakra UI Version

2.2.1

### Browser

Google Chrome 103.0.5060.66

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

It's as if the default breakpoints for `useBreakpointValue` are exclusive and not inclusive to the actual pixel width for a breakpoint. If `1279px` is the start of the screen size for "xl" then I'd expect the breakpoint value to be "xl" at `1279px`.

I should also mention this is happening with a default set of breakpoint values. I have not extended the breakpoint values.

**Comment by effectivetom** [comment]
I can reproduce this on v2.2.0. It occurs at viewport widths one pixel less than each breakpoint (991px, 1279px, 1535px, etc.)

**Comment by effectivetom** [comment]
After a bit of digging in the source, I think this magic number is the issue:

https://github.com/chakra-ui/chakra-ui/blob/a57b6595fdfc7365c4d5e8a17674b944e4a1940d/packages/utils/src/breakpoint.ts#L39-L40

This value should probably be 0.0625 which is 1/16. Using 0.0635 means that Chakra's default media queries end up looking like this:

```
(min-width: 0em) and (max-width: 29.9365em)
(min-width: 30em) and (max-width: 47.9365em)
(min-width: 48em) and (max-width: 61.9365em)
(min-width: 62em) and (max-width: 79.9365em)
(min-width: 80em) and (max-width: 95.9365em)
(min-width: 96em)
```

Using the second query as an example, 768px is the desired breakpoint value. 47.9365 * 16 = 766.984 which excludes 767px.

Might have just been a typo?

**Comment by effectivetom** [comment]
@segunadebayo - see my comment [here](https://github.com/chakra-ui/chakra-ui/pull/6301#issuecomment-1185082588). Any chance we could address this somehow? I'd love to start using this fix but not sure what the correct process is.
