### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'gray' in undefined on React 3.4.1

### ISSUE THREAD

**Issue by fadhilx** [chakra-ui/chakra-ui#627]
**Describe the bug**
i got error `TypeError: Cannot use 'in' operator to search for 'gray' in undefined`

**Expected Behavior**
it should run without error

**To Reproduce**
1. install `create-react-app` to latest version, in this case (3.4.1)
2. create new project with `create-react-app`
3. add button on page
```jsx
import React from "react";
import PropTypes from "prop-types";
import "./LoginPage.scss";
import { Button } from "@chakra-ui/core";
const LoginPage = () => (
  <div className="LoginPage" data-testid="LoginPage">
    LoginPage Component
    <Button>Test</Button>
  </div>
);

LoginPage.propTypes = {};

LoginPage.defaultProps = {};

export default LoginPage;

```
4. save and See error
![image](https://user-images.githubusercontent.com/15516786/79863140-d321c800-8409-11ea-8723-709b3cdd7704.png)

**Suggested solution(s)**
only possible solution so far is to (maybe) downgrade react version. but to fix this issue must done on affected code 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 80

**Comment by segunadebayo** [comment]
Hi @fadhilx,

This error shows up with you're not wrapping the entire application in the `ThemeProvider`. 

Kindly go to the root of your application, import ThemeProvider and wrap your application in it.

Thanks.
