### ISSUE TITLE
Tooltip bg properties throw error when theme object is empty

### ISSUE THREAD

**Issue by Philzen** [chakra-ui/chakra-ui#6270]
### Description

Discovered in a RedwoodJS project, where any test on a component involving the Tooltip component fails when any background-related property is set

### Link to Reproduction

https://github.com/Philzen/chakra-redwood-toolip-bug

### Steps to reproduce

(you can skip step 1. – 3. by simply checking out the repository and follow the no-brainer instructions in [README.md](https://github.com/Philzen/chakra-redwood-toolip-bug/blob/main/README.md))

1. Set up a redwood JS project and add Chakra UI to it as per the official docs
2. Create a page and place Chakra Tooltip on it
3. Set any of  `bg`, `bgColor`, `background`, and `backgroundColor` on the tooltip and run the test suite
4. See error:   
   ```
   Error name:    "TypeError"
   Error message: "Cannot read properties of undefined (reading 'colors.red.600')"

   at Object.getCSSVar (node_modules/@chakra-ui/utils/dist/chakra-ui-utils.cjs.dev.js:367:69)
             at node_modules/@chakra-ui/tooltip/dist/chakra-ui-tooltip.cjs.dev.js:306:57
   ```

   Some other (potentially related root cause) that is being shown if you scroll up even further:

   ```
     console.error
       Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
           at AuthProvider (/home/phil/prog/testing/chakra-redwood-toolip-bug/node_modules/@redwoodjs/auth/dist/AuthProvider.js:61:5)
           at MockProviders (/home/phil/prog/testing/chakra-redwood-toolip-bug/node_modules/@redwoodjs/testing/dist/web/MockProviders.js:75:3)
           at wrapper
   ```

### Chakra UI Version

1.8.8

### Browser

Console

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

This happens only in a jest test in RedwoodJS. The project i'm working on uses dozens of Chakra components all tests are fine. After careful consideration and intense testing i'm opening the issue at this repository b/c i believe the root cause & the solution both lie in [Line 82 – 92 of tooltip.tsx](https://github.com/chakra-ui/chakra-ui/blob/main/packages/tooltip/src/tooltip.tsx#L82-L91).

## Investigation results:

* It does not matter what color you try to set for `bg` (even `#rrggbb` produces the error)
* The problem only happens on `bg`, `bgColor`, `background`, and `backgroundColor` (all other properties such as `color` work fine)
* Interestingly, the offending properties are **exactly** the properties dealt with [in this line of code](https://github.com/chakra-ui/chakra-ui/blob/main/packages/tooltip/src/tooltip.tsx#L82)
* When commenting out [Line 82 – 92](https://github.com/chakra-ui/chakra-ui/blob/main/packages/tooltip/src/tooltip.tsx#L82-L91) in that file, the problem goes away – and the component still works as expected!
* You can try it out directly in this project by commenting out the following lines in `./node_modules/@chakra-ui/tooltip/dist/chakra-ui-tooltip.cjs.dev.js` directly:
    ```js
    var userDefinedBg = (_ref = (_ref2 = background != null ? background : backgroundColor) != null ? _ref2 : bg) != null ? _ref : bgColor;

    if (userDefinedBg) {
      styles.bg = userDefinedBg;
      styles[popper.popperCSSVars.arrowBg["var"]] = utils.getCSSVar(theme, "colors", userDefinedBg);
    }
    ```
  * Even with these lines commented out, the component (incl. whatever backgroundColor you set) still works as expected 🤔

---

BTW i tried really hard setting up a codesandbox for this at https://codesandbox.io/s/confident-framework-qxwdx2?file=/src/redwood.test.tsx – but to no avail so far.

But the linked github repo should suffice, if even needed – if someone could kindly look at the aforementioned code lines and investigate what specific purpose they serve or if they could simply be dropped.

Unfortunately the code is not commented and gives no hint what the intention of that code construct in question is, there surely must have been one when they were written. 

Maybe @ashalfarhan could advise?

**Comment by ashalfarhan** [comment]
Hi @Philzen, it seems like you forgot to wrap the component with the `<ChakraProvider />` like this:

```tsx
expect(() => {
  render(
    <ChakraProvider>
      <TestTooltipPage />
    </ChakraProvider>
  )
}).not.toThrow()
```

**Comment by Philzen** [comment]
> Hi @Philzen, it seems like you forgot to wrap the component with the `<ChakraProvider />` like this:

I left it out on purpose b/c
1. the numerous tests i already have in a large application never crashed … hence i assumed RedwoodJS' mock provider takes care of wrapping that
2. i would have expected to see `Error message: "theme.__cssMap is undefined"` because that happens [in this codesandbox](https://codesandbox.io/s/headless-butterfly-empz9v?file=/src/index.test.tsx) when it is not wrapped

But thanks heaps @ashalfarhan for your feedback and making me try again – the error is not thrown anymore as soon as the test is wrapped, which makes me believe my assumption under 1. is wrong.

I am going to open an issue over at https://github.com/redwoodjs/redwood as well to have a look into it.

**Comment by Philzen** [comment]
> I think we should also check if `theme` is an empty object (which happened in this issue):

@ashalfarhan – Can you kindly advise the issue # you are referring to?

Side question: do you have an idea how to check the theme object in a jest test (cannot use the `useTheme`-hook as it is not a functional component).

> https://github.com/chakra-ui/chakra-ui/blob/25c4b583492939dda5d9c4b20b1f4bd017e8a77c/packages/system/src/providers.tsx#L54-L58

Interesting, when `<Tooltip/` is not wrapped in `<ChakraProvider>` it throws `"theme.__cssMap is undefined"` ([see codesandbox](https://codesandbox.io/s/headless-butterfly-empz9v?file=/src/index.test.tsx)) … it would be preferable for it to throw the error you have linked in that case i think.

Maybe, as i said in the issue description:

> When commenting out [Line 82 – 92](https://github.com/chakra-ui/chakra-ui/blob/main/packages/tooltip/src/tooltip.tsx#L82-L91) in that file, the problem goes away – and the component still works as expected!

... just remove them – or could you elaborate on their specific purpose? IMHO opinion these props exists anyway, they would need to be dealt with separately.

**Comment by ashalfarhan** [comment]
> Can you kindly advise the issue # you are referring to?

Sorry, I'm just trying to give some advice to the maintainer.

> Side question: do you have an idea how to check the theme object in a jest test (cannot use the useTheme-hook as it is not a functional component).

You can just create a function component,  call `useTheme` and try to log it (or check [this sandbox](https://codesandbox.io/s/great-gould-zmwfhm?file=/src/index.test.tsx)).

> it would be preferable for it to throw the error you have linked in that case I think.

Yes, I agree, because [this line](https://github.com/chakra-ui/chakra-ui/blob/25c4b583492939dda5d9c4b20b1f4bd017e8a77c/packages/system/src/providers.tsx#L54-L58) is only check for falsy values.

**Comment by Philzen** [comment]
OK, i've added some more tests against other Components (Box, Input, CircularProgress) in https://codesandbox.io/s/headless-butterfly-empz9v?file=/src/index.test.tsx and i believe we deduct a pattern here:

#### When running in a test environment, no ChakraUI component ever throws an error, even when not wrapped in  `ChakraProvider`

This seems to be the default behaviour, and Tooltip is the exception to this rule. Hence i must withdraw my suggestion from above, it maybe should *not* throw aforementioned error, but instead ~~it should just fail silently in [line 84](https://github.com/chakra-ui/chakra-ui/blob/main/packages/tooltip/src/tooltip.tsx#L84)~~ the *underlying error* in `getCssVar()` simply needs to be fixed :bulb: 

I think i'm going to prepare a PR for this.

**Comment by Philzen** [comment]
@segunadebayo From a RedwoodJS users perspective, this issue is still unresolved until merged and shipped in v1-branch. Kindly refer to [my comment in the linked PR](https://github.com/chakra-ui/chakra-ui/pull/6274#issuecomment-1175111895).
