### ISSUE TITLE
The lazy load component in Tabs will be render twice

### ISSUE THREAD

**Issue by HuPeng333** [chakra-ui/chakra-ui#6279]
### Description

When I want to send a request in the lazy load Tabs, I do this in the useEffect hook,   I expected it only run once, but it run twice when the tabs is selected

### Link to Reproduction

https://codesandbox.io/s/zealous-nobel-2lsdqg?file=/src/index.tsx

### Steps to reproduce

1. Open the console
2. Switch the tabs and check the console's output
3. You will find that it renders the component twice, but one of them gets unmounted very quickly

### Chakra UI Version

2.1.2

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by itkrt2y** [comment]
This is a correct behavior of react in strict mode.

Please read official docs. https://beta-reactjs-org-git-effects-fbopensource.vercel.app/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development
Especially this section => https://beta-reactjs-org-git-effects-fbopensource.vercel.app/learn/synchronizing-with-effects#fetching-data
