### ISSUE TITLE
Input/FormControl isInvalid should cast to boolean

### ISSUE THREAD

**Issue by cyberwombat** [chakra-ui/chakra-ui#628]
Right now the sample form in recipe does not work correctly because ` <FormControl isInvalid={errors.name}>` is not valid and will not create a red outline on error. It needs to change to `  <FormControl isInvalid={!!errors.name}>`. That's/ however a bit verbose so unless there is a reason not to perhaps casting ass boolean would be a good idea. (or fix the recipe form if not). I assume the the other properties like `isDisabled` may react the same way but I haven't test it.

**Comment by cyberwombat** [comment]
Lame

**Comment by IhsenBouallegue** [comment]
@cyberwombat I was losing my mind over this. !! Works and I find it good enough. Thank you.
