### ISSUE TITLE
Allow SliderMark to be themed

### ISSUE THREAD

**Issue by wladiston** [chakra-ui/chakra-ui#6280]
### Description

It would be nice to have the "mark" as a part of the component to be styled as well.

### Problem Statement/Justification

Currently, if you want to customize `SliderMark` you need to abstract it to another component

### Proposed Solution or API

```ts
const sliderStyle: ComponentStyleConfig = {
  // The parts of the component
  parts: ['container', 'track', 'thumb', 'filledTrack', 'mark'],
  // The base styles for each part
  baseStyle: {
    container: {...},
    track: {...},
    filledTrack: {...},
    thumb: {...},
    mark: {...}
  },
  // The size styles for each part
  sizes: {},
  // The variant styles for each part
  variants: {},
  // The default `size` or `variant` values
  defaultProps: {},
}
```

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
