### ISSUE TITLE
chakra-cli generates empty-ish type definition file with 'baseUrl' present in tsconfig

### ISSUE THREAD

**Issue by suimong** [chakra-ui/chakra-ui#6282]
### Description

When 'baseUrl' field is present in tsconfig.json, chakra-cli produces an empty-ish type definition file.

### Link to Reproduction

Refer to the repo mentioned below.

### Steps to reproduce

I made a repo to reproduce the issue [here](https://github.com/suimong/chakra-cli-issue-mwp-pnpm).

### Chakra UI Version

^2.2.0

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

The issue seems new to `chakra-cli@2.1.0` per @TylerAPfledderer's comment [here](https://github.com/chakra-ui/chakra-ui/issues/6197#issuecomment-1175583298).

**Comment by TimKolberger** [comment]
After a very short glance at the repo I noticed the pnpm lock file. I think the cli is not tested with pnpm, at least I didn't do it.

My long shot guess is, that the cli cannot find the theming.d.ts file to override in the node_modules.

**Comment by itkrt2y** [comment]
[workaround] Set `compilerOptions.esModuleInterop` to true
https://github.com/suimong/chakra-cli-issue-mwp-pnpm/blob/00189dd8cfb519046f3f62dd917d70ccbcea7595/tsconfig.json#L8

**Comment by suimong** [comment]
Thank you @itkrt2y! That was super quick!
