### ISSUE TITLE
Improve type definition for ComponentMultiStyleConfig

### ISSUE THREAD

**Issue by suimong** [chakra-ui/chakra-ui#6284]
### Description

Currently the "parts" field is typed `string[]`, which leads to type error if the given array is asserted as const (hence `readonly string[]`)).

### Link to Reproduction

https://codesandbox.io/s/romantic-lehmann-ruvuvp?file=/src/index.tsx

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

^2.2.0

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

A simple fix would be something like:
```typescript
export interface ComponentMultiStyleConfig {
    parts: string[] | readonly string[];
    // other props
}
```
But I'm wondering if there's a better way?

**Comment by StephenLHChan** [comment]
seems like the array should be initialised as below:

```TypeScript
const NavItemParts: string[] = ["list-item", "stack", "icon", "text"];
```

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
