### ISSUE TITLE
Chakra v2 ToastContainer is overwritting chakra color styles

### ISSUE THREAD

**Issue by Aycom366** [chakra-ui/chakra-ui#6285]
### Description

I expected everything to be normal after adding the Toast Container only to come back to my UI and notice colors changes

### Link to Reproduction

https://codesandbox.io/s/blue-cherry-h9z95d?file=/src/index.js

### Steps to reproduce

1. Open the code Sandbox Link
2. Comment out the `<ToastContainer/>` and see change in color

### Chakra UI Version

v2.2.1

### Browser

Google chrome

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

This was how I intend to use the toast component
```
import { ToastStatus } from 'utils/common/ToastStatus';
import { createStandaloneToast } from '@chakra-ui/toast';

export const { toast, ToastContainer } = createStandaloneToast();

export function ToastMessage(
  title: string,
  status: ToastStatus,
  duration?: number | 3000,
  description?: string
) {
  return toast({
    title,
    description,
    status,
    duration,
    isClosable: true,
    position: 'bottom-left',
  });
}
```

After doing all these, I imported the ToastComponent into my main.js file which is the root file like this
```
import { ToastContainer } from 'component/common/ToastComponent';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <Provider store={store}>
      <BrowserRouter>
        <ChakraProvider theme={theme}>
          <App />
          <ToastContainer />
        </ChakraProvider>
      </BrowserRouter>
    </Provider>
  </React.StrictMode>
);
```
But after changing back to my UI, I noticed my color as changed
![Screenshot from 2022-07-07 11-55-50](https://user-images.githubusercontent.com/42998943/177758195-753fea8f-2d41-4718-a409-149cf00a37b4.png)

But after removing the ToastComponent, I have my default color which is this
![Screenshot from 2022-07-07 12-00-20](https://user-images.githubusercontent.com/42998943/177758400-4e424b51-20d1-4495-b725-ed8d793e0def.png)
Code after commenting out the ToastComponent
```
ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <Provider store={store}>
      <BrowserRouter>
        <ChakraProvider theme={theme}>
          <App />
          {/* <ToastContainer /> */}
        </ChakraProvider>
      </BrowserRouter>
    </Provider>
  </React.StrictMode>
);

```

**Comment by TimKolberger** [comment]
Try passing your custom theme to the createStandaloneToast options parameter. I think the css variables are getting overridden by the default theme.

**Comment by Aycom366** [comment]
Oh wow, It works. But I feel it should be updated in the docs.
Thanks very much

**Comment by TimKolberger** [comment]
I think the yellow box warns about that:
https://chakra-ui.com/docs/components/toast#standalone-toasts

If you like to improve the message kindly open a PR in the docs repo 😊
