### ISSUE TITLE
AvatarBadge customize location

### ISSUE THREAD

**Issue by daniellin215** [chakra-ui/chakra-ui#6287]
### Description

According to the chakra docs, I don't see a place where we can customize the location of the avatar group's avatar badge.

### Problem Statement/Justification

Need a badge location customizer to place the badge to the top left of the anchor, which I can then add a `x` icon to handle removing a specific clicked badge's avatar from the group.

### Proposed Solution or API

Similar to MaterialUI, which allows us to customize the `anchorOrigin` to change the location of this badge [here](https://mui.com/material-ui/react-avatar/#with-badge)

### Additional Information

https://chakra-ui.com/docs/components/avatar/usage#avatar-with-badge

**Comment by segunadebayo** [comment]
We've just added support for this. Expect a new release shortly.

**Comment by rishav-eltropy** [comment]
Can we replace the Avatar badge with a custom Icon?

**Comment by pulkitvyas08** [comment]
> Can we replace the Avatar badge with a custom Icon?

Yes, you can do something like this:

```
       <Avatar
          mt="-80px"
          width="150px"
          height="150px"
          size="xl"
          border="5px solid #EFEDFF"
          src={profileImage}
        >
          <AvatarBadge
            cursor="pointer"
            borderColor="gray.300"
            bgColor="gray.300"
          >
            <BiPencil color="black" fontSize="20px" />
          </AvatarBadge>
        </Avatar>
```
