### ISSUE TITLE
Checkbox iconSize attribute didn't work as expected

### ISSUE THREAD

**Issue by nurullah** [chakra-ui/chakra-ui#6288]
### Description

I wanted to use a checkbox with large icon size and small text size and i was look at the checkbox documentation and i saw the iconSize attribute. But when i tried this attribute, i realized it didn't work.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-checkbox-iconsize-problem-34lx6p

### Steps to reproduce

1. Go to 'CodeSandbox link'
2. Look at the 'Checkbox Example'
3. Examine the 'iconSize' parameter
4. See it doesn't work

### Chakra UI Version

2.2.1

### Browser

Google Chrome 103

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by CharleeBrown** [comment]
Can I take this?

**Comment by anubra266** [comment]
https://user-images.githubusercontent.com/30869823/191015035-81cdc893-d0ae-408e-9f87-8bbb71b7190e.mp4

Your example is working quite fine on my end.
**NB:** `iconSize` simply sets `fontSize`, so whatever icon you use, ensure it works with fontSizes.

**Comment by TriupLauro** [comment]
I have the same problem.
The documentation implies it could accept any length like css value 

```jsx
<Checkbox iconColor='blue.400' iconSize='1rem'>
  Option
</Checkbox>
```

[This is from the documentation](https://chakra-ui.com/docs/components/checkbox/usage#changing-the-icon-color-and-size)

Changing this value doesn't change the size of the checkbox, only the size prop do but it can only accept "sm", "md" or "lg".
