### ISSUE TITLE
Next.js 12.2 dev mode seems to break portal based components (e.g. Drawer)

### ISSUE THREAD

**Issue by elmariachi111** [chakra-ui/chakra-ui#6297]
### Description

In Nextjs dev mode drawers don't open on button click

### Link to Reproduction

https://github.com/elmariachi111/test-drawer

### Steps to reproduce

1. compile that project (simple next starter)
2. yarn dev -> the drawer doesn't open
3. yarn build / yarn start -> the drawer works

### Chakra UI Version

2.2.3

### Browser

Firefox 101, Chrome 102

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

This is potentially related to SSR. 
tested with `useDisclosure` and `useState`
When looking at the DOM, two `chakra-protal` divs are created

![image](https://user-images.githubusercontent.com/1344649/178160115-7869d3da-b69e-4e07-9af1-1978c2611718.png)

**Comment by jonahallibone** [comment]
Same issue here, but with Modals. Seems to work again once the viewport is adjusted, or the tab is refocused. Breaks after that again until the same process is repeated
