### ISSUE TITLE
Modal in Nextjs Dev Doesn't Open

### ISSUE THREAD

**Issue by Pulverizer2020** [chakra-ui/chakra-ui#6304]
### Description

When I add a modal into my nextjs application, I expect it to open normally, but it doesn't open when running Nextjs in Dev mode. It works as expected when Nextjs is built for production.

### Link to Reproduction

https://codesandbox.io/s/loving-cori-eutf40?file=/pages/_app.tsx

### Steps to reproduce

The above link doesn't properly recreate the bug. However, by running the above code with the listed dependencies, the modal does not open in Nextjs dev mode, but does when it is built for production.

### Chakra UI Version

2.2.3

### Browser

Google Chrome 103

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by nvsd** [comment]
I'm getting the same thing using CRA.

**Comment by edgarmacas** [comment]
I have the same error, it worked fine but I downloaded my gitlab project again and installed with npm i, and from there it gives me the error

**Comment by grikomsn** [comment]
Putting this here that rolling back Chakra UI to version 2.2.1 fixes the issue on my Next.js 12.2 project.

**Comment by Pulverizer2020** [comment]
> Putting this here that rolling back Chakra UI to version 2.2.1 fixes the issue on my Next.js 12.2 project.

This did not fix the issue for me. What is your version of react?

**Comment by grikomsn** [comment]
Updated previous comment, current project I tested is React 18.

**Comment by Pulverizer2020** [comment]
> Updated previous comment, current project I tested is React 18.

Interesting, I also have React 18..

**Comment by shynsky** [comment]
> Putting this here that rolling back Chakra UI to version 2.2.1 fixes the issue on my Next.js 12.2 + React 18 project.

Which version of framer motion do you have?

**Comment by VVVi** [comment]
It looks like it happens for Chakra-UI 2.2.3, returning to 2.2.1 fix the issue.
"@chakra-ui/react": "2.2.1",

**Comment by VVVi** [comment]
Chakra-UI 2.2.2 also is ok :)

**Comment by manishMandal02** [comment]
This issue still exists, Why mark as closed?
The above solutions are just workarounds

**Comment by roxdiego** [comment]
> "@chakra-ui/react": "2.2.1"
The problem was solved with this information, but do you have any plans to correct this in the future?

**Comment by rohu19** [comment]
Chala jata hu kisi ki dhun me,
Zindagi hai yahan par magar armaan kahin aur hai.
