### ISSUE TITLE
useDimensions should update on dom element size change

### ISSUE THREAD

**Issue by jaslioin** [chakra-ui/chakra-ui#6314]
### Description

currently `useDimensions` return value does not change after mounting

### Problem Statement/Justification

In some cases the target element dimension is changed after mounting, e.g. when a `Card` element is to display some async data, before the data is fetched, the height is 100px, after data is fetched, the height changed to 200px.

### Proposed Solution or API

```jsx
const ref = useRef()
const val = useDimensions(ref)
// when mount: val.contentBox.width: 100
// when asyncData Loaded and update the DOM: val.contentBox.width: 200
return (
<Card ref={ref}>
{asyncData}
</Card>
)

```

### Alternatives

i workaround this by combining the `useMeasure` hook  from `react-use` library, `useMergeRef` and `useDimension`, quite nasty

```jsx
const [measureRef, measure] = useMeasure()
const dimensionRef = useRef()
const dimension = useDimension(dimensionRef)
const ref = useMergeRef(measureRef,dimensionRef)

const renderWidth = measure.width + dimension.padding.left + dimension.padding.right + dimension.border.left + dimension.border.right

console.log("width changed reactively!",renderWidth)
return (
 <Card ref={ref}>
{asyncData}
 </Card>
)
```

**Comment by jaslioin** [comment]
https://codesandbox.io/s/xenodochial-zhukovsky-tyt7z8?file=/src/App.js

codesandbox illustrating current behaviour

**Comment by segunadebayo** [comment]
Hi @jaslioin,

We're deprecating `useDimensions` in favor of `useSize` hook which does exactly as you've described. See the code here: https://github.com/chakra-ui/chakra-ui/tree/main/hooks/use-size

It'll be released shortly.
