### ISSUE TITLE
Modal not opening on clean install of v2.2.3

### ISSUE THREAD

**Issue by MikeWillis** [chakra-ui/chakra-ui#6317]
### Description

Clicking a Button component to open a Modal should open the Modal. Instead, the Modal does not open until some other (unrelated) state change takes place.

### Link to Reproduction

https://codesandbox.io/s/loving-spence-sevw0d?file=/src/index.js

### Steps to reproduce

1. Click `Open Modal`
-- the modal will not open, even though it should
2. Click `Change Some Other State`
-- the modal will open

### Chakra UI Version

2.2.3

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

- Downgrading to v2.2.1 fixes the problem
- removing `StrictMode` fixes the problem

https://github.com/chakra-ui/chakra-ui/discussions/6316

**Comment by segunadebayo** [comment]
This has been fixed in a recent PR. I just published a new release.
