### ISSUE TITLE
auto focus in Input not working inside a Popover or Menu component

### ISSUE THREAD

**Issue by GM1957** [chakra-ui/chakra-ui#6326]
### Description

when we put an Input component with autoFocus={true} inside Menu or Popover component autofocus is not working ideally it should auto focus in the Input component  

### Link to Reproduction

https://codesandbox.io/s/affectionate-goldstine-brw2yv

### Chakra UI Version

2.2.3

### Browser

chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Jessy-BAER** [comment]
Same issue with an Input inside Portal

**Comment by khannoussi-malek** [comment]
my solution :
1. Create a ref with `useRef`
`const myRef = useRef();`
2. Relate your ref with the input that you wanna be auto focused
`  <Input ref={initialFocusRef} />`
3. At the component Modal or Popover, add the parameter 'initialFocusRef' and give it your ref
`<Popover initialFocusRef={myRef}  >`



you can edit the sandbox (App component) with this code, and test by yourself :smile: 
[https://codesandbox.io/s/affectionate-goldstine-brw2yv
](https://codesandbox.io/s/affectionate-goldstine-brw2yv)
```ts
export default function App() {
  const initialFocusRef = useRef();
  return (
          <Popover
      placement='bottom'
      closeOnBlur={false}
      initialFocusRef={initialFocusRef}
    >
      <PopoverTrigger>
        <Button>Trigger</Button>
      </PopoverTrigger>
      <PopoverContent p={5} color='white'  borderColor='blue.800'>
  <Input ref={initialFocusRef} />
      </PopoverContent>
    </Popover>
  );
}
```

**Comment by segunadebayo** [comment]
Kindly use `initialFocusRef` as described above.

**Comment by ttat288** [comment]
in **package.json** you can try **"framer-motion": "^10.18.0"**  . The new version might not work, but when I downgraded it, it worked fine for me.
