### ISSUE TITLE
Popover `openDelay` and `closeDelay` props are ignored

### ISSUE THREAD

**Issue by Philzen** [chakra-ui/chakra-ui#6329]
### Description

When i pass an `openDelay` or `closeDelay` value to a `<Popover>` i'd expect the delay to change accordingly (as stated in the docs)

### Link to Reproduction

https://chakra-ui.com/docs/components/popover/usage#basic-usage

### Steps to reproduce

1. Go to the live examples page, e.g. the [most basic example](https://chakra-ui.com/docs/components/popover/usage#basic-usage)
2. Add a perceptible delay to open and close the `<Popover>`, i.e. change the first line to:
   ```jsx
   <Popover openDelay={30000} closeDelay={30000}>
   ```
3. The popup still opens and closes with the same default delay (200ms)

### Chakra UI Version

1.8.8 (discovered) | 2.2.3 (still there in live example)

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jcleefw** [comment]
I have seen this same issue

**Comment by Poukame** [comment]
I have the issue too. I use 2.3.1.

**Comment by Philzen** [comment]
:facepalm: Ahhh thanks @anubra266 for clarifying, now i see! Maybe we should make a note over at chakra-docs to clarify this in the props documentation?

**Comment by anubra266** [comment]
> 🤦 Ahhh thanks @anubra266 for clarifying, now i see! Maybe we should make a note over at chakra-docs to clarify this in the props documentation?

Yeah @Philzen please feel free to open an issue in the docs repo. Thanks.
