### ISSUE TITLE
Fonts are not getting applied when <ToastContainer /> is used

### ISSUE THREAD

**Issue by ganeshkrishnasharma** [chakra-ui/chakra-ui#6332]
### Description

As per the migration guide after adding <ToastContainer /> , none of the fonts defined in theme file are getting added.

### Link to Reproduction

https://codesandbox.io/s/pedantic-sunset-jyifzm?file=/src/index.js:475-493

### Steps to reproduce

Go to the above example and inspect the text to see that , the fonts defined in the theme file are not getting added. Instead its always as below

`--chakra-fonts-heading: -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";`
`--chakra-fonts-body: -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";`
`--chakra-fonts-mono: SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;`

The ones that i have defined in my theme file is like this
`const theme = extendTheme({
  fonts: {
    body: "arial, helvetica, sans-serif",
    heading: "arial, helvetica, sans-serif",
    mono: "arial, helvetica, sans-serif"
  }
});` 

But this never gets applied. 
<img width="515" alt="Screenshot 2022-07-16 at 9 55 09 AM" src="https://user-images.githubusercontent.com/39894982/179339388-ab32b751-d931-4397-b0d3-bae3d2c0fd46.png">

Also observed that there are 2 portal elements that gets added in the DOM.
<img width="336" alt="Screenshot 2022-07-16 at 9 59 53 AM" src="https://user-images.githubusercontent.com/39894982/179339378-6527675f-7892-4227-9ea9-b871688663e6.png">

### Chakra UI Version

2.2.4

### Browser

All browsers

### Operating System

- [X] macOS
- [X] Windows
- [x] Linux

### Additional Information

This is blocking our production release of React v18. Help is much appreciated.

**Comment by anubra266** [comment]
From the docs:
<img width="768" alt="CleanShot 2022-08-09 at 15 44 35@2x" src="https://user-images.githubusercontent.com/30869823/183678959-2875efb3-c342-42db-a549-6cac4e7d4b2f.png">
