### ISSUE TITLE
Theme configuration does not seem to work with Vite Bundler

### ISSUE THREAD

**Issue by zakariasahmane** [chakra-ui/chakra-ui#6338]
### Description

When i added the storybook addon, i saw all the Chakra components appear, but the theme configuration did not apply to them

### Link to Reproduction

https://github.com/zakariasahmane/chakra-storybook-react/

### Steps to reproduce

1. Clone repo https://github.com/zakariasahmane/chakra-storybook-react/
2. `cd chakra-storybook-react`
3.  Run `yarn install`
4. Run `yarn storybook`
5. Open the `Header` component => You will see that the theme is applied because i used a custom provider
6. Open the `Button` component under `Form` in the `Chakra UI` section, the theme is not applied and the color options are not even in the list of color schemes.

### Chakra UI Version

2.2.3

### Browser

Not related to browser

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

In the `preview` file under `.storybook` folder, you can notice the theme configuration as mentionned in the docs : 

```
export const parameters = {
  chakra: {
    theme,
  }
};
```

This piece of code doesn't seem to work, whereas configuring a `ChakraProvider` in the same file like this : 
```
export const decorators = [(Story) => (
  <ChakraProvider theme={theme}>
    <Story />
  </ChakraProvider>
)]
```

Works with custom components but do not apply to the Chakra UI section that has all the components. I need to use the library with a custom theme and it needs to be exposed from all sides, having the plugin makes it easier and timesaving for us and i would love it if you have either a workaround or a solution. 

Thanks

**Comment by bechurch** [comment]
Having this same issue!

**Comment by omarcresp** [comment]
still having the same issue, waiting for a work around 🙏

**Comment by morellodev** [comment]
I solved it by adding the Chakra decorator to the `decorators` array in `.storybook/preview.tsx`:

```tsx
import { ChakraProviderDecorator } from "@chakra-ui/storybook-addon/dist/feature/decorator/ChakraProviderDecorator";

export const parameters: {
  chakra: {
    theme: myTheme,
  }
};

export const decorators = [
  ChakraProviderDecorator,
  ...customDecorators // if any
];
```

**Comment by wjpg** [comment]
Same issue.

While only using the `parameters` declaration i.e.
```
export const parameters = {
  chakra: { theme }
};
```
Then _no_ Chakra styles are applied to the stories at all. Browser defaults only.

While using a `ChakraProvider` decorator (either via the import as in [this comment](https://github.com/chakra-ui/chakra-ui/issues/6338#issuecomment-1410515657), or via wrapping stories in `<ChakraProvider theme={theme}>` - then _no_ styles being declared via the theme are applied.

I have even managed to replicate this with a minimal theme object declared within `.storybook/preview.js` in order to eliminate any possibility of package/import issues.

Our stack is

```
"@chakra-ui/react": "^2.8.0",
"@chakra-ui/storybook-addon": "^5.0.1",
"@storybook/nextjs": "^7.4.5",
"storybook": "^7.4.5",
 ```

**Comment by guyfrommilkyway** [comment]
I had the same issue. 

From what I analyzed, when I run the application in development mode `npm run dev`, the custom theme passed to ChakraProvider works with no problem. 

But when I generate a build while setting `global = 'window'` and then run the application in production mode `npm run preview`, the custom theme for Chakra-UI doesn't get applied at all;

```
define: {
    global: 'window',
},
```


This is my custom theme.

```
import { extendTheme } from '@chakra-ui/react';

const theme = extendTheme({
  colors: {
    brand: {
      100: '#1F1A38',
      200: '#7B506F',
      300: '#EAD7D1',
      400: '#DBCDC6',
      500: '#CCCCCC',
    },
  },
  styles: {
    global: {
      body: {
        bg: 'brand.100',
      },
    },
  },
});

export default theme;

```

This vite config solves the issue for me.
```
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  const config = {
    plugins: [react()],
    define: {
      global: 'window',
    },
    resolve: {
      alias: {
        '@': '/src',
      },
    },
    server: {
      watch: {
        usePolling: true,
      },
    },
  };

  if (mode !== 'development') delete config.define;

  return config;
});
```

I added a conditional that removes the `define` property of the `config` object when the application isn't in development mode.

**Comment by segunadebayo** [comment]
Closing based on https://github.com/chakra-ui/chakra-ui/issues/6338#issuecomment-1410515657
