### ISSUE TITLE
Tailwind integration

### ISSUE THREAD

**Issue by nahtnam** [chakra-ui/chakra-ui#634]
Does this work well with tailwind? More specifically can I use some of the components in this library and add tailwind classes to customize them? It seems like this library took a lot of inspiration from there so it would be nice to be able to couple them together so users would have to seldom write css

**Comment by segunadebayo** [comment]
Hi @nahtnam, yes you can definitely use Chakra with Tailwind since it's just a bunch of class names you need to add.

Yes, Chakra's theme is inspired by Tailwind so you should be pretty good and most of Chakra's styling props should feel relatable.

Give it a try and let me know what you think.

**Comment by neilchaudhuri** [comment]
I have a CSS file generated by TailwindCSS, and I have, naively perhaps, simply been importing it as a CSS Module like this:

`import "../../styles/dist/my.css";`

And then I use the `className` prop to apply Tailwind-generated styles to a Chakra UI component. One such style for a text input is `w-input-md`, which I apply to Chakra's `Input`.

When I run things in Storybook, the `class` attribute on this input is `class="w-input-md  css-cth1sm"`, and that second class cancels out my class.

I have two questions:

- Is there a more sophisticated way I should apply raw CSS?
- If I am correct `css-cth1sm` is a class generated by Chakra UI, how can I disable that?

I know you are all very busy with an imminent release, but a quick response or pointer to documentation I missed is appreciated.

**Comment by Ojay** [comment]
Hi @segunadebayo - sorry to fire this back up. I'm debating ditching Tailwind in favour of Chakra but here it sounds like you could implement both. I'm not sure how appropriate it is to do so though as there'd be a ton of overlap in the middle, no?

How easy would it be to overwrite Chakra defaults with Tailwind? If using Tailwind you'd want to at least remove the vast majority of Chakra styling, right? Is that remotely possible? Otherwise I'd have thought it was a case of one or the other?

How did you get on using both @nahtnam??

Any perspective is greatly welcome, thanks!

**Comment by mbrookson** [comment]
My current `theme.ts` file for Chakra merges some of the Tailwind config into it to get the colours to match. The object schema seems the same but the colours are difference in each library. This way I can get both to work better together, but a proper integration would be nicer.

```ts
import { theme as chakraTheme } from "@chakra-ui/core";
// @ts-ignore
import resolveConfig from "tailwindcss/resolveConfig";
import tailwindConfig from "../../tailwind.config";

const tailwind = resolveConfig(tailwindConfig);

chakraTheme.colors.blue = tailwind.theme.colors.blue;

export const theme = {
  ...chakraTheme,
  colors: {
    ...chakraTheme.colors,
    blue: {
      ...chakraTheme.colors.blue,
      50: chakraTheme.colors.gray[50],
      100: chakraTheme.colors.gray[100],
    },
    darkBlue: {
      ...chakraTheme.colors.blue,
      50: chakraTheme.colors.gray[50],
      500: chakraTheme.colors.blue[800],
      600: chakraTheme.colors.blue[700],
      700: chakraTheme.colors.blue[800],
      800: chakraTheme.colors.blue[900],
      900: chakraTheme.colors.blue[900],
    },
  },
};

```

**Comment by fi0** [comment]
Does it make sense to use Chakra with https://github.com/ben-rogerson/twin.macro?

**Comment by ljosberinn** [comment]
@fi0 disclaimer: I haven't tried it. But from the looks of it: imo no, not really.

The resulting objects would only fit into the `sx` property of a chakra component, which I guess would work, but that circumvents the entire styled-system props which arguably should provide a better experience. Also, despite both boiling down to css, I wouldn't bet on everything mapping 1:1 as you'd expect it. Most will probably work, but I'd expect some edge cases.

**Comment by dwbelliston** [comment]
hey @mbrookson - could you share your tailwind.config file? - are you using module.exports or something else?

when i use the `import tailwindConfig from "./tailwind.config"` syntax i get this error on build:

```
Attempted import error: './tailwind.config' does not contain a default export (imported as 'tailwindConfig').
```

the tailwind.config file looks like this:

```
module.exports = {
  purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
....
```

**Comment by Abdul-Quadri-Ismail** [comment]
Here is a repo using Chakra and tailwind

https://github.com/Abdul-Quadri-Ismail/Pursuit

**Comment by jamesarosen** [comment]
One of the problems with mixing Chakra and Tailwind is that Chakra moves its `<style>` tags to the end of `<head>`, so they win over Tailwind's `<link>`ed stylesheet. That means
```tsx
<Button class="text-blue">
```
is going to generate
```css
/* tailwind */
.text-blue {
  color: blue;
}

/* chakra / emotion */
.css-14cpn8p {
  color: var(--chakra-colors-black);
}
```
and the Chakra-defined color will win over the Tailwind one.

**Comment by leohxj** [comment]
something like this ?
[material-ui/examples/material-cra-tailwind-ts/tailwind.config.js at master · mui/material-ui · GitHub - https://github.com/mui/material-ui/blob/master/examples/material-cra-tailwind-ts/tailwind.config.js](https://github.com/mui/material-ui/blob/master/examples/material-cra-tailwind-ts/tailwind.config.js)

**Comment by Sahnawaz7hussain** [comment]
@segunadebayo As Chakra ui provides custom props for styling, It would be great if some props name make short,
ex: fontFamily -> fFamily  or fntFam, fontSize -> fSize or fntSiz, textDecoration -> txtDec, textTransForm -> txtTra,

**Comment by artemis-prime** [comment]
Sorry, but why is this marked closed?  I think it's a very common use case and worth tending to. @jamesarosen 's suggestion seems to be a great direction?  

@segunadebayo
