### ISSUE TITLE
Cant Change Collapse Width

### ISSUE THREAD

**Issue by Distortedlogic** [chakra-ui/chakra-ui#6340]
### Description

When I use methods to change collapse width, nothing happens

### Link to Reproduction

https://codesandbox.io/s/friendly-smoke-3yn9y8?file=/src/index.tsx

### Steps to reproduce

There is a 100% flex both as a parent n child of collapse but collapse doesnt adjust it width

### Chakra UI Version

2.2.4

### Browser

Google Chrome Latest

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Note that collapse itself has no width related props

**Comment by wrux** [comment]
Looks like it's hardcoded just to animate height: https://github.com/chakra-ui/chakra-ui/blob/790d2417a3f5d59e2d69229a027af671c2dc0cbc/packages/transition/src/collapse.tsx

You could just create your own custom component with Framer motion. I just created something quick, but the styling would need adjusting: https://codesandbox.io/s/cool-shadow-c9c1kf?file=/src/index.tsx

**Comment by JeremySazMining** [comment]
thanks. I still want it to animate vertically, but I want to be able to change the width of the collapse. You added a flex with w="100%" manually .. Why cant I pass w="100%" to the collapse and it work? that seems the most preferred behavior

**Comment by segunadebayo** [comment]
This is happening because the Collapse component is not a chakra component that can take style props. Swapping it to use the Box component and adding style props works.

```jsx
<Flex border="1px solid blue">
      <Box as={Collapse} in={true} w="100%">
        <Flex w="100%" border="1px solid red">
          <Text>my collapse text</Text>
        </Flex>
      </Box>
</Flex>
```

**Comment by GorgeousPuree** [comment]
> This is happening because the Collapse component is not a chakra component that can take style props. Swapping it to use the Box component and adding style props works.
> 
> ```js
> <Flex border="1px solid blue">
>       <Box as={Collapse} in={true} w="100%">
>         <Flex w="100%" border="1px solid red">
>           <Text>my collapse text</Text>
>         </Flex>
>       </Box>
> </Flex>
> ```

Hmm, how do you use `Collapse`'s `transition`?
If you put `transition={{enter: {duration: indexNum / 2}}}` as a prop of the `Box`, it'll say **Type '{ enter: { duration: number; }; }' is not assignable to type 'ResponsiveValue<Transition<string & {}>> | undefined'**, as it tries to set it into default `Box`'s `transition`, not the `Collapse`'s one. How can I let React know that I need to use `Collapse`'s `transition` prop?
