### ISSUE TITLE
Theme is missing for `Image` component

### ISSUE THREAD

**Issue by ArkShocer** [chakra-ui/chakra-ui#6343]
### Description

When I extend the theme with the `Image` component I expect to be able to create different `variants` but I'm not able to.

### Link to Reproduction

https://codesandbox.io/s/mystifying-fast-0izpcc

### Steps to reproduce

1. Go to https://chakra-ui.com/docs/components/image
2. Click on "Theme source"
3. See missing theme component error

### Chakra UI Version

2.2.3

### Browser

Microsoft Edge 103

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

No theme `image` component is provided under https://github.com/chakra-ui/chakra-ui/tree/main/packages/theme/src/components that's why I'm not able to add variants or change the default style. Unfortunately, my knowledge in TypeScript isn't really that good, and I'm not even sure if it's intended that way or not before making a pr.

**Comment by segunadebayo** [comment]
Hey @ArkShocer,

This is by design. We think the image component should be used to render images only. If you want visually alter the image, feel free to pass style props to it.

We'll consider this use case in the future.

Thanks for understanding.
