### ISSUE TITLE
Highlight should allow passing undefined, or empty array.

### ISSUE THREAD

**Issue by dbousamra** [chakra-ui/chakra-ui#6344]
### Description

When I pass an empty string, undefined, or empty array, I expect the Highlight component to not highlight each character

### Link to Reproduction

https://codesandbox.io/s/cool-cloud-ymdugd?file=/src/index.tsx

### Steps to reproduce

```
<Highlight query={[]} styles={{ px: "1", py: "1", bg: "orange.100" }}>
  With the Highlight component, you can spotlight words.
</Highlight>
```

### Chakra UI Version

2.2.4

### Browser

Google Chrome

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by takethefake** [comment]
Hej @dbousamra thanks for pointing this out!

We currently didn't handle empty strings / arrays well. I've created a PR that should fix this.
