### ISSUE TITLE
Component doesn't accept Props type from Chakra UI

### ISSUE THREAD

**Issue by lethanhvietctt5** [chakra-ui/chakra-ui#6345]
### Description

When I custom a component, I want to recieve Props which type of  Chakra UI component Props as parameter but it does not accept and show many errors

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-typescript-pomi8

### Chakra UI Version

2.2.1

### Browser

Google Chrome 103

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![2022-07-19_100744](https://user-images.githubusercontent.com/45467177/179656261-ec5d1150-b28c-4732-a381-08d1ed50ebe0.png)
![292123306_1203814890413333_5535394627417228758_n](https://user-images.githubusercontent.com/45467177/179656262-b39d90b1-8b1f-4ead-8446-f7667bff9645.png)

**Comment by takethefake** [comment]
Hej @lethanhvietctt5,

it seemed like your csb was empty. I recreated it based on your screenshot. https://codesandbox.io/s/kind-breeze-pp0eh7?file=/src/index.tsx

you would wrap an existing component like this:
```tsx
import {
  forwardRef,
  MenuItemProps,
  MenuItem as ChakraMenuItem,
} from "@chakra-ui/react";

const MenuItem = forwardRef<MenuItemProps, "button">((props, ref) => {
  return <ChakraMenuItem className="font-roboto" {...props} ref={ref} />;
});

```

Does this solve your question?
