### ISSUE TITLE
Style not being applied with NextJS + Chakra-ui

### ISSUE THREAD

**Issue by boukmi** [chakra-ui/chakra-ui#6350]
### Description

When I follow the documentation and set up a next js project with chakra-ui, I expected everything to work, but instead it looks like the styles are not being applied.
Once the project is set up following the tutorial on the website, some of the styling is not being applied
The tutorial that I have followd:
[Getting Started with Nextjs](https://chakra-ui.com/getting-started/nextjs-guidez)

### Link to Reproduction

https://codesandbox.io/s/hungry-ritchie-c5913e

### Steps to reproduce

In codesandbox it worked perfectly

### Chakra UI Version

2.2.4

### Browser

Google Chrome 103

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Here is my **package.json** file:
```json
{
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@chakra-ui/react": "^2.2.4",
    "@emotion/react": "^11",
    "@emotion/styled": "^11",
    "framer-motion": "^6",
    "next": "12.2.2",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "@types/node": "18.0.6",
    "@types/react": "18.0.15",
    "@types/react-dom": "18.0.6",
    "eslint": "8.20.0",
    "eslint-config-next": "12.2.2",
    "typescript": "4.7.4"
  }
}
```
**_app.tsx**
```typescript
import type { AppProps } from 'next/app'
import { ChakraProvider } from "@chakra-ui/provider";

function MyApp({ Component, pageProps }: AppProps) {
  return (
      <ChakraProvider>
        <Component {...pageProps} />
      </ChakraProvider>
  )
}

export default MyApp
```
And **index.tsx**
```typescript
import {Button} from "@chakra-ui/react";

const Home = () => {
  return (
        <Button colorScheme="teal">Button</Button>
  );
}

export default Home
```
Ann the result is as follow:
![image](https://user-images.githubusercontent.com/2116866/179862990-0f9331ea-dc7b-4f66-8ede-f7380aa9cb74.png)
Please help, I've been struggling with this issue fro the last 48h.

PS: the tutorial works perfectly when using plain javascript (no typescript)

Thank you

**Comment by takethefake** [comment]
Hej @boukmi,

since it works well in codesandbox it is quite hard for us to help you debugging the issue could you provide us with a **minimal** github project reproducing the error which we can check out to verify the issue?

**Comment by segunadebayo** [comment]
The issue here is that, in `_app.tsx`, you're importing `ChakraProvider` from the `@chakra-ui/provider` instead of `@chakra-ui/react`.

**Comment by 0xAnon101** [comment]
Hey there, I am facing the same issue, but I am using javascript.
```
import React from "react";
import { createRoot } from "react-dom/client";
import { ChakraProvider } from "@chakra-ui/react";
import AppRoutes from "routes/routes.js";

import "./style.scss";

/**
 * Renders the app onto the DOM
 */
const container = document.getElementById("root");
const root = createRoot(container);

root.render(
  <div className="root-child">
    <ChakraProvider>
      <AppRoutes />
    </ChakraProvider>
  </div>
);
```



here is my  component - 
```
// login.js
import React from "react";
import { Button } from "@chakra-ui/react";

const Login = () => {
  return (
    <div className="login-container">
      <div className="left-side">
        <div className="company-name">P.I.V.O.T Security</div>
        <i className="motto">Detect. Defend. Disrupt</i>
      </div>
      <div className="right-side">
        <Button colorScheme="teal">Click Here</Button>;
      </div>
    </div>
  );
};

export default Login;

```

Here is the output - 
<img width="301" alt="Screenshot 2023-01-20 at 1 40 40 PM" src="https://user-images.githubusercontent.com/13881992/213647333-466064c0-1b86-4b58-8018-382cddca4729.png">

**Comment by 0xAnon101** [comment]
Just an update @segunadebayo . It did work when i reverted back to 1.8.8 version of chakra-ui. There maybe something wrong with v2 or the documentation is not proper

**Comment by waqasansarii** [comment]
I am facing same error, how to resolve it ?

**Comment by 0xAnon101** [comment]
@waqasansarii v2 worked on my end . I updated my create-react-app, I was using the old version. All I then did was copy pasted my codebase, and it magically worked.

**Comment by pythonruss** [comment]
Happening to me too, but seems to effect only buttons for some reason. typescript / react 18
