### ISSUE TITLE
How to have a name color holding 2 colors, for light and dark mode ?

### ISSUE THREAD

**Issue by voyagebagage** [chakra-ui/chakra-ui#6352]
is there a way to make that below working ?
```jsx
colors:{
primary: mode("pink","blue")(props),
secondary etc...
}
```

because the result is that I have to have a primaryDark color and all my components are filled with 
```jsx
 export const ButtonStyles = {
 variants: {
    primary: (props) => ({
    bg: mode("primary","primaryDark")(props)
    }),
    },
    }
``` 
....

_Originally posted by @voyagebagage in https://github.com/chakra-ui/chakra-ui/issues/591#issuecomment-1190209356_

**Comment by takethefake** [comment]
Hej @voyagebagage,

we've introduced a feature called [semantic-tokens](https://chakra-ui.com/docs/styled-system/semantic-tokens) 

A possible solution for your scenario can be found in this codesandbox: https://codesandbox.io/s/amazing-franklin-yj3qhh?file=/src/index.tsx:124-125

**Comment by segunadebayo** [comment]
Closing based on @takethefake's comment above

**Comment by voyagebagage** [comment]
@takethefake thanks a lot, really helping
