### ISSUE TITLE
Tooltip does not work with a lg Switch

### ISSUE THREAD

**Issue by tim-hub** [chakra-ui/chakra-ui#6353]
### Description

When I wrap a Swich into a Tooltip, tool tip not pointed bottom center as unexpected 

### Link to Reproduction

https://codesandbox.io/s/quiet-browser-t8pjbj

### Steps to reproduce

1. Hover on Switch
4. See the issue, as screen shot

![image](https://user-images.githubusercontent.com/2884320/180081759-2d413475-de56-42cb-aa9f-1145e4629985.png)

### Chakra UI Version

2.2.4

### Browser

Firefox 102

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

- wrap on Button/IconButton, does not give problem

**Comment by takethefake** [comment]
Hej @tim-hub thanks for reaching out,

the problem exists, because on how we handle the `Tooltip` component to work. A possible solution for this behavior can be to add `shouldWrapChildren` to the `Tooltip

**Comment by segunadebayo** [comment]
This happens because the underlying `ref` of the Switch, Radio, and Checkbox components point to the visually hidden input element. The solution will be to ensure that the size of the visually hidden element is in sync with the rendered visual control

**Comment by segunadebayo** [comment]
Kindly use `shouldWrapChildren` to solve this use case.
