### ISSUE TITLE
Wrap - overflow:hidden - causing issues with "position: relative" and "position: absolute" inside.

### ISSUE THREAD

**Issue by Daniel-Novikov** [chakra-ui/chakra-ui#6354]
### Description

When inside the Wrap component, relative and absolute positioned elements will be cut off, because of the latest update to add "overflow: hidden"

### Link to Reproduction

https://codesandbox.io/s/sleepy-shadow-rf7cl0

### Steps to reproduce

1. Go to '[...](https://codesandbox.io/s/sleepy-shadow-rf7cl0)'
3. See error - the red square should be fully visible, yet it's cut off.

### Chakra UI Version

2.2.3

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

So basically when you have "overflow: hidden" on container (Wrap), any child element with "absolute" position, that is "relative" to this container will be cut off. 

This can happen if you have, lets say, complex button, with a bunch of "absolute" positioned elements inside of, that need to "bleed out", but because of the "Wrap" component, they will be invisible. 

It's been added in this commit - https://github.com/chakra-ui/chakra-ui/pull/6011/commits/65488b9fd4a727c86ea26604a186dd6917839924

Only happens in Chakra v2

**Comment by segunadebayo** [comment]
Hi @Daniel-Novikov, kindly add `overflow=visible` to the Wrap component to solve this issue.

**Comment by Daniel-Novikov** [comment]
Thanks! Yep, I was wondering why was it added in the first place - i.e. does Wrap even need `overflow: hidden`?

I suspect more people would have that issue, after migrating from Chakra v1 to v2, and it could be very confusing & frustrating the first time you see it.

**Comment by JClackett** [comment]
Yeah, just upgraded to v2 and now I have hundreds of places I have to add overflow visible to, is this the only way?

**Comment by selrond** [comment]
Just got bitten by this when migrating to v2. @segunadebayo mind expanding a bit on the reason behind this change?
