### ISSUE TITLE
user agent style focus for text element inside svg

### ISSUE THREAD

**Issue by JeremySazMining** [chakra-ui/chakra-ui#6358]
### Description

I expected resetCSS to not usage useragent style sheet here and chakra element prop _focus to override it since its there 

### Link to Reproduction

https://codesandbox.io/s/friendly-benji-h6dzyf?file=/pages/TextBox.tsx

### Steps to reproduce

drag text box and see the border on focus .. observe in the code TextBox.tsx the `_focus={{}}` 

### Chakra UI Version

2.2.4

### Browser

Google Chrome Latest

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Im using the lastest Chrome version. I want to override the border created when dragging which I think is coming for focus css being set by user agent stylesheet. This border does not appear for firefox. I tried both with chakra factory and plain jsx elements with the same results.

![21-07-2022-08-54-09](https://user-images.githubusercontent.com/108763555/180218219-82b49601-b15a-4e6f-8f1e-f178d81d44cd.png)

![21-07-2022-08-54-20](https://user-images.githubusercontent.com/108763555/180218257-9c70214e-f4c4-4a3b-ad61-39b32e489b33.png)

![21-07-2022-09-00-27](https://user-images.githubusercontent.com/108763555/180219564-d3b107b9-56a7-425e-8f31-454a5661e527.png)

![21-07-2022-09-00-34](https://user-images.githubusercontent.com/108763555/180219585-38d07c15-6abd-43be-ad33-e150e54b9061.png)

![21-07-2022-09-06-08](https://user-images.githubusercontent.com/108763555/180220706-87044df0-1216-4cf6-bbca-0c3a8f2e6559.png)

![21-07-2022-09-06-20](https://user-images.githubusercontent.com/108763555/180220742-136d905a-82a2-4a39-944e-ca653f8cc193.png)

**Comment by segunadebayo** [comment]
Hey @JeremySazMining,

`chakra.text` is not a valid element for now. Consider styling that element from the parent svg instead.

```jsx
<chakra.svg sx={{ text: { "&:focus": {...} } }} />
```
