### ISSUE TITLE
Typescript complains when calling a function returning ReactNode as ChakraProvider child

### ISSUE THREAD

**Issue by dgrcode** [chakra-ui/chakra-ui#6364]
### Description

When I used the method described in NextJS docs for per-page layout, I expected types to be correct, but typescript complains about it.

### Link to Reproduction

https://codesandbox.io/s/chakra-nextjs-typescript-with-per-page-layouts-6rj9wx?file=/pages/_app.tsx:586-599

### Steps to reproduce

1. Go to the file `_app.tsx`
2. In line 23, see how Typescript shows an error.

### Chakra UI Version

2.0.4

### Browser

Brave 1.35.101 (Chromium: 98.0.4758.87)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The app in codesandbox was working just fine, but it seems interactivity has somehow broken. Links and button don't work. I'm guessing that's a codesandbox glitch, but that's not the point of this issue.

I want to know how to fix the type error. It might be that I'm doing something wrong, I'm not sure.

**Comment by itkrt2y** [comment]
This is not a chakra's issue.

```diff
// L19
- const getLayout = Component.getLayout ?? ((page: NextPage) => page);
+ const getLayout = Component.getLayout ?? ((page) => page);

// or 

+ const getLayout = Component.getLayout ?? ((page: ReactElement) => page);
```

**Comment by dgrcode** [comment]
Oh my bad! Thanks for the super fast reply 🙌 

I'm not sure why I had added that type, when it's not in NextJS documentation. I assumed the issue what with Chakra because the message said the expected type came from Chakra's types, but that was a bit misleading. That might explain why I couldn't find any solution.

Thanks again! And sorry for taking your time to solve an issue unrelated with Chakra!
