### ISSUE TITLE
React does not recognize the `minW` prop on a DOM element

### ISSUE THREAD

**Issue by afalahi** [chakra-ui/chakra-ui#6365]
### Description

When I used the prop 'minW' on 'MenuButton' I don't expect a warning

### Link to Reproduction

https://codesandbox.io/s/peaceful-fast-ds3249?file=/src/index.js

### Steps to reproduce

1. Check the console

### Chakra UI Version

2.2.4

### Browser

Edge Version 103.0.1264.62

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

The app works fine, this is just an error in the console that's annoying. Changing to lowercase removes the error

**Comment by itkrt2y** [comment]
This is because you pass `as={"button"}` to `<MenuButton minW={0}>`.
When using chakra style props, do not use regular HTML tags. In this case, I think it's enough to remove `as={"button"}`.

**Comment by segunadebayo** [comment]
Closing based on @itkrt2y's comment above.
