### ISSUE TITLE
[Flex] where is flex-flow?

### ISSUE THREAD

**Issue by bernaferrari** [chakra-ui/chakra-ui#637]
I can't make Flex break lines because there is no `flex-flow: row wrap;`. If there is another way of doing this, it is undocumented. So I suggest either add a description on how to break lines with Flex, or add that to itself.

**Comment by jamezrin** [comment]
Just pass it to the css prop

```jsx
<Flex css={{
    flexFlow: "row wrap"
}}>
...
</Flex>
```

**Comment by bernaferrari** [comment]
Shouldn't there be a shortcut like everything else?

**Comment by jamezrin** [comment]
You can already do it with the two `direction` and `wrap` properties, flow is just a shorthand. In my opinion it's redundant

**Comment by segunadebayo** [comment]
Thanks for chiming in on this @jamezrin. We don't plan to support all `css` styles in props, just the common ones.

For now, please use the `css` or `style` prop to achieve this.

**Comment by hutber** [comment]
It would be great to be able to use flexflow
```
const centerAlign = {
  display: "flex",
  flexFlow: "column",
  alignItems: "center",
}
```

If we could, then we would be able to spread over all these css options.
