### ISSUE TITLE
Tooltip does not work with Fullscreen API

### ISSUE THREAD

**Issue by honungsburk** [chakra-ui/chakra-ui#6373]
### Description

When using the Fullscreen API tooltips are not displayed

### Link to Reproduction

https://github.com/honungsburk/chakra-fullscreen-tooltip-bug

### Steps to reproduce

1. download the git repo
2. npm install
3. npm run dev

### Chakra UI Version

2.2.4

### Browser

Brave Version 1.41.96 Chromium: 103.0.5060.114 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

You are now allowed to use the fullscreen API in codesandbox so I had to put my reproduction of the issue on Github.

**Comment by segunadebayo** [comment]
The fullscreen API narrows the DOM to the element that requested fullscreen. Because the Portal is appended to the `document.body` and the requesting element is within it, the tooltip doesn't show up (but it's the DOM)

To fix this, pass portal-specific props to the tooltip to tell it what element it should append to.

```jsx
<Tooltip label="should always be visible" portalProps={{ containerRef: ref }}>
    <Button onClick={fullscreenAction.toggle}>Toggle</Button>
</Tooltip>
```

**Comment by azhoang-sts** [comment]
Hi @segunadebayo, Besides the tooltip, this is not working with the popover and another dialog, can you apply portalProps for all them?

> The fullscreen API narrows the DOM to the element that requested fullscreen. Because the Portal is appended to the `document.body` and the requesting element is within it, the tooltip doesn't show up (but it's the DOM)
> 
> To fix this, pass portal-specific props to the tooltip to tell it what element it should append to.
> 
> ```js
> <Tooltip label="should always be visible" portalProps={{ containerRef: ref }}>
>     <Button onClick={fullscreenAction.toggle}>Toggle</Button>
> </Tooltip>
> ```
