### ISSUE TITLE
EnvironmentProvider appends a span to DOM which breaks some unit tests

### ISSUE THREAD

**Issue by ksocha** [chakra-ui/chakra-ui#6374]
### Description

I've noticed that EnvironmentProvider appends an empty span to the document which in my case breaks some unit tests that check if specified components do NOT render any elements. I'm using react-testing-library.

### Link to Reproduction

https://codesandbox.io/s/chakraprovider-empty-span-issue-qbmbdw

### Steps to reproduce

Visible in any case when ChakraProvider is being used.

### Chakra UI Version

2.2.4

### Browser

N/A

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

It was already mentioned https://github.com/chakra-ui/chakra-ui/issues/5855#issuecomment-1095400843.

In my case, when using RTL to unit test a component, with following test:
```
    const { container } = customRender(<ComponentThatShouldNotRenderAnything />);

    expect(container).toBeEmptyDOMElement();
```

and setup like:
```
const TestProviders = ({ children }: { children: React.ReactNode }) => {
  return (
      <ChakraProvider theme={theme}>{children}</ChakraProvider>
  );
};

const customRender = (
  ui: React.ReactElement,
  options?: RenderOptions,
): RenderResult => render(ui, { wrapper: TestProviders, ...options });
```

The above test is failing when using `ChakraProvider`.

I believe it could be solved by adjusting a `mounted` conditional in `EnvironmentProvider` and making it like: `mounted && !node`. This is how I solved my issue for now, I made a patch using `patch-package`. However, I'm not aware of any potential issues it may cause. Maybe there is a better way of solving this issue.

**Comment by KirillKirill** [comment]
hey @ksocha!
I'm facing the same issue. Looks like `toHaveTextContent('')` resolves this
