### ISSUE TITLE
Popover trigger automatically focused when page loads

### ISSUE THREAD

**Issue by Thebigbignooby** [chakra-ui/chakra-ui#6379]
### Description

When I load my app, the popover trigger is automatically focused

### Link to Reproduction

https://codesandbox.io/s/suspicious-mcclintock-ofrqiz?file=/src/UserMenu.tsx

UNABLE TO REPRODUCE IN CODESANDBOX

### Steps to reproduce

!unable to reproduce in codesandbox

### Chakra UI Version

^1.8.8

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I am unable to reproduce this in codesandbox,

But if anyone has any ideas to point me in the right direction 😅 .

I tried adding a SkipNavLink and SkipNavContent, and the PopoverTrigger still gets focused first.
I tried adding a `tabIndex={<insert any number here>}` to the `IconButton` i use as my trigger, and it still gets focused automatically when the page loads.

What could be causing the Popover to yank the focus?

**Comment by segunadebayo** [comment]
Hi @Thebigbignooby,

This is a known issue when using v1.x with React 18. Kindly upgrade to 2.x where this issue is fixed.

Thanks
