### ISSUE TITLE
Uncaught ContextError: useStyles: "styles" is undefined. Seems you forgot to wrap the components in "<InputGroup />"

### ISSUE THREAD

**Issue by MADEiN83** [chakra-ui/chakra-ui#6387]
### Description

I expected to have left and right addons for the Input component, but got an exception instead.

### Link to Reproduction

https://codesandbox.io/s/dazzling-surf-d7j1r6?file=/src/index.tsx

### Steps to reproduce

1. Go to the [link to reproduction](https://codesandbox.io/s/dazzling-surf-d7j1r6?file=/src/index.tsx)
2. Do nothing ;-)
3. See error

![image](https://user-images.githubusercontent.com/9880560/181710082-f439ac52-05f0-4d28-840b-d61a1538f81c.png)

### Chakra UI Version

2.2.4

### Browser

Google Chrome 103.0.5060.114

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by itkrt2y** [comment]
As the error message explains, you forgot to wrap the components in `<InputGroup>`

https://chakra-ui.com/docs/components/input/usage#add-elements-inside-input

```tsx
<InputGroup>
  <Input />
  <InputRightAddon children=".com" />
</InputGroup>
```

**Comment by MADEiN83** [comment]
OMG, I think I was tired -_-
Thanks for reading the exception for me xD
