### ISSUE TITLE
How to change the background color of a IconButton of the 2 modes

### ISSUE THREAD

**Issue by voyagebagage** [chakra-ui/chakra-ui#6389]
### Description

the light mode is having an annoying white background of IconButtons

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-javascript-lzzg9

### Steps to reproduce

![Capture d’écran 2022-07-29 à 17 26 58](https://user-images.githubusercontent.com/81431557/181740357-a131d64f-71e4-4879-9261-96b706eb01d3.png)

I have tried something like that :
```js
semanticTokens: {
    colors,
    components: {
    IconButton: {
      colorScheme: { // or bg or color
        default: "red",
        _dark: "brown",
      },
    },
```
I also tried like that directly in the overrides:
```js
 const overrides = {
 IconButton: (props) => ({
     bg: mode(darken("#4ff3cc", 10), whiten("#30373D", 37))(props),
     }),
 } 
 const customTheme = extendTheme(overrides);
``` 
 I also tried in baseStyle and defaultProps and in global style
 ```
 styles: {
    global: (props) => ({here})
    }
```

### Chakra UI Version

 "@chakra-ui/react": "^1.8.3",

### Browser

Brave, 1.40.107 chromium

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

using chakra ui within Next.js no TS

**Comment by segunadebayo** [comment]
Here's how to achieve that:

```jsx
<IconButton bg="red.500" _dark={{ bg: "red.600" }} icon={<p>A</p>} />
```

**Comment by voyagebagage** [comment]
**THanks**

**Comment by voyagebagage** [comment]
in Button it is fine but somehow in `IconButton` it doesn't work:

```jsx
 baseStyle: (
    props,
    myColor2 = customTheme?.semanticTokens?.colors?.primary?._dark
  ) => {
    const oppositeColor = props.oppositeColor;
    return {
      //   light: {

      bg: oppositeColor ? myColor2 : "red",
      _hover: { bg: "primary" },
      //   },

      _dark: { _hover: { bg: "primary" } },
    };
  },
  
  ```
  
  if I add `oppositeColor` to  `IconButton`  the bg isn't  white anymore but if I don't the color is back to white and not red

**Comment by voyagebagage** [comment]
How to choose the default color for  a color,bg of a component`IconButton  bg="olive" _dark={{ bg: "default ??" }}`
