### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by lishine** [chakra-ui/chakra-ui#639]
I am seeking for an admin theme that my manager will like. I want to use chackra but the thing is I don't find any themes to use or to buy.
My manager don't like the default chackra theme. He looking at some templates online. Should I take a CSS template and modify chackra theme to look like that? There are many themes for react-material-ui.
What should I do?

**Comment by jaeyholic** [comment]
you can hire someone to develop one for you or you can do it yourself if you're good with chakra-UI

**Comment by lishine** [comment]
Thanks for reply 😊
I am in a "business" of diy 😋
I had a harsh talk with my manager-client-my-brother. He is a developer my everything regarding CSS has misunderstanding.
He shows me a demo page of some dashboard UI components. And he says, it is a template, it shows you exactly how I want you to do it - pixel perfect lol.
I explain to him that these are just components, part of a design system. I tell him to look a the chackra-ui website, look at the components, I say.
Here he getting mad, he want to see some demo. So my problem is that there is no demo page and in this case dashboard demo...

**Comment by segunadebayo** [comment]
Hi @lishine,

We intend to look into themes after the next major release.

For now, I can recommend that you check for a premium dashboard UI kit, which may be designed in Sketch or Figma, and show it to your manager if he like it.

Once you get his approval, then you can try to recreate the UI kit using Chakra.

You can also consider checking Tailwind UI's dashboard components and try to use Chakra's components to make them.

Hope this helps?
