### ISSUE TITLE
How to use a custom frame for your picture using custom Icons

### ISSUE THREAD

**Issue by voyagebagage** [chakra-ui/chakra-ui#6390]
### Description

I would like not to have only square and circle shape "picture box", mixed issue with Next.js

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-javascript-lzzg9

### Steps to reproduce

I actually don't know if it is possible within next or simply Chakra-ui to insert an image inside an Icon ?
or should I just use photoshop and import the image like that, I have tried to play with zIndex, the box , Icon and the Image but no luck
here it is just a random example of a triangle custom icon

```js
import Image from "next/image";

const ChakraNextImage = (props) => {
    const { src, alt, ...rest } = props;
    return (
      <Box position="relative" {...rest}>
        <Image objectFit="cover" layout="fill" src={Pic} alt={alt} />
      </Box>
    );
  };
  
<Icon viewBox="0 0 24 24" boxSize="lg" position="relative"> //or the 'as' prop within the Icon
            {/* <ChakraNextImage boxSize="lg" /> */}
            <path
              as={ChakraNextImage}
              fill="currentColor"
              d="m2.095 19.882 9.248-16.5a.753.753 0 0 1 1.313 0l9.248 16.5a.75.75 0 0 1-.656 1.116H2.752a.75.75 0 0 1-.657-1.116z"
            />
          </Icon>
```

### Chakra UI Version

    "@chakra-ui/react": "^1.8.3",

### Browser

brave v1.40

### Operating System

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hey. This is not possible within Chakra or React by default.

You should look into SVG Foreign objects:
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject
