### ISSUE TITLE
Error: Cannot find module '@chakra-ui/core'

### ISSUE THREAD

**Issue by glockjt** [chakra-ui/chakra-ui#64]
I'm getting this error after adding it to my `next.js` project.  I have a component in typescript `Layout.tsx` in which I import as follows:

```javascript
import { ThemeProvider, Flex, Box } from "@chakra-ui/core";
```

resulting in the following error

```bash
Error: Cannot find module '@chakra-ui/core'
```

I also installed running the following command:

```bash
yarn add @chakra-ui/core @emotion/core @emotion/styled emotion-theming
```

**Comment by segunadebayo** [comment]
Hi @glockjt ,

Kindly put this on Codesandbox and send me a link so I can take a look.

**Comment by glockjt** [comment]
@segunadebayo Thanks for the fast response.  It seems like codesandbox doesn't work with `next.js` typescript.

**Comment by segunadebayo** [comment]
Ah. I'm not sure how I can help in this case.

I haven't tried Chakra UI on a Next Typescript project but it works fine with create-react-app Typescript. I really hope you can get the code on a link so I can take a look.

I'll create a Next TS project soon and try to resolve this issue.

**Comment by vueu** [comment]
I was getting this error too with the exact same environment (Next.js with TypeScript).

What fixed it for me was removing and reinstalling the package.

**Comment by fedirlutsenko** [comment]
Use import { extendTheme } from "@chakra-ui/react" instead.
@chakra-ui/core is no longer supported.
