### ISSUE TITLE
[TagCloseButton] Doesn't expose type property on button

### ISSUE THREAD

**Issue by SDrinkwater** [chakra-ui/chakra-ui#640]
**Describe the bug**
The `TagCloseButton` doesn't expose the button's type property. You can technically use it, but TypeScript complains that it can't find the property.
I also think the default type for this button should be `button`. Without it, the button defaults to `type="submit"` behaviour which causes issues if used inside of a form, i.e., the close button will be pressed when hitting enter if the button is placed before the submit button.

**Expected Behavior**
`TagCloseButton` should expose the button type property and take on a default value of `type="button"`.

**Suggested solution(s)**
This can be worked around by explicitly setting the button type. In TS environments, `//@ts-ignore` can be used to ignore the error.

**Comment by with-heart** [comment]
We aren't doing any more work on the pre-1.0 codebase in preparation for the 1.0 release. `type` is now a valid property for buttons, but I did notice that in 1.0 we still don't default `type` to `button`, so I've opened #958 to resolve that issue.
