### ISSUE TITLE
add a new prop to control changing case behavior in the badge component

### ISSUE THREAD

**Issue by kr-anurag** [chakra-ui/chakra-ui#6403]
### Description

https://chakra-ui.com/docs/components/badge

Now the Badge component automatically changes the case of its value to be uppercase. Sometimes it's unnecessary and unwanted.

So my proposal is a prop to control this behavior.

### Problem Statement/Justification

While using the Badge component, the change in case is unwanted and unnecessary at times.

### Proposed Solution or API

Something like this could be really nice:

https://ui.supabase.io/components/badge

**Comment by itkrt2y** [comment]
You can change case with `textTransform`.

```tsx
<Badge textTransform="lowercase">sample</Badge>
```

**Comment by olavoparno** [comment]
> You can change case with `textTransform`.
> 
> ```tsx
> <Badge textTransform="lowercase">sample</Badge>
> ```

I've set it to `<Badge textTransform="none">sample</Badge>` so that it is set on the badge level.
