### ISSUE TITLE
Dependencies broken after `yarn remove @chakra-ui/react` and `yarn add @chakra-ui/react`

### ISSUE THREAD

**Issue by dgrcode** [chakra-ui/chakra-ui#6404]
### Description

When removing and reinstalling the dependency, I expected everything to work, but I get an error

### Link to Reproduction

https://codesandbox.io/s/hydration-error-example-85yns3?file=/pages/index.tsx

### Steps to reproduce

1. the project doesn't load after I removed and reinstalled @chakra-ui/react.
2. I'm not sure if this will reproduce because it'll depend on how codesandbox recreates the projects.

### Chakra UI Version

2.2.4

### Browser

Brave Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (x86_64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The error I'm getting is `Error: Cannot find module '@chakra-ui/anatomy'`. But I can see the module inside my node_modules. Reinstalling the module doesn't change anything.

The error I see on codesandbox is different.

I'm not sure what's going on, but I honestly doubt this is a Chakra issue, or at least, a Chakra issue _only_. Asking here because the complain is about a module from chakra, and hopefully someone has seen this before.

**Comment by TheTedAdams** [comment]
Dupe of #6372 and #6376

Basically anyone using yarn 2/3/berry has had massive pain if they updated their lock file in the last week.

**Comment by dgrcode** [comment]
It seems I got it working after nuking node_modules and yarn.lock a couple of times. Maybe I missed something the first time.

Thanks for the links to the other issues! They didn't come up on my searches before opening this issue. Yarn is definitely doing something I don't understand.
