### ISSUE TITLE
`<Progress>` should use `transform: scaleX` instead of width for animations and GPU acceleration

### ISSUE THREAD

**Issue by rbozan** [chakra-ui/chakra-ui#6409]
### Description

It'd be nice if <Progress> would use the following:

```css
width: 100%;
transform: scaleX(0.5);
```

instead of
```css
width: 50%
```

Now it always modifies the `width`. Why not modify the scale for GPU acceleration and animations?

If it won't be standard (because of for example, round progress bars), it'd be nice if we can at least request such a way of defining the progress bar, as a square progress bar would only benefit from it.

### Problem Statement/Justification

- There does not seem to be a good way to have a Progress bar with `transform: scaleX` instead of width. For example, the following:

```
        <Progress value={1} transform={`scaleX(${percentageFinished})`} max={1} size="xs" />
```

would scale the FULL progress bar, not just the inner progress.

### Proposed Solution or API

-

**Comment by segunadebayo** [comment]
Hey @rbozan,

Thanks for the detailed report and suggestion. We tried this earlier in development, and it didn't play nicely with the stripe and indeterminate variants.

For now, let's keep it as is. In the future, I'll reconsider this.

**Comment by rbozan** [comment]
> Hey @rbozan,
> 
> Thanks for the detailed report and suggestion. We tried this earlier in development, and it didn't play nicely with the stripe and indeterminate variants.
> 
> For now, let's keep it as is. In the future, I'll reconsider this.

Hi @segunadebayo 

I think it's ok to that you made this decision as indeed some things could break, however there does not seem to be a way to easily customise the inner progress bar which forces me to make my own Progess component. Is there a way to style the inner progress in some way so I can still keep using the Chakra UI component?
