### ISSUE TITLE
Having to override support statement in modal.tsx

### ISSUE THREAD

**Issue by prbxr** [chakra-ui/chakra-ui#6413]
### Description

I don't know how to improve on it.

### Problem Statement/Justification

In my theme I try to set **height** on a Modal's dialogContainer part, like this

```ts
const sizes: Record<string, PartsStyleFunction<typeof parts>> = {
	pdp: (props) => {
		return {
			dialogContainer: { height: '200px' },
		}
	},
}
```

But it does not work, instead  I have to do this:

```ts
const sizes: Record<string, PartsStyleFunction<typeof parts>> = {
	pdp: (props) => {
		return {
			dialogContainer: {
				'@supports(height: -webkit-fill-available)': {
					height: '200px',
				},
				height: '200px',
			},
		}
	},
}
```

### Proposed Solution or API

The reason is this code

```ts
    const dialogContainerStyles: SystemStyleObject = {
      display: "flex",
      width: "100vw",
      height: "100vh",
      "@supports(height: -webkit-fill-available)": {
        height: "-webkit-fill-available",
      },
      position: "fixed",
      left: 0,
      top: 0,
      ...styles.dialogContainer,
    }
```

from
https://github.com/chakra-ui/chakra-ui/blob/1839e22ebad1c2a52795eac5fd0b3eb38ae03f9c/packages/modal/src/modal.tsx

**Comment by segunadebayo** [comment]
Hi @prbxr,

This has been fixed in a recent PR by leveraging CSS variables. I'll publish an update shortly.

If after the upgrade, the problem still exists in your application, I'll re-open this.
