### ISSUE TITLE
Custom scrollbars in MenuList

### ISSUE THREAD

**Issue by devdreamsolution** [chakra-ui/chakra-ui#6416]
### Description

I wanna implement custom scrollbar in MenuList

### Link to Reproduction

This doesn't have codesandbox

### Steps to reproduce

I used this react custom scrollbar package.
https://www.npmjs.com/package/react-custom-scrollbars
But the MenuList doesn't work.
This screenshot is the result.
![image](https://user-images.githubusercontent.com/54434088/182734040-86a44c13-9011-4d24-9e69-a5a748de5852.png)

This is my code.
```ts
<MenuList
    borderRadius="10px"
>
    <Scrollbars style={{ height: 300, position: "absolute" }}>
        {children}
    </Scrollbars>
</MenuList>
```

### Chakra UI Version

2.2.1

### Browser

Google chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Please follow the issue template as we cannot act on issues that don't have reproductions.
