### ISSUE TITLE
"Black" colours appear to not work on buttons.

### ISSUE THREAD

**Issue by SmolAlli** [chakra-ui/chakra-ui#6418]
### Description

When I create a button and set the colour to black, it does not set it properly

### Link to Reproduction

https://codesandbox.io/s/nice-bell-vjb2e1

### Steps to reproduce

1. Create a button with the `colorScheme="black"` property.
2. Look at the CSS
3. Colours have not been set properly.

Images showing below code and result.
![image](https://user-images.githubusercontent.com/22519967/182776488-4dac8ba7-d15f-4f68-a251-17b65b3af0b3.png)
![image](https://user-images.githubusercontent.com/22519967/182776522-f44eef3e-33ac-42e9-8cb8-24583905ca78.png)

Expected result (using green as an example)
![image](https://user-images.githubusercontent.com/22519967/182776637-260ca5cd-9244-44f2-994a-a8bc1b286d06.png)
![image](https://user-images.githubusercontent.com/22519967/182776675-c1fe2042-06a7-4663-9b55-a20e66d903c2.png)

### Chakra UI Version

2.2.4 React

### Browser

Firefox 103, Chrome 103

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I have tested it with and without the `ghost` property that's shown in the screenshots, and they both show similar/the same issue.

**Comment by segunadebayo** [comment]
Hi @SmolAlli,

The black color is not a scale of colors. To use `colorScheme`, you need to provide a scale of (50-900) values for that color. In this case, the black color is just a single color.

I believe your goal is to make the background color of the button black, to achieve that, set the `bg='black'` or provide a black color scale.
