### ISSUE TITLE
Ability to change Wrap's ul element like with "as"

### ISSUE THREAD

**Issue by delanebob** [chakra-ui/chakra-ui#6426]
### Description

When using the `<Wrap />` component there is no way to change the `ul` element it uses within the component. When you give it an `as="div"` prop, it gets assigned to the parent container of the component like so:

```jsx
<Wrap as="div">
  <WrapItem>
    ...
  </WrapItem>
</Wrap>
```

### Problem Statement/Justification

The main problem with this, is that it makes the component semantically stuck to being a `ul` and can't be used in areas that you would like to have a similar layout effect to `<Wrap />` but not have it to be a `ul`.

### Description list:

```jsx
<Wrap as="dl">
  <WrapItem as="div">
    <Heading as="dt">
      Label
    </Heading>
    <Text as="dd">
      Description
    </Text>
  </WrapItem>
</Wrap>
```

### Laying out component:

```jsx
<Wrap as="div">
  <WrapItem as="div">
    <Heading>
      Label
    </Heading>
  </WrapItem>
  <WrapItem as="div">
    <Button>
      Action
    </Button>
  </WrapItem>
</Wrap>
```

### Proposed Solution or API

The 2 possible solutions I can think of are:
- Provide another prop to change the `ul` as.
- Assign the `as` to the `ul` as the div container doesn't have a semantic meaning.

### Alternatives

The alternative is to recreate this component in our app, but with the requires that we see beneficial. But I think this component is great and would get better use from the component if we made it more flexible.

**Comment by segunadebayo** [comment]
Hi @delanebob,

I think a <Flex> component with `gap` and `flexWrap` set would help you achieve the results you want without a change to the Wrap component in Chakra. This component will most likely be upgraded to use that approach in the future.
