### ISSUE TITLE
Missing dependency for `@chakra-ui/cli`

### ISSUE THREAD

**Issue by Belco90** [chakra-ui/chakra-ui#6427]
### Description

When I use pnpm as my package manager, and I run the `chakra-cli tokens` command, I get an error about styled-system can't be found in node_modules

### Link to Reproduction

https://github.com/Belco90/personal-website/pull/38

### Steps to reproduce

The provided repro link is actually fixed. You can reproduce it by

1. Uninstalling `@chakra-ui/styled-system` from dev dependencies
2. Running `pnpm gen:theme-typings`

You can run into the same issue in any repo using Chakra UI by:

1. Switching the package manager to pnpm
2. Setting up Chakra CLI to generate custom tokens
3. Running the command to generate custom tokens

### Chakra UI Version

2.2.6

### Browser

n/a

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This is the error in the terminal:
![chakra-pnpm](https://user-images.githubusercontent.com/2677072/183116730-f11d8a6a-0456-4fbc-a6dd-3f74dee9ddd3.png)

This seems a phantom dependency to me. Since pnpm manages the dependencies in a non-flat node_modules, code has no access to arbitrary packages. The default output for `@chakra-ui/cli` token command is `@chakra-ui/styled-system`, which is not explicitly set as dependency of `@chakra-ui/cli`. This works fine with npm since all packages are hoisted in the node_modules, so `@chakra-ui/styled-system` is found implicitly installed by other package (not sure which one, but probably another chakra package).

I think just adding `@chakra-ui/styled-system` as a dependency of `@chakra-ui/cli` would fix this issue. As a workaround, I had to explicitly install `@chakra-ui/styled-system` in the dev dependencies of my repo.

**Comment by eli-s-r** [comment]
@Belco90 Explicitly installing `@chakra-ui/styled-system` resolves the issue for me. Thanks for the suggestion!

**Comment by segunadebayo** [comment]
Thanks for the detailed report and suggestions.

Unfortunately, this is something we can't fix on our end.

To fix this, you can either:
- Install the styled-system package
- Specify the `--out` parameter, create a `d.ts` and use declaration merging

```ts
import { BaseThemeTypings } from "@chakra-ui/styled-system";
import { Tokens } from "../path/to/d.ts"
  
declare module "@chakra-ui/styled-system" {
    export interface CustomThemeTypings extends BaseThemeTypings, Tokens { }
}
```

**Comment by Belco90** [comment]
Thanks for the suggestions @segunadebayo. I ended up installing the styled-system package.

Since installing it fixed the issue and this happens with pnpm but not npm, I believed this was a phantom dependency that could be fixed by adding the styled-system package as dependency of the CLI one.

Perhaps a clarification through the CLI or Chakra's docs would be great too.

**Comment by marekopatril** [comment]
I had same issues with pnpm - wrapping up Chakra components into mine (when importing props). Only solution was to switch `shamefully-hoist=true` in .npmrc 
It will make same structure in node_modules like yarn or npm
