### ISSUE TITLE
Keyboard shortcuts for buttons

### ISSUE THREAD

**Issue by AnishDe12020** [chakra-ui/chakra-ui#6431]
### Description

I have seen many apps do this - a keyboard shortcut that triggers the action linked to a button

Example - There is a save button triggered on pressing ctrl + enter

### Problem Statement/Justification

Although it is possible to listen for keypresses and trigger a function with some code, it can get repetitive and, as of now, there is proper integration with a chakra button (for example, showing the keyboard shortcut in the button/tooltip of the button)

### Proposed Solution or API

An optional prop (something like `keyboardShortcut`) that can be passed to a button.

The component will listen for the keybinding to be pressed and will trigger the `onCliclk` handler.

There can also be an option to show the keyboard shortcut in the button/in the button's tooltip

### Alternatives

It could also be a separate component like `ButtonWithKeyboardShortcut` or something like that in case the goal is to keep the vanilla `Button` component simple

### Additional Information

Possible use of - 
- `useEventListener` hook (https://github.com/chakra-ui/chakra-ui/blob/main/packages/hooks/src/use-event-listener.ts)
- `Kbd` component (https://chakra-ui.com/docs/components/kbd/usage)

Inspiration:
Linear - 
![image](https://user-images.githubusercontent.com/63192115/183240980-5cffeef6-08da-4fd3-b857-a897b274c3af.png)
![image](https://user-images.githubusercontent.com/63192115/183241000-59e16d8b-c54e-4e62-b643-80b8aa9b5b15.png)

Height (height.app) - 
![image](https://user-images.githubusercontent.com/63192115/183241010-54013c04-d3d5-4667-bfab-f39138ef81b0.png)

**Comment by segunadebayo** [comment]
Hey, this sounds like a user-land feature to me.

Consider implementing it within your app and sharing the code snippets here for those interested.

Thanks

**Comment by userFortyTwo** [comment]
A user land feature? I don't think so. It is very common for a UI framework to provide a way to assign a keyboard shortcut to a button, and, in fact, many UI frameworks can do exactly that.
