### ISSUE TITLE
React App Not Rendering

### ISSUE THREAD

**Issue by ajohnson1031** [chakra-ui/chakra-ui#6435]
### Description

After configuring Chakra-UI, when I run the app, my <App /> component does not display.

### Link to Reproduction

https://codesandbox.io/s/laughing-kapitsa-8mfgsk

### Steps to reproduce

1. CRA new react app.
2. Install chakra-ui dependencies
3. Configure chakra-ui provider and colormode
4. Create new components folder and new component
5. Render and run

### Chakra UI Version

2.2.6

### Browser

Brave Version 1.41.96 Chromium: 103.0.5060.114 (Official Build) (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Link to code: https://github.com/ajohnson1031/whatsapp-clone-chakra-ui

**Comment by mohammadizanloo55** [comment]
Hi, you need to configure your **index.js** file as follows:
```
<React.StrictMode>
    <ColorModeScript initialColorMode={theme.config.initialColorMode} />
    <ChakraProvider theme={theme}>
      <App />
    </ChakraProvider>
  </React.StrictMode>

```

**Comment by ajohnson1031** [comment]
@mohammadizanloo55 - Thanks! Fixed my problem! Call this one `closed`!

**Comment by RISHVANDHINI** [comment]
Still my react web is not loading though Chakra-UI installation was done perfectly
