### ISSUE TITLE
ProTheme error - Named export 'theme' not found. 

### ISSUE THREAD

**Issue by tecoad** [chakra-ui/chakra-ui#6436]
### Description

When I import the pro-theme into my custom theme using extendTheme, I get this Named export 'theme' not found.

### Link to Reproduction

https://github.com/tecoad/my-app

### Steps to reproduce

1. Clone and try to build the following repo: https://github.com/tecoad/my-app
2. The following error would display:

```
Server Error
SyntaxError: Named export 'theme' not found. The requested module '@chakra-ui/react' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@chakra-ui/react';
const { extendTheme, theme: theme$1 } = pkg;

This error happened while generating the page. Any console logs will be displayed in the terminal window.

```

### Chakra UI Version

2.2.6

### Browser

Version 103.0.5060.134 (Official Build) (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

<img width="1053" alt="Screen Shot 2022-08-07 at 11 55 58" src="https://user-images.githubusercontent.com/2627749/183297113-bf69a9ff-1941-47c6-9499-2956ebabf81d.png">

**Comment by Pagebakers** [comment]
My suspicion is that this is because Chakra doesn't use .mjs file extension for the module files and imports from other .mjs based packages fail to resolve the Chakra UI esm modules.

More info: https://github.com/vercel/next.js/issues/30750

**Comment by segunadebayo** [comment]
We've had too many problems with `.mjs` files recently, and we've decided to stick with the current structure for now.

@tecoad, I recommend downloading the theme locally and extracting it to your project. We'll consider switching the pro themes to match the format for Chakra UI for now

**Comment by Destroyer369** [comment]
Maybe you forget to run

npx @chakra-ui/cli snippet add

It will installed required dependencies and add recommended snippets, It will also create provider.tsx in you src/components/ui.

Here is link to read more https://www.chakra-ui.com/docs/get-started/frameworks/vite#add-snippets
