### ISSUE TITLE
Prop definition of as-type not overwriting those of the component they are applied on → TypeScript Error

### ISSUE THREAD

**Issue by Philzen** [chakra-ui/chakra-ui#6439]
### Description

When using the `as`-prop, i expect the props of the `as`-type to become available as they are defined in that type.  
This works fine for props that do not exist on the component that `as` is used on.
However, if the prop exists on both types, TypeScript still refers to the wrong definition, although, when compiled and run, functionally the implementation from the `as`-component applies (and actually works).

### Link to Reproduction

https://codesandbox.io/s/competent-dubinsky-n0wymw?file=/src/index.tsx:729-761

### Steps to reproduce

1. Take any chakra component for instance `<Box>` or `<chakra.div>`
2. Apply the `as`-prop, referring to a component that contains a prop which is named identical to the component you chose in step 1., but has a different type – it does not matter if it's type is fundamentally different (such as string vs. number) or if it simply has a broader type (such as allowing more options).
3. Apply the prop and choose a value that is valid for the definition of the element chosen in 2., but does not comply with the type of the component you chose in 1.

### Chakra UI Version

1.8.8 (discovered) | 2.2.6 (still there in live example)

### Additional Information

This issue was discovered when trying to apply some nice Chakra-styling functionality to the RedwoodJS `<Form>`-component, which is why i initially opened the issue over here: https://github.com/redwoodjs/redwood/issues/5956 – i created the aforementioned [codesandbox](https://codesandbox.io/s/competent-dubinsky-n0wymw?file=/src/index.tsx:729-761) for that, where the typescript warning is generated in line 41 as

```sh
(JSX attribute) onSubmit?: React.FormEventHandler<HTMLFormElement>

Type '(input: { message: string; }, e: any) => void' is not assignable to type 'FormEventHandler<HTMLFormElement>'.ts(2322)
index.d.ts(1410, 9): The expected type comes from property 'onSubmit' which is declared here on type 'IntrinsicAttributes & OmitCommonProps<DetailedHTMLProps<FormHTMLAttributes<HTMLFormElement>, HTMLFormElement>, keyof ChakraProps> & ChakraProps & OmitCommonProps<...> & { ...; }'
```

The `onSubmit`-prop actually *does have* has a different signature for `<Form>`s – which is why the code works as intended, but TypeScript simply doesn't get it. :shrug: 

After some investigation we came to the consensus that this can only be solved on the ChakraUI side. 

---

I made some additional tests along with examples in the codesandbox to demonstrate that this is not RedwoodJS-specific indeed. Here is another example, again using a non-chakra enabled property (it comes from `@types/react`):

https://codesandbox.io/s/competent-dubinsky-n0wymw?file=/src/other-example.tsx:493-553

Similar result: 

```sh
(JSX attribute) tabIndex?: number

Type 'string' is not assignable to type 'number'.ts(2322)
index.d.ts(1865, 9): The expected type comes from property 'tabIndex' which is declared here on type 'IntrinsicAttributes & OmitCommonProps<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, keyof ChakraProps> & ChakraProps & OmitCommonProps<...> & { ...; }'
```

---

The final test was to see if this also applies to ChakraUI system-enabled props (which live in `@chakra-ui/system`) … and indeed it does:

https://codesandbox.io/s/competent-dubinsky-n0wymw?file=/src/another-example.tsx:656-728

```sh
(JSX attribute) PositionProps.position?: ResponsiveValue<Property.Position>

Type '"allovertheplace"' is not assignable to type 'ResponsiveValue<Position>'.ts(2322)
index.d.ts(1272, 5): The expected type comes from property 'position' which is declared here on type 'IntrinsicAttributes & OmitCommonProps<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, keyof ChakraProps> & ChakraProps & OmitCommonProps<...> & { ...; }'
```

Note that the last two examples are no real-world applications and probably don't make a lot of sense, i just made them up to demostrate the TypeScript issue. They do not show a TypeScript issue when used directly with their custom values – or with compatible value that is valid on both components.

--- 

My hunch is that this comes down to something in https://github.com/chakra-ui/chakra-ui/blob/ff0dfb2b735a047c7a811f65b20fb81fa3db6f4a/packages/system/src/system.types.tsx#L75-L76

… and above – that's the place where the solution lies i guess. Unfortunately this stuff is completely over my head, i only understand that (as the issue title states) the prop-definition from the as-component should always overwrite an existing one, which it currently doesn't.

**Comment by Schmell** [comment]
Same problem here and also with the size prop as typescript will use ` preact/src/jsx.d.ts ` as typedef instead of the chakra typedefs
I also find it odd that this only showed up when i switched to using Vite instead of preactCLI.
Maybe this is a Vite problem??

**Comment by omar-bear** [comment]
did you try to apply this ? 

https://chakra-ui.com/community/recipes/as-prop#option-1-using-forwardref-from-chakra-uireact
```tsx
import { forwardRef, Box, BoxProps } from '@chakra-ui/react'

const Card = forwardRef<BoxProps, 'div'>((props, ref) => (
  <Box px='4' py='5' rounded='sm' shadow='lg' ref={ref} {...props} />
))
```
make sure for the place of your basic type

**Comment by matthewrose** [comment]
I run into this all the time when using `Button` `as` `Link`. i.e. spreading a `LinkProps` object into a `Button` as props.

Example:
```
<Button as={Link} {...linkProps} />
```

I've needed to define a new, merged type most of the time.

**Comment by KryziK** [comment]
I have a similar issue. I am using @chakra-ui/react's Link, and react-router-dom's NavLink.

However, 

```js
import { Link } from "@chakra-ui/react";
import { NavLink } from "react-router-dom";
// ...
<Link as={NavLink} className={({ isActive }) => isActive ? "yes" : undefined}>My Link</Link>
```

does not work, because

`Type '({ isActive }: { isActive: any; }) => string' is not assignable to type 'string'.ts(2322)`

No matter what I try, it's not liking the NavLink and NavLinkProps from react-router-dom.

**Comment by segunadebayo** [comment]
cc: @TimKolberger Could you help look into this.

**Comment by lucasruy** [comment]
Do we have any updates on this issue?

**Comment by TimKolberger** [comment]
I forgot to update this issue. I experimented in the polymorphic repo, which is basically the extraction of the chakra as prop typings (chakra has still a similar implementation), to support the mentioned behavior and I could not get it to work correctly or to have a viable performance.

See https://github.com/chakra-ui/polymorphic/pull/138

The as prop typings are quite fragile and very complex. I stopped working on this to not get frustrated 😅

Feel free to open a PR ✨ every help is appreciated!

**Comment by segunadebayo** [comment]
This is currently in the "can't fix" due to the complexity involved in getting this right.

In future versions, we'll consider adding an `asChild` prop to allow you to forward props to a child element using `cloneElement`.

For now, I'll close this.

I know it's a bummer, but we don't have the capacity to fix this **without a breaking change**. Getting the typings for events is the current limitation of the types we have.
