### ISSUE TITLE
[Button] using a color without shades throws a warning

### ISSUE THREAD

**Issue by tafelito** [chakra-ui/chakra-ui#644]
**Describe the bug**

The Button has a check here to validate the variant color, but is not considering a color like white or black or any plain colors that has no shades 

https://github.com/chakra-ui/chakra-ui/blob/67c0243a4becd2c2509934d59e52b4a25ff199ab/packages/chakra-ui/src/utils/index.js#L168

Also if you do send a color like blue.500 then the check also warns because the color is not part of the theme

**Expected Behavior**
It shouldn't warn in case of an existing color with or without shades

**Comment by with-heart** [comment]
Hi @tafelito, I'm going to close this in preparation for 1.0. We can revisit it after the release if still needed!

**Comment by bel0v** [comment]
I'm having the same issue, passing "white" as `variantColor` produces a warning.

**Comment by trompx** [comment]
Same here. The problem is that I'd like a black button but not with #000 but with #0c0c0c.
The problem is that the button automatically selects customBlack.500 so if I want my button to have the #0c0c0c color, I need to set the 500 value to that, and no palette generator make it easy to generate those kind of values.
Is there another way to have a black/white button or overriding the button styles like mentionned here https://next.chakra-ui.com/docs/theming/component-style is the way to go? In that case, it seems to set in hard the color. Will it still be overriden if I pass a colorScheme in the button props?

**Comment by with-heart** [comment]
@trompx You could do it a few different ways. A `variant` on `Button` might be easiest. Depending on how you create it, it could ignore `colorScheme`, as seen here: https://codesandbox.io/s/weathered-firefly-5l0v1?file=/src/App.tsx

The problem with not using a color scale is that you don't get any of the usual hover/active/etc. states automatically, so you'd have to set that up yourself.

**Comment by trompx** [comment]
Super interesting @with-heart, thanks! That was the missing part from the docs. I didn't know if I could pass the colorScheme in the variant, so I hardcoded multiple variants for my brand colors.
Now I can do it with:
```
variants: {
    solid: ({ colorMode, colorScheme }: any) => ({
      bg: colorScheme + ".500",
      color: colorMode === "dark" ? "black" : "white",
      _hover: { bg: colorScheme + ".700" },
    }),
...
```

**Comment by cyberwombat** [comment]
I made a little helper to help generate these palettes using 500 as the baseline.
```
import tinycolor from 'tinycolor2'

const generatePalette = (color: string, inc: number = 0.5) => {
  const c = tinycolor(color)
  return {
    50: c.darken(inc * 5).toString(),
    100: c.darken(inc * 4).toString(),
    200: c.darken(inc * 3).toString(),
    300: c.darken(inc * 2).toString(),
    400: c.darken(inc).toString(),
    500: color,
    600: c.lighten(inc).toString(),
    700: c.lighten(inc * 2).toString(),
    800: c.lighten(inc * 3).toString(),
    900: c.lighten(inc * 4).toString()
  }
}
```
