### ISSUE TITLE
VSCode autocomplete for theme props not working

### ISSUE THREAD

**Issue by JRebella** [chakra-ui/chakra-ui#6440]
### Description

When filling in theme related props like bg color I expected intellisense suggestions with theme tokens but none are showing up

### Workaround

Use exact version of chakra `2.2.0`. Thanks [system32uwu](https://github.com/system32uwu)

### Link to Reproduction

https://codesandbox.io/s/purple-water-b30s3k?file=/src/index.tsx

### Steps to reproduce

1. Create a simple `<Box />` component
2. Add a prop that uses theme tokens, for example`bg`
3. CTRL+Space to have the intellisense suggestions pop up
4. Note that no suggestions are shown with theme tokens like `red.100`, `red.200`, etc

![image](https://user-images.githubusercontent.com/47323512/183311285-67d08178-eba6-47de-b6f9-27218191c88b.png)

### Chakra UI Version

2.2.6

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

First tested in next,js using pnpm, then CRA using npm and the chakra template, then codesandbox using the chakra template. Same result everytime

I'm not 100% sure this is a supported feature, most I could find in the [docs is the following which makes me believe autocomplete suggestions are supported](https://chakra-ui.com/docs/styled-system/advanced-theming#theme-typings):
![image](https://user-images.githubusercontent.com/47323512/183311367-1df751dc-c694-40d6-be41-8b04324e5d5a.png)

**Comment by system32uwu** [comment]
This was indeed supported, it stopped working for me as well using vite and pnpm, I'm trying to find the latest version where it was working, will update soon.

**Comment by giovannijoao** [comment]
I updated for the version 2.2.3 because of Highlight component and I started facing this problem.

**Comment by marsidev** [comment]
Same here. I downgraded it to 2.2.4 and it works fine.

**Comment by robcrockhlx** [comment]
I thought this wasn't working, but then I reloaded VS Code and all was right again in the world 🙌

**Comment by hkvongit** [comment]
Always make sure Project Wide Intellisense is enabled in the VS Code setting:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/45459914/227188900-8f52fad9-09b1-4243-bf1f-80b3c4009080.png">

**Comment by devsahadat** [comment]
![image](https://github.com/chakra-ui/chakra-ui/assets/95290111/c0813cc2-b9d0-44c5-b969-a6579db988de)
Enabling this setting worked for me. Have fun ❤️

**Comment by Zain-ul-din** [comment]
Still not working for me I'm using `react-vite`  app chakra at version `^2.8.2` any idea how to make intellisense work?
