### ISSUE TITLE
Mobile Chrome password manager bar above keyboard on Editable input focus

### ISSUE THREAD

**Issue by xvvvyz** [chakra-ui/chakra-ui#6445]
### Description

Google Chrome on Android adds password manager bar above the keyboard when Editable inputs are focused. I'd expect for this to happen for password inputs, but not for all inputs.

### Link to Reproduction

https://chakra-ui.com/docs/components/editable

### Steps to reproduce

1. Go to https://chakra-ui.com/docs/components/editable on mobile Google Chrome
2. Tap on the first Editable input

### Chakra UI Version

2.2.3

### Browser

Chrome 103.0.5060.129

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [x] Android 12

### Additional Information

![screenshot](https://user-images.githubusercontent.com/2367158/183539335-a31b4fae-27d9-4779-83b6-cb46d8686969.png)

**Comment by segunadebayo** [comment]
Hey @xvvvyz,

The editable input is just a plain input element. We don't do anything extra for this use case. 

Feel free to add extra attributes to the EditableInput component if you want to turn off this behavior. Set `autoComplete=off`

**Comment by xvvvyz** [comment]
Upon further investigation, for anyone who stumbles upon this, it seems to be a Chrome issue. Some recently created StackOverflow threads:

- https://stackoverflow.com/questions/73223498/how-to-hide-the-manage-password-bar-above-the-keyboard-for-non-password-textboxe
- https://stackoverflow.com/questions/73160690/what-is-making-the-password-autofill-bar-show-above-the-keyboard-in-android-chro/73317858

`autoComplete=off` does NOT have any effect, unfortunately. Will continue investigating...
