### ISSUE TITLE
Transition duration props to Accordion

### ISSUE THREAD

**Issue by mihaichiciu** [chakra-ui/chakra-ui#6449]
### Description

I know that the `Collapse` component is able to receive `transition` as a prop and change the enter and exit animation duration, but I am not able to do that on the `AccordionPanel` component, which is using `Collapse` under the hood.

### Problem Statement/Justification

This will allow us to change the transition speed with which an `Accordion` is opened and closed

### Proposed Solution or API

I would like to be able to pass `transition` as a prop to the at least one of the `AccordionPanel/AccordionItem/Accordion` components and be able to change the speed of showing the Accordion.

**Comment by bosworthco** [comment]
Relates to #6189
