### ISSUE TITLE
Request to add a closeAll() method from useToast()

### ISSUE THREAD

**Issue by yuyao17** [chakra-ui/chakra-ui#645]
**Is your feature request related to a problem? Please describe.**

There are times when I want to programmatically remove toast notifications (e.g. when someone navigates to a different route, remove all existing toast notifications from screen), and it currently seems like theres no way to do so.

**Describe the solution you'd like**

I'd like to return `toast.closeAll()` function from `useToast()`

e.g.

```js
const { closeAll } = useToast()

return (
 <button onClick={() => closeAll()}>Close all toast notifications</button>
)
```

I think this is relatively easy to do, just export `toaster.closeAll()` with `notify`

**Comment by segunadebayo** [comment]
Hi @yuyao17,

I'm glad you have an idea for a possible solution. Feel free to open a PR that fixes that and I'll take a look.

Thanks for this.

**Comment by with-heart** [comment]
Hi @yuyao17, as mentioned in your PR, this functionality has been added in 1.0. You can see migration docs for changes to Toast here: https://next.chakra-ui.com/docs/migration#toast
