### ISSUE TITLE
Disabled-state on `flushed` and `unstyled` inputs not recognizable

### ISSUE THREAD

**Issue by Philzen** [chakra-ui/chakra-ui#6453]
### Description

When i hover over a disabled input, i'd expect to see the `cursor: not-allowed` style being applied, or at least have any other visual feedback that the inputs are actually disabled.

Not sure if this is a bug or a feature :wink: – but it heavily confused me when i implemented a form whose components transform are disabled on submit.

### Link to Reproduction

https://chakra-ui.com/docs/components/input#changing-the-appearance-of-the-input

### Steps to reproduce

1. Go to the [docs page for the input component](https://chakra-ui.com/docs/components/input#changing-the-appearance-of-the-input)
2. Add `disabled` or `isDisabled` as a prop on any of the four variants and see how they change their appearance and hover styles. Alternatively, copy  
    ```tsx
    <Stack spacing={3}>
      <Input variant='outline' disabled placeholder='Outline' />
      <Input variant='filled'  disabled placeholder='Filled' />
      <Input variant='flushed' disabled placeholder='Flushed' />
      <Input variant='unstyled' disabled placeholder='Unstyled' />
    </Stack>
    ```
    into the live example box.
3. The `outline` and `filled` variants can clearly be recognized as being disabled, while `flushed` and `unstyled` still look the same.

### Chakra UI Version

1.8.8 (discovered) | 2.2.6 (still there in live example)

### Browser

All

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

On looking into the issue, it transpired that the `flushed` and `unstyled` variants actually don't have anything set for `_disabled` in the default theme. Only workaround is to set `_disabled` and `_hover` manually as props on the component, as afaik it's not possible to extend an existing variant without redefining / overwriting it.

**Comment by mohammadizanloo55** [comment]
I think this problem can be solved by adding this code : 
```js
_disabled: {
    opacity: 0.4,
    cursor: "not-allowed",
}
```
 to [this](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/input.ts#L175) part of the repository
just like other input variants

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
