### ISSUE TITLE
Request to add [Squircle-shaped] outline

### ISSUE THREAD

**Issue by coodoo** [chakra-ui/chakra-ui#646]
[Squircle](https://en.wikipedia.org/wiki/Squircle) is a shape between square and circle, often seen on iOS as app icons.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Superellipse_chamfered_square.svg/400px-Superellipse_chamfered_square.svg.png)

It would be nice to support this kind of shape as outline for `button` and `icon`, here's a [react implementation](https://github.com/caceres97/react-squircle).

**Comment by segunadebayo** [comment]
Hi @coodoo, 

Thanks for this idea! It looks good at a glance but I'm don't think it's something we'll like to add to the core of Chakra, perhaps we can leave this to the users and just show them examples.

You get what I mean? I'm happy you linked to the library as well so we'll consider showing this in the docs.

Thanks again.
