### ISSUE TITLE
Add a dynamic upgrade theme on select 'system' from OS

### ISSUE THREAD

**Issue by StKostyantin** [chakra-ui/chakra-ui#6469]
### Description

When the 'system' is selected in the theme, it selects the theme that stands on the OS at the moment. 
I propose to add dynamically pull the theme from OS if the user chooses 'system', even if it changes itself, depending on time.

### Problem Statement/Justification

A user can change the theme on the OS automatically depending on the day or night. And when the theme change in OS, the chakra will pull these changes to the site. 

### Proposed Solution or API

We can add a new state:
`const [osColorScheme, setOsColorScheme] = useState<'light' | 'dark'>(defaultTheme);`

And subscribe to these changes in ChakraProvider:
```
const mqlDark = window.matchMedia('(prefers-color-scheme: dark)');

useEffect(() => {
    mqlDark.addEventListener('change', e => {
      setOsColorScheme(e.matches ? 'dark' : 'light');
    });
  }, []);
```

### Additional Information

You can see an example of implementation
[Example](https://github.com/BarnBridge/barnbridge-frontend/blob/development/src/components/providers/generalProvider.tsx)

**Comment by RobinClowers** [comment]
I believe this is what `ColorModeScript` does? https://chakra-ui.com/docs/styled-system/color-mode#setup

**Comment by StKostyantin** [comment]
> I believe this is what `ColorModeScript` does? https://chakra-ui.com/docs/styled-system/color-mode#setup

No, it works only when the application is initialized. If the user theme changes  as often happens with macOS users (or he changes it himself) with the application open - the theme will not change.

**Comment by RobinClowers** [comment]
It works for me, do you have `useSystemColorMode` set to true?

**Comment by StKostyantin** [comment]
> It works for me, do you have `useSystemColorMode` set to true?

Maybe fixed in version 2, because the first one did not work, and then did not test, thanks)
