### ISSUE TITLE
Color flash with Remix SSR + Chakra 2.2.6

### ISSUE THREAD

**Issue by jca41** [chakra-ui/chakra-ui#6473]
### Description

There is a content/color flash (borders mainly) with Remix SSR after upgrading to Chakra 2.x.

### Link to Reproduction

https://stackblitz.com/edit/node-bgcy7f?file=package.json

### Steps to reproduce

Notice how the borders of the input and the stack divider flash from black to light grey.

### Chakra UI Version

2.2.6

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
The fix for this is to include the `ColorModeScript` in the `root.tsx`. This will ensure that the color mode value is set eagerly.

https://stackblitz.com/edit/node-znnwzk?file=app/root.tsx

**Comment by jca41** [comment]
Thank you!
