### ISSUE TITLE
type checking / intellisense not working

### ISSUE THREAD

**Issue by thatvegandev** [chakra-ui/chakra-ui#6479]
### Description

When I insert bad types, there are no complaints, and no intellisense (default theme)

### Link to Reproduction

https://codesandbox.io/s/reverent-rosalind-1l05g1

### Steps to reproduce

1. see how in `index.tsx` there are no errors thrown when I used `<Box h="asdfasdf">`

### Chakra UI Version

2.2.6

### Browser

Google Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by georgekrax** [comment]
I have a similar issue on this code block:
```ts
<Textarea
     placeholder="Enter your text..."
     defaultValue="Hello world!"
     onChange={e => console.log(e.target.value)}
/>
```

I get an error: **Parameter 'e' implicitly has an 'any' type. ts(7006)**, which is not usual for Chakra. I have been using the package a lot of time, in order to know its strict typed system!!

**Comment by thatvegandev** [comment]
I can confirm the last working version was `2.2.4`

**Comment by segunadebayo** [comment]
This happened when we switched from `yarn` to `pnpm`. Sorry about the inconvenience.

Kindly upgrade to 2.2.8. This has been fixed

**Comment by georgekrax** [comment]
I can confirm it works as before. Great!
Thank you @segunadebayo! 😊
