### ISSUE TITLE
Button size is not responsive

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#6488]
### Description

I reopen this issue because it is not implemented in v2: https://github.com/chakra-ui/chakra-ui/issues/4140

The size prop of the Button component does not accept responsive values.

### Problem Statement/Justification

The size prop of the Button component does not accept responsive values.

### Proposed Solution or API

Same API as what we do for other properties

**Comment by segunadebayo** [comment]
Hi @lcswillems,

This was implemented a few months ago. See here: https://codesandbox.io/s/responsive-variants-rtpn7t

Cheers.

**Comment by lcswillems** [comment]
Oh that's great!! Thank you! And sorry for having missed this!
