### ISSUE TITLE
[CSSReset] if config is provided, don't call defaultConfig

### ISSUE THREAD

**Issue by probablyup** [chakra-ui/chakra-ui#649]
**Describe the bug**
In our project our color needs did not require all the grays, whiteAlpha, etc. When trying to use CSSReset if those color steps are not available, even with a custom config, the library will throw because it attempts to access the theme properties to process the defaultConfig.

**Expected Behavior**
If a custom config is given, don't try to initialize defaultConfig using theme values.

**Comment by with-heart** [comment]
This has been fixed in 1.0. `CSSReset` no longer references the `theme` in any way.
