### ISSUE TITLE
RangeSlider not responding on mobile

### ISSUE THREAD

**Issue by wicka-aus** [chakra-ui/chakra-ui#6491]
### Description

Cant reproduce your code on my site.

### Link to Reproduction

https://codesandbox.io/s/laughing-mirzakhani-wzx974?file=/pages/index.js

### Steps to reproduce

Hi 

I pasted your code from the Chakra UI site on my site. The slider works on desktop but not mobile, bit it work on both for you site. Why is this?

TIA

PS LOVE Chakra!

`
import {
    RangeSlider,
    RangeSliderTrack,
    RangeSliderFilledTrack,
    RangeSliderThumb,
  } from '@chakra-ui/react'

export default function Range(){

    return(
        <RangeSlider
  aria-label={['min', 'max']}
  colorScheme='pink'
  defaultValue={[10, 30]}
>
  <RangeSliderTrack>
    <RangeSliderFilledTrack />
  </RangeSliderTrack>
  <RangeSliderThumb index={0} />
  <RangeSliderThumb index={1} />
</RangeSlider>
    )

}
`

### Chakra UI Version

2.2.4

### Browser

Google Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by mabaranowski** [comment]
I can confirm this. 
From v2.0.0+ the Slider component is broken on mobile.
When I downgrade @chakra-ui/react to 1.8.8, it works, while from 2.0.0 it does not.

@wicka-aus, you can do for example @chakra-ui/react 2.2.8, and install an additional package @chakra-ui/slider at version 1.5.11. 
Works fine as a temporary fix, until maintainers take a look at this.

**Comment by wicka-aus** [comment]
@mabaranowski thanks for your advice. I just downgraded too, as the slider works fine prior to the latest version.

**Comment by simonflk** [comment]
I just ran into this too.

@mabaranowski in fact it looks it was broken in 2.2.9 - and is still working if you roll back to 2.2.4

Possibly this refactor broke it: chakra-ui/chakra-ui#6472

It's clearly broken if you open the docs on mobile: https://v1.chakra-ui.com/docs/components/form/slider

**Comment by simonflk** [comment]
> I pasted your code from the Chakra UI site on my site. The slider works on desktop but not mobile, bit it work on both for you site. Why is this?

I saw the same thing happening yesterday, but today the chakra docs are broken - I'm guessing they just pushed out a docs update which picked up the new version.

I spent way too long trying to see why it appeared to work in the docs but not in my app

**Comment by segunadebayo** [comment]
Thanks for the detailed analysis @simonflk. This regression is on me and I've just pushed a fix for this. We'll release an update shortly. 

**Reference:**
https://github.com/chakra-ui/chakra-ui/commit/7000bb5fe432db85ed41aeb0c5d488bbc7da4785

If the issue persists after upgrading, I'll re-open it.
