### ISSUE TITLE
[Gatsby] The toast is cover by Modal

### ISSUE THREAD

**Issue by wujiankun** [chakra-ui/chakra-ui#6493]
### Description

When I use Modal component and toast api at the same time , when they both showed up,the The toast will be covered by Modal

**Comment by nikolovlazar** [comment]
@wujiankun I found a solution for the time being. In your `gatsby-config.js` file where you pass the plugin options, add `portalZIndex: null` like this:
```javascript
plugins: [
  {
    resolve: '@chakra-ui/gatsby-plugin',
    options: {
      /**
       * @property {boolean} [resetCSS=true]
       * if false, this plugin will not use `<CSSReset />
       */
      resetCSS: true,
      /**
       * @property {boolean} [isUsingColorMode=true]
       * if false, this plugin will not use <ColorModeProvider />
       */
      isUsingColorMode: true,
      portalZIndex: null, // <------------ ADD THIS LINE
    },
  },
],
```

This will remove the portal z-index and your toast will come on top of your modal.

**Comment by nikolovlazar** [comment]
@segunadebayo do you think we need to fix this on the plugin level?

**Comment by wujiankun** [comment]
You're great. You solve problems quickly and accurately

**Comment by segunadebayo** [comment]
@nikolovlazar, yes we should release a new version of the gatsby plugin with that fix.
