### ISSUE TITLE
Sending form returns chakra-ui styles in Netlify Forms

### ISSUE THREAD

**Issue by flaxflour** [chakra-ui/chakra-ui#6494]
### Description

Required field should return a first name, but it returns first name with chakra-ui styles

### Link to Reproduction

I can't provide link because It needs to work with netlify

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

"@chakra-ui/react": "^2.2.6"

### Browser

Firefox 103.0.2 (64-bit)

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

In the screenshot you can see that the value of the first name with astrerix(isRequired) styles and only after that the actual first name
![image](https://user-images.githubusercontent.com/31704887/185256094-fe14cebd-7b37-4495-bc2b-50afb3b78f13.png)

code for the reproductions:
```JSX
<SimpleGrid
  maxW="md"
  width="full"
  px="5"
  py="2"
  textAlign="center"
  borderWidth="2px"
  shadow="sm"
  borderColor="link"
  borderRadius="md"
>
  <Box maxW="full" overflow="hidden" padding={6}>
    <form
      name="contact"
      method="POST"
      data-netlify="true"
      data-netlify-honeypot="bot-field"
    >
      <input type="hidden" name="form-name" value="contact" />
      <p hidden>
        <label>
          Don`&apos;`t fill this out: <input name="bot-field" />
        </label>
      </p>
      <FormControl isRequired mb="1rem">
        <FormLabel fontWeight="bold">First name:</FormLabel>
        <Input name="name" type="text" placeholder="First name" />
      </FormControl>
      <ContactReason />
      <FormControl mb="1rem">
        <FormLabel fontWeight="bold">Message:</FormLabel>
        <Textarea name="message" placeholder="Enter your message here" />
      </FormControl>
      <Button size="lg" mt={4} colorScheme="blue" type="submit">
        Send
      </Button>
    </form>
  </Box>
</SimpleGrid>
```
Request form data:
![image](https://user-images.githubusercontent.com/31704887/185257533-01b7bc4f-5ac1-4523-a759-effd021b4df9.png)

Request form data raw:
form-name=contact&bot-field=&name=John&reason=I+want+to+hire+you&message=Startup+idea

**Comment by segunadebayo** [comment]
Hey @flaxflour. This has much to do with how Netlify handles forms, but it's hard to provide any help without a reproduction.

If you can provide a repro, I'll re-open this.

**Comment by flaxflour** [comment]
Thanks, @segunadebayo! Sorry for the long wait.

repo: https://github.com/flaxflour/silenius.dev

**Comment by schlpbch** [comment]
@segunadebayo : I'm seeing the same issue.

![Screenshot from 2022-09-27 22-04-46](https://user-images.githubusercontent.com/18540761/192625662-132c19cf-5df8-457a-a208-5567e0acccfd.png)

**Comment by stefan1968** [comment]
I'm having the exact same issue.

**Comment by letavocado** [comment]
@segunadebayo
