### ISSUE TITLE
Name of html component in chrome developer tools

### ISSUE THREAD

**Issue by lishine** [chakra-ui/chakra-ui#650]
1. No way for Chakra to have the component name be part of the generated class name, like with babel-plugin-emotion?
2. Generally, what approach do people take regarding pinpointing React component in the html tree. Maybe like adding id='component name' to the most outside html tag ? Maybe there is babel plugin for this?

**Comment by aaronmcadam** [comment]
I've been wanting `babel-plugin-emotion` support for a while.

What if we used a `data-chakra` data attributes to tell us the component name and type?

**Comment by lishine** [comment]
I agree.  data-chakra would be cool.
babel-plugin-emotion adds hash-Box. I saw somewhere reverse order Box-hash, it would be more visible! Otherwise it is pretty useless.
What I do now:
```
export const withDataId = (dataId: string, moreProps?: BoxProps) => ({ children, ...props }: BoxProps) => (
    <Box data-id={dataId} {...moreProps} {...props}>
        {children}
    </Box>
)
```
use it
```
const Container = withDataId('Layout')
const Top = withDataId('Top', { as: 'header' })
const Left = withDataId('Left', { as: 'aside' })
const Center = withDataId('Center', { as: 'main' })
```
Then my code is more readable after some time.

**Comment by aaronmcadam** [comment]
Hmm, thanks for noting down that workaround. I'd hope to lean on the `displayName` of the React component instance if we could.

**Comment by lishine** [comment]
What displayname supposed to do?

**Comment by lishine** [comment]
You mean in the react Dev tools ? I use the regular Dev tools because I am looking at the style. Would you help me understand how people use the react Dev tools , because it lack all the regular Dev goodies and on the other hand all these context wrappers, make me a headache?

**Comment by aaronmcadam** [comment]
I meant we could use `React.displayName` to add a `data-chakra-componentName` attribute for example. So, when using a `Box`, we would see `<div data-chakra-componentName="Box" />`. In the case of custom components, it would use its name instead.

**Comment by lishine** [comment]
?
https://github.com/lemonmade/babel-plugin-react-component-data-attribute

**Comment by segunadebayo** [comment]
We've solved this in the recent `v1` pre-release by adding classNames to all components.
