### ISSUE TITLE
extending ModalOverlay component baseStyle and defaultProps is not working

### ISSUE THREAD

**Issue by betulkaplan-amplo** [chakra-ui/chakra-ui#6504]
### Description

When define ModalOverlay in extendTheme and ste its defaultProps to bg: "linear-gradient(135deg, #007BFBCC, #A3A9F4CC)" or baseStyle background to  "linear-gradient(135deg, #007BFBCC, #A3A9F4CC)" or backgroundImage to "linear-gradient(135deg, #007BFBCC, #A3A9F4CC)", I expect this setting to reflect all the ModalOverlays that are not given overriding props of styles, but this settings has no effect to my ModalOverlay while it works when bg="linear-gradient(135deg, #007BFBCC, #A3A9F4CC)" is giveng inline 

### Link to Reproduction

https://codesandbox.io/s/condescending-herschel-gd8qrq?file=/src/index.tsx

### Steps to reproduce

1. Go to CodeSandBox link
2. Click on View the browser, 
3. See error

### Chakra UI Version

1.8.3

### Browser

Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Here's how to structure your code to work:

```jsx
const theme = extendTheme({
  components: {
    Modal: {
      baseStyle: {
        overlay: {
          backgroundImage: "linear-gradient(135deg, #007BFBCC, #A3A9F4CC)",
          background: "linear-gradient(135deg, #007BFBCC, #A3A9F4CC)",
          backgroundColor: "linear-gradient(135deg, #007BFBCC, #A3A9F4CC)"
        }
      }
    },
    Button: {
      defaultProps: {
        colorScheme: "red"
      }
    }
  }
});
```

https://codesandbox.io/s/romantic-andras-oy6mkq?file=/src/index.tsx:270-697

**Comment by betulkaplan-amplo** [comment]
Thank you so much!
