### ISSUE TITLE
Scroll lock and mounted modal content in StrictMode with Next

### ISSUE THREAD

**Issue by florianmartens** [chakra-ui/chakra-ui#6511]
### Description

When closing a modal scroll lock stays in place and modal content remains mounted (although hidden).

### Link to Reproduction

https://codesandbox.io/embed/compassionate-scott-m6umdc

### Chakra UI Version

2.2.8

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Please note that the Sandbox does not reproduce the issue. It shows the code I'm working with but I'm unable to reproduce the issue in any new project. I'm rasing this in the hopes that more people experiencing similar problems and might be able to reproduce this.

I'm currently upgrading a monorepo project to React 18 and Chakra UI 2. After the upgrade, I'm having a problem with modals which might be related to #5321. When opening and closing any modal, the scroll lock remains in place. Additionally, the modal content is still mounted but hidden. When a modal e.g. plays a video, the sound is still audible eventhough the modal is closed. This behaviour is only present in strictmode. When disabling strict mode, it works as expectd.

When creating a new next project modals close as expected. I'd love any help I can get in investigating this.

### Attempts to solve the issue
- Running `yarn upgrade` deleting `node_modules` and comparing dependencies and transitive dependencies
- Experienting with different versions of `fromer_motion`

```
"dependencies": {
        "@chakra-ui/icons": "^2.0.6",
        "@chakra-ui/react": "^2.2.8",
        "@emotion/react": "^11.10.0",
        "@emotion/styled": "^11.10.0",
        "framer-motion": "^7.2.0",
        "next": "12.2.5",
        "@nl/common": "*",
        "@nl/types": "*",
        "@nl/ui": "*",
        "axios": "^0.25.0",
        "cors": "^2.8.5",
        "next-transpile-modules": "^9.0.0",
        "nodemailer": "^6.6.5",
        "react-icons": "^4.3.1",
        "react-query": "^3.34.15",
        "react-transition-group": "^4.4.2",
        "usehooks-ts": "^2.4.1",
        "zod": "^3.9.8"
    }
```

**Comment by cieltan** [comment]
@florianmartens Can you go into more detail about the transitive dependency? I am also running into similar issues on my repo as well.

**Comment by fxckdead** [comment]
I'm having the same issue, can you tell how you fixed it @florianmartens ?
