### ISSUE TITLE
[Combobox] Component spike

### ISSUE THREAD

**Issue by martinpengellyphillips** [chakra-ui/chakra-ui#652]
Hello 👋 

I needed to create a basic combobox for my app recently and so spiked something out based on the existing `Menu` approach. Thought I would share for reference - could be a `Recipe` perhaps or help guide development of a proper Combobox in future.

https://codesandbox.io/s/chakra-ui-combobox-spike-eb0gq?file=/src/components/Combobox.js

**Comment by segunadebayo** [comment]
Hey @martinpengellyphillips, Amazing! Thanks for sharing this.

We have Combobox in our backlog and this will be very helpful to use as a reference.

**Comment by martinpengellyphillips** [comment]
@segunadebayo Great to hear 🙌

**Comment by with-heart** [comment]
A `Combobox` component is an item on our short-term roadmap. The roadmap is not publicly available yet, but I'm going to close this issue since it's work we'll be accomplishing soon.
