### ISSUE TITLE
Color mode doesn't work with gray buttons

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#6524]
### Description

Color mode doesn't work with gray buttons

### Link to Reproduction

https://codesandbox.io/s/jolly-banzai-ebztev?file=/src/index.tsx

### Steps to reproduce

When the page is in light mode:

![image](https://user-images.githubusercontent.com/5437552/185743397-2a9f590e-02ad-4067-9dc8-9fa5ab946661.png)

When the page is in dark mode:

![image](https://user-images.githubusercontent.com/5437552/185743411-781d66d4-1c75-4893-ab79-6884fa08b853.png)

The "Light Mode always" and "Dark Mode always" should not change style when the page color mode changes.

Besides the dark mode version of the button on the light mode page is wrong.

### Chakra UI Version

2.2.8

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by dvartic** [comment]
Created a PR to fix this issue. The problem is caused because the current theme sets inherit on color attrib on gray buttons for variants solid, ghost and outline, and thus prevents LightMode and DarkMode components from working as expected and is inconsistent with the other variants and colors.
