### ISSUE TITLE
Div identifier

### ISSUE THREAD

**Issue by aunjaffery** [chakra-ui/chakra-ui#6525]
### Description

Hello chakra! love the library... Can you please add a tag or something, which will show up in dev tools along with classNames. Just to identify Divs more easily and create meaning for divs. It will greatly improve development...

### Problem Statement/Justification

It is hard to identify Divs in large code base, speacially in dev-tools.

### Proposed Solution or API

Please add a tag to identify divs.

**Comment by segunadebayo** [comment]
Hi @aunjaffery,

After thinking about this. We won't be adding this feature. Kindly attach attributes on your end.

Also, the class names are auto-generated by emotion. That's beyond our scope.
