### ISSUE TITLE
Build ignoring "Unresponsive" Breakpoint Value when using useEffect

### ISSUE THREAD

**Issue by ochoadan** [chakra-ui/chakra-ui#6527]
### Description

When I used the breakpoint values, I expected "sm" value to change

### Link to Reproduction

https://github.com/ochoadan/chakra-bug

### Steps to reproduce

_Since this is a build issue NOT a dev issue I created a repo instead of using codesandbox:_ 

### To reproduce:
Clone [repository](https://github.com/ochoadan/chakra-bug) and follow instructions 
OR use the code provided below on a project page and compare dev with build to recreate the issue.

The problem is the following: The breakpoint of "sm" is ignored and doesn't change the value provided. I have tried making a custom theme, but the problem remains which makes me believe it’s a size problem.

### See the error:
![img](https://github.com/ochoadan/chakra-bug/blob/main/image.jpg?raw=true)

### Code to reproduce:
```
// pages/index.tsx

import { Stack, Button } from "@chakra-ui/react";
import { useEffect, useState } from "react";

const Index = () => {
  const [status, setStatus] = useState<number>(0.3);

  useEffect(() => {
    setStatus(0.6);
  }, []);

  if (status < 0.5) {
    return <div>loading</div>;
  }

  return (
    <Stack
      direction={{ base: "column", sm: "row" }}
      mb={{ base: 4, md: 8 }}
      spacing={4}
    >
      <Button colorScheme={"blue"}>Get started</Button>
      <Button>Learn more</Button>
    </Stack>
  );
};

export default Index;
```

### Things to remember:
It’s only the "sm" value that doesn't work and when the value its ignored it takes the "base" value instead.
It doesn't happen on dev, but it does on build.

### Chakra UI Version

2.2.8

### Browser

LibreWolf, Edge

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I have ONLY created this project with npm, I have NOT tried to recreate this issue with yarn or pmpn.

### Credit to [aboveyunhai](https://github.com/aboveyunhai) for recreating issue without NextAuth, Guy knows his stuff.

**Comment by maverick-dev7** [comment]
This is happening too in production with "md" breakpoint when reloading the page.

**Comment by segunadebayo** [comment]
Hi @ochoadan,

This is most likely a bug in Next.js and the modification going on. Can you set swcMinify to false and see if the issue persist?

**Comment by ochoadan** [comment]
Hi there @segunadebayo.
The issue is non persisstent without swcMinify, meaning it IS a Next.js feature bug. I totally forgot this feature was enabled.
