### ISSUE TITLE
[Menu] Cannot read property 'length' of null

### ISSUE THREAD

**Issue by bjgrosse** [chakra-ui/chakra-ui#653]
Intermittently I get this error when using a Menu component. It happens after clicking a menu item. 

The line where the item is thrown is 388 of the menu/index.js:

`if (focusableItems && focusableItems.current.length > 0) {`

I think the fix is quite simple: focusableItems is created with useRef, so this line should be checking that focusableItems.**current** is not null:

`if (focusableItems.current && focusableItems.current.length > 0) {`

**Comment by segunadebayo** [comment]
Hi @bjgrosse,

Thanks for catching this. We've fixed this in preparation for the next release.

**Comment by JClackett** [comment]
Hi @segunadebayo 

Thanks for the fix, will this be in the next minor release, or in the TS release?

Thanks for the good work!

**Comment by l3szcz** [comment]
For anyone that has this bug - you can use [patch-package](https://www.npmjs.com/package/patch-package) to make and automatically apply a fix on each `npm install` until it is fixed.

**Comment by segunadebayo** [comment]
Thanks for chiming in @l3szcz.

@JClackett, we've published a couple of pre-releases and we plan to release an update this week.

Thanks guys.

**Comment by JWeis** [comment]
@segunadebayo Hello! Thank you for this great framework! I am running into this same issue. I am trying to map over an array of items that I would like to display in a  MenuList as MenuItems. When I hover over the MenuButton that is the trigger to this MenuList I get this error. 

```Unhandled Runtime Error
TypeError: Cannot read property 'length' of null

Call Stack
eval
node_modules/@chakra-ui/core/dist/es/Menu/index.js (388:0)
eval
node_modules/@chakra-ui/core/dist/es/utils/index.js (84:0)
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js (188:0)
Object.invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js (237:0)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (292:0)
invokeGuardedCallbackAndCatchFirstError
node_modules/react-dom/cjs/react-dom.development.js (306:0)
executeDispatch
node_modules/react-dom/cjs/react-dom.development.js (389:0)
executeDispatchesInOrder
node_modules/react-dom/cjs/react-dom.development.js (414:0)
executeDispatchesAndRelease
node_modules/react-dom/cjs/react-dom.development.js (3278:0)
executeDispatchesAndReleaseTopLevel
node_modules/react-dom/cjs/react-dom.development.js (3287:0)
Array.forEach
<anonymous>
forEachAccumulated
node_modules/react-dom/cjs/react-dom.development.js (3257:0)
runEventsInBatch
node_modules/react-dom/cjs/react-dom.development.js (3304:0)
runExtractedPluginEventsInBatch
node_modules/react-dom/cjs/react-dom.development.js (3514:0)
handleTopLevel
node_modules/react-dom/cjs/react-dom.development.js (3558:0)
batchedEventUpdates$1
node_modules/react-dom/cjs/react-dom.development.js (21871:0)
batchedEventUpdates
node_modules/react-dom/cjs/react-dom.development.js (795:0)
dispatchEventForLegacyPluginEventSystem
node_modules/react-dom/cjs/react-dom.development.js (3568:0)
attemptToDispatchEvent
node_modules/react-dom/cjs/react-dom.development.js (4267:0)
dispatchEvent
node_modules/react-dom/cjs/react-dom.development.js (4189:0)
unstable_runWithPriority
node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js (653:0)
dispatchUserBlockingUpdate
node_modules/react-dom/cjs/react-dom.development.js (4172:0)
```

Any suggestions on how to fix this?

**Comment by ljosberinn** [comment]
@JWeis hi could you provide a codesandbox? what version are you seeing this on?

**Comment by JWeis** [comment]
@ljosberinn I haven't done that before. What is the best way to do so? 

Here is the code I am trying to implement:

```
<Menu closeOnBlur closeOnSelect>
      <MenuButton
        as={StyleLink}
        onClick={onToggle}
        textDecoration="none"
        _hover={{ textDecoration: 'none' }}
      >
        <MenuItem
          w="full"
          textAlign="center"
          p="1em"
          display="block"
          _hover={{ bg: 'gray.200' }}
          role="menuitem"
        >
          {item.name}
        </MenuItem>
      </MenuButton>
      <MenuList maxWidth="250px" isOpen={isOpen}>
        <PopoverArrow />
        {item.dropdowns.map((drop) => {
          if (drop._type === 'internal') {
            return (
              <MenuItem
                w="full"
                textAlign="center"
                p="1em"
                display="block"
                _hover={{ bg: 'gray.200' }}
                role="menuitem"
              >
                <Link href="#" key={drop._key}>
                  <a>{drop.name}</a>
                </Link>
              </MenuItem>
            )
          }
          if (drop._type === 'external' || drop._type === 'resource') {
            return (
              <a
                href={drop.link}
                key={drop._key}
                target="_blank"
                rel="noopener noreferer"
              >
                <MenuItem
                  w="full"
                  textAlign="center"
                  p="1em"
                  display="block"
                  _hover={{ bg: 'gray.200' }}
                  role="menuitem"
                >
                  {drop.name}
                </MenuItem>
              </a>
            )
          }
        })}
      </MenuList>
    </Menu>
```

**Comment by ljosberinn** [comment]
If you can additionally provide a JSON of `item.dropdowns`, I can go from there.

**Comment by JWeis** [comment]
@ljosberinn thank you! Here is the `item` Object that I am passing in as a prop. 

```
{
  "_key": "bb16b6f91deb",
  "dropdowns": [
    {
      "_key": "f53d23e84662",
      "_type": "internal",
      "name": "Business Solutions",
      "slug": { "_type": "slugType", "current": "business-solutions" }
    },
    {
      "_key": "b79bafb4deb3",
      "_type": "resource",
      "link": "https://cdn.sanity.io/files/m3csstrl/production/289d8f10982a162eb4768b4f9c44612ca6633606.pdf",
      "name": "Test Resource"
    },
    {
      "_key": "715547b3226b",
      "_type": "external",
      "link": "https://www.sips.org/",
      "name": "SIPA"
    }
  ],
  "name": "Services",
  "slug": { "_type": "slugType", "current": "services" }
}
```

**Comment by ljosberinn** [comment]
You're not always returning in your `dropdowns.map`, so effectively you're in the same situation as #1319. `.map` functions should always return something. I'd recommend filtering beforehand instead. Here's a working sandbox: https://codesandbox.io/s/muddy-morning-7s606?file=/src/App.js

**Comment by JWeis** [comment]
@ljosberinn Thank you for this! It works perfectly in your sandbox but not in my dev. I am running Next.js as well and not sure if that makes a difference. How is this working without `useDisclosure()` hook to toggle open? I am setting up a sandbox now.

**Comment by ljosberinn** [comment]
`useDisclosure` is only needed if you want to trigger it through some other means. `Menu` itself can already take care of itself if you let it. Running Next shouldn't make any difference. Do you still see the same error in your code or a different?

**Comment by JWeis** [comment]
Same error with the code you provided. Here is a sandbox: https://codesandbox.io/s/crazy-panini-pzyrx

**Comment by ljosberinn** [comment]
I'm not seeing an error in that sandbox, but I can't open the `Menu` either because theres an `MenuItem` surrounding the `Menu`. Removing that and replacing `next/link` with `Link` from Chakra because you can't replicate Nextjs that easily in the sandbox works. No errors: https://codesandbox.io/s/brave-leakey-btrwr?file=/src/Dropdown.js

**Comment by JWeis** [comment]
That was the issue. I hade `MenuItem` directly under `Menu` in the parent component which was why I was seeing the last error. All working now. Thank you!!

**Comment by ljosberinn** [comment]
Youre welcome - please feel free to join our discord for a better "live support" experience :] https://discord.gg/T6tcfU

**Comment by JWeis** [comment]
Joined! Thank you!

**Comment by tafelito** [comment]
I'm seeing this same error but only when using usePortal property. The error seems to be different than the OP since that was already fixed. Anyone has seen this in 0.8?

**Comment by mmahalwy** [comment]
running into this too. any luck @tafelito ?
