### ISSUE TITLE
Dark mode not set by default

### ISSUE THREAD

**Issue by alexbakers** [chakra-ui/chakra-ui#6538]
### Description

Dark mode not set by default

### Link to Reproduction

localhost

### Steps to reproduce

Default - **light**. Why?

```
import {
  ChakraProvider,
  ColorModeScript,
  extendTheme,
  type ThemeConfig,
} from "@chakra-ui/react";

const configChakra: ThemeConfig = {
  useSystemColorMode: false,
  initialColorMode: "dark",
};

const theme = extendTheme(configChakra);

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
        <ChakraProvider theme={theme}>
          <ColorModeScript initialColorMode={theme.config.initialColorMode} />
          <App />
        </ChakraProvider>
  </React.StrictMode>
);
```

But toggle nice work to dark  in App.tsx
```
const { colorMode, toggleColorMode } = useColorMode();

<Button onClick={toggleColorMode}>
  Toggle {colorMode === "light" ? "Dark" : "Light"}
</Button>
```

https://user-images.githubusercontent.com/98721968/186196498-cd966e4e-b603-44e9-ae02-442a32038a2f.mov

### Chakra UI Version

2.2.3

### Browser

[Version 1.42.97 Chromium: 104.0.5112.102 (Official Build) (arm64)](https://brave.com/latest/)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by alexbakers** [comment]
My solution:

```
useEffect(() => {
  if (colorMode === "light") {
    toggleColorMode();
  }
}, []);
```

But I think there are better options.

**Comment by segunadebayo** [comment]
This happens when you already have a value for `chakra-ui-color-mode` in the localstorage. Can you clear local storage?

**Comment by alexbakers** [comment]
> This happens when you already have a value for `chakra-ui-color-mode` in the localstorage. Can you clear local storage?

Thanks for your reply.

The behavior of a site with a default dark theme is somewhat unpredictable.

Button blinking after every page refresh.


https://user-images.githubusercontent.com/98721968/186519217-6b06415f-2b35-438b-be7e-06e9cb205b46.mp4

```
const { colorMode, toggleColorMode } = useColorMode();
useEffect(() => {
  console.log("colorMode", colorMode);
  if (colorMode === "light") {
    // toggleColorMode();
  }
}, []);
```

The console says that the theme is light, but the theme on the site is dark.

**Comment by remiroyc** [comment]
Same issue here

**Comment by anubra266** [comment]
@alexbakers I can't reproduce this. If issue persists, please feel free to reopen with a codesandbox reproduction

**Comment by schulzf** [comment]
I get exactly the same issue (running chakra on nextjs), I have followed the docs on how to set the colorMode to dark by default, but when my app loads it sets `chakra-ui-color-mode` to light on localStorage

here is my theme settings
```
export const theme = extendTheme({
	fonts,
	colors,
	components: {},
	useSystemColorMode: false,
	initialColorMode: 'dark',
	breakpoints: {
		// this makes everything below 1168px show as mobile and everything above as desktop
		sm: `1168px`,
		md: `1168px`,
		lg: `1169px`,
		xl: `1169px`,
		'2xl': `1169px`,
		'3xl': `1169px`,
	},
});
```

my `_app.tsx` looks like this:
```
		<ApolloProvider client={gqlClient}>
			<SessionContextProvider supabaseClient={supabaseClient} initialSession={pageProps.initialSession}>
				<ChakraProvider theme={theme}>
					<ToastContainer />
					<SignupContextProvider>
						<Component {...pageProps} />
					</SignupContextProvider>
				</ChakraProvider>
			</SessionContextProvider>
		</ApolloProvider>
```

am I missing something?

dependencies:
`"@chakra-ui/react": "^2.4.3"`
`"next": "^13.1.4"`

**Comment by emil14** [comment]
Any updates?

**Comment by ChristianHardy** [comment]
Same problem here, why the issue closed? Somebody solve it?

**Comment by codengine** [comment]
Same here (using vite), even with private browsing.

**Comment by patmifsud** [comment]
Same here

**Comment by utajum** [comment]
My workaround

```js
import {
	LightMode,
	DarkMode,
} from '@chakra-ui/react'

const DarkOrLightMode = ({
	forceThemeMode,
	children,
}: {
	forceThemeMode?: 'light' | 'dark' | undefined
	children: React.ReactNode
}) => {
	if (forceThemeMode === 'light') {
		return <LightMode>{children}</LightMode>
	}

	if (forceThemeMode === 'dark') {
		return <DarkMode>{children}</DarkMode>
	}

	return <>{children}</>
}
```
