### ISSUE TITLE
"Progress" doesn't load

### ISSUE THREAD

**Issue by magmabits** [chakra-ui/chakra-ui#6543]
### Description

When I added the "Progress"-Element to my code, I thought it would add a visible progressbar, however it didn't.

### Link to Reproduction

https://codesandbox.io/s/goofy-ahh-progress-j37bwr

### Steps to reproduce

1. Open `components/LanguageCards.tsx`
2. Try to add a "progress" element to a "card

### Chakra UI Version

2.2.4

### Browser

Firefox 103.0.2 (64-bit)

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![grafik](https://user-images.githubusercontent.com/66217030/186267696-0001a990-a530-4937-80b8-4ac838b6fa84.png)

**Comment by magmabits** [comment]
Also, I get these (look at attached image below) errors for no apparent reason:
![image](https://user-images.githubusercontent.com/66217030/186268941-85b0ada4-a822-4c5a-adf4-7b1b90f47166.png)

Anything on that?

**Comment by segunadebayo** [comment]
Your reproduction doesn't load at all.

Looking at the code, I see you're using a flex layout around the Progress. Consider setting the width to 100% or wrapping the Progress with an extra div. 

It's mostly a CSS issue, not a Chakra one. Regarding that error, please upgrade to the most recent version.
