### ISSUE TITLE
Theme source link of form control broken

### ISSUE THREAD

**Issue by renancleyson-dev** [chakra-ui/chakra-ui#6546]
### Description

When I was looking for the theme source for form control, it opened a tab for a GH 404 page.

### Link to Reproduction

https://chakra-ui.com/docs/components/form-control/usage

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.2.3

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Good catch. It works now 👍🏽
