### ISSUE TITLE
Stack won't render content in NextJS [TypeScript]

### ISSUE THREAD

**Issue by AlternativeForce** [chakra-ui/chakra-ui#6548]
### Description

All variants of Stack (Stack, HStack, VStack), won't have content inside of them render to the page. Visible in Inspect Element, but no content seems to be injected.

### Link to Reproduction

https://codesandbox.io/s/stupefied-hypatia-897yc8?file=/pages/index.tsx

### Steps to reproduce

1. Install all required packages for NextJS 
2. Install all required packages for ChakraUI
3. Implement ChakraProvider into _app.tsx
4. Import any Stack element from @chakra-ui/react
5. Create a functional component and return a Stack component with text inside EX: return <Stack>Welcome to Chakra UI</Stack>;

### Chakra UI Version

2.2.8

### Browser

Google Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![blank1](https://user-images.githubusercontent.com/92130486/186333969-a6f50d7b-3de9-40a6-8ef0-346df72acb1d.PNG)
![blank2](https://user-images.githubusercontent.com/92130486/186334168-aafb8925-f72e-4280-b030-600518e3eea0.PNG)
![blank3](https://user-images.githubusercontent.com/92130486/186334247-d6214547-d3f2-43c8-80b6-e0880bf79c28.PNG)

**Comment by segunadebayo** [comment]
Hi @AlternativeForce,

Stack-related elements require an element due to the selectors we use internally. 

Please wrap the content within a `<span>` and it should work as expected.
