### ISSUE TITLE
Cannot use Chakra in combination with Turborepo and Next.js

### ISSUE THREAD

**Issue by engelkes-finstreet** [chakra-ui/chakra-ui#6551]
### Description

When I installed chakra in a Turborepo package, I expected to be able to use the components in my other apps  but I receive an error

### Link to Reproduction

There is no Turborepo example on CodeSandbox

### Steps to reproduce

1. Create a new Turborepo with `npx create-turbo@latest`
2. In the UI package install all Chakra dependencies
3. In the `Button.tsx` component import the Button from Chakra and use it in the component
4. Start the `web` or `docs` app and the following error occurs:

```
error - Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

### Chakra UI Version

2.2.8

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @engelkes-finstreet,

This issue isn't related to Chakra. I just tried it, and it seems it throws without using any Chakra component. Kindly report this in the Turbo repo instead.

Thanks.

<img width="909" alt="CleanShot 2022-08-26 at 16 06 19@2x" src="https://user-images.githubusercontent.com/6916170/186899845-6093dd3c-caf1-49b3-a26e-10d5730b49e8.png">

**Comment by taneba** [comment]
@engelkes-finstreet 
I'm facing the same problem. Did you get to any solution?
