### ISSUE TITLE
Switch value not being set by React-Hook-Form

### ISSUE THREAD

**Issue by cpvalente** [chakra-ui/chakra-ui#6552]
### Description

When using Chakra UI with react hook form, I am able to control the input fields as expected. However, when using a Switch component, the reset() action is not able to reset the value of the component

This is because <Switch> uses a prop isChecked rather than a traditional value.
I wonder if there is a potential to revise the integration of this component?

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-react-hook-form-switch-ltoxkc?file=/src/HookForm.js

### Steps to reproduce

1. Go to ['codesandbox'](https://codesandbox.io/s/chakra-ui-react-hook-form-switch-ltoxkc?file=/src/HookForm.js)
2. Change the name field to another value
3. Click on switch component to make it active
4. Click on reset button.
5. The name field is reset correctly, but the <Switch> value remains unchanged

### Chakra UI Version

2.0.0

### Browser

Chrome and Firefox

### Operating System

- [ ] macOS
- [x] Windows
- [ ] Linux

**Comment by itsrennyman** [comment]
Hello, @cpvalente.

Looking at the source code there's already an integration for this particular behavior from `react-hook-form`.

https://github.com/chakra-ui/chakra-ui/blob/%40chakra-ui/checkbox%402.0.0/packages/checkbox/src/use-checkbox.ts#L233-L250

I think some debug in this piece of code on the `reset()` call can help us find the solution.

What do you think about?

**Comment by tumdav93** [comment]
@segunadebayo I faced another issue, When Switch has defaultChecked set to true and react hook form programmatically sets the value false, the chakra system ignores the false value, and Switch remains checked.
