### ISSUE TITLE
Select component attempts to access `_focus` in potentially undefined styles.field object

### ISSUE THREAD

**Issue by michael-rayner92** [chakra-ui/chakra-ui#6554]
### Description

When I test a form using the Select component, I expected the component to render but a TypeError Cannot read properties of undefined (reading '_focus') happened instead

### Link to Reproduction

https://codesandbox.io/s/chakra-select-component-bug-in7khe

### Steps to reproduce

1. Go to the [CodeSandbox link ](https://codesandbox.io/s/chakra-select-component-bug-in7khe)
2. Run `yarn test`
3. Error will log to the console

### Chakra UI Version

2.2.9

### Browser

Google Chrome 104

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

The issue is coming from the [packages/select/src/select.tsx](https://github.com/chakra-ui/chakra-ui/blob/main/packages/select/src/select.tsx) file.

The styles object is created using `useMultiStyleConfig()`

```JavaScript
const styles = useMultiStyleConfig("Select", props)
```

However when later populating the **fieldStyles**, the `styles.field["_focus"]` is accessed. The *field* value is potentially undefined and therefore will throw an uncaught error.

```JavaScript
  const fieldStyles: SystemStyleObject = {
    paddingEnd: "2rem",
    ...styles.field,
    _focus: {
      zIndex: "unset",
      ...(styles as any).field["_focus"],
    },
  }
```

Looking at how other components have similarly approached this issue, e.g. [button.tsx](https://github.com/chakra-ui/chakra-ui/blob/main/packages/button/src/button.tsx) and [input-element.tsx](https://github.com/chakra-ui/chakra-ui/blob/main/packages/input/src/input-element.tsx), it looks like the fix is to add optional chaining before accessing the field and/or focus element.

Hence the proposed solution:

```JavaScript
...(styles as any).field?.["_focus"]
```

**Comment by segunadebayo** [comment]
Good catch! I just pushed a fix @michael-rayner92. I'll do a new release shortly.
