### ISSUE TITLE
Table, table cell, table row have redundant aria roles

### ISSUE THREAD

**Issue by iansjk** [chakra-ui/chakra-ui#6556]
### Description

Chakra-UI's `Table`, `Tr`, and `Td` elements render `<table>`, `<tr>`, `<td>` elements respectively. These HTML elements have implicit ARIA roles, but Chakra-UI adds redundant roles to the output.

### Link to Reproduction

https://codesandbox.io/s/gifted-cannon-u0u8eq

### Steps to reproduce

1. Open codesandbox
2. Open devtools inspector
3. Observe that `<table>`, `<tr>`, and `<td>` elements have `role="..."` attributes defined

### Chakra UI Version

2.2.8

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

A workaround is to suppress the addition of the redundant role attribute by passing `role={undefined}` to Table, Tr, and Td.

Note that `<table>` and `<tr>` have implicit roles `table` and `row` respectively, so those are purely duplicative, but `<td>` has implicit role `cell`. Chakra's `Td` currently gives it `role="gridcell"`. These are slightly different, but elements with role `gridcell` can only be descendants of a `table role="grid"` (which Chakra's `Table` is not using), so the current usage is not valid.

**Comment by iansjk** [comment]
If this issue makes sense to the maintainers I'm happy to submit a PR for it.

Looking through the source, I noticed that `MenuDivider` likewise outputs a `<hr>` but puts `role="separator"` on it, which is an intrinsic role of `<hr>`. I didn't see anything else though.

**Comment by segunadebayo** [comment]
Hi @iansjk. Go for it

**Comment by TimKolberger** [comment]
I think the intention to duplicate the role is in maintaining the elements role even if the as prop is used.

But I agree with removing it for the common use case, which is without an as prop.
