### ISSUE TITLE
Not able to use chakra ui pro theme

### ISSUE THREAD

**Issue by aravind-tc** [chakra-ui/chakra-ui#6557]
### Description

Not able to use chakra ui pro theme

### Link to Reproduction

Not Available

### Steps to reproduce

We have just installed the chakra ui pro blueberry theme. We have followed the guidelines mentioned in the readMe document.

We are facing with the following issue
<img width="959" alt="Screen Shot 2022-08-24 at 5 40 28 PM" src="https://user-images.githubusercontent.com/37326359/186548735-d24642df-eff9-4830-9e44-cd59b43b1674.png">

We are using the following Chakra ui versions
 "@chakra-ui/pro-theme": "^0.0.53",
    "@chakra-ui/react": "^2.2.8",
    "@chakra-ui/theme-tools": "^2.0.10",

### Chakra UI Version

2.2.8

### Browser

Google Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @aravind-tc,

Consider downloading the pro theme from the website and using it locally. We're yet to look into the module export differences between Pro and Chakra (It's our next priority).

Thanks

![CleanShot 2022-08-25 at 12 24 03@2x](https://user-images.githubusercontent.com/6916170/186614511-ab2be322-5c66-48d0-bf18-e6bc643e37cf.png)

**Comment by oceandrama** [comment]
@segunadebayo Hi! Do you have any updates on this?
