### ISSUE TITLE
Tooltip arbitrarily activates when slider value changes

### ISSUE THREAD

**Issue by makifoxgirl** [chakra-ui/chakra-ui#6558]
### Description

Tooltip arbitrarily activates when slider value changes

### Link to Reproduction

https://codesandbox.io/s/cold-dawn-oo7jeh

### Steps to reproduce

1. Open the CodeSandbox page
2. Hover over slider to see the tooltip
3. Press button to see it activate tooltip without hovering over it

### Chakra UI Version

@chakra-ui/react ^2.2.8

### Browser

Firefox 105.0b2 on Windows 11 and macOS
Chrome 104.0.5112.102 on Windows 11
Safari 15.6 (17613.3.9.1.5) on macOS

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I have a video that shows the same problem in production. Take a look:

https://user-images.githubusercontent.com/8362329/186579613-4eebe33d-2c88-4851-98c1-9ba42ab97397.mp4

**Comment by 0xFuji** [comment]
This is caused by the slider triggering the onFocus event when the value is changed... How to fix this? I don't know :)

**Comment by Wonder2210** [comment]
@makifoxgirl I don't k now if you fixed yet, but it can be fixed using the prop` focusThumbOnChange={false}`  more info here https://chakra-ui.com/docs/components/slider/props

**Comment by makifoxgirl** [comment]
@Wonder2210 Sorry for the late reply. This fixed my issue! Thank you so much, I had missed it
