### ISSUE TITLE
Request to add Stepper component

### ISSUE THREAD

**Issue by jeanverster** [chakra-ui/chakra-ui#656]
What's everyone's thoughts on including a Stepper component and whether that would be a consideration? I believe it's quite a common use case for multi-step forms / wizards, and having a built in solution would be great.

I recently had to implement one in a project I was working on, and would be happy to have a go at implementing it, but would like to use this thread as an opportunity to discuss the potential API and how it would work?

Currently how I have set mine up is to simply pass the "steps" as children of the stepper component and then handle the logic the split them into their respective steps inside the `Stepper` component, so usage would look something like this:

```
<Stepper activeStep={step}>
  <H5>Step 1 Content</H5>
  <H5>Step 2 Content</H5>
  <H5>Step 3 Content</H5>
  <H5>Step 4 Content</H5>
</Stepper>
```

The above would render this:

![stepper](https://user-images.githubusercontent.com/17738943/80682228-64f09b80-8ac2-11ea-821e-c9f02ca00e4a.gif)

This would give the user total control over what gets rendered as well as incrementing / decrementing the current active step, although I'm open to suggestions as to alternatives. I'm also not sure about wai-aria specifications for Steppers / wizards (or if there are any) so any help there would be much appreciated.

Look forward to hearing your thoughts!

**Comment by raikusy** [comment]
It would be great to have a Stepper component like this! +1 for this.

**Comment by aaronmcadam** [comment]
I think this is a good idea for a component, but I don't believe `Stepper` is the right name for it for Chakra.

Whilst "Stepper" seems to be a popular name for [wizard component](https://material-ui.com/components/steppers/), it is also [the name](https://www.nngroup.com/articles/input-steppers/) of a [component](https://docs.mobify.com/progressive-web/latest/components/#!/Stepper) for incrementing and decrementing numbers on a form. [NumberInput](https://chakra-ui.com/numberinput) has `NumberInputStepper`, `NumberIncrementStepper` and `NumberDecrementStepper`.

How about `Wizard`?

**Comment by jeanverster** [comment]
@aaronmcadam agreed, totally forgot about the other `Stepper` references. Happy to call it Wizard 👍 Will hopefully get a gap to work on this soon and submit a PR

**Comment by ernstoarllano** [comment]
Would love to see a Stepper component added. Have a current project that's using Material UI, but would love to switch to Chakra UI if it had this one component, literally the one component that's preventing a full switch.

**Comment by dimitropoulos** [comment]
hey :smile: I noticed that you're working on building a Stepper.  The [react-ui-roundup](https://github.com/dimitropoulos/react-ui-roundup) has a lot of other examples of Steppers that might be interesting or useful points of reference to you while you're developing it for chakra-ui.

https://react-ui-roundup.dimitrimitropoulos.com/#Stepper

> Tip: if you view from the website you can open click `OPEN ALL IN NEW TABS` and see them all at once.

**Comment by with-heart** [comment]
Thanks for the idea @jeanverster but I'm going to close this issue as part of our backlog cleanup as we have no plans to implement something like this soon.

**Comment by jeanverster** [comment]
For anyone that happens to come across this, I have recently published a standalone steps component designed to work with Chakra UI if anyone's interested 🙂

https://github.com/jeanverster/chakra-ui-steps

**Comment by anubra266** [comment]
Cool...Nicely done @jeanverster

**Comment by vdurvalino** [comment]
> For anyone that happens to come across this, I have recently published a standalone steps component designed to work with Chakra UI if anyone's interested 
> 
> https://github.com/jeanverster/chakra-ui-steps

Thanks for that

**Comment by melvinalmonte** [comment]
> https://github.com/jeanverster/chakra-ui-steps

My man! love it

**Comment by Ningaro** [comment]
> https://github.com/jeanverster/chakra-ui-steps
Awesome! ❤

**Comment by festus14** [comment]
> For anyone that happens to come across this, I have recently published a standalone steps component designed to work with Chakra UI if anyone's interested slightly_smiling_face
> 
> https://github.com/jeanverster/chakra-ui-steps

Wow, Thanks a lot for this.

**Comment by spidertwin2** [comment]
> For anyone that happens to come across this, I have recently published a standalone steps component designed to work with Chakra UI if anyone's interested 🙂
> 
> https://github.com/jeanverster/chakra-ui-steps

Thanks for working on this!! Very neatly executed ✌️

**Comment by MalikaRakhimova31** [comment]
> For anyone that happens to come across this, I have recently published a standalone steps component designed to work with Chakra UI if anyone's interested 🙂
> 
> https://github.com/jeanverster/chakra-ui-steps

Faced with an error while using this component in next.js. Gives width is undefined in responsiveness
