### ISSUE TITLE
Truncated text (noOfLines) not working in Firefox

### ISSUE THREAD

**Issue by Mbensler** [chakra-ui/chakra-ui#6560]
### Description

My truncated text does not work in Firefox, but it works in Chrome and Edge. This might be a problem in all "Firefox browsers" and not Chromium browsers

`<Text noOfLines={4}>`

### Link to Reproduction

https://ck-frontend-newest.vercel.app/

### Steps to reproduce

1. Go to ['this link'](https://ck-frontend-newest.vercel.app/)
3. Scroll down to the middle/bottom of the page where it says "/NYHEDER - Seneste nyt fra din revisor"
4. The error is happening in the news boxes. It works fine in Chromium based browsers, but it doesn't work at all in Firefox. Instead of only printing 4 lines of text it prints all of the text, making the boxes and the section huge.
5. Swap between Chromium(Edge, Chrome) and Firefox browsers to see the error.

### Chakra UI Version

2.2.9

### Browser

Firefox 104.0

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

This is a pretty huge error on my site, which is to be released soon. Is there any way I can correct this myself until a proper fix has been released?

Thanks in advance.

**Comment by segunadebayo** [comment]
Hi @Mbensler,

Looking at your website, the issue here is that noOfLines should be applied to the element that contains the text content, not the container.

https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp

```jsx
<Box sx={{ "> p": { noOfLines: 4 } }}>
</Box>
```
