### ISSUE TITLE
Type error: Module '"@chakra-ui/theme-tools"' has no exported member 'SystemStyleFunction'

### ISSUE THREAD

**Issue by aravind-tc** [chakra-ui/chakra-ui#6561]
### Description

Type error: Module '"@chakra-ui/theme-tools"' has no exported member 'SystemStyleFunction'

### Link to Reproduction

Not Available

### Steps to reproduce

I have purchased and copied the blueberry chakra UI pro theme in my project. It seems that components such as avatar.ts in components folder has some type script issues

Type error: Module '"@chakra-ui/theme-tools"' has no exported member 'SystemStyleFunction'

We are not able to compile the project. Is this known issue to you? For now, we unblocked ourself with // @ts-nocheck but can you gracefully fix this?

### Chakra UI Version

2.2.8

### Browser

Google Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @aravind-tc,

Can you import this directly from "@chakra-ui/react" for now. I'll push an update for this shortly.

Thanks

**Comment by segunadebayo** [comment]
Kindly upgrade to 2.2.9. The exports exists there.

**Comment by aravind-tc** [comment]
As suggested , i am importing from chakra- ui 2.2.9 release as mentioned below
import { SystemStyleFunction } from '@chakra-ui/react'

But, all the component files in blue berry theme imports "SystemStyleFunction" from '@chakra-ui/theme-tools' . Can you update the theme tools or modify the files to make sure that this type is imported from chakra ui instead.
