### ISSUE TITLE
Toast doesn't update on second update if first update doesn't include position

### ISSUE THREAD

**Issue by rtman** [chakra-ui/chakra-ui#6565]
### Description

When I update a toast 2 times I expect it to update 2 times but it only updates 1 time

### Link to Reproduction

https://codesandbox.io/s/eloquent-lehmann-in28bs

### Steps to reproduce

1. Go to https://codesandbox.io/s/eloquent-lehmann-in28bs
2. Click on toast
2. Click on update toast
2. Click on update toast 2
4. See the toast is not updated the last time

### Chakra UI Version

2.2.8

### Browser

Brave

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The issue seems to be that if you specify a position on the original toast, but not on the subsequent updates, a second update does not work. Specifying the position on each toast update does work.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
