### ISSUE TITLE
Exporting ModalStylesProvider 

### ISSUE THREAD

**Issue by federicodelpiano** [chakra-ui/chakra-ui#6566]
### Description

I'm wondering if it's possible to export the ModalStylesProvider from the Modal component?

### Problem Statement/Justification

Using Chakra 1.8.6 I made a custom Modal implementation, to keep it's Portal always mounted (and hide it using display).
Looks like this:
```
export const PersistentModal = (props: ModalProps) => {
  const styles = useMultiStyleConfig('Modal', props)
  const modal = useModal(props)
  const { isOpen, children, portalProps } = props
  const context = { ...modal, blockScrollOnMount: isOpen }

  return (
    <ModalContextProvider value={context}>
      <StylesProvider value={styles}>
        <Portal {...portalProps}>
          <Box display={context.isOpen ? 'initial' : 'none'}>{children}</Box>
        </Portal>
      </StylesProvider>
    </ModalContextProvider>
  )
}
```

I'm migrating to v2.2.x and I have two issues:
- I'm getting this error:
`ContextError: useModalStyles returned is 'undefined'. Seems you forgot to wrap the components in "<Modal />"` (cause by the Modal children calling useModalStyles).
- The **StylesProvider** is deprecated.

To my understanding, I should replace the deprecated **StylesProvider** with the **ModalStylesProvider**, but I see [here](https://github.com/chakra-ui/chakra-ui/blob/3a87f68474221ed402fe5d169f7067763c8436d5/packages/components/modal/src/modal.tsx#L23) that you're not exporting the ModalStylesProvider.

### Proposed Solution or API

Export the ModalStylesProvider from the Modal component.

**Comment by segunadebayo** [comment]
Hi @federicodelpiano,

StylesProvider is a regular React context provider. Feel free to create your context to handle this since it's a custom modal you have.

```jsx
const StylesContext = React.createContext()

export const PersistentModal = (props: ModalProps) => {
  const styles = useMultiStyleConfig('Modal', props)
  const modal = useModal(props)
  const { isOpen, children, portalProps } = props
  const context = { ...modal, blockScrollOnMount: isOpen }

  return (
    <ModalContextProvider value={context}>
      <StylesContext.Provider value={styles}>
        <Portal {...portalProps}>
          <Box display={context.isOpen ? 'initial' : 'none'}>{children}</Box>
        </Portal>
      </StylesContext.Provider>
    </ModalContextProvider>
  )
}
```

**Comment by federicodelpiano** [comment]
@segunadebayo thanks for you reply.
The issue i'm having is with the children of the Modal (ModalOverlay, ModalContent, etc.):
```
      <PersistentModal
        isOpen={isOpen}
        onClose={onClose}
        size="full"
      >
        <ModalOverlay />
        <ModalContent>
          <ModalHeader>
            Title here
          </ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            Body here
          </ModalBody>
          <ModalFooter>
            <Button onClick={onClose}>
              Close
            </Button>
          </ModalFooter>
        </ModalContent>
      </PersistentModal>
```

Those children components are referencing a context that is supposed to be created in the original Chakra Modal, but since I'm not using that, that context was never created, that's why useModalStyles returns undefined.
