### ISSUE TITLE
As suggested , i am importing from chakra- ui 2.2.9 release as mentioned below

### ISSUE THREAD

**Issue by aravind-tc** [chakra-ui/chakra-ui#6568]
As suggested , i am importing from chakra- ui 2.2.9 release as mentioned below
import { SystemStyleFunction } from '@chakra-ui/react'

But, all the component files in blue berry theme imports "SystemStyleFunction" from '@chakra-ui/theme-tools' . Can you update the theme tools or modify the files to make sure that this type is imported from chakra ui instead.

_Originally posted by @aravind-tc in https://github.com/chakra-ui/chakra-ui/issues/6561#issuecomment-1228336320_

**Comment by segunadebayo** [comment]
If you upgrade theme tools to the latest version, you should be able to see `SystemStyleFunction` exported, and the error should be gone.

See here: https://github.com/chakra-ui/chakra-ui/blob/ac6a00aea4113c4d77d6568125ddf38b339635b4/packages/components/theme-tools/src/component.ts#L12
