### ISSUE TITLE
Types - incoherence in `UseRadioProps` type when using `exactOptionalPropertyTypes`

### ISSUE THREAD

**Issue by mijamo** [chakra-ui/chakra-ui#6569]
### Description

The return type of `getRadioProps` should match `UseRadioProps` but currently it doesn't for the `onChange` property when activating strict checks in typescript.

### Link to Reproduction

https://codesandbox.io/s/long-sky-31k3xp?file=/src/index.tsx

### Steps to reproduce

See the error while trying to use `CustomRadio` after calling `getRadioProps`:

```
Types of property 'onChange' are incompatible.
    Type 'FormEventHandler<HTMLInputElement> | undefined' is not assignable to type '(event: ChangeEvent<HTMLInputElement>) => void'.
      Type 'undefined' is not assignable to type '(event: ChangeEvent<HTMLInputElement>) => void'
```

I think the `onChange` event should be specified in the output of `getRadioProps` just like `id` and `role` already are

### Chakra UI Version

2.2.9

### Operating System

- [ ] macOS
- [ ] Windows
- [x] Linux

**Comment by isBatak** [comment]
Chakra should enable https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes and add `| undefined` at the end of types like this one https://github.com/chakra-ui/chakra-ui/blob/b0a36dba2cf82ca343f77f9864134c6c5fc53221/packages/styled-system/src/utils/types.ts#L10
`export type ResponsiveValue<T> = T | ResponsiveArray<T> | ResponsiveObject<T> | undefined`

**Comment by segunadebayo** [comment]
Adding [exactOptionalPropertyTypes](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes) would be too much of a change since our focus is on v3.

I recommend making the changes suggested above. Thanks for understanding
