### ISSUE TITLE
can't remove checked radio programmatically for useRadioGroup

### ISSUE THREAD

**Issue by aayman997** [chakra-ui/chakra-ui#6574]
### Description

I have two radio groups, The second one depends on the first one, When I select radio from the first one and then select one in the second group It's working perfectly but if I tried to change the value of the first one the second groups keep checked I need to deselect the second group radio if the first one value changed

### Link to Reproduction

https://codesandbox.io/s/radio-example-4npgil?file=/pages/index.tsx

### Steps to reproduce

1. Open the sandbox
2. Select a day
3. Select a time
4. Now select another day

**Current behavior**
- The selected time keep checked after changing the day

**Expected behavior**
- The selected time must be cleared after selecting another day

### Chakra UI Version

2.2.3

### Browser

Chrome 104.0.5112.102 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This isn't a Chakra UI issue. It has more to do with how you've modeled the component and state.

**Here's a working solution:**
https://codesandbox.io/s/dependent-radio-groups-2i6kni
