### ISSUE TITLE
`focusBorderColor` prop on forms (Input, Select, etc) doesn't work if color isn't hex or rgb.

### ISSUE THREAD

**Issue by Hexiro** [chakra-ui/chakra-ui#6578]
### Description

I expected it to not matter what format the color is in.

### Link to Reproduction

https://codesandbox.io/s/crazy-bouman-pzb5nm?file=/src/index.tsx

### Steps to reproduce

1. Create form element that has `focusBorderColor` as a prop option.
2. Change `focusBorderColor` to a theme color that's hsl or hwb, or a hsl, hwb value directly.
3. Focus element
4. See color is `undefined` in devtools:

### Chakra UI Version

2.2.9

### Browser

Opera GX 89

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Undefined color (when using hsl or hwb):

![image](https://user-images.githubusercontent.com/42787085/187000880-55c615e0-81a0-42f5-a837-37832ef9adab.png)

love chakra ui ❤

**Comment by NickVishwamitra** [comment]
Removing the 'deg' from the hsl color fixes it:

hsl(264 100% 50%)

**Comment by Hexiro** [comment]
that's interesting

**Comment by segunadebayo** [comment]
This has been fixed in a recent PR. We'll publish an update shortly
