### ISSUE TITLE
Add itemIcon prop to List component

### ISSUE THREAD

**Issue by Pacheco95** [chakra-ui/chakra-ui#6587]
### Description

Add `itemIcon` prop to List component to avoid code duplication

### Problem Statement/Justification

Today it is possible to style lists throug `ListIcon` within `ListItem` component.
Imo, having a listing with different icons for each list item is uncommon. So, my suggestion is to add the `itemIcon` prop to `List` and apply the passed icon as the default for all items in the list

### Proposed Solution or API

Instead of:

```tsx
<List>
  <ListItem>
    <ListIcon as={CheckIcon} />
    ...
  </ListItem>
    <ListItem>
    <ListIcon as={CheckIcon} />
    ...
  </ListItem>
    <ListItem>
    <ListIcon as={CheckIcon} />
    ...
  </ListItem>
</List>
```
do:

```tsx
<List itemIcon={CheckIcon}>
  <ListItem>
    ...
  </ListItem>
  <ListItem>
    ...
  </ListItem>
  <ListItem>
    ...
  </ListItem>
</List>
```

**Comment by segunadebayo** [comment]
Hi @Pacheco95.

I imagine you can easily achieve this in your app code by iterating with `Array.map`. I'm hesitant to add this API to Chakra UI itself.

Thanks
