### ISSUE TITLE
Using <Hide> with SSR

### ISSUE THREAD

**Issue by rbozan** [chakra-ui/chakra-ui#6589]
### Description

https://github.com/chakra-ui/chakra-ui/blob/3a87f68474221ed402fe5d169f7067763c8436d5/packages/components/media-query/src/use-media-query.ts#L32

In this line we have the possibility to have SSR go to a fallback value. However, using Hide, it doesn't seem that we can provide such a fallback value. We can for example use the "is-mobile" package to check if the user is on a phone, but how would we say that we'd like to render the mobile view then?

### Problem Statement/Justification

At the moment using Next.js it's rendering the desktop view on first render and then switching to mobile afterwards. 

### Proposed Solution or API

Allow us to give fallback prop?

**Comment by segunadebayo** [comment]
Hi @rbozan,

I'd recommend using the CSS display property to show/hide elements on screen. We're considering deprecating those Show/Hide components in the future.

**Comment by rbozan** [comment]
@segunadebayo Hi,

Is there not a possibility to have this implemented in the current Hide component in Chakra UI instead? Material UI does the same with https://mui.com/material-ui/api/hidden/ with their "css" implementation:



 implementation | 'css'\| 'js' | 'js' | Specify which implementation to use.  'js' is the default, 'css' works better for server-side rendering.
-- | -- | -- | --

Otherwise a lot of Chakra UI users would have to write their own Hidden component with CSS while I'm pretty sure those implementations wouldn't differ from project to project.
