### ISSUE TITLE
Chakra Portal does not support Shadow dom

### ISSUE THREAD

**Issue by davidizac** [chakra-ui/chakra-ui#6591]
### Description

When I use the portal component inside shadow dom, I get the portal node outside of it (at document.body level) which is a bad behavior since my chakra styles aren't defined outside.

### Problem Statement/Justification

A valid reason for adding this feature is that it will allow us to use chakra ui on chrome extensions.

### Proposed Solution or API

Open to discuss about any solutions

**Comment by davidizac** [comment]
Works finally

**Comment by sheryarshirazi** [comment]
@davidizac how did you do that? can you give some example or codesandbox link?

**Comment by franky47** [comment]
@davidizac I would also be interested in learning more about your fix to constrain Chakra into the Shadow DOM. I'm trying to package a Drawer into a web component and it escapes into the main document's body, rather than into a shadowed Portal.

**Comment by EmilEriksen** [comment]
I don't think it's possible to make the default portal render in the shadow DOM currently. Chakra inserts the default portal by creating a temporary node and obtaining a reference to the document with `tempNode.ownerDocument`. See [here](https://github.com/chakra-ui/chakra-ui/blob/c57b00f80f177c2a165dc3e879e30e362b0806fb/packages/components/portal/src/portal.tsx#L54).
