### ISSUE TITLE
[Mobile view] Avatar falling out of stack in the demo

### ISSUE THREAD

**Issue by JayeshJanyani** [chakra-ui/chakra-ui#660]
**Describe the bug**
While I was scrolling through the Avatar component in Mobile view. I observed that the Avatar badges are falling out of the stack boundary.

**Expected Behavior**
Avatar badges should be viewable inside stack for better user experience.

**To Reproduce**
1. Visit https://chakra-ui.com/avatar or Open Avatar tab from the side navigation in the website
2. Scroll to "Usage" heading.
3. Also, scroll a little to "Avatar Sizes" heading.

**Device**
OS: iOS 13.3.1
Device: iPhone XR
![IMG-4524](https://user-images.githubusercontent.com/29023441/80748149-1b479580-8b42-11ea-8ae3-9f02e3e1dd42.PNG)
![IMG-4525](https://user-images.githubusercontent.com/29023441/80748166-20a4e000-8b42-11ea-9de4-2123879ceeb4.PNG)

**Comment by segunadebayo** [comment]
Hi @JayeshJanyani,

This is happening due to 2 reasons.
- Avatar uses `z-Index`
- `Stack` doesn't set `flexWrap` or `overflow` property.

Thanks for bringing it up. Let's check it in the docs @with-heart
