### ISSUE TITLE
Unwanted css manioluation

### ISSUE THREAD

**Issue by Clientastisch** [chakra-ui/chakra-ui#6600]
### Description

When I use h1, h2, h3, ... they are all the same font size/width

### Steps to reproduce

For some reason, all tags such as h1, h2, ..., as well as p are all of the same height and font/size.
This behavior is not desirable for my application. 

Is there a way to fix this, so that the default h1, h2, h3... properties are used?

 https://i.imgur.com/DA5vf1F.png

### Chakra UI Version

1.6.4

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hey. This is the side effect of the CSS reset applied by Chakra UI.

To turn this off. You can pass the `resetCSS=false` to the `ChakraProvider`
