### ISSUE TITLE
Unexpected behavior when slider max value updated

### ISSUE THREAD

**Issue by ahrbil** [chakra-ui/chakra-ui#6606]
### Description

When Slider max value updated, the Slider component should use the latest value.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-et8r5j?file=src/App.jsx

### Steps to reproduce

After `setTimeout` is completed, try interacting with the Slider component. 

### Chakra UI Version

2.3.1

### Browser

Microsoft Edge 105

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Noctambul** [comment]
Did you find a workaround ? There is only the click on the track which seems not to take into account the new max value
