### ISSUE TITLE
Tooltip causes console error

### ISSUE THREAD

**Issue by zikowang** [chakra-ui/chakra-ui#6607]
### Description

When Tooltip is used and triggered, there is an error shown in the browser console

### Link to Reproduction

https://codesandbox.io/s/morning-bird-rlf3u9

### Steps to reproduce

1. Set up a minimal React 18 project
2. Install ChakraUi 2.3.1 (currently latest version)
3. Use the Tooltip component anywhere inside the ChakraProvider
4. Tigger the Tooltip
5. Check the browser console for the error message

(The error is triggered once and will be treggered after the page is reloaded)

### Chakra UI Version

2.3.1

### Browser

Chrome Version 104.0.5112.101 (Offizieller Build) (arm64), Safari Version 15.6.1 (17613.3.9.1.16)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The error says
> Using kebab-case for css properties in objects is not supported. Did you mean var(-tooltipFg)?

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/16488024/187674641-f9da46ae-ea5a-4fab-9bb2-514e14207973.png">

**Comment by JayV30** [comment]
Having the same issue, driving me nuts all morning. Seems related to the latest version (and perhaps dependencies?). I'm not familiar with Chakra-UI under the hood, but this was not happening for me on 2.2.9.

**Comment by JayV30** [comment]
#6605

**Comment by cereallarceny** [comment]
Second - we're also having this problem on 2.2.6 @JayV30
