### ISSUE TITLE
Chakra `transition` Property is taking over `framer-motion` transition` Property.

### ISSUE THREAD

**Issue by a4addel** [chakra-ui/chakra-ui#6608]
I can't build bc When I use framer-motion with as Property Typescript show error and

the error is
`Type '{ opacity: number; }' is not assignable to type 'ResponsiveValue<Transition<string & {}>>'.`

I got over it by using framer-motion component
`<motion.div animate={{ opacity: .3 }}></motion.div>`
I suggest to change the name of the properties that might mixup with other libraries

![dddCapture](https://user-images.githubusercontent.com/84184203/187723014-30803bb1-e60e-4a72-91f0-5748423b7310.PNG)

**Comment by NickVishwamitra** [comment]
Framer allows you to place the transition prop inside the animate prop so this is what I do to get around those clashing prop names:

```tsx
<Heading
      as={motion.h1}
      initial={{ opacity: 0 }}
      animate={{
        opacity: 1,
        transition: {
          delay: 1,
          duration: 1,
        },
      }}
    >
   Welcome to Chakra UI
</Heading>
```
