### ISSUE TITLE
[v1] Migration path umbrella thread

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#661]
Hi,

I recently peeked into `dev-ts` to verify whether a bug I found is still an issue. Gladly, it's been fixed there.

However, I noticed a few differences between `master` and `dev-ts` and would like to collect information about potential incompatibilities or breaking changes in here, as I'm currently in the planning phase of building a larger site with chakra and I think it's in everyones best interest to communicate this as early as possible.

Thanks!

**Comment by segunadebayo** [comment]
I think I tried to cover some breaking changes in this post #696. 

Please leave any comments you have there.

Thank you!
