### ISSUE TITLE
Switching tabs causes flickering of children's slider

### ISSUE THREAD

**Issue by lucasrabiec** [chakra-ui/chakra-ui#6615]
### Description

Switching Tabs causes (flickering) changing of padding-top/-bottom of children's Slider.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-fycxjc?file=src/App.tsx

### Steps to reproduce

1. Switch between tabs (Left, Right)
1. You should notice some kind of flickering on slider, caused by changing padding (from 0px to 7px and vice versa)
Additional info: Bug occurs only when Slider has a Thumb.

### Chakra UI Version

2.3.1

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Here is a video in which you can notice how padding-top and -bottom are changing when switching tabs.
https://user-images.githubusercontent.com/9741188/187916258-317aee41-2725-495f-aa1d-f3c3dd69bf81.mov

**Comment by lucasrabiec** [comment]
I found the place which causes this strange flickering effect on the slider: https://github.com/chakra-ui/chakra-ui/blob/3a87f68474221ed402fe5d169f7067763c8436d5/packages/components/slider/src/slider-utils.ts#L78-L89

And also calculating thumb style will cause a thumb flickering effect while switching tabs: https://github.com/chakra-ui/chakra-ui/blob/3a87f68474221ed402fe5d169f7067763c8436d5/packages/components/slider/src/slider-utils.ts#L49-L53

When we switch from the left to the right tab, the left tab with content hides and the left thumb size is changed from 14 (default) to 0, but the right thumb from 0 to 14. That is why we are noticing that strange flicker effect during the switching (changing padding causes the whole slider moves for a while). Such a weird edge case. The thumb size is dynamic while showing and hiding and I don't have any idea how to solve it.

@segunadebayo I noticed that most of the work on it is made by you. I'm guessing you have more insight into it 😃 Do you have an idea how to handle this issue?

**Comment by segunadebayo** [comment]
No idea. I'll look into this

**Comment by egorguscha** [comment]
@segunadebayo Hi, any ideas?

**Comment by arbejd** [comment]
Stumbled upon this issue also

**Comment by gbrocha** [comment]
Still happening. Any update on this?

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
