### ISSUE TITLE
Editable: Wrapping preview with Tooltip doesn't blur per Tooltip docs; persists Tooltip

### ISSUE THREAD

**Issue by don-hover** [chakra-ui/chakra-ui#6616]
### Description

When using tab to focus and then blur an EditablePreview wrapped by a Tooltip, I expect the tooltip to appear when focusing and disappear when blurring the EditablePreview, but it appears and then persists, it doesn't disappear on blur().

### Link to Reproduction

https://codesandbox.io/s/musing-ioana-txiqp0?file=/src/index.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/musing-ioana-txiqp0.  This is a test app that contains an `EditablePreview` component wrapped by a `Tooltip`.
2. Click on the preview browser window.
3. Use the 'tab' key to tab through first the "dummy" `Box` element, and then the `EditablePreview` labeled "Tooltip test", and then tab away from the editable preview.
4. Observe that the tooltip is displayed when focusing onto the editable preview, but incorrectly persists when tabbing away from (blurring) the editable preview.

![Screen Shot 2022-09-01 at 1 04 44 PM](https://user-images.githubusercontent.com/77687833/187971827-5e7d7ce9-f9f0-4d94-873d-a39eed7bd592.png)

### Chakra UI Version

latest

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Somewhat related to closed issue https://github.com/chakra-ui/chakra-ui/issues/6255

**Comment by segunadebayo** [comment]
Hi @don-hover,

To fix this, kindly close the tooltip on pointer down using the `closeOnMouseDown` options. We don't manage the coordination of the events, it's most likely a react bug.

**Comment by infrasparker** [comment]
@segunadebayo
I'm getting this same issue and I'm confused what `closeOnMouseDown` has to do with it. This is occurring when the user tabs away from an element, so there's no mouse events involved.
The codesandbox link that @don-hover provided is a good example - the tooltip gets stuck when someone tabs away from the focused element in an `EditablePreview`, which is another chakra element anyway.
