### ISSUE TITLE
tooltip has color of black by default

### ISSUE THREAD

**Issue by mistersingh179** [chakra-ui/chakra-ui#6617]
### Description

The text in tooltip is black in color by default. I expect it to be white on black.

### Link to Reproduction

https://codesandbox.io/s/quizzical-banach-5df2y7?file=/src/App.js

### Steps to reproduce

1. Hover over text
2. You will see tooltip
3. It has incorrect color

### Chakra UI Version

2.3.1

### Browser

Chrome 104.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by dennemark** [comment]
Thanks for creating this issue. Experiencing the same. More details here:
![image](https://user-images.githubusercontent.com/29654902/188075315-61a1ce21-b819-4231-887b-8aaa18f9aa5f.png)

console.log error message: `Using kebab-case for css properties in objects is not supported. Did you mean var(-tooltipFg)?`

OS: Windows

**Comment by dennemark** [comment]
I think it is this PR? https://github.com/chakra-ui/chakra-ui/pull/6605

**Comment by NachoKai** [comment]
Same issue here, and tooltip styles broken
`Using kebab-case for css properties in objects is not supported. Did you mean var(-tooltipFg)? `

**Comment by segunadebayo** [comment]
This has been fixed in latest release.
