### ISSUE TITLE
Option to wipe baseStyle entirely

### ISSUE THREAD

**Issue by WesleyYue** [chakra-ui/chakra-ui#6618]
### Description

We would like to request a feature that allows removing all styling for specific Chakra components.

### Problem Statement/Justification

We use Tailwind with Chakra. On some components, we would like to have specific control over the element via Tailwind classes. However, this is often times not possible if the baseStyle already defines the properties, since it has higher precedence over the Tailwind css classes.

### Proposed Solution or API

n/a

**Comment by Patrick-Ullrich** [comment]
This already works, simply do not use `extendTheme` and you are not important any Chakra specific styling.

**Comment by segunadebayo** [comment]
Hey. You can simply use an empty theme in the ChakraProvider.

```jsx
<ChakraProvider theme={{}}>
  <App />
</ChakraProvider>
```

or remove specific components using a omit function

```jsx
const customTheme = omit(theme.components, ["Button"])

<ChakraProvider theme={customTheme}>
  <App />
</ChakraProvider>
```
