### ISSUE TITLE
[textOverflow] is not available as a prop, despite documentation

### ISSUE THREAD

**Issue by chrysb** [chakra-ui/chakra-ui#662]
**Describe the bug**
I am unable to use `textOverflow` as an option. We're currently on `0.7.0` which I believe is the latest

**Expected Behavior**
According to the documentation, `text-overflow` should be available on all components as `textOverflow`

**To Reproduce**
1. Create a `Box` and try to add a `textOverflow` prop

![image](https://user-images.githubusercontent.com/120388/80894175-aed9ad00-8c8d-11ea-86cb-55490d93b75d.png)

**Comment by segunadebayo** [comment]
Hi @chrysb,

I see what you mean. Actually, `textOverflow` is missing in the type definition but it works.

We'll update this in the next release.

Thanks.

**Comment by chrysb** [comment]
Awesome, thanks so much!

**Comment by segunadebayo** [comment]
@chrysb, in the meantime, consider using the `style` prop or emotion's `css` prop to control the text-overflow.

**Comment by with-heart** [comment]
I can verify that this is now working in the 1.0 pre-release: https://codesandbox.io/s/damp-sunset-fes1g?file=/src/App.js
