### ISSUE TITLE
[@chakra-ui/gatsby-plugin] support for `cookieStorageManagerSSR`

### ISSUE THREAD

**Issue by pettinarip** [chakra-ui/chakra-ui#6621]
### Description

The current plugin implementation does not support `cookieStorageManagerSSR` which helps to avoid the initial flashing on sites.

### Problem Statement/Justification

`cookieStorageManagerSSR` solves the color mode `flashing` problem: https://chakra-ui.com/docs/styled-system/color-mode#add-colormodemanager-optional-for-ssr

### Proposed Solution or API

https://chakra-ui.com/docs/styled-system/color-mode#add-colormodemanager-optional-for-ssr

Not sure if this is doable on Gatsby side but I guess that it could be done inside the `gatsby-ssr.js` file.

**Comment by segunadebayo** [comment]
We don't have plans to support this. Sorry.
