### ISSUE TITLE
[remix] color mode changes to previous after route change with `cookieStorageManagerSSR`

### ISSUE THREAD

**Issue by ImExoOdeex** [chakra-ui/chakra-ui#6622]
### Description

When using `cookieStorageManagerSSR()` to store a color mode cookie, when theme has been changed and we change route, theme returns to its previous state. [video](https://www.zdaje.com/remix.mp4)

### Link to Reproduction

https://node-vpxihz--3000.local.webcontainer.io/

### Steps to reproduce

We'll copy my repo, cuz I found that on stackblitz
1. Go to ['https://github.com/ImExoOdeex/remix-chakra-ui-SSR'](https://github.com/ImExoOdeex/remix-chakra-ui-SSR)
2. Clone that repo
3. Run `npm i` and `npm run dev`
4. Watch [video](https://www.zdaje.com/remix.mp4) and do the same.

### Chakra UI Version

2.3.1

### Browser

Google Chrome 104.0.5112.102

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

On stackblizt its not working as I wanted, instead copy repo in `Steps to reproduce`. People in discord are having same problem

**Comment by zengxinzhy** [comment]
I encountered the same issue, and I solved it by saving cookieStorageManagerSSR into a `useConst` or `useState`



```
const cookieManager = useConst(cookieStorageManagerSSR(cookies));
return (
  <Document>
        <ChakraProvider theme={theme}
          colorModeManager={typeof cookies === 'string'
            ? cookieManager
            : localStorageManager
          }>
          [...]
        </ChakraProvider>
   </Document>
);


```

**Comment by SpencerDuball** [comment]
> I encountered the same issue, and I solved it by saving cookieStorageManagerSSR into a `useConst` or `useState`
> 
> ```
> const cookieManager = useConst(cookieStorageManagerSSR(cookies));
> return (
>   <Document>
>         <ChakraProvider theme={theme}
>           colorModeManager={typeof cookies === 'string'
>             ? cookieManager
>             : localStorageManager
>           }>
>           [...]
>         </ChakraProvider>
>    </Document>
> );
> ```

You are a hero, this has been the bane of my existence for quite some time. Thank you for posting this!

**Comment by selbekk** [comment]
I would suggest filing this as a bug

**Comment by segunadebayo** [comment]
Closing based on https://github.com/chakra-ui/chakra-ui/issues/6622#issuecomment-1298150598
