### ISSUE TITLE
<Stack> with <StackDivider> When set direction responsibly is not showing

### ISSUE THREAD

**Issue by violabg** [chakra-ui/chakra-ui#6624]
### Description

https://codesandbox.io/s/sandpack-project-forked-oijtwj?file=/App.tsx

### Link to Reproduction

https://codesandbox.io/s/sandpack-project-forked-oijtwj?file=/App.tsx

### Steps to reproduce

Resize the window

### Chakra UI Version

2.3.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by violabg** [comment]
It used to work, but after I have updated to the latest version, my layout is broken

**Comment by VincenzoSMC** [comment]
I’m having this issue too, and it’s breaking my design. Please fix it

**Comment by segunadebayo** [comment]
This was a regression and we've fixed it in #6704.

We'll release an update shortly.

**Comment by violabg** [comment]
is this fix been released? because I still see the bug on the latest release 

https://codesandbox.io/s/sandpack-project-forked-myqlst?file=/App.tsx

**Comment by itkrt2y** [comment]
@violabg Use `direction` instead of `flexDirection`
https://chakra-ui.com/docs/components/stack/usage#responsive-direction

**Comment by violabg** [comment]
thanks, I'm closing this.
but direction e flexDirection can lead to confusion...
