### ISSUE TITLE
2.3.1 rendering speed is slower than 2.2.4

### ISSUE THREAD

**Issue by saihyou** [chakra-ui/chakra-ui#6625]
### Description

When I drew `Grid`, the rendering speed was significantly slower than in 2.2.4.

### Link to Reproduction

https://codesandbox.io/s/restless-wood-wec29b?file=/src/index.tsx

### Steps to reproduce

1. Open the SandBox in new window
2. Start React Profiler
3. Click the Button
4. Stop React Profiler
5. Change `@chakra-ui/react` version to `2.2.4` and repeat steps 1 to 4

### Chakra UI Version

2.3.1

### Browser

Google Chrome 104.0.5112.102

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I attach the results of my measurements.
`Styled(div)` is much slower in 2.3.1 compared to 2.2.4.

**2.3.1**
![2 3 1](https://user-images.githubusercontent.com/1284461/188259371-a40518e9-f262-4510-8875-a877d25e5aca.png)

**2.2.4**
![2 2 4](https://user-images.githubusercontent.com/1284461/188259378-32ef895a-e54e-4fb2-ba54-984e0762554c.png)

**Comment by segunadebayo** [comment]
Hey @saihyou,

This happened because we improved the internals of Chakra UI. Kindly upgrade to the latest.

Thanks
