### ISSUE TITLE
`NumberInput` styling incomplete when parent `FormControl` has `isDisabled=true`

### ISSUE THREAD

**Issue by psychedelicious** [chakra-ui/chakra-ui#6627]
### Description

When `isDisabled=true`, Number Input does not fully grey-out and cursor is not changed.

### Link to Reproduction

https://codesandbox.io/s/friendly-drake-dnbpm2

### Steps to reproduce

1. Go to https://codesandbox.io/s/friendly-drake-dnbpm2
2. Observe that for disabled Number Input only greys-out the Steppers and border, the "no touch" cursor only shows when hovering the Steppers, and the border changes colour on hover
3. Compared to the disabled Select, where everything is greyed-out, the "no touch" cursor shows over the whole component, and the border colour does not change on hover

### Chakra UI Version

2.3.1

### Browser

Firefox 104.0.1, Safari 15.6.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
<img width="794" alt="CleanShot 2022-09-13 at 12 45 28@2x" src="https://user-images.githubusercontent.com/30869823/189892749-5a7c85fd-097f-4119-9eff-fa81949d4800.png">
 
Works well in the docs, so it's not an issue from Chakra. You're doing something else wrong. Feel free to ask for help in the Discord community.

**Comment by JTBrinkmann** [comment]
@anubra266 it works on the docs pages because those are using the older 2.2.9 release. I can **confirm** it's broken since 2.3.0 of `@chakra-ui/react`.
