### ISSUE TITLE
RROR in node_modules/@chakra-ui/descendant/src/use-descendant.ts:11:56 TS2344

### ISSUE THREAD

**Issue by Gosiaisean** [chakra-ui/chakra-ui#6632]
### Description

When i installed i18n-intl for react i got following issue: ERROR in node_modules/@chakra-ui/descendant/src/use-descendant.ts:11:56 TS2344: Type 'K' does not satisfy the constraint 'Record<string, any>'

### Link to Reproduction

no link - installation issue?

### Steps to reproduce

1. Install i18n intl
2. Run application

### Chakra UI Version

1.7.4

### Browser

Any

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by thenerdassassin** [comment]
I have seen this identical issue. I received it after installing these npm packages:
* ethers
* wagmi

**Comment by jonasgroendahl** [comment]
also having this issue, trying to use `tsm` with strict=true

**Comment by thomas0306** [comment]
facing the same issue, we have downgraded typescript (4.8.2 -> 4.7.4) as a temporary solution.

**Comment by JClackett** [comment]
Downgrading to 4.7.4 for now too!

**Comment by cpvalente** [comment]
This error doesnt seem to exist with the latest chakra and ts versions.
Tested now with     

> "@chakra-ui/react": "^2.3.2",
> "typescript": "^4.8.3"

**Comment by segunadebayo** [comment]
I just released [v1.8.9](https://www.npmjs.com/package/@chakra-ui/react/v/1.8.9)

Please update this version recent version to resolve the problem.
