### ISSUE TITLE
Error in Tooltip Color Style Definition

### ISSUE THREAD

**Issue by netbizltd** [chakra-ui/chakra-ui#6633]
### Description

Text inside tooltip not readable

### Link to Reproduction

https://codesandbox.io/s/reverent-spence-du1i02?file=/src/index.js

### Steps to reproduce

Light UI shows dark tooltips. Text should be light but it is black.
Dark UI shows light tooltips. Text should be dark but it is white.

This screenshot shows the error in the styles:

![image](https://user-images.githubusercontent.com/97948726/188456460-0320f969-b9a4-4dc8-b5f8-8dd344149528.png)

### Chakra UI Version

2.1.0

### Browser

Brave

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Temporary Fix: <Tooltip color="inverted" ...>...</Tooltip>

**Comment by lucasishuman** [comment]
Related #6636

**Comment by segunadebayo** [comment]
This has been fixed in the latest release. Kindly upgrade.
