### ISSUE TITLE
Function to create blank theme with just the bare basics

### ISSUE THREAD

**Issue by LaylBongers** [chakra-ui/chakra-ui#6634]
### Description

I want to be able to create a new theme from just the basics, the colors, sizes, and reset css, but not any component styling.

### Problem Statement/Justification

A significant amount of my theme code is dedicated to un-doing default styles, and it quickly becomes unclear what's actually important styling or not.

### Proposed Solution or API

Create a new function like `extendTheme`, which just extends the basics, probably `semanticTokens`, `direction`, `...foundations`, and `config`, as well as a subset of `styles`, but critically not `components`.

### Alternatives

Manually copying from the existing theme is very cumbersome, and doesn't allow easily overwriting foundations where necessary, as `extendTheme` always extends the default theme.

**Comment by segunadebayo** [comment]
Hi @LaylBongers,

You can import specific parts of the theme by installing the theme package, and 

```jsx
import { foundations }  from "@chakra-ui/theme/foundations"

function App({children}){
 return <ChakraProvider theme={foundations}> {children} </ChakraProvider>
}
```

**Comment by LaylBongers** [comment]
I could do this in the past, but this doesn't work anymore on the current published version of @chakra-ui/theme
