### ISSUE TITLE
Virtual scroll in Table

### ISSUE THREAD

**Issue by roshnidevadiga** [chakra-ui/chakra-ui#6635]
### Description

Need a way by which we could implement virtual scrolling in table

### Problem Statement/Justification

I am using the chakra UI table to render a huge list of data. Since the data could be huge, I was looking for a way to use virtual scrolling here, so that only the items in viewport appear in the DOM. Is there a way to do that? I tried to wrap my Tbody contents with FixedSizeList of react-window. But it gives out an error that div cannot be a child of tbody. Is there any other way of achieving this?

` <Tbody {...getTableBodyProps()}>
                    <FixedSizeList height={400} itemCount={rows.length} itemSize={35}>
                        {rows.map(row => {
                            prepareRow(row);
                            return (
                                <Tr {...row.getRowProps()}>
                                    {row.cells.map(cell => {
                                        return (
                                            <Td {...cell.getCellProps()}>{cell.render("Cell")}</Td>
                                        );
                                    })}
                                </Tr>
                            );
                        })}
                    </FixedSizeList>
                </Tbody>`

### Proposed Solution or API

If the integration issues with react-window is resolved, I guess we should be good. Else if the similar functionality could be provided by chakra-ui out of the box, it would be great

**Comment by segunadebayo** [comment]
Hi @roshnidevadiga. This isn't in the scope of Chakra UI for now

**Comment by matthesinator** [comment]
Any luck in solving your problem yet? I've got the same problem

**Comment by NiklasPor** [comment]
For anyone coming across this, either stop using the table elements or convert (all) of them to regular divs by passing `as="div"`. Then add the correct table aria roles everywhere. Also bear in mind, the chakra performance of larger components while fast virtual scrolling might not be super-good.
