### ISSUE TITLE
Tooltip text color

### ISSUE THREAD

**Issue by novacooo** [chakra-ui/chakra-ui#6636]
### Description

The color of the font in the tooltip is inverted. The light theme is the same as the dark theme and vice versa.

### Link to Reproduction

https://codesandbox.io/s/tooltip-text-color-bug-chakra-ui-s6o4pf?file=/src/index.tsx

### Chakra UI Version

2.3.1

**Comment by lucasishuman** [comment]
Related #6633

**Comment by mmmeff** [comment]
This was merged and a fix should release soon.

You can fix it in the meantime by customizing the default styles in your theme:

```
extendTheme({
  components: {
    Tooltip: {
      baseStyle: {
        color: 'white',
        background: 'gray.700',
      },
    },
  },
})
```

**Comment by segunadebayo** [comment]
This has been fixed in the latest version.
