### ISSUE TITLE
[Docs]: All components in a single page (kitchen sink / demo)

### ISSUE THREAD

**Issue by lucasholder** [chakra-ui/chakra-ui#664]
It would be nice to have a "kitchen sink" page with all the components displayed, would make discovering the components easier instead of having to click each link in the navigation one by one.

**Comment by jmilani224** [comment]
Hi @segunadebayo - I'm a big fan of this project - I starting building out a 'kitchen sink' page and wanted to get your input. Let me know if you'd find this useful, and I'll complete it. I'm building with gatsby, but the code should transfer to your site pretty easily if you wanted to bring it over:

https://chakra-ui-kitchen-sink.netlify.app/

Here's how I'm currently organizing the components - would love to get your input on this as well:

https://docs.google.com/spreadsheets/d/1yeERPAQbOfR2bPO_pnUYA62cZAiinDsW6uW8yWOXyPE/edit?usp=sharing

**Comment by jmilani224** [comment]
Quick update - I wrapped up a kitchen sink demo here: https://chakra-ui-kitchen-sink.netlify.app/

**Comment by with-heart** [comment]
Going to close this as we have some plans for improving the docs and creating new ways to learn Chakra in the works.
