### ISSUE TITLE
ModalOverlay does not respect theme's style configuration for component

### ISSUE THREAD

**Issue by mmmeff** [chakra-ui/chakra-ui#6646]
### Description

When I define baseStyles for a ModalOverlay in my theme, they have no effect on the component

### Link to Reproduction

https://codesandbox.io/s/crazy-http-f0w2i3?file=/src/index.tsx

### Steps to reproduce

1. Add a custom theme
2. Try and override base styles for the ModalOverlay component

### Chakra UI Version

2.3.1

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Modal is considered a composite (or multipart) component. Here's the correct structure:

```jsx
const theme = extendTheme({
  components: {
    Heading: {
      baseStyle: {
        background: "red.500"
      }
    },
    Modal: {
      baseStyle: {
        overlay: {
          background: "red"
        }
      }
    }
  }
});
```

https://codesandbox.io/s/pedantic-visvesvaraya-ns0o8v?file=/src/index.tsx:743-976

**Comment by mmmeff** [comment]
Thanks! Should this be reflected somewhere in the documentation? I'm not sure how I ever would have figured that out without your help!
