### ISSUE TITLE
kebab-case for css properties in objects is not supported. Did you mean var(-tooltipFg)

### ISSUE THREAD

**Issue by iluvkoohi** [chakra-ui/chakra-ui#6647]
### Description

When I wrapped my form with a tooltip, I expected to have it work flawlessly, but it throws a warning in the console, which bothers me since this is my first time using this design framework.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-javascript-lzzg9

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

"@chakra-ui/react": "^2.3.1"

### Browser

Google Chrome Latest

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

**This is the code I used which I copied from chakra UI Documentation**

```
 <Tooltip
              color={"white"}
              backgroundColor={"red"}
              label='Email already exist'
              placement='left'
              isOpen={state.register.statusCode == 400} 
              hasArrow>
              <Input
                  id="email"
                  isInvalid={state.register.hasError || errors.email}
                  placeholder="example@email.com"
                  bg={'gray.100'}
                  border={0}
                  color={'gray.500'}
                  _placeholder={{
                      color: 'gray.500',
                  }}
                  {...registerEmail} />
</Tooltip>
```

**Every time a tooltip is toggled or displayed in DOM, this warning appears.**

`Using kebab-case for css properties in objects is not supported. Did you mean var(-tooltipFg)? `

**Comment by wuxinli1025** [comment]
I have the same issue, also `--tooltip-fg` is not defined:
<img width="276" alt="Screen Shot 2022-09-11 at 11 57 52 AM" src="https://user-images.githubusercontent.com/1777979/189508554-47ce5ff7-e9da-4bc1-a37e-acbc551646c9.png">

**Comment by anubra266** [comment]
This has been fixed. Please upgrate to the latest version.
