### ISSUE TITLE
[PseudoBox] _before={{content=`""`}}  is not available, despite documentation

### ISSUE THREAD

**Issue by alfrejivi** [chakra-ui/chakra-ui#665]
**Describe the bug**
The content attribute is not correctly typed inside _before prop.

**Expected Behavior**
According to the documentation, content should be available on _before prop
<img width="573" alt="Screenshot 2020-05-03 at 17 37 20" src="https://user-images.githubusercontent.com/3359248/80918488-950b9900-8d65-11ea-82e0-d14edf798c81.png">

**To Reproduce**
1. Create a PseudoBox Component and try to add content attribute inside _before prop:
<img width="1019" alt="Screenshot 2020-05-03 at 17 37 10" src="https://user-images.githubusercontent.com/3359248/80918516-b9677580-8d65-11ea-86a8-db4f74d7ed57.png">

**Comment by segunadebayo** [comment]
Hi @alfrejivi, kindly upgrade to the recent version.

Thanks
