### ISSUE TITLE
textStyle does not override Heading component or Text component with baseStyles defined

### ISSUE THREAD

**Issue by TomSmedley** [chakra-ui/chakra-ui#6655]
### Description

https://chakra-ui.com/docs/styled-system/text-and-layer-styles#text-styles here highlights a way of consistently defining your brand guideline text styles. However, if you try to use textStyle in a Heading component it doesn't work, if you use it with a Text component that has a baseStyle defined for the default paragraph style it does not override. I believe that textStyle should have higher priority for a clean way of defining text guidelines across components.

### Link to Reproduction

N/A

### Steps to reproduce

1. Defined Text Styles in accordance to the documentation.
2. Apply `textStyle` to `Heading`.
3. Defined a baseStyle for the component Text (for the default paragraph styling).
4. Apply `textStyle` to `Text`.
5. See that `textStyle` doesn't function to override styles.

### Chakra UI Version

2.2.9

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @TomSmedley. This is a duplicate issue from the past, and it's a known one.

For now, Kindly ensure you stick with your predefined text styles or use the `sx` prop, which has the highest specificity.
