### ISSUE TITLE
Popover doesn't toggle on Safari (OSX / iOS)

### ISSUE THREAD

**Issue by TomSmedley** [chakra-ui/chakra-ui#6658]
### Description

https://chakra-ui.com/docs/components/popover clicking on "Trigger" should open and close the popover, however, on Safari it doesn't work and will keep opening

### Link to Reproduction

https://chakra-ui.com/docs/components/popover

### Steps to reproduce

1. Go to Safari on your mobile on mac
2. Click to https://chakra-ui.com/docs/components/popover
3. Scroll down to the example and click the "Trigger" button
4. The popover will not toggle it's open and close state but in fact keep opening

### Chakra UI Version

2.2.9

### Browser

Safari

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Klaha** [comment]
Would this probably be with an specific version of safari?
Just tried it on 

* macOS 12.5 and Safari 15.6 and worked correctly.
* iphone on 15.6.1 and worked correctly.
