### ISSUE TITLE
Chakra CLI fails to generate tokens for a theme package

### ISSUE THREAD

**Issue by AnishDe12020** [chakra-ui/chakra-ui#6659]
### Description

The CLI fails to generate ts tokens when using a theme package

### Link to Reproduction

https://codesandbox.io/p/github/AnishDe12020/orbits-ui-chakra-cli-bug-reproduction/draft/funny-albattani?import=true&file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A22%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A22%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl7t2dgvn0007lmfrbr3qha1v%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fpages%252F_app.tsx%2522%252C%2522%252Fpages%252Findex.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl7t2jnkt01de2v6ie5ptfv7e%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl7t2jmct01al2v6isudby1le%2522%252C%2522isMinimized%2522%253Atrue%257D%252C%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cl7t2fg670014lmfrg7cu2b9p%2522%252C%2522key%2522%253A%2522cl7t2fg3200ho2v6it5bj9lwu%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D

### Steps to reproduce

1. install the chakra cli
2. install `@orbits-ui/chakra-theme`
3. run `yarn chakra-cli tokens "@orbits-ui/chakra-theme"` (same behaviour without quotation marks

### Chakra UI Version

2.3.1 (but irrelevant. chakra cli v2.1.7)

### Browser

brave (latest) but irrelevant

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

![image](https://user-images.githubusercontent.com/63192115/189129701-2313b654-6a6c-4579-a5ba-5da83eb16a63.png)

From the error msg it seems like the cli is looking for a file with the package name

for the csb reproduction, i had to give one that uses csb projects as only that supports a terminal, im not able to figure out how to give write access so you probably gotta fork it

**Comment by Fsss126** [comment]
Came across this issue as well. 

I've looked into the problem to see what produces this error and if it may be due to some misuse of the command. The error occurs if the package name you pass contains `/`. That happens because package name is treated the same way as path to a theme file when trying to resolve tsconfig and is used when building path to the initial directory to start search for tsconfig, but such directory doesn't exist so `configLoader` produces an exception. 

Would appreciate if it will be fixed soon 🙏

**Comment by saipathuri** [comment]
@segunadebayo I'm still running into this issue on `2.4.1`.
