### ISSUE TITLE
[useToast hook] onClose callback doesn't work

### ISSUE THREAD

**Issue by alfrejivi** [chakra-ui/chakra-ui#666]
**Describe the bug**
I'm trying to use the Toast component, and I'd like to trigger an action when the toast closes:

<img width="683" alt="Screenshot 2020-05-03 at 17 48 28" src="https://user-images.githubusercontent.com/3359248/80918649-55917c80-8d66-11ea-8ee0-48232e653bba.png">

**Expected Behavior**
The onClose callback should be triggered when the toast is closed

**To Reproduce**
1. Get the `toast` method using the Hook: `const` toast = useToast();`
2. Call the `toast` method adding the `onClose: () => {}` callback
3. Close the toast clicking on the `close` button displayed on the UI
4. The callback is never triggered

**Comment by mehulcse** [comment]
@segunadebayo Can I raise the PR or is there any work in progress on this? There is one open PR #647 related to `closeAll` toast functionality.
