### ISSUE TITLE
Adding a responsive direction to Stack after setting responsive padding/margin causes the browser to lock up

### ISSUE THREAD

**Issue by benjamincharity** [chakra-ui/chakra-ui#6660]
### Description

I expected performance to be unaffected by styles But have found on long lists, adding a responsive direction crushes the browser

### Link to Reproduction

https://codesandbox.io/s/chakra-stack-direction-render-issue-rnjgsn?file=/src/index.tsx

### Steps to reproduce

1. Go here: https://codesandbox.io/s/chakra-stack-direction-render-issue-rnjgsn?file=/src/index.tsx
2. Uncomment line `24`
3. Notice it takes exponentially longer to render the list.
4. NOTE: If we remove the responsive padding/margins on the same element and _also_ add the direction the problem is _not_ present.

### Chakra UI Version

2.3.2

### Browser

Safari 15.6.1, Chrome Version 105.0.5195.102 (Official Build) (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Thanks for all your hard work on this library!

**Comment by ojotuk** [comment]
Commenting for a wider audience. This issue is applicable to Flex also.

> ### Description
> I expected performance to be unaffected by styles But have found on long lists, adding a responsive direction crushes the browser
> 
> ### Link to Reproduction
> https://codesandbox.io/s/chakra-stack-direction-render-issue-rnjgsn?file=/src/index.tsx
> 
> ### Steps to reproduce
> 1. Go here: https://codesandbox.io/s/chakra-stack-direction-render-issue-rnjgsn?file=/src/index.tsx
> 2. Uncomment line `24`
> 3. Notice it takes exponentially longer to render the list.
> 4. NOTE: If we remove the responsive padding/margins on the same element and _also_ add the direction the problem is _not_ present.
> 
> ### Chakra UI Version
> 2.3.2
> 
> ### Browser
> Safari 15.6.1, Chrome Version 105.0.5195.102 (Official Build) (arm64)
> 
> ### Operating System
> * [x]  macOS
> * [ ]  Windows
> * [ ]  Linux
> 
> ### Additional Information
> Thanks for all your hard work on this library!
