### ISSUE TITLE
`PopoverCloseButton` / Popover content components don't forward Ref

### ISSUE THREAD

**Issue by mayakoneval** [chakra-ui/chakra-ui#6665]
### Description

`React.forwardRef` on `PopoverCloseButton` & other Popover content elements

### Problem Statement/Justification

I was trying to get the `PopoverCloseButton` to capture focus in my Popover using `initialFocusRef`, but the `PopoverCloseButton` doesn't use `React.forwardRef`. 

### Proposed Solution or API

Can we have the button & other popover components use `React.forwardRef`? Is there a reason not to?

**Comment by anubra266** [comment]
@mayakoneval could you create a little codesandbox reproduction if the issue you're facing. This component already has `forwardRef`.
