### ISSUE TITLE
[Modal] SlideIn/Scale child render function type issue

### ISSUE THREAD

**Issue by alfrejivi** [chakra-ui/chakra-ui#667]
**Describe the bug**
When using a Modal with SlideIn/Scale transition, the child function is throwing a type error

<img width="698" alt="Screenshot 2020-05-03 at 17 53 54" src="https://user-images.githubusercontent.com/3359248/80918993-e74db980-8d67-11ea-9100-4e7fa9f2ed15.png">

<img width="983" alt="Screenshot 2020-05-03 at 17 54 27" src="https://user-images.githubusercontent.com/3359248/80918997-ee74c780-8d67-11ea-80d6-fbaeec69a509.png">

**Expected Behavior**
Being able to use SlideIn/Scale child render function without any`type` issue.

**To Reproduce**
1. Create a Modal with a SlideIn/Scale transition
2. Try to use the child function with the `styles` param with no `type` issues

**Comment by with-heart** [comment]
I have verified that the type issue no longer remains in 1.0: https://codesandbox.io/s/condescending-darkness-pb87z?file=/src/App.js
