### ISSUE TITLE
How to disable accesibility outline?

### ISSUE THREAD

**Issue by nfdeak** [chakra-ui/chakra-ui#668]
I tried setting  shadows: {...theme.shadows, outline:'0 !important'} in my theme but nothing changed.

**Comment by segunadebayo** [comment]
Hey @nfdeak,

That's weird. It should work, can you send over a CodeSandbox replica of this?

You can also consider using the `focus-visible` approach here: https://medium.com/@keeganfamouss/accessibility-on-demand-with-chakra-ui-and-focus-visible-19413b1bc6f9

**Comment by nfdeak** [comment]
Hi @segunadebayo ,
Here is a CodeSandbox with a minimal setup of my project and the outline set to 0. Just click the Menu on the right side to see the outline: [link](https://codesandbox.io/s/youthful-faraday-bxg9i?file=/src/App.js)

**Comment by segunadebayo** [comment]
I see what you mean now. The thing is, we don't disable the browser focus styles so you can simply pass `outline=0` to the `MenuButton`

https://codesandbox.io/s/modest-framework-uienj?file=/src/components/Header.js

**Comment by nfdeak** [comment]
But how would I go about making the outline 0 globally? I tried to put `css={css`outline:0}`}` to the root and it's not working.

**Comment by segunadebayo** [comment]
@nfdeak, you can use the `Global` component from emotion to achieve this.

**Comment by shadab14meb346** [comment]
> I see what you mean now. The thing is, we don't disable the browser focus styles so you can simply pass `outline=0` to the `MenuButton`
> 
> https://codesandbox.io/s/modest-framework-uienj?file=/src/components/Header.js

In my case outline="0 !important got worked"

**Comment by hirooutdoor** [comment]
Now, it's available with style props like `_focus={{_focus: "none"}}`, right?

```
<IconButton
          _focus={{_focus: "none"}}
          aria-label="DarkMode Switch"
          icon={colorMode === 'light' ? <MoonIcon /> : <SunIcon />}
          onClick={toggleColorMode}
        />
```

**Comment by cbdeveloper** [comment]
This is what I'm doing for my inputs.
But it would be nice to opt-out of this out-of-the-box.

```
import type { ComponentStyleConfig } from '@chakra-ui/theme';

export const InputStyles: ComponentStyleConfig = {
  variants: {
    outline: {
      field: {
        padding: 3,
        _focus: {
          boxShadow: 'none',
          borderColor: 'inherit',
        },
        _hover: {
          boxShadow: 'none',
          borderColor: 'inherit',
        },
      },
    },
  },
};
```

And on my theme, I'm doing:

```
import { extendTheme } from '@chakra-ui/react';
import { InputStyles } from 'chakra.ui';

export const theme = extendTheme({
  components: {
    Input: InputStyles,
  },
});
```

**Comment by Jarrodsz** [comment]
Any update on how to disable this?
This should be a flag true, false in the theme config!
