### ISSUE TITLE
Issue loading Remix Links tags at the same time as chakra-ui styles

### ISSUE THREAD

**Issue by aaacafe786** [chakra-ui/chakra-ui#6686]
### Description

i installed chakra-ui as per: https://chakra-ui.com/getting-started/remix-guide, i also have css files that i am importing using the remix ```<Links>``` function. the styles are loaded at different times, causing a flash of unstyled content. furthermore, i cannot prepend the chakra styles above the remix links, the "prepend" option createCache({ key: 'css', prepend: true }) does nothing 

### Link to Reproduction

https://pr-101-osc-ecommerce.fly.dev/

### Steps to reproduce

1. Go to homepage: 
2. throttle to slow 3g
3. reload page

### Chakra UI Version

2.2.6

### Browser

Google chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Please follow the issue template as we cannot act on issues that lack important information.

**Comment by aaacafe786** [comment]
Morning mate, i can see that the issue i posted on github is closed, would you be alright with me making a new one with all the info i sent to you in this thread
