### ISSUE TITLE
[FAQ] Chakra UI + Framer Motion

### ISSUE THREAD

**Issue by segunadebayo** [chakra-ui/chakra-ui#669]
Hey Chakra family,

If you'd like to add some interesting motion interaction or animation to your Chakra UI websites or apps, here's a quick tip:

```jsx
import {  Box } from "@chakra-ui/core";
import { motion } from "framer-motion";

// 1. Create a custom motion component from Box
const MotionBox = motion.custom(Box);

// 2. You'll get access to `motion` and `chakra` props in `MotionBox`
function Example(){
  return (
       <MotionBox
          size="40px"
          bg="red.300"
          drag="x"
          dragConstraints={{ left: -100, right: 100 }}
          whileHover={{ scale: 1.1 }}
          whileTap={{ scale: 0.9 }}
        />
  )
}
```

// 3. Add some awesome transitions to your apps 🥳

Hope you all find this useful.

PS: I'm happy to merge a PR that adds this to the Recipes in the docs.

Cheers.

**Comment by nicolastoulemont** [comment]
I'm having some issue with framer-motion props being passed to the DOM when composing chakra-ui component and motion.custom() as shown here.

[code-sandbox example](https://codesandbox.io/s/shy-resonance-byife?file=/src/Logo.tsx).

I would like to point out that, in production those props are lower cased and don't cause any issues. But they are still passed to the DOM as such (from another example) : `<a class="chakra-link css-1s1imuf" initial="[object Object]" animate="[object Object]" whilehover="[object Object]" whiletap="[object Object]" href="/dummy-link" style="opacity: 1; transform: none;"><div class="css-1ukvcs0"></a>`

Which is not optimal, but I don't know if anything can be done about it. 😄

**Comment by oschade** [comment]
@nicolastoulemont 
You can use framer-motion like:

`const MotionBox = chakra(motion.div)`

**Comment by nicolastoulemont** [comment]
> @nicolastoulemont
> You can use framer-motion like:
> 
> `const MotionBox = chakra(motion.div)`

Thank you very much, it does fix this issue !

**Comment by Dantonyswamy** [comment]
Hi, 
I am having an issue when I tries to use framer motion example for typescript. The `<Example />` component is not showing with specified background color
Here is my component file in `src/Example.tsx`
```
import React from "react"
import { Box, BoxProps } from '@chakra-ui/layout';
import { motion } from 'framer-motion';

export const MotionBox = motion<BoxProps>(Box);

const Example= () => {
  return (
  <>
    <MotionBox
      height="100px"
      bg="red.100"
      drag="x"
      dragConstraints={{ left: -100, right: 100 }}
      whileHover={{ scale: 1.1 }}
      whileTap={{ scale: 0.9 }}
      />
      <Box>This is a Motion Box</Box>
      </>
  )
}

  export default Example;
  ```
  and here how I am importing the component in my `src/App.tsx` :
  ```
  import * as React from "react"
import {
  ChakraProvider,
  Box,
  VStack, 
  Grid,
  theme
} from "@chakra-ui/react"
import { ColorModeSwitcher } from "./ColorModeSwitcher"
import Example from "./Example";

export const App = () => (
  <ChakraProvider theme={theme}>
    <Box textAlign="center" fontSize="xl" background="blue.100">
      <Grid minH="100vh" p={3}>
        <ColorModeSwitcher justifySelf="flex-end" />
        <VStack spacing={8}>
       <Example />         
        </VStack>
      </Grid>
    </Box>
  </ChakraProvider>
)
```
And UI is rendering like this:
![image](https://user-images.githubusercontent.com/46323214/131224003-16e5faec-8b68-4dd9-ad7e-d174b94e8e42.png)

I could understand what I am doing wrong??
