### ISSUE TITLE
Default/Out of the box chakra ui styles not being applied 

### ISSUE THREAD

**Issue by devlukedreamstage** [chakra-ui/chakra-ui#6690]
### Description

When I wrap my app in ChakraProvider, the default charka styles dont get applied

### Link to Reproduction

Cannot reproduce, code would look just like the example

### Steps to reproduce

1.Open NextJS app
2. Wrap <Component /> in _app.tsx in ChakraProvider
3. No styles are being applied except for light mode, dark mode

### Chakra UI Version

2.3.2

### Browser

Chr

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

When I wrap an imported component in its own ChakraProvider, it gets styles applied even while keeping the whole app wrapped in the provider

I also noticed this error when theres only one ChakraProvider: `You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.`

**Comment by segunadebayo** [comment]
I'm sorry, but we don't understand the problem you are reporting.

Please provide a repository or CodeSandbox reproducing this problem, and describe the difference between the expected and current behavior.
