### ISSUE TITLE
Regression: since @chakra-ui/react@2.8.9, using `onEdit` with `onChange` in Editable causes text selection on every keystroke

### ISSUE THREAD

**Issue by jessicalc** [chakra-ui/chakra-ui#6693]
### Description

When I upgraded to 2.2.9, our `<Editable>` implementation, which used `onChange` and `onEdit`, broke - every time I typed a character into the field, it would trigger a selection of all the text and type over it. 

### Link to Reproduction

https://codesandbox.io/s/dazzling-babycat-djo67m?file=/src/index.tsx

### Steps to reproduce

When I upgraded to 2.2.9, our `<Editable>` implementation, which used `onChange` and `onEdit`, broke - every time I typed a character into the field, it would trigger a selection of all the text and type over it. 

1. Go to https://codesandbox.io/s/gifted-pond-z7ms0e?file=/src/index.tsx (using @chakra-ui/react@2.2.8). This represents a simplified version of our in-app implementation of `<Editable>` with `onChange` and `onEdit` handlers. 
2. Type characters into the input field. Observe that it works!  
![2 2 8](https://user-images.githubusercontent.com/729524/190245984-3404d58f-4a79-4566-9f77-c3527e778578.gif)
3. Now, go to https://codesandbox.io/s/dazzling-babycat-djo67m?file=/src/index.tsx (using @chakra-ui/react@2.2.9). 
4. Type characters into the input field. Observe that they eat themselves. 
![2 2 9](https://user-images.githubusercontent.com/729524/190246232-36218d4c-c19d-4d2c-9b07-9c42369a6f5c.gif)

The only difference between these two code sandboxes is the Chakra UI version. 

It's entirely possible, by the way, that we weren't using the handlers properly in our original implementation. I wanted to flag this because we didn't change anything about our code and observed a regression from upgrading our Chakra UI version.

Thank you :) 

### Chakra UI Version

2.2.9

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by jessicalc** [comment]
Thank you so much, @segunadebayo! Have a beautiful week.
