### ISSUE TITLE
Heading: custom line height has lower priority than default 

### ISSUE THREAD

**Issue by ivan-kleshnin** [chakra-ui/chakra-ui#6695]
### Description

The `lineHeight` setting below is ignored (or has too low priority):

```ts
extendTheme({
  components:
    Heading: {
      baseStyle: {
        color: "red",       // 👍 correctly overrides the default
        lineHeight: "1.25", // 👎 is overriden by the default 1.33 (or 1.2 on smaller screens)
      }
    }
  }
})
```

### Steps to reproduce

1. Watch the video:
https://user-images.githubusercontent.com/2128182/190352359-c172eb7c-5d70-4902-9a9b-3add08508866.mp4

2. Check the sandbox: https://codesandbox.io/s/currying-architecture-1ukwmz?file=/src/index.tsx

### Chakra UI Version

Tested in `@chakra-ui/react@2.2.3` and `@chakra-ui/react@2.3.2`

### Browser

Does not matter

### Operating System

Does not matter

---

There're multiple other ways to set the line height so it's not a blocker, but the above approach has to work.

Default line height is responsive (1.33 on large screens, 1.2 on small). I don't mind about any defaults but I don't want Chakra to be too smart and control  my customized line heights in any way.

**Comment by nvmnghia** [comment]
maybe it's controlled by the `sizes`?

**Comment by nvmnghia** [comment]
> Yes, it can be controlled per `size`. And in real world you rather want different line heights for different font sizes (because the # of chars per line is smaller for larger letters). But the existence of a workaround does not nullify the original issue.

I believe this is the intended way of customising in Chakra. Doing what you requested could be a breaking change.

**Comment by matthewrose** [comment]
Can you not `null` the line height set by the size and instead set via heading. That is what I am doing. Granted I set all my line heights and font sizes using `textStyle`...

**Comment by ivan-kleshnin** [comment]
> I believe this is the intended way of customising in Chakra. Doing what you requested could be a breaking change.

You mean there're default sizes in Chakra that override my `baseStyle`. 
Yeah, looking at this today I think you're right. Closing.

**Comment by bhardy** [comment]
@ivan-kleshnin in our system we use unitless line-heights which are the same value for every font-size. this setup requires us to drop that same value onto each item in the `sizes` property while theming. My expectation was that if you set a line-height on the baseStyle it should override all the chakra defaults for sizes

**Comment by ivan-kleshnin** [comment]
> in our system we use unitless line-heights which are the same value for every font-size

Smaller fonts should have proportionally increased line heights and Larger fonts should have proportionally decreased LH.
Because for smaller font you'll have more characters per line and vice-versa. More characters per-line => harder to read => requires more interline spacing.
