### ISSUE TITLE
Hydration failure in MeteorJS

### ISSUE THREAD

**Issue by laakal** [chakra-ui/chakra-ui#6696]
### Description

Hydration failed because the initial UI does not match what was rendered on the server.

### Link to Reproduction

Not possible(Meteorjs)

### Steps to reproduce

<img width="659" alt="Screen Shot 2022-09-15 at 13 54 39" src="https://user-images.githubusercontent.com/9221304/190386480-74b84c67-a1c5-41cc-be20-1a8d3c7b5d2d.png">

Code where the error occurred:
```js
// src/link.tsx
var Link = forwardRef14(function Link2(props, ref) {
  const styles = useStyleConfig8("Link", props);    // <-- Error location
  const { className, isExternal, ...rest } = omitThemingProps8(props);
  return /* @__PURE__ */ React.createElement(chakra13.a, {
    target: isExternal ? "_blank" : void 0,
    rel: isExternal ? "noopener" : void 0,
    ref,
    className: cx8("chakra-link", className),
    ...rest,
    __css: styles
  });
});
Link.displayName = "Link";
```

### Chakra UI Version

v2.2.9

### Browser

Google Chrome v105

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by mikemajara** [comment]
Can you explain how you solved this so people can get some guidance?

**Comment by laakal** [comment]
@mikemajara  This issue is relevant to MeteorJS not  chakra ui. Check [link](https://github.com/meteor/meteor/issues/12185)
