### ISSUE TITLE
Modal Lag / Stutter with ModalOverlay

### ISSUE THREAD

**Issue by DmacMcgreg** [chakra-ui/chakra-ui#6699]
### Description

When opening the modal component, there is quite a considerable lag/stuttter/delay/drop in frame rate.

### Link to Reproduction

https://chakra-ui.com/docs/components/modal#block-scrolling-when-modal-opens

### Steps to reproduce

1. Go to Link
2. Click on Open Modal button
3. Notice lag

if you don't notice any lag, try a 4x slowdown of CPU in the chrome performance panel by clicking the gear icon.

I first noticed it when my computer was running too many programs (Latest MacOS, i7 Intel Macbook Pro 16" 2019)
I also notice it in an app with 2 Layers of Nested Tabs.

In the docs it seems to perform just okay, but in a real app, it does slow down quite a lot!

Check out this example from my app:
![CleanShot 2022-09-15 at 12 58 01](https://user-images.githubusercontent.com/3266023/190451426-60bd0d0a-9d66-4dec-b2a5-75b7d122b544.gif)

Here it is without the Overlay
![CleanShot 2022-09-15 at 13 00 58](https://user-images.githubusercontent.com/3266023/190452091-17318984-f9ab-4671-b2cf-70f7349974d8.gif)

### Chakra UI Version

2.2.9

### Browser

Google Chrome 105

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Perhaps related to this ticket?
https://github.com/chakra-ui/chakra-ui/issues/6249

**Comment by segunadebayo** [comment]
Hi @DmacMcgreg,

This has been fixed in a recent PR. It's a regression from an existing PR.

We'll publish an update soon

**Comment by DmacMcgreg** [comment]
@segunadebayo 
This still seems to be a problem
I'm seeing a lot of clunky-ness with the modal component. Check out the docs. With or without overlay
https://chakra-ui.com/docs/components/modal

I'm using Chrome 107, Mac os ventura 13.0, core i7 macbook pro 2019

**Comment by frsmlk** [comment]
This has not been fixed. I'm also noticing lag if i scroll within the modal.
