### ISSUE TITLE
[Drawer] Use a fixed opacity for the drawer body

### ISSUE THREAD

**Issue by fernandobandeira** [chakra-ui/chakra-ui#67]
![Screen Shot 2019-09-11 at 02 41 50](https://user-images.githubusercontent.com/8373980/64671179-f7fa9980-d43d-11e9-9a4c-719651a88954.png)

As you can see, since the opacity animation is also being applied to the drawer, it ends up making the text overlap with the topnav while the drawer is being opened, I think we could make it so the overlay opacity doesn't apply to the drawer body, this way it'd always be solid, what are your thoughts on this?

**Comment by segunadebayo** [comment]
@fernandobandeira , I agree. I'll work on this.

**Comment by segunadebayo** [comment]
Hi Fernando,

I've released a new version of Chakra that resolves this. Kindly upgrade
