### ISSUE TITLE
Request to add autosizing to Textarea

### ISSUE THREAD

**Issue by chrysb** [chakra-ui/chakra-ui#670]
**Is your feature request related to a problem? Please describe.**
This is a pretty standard feature for textareas nowadays

**Describe the solution you'd like**
Simply add `maxRows` and `minRows` as props, and auto-grow/shrink with content

**Describe alternatives you've considered**
Currently going to have to implement `react-textarea-autosize` and figure out how to do the styling independent of Chakra 😢

**Comment by santialbo** [comment]
For anyone needing this you can achieve the result using [autosize](https://www.npmjs.com/package/autosize).
Just add the following `useEffect` hook.
```
useEffect(() => {
    autosize(ref.current!);
    return () => {
      autosize.destroy(ref.current!);
    };
  }, []);
```
A few notes:
- Chakra is adding a default min-height and height. If you need it to be smaller than default you need to override those values.
- You need to disable css transitions otherwise you will see the scrollbar visible during the transition which looks uglier than no transition

**Comment by segunadebayo** [comment]
Here's a solution I used recently on a project.

```jsx
import { Textarea } from "@chakra-ui/core";
import ResizeTextarea from "react-textarea-autosize";
import React from "react";

export const AutoResizeTextarea = React.forwardRef((props, ref) => {
  return (
    <Textarea
      minH="unset"
      overflow="hidden"
      w="100%"
      resize="none"
      ref={ref}
      minRows={1}
      as={ResizeTextarea}
      {...props}
    />
  );
});
```

Hope you find this useful.

**Comment by mauryakrishna** [comment]
> Here's a solution I used recently on a project.
> 
> ```js-jsx
> import { Textarea } from "@chakra-ui/core";
> import ResizeTextarea from "react-textarea-autosize";
> import React from "react";
> 
> export const AutoResizeTextarea = React.forwardRef((props, ref) => {
>   return (
>     <Textarea
>       minH="unset"
>       overflow="hidden"
>       w="100%"
>       resize="none"
>       ref={ref}
>       minRows={1}
>       as={ResizeTextarea}
>       {...props}
>     />
>   );
> });
> ```
> 
> Hope you find this useful.

Thanks a lot. It was smooth.  But I wanted to restrict the number of rows while dynamically increasing the rows. Can you help me out on this?

**Comment by hichana** [comment]
@segunadebayo solution works great, but note that unless you disable css transitions as proposed by @santialbo , you get the text jumping up and down a bit when typing and getting a new line. Simply add `transition="height none"` to the <Textarea component above.

**Comment by fandy** [comment]
> Here's a solution I used recently on a project.
> 
> 
> 
> ```jsx
> 
> import { Textarea } from "@chakra-ui/core";
> 
> import ResizeTextarea from "react-textarea-autosize";
> 
> import React from "react";
> 
> 
> 
> export const AutoResizeTextarea = React.forwardRef((props, ref) => {
> 
>   return (
> 
>     <Textarea
> 
>       minH="unset"
> 
>       overflow="hidden"
> 
>       w="100%"
> 
>       resize="none"
> 
>       ref={ref}
> 
>       minRows={1}
> 
>       as={ResizeTextarea}
> 
>       {...props}
> 
>     />
> 
>   );
> 
> });
> 
> ```
> 
> 
> 
> Hope you find this useful.

Thank a lot! I really enjoy this library.

**Comment by Josscii** [comment]
> Here's a solution I used recently on a project.
> 
> ```js
> import { Textarea } from "@chakra-ui/core";
> import ResizeTextarea from "react-textarea-autosize";
> import React from "react";
> 
> export const AutoResizeTextarea = React.forwardRef((props, ref) => {
>   return (
>     <Textarea
>       minH="unset"
>       overflow="hidden"
>       w="100%"
>       resize="none"
>       ref={ref}
>       minRows={1}
>       as={ResizeTextarea}
>       {...props}
>     />
>   );
> });
> ```
> 
> Hope you find this useful.

for any one who wants a **typescript** version:

```typescript
import { Textarea, TextareaProps } from "@chakra-ui/react";
import ResizeTextarea from "react-textarea-autosize";
import React from "react";

export const AutoResizeTextarea = React.forwardRef<
  HTMLTextAreaElement,
  TextareaProps
>((props, ref) => {
  return (
    <Textarea
      minH="unset"
      overflow="hidden"
      w="100%"
      resize="none"
      ref={ref}
      minRows={1}
      as={ResizeTextarea}
      {...props}
    />
  );
});
```

**Comment by Lschulzes** [comment]
```
const [value, setValue] = useState('');

const handleMessageValueChange = (e: ChangeEvent<HTMLTextAreaElement>) => { 
setValue(e.target.value);
};

<Box position="relative">
<Textarea
onChange={handleValueChange} 
value={value ?? ''}
w="full"
h="full"
position="absolute"
overflow="hidden"
resize="none"
size="lg" 
/>

<Textarea visibility="hidden" size="lg" as="div" whiteSpace="pre-wrap" h="auto">
{value}
{value.charAt(value.length - 1) === '\n' && '\n'}
</Textarea>
</Box>
```

**Comment by cbdeveloper** [comment]
@Josscii and @mauryakrishna 

Should we use `fowardRef` from `chakra` instead of `React` ?

https://chakra-ui.com/community/recipes/as-prop#option-1-using-forwardref-from-chakra-uireact

**Comment by lgj9172** [comment]
```
import ResizeTextarea from "react-textarea-autosize";
import React from "react";
import { Textarea, forwardRef } from "@chakra-ui/react";

export const AutoResizeTextarea = forwardRef((props, ref) => (
  <Textarea
    minH="unset"
    overflow="hidden"
    w="100%"
    resize="none"
    ref={ref}
    minRows={3}
    as={ResizeTextarea}
    {...props}
  />
));

```

Be happy with this version!

**Comment by dm3yb** [comment]
I found a pretty simple solution using only CSS. I hope it will help you:

```
const styles = css`
  .chakra-textarea {
    field-sizing: content !important; // auto-expanding textarea's
    height: initial !important; // reset preset chakra height 
  }
`

export const ComponentName = ({}) => {
  return (
   <VStack css={styles}>
     <Textarea />
   <VStack/>
  )
}
```

**Comment by jpenna** [comment]
> I found a pretty simple solution using only CSS. I hope it will help you:
> 
> ```tsx
> const styles = css`
>   .chakra-textarea {
>     field-sizing: content !important; // auto-expanding textarea's
>     height: initial !important; // reset preset chakra height 
>   }
> `
> 
> export const ComponentName = ({}) => {
>   return (
>    <VStack css={styles}>
>      <Textarea />
>    <VStack/>
>   )
> }
> ```

This is awesome! I made it without a wrapper component:

```jsx
        <Textarea
          height="initial"
          sx={{ 'field-sizing': 'content' }}
        />
```


Unfortunatelly, as of today, the `field-sizing` CSS property isn't supported by Safari or Firefox...
