### ISSUE TITLE
Responsive properties make app extremely slow

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#6702]
### Description

With Chakra 2 & React 18, when I add several responsive properties to a component the app becomes extremely slow. This was not happeing with React 17 & Chakra 1.

### Link to Reproduction

https://codesandbox.io/s/hopeful-roman-itrq3v?file=/pages/index.tsx

### Steps to reproduce

1. Go to the reproduction
2. Codesandbox is not even able to display the app as it is too slow.

Try removing responsive properties and the app will load fast.

### Chakra UI Version

2.2.8

**Comment by segunadebayo** [comment]
Most likely caused by https://github.com/chakra-ui/chakra-ui/pull/6335/files. Please revert for now @anubra266

**Comment by lcswillems** [comment]
Thanks for the fast answer!

**Comment by lcswillems** [comment]
I can confirm the issue is not present in 2.2.6
