### ISSUE TITLE
Imported fonts are not applied in theme.js (NextJs typescript)

### ISSUE THREAD

**Issue by alessiogmonti** [chakra-ui/chakra-ui#6708]
### Description

Importing the font exactly as stated in the documentation does not work.

### Link to Reproduction

no

### Steps to reproduce

- Install this font: https://fontsource.org/fonts/space-grotesk: `yarn add @fontsource/space-grotesk`
- `import '@fontsource/space-grotesk'`  in _app.tsx
- define fonts in theme.js :
    `const fonts = { Heading: "Space Grotesk",
                               Button: "Space Grotesk" }`
- add to extendTheme : `const theme = extendTheme({ fonts, ...}`
- add to ` <ChakraProvider theme={theme}>` in _app.tsx

Followed the steps in the documentation exactly. I know theme is being applied correctly because other styling works fine, but fonts don't. It's not the font in particular because it works as an inline style (`<Heading fontFamily='Space Grotesk' />`).

### Chakra UI Version

2.2.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by ali-idrizi** [comment]
This works fine on my end if I replace `Heading` with `heading`. So try: 

```
const fonts = { heading: "Space Grotesk" }
```
