### ISSUE TITLE
Include "as" in Chakra-UI components properties

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#6710]
### Description

Currently, we need to use Chakra-UI custom forwardRef in order to pass the "as" property to child component. From reading the coding, I don't see a reason why "as" should not be included in Chakra-UI components properties.

### Problem Statement/Justification

Currently, we need to use Chakra-UI custom forwardRef in order to pass the "as" property to child component. Would be nice if we don't have to do this.

### Proposed Solution or API

Include "as" in Chakra-UI components properties.

**Comment by anubra266** [comment]
You don't need `forwardRef` to use `as`. And chakra `forwardRef` does exactly what the native `React.forwardRef` does, it's just extended for more friendly types - typescript.
https://github.com/chakra-ui/chakra-ui/blob/ef722cac8d1428bcca636c10ce5c2f95cb324b11/packages/components/system/src/forward-ref.tsx#L18

**Comment by lcswillems** [comment]
Hi @anubra266 

The wording of my issue was misleading. I rather wanted to say that by looking at Chakra-UI forwardRef I saw that the "as" property was not included by default in components props.

It is not clear in my case what I should do to add it to my component and, by reading Chakra-UI codebase, I don't see a reason why the "as" property is not included by default.

I rephrased the issue message above

**Comment by anubra266** [comment]
@lcswillems it's included in the types for all components though.

**Comment by anubra266** [comment]
@lcswillems it's included in the types for all components though.

**Comment by lcswillems** [comment]
That's true... I will dig in and let you know if I succeed to identify what feels wrong for me. Thanks for your help!
