### ISSUE TITLE
NumberInput field acting crazy on right mouse click

### ISSUE THREAD

**Issue by rome2o** [chakra-ui/chakra-ui#6711]
### Description

When I clicked the number field with my right mouse click, the number kept going up as if it's incrementing upon focus of right mouse click.

### Link to Reproduction

https://chakra-ui.com/docs/components/number-input

### Steps to reproduce

1. Go to the link mentioned above.
2. Right click on up or down arrow
2. See error

https://www.awesomescreenshot.com/video/11155272?key=42a15fe1eaf74e50d78c554f73adc18c

### Chakra UI Version

Latest

### Browser

Brave Browser

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by joaosantos99** [comment]
Can I take this issue?

**Comment by rome2o** [comment]
Hi there,

I've figured out a fix for this. 

Just add the following

```
 onContextMenu={(e) => ( e.preventDefault())}
 ```

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
