### ISSUE TITLE
forwardRef expects variable declaration

### ISSUE THREAD

**Issue by rackodo** [chakra-ui/chakra-ui#6712]
### Description

I'm trying to create a custom component for MenuButton, but the example code is producing an error.

### Link to Reproduction

https://codesandbox.io/s/twilight-rgb-z3uqs4?file=/pages/index.js

### Steps to reproduce

1. Copy Option 1's example code from [this doc page](https://chakra-ui.com/community/recipes/as-prop#option-1-using-forwardref-from-chakra-uireact) and use Card.
2. Receive error.

### Chakra UI Version

2.3.2

### Browser

Firefox 104.0.2

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @rackodo,

That example assumes you're using TypeScript. Here's what a JavaScript version would look like:

```js
const Card = forwardRef((props, ref) => (
  <Box px="4" py="5" rounded="sm" shadow="lg" ref={ref} {...props} />
));
```

https://codesandbox.io/s/confident-chatterjee-jqzock?file=/pages/index.js
