### ISSUE TITLE
useRangeSlider defaultValue type does not match RangeSlider component defaultValue

### ISSUE THREAD

**Issue by Abdelatief** [chakra-ui/chakra-ui#6713]
### Description

when I try to use the useRangeSlider hook and destructure the getRootProps that is returned from the hook to the RangeSlider component. expected that the returned props type match the RangeSlider props type but types does not match, specifically the defaultValue prop

### Link to Reproduction

https://codesandbox.io/s/condescending-dream-j2pchn?file=/src/index.tsx

### Steps to reproduce

1. pass a getRootProps that is returned from the useRangeSlider hook to the RangeSlider component and a type error will occur

### Chakra UI Version

2.2.9

### Browser

Firefox v104.0.1 64bit

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Hi @Abdelatief,

This is an incorrect usage of the RangeSlider component. You shouldn't use both `useRangeSlider` and `RangeSlider` simultaneously. That explains why you're running into this.

`useRangeSlider` should be used when working on custom range sliders.

Kindly refactor the code on your end.
