### ISSUE TITLE
Console.log in expand-responsive

### ISSUE THREAD

**Issue by torleifhalseth** [chakra-ui/chakra-ui#6715]
### Description

Console.log in expand-responsive

### Link to Reproduction

none

### Steps to reproduce

Console log: 
https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/styled-system/src/utils/expand-responsive.ts#L61

### Chakra UI Version

2.3.3

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Note: I tried to fork the project to remove the console.log myself but for some reason, the code does not contain the console when I clone it locally 🤷 Any tips?

**Comment by saifbechan** [comment]
Having the exact same issue with version 2.3.2.

**Comment by daniele-sarnari-blinkoo** [comment]
same, revert to 2.3.2 for now

**Comment by segunadebayo** [comment]
Fixed. Will release an update shortly
