### ISSUE TITLE
please remove this redundant debug log

### ISSUE THREAD

**Issue by coverlv** [chakra-ui/chakra-ui#6718]
### Description

file: https://github.com/chakra-ui/chakra-ui/blob/%40chakra-ui/react%402.3.3/packages/components/styled-system/src/utils/expand-responsive.ts#L61

```tsx
  console.log("computedStyles :>> ", computedStyles) // <- this line
  return computedStyles
```

### Problem Statement/Justification

so many logs on console

### Proposed Solution or API

remove this logging code

**Comment by coverlv** [comment]
maybe a temporary solution?

```tsx
const log = console.log;
console.log = (str, ...args) => {
  if (str === 'computedStyles :>> ') return;
  return log(str, ...args);
};
```

**Comment by GhostSlayer** [comment]
Indeed interesting that there is no further testing before pushing stuff to releases. Well it's nothing of a big issue :D maybe a lil bit annoying though

**Comment by GhostSlayer** [comment]
This was already fixed btw https://github.com/chakra-ui/chakra-ui/commit/ab1c42f501a95bdb44ceca796f24a83aa0661868
