### ISSUE TITLE
ComputedStyles logged every render 

### ISSUE THREAD

**Issue by plopez062500** [chakra-ui/chakra-ui#6719]
### Description

When a page in rendered ComputedStyles object is logged to the console. This was happening on version 2.3.3. Reverting to 2.3.2 fixed the issue. Possibly someone left a console.log() in the source?

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-typescript-pomi8?file

### Steps to reproduce

1. Create a react project.
2. Install and setup chakra-ui.
3. Render a page in the browser and view the console.

### Chakra UI Version

2.3.3

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by capaj** [comment]
yes, it is here

![image](https://user-images.githubusercontent.com/1305378/191023687-4a733e95-1733-4007-9382-0eda776b711e.png)


please please can we get a patch release?

**Comment by segunadebayo** [comment]
Fixed. Will release an update shortly
