### ISSUE TITLE
`__css` not taken into account by `<LinkBox />`

### ISSUE THREAD

**Issue by martinezleoml** [chakra-ui/chakra-ui#6720]
### Description

When I pass `__css` prop to `<LinkBox />`, I expect properties to be taken into account.

The use case is to be able to replace each `<Td>` of a table line by `<LinkBox as="td">` to make the whole line clickable, **while conserving `Table` styling** (thanks to `useTableStyles()` hook):

```typescript
function ClickableTd({children, ...restProps}: TableCellProps) {
  const styles = useTableStyles();

  return <LinkBox as="td" __css={styles.td} {...restProps}>{children}</LinkBox>;
}
```

### Link to Reproduction

Here is a repro illustrating the use case:

https://codesandbox.io/s/inspiring-stitch-elhgvb

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.3.3

### Browser

Google Chrome 105.0.5195.125 (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @martinezleoml,

Please use the `sx` prop for this. `__css` is consumed by LinkBox already.
