### ISSUE TITLE
Some Chakra CSS variables are not defined without JavaScript 

### ISSUE THREAD

**Issue by Mattinton** [chakra-ui/chakra-ui#6727]
### Description

When I disable JavaScript on my web app I expect all the CSS variables to be defined.

### Link to Reproduction

https://chakra-ui.com/blog

### Steps to reproduce

1. Go to 'https://chakra-ui.com/blog'
2. Disable JavaScript for that page
3. Observe that `var(--chakra-colors-chakra-border-color)` is not defined. Neither is `var(--chakra-colors-chakra-body-bg)`.

### Chakra UI Version

Latest?

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Discovered this while working on a Remix project and trying to support a no JavaScript experience.

**Comment by segunadebayo** [comment]
Hi @Mattinton, Currently, JS is required for the global style injection to work correctly.

Since we use Emotion under the hood, you can set up the [CacheProvider](https://emotion.sh/docs/cache-provider) to extract styles in SSR, so it works as expected.
