### ISSUE TITLE
add event to useNumberInput onChange callback

### ISSUE THREAD

**Issue by upeguiborja** [chakra-ui/chakra-ui#6729]
### Description

Allow the caller to parse or use the raw event emitted by the `Input` element when using the useNumberInput hook.

### Problem Statement/Justification

When using the useNumberInput hook along with libraries that expect for example a `ChangeEvent<HTMLNumberInput>` like formik the current handler comes short as it just provides `valueAsString` and `valueAsNumber`.

### Proposed Solution or API

Modify the signature and implementation of the `useNumberInput` `onChange` config prop to include the event. From `onChange: (valueAsString: string, valueAsNumber: number): void` to `onChange: (valueAsString: string, valueAsNumber: number, event: ChangeEvent<HTMLInputElement>): void` or a more generic one.

### Additional Information

https://formik.org/docs/api/formik#handlechange-e-reactchangeeventany--void

**Comment by segunadebayo** [comment]
Hi @upeguiborja,

Consider passing the `onChange` handler to the `getInputProps` instead. That'll give you a proper interface to formik.
