### ISSUE TITLE
Accordion - allowMultiple, allowToggle without defaultIndex

### ISSUE THREAD

**Issue by jimmi-rbn** [chakra-ui/chakra-ui#6734]
### Description

Warning in console when allowMultiple, allowToggle without setting defaultIndex

### Link to Reproduction

https://codesandbox.io/s/muddy-brook-eiq1lp?file=/src/index.js

### Steps to reproduce

Insert accordion from chakra example.
Set allowMultiple, allowToggle without defaultIndex and open console.

This example from chakra-ui documentation has the same but without any warnings.
https://chakra-ui.com/docs/components/accordion/usage#accessing-the-internal-state

### Chakra UI Version

2.3.4

### Browser

105

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@jimmi-rbn This warning for `allowToggle` is expected as there's no need for `allowToggle` when `allowMultiple` is true.
<img width="569" alt="CleanShot 2022-09-21 at 10 19 29@2x" src="https://user-images.githubusercontent.com/30869823/191466709-0f540454-71d9-40fb-9d88-045aae62ab36.png">

I'll look into the `allowMultiple` log though
