### ISSUE TITLE
`<Button as="div" isDisabled />` not disabled

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#6736]
### Description

`<Button as="div" isDisabled>Button</Button>` is not disabled. It was working with Chakra-UI 1.8.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-typescript-pomi8?file=/src/index.tsx

### Chakra UI Version

2.3.4

**Comment by noobinthisgame** [comment]
Hey, @lcswillems thanks for reaching out :) 

This behavior seems to be coming from changes we did in 2.3.3:

https://chakra-ui.com/changelog/2.3.3#chakra-uistyled-system232
https://github.com/chakra-ui/chakra-ui/pull/6700

I'll take a look at this.
