### ISSUE TITLE
ComponentWithSkeleton Utility Package

### ISSUE THREAD

**Issue by Distortedlogic** [chakra-ui/chakra-ui#6746]
### Description

A Side package called say `@chakra-ui/skeleton-components` which contains chakra components with builtin skeletons, i.e. something like

```
<TextWithSkeleton isLoaded={isLoaded} textAlign="center" noOfLines={1}>
        {meme?.title}
      </TextWithSkeleton>
```

### Problem Statement/Justification

When I have a component thats intended to be skeletonized while awaiting data fetching, the component becomes bloated with skeletons wrapping everything. This particularly applies with images as if I set the skeleton wrapper hieght and width it applies to children such as an image. So to work around that, I use conditionals which is even uglier bloating.

To avoid above, I started creating such components as `TextWithSkeleton` and this has helped a ton with readability and believe its worth of consideration for someone to make a full blown chakra utility package like this. What I have is def not generic enough to become a seed for the package, nor do I know enough chakra internals to do it.

### Proposed Solution or API

```
<TextWithSkeleton isLoaded={isLoaded} >
  {meme?.title}
</TextWithSkeleton>

<ImageWithSkeleton
        isLoaded={isLoaded}
        src={meme?.url}
       SkeletonHieght="150px"
       SkeletonWidth="250px"
/>


```

### Alternatives

I already have made my own components for my project that do this.

### Additional Information

Just throwing out there for consideration

**Comment by anubra266** [comment]
Hi @Distortedlogic It would be high maintenance to have Higher order components like this in chakra. You could make a recipe package that does this, and consume in your projects, it'll also be a contribution to open source that other developers can use.
