### ISSUE TITLE
Checkbox values not being considered when overriding the theme

### ISSUE THREAD

**Issue by michelecocuccio** [chakra-ui/chakra-ui#6749]
### Description

When trying to override some property of Checkbox using the them, they are ignored

### Link to Reproduction

https://codesandbox.io/s/nifty-hofstadter-lzl3vs?file=/src/index.tsx

### Steps to reproduce

1) Try to override the `display` or `alignItems` property on a Checkbox component using the theme
2) Notice how some props are working (like `bg`) but not the ones mentioned above

### Chakra UI Version

2.3.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

When trying to align a checkbox (which is already has `display: flex` as style) using `alignItems` by overriding the theme, the property is ignored while some others (like `p` or `bg`) are being overridden correctly. I need to align the checkbox to the text. I think this can be a common use case for longer privacy policy text. Am I doing anything wrong?  Thanks
![Screenshot 2022-09-23 at 19 05 39](https://user-images.githubusercontent.com/8071249/192019237-4946be20-0229-4815-a5bb-7d19393281cb.png)
![Screenshot 2022-09-23 at 19 05 30](https://user-images.githubusercontent.com/8071249/192019229-c927b3b6-11dc-4a97-8ea4-3102b958c1a6.png)
![Screenshot 2022-09-23 at 19 05 17](https://user-images.githubusercontent.com/8071249/192019206-972adeb8-4156-4b8d-bebb-5b9e6ba0732f.png)

**Comment by linus-amg** [comment]
Not a fix, but as an alternative you could use https://chakra-ui.com/docs/hooks/use-checkbox to create your own Version of a Checkbox in the meanwhile. Good luck!
