### ISSUE TITLE
Glitch 

### ISSUE THREAD

**Issue by digitalforus** [chakra-ui/chakra-ui#675]
Details
There's a  glitch in the first sentence of the Browser Security section. It should be "Changes to the docs will not reload the site." and not "Changes to the docs will hot reload the site."

**Comment by segunadebayo** [comment]
Hello @digitalforus,

This issue isn't clear to make, could you explain better?

**Comment by digitalforus** [comment]
Okay, what I mean is that the sentence "Changes to the docs will hot reload the site" ought to be "Changes to the docs will not reload the site." 
There is a typo with "hot" for "not"

Here is the link to the page
https://chakra-ui.com/contributing

**Comment by ralphilius** [comment]
@digitalforus It's not a glitch, it's a feature. `Hot reload` means you don't need to refresh the page to see changes.

**Comment by digitalforus** [comment]
> @digitalforus It's not a glitch, it's a feature. `Hot reload` means you don't need to refresh the page to see changes.

Thanks for the clarification
