### ISSUE TITLE
emotionStyled not working

### ISSUE THREAD

**Issue by danchitnis** [chakra-ui/chakra-ui#6755]
### Description

When I run `yarn start` I expect to all files to compile and run in browser, however, I get the following error:

**Chrome Error:**
Uncaught TypeError: emotionStyled is not a function
    at styled (@chakra-ui.system.v2.2.11.js:136:21)
    at Object.apply (@chakra-ui.system.v2.2.11.js:179:14)
    at @chakra-ui.visually-hidden.v2.0.10.js:20:22

### Link to Reproduction

1. git clone https://github.com/danchitnis/EEsim.git
2. yarn install
3. yarn start

Alternatively use Github Codespace

### Steps to reproduce

Updating Chakra from 2.2.4 to 2.3.4

### Chakra UI Version

2.3.4

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

**I am using the following dependencies:**
"@chakra-ui/react": "2.3.4",
"@emotion/react": "^11.10.4",
"@emotion/styled": "^11.10.4",
"framer-motion": "^7.4.0",
"react": "^18.2.0",
"react-dom": "^18.2.0",

**Comment by anubra266** [comment]
Unable to reproduce this. Please feel free to reopen with a codesandbox reproduction.

**Comment by segunadebayo** [comment]
I looked into this, and it turns out it's related to how snowpack resolves this line.

```
import emotionStyled from "@emotion/styled"
```

Emotion uses a default export for its styled package, so this is an issue from Snowpack's resolution process, not Chakra UI. Please file an issue report there.

**Comment by danchitnis** [comment]
Thanks, I can confirm this was a Snowpack issue. I didn't realize that it was no longer maintained. Now, it works with Parcel without any issues.
