### ISSUE TITLE
React does not recognize the `motionProps` prop on a DOM element.

### ISSUE THREAD

**Issue by iluvkoohi** [chakra-ui/chakra-ui#6758]
### Description

Problem occurred every time I open the drawer.

### Link to Reproduction

https://codesandbox.io/s/black-leftpad-f5lo5b?file=/src/App.js

### Chakra UI Version

2.3.4

### Browser

Microsoft Edge

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

`Warning: React does not recognize the motionProps prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase motionprops instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

**Comment by cc-dev04** [comment]
I have the same problem, any solution?

**Comment by frxitas** [comment]
i have de same error. Chakra UI Version 2.3.4 ☹️

**Comment by KarolChang** [comment]
same problem. But disappear on production mode.

**Comment by iluvkoohi** [comment]
> same problem. But this warning disappear on production mode.

Some errors are being ignored in production

**Comment by anubra266** [comment]
I can't reproduce this. Please feel free to reopen with a codesandbox reproduction.

**Comment by Anoosh-MR** [comment]
I have the same error? did anyone get any idea how to solve it?

**Comment by jackielowens** [comment]
I also same issue with Chakra version 2.3.3

**Comment by statico** [comment]
I'm also having this issue. I tried creating a Codesandbox demo with the exact package versions we're using but also cannot reproduce the error. https://codesandbox.io/s/black-leftpad-f5lo5b?file=/src/App.js

**Comment by martinezleoml** [comment]
Also facing the issue.

`@chakra-ui/transition` package hasn't be published since august whereas changes (including `motionProps` property) has been introduced with https://github.com/chakra-ui/chakra-ui/pull/6679.

**Comment by iluvkoohi** [comment]
> https://codesandbox.io/s/black-leftpad-f5lo5b?file=/src/App.js

Hi, I'm using your url sandbox for this issue.

**Comment by drikthereal** [comment]
I'm also having this issue... codesandbox does not give an error when it should.

To see how codesandbox is broken, simply open the link @statico posted and replace `<DrawerContent>` with `<DrawerContent fooBar="baz">` which **should** give an error like this:

```React does not recognize the `fooBar` prop on a DOM element.```

**Comment by Beatriz2529** [comment]
I'm facing the same issue, please reopen this @anubra266

**Comment by LinnJS** [comment]
Same issue over here 😞

**Comment by matthewrose** [comment]
Same issue for `"@chakra-ui/react": "^2.3.4"`

**Comment by dotdev-support** [comment]
Same issue for `"@chakra-ui/react": "^2.3.4"`

**Comment by elmarkou** [comment]
Same here!

**Comment by segunadebayo** [comment]
Good catch, @martinezleoml. The issue was that the transition package was not released properly. That's my bad.

I've now added it to the next release. It should work as expected afterward

**Comment by drikthereal** [comment]
I updated to `@chakra-ui/react@2.3.6` and the error is gone. Thank you guys!

**Comment by mswezey23** [comment]
+1 2.3.6 fixed this exact error for myself. Thanks everyone!

**Comment by nileshgulia1** [comment]
For the custom attributes to the DOM element, you can use the data-* syntax, for the attributes you think are informative for a given DOM element.

**Comment by dkrefta** [comment]
I'm facing the same issue but with showBorder:
api.ts:23 Warning: React does not recognize the `showBorder` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `showborder` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

I tried to open a new issue but they closed lol
https://github.com/chakra-ui/chakra-ui/issues/8805

**Comment by dkrefta** [comment]
same issue:
https://github.com/chakra-ui/chakra-ui/issues/8808
