### ISSUE TITLE
[Request] Expose `setValue` method from `useClipboard` hook

### ISSUE THREAD

**Issue by SpencerKaiser** [chakra-ui/chakra-ui#6759]
### Description

Please expose a new `setValue` method from the hook so users can update the value the `onCopy` method will copy to the user's clipboard

### Problem Statement/Justification

There are frequently times where a page has multiple components that can all be copied to a clipboard. The `useClipboard` hook doesn't expose a way to change that value and, as a result, the dev is forced to rely on a re-render to execute for a `useState` value to update before the clipboard will work OR the dev will need to abstract the copy-able value into a new component so multiple hooks can exist on one page.

### Proposed Solution or API

``` typescript
const defaultValue = 'some string';
const { onCopy, setValue } = useClipboard(defaultValue);

// ...

const updatedValue = 'some new string';
setValue(updatedValue);
onCopy();
// updatedValue copied to clipboard
```

### Alternatives

Moving all relevant copy-able elements to their own components (ideal from an abstraction standpoint, but often unnecessary if the original file is trivially small)

**Comment by clement-v8** [comment]
@SpencerKaiser why don't you put the value in a `useState` hook?
```typescript```
const [copyValue, setCopyValue] = useState<string>('');
const { onCopy } = useClipboard(copyValue);
```

when you want to change the `copyValue`, you can only `setCopyValue`

**Comment by SpencerKaiser** [comment]
That was one of the pieces I mentioned above; if you use `useState`, you're reliant on a render updating the `useClipboard` hook, which isn't guaranteed to happen...

``` typescript
const onClick = () => {
  setCopyValue('some new value');
  onCopy();
  // Old value may be copied because the render hasn't completed yet

  setCopyValue('some new value');
  wait(1000);
  onCopy();
  // This will work, but it's exceptionally hacky 😅
}
```

`useRef` won't work either, FWIW

Here's a [CodeSandbox demo](https://codesandbox.io/s/confident-sutherland-rj64yk?file=/src/index.tsx)

**Comment by SpencerKaiser** [comment]
@segunadebayo thank you!!!! 🚀

**Comment by nachoiacovino** [comment]
hey @segunadebayo @SpencerKaiser and @noobinthisgame, after updating my useClipboard logic broke in my app, before, I would have some inputs that would generate an iframe code users could copy, so in each render the value was getting updated and users could copy the updated code.

This change makes it so the original value is always stored and not updated in rerenders, which I'm not sure was the idea since it wasn't supposed to be a breaking change.

I can make it work by doing a useEffect but previous way was much more straightforward, please tell me if there's something I'm missing, if this is the way to do it going forward or was this an oversight?

Thanks in advance.

**Comment by tuananhl** [comment]
@SpencerKaiser Did you see the new implementation and does it work on your case? I think it's the same as my example above. now it's implemented by using state. 
@nachoiacovino yes. I think the new implementation is quite redundant and it breaks some upgrading apps. Now if we get the value from the form, or another controlled input or something like that, we must call the `setValue` again.

I think we should revert this change and expose a method that copies the text directly instead to help @SpencerKaiser solve his case

```
const copyTextToClipboard = useCallback((text: string, copyOptions) => {
    copy(value, copyOptions)
}, [value, copyOptions])
```

**Comment by SpencerKaiser** [comment]
That would totally work for my needs; I actually haven't updated with the latest to even use the update (sorry 😅). What you proposed would work perfectly though

**Comment by SpencerKaiser** [comment]
@tuananhl sorry for the belated response; the original actually doesn't work for my needs... if the user clicks a button and the button dynamically uses `setValue`, the state that's accessed by `onCopy` is stale.

In this example, 
``` typescript
const { onCopy, setValue } = useClipboard('Hello world!');

const onClick = () => {
  setValue('Some dynamic value');
  onCopy(); // User copies "Hello world!" to their clipboard, subsequent click will copy "Some dynamic value")
}
```

I think your most recent suggestion is just an all-around better implementation and it sounds like that might un-break @nachoiacovino's use-case 😬

**Comment by nachoiacovino** [comment]
I ended up doing this to fix it on every part of the app we use `useClipboard`:

```tsx
  const { onCopy, setValue } = useClipboard(address || "");

  useEffect(() => {
    if (address) {
      setValue(address);
    }
  }, [address, setValue]);
```

Leaving this for future reference but seems a bit redundant having to always do this.

**Comment by RobinClowers** [comment]
This is an extremely confusing api for a hook. If a hook takes a value, it should react to changes in that value, not require calling a separate function to update it. This was also a breaking change despite what https://github.com/chakra-ui/chakra-ui/pull/6763 says.

**Comment by inspiraluna** [comment]
I had to use a timeout before running onCopy. Maybe this is helpful for somebody:
```
            <InputGroup>
                <FormLabel htmlFor="myInput">dbAddress:</FormLabel>
                <Input name="myInput" id="myInput" readOnly={true} 
                    value={props.store.dbList?.id?props.store.dbList?.id:''} /> 
                <InputRightElement children={<CopyIcon color={hasCopied?'blue':'orange'} 
                onClick={()=> { setValue(document.getElementById('myInput').value);setTimeout(onCopy, 1000);} }/>} />
            </InputGroup>
```

**Comment by danbunkr** [comment]
I upgraded Chakra to v2 to take advantage of the `setValue` method as I thought I might fix my needs. But I was experiencing the same bug @SpencerKaiser where the onCopy was lagging behind and and to be called 2x to copy the correct value. I ended up ripping out all `useClipboard` from my code and just doing the native JS `navigator.clipboard.writeText` method until this becomes more stable.

**Comment by pom421** [comment]
This is definitely a breaking change, since data returned by async stuff don't work anymore.

I am suprised of the API choice. I would have expected the parameter in useClipboard would be used dynamically (between render). This way, it would have prevented to add useffect for wrapping setValue any time to sync with data.

**Comment by sohrab-** [comment]
So umm to simplify the above use case, now the previously simple use case of when the `value` _was_ a prop, has to be changed, for it to resume to work? 😕 

```diff
- const { hasCopied, onCopy } = useClipboard(value);
+ const { hasCopied, onCopy, setValue } = useClipboard("");
+ useEffect(() => {
+     setValue(value);
+ }, [value]); 
```
