### ISSUE TITLE
[ButtonGroup + potentially some others] Doesn't use forwardRef

### ISSUE THREAD

**Issue by selbekk** [chakra-ui/chakra-ui#676]
**Describe the bug**
ButtonGroup doesn't use forwardRef

**Expected Behavior**
It should use forwardRef, so I can use it with `motion.custom`. In addition, I would expect all elements to forward their ref the same way, so it's consistent.

I didn't research what other components doesn't forward their refs, but this should be done on all of them.

I filed this as a bug, but perhaps it's just unexpected behavior, and it should be a feature. 🤷‍♂️

Thanks for a great component library by the way - I love everything else about it 💋

**Comment by segunadebayo** [comment]
Thank you for this feedback @selbekk. We'll look into this.

Glad to hear that you love Chakra UI 💖

**Comment by segunadebayo** [comment]
This fix has been published!
