### ISSUE TITLE
React does not recognize the `pId` prop on a DOM element. 

### ISSUE THREAD

**Issue by iluvkoohi** [chakra-ui/chakra-ui#6761]
### Description

Error occurs when creating a Button with left/rightIcon (react-icons)

### Link to Reproduction

https://codesandbox.io

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.3.4

### Browser

Microsoft Edge

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Warning: React does not recognize the `pId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `pid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by anubra266** [comment]
@iluvkoohi I can't reproduce this. Please feel free to reopen with a codesandbox reproduction.
