### ISSUE TITLE
MenuList breaks draggable preview

### ISSUE THREAD

**Issue by mxthevs** [chakra-ui/chakra-ui#6762]
### Description

When using `MenuList` inside a `draggable` container, the default preview also show other elements that are not in the draggable container.

### Link to Reproduction

https://codesandbox.io/s/bold-cdn-6ll7bd?file=/src/index.tsx:295-352

### Steps to reproduce

1. Create a draggable container with a `Menu` component inside. 
2. Render any element before the container.
3. Drag the container
4. Notice that the drag preview also shows the elements that are outside the container. 

### Chakra UI Version

2.3.4

### Browser

Google Chrome 105.0.5195.125

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I debugged this a little bit and I think this happens because of the hidden elements that MenuList uses.

Screenshot for reference:
<img width="442" alt="Screenshot 2022-09-28 at 09 47 00" src="https://user-images.githubusercontent.com/46231311/192782294-ee268fd7-a54a-454c-8077-417ed02a272b.png">

**Comment by aboveyunhai** [comment]
@mxthevs  check this one: https://github.com/react-dnd/react-dnd/issues/832

**Comment by jonrosner** [comment]
I solved the problem the following way:

```
<Menu>
          {({ isOpen }) => (
            <>
              <MenuButton />
              <MenuList style={{
                  display: !isOpen ? 'none' : '', // <-- this solved the problem as long as the menu is closed
                }}>
...
```

It's not optimal though as the preview is still broken if the modal is open. If anyone has a better solution please share.
