### ISSUE TITLE
Request to add Pagination

### ISSUE THREAD

**Issue by adventurini** [chakra-ui/chakra-ui#677]
That's all

**Comment by with-heart** [comment]
Hi @adventurini! We're focusing all current effort on getting through the 1.0 release. Once we get through that, we'll be taking time to refocus and thinking about the future of our features and components again. In the meantime, I'm going to close this, but we can revisit later.

**Comment by hjaved-nha** [comment]
Any plans for adding Pagination now that 1.0 release is out ?

**Comment by sainhimanshu9** [comment]
Its 2021, when will you add the pagination?

**Comment by citypaul** [comment]
> Its 2021, when will you add the pagination?

You realise this is an open source project, right @sainhimanshu9? Feel free to contribute pagination to the library yourself.

**Comment by sainhimanshu9** [comment]
@citypaul did i mention you in my query? so calm yourself.

**Comment by citypaul** [comment]
>@citypaul did i mention you in my query? so calm yourself.

@sainhimanshu9 no you didn't, but consider showing a bit of empathy for others - nobody owes you anything.

**Comment by sainhimanshu9** [comment]
@citypaul  i was asking when will pagination be up? how is it rude? don't create things in your head. ignore now.

**Comment by Waxaranai** [comment]
Any updates?

**Comment by tsanyqudsi** [comment]
Maybe you guys can talk with https://github.com/niconiahi/chakra-paginator

**Comment by ostrebler** [comment]
Any update ?

**Comment by JavaJamie** [comment]
Any update?

**Comment by zanami** [comment]
https://github.com/anubra266/choc-paginator
https://github.com/niconiahi/ajna/tree/main/packages/pagination

**Comment by FernandoI7** [comment]
Any update?

**Comment by trompx** [comment]
Can this be reopened @with-heart please?

**Comment by mahezsh** [comment]
I think [Chakra UI + React Table example](https://chakra-ui.com/getting-started/with-react-table) serves the purpose.

**Comment by VaZark** [comment]
It might nice to have PageGroup and page number stepper out of the box on Chakra for those not using react table. 

Something like [this on Ant Design](https://ant.design/components/pagination)
