### ISSUE TITLE
Tooltip will removed when changing label text

### ISSUE THREAD

**Issue by rikusen0335** [chakra-ui/chakra-ui#6773]
### Description

Tooltip will removed when changing label text, like using useState or useClipboard or something like that.

### Link to Reproduction

https://stackblitz.com/edit/react-ts-mlswqt?file=App.tsx

### Steps to reproduce

See stackblitz

### Chakra UI Version

2.3.4

### Browser

Vivaldi

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by DanishOnGit** [comment]
There is a default value of 1500ms, after which the `hasCopied` value changes back to false.
That is why your Tooltip text is behaving that way.

To change the behaviour, you can provide a delay value as shown below (https://chakra-ui.com/docs/hooks/use-clipboard#arguments)

```
Usage: 
const { hasCopied, onCopy } = useClipboard('test',4000);
```
Try the above code and see the change.
Hope that answers the question!

**Comment by segunadebayo** [comment]
Kindly use the solution suggested above

**Comment by rikusen0335** [comment]
It's not the point of this issue!
useClipboard is not even an issue, this can be happen if I used useState.

I made a reproduction here: https://stackblitz.com/edit/react-ts-8plpxy?file=App.tsx

**Comment by azhoang-sts** [comment]
I have same issue with react-table.

**Comment by DanishOnGit** [comment]
> It's not the point of this issue! useClipboard is not even an issue, this can be happen if I used useState.
> 
> I made a reproduction here: https://stackblitz.com/edit/react-ts-8plpxy?file=App.tsx

Can you please elaborate on the issue?
All I am seeing is, after clicking the button, tooltip text is changing to 'copied', which is correct as per you code.

**Comment by rikusen0335** [comment]
@DanishOnGit 
Okay so, I am expecting tooltip to remain fre seconds like default behaves.
The tooltip will be hidden immediately if we change the the text in it even I set the `hasCopied` duration like @DanishOnGit said.

I gotta give you what is actually happening with GIF
![vivaldi_4uYMyqmDkQ](https://user-images.githubusercontent.com/19174234/194881678-4379d861-c3fb-486c-8ea7-08e4584ed3d9.gif)
This GIF shows that clicking tooltip make it is hidden immediately

**Comment by DanishOnGit** [comment]
@rikusen0335  Ohkkay...got it! Will try to address this if possible.

**Comment by rikusen0335** [comment]
Oh that what I wanted! Sorry for not reading as much as I can.
I really appreciate for your help though. Issue closing.
