### ISSUE TITLE
Add type `ResponsiveValue` to `hidden` prop

### ISSUE THREAD

**Issue by thatvegandev** [chakra-ui/chakra-ui#6778]
### Description

I'd like to see the `hidden` prop be given the additional type option of `ResponsiveValue`.

### Problem Statement/Justification

This seems like a pretty basic request. Coming from tailwind I'm used to having options like `sm:hidden, md:block` etc. I'd like to be able to accomplish the same thing here via props.

### Proposed Solution or API

```
hidden={{
  base: condition,
  md: false
}}
```

### Alternatives

This is what I'm currently having to do, but it's a big code smell

```
height={{
  base: condition ? 0 : 'inherit',
}}
```

### Additional Information

Would be up to PR this myself if necessary. Just let me know!

**Comment by segunadebayo** [comment]
Hi @thatvegandev,

The `hidden` property is an HTML attribute, not a CSS property. To hide a property responsively, please use `display: none` instead and apply that responsively.

Thanks
