### ISSUE TITLE
TypeScript prop autocomplete not working

### ISSUE THREAD

**Issue by aecorredor** [chakra-ui/chakra-ui#6785]
### Description

When I used any chakra component and specified props, I expected VSCode's autocomplete to work by showing a subset of the available values (like sizes for `Heading`), but instead I saw no autocomplete appear and the prop was just typed as `string`.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-typescript-pomi8 (I think this should do, but since this is specific to VSCode's autocomplete, it might not be enough, and might need to clone locally and open VSCode to reproduce).

### Steps to reproduce

Try to use any chakra component and see the autocomplete not work in VSCode. The TypeScript starter should be enough to reproduce. The project I'm using has `"typescript": "^4.7.4"` and `"@chakra-ui/react": "^2.3.5"`. I confirmed my `tsconfig.json` is exactly the same as the example repo.

### Chakra UI Version

`2.3.5`

### Browser

N/A

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I had a project with older TypeScript and chakra versions where the autocomplete was working (`"typescript": "^4.3.0"` and `"@chakra-ui/react": "^1.4.2"`).

**Comment by anubra266** [comment]
@aecorredor this is from your codesandbox reproduction

<img width="1437" alt="CleanShot 2022-10-04 at 12 02 09@2x" src="https://user-images.githubusercontent.com/30869823/193803017-1b6b8a89-bcdc-44ca-a24b-99bb4ff72d10.png">

**Comment by aecorredor** [comment]
> @aecorredor this is from your codesandbox reproduction
> 
> 
> 
> <img width="1437" alt="CleanShot 2022-10-04 at 12 02 09@2x" src="https://user-images.githubusercontent.com/30869823/193803017-1b6b8a89-bcdc-44ca-a24b-99bb4ff72d10.png">
> 
> 

@anubra266 maybe my explanation wasn't clear enough. The prop name autocompletion does work. What doesn't is the prop value autocompletion, which used to work in older chakra versions.

**Comment by anubra266** [comment]
@aecorredor Not this?

<img width="1440" alt="CleanShot 2022-10-04 at 13 46 11@2x" src="https://user-images.githubusercontent.com/30869823/193822849-6fcf8b71-f9a7-46a3-94d9-b882c734a624.png">

**Comment by aecorredor** [comment]
Right, that's what stopped working:

In an older version:
<img width="503" alt="Screen Shot 2022-10-04 at 9 00 04 AM" src="https://user-images.githubusercontent.com/9114987/193826165-f4cc0d3e-4f46-4ff0-bb5c-4cab59a74875.png">

In latest version:
<img width="177" alt="Screen Shot 2022-10-04 at 9 00 58 AM" src="https://user-images.githubusercontent.com/9114987/193826170-50aa87ce-c36e-40cf-878f-3d6e1ee3119e.png">

I'll try to find a fully reproducible example. It's strange since my configs look the same from what I've been seeing.

**Comment by aecorredor** [comment]
@anubra266 I got this to work. I updated the react type dependencies to match exactly what the codesandbox had. I think some discrepancies in types from older versions caused the issue, especially since react 18.
