### ISSUE TITLE
Popover in a Portal (inside Modal) gets rendered behind the Modal

### ISSUE THREAD

**Issue by agon-qorolli** [chakra-ui/chakra-ui#6794]
### Description

When I add a Popover in a Portal (inside of a Modal), I expect the Portal to render on top of the Modal, but it doesn't, it gets rendered behind the Modal.

### Link to Reproduction

https://codesandbox.io/s/portaled-popover-inside-modal-gets-rendered-behind-the-modal-oydhge

### Steps to reproduce

1. Go to https://codesandbox.io/s/portaled-popover-inside-modal-gets-rendered-behind-the-modal-oydhge
2. Click on Open Modal
3. Click on Trigger Popover, inside the Modal
4. See Popover being rendered behind the Modal

### Chakra UI Version

2.3.5

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

<img width="2413" alt="Screenshot 2022-10-06 at 18 54 20" src="https://user-images.githubusercontent.com/97028874/194374321-3a1164f5-59e3-4a09-be6c-cdbdd5964aa8.png">

**Comment by marek-sed** [comment]
I think this is expected behavior, you just need to read up a little bit on [portals](https://chakra-ui.com/docs/components/portal/usage#nesting-portals).
I think the documentation could be improved here, something like a portal recipies how to solve various z-index chalenges might be useful.

So here is the fix for you.
https://codesandbox.io/s/portaled-popover-inside-modal-gets-rendered-behind-the-modal-forked-3hq9x1?file=/src/App.tsx

have a good one.

**Comment by agon-qorolli** [comment]
@marek-sed thanks Marek, this is a proper fix, I like it.

**Comment by baptisteArno** [comment]
I'm getting the modal ref like this:

```ts
  const modalRef = useRef<HTMLDivElement | null>(null)

  useEffect(() => {
    modalRef.current = dropdownRef.current?.closest(
      '[role="dialog"]'
    ) as HTMLDivElement | null
  }, [])
```

Not the cleanest but it works fine 😁

**Comment by agon-qorolli** [comment]
@baptisteArno yes there is a "better" one, I found later after this issue was closed. You just have to wrap `<PopoverContent />` this way:

```
<Box
  sx={{
    "& .chakra-popover__popper": {
      zIndex: "popover"
    }
  }}
>
        // <PopoverContent />
</Box>
```

Here's the working demo https://codesandbox.io/s/portaled-popover-inside-modal-gets-rendered-behind-the-modal-forked-xkmny5

**Comment by baptisteArno** [comment]
Thank you for the explanations 🙏

**Comment by baldurpan** [comment]
Another solution would be a custom portal component. (Works for Chakra v1.8 at least)
```javascript
import { Portal as ChakraPortal, useModalContext } from "@chakra-ui/react";

export function Portal({ children }) {
  try {
    const modalContext = useModalContext();
    return <ChakraPortal containerRef={modalContext?.dialogRef}>{children}</ChakraPortal>;
  } catch {
    return <ChakraPortal>{children}</ChakraPortal>;
  }
}
```
