### ISSUE TITLE
[Progress] [CircularProgress] Add CSS-based value animation

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#68]
`Progress` and `CircularProgesss` components are ideal for denoting the passage of time. However, they do not support time-based value animations yet. While it is possible to combine a state variable ([`useState`](https://reactjs.org/docs/hooks-state.html)) with a timer ([`setTimeout`](https://developer.mozilla.org/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout) or [`requestAnimationFrame`](https://developer.mozilla.org/docs/Web/API/window/requestAnimationFrame)), JavaScript animations are not as smooth as the ones made with CSS, as the latter can be GPU-accelerated.

I propose adding an `AnimatedValueProvider` based on the [React Context API](https://reactjs.org/docs/context.html), with syntax similar to below, inspired by the [`animation` CSS property](https://developer.mozilla.org/docs/Web/CSS/animation):

```jsx
<AnimatedValueProvider duration="30s">
  <CircularProgress />
</AnimatedValueProvider>
```

Only the `duration` prop should be mandatory, and the following could also be configured:

- `timingFunction` (override browser default value to be `linear`, as it fits the use-case better)
- `delay`
- `iterationCount`
- `direction`

The implementation could reuse the [logic behind an indeterminate `CircularProgress` component](https://github.com/chakra-ui/chakra-ui/blob/ad860f0a477a548a590b9dfbe20434fe6f9271a8/packages/chakra-ui/src/CircularProgress/index.js#L104), depending on the `useContext` hook to retrieve parameters from `AnimatedValueProvider`:

- If no provider is detected or the given `duration` is nullish, then leave the behavior of child components intact.
- The provider shall not override a `value` explicitly given to a child.
- `min` and `max` values given to a progress component should be respected by `AnimatedValueProvider` readings.

**Comment by jgarrow** [comment]
Would also love to be able to animate the "fill" of the `Progress` and `CircularProgress` components. Our current workaround is dynamically changing the `value` prop value, which means triggering lots of re-renders.

**Comment by laptop10** [comment]
hi rober
