### ISSUE TITLE
Dark Mode only activates in production, despite hard-coding only light-mode

### ISSUE THREAD

**Issue by ChristopherWirtOfficial** [chakra-ui/chakra-ui#6802]
### Description

When I don't realize there's a localStorage setting forcing a color mode from before I remembered to ignore system color mode settings and force light mode, users keep having the site be in dark mode and no one knows why (except now they do)

### Link to Reproduction

N/A

### Steps to reproduce

This is a misleading title on purpose, because that's exactly what this feels like to encounter this unexpected problem. When you integrate chakra into a react project, if you don't plan on using more than one color mode for your them, but you either don't know or don't remember that you should then disable listening to the system color setting, you end up with a deploy that sets a localStorage setting you don't know about for dark mode or light mode and then at some point you want to lock it to light mode because it's obviously picking up on your system value, you _don't_ know that you also need to remove this localStorage setting or anyone that's visited the website before you fixed this will have the localStorage setting and it will still dictate the color mode. 

So then you use the `<LightMode>` component, or some other trick to force the color mode you want, and that works except on the `body` which for some reason still has the `dark-mode` class, and then eventually you (hopefully) find the local storage item. All the while, the issue is inconsistent across devices and people, and goes away without a trace if you solve it (by accident probably) by clearing storage.

Anyway, there's a real good chance I'm just a moron. But I'm probably not the only moron, and I just hope I typed enough that google will help that moron find this discussion.

### Chakra UI Version

2.3.5

### Browser

Chrome 105

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by strider-** [comment]
I've also run into this issue, the principle of least surprise bit me when I explicitly used a `<LightMode>` component and spent quite a bit of time trying to figure out that local storage wins.

**Comment by HiHowdy** [comment]
I had a similar issue, but it was simply just that I didn't define the correct `initialColorMode` in the ThemeConfig.

```ts
const config: ThemeConfig = {
   initialColorMode: "light",
   useSystemColorMode: false,
};

const theme = extendTheme({
   config,
});

export default theme;
```

**Comment by anubra266** [comment]
@ChristopherWirtOfficial We can't change the rules deciding the order in which chakra decides modes. They've been discussed and agreed on the best order of color mode resolutions.
Though to fix your issue, I'd have a effect that checks the current color mode, and sets it to light if it's dark. This would only need to happen once for your users.
