### ISSUE TITLE
MenuList is under scrollbar and over background when put into scrollable item

### ISSUE THREAD

**Issue by hadson172** [chakra-ui/chakra-ui#6813]
### Description

When I put Menu inside scrollable div and on the right side, then menuList shows under scrollabar + not hides when scrolling down.

### Link to Reproduction

https://codesandbox.io/s/still-sea-21bs80?file=%2Fsrc%2Findex.tsx

### Steps to reproduce

1. Go to Link above
2. Click on menu button
3. See that scroll is over popup
4. Scroll down, popup is going up over the page, it should disappear

### Chakra UI Version

2.0.2

### Browser

Firefox 105.0.3

### Operating System

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hey @hadson172,

Here's how to resolve this issue:
https://codesandbox.io/s/menu-with-custom-boundary-52fj3o

The menu allows you to set a custom boundary for dynamic positioning.
