### ISSUE TITLE
Unable to set open/closed state of AccordionItem from external boolean value. 

### ISSUE THREAD

**Issue by alexmassen-hane** [chakra-ui/chakra-ui#6817]
### Description

I am using a number of accordion items and I can see no way of forcing an accordion to open based on any sort of event apart from clicking on the AccodianButton. 

### Problem Statement/Justification

I would like to open an accordion based on either a mouse hover over or perhaps from clicking a checkbox that is inside an AccordionItem and setting the value based on the checkbox.

### Proposed Solution or API

Implement something in the form of:

AccordionItem isOpen={optionalOpenMethod} 

### Alternatives

Building another component from scratch using the AccordionItemProvider and other functions from accordion.tsx

**Comment by marek-sed** [comment]
You do not need to set state, you can access the trigger from useAccordionItemState hook. 
Here is an example, that does expand on hover. 

Regarding click on checkbox and expand, we had some discussion on our project about that and would advice against that, it is bad idea to combine selecting and expanding action. We added expand carrets to the right side. But you could create probably AccordionCheckboxItem in this way.

**Comment by alexmassen-hane** [comment]
Thanks for the quick reply Marek. Do you have a link for the hover example and carrets?

**Comment by marek-sed** [comment]
I did not paste it lol, sry
https://codesandbox.io/s/icy-meadow-vxcyi2?file=/src/index.tsx

**Comment by alexmassen-hane** [comment]
Thanks for the help! 
Greatly appreciated.

**Comment by cullylarson** [comment]
If anyone else finds this and wants maybe a simpler but more of a hacky solution:

```tsx
<Accordian key={isOpen ? "open" : "closed"} defaultIndex={isOpen ? [0] : undefined}>
```

Changing `key` will cause Accordian to re-render when `isOpen` changes.
