### ISSUE TITLE
Add Display Name to CSS classNames for Easy Debugging

### ISSUE THREAD

**Issue by yantakus** [chakra-ui/chakra-ui#682]
Opening a separate issue as requested by @hendrikniemann in https://github.com/chakra-ui/chakra-ui/issues/211.

It would be very helpful if `chakra-ui` adds component names to CSS classes it generates, like `styled-components` does. So that we can see components names not only in react developer tools, but in Elements panel as well.

ATM it looks like this:
![image](https://user-images.githubusercontent.com/2179726/81039995-11f85900-8eb3-11ea-9995-b783b17ee5bd.png)
and it's very hard to understand anything.

If it's `Flex-css-5vq3nc` or `Box-css-5vq3nc` - it's at least something.

I'm not sure if we can add names of custom components like `styled-components` does this, so that

```
import React from 'react`
import styled from 'styled-components'

const StyledSomething = styled.div`
   display: flex;
`

const CustomComponent = () => <StyledSomething />

export default CustomComponent
```
becomes `CustomComponent-css-5vq3nc`.

If it's possible, it would be super helpful.

**Comment by elisherer** [comment]
Since `babel-plugin-emotion` is adding that [Contextual Class Names](https://emotion.sh/docs/babel-plugin-emotion#features).
You can set `babel-loader` to not exclude `@chakra-ui` in `webpack.config.js` in the js loader rule:
```js
  {
        test: /\.js$/,
        exclude: path => !path.includes("@chakra-ui") && /node_modules/.test(path),
        use: "babel-loader",
  }
```
I tested it and it started to show chakra's components names in the classNames, but mostly `Box` and `Box-PseudoBox` so probably not what you wanted.

**Comment by benregn** [comment]
I tried adding that snippet in Next.js with the following modifications:

```javascript
webpack: (config, options) => {
  config.module.rules.push({
    test: /\.jsx?$/,
    exclude: (path) =>
      !path.includes('@chakra-ui') && /node_modules/.test(path),
    use: [options.defaultLoaders.babel, 'babel-loader'],
  });

  return config;
}
```

I have installed the `babel-plugin-emotion` package and included it in the `.babelrc` file like this:

```json
{
  "presets": ["next/babel"],
  "plugins": ["emotion"]
}
```

But I'm still seeing `css-yxduxz` as classes. Any ideas on what I'm doing wrong?

**Comment by segunadebayo** [comment]
Hey guys,

We've solved this in the `v1` pre-release by adding class names to all components.

**Comment by Maybach91** [comment]
@segunadebayo 
> Hey guys,
> 
> We've solved this in the `v1` pre-release by adding class names to all components.

Hej, sorry for getting back to this closed issue here.

I’m using `"@chakra-ui/core": "^1.0.0-rc.5"` but i still don’t see the class names? Is there any configuration or way to activate it?

**Comment by ljosberinn** [comment]
no, they are enabled by default, you can see it in the docs for example!

![image](https://user-images.githubusercontent.com/29307652/97003893-7b8d2200-153c-11eb-855e-8fa4c2314197.png)

**Comment by Maybach91** [comment]
@ljosberinn  thanks ! Ah that means only, when i have the attribute `className` its shown in the rendered HTML, right? But when i have my own Components or just `<Box>` etc. its not shown right?

**Comment by ljosberinn** [comment]
it's there by default, the component there is just `<Text>` with some props, but iirc `Box` is more or less the only component that doesnt have its own className because its implementation is literally just `export const Box = chakra.div`.

**Comment by Maybach91** [comment]
Ah okay. I’m almost just using Boxes for most of my Layout stuff. Its working with the mentioned `<Text>`. Would be helpful to have the component name as class name as well. e.g. my Component `<Header>` hast just `<Box>` Elements as children. But thats a different topic. :) Thanks for the clarification @ljosberinn !

**Comment by ljosberinn** [comment]
you could do this:
```js
import { Box as ChakraBox } from '@chakra-ui/core';

export const Box = ({ className, ...rest }) => <ChakraBox className={['chakra-box', className].filter(Boolean).join(' ')} {...rest} />
```
