### ISSUE TITLE
@chakra-ui/react installation with pnpm package manager

### ISSUE THREAD

**Issue by kicks321** [chakra-ui/chakra-ui#6820]
### Description

When installing @chakra-ui for a React application using pnpm, it is necessary to have to install the separate packages like @chakra-ui/layout. 

### Problem Statement/Justification

PNPM documentation not provided for installation.

### Proposed Solution or API

 I did not see pnpm installation guides in the documentation, but would be nice to have that updated at some point to let users know separate packages need to be installed as well if using pnpm.

**Comment by anubra266** [comment]
@kicks321 That's not true, pnpm installation is just like the other package managers, 
```sh
pnpm i @chakra-ui/react @emotion/react @emotion/styled framer-motion
```
Attached a video that shows this


https://user-images.githubusercontent.com/30869823/195837629-2cab2c32-8949-46a2-bf80-7b67104c3da9.mp4

**Comment by brandoncollins7** [comment]
It does not work with pnpm.... I get an error:

import { tabsAnatomy } from "@chakra-ui/anatomy"
 [vite] Internal server error: Failed to resolve import "@chakra-ui/anatomy" from "src\shared\theme\components\Tabs.ts". Does the file exist?
