### ISSUE TITLE
In a Popover if you shift tab to trigger button you are immediately taken back to initial focus ref

### ISSUE THREAD

**Issue by jcfizzler** [chakra-ui/chakra-ui#6821]
### Description

If you have a Popover and you shift tab to trigger button you are immediately taken right back to initial focus ref or, if no initial focus ref is defined, the entire popover is focused. This looks weird and makes it seem like the user can't (shift) tab out to leave the popover. They can of course still close it by clicking ESC a close button if one is present.

### Link to Reproduction

https://chakra-ui.com/docs/components/popover/usage

### Steps to reproduce

You can see this on the tutorials for Chakra-UI. Open a popover and navigate backwards to the trigger button using SHIFT+TAB. If the Popover has an initialFocusRef defined you will be taken back to that element as soon as you land on the trigger button. Otherwise the entire modal will be focused. 

### Chakra UI Version

v2.3.5

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by brunolucena** [comment]
I'm also facing this issue, it makes the inputs unusable using only the keyboard.
