### ISSUE TITLE
2.3.5 breaks dark mode and toggling color mode

### ISSUE THREAD

**Issue by JClackett** [chakra-ui/chakra-ui#6825]
### Description

Dark mode/toggling color mode stopped working in 2.3.5

### Link to Reproduction

https://boilerplate-remix.noquarter.co

### Steps to reproduce

Login with:
email: chakra@gmail.com
password: password

Toggle the theme in the nav menu thats top right, it doesn't do anything.

If the theme was already saved as dark mode when on 2.3.4, after upgrading to 2.3.5, it completely breaks and half the app is dark mode and half the app is light mode.

Repo: https://github.com/NoQuarterTeam/boilerplate-remix

Component responsible for changing color mode:
https://github.com/NoQuarterTeam/boilerplate-remix/blob/main/app/components/Nav.tsx

Nothing special going on here, just stopped working 2.3.5 

### Chakra UI Version

2.3.5

### Browser

Safari

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Project uses remix??

**Comment by yumemi-omi** [comment]
I faced same issue.

**Comment by anubra266** [comment]
@JClackett Please upgrade to latest version
