### ISSUE TITLE
Style props do not allow to override theme style

### ISSUE THREAD

**Issue by bertho-zero** [chakra-ui/chakra-ui#6829]
### Description

When I use the `px` prop on a button with variant link it has no effect.

### Link to Reproduction

https://codesandbox.io/s/zealous-browser-rgsbbq

### Steps to reproduce

By inspecting the 4th button we see that the padding is not applied.

The css rule `padding: 0` from the theme is listed after `padding-inline-start` and `padding-inline-end` from the `px` prop:

![image](https://user-images.githubusercontent.com/8525267/195885264-f14e25e2-5533-4674-bf42-96fdc513694e.png)

Shouldn't the rules coming from the props be after the rules from the theme to be able to override them?

### Chakra UI Version

2.3.5

### Browser

Brave 1.41.96

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by mortezasabihi** [comment]
Hey, I have checked this and I found out the issue is not related to padding, it's about height property, look at this:

Ghost styled button:
![image](https://user-images.githubusercontent.com/35567646/196001316-a5bb50fe-3218-44e8-8ead-e06622eb3adf.png)

Link styled button:
![image](https://user-images.githubusercontent.com/35567646/196001341-7db32d85-344b-4458-b088-b20be14e7d2e.png)

**Comment by bertho-zero** [comment]
My problem is that I try to add horizontal padding via px in props and it is ignored, nothing to do with height or visual rendering.

**Comment by bertho-zero** [comment]
It's this `Object.assign` that's the problem:
https://github.com/chakra-ui/chakra-ui/blob/16ba8cdd447be4d8a0a4a4eecc8de81fe04e637c/packages/components/system/src/system.ts#L52-L58

The `px:4` is in both `__css` and `styleProps`, and the `Object.assign` does not put styleProps values after those of __css, `Object.assign` already finding the key in the object it just replaces value without moving it at the end.

---

This test does not pass because padding is after `paddingInlineStart` and `paddingInlineEnd`:

```js
test("should respect priority order", () => {
  const result = toCSSObject({})({
    theme,
    __css: {
      px: 4,
      padding: 0,
    },
    px: 4,
  })

  // Can't test result without stringify because it sorts keys alphabetically
  expect(JSON.stringify(result, null, 2)).toMatchInlineSnapshot(`
    "{
      \\"padding\": \\"0px\\",
      \\"paddingInlineStart\\": \\"var(--chakra-space-4)\\",
      \\"paddingInlineEnd\\": \\"var(--chakra-space-4)\\"
    }"
  `)
})
```

**Comment by bertho-zero** [comment]
@segunadebayo Maybe you can look at this? It seems to me that this problem is serious and can be at the origin of several issues.

I added a reproduction code, a test that does not pass and an explanation.
