### ISSUE TITLE
[Component] Custom Icons give console error and do not allow tooltips.

### ISSUE THREAD

**Issue by ELI7VH** [chakra-ui/chakra-ui#683]
I am trying to load icons from React-Icons, and when i use `<Icon as={MdPeople} />` for example I get the following error in console: (I tried it with `<Box />` with the same result)

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Context.Consumer`.
    in MdPeople (created by Context.Consumer)
    in Styled(div) (created by Icon)
    in Icon (at PartnerIcon.tsx:20)
    in Tooltip (at PartnerIcon.tsx:14)
    ...
```
My componnet looks like so:
```jsx
import React from 'react'
import { Team } from 'types/Team'
import { MdPeople } from 'react-icons/md'
import { Tooltip, Icon } from '@chakra-ui/core'

type Props = {
  team: Team
}

export const PartnerIcon = ({ team }: Props) => {
  // use user to determine if this should be rendered.

  return (
    <Tooltip
      label={`Partner ${team.name}`}
      aria-label="Partner"
      placement="top"
      hasArrow
    >
      <Icon color="white" as={MdPeople} /> // tried this with <Box as... /> with the same result.
    </Tooltip>
  )
}
```

On top of this error, It does not show a tooltip when I hover over the icon. - I want to point out that the tooltip works fine when used with a normal icon. 

Not exactly sure how to debug this. 

Oh also, if you wrap a `<Tooltip>` element around this example you can see  that the tooltip does not render: https://chakra-ui.com/icon#adding-custom-icons

**Comment by with-heart** [comment]
This appears to still be an issue in 1.0.

**Comment by segunadebayo** [comment]
@with-heart, can you reproduce this in codesandbox so I can verify?

**Comment by with-heart** [comment]
So I can see that if I add `Tooltip` to some of the `Icon` examples at https://next.chakra-ui.com, it doesn't work, but I tested it in CodeSandbox and things are working fine: https://codesandbox.io/s/condescending-flower-jh00x?file=/src/App.js

**Comment by timkindberg** [comment]
In the site if you do:
```
<Tooltip isOpen label="hello"><Box as={MdSettings} size="32px" color="green.400" /></Tooltip>
```
Then scroll down, you'll see the tooltip at the bottom of the page, so it's having trouble finding how/where to anchor itself to.

**Comment by segunadebayo** [comment]
This issue is happening because `react-icons` doesn't use `forwardRef` and tooltip can't work correctly without `ref` placed in the icon.

See here: https://github.com/react-icons/react-icons/blob/f95cf84f7beff3638be8bb12a51d00338da97100/packages/react-icons/src/iconBase.tsx#L30

@with-heart  I'll suggest we open an issue or PR in `react-icons` repo to get this fixed.

I believe it works well if you use any icon from `@chakra-ui/icons`

Thanks guys.

**Comment by with-heart** [comment]
Opened an issue on their end. Depending on the reception I might open a PR too :)

**Comment by luizcieslak** [comment]
I'm facing the same issue. While `react-icons` doesn't support `forwardRef`, a quick solution would be add the icon as a child:

```js
<Tooltip isOpen label="hello">
  <Box size="32px" color="green.400">
    <MdSettings />
  </Box>
</Tooltip>

**Comment by renanblamas** [comment]
I was facing the same problem, I was tryng to Wrap a <Badge>  (from Chakrathe) with the Tooltip. A solution to it was using a <Flex> and then it worked properly. I know is not the best way to solve this, but it worked fine for me.

`<Tooltip label="tooltipLabel">
      <Flex>
        <Badge bg="green">Retry Job</Badge>
      </Flex>
    </Tooltip>`
