### ISSUE TITLE
Tabs are activated on down-event

### ISSUE THREAD

**Issue by joe-watkins** [chakra-ui/chakra-ui#6830]
### Description

Tabs are activated on down-event

### Link to Reproduction

https://chakra-ui.com/docs/components/tabs/usage

### Steps to reproduce

1. Go to ['Tabs Component'](https://chakra-ui.com/docs/components/tabs/usage)
2. Scroll down to Usage and click on the tab without letting up on the mouse.
4. The tab will be activated.

Ideally, tabs would activate on up-event to not potentially cause any issues related to [2.5.2 Pointer Cancellation](https://www.w3.org/WAI/WCAG21/Understanding/pointer-cancellation.html) allowing Up-reversal.

### Chakra UI Version

2.35

### Browser

Google Chrome 106

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information
![animated gif of tabs in action, mouse user trying to cancel selection](https://user-images.githubusercontent.com/3695795/195956202-fbb11d61-0784-4d51-a4e0-6dd11f96d93f.gif)

**Comment by segunadebayo** [comment]
Hi @joe-watkins,

Valid point! The Tabs component uses two patterns: 

- Selection follows focus: When the tab is focused, it'll be selected. This is called the "auto" mode (the default mode)
- Selection doesn't follow focus: When the tab is clicked, it'll be selected. This is called the "manual" mode and can be triggered by passing `isManual` to the Tabs.

In your case, you can use `isManual` to achieve the result you're looking for.

**Comment by joe-watkins** [comment]
@segunadebayo Thank you for the detailed response :) 

Would it be possible to have the same functionality present on "auto" (where selection follows focus AND when clicked it happens on an up-event and not a down?). If you take a peek at the ARIA Authoring Practices Guide's: [Example of Tabs with Automatic Activation](https://www.w3.org/WAI/ARIA/apg/example-index/tabs/tabs-automatic), you'll notice you can click on a tab, while continuing to keep the mouse pressed, move away from the tab to cancel the interaction by depressing the mouse button. 

![Screenshot of auto mode apg demo, mouse user can cancel interaction](https://user-images.githubusercontent.com/3695795/196224726-76d00778-ee66-4b01-8ce2-9463781bb73f.gif)

In the Chakra auto mode, you click on a tab and before the mouse button is depressed the change occurs. 

So for the APG examples, the functionality is present for both Manual and Auto. Would this be possible for Chakra's? This may be the result of simply listening for a `keydown` or `click` event. Are you listening for maybe `keyup` or `mousedown`?

**Comment by joe-watkins** [comment]
More information can be found at WCAG 2.5.2 Failure Technique: [F101](https://www.w3.org/WAI/WCAG21/Techniques/failures/F101)
