### ISSUE TITLE
backdropBlur property is not working

### ISSUE THREAD

**Issue by devjs1000** [chakra-ui/chakra-ui#6832]
### Description

I have tried to use backdropBlur for blur effect on Box it was not working but on other hand backdropFilter is working. So I think there is the issue in the backdropBlur attr.

### Link to Reproduction

https://codesandbox.com

### Steps to reproduce

add the backdropBlur attribute it will not work
but in other hand backdropFilter is working

### Chakra UI Version

^2.3.5

### Browser

106

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by devjs1000** [comment]
i have not added codesandbox because it was unnecessary in this case

**Comment by segunadebayo** [comment]
Hi @devjs1000,

The backdrop filter is a valid CSS property, while the backdrop blur is a "made up" property that only works when you pass `backdropFiilter=auto`.

```jsx
<Box backdropFilter="auto" backdropBlur="4px" />
```
