### ISSUE TITLE
chakra v1.8.8 didn't work with framer-motion version 5 and above 

### ISSUE THREAD

**Issue by zaherkassem** [chakra-ui/chakra-ui#6836]
### Description

I want to use framer-motion version 6 with chakra v1.8.8 for 2 reasons:

### Problem Statement/Justification

my project build in react v17 and i can't upgrade right now to v18 , so i can't also upgrade chakra-ui to v2
i want to use ReOrder from motion that not found in v4
when i install motion v5 or v6 some of chakra-ui components are broken

### Proposed Solution or API

didn't have one

**Comment by segunadebayo** [comment]
Hi @zaherkassem,

Sorry, we longer maintain the v1 versions.

Please consider using `patch-package` to fix the issues, or consider upgrading to React 18.

I know it's inconvenient but it'll help keep your app up to date with future releases.

Thanks for understanding
