### ISSUE TITLE
Props are not type-safe

### ISSUE THREAD

**Issue by Newbie012** [chakra-ui/chakra-ui#6843]
### Description

When I wrote an invalid property such as `bg="thiscolordoesnotexist"` I expected TSC to throw an error, but nothing happened instead

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-wzx6kp?file=src%2FApp.tsx&terminal=dev

### Steps to reproduce

1. Go to https://stackblitz.com/edit/vitejs-vite-wzx6kp?file=src%2FApp.tsx&terminal=dev
2. Open `App.tsx`
3. See that TypeScript doesn't complain about invalid props

### Chakra UI Version

^2.3.6

### Browser

Version 106.0.5249.119 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by MiroslavPetrik** [comment]
Yes, because the `ThemeTypings` accept anything...
![image](https://user-images.githubusercontent.com/38855190/197192743-eee487a8-81be-498d-ad9e-e4c2fc801c58.png)

**Comment by segunadebayo** [comment]
This is a very slippery slope, and we've had this conversation in the past. Not everyone wants this level of strictness when writing CSS.

As a workaround, there's a [PR](https://github.com/chakra-ui/chakra-ui/pull/5701) we're looking into that adds support for strict token types to the CLI.

When that is merged, you can use it to achieve the strictness you want.
