### ISSUE TITLE
Allow removing CSS vendor prefixes

### ISSUE THREAD

**Issue by JunlinPan-Crypto** [chakra-ui/chakra-ui#6846]
### Description

There are too many unnecessary vendor prefixes generated by Chakra UI for modern browsers and we have no way to remove them.

![image](https://user-images.githubusercontent.com/90383710/196409181-922a34a6-bff0-47dd-bcb5-40ff4da77ed7.png)

### Problem Statement/Justification

Most of vendor prefixes are unnecessary for modern browsers and it's inconvenient for developers to inspect CSS styles.

### Proposed Solution or API

Read `browserslist` configuration from project root and other postcss configurations to determine how to deal with CSS

**Comment by JunlinPan-Crypto** [comment]
Related discussion: https://github.com/chakra-ui/chakra-ui/discussions/6216

**Comment by segunadebayo** [comment]
Hi @JunlinPan-Crypto,

This is something I've been thinking about as well. Unfortunately, this aspect is handled by Emotion [(See Issue)](https://github.com/emotion-js/emotion/issues/2747), and they're looking to add support for this in the next major.

Closing this as it's not actionable on our end.

Thanks for understanding.
