### ISSUE TITLE
Modal component closeOnOverClick not working

### ISSUE THREAD

**Issue by danieloski98** [chakra-ui/chakra-ui#685]
when the modal is open and the prop closeOnOverlayClick is set to true the modal does close, it still remains open

**Expected Behavior**
when a user clicked on the overlay or the esc key the modal should be closed.

**Desktop (please complete the following information):**
 - OS: linux(elementary os hera)
 - Browser chrome, firefox
 - Version 81, 76

**Comment by segunadebayo** [comment]
Hi @danieloski98,

Can you drop a CodeSandBox link that replicates this issue? As far as I can tell, it works currently.

**Comment by danieloski98** [comment]
Ok
