### ISSUE TITLE
Popover doesn't open if the trigger element has a <Tooltip>

### ISSUE THREAD

**Issue by mcintyre94** [chakra-ui/chakra-ui#6852]
### Description

When I make a <Tooltip> the child of PopoverTrigger, its child cannot trigger the popover. 

### Link to Reproduction

https://stackblitz.com/edit/nextjs-k6xwdc?file=pages/index.js

### Steps to reproduce

Nest elements like this:

```js
    <Popover>
      <PopoverTrigger>
        <Tooltip label="Give feedback">
          <IconButton size="sm" aria-label="Give feedback" icon={<AddIcon />} />
        </Tooltip>
      </PopoverTrigger>
      <PopoverContent>
        <PopoverArrow />
        <PopoverCloseButton />
        <PopoverHeader>Confirmation!</PopoverHeader>
        <PopoverBody>Are you sure you want to have that milkshake?</PopoverBody>
      </PopoverContent>
    </Popover>
```

I've tried moving the tooltip, and this is the only place where it will actually render - but then the `IconButton` is not clickable to expand the popover. 

In my repro URL, the first button has the tooltip and clicking it doesn't work, the second button has no tooltip and clicking it opens the popover content.

### Chakra UI Version

1.8.5

### Browser

Google Chrome 106

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I tried using `<Tooltip isOpen={true}`, and clicking the always-open tooltip doesn't trigger the popover either. So I don't think the issue is that the tooltip text becomes the trigger.

**Comment by segunadebayo** [comment]
The reason this doesn't work is that the Popover Trigger needs to attach a `ref` to its children. The tooltip doesn't forward its ref to its content not the trigger hence the issue.

Here's a working code that coordinates the ref forwarding correctly.

```jsx
const ButtonWithTooltip = forwardRef((props, ref) => {
  const { label, ...rest } = props;
  return (
    <Tooltip label={label}>
      <IconButton
        ref={ref}
        size="sm"
        aria-label={label}
        icon={<AddIcon />}
        {...rest}
      />
    </Tooltip>
  );
});

const Page = () => {
  return (
    <Box padding="10">
      <Popover>
        <PopoverTrigger>
          <ButtonWithTooltip label="Give Feedback" />
        </PopoverTrigger>
        <PopoverContent>
          <PopoverArrow />
          <PopoverCloseButton />
          <PopoverHeader>Confirmation!</PopoverHeader>
          <PopoverBody>
            Are you sure you want to have that milkshake?
          </PopoverBody>
        </PopoverContent>
      </Popover>
    </Box>
  );
};
```

https://stackblitz.com/edit/nextjs-nk87b5?file=pages%2Findex.js

**Comment by mcintyre94** [comment]
Thanks a lot for your help, that works perfectly :)
