### ISSUE TITLE
On formatting numberInput the users cursor position is lost (moves to the end)

### ISSUE THREAD

**Issue by rtman** [chakra-ui/chakra-ui#6853]
### Description

When I format the number input to have commas, I expect the cursor position to be retained onChange but it is not

### Link to Reproduction

https://codesandbox.io/s/chakra-format-number-forked-xx6mcc?file=/pages/index.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/chakra-format-number-forked-xx6mcc?file=/pages/index.tsx
2. Click on the number input
3. Enter 1000
4. Change any character but the last 0, and see that the cursor jumps to the end.

### Chakra UI Version

2.2.8

### Browser

1.43.94 chromium

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

For reference, the expected behaviour can be seen here in this other components example
https://s-yadav.github.io/react-number-format/docs/customization#examples

**Comment by rtman** [comment]
I updated the codesandbox with a workaround using `Input` as `NumericInput` from `react-number-input`, though it's not ideal because you lose all the added functionality from `NumberInput`. 

@segunadebayo @TimKolberger any thoughts on how to do this in a more chakra way?

**Comment by itsajay1029** [comment]
Is someone working on this @segunadebayo ?

**Comment by segunadebayo** [comment]
@itsajay1029 Feel free to take a stab at it if you want 😃

**Comment by segunadebayo** [comment]
This has already been fixed in one of the recent PRs. We'll release an update shortly.

If the issue persists after the release, I'll re-open this issue.

**Comment by Zalart** [comment]
I think this problem is not solved so far.
My workaround was to add an additional changeHandler on NumberInputField component, to get access to event object:
```const onInputChange = (event: ChangeEvent<HTMLInputElement>) => {
			const caret = event.target.selectionStart;
			const element = event.target;

			window.requestAnimationFrame(() => {
				element.selectionStart = caret;
				element.selectionEnd = caret;
			});
		};
```
```
<InputGroup>
   <NumberInput {...props}>
      <NumberInputField onChange={onInputChange} />
 </NumberInput {...props}>
 </InputGroup>
```
