### ISSUE TITLE
Dark mode is broken in storybook after upgrading to @chakra/react 2.3.5

### ISSUE THREAD

**Issue by blechatellier** [chakra-ui/chakra-ui#6855]
### Description

When I toggle dark mode in storybook, I expect to see the dark version of a button but it doesn't work as expected

### Link to Reproduction

https://github.com/blechatellier/strokybook-chakra-bug

### Steps to reproduce

1.  Run `yarn storybook`
2. Go to the Button stories
3. Toggle dark mode

### Chakra UI Version

2.3.5 and up

### Browser

Version 1.42.88 Chromium: 104.0.5112.81 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Works with @chakra/react 2.3.4 and fails on 2.3.5 and 2.3.6

![image](https://user-images.githubusercontent.com/437646/196786870-71e9239e-53ac-4fed-9ae0-61b1549fb7d5.png)
![image](https://user-images.githubusercontent.com/437646/196786914-e27f1c40-3e02-4857-8554-a7db575f851e.png)

**Comment by blechatellier** [comment]
If I manually wrap up a ChakraProvider around the story without using "@chakra-ui/storybook-addon", it works, so I suspect the issue is with the addon.

**Comment by blechatellier** [comment]
Temporary solution to be able to use the latest @chakra/react version was to remove the storybook addon and implement my own theme toggle.

```interface ColorModeProps {
  colorMode: 'light' | 'dark';
  children: JSX.Element;
}

function ColorMode(props: ColorModeProps) {
  const { setColorMode } = useColorMode();

  useEffect(() => {
    setColorMode(props.colorMode);
  }, [props.colorMode]);

  return props.children;
}

export const decorators = [
  (Story, context) => {
    return (
      <ChakraProvider theme={theme}>
        <ColorMode colorMode={context.globals.colorMode}>
          <Story />
        </ColorMode>
      </ChakraProvider>
    );
  }
];

export const globalTypes = {
  colorMode: {
    name: 'Color Mode',
    defaultValue: 'light',
    toolbar: {
      items: [
        { title: 'Light', value: 'light' },
        { title: 'Dark', value: 'dark' }
      ],
      dynamicTitle: true
    }
  }
};
```

**Comment by VickyKoblinski** [comment]
Oops, I dupped this issue here https://github.com/chakra-ui/chakra-ui/issues/6922

**Comment by dconley1212** [comment]
Thanks, @blechatellier that was the fix for me!

**Comment by yougotashovel** [comment]
> Temporary solution to be able to use the latest @chakra/react version was to remove the storybook addon and implement my own theme toggle.
> 
> ```tsx
> interface ColorModeProps {
>   colorMode: 'light' | 'dark';
>   children: JSX.Element;
> }
> 
> function ColorMode(props: ColorModeProps) {
>   const { setColorMode } = useColorMode();
> 
>   useEffect(() => {
>     setColorMode(props.colorMode);
>   }, [props.colorMode]);
> 
>   return props.children;
> }
> 
> export const decorators = [
>   (Story, context) => {
>     return (
>       <ChakraProvider>
>         <ColorMode colorMode={context.globals.colorMode}>
>           <Story />
>         </ColorMode>
>       </ChakraProvider>
>     );
>   }
> ];
> 
> export const globalTypes = {
>   colorMode: {
>     name: 'Color Mode',
>     defaultValue: 'light',
>     toolbar: {
>       items: [
>         { title: 'Light', value: 'light' },
>         { title: 'Dark', value: 'dark' }
>       ],
>       dynamicTitle: true
>     }
>   }
> };
> ```

Where do you put this code?

**Comment by dconley1212** [comment]
@yougotashovel you put it in the preview file

**Comment by TheTedAdams** [comment]
I don't think https://github.com/chakra-ui/chakra-ui/pull/7154 actually fixed this issue... it looks like all that PR did was move the icon definitions...
