### ISSUE TITLE
`useDimensions` is deprecated but `useSize` is an internal utility

### ISSUE THREAD

**Issue by rafaelalmeidatk** [chakra-ui/chakra-ui#6856]
### Description

The `useDimensions` hook is marked as deprecated and it is written to use `useSize` instead, but there is no page in the docs for this hook and the `README.md` file says it is an internal hook and not intended for public usage: https://github.com/chakra-ui/chakra-ui/blob/3a87f68474221ed402fe5d169f7067763c8436d5/packages/hooks/use-size/README.md?plain=1#L5

 I tried to use it in a project but it looks like it is not exported yet, see the reproduction below

### Link to Reproduction

https://codesandbox.io/s/sparkling-surf-wbwhsc

### Steps to reproduce

1. Try to import `useSize`
2. The app crashes

### Chakra UI Version

2.3.6

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hey @rafaelalmeidatk. Yes, we'd like to keep it as an internal utility because it's subject to change before the next major release.

After the next major release, we'll consider adding it to the docs and exposing it's API

**Comment by rafaelalmeidatk** [comment]
Thanks for the response @segunadebayo! I understand the decision to not release the new hook until a major version, but if that's the case I think it makes sense to not deprecate `useDimensions` until we have an alternative. Or at least remove the instruction to use the hook that isn't available yet because its confusing.

**Comment by MTraveller** [comment]
Any update on this?

**Comment by OttlikG** [comment]
This utility would be very helpful.
Please release.

**Comment by mcreenan** [comment]
Hi, can the hook documentation at least be updated to reflect the actual state of each hook?

**Comment by hooch** [comment]
Please reopen this issue.  It's a showstopper.

**Comment by kjanred** [comment]
> Would be great to get the documentation updated.
> 
> In case it helps someone else:
> 
> ```
> import { useSize } from '@chakra-ui/react-use-size'
> const elementRef = useRef<HTMLDivElement>(null)
> const { width } = useSize(elementRef) ?? { width: null }
> return <Box ref={elementRef} />
> ```

Now it is saying useRef does not exist.

**Comment by asimplify** [comment]
> > Would be great to get the documentation updated.
> > In case it helps someone else:
> > ```
> > import { useSize } from '@chakra-ui/react-use-size'
> > const elementRef = useRef<HTMLDivElement>(null)
> > const { width } = useSize(elementRef) ?? { width: null }
> > return <Box ref={elementRef} />
> > ```
> 
> Now it is saying useRef does not exist.

You have to import useRef from react separately like this :
import { useRef } from "react";
