### ISSUE TITLE
Unable to define style for DrawerContent in theme

### ISSUE THREAD

**Issue by mohamed-bouksiaa** [chakra-ui/chakra-ui#6866]
### Description

By looking here https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/theme/src/components/drawer.ts I don't see a way to define a custom style everywhere in the app for the DrawerContent component.

### Link to Reproduction

https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/theme/src/components/drawer.ts

### Chakra UI Version

1.8.8

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by TylerAPfledderer** [comment]
Hey @mohamed-bouksiaa!

So the theme config for `DrawerContent` is a combination of the [baseStyleDialogContainer and baseStyleDialog styles](https://github.com/chakra-ui/chakra-ui/blob/95aa4499c72de28e91dd9274177c529db55e7964/packages/components/theme/src/components/drawer.ts#L32-L49).

Where the `dialog container` is the wrapper that spans the entirety of the window, and the `dialog` is the actual outer container holding the content.

Note the styles [in the component](https://github.com/chakra-ui/chakra-ui/blob/95aa4499c72de28e91dd9274177c529db55e7964/packages/components/modal/src/drawer-content.tsx#L52-L69) that call on `styles.dialog` and `styles.dialogContainer` which are the base styles from the config.

I hope this helps! 😄
