### ISSUE TITLE
createDescendantContext does not create a fresh new context

### ISSUE THREAD

**Issue by anilanar** [chakra-ui/chakra-ui#6869]
### Description

`createDescendantContext` does not create a fresh new context but instead shares a single context for all `createDescendantContext` invocations.

### Problem Statement/Justification

Due to it having just a single context, components that use descendants cannot be nested in each other.

For example, you cannot have a custom tab implementation (that uses `useTab` hook) inside a menu (where each menu item is a tab).

### Proposed Solution or API

I don't see why `createDescendantContext` would not just create a new context, and why individual hooks are not parametrized by it.

New implementation:

```ts
export function createDescendantContext<
  T extends HTMLElement = HTMLElement,
  K extends Record<string, any> = {},
>() {
  const ContextProvider = createContext(({ ... }))

  const useDescendantsContext = createUseDescendantsContext(ContextProvider)

  const useDescendant = createUseDescendant(ContextProvider);

  const useDescendants = createUseDescendants(ContextProvider);

  return [
    // context provider
    ContextProvider,
    // call this when you need to read from context
    useDescendantsContext,
    // descendants state information, to be called and passed to `ContextProvider`
    useDescendants,
    // descendant index information
    useDescendant,
  ] as const
}
```

**Comment by BruceHubbard** [comment]
I think I may have just hit this bug (took me forever to triage it).  We have some page tabs along our header (using Chakra's <Tabs>) and we have logic that checks if the number of tabs is > 5 and if so it pushes some of the tabs into a dropdown (using Chakra's <Menu> component).  It worked fine in 1.2.1 but I'm trying to upgrade to 1.8.8 and this broke during the upgrade (currently trying to find a workaround).

**Comment by BruceHubbard** [comment]
Here's a Codesandbox that show's the problem: https://codesandbox.io/p/sandbox/lucid-architecture-twlvwc?file=%2Fsrc%2Findex.js

If you click on the "More ^" menu button and then click on the "three" tab is shows two's content instead of three

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by BruceHubbard** [comment]
Awesome, thanks @segunadebayo!
