### ISSUE TITLE
[Drawer] DrawerOverlay allow to scroll content in IOS

### ISSUE THREAD

**Issue by polRk** [chakra-ui/chakra-ui#687]
Go to https://chakra-ui.com/drawer, open drawer in iPhone, and try to touchMove DrawerOverlay, as a result you can scroll document and **can't** scroll DrawerContent... It's a seriously bug!

PS. You can't scroll DrawerContent if scroll event on DrawerOverlay hasn't ended yet

**Comment by hoehooiyan** [comment]
Noticed this today as well, hope it will be fixed soon 😥

**Comment by hfellerhoff** [comment]
This looks like a Modal issue, as the document scroll on iOS happens with Modals as well (which is what Drawer is build off of).

**Comment by segunadebayo** [comment]
Thanks for chiming in @hfellerhoff.

Indeed it's related to the `body-scroll-lock` library and we've changed to use to a more reliable and actively maintained library "react-remove-scroll".

This issue has been fixed and we'll release an update shortly.

Thanks for reporting this @polRk
