### ISSUE TITLE
Chakra Modal expecting react to be imported

### ISSUE THREAD

**Issue by Daggron** [chakra-ui/chakra-ui#6871]
### Description

I am using Chakra with Typescript and When I am trying to use Modal component in my app an error is being thrown by ts "'React' refers to a UMD global, but the current file is a module. Consider adding an import instead". This is asking me to import React in my component and when I import react the error goes away. Since we are using react-18 there is no need to import react but Modal component usage forces me to import react in my code.

### Link to Reproduction

https://codesandbox.io/s/elated-archimedes-x58cif?file=/src/App.tsx

### Steps to reproduce

1. Go to 'App.tsx'
2. Hover over the Error lines shown for Modal and Modal content

### Chakra UI Version

2.3.6

### Browser

NA

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

- Ts version 4.8.4
- React version 18.2.0

**Comment by mcctrix** [comment]
When i tried that in fresh vite react ts app, it's working fine.
![image](https://user-images.githubusercontent.com/42296139/197210534-bfd9e855-77ea-4e96-a1b9-7aca24bab45c.png)

**Comment by Daggron** [comment]
> When i tried that in fresh vite react ts app, it's working fine. ![image](https://user-images.githubusercontent.com/42296139/197211218-96059519-f377-4032-a9b8-a153247d82cd.png)

Which Version of chakra you are using ?
Its not working in sandbox either, so definitely not a problem with the setup.

**Comment by itkrt2y** [comment]
Use `"jsx": "react-jsx"` instead of `"jsx": "react"` in tsconfig.json

**Comment by Daggron** [comment]
> Use `"jsx": "react-jsx"` instead of `"jsx": "react"` in tsconfig.json

But Why, Why does this problem only comes for Modal and Not for other components ?

**Comment by anubra266** [comment]
@Daggron This issue is not chakra related. It's Typescript.
