### ISSUE TITLE
[DOM] Found 6 elements with non-unique id #pin-input   when I using PinInput

### ISSUE THREAD

**Issue by diqye** [chakra-ui/chakra-ui#6872]
### Description

a error apear When i useing PinInput 

### Link to Reproduction

Don't need codesandbox

### Steps to reproduce

1. Create nextjs project (rendered by server)
2. to use PinInput and PinInputField component 
3. browse your page
<img width="871" alt="image" src="https://user-images.githubusercontent.com/34941345/197225911-012d1621-28a2-4535-bcf4-b81911427803.png">

The reason is that to have same id when rendered by server , see the image below.
<img width="870" alt="image" src="https://user-images.githubusercontent.com/34941345/197226501-8606c737-b112-4eae-8b47-44a335512569.png">

### Chakra UI Version

^2.0.4

### Operating System

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I just pushed a fix for this. You should be able to pass `index` to each pin input field instead. That way, the id will be consistent on the server.

We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
