### ISSUE TITLE
[IconPaths] Component has a big size

### ISSUE THREAD

**Issue by polRk** [chakra-ui/chakra-ui#689]
I do not use chakra icons, but they are present in my bundle.
<img width="1422" alt="Снимок экрана 2020-05-09 в 10 11 13 AM" src="https://user-images.githubusercontent.com/39828645/81466871-7d0c9d00-91dd-11ea-9714-2e5162cd8e7b.png">

**Comment by with-heart** [comment]
Hi @polRk! We have moved revised how icons work in Chakra in 1.0, and they have been moved to their own separate package (`@chakra-ui/icons`). This should no longer be an issue once 1.0 is released.

See https://next.chakra-ui.com/ for more information about the upcoming release!
