### ISSUE TITLE
`BreadcrumbSeparator` won't display when inside a fragment

### ISSUE THREAD

**Issue by bl-ue** [chakra-ui/chakra-ui#6897]
### Description

When using a `BreadcrumbItem` inside a React fragment instead of directly inside a `Breadcrumb`, the `BreadcrumbSeparator` for that item will not be displayed.

### Link to Reproduction

https://codesandbox.io/s/small-browser-z1pcdp

### Steps to reproduce

1. Go to reproduction CodeSandbox
2. Each number should be in its own breadcrumb, but breadcrumbs 3, 4 and 5 are all in the same breadcrumb.

### Chakra UI Version

1.8.9

### Browser

Google Chrome 106

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Hi @bl-ue,

This is happening because Breadcrumb is using `cloneElement` and needs to forward certain properties to its direct children.

Consider providing the separator manually:

```jsx
<Breadcrumb separator={null} spacing={0}>
        <BreadcrumbItem key="1">
          <BreadcrumbLink>1</BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbSeparator mx="4" color="gray.300">
          /
        </BreadcrumbSeparator>
        <BreadcrumbItem key="2">
          <BreadcrumbLink>2</BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbSeparator mx="4" color="gray.300">
          /
        </BreadcrumbSeparator>
</Breadcrumb>
```

https://codesandbox.io/s/infallible-golick-9mz2lc?file=/src/index.js
