### ISSUE TITLE
Disable a11y focus returning globally

### ISSUE THREAD

**Issue by polRk** [chakra-ui/chakra-ui#690]
How can i disable focus returning ? Close menu, popover, drawer, i do not want to return focus. Focus returning causes a lot of inconvenience. I'm using chakra for developing my CRM, for a small circle of people.

See https://github.com/chakra-ui/chakra-ui/issues/213.
Turn off https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/Menu/index.js#L95-L100

**Comment by segunadebayo** [comment]
Hi @polRk,

This will go against our accessibility standards, but we can give it some thoughts if you can provide a valid use-case that doesn't impact accessibility.

**Comment by polRk** [comment]
1. Open the popup menu
2. Click on the button that is outside the popup-menu
3. Click does not occur, because first there is a loss of focus, you need to click again ( 2 clicks )
