### ISSUE TITLE
isChecked prop on Radio Buttons ineffective if a value is set

### ISSUE THREAD

**Issue by stellenberger** [chakra-ui/chakra-ui#6902]
### Description

Pretty simple bug; the isChecked={true | false} prop does not work when a value is set

### Link to Reproduction

https://codesandbox.io/s/goofy-easley-9l8l6f?file=/src/App.js

### Steps to reproduce

Render a radio button as follows: 

```
 <RadioGroup>
  <Stack direction='column'>
    <Radio isChecked={true} onChange={handleOnChange} name="a_name" value='a_value' data-id="tt_radius">Radius</Radio>
  </Stack>
</RadioGroup>
```

Notice that the radio button does not check, even with the isChecked prop, if the value is set. If the value is removed, it is fine. 

### Chakra UI Version

^2.2.1

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

We neeeeeeeeeeeeed to set a value!!!!!!!!!

**Comment by tkanzakic** [comment]
This is because you have your `Radio` inside a `RadioGroup` and in this case the behaviour of the parent component takes precedence, this should work as expected:

```
  <Stack direction='column'>
    <Radio isChecked={true} onChange={handleOnChange} name="a_name" value='a_value' data-id="tt_radius">Radius</Radio>
  </Stack>
```

or as [suggested in the documentation](https://chakra-ui.com/docs/components/radio/usage#usage) move the behaviour to the `RadioGroup`

**Comment by segunadebayo** [comment]
Closing this as @tkanzakic explained the solution perfectly.
