### ISSUE TITLE
[Menu/Avatar] Z-index of Avatar component is overlapping with dropdown of Menu component

### ISSUE THREAD

**Issue by ghoshnirmalya** [chakra-ui/chakra-ui#691]
**Describe the bug**
When the Avatar component is present below the MenuList component, then the Avatar  component appears on top of the MenuList component.

<img width="462" alt="Screenshot 2020-05-09 at 7 12 42 PM" src="https://user-images.githubusercontent.com/6391763/81475381-71df5e80-9229-11ea-9f1c-982fa09858ba.png">

**Expected Behavior**
The Avatar component shouldn't appear on top of the MenuList component.

<img width="483" alt="Screenshot 2020-05-09 at 7 18 18 PM" src="https://user-images.githubusercontent.com/6391763/81475435-df8b8a80-9229-11ea-83c5-1e5541ad788d.png">

**To Reproduce**
Add an Avatar component just below a Menu component with a MenuList inside it. [Link to the issue in CodeSandbox](https://codesandbox.io/s/chakra-ui-issue-with-menu-and-avatar-component-lu0q7).

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome
 - Version: 81.0.4044.138

**Comment by ghoshnirmalya** [comment]
## Possible solution:
We can replace the value of `z-index` for the [Menu component](https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/Menu/index.js#L334) to a much higher value (eg: like popover, which has a `z-index` value of [1500](https://github.com/chakra-ui/chakra-ui/blob/24b9df8b73c45735579f4a9e5a16e71b3703f432/packages/chakra-ui-docs/pages/theme.mdx#z-index)).

**Comment by segunadebayo** [comment]
Thanks for reporting this @ghoshnirmalya.

In V1, Avatar no longer uses `z-index`, this fixes the issue with the overlapping.

We'll release an update shortly.

Thanks

**Comment by talksik** [comment]
I am still seeing this issue. Avatar showing on top of popover :(
