### ISSUE TITLE
ColorModeContext / ColorModeProvider default initial mode

### ISSUE THREAD

**Issue by najibghadri** [chakra-ui/chakra-ui#692]
I have been reading through the src code, but I didn't find an elegant way to set the initial default colormode to dark instead of light. Is there a way? If not do you think it's enough to check in index.js if it is set in localStorage, if not set it to dark? Thanks!

**Comment by najibghadri** [comment]
Okay, sorry for asking, this simple snippet worked in index.js. Still it could be put I think, but I have no idea how to make it for you, I don't use typescript yet :/ :)

```
if (localStorage.getItem("darkMode") === null) {
  localStorage.setItem("darkMode", "true");
}
```

**Comment by with-heart** [comment]
Hi @najibghadri! One of the major features of our upcoming 1.0 release is better color mode support. 

> We've fixed the bugs related to Color mode and it's now easy to persist color mode, set initial color mode, and lock specific components to a certain color mode.

See #696 for more information. Thanks for sharing your workaround for anyone who needs this now.
