### ISSUE TITLE
transform: translate() not working.

### ISSUE THREAD

**Issue by yanivdouieb** [chakra-ui/chakra-ui#6921]
### Description

Hello, I would like to know why putting ```transform: translate(-50%, -50%)``` on the style file with Chakra does not work. The text should normally be centered in the middle of the screen, but this is not the case. So how can I center an element in the center of the screen with Chakra UI?

### Link to Reproduction

--

### Chakra UI Version

2.3.6

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Please follow the issue template as we're not able to act on issues that are lacking important information.
