### ISSUE TITLE
useClipboard does not copy dynamic input anymore

### ISSUE THREAD

**Issue by JonrGull** [chakra-ui/chakra-ui#6923]
### Description

Let me start off by saying I may have made a mistake and am not thinking correctly, and I apologize in advance.

However, I recently updated my small project to V2 and suddenly my `useClipboard` hook just doesn't copy a passed value anymore. The example on the page will copy the initial value, but if you create a function that changes it, it doesn't seem to work.

It used to work fine in `1.8.8` or so.

I'll keep working on it, but I've been utterly stumped for hours. As soon as I switch y Chakra UI version to below version 2, it works without touching anything else.

Please take a look and let me know. 

### Link to Reproduction

https://codesandbox.io/s/wild-bird-vn0e8h?file=/src/index.tsx

Here is a Nextjs example which is closer to what my project is:

2.3.6 example with `useClipboard` not working
https://codesandbox.io/s/chakra-2-3-6-ncxl8j?file=/pages/index.tsx

working 1.8.9 example
https://codesandbox.io/s/chakra-1-8-9-jq3nu4?file=/pages/index.tsx

### Steps to reproduce

1. Setup project to use `useClipboard`
2. Pass `useClipboard` a value from `useState` 
3. Click 'Copy'
4. Copied string will likely be the last thing in your clipboard, because it tries to copy an empty string.

### Chakra UI Version

2.3.6

### Browser

Edge

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by tuananhl** [comment]
hey @JonrGull 
The way to set the value of `useClipboard` hook was changed in this ticket https://github.com/chakra-ui/chakra-ui/issues/6759.
The doc for this hook is updated some mins ago. So I think you should keep your app in 1.8 or wait for the author

**Comment by JonrGull** [comment]
> hey @JonrGull The way to set the value of `useClipboard` hook was changed in this ticket #6759. The doc for this hook is updated some mins ago. So I think you should keep your app in 1.8 or wait for the author

Dang I did my best to search for similar issues! Thank you, I'll close this.
