### ISSUE TITLE
Scrolling inside modal with list of checkboxes doesn't work on mobile device

### ISSUE THREAD

**Issue by sunnyfeijen** [chakra-ui/chakra-ui#6924]
### Description

On a mobile device (or any touch device I think):
On a page that is long enough to scroll you can scroll the page when starting your scroll movement on a CheckboxGroup (on the text labels).
But when the same CheckboxGroup is inside a modal you can't scroll when starting the scroll on the checkbox or text labels.

### Link to Reproduction

https://codesandbox.io/s/relaxed-neco-mbvxvj?file=/src/index.tsx

### Steps to reproduce

1. Go to the codesandbox on a mobile device (I tested on Android - Samsung s21 - Chrome)
2. Click on either 'open modal' or 'open modal 2'
3. Try to scroll when starting scroll movement on the checkbox list, doesn't work. But when starting outside the test of the checkbox list it works.

### Chakra UI Version

~~2.3.5~~ 2.4.9

### Browser

Google Chrome 106

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

A link to a [screen recording](https://youtu.be/KBEP-h9PT9I)

**Comment by itsajay1029** [comment]
Can I work on this issue ? @sunnyfeijen

**Comment by themeltdown** [comment]
Ran in to this issue as well.. And still persistant

**Comment by thienphanexcalibur** [comment]
![image](https://user-images.githubusercontent.com/31528474/220400700-a5d794c7-4c21-48d5-8c93-a910816346a8.png)
You need to add `scrollBehavior` props to the `Modal` component. 
I have just reproduced your issue and it worked by doing so.

**Comment by sunnyfeijen** [comment]
@thienphanexcalibur Sorry but that doesn't solve the issue. The problem is that you cant start the scroll (on touch devices) inside the checkbox list.

**Comment by PepeIksde** [comment]
I'm having the same issue

**Comment by PepeIksde** [comment]
Hello Segunadebayo update to @chakra/2.5.4, @chakra/2.5.5 doesn't solve the issue.

**Comment by PepeIksde** [comment]
![image](https://user-images.githubusercontent.com/95045233/228948746-1d561985-fb42-4bb6-b925-7001981f2d86.png)
