### ISSUE TITLE
where the https://github.com/chakra-ui/awesome-chakra-ui ?

### ISSUE THREAD

**Issue by hinego** [chakra-ui/chakra-ui#6928]
### Description

where the https://github.com/chakra-ui/awesome-chakra-ui ?

### Problem Statement/Justification

where the https://github.com/chakra-ui/awesome-chakra-ui ?

### Proposed Solution or API

where the https://github.com/chakra-ui/awesome-chakra-ui ?

### Alternatives

where the https://github.com/chakra-ui/awesome-chakra-ui ?

### Additional Information

where the https://github.com/chakra-ui/awesome-chakra-ui ?

**Comment by segunadebayo** [comment]
Hello. We deprecated that repo. Kindly open an issue/discussion in the docs if you have any questions
