### ISSUE TITLE
Dark mode hue settings

### ISSUE THREAD

**Issue by KidLinus** [chakra-ui/chakra-ui#6931]
### Description

I'm writing an Application that's designed to be dark mode first. All my colors are however washed out to arbitrary hues in Chakra when the dark mode is enabled.

Buttons for instance are just picking [colorScheme].200 in dark mode and [colorScheme].500 in light mode. 

How can I work with this library so that colors stay in the tint that I told them to and still use dark mode so that I'm not working agains the library?

I know I can override a button components style but it is per compoenent. If i did this I'd be re-skinning the entire library and then what would be the point of using Chakra?

### Problem Statement/Justification

Without this support the dark and light mode is simply unusable unless you are fine with incorrect colors or strange animations due to overriding multiple tints in your colors.

### Proposed Solution or API

There are many ways to go about this. A few ways would be:

- Stop hardcoding tints in components.
- Allow colors and their tints to be defined per theme
- Stop hard-wiring dark/light theme into the lib and instead let the supplied theme just be the theme. Perhaps provide tools to generate a dark theme from a light one to ease development.

### Alternatives

Changing framework or wiriting the dark ui in light mode and overriding all colors and components.

**Comment by KidLinus** [comment]
Example of what I mean by hardcoded:
https://github.com/chakra-ui/chakra-ui/blob/eb8bff911e6ec9de0165ab1e8f5ca10d5e022459/packages/theme/src/components/button.ts#L89

**Comment by anubra266** [comment]
@KidLinus What you're looking for is how to customize the theme. This hardcoded styles are just the default theme, you can customize the theme and it will be applied to all your buttons.
Learn more on how to customize a component theme [here](https://chakra-ui.com/docs/styled-system/component-style)

**Comment by xencodes** [comment]
shouldn't there be an option to set which tint to use for dark mode and light mode? 
like when i am setting `colorScheme` to `orange` or something on a button, it automatically picks orange's light shade on dark which makes it looks a little weird.
