### ISSUE TITLE
Incorrect selection problem for button color

### ISSUE THREAD

**Issue by soheilhassanjani** [chakra-ui/chakra-ui#6936]
### Description

Hello . I added a new color in the project with the color code #dbff74 , which is almost a phosphorescent color. When I use this color for the button, the text inside the button is white, which is not legible at all. How can I solve this problem?

### Link to Reproduction

https://codesandbox.io/s/interesting-leftpad-16nqg1?file=/pages/index.tsx

### Chakra UI Version

2.3.6

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hey @soheilhassanjani,

You can use the `color` prop, which is used you've done. That's one way.

Another way is to update the theme for the button component like so:

```jsx
const theme = extendTheme({
  colors,
  components: {
    Button: {
      variants: {
        solid: {
          color: "gray.800"
        }
      }
    }
  }
});
```

That way, it's always legible for the solid variant of the button.

Here's a sandbox:
https://codesandbox.io/s/festive-bassi-ff8nrg?file=/pages/_app.tsx

**Comment by soheilhassanjani** [comment]
@segunadebayo 
Inside Bootstrap, when we add a new color, such as Chakra, it automatically selects the right color for the texts. I had the same problem in Bootstrap, which apparently had a variable called $min-contrast-ratio, which was corrected by changing its number. Do we have such a thing in the chakra?
