### ISSUE TITLE
Icons have no way of touching defaultProps

### ISSUE THREAD

**Issue by saltnpixels** [chakra-ui/chakra-ui#6939]
### Description

When using the Icon component it does not seem to have any part in the theme object. This means we cannot alter the icon default props. Namely the height set to 1em. This should be auto.

Not every icon is perfectly square. And 1em on the height can chop it a bit. 

The width can be 1em but height should be auto.

### Link to Reproduction

no link

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.3.7

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
@anubra266 Let's hook up the Icon to the theme
