### ISSUE TITLE
Scoping global CSS reset

### ISSUE THREAD

**Issue by selbekk** [chakra-ui/chakra-ui#6946]
### Description

We're introducing Chakra into a legacy application, and when we add a `ChakraProvider` to a part of our application, the entire site is changed.

This is due to the global CSS reset that Chakra ships with. I can remove the css reset with the (undocumented) `resetCSS` property, but then everything looks weird.

This makes is really painful to introduce Chakra to legacy codebases.

### Problem Statement/Justification

This would make it possible to introduce Chakra into legacy applications.

### Proposed Solution or API

We could make the ChakraProvider add an auto-generated class name to the CSS reset, and scope it that way. However, adding a class in front of all css resets, makes it override the component specific styles (the specificity is higher). So that won't work.

We could add the same class in front of all emotion generated code as well (somehow). Not sure how that would work though

**Comment by franky47** [comment]
Another use-case for this is to allow Chakra to be used in components that are destined to be used in potential non-Chakra apps.

I'm working on a devtools component for a headless frontend library (similar to what is done by the [React Query devtools](https://tanstack.com/query/v4/docs/devtools), and Chakra would be ideal to build its UI.

However, not every consuming app would be using Chakra at its root, and:
- injecting the CSS reset would break the host app's styles
- not injecting it would break the devtools' styles

One solution that requires minimal refactoring would be to expose the css injected in Emotion's `<Global/>` component, possibly in several parts:
- reset styles for the root elements (html, body, main)
- reset styles for the other element types

This way, an isolated Chakra component could:
- Wrap itself in a `ChakraProvider`, but not apply the global CSS reset
- Import the reset styles and inject them scoped to the component's container, using CSS modules

**Comment by tecbird** [comment]
+1
