### ISSUE TITLE
Support setting the default toast position in  theme

### ISSUE THREAD

**Issue by RobinClowers** [chakra-ui/chakra-ui#6949]
### Description

Right now, if you want all toasts to appear in a custom location, you have to remember to set it in every place, or wrap the `useToast` hook (and remember to use that!). It would be great if you could set the default position in the theme.

### Problem Statement/Justification

Chakra supports theming and setting default props for other similar things, so it seems very reasonable that it would support this as well. May apps have their all their toasts appear in the same area, and having to remember to set a property to the same value all the time is error prone.

### Proposed Solution or API

I'm not 100% sure the right way to do this, but maybe a new `defaultProp` on the `Toast` component?

### Alternatives

As I mentioned, you could wrap the `useToast` hook, but that's not ideal, and doesn't handle stand alone toasts either.

### Additional Information

I found the current default hard coded here: https://github.com/chakra-ui/chakra-ui/blob/6774510dea8e669a91e8cb78a8a033c38cd24311/packages/components/toast/src/toast.placement.ts#L30

**Comment by simonpeters** [comment]
is this still in the works?

**Comment by segunadebayo** [comment]
Right now, you're able to do this by passing the `toastOptions` to the `ChakraProvider`

```jsx 
<ChakraProvider toastOptions={{ defaultOptions: { position: "left" } }}>
   <App />
</ChakraProvider>
```
