### ISSUE TITLE
Menu List not responding on click

### ISSUE THREAD

**Issue by rohith033** [chakra-ui/chakra-ui#6959]
### Description

When I am Trying to access menu it is not responding

### Link to Reproduction

.

### Steps to reproduce

`<Menu>
        <MenuButton as={IconButton} icon={<FcMenu />} variant='outline' color='gray.400' />
        <MenuList>
          <Link href='/' passHref>
            <MenuItem icon={<FcHome />}>Home</MenuItem>
          </Link>
          <Link href='/Search' passHref>
            <MenuItem icon={<BsSearch />}>Search</MenuItem>
          </Link>
          <Link href='/Buy Property' passHref>
            <MenuItem icon={<FcAbout />}>Buy Property</MenuItem>
          </Link>
          <Link href='/Rent Property' passHref>
            <MenuItem icon={<FiKey />}>Rent Property</MenuItem>
          </Link>
        </MenuList>
      </Menu> `

### Chakra UI Version

^2.3.7

### Browser

Brave

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Utkarshn10** [comment]
Hey @rohith033 could you specify the error ?

**Comment by Utkarshn10** [comment]
Hey @rohith033 i tried to replicate the lines above and the issue i faced was with the icons. So i changed the **FiKey** to **FcKey** and **BsSearch** to **FcSearch** and this is working fine.

### Here's the line after changes :

`<Menu> <MenuButton as={IconButton} icon={<FcMenu />} variant='outline' color='gray.400' /> <MenuList> <Link href='/' passHref> <MenuItem icon={<FcHome />}>Home</MenuItem> </Link> <Link href='/Search' passHref> <MenuItem icon={<FcSearch />}>Search</MenuItem> </Link> <Link href='/Buy Property' passHref> <MenuItem icon={<FcAbout />}>Buy Property</MenuItem> </Link> <Link href='/Rent Property' passHref> <MenuItem icon={<FcKey />}>Rent Property</MenuItem> </Link> </MenuList> </Menu>`

### **Output :** 

![Screenshot (181)](https://user-images.githubusercontent.com/58587256/201321573-bd0b83df-0cb2-4f4b-a914-30c21dc76d26.png)

**Comment by segunadebayo** [comment]
Thank you for helping @Utkarshn10. I hope that solution helps you @rohith033

You didn't provide sufficient information for us to understand and reproduce the problem.
