### ISSUE TITLE
Road to TypeScript Release

### ISSUE THREAD

**Issue by segunadebayo** [chakra-ui/chakra-ui#696]
Hey Chakra people,

I'm glad to let you know that we're now entering the final phase of the TypeScript release. It's been super challenging and took a lot of work + collaboration to get this working. If you contributed to this release and you're reading this, THANK YOU 💖.

Here's a detailed list of new features and breaking changes to expect in the next release.

## New Features & Changes 🥳

- **Component Theming API:** This is a simple way to style any components and its modifiers (sizes, variants, and color scheme) from the theme object or locally within a `chakra` factory function. To get an idea, see #695 

- **Better Color Mode Support:** We've fixed the bugs related to Color mode and it's now easy to persist color mode, set initial color mode, and lock specific components to a certain color mode.

- **Low-level Hooks:** For some components, we'll give users access to their internal React hooks implementation to make it possible to create custom versions of the same component.

- **Better TypeScript support:** This means all components have very good TypeScript support and most low-level components like `Box`, `Flex`, etc. will support the `as` prop and types will be extracted properly.

## Breaking Changes 💣

Here are a few obvious breaking changes, in the docs we'll make sure we provide a detailed step-by-step migration plan.

- We're renaming all `variantColor` prop to `colorScheme` to make it easier to understand that this prop represents a visual color style, not a css color attribute. For example, when I say "an outline button with a red color scheme", it's easier to picture what the button looks like without seeing the code or UI.

- We're removing support for the `size` layout prop. We think the `size` prop should be constrained to only components (for now). The size prop has caused a lot of confusion in general because in some components it means the visual size, and in some, it means  width+height. **We recommend you use `w` or `width` and `h` or `height` as a replacement for size.**

- We're deprecating a few style props to reduce the general style props API surface. We'll document these in the docs.

## Timeline

We're looking to complete this before the end of May but we'll need all the help we can get. The worst-case scenario is the end of June if all goes well.

## Now we need your help

It's a lot of work the team has put into this release, now that we're pretty close to "DONE", we need some help to get us to the finish line.

If you feel you're able to give us 30minutes - 1 hour of your time over the next 1-2 weeks, please let me know. Thanks in advance 💖

**Here are some areas we need help with:**
- Setup the build, test, and release pipeline using Github Actions.
- Write rich, interactive docs and tutorials for the next release (I'll walk you through this part)
- Write translations once we've made progress with the English translation
- Review code against issues and ensure we've fixed most of the issues
- Revamp the website's interface and experience to make it super easy to find/explore components.

Thank you and I can't wait to get this next release out into your hands so you can build your websites & apps even faster.

Cheers 🥂

**Comment by with-heart** [comment]
So excited! There is so much additional quality coming in the next release! Chakra keeps getting better and better. Thanks for all of your hard work @segunadebayo.

I'll commit to working on documentation and tutorials, reviewing code, fixing bugs, and working on the website interface and experience. I'm also happy to help anyone that would like to get involved!

**Comment by singingwolfboy** [comment]
Hey @segunadebayo, I'm happy to help set up GitHub Actions! I've been playing with it a lot lately, and it's a really powerful and flexible system. Let me know what you need, and I'll try to make it happen! Might be easiest to do a videocall at some point to chat about it.

**Comment by margalit** [comment]
> I'll commit to working on documentation and tutorials, reviewing code, fixing bugs, and working on the website interface and experience. I'm also happy to help anyone that would like to get involved!

@with-heart I’d love to contribute by adding search functionality if this hasn’t already been completed/assigned.

**Comment by with-heart** [comment]
That would be AWESOME @margalit! #326 has been hanging around for awhile but let's continue the conversation there :)

**Comment by segunadebayo** [comment]
@singingwolfboy That's cool. Join our discord: https://discord.gg/bysKUD and send me a DM so we can talk about this.

Thank you!

**Comment by murbanowicz** [comment]
I am glad to see this issue. 
For me, it is 'no go' with Chakra at the moment because of no TS support.
I am not able to help with preparing the code at the moment, but in the future of if you will need TS review - I am here to help, so feel free to ping me with PRs if you want to.

**Comment by b-b0t** [comment]
@segunadebayo this is great. Will this release resolve SSR dark mode issues on Next.js or are PR's needed for that?

**Comment by segunadebayo** [comment]
@murbanowicz, Chakra does have TS support, we're only working to improve it.

@b-b0t Yes, this will resolve that.

**Comment by neilchaudhuri** [comment]
I am beginning to work on the components for a brand new design system for our client. I am definitely using Chakra UI as the foundation for it because it's awesome, but I have been debating whether to use Chakra UI's native theming or integrating it with Theme UI. 

It seems like the fastest way to go is the former, but judging from comments in other GitHub issue threads, it seems like Theme UI is the future in a few months or so.

Is this an accurate assessment? If so, I will probably choose to start from Theme UI and integrate it with Chakra UI to be better prepared for the future since the difference in effort doesn't seem prohibitive and since the two can work even without the `sx` prop.

Please let me know if this seems like a reasonable approach, or if you would suggest something different.

**Comment by remorses** [comment]
I noticed that `@emotion/core` is currently a dependency of `@chakra-ui/system`, instead it should be a peer dependency to not duplicate the theme context instance

It would be cool to have an `alpha` release to try out the new stuff, you can release an alpha version using `lerna publish --canary --preid alpha`

**Comment by mwood23** [comment]
I can help with proofing the TS docs comments, testing, and reviewing the types! Let me know when the branch is ready to poke at and I'll run through it.

**Comment by with-heart** [comment]
We're planning on releasing an alpha version sometime in the next week or two if all goes according to plan. We definitely want to get this in front of the community so we can gather feedback and work through any issues before releasing to the public.

**Comment by bmitchinson** [comment]
> @singingwolfboy That's cool. Join our discord: https://discord.gg/bysKUD and send me a DM so we can talk about this.
> 
> Thank you!

Anyway you could post an updated discord link, would love to join but it expired.

**Comment by aaronmcadam** [comment]
Hey @bmitchinson, try this link: https://discord.gg/Fbd5J2

**Comment by mrmckeb** [comment]
It looks like those Discord links expire fast. 

I'd like to jump in and help with this release, and see if I can knock off some items from #801. Can someone shoot me an invite? I'm on Discord (CRA, Storybook orgs) as mrmckeb#6289.

**Comment by kimroen** [comment]
The default expiry is one day. Here’s one that doesn’t expire: https://discord.gg/RKXwfXm

Welcome!
