### ISSUE TITLE
Heading line height is cropping the text

### ISSUE THREAD

**Issue by beltranrengifo** [chakra-ui/chakra-ui#6971]
### Description

When I use a `Heading as="h2" size="3xl" noOfLines={1}` the text gets cropped at the bottom

![image](https://user-images.githubusercontent.com/19485114/201420300-5516cc09-0f97-4c89-ae13-cbc7f5ce54a4.png)
![image](https://user-images.githubusercontent.com/19485114/201420408-6be11906-414a-4972-888b-11809eb11009.png)

If I use `line-height: normal;` things seem normal.

Plz let me know if I can help. I'm new to Chakra so maybe I missing something. Thank you!!! ❤️ 

### Link to Reproduction

https://codesandbox.io/s/chakra-heading-cropped-9siw4w

### Steps to reproduce

1. Add a new Heading component with this settings `as="h2" size="3xl" noOfLines={1}`
2. Add this text to the Heading component: `✏️ Fill in your data!`
3. The text, the `y` is cropped in the bottom
4. See error:
![image](https://user-images.githubusercontent.com/19485114/201421916-45562704-43bd-47a8-b28f-2ba859be40ce.png)

### Chakra UI Version

React 2.3.7

### Browser

Chrome Version 106.0.5249.119 (Official Build) (x86_64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi  @beltranrengifo,

This is a visual issue in Chakra itself. Unfortunately, we can't change it immediately because it'll be considered a breaking change.

You can override the lineHeight manually by passing style properties to the Heading component.

```jsx
<Heading as="h2" size="3xl" noOfLines={1} lineHeight="normal">
      ✏️ Fill in your data!
</Heading>
```

**Comment by beltranrengifo** [comment]
Thank you for your response!
