### ISSUE TITLE
gatsby5 compatibility

### ISSUE THREAD

**Issue by wryfi** [chakra-ui/chakra-ui#6976]
### Description

Gatsby 5 is recently released, but the gatsby-plugin isn't compatible. At first glance, it appears to just need its `package.json` updated similar to the following:

```
--- ../../../chakra-ui/chakra-ui/tooling/gatsby-plugin/package.json	2022-11-12 07:56:32.000000000 -0800
+++ package.json	2022-11-12 08:19:48.000000000 -0800
@@ -16,10 +16,10 @@
   },
   "peerDependencies": {
     "@chakra-ui/react": ">=2.0.0",
-    "gatsby": "^2.29.3 || ^3.0.0 || ^4.0.0"
+    "gatsby": "^2.29.3 || ^3.0.0 || ^4.0.0 || ^5.0.0"
   },
   "devDependencies": {
-    "@chakra-ui/react": "workspace:*",
-    "gatsby": "^4.18.2"
+    "@chakra-ui/react": ">=2.0",
+    "gatsby": "^5.0.0"
   }
 }
```

Not sure why but setting the `@chakra-ui/react` version to `workspace:*` didn't work for me with npm, so I had to change to match the version number above. ymmv.

### Problem Statement/Justification

chakra should be compatible with the latest Gatsby.

### Proposed Solution or API

see description

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
