### ISSUE TITLE
Last element of WrapItem component doesn't display boxShadow

### ISSUE THREAD

**Issue by GKosheev** [chakra-ui/chakra-ui#6986]
### Description

I use ```Wrap``` component with ```WrapItems``` in my project. When I added ```boxShadow``` to each of the ```WrapItem```, I noticed that, for some reason, the last element of it doesn't display ```boxShadow``` properly (it only touches the corners). 
If I add an additional ```WrapItem``` at the end of all items, and set ```visibility="hidden"```, I can see the full ```boxShadow``` of the previous item.

```jsx
   <Wrap direction="column" spacing="20px">
            <WrapItem>
            <Button colorScheme="blue" boxShadow="lg">Test 1</Button>
            </WrapItem>

            <WrapItem>
            <Button colorScheme="blue" boxShadow="lg">Test 2</Button>
            </WrapItem>

            <WrapItem>
            <Button colorScheme="blue" boxShadow="lg">Test 3</Button>
            </WrapItem>

            <WrapItem visibility="hidden">
          
            </WrapItem>
    </Wrap>

```

It also blocks boxShadow of each button if you set ```direction="row"``` as a prop in ```Wrap``` component.

### Link to Reproduction

https://codesandbox.io/s/red-glitter-xv2h2c

### Steps to reproduce

1. Go to 'sandbox'
2. Delete the very last item with ```visibility="hidden"```
3. Now ```test 3``` button loses most of its boxShadow

It also blocks boxShadow of each button if you set ```direction="row"``` as a prop in ```Wrap``` component.

### Chakra UI Version

2.4.1

### Browser

106.0.5249.121

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @GKosheev,

You can fix this by passing `overflow: visible` to the `Wrap` component instead.

```jsx
function App() {
  return (
    <Wrap direction="column" spacing="20px" overflow="visible">
      <WrapItem>
        <Button colorScheme="blue" boxShadow="xl">
          Test 1
        </Button>
      </WrapItem>

      <WrapItem>
        <Button colorScheme="blue" boxShadow="xl">
          Test 2
        </Button>
      </WrapItem>

      <WrapItem>
        <Button colorScheme="blue" boxShadow="xl">
          Test 3
        </Button>
      </WrapItem>
    </Wrap>
  );
}
```
