### ISSUE TITLE
RangeSlider does not respond to color mode

### ISSUE THREAD

**Issue by StrangersSoftware** [chakra-ui/chakra-ui#6990]
### Description

When I change color theme to dark, RangeSliderThumb background does not changed to main theme dark color.

Please check the gif in attachments. Link to codesandbox is just to push the issue. 

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-slider-with-slider-mark-ex20y

### Steps to reproduce

1. Change main theme to dark.
2. Check the RangeSliderThumb background.

### Chakra UI Version

2.3.7

### Browser

Chromium 104.0.5112.39

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![sliderBg](https://user-images.githubusercontent.com/15338501/201911045-965e7dbd-82b8-41aa-b616-5b95b508b13c.gif)

**Comment by zRealMikeJordan** [comment]
I'll take a look at this Friday afternoon

**Comment by zRealMikeJordan** [comment]
@StrangersSoftware I created a storybook for this, but wasn't able to reproduce.  One thought: what are you passing to the thumbProps.children ?

I'm just passing the raw value for each of the lower and upper nodes.  Are you passing an element or a string/number value?

<img width="566" alt="image" src="https://user-images.githubusercontent.com/23301201/202810123-4f7d21ed-9832-444d-a497-7499bbc05084.png">

**Comment by StrangersSoftware** [comment]
Here is my code:
```
<RangeSlider value={prices} min={pricesEdges[0]} max={pricesEdges[1]} onChange={setPrices} isDisabled={!usePrice}>
  <RangeSliderTrack>
    <RangeSliderFilledTrack />
  </RangeSliderTrack>
  <RangeSliderThumb bg={buttonBgColor} boxSize={[10, 12]} index={0} shadow="outline" >
    <Flex>{ prices[0] }</Flex>
  </RangeSliderThumb>
  <RangeSliderThumb bg={buttonBgColor} boxSize={[10, 12]} index={1} shadow="outline">
    <Flex>{ prices[1] }</Flex>
  </RangeSliderThumb>
</RangeSlider>
```
As you can see I use forced BG color here. Without this it starts to behave as shown on my gif in bug description.

**Comment by zRealMikeJordan** [comment]
@StrangersSoftware  what happens if you remove the  <Flex> wrapper from around the prices?  try that and then remove the forced bg and let me know what happens...

**Comment by StrangersSoftware** [comment]
@zRealMikeJordan  Thanks for trying to help! )) The same issue I face with code below. Maybe I will try to create this on CodeSandBox and then it will help you more.
```
<RangeSlider value={prices} min={pricesEdges[0]} max={pricesEdges[1]} onChange={setPrices} isDisabled={!usePrice}>
  <RangeSliderTrack>
    <RangeSliderFilledTrack />
  </RangeSliderTrack>
  <RangeSliderThumb boxSize={[10, 12]} index={0} shadow="outline" >
    { prices[0] }
  </RangeSliderThumb>
  <RangeSliderThumb bg={buttonBgColor} boxSize={[10, 12]} index={1} shadow="outline">
    <Flex>{ prices[1] }</Flex>
  </RangeSliderThumb>
</RangeSlider>
```
![new](https://user-images.githubusercontent.com/15338501/203121373-3f129f85-0046-4323-919c-342e573cb731.gif)

**Comment by StrangersSoftware** [comment]
@zRealMikeJordan Here is the link and you can see the same issue on my example here too:

https://codesandbox.io/s/compassionate-ully-o6tywt

**Comment by segunadebayo** [comment]
Hi @StrangersSoftware,

This is actually by design to provide better contrast in dark mode. It's really hard to create a one size fits all UI solution for these components.

Please consider customizing the component as needed.

```jsx
<RanderSliderThumb _dark={{ bg: "gray.700" }} />
```
