### ISSUE TITLE
Using noOfLines with dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by JClackett** [chakra-ui/chakra-ui#6992]
### Description

I have an api that returns a CMS style text paragraph that embeds many tags etc.

Is it possible to use noOfLines with this somehow? when I try it blows up looks super strange

<img width="566" alt="Screenshot 2022-11-15 at 15 20 09" src="https://user-images.githubusercontent.com/12549124/201942584-d2b54202-2e39-4c43-b220-5ce578db581f.png">

### Problem Statement/Justification

Would be nice to be able to add this truncated feature on CMS paragraphs.

### Proposed Solution or API

Not sure here tbh

### Alternatives

Custom built JS solution

**Comment by anubra266** [comment]
@JClackett This is quite vague. Would be nice if you could add some more information for us to better understand the issue

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to reproduce the problem.

**Comment by JClackett** [comment]
Sorry! was hard to explain...

Basically I have some rich text data from an api e.g:

```ts
const description = `<p>a load of text..</p><br /><p>some more text</p>`
```

I then want to render this using:

```tsx
<Box dangerouslySetInnerHtml={{__html: description }}/> 
```
This is all good and works fine!

However the feature i'm requesting/question im asking is, if I want to be able to "cut" this text off using "noOfLines={3}", how would I do this?

**Comment by anubra266** [comment]
@JClackett 
<img width="1112" alt="CleanShot 2022-11-19 at 09 16 03@2x" src="https://user-images.githubusercontent.com/30869823/202841669-4e9bfda1-62bf-437c-bd01-47b71e6a3852.png">

**Comment by JClackett** [comment]
Yeah but yours doesn't contain any <p> tags which rich editor inputs usually give

**Comment by anubra266** [comment]
> Yeah but yours doesn't contain any
> 
> tags which rich editor inputs usually give

@JClackett what tags do you mean? I added a bold tag.

**Comment by JClackett** [comment]
It's a WYSIWYG input so can be any number of tags: "p, br, ul" etc.

My assumption is that this won't work with noOfLines, but just wanted to check if there was a possible solution?

So as an example:

```html
<p>Veniam ad <strong>voluptate</strong> esse sint excepteur excepteur. Est est et anim culpa 
eiusmod esse. Laborum exercitation aute elit <u>voluptate</u> elit minim enim sint commodo 
non id commodo sit veniam ex. Fugiat labore laboris sunt ut adipisiciong.</p>
<p><br></p>
<p>Labore dolore tempor <strong>anim</strong>. Anim sunt proident velit anim anim. 
Consectetur mollit quis incididunt duis laborum do non mollit nostrud labore cupidatat. Quis
cillum eu sint eiusmod. Magna nulla dolor eiusmod fugiat ipsum culpa. Officia dolore dolore 
fugiat dolor velit cupidatat aliqua aute. Do irure aliqua sunt sunt reprehenderit enim est 
irure ea.</p>
```

trying to achieve something like this...

https://user-images.githubusercontent.com/12549124/203057069-4bce32da-e5cd-4a1b-9e69-724496fc27bd.mov


At the moment having to manually .slice the value that is entered into the dangerouslySetInnerHtml, but its completely random and can cut off the text in the middle of a "b" tag and look pretty strange

**Comment by JClackett** [comment]
It's a WYSIWYG input so can be any number of tags: "p, br, ul" etc.

My assumption is that this won't work with noOfLines, but just wanted to check if there was a possible solution?

So as an example:

```html
<p>Veniam ad <strong>voluptate</strong> esse sint excepteur excepteur. Est est et anim culpa 
eiusmod esse. Laborum exercitation aute elit <u>voluptate</u> elit minim enim sint commodo 
non id commodo sit veniam ex. Fugiat labore laboris sunt ut adipisiciong.</p>
<p><br></p>
<p>Labore dolore tempor <strong>anim</strong>. Anim sunt proident velit anim anim. 
Consectetur mollit quis incididunt duis laborum do non mollit nostrud labore cupidatat. Quis
cillum eu sint eiusmod. Magna nulla dolor eiusmod fugiat ipsum culpa. Officia dolore dolore 
fugiat dolor velit cupidatat aliqua aute. Do irure aliqua sunt sunt reprehenderit enim est 
irure ea.</p>
```

trying to achieve something like this...

https://user-images.githubusercontent.com/12549124/203057069-4bce32da-e5cd-4a1b-9e69-724496fc27bd.mov


At the moment having to manually .slice the value that is entered into the dangerouslySetInnerHtml, but its completely random and can cut off the text in the middle of a "b" tag and look pretty strange
