### ISSUE TITLE
kebab-case for css properties in objects is not supported. Did you mean var(-tabsBorderColor)?

### ISSUE THREAD

**Issue by violabg** [chakra-ui/chakra-ui#6993]
### Description

After updating to version 2.4.1, I'm getting this warning in the console.log, when using tabs component with  variant="enclosed"

kebab-case for css properties in objects is not supported. Did you mean var(-tabsBorderColor)?

### Link to Reproduction

https://codesandbox.io/s/goofy-hooks-s0el7u?file=/pages/index.tsx

### Steps to reproduce

run the codesandbox and check the console

### Chakra UI Version

2.4.1

### Browser

all

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
