### ISSUE TITLE
Theming for Grid

### ISSUE THREAD

**Issue by saltnpixels** [chakra-ui/chakra-ui#6994]
### Description

I cannot seem to add base styles for the Grid component in the theme object. We are trying to make a 12 column grid as the default. Especially cause some devs don't know how to use grid-template-columns. Would be nice to set it as a default base style. 

How can we add defaults for the grid component with the ability to override those default props?

### Link to Reproduction

none

### Steps to reproduce

Try to override the theme component Grid.

### Chakra UI Version

latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I'd recommend making a specialized Grid component for your team. We also made the SimpleGrid component for this same reason. 

Currently, we don't allow using the theme object to provide default props for components. We only use it for theming-related properties.
