### ISSUE TITLE
[Tooltip] isOpen, defaultIsOpen props not working

### ISSUE THREAD

**Issue by jdmann** [chakra-ui/chakra-ui#700]
**Describe the bug**
when adding isOpen or defaultIsOpen props to Tooltip, Tooltip does not open

**Expected Behavior**
Tooltip should open when page loads, and remain open (if isOpen is used)

**To Reproduce**
 <Tooltip aria-label="test" label="test" defaultIsOpen={true}>test</Tooltip>

**Suggested solution(s)**
n/a

**Desktop (please complete the following information):**
 OS X 10.15.3
Chrome Version 81.0.4044.138 

**Additional context**
n/a

**Comment by tioluwani94** [comment]
Hi @jdmann, I'm sorry but we can't reproduce this issue. To help us, kindly create a repository or Codesandbox that reproduces this problem so we can fix it. I tried reproducing the issue here https://codesandbox.io/s/exciting-benz-b55u3?file=/src/index.js

**Comment by tafelito** [comment]
I'm seeing the same issue with the AccordionItem. Setting defaultIsOpen to true does not seem to be working when using inside the Accordion parent component. If the Accordion is not used, then it does work. Should I create a separate issue?

**Comment by with-heart** [comment]
I've verified that both `isOpen` and `defaultIsOpen` props work on `Tooltip` in 1.0: https://codesandbox.io/s/sad-hertz-j5yo5?file=/src/App.js

**Comment by tafelito** [comment]
@with-heart what about in AccordionItem? Do you think this is something that could be fixed in the current release? we can't really afford to jump to v1 just yet 😬
