### ISSUE TITLE
Tooltip doesn't close on Esc inside modal

### ISSUE THREAD

**Issue by connordear** [chakra-ui/chakra-ui#7004]
### Description

When a `Tooltip` is used inside of a `Modal` component, the tooltip cannot be closed by pressing the Escape key anymore.

### Link to Reproduction

https://codesandbox.io/s/snowy-cookies-ti19j6?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce

1) Tab to the "Tab to me" button on the first page
2) Observe the tooltip is displayed and can be closed by pressing escape.
3) open the modal, tab to the "Tab to me" button in the modal and observe it cannot be closed by pressing escape

### Chakra UI Version

2.4.1

### Browser

Google Chrome 107

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zRealMikeJordan** [comment]
I'll take a look at this Friday afternoon and try to get it fixed.

**Comment by zRealMikeJordan** [comment]
@connordear @segunadebayo  can you take a look at this PR and let me know what you think?  I'd like to write a test for this too, but it would require testing interaction between at least two components.  What's the best way to do some e2e testing in this project?

https://github.com/chakra-ui/chakra-ui/pull/7013

**Comment by connordear** [comment]
thanks for getting to this so quickly! I wonder why the `e.stopPropagation()` was there in the first place? And is there a `default` behaviour for pressing escape that the `e.preventDefault()` stops?
