### ISSUE TITLE
Multipart component theming doesn't work for Popover arrow

### ISSUE THREAD

**Issue by jeliroco** [chakra-ui/chakra-ui#7005]
### Description

Bumping a previous bug report that was erroneously marked Closed without being addressed.

[Link to @noobinthisgame's original report](https://github.com/chakra-ui/chakra-ui/issues/5821)

### Link to Reproduction

https://codesandbox.io/s/cool-newton-xw6kie?file=/src/App.js

### Steps to reproduce

1. Go to Codesandbox
2. See the theme with the arrow part.
3. It has no effect

### Chakra UI Version

2.4.1

### Browser

Google Chrome 93, Mozilla Firefox 106.0.5 

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Also maybe worth noting that the Popover Theming page is not populated:

https://chakra-ui.com/docs/components/popover/theming

**Comment by anubra266** [comment]
@jeliroco we'll be allowing overriding the background and shadow of the arrow using css variables. when this is released, this is what you can do in your custom theme.

```js
    baseStyle: {
      content: {
        ...
      },
      arrow: {
        "--popper-arrow-bg" : "blue.500",
        "--popper-arrow-shadow" : "lg",
      }
    }
```
