### ISSUE TITLE
Slide component should allow style override for position

### ISSUE THREAD

**Issue by timechainb** [chakra-ui/chakra-ui#7016]
### Description

The `Slide` transition component would be great for my needs except that `position: fixed` is applied in the component regardless of my theme overrides. I want the option to apply `absolute` position so Slide can be contained inside another element in my project instead of relative to the entire project body as it currently is with `fixed` position.

### Problem Statement/Justification

Position fixed is being applied to Slide regardless of theme overrides.

### Proposed Solution or API

Add an optional position prop to Slide component that only accepts `fixed` or `absolute` values. Can still default to `fixed`.

**Comment by segunadebayo** [comment]
Hi @timechainb,

You can fix this by overriding the position attribute with the `style` prop

```jsx
<Slide style={{ position: "absolute" }} />
```
