### ISSUE TITLE
Chakra-UI toggleColorMode(); doesn't work in storybook environment

### ISSUE THREAD

**Issue by Volchinskiy** [chakra-ui/chakra-ui#7017]
### Description

Hello everyone! 
I make component that toggle color mode in three way 
  system - set color mode that configured on your machine(dinamik)
  light     - set light color mode
  dark     - set dark color mode

And he perfectly works in React environment but when i try to toggle color mode in storybook environment i get this mistake. (photo)

This is a function that call when i change color mode using Menu component
 
const handleChange = (changedColorMode: string) => {
    if (changedColorMode === userColorMode) return;
    setLocalColorMode(changedColorMode);
    localStorage.setItem("user_color_mode", changedColorMode);
    if (changedColorMode === "system") {
        const osColorMode = getOsColorMode();
        if (osColorMode !== chakraColorMode) toggleColorMode();
        return;
    }
    if (changedColorMode !== chakraColorMode) toggleColorMode();
};

It just swear on chakra toggleColorMode() and I don't know how to fix it.
Also I try to add this settings to main.js storybook how it write here https://chakra-ui.com/getting-started/with-storybook#troubleshooting-storybook but it doesn't help.
![image](https://user-images.githubusercontent.com/85849172/202913499-69c76d09-0f95-4c46-8ab9-865550f067e7.png)

### Link to Reproduction

https://github.com/Volchinskiy/chakra_ui_bug_report

### Steps to reproduce

1. Clone repo
2. In root folder run "yarn install" or "npm i"
3. Run "yarn start" or "npm start"
4. Split terminal.
5. Run "yarn storybook" or "npm storybook"
6. In react enviroment you can see component that can change color mode and it works fine. Try to change color mode.
7. In storybook enviroment the same component but when you try to change color mode you will get a error.

### Chakra UI Version

2.4.1

### Browser

Chrome 106.0.5249.119

### Operating System

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by Matheus8174** [comment]
I hit a similar issue trying to change the theme then i follow [this](https://ashwin.hashnode.dev/chakra-ui-and-storybook) tutorial and it work for me.

I hope it helps you.

**Comment by Volchinskiy** [comment]
[Matheus8174](https://github.com/Matheus8174) thank you very much, you really helped me

**Comment by segunadebayo** [comment]
This should now be fixed with the recent PR I opened to improve the Storybook Addon
