### ISSUE TITLE
Allow to lazy load the content of a modal

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#7018]
### Description

I would like to load the content of a modal only if the modal is open.

### Problem Statement/Justification

I would like to load the content of a modal only if the modal is open.

### Proposed Solution or API

Something similar to the `isLazy` and `lazyBehavior` props of Popover component.

**Comment by aboveyunhai** [comment]
if you urgently need a solution to solve performance issue caused by modal component.
then you can create you own lazy component before the feature exists.
next.js: https://nextjs.org/docs/advanced-features/dynamic-import
or react: https://reactjs.org/docs/code-splitting.html#reactlazy

**Comment by segunadebayo** [comment]
I can't think of an easy way to add this at the moment.

The modal component isn't mounted by default compared to the popover component. To lazy load the content, we'll need a way to keep the modal rendered in the DOM but hidden. However, the other behavior of the modal dialog (inert, focus trap) might get affected. It's doable but adds unneeded complexity to the codebase.

Please use the framework alternatives to handle this behavior.

Thanks for understanding.

**Comment by lcswillems** [comment]
@segunadebayo Why do you say it is unneeded? In my case, I would need such a behavior.

And also, what are the framework alternatives?

**Comment by lcswillems** [comment]
@segunadebayo "The modal component isn't mounted by default": it seems it is mounted by default. This is the reason I am opening the issue

**Comment by zzh8829** [comment]
@segunadebayo  the content of modals are definitely mounted by default, we are also having this problem in our app

**Comment by aboveyunhai** [comment]
@zzh8829  @lcswillems 
I just create a codesand box for you guys to see the subtle differences how you structure the code could make the content lazy or not, there is a workaround. 

it could be a bug @segunadebayo  

https://codesandbox.io/s/sandpack-project-forked-zncoev?file=/App.tsx

**Comment by lcswillems** [comment]
I have created a new issue here: https://github.com/chakra-ui/chakra-ui/issues/7067

**Comment by uvera** [comment]
@aboveyunhai @lcswillems here's an example how I would approach lazy loading

https://codesandbox.io/s/sandpack-project-forked-q2h08u?file=/App.tsx


Your issue with console.log executing is that it's immediately evaluated. If I read correctly, JSX parser immediately evaluates expressions in curly braces. There is no easy way around this.

```javascript
const LazyModalContent = ({
  children
}: {
  children: () => React.ReactNode;
}) => {
  return <ModalContent>{children()}</ModalContent>;
};
```

```javascript
const ModalLazySuccess = () => {
  const { isOpen, onOpen, onClose } = useDisclosure();
  return (
    <>
      <Button onClick={onOpen}>Modal Lazy Success</Button>
      <Modal isOpen={isOpen} onClose={onClose}>
        <ModalOverlay />
        <LazyModalContent>
          {() => (
            <>
              <ModalHeader>Modal Title</ModalHeader>
              <ModalCloseButton />
              <ModalBody>
                <Box>
                  {console.log("modal-lazy-success")}
                  <Box>content</Box>
                </Box>
              </ModalBody>
              <ModalFooter>
                <Button colorScheme="blue" mr={3} onClick={onClose}>
                  Close
                </Button>
                <Button variant="ghost">Secondary Action</Button>
              </ModalFooter>
            </>
          )}
        </LazyModalContent>
      </Modal>
    </>
  );
};
```

**Comment by etarley** [comment]
Just put the modal inside a lazy loaded Popover, that worked for me.

**Comment by VHQDevFS** [comment]
> Just put the modal inside a lazy loaded Popover, that worked for me.

can you give me an example code please.
