### ISSUE TITLE
Popover isLazy is not working as expected

### ISSUE THREAD

**Issue by chrysb** [chakra-ui/chakra-ui#7020]
### Description

When I set the `isLazy` property on the `Popover` component, I expect the component not to execute Apollo GraphQL calls until it is opened, but I observe that it does.

My use case is that I want to show a popover that fetches remote information when it opens, but it fetches it even before. I can see 20+ GraphQL calls in my network monitor.

```
const WalletPeek = ({ user, address, children }: Props) => {
  return (
    <Popover
      trigger='hover'
      openDelay={700}
      placement='bottom-start'
      isLazy
    >
      <PopoverTrigger>
          {children}
      </PopoverTrigger>

      <WalletPeekBody user={user} address={address} />
    </Popover>
  )
}
```

In this case, `WalletPeekBody` has a GraphQL call within it, and it's getting triggered on page load.

WalletPeekBody:

```
const WalletPeekBody = ({ address }: Props) => {
  const { data } = useWalletSummaryQuery({
    variables: {
      address,
    },
  })
  
  return (
    <Portal>
      <PopoverContent>
         ...
      </PopoverContent>
   </Portal>
  )
}
```

### Chakra UI Version

2.4.1

### Browser

Chrome Version 107.0.5304.87 (Official Build) (x86_64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Right now my workaround is to not render the body unless `isOpen` is true, but then we lose the nice animation on hover.

e.g.

```
      {({ isOpen }) => (
        <>
          <PopoverTrigger>
             {children}
          </PopoverTrigger>

          {isOpen && <WalletPeekBody address={address} />}
        </>
      )}
```

**Comment by segunadebayo** [comment]
Hi @chrysb,

This issue doesn't contain a reproduction, and it's hard for us to help. Technically speaking, this should work though but we need a repro to verify.

Please create a CodeSandbox or StackBlitz reproduction, and we'll re-open
