### ISSUE TITLE
@chakra-ui/react-types@2.0.4 is built incorrectly

### ISSUE THREAD

**Issue by rolule** [chakra-ui/chakra-ui#7025]
### Description

After installing @chakra-ui/react version 2.4.1, [@typescript-eslint/no-unsafe-assignment](https://typescript-eslint.io/rules/no-unsafe-assignment) warned me that the return type of `useRadio` and `useRadioGroup` is `any`. I looked at the useRadio type, which uses the `PropGetter` type from `@chakra-ui/react-types`. Then I looked at `@chakra-ui/react-types@2.0.4`, and found out the following:
- the `package.json` file declares the `"types"`, `"main"`, `"module"` (and all corresponding `"export"` fields) with a path under `dist/`
- the actual served package does not contain a `dist` folder. Instead, it only contains a `src` folder

This leads me to believe, that the package `@chakra-ui/react-types@2.0.4` is served incorrectly from npm after the changes to the package.json in version `2.0.4`. Installing version `2.0.3` resolves the issue. 

### Link to Reproduction

https://codesandbox.io/s/damp-framework-jxszc4?file=/src/index.tsx

### Steps to reproduce

1. Install `@chakra-ui/react@2.4.1`
2. Create a component and import `useRadio` from `@chakra-ui/react` and use it: `const { getCheckboxProps } = useRadio()`
3. Use the destructured function: `const checkbox = getCheckboxProps()`
4. Check the type of `checkbox`: it is `any` but it should be `PropGetter<Record<string, unknown>, _chakra_ui_react_types.DOMAttributes<_chakra_ui_react_types.DOMElement>>`

### Chakra UI Version

2.4.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. Luckily it has already been fixed in one of the recent PRs. We'll push an update shortly.
