### ISSUE TITLE
The ellipsis does not work on Badge component

### ISSUE THREAD

**Issue by manakuro** [chakra-ui/chakra-ui#7027]
### Description

The ellipsis does not show up on the Badge component using `noOfLines` and `maxW`. It used to work on `"@chakra-ui/react": "^1.7.3"`.

It's probably because the inner `span` has `display: flex` style. It should work with `display: inline-box`.

### Link to Reproduction

https://codesandbox.io/s/pensive-spence-3pd41y?file=/src/index.js

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.4.1

### Browser

Google Chrome 107.0.5304.110

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by manakuro** [comment]
Can I try to fix it?

**Comment by anubra266** [comment]
Yeah you can try @manakuro

**Comment by segunadebayo** [comment]
Hi @manakuro,

We recently added the `isTruncated` style property back to v2. Once released, you can use this to achieve the ellipsis.

Thanks
