### ISSUE TITLE
Avatar component theming doesn't work as expected

### ISSUE THREAD

**Issue by Daidalos117** [chakra-ui/chakra-ui#7033]
### Description

Hi guys,

when I use Avatar component, I can directly influence the border radius with a borderRadius prop. It will change the radius for container but the image too. When I try to override default props with a theme, it just doesn't work. Please see the linked reproduction.
When I try to influence the border with a css, I can change it for a container but the output is not what it is desired. How to change css for the image itself? The image is not even mentioned as an anatomy part of avatar in documentation.

Maybe I am missing something? Not really sure, but for me it seems that the working of the component is really unclear.
Thanks for any input!

### Link to Reproduction

https://stackblitz.com/edit/react-ts-qeyeyd?file=App.tsx

### Steps to reproduce

1. use avatar
2. add custom theme
3. try to override defaultProps such as borderRadius

### Chakra UI Version

2.4.1

### Browser

Chrome

### Operating System

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
<img width="702" alt="CleanShot 2022-11-25 at 10 38 40@2x" src="https://user-images.githubusercontent.com/30869823/203948855-eb903818-8d99-4e8c-bc80-1178a650eee9.png">

**Comment by anubra266** [comment]
Meant no offense @Daidalos117. Saw that you had normal styleProps in your repro sandbox Avatar, and thought that might be what you were looking for. 
Re-reading your issue clearly now, and it seems you're concerned about an anatomy for the image. I'll reopen for now, and we'll get back regarding this.

**Comment by anubra266** [comment]
@Daidalos117 There are no plans to add a new anatomy for the `image` as at this time. The theme is all just css too. So you can use CSS selectors to target the image from the container.
<img width="1098" alt="CleanShot 2022-11-25 at 17 30 20@2x" src="https://user-images.githubusercontent.com/30869823/204026081-205a55e4-df0c-4d58-b810-c6f5e72bfb5f.png">
