### ISSUE TITLE
Problems applying custom themes

### ISSUE THREAD

**Issue by Woo-Dong93** [chakra-ui/chakra-ui#7037]
### Description

hello. I am using chakra-ui for a new project
A problem occurred during this process.
We are injecting the theme using `ChakraProvider`.
Themes injected from outside are well merged with the default themes.
However, when injected into the `ChakraProvider`, the injected theme is not applied and the theme provided by ChakraUI is applied.
The cause is unknown.

Custom theme are normally injected into the browser, but are not applied due to the priority of the theme provided by ChakraUI.

```
export default function provider({ children, theme }) {
  const customTheme =  extendTheme(defaultTheme, theme));

  return (
    <ChakraProvider
      theme={customTheme}
    >
      {children}
    </ChakraProvider>
  );
}
```

### Link to Reproduction

null

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.0.2

### Browser

google chorme 107

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by CoderK** [comment]
This issue is likely to be related to `ToastContainer`. The exact cause is unknown, but if you make `ToastContainer` with `createStandaloneToast` and add it, it can be 100% reproduced.

The code below is that I reproduced on create-react-app.

```
import React from 'react';
import logo from './logo.svg';
import './App.css';
import {Button, ChakraProvider, extendTheme} from "@chakra-ui/react";
import { createStandaloneToast } from '@chakra-ui/toast'

const { toast, ToastContainer } = createStandaloneToast();

const customTheme = extendTheme(
    {
      fontSizes: {
        xs: '0.75rem',
        sm: '0.875rem',
        md: '1rem',
        lg: '12rem',
        xl: '100px',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '3.75rem',
        '7xl': '4.5rem',
        '8xl': '6rem',
        '9xl': '8rem',
      },
    }
);

function App() {
  return (
      <>
          <ChakraProvider theme={customTheme}>
              <Button fontSize='lg'>blahblah</Button>
              <div className="App">
                  <header className="App-header">
                      <img src={logo} className="App-logo" alt="logo" />
                      <p>
                          Edit <code>src/App.tsx</code> and save to reload.
                      </p>
                      <a
                          className="App-link"
                          href="https://reactjs.org"
                          target="_blank"
                          rel="noopener noreferrer"
                      >
                          Learn React
                      </a>
                  </header>
              </div>
              <ToastContainer />
          </ChakraProvider>
      </>
  );
}

export default App;
```

**Comment by segunadebayo** [comment]
Hi @Woo-Dong93,

This issue doesn't contain a reproduction, and it's hard for us to help.

Please create a CodeSandbox or StackBlitz reproduction, and we'll re-open
