### ISSUE TITLE
Can't use <Link /> with Gatsby's <Link />

### ISSUE THREAD

**Issue by afonsojramos** [chakra-ui/chakra-ui#7038]
### Description

Similar to this [issue](https://github.com/chakra-ui/chakra-ui/issues/194), I am unable to have Typescript not show an error here: 

<img width="158" alt="image" src="https://user-images.githubusercontent.com/19473034/204006176-8d5fd456-3a47-40f1-9e99-af94af7c3569.png">

This is TypeScript's output:
```
Type 'typeof GatsbyLink' is not assignable to type 'As<any> | undefined'.
  Type 'typeof GatsbyLink' is not assignable to type 'ComponentClass<any, any>'.
    Type 'GatsbyLink<unknown>' is missing the following properties from type 'Component<any, any, any>': context, setState, forceUpdate, render, and 3 more.ts(2322)
index.d.ts(52, 5): The expected type comes from property 'as' which is declared here on type 'IntrinsicAttributes & OmitCommonProps<DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>, keyof LinkProps> & LinkProps & OmitCommonProps<...> & { ...; }'
```

The documentation is being followed as per this [entry](https://chakra-ui.com/docs/components/link/usage#usage-with-routing-library), so I am not sure what is happening.

### Chakra UI Version

2.4.1

### Operating System

- [x] macOS
- [x] Windows
- [x] Linux

**Comment by segunadebayo** [comment]
Hi @afonsojramos,

This issue doesn't contain a reproduction, and it's hard for us to help.

Please create a CodeSandbox or StackBlitz reproduction, and we'll re-open
