### ISSUE TITLE
Move a tab as far left into view on focus with horizontal scrolling

### ISSUE THREAD

**Issue by JulianoBazzi** [chakra-ui/chakra-ui#7039]
### Description

Problem to move a tab as far left into view on focus with horizontal scrolling.

Related topic:
https://stackoverflow.com/questions/71849336/how-do-you-move-a-tab-as-far-left-into-view-on-focus-with-horizontal-scrolling

### Link to Reproduction

https://codesandbox.io/s/6so1j6

### Steps to reproduce

1. Emulate a low resolution cell phone in DevTools (suggestion: iPhone SE).
2. According to the attached image, if I click on "Tab F", it is selected, but the tab is not focused
![Tab Selected Not Focus](https://user-images.githubusercontent.com/16826201/204063680-8fe24dca-486f-4301-9a8e-4247088b42df.jpg)

### Chakra UI Version

2.3.4

### Browser

Google Chrome 107.0.5304.122

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by renatorl** [comment]
I have the same problem, does anyone have a solution for this?

**Comment by segunadebayo** [comment]
Hi @JulianoBazzi,

Here's a small utility to help you scroll the selected tab into view.

```ts
function useScrollTabIntoView(index: number) {
  const tablistRef = useRef<HTMLDivElement>();

  useEffect(() => {
    const selectedTab = tablistRef.current.querySelector(
      "[role=tab][aria-selected]"
    );
    selectedTab?.scrollIntoView();
  }, [index]);

  return tablistRef;
}
```

and use it like so:

```js
const App = () => {
  const [tabIndex, setTabIndex] = useState(0);

  const handleChange = (nextTabIndex: number) => {
    console.log("inside", nextTabIndex, tabIndex);
    if (nextTabIndex !== tabIndex) {
      setTabIndex(nextTabIndex);
    }
  };

  const tablistRef = useScrollTabIntoView(tabIndex);

  return (
    <Tabs index={tabIndex} onChange={handleChange}>
      <TabList
        ref={tablistRef}
        overflowX="scroll"
        sx={{
          scrollbarWidth: "none",
          "::-webkit-scrollbar": {
            display: "none"
          }
        }}
      >
        <Tab flexShrink={0}>Tab A</Tab>
        <Tab flexShrink={0}>Tab B</Tab>
        <Tab flexShrink={0}>Tab C</Tab>
      </TabList>
      <TabPanels p="2rem">
        <TabPanel>you are on the tab A</TabPanel>
        <TabPanel>you are on the tab B</TabPanel>
        <TabPanel>you are on the tab C</TabPanel>
      </TabPanels>
    </Tabs>
  );
};

```
