### ISSUE TITLE
Update `probot-stale` config to exempt more labels

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#704]
I'd like to update `probot-stale`'s configuration to at least exempt `Type: Feature 🚀`. If it's important enough to be flagged as a potential feature, we should manage closing ourselves if we feel that it's no longer useful.

Does this sound like a good? If so, should we include more of our labels? All of them?

**Comment by segunadebayo** [comment]
This sounds like a good idea, Mark. Please go for it.

Feel free to exempt labels that you think are worth exempting.
