### ISSUE TITLE
backdropFilter "auto" causes significant fps drop in ModalOverlay

### ISSUE THREAD

**Issue by GKosheev** [chakra-ui/chakra-ui#7048]
### Description

I use ```ModalOverlay``` with ```backdropFilter="auto" backdropBlur="2px"``` and experience a significant fps drop. The wider the screen, the fewer fps I have. As far as I can understand, when this prop is set to ```auto```, Chakra UI handles this property and defines the color based on backdropBlur and backdropSaturate.

### Link to Reproduction

https://codesandbox.io/s/frosty-snowflake-ekq3oh?file=/src/index.js

### Steps to reproduce

1. Go to 'Shared Sandbox'
2. Click on 'auto & none buttons (make the screen wider to experience fps drop)'

### Chakra UI Version

2.3.5

### Browser

Google Chrome 107.0.5304.107

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I wonder if that's expected behavior or if is it an issue with the library.

**Comment by segunadebayo** [comment]
The native CSS filter and backdrop filter properties have a significant impact on fps. I'd recommend using them sparingly.
