### ISSUE TITLE
[Dialog] preserveFocusLock={false} not working

### ISSUE THREAD

**Issue by rfash** [chakra-ui/chakra-ui#705]
**Issue**

after reading https://github.com/chakra-ui/chakra-ui/pull/568, I ran 
yarn add https://pkg.csb.dev/chakra-ui/chakra-ui/commit/75529578/@chakra-ui/core

I proceeded to add preserveFocusLock={false} to my Dialog modal, but I am still unable to interact with links outside the Dialog box.

**Expected Behavior**
I would like to be able to click on links outside the dialog box.

**To Reproduce**
yarn add https://pkg.csb.dev/chakra-ui/chakra-ui/commit/75529578/@chakra-ui/core
 add preserveFocusLock={false} to my Dialog
try clicking or interacting with any links outside of the Dialog component.

**Comment by with-heart** [comment]
Hi @rfash, that PR was not merged so `preserveFocusLock` is not a prop available for use. 

This functionality exists in 1.0 (currently in pre-release) as the `trapFocus` prop.
