### ISSUE TITLE
Modal Custom Height

### ISSUE THREAD

**Issue by renchris** [chakra-ui/chakra-ui#7052]
### Description

I am wanting to create a mobile navigation menu that pops up when the button in the fixed navigation menu at the top of the screen is clicked.

It should take the full view width and height UNDER the navigation bar

Currently there are a number of fixed sizes for the size prop. The "full" size covers the entire width and height of the screen, including and covering the navigation menu.

How would I modify it so that the modal height is calc(100vh - 64px) instead?

I was trying to create just a box component instead that took that height but it still allows horizontal scrolling of the main content underneath which is what I don't want

### Link to Reproduction

https://chakra-ui.com/docs/components/modal/usage

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.4.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by veloware** [comment]
Modals use portal, so you should be able to change the portal container ref using the Modal's `portalProps` prop.  I haven't use it before, but it looks like you should be able to do something like - 

```
const modalContainerRef = React.useRef()
...
<Box ref={modalContainerRef}> ** The container that sits below your nav bar ** </Box>
...
<Modal portalProps={{ containerRef: modalContainerRef}}>...</Modal>
```

**Comment by segunadebayo** [comment]
Hi @renchris,

You can change the height of the dialog by padding the `maxHeight` property to the `DialogContent`

```jsx
      <Modal>
        <ModalOverlay />
        <ModalContent maxHeight="<customHeight>">
          <ModalHeader>Modal Title</ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            <Lorem count={2} />
          </ModalBody>

          <ModalFooter>
            <Button colorScheme='blue' mr={3} onClick={onClose}>
              Close
            </Button>
            <Button variant='ghost'>Secondary Action</Button>
          </ModalFooter>
        </ModalContent>
      </Modal>
```
