### ISSUE TITLE
`FunctionComp.defaultProps` is going to be deprecated in React 18.3.0

### ISSUE THREAD

**Issue by isBatak** [chakra-ui/chakra-ui#7057]
### Description

This issue is based on this [Discord](https://discord.com/channels/660863154703695893/660863154703695896/1045867951779229706) report

The error that happens when using Portal with Next.js 13.0.5
```
Warning: Portal: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
```

The root of the problem: 
https://github.com/chakra-ui/chakra-ui/blob/4d5501b82b6fe215f1a7d205250325c0a2221337/packages/components/portal/src/portal.tsx#L178

Links to React PR and ESLint change:
https://github.com/facebook/react/pull/25699
https://github.com/jsx-eslint/eslint-plugin-react/issues/2396

Other components might also be affected.

### Problem Statement/Justification

This will make Chakra UI more aligned with React 18.3.0

### Proposed Solution or API

Change:
```
Portal.defaultProps = {
  appendToParentPortal: true,
}
```
Into:
```
export function Portal(props: PortalProps) {
  const { containerRef, ...rest } = { appendToParentPortal: true, ...props };
  return containerRef ? (
    <ContainerPortal containerRef={containerRef} {...rest} />
  ) : (
    <DefaultPortal {...rest} />
  )
}
```
The goal isn't to remove `defaultProps`, but to change how they're defined on function components.

**Comment by AlexKvazos** [comment]
[PR](https://github.com/chakra-ui/chakra-ui/pull/7059) submmited. This is my first contribution, please let know if I missed anything.

**Comment by cereallarceny** [comment]
I've also submitted a PR which sufficiently solves the problem for all components: https://github.com/chakra-ui/chakra-ui/pull/7068

The PR submitted by @AlexKvazos only solved the problem in one component.
