### ISSUE TITLE
“as” property breaks chakra(motion.div)

### ISSUE THREAD

**Issue by rubenswieringa** [chakra-ui/chakra-ui#7062]
### Description

I followed the [instructions from the docs](https://chakra-ui.com/getting-started/with-framer) for wrapping a Framer Motion component with Chakra:
```js
const MotionBox = chakra(motion.div, {
  shouldForwardProp: (prop) => isValidMotionProp(prop) || shouldForwardProp(prop),
});
```

…and it works, except for when I pass an `as`-property:
```jsx
<MotionBox as="header" />
```
---

I understand that the wrapped component already specifies the actual html-element (eg. “motion.div”) and that Framer Motion doesn’t have a corresponding property, but:

**What I would have expected to happen** (in hindsight):
* Chakra ignores the `as`-property
* Framer Motion still does its thing (eg. works)
* Chakra writes a warning to the console about the `as`-property being ignored

**What actually happened:**
* None of the Framer Motion properties I placed have any effect anymore
* There is no indication that the `as`-property is the culprit (took me a while to figure it out)

Having said that – if possible, it would be absolutely amazing if `<MotionBox as="header"/>` could/would actually work.

---

### Link to Reproduction

https://codesandbox.io/s/sandpack-project-forked-yh9jcf?file=/App.tsx

### Steps to reproduce

1. Create a Chakra-wrapper for a Framer Motion component ([sample code in docs](https://chakra-ui.com/getting-started/with-framer))
2. Add an `as` property

### Chakra UI Version

2.4.2

### Browser

Google Chrome; Firefox

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @rubenswieringa,

This is because you're swapping out the `motion` element with a native `header`, and that breaks the outcome.

If you used `<MotionBox as={motion.header} />`, it should work as expected.

https://codesandbox.io/s/sandpack-project-forked-e43qsl
