### ISSUE TITLE
[MenuButton] MenuButton as {Button} doesn't have Button props - Typescript

### ISSUE THREAD

**Issue by OmarZeidan** [chakra-ui/chakra-ui#707]
**Describe the bug**

For the component `MenuButton` using it `as={Button}` is missing `Button` props.

<img width="1386" alt="Screenshot 2020-05-13 at 17 04 24" src="https://user-images.githubusercontent.com/3344403/81830038-da854e80-953b-11ea-84e8-9e5b58dd22aa.png">

**Expected Behavior**

It should accepts the `as` component props. In this case `Button`.

It wouldn't make sense if we make all the `as` component's props available, but at least `Button` props would be the most common here.

**Suggested solution(s)**

As a workaround, this can be solved by adding the `ButtonProps` to the `MenuButtonProps`
- File: `@chakra-ui/core/dist/Menu/index.d.ts`

- Changes: 
```javascript
// Before
export type MenuButtonProps = PseudoBoxProps & IMenuButton;

// After
export type MenuButtonProps = PseudoBoxProps & ButtonProps & IMenuButton;
```

If there is a current solution I have missed please do let me know.

With <3

**Comment by with-heart** [comment]
Hi @OmarZeidan! We've been hard at work getting ready for our 1.0 release (see #696). 

This release completely revamps our internal system for constructing components and migrates the codebase to TypeScript, and a part of that is making sure that `as` works correctly with other Chakra components and your own typed components. 

Once the release is out, you should find a much greater consistency around our type system.

**Comment by OmarZeidan** [comment]
@with-heart Great news! 

For the first time I fall in love and dig deep with a UI library. Happy to help in anyway possible as much as I could.

Love for all your hard working and looking forward for the `1.0` release.
