### ISSUE TITLE
Blue outline borders around all clickable components ugly

### ISSUE THREAD

**Issue by vonwao** [chakra-ui/chakra-ui#708]
I'm getting blue outline borders around all my clickable components, for example Button, Tab, and AccordionHeader.  I realize this is likely related to default behavior in Chrome, but it's quite ugly. 

This seems to be related to similar issues also reported in other UI libraries:

- https://stackoverflow.com/questions/42423371/how-do-i-remove-the-blue-border-that-appears-when-clicking-on-a-uib-accordion-he
- https://github.com/mui-org/material-ui/issues/11504

**Suggested solution(s)**

:focus {outline:0 !important;}

Should this be added as default for all chakra components? 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by with-heart** [comment]
Hi @vonwao! 

One of the primary goals of Chakra UI is to strictly follow WAI-ARIA standards. Element outlines are an important part of accessibility, and removing them makes it difficult for keyboard users to navigate a site.

The A11y Project has a short article on why you shouldn't remove the outline: [Quick Tip: Never remove CSS](https://a11yproject.com/posts/never-remove-css-outlines/). That article details a few alternatives if you don't like the default outline.

This of course doesn't mean that you can't do as you please with your use of the components, but it would hurt Chakra's commitment to accessibility to disable it by default.

**Comment by with-heart** [comment]
Also Chakra 1.0 will comes with a component theming API that will make it easy to set default outlines for your components through your `theme`. It's not out just yet, but it'll be here soon.

**Comment by vonwao** [comment]
Thanks for this info @with-heart.  I'm still confused, if this behavior is so important how come I've never seen a website with outlines around tabs?  What I mean, to be clear, is this:

![image](https://user-images.githubusercontent.com/377000/82229822-e6389280-98f8-11ea-8d3d-2954226cf4d3.png)

This is so ugly that it's actually unusable.  I've never seen this anywhere else.

Is this always the case with Chakra-ui?  Or does it have to do with my browser settings?

**Comment by eliraz-refael** [comment]
I agree with the author, it's kinda ugly focus, and that's pretty shamefull since this library is the prettiest I've seen in years.
I however discovered that this blue `outline` is actually a box-shadow applied on focus
![image](https://user-images.githubusercontent.com/18550582/83783738-e8d90d00-a698-11ea-897f-602bd94fa45c.png)

**Comment by dusty** [comment]
@vonwao @eliraz-refael 

Have you seen this?  This is working great for me.

https://medium.com/@keeganfamouss/accessibility-on-demand-with-chakra-ui-and-focus-visible-19413b1bc6f9

**Comment by eliraz-refael** [comment]
That looks good, and I think that should be implemented into the library, at least as an option.

**Comment by dfeehrer** [comment]
+1 Totally agree, the `focus-visible` approach is working well for me too, but it would be great if this could be implemented in the library itself somehow, those blue outlines showing up on click take away from how nice the rest of the components look

**Comment by TransmissionsDev** [comment]
+1 for sure. I've never come across a website before that shows focus shadows on click like this.

**Comment by with-heart** [comment]
#2016 has a solution for this in Segun's reply.

**Comment by iamonuwa** [comment]
passing a _focus props with outline="none" solves this issue.

**Comment by winjingjie96** [comment]
> passing a _focus props with outline="none" solves this issue.

this doesn't work on mobile though

**Comment by milinpaul** [comment]
`const theme = extendTheme({
    components: {
        Button: {
            baseStyle: {
                _focus: {
                    boxShadow: 'none'
                }
            }
        }
    }
})`

Using extendTheme utility we can able to remove the outline. Above snippets works for me.

**Comment by monecchi** [comment]
For the switch input, when using `extendTheme` the `_focus` jsx attribute goes like the following:

```javascript
...

components: {
  Switch: {
    baseStyle: {
      track: {
        _focus: {
          boxShadow: 'none'
        }
      }
    }
  }
}

...
```

**Comment by docyx** [comment]
Solution that's working for me:

1. Install `focus-visible` package from npm (`yarn add focus-visible` or `npm i focus-visible`)
2. Add the following to your `extendTheme` config:
```js
extendTheme({
  styles: {
    global: {
      // Remove Chakra's default border focus outline and use :focus-visible instead
      '.js-focus-visible :focus:not([data-focus-visible-added])': {
        outline: 'none',
        boxShadow: 'none'
      }
    }
  }
})
```
3. Add the following snippet to the highest level of your app (e.g. in `index.jsx` if using CRA, or `_app.jsx` if using Next.js):
```js
import 'focus-visible/dist/focus-visible'
```
4. Make sure your `ChakraProvider` has its `theme` set to your app's `extendTheme`, e.g.:
```jsx
import chakraTheme from '@/path/to/theme'

// --snip--
<ChakraProvider theme={chakraTheme}>
// --snip--
```

**Comment by xencodes** [comment]
try this CSS
```css
* {
    -webkit-tap-highlight-color: transparent;
}
```

**Comment by OmarZeidan** [comment]
> `const theme = extendTheme({ components: { Button: { baseStyle: { _focus: { boxShadow: 'none' } } } } })`
> 
> Using extendTheme utility we can able to remove the outline. Above snippets works for me.

This solution is for V1, we are talking about `V0.x` here

**Comment by amarjeet987** [comment]
Try this for the component where you're facing the issue
`_focus={{
  boxShadow: "none",
}}`

**Comment by wouter-deen** [comment]
> `const theme = extendTheme({ components: { Button: { baseStyle: { _focus: { boxShadow: 'none' } } } } })`
> 
> Using extendTheme utility we can able to remove the outline. Above snippets works for me.

For some reason this doesn't seem to work for me. However, @amarjeet987's solution works fine when I apply it directly to the element! Not really practical when you want to apply it to each instance of the element in your project, but it works.

**Comment by hirooutdoor** [comment]
> Try this for the component where you're facing the issue
> `_focus={{ boxShadow: "none", }}`

Yes, this one works for me too. Thanks,  @amarjeet987 :)
Just so you know, you can find the list of style props here; [https://chakra-ui.com/docs/features/style-props](https://chakra-ui.com/docs/features/style-props)
```
<IconButton
  _focus={{boxShadow: "none"}}
  aria-label="DarkMode Switch"
  icon={colorMode === 'light' ? <MoonIcon /> : <SunIcon />}
  onClick={toggleColorMode}
/>
```

**Comment by cloudy-boyuan** [comment]
Try this?

```ts
const customTheme = extendTheme({shadows: { outline: "none" }});
```

**Comment by bubuq3** [comment]
_focus={{boxShadow: "none"}} didnt help.
![image](https://user-images.githubusercontent.com/62507500/147857378-3397a7cb-e14f-4cda-b9af-38b8277c08c6.png)
However, on Languages group I dont have this blue outline...
![image](https://user-images.githubusercontent.com/62507500/147857387-c106f6ab-9239-4e74-afee-e91d5cfffdc4.png)

How to get rid of it?
```js
              <Menu isLazy id="navbar-menu">
                <MenuButton
                  as={IconButton}
                  icon={<HamburgerIcon />}
                  variant="outline"
                  aria-label="Options"
                />

                <MenuList bg={useColorModeValue('white', '#202023')}>
                  <MenuGroup>
                    <NextLink href="/" passHref _focus={{ boxShadow: 'none' }}>
                      <MenuItem as={Link}>{t.aboutMeMobileMenu}</MenuItem>
                    </NextLink>
                    <NextLink
                      href="https://xxxxxxx"
                      passHref
                    >
                      <MenuItem as={Link}>Portfolio</MenuItem>
                    </NextLink>

                    <MenuItem
                      as={Link}
                      href="hxxxxxxxxx"
                      style={{ gap: 4 }}
                    >
                      <IoLogoGithub />
                      Github
                    </MenuItem>
                  </MenuGroup>

                  <MenuGroup title="Languages" align="left">
                    <MenuItem>English</MenuItem>
                    <MenuItem>Polish</MenuItem>
                  </MenuGroup>
                </MenuList>
              </Menu>
```

**Comment by AmritPant** [comment]
> I agree with the author, it's kinda ugly focus, and that's pretty shamefull since this library is the prettiest I've seen in years. I however discovered that this blue `outline` is actually a `box-shadow` applied on focus ![image](https://user-images.githubusercontent.com/18550582/83783738-e8d90d00-a698-11ea-897f-602bd94fa45c.png) I truly hope that it can be disabled globally because it's a deal breaker for me at least. a quick and dirty workaround is to to the following: ![image](https://user-images.githubusercontent.com/18550582/83785695-605b6c00-a69a-11ea-95df-b516f891b7cd.png)

Thanks so much this works for me

**Comment by jaaymes** [comment]
_focus={{
            WebkitTapHighlightColor: 'transparent'
          }}

**Comment by benatkin** [comment]
I think this should be reopened, as :focus-visible has become supported in more browsers. Perhaps a polyfill should be added for Safari. In Chrome the ideal behavior is applied to buttons that don't have a custom focus outline/box-shadow, but with the custom outline/box-shadow in Chakra, you lose it. The reason I think this should be implemented in core is because I think the demos would look a lot better.

<img width="258" alt="Captura de Pantalla 2022-03-11 a la(s) 13 33 00" src="https://user-images.githubusercontent.com/4126/157973413-b0a58ceb-f6b9-4198-9747-093b1b2d5274.png">

**Comment by mwibutsa** [comment]
I am not sure if it's for all of them but I realized some components have the data-focus attribute to which the outline is applied. so I had to disable it like this
`*[data-focus] {
    box-shadow: none !important;
}`

**Comment by benatkin** [comment]
@vonwao I agree. The only thing is that a kludge was needed in order to fix this issue. Not anymore, thanks to the `:focus-visible` selector, except in Safari, and that is added to WebKit which means soon it should be in Safari.

**Comment by ezerobledo91** [comment]
> Try this for the component where you're facing the issue `_focus={{ boxShadow: "none", }}
This solutions works in V2.xxx Excellent!

**Comment by dewaleolaoye** [comment]
if you are using the Drawer component, pass the `autoFocus` prop and set it to false

**Comment by benatkin** [comment]
Safari 15.4 has been out for a few months now. Please reopen this. It can be fixed properly, so that the custom outlines behave just like the default outlines! https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible

It will probably need to be done in a minor or major release to give users an opportunity to read the release notes and not have an unexpected change, but an open issue is proper for that.

**Comment by rushi2784** [comment]
` focusBorderColor='0'`  try this working for me

**Comment by mateomolinari** [comment]
> _focus={{ WebkitTapHighlightColor: 'transparent' }}

thank god, it was driving me crazy. this stopped the light blue background when swapping icons.

**Comment by 0xrasla** [comment]
`_focusVisible={{
    boxShadow: "none",
    outline: "none",
}}`


This prop working better for me

**Comment by vicradon** [comment]
> ```css
> body.using-mouse *:focus {
>   box-shadow: none !important;
> }
> ```

Hi @nilobarp 
Where can I put this Javascript in a Next.js application?

**Comment by galvaolucas** [comment]
The following solution worked for me, in the theme.ts:

```
components: {
        Button: {
            baseStyle: {
                _focus: {
                    boxShadow: 'none !important',
                }
            }
        },
    }
```

**Comment by NxRoot** [comment]
New versions of chakra use `border-color` and `focus-visible`.

Solution to remove the focus from all components

```css
/* Remove Chakra UI Focus*/
:focus, :focus-visible, *[data-focus] {
  box-shadow: none !important;
  outline: none !important;
  border-color: inherit !important;
}
```

**Comment by benatkin** [comment]
> New versions of chakra use `border-color` and `focus-visible`.
> 
> Solution to remove the focus from all components
> 
> ```css
> /* Remove Chakra UI Focus*/
> :focus, :focus-visible, *[data-focus] {
>   box-shadow: none !important;
>   outline: none !important;
>   border-color: inherit !important;
> }
> ```

In that case it seems that the problem is solved, and further advice will likely be about removing accessibility. I'll unsubscribe and it might be a good idea to lock this issue.

**Comment by NoamRivlin** [comment]
this worked for me when handling textArea:

   
```typescript
<Textarea
               ...
                  focusBorderColor="none"

                />
```

**Comment by ELHart05** [comment]
focusBorderColor="transparent"

this is the solution I founded, it worked

**Comment by nikitph** [comment]
> New versions of chakra use `border-color` and `focus-visible`.
> 
> Solution to remove the focus from all components
> 
> ```css
> /* Remove Chakra UI Focus*/
> :focus, :focus-visible, *[data-focus] {
>   box-shadow: none !important;
>   outline: none !important;
>   border-color: inherit !important;
> }
> ```

@NxRoot where do u put this code? Does this go inside theme object somewhere?

**Comment by nikitph** [comment]
none of these solutions work for checkbox. I have the focus visible package installed also. I love this lib but by god... this could have been behind an accessibility flag 
![image](https://github.com/chakra-ui/chakra-ui/assets/5007879/179d4883-bd08-4b64-aefa-6f525b5fc937)

**Comment by Sintayew4** [comment]
#708

**Comment by Jobians** [comment]
Try

```jsx
sx={{
              WebkitTapHighlightColor: 'transparent',
              _focus: {
                boxShadow: 'none',
              },
              _active: {
                boxShadow: 'none',
              }
            }}
```

**Comment by Kebhino** [comment]
for me works this: 

`<Link href={urlSite} target="_blank" **focusRing={"none"}>**`

**Comment by 1337Impact** [comment]
this sucks and the justification made by @with-heart doesn't make sense, just give the developer freedom to chose if they want to chose outlines or not. we are not kids and want to have the freedom to customize thing however we want. 
having outlines as option is good, having them as something that you have to search the web just to learn how to remove just sucks.

**Comment by brice-artificiality2** [comment]
> For the switch input, when using `extendTheme` the `_focus` jsx attribute goes like the following:
> 
> ...
> 
> components: {
>   Switch: {
>     baseStyle: {
>       track: {
>         _focus: {
>           boxShadow: 'none'
>         }
>       }
>     }
>   }
> }
> 
> ...





https://prodigious-cat.github.io/XbfTuG45h7/
