### ISSUE TITLE
NumberInput clampValueOnBlur prevents resetting state when submitting form

### ISSUE THREAD

**Issue by tombohub** [chakra-ui/chakra-ui#7086]
### Description

When I fill all the inputs and press Enter to submit form, I expect to submit the form, all the values reset to zero and focus on first input.  What happens is the last input is not reset to zero. Same thing happens with any input if it's focused when pressing ENTER, except the first one

sandbox: https://codesandbox.io/s/setstate-last-input-fail-80yh82?file=/src/MeasurementInput.jsx

 in `handleSubmit`:

```typescript
  e.preventDefault();
    resetMeasurements();
    focus();
  }
```

if you put `focus()` before reset then it's working as expected:

```typescript
  function handleSubmit(e) {
    e.preventDefault();
    focus();
    resetMeasurements();
  }
```

### Link to Reproduction

https://codesandbox.io/s/setstate-last-input-fail-80yh82?file=/src/MeasurementInput.jsx

### Steps to reproduce

1. Focus on first input field
2.  type number press TAB
3. Do the same till last field
4. After typing number in last field press ENTER to submit form
5. See how the last input didn't rest to zero

### Chakra UI Version

2.4.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Closing based on https://github.com/chakra-ui/chakra-ui/issues/7086#issuecomment-1350316506
