### ISSUE TITLE
Chakra-ui NextJs 13 with NextLink and Chakra Link Hydration Error

### ISSUE THREAD

**Issue by ryanSN** [chakra-ui/chakra-ui#7090]
### Description

When I wrap a Chakra ui Link in a next/link within nextjs 13 I expect links to continue to function.
Currently getting a hydration UI error:
```Error: Hydration failed because the initial UI does not match what was rendered on the server.```

Looks to be due to the changes to Nextjs 13, nextjs's `<Link>` component which now automatically wraps children in an 
`<a>` tag.
They have a codemod to address any 

```js
<Link>
    <a>my link</a>
</Link>
```
But this seems to effect the Chakra Link component as well.

Following a couple of posts (
https://www.bharathikannan.com/blog/use-next-link-with-chakra-ui 
https://jools.dev/using-nextjs-link-with-chakra-ui-link
)

 Someone may have done the below
```js
 <NextLink href="/#" passHref>
    <Link>Chakra Link</Link>
 </NextLink>
 ```

### Link to Reproduction

https://codesandbox.io/p/sandbox/jovial-kare-igf688?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A18%2C%22endLineNumber%22%3A13%2C%22startColumn%22%3A6%2C%22startLineNumber%22%3A11%7D%5D

### Steps to reproduce

1. using a fresh nextjs 13 instance
2. Create a Chakra Link Component wrapped in a next/link with a passHref
3. yarn dev
4. refresh the page
5. you will see 3 hydration errors 

### Chakra UI Version

2.4.3

### Browser

Google Chrome 107.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I suspect the `<Link>` component in Chakra outputs an `<a>` tag, so wrapping will cause a `<a><a>` and thus a hydration error.

**Comment by JClackett** [comment]
Use like this:

```tsx
  <Link as={NextLink} href="/#">Chakra Link</Link>
```

**Comment by anubra266** [comment]
@ryanSN In nextjs 13, [Next Link renders an `a` tag by default](https://beta.nextjs.org/docs/upgrade-guide#link-component), so having the Chakra Link as a Child renders another `a` tag as the child of the `a` tag from nextjs.
What you can do is use the `as` prop to change the element rendered by Chakra Link
```html
<NextLink>
	<ChakraLink as="span"> Home </ChakraLink>
</NextLink>
```

**Comment by arjunlubana** [comment]
This worked for me. I set the link overlay as NextLink.
`
<LinkBox>
<LinkOverlay as={NextLink} href="#" passHref>
          Some blog post
</LinkOverlay>
<p>Lorem ipsum </p>
</LinkBox>
`

**Comment by arjunlubana** [comment]
Also can we change this in the docs

**Comment by RannyArcher** [comment]
you can even use _legacyBehavior_ prop besides passHref.

according to [Nextjs Docs](https://nextjs.org/docs/pages/api-reference/components/link#legacybehavior):

> An <a> element is no longer required as a child of <Link>. Add the legacyBehavior prop to use the legacy behavior or remove the <a> to upgrade. A [codemod is available](https://nextjs.org/docs/app/building-your-application/upgrading/codemods#new-link) to automatically upgrade your code.
> **Good to know**: when legacyBehavior is not set to true, all [anchor](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) tag properties can be passed to next/link as well such as, className, onClick, etc.

**Comment by FloweringDeathStar** [comment]
this should be easier...
