### ISSUE TITLE
Buttons inside `Drawer` are hidden on big screens using Chrome

### ISSUE THREAD

**Issue by sftsk** [chakra-ui/chakra-ui#7091]
### Description

When I am using a `Drawer` on a big screen/ big window on Chromium based browsers for some weird reason the buttons (and other possible form elements) towards the side it's coming from become invisible until I click one of them, then they all appear at once.
This even happens on the example page using the basic drawer example: https://chakra-ui.com/docs/components/drawer/usage

Attached are the screenshots, if the window is too big, the button is invisible.

### Link to Reproduction

https://chakra-ui.com/docs/components/drawer/usage

### Steps to reproduce

1. Use Chrome on a big screen (window wider than 2070px) and go to https://chakra-ui.com/docs/components/drawer/usage#basic-drawer
2. Click on `Open`
3. The `<DrawerCloseButton />` is visually hidden 

### Chakra UI Version

2.4.2

### Browser

Chrome Version 108.0.5359.98 (Official Build) (arm64), same happens in Arc 0.79.2 (36228)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

<img width="2992" alt="big screen right after open" src="https://user-images.githubusercontent.com/646910/206665224-0eeb5c57-5f93-4e67-8d4a-37c4bbdbaa31.png">
<img width="2992" alt="big screen hover works but button still not shown" src="https://user-images.githubusercontent.com/646910/206665231-9d98b04d-28d5-48e6-b1ad-56f9e7756af5.png">
<img width="1425" alt="smaller window and all works as expected" src="https://user-images.githubusercontent.com/646910/206665233-49dae32b-b5ee-4111-9c28-06eb54906ed6.png">

**Comment by sftsk** [comment]
Any update? This seems like a pretty big issue..

**Comment by anubra266** [comment]
Not quote clear on this issue @sftsk. I'm unable to reproduce it
<img width="1440" alt="CleanShot 2022-12-16 at 01 24 35@2x" src="https://user-images.githubusercontent.com/30869823/207994287-9a802b8c-ac9f-476f-bc26-5e5ea1b3e897.png">

**Comment by sftsk** [comment]
@anubra266 have you tried it on Chrome? What OS are you on?
I have made a video to better show what is happening:

https://user-images.githubusercontent.com/646910/208376007-11147130-6623-41eb-8881-459053d575d1.mov

(Sorry for the bad resolution but otherwise the file was too big)

**Comment by alkamin** [comment]
We're seeing the same behavior on 1.8.8

**Comment by hsl0505** [comment]
+ 1 same. Any update?

**Comment by cgarrovillo** [comment]
Same issue on 1.7.3.

**Comment by cgarrovillo** [comment]
@anubra266 Were you able to reproduce it?   Also I wonder if as a workaround an automatic onClick on an invisible button would work 🤔

**Comment by coverlv** [comment]
reproduce:
drag our chrome's width as wide as we can like below:

<img height="100" alt="image" src="https://user-images.githubusercontent.com/94817349/221807934-b55d3afb-0063-4597-860f-7c1599083e91.png">

if we input some text trigger it render again, the close icon will show again:

<img height="100" alt="image" src="https://user-images.githubusercontent.com/94817349/221807483-46a9821d-f0c1-4707-a4fd-1761b6c7c10d.png">



a way to fix:
close the motion animation of drawerContent:

```
 <DrawerContent
  motionProps={{
    initial: 'none',
    animate: 'none',
    exit: 'none',
  }}
>
```

**Comment by bosswissam** [comment]
Seeing the same issue on chrome `110.0.5481.177` macOS, any update?

**Comment by pete-willard** [comment]
Hello! I found that in my case the issue was caused by `backdropFilter` property (with a blur) added to input and select field styles. Hope this helps someone

**Comment by bj-nostra** [comment]
Appear to be having the same issue. What information can we provide that will help this get resolved?

Thanks in advance!

**Comment by DzunN86** [comment]
Hello! I got the same issue
but the case if it's opened on a mobile screen  with the props `placement="bottom"` `size="full"`
https://chakra-ui.com/docs/components/drawer#drawer-widths
![image](https://github.com/chakra-ui/chakra-ui/assets/26589341/f79bf0ed-fbaa-4fa8-8ee1-52042fbe1b83)

**Comment by nicoguefveneu** [comment]
Hello!
Still happening on big screens, at 1999px it's working, but from 2000px it' not working anymore, whatever the height is.
My config:
- Mac OS 12.6.1
- Chrome 116.0.5845.187

It's not working either on Edge (seems logic ^^)

But it's working on Firefox and Safari.

Hope it can help to fix it!

**Comment by selrond** [comment]
Just found out that it works properly if I don’t use HiDPI resolution. Probably a chromium bug?

**Comment by segunadebayo** [comment]
This is more of a chromium bug than it is related to Chakra UI. 

I tested it and couldn't reproduce it anymore. Perhaps it is now fixed?

**Comment by selrond** [comment]
Seems to be fixed indeed 👍

**Comment by nicoguefveneu** [comment]
Yes fixed as well 👌 


> Hello! Still happening on big screens, at 1999px it's working, but from 2000px it' not working anymore, whatever the height is. My config:
> 
> * Mac OS 12.6.1
> * Chrome 116.0.5845.187
> 
> It's not working either on Edge (seems logic ^^)
> 
> But it's working on Firefox and Safari.
> 
> Hope it can help to fix it!
