### ISSUE TITLE
Paid component with runaway scrollbar

### ISSUE THREAD

**Issue by FreddieFruitSticks** [chakra-ui/chakra-ui#7092]
### Description

When I view this component in Chrome https://pro.chakra-ui.com/components/marketing/flyout-menu I expected the commponent to load without recursively growing to beyond the screen. Instead the side scrollbar shows the component height is growing without bound

### Link to Reproduction

 https://pro.chakra-ui.com/components/marketing/flyout-menu

### Steps to reproduce

1. Go ['here'](https://pro.chakra-ui.com/components/marketing/flyout-menu)
2. Look at side scrollbar
3. Component grows without bound

### Chakra UI Version

The version the above link is using

### Browser

Version 107.0.5304.110 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
This has been fixed.
