### ISSUE TITLE
Number Input: change commands of the arrows

### ISSUE THREAD

**Issue by kul-sudo** [chakra-ui/chakra-ui#7093]
### Description

``` js
<NumberInput>
  <NumberInputField>
  <NumberInputStepper>
    <NumberIncrementStepper />
    <NumberDecrementStepper />
  </NumberInputStepper>
</NumberInput>
```

The Feature Request is the feature of changing the commands of ```<NumberIncrementStepper />``` and  ```<NumberDecrementStepper />```.
For instance, the feature of making the Increment Stepper go 1 number down and the Decrement Stepper go 1 number up.

### Problem Statement/Justification

There is a lot of different projects with different designs. If this is not enough, then here is an example:
A vertical ```div``` which contains elements and Number Inputs the make them change their positions in the order (from 1 to 10, for example). In this case, the Increment Stepper shall make the number in the input go down, so that it comes closer to 1, whereas the Decrement Stepper shall make the number go closer to 10. Indeed, for the user it is easier to see the arrow which goes up decreasing the number considering that fact that the elements of this ```div``` go **STARTING WITH** 1 and **FINISHING WITH** 10.
This is easiest example.

### Proposed Solution or API

``` js
<NumberInput>
  <NumberInputField>
  <NumberInputStepper>
    <NumberIncrementStepper />
    <NumberDecrementStepper />
  </NumberInputStepper>
</NumberInput>
```

### Alternatives

I have considered making my own custom buttons, but I am too afraid of breaking something in my immense project. A UI framework has to have this feature anyway.

**Comment by Tisks** [comment]
As far as I can understand... you need the increment stepper to decrease and the decrement one to increase?
Does this solution suffice? Reordering the steppers and swapping their icons to simulate it.
```
<NumberInput defaultValue={5} min={1} max={10} >
  <NumberInputField />
  <NumberInputStepper>
    <NumberDecrementStepper
      children={<TriangleUpIcon/>}
    />
    <NumberIncrementStepper
      children={<TriangleDownIcon/>}
    />
  </NumberInputStepper>
</NumberInput>
```

**Comment by kul-sudo** [comment]
> As far as I can understand... you need the increment stepper to decrease and the decrement one to increase? Does this solution suffice? Reordering the steppers and swapping their icons to simulate it.
> 
> ```
> <NumberInput defaultValue={5} min={1} max={10} >
>   <NumberInputField />
>   <NumberInputStepper>
>     <NumberDecrementStepper
>       children={<TriangleUpIcon/>}
>     />
>     <NumberIncrementStepper
>       children={<TriangleDownIcon/>}
>     />
>   </NumberInputStepper>
> </NumberInput>
> ```

Oh, mate. That's a really witty solution. Good job! It works.
