### ISSUE TITLE
Request to extend stack and grid from pseudobox

### ISSUE THREAD

**Issue by harisvsulaiman** [chakra-ui/chakra-ui#710]
This helps grid and stack have pseudo props.
I suggest we extend grid and stack from pseudo box.

I have tried using the emotion css prop, but it is cumbersome.

**Comment by with-heart** [comment]
Hi @harisvsulaiman! In the 1.0 release of Chakra (see #696), both `Stack` and `Grid` are created using `chakra.div`, meaning they both have full access to pseudo props. Hopefully this will be out for you to use within the next month :)
