### ISSUE TITLE
Tooltip will not open when tapping on Icon trigger on mobile device 

### ISSUE THREAD

**Issue by tom2drum** [chakra-ui/chakra-ui#7107]
### Description

I am using a custom Icon component as a trigger for Tooltip. Following this [doc](https://chakra-ui.com/docs/components/tooltip/usage#with-an-icon) I wrapped Icon in a span and it made it work in desktop browser. However, on mobile device tooltip will not show up when I tap on the trigger.

I found this issue in the latest update v2.4.2. If I rollback version to v2.3.1 everything works fine.

### Link to Reproduction

https://codesandbox.io/s/little-water-f32gcq

### Steps to reproduce

1. Go to https://f32gcq.csb.app/ on your mobile device
2. Tap on icon
3. Tooltip will not show up

### Chakra UI Version

2.4.2

### Browser

Mobile Safari 16.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Issue also can be reproduced if open the link in Google Chrome desktop in mobile device simulation mode

**Comment by jddeleon** [comment]
Also seeing this issue. I was able to find a workaround by making the tooltip a controlled component

``` 
const { isOpen, onOpen, onToggle, onClose } = useDisclosure();
             
<Tooltip label='Tooltip content' isOpen={isOpen}>
        <IconButton
          variant="unstyled"
          minW="none"
          minHeight="auto"
          height="auto"
          aria-label="more info"
          onMouseEnter={onOpen}
          onMouseLeave={onClose}
          onClick={onToggle}
          icon={<AiOutlineInfoCircle />}
        />
</Tooltip>

**Comment by aysegulkavaklii** [comment]
Same issue here, controlled component or shouldWrapChildren worked but to show up the tooltip first I should click the out of the component and then click the component on mobile devices.

**Comment by segunadebayo** [comment]
Hi @jddeleon,

I recommend switching from a Tooltip to a click-trigger Popover on mobile. We don't do the switch for you automatically since it's a subjective decision.
