### ISSUE TITLE
@chakra-ui/react installation with pnpm package manager

### ISSUE THREAD

**Issue by brandoncollins7** [chakra-ui/chakra-ui#7118]
### Description

There is another post like this here: https://github.com/chakra-ui/chakra-ui/issues/6820 but it is not true that it works.

I am getting this error with pnpm but all works fine with yarn:

import { tabsAnatomy } from "@chakra-ui/anatomy"

[vite] Internal server error: Failed to resolve import "@chakra-ui/anatomy" from "src\shared\theme\components\Tabs.ts". Does the file exist?

### Link to Reproduction

not able to make CodeSandbox

### Steps to reproduce

- Install with pnpm
- include "import { tabsAnatomy } from "@chakra-ui/anatomy""
- load application
- see error on screen

### Chakra UI Version

2.4.1

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Hi @brandoncollins7,

With pnpm, you need to install that package explicitly if you want to import from it.

```sh
pnpm i @chakra-ui/anatomy
```

Then you can use it as needed.

```
import { tabsAnatomy } from "@chakra-ui/anatomy"
```
