### ISSUE TITLE
Clicks not working after closing modals

### ISSUE THREAD

**Issue by leonard-henriquez** [chakra-ui/chakra-ui#7119]
### Description

When I close a modal, I expect to be able to click on buttons (or any interactive ui element) but I can't click anywhere as if every element were disabled.

It seems to be due to the div with the class `chakra-modal__content-container` that is still present on top.

https://user-images.githubusercontent.com/30215564/208254138-cd6f7adf-ad04-4e76-9262-6f8eb201a369.mov

https://user-images.githubusercontent.com/30215564/208254209-9f8cc2dd-457e-49a3-9120-01362f1da6d7.mov

### Link to Reproduction

n/a

### Chakra UI Version

2.4.4

### Browser

Google Chrome 108

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Rodrigo-P-Angeli** [comment]
+1 Same issue here

**Comment by Rodrigo-P-Angeli** [comment]
It fixed when I moved the declaration of the component to its parent. But it makes the parent component too big

**Comment by Rodrigo-P-Angeli** [comment]
Fixed by unmounting the whole modal. 

try wrapping the component with the isOpen variable, like: 

<img width="476" alt="Captura de Tela 2022-12-20 às 11 20 38" src="https://user-images.githubusercontent.com/58442800/208688873-3012d9dd-b158-4cea-88c6-387f97dbb16c.png">

when false, the modal will be unmounted, as well, the 'chakra-modal__content-container' class.

**Comment by anubra266** [comment]
Hmm...what chakra version is that. I remember having this issue before, but it was fixed later on

**Comment by Rodrigo-P-Angeli** [comment]
> Hmm...what chakra version is that. I remember having this issue before, but it was fixed later on

1.6.10

**Comment by leonard-henriquez** [comment]
I use the latest version of Chakra: @chakra-ui/react: "2.4.4"

**Comment by segunadebayo** [comment]
Hi @leonard-henriquez,

What version of `framer-motion` are you using?

**Comment by leonard-henriquez** [comment]
I had two different version of framer-motion.
I upgraded both to the last version (8.0.1) and it now seem to work !
Thank you!

**Comment by byrpatrick** [comment]
Thank you! I had the same issue using `framer-motion` `4.x.x`. Upgrading it to the latest makes it work.

**Comment by dellwatson** [comment]
still same issue with latest version 2.8, but as @Rodrigo-P-Angeli  suggested. fixed by unmount the component
