### ISSUE TITLE
[Modal] `blockScrollOnMount` fails on iOS devices

### ISSUE THREAD

**Issue by ansonkao** [chakra-ui/chakra-ui#712]
**Describe the bug**
`blockScrollOnMount` fails on iOS devices. Scrolling the background remains, and the following error appears in the console:
```
disableBodyScroll unsuccessful - targetElement must be provided when calling disableBodyScroll on IOS devices.
```

See https://github.com/willmcpo/body-scroll-lock/blob/master/src/bodyScrollLock.js#L148

**Expected Behavior**
Scrolling should stop.

**To Reproduce**
1. Use an iOS device
2. Go to https://chakra-ui.com/modal#block-scrolling-when-modal-opens
3. Click on any modal (by default, they all have `blockScrollOnMount = true`)
4. Scroll the page

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Safari
 - Version: Tested on both 13.4.1 and 11

**Comment by keshav-bohr** [comment]
Hi @ansonkao 
I was unable to reproduce the issue
iOS device, safari version 13.1

**Comment by segunadebayo** [comment]
Hi @ansonkao,

We also faced issues with the internal library used to manage scroll lock. We've updated it to one that's more reliable and works on iOS.

We'll release an update shortly.

**Comment by gaurangrshah** [comment]
I can confirm I'm also seeing this issue on OSX, tested in both safari and chrome, has this been updated already? 

![image](https://user-images.githubusercontent.com/1086269/93557063-21e77580-f948-11ea-9536-9bba0204aa1a.png)

**Comment by PawelJ-PL** [comment]
I can observe similar error message on Linux (Firefox and Chrome). When I'm opening following modal:
```jsx
    <Modal isOpen={isOpen} onClose={onClose}>
            <ModalOverlay />
            <ModalContent>
                <ModalBody>FOO BAR</ModalBody>
                <ModalFooter>
                    <Button size="xs" onClick={onClose} variantColor="gray" marginX={"0.2em"}>
                        Cancel
                    </Button>
                    <Button size="xs" variantColor="blue" marginX={"0.2em"}>
                        Create
                    </Button>
                </ModalFooter>
            </ModalContent>
        </Modal>
```

I can see error in developer console:

`enableBodyScroll unsuccessful - targetElement must be provided when calling enableBodyScroll on IOS devices. `

**Comment by GonzaCoding** [comment]
> I can observe similar error message on Linux (Firefox and Chrome). When I'm opening or closing following modal:
> 
> ```js-jsx
>     <Modal isOpen={isOpen} onClose={onClose}>
>             <ModalOverlay />
>             <ModalContent>
>                 <ModalBody>FOO BAR</ModalBody>
>                 <ModalFooter>
>                     <Button size="xs" onClick={onClose} variantColor="gray" marginX={"0.2em"}>
>                         Cancel
>                     </Button>
>                     <Button size="xs" variantColor="blue" marginX={"0.2em"}>
>                         Create
>                     </Button>
>                 </ModalFooter>
>             </ModalContent>
>         </Modal>
> ```
> 
> I can see error in developer console:
> 
> `enableBodyScroll unsuccessful - targetElement must be provided when calling enableBodyScroll on IOS devices. `

same issue when opening a Modal, in Windows with Chrome. The modal es Wrapped into a separated component and I pass onClose and isOpen as props.

**Comment by PawelJ-PL** [comment]
I observed one more strange thing. I see the same message also when I have defined a modal (even closed) on the page and go to another page (clicking on the link from React Router, which updates the history).

If I throw the modal away from the page, the problem does not occur.

**Comment by ljosberinn** [comment]
https://github.com/willmcpo/body-scroll-lock/issues/190 might be related

**Comment by sarendsen** [comment]
Having the same issue.

**Comment by PawelJ-PL** [comment]
After migration to V1 (version `@chakra-ui/core": "1.0.0-rc.3`) problem no longer exists

**Comment by sarendsen** [comment]
Can confirm. Fixed in the RC

**Comment by UcheSylvester** [comment]
I just upgraded to `@chakra-ui/core: "1.0.0-rc.3"` but I'm still getting the same error and blockScrollOnMount isn't working as expected

**Comment by ljosberinn** [comment]
@UcheSylvester would you mind trying again after these steps:
- remove `node_modules`
- remove `package-lock.json` | `yarn.lock`
- reinstall with `rc.5` (all chakra packages must have the same version, else you end up with 🍝

**Comment by Prottoy2938** [comment]
using `@chakra-ui/core: "1.0.0-rc.5"` doesn't solves the error

**Comment by pinutz23** [comment]
Updating to `@chakra-ui/core: 1.x.x` is no solution, because it introduces a lot of other breaking changes which than have to be resolved. There should be a patch version if there is a solution to this.

**Comment by christophemarois** [comment]
@pinutz23 #687 Patch to quickly fix the issue in `@chakra-ui/core: 0.8.0`

1. Put this in `./patches/@chakra-ui+core+0.8.0.patch`

```patch
diff --git a/node_modules/@chakra-ui/core/dist/es/Drawer/index.js b/node_modules/@chakra-ui/core/dist/es/Drawer/index.js
index 7f0779e..5352e4a 100644
--- a/node_modules/@chakra-ui/core/dist/es/Drawer/index.js
+++ b/node_modules/@chakra-ui/core/dist/es/Drawer/index.js
@@ -40,6 +40,7 @@ var Drawer = function Drawer(_ref) {
       }
     }, jsx(Modal, _extends({
       isOpen: true,
+      scrollBehavior: 'inside',
       onClose: onClose,
       finalFocusRef: finalFocusRef,
       formatIds: function formatIds(id) {
diff --git a/node_modules/@chakra-ui/core/dist/es/Modal/index.js b/node_modules/@chakra-ui/core/dist/es/Modal/index.js
index 67828ba..97f7b30 100644
--- a/node_modules/@chakra-ui/core/dist/es/Modal/index.js
+++ b/node_modules/@chakra-ui/core/dist/es/Modal/index.js
@@ -118,6 +118,7 @@ var Modal = function Modal(_ref2) {
 
   useEffect(function () {
     var dialogNode = contentRef.current;
+    if (!dialogNode) return;
 
     if (isOpen && blockScrollOnMount) {
       disableBodyScroll(dialogNode, {
@@ -128,7 +129,7 @@ var Modal = function Modal(_ref2) {
     return function () {
       return enableBodyScroll(dialogNode);
     };
-  }, [isOpen, blockScrollOnMount, preserveScrollBarGap]);
+  }, [contentRef.current, isOpen, blockScrollOnMount, preserveScrollBarGap]);
   useEffect(function () {
     var func = function func(event) {
       if (event.key === "Escape" && closeOnEsc) {

```

2. Run `npm install --save-dev patch-package`
3. Add `"postinstall": "patch-package"` to `package.json` scripts
4. Run `npx patch-package` once

**Comment by pinutz23** [comment]
@christophemarois Awesome! You did not only fix my problem, but I also learned about a new awesome package 👍 Thanks!

**Comment by sSwiergosz** [comment]
@christophemarois - same as above  👍 👍 👍 Thanks for your help!

**Comment by Justbigmack** [comment]
Not sure why this is closed. This is still an issue. Updating to @chakra-ui/core: 1.x.x introduced breaking changes in the app, so the patch solution from Christopher above is the only one we can go with for now.

**Comment by ljosberinn** [comment]
@Justbigmack Because the initial issue was for v0 and since the team has no ios device, it was considered fixed. It was also reported as fixed twice [here](https://github.com/chakra-ui/chakra-ui/issues/712#issuecomment-698512586) and right above. And since v0 won't receive another release to my knowledge, we currently [have conflicting info whether it's fixed in the latest rc or not](https://github.com/chakra-ui/chakra-ui/issues/712#issuecomment-706679898).

**Comment by dusty** [comment]
I'm getting this error logged to the console for me as well, but not even using an ios device, just using firefox or chrome on a mac.  

I found I could prevent the errors from logging to the console, by locking to a previous body-scroll-lock version using resolutions in my package.json file.

```
"resolutions": {
    "body-scroll-lock": "3.0.3"
  },
```

Note: looking through the code, it appears they dropped body-scroll-lock and replaced it with react-remove-scroll in v1.

**Comment by diogolessa** [comment]
I am facing the same with chakra `v0.8.0`, using on Linux Chrome/Firefox. Is there any prediction about the real fix? Not sure why it's closed. Thanks.

**Comment by paambaati** [comment]
For folks still on v0.x, @dusty's comment above (https://github.com/chakra-ui/chakra-ui/issues/712#issuecomment-715487814) has a solution that works.

I can confirm that using the latest stable version of `body-scroll-lock` seems to fix this issue —

```
"resolutions": {
    "body-scroll-lock": "3.1.5"
}
```

**Comment by diogolessa** [comment]
Thansk, @dusty . Resolving to `3.0.3` solved the problem.

**Comment by easydatasolution** [comment]
> I'm getting this error logged to the console for me as well, but not even using an ios device, just using firefox or chrome on a mac.
> 
> I found I could prevent the errors from logging to the console, by locking to a previous body-scroll-lock version using resolutions in my package.json file.
> 
> ```
> "resolutions": {
>     "body-scroll-lock": "3.0.3"
>   },
> ```
> 
> Note: looking through the code, it appears they dropped body-scroll-lock and replaced it with react-remove-scroll in v1.

Additional note: this is currently **only natively supported using yarn and not npm**.

If you use npm, one way to solve this is by using `npm-force-resolutions` like this:
```json
"scripts": {
  "preinstall": "npx npm-force-resolutions"
}
```
Also a [npm RFC is acceped](https://github.com/npm/rfcs/blob/latest/accepted/0009-package-overrides.md) to add this to npm.

**Comment by pinutz23** [comment]
> I'm getting this error logged to the console for me as well, but not even using an ios device, just using firefox or chrome on a mac.
> 
> I found I could prevent the errors from logging to the console, by locking to a previous body-scroll-lock version using resolutions in my package.json file.
> 
> ```
> "resolutions": {
>     "body-scroll-lock": "3.0.3"
>   },
> ```
> 
> Note: looking through the code, it appears they dropped body-scroll-lock and replaced it with react-remove-scroll in v1.

Additional note: this is currently **only natively supported using yarn and not npm**.

If you use npm, one way to solve this is by using `npm-force-resolutions` like this:
```json
"scripts": {
  "preinstall": "npx npm-force-resolutions"
}
```
Also a [npm RFC is acceped](https://github.com/npm/rfcs/blob/latest/accepted/0009-package-overrides.md) to add this to npm.

**Comment by maxdbarton97** [comment]
For me this wasn't actually an issue with the package, I just had to wait till the target element was defined.
`
    const [targetElement, setTargetElement] = useState(null);
    const targetRef = createRef();

    useEffect(() => {
        setTargetElement(targetRef.current);
    }, []);

    useEffect(() => {
        if (targetElement) {
            if (isOpen) enableBodyScroll(targetElement);
            else disableBodyScroll(targetElement);
        }
    }, [targetElement, isOpen]); 
`
