### ISSUE TITLE
Opacity prop cause zIndex issue

### ISSUE THREAD

**Issue by dendrofen** [chakra-ui/chakra-ui#7120]
### Description

When set opacity to Text, zIndex automatically increasing.
Elements with position sticky goes under Text with opacity prop.

![image](https://user-images.githubusercontent.com/54393894/208268308-0c26e506-1ff4-4c3e-873f-787c80193d52.png)

### Link to Reproduction

https://codesandbox.io/s/beautiful-scooby-xoi4mc?file=/src/index.js

### Steps to reproduce

1. Set opacity to Text '0.65'
2. Set Heading position: sticky
3. Scroll down, so sticky heading overlap with Text

### Chakra UI Version

2.4.4

### Browser

Google Chrome 108.0.5359.98 (Official Build) (x86_64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@dendrofen This isn't a chakra issue. This is an addition with pure CSS
<img width="1112" alt="CleanShot 2022-12-21 at 10 03 52@2x" src="https://user-images.githubusercontent.com/30869823/208865186-7a41f35b-40b3-409d-b8d3-d93a5c9dfd2d.png">

But to assist with your underlying css issue, all you have to do is add `zIndex="1"` to the sticky elements
