### ISSUE TITLE
Cannot style font size of Button component in baseStyle

### ISSUE THREAD

**Issue by kaluabentes** [chakra-ui/chakra-ui#7121]
### Description

Cannot style font size of Button component in baseStyle key of theme override object

### Link to Reproduction

https://codesandbox.io/s/affectionate-ritchie-i15u89?file=/pages/index.tsx

### Steps to reproduce

1. Go to 'theme.js'
2. Add baseStyle in Button style override
3. Add fontSize prop

### Chakra UI Version

2.4.1

### Browser

Microsoft Edge 

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@kaluabentes The fontSize is defined in the [theme sizes key](https://github.com/chakra-ui/chakra-ui/blob/05d2356d7d65e7d9d0b56b3ad7f2ef5181d738fb/packages/components/theme/src/components/button.ts#L168). The default size for a button is [md](https://github.com/chakra-ui/chakra-ui/blob/05d2356d7d65e7d9d0b56b3ad7f2ef5181d738fb/packages/components/theme/src/components/button.ts#L201). This overrides anything defined in baseStyle. So if you want a different fontSize, you can
- Define a new Sizes key in your theme, and use it as the default size in [`defaultProps`](https://github.com/chakra-ui/chakra-ui/blob/05d2356d7d65e7d9d0b56b3ad7f2ef5181d738fb/packages/components/theme/src/components/button.ts#L199)
- You can edit the `md` size, which is the default button size. Note that all buttons in your application will reflect this particular change by default, unless you then give them respective individual fontSizes. Example below:
<img width="1114" alt="CleanShot 2022-12-20 at 12 44 40@2x" src="https://user-images.githubusercontent.com/30869823/208660289-ecc2e6b1-3d50-482b-8964-9d799a093f68.png">
