### ISSUE TITLE
Divider allow responsive orientation

### ISSUE THREAD

**Issue by JohnFedorchak** [chakra-ui/chakra-ui#7125]
### Description

Allow the Divider to have an orientation set by an object, such as
```jsx
<Divider orientation={{ base: "horizontal", md: "vertical" }} />
```

### Problem Statement/Justification

This should be added to be consistent with the other reactive components and their attributes, 

and to make it easy to display a horizontal line when things are stacked vertically in a mobile layout, but to display a vertical line when things are stacked horizontally on a desktop layout.

### Proposed Solution or API

I think that it needs to be made a `ResponsiveValue<"horizontal" | "vertical">`?

### Additional Information

Currently I'm using something like
```jsx
<Box
  w={{ base: "80%", md: "2px" }}
  h={{ base: "2px", md: "80%" }}
/>
```
to accomplish this.

**Comment by anubra266** [comment]
@JohnFedorchak You can make use of the `useBreakpointValue` hook for this, but responsive orientation is not a design decision we want to take right now, to avoid new complexities in the codebase.
