### ISSUE TITLE
import_react2.createContext is not a function with Next.js 13 app directory with ChakraProvider in root layout

### ISSUE THREAD

**Issue by Southclaws** [chakra-ui/chakra-ui#7133]
### Description

Decided to experiment with Next.js 13's App directory beta. It seems Chakra isn't compatible with this yet and I can't figure out why from the error.

After a refresh I saw:

```
You're importing a component that needs useState. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.

    ,-[74:1]
 74 | import { createContext as createContext2 } from "@chakra-ui/react-context";
 75 | import { useControllableState } from "@chakra-ui/react-use-controllable-state";
 76 | import { mergeRefs } from "@chakra-ui/react-use-merge-refs";
 77 | import { useCallback, useEffect, useId, useRef, useState } from "react";
    :                                                 ^^^^^^^^
 78 | function useAccordion(props) {
 79 |   const {
 80 |     onChange,
    `----
```

So I marked it as client and now it's:

```
TypeError: can't access property "call", originalFactory is undefined
```

So there's clearly a lot going wrong here! I know Next.js 13's new app directory and layouts feature is not ready yet but figured I'd post an issue since I couldn't find any related to the issues with upgrading.

### Link to Reproduction

https://codesandbox.io/s/chakra-next-13-layouts-yo24vb?file=/app/layout.tsx

### Chakra UI Version

2.4.4

### Browser

All major browsers

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@Southclaws In your reproduction, none of the pages is marked as client. Add `"use client"` to the top of the files where chakra is invoked.

**Comment by Southclaws** [comment]
Oh yeah I did try that, and it resulted in a different error. Sorry I forgot to post that. Will get to it later today 👍
