### ISSUE TITLE
Tab navigation doesn't work inside Menu component

### ISSUE THREAD

**Issue by nirajmchauhan** [chakra-ui/chakra-ui#7134]
### Description

Tab navigation doesn't work if form fields are added to `MenuList`

### Link to Reproduction

https://codesandbox.io/s/bold-brattain-sjcgik?file=/src/index.tsx

### Steps to reproduce

1. Add a `Menu`
2. Within `MenuList`, add some inputs or buttons
3. Now when you open the menu and try to navigate the form fields using `TAB` key, it will not work.

### Chakra UI Version

latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @nirajmchauhan,

Focus is fully managed by the `Menu` and it can't contain other elements other than menuitem, and their radio/checkbox equivalent.

![CleanShot 2022-12-23 at 13 58 08@2x](https://user-images.githubusercontent.com/6916170/209315079-5f33be48-1c75-4517-9257-84c75ae258b7.png)

**Comment by adedaniel** [comment]
Optionally, you can go for the [Popover](https://chakra-ui.com/docs/components/popover/usage) component
