### ISSUE TITLE
Shortened styled-system props are sometimes ignored with the default theme (h on Button)

### ISSUE THREAD

**Issue by bertho-zero** [chakra-ui/chakra-ui#7136]
### Description

When I add a `h` property on a `Button` (variant `link`) it is ignored, if I replace `h` with `height` it works fine.

### Link to Reproduction

https://codesandbox.io/s/inspiring-artem-1qsf5t

### Steps to reproduce

1. Open the Devtools
2. Look at the height of the button

### Chakra UI Version

2.4.4

### Browser

Brave 1.46.144

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

I see in the react debugger that the `Button`'s `__css` key contains `h` and `height`, in addition to the `h` key next to `__css` which is ignored.

**Comment by segunadebayo** [comment]
Closing since the PR is merged

**Comment by bertho-zero** [comment]
I wouldn't have thought this PR would have fixed that bug too, that's great
