### ISSUE TITLE
MenuList scroll jittering issue

### ISSUE THREAD

**Issue by nathsou** [chakra-ui/chakra-ui#7139]
### Description

When using a scrollable `MenuList`, on some occasions the scrollbar jitters back and forth.
I could not reproduce on 1.8.8.

See:

https://user-images.githubusercontent.com/4953827/208670238-e9c958eb-23c4-42d3-aa89-d025dbf7cf04.mp4

### Link to Reproduction

https://codesandbox.io/s/thirsty-blackwell-rblti6

### Steps to reproduce

1. Go to the sandbox or create a menu list with a restricted height and `overflow-y: scroll`
2. Using your mouse cursor, circle around the list items (make sure to leave the component and enter it again multiple times)
3. At some point, the items under the cursor stop being highlighted.
4. Scroll inside the menu list, the scrollbar should move back and forth uncontrollably.

### Chakra UI Version

2.0.0 -> 2.4.4

### Browser

Google Chrome 108

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Possibly linked to https://github.com/chakra-ui/chakra-ui/issues/7100

**Comment by uson1x** [comment]
Same issue here, have you been able to find any workarounds so far? I haven't, unfortunately

**Comment by Zoleas** [comment]
> 

Hello, I work with @nathsou (he is in vacation right now)
Sadly, we had to revert the update of the library on our side. We will wait for a fix.

**Comment by uson1x** [comment]
[@Villadshamme](https://github.com/Villadshammershoi) found out that if you change elements to
```
<MenuList as="ul" />
  <MenuItem as="li" />
  ...
```
the jittering is gone. We didn't notice other side effects, not sure if there are.

**Comment by vkbansal** [comment]
I'm also facing the same issue, when upgrading from 2.4.1 to 2.4.4.

I tried all the versions in between and the the issue appears after `2.4.2`.

I believe [this dependency](https://github.com/chakra-ui/chakra-ui/commit/f84891b103c1b666f660018442fd92151e3ea868#diff-0e731dd338290c1246d8b5b3d9c3c27f47adcd25ab37a6b236f39b6822337d9bL177) is causing the issue.

**Comment by nathsou** [comment]
> [@Villadshamme](https://github.com/Villadshammershoi) found out that if you change elements to
> 
> ```
> <MenuList as="ul" />
>   <MenuItem as="li" />
>   ...
> ```
> 
> the jittering is gone. We didn't notice other side effects, not sure if there are.

Indeed thanks, this looks like a satisfactory temporary fix, the only change in my tests is the cursor on the list items which is now `default` instead of `pointer` but this can be changed very easily.

**Comment by themeltdown** [comment]
> [@Villadshamme](https://github.com/Villadshammershoi) found out that if you change elements to
> 
> ```
> <MenuList as="ul" />
>   <MenuItem as="li" />
>   ...
> ```
> 
> the jittering is gone. We didn't notice other side effects, not sure if there are.

As well having similar issues. This particular workaround made the scroll smoother. 
However there is an issue, when the curse is at the start or end at the MenuList container, it scroll automatically fully. 

So far no fully working workaround is available

**Comment by mantariksh** [comment]
@nathsou I've opened #7315 to address this. It should be fixed in this codesandbox: https://codesandbox.io/s/hungry-kate-b17or5

In the meantime, I've found that reverting to version 2.4.1 fixes the issue on my project.

By the way, thanks for the detailed steps to reproduce the issue, they were really helpful!

**Comment by nathsou** [comment]
@mantariksh Excellent, thanks a lot :)

**Comment by asimplify** [comment]
Still facing this issue in v2.6.1
