### ISSUE TITLE
isRequired in FormControl has incorrect behaviour with Switch component

### ISSUE THREAD

**Issue by anothertempore** [chakra-ui/chakra-ui#7145]
### Description

When I toggle Switch from true to false, I expected Switch turns into false and submit successfully but the required error shows up.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-v2-4-4-switch-9k2630

### Steps to reproduce

1. Go to CodeSandBox repo
2. Click on 'Switch' to toggle it off
3. Click on 'Submit' button

### Chakra UI Version

2.4.4

### Browser

Google Chrome 93

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

1. I use React Hook Form
2. The v1.6.2 has the correct behaviour, could check https://codesandbox.io/s/chakra-ui-v1-6-2-switch-u2oi7b?file=/src/index.js to try it out.

**Comment by Brennvo** [comment]
This sounds like the nature of a switch. Both a switch and checkbox are binary in that they are either true or false. Required in this sense means that the value of the switch should be true.

An example would be terms and conditions at the bottom of the page. They are marked as "required", which means you must agree to the terms by marking the checkbox as selected.

If a value of `false` is indeed valid in your situation, I would recommend using a radio buttons that are initially unset. Then, you can require one of those radio buttons to be selected, in which case you can select the "falsy" value as a valid option.
