### ISSUE TITLE
Cannot specify certain styles in multipart components (Select/Input)

### ISSUE THREAD

**Issue by SheaBelsky** [chakra-ui/chakra-ui#7150]
### Description

When I specify `borderColor` for multipart components, I expect the provided `borderColor` value to take effect in my theme, but it does not take effect. This also applies to a variety of other styles depending on the component in question.

### Link to Reproduction

https://codesandbox.io/s/loving-star-zfd1y6?file=/src/theme/chakra.ts

### Steps to reproduce

1. Follow the instructions to apply styles to a multipart Input or Select (https://chakra-ui.com/docs/components/input/theming or https://chakra-ui.com/docs/components/select/theming)
2. Apply the `borderColor` style
3. View the output in the UI
4. Observe how other styles are applied, but not `borderColor`. For the `Input`, observe how many styles are specified, but only `padding` is used, while every other style is disregarded. For the `Input`, I notice that `border`, `backgroundColor` and `color` are applied styles, but `backgroundColor` and `color` are overridden by other Chakra UI styles (when this should not be the case.) `borderColor` is never applied.

### Chakra UI Version

2.4.4

### Browser

Google Chrome 108

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by SheaBelsky** [comment]
I was able to resolve this by specifying a custom variant and then using the variant as the default for my styles, but it doesn't solve the underlying issue of this functionality not working as documented.

Working code:

```js
import { createMultiStyleConfigHelpers } from "@chakra-ui/react";
import { selectAnatomy } from "@chakra-ui/anatomy";

const { definePartsStyle, defineMultiStyleConfig } =
  createMultiStyleConfigHelpers(selectAnatomy.keys);

const defaultVariant = definePartsStyle({
  field: {
    backgroundColor: "white",
    borderColor: "gray.500",
    borderRadius: "12px",
    border: "1px solid"
  }
});

const selectMultistyleConfig = defineMultiStyleConfig({
  defaultProps: {
    variant: "mentra"
  },
  variants: {
    mentra: defaultVariant
  }
});

export default selectMultistyleConfig;
```

I should be able to use `baseStyle` for this without having to specify a custom variant, as the documentation describes.

**Comment by SheaBelsky** [comment]
This also isn't working with `Textarea` components using this code:


```js
import { defineStyle, defineStyleConfig } from "@chakra-ui/react";

const textareaConfig = defineStyleConfig({
  baseStyle: defineStyle({
    borderRadius: "12px",
    color: "red"
  })
});

export default textareaConfig;
```

`color: red` is applied in CSS, but the `borderRadius` is not.

**Comment by anubra266** [comment]
@SheaBelsky Variants have higher specificity than `baseStyles`. Anything defined in the variants override the baseStyle, so all those changes you're making to `baseStyles` and not reflecting are being overridden by the default variant. For example, the [default variant](https://github.com/chakra-ui/chakra-ui/blob/bad865c9b5be80f126c4133a77240be527c35c30/packages/components/theme/src/components/input.ts#L207) in the Input is `outline`.
You can customize the outline variant to customize how you want your inputs to look by default, or you can create a new variant, and set it as the default in your custom theme.
Also note that stuff like fontSize, is set in the sizes key of the component theme, so it'll override the `baseStyles` too. Look into the [default theme](https://github.com/chakra-ui/chakra-ui/blob/bad865c9b5be80f126c4133a77240be527c35c30/packages/components/theme/src/components/input.ts#L207) to see how it's structured by default.

**Comment by SheaBelsky** [comment]
Got it, is there a reason the documentation for each of these components suggests a way that is incorrect? I would be happy to open a pull request describing the default variants for these components so that the documentation is correct.

**Comment by anubra266** [comment]
@SheaBelsky To the best of my knowledge, the docs already explain it well, though I'd love to know what you think the docs is missing

**Comment by SheaBelsky** [comment]
@anubra266 Looking at just the Input component, one of the sections in the documentation is titled "Customizing the default theme". As a lay person with no knowledge that the Input component has a variant that I have to configure, I would expect that this code as provided in the documentation would be all that is required to customize the default appearance of the Input component. 

https://chakra-ui.com/docs/components/input/theming#customizing-the-default-theme

This documentation makes no mention of needing to override the `outline` variant in order to actually set base styles that take precedent over existing `outline` styles. If that's a necessary part of customizing the default theme of the Input (as the title of that section describes), I would expect the documentation to contain information about needing override the `outline` variant and use that as the starting point for any style customizations that should apply to all Input components.

**Comment by SheaBelsky** [comment]
The documentation for the Button component does a great job of describing what I'm talking about:

https://chakra-ui.com/docs/components/button/theming

On this page, they explicitly say "The default variant is `outline`, so you have to set styles on the `outline` variant". And everything else follows from that. Perhaps it's just a discrepancy that this was missed for the Input component - but this is the guideline for what I would have expected to read for the Input component.

**Comment by michielglibert** [comment]
I agree with @SheaBelsky that this is really confusing. I was expecting the example on theming the `Input` component to work out of the box but it had no effect. To me this is clearly a mistake that was made in the documentation. Other pages about theming a component seem to have working examples with the `variant` included.
