### ISSUE TITLE
Why don't support CircularProgress Theme

### ISSUE THREAD

**Issue by dyk98** [chakra-ui/chakra-ui#7153]
### Description

when i code my custom component, i can't find components/theme/src/components/circularProgress.ts only progress.ts, but it don't useful for circularProgress. And i find circularProgressAnatomy but i don't know how to use it
why we don't support theme of CircularProgress

### Link to Reproduction

null

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.4.3

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is because the CircularProgress is based on SVG properties, not CSS properties. That's why we don't provide a theme for it.
