### ISSUE TITLE
Font loaded using `next/font` should work in portals (like in Modals)

### ISSUE THREAD

**Issue by Inambe** [chakra-ui/chakra-ui#7157]
### Description

I was confused if it was a feature request or a bug nevertheless, but I believe fonts loaded via `next/font` should be applied to portals (e.g. in Modals)

Right now, when I use `next/font` and apply it to chakra-ui theme, everything works great except in portals. It's very logical considering how `next/font` works and can be fixed by going other routes than suggested in the `next/font` official guide.

I looked for it and can't find anything fixing this properly.

### Problem Statement/Justification

I explained the problem in the Description.
Reason: Because `next/font` is being used a lot and even will even go further so chakra-ui should handle that.

### Proposed Solution or API

Maybe copy the same fonts in portals that are set to `fonts.body`. I'm not sure about the solutions.

### Alternatives

Since `next/font` generates a class that we use on main/div in `_app.js` to apply the font to the app (as suggested in their docs) we could set the same class to the root element, and font will work.

**Comment by segunadebayo** [comment]
Hi @Inambe,

You want to apply the `next/font` generated class to `body`, not the `main/div` to get it working in Portals.

Portals render elements as a child of `body`, hence the reason it doesn't work.

**Comment by davidreis97** [comment]
Hi @segunadebayo,

and how can one apply the `next/font` generated class to `body` given that it's not possible to use `next/font` inside `_document.tsx`?

**Comment by STiXzoOR** [comment]
> Hi @segunadebayo,
> 
> and how can one apply the `next/font` generated class to `body` given that it's not possible to use `next/font` inside `_document.tsx`?
> 
> **EDIT**
> 
> I got it, here's how I did it:
> 
> ```
> const theme = extendTheme({
>   styles: {
>     global: () => ({
>       body: {
>         fontFamily: myFont.style.fontFamily
>       }
>     })
>   }
> })
> ```

Hi @segunadebayo, @davidreis97 i did something similar on a project but in doing so, it breaks the theme typings generation when we call `chakra-cli`:

<img width="618" alt="image" src="https://user-images.githubusercontent.com/23358296/213866947-31771fd0-3395-44e4-8ae4-6f5189a0207f.png">

**Comment by MYKEU** [comment]
@STiXzoOR out of curiosity, did you manage to solve that issue?

**Comment by dalindev** [comment]
> > Hi @segunadebayo,
> > and how can one apply the `next/font` generated class to `body` given that it's not possible to use `next/font` inside `_document.tsx`?
> > **EDIT**
> > I got it, here's how I did it:
> > ```
> > const theme = extendTheme({
> >   styles: {
> >     global: () => ({
> >       body: {
> >         fontFamily: myFont.style.fontFamily
> >       }
> >     })
> >   }
> > })
> > ```
> 
> Hi @segunadebayo, @davidreis97 i did something similar on a project but in doing so, it breaks the theme typings generation when we call `chakra-cli`:
> 
> <img alt="image" width="618" src="https://user-images.githubusercontent.com/23358296/213866947-31771fd0-3395-44e4-8ae4-6f5189a0207f.png">

I have the same issues... 😿

**Comment by Belco90** [comment]
Getting the same issue here! Since I started using `next/font` in my custom theme, the typings started failing:
![CleanShot 2023-05-02 at 13 53 53](https://user-images.githubusercontent.com/2677072/235659035-16272fd7-13c7-45d4-8d1e-9bec3c451596.png)

**Comment by Belco90** [comment]
I figured out a workaround thanks to [applying `next/font` in `<head>`](https://nextjs.org/docs/basic-features/font-optimization#apply-the-font-in-head).

So basically you have to set your custom fonts in your Chakra's custom theme using css vars, and then define such vars in your `_app.tsx` with built-in styled-jsx:
![CleanShot 2023-05-02 at 14 14 44](https://user-images.githubusercontent.com/2677072/235663379-f6fc59e5-a265-4740-b082-0243c8bafac2.png) 
![image](https://user-images.githubusercontent.com/2677072/235663731-7f12ddd8-33c1-48e2-aa6a-b591171b76fb.png)


You can see the commit here: https://github.com/Belco90/personal-website/commit/70b0821fa4fe6ba3021b177be932f03cb7fd3892

**Comment by STiXzoOR** [comment]
@Belco90 I went with the emotion way and attached the vars to to the `Global` component. In that way i can use the fonts anywhere even in storybook

<img width="493" alt="image" src="https://user-images.githubusercontent.com/23358296/235664249-ef6e878a-d22e-41ba-b3bd-1dff248b46a8.png">
