### ISSUE TITLE
Show only 1 toast at a time

### ISSUE THREAD

**Issue by naama-melio** [chakra-ui/chakra-ui#7162]
### Description

Is there an option to display only 1 toast at a time?

### Problem Statement/Justification

Sometimes you don't want the toasts to stack on top of each other, you want them to replace each other.

### Proposed Solution or API

-

**Comment by michefraim** [comment]
Toast id's can be used for this

> The id of the toast. Mostly used when you need to prevent duplicate. By default, we generate a unique id for each toast

**Comment by MrAngelos6** [comment]
Maybe, when you want to replace it, you can close the current one, et open a new one. They won't stack like you want :)
Use a ref on the current like the docs : https://chakra-ui.com/docs/components/toast/usage#closing-toasts
