### ISSUE TITLE
Error: Duplicate parameter name not allowed in this context..... , when add ChakraProvider inside pages/_app.js.

### ISSUE THREAD

**Issue by zwelhtetyan** [chakra-ui/chakra-ui#7163]
### Description

![Screenshot from 2022-12-26 15-27-04](https://user-images.githubusercontent.com/89287841/209528679-8674f166-01d6-4407-aa5f-7a570e3028e5.png)

![Screenshot from 2022-12-26 15-26-48](https://user-images.githubusercontent.com/89287841/209528691-bf8342cd-896d-4655-b874-2c645aabdffd.png)

### Link to Reproduction

https://github.com/zwelhtetyan/realtor-zhy

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.4.4

### Browser

chrome

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Hi @zwelhtetyan,

This is not a Chakra UI bug. Most likely related to Next.js.

Please open the issue there.

**Comment by zwelhtetyan** [comment]
It is gone, when i remove ChakraProvider. This is why i confuse about this.
