### ISSUE TITLE
[Input] When type="date" not showing icon and format dd.mm.yyyy on mobile browsers

### ISSUE THREAD

**Issue by denysoleksiienko** [chakra-ui/chakra-ui#7168]
### Description

Not correctly showing the input type **date** on mobile. 
Is there a solution how to fix this?

```
 <Input
   {...register('date', {
     required: 'Required field',
   })}
   id='date'
   max='9999-12-31'
   type='date'
/>
```
![photo_2022-12-26 23 50 56](https://user-images.githubusercontent.com/93124834/209585267-38f7aacf-f91a-46a0-82d0-d734713e12d9.jpeg)

### Chakra UI Version

1.8.8

### Browser

108.0.5359.128

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Please follow the issue template as we're not able to act on issues that are lacking important information.

**Comment by bindalsarthak03** [comment]
@denysoleksiienko  Is it solved?
