### ISSUE TITLE
Chakra CLI and Typescript 

### ISSUE THREAD

**Issue by juliancwirko** [chakra-ui/chakra-ui#7172]
### Description

I want to use strict typing in a couple of places. But the file generated by Chakra UI isn't enough. I created a reproduction repository with a detailed description in the README.md file. I would be very grateful if someone could answer what is wrong with my approach or if some things are not implemented in Chakra UI/CLI yet. Thanks.

Link to the repository: https://github.com/juliancwirko/chakra-typescript-problem

### Link to Reproduction

https://github.com/juliancwirko/chakra-typescript-problem

### Steps to reproduce

1. clone the reproduction repository
2. npm install
3. npm run theme (if needed to make sure that the chakra CLI generates the theming.types.d.ts)
4. see the README.md there for more details and screenshots
5. Modify App.tsx Button component in VS Code to see how the typings work there

### Chakra UI Version

2.4.5

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Strict typings have been implemented into the CLI a few months ago, please check the docs for more information
