### ISSUE TITLE
EditableTextarea need to handle br(or some adapter support to show content)

### ISSUE THREAD

**Issue by kousuke** [chakra-ui/chakra-ui#7174]
### Description

EdiableTextArea can input texts with linefeeds. but when showing the content, it is just one line contents.
It's better to have add BR or some function to show 

### Problem Statement/Justification

Inputing image is here 
![スクリーンショット 2022-12-27 午後6 47 37](https://user-images.githubusercontent.com/596109/209749583-9967f58b-cca2-487f-8f7c-10f166a6b403.png)

Showing content is here
![スクリーンショット 2022-12-27 午後6 47 44](https://user-images.githubusercontent.com/596109/209749612-3cbea00c-51db-40d7-8fe1-2d6cb615cfee.png)

### Proposed Solution or API

some thing we can have same way to input text and to show text

**Comment by anubra266** [comment]
@kousuke The editable text area works just like the native text area

<img width="811" alt="CleanShot 2022-12-29 at 22 03 16@2x" src="https://user-images.githubusercontent.com/30869823/210010912-de656c2b-f215-4a23-a990-a01824992238.png">

**Comment by kousuke** [comment]
I think using dangerouslySetInnerHTML with user input makes lots of security holes. not good idea to me.

**Comment by anubra266** [comment]
@kousuke I only did that to show you that the input preserves the new lines. It's left to you to choose how you want to show it in your UI.

**Comment by ksdme** [comment]
`<EditablePreview whiteSpace="pre-wrap" />` should just work.

**Comment by kousuke** [comment]
great, it should be on doc!
