### ISSUE TITLE
Roadmap - v3.0 🗺

### ISSUE THREAD

**Issue by segunadebayo** [chakra-ui/chakra-ui#7180]
Hi friends,

First, I'd like to thank you all for supporting Chakra UI and using Chakra in your projects to build accessible and delightful applications. It beats my imagination each time to see that a project that started as a "just launch it and see what happens" has now become an essential frontend toolkit helping over 1.5m developers (per month) worldwide.

We recently posted [our roadmap](https://chakra-ui.canny.io/) and made it public here. From this experiment, it was quickly apparent that "more components" and "CSS-in-JS" were crucial topics we needed to address.

Eight months ago, we released [Zag.js](https://zagjs.com/), headless, framework-agnostic components powered by state machines. Even though we started with a "beta" version, we're starting to reach a stable state and are excited to push all interactive components from [Zag.js](https://zagjs.com/) into Chakra UI in v4.

We're excited about the future of Chakra. As we build and get ready for v4 ("takeoff"), we'd like to release a v3 ("runway") which gets us aligned with this new vision. 

### General

- Migrate from Popper.js to Floating UI
- Remove dependency on `framer-motion`: We'll redesign the components to fit any motion library or native css animation.
- Consolidate component packages: We'll consolidate all components into a single `@chakra-ui/react` package, reducing the maintenance and usage complexity.
- Remove legacy (or deprecated) components and utilities
- Built-in emotion cache support in `ChakraProvider`
- Support `defaultProps` in theme for components.
   - Default props must be JSON-serializable (string, number, boolean, null)

### Component Refactoring

- PinInput
	- Switch value to use an array instead of string
- Add support for label
- Checkbox, Radio, Tooltip
	- Use compound component pattern
	- Throw an error when `ref` to trigger can't be found
- Slider, Range Slider
- Add support for label
- Progress
 - Use compound component pattern
- All components
	- Remove the use of descendants package in favor of `id` or `value` provided by the user
- Integrate anatomy into components packages

### Theming and Tokens

- Remove social media colors from the theme
- Update all components to use design tokens.
- Provide more semantic tokens (at the moment, we provide body text, bg, and border). This makes it easier to design color-more compatible UIs faster without having to specify light/dark values every time
- Rename global semantic tokens to use the `global` or `system` prefix instead of `chakra`

### Styled System

- Redesign CLI for better ESM and type generation
- Provide a way to scope the css reset to a dedicated className
- Improve shorthand and longhand declaration merging
- Move text and layer styles to cascade layer (to help improve override)

Regarding CSS-in-JS, we've been in a 10-months long research phase to design our first static solution for Chakra UI. We've made a lot of progress with this, and we're excited to show it in the coming months.

If there's anything else you'd love to see in v3.0 that's not on [the roadmap](https://chakra-ui.canny.io/), feel free to comment below, and we'll consider it as well.

Thanks a lot, and Happy Holidays! 🎉🥳

**Comment by calebpitan** [comment]
>  Throw an error when ref to trigger can be found

I think you mean "Throw an error when ref to trigger can't be found", no?

**Comment by la55u** [comment]
Looks promising! Just one thing that unclear for me: 
> Support defaultProps in theme for components.

How is this different from the existing `defaultProps` solution in components in the current theming system?

**Comment by segunadebayo** [comment]
@la55u, at the moment, only colorScheme, size, and variant are fully supported in `defaultProps`.

**Comment by Brennvo** [comment]
> Remove the use of descendants package in favor of id or value provided by the user

This sounds like it would make migrating to v3 tedious for all components currently dependent on the descendants package. If I'm understanding this correctly, a user migrating to v3 will have to add IDs to all affected components in their project, e.g., an `AccordionItem` or `Tab`?

Alternatively, we could just refactor the `useDescendants` hook to return the passed user ID if it is supplied.

**Comment by amosbastian** [comment]
>Regarding CSS-in-JS, we've been in a 10-months long research phase to design our first static solution for Chakra UI. We've made a lot of progress with this, and we're excited to show it in the coming months.

Biggest thing for me. Glad to see it's being addressed! 🙌

**Comment by asterikx** [comment]
Any chance React server components support will make it into v3? Given Next.js v13 supports SCs, this would be a great addition IMO.

**Comment by ODelibalta** [comment]
I sincerely appreciate the effort that went into this UI. That is why I had no problem supporting it. My biggest issue right now is the lack of support for NextJS when using only the app directory. I've opened a discussion and I have yet to see any replies to it. I know you guys have a lot on your plates but NextJS is one of the if not the most popular framework out there. I'd have thought making sure this UI works with it without any problems would be a higher priority.

**Comment by lcswillems** [comment]
> > Regarding CSS-in-JS, we've been in a 10-months long research phase to design our first static solution for Chakra UI. We've made a lot of progress with this, and we're excited to show it in the coming months.
> 
> Biggest thing for me. Glad to see it's being addressed! raised_hands

What does this mean? Will there still be able to dynamically change style (using JS variables for example) @segunadebayo ?

**Comment by bertho-zero** [comment]
A `@chakra-ui/next` package could help a lot of people with links and images.

`Link` + `next/link`
`LinkOverlay` + `next/link`
`Image` + `next/image`

**Comment by jinsley8** [comment]
> A `@chakra-ui/next` package could help a lot of people with links and images.
> 
> `Link` + `next/link` `LinkOverlay` + `next/link` `Image` + `next/image`

I think that would be unnecessary. It's pretty simple to make those changes right now as-is.

**Comment by bertho-zero** [comment]
> > A `@chakra-ui/next` package could help a lot of people with links and images.
> > `Link` + `next/link` `LinkOverlay` + `next/link` `Image` + `next/image`
> 
> I think that would be unnecessary. It's pretty simple to make those changes right now as-is. I haven't checked the docs recently but maybe a little section on each page to explain the change would suffice.

In theory there is just to wrap the components with the chakra factory, in reality there are overlapping props which force to create a component and there is also typing to write.

I'm using both in a project and it's hell mixing chakra and next for links and images. Lots of devs are using Next and an official way to handle those few hitches would be welcome

**Comment by timkindberg** [comment]
Definitely spooked by all the anti-css-in-js rhetoric happening all over the internet lately. That, paired with the lack of Next.js 13 support due to Emotion being CSS-in-JS, has me second guessing my teams choice in using CSS-in-JS. 

However, we chose Chakra UI for really great reasons. The styling ergonomics, mixed with the set of pre-made and highly theme-able _and accessible_ components were the biggest selling point. Not only was it 1) the way we were going to write CSS, it was also 2) a great starting point for our base components and a template for how to write our own.

To me, it's a choice between:
- Chakra UI (all in one choice)
- Tailwind + Headless UI (or something similar)
- Vanilla Extract w/ Sprinkles + Headless UI (or something similar)

The tradeoff seemed worth it several years ago. But the CSS-in-JS doom is looming. I hope that someone finds a way to mitigate the doom, hopefully your work and research into how to take a static CSS approach will prove successful. We are rooting for you!!

We are still on v1.2.1 🙈 😢 💀

**Comment by bjornhauge** [comment]
I've always wished Chakra would have an additional semantic layer for colors in the way that [Microsoft's Fluent UI](https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/theming-designer/) does. I see here that *something* additional in that direction is planned (not sure how much). I'd just like to throw in my vote that complete-ish coverage would make a lot of sense. For instance, Button, Icon Button, and Menu Item would all use the same set of default, hover, active, and aria-selected background colors, and there would be corresponding semantic token slots that would be very quick to edit once for use everywhere (e.g. replace gray.100 with gray.200 for hover background or something). It would also consolidate the dark/light mode color re-mapping into a single place, which would make both that re-mapping itself easier, and also make the *rest* of the logic currently in the component themes much simpler.

**Comment by bertho-zero** [comment]
One thing I would love would be a set of stories so we can see the theme we're expanding on as a whole. Or a tool that allows you to visualize the impact of our changes on all components.

**Comment by cereallarceny** [comment]
Would love to see support for server components like in the Next 13 app directory. However, [it's my understanding that as long as Chakra relies on runtime-based CSS-in-JS engines like Emotion, that this will never be supported](https://github.com/emotion-js/emotion/issues/2928#issuecomment-1407814901). I'd love to hear from core Chakra contributors how they plan to bridge this gap, if at all. As someone using Chakra in many web applications, but also wanting to take advantage of the benefits of server components, it appears to be a fork in the road.

@segunadebayo Do you and the team have any idea about how Chakra might go about supporting RSC?

**Comment by bfeister** [comment]
Just dropping by to say "Hell yeah, first static solution for Chakra UI!" 

🏅 🚀

**Comment by minhchu** [comment]
Glad to see this roadmap 🎉 
Really want to see the static extraction.
Chakra team has done a lot. Thank you

**Comment by leonard-henriquez** [comment]
> Regarding CSS-in-JS, we've been in a 10-months long research phase to design our first static solution for Chakra UI. We've made a lot of progress with this, and we're excited to show it in the coming months.

Where can we find the discussion/the research regarding this topic ? 
Do you have a rough idea of when this could be released @segunadebayo ?

**Comment by ScottAwesome** [comment]
First off: I thought I recognized you from Zag and the xstate community @segunadebayo ! So Hello :)

Secondly, I too was looking to see if there was any forward movement on the CSS In JS replacement, if you haven't looked already, you may find [Compiled](https://compiledcssinjs.com/) a suitable bridge

**Comment by mikirejf** [comment]
Add support for "in place" breakpoint values like Mantine does it:
![image](https://user-images.githubusercontent.com/8895894/218514640-82f1b6e5-d8e5-4825-8775-306891d3c7b2.png)


Add a similar API to that of the responsive styles to use container queries via style props:
`
<Box w={{800: '100px', 1440: '200px', cq: true}} />
`
It should already automatically watch the parent container under the hood.

**Comment by vitalijalbu** [comment]
We'd like more components, like **Lists**: 
https://framework7.io/docs/list-view
Or **Autocomplete**
https://mantine.dev/core/autocomplete/

**Comment by renatopardini** [comment]
@segunadebayo, is there a release date for react server components and next v13?

**Comment by violabg** [comment]
> Relevant read: https://www.adebayosegun.com/blog/the-future-of-chakra-ui

Very interesting.
@segunadebayo 
Have you considered https://unocss.dev/, it looks promising

**Comment by xlukasfrana** [comment]
> > Relevant read: https://www.adebayosegun.com/blog/the-future-of-chakra-ui
> 
> 
> 
> Very interesting.
> 
> @segunadebayo 
> 
> Have you considered https://unocss.dev/, it looks promising

Awesome tip by the way! UnoCSS is great! 🚀

**Comment by violabg** [comment]
@cschroeter looks good
Any ETA for Panda?

**Comment by mikirejf** [comment]
> @cschroeter looks good
> 
> Any ETA for Panda?

I believe there was no ETA announced anywhere.

There are already blog posts about it tho: https://infinum.com/blog/panda-css-css-in-js-without-runtime-overhead/

**Comment by bertho-zero** [comment]
With Panda I see that there are still object props for responsiveness which causes re-renders with react.

Will a solution be available to extract these objects from the component at compile time?

```jsx
py={{ base: '16', md: '24' }}
```

**Comment by harisvsulaiman** [comment]
> With Panda I see that there are still object props for responsiveness which causes re-renders with react.
> 
> Will a solution be available to extract these objects from the component at compile time?
> 
> ```jsx
> py={{ base: '16', md: '24' }}
> ```

@bertho-zero why does it cause re renders?

**Comment by bertho-zero** [comment]
@harisvsulaiman With each creation of the component a new object is created, the prop is different (`===`) and the react reconciliation makes a superfluous render.

It's explained at the beginning of https://github.com/welldone-software/why-did-you-render

You can see that here: https://codesandbox.io/s/why-did-you-render-sandbox-forked-hetd9k
The fixed version: https://codesandbox.io/s/why-did-you-render-sandbox-forked-ghfl0q?file=/src/index.js:889-1002

In large data-driven components it can quickly become a problem.

**Comment by bhaugeea** [comment]
> @harisvsulaiman With each creation of the component a new object is created, the prop is different (`===`) and the react reconciliation makes a superfluous render.

The component will re-render anyway because its parent re-renders. By default, if any component re-renders then its entire sub-tree re-renders. This is only not true if you memoize a component &mdash; in that case, its props and hooks start to matter. You'll just need to memoize the breakpoints prop using `useMemo` in the parent component, or declare it as a variable outside the component function if it doesn't need to be dynamic.

**Comment by bertho-zero** [comment]
Declaring every style property that is responsive outside of the component or in a useMemo gets cumbersome.

**Comment by mayrsascha** [comment]
Next.js 13.4 just got released. Their App Router is now stable. And more importantly, their App Router is the new default and so are React Server Components. 

Given that one of the most popular React web frameworks uses Server Components as the default, I recommend that the Chakra UI team considers adding support for them to stay relevant.

**Comment by timkindberg** [comment]
> Next.js 13.4 just got released. Their App Router is now stable. And more importantly, their App Router is the new default and so are React Server Components.
> 
> Given that one of the most popular React web frameworks uses Server Components as the default, I recommend that the Chakra UI team considers adding support for them to stay relevant.

They are actively innovating on solutions. See the comment above: https://github.com/chakra-ui/chakra-ui/issues/7180#issuecomment-1508882300

**Comment by mayrsascha** [comment]
@timkindberg Thank you for pointing to that, but it's not yet on their [official roadmap](https://chakra-ui.canny.io/). In fact, it's as of today the most requested feature not yet on their roadmap.

**Comment by cereallarceny** [comment]
> I recommend that the Chakra UI team considers adding support for them to stay relevant.

While I agree that we would all love to RSC be supported in Chakra, there's a more empathetic way to put this. The maintainers of this library, as with many open-source projects don't owe anything to you or anyone else to stick to **your** definition of "relevance".

Furthermore, @segunadebayo has made many attempts here and on his personal blog to recruit people to assist with this problem - which is far bigger than Chakra specifically. Let's try to keep it respectful here - after all, it is free software. 😊

**Comment by mayrsascha** [comment]
@cereallarceny I didn't mean to be disrespectful and I'm sorry if this sounded like I was. I am very grateful for the free open-source software and all the hard work and hours Chakra UI contributors put into this. Many projects, amongst others my own projects, wouldn't be possible without them.

What I meant by staying relevant is that anyone starting a new project with Next.js as of today won't be able to use Chakra UI with their default configuration of using their App Router and RSC. 

This will directly interfere with the popularity of Chakra UI, as Next.js is one of the most popular web frameworks now and in the foreseeable future and has nothing to do with my definition of relevancy, but rather with the market for component/UI libraries. With Next.js 13.4 having RSC as default, it's probably only a matter of time before other frameworks and component/UI libraries hop on the RSC bandwagon in order to compete/be compatible.

Given how long major version upgrades of a big project like Chakra usually take (~ many months) and specifically the technical difficulties of migrating Chakra's CSS-in-JS approach to be compatible with RSC, I don't think it would be wise to hold off on this until v4. Hence my recommendation for the v3 roadmap.

**Comment by Tolu-Mals** [comment]
Hi, great work so far ✨, I love Chakra UI 🚀

Can we have a way to pass in variables to the chakra factory? For dynamic styling

For example, I have a custom button like this:

```tsx
const CustomButton = chakra(Button, {
    baseStyles: { 
        backgroundColor: 'blue'
    }
})
```

If I want the background color to change based on some success variable, it could look like this:

```tsx
const CustomButton = chakra(Button, {
    baseStyles: (success) => { 
        //background should be green when success === true
        backgroundColor: success ? 'green' : 'blue',
    }
})
```

And we could pass it to the Button like this:

```tsx
<CustomButton success={true}>Button Label</CustomButton>
```

**Comment by jonybekov** [comment]
> Hi, great work so far ✨, I love Chakra UI 🚀
> 
> Can we have a way to pass in variables to the chakra factory? For dynamic styling
> 
> For example, I have a custom button like this:
> 
> ```tsx
> const CustomButton = chakra(Button, {
>     baseStyles: { 
>         backgroundColor: 'blue'
>     }
> })
> ```
> 
> If I want the background color to change based on some success variable, it could look like this:
> 
> ```tsx
> const CustomButton = chakra(Button, {
>     baseStyles: (success) => { 
>         //background should be green when success === true
>         backgroundColor: success ? 'green' : 'blue',
>     }
> })
> ```
> 
> And we could pass it to the Button like this:
> 
> ```tsx
> <CustomButton success={true}>Button Label</CustomButton>
> ```

Why overcomplicate things if you can just do it in normal way?

```typescript
const ChakraButton = chakra(Button);

const CustomButton = ({ success} ) => {
   return <ChakraButton backgroundColor={success ? 'green' : 'blue'} />
}
```

And the use it:
```
<CustomButton success />
```

**Comment by Tolu-Mals** [comment]
> @Tolu-Mals 
> 
> 
> 
> Why overcomplicate things if you can just do it in normal React-ish way?
> 
> 
> 
> ```typescript
> 
> const ChakraButton = chakra(Button);
> 
> 
> 
> const CustomButton = ({ success }) => {
> 
>    return <ChakraButton backgroundColor={success ? 'green' : 'blue'} />
> 
> }
> 
> ```
> 
> 
> 
> And the use it:
> 
> ```typescript
> 
> <CustomButton success />
> 
> ```

It's true that I could do it the way you described. But I like to separate my styles when there are a lot of them, sometimes I put them in a separate 'styles.ts' file and then export all the chakra created components. It helps with making the components readable, especially when the chakra factory created peices are named well.
