### ISSUE TITLE
chakra components are unstyled when theme is passed to provider

### ISSUE THREAD

**Issue by calebpitan** [chakra-ui/chakra-ui#7181]
### Description

When I pass in a custom extended theme to the chakra provider all the components are unstyled. 
The moment the theme is removed everything is normal and even when re-added.

### Link to Reproduction

https://codesandbox.io/p/sandbox/fancy-dust-n4m0zj

### Steps to reproduce

1. On initial load styles break and components are unstyled
2. Go to `_app.tsx`
3. Change theme prop to undefined and save
4. Styles show up correctly
5. Change theme prop back to its original value `theme={theme}`
6. Styles show up correctly
7. Reload the embedded iframe that renders the app in the codesandbox
8. Styles break and components become unstyled again

### Chakra UI Version

2.4.6

### Browser

Google Chrome 108.0.5359.124 (Official Build) (arm64) 

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

When theme is added to chakra provider
![image](https://user-images.githubusercontent.com/36812893/210036334-6adeaba9-d59d-44f6-a01e-d98372b5ae9c.png)

when theme is removed from chakra provider and/or added back without reloading

![image](https://user-images.githubusercontent.com/36812893/210036277-0613a512-aae5-495b-bca6-2760d6d48e30.png)

**Comment by TylerAPfledderer** [comment]
Hey @calebpitan!

It appears that you are using `extendBaseTheme`, but using the `ChakraProvider`

I think you meant to use `extendTheme`

`extendBaseTheme` is to be used in conjunction with `ChakraBaseProvider` if you wanted to manually import default component themes as needed.

**Comment by calebpitan** [comment]
Oh my! 

Thanks @TylerAPfledderer.

I've spent hours on this before finally filing an issue and it would have taken just a second to notice that, but sadly, I didn't.

**Comment by TylerAPfledderer** [comment]
It's quite alright. Glad to be of service! 🤘
