### ISSUE TITLE
App breaks in production with ChakraUI + React Table

### ISSUE THREAD

**Issue by st3fus** [chakra-ui/chakra-ui#7182]
### Description

So basically, my app crashes and displays these errors while in production. Locally, the app works fine, the moment it's deployed it shows this error. The main dependecy that breaks is react table along with Chakra UI.

### Link to Reproduction

None

### Steps to reproduce

None

### Chakra UI Version

2.4.6

### Browser

Google Chrome 107.0.5304.110

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Screenshot of the error:
![image](https://user-images.githubusercontent.com/112018215/210087542-0e5c6326-cbc3-4acd-87d5-7e69ac8babfb.png)

![image](https://user-images.githubusercontent.com/112018215/210087637-b15c0a2f-904b-41e1-9896-637d8bcf4990.png)

This only happens in production, locally, the app works just fine. I can't share complete code in sandbox since I got a NDA signed that's also related to this code. I could give some parts of it with prior agreement of my superiors. But yeah, this started to happen recently, 2-3 days ago. I even tried bunch of other versions of chakra and other dependencies but no luck.

Also, a screenshot of my package.json:
![image](https://user-images.githubusercontent.com/112018215/210087790-e0c1d46d-8974-487d-ad45-697dd768ce4b.png)

**Comment by st3fus** [comment]
@segunadebayo Sorry for tagging you, but I think this is probably related to previous issues you closed after releasing 2.4.6, you did note if it continues happening to open a new issue. Thank you for your time, everyone.

**Comment by segunadebayo** [comment]
Hi @st3fus, can you create a minimal reproduction of this issue?

It's tough to help without a reproduction, from the looks of this, you might need to the following in your `next.config.js`:
- Set `esmExternals` to `false`
- Set `swcMinify` to `false`

**Comment by st3fus** [comment]
Greetings @segunadebayo, thank you for a swift response and solution. Seems like setting those two settings to false resolved our issue for now, I just hope disabling those two wont cause any problems in the future, fingers crossed. You can mark this as closed, thank you once more.
