### ISSUE TITLE
Unable to overwrite base style for Card component

### ISSUE THREAD

**Issue by boonyeow** [chakra-ui/chakra-ui#7183]
### Description

Expected base style for Card component to be overwritten however, there's some inconsistencies-- i.e. works for `bg` and `fontWeight`, but not for `borderRadius` and `shadow`. 

Please see commented lines: [https://codesandbox.io/s/elastic-varahamihira-uhz824?file=/src/theme.js](https://codesandbox.io/s/elastic-varahamihira-uhz824?file=/src/theme.js)

### Link to Reproduction

https://codesandbox.io/s/elastic-varahamihira-uhz824?file=/src/theme.js

### Chakra UI Version

2.4.6

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Good catch @boonyeow.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
