### ISSUE TITLE
Ability to set the "as" attribute from a variant

### ISSUE THREAD

**Issue by Southclaws** [chakra-ui/chakra-ui#7189]
### Description

Hey! Lover of Chakra here, huge respect for this project ♥️

So I've always wondered why there's only a Heading component, I get that you can set the "as" attribute for h1, h2, h3, etc... but styling this seems awkward unless I'm missing something.

Essentially, what I'd like to do is:

```tsx
<Heading variant="h1">
<Heading variant="h2">
<Heading variant="h3">
<Heading variant="h4">
<Heading variant="h5">
```

And automatically make the variant set my styles and the `as` attribute to the respective header level.

I've tried this in the theme:

```tsx
  variants: {
    h1: { fontSize: "2xl", as: "h1" },
    h2: { fontSize: "xl", as: "h2" },
    h3: { fontSize: "lg", as: "h3" },
    h4: { fontSize: "md", as: "h4" },
    h5: { fontSize: "sm", as: "h5" },
    h6: { fontSize: "sm", as: "h6" },
  },
```

But the resulting HTML shows each heading as a `h2`.

For now I can just write this:

```tsx
<Heading as="h1" variant="h1">
<Heading as="h2" variant="h2">
<Heading as="h3" variant="h3">
<Heading as="h4" variant="h4">
<Heading as="h5" variant="h5">
```

Which is fine but I can imagine forgetting to add this repetition from time to time.

---

What I think is going on here is that Chakra's theming allows changing styles only, but not changing the underlying element type. If this is the case, this totally makes sense and I can imagine there may be some complexity in allowing themes to change the resulting element type.

So I'm wondering if there's a way I can drive the styles from the `as` prop instead of a variant.

Anyway, thanks!

### Problem Statement/Justification

It would make semantic heading levels easier to style and use.

### Proposed Solution or API

Allow themes to set `as` or allow themes to derive styles from `as`.

### Alternatives

My alternative is quite simple, just create my own custom components <Heading1>, <Heading2> etc... which I'm quite happy to do!

**Comment by segunadebayo** [comment]
Hi @Southclaws,

I'd rather have you use the alternative solution you proposed. At the moment, there's no easy way to add support for this without increasing the system's complexity.

Thanks for understanding.

**Comment by Southclaws** [comment]
I completely understand, makes sense, thanks for confirming!
