### ISSUE TITLE
Box as Iframe create issue with typescript

### ISSUE THREAD

**Issue by jitenderchand** [chakra-ui/chakra-ui#719]
**Describe the bug**
I am using <Box> as Iframe but when I pass `src` it gives typescript error

<img width="1438" alt="Screen Shot 2020-05-15 at 8 13 58 PM" src="https://user-images.githubusercontent.com/2376596/82063426-1578b500-96e9-11ea-92eb-562fe3c6709a.png">

**Desktop (please complete the following information):**
 - Version 0.7.0

**Comment by segunadebayo** [comment]
Hi @jitenderchand,

We're aware of this and it's a duplicate in #205. I'll close this out for now as we've solved this in preparation for the next release.

Thanks
