### ISSUE TITLE
`loading` attribute of component `Image` or `Avatar` doesn't work

### ISSUE THREAD

**Issue by KKzLEO** [chakra-ui/chakra-ui#7192]
### Description

I want to add `loading` attr for `Avatar` component to have `lazy-loading` function, but it doesn't work well because the `loading` attribute doesn't be passed to `use-image` hook so it still loaded each image in the first time instead of scrolling

at line 34 of  `avatar-image.tsx`
![image](https://user-images.githubusercontent.com/26006239/210623711-f7e1f06c-3abc-4ce5-bded-b3a2163c5c0b.png)

### Link to Reproduction

https://codesandbox.io/s/dark-wind-xc0t2m?file=/src/index.js

### Steps to reproduce

1. Open dev tool and go to `Network` tab
2. Filter with `image`
3. Go to sandbox
4. Comment and uncomment `Success` or `Failure` example and see the differences (Remember refresh the whole page cuz cache)
5. You can see the `lazyloading` function of original img tag works well but `Image` or `Avatar` doesn't. 

### Chakra UI Version

3.2.1

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
For this case, please use the `Img` component and pass the `loading` attribute to it instead.

```jsx
<Img loading="lazy" rounded="full" />
```

**Comment by KKzLEO** [comment]
@segunadebayo  it's still not working even using `Img` component instead.
![image](https://user-images.githubusercontent.com/26006239/212683636-6d96ee90-8c1c-450c-a666-3297644f9263.png)

**Comment by KKzLEO** [comment]
@segunadebayo could you reopen this issue?

**Comment by ali-garajian** [comment]
I have the same issue. Apparently the problem is that the order of the properties matters. i.e.

`<img loading='lazy' src='...' />` -> works
`<img src='...'  loading='lazy' />` -> doesn't work
