### ISSUE TITLE
Checkbox animates initial state

### ISSUE THREAD

**Issue by vadimdemedes** [chakra-ui/chakra-ui#7193]
### Description

When `Checkbox` is rendered with `isChecked={true}` set right away, it still performs an animation for drawing a check mark inside of it, as if user interacted with that checkbox. I think if checkbox is immediately rendered with `isChecked={true}`, there should be no animation.

P.S. Thanks for a great project!

### Link to Reproduction

https://codesandbox.io/s/cocky-https-4hii19?file=/src/App.js

### Steps to reproduce

1. Click "Toggle checkbox visibility" button
2. Checkbox isn't rendered
3. Click the same button again
4. Checkbox is now rendered, but there's an animation for drawing a check mark

### Chakra UI Version

2.4.6

### Browser

Google Chrome 108

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

In Framer Motion this is solved by setting `initial={false}` to avoid animations on initial render. See https://www.framer.com/docs/animate-presence/##suppressing-initial-animations.

**Comment by szpytfire** [comment]
+1. Having issues in Snapshot tests because of this! This isn't limited to MacOS // Google Chrome; happens on all browsers.

Any chance of this behaviour being reviewed?

**Comment by selrond** [comment]
This is especially problematic when using some kind of virtualization like https://github.com/bvaughn/react-window, which utilizes render props pattern, recreating checkbox components on each render:

https://user-images.githubusercontent.com/6603389/230128154-c1d1fe4c-8daa-462d-a1d6-02bd42f74e5a.mp4

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by selrond** [comment]
For the reference: https://github.com/chakra-ui/chakra-ui/commit/24f952da27ef43febbe20714a08eb94ce87133eb
