### ISSUE TITLE
Accordion not opening sometimes in a Playwright test

### ISSUE THREAD

**Issue by baptisteArno** [chakra-ui/chakra-ui#7199]
### Description

When I test a component with an Accordion using Playwright, sometimes, the accordion simply doesn't open. It's just inconsistent.

[video.webm](https://user-images.githubusercontent.com/16015833/211023147-61611f56-ec04-4490-8d24-b6b236b580fe.webm)

The arrow is animating, but the `AccordionPanel` isn't showing.

### Link to Reproduction

Can't reproduce in sandbox 😕

### Steps to reproduce

Here is the Playwright command that fails:

```ts
await page.getByRole('button', { name: 'Set user details' }).click()
```

### Chakra UI Version

2.4.6

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @baptisteArno.

This might be related to framer motion. Could you upgrade to the latest version of framer-motion to see if the issue goes away?

I can't think of a way to fix this on our end.
