### ISSUE TITLE
useBreakpoint hook Cannot read property 'details' of undefined when run unit test with Jest

### ISSUE THREAD

**Issue by tqdung** [chakra-ui/chakra-ui#7201]
### Description

I'm setup unit test for my project. I'm using Chakra-ui (ver 2).

But when run unit test (Jest) it was failed with an error "Can not read property details of undefined".
When I'm researching I know it's faill because useBreakpoint use "window" object that is not available (some functions) on node environment.

I also try to manual mock for window/document object, but seem not make sense

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/37869666/211151662-ae15fb8e-a542-445a-8d79-dd56a1836421.png">

### Link to Reproduction

https://codesandbox.io/s/dazzling-julien-qo7hc5?file=/src/components/Text/Text.tsx:106-121

### Chakra UI Version

2.4.4

### Operating System

- [X] macOS

**Comment by segunadebayo** [comment]
This error occurs when you don't wrap your application within `ChakraProvider` before running the test.

```js
 render(
    <ChakraProvider>
      <Text>Default Text</Text>
    </ChakraProvider>
  );
```

To mock the window or document, check the setup test we have here:

https://github.com/chakra-ui/chakra-ui/blob/496ebaedd489a05c19c31c946b872757e4f338d4/scripts/setup-test.ts#L24

**Comment by kamatheuska** [comment]
I used the setup @segunadebayo  proposed [on this issue](https://github.com/chakra-ui/chakra-ui/issues/7201#issuecomment-1380575780), mocking `matchMedia`. I am using Vitest though.

This is my current setup file
```ts
// eslint-disable-next-line no-undef
globalThis.IS_REACT_ACT_ENVIRONMENT = true;

if (typeof window.matchMedia !== 'function') {
  Object.defineProperty(window, 'matchMedia', {
    enumerable: true,
    configurable: true,
    writable: true,
    value: vi.fn().mockImplementation((query) => ({
      matches: false,
      media: query,
      onchange: null,
      addListener: vi.fn(), // Deprecated
      removeListener: vi.fn(), // Deprecated
      addEventListener: vi.fn(),
      removeEventListener: vi.fn(),
      dispatchEvent: vi.fn(),
    })),
  });
}
```


I am getting this error:

```
TypeError: env.window.matchMedia is not a function
 ❯ node_modules/.pnpm/@chakra-ui+media-query@3.2.0_zqvnne7mlmz4vg4qwr7iekv2na/node_modules/@chakra-ui/media-query/dist/chakra-ui-media-query.cjs.dev.js:84:29
```

Seems to me that ` reactEnv.useEnvironment()` is returning an undefined value for `env.window.matchMedia` on a second call to the function.

**Comment by jhujhul** [comment]
I had exactly the same issue.

I ended up fixing it by mocking `useBreakpoint` and `useBreakpointValue` which are calling `matchMedia`. 

```ts
vi.mock('@chakra-ui/react', async () => {
  const module = (await vi.importActual('@chakra-ui/react')) as object;

  return {
    ...module,
    useBreakpoint: vi.fn(),
    useBreakpointValue: vi.fn(),
  };
});
```

**Comment by bobba76** [comment]
This one fixed the issue for me. 

I had first: **useBreakpoint hook Cannot read property 'details' of undefined when run unit test with Jest**
Then I got: **TypeError: env.window.matchMedia is not a function**

setupTests.ts

`global.matchMedia = global.matchMedia || function () {
  return {
    matches: false,
    addListener: jest.fn(),
    removeListener: jest.fn(),
  };
};`

More here [21096](https://github.com/ant-design/ant-design/issues/21096#issuecomment-725301551)
