### ISSUE TITLE
Chakra-ui dose not support next js 13 app directory yet ?

### ISSUE THREAD

**Issue by anhdd-kuro** [chakra-ui/chakra-ui#7209]
### Description

My demo repo
https://github.com/anhdd-kuro/next13-strapi-chakraui-demo/tree/main/client

I have the same code in `pages/test.tsx` and `app/page.tsx` + `app/layout.tsx`
There is no problem with `pages/test.tsx`
This is css that rendered when access to app/page.tsx 
_( already have "use client" at top and there is no console error )_ 

```css
max-width: sm;
border-width: 1px;
border-radius: lg;
```

The unit like "lg" "sm" does not transform to rem, others like "flexBasis" "gap" still working
Am I forgot any else config ?

### Link to Reproduction

https://github.com/anhdd-kuro/next13-strapi-chakraui-demo/tree/main/client

### Steps to reproduce

- run yarn at both client and sever
- run `yarn dev` at client and `yarn develop` at server
- access to `http://localhost:1337/admin` then create a post or just hardcode posts in client with this json response

```json
{"data":[{"id":1,"attributes":{"title":"post 1","content":"post 1 content","createdAt":"2023-01-05T05:40:05.287Z","updatedAt":"2023-01-06T02:46:10.754Z","publishedAt":"2023-01-05T05:41:54.896Z"}},{"id":2,"attributes":{"title":"post 2","content":"post 2 contentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontent","createdAt":"2023-01-05T05:42:30.309Z","updatedAt":"2023-01-06T02:46:16.530Z","publishedAt":"2023-01-05T05:44:25.585Z"}}],"meta":{"pagination":{"page":1,"pageSize":25,"pageCount":1,"total":2}}}
```

result in `app/page.tsx`
![スクリーンショット 2023-01-09 13 03 29](https://user-images.githubusercontent.com/13819766/211239416-6a454f36-3978-445b-8266-3aad4cd0a27a.png)

result in `pages/test.tsx`
![スクリーンショット 2023-01-09 13 03 43](https://user-images.githubusercontent.com/13819766/211239385-206e03c4-2099-4e8f-b4b0-ebca07e4de70.png)

### Chakra UI Version

2.4.6

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Distortedlogic** [comment]
bump

**Comment by mafirat** [comment]
**_I guess_**, you need to use `ChakraProvider` in layout component under `app` directory. Because Chakra is a context based UI library. 

In your case your `layout.tsx` file should be something like this:

```js
<html>
  <head />
  <body>
      <ChakraProvider>
      // other things
      {children}
      </ChakraProvider>
  </body>
</html>
```

And it works under `pages` director because you wrap the whole application with `<ChakraProvider>....</ChakraProvider>` already.

**Comment by meera** [comment]
Make sure you add "use client" in layout.tsx.  Like this. 

`"use client";

import { ChakraProvider } from "@chakra-ui/react";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
    
      <head />

      <body>
        <ChakraProvider> {children} </ChakraProvider>
      </body>
    </html>
  );
}
`

**Comment by geisterfurz007** [comment]
@meera using `"use client"` is not allowed on the root layout:

> The root layout is a [Server Component](https://beta.nextjs.org/docs/rendering/server-and-client-components) by default and can not be set to a [Client Component](https://beta.nextjs.org/docs/rendering/server-and-client-components#client-components).

From https://beta.nextjs.org/docs/routing/pages-and-layouts#root-layout-required

**Comment by Distortedlogic** [comment]
additionally, making root layout a client component would make everything a client component which defeats the purpose

**Comment by vivekinfinity** [comment]
@Distortedlogic then where will you put?

**Comment by Pherwerz** [comment]
@vivekinfinity i don't think chakra-ui is optimized for the new app dir

**Comment by Pherwerz** [comment]
like @Distortedlogic  said a lot of nextjs benefits will be lost with that "use client" line. i'll just rather do a creat react app instead

**Comment by Distortedlogic** [comment]
U can still use SSR with pages dir

**Comment by Pherwerz** [comment]
That also defeats the purpose of the appdir

**Comment by Distortedlogic** [comment]
@Pherwerz yes, chakra does not yet support appdir. This is stated in the docs

**Comment by segunadebayo** [comment]
Yes, Chakra does not work in the app directory without the `use client` directive. You can't use state and context in a server component. That makes it challenging to build support for RSC into every component.

Chakra works in the pages directory, though.

**Comment by arclogos132** [comment]
When will this be supported?

**Comment by subalee** [comment]
@segunadebayo Understandable, is there a plan to implement this at some point in the future? Thanks for Chakra!

**Comment by tushar-singh** [comment]
For anyone still struggling with `ChakraProvider` you need to put the provider in a client component, then wrap your layout children inside it.

ClientProvider.jsx (client component)
```jsx
'use client';

import { ChakraProvider } from '@chakra-ui/provider';

export default function ClientProvider({ children }) {
    return <ChakraProvider>{children}</ChakraProvider>
}
```

layout.tsx (server component)
```jsx
import ClientProvider from './ClientProvider';

export default async function MyLayout({ children }) {
    return <ClientProvider>{children}</ClientProvider>
}
```

This allows your client components to use Context without breaking server components. See: https://beta.nextjs.org/docs/rendering/fundamentals#component-level-client-and-server-rendering

**Comment by TimRuiterkamp1** [comment]
If you want to prevent your layout from being transformed to client side as a whole, you can add `/** @jsxImportSource react */` to the top of your layouts. This will remove the createContextx issue you might find when trying to get chakra working with the App directory.
