### ISSUE TITLE
[Input] width types are incorrect

### ISSUE THREAD

**Issue by dannytatom** [chakra-ui/chakra-ui#721]
**Describe the bug**

The `width` prop has the type of:

```
width?: string | number | ((string | number | null)[] & string) | ((string | number | null)[] & number) | ({
    [x: string]: string | number | undefined;
    [x: number]: string | number | undefined;
} & string) | ({
    ...;
} & number) | undefined
```

This means you get a TS error when trying to do `width={[0.5, 100]}`.

**Expected Behavior**

It should just be `(string | number | null)[]`, not `((string | number | null)[] & string)` (and the one after shouldn't exist?), I would think.

**To Reproduce**

https://codesandbox.io/s/react-typescript-h37hn?file=/src/index.tsx

**Suggested solution(s)**

Not sure. I tried finding it myself, but not really clear where this is defined.

**Comment by with-heart** [comment]
Hi @dannytatom! We're very close to releasing 1.0 which is a complete rewrite of Chakra to be 100% native TypeScript. That rewrite resolves a lot of typing issues that exists throughout previous Chakra versions. You can see more information here: https://next.chakra-ui.com/

I'm going to close this issue, as this should no longer be an issue in 1.0.
