### ISSUE TITLE
TypeScript: property position does not support !important

### ISSUE THREAD

**Issue by bertho-zero** [chakra-ui/chakra-ui#7211]
### Description

Type of the property `position` does not support `!important`

### Link to Reproduction

https://codesandbox.io/s/immutable-bush-xe5lve?file=/src/index.tsx

### Steps to reproduce

1. Show code to see the TS error

### Chakra UI Version

2.4.6

### Browser

Brave 1.46.144

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

![image](https://user-images.githubusercontent.com/8525267/211346011-e4516baf-371b-4c7f-b015-01bfce6aba5f.png)

**Comment by dreamid27** [comment]
The first question is why you need !important in position ?

**Comment by bertho-zero** [comment]
Because `next/image` adds a `position: absolute` via Image's style prop and I need to unset it.

```jsx
pos="unset!important"
```

**Comment by segunadebayo** [comment]
I'm pretty reluctant to support this. It seems you're using the `strict` option that only allows specified values.

I'd recommend either switching to the loose version or using the `sx` prop to solve this.

For next/image, I'd recommend setting `position: relative` on a wrapping element to resolve this problem.

**Comment by bertho-zero** [comment]
I don't see what strict/loose you are talking about?

I understand there is a better solution for this specific problem but why wouldn't the `!important` keyword be allowed for all attributes? Wouldn't that be too opinionated for a lib like chakra?
