### ISSUE TITLE
Draggable scroll doesn't work inside <AccordionItem />

### ISSUE THREAD

**Issue by AllanAbucarub** [chakra-ui/chakra-ui#7215]
### Description

When I turn on emulation of device in Desktop Chrome and I have a scroll inside of a <AccordionItem />, it simply doesn't work.

To scroll I have to click exactly on the scrollbar and then drag.

if I remove the div with the scroll from the AccordionItem component, it works properly.

### Link to Reproduction

https://chakra-ui.com/docs/components/accordion/usage

### Steps to reproduce

1. Create a div with scroll inside a AccordionItem component.
2. Turn on device emulation on Chrome Desktop
3. Try to scroll by dragging

### Chakra UI Version

2.4.6

### Browser

Google Chrome

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

https://user-images.githubusercontent.com/69906491/211876614-3666329a-a5fa-4247-81c0-ecbb52216cf3.mp4

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Please provide a reproduction link
