### ISSUE TITLE
useDimensions: Ref is cached on mount only

### ISSUE THREAD

**Issue by jarstelfox** [chakra-ui/chakra-ui#7218]
### Description

I have a case where I am looking to detect a collision and swap to a more compact view. Although I can easily measure the left and right and detect the collision. The problem then becomes that the dimension hook is broken on the smaller element. For clarity, see the code sandbox.

Expected Behavior:

It is possible to measure the smaller view (blue in the example).

### Link to Reproduction

https://codesandbox.io/s/exciting-johnson-jpvx8n?file=/src/index.js

### Steps to reproduce

Valid:
1. Load the Sandbox
2. Drag the window until the red and green collide
3. Note that the collision state is true
4. Note that both the red and green boxes can be measured

Bug:
1. Load the Sandbox
2. Check the `showBlue` switch
3. Drag the window until the blue and green collide
4. Note that both the blue box _can not_ be measured.
 5. Note that the collision state is null due to the lack of measurements

### Chakra UI Version

2.4.6

### Browser

Google Chrome 108

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

I believe this is the actual line that causes the issue: https://github.com/chakra-ui/chakra-ui/blob/main/packages/legacy/hooks/src/use-dimensions.ts#L27

The blame went back to: https://github.com/chakra-ui/chakra-ui/commit/43bd32bb5263fd22ea95e31ecb3ff9e32c6cd8c5

Unfortunately, no additional context was given there.

My understanding of the problem:
[This closure](https://github.com/chakra-ui/chakra-ui/blob/ddbb1b4c49b8f124c0368929357e2891265a50c0/packages/legacy/hooks/src/use-dimensions.ts#L29-L39) is wrapping up the ref.current at mounting time. We then add global resize listeners with the closed-over variable from mounting time. 

The code behaved as expected if I closed over ref and so we can access the mutable ref.current at every event.

**Comment by segunadebayo** [comment]
Good catch and hint @jarstelfox.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
