### ISSUE TITLE
Drawer focus trap breaks Chrome Extension for developers

### ISSUE THREAD

**Issue by ErwinAI** [chakra-ui/chakra-ui#7219]
### Description

Hello there!

I've received a bug report that the chrome extension I'm building (Tailscan) is not able to add Tailwind classes to elements inside the Drawer component. I've replicated the issue on the documentation page and also read that the focus is trapped inside the Drawer component while it's open (https://chakra-ui.com/docs/components/drawer/usage#accessibility). The chrome extension itself runs outside the <body> tag in a separate Shadow DOM, for context.

Is there a way/chance to make this focus trap less invasive? I'm not too familiar with the intricate workings of the Drawer component so I'm not sure about the props `lockFocusAcrossFrames` or `trapFocus`, but it would make sense to me, at least to some degree, to set trapFocus to false in dev mode? This can be done manually but that's not ideal, as it would mean code has to be changed to unlock my (or any) chrome extension inspection tool to work properly.

### Link to Reproduction

https://chakra-ui.com/docs/components/drawer

### Chakra UI Version

Most recent

### Browser

Most recent

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Our focus trap is powered by [React Focus Lock](https://www.npmjs.com/package/react-focus-lock), and there's not much we can do to make it less invasive.

I'd recommend not using the Drawer component (or turning off focus trap) and making a custom one that leverages the focus lock package will custom focus logic (you can check the react-focus-lock package)
