### ISSUE TITLE
How Comes Menulist is blurry on open?? 

### ISSUE THREAD

**Issue by maxwaiyaki** [chakra-ui/chakra-ui#722]
**Describe the bug**
Blurry MenuList

**Expected Behavior**
MenuList should be blurry

**To Reproduce**
Open the example MenuList on the docs

**Desktop (please complete the following information):**
 - OS: [Windows 10 ]
 - Browser [chrome and firefox]

**Comment by segunadebayo** [comment]
Hi @maxwaiyaki, this issue isn't clear to me.

Can you explain a bit more? If you can show a Codesandbox as well, that would be better.

**Comment by maxwaiyaki** [comment]
I'm not sure whether this is just a subjective performance case on my side but, popovers (which constitute the Menu Component, specifically the MunuList) seem to be blurred when open. Tooltips are also showing the same behavior. 

This behavior is replicable by opening any examples of the [Menu ](https://chakra-ui.com/menu), [Popover](https://chakra-ui.com/popover) and [Tooltip](https://chakra-ui.com/tooltip) examples in the Chakra UI Docs.

**Menu List**
![Annotation 2020-05-16 144302](https://user-images.githubusercontent.com/28390298/82119100-6689b700-9784-11ea-8b1e-ebbe6e793fc6.png)

**Popover
![Annotation 2020-05-16 144350](https://user-images.githubusercontent.com/28390298/82119113-8b7e2a00-9784-11ea-9b6a-e12e4ee9483c.png)
**

**Comment by maxwaiyaki** [comment]
I have been able to fix the  problem seems to be solved by passing the following props to `<Menu />`

``` js
modifiers={{
  computeStyle: {
    gpuAcceleration: false
  }
}}
```
**Reactstrap Solution** https://github.com/reactstrap/reactstrap/issues/1303#issuecomment-512035401

**Comment by segunadebayo** [comment]
That's really weird.

Thank you for taking the time to find a solution.

**Comment by quangogster** [comment]
> I have been able to fix the problem by passing the following props to `<MenuList />`, `Tooltip />` and `<PopoverContent />`
> 
> ```js
> modifiers={{
>   computeStyle: {
>     gpuAcceleration: false
>   }
> }}
> ```
> 
> **Reactstrap Solution** [reactstrap/reactstrap#1303 (comment)](https://github.com/reactstrap/reactstrap/issues/1303#issuecomment-512035401)

i love you
