### ISSUE TITLE
Dark theme as default, makes transparent iframes have white background-color. 

### ISSUE THREAD

**Issue by orjank11** [chakra-ui/chakra-ui#7220]
### Description

When I upgraded from Chakra-1.8* to Chakra-2** (dark theme as default application), I expected iframes (we're using hubspot chat) to be transparent in the background 

But instead background-color seems to have a white color instead.

### Link to Reproduction

https://codesandbox.io/s/chakra-2-4-6-iframe-bug-example-srgpqx?file=/src/index.tsx

### Steps to reproduce

1. Go to CodeSandbox Url.
2. The bug will appear.
3. Change "dark" to "light"
4. The bug will disappear.

### Chakra UI Version

2.4.6

### Browser

Google Chrome 108.0.5359.124, Safari 16.1 (18614.2.9.1.12)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Current fix is: 
document.getElementsByTagName("html")[0].style = ""; // remove color-scheme: dark injection on the html tag.

**Comment by segunadebayo** [comment]
Hi @orjank11,

To fix this, you can set `color-scheme: auto` on the iframe styles.

**Comment by orjank11** [comment]
Thank you for responding.

So, I am not sure if that is a good enough solution to close the issue, thou I agree with you it is a better solution than the solution I suggested. 

Most of Iframes are not directly set inside of the react project, but a script file from hubspot in the html file. This will result in us have to find the iframe in code, and from there inject the style properties. leading to a bad developer experience.

**Comment by orjank11** [comment]
Never mind, I was thinking as a property on the element, I guess it's way easier just adding it directly in css. 

aka 

iframe {
  color-scheme: auto
}
