### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'gray' in undefined

### ISSUE THREAD

**Issue by ivanjeremic** [chakra-ui/chakra-ui#723]
I think there is a bug with the chakra typing, can anyone help to resolve this issue? This is what I get when using Chakra in a Create-React-App Typescript.

`useVariantColorWarning`
`/node_modules/@chakra-ui/core/dist/es/utils/index.js:113`
```
  110 | var variantColorIsDefined = variantColor != null;
  111 | 
  112 | if (variantColorIsDefined) {
> 113 |   var variantColorExists = variantColor in theme.colors; // If variant color exists in theme object
      | ^  114 | 
  115 |   if (!variantColorExists) {
  116 |     console.warn("You passed an invalid variantColor to the " + label + " Component. Variant color values must be a color key in the theme object that has '100' - '900' color values. Check http://chakra-ui.com/theme#colors to see possible values");
```
`/node_modules/@chakra-ui/core/dist/es/Button/index.js:62`
```
  59 | 
  60 | // Wrong usage of `variantColor` prop is quite common
  61 | // Let's add a warning hook that validates the passed variantColor
> 62 | useVariantColorWarning("Button", variantColor);
     | ^  63 | var buttonStyleProps = useButtonStyle({
  64 |   color: variantColor,
  65 |   variant: variant,
```
``

**Comment by segunadebayo** [comment]
Hi @ivanjeremic,

This error shows up when you don't wrap your `App` with `ThemeProvider` from Chakra.

Here's what you need to do:

```jsx
// import the provider
import { ThemeProvider, CSSReset } from '@chakra-ui/core'

// in your index.tsx, add this

<ThemeProvider>
   <CSSReset />
   <App/>
</ThemeProvider>
```

**Comment by absolutelysimon** [comment]
Perhaps the "Getting Started" documentation should specify that <ThemeProvider> must be the outermost component?

**Comment by balibebas** [comment]
I feel the docs are pretty clear about wrapping in a provider. For unit testing you'd do something like this to test your components:

```tsx
describe("Navigation", () => {
  it("renders correctly", () => {
    const tree = renderer
      .create(
        <ThemeProvider>
          <Navigation siteTitle="Default Starter" />
        </ThemeProvider>,
      )
      .toJSON();
    expect(tree).toMatchSnapshot();
  });
});
```

**Comment by kennyOlakunle** [comment]
I had issues before but Wrapping ThemeProvider around my app did the trick.

**Comment by talentlessguy** [comment]
Still happens: https://codesandbox.io/s/zen-lamport-3qcgz?file=/pages/_app.tsx

**Comment by with-heart** [comment]
@talentlessguy I don't think any of those errors were related to Chakra. See https://codesandbox.io/s/dank-meadow-f7hkx?file=/pages/_app.tsx

The first issue was that a `.ts` file can't have `jsx` in it, so renaming `theme.ts` to `theme.tsx` fixed that issue. 

The other issue was that you were using `import 'styles/global.css'` which doesn't exist. Switching that `import '../style.css'` seems to work.

The app is running for me after making those changes!

**Comment by talentlessguy** [comment]
@with-heart ohhh my bad... yesterday was in a rush and didn't see these problems

thx for pointing out

**Comment by with-heart** [comment]
@talentlessguy It's all good! Glad it's working for you!

**Comment by rvisio** [comment]
Just ran into this on chakra-ui/react 1.7.2
