### ISSUE TITLE
Module not found: Error: Can't resolve 'css-box-model' in '/vercel/path0/node_modules/@chakra-ui/utils/dist'

### ISSUE THREAD

**Issue by Ian-Balijawa** [chakra-ui/chakra-ui#7231]
### Description

I encountered this error at build time. This happened both in dev and prod.
Below is the error while deploying.

Below is a screenshot
https://user-images.githubusercontent.com/49788350/212297406-2e7d7ca9-b013-412d-94fc-7f46bdd5c8a1.png

Couldn't find a solution anywhere so I came here.
Any help will be appreciated...

### Link to Reproduction

https://github.com/Ian-Balijawa/miingo.git

### Steps to reproduce

1. Clone the code at https://github.com/Ian-Balijawa/miingo.git
2. RUN npm i or yarn
3. RUN npm build  or yarn build
4. See error --> Module not found: Error: Can't resolve 'css-box-model' in '/vercel/path0/node_modules/@chakra-ui/utils/dist'

### Chakra UI Version

2.4.1

### Browser

Google Chrome Version 108.0.5359.126 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

https://user-images.githubusercontent.com/49788350/212297876-91ef2af8-c737-4ad2-a2f1-93883e5e2091.png

**Comment by segunadebayo** [comment]
Hi @Ian-Balijawa,

Please upgrade to the latest version. I just verified that it works.

<img width="651" alt="CleanShot 2023-01-13 at 15 20 03@2x" src="https://user-images.githubusercontent.com/6916170/212308560-f3d62ce9-0389-44db-a7bf-3baeb6e1d5ab.png">

**Comment by Ian-Balijawa** [comment]
updating worked, thanks
