### ISSUE TITLE
minW not working on button with responsive size

### ISSUE THREAD

**Issue by nejcm** [chakra-ui/chakra-ui#7236]
### Description

When defining a button with multiple sizes the minW attribute can not be overridden. Same goes if a button has minW inside theme config sizes.
Eg. `<Button colorScheme='blue' minW="200px" size={['sm', 'md', 'lg']}>Button</Button>`

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-button-bug-gb1u9o

### Chakra UI Version

2.4.3

### Browser

Edge

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @nejcm,

Please use `!important` for this use-case, the media queries make it pretty challenging to override the min-width for the responsive sizes.

Cheers
