### ISSUE TITLE
Tailwind css-like color opacity modifier

### ISSUE THREAD

**Issue by SonMooSans** [chakra-ui/chakra-ui#7239]
### Description

The design system of Chakra UI of pretty nice!

But when the project is growing, I found that it was hard to change the opacity of colors
I need to add a new color variable to my theme config in order to use a color with opacity

Can we have something like `blue.900/50` just like what we can do in tailwind css?

### Problem Statement/Justification

it decreases the difficulty of changing a color variable and improves the code quality

For example, we have a semantic token color called `primary`, I can use `primary/50` as the background for hovered buttons
If I'd like to change the primary color I just need to change the value in the theme easily

Otherwise, if I have a theme like this:
```
background: {
    default: "#123456". _dark: "#123456"
},
backgroundAlpha: {
    default: "#12345678". _dark: "#12345678"
}
```
I need to edit all related variables in order to change the primary color

### Proposed Solution or API

```jsx
<Box bg='blue.900' /> //1
<Box bg='blue.900/50' /> //0.5
```

### Alternatives

Add a new color variable or directly copy the value

### Additional Information

https://tailwindcss.com/docs/background-color#changing-the-opacity

**Comment by segunadebayo** [comment]
Hi @SonMooSans,

We thought about this after a while but decided not to go in this direction. I'd recommend creating an "alpha" palette for most of your colors instead of dynamically changing it at runtime.

See some ideas here:
https://www.radix-ui.com/docs/colors/palette-composition/the-scales
