### ISSUE TITLE
useMenuDescendants no longer exported

### ISSUE THREAD

**Issue by Pagebakers** [chakra-ui/chakra-ui#7240]
### Description

I have components that depend on this hook, but it's no longer exported, this should've been a major change :(

```ts
export const [
  MenuDescendantsProvider,
  useMenuDescendantsContext,
  useMenuDescendants,
  useMenuDescendant,
] = createDescendantContext<HTMLElement>()
```

None of these are re-exported in the main index.ts

### Link to Reproduction

import { useMenuDescendants } from '@chakra-ui/react'

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.4.3

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by MaximKing1** [comment]
+1 also experiencing this
