### ISSUE TITLE
<Button disabled={undefined} isDisabled /> is not disabled

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#7243]
### Description

This button is disabled:

```
<Button isDisabled>Button</Button>
```

but this button isn't:

```
<Button disabled={undefined} isDisabled>Button</Button>
```

### Link to Reproduction

https://codesandbox.io/s/purple-breeze-4sdci9?file=/src/index.js

### Chakra UI Version

2.4.8

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by tuananhl** [comment]
@lcswillems you can see this [line](https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/button/src/button.tsx#L90) . Then, you can understand that your `disabled={undefined}` will replace the disabled prop in this [line](https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/button/src/button.tsx#L82)

So, you can only use `isDisabled` prop for disable the button

**Comment by segunadebayo** [comment]
As documented, `isDisabled` is the way to disable the buttons.

I'll update the code to reflect this as well, but @tuananhl is spot on with why this happens.
