### ISSUE TITLE
Modal/Drawer open/close animations become dramatically slow when the DOM  node size is more than 10000

### ISSUE THREAD

**Issue by tumdav93** [chakra-ui/chakra-ui#7245]
### Description

When the DOM nodes size is not so large modal or drawer open/close animations are working fast. It dramatically starts slowing when the DOM elements count is increasing. As there are no expensive re-renders the expected behavior is that there should not be any lag.
Putting  motionPreset="none" and trapFocus={false}  makes modal/drawer open-close actions a bit quicker but again it does not work as fast as when DOM is small.

  

### Link to Reproduction

https://codesandbox.io/s/wandering-fast-71wv53?file=/src/app.js

### Steps to reproduce

1. Open the provided code sandbox link 
2. Click on **Open Modal** button
3. See modal open/close delays a bit
4.  Open ```src/app.js``` file
5. In line 6 change data count  from 10,000 to 100 
6. Click on **Open Modal** button
7. Modal  open/close actions work as fast as expected

### Chakra UI Version

2.4.8

### Browser

Google Chrome Version 109.0.5414.87 (Official Build) (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by tumdav93** [comment]
@segunadebayo I would really appreciate your suggestion here, I guess it's because of framer-motion.

**Comment by dvartic** [comment]
Can also be related to Chrome/Chromium, since it seems to be working fine on Firefox.

**Comment by bebru2k1** [comment]
same issue :((

**Comment by brenopolanski** [comment]
I have the same issue.

> Can also be related to Chrome/Chromium, since it seems to be working fine on Firefox.

For me, the Firefox also has the same issue.

**Comment by SangJunBak** [comment]
Same issue :(

**Comment by shihKaiHung** [comment]
Same issue: (

**Comment by hiroyuki-chiba-0** [comment]
Same issue: (

**Comment by denisputnov** [comment]
Same issue :(

**Comment by segunadebayo** [comment]
Having a DOM size of 10000 elements is bound to have a performance issue.

Even lighthouse recommends that you keep the DOM size around 2000 elements or so.
https://developer.chrome.com/docs/lighthouse/performance/dom-size

Things you can do:

- Create a dedicated portal container for all portals to avoid appending portals to `document.body` (due to the large DOM size and reflow cost). Then set all portals to be mounted to this container.

- Use a virtualization library to manage the number of visible items.

**Comment by odemchenkocbre** [comment]
I have the same issue
Chakra version: 3.4.0

Number of DOM elements on the page: 145. But anyway, open and close animation is extremely slow.

**Comment by tumdav93** [comment]
Hi @odemchenkocbre could you please provide a code example? It would really help to better understand the current implementation. Additionally, it might be worth checking if there are any unnecessary re-renders that could be blocking the UI.
