### ISSUE TITLE
Misusing the recommended “SameSite“ attribute in color mode on Firefox

### ISSUE THREAD

**Issue by imcvampire** [chakra-ui/chakra-ui#7246]
### Description

When I use `cookieStorageManagerSSR`, there is a warning.

Log:

```
Cookie “chakra-ui-color-mode” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

### Steps to reproduce

```js
      <ChakraProvider
        colorModeManager={typeof cookies === 'string' ? cookieStorageManagerSSR(cookies) : localStorageManager}
      >
      </ChakraProvider>
```

### Chakra UI Version

2.4.4

### Browser

Firefox

### Operating System

- macOS
- Windows
- Linux

### Additional Information

https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by segunadebayo** [comment]
Hey @imcvampire.

This isn't an issue at the moment because the cookie isn't meant to be sent to third-party contexts. If it should in your app, please consider implementing a custom colorModeManager based on its interface.
