### ISSUE TITLE
Modals break tests 'check render method of 'FocusLock''

### ISSUE THREAD

**Issue by michefraim** [chakra-ui/chakra-ui#7249]
### Description

All of my tests involving modals are broken with the same error:

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `FocusLock`.
````

Using Vitest + React testing library, any version ^2.4.6 including 2.4.8.

### Link to Reproduction

https://codesandbox.io/s/floral-wildflower-4prhud

### Steps to reproduce

1. Setup vitest
2. have a test of a chakra-ui modal of some sort (AlertDialog, Modal or such)
3. Make sure the test sets the `isOpen` to true

### Chakra UI Version

^2.4.6

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

* The reproduction doesn't work for some reason in the sandbox, but should work locally

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
