### ISSUE TITLE
Drawer component pinned to the bottom should have max-height or height restrictions if its not full.

### ISSUE THREAD

**Issue by hadson172** [chakra-ui/chakra-ui#7252]
### Description

Drawer component with `placement="bottom"` and `size != "full"` has `max-height: 100vh`

### Link to Reproduction

https://chakra-ui.com/docs/components/drawer/usage

### Steps to reproduce

1. Go to https://chakra-ui.com/docs/components/drawer/usage
2. Click on radio botton "bottom" to open bottom drawer
3. Inspect shows 
![obraz](https://user-images.githubusercontent.com/8881977/212899897-f4123699-7f19-4a01-a64c-2fa39d5fe7b0.png)

### Chakra UI Version

2.0.2

### Browser

Firefox

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @hadson172,

This is not a bug. Feel free to modify this yourself.

```jsx
<DrawerContent maxHeight="400px">
...
</DrawerContent>
```
