### ISSUE TITLE
When two drawers are opened in same time scrolling by scrollwheel is broken.

### ISSUE THREAD

**Issue by hadson172** [chakra-ui/chakra-ui#7254]
### Description

When i open two drawers, one on the top of the other scrolling by scrollwheel is broken.

### Link to Reproduction

https://codesandbox.io/s/festive-pateu-rwsgp2?file=%2Fsrc%2Findex.tsx

### Steps to reproduce

1. Just click the button to open two drawers and see that scrolling is not possible

### Chakra UI Version

2.4.9

### Browser

Firefox

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by carlosberti** [comment]
Having the same problem here. Any workaround, @hadson172?

**Comment by carlosberti** [comment]
Quick workaround: disable `blockScrollOnMount` at the drawers.

**Comment by segunadebayo** [comment]
Hey @hadson172, you need to wrap the drawer within each other to get this working.

```jsx
<ParentDrawer>
  <ChildDrawer />
</ParentDrawer>
```

not

```jsx
  <ParentDrawer />
  <ChildDrawer />
```
