### ISSUE TITLE
ModalHeader and ModalCloseButton overflow

### ISSUE THREAD

**Issue by bertho-zero** [chakra-ui/chakra-ui#7256]
### Description

When a modal is displayed with a long title, it can go behind the close button, which is visually not pretty.

![image](https://user-images.githubusercontent.com/8525267/213140569-3d836710-9f5b-471e-9931-ac2967005420.png)

### Link to Reproduction

https://codesandbox.io/s/sad-babycat-ijposv?file=/src/index.js

### Steps to reproduce

1. Click on 'Open Modal'

### Chakra UI Version

2.4.9

### Browser

Brave 1.46.144

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

This problem could be fixed by moving the ModalCloseButton in the ModalHeader, which changes the html structure a bit but doesn't change anything visually because the button is absolute.

And when there is a close button in the header, we can increase the right padding to avoid overlapping:

```jsx
{/* Before */}
<ModalContent>
  <ModalHeader>
    ...
  </ModalHeader>
  <ModalCloseButton />
</ModalContent>

{/* After */}
<ModalContent>
  <ModalHeader>
    ...
    <ModalCloseButton />
  </ModalHeader>
</ModalContent>
```

The fix ([example](https://codesandbox.io/s/hardcore-curran-ljv4yx?file=/src/index.js)), it can be in the theme:

```jsx
<ModalHeader
  sx={{
    ':has(> .chakra-modal__close-btn)': {
      pr: 12, // to not overflow with close button
    },
  }}
>
```

![image](https://user-images.githubusercontent.com/8525267/213143709-59e07914-fe0e-4d10-9341-d278f7c71dfc.png)

**Comment by ArthurDinalli** [comment]
I could be misunterstanding the issue, but this seems to be a correct behavior. On your example in the sandbox, you had set the modal size to "xs", this means that it`s using a fixed size. If you want it to maintain its natural padding, try removing the property!

**Comment by bertho-zero** [comment]
Removing the size does not resolve the issue, the problem is that a long title can go behind the close button.

The title can be translated into several languages or contain dynamic content and have an unknown length.

Same example without size: https://codesandbox.io/s/wonderful-lumiere-mlnqhs?file=/src/index.js

**Comment by ArthurDinalli** [comment]
![Screen Shot 2023-01-26 at 15 20 12](https://user-images.githubusercontent.com/50238147/214917734-5a1b9baa-767a-4269-ba2e-6268a8a95005.png)
This is a print on the sandbox.

**Comment by bertho-zero** [comment]
With Chrome, Brave and Firefox on Ubuntu. I have the same result on all my browsers.

![image](https://user-images.githubusercontent.com/8525267/215073293-87a1a2a5-5cab-412f-a168-27bf2bca35c3.png)

**Comment by abhizeit** [comment]
I also encountered this issue today. Had to remove the `<ModalCloseButton />`  to achieve the desired UI.

**Comment by segunadebayo** [comment]
I acknowledge this issue. However, I consider it a subjective choice. Fortunately, you can fix this yourself by setting the CloseButton to position relative and fixing the layout to match your desired outcome, or you can set a padding end to the modal header.
