### ISSUE TITLE
MenuItem icon not vertically aligned

### ISSUE THREAD

**Issue by xobotyi** [chakra-ui/chakra-ui#7257]
### Description

If add icon to `MenuItem` there is no easy way to align item within `chakra-menu__icon-wrapper`.
One of workarounds is to use `Center` component, but it is redundant eleemnt in tree.

Also it is impossible to add custom styles since icon props arent exposed within `menuAnatomy` of `@chakra-ui/anatomy`.

### Link to Reproduction

https://codesandbox.io/s/intelligent-bouman-1nsh6u?file=/src/index.tsx

### Steps to reproduce

- Add icon which dimensions smaller than `chakra-menu__icon-wrapper`

### Chakra UI Version

2.4.9

### Browser

Chrome 109

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by tae100k** [comment]
@segunadebayo 
From what version it  will be available?
