### ISSUE TITLE
Image component is incompatible with Next.js Image

### ISSUE THREAD

**Issue by zchenwei** [chakra-ui/chakra-ui#7261]
### Description

The Image component is not compatible with the Next.js `Image` component. The Next.js `Image` component expects `width` and `height` to be defined or it will throw an error. The issue is Chakra Image component thinks `width` and `height` are style props and passes them to the `style` prop, which Next.js doesn't like.

### Link to Reproduction

https://stackblitz.com/edit/nextjs-7gq3e9?file=pages%2Findex.js

### Steps to reproduce

```jsx
import NextImage from 'next/image'
import { Image } from '@chakra-ui/react'

const App = () => {
return (
  <Image
    as={NextImage}
    width={300}
    height={300}
    src=""
  />
)
}
```

### Chakra UI Version

latest

### Browser

Chrome 108

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

![Screen Shot 2023-01-18 at 3 24 20 PM](https://user-images.githubusercontent.com/40295569/213317264-a4507bc6-d5a0-43d8-911a-cb687a5a928c.png)

**Comment by Kevinrp22** [comment]
You must create a custom component

This is an example that I use in my project
```js
// Image.js
import { chakra } from "@chakra-ui/react";
import Image from "next/image";

export default chakra(Image, {
  shouldForwardProp: (prop) => ["width", "height", "src", "alt"].includes(prop),
});
```
then you use it
```js
Import ChakraNextImage from "chakra/components/Image";

<ChakraNextImage
    src={URL_PATH}
    width="50"
    height="50"
    alt={'img'}
    objectFit={"cover"}
    borderRadius={"full"}
/>
```

**Comment by ArthurDinalli** [comment]
Just out of curiosity, why are you trying to use the Image component from next inside chakra`s Image?

**Comment by YBouz** [comment]
> Just out of curiosity, why are you trying to use the Image component from next inside chakra`s Image?

It's a common idea, to use Chakra's styling props with Next's optimized image - I'm assuming that's what @zchenwei intention is.

I do it the way @Kevinrp22 has suggested - and as far as I know that is the correct method.

**Comment by sangdth** [comment]
@ArthurDinalli The `next/image` is created so Nextjs can optimise images with their features, but we still love to style our components in Chakra way. So when using Chakra inside Nextjs, some of us, at least me, need this combination.

**Comment by segunadebayo** [comment]
Thanks for chiming in with your solution @Kevinrp22

Feel free to use this solution for now. We would consider shipping this in the `@chakra-ui/next-js` package.

**Comment by coolbeatz71** [comment]
The `fill` property from nextjs 13 next/image is getting confused with `Token<CSS.Property.Color, "colors">`. Can somebody tell how to fix?

**Comment by yaoandy107** [comment]
@Kevinrp22 Thanks for your solutions! However, I noticed that the width and height values you're using in your custom component may cause conflicts with the Next.js Image component. This is because Chakra will treat numbers as space keys, while Next.js interprets them as pixels.

For example, when using it like this:
```tsx
<ChakraNextImage
    src={URL_PATH}
    width="36"
    height="36"
    alt={'img'}
    objectFit={"cover"}
    borderRadius={"full"}
/>
```

The CSS for width and height will be as follows:
```css
width: var(--chakra-sizes-36);
height: var(--chakra-sizes-36);
```

Do you have any idea how to solve this problem?

**Comment by NingXinHui** [comment]
> ```js
> Import ChakraNextImage from "chakra/components/Image";
> ```

Error: (0 , _chakra_ui_react__WEBPACK_IMPORTED_MODULE_1__.chakra) is not a function

**Comment by icarocapobianco** [comment]
Unfortunately, that forces us to add 'use client'. I want to keep most components SSR. Guess I got to study component composition now.

**Comment by icarocapobianco** [comment]
I think I overdid this...
```ts
'use client'
import NextImage from 'next/image'
import { Image as ChakraImage, PropsOf } from '@chakra-ui/react'

type NextProps = PropsOf<typeof NextImage>
type ChakraProps = PropsOf<typeof ChakraImage>

type ChakraPropsOnly = {
    [K in keyof ChakraProps as K extends keyof NextProps ? never : K]: ChakraProps[K]
}
type NextPropsOnly = {
    [K in keyof NextProps as K extends keyof ChakraProps ? never : K]: NextProps[K]
}

type NextPriorityKeys = 'src' | 'width' | 'height' | 'alt'

type NextPriorityPropsOnly = {
    [K in NextPriorityKeys]: NextProps[K]
} & {
    fill?: NextProps['fill']
}

type SharedKeys = Exclude<keyof (ChakraProps | NextProps), keyof NextPriorityPropsOnly>

type SharedNextProps = {
    [K in SharedKeys]: NextProps[K]
}
type SharedChakraProps =  {
    [K in SharedKeys]: ChakraProps[K]
}

export type ImageProps = ChakraPropsOnly & NextPropsOnly & NextPriorityPropsOnly & {
    otherChakraProps?: Omit<SharedChakraProps, 'as'>,
    otherNextProps?: SharedNextProps
}

export const Image = ( {
    src, width, height, alt, fill,
    otherNextProps, otherChakraProps,
    ...props
}: ImageProps ) => (
    <ChakraImage
        as={() => (
            <NextImage
                src={src}
                width={width}
                height={height}
                alt={alt}
                fill={fill}
                {...otherNextProps}
                {...props}
            />
        )}
        {...otherChakraProps}
        {...props}
    />
)

export default Image
```
