### ISSUE TITLE
Module parse failed: Unexpected character '' (1:0) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

### ISSUE THREAD

**Issue by Eriickson** [chakra-ui/chakra-ui#7266]
### Description

hello, I created a project from scratch with Nextjs 13 (I am not using the /app directory)

And the first thing I did was add Chakra UI to the project, but it throws me the following error:
## View
![image](https://user-images.githubusercontent.com/38663299/213867115-36c85825-a62d-4296-b60b-2b8085bd4665.png)
## Code: 
![image](https://user-images.githubusercontent.com/38663299/213867230-8400b572-9cf1-4f19-9ff6-ec9608736197.png)

I followed exactly the steps that are in the official documentation for both nextjs and Chakra UI
NextJs Doc: https://nextjs.org/docs/basic-features/typescript
Chakra UI Doc: https://chakra-ui.com/getting-started/nextjs-guide

### Link to Reproduction

Not sandbox

### Steps to reproduce

1. install project
2. Run yarn dev command

### Chakra UI Version

2.4.9

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by abdulmalik-yahya** [comment]
use `npm i file-loader`
and include it in the webpack.config.js , as follows just within the rules array of objects

`module: {
    rules: [
      { test: /\.(ts|tsx|jsx)$/, loader: "ts-loader" },
      { test: /\.css$/, use: ['style-loader', 'css-loader'] },
      // custom loader added by me and installed using npm i file-loader
      {
        test: /\.(gif|svg|jpg|png)$/,  // add whatever files you wanna use within this regEx
        use: ["file-loader"]
      }

    ],

.......... other boilerplate config `

I hope this can help you

**Comment by segunadebayo** [comment]
Hi @Eriickson,

This issue doesn't contain a reproduction, and it's hard for us to help.

Please create a CodeSandbox or StackBlitz reproduction, and we'll re-open

**Comment by ellysabbath** [comment]
I got something, But even my self amgetting the same problem but am not using webpack.config.js am using next.config.mjs, how can i get help
