### ISSUE TITLE
BreadcrumbLink not compatible with next.js 13

### ISSUE THREAD

**Issue by villesau** [chakra-ui/chakra-ui#7267]
### Description

Following:

```
        <BreadcrumbItem isCurrentPage>
          <BreadcrumbLink
            as={NextLink}
            href={`/some-link`}
          >
            link
          </BreadcrumbLink>
        </BreadcrumbItem>
```

causes `Failed prop type: The prop `href` expects a `string` or `object` in `<Link>`, but got `undefined` instead.` in the next.js 13 projects. When removing the above, things starts to work. I believe it might need some adjustments to work like regular link: https://chakra-ui.com/docs/components/link/usage#usage-with-nextjs

### Link to Reproduction

https://codesandbox.io/s/exciting-benji-g7p6vu?file=/pages/index.tsx

### Steps to reproduce

1. unfortunately the sandbox is somehow broken and resolving the dependencies does not seem to work correctly.

### Chakra UI Version

2.4.9

### Browser

chrome 109

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jeferson-sb** [comment]
I believe this issue happens because the `ìsCurrentPage` makes so the breadcrumb link renders in `<span>` instead of an anchor tag and it also doesn't forward the `href` property that is required to `next/link` component.
If you get rid of the `as={NextLink}` prop then it should work.

https://github.com/chakra-ui/chakra-ui/blob/bea57af3fc039fce0d1b9ac272cdd65c21fd98e1/packages/components/breadcrumb/src/breadcrumb-link.tsx#L30-L34

**Comment by segunadebayo** [comment]
To get  this working, you need to omit the `as={NextLink}` when `isCurrentPage` is set to true

**Comment by villesau** [comment]
Thanks! That makes sense, but it's not clear when using the component. Documentation regarding next.js usage could help (I can draft something when validated that this works), but in optimal case the user of the component would not need to consider different flags when using the component with next.js. One option could be to omit the `as` inside the component in case of `isCurrentPage`, but there is of course a chance that it blocks some other use cases so it is important to understand what the `as` is mostly used for in this case to make any tradeoffs. Does ChakraUI have other similar cases in some components?

**Comment by manikanta-pindi** [comment]
In NextJS for the last breadcrumb, we can make ### as={ condition===true ? Text : NextLink }. This should do it.
