### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by wouterds** [chakra-ui/chakra-ui#727]
It would be nice if there's a changelog between versions. E.g. I see I'm on v0.7.0 and I can update to 0.8.0 but I have no clue what's changed, is new, or might be breaking changes.

**Comment by segunadebayo** [comment]
Hi @wouterds,

There are no breaking changes. We mostly improved types and added forwardRefs to some components.

Here's the link to the Changelog. https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/CHANGELOG.md

We'll try to improve this next time, thanks for the feedback.
