### ISSUE TITLE
square avatars

### ISSUE THREAD

**Issue by talksik** [chakra-ui/chakra-ui#7272]
### Description

I can't seem to find a way to have rounded avatars instead of fully circle ones. Even with trying to override inline styles.

### Problem Statement/Justification

I can't seem to find a way to have rounded avatars. Even with trying to override inline styles.

### Proposed Solution or API

A variant : "circle" | "square"

**Comment by la55u** [comment]
e.g. `borderRadius={2}` on `Avatar` works fine for me

**Comment by talksik** [comment]
ahh yess thank you works out well!
