### ISSUE TITLE
SkeletonText regression - no longer shimmers

### ISSUE THREAD

**Issue by jaypaik** [chakra-ui/chakra-ui#7277]
### Description

I recently upgraded to 2.4.9 and noticed that `SkeletonText` components weren't shimmering anymore. The default color they render with happens to blend into the background of my app so they're not visible at all to users. 

I made a hotfix on my end to replace these with `Skeleton` components instead, but wanted to flag this.

You can see the repro on the docs: https://chakra-ui.com/docs/components/skeleton/usage#circle-and-text-skeleton

Thanks!

### Link to Reproduction

https://chakra-ui.com/docs/components/skeleton/usage#circle-and-text-skeleton

### Steps to reproduce

1. See that the SkeletonText component does not shimmer.

### Chakra UI Version

2.4.9

### Browser

Google Chrome 109

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by GKosheev** [comment]
@jaypaik, I created an issue related to that problem (#7230) a couple of weeks ago with a potential solution. 

As for now, as @STiXzoOR mentioned, you should pass `speed` and `fadeDuration` props to that component directly.

The default values for those props are the following: 

```javascript
    fadeDuration: 0.4, 
    speed: 0.8
```

**Comment by GKosheev** [comment]
@jaypaik it got fixed in 2.5.0, so this issue can now be closed
