### ISSUE TITLE
Improve Docs for Modal / Missing imports

### ISSUE THREAD

**Issue by jackblackCH** [chakra-ui/chakra-ui#728]
There are three missing imports of components which are used in the JSX demo code.
https://chakra-ui.com/modal

`useDisclosure` and `Button` and `Lorem`

```
// Current docs
import {
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalFooter,
  ModalBody,
  ModalCloseButton,
} from "@chakra-ui/core";
```
I expect the demo code to work out of the box. 

```
// Expected in docs
import {
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalFooter,
  ModalBody,
  ModalCloseButton,
  useDisclosure,
  Button
} from "@chakra-ui/core";
```

So there should be `useDisclosure` and `Button`

a `Lorem` component is used as well which does not come from Chakra-UI?

**Comment by segunadebayo** [comment]
Hey @robbevan, thanks for letting us know.

The goal of the imports at the top is to show only Modal related components.

I do understand your point though. In the next docs will include a codesandbox link where you'll find all the imports you expect.

Thanks.

PS: Yes, Lorem doesn't come from Chakra UI

**Comment by robbevan** [comment]
Not me, but good to know. For @jackblackCH I think.

**Comment by ejabu** [comment]
for someone else who is starting with Chakra-ui,

I suggest you to change this

```
<Lorem/>
```

to 
```
            <Skeleton w={1/3} my={2} height="10px" />
            <Skeleton height="10px" />
```

don't forget to update imports at the top of the file

```
import {
  Skeleton, // THIS ONE
  Button,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalFooter,
  ModalBody,
  ModalCloseButton,
} from "@chakra-ui/core";
```
