### ISSUE TITLE
Using <Link as={NextLink}/> requires href as string

### ISSUE THREAD

**Issue by rtman** [chakra-ui/chakra-ui#7280]
### Description

When I use the chakra recommended way of using nextjs 13 links I expect to be able to pass an object to href but it requires a string. `NextLink` allows object notation for href but chakra `Link` does not.

```
    <Link as={NextLink} href={{ pathname, query: queryParams }}>
      ...
    </Link>
```

![Screen Shot 2023-01-25 at 10 28 18 AM](https://user-images.githubusercontent.com/20849135/214650935-66bcce3b-336c-43b1-957a-4b1fd752e82c.png)

### Link to Reproduction

not needed

### Chakra UI Version

2.4.6

### Browser

1.43.94 chromium

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by aaronpurewal** [comment]
bump

**Comment by segunadebayo** [comment]
Please use the recently released @chakra-ui/next-js integration package to resolve this.

**Comment by dorklord23** [comment]
I couldn't find the module (`@chakra-ui/next-js`) even after installed it. I used pnpm to install it.

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/aria/repo/kommodity-catalog-website/node_modules/.pnpm/@chakra-ui+next-js@2.0.1_vynkb36op7zw7sbyuz74ywk4ve/node_modules/next/link' imported from /home/aria/repo/kommodity-catalog-website/node_modules/.pnpm/@chakra-ui+next-js@2.0.1_vynkb36op7zw7sbyuz74ywk4ve/node_modules/@chakra-ui/next-js/dist/chunk-LYWO3SBR.mjs
Did you mean to import next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/link.js?
```
