### ISSUE TITLE
Avatar doesn't support emoji

### ISSUE THREAD

**Issue by krystxf** [chakra-ui/chakra-ui#7290]
### Description

I don't know if it's ideal to display the emoji directly, but I don't think this is the ideal placeholder

![image](https://user-images.githubusercontent.com/48121710/215257039-0290894c-6b0c-43f2-b8e7-35f2cd20990f.png)
 

### Link to Reproduction

https://codesandbox.io/s/serene-james-9ysm0b

### Steps to reproduce

1. `<Avatar name='😄' /> `

### Chakra UI Version

2.4.9

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by nimpossible** [comment]
You can use Avatar with an icon for the same, why to work with the `name` prop? `icon` prop adds more intent.

![image](https://user-images.githubusercontent.com/16114850/215543234-e0ed88ba-5cf9-46e7-817c-a184e3d52a57.png)

Demo here: https://lnttcz.csb.app/

Happy for a discussion! 🙂

**Comment by krystxf** [comment]
The problem I've run into is that a user can fill in an emoji in the username, and only an emoji is also a valid username. So I was wondering if it would be bloat to add a handler for this to the Chakra UI

**Comment by nimpossible** [comment]
@krystxf: I didn't get what you mean when- a user can fill in an emoji in username (understood in plan English, but not logically), because, from the end user's perspective it doesn't matter how are you handling that in code! If I'm not able to understand your thoughts, could you please elaborate more with an example?

**Comment by segunadebayo** [comment]
Hi @krystxf,

This sounds to me like a custom requirement that should be added to your own code, not Chakra.

Feel free to use the `getInitials` function to convert the emoji into something that works for your app:
<img width="796" alt="CleanShot 2023-02-06 at 17 21 59@2x" src="https://user-images.githubusercontent.com/6916170/216982299-ca60f092-94d5-4ff3-99a9-83ff1e711531.png">
