### ISSUE TITLE
Collapse isOpen property does not exist

### ISSUE THREAD

**Issue by fabidi** [chakra-ui/chakra-ui#7291]
### Description

According to the documentation, we should use isOpen. This fails. When using "in" instead, that works.

E.g, when specifying these two components, only the latter will be displayed:

<Collapse isOpen={true}>isOpen Example</Collapse>
<Collapse in={true}>In Example</Collapse>

### Link to Reproduction

https://codesandbox.io/s/cool-cookies-9tj3vi?file=/src/index.tsx

### Steps to reproduce

1. Open the sandbox
2. Click on 'Toggle'
3. See that only the "In Example" is displayed.

### Chakra UI Version

2.4.9/latest

### Browser

Google Chrome 108.0.5359.126 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by nimpossible** [comment]
@fabidi: Looks like this is not a bug, but you're using the props incorrectly in the newer Chakra version. As you've also mentioned that the documentation says the same, I reckon you're referring to the older version of docs. Also, the `codesandbox` link contains the latest version of Chakra. Below I got for you...

- Version 0.8.x: https://v0.chakra-ui.com/collapse (You might be referring this)
- Version 1.8.8: https://v1.chakra-ui.com/docs/components/other/transitions#collapse-transition (but, the code is from here where the props are changed and it is `in`)

Screenshot from your code:
![image](https://user-images.githubusercontent.com/16114850/215536915-eaf55684-49fc-4525-980c-a642470205c7.png)

**Comment by segunadebayo** [comment]
Thanks for chiming in @nimpossible 

Please upgrade to the latest version. That should fix your expectation. The current docs if for v2

**Comment by fabidi** [comment]
Ah, thank you for setting me straight folks. I was using old docs. Thank you, this was maddening. So when I googled for Chakra docs, it always shows me the v0 docs first, unless I explicitly google for Chakra v2.
