### ISSUE TITLE
Export FocusLock from @chakra-ui/react

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#7293]
### Description

I would want to be able to do:

```
import { FocusLock } from "@chakra-ui/react";
```

instead of:

```
import { FocusLock } from "@chakra-ui/focus-lock";
```

This will require one less package to be added to package.json.

### Problem Statement/Justification

Cf description

### Proposed Solution or API

Cf description

**Comment by segunadebayo** [comment]
Good idea! Done ✅

**Comment by lcswillems** [comment]
Thanks :pray:
