### ISSUE TITLE
Module '"@chakra-ui/react"' has no exported member 'ExpandedIndex'.

### ISSUE THREAD

**Issue by psychedelicious** [chakra-ui/chakra-ui#7296]
### Description

As of `@chakra-ui/react` 2.4.5, I am getting this when trying to import the `ExpandedIndex` type:
`Module '"@chakra-ui/react"' has no exported member 'ExpandedIndex'.`

Issue does not occur on 2.4.4.

Maybe related to #7154?

### Link to Reproduction

https://codesandbox.io/s/youthful-platform-exsdcw?file=/src/index.tsx

### Steps to reproduce

- Note the error on @chakra-ui/react 2.4.5
- Change to @chakra-ui/react 2.4.4 and refresh - no error.

### Chakra UI Version

^2.4.5

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
