### ISSUE TITLE
VSCode auto import stops working after first import in monorepo

### ISSUE THREAD

**Issue by MarceloAlves** [chakra-ui/chakra-ui#7298]
### Description

We're having this interesting issue in our monorepo that we can't seem to figure out. When we use intellisense to auto import something from Chakra any subsequent import can't be found. This only seems to happen when each package is running the same version of Chakra (in this case 2.4.9). If we pin all packages to different Chakra versions the problem goes away. However, we had to move away from using different versions because of some issues with context sharing.

![CleanShot 2023-01-30 at 12 00 25](https://user-images.githubusercontent.com/216782/215583066-3bbcc0ef-6467-4763-92ca-7c464d1f412f.gif)

### Link to Reproduction

https://github.com/MarceloAlves/chakra-monorepo-repro

### Steps to reproduce

1. Clone repo
2. Run `pnpm install`
3. Open VSCode
4. Open `apps/new-app/src/index.tsx`
5. In the component, type `const t = useToast` and have VS Code auto import from the dropdown
6. Try to import `useDisclosure` the same way

### Chakra UI Version

2.4.9

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hey @MarceloAlves,

Unfortunately, this is not an issue we can resolve on our end.

It work pretty well for me though

**Comment by cyphercider** [comment]
Hi @MarceloAlves, did you ever come up with a solution to this?  I'm seeing the same behavior.

**Comment by MarceloAlves** [comment]
> Hi @MarceloAlves, did you ever come up with a solution to this? I'm seeing the same behavior.

Hey there. I haven't. A coworker had it working for a while then after installing deps it quit working for him. Importing in the `components` package works fine but all the apps won't work. I've given up on making it work at this point
