### ISSUE TITLE
Modal crashes because of the active element being an iframe which has different origin 

### ISSUE THREAD

**Issue by sandrinjoy** [chakra-ui/chakra-ui#7306]
### Description

export var getActiveElement = function (inDocument) {
    var _a;
    if (inDocument === void 0) { inDocument = document; }
    if (!inDocument || !inDocument.activeElement) {
        return undefined;
    }
    var activeElement = inDocument.activeElement;
    return (activeElement.shadowRoot
        ? getActiveElement(activeElement.shadowRoot)
        : activeElement instanceof HTMLIFrameElement && ((_a = activeElement.contentWindow) === null || _a === void 0 ? void 0 : _a.document)
            ? getActiveElement(activeElement.contentWindow.document)
            : activeElement);

};

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/48259475/215964921-ae2f1690-5980-4c7f-92bf-1c58d0bccb29.png">

It started to happen after updating chakra ui.
i remember there was a change in the implementation of modal, where it is referenced with the current active element or something

### Link to Reproduction

localhost:3001

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.4.9

### Browser

chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by orv1s** [comment]
had same issue when interacting with Paypal iframe, upgrading to 2.5.1 fixed it.
