### ISSUE TITLE
Modal needs some horizontal margin

### ISSUE THREAD

**Issue by abhizeit** [chakra-ui/chakra-ui#7308]
### Description

Modal needs some `mx` as  it takes the the takes the full `vw` in small screens. A little horizontal margin would make component look more clean.

### Problem Statement/Justification

This is what the modal looks before adding horizontal margin.
![Screenshot 2023-02-01 204811](https://user-images.githubusercontent.com/81003403/216083426-b12ae1a1-e4ad-45f2-8628-5f232bae2ce2.png)

Here is the component with some horizontal margin.
![Screenshot 2023-02-01 205711](https://user-images.githubusercontent.com/81003403/216086609-eb73e72f-741f-4377-94a6-37bf9966c5db.png)

### Proposed Solution or API

`mx="10px"`

**Comment by segunadebayo** [comment]
This is a subjective decision that can vary from app to app. Please add this to your app for now.

Thanks

**Comment by NiklasPor** [comment]
For anyone coming across this, adding padding on the `dialogContainer` will work more nicely, because you won't receive any scroll bars on very small screens. 👋  Also I totally agree that this is subjective 👍
