### ISSUE TITLE
Allow to pass ref

### ISSUE THREAD

**Issue by flexicious** [chakra-ui/chakra-ui#7311]
### Description

We are developing an adapter for our datagrid component to use Chakra, similar to one we did for Ant and Material:  https://reactdatagrid.com/docs/ant-design/ant-design-adapter. https://reactdatagrid.com/docs/category/material-ui/ 

There is a demo of this at https://reactdatagrid.com/examples/?example=Material_Demo https://reactdatagrid.com/examples/?example=Ant_Design_Demo. 

However, we are not able to reference the underlying input element. By comparison, Material allows to pass inputRef property (https://mui.com/material-ui/api/text-field/#props) which we can use to perform custom actions on the text input. Is it possible to expose a ref property on Input, Select and TextArea elements? 

### Problem Statement/Justification

This will allow us to do things like focus into text areas, get values in and out, etc. 

### Proposed Solution or API

<Input ref={inputRef}
<Select ref={selectRef}
<Checkbox ref={checkBoxRef}

**Comment by segunadebayo** [comment]
Hi @flexicious,

At the moment, all the components you mentioned all support `ref`. If you notice anything weird not working feel free to open an issue specific to that component.

Thanks
