### ISSUE TITLE
Flash of partially styled content on page load

### ISSUE THREAD

**Issue by dysbulic** [chakra-ui/chakra-ui#7314]
### Description

[MetaGame](//metagame.wtf)'s site is rendered server-side by Next.js (`v12.3.1`). When this happens, only the global styles are being generated. Component-specific styles are only rendering client-side, and this causes a period of partially styled content when the page loads.

### Link to Reproduction

Unable to reproduce in a small app.

### Steps to Reproduce

I suspect the issue has to do with the size of our application. When I created an [app in CodeSandbox](//codesandbox.io/p/sandbox/frosty-snow-gbf3et) and viewed the HTML sent by the server, it includes `style` tags with `data-emotion` set to both `css-global` *(the global styles)* and `css` *(the component-specific styles)*.

[MetaGame](//metagame.wtf)'s site is only generating the global styles.

1. Open the network inspector in the browser's developers' tools
2. Go to [metagame.wtf](//metagame.wtf)
3. View the first file sent which should be HTML called `metagame.wtf` at the top of the network inspector's files list
4. Hit the `{}` button in the lower left corner to reformat the document
5. Scroll down until you find the `body` tag
6. Note that the `style` following it has a `data-emotion` attribute of `css-global`
7. Scroll to the bottom of that, and then past three more `css-global` `style`s
8. Note that the HTML begins following the last `css-global` `style`, there are no component-specific `css` styles

### Chakra UI Version

2.3.6

### Browser

Brave 1.47

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Hi @dysbulic,

This is a strange scenario and I don't think it's related to the size of your site. We'll need more information to help you resolve this unfortunately.

If you're able to reproduce a minimal part of your app, please post it here and I'll re-open.
