### ISSUE TITLE
Don't include `value` state in `useClipboard`

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#7319]
### Description

I would like [the implementation of useClipboard](https://github.com/chakra-ui/chakra-ui/blob/main/packages/legacy/hooks/src/use-clipboard.ts) to be modified this way:

```diff
export function useClipboard(
-  initialValue: string,
+  value: string,
  optionsOrTimeout: number | UseClipboardOptions = {},
) {
  const [hasCopied, setHasCopied] = useState(false)

-  const [value, setValue] = useState(initialValue)

  const { timeout = 1500, ...copyOptions } =
    typeof optionsOrTimeout === "number"
      ? { timeout: optionsOrTimeout }
      : optionsOrTimeout

  const onCopy = useCallback(() => {
    const didCopy = copy(value, copyOptions)
    setHasCopied(didCopy)
  }, [value, copyOptions])

  useEffect(() => {
    let timeoutId: number | null = null

    if (hasCopied) {
      timeoutId = window.setTimeout(() => {
        setHasCopied(false)
      }, timeout)
    }

    return () => {
      if (timeoutId) {
        window.clearTimeout(timeoutId)
      }
    }
  }, [timeout, hasCopied])

-  return { value, setValue, onCopy, hasCopied }
+  return { value, onCopy, hasCopied }
}
```

### Problem Statement/Justification

I currently have this component:

```
import { CheckIcon, CopyIcon } from "@chakra-ui/icons";
import { IconButtonProps, useClipboard, IconButton } from "@chakra-ui/react";

export type CopyIconButtonProps = IconButtonProps & { value: string };

export default function CopyIconButton({
  value,
  ...props
}: CopyIconButtonProps) {
  const { hasCopied, setValue, onCopy } = useClipboard(value);

  useEffect(() => {
    setValue(value);
  }, [value]);

  return (
    <IconButton
      icon={hasCopied ? <CheckIcon /> : <CopyIcon />}
      onClick={onCopy}
      {...props}
    />
  );
}
```

Because there is a `value` state inside `useClipboard`, I need to sync my `value` to `useClipboard` `value` state using a `useEffect`.

With the modification I suggest, this code would work:

```
import { CheckIcon, CopyIcon } from "@chakra-ui/icons";
import { IconButtonProps, useClipboard, IconButton } from "@chakra-ui/react";
import { useEffect } from "react";

export type CopyIconButtonProps = IconButtonProps & { value: string };

export default function CopyIconButton({
  value,
  ...props
}: CopyIconButtonProps) {
  const { hasCopied, setValue, onCopy } = useClipboard(value);

  return (
    <IconButton
      icon={hasCopied ? <CheckIcon /> : <CopyIcon />}
      onClick={onCopy}
      {...props}
    />
  );
}
```

### Proposed Solution or API

Cf above

**Comment by segunadebayo** [comment]
This is an interesting proposal, and I like where it's going.

This would be a breaking change at the moment. I'd recommend moving the state sync code into the use-clipboard hook for backward compatibility (while enabling this feature)

I'll work on this shortly

**Comment by segunadebayo** [comment]
I just pushed an update for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by lcswillems** [comment]
Thanks for finding a clever way to modify the hook while keeping the backward compatibility :pray: 

I think that in Chakra-UI v3, we should remove the `valueState` entirely as it creates unnecessary rerenders.

To add on the importance of this issue:

We originally thought that `useClipboard(value)` would be copying `value` to the clipboard. We then lately discovered it was only copying the first value passed. And this had quite dangerous consequences for our app as people were copying the old value while thinking they were copying the value displayed on the screen.
