### ISSUE TITLE
Menu component doesn't work properly in monorepo

### ISSUE THREAD

**Issue by vitaliyirtlach** [chakra-ui/chakra-ui#7321]
### Description

When I run a project without monorepo (turborepo or yarn workspaces) the menu is working properly (applying theme, scroll behaviour is good), but when i move this project to turborepo (using default template form _**create-turbo**_) only menu component is not applying theme and scroll behaviour is unexpectable (jumping).

### Project without monorepo
Everything is good

https://user-images.githubusercontent.com/63682036/216816935-3abff093-9ba4-4222-9b6d-3289ee6eb6c5.mov

### Monorepo
Not applying theme and scroll behaviour is unexpectable (jumping).

https://user-images.githubusercontent.com/63682036/216817080-7ea4e8de-1694-46ec-9bf9-f56b2d4c632d.mov

### Link to Reproduction

no-link

### Steps to reproduce

1. Create turborepo 
2. Move project to apps folder
3. Install dependecies 
4. Run project
5. See bug

### Chakra UI Version

^2.3.6

### Operating System

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by designorant** [comment]
@vitaliyirtlach https://github.com/chakra-ui/chakra-ui/issues/7325 is now closed fyi. Can you check whether this is still happening?

**Comment by segunadebayo** [comment]
This was fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If after the upgrade the problem still exists in your application, please open a new issue and follow the instructions in the issue template.
