### ISSUE TITLE
Toast Accessibility

### ISSUE THREAD

**Issue by oliverroyknox** [chakra-ui/chakra-ui#7324]
### Description

When I run a web application using the `Toast` component through the [W3C Validator](https://validator.w3.org), I expect it to pass with no errors but instead it produces an error because of an invalid tag / role combination.

Inside the `<chakra-portal>` element, there is a series of `ul` tags with `role="region"` set. This is not a valid role for a `ul` tag as stated by the [UL Tag Technical Summary](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul#technical_summary), and thus is invalid HTML.

### Link to Reproduction

https://codesandbox.io/s/chakra-toast-accessibility-bpffqm

### Steps to reproduce

1. Go to the `codesandbox` link.
2. Open dev tools.
3. Copy the `html` element from the example.
4. Run the `html` through the [W3C Validator](https://validator.w3.org).
5. See error (example below).

### Chakra UI Version

2.4.9

### Browser

Chromium 109

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The output relating to the toast component from https://validator.w3.org

![Validator Output](https://user-images.githubusercontent.com/66905212/216941165-b81f37d7-a850-4338-9753-c032b16e643e.png)

**Comment by cmrd-senya** [comment]
Any updates for this issue? Anything blocking the merge of the attached PR?

**Comment by segunadebayo** [comment]
Please see comment here: https://github.com/chakra-ui/chakra-ui/pull/7499#issuecomment-1520676190
