### ISSUE TITLE
Bad typings with definePartsStyle/createMultiStyleConfigHelpers

### ISSUE THREAD

**Issue by kyin42** [chakra-ui/chakra-ui#7327]
### Description

When I define theme styles for a component with parts using definePartsStyle I expected it to be typed to only allow keys with values defined by the keys in createMultiStyleConfigHelpers.

For example Input has 3 parts 'field','element', and 'addon'. but typings allow me to set any key instead of only those 3:
```
import { inputAnatomy } from '@chakra-ui/anatomy';
import { createMultiStyleConfigHelpers, StyleConfig } from '@chakra-ui/react';

const { definePartsStyle, defineMultiStyleConfig } = createMultiStyleConfigHelpers(
  inputAnatomy.keys,
);

const baseStyle = definePartsStyle({
  field: {
    fontFamily: 'mono',
    color: 'teal.500',
  },
  test: {
    color: 'black',
  },
});

export const inputTheme = defineMultiStyleConfig({ baseStyle });
``` 
perhaps this is desired, but to my understanding any extra keys not defined by createMultiStyleConfigHelpers will do nothing and will be useless and should be prevented through correct types.

Also, just an extra note, could typing be done through a type definition instead of a function? Feels weird that we have to use createMultiStyleConfigHelpers().

### Link to Reproduction

https://codesandbox.io/s/recursing-villani-oidekl?file=/src/theme.ts

### Chakra UI Version

2.4.1

**Comment by Pagebakers** [comment]
It's actually helpful because it adds autocomplete functionality. Having this too strict might be a burden when you add custom components for example.

**Comment by segunadebayo** [comment]
As @Pagebakers mentioned, it has been helpful so far in most applications I work on.

You don't technically have to use `createMultiStyleConfigHelpers`; you can always add a type definition yourself. That function aims to provide a uniform experience for both JS and TS users.
