### ISSUE TITLE
[Select field] IE11 - duplicate dropdown arrows

### ISSUE THREAD

**Issue by alanbuchanan** [chakra-ui/chakra-ui#733]
**Describe the bug**
In IE11, the Select field shows the native dropdown arrow as well as the custom Chakra arrow.

<img width="645" alt="Screenshot 2020-05-18 at 11 01 52" src="https://user-images.githubusercontent.com/10364894/82202107-53e4be80-98f9-11ea-9ed5-c981bdcfa2e2.png">

**Expected Behavior**
Only the custom Chakra arrow should show. The native one should not show up.

**To Reproduce**
1. Open IE11
2. Navigate to https://chakra-ui.com/select
3. Observe the Select field
4. Observe two dropdown arrows

**Suggested solution(s)**
Please remove or hide the native dropdown arrow.

**Desktop (please complete the following information):**
 - OS - Windows 10
 - Browser - Internet Explorer
 - Version - 11

**Comment by lightDer** [comment]
I had the same problem. You can use this workaround on css.

```
select::-ms-expand {
  display: none;
}
```

**Comment by dedo1911** [comment]
@lightDer suggestion works perfectly. You should add it to CSSReset and make a PR

**Comment by with-heart** [comment]
The workaround has been added to `CSSReset` for the 1.0 release. Thanks for the suggestion @lightDer!

**Comment by iamandyk** [comment]
I'm seeing a duplicate arrow in Chrome Version 83.0.4103.116 (Official Build) (64-bit). Maybe I have CSSReset setup wrong? My repo is here: https://github.com/iamandyk/safespace

**Comment by with-heart** [comment]
Hi @iamandyk, this is due to chakra-ui/chakra-cli#5. 

https://github.com/chakra-ui/chakra-ui/blob/master/packages/theme/src/components/select.ts Should exist in your `chakra` folder, but isn't currently being generated by the cli, so it's missing.
