### ISSUE TITLE
Programatically open an accordion item

### ISSUE THREAD

**Issue by lukemcgregor** [chakra-ui/chakra-ui#7330]
### Description

Currently the accordion doesn't have an API listed in the documentation which allows items to be programatically opened. 

### Problem Statement/Justification

There are lots of reasons you might want to programatically open an item, however my use case is that something new gets added to the accordion and I want to have that new item focused and opened.

### Proposed Solution or API

Add open(index) and close(index) methods to the Accordion ref

### Alternatives

You can achieve this functionality by destroying and re-creating the component with a new default opened item, however this is pretty yuck to do and will likely cause other issues

**Comment by segunadebayo** [comment]
Here's a quick example of how to control the accordion programmaticaly

```jsx
import { Button, Box,  Accordion, AccordionItem, AccordionButton, AccordionPanel, AccordionIcon } from '@chakra-ui/react'
import {useState} from 'react'

export const App = () => {
  const [index, setIndex] = useState(0)
  return (
    <Accordion allowToggle index={index} onChange={setIndex}>
      <AccordionItem>Ï
        <h2>
          <AccordionButton>
            <Box as="span" flex="1" textAlign="left">
              Section 1 title
            </Box>
            <AccordionIcon />
          </AccordionButton>
        </h2>
        <AccordionPanel pb={4}>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat.
        </AccordionPanel>
      </AccordionItem>

      <AccordionItem>
        <h2>
          <AccordionButton>
            <Box as="span" flex="1" textAlign="left">
              Section 2 title
            </Box>
            <AccordionIcon />
          </AccordionButton>
        </h2>
        <AccordionPanel pb={4}>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat.
        </AccordionPanel>
      </AccordionItem>
    </Accordion>
  )
}

```

With the state in place, you can now set the value to whatever you want.

**Comment by mayteio** [comment]
It's here: https://chakra-ui.com/docs/components/accordion/props

**Comment by sr-jghb** [comment]
Those docs never mention `setIndex`, and certainly don't describe this method of toggle control
