### ISSUE TITLE
Export useModalManager and/or add index in useModal

### ISSUE THREAD

**Issue by bertho-zero** [chakra-ui/chakra-ui#7337]
### Description

I would need the `ModalManager` to create custom components that look like modals.

### Problem Statement/Justification

I am creating a custom component which is similar to a drawer except that above a certain breakpoint it is displayed directly in the dom (without a drawer).
This is to have a drawer on mobile and the content of the drawer visible on desktop without having to duplicate the elements and thus avoid Flash Of Content.

I would like to use `isTopModal` from `ModalManager` to make my component detect as the topmost modal or not.

For that it would be necessary to export `useModalManager` or that `useModal` returns the index of the modal.

### Proposed Solution or API

`useModal` could export `index`, `isTopModal` or `manager`.

`modalManager` and `useModalManager` could be exported.

**Comment by mikirejf** [comment]
Bump. It would be nice to have the manager instance exported so we can have an idiomatic way to check the number of opened modals etc ...
