### ISSUE TITLE
Button has a default hover background color style  ,which is not normal

### ISSUE THREAD

**Issue by cl510804194** [chakra-ui/chakra-ui#7341]
### Description

When i import a Button component from `@chakra-ui/react` , it has a default  hover  background color:`:var(--chakra-colors-gray-200)`,  Even if I changed its `background-color` style , the default hover background color is also exist..

### Link to Reproduction

https://codesandbox.io/p/sandbox/misty-morning-s6yglr?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A38%2C%22endLineNumber%22%3A3%2C%22startColumn%22%3A38%2C%22startLineNumber%22%3A3%7D%5D

### Steps to reproduce

1.  install dependencies
2. go to pages/index.tsx
3. mouse move on buttons
4. See error, their `background-color`  style is same 

### Chakra UI Version
enviroment:
`@chakra-ui/react`: `^2.4.9`
`next`: `13.1.6`

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Here's how to resolve this:

```jsx
<Button bg="red" _hover={{ bg: "<color>" }} >red</Button>

// or

<Button variant="unstyled" bg="<color>">red</Button>
```

**Comment by juditRamo** [comment]
You could also use the ColorScheme prop. It uses colors from the Chakra UI theme (which you can edit) and automatically sets the bg color, and the on hover bg color. 

To see how Color Scheme and theme work:
https://chakra-ui.com/docs/styled-system/customize-theme

This is quite useful if you want to maintain the same color scheme throughout the whole app.

**Comment by sbeben** [comment]
this is soooooo bad guys..
do you have a fix in plans?
