### ISSUE TITLE
Missing Icon Exports

### ISSUE THREAD

**Issue by nbouvrette** [chakra-ui/chakra-ui#7347]
### Description

I don't know if this is by design but I noticed that the `<WarningIcon />` component is included in `node_modules/@chakra-ui/icons/dist/index.d.ts` but `<SuccessIcon />` and `<ErrorIcon />` seem to be missing.

I don't know if other icons are missing too but those can be useful when building custom errors if we want to mimic Chakra's style without copying the svg.

### Link to Reproduction

N/A

### Steps to reproduce

Check description

### Chakra UI Version

Latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by sciffany** [comment]
Not sure if this will help, but are you looking for CheckIcon, and InfoIcon?

**Comment by sciffany** [comment]
Not sure if this answers your question, but are you looking for CheckIcon and InfoIcon respectively?

**Comment by segunadebayo** [comment]
Hi @nbouvrette,

We don't recommend using the `@chakra-ui/icons` package since we no longer maintain it.

Consider switching to `react-icons` or an equivalent icon library.

**Comment by nbouvrette** [comment]
@segunadebayo I'm not sure I understand, you already provide some icons in Chakra, like [alerts](https://chakra-ui.com/docs/components/alert).

I don't really need the other non-maintained icons but I would expect at least the icons that we provided in Chakra components to be available if I want to mimic the style on custom components?
