### ISSUE TITLE
Slider Element SliderThumb breaks inputs with shared state value

### ISSUE THREAD

**Issue by devcrowley** [chakra-ui/chakra-ui#7348]
### Description

If a component contains an Input and Slider element, and both element values share the same state variable, the slider element will steal focus away from the input if the input changes.  This causes the input to only allow one character to be typed at a time when it loses focus.

The problem only occurs if the slider includes a SliderThumb element within the Slider tags.  If the SliderThumb element is removed or set to "display=none" then the input works as expected.

### Link to Reproduction

https://codesandbox.io/s/ancient-cookies-g2zwtp?file=/src/index.js

### Steps to reproduce

Create an input and slider with the same state variable as their values.  When the state value changes, the slider will steal focus from the input if the input was the component which modified the value.

### Chakra UI Version

2.4.9

### Browser

Chromium

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I suspect that when the value on the slider changes, the SliderThumb takes focus since it assumes the user is dragging the slider for the value change to occur.  Perhaps a mouseDown check should be included before taking focus.  I haven't reviewed the ChakraUI slider source yet to determine if this is the cause but will look into it very soon.

**Comment by devcrowley** [comment]
Confirmed:  If you add an onFocus event to the SliderThumb, it fires when adding values to the Input.

It can be duplicated with:

<SliderThumb
    onFocus={() => {
        console.log("Sliderthumb gained focus");
    }}
/>

**Comment by segunadebayo** [comment]
Please use the `focusThumbOnChange` props and set it to `false`
