### ISSUE TITLE
`colorScheme` doesn't work with `NumberInput`

### ISSUE THREAD

**Issue by adamzerner** [chakra-ui/chakra-ui#7349]
### Description

When I set `colorScheme="red"` on `NumberInput` I expected some sort of red color but instead don't see any changes in color.

Docs: https://chakra-ui.com/docs/components/number-input/props

### Link to Reproduction

https://codesandbox.io/s/uw9cdp?file=%2FApp.tsx

### Chakra UI Version

Latest (I used Chakra Play)

### Browser

Latest Firefox

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by GKosheev** [comment]
I've just checked the basic theming for `NumberInput` and I couldn't find any definition of `colorScheme`, thus it's a mistake in the docs. I'm going to make a PR to fix that.

**Comment by segunadebayo** [comment]
Hi @adamzerner,

NumberInput doesn't implement the colorScheme props by default but you can implement that yourself if you need it.
