### ISSUE TITLE
Chakra UI's button click handlers are being removed in deno fresh

### ISSUE THREAD

**Issue by vinaybedre** [chakra-ui/chakra-ui#7350]
### Description

When I use ChakraUI in deno fresh, with a button with click handlers on them, I expect them to stay when I render in browser, but button click handlers are being removed at the time of rendering.

### Link to Reproduction

https://github.com/vinaybedre/deno-fresh-chakra-ui/blob/main/islands/Counter.tsx

### Steps to reproduce

1. Install latest version of deno
2. Clone the repo and run `deno task start`
3. Open http://localhost:8000
4. Check the Button has no click event handlers on them as defined in the repo

### Chakra UI Version

2.4.9

### Browser

Google Chrome 109.0.5414.119

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hey @vinaybedre,

At the moment, we don't have the manpower to investigate Deno fresh.

If anyone finds a solution, feel free to post it here.
