### ISSUE TITLE
React typescript compile failing randomly

### ISSUE THREAD

**Issue by ELI7VH** [chakra-ui/chakra-ui#7353]
### Description

I tried to start my project after a week (and a fresh install), and I started getting this compile error

```
Failed to compile.

./node_modules/@chakra-ui/transition/dist/chunk-3TED3OTR.mjs
Can't import the named export 'AnimatePresence' from non EcmaScript module (only default export is available)
```

I am on MacOS and have zero idea why this has happened. 

I am not importing "AnimatePresence" anywhere on my app.

I have rolled back source control to when it last compiled, and still doesn't work.

### Link to Reproduction

n/a

### Steps to reproduce

```
{
  "@chakra-ui/react": "^2.4.9",
  "@emotion/react": "^11.10.5",
  "@emotion/styled": "^11.10.5",
  "framer-motion": "^9.0.2",
}
```

### Chakra UI Version

2.4.9

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I don't even know where to start with debugging this, any guidance would be much appreciated!

**Comment by didymus707** [comment]
> ./node_modules/@chakra-ui/transition/dist/chunk-LRMLOJAR.mjs
> Can't import the named export 'AnimatePresence' from non EcmaScript module (only default export is available)

Experiencing the same thing

**Comment by ELI7VH** [comment]
I ripped out my app, and transplated it to a vite app. no more problems.
