### ISSUE TITLE
Modal content not scrolling on small screen

### ISSUE THREAD

**Issue by Danztee** [chakra-ui/chakra-ui#7356]
### Description

I have a modal with multiple input fields. On small screen, when the keyboard opens to type, I'm unable to scroll down to the second input field. I'll have to close the keyboard before I can click the second input field which is not user friendly

### Link to Reproduction

No link

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

5

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Nothing

**Comment by RioChndr** [comment]
I help to answer, modal chakra by default will block scroll as mention at here (https://chakra-ui.com/docs/components/modal/usage#block-scrolling-when-modal-opens). If you want to change it to scrollable because your form too long, you can set `blockScrollOnMount` to `false`.

Good lock, thank you.

**Comment by Danztee** [comment]
Thank you RioChndr, it worked.

**Comment by purohitdheeraj** [comment]
This worked guys put this on Modal like this ✌️
thank you @RioChndr 

```
 <ChakraModal
      blockScrollOnMount={false}
   ...
    >
```
