### ISSUE TITLE
Popover not closing on outside click when it's not focused

### ISSUE THREAD

**Issue by baptisteArno** [chakra-ui/chakra-ui#7359]
### Description

When I have buttons that trigger some state change inside a Popover, then an outside click doesn't make it close.

### Link to Reproduction

https://codesandbox.io/s/naughty-scooby-ykxiy4

### Steps to reproduce

1. Open the popover
2. Click on the button to make it disappear
3. Try to close the popover by clicking outside

### Chakra UI Version

2.5.0

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by GKosheev** [comment]
@baptisteArno, It seems when you change the state of the `isVisible`, it triggers the component re-render with the loss of focus toward any element, since you can't have a focus on the element which no longer exists. (you can check the current focus using `document.activeElement`). To return focus you can click on `Popover` again so you can close it with an outside click.

You can also use `useRef` hook to retain the focus on `Popover` after changing the state of `isVisible`:

```tsx
const popoverContentRef = React.useRef(null);
...
<PopoverContent ref={popoverContentRef} w="300px" as={Stack} p="4">

{isVisible && (
  <Button
    onClick={() => {
      setIsVisible(false);
      popoverContentRef.current.focus();
    }}
  >
    Click to make it disappear
  </Button>
)}
...

**Comment by baptisteArno** [comment]
Thank you for the info. My app is heavily based on Popovers, and it happens at a lot of places. Is there anything I can do to "lock" the focus? Can `FocusLock` help me in that case?

**Comment by GKosheev** [comment]
@baptisteArno, It's hard to say for now. I'd probably expect it to change the focus from deleted element to the first parent element. I'll investigate how precisely it works with `Popover` as I found some conditions which trigger `onClose`:

```typescript
if (isOpen && closeOnBlur && isValidBlur) {
  onClose()
}
```

Besides that, I know that it's just an example but still, it'd be a better approach to move `as={Stack}` at least from `PopoverContent` to `PopoverBody` to avoid following warnings in the console: 

`Warning: Unknown event handler property onAnimationComplete. It will be ignored`

But I'd use it separately within the `PopoverBody`.

**Comment by baptisteArno** [comment]
The reproduction is just a dumb example.

The same issue arises at several places in my application. Here is another use-case:

https://user-images.githubusercontent.com/16015833/219104399-d0f94888-2337-43b5-b2af-6a0f6116110b.mp4

**Comment by baptisteArno** [comment]
A workaround could be to control the open/close state and implement a simple outside click event listener.

**Comment by GKosheev** [comment]
@baptisteArno, there is a suggestion from the [docs](https://chakra-ui.com/docs/components/popover/usage#trapping-focus-within-popover) to use `react-focus-lock` to trap the focus in particular situations. You might consider using it in your example with the disappearing button. 

I'll investigate further, but, as for now, I don't have any evidence that this is the problem with the `Popover`.

**Comment by anubra266** [comment]
This happens whenever the popover is not focused. Could you change the issue title to this @baptisteArno just so we know we're tracking that here.

**Comment by Inventor77** [comment]
@segunadebayo @anubra266 @GKosheev: If this issue still persists, can I take this up to resolve it?

**Comment by gabriel-unmand** [comment]
this doesn't fix the issue, but if anyone needs it:

a good workaround for this is to use the Chakra UI hook: [use-outside-click](https://chakra-ui.com/docs/hooks/use-outside-click)

sample usage would be:
```
const { isOpen, onToggle, onClose } = useDisclosure()
const popoverRef = useRef(null)
  useOutsideClick({
    ref: popoverRef,
    handler: onClose,
  })
```

```
<Box ref={popoverRef}>
                <Popover autoFocus={false} placement="bottom-start" isOpen={isOpen}>
                ... etc ...
                </>
</>

```

**Comment by j-baldera** [comment]
> this doesn't fix the issue, but if anyone needs it:
> 
> a good workaround for this is to use the Chakra UI hook: [use-outside-click](https://chakra-ui.com/docs/hooks/use-outside-click)
> 
> sample usage would be:
> 
> ```
> const { isOpen, onToggle, onClose } = useDisclosure()
> const popoverRef = useRef(null)
>   useOutsideClick({
>     ref: popoverRef,
>     handler: onClose,
>   })
> ```
> 
> ```
> <Box ref={popoverRef}>
>                 <Popover autoFocus={false} placement="bottom-start" isOpen={isOpen}>
>                 ... etc ...
>                 </>
> </>
> ```

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
