### ISSUE TITLE
Change default colorscheme of Alert based on status

### ISSUE THREAD

**Issue by stiafo** [chakra-ui/chakra-ui#7366]
### Description

Hi,

I'd like for there to be possible to change the color scheme used by components that use a status prop like Alert and Toast. It should be possible to change the default color scheme used when status="error, and a different one for when status="info" etc.

In packages/components/alert/src/alert-context.ts I find that the colorScheme is changed based on the status-prop like this:

```javascript
const STATUSES = {
  info: { icon: InfoIcon, colorScheme: "blue" },
  warning: { icon: WarningIcon, colorScheme: "orange" },
  success: { icon: CheckIcon, colorScheme: "green" },
  error: { icon: WarningIcon, colorScheme: "red" },
  loading: { icon: Spinner, colorScheme: "blue" },
}
```

However I would like to change the default color schema according to my custom brand colors. I tried doing this with `withDefaultColorScheme({ colorScheme: 'red', components: ['Alert']}` but I couldn't get it to work on Alert (but it changed other components like Tag) and I guess it doesn't change the color scheme based on the status-prop like the example above.

### Problem Statement/Justification

When creating a custom design system using Chakra one should also be able to change the defaults of semantic colors like success and warning. This is kind of critical for me an my team and it is annoying and time-consuming having to define colorSchema every time we want to use a component like Alert or Toast. It makes it also more prone to errors and the developed website being in conflict with Universal Design.

### Proposed Solution or API

Ideally one could change the color scheme based on status for all components that use the status prop. E.g one could override the default theme with something like:

```javascript
colorSchemes: {
  info: 'brand.info',
  success: 'brand.success',
  error: 'brand.error'
}
```

This would then change the color scheme for all feedback-related components that use the status prop like Alert and Toast.

### Alternatives

Another solution could be to change the color scheme on a per-component basis. I don't know how this should be implemented, but the Alert could for example have an _info_ selector or something.

```javascript
 const Alert = {
  baseStyle: {
    container: {
      info: {
        bg: 'brand.primary.500',
        borderColor: 'brand.primary.600'
      }
    }
  }
}
```

**Comment by Patrick-Ullrich** [comment]
Not the answer that you are probably looking for, but in my experience colorSchemes aren't very feature rich in chakra and I wasn't ever able to really leverage them within design systems. Great to get you started but lack advanced customizability. 

If this isn't being implemented I would recommend to create your own Alert component that wraps around Chakras Alert Component where you update the variant or Color scheme or whatever you like based on the status.

**Comment by segunadebayo** [comment]
Hi @stiafo,

You can use the solution that @jovanGG suggested.

In the next version, I've added a `data-status` attribute to all the alert parts. You can use that to style the components as needed.

I'll publish a new release pretty soon.

**Comment by uniquelau** [comment]
Useful thread 🙂 For some extra context, to target with `data-status` is simple.
You can use `&[data-status="info"]'`.

![image](https://github.com/chakra-ui/chakra-ui/assets/914735/67859b13-b3e4-4ae7-9214-0a36ae07c40c)

**Comment by ristarr11** [comment]
export const Alert = {
  baseStyle: (props) => ({
    container: {
      bg:
        props.status === 'info'
          ? 'var(--chakra-colors-primary-500)'
          : props.status === 'warning'
            ? 'var(--chakra-colors-semantic-warning)'
            : props.status === 'error'
              ? 'var(--chakra-colors-semantic-error)'
              : 'var(--chakra-colors-semantic-success)',
    },
  }),
};

import { Alert } from './components/alert';
export const theme = extendTheme({
  components: {
    Alert,
  },
});
