### ISSUE TITLE
After setting autoFocus to false Popover not closing on clicking outside

### ISSUE THREAD

**Issue by harshilparmar** [chakra-ui/chakra-ui#7367]
### Description

When I set `autoFocus` prop to false on `Popover` , it is not closing on outside click. And works same as `closeOnBlur` set to false.
Is it intended behavior ? It should not have any effect based on autoFocus , correct ?

### Link to Reproduction

https://codesandbox.io/s/o3j98z?file=/App.tsx&utm_medium=sandpack

### Steps to reproduce

1. Go to sandbox link
2. Click on Trigger button
3. Click outside, here it should close popover
4. set autoFocus to true
5. Now it will work

### Chakra UI Version

2.5.1

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by anubra266** [comment]
Closing in favour of duplicate https://github.com/chakra-ui/chakra-ui/issues/7359
