### ISSUE TITLE
MenuButton don't have isDisabled prop

### ISSUE THREAD

**Issue by GabriPires** [chakra-ui/chakra-ui#7369]
### Description

Greetings! In the project that my team and I are building, we're using the MenuButton component and we have rules to disable it. However, I noticed that by default the MenuButton doesn't receive the isDisabled property, which became the predominant property for the disabled state after updates.

The disabled behavior works normally, but for IntelliSense and TypeScript integration purposes, it would be great if it was possible to access this property in the same way as a regular Button.

I apologize for any lack of explanation at any point, and I'm available to collaborate on understanding if necessary!

### Link to Reproduction

https://codesandbox.io/p/sandbox/chakra-menubutton-test-y8v6ln?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A34%2C%22endLineNumber%22%3A21%2C%22startColumn%22%3A34%2C%22startLineNumber%22%3A21%7D%5D

### Chakra UI Version

2.5.1

### Browser

Firefox 109.1

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by brunorangel1** [comment]
Great question. I'm also waiting to know how to solve this.

**Comment by sciffany** [comment]
I'm new to this repo. Correct me if I'm wrong, seems like adding "as={Button}" solves the issue. Adding "as={Button}" is also the only way to be able to use other Button props, such as rightIcon (or colorScheme, variant, and size).

**Comment by GabriPires** [comment]
> I'm new to this repo. Correct me if I'm wrong, seems like adding "as={Button}" solves the issue. Adding "as={Button}" is also the only way to be able to use other Button props, such as rightIcon (or colorScheme, variant, and size). Do you want MenuButton to have all of these properties too?
> 
> 
> 
> 
Yes, the expected behavior would be that, indeed, however, with the 'isDisabled' property this did not happen, as I mentioned, the behavior still works, but it became somewhat confusing after the update where we used 'isDisabled' instead of 'disabled', since this prop is not recognized in the MenuButton, even though we treat it as a Button.

**Comment by sciffany** [comment]
> since this prop is not recognized in the MenuButton, even though we treat it as a Button. 

Sorry I'm a bit confused because when we treat MenuButton as a Button, isDisabled is a valid property. See that there is no red squiggly under isDisabled.

<img width="313" alt="image" src="https://user-images.githubusercontent.com/10327456/219904475-25bc6bca-dcd4-4a6f-ac07-1257f99077ca.png">

**Comment by anubra266** [comment]
@GabriPires It works as expected in your codesandbox reproduction

<img width="391" alt="CleanShot 2023-02-21 at 01 11 14@2x" src="https://user-images.githubusercontent.com/30869823/220215982-2c1c9ebf-58f2-42bc-a079-f075957553b1.png">

**Comment by penx** [comment]
@anubra266 `as={Button}` seems like a good workaround but I don't think it's a fix, can this be reopened?

I think the _fix_ would be to support the `isDisabled` on MenuButton?

**Comment by szpytfire** [comment]
@anubra266 surely [MenuButtonProps](https://github.com/chakra-ui/chakra-ui/blob/3e1b3f6b6a7398b71ac08339110f075695fbae94/packages/components/menu/src/menu-button.tsx#L7) should be something like `export interface MenuButton props extends ButtonProps {}`.

I say this, because MenuButton uses Button under the hood, and the props that are passed into MenuButton end up [getting spread into Button](https://github.com/chakra-ui/chakra-ui/blob/3e1b3f6b6a7398b71ac08339110f075695fbae94/packages/components/menu/src/menu-button.tsx#L14) anyway

**Comment by szpytfire** [comment]
Actually, I've just closed my PR, as I notice that the props are passed into `chakra.button` (which is imported from system). Therefore, passing in `disabled` to MenuButton is the correct solution.

**Comment by yechielb2000** [comment]
> Actually, I've just closed my PR, as I notice that the props are passed into `chakra.button` (which is imported from system). Therefore, passing in `disabled` to MenuButton is the correct solution.

`disabled` does not work for me.
When i call it like this 
```
<MenuButton disabled as={Button}>some cute name</MenuButton>
```
I still can press this and it opens the menu.

**Comment by mdumakurtas** [comment]
How to disable button?
