### ISSUE TITLE
Question on Best Practices for Theming with Pure CSS

### ISSUE THREAD

**Issue by neilchaudhuri** [chakra-ui/chakra-ui#737]
I have a CSS file generated by TailwindCSS, and I have, naively perhaps, simply been importing it as a CSS Module like this:

import "../../styles/dist/my.css";

And then I use the className prop to apply Tailwind-generated styles to a Chakra UI component. One such style for a text input is w-input-md, which I apply to Chakra's Input.

When I run things in Storybook, the class attribute on this input is class="w-input-md css-cth1sm", and that second class cancels out my class.

I have two questions:

Is there a more sophisticated way I should apply raw CSS?
If I am correct css-cth1sm is a class generated by Chakra UI, how can I disable that?
I know you are all very busy with an imminent release, but a quick response or pointer to documentation I missed is appreciated.

**Comment by dudufigueiredo** [comment]
On Theme-UI they have a theme preset with objects recreating Tailwind default config:

https://github.com/system-ui/theme-ui/blob/master/packages/preset-tailwind/src/index.ts

If you bring it to your theme, [See README.md here](https://github.com/system-ui/theme-ui/tree/master/packages/preset-tailwind), you'll have a much better integrated solution rather the raw css that don't take the advantage of having a Styled Systems based component library.

**Comment by neilchaudhuri** [comment]
This is helpful. Thanks.

I need to read up on how Theme UI works, but if I bring it into the mix, how do I integrate with Chakra UI given that `sx` isn't supported per #579? The thread mentions a `css` function. Is the idea that I can call `css` with `sx` to bring it in?

**Comment by dudufigueiredo** [comment]
I've just noticed that the default theme is Tailwind inspired, regarding the token names and values, if you read there in the docs (https://chakra-ui.com/theme) it might give you enough directions. // The variants and values declared on your Theme object are the variants you use on your elements props... to understand more about theme you should read System UI's Theme Specification.

**Comment by segunadebayo** [comment]
@neilchaudhuri, there's no sophisticated way to convert the tailwind classes to Chakra. You might have to do this manually by passing props to the component.

I understand it's a painful experience. Hopefully, we might be able to make this a lot easier in the future.

Thanks
