### ISSUE TITLE
Chakra ui Modal, keyboard, input, scroll

### ISSUE THREAD

**Issue by PepeIksde** [chakra-ui/chakra-ui#7371]
### Description

I have an issue with scrolling the content within a modal. I am using a Chakra UI modal and when I click on an input field, the keyboard pops up and I am unable to scroll to the end of the modal. Similarly, when I click on the bottom of the modal, I am unable to scroll up. but When I close the keyboard, I am able to scroll the entire content in the modal.

### Link to Reproduction

w

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.5.0

### Browser

Safari

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

https://i.stack.imgur.com/8jQbI.gif

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Looking at the GIF though, this is an issue from the underlying `react-remove-scroll` library we use internally. Kindly open an issue there.

**Comment by Isha988** [comment]
@segunadebayo  I am also facing the same issue, the drawer and modal content hides behind  keyboard in mobiles.

**Comment by antondalgren** [comment]
Same here! 

Content hides behind the keyboard on a mobile device.
