### ISSUE TITLE
Popover fails to close when clicking while using FullCalendar

### ISSUE THREAD

**Issue by trybick** [chakra-ui/chakra-ui#7373]
### Description

I'm using a calendar package called FullCalendar and I noticed an issue where Chakra's Popover doesn't close when clicking inside the calendar. 

### Demo
https://user-images.githubusercontent.com/39889198/219971810-316488ec-b960-4e73-bda4-78c7be226c65.mov

### Link to Reproduction

https://codesandbox.io/s/confident-vaughan-g730m2?file=/src/index.js

### Steps to reproduce

1. Click one of the events on the calendar (see February 2023) to open the popover.
2. Click anywhere inside the calendar, like a different day, and notice the popover is still open.
3. Click anywhere outside the calendar and notice the popover closes.
4. --> Clicking inside the calendar should close the popover. 

### Chakra UI Version

2.5.1

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Not sure how much of this is chakra's fault verse the calendar's. I figure maybe chakra team should look at it because it seems to be failing to detect a click outside the popover. The calendar isn't using an iframe.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
