### ISSUE TITLE
Override `shadowBox` style under `_focusVisible` doesn't work in custom Input theme

### ISSUE THREAD

**Issue by JunlinPan-Crypto** [chakra-ui/chakra-ui#7377]
### Description

When I override default `shadowBox` style of `Input` theme component under `_focusVisible` pseudo class, I expected overriding work, but it didn't. 

### Link to Reproduction

https://codesandbox.io/p/sandbox/modern-flower-irngz7?file=%2Ftheme%2Finput.ts

### Steps to reproduce

1. Custom `Input` theme to override default `boxShadow` under `_focusVisible` pseudo class:
```ts
// theme/input.ts
import { inputAnatomy } from "@chakra-ui/anatomy";
import { createMultiStyleConfigHelpers } from "@chakra-ui/react";

const { definePartsStyle, defineMultiStyleConfig } =
  createMultiStyleConfigHelpers(inputAnatomy.keys);

const baseStyle = definePartsStyle({
  field: {
    // width work
    width: '80%',
    // FIXME: Unset boxShadow doesn't work here
    _focusVisible: {
      boxShadow: "none",
    },
  },
});

export default defineMultiStyleConfig({ baseStyle });
```

2. Use `Input` component and set `border="none"`
```tsx
<Input border="none" />
```

3. Focus input then still see the default blue box shadow, expecting none.
<img width="546" alt="image" src="https://user-images.githubusercontent.com/90383710/220050341-c096c888-cf8b-42ba-a074-ab7e47e31248.png">

4. Inspect the style and force `:focus-visible` state, seeing the default `box-shadow` is still there, but `width` overrode.
<img width="403" alt="image" src="https://user-images.githubusercontent.com/90383710/220050495-d3ed1328-e585-4669-accb-cc120e5ad0fd.png">

### Chakra UI Version

2.5.1

### Browser

Google Chrome 110

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by JunlinPan-Crypto** [comment]
Wrap with `_light` or `_dark` work (but why not default?):

```ts
const baseStyle = definePartsStyle({
  field: {
    // width work
    width: '80%',
    // Wrap with _light or _dark work
    _light: {
      _focusVisible: {
        boxShadow: "none",
      },
    }
  },
});
```

**Comment by segunadebayo** [comment]
Please add the override to the outline variant:

```tsx
const outlineVariant = definePartsStyle({
  field: {
    _focusVisible: {
      boxShadow: "none",
    },
  },
});

export default defineMultiStyleConfig({
  variants: { outline: outlineVariant },
});

```
