### ISSUE TITLE
Figma Design Tokens Plugin

### ISSUE THREAD

**Issue by yarinsa** [chakra-ui/chakra-ui#7381]
### Description

Using FigPilot and Chakra we are almost fully converting Figma -> Code. 

I noticed that the only thing that still needs to be modified by the end developer is the values of the design tokens. 
I know that it's still an RFC, and Figma team said they are working on official support .
But I ran into [Atlassian plugin](https://www.figma.com/community/plugin/1144189860740169808/Atlassian-Design-Tokens) exposing their tokens and allows syncing between the two. 

### Problem Statement/Justification

To provide a full awesome eco-system :) 

### Proposed Solution or API

[Atlassian Plugin](https://www.figma.com/community/plugin/1144189860740169808/Atlassian-Design-Tokens)

### Alternatives

Provide a simple json file to load into the existing generic (and not so great plugin)

### Additional Information

I would be willing to take on the project together with the Chakra team. 
Contact me :)

**Comment by segunadebayo** [comment]
Hey @yarinsa,

Thanks for this suggestion, we're looking to improving the design token support. Should land pretty soon.

We'll keep in touch when we need more hands :)
