### ISSUE TITLE
Tooltip around a switch stays open even when not hovering.

### ISSUE THREAD

**Issue by AHarmlessPyro** [chakra-ui/chakra-ui#7382]
### Description

When hovering over a switch inside a tooltip, even when not hovering, the tooltip stays open. It remains open even when clicking on empty space, and only closes when the value on the switch is changed and then some empty space is clicked.

An example is provided [here](https://play.chakra-ui.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwATFwBUIIAbbJNAGlwGUB3JbMAC1wF9cAzTCFXAOQABVgEMA1plEBaAK5IA9Jhiiw2AQB0AdtpgAPDDlyQtAZzwBBNGlwBeXAAoAlHYB8+bblzLsszFsdPL1wAHmIyChtSUQAjGFJbDRBw8kpcaLjSJNcg4NCGJlZcBRyA4JCFFMjSrydtdm0QdiA)

Adding the `hasArrow` prop to it doesn't seem to matter either. Example for that [here](https://play.chakra-ui.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwATFwBUIIAbbJNAGlwGUB3JbMAC1wF9cAzTCFXAOQABVgEMA1plEBaAK5IA9Jhiiw2AQB0AdtpgAPDDlyQtAZzwBBNGlwBeXAAoAlHYB8+bblzLsszFsdPL1wAHmIyChsWUVMLTF56XFJRACMYUlsNEHDySiTU9KzXIODQhiZWXAVigOCQhRzImq8nbXZtEHYgA).

Sidenote: Since there's a sandbox on chakra-ui.com, maybe allowing links to that would be nice.

### Link to Reproduction

https://codesandbox.io/s/determined-williams-t615gc?file=/src/index.js

### Steps to reproduce

1. Create Tooltip
2. Put a switch inside it
3. Hover on switch
4. Notice that the tooltip stays visible even when mouse is not over the element(s)

### Chakra UI Version

2.5.1 (also seen with 2.2.1)

### Browser

firefox,chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by aysegulkavaklii** [comment]
You can use shouldWrapChildren prop 

<Tooltip label="Tooltip label" shouldWrapChildren>
      <Switch />
    </Tooltip>

**Comment by AHarmlessPyro** [comment]
My apologies. Thanks a lot. I think this solves it.
