### ISSUE TITLE
The same bundle size with ChakraBaseProvider and ChakraProvider

### ISSUE THREAD

**Issue by MiljkovicMarko** [chakra-ui/chakra-ui#7383]
Hi, I just started using ChakraUI and it turned my NextJs app into red bundle size...
I've tried using ChakraBaseProvider as suggested in #4975  but size is the same somehow...
![image](https://user-images.githubusercontent.com/47562747/220421457-0605a348-2e84-44bd-80e2-b0f18729e62d.png)

![image](https://user-images.githubusercontent.com/47562747/220422157-b8411223-ba68-46f3-ad67-1c3ef0bac609.png)

If I comment out the provider and import I get 80kB smaller size in NextJs.

P.S. I've used extendBaseTheme and chakraTheme but in another file where I use them to form theme and using only Button, just like in the example.

**Comment by Patrick-Ullrich** [comment]
The whole base provider change doesn't really drastically reduce the bundle size.

Getting framer motion out of the chakra will help reduce the bundle size but otherwise at this point you are stuck with a larger bundle size.

**Comment by oBusk** [comment]
I was thinking it was probably something with NextJS, so I setup a minimal react/babel/webpack project to try to see if there was any difference in importing `extendBaseTheme` vs `extendTheme()` and `ChakraProvider` vs `ChakraBaseProvider` and I'm definetely not seeing any difference in bundle size however I doi t. Would love to have an example of a setup where the bundlesize actually is reduced.

**Comment by oBusk** [comment]
I've been searching github for anyone using `extendBaseTheme()`, thinking if there's someone who has seen a reduction in bundle size, but only found projects setting up for the first time, opting in to use `extendBasetheme()`. 
Others who has changed from `extendTheme()` to `extendBaseTheme()` seems to similiarly not actually see any differance in bundlesize, see https://github.com/ethereum/ethereum-org-website/pull/9681#issuecomment-1485367779

**Comment by R3flector** [comment]
I tried both providers, found the same bundle size. It's good that this topic exists and did not have to create a new one

**Comment by EvilaMany** [comment]
Same problem

**Comment by corneduring** [comment]
Anyone found a solution yet? I want to only specify the chakra ui components I need up front and only have those component be themed through the theme I pass to the ChakraBaseProvider?

**Comment by MoeAl-khalkhali** [comment]
For anyone still having this issue, this worked for me

import { ChakraProvider } from "@chakra-ui/provider";
Instead of
import { ChakraProvider } from "@chakra-ui/react";

Reduced my bundle size by 137kb

**Comment by segunadebayo** [comment]
I recommend upgrading to the latest version. Then, import the provider from `@chakra-ui/react/provider` instead.

```tsx
// chakra-provider.tsx

import { baseTheme } from "@chakra-ui/theme"
import { Provider } from "@chakra-ui/react/provider"

const ChakraProvider = ({ children }) => {
   return <Provider theme={baseTheme}>{ children }</Provider>
}
```
