### ISSUE TITLE
Issue : : Relate to Range Slider. 

### ISSUE THREAD

**Issue by sayshark75** [chakra-ui/chakra-ui#7390]
### Link to Reproduction

https://codesandbox.io/s/chakra-ui-javascript-lzzg9

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.5.1

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

`<RangeSlider
// aria-label={["min", "max"]}
              defaultValue={[minVal, maxVal]}
              min={0}
              max={4000}
              onChangeEnd={(val) => {
                setMaxVal(val[1]);
              }}
              onChangeStart={(val) => {
                setMinVal(val[0]);
              }}
            >
              <RangeSliderTrack bg="grey">
                <RangeSliderFilledTrack bg="black" />
              </RangeSliderTrack>
              <RangeSliderThumb boxSize={6} index={0}>
                <Box color="black" as={FaStar} />
              </RangeSliderThumb>
              <RangeSliderThumb boxSize={6} index={1}>
                <Box color="black" as={FaStar} />
              </RangeSliderThumb>
            </RangeSlider>`

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Please follow the issue template as we're not able to act on issues that are lacking important information.
