### ISSUE TITLE
Drawer being invisible and opened when moving into pages

### ISSUE THREAD

**Issue by pulgueta** [chakra-ui/chakra-ui#7399]
### Description

I am using a Drawer as a side navbar in my webapp. But when I navigate through pages by clicking the link, it navigates but shows the backdrop of the Drawer and doesn't let me touch anything because shows 'locked', I need to refresh the page to make it work. It happens in both PC and mobile.

Capture: https://prnt.sc/R-Y4Y_-jAdYZ

### Link to Reproduction

https://xochicalli-commerce.firebaseapp.com/admin/add

### Steps to reproduce

Use the mobile view and navigate to whatever page you want

### Chakra UI Version

2.4.9

### Browser

Brave

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by theVedanta** [comment]
Seems to work fine for me

**Comment by jiheon788** [comment]
The same thing happens to me. The code is as follows

```
const onSelect = (name: string) => {
    navigate(`/admin/order?customer=${name}`);
    onClose();
};
```

**Comment by trksprkz** [comment]
Works fine for me, what steps have you taken so far? It'll give us a better idea both of solutions and replication. As it seems for us we're only accessible to the oAuth page.

**Comment by segunadebayo** [comment]
Hi @pulgueta,

You need to close the drawer when the route changes. You can leverage the solution mentioned here:
https://github.com/chakra-ui/chakra-ui/issues/7399#issuecomment-1477616471
