### ISSUE TITLE
Heading does not respond on colorScheme

### ISSUE THREAD

**Issue by StrangersSoftware** [chakra-ui/chakra-ui#7401]
### Description

When I set `colorScheme` it does not applied on text.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-header-00pnl?file=/src/header.js

### Steps to reproduce

1. Go to line 26 on codesandbox link.
2. Set colorScheme with some color for heading.
3. See error

### Chakra UI Version

2.5.1

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Pagebakers** [comment]
colorScheme isn't implemented for the Heading component, you should use `color` instead to change the text color.

**Comment by yzalvov** [comment]
Is it @Pagebakers ?

Chakra docs > [Heading props](https://chakra-ui.com/docs/components/heading/props#props)

<img width="1224" alt="Screenshot 2023-05-01 at 20 18 23" src="https://user-images.githubusercontent.com/25827414/235504926-ac27a6bc-8604-49c5-a155-09e21278e4f0.png">
