### ISSUE TITLE
BreadcrumbItem with isCurrentPage makes it look like a link

### ISSUE THREAD

**Issue by sakimyto** [chakra-ui/chakra-ui#7404]
### Description

BreadcrumbItem with isCurrentPage makes it look like a link.

### Problem Statement/Justification

With isCurrentPage, it becomes `<span>` tag, not `<a>` tag, so `text-decoration: underline` and  `cursor: pointer` on hover is not appropriate?

### Proposed Solution or API

https://github.com/chakra-ui/chakra-ui/blob/bea57af3fc039fce0d1b9ac272cdd65c21fd98e1/packages/components/breadcrumb/src/breadcrumb-link.tsx#L30-L34

Change `styles.link` to one for text, etc.

**Comment by segunadebayo** [comment]
Good catch @sakimyto!

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
