### ISSUE TITLE
Popover z-index

### ISSUE THREAD

**Issue by vitalijalbu** [chakra-ui/chakra-ui#7408]
### Description

The popover doesn't have a specifi z-index.

### Link to Reproduction

https://turo.vercel.app/search

### Steps to reproduce

1. Go to search page
2. Click on some filters buttons

### Chakra UI Version

latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by robcrock** [comment]
@vitalijalbu if you need a quick workaround, it looks like this should work too.

The sibling could be set to `position: relative` and `z-index: -1`
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/35023759/232233068-7bc28d10-012f-4eb8-8321-fb4c979b47d9.png">

**Comment by chasegarner** [comment]
I opened a new PR for this one that includes a changeset for a faster merge.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
