### ISSUE TITLE
compiling error: Can't import the named export 'AnimatePresence' from non EcmaScript module

### ISSUE THREAD

**Issue by denghuiquan** [chakra-ui/chakra-ui#7414]
### Description

when i try to run the demo of the get start page step by step, i get this error tips:
----------
Failed to compile.

./node_modules/@chakra-ui/react/node_modules/@chakra-ui/transition/dist/chunk-3TED3OTR.mjs
Can't import the named export 'AnimatePresence' from non EcmaScript module (only default export is available)
----------
the version of the related packages:
`
    "@chakra-ui/react": "^2.5.1",
    "@chakra-ui/theme": "^2.2.4",
    ...
     "react": "^16.13.1",
`

this happen just when i want to import { ChakraProvider } from '@chakra-ui/react' or import { ChakraBaseProvider } from '@chakra-ui/react'

### Link to Reproduction

https://chakra-ui.com/getting-started/cra-guide#2-provider-setup

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.5.1

### Browser

*

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

<img width="906" alt="image" src="https://user-images.githubusercontent.com/5303970/222442235-05add4a7-bbcf-4db5-8416-45f4baec1647.png">

**Comment by bin0316** [comment]
same problem was happened in my side

**Comment by glaciotech** [comment]
I'm hitting this issue as well. Solved in the past by downgrading framer motion to i think v3.x but having some issues now as chakra requires v4 and above.

**Comment by ian** [comment]
Anyone solved this?

**Comment by sadewole** [comment]
Currently facing this issue.

**Comment by juampirossetti** [comment]
Facing same issue here

**Comment by MuhammadHadiofficial** [comment]
Facing the same issue on fresh install of chakra UI

**Comment by yash-5575** [comment]
Facing the same issue

**Comment by CarlosDurand** [comment]
Same problem here

**Comment by Munter** [comment]
I solved this by updating to framer-motion@5

**Comment by Ankithubnew** [comment]
the same issue is happening with me hope it will get resolved soon in an upcoming update

**Comment by Dinesh10001** [comment]
> This works for me
> 
> ```
> webpackConfig.module.rules.push({
>     test: /\.mjs$/,
>     include: /node_modules/,
>     type: "javascript/auto"
> });
> ```

where to add this code

**Comment by Ankithubnew** [comment]
> the same issue is happening with me hope it will get resolved soon in an upcoming update



> > This works for me
> > ```
> > webpackConfig.module.rules.push({
> >     test: /\.mjs$/,
> >     include: /node_modules/,
> >     type: "javascript/auto"
> > });
> > ```
> 
> where to add this code

I would suggest change the reactscript version to 5.0 it is working for me

**Comment by segunadebayo** [comment]
Kindly update react scripts version to get it working or use the custom webpack config suggestion above to get it working.

**Comment by gtsaroj** [comment]
how to solve this bug ?

**Comment by gtsaroj** [comment]
> > This works for me
> > ```
> > webpackConfig.module.rules.push({
> >     test: /\.mjs$/,
> >     include: /node_modules/,
> >     type: "javascript/auto"
> > });
> > ```
> 
> where to add this code

where we add write this code ?

**Comment by rikprathmesh** [comment]
> same problem was happened in my side

is there any who know how to solve this error

**Comment by Madhur1808** [comment]
> > > This works for me
> > > ```
> > > webpackConfig.module.rules.push({
> > >     test: /\.mjs$/,
> > >     include: /node_modules/,
> > >     type: "javascript/auto"
> > > });
> > > ```
> 
> where we add write this code ? in window

Go inside your node_modules folder then react-scripts->config->webpack.config.js
search for module object inside that there will be a rules array paste this code there as oneOf the rule.
`{
    test: /\.mjs$/,
    include: /node_modules/,
    type: "javascript/auto"
}`

**Comment by ristarr11** [comment]
I have used 
{
test: /\.(mjs)$/,
include: /node_modules/,
type: "javascript/auto"
}
Which has resolved the issues for .mjs files, but chakra 2.8.1 and webpack.config, now give new error only for @zag-js:
./node_modules/@zag-js/dom-query/dist/index.mjs 11:44
  11:44  error  Module parse failed: Unexpected token You may need an appropriate
                loader to handle this file type, currently no loaders are configured to...
                
This is for @zag-js/dom-query, @zag-js/element-size.

Did anyone stumble on this step, perhaps?

**Comment by SubhasmitaLMG** [comment]
Showing error
webpackConfig is not defined
error Command failed with exit code 1.

**Comment by SubhasmitaLMG** [comment]
> > the same issue is happening with me hope it will get resolved soon in an upcoming update
> 
> > > This works for me
> > > ```
> > > webpackConfig.module.rules.push({
> > >     test: /\.mjs$/,
> > >     include: /node_modules/,
> > >     type: "javascript/auto"
> > > });
> > > ```
> > 
> > 
> > where to add this code
> 
> I would suggest change the reactscript version to 5.0 it is working for me

My react-scripts@^5.0.1 is already 5.
But the issue is still the same.

**Comment by msudgh** [comment]
How to fix with Parcel bundler?

**Comment by ruoxiangxin2012** [comment]
> I have used { test: /.(mjs)$/, include: /node_modules/, type: "javascript/auto" } Which has resolved the issues for .mjs files, but chakra 2.8.1 and webpack.config, now give new error only for @zag-js: ./node_modules/@zag-js/dom-query/dist/index.mjs 11:44 11:44 error Module parse failed: Unexpected token You may need an appropriate loader to handle this file type, currently no loaders are configured to...
> 
> This is for @zag-js/dom-query, @zag-js/element-size.
> 
> Did anyone stumble on this step, perhaps?

Has this problem been resolved?

**Comment by nimamogh** [comment]
I observed the same error on chakra-ui @2.8.2. Running

"npm audit fix --force"

in the terminal fixed the issue for me. 

Hope it helps someone!

**Comment by helios-code** [comment]
> I observed the same error on chakra-ui @2.8.2. Running
> 
> "npm audit fix --force"
> 
> in the terminal fixed the issue for me.
> 
> Hope it helps someone!

Works for me !

**Comment by chaitanya1248** [comment]
> This works for me
> 
> ```
> webpackConfig.module.rules.push({
>     test: /\.mjs$/,
>     include: /node_modules/,
>     type: "javascript/auto"
> });
> ```

Thank you for sharing this. I cannot update react-script for various other reasons. This helped me fix the issue. I was wondering what does it actually do?
