### ISSUE TITLE
Menu "closeOnSelect" does not work within Shadow DOM

### ISSUE THREAD

**Issue by oliveiracdz** [chakra-ui/chakra-ui#7419]
### Description

When I set false on `closeOnSelect`, I expect it to keep opened after click.
It works well in normal scenario, but it does not work within shadow DOM. 

### Link to Reproduction

https://codesandbox.io/s/chakra-menu-list-close-on-select-forked-b2ipng

### Steps to reproduce

1. Add a `Menu` component to Shadow DOM;
2. Set `closeOnSelect` to false;
3. Click on an item;
4. See error: the menu is closed.

### Chakra UI Version

2.5.1

### Browser

Google Chrome 110

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Maybe related with [isHtmlElement](https://github.com/chakra-ui/chakra-ui/blob/bea57af3fc039fce0d1b9ac272cdd65c21fd98e1/packages/components/menu/src/use-menu.ts#L817) on [isTargetMenuItem](https://github.com/chakra-ui/chakra-ui/blob/bea57af3fc039fce0d1b9ac272cdd65c21fd98e1/packages/components/menu/src/use-menu.ts#L387)?

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
