### ISSUE TITLE
ComponentStyleConfig not showing suggestions to css properties

### ISSUE THREAD

**Issue by FilipeDexper** [chakra-ui/chakra-ui#7423]
### Description

When I declare a object usign the `ComponentStyleConfig` type, my vscode doesn't show any suggestions for the css properties: 
![Screenshot from 2023-03-06 12-00-08](https://user-images.githubusercontent.com/124596139/223151294-4557160e-3e21-4377-9d31-2fe4962a90f4.png)
![Screenshot from 2023-03-06 12-00-31](https://user-images.githubusercontent.com/124596139/223151318-24df4ac4-9df6-4279-9506-57afec34eb8d.png)

I decided to investigate chakra's typing myself and I actually came to a conclusion. Please note that I'm not an active contributor to chakra's source code, so I have a limited understanding of the  source code, and I may be interpreting  something wrong. That being  said, I tried my best at understanding the typings  and making sure I didn't break something else  in the process. 

I noticed that when I pass a property to a chakra component (e.g color) the auto complete works fine. So I went to the type declarations of the `color` property, which is a `ColorProps.color?: ResponsiveValue<Property.Color | ...100+ more>`

Then I checked what is under the hood of `ComponentStyleConfig`, which is `ComponentSingleStyleConfig | ComponentMultiStyleConfig;`

Both types have a `baseStyle` which can be a `SystemStyleInterpolation` or a `PartsStyleInterpolation` which pretty much end being a `SystemStyleObject`. The `SystemStyleObject`  is a  `RecursiveCSSObject<CSSWithMultiValues>`. 
CSSWithMultipleValues is 
```
interface SystemCSSProperties extends CSS.Properties, Omit<StyleProps, keyof CSS.Properties> {
}
declare type ThemeThunk<T> = T | ((theme: Record<string, any>) => T);
declare type PropertyValue<K extends keyof SystemCSSProperties> = ThemeThunk<ResponsiveValue<boolean | number | string | SystemCSSProperties[K]>>;
declare type CSSWithMultiValues = {
    [K in keyof SystemCSSProperties]?: K extends keyof StyleProps ? StyleProps[K] | PropertyValue<K> : PropertyValue<K>;
};
```
K is a key of SystemCSSProperties which extends `CSS.Properties` (all vanilla css props I presume)  or  `Omit<StyleProps, keyof CSS.Properties>` which takes `StyleProps` and omits the keys of CSS.Properties (because they've already been i ncluded).  `StyleProps` extends `SpaceProps, ColorProps` etc which is exactly what I looked  into at the start of  my journey   ( the color property).  So basically `SystemCSSProperties` is a combination of all default  css properties  + chakra's custom properties (like bg, mx, my , etc.) and  K can be any key of SystemCSSProperties. 

Now, `K extends keyof StyleProps ?` check if K is a key of StyleProps. If it  is, then  the value is `StyleProps[K] | PropertyValue<K>`, otherwise it is just `PropertyValue<K>`

Here lies  my problem, if I'm understanding everything correctly. I think if K is indeed a k ey of   `StyleProps`,  it  should be just `StyleProps[K]`, not  `StyleProps[K] | PropertyValue<K>`. In fact, I edited this file, removing the `| PropertyValue<K>` and  the auto complete started working again. Now my question is, why is the `| PropertyValue<K>` relevant? I removed  it and  apparently it didn't break anything.  If this is indeed the problem, I can create a pull request to fix this issue. Otherwise, please instruct me on how this should be tackled. 

Here is my auto complete working again: 
![Screenshot from 2023-03-06 12-00-20](https://user-images.githubusercontent.com/124596139/223178579-bb451982-01e2-45b1-b513-e752e55f4cc1.png)
![Screenshot from 2023-03-06 12-00-41](https://user-images.githubusercontent.com/124596139/223178625-0b4b8187-0065-43f5-8f5e-da15f80585e9.png)

### Link to Reproduction

https://github.com/FilipePfluck/chakra-typing-example

### Steps to reproduce

1. Clone this repo and install the dependencies: https://github.com/FilipePfluck/chakra-typing-example
2. Go to the empty string and press control + space to get the suggestions
3. Notice how there aren't any suggestion

### Chakra UI Version

^2.2.1

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by Pagebakers** [comment]
Can you try using the `defineStyle()` or `defineStyleConfig` helper functions?

```ts
const styleObj = defineStyleConfig({
  baseStyle: {
    bg: 'white'
  },
  variants: {
    blue: defineStyle({
      bg: 'blue'
    })
  }
})
```

Also make sure you generate the theme typings.

**Comment by FilipeDexper** [comment]
@Pagebakers sorry for taking so long to respond. Using `defineStyleConfig` or `defineStyle` had the same problem with the `ComponentStyleConfig`. And yes, I generated the theme typings with chakra-cli

**Comment by segunadebayo** [comment]
Closing based on https://github.com/chakra-ui/chakra-ui/issues/7423#issuecomment-1457021065
