### ISSUE TITLE
The accordion item remains open when the data was changed

### ISSUE THREAD

**Issue by romadryud** [chakra-ui/chakra-ui#7425]
### Description

The accordion item remains open when the data was changed. I think if there is new data, it must close all the items that are open.

### Link to Reproduction

Bug_2160 in Accordion storybook

### Steps to reproduce

https://user-images.githubusercontent.com/19193036/223297052-e4b3fe7f-167e-4fca-88a1-e8d3d7e31fd1.mov

1. Open storybook
2. Find Accordion
3. Open the first item
4. Input a

### Chakra UI Version

2.5.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
In this scenario, you want to control the accordion's selected index and clear the value on change.

It's more challenging to figure that out internally within the components.

![CleanShot 2023-03-18 at 17 09 19@2x](https://user-images.githubusercontent.com/6916170/226122155-5dbc1aa2-1cbc-426c-b4ed-da47f707c3a7.png)
