### ISSUE TITLE
Divider margin and padding not applied correctly 

### ISSUE THREAD

**Issue by vva-fyayc** [chakra-ui/chakra-ui#7430]
### Description

When using a <Divider /> component and you add padding top or bottom, same for margin top or bottom they don't get applied correctly.

### Link to Reproduction

https://play.chakra-ui.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwATFwCEIAPAGlwBEkA3JWTXAX1wDNMIVcByAATAAWAQwDWmIQFoArkgD0mGELDZuAHQB2GmCQw5ckdQGc8AQTRpcAXlwAKAJRWAfPg25cC7FMzrbAHmIkjhq+1HQMuCjYlqogAIwADGgkMREARtEgAEyJySC4skHqvrIBjnYaTCBMQA

### Steps to reproduce

If you have a 

<Box>
<Divider mt="10px" mb="20px" />
</Box>

The Box should end up 30px tall, but we get 1px

### Chakra UI Version

2.5.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by santhosh-john** [comment]
@vva-fyayc: This is working correctly. Please try adding an outline/border surrounding your Box to see the effect. Also, please have a look at my example which explains the same: https://play.chakra-ui.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwATFwCEIAPAGlwBEkA3JWTCgFRhLwF9cAzTCFXAOQABMAAsAhgGtM4gLQBXJAHpMMcWGwCAOgDtdrDDlyQdAZzwBBNGlwBeXAAoAlHYB8+Xblyrs8zDsdPL1wAHlcg4NCWNldCGAAbCAB3WSJSXCSkbFFcFHFMAHMkAIgA7JhcKFp6GEwQpWjscIDI0OISXAAjLAZbLRAARjQO0wh4+m8YKH7m1uCQ6joGXOw+wYAGYf7czrWAJk2Sbe7MXv6hjqgIbGwpyemQXCVZ1vr25pDOzCeXyJDG2IJZKpdoZLI5NDiKBVHQFXClXDlSrVBj1AEReagk5nQbDXCjcZQLrxeQwGYYv6LGrfNCrc6HbZoXb0raPToFNYFVQwHQAOgALOt1ttnhT5gCmKIkKZcNLEaIKrc2LKzDV5RVuh1xFxbt8kVUlrU0awmmK3qRfqFRS0nLp2LoQOwgA

If I got @vva-fyayc's question correctly, then; this could be closed, @segunadebayo.
