### ISSUE TITLE
First letter pseudo selector

### ISSUE THREAD

**Issue by isBatak** [chakra-ui/chakra-ui#7431]
### Description

It would be nice to have a built-in support for `::first-letter` pseudo selector.

### Problem Statement/Justification

Currently we have to use `sx` like this
```
<Box sx={{ '::first-letter': { textDecoration: 'underline' } }}>Some text</Box>
```
https://play.chakra-ui.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwATFwCEIAPXAX1wDNMIVcByAATAAsBDAa03YFoBXJAHpMMdmGwMAOgDtZMEhhy5IMgM54AgmjS4AvLgAUASn0A+fLNy5R2fphm4APMTJqSe4AQbx4VJJgavAA2MNjYMJg++LgRJNgAIjCQPNhIEDLwjPwysJjBSDIwDBQU5GYAynQwsQrYTkKuZrLkIORAA

### Proposed Solution or API

Add `_firstLetter` pseudo selector
```
<Box _firstLetter={{ textDecoration: 'underline' }}>Some text</Box>
```

**Comment by nimpossible** [comment]
@isBatak: This looks like a custom need. Though a bit hacky, we are using the `sx` prop for using all pseudo selectors, CSS' custom properties, etc. If we were to make an addition of this prop, it will pollute the way Chakra-UI is currently defining the props/prop-names. Also, we have to keep adding such custom props for other pseudo selectors too which doesn't add much benefit now considering other priorities. @segunadebayo, what's your thoughts on this?

**Comment by isBatak** [comment]
@nimpossible it's basically one line of code https://github.com/chakra-ui/chakra-ui/pull/7441/files.
But I agree, If it doesn't make sense and it's a rare use-case then I'm fine with this decision.

**Comment by santhosh-john** [comment]
Thanks for your understanding @isBatak. In that case this ticket could be closed, @segunadebayo.
