### ISSUE TITLE
[bug] use-controllable  when value is string ,cause  loop 

### ISSUE THREAD

**Issue by vaynevayne** [chakra-ui/chakra-ui#7436]
### Description

when i reset _list in useDidupdate, the child component loop render,

i hard to reproduce it, He is normal in demo, but in my application, he has bug, 
i  tried to paste my application code into the sandbox a little bit, but there were no bugs,

in use-controllable, replace useCallbackRef to useCallback, it works well 
`const setValue = useCallback(`

### Link to Reproduction

https://codesandbox.io/s/inspiring-panna-l9ro2c?file=/src/Child.tsx

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I'm sorry but we don't understand the problem you are reporting.

Please provide a repository or CodeSandbox reproducing this problem, and describe the difference between the expected and current behavior.
