### ISSUE TITLE
Object.fromEntries is not a function

### ISSUE THREAD

**Issue by iamdreo** [chakra-ui/chakra-ui#7437]
### Description

The SemanticTokenEntries code gives an error on older browsers ` const semanticTokenEntries = Object.entries(flatten(semanticTokens, 1) ?? {}).map(([token, value]) => {
    const enhancedToken = { isSemantic: true, value };
    return [token, enhancedToken];
  });
  return Object.fromEntries([
    ...tokenEntries,
    ...semanticTokenEntries
  ]);
}` 

I'm guessing cause Object.fromEntries is not supported by older browsers

### Link to Reproduction

No Link

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.3.4

### Browser

Chrome Mobile 72.0.3626

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Android 9

**Comment by segunadebayo** [comment]
Hi @iamdreo,

I don't know what framework you use with Chakra. Next.js? Custom Setup?

Kindly use a JS polyfill to support the newer JS features we use in the codebase.
