### ISSUE TITLE
About the spacing prop of the <Stack>

### ISSUE THREAD

**Issue by fatihcaen** [chakra-ui/chakra-ui#744]
Hi there. I'm having a great experience with Chakra. First of all, thanks to all the contributors. My problem is, "spacing" prop of Stack doesn't apply to its component children unless I put them in a Box. Here is a screenshot:
![image](https://user-images.githubusercontent.com/54099904/82538567-9c4be880-9b54-11ea-9834-1b0bea92931a.png)
So above, the spacing of 2, doesn't apply to the components that I'm putting as props inside the Stack. But it works when:
![image](https://user-images.githubusercontent.com/54099904/82538659-bd143e00-9b54-11ea-8f72-39839e9d3cc4.png)
I put the component in a Box like this and I believe it's not a good practice.

**Comment by sanderfish** [comment]
While it feels more like a workaround than a solution — have you tried using the `shouldWrapChildren` prop?

**Comment by fatihcaen** [comment]
> 
> 
> While it feels more like a workaround than a solution — have you tried using the `shouldWrapChildren` prop on the `Stack` component?

It works now. Thank you. Well, I guess it's a solution because this is why the `shouldWrapChildren` prop is created in the first place, I guess.

**Comment by segunadebayo** [comment]
Hi @fatihcaen, I believe this has been resolved so I'm going to close this out.

**Comment by PSalaun** [comment]
@fatihcaen if your `UserSection` component's wrapper is a Chakra component (Box or Flex for instance), then normally you just need to spread props, like this:

```javascript
const UserSection = (props) => {
  const { owner, ...otherProps } = props;
  return (
    <Box {...otherProps}>
       ...
    </Box>
  );
};
```
So it can "receive" the margin value that the `Stack` component is passing to its children.

**Comment by aaronmcadam** [comment]
@PSalaun Luckily, we won't have to do that in the new version because we use CSS sibling selectors to set the spacing instead.
