### ISSUE TITLE
Allow responsive value for "placement" in the Drawer component

### ISSUE THREAD

**Issue by feyi-tech** [chakra-ui/chakra-ui#7440]
### Description

I realised the Drawer component doesn't support responsive placement attribute.

I needed to show the drawer on the left on breakpoint >= $md and have it display on the bottom at breakpoint == $base, 
but the the drawer seems to default the layout to the left placement because of the responsive value.

### Problem Statement/Justification

Imagine having comments on a post or live video appear in the Drawer component on the right or left side of a desktop device while having same comments displayed in the drawer at the bottom of the screen like Youtube comments view on a mobile device.

### Proposed Solution or API

<Drawer placement={{base: "bottom", md: "left"}}/>

**Comment by segunadebayo** [comment]
Hi @feyi-tech,

Consider using two different drawers (one for mobile, another for >= md), or use the `useBreakpointValue` hook: https://chakra-ui.com/docs/hooks/use-breakpoint-value

**Comment by feyi-tech** [comment]
Thanks boda segun! Segun seege. Oko maamee.
