### ISSUE TITLE
using grid on small screen flex on large screen

### ISSUE THREAD

**Issue by zakidze** [chakra-ui/chakra-ui#7443]
### Description

i went to a case when i have to use gird on lg screen and flex on small screen or at least disable the grid on small screen however i dint find that in chakra

### Problem Statement/Justification

more flexibility on chakra

### Proposed Solution or API

none

**Comment by anubra266** [comment]
```
display={{ sm:"flex", lg:"grid" }}
```

**Comment by zakidze** [comment]
awosome but can you do it with grid component and flex component
