### ISSUE TITLE
types missing for defaultProps using defineMultiStyleConfig/createMultiStyleConfigHelpers

### ISSUE THREAD

**Issue by HendrickSamuel** [chakra-ui/chakra-ui#7444]
### Description

When I define `defineMultiStyleConfig ` for the modal component following [the documentation](https://chakra-ui.com/docs/components/modal/theming#changing-the-default-properties). 

I expect to be able to set all the `defaultProps` for the Modal component to have it enabled application wide. 

But doing the following:
```ts
import { modalAnatomy } from "@chakra-ui/anatomy";
import { createMultiStyleConfigHelpers, extendTheme } from "@chakra-ui/react";

const { defineMultiStyleConfig } = createMultiStyleConfigHelpers(
  modalAnatomy.keys
);

const modalTheme = defineMultiStyleConfig({
  defaultProps: {
    isCentered: true
  }
});
``` 
raises a typescript error: 
`Type '{ isCentered: true; }' is not assignable to type '{ size?: string | number | undefined; variant?: string | number | undefined; colorScheme?: string | undefined; }'.`

My actual workaround is telling typescript to expect en error
```ts
const modalTheme = defineMultiStyleConfig({
  defaultProps: {
    //@ts-expect-error - defaultProps is not extendable but the value is accepted
    isCentered: true
  }
});
```

Is there a way to extend `defaultProps` type when using `defineMultiStyleConfig` ? 

Note: 
setting `isCentered` actually works but is not accepted by typescript. 

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-multi-style-config-typing-767gys

### Steps to reproduce

1. Go to '/src/theme.ts'
2. See error

### Chakra UI Version

2.5.1

### Additional Information

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/57829885/224717668-fcee648b-ad96-4e1e-ad5b-940a26d6f9c0.png">

**Comment by segunadebayo** [comment]
Hi @HendrickSamuel,

I understand the intent, but the approach can be improved slightly.

How about creating a dedicated `CenteredModal` component that wraps the default Chakra Modal and sets that property? This is the most declarative and clear approach.

```jsx
const CenteredModal = (props: Omit<ModalProps, "isCentered">) => <Modal { ...props} isCentered />
```

Getting the types working for `defineMultiStyleConfig` and the helpers will end up more work than necessary. I prefer to avoid this as much as possible.
