### ISSUE TITLE
HTML invalid markup for NumberInput

### ISSUE THREAD

**Issue by MashaSinkevich** [chakra-ui/chakra-ui#7454]
### Description

**WHEN** 
I copy markup from https://chakra-ui.com/docs/components/number-input
**AND**
past it into https://validator.w3.org/ (validate by Direct Input)
**THEN** 
I expect that there will be no errors
but now there is an error:
`Error: Attribute autocorrect not allowed on element [input](https://html.spec.whatwg.org/multipage/#the-input-element) at this point.`

I was checking the following markup:

```
<!DOCTYPE html>
<html lang="en"><head><title>test</title></head><body>


<div class="chakra-numberinput css-3e5t3k"><input inputmode="decimal" type="text" pattern="[0-9]*(.[0-9]+)?" role="spinbutton" aria-valuemin="10" aria-valuemax="20" aria-valuenow="15" aria-valuetext="15" autocomplete="off" autocorrect="off" class="chakra-numberinput__field css-dphgai" value="15"><div aria-hidden="true" class="css-1jj9yua"><div role="button" tabindex="-1" class="css-1m5jnul"><svg viewBox="0 0 24 24" focusable="false" class="chakra-icon css-onkibi"><path fill="currentColor" d="M12.8,5.4c-0.377-0.504-1.223-0.504-1.6,0l-9,12c-0.228,0.303-0.264,0.708-0.095,1.047 C2.275,18.786,2.621,19,3,19h18c0.379,0,0.725-0.214,0.895-0.553c0.169-0.339,0.133-0.744-0.095-1.047L12.8,5.4z"></path></svg></div><div role="button" tabindex="-1" class="css-1m5jnul"><svg viewBox="0 0 24 24" focusable="false" class="chakra-icon css-onkibi"><path fill="currentColor" d="M21,5H3C2.621,5,2.275,5.214,2.105,5.553C1.937,5.892,1.973,6.297,2.2,6.6l9,12 c0.188,0.252,0.485,0.4,0.8,0.4s0.611-0.148,0.8-0.4l9-12c0.228-0.303,0.264-0.708,0.095-1.047C21.725,5.214,21.379,5,21,5z"></path></svg></div></div></div>


</body></html>

```

**To meet accessibility criteria "A" all HTML markup should be valid (see https://www.w3.org/WAI/WCAG21/quickref/#parsing).**

**Comment by segunadebayo** [comment]
`autocorrect` is a non-standard attribute; that's why the validator throws. However, it works in Safari

<img width="806" alt="CleanShot 2023-03-18 at 17 17 49@2x" src="https://user-images.githubusercontent.com/6916170/226122633-516ab21c-1cfa-4d72-bd9f-27862feaead9.png">

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#non-standard_attributes
