### ISSUE TITLE
`AccordionPanel` height is not updated in specific situations

### ISSUE THREAD

**Issue by todesking** [chakra-ui/chakra-ui#7463]
### Description

When `<AccordionItem>` is opened at mount time(either via the `defaultIndex` or `index` prop), and its content is changed later, we expect the `<AccordionItem>` height to adjust accordingly.
However, in reality, the height remains the same as it was mount time.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-accordion-height-bug-ub776d?file=/src/index.tsx

### Steps to reproduce

1. Create `<Accordion defaultIndex={[0]}>` with some `<AccordionItem>`s.
2. Change contents in `<AccordionItem>`
3. The `<AccordionItem>`'s height is not changed.

### Chakra UI Version

2.5.2

### Browser

Google Chrome Version 111.0.5563.64 (Official Build) (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Workaround: At mount time, close all `<AccordionItem>`s, then open it later.
(See `Accordion2` in CodeSandbox)

**Comment by pyummm** [comment]
https://user-images.githubusercontent.com/26200410/226187617-62b98a53-ea5b-43e6-9c69-e58cabc7fc6f.mov

Confirm problem, here video of my case
