### ISSUE TITLE
Question: How do I unset auto height for img tags?

### ISSUE THREAD

**Issue by paambaati** [chakra-ui/chakra-ui#747]
I want to turn off the `height: auto` rule for `img` tags. I can see that `preflight` is setting the style, but I can't seem to customize it.

#### What I've tried
1. Passing in a `css` prop to the `<CSSReset>` component setting `img { height: unset; }`.

2. Passing in a `style` prop to the `<Image>` component with `{{height: unset}}`.

3. Setting explicit `htmlWidth` and `htmlHeight` props to the `<Image>` component.

None of these work. Is there a quick workaround to unset the `auto` height?

**Comment by segunadebayo** [comment]
@paambaati, you can use the `<Global/>` component from "@emotion/core" to achieve this.

At the root of your application, import the Global component, and write the custom styles to override the CSSReset styles.

Hope this helps

**Comment by aaronmcadam** [comment]
@paambaati Here's an example of how to use `Global` to override the reset styles: https://gist.github.com/aaronmcadam/3659dc8fec1bf03d2cc57fb900dc75d4

**Comment by paambaati** [comment]
@aaronmcadam Thank you so much!

**Comment by aaronmcadam** [comment]
No worries @paambaati. I think we should add my gist to the Recipes on the docs site @segunadebayo
