### ISSUE TITLE
Toast doesn't pass `colorScheme` prop to Alert

### ISSUE THREAD

**Issue by mitsuru-kasai** [chakra-ui/chakra-ui#7472]
### Description

# As template
- When I give `colorScheme` prop to ~Toast~ `useToast` without `render` prop
- I Expected Toast render `Alert` and  pass `colorScheme` to it
- but Toast doesn't pass `colorScheme` to `Alert`

### Link to Reproduction

https://codesandbox.io/s/quirky-lichterman-f3n3w8

### Steps to reproduce

Click the button in the Code Sandbox

### Chakra UI Version

2.5.2

### Browser

Chrome 110.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Thank you all developers,
I love ChakraUI!

I think the cause is that `colorScheme` prop doesn't be passed here 

https://github.com/chakra-ui/chakra-ui/blob/76a9cc02c06bf971f5f3300ed271a4deba19160c/packages/components/toast/src/toast.tsx#L27

**Comment by hectoraldairah** [comment]
Where the `colorScheme` prop is defined for Chakra?
The Toast component is just a composable component of <Alerts /> and `colorScheme `is not a prop of any of them

**Comment by mitsuru-kasai** [comment]
Thank you @hectoraldairah.

Sorry my explanation was not precise.

Precisely, I don't tried to pass `colorScheme` directory to the `Toast` component, but to `useToast()`.

`UseToastOptions` (the type of parameter of `useToast` ) [extends `ThemingProps<"Alert">`](https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/toast/src/use-toast.tsx#L9) and I think `ThemingProps` contains `colorScheme`.

**Comment by mitsuru-kasai** [comment]
It looks that  the Props of `Toast` Component also contains `colorScheme` because it extends `UseToastOptions`.

**Comment by hectoraldairah** [comment]
Yes! Thank you for the clarification.
[I made this PR](https://github.com/chakra-ui/chakra-ui/pull/7481) that solves the issue

**Comment by mitsuru-kasai** [comment]
@hectoraldairah 
Awesome!

Thank you for your quick fix!

**Comment by segunadebayo** [comment]
Merged your PR @hectoraldairah.

Thank you!
