### ISSUE TITLE
Allow tabs to be set by unique key, not index

### ISSUE THREAD

**Issue by mellis481** [chakra-ui/chakra-ui#7473]
### Description

**Relogging issue #6014 because the maintainer advised it would be addressed in the next major release almost a year ago, but it was not.**

Only allowing Tabs to be set by index requires consumers to manage indexes in situations where they need to programmatically set tabs AND one or more tabs are rendered conditionally.

### Problem Statement/Justification

Here is an example of what happens when a tab is conditionally rendered and a tab needs to be selected programmatically if I don't manage the indexes on my own:

```function ControlledExample() {
  const [tabIndex, setTabIndex] = React.useState(0)
  const [isTabTwoHidden, setIsTabTwoHidden] = React.useState(false)

  const handleButton0Click = () => setTabIndex(0);  
  const handleButton1Click = () => setTabIndex(1);  
  const handleButton2Click = () => setTabIndex(2);  
  const handleButton3Click = () => setIsTabTwoHidden(!isTabTwoHidden);
  const handleTabsChange = (index) => setTabIndex(index);

  return (
    <Box>
      <button 
        onClick={handleButton0Click} 
        style={{border:'1px solid black',padding:'5px'}}>Select tab with index 0</button>
      <button 
        onClick={handleButton1Click} 
        style={{border:'1px solid black',padding:'5px'}}>Select tab with index 1</button>
      <button 
        onClick={handleButton2Click}
        style={{border:'1px solid black',padding:'5px'}}>Select tab with index 2</button>
      <button 
        onClick={handleButton3Click} 
        style={{border:'1px solid black',padding:'5px'}}>{isTabTwoHidden ? 'Show' : 'Hide'} tab "Two"</button>
      <Tabs index={tabIndex} onChange={handleTabsChange}>
        <TabList>
          <Tab>One</Tab>
          {!isTabTwoHidden && <Tab>Two</Tab>}
          <Tab>Three</Tab>
        </TabList>
        <TabPanels>
          <TabPanel>
            <p>Click the tabs or pull the slider around</p>
          </TabPanel>
          {!isTabTwoHidden && (
            <TabPanel>
              <p>Yeah yeah. What's up?</p>
            </TabPanel>
          )}
          <TabPanel>
            <p>Oh, hello there.</p>
          </TabPanel>
        </TabPanels>
      </Tabs>
    </Box>
  )
}
```

When tab "Two" is enabled, it's index is 1 and I can programmatically select it using the React hook and index 1.

When tab "Two" is disabled, tab "Three" is the tab with an index of 1 and and when I programmatically set index 1 using the React hook, it selects tab "Three".

It would be great if you could specify the tab you want to select directly by a id/key rather than indirectly by index.

### Proposed Solution or API

Add a `key` property to the `<Tab>` component and have `<Tabs>` use a `selectedKey` prop to determine selection. It seems like this could be used as an alternative to `index` (ie. have both conventions available).

**Comment by mellis481** [comment]
@segunadebayo You said the functionality describe in this issue would be included in v2 which was released a year ago. It wasn't. My team needs this functionality. Can you please just say whether or not there are plans for `@chakra-ui/tabs` to include using a key/id (rather an index) to manage the active tab so I can decide whether or not we should move away from `@chakra-ui/tabs`?

**Comment by Killouis** [comment]
Any news?

**Comment by segunadebayo** [comment]
Sorry to disappoint. This is now landed in Chakra v3 instead.
