### ISSUE TITLE
@chakra-ui/next-js variant props not available

### ISSUE THREAD

**Issue by quentingirard** [chakra-ui/chakra-ui#7474]
### Description

Hello !

I was migrating my custom link implementation to the new link for Next.js that you provided and **variant** seems not available

### Link to Reproduction

https://github.com/Wavemind/medal-creator/tree/feature/dump-chakra

### Chakra UI Version

2.5.2

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

@chakra-ui/react 2.5.2
@chakra-ui/next-js: 2.0.1

![variant](https://user-images.githubusercontent.com/15869493/226662964-bf5d9ab9-4025-4552-890c-d9ec1b83c9b9.png)

**Comment by segunadebayo** [comment]
Good catch @quentingirard.

Just pushed a fix for this. We'll release an update shortly.
