### ISSUE TITLE
EditableTextarea adjust height

### ISSUE THREAD

**Issue by numbing** [chakra-ui/chakra-ui#7478]
### Description

using EditableTextarea i need to it keep the height of EditablePreview and dont get smaller or bigger than that

### Problem Statement/Justification

when user click on a big text on EditablePreview and want to edit it, suddenly the text area become smaller

### Proposed Solution or API

<EditableTextarea
             heigh="auto"
                />

**Comment by segunadebayo** [comment]
This is not supported in the editable component. Consider using https://www.npmjs.com/package/react-textarea-autosize with a custom editable hook instead
