### ISSUE TITLE
Responsive Styles not working with Codesandbox

### ISSUE THREAD

**Issue by nwazuo** [chakra-ui/chakra-ui#748]
I've been working with Chakra-UI for a while and it's been awesome. Just recently I was trying to use Chakra-UI for a demo project on [codesandbox](codesandbox.io) and noticed that declaring different style values for a certain breakpoint on my components don't work. 

In the example below, the browser picks the 'base' style on all screen sizes. This only happens when I use codesandbox. On my local environment and heroku, there's no such problem. 

`    <Box maxWidth={{md: "50vw", base: "90%" }} mx="auto">
      <Text>Some text</Text>
 </Box>
`

I even tried copying the example on the [Responsive Styles page](https://chakra-ui.com/responsive-styles) but I still get the same outcome where responsiveness doesn't work.

**Comment by nwazuo** [comment]
Never Mind. I forgot to wrap my app with the `<ThemeProvider>` wrapper.

**Comment by with-heart** [comment]
That'll do it!

1.0 will report an error if you haven't wrapped with `ThemeProvider`/`theme` :)

**Comment by nwazuo** [comment]
Never Mind. I forgot to wrap my app with the `<ThemeProvider>` wrapper.
