### ISSUE TITLE
Multiple instances of @emotion/react loaded - Vite Framework

### ISSUE THREAD

**Issue by sophonaroap** [chakra-ui/chakra-ui#7480]
### Description

When adding `ChakraProvider` to `main.tsx` of a Vite project (unsure if this effects other frameworks), this error occurs in the browser console:
```
You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.
```
When running `npm ls @emotion/react` I receive this output:
```
project-name-client@0.0.0 /Users/my-name/projects/project-name/client
├─┬ @chakra-ui/react@2.5.2
│ ├─┬ @chakra-ui/css-reset@2.0.13
│ │ └── @emotion/react@11.10.6 deduped
│ ├─┬ @chakra-ui/provider@2.1.3
│ │ └── @emotion/react@11.10.6 deduped
│ ├─┬ @chakra-ui/system@2.5.2
│ │ └── @emotion/react@11.10.6 deduped
│ └── @emotion/react@11.10.6 deduped
├── @emotion/react@11.10.6
└─┬ @emotion/styled@11.10.6
  └── @emotion/react@11.10.6 deduped
```

Deleting `node_modules` and `package-lock.json` and re-running `npm i` does not resolve this issue. 

As far as I am aware, this is a relatively new issue, as I have a previous Chakra project that does not have this issue. 

Seems like a peer-dependency issue. 

### Link to Reproduction

https://codesandbox.io/p/github/codesandbox/codesandbox-template-vite-react/main?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522cl5s649nx000alngf2w2wgcbr%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fpackage.json%2522%252C%2522%252Fsrc%252Fmain.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clfk2aejl00153b6ix7b3kwlx%2522%253A%257B%2522key%2522%253A%2522clfk2aejl00153b6ix7b3kwlx%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522yarn%2520dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522clfk2aejl00163b6ievrzdetp%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clfk2aejl00153b6ix7b3kwlx%2522%252C%2522spacesOrder%2522%253A%255B%2522clfk2aejl00153b6ix7b3kwlx%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D

### Steps to reproduce

1. Run npm ls @emotion/react
2. See deduped packages
3. This can cause an error

### Chakra UI Version

2.5.2

### Browser

Google Chrome 111.0.5563.64

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by xurxe** [comment]
Same problem! Would love a solution...

**Comment by sophonaroap** [comment]
> Same problem! Would love a solution...

I actually figured this one out and it was totally unrelated to Chakra.

I use a Jetbrains IDE, so when I need to import something I just do a quick little keyboard shortcut. HOWEVER sometimes I would type the shortcut before the IDE had the chance to load. What was happening was instead of importing what I thought I was, like a <Button> for example, it was actually importing `React from 'react'`, which is what was causing the issue.
