### ISSUE TITLE
initialFocusRef is not working

### ISSUE THREAD

**Issue by drourke-dev** [chakra-ui/chakra-ui#7483]
### Description

In the example shown on the docs [here](https://chakra-ui.com/docs/components/popover/usage#focus-an-element-when-popover-opens), the "Next" button should be focused initially but it is not. This is also the case for modals. 

### Link to Reproduction

https://codesandbox.io/s/initialfocusref-bug-e4tscq

### Steps to reproduce

1. Go to https://codesandbox.io/s/initialfocusref-bug-e4tscq
2. Click on "Open Modal"
3. "Close" does not receive focus

### Chakra UI Version

2.4.9

### Browser

Version 111.0.5563.110 (Official Build) (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
As shown in the video, the Close button actually receives focus as expected. It just doesn't "show" focus (I mean the outline you might expect to see). If you want to see the focus outline, you can interact with your keyboard.

https://user-images.githubusercontent.com/6916170/227203981-d0fd2360-b15d-4e61-aee0-b33a1a1bf696.mp4

**Comment by drourke-dev** [comment]
Thanks for the speedy response @segunadebayo, I see now that the Button's use `:focus-visible` styles and not `:focus`. I should have checked this first before reporting a bug.
