### ISSUE TITLE
Tag Color Schemes disappeared

### ISSUE THREAD

**Issue by jonahallibone** [chakra-ui/chakra-ui#7485]
### Description

When using `Tag` and `TagLabel`, no colors are present. I am presented with a transparent background and black text

<img width="544" alt="Screenshot 2023-03-23 at 11 26 29 AM" src="https://user-images.githubusercontent.com/8886318/227252536-a79746ab-7d0c-40c6-b6ed-6a0389820bb9.png">

### Link to Reproduction

(I can make another repro because Codesandbox seems to have deleted this one or something).
https://codesandbox.io/s/vigorous-wood-ztp1li?file=/pages/index.tsx

### Steps to reproduce

1. Set up a project
2. Add a tag and a tag label
3. Observe no colors

### Chakra UI Version

2.5.2, 2.5.3

### Browser

Chrome 111

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This issue appeared in 2.5.2, and persists in 2.5.3 I assume it's a tokenization issue.

**Comment by jonahallibone** [comment]
Just poking around a little more

https://github.com/chakra-ui/chakra-ui/blob/b39e242adc60798a8ce40c34805cb19d80d05524/packages/components/theme/src/components/badge.ts#LL36C3-L36C3

It seems like the colors are being set to a css variable but then never actually set the a CSS props (like boxShadow, background or color). The browser more or less confirms this:

<img width="327" alt="Screenshot 2023-03-23 at 12 06 45 PM" src="https://user-images.githubusercontent.com/8886318/227264645-b4fb6179-2ad7-45e6-a181-fca8441cc190.png">


Where can see the colors that should be set to `box-shadow` and `color` simply being defined as variables and then not applied to any CSS props.

**Comment by hectoraldairah** [comment]
Yes, you're right @jonahallibone. Idk why the CSS variables are there but the Tag component doesn't read the value. 
It's kinda weird that (the same CSS variables as you said) in the [official Chakra docs](https://chakra-ui.com/docs/components/tag) those values are working fine. 

I made this [PR](https://github.com/chakra-ui/chakra-ui/pull/7488) that solves it by reading the variables for the badge component.
