### ISSUE TITLE
withDefaultVariant's variant parameter is typed as any

### ISSUE THREAD

**Issue by Kalo0m** [chakra-ui/chakra-ui#7486]
### Description

When I've used withDefaultVariant to select a default variant for my button I expected to have autocompletion with my Buttons' variants but the variant parameter was typed as `any` 

### Link to Reproduction

https://codesandbox.io/s/condescending-brook-8ojw3w?file=/index.tsx:293-296

### Steps to reproduce

```ts
  withDefaultVariant({
    variant: "foo", // it's any!!!
    components: ["Button"]
  })
  ```

### Chakra UI Version

2.5.2

### Browser

Chrome

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Maybe we could use generics in the withDefaultVariant type definition to type the variant parameter
(I don't know if it is the right solution, I'm new in chakra-ui)

```ts
declare function withDefaultVariant<T extends string[] | Record<string, any>>({ variant, components, }: {
    variant: ThemingProps<T>["variant"];
    components?: T
}): ThemeExtension;
```

**Comment by Kalo0m** [comment]
I've tried some typescript changes and this type declaration of the withDefaultVariantBis function seems to be an improvement:
## previous : 
```ts
declare function withDefaultVariant<T extends string[] | Record<string, any>>({
  variant,
  components
}: {
  variant: ThemingProps<T extends string[] ? T[number] : keyof T>["variant"];
  components?: T;
}): ThemeExtension;
```
## New: 
```ts
declare function withDefaultVariantBis<
  T extends string[] | Record<string, any>
>({
  variant,
  components
}: {
  variant: ThemingProps<
    T extends readonly string[] ? T[number] : keyof T
  >["variant"];
  components?: T;
}): ThemeExtension
```
And in this example, variant arguments are typed as `ResponsiveValue<(string & {}) | "outline" | "solid" | "ghost" | "link" | "unstyled" | "filled" | "flushed"> | undefined` which is better than `any` in my opinion
```ts
export const theme = extendTheme(
  withDefaultVariantBis({
    variant: "outline",
    components: {
      'Button': [],
      'Input': []
    }
  }),
  withDefaultVariantBis({
    variant: "flushed",
    components: ['Button', 'Input'] as const
  })
);
```
are you interested in this change? Should I create a pull request?

Here is the codesandbox if you want to take a look https://codesandbox.io/s/wizardly-thompson-lbg3u4?file=/theme.ts

**Comment by segunadebayo** [comment]
Thanks for this. I'd recommend making those changes in your codebase for now.

Adding this is not a priority at the moment. The team is focused on v3.
