### ISSUE TITLE
margin prop  set to 14 renders 56px instead of 14px

### ISSUE THREAD

**Issue by co-bby** [chakra-ui/chakra-ui#7487]
### Description

In this example I expect the Box component to have 14 pixels but it renders 56 pixels

```javascript
import { Box } from '@chakra-ui/react'

const App = () => {
  return <Box border='1px' borderColor='black' width="10"  m="14">Click on me!</Box>
}
```

### Link to Reproduction

https://vdbhdu.codesandbox.io/

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.5.2

### Browser

Mozilla Firefox, Microsoft Edge

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is not a bug. The `m=14` refers to a spacing token of 14 => 56px in the theming system.

Please read more about it here:
https://chakra-ui.com/docs/styled-system/theme
