### ISSUE TITLE
@chakra-ui/icons can't be installed with React 17

### ISSUE THREAD

**Issue by radek-novak** [chakra-ui/chakra-ui#7491]
### Description

I tried to install various versions of @chakra-ui/icons with React 17 and none worked. It seem that version 1 requires React 16+ but @chakra-ui/system requires 18

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: tstchakra@1.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   dev react@"17" from the root project
npm ERR!   peer react@">=16.8.6" from @chakra-ui/icons@1.1.7
npm ERR!   node_modules/@chakra-ui/icons
npm ERR!     dev @chakra-ui/icons@"1" from the root project
npm ERR!   2 more (@emotion/react, @emotion/styled)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=18" from @chakra-ui/system@2.5.3
npm ERR! node_modules/@chakra-ui/system
npm ERR!   peer @chakra-ui/system@">=1.0.0" from @chakra-ui/icons@1.1.7
npm ERR!   node_modules/@chakra-ui/icons
npm ERR!     dev @chakra-ui/icons@"1" from the root project
```

### Link to Reproduction

https://codesandbox.io/s/wandering-fire-pr9hdy

### Steps to reproduce

```
# create an empty npm project
mkdir chakrabug
cd chakrabug
npm init -Y;

npm i -D @chakra-ui/icons@1 react@17 react-dom@17
```
`@chakra-ui/icons` I tried and did not work were `1`, `1.0`, `2`

### Chakra UI Version

1

### Browser

none

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Please install version `1.1.7` which does not require React 18.

See here in the v1 branch: https://github.com/chakra-ui/chakra-ui/blob/v1/packages/icons/package.json
