### ISSUE TITLE
Type doc generation ignores `SystemProps` when not renamed

### ISSUE THREAD

**Issue by kkudose** [chakra-ui/chakra-ui#7495]
### Description

from [generate-type-docs](https://github.com/chakra-ui/chakra-ui/blob/6a590a0248cbe967628e680e0d1c1de8b05fcac7/scripts/generate-type-docs.ts#L77):
```
if (shouldIgnoreProperty(property)) {
        continue
}
```
`typeStatements` ignores getting `SystemProps` when the prop is not renamed.

Examples:
- `Avatar` prop `borderColor` ([source](https://github.com/chakra-ui/chakra-ui/blob/6a590a0248cbe967628e680e0d1c1de8b05fcac7/packages/components/avatar/src/avatar-types.ts#L39), [docs](https://chakra-ui.com/docs/components/avatar/props#avatar-props))
- Well, actually, I can't find any other examples 😅 Maybe it'd be easier to just rename this prop than to fix the tooling.

Counter-examples (renames generate correctly):
- `Image` prop `align` is renamed from `SystemProps["objectPosition"]` ([source](https://github.com/chakra-ui/chakra-ui/blob/6a590a0248cbe967628e680e0d1c1de8b05fcac7/packages/components/image/src/image.tsx#L43), [docs](https://chakra-ui.com/docs/components/image/props#props))
- `List` prop `spacing` is renamed from `SystemProps["margin"]` ([source](https://github.com/chakra-ui/chakra-ui/blob/6a590a0248cbe967628e680e0d1c1de8b05fcac7/packages/components/layout/src/list.tsx#L41), [docs](https://chakra-ui.com/docs/components/image/props#props))

### Link to Reproduction

https://chakra-ui.com/docs/components/avatar/props

### Steps to reproduce

1. Generate docs for `Avatar` -> `borderColor` is missing.
1. Rename `borderColor` and regenerate docs -> renamed prop appears!

### Chakra UI Version

2.5.3

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Sorry. We don't intend to fix this one.

Feel free to open a PR if you're interested
