### ISSUE TITLE
Type doc generation does not correctly infer optional/required for `SystemProps` props

### ISSUE THREAD

**Issue by kkudose** [chakra-ui/chakra-ui#7496]
### Description

Example:
- `Card` props are marked required when they're optional ([docs](https://chakra-ui.com/docs/components/card/props#props))

Relevant code from [generate-type-docs](https://github.com/chakra-ui/chakra-ui/blob/6a590a0248cbe967628e680e0d1c1de8b05fcac7/scripts/generate-type-docs.ts#L95):
```
      const nonNullableType = type.getNonNullableType()

      const typeName = typeChecker.typeToString(nonNullableType)
      const required = nonNullableType === type && typeName !== "any"
```

### Link to Reproduction

https://chakra-ui.com/docs/components/card/props#props

### Steps to reproduce

Example:
1. Generate docs for `Card`
2. Confirm props are incorrectly marked as required.

Counter-example:
1. Confirm `Button` has `iconSpacing` prop correctly marked as optional
3. Update `ButtonOptions` so `iconSpacing` is required.
4. Regen docs
5. Confirm `iconSpacing` is still optional when it should be required. 

### Chakra UI Version

2.5.3

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is now fixed, I believe
