### ISSUE TITLE
can't pass fill to @chakra-ui/next-js

### ISSUE THREAD

**Issue by violabg** [chakra-ui/chakra-ui#7500]
### Description

if try to add the **fill** props to an Image from @chakra-ui/next-js you get a typescript error

https://nextjs.org/docs/api-reference/next/image#fill

### Link to Reproduction

https://codesandbox.io/p/sandbox/reverent-river-n45vhk?selection=%5B%7B%22endColumn%22%3A13%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A13%2C%22startLineNumber%22%3A8%7D%5D&file=%2Fpages%2Findex.tsx

### Steps to reproduce

if try to add the fill props to an Image from @chakra-ui/next-js you get a typescript error

### Chakra UI Version

2.5.3

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by hectoraldairah** [comment]
There is a collision between the [fill?](https://github.com/chakra-ui/chakra-ui/blob/main/packages/core/styled-system/src/config/color.ts#L24) prop from the `ColorProps` interface and the fill property from the Next.js Image.

Maybe omitting the fill prop in the for the [image.tsx](https://github.com/chakra-ui/chakra-ui/blob/main/packages/integrations/next-js/src/image.tsx) could to the trick?

I'm not sure if this change could  be dangerous for some use cases

**Comment by segunadebayo** [comment]
You're correct @hectoraldairah.

Fortunately, this was fixed in my recent PR to improve the TS types for 5.0.

I'll release a new version shortly.

**Comment by hectoraldairah** [comment]
Thank you @segunadebayo !
