### ISSUE TITLE
zIndex on toasts does not work

### ISSUE THREAD

**Issue by saltnpixels** [chakra-ui/chakra-ui#7505]
### Description

We have a component we do not control with a crazy high zIndex. We need Toasts to be on top when shown.
However when setting the theme objects zIndices, the toast key does nothing. 

It seems toasts are hardcoded with a zIndex of 5500 and it cannot be overridden anywhere.

See:
https://github.com/chakra-ui/chakra-ui/blob/8b0bd0d5892d91699571b110adee89857078e9e0/packages/components/toast/src/toast.utils.ts#L90

And toasts don't either have a class of chakra-toast or something for us to apply styles to. Each toast has an id like "chakra-toast-manager-top" which is not helpful. We want ALL toasts to have this zIndex. 

We need the themes toast zIndex to be applied in the file above. 

### Link to Reproduction

https://chakra-ui.com/docs/components/toast/usage

### Steps to reproduce

Open a Toast. Inspect and see it has a zIndex of 5500 and this cannot change

### Chakra UI Version

2.5.4

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Good catch, Eric @saltnpixels.

I've updated the code to use a CSS variable and fall back to the hardcoded value. You should be able to override it in the next release much easier.

```jsx live=false
const theme = extendTheme({
  styles: {
    global: {
      "--toast-z-index": 10,
    },
  },
})
```

In the future, we'll consider making it configurable in the `ToastOptionProvider`

I'll publish a new version shortly.
