### ISSUE TITLE
Typescript error in Editable example - onClick is possibly undefined & getSubmitButtonProps types incompatibile with IconButton 

### ISSUE THREAD

**Issue by AbdelMN** [chakra-ui/chakra-ui#7507]
### Description

Hi,

There is a typing problem, basically we use the IconButton component which takes the props "aria-label" which is typed in non [optional string](https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/button/src/icon-button.tsx#L29) and the thing is that the function getSubmitButtonProps() that we use to get the props that we will give to IconButton type "aria-label" in [optional](https://use-form.netlify.app/interfaces/_node_modules__types_react_index_d_.react.ariaattributes.html#aria_label) so "string | undefined" which is therefore incompatible with IconButton => so we have a typing error. 

It's the same with the onClick function, I'd like to call it myself because I'd like to add something to the function, so I'll call my custom function first and then the basic onClick function so that the editable can be closed, but the problem is that it's typed as optional, so I have a problem calling something that's potentially undefined.

Here is an [example code](https://codesandbox.io/p/sandbox/interesting-hellman-csehx1?file=%2FREADME.md) of the problem  

We can solve the problem for the "aria-label" by providing it ourselves as shown on this [issue](https://github.com/chakra-ui/chakra-ui/issues/6147#issuecomment-1146756314) 

But aria-label is provided by the hooks as you can see so why not use it: 
![image](https://user-images.githubusercontent.com/57446997/228331453-cc9588cf-dc40-4431-8604-4c7766f5f0c1.png)

And on the [official documentation](https://chakra-ui.com/docs/components/editable#with-custom-input-and-controls), the example is the same but does not work. 

I also have the same problem with the onClick function that I can't call because it is possibly undefined because it is typed as optional like "aria-label" 

### Link to Reproduction

https://codesandbox.io/p/sandbox/interesting-hellman-csehx1?file=%2FREADME.md

### Steps to reproduce

Go to Codesandbox example

### Chakra UI Version

2.5.1

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Hi @AbdelMN,

Consider resolving this by casting the types. It's almost not feasible to auto-infer the boundaries of those components.
