### ISSUE TITLE
Variant outline is not working for Tag component

### ISSUE THREAD

**Issue by rhoentier** [chakra-ui/chakra-ui#7509]
### Description

When I updated Chakra UI to version 2.5.3 the outline variant is not working properly.
Even the fix for Ticket #7503 is not working for the outlines.

### Link to Reproduction

https://chakra-ui.com/docs/components/tag#with-right-icon

### Steps to reproduce

1. Go to https://chakra-ui.com/docs/components/tag#with-right-icon

### Chakra UI Version

2.5.3

### Browser

Firefo 111.0.1 

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This has already been fixed in one of the recent PRs. We'll release an update shortly.

If the issue persists after the release, I'll re-open this issue.
