### ISSUE TITLE
Add `aspectRatio` to BoxProps

### ISSUE THREAD

**Issue by jonahallibone** [chakra-ui/chakra-ui#7511]
### Description

It would be great if we could expose the CSS [`aspect-ratio`](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio) to the base props of `<Box />` and all component extending `<Box />`.

### Problem Statement/Justification

This seems like a pretty useful CSS prop to expose without needs `sx` or `_css`, especially since it's been supported on all major browsers since 2021. Personally, we have had need for it multiple times and have found it mildly frustrating that we need to use `sx` or `_css` for what seems like a pretty standard CSS property.

<img width="1379" alt="Screenshot 2023-03-29 at 11 46 51 AM" src="https://user-images.githubusercontent.com/8886318/228594535-15adf9d8-0055-4bf7-a83c-31c11d352e75.png">

### Proposed Solution or API

Add a prop called `aspectRatio` to the props of `Box` and all components that compose `Box`.  I understand this might cause conflict on the `AspectRatio` component, I am not completely sure how to get around that. Seems the options are to 

1. Transition `<AspectRatio />` to use the native CSS prop
2. Create an exemption inside `<AspectRatio />` to handle the prop differently and continue to use the `padding` hack.

**Comment by munnokd** [comment]
Can I work on this issue?

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by jonahallibone** [comment]
@segunadebayo Thanks for the fix! Just to clarify, I should expect  `aspectRatio={1 / 1}` to behave differently from  `aspectRatio={"1 / 1"}`, correct? The former gives me `aspect-ratio: 1px` while the latter gives me the correct `aspect-ratio: 1/1`. Thanks for any clarification
