### ISSUE TITLE
Input component has spin buttons in v2.5.3

### ISSUE THREAD

**Issue by cawpea** [chakra-ui/chakra-ui#7513]
### Description

When I use v2.5.3 (or v2.5.4) of `@chakra-ui/react`, `<Input type="number">` is visible with `::-webkit-inner-spin-button` and `::-webkit-outer-spin-button`. 

<img width="684" alt="CleanShot 2023-03-30 at 15 54 18@2x" src="https://user-images.githubusercontent.com/9220377/228753787-fe754518-bb48-40ff-a087-738cfea7139c.png">

The spin buttons are not visible in v2.5.2. The following updates may have caused this.

https://github.com/chakra-ui/chakra-ui/commit/0f8a50054b8b480bb523dd0964bb31a9e061f8c6#diff-6c2cb5a804c5d6b257e4f8b160744618e1b5e2d7d7c78adb416fc4ac07fae814R176-R179

I have fixed to hide spin buttons using `sx` props like following way.

```jsx
import { Input } from '@chakra-ui/react';

<Input
    type="number"
    sx={{
      '&::-webkit-inner-spin-button, &::-webkit-outer-spin-button': {
        '-webkit-appearance': 'none !important',
      },
    }}
  />
```

Is there any other way to solve this problem?

### Link to Reproduction

https://codesandbox.io/s/delicate-fire-eob7rm?file=/src/index.tsx

### Steps to reproduce

1. hover on `<Input type="number">`.
2. show spin buttons on `<Input type="number">`

### Chakra UI Version

v2.5.3

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Good catch @cawpea.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
