### ISSUE TITLE
Menu component unexpected behavior

### ISSUE THREAD

**Issue by LordPachimari** [chakra-ui/chakra-ui#7519]
### Description

The menu appears to position itself relative to the menu button. In my case, the button disappears (display:none) when the user moves the mouse away from the button (see sandbox), which causes the menu list to shift to the top left corner. However, when you wait for the menu transition to finish and then move your cursor away from the button, then the menu list positions itself as expected.

### Link to Reproduction

https://codesandbox.io/s/serene-surf-xw1ewm?file=/src/index.tsx

### Steps to reproduce

The steps are shown in the ui.

### Chakra UI Version

2.5.3

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @LordPachimari,

This isn't a bug in Chakra. The positioning logic will not work if you hide the button with "display:none" or use the `hidden` prop. You need to adjust the styling approach a bit.

Here's a sandbox that shows how to work it by using position absolute and visibility hidden.
https://codesandbox.io/s/awesome-leaf-vk008v?file=/src/index.tsx
