### ISSUE TITLE
Add polyfill for `text-box-trim` and `text-box-edge`

### ISSUE THREAD

**Issue by isBatak** [chakra-ui/chakra-ui#7522]
### Description

On this link you can find a detailed explanation https://github.com/jantimon/text-box-trim-examples

This feature is still hidden behind the experimental flags in Chrome 111.
![image](https://user-images.githubusercontent.com/4128883/229103863-7ee355f2-87e0-450b-add1-774767faae31.png)

PostCSS has `leading-trim` plugin that could be used as the inspiration
https://github.com/jantimon/text-box-trim-examples/blob/main/app/preview/postcss/plugin/postcssLeadingTrim.ts

Maybe it could be [stylis](https://www.npmjs.com/package/stylis) plugin similar to [stylis-plugin-rtl](https://www.npmjs.com/package/stylis-plugin-rtl/v/2.1.0)

### Problem Statement/Justification

Figma recently introduced this feature for designers. It would be easier for frontend developer if he can just use the same styles.

Source: https://www.figma.com/whats-new/

https://user-images.githubusercontent.com/4128883/229101254-8b849f0a-1a5a-481f-9a19-9718c45a8c1d.mp4

### Figma CSS output:
![image](https://user-images.githubusercontent.com/4128883/229101634-ca602eec-8381-4c4a-8da5-84f1f7e95683.png)
Figma is still calling it by the old name `leading-trim` and `text-edge`

### Proposed Solution or API

```
<Text textBoxTrim="both" textBoxEdge="cap alphabetic" />
```

**Comment by segunadebayo** [comment]
This looks a great feature @isBatak.

I think we should wait until it gets supported mainstream across all browsers. The PostCSS plugin works pretty week for Google Fonts and will require some manual work if it's a custom font. Don't want to manage that difference for now.

Thanks for bringing this up though.
