### ISSUE TITLE
CacheProvider use in Next13 without "/app" layout

### ISSUE THREAD

**Issue by HelloYukyung** [chakra-ui/chakra-ui#7527]
#### System information

version 
    "next": "13.1.6",
    "react": "18.2.0",
    "@chakra-ui/next-js": "^2.1.2",
    "@chakra-ui/react": "^2.5.5",

Hi I'm creating a project without creating a "/app" directory in next13. I didn't create the "/app" directory because I heard that it's not a feature that Next officially provides yet.

I know that chakra-ui works only for client-side components in the official document.
However, my project does not have RootLayout, so I applied CacheProvider and ChakraProvider to _app.tsx.

However, the FOUC phenomenon occurred when the project was distributed.
The default HTML style is shown as shown in the picture below, and then the chakra-ui style is placed on it.

Can you tell me the solution?

<img width="686" alt="image" src="https://user-images.githubusercontent.com/49505843/229305332-b254ed7a-1f71-4c89-afd9-1612889e3546.png">

```
import "@/styles/globals.css";
import "@/styles/miniReset.css";
import "@/styles/font.css";

import { NextPage } from "next";
import type { AppProps } from "next/app";
import { ReactElement, ReactNode, useEffect } from "react";
import { ChakraProvider } from "@chakra-ui/react";
import { CacheProvider } from "@chakra-ui/next-js";
import { theme } from "@/theme";

type NextPageWithLayout<P = object, IP = P> = NextPage<P, IP> & {
  // eslint-disable-next-line no-unused-vars
  getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

export default function App({ Component, pageProps }: AppPropsWithLayout) {
  const getLayout = Component.getLayout || ((page) => page);

  useEffect(() => {
    function handleResize() {
      const body = document.querySelector("body") ?? document.body;
      body.style.height = `${window.innerHeight}px`;
    }
    handleResize();

    window.addEventListener("resize", handleResize);
    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  return (
    <CacheProvider>
      <ChakraProvider theme={theme}>
        {getLayout(<Component {...pageProps} />)}
      </ChakraProvider>
    </CacheProvider>
  );
}

```
### Link to Reproduction

.

### Steps to reproduce

First visit to a site without cache

### Chakra UI Version

2.5.5

### Browser

chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hey @HelloYukyung,

You don't need the CacheProvider if you're not using the app directory. It should work out of the box.
