### ISSUE TITLE
transition does not work with bgGradient in _hover

### ISSUE THREAD

**Issue by somecho** [chakra-ui/chakra-ui#7530]
### Description

I have a component which, when hovered, I want the background to transition into a gradient. 
```jsx
<Container 
    _hover={{ bgGradient: "linear(to-r,red.200,purple.200)"}} 
    transition="0.25s">
</Container>
```
This doesn't work, but using a simple background color works. 
```jsx
<Container 
    _hover={{ background: "red"}} 
    transition="0.25s">
</Container>
```

### Link to Reproduction

https://codesandbox.io/s/green-platform-df91en

### Chakra UI Version

2.5.4

### Browser

Firefox 111.0.1

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

React version 18.2.0

**Comment by segunadebayo** [comment]
Hi @somecho,

This is a fundamental CSS problem. You can transition the `background-image` property in CSS.

You may have to create two different elements and transition from one to the other using opacity.
