### ISSUE TITLE
Modal cannot pan on iOS (pinch is fine)

### ISSUE THREAD

**Issue by richardwu** [chakra-ui/chakra-ui#7531]
### Description

We have a full-screen `Modal`.

We have enabled the `allowPinchZoom` setting which works as intended ✅ (user can pinch to zoom in/out).

However, it does not allow the user to pan (eg 1 finger drag the screen around to pan when zoomed in). 1 finger panning works on a non-modal screen/page.

### Link to Reproduction

https://codesandbox.io/s/damp-frost-oln775?file=/src/index.tsx

### Chakra UI Version

2.5.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @richardwu,

This issue is due to the downstream `react-remove-scroll` library we rely on. Consider opening an issue there instead.

Thanks
