### ISSUE TITLE
Add margin and padding to Divider component

### ISSUE THREAD

**Issue by vitalijalbu** [chakra-ui/chakra-ui#7536]
### Description

Would be a great thing to let Divider having margin and padding, or even beter, have multiple styling of it:
[https://mantine.dev/core/divider/](https://mantine.dev/core/divider/)

### Problem Statement/Justification

You must write own css to customize it 

### Proposed Solution or API

[https://mantine.dev/core/divider/](https://mantine.dev/core/divider/)

**Comment by cschroeter** [comment]
In Charka you can simply do

```tsx
 <Divider my="8" />
 ```
 
 which is pretty much the same as in Mantine
