### ISSUE TITLE
App crashes when using isLoading prop on Button and translate page with Google

### ISSUE THREAD

**Issue by mardrof** [chakra-ui/chakra-ui#7538]
### Description

We have encountered an issue with <Button> component. When using _isLoading_ prop and page is translated with Google Translate, app crashes when user clicks on <Button>. Without translating page app works correctly, no errors appear.

### Link to Reproduction

https://codesandbox.io/s/affectionate-carson-swp7it

### Steps to reproduce

1. Go to [CodeSandbox](https://swp7it.csb.app/) (it is full version of **Link to Reproduction**)
2. Translate page to language other than English
3. Click on "Click on me!"
4. App will crash with error "NotFoundError
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node."

### Chakra UI Version

2.5.5

### Browser

Google Chrome 111.0.5563.147

### Operating System

- [x] macOS
- [X] Windows
- [x] Linux

### Additional Information

![image](https://user-images.githubusercontent.com/8026448/229501322-58cda2bc-6e43-40d5-bf84-7cf1b93872ce.png)

**Comment by paradox37** [comment]
This is not ChakraUI issue. This is React issue which will not be fixed: https://github.com/facebook/react/issues/11538#issuecomment-417504600

As a workaround, you can do it like this:
```
<Button onClick={() => setIsLoading(() => true)} isLoading={isLoading}>
      <Text>Click on me!</Text>
    </Button>
```
