### ISSUE TITLE
Cannot tab to/through RadioGroup on Safari

### ISSUE THREAD

**Issue by nasir-aviva** [chakra-ui/chakra-ui#7545]
### Description

When I try to tab through the page I can tab through all the elements as expected however RadioGroups are skipped on Safari.

In Chrome it works and I can tab to a RadioGroup

This happens on your docs and also in my personal work and I guess is a problem for all forms accessibility wise

### Link to Reproduction

https://chakra-ui.com/docs/components/form-control/usage

### Steps to reproduce

On Chrome
1. Click 

> Sample usage for a radio or checkbox group[#]

2. Press tab 
3. See that the focus goes to `Sasuke`

On safari
1. Click 

> Sample usage for a radio or checkbox group[#]

2. Press tab 
3. See that the focus skips the radio group and goes to the editable example

### Chakra UI Version

2.4.3 and whatever version the docs website uses

### Browser

Safari 16.3

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hey, you need to enable keyboard navigation for form controls in your system settings to tab through radio fields.

![CleanShot 2023-04-24 at 21 18 50@2x](https://user-images.githubusercontent.com/6916170/234107170-de1bbebc-27e1-462e-9f5f-0b3af58fe5df.png)

**Comment by nasir-aviva** [comment]
> Hey, you need to enable keyboard navigation for form controls in your system settings to tab through radio fields.
> 
> ![CleanShot 2023-04-24 at 21 18 50@2x](https://user-images.githubusercontent.com/6916170/234107170-de1bbebc-27e1-462e-9f5f-0b3af58fe5df.png)

Ah I'm so sorry did not know this existed! Thank you
