### ISSUE TITLE
Toast renders twice

### ISSUE THREAD

**Issue by selrond** [chakra-ui/chakra-ui#7547]
### Description

When using toast functionality (doesn’t matter if via `useToast()` or `createStandaloneToast()`), two seemingly identical chakra portals get created, overlaying perfectly, so this duplicity is not obvious.

### Link to Reproduction

https://codesandbox.io/p/sandbox/chakra-duplicate-toasts-2i5wir

### Steps to reproduce

1. Go to https://codesandbox.io/p/sandbox/chakra-duplicate-toasts-2i5wir
2. Click any of the buttons to create at least 1 toast
3. Open the dev tools and notice two divs `<div class="chakra-portal">`
4. Try to hide / delete one to see the toasts are still there

### Chakra UI Version

2.5.4

### Browser

Google Chrome 111

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by itkrt2y** [comment]
Kindly remove `<ToastContainer />` in `_app.tsx`.

**Comment by selrond** [comment]
@itkrt2y why? The [docs recommend doing so](https://chakra-ui.com/docs/components/toast/usage#standalone-toasts).

**Comment by itkrt2y** [comment]
That document is for using toast outside of the chakra provider.
> Use createStandaloneToast to create toasts from outside of your React Components.

You only need to call `<ToastProvider />` once for toast to work properly.

### ChakraProvider

https://github.com/chakra-ui/chakra-ui/blob/c14615106066349955b0eaa7b78d4f3a59a08b03/packages/components/react/src/chakra-provider.tsx#L20-L40

### ToastContainer

https://github.com/chakra-ui/chakra-ui/blob/c14615106066349955b0eaa7b78d4f3a59a08b03/packages/components/toast/src/create-standalone-toast.tsx#L61-L72

**Comment by segunadebayo** [comment]
Closing based on: https://github.com/chakra-ui/chakra-ui/issues/7547#issuecomment-1499226350
