### ISSUE TITLE
`css-reset` overrides `<svg display="xxx">`

### ISSUE THREAD

**Issue by chelproc** [chakra-ui/chakra-ui#7555]
### Description

`css-reset` component current uses `:where` hack to lower the selector specificity.

However, this statement still overrides `svg` element's `display` attribute.

https://github.com/chakra-ui/chakra-ui/blob/c14615106066349955b0eaa7b78d4f3a59a08b03/packages/components/css-reset/src/css-reset.tsx#L275

### Link to Reproduction

https://codesandbox.io/s/elastic-kare-6ngi23?file=/src/index.tsx

### Steps to reproduce

This JSX expects to show nothing, but `css-reset` overrides the default attribute style to be `block`

```JSX
<svg display="none" />
```

### Chakra UI Version

2.5.5

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Possible workaround is:

```css
svg[display="none"] {
  display: none;
}
```

**Comment by mendozagioo** [comment]
🤔 @chelproc, but `svg` in JSX has not attribute `display` because that is part of `style` attribute (`style={{display:'none'}}`).
You are using the `svg` as an element of HTML not a Component.
Or maybe a bit more context is required here, IMO.

**Comment by chelproc** [comment]
@mendozagioo 

The latest spec says [`svg` element in HTML is defined under the SVG namespace](https://html.spec.whatwg.org/multipage/embedded-content-other.html#svg-0), and the root `svg` element (not only shape elements but also `svg` element itself) [has `display` attribute](https://svgwg.org/svg2-draft/styling.html#PresentationAttributes).

React seems to have support for this attribute:
- https://legacy.reactjs.org/docs/dom-elements.html#all-supported-html-attributee
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/88ab488c7d6c4ff0429a24b5822dd8e9c66a8240/types/react/index.d.ts#L2580

So `<svg display="none">` works without `css-reset`

https://codesandbox.io/s/reverent-meadow-h76coo?file=/src/index.js

**Comment by segunadebayo** [comment]
Hi @mendozagioo, please use the style attribute to set the display none if you really need to.
