### ISSUE TITLE
cannot find module '@chakra-ui/next-js' or its corresponding type declarations in nextjs 13 

### ISSUE THREAD

**Issue by yaba101** [chakra-ui/chakra-ui#7558]
## This is terminal response

Module not found: Can't resolve '@chakra-ui/next-js'
  1 | 'use client'
  2 |
> 3 | **import { CacheProvider } from '@chakra-ui/next-js'**
  4 | import { ChakraProvider } from '@chakra-ui/react'
  5 |
  6 | export default function RootLayout({

### Link to Reproduction

https://codesandbox.io/

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.5.5

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![Screenshot (1)](https://user-images.githubusercontent.com/63213576/230900928-8157a0b9-a1b5-436c-9d24-0fea3db4bea6.png)

**Comment by oil-oil** [comment]
@yaba101 Perhaps you should check `package.json` for the presence of the `@chakra-ui/next-js` dependency. If not, you can install it separately.

**Comment by yaba101** [comment]
> @yaba101 Perhaps you should check `package.json` for the presence of the `@chakra-ui/next-js` dependency. If not, you can install it separately.

Nuh, I thought I should do that too but it doesn't work like that.......

**Comment by yaba101** [comment]
actually, the problem wasn't that, the problem was after I install @chakra-ui/next-js separately ( surprisingly not including in docs installation guide )  I faced the following weird console error and crushed the app
![Screenshot (2)](https://user-images.githubusercontent.com/63213576/231234849-386a406f-eccd-4cc5-bde9-f2cbc576db3c.png)

**Comment by segunadebayo** [comment]
This is not an error on our part, please open this in Next.js repo.

**Comment by yaba101** [comment]
Yeah I think the problem comes from Nextjs......

**Comment by R3flector** [comment]
Same error.

/node_modules/.pnpm/@chakra-ui+next-js@2.1.3_@chakra-ui+react@2.6.0_@emotion+react@11.10.6_next@13.3.1_react@18.2.0/node_modules/@chakra-ui/next-js/dist/chunk-43TM32P5.mjs:3
import { useServerInsertedHTML } from "next/navigation.js";
         ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'useServerInsertedHTML' not found. The requested module 'next/navigation.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'next/navigation.js';
const { useServerInsertedHTML } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15) {
  page: '/'

**Comment by Revaycolizer** [comment]
> ### Description
> ## This is terminal response
> Module not found: Can't resolve '@chakra-ui/next-js' 1 | 'use client' 2 |
> 
> > 3 | **import { CacheProvider } from '@chakra-ui/next-js'**
> > 4 | import { ChakraProvider } from '@chakra-ui/react'
> > 5 |
> > 6 | export default function RootLayout({
> 
> ### Link to Reproduction
> https://codesandbox.io/
> 
> ### Steps to reproduce
> 1. Go to '...'
> 2. Click on '...'
> 3. Scroll down to '...'
> 4. See error
> 
> ### Chakra UI Version
> 2.5.5
> 
> ### Browser
> _No response_
> 
> ### Operating System
> * [ ]  macOS
> * [x]  Windows
> * [ ]  Linux
> 
> ### Additional Information
> ![Screenshot (1)](https://user-images.githubusercontent.com/63213576/230900928-8157a0b9-a1b5-436c-9d24-0fea3db4bea6.png)

same error it used to work fine but using now nextjs 13.5.2 getting this error
