### ISSUE TITLE
Prop `className` did not match. Server: "chakra-button css-4xx2wk" Client: "chakra-button css-1e2mwvd"   

### ISSUE THREAD

**Issue by devlopersabbir** [chakra-ui/chakra-ui#7559]
## When I trying to use [@chakraUi](https://chakra-ui.com/) in [NextJs13](https://nextjs.org/) then I got this issue.
`
Warning: Prop `className` did not match. Server: "chakra-button css-4xx2wk" Client: "chakra-button css-1e2mwvd"
`
I'm trying to share my all of source code that can help you find soluation.
## layout.tsx source code
```tsx
"use client";

import { CacheProvider } from "@chakra-ui/next-js";
import { ChakraProvider } from "@chakra-ui/react";
import React from "react";

interface IRootLayout {
  children: React.ReactNode;
}

const RootLayout: React.FC<IRootLayout> = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <title>Next13</title>
      </head>
      <body>
        <CacheProvider>
          <ChakraProvider>{children}</ChakraProvider>
        </CacheProvider>
      </body>
    </html>
  );
};
export default RootLayout;
```
![image](https://user-images.githubusercontent.com/82939905/230833361-fdf7545f-1e1e-4f4a-bf84-57d124fe1a00.png)
## that's is the error. When I'm trying to use chakra then I got this issue.
```tsx
"use client";
import { Button, Center, Heading, Icon, VStack } from "@chakra-ui/react";
import React from "react";
import { FaGoogle } from "react-icons/fa";

const page: React.FC = () => {
  return (
    <React.Fragment>
      <Center>
        <Button size="lg" leftIcon={<Icon as={FaGoogle} />}>
          Google
        </Button>
      </Center>
    </React.Fragment>
  );
};

export default page;
```
Thanks :)

**Comment by clement-touzet** [comment]
I have the same error with next 13.3.0 but not with next 13.2.3 : 
`Warning: Prop `className` did not match. Server: "chakra-heading css-1522hk" Client: "chakra-heading css-18nmmpe"`

**Comment by segunadebayo** [comment]
Hi @devlopersabbir,

Consider the following approaches:

- Add a `data-theme=<light|dark>` to the html attribute
- Add the `ColorModeScript` that'll add the data-theme attribute for you automatically

**Comment by hungnv1312** [comment]
Have you fixed it yet? I also encountered it but couldn't fix it....

**Comment by hungnv1312** [comment]
Remove` export const runtime = 'edge'` at root page and working for me
