### ISSUE TITLE
Vite 4 + Typescript + Chakra are throwing error during build

### ISSUE THREAD

**Issue by RaGreen** [chakra-ui/chakra-ui#7562]
### Description

When I try to build application written in React with Typescript, using Vite 4 I'm getting error from one of Chakra's packages.

> PS D:\repos\other\vite-project> yarn run build
yarn run v1.22.19
$ tsc && vite build
vite v4.2.1 building for production...
✓ 375 modules transformed.
✓ built in 2.64s
Unexpected token (Note that you need plugins to import files that are not JavaScript)
file: D:/repos/other/vite-project/node_modules/@chakra-ui/theme/dist/chunk-VHIIIDDT.mjs:3:2
1: // src/styles.ts
2: var styles = {
3:   global: {
     ^
4:     body: {
5:       fontFamily: "body",
error during build:
RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (file:///D:/repos/other/vite-project/node_modules/rollup/dist/es/shared/node-entry.js:2128:30)
    at Module.error (file:///D:/repos/other/vite-project/node_modules/rollup/dist/es/shared/node-entry.js:13322:16)
    at Module.tryParse (file:///D:/repos/other/vite-project/node_modules/rollup/dist/es/shared/node-entry.js:13999:25)
    at Module.setSource (file:///D:/repos/other/vite-project/node_modules/rollup/dist/es/shared/node-entry.js:13609:39)
    at ModuleLoader.addModuleSource (file:///D:/repos/other/vite-project/node_modules/rollup/dist/es/shared/node-entry.js:23574:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Link to Reproduction

https://codesandbox.io/p/sandbox/youthful-alex-ihqlog

### Steps to reproduce

1. Try to build application with "vite build"

### Chakra UI Version

2.5.5

### Browser

not important

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Package.json:
> {
  "name": "vite-project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@chakra-ui/react": "^2.5.5",
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "framer-motion": "^10.11.5",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.28",
    "@types/react-dom": "^18.0.11",
    "@vitejs/plugin-react-swc": "^3.0.0",
    "typescript": "^4.9.3",
    "vite": "^4.2.0"
  }
}

**Comment by dvartic** [comment]
Unless I'm doing something wrong, I'm not that familiar with Vite, looks like your issue is related to defining a replacement for `global`. If this is removed, build works correctly. Also, on local env, it seems to build either way so more research would be needed, however, it seems unrelated to Chakra.

```ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
});

```

**Comment by thesnups** [comment]
I'm running into this as well. Workaround seems to be to remove the use of `global` when defining theme styles, which is not ideal.

**Comment by Abdulrahman-zazo** [comment]
Does anyone know the problem?
I modified the tsconfig.app.json file, but it still didn't work. 🙁
