### ISSUE TITLE
"noStyles" prop is missing in type definitions of ModalContent

### ISSUE THREAD

**Issue by arielger** [chakra-ui/chakra-ui#757]
**Describe the bug**
I can't pass "noStyles" to ModalContent component since it's not in type definitions.
https://github.com/chakra-ui/chakra-ui/blob/afbd89b9d28291d2c7b9ce11b9e800e93c6ecef5/packages/chakra-ui/src/Modal/index.js#L226

**Suggested solution(s)**
Add "noStyles" to Typescript definitions

**Comment by with-heart** [comment]
Hi @arielger! This issue is no longer relevant for the upcoming 1.0 release. See https://next.chakra-ui.com/docs/components/modal for 1.0 pre-release documentation.
