### ISSUE TITLE
Tooltip placement using breakpoints

### ISSUE THREAD

**Issue by mikikiv** [chakra-ui/chakra-ui#7573]
### Description

`placement` within the Tooltip component should offer the option to position based on window breakpoints `tooltip={{ base: 'top', md: 'left' }}` to allow developers to be more specific in placement

### Problem Statement/Justification

`position='auto'` is probably supposed to be the best option to handle this, but being able to designate a specific position in specific situations is occasionally necessary.
For my case, Auto is placing the tooltip over a different component in desktop while using auto. In mobile, the placement is fine. 
I don't consider that a bug, the overlap is caused by my use of the surrounding components in this case.

### Proposed Solution or API

End user should be able to load the following component

```.tsx
<Tooltip
    label="Add Category"
    aria-label="Add Category"
    placement={{ base: 'top-end', md: 'auto-start' }}
    openDelay={500}
    hasArrow
>
    <IconButton
        aria-label="Add"
        onClick={() => onOpen()}
        margin={'auto'}
        icon={<AddIcon />}
        colorScheme={'blue'}
        cursor={'pointer'}
        size={'md'}
        rounded={'lg'}
    />
</Tooltip>
```

### Alternatives

Rework my components to make the tooltip fit better. 

### Additional Information

Using `placement={{ base: 'top', md: 'left' }}` shows the following errors: 
.tsx error in editor: 
```
Type '{ base: string; md: string; }' is not assignable to type 'PlacementWithLogical | undefined'.ts(2322)
```
error in browser on loading the Tooltip component:
```
Unhandled Runtime Error
TypeError: placement.split is not a function
```
![image](https://user-images.githubusercontent.com/46366395/232183003-d618fd39-62df-425d-bb50-0a6173073568.png)

**Comment by segunadebayo** [comment]
Hi @mikikiv,

Please use the `useBreakpointValue` hook for this use case.
