### ISSUE TITLE
How to use dark theme with Vite and Chakra UI

### ISSUE THREAD

**Issue by Jamzy01** [chakra-ui/chakra-ui#7574]
### Description

When I tried following the customizing theme tutorial at https://chakra-ui.com/getting-started/vite-guide and tried using that knowledge to set the theme to dark, nothing seems to change.

```jsx
import * as React from "react";
import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import * as ReactDOM from "react-dom/client";
import App from "./App";

const config = {
  initialColorMode: "dark",
  useSystemColorMode: false,
};

// 3. extend the theme
const theme = extendTheme({ config });

const rootElement = document.getElementById("root");
ReactDOM.createRoot(rootElement).render(
  <React.StrictMode>
    <ChakraProvider theme={theme}>
      <App />
    </ChakraProvider>
  </React.StrictMode>
);
```

### Link to Reproduction

I can't link to a reproduction because I believe that it is only an issue for Vite

### Steps to reproduce

```jsx
import * as React from "react";
import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import * as ReactDOM from "react-dom/client";
import App from "./App";

const config = {
  initialColorMode: "dark",
  useSystemColorMode: false,
};

// 3. extend the theme
const theme = extendTheme({ config });

const rootElement = document.getElementById("root");
ReactDOM.createRoot(rootElement).render(
  <React.StrictMode>
    <ChakraProvider theme={theme}>
      <App />
    </ChakraProvider>
  </React.StrictMode>
);
```

### Chakra UI Version

2.5.5

### Browser

Microsoft Edge Version 112.0.1722.46 (Official build) (64-bit)

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by dvartic** [comment]
Hello. I cannot reproduce your issue. The config seems to be applying correctly using Vite. Are you testing your color mode config using browser's private window? Else Chakra will had stored a localstorage variable poiting to a colorMode, thus ignoring your config.

**Comment by Jamzy01** [comment]
Thank you so much, I didn't realize that Chakra UI was saving this. I do now realize that the docs explain how the system works fairly well, although I was fairly sure it was a problem with me using Vite as I noticed that the implementations for this vary from different libraries. Thank you for explaining this, and I'm sorry for opening an unnecessary issue when I should have read the docs thoroughly beforehand.
