### ISSUE TITLE
next/image wrapper not forwarding onLoad* callbacks

### ISSUE THREAD

**Issue by olliejm** [chakra-ui/chakra-ui#7575]
### Description

When I passed `onLoadingComplete` callback to the image component from `@chakra-ui/next-js`, it is never invoked. If I instead use the component exported from `next/image` directly, it works as expected. Same also happened with `onLoad` and `onLoadingStart`. Sorry I'm currently pressed for time and struggling to get CodeSandbox to work properly in my browser. But if a reproduction on there is absolutely essential, I will make one at a later point.

### Link to Reproduction

N/A

### Chakra UI Version

2.5.5

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by hectoraldairah** [comment]
Can you please add a live reproduction of the issue?

**Comment by olliejm** [comment]
If absolutely necessary, but I think the problem is already clear here:
https://github.com/chakra-ui/chakra-ui/blob/main/packages/integrations/next-js/src/image.tsx#L9

Only `["width", "height", "src", "alt", "fill", "loading"]` are being forwarded to `next/image`, so seems the cause is already pretty clear and the behaviour I see would be expected with the current implementation of the wrapper. 

Indeed if I copy that file and change it to `shouldForwardProp: () => true`, I see the behaviour I originally expected (that my `onLoadingComplete` callback gets fired).

**Comment by segunadebayo** [comment]
This has already been fixed in one of the recent PRs. We'll release an update shortly.

If the issue persists after the release, I'll re-open this issue.
