### ISSUE TITLE
@chakra-ui/next-js Image not passing through position/style props

### ISSUE THREAD

**Issue by Emperor-Koala** [chakra-ui/chakra-ui#7576]
### Description

I'm trying to build a file manager as part of a larger NextJS project, pulling the image url from a remote source to display the preview. However when I went to build the file preview, the image did not respect the area padding or the aspect ratio of the original image.

Looking through the documentation, NextJS calls out that the default behavior for the images when passing the `fill` prop is to assign position absolute to the image. I tried to override this by passing `style={{position: "unset"}}` and/or `position="relative"` with various values to no avail. Checking the generated source using inspect element, I could see that the `position: absolute` is passed directly as part of the `<img>` style, not as a class style. And to confirm that the `style` prop is not being passed through at all (or at least has no effect), I passed in `style={{display: "none"}}` to see if the image would disappear, but it did not.

### Link to Reproduction

https://codesandbox.io/p/sandbox/sweet-khayyam-o9cjdh?file=%2Fpages%2Findex.tsx

### Steps to reproduce

1. Load the provided reproduction
2. The preview on the right shows the issue

### Chakra UI Version

@chakra-ui/react@^2.5.5, @chakra-ui/next-js@^2.1.2

### Browser

Firefox 112

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by aboveyunhai** [comment]
@Emperor-Koala you have to pass either the height or width to parent or image itself, the component is based on the next.js image component, it has some really specific requirement.
this example it's just a parent container one based on the documentation.
```tsx
      <Box position={"relative"} height="500px or 100% of other element presents inside the box that allow the image to have a height" width={"100%"}>
          <Image
            src={imageUrl}
            alt=""
            fill={true}
          />
        </Box>
```
You can check the doc: https://nextjs.org/docs/api-reference/next/image

**Comment by Emperor-Koala** [comment]
What should I do in a situation where I do not know the dimensions/aspect ratio of the image ahead of time? Should I just resort to using a basic `<img />` tag? Or is there some other option I can use?

**Comment by aboveyunhai** [comment]
> What should I do in a situation where I do not know the dimensions/aspect ratio of the image ahead of time? Should I just resort to using a basic `<img />` tag? Or is there some other option I can use?

See your import , it's `import { Image } from "@chakra-ui/next-js"`
you can use the default `import { Image } from '@chakra-ui/react'`

**Comment by Emperor-Koala** [comment]
Ah, I see then. Thank you for your help!

**Comment by dvartic** [comment]
> What should I do in a situation where I do not know the dimensions/aspect ratio of the image ahead of time? Should I just resort to using a basic `<img />` tag? Or is there some other option I can use?

Hello. I also found issues with Next Image components. I find their docs a bit confusing. There are two ways to import images, one is static, using a js import statement, and the other is dynamic, providing an URL directly in your image component. If you use static import, you do not need to know dimensions ahead of time. Does this help your issue?

https://beta.nextjs.org/docs/optimizing/images#local-images
