### ISSUE TITLE
Hydration error using ChakraProvider with Next 13 (new app/ directory)

### ISSUE THREAD

**Issue by cosmoburn** [chakra-ui/chakra-ui#7578]
### Description

Hi, I have set up a brand new Next 13 project following the instructions [here](https://beta.nextjs.org/docs/installation)

I added <ChakraProvider> to `layout.tsx` as described in the Chakra documentation [here](https://chakra-ui.com/getting-started/nextjs-guide#app-directory-setup)

I expect this to work since I followed all the instructions and this is a clean project.

But instead I get this hydration error:
`Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.`
<img width="1085" alt="Screenshot 2023-04-16 at 3 22 17 PM" src="https://user-images.githubusercontent.com/9123901/232343098-27176225-d50b-4eae-b181-b7360d07c735.png">

I'm also seeing a warning on the console right before this error:
<img width="823" alt="Screenshot 2023-04-16 at 3 32 59 PM" src="https://user-images.githubusercontent.com/9123901/232343648-b4c58719-2fed-4fcb-bb34-33a8a87b2ebf.png">

and this error right after:
<img width="652" alt="Screenshot 2023-04-16 at 4 12 00 PM" src="https://user-images.githubusercontent.com/9123901/232345473-dcc56e49-e2e7-46fa-b8f8-7947fc1d00c0.png">

I can't get the code sandbox to work with next 13 but here is my exact components:

<img width="764" alt="Screenshot 2023-04-16 at 3 36 02 PM" src="https://user-images.githubusercontent.com/9123901/232343766-dee2bb35-4028-4476-9200-34e12b82b25f.png">
<img width="396" alt="Screenshot 2023-04-16 at 3 36 53 PM" src="https://user-images.githubusercontent.com/9123901/232343801-2884ba7d-b914-4506-841e-e8357ad9042e.png">
<img width="437" alt="Screenshot 2023-04-16 at 3 37 09 PM" src="https://user-images.githubusercontent.com/9123901/232343809-957ca386-7fed-4aa2-ae95-e0ee74713a9e.png">

### Link to Reproduction

https://codesandbox.io/s/chakra-hydration-error-13pg3f?file=/next.config.js

### Steps to reproduce

1. start new Next 13 peroject:
`npx create-next-app@latest --experimental-app`

2. install latest chakra-ui
`yarn add @chakra-ui/react @emotion/react @emotion/styled framer-motion`

3. Follow steps [here](url) to add ChakraProvider to `app/layout.tsx`
`https://chakra-ui.com/getting-started/nextjs-guide#app-directory-setup`

### Chakra UI Version

2.5.5

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I am attempting to use the new /app directory feature of Next 13

**Comment by cosmoburn** [comment]
I had something very silly wrong and now realized what it was....

I was trying to put the Provider outside the body

Fixing this got rid of the hydration error:
```
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
```

**Comment by danbeaumont95** [comment]
> I had something very silly wrong and now realized what it was....
> 
> I was trying to put the Provider outside the body
> 
> Fixing this got rid of the hydration error:
> 
> ```
> export default function RootLayout({
>   children,
> }: {
>   children: React.ReactNode;
> }) {
>   return (
>     <html lang="en">
>       <body>
>         <Providers>{children}</Providers>
>       </body>
>     </html>
>   );
> }
> ```

Legend 🙌
