### ISSUE TITLE
[Stack] Responsive direction prop: TypeError direction.endsWith is not a function

### ISSUE THREAD

**Issue by Zwooosh** [chakra-ui/chakra-ui#758]
**Describe the bug**
When providing the direction prop with responsive values (either an array or object). The app crashes on a Type error.

**Expected Behavior**
The direction prop should accept responsive values.

**To Reproduce**
- Use this template: https://codesandbox.io/s/typeerror-on-stack-direction-prop-7s9vy?file=/src/index.js
1. Open the link to see the error
2. If you change the props back to a non responsive string (e.g. `row`) the error disappears.

**Suggested solution(s)**
The Stack component uses `.endsWith` for the `isReversed` prop. This does not account for any responsive styles (i.e. not providing a string value).
```javascript
const _isReversed =
      isReversed || (direction && direction.endsWith("reverse"));
```
Refactoring or removing this prop should fix the issue.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version 0.8.0

**Comment by Zwooosh** [comment]
On closer inspection I noticed this prop is no longer available in the TS Release and should be resolved when `dev-ts` is merged.

**Comment by manjunathkg** [comment]
I am facing this exact same issue. My chakra-ui version is core:0.8.0 and chakra-ui/react at 1.7.4 I am on TS and trying to use the Stack component with direction property.

Can you please let me know which version I should pull to fix this issue?

Regards
M
