### ISSUE TITLE
Add `defaultIndeterminate` to the Checkbox component

### ISSUE THREAD

**Issue by GInTher** [chakra-ui/chakra-ui#7582]
### Description

When creating a `Checkbox`, you can assign it a `defaultChecked` prop, but not a `defaultIndeterminate`. There is however, an `isChecked` prop and an `isIndeterminate` prop.

### Problem Statement/Justification

More consistency! Having a checkbox that is `indeterminate` makes the API more consistent and in line with the HTML spec. If you were to set a Checkbox to `indeterminate` in HTML, you are able to change the state of it when it is clicked.

### Proposed Solution or API

Adding an `defaultIndeterminate` prop to behave the same was `defaultChecked`, which would accept a boolean.

### Alternatives

Managing things in state to set an `indeterminate` state, but it adds so much unnecessary complexity and state management to track and change the checked state.

**Comment by segunadebayo** [comment]
Hi @GInTher,

This seems like a user-land feature to me. You can achieve it with something like:

```tsx
function App(){
const [indeterminate, setIndeterminate] = useState()

useEffect(()=>{
  setIndeterminate(true)
}, [])

return <Checkbox indeterminate={indeterminate} />
}
```

I'll think about this later on but of the bat, I don't think we need to include this.
