### ISSUE TITLE
Problems arise with scrolling when both modals and drawers are open at the same time.

### ISSUE THREAD

**Issue by GabriPires** [chakra-ui/chakra-ui#7588]
### Description

During a specific use case where a confirmation modal was opened within a drawer, I observed that the modal's default scrolling behavior was not working as expected, as demonstrated. Users were unable to scroll through the modal using the mouse wheel, and instead, had to manually click and drag the screen. This issue greatly impacted the user experience and requires urgent attention to ensure seamless and intuitive navigation.

### Link to Reproduction

https://codesandbox.io/s/inspiring-ace-duk1bz?file=/src/index.tsx

### Steps to reproduce

1. Go to codesandbox demonstration
2. Click on 'Open Drawer'
3. Click on 'Open Modal'
4. Try to scroll with mouse wheel and see unexpected behavior

### Chakra UI Version

2.5.1

### Browser

Firefox 109.1

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by brunorangel1** [comment]
Following...

**Comment by segunadebayo** [comment]
Hi @GabriPires,

You need to put the modal inside the drawer for this to work.

Here: https://codesandbox.io/s/exciting-sea-qhvcbu?file=/src/index.tsx

**Comment by GabriPires** [comment]
> Hi @GabriPires,
> 
> You need to put the modal inside the drawer for this to work.
> 
> Here: https://codesandbox.io/s/exciting-sea-qhvcbu?file=/src/index.tsx

Thank you for bringing that. I had not considered utilizing the modal in that manner.

**Comment by oogxdd** [comment]
What if need modal to be outside of the Drawer (sometimes it's both Drawer+Modal are opened and sometimes I only need Modal to be displayed)?

**Comment by GabriPires** [comment]
> What if need modal to be outside of the Drawer (sometimes it's both Drawer+Modal are opened and sometimes I only need Modal to be displayed)?
> 
> 
> 
> upd: (right now i'm conditionally rendering modal in two places: within a Drawer and outside - based on whether Drawer is shown or no)

That is a valid question. I will also encounter use cases where the modal can be open either simultaneously with the drawer or on its own. I am uncertain about how to proceed in this scenario.

**Comment by colemars** [comment]
If your use case allows it, disable `blockScrollOnMount` on all modals that will be open at the same time and manage scroll lock with:

```ts
  const ref = useRef<HTMLElement>(document.body)
  useEffect(() => {
    ref.current.style.overflow = 'hidden'
    ref.current.style.touchAction = 'none'
  }, [])
```

**Comment by charlower** [comment]
> If your use case allows it, disable `blockScrollOnMount` on all modals that will be open at the same time and manage scroll lock with:
> 
> ```ts
>   const ref = useRef<HTMLElement>(document.body)
>   useEffect(() => {
>     ref.current.style.overflow = 'hidden'
>     ref.current.style.touchAction = 'none'
>   }, [])
> ```

saved me, thanks!

**Comment by afifalfiano** [comment]
> If your use case allows it, disable `blockScrollOnMount` on all modals that will be open at the same time and manage scroll lock with:
> 
> ```ts
>   const ref = useRef<HTMLElement>(document.body)
>   useEffect(() => {
>     ref.current.style.overflow = 'hidden'
>     ref.current.style.touchAction = 'none'
>   }, [])
> ```

Thank you,

**Comment by Yu-vo** [comment]
For ModalContent added:
```
onWheel={(e) => {
  e.stopPropagation();
}}
onTouchMove={(e) => {
  e.preventDefault();
  e.stopPropagation();
}}
onScroll={(e) => {
  e.preventDefault();
  e.stopPropagation();
}}
```
Scroll appeared in the modal.
This is works for me.

**Comment by dkrefta** [comment]
Thanks, @Yu-vo! You saved my life—I was going crazy with this bizarre scroll issue. I was considering removing this library from my project haha

**Comment by JoaoMagnago** [comment]
Segun's solution initially did not work for me, for I had only moved the modal inside the drawer, but not to the same level as where it was being opened. After moving the modal to the same level as the button that opened it (in my case, in a context menu inside the drawer header) the problem was solved.

Anyway, I just wanted to register the solution that worked for me. Beware because it may not and probably will not work for all cases.

Hoping that in v3 this doesn't happen anymore.

**Comment by Descatres** [comment]
> For ModalContent added:
> 
> ```
> onWheel={(e) => {
>   e.stopPropagation();
> }}
> onTouchMove={(e) => {
>   e.preventDefault();
>   e.stopPropagation();
> }}
> onScroll={(e) => {
>   e.preventDefault();
>   e.stopPropagation();
> }}
> ```
> 
> Scroll appeared in the modal. This is works for me.

This did the trick for me. Thanks!

**Comment by chanmakotoo** [comment]
@Yu-vo 
I lost 3 hours to this bug 😢 
thank you ❤️
```
<ModalContent
    onWheel={(e) => {
        e.stopPropagation();
    }}
    onTouchMove={(e) => {
        e.preventDefault();
        e.stopPropagation();
     }}
    onScroll={(e) => {
        e.preventDefault();
        e.stopPropagation();
     }}
 >
```

**Comment by rishabhjaiz** [comment]
Can anyone explain why did it fix the problem?
