### ISSUE TITLE
Using Gatsby's Head API will initialise the Chakra UI custom theme you specified. 

### ISSUE THREAD

**Issue by Ryong-E** [chakra-ui/chakra-ui#7589]
### Description

Using the Head API will change the chakra UI theme to the default theme.
Looking through the developer tools, I noticed that when accessing a page with the Head API applied, a style tag is added inside the head tag.
The theme I defined will be applied as the default theme

<img width="710" alt="Screen Shot 2023-04-19 at 16 15 39" src="https://user-images.githubusercontent.com/96985256/232996860-54ba4ff4-f7c3-4875-bfbb-3ac64c31affc.png">

i defined custom theme

<img width="733" alt="Screen Shot 2023-04-19 at 16 16 38" src="https://user-images.githubusercontent.com/96985256/232997220-865eb2f9-60b0-49ce-aeb0-c31ed41490eb.png">

I'm using this component as a wrapPageElement in gatsby-browser and gatsby-ssr

<img width="540" alt="Screen Shot 2023-04-18 at 22 20 56" src="https://user-images.githubusercontent.com/96985256/232995649-dde44fff-b8af-4069-81b8-b4ffeac2e60a.png">

The image is a style in the head tag on a page without the Head API applied.
The theme I defined will be applied as normal

<img width="555" alt="Screen Shot 2023-04-18 at 22 21 06" src="https://user-images.githubusercontent.com/96985256/232996232-a32da9a3-e5f8-4100-a1ec-37b36f367c70.png">

The image is the style inside the head tag when you navigate to a page with the Head API applied.
You can see that the style tag has been added differently from the previous picture.
Because of this behaviour, the theme I defined is not applied

Ps)
 I found an additional workaround Putting the body in the cssVarsRoot property of the ChakraProvider works.

Do I have to use ChakraProvider's cssVarsRoot property to use gatsby's head API?

### Steps to reproduce

that's link my blog github

1. Adding a head to a template
2. npm start, then custom theme test
3. Delete head if it exists in the template
4. start custom theme test

### Chakra UI Version

2.5.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

You are using the latest version of Gatsby, and your node is version 18 LTS

**Comment by LekoArts** [comment]
You should use https://chakra-ui.com/getting-started/gatsby-guide instead of defining your own providers.

As per https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/#usage-notes you need to use `wrapRootElement`, not `wrapPageElement` for the provider. And that's what the existing plugin is already doing.

**Comment by Ryong-E** [comment]
@LekoArts 
I've installed and applied the plugin as per the official documentation.
Since it's a UI related component, shouldn't I use wrapPageElement?

**Comment by Ryong-E** [comment]
@LekoArts 
When not using the Head API,
wrapRootElement will apply my custom theme and then flicker back to the default theme.
Only by using wrapPageElement will my custom theme be applied.

Currently, I am using the template to generate pages via gatsby-node.
If I apply the Head API to the template and test it, I get the following result
The template screen without Head API is applied with the custom theme I defined, but when I go to the page with Head API, it is set to the default theme and fixed.
When I go to the page with Head API, the style tag is added to the head tag.

I wonder if it's just me...

I think it's better to see for yourself.
Here is the link to my project on GitHub
https://github.com/Ryong-E/HanDongRyong.com

In the main branch
1. npm install
2. npm start
3. change dark mode
As usual, you can see the colour gray.800 that I defined is applied
After that, apply the Head API to any of the AllPostTemplate or PostPage in the template folder, and npm start again, and you'll see the
you will see the default theme applied

**Comment by Ryong-E** [comment]
@LekoArts 
Even when I apply the method you described
I'm not getting the results I want

**Comment by segunadebayo** [comment]
Closing based on https://github.com/chakra-ui/chakra-ui/issues/7589#issuecomment-1514273758
