### ISSUE TITLE
Avatar's background may be transparent on re-render

### ISSUE THREAD

**Issue by evanjellis** [chakra-ui/chakra-ui#7591]
### Description

When multiple Avatar components get re-rendered, it's possible for the --avatar-background CSS variable to be missing on the Avatar without a `src` value.

**Example (linked CodeSandbox):**
Given the following code:
```
const [value, setValue] = React.useState(true);
return (
  <>
    <Button onClick={() => setValue(!value)}>Toggle</Button>
    {value ?
      <>
        <Avatar name="Test Name" />
        <Avatar src="https://bit.ly/dan-abramov" />
      </>
      :
      <>
        <Avatar src="https://bit.ly/dan-abramov" />
        <Avatar name="Test Name" />
      </>
    }
  </>
);
```
It renders:

<img width="294" alt="image" src="https://user-images.githubusercontent.com/109565456/233207119-0d84cdc8-33c6-487c-8563-704117bd9afd.png">

![image](https://user-images.githubusercontent.com/109565456/233207561-78e56660-c8aa-46d6-9f61-9733fcac3fa9.png)

After the "Toggle" button is clicked, it renders:

<img width="281" alt="image" src="https://user-images.githubusercontent.com/109565456/233207739-eda5f269-251f-46ea-80e4-bdde29f146c6.png">

![image](https://user-images.githubusercontent.com/109565456/233207957-f1ffc1d2-f905-418e-aa83-d655c889e842.png)

The --avatar-background CSS variable is missing, making the background transparent.

**Example occurrences from my app:**

- When a parent component is re-rendered due to a client-side sort/filter:

<img width="234" alt="image" src="https://user-images.githubusercontent.com/109565456/233209277-602b6198-cb07-4a11-b250-bbd152b431ca.png">

- When a list of Avatars are re-rendered due to an incoming web socket message:

<img width="238" alt="image" src="https://user-images.githubusercontent.com/109565456/233209974-3c056c30-c261-4669-a2d6-9e07786225ce.png">
<img width="143" alt="image" src="https://user-images.githubusercontent.com/109565456/233210049-c54cb639-3086-43e9-8787-7e848c015588.png">

### Link to Reproduction

https://codesandbox.io/s/vigorous-sound-dqq5nw?file=/src/index.js

### Steps to reproduce

1. Have list of Avatar components rendered, 1+ with `src` and 1+ without
2. Trigger re-render via a state change that changes the list
3. Observe Avatar(s) without `src` has transparent background

### Chakra UI Version

@chakra-ui/react ^2.2.4

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by giovanijfc** [comment]
Hi,

Add a key in tag Avatar resolve the problem for me.

Sample code:

`  
<Avatar
    key={`${name}-${img}`}
    src={img ? img : undefined}
    name={name}
 />
 `

**Comment by yarinsa** [comment]
@giovanijfc Thanks! You resolved my issue,

**Comment by Glognus** [comment]
Same error for me

**Comment by YuriGabrielR** [comment]
> Hi,
> 
> Add a key in tag Avatar resolve the problem for me.
> 
> Sample code:
> 
> ` <Avatar key={${name}-${img}} src={img ? img : undefined} name={name} />`


I tried this way, but the error persists

**Comment by segunadebayo** [comment]
Closing based on https://github.com/chakra-ui/chakra-ui/issues/7591#issuecomment-1684054430
