### ISSUE TITLE
Modal edges break when toggling elements inside of it, Safari 16.4

### ISSUE THREAD

**Issue by solestravis** [chakra-ui/chakra-ui#7593]
### Description

When displaying a modal and having items show up/hide on it, the modal edges/borders break.

When toggling a button:

![image](https://user-images.githubusercontent.com/42306533/233696670-57a9ff9e-6c09-4057-8d37-5191d1238b3b.png)

On load, occurs when PayPal button takes a while to load.

![image](https://user-images.githubusercontent.com/42306533/233696708-793f1e08-f883-4ee8-8e47-38b2462f378c.png)

When resizing the screen it fixes itself, but the issue occurs again on refresh.

### Link to Reproduction

https://app.vidiq.com/auth/login

### Steps to reproduce

Apologies I couldn't reproduce on a codesandbox environment, and instead had to redirect you to our prod site 😅 
1. Create an account (it's free). You may need to authenticate a youtube channel to go to the next page. Feel free to create a throwaway account for this. 
3. Head over to `/plans`
4. Click on any of the upgrade links which will trigger the modal.
5. Adding/canceling out of a promo code will cause the PayPal button to hide/show and the issue to occur. 
(See a gif below for reference)

### Chakra UI Version

1.8.7

### Browser

Only see the issue on Safari 16.4 (18615.1.26.11.23)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

See below a gif that displays the issue when toggling the PayPal button.

![amazing_2023_04_21_16_06_13](https://user-images.githubusercontent.com/42306533/233698948-9d022f72-ce47-429d-8fd2-027757078c8d.gif)

**Comment by segunadebayo** [comment]
Hey @solestravis,

We stopped shipping updates to v1.8.7 so I'm not able to help here unfortunately.

This might be related to version of framer-motion you're using. Consider downgrading framer-motion or upgrading the Chakra UI version.

**Comment by adam-stanek** [comment]
Hi guys,

I am having the same issues with v2.7.1 and (10.12.16 framer-motion). Safari 16.5. 

@segunadebayo Can we reopen?

@solestravis Did you managed to solve it somehow?

**Comment by adam-stanek** [comment]
Decided to create a separate issue for it with easy to reproduce steps (#7787)
