### ISSUE TITLE
Link is not affected by textDecoration="none" while hovering

### ISSUE THREAD

**Issue by avintimilsina** [chakra-ui/chakra-ui#7594]
### Issue
Link component is not affected by `textDecoration="none"` attribute. Even in the chakra UI docs if you change the code in the CodeSandbox from: 

`<Link textDecoration={"underline"} href="https://chakra-ui.com">` 
to 
`<Link textDecoration={"none"} href="https://chakra-ui.com">`

 and refresh the CodeSandbox, the underline is still present when you hover over the link.

### Work around 
The only way to remove underline from the Link component is to use inline CSS.

```<Link href="https://chakra-ui.com" style={{ textDecoration: "none" }} >```

This removes the underline when you hover over the Link component.

### Link to Reproduction

https://codesandbox.io/s/quiet-sea-znubij?file=/src/index.tsx

### Steps to reproduce

1. Go to [https://codesandbox.io/s/quiet-sea-znubij?file=/src/index.tsx](url).
2. Let the app build.
3. Hover over  the text to see that the `textDecoration` is not working for the second example.
4. Ideal working of the `textDecoration="none"` should be like as the **Work Around** solution.

### Chakra UI Version

1.6.4

### Browser

Google Chrome Version 112.0.5615.138 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
You can fix this with `<Link _hover={{ textDecoration: "none" }} />`

**Comment by avintimilsina** [comment]
Thank You!

**Comment by ats1999** [comment]
How can i configure it into theme?

**Comment by Cally99** [comment]
Cringy bug and still not fixed in 2.2

**Comment by nathphil9411** [comment]
Thank you

**Comment by RaresGeo** [comment]
Using the `_hover` prop removes the colour change on hover of colorScheme. This should be addressed.
