### ISSUE TITLE
Theme driven component/variant values

### ISSUE THREAD

**Issue by pkrogel-kws** [chakra-ui/chakra-ui#76]
I think it would be beneficial pull component variant css values from the theme.  

For example, on Button, maybe I'd like to adjust the padding values of the different size variants.  This could by just using aliases where possible instead of array values directly.  As it is now, you'd have to adjust the value of a certain array scale, where as using a 'lg' alias that pointed to the key would allow for more customization.  Another place I am currently doing this is with border radius.  I have set the 'rounded' default prop to 'default', and added said key into the theme specification.

Alternatively, you could use styled-system variants to allow optional configuration.  Thoughts?

**Comment by segunadebayo** [comment]
Hi @pkrogel-kws ,

Let's say you created a button like this:

```jsx
<Button size="lg"/>
```
and you want to adjust the padding values, here's what you should do.

```jsx
// To change the padding
<Button size="lg" paddingX="12px" />

// To change the font-size
<Button size="lg" fontSize="18px"/>
```

The variant styles aren't baked in, we made it in a way that you can override them with style props.

I'm aware of the styled-system variants, I'm experimenting with it and would definitely use it in upcoming versions of Chakra.

**Comment by pkrogel-kws** [comment]
Right.  Now let's say you've built out a reusable theme driven template (using gatsby-themes).  I have a new client, and the design system for them is quite different.  

Since I've aliased some colors to they key 'primary' and 'secondary', my colors are easily switched out.  Now comes button styling.  If I've used the method you described, I'd have to change the paddingX and rounded props on every Button, and the theme is no longer drop-in and '100%' driven from the theme definition.  If you alias out the default values like I've suggested, you can still overwrite like you showed for one-offs.

Of course you could use a wrapping component and alias the size/padding keys yourself (which is what I've done), but I still think this approach sacrifices little while offering more customization for people that may want to alter their design system from the theme at the theme level vs component level.  Either way, I have a working solution, and this was only a suggestion.  Feel free to close if this approach just doesn't sound like something you'd consider.

**Comment by segunadebayo** [comment]
Hi @pkrogel-kws,

I understand your suggestion and will definitely look into it. Having variants accessible within the theme definition is in the roadmap since `styled-system` supports that. Chakra will support that soon.

Thanks for this.

**Comment by squ1sh** [comment]
I posted this comment on [this other issue](https://github.com/chakra-ui/chakra-ui/issues/159)  but figured I could post a [link to the codesandbox](https://codesandbox.io/s/determined-lederberg-2r3dz) here too.

It allows for multiple variants to be applied to a single component.  For example, `variant=[{'blue-text', 'fancy-border'}]` will apply the variants from left to right.

**Comment by talentlessguy** [comment]
@segunadebayo what is the priority of `variant` prop? I wanted to try to migrate from Rebass / Theme UI but it doesn't support variants so I can't do it now

**Comment by gopinav** [comment]
Same question. Trying to migrate from rebass and `variant` prop would help out so much! Any update on this?

**Comment by segunadebayo** [comment]
@talentlessguy  and @gopinav, we're adding support for this prop in the next major release

**Comment by nandorojo** [comment]
@segunadebayo That's great news! Not to add any pressure, but is there an expected release date / date range?

**Comment by talentlessguy** [comment]
Unstale it please, `variant` prop is still in demand :)

**Comment by with-heart** [comment]
`variant` support has been added in 1.0, which is currently published as an alpha under the `next` tag (`@chakra-ui/core@next`). The docs for this aren't published on the website just yet, but you can read them here: https://github.com/chakra-ui/chakra-ui/tree/master/website/docs/theming

**Comment by talentlessguy** [comment]
@with-heart thanks for an update! Will wait till it becomes stable

**Comment by joernroeder** [comment]
coming from theme-ui this looks awesome! can not wait to give it a try!
