### ISSUE TITLE
Question on Nested Styling

### ISSUE THREAD

**Issue by neilchaudhuri** [chakra-ui/chakra-ui#760]
I am currently wrapping Chakra UI components inside a custom API for a component library I am building for my organization.  For example:

```
import {Link as ChakraLink} from "@chakra-ui/core";

const Link: React.FC<LinkProps> = (p: LinkProps) => {
    return <ChakraLink {...props}</ChakraLink>
};
```

For this `Link` object, I need the styles to be different according the the context in which they appear--particularly light v. dark background. In other words:

`<div class="light-background"><a href=...">Link</a>`

vs. 

`<div class="dark-background"><a href=...">Link</a>`

Naturally this would be accomplished in pure CSS with a class selector and nesting.

What is the best way to accomplish this with Chakra UI's theming capability?

**Comment by codebender828** [comment]
Hi @neilchaudhuri 

You can access the color mode on using the `useColorMode` hook that Chakra UI exports.

Here's an example in the docs on how to consume it and define an object of light and dark colors.

https://chakra-ui.com/color-mode#styling-color-modes

**Comment by neilchaudhuri** [comment]
Oh cool, thanks. And this works at local levels? By that I mean I am not alternating between dark and light modes for an entire theme. Rather the page is always white, but some sections are dark. So the links on the white portion of the screen would look different than on those little dark sections.

**Comment by codebender828** [comment]
Yeah. It works anywhere as long as your app is wrapped inside the ThemeProvider and ColorModeProvider components.

Typically this is done at setup.

https://chakra-ui.com/color-mode#enable-color-mode

**Comment by neilchaudhuri** [comment]
Great, thanks.

**Comment by neilchaudhuri** [comment]
I am running into a bit of an issue where the mode isn't toggling. This is my component:

```
const color = { light: "clickable", dark: "dark-background-link" };
const Link: React.FC<LinkProps> = (p: LinkProps) => {
    const { colorMode } = useColorMode();

    return <ChakraLink {...props} color={color[colorMode]}>...</ChakraLink>
};
```

In my Storybook I am doing this:

```
export const defaultLinkDarkBackground = () => {
    const {toggleColorMode} = useColorMode();
    useEffect(() => {
        toggleColorMode();
    });
    return (
        <ThemeProvider theme={theme}>
            <ColorModeProvider>
                <Box bg="primary" w="100%" p={4}>
                    <Link href="https://www.google.com">This goes to Google.</Link>
                </Box>
            </ColorModeProvider>
        </ThemeProvider>
    )
}
```

However, the link appears the same as it does when I don't toggle. Any advice on whatever silly thing I am doing wrong?

**Comment by neilchaudhuri** [comment]
It turns out I can just initialize the `ColorModeProvider` with dark and avoid the need to force a toggle altogether. I am still not clear why the call to `useEffect` didn't work, but it's overkill for this purpose nonetheless.

**Comment by ivan-kleshnin** [comment]
Is it still supported? I try 

```
export const theme = extendTheme({
  initialColorMode: 'light',
```

then

```
<LightMode>
  <Text>test</Text>
 </LightMode>
<DarkMode>
  <Text>test</Text>
</DarkMode>
```

and `<Text>` does not change the color within `DarkMode` boundaries. 
From the docs I've got an impression that dark mode is supported by default. I want to style a dark footer within an otherwise light theme...
