### ISSUE TITLE
Seems applying global style to Stack and Box elements not working

### ISSUE THREAD

**Issue by finlaydotb** [chakra-ui/chakra-ui#7601]
### Description

I am following the tutorial here https://chakra-ui.com/docs/styled-system/customize-theme and trying to set the borderRadius for `<Stack/>` basically what I have is

```
components: {
    Stack: {
      baseStyle: {
        borderRadius: '20px',
      },
    },
}
```

But unfortunately this did not work. doing this did not change the border radius. I also tried with `<Box/>` same result.

Any reason why this is happening and how do I set the radius globally?

### Link to Reproduction
https://codesandbox.io/s/chakra-ui-typescript-pomi8?file=/package.json

### Steps to reproduce

1. Set the borderRadius in the baseStyle in the theme for <Stack/>
2. Use the <Stack/> component
3. Notice that no border radius is applies

### Chakra UI Version

2.6.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @finlaydotb,

Those layout components are not designed to be connected to the theme. I recommend creating a shared component in your codebase instead.

**Comment by finlaydotb** [comment]
Thanks for the response. Is there a way I can know which components can be styled from the theme, and which ones cannot?
