### ISSUE TITLE
[BUG] Remove LGTM badge from `README.md`

### ISSUE THREAD

**Issue by Panquesito7** [chakra-ui/chakra-ui#7604]
### Description

The `README.md` still contains a badge of LGTM, however, LGTM is now replaced by [CodeQL](https://github.com/github/codeql).
The badge must be removed, and potentially add a [CodeQL](https://github.com/github/codeql-action) workflow in the repository.

For more information, see: https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

### Link to Reproduction

I don't think this applies here.

### Steps to reproduce

Not applicable.

### Chakra UI Version

Not applicable.

### Browser

Microsoft Edge 112.0.1722.58

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Done!
