### ISSUE TITLE
Request to add Arabic and indian Documentation (طلب إضافة توثيق عربي وهندي)

### ISSUE THREAD

**Issue by Aziz-crypto** [chakra-ui/chakra-ui#761]
**Is your feature request related to a problem? Please describe.**
Some arab and hindu people have difficulty with coding in english, depending on the region

**Describe the solution you'd like**
Add arabic and indian documentation

**Comment by with-heart** [comment]
@Aziz-crypto We would love to have translations available for all languages and this is something we have discussed before. Any chance you'd be able to help us with translations?

**Comment by Skia69** [comment]
> @Aziz-crypto We would love to have translations available for all languages and this is something we have discussed before. Any chance you'd be able to help us with translations?

Hello, i can help with the Arabic translation if need be
I'm a native Arabic speaker

**Comment by with-heart** [comment]
Hi @Skia69, thanks for volunteering! We aren't yet at a place where we support translations, but once we do, we'll be sure to get you involved!
