### ISSUE TITLE
Mapping through array of users with AvatarGroup

### ISSUE THREAD

**Issue by jonathon-neoswap** [chakra-ui/chakra-ui#7616]
### Description

I am mapping through an array of users, and for each item, I am returning an `<Avatar...`. However, it renders the same class for each item which causes some strange visual behavior (not stacking).

The issue (I think) is caused by me calling `<Avatar` from a separate component. Is there a way to prevent this, or must I move my logic into the same file as my `<AvatarGroup` ?

![image](https://user-images.githubusercontent.com/131686268/235529873-c1541559-a0af-4f7e-99d6-c7b08fdc37f0.png)

(The third element is a hard-coded `<Avatar...` item. 

### Link to Reproduction

https://codesandbox.io/s/busy-cloud-iu9h9i?file=/src/index.js

### Chakra UI Version

2.5.1

### Operating System

- [x] macOS
- [x] Windows
- [x] Linux

**Comment by segunadebayo** [comment]
Hi @jonathon-neoswap,

This is happening because the AvatarGroup uses cloneElement, so please make sure that you spread the remaining props to the AvatarItem.

Here's an example:

```jsx
export default function App({ image, name, ...rest }) {
  return <Avatar name={image} src={name} {...rest} />;
}
```
