### ISSUE TITLE
[Component] Gatsby Chakra UI plugin does not support color mode without ResetCSS

### ISSUE THREAD

**Issue by slaking** [chakra-ui/chakra-ui#762]
**Describe the bug**
In this configuration:
>     {
>       resolve: "gatsby-plugin-chakra-ui",
>       options: {
>         isResettingCSS: false,
>         isUsingColorMode: true,
>       },
>     },
Dark mode does not work.

**Expected Behavior**
I would expect it to work. If I set "isResettingCSS" to true, then it works.

**To Reproduce**
See above using the starter project.

**Suggested solution(s)**
-

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari

**Comment by with-heart** [comment]
Hi @slaking, this issue should be resolved in our 1.0 pre-release. It's published as `gatsby-plugin-chakra-ui@1.0.0-next.3`. You'd need to be using `@chakra-ui/core@1.0.0-next.3` as well.

See https://next.chakra-ui.com/guides/how-to-create-a-guide for more information.
