### ISSUE TITLE
Font size is one too big on firefox

### ISSUE THREAD

**Issue by ShyAssassin** [chakra-ui/chakra-ui#7620]
### Description

When using a `Text` component and adding a fontsize, the fontsize will appear as the value define but plus one on firefox on mac (and presumably linux), this only happens on firefox and not any other browser i have tried.

Left is safari right is firefox both on the same site.
<img width="1728" alt="Screenshot 2023-05-02 at 18 40 37" src="https://user-images.githubusercontent.com/49711232/235742498-2a77674c-4d85-4080-9fde-62c1a2ce58c4.png">
Same thing but using a minimal example
<img width="1726" alt="Screenshot 2023-05-02 at 19 51 42" src="https://user-images.githubusercontent.com/49711232/235745372-8db7dd45-2bc0-4393-8c9f-16e249943a50.png">

### Link to Reproduction

https://codesandbox.io/p/sandbox/vibrant-frost-39m8bj?welcome=true

### Steps to reproduce

1. have 2 browsers one of the being firefox
2. open https://39m8bj-3000.csb.app/ in both browsers
3. see that the fontsize in firefox is one bigger than its supposed to be even though it reports the correct size

### Chakra UI Version

1.6.0

### Browser

Firefox

### Operating System

- [X] macOS
- [ ] Windows
- [X] Linux

### Additional Information

I have only seen this bug occur on Mac but not windows i assume that this would also occur on linux.

**Comment by segunadebayo** [comment]
Hey @ShyAssassin,

This is not a Chakra UI bug but perhaps a browser inconsistency. Consider passing the fontSize prop and setting it to a pixel value to investigate further.
