### ISSUE TITLE
Accordion/Modal animation bug on Safari

### ISSUE THREAD

**Issue by justin-gurtz** [chakra-ui/chakra-ui#7622]
### Description

When an `Accordion` is used inside a `Modal`, the height animation is glitchy (see video). I believe this is a bug related to WebKit and/or Safari.

Applying `overflow="auto"` on `ModalContent` and `transform="translate3d(0,0,0)"` on `Accordion` fixes the issue for me locally, however I wasn't able to fix the issue in the sandbox and I'm not sure why.

### Link to Reproduction

https://codesandbox.io/s/keen-dew-9qdcjp?file=/pages/index.tsx

### Steps to reproduce

1. Place an `Accordion` inside a `Modal`
2. Toggle an `AccordionItem`

### Chakra UI Version

2.5.5

### Browser

Safari 16.4

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

https://user-images.githubusercontent.com/40037115/235928531-61b611ca-4d74-4719-bf44-4e13819d550b.mov

**Comment by yellow-mi** [comment]
Hi Justin, I'm facing the same issue using the Accordion, but outside a Modal component, have you figured it out a solution?

**Comment by segunadebayo** [comment]
Closing based on your suggested fix:

> Applying overflow="auto" on ModalContent and transform="translate3d(0,0,0)" on Accordion
