### ISSUE TITLE
Content of the Popover inside InputGroup gets behind input elements

### ISSUE THREAD

**Issue by paradox37** [chakra-ui/chakra-ui#7629]
### Description

For a long time a was on ChakraUI 2.3.6. Now I upgraded to the 2.6.1. I noticed that my custom select is getting behind other elements right after upgrade. I made custom select using Popover. 

This seems to be caused by isolation in InputGroup. Putting isolation auto to InputGroup resolves the issue. 

This is the PR that is causing this: https://github.com/chakra-ui/chakra-ui/pull/7104

But I guess there was a reason for doing what was done in the PR. So, can this be somehow solved without overriding isolation?

### Link to Reproduction

https://codesandbox.io/s/elegant-napier-zx5ml4

### Steps to reproduce

1. Click on the Trigger button
2. Input element which is under the button is visible through popover

### Chakra UI Version

2.6.1

### Browser

Edge 112, Firefox 112

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by xveganxxxedgex** [comment]
I'm hitting this issue too after upgrading. I have a form that has multiple selects and the dropdowns are now being placed underneath the subsequent input groups. Adding this to the overrides config fixes the problem, but this seems like a bug from the [mentioned PR](https://github.com/chakra-ui/chakra-ui/pull/7104).

```css
styles: {
    global: {
        ".chakra-input__group": {
            isolation: "auto !important",
        },
    },
},
```

**Comment by stanfortonski** [comment]
Same :/

**Comment by vitalijalbu** [comment]
Same issues, anyone got the solution?

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
