### ISSUE TITLE
Unable to render rich text using react portable text

### ISSUE THREAD

**Issue by pulkitvyas08** [chakra-ui/chakra-ui#7632]
### Description

When I try to render rich text that I've gotten from sanity (included in the sandbox) I expected for it to be rendered as I wrote it but from what I understand Chakra UI applies it's own styles and 

When I was facing the same issue with a string of rich text from some react rich text editor as WYSIWYG by simply using this:
```
<div
  dangerouslySetInnerHTML={{ __html: postContent.content }}
  className="renderer"
/>
```

But for the data I get from sanity that needs to be rendered by portable text, this can't be implemented (or at least not directly without some sort of transformation step). I even tried adding a `ChakraProvider` with `resetCSS={false}` for that particular component like this:

```
<ChakraProvider resetCSS={false}>
        <PortableText value={blog.body} components={ptComponents} />
</ChakraProvider>
```

But that didn't work either. 

So, is there any way to disable the Chakra UI CSS for a particular component?

### Link to Reproduction

https://codesandbox.io/s/upbeat-heisenberg-p8mmh8

### Steps to reproduce

1. Run the sandbox environment
2. Uncomment line 7 in `_app.tsx` and comment out line 8
3. Observe the difference in the text rendering

### Chakra UI Version

2.5.4

### Browser

Firefox, Chrome, Brave, Edge

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @pulkitvyas08,

You can use this:

```jsx
<Box
      sx={{
        "*": { all: "revert" },
      }}
    >
      <PortableText value={sanityBodyObj} />
    </Box>
```

https://codesandbox.io/p/sandbox/nervous-bell-8qdvws?file=%2Fpages%2Findex.tsx%3A213%2C5-219%2C11
