### ISSUE TITLE
Card prop colorScheme does nothing.

### ISSUE THREAD

**Issue by tophermurphy** [chakra-ui/chakra-ui#7643]
### Description

Adding the colorScheme prop has no effect on the Card component and I don't see it being used in the code. Please, remove from docs and typescript props until it is functional.

### Link to Reproduction

https://codesandbox.io/s/sweet-tristan-crvimt?file=/src/index.tsx

### Steps to reproduce

Use Card component with prop colorScheme="red"

### Chakra UI Version

2.5.5

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is by design. The default styles don't implement colorScheme.

Feel free to add it yourself if you need to support it.

**Comment by lichtner** [comment]
I struggle to add colorScheme to Card component. I was not able to find any useful information about it. Nothing in documentation or any online article.

@tophermurphy did you find any solution?

@segunadebayo do you know how to add colorScheme to Card e.g. red, blue?

**Comment by mikemajara** [comment]
> This is by design. The default styles don't implement colorScheme.

If this is the default, having it listed in the Props tab of the component might be misleading.
