### ISSUE TITLE
Add isFitted to Tabs defaultProps type

### ISSUE THREAD

**Issue by baumandm** [chakra-ui/chakra-ui#7646]
### Description

The `defaultProps` type for the Tabs component theme doesn't include `isFitted`, so attempting to override it causes a Typescript error.  However, the functionality works as expected when setting `isFitted: true`.  It is desirable from a theming perspective to set all tabs to fitted, so I'm requesting to update the type to accommodate this.

```
const defaultProps = {
  isFitted: true
};

export const tabsTheme = defineMultiStyleConfig({ defaultProps });
```

This gives the following Typescript error:

```
Type '{ isFitted: boolean; }' has no properties in common with type '{ size?: string | number | undefined; variant?: string | number | undefined; colorScheme?: string | undefined; }'.ts(2559)
```

### Link to Reproduction

https://codesandbox.io/s/weathered-frost-vpnism

### Steps to reproduce

1. See the tabs are fitted correctly
2. Open theme.ts and see the Typescript error

### Chakra UI Version

2.6.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @baumandm,

I've mentioned this in past issues, but I'm happy to explain this again.

The theming system's `defaultProps` refers to the default values of `variant`, `size`, and an optional `colorScheme` property, not the props for the component.

Consider using the good'ol defaultProps or creating a custom component wrapper that adds the default props you want.
