### ISSUE TITLE
Popover stays in DOM on close

### ISSUE THREAD

**Issue by StrangersSoftware** [chakra-ui/chakra-ui#7647]
### Description

![popover](https://github.com/chakra-ui/chakra-ui/assets/15338501/b26546eb-2782-4b23-bf40-76c90d728437)

```
<Popover isLazy isOpen={itemId === item.id} key={item.id} onClose={() => setItemId(-1)} onOpen={() => setItemId(item.id)} >
    <PopoverTrigger>
      <Flex {...mMenu} alignItems="center" color={isSelected(item) && 'textSection'} flexDir="column"
        h="100%" justifyContent="center" onClick={() => handleItemClick(item)} w="100%" >
        <item.icon boxSize={6} mb={1} />
        { Translate(item.caption) }
      </Flex>
    </PopoverTrigger>
    { item?.items && (
      <PopoverContent bg="bgSecondary" shadow="0 0 5px black" rounded={3} w="fit-content" >
        <PopoverBody px={2} pb={0}>
          <Flex flexDir="column">
            { item.items.map(renderSubItem) }
          </Flex>
        </PopoverBody>
      </PopoverContent>
    ) }
 </Popover>
```

Sandbox link is FAKE!

### Link to Reproduction

https://codesandbox.io/s/demo-chakra-popover-component-75r3n

### Steps to reproduce

1. Just check gif and my code in description.

### Chakra UI Version

2.6.1

### Browser

Chromium 111.0.5563.41

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jonahallibone** [comment]
+1 On this, seeing the same behavior. Popover is closed but still present in the DOM and `visibility` is still set to `visible`
<img width="2227" alt="Screenshot 2023-05-23 at 5 56 35 PM" src="https://github.com/chakra-ui/chakra-ui/assets/8886318/09779b60-46f7-455f-9537-4fbdfc1cd6d3">

**Comment by segunadebayo** [comment]
Hi @jonahallibone,

Due to the desired semantics of the popover (positioning and accessibility), it's required for the popover element to remain in the DOM. When you use the `isLazy` property, the PopoverContent's "children" is unmounted from the DOM, so there should be no issues.

**Comment by jonahallibone** [comment]
@segunadebayo unfortunately the elements behind the area where the popover was become unclickable

**Comment by NathanPB** [comment]
Having the elements behind it not clickable is causing me a major headache, probably to other people as well. Can we please re-open this issue? It's still a problem

I have no background in the internals of Chakra, but I believe that both of those properties should be `visibility: hidden` when the dropdown is closed. If you manually change the `visible` one to `hidden the DOM becomes clickable again`
![image](https://github.com/chakra-ui/chakra-ui/assets/18128642/bca5ed57-7e54-4541-bf7f-54c153669047)

Also, notice that in that image that my first month selector (partially hidden by the firefox devtools tooltip) is outlined with blue, this means that my disclosure has `isOpen` as `true` even when the popover is hidden. I believe that all of that is related.


# WORKAROUND

For the time being, I found a hacky workaround that makes it work back as expected. If you put a `key={Math.random()}` in the `Popover` element then both of those `visibility` attributes becomes `hidden` when the popover contents are hidden and the whole thing starts to work again. Worked for me in controlled popovers.

**Comment by jnorris441** [comment]
This workaround did not work for me unfortunately. Cannot click through the hidden popover.

**Comment by ITSjwags** [comment]
Some additional context to what I'm seeing as well. Might be specific to me, but the `PopoverContent` with the class `chakra-popover__popper` will stay with `visibility: visible` if you click the `PopoverTrigger` to open AND close the content. If you use the trigger to open and not close, and click elsewhere to close, the content seems to get `visibility: hidden` as expected.
