### ISSUE TITLE
Add _complete, _incomplete, _active to Stepper indicator

### ISSUE THREAD

**Issue by srowe0091** [chakra-ui/chakra-ui#7648]
### Description

For the Stepper component, it would be much easier to add tokens for each state of the indicator to be able further customize them.

### Problem Statement/Justification

Currently to get around customizing the indicators, we have to use data selectors like so
```
...
baseStyle: {
  indicator: {
    "&[data-status=complete]": {
      background: "yellow"
    }
  }
}
...
```

### Proposed Solution or API

With the addition of the tokens, the issue can be simplified to just 

```
...
baseStyle: {
  indicator: {
    _complete: {
      background: "yellow"
    }
  }
}
...
```

### Alternatives

using the data selector, but thats not intuitive, as I had to dig inside the theme of the component in order to over ride the styles. The docs doesn't mention how to do this.

**Comment by telip007** [comment]
+1 It should either be stated in the docs or should work with the tokens (this I would prefer).

**Comment by ashatat** [comment]
Is there a workaround for this?

**Comment by zdziczkowski** [comment]
@ashatat - not that I have found or heard yet. In case it is helpful, here is the full file on how I themed my Stepper component:

```
export default {
  baseStyle: {
    title: {
      pb: 1,
      fontSize: "16px",
      lineHeight: "22px",
      fontWeight: "bold",
      color: "brand.black",
    },

    description: {
      fontSize: "16px",
      lineHeight: "22px",
      color: "brand.black",
    },

    indicator: {
      bgColor: "brand.white",
      borderColor: "brand.lightBlue",

      "&[data-status=complete]": {
        bgColor: "brand.blue",
        borderColor: "brand.blue",
        borderWidth: "3px",
      },

      "&[data-status=active]": {
        bgColor: "transparent",
        borderColor: "brand.blue",
        borderWidth: "3px",
      },

      "&[data-status=incomplete]": {
        bgColor: "transparent",
        borderColor: "brand.lightBlue",
        borderWidth: "3px",
      },
    },

    separator: {
      bgColor: "brand.lightBlue",
    },

    icon: {
      borderColor: "brand.blue",
      bgColor: "transparent",
    },
  },
};

```

**Comment by fzn0x** [comment]
I'm stuck on this because it's undocumented, tried to find `StepStatus` theming, it didn't work before I found this issue.

**Comment by segunadebayo** [comment]
Just added support for `_complete` and `_incomplete`. 

Please be sure to watch out for the next minor release (2.10.x)
