### ISSUE TITLE
Support for NextJS 13 App Router

### ISSUE THREAD

**Issue by 1M4nt0** [chakra-ui/chakra-ui#7649]
### Description

Actually new App Router feature of NextJS is unsupported due to no components are implemented with "use client" specification.
Implementing Chackra UI components for this new feature of Next is a big step forward in the adoption of the App Router, that I think it's a great alternative to Pages.

### Problem Statement/Justification

I think lot of people want to adopt NextJS App Router but almost all libraries are not currently supporting that. 
It is very difficult to get around problems for UI libraries that can present if they are not supported and Chackra UI can be a pioneer for the others.

### Proposed Solution or API

It should be only necessary to add "use client" specification up on all Chackra UI components.

### Alternatives

NextJS documentation indicates that for getting around this issue, components can be wrapped in a "use client" component but is too inconvenient to do that.

**Comment by Saim1358** [comment]
I also want this fixed as soon as possible. I am facing much problems regarding this . I have tried too many ways like :

1. I made a component with 'use client" direction to manage all the providers.
2. I imported all the necessary components in a file which have use client direction and exported them to use in server components without adding use client direction.
3. I used @Chakra/next-js package to fix some problems regarding to link and late load problem.
But I faced some problem when i am using cacheProvider from this pakage. All of my buttons had gone . But when I move mouse over it , it shows the button but when I move away from the button the button had been disappeared.

This 3 ways doesn't help me a lot. Even, dev server's hot loading works very late with chakra ui.
Thus, I am facing too much problems. 


I am requesting to fix all of these problems. 🫠

**Comment by ozzyonfire** [comment]
This is kind of a hard and tricky problem to solve. 

Adding 'use client' to all of the Chakra react components isn't going to really "fix" anything. All that would do would force the component to render on the client, this isn't necessarily what we would want. 

Most likely there will be certain components that can be used with Server Components and others, like ones that rely on certain client-side hooks, that will have to be client-side components. 

I think there is an underlying issue with the way the provider works, as well as the way emotion injects styles into the client. 

You can read up on some of the other related issues:
https://github.com/emotion-js/emotion/issues/2928

and #7209.

However, you can absolutely use Chakra with the new app directory in Next.js. 

```typescript
// providers.tsx
'use client'
import { CacheProvider } from '@chakra-ui/next-js';
import { ChakraProvider } from '@chakra-ui/react';

export function Providers({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <CacheProvider>
      <ChakraProvider>
        {children}
      </ChakraProvider>
    </CacheProvider>
  )
}
```

Then import and use that in your layout.tsx or page.tsx while still keeping them Server Components

```typescript
import Providers from './providers';

export default async function Page() {
  // do any server component stuff here
  const items = await fetch('/api/items');
  
  return (
    <Providers>
      <Main items={items} />
    </Providers>
  )
}
```

**Comment by Saim1358** [comment]
> This is kind of a hard and tricky problem to solve.
> 
> Adding 'use client' to all of the Chakra react components isn't going to really "fix" anything. All that would do would force the component to render on the client, this isn't necessarily what we would want.
> 
> Most likely there will be certain components that can be used with Server Components and others, like ones that rely on certain client-side hooks, that will have to be client-side components.
> 
> I think there is an underlying issue with the way the provider works, as well as the way emotion injects styles into the client.
> 
> You can read up on some of the other related issues: [emotion-js/emotion#2928](https://github.com/emotion-js/emotion/issues/2928)
> 
> and #7209.
> 
> However, you can absolutely use Chakra with the new app directory in Next.js.
> 
> ```ts
> // providers.tsx
> 'use client'
> import { CacheProvider } from '@chakra-ui/next-js';
> import { ChakraProvider } from '@chakra-ui/react';
> 
> export function Providers({
>   children
> }: {
>   children: React.ReactNode
> }) {
>   return (
>     <CacheProvider>
>       <ChakraProvider>
>         {children}
>       </ChakraProvider>
>     </CacheProvider>
>   )
> }
> ```
> 
> Then import and use that in your layout.tsx or page.tsx while still keeping them Server Components
> 
> ```ts
> import Providers from './providers';
> 
> export default async function Page() {
>   // do any server component stuff here
>   const items = await fetch('/api/items');
>   
>   return (
>     <Providers>
>       <Main items={items} />
>     </Providers>
>   )
> }
> ```

I did this. But , this caused some performance issues during development.

I want a a particular pakage named "@chakra/next-js" which will be fully optimized with next js app router . I know there is already available a pakage named "@chakra/next-js" . But, that is not fully optimized with next js app router .

I want that normal react users will use only "@chakra/react"  and next js users will use only "@chakra/next-js" ( this will contain all the components).

I have 2 question regarding this . They are :

1. Is there running any development process for next js app router ?
2. How much time it will take ?

**Comment by jonoroboto** [comment]
Bumping, we are interested in this as well. Currently holding us back from using it on future projects

**Comment by mdovn** [comment]
I have another issue. Looks like nextjs try to import all chakra ui components even when I only import the button in dev mode. I think it is tree shaken just fine for production.
Hence, the reloading time when I iterate writing code is terrible.
Do I miss anything? Please show me your insight for this issue.

**Comment by Saim1358** [comment]
> I have another issue. Looks like nextjs try to import all chakra ui components even when I only import the button in dev mode. I think it is tree shaken just fine for production. Hence, the reloading time when I iterate writing code is terrible. Do I miss anything? Please show me your insight for this issue.

You can try some ways to fix this . See my previous comments where I explained all the ways to fix some problems regarding chakra ui and next js. I am not sure that it will be much helpfull for you . But you can try .....🙂


Link :  https://github.com/chakra-ui/chakra-ui/issues/7649#issuecomment-1545592370

**Comment by vagra** [comment]
I am very painful these days. I am trying to use the latest `next.js + chakra-ui + prisma.js` to generate a static website (SSG). I am using the `app router` layout recommended by the latest next.js, 

But firstly I have to write `'use client'` in every `page.tsx`, otherwise chakra will report an error. 

However, in this way, if I use `api` to access prisma to get data, when I try to generate a static site with `npm run build`, an error will be reported. 

And if I directly access prisma in the `page.tsx` through `getStaticProps()` to get data, an error will be reported saying that I cannot access prisma in the browser client.  

I even tried swr, but it just added complexity.  

Can anyone understand my pain? These days have been so painful and no progress at all.

**Comment by 1M4nt0** [comment]
I think, if you are learning NextJS for the first time start with pages layout. There are lot of more examples and tutorials on the web and it's way more supported by packages without doing tricks. On the otherside, if you are trying to migrate to NextJS 13 app router you have to be patient and trying to solve problems one by one. You can also start a project with pages layout and migrate later to the app router because at the moment are both supported concurrently.

**Comment by vagra** [comment]
Yes, I have now switched to the pages router, and chakra-ui can indeed be used normally.

**Comment by cam-eo** [comment]
I just setup a fresh NextJS app today `v13.4.3` with a blank homage page and just added ChakraUI and wrapped the `ChakraProvider` just like it says [in the docs](https://chakra-ui.com/getting-started/nextjs-guide) and ofcourse I used `"use client"` the homepage I get these errors out the gate:


```
Error: Hydration failed because the initial UI does not match what was rendered on the server.

Warning: Expected server HTML to contain a matching <span> in <html>.

See more info here: https://nextjs.org/docs/messages/react-hydration-error
```

```
Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
```

I'm guessing for now if we want to use ChakraUI we will have to continue with the `Page Router`?

**Comment by Saim1358** [comment]
> I just setup a fresh NextJS app today `v13.4.3` with a blank homepage (only a `<main>` tag inside) and just added ChakraUI and wrapped the `ChakraProvider` and `CacheProvider` just like it describes [in the docs](https://chakra-ui.com/getting-started/nextjs-guide#app-directory-setup) and ofcourse I used `"use client"` the homepage I get these errors out the gate:
> 
> 
> ```
> Error: Hydration failed because the initial UI does not match what was rendered on the server.
> 
> Warning: Expected server HTML to contain a matching <span> in <html>.
> 
> See more info here: https://nextjs.org/docs/messages/react-hydration-error
> ```
> 
> ```
> Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
> ```
> 
> I'm guessing for now if we want to use ChakraUI we will have to continue with the `Page Router`?
> 
> [My code](https://github.com/cam-eo/next13-chakraui).
> 
> 


You shouldn't use 'use client' directive in layout.tsx/jsx file . You should make a component ( with use cilent ) and render that in the layout.tsx file . 

I think this will solve your problem . 🙂

**Comment by cam-eo** [comment]
> > I just setup a fresh NextJS app today `v13.4.3` with a blank homepage (only a `<main>` tag inside) and just added ChakraUI and wrapped the `ChakraProvider` and `CacheProvider` just like it describes [in the docs](https://chakra-ui.com/getting-started/nextjs-guide#app-directory-setup) and ofcourse I used `"use client"` the homepage I get these errors out the gate:
> > ```
> > Error: Hydration failed because the initial UI does not match what was rendered on the server.
> > 
> > Warning: Expected server HTML to contain a matching <span> in <html>.
> > 
> > See more info here: https://nextjs.org/docs/messages/react-hydration-error
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm guessing for now if we want to use ChakraUI we will have to continue with the `Page Router`?
> > [My code](https://github.com/cam-eo/next13-chakraui).
> 
> You shouldn't use 'use client' directive in layout.tsx/jsx file . You should make a component ( with use cilent ) and render that in the layout.tsx file .
> 
> I think this will solve your problem . 🙂

Hi Saim. Thank you for that. However, if you look at my code that I shared you will see I have used `"use client"` in `providers.js`, `layout.js`, and `page.js` and the error still persists.

**Comment by Saim1358** [comment]
> > > I just setup a fresh NextJS app today `v13.4.3` with a blank homepage (only a `<main>` tag inside) and just added ChakraUI and wrapped the `ChakraProvider` and `CacheProvider` just like it describes [in the docs](https://chakra-ui.com/getting-started/nextjs-guide#app-directory-setup) and ofcourse I used `"use client"` the homepage I get these errors out the gate:
> > > ```
> > > Error: Hydration failed because the initial UI does not match what was rendered on the server.
> > > 
> > > Warning: Expected server HTML to contain a matching <span> in <html>.
> > > 
> > > See more info here: https://nextjs.org/docs/messages/react-hydration-error
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I'm guessing for now if we want to use ChakraUI we will have to continue with the `Page Router`?
> > > [My code](https://github.com/cam-eo/next13-chakraui).
> > 
> > You shouldn't use 'use client' directive in layout.tsx/jsx file . You should make a component ( with use cilent ) and render that in the layout.tsx file .
> > 
> > I think this will solve your problem . 🙂
> 
> Hi Saim. Thank you for that. 
> 
> However, if you look at my code that I shared you will see I have used `"use client"` in `layout.ts`, and `page.ts` and the error still persists.



You should not use 'use state' directive in layout and page.tsx file .Instead of doing this, do this ....

https://github.com/chakra-ui/chakra-ui/issues/7649#issuecomment-1545592370

**Comment by hb20007** [comment]
I have exactly the same hydration issue mentioned by @cam-eo in a blank Next.js 13 project with Chakra which I set up based on the instructions here: https://chakra-ui.com/getting-started/nextjs-guide

Adding or removing `'use client';` doesn't remove the errors.

I believe the errors are related to `<span id="__chakra_env" hidden=""></span>` which is probably not rendered on the server.

**Comment by cam-eo** [comment]
> > > > I just setup a fresh NextJS app today `v13.4.3` with a blank homepage (only a `<main>` tag inside) and just added ChakraUI and wrapped the `ChakraProvider` and `CacheProvider` just like it describes [in the docs](https://chakra-ui.com/getting-started/nextjs-guide#app-directory-setup) and ofcourse I used `"use client"` the homepage I get these errors out the gate:
> > > > ```
> > > > Error: Hydration failed because the initial UI does not match what was rendered on the server.
> > > > 
> > > > Warning: Expected server HTML to contain a matching <span> in <html>.
> > > > 
> > > > See more info here: https://nextjs.org/docs/messages/react-hydration-error
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ```
> > > > Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > I'm guessing for now if we want to use ChakraUI we will have to continue with the `Page Router`?
> > > > [My code](https://github.com/cam-eo/next13-chakraui).
> > > 
> > > 
> > > You shouldn't use 'use client' directive in layout.tsx/jsx file . You should make a component ( with use cilent ) and render that in the layout.tsx file .
> > > I think this will solve your problem . 🙂
> > 
> > 
> > Hi Saim. Thank you for that.
> > However, if you look at my code that I shared you will see I have used `"use client"` in `layout.ts`, and `page.ts` and the error still persists.
> 
> You should not use 'use state' directive in layout and page.tsx file .Instead of doing this, do this ....
> 
> [#7649 (comment)](https://github.com/chakra-ui/chakra-ui/issues/7649#issuecomment-1545592370)
> 
> Try This .... 🥰

This doesn't look like a solution. point 3 of [this](https://github.com/chakra-ui/chakra-ui/issues/7649#issuecomment-1545592370) even mentions that there is still an issue with `CacheProvider`.

Ofcourse I tried abstracting the providers to a separate component and applied `"use client"` but I get the same issue and from what I can see I am not the only one 

From what I can see, ChakraUI doesn't fully support NextJS App "Router yet". The documentation still mentions "Page Router" stuff like `_app`

**Comment by Saim1358** [comment]
> > > > > I just setup a fresh NextJS app today `v13.4.3` with a blank homepage (only a `<main>` tag inside) and just added ChakraUI and wrapped the `ChakraProvider` and `CacheProvider` just like it describes [in the docs](https://chakra-ui.com/getting-started/nextjs-guide#app-directory-setup) and ofcourse I used `"use client"` the homepage I get these errors out the gate:
> > > > > ```
> > > > > Error: Hydration failed because the initial UI does not match what was rendered on the server.
> > > > > 
> > > > > Warning: Expected server HTML to contain a matching <span> in <html>.
> > > > > 
> > > > > See more info here: https://nextjs.org/docs/messages/react-hydration-error
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > ```
> > > > > Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > I'm guessing for now if we want to use ChakraUI we will have to continue with the `Page Router`?
> > > > > [My code](https://github.com/cam-eo/next13-chakraui).
> > > > 
> > > > 
> > > > You shouldn't use 'use client' directive in layout.tsx/jsx file . You should make a component ( with use cilent ) and render that in the layout.tsx file .
> > > > I think this will solve your problem . 🙂
> > > 
> > > 
> > > Hi Saim. Thank you for that.
> > > However, if you look at my code that I shared you will see I have used `"use client"` in `layout.ts`, and `page.ts` and the error still persists.
> > 
> > You should not use 'use state' directive in layout and page.tsx file .Instead of doing this, do this ....
> > 
> > [#7649 (comment)](https://github.com/chakra-ui/chakra-ui/issues/7649#issuecomment-1545592370)
> > 
> > Try This .... 🥰
> 
> This doesn't look like a solution. point 3 of [this](https://github.com/chakra-ui/chakra-ui/issues/7649#issuecomment-1545592370) even mentions that there is still an issue with `CacheProvider`.
> 
> Ofcourse I tried abstracting the providers to a separate component and applied `"use client"` but I get the same issue and from what I can see I am not the only one 
> 
> From what I can see, ChakraUI doesn't fully support NextJS App "Router yet". We just need to be patient until it's fully supported.

Yaa. You are right. Chakra UI don't support Next JS App Router fully yet ...

**Comment by AdamQuadmon** [comment]
> Yaa. You are right. Chakra UI don't support Next JS App Router fully yet ...

@Saim1358 have you find a UI library compatible with App Router?

**Comment by Saim1358** [comment]
> > Yaa. You are right. Chakra UI don't support Next JS App Router fully yet ...
> 
> @Saim1358 have you find a UI library compatible with App Router?

Almost all UI libraries use react hooks like useRef, useState, useEffect, etc . So , there is no perfect UI library which is currently suitable for Next JS App Router . But, If you are using tailwindcss you can use some tailwindcss UI library which just provide you the designs . You need to make them functional yourself by using useState, useEffect ,etc react hooks. ☹️

**Comment by AdamQuadmon** [comment]
> Almost all UI libraries use react hooks like useRef, useState, useEffect, etc . So , there is no perfect UI library which is currently suitable for Next JS App Router . But, If you are using tailwindcss you can use some tailwindcss UI library which just provide you the designs . You need to make them functional yourself by using useState, useEffect ,etc react hooks. ☹️

I'm coming from Gatsby and it was almost an year since my last `yarn dev`, so I'm quite new to NextJs but on the official docs I found a reference for styling the server components https://nextjs.org/docs/app/building-your-application/styling/css-in-js

they suggest to use pure css-in-js like tailwind but also a couple of libraries that are ready for it

I will give a try to https://tamagui.dev/ waiting for chakra to get up to date with React Server Components

**Comment by segunadebayo** [comment]
Due to the limitations of server components, I don't see a world where Chakra UI will work in the app router without constant use of the `use client` directive, which defeats the purpose and limits the app features you can use.

We're releasing a new app router-compatible styling solution that works like Chakra but without the runtime overhead. Please read my [blog post](https://www.adebayosegun.com/blog/the-future-of-chakra-ui) to learn about the direction we're heading.

Thanks.

**Comment by MA-Ahmad** [comment]
@segunadebayo I appreciate the efforts put into Chakra UI. I've been a big fan and a frequent user of Chakra UI for the past 3 years. Can we get ETA on router-compatible styling solution?

**Comment by pthieu** [comment]
@segunadebayo recently revamping my boilerplates, excited for Panda. Would love to see what state it's in and see if I can beta-test it and help out with bugs.

**Comment by karlhorky** [comment]
Panda CSS has been announced / a first version released here:

https://twitter.com/thesegunadebayo/status/1669732623994834946

**Comment by hungnv1312** [comment]
chakra ui still good?

**Comment by segunadebayo** [comment]
Chakra UI now works with the Next 13 app router without the need to add use client directive.

**Comment by hungnv1312** [comment]
> Chakra UI now works with the Next 13 app router without the need to add use client directive.

yes ser, hope u update document

**Comment by nwankwo-ikemefuna** [comment]
> Chakra UI now works with the Next 13 app router without the need to add use client directive.

Great news @segunadebayo 👍. One of the benefits of the Next app router is being able to extract client side logic to a separate component with `'use client'` directive so the component can be rendered on the client, while keeping the parent component on the server.

Question, if a Chakra component with client side logic (say `Button` component having `onClick` logic) is used in a server component, will the Chakra component be rendered on the server or client?

**Comment by ivanjeremic** [comment]
> Chakra UI now works with the Next 13 app router without the need to add use client directive.

Not on my side anything special I need to do? Or any docs?

**Comment by isaiah2004** [comment]
> Chakra UI now works with the Next 13 app router without the need to add use client directive.

Where do i add the chakraProvider now?

**Comment by cam-eo** [comment]
> > Chakra UI now works with the Next 13 app router without the need to add use client directive.
> 
> Where do i add the chakraProvider now?

You can use [what is described in the Chakra-UI docs](https://chakra-ui.com/getting-started/nextjs-guide) to have `provider.tsx` and use the [NextJS Layout component](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#layouts) to wrap app the pages in it.

**Comment by lluia** [comment]
@Calvin087 my guess is that **yes**, everything below in the tree 🌲  would become a client component. 

It defeats the purpose of using the app router. However, in the future, if Chakra eventually supports RSC (_app router support and RSC support are two different things_) then finally you'll be able to take advantage of the performance improvements of the app router 🙇🏽 

We have a big application built on top of Chakra, but we're slowly migrating to [Panda](https://panda-css.com/) (s [style props](https://panda-css.com/docs/concepts/style-props) make it kinda easy ) and headless UI libs.

**Comment by afroguy16** [comment]
When update docs?
