### ISSUE TITLE
Chakra CLI doesn’t work in Typescript Next.js project

### ISSUE THREAD

**Issue by selrond** [chakra-ui/chakra-ui#7650]
### Description

After https://github.com/chakra-ui/chakra-ui/pull/7621 Chakra CLI errors out in Next.js projects using TS (not sure why it doesn’t break on default TS examples)

Having a simple theme like this

```tsx
import { extendTheme } from '@chakra-ui/react'

const colors = {
  product: {
    red: '#E26021',
  },
}

export default extendTheme({
  colors,
})
```

throws

```
Transforming const to the configured target environment ("es5") is not supported yet
```

### Link to Reproduction

https://codesandbox.io/p/sandbox/focused-waterfall-9cdnjs?file=%2Fpackage.json%3A14%2C28

### Steps to reproduce

Run `npm run theme` in the provided sandbox

**Comment by segunadebayo** [comment]
Please upgrade your tsconfig target to es6 or next

**Comment by selrond** [comment]
Next.js comes with es5 by default, it would be nice to have it mentioned somewhere in the docs
