### ISSUE TITLE
colorScheme refer to 200 instead of 500 in color object

### ISSUE THREAD

**Issue by rdjanuar** [chakra-ui/chakra-ui#7652]
### Description

when i try the current version of chakra ui there is a difference between the reference colorScheme normally refers to object color 500 but it refers to object color 200. is that bug or new refer colorScheme ?

### Link to Reproduction

https://chakra-ui.com/docs/components/button/usage

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.6.1

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

this is the colorScheme between my application and chakra ui docs Button.
my application use chakra ui version by refine : "@refinedev/chakra-ui": "^2.12.0",
![image](https://github.com/chakra-ui/chakra-ui/assets/60952577/227792ad-4232-4f17-9474-7e8b119ff72f)
![image](https://github.com/chakra-ui/chakra-ui/assets/60952577/45ffee5a-4d1f-4785-b28e-16c58fc6a181)

**Comment by segunadebayo** [comment]
Hey @rdjanuar,

This is not a bug. Light mode refers to 500 color value, and dark mode refers to the 200 color value.
