### ISSUE TITLE
NumberInput with react hook form story throws error

### ISSUE THREAD

**Issue by Tolu-Mals** [chakra-ui/chakra-ui#7653]
### Description

When I open the 'with react hook form' section of the NumberInput component, I expect to see the story, but this error is thrown instead
<details>
<summary>Screenshot</summary>
<img width="1436" alt="Screenshot 2023-05-13 at 6 05 04 PM" src="https://github.com/chakra-ui/chakra-ui/assets/30352484/020139be-4442-4e9c-8065-520dad231096">
</details>

### Link to Reproduction

N/A

### Steps to reproduce

1. Clone Chakra UI repo
2. Install dependencies
3. Open story book
4. Open 'with react hook form' story under NumberInput

### Chakra UI Version

local dev environment

### Browser

Brave

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Good catch!

This is now fixed.
