### ISSUE TITLE
TypeScript error when overriding _focusVisible base style with Tag component 

### ISSUE THREAD

**Issue by jsinclair-indeed** [chakra-ui/chakra-ui#7657]
### Description

I am trying to override the `_focusVisible` base style for my `Tag` component in my theme. This works and was compiling fine in older versions `<=v2.5.4`.

```ts
const TagTheme = defineStyleConfig({
  baseStyle: {
    container: {
      _focusVisible: {
        boxShadow: "none",
        outlineColor: "red.500"
      }
    }
  }
});
```

For versions equal to or greater than `@chakra-ui/react@2.5.5` I am seeing a new Typescript error stating:
```
Type '{ _focusVisible: { boxShadow: string; outlineColor: string; }; }' is not assignable to type 'PropertyValue<"container">'.
  Types of property '_focusVisible' are incompatible.
```

I saw there was a recent Major change to the Tag component made in https://github.com/chakra-ui/chakra-ui/pull/7488 but the changes look unrelated from my viewpoint. 

Am I doing something silly here? Should I compose the style differently? Or is there something we can fix in one of the packages?

Many thanks for this library and anyone who is able to spend some time to help ✨ 🙇 

### Link to Reproduction

https://codesandbox.io/s/tag-override-focusvisible-issue-rn1x7i

### Steps to reproduce

1. Go to the reproduction Code Sandbox url
2. Go to the file `src/index.ts`
3. Scroll down to the `const TagStyles` assignment block.
4. Observe the TypeScript error:
```
Type '{ _focusVisible: { boxShadow: string; outlineColor: string; }; }' is not assignable to type 'PropertyValue<"container">'.
  Types of property '_focusVisible' are incompatible.... 
```

### Chakra UI Version

2.5.5

### Browser

Latest stable Google Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Here's the solution:
https://codesandbox.io/s/tag-override-focusvisible-issue-forked-7m93yr?file=/src/index.tsx:0-940

```jsx
const { defineMultiStyleConfig } = createMultiStyleConfigHelpers(["container"]);

const TagStyles = defineMultiStyleConfig({
  baseStyle: {
    container: {
      _focusVisible: {
        boxShadow: "none",
        outlineColor: "red.500"
      }
    }
  }
});

```
