### ISSUE TITLE
Tooltip showing at the wrong time

### ISSUE THREAD

**Issue by dyk98** [chakra-ui/chakra-ui#7662]
### Description

If I use a Tooltip component with Button to make Modal open, Tooltip will show when Modal close

It's code demo, you can use it in Chakta Playground
[Demo](https://play.chakra-ui.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwATAB0A7XXAIQFdtsIiAaY0gFQggBtsk0GTcKBnGABEk-MGwj8KmGD1IBZaAEM2c3IqgqA8gDcYmNkoCeajSoDCtbDCLZTytgAkYS2Jnua2AMVbX3jdQcyaBMAszZzCUFKaloeAF9cADNMCBRcAHIAATAACyUAa0wlAFoKJAB6GSUwbAziYhgADwwcXEgifjwAQTQ0XABeXAAKAEpBgD58AI6u-FxRLTQbOlxaJZW1okjJGFxEoYFhUXFJaRgxgJlsaRJhgNIAHgmH0lxHlnZOfsMAIxg2ANgABGABMAGYweDEvl+N1MKkAO5ApIqQTxF68N5vR4xGgkWiRJBgApA9bLIgYokkra4FAwACEjwqeNomOxTwqnw4XExrye4QW-A2RCBiwpiUJURgZO20ox-Jx4V0+kMRlwFXZHIFDksths2C12p1nmcrn0E0FTCQ2DYMGZ4TNbiNxse4R20So+I1Lu1bqCIV9rrQEyhYYhzJDiuxDoDUCMfKxrvCPggfiDftZJEgEkwAGU8jB6QMCCBfmwKDBS3TMEDoVtqaTgFLdgqk8a3h6q+3XSyvWzoxzcf2SDolJgkEpbCWQABzXKSbCliZ5mAdTSYdXdWpIWjMrMZnEVFO+C2D2OePXWWxBi8qF3MrWjYjxYggeJAA)

### Link to Reproduction

[Code Demo](https://play.chakra-ui.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwATAB0A7XXAIQFdtsIiAaY0gFQggBtsk0GTcKBnGABEk-MGwj8KmGD1IBZaAEM2c3IqgqA8gDcYmNkoCeajSoDCtbDCLZTytgAkYS2Jnua2AMVbX3jdQcyaBMAszZzCUFKaloeAF9cADNMCBRcAHIAATAACyUAa0wlAFoKJAB6GSUwbAziYhgADwwcXEgifjwAQTQ0XABeXAAKAEpBgD58AI6u-FxRLTQbOlxaJZW1okjJGFxEoYFhUXFJaRgxgJlsaRJhgNIAHgmH0lxHlnZOfsMAIxg2ANgABGABMAGYweDEvl+N1MKkAO5ApIqQTxF68N5vR4xGgkWiRJBgApA9bLIgYokkra4FAwACEjwqeNomOxTwqnw4XExrye4QW-A2RCBiwpiUJURgZO20ox-Jx4V0+kMRlwFXZHIFDksths2C12p1nmcrn0E0FTCQ2DYMGZ4TNbiNxse4R20So+I1Lu1bqCIV9rrQEyhYYhzJDiuxDoDUCMfKxrvCPggfiDftZJEgEkwAGU8jB6QMCCBfmwKDBS3TMEDoVtqaTgFLdgqk8a3h6q+3XSyvWzoxzcf2SDolJgkEpbCWQABzXKSbCliZ5mAdTSYdXdWpIWjMrMZnEVFO+C2D2OePXWWxBi8qF3MrWjYjxYggeJAA)

### Steps to reproduce

1. Hover Tooltip
2. Click Button to make Modal open
3. close Modal
4. Tooltip will show

### Chakra UI Version

latest

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I use { trapFocus: false } on Modal to fix this issue

**Comment by koders** [comment]
This seems to be inteded, since by default modal returns focus to the button, and focusing triggers tooltip.
It seems to better fix it with `returnFocusOnClose={false}` than `trapFocus: false` because of accessability.
