### ISSUE TITLE
Slider changing its value when a new touch action is started on the body of the document

### ISSUE THREAD

**Issue by diegotraid** [chakra-ui/chakra-ui#7665]
### Description

Moving the slider and touching anywhere else on the screen shouldn't change the slider position.

### Link to Reproduction

https://codesandbox.io/s/blazing-microservice-d0cc7e

### Steps to reproduce

1. Press and hold the slider thumb
2. While holding the slider thumb, press anywhere on the screen of your device
3. Slider changes the value based on the position of this last touch
4. Try holding both fingers and move the slider to see how slider thumb jumps from one side to the other

### Chakra UI Version

2.6.1

### Browser

Google Chrome 113 on Android device

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is by design. Slides listen for the pointer move and stops when the pointer is released.
