### ISSUE TITLE
viewBox not usable when using a third-party icon library

### ISSUE THREAD

**Issue by alvinlys** [chakra-ui/chakra-ui#7667]
### Description

viewBox props is not usable when Icon is using a third-party icon library

### Link to Reproduction

https://codesandbox.io/s/upbeat-moon-ko0iy2?file=/src/index.js

### Steps to reproduce

1. Import the Icon component from @chakra-ui/react
2. Pass the desired third party icon into the as prop
3. Use the "viewBox" to see no changes

### Chakra UI Version

2.6.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hey @alvinlys,

You don't need the viewBox when using Icon component.

When you pass any external icon component, you can update their size by using the `fontSize` prop.

**Comment by alvinlys** [comment]
> Hey @alvinlys,
> 
> You don't need the viewBox when using Icon component.
> 
> When you pass any external icon component, you can update their size by using the `fontSize` prop.

noted, but wonder is the `fontSize` able to set min-x , min-y , width and height as in viewBox?
