### ISSUE TITLE
Avatar component - names.at is not a function

### ISSUE THREAD

**Issue by MichaelGamel** [chakra-ui/chakra-ui#7670]
### Description

The avatar component not working on the old version of Firefox, 

I'm using this version `78.13.0esr`

The component not working even on the official documentation for chakra-ui,

<img width="1720" alt="image" src="https://github.com/chakra-ui/chakra-ui/assets/6534028/d06ee814-7199-470e-915c-2417e25912a6">

### Link to Reproduction

https://chakra-ui.com/docs/components/avatar/usage

### Steps to reproduce

1- install firefox version `78.13.0esr`
2- open any avatar component 

### Chakra UI Version

2.6.1

### Browser

FireFox

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by MichaelGamel** [comment]
I fixed it by adding polyfills for ".at" function

**Comment by segunadebayo** [comment]
This has already been fixed in one of the recent PRs. We'll release an update shortly.

If the issue persists after the release, I'll re-open this issue.
