### ISSUE TITLE
Using Home and End keys with NumberInput does not move the cursor to start end of the number 

### ISSUE THREAD

**Issue by foxstephen** [chakra-ui/chakra-ui#7672]
### Description

I often use Home and End keys when editing. When using them with `NumberInput` to move cursor to start and end a large number appears instead.

### Link to Reproduction

https://codesandbox.io/s/wandering-https-pok9hy?file=/src/index.tsx

### Steps to reproduce

1. Go to a NumberInput
2. Hit Home or End keys
3. Instead of the cursor being moved to start and end the following is displayed -9007199254740991 or 9007199254740991 (depending on which key is pressed) 

### Chakra UI Version

2.6.1

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Here is an example.
![chakra](https://github.com/chakra-ui/chakra-ui/assets/6042333/27a69cc3-0e8e-40ed-900a-77c8ec908225)

**Comment by Taimoor1729** [comment]
hey, i  just  solve this problem  but i can't clone this app  into my PC is there any thing who can help me @foxstephen

**Comment by Taimoor1729** [comment]
Hi Tyler,

Is this bug not fixed yet?

**Comment by tylers-epilog** [comment]
Nope. I wish it were.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by tylers-epilog** [comment]
Thanks!
