### ISSUE TITLE
Checkbox checked property

### ISSUE THREAD

**Issue by jucian0** [chakra-ui/chakra-ui#7673]
### Description

First, I would like to say thanks for this amazing work.

I'm wondering if the `Checkbox` component has a bug, when a use a native input HTML element type checkbox with `checked` property, it has a behavior, when using `Checkbox` from Chakra UI, it has another behavior.

```jsx
     <input checked type="checkbox" />
     <Checkbox checked />
```

This code produce this result:
<img width="465" alt="Screenshot 2023-05-19 at 07 41 34" src="https://github.com/chakra-ui/chakra-ui/assets/8399579/0a9ca5a4-f837-4a4e-86bf-2c340413d6cd">

I think, both should have the same behavior, right?

### Link to Reproduction

https://codesandbox.io/s/checkbox-chakra-ui-tj0lf3?file=/src/index.tsx

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.6.1

### Browser

Chrome

### Operating System

- [x] macOS
- [ ] Windows
- [X] Linux

**Comment by dvartic** [comment]
AFAIK the API to achieve the same behaviour in Chakra is using `defaultChecked` not the plain HTML property `checked`. I've read complaints about this difference, but I think there is no bug.

**Comment by jucian0** [comment]
Well, if it has the `checked` property, the property should work as expected, IMO.

**Comment by dvartic** [comment]
There's this PR to not allow the property #6656

**Comment by jucian0** [comment]
Thanks, going to see it

**Comment by segunadebayo** [comment]
Please use the `isChecked` property instead. We'll update the types pretty soon.
