### ISSUE TITLE
Dynamic colors with color mode

### ISSUE THREAD

**Issue by slaking** [chakra-ui/chakra-ui#768]
This is a feature request to support "dynamic colors". I would like to be able to define a color like "primary" as different colors in light and dark mode. This would save me from having to do the logic to select a color depending on which color mode is active everywhere around my components.

**Comment by ivoilic** [comment]
I agree this would be an important feature to implement. In the meantime, a great workaround is using CSS variables for all your colors.

**Comment by segunadebayo** [comment]
This is a duplicate of #1147. Kindly see my comments there.

Thank you.
