### ISSUE TITLE
mode @chakra-ui/theme-tools not work in nextjs 13

### ISSUE THREAD

**Issue by bebru2k1** [chakra-ui/chakra-ui#7681]
### Description

mode @chakra-ui/theme-tools not work in nextjs 13

### Link to Reproduction

no link (private project)

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.6.1

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

```js
import { mode } from "@chakra-ui/theme-tools";
 body: {
      // bg: mode("white", "gray.900")(props),
    },
```

`mode` not work in nextjs 13
`package.json`
```json
    "@chakra-ui/next-js": "^2.1.3",
    "@chakra-ui/react": "^2.6.1",
    "@emotion/react": "^11.11.0",
    "@emotion/styled": "^11.11.0",
    "next": "^13.4.2",
```

**Comment by bebru2k1** [comment]
please help

**Comment by segunadebayo** [comment]
I'm sorry, but I don't understand the problem you are reporting.

Please provide a reproduction using CodeSandbox to help me understand better.

**Comment by bebru2k1** [comment]
https://codesandbox.io/p/sandbox/agitated-tereshkova-l1os7v?file=%2Fapp%2Ftheme.ts%3A15%2C46
@segunadebayo 
if I comment line  `bg: mode("white", "gray.900")(props)` line 15 theme.ts. it work fine
but when I use  `bg: mode("white", "gray.900")(props)`  you can see when i click the button. everything disappears without switching to darkMode. actually the button is still there. you can press it to return to the original state. colorMode is not working properly. 
Please fix it. 
Thank you very much

**Comment by cateiru** [comment]
This is probably due to EmotionCacheProvider holding the cache; removing the `CacheProvider` component in `@chakra-ui/next-js` will work correctly.

ref. https://github.com/emotion-js/emotion/discussions/2829

**Comment by meerns** [comment]
@segunadebayo, this issue still exists. It happens when you use mode() in the theme provider. The only fix is to remove CacheProvider.

**Comment by B-HS** [comment]
@segunadebayo Same here, it still happened when using mode().
Here's link for example for reproduce this issue.
https://codesandbox.io/p/sandbox/crimson-morning-dd7rhj?file=%2Fapp%2Fproviders.tsx%3A5%2C50

**Comment by bebru2k1** [comment]
Maybe I should create a new issue? This issue has been closed.

**Comment by bebru2k1** [comment]
@segunadebayo

**Comment by samuelcbird** [comment]
I am experiencing this issue too. Has it been acknowledged by Chakra?

**Comment by moafzalmulla** [comment]
Chakra is great, but I am not able to set a color variable using extend theme function in nextjs.

Say if I set 
`import { extendTheme } from "@chakra-ui/react";
/* theme.ts */
export const theme = extendTheme({
  colors: {
    brand: {
      // white: '#ffffff',
      400: '#272c7d',
      100: '#D6D944',
      200: '#40A83D',
      300: '#0C7348',
      500: '#2D444A',
    },
  },
  fonts: {
    heading: 'var(--font-rubik)',
    body: 'var(--font-rubik)',
  }
});
`

Then import the theme and pas as a prop to 

`    <CacheProvider>
      <ChakraProvider theme={theme}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </ChakraProvider>
    </CacheProvider>`

It still doesn't work.

I tried downgrading emotion-styled and also tried by removing CacheProvider

No luck.

Anyone else manage to resolve this ?

**Comment by Lakmi94** [comment]
Having the same issue.. When colorMode is changed using `toggleColorMode`, the html body background color is not changed to the relevant colorMode's color

**Comment by bebru2k1** [comment]
https://github.com/chakra-ui/chakra-ui/issues/8082
I created a new issue because this issue was closed. Everyone please follow here.

**Comment by manakuro** [comment]
Can we use the `_dark` instead of the `mode`?
https://codesandbox.io/p/devbox/cacheprovider-issue-forked-zd5lnf?file=%2Fapp%2Fproviders.tsx%3A11%2C28

```.ts
const theme = extendTheme({
  styles: {
    global: (props: StyleFunctionProps) => ({
      body: {
        color: "black",
        bg: "white",
        _dark: {
          color: "white",
          bg: "black",
        },
        lineHeight: "base",
      },
    }),
  },
  config: {
    initialColorMode: "dark",
    useSystemColorMode: false,
  },
});
```
