### ISSUE TITLE
Modal returning focus to triggering element broken by use of initialFocusRef 

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [chakra-ui/chakra-ui#7688]
### Description

On upgrading from 1.8.7 to 2.6.1 I spotted an issue with modals not returning focus when they use initialFocusRef.

finalFocusRef works if used - it's the default final focus behaviour that seems not to work.

This seems to reproduce in a simple example.

### Link to Reproduction

https://codesandbox.io/s/chakra-modal-focus-bug-5bijxu?file=/src/App.js

### Steps to reproduce

1. Go to [the sandbox](https://codesandbox.io/s/chakra-modal-focus-bug-5bijxu?file=/src/App.js)
2. Tab to the second button
3. Enter
4. Close the dialog via Escape
5. Observe that the "Open Modal" button is not focussed

This reproduces with the touch/mouse too but it's clearer to see via the focus rings from keyboard navigation.

In v1 this used to work and I think [the docs suggest it should work](https://chakra-ui.com/docs/components/modal/usage#control-focus-when-modal-closes). The code also seems like it's trying to do this but something goes awry.

### Chakra UI Version

2.6.1

### Browser

Google Chrome 113

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I debugged a little and found that the code [here](https://github.com/theKashey/react-focus-lock/blob/master/src/Lock.js) was being run more often and later than I expected, perhaps resulting in it deciding that the input was the active element it needed to remember.

**Comment by segunadebayo** [comment]
Thanks for taking the time to debug the issue. Means a lot.

I noticed it has been fixed, and it works as expected.

We'll release an update shortly.
