### ISSUE TITLE
Icons ignore <DarkMode> and <LightMode> tags

### ISSUE THREAD

**Issue by xobotyi** [chakra-ui/chakra-ui#7689]
### Description

In case icon being placed within `<DarkMode>` tag it stil infers linght mode styles.
Though change performs properly if to change global mode.

### Link to Reproduction

https://codesandbox.io/s/falling-wildflower-qvi64v?file=/src/index.tsx

### Steps to reproduce

1. Wrap any icon containing compoent with `<DarkMode>`
2. Icons remain dark (while should become linght)

### Chakra UI Version

2.6.1

### Browser

latest FireFox and Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by ahzia** [comment]
@xobotyi I can see the dark mode is working fine on codesandbox

**Comment by segunadebayo** [comment]
This is happening because there was explicit color set on the button.

This has already been fixed in one of the recent PRs. We'll release an update shortly.

If the issue persists after the release, I'll re-open this issue.
