### ISSUE TITLE
LinkOverlay on mobile filling entire screen

### ISSUE THREAD

**Issue by GustavoMelloGit** [chakra-ui/chakra-ui#7692]
### Description

I have a table and i am using LinkOverlay with LinkBox, it works fine on Desktop but on mobile the entire screen is filled with the link, making it impossible to use the page.  I already tried setting the height of the :before at LinkOverlay component, but it does not work, neither set LinkBox overflow porperty as hidden.

This is how my component looks like:
```
return (
    <LinkBox as={Tr}>
      <Td textAlign='center' data-cy='table-cell-client-avatar'>
        <Avatar loading='lazy' src={client.profileImage} name={client.name} />
      </Td>
      <Td
        title={client.name}
        maxW={40}
        whiteSpace='nowrap'
        textOverflow='ellipsis'
        overflow='hidden'
        data-cy='table-cell-client-name'
      >
        {client.name}
      </Td>
      <Td title={client.nickname} data-cy='table-cell-client-nickname'>
        {client.nickname}
      </Td>
      <Td
        onClick={handleToggleBalance}
        cursor='pointer'
        color={showBalance ? getColorByValue(client.balance) : 'inherit'}
        data-cy='table-cell-client-balance'
        data-balance={client.balance}
      >
        {showBalance ? formatCurrency(client.balance) : 'R$ ----'}
      </Td>
      <Td title={client?.contact?.phone} data-cy='table-cell-client-phone'>
        {client?.contact?.phone}
      </Td>
      <Td textAlign='center' data-cy='table-cell-client-actions'>
        <HStack w='full' justify='center'>
          <Link to={Routes.updateClient(client.id)}>
            <TableEditButton colorScheme='blue' as='span' aria-label='Editar cliente' />
          </Link>
          <LinkOverlay
            as={Link}
            to={Routes.clientPage(client.id)}
          />
        </HStack>
      </Td>
    </LinkBox>
  )
```

### Link to Reproduction

Dont need it

### Steps to reproduce

1. Create a Table
2. Create a Row with LinkBox as Tr
3. Add LinkOverlay
4. Test it on mobile

### Chakra UI Version

2.4.9

### Browser

Google Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
The LinkOverlay component requires LinkBox to work or any element with position relative. Please update your code accordingly.

**Comment by GustavoMelloGit** [comment]
I finally found the solution. Since <tr> ignores position: relative, you can use the follwing workaround: https://stackoverflow.com/a/51407758
