### ISSUE TITLE
Navigation with the `TAB key` not working in `<Modal>` if it's opened from `<Menu>`

### ISSUE THREAD

**Issue by romanstetsyk** [chakra-ui/chakra-ui#7697]
### Description

If a modal is opened from the menu, navigation with the TAB key is not working.

### Link to Reproduction

https://codesandbox.io/p/sandbox/chakra-ui-open-modal-from-menu-y861zz

### Steps to reproduce

1. Click on 'Menu', then click on 'Open Modal'
2. Try to use the `TAB` key for navigation
3. See that elements' focus doesn't change

For reference, a button to the right of the menu opens the modal, in which the `TAB` key works fine. 

### Chakra UI Version

2.6.1

### Browser

Google Chrome 113

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by vboechat** [comment]
The discussion [#7418](https://github.com/chakra-ui/chakra-ui/discussions/7418) is related to this issue too.
Thank you @romanstetsyk! I've been waiting for an answer in that discussion for so long. Just subscribed to the issue.

**Comment by segunadebayo** [comment]
The solution here is to stop propagation on the ModalContent.

https://codesandbox.io/p/sandbox/chakra-ui-open-modal-from-menu-forked-g5835x?file=%2Fsrc%2FModalInsideMenu.tsx%3A15%2C1-44%2C2

```jsx
function ModalInsideMenu() {
  const { isOpen, onOpen, onClose } = useDisclosure();
  return (
    <>
      <MenuItem onClick={onOpen}>Open Modal</MenuItem>

      <Modal isOpen={isOpen} onClose={onClose}>
        <ModalOverlay />
        <ModalContent
          onKeyDown={(e) => {
            e.stopPropagation();
          }}
        >
          <ModalHeader>Modal Title</ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            <Input />
          </ModalBody>

          <ModalFooter>
            <Button colorScheme="blue" mr={3} onClick={onClose}>
              Close
            </Button>
            <Button variant="ghost">Secondary Action</Button>
          </ModalFooter>
        </ModalContent>
      </Modal>
    </>
  );
}
```

**Comment by romanstetsyk** [comment]
@segunadebayo Thanks for the reply. It works like a charm!
