### ISSUE TITLE
[Button] Attribute type="button" remains when as prop is used

### ISSUE THREAD

**Issue by tristandubbeld** [chakra-ui/chakra-ui#770]
**Describe the bug**
When using the `as` prop on the Button component (e.g. to make it an anchor) the attribute `type="button"` persists.

**Expected Behavior**
When using the Button component with the `as` prop to render it as not a button, it should render the component without `type="button"` by default.

**To Reproduce**
- Use this template: https://codesandbox.io/s/kind-mountain-wcmne?file=/src/index.tsx

**Suggested solution(s)**
Theres two options to solve this issue:

1. Remove `"button"` as default value for the type property in the button component.
2. When the  `as` prop is defined on the Button component, don't use `type="button"` by default.

**Additional context**
I've checked the `dev-ts` branch and the issue also occurs in there. I'm glad to help by creating a PR! Let me know what you think would be the best solution.

**Comment by with-heart** [comment]
I have verified that this issue still exists in 1.0: https://codesandbox.io/s/fancy-glitter-tmq3l?file=/src/index.tsx

**Comment by JClackett** [comment]
Was this ever fixed? I want render a menu item with type="submit" so I can submit a form on click, but it keeps getting overridden to type="button"
