### ISSUE TITLE
Popovers (ex tooltip) don't flip when there is not enough space left on screen to display the full content

### ISSUE THREAD

**Issue by jcfizzler** [chakra-ui/chakra-ui#7700]
### Description

In our website, tooltips don't flip to the opposite orientation when there is not enough space left on screen to display the full content. Here is a GIF of the issue. 

![Tooltip issues](https://github.com/chakra-ui/chakra-ui/assets/33040291/f11c21e2-4409-424d-bdbf-6998ddad61a2)

I'm not able to reproduce this on Chakra's tutorials. What's worse is that even though some or most of the tooltip content could be displayed albeit cutoff, when there is not enough space to show the whole thing, nothing is displayed which makes it look like the tooltip doesn't work.

I added a patch to \node_modules\@chakra-ui\popper\dist\esm\use-popper.js inside `createPopper` as follows (just added the boundary prop):

```
      {
        name: "flip",
        enabled: !!flip,
        options: {
          padding: 8,
          boundary: reference.current.closest("*")
        },
      },
```

This doesn't cause the tooltip to actually flip but at least shows the cutoff tooltip when hovering on the trigger so it doesn't look broken. 

![Tooltip issues with patch](https://github.com/chakra-ui/chakra-ui/assets/33040291/384c7b2e-daa3-4bc6-b922-f76f90878821)

### Link to Reproduction

https://codesandbox.io/s/infallible-monad-cguuts?file=/src/index.tsx

### Steps to reproduce

I've simplified my project index.tsx so that this is the only code in there and it's still reproducible. I'm not able to reproduce in the code sandbox above. :(

render(
	<ChakraProvider>
		<Container h="3000px">
			<Box h="500px">Other content</Box>
			<Tooltip
				hasArrow
				label="This is some useful tooltip content. There is a lot of useful information in here and all you have to do is hover."
			>
				<Box border="1px solid black">Hover Me for Tooltip</Box>
			</Tooltip>
		</Container>
	</ChakraProvider>,
	element,
);

### Chakra UI Version

1.6.0

### Browser

Version 113.0.5672.127 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @jcfizzler,

Sorry, we no longer maintain v1 anymore.

**Comment by cgarrovillo** [comment]
How is this fixed in v2 so it can be overridden for those still using V1?
