### ISSUE TITLE
Checkboxes re-render after events on other inputs

### ISSUE THREAD

**Issue by sriikkila** [chakra-ui/chakra-ui#7702]
### Description

Focusing, changing the value or blurring from text inputs causes all Chakra UI checkboxes on the page to re-render. I noticed the issue while working on a large set of selectable table rows with text inputs on them.

The CodeSandbox browser preview needs to be opened in a new window so that React Dev Tools render highlighting can be seen.

The same behaviour can be seen happening with radio buttons in the Chakra UI documentation https://chakra-ui.com/docs/components/form-control#sample-usage-for-a-radio-or-checkbox-group If any of the text inputs on the page are changed, the inputs in the radio group are re-rendered.

### Link to Reproduction

https://codesandbox.io/s/pedantic-river-m6hufb?file=/src/index.tsx

### Steps to reproduce

1. Go to the CodeSandbox link
2. Click on "Open in New Window" on the browser panel
3. Open the React Developer Tools profiler and enable "Highlight updates when components render" from the settings
4. Click on the text input, write something in it and click elsewhere
5. Keep an eye on the checkbox, it should have re-rendered at least a couple times

### Chakra UI Version

2.0.0

### Browser

Google Chrome 113

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @sriikkila,

This happens because we track focus visibility to ensure we show the focus outline when interacting with the keyboard.

This is technically fine and shouldn't cause any side effects in your application.

**Comment by mmmeff** [comment]
Is there a way to disable this? I'm working on a page that has a ton of checkboxes rendered on it and the re-rendering of every one is causing a non-trivial negative impact to performance for most users of my application.
