### ISSUE TITLE
Menu component glitch for mac (only in SAFARI)

### ISSUE THREAD

**Issue by Srihari2222** [chakra-ui/chakra-ui#7707]
### Description

When I check the menu button in windows it works good but not best and the list opens. But in MAC book mainly in safari browser the experience with the menu which I implemented as a SELECT is not good. I attached the respective files and content so please go through it and solve the issue.

this is in macbook:
https://github.com/chakra-ui/chakra-ui/assets/94112314/bb790f0b-2364-4359-9a03-a2abf2aa3a4c

this is in windows:

https://github.com/chakra-ui/chakra-ui/assets/94112314/7ebc596e-1dbb-4226-a038-c7919d744d2c

And below is the respective code:

### Link to Reproduction

https://codesandbox.io/s/adoring-neco-k6g5yy

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.6.1

### Browser

safari

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

`<Menu>
                        <MenuButton as={Select} type="text" boxShadow="dark-lg" cursor='pointer' color="white" placeholder="States" width={"40%"} border="none" bgColor="darkcyan">
                        </MenuButton>
                        <MenuList sx={scrollbarStyles} maxHeight="270px" overflowY="auto"  bgColor="#161530" border={"none"} borderRadius={5}>
                            {States.map((option) => (
                                <React.Fragment key={option.value}>
                                <MenuItem
                                letterSpacing={"1px"}
                                color="white"
                                bgColor="#161030"
                                value={option.value}
                                onClick={() => handleMenuItemClick(option.label)}
                                >
                                    <Stack minW={"100%"}>
                                        <Text m={0}>{option.label}</Text>

                                        <Divider orientation='horizontal'  width={"100%"} borderColor="#151530" borderWidth={1} m={0} ml={2.5}></Divider>
                                    </Stack>
                                </MenuItem>
                                </React.Fragment>
                            ))}
                        </MenuList>
                    </Menu>`

**Comment by segunadebayo** [comment]
I'm sorry, but I don't understand the problem you are reporting.

Please provide a reproduction using CodeSandbox to help me understand better.
