### ISSUE TITLE
Inputs not changing according to colorScheme

### ISSUE THREAD

**Issue by ig4e** [chakra-ui/chakra-ui#7708]
### Description

When I add the color scheme prop to the Input component its focused border/ring/outline color doesn't change, to change it I must use focusBorderColor which really sucks.

I noticed something weird when I refresh the page on (next13 using create t3 app) it turns to the colorScheme that is selected but instantly goes back to the default cyan

### Link to Reproduction

https://codesandbox.io/p/sandbox/confident-fog-ucn2qi

### Steps to reproduce

```
<span>default input</span>
<Input></Input>
<span>this input's color doesn't change</span>
<Input colorScheme={"pink"}></Input>
<span>also this doesn't change</span>
<Input colorScheme="purple"></Input>
<span>but this works fine</span>
<Input focusBorderColor="pink.500"></Input>

```
### Chakra UI Version

2.6.1

### Browser

Google Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @ig4e,

The colorScheme prop does not affect the input element itself. Please check the theme source to see how the component is styled.

If you want to change the border color looks, you can create a semantic token and use that as the focusBorderColor.

```jsx
const theme = extendTheme({
  semanticTokens: {
    colors: {
      "input-focus": { _light: "pink.500", _dark: "pink.300" },
    },
  },
});

function App({ Component, pageProps }: AppProps) {
  return (
    <ChakraProvider theme={theme}>
      <Component {...pageProps} />
    </ChakraProvider>
  );
}
```

Then use it as the focus border color

```jsx
<Input focusBorderColor="input-focus" />
```

> I caught a bug in the input styling while writing this. It's now fixed and will be released shortly. After the upgrade, you should be able to use my suggestion above.

**Comment by trungtin** [comment]
Then the Input shouldn't have `colorScheme` props, should it? I stumble upon this too.

**Comment by barbarakogus** [comment]
In my opinion, this should be handled by Chakra too
