### ISSUE TITLE
Avatar issue on Safari 15.0

### ISSUE THREAD

**Issue by ivan-dalmet** [chakra-ui/chakra-ui#7712]
### Description

When the property `name` is used on the `<Avatar>` component, the app crash on Safari 15.0 because `.at(0)` is used.

### Link to Reproduction

https://codesandbox.io/s/goofy-wind-o3p7k1?file=/src/index.js

### Steps to reproduce

1. Open a iOS 15.0 device (use xcode simulator iPhone 12 - iOS 15 for example)
2. Open Safari
3. Go the codesandbox preview https://o3p7k1.csb.app/
4. Error "names.at is not a function"
![image](https://github.com/chakra-ui/chakra-ui/assets/9749061/12535b80-6f68-4246-be01-0e16f569542c)

### Chakra UI Version

2.6.1

### Browser

Safari iOS 15.0

### Operating System

- [x] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I know that Safari 15.0 is old but not so much (end of 2021)
https://caniuse.com/mdn-javascript_builtins_array_at
![image](https://github.com/chakra-ui/chakra-ui/assets/9749061/f001164a-8179-4502-a8a3-b86d29482535)

**Comment by segunadebayo** [comment]
This has already been fixed in one of the recent PRs. We'll release an update shortly.

If the issue persists after the release, I'll re-open this issue.

**Comment by ivan-dalmet** [comment]
Yes it's fixed in `2.7.0` 👍
