### ISSUE TITLE
Tooltip `closeOnScroll` does not work

### ISSUE THREAD

**Issue by mgs95** [chakra-ui/chakra-ui#7714]
### Description

I think Tooltip `closeOnScroll` does work if you scroll the root container but it does not when scrolling other elements. You can see in the link to reproduction that hovering the "Item 1" and then scrolling will not close the tooltip (and you can also see how the tooltip exceeds the scrolling container). This is related with [this other issue](https://github.com/chakra-ui/chakra-ui/issues/5755) as it was marked as the solution to it.

### Link to Reproduction

https://codesandbox.io/embed/focused-sea-pxeh62?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce

1. Add a `Tooltip` with `closeOnScroll` prop
2. make sure the tooltip is within a scrollable container
3. Scroll up or down without moving the mouse
4. See how the tooltip is not closed

### Chakra UI Version

2.6.1

### Browser

Google Chrome Version 113.0.5672.126

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Thanks for reporting this @mgs95,

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
