### ISSUE TITLE
RangeSliderMark not getting styled. missing styling hook

### ISSUE THREAD

**Issue by srowe0091** [chakra-ui/chakra-ui#7715]
### Description

The RangeSliderMark component does not have the css styles being applied like the rest of the components

https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/slider/src/range-slider.tsx#L180

Which incidentally makes the marker for the RangeSliderMark unstyled and ignores the styling when applied at theme level.
(this behavior still works as expected for the regular Slider)

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
