### ISSUE TITLE
DrawerCloseButton sometimes not full width without DrawerHeader

### ISSUE THREAD

**Issue by boa901** [chakra-ui/chakra-ui#7717]
### Description

When I create a Drawer without having a DrawerHeader as a child of DrawerContent, the DrawerCloseButton appears to be normal visually, but can only be clicked on its right side in some cases. The hover behavior of the DrawerCloseButton also only applies when the cursor is hovering over the right side of the button in these cases.

This happens when an Input Element is used as a child of the DrawerBody component, but I have not checked extensively to see if it happens when using other elements as well.

If DrawerHeader is a required child or DrawerContent, I failed to see it in the documentation. Should there be some kind of default behavior if no DrawerHeader is used?

### Link to Reproduction

https://codesandbox.io/s/zealous-davinci-t6945z

### Steps to reproduce

1. Go to [this example](https://codesandbox.io/s/zealous-davinci-t6945z)
2. When the example finishes loading, click on Open Drawer
3. Hover/Click the left side of the DrawerCloseButton
4. Check intended behaviors
5. Hover/Click the right side of the DrawerCloseButton
6. Check intended behaviors

### Chakra UI Version

2.5.1

### Browser

Google Chrome 113.0.5672.127
Firefox 102.11.0esr

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by HJordan35** [comment]
It seems like the margin and content area of the form controls creeps into the position of the button. Adding a z-index to the close button appears to resolve the issue. I opened a PR but it is my first one and I probably did something wrong :) So maybe try adding that z-index via an external class property as a workaround to see if that can fix your issue in the short term

**Comment by segunadebayo** [comment]
I recommend tweaking this in your userland code instead.
