### ISSUE TITLE
OnClose from useDisclosure - is redirecting to top of page by default

### ISSUE THREAD

**Issue by vasile890** [chakra-ui/chakra-ui#7722]
### Description

I am using a Drawer with some Navigation Items from Menu. While clicking on my closing button, the Drawer is closing, but is going on top of the page. I want to disable this behavior of going on top of the page.

### Link to Reproduction

Idonthave.com

### Steps to reproduce

1. Click on burger menu and display Drawer.
2. Click on  Menu Item from Burger
3. Closing on the Drawer
4. See the redirect by default to top of the page

### Chakra UI Version

2.2.1

### Browser

Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Please follow the issue template as we're not able to act on issues that are lacking important information.
