### ISSUE TITLE
TypeError with button ref

### ISSUE THREAD

**Issue by zinzombe-kin** [chakra-ui/chakra-ui#7729]
### Description

When I used the Drawer component and copied the example on the chakra UI website, I keep getting an error on the button when I set the ref to the result of React.useRef(). I am using React Typescript

### Link to Reproduction

https://issue-for-chakra-ui.kinzinzombe.repl.co

### Steps to reproduce

1. Go to 'App.tsx'
2. Click on 'Button'
3. Scroll down to 'Line 13'

### Chakra UI Version

2.6.1

### Browser

Firefox 111.0.1

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Hey! I can't see the code of your issue. Most likely you want to do `React.useRef<HTMLButtonElement>(null)`

If you're still running into issue please re-open an issue with a link to the code reproduction

**Comment by joeldmyers** [comment]
This solved the same issue for me. Thanks!
