### ISSUE TITLE
[Icon] backface-visibility: hidden;

### ISSUE THREAD

**Issue by ansonkao** [chakra-ui/chakra-ui#773]
What is the purpose of this line?

https://github.com/chakra-ui/chakra-ui/blob/14b0ad5fb5c821032168793406d5a0c2c3cfc849/packages/chakra-ui/src/Icon/index.js#L9

It forces the `<svg />` component into a new compositing layer, which has [performance implications](https://www.smashingmagazine.com/2016/12/gpu-animation-doing-it-right/)!

**Comment by segunadebayo** [comment]
Thanks for point this out. @ansonkao. We can do without that attribute

We've removed it from the next release.
