### ISSUE TITLE
Button: color prop is getting ignored when using layerStyles

### ISSUE THREAD

**Issue by srowe0091** [chakra-ui/chakra-ui#7738]
### Description

When I style the buttons with layerStyles, I expect all the styling properties to be applied to the component, but the texts `color` property is not getting applied

### Link to Reproduction

https://codesandbox.io/s/dreamy-tamas-f0d879?file=/src/index.tsx

### Steps to reproduce

codesandbox shows how to reproduce

### Chakra UI Version

2.7.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This worked in 2.6.1 and broke in version 2.7.0

**Comment by segunadebayo** [comment]
This is a design flaw in v2. We've now fixed this in the upcoming v3 version
