### ISSUE TITLE
map standard css to logical css when possible

### ISSUE THREAD

**Issue by aaarichter** [chakra-ui/chakra-ui#7739]
### Description

Directional CSS properties should be mapped to logical CSS properties by default. Additionally, shortcut versions of these properties should be used.

### Problem Statement/Justification

1. internally Chakra already uses logical CSS, which is great, but its styling API mostly highlights the old CSS syntax (e.g. marginRight ). So a developer, who isn't fit with the new CSS logical syntax, would be tempted to use the older non-logical syntax. In LTR, this wouldn't make a difference, but in RTL or other writing-modes, the mix of logical CSS properties and conventional properties will likely break the UI components.
2. use of logical CSS shortcut syntax - this would reduce the amount of css applied + opens up new possibilities - e.g like `inset` 

### Proposed Solution or API

1. in the core/styled-system configs, the old directional CSS props should be mapped to logical CSS by default
2. shortcut syntax used - e.g `paddingX` should map to `paddingInline` instead of `paddingInlineStart` and `paddingInlineEnd`

**Comment by segunadebayo** [comment]
This should be left to the user to handle themselves.
