### ISSUE TITLE
Forwarding id property for NumberInput component

### ISSUE THREAD

**Issue by kimroen** [chakra-ui/chakra-ui#774]
**Is your feature request related to a problem? Please describe.**
If you use a `NumberInput` field with the default children within a form control, you cannot associate the label with the input using `htmlFor` and `id` like you might expect.

This works:

```jsx
<FormControl>
  <FormLabel htmlFor="first-name">First Name</FormLabel>
  <Input id="first-name" name="firstName" />
</FormControl>
```

This doesn't work:

```jsx
<FormControl>
  <FormLabel htmlFor="age">Age</FormLabel>
  <NumberInput id="age" name="age" />
</FormControl>
```

Clicking the label in the second case does nothing.

**Describe the solution you'd like**
A nice solution would be to allow the `NumberInput` component to accept `id` and set it on the input.

**Describe alternatives you've considered**
To make the above work at the moment, you need to provide the children for `NumberInput` and set the id on the `NumberInputField`:

```jsx
<FormControl>
  <FormLabel htmlFor="age">Age</FormLabel>
  <NumberInput name="age">
    <NumberInputField id="age" />
    <NumberInputStepper>
      <NumberIncrementStepper />
      <NumberDecrementStepper />
    </NumberInputStepper>
  </NumberInput>
</FormControl>
```

This works, but it feels a little unnecessary and was unexpected :)

**Comment by with-heart** [comment]
Hi @kimroen, this is working as expected in 1.0! See this CodeSandbox: https://codesandbox.io/s/compassionate-williamson-p5gpe?file=/src/App.js

**Comment by kimroen** [comment]
Thanks!
