### ISSUE TITLE
`__css` has higher priority than `color` for `Icon`

### ISSUE THREAD

**Issue by julioolvr** [chakra-ui/chakra-ui#7740]
### Description

When I pass both the `__css` and the `color` prop to the `Icon` component, I expect `color` to have higher priority, but `__css` wins.

From the docs here (emphasis mine) https://chakra-ui.com/docs/styled-system/component-style#return-value:

> Please note that we are passing the styles to the prop __css. It has the same API as [the sx prop](https://chakra-ui.com/docs/styled-system/the-sx-prop), **but has a lower style priority**. This means **you can override the style properties with chakra style props**.

But the following renders a red icon:

```tsx
<PhoneIcon color="blue" __css={{ color: 'red' }}/>
```

### Link to Reproduction

https://codesandbox.io/s/crazy-banzai-9c3yl9?file=/src/index.tsx

### Steps to reproduce

Just checking the rendered result is enough

### Chakra UI Version

2.0.18

### Browser

Google Chrome 114.0.5735.90

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The code does seem to do this intentionally, but I wonder if it was intended (I found this originally on Chakra 1, and saw the same behavior on Chakra 2)

https://github.com/chakra-ui/chakra-ui/blob/2456a7090439ebd1a1d1cdee36daa472d12ce6f7/packages/components/icon/src/icon.tsx#L63-L64

**Comment by snovosel** [comment]
I feel as though this should be intended. It looks like throughout other components there is a similar pattern of spreading the `_css` prop at the end.

Also, I'm trying to think of a use-case where you would want to pass both the `color` style prop and also `_css` including a different color. I would think the `_css` prop would be used as a way to override the default allowed props as well as add any additional styles. 

Open to any comments though

**Comment by julioolvr** [comment]
Looking at the code for the `Button` component, it seems to rely on `chakra.button` that explicitly sets `__css` as the lowest priority https://github.com/chakra-ui/chakra-ui/blob/2456a7090439ebd1a1d1cdee36daa472d12ce6f7/packages/core/system/src/system.ts#L53-L59

I tried the following (and added it to the codesandbox example for comparison) and the `color` prop effectively wins and text shows as blue:

```tsx
<Button __css={{ backgroundColor: "pink", color: "red" }} color="blue">
  Button
</Button>
```

My use case is pretty much the one mentioned in these docs https://chakra-ui.com/docs/styled-system/component-style#return-value. We have a custom multipart component that includes an icon. We allow overriding the icon color through props. So the code goes something like this:

```tsx
const styles = useMultiStyleConfig('MyComponent', { variant });

return (
  <Box>
    {/* Some other stuff */}
    <Icon __css={styles.icon} color={iconColor} />
  </Box>
);
```

And the idea is that if `iconColor` is provided then it is used, otherwise we use what's on the theme.

**Comment by snovosel** [comment]
I see what you're saying. It looks like the implementation for the styles is different between `Button` and `Icon` however.

Would it make sense for your use case to do something like this instead?

```
const styles = useMultiStyleConfig('MyComponent', { variant });

return (
  <Box>
    {/* Some other stuff */}
    <Icon __css={{
            ...styles.icon,
            color: iconColor ? iconColor : styles.icon.color,
        }}  
    />
  </Box>
);
```

I know it might not be the most readable, but should at least handle what you are trying to achieve

**Comment by julioolvr** [comment]
Absolutely, we ended up with something like that (except we're using the `sx` prop for the overrides instead of merging everything in the `__css` prop, but I think that makes no difference in this case). I was just surprised by Chakra's behavior in this case given what the documentation says - to me it looks like a bug, which is why I opened the issue. But maybe the `@chakra-ui/icons` package is not even meant to follow the same conventions? Not sure.

**Comment by snovosel** [comment]
I'm looking through this again, and I think you might be right actually. Looks like in the `Icon` component styles, the color prop is merged with the `__css` prop before rendering the `chakra.svg` element.

I created a PR [here](https://github.com/chakra-ui/chakra-ui/pull/7747) which removes the color prop from being merged with `__css` and for the priority of the styles to be handled downstream

**Comment by artkondakov** [comment]
Have the same issue, temporary solved by using `sx` alongside with `__css` and `useStyleConfig`

**Comment by segunadebayo** [comment]
I recommend using `__css` to apply the component theme styles. Overriding the styles should be done with style props or sx prop.
