### ISSUE TITLE
Custom selectors break semantic tokens

### ISSUE THREAD

**Issue by jsvossen** [chakra-ui/chakra-ui#7744]
### Description

The semantic token docs say:
> The condition can be one of chakra pseudo selectors or a _custom CSS selector_

 Prior to v2.6.0, adding a custom selector worked great, e.g.
```
textBody: {
  default: 'gray.800',
  _dark: 'whiteAlpha.900',
  ['.myClass']: 'red',
}
```
But with the latest version, any kind of custom selector breaks semantic tokens completely. The css resolves to the string "textBody" instead of the token value. Is there some other way we're supposed to define custom selectors? This is a big issue for us as we are using custom selectors to add high contrast mode.

### Link to Reproduction

https://codesandbox.io/s/optimistic-mendeleev-q7mg7v?file=/src/index.tsx

### Steps to reproduce

1. Observe that semantic tokens with a custom selector are not working with the latest Chakra version
2. Change `@chakra-ui/react` version to 2.5.0 in package.json and observe that the selectors are now working as expected.

### Chakra UI Version

2.7.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by TylerAPfledderer** [comment]
Hey @jsvossen!

The note you quoted is prior to the update of the semantic token feature, which now accommodates the ability to nest token object. (So I say this is outdated information, @segunadebayo ?)

With the approach that was taken to parse the object properly, the methods used had to be strict in essentially converting each key into a CSS variable.

I believe the best approach here will be to make use of a nested semantic token and apply it back to your selector.

i.e.
```ts
const customTheme = extendTheme({
  styles: {
    global: {
      ".special": {
        color: "text.special"
      }
    }
  },
  semanticTokens: {
    colors: {
      text: {
        base: {
          default: "gray.500",
          _dark: "gray.300"
        },
        special: "red.500" // <===
      }
    }
  }
});
```

Is your example closely related to production implementation, where `.special` only uses this one style?

Or could you provide an example that is more robust and closer to your implementation?

**Comment by jsvossen** [comment]
Hi @TylerAPfledderer, thanks for your reply. Unfortunately this approach won't work for us, as we really need the custom tokens to be conditional like `_dark`, as our use case is to effectively add a third color mode for a high contrast theme. E.g.
```
sematicTokens: {
  colors: {
    background: {
        default: 'white',
        _dark: 'gray.800',
        [".highContrast"]: 'black',
    }
  }
}
```
And then set `<Card background="background" />` so it will support all three themes based on the user's settings. If this is no longer possible, it seems like a regrettable breaking change to have gone in as a feature.

**Comment by jsvossen** [comment]
Hi @TylerAPfledderer and @segunadebayo, any updates or insights on this? Perhaps as an alternative, is there a way we could extend the pseudo selectors through the theme with a custom selector?

**Comment by damian-szewczyk-wttech** [comment]
@segunadebayo @TylerAPfledderer @jsvossen 
Any solution, workaround for this?
I was thinking about this one to have the alternative colors for components, not based for example on the "dark" or "light" mode, but based on a background color of component's parent. Imagine that you have a primary button which is usually red, but you can place it as well on a red background (could be checked by some ".red" class for example) and in this case the button background should be white.

How would you solve it, without introducing component variants? I was looking forward to solve it using those semantic tokens...

**Comment by segunadebayo** [comment]
The solution to this is to use custom "conditions"

```tsx
const theme = extendTheme({
  conditions: {
    highCon: '.highContrast &',
  },
  semanticTokens: {
    colors: {
      text: { base: 'xx', _highCon: 'xxx' },
    },
  },
})
```

We've further improved this in v3 as well.
