### ISSUE TITLE
Implement faster Virtual DOM replacement

### ISSUE THREAD

**Issue by kilofeq** [chakra-ui/chakra-ui#7748]
### Description

Implementing virtual DOM replacement would significantly increase components performance.

### Problem Statement/Justification

Projects with ChakraUI can be a bit heavy for browsers. Using a much faster virtual DOM can increase rendering time, so the user experience would be much better.

### Proposed Solution or API

It's possible to use Milion.js as a virtual DOM replacement. It can be implemented component by component, so it can be done progressively.

**Comment by segunadebayo** [comment]
Hey @kilofeq,

This is not within the scope of Chakra UI for now.
