### ISSUE TITLE
Tooltip hard to trigger and persists indefinitely in Safari

### ISSUE THREAD

**Issue by cers** [chakra-ui/chakra-ui#7755]
### Description

When Tooltip wraps a disabled Button, the tooltip is (sometimes?) hard to trigger. In attached example, it only seems to trigger when entering the button from the right. After it displays, it never goes away again. Triggering another tooltip would clear it though.

Only seems to be an issue in Safari.

If you pass shouldWrapChildren to the Tooltip component, then it behaves as expected.

### Link to Reproduction

https://play.chakra-ui.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwATFwCEBXbbCAOwBpcAVCCAG2yTRoGEALAQwGtNuABUwQAbkliZcAX1wAzESlwByAAJge-bgFpiSAPSYY3MNmUAdCpZgAPDDlyQKAZzwBBNGlwBeXAAoASh8APnxLXFx9fVxyJhYvJGdcHkwoGIgYzCQAc2yYKSQKXABlbjluLP8YCmx8+UVcLOzObACqcMjogCNSXAB3TmrcJDwoCBhnGhHcChhROuzxpO4+7gBPXG5s7kKOo2xiTCK-DoiAHi4+AWExCXzg04jcM-o41lxGbi6YRm9zEAAcnM6pw7klCiUyhUkP8HkUngiziQyJRhs4ACKJL6MGBQYLI8gUM76AmUOEI876V7MVjkp7Ey5aG7iSR0gKWaSWEDSIA

### Steps to reproduce

1. Go to attached link
2. Hover mouse over button from bottom, observe nothing happens
3. Hover instead from the side (the right)
4. Tooltip appears
5. Remove mouse from button
6. Tooltip persists

### Chakra UI Version

2.7.0

### Browser

Safari 16.4

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jonahallibone** [comment]
This is only in Safari versions < `16.5`

**Comment by gaspesla** [comment]
Still happening in Safari 17

**Comment by Mathias-Shiny** [comment]
Still an issue in 17.1.2

**Comment by segunadebayo** [comment]
It works in Safari 17.4.1. This must be related to pointer events in Safari and React.
