### ISSUE TITLE
Versioned documentation

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#776]
As an organization, we would like to provide versioned documentation, so that users on can always access the most up-to-date documentation for their version. 

This would be similar to the [React website](https://reactjs.org), where the documentation displayed by default is for the most recent version, while they provide a [React Versions](https://reactjs.org/versions) page that allows the user to switch to documentation for older versions.

In order to make this happen, we need to think through a few things:

1. We're using `gatsby` with `gatsby-plugin-mdx` for our documentation. What's the best approach to maintaining multiple versions of the same documentation files?

2. Our documentation uses Chakra components for component examples, live code editor output, **and** styling the mdx content of each page. The examples and editor output should use components from the version of Chakra specific to the pages the user is currently viewing, while the mdx components of each page should remain the same for all versions so that we can maintain styling/layout of our docs pages independently using the most up-to-date Chakra version. How can we use multiple versions of Chakra UI simultaneously in order to accomplish this?

These feel like potentially non-trivial problems, so we could really use outside expertise and community feedback to help guide us in a good direction. Any help is greatly appreciated!

**Comment by with-heart** [comment]
I found [this post](https://www.gatsbyjs.org/blog/2019-07-03-using-themes-for-distributed-docs/) from an Apollo developer on how they used gatby themes and `gatsby-source-git` to accomplish  versioning (among other things). This could be useful for #1.

**Comment by Ahmedmadugu** [comment]
Nice one

**Comment by segunadebayo** [comment]
@with-heart, I think zeit can make this a lot easier for us.

We can simply alias the current build to `v0.chakra-ui.com` and we should be good with this.

What do you think?

**Comment by with-heart** [comment]
I think that can at least give us the ability to support `v0` documentation once 1.0 is released. We'll probably need something a little fancier to be able to support minor/patch level versions beyond that, if we want that.

**Comment by segunadebayo** [comment]
I don't think we'll need to update v0 docs once we release v1. All efforts will move to v1 docs instead.

Let's leave out the need to create something fancier.

**Comment by with-heart** [comment]
That's fair. We can revisit it later if the need should arise
