### ISSUE TITLE
Tooltip onClose prop fires both when tooltip opens and closes

### ISSUE THREAD

**Issue by zachdorcinville21** [chakra-ui/chakra-ui#7760]
### Description

I have a Tooltip component like so:

`
<Tooltip
                hasArrow
                onClose={() => console.log('closed')}...
`

When the tooltip opens, the `onClose` prop gets fired, triggering the console log.

### Link to Reproduction

https://codesandbox.io/s/muddy-forest-m4rclc?file=/src/App.js

### Steps to reproduce

1. Hover over "Start editing to see some magic happen!"
2. Observe the console to see "closed" being logged when the tooltip opens instead of on close

### Chakra UI Version

2.6.1

### Browser

Google Chrome 114.0.5735.90

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Suzan-Dev** [comment]
In `use-tooltip.ts` file, calling `dispatchCloseEvent()` is producing the issue.

```js
const dispatchCloseEvent = useCloseEvent(ref, closeNow)

const openWithDelay = useCallback(() => {
  if (!isDisabled && !enterTimeout.current) {
    dispatchCloseEvent()
    const win = getWin(ref)
    enterTimeout.current = win.setTimeout(onOpen, openDelay)
  }
}, [dispatchCloseEvent, isDisabled, onOpen, openDelay])
```
