### ISSUE TITLE
Prop `className` did not match.

### ISSUE THREAD

**Issue by frostwowa** [chakra-ui/chakra-ui#7765]
When I use **ColorModeScript** I get `Warning: Prop "className" did not match. Server: "__variable_1769c4 __variable_268731 __variable_310ce6 bg-n-2 font-sans text-body-2 antialiased text-n-7 dark:bg-n-7 chakra-ui-dark" Client: "__variable_1769c4 __variable_268731 __variable_310ce6 bg-n-2 font -sans text-body-2 antialiased text-n-7 dark:bg-n-7"`

I use "@chakra-ui/next-js": "^2.1.4", "@chakra-ui/react": "^2.7.0" and **"next": "13.4.5".**

**_If I don't use ColorModeScript there is no error, but when I reload the page it flickers_**

providers.tsx =>
<img width="807" alt="1" src="https://github.com/chakra-ui/chakra-ui/assets/34405483/2420a21c-e8ad-4a5f-a188-fdca44e2b92d">

layout.tsx
<img width="973" alt="2" src="https://github.com/chakra-ui/chakra-ui/assets/34405483/27d9f166-31f1-4a8b-9b4a-16140101d75b">

**Comment by frostwowa** [comment]
@segunadebayo  then an error occurs, because we cannot use "use client" in the layout.tsx
<img width="980" alt="3" src="https://github.com/chakra-ui/chakra-ui/assets/34405483/01be4b7c-19a7-4808-bf3c-be36488d1c3e">

**Comment by frostwowa** [comment]
@segunadebayo layout.tsx

<img width="1118" alt="4" src="https://github.com/chakra-ui/chakra-ui/assets/34405483/dde9b3d6-b9a1-48af-b219-e52dd7ef2c17">

**Comment by frostwowa** [comment]
@segunadebayo providers.tsx

<img width="1069" alt="5" src="https://github.com/chakra-ui/chakra-ui/assets/34405483/65536688-4ce6-4218-a1be-fbf82433013f">

**Comment by fidalgodev** [comment]
Having the same issue, following the recommended setup from the docs [here](https://chakra-ui.com/getting-started/nextjs-guide#app-directory-setup)

Brand new project.

**Comment by frostwowa** [comment]
@segunadebayo it [it](https://chakra-ui.com/getting-started/nextjs-guide#app-directory-setup) shows how to add chakra to a project with a new next, but does not show how to add colormod to such a project

**Comment by frostwowa** [comment]
Help me, please!

**Comment by sktbrd** [comment]
I am having the same issues, when I try to solve creating a _document.tsx I get rid of the error, but I cant build in new next
