### ISSUE TITLE
blockScrollOnMount doesn't allow scroll of DOM elements

### ISSUE THREAD

**Issue by nextglabs** [chakra-ui/chakra-ui#7766]
### Description

When `blockScrollOnMount={false}` in `Drawer` or `Modal`, the vertical horizontal scroll of individual DOM elements doesn't work. 

### Link to Reproduction

https://codesandbox.io/s/xenodochial-goldstine-472jnv?file=/src/index.tsx

### Steps to reproduce

1. Open the Drawer
2. Try to scroll the red box behind the Modal until you see "You reached the bottom" text, which is initially hidden

### Chakra UI Version

2.7.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The vertical scroll works on the main element but not on individual DOM elements

**Comment by segunadebayo** [comment]
Here's how to resolve this:

```tsx
<ModalContent
  pointerEvents="all"
  containerProps={{ pointerEvents: 'none' }}
>
  {/* ... */}
</ModalContent>
```
