### ISSUE TITLE
[IImage interface] Bug in onLoad definition (and possibly onError)

### ISSUE THREAD

**Issue by wweaver** [chakra-ui/chakra-ui#777]
**Describe the bug**

The `<Image>` component's `onLoad` function is defined incorrectly in typescript. It's defined as `() => void`, but the first argument could be an `event`.

![image](https://user-images.githubusercontent.com/1482976/83261053-c0c54780-a188-11ea-8a45-699a0fee367d.png)

![image](https://user-images.githubusercontent.com/1482976/83261108-da668f00-a188-11ea-8f91-6603975c48f9.png)

**Expected Behavior**

If I just remove the `onLoad` definition in the `IImage` interface the type error goes away as the underlying BoxProps, really the React DomAttributes, already supports what is needed.

**To Reproduce**

Create an Image with an onLoad method that takes an event

```
<Image
    src={'/path/to/image'}
    onLoad={(event: SyntheticEvent<any, Event>): void =>
        console.log(event.currentTarget.width)
    }
/>
```

**Suggested solution(s)**
Remove the `onLoad` definition from the `IImage` interface.

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser: N / A
 - Version: N / A

**Additional context**
I'm not using the `onError` callback but I'm guessing that has the same issue.

**Comment by segunadebayo** [comment]
This is no longer an issue in the `v1` pre-release version.
