### ISSUE TITLE
Accordion doesn't open if you click it multipe times fast enough, and it loses track of state.

### ISSUE THREAD

**Issue by fidalgodev** [chakra-ui/chakra-ui#7775]
### Description

If you click the accordion button 3 times fast, the accordion acts up and loses state. It stays closed, even tho the Arrow icon stays on the open state. Then you need to click it twice for it to open again (first for it to close, even tho the panel is not rendering, and then again to open normally):

https://github.com/chakra-ui/chakra-ui/assets/41859298/027d6c14-e85d-474d-86d7-99ef1aab6912

JSX:

```
<Accordion allowToggle defaultIndex={[0]}>
  <AccordionItem>
    <AccordionButton>
      <Box as="span" flex="1">
        Accounts
      </Box>
      <AccordionIcon />
    </AccordionButton>
    <AccordionPanel flexDirection="column" display="flex">
      <NavLink as={NextLink} href={' '}>
        Monzo
      </NavLink>
      <NavLink as={NextLink} href={' '}>
        Starling
      </NavLink>
      <NavLink as={NextLink} href={' '}>
        Chase
      </NavLink>
    </AccordionPanel>
  </AccordionItem>
</Accordion>
```

### Link to Reproduction

N/A

### Steps to reproduce

1. Create an accordion
2. Click 3 times fast on the Button that triggers the opening
3. See the accordion panel not opening, even tho the arrow state is on the open state.

```
"@chakra-ui/next-js": "^2.1.4",
 "@chakra-ui/react": "^2.7.0",
```

### Chakra UI Version

2.1.4 next-js, 2.7.0 react js

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by henriquesml** [comment]
Apparently, the issue occurs in the Collapse component due to the missing display. I've opened a fix proposition PR at #7819

**Comment by chuganzy** [comment]
There seems to be a race condition in `framer-motion` that is causing this to happen. Looking into it later.

**Comment by chuganzy** [comment]
@nelsieborja That is because of the `framer/motion`'s version that website relies on. It uses older one, which does not have this issue.

**Comment by stefanalexlupu** [comment]
Hi, I am also encountering this problem on nested accordions. I reproduced this issue here: https://codesandbox.io/s/nested-accordions-in-chakra-ui-59ncv4?file=/src/App.js

When an accordion is open, if you double click, it closes but the button remains in the open state

framer-motion v10 (mentioning this because comments above indicate it might be a framer motion issue)

**Comment by forrestwilkins** [comment]
@chuganzy Downgrading `framer-motion` to `v9` worked for me as well.

**Comment by Nightbr** [comment]
Same here, downgrading to `framer-motion` to `v9` works. 
We tested with latest framer-motion version v10.16.16 -> bug with the `defaultIndex={[0]}` not diplayed

**Comment by chuganzy** [comment]
I have an open PR that solves this issue here. https://github.com/framer/motion/pull/2265

**Comment by goncaloflf** [comment]
FYI if someone is still facing this issue, bumping your framer-motion version to `v.11.x.x` seems to solve this issue. Maybe @fidalgodev can close this issue now 🙏
