### ISSUE TITLE
React Hook Form example does not work with Chakra 2.x.x

### ISSUE THREAD

**Issue by banool** [chakra-ui/chakra-ui#7776]
### Description

This tutorial is written for Chakra 1.x.x but it shows up even when you have the docs for 2.x.x selected: https://chakra-ui.com/getting-started/with-hook-form. When viewing the 2.x.x docs this page should not show the example and instead say "this example is only for 1.x.x".

Check out the code, you'll notice the value being passed into isInvalid is no longer correct.

Better than saying "this is example is only for 1.x.x" would be to update the example for 2.x.x also. But I'm really struggling to get it working.

### Link to Reproduction

https://codesandbox.io/s/tender-panna-kp5c8z?file=/src/index.tsx

### Chakra UI Version

2.7.0

### Browser

Firefox 114.0.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by tuananhl** [comment]
@banool that's only typing issue. 
First, you need to give that hook the form interface like

```useForm<{name: string}>()```

then, for `isInvalid` prop, which required a boolean value. So change from `isInvalid={errors.name}` to `isInvalid={!!errors.name}` basically
