### ISSUE TITLE
Auto focus is on last `MenuItem` instead of the first if `Menu` has `isLazy` attribute

### ISSUE THREAD

**Issue by romanstetsyk** [chakra-ui/chakra-ui#7779]
### Description

When a `Menu` is opened and has an `isLazy` attribute, the last `MenuItem` in the `MenuList` receives focus instead of the first.

### Link to Reproduction

https://codesandbox.io/p/sandbox/nostalgic-mirzakhani-hmkvmx?file=%2Fsrc%2FApp.tsx%3A15%2C1

### Steps to reproduce

1. Click on `Open Menu` that has `isLazy`
2. See that the last item has the focus
3. For comparison, click on `Open Menu` that doesn't have `isLazy`
4. See that the first item is focused, as expected

### Chakra UI Version

2.7.0

### Browser

Google Chrome 114

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The bug can be reproduced in the Chrome browser but not in Safari.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
