### ISSUE TITLE
The layout or style of the input type datetime-local

### ISSUE THREAD

**Issue by UmerGillani36** [chakra-ui/chakra-ui#7782]
### Description

i am using the input component of chakra-ui of type datetime-local and it is landscape date and time but in mobile side i want to open this in portrait this is my code how can i do this? 

### Problem Statement/Justification

In mobile side the modal of date-time picker overflows, this input should have the attribute of landscape and portrait 

### Proposed Solution or API

<Input
              placeholder={String?.createCampaign?.deadlinePlaceholder}
              size="md"
              type="datetime-local"
              value={deadline}
              min={new Date().toISOString().split('.')[0]}
              onChange={(e) => setDeadline(e.target.value)}
            />

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Please follow the issue template as we're not able to act on issues that are lacking important information.
