### ISSUE TITLE
shadowColor of PopoverArrow is spit out directly into the DOM

### ISSUE THREAD

**Issue by touyou** [chakra-ui/chakra-ui#7784]
### Description

When using shadowColor, a new property of PopoverArrow, I found that the shadowColor is spit out directly into the DOM. Rendering itself is not a problem, but warnings are appearing, and this is affecting testing and other operations.

### Link to Reproduction

https://codesandbox.io/s/shadowcolor-sample-gxknmg

### Steps to reproduce

1. Open reproduction sandbox
2. Select Console Tab

### Chakra UI Version

2.7.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

![image](https://github.com/chakra-ui/chakra-ui/assets/465697/fb9d1d4b-20db-44f9-b9a7-b25e5385cdec)

![image](https://github.com/chakra-ui/chakra-ui/assets/465697/7f5a45d6-f7d9-4754-84b1-4cba1e75275e)

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
