### ISSUE TITLE
Modal edges break when resizing the content in Safari 16

### ISSUE THREAD

**Issue by adam-stanek** [chakra-ui/chakra-ui#7787]
### Description

Hi guys, I am having an weird issue in Safari 16 when vertically expanding the modal content.

Here is minimalistic snippet:

```typescript
function TestModal() {
  const { isOpen: expanded, onToggle } = useDisclosure()

  return (
    <Modal isOpen={true} onClose={() => {}}>
      <ModalOverlay />
      <ModalContent>
        <Box p={4}>
          <Button onClick={onToggle}>Expand</Button>
          <Box pt={2}>
            <Collapse in={expanded}>
              <Box h="100px" bg="gray.200" borderRadius="lg" />
            </Collapse>
          </Box>
        </Box>
      </ModalContent>
    </Modal>
  )
}
```

It creates rendering artifacts around the modal edges (see screenshot).

There was similar issue reported and closed on Chakra v1 #7593 

### Link to Reproduction

https://codesandbox.io/s/crazy-gauss-nqcp54?file=/src/index.tsx

### Steps to reproduce

1. Click on Expand button

### Chakra UI Version

2.7.1

### Browser

Safari 16.5

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

<img width="487" alt="Screenshot 2023-06-20 at 23 30 28" src="https://github.com/chakra-ui/chakra-ui/assets/701570/463d2bb8-e90f-4423-b478-87385a6f1a11">

**Comment by solestravis** [comment]
Hey Adam, just saw your comment on my issue. I did not manage to solve this.
Glad you could reproduce it, I'll keep an eye out to see what they tell you here.

**Comment by segunadebayo** [comment]
Please use the solution shown here:
https://github.com/orangehrm/oxd/pull/755/files
