### ISSUE TITLE
[Avatar] MenuList not displaying in the correct location when using Avatar as MenuButton

### ISSUE THREAD

**Issue by KevinLu** [chakra-ui/chakra-ui#779]
**Describe the bug**
The MenuList is not displaying below the Avatar MenuButton when opened.
![image](https://user-images.githubusercontent.com/18564130/83314747-f4848980-a1e9-11ea-93bd-8a75c997c2f4.png)

As you can see from the image, the MenuList appears all the way on the left of the screen, while the MenuButton is on the right.

**Expected Behavior**
The MenuList appears just below the MenuButton.

**To Reproduce**
```jsx
        <Menu>
          <MenuButton as={Avatar}></MenuButton>
          <MenuList>
            <MenuItem color="black">My account</MenuItem>
            <MenuItem color="black">Orders</MenuItem>
            <MenuDivider />
            <MenuItem color="black">Logout</MenuItem>
          </MenuList>
        </Menu>
```

Click on the MenuButton.

**Suggested solution(s)**
While this is not a solution, it is a workaround. We can use the Image component.
```jsx
        <Menu>
          <MenuButton size="40px" rounded="full" src="https://bit.ly/sage-adebayo" as={Image}></MenuButton>
          <MenuList>
            <MenuItem color="black">My account</MenuItem>
            <MenuItem color="black">Orders</MenuItem>
            <MenuDivider />
            <MenuItem color="black">Logout</MenuItem>
          </MenuList>
        </Menu>
```
![image](https://user-images.githubusercontent.com/18564130/83314828-4af1c800-a1ea-11ea-90b8-713c106525f5.png)

The drawbacks of this workaround are the missing features of the Avatar component (fallbacks and badges).

**Desktop**
- OS: Windows 10 Home
- Browser: Firefox 76.0.1 (64-bit)

**Comment by segunadebayo** [comment]
Hey @KevinLu, this is usage is incorrect. The MenuButton should not be replaced with the Avatar instead, the avatar should be wrapped within the MenuButton.

Here's what I mean:

```jsx
<Menu>
     <MenuButton>
       <Avatar src="https://bit.ly/sage-adebayo" />
     </MenuButton>
     <MenuList>
       <MenuItem color="black">My account</MenuItem>
       <MenuItem color="black">Orders</MenuItem>
       <MenuDivider />
       <MenuItem color="black">Logout</MenuItem>
     </MenuList>
</Menu>
```

I hope this helps.

**Comment by KevinLu** [comment]
Thanks! Your implementation is working great!
