### ISSUE TITLE
PopoverContentProps has to accept children as other props types of Chakra-UI component do.

### ISSUE THREAD

**Issue by yukiyohure** [chakra-ui/chakra-ui#7795]
### Description

I updated `@chakra-ui/react` from 2.5.5 to 2.7.0 then the `PopoverContentProps` doesn't have the type for children inside.

```ts
// custom_popover_content.tsx
import {PopoverContent, PopoverContentProps} from '@chakra-ui/react';
import React, {forwardRef} from 'react';

export const MyPopoverContent = forwardRef<HTMLDivElement, PopoverContentProps>((props, ref) => (
  <PopoverContent
    ref={ref}
    // Customize something
    {...props}
  />
));

// my_popover.tsx
export default function MyPopover() {
  return (
    <Popover>
      <PopoverTrigger>
        <Button>Trigger</Button>
      </PopoverTrigger>
      <MyPopoverContent> // Type '{ children: Element; }' is not assignable to type 'IntrinsicAttributes & PopoverContentProps & RefAttributes<HTMLDivElement>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & PopoverContentProps & RefAttributes<HTMLDivElement>'.
        <PopoverArrow />
        <PopoverCloseButton />
        <PopoverHeader>Confirmation!</PopoverHeader>
        <PopoverBody>Are you sure you want to have that milkshake?</PopoverBody>
      </PopoverContent>
    </Popover>
  );
}
```

With the code above TS tells me an error saying ` // Type '{ children: Element; }' is not assignable to type 'IntrinsicAttributes & PopoverContentProps & RefAttributes<HTMLDivElement>'` while other types of the prop for Chakra-UI component that can have children accept the children type inside, e.g. `TabPanelProps`.

### Link to Reproduction

https://codesandbox.io/s/happy-jasper-w24t94?file=/src/index.tsx

### Chakra UI Version

2.7.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This works now in the latest version
