### ISSUE TITLE
[Dialog] Warnings

### ISSUE THREAD

**Issue by alexluong** [chakra-ui/chakra-ui#78]
When using `Dialog` component, it gives a few warnings:

- Reach UI warning, similar to #65
- `React does not recognize the zIndex prop on a DOM element...`
- `React does not recognize the overflowY prop on a DOM element...`

Just wanna let you know about this. It's just a bit of annoyance, but everything works fine.

**Comment by segunadebayo** [comment]
Yeah, I understand it can be annoying.

I'll resolve the last 2 items and release a patch. For Reach UI, I'll find a way to suppress the error until they resolve it.
