### ISSUE TITLE
Width with number or list of numbers doesn't work as expected

### ISSUE THREAD

**Issue by RannyArcher** [chakra-ui/chakra-ui#7801]
### Description

**when i** open a file that includes this following code on the browser.
```tsx
<Box width={[1, 1 / 2, 1 / 4]} />
```
**i expected** the size to be full width on small screen, half width on medium ones, quarter width on large ones.
**but i get** weired width on each small and medium screens. but correct one in the large one.

i inspected the sizes variables used and i found that, some used sizes like `--chakra-sizes-1` and `--chakra-sizes-0-5` are defined in fixed unit not percentage and i think that's what causing this problem which makes the desired scenarioas mentioned above and in [documentation](https://chakra-ui.com/docs/styled-system/responsive-styles[#](https://chakra-ui.com/docs/styled-system/responsive-styles#under-the-hood)under-the-hood) too, doesn't work as desired.

### Link to Reproduction

localhost

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

latest

### Browser

qutebrowser, firefox

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

sfsdf

**Comment by segunadebayo** [comment]
Please use the percentage versions instead.
