### ISSUE TITLE
Heading sizes & device breakpoints don't work well when used in extendTheme

### ISSUE THREAD

**Issue by jsinglamms** [chakra-ui/chakra-ui#7807]
### Description

When I create a heading, using a size attribute, and set the fontSize with multiple values depending on the device breakpoint, this is not working and ignoring it when using the extendTheme, if the fontSize is defined in the heading directly works fine. 

The Text component works fine

### Link to Reproduction

https://codesandbox.io/s/sxgs9c?file=%2FApp.tsx&utm_medium=sandpack

### Steps to reproduce

1. Go to 'the code sandbox'
2. Resize the window
3. You can see how the first heading and the text fontSize change, but the heading in the middle don't chage 

If you inspect the second Headingsize, you will se that only the mint-width query of 48px is generated, and nothing else. 

### Chakra UI Version

React 2.6.1

### Browser

Firefox

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I'm not sure it's an error, seems related to this: https://github.com/chakra-ui/chakra-ui/issues/3501 But Maybe I'm doing something wrong.

Today I investigated more, if the info is set with a list for the heading works, but with the object doesn't work, it generates the default.

**Comment by muco-rolle** [comment]
The middle text and the last text have a fixed size of 4xl. However, the first text has breakpoints(` fontSize={{base: '30px', md: '40px', lg: '72px', xl: '90px'}}`), which is why it does change size while the others don't.

I hope this helps! Let me know if you have any other questions.

**Comment by Dracks** [comment]
first of all, the only one that doesn't change, is the middle one (the one that has a problem) second of all, the size with breakpoints is defined in the theme.tsx:
```
export const theme = extendTheme({
  components: {
    Heading: {
      sizes: {
        '4xl': {
          fontSize: {base: '30px', md: '40px', lg: '72px', xl: '90px'}
        } 
      },
    },
    Text: {
      sizes: {
        '4xl': {
          fontSize: {base: '30px', md: '40px', lg: '72px', xl: '90px'}
        } 
      },
    }
  }
})
```
Also, we discover that if we put the size breakpoints in the heading as an array works, but doesn't work as an object.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
