### ISSUE TITLE
`Tabs` component moves focus when pressing Cmd/Ctrl-LeftArrow

### ISSUE THREAD

**Issue by jfdoming** [chakra-ui/chakra-ui#7808]
### Description

Keyboard handling for tabs does not seem to handle modifier keys properly. Specifically, using the keyboard shortcut for the browser back button (Cmd-LeftArrow on MacOS) causes the `onChange` handler of the tabs component to fire as if only `LeftArrow` was pressed.

Expected behaviour: The component should ignore events like this where the browser is already running logic.

### Link to Reproduction

https://codesandbox.io/s/pnvjp2?file=/App.tsx

### Steps to reproduce

1. Render a basic tab component (e.g. open the repro sandbox).
2. Focus one of the tabs.
3. Press "Cmd-LeftArrow" (or "Ctrl-LeftArrow" depending on your system) in order to navigate back one page.
4. Observe that the current tab is updated.

### Chakra UI Version

2.7.1

### Browser

Google Chrome 114

### Operating System

- [X] macOS
- [x] Windows
- [x] Linux

**Comment by segunadebayo** [comment]
Hi @jfdoming,

I can't seem to reproduce this on MacOS. Ctrl + Tab key doesn't move the focus.

Could you send a screen recording of this behavior?

**Comment by jfdoming** [comment]
Hi! Sorry for the delay, I was on vacation. Here is what I mean:

https://github.com/chakra-ui/chakra-ui/assets/9922514/60963680-00df-47d7-814c-bb08275e833a

As the video shows, the Command+Arrow combinations would normally be used for navigation, but Chakra is interpreting them as moving the tab.

**Comment by segunadebayo** [comment]
This is by design. The tab component should prevent the default browser behavior and handle the event itself.
