### ISSUE TITLE
[Theme] Body background color is not being changed

### ISSUE THREAD

**Issue by geocine** [chakra-ui/chakra-ui#781]
**Describe the bug**
https://codesandbox.io/s/chakra-ts-starter-sn639

I have created a theme and changed the background however it is not being applied 

```jsx
const customTheme = {
  ...theme,
  colors: {
    ...theme.colors,
    background: "red.500"
  }
};

function App() {
  return (
    <ThemeProvider theme={customTheme}>
      <Heading>Welcome</Heading>
    </ThemeProvider>
  );
}
```

**Expected Behavior**
The body `background` should change to `red.500`

**To Reproduce**
https://codesandbox.io/s/chakra-ts-starter-sn639

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Firefox Developer Edition
 - Version: 77.0b9

**Additional context**
https://theme-ui.com/theming/, says here changing the `body` , changes the Body background color

**Comment by dskline** [comment]
Currently, support for dot notation isn't available on the initial theme configuration object. (I also wouldn't expect this to be a high priority feature).

What you can do instead (two options):

**Option 1**

Copy and paste the hex color from https://chakra-ui.com/theme#red

```
const customTheme = {
  ...theme,
  colors: {
    ...theme.colors,
    background: "#E53E3E"
  }
};
```

**Option 2**

Import the color from the chakra library:

```
import chakraColors from '@chakra-ui/core/dist/theme/colors'

const customTheme = {
  ...theme,
  colors: {
    ...theme.colors,
    background: chakraColors.red['500']
  }
};
```

**Comment by dskline** [comment]
It looks like you're referencing the APIs of two different UI libraries. (Chakra and Theme UI)

Check out the documentation for using Chakra's ThemeProvider here:
https://chakra-ui.com/getting-started

You're probably wanting something like this:

```
function App() {
  return (
    <ThemeProvider theme={customTheme}>
      <Box bg="red.500" minHeight="100vh">
        <Heading>Welcome</Heading>
      </Box>
    </ThemeProvider>
  );
}
```

**Comment by geocine** [comment]
@dskline My assumption that its similar to how `theme-ui` works is incorrect, thank you for pointing that out. I checked the documentation of `chakra-ui` there isn't a way to change the body specific css without using a global css (eg. emotion's `Global`). Am I missing something or using a global css is the only way?

**Comment by dannytatom** [comment]
to add on to what @dskline said, i've found that you also need `minWidth="min-content"`, otherwise things get wonky on mobile when scrolling horizontally if content stretches beyond the viewport.

what do you mean by needing to change body specific CSS?

**Comment by geocine** [comment]
@dannytatom I want to attach the css to the HTML `<body>`.

The solution given by @dskline is essentially creating `<div>` inside the react root element which is inside the `<body>` and attaching the css to that. 

I effectively want to do this the chakra way
```css
body { 
   background-color: red;
}
```

**Comment by dannytatom** [comment]
@geocine yeah, there's no real way to do that since the body lives outside the react app. is there a reason what @dskline suggested wouldn't work? it's how we've been doing it at my job and works fine.

**Comment by geocine** [comment]
It's looks unnatural to me, if you add it to the `body`, then you wouldn't need to mess with `minHeight` and `minWidth`. That is - why this is in `theme-ui` which is also based on the Styled System.

**Comment by santialbo** [comment]
You can set the background color on the `<CSSReset/>` element. Check this updated codesanbox
https://codesandbox.io/s/chakra-ts-starter-fn3yt?file=/src/index.tsx

```tsx
const config = (theme: ITheme) => ({
  light: {
    color: theme.colors.gray[700],
    bg: theme.colors.red[500],
    borderColor: theme.colors.gray[200],
    placeholderColor: theme.colors.gray[500]
  },
  dark: {
    color: theme.colors.whiteAlpha[900],
    bg: theme.colors.gray[800],
    borderColor: theme.colors.whiteAlpha[300],
    placeholderColor: theme.colors.whiteAlpha[400]
  }
});

function App() {
  return (
    <ThemeProvider theme={theme}>
      <CSSReset config={config} />
      <Heading>Welcome</Heading>
    </ThemeProvider>
  );
}
```

**Comment by geocine** [comment]
Oh dang, thank you @santialbo , I think this works for me so I'll be closing this issue.
