### ISSUE TITLE
Error: Element type is invalid: expected a string ... Check the render method of `Styled(Component)` when using Image component

### ISSUE THREAD

**Issue by abdulramonjemil** [chakra-ui/chakra-ui#7827]
### Description

When I import and use the Image component from the `@chakra-ui/next-js` package in a next.js project, I expect everything to work fine with no errors. However, I get the element type is invalid error.

### Link to Reproduction

https://codesandbox.io/p/sandbox/chakra-next-image-error-fxgmws

### Steps to reproduce

Navigate to the /signup route, and you'll see the error.

### Chakra UI Version

2.7.1

### Browser

Google Chrome 114

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

The error occurs when I try to use the `Image` component from `@chakra-ui/next-js` in any of the pages. If you comment out the part where the component is used (in `app/signup/layout.tsx`), no error occurs.

```tsx
function TopBar() {
  console.log(ChakraNextImage, "\n", HStack);

  return (
    <HStack p="6">
      {/* <ChakraNextImage
        alt="Quiz Labb Logo"
        height="50"
        src="/quiz-labb.svg"
        width="50"
        h="14"
        w="14"
      /> */}
    </HStack>
  );
}
```

I've tried many things, but none work, including changing props, moving the component call to a page file instead of a layout file, etc. When I pass the component, i.e. `<ChakraNextImage ... />` to `React.isValidElement`, it returns true, so I don't know why the error keeps showing up.

**Comment by abdulramonjemil** [comment]
Is anyone willing to look into this? I've been stuck on it for several hours now.

**Comment by vaibhav1324** [comment]
Hey everyone 🙋🏻‍♂️
checkout my article on how i style my chakra components
https://medium.com/@vaib1324/enhancing-code-readability-with-chakrastyled-in-chakra-ui-9c656219a924

**Comment by jakubczarnowski** [comment]
Any  updates?

**Comment by abdulramonjemil** [comment]
> Any updates?

None so far. I also found out that it's not just `Image`. It's the same for the `Link` component. A quick workaround is to use the `as` with the raw Nextjs component. For example:

```jsx
return (
  <ChakraNextLink as={NextLink} href="#" />
)
```

**Comment by jakubczarnowski** [comment]
Note: currently this issue only happens on next version 13.4.8+, anything below works fine

**Comment by jaybells12** [comment]
> Any updates?

Hey, I was running into a similar issue. I was able to work around it by manually creating the Image component.
```
import { chakra, ChakraComponent } from '@chakra-ui/react'
import NextImage, {
  StaticImageData,
  ImageProps as NextImageProps,
} from 'next/image'
const Image: ChakraComponent<'img', NextImageProps> = chakra(NextImage, {
  shouldForwardProp: (prop) =>
    [
      'src',
      'alt',
      'width',
      'height',
      'fill',
      'loader',
      'quality',
      'priority',
      'loading',
      'placeholder',
      'blurDataURL',
      'unoptimized',
      'onLoadingComplete',
    ].includes(prop),
})
```

Definitely not ideal, but at least can continue on other things while this issue gets resolved.

**Comment by abdulramonjemil** [comment]
Makes sense. I hope that they fix it as soon as possible. According to @jakubczarnowski's comment, it looks like it's an issue with Next.js, not Chakra. So, we'll have to wait. Maybe someone can create an issue there 😐.

**Comment by segunadebayo** [comment]
Hi @abdulramonjemil,

This isn't a bug in Chakra UI, as far as I can tell. Please create an issue in the Next.js repo about this.

Thanks
