### ISSUE TITLE
Attempted import error: 'getColorVar' is not exported from '@chakra-ui/theme-tools' (imported as 'getColorVar').

### ISSUE THREAD

**Issue by villesau** [chakra-ui/chakra-ui#7832]
### Description

When installing chkra-ui and running it via next.js, I'm getting: `Attempted import error: 'getColorVar' is not exported from '@chakra-ui/theme-tools' (imported as 'getColorVar').`

### Link to Reproduction

Not available

### Steps to reproduce

1. install latest chakra and related packages at the time of writing (necessarily no need for latest, not sure)
2. install next.js
3. run `yarn dev`
4. navigate to the app
5. following error is thrown:

```
error - ./node_modules/@chakra-ui/theme/dist/chunk-VB5QFFP5.mjs
Attempted import error: 'getColorVar' is not exported from '@chakra-ui/theme-tools' (imported as 'getColorVar').

Import trace for requested module:
./node_modules/@chakra-ui/theme/dist/chunk-VB5QFFP5.mjs
./node_modules/@chakra-ui/theme/dist/index.mjs
./node_modules/@chakra-ui/react/dist/index.mjs

```

### Chakra UI Version

2.7.1

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @villesau,

This was fixed in a recent PR from @TylerAPfledderer. 

We'll release an update shortly.

If the issue persists after the release, I'll re-open this issue.
