### ISSUE TITLE
Avatar alt text

### ISSUE THREAD

**Issue by HaleyWardo** [chakra-ui/chakra-ui#7833]
### Description

How to include alternative text to `img` without a `name` being provided.

### Problem Statement/Justification

In our specific use case, we are not wanting to display the user initials and just have the fallback be a user icon. The issue with this is that we aren't passing in a `name` so that the fallback initials will be ignored. With doing this, the `alt` attribute isn't getting applied and is causing accessibility errors. 

_Note:_ we are always passing in an `aria-label`.

Things I've tried: 
- Passing in `alt` and `aria-label` but those attributes are getting applied to the `span`. 
- Passing in `ignoreFallback` but this prevents the fallback icon from being rendered.

<img width="251" alt="Screen Shot 2023-07-07 at 10 33 24 AM" src="https://github.com/chakra-ui/chakra-ui/assets/32574227/f70d7d64-523f-429f-8b0c-b60c74504257">

### Proposed Solution or API

Possible solutions: 

- Allow for an `alt` prop to be passed in and applied to the `svg`. 
- Create a new `fallbackOrder` prop which will allow consumers to decide the fallback + order (EX: `['src', 'icon']`. With this, we can now pass in the `name` prop.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
