### ISSUE TITLE
Can't change `Tabs` `background-image` with theming.

### ISSUE THREAD

**Issue by IceFreez3r** [chakra-ui/chakra-ui#7841]
### Description

I tried to change the `background-image` of the `Tabs` component using a custom theme, but it's overwritten by `background: var(--tabs-bg)` from [this line](https://discord.com/channels/660863154703695893/1127177191483002890/1127177191483002890), which is undefined, so the background is set to nothing.
The theme is otherwise correctly applied, so I would assume, that the problem is somewhere else.

### Link to Reproduction

Uses background color instead of image, but same problem

https://codesandbox.io/s/nifty-hoover-l78tdp

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.4.9

### Browser

Firefox

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

![grafik](https://github.com/chakra-ui/chakra-ui/assets/39794212/d7712256-1dc7-4d06-9d67-1613d50904df)

**Comment by OmprakashR** [comment]
Hi,
I am facing the same issue in my project. 
**Solution:** using the overwrite of the base class using CSS. hope this will help you.


`.chakra-tabs__tablist button {
  background-color: #000000;
  color: #fff;
}
`
Thank you!

**Comment by segunadebayo** [comment]
The default variant of the tabs component is `line`. I recommend overriding the styles for that variant instead.

```tsx
import { tabsAnatomy } from "@chakra-ui/anatomy";
import { createMultiStyleConfigHelpers } from "@chakra-ui/styled-system";

const { defineMultiStyleConfig } = createMultiStyleConfigHelpers(
  tabsAnatomy.keys
);
const tabsTheme = defineMultiStyleConfig({
  baseStyle: {
    tab: {
      paddingX: "5px",
      transition: "transform 0.05s",
      _hover: {
        transform: "scale(1.05)",
      },
    },
  },
  variants: {
    line: {
      tab: {
        background: "black",
        _selected: {
          background: "red",
          color: "white",
          border: "none",
        },
      },
    },
  },
});

export default tabsTheme;

```
