### ISSUE TITLE
@chakra-ui/react"' has no exported member named 'Grid'. Did you mean 'grid'?

### ISSUE THREAD

**Issue by nitin-pandita** [chakra-ui/chakra-ui#7844]
### Description

I wanted to import a grid from Chakra ui but it is not importing, it is giving an error. I tried to reinstall the chakra ui but still showing the same error

### Link to Reproduction

http://localhost:5173/

### Steps to reproduce

1. Go to ''
2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.7.1

### Browser

Google Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by vaibhav1324** [comment]
Hey everyone 🙋🏻‍♂️
checkout my article on how i style my chakra components
https://medium.com/@vaib1324/enhancing-code-readability-with-chakrastyled-in-chakra-ui-9c656219a924

**Comment by aklite** [comment]
and the issue above @nitin-pandita mentioned same problem  along with that
Module '"@chakra-ui/react"' has no exported member 'Box'.

Module '"@chakra-ui/react"' has no exported member 'Flex'.
i am using @chakra-ui/react version 2.5.3

**Comment by cr1pt0-d3v** [comment]
Hi guys, I have the same problem with Drawer and all his related components 'Module '"@chakra-ui/react"' has no exported member 'DrawerHeader'.' in typescript, how I can fix this, thank you

**Comment by segunadebayo** [comment]
Please upgrade to the latest version

**Comment by tschaub** [comment]
I'm seeing these same issues with @chakra-ui/react@3.8.1.
```
src/main.jsx:1:9 - error TS2305: Module '"@chakra-ui/react"' has no exported member 'Box'.
1 import {Box, ChakraProvider, Flex, defaultSystem} from '@chakra-ui/react';
          ~~~

src/main.jsx:1:14 - error TS2305: Module '"@chakra-ui/react"' has no exported member 'ChakraProvider'.
1 import {Box, ChakraProvider, Flex, defaultSystem} from '@chakra-ui/react';
               ~~~~~~~~~~~~~~

src/main.jsx:1:30 - error TS2305: Module '"@chakra-ui/react"' has no exported member 'Flex'.
1 import {Box, ChakraProvider, Flex, defaultSystem} from '@chakra-ui/react';
                               ~~~~

Found 3 errors in the same file, starting at: src/main.jsx:1
```

**Comment by JeelRajodiya** [comment]
in my case, I had to revert `pnpm-lock.yaml` file from the working state of the codebase.
