### ISSUE TITLE
Prop className did not match -  using ColorModeScript (Next 13.4.5 and App routing)

### ISSUE THREAD

**Issue by frostwowa** [chakra-ui/chakra-ui#7845]
When I use **ColorModeScript** I get Warning: Prop "className" did not match. Server: "__variable_1769c4 __variable_268731 __variable_310ce6 bg-n-2 font-sans text-body-2 antialiased text-n-7 dark:bg-n-7 chakra-ui-dark" Client: "__variable_1769c4 __variable_268731 __variable_310ce6 bg-n-2 font -sans text-body-2 antialiased text-n-7 dark:bg-n-7"

**If I don't use ColorModeScript there is no error, but when I reload the page it flickers.**

**I use "@chakra-ui/next-js": "^2.1.4", "@chakra-ui/react": "^2.7.1" and "next": "13.4.5".**

[**Here**](https://chakra-ui.com/getting-started/nextjs-guide#installation) shows how to add chakra-ui to a project with a new Next JS (13.4.5 with App Router), but does not show how to add ColorModeScript to such a project

Shown only for old Next JS without App 

If we add ColorModeScript to the layout.tsx, then an error occurs, because we cannot use "use client" in the layout.tsx
<img width="880" alt="1" src="https://github.com/chakra-ui/chakra-ui/assets/34405483/92be2682-af2f-410e-88f8-9eff61c57638">

Error
<img width="980" alt="2" src="https://github.com/chakra-ui/chakra-ui/assets/34405483/7783b21a-e8aa-4c0c-b30d-77eb1a4a281d">

**Comment by frostwowa** [comment]
Now I have this structure

providers.tsx
<img width="830" alt="3" src="https://github.com/chakra-ui/chakra-ui/assets/34405483/af10cf5c-5899-476a-ae14-3c8ef137660a">

layout.tsx
<img width="1022" alt="4" src="https://github.com/chakra-ui/chakra-ui/assets/34405483/e830aba7-7587-4739-b121-fa374aa89d47">

**Comment by frostwowa** [comment]
This problem is only on local part, when I see on hosting then all good

**Comment by s4sh4w4lk3r** [comment]
Thanks for telling me that the problem is only on the dev server, but everything is fine on prod. I just did the script execution based on the condition of the environment value.

```
// Providers.tsx
export default function Providers({ children }: { children: ReactNode }) {
    return (
        <ChakraProvider>
            <>
                // here
                {env.NODE_ENV === "production" ?? (
                    <ColorModeScript
                        initialColorMode={"dark"}
                        key={"color-script"}
                    />
                )}

                {children}
            </>
        </ChakraProvider>
    );
}
```

**Comment by segunadebayo** [comment]
Please add `supresshydrationWarning` to the html element to fix this.
