### ISSUE TITLE
`TabIndicator` does not align with `Tab` when window is resized with center-aligned tabs

### ISSUE THREAD

**Issue by debater-coder** [chakra-ui/chakra-ui#7846]
### Description

Following [this](https://chakra-ui.com/docs/components/tabs/usage#styling-the-tab-states-via-props) example, I created some tabs which I could use with custom styles. When it is center-aligned, and the window is resized, the `TabIndicator` moves out of alignment.

### Link to Reproduction

https://codesandbox.io/s/mystifying-cache-jg7g8n?file=/src/index.tsx

### Steps to reproduce

1. Open the sandbox
2. Resize the viewport
3. See that the `TabIndicator` does not align properly

### Chakra UI Version

2.7.1

### Browser

Microsoft Edge 114.0.1823.67 (Official build) (64-bit) 

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![image](https://github.com/chakra-ui/chakra-ui/assets/52619668/0b6e2bfc-a988-4842-9b6f-3137bfea87f6)

**Comment by vennilamahalingam** [comment]
#7882
