### ISSUE TITLE
Non-unique ids are generated when using `CheckboxGroup` and `FormControl`

### ISSUE THREAD

**Issue by romanstetsyk** [chakra-ui/chakra-ui#7847]
### Description

All checkboxes in `CheckboxGroup` have the same `id` attribute if used with `FormControl`.
Expected behavior: all ids should be unique.

### Link to Reproduction

https://codesandbox.io/p/sandbox/checkboxgroup-unique-id-ww6lnx?file=%2Fsrc%2FApp.tsx%3A6%2C34

### Chakra UI Version

2.7.1

### Browser

Google Chrome 114

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

<img width="719" alt="image" src="https://github.com/chakra-ui/chakra-ui/assets/25715951/7766948f-4092-464e-a98a-0d158d2edffc">

Related issue: #3074

**Comment by segunadebayo** [comment]
Hi @romanstetsyk.

FormControl was not designed to work with CheckboxGroup. Please use explicit ids in your code.

We'll add this to the docs.
