### ISSUE TITLE
[Slider] CSS styles are recreated each time the value changes.

### ISSUE THREAD

**Issue by vmenard17** [chakra-ui/chakra-ui#786]
**Describe the bug**

When the value property of Slider changes programmatically, when I inspect the DOM, CSS styles are recreated each time.

**Expected Behavior**

CSS styles should be injected only once.

**To Reproduce**
1 - https://codesandbox.io/s/flamboyant-colden-h379g
2 - Inspect DOM

**Desktop (please complete the following information):**
 - Version @chakra-ui/core@0.8.0

**Comment by with-heart** [comment]
This has been fixed in 1.0. The track now uses an inline `style` tag to manage the specific styles that update as the slider handle is moved.

You can see it in action here: https://next.chakra-ui.com/docs/form/slider
