### ISSUE TITLE
[Possible Bug] Chakra UI Drawer component destroy child components on close?

### ISSUE THREAD

**Issue by samitkxel** [chakra-ui/chakra-ui#7867]
### Description

I am using Chakra UI Drawer component, and I have nested a form inside of it, which has some really complicated states inside of it. The problem is when I am closing the drawer, the child nested(child) elements inside of the drawer are being destroyed and all the states inside of it are being reset.

I want something like Antd library, which has a prop that you can pass to the drawer as destroyOnClose = false that prevents the Drawer to not destroy its children on close. I want the same thing for Chakra. Is there a way? 
like for Antd reference: https://ant.design/components/drawer#api

In my sample code:-
When you'll click the "Open" button. It'll open the drawer and inside of it, there will be an input field. When you'll write something inside of it, close the drawer, and reopen it then the value inside of the text field will be gone because the Drawer destroys the child component. 

### Link to Reproduction

https://codesandbox.io/s/laughing-johnson-cy47rf?file=/src/Form.jsx

### Chakra UI Version

2.5.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by samitkxel** [comment]
Thanks @vldvel for the response. I am hoping that they would notice it and add this check inside their Modal and Drawer

**Comment by segunadebayo** [comment]
This is by design. For custom behavior, please use the `useModal` hook to create a custom dialog

**Comment by coolbeatz71** [comment]
Is there a possibility to have an example of use?
