### ISSUE TITLE
TabPanel should not have tabindex=0

### ISSUE THREAD

**Issue by mellis481** [chakra-ui/chakra-ui#7868]
### Description

The tab panel elements (`<div>`s) are focusable because they have a `tabindex="0"`. They shouldn't be, however, as they are not interactive elements.

![image](https://github.com/chakra-ui/chakra-ui/assets/39313898/bd11b3f3-e543-421f-bde2-cae243f48629)

### Link to Reproduction

https://chakra-ui.com/docs/components/tabs#usage

### Steps to reproduce

1. Go to any Chakra Tabs example.
2. Tab through the elements.
3. The tab panel will be focusable even though it (a `<div>`) is not an interactive element.

### Chakra UI Version

1.6.4

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by aboveyunhai** [comment]
@mellis481  it seems like MDN also uses `tabIndex=0` for the active panel
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role#example

**Comment by mellis481** [comment]
@aboveyunhai You linked to MDN's article on tab, not tabpanel.  Here is the article on tabpanels: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tabpanel_role

I skimmed through it and it does seem like MDN is calling out that the tabpanel should be focusable. For what reason, I don't understand.  And I would be inclined to prefer W3C's tabs [example](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-manual/) which does not set `tabindex` on the tabpanel element and since it's a `<div>` (a non-interactive element), it's not focusable.

**Comment by aboveyunhai** [comment]
@mellis481  there is also an W3C document says why you want to make it focusable: https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/#accessibilityfeatures

**Comment by mellis481** [comment]
@aboveyunhai Interesting. Thanks for the link. I'll close this issue.
