### ISSUE TITLE
Theme not applying properly

### ISSUE THREAD

**Issue by useEffects** [chakra-ui/chakra-ui#7873]
### Description

[https://chakra-ui.com/docs/components/menu/theming](https://chakra-ui.com/docs/components/menu/theming)

![image](https://github.com/chakra-ui/chakra-ui/assets/80976002/b6efbd6e-f5f2-4889-89e0-4c6563fbc734)

This is from the official docs about theming chakra-ui menu component, but seems like its not rendering expected results in both your docs as well as in my local environment
![image](https://github.com/chakra-ui/chakra-ui/assets/80976002/684adb60-c3b3-415e-8e14-0de5fdbdfdea)
^ emotion css are overwritten before chakra-ui's css themes, the behavior is same even if the emotion css are prepended in the head tag

### Link to Reproduction

https://codesandbox.io/s/dyh5dj?file=%2FApp.tsx&from-sandpack=true

### Steps to reproduce

try to customize menu by referring the docs

### Chakra UI Version

latest

### Browser

edge

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Please add this style to your menu item theme to fix it

![CleanShot 2024-10-04 at 18 38 26@2x](https://github.com/user-attachments/assets/630d24ee-6f76-4970-81bc-c9c72f2ce16a)
