### ISSUE TITLE
`Hightlight` doesn't highlight a word immediately after a highlighted word

### ISSUE THREAD

**Issue by zhaoruibing** [chakra-ui/chakra-ui#7877]
### Description

Highlight doesn't highlight the word/character following an already highlighted word.
My use case is to highlight languages where the word separator is not a space, like Chinese, Japanese and etc..

**Test Case**

```TypeScript
  <Highlight
    query={["s", "中", "文", "🚘", "🌇"]}
    styles={{ px: "2", py: "1", rounded: "full", bg: "teal.100" }}
  >
    Thissssssssss is an example. Chinese: 这是一句中文。 Emoji:
    🚘🌇
  </Highlight>
```

**What Happened**
It skips the character after a matched character.
![image](https://github.com/chakra-ui/chakra-ui/assets/2396338/84024a45-bfab-4180-8df3-37f7491d0a4f)

**What Excepted**
All characters matching the query shall be highlighted.
![image](https://github.com/chakra-ui/chakra-ui/assets/2396338/3ce1a847-8b4f-4129-900d-018c891ec356)

### Link to Reproduction

https://codesandbox.io/embed/vibrant-rosalind-t3dk3h

### Chakra UI Version

1.6.4

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

FYI, I am not fluent with TypeScript, so don't quote me on this.

I believe [highlightWords() in highlight.tsx](https://github.com/chakra-ui/chakra-ui/blob/f6c3c5b07025e2ddbaaf496ef52be469d865d4f8/packages/components/layout/src/highlight.tsx#L36C10-L36C24) is the cause.
I have luck with this modified highlighWords() (written by ChatGPT)
```TypeScript
function highlightWords({ text, query }: HighlightOptions): Chunk[] {
  const regex = buildRegex(Array.isArray(query) ? query : [query]);
  if (!regex) {
    return [{ text, match: false }];
  }

  const chunks: Chunk[] = [];
  let match: RegExpExecArray | null;

  while ((match = regex.exec(text))) {
    const { index } = match;

    if (index !== regex.lastIndex) {
      chunks.push({ text: text.slice(regex.lastIndex, index), match: false });
    }

    chunks.push({ text: match[0], match: true });
    regex.lastIndex = index + match[0].length;
  }

  if (regex.lastIndex < text.length) {
    chunks.push({ text: text.slice(regex.lastIndex), match: false });
  }

  return chunks;
}
```

**Comment by segunadebayo** [comment]
This is a design flaw in v2. We've improved this in v3.
