### ISSUE TITLE
styles applied twice in next 13

### ISSUE THREAD

**Issue by mohammadizanloo55** [chakra-ui/chakra-ui#7893]
### Description

when I'm using `CacheProvider` from `@chakra-ui/next-js` package styles are applied twice 

I reproduce this bug In this (see the `button` styles) [code sand box](https://codesandbox.io/p/sandbox/vigorous-agnesi-zh97j8?file=%2Fapp%2Fpage.tsx%3A7%2C11)

![Screenshot_2023-07-27_13-20-33](https://github.com/chakra-ui/chakra-ui/assets/54350937/16858204-ed60-437e-a1d7-3dcb82ef21bb)

### Link to Reproduction

https://codesandbox.io/p/sandbox/vigorous-agnesi-zh97j8?file=%2Fapp%2Fpage.tsx%3A7%2C11

### Steps to reproduce

1. Go to the Reproduction website
2. Check Button styles

### Chakra UI Version

2.8.0

### Browser

Google chrome 96.0.4664.110 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by gioxoay** [comment]
Here is my implementation for CacheProvider to resolve this issue, the difference is that adding a logic check server already inserted style will ignore the client.

```"use client";

import { PropsWithChildren, createElement, useMemo, useRef } from "react";
import { CacheProvider as EmotionCacheProvider } from "@emotion/react";
import emotion_createCache, { Options as CacheOptions } from "@emotion/cache";
import { useServerInsertedHTML } from "next/navigation";

type EmotionCacheOptions = Partial<CacheOptions>;

type CacheProviderProps = PropsWithChildren<EmotionCacheOptions>;

const createCache = ((emotion_createCache as any).default ??
  emotion_createCache) as typeof emotion_createCache;

function useEmotionCache(options?: EmotionCacheOptions) {
  const isServerInserted = useRef(false);

  const cache = useMemo(() => {
    const cache = createCache({ key: "css", prepend: true, ...options });
    cache.compat = true;
    return cache;
  }, [options]);

  useServerInsertedHTML(() => {
    if (!isServerInserted.current) {
      isServerInserted.current = true;
      return createElement("style", {
        key: cache.key,
        "data-emotion": `${cache.key} ${Object.keys(cache.inserted).join(" ")}`,
        dangerouslySetInnerHTML: {
          __html: Object.values(cache.inserted).join(" "),
        },
      });
    }
  });

  return cache;
}

export function CacheProvider({
  children,
  ...cacheOptions
}: CacheProviderProps) {
  return (
    <EmotionCacheProvider value={useEmotionCache(cacheOptions)}>
      {children}
    </EmotionCacheProvider>
  );
}
```
