### ISSUE TITLE
Drawer colorScheme doesn't work

### ISSUE THREAD

**Issue by tophermurphy** [chakra-ui/chakra-ui#7895]
### Description

When I add colorScheme = "blue" to the Drawer component it does nothing.

### Link to Reproduction

https://codesandbox.io/s/dreamy-danilo-7zfxc5?file=/src/index.js

### Steps to reproduce

1. Click open.
2. See drawer is at default colorScheme

### Chakra UI Version

2.8.0

### Browser

Firefox, Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is because colorScheme is not implemented in the drawer component. Feel free to extend the theme to support it.
