### ISSUE TITLE
[CSSReset] Consider using CSS Remedy on the long term

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#79]
As the first beta of CSS Remedy [is out](https://github.com/mozdevs/cssremedy/releases/tag/v0.1.0-beta.1), it may be worth giving a try. The rules are compiled by people heavily involved in the CSS specification, and the resulting file is way more concise than [Normalize.css](https://github.com/necolas/normalize.css).

**Comment by tioluwani94** [comment]
Hi @kripod,

Thanks for the suggestion. We'll keep an eye on CSS Remedy and track its progress.
