### ISSUE TITLE
Inline Variants with Chakra Factory is not working.

### ISSUE THREAD

**Issue by ankursehdev** [chakra-ui/chakra-ui#7901]
### Description

Hello Everyone, I am trying to create Inline Variants with Chakra Factory but it's not working.

I looked into this: https://github.com/chakra-ui/chakra-ui/issues/6315 and also https://github.com/chakra-ui/chakra-ui/issues/435 , seems like it's supported but couldn't find a doc here: https://chakra-ui.com/docs/styled-system/chakra-factory

is there anything I am missing here? or is it not supported?
```
const InformationTextContainer: ChakraComponent<'div'> = chakra(Box, {
  baseStyle: () => ({
    display: 'flex',
    border: '3px solid blue',
  }),
  variants: {
    primary: ({ theme }) => ({
      color: 'red'
    }),
    secondary: ({ theme }) => ({
      border: '1px solid black',
      color: 'blue'
    }),
  },
  defaultProps: {
    variant: 'secondary',
  },
});
```
--
<InformationTextContainer variant="secondary"> Text here</InformationTextContainer>
The variant doesn't work! Any pointers on what I am doing wrong?

### Link to Reproduction

https://play.chakra-ui.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwATFwCEBXbbCAOwBpcwALAQwGtMGbCIAPXAX1wDNMEFLgDkAAXrNWAWmJIA9JhgMw2UQB0KWyBQDOeAJIV+WFA2xJKAFRidsAYUrYGSCjEzxcDxiwZP0ShgKbAAeUSgkADdRAD5cAF5aX1YACg5OGmAtXFwAIwY9GABlbABPABsYL1SASkT41OyKXNzIvTQKhjKvUX4qzlEqHNa8rFhPMQBmNG49CAqkKHyK4hghkdy0BihIigBzXoBGAAZZzRbeWuHLqIZMJAYQvS9m1tw0B-NMHtwm3GwdBgKBgVwafze71oCywvWUUAu7x4102uCKuig91+-0BwNByPBTVRuTGmAmx1maIWSxWqiYG0u70gFVhYjyq3WqORN1yPB5uFg-AYxAq2AACkI0C98Ki7g8ntheujKJifgzeTdkQBuLRaOwYHDQ-R4ACCaDQiT+9QS8UhymwxEwLVCxlMmHMlhsdkczlc7kwuDljxCCQ0IE+qCxYdihlwDBEblMAO9uCBylCCldZgsVgotnsThCfo8sS0PBAPCAA

### Steps to reproduce

In the demo you can see that base styles are getting applied but not the variants style.

### Chakra UI Version

2.7.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by andrewzamojc-pd** [comment]
I was trying to do something similar. I wanted to create variants in a custom component file , without adding them to the theme. The technique involves useStyleConfig, but passing a _falsy_ theme key as the first parameter. The second parameter is an object that usually takes `variant`, but can additionally take a `styleConfig`.

Although the technique as a whole is undocumented afaik, and possibly hacky, you can see why it works [in their implementation]( https://github.com/chakra-ui/chakra-ui/blob/f3c4a492e5636d2745b438d10794fa4e7999b6de/packages/core/system/src/use-style-config.ts#L20). 

It does seem to merge things properly and allow "inline" variants that can be applied with `sx` or `_css`. You might be able to do something like:
 
```
// InformationTextContainer.jsx

const inlineStyleConfig = {
  baseStyles: { ... },
  variants:  { primary: ..., secondary: .. },
};

export const InformationTextContainer =  ({ variant, children }) => {
  const styles = useStyleConfig(
    '', // falsy theme key, since not in theme. Null would be nice, but chakra wants a string
    { 
      variant,  // from prop, e.g. 'primary'
      styleConfig: inlineStyleConfig 
    }
  );

  return <Box sx={styles}>{children}</Box>;
```

**Comment by ankursehdev** [comment]
@andrewzamojc-pd  - This worked, you're a life saver, I kept looking at the file but missed that I can pass the `styleConfig` like this. Thank you once again for this.

**Comment by segunadebayo** [comment]
Correct. This is a design flaw in Chakra v2.

Using the suggested approach above works. We've improved this significantly in v3
