### ISSUE TITLE
double spacing after a string in Input, Textarea, Editable components populates a dot

### ISSUE THREAD

**Issue by lokeshwaranc** [chakra-ui/chakra-ui#7904]
### Description

When I type two spaces followed by a string populates a dot in the following chakra components 
1. Input
2. Textarea
3. Editable

### Link to Reproduction

https://codesandbox.io/s/friendly-ioana-pftl8l

### Steps to reproduce

1. Type two spaces followed by a string in any of the field
2. You will get an dot and space

### Chakra UI Version

2.7.2

### Browser

Google Chrome Version 114.0.5735.248 (Official Build) (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I can't reproduce this. The Chakra Input mirrors the native input, so this smells like an extension or something else on your end is causing this.

Definitely not a Chakra bug
