### ISSUE TITLE
Heading as h1 not working for seo

### ISSUE THREAD

**Issue by beurnii** [chakra-ui/chakra-ui#7908]
### Description

I have done a website, and I am trying to optimised my SEO for it. For that, I need to set a H1 and some H2s in my pages. I have done so with using the 'as' in the heading tag. This seems to work alright when I inspect the HTML.

 However, when a run it trough some SEO analysers, none of them report seeing H1 or H2s. I don't really understand why.
Here an example of and heading that I have.

```
    <Heading as={'h1'} letterSpacing={'0.2px'} paddingBottom={'10px'} fontSize={{sm: 'xl', md: '56px'}}>  
        {t("Charting a path to innovation")}  
    </Heading>  
```
the _{t(...)}_ is from i18next for the translation

Is there something I am doing wrong? Could it be that the javascript that sets the H# type runs after the seo analyser?

here some free seo analyser that I used:
https://aioseo.com/seo-analyzer/
https://suite.seotesteronline.com/seo-checker/
https://rankmath.com/tools/seo-analyzer/
https://freetools.seobility.net/en/seocheck

Thanks

### Link to Reproduction

https://codesandbox.io/s/inspiring-mcclintock-ttmmgc

### Chakra UI Version

2.3.7

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by nd-yi** [comment]
it seem be caused by React libary,  replace 'Heading' with native h1 tag will get the same error

**Comment by segunadebayo** [comment]
This is not a bug in Chakra UI.

**Comment by DamriaNeelesh** [comment]
Isn't there any solutions for this till now I am also getting these Issues on SEO analyzers because of Chakra UI

**Comment by rehansi** [comment]
i am facing the same issue even though i used the basic H1 tag but the issue still persists

**Comment by rehansi** [comment]
> This is not a bug in Chakra UI. 

could you please tell me how to resolve this issue
