### ISSUE TITLE
Stepper component returns lint error when adding sx properties 

### ISSUE THREAD

**Issue by bwcr** [chakra-ui/chakra-ui#7911]
### Description

When I add sx to StepNumber and other Step required components, I expected no errors but it returns errors instead
``[{
	"resource": ".../ChannelsAdd.tsx",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type '{ sx: { '&[data-status=\"active\"],&[data-status=\"complete\"]': { color: string; }; '&[data-status=\"incomplete\"]': { color: string; }; }; fontWeight: string; fontSize: string; }' is not assignable to type 'IntrinsicAttributes & Omit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, \"transition\" | ... 2 more ... | \"translate\"> & { ...; } & { ...; }'.\n  Property 'sx' does not exist on type 'IntrinsicAttributes & Omit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, \"transition\" | ... 2 more ... | \"translate\"> & { ...; } & { ...; }'.",
	"source": "ts",
	"startLineNumber": 61,
	"startColumn": 21,
	"endLineNumber": 61,
	"endColumn": 23
}]``

### Link to Reproduction

https://codesandbox.io/s/laughing-fog-8n53mj?file=/src/index.tsx

### Chakra UI Version

2.8.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
