### ISSUE TITLE
Add `alex` for documentation

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#792]
After reading feedback from @aaronmcadam on #789, I think we should consider adding [`alex`](https://alexjs.com/) to our documentation linting/pipeline. This will help us guarantee that the voice of our documentation remains considerate and respectful.

**Comment by aaronmcadam** [comment]
Maybe a good first step would be to install one of the text editor plugins: https://github.com/shinnn/vscode-alex.

**Comment by segunadebayo** [comment]
Let's skip this for now.

At the least, we can add it `alex` to the list of VSCode recommended extensions.

@with-heart If you can help with this, that'll be great

**Comment by with-heart** [comment]
@segunadebayo I couldn't get the vscode extension to work, so let's just skip this completely for now :P

**Comment by aaronmcadam** [comment]
>  I couldn't get the vscode extension to work

I had the same experience. Maybe this would be best run as a pipeline task as originally suggested. 😄
