### ISSUE TITLE
`isEditing` property from `useEditable` is not reactive

### ISSUE THREAD

**Issue by prenaissance** [chakra-ui/chakra-ui#7920]
### Description

When I use
```ts
import { useEditable } from "@chakra-ui/react";
const { isEditing } = useEditable();
```
I expect `isEditing` to switch to true and cause a rerender when the `Editable` component is in editing mode, caused by focus, instead the value is always false. The behaviour with `onEdit` and `getEditButtonProps` is always correct.
With `useEditableContext`, `useEditableState` or `useEditableControls` the issue is not present.

### Link to Reproduction

https://codesandbox.io/s/quirky-paper-zwfdxc?file=/src/index.tsx

### Steps to reproduce

1. Recreate the code scenario described or linked in the sanbox.
2. Click on the preview text
3. Observe how the internal state changes correctly, but it's not relfected on `isEditing` from the `useEdtiable` hook.

### Chakra UI Version

2.8.0

### Browser

Mozilla Firefox  116

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hey! useEditableControls is the correct way to fix this, as you pointed out.

useEditable is a lower-level hook to create your own Editable. You had 2 editable states in your example, one from useEditable and another within the Editable component, That's why it didn't work.
