### ISSUE TITLE
onClick not being triggered in modal and drawer when using Apple Pencil

### ISSUE THREAD

**Issue by danforejtek** [chakra-ui/chakra-ui#7921]
### Description

When I try to "click" button inside modal with apple pencil event is not being triggered.

### Link to Reproduction

https://chakra-ui.com/docs/components/modal#control-focus-when-modal-closes

### Steps to reproduce

Open modal and click any button inside.

### Chakra UI Version

2.8.0

### Browser

Chrome 115.0.5790.160; Safari 16.5

### Operating System

- [x] iOS

### Additional Information

OS: iOS, 
Device: iPad Air 4. gen (A2316) with Apple Pencil 2. gen

**Comment by AEJIJEON** [comment]
the same issue occured to me. did you solve ?

**Comment by danforejtek** [comment]
I am using onPointerUp instead of onClick within the modal.

**Comment by segunadebayo** [comment]
Closing based on https://github.com/chakra-ui/chakra-ui/issues/7921#issuecomment-1831434375

Pointer events are more resourceful when it comes to fine pointers like the Apple Pencil.
