### ISSUE TITLE
FormControl's parts' _disabled styling is not applied, resulting in disparate opacity

### ISSUE THREAD

**Issue by StanLaurent** [chakra-ui/chakra-ui#7922]
### Description

I have defined a custom theme for the parts of the FormControl. Props get styled properly, except the one I defined in _disabled.

This results in a reduced opacity I cannot control, and the HelperText standing out since it has opacity set to 1.

![image](https://github.com/chakra-ui/chakra-ui/assets/109153151/12d2202a-096a-495e-ba9f-9663114b85ce)

### Link to Reproduction

https://codesandbox.io/s/upbeat-elgamal-xdzhm8

### Steps to reproduce

1. Open formControl.tsx in the `theme` folder
2. See how the styling is not applied.

### Chakra UI Version

2.7.1

### Browser

Edge

### Operating System

- [x] Windows

**Comment by nikparo** [comment]
I have opened a PR that will allow state-based styling for FormControl components including `FormHelperText` - https://github.com/chakra-ui/chakra-ui/pull/8102

**Comment by StanLaurent** [comment]
Thanks!
