### ISSUE TITLE
Collapse gets stuck closed sometimes

### ISSUE THREAD

**Issue by david-morris** [chakra-ui/chakra-ui#7935]
### Description

Collapse sometimes doesn't open even when you change its `in` prop to `true`.

### Link to Reproduction

N/A (only reproducible with fast usage of animation)

### Steps to reproduce

1. Add a Collapse to a heavyweight form
2. Write a test which animates clicks

### Chakra UI Version

2.3.4

### Browser

Chrome 115.0.5790.171 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [X] Windows
- [X] Linux

### Additional Information

At first I thought this was restricted to a jest-playwright/storybook test-runner environment.  This actually always stops a certain test (and not on the first time that this collapse is opened).

But then I saw the issue happen in one particular storybook build:
![grafik](https://github.com/chakra-ui/chakra-ui/assets/5530960/2f4e5bf5-f4b8-45cb-92aa-a963600534fd)
That's some VerticalSteps code, and I've confirmed with console logs in jest that Collapse receives `true` as its `in` when that happens.

As for OS, I've checked both Windows and Linux because the testing is going on in WSL and github linux runners, but the browser is Windows (chrome).

Workaround: if I wait to click the button which opens the collapse by 200ms in my test, this doesn't happen.  So I will just wait 500ms to avoid a flaky test.
I don't think our users are able to navigate fast enough to trigger this bug.  But it would be nice to have the test run a little quicker, and it's weird that this is shaky.

**Comment by segunadebayo** [comment]
This is likely a framer-motion related issue. Please upgrade to the latest versions for Chakra and Framer Motion
