### ISSUE TITLE
Input type="search" switches between round and square (borderRadius) on phone

### ISSUE THREAD

**Issue by adrianflatner** [chakra-ui/chakra-ui#7939]
### Description

The search field (input component with type="search") switches between having a high value of borderRadius to having the normal value. This is only when using it on a phone - not when inspecting it on a desktop in phone mode. It is round to begin with and gets square on focus. 

### Link to Reproduction

https://codesandbox.io/s/jolly-parm-tz9t4y?file=/src/index.tsx

### Steps to reproduce

1. Go to [https://codesandbox.io/s/jolly-parm-tz9t4y?file=/src/index.tsx](https://codesandbox.io/s/jolly-parm-tz9t4y?file=/src/index.tsx) on a phone (Iphone in my case).
4. See round search field.
5. Try clicking on it.

### Chakra UI Version

2.5.1

### Browser

Chrome

**Comment by DavideFrancescon** [comment]
Just tested it on android and it works fine, the issue is only present on IOS(tested on safari, chrome and firefox). I'll see if I can find anything!

**Comment by DavideFrancescon** [comment]
![Screenshot 2023-08-23 alle 12 13 15](https://github.com/chakra-ui/chakra-ui/assets/102860588/0b01872c-37c9-4fc9-adf9-12bc799bc8d7)
I found this inconsistence in the css, and i'm 99% sure it's not wanted as in 3 of them is none and in the other is textarea. Anyway this is what's causing the issue, I'll fix it and let's see if they accept it.

**Comment by segunadebayo** [comment]
Please pass appearance="none" to the input component to resolve this.
