### ISSUE TITLE
Chakra UI NextJS13 hydration issue

### ISSUE THREAD

**Issue by suenalaba** [chakra-ui/chakra-ui#7941]
### Description

I keep getting the following error message:
```
Error: Hydration failed because the initial UI does not match what was rendered on the server.

Warning: Did not expect server HTML to contain a <a> in <div>.
```

I currently have the following code snippet:
```
return (
    <Flex bg='tomato' p={4} ml={'auto'}>
      <Box ml={'auto'}>{body}</Box>
    </Flex>
);
```
where,
```
body = (
      <>
        <Link as={NextLink} href='/login' mr={2}>
          login
        </Link>
        <Link as={NextLink} href='/register' mr={2}>
          register
        </Link>
      </>
);
```

I am currently following the latest ChakraUI docs on this page: https://chakra-ui.com/docs/components/link

![Screenshot 2023-08-13 at 5 43 43 PM](https://github.com/chakra-ui/chakra-ui/assets/61338348/1e09a733-23cd-48fa-aa6d-586068f80c31)

where they mentioned about the hydration issue. However, following their example still doesn't solve the problem.

Inspecting my page source I do indeed see an <a> tag in <div> as: 
```
<a class="chakra-link css-1to8xmn" href="[/login](http://localhost:3000/login)">login</a>
```

Is there a workaround this?

### Link to Reproduction

https

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.2.1

### Browser

Google Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by laakal** [comment]
Can you try Link component compatible with Nextjs?
```js
// app/page.tsx
'use client'
import { Link } from '@chakra-ui/next-js'

export default function Page() {
  return (
    <Link href='/about' color='blue.400' _hover={{ color: 'blue.500' }}>
      About
    </Link>
  )
}
```

**Comment by suenalaba** [comment]
This doesn't work

**Comment by mandorakannu** [comment]
I am also facing this issue. My code:
```
import {
  Drawer,
  DrawerBody,
  DrawerFooter,
  DrawerHeader,
  DrawerOverlay,
  DrawerContent,
  DrawerCloseButton,
} from "@chakra-ui/react";
import Link from "next/link";
import { useRef, Fragment } from "react";
import links from "@jsons/navbar-links.json";
import SocialIcons from "@ui/Social-Icons";

interface Props {
  isOpen: boolean;
  onOpen: () => void;
}

export function DrawerNavigation({ isOpen, onOpen }: Props) {
  const btnRef = useRef<HTMLButtonElement>(null);
  const onClose = () => onOpen();

  return (
    <>
      <Drawer
        isOpen={isOpen}
        placement="right"
        onClose={onClose}
        finalFocusRef={btnRef}
      >
        <DrawerOverlay />
        <DrawerContent className="bg-secondary-200 text-white">
          <DrawerCloseButton className="focus:border-none" />
          <DrawerHeader className="text-lg">
            Threads | Kannu Mandora
          </DrawerHeader>

          <DrawerBody>
            <ul className="list-none">
              {links.map(({ name, link }, index) => (
                <Fragment key={index}>
                  <li className="my-6">
                    <Link
                      href={link}
                      className="hover:text-primary-500 active:text-primary-500 transition-colors duration-100 ease-linear"
                    >
                      {name.toUpperCase()}
                    </Link>
                  </li>
                  <hr />
                </Fragment>
              ))}
            </ul>
          </DrawerBody>

          <DrawerFooter>
            <SocialIcons />
          </DrawerFooter>
        </DrawerContent>
      </Drawer>
    </>
  );
}
```

**Comment by danbeaumont95** [comment]
Also getting same issue with using Chakra UI and next 14.0.2,

 Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

Warning: Did not expect server HTML to contain a <div> in <div>.

See more info here: https://nextjs.org/docs/messages/react-hydration-error

Component Stack
div
eval
./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js (60:66)
ChakraComponent
./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs (51:102)
InputGroup2
./node_modules/@chakra-ui/input/dist/chunk-FKYN3ZGE.mjs (32:90)
div
eval
./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js (60:66)
ChakraComponent
./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs (51:102)
FormControl2
./node_modules/@chakra-ui/form-control/dist/chunk-DFWC5MHP.mjs (146:90)
div
eval
./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js (60:66)
ChakraComponent
./node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs (51:102)
eval
./node_modules/@chakra-ui/layout/dist/chunk-ZHMYA64R.mjs (25:5)

**Comment by danbeaumont95** [comment]
So it turns out you need to put your <Providers> in app/layout.tsx 
I stupidly originally had mine in page.tsx
See: https://github.com/chakra-ui/chakra-ui/issues/7578#issuecomment-1510655264
import '@/app/ui/global.css';
import { Providers } from './providers';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Providers>{children}</Providers>
    </html>
  )
}

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Please provide a reproduction

**Comment by takumade** [comment]
Let admit it

The Chakra UI and Next JS 13/14 combination sucks

**Comment by mandorakannu** [comment]
> Let admit it
> 
> The Chakra UI and Next JS 13/14 combination sucks

100% Agree!

**Comment by danmichaelo** [comment]
`suppressHydrationWarning` is used in the official Chakra UI NextJS example, does that mean that Chakra UI cannot really be used without it at the moment? 🤔 

https://github.com/chakra-ui/chakra-ui/blob/main/sandbox/next-app/app/layout.tsx#L15C39-L15C63

**Comment by mandorakannu** [comment]
Yes, you're right; however, using ChakraUI with Next.js is kind of sucky. We can suppress the warning, but as developers, we need to completely remove these errors.

**Comment by oxedom** [comment]
Any solution?

**Comment by FunctionDJ** [comment]
If a library causes these warnings and it's documentation instructs to suppress these warnings the library should probably be considered incompatible with Next 15. Plain and simple.

These hydration warnings are important and suppressing them is probably even worse than just instructing users to just ignore them.
I have found many issues with SSR in my code before thanks to these warnings and could fix them - be it misplaced browser-only code or using components that are simply incompatible with SSR and must be client rendered only with `next/dynamic`.

Disabling these warnings is not a valid option in my opinion and i'll unfortunately have to look for another component library. I really hope chakra-ui can sort this out, i've subscribed to all related issues.

**Comment by nappalm** [comment]
> If a library causes these warnings and it's documentation instructs to suppress these warnings the library should probably be considered incompatible with Next 15. Plain and simple.
> 
> These hydration warnings are important and suppressing them is probably even worse than just instructing users to just ignore them. I have found many issues with SSR in my code before thanks to these warnings and could fix them - be it misplaced browser-only code or using components that are simply incompatible with SSR and must be client rendered only with `next/dynamic`.
> 
> Disabling these warnings is not a valid option in my opinion and i'll unfortunately have to look for another component library. I really hope chakra-ui can sort this out, i've subscribed to all related issues.

I completely agree, although chakra-ui is pretty good, it is difficult for them not to provide good support for next updates.

**Comment by jaalzu** [comment]
2026 and still happen.. CHAKRA AND NEXTJS ARE BAD!
