### ISSUE TITLE
Tooltip placement responsive not works

### ISSUE THREAD

**Issue by fiorins** [chakra-ui/chakra-ui#7943]
### Description

Hi, I'm implementing tooltip on my component but the placement property doesn't work with responsive values and throws the error:
`Type '{ base: string; md: string; }' is not assignable to type 'PlacementWithLogical | undefined'.`

```js
<Tooltip
    hasArrow
    label='my label'
    bg='my color'
    color={{ base: "#fff", md: "#000" }}
    placement={{ base: "bottom", md: "left" }}
>
    <...>
</Tooltip>
```

I didn't find anything can help into tooltip documentation

### Link to Reproduction

It doesn't need

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.8.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @fiorins,

The tooltip placement was not designed to support responsive values.

Please use useBreakpointValue hook instead
