### ISSUE TITLE
Popover Component with Parcel.js (Cannot read properties of undefined (reading 'transformOrigin'))

### ISSUE THREAD

**Issue by index01d** [chakra-ui/chakra-ui#7948]
### Description

When attempting to use the Popover component from Chakra UI in a project built with Parcel.js, an error is thrown during rendering. The error message indicates a "TypeError: Cannot read properties of undefined (reading 'transformOrigin')" and points to the use-popover.ts file.

<img width="812" alt="async-star-8tvpvh - CodeSandbox 2023-08-14 17-22-22" src="https://github.com/chakra-ui/chakra-ui/assets/236657/09c961df-d382-49d5-9a1d-1294f13a3833">

### Link to Reproduction

https://codesandbox.io/p/sandbox/async-star-8tvpvh?file=/src/MyComponent.js:18,7

### Chakra UI Version

2.8.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Can't reproduce this. I get this error 

```
Uncaught TypeError: window.initializeReviews is not a function
```

Please upgrade to the latest version
