### ISSUE TITLE
Responsive Header with Chakra UI - Recipes - Documentation

### ISSUE THREAD

**Issue by tonilaukka** [chakra-ui/chakra-ui#795]
**Describe the bug**
Responsive Header Example breaks on browser widths below sm breakpoint.

**Expected Behavior**
I would expect the navi to work on all widths since it's responsive

**To Reproduce**
- Use this template: https://codesandbox.io/s/chakra-ui-react-hook-form-rvi3p
- List the steps to reproduce the behavior:
1. Open Developer tools
2. Toggle Device Toolbar
3. Select iPhone 5/SE

**Suggested solution(s)**
Change sm breakpoint to base: https://codesandbox.io/s/chakra-ui-header-00pnl
Depending on your layout moving mobile menu to headers sibling might work better: https://codesandbox.io/s/chakra-ui-header-lr09f

**Comment by with-heart** [comment]
Hi @tonilaukka, I can confirm this as an issue. However, we're focusing all efforts on the 1.0 pre-release and this issue does not exist on that site (https://next.chakra-ui.com). Thanks for reporting but I'm going to close this as no longer relevant!

**Comment by jeanbauer** [comment]
@tonilaukka I just updated the sandbox for that recipe (old/current website) with your suggestion. Thanks.
