### ISSUE TITLE
useRangeSlider ts error Expected 1 arguments, but got 4 (fix provided)

### ISSUE THREAD

**Issue by hooch** [chakra-ui/chakra-ui#7955]
### Description

When using the `useRangeSlider` hook according to the [example provided in the docs](https://chakra-ui.com/docs/hooks/use-range-slider) I kept getting `Expected 1 arguments, but got 4. ts(2554)`:

`const rangeSlider = useRangeSlider(min, max, defaultValue, rest )`

This also occurs in the [provided CodeSandbox](https://codesandbox.io/s/0s4pvu?file=%2FApp.tsx&from-sandpack=true):

![Screenshot 2023-08-21 at 08 59 10](https://github.com/chakra-ui/chakra-ui/assets/987814/ce3e5e33-1d75-4d64-bd25-0a2283f9f126)

After comparing with the [Slider component](https://chakra-ui.com/docs/components/slider/usage) docs, I got things working with the following changes to the CodeSandbox:

index.tsx
```
   <App
        min={0} <-- was set to 25
        max={100} <-- was set to 75
```

App.tsx:
```
        <Actions
          actions={actions}
          min={defaultValue[0]} <-- was using the min prop value
          max={defaultValue[1]} <-- was using the max prop value
```

With the above corrections, the typescript errors can be solved and useRangeSlider hook example can be made to work correctly:

Before:

`useRangeSlider(min, max, defaultValue, rest)`

After:

`useRangeSlider({ min, max, defaultValue, ...rest })`

### Link to Reproduction

https://codesandbox.io/s/0s4pvu?file=%2FApp.tsx&from-sandpack=true

### Chakra UI Version

2.8.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by DavideFrancescon** [comment]
I'll fix the docs!

**Comment by segunadebayo** [comment]
Fixed in the docs

**Comment by DavideFrancescon** [comment]
@segunadebayo all that's missing now is the table of props at the bottom of the page but I noticed it's still a wip, right?

**Comment by hooch** [comment]
The codesandbox sample seems only to have had one of the abovementioned fixes applied.  Left comments on the MR

**Comment by hooch** [comment]
The reset button in Actions should be resetting to the defaultValues prop, but it resets to [min, max].
The problem is not obvious when min and max are set to 25, 75.
There's also the `rest` parameter which needs to be specified as `...rest`
And this is just the start of the typescript compiler problems..

**Comment by DavideFrancescon** [comment]
Oh i didn't notice the ...rest thing, you are right, it compiled and executed so I missed it, my bad, i'll fix that asap. 

And for the other thing, I understood now what the problem was, I thought it was just a miss-match with the range and not within the code.  
Thanks for the clarifications, i'll be sure to fix all of that!

**Comment by DavideFrancescon** [comment]
@hooch  It's longer then i thought it would be, could you please open an issue on the docs repo in the mean time. I need to fix pretty much every file and the typing they are using.
