### ISSUE TITLE
Image componet does not show fallback image when loading prop is set to "lazy"

### ISSUE THREAD

**Issue by Fawad-invoo** [chakra-ui/chakra-ui#7956]
### Description

**When I** use loading prop with value "lazy" in image along with fallbackSrc, **I expect** the fallback image provided via fallbackSrc to load when that CharkaUI image component is in viewport or near to viewport, it also start downloading the main image provided via src prop. Once the main image download it should replace the fallback image.

But with loading prop with value "lazy", fallbackSrc does not load at all and main image loads directly which takes time.

[Codesandbox example](https://codesandbox.io/p/sandbox/eager-shamir-w5ry4x?file=/src/App.tsx:12,18-12,23)

### Link to Reproduction

https://codesandbox.io/p/sandbox/eager-shamir-w5ry4x?file=/src/App.tsx:12,18-12,23

### Steps to reproduce

1. Open this [link](https://codesandbox.io/p/sandbox/eager-shamir-w5ry4x?file=/src/App.tsx:12,18-12,23)
2. Run the example with src and fallbackSrc while loading prop should be commented out
3. Using browser dev tool, under network tab disable the cache and  also apply slow 3G.
4. Now observe,  the fallback image appears and main src image replaces it after it get downloaded. This is the expected behaviour
5. Now just add loading prop with value "lazy" and refresh the page. 

### Chakra UI Version

2.8.0

### Browser

Google chrome 15

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by DavideFrancescon** [comment]
I'd like to try fixing this! I could replicate this easily, just hoping the fix is as easy as that

**Comment by DavideFrancescon** [comment]
@Fawad-invoo i found [this](https://github.com/chakra-ui/chakra-ui/pull/1012), so I think it's wanted to have it working like that.

@segunadebayo do we leave it like that or not, cause it's true that it's bugged, but maybe if a lazy image needs to show a loading screen the problem is not coming from the library but from how the web site is built. 

If you have an image in the first page rendered you could consider removing the lazy loading

**Comment by Fawad-invoo** [comment]
I did not get what is the point of bypassing the fallbackSrc and its even confusing with no mention of this behaviour on documentation.
The main point of lazy loading it to improve UX. If user still have to see blank space while image is being loading then what is the point of image component then? why not just use native html image tag instead of Chakra UI component 

For example, Image component of NextJS shows fallback image or blurred version while original image is being downloaded. That is expected behaviour and that is what makes UX better

**Comment by cranium** [comment]
I'm disappointed by the behavior here as well- it would be nice if a Skeleton could fill the space while its loading, seeing as Skeletons seem to be the standard way of indicating loading in Chakra.

**Comment by phoneticallySAARTHaK** [comment]
I am getting this behavior with `loading="eager"` as well

**Comment by xobotyi** [comment]
Same here - setting `loading` prop breaks the fallback behaviour

**Comment by EXPITC** [comment]
just like @xobotyi said, approved +1

**Comment by iamheinrich** [comment]
I'm having the same problem. If loading="lazy' and fallback = some skeleton, the component does not render the fallback skeleton at all. Works as expected with disabled loading props.

**Comment by iamheinrich** [comment]
> I'm disappointed by the behavior generally here- it would be nice if a Skeleton could fill the space while its loading, seeing as Skeletons seem to be the standard way of indicating loading in Chakra. The fallbackSrc is another thing that has to be loaded anyway...
> 
>  asdf.mov 
> Here is my workaround:
> 
> ```js
> import { Image, Skeleton } from "@chakra-ui/react";
> import { ComponentProps, useCallback, useMemo, useState } from "react";
> 
> const LazyImage = (props: ComponentProps<typeof Image>) => {
>   const [inView, setInView] = useState<boolean>(false);
>   const [isLoading, setIsLoading] = useState<boolean>(true);
> 
>   const callback = useCallback<IntersectionObserverCallback>(
>     (entries, observer) => {
>       entries.forEach((entry) => {
>         if (entry.isIntersecting) {
>           setInView(true);
>           observer.disconnect();
>         }
>       });
>     },
>     []
>   );
> 
>   const observer = useMemo(
>     () => new IntersectionObserver(callback),
>     [callback]
>   );
> 
>   const skeletonRef = (el: HTMLDivElement) => {
>     if (el) observer.observe(el);
>   };
>   const imageRef = (el: HTMLImageElement) => {
>     if (el) el.addEventListener("load", () => setIsLoading(false));
>   };
> 
>   const imageProps = useMemo(() => {
>     if (isLoading) {
>       return {
>         ...props,
>         display: "none",
>       };
>     }
> 
>     return props;
>   }, [isLoading, props]);
> 
>   return (
>     <>
>       {(!inView || isLoading) && <Skeleton ref={skeletonRef} {...props} />}
>       {inView && <Image ref={imageRef} {...imageProps} />}
>     </>
>   );
> };
> 
> export default LazyImage;
> ```
> 
>  Screen.Recording.2023-09-14.at.6.33.29.PM.mov

Very helpful! Using it, thanks @cranium

**Comment by segunadebayo** [comment]
Closing based on https://github.com/chakra-ui/chakra-ui/issues/7956#issuecomment-1720315375 and https://github.com/chakra-ui/chakra-ui/issues/7956#issuecomment-1868349054

**Comment by DucNg** [comment]
> Closing based on [#7956 (comment)](https://github.com/chakra-ui/chakra-ui/issues/7956#issuecomment-1720315375) and [#7956 (comment)](https://github.com/chakra-ui/chakra-ui/issues/7956#issuecomment-1868349054)


Can you please reopen this issue? It isn't fix as of today. We still cannot use the "fallbackSrc" whenever "loading" is set to "lazy". Having a workaround doesn't mean this isn't a bug.
