### ISSUE TITLE
Wrap component with direction=column does not wrap

### ISSUE THREAD

**Issue by MartinP-C** [chakra-ui/chakra-ui#7957]
### Description

Using a `<Wrap>` with `direction="column"`, I expect the items to wrap when inside a container smaller than the whole list.  

It appears the `div.chakra-wrap` is taking the parent height but the `ul.chakra-wrap__list` overflows instead of taking the parent height so doesn't trigger flex wrapping

### Link to Reproduction

https://codesandbox.io/s/mystifying-glade-kd9hnw?file=/src/index.tsx

### Steps to reproduce

1. View sandbox
2. items do not wrap despite being in fixed height container

### Chakra UI Version

2.8.0

### Browser

Google Chrome 115.0.5790.173

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @MartinP-C,

Here's a working solution:
https://codesandbox.io/s/laughing-beaver-29pf3j?file=/src/index.tsx:323-626

```jsx
<Wrap
        direction="column"
        height="100%"
        position="relative"
        sx={{ ul: { height: "100%" } }}
      >
        {new Array(8).fill(0).map((_, i) => (
          <Box height="60px" width="60px" border="1px solid black">
            {i}
          </Box>
        ))}
      </Wrap>
```

In the future versions, we'll consider add these interally
