### ISSUE TITLE
React router NavLink exact property does not work

### ISSUE THREAD

**Issue by tumdav** [chakra-ui/chakra-ui#796]
When true, the active class/style will only be applied if the location is matched exactly.

```js
<NavLink exact to="/users">
  Users
</NavLink>
```
Expectation: It should remove the active class when a user navigates /users/:id
Actual result: It removes active class

## Chakra-ui implementation
```js
<Link
 as={NavLink}
 to="/users"
 exact
>
 Users
</Link>
```

Expectation: It should remove the active class when a user navigates /users/:id
Actual result: It doesn't remove active class

**Comment by with-heart** [comment]
Hi @tumdav, could you please reproduce this in CodeSandbox? That will make it much easier for us to investigate.

**Comment by jdinicola** [comment]
Hi, I'm having the same problem so I created the CodeSandbox... Hope this helps:

[https://codesandbox.io/s/magical-cloud-vym96](https://codesandbox.io/s/magical-cloud-vym96)

**Comment by with-heart** [comment]
This is an issue with polymorphic `as` being incomplete in earlier Chakra versions. This prop now works as expected in 1.0, which is currently in pre-release status: https://codesandbox.io/s/elegant-frost-37n8n?file=/src/App.js

**Comment by aitsamahad** [comment]
Is there any solution for this problem?
i am facing the same issue
My NavLink is like
`<NavLink
          className="iconContainer"
          exact
          to="/"
          activeClassName="isActive"
        >`
But the class isActive is always being shown on the root path, if we navigate to other paths it is working there fine, but only on root path it is stuck as active.

Using react project created with "create-react-app" btw.

**Comment by ljosberinn** [comment]
@aitsamahad hi, how is this related to Chakra?

**Comment by aitsamahad** [comment]
@ljosberinn oh, sorry. I was just searching for this issue, read this discussion and saw that it isn't solved so i just posted my problem here too.
Didn't saw that it is actually an official chakra-ui repo, my bad!
