### ISSUE TITLE
Allow image preload with `preload` prop in Image component

### ISSUE THREAD

**Issue by fzn0x** [chakra-ui/chakra-ui#7966]
### Description

Ideally we would allow users to preload images

### Problem Statement/Justification

Can't figure out how to preload images in Image component _easily_

### Proposed Solution or API

 a `preload` prop would suffice with:

```js
React.useLayoutEffect(() => {
  if (props.preload && props.src) {
    const image = new Image()
    image.src = props.src
  }
}, [props.preload, props.src])
```

**Comment by Sudarsh1010** [comment]
I'll work on it!

**Comment by Sudarsh1010** [comment]
I think It's already getting preloaded.

image.tsx:
`  const status = useImage({
    ...props,
    crossOrigin,
    ignoreFallback: shouldIgnoreFallbackImage,
  })

  const showFallbackImage = shouldShowFallbackImage(status, fallbackStrategy)`
  
use-image.ts(line 83):
`const load = useCallback(() => {
    if (!src) return

    flush()

    const img = new Image()
    img.src = src
    if (crossOrigin) img.crossOrigin = crossOrigin
    if (srcSet) img.srcset = srcSet
    if (sizes) img.sizes = sizes
    if (loading) img.loading = loading

    img.onload = (event) => {
      flush()
      setStatus("loaded")
      onLoad?.(event as unknown as ImageEvent)
    }
    img.onerror = (error) => {
      flush()
      setStatus("failed")
      onError?.(error as any)
    }

    imageRef.current = img
  }, [src, crossOrigin, srcSet, sizes, onLoad, onError, loading])

  const flush = () => {
    if (imageRef.current) {
      imageRef.current.onload = null
      imageRef.current.onerror = null
      imageRef.current = null
    }
  }`

I'm new to this contribution side. If I am wrong, let me know. Thank You!

**Comment by segunadebayo** [comment]
Indeed, the image is already preloaded. Please use the `Img` component if you need to use the native image element.
