### ISSUE TITLE
Input `onChange` doesn't work correctly when using with dynamic `defaultValue`

### ISSUE THREAD

**Issue by namdien177** [chakra-ui/chakra-ui#7968]
### Description

Using dynamic value on the `defaultValue` property on `<Input />` causes the initial `onChange` action (right after the input completes its render default value) not to emit.

~~While the `defaultValue` is being changed, the `onChange` event does fire (which I'm not sure is the correct behavior or not)~~ Tested again, and it doesn't fire the `onChange` when changing `defaultValue`.
Using the `value` instead of `defaultValue` will have the `onChange` event behave as "expected" for me, but it doesn't feel right...

Although I'm using formik library to demonstrate real scenario implementation, testing with delayed `setState` also result the same behavior (in the reproduction).

From the second time edit and forward, it will be OK.

### Link to Reproduction

https://stackblitz.com/edit/stackblitz-starters-cbxm89?file=src%2Finput-by-context.tsx

### Steps to reproduce

1. Open `Console` (to observe debug log)
2. Click on the input component on the screen
3. `Ctrl` + `A` (`cmd` + `A`) and delete all text in input
4. Click outside the input (to blur the input). The debug log should emit the blur state correctly, but the value will not change.
5. Click submit, the value should be the same as the old value
6. If edit the text again, the value will be updated correctly.

### Chakra UI Version

2.8.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I haven't tested it on Windows yet.

**Comment by Philzen** [comment]
I believe this is not a bug – though it can be a pitfall (which i've been in before). Maybe the documentation could be clearer in this regards. 

As far as i understand it today, a `defaultValue` is not much more than a fallback, or better: initial value to set on ever-first display to the user, while the user selection has never been made before, hence the variable bound to that selection still being undefined or null. If you want the control to reflect the last user selection after bind `value` against it, not `defaultValue` b/c the latter will be flaky (b/c sometimes the control is rendered before the variable is restored to your last state, sometimes not), referring to the pitfall mentioned above.

The `defaultValue` is parsed once, and determines the initial state of the control, whatever changes come after that are ignored. In that sense it's absolutely consistent that it won't raise an `onChange`-event (as it never changes).

**Comment by namdien177** [comment]
> I believe this is not a bug – though it can be a pitfall (which i've been in before). Maybe the documentation could be clearer in this regards.
> 
> As far as i understand it today, a `defaultValue` is not much more than a fallback, or better: initial value to set on ever-first display to the user, while the user selection has never been made before, hence the variable bound to that selection still being undefined or null. If you want the control to reflect the last user selection then bind `value` against the variable holding that information, not `defaultValue` b/c the latter will be flaky (b/c sometimes the control is rendered before the variable is restored to your last state, sometimes not), referring to the pitfall mentioned above.
> 
> The `defaultValue` is parsed once, and determines the initial state of the control, whatever changes come after that are ignored. In that sense it's absolutely consistent that it won't raise an `onChange`-event (as it never changes).

Yeah, it seems to be so. The behavior of `defaultValue` in this case makes me feel a little bit confused and mistake it to be a bug. I also did the test on the native input tag and it does the same thing. Close as it's the correct behavior.
