### ISSUE TITLE
[Bug] useEditableControls callbacks return `disabled` instead of `isDisabled`

### ISSUE THREAD

**Issue by david-morris** [chakra-ui/chakra-ui#7971]
### Description

While the type of useEditableState indicates it should have `isDisabled` rather than `disabled`, console logs indicate that `disabled` is still returned.

Since that's no longer compatible with `<Button>` and friends, that's a bug.

The `<Editable>` can still be disabled with `isDisabled`, but it doesn't pass that info down to any `<Button>` using getSubmitButtonProps, getCancelButtonProps, or getEditButtonProps of useEditableControls().

So the editable looks broken (doesn't do anything except react visually when clicked) instead of disabled (doesn't do anything including react visually on click, is grayed-out, uses not-allowed cursor).

### Link to Reproduction

https://codesandbox.io/s/kind-cdn-hgyykp?file=/src/index.tsx

### Steps to reproduce

1. Use the `Editable` component
2. Set up custom controls
3. set `isDisabled={true}` on the Editable

### Chakra UI Version

2.8.0

### Browser

Chrome and Firefox

### Operating System

- [ ] macOS
- [X] Windows
- [X] Linux

### Additional Information

Here's my workaround:
```tsx
const patchDisabled = <T extends object>(dirty: T) => {
  const { disabled, ...rest } = dirty as T & { disabled: boolean }
  if ("disabled" in dirty === false)
    throw new Error("Upstream fixed isDisabled bug")
  return {
    isDisabled: disabled,
    ...rest,
  }
}
```

**Comment by segunadebayo** [comment]
Button now supports disabled so it should work now. Please upgrade to the latest.
