### ISSUE TITLE
Chakra UI for Next JS 13

### ISSUE THREAD

**Issue by brunofsilveira** [chakra-ui/chakra-ui#7973]
### Description

Hello, I currently use and have a lot of productivity with ChakraUI, so I would like to know if the library will receive support for version 13 of NextJS, with SSC.

I am sorry if the communication channel for questions is not this one.

### Problem Statement/Justification

Doubt

### Proposed Solution or API

-

**Comment by muco-rolle** [comment]
Check this one out https://www.adebayosegun.com/blog/chakra-panda-ark-whats-the-plan

**Comment by brunofsilveira** [comment]
Thank you!
