### ISSUE TITLE
Focussing an element within Popover via `initialFocusRef` is broken

### ISSUE THREAD

**Issue by Philzen** [chakra-ui/chakra-ui#7976]
### Description

Just clicked through the Popover examples and noticed https://chakra-ui.com/docs/components/popover#focus-an-element-when-popover-opens seems to be broken.

On V1 it still works: https://v1.chakra-ui.com/docs/components/overlay/popover#focus-an-element-when-popover-opens – the focus is trapped on the button referenced via `ref={initialFocusRef}` when the popover opens.

### Link to Reproduction

https://v2.chakra-ui.com/docs/components/popover#focus-an-element-when-popover-opens

### Steps to reproduce

1. Go to the example
2. Click on 'Trigger' → no focus visible within popover content
3. Hit TAB multiple times
4. you can tell that the focus is on the page (the code example) itself instead of within the popover

### Chakra UI Version

2.8.0

### Browsers

- Firefox 116.0.2 – 127.0 
- Chromium 126.0.6478.61

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by Sudarsh1010** [comment]
It is working on mac. I tested it right now. I cannot reproduce the issue. can you explain more about it

**Comment by janvi01** [comment]
Hey, I am able to reproduce this issue and would like to work on this. @Philzen

**Comment by realing29** [comment]
The same problem, the focus does not work if you pass <input transition="all .3s"/>, but if you pass <input transition="border-color .3s"/> then the focus is working.
Example - https://codesandbox.io/p/sandbox/great-lena-5k68f8
I tried it in edge, firefox, chrome.

**Comment by hernanif1** [comment]
@realing29 It is not clear to me, is it intentional that you removed FocusLock from your example?
Or is it something they improved later on the docs?

**Comment by Philzen** [comment]
@Sudarsh1010 See the linked examples for "Focus an element when Popover opens" in the docs.

v1 works as expected, the focus is placed on the „Next“-Button, and also re-captured whenever you click anywhere else in the page:

![grafik](https://github.com/chakra-ui/chakra-ui/assets/1634615/3b110a77-aebb-4269-ae53-3be57f8817e3)

v2:

![grafik](https://github.com/chakra-ui/chakra-ui/assets/1634615/27470fe2-37ef-4e5f-8550-3686c9cde93f)

No focus on the „Next”-Button and you can also freely place it anywhere else on the page, incl. selecting text.

**Comment by hernanif1** [comment]
The only workaround that I found so far was adding the controlled state via useDisclosure in the trigger button and using the hook useOutsideClick to call the onClose :/

**Comment by Philzen** [comment]
@segunadebayo i may be wrong, but it looks like `initialFocusEl` is also broken in the v3 series: https://next.chakra-ui.com/docs/components/popover#initial-focus

**Comment by segunadebayo** [comment]
@Philzen It's not broken in v3. We only use focus-visible so you can't see the focus but if you press the tab key or open with keyboard, you should see that it works correctly.

**Comment by segunadebayo** [comment]
From my investigation, The focus is actually on the element, but it's not visible.

This is because we switched the styling from focus to focus-visible. Press the tab key or open it with the keyboard to see the focus indicator.
