### ISSUE TITLE
[Stack] Component throws error when direction prop is an array

### ISSUE THREAD

**Issue by ghoshnirmalya** [chakra-ui/chakra-ui#798]
**Describe the bug**
When an array is passed to the `direction` prop of Stack component, it throws `TypeError
direction.endsWith is not a function`. See the image below:

<img width="671" alt="Screenshot 2020-06-03 at 3 12 27 PM" src="https://user-images.githubusercontent.com/6391763/83621723-ad611480-a5ac-11ea-8610-50fd26badc52.png">

This is because of [this line](https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/Stack/index.js#L25) in the Stack component. Also, TS doesn't throw an error on VSCode. See the image below:

<img width="343" alt="Screenshot 2020-06-03 at 3 13 44 PM" src="https://user-images.githubusercontent.com/6391763/83621868-e39e9400-a5ac-11ea-810e-bc4c3720df32.png">

**Expected Behavior**
TS should throw an error that only string is accepted. Also, no error should be shown on the browser because of this.

**To Reproduce**
Add a Stack component and pass an array to the `direction` prop. [Link to the issue in CodeSandbox](https://codesandbox.io/s/chakra-ui-issue-with-stack-ws2oj?file=/src/index.js).

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome
 - Version: 81.0.4044.138

**Comment by mplis** [comment]
Looks like a duplicate of #758

**Comment by ghoshnirmalya** [comment]
@mplis Yes. It's a duplicate. I'll close this issue.

**Comment by Ndifreke** [comment]
Any update on this? I was going to raise this issue again seeing that it is still persistent.

**Comment by with-heart** [comment]
@Ndifreke This has been fixed in 1.0. Hoping to have an alpha/beta released soon.

**Comment by openarun** [comment]
Got this error just now  :P 
How do I fix it? I am on "@chakra-ui/core": "^0.8.0",
