### ISSUE TITLE
Number field looses the zero when using it for a phone number field !!

### ISSUE THREAD

**Issue by bonface221** [chakra-ui/chakra-ui#7988]
### Description

when I create a form field with a number input I expect the number to stay as it is and not loose the zero.

![image](https://github.com/chakra-ui/chakra-ui/assets/98006412/f10bd05a-379e-4c82-b02d-9146dde58514)

### Link to Reproduction

https://chakra-ui.com/docs/components/number-input#usage/

### Steps to reproduce

1. Go to [chakra ui](https://chakra-ui.com/docs/components/number-input#usage/)
2. Click on the  number input and add a number prefixed with zero
3. See error

### Chakra UI Version

2.7.1

### Browser

Google Chrome

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by DavidHughes** [comment]
The number field is designed for numeric inputs which want to have an easy way to increment/decrement, and I would expect isn't designed for input like telephone numbers or reference numbers.

You'll likely get what you need by using the [Input](https://chakra-ui.com/docs/components/input/usage#password-input-example) component with the [`type="tel"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel) input HTML attribute

**Comment by bonface221** [comment]
Thanks
