### ISSUE TITLE
noOfLines with padding

### ISSUE THREAD

**Issue by moiri-gamboni** [chakra-ui/chakra-ui#7989]
### Description

Using `noOfLines` on a component with bottom padding adds the ellipsis at the right place but doesn't crop the text after the ellipsis. With sufficient padding the whole text or part of the next line will be visible. Even when the text is not visible, it can still be selected by starting the selection from the first line. Tested on `Text` and `Heading`.

Replacing padding with a margin fixes the visibility issue but not the text selection.

### Link to Reproduction

https://codesandbox.io/s/cranky-napier-4l87r7

### Steps to reproduce

1. Create a `Text` or `Heading` component with `noOfLines` set low enough to truncate the text, and `pb` set larger than the gap between lines (by default 1.5 is already enough to see part of the following line).
2. Text that should be truncated is visible.

### Chakra UI Version

2.8.0

### Browser

Firefox 108.0, Chrome 116.0.5845.140

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
This isn't a Chakra UI bug. I recommend adding the padding to a container element instead so that the text only handles the textual content.
