### ISSUE TITLE
Select element :focus style is missing

### ISSUE THREAD

**Issue by antpaw** [chakra-ui/chakra-ui#7990]
### Description

When I click on a label assigned to a Select element, I expected the Select element to have some sort of visual feed back (blue outline, like it happens with Inputs) but nothing happened instead.

### Link to Reproduction

https://codesandbox.io/s/compassionate-brahmagupta-pc3h6q?file=/src/index.js

### Steps to reproduce

1. Click on 'A) label'
2. See that nothing happens

### Chakra UI Version

2.8.0

### Browser

- Firefox

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by antpaw** [comment]
it works in the latest version, sorry

**Comment by antpaw** [comment]
after double checking I've realized that i can only recreate the issue only in Firefox on latest mac os

**Comment by joaoGabriel55** [comment]
Hello @antpaw apparently this problem is more about Firefox. If you open this link, on Firefox:
https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible#try_it
You will see the same problem.

**Comment by antpaw** [comment]
@joaoGabriel55 I agree, Firefox only supports `:focus` I'm suggesting to include that selector as well.

**Comment by joaoGabriel55** [comment]
I got it now. Thanks!

**Comment by segunadebayo** [comment]
We use focus-visible styling for most components in Chakra. If you really need to make it show up, please update your app code to include focus styles.
