### ISSUE TITLE
Theme: button flickering

### ISSUE THREAD

**Issue by vikram-08** [chakra-ui/chakra-ui#7992]
### Description

I'm using Chakra-UI in NextJs 13, and the button is flickering. 
Other components are working well except for the button.

https://github.com/chakra-ui/chakra-ui/assets/104752629/7bbcdac1-3703-4b83-b4ff-afac2c0f9bfa

### Link to Reproduction

https://next-13-boilerplate.vercel.app

### Steps to reproduce

1. Use Chakra-UI with NextJS 13

### Chakra UI Version

2.8.0

### Browser

Google Chrome Version 116.0.5845.142 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Tanush-J** [comment]
I am not able to reproduce this bug, my current Chrome version is 117
