### ISSUE TITLE
[Select component] Brave 1.57.64 - duplicate dropdown arrows

### ISSUE THREAD

**Issue by TheSoggy** [chakra-ui/chakra-ui#7998]
### Description

In Brave 1.57.64, the Select field shows the native dropdown arrow as well as the custom Chakra arrow. 
![image](https://github.com/chakra-ui/chakra-ui/assets/8470009/fc3c4017-4856-4864-9685-36d9bc0af113)

### Link to Reproduction

https://chakra-ui.com/docs/components/select

### Steps to reproduce

1. Open Brave
2. Go to [Chakra UI Select](https://chakra-ui.com/docs/components/select)
3. Scroll to [Usage](https://chakra-ui.com/docs/components/select#usage)
4. Observe two dropdown arrows

### Chakra UI Version

2.8.0

### Browser

Brave 1.57.64

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Jmedina821** [comment]
![Captura de Pantalla 2023-09-15 a la(s) 8 31 44 p  m](https://github.com/chakra-ui/chakra-ui/assets/12435657/42e5e1fc-5aea-4109-8824-1a5a45542f27)
same problem here.

**Comment by segunadebayo** [comment]
This is now fixed in the latest Brave
