### ISSUE TITLE
Slider doesn't work on iOS

### ISSUE THREAD

**Issue by luisrudge** [chakra-ui/chakra-ui#8]
I can't change the value when using iOS

**Comment by aghassemi** [comment]
Same with Chrome on Android

**Comment by cyan33** [comment]
Confirmed that this is can be reproduced on the chrome dev tool in mobile. 

I can take a look if no one hasn't worked on it. :)

**Comment by devanshj** [comment]
Can you folks test if the issue is fixed by PR #18 on [this storybook](http://chakra-ui-pr-18.surge.sh/?path=/story/slider--default) which contains the PR

**Comment by luisrudge** [comment]
Fixed it for me

**Comment by segunadebayo** [comment]
Thanks for looking into this @devanshj

**Comment by devanshj** [comment]
@segunadebayo You're welcome!
