### ISSUE TITLE
Wire StoryBook knobs

### ISSUE THREAD

**Issue by devey** [chakra-ui/chakra-ui#800]
It's great you have all the components in StoryBook and I see it's actually quite a few of them but maybe it would make sense to start wiring some of them to some of the StoryBook addons; firstly to the knobs.

**Comment by with-heart** [comment]
Knobs are great! We're on `storybook@6.0.0` though, so I think we should try out [`addon-controls`](https://github.com/storybookjs/storybook/tree/next/addons/controls) which gives us even more control :)

**Comment by thefrontendwizard** [comment]
So I guess the natural outcome of this issue would be to start using the `addon-controls` on the stories. I'd like to help on that. Is it better to open a PR for each component stories or shall we have a big one with all the components stories with controls?

**Comment by with-heart** [comment]
Hi @thefrontendwizard, sorry for not getting back to you sooner! We're very busy with the 1.0 release but if you'd still like to work on this, please join us on Discord: https://discord.gg/BEZ8VDy

**Comment by thefrontendwizard** [comment]
> Hi @thefrontendwizard, sorry for not getting back to you sooner! We're very busy with the 1.0 release but if you'd still like to work on this, please join us on Discord: https://discord.gg/BEZ8VDy

Just joined :)

**Comment by with-heart** [comment]
I love the idea @devey and when we have time we will revisit our Storybook to make it more useful. In the short-term the team has more pressing priorities to focus on, so I'm going to close this for now.

**Comment by selrond** [comment]
How about reopening this?
Knobs seem to be especially beneficial for prop-based UI lib like Chakra
