### ISSUE TITLE
Can't use color tokens with `textFillColor` property

### ISSUE THREAD

**Issue by isBatak** [chakra-ui/chakra-ui#8003]
### Description

`textFillColor` doesn't respect color token.

Here is the example:
```
import { Input } from '@chakra-ui/react'

export const App = () => {
  return (
    <Input
      type="email"
      _autofill={{
        textFillColor: `colors.gray.500`,
      }}
    />
  )
}
```
generated class:
```
.css-1dcmgll:-webkit-autofill {
  -webkit-text-fill-color: colors.gray.500;
  text-fill-color: colors.gray.500;
}
```

expected:
```
.css-1dcmgll:-webkit-autofill {
  -webkit-text-fill-color: var(--chakra-colors-gray-500);
  text-fill-color: var(--chakra-colors-gray-500);
}
```

It should work with semantic color tokens too.
```
export const theme = extendTheme({
   semanticTokens: {
      colors: {
         'special.white': '#fff",
       },
    },
});

export const App = () => {
  return (
    <Input
      type="email"
      _autofill={{
        textFillColor: `colors.special.white`,
      }}
    />
  )
}
```

It should work with `!important` modifier.
```
export const App = () => {
  return (
    <Input
      type="email"
      _autofill={{
        textFillColor: `colors.special.white !important`,
      }}
    />
  )
}
```

### Link to Reproduction

https://play.chakra-ui.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwATFwEkA7NAVzwF9cAzTCFXAcgAEwALAQwGtNOBaMkgD0mGJzDYmAHWKyYADww5ckYgGc8AQTRpcAXlwAKAJQGAfPlm5cY7GUzFj1m7gA8Jcthevc2AJ5oMPrSIDAonEgANqE+rgD6nBQQNNFR+sDAcb7YitgAYmkAwhBRWPDMkGWY6gB0AOZ8-rUArAAMbUwANNm4lJRxwuYuJrIDxCCUQA

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.8.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by isBatak** [comment]
Workaround:
```
export const App = () => {
  return (
    <Input
      type="email"
      _autofill={{
        '--text-fill-color': 'colors.gray.500',
        textFillColor: 'var(--text-fill-color)',
      }}
    />
  )
}
```

**Comment by segunadebayo** [comment]
Added support for this. Will release a new minor shortly
