### ISSUE TITLE
Button _hover colorScheme is not working as expected

### ISSUE THREAD

**Issue by Newbie012** [chakra-ui/chakra-ui#8018]
### Description

When I use `<Button colorScheme="blue" _hover={{ colorScheme: "red" }} />`, I expected the color scheme of the button to change to red when I hover over it, but instead it kept the previous color scheme, and there we no hover changes at all.

### Link to Reproduction

https://codesandbox.io/s/misty-frog-s3tnln

### Steps to reproduce

1. Go to ['reproduction'](https://codesandbox.io/s/misty-frog-s3tnln)
2. Hover on the button
4. See the issue

### Chakra UI Version

2.8.1

### Browser

116

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Tanush-J** [comment]
Instead of `_hover={{ colorScheme: "red" }}` use `_hover={{ bg: "red" }}`

**Comment by Newbie012** [comment]
It's not just bg. It's color and borderColor as well. It would've been easier to simply use colorScheme.

**Comment by segunadebayo** [comment]
This is a design constraint in v2. You can't change colorScheme based on `_hover` or other conditions.
