### ISSUE TITLE
[Popover] Is there a way to allow for wider popover content?

### ISSUE THREAD

**Issue by andregoldstein** [chakra-ui/chakra-ui#802]
The parent `Popover` component seems to set it's max-width to `20rem`, I'm trying to filter a filter box that ideally would be wider but I can't seem to target the right props/components to do this. Any clues? Thanks!

**Comment by andregoldstein** [comment]
Closing as I have managed to set `maxW` to `PopoverContent`

**Comment by ayoubphy** [comment]
> 
> 
> Closing as I have managed to set `maxW` to `PopoverContent`

This doesn't solve the problem as the PopoverContent will no longer be horizontally centered relative to the Trigger Burron, and for my use case I need it to be centered

**Comment by with-heart** [comment]
@ayoubphy Open issue for this here: https://github.com/chakra-ui/chakra-ui/issues/2481
