### ISSUE TITLE
Skeleton performance issue

### ISSUE THREAD

**Issue by asborisov** [chakra-ui/chakra-ui#8022]
### Description

Using Skeleton utilise **a lot** of CPU time.
Skeleton usage examples page gives ~91% CPU utilisation on M1 Pro, while neighbour Props tab give ~0%

Based on my research it's caused by the keyframe animation of `background` property. Based on https://web.dev/stick-to-compositor-only-properties-and-manage-layer-count/ animating something but position, scale, rotation, skew, matrix or opacity causing forced re-paint. This operation can't be offload to GPU only.

In our codebase (private repo), I was able to reduce CPU consumption drastically using approach from https://openclassrooms.com/en/courses/5625816-create-modern-css-animations/5995831-create-more-peformant-color-animations-using-the-css-opacity-property

### Link to Reproduction

https://chakra-ui.com/docs/components/skeleton/usage

### Steps to reproduce

1. Go to [Skeleton examples](https://chakra-ui.com/docs/components/skeleton/usage) page using Safari
2. Open Dev tools and record `Timelines` session
3. Check `Energy Impact` and `Main Thread` work distribution
4. I can see Average 91% of CPU utilisation on M1 Pro chip. `Props` tab giving ~0% 😄 

### Chakra UI Version

2.8.0

### Browser

Safari 16.6

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by cranium** [comment]
I'm noticing this too- using ~60% of my CPU on Firefox, when I remove the animations in the inspector it drops to 5%-10%.

**Comment by asborisov** [comment]
I solved this in our codebase like this:
1. Update theme config like this:
```ts
import { ThemeComponents, defineStyleConfig } from '@chakra-ui/react';
import { keyframes } from '@chakra-ui/system';

const placeholderAnimation = keyframes({
  from: {
    opacity: 1,
  },
  to: {
    opacity: 0,
  },
});

export const skeletonTheming: ThemeComponents = {
  Skeleton: defineStyleConfig({
    baseStyle: {
      boxShadow: 'none',
      backgroundClip: 'padding-box',
      bgColor: 'gray.-120',
      cursor: 'default',
      color: 'transparent',
      pointerEvents: 'none',
      userSelect: 'none',
      '&::before, *': {
        visibility: 'hidden',
      },
      ':after': {
        content: "''",
        animation: `0.8s linear infinite alternate ${placeholderAnimation}`,
        bgColor: 'gray.-140',
        opacity: 0,
        display: 'block',
        width: 'full',
        height: 'full',
      },
    },
  }),
};

```
2. And replace Skeleton component with following:
```ts
import { Box, SkeletonProps } from '@chakra-ui/react';
import { usePrevious } from '@chakra-ui/react-use-previous';
import { chakra, forwardRef, keyframes, omitThemingProps, useStyleConfig } from '@chakra-ui/system';

import { useIsFirstRender } from '@hooks/useIsFirstRender';

const fade = keyframes({
  from: { opacity: 0 },
  to: { opacity: 1 },
});

/**
 * Based on chakra-ui Skeleton source as they don't have a way to override animation
 * https://github.com/chakra-ui/chakra-ui/blob/bd3d0fd2f444be2ba23764d7c86906cb488fb409/packages/components/skeleton/src/skeleton.tsx
 */
export const Skeleton = forwardRef<SkeletonProps, 'div'>((props, ref) => {
  const styles = useStyleConfig('Skeleton', props);
  // eslint-disable-next-line testing-library/render-result-naming-convention
  const isFirstRender = useIsFirstRender();

  const { isLoaded, fadeDuration, fitContent, ...rest } = omitThemingProps(props);

  const wasPreviouslyLoaded = usePrevious(isLoaded);

  if (isLoaded) {
    const animation = isFirstRender || wasPreviouslyLoaded ? 'none' : `${fade} ${fadeDuration}s`;

    return <chakra.div ref={ref} __css={{ animation }} {...rest} />;
  }

  return (
    <Box
      ref={ref}
      {...rest}
      __css={{
        width: fitContent ? 'fit-content' : undefined,
        ...styles,
      }}
    />
  );
});

Skeleton.displayName = 'Skeleton';
```

**Comment by segunadebayo** [comment]
I just pushed a fix for this that adds support for overriding animation via the `animation` prop.

We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
