### ISSUE TITLE
The Switch label cannot be themed through variants

### ISSUE THREAD

**Issue by nikparo** [chakra-ui/chakra-ui#8032]
### Description

Theming the label of the `Switch` does not work properly, despite partial support for a `label` "part". 

It only works when part of the `baseStyle` in the Switch component theme. It's not picked up when used in a variant, and according to typescript it is not a supported part.

### Link to Reproduction

https://codesandbox.io/s/ecstatic-snyder-d2s7jw?file=/src/index.tsx

### Steps to reproduce

In the codesandbox above, the label background is styled through `baseStyle.label.bg`.
On the other hand, `variants.custom.label` does nothing.

### Chakra UI Version

2.8.1

### Browser

Firefox 117.0.1, Chrome 117.0.5938.92

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

There is code for styling the `Switch` label through a "part" in the theme: https://github.com/chakra-ui/chakra-ui/blob/63431c1ef3b7e8ac9b97c94ca025dd54b9aa3338/packages/components/switch/src/switch.tsx#L76

The [default switch theme](https://github.com/chakra-ui/chakra-ui/blob/6d12ea81f4791f4df2953533b570178f59551b74/packages/components/theme/src/components/switch.ts#L61) does not include the `label`, nor does the [`switchAnatomy`](https://github.com/chakra-ui/chakra-ui/blob/6d12ea81f4791f4df2953533b570178f59551b74/packages/components/anatomy/src/components.ts#L136). I think they should.

**Comment by isBatak** [comment]
A part of the problem is in anatomy, there is no label part https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/anatomy/src/components.ts#L136, but component  is expecting it here https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/switch/src/switch.tsx#L76
You can make a PR to chakra anatomy definition to add label part.
I think you can quick-fix it like this, but I haven't tried ti
```
const { definePartsStyle, defineMultiStyleConfig } = createMultiStyleConfigHelpers(
	[...switchAnatomy.keys, 'label']
);
```

**Comment by nikparo** [comment]
We were using something similar to the second option, but the first one is much nicer. Tested it and it seems to work perfectly, thanks!

**Comment by isBatak** [comment]
Great, please If you have time open a PR for anatomy

**Comment by iNetJoJo** [comment]
@nikparo @isBatak here is PR
https://github.com/chakra-ui/chakra-ui/pull/8038
