### ISSUE TITLE
Add pseudo selectors :first-child and :last-child

### ISSUE THREAD

**Issue by Fsss126** [chakra-ui/chakra-ui#8034]
### Description

Add shorthand props for pseudo selectors :first-child and :last-child

### Problem Statement/Justification

By now chakra has `_first` and `_last` (and their negated counterparts `_notFirst` `_notLast`) props but they translate to CSS selectors `:first-of-type` and `:last-of-type` but there's no equivalent shorthand for `:first-child` and `:last-child` that would be also much helpful

### Proposed Solution or API

Add `_firstChild` `_lastChild` `_notFirstChild` `_notLastChild`

Need to add to [pseudoSelectors](https://github.com/chakra-ui/chakra-ui/blob/6d12ea81f4791f4df2953533b570178f59551b74/packages/core/styled-system/src/pseudos.ts#L37C24-L37C24)

```
   /**
   * Styles for CSS Selector `&:first-child`
   */
  _firstChild: "&:first-child",
  /**
   * Styles for CSS Selector `&:last-child`
   */
  _lastChild: "&:last-child",
  /**
   * Styles for CSS Selector `&:not(:first-of-type)`
   */
  _notFirstChild: "&:not(:first-child)",
  /**
   * Styles for CSS Selector `&:not(:last-child)`
   */
  _notLastChild: "&:not(:last-child)",
```

### Alternatives

Maybe also consider adding dedicated `_firstOfType` `_lastOfType` props (and negated variants) aliasing `_first` and `_last` because it felt misleading at first that they translate to CSS selectors `:first-of-type` and `:last-of-type` asI expected them to equal to `:first-child` and `:last-child`

**Comment by shaikahmadnawaz** [comment]
I am working on this issue.

**Comment by isBatak** [comment]
You can't do that because Emotion.js will throw warning if you use `:first-child`, `:nth-child`, or `:nth-last-child` selectors.
This is because, when using SSR, the style element is injected immediately above the styled element and actual `<style>` tag will be a first child, that's why Chakra uses `:first-of-type`, to skip the style tag.

https://github.com/emotion-js/emotion/issues/1178

**Comment by shaikahmadnawaz** [comment]
> @Fsss126 @shaikahmadnawaz You can't do that because Emotion.js will throw warning if you use `:first-child`, `:nth-child`, or `:nth-last-child` selectors. This is because, when using SSR, the style element is injected immediately above the styled element and actual `<style>` tag will be a first child, that's why Chakra uses `:first-of-type`, to skip the style tag.
> 
> Here are some workarounds to skip the `style` tag and still use first-child, but they might still trigger the warning [emotion-js/emotion#1178](https://github.com/emotion-js/emotion/issues/1178)

Okay 👍

**Comment by segunadebayo** [comment]
Closing based on the comment above
