### ISSUE TITLE
Let the NumberInput component get properties from the surrounding FormControl

### ISSUE THREAD

**Issue by kimroen** [chakra-ui/chakra-ui#804]
**Is your feature request related to a problem? Please describe.**
As described [in the documentation for `FormControl`](https://chakra-ui.com/formcontrol), you can surround an `Input` component with a `FormControl`, causing the properties `isInvalid`, `isRequired` and `isDisabled` to be propagated from the `FromControl` to the `Input`:

```js
function MyComponent() {
  return (
    <FormControl isInvalid={true}>
      <Input /> {/* This input now has `isInvalid={true}` */}
    </FormControl>
  );
}
```

I would expect the same thing to happen with `NumberInput`, but it doesn't.

```js
function MyComponent() {
  return (
    <FormControl isInvalid={true}>
      <NumberInput /> {/* This input does not have `isInvalid={true}` */}
    </FormControl>
  );
}
```

**Describe the solution you'd like**
It would be great if the `NumberInput` picked up this context in the same way that the `Input` and `Select` does. I imagine the implementation would be very similar, getting the props from `useFormControl` and setting some defaults.

**Describe alternatives you've considered**
The current way to do this is to pass it in explicitly both places:

```js
function MyComponent() {
  const isInvalid = true;
  return (
    <FormControl isInvalid={isInvalid}>
      <NumberInput isInvalid={isInvalid} />
    </FormControl>
  );
}
```

**Comment by with-heart** [comment]
The tools definitely exist in the 1.0 codebase to make this happen. We have `useFormControlContext` which connects to the `FormControl` context values, and `NumberInput` or `useNumberInput` could be modified to default to the values found in that context if not passed as props.

We don't have the bandwidth to add support for this right now, but I think it'd be a solid feature if anyone would like to pick it up!

**Comment by silltho** [comment]
I would like to give it a try.
