### ISSUE TITLE
Autocomplete Input

### ISSUE THREAD

**Issue by androidplayer1** [chakra-ui/chakra-ui#8041]
### Description

I tried several times to implement an autocompelte input but failed. Tried to combine input and menu or popover but still failed to do it.

As a component library, it is really weird that autocomplete is missing on Chakra,

### Problem Statement/Justification

Autocomplete is used for filtering, search etc ...

### Proposed Solution or API

Same as input field, but provide with suggestions elements.

**Comment by JORDAAAN1495** [comment]
I second this, an AutoComplete component would be really useful

**Comment by segunadebayo** [comment]
This is coming to Chakra v3.

**Comment by dovigz** [comment]
I dont see a autocomplete in the v3 docs...? What is it called?

**Comment by ericute** [comment]
> This is coming to Chakra v3.

@segunadebayo I don't see it in v3.1.1. Not in the docs, and not in the components list.

**Comment by SherifNeamatalla** [comment]
Why is this closed? the component is NOT in v3 ..
