### ISSUE TITLE
CSP error thrown by color-mode.util

### ISSUE THREAD

**Issue by apexskier** [chakra-ui/chakra-ui#8043]
### Description

When I use Chakra in a project with a content security policy, I see the following error:

```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src http://my-domain.test/ 'nonce-LBVC3WAK89jF6Nh0lWF7IQ=='". Either the 'unsafe-inline' keyword, a hash ('sha256-GNF74DLkXb0fH3ILHgILFjk1ozCF3SNXQ5mQb7WLu/Y='), or a nonce ('nonce-...') is required to enable inline execution.

preventTransition @ color-mode.utils.ts:55
setDataset @ color-mode.utils.ts:17
(anonymous) @ color-mode-provider.tsx:68
(anonymous) @ color-mode-provider.tsx:86
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
performSyncWorkOnRoot @ react-dom.development.js:26076
flushSyncCallbacks @ react-dom.development.js:12042
commitRootImpl @ react-dom.development.js:26959
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
```

This is not resolved by setting a nonce in my emotion cache, or by adding a `ColorModeScript` with a nonce.

### Link to Reproduction

https://github.com/chakra-ui/chakra-ui/compare/main...apexskier:chakra-ui:csp-style-issue

### Steps to reproduce

Run the vite-js example project from my fork, run behind https and add a content security policy matching the one in the vite config example. (I used something similar to `ngrok` and this chrome plugin https://chrome.google.com/webstore/detail/modheader-modify-http-hea/idgpnmonknjnojddfkpgkljpfnnfcklj.

### Chakra UI Version

default branch

### Browser

Google Chrome 116.0.5845.187

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The error comes from the `<style>` node creation here: https://github.com/chakra-ui/chakra-ui/blob/6d12ea81f4791f4df2953533b570178f59551b74/packages/components/color-mode/src/color-mode.utils.ts#L49-L55

To fix this the same way CSP is supported for the main script injection, a nonce also needs to be passed into this style injection. It would make sense to me to reuse the same nonce, which would be most seamless by using the same from emotion cache provider. (or it could be passed through in some other way)

An example/verification of this fix can be found here https://github.com/apexskier/chakra-ui/compare/csp-style-issue...apexskier:chakra-ui:csp-style-issue-fix (the first commit, or combo of first and second commits both work).

**Comment by apexskier** [comment]
This is a similar issue, though not the same cause or fix, as https://github.com/chakra-ui/chakra-ui/issues/3383.

**Comment by ernieMrtnz** [comment]
I just ran into this as well. I might try to patch this locally with your solution in the meantime, thnx btw!

**Comment by josh-atkins** [comment]
Just came across this issue while trying to get rid of this error with chakra-ui/nextjs.

If I understand correctly, the style tag being injected is hard coded into the source, so adding the suggested hash to the CSP `style-src` should remove the error (`sha256-GNF74DLkXb0fH3ILHgILFjk1ozCF3SNXQ5mQb7WLu/Y=`)

..not super elegant but seems to work so long as the source remains unchanged.

**Comment by andrey-mitko** [comment]
Hi, I recently encountered the same issue and decided to [open a PR with the suggested fix](https://github.com/chakra-ui/chakra-ui/pull/8523). 

The pull request introduces the above-mentioned changes to set the nonce value on the injected style tag based on the nonce value already set inside the emotion cache provider.

**Comment by segunadebayo** [comment]
This is now fixed in the latest version
