### ISSUE TITLE
lazy menu + portal does not work as expected

### ISSUE THREAD

**Issue by codebutler** [chakra-ui/chakra-ui#8047]
### Description

Given code like:

```tsx
<Menu isLazy lazyBehavior="unmount">
  <MenuButton>Open menu</MenuButton>
  <Portal>
    <MenuList>
      <MenuItem>Menu 1</MenuItem>
      <MenuItem>New Window</MenuItem>
      <MenuItem>Open Closed Tab</MenuItem>
      <MenuItem>Open File</MenuItem>
    </MenuList>
  </Portal>
</Menu>
```

I expected the Portal would only be created when needed, however that's not the case because the conditional rendering happens for the children of `MenuList` rather than `Menu`.

https://github.com/chakra-ui/chakra-ui/blob/6d12ea81f4791f4df2953533b570178f59551b74/packages/components/menu/src/use-menu.ts#L521

### Link to Reproduction

https://codesandbox.io/s/restless-sun-9mfjrw?file=/src/index.tsx

### Chakra UI Version

2.8.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by codebutler** [comment]
A possible solution might be to add an optional component like:

```tsx
<Menu isLazy lazyBehavior="unmount">
  <MenuButton>Open menu</MenuButton>
  <MenuChildren>
    <Portal>
      <MenuList>
        <MenuItem>Menu 1</MenuItem>
        <MenuItem>New Window</MenuItem>
        <MenuItem>Open Closed Tab</MenuItem>
        <MenuItem>Open File</MenuItem>
      </MenuList>
    </Portal>
  </MenuChildren>
</Menu>
```

**Comment by codebutler** [comment]
I didn't realize that the context was exported, so this is what I've done within my app:

```tsx
import { Portal, useMenuContext } from "@chakra-ui/react";

export const MenuPortal: React.FC<React.PropsWithChildren> = ({
  children,
}) => {
  const { isLazy, isOpen } = useMenuContext();
  return isLazy && !isOpen ? null : <Portal>{children}</Portal>;
};
```

Let me know if you think this should be added to chakra and I can open a PR.

**Comment by NiklasPor** [comment]
> I didn't realize that the context was exported, so this is what I've done within my app:
> 
> ```tsx
> import { Portal, useMenuContext } from "@chakra-ui/react";
> 
> export const MenuPortal: React.FC<React.PropsWithChildren> = ({
>   children,
> }) => {
>   const { isLazy, isOpen } = useMenuContext();
>   return isLazy && !isOpen ? null : <Portal>{children}</Portal>;
> };
> ```
> 
> Let me know if you think this should be added to chakra and I can open a PR.

Just as a heads-up, won't this kill the "out" animation? Also looking for a workaround for this use-case (in my case for the popover).

**Comment by segunadebayo** [comment]
Closing based on https://github.com/chakra-ui/chakra-ui/issues/8047#issuecomment-1747007330
