### ISSUE TITLE
Security contact

### ISSUE THREAD

**Issue by adrian-doyensec** [chakra-ui/chakra-ui#8051]
### Description

Hi chakra-ui team!

I've identified a potential security issue with Chakra-ui and would like to report it in private. I couldn't find any dedicated email (security@ doesn't work) or page for that (the https://github.com/chakra-ui/chakra-ui/security page is empty). Could you share a preferred contact method?

Is there a dedicated e-mail address? Is there a PGP key I could use?

Regards

### Link to Reproduction

n/a

### Steps to reproduce

n/a

### Chakra UI Version

2.8.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Please send an email to support@chakra-ui.com
