### ISSUE TITLE
`useClipboard` occasionally displays an unexpected dialog box

### ISSUE THREAD

**Issue by justin-gurtz** [chakra-ui/chakra-ui#8052]
### Description

`onCopy` from `useClipboard` occasionally displays a weird dialog box:

<img width="1234" alt="Screenshot 2023-10-04 at 16 52 22" src="https://github.com/chakra-ui/chakra-ui/assets/40037115/f0df955f-2704-40be-8a00-1efaf435601b">

### Link to Reproduction

N/A

### Steps to reproduce

It's unclear. I saw it 2 times yesterday but compared to all my other 'normal' experiences I don't remember doing anything different. Before creating this ticket I tried to reproduce it but couldn't.

### Chakra UI Version

2.8.1

### Browser

Safari 17.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

FWIW I'm not doing anything fancy, just a simple button:

```
const Component = () => {
  const { onCopy, hasCopied } = useClipboard('...')

  return (
    <Button onClick={onCopy}>
      {hasCopied ? 'Copied to clipboard!' : 'Share Framework'}
    </Button>
  )
}
```

**Comment by JapMul** [comment]
This happens as a fallback from the [copy-to-clipboard](https://github.com/sudodoki/copy-to-clipboard) package when `document.execCommand` fails for some reason. The Chakra docs don't specify it (and typescript will not like it), but if you call `useClipboard('...', { debug: true})` it will log the errors to your console.

[Demo](https://codesandbox.io/s/aged-snow-9xfjxc?file=/src/index.tsx)

**Comment by segunadebayo** [comment]
Pushed a fix for this to use navigator.writeText when possible

We'll release an update shortly. If the issue persists after upgrading, I'll re-open it.
