### ISSUE TITLE
MenuList is jumping on hover when wrapping 15+ MenuItem

### ISSUE THREAD

**Issue by floustao** [chakra-ui/chakra-ui#8053]
### Description

When I use `MenuList` wrapping a "long" list making the list scrollable, if I scroll down let's say to select the bottom MenuItem, the list jumps and makes it tricky to select.
It happens to most of my lists.

Please see the codesandbox.

I tried the fix discussed here but it didn't work for me:
https://github.com/chakra-ui/chakra-ui/issues/7139

I also tried bumping the chakra-ui version but no success.

Any ideas?
Thank you

### Link to Reproduction

https://codesandbox.io/s/confident-sea-pydp2z?file=/src/index.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/confident-sea-pydp2z?file=/src/index.tsx
2. Click on button `Click me`
3. Scroll down to bottom of list to select the 20th name
4. See the list jumping

### Chakra UI Version

^2.3.7

### Browser

Google Chrome Version 116.0.5845.187 (Official Build) (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by DarthMuzammil** [comment]
@floustao i tried it in the sandbox, doesn't happen.

**Comment by segunadebayo** [comment]
Sorry, I can't reproduce this.
