### ISSUE TITLE
After menu close there is some part of top section  showing 

### ISSUE THREAD

**Issue by harshmangalam** [chakra-ui/chakra-ui#8059]
### Description

```js

import {
  Menu,
  MenuButton,
  MenuList,
  MenuItem,
  IconButton,
} from "@chakra-ui/react";
import { Link } from "react-router-dom";
import { CgMenuGridO } from "react-icons/cg";
import { links } from "./_links";
function DesktopMenu() {
  return (
    <Menu isLazy>
      <MenuButton
        as={IconButton}
        aria-label="Menus"
        icon={<CgMenuGridO size={20} />}
      />
      <MenuList>
        {links.map((menu) => (
          <MenuItem
            key={menu.name}
            as={Link}
            to={menu.to}
            aria-label={menu.name}
          >
            {menu.name}
          </MenuItem>
        ))}
      </MenuList>
    </Menu>
  );
}

export default DesktopMenu;


```

### Link to Reproduction

https://suretrustforruralyouth.com/

### Steps to reproduce

Click on menu icon from top right corner
Now navigate to different routes
You will see some portion still showing 
If i will remove `isLazy` from Menu component then all menu still showing and not closed

### Chakra UI Version

2.8.1

### Browser

Google chrome Version 117.0.5938.149 (Official Build) (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Please provide an actual reproduction with CodeSandbox or Stackblitz for us to help.
