### ISSUE TITLE
[Progress] Bar should allow setting of max (and min), and auto calculation of % progress

### ISSUE THREAD

**Issue by timkindberg** [chakra-ui/chakra-ui#806]
**Is your feature request related to a problem? Please describe.**
When adding a progress bar where you have some data with a max value that is not 100 and a current value that is not between 0–100, it would be nice to not have to convert to a percentage.

**Describe the solution you'd like**
I'd like to pass in any `max` (and in lesser scenarios also `min`) and a value.

Example:
```
<Progress max={487} value={377} />
```
This would display a progress bar that is 77% filled because 377 ÷ 487 = .77

**Additional context**
Prop defaults:
- max can default to 100
- min can default to 0

This would also provide richer ADA compliance because the screen-reader would have more knowledge of the data actually being represented when it is not a clean 0–100.

**Comment by with-heart** [comment]
Oh hi Tim 👋 

This will be supported in 1.0! `min` defaults to `100` and `max` defaults to `100`, but they are overridable and the percentage is calculated using this formula:

![image](https://user-images.githubusercontent.com/1954752/83921623-ba1c6e80-a74c-11ea-9850-2066f6a062a1.png)

Plugging in your example leaves us with ~77.4% :)
