### ISSUE TITLE
Would you add support for gridTemplate ?

### ISSUE THREAD

**Issue by lishine** [chakra-ui/chakra-ui#807]

**Comment by lishine** [comment]
BTW 'placeItems' seems to not yet supported #586

**Comment by segunadebayo** [comment]
Hi @lishine,

We've added support for `placeItems` in preparation for the next release.

Thanks for bringing it up.

**Comment by with-heart** [comment]
`gridTemplate` is also supported via `gridTemplateRows`+`gridTemplateColumns`+`gridTemplateAreas` :)

**Comment by lishine** [comment]
> `gridTemplate` is also supported via `gridTemplateRows`+`gridTemplateColumns`+`gridTemplateAreas` :)

Sure, but why would we limit ourselves to write three css properties, when CSS itself gives possibility to write all three in one property

**Comment by lishine** [comment]
It wasn't clear to me, do you intend to support gridTemplate?
