### ISSUE TITLE
Tooltip show delay not canceled when child element changes

### ISSUE THREAD

**Issue by codebutler** [chakra-ui/chakra-ui#8076]
### Description

The tooltip is incorrectly displayed when the element is no longer under the cursor:

https://github.com/chakra-ui/chakra-ui/assets/3827/df2df3c0-1e19-4dc9-be43-8ed59d70b584

. This only happens if the content changes. The problem goes away if the icon prop is fixed.

### Link to Reproduction

https://codesandbox.io/s/little-fog-tnwf4c?file=/src/index.tsx

### Steps to reproduce

See codesandbox and video.

Hover over the button with the icon and click just before the tooltip is displayed. The element will move to no longer be under the cursor and the tooltip will incorrectly be displayed. 

### Chakra UI Version

2.8.1

### Browser

Google Chrome 118, Microsoft Edge 111

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
The tooltip re-renders due to the state change in the parent. As you can see, we cleanup the timeouts correctly
![CleanShot 2024-10-04 at 18 54 33@2x](https://github.com/user-attachments/assets/e263ab68-2650-4934-9a5a-9818718b449c)

I recommend localizing the state as much as possible.

```tsx
const TooltipButton = React.forwardRef((props, ref) => {
  const [value, { toggle }] = useBoolean(true);
  return (
    <IconButton
      ref={ref}
      aria-label="button"
      icon={value ? <WarningIcon /> : <WarningTwoIcon />}
      onClick={toggle}
      {...props}
    />
  );
});
```
