### ISSUE TITLE
CircularProgress size type accepts (string | number)[] and renders accordingly but size type is misdefined

### ISSUE THREAD

**Issue by mwmcode** [chakra-ui/chakra-ui#8077]
### Description

When I pass `string[]` to `size` like this `<CircularProgress size={['32px', '62px']} />` it works (renders different sizes depending on screen size (as codesandbox link shows) but TS complains (screenshot)

![Screenshot 2023-10-18 at 5 44 46 PM](https://github.com/chakra-ui/chakra-ui/assets/13101565/9c8f8bcc-ece4-4686-8e1a-b823b8e653c4)

### Link to Reproduction

https://codesandbox.io/s/keen-sea-r3qlwo?file=/src/index.tsx

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.8.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

👀 packages/components/progress/src/circular-progress.tsx

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
