### ISSUE TITLE
Active Step Percent getting NaN when only one step

### ISSUE THREAD

**Issue by bwcr** [chakra-ui/chakra-ui#8078]
### Description

I was forced to make a stepper in my dynamic form component and the activeStepPercent returns NaN when it only got one step on some forms. I might not want to render the stepper conditionally so maybe it needs minor improvement. Thanks

### Link to Reproduction

https://codesandbox.io/s/amazing-meninsky-vzy5sv

### Chakra UI Version

2.8.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Good catch. Pushed a fix for this.

We'll release an update shortly.
