### ISSUE TITLE
`Box` component miss `variant` prop

### ISSUE THREAD

**Issue by zyyv** [chakra-ui/chakra-ui#8079]
### Description

I briefly searched past issues and found no duplicate questions. If there are any, please close them at any time to maintain the unity of the discussion.

The Box component is missing the variant property, is this intentional?

I think variant is equally important on Box components, like the following case.

E.g.
```ts
const pseudoBorder = {
  _before: {
    content: '""',
    pos: 'absolute',
    zIndex: '0',
    w: '200%',
    h: '200%',
    transform: 'scale(.5)',
    transformOrigin: '0',
    bgColor: 'var(--b-color, #fefefe)',
  },
};

export const BoxTheme = defineStyleConfig({
  baseStyle: { pos: 'relative' },
  variants: {
    bt: {
      _before: {
        ...pseudoBorder,
        h: '1px',
        top: 0,
        left: 0,
      },
    },
    // ...
  },
});
```

Expect: 
```html
<!-- The Box component has pseudo element as a border top -->
<Box variant="bt">...</Box> 
```

But `variant` isn't exist in Box conponent.
<img width="882" alt="image" src="https://github.com/chakra-ui/chakra-ui/assets/42139754/2f9a1ff9-de59-449f-b313-8dbd52db3c79">

As a workaround, i can use 
```ts
chakra(Box, { ... })
```

But this is not a universal way

### Link to Reproduction

none

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

```json
"@chakra-ui/react": "^2.7.1",    
"@chakra-ui/theme": "^3.1.2",
```

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by willklein** [comment]
If I could offer some insight as a fellow developer and Chakra UI consumer, I've never seen a component library or design system implement variants on a `Box` component. I wouldn't expect any of the layout components to support variants.

**Comment by zyyv** [comment]
I agree with you, it's more likely to be customized for my needs.
Do you have a good way to resolve this example?
