### ISSUE TITLE
mode @chakra-ui/theme-tools not work in nextjs 13

### ISSUE THREAD

**Issue by bebru2k1** [chakra-ui/chakra-ui#8082]
### Description

Sorry for too little content. I hope the Chakra team will review this closed issue. I see quite a few people are having problems. 
Link here https://github.com/chakra-ui/chakra-ui/issues/7681.  
Thanks

### Link to Reproduction

no link

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.8.1

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by sangdth** [comment]
I can confirm it still happens today. Remove the `CacheProvider` make it works!!!

```
extendTheme({
  global: (props: StyleFunctionProps) => ({
    body: {
      bg: mode('gray.100', 'gray.800')(props),
    },
  })
})
```

Packages:

```
    "@chakra-ui/icons": "2.1.1",
    "@chakra-ui/next-js": "2.2.0",
    "@chakra-ui/react": "2.8.2",
    "@chakra-ui/styled-system": "2.9.2",
    "@chakra-ui/theme-tools": "2.1.2",
    "@emotion/react": "11.11.1",
    "@emotion/styled": "11.11.0",

    "next": "14.0.3",
```

**Comment by bebru2k1** [comment]
Does clearing cache have any effect on performance?

**Comment by bebru2k1** [comment]
> I can confirm it still happens today. Remove the `CacheProvider` make it works!!!
> 
> The below setup will stuck with `gray.100` on both light and dark mode, removing the CacheProvider and it works correctly.
> 
> ```
> extendTheme({
>   global: (props: StyleFunctionProps) => ({
>     body: {
>       bg: mode('gray.100', 'gray.800')(props),
>     },
>   })
> })
> ```
> 
> Packages:
> 
> ```
>     "@chakra-ui/icons": "2.1.1",
>     "@chakra-ui/next-js": "2.2.0",
>     "@chakra-ui/react": "2.8.2",
>     "@chakra-ui/styled-system": "2.9.2",
>     "@chakra-ui/theme-tools": "2.1.2",
>     "@emotion/react": "11.11.1",
>     "@emotion/styled": "11.11.0",
> 
>     "next": "14.0.3",
> ```

Does clearing cache have any effect on performance?

**Comment by zulalc** [comment]
My Vite + React project has the same issue right now, how do you remove CacheProvider? Are there any other solutions?

**Comment by segunadebayo** [comment]
I recommend switching to `_dark` instead. Please take a look at the comment below.

https://github.com/chakra-ui/chakra-ui/issues/7681#issuecomment-1823838873

This might have something to do with Next.js RSC, you can also remove the CacheProvider. It's not needed anymore.
