### ISSUE TITLE
Slider thumb tracks mouse when you are pressing it and then blur out of the element it's in

### ISSUE THREAD

**Issue by AmaxJ** [chakra-ui/chakra-ui#8089]
### Description

When I hold down the slider thumb and move the mouse cursor out of the window in which the slider is implemented, if i move the cursor back into the window where the slider is, the thumb tracks the cursor even though i am no longer pressing it.

This issue is visible in the chakra-ui docs themselves: https://chakra-ui.com/docs/hooks/use-slider 

### Link to Reproduction

https://chakra-ui.com/docs/hooks/use-slider

### Steps to reproduce

1. Press the slider thumb with your mouse
2. While holding it down, move your cursor out of the white box and release.
3. Bring the cursor back into the white box.
4. Now the thumb will track the movement of your mouse even though you are not pressing it.

### Chakra UI Version

2.6.1

### Browser

chrome Version 118.0.5993.88

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Potential solution: 
`usePanEvent(rootRef, {
  onPanSessionStart(event) {
    const state = stateRef.current
    if (!state.isInteractive) return
    setDragging(true)
    focusThumb()
    setValueFromPointer(event)
    onChangeStart?.(state.value)

    // add global mouseup listener
    window.addEventListener('mouseup', handleGlobalMouseUp)
  },
  onPanSessionEnd() {
    const state = stateRef.current
    if (!state.isInteractive) return
    setDragging(false)
    onChangeEnd?.(state.value)

    // remove global mouseup listener
    window.removeEventListener('mouseup', handleGlobalMouseUp)
  },
  onPan(event) {
    const state = stateRef.current
    if (!state.isInteractive) return
    setValueFromPointer(event)
  },
})

const handleGlobalMouseUp = () => {
  setDragging(false)
  // Ensure to remove listener just in case
  window.removeEventListener('mouseup', handleGlobalMouseUp)
}`

**Comment by segunadebayo** [comment]
I can't reproduce this. We have already handled this use case in the PanEvent class.

Please share a screen recording or a reproduction
