### ISSUE TITLE
When printing a page with responsive layout, the browser always use the narrowest breakpoint.

### ISSUE THREAD

**Issue by ShikyC** [chakra-ui/chakra-ui#8091]
### Description

Minimum code:

```
function App() {
  return (
    <Flex>
      <Button display={["none", "none", "none", "none", "block"]}>A</Button>
      <Button display={["none", "none", "none", "block", "block"]}>B</Button>
      <Button display={["none", "none", "block", "block", "block"]}>C</Button>
      <Button display={["none", "block", "block", "block", "block"]}>D</Button>
      <Button display={["block", "block", "block", "block", "block"]}>E</Button>
    </Flex>
  );
}
```

When trying to print the page in the browser, there's always only button E visible, no matter how wide the page is.

### Link to Reproduction

https://codesandbox.io/s/trusting-bassi-mrr2st?file=/src/index.js

### Steps to reproduce

Open the page in the browser and open the print dialog. Codesandbox does not support printing well, so it's better start the project locally.

### Chakra UI Version

2.8.1

### Browser

Edge & Safari. Not tested with other browsers.

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by ShikyC** [comment]
Fixed by adding a custom css print media query to every responsive component. Example:

```
import { css } from "@chakra-ui/react";

// When printing, this grid always use the "1fr" layout
<Grid templateColumns={["1fr", "1fr 1fr", "1fr 1fr 1fr"]} /> 

// Force the grid to use the "1fr 1fr 1fr" layout when printing
<Grid templateColumns={["1fr", "1fr 1fr", "1fr 1fr 1fr"]} css={css({ "@media print": { gridTemplateColumns: "1fr 1fr 1fr" } })} /> 
```

**Comment by segunadebayo** [comment]
Closing based on the workaround above.

**Comment by tilak-puli** [comment]
Reopening this as work around is not feasible to do for a big page with lots of components. If we can select breakpoint for the print view that would be great
