### ISSUE TITLE
Icon does not change its size using iconSize in Checkbox with default size values

### ISSUE THREAD

**Issue by ltlaitoff** [chakra-ui/chakra-ui#8092]
### Description

This issue is based on #6288, with a more detailed description of the problem because it was **not resolved**.

When the `iconSize` parameter is set in the `<Checkbox>` component, the icon size does not change.

The size also does not change when specifying other standard values for the `size` parameter, namely `sm`, `md`, and `lg`.

Example:

```tsx
<Checkbox iconSize="2rem">Option</Checkbox>
```

Or an example from the [DOCUMENTATION](https://chakra-ui.com/docs/components/checkbox/usage#changing-the-icon-color-and-size):

```tsx
<Checkbox
  iconColor="blue.400"
  iconSize="1rem"
>
  Option
</Checkbox>
```

However, miraculously, when the `size` parameter is set to a value different from the standard ones, `iconSize` starts working

Example:

```tsx
<Checkbox
  size="other"
  iconSize="2rem"
>
  Option
</Checkbox>
```

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-checkbox-iconsize-problem-again-8zl7jx?file=/src/App.js

### Steps to reproduce

1. Go to 'CodeSandbox link'
2. Look at the 'Checkbox Example'
3. Examine the 'iconSize' parameter
4. See it doesn't work

### Chakra UI Version

2.8.1

### Browser

Google Chrome 118

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by fzn0x** [comment]
Valid issue. 

Working

```ts
<Td mx="auto">
  {" "}
  <Flex mx="auto" direction="row" gap={3} align="center">
    <Checkbox
      isChecked={checkboxes[0].isChecked}
      onChange={(e) => handleCheckboxChange(0)}
      sx={{
        "& .chakra-checkbox__control": {
          borderColor: "black",
          borderWidth: "0.1px",
          width: "34px",
          height: "36px",
          rounded: "full",
        },
      }}
      _checked={{
        "& .chakra-checkbox__control": {
          background: "#D28E2F",
          color: "white",
        },
      }}
      size="other"
      iconSize="2rem"
    />
  </Flex>
</Td>
```

Not working

```ts
<Td mx="auto">
  {" "}
  <Flex mx="auto" direction="row" gap={3} align="center">
    <Checkbox
      isChecked={checkboxes[0].isChecked}
      onChange={(e) => handleCheckboxChange(0)}
      sx={{
        "& .chakra-checkbox__control": {
          borderColor: "black",
          borderWidth: "0.1px",
          width: "34px",
          height: "36px",
          rounded: "full",
        },
      }}
      _checked={{
        "& .chakra-checkbox__control": {
          background: "#D28E2F",
          color: "white",
        },
      }}
      size="lg"
      iconSize="2rem"
    />
  </Flex>
</Td>
```

Only when the `size` is set.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
