### ISSUE TITLE
Disabling all animations

### ISSUE THREAD

**Issue by kul-sudo** [chakra-ui/chakra-ui#8099]
### Description

Hello!

Chakra UI seems to have no way to disable all animations of all components.

### Problem Statement/Justification

Such a feature would be useful if a user, let's say, has a bad device, so we can let them toggle whether they need animations or not.

### Proposed Solution or API

I think it should be able to be controlled in `ChakraProvider`.

**Comment by segunadebayo** [comment]
This is duplicate issue #3696
