### ISSUE TITLE
Exposing the useAlertContext - custom component theming issues

### ISSUE THREAD

**Issue by CaitlinSweeney** [chakra-ui/chakra-ui#8104]
### Description

Hello,
I'm upgrading from `Chakra-UI@v1 `to `Chakra-UI@v2` (finally). I have my custom components in a npm package so I can re-use the theme and custom components in 2 applications. I am looking to customize some components a bit easier.

### Problem Statement/Justification

I'm having a lot of issues getting the custom theme files to access the theme provider. It works as expected here: https://codesandbox.io/s/chakra-ui-v2-with-custom-themes-76r2xy

 I understand you can override the `AlertIcon` by passing a child component. Would it be possible to export the `useAlertContext` so the `status` is exposed? Makes it easier to create a reusable component for overriding the AlertIcon. Right now the `alertStyles` is exported.

### Proposed Solution or API

Option for some customization when implementing:  
```
const STATUSES = {
  default: { icon: ErrorIcon, colorScheme: 'gray' },
  info: { icon: ErrorIcon, colorScheme: 'blue' },
  warning: { icon: ErrorIcon, colorScheme: 'orange' },
  success: { icon: CheckIcon, colorScheme: 'green' },
  error: { icon: ErrorIcon, colorScheme: 'red' },
}
export type AlertStatus = keyof typeof STATUSES

export function getStatusIcon(status: AlertStatus) {
  return STATUSES[status].icon
}
 export const AlertIcon = forwardRef<AlertIconProps, 'span'>((props, ref) => {
  const { status } = useAlertContext()
  const CustomIcon= getStatusIcon(status)
  
  return (
    <ChakraAlertIcon
      {...props}
      {...ref}
    >
      {props.children ||  <CustomIcon h="100%"w="100%" /> )}
    </ChakraAlertIcon>
  )
})
``` 

### Alternatives

Alternatively, I can just use this.
```
export const AlertGroup = forwardRef<AlertGroupProps, 'div'>((props, ref) => {
  const {
    children,
    description,
    descriptionProps,
    iconProps,
    status = 'error',
    title,
    titleProps,
    orientation,
    variant,
    ...sx
  } = props

  const container = {
    status,
    orientation,
    ref,
    variant,
    ...sx,
  }

  const getIcon = (() => {
    switch (status) {
    case 'error': return <ErrorIcon color="red.500" />
    case 'info': return <ErrorIcon color="blue.500"  />
    case 'success': return <CheckIcon color="green.500" />
    case 'warning': return <WarningIcon color="orange.300" />
    default: return <ErrorIcon color="gray.200" />
    }
  })()

  return (
    <ChakraAlert {...container}>
      <ChakraAlertIcon {...iconProps}>{getIcon}</ChakraAlertIcon>
      {title && (
        <ChakraAlertTitle color="blue.500" {...titleProps}>
          {title}
        </ChakraAlertTitle>
      )}
      {description && (
        <ChakraAlertDescription {...descriptionProps}>{description}</ChakraAlertDescription>
      )}
      {children}
    </ChakraAlert>
  )
})
```

**Comment by Philzen** [comment]
@CaitlinSweeney / @bhainesva with #8433 merged this seems now fixed … guess we're waiting now for v2.8.3 to be released, any ideas when this is going to happen so this issue can be closed?

**Comment by bhainesva** [comment]
I made the PR because I was also having this issue, but I'm not a maintainer and can't speak to the release schedule.

**Comment by Philzen** [comment]
@segunadebayo is it possible to have v2 patch releases anytime soon?

I would have tried to use the repo directly as a dependency in package.json, but as our project is redwoodjs which is fixed to yarn that's a dead end as it unfortunately cannot build pnpm projects.

Apologies and hoping this doesn't come across nagging as i know (and am excited about) you are busy building v3.

**Comment by CaitlinSweeney** [comment]
@Philzen Apologies for the non-reply. I'm not a maintainer, thanks for putting up a PR

**Comment by segunadebayo** [comment]
This is now resolved in the latest v2 version
