### ISSUE TITLE
CardFooter component does not respect spacing via Flex component

### ISSUE THREAD

**Issue by EpicPi** [chakra-ui/chakra-ui#8105]
### Description

Using the `Flex` component in the `CardFooter` results in no spacing. When used in the `CardBody`, `Flex` behaves appropriately.

```
    <Card>
     <CardBody>
        <Flex>
          <Button>
            Next
          </Button>
          <Spacer />
          <Button>
            Report
          </Button>
        </Flex>
     </CardBody>
     <CardFooter>
     </CardFooter>
    </Card>
```
![image](https://github.com/chakra-ui/chakra-ui/assets/9906905/d534d758-5676-467d-a85b-31c32b052c5f)

```
    <Card>
     <CardBody>
     </CardBody>
      <CardFooter>
        <Flex>
          <Button>
            Next
          </Button>
          <Spacer />
          <Button>
            Report
          </Button>
        </Flex>
      </CardFooter>
    </Card>
```
![image](https://github.com/chakra-ui/chakra-ui/assets/9906905/0d437f61-4509-402f-9e33-f9f1c710ceab)

### Link to Reproduction

https://codesandbox.io/s/dark-currying-ff9vcz?file=/src/index.tsx

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

@chakra-ui/react: 2.8.1

### Browser

Chrome 118

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by akshay-xp** [comment]
@EpicPi `CardFooter` already has flex property. 
You can remove the extra `Flex` in `CardFooter` for it to work.

``` 
<CardFooter>
  <Button>
    Next
  </Button>
  <Spacer />
  <Button>
    Report
  </Button>
</CardFooter>
```

**Comment by EpicPi** [comment]
Ah, brilliant! 
Thanks!

**Comment by EpicPi** [comment]
Resolved.
