### ISSUE TITLE
Tabs component ignores DarkMode wrapper component

### ISSUE THREAD

**Issue by IliasP91** [chakra-ui/chakra-ui#8107]
### Description

When I wrap a Tabs component with a DarkMode component it is expected to have its dark mode colors applied but it does not.

### Link to Reproduction

https://play.chakra-ui.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwATAB0A7XXAEQENMBrAWWhgBpjSAVCgI2ZN3Y4GdubTgBkk-bEN6cAChSIwANoJbSOchYu4BfXADNMEFLgDkAATAALCtUwUAtAFckAekwwKYbCeLEYADwwcXEgiCVwAQTQ0XABeXAAKAEo4gD58VXdsR0wSBNVSAB5KGnpYVILSXEK+fgqeKqqa0XFsesaO6r5UgHkFQpduys7mjl7+wc52zqbuvpgBoYaOxZaJeuHZ2XklOs3G0Y0lVIBGVfUdxWmZru3NVIAmc6Or-a2L+4BmZ8vrlcmPrs-kUAXtlgMSnQGNMksRtMQQNogA

### Steps to reproduce

1. Go to  [playground](https://play.chakra-ui.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwATAB0A7XXAEQENMBrAWWhgBpjSAVCgI2ZN3Y4GdubTgBkk-bEN6cAChSIwANoJbSOchYu4BfXADNMEFLgDkAATAALCtUwUAtAFckAekwwKYbCeLEYADwwcXEgiCVwAQTQ0XABeXAAKAEo4gD58VXdsR0wSBNVSAB5KGnpYVILSXEK+fgqeKqqa0XFsesaO6r5UgHkFQpduys7mjl7+wc52zqbuvpgBoYaOxZaJeuHZ2XklOs3G0Y0lVIBGVfUdxWmZru3NVIAmc6Or-a2L+4BmZ8vrlcmPrs-kUAXtlgMSnQGNMksRtMQQNogA)
2 See rendered tabs, they should have the dark mode colors, ie white font color instead of black

### Chakra UI Version

2.8.1

### Browser

Chrome, Firefox

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
The DarkMode component doesn't apply the color/bg from the color mode. Indeed, this is a design flaw in v2 that we've improved in v3.

Kindly tweak the styles as needed in your app.
