### ISSUE TITLE
chakraTheme import errors for use with ChakraBaseProvider, workaround results in weird styling.

### ISSUE THREAD

**Issue by Diligentia-Uitgeverij** [chakra-ui/chakra-ui#8108]
### Description

When I follow the Chakra [documentation ](https://chakra-ui.com/getting-started)to only include a specific Component, I'd expect the imports to work and not having to do workarounds with namespace imports. 

Instead of using the ChakraProvider, I am using the ChakraBaseProvider as documented below to just include the Modal component. After changing the imports to namespace imports This works but my modal styling is off. Specifically the "ModalCloseButton".

I decided to make this a bug report due to the import weirdness, but I have also included the styling issues, which might have been the result of my workaround. 

I have no additional styling issues when replicating the issue in CodeSandbox.

### Link to Reproduction

https://codesandbox.io/s/nameless-shape-ql6zkw?file=/src/index.tsx

### Steps to reproduce

```
import { ChakraBaseProvider, extendBaseTheme } from '@chakra-ui/react'
import chakraTheme from '@chakra-ui/theme'

const { Modal } = chakraTheme.components // problematic part, errors below 

const theme = extendBaseTheme({
    components: {
        Modal,
    },
})
function App() {
   return <ChakraBaseProvider theme={theme}> 
       //other providers
   </ChakraBaseProvider>
}    
```
**Errors:**
**in WebStorm** 

> TS2339: Property 'components' does not exist on type 'typeof import("//wsl$/Ubuntu-18.04/home/userName/development/projectName/node_modules/@chakra-ui/theme/dist/index")'.

**in Chrome console** 

> Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@chakra-ui_theme.js?v=720c7efb' does not provide an export named 'default'

**Workaround:**

`import chakraTheme from '@chakra-ui/theme'`
becomes
`import * as chakraTheme from '@chakra-ui/theme'`
and 
`const { Modal } = chakraTheme.components`
becomes
`const { Modal } = chakraTheme.theme.components`

After doing this i can use the Modal component but the ModalCloseButton's styling is off. fill color of the SVG is set to "currentColor" and it is missing some padding.
![chrome_EEWJhY2r4v](https://github.com/chakra-ui/chakra-ui/assets/9550131/06502a70-6c87-436e-a09b-6c7b315305f8)

When I use the regular ChakraProvider, the padding of the close button is correct, but the fill color is still missing. 
![chrome_SLX61JaJDT](https://github.com/chakra-ui/chakra-ui/assets/9550131/f3b22e12-c255-4fe2-89be-4de42f116087)

I assume the missing color is due to me not using the Chakra theme? I can fix it by adding an inline style to the ModalCloseButton tag.

### Chakra UI Version

2.8.1

### Browser

118.0.5993.120 

### Operating System

- [ ] macOS
- [X] Windows
- [X] Linux

### Additional Information

OS: Windows running on WSL 2 Ubuntu 18

React: 18.0.0
Typescript: 4.5.4
Vite: 4.4.9
@vitejs/plugin-react: 1.0.7

**Vite config:**
```
export default defineConfig({
    plugins: [react(), eslintPlugin({
        failOnWarning: false,
        failOnError: false
    })],
    server: {
        host: params.HOST,
        port: 3000,
        watch: {
            usePolling: true
        }
    },
    build: {
        manifest: true,
    }
});
```

**Comment by TylerAPfledderer** [comment]
Hey @Diligentia-Uitgeverij!

A couple of points here for you:
- I do see that the import example for `@chakra-ui/theme` is incorrect because `theme` is a named import.
So the example should actually be
```ts
import { theme as chakraTheme } from "@chakra-ui/theme"
```
Note that importing from `@chakra-ui/theme` is only by example. And as stated you can simply import the `theme` from `@chakra-ui/react` (as opposed to importing `baseTheme` which is not what you want).
- As to the styling of `ModalCloseButton`: it is consuming the styles for `CloseButton` so if you want the default theme for this button, you need to add the `CloseButton` object to the component list.

I made a [version of your minimal repo](https://codesandbox.io/s/recursing-diffie-m5z69l?file=/src/index.tsx) showing these changes. 😄

**Comment by Diligentia-Uitgeverij** [comment]
Hey @TylerAPfledderer! Thank you for your clear answer. 

I do want to point out that I followed the documentation provided here: [https://chakra-ui.com/getting-started#chakrabaseprovider](https://chakra-ui.com/getting-started#chakrabaseprovider). Where the import appears to be incorrect. Maybe it could be changed to what you have provided in your answer.

After having a look at your repo I conclude that everything could just have been imported from '@chakra-ui/react' as it also includes the theme? 

Thanks again.

**Comment by TylerAPfledderer** [comment]
> Hey @TylerAPfledderer! Thank you for your clear answer. 
> 
> I do want to point out that I followed the documentation provided here: [https://chakra-ui.com/getting-started#chakrabaseprovider](https://chakra-ui.com/getting-started#chakrabaseprovider). Where the import appears to be incorrect. Maybe it could be changed to what you have provided in your answer.
> 
> After having a look at your repo I conclude that everything could just have been imported from '@chakra-ui/react' as it also includes the theme? 
> 
> Thanks again.
> 
> 

Yes, that is all correct. I will look at putting up a PR to make this more clear.

You got it! 🤘
