### ISSUE TITLE
Guides Ideas

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#811]
As part of the 1.0 release, we're revamping the Chakra UI website. One of the new website features is the "Guides" section, where we want to build a platform that makes it as effortless as possible for community members to write and publish Chakra-related guides. 

As part of this effort, I'd like to start a thread of guides ideas that community members could use to get started. 

# Ideas

- Create custom implementations of Chakra components using the new `useX` hooks
  - `useAccordion`/`useAccordionItem`
  - `useCheckbox`/`useCheckboxGroup`
  - `useRadio`
  - `useSlider`
- Set up and manage color modes
- Configure global app styles using `theme.styles.global`
- [x] Style a gatsby project with Chakra using `gatsby-plugin-chakra-ui` #907 
- Add Chakra to a `create-react-app` application

**Comment by balibebas** [comment]
Tossing a couple more in the bag:

- Style MDX content with `MDXProvider`. ([reference](https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/?=mdx#mdxprovider)
- Style MDX content using theme `styles` section like Theme UI ([reference](https://theme-ui.com/styling-mdx)).

**Comment by balibebas** [comment]
Tossing a couple more in the bag:

- Style MDX content with `MDXProvider` ([reference](https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/?=mdx#mdxprovider)).
- Style MDX content using theme `styles` section like Theme UI ([reference](https://theme-ui.com/styling-mdx)).

**Comment by segunadebayo** [comment]
More ideas:
- Setup Chakra in Next.js
- Setup Chakra in Gatsby
- Theming compound components (like Tabs, Menu, etc.)
- Theming custom components
- Using Chakra with Reakit or Reach UI
- Moving from Theme UI
- Moving from Tailwind

**Comment by with-heart** [comment]
- Use Chakra with Storybook
- Use Chakra with `@storybook/addon-docs` (MDX)

**Comment by glenmcrae** [comment]
Throwing another one out there
- Using Chakra `Grid` and `Flexbox` components to create a lightweight and super simple landing page and a dashboard(y) kinda view

**Comment by with-heart** [comment]
- Building custom components that play well with Chakra and a11y (suggested in #1495)

**Comment by with-heart** [comment]
I've taken a number of the guides ideas and added them as cards in the [Improve third-party integrations documentation project](https://github.com/chakra-ui/chakra-ui/projects/2).

**Comment by balibebas** [comment]
That's great. I wasn't able to comment on the MDX card but since I proposed the guide I'll drop a link to some sample implementation here in another Chakra-based Gatsby boilerplate I open sourced: https://git.habd.as/comfusion/gatsby-starter-shopify-headless-commerce/src/branch/master/src/components/MDXLayout.tsx

**Comment by segunadebayo** [comment]
@with-heart, let's work with the ideas already listed here.

We can close this out for now.
