### ISSUE TITLE
Error in `ChakraProviderDecorator`

### ISSUE THREAD

**Issue by neddy34** [chakra-ui/chakra-ui#8142]
### Description

since `chakraTheme` variable is possibly `undefined` [here](
https://github.com/chakra-ui/chakra-ui/blame/main/tooling/storybook-addon/src/ChakraProviderDecorator.tsx#L14)
accessing its `direction` field might couse error.

### Link to Reproduction

https://github.com/chakra-ui/chakra-ui/blame/main/tooling/storybook-addon/src/ChakraProviderDecorator.tsx#L13-L18

### Steps to reproduce

No need to reproduce since this issue is related to syntax

### Chakra UI Version

5.1.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
