### ISSUE TITLE
[BUG]: [Menu] MenuList and MenuItem auto trigger onFocus function

### ISSUE THREAD

**Issue by rubysky17** [chakra-ui/chakra-ui#8148]
### Description

I'm using  chakraUI and combine 2 components: Menu and Input to create my custom AutoComplete. The action i want to do clicking a Input and the Menu will open and show all result with search key type from user. And when i show menu below input, the trigger focus mouse always stay in input component. Move mouse to the <MenuList /> or <MenuItem /> my focus on input dissappear. I see the function onFocus always trigger onMouseMove. 

### Link to Reproduction

https://codesandbox.io/p/sandbox/chakra-ui-menu-list-issue-forked-p8crc6?file=%2Fsrc%2Findex.js%3A19%2C12

### Steps to reproduce

1. Click on button to show menu
2. Hover to MenuItem or MenuList
3. see my console.log in codesandbox 

### Chakra UI Version

4.8.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is not a bug. The menu is built based on roving focus, so you should expect the onFocus handler to be called when you navigate the menu.

Please add some guards to your userland code to resolve this.

**Comment by Shahor** [comment]
> This is not a bug. The menu is built based on roving focus, so you should expect the onFocus handler to be called when you navigate the menu.
> 
> Please add some guards to your userland code to resolve this.

Hi @segunadebayo 👋🏽 

I'm currently facing the same issue and it's unclear to me how we could add userland code to resolve this. 

`Menu.Root` doesn't expose any way to change the focus trap behaviour and I don't see a way to hook into the underlying code doing the focus to prevent it from happening.

Would you have any pointers on this matter maybe?
