### ISSUE TITLE
useDisclosure() not a function

### ISSUE THREAD

**Issue by MVARUNREDDY8203** [chakra-ui/chakra-ui#8155]
### Description

I'm using a drawer component, it uses useDisclosure, which is not working and is throwing the error: 

Unhandled Runtime Error Error: (0 , chakra_ui_react__WEBPACK_IMPORTED_MODULE_2_.useDisclosure) is not a function

![image](https://github.com/chakra-ui/chakra-ui/assets/94187286/f3e4085c-1d6f-4454-9f28-ea5a96563609)

here is the code where im importing it

![image](https://github.com/chakra-ui/chakra-ui/assets/94187286/db932aed-747a-4062-8f84-6c0d90091cb3)

### Link to Reproduction

https://codesandbox.io/p/sandbox/young-thunder-33gq2j?file=%2Fsrc%2Findex.js%3A11%2C5

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

latest

### Browser

chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Its working properly on another project and a sandbox but this, I have tried re running the project, doesnt work, pls help

**Comment by FathZulfaAli** [comment]
same here, I was trying to make modal straight from chakra ui documentation

**Comment by NZMia** [comment]
same here

**Comment by MVARUNREDDY8203** [comment]
So I was using js previously when I was facing this error...
Now I'm using ts and what I think is happening is that there's some error while installing chakraUI, like go thru the steps carefully and include providers.tsx etc etc... when I installed carefully it works now...q

**Comment by allenhartwig** [comment]
If anyone else comes across this, the issue for me was the lack of `'use client'` declaration at the top of the file importing the component using `useDisclosure`.
