### ISSUE TITLE
"The type '{ emotionAlias: false; }' is not assignable to Type" Chakra UI Storybook Add-on Typescript error

### ISSUE THREAD

**Issue by prb567** [chakra-ui/chakra-ui#8156]
### Description

I'm following the chakra ui storybook official guide (https://chakra-ui.com/getting-started/with-storybook) and I have a critical error("The type '{ emotionAlias: false; }' is not assignable to Type"(...) when i try to update ".storybook\main.ts" file.
![Screenshot 2023-12-07 160930](https://github.com/chakra-ui/chakra-ui/assets/149665537/e4334ea2-8cc4-4fb3-9c80-3abfedc225c4)

### Link to Reproduction

#

### Chakra UI Version

2.8.1

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Stack:
    "@chakra-ui/storybook-addon": "^5.1.0",
    "@storybook/addon-essentials": "7.5.1",
    "@storybook/addon-interactions": "7.5.1",
    "@storybook/addon-links": "7.5.1",
    "@storybook/addon-onboarding": "1.0.8",
    "@storybook/blocks": "7.5.1",
    "@storybook/react": "7.5.1",
    "@storybook/react-vite": "7.5.1",
    "@storybook/testing-library": "0.2.2",
    "eslint-plugin-storybook": "^0.6.15",
    "storybook": "7.5.1",
    "vite": "^4.4.5",
    "vite-tsconfig-paths": "^4.2.1",

**Comment by averycpawelek** [comment]
@prb567 did you figure out a solution to this issue? I am facing the same problem

**Comment by prb567** [comment]
@averycpawelek Unfortunately no, I had to renounce to use Storybook in my current project.

**Comment by averycpawelek** [comment]
@prb567 I was able to work around this issue by removing the "@chakra-ui/storybook-addon" and writing a custom decorator to wrap all stories in the `ChakraProvider`. Here's what my `.storybook/preview.tsx` ended up looking like:

```
mport React from "react";

import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import type { Preview } from "@storybook/react";
import { YOUR_THEME_HERE } from "../src/themes";

const theme = extendTheme(YOUR_THEME_HERE);

const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
  decorators: [
    (Story) => (
      <ChakraProvider theme={theme} >
        <Story />
      </ChakraProvider>
    ),
  ],
};

export default preview;
```

This seems to allow Storybook to work with the Chakra theme without an issue.

**Comment by kingr** [comment]
> decorators: [
>     (Story) => (
>       <ChakraProvider theme={theme} >
>         <Story />
>       </ChakraProvider>
>     ),
>   ],

this worked for me thanks

**Comment by segunadebayo** [comment]
Closing based on https://github.com/chakra-ui/chakra-ui/issues/8156#issuecomment-1977404313
