### ISSUE TITLE
<MenuOptionGroup type="radio" /> has onChange type of string | string[]

### ISSUE THREAD

**Issue by jmahabal** [chakra-ui/chakra-ui#8157]
### Description

Hi! I had a question around expected behavior. 

I noticed in the [documentation](https://chakra-ui.com/docs/components/menu/props) for `MenuOptionGroup` that we're typing the value as `string[]`, which makes sense for when you can select multiple options with `type="checkbox`. In the case for `type="radio"` though, I'd expect these values to be `string` only.

<img width="820" alt="Screenshot 2023-12-07 at 10 41 22 AM" src="https://github.com/testing-library/jest-dom/assets/4358471/84baaebc-8bd7-4d4f-92bd-3730e8aa58bf">

In my code, I'm having to be extra defensive so I was curious about whether this was expected. I wasn't able to find much information online. 

```
<MenuOptionGroup
    type="radio"
    onChange={value => {
        // `value` is typed as `string | string[]` from Chakra but in our case
        // it should always be a string since the `type` is `radio` and not `checkbox`
        if (value instanceof Array) {
            setGrouping([value[0]]);
        } else if (value === undefined) {
            setGrouping([]);
        } else {
            setGrouping([value]);
        }
    }}
>
```

I can try to submit a PR for better typing if this is something that should change! Thanks.

### Link to Reproduction

https://codesandbox.io/p/sandbox/stupefied-bush-vxs4zx

### Steps to reproduce

Click the `MenuItem` and open the `console` to look at the logs. Notice that for the `MenuOptionGroup` with a `type="radio"` it's always a string and for `type="checkbox"` it's an array. 

As a result, I'd expect the return types to be smarter and inferred based on the `type` prop that's passed in.

### Chakra UI Version

2.8.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is a design constraint in v2 due to the type complexity from the `as` prop support. We're unable to combine it with other generic types.

Please cast this in your userland code instead.

Thanks for understanding
