### ISSUE TITLE
Add option to open drawer in component (right not open only in body)

### ISSUE THREAD

**Issue by suenot** [chakra-ui/chakra-ui#8158]
### Description

![telegram-cloud-photo-size-2-5444931767619409308-y](https://github.com/chakra-ui/chakra-ui/assets/1426876/1ba05ed8-b171-4bae-80f6-1df555245133)
Provide ability to pass drawer from body to some parent component. In this example it is widget.

### Problem Statement/Justification

Abitilty to create widgets with drawers.

### Proposed Solution or API

No ideas

**Comment by suenot** [comment]
I tried this:
```
  const wrapperRef = useRef(null);
  const bg = useColorModeValue('#fff', '#181818');

  return (
    <Box sx={{position: 'relative'}} ref={wrapperRef}>
      <Drawer placement="bottom" onClose={()=>{}} isOpen={true} portalProps={{containerRef: wrapperRef}}>
        <DrawerOverlay />
        <DrawerContent>
          <DrawerHeader borderBottomWidth='1px'>Basic Drawer</DrawerHeader>
          <DrawerBody>
            <p>Some contents...</p>
            <p>Some contents...</p>
            <p>Some contents...</p>
          </DrawerBody>
        </DrawerContent>
      </Drawer>
    </Box>
  );
```

not helped

**Comment by suenot** [comment]
https://github.com/chakra-ui/chakra-ui/issues/7214

**Comment by suenot** [comment]
Example what I want you can find in Naive vue framework: https://www.naiveui.com/en-US/dark/components/drawer#target.vue
<img width="542" alt="image" src="https://github.com/chakra-ui/chakra-ui/assets/1426876/33ceaba4-f6d0-4864-8688-c18cb28cd88d">

**Comment by segunadebayo** [comment]
You can pass the `portalProps.containerRef` prop to the drawer to fix this.
