### ISSUE TITLE
Missing container at table theme parts

### ISSUE THREAD

**Issue by gifaeriyanto** [chakra-ui/chakra-ui#8166]
### Description

I wanted to customize TableContainer like changing the border-radius from the theme, but currently, it's not supported yet.

### Problem Statement/Justification

Can't custom TableContainer form theme

### Proposed Solution or API

Add container as table part in theme

**Comment by CLLane** [comment]
Ill give this a third, working to theme both a `TableContainer` as well as an `InputGroup` neither will take a typical `baseStyle` override.  Seems to be a limit placed on container-components. 

Linking this [old thread](https://github.com/chakra-ui/chakra-ui/issues/5252) as it lead me here and may give some context to Chakra's thoughts.

**Comment by segunadebayo** [comment]
This is by design. The table container is only an overflow wrapper to make the table scrollable. It is excluded from the theme parts.

Please pass style props directly to it to style it
