### ISSUE TITLE
The auto-suggested value for some property is not working.

### ISSUE THREAD

**Issue by lucphamvan** [chakra-ui/chakra-ui#8169]
### Description

The auto-suggested value for some property is not working.

- size
- variant
- colorSchema

### Link to Reproduction

https://codesandbox.io/p/sandbox/chakra-button-demo-gnpwgj-gnpwgj

### Steps to reproduce

![Untitled](https://github.com/chakra-ui/chakra-ui/assets/61300156/6caa5853-6c32-40b9-842c-e5c10ffb25da)

### Chakra UI Version

2.8.2

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by wontondon** [comment]
I have observed this behavior as well on macos. For me it appears to be any of the chakra tokens aren't really shown in autocomplete.

**Comment by lucphamvan** [comment]
yes, that's right, all property of chakra tokens not work in autocomplete. No any update to fix this ?

**Comment by LucasCavalheri** [comment]
This issue needs more attention!

**Comment by pedrocarlos-ti** [comment]
Same here 😅

I was so close to open a new Issue when I saw this one.

Here, I tried with a few different components and didn't show the autocomplete as well ( even in codesandbox).

![image](https://github.com/chakra-ui/chakra-ui/assets/18473317/a6b7400c-4ea3-4291-89ec-27157770f57f)

But in the docs says:
![image](https://github.com/chakra-ui/chakra-ui/assets/18473317/47a0fc13-d6f7-4572-940e-c46a4204f08f)


https://codesandbox.io/p/sandbox/hardcore-bessie-6r4dp7

If someone knows how to solve, it would be amazing!!! Develop without autocomplete is a pain.

**Comment by Harshitazz** [comment]
facing the similar issue.

**Comment by nerdjfpb** [comment]
Happening with me too, let me know if there is any solution of it!

**Comment by rossanodr** [comment]
> Happening with me too, let me know if there is any solution of it!

I've rolled back to 2.8.1 version. Fixed for me

**Comment by lucphamvan** [comment]
Hello, team still not fix this problem ? version 2.8.1 still not work guy

**Comment by lucphamvan** [comment]
it's over one year, why team not fix this problem, It still happen in version 3. All chakra token property not work

**Comment by segunadebayo** [comment]
This is now fixed in the latest v2 version
