### ISSUE TITLE
Issues hard to debug

### ISSUE THREAD

**Issue by villesau** [chakra-ui/chakra-ui#8177]
### Description

I'm getting `Error: React.Children.only expected to receive a single React element child.`

However, the issue comes from: `node_modules/@chakra-ui/layout/dist/chunk-ZVFRDZZY.mjs (14:24)`

Suggestion: Provide sane filenames for debugging purposes. In this case the filename should point to `aspect-ratio.tsx`

### Link to Reproduction

-

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.8.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
https://github.com/chakra-ui/chakra-ui/pull/8153

This is fixed in the above PR. Will cut a new release shortly

**Comment by villesau** [comment]
Nice, sounds great! :)
