### ISSUE TITLE
Tooltip label not working properly with hasArrow on Safari

### ISSUE THREAD

**Issue by gregdolby** [chakra-ui/chakra-ui#8188]
### Description

When you use Tooltip with hasArrow on Safari the tooltip displays vertial then switches to horizontal

### Link to Reproduction

https://codesandbox.io/p/sandbox/jovial-cerf-5vjjrr?file=%2Fpackage.json%3A8%2C26-8%2C32

### Steps to reproduce

1. Go to https://codesandbox.io/p/sandbox/jovial-cerf-5vjjrr?file=%2Fpackage.json%3A8%2C26-8%2C32
2. Click on mouseover the button
3. See tooltip change orientation on mouseover

### Chakra UI Version

2.82

### Browser

Safari

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Remove hasArrow prop from tooltip and it works fine

**Comment by carlosberti** [comment]
I'm facing the same problem here. The weirdest part is that it only happens on my nextjs project, not sure if there is a connection

**Comment by cameronevans** [comment]
in my experience this is an issue when the tooltip is embedded. in the code sandbox example if you open the preview in a separate tab or locally it works fine. there must be an issue with the preview iframe or in my case a shadow dom.

can reproduce it in the example outside of its preview iframe by changing the root
```tsx
const root = createRoot(rootElement.attachShadow({mode: 'open'}));
```

however adding an `aria-label` prop fixes it as well but i'm not sure why

**Comment by segunadebayo** [comment]
Closing based on https://github.com/chakra-ui/chakra-ui/issues/8188#issuecomment-2331216028

Please include an aria-label when possible.
