### ISSUE TITLE
Request to support library in Svelte

### ISSUE THREAD

**Issue by iamyuu** [chakra-ui/chakra-ui#819]
Because this library has achieved great popularity. And currently the UI library for [Svelte](https://svelte.dev/) still a little a bit (I think), extending it to [Svelte](https://svelte.dev/) would be great.

**Comment by balibebas** [comment]
Right now the maintainers are working on a TypeScript conversion and releasing a 1.0. I see Svelte is not using React, which this library is based upon. It would seem someone would need to do a complete rewrite of the codebase to make it work with Svelte. Perhaps that's not a task someone working with Svente should take up?

**Comment by balibebas** [comment]
Right now the maintainers are working on a TypeScript conversion and releasing a 1.0. I see Svelte is not using React, which this library is based upon. It would seem someone would need to do a complete rewrite of the codebase to make it work with Svelte. Perhaps that's a task someone working with Svente should take up instead?

**Comment by balibebas** [comment]
Right now the maintainers are working on a TypeScript conversion and releasing a 1.0. I see Svelte is not using React, which this library is based upon. It would seem someone would need to do a complete rewrite of the codebase to make it work with Svelte. Perhaps that's a task someone working with Svelte should take up instead?

**Comment by balibebas** [comment]
Selamat malam, kak. Right now the maintainers are working on a TypeScript conversion and releasing a 1.0. I see Svelte is not using React, which this library is based upon. It would seem someone would need to do a complete rewrite of the codebase to make it work with Svelte. Perhaps that's a task someone working with Svelte should take up instead?

**Comment by with-heart** [comment]
@codebender828 recently implemented Chakra in Vue. He might be able to give you more details about his process. Svelte support would definitely be cool :)

**Comment by iamyuu** [comment]
Yes, I think so, @balibebas. I don't have time with that (but I'll try, can't promise with it), I hope someone can work on it.

**Comment by segunadebayo** [comment]
Thanks for this @iamyuu. This isn't the focus of the team for now so I'm going to close it out.

**Comment by 11reed** [comment]
Any updates on this?

**Comment by xpluscal** [comment]
That would be super awesome.

**Comment by ranjan-purbey** [comment]
Would any of the maintainers be interested in guiding someone to port the library to svelte? I think a lot of people (including me) would be willing to contribute

**Comment by iamyuu** [comment]
The idea behind `<Box />` component is to pass the rest props into styled system and CSS in js

Check out the example on svelte [repl](https://svelte.dev/repl/ae2973570cf74857b392d86a6aabb0cb)

**Comment by elcharitas** [comment]
@iamyuu I published a post about the implementation of Chakra UI in svelte. Do check it out here https://blog.elcharitas.dev/announcing-chakra-ui-svelte

**Comment by h4ckedneko** [comment]
Ark recently announced its support for Svelte. It would be awesome for Chakra UI to support it too.
