### ISSUE TITLE
Chakra tokens fail when importing NextJS next/fonts/google

### ISSUE THREAD

**Issue by herrethan** [chakra-ui/chakra-ui#8190]
### Description

I'm not sure if this is an issue with the NextJS file structure in `next/fonts/google` or with the Chakra CLI itself, or its another cjs vs ESM issue, but one would assume this would be possible when creating custom theme fonts:

```ts
// theme/fonts.ts

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const fonts = {
  body: `${inter.style.fontFamily}, sans-serif`,
};
```

But we get this fun ESBuild error that crashes the CLI:
```bash
▲ [WARNING] Import "Inter" will always be undefined because the file "node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/font/google/index.js" has no exports [import-is-undefined]
```

However, the app and build work perfectly fine. It's only the tokens that fail. 
I realize the docs recommend the current workaround of creating your own `:root { --font: ... }` vars inside `_app.tsx`, which works, but I'd be curious to hear if the team has any feedback or whether this might just be a temporary issue.

### Link to Reproduction

NA

### Steps to reproduce

Try to use any fonts from NextJs `next/fonts/google` directly inside a theme and export theme typings with `chakra-cli tokens`.

Version info:
```
"@chakra-ui/cli": "^2.4.1",
"@chakra-ui/next-js": "^2.2.0",
"@chakra-ui/react": "^2.8.2",
"@chakra-ui/styled-system": "^2.9.2",
"@chakra-ui/theme-tools": "^2.1.2",
"next": "14.0.4",
```

### Chakra UI Version

2.8.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by sorenhusted** [comment]
I'm having the exact same issue. Hoping for a fix/work-around

**Comment by segunadebayo** [comment]
This is because the Chakra CLI cannot resolve the imported font.

Please use the css variable format instead as started in the Next.js docs.
![CleanShot 2024-10-03 at 18 34 32@2x](https://github.com/user-attachments/assets/93c68f0f-b522-4b1d-bf35-bc55b7fb7807)

**Comment by mergd** [comment]
![Image](https://github.com/user-attachments/assets/18f27262-a846-486e-9f09-cb4a96c5bc00)


Still running into issues here – I'm using the css vars approach.

**Comment by shashwa7-dev** [comment]
> ![Image](https://github.com/user-attachments/assets/18f27262-a846-486e-9f09-cb4a96c5bc00)
> 
> Still running into issues here – I'm using the css vars approach.

![Image](https://github.com/user-attachments/assets/9a88f853-955c-46e7-a511-e42230b400b3)

apparently just attach font class vars in html tag instead of the body tag. It worked for me. also its mention in chakra's official font import doc.

https://www.chakra-ui.com/docs/get-started/frameworks/next-app
