### ISSUE TITLE
[NumberInput] Incorrect Bounds

### ISSUE THREAD

**Issue by zandoh** [chakra-ui/chakra-ui#82]
When using the NumberInput component with a max value, the input field allows a user to type in a number over the max

Additionally for example a max is set to 25 and a user types in 26 then uses ctrl + down the NumberInput displays 25.9 which is over the max

**Comment by segunadebayo** [comment]
Hi @zandoh,

Thanks for catching this bug. I've resolved it and will release a patch soon.

The expected result is to take the value back to the `max`, correct?

**Comment by zandoh** [comment]
@segunadebayo yep! Taking the user back to the max value would be the expected functionality

**Comment by segunadebayo** [comment]
I'm closing this now because it has been resolved. I'll publish a patch shortly.
