### ISSUE TITLE
useBreakpointValue returns 'window is not defined' build error on NextJS App Router

### ISSUE THREAD

**Issue by bwcr** [chakra-ui/chakra-ui#8200]
### Description

The documentation recommends using useBreakpointValue and setting SSR to false to resolve an issue with incorrect media queries on first launch. However, when I tried to implement it on the Next.JS app router, the build returned an error stating that "window is not defined". I am hoping that this issue will be fixed soon.
![image](https://github.com/chakra-ui/chakra-ui/assets/50513707/8d6c2aad-f2fa-464a-b9c2-a3d0b08b5f74)
![image](https://github.com/chakra-ui/chakra-ui/assets/50513707/75f8e43d-1538-41ce-83fe-0b349dd67af6)

I haven't had a chance to reproduce the error on CodeSandbox, but it seems obvious. Perhaps others can replicate it on their Next.js App Router build.

### Link to Reproduction

https://codesandbox.io/p/devbox/chakra-ui-next-js-app-router-forked-6kzrrs

### Steps to reproduce

When attempting to build the project using 'npm run build' or 'yarn build', the build fails and returns a 'window is not defined' error, causing the build to abort.

### Chakra UI Version

2.8.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
The reproduction you attached is incorrect.

- Set `ssr: true`
- Add `use client` to the top of your file where this hook is used
- Consider switching to style props (with display none) to change the layout based on breakpoints.

**Comment by DavidCodesDev** [comment]
Will this ever be fixed though? That hook is supposed to work on server-side

**Comment by jacob-ndconnect** [comment]
Same thing here. I've seen to either use ssr: false to solve the flickering/re-rendering issue, or use ssr:true so I can actually build and deploy it. I'm using NextJS exported statically, so all of my components are specified "use client", though I still have this issue.

**Comment by iweurman** [comment]
This fixed it for me:
`const breakpoint = useBreakpoint({
    ssr: typeof window !== "undefined" ? false : undefined,
  })`
