### ISSUE TITLE
[BUG] Using custom variant on Button, when set isDisabled, style conflict problem

### ISSUE THREAD

**Issue by MoEikei** [chakra-ui/chakra-ui#8217]
### Description

When i add a custom variant on Button, then apply it on the component, and i set the isDisabled property too, after set all these, hover on this button, the hover style changes to all white, you cant see anything.

i use the example from chakra ui official website to explain this issue:
<img width="1094" alt="image" src="https://github.com/chakra-ui/chakra-ui/assets/156629154/824dff9a-c4b1-4600-a433-b87fb074a6a2">

I add this isDisabled property here, then the showcase on the top change to this blank when i hover it
<img width="767" alt="image" src="https://github.com/chakra-ui/chakra-ui/assets/156629154/c3cead3a-0cf2-4b78-b3fd-279803d6523b">

### Link to Reproduction

https://codesandbox.io/p/sandbox/sandpack-project-s5tq85?file=%2FApp.tsx%3A12%2C38

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

"@chakra-ui/react": "^2.8.2",

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is a design flaw in the button component due the styles defined here:
https://github.com/chakra-ui/chakra-ui/blob/v2/packages/theme/src/components/button.ts#L21

I recommend adding the `!important` to the hover styles or styling the disabled state as well.

```tsx
const customVariant = defineStyle((props) => {
  const { colorScheme: c } = props;
  return {
   // ...
    _hover: {
      transform: "scale(1.05, 1.05)",
      bg: `${c}.600!`,

      _dark: {
        bg: `${c}.300!`,
      },
    },
  };
});
```
