### ISSUE TITLE
Select component's isReadOnly doesn't do anything

### ISSUE THREAD

**Issue by paramtd** [chakra-ui/chakra-ui#8233]
### Description

I expected the Select to not be editable when `isReadOnly={true}`

### Link to Reproduction

https://codesandbox.io/p/sandbox/sharp-voice-pc3tn8

### Steps to reproduce

1. Go to src/index.js
2. Note that Select has isReadOnly property
3. Click on Select and change it

### Chakra UI Version

2.8.2

### Browser

Arc

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by DeveloperRaj** [comment]
@paramtd select elements do not support readOnly attribute. You should be using disabled attribute.

**Comment by ktpi2000** [comment]
https://chakra-ui.com/docs/components/select/props

The `isReadOnly` prop seems to be applicable in the Document.

Should I initiate a Pull Request to amend the description?

**Comment by segunadebayo** [comment]
This is by design. A native select cannot be made to be read only.
