### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node', when Button has `isLoading` set to true, and google chrome translate is translating

### ISSUE THREAD

**Issue by elboletaire** [chakra-ui/chakra-ui#8238]
### Description

The app crashes when a Button component gets `isLoading` set to true, and you're running google chrome with its translation feature translating.

There is an open issue in react about this, but considering react never responded and the issue was created in 2019.... https://github.com/facebook/react/issues/17256

I identified this issue exclusively in the Button component (also using `chakra.button`) when `isLoading` is set to true, but it may happen in other components, considering it is related to react fragments and google chrome's translate feature.

### Link to Reproduction

https://codesandbox.io/p/devbox/25kfq2

### Steps to reproduce

1. Open Google Chrome (only reproducible in this browser, as far as I've seen)
2. Go to the provided codesandbox url
3. Copy-paste the URL of the embedded browser to your google-chrome, since the embedded browser won't get translated by google chrome. As of the time of this writing, that url is: https://25kfq2-5173.csb.app/
4. Ensure google chrome translate is enabled and is working, so you don't see the button as "click me", but in any other language
5. Click the button (and check the console, since it will just disappear)

### Chakra UI Version

2.8.2

### Browser

Google Chrome 121.0.6167.86

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

Note this issue is at least 3 years old, so the google chrome version is not really that important (also, the referenced facebook issue speaks of other cases, like google chrome extensions, although I could only reproduce it using their integrated translate feature while translating).

**Comment by elboletaire** [comment]
I forgot to mention: changing [this fragment](https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/src/button/button.tsx#L134) with a `span` or a `div` seems to do the trick... but I didn't want to open a PR changing a fragment for a span or a div for obvious reasons...

**Comment by EmanuelaGr** [comment]
Hi there, any follow-up on this issue? We are having the same issue and I need a fix for this. Thank you

**Comment by elboletaire** [comment]
> Hi there, any follow-up on this issue? We are having the same issue and I need a fix for this. Thank you

Not a fix, but as a workaround we did create our own button version (copy-pasting it from chakra source) and use that instead of chakra one.. 🤷🏼‍♀️ https://github.com/vocdoni/ui-components/blob/main/packages/chakra-components/src/components/layout/Button.tsx

**Comment by segunadebayo** [comment]
Added support for a new `shouldWrapChildren` prop that will help prevent this.

Will release a minor shortly.

**Comment by elboletaire** [comment]
> Added support for a new `shouldWrapChildren` prop that will help prevent this.
> 
> Will release a minor shortly.

A minor for version 2? Or will be only for the `next` version?

**Comment by elboletaire** [comment]
@segunadebayo this fix does not work entirely well. Since it's only being wrapped when it's loading, when switching to not loading the app still crashes with the exact same error.

Using chakra v2.10.7	

You can reproduce it with this codesandbox (remember to open the preview on a custom tab, otherwise the translation does not work), which is using latest v2 version:
https://codesandbox.io/p/devbox/practical-austin-r8mgqr?file=%2Fsrc%2FApp.tsx

I'd reopen the issue, but I got no perms

**Comment by preveenraj** [comment]
The issue got fixed for me when I wrapped the loadingText with span.

```
<Button
loadingText={<span>{loadingTextFromParent}</span>}
...
/>
```
