### ISSUE TITLE
Components are unstyled when rendered in an iframe possibly due to emotion issue

### ISSUE THREAD

**Issue by alexdanilowicz** [chakra-ui/chakra-ui#8241]
### Description

When I render Chakra UI React in an iframe, I expect it to be styled by default when wrapped in a ChakraProvider, but instead it's unstyled - it appears because the <style data-emotion > tags are empty. 

I recognize this is an non-standard when of rendering Chakra components because its deps are not installed in the iframe directly - it's just Chakra. But this was working before in early-November. Considering everything is pinned, I'm not sure what could have changed, but perhaps the Chakra contributors have an idea of what might have changed between now and November? 

Thank you very much and happy to provide anything else. Very appreciative of the Charka ecosystem and this amazing project.

### Link to Reproduction

https://codesandbox.io/p/sandbox/nervous-kepler-28mgzf?file=%2Fsrc%2FApp.tsx

### Steps to reproduce

The issue is visible in the code sandbox by default. 

<img width="1113" alt="CleanShot 2024-01-28 at 20 17 29@2x" src="https://github.com/chakra-ui/chakra-ui/assets/29822597/90a78d01-862a-4b91-acd6-88696075cdd0">

### Chakra UI Version

2.8.1

### Browser

Google Chrome 

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

1. This screenshot demonstrates why I think the fact that the empty <style data-emotion /> tags are the cause of the issue. On the left is the iframe reproduction. On the right is a next.js app that renders the same code: a button with colorScheme='blue'.

![CleanShot 2024-01-26 at 22 17 48@2x (2)](https://github.com/chakra-ui/chakra-ui/assets/29822597/b88f3874-c49d-4d4e-82e3-9a996bbf3e8a)

2. In the reproduction, it's interesting, on chakra version 2.8.2 the button color becomes white.
<img width="1366" alt="CleanShot 2024-01-28 at 20 20 15@2x" src="https://github.com/chakra-ui/chakra-ui/assets/29822597/7e0a139c-2bf2-4705-be53-49c96fbe1d20">

**Comment by benmisch** [comment]
Encountering this issue as well and I've also isolated it to the emotion cache. Using other theme-related props like `size` or `variant` doesn't work either. `isLoading` does work however, narrowing this down to a theming/css generation issue.  Current hunch is that it's either a wrong place or wrong timing situation. Maybe the generated css class is getting written to the wrong container. Or it's getting overwritten. Or it's trying to write too early.

**Comment by segunadebayo** [comment]
I recommend following this article to learn how to work emotion in an iframe.
https://theme-ui.com/guides/custom-cache-provider

This happens because emotion uses the `document.head` to append style tags. The "head" instance is different for an iframe, so it doesn't work.
