### ISSUE TITLE
Dynamic tab list unmounts and remounts panels when their position in array changes

### ISSUE THREAD

**Issue by dwillett** [chakra-ui/chakra-ui#8248]
### Description

When I render a dynamic list of tab panels and I trigger removal of an item in the list, I expect the remaining tab panels and children to not be remounted. 

```typescript
 const children = validChildren.map((child, index) =>
    createElement(
      TabPanelProvider,
      {
        key: index,
        value: {
          isSelected: index === selectedIndex,
          id: makeTabPanelId(id, index),
          tabId: makeTabId(id, index),
          selectedIndex,
        },
      },
      child,
    ),
  )
```
Because the key provided to the wrapping TabPanelProvider is based on the array index, it seems there's no means by which the children can provide a key to stay stable and avoid being unmounted when the list changes.

### Link to Reproduction

https://codesandbox.io/p/sandbox/sleepy-drake-rhj833

### Steps to reproduce

1. Go to https://codesandbox.io/p/sandbox/sleepy-drake-rhj833
2. Open devtools
3. Click on close button in Tab 2
4. See console log messages for unmounts of Tab 2 as well as Tab 3 (due to array position change)

### Chakra UI Version

2.8.2

### Browser

Google Chrome 120.0.6099.216

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

It feels like the key prop for the tab panel should be used in some way to keep the wrapping Provider component stable and avoid the unmount / remount.

**Comment by Henriquesoto92** [comment]
I have a similar problem, when deleting a tab, the input value inside the tab does not reset the values. I'll try to do a test here to show you.

**Comment by segunadebayo** [comment]
I just pushed a fix for this so that TabPanel can use the custom `key` (if provided).

We'll release an update shortly. If the issue persists after upgrading, I'll re-open it.
