### ISSUE TITLE
Invalid state not applying to InputGroup -> InputRightElement

### ISSUE THREAD

**Issue by mikestecker** [chakra-ui/chakra-ui#8251]
### Description

When I try and add pseudo styles to the `element`, none of them seem to be applying, namely the `_invalid` state. I'd like to change my icon color alongside the input border color but it doesn't seem to work.

<img width="602" alt="Screenshot 2024-02-02 at 9 51 01 AM" src="https://github.com/chakra-ui/chakra-ui/assets/407465/d19f7661-a681-4585-948f-0c7b6f23b320">
<img width="892" alt="Screenshot 2024-02-02 at 9 52 02 AM" src="https://github.com/chakra-ui/chakra-ui/assets/407465/16be46c8-3b49-477d-8eb0-0109d38367e0">

### Link to Reproduction

none

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.8.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by MatthewTang** [comment]
facing same issue here

I am currently using the option 1 mentioned in this [answer](https://github.com/chakra-ui/chakra-ui/issues/4887#issuecomment-949802344), ie setting the `errorBorderColor`, but that I couldn't set the `box-shadow`..

thanks in advance!

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Please re-open with a reproduction
