### ISSUE TITLE
Can not edit `<Input>` if it's inside `<Radio>`

### ISSUE THREAD

**Issue by ip10x** [chakra-ui/chakra-ui#8254]
### Description

Basically the title. The `<Input>` outside the `<Radio>` works as expected. But the `<Input>` inside is not editable. Curious as to why this is happening.

### Link to Reproduction

https://codesandbox.io/p/sandbox/compassionate-gagarin-njhy3n

### Steps to reproduce

See example in CodeSandbox

### Chakra UI Version

2.6.2

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I don’t recommend composing an input inside a radio. Consider solving this in your userland code.
