### ISSUE TITLE
Undo not work on Controlled Input inside Form Control 

### ISSUE THREAD

**Issue by marcusviniciusf** [chakra-ui/chakra-ui#8259]
### Description

In Safari, when I press CMD+Z(undo) to revert change when the field is controlled and it's wrapped by a FormControl, it does not work.

https://github.com/chakra-ui/chakra-ui/assets/17880908/d787d8ae-3569-4c74-9d63-057e419f3682

### Link to Reproduction

https://chakra-ui.com/docs/components/form-control/usage#error-message

### Steps to reproduce

1. Open Safari
2. Go to [Chakra UI FormControl example](https://chakra-ui.com/docs/components/form-control/usage#error-message)
3. Make any change in the email input
4. Blur the field
5. Try to undo the changes

### Chakra UI Version

2.8.2

### Browser

Safari

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is not Chakra UI issue since we don’t do anything with the native input element.

Kindly solve this in the userland code

**Comment by marcusviniciusf** [comment]
@segunadebayo 
The problem is not the native input element, it's the FormControl. It's preventing the undo behavior from the input element.
You can check by yourself here:
[Sandbox](https://codesandbox.io/p/devbox/chakra-form-control-issue-n6nkvc)
