### ISSUE TITLE
Unable to style SelectField

### ISSUE THREAD

**Issue by isBatak** [chakra-ui/chakra-ui#8260]
### Description

I have a feeling that `layoutProps` should be spread onto `SelectField` https://github.com/chakra-ui/chakra-ui/blob/09696a98b199280e194be9d3418488cb22860b57/packages/components/src/select/select.tsx#L116

`{...rootProps}` already covers the case for styling wrapper element.

### Problem Statement/Justification

Can't add padding to `SelectField` 
```jsx
<FormControl>
  <FormLabel>Label</FormLabel>
  <InputGroup>
	  <InputLeftElement>
		  <Icon/>
	  </InputLeftElement>
	  <Select pl={10}> // I want to add padding to the <select> element not the wrapper 
	      <option value="1">
		      Some option
	      </option>
	  </Select>
  </InputGroup>
</FormControl>
```

### Proposed Solution or API

Spread `layoutProps` onto `SelectField`

**Comment by segunadebayo** [comment]
This would be a breaking change. I recommend using a selector to style the select field via the sx prop
