### ISSUE TITLE
Controlled radio and Select cannot be cleared

### ISSUE THREAD

**Issue by NeleRober** [chakra-ui/chakra-ui#8262]
### Description

When using a controlled radio input or select input, the parent can clear the value of the input, but it stays visually selected

### Link to Reproduction

[Sandbox](https://codesandbox.io/p/sandbox/wandering-architecture-mxlprh?file=%2FApp.tsx%3A9%2C28&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls93dnro00073b6k1olgrnl9%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls93dnro00033b6kypa2wv7c%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls93dnro00043b6kalpaszzs%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls93dnro00063b6karrhr4g7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls93dnro00033b6kypa2wv7c%2522%253A%257B%2522id%2522%253A%2522cls93dnro00033b6kypa2wv7c%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls93ei9n00523b6kr5nzlfwu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A26%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A32%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clsbrar9k00023b6kxjzj8b7y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A28%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A28%257D%255D%252C%2522filepath%2522%253A%2522%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsbrar9k00023b6kxjzj8b7y%2522%257D%252C%2522cls93dnro00063b6karrhr4g7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls93dnro00053b6k56hy4q8j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls93dnro00063b6karrhr4g7%2522%252C%2522activeTabId%2522%253A%2522cls93dnro00053b6k56hy4q8j%2522%257D%252C%2522cls93dnro00043b6kalpaszzs%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls93dnro00043b6kalpaszzs%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Go to [the Sandbox implementation](https://codesandbox.io/p/sandbox/wandering-architecture-mxlprh?file=%2FApp.tsx%3A9%2C28&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls93dnro00073b6k1olgrnl9%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls93dnro00033b6kypa2wv7c%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls93dnro00043b6kalpaszzs%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls93dnro00063b6karrhr4g7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls93dnro00033b6kypa2wv7c%2522%253A%257B%2522id%2522%253A%2522cls93dnro00033b6kypa2wv7c%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls93ei9n00523b6kr5nzlfwu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A26%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A32%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clsbrar9k00023b6kxjzj8b7y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A28%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A28%257D%255D%252C%2522filepath%2522%253A%2522%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsbrar9k00023b6kxjzj8b7y%2522%257D%252C%2522cls93dnro00063b6karrhr4g7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls93dnro00053b6k56hy4q8j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls93dnro00063b6karrhr4g7%2522%252C%2522activeTabId%2522%253A%2522cls93dnro00053b6k56hy4q8j%2522%257D%252C%2522cls93dnro00043b6kalpaszzs%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls93dnro00043b6kalpaszzs%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
2. Follow the steps described in the scenario's
3. You will see that the parents state **clears the "selectedOption"**, but that the controlled radio and select **still show** the old value as **selected** (or in scenario 2 even the previous old value)

Are we missing something in the setup of our controlled radio or select?

Screenshot: see the selectedOption at the bottom vs the selected values in the radio and select

<img width="321" alt="image" src="https://github.com/chakra-ui/chakra-ui/assets/67055677/94c8402b-43f1-4014-960b-67bf21427f4c">

Video: see the selectedOption at the bottom vs the selected values in the radio and select
https://github.com/chakra-ui/chakra-ui/assets/67055677/4662f723-2059-405c-9dba-0a2db0d25e62

### Chakra UI Version

1.8.9

### Browser

Google Chrome 121

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

We bumped into this issue when trying to disable an option. When disabling it, we also wanted to clear it. However, it didn't seem to get cleared. Initially, we thought the issue was due to the fact that we were disabling ànd clearing the option at the same time, but that doesn't seem to be the case. (hence the "disable and clear C" button in the code example)

**Comment by ChloeLo27** [comment]
I too also run into the same problem.  I need an option to clear the radio group selection, but getting the `setValue` function from `useRadioGroup` doesn't select it on the UI level.  If I read the `value` from the `useRadioGroup` hook it's an empty value alright, but UI wise it's not reflecting that underlying change.

**Comment by segunadebayo** [comment]
Please use an empty value or null to clear the selected value

`setSelectedOption("")`
