### ISSUE TITLE
Form Control Input not undo in Safari

### ISSUE THREAD

**Issue by marcusviniciusf** [chakra-ui/chakra-ui#8265]
### Description

When I create an controlled input inside a <FormControl> and try to undo the change, it doesn't not work. If it's outside FormControl, it works fine. 
In Safari

### Link to Reproduction

https://codesandbox.io/p/devbox/chakra-form-control-issue-n6nkvc

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.8.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @marcusviniciusf,

Chakra doesn't do anything special with FormControl. The reproduction link doesn't work.

Would recommend sticking with the non-FormControl version for now.
