### ISSUE TITLE
Weird behavior with Next 14.1, works well in 13.5

### ISSUE THREAD

**Issue by ddeisadze** [chakra-ui/chakra-ui#8266]
### Description

I just upgraded to 14.1 for nextjs, the only error i get is with chakra chunk importing useMemo

see 

Import trace for requested module:
../../node_modules/@chakra-ui/accordion/dist/chunk-CRBMUVJA.mjs
../../node_modules/@chakra-ui/accordion/dist/index.mjs
../../node_modules/@chakra-ui/react/dist/index.mjs
./src/app/providers.tsx
 ⨯ ../../node_modules/@chakra-ui/accordion/dist/chunk-CRBMUVJA.mjs
Attempted import error: 'useMemo' is not exported from 'react' (imported as 'useMemo').

Import trace for requested module:
../../node_modules/@chakra-ui/accordion/dist/chunk-CRBMUVJA.mjs
../../node_modules/@chakra-ui/accordion/dist/index.mjs
../../node_modules/@chakra-ui/react/dist/index.mjs
./src/app/home/page.tsx
 ⨯ ../../node_modules/@chakra-ui/accordion/dist/chunk-CRBMUVJA.mjs
Attempted import error: 'useMemo' is not exported from 'react' (imported as 'useMemo').

Import trace for requested module:
../../node_modules/@chakra-ui/accordion/dist/chunk-CRBMUVJA.mjs
../../node_modules/@chakra-ui/accordion/dist/index.mjs
../../node_modules/@chakra-ui/react/dist/index.mjs
./src/app/providers.tsx

### Link to Reproduction

Its a large project not sure how to reproduce

### Chakra UI Version

2.8.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Node: 21.5.0
  npm: 10.1.0
  Yarn: 4.0.0
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 4.9.5

**Comment by Hagriel** [comment]
Have the same issue

**Comment by ddeisadze** [comment]
@Hagriel it works if you update to 14.1.1-canary.44, they patched an update to fix this

**Comment by segunadebayo** [comment]
It works now.
