### ISSUE TITLE
Modal content not scrolling if Modal open on top of another Modal

### ISSUE THREAD

**Issue by Passhub** [chakra-ui/chakra-ui#8269]
### Description

I have 2 modals. I'm opening second modal on top of first one (without closings first one).

Both modals have a lot of content inside and using scrollBehavior={true}.

When only first modal visible - everything is working fine, but when i'm opening second one, it's content cannot be scrolled.

Expected behavior - I just want second Modal scroll behavior works the same way as if only one modal exist. (And I dont want to close first modal).

Will be very thankfull if some one can help me wtih this problem.

### Link to Reproduction

https://codesandbox.io/p/sandbox/distracted-gauss-4fqjy3?file=%2Fsrc%2Findex.tsx%3A38%2C55&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsehxrbn00063b6i1df4g7r5%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsehxrbn00023b6iacsspgqa%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsehxrbn00033b6i5odt6m2v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsehxrbn00053b6i0y0to04z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsehxrbn00023b6iacsspgqa%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsehxrbm00013b6i02qp4ouw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Ftsconfig.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clsei91cf00023b6kz9x6w09f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A38%252C%2522startColumn%2522%253A55%252C%2522endLineNumber%2522%253A38%252C%2522endColumn%2522%253A55%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clsehxrbn00023b6iacsspgqa%2522%252C%2522activeTabId%2522%253A%2522clsei91cf00023b6kz9x6w09f%2522%257D%252C%2522clsehxrbn00053b6i0y0to04z%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsehxrbn00043b6ispzei6a3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsehxrbn00053b6i0y0to04z%2522%252C%2522activeTabId%2522%253A%2522clsehxrbn00043b6ispzei6a3%2522%257D%252C%2522clsehxrbn00033b6i5odt6m2v%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsehxrbn00033b6i5odt6m2v%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

1. Go to the reproduction example
2. Click on 'open first modal'
3. Check scroll availabilty in first modal
4. Click on 'open second modal on top of first one'
5. Try to scroll content in second modal and see the error

### Chakra UI Version

2.8.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zhoudalang** [comment]
I met the same problem. You can put the second modal inside the ModalContent component for this to work.

`

  <Modal>

     <ModalOverlay/>
     <ModalContent>
        {isOpenSecondModal &&
          ReactDOM.createPortal(
            secondModal,
            document.getElementById("modal-root")
          )}
      </ModalContent>

</Modal>

`

**Comment by Passhub** [comment]
> I met the same problem. You can put the second modal inside the ModalContent component like this. It will works fine.
> 
> `
> 
> ```
>  <ModalOverlay/>
>  <ModalContent>
>     {isOpenSecondModal &&
>       ReactDOM.createPortal(
>         secondModal,
>         document.getElementById("modal-root")
>       )}
>   </ModalContent>
> ```
> 
> `

Thanks for sharing ur solution. I'll try this one, but in my case it still will not work because i'm using "connected modals" solution in my app. (it's like controlling modals visability with redux|context|smth like that). So my modals are independent components and I cannot pass another modal into them.

But i've came with another solutuion on this problem. I was trying to find the reason why scroll blocking in general. And I found that Chakra UI using react-remove-scrollbar to disable scrolling while opening modals. 

To be more clear this lib creating "wheel" event listener on document with passive=false when u open modals (document.eventListener("wheel") and inside this event we can find function that use event.PreventDefault() wich effects scrolling on top one modals (If my investigations was correct ofcoz).   

As we know, we cannot just delete this eventListener because we don't have access to specific handler passed to it (especially in third-paty code).

So I found the solution to create custom "wheel" eventListener to override this behaviour with Bubbling and Capturing principles in JS. 

I created event in a capturing phase and force it to call event.StopImmediatePropagation() method to prevent react-remove-scrollbar from doing anything to with "wheel" event while my second modal is open.

I've test it and didn't find any problems yet. Ofcoz I'm using this approach ONLY when I need to open modal on top of another to prevent any problems as much as I can.

Here the custom hook I implemented:

![image](https://github.com/chakra-ui/chakra-ui/assets/31039433/6c2ad72b-d316-4c91-a44c-86056c65848e)

Hope it will help anyone.

P.S. Sorry for posting photo, couldn't use code insert correctly...

**Comment by victordev13** [comment]
Same problem here, thanks for alternatives to bypass this.

**Comment by segunadebayo** [comment]
The correct approach is what @tomaspanek mentioned here:
https://github.com/chakra-ui/chakra-ui/issues/8269#issuecomment-2402421818

Please move the second modal body into the first one to create the nesting required.

**Comment by iamrakhmatov** [comment]
Hey @segunadebayo, unfortunately in my case I have a Modal at the root level and I'm triggering it throughout the app using context but when I open it from within the Drawer it's not working, so I can't put my Modal inside DrawerBody unfortunately so how can I solve this issue?
