### ISSUE TITLE
Change default error(isInvalid) style of FormControl

### ISSUE THREAD

**Issue by ganeshkrishnasharma** [chakra-ui/chakra-ui#827]
How to change the default error styles of Form control? for example if i want to add a light red color as background? i currently don't see any option for that.

**Comment by santialbo** [comment]
You can use the `_invalid` prop.
```jsx
<FormControl isInvalid={true}>
  <Input _invalid={{ backgroundColor: "red.100" }} />
</FormControl>
```
https://codesandbox.io/s/chakra-invalid-input-yo6j0?file=/src/index.js

**Comment by ganeshkrishnasharma** [comment]
Thanks @santialbo , wasn't aware of _invalid prop for Input. Closing the issue.

**Comment by tpiecora** [comment]
is there a reason this shouldn't work?
```export const chakraTheme = extendTheme({
  components: {
    FormLabel: {
      defaultProps: { _invalid: { textColor: 'red.100' } },
    },
  },
});
```

It works fine as a prop on the component but I want to have it be a default.

**Comment by ImSolitude** [comment]
> is there a reason this shouldn't work?
> 
> ```
> export const chakraTheme = extendTheme({
>   components: {
>     FormLabel: {
>       defaultProps: { _invalid: { textColor: 'red.100' } },
>     },
>   },
> });
> ```
> 
> It works fine as a prop on the component but I want to have it be a default.
> 
> If this is a different issue, I can make a proper new one. It just seemed related.

I think this issue should be open again. It's still an issue as I cannot have it as a default.

**Comment by ryansle** [comment]
bumping this issue
