### ISSUE TITLE
NumberInput does not support right/left input elements.

### ISSUE THREAD

**Issue by Munaf-Divan** [chakra-ui/chakra-ui#8282]
### Description

When I tried to add `<InputRightElement>` in the `NumberInput` field, it did not support it.

![image](https://github.com/chakra-ui/chakra-ui/assets/140388383/66a6c838-1e60-4873-8b82-4cfd30e71a36)

### Link to Reproduction

https://discord.com/channels/937049452349382677/1205110862449217566/1205110862449217566

### Expected Behavior

We should also be able to add the right element in the number input field, just like the Input element.

### Chakra UI Version

2.8.2

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by veloware** [comment]
It does support it, you just need to use `InputGroup` - 

<img width="793" alt="image" src="https://github.com/chakra-ui/chakra-ui/assets/61578546/f0354422-5409-4599-ad02-7d526e2f7ec9">

**Comment by Pagebakers** [comment]
InputLeft/RightAddon is broken:

<img width="620" alt="Screenshot 2024-02-21 at 09 24 40" src="https://github.com/chakra-ui/chakra-ui/assets/32583/1fac8d77-6210-45e5-bcbf-a24d8459a979">

**Comment by segunadebayo** [comment]
This is a design flaw in v2. We've improved this significantly in v3.

I recommend styling the components in your userland code.

Thanks for understanding.
