### ISSUE TITLE
Change icon for drawer close button and such

### ISSUE THREAD

**Issue by saltnpixels** [chakra-ui/chakra-ui#8288]
### Description

The close buttons and drawer close and modal close don’t allow for changing the icon easily. 

Am I missing something or how can this be achieved? 

### Problem Statement/Justification

Changing icons is pretty standard I would think 

### Proposed Solution or API

An icon prop? The as prop breaks them from functioning.

**Comment by saltnpixels** [comment]
omg. I just looked at the source code and discovered you can give it a child icon!?? this is not in the docs!

**Comment by imMatheus** [comment]
Yeah i think this should be a thing that can be customized in a global space. For example, i have the use case where we have our own custom icons for all icons in our app. And the close icon Chakra provides is not the same, so we need it to be changed. Passing in a child will be pretty annoying at our scale :/

**Comment by segunadebayo** [comment]
We will improve the docs over time. As you’ve seen, you can customize it by passing the icon as a child.

You can also create a dedicated component to share it
