### ISSUE TITLE
Select size="sm" not keeping original borderRadius

### ISSUE THREAD

**Issue by vitalijalbu** [chakra-ui/chakra-ui#8307]
### Description

No theme applied;
As you can see buttons have bigger **border-radius** that select component (both setted to `size="sm"`)

![Screenshot 2024-02-22 alle 14 26 11](https://github.com/chakra-ui/chakra-ui/assets/40239902/e594a65b-9038-46ce-84e3-dfedbaeb8f58)

### Link to Reproduction

no needed

### Steps to reproduce

1. Create a sm button
2. Create a sm select
3. See different border radius

### Chakra UI Version

latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by TylerAPfledderer** [comment]
Hey @vitalijalbu!

If you are just using the default theme config, this is expected as the default design choices are on a component-by-component basis.

You can see in the [button theme](https://github.com/chakra-ui/chakra-ui/blob/main/packages%2Ftheme%2Fsrc%2Fcomponents%2Fbutton.ts#L7) that it has a border radius of `md` defined only in the base style.

And the border radius for the `sm` size of the select comes from the input theme, define as `sm`.

[Reference in the select theme](https://github.com/chakra-ui/chakra-ui/blob/main/packages%2Ftheme%2Fsrc%2Fcomponents%2Fselect.ts#L68)

[Declared in the input theme](https://github.com/chakra-ui/chakra-ui/blob/main/packages%2Ftheme%2Fsrc%2Fcomponents%2Finput.ts#L59)

You'll need to extend the theme to override the choice of border radius specifically for the `sm` size of the select component (and ultimately the input component), or vice versa with the button.

**Comment by segunadebayo** [comment]
Please update the border-radius in your userland code. Changing this might break UI for other users.

Thanks for understanding.
