### ISSUE TITLE
borderStyle ignored on Divider theme

### ISSUE THREAD

**Issue by mhamid3d** [chakra-ui/chakra-ui#8308]
### Description

When I set the borderStyle to 'dashed' for Dividers in my extended theme, the Dividers are still showing as solid.

### Link to Reproduction

https://codesandbox.io/p/sandbox/chakra-divider-border-theme-l2j5v8

### Steps to reproduce

1. Extend the theme for Divider component
2. Change borderStyle in baseStyle
3. Create divider component

### Chakra UI Version

2.8.1

### Browser

Microsoft Edge

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Interestingly, with Menu divider multipart theme, this is not an issue and borderStyle actually works.

**Comment by amrlpdr** [comment]
For me is a bug for this theme. 

I try for differents ways, but not work.

**Comment by segunadebayo** [comment]
I'd create an unstyled variant and set it as the default prop so I can style it all from the baseStyle.

```tsx
const theme = extendTheme({
  components: {
    Divider: {
      baseStyle: {
        borderColor: "red",
        borderWidth: 2,
        borderStyle: "dashed",
      },
      variants: {
        unstyled: {},
      },
      defaultProps: {
        variant: "unstyled",
      },
    },
  },
});
```
