### ISSUE TITLE
Creating custom MenuItemOption component removes icon

### ISSUE THREAD

**Issue by mhamid3d** [chakra-ui/chakra-ui#8309]
### Description

When I create a custom `MenuItemOption` component that extends the default chakra one, the check icon is missing, and adding a custom icon does not show either.

### Link to Reproduction

https://codesandbox.io/p/sandbox/chakra-menuitemoption-lh87jj

### Steps to reproduce

1. Create a component that extends MenuItemOption
2. Use it in a Menu and check if the icon is there

### Chakra UI Version

2.8.1

### Browser

Microsoft Edge

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by amrlpdr** [comment]
Your codesandbox is unavable for me. You can post a new codesandbox ?

**Comment by mhamid3d** [comment]
@pdroamrl sorry, same link should be public now!

**Comment by pdroamrl** [comment]
Thanks!

**Comment by segunadebayo** [comment]
Here's how to fix this.

```tsx
CustomMenuItemOption.id = "MenuItemOption";
```
