### ISSUE TITLE
Text noOfLines 1 whitespace with long words

### ISSUE THREAD

**Issue by HaleyWardo** [chakra-ui/chakra-ui#8311]
### Description

When using the Text component with `noOfLines` of 1, I would expect that the end word would break anywhere. Instead, the whole word wraps which causes empty whitespace. 

Current behavior: 
<img width="309" alt="Screenshot 2024-02-23 at 3 27 56 PM" src="https://github.com/chakra-ui/chakra-ui/assets/32574227/97737559-a452-452e-9586-e1c60be1b9f7">

Expected behavior: 
<img width="305" alt="Screenshot 2024-02-23 at 3 45 07 PM" src="https://github.com/chakra-ui/chakra-ui/assets/32574227/c4e02ac7-7945-4041-b8f5-1fe0384e30a2">

### Link to Reproduction

[Link](https://codesandbox.io/p/sandbox/chakraui-text-noofline-whitespace-7p6xg5?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsz37on700063b6hyr46x85c%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsz37on600023b6h8cbixiz0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsz37on600033b6hrkajfbxj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsz37on600053b6hkr1rbtgr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsz37on600023b6h8cbixiz0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsz37on600013b6hy85v46ug%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522clsz37on600023b6h8cbixiz0%2522%252C%2522activeTabId%2522%253A%2522clsz37on600013b6hy85v46ug%2522%257D%252C%2522clsz37on600053b6hkr1rbtgr%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsz37on600043b6hbvur8av8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsz37on600053b6hkr1rbtgr%2522%252C%2522activeTabId%2522%253A%2522clsz37on600043b6hbvur8av8%2522%257D%252C%2522clsz37on600033b6hrkajfbxj%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsz37on600033b6hrkajfbxj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

- With a Text component, set `noOfLines` to 1
- Make the text content have really long words

### Chakra UI Version

2.5.4

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I've tried handling this on my own 2 ways:

1. Setting a ref to check if the text is truncated and if so then get the `-webkit-line-clamp` value to see if the current `noOfLines` is 1. The issue with this is that line-clamp is computed as none when `noOfLines` is a ResponsiveValue.
2. Creating a custom `useCurrentBreakpointValue` hook, which take a ResponsiveValue, maps that to a breakpoint value object (`{base: '', sm: '', md: '', ...}`), and then uses the `useBreakpointValue` hook to get the current value. 

With both of these solutions, I would check if the text is truncated and if `noOfLines === 1`, if so then I would set `word-break: "break-all"`. 

However, I think this is super hacky and causes some undesirable flickering when rendering and resizing the browser. It would be nice if this is handled in the Text component itself.

**Comment by joaorodrs** [comment]
Hey Haley! Thanks for your contribution.

I observed that by default, when using `-webkit-line-clamp`, it uses the CSS initial value `word-break: normal`, which does not break words when clamping text, the same behaviour seen in the `noOfLines={n}` ChakraUI prop.

I think it would be wise to start a discussion about this change, because at the same time it makes more sense to use `word-break: break-all` every time `noOfLines` is applied, it would overwrite the default CSS value when trying to break lines (which is `word-break: normal`).

What do you think of this?

**Comment by joaorodrs** [comment]
What I meant is that should be a discussion whether `word-break: break-all` should be applied when `noOfLines` caused the text to clamp.

**Comment by segunadebayo** [comment]
Thanks for the suggestions.

I recommend applying this to your user-land code instead, as this might be a breaking change for most users.

`<Text noOfLines={1} wordBreak="break-all">`
