### ISSUE TITLE
Tab component is not accessible 

### ISSUE THREAD

**Issue by alexcaravaca** [chakra-ui/chakra-ui#8324]
### Description

when you try to navigate through the tabs here https://chakra-ui.com/docs/components/tabs#usage you cannot navigate using the keyboard "tab" If you inspect the element you will see the the tabindex for the tabs that are not selected is -1 see the attached screenshot 
![Screenshot 2024-02-26 at 13 30 15](https://github.com/chakra-ui/chakra-ui/assets/13257577/fa97b8cc-afce-4585-b244-05140c12b85e)

### Link to Reproduction

https://chakra-ui.com/docs/components/tabs#usage

### Steps to reproduce

1. Go to   https://chakra-ui.com/docs/components/tabs#usage
2. open the inspector 
3. inspect the first tab component example 

![Screenshot 2024-02-26 at 13 30 15](https://github.com/chakra-ui/chakra-ui/assets/13257577/8679052f-79df-436a-9c7e-a2ad0013922e)

### Chakra UI Version

v2.8.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Expected behaviour 
tabIndex should be 0 so the user can navigate through the tabs using the keyboard (tab)

**Comment by segunadebayo** [comment]
The tabs component is operable with the arrow keys not the Tab key. This is mentioned in the docs
