### ISSUE TITLE
Event listener type is wrong when using `as="form"` 

### ISSUE THREAD

**Issue by shuta13** [chakra-ui/chakra-ui#8331]
### Description

Related: https://github.com/chakra-ui/chakra-ui/issues/4037

It seems to be fixed but I still got a bug in the event listener when passing `as="form"` props to some component. They are as follows.

```tsx
// ~~~

    <Stack
      as="form"
      onSubmit={(e) => {
        e.preventDefault();
        // got errors in `new FormData(e.currentTarget)`
        // error: Argument of type 'EventTarget & HTMLDivElement' is not assignable to parameter of type 'HTMLFormElement | undefined'.
        setData(Object.fromEntries(new FormData(e.currentTarget)));
      }}
    >

```

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-kp7lgx?file=src%2FApp.tsx

### Steps to reproduce

1. Pass `as="form"` props to some chakra-ui component
2. Set `onSubmit` event listener
3. Errors occur

### Chakra UI Version

2.8.2

### Browser

Google Chrome 121

### Operating System

macOS

**Comment by segunadebayo** [comment]
This is a limitation of the types we have in place right now.

We don’t intend to fix it. It will be replaced with a new asChild prop in the next major release.
