### ISSUE TITLE
Image Component width and height attributes

### ISSUE THREAD

**Issue by saltnpixels** [chakra-ui/chakra-ui#8344]
### Description

To avoid layout shifts an image needs a width and height attribute. It seems with the way Chakra works the width and height prop are applied as css, not as the proper attributes needed. This causes layout shifting. Is there a way to add those attributes?

### Link to Reproduction

none

### Chakra UI Version

2.8.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Please use htmlWidth and htmlHeight.

That will ensure the native attributes are applied

**Comment by saltnpixels** [comment]
Sorry. Yes i didn’t realize those props existed until I clicked to check the props. I came here to answer my own question but you beat me to it. 
thanks
