### ISSUE TITLE
ColorModeProvider doesn't respect environment

### ISSUE THREAD

**Issue by anilanar** [chakra-ui/chakra-ui#8359]
### Description

In a custom environment like an iframe, I expect everything to work when used with `<ChakraProvider environment={{...}}>`.

However, the color manager ignores custom environments completely. See:

https://github.com/chakra-ui/chakra-ui/blob/7b6e66a15b08ad27e8458a009c3fb15ee738ca37/packages/components/src/color-mode/color-mode.utils.ts#L17-L24

As a result of that, `data-theme` attribute is not set on the `<html>` element. Because of that, default border color stays the user-agent default instead of chakra-ui's default. 

I don't utilize color manager functionality of chakra-ui, but I assume that feature is completely broken due to this.

### Link to Reproduction

https://codesandbox.io/p/sandbox/agitated-faraday-jns5jc

### Steps to reproduce

1. Look at the screen.

### Chakra UI Version

2.8.2

### Browser

Chrome, Firefox

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
This is now fixed by leveraging the CacheProvider from emotion.

Please follow this guide here:
https://www.adebayosegun.com/snippets/emotion-in-iframe
