### ISSUE TITLE
Divider renders without styles in first time

### ISSUE THREAD

**Issue by max10rogerio** [chakra-ui/chakra-ui#8360]
### Description

I'm using nextjs with app router in latest version

When I use the divider component, the divider renders without styles on the loading page. After the page fully loads, the styles are applied.

On loading page
![image](https://github.com/chakra-ui/chakra-ui/assets/21085292/153ea7b4-a43e-4396-8664-db02042fbf81)

After load page complete
![image](https://github.com/chakra-ui/chakra-ui/assets/21085292/c2f3a870-2f6d-4351-8106-548d6c8ffcba)

Full Example

https://github.com/chakra-ui/chakra-ui/assets/21085292/381259d8-a00d-419a-aad1-50eec2e66270

On codesandbox example, you need refresh refresh then you see a black line for a moment.

### Link to Reproduction

https://codesandbox.io/p/devbox/infallible-mahavira-ffjqmc?workspaceId=339403a7-df20-4695-bad9-9676ec52a704

### Chakra UI Version

2.8.2

### Browser

Google Chrome 122.0.6261.112

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I'm using WSL

### Update 1:

When I set the borderColor in theme that's work fine.

````tsx

// ./theme.ts
import { extendTheme } from "@chakra-ui/react";

export const theme = extendTheme({
  components: {
    Divider: {
      baseStyle: {
        borderColor: "gray.200",
      },
    },
  },
});

// providers.tsx
"use client";

import { CacheProvider } from "@chakra-ui/next-js";
import { PropsWithChildren } from "react";
import { ChakraProvider } from "@chakra-ui/react";

export const Providers = (props: PropsWithChildren) => {
  return (
    <CacheProvider>
      <ChakraProvider theme={theme}>{props.children}</ChakraProvider>
    </CacheProvider>
  );
};

**Comment by segunadebayo** [comment]
Please add the ColorModeScript so it can setup the data attributes and classname on the HTML element correctly.

```tsx
export const Providers = (props: PropsWithChildren) => {
  return (
    <CacheProvider>
      <ChakraProvider>
        <ColorModeScript />
        {props.children}
        </ChakraProvider>
    </CacheProvider>
  );
};

```
