### ISSUE TITLE
Popover component types don't allow `Popover.defaultProps` usage

### ISSUE THREAD

**Issue by esilverm** [chakra-ui/chakra-ui#8361]
### Description

When I was building a Popover wrapper that passed in some default props, I noticed that the typing for the Popover element doesn't allow for passing of `defaultProps` in the format of:

```tsx
Popover.defaultProps = { ... }
```

This format is supported by components such as `Button` because of the `ComponentWithAs` types passed by `forwardRef`, but `Popover` also supports adding `defaultProps` this way (as seen in the code sandbox) I'd expect the types to be present here too.

### Link to Reproduction

https://codesandbox.io/p/sandbox/condescending-brook-rzqhrk

### Chakra UI Version

2.8.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @esilverm, 

defaultProps is now deprecated in React. Consider setting the props on the Popover directly.
