### ISSUE TITLE
Cursor blinking on every text component <Heading>,<Text>

### ISSUE THREAD

**Issue by DawnSpark7** [chakra-ui/chakra-ui#8370]
### Description

When I am adding any text based component I am getting blinking cursor on each of them. This is very bad in terms of UX.

### Link to Reproduction

https://chakra-ui.com/docs/components/text/usage

### Steps to reproduce

Choose any of the given headings in the example, click on any of them and see the cursor keeps blinking

### Chakra UI Version

2.8.2

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, I can't seem to reproduce the problem.

Kindly provide a repro, and I'll re-open
