### ISSUE TITLE
Docs should link to relevant version's source

### ISSUE THREAD

**Issue by dijonkitchen** [chakra-ui/chakra-ui#8392]
### Description

When I go to the docs and click on the view source button, it should show the source for the proper version. 

### Link to Reproduction

https://github.com/chakra-ui/chakra-ui/tree/v1/packages/editable

### Steps to reproduce

When I go to https://v1.chakra-ui.com/docs/components/form/editable, 

I expect to go to https://github.com/chakra-ui/chakra-ui/tree/v1/packages/editable

instead of the incorrect link: https://github.com/chakra-ui/chakra-ui/tree/main/packages/editable

### Chakra UI Version

1.8.8

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Duplicate issue. We’re working on this
