### ISSUE TITLE
Github links for Customized theme and Default themes are broken

### ISSUE THREAD

**Issue by sandip-sadhukhan** [chakra-ui/chakra-ui#8395]
### Description

When I went to [Customized theme](https://chakra-ui.com/docs/styled-system/customize-theme) page, and click on [this](https://chakra-ui.com/docs/styled-system/customize-theme#:~:text=If%20you%27re%20curious%20as%20to%20what%20theme%20styles%20you%20can%20override%2C%20please%20reference%20the%20default%20theme%20foundation%20style%20files.) link it gives 404 page not found.

### Link to Reproduction

https://chakra-ui.com/docs/styled-system/customize-theme#:~:text=If%20you%27re%20curious%20as%20to%20what%20theme%20styles%20you%20can%20override%2C%20please%20reference%20the%20default%20theme%20foundation%20style%20files.

### Steps to reproduce

1. Go to https://chakra-ui.com/docs/styled-system/customize-theme this page.
2. Click on [this](https://chakra-ui.com/docs/styled-system/customize-theme#:~:text=If%20you%27re%20curious%20as%20to%20what%20theme%20styles%20you%20can%20override%2C%20please%20reference%20the%20default%20theme%20foundation%20style%20files.) link.
3. It will open File not found error page.

### Chakra UI Version

2.8.2

### Browser

Google Chrome

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by AboubakreSenouci** [comment]
#162

**Comment by segunadebayo** [comment]
This is now fixed.
