### ISSUE TITLE
[Button] Improve support for rounded buttons

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#84]
I just came across an [article about rounded buttons](https://cloudfour.com/thinks/jagged-little-pill-issues-with-rounded-buttons/) and thought the desired cross-browser compatible behavior could be implemented by Chakra UI.

**Comment by tioluwani94** [comment]
Hi @kripod, thanks for this, we will check the article out.

**Comment by segunadebayo** [comment]
I'll close this issue for now since there's not much conversation around it
