### ISSUE TITLE
[Modal] Long ModalHeader causes overlap and overflow issues with close button

### ISSUE THREAD

**Issue by juanri0s** [chakra-ui/chakra-ui#840]
**Describe the bug**
Attempted in code and also Chakra UI docs editable example. When you have a long modal header, or long single word, it goes behind the close button

![image](https://user-images.githubusercontent.com/8475305/84312478-03950100-ab33-11ea-92d1-0bd0df3fdeee.png)

![image](https://user-images.githubusercontent.com/8475305/84312428-ea8c5000-ab32-11ea-8dd9-34a1b87fd616.png)

![image](https://user-images.githubusercontent.com/8475305/84313415-7b176000-ab34-11ea-8657-5179641893b1.png)

**Expected Behavior** 

I expect that if there is a long modal header, that it would wrap by itself before it hits the close button.

**To Reproduce**

- Use this template:
- List the steps to reproduce the behavior:

1. Implement modal or go to https://chakra-ui.com/modal
2. Write long modal header

**Suggested solution(s)**

Wrap the text. Or somehow note the character limit in the docs. Or somehow limit the character limit.

Also, yes I know you can just give the header a rightMargin or a maxWidth but it's not a fool proof solution. Just think it should be built in

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 83.0.4103.97 (Official Build) (64-bit)

**Additional context** Add any other context about the problem here.

**Comment by segunadebayo** [comment]
Hi @juanri0s,

- To fix this issue, add `word-wrap: break-word` to the ModalHeader or Globally`. 
- For the collision with close-button, kindly add a `padding-right` to `ModalHeader`.

Let me know if this helps.

**Comment by juanri0s** [comment]
Hi @segunadebayo,

I mentioned that I am aware that those solutions will fix _my_ issue, but I see this as a Modal component issue in the library itself, maybe as a default property. I've noticed other UI libraries handle it just fine and I'm not sure seeing text overflow outside of the modal is an issue the user should be handling themselves. 

Padding is hacky because it requires a specific padding like `0.1875rem` on a 16px base, which isn't really the best.

Max width is hacky because again it requires a specific weird percentage such as 97%. 

But it seems you closed the issue so if that's just how the library will be then that's fine, might be something to maybe update in the docs then?

**Comment by with-heart** [comment]
In 1.0, `ModalHeader` now wraps correctly:
![image](https://user-images.githubusercontent.com/1954752/84717060-d1c0d780-af42-11ea-9f38-ca50d22e316a.png)

However the button overlap situation is still possible. Not sure of the value in addressing it by default, but wanted to point out how it will work after release.

**Comment by juanri0s** [comment]
Yeah I understand your points, just not in full agreement but that’s okay @with-heart @segunadebayo. I appreciate the discussion on it! Overall its a pleasure working with the library
