### ISSUE TITLE
Floating Labels - Broken gist in Docs

### ISSUE THREAD

**Issue by igorradovanov** [chakra-ui/chakra-ui#8402]
### Description

When I navigate to the 'Floating Labels' page in the documentation, I expect to see the Gist demo. However, it displays an error message stating, 'Invalid left-hand side in assignment.'

![chakra_ui](https://github.com/chakra-ui/chakra-ui/assets/20539903/59ec9030-79e3-4831-8b04-78ed72100604)

### Link to Reproduction

Not applicable

### Steps to reproduce

1. Go to 'https://chakra-ui.com/community/recipes/floating-labels'
2. See error

### Chakra UI Version

Not applicable

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

This is a documentation issue, not issue with the package itself.

**Comment by jensanjo** [comment]
This also happens with the gist on the [landing page](https://chakra-ui.com/).
![Schermafdruk van 2024-04-03 08-35-19](https://github.com/chakra-ui/chakra-ui/assets/1952482/e790febb-bc31-4cb1-9d80-8bf7ca525d78)

**Comment by jeferson-sb** [comment]
It seems to be an issue with codesandbox sandpack

![image](https://github.com/chakra-ui/chakra-ui/assets/30840709/33db538e-064c-42e0-abb8-50dd5bb85428)

**Comment by segunadebayo** [comment]
This is now fixed with the latest sandpack version
