### ISSUE TITLE
Fix references to old documentation repo

### ISSUE THREAD

**Issue by pwbriggs** [chakra-ui/chakra-ui#8415]
### Description

Not really a feature request in the library itself, but this was the most applicable issue form provided.

### Problem Statement/Justification

As far as I can tell, the documentation is now kept in this repo (`chakra-ui`). However, there are still references pointing to the (read-only) `chakra-ui-docs`.

### Proposed Solution or API

Migrate docs-related issue forms and contributing guide to this repo. Also fix the "Edit this page on GitHub" links in the footer of the docs.

**Comment by pwbriggs** [comment]
Huh. Despite this line in `site-config.json`, the docs page at `https://chakra-ui.com/getting-started` still links to `https://github.com/chakra-ui/chakra-ui-docs/tree/main/content/getting-started/index.mdx`. Is that config file somehow not getting used? Or is the website build & publish pipeline down?

https://github.com/chakra-ui/chakra-ui/blob/dfc81b4d4b3a667055e67fdac39cc17b27742f33/website/configs/site-config.json#L17

**Comment by segunadebayo** [comment]
Duplicate issue. We’re working on this

**Comment by pwbriggs** [comment]
Where is this other issue?
