### ISSUE TITLE
Tooltip still open after clicking an external Link

### ISSUE THREAD

**Issue by yosef-ian-kurniadi** [chakra-ui/chakra-ui#8418]
### Description

When I clicked an external link wrapped by a tooltip, I expected to come bank from that link and expect to see that tooltip closed. But that is not the case

Might be similar to https://github.com/chakra-ui/chakra-ui/issues/8124

### Link to Reproduction

https://codesandbox.io/p/sandbox/upbeat-shirley-d4d685.

### Steps to reproduce

1. Press on the link
2. You will be redirected to chakra's page
3. Go back to codesandbox
4. Tooltip is still open

### Chakra UI Version

@chakra-ui/react@2.8.0

### Browser

Google Chrome 123

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @yosef-ian-kurniadi,

Consider forcing a blur event when the link is clicked, or the page is navigated.

Something like this `onClick={e => { e.currentTarget.blur() }}`
