### ISSUE TITLE
Sidebar Icon Button too close to each other - Visible Overlapping

### ISSUE THREAD

**Issue by BeginArjun** [chakra-ui/chakra-ui#8420]
### Description

Button Links with Icon in the Sidebar are too close to each other in the docs page.
Here's the Image :
![image](https://github.com/chakra-ui/chakra-ui/assets/92989288/e82b3ff7-e37f-4e76-8ac9-08c7e0ab4052)

### Problem Statement/Justification

To make it easier for users to understand the difference between the buttons.

### Proposed Solution or API

Increasing the gap between them

### Additional Information

Vist here to see the issue : https://chakra-ui.com/getting-started

**Comment by BeginArjun** [comment]
I would like to work on this if you think this should be fixed

**Comment by segunadebayo** [comment]
This was an issue based on a recent domain migration we did. Might be a regression from Vercel itself. We've done a temporary redirect to v2 for now.

We'll work on getting back the domain.
