### ISSUE TITLE
‼️ The docs are broken ‼️ 

### ISSUE THREAD

**Issue by taylorpreston** [chakra-ui/chakra-ui#8421]
### Description

Vercel client side error.

### Link to Reproduction

https://chakra-ui.com/docs/components/menu/usage

### Steps to reproduce

<img width="932" alt="Screenshot 2024-04-11 at 10 00 08 AM" src="https://github.com/chakra-ui/chakra-ui/assets/14971676/93c75b24-1396-480d-8041-e7b961bec88a">

### Chakra UI Version

2..8.2???

### Operating System

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This seems to be an issue from Vercel. We've done a temporary redirect to v2 for now.

We'll work on getting back the domain.
