### ISSUE TITLE
"ReferenceError: CircularProgress is not defined" in CircularProgress docs

### ISSUE THREAD

**Issue by callum-gander** [chakra-ui/chakra-ui#8424]
### Description

Just wanted to point out that there's multiple `ReferenceError: CircularProgress is not defined` displaying on https://chakra-ui.com/docs/components/circular-progress

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-javascript-lzzg9

### Steps to reproduce

1. Go to [this url](https://chakra-ui.com/docs/components/circular-progress)
3. Scroll down 

### Chakra UI Version

2.8.2

### Browser

Chrome Version 123.0.6312.107

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This seems to be an issue from Vercel itself. We've done a temporary redirect to v2 for now.

We'll work on getting back the domain.
