### ISSUE TITLE
"Application error: a client-side exception has occurred" in docs for tooltip page

### ISSUE THREAD

**Issue by callum-gander** [chakra-ui/chakra-ui#8425]
### Description

Getting an "Application error: a client-side exception has occurred (see the browser console for more information)." when I go to the docs page for the tooltip, here https://chakra-ui.com/docs/components/tooltip/usage

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-typescript-pomi8

### Steps to reproduce

1. Go to [tooltip docs](https://chakra-ui.com/docs/components/tooltip/usage)
2. See error

### Chakra UI Version

2.8.2

### Browser

Chrome Version 123.0.6312.107

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This seems to be an issue from Vercel itself. We've done a temporary redirect to v2 for now.

We'll work on getting back the domain.
