### ISSUE TITLE
"ReferenceError: Tab is not defined" errors on Tabs docs

### ISSUE THREAD

**Issue by callum-gander** [chakra-ui/chakra-ui#8426]
### Description

You'll see multiple "ReferenceError: Tab is not defined" on the https://chakra-ui.com/docs/components/tabs/usage page 

### Link to Reproduction

https://codesandbox.io/p/sandbox/chakra-ui-javascript-lzzg9?file=%2Fsrc%2Findex.js

### Steps to reproduce

1. Go to [the tabs docs](https://chakra-ui.com/docs/components/tabs/usage)
3. Scroll down

### Chakra UI Version

2.8.2

### Browser

Chrome Version 123.0.6312.107

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This seems to be an issue from Vercel itself. We've done a temporary redirect to v2 for now.

We'll work on getting back the domain.
