### ISSUE TITLE
"Error: Minified React error #130" on Avatar docs page 

### ISSUE THREAD

**Issue by callum-gander** [chakra-ui/chakra-ui#8427]
### Description

This is the fourth bug with the docs on the website I've come across today. This one's different from the others, getting "Error: Minified React error #130" on the Avatar docs page

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-typescript-pomi8

### Steps to reproduce

1. Go to [the avatar docs page](https://chakra-ui.com/docs/components/avatar/usage)
2. Scroll down
3. See error

### Chakra UI Version

2.8.2

### Browser

Chrome Version 123.0.6312.107

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This seems to be an issue from Vercel itself. We've done a temporary redirect to v2 for now.

We'll work on getting back the domain.
