### ISSUE TITLE
"ReferenceError: AccordionPanel is not defined" on the Accordion docs page 

### ISSUE THREAD

**Issue by callum-gander** [chakra-ui/chakra-ui#8428]
### Description

Fifth instance of a bug with the docs today, as stated in the title, see here https://chakra-ui.com/docs/components/accordion/usage

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-typescript-pomi8

### Steps to reproduce

1. Go to https://chakra-ui.com/docs/components/accordion/usage
3. Scroll down 

### Chakra UI Version

2.8.2

### Browser

Chrome Version 123.0.6312.107

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This seems to be an issue from Vercel itself. We've done a temporary redirect to v2 for now.

We'll work on getting back the domain.
