### ISSUE TITLE
Multiple Errors on the Popover docs page

### ISSUE THREAD

**Issue by callum-gander** [chakra-ui/chakra-ui#8429]
### Description

Variety of different errors appearing on the page
- ReferenceError: Radio is not defined
- ReferenceError: PopoverCloseButton is not defined
- ReferenceError: EditIcon is not defined
- Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-typescript-pomi8

### Steps to reproduce

1. Go to [the popover docs page](https://chakra-ui.com/docs/components/popover/usage)
2. Scroll down 
3. See error

### Chakra UI Version

2.8.2

### Browser

Chrome Version 123.0.6312.107

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This seems to be an issue from Vercel itself. We've done a temporary redirect to v2 for now.

We'll work on getting back the domain.
