### ISSUE TITLE
Progress is not a clickable element when used with LinkOverlay

### ISSUE THREAD

**Issue by gleuch** [chakra-ui/chakra-ui#8432]
### Description

When using Progress with LinkOverlay, the progress bar is not clickable.

### Link to Reproduction

https://codepen.io/_gleuch/pen/JjVZpZj

### Steps to reproduce

1. Hover over any `<Progress>` bar component within a `<LinkBox>` component
2. Try to click on the progress, it should be wrapped but is not

### Chakra UI Version

2.8.2

### Browser

Google Chrome 124

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

When looking at generated CSS for progress bar, it seems that `position:relative` on the progress bar parent is preventing LinkOverlay from working correctly. I've been able to circumvent using `<Progress position="unset" value={50} />`.

I have not tried any other browsers or OS's.

**Comment by segunadebayo** [comment]
I don’t recommend using LinkOverlay for progress elements.

Your workaround is also fine. There’s only so much we can do on our side.
