### ISSUE TITLE
[Modal] Scrollbar hiding causes page flickering

### ISSUE THREAD

**Issue by asterikx** [chakra-ui/chakra-ui#844]
**Describe the bug**
When opening a modal the scrollbar gets hidden causing the page to flicker (including the modal itself).

This can also be seen in the [Chakra docs](https://chakra-ui.com/modal) when clicking on a `Open modal` button.

**Expected Behavior**

If the current page has a scrollbar, the scrollbar stays visible when opening a modal (no flickering). 

**Suggested solution(s)**

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome, Safari

**Additional context**
Related to #129

**Comment by segunadebayo** [comment]
Hi @asterikx,

You can solve this with these props:
- `blockScrollOnMount`: whether the modal should block scroll on mount
- `preserveScrollBarGap`: this will preserve the scrollbar space to avoid flickering.

Try these and let me know if it works. I will re-open this if it doesn't work.

Cheers.

**Comment by viennv1709** [comment]
It works, but I still see scrollbar when `placement="right"`. Please see how material UI solve it https://material-ui.com/components/drawers/
