### ISSUE TITLE
Scrollbar not following activeIndex on Menu (when have fixed Height)

### ISSUE THREAD

**Issue by therrou** [chakra-ui/chakra-ui#8444]
### Description

When a Menu is used with a fixed `height` or `maxHeight` to avoid a large `MenuList`, and trying to navigate with the keyboards (arrow down, arrow up, or open the menu with space/enter) the scroll of the menu is not following the focused item, creating a problem for accessibility with keyboard. The issue is caused in the `useMenu` hook and the `preventScroll: true ` from `useUpdateEffect` hook 

### Link to Reproduction

https://codesandbox.io/p/sandbox/busy-http-48t8rw?file=%2Fsrc%2Findex.tsx%3A22%2C20

### Steps to reproduce

1. In the sandbox, tab and set focus on the `MenuButton` element
2. Open the Menu with arrow up, arrow down, `Space` or `Enter`
3. The scrollbar of the menu is not following the active index. Below there is a container with focusable elements with the expected behaviour.

### Chakra UI Version

2.8.2

### Browser

123

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Setting the `preventScroll: false` will fix the issue and considering that the menu could be used as a dropdown/selector (to have more flexibility and styles) I think would be a great improvement.

**Comment by Jzmang** [comment]
Same here, facing this issue. Are there any workarounds for this by any chance?

**Comment by segunadebayo** [comment]
Duplicate of #8075

Working on a fix for this.
