### ISSUE TITLE
Stepper is not keyboard accessible

### ISSUE THREAD

**Issue by drscottlobo** [chakra-ui/chakra-ui#8449]
### Description

I'm loving this library! I had so many issues customizing MUI and switched to Chakra and it has been so much easier and more intuitive to use. Thank you for all your hard work on it! 

I just ran into the following issue: 

Currently the Step component of the Stepper allows for an onClick in order to set the active step. However, when this is the case, shouldn't the Step component also allow the user to tab to a new step and trigger the onClick with a Spacebar or Enter? This does not currently work.

### Link to Reproduction

https://v2.chakra-ui.com/docs/components/stepper/usage

### Steps to reproduce

I tried adding tab-index={0} to Step, which does allow the keyboard to focus on the Steps, but a click is not triggered with Spacebar or Enter. I also tried role="button" to no avail. Can keyboard access be better supported with this component? 

### Chakra UI Version

2.8.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by drscottlobo** [comment]
Will this issue be addressed?

**Comment by SvenReissig** [comment]
I ran into the same problem and really would appreciate a native accessibility support :)
