### ISSUE TITLE
could not import image from local storage

### ISSUE THREAD

**Issue by shreeram800** [chakra-ui/chakra-ui#8450]
### Description

When i tried to import local image by pasting the PATH of the image, it was showing error again and again .
![Screenshot 2024-04-20 193008](https://github.com/chakra-ui/chakra-ui/assets/109337160/67cd3a38-ef2d-40d6-ae1e-b053ae7fbaea)

### Link to Reproduction

https://v2.chakra-ui.com/docs/components/image/usage

### Steps to reproduce

1. Go to importing image from local storage

### Chakra UI Version

latest

### Browser

Brave

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is not a Chakra UI bug.
