### ISSUE TITLE
--bg-modal not working if white color has been modified by theme 

### ISSUE THREAD

**Issue by MattBevis** [chakra-ui/chakra-ui#8458]
### Description

When I have modified the theme.colors white, the --modal-bg variable doesn't pull through anymore. It uses a value of `colors . white` (spacing intentional) instead of `colors.white` is there anyway around this?

Please see my reproduction link below

### Link to Reproduction

https://github.com/MattBevis/chakra-ui-modal-example

### Steps to reproduce

1. Modify the theme white color
3. Create a modal and open it
4. See transparent modal background
5. Inspect the section element of the modal to see the css variable `--modal-bg` not being applied correctly 

### Chakra UI Version

2.8.2

### Browser

Good Chrome 123

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by gnowland** [comment]
I am also experiencing this issue!

**Comment by segunadebayo** [comment]
This is happening because the `colors.white` has been modified to `colors.white.500` in the new theme.

I guess this is what you meant to do?

```diff
 const theme = extendTheme({
    colors: {
-       white: { 500: "hsl(0, 0%, 100%)" },
+       white: "hsl(0, 0%, 100%)"
    },
  });
```
