### ISSUE TITLE
PopoverArrow did not apply the _dark property

### ISSUE THREAD

**Issue by tuanpq1998** [chakra-ui/chakra-ui#8478]
### Description

- Demo:
```tsx
<Popover>
  <PopoverTrigger>
    <Button>Trigger</Button>
  </PopoverTrigger>
  <PopoverContent color='white' _dark={{
              backgroundColor: 'blue.500',
            }} 
            bg='blue.800' >
    <PopoverArrow color='white' _dark={{
              backgroundColor: 'blue.500',
            }} bg='blue.800'  />
    <PopoverCloseButton />
    <PopoverHeader>Confirmation!</PopoverHeader>
    <PopoverBody>Are you sure you want to have that milkshake?</PopoverBody>
  </PopoverContent>
</Popover>
```

- Image:
   - Light mode: (works fine)
![image](https://github.com/chakra-ui/chakra-ui/assets/29828700/fc1912d3-cb7f-4c53-84f7-cdee2ab4648a)
   - Dark mode: 
![image](https://github.com/chakra-ui/chakra-ui/assets/29828700/2b3a10ff-01cd-4f9b-ba6b-f05350025822)

- Description: When I change to Dark mode, `PopoverArrow` remains the same bg color as Light mode although I  I have set up by `_dark`

### Link to Reproduction

https://codesandbox.io/p/sandbox/fragrant-night-ckjztz

### Steps to reproduce

1. Run the code in demo

### Chakra UI Version

lastest

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by odalysruano** [comment]
Chakra UI provides the [useColorModeValue hook](https://v2.chakra-ui.com/docs/styled-system/color-mode#usecolormodevalue) that changes background color depending on color mode. It's not necessary to use `_dark`. Here's an example:

```
function MyPopover() {
  const bg = useColorModeValue("blue.800", "blue.500");
  return (
    <Popover>
      <PopoverTrigger>
        <Button>Trigger</Button>
      </PopoverTrigger>
      <PopoverContent color="white" bg={bg}>
        <PopoverArrow bg={bg} />
        <PopoverCloseButton />
        <PopoverHeader>Confirmation!</PopoverHeader>
        <PopoverBody>Are you sure you want to have that milkshake?</PopoverBody>
      </PopoverContent>
    </Popover>
  );
}

```

Using the `useColorModeValue` hook will ensure the `PopoverArrow` turns the intended color in dark or light mode.

Here's a link to the code sandbox:
https://codesandbox.io/p/sandbox/popover-arrow-dark-demo-forked-mhqtcp

@segunadebayo can we close this issue?

**Comment by segunadebayo** [comment]
To style the arrow, you need to set the `--popper-arrow-bg` css variable.

You can also use the suggested solution above.
