### ISSUE TITLE
Support for `mode` prop for Transitions components

### ISSUE THREAD

**Issue by baptisteArno** [chakra-ui/chakra-ui#8481]
### Description

It would be nice to be able to change the default `mode` prop from `AnimatePresence` for all Transitions components.

### Problem Statement/Justification

A lot of time, I would actually need to change the mode to `popLayout`

### Proposed Solution or API

Just forward the `mode` prop to `AnimatePresence`

### Alternatives

Write my own AnimatePresence component.

### Additional Information

If you are OK with this, I can create a PR.

**Comment by segunadebayo** [comment]
Added support for this. Will release a new minor version shortly.
