### ISSUE TITLE
"Edit this page on GitHub" link in documentation links to wrong page

### ISSUE THREAD

**Issue by MrAlexLau** [chakra-ui/chakra-ui#8482]
### Description

When I click on the "Edit this page on Github" link at the bottom of various documentation pages like the `Link` page or the `Accordion` page, the resulting Github pages do not appear to reflect the actual documentation I see on the page.

For example:
- The [Link](https://v2.chakra-ui.com/docs/components/link) documentation page points to [this file](https://github.com/chakra-ui/chakra-ui/blob/main/website/content/docs/components/link/usage.mdx). The source file doesn't include a "Usage with Next.js" section at all on it.
- Likewise, the [Accordion](https://v2.chakra-ui.com/docs/components/accordion/usage) page points to [this file](https://github.com/chakra-ui/chakra-ui/blob/main/website/content/docs/components/link/usage.mdx), and glancing at each of them the "Imports" section looks completely different.

### Link to Reproduction

https://v2.chakra-ui.com/docs/components/link

### Steps to reproduce

1. Go to the [Link](https://v2.chakra-ui.com/docs/components/link) documentation page 
2. Click on the "Edit this page on GitHub" link at the bottom of the page which takes you [here](https://github.com/chakra-ui/chakra-ui/blob/main/website/content/docs/components/link/usage.mdx).
3. Note that the content of the source file differs from the content on the documentation page

### Chakra UI Version

2.8.2

### Browser

Any browser

### Operating System

- [X] macOS
- [x] Windows
- [x] Linux

**Comment by ijayhub** [comment]
I don't get please is this task open or closed?? if it is open please assign to me.
thank you

**Comment by MrAlexLau** [comment]
I don't think it's fixed. Pinging @abdulbasithqb in case I'm missing something.

**Comment by ijayhub** [comment]
Okay

**Comment by segunadebayo** [comment]
I just pushed a fix for this. I'll deploy the website shortly
