### ISSUE TITLE
Drawer closeOnOverlayClick doesn't work

### ISSUE THREAD

**Issue by Lukasvo** [chakra-ui/chakra-ui#8485]
### Description

When I try the Drawer code examples from the [documentation](https://v2.chakra-ui.com/docs/components/drawer/usage), nothing happens when I click the overlay. The default value for closeOnOverlayClick is true, and also when I explicitly set it to true, nothing happens on click.

Is this a bug or am I doing something wrong? (See attached code sandbox)

### Link to Reproduction

https://codesandbox.io/p/sandbox/delicate-fast-lcdh84

### Steps to reproduce

1. Click the button to open the Drawer
2. Click the overlay. Nothing happens

### Chakra UI Version

2.8.2

### Browser

Version 124.0.6367.158 (Official Build) (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by bumling** [comment]
Perhaps related to: https://github.com/chakra-ui/chakra-ui/issues/8516

**Comment by segunadebayo** [comment]
This is fixed.
