### ISSUE TITLE
Invalid license

### ISSUE THREAD

**Issue by mbrookes** [chakra-ui/chakra-ui#85]
Hey there!

I can't help noticing that most of the code here is copied from Material-UI and other React component libraries. That's absolutely fine, Material-UI is open-source for a reason (although it leaves me curious as to the motivation behind a library that is nothing more than a copy-and-paste compilation).

However, the MIT license states "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software." You haven't retained the copyright notice, nor attributed the libraries from which the code was copied.

**Comment by xtalx** [comment]
I see no evidence of “copy/paste.” Many component libraries are built similarly. Many are using similar supporting libraries like styled system which leads to a lot of similarities. Also components will have similar APIs. I would say it would be pretty difficult to create a component library with similar requirements that was totally unique in its implementation.

**Comment by segunadebayo** [comment]
Hi @mbrookes ,

I agree with you that Chakra UI was inspired by Material UI and other react libraries. I'll definitely add some more attribution, thanks for suggesting that.

However, to say that Chakra UI is nothing more than a cut-and-paste, I disagree. I believe Chakra has its unique components and API spec. The docs will show that for itself.

Thanks for voicing your concern though.

**Comment by segunadebayo** [comment]
I'm closing this now.

I'll make sure to add the origin of any copied or modified code in Chakra UI for proper attribution and conformance to the MIT License.

**Comment by mbrookes** [comment]
> I see no evidence of “copy/paste.”

I didn't provide any, as @segunadebayo already knows this to be true. However, compare Slider, Popper and Portal, for example. Also, if you look at the cadence of commits in the early stages, it becomes apparent that the components were not developed organically.

> I'll make sure to add the origin of any copied or modified code

That would be great! But until then, closing the issue is a bit premature.

**Comment by segunadebayo** [comment]
Hi @mbrookes ,

I closed this because I've added attributions to the parts of Chakra UI that were inspired by Material UI. I believe this addresses the issue.

Thanks again.

**Comment by mbrookes** [comment]
@segunadebayo Thanks, yes, and a very nice complement in there too, much appreciated... 

However the original authors of the other components might appreciate the same courtesy.

Best of luck with Chakra-UI! 👍

**Comment by segunadebayo** [comment]
You're welcome @mbrookes ,

I really admire the work you and the team at Material UI have done, and would definitely not take the credit for it. Thanks for bringing this to my attention.

Thanks again.
