### ISSUE TITLE
change log for particular version return 404

### ISSUE THREAD

**Issue by dzienisz** [chakra-ui/chakra-ui#8508]
### Description

change log for particular version return 404

https://github.com/chakra-ui/chakra-ui/blob/main/CHANGELOG.md

### Link to Reproduction

https://github.com/chakra-ui/chakra-ui/blob/main/.changelog/v2.7.1.mdx

### Chakra UI Version

all versions

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is now fixed. We link to the changelog file now.

**Comment by dzienisz** [comment]
It's not fixed, reopen please
