### ISSUE TITLE
Question: What is the preferred way to change the core props of a component?

### ISSUE THREAD

**Issue by cereallarceny** [chakra-ui/chakra-ui#851]
I'm trying to make a UI component system on top of Chakra. Usually I'm extending components with additional functionality specific to my use-cases. However, sometimes I simply change the `defaultProps` of a component, re-export, and move on. Here's an example of that very thing for `Button`'s:

```jsx
import { Button as ChakraButton } from '@chakra-ui/core';

export const Button = ChakraButton;

Button.defaultProps = {
  fontWeight: 'medium',
  size: 'md',
  variant: 'solid',
  variantColor: 'blue',
  _focus: {
    outline: 'none'
  }
};
```

This works great for any buttons that a developer uses directly. However, other Chakra components that compose the `Button` component (like `AccordionHeader`) will not pick up these changes.

**Rather than defining what a `Button` looks like when called directly, is there some way I change the internal reference of what a `Button` is to Chakra?**

I don't want to go through every component that implements a `Button` component and have to override them. I'd rather do it in one place and move on.

I couldn't find any explanation of this in your documentation, as it looks like you're only intending for developers to build more complex components off of your components, rather than have the ability to change the definition of an individual core component itself. Is what I'm asking for making sense?

**Comment by santialbo** [comment]
A new version of the library is expected to be released very soon which will allow you to do precisely that. You can check the theming docs for this upcoming release:
https://github.com/chakra-ui/chakra-ui/blob/master/docs/pages/theming/simple.mdx#using-the-themekey

**Comment by cereallarceny** [comment]
Wow, that's fantastic. Exactly what I was looking for. I was really hoping to avoid forking the repo in its entirety. Is there a branch or pre-release that myself and my team can work off of in the meantime?

Likewise, I'm a bit concerned about continuing my existing development. Are there a lot of expected breaking changes @santialbo ?

**Comment by santialbo** [comment]
There will be some breaking changes but hopefully not very big. Check out #696 
The master branch is already what's going to be the next release. It was said that the alpha release was going to happen this weekend. I think it's worth waiting til Monday ;P

**Comment by cereallarceny** [comment]
Wow! Hopping on Discord now @santialbo - thrilled about this new direction for Chakra. I'll close my issue as it will soon be irrelevant. Let me know if I can tackle any open issues for the release!

**Comment by jackblackCH** [comment]
Why does this method not work for Input? It only renders the placeholder and no input field.
```
import { Input as ChakraInput } from "@chakra-ui/core";

export const Input = ChakraInput;

Input.defaultProps = {
  border: "solid 1px hotpink",
  bg: "#fff",
  color: "#333",
  size: "lg",
  variant: "outline",
  placehoder: "negg",
};
```

**Comment by httpete** [comment]
> A new version of the library is expected to be released very soon which will allow you to do precisely that. You can check the theming docs for this upcoming release:
> https://github.com/chakra-ui/chakra-ui/blob/master/docs/pages/theming/simple.mdx#using-the-themekey

Hi - that link is broken - and what you are doing is exactly what I am thinking too - Can you point me to the new doc for the themekey idea? I feel for projects that want to build on top of the base provided by Chakra is a great use case.
