### ISSUE TITLE
Warning Invalid attribute name: `--breadcrumb-link-decor` Breadcrumb

### ISSUE THREAD

**Issue by alexvuong** [chakra-ui/chakra-ui#8513]
### Description

When I customise Breadcrumb components and passing styles into these components, I saw warning about styling such as "Invalid attribute name: ......."
![image](https://github.com/chakra-ui/chakra-ui/assets/52219283/2fad1204-bd74-48b9-9c0f-9ec718a9ce3c)
![image](https://github.com/chakra-ui/chakra-ui/assets/52219283/c1b6fd70-8394-402a-9f49-ca4ad5dc941b)

### Link to Reproduction

https://codesandbox.io/p/sandbox/chakra-ui-customised-breadcrumb-style-warning-lwsh5z

### Steps to reproduce

1. Load the sandbox
2. Open the browser consoles to see the warnings

### Chakra UI Version

>=2.6.0

### Browser

Chrome Version 124.0.6367.208

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Please change from 

```tsx
<BreadcrumbLink {...styles.link}>Current</BreadcrumbLink>
```


to this:

```tsx
<BreadcrumbLink sx={styles.link}>Current</BreadcrumbLink>
```
