### ISSUE TITLE
Popover not closing on outside click with latest framer-motion version

### ISSUE THREAD

**Issue by talamcol** [chakra-ui/chakra-ui#8516]
### Description

After upgrading framer-motion to the latest version `11.2.6`, the popover does not close anymore on outside click. The example is taken from the chakra docs [here](https://v2.chakra-ui.com/docs/components/popover#rendering-the-popover-in-a-portal). Version `11.1.7` works fine.

### Link to Reproduction

https://codesandbox.io/p/sandbox/chakra-popover-not-closing-yv4hh7

### Steps to reproduce

1. open popover using the button
2. click outside
3. popover does not close

### Chakra UI Version

2.8.2

### Browser

Chrome 125.0.6422.113

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by furquan-lp** [comment]
Having this exact same issue with `framer-motion` 11.2.10 as well. Still not fixed in the latest version of chakra-ui.

**Comment by Fazliddin-04** [comment]
`framer-motion` 11.1.7 is not working. Chakra UI: 2.8.2

Is there any solution?

**Comment by zanuarmirza** [comment]
try this [solution](https://github.com/chakra-ui/chakra-ui/issues/8555#issuecomment-2250638996).

**Comment by benjyiw** [comment]
I was facing similar issues today on `framer-motion@11.3.17`. Upgrading to `framer-motion@11.7.0` resolved everything for me.

**Comment by segunadebayo** [comment]
Kindly upgrade to framer-motion@11.7.0 to resolve this.

**Comment by Raza118041** [comment]
Hi everyone,

Can anyone guide me? I’m using the Framer Motion library in Next.js, and I’m facing an issue, when my bottom sheet opens, I’m able to click the buttons outside of it. I want to so that this doesn’t happen. Also, I’d like the background color to slightly change when the bottom sheet is open, and clickable outside the bottom sheet should be disabled.
