### ISSUE TITLE
Stack element spacing adds additional space when using SSR

### ISSUE THREAD

**Issue by remorses** [chakra-ui/chakra-ui#852]
This line uses the siblings selector to add spacing to elements
https://github.com/chakra-ui/chakra-ui/blob/a6141a7928da52a82f3a4238dda0be460c4b5ee6/packages/layout/src/stack.tsx#L94

The problem is that emotion adds additional style tags between elements when using SSR (only when NODE_ENV == prod), this way the stack element will add additional space to these style tags

From the emotion docs
> The rendered output will insert a <style> tag above each element

> Warning: This approach can interfere with nth child and similar selectors as it is inserts style tags directly into your markup. You will get a warning if you use such selectors when using this approach.

The solution would be to not use the selector in the parent stack and instead use a dummy divider component that has `height` set equal to `spacing`

**Comment by segunadebayo** [comment]
Hi, @remorses.

I'm aware of this issue and I've tested it with Gatsby and Next.js. Did you try to re-create this? If yes, please drop a link here so I can have a look.

Thanks

**Comment by remorses** [comment]
This page uses the stack from the new chakra ui, as you can see there is a top space before the page is rehydrated and emotion removes the style tags at runtime

https://landing-blocks.now.sh/

**Comment by remorses** [comment]
Using `'> *:not(style) + *:not(style)'` as selector completely removes this problem

**Comment by remorses** [comment]
Using `'> *:not(style) ~ *:not(style)'` completely removes the problem

**Comment by segunadebayo** [comment]
Amazing! Thanks for this suggestion @remorses. 

It worked perfectly. You're awesome!
