### ISSUE TITLE
[v3] Merging configs not working as expected

### ISSUE THREAD

**Issue by Curetix** [chakra-ui/chakra-ui#8525]
### Description

Hi, I've been really enjoying playing around with v3, great work!

I set up a custom theme to use the Tailwind color palette like this:

```tsx
import { createSystem, defaultConfig, defineConfig, mergeConfigs } from "@chakra-ui/react";

export const customConfig = defineConfig({
  theme: {
    tokens: {
      colors: {
        gray: {
          50: { value: "#f9fafb" },
          100: { value: "#f3f4f6" },
          200: { value: "#e5e7eb" },
          300: { value: "#d1d5db" },
          400: { value: "#9ca3af" },
          500: { value: "#6b7280" },
          600: { value: "#4b5563" },
          700: { value: "#374151" },
          800: { value: "#1f2937" },
          900: { value: "#111827" },
          950: { value: "#030712" },
        },

        /* .... */
      },
    },
  },
});

export const customSystem = createSystem(mergeConfigs(defaultConfig, customConfig));
```

... and then use it as the `value` prop on the `ChakraProvider`. This worked great in 3.0.0-next.0, but with 3.0.0-next.1 the colors are overwritten again with the default Chakra colors. When I swap the order of configs passed to `mergeConfigs` it works. I also noticed that `mergeConfigs` is not only returning a new config object, but it also modifies the existing object(s). That's a bit unintuitive and might have been an unintended change in 513f8ba872888b5b15ba64a15f433a7f07b6ef58?

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-rdekf5?file=src%2FApp.tsx

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

3.0.0-next.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Please send all v3 feedbacks here
https://github.com/chakra-ui/chakra-ui/discussions/8518

**Comment by segunadebayo** [comment]
You're right, though; the changes in that commit were the bug. I've fixed it in a recent commit.
