### ISSUE TITLE
Request to add custom Color mode definitions to ColorMode Component and Hook

### ISSUE THREAD

**Issue by Fazzacoot** [chakra-ui/chakra-ui#853]
**The Problem** I would like to have the ability to define my own color modes. Light and dark are useful but limiting for what I want to achieve. I would like be able to have a custom color mode with a custom name. My reasoning is I am building a site that does not need a light and dark mode but wants to switch certain colors based on what product line you are viewing. This means there could be more than two color modes required as there would be multiple product lines available on the site.

**Describe the solution you'd like**  Have the ability to pass in the different color modes I want to the provider and hook so that I can use my custom color definitions.

**Describe alternatives you've considered**  Build a custom Context provider that would manage the colors of the site without chakra managing it. Basically not use color provider to manage the Color Mode but build my own Provider to manage the color

**Comment by santialbo** [comment]
You can already define different themes and change the selected theme on the `ThemeProvider`

**Comment by Fazzacoot** [comment]
Ok so I would manage what `theme` I pass to the `ThemeProvider` my self through a global State and then define my needed colors and theme variables that way?
