### ISSUE TITLE
Add CodeSandbox link to issue templates

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#854]
Idea courtesy of @santialbo 

Once we release 1.0, we should create a CodeSandbox instance with Chakra pre-installed and then link to it in our issue templates. This will make it easier for us to assist users reporting issues as we'll be able to see their issue live.

**Comment by aaronmcadam** [comment]
Will that replace the Codesandbox links we already have in the README? A problem I've found is trying to keep the Chakra dependencies up to date within the sandbox. We've been updating the link manually. That means that we've got to remember to update it for each release.

**Comment by with-heart** [comment]
@aaronadamsCA Not sure. I haven't thought this all the way through yet. 🙃

**Comment by tonilaukka** [comment]
If I understand the docs correctly there will be no issue with keeping up the dependencies:
> With CodeSandbox you can import any GitHub repository as a sandbox (detailed here). An imported sandbox will automatically stay in sync with the GitHub repository; if you make a commit to GitHub it will reflect immediately in the sandbox.

https://codesandbox.io/docs/git

**Comment by with-heart** [comment]
Gonna close this as the following block has been added to the bug reports template:

Official Chakra CodeSandbox templates:
- [JavaScript CodeSandbox template](https://codesandbox.io/s/github/chakra-ui/codesandbox-react-js-template/tree/master)
- [TypeScript CodeSandbox template](https://codesandbox.io/s/github/chakra-ui/codesandbox-react-ts-template/tree/master)
