### ISSUE TITLE
Is this contributing documentation command wrong?

### ISSUE THREAD

**Issue by niconiahi** [chakra-ui/chakra-ui#855]
I just forked the repo and cloned it locally, and then run yarn boot as the documentation says and the command wasn't found. Then I looked into the package.json and effectively, it isn't there. Could `yarn prestart` be the correct one?

![](https://cdn.discordapp.com/attachments/688384130118975516/721423098456309922/Screen_Shot_2020-06-13_at_14.51.31.png)

**Comment by segunadebayo** [comment]
Hi @niconiahi,

I will update this, it should be `yarn boot` but I forgot to add it. Will do so now.

Thanks for letting us know.
