### ISSUE TITLE
Framer-motion 11.2.0 breaks Popover `initialFocusRef` functionality

### ISSUE THREAD

**Issue by jonhaddow** [chakra-ui/chakra-ui#8555]
### Description

When updating `framer-motion` from 11.1.9 to 11.2.0, ChakraUI's Popover component doesn't automatically focus on the element referenced by the `initialFocusRef` prop (the expected behaviour is documented [here](https://v2.chakra-ui.com/docs/components/popover/usage#focus-an-element-when-popover-opens))

To be clear, this works with `framer-motion` version 11.1.9, but **not** with version 11.2.0. It's possibly this is a bug, with `framer-motion`, but I'm raising the issue here as it's possibly a compatibility issue with Chakra's use of the library.

Thanks 🙏  

### Link to Reproduction

https://codesandbox.io/p/sandbox/sweet-lucy-sz3k82?file=/package.json:11,29

### Steps to reproduce

1. Setup the Popover component with an Input within the PopoverBody.
2. Ensure that the input ref is passed into the `initialFocusRef` prop for the Popover
3. Click on the trigger to open the Popover content
4. See that the Input is not automatically focused.

### Chakra UI Version

2.8.2

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by goncaloflf** [comment]
I have 2 identical codesandboxes here, one with `framer-motion@11.1.9` and the other with `framer-motion@11.2.0`, minimal use-case to reproduce, and can verify that the minor bump on framer-motion seems to cause this.

| framer-motion version 	| Sandbox                                                                                               	|
|-----------------------	|-------------------------------------------------------------------------------------------------------	|
| 11.1.9 (working)      	| https://codesandbox.io/p/sandbox/v11-1-9-chakra-popover-w-framer-motion-v11-not-working-forked-pg47fk 	|
| 11.2.0 (not working)  	| https://codesandbox.io/p/sandbox/v11-2-0-chakra-popover-w-framer-motion-v11-not-working-k3gp26        	|

**Comment by za-miru** [comment]
I got this issue also a few days ago. After debugging I figured out that this issue is caused by framer-motion update about animate "display" and "visibility" interpolation ([framer-motion changes](https://github.com/framer/motion/commit/e4077e9c3f9a0b5309d8f86a3e59e4f5955f53e2)) . On the chakra-ui side, this code at `package/hooks/use-focus-effect/src/index.ts` should do the focus action but nothing happen when using latest framer-motion.
```
requestAnimationFrame(() => {
  //  focus to popover is not working here
  tabbableEls[0].focus({ preventScroll }) 
})
```
I try to remove this code at framer-motion at `can-animate.ts` and it's working again
```
if (name === "display" || name === "visibility") return true
```

**Comment by za-miru** [comment]
to fixed this issue in project level is by set visibility transition duration to 0 at your PopoverContent.
```
    <PopoverContent
      variants={{
        exit: {
          opacity: 0,
          scale: 0.95,
          transition: {
            duration: 0.1,
            ease: [0.4, 0, 1, 1],
          },
        },
        enter: {
          scale: 1,
          opacity: 1,
          transition: {
            // fix code
            visibility: {
              duration: 0,
            },
            duration: 0.15,
            ease: [0, 0, 0.2, 1],
          },
        },
      }}
    > ...
```
It will make visibility value on the first frame to `visible`, then popover focus should be working.

**Comment by MartinP-C** [comment]
> I have 2 identical codesandboxes here, one with `framer-motion@11.1.9` and the other with `framer-motion@11.2.0`, minimal use-case to reproduce, and can verify that the minor bump on framer-motion seems to cause this.
> 
> framer-motion version	Sandbox
> 11.1.9 (working)	https://codesandbox.io/p/sandbox/v11-1-9-chakra-popover-w-framer-motion-v11-not-working-forked-pg47fk
> 11.2.0 (not working)	https://codesandbox.io/p/sandbox/v11-2-0-chakra-popover-w-framer-motion-v11-not-working-k3gp26
> Please note that this doesn't seem to be related to `initialFocusRef` as stated by @jonhaddow , as my usecase doesn't use it and still fails. It seems like chakra is unable to focus the PopoverContent in any way. I downgraded to `11.1.9` for now to solve this on my project.

It looks like this is fixed using framer-motion ^11.3.25
https://codesandbox.io/p/sandbox/v11-3-25-chakra-popover-w-framer-motion-v11-not-working-forked-tkq76p?file=%2Fpackage.json%3A16%2C30

**Comment by benjyiw** [comment]
I was facing similar issues today on `framer-motion@11.3.17`. Upgrading to `framer-motion@11.7.0` resolved everything for me.

**Comment by segunadebayo** [comment]
Kindly upgrade to framer-motion@11.7.0 to resolve this
