### ISSUE TITLE
Wrong position of Tooltip with child Icon element

### ISSUE THREAD

**Issue by EmeraldWeb** [chakra-ui/chakra-ui#8556]
### Description

When a Tooltip component has an Icon component as a direct child then its position jumps to the top left corner of the screen.

MacOs Monterey - 12.0.1 (21A559)
Google Chrome - 125.0.6422.142
@chakra-ui/react - 2.8.2
@emotion/react - 11.11.4
@emotion/styled - 11.11.5
react - 18.3.1

<img width="997" alt="Снимок экрана 2024-06-07 в 15 32 01" src="https://github.com/chakra-ui/chakra-ui/assets/20793330/92fcb029-c524-4bde-b57f-02251dffa13c">

I have attached an example of a build (in zip archive without password) with this bug:

[chakra-ui-tooltip-icon.zip](https://github.com/user-attachments/files/15740420/chakra-ui-tooltip-icon.zip)

### Link to Reproduction

https://www.dropbox.com/scl/fi/osde7donfbwd36w68m5gj/chakra-ui-tooltip-icon.zip?rlkey=ar8flljbc7ye8ujfk78lzg9hd&st=bvrdwq27&dl=0

### Steps to reproduce

1. unzip archive
2. npm i
3. npm run serve
4. hover you mouse over yellow star - wrong position of tooltip, over green star - all ok (because it has additional div wrap)

### Chakra UI Version

2.8.2

### Browser

Google Chrome - 125.0.6422.142

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Lsw931102** [comment]
I has the same question

**Comment by andynghiaa** [comment]
Thank for your issue due to that I had fixed the tooltip to display with an icon inside , just use a div wrapper , it's cool

**Comment by segunadebayo** [comment]
Please use `forwardRef` in your icon component or wrap with an inline element (like a span)
