### ISSUE TITLE
Icon component missing variant prop

### ISSUE THREAD

**Issue by miguelh72** [chakra-ui/chakra-ui#8558]
### Description

I expect typescript to not throw an error when I use variants for the `Icon` component. Instead, I get the following error,
```txt
Type '{ as: IconType; variant: string; size: number; }' is not assignable to type 'IntrinsicAttributes & MergeWithAs<SVGProps<SVGSVGElement>, IconBaseProps, IconProps, IconType>'.
  Property 'variant' does not exist on type 'IntrinsicAttributes & MergeWithAs<SVGProps<SVGSVGElement>, IconBaseProps, IconProps, IconType>'.ts(2322)
```

### Link to Reproduction

https://codesandbox.io/p/sandbox/bold-bell-pnvvvs

### Steps to reproduce

I have variants set up through the theme as follow,
```ts
const topNav = defineStyle({
  color: 'gray.600',
});

const brand = defineStyle({
  color: 'gray.700',
});

const iconTheme = defineStyleConfig({
  variants: {
    'top-nav': topNav,
    brand,
  },
  defaultProps: {
    variant: 'brand',
  },
});

...

export default extendTheme({
  ...
  components: {
    ...
    Icon: iconTheme,
  }
});
```

Interestingly, even though typescript complains the following code works as expected, so this looks like a typing issue only,
```jsx
<Icon variant="top-nav" />
```

### Chakra UI Version

2.8.2

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Please use the CLI to generate typings for the icon variants.
