### ISSUE TITLE
Popover usePortal prop not supported as described by documentation

### ISSUE THREAD

**Issue by ryanlynch717** [chakra-ui/chakra-ui#8567]
### Description

Using chakra-ui/react - I am following the [docs](https://chakra-ui.vercel.app/popover#rendering-the-popover-in-a-portal) to implement a popover where the contents render in a portal, but I get the following TS error:

```
[TypeScript] Type '{ children: Element[]; usePortal: true; }' is not assignable to type 'IntrinsicAttributes & PopoverProps'. Property 'usePortal' does not exist on type 'IntrinsicAttributes & PopoverProps'.
```

If I ignore the TS error, it also does not render the contents of the popover in a portal as expected.

I noticed a [previous issue](https://github.com/chakra-ui/chakra-ui/pull/356) where the type defintion seemed to be fixed in 2020 https://github.com/chakra-ui/chakra-ui/pull/356 so I'm unsure how to proceed. Are the docs outdated, is there another way to achieve this now? My use case is having the popper trigger from a dialog, so a portal would be good to render the popper outside of the dialog boundaries. 

Appreciate any guidance here. Thanks 😃 

### Link to Reproduction

- I was able to get this working by wrapping the <PopoverContent> in a <Portal> to mirror the <Menu> component docs, so I suspect this just needs a documentation update.
- [codesandbox example](https://codesandbox.io/p/sandbox/upbeat-violet-67rmrf?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxbx4lgm00063b6kgh7j7ri1%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxbx4lgm00023b6ks65ct9ia%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxbx4lgm00033b6kx25pqjdc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxbx4lgm00053b6kipfwrc3k%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxbx4lgm00023b6ks65ct9ia%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxbx4lgm00013b6kgz2hpfx7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A52%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A52%257D%255D%257D%255D%252C%2522id%2522%253A%2522clxbx4lgm00023b6ks65ct9ia%2522%252C%2522activeTabId%2522%253A%2522clxbx4lgm00013b6kgz2hpfx7%2522%257D%252C%2522clxbx4lgm00053b6kipfwrc3k%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxbx4lgm00043b6kv1kraqyy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxbx4lgm00053b6kipfwrc3k%2522%252C%2522activeTabId%2522%253A%2522clxbx4lgm00043b6kv1kraqyy%2522%257D%252C%2522clxbx4lgm00033b6kx25pqjdc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxbx4lgm00033b6kx25pqjdc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

- Implement a popover as per the documentation, and pass the `usePortal` prop

```
<Popover usePortal>
    <PopoverTrigger>
        <Text w="240px" variant="regularBold">
    ....
```

### Chakra UI Version

2.8.2

### Browser

Chrome Version 125.0.6422.142

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
You have the wrong docs link. Please visit https://v2.chakra-ui.com/docs/components/popover/usage
