### ISSUE TITLE
Highligh not marking the texts correctly

### ISSUE THREAD

**Issue by russoedu** [chakra-ui/chakra-ui#8571]
### Description

When I add an array in the Highlight component I expect all values to be marked, but some values are being partially marked. 

When an entry in the array contains part of another, the order matters.

Example: 
```
<Highlight
  query={[
    '1',
    '11',
  ]}
  styles={vnStyle}
>
  {'1 X 11'}
</Highlight>
```

This will only mark `1`, but not `11`. If I change the array order, it marks both.

### Link to Reproduction

https://codesandbox.io/p/sandbox/gifted-sea-rf7cyn

### Steps to reproduce

See the sandbox

### Chakra UI Version

2.8.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
You can fix this by reversing the query array: `query={['11', '1']}`
