### ISSUE TITLE
Request to add a support for an interactive Tooltip

### ISSUE THREAD

**Issue by chrysb** [chakra-ui/chakra-ui#858]
I would love it if I could create a Tooltip that allows me to mouseover it and click on a link or otherwise interact with the content within the Tooltip.

This would be great to give people a link out to a help center to "Learn more" for example.

**Comment by davidli3100** [comment]
You could use a popover for that. It takes a trigger of "hover" so you can interact with the contents on hover

**Comment by chrysb** [comment]
> You could use a popover for that. It takes a trigger of "hover" so you can interact with the contents on hover

Great tip, ty!
