### ISSUE TITLE
Custom Colors Not Suggested

### ISSUE THREAD

**Issue by rossanodr** [chakra-ui/chakra-ui#8586]
### Description

When extending the theme to include custom colors in Chakra UI, the new colors are not suggested in the TypeScript typings, only the default colors are suggested.

### Link to Reproduction

https://v2.chakra-ui.com/getting-started/cra-guide#chakraprovider-props

### Steps to reproduce

Import the extendTheme function from Chakra UI.
Extend the theme to include custom colors.
Pass the extended theme to ChakraProvider.
Try to use the new color in a component, e.g., <Button color='' />.
// 1. Import the extendTheme function
import { extendTheme, ChakraProvider } from '@chakra-ui/react'

// 2. Extend the theme to include custom colors, fonts, etc
const colors = {
  brand: {
    900: '#1a365d',
    800: '#153e75',
    700: '#2a69ac',
  },
}

const theme = extendTheme({ colors })

// 3. Pass the `theme` prop to the `ChakraProvider`
function App() {
  return (
    <ChakraProvider theme={theme}>
      <App />
    </ChakraProvider>
  )
}
When using the custom color in a component, the new colors are not suggested in the TypeScript typings:

<Button color='' > // new colors are not suggested
Expected Behavior
The new custom colors should be suggested in the TypeScript typings just like the default colors.

### Chakra UI Version

2.8.2

### Operating System

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by zgid123** [comment]
you should use chakra-cli to generate the typings to node_modules.

```
chakra-cli tokens <path to your theme config>
```

**Comment by rossanodr** [comment]
> you should use chakra-cli to generate the typings to node_modules.
> 
> ```
> chakra-cli tokens <path to your theme config>
> ```

I tried using that, but the only effect was that the default typings disappeared.

**Comment by zgid123** [comment]
Do you have an example repo? I will have a look

**Comment by zgid123** [comment]
Do you have an example repo? I will have a look

**Comment by synasapmob** [comment]
// utils/colors.ts
```
const colors = {
  shader: {
    a: {
        50"red",
        ...etc
    }
}
```

// package.json
```
{
  "scripts": {
    "theme:watch": "chakra-cli tokens utils/colors.ts --watch",
  },
}
```

**Result**:
![Screen Shot 2024-08-04 at 15 45 17](https://github.com/user-attachments/assets/72f1d87d-ef6a-483e-9c85-adebda5b9ab3)

![Screen Shot 2024-08-04 at 15 40 03](https://github.com/user-attachments/assets/637f1c1e-312a-4cb1-b896-ddc6602c7a9d)

**More**
[https://v2.chakra-ui.com/docs/styled-system/cli](https://v2.chakra-ui.com/docs/styled-system/cli)
