### ISSUE TITLE
DrawerTrigger is not exported in Chakra-UI v3 (React)

### ISSUE THREAD

**Issue by satarovbekzhan** [chakra-ui/chakra-ui#8588]
### Description

DrawerTrigger is not exported in v3. It is declared [here](https://github.com/chakra-ui/chakra-ui/blob/main/packages/react/src/components/drawer/drawer.ts) but not exported [from here](https://github.com/chakra-ui/chakra-ui/blob/main/packages/react/src/components/drawer/index.ts).

### Link to Reproduction

-

### Steps to reproduce

1. Initialize a React project.
2. Install and setup `"@chakra-ui/react": "^3.0.0-next.4"`.
3. Import it `import { DrawerTrigger } from '@chakra-ui/react';`

### Chakra UI Version

3.0.0-next.4

### Browser

Not relevant

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Good catch. Fixed this already.

**Comment by satarovbekzhan** [comment]
One more thing 🙏 I came up with this solution temporarily; it works great, but these props are not typed either.

```typescript
const [open, setOpen] = useState(false);

...

<Drawer.Root
    open={open}
    onOpenChange={({ open }: { open: boolean }) => setOpen(open)}
>
```
