### ISSUE TITLE
Date input calendar does not toggle properly

### ISSUE THREAD

**Issue by EricHasegawa** [chakra-ui/chakra-ui#8592]
### Description

When I use the `Input` component with `type='date'`, the calendar icon that appears on the right does not toggle on click. It toggles on, but not off, and effectively it only closes on outside click.

https://github.com/chakra-ui/chakra-ui/assets/26236981/8d3eb9d8-c42e-4008-b6bf-29872656ddc9

### Link to Reproduction

See video 

### Steps to reproduce

1. Use input with type date
2. Click calendar icon
3. Click again
4. Watch it come back

### Chakra UI Version

2.5.2

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is a native browser issue. It's not related to Chakra UI
