### ISSUE TITLE
[Next] Chakra V3 Feedback

### ISSUE THREAD

**Issue by segunadebayo** [chakra-ui/chakra-ui#8593]
### Discussed in https://github.com/chakra-ui/chakra-ui/discussions/8518

<div type='discussions-op-text'>

<sup>Originally posted by **segunadebayo** May 29, 2024</sup>
As our team works towards the anticipated release of Chakra UI version 3, we believe it's valuable to leverage this open communication channel to gather constructive feedback from early testers actively.
</div>

> [!NOTE]
> Please send all comments to the discussion above

**Comment by satarovbekzhan** [comment]
I'm using it and I'm super excited 🔥. Chakra is already my default UI library, and I hope v3 will be production-ready before the release 😅. Keep rocking, Chakraverse Team 🚀🚀🚀

**Comment by auvansang** [comment]
Last night, I try the v3-next.8, I saw, when I hover on the button, the mouse still show Arrow instead of pointer.

**Comment by lcswillems** [comment]
Will Chakra v3 be compatible with the Next.js app router?

Loading the ChakraProvider generates this error:

```
⨯ Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". Or maybe you meant to call this function rather than return it.
  {subtle: function, left-accent: ..., top-accent: ..., solid: ...}
```

with Next.js 14.2 app router.

**Comment by Curetix** [comment]
> Will Chakra v3 be compatible with the Next.js app router?
> 
> Loading the ChakraProvider generates this error:
> 
> ```
> ⨯ Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". Or maybe you meant to call this function rather than return it.
>   {subtle: function, left-accent: ..., top-accent: ..., solid: ...}
> ```
> 
> with Next.js 14.2 app router.

It works in both the Pages and App Router. Take a look at the example: https://github.com/chakra-ui/chakra-ui/tree/main/sandbox/next-app

**Comment by PatrickRogg** [comment]
I'm trying to put a menu into a custom position. Using `offset` doesn't seem to work like it did in v2. Anything else I need to do? Seems like top and left are still both set to 0.

```
<Menu.Root open={isOpen} onOpenChange={onClose}>
      <Menu.Positioner offset={[100, 200]}>
        <Menu.Content>
          <Menu.Item asChild value="123">
            <Box>123</Box>
          </Menu.Item>
        </Menu.Content>
      </Menu.Positioner>
    </Menu.Root>
```

Another thing I've noticed is that the shadow around the menu seems to disappear when the mouse down is released. I think v2 had the same issue.

![image](https://github.com/user-attachments/assets/ad1aa155-4a60-4c4e-a806-75183b27698c)

**Comment by wingsofovnia** [comment]
In the anticipation of release, I decided to go for the next.X version of Chakra UI for a greenfield project and I can't regret more :( Although the [migration guide](https://github.com/chakra-ui/chakra-ui/blob/main/MIGRATION.md) is very helpful, many things there are outdated or don't work as expected. https://next.chakra-ui.com is for the most part broken for many components or just straight outdated.

**Comment by lcswillems** [comment]
Regarding this part:

```
Before:

<Box bgGradient="linear(to-r, red.200, pink.500)" />
After:

<Box bgGradient="to-r" gradientFrom="red.200" gradientTo="pink.500" />
colorScheme is now colorPalette: Prior to this change, the colorScheme prop could only be used in a component's theme. This has been changed to colorPalette to better reflect the purpose of the prop and can be used anywhere.
```

What if I want multiple stops?

**Comment by segunadebayo** [comment]
> I'm trying to put a menu into a custom position. Using `offset` doesn't seem to work like it did in v2. Anything else I need to do? Seems like top and left are still both set to 0.
> 
> ```
> <Menu.Root open={isOpen} onOpenChange={onClose}>
>       <Menu.Positioner offset={[100, 200]}>
>         <Menu.Content>
>           <Menu.Item asChild value="123">
>             <Box>123</Box>
>           </Menu.Item>
>         </Menu.Content>
>       </Menu.Positioner>
>     </Menu.Root>
> ```
> 
> Another thing I've noticed is that the shadow around the menu seems to disappear when the mouse down is released. I think v2 had the same issue.
> 
> ![image](https://private-user-images.githubusercontent.com/46286606/353725777-ad1aa155-4a60-4c4e-a806-75183b27698c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTc5ODYsIm5iZiI6MTcyMzgxNzY4NiwicGF0aCI6Ii80NjI4NjYwNi8zNTM3MjU3NzctYWQxYWExNTUtNGE2MC00YzRlLWE4MDYtNzUxODNiMjc2OThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDE0MTQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNDIzMTY3MTI3MmQxNzljMWQyZjJjYWE1NGI3NGRhMjkzM2NkMDhiMTk3MzJjZWM0NTkyNTM4NmI5NDJkZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GuyKMY-P4qsxNb2oGXlYPQe6aZqQi3HOyFEHbIRwBRA)

Please set `positioning.placement` or `positioning.offset` on the `Menu.Root`. The docs are still WIP

```tsx
<Menu.Root positioning={{ placement: "top" }} />
```

**Comment by JoeyKo** [comment]
static extraction of css is really important!

**Comment by FabianFrank** [comment]
What's the best way to learn about the major changes that are coming in v3?

**Comment by wingsofovnia** [comment]
It seems that the new `NumberInput.Root` no longer exposes `precision` and I couldn't find an equivalent elsewhere. Is this no longer supported / should be implemented manually?

**Comment by hafiz006** [comment]
In V3, can I use ColorPalette in a global level? Without setting individual components colorPalette, I'd like to set the color to all components throughout the application. I have checked the docs for theme, but it has code for changing custom colors for individual components, and does not seem to even use the available colors from colorPalette. 

Thanks

**Comment by asyven** [comment]
<img width="1254" alt="image" src="https://github.com/user-attachments/assets/1381088a-158e-4b53-a7ad-4e452c25e273">
<img width="1248" alt="image" src="https://github.com/user-attachments/assets/e4fd9490-52bb-4db7-87f0-a82b1c8faa15">

v3 docs override v2, bunch of examples, quick search not working for now

**Comment by Sowmo0509** [comment]
The only reason not to use Chakra UI is it has lesser components. Other than that, it's amazing. Please look into MUI or Ant Design UI and add more components like- Autocomplete, Sortable tables, Validation with Forms, and more. Really need.

**Comment by a327958099** [comment]
The documentation for Chakra V2.8 no longer exists, which means that the system developed based on this version cannot view the component library documentation. I hope to restore the component library documentation of the previous version.

**Comment by PabloTGAr** [comment]
> What's the best way to learn about the major changes that are coming in v3?

The [MIGRATION.md](https://github.com/chakra-ui/chakra-ui/blob/main/MIGRATION.md) file there is a summary of the changes between v2 and v3

**Comment by lucas-garrido** [comment]
error with command ```npx @chakra-ui/cli@next snippet add```

```
file:///home/node/.npm/_npx/9fbc5fbb3b641738/node_modules/@chakra-ui/cli/dist/esm/utils/io.js:26
    const root2 = import.meta.resolve("@chakra-ui/react");
                              ^

TypeError: (intermediate value).resolve is not a function
    at getBasePath (file:///home/node/.npm/_npx/9fbc5fbb3b641738/node_modules/@chakra-ui/cli/dist/esm/utils/io.js:26:31)
    at file:///home/node/.npm/_npx/9fbc5fbb3b641738/node_modules/@chakra-ui/cli/dist/esm/utils/io.js:38:18
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    ```

**Comment by Benjamin-htr** [comment]
@hafiz006 I asked the same question on the discord, and actually it was added recently, you can do it like this:
```css
globalCss: {
  body: {
    colorPalette: "purple",
  }
}
```

**Comment by jaisharx** [comment]
Running the ```npx @chakra-ui/cli@next snippet add``` command adds all the components in my project directory within ```components/ui/*```. Is this something that chakra will be doing from now on? Not a big fan of component libraries doing this, what if I update the file in a breaking way, and then a major bug fix is released? Or is it recommended never to touch these files, but then why should the files have to exist within the project directory and not node_modules?

**Comment by stefee** [comment]
Would love to know if all the Ark UI components are going to get corresponding Chakra components (e.g. Date Picker) 😎

**Comment by segunadebayo** [comment]
@lucas-garrido Please upgrade your node version

**Comment by segunadebayo** [comment]
@jaisharx understandable. We recommend adding these snippets from v3. The files wouldn't be updated much; it's just a starter template for you. You can update it as you want.

Chakra still provides the core primitives. The goal of the snippets is to give you more control over how these components are styled and structured.

**Comment by segunadebayo** [comment]
@stefee Oh yes! We'll unleash all Ark components in Chakra back to back after the launch.

**Comment by segunadebayo** [comment]
@Sowmo0509 We're coming in hot with new components in v3.

**Comment by andrew-frank** [comment]
Mmm date picker, that's great!

Is there any estimated date of the v3.0 release? Can't find any GH projects or issues trackers. The only info I can find is this thread, PRs and the blog post (which btw suggests v3 is out, but the latest is `next.23` pre-release version).

**Comment by andrew-frank** [comment]
@hafiz006 @Benjamin-htr another option is to override the `accent` color token, as I *think* all Chakra v3 components use `colorPalette='accent'` [by default](https://github.com/chakra-ui/chakra-ui/blob/f6815563ec61dc786f459985049dbd70609ddafc/packages/react/src/theme/global-css.ts#L47). This could give you a bit more finer control.


In your theme file:
```
export const system: SystemConfig = {
  theme: {
    semanticTokens: {
      colors: {
        // NOTE: ovveride the accent color to match the branding
        accent: {
          contrast: {
            value: { base: '{colors.white}', _dark: '{colors.black}' }
          },
          fg: {
            value: { base: '{colors.gray.800}', _dark: '{colors.gray.200}' }
          },
          muted: {
            value: { base: '{colors.gray.100}', _dark: '{colors.gray.900}' }
          },
          subtle: {
            value: { base: '{colors.gray.200}', _dark: '{colors.gray.800}' }
          },
          emphasized: {
            value: { base: '{colors.gray.300}', _dark: '{colors.gray.700}' }
          },
          solid: {
            value: { base: '{colors.gray.900}', _dark: '{colors.white}' }
          }
        }
      }
    },
  }
}
```

**Comment by lucas-garrido** [comment]
```
import { createSystem, defineConfig } from "@chakra-ui/react";

const config = defineConfig({
  theme: {
    tokens: {
      colors: {
        red: { value: "#EE0F0F" },
      },
    },
    semanticTokens: {
      colors: {
        danger: { value: "{colors.red}" },
      },
    },
  },
});

export const system = createSystem(config);
```

why does using custom theme config break all the components style ? do i have to merge with the defaultSystem ?

**Comment by stefee** [comment]
I noticed that the Button component currently does not have `cursor: pointer` in v3 - is that by choice and if so what's the rationale behind that? It goes contrary to most recent popular libraries:
- [Park UI](https://park-ui.com/react/docs/components/button)
- [Tailwind UI](https://tailwindui.com/components/application-ui/elements/buttons)
- [shadcn/ui](https://ui.shadcn.com/docs/components/button)

**Comment by Bluorenge** [comment]
Is it just me that short indentation entries don't work and the container has no restrictions?

**Comment by lucphamvan** [comment]
please fix the autosuggestion , it's not work with all chakra token property

**Comment by evangordo** [comment]
Any examples of a simple a theme.ts setup?

**Comment by Bluorenge** [comment]
https://next.chakra-ui.com/docs/styling/text-styles#update-the-theme - not extend field, just textStyles

**Comment by wingsofovnia** [comment]
Recent update broke some code of mine that accessed styles of default recipes:
```
const inputRecipe = useRecipe({ key: 'input', recipe: rest.recipe })
const borderColorOld = inputRecipe().borderColor // worked before, not now
const borderColorNew = inputRecipe()['@layer recipes'].borderColor // works now
```
seems to be due to https://github.com/chakra-ui/chakra-ui/commit/798b8889b2a68951e602c2f7a88d680c277f5deb. Is that supposed to be now accessed this way, @segunadebayo?

**Comment by lucas-garrido** [comment]
do you guys have hydratation error when using turbopack ?

**Comment by wingsofovnia** [comment]
> do you guys have hydratation error when using turbopack ?

I get this:
```
Warning: Expected server HTML to contain a matching <div> in <body>.
div
Styled(div)@http://localhost:3000/_next/static/chunks/node_modules_%40emotion_987743._.js:778:197
Flex2@http://localhost:3000/_next/static/chunks/node_modules_%40chakra-ui_react_dist_esm_641a3f._.js:548:11
ChakraProvider@http://localhost:3000/_next/static/chunks/node_modules_%40chakra-ui_react_dist_esm_641a3f._.js:177:198
ChakraClientProvider@http://localhost:3000/_next/static/chunks/_12106d._.js:18:203
....
[Error] Error: Hydration failed because the initial UI does not match what was rendered on the server.
....
```

**Comment by Bluorenge** [comment]
How can I customize a specific part of a component via recipes?

**Comment by Bluorenge** [comment]
For layerStyles I can only use one level of nesting?

**Comment by l0gicgate** [comment]
Is there a way to add a custom `colorPalette`? I want to add a `brand` variant.

It would be amazing to see a full example theme with everything configured for a brand.

This would answer a lot of questions.

**Comment by Bluorenge** [comment]
Can I add a variant for Link via theme recipe?

**Comment by gvillo** [comment]
question, in the v3 migration docs it says `Default color palette is now gray for all components but you can configure this in your theme.`, but I couldn't find any `defaultColorPalette` prop in the theme to do that.

**Comment by drscottlobo** [comment]
Hi all! Having a great time exploring V3! I'm running into a repeated warning when using the asChild prop with various components and react icons:

Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
Check the render method of `Styled(span)`.
    at MdSchool 

Here is an example of code that is causing the warning: 
```
<List.Root>
  <List.Item>
    <List.Indicator asChild>
      <MdSchool />
    </List.Indicator>
    Courses
  </List.Item>
</List.Root>`
```

Any idea if I'm doing something wrong? If I remove "asChild" the warning goes away, but I think it loses the <Item.Indicator> styling as well. 

Thanks!

**Comment by Bluorenge** [comment]
I can't create recipe for tabs:

```typescript
import { defineRecipe } from '@chakra-ui/react';

const tabsRecipe = defineRecipe({
    variants: {
        variant: {
            subtle: {
                trigger: {
                    borderRadius: 'var(--tabs-trigger-radius)',
                    color: 'fg.subtle',

                    _selected: {
                        bg: 'red',
                        color: 'colorPalette.fg',
                    },
                },
            },
        },
    },
});

export { tabsRecipe };
```

**Comment by fredericbahr** [comment]
I personally dont like the removal of the color mode functionality as it was a nice feature of chakra ui. I explicitly dont want to install other packages in order to have light/dark mode supported.
In addition, not all people use Next.js, so using a package explicitly designed for next.js is not ideal.
