### ISSUE TITLE
defaultProps of createIcon are overwritten when component is used in `as` prop for Icon

### ISSUE THREAD

**Issue by piotrpawlik** [chakra-ui/chakra-ui#8596]
### Description

I'm defining custom icon using `createIcon` like this:
```
const CustomIcon = createIcon({
  defaultProps: { color: "red" },
  displayName: "CustomIcon",
  viewBox: "0 0 20 20",
  d: "...",
```

Now I want to use it like this:
```
<Icon as={CustomIcon} />
<Icon as={CustomIcon} color="blue" />
```
I want to be able to have default color for an icon and be able to overwrite it when needed. 
`<Icon as={CustomIcon} />` is not using default color defined in `defaultProps`

To make it work I need to use icon directly like this:
```
<CustomIcon />
<CustomIcon color='blue' />
```

But since I'm also using other icons from `react-icons` package and using way from [docs](https://v2.chakra-ui.com/docs/components/icon/usage) with `as` prop all over the app, I want to be able to use `as` prop for custom icons as well. 

### Link to Reproduction

https://codesandbox.io/s/hungry-saha-cfjzmg?file=/src/index.js

### Steps to reproduce

Go to sandbox above and you will see that `<Icon as={CustomIcon} />` doesn't have default color. 

### Chakra UI Version

2.6.0

### Browser

n/a

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
The output of createIcon is already a styleable component. You don’t need to use the as prop afterward.
