### ISSUE TITLE
Drawer "close" animation does not work unless DrawerOverlay component is used.

### ISSUE THREAD

**Issue by gnowland** [chakra-ui/chakra-ui#8604]
### Description

The Drawer component (and I assume all other "Modal"-based components) does not animate out of view and instead closes immediately if the <DrawerOverlay> component is not used.

I assume this is because the animation is being set on the overlay layer or and without the overlay the script removes the Drawer from the DOM before the animation runs?

I love that the modal architecture is implemented as multiple components so devs can pick and choose what elements they want to include, and hope the "close" animation can be handled in the parent Drawer component so I can use it without an overlay. Thanks! :) 

### Link to Reproduction

https://codesandbox.io/p/sandbox/broken-surf-92m4pt

### Steps to reproduce

1. Go to https://codesandbox.io/p/sandbox/broken-surf-92m4pt
2. Click on drawer with overlay
3. Close
4. Click on drawer without overlay
5. Close
6. See difference

### Chakra UI Version

2.8.2

### Browser

Chrome 126.0.6478.114

### Operating System

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by gnowland** [comment]
I'm hacking it for now with `<DrawerOverlay display="none" />` XD

**Comment by segunadebayo** [comment]
This is a design decision/flaw in the Drawer component. Consider setting `visibility: hidden` or `display: none` like you figured out.
