### ISSUE TITLE
not able to resize Select option

### ISSUE THREAD

**Issue by shatishdesai202** [chakra-ui/chakra-ui#8619]
### Description

![image](https://github.com/chakra-ui/chakra-ui/assets/66472172/bc8bb079-eea7-4094-963b-8726e79cfe79)

not able to resize the option width,  it is going outside of its parent width

### Link to Reproduction

https://v2.chakra-ui.com/docs/components/select

### Chakra UI Version

2.8.2

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
This is the native browser select component. It's not a custom one, so there's not much we can do about it.
