### ISSUE TITLE
Screen Reader Reads Empty Divs Injected by Chakra UI Portal

### ISSUE THREAD

**Issue by edtech1985** [chakra-ui/chakra-ui#8620]
### Description

Hey mates,

I've encountered an issue while using a screen reader (in my case, Orca). At the end of the page, the screen reader is reading some empty divs. This issue is affecting the accessibility (a11y) of our platform, and it's something that our a11y users are reporting to us.

It appears that these empty divs are being injected by Chakra UI Portal. Here is an example of the divs that are being read:

![image](https://github.com/chakra-ui/chakra-ui/assets/98822745/7ee2f054-64c4-4b07-8d61-4f6ac1ec2cf8)

I found this closed topic (https://github.com/chakra-ui/chakra-ui/issues/7831)

Is there any way to add an aria-hidden attribute to these divs when they are empty to prevent screen readers from reading them?

Thanks for your help!

### Link to Reproduction

https://codesandbox.io/p/devbox/chakra-ui-next-js-typescript-kxvyr

### Steps to reproduce

1. Go to any page
2. Inspect the page
3. Scroll down to the end

### Chakra UI Version

chakra-ui/react": "^2.8.2"

### Browser

Version 126.0.6478.126 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
These are added due to the way toast components work in v2.

A potential workaround is to add `aria-hidden` to the toast containers after the page mount 

```tsx
useEffect(() => {
	const toastRegions =  document.querySelectorAll('.portal [role=region]')
	toastRegions.forEach(region => region.setAttribute('aria-hidden', true))
}, [])
```

You could also consider removing them `region.remove()` as well if you don't use the toast component.

In the upcoming v3 version, these issues won't exist.

**Comment by edtech1985** [comment]
Hi Segun,

Thanks for the suggestion. Initially, the workaround didn't seem to work for me, but I came up with an alternative solution in my app component that worked. Here's what I did:

```
useEffect(() => {
  let count = 0;
  const interval = setInterval(() => {
    count += 1;
    if (count === 10) {
      clearInterval(interval);
    }
    const toastRegions = document.querySelectorAll('.chakra-portal [role=region]');
    toastRegions.forEach((region) => {
      region.setAttribute('aria-hidden', 'true');
    });
  }, 2000);
}, []);
```

This way, it keeps checking and setting aria-hidden until it successfully applies to all toast containers. Looking forward to v3 where this issue will be resolved.

Thanks again!

**Comment by oleksandr-danylchenko** [comment]
Thanks, @edtech1985! Your issue description is very precise and straight to the point! 

---

We faced the same one on our project, and I couldn't find whether those regions can be controlled or hidden. Because we don't even use the `Toast` feature. Unfortunately, it doesn't seem so in `Chakra@2`. However, the issue has been resolved since the `Chakra@3` release. Now the regions don't immediately appear in the DOM.

---

Not having enough capacity to migrate to the `Chakra@3`, I tweaked your suggestion and created the `useHideEmptyChakraRegions` hook:
```tsx
import { useEffect } from 'react';
import { poll } from 'poll';

const CHAKRA_TOAST_REGION_SELECTOR = '.chakra-portal [role=region]';

/**
 * The `Chakra@2` creates empty live regions in the DOM upon initialization.
 * They are used to announce the content of the toasts that are spawned imperatively.
 * Unfortunately, those regions are being read by screen readers even though they could be empty.
 * These can be disorienting and make the Webtext seem disorganized.
 *
 * @see https://linear.app/soomo/issue/TECH-1581
 * @see https://github.com/chakra-ui/chakra-ui/issues/8620
 */
export const useHideEmptyChakraRegions = () => {
	useEffect(() => {
		let stopPolling = false;
		let isHidden = false;

		const shouldStopPolling = () => isHidden || stopPolling;

		const pollingDelayMs = 10;
		const stopPollingInMs = 2000;
		const stopPollingTimeout = setTimeout(() => (stopPolling = true), stopPollingInMs);
		void poll(
			() => {
				const toastRegions = document.querySelectorAll(CHAKRA_TOAST_REGION_SELECTOR);
				if (toastRegions.length > 0) {
					toastRegions.forEach((region) => region.setAttribute('aria-hidden', 'true'));
					isHidden = true;
				}
			},
			pollingDelayMs,
			shouldStopPolling
		);

		return () => {
			stopPolling = true;
			clearTimeout(stopPollingTimeout);
		};
	}, []);
};
```
