### ISSUE TITLE
Menu's matchWidth is causing position issues 

### ISSUE THREAD

**Issue by sofia5** [chakra-ui/chakra-ui#8636]
### Description

In certain situation the matchWidth property is causing issues with the menu list position. 

With `matchWidth: true`:
![image](https://github.com/chakra-ui/chakra-ui/assets/11710053/125ab374-e9b6-41af-bbca-1ef1e9711d92)

Without `matchWidth`:
![image](https://github.com/chakra-ui/chakra-ui/assets/11710053/4e89c725-85bc-449f-8eff-2f6f27ffd5a7)

In second image, the menu is is positioned as `bottom-left` to avoid overflow on the screen's boundary. In the first, it stays `bottom-right`, even though there's not enough room to do so. I have a reusable component that should have matchWidth by default, but I always want it to show up within the boundaries of the screen.  

### Link to Reproduction

https://codesandbox.io/p/devbox/agitated-cherry-shv87m?welcome=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cly311zck00063589u9bwudmh%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cly311zck00023589nue8rri1%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cly317e0k00o23589f2v5elnl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cly311zck00053589x112ed1p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cly311zck00023589nue8rri1%2522%253A%257B%2522id%2522%253A%2522cly311zck00023589nue8rri1%2522%252C%2522activeTabId%2522%253A%2522cly311zcj00013589wusy4w6z%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly311zcj00013589wusy4w6z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A9%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A26%257D%255D%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522cly315seo00bs35897yheiakl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cly311zck00053589x112ed1p%2522%253A%257B%2522id%2522%253A%2522cly311zck00053589x112ed1p%2522%252C%2522activeTabId%2522%253A%2522cly35ykwe00093588cy7o5r83%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cly35w9jw018r3589v3abcpwg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522path%2522%253A%2522%252Feditors%252Fweb%252Fvscode-web%2522%252C%2522id%2522%253A%2522cly35ykwd00083588ksgn8cvs%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522path%2522%253A%2522%252Feditors%252Fweb%252Fvscode-web%2522%252C%2522id%2522%253A%2522cly35ykwe00093588cy7o5r83%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cly317e0k00o23589f2v5elnl%2522%253A%257B%2522id%2522%253A%2522cly317e0k00o23589f2v5elnl%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly317b8s00nx358900n3uok9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cly317d91000vdfgnamqgfiy3%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cly317b8s00nx358900n3uok9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

1. Click the button to the right
2. See how the menu opens out of bounds
3. Remove matchWidth
4. See how the position is working fine again. 

### Chakra UI Version

2.8.2

### Browser

Google Chrome Version 126.0.6478.126 (Official Build) (64-bit)

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by imMatheus** [comment]
Im having the same issue actually, would be nice to get a fix for it :)

**Comment by synasapmob** [comment]
you need undo value of min-width in menu component, check below it's fixed

![Screen Shot 2024-08-04 at 15 17 06](https://github.com/user-attachments/assets/d83d4040-8fa6-4260-b596-8e01063eca57)

[https://codesandbox.io/p/devbox/dawn-violet-2345gm](https://codesandbox.io/p/devbox/dawn-violet-2345gm)

**Comment by segunadebayo** [comment]
Closing based on https://github.com/chakra-ui/chakra-ui/issues/8636#issuecomment-2267422135

The fix is to add this prop

![CleanShot 2024-10-04 at 19 01 15@2x](https://github.com/user-attachments/assets/afe87e8d-4d7c-45f6-817d-50314fd5a07b)

**Comment by sofia5** [comment]
> Closing based on [#8636 (comment)](https://github.com/chakra-ui/chakra-ui/issues/8636#issuecomment-2267422135)
> 
> The fix is to add this prop
> 
> ![CleanShot 2024-10-04 at 19 01 15@2x](https://private-user-images.githubusercontent.com/6916170/373756486-afe87e8d-4d7c-45f6-817d-50314fd5a07b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NzQ0NTUsIm5iZiI6MTcyODQ3NDE1NSwicGF0aCI6Ii82OTE2MTcwLzM3Mzc1NjQ4Ni1hZmU4N2U4ZC00ZDdjLTQ1ZjYtODE3ZC01MDMxNGZkNWEwN2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMTE0MjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTQyOTU0ZTdjMGI1YmExMmM4Mjk2ZDRiNWRhZDQwOTQ5NDExOWZlMDlmNTIyOWFhYzE3ZTVjMzMzOGVhYzkzNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.CGP3iAlX7i8dSumQE8d18JIwMDFmvykpLL5WZZzt-Jo)

Hi! Great to get a response, but this is not a solution. Unsetting the min-width only makes the content not fit the list anymore. What I want is to have: 
A menu with a `minWidth` and `matchWidth=true` that fits inside the screen boundaries. If the width is to large to fit the screen boundary, I would expect the position to change.
