### ISSUE TITLE
Unable to style Input component

### ISSUE THREAD

**Issue by habmic** [chakra-ui/chakra-ui#8653]
### Description

Hi everyone!

I'm new to Chakra UI, so this might be a newbie question. I'm trying to apply some simple styles, such as size, to an Input component, but they don't seem to have any effect. However, when I set the size attribute on a Button component, it works as expected.

I noticed that the Input is rendered with a css-0 class, while the Button has a specific class applied to it. Here are the elements:

Input: `<input placeholder="Outline" class="chakra-input css-0">`
Button: `<button type="button" class="chakra-button css-i8y1hn">N/A</button>`
Here is my code:

```<SimpleGrid columns={2} spacing="10">
  <Button size="lg">N/A</Button>
  <Button variant="outline" size="sm">N/A</Button>
  <Input variant="outline" placeholder="Outline" />
  <Input variant="filled" placeholder="Filled" />
  <Input variant="flushed" placeholder="Flushed" />
  <Input variant="unstyled" placeholder="Unstyled" />
</SimpleGrid>
```
And the rendered HTML:

```<div class="css-b8am6i">
  <button type="button" class="chakra-button css-1vhy5a1">N/A</button>
  <button type="button" class="chakra-button css-i8y1hn">N/A</button>
  <input placeholder="Outline" class="chakra-input css-0">
  <input placeholder="Filled" class="chakra-input css-0">
  <input placeholder="Flushed" class="chakra-input css-0">
  <input placeholder="Unstyled" class="chakra-input css-0">
</div>
```
<img width="1370" alt="Untitled" src="https://github.com/chakra-ui/chakra-ui/assets/7610573/153c7dd4-cab5-4aa8-8963-760470ac6ab8">

Any insights on why the Input component isn't responding to style changes would be greatly appreciated!

### Link to Reproduction

N/A

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.8.2

### Browser

Google Chrome 126

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by JacobDel** [comment]
Any updates on this?
