### ISSUE TITLE
Chakra CLI tokens command fails when importing something from @fontsource

### ISSUE THREAD

**Issue by kainbryanjones** [chakra-ui/chakra-ui#8656]
### Description

When I follow this guide https://v2.chakra-ui.com/docs/styled-system/cli#usage I get this error

![image](https://github.com/user-attachments/assets/6217a518-ce0c-499a-9fb7-5062166851c7)

The problem resolves if I temporarily remove the 'import "@fontsource/lato"' from the top of my file.

### Link to Reproduction

https://codesandbox.io/s/blazing-silence-x6zqzp?file=/src/theme.ts:120-127

### Steps to reproduce

1. create a theme
2. import something from @fontsource and use that in the theme such as ```fonts: {
        body: "lato"
    }```
3. run the chakra cli tokens command on theme

### Chakra UI Version

    "@chakra-ui/react": "^2.8.2",

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
The CLI cannot statically resolve that import since it doesn’t handle font files 

I recommend separating out the fontsource import from the actual theme object.
