### ISSUE TITLE
VisuallyHidden: ctrl+f browser search finds it

### ISSUE THREAD

**Issue by davidrans** [chakra-ui/chakra-ui#8665]
### Description

When I search for text with the native browser find-in-page search, I expect it to not match the text inside `<VisuallyHidden>` elements.

### Link to Reproduction

https://codesandbox.io/p/sandbox/old-sky-gnswsd?file=%2Fsrc%2Findex.js&workspaceId=5a13c0e1-bacf-4e50-b31b-8682a0c5508a

### Steps to reproduce

1. Go to linked sandbox
2. Ctrl/Cmd + f to search in page
3. See two results instead of one because the visually hidden elements are being found

![image](https://github.com/user-attachments/assets/176bb4a6-f067-4f3d-849c-42ee9f6606c7)

### Chakra UI Version

2.8.2

### Browser

Google Chrome 126

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
The goal of this component is to hide its content from visually but make it visible to screenreaders.

Hiding it from the browser all together defeats its purpose. Would recommend implementing this in your app code

**Comment by davidrans** [comment]
Yeah, I think it's confusing for the browser search to bring something up that's invisible on the page, but I don't know how to prevent it without also preventing screen readers from finding it.

Looks like there's some discussion of a CSS rule to specify this behavior here: https://github.com/w3c/csswg-drafts/issues/3460
