### ISSUE TITLE
Theme: Font size for "md" size on Stat component does not work

### ISSUE THREAD

**Issue by imMatheus** [chakra-ui/chakra-ui#8674]
### Description

I was adding some theming to the `Stat` component and found that when I was trying to change the fontSizes of the different parts of the `Stat` component (such as `label`, `number` and `helperText`) in the `baseStyle` config, they where not applied when I was using the `md` size, other sizes like `sm` and `lg` works. It only seems to be an issue with font size weird enough, other props like `color` and `line-height` work to add. 

I found that adding the styling in the `sizes` prop did seem to work, but in my case, I want the exact same sizing for the `label` and `helperText` props regardless of size, only the `number` component should have different styling based on size. It's not the end of the world, I can get by this pretty easily in many ways here, just duplicating the font size on the different sizes for example. But this feels like a bug that could get fixed as well :)

I gladly have a look and try to file a PR for a fix if this gets deemed a bug. Maybe I'm missing something and this is the intended behaviour, not super sure 🙏 

### Link to Reproduction

https://codesandbox.io/p/sandbox/unruffled-cloud-z2f47r

### Steps to reproduce

1. Create a `Stat` theme
2. In base styles, add a different font size to the `label`, `number` or `helpText`
3. Use the Stat component with size `md`
4. Your font size is now not applied, but change the size to `sm` for example will apply the style

### Chakra UI Version

2.5.5

### Browser

Google chrome 126

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Again, if this is deemed a bug, I'll gladly have a look 🙏 

![Screenshot 2024-07-25 at 11 08 24](https://github.com/user-attachments/assets/bebe5424-5d04-415b-8dea-ca2e2a47c945)

**Comment by segunadebayo** [comment]
The size of the stat determines the font size, and the default size is md.

You need to override this in the theme to get it working.

```tsx
const baseStyle = definePartsStyle({
  label: { color: "green.500" },
  number: { color: "blue.500" },
  helpText: { color: "red.500" },
});

export const statTheme = defineMultiStyleConfig({
  baseStyle,
  sizes: {
    md: {
      label: { fontSize: "3xl" },
      number: { fontSize: "3xl" },
      helpText: { fontSize: "3xl" },
    },
  },
});
```
