### ISSUE TITLE
Use Modals should stop keyboard Propagation in the same way that it does for clicks

### ISSUE THREAD

**Issue by benmcginnis** [chakra-ui/chakra-ui#8687]
### Description

When I open a modal, I expect keyboard events to stay within the modal just like clicks do, but keyboard events propagate.

Compare: 
https://github.com/chakra-ui/chakra-ui/blob/78dfd7ed5925e0d3a792c7f751ce18ac0c578c2a/packages/components/src/modal/use-modal.ts#L133
with:
https://github.com/chakra-ui/chakra-ui/blob/78dfd7ed5925e0d3a792c7f751ce18ac0c578c2a/packages/components/src/modal/use-modal.ts#L99

This causes things like a universal search bar to be triggered when a user is types the hotkey but from within a drawer or modal.

### Link to Reproduction

https://codesandbox.io/p/sandbox/chakra-keydown-example-vx8nhw

### Steps to reproduce

1. Click button to open drawer
2. start typing in input, and type '/' key
3. see that second modal pops up

### Chakra UI Version

2.8.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Listening for the `keydown` handle on the document will make it get called every time. I recommend guarding the global listener with the `isOpen` from the modal.

```tsx
const down = (e) => {
      if (isOpen) return; // here
      console.log(e.key);
      if (e.key === "/") {
        e.preventDefault();
        onOpen();
      }
    };
```

or you can stop propagation manually in the modal content/drawer content

```tsx
<ModalContent onKeyDown={(e) => e.stopPropagation()}>
          <ModalHeader>Search for stuff</ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            <Input placeholder="Type your search" type="search" />
          </ModalBody>
        </ModalContent>
```
