### ISSUE TITLE
Image component is missing the alt attribute

### ISSUE THREAD

**Issue by onefastsnail** [chakra-ui/chakra-ui#87]
Both from the [demo page ](https://chakra-ui.com/image) and a local build, the `alt` attribute is not being used on the `img` element despite being passed in.

Haven't had much time to look at why, but just thought to add it here 😄

**Comment by segunadebayo** [comment]
Hi @onefastsnail ,

I've confirmed this and fixed the issue. I'll release a patch soon.

**Comment by segunadebayo** [comment]
I've released a new version of Chakra that resolves this. Kindly upgrade
