### ISSUE TITLE
Accessing the useSteps methods gives an unbound-method error

### ISSUE THREAD

**Issue by kwaimind** [chakra-ui/chakra-ui#8718]
### Description

When I use `useSteps`, I expect to be able to call the `isCompleteStep` and `isActiveStep` methods but instead I get the following Typescript error:

```
Avoid referencing unbound methods which may cause unintentional scoping of `this`.
If your function does not access `this`, you can annotate it with `this: void`, or consider using an arrow function instead  @typescript-eslint/unbound-method
```

### Link to Reproduction

#

### Chakra UI Version

2.8.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
