### ISSUE TITLE
Default options for toast is not applied.

### ISSUE THREAD

**Issue by MertzAndreas** [chakra-ui/chakra-ui#8721]
### Description

I have tried to configure the toast component, and found out that it was possible to define defaultOptions for the theme component directly in the ChakraProvider. I have tried to define duration and position, which are both ignored. Im using Nextjs app router, which i think might be causing the issue, but i have followed the docs in terms of setting up chakra with nextjs, where i have defined a client component and wrapped my children inside layout with this component.

```JS
'use client';
import React from 'react';
import { CacheProvider } from '@chakra-ui/next-js';
import { ChakraProvider } from '@chakra-ui/react';

const ChakraProviderWrapper = ({ children }: React.PropsWithChildren) => {
    return (
        <CacheProvider>
            <ChakraProvider
                toastOptions={{ defaultOptions: { position: 'bottom-right', duration: 1000 } }}
            >
                {children}
            </ChakraProvider>
        </CacheProvider>
    );
};

export default ChakraProviderWrapper;

``` 

### Link to Reproduction

https://github.com/MertzAndreas/Todo-Frontend/blob/main/app/Account/Login/page.tsx

### Steps to reproduce

I have linked my personal project, which im currently developing, im hoping that's ok, otherwise please say otherwise and i will see if i can create a sandbox which reproduces. The toast works as expected, except for the default options being applied.

### Chakra UI Version

    "@chakra-ui/next-js": "^2.2.0",     "@chakra-ui/react": "^2.8.2",

### Browser

Arc, Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
At the moment, all other toast options besides placement and duration are applied. This is a design flaw in v2.

We've improved this in v3.
