### ISSUE TITLE
[NumberInput] Not defaulting to Max when user types a too high number

### ISSUE THREAD

**Issue by HadiSDev** [chakra-ui/chakra-ui#873]
**Describe the bug** A clear and concise description of what the bug is.

![image](https://user-images.githubusercontent.com/10367624/84826351-1f147600-b023-11ea-85a1-4c35dad86101.png)

I have a NumberInput where max is set to 9999 and min to 0. The user can however as seen in the image above still type number above max. This is inconvenient when you are dealing with zipcodes for example.

I expect it to default to the max value if an entered value is higher than max. Similar to min

    "@chakra-ui/core": "^0.8.0",
    "@emotion/core": "^10.0.28",
    "@emotion/styled": "^10.0.27",

**Comment by with-heart** [comment]
We don't have this functionality built in to the library. The closest thing we have is in 1.0 which clamps the value on blur.

You could manage this yourself using `value` and `onChange`. Here's an example: https://codesandbox.io/s/cranky-wave-hwwdv?file=/src/App.js
