### ISSUE TITLE
Input - no aria-invalid attribute when isInvalid is false

### ISSUE THREAD

**Issue by shamelio** [chakra-ui/chakra-ui#8732]
### Description

When setting isValid to false (`<Input isInvalid={false} />`) it set aria-invalid to undefined and not "false".
It leads to bad experience with VoiceOver on iOS device - doesn't reproduce on MacOs:
When focusing on a required input with empty value, voice over says "invalid data".

I've added a sandbox with html that shows the difference between aria-invalid="false" and no aria-invalid attribute.

### Link to Reproduction

https://codesandbox.io/p/sandbox/aria-invalid-lvvq92

### Steps to reproduce

1. Open sandbox on iOS device and open VoiceOver
2. Click on the first field (Required1) - VoiceOver is ok
3. Click on the second field (Required2) - 
4. VoiceOver is say in the end "Invalid data"

### Chakra UI Version

1.8.9

### Browser

Google chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

iOs

**Comment by shamelio** [comment]
My workaround was setting aria-invalid manually using ref:
```
useEffect(() => {
  ref.current?.setAttribute('aria-invalid', props.isInvalid ? 'true' : 'false');
}, [props.isInvalid]);
```

**Comment by segunadebayo** [comment]
I'd recommend adding this in the userland code.

```jsx
<Input aria-invalid={isInvalid} />
```

The v1 branch is no longer maintained.
