### ISSUE TITLE
(v2) [IconButton] padding="0" gets overwritten by conditional `size` prop

### ISSUE THREAD

**Issue by isBatak** [chakra-ui/chakra-ui#8755]
### Description

When `size` prop use conditional styles then underlying  Button styles for size have higher specificity because of media queries or the higher position in the CSS.

This inlined style gets overwritten https://github.com/chakra-ui/chakra-ui/blob/37dae70264921637008bb0780f5559dc5d2ed22f/packages/components/src/button/icon-button.tsx#L54

![image](https://github.com/user-attachments/assets/d0e21751-ae92-480e-a7da-c2d926a7f5c6)

Workaround is to add `p="0!"`
```
<IconButton size={{ base: 'sm', md: 'md' }} p="0!" icon={<UpDownIcon />} />
```

### Link to Reproduction

https://play.chakra-ui.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwATFwElIA7AIQFdtsITcBfXAM0whVwHIABMACwEMA1pn4BaCkgD0mGPzDYOAHRKoMOfLjAz+2GMVoNmrdtz5CR4qUlIBnJSWXKYADzV5beAKpoAIhADuJPp0ALya2rrBABTAyri4UEg2aAA2-ACeAHL8KDDwnN5+gcEcADRxuABuSDD+ZBDO+RwADLitAEzNHV1lFZKSuGg6vJr8dPwpNhC4AEYwuGMLmCLpuBBMuDApMLkk2DaluEgb6RAUuAKV8ygUKdhIqfND2LwHuClIJDBvNgJo34cYNgwAA6CrPXj5KIVeIAHghMPizCQKRSIQ4YAoyxgewAwhAUlh7EikVB0QBZXAARi6hxprXYogA7ABWQ6tfi4VmlVltamlVpUlnNAULLls3mC0WiIUi5rEpGSAB8FQAlOUSPRVY4vq4sO5aDY8ABBNBoXBhKKqi1K-AVGTYLF0WHBSjUAw2JAALxgIWABBm-BseU4NhQZVwKCgTSjHAYjGstD9sMKASCpFwysYyuU9BA9CAA

### Steps to reproduce

1. Go to Chakra playground link
2. Inspect the first button CSS in Browser dev tools
3. Compare with other buttons style

### Chakra UI Version

2.8.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by ekansh2** [comment]
Hi @isBatak, I would like to work on this issue. Please assign to me.

**Comment by isBatak** [comment]
@ekansh2 that solution is to use `px="0" py="0"` like in v3 https://github.com/chakra-ui/chakra-ui/blob/f4d903642b9d4f4efff854b01be7e5c98250db02/packages/react/src/components/button/icon-button.tsx#L12
Make sure to make a PR that points to v2 branch.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
