### ISSUE TITLE
Request to add [Inline] component

### ISSUE THREAD

**Issue by aaronmcadam** [chakra-ui/chakra-ui#877]
First of all, fantastic work everyone on the v1 work! ❤️  💙  💛  💚  

A lot of my `Stack` usage involves me adding the `isInline` prop.

What happened [the idea we had for an `Inline` layout component](https://github.com/chakra-ui/chakra-ui/issues/484)?

If we don't implement a separate component, I think we should change the `isInline` to `orientation`. It would accept `vertical` and `horizontal`. It would default to `vertical`. Here's an example: https://paste.twilio.design/layout/stack/

**Comment by aaronmcadam** [comment]
Ah I didn't read the docs properly, closing.

**Comment by with-heart** [comment]
We also have `VStack` and `HStack` coming soon if you don't need to responsively change the orientation of your `Stack` :)

**Comment by aaronmcadam** [comment]
Thanks, @with-heart, that sounds good!
