### ISSUE TITLE
v3: Avatar can't fallback to initials

### ISSUE THREAD

**Issue by wingsofovnia** [chakra-ui/chakra-ui#8777]
### Description

After upgrading to `next.20`, I am no longer able to fallback to name initials.
This used to work:
```
<Avatar.Root>
  <Avatar.Image src={img} />
  <Avatar.Fallback><Avatar.Initial name={name ?? 'N A'}/></Avatar.Fallback>
</Avatar.Root>
```

`Avatar.Initial` got recently removed. `Avatar.Fallback` has no `name` exposed, and `getInitials` is not applied to `children`.

### Link to Reproduction

snippet in description

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

3.0.0-next.20

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This isn’t an issue since v3 is still in active development.

Please run the snippets command to add the avatar to your project.

npx @chakra-ui/cli@next snippet add avatar

That should give you a composed avatar component that has the initials logic.

**Comment by wingsofovnia** [comment]
@segunadebayo thank you for a prompt reply. I see that getting initials is no longer a built-in feature. On a side note, how should be the issues with the .next versions reported then? I understand that these might not be bugs of the currently supported Chakra version but very much can be the future Chakra bugs and it is a good idea to let people, who risked and started using an untested version, report the potential issues.
