### ISSUE TITLE
Setting an input field's background color in the baseStyle theme object does not work

### ISSUE THREAD

**Issue by nicolls1** [chakra-ui/chakra-ui#8782]
### Description

When I set a input field's background color in the baseStyle of the theme object, I expected the theme to update.

### Link to Reproduction

https://codesandbox.io/p/sandbox/admiring-hooks-vkw6fl

### Steps to reproduce

See example for the theme not working. Also, if you update this line in the example linked: 
```
    backgroundColor: "green",
```
to
```
    backgroundColor: "green !imporant",
```
the background color is now updated. Looking at the element, something is setting background to "inherit" after the theming and I cannot identify where that is coming from. It seems unexpected to me.

### Chakra UI Version

2.8.2 

### Browser

Firefox 129.0.1 (64-bit)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
The variant of the input is responsible for setting the background color. The default variant is `outline`, that's the one you should override instead.

```tsx
const inputTheme = defineMultiStyleConfig({
  variants: {
    outline: {
      field: {
        bg: "green",
      },
    },
  },
});

```

**Comment by FilipSavic95** [comment]
Came here as i was trying to put the bg color of my input in the theme, and it didn't work 
because the default button variant is `outline` which doesn't have a background...
so just setting my bg color as I wanted AND then setting the `variant='subtle'` fixed it for me
