### ISSUE TITLE
borderRadius prop doesn't work for SkeletonText

### ISSUE THREAD

**Issue by derherbst** [chakra-ui/chakra-ui#8786]
### Description

Hello everyone! 

When I try to add `borderRadius` property to a `SkeletonText` component it doesn't work, although this component extends the main Skeleton components interface. 

According to the source code it wasn't there in the first place. There are several props for size but no `borderRadius` among them or anywhere else.

https://github.com/chakra-ui/chakra-ui/blob/v2/packages/components/src/skeleton/skeleton-text.tsx#L75-L92

The actual prop applies to the `skeleton__group` wrapper which contains skeleton-text element (see the pic):

Has it been made intentionally, or the prop was missed?

If it was, I would be happy to contribute.

My project's `chakra-ui/react` version is `2.7.3` but it is reproduced on the `latest` one as well. (both use `chakra-ui/skeleton` version `2.1.0` anyway)

### Link to Reproduction

https://codesandbox.io/p/sandbox/runtime-paper-42ssnc?file=%2Fsrc%2Findex.tsx%3A19%2C11

### Steps to reproduce

1. Go to the codesandbox link 
2. Change the borderRadius value to anything
3. See no change

### Chakra UI Version

2.7.3

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

![image](https://github.com/user-attachments/assets/aa370a81-d81d-4c55-9921-0576372a9596)

P.S. I forked and cloned the repo and checked storybooks. It works as expected there. Only there

**Comment by segunadebayo** [comment]
Here's how to resolve this:

```tsx
function App() {
  return (
    <Box>
      <SkeletonText
        mt="4"
        noOfLines={2}
        spacing="4"
        w="500px"
        skeletonHeight="4"
        sx={{
          "& div": { borderRadius: "16px" },
        }}
      >
        I want this skeleton to have custom borderRadius
      </SkeletonText>
    </Box>
  );
}
```
