### ISSUE TITLE
Some text code is not display when in Light Mode

### ISSUE THREAD

**Issue by dunkeyyfong** [chakra-ui/chakra-ui#8789]
### Description

When I was looking at the new changes to Chakra UI in the latest version v3.0.0, I saw areas like the image below, which didn't seem to be visible. I highlighted that part and noticed that, it seems that when in Light mode, the text did not change color.
<img width="808" alt="Ảnh chụp Màn hình 2024-08-31 lúc 23 55 16" src="https://github.com/user-attachments/assets/c1038fae-cb5f-402c-b87a-64fc7151e8d6">

### Link to Reproduction

ddd

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

3.0.0

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I think this is just a small problem so I probably don't have too many questions, I also don't have a codesanbox link because I haven't seen any bugs yet :D

**Comment by victorzhu30** [comment]
ｓａｍｅ　ｑｕｅｓｔｉｏｎ，　ｍａｎｙ　ｕｒｌｓ　ｄｏｎ＇ｔ　ｅｘｉｓｔ

**Comment by segunadebayo** [comment]
Fixed now
