### ISSUE TITLE
V2 docs pointing to V3 version

### ISSUE THREAD

**Issue by lucca180** [chakra-ui/chakra-ui#8790]
### Description

Hey, the [V2 docs](https://v2.chakra-ui.com/) are pointing to V3 docs instead

### Link to Reproduction

https://v2.chakra-ui.com/

### Steps to reproduce

Visit the docs site

### Chakra UI Version

2.x

### Browser

Chrome 128

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by UNIkeEN** [comment]
+1, I can only use v1 docs to see the usage of `Modal`, `AlertDialog` and etc.

**Comment by a327958099** [comment]
Same problem, hope to restore the component library document of v2 version

**Comment by weizheweng** [comment]
Same problem

**Comment by Aeolun** [comment]
Also, V3 docs are pretty broken

**Comment by taufan-mft** [comment]
i think it's working again now

**Comment by segunadebayo** [comment]
Works now
