### ISSUE TITLE
[Slider] Incorrect type for onChange prop

### ISSUE THREAD

**Issue by franky47** [chakra-ui/chakra-ui#88]
The Slider component props inherit from `BoxProps`, which pulls an incorrect typing for `onChange`. 

From the Slider component source code and the docs, I assume the correct type is 
```ts
onChange?: (newValue: number) => void
```

I can open a PR with the suggested change.

**Comment by segunadebayo** [comment]
Thanks for the PR @franky47 .

I'll release a patch soon.
