### ISSUE TITLE
 React does not recognize the `showBorder` prop on a DOM element

### ISSUE THREAD

**Issue by dkrefta** [chakra-ui/chakra-ui#8808]
### Description

The showBorder issue is automatically appearing in my console log. I was able to add this prop to the Avatar component, but it's still annoying to see this error—it only happens in staging and local environments. Is there any way to fix this?

![image](https://github.com/user-attachments/assets/ba01f53a-42b9-4304-8552-1eab8620f3c9)

**index.js:27 Warning: React does not recognize the `showBorder` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `showborder` instead. If you accidentally passed it from a parent component, remove it from the DOM** 

### Link to Reproduction

https://codesandbox.io/p/sandbox/cold-rgb-vqlyjd?workspaceId=d3290ae6-28fd-4810-8ee3-dd2ab716971c

### Steps to reproduce

 When using the component <Avatar showBorder={true} />, it causes this error.
Check the console, and you will see the error:
index.js:27 Warning: React does not recognize the `showBorder` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `showborder` instead. If you accidentally passed it from a parent component, remove it from the DOM 

### Chakra UI Version

lastest

### Browser

latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by dkrefta** [comment]
https://github.com/chakra-ui/chakra-ui/issues/6758

**Comment by dkrefta** [comment]
https://github.com/chakra-ui/chakra-ui/issues/8805

**Comment by segunadebayo** [comment]
Do you use a custom Avatar component? This can't happen with the default Avatar component since the `showBorder` prop is restructured and doesn't get to the DOM.

If you use a custom Avatar, kindly omit the showBorder prop.

PS: Your reproduction link isn't working.
