### ISSUE TITLE
Dedupe standalone toasts: there is no `toast.isActive`

### ISSUE THREAD

**Issue by jpenna** [chakra-ui/chakra-ui#8867]
### Description

I'm looking to have standalone toasts appear only once, similar to "regular" toasts, but deduplication is not possible since `toast.isActive` is not available for standalone toasts, which is typically accessed via the `useToast()` hook.

A temporary solution could be to maintain a state for the toast ID, returned by `standaloneToast.toast()`, and implement a timeout for its duration. However, this approach is flawed because it doesn't reset the timeout if the toast is triggered again, and it prevents the toast from being displayed again until the previous one has completely closed.

### Link to Reproduction

https://codesandbox.io/p/sandbox/condescending-cherry-qkz632

### Steps to reproduce

1. Create a standalone toast like in the docs (https://v2.chakra-ui.com/docs/components/toast/usage#standalone-toasts)
2. Add an ID and duplicate the toast
3. Both will show up

### Chakra UI Version

2.9.1

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
`toast.isActive` actually exists, it was just a type issue.

![CleanShot 2024-10-04 at 19 29 42@2x](https://github.com/user-attachments/assets/c4f70f00-3dd2-41ab-b68f-a26094f2ab54)

https://codesandbox.io/p/sandbox/cocky-voice-zkt973?file=%2Fsrc%2Findex.tsx%3A18%2C14

**Comment by jpenna** [comment]
It worked! Thanks and sorry for not seeing it.
