### ISSUE TITLE
`leastDestructiveRef` prop on AlertDialog is broken in v2

### ISSUE THREAD

**Issue by Philzen** [chakra-ui/chakra-ui#8869]
### Description

The `leastDestructiveRef` prop does not work anymore in the Chakra UI v2 product line.

Worked fine in v1: 

See https://v1.chakra-ui.com/docs/components/overlay/alert-dialog#usage
→ click on "Delete Customer"
→ Cancel button is focussed

### Link to Reproduction

https://v2.chakra-ui.com/docs/components/alert-dialog/usage#usage → no element in the modal receives focus anymore whatsoever.

### Chakra UI Version

2.8.2 / 2.9.1

### Browser

Firefox 130.0

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by Philzen** [comment]
Related to https://github.com/chakra-ui/chakra-ui/issues/7976 – probably sharing the same root cause.

**Comment by segunadebayo** [comment]
The focus is actually on the element, but it's not visible.

This is because we switched the styling from focus to focus-visible. If you press the tab key or open with keyboard, you'll see the focus indicator.
