### ISSUE TITLE
Code sandbox broken in the home page

### ISSUE THREAD

**Issue by Mohammed-Yasin-Mulla** [chakra-ui/chakra-ui#8870]
### Description

The home page sandbox code is broken for some reason.
<img width="1442" alt="image" src="https://github.com/user-attachments/assets/7652ec3c-c70a-4803-9ac0-2f21d2f6704b">

### Link to Reproduction

https://v2.chakra-ui.com/

### Steps to reproduce

1. Go to `https://v2.chakra-ui.com/`
2. scroll down to Less code. More speed sectio
3. See the error on the left side
<img width="1442" alt="image" src="https://github.com/user-attachments/assets/084c3a9a-5c59-456f-b64f-c552beb08743">

### Chakra UI Version

2.9.1

### Browser

arc browser

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Works now. Thanks for letting me know
