### ISSUE TITLE
play.chakra-ui.com is broken

### ISSUE THREAD

**Issue by Ploppy3** [chakra-ui/chakra-ui#8872]
### Description

play.chakra-ui.com is broken

### Link to Reproduction

https://play.chakra-ui.com

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

1.0.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Not broken for me. Please share a screenshot
