### ISSUE TITLE
False type errors on some components

### ISSUE THREAD

**Issue by kota113** [chakra-ui/chakra-ui#8873]
### Description

IDE: Jetbrains Webstorm 2024.1.5

This error occurs when I'm using some components on Chakra UI.  
As this library utilizes `ComponentWithAs<"div", ...>` function and renders components as div, my IDE misidentifies the component as a `div` element, resulting in a false alert.  
It'll be great if this can be fixed by adding some type hints.

e.g. Alert on `NumberInput` component. 
![image](https://github.com/user-attachments/assets/6658272f-0e2e-4088-969d-884ba144f62a)

### Link to Reproduction

https://codesandbox.io/p/sandbox/keen-tdd-g83d4l

### Steps to reproduce

1. Use Jetbrains editor with default configuration
2. open or create React project
3. setup Chakra UI
4. Use some `div` components cause this error, including `NumberInput`.

### Chakra UI Version

2.9.1

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Working on a fix for this.

**Comment by kota113** [comment]
@segunadebayo Thank you!! I really appreciate it.
