### ISSUE TITLE
Error on application build

### ISSUE THREAD

**Issue by carlosvaldezfl** [chakra-ui/chakra-ui#8876]
### Description

Hello 

I'm trying to deploy an application, the problem is when i run yarn run build i'm getting the next error:

`TS2305: Module '"@chakra-ui/react"' has no exported member 'useOutsideClick'.` 

(this is only an example, because i'm getting the same for useConst and another components)
So i'm not able to deploy locally or on docker.

I have tried to fix this by changing the react version and node version but i'm still getting the same problem
React version: 18.3.1

PD. the deploy is failing on google cloud too.

Could you please help me with this?

### Link to Reproduction

no link

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.9.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is now fixed. Please upgrade to 2.9.3

**Comment by krl-gbhdigital** [comment]
It seems like any v2 build higher than 2.8.2 is gving me error:

> Module '"@chakra-ui/react"' has no exported member 'useConst'.

Do you know what the solution is for this? App will not compile.
