### ISSUE TITLE
extendTheme is not a function

### ISSUE THREAD

**Issue by Fazliddin-04** [chakra-ui/chakra-ui#8882]
### Description

When I run my next.js project in development, this is error is occuring:
```
TypeError: (0 , _chakra_ui_react__WEBPACK_IMPORTED_MODULE_14__.extendTheme) is not a function
```

Versions:
```
    "@chakra-ui/next-js": "^2.3.3",
    "@chakra-ui/react": "^2.9.4",
```

### Link to Reproduction

https://codesandbox.io/p/devbox/next-international-app-router-forked-rfqxzh

### Chakra UI Version

2.9.4

### Browser

Firefox 131.0

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is not a bug, it's related to RSC in general.

Create a dedicated file for the provider and add the `use client` directive

```tsx
'use client'

import { ChakraProvider, extendTheme } from '@chakra-ui/react'

const theme = extendTheme({
  colors: {
    error: '#DA1A32',
    success: '#3FD75B',
  },
})

export const Provider = ({
  children,
}: Readonly<{ children: React.ReactNode }>) => {
  return <ChakraProvider theme={theme}>{children}</ChakraProvider>
}
```

Import the file into the layout.tsx file.

```tsx
<html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider>{children}</Provider>
      </body>
    </html>
```

**Comment by Fazliddin-04** [comment]
Wow! I'm just wondering now how it worked in development for about half a year :)
