### ISSUE TITLE
Peer dependency conflict between `@chakra-ui/react` and `react-lorem-component`

### ISSUE THREAD

**Issue by glacius-mitchell** [chakra-ui/chakra-ui#8903]
For context, `@chakra-ui/react` 2.10.1 depends on `react-lorem-component`:

https://github.com/chakra-ui/chakra-ui/blob/c6512d6bd05f5ae48832cdc40a56b9cbb7e04709/packages/components/package.json#L49

Note that `@chakra-ui/react` 2.10.1 has a peer dependency on `react` 18 or greater:

https://github.com/chakra-ui/chakra-ui/blob/c6512d6bd05f5ae48832cdc40a56b9cbb7e04709/packages/components/package.json#L56

However, `react-lorem-component` 0.13.0 has a peer dependency on `react` 16:

https://github.com/martinandert/react-lorem-component/blob/dd7d0ca9bcf075f5ae0f57802074a123c279232b/package.json#L32-L34

```json
  "peerDependencies": {
    "react": "16.x"
  },
```

These are incompatible, leading to peer dependency warnings when attempting to install `@chakra-ui/react` 2.10.1:

```
 WARN  Issues with peer dependencies found
my-example-package
└─┬ @chakra-ui/react 2.10.1
  └─┬ react-lorem-component 0.13.0
    └── ✕ unmet peer react@16.x: found 18.3.1
```

From what I can tell, `react-lorem-component` is only used in two places in the source code for `@chakra-ui/react` 2.10.1:

https://github.com/chakra-ui/chakra-ui/blob/c6512d6bd05f5ae48832cdc40a56b9cbb7e04709/packages/components/src/modal/modal.stories.tsx#L5

https://github.com/chakra-ui/chakra-ui/blob/c6512d6bd05f5ae48832cdc40a56b9cbb7e04709/packages/components/src/number-input/number-input.stories.tsx#L4

Neither of these looks like it requires `react-lorem-component` to be a production dependency.

Could `react-lorem-component` be switched from a production dependency to a dev dependency for `@chakra-ui/react` v2 to avoid the peer dependency conflict for consumers of this library? (Or perhaps you'd like to remove it altogether or switch to a more modern alternative given that it hasn't been updated in 7 years?)

**Comment by segunadebayo** [comment]
Good catch.  I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by mirror-ru** [comment]
![image](https://github.com/user-attachments/assets/92b2420b-57d1-49c7-9d77-830fbc7889ab)

**Comment by WichardRiezebos** [comment]
When can I expect this release? It's blocking our development.

**Comment by mirror-ru** [comment]
> When can I expect this release? It's blocking our development.

Already fixed, check latest update
