### ISSUE TITLE
Gradient Props Not Working as Expected with Text Component And bgClip="Text" prop

### ISSUE THREAD

**Issue by Plasmatronics** [chakra-ui/chakra-ui#8904]
### Description

When applying the gradients with the gradientFrom, gradientTo, and bgGradient(direction) props, and then applying bgClip="Text" on a Text or Heading component, no gradient is rendered.

### Link to Reproduction

https://codesandbox.io/p/sandbox/peaceful-ritchie-4xpdf3?file=%2Fsrc%2Findex.tsx%3A21%2C9&workspaceId=04c0dc82-137b-495b-9f48-3685476ec068

### Steps to reproduce

1). Go to code sandbox link
2). Examine the lack of gradient on the text and heading components provided despite appropriate gradient props.

### Chakra UI Version

3.0.0-next.26

### Browser

Version 129.0.6668.60

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![gradientNotWorkingChakra](https://github.com/user-attachments/assets/d6400147-a0df-4804-b13a-a89cd55bc9f5)

**Comment by Plasmatronics** [comment]
@stevensecreti

**Comment by stevensecreti** [comment]
https://codesandbox.io/p/sandbox/cranky-williams-5ws29m?workspaceId=500deda5-252c-44cc-abda-6907aaf8ed0b
