### ISSUE TITLE
Incorrect package.json, missing peerDependencies

### ISSUE THREAD

**Issue by agarwalvaibhav0211** [chakra-ui/chakra-ui#8912]
### Description

I'm using yarn pnp, so caught this error while working with a project. `@chakra-ui/utils` package lists react as a peerDependency. But `@chakra-ui/styled-system`, `@chakra-ui/theme-tools` and `@chakra-ui/theme` use the `@chakra-ui/utils` package without adding react to their peerDependency. 

These can be fixed by adding the react package as peerDependency in all the consuming packages

### Link to Reproduction

N/A

### Steps to reproduce

N/A

### Chakra UI Version

2.10

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Please upgrade all packages to their latest versions

**Comment by agarwalvaibhav0211** [comment]
@segunadebayo, I'm on the latest package version. Also, I can see this issue on the latest npm build code as well:
![image](https://github.com/user-attachments/assets/4959a4ef-9231-4e31-b1d5-84c0b41655fb)
![image](https://github.com/user-attachments/assets/dc6386dc-6863-4d41-9582-fee7c5300432)

**Comment by Dartoxian** [comment]
Also seeing this - 2.10 was released with no changelog entry and is not installing required packages in the same way 2.8.2 did.
