### ISSUE TITLE
v3 scrollBehavior='inside' not working

### ISSUE THREAD

**Issue by Bluorenge** [chakra-ui/chakra-ui#8916]
### Description

v3 scrollBehavior='inside' not working. 

### Link to Reproduction

https://github.com/chakra-ui/chakra-ui/tree/main/packages/react/src/components/dialog

### Chakra UI Version

@chakra-ui/react@3.0.0-next.29

### Browser

Google chrome 131

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
It works in the docs as you can see https://next.chakra-ui.com/docs/components/dialog#inside-scroll

If it's not working for you, please send a reproduction

**Comment by Bluorenge** [comment]
the problem been here: `export const DialogRoot = chakra(ChakraDialog.Root, dialogRecipe);`
