### ISSUE TITLE
Next.js package loading invalid import

### ISSUE THREAD

**Issue by DeJayDev** [chakra-ui/chakra-ui#8921]
### Description

During a `next build`, the `@chakra-ui/next-js` package triggers an error for an erroneous import.

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/dj/.../playless/node_modules/next/image' imported from /home/dj/.../playless/node_modules/@chakra-ui/next-js/dist/esm/image.mjs
Did you mean to import "next/image.js"?
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1169:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:540:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:509:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:96:40)
    at link (node:internal/modules/esm/module_job:95:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///home/dj/.../playless/node_modules/next/image'
}
```

### Link to Reproduction

I cannot reproduce this in a clean CodeSandbox.

### Steps to reproduce

1. Seemingly, just import any component `@chakra-ui/next-js`. The problematic project uses `Link`.

### Chakra UI Version

2.10.1

### Additional Information

`@chakra-ui/next-js@2.4.1`
`next@14.2.15`

**Comment by mountainash** [comment]
Also experiencing this with the same package versions. Attempting to swap out with `@chakra-ui/react` doesn't work as we make use of the [`locale`](https://nextjs.org/docs/pages/api-reference/components/link#locale) prop which isn't on the React Link

**Comment by mountainash** [comment]
Narrowing it down to what worked before, I'm leading to think this is a Yarn v4.5.0 issue, as the latest packages are working when `install` and `build` with Yarn v1.22.22.

**Comment by DeJayDev** [comment]
I have this issue with `npm`, but thinking about resolution is interesting. 

My tsconfig defines:
```
    "module": "esnext",
    "moduleResolution": "node",
```

It's likely this can be fixed with the proper project configuration, which is why I can't force this issue in a CodeSandbox?

**Comment by segunadebayo** [comment]
I just pushed a fix for this. It's related to the lack of `use client` directive in the component.

We'll release an update shortly. If the issue persists after upgrading, I'll re-open it.

**Comment by jonahallibone** [comment]
This isn't resolved if you're using pages router from what i can tell
