### ISSUE TITLE
Border Radius 'none ' is not working on chakra ui v3

### ISSUE THREAD

**Issue by techwithtwin** [chakra-ui/chakra-ui#8923]
### Description

When I added borderRadius='none' to my button I expected to see the button with no borders but in turn nothing happens

### Link to Reproduction

https://codesandbox.io/p/devbox/4szqrs

### Steps to reproduce

1. Go to app/page.tsx
2. Check on the button
3. Make sure the preview is running
4. See that with borderRadius='none' the button still has a radius

### Chakra UI Version

3.0.0-next.29

### Browser

Google Chrome

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Please add this to the feedback discussion. Please set border radius to zero in the meantime.
