### ISSUE TITLE
Placement on the toaster.create function is not working correctly

### ISSUE THREAD

**Issue by techwithtwin** [chakra-ui/chakra-ui#8924]
### Description

When I added placement='top' or 'bottom' to the toaster .create() function it is not working.
I have added the toaster component in the root layout and also I have installed the toaster using the snippet add.

### Link to Reproduction

https://codesandbox.io/p/devbox/chakra-ui-v3-issue-forked-xvp8v4?workspaceId=36641a55-24d1-4370-850f-6e0f6019cdef

### Steps to reproduce

1. Go to app/my-button.tsx
2. Click on the button don't he preview which should trigger the toast
3. see no change and then remove the placement prop refresh the preview and see the toaster works

### Chakra UI Version

3.0.0-next.29

### Browser

Google Chrome

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Please add these issues to the v3 feedback discussion.

Set the placement in the createToaster function in the components/ui/toaster file.
