### ISSUE TITLE
Importing from `@chakra-ui/next-js` errors on `next/image not found`

### ISSUE THREAD

**Issue by jonahallibone** [chakra-ui/chakra-ui#8926]
### Description

When I try and use the `@chakra-ui/next-js` package for `<Link />` I get an error related to`next/image`

<img width="1512" alt="Screenshot 2024-10-09 at 11 29 52 PM" src="https://github.com/user-attachments/assets/01533c48-fcef-4343-a986-7998124338fe">

I see related issues but they seem to be addressing `app` router but I am using `pages` router

Error is:

```
Error: Failed to load external module @chakra-ui/next-js: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/jonahallibone/code/temelio/temelio-backend/node_modules/next/image' imported from /Users/jonahallibone/code/temelio/temelio-backend/node_modules/@chakra-ui/next-js/dist/esm/image.mjs
Did you mean to import next/image.js?
```

### Link to Reproduction

N/A

### Steps to reproduce

Upgrade to these verisons:

```
"@chakra-ui/anatomy": "^2.3.4",
"@chakra-ui/next-js": "^2.4.2",
"@chakra-ui/react": "^2.10.2",
"@chakra-ui/react-use-size": "^2.1.0",
"@chakra-ui/styled-system": "^2.11.2",
```

### Chakra UI Version

2.10.1

### Operating System

- [X] macOS

**Comment by lucky-victory1** [comment]
I came here to report this too, I have spent hours debugging this since I wasn't even importing `Image` component anywhere. 
![image](https://github.com/user-attachments/assets/3988f6cf-9b4a-441e-b6dd-ba8c75f3ec01)

**Comment by jonahallibone** [comment]
@lucky-victory1 I'm also not using the Image component

**Comment by jonahallibone** [comment]
> I came here to report this too, I have spent hours debugging this since I wasn't even importing `Image` component anywhere. ![image](https://private-user-images.githubusercontent.com/113092061/375360291-3988f6cf-9b4a-441e-b6dd-ba8c75f3ec01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1Njk4NjQsIm5iZiI6MTcyODU2OTU2NCwicGF0aCI6Ii8xMTMwOTIwNjEvMzc1MzYwMjkxLTM5ODhmNmNmLTliNGEtNDQxZS1iNmRkLWJhOGM3NWYzZWMwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxNDEyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYmNiYWU1MzIxOGRjNzE1MTE1ZDZlMTliZTFmNWUwYzkyY2QxMDEzZWVlNTk5MDUxM2QzMWY4NjQ1MGEyYjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.18mW-jsR9QPCWiY9A9rZtMeZTlZnqu_MgiMGfB-NNcA)

```
transpilePackages: [
  "@chakra-ui/nextjs",
],
```

in my `next.config.js` worked for me in the time being

**Comment by segunadebayo** [comment]
Unfortunately, debugging and fixing v2 isn't top priority for us at the moment.

I recommend not using the `@chakra-ui/next-js` and working with the native image from Next.js or Chakra. You could probably copy the code from the v2 branch as well.

**Comment by jonahallibone** [comment]
@segunadebayo I appreciate that v2 is not the priority, but we aren't using the. `@chakra-ui/next-js` package for images at all, we are just using it for the links (which if i understand fixes the issues with the props be forwarded correctly for `href` as well as some other issues). We do plan to upgrade to chakra v3 at some point, but as of now the latest version of chakra ui v2 will be broken for all projects which use the `@chakra-ui/next-js` package in any way at all. I think the fix is probably related to the build process which changed sometime before the v3 release.

**Comment by DeJayDev** [comment]
This has been the case since #8921 where the maintainer states:

> We'll release an update shortly. If the issue persists after upgrading, I'll re-open it.

And after receiving a report that it was still broken, ignored it. This happened before the v3 loop, but it's probably fruitless to depend on the maintainer. Unfortunately even with v3 it's still a gamble to actually have problems solved.
