### ISSUE TITLE
v2.10.3 now requires every unit test to be wrapped in the theme provider or  else errors 'undefined is not a function'

### ISSUE THREAD

**Issue by ra-lfaro** [chakra-ui/chakra-ui#8948]
### Description

in 2.8.2 It was not a requirement to use the chakra provider for unit tests when paired with '@testing-library/react'. Now every test without a wrapper fails with the error

```
 TypeError: undefined is not a function
        at Array.filter (<anonymous>)
```

![image](https://github.com/user-attachments/assets/61097055-4346-4506-a473-89111833fc4d)

![image](https://github.com/user-attachments/assets/d4a653d2-35bd-4157-9cd2-c42a3855356e)

Before i go updating every unit test, wanted to double check this is intentional or a bug?

Thanks!

### Link to Reproduction

https://codesandbox.io/p/sandbox/busy-panka-t4qqzs?workspaceId=dffd4bcf-f88e-417f-bcce-406f15ad7df5
### Steps to reproduce

Run tests in samebox

### Chakra UI Version

2.10.3

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Yes, we recommend wrapping tests in the ChakraProvider to resolve the theme and color mode correctly.
