### ISSUE TITLE
Dependencies missing in @chakra-ui/react after update

### ISSUE THREAD

**Issue by ArthurCalazans** [chakra-ui/chakra-ui#8951]
### Description

Hi,

Up until October 7th, running yarn install was working correctly and installing all necessary dependencies, including those for @chakra-ui/react. However, after this date, dependencies for @chakra-ui/react are no longer being installed properly.

I noticed that in version 2.10.3 of @chakra-ui/react, not all required dependencies are listed. On the other hand, version 2.8.2 does include all the necessary dependencies. The issue I am facing is that my package.json has @chakra-ui/react set to ^2.2.8, and this hasn't been modified in over two years. Additionally, the Node.js version being used is 18, and that hasn't changed either.

I will provide evidence from the package.json of @chakra-ui/react for reference.

Details:

Current package.json entry: "@chakra-ui/react": "^2.2.8"
No changes to the Node.js version (using Node.js 18).
Yarn is not pulling all necessary dependencies for Chakra UI after October 7th.
Please let me know if there's any additional information or logs that would be helpful.
[package-2.8.2.json](https://github.com/user-attachments/files/17439604/package-2.8.2.json)
[package2.10.3.json](https://github.com/user-attachments/files/17439606/package2.10.3.json)
[yarn.lock-dontwork.txt](https://github.com/user-attachments/files/17439609/yarn.lock-dontwork.txt)
[yarn.lock-work.txt](https://github.com/user-attachments/files/17439610/yarn.lock-work.txt)

### Link to Reproduction

https://github.com/chakra-ui/chakra-ui/

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.2.8

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by ArthurCalazans** [comment]
Here is the error I'm seeing during build:

Error: The following dependencies are imported but could not be resolved:

  @chakra-ui/button (imported by /app/src/components/Table/parts/PageSize.jsx)

Are they installed?
    at file:///app/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:50655:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///app/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:50160:26
4:00:19 PM [vite] Pre-transform error: Failed to resolve import "@chakra-ui/button" from "src/components/Table/parts/Prev.jsx". Does the file exist?
4:00:19 PM [vite] Pre-transform error: Failed to resolve import "@chakra-ui/button" from "src/components/Table/parts/Next.jsx". Does the file exist?
4:00:19 PM [vite] Pre-transform error: Failed to resolve import "@chakra-ui/button" from "src/components/Table/parts/ForwardBackward.jsx". Does the file exist?
4:00:19 PM [vite] Pre-transform error: Failed to resolve import "@chakra-ui/button" from "src/components/Table/parts/PageSize.jsx". Does the file exist?
✘ [ERROR] Could not resolve "@chakra-ui/icon"

    node_modules/chakra-ui-steps/dist/chakra-ui-steps.mjs:8:33:
      8 │ import { createIcon as pe } from "@chakra-ui/icon";
        ╵                                  ~~~~~~~~~~~~~~~~~

  You can mark the path "@chakra-ui/icon" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "@chakra-ui/react-context"

    node_modules/chakra-ui-steps/dist/chakra-ui-steps.mjs:9:36:
      9 │ import { createContext as he } from "@chakra-ui/react-context";
        ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@chakra-ui/react-context" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

4:00:24 PM [vite] error while updating dependencies:
Error: Build failed with 2 errors:
node_modules/chakra-ui-steps/dist/chakra-ui-steps.mjs:8:33: ERROR: Could not resolve "@chakra-ui/icon"
node_modules/chakra-ui-steps/dist/chakra-ui-steps.mjs:9:36: ERROR: Could not resolve "@chakra-ui/react-context"

**Comment by segunadebayo** [comment]
The packages were restructured into a single package.

Please import them directly from `@chakra-ui/react/button` and `@chakra-ui/react/icon` accordingly.

Sorry for the inconvenience caused.
