### ISSUE TITLE
Chakra Pro permission issue

### ISSUE THREAD

**Issue by edukinara** [chakra-ui/chakra-ui#8954]
### Description

Recently been unable to view component code in Pro even with a licensed account.

### Link to Reproduction

N/A

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.10.3

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Please send an email to support@chakra-ui.com to resolve this

**Comment by cschroeter** [comment]
@edukinara 

Issue should be fixed by now. Sorry for the inconvenience
