### ISSUE TITLE
v2.10.3 Menu breaks test

### ISSUE THREAD

**Issue by moczolaszlo** [chakra-ui/chakra-ui#8955]
### Description

Hi,
In the latest version the Menu drops a strange error inside tests:

`TypeError: menuRef.current?.scrollTo is not a function`

I made a codesandbox preview, you can see the failing test there.

I just found this commit from @segunadebayo , I think this is related: https://github.com/chakra-ui/chakra-ui/commit/39e55ddbbd7fedc0f5a4c98a2446d4fc8f371568

Maybe a little guard could help:
```tsx
if ( menuRef.current?.scrollTo) {
    menuRef.current?.scrollTo(0, 0);
}    
 ```
 
Thank you for the answer!

### Link to Reproduction

https://codesandbox.io/p/sandbox/trusting-shadow-zpw5nx?workspaceId=0059ddce-7b97-4ae1-9848-97d8eb0382f4

### Steps to reproduce

Just run the test in the codesandbox.

### Chakra UI Version

2.10.3

**Comment by segunadebayo** [comment]
Please add these to your tests

```ts
window.Element.prototype.scrollTo = () => {}
```

**Comment by moczolaszlo** [comment]
Thank you very much, its works.
