### ISSUE TITLE
System color mode gets out of sync

### ISSUE THREAD

**Issue by cranium** [chakra-ui/chakra-ui#8959]
### Description

I use Chakra UI in production with the recommendations on using system color mode outlined [here](https://v2.chakra-ui.com/docs/styled-system/color-mode).

I'm getting reports from users of the color mode being desynced from their system settings:
![image](https://github.com/user-attachments/assets/65f834bb-3b3a-408d-93ec-c4529a562fb7)

Looking into it on my own, it seems like if I change my system setting without the site open, or maybe in some cases using the day/night auto mode on Mac, the page will load with the value stored in local storage and not the system value.

Is this a bug? It seems like an issue if Chakra is persisting a color mode setting when I always want to use and react to the system setting.

Should I make a new color storage manager that just always does a lookup to the system color? Are there downsides to that approach?

### Link to Reproduction

not able to repro in code sandbox

### Chakra UI Version

2.7.0

### Browser

Latest Chrome, Firefox

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by cranium** [comment]
I'm currently testing this as a workaround:

![image](https://github.com/user-attachments/assets/12d1a0b4-69c9-4f5e-8700-c4cc945571aa)

Its pretty confusing to me why the default is to persist the color mode if I'm not using SSR and just want to match the user's system setting.

**Comment by cranium** [comment]
I have received reports that the workaround fixed the issue for people that it wasn't working for.

**Comment by segunadebayo** [comment]
That sounds good. Thanks for sharing your fix.

We don't have the capacity to work on v2 at the moment. Thanks for understanding
