### ISSUE TITLE
[Regression] Unable to scroll dialog with `scrollBehavior="outside"`

### ISSUE THREAD

**Issue by glacius-mitchell** [chakra-ui/chakra-ui#8978]
### Description

In Chakra UI v2, when there's a long modal with `scrollBehavior="outside"` (e.g. go to the `Modal overflow behavior` section of https://v2.chakra-ui.com/docs/components/modal#modal-overflow-behavior, select `outside`, and click `Trigger modal`), it can be scrolled no matter where your mouse is.

In Chakra UI v3, when there's a long dialog with `scrollBehavior="outside"` (e.g. go to the `Outside Scroll` section of https://www.chakra-ui.com/docs/components/dialog#outside-scroll and click `Outside Scroll`), it can only be scrolled if your mouse is on top of the dialog. If your mouse is positioned outside of the dialog, it cannot be scrolled. In addition, on iOS Safari, it cannot be scrolled at all.

### Link to Reproduction

https://www.chakra-ui.com/docs/components/dialog#outside-scroll

### Steps to reproduce

Go to the `Outside Scroll` section of https://www.chakra-ui.com/docs/components/dialog#outside-scroll and click `Outside Scroll`. On desktop, you will find that you cannot scroll the dialog if your mouse is not on top of the dialog. On iOS Safari, you will find that you cannot scroll the dialog at all.

Desktop diagram:

> ![www chakra-ui com_docs_components_dialog](https://github.com/user-attachments/assets/976e5b45-4c7e-4049-a6ac-e9d6cd629917)

Mobile diagram:

> <img width="375" src="https://github.com/user-attachments/assets/cad89ec8-c0bf-40c8-8390-c743fd64536f">

### Chakra UI Version

3.0.0

### Browser

Chrome 129.0.6668.90, Safari 18.0.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by khotcholava** [comment]
**Proposal**

It would be great to provide a property like scroll="body" to apply scrolling to the body, or scroll="modal" to apply scrolling specifically to the modal.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
