### ISSUE TITLE
Missing Separator component in Chakra CLI-generated components after migration to v3.0.0

### ISSUE THREAD

**Issue by JoShMiQueL** [chakra-ui/chakra-ui#8979]
### Description

After migrating to Chakra UI v3.0.0, the Divider component has been renamed to Separator, as per the migration guide. However, when using @chakra-ui/cli to generate local components (e.g., accessible via @/components/ui), the Separator component is not generated. This leads to the inability to use the renamed Separator component through the local component imports. Other components are generated correctly, but this one seems to be missing.

### Link to Reproduction

https://codesandbox.io/p/devbox/elated-gianmarco-ylx6g8?workspaceId=d70893f5-77e0-415c-8bbd-c818e26b8a78

### Steps to reproduce

1. Create a new project with Chakra UI 3.0.0
2. Use @chakra-ui/cli to generate the local components.
3. Check the @/components/ui folder.
4. Observe that the Separator component is not generated.

### Chakra UI Version

3.0.0

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

The issue seems specific to the renaming of Divider to Separator. Other components are generated correctly after running @chakra-ui/cli, but the Separator is missing entirely from the output.

**Comment by segunadebayo** [comment]
Separator should be imported directly from `@chakra-ui/react`
