### ISSUE TITLE
Error When Adding Chakra UI CLI Snippets 

### ISSUE THREAD

**Issue by Fazliddin-04** [chakra-ui/chakra-ui#8984]
### Description

When installing @chakra-ui/react v3 in a React & Vite project, running the @chakra-ui/cli snippets command returns the following error:
```
┌  Chakra CLI ⚡️
node:internal/modules/esm/resolve:854
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@chakra-ui/react' imported from C:\Users\user\AppData\Local\npm-cache\_npx\de2e382d70c335ff\node_modules\@chakra-ui\cli\dist\esm\commands\eject.js
    at packageResolve (node:internal/modules/esm/resolve:854:9)
    at moduleResolve (node:internal/modules/esm/resolve:927:18)
    at defaultResolve (node:internal/modules/esm/resolve:1169:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:96:40)
    at link (node:internal/modules/esm/module_job:95:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.18.0
```

I attempted to reproduce this issue on CodeSandbox, but it worked without any errors. What could be the potential reasons for this problem?

### Link to Reproduction

https://codesandbox.io/p/live/c9bd65da-0048-44fe-918d-b0b463a3d44d

### Steps to reproduce

1. Create Vite project with React template
2. Install Chakra UI step by step to your project.
3. Run `npx @chakra-ui/cli snippet add`

### Chakra UI Version

3.0.0

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

_package.json_
```
{
  "name": "mfe_kds",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc -b && vite build",
    "lint": "eslint .",
    "preview": "vite preview"
  },
  "dependencies": {
    "@chakra-ui/react": "^3.0.0",
    "@emotion/react": "^11.13.3",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@eslint/js": "^9.13.0",
    "@types/react": "^18.3.11",
    "@types/react-dom": "^18.3.1",
    "@vitejs/plugin-react": "^4.3.3",
    "eslint": "^9.13.0",
    "eslint-plugin-react-hooks": "^5.0.0",
    "eslint-plugin-react-refresh": "^0.4.13",
    "globals": "^15.11.0",
    "typescript": "~5.6.2",
    "typescript-eslint": "^8.10.0",
    "vite": "^5.4.9"
  }
}
```

**Comment by segunadebayo** [comment]
Please upgrade your node version to 20 or more.

**Comment by Fazliddin-04** [comment]
Hi @segunadebayo! Thanks for making UIs more easier and satisfying!

First I tried on Node v22.8.0, cleared npm cache, and switched to LTS. not working anyway. I think, something is wrong with my device.
But now, it is okay to use core library also without CLI snippets.

**Comment by woojenoh** [comment]
I also get the same error.

**Comment by schunlee** [comment]
I also meet error as below:
PS C:\Users\Administrator\learn-chakra-ui> npx @chakra-ui/cli snippet add
┌  Chakra CLI ⚡️
file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108
                        reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error));
                               ^

FetchError: request to https://chakra-v3-docs.vercel.app/compositions/index.json failed, reason: connect ETIMEDOUT 31.13.82.33:443
    at ClientRequest.<anonymous> (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108:11)
    at emitErrorEvent (node:_http_client:101:11)
    at TLSSocket.socketErrorListener (node:_http_client:504:5)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  erroredSysCall: 'connect'
}

Node.js v20.18.0

but I can visit  https://chakra-v3-docs.vercel.app/compositions/index.json via browser

**Comment by SANGET** [comment]
> I also meet error as below: PS C:\Users\Administrator\learn-chakra-ui> npx @chakra-ui/cli snippet add ┌ Chakra CLI ⚡️ file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108 reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error)); ^
> 
> FetchError: request to https://chakra-v3-docs.vercel.app/compositions/index.json failed, reason: connect ETIMEDOUT 31.13.82.33:443 at ClientRequest. (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108:11) at emitErrorEvent (node:_http_client:101:11) at TLSSocket.socketErrorListener (node:_http_client:504:5) at TLSSocket.emit (node:events:519:28) at emitErrorNT (node:internal/streams/destroy:169:8) at emitErrorCloseNT (node:internal/streams/destroy:128:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { type: 'system', errno: 'ETIMEDOUT', code: 'ETIMEDOUT', erroredSysCall: 'connect' }
> 
> Node.js v20.18.0
> 
> but I can visit https://chakra-v3-docs.vercel.app/compositions/index.json via browser

Same problem, is there a solution?

**Comment by abdulazizdevv** [comment]
same issuse 😢

**Comment by Daidalos117** [comment]
same here :/

**Comment by Daidalos117** [comment]
Had the same issue. What I did to solve it:
Switch to the folder with the script project, take the path from the error:
`node:internal/modules/esm/resolve:854
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@chakra-ui/react' imported from /Users/user/.npm/_npx/de2e382d70c335ff/node_modules/@chakra-ui/cli/dist/esm/commands/eject.js
    at packageResolve (node:internal/modules/esm/resolve:854:9)
    at moduleResolve (node:internal/modules/esm/resolve:927:18)`

`cd /Users/user/.npm/_npx/de2e382d70c335ff`
and install the chakra ui manually:
`npm install @chakra-ui/react`

After that, snippets installed sucesfully. I don't know why, but I didn't have the package installed in that npx project.

**Comment by Agicon-Frederik** [comment]
I had the same issue.
@Daidalos117 : your workaround worked for me too ! 
Tnx

**Comment by kingport** [comment]
> I also meet error as below: PS C:\Users\Administrator\learn-chakra-ui> npx @chakra-ui/cli snippet add ┌ Chakra CLI ⚡️ file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108 reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error)); ^
> 
> FetchError: request to https://chakra-v3-docs.vercel.app/compositions/index.json failed, reason: connect ETIMEDOUT 31.13.82.33:443 at ClientRequest. (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108:11) at emitErrorEvent (node:_http_client:101:11) at TLSSocket.socketErrorListener (node:_http_client:504:5) at TLSSocket.emit (node:events:519:28) at emitErrorNT (node:internal/streams/destroy:169:8) at emitErrorCloseNT (node:internal/streams/destroy:128:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { type: 'system', errno: 'ETIMEDOUT', code: 'ETIMEDOUT', erroredSysCall: 'connect' }
> 
> Node.js v20.18.0
> 
> but I can visit https://chakra-v3-docs.vercel.app/compositions/index.json via browser

same issuse 😢

**Comment by sephialaureenciaa** [comment]
I have the same issue

**Comment by betonix** [comment]
why is closed? same issue here

**Comment by emsurezhang** [comment]
MACOS has the save issue

**Comment by eliakorkmaz** [comment]
i followed the installation and got the same error, fix my issue with installing `@chakra-ui/cli` before I add snippets 

try this command to install `cli` separately

`npm i @chakra-ui/cli`

then 

`npx @chakra-ui/cli snippet add`

**Comment by raffeyang** [comment]
same issue

**Comment by satarovbekzhan** [comment]
> i followed the installation and got the same error, fix my issue with installing `@chakra-ui/cli` before I add snippets
> 
> try this command to install `cli` separately
> 
> `npm i @chakra-ui/cli`
> 
> then
> 
> `npx @chakra-ui/cli snippet add`

This one worked for me

**Comment by ziyiyu** [comment]
> Quote reply
> Refere



> I also meet error as below: PS C:\Users\Administrator\learn-chakra-ui> npx @chakra-ui/cli snippet add ┌ Chakra CLI ⚡️ file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108 reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error)); ^
> 
> FetchError: request to https://chakra-v3-docs.vercel.app/compositions/index.json failed, reason: connect ETIMEDOUT 31.13.82.33:443 at ClientRequest. (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108:11) at emitErrorEvent (node:_http_client:101:11) at TLSSocket.socketErrorListener (node:_http_client:504:5) at TLSSocket.emit (node:events:519:28) at emitErrorNT (node:internal/streams/destroy:169:8) at emitErrorCloseNT (node:internal/streams/destroy:128:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { type: 'system', errno: 'ETIMEDOUT', code: 'ETIMEDOUT', erroredSysCall: 'connect' }
> 
> Node.js v20.18.0
> 
> but I can visit https://chakra-v3-docs.vercel.app/compositions/index.json via browser

same issuse 😢

**Comment by wxul** [comment]
> I also meet error as below: PS C:\Users\Administrator\learn-chakra-ui> npx @chakra-ui/cli snippet add ┌ Chakra CLI ⚡️ file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108 reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error)); ^
> 
> FetchError: request to https://chakra-v3-docs.vercel.app/compositions/index.json failed, reason: connect ETIMEDOUT 31.13.82.33:443 at ClientRequest. (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108:11) at emitErrorEvent (node:_http_client:101:11) at TLSSocket.socketErrorListener (node:_http_client:504:5) at TLSSocket.emit (node:events:519:28) at emitErrorNT (node:internal/streams/destroy:169:8) at emitErrorCloseNT (node:internal/streams/destroy:128:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { type: 'system', errno: 'ETIMEDOUT', code: 'ETIMEDOUT', erroredSysCall: 'connect' }
> 
> Node.js v20.18.0
> 
> but I can visit https://chakra-v3-docs.vercel.app/compositions/index.json via browser

The domain vercel.app is banned in some places, and I guess you were using a VPN to visit the link in the browser. In this case, you can try to use a proxy to run the CLI like `HTTP_PROXY=http://127.0.0.1:7890 HTTPS_PROXY=http://127.0.0.1:7890 npx @chakra-ui/cli snippet add`

**Comment by DoubleRu1** [comment]
> > I also meet error as below: PS C:\Users\Administrator\learn-chakra-ui> npx @chakra-ui/cli snippet add ┌ Chakra CLI ⚡️ file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108 reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error)); ^
> > FetchError: request to https://chakra-v3-docs.vercel.app/compositions/index.json failed, reason: connect ETIMEDOUT 31.13.82.33:443 at ClientRequest. (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108:11) at emitErrorEvent (node:_http_client:101:11) at TLSSocket.socketErrorListener (node:_http_client:504:5) at TLSSocket.emit (node:events:519:28) at emitErrorNT (node:internal/streams/destroy:169:8) at emitErrorCloseNT (node:internal/streams/destroy:128:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { type: 'system', errno: 'ETIMEDOUT', code: 'ETIMEDOUT', erroredSysCall: 'connect' }
> > Node.js v20.18.0
> > but I can visit https://chakra-v3-docs.vercel.app/compositions/index.json via browser
> 
> The domain vercel.app is banned in some places, and I guess you were using a VPN to visit the link in the browser. In this case, you can try to use a proxy to run the CLI like `HTTP_PROXY=http://127.0.0.1:7890 HTTPS_PROXY=http://127.0.0.1:7890 npx @chakra-ui/cli snippet add`

this works for me, wonderful solution

**Comment by chenpeng123** [comment]
> > I also meet error as below: PS C:\Users\Administrator\learn-chakra-ui> npx @chakra-ui/cli snippet add ┌ Chakra CLI ⚡️ file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108 reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error)); ^
> > FetchError: request to https://chakra-v3-docs.vercel.app/compositions/index.json failed, reason: connect ETIMEDOUT 31.13.82.33:443 at ClientRequest. (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108:11) at emitErrorEvent (node:_http_client:101:11) at TLSSocket.socketErrorListener (node:_http_client:504:5) at TLSSocket.emit (node:events:519:28) at emitErrorNT (node:internal/streams/destroy:169:8) at emitErrorCloseNT (node:internal/streams/destroy:128:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { type: 'system', errno: 'ETIMEDOUT', code: 'ETIMEDOUT', erroredSysCall: 'connect' }
> > Node.js v20.18.0
> > but I can visit https://chakra-v3-docs.vercel.app/compositions/index.json via browser
> 
> The domain vercel.app is banned in some places, and I guess you were using a VPN to visit the link in the browser. In this case, you can try to use a proxy to run the CLI like `HTTP_PROXY=http://127.0.0.1:7890 HTTPS_PROXY=http://127.0.0.1:7890 npx @chakra-ui/cli snippet add`

this works for me, wonderful solution

**Comment by lm83680** [comment]
> > 我还遇到如下错误： PS C:\Users\Administrator\learn-chakra-ui> npx @chakra-ui/cli snippet add ┌ Chakra CLI ⚡️ file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108 rejection(new FetchError( `request to ${request.url} failed, reason: ${error.message}`, 'system', error)); ^
> > [FetchError: 对https://chakra-v3-docs.vercel.app/compositions/index.json](https://chakra-v3-docs.vercel.app/compositions/index.json)的请求失败，原因：在 ClientRequest 处连接 ETIMEDOUT 31.13.82.33:443。 （file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108:11）在 emitErrorEvent（node:_http_client:101:11）处在 TLSSocket.socketErrorListener（node:_http_client:504:5）处在 TLSSocket.emit（node:events:519:28）处在 emitErrorNT（node:internal/streams/destroy:169:8）处在 emitErrorCloseNT（node:internal/streams/destroy:128:3）处在 process.processTicksAndRejections（node:internal/process/task_queues:82:21）{类型：'system'，errno：'ETIMEDOUT'，代码：'ETIMEDOUT'，错误系统调用：‘连接’ }
> > Node.js v20.18.0
> > 但我可以通过浏览器访问https://chakra-v3-docs.vercel.app/compositions/index.json
> 
> 域名 vercel.app 在某些地方被禁止，我猜你是使用 VPN 在浏览器中访问链接。在这种情况下，你可以尝试使用代理来运行 CLI，例如`HTTP_PROXY=http://127.0.0.1:7890 HTTPS_PROXY=http://127.0.0.1:7890 npx @chakra-ui/cli snippet add`

Perfect

**Comment by Delay-n-days** [comment]
set HTTP_PROXY=http://127.0.0.1:7890
set HTTPS_PROXY=http://127.0.0.1:7890
npm cache clean --force
npm config set proxy=http://127.0.0.1:7890
npm config set https-proxy http://127.0.0.1:7890
npx @chakra-ui/cli snippet add

**Comment by fanmengwen** [comment]
not work for me

**Comment by Rogant** [comment]
> i followed the installation and got the same error, fix my issue with installing `@chakra-ui/cli` before I add snippets
> 
> try this command to install `cli` separately
> 
> `npm i @chakra-ui/cli`
> 
> then
> 
> `npx @chakra-ui/cli snippet add`

This works for me, should be included in the docs!
Cheers!

**Comment by NNNewbie477** [comment]
> > I also meet error as below: PS C:\Users\Administrator\learn-chakra-ui> npx @chakra-ui/cli snippet add ┌ Chakra CLI ⚡️ file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108 reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error)); ^
> > FetchError: request to https://chakra-v3-docs.vercel.app/compositions/index.json failed, reason: connect ETIMEDOUT 31.13.82.33:443 at ClientRequest. (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108:11) at emitErrorEvent (node:_http_client:101:11) at TLSSocket.socketErrorListener (node:_http_client:504:5) at TLSSocket.emit (node:events:519:28) at emitErrorNT (node:internal/streams/destroy:169:8) at emitErrorCloseNT (node:internal/streams/destroy:128:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { type: 'system', errno: 'ETIMEDOUT', code: 'ETIMEDOUT', erroredSysCall: 'connect' }
> > Node.js v20.18.0
> > but I can visit https://chakra-v3-docs.vercel.app/compositions/index.json via browser
> 
> The domain vercel.app is banned in some places, and I guess you were using a VPN to visit the link in the browser. In this case, you can try to use a proxy to run the CLI like `HTTP_PROXY=http://127.0.0.1:7890 HTTPS_PROXY=http://127.0.0.1:7890 npx @chakra-ui/cli snippet add`

I'm from China and this one works for me, thanks bro.

**Comment by mail2ifham** [comment]
> i followed the installation and got the same error, fix my issue with installing `@chakra-ui/cli` before I add snippets
> 
> try this command to install `cli` separately
> 
> `npm i @chakra-ui/cli`
> 
> then
> 
> `npx @chakra-ui/cli snippet add`


this is worked for me

**Comment by liuzhaowei55** [comment]
> > I also meet error as below: PS C:\Users\Administrator\learn-chakra-ui> npx @chakra-ui/cli snippet add ┌ Chakra CLI ⚡️ file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108 reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error)); ^
> > FetchError: request to https://chakra-v3-docs.vercel.app/compositions/index.json failed, reason: connect ETIMEDOUT 31.13.82.33:443 at ClientRequest. (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108:11) at emitErrorEvent (node:_http_client:101:11) at TLSSocket.socketErrorListener (node:_http_client:504:5) at TLSSocket.emit (node:events:519:28) at emitErrorNT (node:internal/streams/destroy:169:8) at emitErrorCloseNT (node:internal/streams/destroy:128:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { type: 'system', errno: 'ETIMEDOUT', code: 'ETIMEDOUT', erroredSysCall: 'connect' }
> > Node.js v20.18.0
> > but I can visit https://chakra-v3-docs.vercel.app/compositions/index.json via browser
> 
> The domain vercel.app is banned in some places, and I guess you were using a VPN to visit the link in the browser. In this case, you can try to use a proxy to run the CLI like `HTTP_PROXY=http://127.0.0.1:7890 HTTPS_PROXY=http://127.0.0.1:7890 npx @chakra-ui/cli snippet add`

if you use proxy setting, HTTP_PROXY HTTPS_PROXY is OK; http_proxy https_proxy does not work

**Comment by rohan11110** [comment]
> `npm i @chakra-ui/cli`

Try this...

**Comment by rohan11110** [comment]
> i followed the installation and got the same error, fix my issue with installing `@chakra-ui/cli` before I add snippets
> 
> try this command to install `cli` separately
> 
> `npm i @chakra-ui/cli`
> 
> then
> 
> `npx @chakra-ui/cli snippet add`

 it will solve the problem

**Comment by TseringYuu** [comment]
> > I also meet error as below: PS C:\Users\Administrator\learn-chakra-ui> npx @chakra-ui/cli snippet add ┌ Chakra CLI ⚡️ file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108 reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error)); ^
> > FetchError: request to https://chakra-v3-docs.vercel.app/compositions/index.json failed, reason: connect ETIMEDOUT 31.13.82.33:443 at ClientRequest. (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108:11) at emitErrorEvent (node:_http_client:101:11) at TLSSocket.socketErrorListener (node:_http_client:504:5) at TLSSocket.emit (node:events:519:28) at emitErrorNT (node:internal/streams/destroy:169:8) at emitErrorCloseNT (node:internal/streams/destroy:128:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { type: 'system', errno: 'ETIMEDOUT', code: 'ETIMEDOUT', erroredSysCall: 'connect' }
> > Node.js v20.18.0
> > but I can visit https://chakra-v3-docs.vercel.app/compositions/index.json via browser
> 
> The domain vercel.app is banned in some places, and I guess you were using a VPN to visit the link in the browser. In this case, you can try to use a proxy to run the CLI like `HTTP_PROXY=http://127.0.0.1:7890 HTTPS_PROXY=http://127.0.0.1:7890 npx @chakra-ui/cli snippet add`

Nice work! Thx

**Comment by songhetian** [comment]
Try the method here https://github.com/xesam/chakra-ui-local-compositions?tab=readme-ov-file

**Comment by ynfeng** [comment]
> > > I also meet error as below: PS C:\Users\Administrator\learn-chakra-ui> npx @chakra-ui/cli snippet add ┌ Chakra CLI ⚡️ file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108 reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error)); ^
> > > FetchError: request to https://chakra-v3-docs.vercel.app/compositions/index.json failed, reason: connect ETIMEDOUT 31.13.82.33:443 at ClientRequest. (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/de2e382d70c335ff/node_modules/node-fetch/src/index.js:108:11) at emitErrorEvent (node:_http_client:101:11) at TLSSocket.socketErrorListener (node:_http_client:504:5) at TLSSocket.emit (node:events:519:28) at emitErrorNT (node:internal/streams/destroy:169:8) at emitErrorCloseNT (node:internal/streams/destroy:128:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { type: 'system', errno: 'ETIMEDOUT', code: 'ETIMEDOUT', erroredSysCall: 'connect' }
> > > Node.js v20.18.0
> > > but I can visit https://chakra-v3-docs.vercel.app/compositions/index.json via browser
> > 
> > 
> > The domain vercel.app is banned in some places, and I guess you were using a VPN to visit the link in the browser. In this case, you can try to use a proxy to run the CLI like `HTTP_PROXY=http://127.0.0.1:7890 HTTPS_PROXY=http://127.0.0.1:7890 npx @chakra-ui/cli snippet add`
> 
> if you use proxy setting, HTTP_PROXY HTTPS_PROXY is OK; http_proxy https_proxy does not work

This work for me

**Comment by husenlinwei** [comment]
<img width="2285" height="880" alt="Image" src="https://github.com/user-attachments/assets/9bd3503e-4b4a-4771-a913-7c8cd0d631ef" />

So, you can edit the code inside node_modules like this:
```
const env = processEnvSchema.parse(process.env);
# Add this line of code
env.HTTPS_PROXY = '<Your proxy address>' 

...
```
Or, a better way is to set a temporary HTTPS_PROXY environment variable. Just like: 

+ Set environment variables in Windows PowerShell.
```
$env:HTTPS_PROXY="<Your proxy address>"
```
+ Other platforms? Please ask the tireless Mr. LLM.

**Comment by schunlee** [comment]
as developer from China, 'cause vercel be banned here. you can edit file node_modules\@chakra-ui\cli\dist\esm\utils\fetch.js
add cloudflare worker proxy as below:

<img width="1307" height="644" alt="Image" src="https://github.com/user-attachments/assets/ed121132-fbc6-4343-85cd-8c54bbe3992c" />

how to delpoy your own cloudflare worker see here:
https://github.com/BH3GEI/CloudflareWorkerProxy
