### ISSUE TITLE
Spinner issue in 3.0

### ISSUE THREAD

**Issue by Zheruel** [chakra-ui/chakra-ui#8986]
### Description

After updating chakra UI to 3.0 I get the following issue:
![image](https://github.com/user-attachments/assets/c46b5f79-0e8c-46b7-b0bb-c1ea229af1f9)

This is my paqckage.json, it's just a simple VITE application:
```
{
  "name": "my-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "lint": "eslint 'src/**/*.{ts,tsx}' --quiet",
    "prettier:check": "prettier --check 'src/**/*.{ts,tsx,json,css,md}'",
    "prettier:fix": "prettier --write 'src/**/*.{ts,tsx,json,css,md}'",
    "format": "prettier --write 'src/**/*.{ts,tsx,json,css,md}'"
  },
  "engines": {
    "node": ">=20.11.1",
    "pnpm": ">=8.15.1"
  },
  "dependencies": {
    "@chakra-ui/icons": "^2.2.4",
    "@chakra-ui/react": "^3.0.0",
    "@emotion/react": "^11.13.3",
    "@tanstack/react-query": "^5.59.15",
    "jotai": "^2.10.1",
    "ky": "^1.7.2",
    "next-themes": "^0.3.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-icons": "^5.3.0",
    "react-quill": "^2.0.0",
    "react-router-dom": "^6.27.0",
    "styled-components": "^6.1.13",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "@eslint/js": "^9.13.0",
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "@types/styled-components": "^5.1.34",
    "@vitejs/plugin-react": "^4.3.3",
    "eslint": "^9.13.0",
    "eslint-plugin-react-hooks": "^5.1.0-rc.0",
    "eslint-plugin-react-refresh": "^0.4.13",
    "globals": "^15.11.0",
    "prettier": "^3.3.3",
    "typescript": "^5.6.3",
    "typescript-eslint": "^8.11.0",
    "vite": "^5.4.10"
  }
}
```

### Link to Reproduction

No need.

### Steps to reproduce

1. Have a chakra 2.0 project
2. Follow migration steps to update to chakra 3.0
3. It will happen

### Chakra UI Version

3.0.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by maxzinovev** [comment]
the same problem

**Comment by segunadebayo** [comment]
Both `@chakra-ui/icons` and `forwardRef` have been removed.

- Replace forwardRef with the react one
- Replace @chakra-ui/icons with a robust library like react-icons

**Comment by Zheruel** [comment]
This is from node modules...  not from my project.

**Comment by maxzinovev** [comment]
> This is from node modules... not from my project.

У вас есть пакет "@chakra-ui/icons" в package.json?

**Comment by maxzinovev** [comment]
> This is from node modules... not from my project.

Do you have the package "@chakra-ui/icons" in package.json?

**Comment by HazzaMore** [comment]
I am having the same issue and unable to resolve it still without considering to code my own custom spinner instead. The issue is with the chakra v3 spinner code (code we do not have access to) still trying to get forwardRef from @chakra-ui/react if I am not mistaken?  I could be wrong here but from my limited knowledge I'm struggling to see anything I could change in my own code that would fix this - I don't have chakra-ui/icons in the package.json for one.
```
node_modules/@chakra-ui/icons/dist/esm/Spinner.mjs (2:9): "forwardRef" is not exported by "node_modules/@chakra-ui/react/dist/esm/index.js", imported by "node_modules/@chakra-ui/icons/dist/esm/Spinner.mjs".

file: /vercel/path0/node_modules/@chakra-ui/icons/dist/esm/Spinner.mjs:2:9
1: import { jsxs, jsx } from 'react/jsx-runtime';
2: import { forwardRef, Icon } from '@chakra-ui/react';
            ^
3: import { useId } from 'react';
```
