### ISSUE TITLE
Modal removed in v3.0?

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#8987]
### Description

Modal removed in v3.0?

It is not mentioned in https://www.chakra-ui.com/docs/get-started/migration

### Chakra UI Version

3.0

**Comment by Bluorenge** [comment]
now is https://www.chakra-ui.com/docs/components/drawer

**Comment by segunadebayo** [comment]
Updated the docs accordingly

**Comment by surapunoyousei** [comment]
Thanks for updating the documentation.

**Comment by lcswillems** [comment]
Thanks for the update! :pray:

**Comment by absolutelysimon** [comment]
Took me a while to catch this. Maybe a warning on old versions for deprecated components?

https://v2.chakra-ui.com/docs/components/modal
