### ISSUE TITLE
Image fallback removed from v3.0?

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#8988]
### Description

Image fallback removed from v3.0?

https://v2.chakra-ui.com/docs/components/image/usage#fallback-support

### Chakra UI Version

3.0

**Comment by segunadebayo** [comment]
Yes, it's mentioned in the migration docs.

Please use the blur hash support in frameworks like Next.js instead.

**Comment by lcswillems** [comment]
Indeed, missed it!

What's the blur hash? I've researched Next.js docs and found nothing mentioning something like this.

**Comment by techwithtwin** [comment]
placeholder in the nextjs Image

**Comment by lcswillems** [comment]
I see, thank you! In my case I was using a React component as fallback, and it doesn't seem to support this

**Comment by LoukasPap** [comment]
Is `fallback` going to be added in v3.0 anytime?
