### ISSUE TITLE
Typescript support custom variants

### ISSUE THREAD

**Issue by y-wertz-priomold** [chakra-ui/chakra-ui#8992]
### Description

Using a custom bool variant gives typescript error (but works fine).

Example: Variant "priomold" is created on Heading component according to https://www.chakra-ui.com/docs/theming/customization/recipes#adding-new-variant

### Theme.ts

``` typescript
import { createSystem, defaultConfig, defineConfig } from "@chakra-ui/react";
import {
  accordionAnatomy,
  cardAnatomy,
  checkboxAnatomy,
  menuAnatomy,
  selectAnatomy,
  tagAnatomy,
} from "@chakra-ui/react/anatomy";

const config = defineConfig({
  theme: {
   recipes: {
      heading: {
        base: {
          fontWeight: "bold",
        },
        variants: {
          priomold: {
            true: {
              color: "priomold.500",
            },
          },
        },
        defaultVariants: {
          size: "5xl",
        },
      },
    },
  },
});

export const system = createSystem(defaultConfig, config);
```

### Usage
``` jsx
...
<Heading size="md" priomold mb={1}>
  Auftrag
</Heading>
...
```

### Error
![image](https://github.com/user-attachments/assets/6e18f30e-aed8-4b91-80a9-376994f7412f)

### Tried solutions
Running `npx @chakra-ui/cli typegen ./theme.ts` doesn't fix the issue

### Link to Reproduction

https://www.chakra-ui.com/docs/theming/customization/recipes#adding-new-variant

### Steps to reproduce

1. Create custom bool variant 
2. Run `npx @chakra-ui/cli typegen ./theme.ts`
3. Use variant

### Chakra UI Version

3.0.0

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Please install the `@chakra-ui/cli` for now. It works when running it directly with the CLI as opposed to `npx`

We'll track and fix the `npx` related issues later on.
