### ISSUE TITLE
keyframes from `@chakra-ui/react` not available anymore and keyframe from `@emotion/react` doesn't work

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#8994]
### Description

Before, this kind of code was working:

```
<Box
  position="absolute"
  top="0"
  left="0"
  right="0"
  bottom="0"
  backgroundSize="20px 20px"
  backgroundImage="radial-gradient(arda.100 0%, transparent 10%)"
  animation={`4s ease-in-out infinite alternate ${opacityKeyframes}`}
/>
```

with:

```
const opacityKeyframes = keyframes`
  0% { opacity: 0.4; }
  100% { opacity: 1; }
`;
```

and

```
import { Box, keyframes } from "@chakra-ui/react";
```

But it doesn't work anymore with Chakra 3, even when trying to use the `keyframes` from `@emotion/react`.

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-ia4rpb?file=src%2FApp.tsx,src%2Fmain.tsx

### Steps to reproduce

1. Open the reproduction
2. Go to App.tsx
3. Check the div in Chrome Dev Tools. The animation is marked as not available:
![image](https://github.com/user-attachments/assets/054950cb-fe25-446e-9d01-bd28eac984d2)

In v2, it would have been available.

### Chakra UI Version

3

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
