### ISSUE TITLE
ghost button styles not properly updated when parent has dark/light class

### ISSUE THREAD

**Issue by baptisteArno** [chakra-ui/chakra-ui#8998]
### Description

When I apply the `dark` class to a button's parent in a light mode system, I am expecting the button to be displayed as if the theme was set to dark.

### Link to Reproduction

https://codesandbox.io/p/sandbox/relaxed-swanson-n9rlhq?workspaceId=02bf022e-643a-45ea-b559-ba567b7285ae

### Chakra UI Version

3.0.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by baptisteArno** [comment]
Sorry, I needed to set colorPalette to gray and it worked fine. Still need some time to adjust to 3.0 mential model 😅

**Comment by baptisteArno** [comment]
But still, gray should be the default so maybe this is still an issue

**Comment by segunadebayo** [comment]
Here's how I would resolve this:

```tsx
function App() {
  return (
    <Theme appearance="dark" bg="gray.950">
      <Button variant="ghost">Welcome to Chakra + TS</Button>
    </Theme>
  );
}
```
