### ISSUE TITLE
Vite config .mjs .mts are missing in CLI

### ISSUE THREAD

**Issue by danchitnis** [chakra-ui/chakra-ui#8999]
### Description

in [here](https://github.com/chakra-ui/chakra-ui/blob/f40e7bbc435c09b8df75b271fa75e97b42fbeaae/packages/cli/src/utils/context.ts#L26) `vite.config.mjs` and `.mts` are missing hence Chakra CLI crashes if these files are present instead of the `.ts` or `.js` config files. See [here](https://vite.dev/guide/troubleshooting#vite-cjs-node-api-deprecated) for Vite guidance. 

### Link to Reproduction

Note required

### Chakra UI Version

3.0.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
