### ISSUE TITLE
App does not start in IE11

### ISSUE THREAD

**Issue by kstulgys** [chakra-ui/chakra-ui#902]
**Describe the bug** 
I'm testing the nextjs + chakra-ui app in BrowserStack with IE11. I'm running the nextjs example app: https://github.com/vercel/next.js/tree/canary/examples/with-chakra-ui
The app does not run. Error in the console (screenshot below) :

![image](https://user-images.githubusercontent.com/25918214/85207414-3c9e5400-b331-11ea-8846-a9da0772fc63.png)

**Expected Behavior** 

Expected the app to run in IE11 browser.

**Link to minimal reproduction** 

https://github.com/vercel/next.js/tree/canary/examples/with-chakra-ui

**Steps to Reproduce** 

1. Clone repo
2. Run the project (yarn dev)
3. Enable BrowserstackLocal
4. Select windows 10 IE11 browser
5. Go to http://localhost:3000/

**Suggested solution(s)**

**Desktop:**

**Additional context**

**Comment by segunadebayo** [comment]
Hi @kstulgys,

We've decided to lower the urge to make Chakra UI IE-11 compatible for now, considering the size of the team and the efforts involved. I'm personally interested in fixing this but not for now.

I'm aware this might not be the best choice but we'll live with this for the time being. If you feel inclined to help us fix these issues as well, you're welcome to contribute. I'm here to help.

Thank you for reporting this.
