### ISSUE TITLE
Compound components are unusable without manually typing the generics

### ISSUE THREAD

**Issue by Newbie012** [chakra-ui/chakra-ui#9023]
### Description

When I type the following compound component:

```tsx
import { createSlotRecipeContext, defineSlotRecipe } from "@chakra-ui/react";

const checkboxSlotRecipe = defineSlotRecipe({
  slots: ["root", "control", "label"],
  base: {
    root: { display: "flex", alignItems: "center", gap: "2" },
    control: { borderWidth: "1px", borderRadius: "sm" },
    label: { marginStart: "2" },
  },
  variants: {
    size: {
      sm: {
        control: { width: "8", height: "8" },
        label: { fontSize: "sm" },
      },
      md: {
        control: { width: "10", height: "10" },
        label: { fontSize: "md" },
      },
    },
  },
});

const { withProvider, withContext } = createSlotRecipeContext({
  recipe: checkboxSlotRecipe,
});

export const CheckboxRoot = withProvider("label", "root");
export const CheckboxControl = withContext("input", "control");
export const CheckboxLabel = withContext("span", "label");
```

and this demo component:

```tsx
function Demo() {
  return (
    <CheckboxRoot>
      <CheckboxControl type="checkbox" />
      <CheckboxLabel>Checkbox</CheckboxLabel>
    </CheckboxRoot>
  );
}
```

I expected the components to be fully typed with auto inference, but instead, I get the following errors:

<img width="867" alt="image" src="https://github.com/user-attachments/assets/b098f8f2-f61d-4e46-a11d-6b0ae36994f6">
<img width="913" alt="image" src="https://github.com/user-attachments/assets/5ffd7d6a-341f-4dcc-bf40-d3637b1eadd4">

In order for the types to work, I have to manually type the generics of `withProvider` and `withContext` which as a result adds a lot of boilerplate:

```tsx
// ...

interface CheckboxRootProps
  extends HTMLChakraProps<"div", RecipeVariantProps<typeof checkboxSlotRecipe>> {}
export const CheckboxRoot = withProvider<HTMLLabelElement, CheckboxRootProps>("label", "root");

interface CheckboxControlProps extends HTMLChakraProps<"input"> {}
export const CheckboxControl = withContext<HTMLInputElement, CheckboxControlProps>(
  "input",
  "control",
);

interface CheckboxLabelProps extends HTMLChakraProps<"span"> {}
export const CheckboxLabel = withContext<HTMLSpanElement, CheckboxLabelProps>("span", "label");
```

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-dpygj6?file=src%2FISSUE%2Fno-generics-recipe.tsx

### Steps to reproduce

1. Go to [`src/ISSUE/no-generics-recipe.tsx`](https://stackblitz.com/edit/vitejs-vite-dpygj6?file=src%2FISSUE%2Fno-generics-recipe.tsx) and see there are errors
2. Go to [`src/ISSUE/with-generics-recipe.tsx`](https://stackblitz.com/edit/vitejs-vite-dpygj6?file=src%2FISSUE%2Fwith-generics-recipe.tsx) and see that there are no issues

### Chakra UI Version

3.0.1

### Browser

Google Chrome 130

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The codesandbox template is out of date, so I [made a minimal template](https://stackblitz.com/edit/vitejs-vite-8ruxik?file=README.md), so feel free to fork it.

**Comment by segunadebayo** [comment]
This is by design. We played with automatically inferring the types but got very slow TS compilation types due to the complexity. So, we opted for explicit typings instead, just like `React.forwardRef` to speed things up.
