### ISSUE TITLE
colorPalette with custom theme doesn't work on components

### ISSUE THREAD

**Issue by willedanielsson** [chakra-ui/chakra-ui#9024]
### Description

When migrating to V3, one issue is that the Tabs, Badges, Switches beforehand could support `colorScheme="brand"` which was a core feature. However this no longer seems to be the case for custom color palettes added to the theme.

### Link to Reproduction

https://www.chakra-ui.com/docs/components/tabs

### Steps to reproduce

1. Use the Tabs component
2. Try using a custom color specified in your theme like in v2
3. Doesn't work

### Chakra UI Version

3.0.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Please read this guide
https://www.chakra-ui.com/docs/theming/customization/colors#color-palette

**Comment by willedanielsson** [comment]
@segunadebayo Aaah it was the new semanticTokens-part that was missing, could be good to add this to the migration guide as I'm sure more will otherwise miss it
