### ISSUE TITLE
[Core] Theme can not be initializied

### ISSUE THREAD

**Issue by danielbischoff** [chakra-ui/chakra-ui#903]
With the latest version "@chakra-ui/core": "^1.0.0-next.0" a theme can not be created with the command `npx chakra init --theme`.

Error Msg:
Program could not be found: chakra

When looking into the `node_modules/bin` folder there is no chakra script installed.

**Suggested solution(s)**
A script named chakra must be installed in the `node_modules/bin` folder

**Comment by segunadebayo** [comment]
Hi @danielbischoff, we're still working on this.

In the meantime, you can install `@chakra-ui/theme`.

**Comment by balibebas** [comment]
Thanks @segunadebayo. Here's what I tried so far to upgrade from the latest version zero release:

```
yarn add @chakra-ui/core@1.0.0-next.0 @chakra-ui/theme
```

Then in my `theme.tsx` file I tried swapping this:

```
import React from "react";
import { theme, DefaultTheme } from "@chakra-ui/theme";
```

I also tried to import `"chakra-ui-theme"` based on the [`@chakra-ui/theme@0.0.2` readme](https://cdn.jsdelivr.net/npm/@chakra-ui/theme@0.0.2/README.md). No luck, however. Looking at the theme package I don't see any exports so I'm probably doing something wrong.

**Comment by segunadebayo** [comment]
I will update the migration guide to include this. Here's what you should do

`import theme, { Theme } from @chakra-ui/theme`

Can you try this?

**Comment by balibebas** [comment]
@segunadebayo that did the trick. thanks

**Comment by with-heart** [comment]
Hi @danielbischoff, this should be working now.

```sh
npm i -g chakra-cli
chakra init --theme
```

Add the `--ts` flag if you'd like to generate the theme as TypeScript.
