### ISSUE TITLE
Getting an error from @chakra ui icons package while migrating from react v17 to v18

### ISSUE THREAD

**Issue by harshmangalam** [chakra-ui/chakra-ui#9033]
### Description

No matching export in "node_modules/.pnpm/@chakra-ui+react@3.0.2_@emotion+react@11.13.3_react@18.3.1__@internationalized+date@3.5.6_rea_hj4lvis3ou4xvy5gswd7zipacu/node_modules/@chakra-ui/react/dist/esm/index.js" for import "forwardRef"

    node_modules/.pnpm/@chakra-ui+icons@2.2.4_@chakra-ui+react@3.0.2_@emotion+react@11.13.3_react@18.3.1__@internati_qzyrwkp3bvakkg5fqailed5o5a/node_modules/@chakra-ui/icons/dist/esm/Spinner.mjs:2:9:
      2 │ import { forwardRef, Icon } from '@chakra-ui/react';

### Link to Reproduction

NA

### Chakra UI Version

v3

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Chakra icons has been removed. Please refer to the migration guide
