### ISSUE TITLE
[Core] Icons can not be used/imported (typescript)

### ISSUE THREAD

**Issue by danielbischoff** [chakra-ui/chakra-ui#904]
Version: "@chakra-ui/core": "^1.0.0-next.0"

When you want to use an Icon e.g. `<ExternalLinkIcon />` typescript says it is not exported from chakra.

```
import {
  ExternalLinkIcon
} from "@chakra-ui/core";
```

does not work.

I looked into the sources and found that the @chakra/icons package is not exported from the types.

**Suggested solution**
Export `@chakra-ui/icons`from the core package

**Comment by segunadebayo** [comment]
Please install `@chakra-ui/icons`

**Comment by with-heart** [comment]
Since this separation is already noted in the migration guide, I'm going to go ahead and close this.
