### ISSUE TITLE
Avatar.Root does not respect `as` prop.

### ISSUE THREAD

**Issue by Newbie012** [chakra-ui/chakra-ui#9046]
### Description

When I set `<Avatar.Root as="span">` I expected the DOM element to be `span`, but instead it's `div`.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-ntrqra?file=src%2Fcomponents%2Fui%2Favatar.tsx

### Steps to reproduce

1. Go to `avatar.tsx`
2. See that there's `as="span"`
3. Inspect the avatar element in the preview
4. See that it's still `div` and not `span`

### Chakra UI Version

3.0.1

### Browser

Google Chrome 130

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
