### ISSUE TITLE
[Icons] Typescript prop sx required

### ISSUE THREAD

**Issue by danielbischoff** [chakra-ui/chakra-ui#905]
Version: "@chakra-ui/core": "^1.0.0-next.0"

Currently icons can not be used as mentioned in bug https://github.com/chakra-ui/chakra-ui/issues/904. But after I locally fixed it, typescript prints an error if I do not add the `sx` property to any Icon (update: also other elements are affected).

**Update**
It seems like more components are affected:
InputGroup
InputLeftElement

**Error Messages**
Error Icon
Property 'sx' is missing in type '{}' but required in type 'Pick<(Pick<Pick<SVGProps<SVGSVGElement>, "string" | "name" | "id" | "cursor" | "style" | "clipPath" | "filter" | "mask" | "path" | "children" | "color" | ... 460 more ... | "sx"> & { ...; }, "string" | ... 471 more ... | "sx"> & ChakraProps & { ...; }) | (Pick<...> & ... 3 more ... & ChakraProps), "string" | ... 677...'.ts(2741)

Error InputGroup
Property 'sx' is missing in type '{ children: Element[]; size: string; flex: string; }' but required in type 'Pick<InputGroupProps, "cursor" | "id" | "p" | "slot" | "style" | "title" | "children" | "transition" | "_hover" | "_active" | "_focus" | "_highlighted" | "_focusWithin" | ... 471 more ... | "sx">'.ts(2741)

Error InputLeftElement
Property 'sx' is missing in type '{ children: Element; }' but required in type 'Pick<InputElementProps, "cursor" | "id" | "p" | "slot" | "style" | "title" | "children" | "transition" | "_hover" | "_active" | "_focus" | "_highlighted" | "_focusWithin" | ... 472 more ... | "placement">'.ts(2741)

**Suggested solution(s)**
the sx prop should not be mandatory

Please be aware that I tested the Icon component with a locally patched chakra core as mentioned in the other bug report https://github.com/chakra-ui/chakra-ui/issues/904.

**Comment by segunadebayo** [comment]
Please join our discord server: https://discord.gg/SC6QVZd

**Comment by with-heart** [comment]
I believe this is fixed in `1.0.0-next.2`. Can you check that @danielbischoff?

**Comment by danielbischoff** [comment]
Yep it is fixed now. Thank you!

**Comment by with-heart** [comment]
Awesome! Thanks for letting me know :)
