### ISSUE TITLE
Password docs wrong import issues

### ISSUE THREAD

**Issue by harshmangalam** [chakra-ui/chakra-ui#9059]
### Description

Currently password docs is importing `PasswordStrengthIndicator` but it should be `PasswordStrengthMeter`
```
import {
  PasswordInput,
  PasswordStrengthIndicator,
} from "@/components/ui/password-input"
```

### Link to Reproduction

https://github.com/chakra-ui/chakra-ui/blob/main/apps/www/content/docs/components/password-input.mdx

### Steps to reproduce

https://www.chakra-ui.com/docs/components/password-input

### Chakra UI Version

3.0.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Fixed
