### ISSUE TITLE
HoverCard doesn't work on mobile

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#9064]
### Description

On mobile, when I click on the trigger of a hover card, the hover card doesn't display.

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-t6aesi?file=src%2FApp.tsx

### Steps to reproduce

Open the reproduction, open on mobile, hover the text "Hello", nothing happens.

### Chakra UI Version

3.0.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hovercard isn't designed to work on mobile. Please use a popover instead

**Comment by lcswillems** [comment]
What's the point of having a component that only works on desktop? Seems useless to me but maybe I'm missing something?

I've opened a new issue to explain the use case better:

https://github.com/chakra-ui/chakra-ui/issues/9069
