### ISSUE TITLE
cli: adding a snippet with --outdir creates `src/components/ui` directory

### ISSUE THREAD

**Issue by Bogdanp** [chakra-ui/chakra-ui#9067]
### Description

What it says on the tin. When you run

```
npx @chakra-ui/cli snippet add --outdir frontend/components provider
```

it puts the `provider.tsx` file in `frontend/components`, but it also creates a `src/components/ui` folder.

### Link to Reproduction

N/A

### Steps to reproduce

npx @chakra-ui/cli snippet add --outdir frontend/components provider

### Chakra UI Version

3.0.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
