### ISSUE TITLE
Menu component does not work in ElectroBun environment.

### ISSUE THREAD

**Issue by janckerchen** [chakra-ui/chakra-ui#9072]
### Description

The following code works fine in the browser environment, but does not work in the ElectroBun environment.

```jsx
import {Provider} from '@/components/ui/provider'
import {
  MenuContent,
  MenuItem,
  MenuRoot,
  MenuTrigger,
} from '@/components/ui/menu'
import {Button} from '@/components/ui/button'

export const App = () => (
  <Provider>
    <MenuRoot>
      <MenuTrigger asChild>
        <Button variant='outline' size='sm'>
          Open
        </Button>
      </MenuTrigger>
      <MenuContent>
        <MenuItem value='new-txt'>New Text File</MenuItem>
        <MenuItem value='new-file'>New File...</MenuItem>
        <MenuItem value='new-win'>New Window</MenuItem>
        <MenuItem value='open-file'>Open File...</MenuItem>
        <MenuItem value='export'>Export</MenuItem>
      </MenuContent>
    </MenuRoot>
  </Provider>

)
```

system environment

```
bun  1.1.33
"electrobun": "^0.0.15",
"@chakra-ui/react": "^3.0.2",
```

Error

<img width="583" alt="image" src="https://github.com/user-attachments/assets/e96a6655-695b-42eb-aa32-bde0026abdcc">

### Link to Reproduction

browser is fine

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

3.0.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by janckerchen** [comment]
ElectroBun  author reply https://github.com/blackboardsh/electrobun/issues/26#issuecomment-2452999365

> 
> i suspect this is either:
> 
> a chakra-ui issue in webkit (you can test in safari)
> a chakra-ui issue with bun build (maybe only compatible with vite or webpack)
> a chakra-ui or general React bug in your actual code
> I’ve heard of chakra-ui issues when the bundler doesn’t handle cyclical imports in a certain way.

**Comment by segunadebayo** [comment]
Please read the guide here for custom window environments

https://www.chakra-ui.com/docs/components/environment-provider

You most likely need to wrap your app with the EnvironmentProvider
