### ISSUE TITLE
Storybook links are wrong on the website

### ISSUE THREAD

**Issue by in43sh** [chakra-ui/chakra-ui#9077]
### Description

If you visit any storybook link from the website, storybook will tell you that the story was not found. Take `NumberInput` for example: Storybook link from the [website](https://www.chakra-ui.com/docs/components/number-input) is `https://storybook.chakra-ui.com/?path=/story/components-number-input--basic` but the actual current link is `https://storybook.chakra-ui.com/?path=/story/forms-numberinput--basic`. I believe this applies to all links on the website docs

### Link to Reproduction

https://www.chakra-ui.com/docs/components/number-input

### Steps to reproduce

1. Go to https://www.chakra-ui.com/docs/components/concepts/overview
2. Choose any component from the left nav bar
3. Within that component, try visiting the Storybook link related to that component

### Chakra UI Version

3.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is now fixed.
