### ISSUE TITLE
Missing Form Data When Using Select

### ISSUE THREAD

**Issue by khotei** [chakra-ui/chakra-ui#9079]
### Description

I'm using the Form API to handle form data through the `onSubmit` event. When I include standard HTML form elements (e.g., `<input>` and `<select>`) with a name attribute, I can retrieve the values of these elements upon form submission.

Let's take an example.

```
<form onSubmit={...}>
  <label>
    Email:
    <input type="text" name="email" />
  </label>
  <label>
    Role:
    <select name="role">...</select>
  </label>
</form>
```

By using` e.currentTarget.elements[name].value`, I can retrieve the values from `event` in the `onSubmit` handler.

---

In this setup, I notice that the Chakra `Select` component does not render an underlying form control element (like a hidden input) that reflects the selected value. As a result, the value of `Select` is missing from the `FormData` when I submit the form, as there’s no actual form control element in the DOM to capture the selected value.

```
<SelectRoot name="role">
  <SelectLabel />
  <SelectTrigger>
    <SelectValueText />
  </SelectTrigger>
  <SelectContent>
    <SelectItem />
  </SelectContent>
</SelectRoot>
```

This issue also persists when using the new `react@19` feature with [useActionState](https://19.react.dev/reference/react/useActionState), where I attempt to retrieve the selected value using the `FormData` API as documented in [MDN](https://developer.mozilla.org/en-US/docs/Web/API/FormData).

### Link to Reproduction

https://codesandbox.io/p/sandbox/nifty-architecture-6rhfyk?file=%2Fsrc%2Findex.tsx%3A38%2C10-39%2C25

### Steps to reproduce

1. Go to sandbox
2. Fill input and select value from the select.
3. Open the console and submit the form.
4. Observe that in the elements we could find `email` input and retrieve value from it, but with select there is no such option.
5. Go to HTML as observer that there is `span` element with value and there is no form control element that hold select value, and could be used with Form API and https://19.react.dev/reference/react/useActionState, when you want to get selected value from https://developer.mozilla.org/en-US/docs/Web/API/FormData

### Chakra UI Version

3.0.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Good catch!

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
