### ISSUE TITLE
CRA support 

### ISSUE THREAD

**Issue by Ahmed-Ibrahim-Anter** [chakra-ui/chakra-ui#9086]
### Description

when use C R A does not work as expected firstly can not use custom theme even if it fails even if use chakra typegen src/theme.ts
and use path @ not native support  in CRA do you support CRA or have to use Vite as my app need CRA

### Link to Reproduction

https://codesandbox.io/p/sandbox/chakra-ui-typescript-pomi8

### Steps to reproduce

I try to install v 3 in new CRA app but it failed to update provider it work with defaultSystem but if use custom import { createSystem, defaultConfig } from "@chakra-ui/react"

export const system = createSystem(defaultConfig, {
  theme: {
    tokens: {
      fonts: {
        heading: { value: `'Figtree', sans-serif` },
        body: { value: `'Figtree', sans-serif` },
      },
    },
  },
})
it faild even if use chakra typegen src/theme.ts

### Chakra UI Version

3.0.0

### Browser

chrome latest

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This shows you didn't run the CLI to install the snippets.

Here's the fix for this:

```tsx
import { ChakraProvider, defaultSystem, Heading } from "@chakra-ui/react";
import * as React from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

function App() {
  return <Heading>Welcome to Chakra + TS</Heading>;
}

const rootElement = document.getElementById("root");
const root = createRoot(rootElement);

root.render(
  <React.StrictMode>
    <ChakraProvider value={defaultSystem}>
      <App />
    </ChakraProvider>
  </React.StrictMode>
);
```
