### ISSUE TITLE
Imported types from ark-ui cannot be resolved

### ISSUE THREAD

**Issue by Ploppy3** [chakra-ui/chakra-ui#9089]
### Description

Cannot import type

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-javascript-lzzg9

### Steps to reproduce

When writing the following JSDOC import:
`import("@chakra-ui/react").AccordionItemTriggerProps`
The type cannot be resolved.

### Chakra UI Version

3.0.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
We prefer to import from `@ark-ui/react/accordion` for bundle size optimization.

In this case, you probably need to create a `jsconfig.json` file that matches what's stated here
https://www.chakra-ui.com/docs/get-started/installation#update-tsconfig

**Comment by Ploppy3** [comment]
@segunadebayo Our project is not typescript but we use jsconfig for type checking.

Here is how I can possibly fix the problem but I'm not sure if it is a good solution.

```js
{
  "compilerOptions": {
    "baseUrl": "./",
    "target": "ES5",
    "allowJs": true,
    "checkJs": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "jsx": "react-jsx",
    "maxNodeModuleJsDepth": 0,
    "paths": {
      "@/*": [
        "./*"
      ],
      "@ark-ui/react/*": [
        "node_modules/@ark-ui/react"
      ]
    }
  },
  ...
}
```

**Comment by Ploppy3** [comment]
The problem was that I was not using typescript v5
