### ISSUE TITLE
[Color Mode] Typescript Error: /@chakra-ui/color-mode/dist/types/color-mode.d.ts(2,13): '=' expected.

### ISSUE THREAD

**Issue by Fawwad-Khan** [chakra-ui/chakra-ui#909]
Hi, 
I've just setup my project and npm installed Chakra UI as instructed in the get started guide in the docs. I used create-react-app to setup my project with typescript template. I imported the box and grid components and its giving me this error. Is this a bug or I didnt set it up the right way or something.
Please help. Thank you :) 

![image](https://user-images.githubusercontent.com/41516971/85235293-473e1380-b42d-11ea-936b-6a411b7d821d.png)

Also my react and typescript versions.

![image](https://user-images.githubusercontent.com/41516971/85235298-60df5b00-b42d-11ea-881d-ad1710a79ba9.png)

**Comment by Fawwad-Khan** [comment]
Sorry about that, I noticed the typescript version on the example and saw that I was using a previous version of typescript, running npm update fixed it. 🎉🎉

**Comment by with-heart** [comment]
@segunadebayo Should we address this or document it somewhere? As of right now, CRA uses `"typescript": "~3.7.2"` so this isn't going to work out of the box for CRA users either.

**Comment by timothyallan** [comment]
I think it's a good idea to perhaps document it somewhere. I just found this issue as I also got stung by this as well. I'm evaluating Chakra 1 with a fresh CRA install.

**Comment by olup** [comment]
So what's the catch here ? What typescript version is needed to make chakra work ?

**Comment by Fawwad-Khan** [comment]
A simple npm update worked for me, but I think the specific Typescript version for Chakra to work is 3.9.5 as it is in the CRA example in the repo.

**Comment by with-heart** [comment]
We're at `3.9.5` but I think `>=3.8.0` will make everything work.
