### ISSUE TITLE
[Input] Flushed Variant won't accept focusBorderColor

### ISSUE THREAD

**Issue by mattrothenberg** [chakra-ui/chakra-ui#91]
Hello!

I've noticed that when using the `flushed` variant of the `Input` component, the `focusBorderColor` doesn't seem to work.

```jsx
<Input
  variant="flushed"
  focusBorderColor="green"
  {...props.field}
  id="name"
  placeholder="John Doe"
/>
```
<img width="185" alt="Screen Shot 2019-09-16 at 3 16 12 PM" src="https://user-images.githubusercontent.com/5148596/64986415-f5ac9b00-d894-11e9-932d-11f6e25cb7f0.png">

Looking at the `flushedStyle` function here, it doesn't look like the prop is even being taken into account.

https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/Input/styles.js#L80-L98

1. Is this intentional?
2. If so, I'm happy to update the docs accordingly.
3. If not, I'm happy to update the implementation to take `focusBorderColor` into account.

Love the library, thanks again for your hard work here.

Cheers 🎊

**Comment by segunadebayo** [comment]
Hi @mattrothenberg,

Please feel free to update the implementation and submit a PR. I guess we skipped it.

Thanks for catching this.

**Comment by mattrothenberg** [comment]
Resolved by https://github.com/chakra-ui/chakra-ui/pull/92

🥂
