### ISSUE TITLE
How to use ::-webkit-scrollbar pseudo element properly?

### ISSUE THREAD

**Issue by diogolessa** [chakra-ui/chakra-ui#910]
Hi everyone,

This seems to be a simple issue, but I haven't found a way to make this works, neither found it on the docs nor on the web. I am struggling to add a `::-webkit-scrollbar` pseudo element to a component. I've tried several ways, but none of them works. The current code looks like this:

```jsx
import React from 'react'

import { useTheme, Flex } from '@chakra-ui/core'
import propTypes from 'prop-types'

const Container = ({ isFluid, horizontalScroll, children, ...rest }) => {
  const { breakpoints } = useTheme()
  const width = ['100%', null, ...breakpoints.slice(1)]

  return (
    <Flex
      maxWidth={isFluid ? '100%' : width}
      px={horizontalScroll ? [0, 0, 4] : 4}
      mx="auto"
      overflowX={horizontalScroll ? 'auto' : 'initial'}
      css={{
        '&::-webkit-scrollbar': {
          display: 'none',
        },
      }}
      {...rest}
    >
      {children}
    </Flex>
  )
}
```

Is there any guide/doc for this? I appreciate any help.

Thanks in advance.

**Comment by diogolessa** [comment]
Okay, I friend of mine explained how to solve this:

* Import jsx from @emotion-core library: `import { jsx } from '@emotion/core'`
* Add this comment at the top of the file: `/** @jsx jsx */`

**Comment by with-heart** [comment]
@diogolessa Thanks for documenting the solution from your friend :)

**Comment by kfalkiewicz** [comment]
I have the same problem but with components theme object. Any solution? (this one doesn't work).

**Comment by dodas** [comment]
@kfalkiewicz if works exactly the same way in the component theme as well.
I made a codesandbox where I hide `TabPanel`'s scrollbar: https://codesandbox.io/s/naughty-yonath-9x9zg?file=/src/index.tsx:1604-1640
