### ISSUE TITLE
404 for modal root: https://www.chakra-ui.com/modal

### ISSUE THREAD

**Issue by Jeandevweb** [chakra-ui/chakra-ui#9102]
### Description

hello,

i want to use the modal component but i have a 404 page not found.

"https://www.chakra-ui.com/modal"

thank you

### Link to Reproduction

https://www.chakra-ui.com/modal

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

3

### Browser

google chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Newbie012** [comment]
In V3, the [`Modal`](https://v2.chakra-ui.com/docs/components/modal/usage) component was replaced by the new [`Dialog`](https://www.chakra-ui.com/docs/components/dialog) component.
