### ISSUE TITLE
Select: item list opens behind dialog

### ISSUE THREAD

**Issue by Bogdanp** [chakra-ui/chakra-ui#9104]
### Description

When I use a <Select> inside a <Dialog> and trigger the select, it opens behind the dialog.

### Link to Reproduction

N/A

### Steps to reproduce

Put a select component inside a dialog and try to trigger it.

### Chakra UI Version

3.1.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Please follow the issue template as we're not able to act on issues that are lacking important information.
