### ISSUE TITLE
Select: item list opens behind dialog

### ISSUE THREAD

**Issue by Bogdanp** [chakra-ui/chakra-ui#9107]
### Description

What is says on the tin.

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-bphtux?file=src%2FApp.tsx

### Steps to reproduce

1. Put a Select inside a Dialog.
2. Open the Dialog.
3. Trigger the Select.
4. The Select items appear behind the dialog.

### Chakra UI Version

3.1.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Bogdanp** [comment]
Thanks for the workaround, but shouldn't the default z-index for the select content be greater than the z-index of a dialog?

**Comment by myniqx** [comment]
of course. probably it's a bug.

**Comment by segunadebayo** [comment]
This is not exactly a bug; it's related to how the components stack on top of each other (regardless of which comes first)

We can't rely explicitly on zIndex to manage the stacking. Instead, we recommend changing the portal target to the dialog's content.

Here's how to fix it:
https://github.com/chakra-ui/chakra-ui/blob/main/apps/compositions/src/examples/select-in-dialog.tsx
