### ISSUE TITLE
Select snippet uses components that don't exist

### ISSUE THREAD

**Issue by BrennenRocks** [chakra-ui/chakra-ui#9112]
### Description

I ran `pnpm dlx chakra snippet add select` which added the appropriate file to my package however my `SelectRoot` component looks like this
```typescript
export const SelectRoot = forwardRef<HTMLDivElement, ChakraSelect.RootProps>(
	function SelectRoot(props, ref) {
		return (
			<ChakraSelect.Root
				{...props}
				ref={ref}
				positioning={{ sameWidth: true, ...props.positioning }}
			>
				{props.asChild ? (
					props.children
				) : (
					<>
						<ChakraSelect.HiddenSelect />
						{props.children}
					</>
				)}
			</ChakraSelect.Root>
		);
	},
) as ChakraSelect.RootComponent;
```
but `ChakraSelect.HiddenSelect` and `ChakraSelect.RootComponent` don't actually exist when I look at `ChakraSelect`

Just using the basic Stackblitz link you can find the issue in the `select.tsx` file https://stackblitz.com/edit/chakra-ui-v3?file=src%2Fcomponents%2Fui%2Fselect.tsx

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3?file=src%2Fcomponents%2Fui%2Fselect.tsx

### Steps to reproduce

1. Add the `select` component from the `@chakra-ui/cli`

### Chakra UI Version

3.1.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is caching problem on StackBlitz' end. Please upgrade to the latest `3.1.0` version
