### ISSUE TITLE
[Docs] link to default theme is incorrect

### ISSUE THREAD

**Issue by callumflack** [chakra-ui/chakra-ui#912]
Minor issue. The current link at `https://chakra-ui.com/theme` is: 

https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/theme

…when it should be something like:

https://github.com/chakra-ui/chakra-ui/tree/master/packages/theme/src/foundations

**Comment by with-heart** [comment]
Hi @callumflack! We're in the process of rolling out 1.0 and we haven't yet deployed the new docs site, so we're in a weird in-between state. This will be fixed once the new site is rolled out soon. Thanks for reporting :)

**Comment by callumflack** [comment]
I can imagine you're busy. Chakra has been fantastic. Looking forward to yr progress!

**Comment by with-heart** [comment]
Thank you so much for the encouragement! It helps keep us motivated and on task :) Much appreciated!
