### ISSUE TITLE
Document `typescript@^3.8.0` requirement

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#913]
Since we're using syntax from TypeScript 3.8 (like `import type`/`export type`), I think it's important for us to document that this is the minimum version users will need to be have if they want to use the TypeScript version of Chakra. 

This requirement affects CRA users in particular, as the current version of CRA includes `"typescript": "~3.7.2"`.

- [x] Add note to installation docs
- [x] Add note to `migration.mdx`
- [ ] ~~Add CRA-specific note somewhere (best place is probably not-yet-existing CRA-specific guide; see #811)~~

**Comment by segunadebayo** [comment]
What if we revert our `import/export` to a version that works with CRA? For now

**Comment by with-heart** [comment]
That could work, though @mrmckeb [mentioned here](https://github.com/chakra-ui/chakra-ui/issues/956#issuecomment-648994208) that a new CRA release should be out very soon, so we may not really need to worry about it.
