### ISSUE TITLE
PaginationPageText never goes above 7, even when count of pages is higher.

### ISSUE THREAD

**Issue by drscottlobo** [chakra-ui/chakra-ui#9131]
### Description

When using pagination text on mobile, the PaginationPageText never goes above displaying "1 of 7." This bug is clearly displayed in the Chakra docs on the pagination page in the Compact section, pasted below. The expected behavior would be a display of 1 of 10 with a count of 20 and a page size of 2, but no matter what number is placed in the PaginationRoot, 7 is the max it will display. It must be a bug?

```
import { HStack } from "@chakra-ui/react"
import {
  PaginationNextTrigger,
  PaginationPageText,
  PaginationPrevTrigger,
  PaginationRoot,
} from "@/components/ui/pagination"

const Demo = () => {
  return (
    <PaginationRoot count={20} pageSize={2} defaultPage={1}>
      <HStack gap="4">
        <PaginationPrevTrigger />
        <PaginationPageText />
        <PaginationNextTrigger />
      </HStack>
    </PaginationRoot>
  )
}
```

### Link to Reproduction

https://www.chakra-ui.com/docs/components/pagination#compact

### Steps to reproduce

Go to the docs, go to the Pagination section displayed in the [Compact section](https://www.chakra-ui.com/docs/components/pagination#compact), the page should display 1 of 10 in the demo, but it is impossible to get the total pages above 7. 

### Chakra UI Version

3.0.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

N/A

**Comment by toshiya14** [comment]
facing the same problem, but I figure out the problem.

-----
## Resolution

simply change the `pages.total` into `totalPages`.

make changes as below:
in src/components/ui/pagination.tsx: 195
**(For auto-formating, if you don't see code below in line 195, please search for `function PaginationPageText(`)**

```ts
  const { page, pageRange, count, totalPages } = usePaginationContext()
  const content = useMemo(() => {
    if (format === 'short') return `${page} / ${totalPages}`
    if (format === 'compact') return `${page} of ${totalPages}`
    return `${pageRange.start + 1} - ${pageRange.end} of ${count}`
  }, [format, page, pageRange, count, totalPages])
```
Everything works fine now.

-----

## What happened?

If add `console.log("pages", pages)` inside this `useMemo`:

```ts
  const { page, pages, pageRange, count } = usePaginationContext()
  const content = useMemo(() => {
    console.log('pages', pages)
    if (format === 'short') return `${page} / ${pages.length}`
    if (format === 'compact') return `${page} of ${pages.length}`
    return `${pageRange.start + 1} - ${pageRange.end} of ${count}`
  }, [format, page, pages.length, pageRange, count])
```

you will see:

```
0: Object { type: "page", value: 1 }
1: Object { type: "ellipsis" }
2: Object { type: "page", value: 99 }
3: Object { type: "page", value: 100 }
4: Object { type: "page", value: 101 }
5: Object { type: "page", value: 102 }
6: Object { type: "page", value: 103 }

length: 7
```

The `pages` object actullly not includes all the pages, but `ellipsis` instead of the middle items.

**Comment by drscottlobo** [comment]
That fixed it! Thank you!

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by drscottlobo** [comment]
Thank you Segun! _______________Scott Wolf, DMAOxnard College - Professor of MusicOn Nov 14, 2024, at 9:12 AM, Segun Adebayo ***@***.***> wrote:﻿
I just pushed a fix for this. We'll release an update shortly.
If the issue persists after upgrading, I'll re-open it.
