### ISSUE TITLE
Spinner code in v3.0 is importing forwardRef from 'chakra-ui/react'

### ISSUE THREAD

**Issue by HazzaMore** [chakra-ui/chakra-ui#9134]
I am having the same problem mentioned in another issue that shouldn't have been closed. I am unable to resolve it still without considering to code my own custom spinner instead. The issue is with the chakra v3 spinner code (code we do not have access to) is still trying to get forwardRef from @chakra-ui/react if I am not mistaken?  I could be wrong here but from my limited knowledge I'm struggling to see anything I could change in my own code that would fix this - I don't have chakra-ui/icons in the package.json for one.
```
node_modules/@chakra-ui/icons/dist/esm/Spinner.mjs (2:9): "forwardRef" is not exported by "node_modules/@chakra-ui/react/dist/esm/index.js", imported by "node_modules/@chakra-ui/icons/dist/esm/Spinner.mjs".

file: /vercel/path0/node_modules/@chakra-ui/icons/dist/esm/Spinner.mjs:2:9
1: import { jsxs, jsx } from 'react/jsx-runtime';
2: import { forwardRef, Icon } from '@chakra-ui/react';
            ^
3: import { useId } from 'react';
```

_Originally posted by @HazzaMore in https://github.com/chakra-ui/chakra-ui/issues/8986#issuecomment-2466175834_

**Comment by segunadebayo** [comment]
This is unrelated to v3, as `@chakra-ui/icons` was removed in v3.

You probably want to remove this from your codebase in favor of react-icons or lucide-react.

**Comment by HazzaMore** [comment]
I did not use chakra-ui/icons in my codebase, its spinner I imported as 
`import { Spinner } from "@chakra-ui/react"` 
To me it looks like it is still using the chakra-ui/icons library. Me removing the spinner import resolved the issue with my code

**Comment by Rosember10** [comment]
hi, for me, the solution was,  I uninstalled the package @chakra-ui/icons
