### ISSUE TITLE
FormControl / FormErrorMessage removed but no mention in the migration guide

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#9135]
### Description

It seems that FormControl and FormErrorMessage have been removed from Chakra 3, but there is no mention in the migration guide:

https://www.chakra-ui.com/docs/get-started/migration

### Chakra UI Version

3

**Comment by segunadebayo** [comment]
Done.

**Comment by lcswillems** [comment]
Thanks! :pray: @segunadebayo The thing is that I don't even know what should be the replacement.
