### ISSUE TITLE
isRound removed from IconButton but no mention in migration guide

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#9136]
### Description

The prop `isRound` has been removed from `IconButton`, but nothing is mentioned on this subject in the migration guide.

https://www.chakra-ui.com/docs/get-started/migration

### Chakra UI Version

3

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by lcswillems** [comment]
Thanks! :pray:
