### ISSUE TITLE
resetCSS prop from ChakraProvider removed but no mention in migration

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#9137]
### Description

I use Chakra-UI in a component of a website, which already has its own styles, and so I use `resetCSS={false}` to prevent Chakra to reset the styles of the website.

https://www.chakra-ui.com/docs/get-started/migration

### Chakra UI Version

3

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by lcswillems** [comment]
Thanks! :pray:
