### ISSUE TITLE
Borders aren't rendering

### ISSUE THREAD

**Issue by jeffclaybrook** [chakra-ui/chakra-ui#9138]
### Description

Borders aren't rendering for the following components: Accordion, Avatar (outline), Button (outline), Card, Checkbox Card, Checkboxes, possibly more, I haven't gotten that far yet.

### Link to Reproduction

https://stackblitz.com/edit/stackblitz-starters-vi1agq

### Steps to reproduce

1. Create one of the components mentioned above according to the Chakra UI docs

### Chakra UI Version

3.0.0

### Browser

Google Chrome 130.0.6723.116

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Please remove the `globals.css` file import to make it work.
