### ISSUE TITLE
Create custom `create-react-app` templates

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#914]
`create-react-app` allows users to define custom templates: https://create-react-app.dev/docs/custom-templates/

We should define custom js and ts templates so that users can easily spin up Chakra-based CRA projects.

- [x] JS template created
- [x] TS template created
- [x] Guide created for using templates
- [x] Packages are correctly attached to versioning/publishing

**Comment by segunadebayo** [comment]
Sounds great @with-heart

I see you've created repos for them so we can close out this issue. We now need to create an issue to update the docs  "getting started" page to include this.

Thanks

**Comment by with-heart** [comment]
I made those for possible CodeSandbox templates generated from the CRA templates, but I don't think the separate repos are actually gonna be that useful. CodeSandbox doesn't give an easy way to keep a sandbox template always up-to-date with a GitHub repo unfortunately :(

I'm gonna re-open this so we can still get the CRA templates in place. I have #936 in draft, but I'll try to finish the remaining work on them so we can get that merged and this issue closed for real this time :)
