### ISSUE TITLE
Duplication of @zag-js packages

### ISSUE THREAD

**Issue by oceandrama** [chakra-ui/chakra-ui#9141]
### Description

There is a conflict between `@ark-ui/anatomy@3.5.0` and `@ark-ui/react@4.1.2` packages, which are both in the dependencies of `@chakra-ui/react@3.1.0`
 `@ark-ui/anatomy@3.5.0` has `@zag-js/...@0.62.1` in the dependencies
![image](https://github.com/user-attachments/assets/fd806756-56f0-4b8c-82dd-c8ba9b1b9d4b)
but `@ark-ui/react@4.1.2` has `@zag-js/...@0.74.2`
![image](https://github.com/user-attachments/assets/06940c72-e512-4a43-a53a-aecd27776651)
which leads to duplicate all `@zag-js` components (deduplication is not working because of major version 0 of @zag-js)

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3?file=src%2FApp.tsx

### Steps to reproduce

1. Intall `@chakra-ui/react@3.1.0`
2. Go to `package-lock.json` or `yarn.lock`

### Chakra UI Version

3.1.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
