### ISSUE TITLE
missing type exports for components

### ISSUE THREAD

**Issue by danchitnis** [chakra-ui/chakra-ui#9146]
### Description

There are some missing type exports in Chakra v3 components. For example, in [Number Input](https://www.chakra-ui.com/docs/components/number-input), the event [NumberInputValueChangeDetails](https://github.com/chakra-ui/chakra-ui/blob/6a6d598227c5f03a86372dcc0b9f424becdcd8c7/packages/react/src/components/number-input/number-input.tsx#L137) is not exported correctly from [here](https://github.com/chakra-ui/chakra-ui/blob/main/packages/react/src/components/number-input/index.ts) to `chakra-ui/react`.

Additionally, in the [documentation](https://www.chakra-ui.com/docs/components/number-input#root) it is better to be more accurate for the type is `NumberInputValueChangeDetails`, not `ValueChangeDetails` as it is mentioned for the function callback related to `onValueChange`

### Link to Reproduction

N/A

### Steps to reproduce

to fix the issue, you could add

```typescript
export type { NumberInputValueChangeDetails } from "./number-input.d.ts";
```

to [here](https://github.com/chakra-ui/chakra-ui/blob/main/packages/react/src/components/number-input/index.ts)

### Chakra UI Version

3.1.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by danchitnis** [comment]
@segunadebayo I think `TabsValueChangeDetails` is also missing?
