### ISSUE TITLE
Size change of avatar in timeline leads to broken layout

### ISSUE THREAD

**Issue by mccount** [chakra-ui/chakra-ui#9160]
### Description

When I create a timeline element and try use the avatar as the timeline connector and change the size, I expected the timeline to grow, instead the layout breaks.

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-vejmu9?file=src%2FApp.tsx

### Steps to reproduce

1. Go to 'VS Code'
2. Create new 'Chakra UI project with latest dependencies'
3. Add timeline component with avatar in the timeline connector, set size to something else than "full"

### Chakra UI Version

3.0.0

### Browser

latest Edge and Firefox

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![image](https://github.com/user-attachments/assets/4f695368-3b19-4ec9-b38b-81067eeb6dfd)

**Comment by segunadebayo** [comment]
Setting the size to full allows it to adjust to the height of the timeline indicator. You can control the size of the timeline if you want to see a large avatar.

If you set the custom size, you should tweak the timeline/avatar styles yourself.
