### ISSUE TITLE
In Chakra V3 SelectRoot, using React Element in collection causes error

### ISSUE THREAD

**Issue by EyuelDK** [chakra-ui/chakra-ui#9166]
### Description

When I created a collection using `createListCollection` that contained items with React Element properties and I passed this collection into `SelectRoot` it throws an error. It seems to be caused by the React Element properties; note that using a string instead will work.

### Link to Reproduction

https://codesandbox.io/p/devbox/5qf69t

### Steps to reproduce

1. Create a collection using `createListCollection` that has items of React Element property (for example, item is `{ label: <div>Label</div> })`
2. Pass the collection into `SelectRoot`
3. See error

### Chakra UI Version

3.1.1

### Browser

Google Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I don't recommend passing React Elements to the collection. Please use objects or primitive data and render the JSX at the render
