### ISSUE TITLE
[Menu] Menu broken when used within a context menu trigger container.

### ISSUE THREAD

**Issue by vrimar** [chakra-ui/chakra-ui#9171]
### Description

On initial load, _hovering_ the "Action" button will open the nested menu within the context menu trigger. Opening the nested menu via "Action" button click and then hovering over the nested menu will close it. 

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-zb65kg?file=src%2FApp.tsx

### Chakra UI Version

3.1.1

### Browser

Google Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
You've created some "nested menu," but you probably meant to create a sibling menu (one context menu, another regular menu)

Here's an example of how to resolve this design

```tsx

function App() {
  const [open, setOpen] = useState(false);
  const buttonRef = useRef<HTMLButtonElement>(null);
  return (
    <>
      <MenuRoot
        positioning={{
          getAnchorRect: () => buttonRef.current!.getBoundingClientRect(),
        }}
        open={open}
        onOpenChange={(e) => setOpen(e.open)}
      >
        <MenuContent>
          <MenuItem value="action">Nested Action</MenuItem>
        </MenuContent>
      </MenuRoot>
      <MenuRoot>
        <MenuContextTrigger asChild>
          <Stack p="10" bg="lightgray" height="500px" width="500px">
            <Button ref={buttonRef} onClick={() => setOpen((c) => !c)}>
              Action
            </Button>
          </Stack>
        </MenuContextTrigger>
        <MenuContent>
          <MenuItem value="action">Context Action</MenuItem>
        </MenuContent>
      </MenuRoot>
    </>
  );
}
```

Notice how I controlled the normal menu but kept it within the ContextMenuTrigger. This avoids the issue where the context menu thinks we're creating a "nested" menu.

https://stackblitz.com/edit/chakra-ui-v3-hax4c5?file=src%2FApp.tsx

**Comment by vrimar** [comment]
Thanks for the quick reply, I'll check it out!
