### ISSUE TITLE
Feature Request: Snippet can be imported directly instead of copied into the project

### ISSUE THREAD

**Issue by hongfanmeng** [chakra-ui/chakra-ui#9172]
### Description

Chakra UI v3 has added snippets that can be copied to projects using the CLI. However, some users may not need to modify these snippets. Is it possible to export these snippets in a package e.g. `@chakra-ui/react/snippets` so that users do not need to add those code to their projects?

### Problem Statement/Justification

Add a package that exports these snippets to reduce the amount of code in the project for users who do not need to make modifications, while still retaining the ability for users who need to make changes.

### Proposed Solution or API

Add a package e.g. `@chakra-ui/react/snippets` to export all these snippets

**Comment by segunadebayo** [comment]
Thanks for sharing this idea. We explored it before launching v3 and decided not to pursue it.

We want users **always** to have the option to update the snippets as needed.

Thanks for understanding.
