### ISSUE TITLE
Error: Uncaught TypeError: Cannot read properties of undefined (reading '_config') when using <ChakraProvider> with Chakra UI v3.1.2 in Vite React Project

### ISSUE THREAD

**Issue by akashkmt** [chakra-ui/chakra-ui#9174]
### Description

I ran into an issue while setting up Chakra UI in a new React project created with Vite. I installed the latest Chakra UI version (3.1.2), but when I wrapped my app with the ChakraProvider, the app crashes with this error in the console:

```
@chakra-ui_react.js?v=91fb0e8b:2978 Uncaught TypeError: Cannot read properties of undefined (reading '_config')

The above error occurred in the <ChakraProvider> component:

    at ChakraProvider (http://localhost:5174/node_modules/.vite/deps/@chakra-ui_react.js?v=91fb0e8b:2976:18)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

I have checked this template as well as mentioned in contribution doc:

> JavaScript Starter: [link](https://codesandbox.io/s/chakra-ui-javascript-lzzg9)

Here also the same error is coming.

Additional Context:
- I’ve tried clearing node_modules and reinstalling everything (rm -rf node_modules && npm install), but the issue persists.
- I downgraded Chakra UI to an older version (e.g., 2.0.0), and everything worked fine, so this seems to be an issue with the latest version (3.1.2).
- I am using react+vite+javascript.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-5xsjrz?file=src%2Fmain.jsx

### Chakra UI Version

3.1.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Here's what you need to do:

```tsx
import { StrictMode } from 'react';
import { ChakraProvider, defaultSystem } from '@chakra-ui/react';
import { createRoot } from 'react-dom/client';
import './index.css';
import App from './App.jsx';

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <ChakraProvider value={defaultSystem}>
      <App />
    </ChakraProvider>
  </StrictMode>
);
```

Notice the defaultSystem passed to the provider

**Comment by JasonLeviGoodison** [comment]
Same problem for me, but not a vite project. Just a vanilla Next js app. Was working before and stopped. Versions are the same as OP:
Next version "^14.2.12"

**Comment by bumi001** [comment]
When I use `    <ChakraProvider value={defaultSystem}>` vscode shows the following error:

Type 'SystemContext' is not assignable to type 'ValueObject'.
  Index signature for type 'string' is missing in type 'SystemContext'.ts(2322)
index.d.mts(43, 5): The expected type comes from property 'value' which is declared here on type 'IntrinsicAttributes & ColorModeProviderProps'

**Comment by bumi001** [comment]
I edited node_modules/@chakra-ui/react/dist/types/styled-system/types.d.ts and added the following line:
`[key: string]: any;` to the SystemContext Interface as shown below:
```

export interface SystemContext {
    $$chakra: true;
    [key: string]: any;           //<--- _**added this line**_
    _config: SystemConfig;

``` 
That made the error go away.

**Comment by bumi001** [comment]
In case you generate the snippets and then import the Provider as in:

`import {Provider} from '@/components/ui/provider';`

Then, you should use the Provider without the value prop as in:
```
createRoot(document.getElementById('root')).render(
  <StrictMode>
    <Provider >
      <App />
    </Provider>
  </StrictMode>
);

```

Note that `ChakraProvider` from `'@chakra-ui/react'` and `Provider` from `'@/components/ui/provider'` have different function signatures.
