### ISSUE TITLE
Popover is not portalled

### ISSUE THREAD

**Issue by lt123345** [chakra-ui/chakra-ui#9177]
### Description

When I am using @chakra-ui/react version 3, I tried the portalled Popover.

Expected: As in the doc, the popover contenet should be portalled correctly.

Actual: In my project the popover content is inline. Not portalled, and even not absolute positioned.

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-d3fcrd?file=package.json,src%2FApp.tsx

### Steps to reproduce

1. Go to https://stackblitz.com/edit/chakra-ui-v3-d3fcrd?file=package.json,src%2FApp.tsx
2. Click on 'Popover trigger' button
3. Expected: The popover content should be portalled.
4. Actual: The popver content is not portalled, and the 'Hello, world' below is re-positioned by the popover content.

### Chakra UI Version

3.1.2

### Browser

Google Chrome Version 130.0.6723.92 (Official Build) (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The popover trigger:
<img width="325" alt="image" src="https://github.com/user-attachments/assets/7c43d036-0a41-474e-acc2-4b129681cdd5">

After click, the "Hello, world!" text is pushed down by the popover content.
<img width="383" alt="image" src="https://github.com/user-attachments/assets/0a21a526-53e3-434f-9d69-2cd5f32c97bb">

The popover content is right after the trigger button, even if I specified `portalled={true}` to the PopoverRoot.
<img width="1245" alt="image" src="https://github.com/user-attachments/assets/c5dbfdd8-b1da-435e-8b8a-9c75fe4c3a22">

**Comment by lt123345** [comment]
I found that using `npx @chakra-ui/cli@next snippet add popover` and change all imports from the project works as expected.

**Comment by jpv123** [comment]
This comment was gold. @segunadebayo do you know why this only works from the snippet? I have the same issue with the Dialog component that it is not portalled correctly
