### ISSUE TITLE
Semantic tokens doesn't work with custom conditions

### ISSUE THREAD

**Issue by tranbathanhtung** [chakra-ui/chakra-ui#9178]
### Description

https://www.chakra-ui.com/docs/theming/semantic-tokens#conditional-token

I tried to test with default other conditions but it seems like only _dark condition is working.

```js
defineConfig({
  conditions: {
    mb: "@media (max-width: 768px)",
  },
  theme: {
    semanticTokens: {
      spacing: {
        section: {
          value: { base: "8rem", mb: "4rem" },
        },
      },
    },
  },
})
```

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-mdhsh2?file=src%2FApp.tsx

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

3.1.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
When you create custom conditions, you access them with `_[name]`. In this case, it should be `_mb` instead.

**Comment by tranbathanhtung** [comment]
@segunadebayo I tried _mb too but it still doesn't work? Did you test? https://stackblitz.com/edit/chakra-ui-v3-mdhsh2?file=src%2Fcomponents%2Fui%2Fprovider.tsx
