### ISSUE TITLE
Chakra-UI v3 Input and Next v15 do not work with react-input-mask. TypeError: reactDom.findDOMNode is not a function

### ISSUE THREAD

**Issue by Rakhymbek** [chakra-ui/chakra-ui#9181]
### Description

I wanted to try new next 15 with chakra-ui v3. Everything was okay, I did all necessary setup from https://www.chakra-ui.com/docs/get-started/installation.

Then I used Input component with InputMask to create custom component.
```
import InputMask, { Props as InputMaskProps } from 'react-input-mask';
import React from 'react';
import { Input } from '@chakra-ui/react';

interface MaskedInputProps extends InputMaskProps {
  field: any;
  mask: string;
  handleOnChange?: (event: React.ChangeEvent<HTMLInputElement>) => void;
}
const MaskedInput: React.FC<MaskedInputProps> = ({
  field,
  mask,
  handleOnChange,
  disabled,
  ...rest
}) => {
  const { onChange, ...fieldRest } = field;

  const renderInput = function Component(inputProps: InputMaskProps) {
    return <Input disabled={disabled} {...fieldRest} {...inputProps} {...rest} />;
  };

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    handleOnChange?.(event);
    onChange(event);
  };
  return (
    <InputMask
      mask={mask}
      value={fieldRest.value}
      onChange={handleChange}
      onBlur={fieldRest.onBlur}
      disabled={disabled}
    >
      {renderInput as any}
    </InputMask>
  );
};
```

1. With Next 15.0.3
<img width="1603" alt="image" src="https://github.com/user-attachments/assets/68a75c3d-566b-4396-beba-23ed83b90755">

2. With Next 14.2.18 it works as expected
![image](https://github.com/user-attachments/assets/ef22cfcd-8091-476b-a53e-77fc42074355)

There 2 ways for me:
1. Downgrade Next version from 15 to 14
2. Try to use another library or maybe without lib

### Link to Reproduction

https://stackblitz.com/edit/stackblitz-starters-5g6qpl?file=app%2Fpage.tsx

### Steps to reproduce

1. Install new Next 15, Chakra v3 and react-input-mask v2.0.4
3. Try to use InputMask with Input
4. Run your app with `npm run dev`
5. See error - TypeError: reactDom.findDOMNode is not a function

### Chakra UI Version

3.1.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is not a Chakra UI bug. It's related to react-input-mask.

Read more here: https://github.com/sanniassin/react-input-mask/issues/317

**Comment by raifemre** [comment]
use "react-number-format" instead.

If you are also using react-hook-form here is the simple snippet to give some idea

`
import { Heading, Input, VStack, Stack, Text, Fieldset, Separator, Container, Group, InputAddon } from "@chakra-ui/react";
import { Controller, useForm } from "react-hook-form";

const {
    control,
    handleSubmit,
    resetField,
    formState: { errors, isSubmitting, isValid },
  } = useForm({
    mode: "onSubmit",
    defaultValues: {
      phoneNumber: "",
    },
  });

function onCountrySelect(event, countryCode: string) {
    resetField("phoneNumber");
    setCountryCode(countryCode);
    phoneRef?.current?.focus();
  }

  const CountrySelect = () => (
    <NativeSelectRoot size="lg" variant="subtle">
      <NativeSelectField minWidth="85px" focusRingColor="gray.100" value={countryCode} onChange={(e) => onCountrySelect(e, e.currentTarget.value)}>
        <option value="+90">+90</option>
        <option value="+358">+358</option>
      </NativeSelectField>
    </NativeSelectRoot>
  );

function getCountryCodeFormat(countryCode: string) {
    switch (countryCode) {
      case "+90":
        return { format: "(###) ### ## ##", placeholder: "(532) 000 00 00" };
      case "+358":
        return { format: "## ### ####", placeholder: "50 123 4567" };
      default:
        return { format: "### ### ####", placeholder: "123 456 7890" };
    }
  }


<Fieldset.Root size="lg" maxW="md" invalid={errors.phoneNumber}>
            <Fieldset.Content>
              <Field invalid={!!errors.phoneNumber}></Field>
              <Controller
                control={control}
                name="phoneNumber"
                render={({ field: { onBlur, onChange, value } }) => (
                  <Group attached>
                    <InputAddon size="md" px={0.5}>
                      <CountrySelect />
                    </InputAddon>
                    <PatternFormat
                      getInputRef={phoneRef}
                      format={getCountryCodeFormat(countryCode).format}
                      value={value}
                      onBlur={onBlur}
                      onValueChange={(values) => onChange(values.value)}
                      valueIsNumericString
                      mask=" "
                      id="phoneNumber"
                      placeholder={getCountryCodeFormat(countryCode).placeholder}
                      size="xl"
                      autoFocus
                      onKeyPress={(event) => {
                        if (/[0-9]/.test(event.key) || event.key === "Enter") {
                        } else {
                          event.preventDefault();
                        }
                      }}
                      customInput={Input}
                    />
                  </Group>
                )}
              />
            </Fieldset.Content>
      <Fieldset.ErrorText>{errors.phoneNumber && errors.phoneNumber.message}</Fieldset.ErrorText>
 </Fieldset.Root>`

**Comment by raifemre** [comment]
use "react-number-format" instead. PatternFormat works great

**Comment by Rakhymbek** [comment]
> use "react-number-format" instead. PatternFormat works great

thank you, mate! Appreciate it✊🏻
I've seen your code example in email message, but could not find it here.
