### ISSUE TITLE
'extend' does not exist in type 'ThemingConfig'

### ISSUE THREAD

**Issue by riceboyler** [chakra-ui/chakra-ui#9200]
### Description

I'm attempting to migrate from v2 to v3 of Chakra (YAY!) but when rebuilding my custom theme file as instructed, when I try to do:
```
const typeConfig = defineConfig({
  theme: {
    extend: {
      textStyles: {
        ...TYPOGRAPHY_V2,
        ...TYPOGRAPHY_V5
      }
   }
}
```

I'm getting a Typescript error: "Object literal may only specify known properties, and 'extend' does not exist in type 'ThemingConfig'. Am I missing some extra types or something?

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3?file=src%2Ftheme.ts

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

3.1.2

### Browser

Unrelated, but Arc Browser

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by riceboyler** [comment]
I realize my StackBlitz link doesn't work because I forgot to fork it first. I'll update in a bit.

**Comment by segunadebayo** [comment]
extend does not exist in the theming structure.

Please read the guide here
https://www.chakra-ui.com/docs/theming/customization/overview

**Comment by FlawaCLV** [comment]
It's honestly a huge disappointment how component design has to be done in v3. You basically have to rewrite all components yourself and host them in your codebase... Really make no sense.

The migration from v2 is **painful**
