### ISSUE TITLE
Reference Error: structuredClone is not defined when testing with Tooltip

### ISSUE THREAD

**Issue by undertakingyou** [chakra-ui/chakra-ui#9201]
### Description

When I run tests on a component that uses Tooltip from a snippet I get the error `ReferenceError: structuredClone is not defined`.

### Link to Reproduction

https://github.com/undertakingyou/testing-chakra-two

### Steps to reproduce

1. Create a simple component that uses the Tooltip:
```
import { List, Text } from "@chakra-ui/react";
import { Tooltip } from "@/components/ui/tooltip";

export function DocumentInfo() {
    return (
        <List.Root>
            <List.Item>Document 1</List.Item>
            <List.Item>Document 2</List.Item>
            <List.Item>
                <Tooltip content="This is my tooltip">
                    <Text>Document 3</Text>
                </Tooltip>
            </List.Item>
        </List.Root>
    );
}
```

2. Create a simple test that tests this component:
```
import "@testing-library/jest-dom";
import { render } from "@testing-library/react";
import { DocumentInfo } from "./DocumentInfo";

describe("DocumentInfo", () => {
    const { getByText } = render(<DocumentInfo />);

    expect(getByText("Document 1")).toBeInTheDocument();
});
```

3. Run the tests `npm run test`

### Chakra UI Version

3.1.2

### Browser

Google Chrome 131

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I am using Next.js with nothing really special in the tests. I have set up a sample repository at https://github.com/undertakingyou/testing-chakra-two where you can see the error. The concern is with the `./app/list/_components/DocumentInfo.txs` and its associated spec file.

More details on versions:
* next: 15.0.3
* react: 18.3.1
* node: 22.9.0

**Comment by segunadebayo** [comment]
Please configure your jest config and define the structuredClone implementation. It seems it’s not supported in Jest just yet.

Here’s an example
https://github.com/smg-automotive/components-pkg/blob/0ce5cbe9da3818b0da508d77495949bb19c71fec/.jest/setup/structuredClone.ts
