### ISSUE TITLE
ColorPalette not working with custom color tokens

### ISSUE THREAD

**Issue by Baystef** [chakra-ui/chakra-ui#9209]
### Description

When I add Color tokens, I want to be able to see autocompletion and the colour been applied on the component, instead, autocomplete is not working and the colour is not been applied on the component

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-f26gd3?file=src%2Fmain.tsx,src%2Ftheme.ts,src%2Fcomponents%2Fui%2Fprovider.tsx,src%2FApp.tsx

### Steps to reproduce

ColorPalette of primary is set on the LinkButton and also the theme.ts has the primary colour tokens 

### Chakra UI Version

3.1.2

### Browser

Google Chrome 130

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Please follow this guide
https://www.chakra-ui.com/guides/theming-custom-colors
