### ISSUE TITLE
Theming does not work and documentation is wrong v3

### ISSUE THREAD

**Issue by austen-zeh** [chakra-ui/chakra-ui#9216]
### Description

When I define a recipe for button, none of the styling is used. I have to include "!important" in the css value to get the recipe to actually override the default.

Furthermore, the documentation shows to define the recipe as:

`const Button = chakra("button", {
  base: {
    display: "flex",
  },
  variants: {
    visual: {
      solid: { bg: "red.200", color: "white" },
      outline: { borderWidth: "1px", borderColor: "red.200" },
    },
    size: {
      sm: { padding: "4", fontSize: "12px" },
      lg: { padding: "8", fontSize: "24px" },
    },
  },
  defaultVariants: {
    visual: "solid",
    size: "lg",
  },
})`

However, the true format that is accepted and works is as follows:

`recipes: {
    button: defineRecipe({
        base: {
            bg: "bg !important"
        },
        variants: {
            variant: {
                solid: {
                    bg: "bg !important",
                    color: "fg"
                },
                outline: {
                    border: {
                        base: "1px solid lightgray !important",
                        _dark: "1px solid white"
                    }
                }
            }
        },
        defaultVariants: {
            variant: "outline"
        }
    })
}`

The documentation says to define "variants.visual.solid", but the true structure is "variants.variant.solid", same issue with defaultVariants. The documentation says "defaultVariants.visual" but the true structure is "defaultVariants.variant".

This makes development extremely difficult, because I am trying to follow the documentation but the docs are wrong leaving me to figure it out on my own. I have spent way more time than I should have to in order to style a button....

I don't understand why you have to completely change the way to "extend" themes in v3, i have wasted so much time on this.

### Link to Reproduction

no link needed

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

3.0.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you needed more information so that we could understand and reproduce the problem.

Please follow the issue template, as we cannot act on issues that lack essential information.

I'd appreciate it if you also keep feedback as constructive as possible.

**Comment by liemdo** [comment]
Thanks @austen-zeh. I spent hours trying to override the color of the button until I saw your post.
