### ISSUE TITLE
Toast does not display when changing placement

### ISSUE THREAD

**Issue by j-bullard** [chakra-ui/chakra-ui#9219]
### Description

When I change the `placement` of a toast when creating a toast, I expect the toast to be displayed in designated location, instead no toast is displayed.

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-bnvufm?file=src%2FApp.tsx

### Steps to reproduce

1. Add `<Toaster />` component to `main.tsx`
2. Add button and set `onClick` to show toast
3. Change toasts placement property to something other than what is defined in `toaster.tsx`
4. Click on button, toast will not display

### Chakra UI Version

3.2.0

### Browser

Google Chrome 131

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is by design. You should only use the placement defined in the toaster.tsx

We'll update the types to reflect this in the future.

If you want a toaster in a different location, create a new toaster altogether by duplicating the `toaster.tsx` file

**Comment by j-bullard** [comment]
My initial reaction is that this is a horrible design choice. But I definitely don't want to jump to conclusions because I don't know what is driving this. 

Why would I create a second `toaster.tsx` just to change the placement of the toaster? What other properties can I not change that would require another toaster to be created? How many `"toasters"` am I going to have to create for each of my use-cases?

At least for me I don't think I would ever need to use the default Chakra toaster if this is the case, and instead continue using other libs.
