### ISSUE TITLE
useBreakpointValue(..., { ssr: false }) causes error during build

### ISSUE THREAD

**Issue by hannaszepesi** [chakra-ui/chakra-ui#9224]
### Description

Hi!:) I am using Chakra UI v3.2.0 with NextJS and when I call useBreakpointValue with ssr: false and running `next build` it causes: `ReferenceError: window is not defined`. There was another issue related to useBreakpointValue with ssr: false that is already fixed in the version I am using, but the one I am reporting seems to be a different one.

### Link to Reproduction

https://stackblitz.com/edit/stackblitz-starters-negmml?description=The%20React%20framework%20for%20production&file=package.json,app%2Fpage.tsx,app%2Flayout.tsx&title=Next.js%20Starter

### Steps to reproduce

1. Run `npm run build` in the terminal.

### Chakra UI Version

3.2.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
You should use `ssr: false` in a client-only project like Vite or CRA. With Next.js, you need to keep `ssr: true`

**Comment by hannaszepesi** [comment]
@segunadebayo Thank you for the fast reply! I am using it in only client components, but I started using it originally because it prevented some initial flickering. For example I am using it in my AppBar and first it always renders the desktop version for a short moment, not the mobile. In V2 I could prevent this flickering with the ssr: false prop. Do you have any suggestions how to avoid it now?
