### ISSUE TITLE
File-Upload snippet broken

### ISSUE THREAD

**Issue by agenthesh** [chakra-ui/chakra-ui#9225]
### Description

When I run the command chakra snippet add file-upload (as mentioned in the docs [here](https://www.chakra-ui.com/docs/components/file-upload#setup) ), I get the following feedback in the console:

```
┌  Chakra CLI ⚡️
│
●  Adding 1 snippet(s)...
│
◇  Writing selected snippets
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```

### Link to Reproduction

N/A

### Steps to reproduce

1. Run $ chakra snippet add file-upload in terminal

### Chakra UI Version

3.1.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
That's a good catch @agenthesh. I've pushed a fix for this.
