### ISSUE TITLE
Chakra V3 error when using Icon from react-icons

### ISSUE THREAD

**Issue by GuilhermeAmado** [chakra-ui/chakra-ui#9227]
### Description

When I try to integrate with popular react icon libraries like react-icons according to the documentation (https://www.chakra-ui.com/docs/components/icon), I have an error on the console.

![image](https://github.com/user-attachments/assets/d5e44806-db19-4b97-be64-99fd91095d71)

![image](https://github.com/user-attachments/assets/0584e2aa-0bcc-440d-bdb8-bc2b992b8bb5)

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-rnbeyf?file=src%2FApp.tsx

### Chakra UI Version

3.1.1

### Browser

All browsers

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
This is a long-standing error from react-icons. They don't forwardRef correctly
https://github.com/react-icons/react-icons/issues/336

**Comment by imhmdb** [comment]
just in case anyone was looking for a workaround to fix this, I managed to resolve the warning in my project using this:
```typescript
import { forwardRef } from 'react';
import { Icon, Span, type IconProps } from '@chakra-ui/react';
import type { ForwardRefRenderFunction } from 'react';
import type { IconType } from 'react-icons'

type ReactIconProps = IconProps & {
  icon: IconType;
};

const ReactIcon: ForwardRefRenderFunction<HTMLElement, ReactIconProps> = ({ icon: IconType, ...props }, ref) => (
  <Icon {...props}>
    <Span ref={ref} height={"unset"} lineHeight={"unset"}>
        <IconType />
    </Span>
  </Icon>
);

const ForwardedReactIcon = forwardRef(ReactIcon);

export { ForwardedReactIcon as ReactIcon };
```

and then I use it like this:
```typescript
import { ReactIcon } from '@/components/ui/icon';

<ReactIcon icon={FaPlus} px={1} fontSize={'lg'} />
```
instead of doing:
```typescript
<Icon>
    <FaPlus />
</Icon>
```

p.s. I'm new to react so I'm not sure if there's anything wrong with my approach

**Comment by alexpeev9** [comment]
Hello,
I experimented with several approaches, but this was the only one that resolved my issue.

```
import { Icon as ChakraIcon, IconProps as ChakraIconProps, Span } from "@chakra-ui/react";
import React from "react";
import { IconType } from "react-icons/lib";

type IconProps = ChakraIconProps & {
    icon: IconType;
};

const Icon = React.forwardRef<HTMLElement, IconProps>(({ icon: IconElement, ...props }, ref) => (
    <ChakraIcon {...props} asChild>
        <Span ref={ref}>
            <IconElement style={{ width: "100%", height: "100%" }} />
        </Span>
    </ChakraIcon>
));

export { Icon };
```

How to use
```
import { Icon } from "../ui/Icon";

<Icon boxSize={7} icon={PiHouse} />
```

I hope that someone finds a better approach or fixes this. 🍀

**Comment by michelpf** [comment]
> just in case anyone was looking for a workaround to fix this, I managed to resolve the warning in my project using this:
> 
> ```ts
> import { forwardRef } from 'react';
> import { Icon, Span, type IconProps } from '@chakra-ui/react';
> import type { ForwardRefRenderFunction } from 'react';
> import type { IconType } from 'react-icons'
> 
> type ReactIconProps = IconProps & {
>   icon: IconType;
> };
> 
> const ReactIcon: ForwardRefRenderFunction<HTMLElement, ReactIconProps> = ({ icon: IconType, ...props }, ref) => (
>   <Icon {...props}>
>     <Span ref={ref} height={"unset"} lineHeight={"unset"}>
>         <IconType />
>     </Span>
>   </Icon>
> );
> 
> const ForwardedReactIcon = forwardRef(ReactIcon);
> 
> export { ForwardedReactIcon as ReactIcon };
> ```
> 
> and then I use it like this:
> 
> ```ts
> import { ReactIcon } from '@/components/ui/icon';
> 
> <ReactIcon icon={FaPlus} px={1} fontSize={'lg'} />
> ```
> 
> instead of doing:
> 
> ```ts
> <Icon>
>     <FaPlus />
> </Icon>
> ```
> 
> p.s. I'm new to react so I'm not sure if there's anything wrong with my approach

Your solution worked like a charm in my application. Thank you for sharing!
