### ISSUE TITLE
Has useOutsideClick been removed?

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#9229]
useOutsideClick doesn't seem available anymore? However there is no mention in the migration guide.

https://www.chakra-ui.com/docs/get-started/migration

**Comment by segunadebayo** [comment]
This is mentioned somewhat in the docs. I tweaked the wording in the migration guide

**Comment by lcswillems** [comment]
@segunadebayo Could you point me out to the place in the documentation where it is mentioned? I can't find out
