### ISSUE TITLE
What's the equivalent of <Input variant="unstyled" /> in v3?

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#9234]
The migration doesn't mention anything regarding the variant "unstyled" of the Input in v3.

Has it been removed? What's the alternative?

https://www.chakra-ui.com/docs/get-started/migration#input-select-textarea

**Comment by AlphaNecron** [comment]
You can try importing Input from ark-ui.

**Comment by lcswillems** [comment]
Thanks @segunadebayo ! Is it documented anywhere in the website? Asking to know if I missed something.

And it would seem more logic to have a variant:

```
<Input variant="unstyled" />
```
