### ISSUE TITLE
ListItem unexpected styling

### ISSUE THREAD

**Issue by DeJayDev** [chakra-ui/chakra-ui#9235]
### Description

While upgrading from Chakra UI 2 to Chakra UI 3, we updated our mdx powered pages to use the new components `List.Item` and `List.Root` from `ListItem` and `OrderedList`. However, the resulting generated page is visually different.

| v2 | v3 |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/f46772db-5be5-4440-b233-f4973b23caf6) | ![image](https://github.com/user-attachments/assets/436e40d6-01fa-4195-85c0-407c3c6b6c84) |
| ![image](https://github.com/user-attachments/assets/7151a762-ef36-460f-b33b-42c32fc99e47) | ![image](https://github.com/user-attachments/assets/04453c0c-024e-4d98-9442-9b996b497e86) |  

It should be important to note, the generated HTML is *not* different. The only differences come in how Chakra UI v3 generates classnames.

### Link to Reproduction

Source Code:
https://github.com/DeJayDev/chakra-visual-incompatibility

Deployed To:
https://chakra-9235.playless.workers.dev/weird

PS: Chakra is too big to deploy to Workers without Workers Paid?

### Chakra UI Version

3.2.0

### Additional Information

This is a Next.js v14 app, using the app router.

**Comment by lcswillems** [comment]
Good that you posted! I hesitated to post too. Same remark on my side :+1:

**Comment by segunadebayo** [comment]
We'll update the migration guide as needed.

For now, please update the styling similar to
https://github.com/chakra-ui/chakra-ui/blob/main/apps/compositions/src/examples/list-with-marker-style.tsx

Alternatively, you can use the Prose component
https://www.chakra-ui.com/docs/components/prose

**Comment by DeJayDev** [comment]
This doesn't resolve the issue.

The marker style doesn't visually change the page at all unless you additionally define `listStyle="decimal"` with the marker style causes the numbers to vanish entirely and that is unfortunately not a solution.

The alternative of using Prose is also impossible. If it wasn't clear, I am using [Next.js' built in MDX handling](https://nextjs.org/docs/app/building-your-application/configuring/mdx). All I can do is define component styles. I (and others) would expect to be able to have my Terms of Service not break during the upgrade to Chakra v3. It's unreasonable to have to maintain the full copy of a Privacy Policy and Terms of Service in React. 

This is all of the control I have:
https://github.com/Playlessgames/chakra-9235/blob/main/mdx-components.tsx#L12-L14
