### ISSUE TITLE
Problem with custom breakpoints (migration)

### ISSUE THREAD

**Issue by t4llfly** [chakra-ui/chakra-ui#9241]
### Description

On Chakra UI v2, i had used custom breakpoints named '2xl' and '3xl'. After update to v3, IDE sending error
"TS2353: Object literal may only specify known properties, and '3xl' does not exist in type"

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-k4hkih?file=src%2FApp.tsx

### Steps to reproduce

1. Create new theme using theme.ts
2. Insert it into Provider
3. Attempt to use object syntax with this breakpoint

### Chakra UI Version

3.0.0

### Browser

Firefox 132

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![image](https://github.com/user-attachments/assets/ef28cada-a583-4e7f-b22d-c08c5a7c84aa)

**Comment by segunadebayo** [comment]
Please follow the instructions here:
https://www.chakra-ui.com/docs/theming/customization/overview#complete-customization

You need to update the types using the CLI

**Comment by sayshark75** [comment]
Hey @segunadebayo, i have same issue, unable to use custom breakpoints
```
// theme.ts
import { createSystem, defaultBaseConfig, defineConfig } from "@chakra-ui/react";
import { fonts } from "./fonts";
import globalCss from "./global";
import { breakpoints } from "./breakpoints";
import colors from "./colors";

const customConfig = defineConfig({
  preflight: true,
  cssVarsPrefix: "chakra",
  cssVarsRoot: ":where(:root, :host)",
  globalCss,
  theme: {
    breakpoints,
    tokens: {
      fonts,
      colors,
    },
  },
});

export default createSystem(defaultBaseConfig, customConfig);
```
breakpoints.ts
```
export const breakpoints = {
  base: "20em", // 320px // first mobile
  mobile: "23.125em", // 370px // second mobile
  sm: "26.25em", // 420px // third mobile
  smd: "30em", // 480px // fourth mobile
  md: "48em", // 768px // common tablet
  fold: "54.375em", // 870px // unfolded as tablet
  lg: "64em", // 1024px // first desktop
  xl: "73.75em", // 1180px // second
  xxl: "90em", // 1440px	// third
  fo: "98.75em", // 1580px //fourth
};
```
tried to update types using cli
```
npx @chakra-ui/cli typegen ./src/styles/theme.ts
 ```
- I know currently not planned to fix it, but any workaround to it?
- here is the log of issue, on the `mobile` breakpoint
```
Object literal may only specify known properties, and 'mobile' does not exist in type 'readonly string[] | ("border" | "bg" | "colorPalette" | `var(--${string})` | (string & {}) | AnyString | "-moz-initial" | "inherit" | "initial" | "revert" | "revert-layer" | "unset" | ... 433 more ... | undefined)[] | { ...; }'.
```
the colors changing to proper breakpoint size
```
<Box
        margin={"auto"}
        bgColor={{
          base: "tomato",
          mobile: "green",
          sm: "blue",
          smd: "yellow",
          md: "red",
          fold: "green",
          lg: "blue",
          xl: "yellow",
          xxl: "red",
          fo: "green",
        }}
        maxW={{ base: "90%", lg: "980px", xl: "1150px", xxl: "1280px", fo: "1400px" }}
        {...props}
      >
        {children}
      </Box>
      ```

**Comment by t4llfly** [comment]
i found temporary solution for this problem. you need to install cli as dev dependency, and after that it will create types with `typegen`. it will also work while building project, but if you use GitHub workflow you should also add installation of cli in script.

**Comment by sayshark75** [comment]
Not worked, i was using nextjs 15, do it causing such issues?
