### ISSUE TITLE
Icon created by createIcon disappears when using a Linear Gradient inside a Hover Card

### ISSUE THREAD

**Issue by Jkdrumm** [chakra-ui/chakra-ui#9244]
### Description

When I use `createIcon` that has a `<LinearGradient />` inside multiple `<HoverCard />` components, the Icon does not show in the later renderings unless the first `<HoverCard />` is open and visible. I expected the icon to be visible in both cards regardless if the other ones are open, but the icon disappears instead.

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-xkinlk?file=src%2FApp.tsx

### Steps to reproduce

1. Hover button labeled "Hover 1"
2. Hover button labeled "Hover 2"
3. See the icon disappear from the "Hover 2" card when the "Hover 1" hover card is not open

### Chakra UI Version

3.2.0

### Browser

Brave v1.73.91

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I suspect this is because of how referencing linear gradients with `url(#id)` works, referencing the gradient that is not visible. I tried creating random IDs but I think all instances use the same random ID and this method also led to hydration errors in Next.js. A workaround was to render the icon before the Hover Cards render

**Comment by segunadebayo** [comment]
You need to generate unique IDs for each linear gradient using useId from React.

https://stackblitz.com/edit/chakra-ui-v3-onfcs8?file=src%2Fcomponents%2Fcompound%2FChakraIcon.tsx
