### ISSUE TITLE
chakra-cli document about `chakra snippet --dir` is incorrect

### ISSUE THREAD

**Issue by ryo-hoshino-UB** [chakra-ui/chakra-ui#9246]
### Description

I attempted to specify the directory to add snippets with npx chakra snippets `--dir` ./components/custom as outlined in `apps/www/content/guides/snippet-specify-custom-directory.mdx`, but unfortunately, it did not work due to an issue with the command snippets and option `--dir`.
Finally, I found the correct each of them (`snippet` and `--outdir`) from the [issue](https://github.com/chakra-ui/chakra-ui/issues/9067) and I was done what I wanted to do.
`npx @chakra-ui/cli snippet add --outdir ./src/ui`

After some trial and error, I managed to find the correct command for adding snippets (`npx @chakra-ui/cli snippet add --outdir ./src/ui)` from the [issue](https://github.com/chakra-ui/chakra-ui/issues/9067). This allowed me to achieve my desired outcome.
However, I noticed some inconsistencies in the documentation, which I would appreciate your help in addressing.
- https://github.com/chakra-ui/chakra-ui/blob/6ab2ea3720cb4dd5af185f548a307d8307cea977/apps/www/content/docs/get-started/cli.mdx?plain=1#L89
- https://github.com/chakra-ui/chakra-ui/blob/6ab2ea3720cb4dd5af185f548a307d8307cea977/apps/www/content/guides/snippet-specify-custom-directory.mdx?plain=1#L14

### Link to Reproduction

None

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

3.2.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I've updated the docs accordingly.
