### ISSUE TITLE
useColorMode with latest chakra-ui/react

### ISSUE THREAD

**Issue by jerome-diver** [chakra-ui/chakra-ui#9253]
### Description

When i use documented code about usecolorMode, i would like it to not generate error

### Link to Reproduction

do not need

### Steps to reproduce

1. install chakra-ui latest
2. follow the documentation
3. after components directory has been generated, you can find in file color-mode.tsx that it generate an import error because there is no next-theme to import from.

### Chakra UI Version

latest

### Browser

error at compile time

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
This has been fixed in the latest CLI version. Please install `next-themes` locally and it should work as expected.

**Comment by jerome-diver** [comment]
Ok, but do you update your documentation accordingly with real fact ?
The error is about fake documentation that does not reflect the reality. 
Before to close, i suppose that you do fix the documentation, correct ?
