### ISSUE TITLE
Markers aren't positioned correctly when slider orientation is vertical

### ISSUE THREAD

**Issue by joekrill** [chakra-ui/chakra-ui#9255]
### Description

With `orientation="vertical"` the markers "bunch up" at the top of the slider. It's more evident when using labels because without them the dots can sometimes be a bit hard to see (they can be seen more easily in dark mode). 

<img width="442" alt="Screenshot 2024-11-26 at 6 06 22 AM" src="https://github.com/user-attachments/assets/cf0bb5d2-5ca8-4096-ae4a-922f130c5ca1">

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-wfzk9n?file=src%2FApp.tsx

### Steps to reproduce

Create a `<Slider />` component with `orientation="vertical"` and `marks={[0,25,50,75, 100]}`

### Chakra UI Version

3.2.0

### Browser

Firefox (but browser agnostic)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by joekrill** [comment]
I started looking into what it might take to fix this. I have a branch here with it "fixed": 

https://github.com/chakra-ui/chakra-ui/compare/main...joekrill:chakra-ui:fix/vertical-slider-markers?expand=1

<img width="79" alt="Screenshot 2024-11-26 at 9 31 55 AM" src="https://github.com/user-attachments/assets/c0e79361-9c15-441a-8235-057045433559">

While this definitely fixes the marker positioning, the main problem is how to handle labels (if they exist). They are (currently) absolutely positioned so it's going to potentially overlap other elements. To what extent is entirely dependent on the length of the labels. 


<img width="91" alt="Screenshot 2024-11-26 at 9 32 20 AM" src="https://github.com/user-attachments/assets/974d22d4-794d-44f7-9141-ec3983aeb453">

However, that branch  _does_ put things in a _better_ state than they currently are. That is, it's broken either way, just "less broken" in this branch (as long as markers aren't labelled it's fine). Further, it seems like labeling markers isn't really documented, so maybe it's not supposed to be fully supported yet?

I'm happy to put this up as a PR as-is, but also totally understand if this isn't the ideal fix and it should be held off until it's "fully" fixed. I did make one questionable change: there was some padding that was being added in the composition when markers had labels -- I swapped that out with a data attribute so that the padding could be added in the recipe instead. But I'm not sure that's really the way the Chakra team would want that handled. So if you do want me to put the PR up, just let me know how you'd like me to handle that (If I move it back to logic in the composition, then there just needs to be an additional check to only apply it when the orientation is horizontal).

**Comment by joekrill** [comment]
I just found another bug with the slider marker positioning: when you include [a label for the slider itself](https://www.chakra-ui.com/docs/components/slider#label) while also including marks, the marks become positioned over top of the label (used dark mode again here because it's easier to see):

<img width="258" alt="Screenshot 2024-11-26 at 5 40 26 PM" src="https://github.com/user-attachments/assets/9924de76-2e59-4a4d-9606-5c65faa3d8c8">

The code for the above screenshot is from modifying the `slider-with-label.tsx` example to:

```jsx
<Slider
  label="Quantity"
  width="200px"
  defaultValue={[40]}
  marks={[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]}
/>
```

**Comment by segunadebayo** [comment]
Thanks for the detailed feedback on the markers. It helped a lot to track the issues.

I've refactored the snippet and recipe to fix this. I've also updated the docs accordingly.

Will release a patch shortly
