### ISSUE TITLE
CssVarsRoot should be respected in @layer reset, base and tokens to prevent global style leakage

### ISSUE THREAD

**Issue by du33169** [chakra-ui/chakra-ui#9256]
### Description

I am using Chakra-ui in a subsystem as part of a huge project. By default, Chakra overrides some of the global styles, so I tried the solution mentioned in [#2145](https://github.com/chakra-ui/chakra-ui/issues/2145), using shadow dom and `CacheProvider`.

However, some Chakra styles do not inherit correctly. After investigating for days, I found the following rules to be involved:

| css layer | rule(selector)            | configuration entry to override | file |
| ------- | --------------------------- | ------------------------------- | ------------------------------- |
| @reset  | html                        | preflight: {scope: ...}         | (not found, possibly in panda css) |
| @base   | html                        | delete defaultConfig.globalCss.html;<br>globalCss:{xxx:{...}} | `packages/react/src/theme/global-css.ts` |
| @tokens | :where(html,.chakra-themes) | cssVarsRoot                     | `packages/react/src/theme/index.ts` |
| @tokens | :root, .light               | condition:{light:...}           | `packages/react/src/preset-base.ts` |

Overriding the above configuration entries will fix most of them:
```typescript
const myCssVarsRoot = ":host";
const config = defineConfig({
  cssVarsRoot: myCssVarsRoot,
  conditions: {
    light: `${myCssVarsRoot}, .light`,
  },
  preflight: { scope: myCssVarsRoot },
  globalCss: {
    [myCssVarsRoot]: defaultConfig.globalCss.html,
  },
});
const system = createSystem(defaultConfig, config);
```

In this way we can prevent Chakra styles from leaking without shadow dom by setting `myCssVarsRoot` to the target element. A full implementation of this `ContainedProvider` is available in this [codesandbox](https://codesandbox.io/p/sandbox/wispy-leaf-h99sgr) (and `ShadowProvider` if shadow dom is still needed). 

(Note: Drawer and Dialog use a built-in portal that defaults to `docuemnt.body`. To use it in a contained situation, either set `portalled={false}` on `DrawerContent` or specify `portalRef` manually). However, this is only a tricky workaround. Some problems, such as font, are still not fully solved. 

I recommend **using `cssVarsRoot` to replace these default values, instead of hardcoded `html`, `:root` and other selectors** in the styling engine to fix the style leakage problem.

### Link to Reproduction

https://codesandbox.io/p/sandbox/wispy-leaf-h99sgr

### Steps to reproduce

1. Go to the [codesandbox](https://codesandbox.io/p/sandbox/wispy-leaf-h99sgr)
2. Click on 'Load Charka (Provider)'
3. See error:
   1. The table gets `margin: 0`
   2. The button style is overrided
   3. The Charka Button and Drawer inherit the global font

Screenshot:

![图片](https://github.com/user-attachments/assets/5c67e05d-d6f8-4120-9b3a-f61dc6be29d0)

### Chakra UI Version

3.2.0

### Browser

Mozilla Firefox v132.0.2

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Default value for cssVarsRoot

I have been trying to find a better default value for `cssVarsRoot` to add support for shadow dom. But `:where(:root,:host)` doesn't work as expected inside a shadow dom. For example, the following css works in a light dom, but has no effect in a shadow dom:

```css
:where(:root,:host){--mycolor: blue;}
div {color: var(--mycolor); }
```

I'm not an expert on CSS so this is just a reminder in case anyone is interested.

### Style Leakage

This is the problem someone is bound to run into if they want to use Chakra in a serious and complex project, or if they want to develop a browser extension. In fact, it becomes a major reason why some developers have to deprecate Chakra UI (see #7520), even though they like it. 

If possible, I recommend that the team pay more attention to this, and add appropriate testing and documentation.

**Comment by ganeshkrishnasharma** [comment]
I am facing this issue as well. I have built an SDK package with CSS heavy elements, and facing css leakage issues in both ways, ( some styles of parent app is overriding my sdk styles & some styles of my sdk is overriding the styles of parent app ) . 

Please recommend what is the clean way to handle this situation? @segunadebayo . Thanks in advance

**Comment by segunadebayo** [comment]
I've just added a shadow DOM example in the sandbox. Check it out here:
https://github.com/chakra-ui/chakra-ui/tree/main/sandbox/shadow-dom

We'll update the docs shortly to include a getting started guide for Shadow DOM

**Comment by bertho-zero** [comment]
If I add this part, then my modal closes as soon as I remove and then give focus back to the page. If I remove it, it seems to work correctly. What is it used for?

```jsx
<EnvironmentProvider value={() => shadow.shadowRoot ?? document}>
```

edit: It works if the Dialog is not portalled and the backdrop is broken...
