### ISSUE TITLE
Loading prop doesn't exist on IconButton component but indicate in documentation

### ISSUE THREAD

**Issue by Benjamin-htr** [chakra-ui/chakra-ui#9264]
### Description

Hi !

The component icon button doesn't have the loading attribute like the button, even though the documentation lists it.

- documentation of the icon button :
<img width="833" alt="image" src="https://github.com/user-attachments/assets/5b44eff4-c1a7-41b0-a7d7-a97dfb2dd2e1">

- typescript error in my IDE :
<img width="1284" alt="SCR-20241128-nehr" src="https://github.com/user-attachments/assets/096ded4b-addb-4774-a82e-c65e530faa41">

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-j2w65j?file=src%2FApp.tsx

### Steps to reproduce

1. Go to the stackblitz reproduction
2. Check inside src/App.tsx

### Chakra UI Version

3.0.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Pushed a fix for this.

**Comment by matteo0402** [comment]
Any reason why the IconButton won't have the loading prop?
