### ISSUE TITLE
Unexpected constant nullishness on the left-hand side of a `??` expression

### ISSUE THREAD

**Issue by j-bullard** [chakra-ui/chakra-ui#9268]
### Description

When I install blocks into a clean Vite project, I get an eslint warning about [no-constant-binary-expression](https://eslint.org/docs/latest/rules/no-constant-binary-expression).

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-bnvufm?file=src%2FApp.tsx

### Steps to reproduce

Follow steps on [Using Chakra with Vite](https://www.chakra-ui.com/docs/get-started/frameworks/vite) but instead of installing default components, install all `npx @chakra-ui/cli snippet add`.

### Chakra UI Version

3.2.1

### Browser

Google Chrome 131

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Inside of chart.tsx, the following code exists

```tsx
  const total = filteredPayload?.reduce((acc, item) => {
    return acc + (Number(item.value) ?? 0)
  }, 0)
```

Recommend changing it to:

```tsx
  const total = filteredPayload?.reduce((acc, item) => {
    (isNaN(Number(item.value)) ? 0 : Number(item.value))
  }, 0)
```

That way it checks to see if the value can be a number and returns 0 if not, while still representing other values as a number.

**Comment by segunadebayo** [comment]
Good catch. I've updated the snippet as needed
