### ISSUE TITLE
PasswordInput Icon margin 

### ISSUE THREAD

**Issue by Ahmed-Ibrahim-Anter** [chakra-ui/chakra-ui#9271]
### Description

I'm experiencing an issue where I am unable to modify the icon's props or style directly from my component. Specifically, I want to remove a negative value to the icon's position so that it touches the border, but I can't access or change the icon's properties as needed.
![Screenshot 2024-12-01 063408](https://github.com/user-attachments/assets/9fecb78d-3aed-4af5-be1a-5a2f2f4b257c)
![Screenshot 2024-12-01 063325](https://github.com/user-attachments/assets/5183bc57-b8a4-42f5-b10c-4de869bfe58e)

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3?file=src%2FApp.tsx

### Chakra UI Version

3

### Browser

 131.0.6778.86

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
You can change this in your codebase in the `password-input.tsx` file directly.

Please attach a reproduction to get more help.
