### ISSUE TITLE
Responsive semanticTokens doesn't work

### ISSUE THREAD

**Issue by tranbathanhtung** [chakra-ui/chakra-ui#9283]
### Description

```js
semanticTokens: {
  spacing: {
    container: {
      value: { base: "spacing.4", _md: "spacing.6", _lg: "spacing.8" },
    },
  },
},
```
or 
```js
semanticTokens: {
  spacing: {
    container: {
      value: { base: "spacing.4", md: "spacing.6", lg: "spacing.8" },
    },
  },
},
```

even with custom conditions #9178 

Both of the syntax doesn't work. Only the base is rendered. I already stuck with this issue 2 week

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-mdhsh2?file=src%2Fcomponents%2Fui%2Fprovider.tsx,src%2FApp.tsx

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

3.1.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Here's the correct referencing syntax

```ts
semanticTokens: {
  spacing: {
    container: {
      value: { base: "{spacing.4}", md: "{spacing.6}", lg: "{spacing.8}" },
    },
  },
},
```
