### ISSUE TITLE
Ark-ui modules cannot find in chakra-ui exports

### ISSUE THREAD

**Issue by leodionizio** [chakra-ui/chakra-ui#9284]
### Description

When I run tests using jest or react-scripts, appears the error log:
```
Cannot find module '@ark-ui/react/format' from 'node_modules/@chakra-ui/react/dist/cjs/components/format/index.cjs
```
When I added the correct path in `moduleNameMapper` in `jest.config.js` this is required for all components.

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-r1asw8?file=src%2FApp.tsx

### Steps to reproduce

1. Install Chakra-UI V3
2. Run tests
3. See error

### Chakra UI Version

3.2.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

![Screenshot 2024-12-03 at 10 00 51](https://github.com/user-attachments/assets/c8bc3170-557c-4758-a31d-55eb5a2d4bb8)
![Screenshot 2024-12-03 at 10 01 23](https://github.com/user-attachments/assets/8c287e13-633e-460c-99f6-1471643552d6)
![Screenshot 2024-12-03 at 10 01 32](https://github.com/user-attachments/assets/5c70afac-be70-427c-b9f2-2994b2849380)

**Comment by segunadebayo** [comment]
I would recommend setting ESM resolution for your Jest set up or switch to Vite/Bun that resolves ESM by default
