### ISSUE TITLE
Value of Semantic Tokens Color

### ISSUE THREAD

**Issue by AvanadeMichal** [chakra-ui/chakra-ui#9285]
### Description

Shouldn't the values of these css variables be exactly as in the theme/semantic-tokens/colors.ts file?

What I don't agree with is the colourPalete.muted in light mode which is set to 
```
export const colors = defineSemanticTokens.colors({
  ...
  yellow: {
    ...
    muted: {
      value: {
        base: ‘{colors.yellow.50}’,
```

and css variable is :
--chakra-colors-yellow-muted: var(--chakra-colors-yellow-200);

The same think with the rest colors variable. 
![Screenshot 2024-12-03 145247](https://github.com/user-attachments/assets/2d4ebb4b-d6a9-4a18-ab78-f742a9b4a6b3)
![Screenshot 2024-12-03 145332](https://github.com/user-attachments/assets/fb7afd73-9011-4710-8ba1-16f59ffc3678)

### Link to Reproduction

https://www.chakra-ui.com/

### Steps to reproduce

1. Go to (https://www.chakra-ui.com/)
2. Click on dev tools
3. Scroll down to css variables

### Chakra UI Version

3.2.0

### Browser

Edge

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
If you disagree, you can always customize the semantic token colors.

https://www.chakra-ui.com/docs/theming/semantic-tokens
