### ISSUE TITLE
Responsive semanticTokens doesn't work #3

### ISSUE THREAD

**Issue by pepelele** [chakra-ui/chakra-ui#9289]
### Description

#9283 
#9178

https://github.com/chakra-ui/chakra-ui/issues/9283#issuecomment-2515597247
```js
semanticTokens: {
  spacing: {
    container: {
      value: { base: "{spacing.4}", md: "{spacing.6}", lg: "{spacing.8}" },
    },
  },
},
```
It doesn't work. If it works please give me a REAL WORKED EXAMPLE link like this https://stackblitz.com/edit/chakra-ui-v3-mdhsh2?file=src%2Fcomponents%2Fui%2Fprovider.tsx,src%2FApp.tsx. Please take responsibility for your answer

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-mdhsh2?file=src%2Fcomponents%2Fui%2Fprovider.tsx,src%2FApp.tsx

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

3.1.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hey. Sorry about the previous answer. It was actually a bug (despite the correct syntax)

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by pepelele** [comment]
tks u <3
