### ISSUE TITLE
Button inside Tooltip does not have attached Group properties set

### ISSUE THREAD

**Issue by dtemkin1** [chakra-ui/chakra-ui#9294]
### Description

When I placed a Button inside a Tooltip in a Group with the attached prop, it doesn't properly style the corners as attached. I'm not sure if I'm doing something wrong? But let me know! :)

![image](https://github.com/user-attachments/assets/49d9129b-b0d1-4544-8b80-a5a1ae79a230)

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-g4tvat?file=src%2FApp.tsx

### Steps to reproduce

1. Create a `<Group />` component with the `attached` prop
2. Add a few `<Button />` components inside the group
3. Wrap a button with a `<Tooltip />` component

### Chakra UI Version

3.2.3

### Browser

Google Chrome 131

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is a design limitation due to how the Group component works. It forwards specific styling props to its children.

You can resolve it by creating a dedicated `LabeledButton` component and forward the props.

```tsx
const LabeledButton = (props: ButtonProps) => {
  const { title, ...rest } = props;
  if (!title) return <Button {...rest} />;
  return (
    <Tooltip content={title}>
      <Button {...rest} />
    </Tooltip>
  );
};

function App() {
  return (
    <Center minH="dvh">
      <Box pos="absolute" top="4" right="4">
        <ColorModeButton />
      </Box>
      <VStack gap="5">
        <Group attached>
          <Button>Button 1</Button>
          <Button>Button 2</Button>
          <Button>Button 3</Button>
          <LabeledButton title="Tooltip on button!">Button 4</LabeledButton>
          <Button>Button 5</Button>
        </Group>
      </VStack>
    </Center>
  );
}
```
