### ISSUE TITLE
[Textarea] doesn't have resize option

### ISSUE THREAD

**Issue by jestrux** [chakra-ui/chakra-ui#93]
After going through the code, I noticed [here](https://github.com/chakra-ui/chakra-ui/blob/4085e27ecff1b295cea7265011921b5d12c25f15/packages/chakra-ui/src/Textarea/index.js#L21) that there's an **ExpandingTextarea** component being exported but I didn't see mention of this in the docs.

**Comment by jestrux** [comment]
I would happily create a pull request to update the docs with an example showing the ExpandableTextarea or add a resize prop to the TextArea component itself.

**Comment by segunadebayo** [comment]
Hi @jestrux,

I'm not sure what you mean by "resize".

If you're referring to the css resize style, the `<Textarea/>` component can be passed a `resize` prop and you can set its value to be "horizontal", "vertical", etc.

If what you mean is that Textarea's height should auto-resize based on the content in it, then we might need to export the `ExpandingTextarea` component. Feel free to create a PR for this update. Ideally, it'll be in its own folder and have its type definition.

Thanks.

**Comment by jestrux** [comment]
Hi @segunadebayo 

I was actually talking about the prior.

The docs don't show that you can pass "resize" as a prop like you said, and on the list of props for `TextArea` component, it just says _The Textarea composes the Input component_ and then when you go to the `Input` component "resize" is not listed as one of the props.

**Comment by jestrux** [comment]
I would love to work on exporting the ExpandingTextArea component, is there anythig I need to know other than what's on the contributing guidelines?

**Comment by segunadebayo** [comment]
Hi @jestrux ,

I agree. Please feel free to add the `resize` prop to the Textarea docs.

I'd appreciate if you add the ExpandingTextarea component as well. Here's what you need to do:

- Create a new folder named `ExpandingTextarea`
- Add `index.js`, `index.d.ts`, and `examples.js`
- Add the component code in `index.js`
- Add type definitions in `index.d.ts`
- Add some storybook examples in `examples.js`
- Update the `src/index.js` and `src/index.d.ts` to include the `ExpandingTextarea`.
- Update the docs for Textarea

I'll include this in the contribution guidelines shortly.

Thanks.

**Comment by jestrux** [comment]
Thanks, this is very helpful. I'll get right on it.
