### ISSUE TITLE
Using font CSS variables in system config makes --chakra-fonts-[token] not defined

### ISSUE THREAD

**Issue by thomasarbona** [chakra-ui/chakra-ui#9309]
### Description

When I setup the theme.tokens.fonts with CSS variables in system config (following this guide https://www.chakra-ui.com/guides/theming-add-custom-font-to-nextjs), it cause the text fonts variables linked to be not defined.

```typescript
const system = createSystem(defaultConfig, {
  theme: {
    tokens: {
      fonts: {
        heading: { value: "var(--font-geist-sans)" },
        body: { value: "var(--font-geist-mono)" },
      },
    },
  },
})
```

Then on Heading element:
![Screenshot 2024-12-08 at 20 32 35](https://github.com/user-attachments/assets/89f530b5-5f0a-432f-a6ad-bfc3ec4cc361)

### Link to Reproduction

https://github.com/thomasarbona/chakraui-cssvar-bug-repro

### Steps to reproduce

See on home page how <Heading /> and <Text /> have not defined text font variables

### Chakra UI Version

3.2.3

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Based on the docs, please attach the font variables to the HTML element

![CleanShot 2024-12-12 at 22 01 45@2x](https://github.com/user-attachments/assets/48fea707-677d-46c2-bfbf-6a1d8ae21efa)

**Comment by thomasarbona** [comment]
Ok thank's, my bad I missed this point in the doc
