### ISSUE TITLE
[Bug] All styling reset with following dependencies. Trying to upgrade dependencies

### ISSUE THREAD

**Issue by spate9** [chakra-ui/chakra-ui#931]
Created new next app and install chakra using: yarn add @chakra-ui/core @emotion/core @emotion/styled emotion-theming

Added the following dependencies to my package.json: 
"dependencies": {
    "@chakra-ui/core": "^1.0.0-next.2",
    "@emotion/core": "^10.0.28",
    "@emotion/styled": "^10.0.27",
    "emotion-theming": "^10.0.27",
    "next": "9.4.4",
    "react": "16.13.1",
    "react-dom": "16.13.1"
  }
}

Styles no longer work.

 If I revert to the following dependencies: 
  "dependencies": {
    "@chakra-ui/core": "0.8.0",
    "@emotion/core": "10.0.28",
    "@emotion/styled": "10.0.27",
    "emotion-theming": "^10.0.27",
    "next": "^9.1.7",
    "react": "^16.12.0",
    "react-dom": "^16.12.0"
  }
styles resume working.

Anyone else having this issue? How can I rectify this

**Comment by ljosberinn** [comment]
You most likely dont need those emotion dependencies anymore. Take a look at my package.json [here](https://github.com/ljosberinn/personal-react-boilerplate/blob/master/package.json#L15).

**Comment by segunadebayo** [comment]
@spate9 The pre-release is still experimental and we're working to make it stable.

The reason you don't have styles is that we've moved the theme to its own package.

- Install `@chakra-ui/theme`
- `import theme from @chakra-ui/theme`
- Mount the theme on the ChakraProvider or ThemeProvider

PS: We'll document this in the migration guide.

**Comment by spate9** [comment]
@ljosberinn Thanks for sharing. That fixed it.

@segunadebayo Perfect -- thanks for clarifying. Appreciate it! Able to get it to work now.
