### ISSUE TITLE
Typescript errors with select snippet

### ISSUE THREAD

**Issue by ahcai** [chakra-ui/chakra-ui#9314]
### Description

When I installed the `select` snippet through `npx @chakra-ui/cli snippet add select` in Chakra UI V3, I get these typescript errors.
![Screenshot 2024-12-09 at 2 38 19 PM](https://github.com/user-attachments/assets/5217b431-6c06-474c-9de3-efea9318c591)

### Link to Reproduction

Internal repo

### Steps to reproduce

Typescript version: 4.4.2
React version: 18.3.1

### Chakra UI Version

3.2.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by veloware** [comment]
Related discussions - https://github.com/chakra-ui/chakra-ui/discussions/9282, https://github.com/chakra-ui/chakra-ui/discussions/9306

**Comment by segunadebayo** [comment]
Closing this in favor of the above discussions.

**Comment by ahcai** [comment]
I ended up updating my `moduleResolution` to `bundler` and that fixed it, but also had to create a separate `tsconfig` for tests that had `moduleResolution: node` since jest wasn't happy with bundler.
