### ISSUE TITLE
No info how to implement animations

### ISSUE THREAD

**Issue by vitonsky** [chakra-ui/chakra-ui#9317]
### Description

I want to implement custom spinning animation, i can implement it with CSS, but i can't with chakra, since docs have no explanation how it works and does not have examples with code.

I tried to google about it and now i have this code that does not work

```tsx
// My theme is
export const basicTheme = extendTheme({
	keyframes: {
		spin2: {
			from: { transform: "rotate(0deg)" },
			to: { transform: "rotate(360deg)" },
		},
	},
});

// My JSX
<Box sx={{ animationName: 'spin2', animationDuration: '300ms' }}>
	<FaArrowsRotate />
</Box>
```

### Link to Reproduction

I can't found template for v2, but v3 does not have `extendTheme`

### Steps to reproduce

- Go to docs https://www.chakra-ui.com/docs/
- Try to find info how to add custom CSS animation and how to use it

Expected behaviour:
- Found some explanation how to add CSS animation and how to use custom animation for component

Actual behaviour:
- With search i can found 3 mentions about keyframes or animations, but they are inconsistent and deprecated so it does not work even with chakra v2 (docs does not exists for both v2 and v3)

### Chakra UI Version

2.8.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

It would be nice to add short section in docs with explanation how to work with CSS animations in Chakra

**Comment by Belco90** [comment]
I think this should be possible by using [`defineKeyframes`](https://github.com/chakra-ui/chakra-ui/blob/main/packages/react/src/theme/tokens/keyframes.ts) in combination with [`defineConfig`](https://www.chakra-ui.com/docs/theming/customization/overview#customization), although there is no reference to this in the official docs as you mentioned.

**Comment by segunadebayo** [comment]
I've updated the theme customization docs to cover how to do this.
See commit https://github.com/chakra-ui/chakra-ui/commit/6855a72eadc2ae0f9b9f30d4fee940f323ddc8c8
