### ISSUE TITLE
Request to add loading prop on Image

### ISSUE THREAD

**Issue by Andu033** [chakra-ui/chakra-ui#932]
**What problem does this feature solve?** 
This give you the option to set some images to load lazy.

**What does the proposed API look like?** Just add a prop lazy and forward this to the img tag that is rendered.

**Describe alternatives you've considered** I considered using img everywhere instead of Image.

**Additional context** Add any other context or screenshots about the feature
request here.
Here is a PR that did that but I dont know why this is not implemented now. The PR was merged.
https://github.com/chakra-ui/chakra-ui/pull/680

**Comment by with-heart** [comment]
The code from that PR was lost at some point during the 1.0 transition. Identical functionality should exist on `Image` in 1.0.

**Comment by Andu033** [comment]
@with-heart PR here https://github.com/chakra-ui/chakra-ui/pull/1012.
