### ISSUE TITLE
Failed to resolve import "@/components/ui/provider" from "src/main.jsx". Does the file exist?

### ISSUE THREAD

**Issue by pga5e** [chakra-ui/chakra-ui#9322]
### Description

https://www.chakra-ui.com/docs/get-started/frameworks/vite

following this guide, i installed chakra but am not using typescript am using js

so i didnt do this "Update tsconfig
If you're using TypeScript, in the tsconfig.app.json file, make sure the compilerOptions includes the following:

tsconfig.app.json

{
  "compilerOptions": {
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "skipLibCheck": true,
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
5
Setup Vite Config Paths
In your project, set up a vite config path to automatically sync tsconfig with vite using the command:

npm i -D vite-tsconfig-paths
Update the vite.config.ts file:

import react from "@vitejs/plugin-react"
import { defineConfig } from "vite"
import tsconfigPaths from "vite-tsconfig-paths"

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), tsconfigPaths()],
})"

now when i did hello world, i get this error: "Error: The following dependencies are imported but could not be resolved:

  @/components/ui/provider (imported by E:/Projects ALL/React Projects/DSA-React Problem Solving/src/main.jsx)

Are they installed?"
11:23:27 am [vite] Pre-transform error: Failed to resolve import "@/components/ui/provider" from "src/main.jsx". Does the file exist?
  Plugin: vite:import-analysis
  File: E:/Projects ALL/React Projects/DSA-React Problem Solving/src/main.jsx:1:25
  1  |  import { jsxDEV } from "react/jsx-dev-runtime";
  2  |  import { Provider } from "@/components/ui/provider";
     |                            ^
  3  |  import { StrictMode } from "react";
  4  |  import { createRoot } from "react-dom/client";

so why does @ always mesh up?

### Link to Reproduction

https://github.com/pga5e/JS-React-Problem-Solving

### Steps to reproduce

1. install chakra using javascript in vite
2. npm run dev will create error

### Chakra UI Version

latest

### Browser

Google Chrome Latest

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

[plugin:vite:import-analysis] Failed to resolve import "@/components/ui/provider" from "src/main.jsx". Does the file exist?

E:/Projects ALL/React Projects/DSA-React Problem Solving/src/main.jsx:1:25

1  |  import { jsxDEV } from "react/jsx-dev-runtime";
2  |  import { Provider } from "@/components/ui/provider";
   |                            ^
3  |  import { StrictMode } from "react";
4  |  import { createRoot } from "react-dom/client";

**Comment by thesohailjafri** [comment]
you did everything right. The documentation is not correct on website

use the following code in main.js

```javascript
// your-project/src/main.tsx/jsx
import { ChakraProvider, defaultSystem } from "@chakra-ui/react"
import { ThemeProvider } from "next-themes"
import React from "react"
import ReactDOM from "react-dom/client"
import App from "./App"

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <ChakraProvider value={defaultSystem}>
      <ThemeProvider attribute="class" disableTransitionOnChange>
        <App />
      </ThemeProvider>
    </ChakraProvider>
  </React.StrictMode>,
)
```

check the whole code reference from below link 
https://github.com/chakra-ui/chakra-ui/blob/main/sandbox/vite-ts/src/main.tsx

**Comment by thesohailjafri** [comment]
If you are using javascript then '@' wont work as its path alias is defined in `tsconfig.json` file. So use ../../../../ path
___
- you can  use ../../../../ but this gets really dirty in big project 
- and using ../../../../ wont be a problem if you use this approach in production apps

I hope I'm clear

**Comment by segunadebayo** [comment]
Please follow the guide here:
https://www.chakra-ui.com/docs/get-started/frameworks/vite#update-tsconfig

Set up `jsconfig.json` instead, if you're using JS.

**Comment by pga5e** [comment]
[Setup Vite Config Paths](https://www.chakra-ui.com/docs/get-started/frameworks/vite#setup-vite-config-paths)
In your project, set up a vite config path to automatically sync tsconfig with vite using the command:

      `npm i -D vite-tsconfig-paths`
Update the vite.config.ts file:

so if i am using Javascript: is there a **`vite-jsconfig-paths?`** so in case of js, is vite.configt.js is to be updated with code provided in the getting started or is code different?

**Comment by rebase-master** [comment]
> you did everything right. The documentation is not correct on website
> 
> use the following code in main.js
> 
> ```js
> // your-project/src/main.tsx/jsx
> import { ChakraProvider, defaultSystem } from "@chakra-ui/react"
> import { ThemeProvider } from "next-themes"
> import React from "react"
> import ReactDOM from "react-dom/client"
> import App from "./App"
> 
> ReactDOM.createRoot(document.getElementById("root")!).render(
>   <React.StrictMode>
>     <ChakraProvider value={defaultSystem}>
>       <ThemeProvider attribute="class" disableTransitionOnChange>
>         <App />
>       </ThemeProvider>
>     </ChakraProvider>
>   </React.StrictMode>,
> )
> ```
> 
> check the whole code reference from below link https://github.com/chakra-ui/chakra-ui/blob/main/sandbox/vite-ts/src/main.tsx

This worked for me. Thanks!
