### ISSUE TITLE
Incorrect Vite Project Get-Started Guide

### ISSUE THREAD

**Issue by thesohailjafri** [chakra-ui/chakra-ui#9323]
### Description

The documentation for the [Vite setup guide](https://www.chakra-ui.com/docs/get-started/frameworks/vite#setup-provider) on the Chakra UI website appears to have incorrect code in the Provider setup example. The documentation suggests using:

```javascript
import { Provider } from "@/components/ui/provider"
import React from "react"
import ReactDOM from "react-dom/client"
import App from "./App"

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <Provider>
      <App />
    </Provider>
  </React.StrictMode>,
)
```

However, in the previously provided setup, there is no reference to a ui/provider file or component. Instead, the correct setup directly uses ChakraProvider from @chakra-ui/react as follows:

```javascript
import { ChakraProvider, defaultSystem } from "@chakra-ui/react"
import { ThemeProvider } from "next-themes"
import React from "react"
import ReactDOM from "react-dom/client"
import App from "./App"

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <ChakraProvider value={defaultSystem}>
      <ThemeProvider attribute="class" disableTransitionOnChange>
        <App />
      </ThemeProvider>
    </ChakraProvider>
  </React.StrictMode>,
)
```

The incorrect example suggests a non-existent or unexplained custom provider (@/components/ui/provider), which could confuse developers following the guide. like it happened with [#9322](https://github.com/chakra-ui/chakra-ui/issues/9322)

### Link to Reproduction

https://www.chakra-ui.com/docs/get-started/frameworks/vite#setup-provider

### Steps to reproduce

Steps to Reproduce:

Visit the [Vite setup guide page](https://www.chakra-ui.com/docs/get-started/frameworks/vite#setup-provider).

Attempt to implement the given example code in a Vite project.

Observe that @/components/ui/provider is not part of the setup and results in an error.

Compare with the previously provided example which correctly uses ChakraProvider.

### Chakra UI Version

3.x.x

### Browser

Google Chrome 93

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

Please update the documentation to reflect the correct usage of ChakraProvider and remove or clarify the reference to @/components/ui/provider. This will help avoid confusion for new users following the Vite setup guide.

**Comment by segunadebayo** [comment]
The reference to snippets is mentioned before the provider setup. I'll update the docs to set up tsconfig before the `Provider`

https://www.chakra-ui.com/docs/get-started/frameworks/vite#add-snippets
