### ISSUE TITLE
[V1] `useColorMode` should return an object instead of an array

### ISSUE THREAD

**Issue by remorses** [chakra-ui/chakra-ui#933]
I think the change in the `useColorMode` is unnecessary and harmful: using an array does not add any benefit and will force a lot of people to change hundreds of lines in every project using chakra-ui

There are also many benefits on using an object over a tuple:
- Using an object let you use auto completion to more easily access the `colorMode` value.
- Using an object will let you add new possible fields to the `ColorModeContext` without needing to type every array element
- Using an object lets you access the `toggleColorMode` alone more easily:
```ts
const { toggleColorMode } = useColorMode()
const [_, toggleColorMode] = useColorMode()
```

**Comment by remorses** [comment]
I am happy to open a pull request if you don't want to implement it yourself

**Comment by segunadebayo** [comment]
I've just resolved this. Thanks for the feedback!
