### ISSUE TITLE
Error when adding the table snippet via chakra-cli

### ISSUE THREAD

**Issue by LordHub** [chakra-ui/chakra-ui#9347]
### Description

Currently I'm migrating my project to v3, so I have been adding the new Component using chakra-cli. I have been able to add a few of them but when I try to add the `table` component I get the following error. 
```
npx @chakra-ui/cli snippet add table
┌  Chakra CLI ⚡️
│
●  Adding 1 snippet(s)...
│
◇  Writing selected snippets
SyntaxError: Unexpected token < in JSON at position 0
```
What I realized is that unlike for other components like `menu`, there's no Setup section so this command is not on the page but I just assumed that this is how it should be added, but I might be in the wrong. 

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3?file=src%2FApp.tsx

### Steps to reproduce

Run the command: `npx @chakra-ui/cli snippet add table`

### Chakra UI Version

3.0.0

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Based on the docs. The table doesn't use a snippet, as seen in the docs
https://www.chakra-ui.com/docs/components/table
