### ISSUE TITLE
Why do many components have the same image in UI/components/overview.

### ISSUE THREAD

**Issue by barat-sh** [chakra-ui/chakra-ui#9354]
### Description

![image](https://github.com/user-attachments/assets/81feef9f-cb5c-44b8-bc2d-5b31135dc150)
can we have unique images for each components.

It will be easy for users to navigate and find.

Thanks

### Link to Reproduction

https://www.chakra-ui.com/docs/components/concepts/overview

### Chakra UI Version

3.0.0

**Comment by OmarDronodat** [comment]
I think this is the default image until they make one

**Comment by segunadebayo** [comment]
Closing based on https://github.com/chakra-ui/chakra-ui/issues/9354#issuecomment-2553490802
