### ISSUE TITLE
[v3] Recipe for Button is not working as expected

### ISSUE THREAD

**Issue by rohanmohapatra** [chakra-ui/chakra-ui#9355]
### Description

I have a recipe for creating a button

- Recipe
```
export const button = defineRecipe({
  base: {
    fontFamily: fonts.inter.style.fontFamily,
    px: "2rem",
    // cursor: "pointer",
  },
  variants: {
    brand: {
      navbar: {
        backgroundColor: "transparent",
        height: "8",
        color: "gray.500",
        _hover: {
          color: "gray.950",
        },
      },
  },
})
```

- Component
```
export const Button = chakra("button", button);
```

Now, the Button loses all it's inherent styles like `cursor: pointer`. Is this the right way to extend a theme? FYI, I am coming from v2 and I followed the Migration guide. The Migration Guide does not capture this.

### Link to Reproduction

..

### Chakra UI Version

3.0.0

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by rohanmohapatra** [comment]
FYI, I have a workaround as 

import { chakra, Button as ChakraButton } from "@chakra-ui/react";
export const Button = chakra(ChakraButton, buttonRecipe);

But this seems like a hack, is this the right way?

**Comment by pmredding** [comment]
@segunadebayo It looks like your linked example doesn't work. I updated it to pass in the customized system in the provider, but the typing still isn't correct.

**Comment by nsaunders** [comment]
> @segunadebayo It looks like your linked example doesn't work. I updated it to pass in the customized system in the provider, but the typing still isn't correct. Can you update it to show how the typing should be?

Agreed, it would be great to have your insight @segunadebayo. To add a custom variant, must be use a snippet to avoid a type error?
