### ISSUE TITLE
ContextError: useContext returned `undefined` when using NextJS React (19) installation

### ISSUE THREAD

**Issue by bmacer** [chakra-ui/chakra-ui#9357]
### Description

When following the [default React installation steps](https://react.dev/learn/start-a-new-react-project#nextjs-pages-router) and the [default Chakra UI steps](https://www.chakra-ui.com/), I observe the error:

```
ContextError: useContext returned `undefined`. Seems you forgot to wrap component within <ChakraProvider />
```

### Steps to reproduce

Create a new (React 19) project
```
npx create-next-app@latest
```
<default options - enter multiple times>
Change into directory and add Chakra-UI
```
cd my-app
npm install @chakra-ui/react
```
Replace /src/page.tsx with
```
import { Text } from "@chakra-ui/react";

export default function Home() {
  return (
    <Text>Hello World</Text>
  );
}
```
Start app
```
npm run dev
```
Navigate to http://localhost:3000/
Observe error:
```
ContextError: useContext returned `undefined`. Seems you forgot to wrap component within <ChakraProvider />
```

### Chakra UI Version

3.2.3

### Browser

Brave

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Workaround was to use NextJS 14.2.21
```
npx create-next-app@14.2.21
```

**Comment by segunadebayo** [comment]
You're most likely missing this step
https://www.chakra-ui.com/docs/get-started/installation#setup-provider

Please follow the docs as mentioned
