### ISSUE TITLE
Custom Breakpoints Are Merged with Default Breakpoints, Causing Issues with Array Syntax

### ISSUE THREAD

**Issue by nikolay-petrov-gj** [chakra-ui/chakra-ui#9386]
### Description

I'm using custom breakpoints for my project as follows:

```
import { createSystem, defaultConfig } from '@chakra-ui/react';

export const system = createSystem(defaultConfig, {
  theme: {
    breakpoints: {
      tablet: '768px',
      desktop: '1366px',
    },
  },
});
```

However, instead of replacing the default breakpoints, the custom breakpoints are concatenated with the default ones. This behavior causes issues when using the Array syntax for responsive design, as described in the [documentation](https://www.chakra-ui.com/docs/styling/responsive-design#array-syntax). The theme still includes all the default breakpoints, which makes it impossible to use only two breakpoints (tablet and desktop) as intended.

In Chakra UI v2, I could achieve the desired behavior by explicitly nullifying the default breakpoints and defining only the ones I needed, like so:

```
import { extendTheme } from '@chakra-ui/react';

export const theme = extendTheme({
  breakpoints: {
    base: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    '2xl': null,
    mobile: '0px',
    tablet: '768px',
    desktop: '1366px',
  },
});
```

This approach worked correctly in v2, but I couldn't find a way to replicate this behavior in the latest version.

### Expected Behavior
Custom breakpoints should completely replace the default breakpoints when defined, without merging them.

### Actual Behavior
Default breakpoints are still present in the theme alongside custom breakpoints, which creates conflicts when using Array syntax for responsive styles.

### Suggested Solution
Provide an option or method to entirely replace default breakpoints with custom ones without merging, as was possible in Chakra UI v2.

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-8bwgdzkm?file=src%2FApp.tsx

### Steps to reproduce

1. Define custom breakpoints using createSystem or similar methods.
2. Use Array syntax for responsive styles.
3. Observe that default breakpoints are still applied in the theme, causing unexpected behavior.

### Chakra UI Version

3.2.3

### Browser

Google Chrome 131.0.6778.205 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Thank you for your attention to this issue! Let me know if further clarification or a minimal reproduction example is needed.

**Comment by segunadebayo** [comment]
You can omit the `theme.breakpoints` from the `defaultConfig`

```tsx
import { createSystem, defaultConfig } from '@chakra-ui/react';
import { omit } from './omit';

const baseConfig = omit(defaultConfig, ['theme.breakpoints']);

export const system = createSystem(baseConfig, {
  theme: {
    breakpoints: {
      tablet: '768px',
      desktop: '1366px',
    },
  },
});
```

https://stackblitz.com/edit/chakra-ui-v3-jgs2qnzs?file=src%2Ftheme.ts,src%2FApp.tsx
