### ISSUE TITLE
[Select] Visual output is broken

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#939]
The `Select` component is not rendering the correct visual output. 

# Issues

- `div` container is not taking up full width of its parent, leading to dropdown icon overlap
  - cause: `props.isFullWidth` has no default, causing container to default to width of `auto`
  - v0 behavior: container always has width of `100%`
- `line-height` is cutting off letter descenders
  - cause: `line-height: 1`
  - v0 value: `line-height: normal`

# Screenshots 

You can see the issues at [next.chakra-ui.com/docs/form/select](https://next.chakra-ui.com/docs/form/select).

![image](https://user-images.githubusercontent.com/1954752/85469098-41564880-b57b-11ea-9676-a3fa89592b82.png)

This is in comparison to the existing `Select` docs:

![image](https://user-images.githubusercontent.com/1954752/85469029-2aaff180-b57b-11ea-9435-9aa8981793fd.png)

The "g" descender is cut off in this version, but it's so slight that you can hardly see it.

**Comment by skozer** [comment]
Another issue:

The icon wrapper inside Select has a `z-index` of 2, which stacks above modals in Chakra v1.
Likely due to this: https://next.chakra-ui.com/docs/z-index#chakra-portal-to-the-rescue

Does the icon wrapper need to have `z-index` set?
