### ISSUE TITLE
JSX is resolved to any with React 19

### ISSUE THREAD

**Issue by oceandrama** [chakra-ui/chakra-ui#9393]
### Description

There are a lot of JSX namespace using in the codebase, but in React 19 it has been moved into React namespace (https://react.dev/blog/2024/04/25/react-19-upgrade-guide#the-jsx-namespace-in-typescript)

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-2wmexhvf?file=src%2FApp.tsx,package.json

### Steps to reproduce

1. Go to App.tsx
2. Scroll down to line 20
3. See error

### Chakra UI Version

3.2.3

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
All references to JSX have been resolved by importing explicitly from React.JSX

Will do a release shortly
