### ISSUE TITLE
[Link] "href" prop is unspecified in Link props types

### ISSUE THREAD

**Issue by sukazavr** [chakra-ui/chakra-ui#94]
Hello!
TypeScript linter says that `Link` component has no `href` prop.
It seems like a mistake or mb I did smth wrong...

```
Type '{ children: string; href: string; }' is not assignable to type 'IntrinsicAttributes & ILink & IPseudoBoxProps & RefAttributes<HTMLElement> & HTMLAttributes<HTMLElement> & LayoutProps & ColorProps & SpaceProps<ReactText> & ... 15 more ... & { ...; }'.
  Property 'href' does not exist on type 'IntrinsicAttributes & ILink & IPseudoBoxProps & RefAttributes<HTMLElement> & HTMLAttributes<HTMLElement> & LayoutProps & ColorProps & SpaceProps<ReactText> & ... 15 more ... & { ...; }'.
```

My typescript config was initialized by CRA 3.1.1, mb there is smth wrong.

**Comment by segunadebayo** [comment]
Hi @sukazavr ,

It was an issue in the type definition. I've fixed this and will release a patch shortly.

Thanks.

**Comment by segunadebayo** [comment]
I've released a new version of Chakra that resolves this. Kindly upgrade
