### ISSUE TITLE
[CSSReset] Rules are defined multiple times with varying values

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#940]
There are a number of rules defined in `CSSReset` that are repeated, sometimes with different values each time. Due to the nature of the cascade, the resulting values may end up being the defaults we expect, but there's no need to define them twice.

An example of this is `html { line-height }`. It is defined on line 8 as `1.15`, then again on line 226 as `1.5`.

**Comment by segunadebayo** [comment]
Done!
