### ISSUE TITLE
[Tooltip] Timeouts for separate Tooltips are conflicting

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#943]
Strange behavior with `Tooltip` timeouts post-upgrade. It seems timeouts are not getting reset somewhere causing the following unexpected behavior with two icon buttons with tooltips:

![Peek 2020-06-23 16-16](https://user-images.githubusercontent.com/65664227/85378266-e3baff80-b56c-11ea-9da1-ec69587e0391.gif)

Notice the timeout of one `Tooltip` causes other tooltips to close. I believe this is a regression.

_Originally posted by @balibebas in https://github.com/chakra-ui/chakra-ui/issues/906#issuecomment-647987021_

**Comment by jmiazga** [comment]
I started to do some digging, and it seems like it was working up until this commit: 239007b

**Comment by segunadebayo** [comment]
@with-heart and @jmiazga, I'm working on this now.

Thanks for reporting this.

**Comment by segunadebayo** [comment]
Fixed this by reverting the logic back to v0. The library we depended on add some inconsistencies with timeouts.

In the future, we'll consider using a state machine for this tooltip.

**Comment by with-heart** [comment]
@segunadebayo Are you boarding the `xstate` train? 😁
