### ISSUE TITLE
Icons from `@chakra-ui/icons` throw missing `path` property error

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#946]
Use of icons from `@chakra-ui/icons` throwing type error:

> Property 'path' is missing in type '{}' but required in type ...

Reproduction: https://codesandbox.io/s/romantic-worker-u8ypi?file=/src/App.tsx

**Comment by segunadebayo** [comment]
This has been fixed, thanks to @ljosberinn's suggestion
