### ISSUE TITLE
[Input] Placeholder is missing in textfield

### ISSUE THREAD

**Issue by yfchiuaa** [chakra-ui/chakra-ui#949]
I am trying to create a form with #21CDFA background and <Input /> components, but the placeholder is missing. Here is my code:
![input_issues](https://user-images.githubusercontent.com/32567402/85492512-e0288680-b607-11ea-8416-ed9003304e7a.png)
And the output is like this:
<img width="486" alt="Screenshot 2020-06-24 at 10 43 52 AM" src="https://user-images.githubusercontent.com/32567402/85492456-c8510280-b607-11ea-8425-d92948c485b9.png">
The placeholder cannot be seen at all.

And the thing is that if I change the color of input to black, the placeholder is actually there:
<img width="486" alt="Screenshot 2020-06-24 at 10 47 14 AM" src="https://user-images.githubusercontent.com/32567402/85492644-149c4280-b608-11ea-8ba6-dfbea17d4269.png">

Is it the problem of my code or something with the Input components? Thanks!

**Comment by with-heart** [comment]
Hi @yfchiuaa, could you reproduce the issue in codesandbox for us please?

**Comment by chetan-2002** [comment]
Hey @yfchiuaa, I am facing the same issue, can you please help me to resolve it!
Thanks!

**Comment by JoelAngels** [comment]
The placeholder of an input can be styled by using the _placeholder prop. Per default the placeholder has an opacity of 0.6, so it can be necessary to set the opacity to 1 if you want the placeholder to have a specific color.

like this

  <Input
    placeholder='custom placeholder'
    _placeholder={{ opacity: 1, color: 'gray.500' }}
  />
