### ISSUE TITLE
[Examples] Unable to render Application after initial build

### ISSUE THREAD

**Issue by cachemoney** [chakra-ui/chakra-ui#950]
I am using Node 12.2.0. After cloning both nextJS example project folders, and running npm install, I see that there are quite a few of peer dependencies that need to be downloaded.  Is the current examples using a beta version for nextjs?  Any ideas how I could resolve this?

**Comment by with-heart** [comment]
Hi @cachemoney, the current version is using an alpha version of 1.0. The packages are set for a peer dependency to `@1.x` packages but everything is currently published under `@1.0.0-next.x`. This should be resolved once we've released 1.0.
