### ISSUE TITLE
Current docs and components are out of sync and broken. Installed version does not reflect current docs.

### ISSUE THREAD

**Issue by jackblackCH** [chakra-ui/chakra-ui#951]
Firstly, as a user, it's not obvious that you are installing a beta/new/next version but the current online docs are not fully reflecting them. Sadly, many code snippets and props and components simply don't work and it's quite hard to figure out that there are many breaking changes. 

**Please always update the docs acordingly when adding breaking changes**, it's not obvious and and it is super frustrating to run into these errors while using a new framework.

**At least, I highly recommend you to highlight the exact version on docs pages and add a warning/banner that the users is maybe looking to an outdated or old version**. The current state "in between" is super frustrating.

PS: I am a huge supporter of Chakra, so I write this with the intention of not frustrating any more new and existing users.

Some issues/suprises i run into
- Theming, ChakraProvider vs ThemeProvider
- Undocumented light and dark mode
- Override of {...theme.colors} -> new concept. very surprising
- Skeleton (broken)
- Button Variants
  - Many new props

**Comment by aaronmcadam** [comment]
The current documentation is for [version `0.8` of Chakra](https://github.com/chakra-ui/chakra-ui/releases/tag/%40chakra-ui%2Fcore%400.8.0).

The documentation for [the next release](https://github.com/chakra-ui/chakra-ui/releases/tag/%40chakra-ui%2Fcore) is currently deployed at https://next.chakra-ui.com/.

**Comment by balibebas** [comment]
As a counter point, the majority of users using Chakra and needing to reference the docs still need the old documentation. If you need access to the new docs I found cloning Chakra UI and running `docs:start` script from the package manifest works quite well. Personally I'd rather see the new version polished before the docs.

**Comment by aaronmcadam** [comment]
The next release is still in beta. It's been published for users to test. I would not expect the majority of users to upgrade yet.

**Comment by aaronmcadam** [comment]
However, if you do notice problems with the new documentation, please report them here: https://github.com/chakra-ui/chakra-ui/issues/906

**Comment by with-heart** [comment]
I see the problem. The `@chakra-ui/core` is installing the alpha version and should not be.

**Comment by jackblackCH** [comment]
Oh I see, yes. For any new user who is blindly copying the commands, this leads into a lot of frustration. A quickfix could be to add the versions to the npm installs to the the README #953
