### ISSUE TITLE
[ButtonGroup] documentation is missing

### ISSUE THREAD

**Issue by aaronmcadam** [chakra-ui/chakra-ui#952]
I use `ButtonGroup` all the time, but it's not on the documentation site. Have we just not gotten around to documenting it? Are we thinking about removing it?

**Comment by with-heart** [comment]
It still exists, I think it was just missed :)

**Comment by aaronmcadam** [comment]
Great, thanks @with-heart :)

**Comment by segunadebayo** [comment]
Done with this. Thanks for the reminder @aaronadamsCA

**Comment by DewinP** [comment]
`ButtonGroup` documentation is missing as of version 1.0. Is it getting deprecated?

**Comment by with-heart** [comment]
@DewinP https://chakra-ui.com/docs/form/button#grouping-buttons

**Comment by alyzidan** [comment]
Still missing until this ver day !
