### ISSUE TITLE
Package `@chakra-ui/core` is installing `1.0.0-next.2`

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#953]
I don't think this is intentional, but the `@chakra-ui/core` package is pointing to the alpha version while it should still be pointing to `0.8.0`. Reported in #951.

**Comment by segunadebayo** [comment]
I made a mistake on this one. I'm not sure how to revert this, to be honest.

We'll have to update the v0 docs to let the new users know about this.

**Comment by aaronmcadam** [comment]
> I made a mistake on this one. I'm not sure how to revert this, to be honest.
> 
> We'll have to update the v0 docs to let the new users know about this.

You may have to reach out to [NPM support](https://www.npmjs.com/support) to get them to unpublish those versions. They've done it for me in the past.

**Comment by with-heart** [comment]
We were able to fix this using `npm dist-tag add @chakra-ui/core@0.8.0 latest`!
