### ISSUE TITLE
Add alpha version banner to next.chakra-ui.com

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#954]
Suggested in #951, this would help make it apparent to users that the documentation they're looking at is for the alpha version.

**Comment by jmiazga** [comment]
@with-heart Do you have a design in mind for this?

**Comment by with-heart** [comment]
I played around with this a bit and it's actually kind of a pain to integrate with our current header. I'm going to close this and we can revisit if it's really a problem.
