### ISSUE TITLE
[Menu] `placement` prop has moved from `MenuList` to `Menu`

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#959]
`website/docs/components/menu.mdx` lists `placement` as a prop on `MenuList`, but it is now a prop on `Menu` itself.

- [ ] Move the prop from `MenuList` props table to `Menu` props table
- [ ] Add note about prop move to `website/docs/migration.mdx`

**Comment by segunadebayo** [comment]
Done!
