### ISSUE TITLE
Documentation error in PseudoBox

### ISSUE THREAD

**Issue by rohmanhm** [chakra-ui/chakra-ui#96]
I just wanted to tell you that you have a documentation error on `Pseudobox`

![image](https://user-images.githubusercontent.com/7524911/65196622-94f6ab80-daaa-11e9-9de8-2c6167aa003d.png)

**Comment by rohmanhm** [comment]
URL: https://chakra-ui.com/pseudobox

**Comment by segunadebayo** [comment]
Hi @rohmanhm , I can't seem to see this issue on my end.

Can you confirm that you didn't edit the code before it showed this error?

**Comment by rohmanhm** [comment]
I'm not editing anything, just scrolling through pages.
I believe it's fixed with your latest commit to master.
