### ISSUE TITLE
Integrate with Chromatic

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#960]
This a placeholder issue for integrating with Chromatic. https://www.chromatic.com/

Chromatic comes with a lot of features, but we'd really like the functionality around visual testing, so we can guarantee that changes made to the codebase don't cause visual regressions.

**Comment by with-heart** [comment]
I've reached out to Chromatic about the open source plan, so hopefully once we get 1.0 launched, we can work on setting up Chromatic as part of our workflow and pipeline. This will give us far more mileage than our snapshot tests ever could. 

Once I hear back from them, I'll start to formulate a plan for how to set things up and how to proceed from where we are now.

**Comment by segunadebayo** [comment]
Let's discuss this later today, @with-heart. I think we can drop this for now to keep our processes as simple as possible.

We already have a lot going on in the code, CI pipelines and so on. This is more of a "less is more" decision.

**Comment by with-heart** [comment]
@segunadebayo Someone else pointed out in Discord at one point that we'd probably end up going over the free tests they provide for open source projects, so it may not be worth it anyway. Worth talking about though!
