### ISSUE TITLE
`theme.typography.fontWeights` cannot be used with `fontWeight` prop

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#962]
The `fontWeight` prop is throwing a type error when used with the names defined in `theme/foundations/typography.ts`. This applies whether it's used with `chakra` or a defined component like `Text` or `Heading`. The weights all appear to be working fine however.

Reproduction: https://codesandbox.io/s/silly-ellis-zu8e6?file=/src/App.tsx

**Comment by segunadebayo** [comment]
I've updated the types for fontWeight to `string` for now. It's challenging to figure out the types based on what's in the theme.

Thanks for this.
