### ISSUE TITLE
Cannot scroll hamburger menu nav on iPhone

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#966]
The hamburger menu can be opened on iPhone but cannot be scrolled.

**Comment by segunadebayo** [comment]
Might be related to: https://github.com/willmcpo/body-scroll-lock/issues/184

**Comment by with-heart** [comment]
Seems like it. Looks like there's [a PR open since September 2019](https://github.com/willmcpo/body-scroll-lock/pull/133) to fix the issue.

**Comment by saptaksengupta** [comment]
I would like to work on it, if it's already not in progress. @sebqq @with-heart

**Comment by with-heart** [comment]
@saptaksengupta Please! If you're not able to get this working with `body-scroll-lock`, @segunadebayo had mentioned switching to https://github.com/jossmac/react-scrolllock instead, which `@reach/ui` uses.

**Comment by segunadebayo** [comment]
Hi @saptaksengupta, I'm excited to see you're willing to help. Thank you

@with-heart, I've updated the code to use react-remove-scroll which should solve this problem, I believe.

@saptaksengupta, please feel free to contribute on other issues, I'm happy to help too.

**Comment by with-heart** [comment]
@segunadebayo I'll get that deployed so some friends can confirm this is working now

**Comment by saptaksengupta** [comment]
no problem @segunadebayo. cool 👌
