### ISSUE TITLE
Color prop inconsistency

### ISSUE THREAD

**Issue by jestrux** [chakra-ui/chakra-ui#97]
Hi @segunadebayo @mattrothenberg 

I thought I'd create a separate issue for this so we can track ideas a bit better.

_Originally posted by @segunadebayo in https://github.com/chakra-ui/chakra-ui/pull/92#issuecomment-532425620_

**Comment by jestrux** [comment]
I was wondering if we could create a Color type so that all color props can be of that type.

The Color type will then be compatible with either `aquawhite` or `blue.500` or `rgba(34,56,21)` or `#555` and `#F34477`.

The one issue I'm having with this is how to make sure that it can correctly provide compile time errors when someone enters a theme color that doesn't exist e.g. `amber.300`

**Comment by mattrothenberg** [comment]
@jestrux Cool idea!

I'm curious if we're working against the grain of a type system by allowing all of these values to match the `color` type:

- `aquaWhite` (CSS color value)
- `blue.500` (Unique key from Chakra color them)
- `rgba(34,56,21)` (CSS rgba value)
- `#555` (CSS 3 digit HEX)
- `#F34477` (CSS 6 digit HEX).

If the issue is being able to provide compile time errors around incorrect color values, would it make more sense to express those values as some kind of constant that could be imported and used in a component, e.g.,

```jsx
import { Colors, Box } from '@chakra-ui/core'

const RandomComponent = () => (
  <Box bg={Colors.Blue200} color={Colors.Blue700} />
)
```

Food for thought!

**Comment by jestrux** [comment]
@mattrothenberg So I was thinking of a very similar idea, 

Except for one thing, I really like something @segunadebayo said in the previous feed that we should allow the user to enter the color they want. 

I feel like that way they won't bee too tightly bound by the theme color system we set up if they don't want to use it. So I was thinking of something more like:

- `aquaWhite` would be `Color.byName('aquaWhite')`

- `rgba(34,56,21)` could be `Color.fromRgba('34,56,21')`

- `#F34477` would be `Color.fromHex('#F34477')`

- `Color.fromHex('#555')` could throw an error saying six characters required

- `blue.500` would be like you suggested `Colors.Blue500`

where `Colors` would just be a static constant based on the `Color` type

**Comment by mattrothenberg** [comment]
Oh, I think a user should absolutely be able to pass a color string of
their choice, as long as it's a string.

I think the `fromHex` function (or its counterparts) adds additional
complexity to the API, while not adding a ton of value. A string is a
string is a string at the end of the day.

My two cents!

**Comment by jestrux** [comment]
Oh okay,

Let me see if I get your point correctly, if a user wants to use some color of their own, let them. But in case they want to use the colors from the theme then they should import *`Colors`* and use that.

Is this what you meant?

**Comment by mattrothenberg** [comment]
Yup, exactly!

My suggestion was in response to your question about how you can prevent
users from picking the wrong color value from the underlying theme.

**Comment by jestrux** [comment]
Yeah, this makes sense.

As long as we give the user freedom of choice while at the same time being able to prevent them from picking a  nonexistent color from the theme, it should be okay.

I'm sure either you or @segunadebayo or whoever else picks this up should have a much easier time implementing this into the color props.

**Comment by Philzen** [comment]
I've noticed that adding a raw color ad-hoc (as described in https://chakra-ui.com/docs/styled-system/features/style-props#color-and-background-color) does not work in `rgb(...)` and `rgba(...)` style – at least when trying to define it in the `endColor` of a Skeleton. Any ideas?
