### ISSUE TITLE
[Box] Size property on box not working

### ISSUE THREAD

**Issue by HadiSDev** [chakra-ui/chakra-ui#976]
**Describe the bug** A clear and concise description of what the bug is.

Setting size to anything on box property (or actually any component, I tried with Image as well) does not do anything

See codesandbox

**Link to minimal reproduction** Please provide a codesandbox link or GitHub
repo with a minimal reproduction of the issue.
https://codesandbox.io/s/reverent-carson-y6bk2?file=/src/App.tsx

**Comment by segunadebayo** [comment]
Hey @HadiSDev,

Like I mentioned on Discord, the `size` prop has been deprecated in favor of `w` and `h`, or `boxSize` prop.

Please refer to the migration docs here: https://next.chakra-ui.com/docs/migration
