### ISSUE TITLE
Accordion headers need type="button"

### ISSUE THREAD

**Issue by eranimo** [chakra-ui/chakra-ui#98]
Currently they use PseudoBox and they don't define the `type` prop, which makes them submit forms if Accordion is used inside a <form> element. Also, the PseudoBox Typescript definitions don't include the `type` prop.

**Comment by segunadebayo** [comment]
Thanks for catching this @eranimo ,

I'll update the AccordionHeader component soon and release a patch.

**Comment by segunadebayo** [comment]
I've released a new version of Chakra that resolves this. Kindly upgrade

**Comment by kibs** [comment]
Hi, I just upgraded to v1 (next) and it seems like type="button" was not added to the AccordionButton component

**Comment by ljosberinn** [comment]
@kibs thanks, I'll create a separate issue since this is slightly different, should be an easy fix
