### ISSUE TITLE
[Text] Text is not centering vertically in Firefox browser

### ISSUE THREAD

**Issue by lamualfa** [chakra-ui/chakra-ui#983]
**Describe the bug**

Text is not centering vertically in Firefox browser (Text **NEW** with cyan background).

### With Firefox Browser 77.0.1 

![image](https://user-images.githubusercontent.com/39755201/85753690-aace8680-b736-11ea-8c7d-1e18f30d1017.png)

### With Chrome Browser 83.0

![image](https://user-images.githubusercontent.com/39755201/85754004-eec18b80-b736-11ea-887f-a0a2d9b6b1f4.png)

**Expected Behavior** 

The Text is in the center of the box on all browsers.

**Link to minimal reproduction**

This is not my code, but this is from the chakra-ui.com website. See: https://chakra-ui.com/box#usage-1

**Desktop (please complete the following information):**

- OS: Debian 10 (Buster)
- Browser:
  - Firefox 77.0.1 
  - Chrome 83.0

**Comment by santialbo** [comment]
<img width="397" alt="Screenshot 2020-06-26 at 15 04 50" src="https://user-images.githubusercontent.com/1557563/85860065-71415e00-b7be-11ea-8005-46d34e7b8012.png">

From Firefox 77.0.1 on Mac, could it be the default Debian font?

**Comment by la55u** [comment]
I experience the same issue and not just here, some of the components are not aligned properly. From the docs, notice how the text is not centered:

![image](https://user-images.githubusercontent.com/30611343/85920507-a27c6580-b874-11ea-9c2e-a15f3abd4cc5.png)

**Comment by with-heart** [comment]
@lamualfa @la55u Could one of you verify that you're seeing the same issue on https://next.chakra-ui.com/?

**Comment by la55u** [comment]
@with-heart Yes, both checkbox and OP's badge example is off there too.

**Comment by lamualfa** [comment]
@santialbo Yes, I guess it's a matter of the font used. Default font system makes the text position is not in the middle. I have tested using both different fonts. Here is the Pen: https://codepen.io/laodemalfatih/pen/oNbGeqq

**Comment by lamualfa** [comment]
To fix this issue, you can try to change the default font with a font that doesn't have this problem. For example like: `sans-serif`, [Roboto](https://fonts.google.com/specimen/Roboto), etc.

**Comment by with-heart** [comment]
For future reference, it appears that Firefox calculates `align-items: baseline` differently from other browsers, and expects `inline-flex` rather than `flex` on the containing element.
