### ISSUE TITLE
Recommended way to use an inline select/input?

### ISSUE THREAD

**Issue by kevholder** [chakra-ui/chakra-ui#989]
What is the recommended way to use inline select/input? I tried `<Select placeholder="Order by..." size="sm" display="inline" width="auto">` but it seems the `width` prop becomes `100%`.

**Comment by segunadebayo** [comment]
@kevholder,

I'd recommend you wrap the select in a `Box` and control the width from there to match your design requirements.

This has been fixed in v1 so consider this a temporary solution.

Thanks
