### ISSUE TITLE
[Breadcrumb] Example with Routing Library

### ISSUE THREAD

**Issue by brennj** [chakra-ui/chakra-ui#99]
Hello!

I was struggling trying to use the Breadcrumb component using a Library like `@reach/router`. I have tried wrapping the `BreadcrumbLink` in a `Link` from Reach so that it can use its routing system and not reload the page in a SPA. But the problem is, the last child won't behave as intended where it shouldn't render an `a` tag. 

I have made some examples of different solutions but wanted to know am I doing the right thing here. From using the library a couple of days it is where I personally found the most friction trying to get my head around this awesome library. Maybe some examples using reach could be provided?

Heres a link to my messing about:
https://codesandbox.io/s/naughty-chandrasekhar-yq2ez?fontsize=14

Thoughts would be welcome or letting me know if I'm doing it totally wrong!

**Comment by segunadebayo** [comment]
Hi @brennj,

I checked the link and played a bit with the examples. I think you need to use the `as` prop to internal replace the component used in `BreadcrumbLink` from `a` to Reach's `Link`.

```jsx
<Breadcrumb>
      <BreadcrumbItem>
        <BreadcrumbLink as={Link} to="/">
          Home
        </BreadcrumbLink>
      </BreadcrumbItem>
      <BreadcrumbItem>
        <BreadcrumbLink as={Link} to="/about">
          About
        </BreadcrumbLink>
      </BreadcrumbItem>
      <BreadcrumbItem isCurrentPage>
        <BreadcrumbLink to="/contact">Contact</BreadcrumbLink>
      </BreadcrumbItem>
    </Breadcrumb>
```

For the last child, you might need to omit the `as={Link}`. If you choose to still use it, then here's what you can do:
- Style it so it doesn't look like a link
- Set its `tabIndex` to `-1` so the keyboard can't reach it
- Set its `pointerEvents` to `none`

Here's the link to the sandbox: https://codesandbox.io/s/small-bush-un9r8?fontsize=14

Hope this helps.
