### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by brennanfife** [chakra-ui/chakra-ui#991]
Thought I had seen a post a few weeks ago regarding the roadmap of this library. Seems like this [link](https://github.com/chakra-ui/chakra-ui/blob/master/ROADMAP.md) is down. Is this temporarily down during the transition to v1?

**Comment by with-heart** [comment]
You might be thinking of #696 for the post.

At some point along the way, `ROADMAP.md` was deleted. I think right now the only real roadmap item we have is getting 1.0 released. Once we get to that point, we can start thinking about the future again :)

**Comment by with-heart** [comment]
Trying to clean up our issues backlog so I'm going to close this. If you have any feedback to share on roadmap ideas or something, feel free to reply or create a new issue!

**Comment by jsefiani** [comment]
Hey guys, is it possible to share your roadmap publicly? Something like Material UI? 
https://material-ui.com/discover-more/roadmap/

**Comment by with-heart** [comment]
@jsefiani Your question implies that we have a roadmap 😆 

It's something we're working on. The roadmap for longest time was basically just "finally release v1", and it's taking us a bit to regroup and organize for the future. We've been coming up with a general direction of where we're heading over the last week or two, so when we have something more concrete, we'll definitely share it with the community.
