### ISSUE TITLE
[gatsby-plugin-chakra-ui] Update the 1.0 installation documentation

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#996]
The documentation for installing gatsby-plugin-chakra-ui are outdated at the moment, FYI. Following the instructions causes the plugin to be installed at version 1.0.0-next.2, but the other dependencies at 0.8.0.

_Originally posted by @jhthenerd in https://github.com/chakra-ui/chakra-ui/issues/906#issuecomment-650481876_

**Comment by segunadebayo** [comment]
Done!
