### ISSUE TITLE
[Skeleton] `colorStart`, `colorEnd`, and `isLoaded` props aren't working as expected

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#997]
Seems like the `Skeleton` component is not working as documented [here](https://next.chakra-ui.com/docs/components/skeleton). `colorStart`, `colorEnd` and `isLoaded` props don't seem to be working. Also it seems the `isLoaded` prop is throwing errors on TypeScript:

```
Property 'isLoaded' does not exist on type 'IntrinsicAttributes & Pick<(Pick<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>
```

_Originally posted by @divyanshu013 in https://github.com/chakra-ui/chakra-ui/issues/906#issuecomment-649639556_

**Comment by segunadebayo** [comment]
We've renamed the props from `colorStart` and `colorEnd` to `startColor` and `endColor`.

I've reverted the skeleton prop from `hasLoaded` back to `isLoaded`.

I've updated the migration guide as well.
